### ISSUE TITLE
Package request: fastfetch

### ISSUE THREAD

**Issue by MatcraftouOff** [NixOS/nixpkgs#240931] opened 2023-07-01 15:29 UTC
Introduction:

Since neofetch is no longer developped, another developper made fastfetch, it is an up-to-date alternative to neofetch that is faster because it is developped in C instead of Shell

----------------------------------------------------------------------------------------------------------------

Project description:
Like neofetch, but much faster because written in C. 

----------------------------------------------------------------------------------------------------------------

Metadata:

* homepage URL: none
* source URL: https://github.com/fastfetch-cli/fastfetch
* license: mit
* platforms: unix, linux, android, windows, macos....

----------------------------------------------------------------------------------------------------------------

*_Have a good day_*

**Comment by figsoda** [comment] 2023-07-01 16:33
duplicate of #176799

**Closed** 2023-07-01 16:33 UTC
Labels: 2.status: duplicate, 0.kind: packaging request
