### ISSUE TITLE
Viber 18.2.0.2

### ISSUE THREAD

**Issue by icyrockcom** [NixOS/nixpkgs#193394] opened 2022-09-28 20:53 UTC
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
https://github.com/NixOS/nixpkgs/commit/3e913ac64c178b83e17068513c8d4d2d08b22aec

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)
https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+is%3Aopen+viber

###### Project name
`nix search` name:

current version: 16.1.0.37 https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/networking/instant-messengers/viber/default.nix#L9
desired version: 18.2.0.2

###### Notify maintainers

maintainers: @jagajaga 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by SimonBrandner** [comment] 2023-07-12 07:54
I've just had a go at updating the package though when actually running it I get

```shell
(viber:354492): GStreamer-CRITICAL **: 09:52:43.560: gst_element_link_many: assertion 'GST_IS_ELEMENT (element_2)' failed
zsh: segmentation fault (core dumped)  ./result/bin/viber
```

and I am not really sure how to resolve that. Internet seems to suggest the issue is in the app though it seems to work fine on Debian

**Comment by SimonBrandner** [comment] 2023-07-12 11:39
FWIW, I made a [PR with my changes](https://github.com/NixOS/nixpkgs/pull/243057). Perhaps someone else is more lucky

**Comment by onny** [comment] 2024-08-24 07:19
Viber already updated to a more recent version, closing this

**Closed by onny** 2024-08-24 07:19 UTC
Labels: 9.needs: package (update)
