### ISSUE TITLE
linux-5.10.17 nvidia modules build failed

### ISSUE THREAD

**Issue by astrojhgu** [NixOS/nixpkgs#114075] opened 2021-02-23 05:28 UTC
**Describe the bug**

Upgrading failed caused by a building failure of linux 5.10.17 module

**To Reproduce**
```
sudo nixos-rebuild boot --upgrade
```

**Expected behavior**
`nixos-rebuild` command exit normally

**Screenshots**
![image](https://user-images.githubusercontent.com/2651231/108805255-a4045600-75da-11eb-9f3f-305a8884d6a6.png)
![image](https://user-images.githubusercontent.com/2651231/108805301-c007f780-75da-11eb-87b3-19c241d86239.png)

**Additional context**
Here are the error message copied from my terminal window:
```
/build/kernel/nvidia/nv-mmap.c:334:16: warning: this statement may fall through [-Wimplicit-fallthrough=]
  334 |             if (NV_ALLOW_CACHING(memory_type))
      |                ^
/build/kernel/nvidia/nv-mmap.c:336:9: note: here
  336 |         default:
      |         ^~~~~~~
/build/kernel/nvidia/nv-dma.c: In function 'nv_dma_is_map_resource_implemented':
/build/kernel/nvidia/nv-dma.c:631:37: error: implicit declaration of function 'get_dma_ops' [-Werror=implicit-function-declaration]
  631 |     const struct dma_map_ops *ops = get_dma_ops(dma_dev->dev);
      |                                     ^~~~~~~~~~~
/build/kernel/nvidia/nv-dma.c:631:37: warning: initialization of 'const struct dma_map_ops *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
/build/kernel/nvidia/nv-dma.c:646:16: error: dereferencing pointer to incomplete type 'const struct dma_map_ops'
  646 |     return (ops->map_resource != NULL);
      |                ^~
/build/kernel/nvidia/nv-dma.c:650:1: error: control reaches end of non-void function [-Werror=return-type]
  650 | }
      | ^
```
**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
- system: `"x86_64-linux"`
 - host os: `Linux 5.9.16, NixOS, 20.09.2812.f18fbc33930 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by heroku-miraheze** [comment] 2021-02-23 09:58
Duplicate of #113963

**Comment by SCOTT-HAMILTON** [comment] 2021-02-24 10:08
Would be helpful if we had at least `boot.kernelModules`.

**Comment by noonien** [comment] 2021-02-28 20:33
This also stops me from upgrading my system. What information should I post for more info?
```
$ nix-run nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.16, NixOS, 20.09.20210120.da3378c (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`
 - channels(root): `""`
 - channels(george): `""`
 - nixpkgs: `/run/current-system/nix-channels/nixpkgs`
````

```
boot.kernelPackages = pkgs.linuxPackages_latest;
services.xserver = {
    useGlamor = true;
    videoDrivers = [ "nvidia" ];
};
```

If any more info is required, I'm happy to provide it.

**Comment by astrojhgu** [comment] 2021-03-01 01:47
> Would be helpful if we had at least `boot.kernelModules`.

```
boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.tmpOnTmpfs = true;
  boot.extraModulePackages = [ config.boot.kernelPackages.acpi_call ];
  boot.kernelModules = ["acpi_call" "coretemp" ];
  console.earlySetup = true;
```

**Comment by astrojhgu** [comment] 2021-03-10 03:52
I switch my `boot.kernelPackages` back to `pkgs.linuxPackages` from `pkgs.linuxPackages_latest`, then the upgrade succeeded.

Originally I used the latest kernel to ensure that all the devices are driven, not it seems that the default kernel version has already been OK.

**Comment by breuerfelix** [comment] 2021-04-19 08:31
I need the 5.10 Kernel for my AMD 5600 CPU (which adds support like reading out temperature).  
Is there a fix around to use nvidia + latest kernel ? @astrojhgu is just downgrading his kernel version which is not what i want.

**Comment by eamsden** [comment] 2021-04-20 18:20
This seems specific to the 5.10 kernel. I've just built and started running the 5.11 kernel in nixpkgs-unstable and there was no build issue.

**Comment by breuerfelix** [comment] 2021-04-21 05:56
@eamsden i tried the same and nvidia also failed. but i am using the kernel from 20.09 repos, maybe i should try the unstable 5.11 :)

**Comment by rycee** [comment] 2021-09-29 08:58
There have been multiple module updates since then, perhaps works now?

**Comment by r-burns** [comment] 2021-10-14 06:36
Yep, closing as I'm using the nvidia module on 5.13

**Closed by r-burns** 2021-10-14 06:36 UTC
Labels: 0.kind: bug, 6.topic: kernel
