### ISSUE TITLE
Plasma - Rendering is incorrect for many settings in "System Settings" panel

### ISSUE THREAD

**Issue by Elyhaka** [NixOS/nixpkgs#80351] opened 2020-02-17 13:06 UTC
## Bugs

It seems that the system settings are not displaying correctly. I will present here the differences between ArchLinux and NixOS with a vanilla theme (Breeze light).

At a first glance, the main components affected seem to be QML UIs.

#### NixOS

```
Operating System: NixOS 20.03pre212208.8130f3c1c2b
KDE Plasma Version: 5.17.5
KDE Frameworks Version: 5.66.0
Qt Version: 5.12.6
Kernel Version: 5.5.2
OS Type: 64-bit
Processors: 8 × AMD Ryzen 7 PRO 3700U w/ Radeon Vega Mobile Gfx
Memory: 21,5 GiB of RAM
```

#### ArchLinux

```
Operating System: Arch Linux 
KDE Plasma Version: 5.17.5
KDE Frameworks Version: 5.67.0
Qt Version: 5.14.1
Kernel Version: 5.5.2-arch1-1
OS Type: 64-bit
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 15,5 Gio
```

### Global theme duplicated with duplicates not working correctly

![Screenshot_20200217_133453](https://user-images.githubusercontent.com/57923898/74654351-69c3d580-518a-11ea-9283-cd9f0899f6da.png)

The themes are presented multiple times (Breeze and Breeze Dark) but only one of each is working properly.

### The UI to manage displays is broken

The UI seems broken, when we "force scroll" we can see some hidden content appearing from overscrolling. The UI to select screen placement is also not working properly, as shown here :

ArchLinux :

![photo_2020-02-17_13-39-46](https://user-images.githubusercontent.com/57923898/74654656-1aca7000-518b-11ea-8ee8-ef5f87766163.jpg)

NixOS : 

![Screenshot_20200217_133710](https://user-images.githubusercontent.com/57923898/74654456-9b3ca100-518a-11ea-9aee-6aee55c80c34.png)

### Some UI elements have lost their theme, making them difficult to use

Some elements are not drawn correctly and are unusable because of this. For instance, see following screenshots:

ArchLinux :

![Bug2](https://user-images.githubusercontent.com/57923898/74655640-fa9bb080-518c-11ea-96e3-e6bf46e00037.png)

NixOS :

![Screenshot_20200217_134534](https://user-images.githubusercontent.com/57923898/74655231-56196e80-518c-11ea-8b77-68a8332f4877.png)

Those issues degrade the experience a lot when using the Plasma Desktop Environement under NixOS. Let me know if I can provide any more information or help to track down those issues.

**To Reproduce**
1. Enable plasma with the following default configuration :

```
services.xserver = {
  displayManager.sddm.enable = true;
  desktopManager.plasma5.enable = true;
}
```

**Expected behavior**

It should display as closely as possible as the reference screenshot for ArchLinux.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.2, NixOS, 20.03pre212208.8130f3c1c2b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03pre212208.8130f3c1c2b"`
 - channels(ely): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:

cc @worldofpeace @ttuegel

**Comment by ttuegel** [comment] 2020-02-17 13:29
Duplicate of #79713

**Closed by ttuegel** 2020-02-17 13:29 UTC
Labels: 0.kind: bug
