### ISSUE TITLE
Overriding user-agent used by fetchurl

### ISSUE THREAD

**Issue by sikmir** [NixOS/nixpkgs#90034] opened 2020-06-10 09:19 UTC
**Describe the bug**
I'm trying to override User-Agent header used by **fetchurl** (#17757) using:
```
curlOpts = "--user-agent 'Mac OS X'";
```
That leads to:
```
curl: (28) Resolving timed out after 15001 milliseconds
curl: (6) Could not resolve host: X'
curl: (22) The requested URL returned error: 404 Not Found
```
That's caused by whitespaces in the 'Mac OS X' string, otherwise it works correctly (e.g. with 'Mac_OS_X').

**Comment by lheckemann** [comment] 2020-06-11 12:16
I'm not sure this can be worked around with the way fetchurl is currently implemented: https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchurl/builder.sh#L20

This could be avoided with the help of structuredAttrs, but that work isn't complete yet.

**Comment by gdamjan** [comment] 2020-09-22 11:47
shouldn't be enough to just add quotes around `$curlOpts` here:

https://github.com/NixOS/nixpkgs/blob/06b27898a4563ef2e0e653fd78f76b77c31820ff/pkgs/build-support/fetchurl/builder.sh#L26

**Comment by gdamjan** [comment] 2020-09-22 12:01
[replying to myself] obviously not. since then the two strings in `"--user-agent 'Mozilla 5.0'"` are considered a single argument given to curl :/

**Comment by sikmir** [comment] 2021-03-21 22:35
Still important.

**Comment by dermetfan** [comment] 2021-08-22 18:05
Probably duplicate of #41820.

**Comment by Infinisil** [comment] 2022-03-11 22:26
Duplicate of #41820

**Closed by Infinisil** 2022-03-11 22:26 UTC
Labels: 0.kind: bug
