### ISSUE TITLE
GRUB install fails with aarch64-efi target

### ISSUE THREAD

**Issue by ne9z** [NixOS/nixpkgs#222491] opened 2023-03-22 07:44 UTC
### Describe the bug
GRUB fails to install EFI bootloader on an aarch64-efi target:
```
# nixos-install --root /mnt
Died at /nix/store/ids166d0qf8k4s7clmwzbba2ml4ysxik-install-grub.pl line 608.
```
Due to [this line](https://github.com/NixOS/nixpkgs/blob/1594660ef26db2424ca58a3ffc1831c3640776c8/nixos/modules/system/boot/loader/grub/install-grub.pl):
``` perl
        if (($grubTarget eq "") || ($grubTargetEfi eq "")) { die }
```

Reported by [onsails](https://github.com/openzfs/openzfs-docs/issues/337#issuecomment-1213362535) originally in openzfs-docs repo. In the [Root on ZFS guide](https://openzfs.github.io/openzfs-docs/Getting%20Started/NixOS/Root%20on%20ZFS.html) I had written, I have to use [a patched GRUB configuration module](https://github.com/ne9z/dotfiles-flake/blob/4bdf7b650e4e4af9cda1e2750746a0eb2d3ee661/modules/boot/grub-for-arm64/install-grub.pl#L610) to let GRUB install correctly:
``` perl
        if (($grubTarget eq "") || ($grubTargetEfi eq "")) { return "both" }
```

### Steps To Reproduce
1. Boot your ARM64 board with Tow-Boot.
2. Install NixOS with GRUB and EFI support.
3. ``nixos-install`` dies on the perl script.

### Expected behavior
GRUB installs correctly for aarch64-efi target.

### Notify maintainers

@samueldr

**Comment by iliana** [comment] 2023-06-05 04:05
Ran into this (same culprit, different root cause) and debugged a little. This is because `$grubTarget` on aarch64-linux is `""`, as it is usually EFI-only.

If `boot.loader.grub.devices = ["nodev"]`, this conditional sets `$grub` to null:

https://github.com/NixOS/nixpkgs/blob/e7603eba51f2c7820c0a182c6bbb351181caa8e7/nixos/modules/system/boot/loader/grub/grub.nix#L18-L23

But if `devices` is set to any other value, `$grub` gets filled in with the path to a build that does not support EFI (not sure how that works). Thus this dies, because `$grub` and `$grubEfi` are both set, but `$grubTarget` is unset:

https://github.com/NixOS/nixpkgs/blob/945f0625d549db0fc3e4d05484223cca14698064/nixos/modules/system/boot/loader/grub/install-grub.pl#L582-L587

In the case of ne9z/dotfiles-flake (used by your Root on ZFS Guide), setting `devices` to `["nodev"]` on aarch64 should resolve the issue.

However if you are me, and are solely using `boot.loader.grub.mirroredBoots` (instead of `devices`), you are out of luck. I'm not sure what the correct fix here is, but I think the conditional in grub.nix I mention above should be looking at `mirroredBoots`, which gets generated based on `devices` if unset. I might work on a patch for that.

**Comment by motiejus** [comment] 2023-08-26 20:51
> However if you are me, and are solely using `boot.loader.grub.mirroredBoots` (instead of `devices`), you are out of luck. I'm not sure what the correct fix here is, but I think the conditional in grub.nix I mention above should be looking at `mirroredBoots`, which gets generated based on `devices` if unset. I might work on a patch for that.

Indeed `devices = ["nodev"]` works. An it's been fixed in unstable by @iliana in #236027, thanks!

For whoever stumbles into this before 23.11 comes out, here is my workaround: https://git.jakstys.lt/motiejus/config/commit/1db9253ae6a42a083254bffc476298b1225ecd71#diff-e8651b14ed2e3c8d0fd93e6ef8e693314a9c478f

Inline:

```patch
diff --git a/modules/base/boot/default.nix b/modules/base/boot/default.nix
index d07d4e0..71e45cd 100644
--- a/modules/base/boot/default.nix
+++ b/modules/base/boot/default.nix
@@ -26,6 +26,11 @@ in {
       description = "Specify boot devices";
       type = types.nonEmptyListOf types.str;
     };
+    forceNoDev2305 = mkOption {
+      description = "https://github.com/NixOS/nixpkgs/issues/222491";
+      type = types.bool;
+      default = false;
+    };
     availableKernelModules = mkOption {
       type = types.nonEmptyListOf types.str;
       default = ["uas" "nvme" "ahci"];
@@ -130,7 +135,10 @@ in {
           generationsDir.copyKernels = true;
           grub = {
             enable = true;
-            devices = map (diskName: cfg.devNodes + diskName) cfg.bootDevices;
+            devices =
+              if cfg.forceNoDev2305
+              then ["nodev"]
+              else map (diskName: cfg.devNodes + diskName) cfg.bootDevices;
             efiInstallAsRemovable = cfg.removableEfi;
             copyKernels = true;
             efiSupport = true;
```

**Comment by Alxandr** [comment] 2023-09-06 20:25
I'm having the same issue even with `nodev` - and I'm not able to figure out how to solve this. I'm new to nixos, trying to set up my first server, and this is turning out to be a wall I'm not sure how to overcome. I've uploaded my config here: https://github.com/Alxandr/dbost-server/blob/main/configuration.nix. 

The error I'm getting is:

```
Died at /nix/store/an9ngv2vg95bdcy0ifsxlbkasprm4dcw-install-grub.pl line 586.
```

I'd be very appreciative if someone could point out how I can solve this.

**Comment by samueldr** [comment] 2023-09-06 23:27
(After discussion in the matrix room...)

For

```
Died at /nix/store/an9ngv2vg95bdcy0ifsxlbkasprm4dcw-install-grub.pl line 586.
```

to be reached on 23.05, the `grub` value needs to be non-null/non-empty:

 - https://github.com/NixOS/nixpkgs/blob/4077a0e4ac3356222bc1f0a070af7939c3098535/nixos/modules/system/boot/loader/grub/install-grub.pl#L583-L586
 - https://github.com/NixOS/nixpkgs/blob/4077a0e4ac3356222bc1f0a070af7939c3098535/nixos/modules/system/boot/loader/grub/grub.nix#L18-L23

So `grub.device[s]` being different than `"nodev"`.

**Closed** 2023-12-14 20:41 UTC
Labels: 0.kind: bug
