### ISSUE TITLE
onlyoffice-docserver fails to build after noxos upgrade to 24.11

### ISSUE THREAD

**Issue by fschn90** [NixOS/nixpkgs#363234] opened 2024-12-08 14:31 UTC
## Describe the bug

When upgrading from NixOS 24.05 to 24.11 onlyoffice-docserver doesnt work anymore.
## Steps To Reproduce

```nix
  services.onlyoffice = {
    enable = true;
  };
```

## Expected behavior

onlyoffice not to fail but to work.

## Additional context

I've tried the following with no avail:
```bash
sudo mv /var/lib/onlyoffice /var/lib/onlyoffice-bak
sudo systemctl restart onlyoffice-docservice
```
getting followings errors:
```bash
onlyoffice-wrapper[1572910]: /nix/store/sipdf17286pcby48d4ypxkcyz183fcrp-onlyoffice-documentserver-run-script: line 22: var/www/onlyoffice/documentserver/server/tools/allfontsgen: No such file or directory
onlyoffice-wrapper[1572897]: Done
onlyoffice-wrapper[1572897]: Generating presentation themes, please wait...
onlyoffice-wrapper[1572911]: /nix/store/sipdf17286pcby48d4ypxkcyz183fcrp-onlyoffice-documentserver-run-script: line 33: var/www/onlyoffice/documentserver/server/tools/allthemesgen: No such file or directory
onlyoffice-wrapper[1572912]: /nix/store/sipdf17286pcby48d4ypxkcyz183fcrp-onlyoffice-documentserver-run-script: line 38: var/www/onlyoffice/documentserver/server/tools/allthemesgen: No such file or directory
onlyoffice-wrapper[1572913]: /nix/store/sipdf17286pcby48d4ypxkcyz183fcrp-onlyoffice-documentserver-run-script: line 45: var/www/onlyoffice/documentserver/server/tools/allthemesgen: No such file or directory
onlyoffice-wrapper[1572897]: Done
onlyoffice-wrapper[1572897]: /nix/store/sipdf17286pcby48d4ypxkcyz183fcrp-onlyoffice-documentserver-run-script: line 52: /var/www/onlyoffice/documentserver/server/DocService/docservice: No such file or directory
omhe systemd[1]: onlyoffice-docservice.service: Main process exited, code=exited, status=127/n/a
```

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.63, NixOS, 24.11 (Vicuna), 24.11.20241203.b681065`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/store/w66xaybnxjf5zhxapxs3pd3zp7gxk9dw-source`

## Notify maintainers

@SuperSandro2000 
---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment] 2024-12-08 14:37
Dupe of #342543

**Closed** 2024-12-08 14:38 UTC
Labels: 0.kind: bug
