### ISSUE TITLE
Haskell development shells are not very useful

### ISSUE THREAD

**Issue by ncfavier** [NixOS/nixpkgs#196753] opened 2022-10-19 12:29 UTC
`nix develop nixpkgs#haskellPackages.foo` gives me a shell without cabal, and if I add cabal myself it fails most of the time because of a missing system dependency (`pkg-config`, `zlib`, ...).

cc @sternenseemann @cdepillabout @maralorn

**Comment by ncfavier** [comment] 2022-10-19 14:22
Thanks for writing such detailed answers to such an underspecified question! It seems like both `foo.env` and `shellFor` do what I want (use Nix for dependencies) and I can add `cabal-install` to the build inputs so this is good.

`developPackage` doesn't seem to use `ghcWithPackages` so it still runs into missing `pkg-config` stuff when trying to build a package depending on e.g. `gnuidn`.

Agreed that there's no bug here, just needs better documentation.

**Comment by maralorn** [comment] 2022-10-19 22:43
I guess that makes this a duplicate of #121403. :D

**Closed by maralorn** 2022-10-19 22:43 UTC
Labels: 6.topic: haskell, 6.topic: documentation
