### ISSUE TITLE
xdg-desktop-portal-gtk is broken when installed alongside gnome and used outside of gnome

### ISSUE THREAD

**Issue by clanktron** [NixOS/nixpkgs#334260] opened 2024-08-12 23:59 UTC
### Describe the bug
When gnome is installed via `services.xserver.desktopManager.gnome.enable` it installs xdg-desktop-portal-gnome and xdg-desktop-portal-gtk. However it passes an override flag to the gtk portal to disable a number of interfaces that are instead provided by the gnome portal. 

https://github.com/NixOS/nixpkgs/blob/6cbec70756cb7de1542f668a3807ca7808f62547/nixos/modules/services/x11/desktop-managers/gnome.nix#L284-L290

https://github.com/NixOS/nixpkgs/blob/6cbec70756cb7de1542f668a3807ca7808f62547/pkgs/development/libraries/xdg-desktop-portal-gtk/default.nix#L45-L50

This is fine if you're only using gnome. However if you're relying on the gtk portal for other window mangers/DE (any/all gnome/gtk4 apps use such), then the gtk portal can only provide a small subset of its intended functionality (missing settings, online accounts, etc).

I'm not sure if the gtk portal and gnome portal will have conflicts when the `disabled` flags are removed. If they do, then the user would need two gtk portals (one with the disabled flags that'll only run under gnome, and another with everything enabled that should run under other window managers/DE). If anyone has extra insight on this I'm all ears.

### Steps To Reproduce
1. enable gnome in configuration.nix 
3. have another DE/window manager installed
4. boot to said other DE/window manager and attempt to use any gtk4 or gnome-reliant apps

### Expected behavior
GTK4/Gnome apps should have access to online accounts, dark mode preferences, etc.

### Additional Context
- probably the root cause of https://github.com/NixOS/nixpkgs/issues/274554

### Metadata
```console
[I] clayton@nixos ~ [1]> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.44, NixOS, 24.05 (Uakari), 24.05.3690.21cc704b5e91`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```
---

**Comment by herrwiese** [comment] 2024-10-01 07:02
I have a similar issue, where Plasma6 recently adds `xdg-desktop-portal-gtk` (without override flag).  When Gnome is also enabled, this causes build failures because now building `user-units` tries to create an `xdg-desktop-portal-gtk.service` symlink to both variants of `xdg-desktop-portal-gtk`. -.-

**Comment by SuperSandro2000** [comment] 2024-10-05 22:11
The problem is probably that there are duplicated entries in xdg.portal.extraPortals which then fail to symlink in https://github.com/NixOS/nixpkgs/blob/3a8cd368bba4d3bfecf2df1425b948bff153b442/nixos/lib/systemd-lib.nix#L257

**Comment by Artturin** [comment] 2024-10-12 22:15
Fixed in https://github.com/nixos/nixpkgs/commit/c85360e7996126694237fe6c09d36d2bedce2963

**Closed by Artturin** 2024-10-12 22:15 UTC
Labels: 0.kind: bug
