### ISSUE TITLE
support for sharing arbitrary directories between nixos-containers and host system

### ISSUE THREAD

**Issue by anderspapitto** [NixOS/nixpkgs#10315] opened 2015-10-11 05:34 UTC
for example, I'd like to set up a container with access to ~/dev/myproj, in which to run compilation, testing, and other dev-related stuff for my project. However after scouring the documentation, it seems that there is no way exposed to share an arbitrary directory into the container (though, clearly it's possible, since /nix/store is shared in this way)

**Comment by ericsagnes** [comment] 2015-10-11 11:49
duplicate of #9886 
open in PR #7993

**Comment by joachifm** [comment] 2016-04-03 22:28
Looks to me like this has been addressed

**Closed by joachifm** 2016-04-03 22:28 UTC
Labels: 6.topic: nixos
