### ISSUE TITLE
tevent: pytalloc-util not found

### ISSUE THREAD

**Issue by gtgteq** [NixOS/nixpkgs#82489] opened 2020-03-13 14:40 UTC
**Describe the bug**
build of `tevent` failed.

**To Reproduce**
```
$ nix-shell -p tevent
...
Checking for system talloc (>=2.1.13)                                                           : yes
Checking for system pytalloc-util (>=2.1.13)                                                    : not found
ERROR: System library pytalloc-util of version 2.1.13 not found, and bundling disabled
builder for '/nix/store/aryzqwvawf3s4n1f6rk93bxq9q7dpi5g-tevent-0.9.37.drv' failed with exit code 1
error: build of '/nix/store/aryzqwvawf3s4n1f6rk93bxq9q7dpi5g-tevent-0.9.37.drv' failed
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.107, NixOS, 20.09pre215183.7948e6785b4 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre215183.7948e6785b4"`
 - channels(gtgteq): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- services.sssd
```

**Comment by jtojnar** [comment] 2020-03-31 01:40
Looks like regression in d617e54692507f31b1c546ad6221e7f96aa1b6dc. We need to build talloc with Python 3 too.

**Comment by jtojnar** [comment] 2020-03-31 01:57
It might also be fixed by https://github.com/NixOS/nixpkgs/pull/58380

**Comment by jtojnar** [comment] 2020-03-31 01:57
It might also need https://github.com/NixOS/nixpkgs/pull/58380

**Closed** 2020-03-31 19:08 UTC
Labels: 0.kind: bug
