### ISSUE TITLE
tmux "crashes???" when konsole tab is closed

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#35415] opened 2018-02-23 18:56 UTC
## Issue description

I've been using Konsole for years and it works great with tmux. However since a few days ago on unstable small, when I close a Konsole tab, the tmux session "in that tab" gets killed/stopped or whatever....

### Steps to reproduce

1. Use nixos-uunstable-small
2. Open Konsole
3. SSH into server
4. Start TMUX session
5. Right-click the konsole server tab and close it
6. Open new tap, ssh into same server again
7. Try to attach tmux

-->  https://youtu.be/-hXLPQfoI70

This has been happening not longer than 2 weeks I think... maybe even less than 1 week - not sure how long but not very long.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.21, NixOS, 18.03pre129183.a3c96fd4de3 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(hyper): `""`
 - channels(root): `"nixos-18.03pre129183.a3c96fd4de3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by sjau** [comment] 2018-02-23 19:00
Ok, I tested this on another server - same behaviour:

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.81, NixOS, 18.03pre128357.327a84749ed (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre128357.327a84749ed"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

If I do this on a non-nixos server it all works fine.

**Comment by sjau** [comment] 2018-02-23 19:03
I tested on a third server - this time I get the expected behaviour:

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.75, NixOS, 18.03pre124914.b9806751074 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre124914.b9806751074"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

(so all works fine here)

**Comment by LnL7** [comment] 2018-02-23 20:40
Git bisect blames 672bb6b4abd27d9b2796152522b54f5b82c9f76b, I don't really see anything suspicious in there.

**Comment by Mic92** [comment] 2018-02-24 00:44
@LnL7 can you track this down with `sysdig`?

**Comment by LnL7** [comment] 2018-02-24 01:07
I'm not sure how much time I'll have this weekend, it's pretty easy to reproduce if anybody else wants to take a shot at it. Tmux will die when the ssh connection closes.

```nix
{ config, lib, pkgs, ... }:
{
  services.mingetty.autologinUser = "root";
  virtualisation.graphics = false;

  users.users.foo = {
    uid = 1000;
    group = "foo";
    isNormalUser = true;
    openssh.authorizedKeys.keys = [ "..." ];
  };
  users.groups.foo = { gid = 1000; };

  environment.systemPackages = [ pkgs.tmux ];
  services.openssh.enable = true;
}
```

```sh
export QEMU_NET_OPTS="hostfwd=tcp::3000-:22"
nixos-rebuild build-vm -I nixos-config=foo.nix -I nixpkgs=.
./result/bin/run-nixos-vm

ssh -i ./foo_rsa -p 3000 foo@127.0.0.1
```

**Comment by orivej** [comment] 2018-02-24 01:09
> Git bisect blames 672bb6b4abd27d9b2796152522b54f5b82c9f76b, but I don't really see anything suspicious in there.

One thing that may be related is that it brings 1de98e85681e7d1028fe866fa220c05ce1ed842f, "plasma: 5.11.5 -> 5.12.1".

**Comment by Mic92** [comment] 2018-02-24 01:10
@LnL7 ah now, this is a different one. You need lingering enabled in logind, otherwise tmux get killed once, you close your ssh connnection, because your logind seat gets deallocated: https://github.com/NixOS/nixpkgs/issues/29234#issuecomment-340230209

**Comment by Mic92** [comment] 2018-02-24 01:11
@sjau are you experiencing this on a server via ssh or locally in konsole?

**Comment by LnL7** [comment] 2018-02-24 01:13
I've seen that issue with nix-build, tmux works fine it uses `/tmp/tmux-$UID` for the socket.

**Comment by sjau** [comment] 2018-02-24 05:40
@Mic92 

I experience this via ssh.... I tested it on 3 nixos servers... the 2 newer ones have that isse, an older one doesn't. Also non-nixos server don't have that issue either.

**Comment by MP2E** [comment] 2018-02-25 01:56
I'm affected by this issue as well, except I'm using rxvt-unicode as the terminal

**Comment by sjau** [comment] 2018-02-25 16:53
Btw, it only happens if I start tmux as normal user. When I login by ssh as root user, start tmux, close the konsole tab and re-login, the tmux session is still running

**Comment by Mic92** [comment] 2018-02-25 17:14
This can be fixed by doing `loginctl enable-linger $USER`, where `$USER` is your user.

**Comment by LnL7** [comment] 2018-02-25 17:16
enable-linger does not change the behaviour.

**Comment by LnL7** [comment] 2018-02-25 17:24
Note that there's also nothing systemd related in bad commit git bisect ended up in.

**Comment by sjau** [comment] 2018-02-25 23:15
I also tested it and the offending comit that I found was

f5e96d3e1b7 xz: set CONFIG_SHELL to /bin/sh, fix retained reference to bootstrap

**Comment by sjau** [comment] 2018-02-26 07:56
I tested it now also on a live server - reverting back to commit 122fa75b2de619ceace4b94a613683e54c34ddd0 makes tmux run properly again.

**Comment by sjau** [comment] 2018-02-26 08:09
Ok, it might not be that commit as I used

`git log --oneline b9806751074..327a84749ed`

and those two commits are adjacent

**Comment by dtzWill** [comment] 2018-02-26 11:59
Maybe both enabling lingering and using systemd-run is needed?

cc https://github.com/NixOS/nixpkgs/issues/15798#issuecomment-222352494

Hmm, I tried this but it failed to start due to permissions?

```
Feb 26 05:52:42 gravity polkitd[8886]: Registered Authentication Agent for unix-process:9169:30559097 (system bus name :1.31 [/run/current-system/sw/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Feb 26 05:52:42 gravity systemd[5382]: run-rff29cc1b2fea4c84ad8787b5f7c40649.scope: Failed to add PIDs to scope's control group: Permission denied
Feb 26 05:52:42 gravity systemd[5382]: run-rff29cc1b2fea4c84ad8787b5f7c40649.scope: Failed with result 'resources'.
Feb 26 05:52:42 gravity systemd[5382]: Failed to start /run/current-system/sw/bin/screen hydra.
```

Perhaps related: https://bbs.archlinux.org/viewtopic.php?id=227953

Is this really desirable default behavior? If so, should probably be mentioned in release notes....

From https://bbs.archlinux.org/viewtopic.php?pid=1724323#p1724323 possible hint:

> Ok, it seems that the distro package maintainer enabled systemd hybrid cgroup without kernel support.

**Comment by dtzWill** [comment] 2018-02-26 12:00
Or maybe `-Ddefault-kill-user-processes=false`? It does seem rather hostile default behavior.

**Comment by 7c6f434c** [comment] 2018-02-26 12:02
@dtzWill long long time ago, when this specific crazy change in `systemd` started affecting NixOS, we did add `KillUserProcesses=no` into `logind.conf` and never removed it. Because the default `systemd` behaviour is indeed hostile to any user who has a chance to install NixOS on their own.

**Comment by dtzWill** [comment] 2018-02-26 12:13
Oh, well hooray for that ^_^.  Good to know.

Chasing that:

```
$ find -L /run/current-system -name "logind.conf"
/run/current-system/etc/systemd/logind.conf
/run/current-system/systemd/etc/systemd/logind.conf
```

One of which sets `KillUserProcesses=no` nicely and the other does not.  Hopefully/presumably the other is just an example/dead-end. Hmm.

**Comment by dtzWill** [comment] 2018-02-26 12:17
Erm, maybe this **is** the problem? Poking at loginctl to try to see what it is reading from or what config it ends up with led me to try:
```
$ loginctl -p KillUserProcesses show-session
KillUserProcesses=yes
```

**Comment by dtzWill** [comment] 2018-02-26 13:25
(I'm not a systemd expert, can someone take a look? Thanks!)

**Comment by fpletz** [comment] 2018-02-26 13:38
@dtzWill Thanks for the debugging. This is probably a regression due to the recent systemd update. I can confirm that I have `KillUserProcesses=no` in `/etc/systemd/logind.conf` but `loginctl -p KillUserProcesses show-session` will print `KillUserProcesses=yes`.

**Comment by Mic92** [comment] 2018-02-26 13:42
@fpletz @dtzWill I looked into that using `sysdig` it only tries to read `${pkgs.systemd}/etc/systemd/logind.conf`, but not `/etc/systemd/logind.conf`. That's why configuration is never applied.

**Comment by Mic92** [comment] 2018-02-26 16:33
I made a pull request to our systemd fork that fixes the issue.

**Closed** 2018-03-03 09:44 UTC
Labels: 0.kind: regression, 1.severity: blocker, 6.topic: nixos
