### ISSUE TITLE
Build failure: compiler-rt-19.1.0-rc3

### ISSUE THREAD

**Issue by gracicot** [NixOS/nixpkgs#340797] opened 2024-09-09 15:17 UTC
### Steps To Reproduce

1. build `compiler-rt-19.1.0-rc3` on x86_64 linux

Here's my flake.nix:
```nix
{
  description = "Test";

  # Nixpkgs / NixOS version to use.
  inputs.nixpkgs.url = "nixpkgs/nixos-unstable";

  outputs = {
    self, nixpkgs
  }:
    let
      # System types to support.
      supportedSystems = [ "x86_64-linux" "x86_64-darwin" "aarch64-linux" "aarch64-darwin" ];

      forAllSystems = nixpkgs.lib.genAttrs supportedSystems;

      nixpkgsFor = forAllSystems (system: import nixpkgs { inherit system; });
    in
    {
      devShells = forAllSystems (system:
      let
        pkgs = nixpkgsFor.${system};
        llvmPackages = pkgs.llvmPackages_19;
        stdenv = llvmPackages.libcxxStdenv;
        mkShell = pkgs.mkShell.override { inherit stdenv; };
      in {
        default = mkShell {

        };
      });
  };
}
```
flake.lock:
```json
{
  "nodes": {
    "nixpkgs": {
      "locked": {
        "lastModified": 1725634671,
        "narHash": "sha256-v3rIhsJBOMLR8e/RNWxr828tB+WywYIoajrZKFM+0Gg=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "574d1eac1c200690e27b8eb4e24887f8df7ac27c",
        "type": "github"
      },
      "original": {
        "id": "nixpkgs",
        "ref": "nixos-unstable",
        "type": "indirect"
      }
    },
    "root": {
      "inputs": {
        "nixpkgs": "nixpkgs"
      }
    }
  },
  "root": "root",
  "version": 7
}
```

### Build log

https://gist.github.com/gracicot/e1a778ef067ea1749ddcffc2f7cbffd1

### Additional context

This only happen when using clang with libcxx on linux. This seems to be caused by the addition of a new sanitizer called rtsan: https://clang.llvm.org/docs/RealtimeSanitizer.html

### Notify maintainers

@NixOS/llvm 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.7-arch1-1, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.2`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/home/voidstar/.nix-defexpr/channels/nixpkgs`
```

Note: also happen on the `nixos/nix` docker image on linux x86. Does not seem to occur on linux arm64.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by RossComputerGuy** [comment] 2024-09-09 15:41
Duplicate of #329838, fix has already been merged into master. Please check the issue tracker to see if your issue was already reported before opening a new one.

**Closed by RossComputerGuy** 2024-09-09 15:41 UTC
Labels: 0.kind: build failure
