### ISSUE TITLE
sudo[5132]: sh: ps: command not found

### ISSUE THREAD

**Issue by wwat** [NixOS/nixpkgs#5490] opened 2014-12-28 18:44 UTC
I get this message, but I expect that this shouldn't have happened. 

```
pkexec must be setuid root
```
```
ls -lah `which pkexec`
-r-s--x--x 1 root root 13K Dec 28 19:36 /var/setuid-wrappers/pkexec
```

Perhaps there is a bug in the program I am trying to get working, but some feedback would be nice.

**Comment by wwat** [comment] 2015-01-02 14:59
I don't experience this issue anymore.

**Comment by wwat** [comment] 2015-01-03 21:23
I can reproduce this issue (or perhaps feature) when I add `--prefix PATH : "${procps}/bin"` to some binary. The intention of procps was to have `ps` in `PATH`, but apparently that is not needed, because ps is normally already available, but I still get the following line in my logs then:
``` Jan 03 21:18:20 nixos sudo[5132]: sh: ps: command not found ```
 Searching for 'ps' in source code is rather impossible with grep like tools, so, what can I do to find calls to 'ps' or to simply make it work (without identifying call sites)?

**Comment by lethalman** [comment] 2015-01-03 21:43
For procps maybe it's better to use --suffix, so that the setuid wrapper
takes precedence.

On Sat, Jan 3, 2015 at 10:23 PM, wwat <notifications@github.com> wrote:

> I can reproduce this issue (or perhaps feature) when I add --prefix PATH
> : "${procps}/bin" to some binary. The intention of procps was to have ps
> in PATH, but apparently that is not needed, because ps is normally
> already available, but I still get the following line in my logs then:
> Jan 03 21:18:20 nixos sudo[5132]: sh: ps: command not found
> Searching for 'ps' in source code is rather impossible with grep like
> tools, so, what can I do to find calls to 'ps' or to simply make it work
> (without identifying call sites)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/5490#issuecomment-68610118>.
>



-- 
NixOS Linux <http://nixos.org>

**Comment by wwat** [comment] 2015-01-03 22:05
@lethalman and when I do that, I get ` nixos sudo[8793]: pkexec must be setuid root`, so it might be that the ps thing either solved something, or it reintroduced the same problem (which now means that I would be in an infinite loop).

**Comment by bjornfor** [comment] 2015-01-03 22:19
@wwat: ensure that /var/setuid-wrappers is first in PATH. Then you'll get the (correct) setuid variant of pkexec.

**Comment by wwat** [comment] 2015-01-04 11:35
@bjornfor Isn't that what @lethalman's suggestion comes down to?

**Comment by bjornfor** [comment] 2015-01-04 11:51
@wwat: Yes. But it assumes that the setuid is already in path. My guess is that it isn't. That's why I suggest to explicitly put /var/setuid-wrappers in PATH for whatever command you're trying to run.

**Comment by vcunat** [comment] 2015-01-04 11:56
If you need it with setuid, then paths like ``${procps}/bin`` are useless, both on nixos and non-nixos. You can either assume a reasonable $PATH gets passed from the caller, or e.g. use something like ``/var/setuid-wrappers:/usr/bin`` to cover both cases.

**Comment by wwat** [comment] 2015-01-05 08:16
Is it safe to say that in general there should be no references to `/nix/store/<path>/pkexec` where pkexec is not suid in `$out`?

**Comment by bjornfor** [comment] 2015-01-05 08:37
Yes, it seems so. pkexec requires setuid:
```
$ nix-build -A polkit
/nix/store/mda8yqp7wzi64kgrf3h8l6az1b41jikn-polkit-0.112
$ ./result/bin/pkexec 
pkexec must be setuid root
```

The nix store cannot have setuid binaries (due to security + its multi-user capabilities), so setuid binaries are in /var/setuid-wrappers instead.

**Comment by wwat** [comment] 2015-01-05 09:27
So, it would be possible to warn for references like this being created, i.e. make configuration time errors appear. (it would just be a matter of scanning the files under `$out`).

**Comment by bjornfor** [comment] 2015-01-05 10:19
AFAICS, no explicit references are being made (so there is nothing to scan). Your issue happens at runtime because /var/setuid-wrappers isn't first in $PATH. Other programs aren't rebuilt when a setuid binary is written to /var/setuid-wrappers.

**Comment by wwat** [comment] 2015-01-05 10:30
Ok, so you are saying that the `polkit` dependency add it to PATH, and that the /var/setuid-wrappers version is therefor never even found?

**Comment by bjornfor** [comment] 2015-01-05 11:17
@wwat: Something like that. Run ```which -a pkexec```. You should see something like this:

```
/var/setuid-wrappers/pkexec
/run/current-system/sw/bin/pkexec
```

Run both of them. THe first one works and the other will say "pkexec must be setuid root". This is why I earlier suggested you put /var/setuid-wrappers first in $PATH for whatever thing you're trying to run.

**Comment by wwat** [comment] 2015-01-10 14:36
I am seeing this in my output:
```
patching script interpreter paths
/nix/store/caa209kmmvj489bsq7bqp0pl1193rlkp-zoneminder-1.28.0/bin/.zmsystemctl.pl-wrapped: interpreter directive changed from "/var/setuid-wrappers/pkexec /nix/store6qvjjaywj6qf8jn9splpiz9qap01w36w-perl-5.16.3/bin/perl" to "/nix/store/6hik1yf1ml2imw46mh0ma406391vsgj5-polkit-0.112/bin/pkexec /nix/store/
6qvjjaywj6qf8jn9splpiz9qap01w36w-perl-5.16.3/bin/perl "
```
Can anyone explain to me why that is happening? (I patched it such that it would use /var/setuid-wrappers/pkexec, but then there is something which patches it to the wrong value again. )

**Comment by bjornfor** [comment] 2015-01-10 15:41
It's the patchShebangs function in the standard builder that does that. It replaces shebangs with absolute paths to nix store objects. But for this package it seems you have to stop it from doing that. Try setting ```dontPatchShebangs = true;``` in the derivation. You may have to do some manual shebang patching though, like ```patchShebangs $out/bin/some-file```, but skip that particular troublesome file.

But... wait... patchShebangs only patches *shebangs* (the first line in executable scripts), so "pkexec" is used as a shebang? I didn't know that.

**Comment by wwat** [comment] 2015-01-10 16:01
@bjornfor 
Yes, it's being used as a shebang in zoneminder. Since shebangs are not portable, this can be considered a bug in Zoneminder too. Every single time you write #! you are essentially wasting bytes. 

I figured out the dontPatchShebangs myself too in the meanwhile, but then I get:
```
 nixos sudo[26857]: Error creating textual authentication agent: Error opening current controlling terminal for the process (`/dev/tty'): No such device or address
```
I already configured polkit to allow *everything* and yet, it still whines (and that error message is also rather bad).

**Comment by bjornfor** [comment] 2015-01-10 16:08
I don't know what you mean with "shebangs are not portable".

I don't know anything about polkit :-/

**Comment by wwat** [comment] 2015-01-10 16:17
@bjornfor For a portable program you should always specify the interpreter in the caller. 
a.sh
```
#!/<whatever>
echo hi
```
So, `sh a.sh` would be considered correct code, but `./a.sh` is not.

**Comment by bjornfor** [comment] 2015-07-12 10:28
I think the issue is solved: /var/setuid-wrappers/ must be in $PATH for the correct (setuid) pkexec binary to be run. The issue is also specific to the zoneminder package that has a script with a pkexec shebang (which can be patched out). Closing.

**Closed by bjornfor** 2015-07-12 10:28 UTC
