### ISSUE TITLE
KDE wallet broken

### ISSUE THREAD

**Issue by benley** [NixOS/nixpkgs#27416] opened 2017-07-16 01:22 UTC
## Issue description
My KDE wallet has gone missing.  Here's what shows up in syslog:

```
xsession[2964]: Pass a valid window to KWallet::Wallet::openWallet().
xsession[2964]: Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.Spawn.ExecFailed", "Failed to execute program org.kde.kwalletd5: No such file or directory")
xsession[2964]: The kwalletd service is still not registered
xsession[2964]: Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.Spawn.ExecFailed", "Failed to execute program org.kde.kwalletd5: No such file or directory")
xsession[2964]: The kwalletd service is still not registered
xsession[2964]: Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.Spawn.ExecFailed", "Failed to execute program org.kde.kwalletd5: No such file or directory")
xsession[2964]: The kwalletd service is still not registered
xsession[2964]: Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.Spawn.ExecFailed", "Failed to execute program org.kde.kwalletd5: No such file or directory")
xsession[2964]: The kwalletd service is still not registered
xsession[2964]: Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.Spawn.ExecFailed", "Failed to execute program org.kde.kwalletd5: No such file or directory")
xsession[2964]: The kwalletd service is still not registered
xsession[2964]: Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.Spawn.ExecFailed", "Failed to execute program org.kde.kwalletd5: No such file or directory")
xsession[2964]: The kwalletd service is still not registered
xsession[2964]: Invalid DBus reply:  QDBusError("org.freedesktop.DBus.Error.Spawn.ExecFailed", "Failed to execute program org.kde.kwalletd5: No such file or directory")
xsession[2964]: plasma-nm: Error opening kwallet.
xsession[2964]: Pass a valid window to KWallet::Wallet::openWallet().
xsession[2964]: Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.Spawn.ExecFailed", "Failed to execute program org.kde.kwalletd5: No such file or directory")
xsession[2964]: The kwalletd service is still not registered
xsession[2964]: Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.Spawn.ExecFailed", "Failed to execute program org.kde.kwalletd5: No such file or directory")
xsession[2964]: The kwalletd service is still not registered
xsession[2964]: Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.Spawn.ExecFailed", "Failed to execute program org.kde.kwalletd5: No such file or directory")
xsession[2964]: The kwalletd service is still not registered
xsession[2964]: Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.Spawn.ExecFailed", "Failed to execute program org.kde.kwalletd5: No such file or directory")
xsession[2964]: The kwalletd service is still not registered
xsession[2964]: Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.Spawn.ExecFailed", "Failed to execute program org.kde.kwalletd5: No such file or directory")
xsession[2964]: The kwalletd service is still not registered
xsession[2964]: Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.Spawn.ExecFailed", "Failed to execute program org.kde.kwalletd5: No such file or directory")
xsession[2964]: The kwalletd service is still not registered
xsession[2964]: Invalid DBus reply:  QDBusError("org.freedesktop.DBus.Error.Spawn.ExecFailed", "Failed to execute program org.kde.kwalletd5: No such file or directory")
xsession[2964]: plasma-nm: Error opening kwallet.
```

Probably related to the kde/plasma 5.8 to 5.9 upgrade? I'm really not sure.

## Technical details

* System: 17.09pre110213.01c3847b9c (Hummingbird)
* Nix version: nix-env (Nix) 1.11.11
* Nixpkgs version: "17.09pre110213.01c3847b9c"
* Sandboxing enabled: yes

**Comment by FRidh** [comment] 2017-07-16 09:47
This is a duplicate of https://github.com/NixOS/nixpkgs/issues/27038 and has been fixed with https://github.com/NixOS/nixpkgs/pull/27157. The fix just hasn't landed in the channel yet.

**Closed by FRidh** 2017-07-16 09:47 UTC

**Comment by benley** [comment] 2017-07-16 21:45
aha, sorry for the dupe and thank you for the fix.
