### ISSUE TITLE
Speed up autoconf generated ./configure with a site file

### ISSUE THREAD

**Issue by musteresel** [NixOS/nixpkgs#24081] opened 2017-03-19 21:54 UTC
I'm currently using nix-build as command to an `hg bisect`, when I wondered: Every time nix-build is invoked (on a new revision of the software I'm searching an error in) it starts out with a completely fresh build (good! because purity) which involves running `./configure`. This runs lots of tests, like:

```
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking how to make hard links... ln
checking whether ln -s works... yes
```

And also standard library related stuff:

```
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
```

But, don't the results of all those tests are only dependent on the `stdenv` used to build the package? What if that `stdenv` would include a [site configuration file](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Site-Defaults.html) which sets the cache variables for those tests, making every autoconf generated `./configure` skip the actual test? (After all these are pretty "heavy", running the compiler, forking shells, ...)

This would thus speedup building of every package with an autoconf generated configure file.

Ideas / Thoughts?

**Comment by bjornfor** [comment] 2017-03-19 22:11
If this can be done in a safe way (not breaking purity) that'd be awesome!

**Comment by joachifm** [comment] 2017-03-19 23:07
Previous discussion at https://github.com/NixOS/nixpkgs/issues/14586

**Comment by dezgeg** [comment] 2017-08-16 23:42
Yes, sounds like a duplicate of  #14586.

**Closed by dezgeg** 2017-08-16 23:42 UTC
