### ISSUE TITLE
Package request: PACKAGENAME

### ISSUE THREAD

**Issue by RowanBee** [NixOS/nixpkgs#329987] opened 2024-07-25 20:04 UTC
**Project description**

Crafty Controller is a free and open-source Minecraft launcher and manager that allows users to start and administer Minecraft servers from a user-friendly interface. The interface is run as a self-hosted web server that is accessible to devices on the local network by default and can be port forwarded to provide external access outside of your local network. Crafty is designed to be easy to install and use, requiring only a bit of technical knowledge and a desire to learn to get started. Crafty Controller is still actively being developed by Arcadia Technology and we are continually making major improvements to the software.

**Metadata**

* homepage URL: https://craftycontrol.com/
* source URL: https://gitlab.com/crafty-controller
* license: GPL-3
* platforms: linux (Ubuntu/Debian, CentOS)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment] 2024-07-25 20:26
Duplicate of https://github.com/NixOS/nixpkgs/issues/212543

**Closed by donovanglover** 2024-07-25 20:26 UTC
Labels: 0.kind: packaging request
