### ISSUE TITLE
busybox installs all applets as symlinks by default

### ISSUE THREAD

**Issue by steveeJ** [NixOS/nixpkgs#10716] opened 2015-10-30 12:17 UTC
When busybox is installed it installs all applets as symlinks by default. This includes less and other important system utilities, which breaks tools that rely on the full-fledged versions of these. To name an example: nix-env can't display query results anymore.

**Comment by steveeJ** [comment] 2015-10-30 12:40
As a workaround in the user-environment it helps to use the following in the ~/.nixpkgs/config.nix file
```nix
{
 packageOverrides = pkgs: rec {
   busybox = pkgs.busybox.override {
     extraConfig = ''
       CONFIG_INSTALL_APPLET_DONT y
       CONFIG_INSTALL_APPLET_SYMLINKS n
     '';
   };
 };
}
```

**Comment by steveeJ** [comment] 2015-10-30 12:43
*Note:* I tried to override this on my system's configuration.nix, but it seems to break initrd generation.

**Comment by vcunat** [comment] 2015-10-31 08:15
If you only want to override the one put into `systemPackages`, just write simply
```nix
systemPackages = [ (pkgs.busybox.override { /*...*/ }) ];
```

**Comment by steveeJ** [comment] 2015-10-31 20:12
@vcunat thanks, that works! Do you really think the default behavior is a good default? I'd find it better to set an override for the needed config in the initrd expression(s). It's not fun to try out busybox and suddenly have a broken environment.

**Comment by vcunat** [comment] 2015-10-31 22:01
IMO the purpose of `packageOverrides` is exactly when you want to override **every** usage of a certain attribute, as there's no other easy way AFAIK. Was that unclear from the documentation? (If so, maybe we should improve it.)

As I've shown, there is an easy way to override a package you put into `systemPackages`.

**Comment by steveeJ** [comment] 2015-11-01 00:10
@vcunat I've already confirmed that the override in the systemPackages works and allows me to adjust the busybox configuration, but that's not the issue. What I'm questioning is if the default busybox configuration is a good fit for most users. My opinion is that it is not because as mentioned before it will mask tools like `ls` and `less` when it is installed. My assumption is that most people will install the busybox package without checking the default configuration first and will end up with a broken environment.

**Comment by vcunat** [comment] 2015-11-01 00:19
I see. I got you wrong. Setting busybox to lower priority by default might be a solution. ATM I'm not completely certain whether `systemPackages` do support priorities, but `nix-env` certainly does (and even fails if there's a same-priority collision).

**Comment by cleverca22** [comment] 2015-11-19 07:58
but can a systemPackage ever be higher in priority then a nix-env package?, i don't think the order in PATH will allow it

**Comment by vcunat** [comment] 2015-11-19 09:37
No, the priorities work only within each nix-environment, not across.

**Comment by cleverca22** [comment] 2015-11-19 10:52
so even with a low priority, if i nix-env busybox, i also have to nix-env coreutils to fix things, a seperate derivation would probably work better

**Comment by wmertens** [comment] 2016-02-27 06:58
(triage) is any work planned for this?

I see 3 approaches:

1. Make a busyboxWithLinks attribute and let busybox only install the binary
1. Set the busybox priority to low, which was already proposed
1. Make a busyboxBinaryOnly attribute

I think 2 and 3 have the least chance of being breaking changes and they can both be implemented at the same time.

@cleverca22is this something you can take on, make a PR?

On phone, sorry for brevity…

**Comment by cleverca22** [comment] 2016-02-28 01:16
ive got a patch for busybox to remove the symlinks, now i just need to make that the default, without breaking the initrd

**Comment by xanatos-chimera** [comment] 2016-12-20 01:29
The issue is still present for me. Commands such as nix-env -qa .\* or systemctl status connman still yield the following error:

`systemctl` status connman
less: invalid option -- 'R'
BusyBox v1.24.2 () multi-call binary.

Usage: less [-EIMmNSh~] [FILE]...

View FILE (or stdin) one screenful at a time

	-E	Quit once the end of a file is reached
	-I	Ignore case in all searches
	-M,-m	Display status line with line numbers
		and percentage through the file
	-N	Prefix line number to each line
	-S	Truncate long lines
	-~	Suppress ~s displayed past EOF`
This occurres with busybox 1.24.2 and with version 1.25.1 as well.

**Comment by vcunat** [comment] 2016-12-20 08:21
Yes. I wonder what are possible use cases for installing busybox into an environment (on a non-embedded Linux).

**Comment by yegortimoshenko** [comment] 2017-12-21 15:33
@vcunat I know some people who like `vi` it comes with.

**Comment by Ekleog** [comment] 2019-09-08 02:41
Should be fixed by https://github.com/NixOS/nixpkgs/commit/1c0286331791

**Closed by Ekleog** 2019-09-08 02:41 UTC
Labels: 0.kind: enhancement
