### ISSUE TITLE
Package removal request

### ISSUE THREAD

**Issue by peppy** [NixOS/nixpkgs#132610] opened 2021-08-04 00:11 UTC
I am the main developer of osu!. I am requesting either removal of the "osu-lazer" package, or removal of the code patch as listed here: https://github.com/NixOS/nixpkgs/blob/master/pkgs/games/osu-lazer/bypass-tamper-detection.patch

We provide appimages, which should be the only source of truth for our binaries, as this is an online game which requires authentic client-side binaries to be used.

Thanks in advance!

**Comment by Artturin** [comment] 2021-08-04 00:22
Maintainer ping: @oxalica 
you can read the reasoning for the patch here https://github.com/NixOS/nixpkgs/pull/94833
we might be able to extract the appimage and use that

**Comment by oxalica** [comment] 2021-08-04 20:05
> we may be able to extract/wrap the appimage and use that

It used to be, but I'm not a fan of it because,
1. It pulls tons of unnecessary dependencies and makes the closure quite huge.
2. We do have access to the source, building from source should be generally preferred rather than from trusting upstream binaries.

I think we could remove the patch and try to bit-by-bit reproduce the same binary as the official release to match the hash. It may take some work. But I may not be familiar enough with .NET build system. Also @notgne2 for help.

**Comment by notgne2** [comment] 2021-08-04 22:00
@peppy While I understand wanting to control what client distributions are used in your multiplayer game, I feel like I'm very far from understanding the purpose of this tamper detection. Our distribution from this package might not match your hash, but it is very much legitimate and contains no cheats or player advantage modifications, you are free to audit the build process.

Does the fact you are making this issue not help remind you in any way how very silly this requirement is? No offence, but I think anybody capable of modifying the game for the sake of gaining an unfair advantage will have no problems deleting a few lines of code, so you aren't really protecting anything, and if you really think that this patch/bypass is some kind of divine secret bestowed upon my by the gods, then I advise you to stop drawing more attention to it.

The only thing you can gain by having it removed from here, is making it harder for legitimate honest players to play your game, and make sure more potential cheaters or hypothetically packagers which _don't_ care about maintaining legitimacy know how to bypass this in their own modified builds of it.

Like @oxalica said, we have other reasons to not be using your AppImages, though I actually would humor the idea of reproducing the build used in the original AppImage to match the hash instead of having this patch, but there are a number of reasons that may turn out to be impossible, and if so, I personally believe we should keep the patch.

I don't mean to be rude about this, I appreciate your work, your game, and your efforts to keep multiplayer fair, that is the whole reason this patch was even worth writing to begin with. I just don't think this specific form of protection is going to protect anything. Me and many others will continue to want to build from source and play online, having it removed from nixpkgs just means we will all need to copy paste an overlay instead, something that may be very annoying to a legitimate player, not so much to a cheater (though I would like to believe us NixOS folks are better than that)

**Comment by peppy** [comment] 2021-08-05 02:13
- The check your have bypassed is currently intended to avoid compatibility issues primarily. Because you have set it to a constant, old clients could connect to incompatible server components.
- The hash you used was outdated, causing reports to our end of things not working.

If changes cannot be made to use the app image then I would request delisting of the package for the time being, thanks.

**Comment by notgne2** [comment] 2021-08-05 03:36
If it helps out at all, I can submit a patch upstream to remove your misinformed hash check system and replace it with something which does not cause you issues and reports, perhaps a version number, a commit hash, or a timestamp. Otherwise I can implement a way to keep this hash up to date and persistently mirroring the AppImage most equivilent to the revision we are packaging if you would prefer to avoid breaking your mistaken system.

It is up to other maintainers of nixpkgs if they wish to keep this patch in place, but it is in my opinion that it should remain, and I hope descisions regarding the "ambee" Python package and Home Assistant suite set a precedent of prioritizing the NixOS users and community over the odd descision making of some developers.

I will gladly contribute my time to investigating reproducible builds, fixing your broken compatibility checks, or working around them by mirroring more relevant hashes, but none of it towards an outcome where NixOS users are forced to use an AppImage to play osu! online. If it is removed from nixpkgs, I will take the same stance in my own package overlay which I will distribute to any NixOS osu! players, I do not want to cause any additional issues for you and your system, but if you do not want me distributing fixed copies of you game, I suggest you change your license.

**Comment by bdach** [comment] 2021-08-05 06:47
> if you do not want me distributing fixed copies of you game, I suggest you change your license

While this may be technically correct, I find it utterly disappointing and unnecessary that apparently the only means of recourse available to get @notgne2 to abide by the wishes of the primary developer of a project are *legal* means. Especially so that to my knowledge there was no actual effort or contact from @notgne2 or anyone else to establish what would be the *proper* solution - the workaround committed to this repository was implemented by what seems to be a judgement of *one* person, entirely unconnected to the project being redistributed to boot.

**Comment by notgne2** [comment] 2021-08-05 07:02
@bdach

If your wishes are to make it more difficult for NixOS users to play osu! because of a developmental mistake, it's unfortunately none of my concern, however I even offered to help develop a better solution for compatibility checks, or work on better hash<->rev parity within nixpkgs if I am really to believe that's what the hash check is for.

Honestly my original plan was to open an issue on the osu repository to begin discourse about why you even have this check to begin with, but I had already found forum posts indicating that upstream probably wouldn't care to change it, and then kindof forgot about it.

I'm willing to meet at any middleground that does not involve me and others being unable to play on a copy compiled from source, your approach is to aggressively demand nixpkgs remove my fix and make no attempt to solve the actual issue which I would be very willing to assist with.

I mean no harm by any of this, I _want_ to work with the osu! team on solving this issue and removing the patch, but until you're interested in doing so, I'm going to make sure this patch is distributed to anybody who needs it to the best of my ability.

**Comment by oxalica** [comment] 2021-08-05 07:11
@peppy 
> The check your have bypassed is currently intended to avoid compatibility issues primarily. Because you have set it to a constant, old clients could connect to incompatible server components.
> The hash you used was outdated, causing reports to our end of things not working.

If so we can simply update that hash every time when updating the game. But you still don't like it, yes?

IMO, the "temper detection" will barely do anything other than keeping honest players from compiling source code themselves. (which makes me more concern about the "pre-built" binaries.)
- Cheaters can still simply bypass it in anyway including modifying your binary, hooking filesystem or even kernel, no matter if that hash check exists.
- Cheating can always be detected by human players from game replays, no matter if that hash check exists.

Anyways, I cannot trust any "pre-built" binaries unless I (and everyone, for nixpkgs) can reproduce it themselves. I'm glad to see you can also helps us and other package collection to achieve this goal by more documentations for the reproducible building process.

Another remind: `osu-lazer`is currently not built on nixpkgs' building platform (Hydra). The nix files here are just recipes for users themselves to build for their own, quite like what AUR (Arch User Repository) did.

**Comment by peppy** [comment] 2021-08-05 07:13
Thanks for your insight. I'm not really interested in discussion over what is and is not being achieved by the measures we have in place - that is out of scope.

You are welcome to implement your own methods of generating the hash if you deem that as best for your users. Please make sure that you do so in a way that doesn't generate support burden at our end. That is the only reason I brought this up in the first place. We are trying to make a game predominantly for windows but linux users are generating the majority of our support burden.

**Comment by notgne2** [comment] 2021-08-05 07:17
@peppy I'll bake up a script which makes our version use hashes from the AppImage equivilent to the revision ours is being built with if that sounds best, idealy you would switch the system out for something not involving any binary hashing at all, but another way of working with us here is if we are able to submit our hashes to you for whitelisting on your end, though I'm not sure how well that would work accounting for delays and whatnot.

**Comment by oxalica** [comment] 2021-08-05 07:26
Close since the patch is removed according to the request.

**Closed by oxalica** 2021-08-05 07:26 UTC
Labels: 0.kind: bug, 11.by: upstream-developer

**Comment by joepie91** [comment] 2021-08-15 11:40
While I'm somewhat hesitant to dig up this thread again, I think it would probably be best to post this publicly after all, because it's starting to feel like disputes like this are becoming a recurring issue, and I don't think we're dealing with it very well as a community right now.

@notgne2 While *in principle* I agree with your technical criticism of a hash check being ineffective for cheating protection, your hostility was IMO uncalled for. It would have been enough to stick with the technical point on how it can't work, without trying to squeeze words like "broken" and "misinformed" into every other sentence, or generally talking to/about @peppy with such a patronizing tone.

Comments and phrasing like these, for example:

> and if you really think that this patch/bypass is some kind of divine secret bestowed upon my by the gods

> prioritizing the NixOS users and community over the odd descision making of some developers.

> if you do not want me distributing fixed copies of you game, I suggest you change your license.

> If your wishes are to make it more difficult for NixOS users to play osu! because of a developmental mistake

... are really not acceptable; they don't contribute any actionable information to the discussion, they don't establish a common understanding that we can move forward from, their only purpose (at least in that phrasing) seems to be to direct anger at @peppy.

I do not think that this is something we should be doing - *or accepting* - as a community, especially considering that Nix *does* still use a relatively uncommon packaging model and some degree of misunderstanding by others should therefore be expected, however frustrating it may be. It's at least partly on us to compensate for that, eg. by patiently clarifying the reason for certain decisions.

Additionally, these sorts of discussions should really be approached from an assumption of good faith; prioritizing *understanding somebody's concern*, without being judgmental, without drawing any conclusions until the exact concern is clear. In this case, that concern seems to be "it breaks stuff because it is effectively misreporting the version", which is a legitimate and solvable concern.

We could have gotten there without the personal attacks, and in that case we might have come to a solution other than removal.

**Comment by peppy** [comment] 2021-08-15 13:18
Was hesitant to reply here but I can confirm that it is not intended to be "anti-cheat" measures (porting this across is one of the remaining blockers for more online leaderboards to come online). In fact, the code replaced by the patch itself has a comment and fallback case which should make that very apparent.

Others on our team did show frustration and disappointment at the tone in here.

Thanks for the understanding.
