### ISSUE TITLE
Package request: Nekoray

### ISSUE THREAD

**Issue by Chapped1888** [NixOS/nixpkgs#280714] opened 2024-01-13 11:36 UTC
**Project description**

Qt based cross-platform GUI proxy configuration manager (backend: v2ray / sing-box)

Support Windows / Linux out of the box now.

**Metadata**

* source URL: https://github.com/MatsuriDayo/nekoray
* license: GPL 3.0
* platforms: Windows, Linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-01-14 01:17
duplicate of #244451

**Closed by eclairevoyant** 2024-01-14 01:17 UTC
Labels: 2.status: duplicate, 0.kind: packaging request
