### ISSUE TITLE
Package request: kWinFT

### ISSUE THREAD

**Issue by kunihir0** [NixOS/nixpkgs#244921] opened 2023-07-22 22:22 UTC
**Project description**
Wayland compositor and X11 window manager (a reboot of KWin)

- homepage URL: https://gitlab.com/kwinft/kwinft
- source URL: https://gitlab.com/kwinft/kwinft
- license: gpl
- platforms: linux

**Comment by Aleksanaa** [comment] 2023-08-07 05:34
duplicate of https://github.com/NixOS/nixpkgs/issues/197356 and https://github.com/NixOS/nixpkgs/issues/158827

**Closed by Aleksanaa** 2023-08-07 05:34 UTC
Labels: 0.kind: packaging request
