### ISSUE TITLE
libva: iris_drv_video.so not found

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#85850] opened 2020-04-23 07:01 UTC
**Describe the bug**
libva tries to find and use iris_drv_video.so instead of i965_drv_video.so like before

**To Reproduce**
1. Use nixos-unstable channel
2. Open vlc on console to see log
3. Open any video in vlc

**Expected behavior**
i965_drv_video.so is used and no vlc crash happens

**Additional context**

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.33, NixOS, 20.09.git.22a3bf9fb9e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(gnidorah): `""`
 - channels(root): `"nixos-20.09pre222138.b3c3a0bd183"`
 - nixpkgs: `/home/gnidorah/tmp/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by primeos** [comment] 2020-04-23 10:26
Seems to be an upstream issue that affects only X11 (DRI 2): https://github.com/intel/libva/pull/406
After we update `libva` to [2.7.1](https://github.com/intel/libva/releases/tag/2.7.1) this should be fixed.

As a temporary workaround it should work via `export LIBVA_DRIVER_NAME=i965` (or `iHD`, depending on which driver you prefer).

**Comment by primeos** [comment] 2020-04-23 19:34
I opened a PR for the update: #85886

Note: I added the regression label as `iris` is the new default since Mesa 20 (the previous default driver was `i965`). As a result NixOS `20.03` shouldn't be affected by this as we stayed on Mesa 19.

**Closed** 2020-04-27 17:35 UTC
Labels: 0.kind: bug, 0.kind: regression
