### ISSUE TITLE
Qtox cannot find libQt5OpenGL

### ISSUE THREAD

**Issue by pijul** [NixOS/nixpkgs#15744] opened 2016-05-27 08:17 UTC
## Issue description
Qtox refuses to start even on the most recent update of unstable nixos.  Here's what I get when I try to start it:

```
x@y ~ % qtox                                                                         ~
/run/current-system/sw/bin/qtox: error while loading shared libraries: libQt5OpenGL.so.5: cannot open shared object file: No such file or directory
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
16.09pre84171.6d16979 (Flounder)

* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.2

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"16.09pre84171.6d16979"

**Comment by rardiol** [comment] 2016-05-27 12:35
99% sure it's a duplicate of https://github.com/NixOS/nixpkgs/issues/15556

**Comment by rardiol** [comment] 2016-05-30 03:01
Hmm, apparently it's not the same fix, even if it's the same problem (qt tmp folder at the beggining of rpath). @ttuegel, any ideas?

**Comment by ttuegel** [comment] 2016-05-30 21:28
It's because `qtox` has a custom `installPhase` that does not call its hooks correctly, so the temporary directory never gets deleted (which is required for the `RPATH` to be updated). I'll have it fixed today, but I'm also going to move the deletion to an earlier point in the build process when it cannot be carelessly omitted.

**Comment by rardiol** [comment] 2016-05-30 21:38
If you're going to fix the install phase, getting it to install the .desktop file would be nice. I think there's something wrong with the qtox.pro file (around line 180 I think) that causes "make install" to ignore the prefix set and install to /usr/, so whoever packaged it probably worked around it by doing a manual installPhase.

**Closed** 2016-05-30 22:02 UTC
