### ISSUE TITLE
Build failure: postman

### ISSUE THREAD

**Issue by Ziothh** [NixOS/nixpkgs#267680] opened 2023-11-15 14:42 UTC
### Steps To Reproduce

Build `postman` (currently v10.18.6).

### Build log

```console
trying https://dl.pstmn.io/download/version/10.18.6/linux64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
error: cannot download postman-10.18.6.tar.gz from any mirro
```

### Additional context

It seems like the Postman team has changed their API structure.
The package builder fetches from [https://dl.pstmn.io/download/version/10.18.6/linux64](https://dl.pstmn.io/download/version/10.18.6/linux64), which responds with a `404` status code.

If you go to their official download page you see that they use `linux_64` instead of `linux64` in their download link: [https://dl.pstmn.io/download/latest/linux_64](https://dl.pstmn.io/download/latest/linux_64).

I've tried changing `linux64` to `linux_64` in the v10.18.6 link but this also responds with a `404`.

### Notify maintainers

@johnrichardrinehart 
@evanjs 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.9, NixOS, 23.11 (Tapir), 23.11.20231026.63678e9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(zioth): `"home-manager, nixos"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/35dcag44a0ymww0vy0s4jjgxwpv9g62d-source`
```

**Comment by TomaSajt** [comment] 2023-11-15 21:38
It seems as if only the download links for `10.19.0` and `10.20.0` are working. About the underscore being there or not, it just works both ways.

**Comment by evanjs** [comment] 2023-11-15 21:55
Reminder: Postman no longer provides artifacts for old versions, merely citing "security" concerns.

Source: https://github.com/postmanlabs/postman-app-support/issues/12383#issuecomment-1750338961

**Comment by Artturin** [comment] 2023-11-17 23:34
Dupe of https://github.com/NixOS/nixpkgs/issues/259147

**Closed by Artturin** 2023-11-17 23:34 UTC
Labels: 0.kind: build failure
