### ISSUE TITLE
Video thumbnails in Dolphin (KDE) not shown

### ISSUE THREAD

**Issue by 01mf02** [NixOS/nixpkgs#29384] opened 2017-09-14 17:30 UTC
## Issue description

When using Dolphin to browse a folder with videos, the video thumbnails are not shown.
On the other hand, image thumbnails are correctly shown. Manually creating video thumbnails with ffmpegthumbnailer also works.

### Steps to reproduce

* Set `services.xserver.desktopManager.plasma5.enable = true;` in configuration.nix
* Start Plasma.
* `wget http://www.engr.colostate.edu/me/facil/dynamics/files/flame.avi`
* `dolphin`
* Enable "Preview" option in Dolphin
* Observe that no thumbnail for `flame.avi` is shown

## Technical details

* System: NixOS: 17.03
* Nix version: 1.11.14
* Nixpkgs version: "17.03.1825.df7e518568"
* Sandboxing enabled: false

**Comment by zauberpony** [comment] 2018-11-11 16:07
In recent nixos-versions, the thumbnail is being shown correctly, i.e. I **can't reproduce** the issue. Has probably been fixed in the mean-time, or the defaults have changed (on a debian-machine video-thumbnails have been disabled by default).
So IMO this issue should be **closed**.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.79, NixOS, 18.09.1228.a4c4cbb613c (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by ttuegel** [comment] 2018-11-11 19:52
Thanks for checking up!

**Closed by ttuegel** 2018-11-11 19:52 UTC
Labels: 6.topic: qt/kde
