### ISSUE TITLE
 qutebrowser 1.6 doesn't build on nixos-unstable (pykeepass issue)

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#56806] opened 2019-03-04 07:15 UTC
## Issue description

qutebrowser 1.6 doesn't build on nixos-unstable 
```
note: keeping build directory '/tmp/nix-build-python3.7-pykeepass-3.0.3.drv-1'
builder for '/nix/store/jmiyqjyy50ic1mxpp46nh5kw6pn739l9-python3.7-pykeepass-3.0.3.drv' failed with exit code 1; last 10 log lines:
  adding 'pykeepass-3.0.3.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
  installing
  /build/pykeepass-3.0.3/dist /build/pykeepass-3.0.3
  Processing ./pykeepass-3.0.3-py3-none-any.whl
  Requirement already satisfied: construct in /nix/store/jwsklhvr59xazfimfwvdrijzaiz498r9-python3.7-construct-2.9.45/lib/python3.7/site-packages (from pykeepass==3.0.3) (2.9.45)
  Requirement already satisfied: python-dateutil in /nix/store/qrcjaiprdn5wp47slc04zhhil2sg5a72-python3.7-python-dateutil-2.8.0/lib/python3.7/site-packages (from pykeepass==3.0.3) (2.8.0)
  Collecting future (from pykeepass==3.0.3)
    Could not find a version that satisfies the requirement future (from pykeepass==3.0.3) (from versions: )
  No matching distribution found for future (from pykeepass==3.0.3)
cannot build derivation '/nix/store/8varg5ji8a196xflz2mpz2lq75f1r94d-qutebrowser-1.6.0.drv': 1 dependencies couldn't be built
[0 built (1 failed), 2 copied (0.4 MiB), 0.1 MiB DL]

```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.20.12, NixOS, 19.09.git.e0f1c42 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(teto): `"nixos-18.09, nixos-unstable"`
 - nixpkgs: `/home/teto/nixpkgs`

**Comment by dotlambda** [comment] 2019-03-04 12:26
duplicate of https://github.com/NixOS/nixpkgs/issues/56612

**Closed by dotlambda** 2019-03-04 12:26 UTC
