### ISSUE TITLE
`phpcbf` is now deprecated, use `php-codesniffer` instead which contains both `phpcs` and `phpcbf`.

### ISSUE THREAD

**Issue by HippieMitch** [NixOS/nixpkgs#292006] opened 2024-02-28 06:00 UTC
### Describe the bug
After updating my flake.lock file on 02/27/2024 I'm unable to perform a nixos-rebuild without getting the error:

"`phpcbf` is now deprecated, use `php-codesniffer` instead which contains both `phpcs` and `phpcbf`"

I'm unable to see what is pulling this in so any advice on how to track this down would be helpful.

### Steps To Reproduce
1. In a terminal, execute a "nix flake update".
2. Attempt a nixos-rebuild.

### Expected behavior
I was expecting my system to rebuild without errors as I haven't changed anything since the last successful rebuild aside from my flake.lock file.

### Screenshots
![nixos-rebuild error](https://github.com/NixOS/nixpkgs/assets/72957198/95956608-08d0-45da-916a-ab3d30d0f296)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

![nix-info](https://github.com/NixOS/nixpkgs/assets/72957198/5350eb95-fd57-4439-a0cc-10b01155d8d7)

---

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by RustLover2910** [comment] 2024-02-28 12:31
I am also having that issue. I can't even install packages now without nix-env

**Comment by dotlambda** [comment] 2024-02-28 23:53
Did you try `--show-trace`?

**Comment by dotlambda** [comment] 2024-02-28 23:56
duplicate of https://github.com/nix-community/nixvim/issues/1160

**Closed by dotlambda** 2024-02-28 23:56 UTC
Labels: 0.kind: bug

**Comment by HippieMitch** [comment] 2024-02-29 05:24
Thanks!  Sorry this was in the wrong place.  I realize it is technically a build error and not a bug, but I just couldn't pinpoint the responsible package.  I will try --show-trace with issues in the future.
