### ISSUE TITLE
nixpkg: no space left on devace

### ISSUE THREAD

**Issue by Pitometsu** [NixOS/nixpkgs#12240] opened 2016-01-08 16:12 UTC
```
project > nix-shell --show-trace --run 'zsh'
error: while evaluating the attribute ‘bundler’ of the derivation ‘holdem-0.1’ at /home/netsu/Projects/Holdem/default.nix:5:3:
while evaluating the attribute ‘ruby’ of the derivation ‘ruby-2.2.3-p0-bundler-2015-01-11’ at /nix/store/plmwmzd5v036r41bah692qn9yasa4xil-nixos-16.03pre73316.93d8671/nixos/pkgs/development/interpreters/ruby/gem.nix:23:3:
while evaluating the attribute ‘stdenv’ of the derivation ‘ruby-2.2.3-p0’ at /nix/store/plmwmzd5v036r41bah692qn9yasa4xil-nixos-16.03pre73316.93d8671/nixos/pkgs/development/interpreters/ruby/default.nix:38:9:
while evaluating the attribute ‘shell’ of the derivation ‘stdenv’ at /nix/store/plmwmzd5v036r41bah692qn9yasa4xil-nixos-16.03pre73316.93d8671/nixos/pkgs/stdenv/generic/default.nix:238:14:
while evaluating the attribute ‘shell’ at /nix/store/plmwmzd5v036r41bah692qn9yasa4xil-nixos-16.03pre73316.93d8671/nixos/pkgs/build-support/cc-wrapper/default.nix:38:10:
while evaluating the attribute ‘stdenv’ of the derivation ‘bash-4.3-p42’ at /nix/store/plmwmzd5v036r41bah692qn9yasa4xil-nixos-16.03pre73316.93d8671/nixos/pkgs/shells/bash/default.nix:15:3:
while evaluating the attribute ‘defaultNativeBuildInputs’ of the derivation ‘stdenv-linux-boot’ at /nix/store/plmwmzd5v036r41bah692qn9yasa4xil-nixos-16.03pre73316.93d8671/nixos/pkgs/stdenv/generic/default.nix:238:14:
while evaluating the attribute ‘stdenv’ of the derivation ‘xz-5.2.2’ at /nix/store/plmwmzd5v036r41bah692qn9yasa4xil-nixos-16.03pre73316.93d8671/nixos/pkgs/tools/compression/xz/default.nix:4:3:
writing to file: No space left on device
```

[Derivation](http://nixpaste.lbr.uno/z1NYFhlm)

...What did do I wrong?

**Comment by mogorman** [comment] 2016-01-08 16:28
did you run out of disk space?

**Comment by Pitometsu** [comment] 2016-01-08 16:30
50Gb for root not enough yet?

**Comment by mogorman** [comment] 2016-01-08 16:32
i would think it would be.  when you run df do you have free disk space?

**Comment by Pitometsu** [comment] 2016-01-08 16:32
Yes, you right. Even after `nix-collect-garbage -d` 98% used. But I have pretty minimalistic desktop environment! So what is an issue in this case?

**Comment by mogorman** [comment] 2016-01-08 16:34
i have a script called empty-trash which i run as root.  it cleans up all old generations so use carefully
```
#!/usr/bin/env bash
nix-env --delete-generations old
nix-collect-garbage
nix-collect-garbage -d
nix-store --gc --print-dead
```

**Comment by mogorman** [comment] 2016-01-08 16:35
i take it this is problem with your other bug.  try it and if it solves problem please close both bugs

**Comment by Pitometsu** [comment] 2016-01-08 16:36
I not use nix-env, so nxc (nix-collect-garbage -d alias for me) should work enough. What `nix-store --gc --print-dead` is for?

**Comment by mogorman** [comment] 2016-01-08 16:39
deletes unreachable paths in the nix-store and tells you what they were if they existed

**Comment by Pitometsu** [comment] 2016-01-08 16:41
@mogorman ok, thanks! Few minutes to check all.

**Comment by mogorman** [comment] 2016-01-08 16:42
also you could do a du -h on /nix/store to confirm it is nix thats taking up all your space

**Comment by Pitometsu** [comment] 2016-01-08 16:44
probably yes, because it already cleanup 15Gb for me. Nixpkg should really care about compression or so... Or I should cleanup it each time.

**Comment by mogorman** [comment] 2016-01-08 16:50
not each time just sometimes.   you mind closing these bugs i assume they are caused by your low disk space

**Comment by Pitometsu** [comment] 2016-01-08 16:51
`.\_/.` 50Gb isn't low yet!

**Comment by Pitometsu** [comment] 2016-01-08 16:52
Let me check nix-shell...

**Comment by offlinehacker** [comment] 2016-01-08 16:56
It, looks like you run out of disk space on your devace :D

V pet., 8. jan. 2016 5:12 pop. je oseba Netsu <notifications@github.com>
napisala:

**Comment by Pitometsu** [comment] 2016-01-08 16:56
@mogorman BTW, on `nix-env --delete-generations old`
I got
```
error: ‘/nix/var/nix/profiles/per-user/username’ is not a symlink
```
Same for root.

**Comment by Pitometsu** [comment] 2016-01-08 16:58
@offlinehacker thank you, captain!

**Comment by mogorman** [comment] 2016-01-08 16:59
the files in that dir are symlinks right? '/nix/var/nix/profiles/per-user/username’

**Comment by Pitometsu** [comment] 2016-01-08 17:01
@mogorman now for nix-shell have only one warning:

```
> nix-shell --show-trace --run 'zsh'
warning: dumping very large path (> 256 MiB); this may run out of memory
>_
```

**Comment by Pitometsu** [comment] 2016-01-08 17:06
```
> ll /nix/var/nix/profiles/per-user
total 8.0K
drwxr-xr-x 2 netsu users 4.0K Jan  8 18:45 username
drwxr-xr-x 2 root  root  4.0K Jan  8 18:45 root
root@hackbook> ll /nix/var/nix/profiles/per-user/root
total 4.0K
lrwxrwxrwx 1 root root 16 Jan  8 18:14 channels -> channels-44-link
lrwxrwxrwx 1 root root 60 Jan  8 17:37 channels-44-link -> /nix/store/7xfgvgir2ap2csm3l0fz1affwryazq7b-user-environment
root@hackbook> ll /nix/var/nix/profiles/per-user/username
total 8.0K
lrwxrwxrwx 1 username users 15 Oct 10 01:59 channels -> channels-1-link
lrwxrwxrwx 1 username users 60 Oct 10 01:59 channels-1-link -> /nix/store/27wr7i3ign059xzdfwc7rkm2dam7sr3m-user-environment
lrwxrwxrwx 1 username users 14 Sep  1 21:15 profile -> profile-6-link
lrwxrwxrwx 1 username users 60 Sep  1 21:15 profile-6-link -> /nix/store/zxn68vqsy4li8v99f8gaidw7v8s1azmh-user-environment
root@hackbook>
```

**Comment by peti** [comment] 2016-01-08 17:10
Duplicate of https://github.com/NixOS/nixpkgs/issues/12241, no?

**Closed by peti** 2016-01-08 17:10 UTC

**Comment by Pitometsu** [comment] 2016-01-08 17:16
@peti, no. We discuss 2 things here also: error about symlinks in **profiles** and warning about large path in **nix-shell**. Could you reopen issue, because both, error and the warning not solved yet. Thank you.

**Comment by Pitometsu** [comment] 2016-01-08 17:24
@peti ?... Ok, thanks, no problem. I'll create new two.

**Comment by vcunat** [comment] 2016-01-08 17:25
The large-path warning is normal. The only thing it can cause AFAIK is depleting your RAM.

**Comment by Pitometsu** [comment] 2016-01-08 17:29
@vcunat thanks, I create [issue](https://github.com/NixOS/nixpkgs/issues/12243) already.
Can I somehow solve this warning? I shouldn't got warning in case if I just do all in right way.

**Comment by peti** [comment] 2016-01-08 17:37
No, you can not solve that warning (except by reducing the size of the directory that's copied into the store when you enter `nix-shell`).
