### ISSUE TITLE
Games fail to start in Steam when setting gamescope in Launch Options

### ISSUE THREAD

**Issue by Kojuma04** [NixOS/nixpkgs#266551] opened 2023-11-09 23:56 UTC
### Describe the bug
Games fail to start when setting gamescope in Steam launch options, but only when using `programs.gamescope.enable = true`, it works normally when installing gamescope via `environment.systemPackages`.

### Steps To Reproduce
1. set `programs.gamescope.enable = true` in configuration.nix
2. set `gamescope -- %command%` in Steam Launch options
3. try to start a game

### Expected behavior
Game starts normally but inside a gamescope session.

**Comment by SuperSamus** [comment] 2023-11-11 21:00
Duplicate of #214275.

**Comment by Lord-Valen** [comment] 2023-12-13 00:56
Closing as duplicate.

**Closed by Lord-Valen** 2023-12-13 00:56 UTC
Labels: 0.kind: bug
