### ISSUE TITLE
`python3Packages.psutil` is causing segfaults on darwin

### ISSUE THREAD

**Issue by risicle** [NixOS/nixpkgs#146760] opened 2021-11-20 13:43 UTC
### Describe the bug
For a while now, some `python3Packages.psutil` routines have been segfaulting on darwin. This has become more problematic recently because newer versions of `python3Packages.distributed` make a call to `psutil.disk_io_counters()`, which pretty robustly segfaults on darwin. Packages that use `python3Packages.distributed` in their tests are failing as a result. e.g. https://hydra.nixos.org/log/x8a5k4lvfmnlyp088slxg0c72j1a7hq9-python3.8-stumpy-1.9.2.drv. `python3Packages.psutil`'s own tests are of course disabled because they have proven to be so problematic.

We've opened some upstream issues for these problems (https://github.com/giampaolo/psutil/issues/2009, https://github.com/giampaolo/psutil/issues/1715), but I'm increasingly starting to feel these are Our Bugs.

The next step is probably to do some proper debugging on these segfaults, but I personally lack the motivation to learn darwin's weird debugging ecosystem (give me gdb and ELF anyday), so instead I'm documenting my findings here.

### Steps To Reproduce
1. Be on darwin (tested x86_64, macos 10.15)
2. 
```
$ nix-shell -p python38Packages.psutil --pure --run python
Python 3.8.8 (default, Jun 15 2021, 08:25:07) 
[Clang 7.1.0 (tags/RELEASE_710/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.disk_io_counters()
/private/tmp/nix-shell-4915-0/rc: line 1:  4918 Segmentation fault: 11  python
```

When I use a pip-installed version on the same machine it succeeds:

```
$ nix-shell -p python38 --pure

[nix-shell:~]$ python -m venv venv

[nix-shell:~]$ . venv/bin/activate
(venv) 
[nix-shell:~]$ pip install psutil
Collecting psutil
  Downloading psutil-5.8.0-cp38-cp38-macosx_10_9_x86_64.whl (236 kB)
     |████████████████████████████████| 236 kB 23.5 MB/s 
Installing collected packages: psutil
Successfully installed psutil-5.8.0
WARNING: You are using pip version 20.2.3; however, version 21.3.1 is available.
You should consider upgrading via the '/Users/bob/venv/bin/python -m pip install --upgrade pip' command.
(venv) 
[nix-shell:~]$ python
Python 3.8.8 (default, Jun 15 2021, 08:25:07) 
[Clang 7.1.0 (tags/RELEASE_710/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.disk_io_counters()
sdiskio(read_count=27110, write_count=309745, read_bytes=3164171264, write_bytes=6676201472, read_time=23219, write_time=58976)
>>> 
```

### Notify maintainers
@jonringer @NixOS/darwin-maintainers @teh @costrouc 

### Metadata

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python3Packages.psutil python3Packages.distributed python3Packages.stumpy
# a list of nixos modules affected by the problem
module:
```

**Comment by reckenrode** [comment] 2021-11-20 13:57
I can’t reproduce on aarch64-darwin running macOS 12.0.1. I tried both the aarch64 and x86_64 builds of Python. (Not saying this isn’t a problem, but it may be that it’s dependent on the macOS version being run.)

```
reckenrode@dyrstelice ~/D/python-testing> nix shell nixpkgs#python38 
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
reckenrode@dyrstelice ~/D/python-testing> python -m venv venv
reckenrode@dyrstelice ~/D/python-testing> source venv/bin/activate.fish 
(venv) reckenrode@dyrstelice ~/D/python-testing> pip install psutil
Collecting psutil
  Downloading psutil-5.8.0.tar.gz (470 kB)
     |████████████████████████████████| 470 kB 3.0 MB/s 
Using legacy 'setup.py install' for psutil, since package 'wheel' is not installed.
Installing collected packages: psutil
    Running setup.py install for psutil ... done
Successfully installed psutil-5.8.0
WARNING: You are using pip version 21.1.1; however, version 21.3.1 is available.
You should consider upgrading via the '/Users/reckenrode/Developer/python-testing/venv/bin/python -m pip install --upgrade pip' command.
(venv) reckenrode@dyrstelice ~/D/python-testing> python
Python 3.8.11 (default, Sep  2 2021, 11:54:43) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.disk_io_counters()
sdiskio(read_count=35615807, write_count=8211080, read_bytes=2618724024320, write_bytes=144779620352, read_time=9463055, write_time=634505)
>>> psutil.sensors_battery()
sbattery(percent=100, secsleft=26820, power_plugged=False)
>>> 
```

**Comment by risicle** [comment] 2021-11-20 14:01
That is an interesting data point, because I'm quite certain that our `aarch64-darwin` uses a much newer SDK version.

**Comment by risicle** [comment] 2021-11-20 14:06
Does the _first_ of my two snippets fail on your `aarch64-darwin` system?

**Comment by reckenrode** [comment] 2021-11-20 15:42
Sorry, yeah. I tested that first but posted the second results. Here’s what I get with the first snippet.

```
> nix-shell -p python38Packages.psutil --pure --run python
Python 3.8.11 (default, Sep  2 2021, 11:54:43) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.disk_io_counters()
sdiskio(read_count=35966804, write_count=8307065, read_bytes=2622787362816, write_bytes=146699354112, read_time=9528325, write_time=641991)
>>> psutil.sensors_battery()
sbattery(percent=90, secsleft=34680, power_plugged=False)
>>> 
```

**Comment by reckenrode** [comment] 2021-11-20 15:44
I just tested the x86_64-darwin binaries on my aarch64-darwin system and got the crash.

```
> nix-shell -p python38Packages.psutil --pure --run python --system x86_64-darwin
Python 3.8.11 (default, Sep  2 2021, 11:58:38) 
[Clang 7.1.0 (tags/RELEASE_710/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.disk_io_counters()
/private/tmp/nix-shell-27803-0/rc: line 3: 27810 Segmentation fault: 11  python
```

**Comment by risicle** [comment] 2021-11-20 15:49
Ok so it is still potentially SDK-version-related.

**Comment by kira-bruneau** [comment] 2021-11-20 16:19
This sounds very similar to the problem in #144704. I wonder if it's related.

**Comment by thefloweringash** [comment] 2021-11-21 04:12
I had a look at this when it was mentioned on matrix. From what I can tell the crash occurs as soon as psutil tries to interact with CoreFoundation types returned from querying the system. I did some printf style debugging by adding calls to `CFShow`, and all I could get was a crash.

I suspect it's related to mixing and matching system CoreFoundation with swift-corefoundation built from source. I haven't gotten to the bottom of the issue yet, but if psutil is explicitly linked with system CoreFoundation[1], then it seems to work.

```
❯ nix shell  --impure --ignore-environment \
  --expr 'let pkgs = import ./. {}; in
    pkgs.python3.withPackages (ps: [ ps.psutil ])' \
  -c python3 -c "import psutil;  print(psutil.disk_io_counters())"
zsh: segmentation fault  nix shell --impure --ignore-environment --expr  -c python3 -c
```

```
❯ nix shell  --impure --ignore-environment \
  --expr 'let pkgs = import ./. {}; in
    pkgs.python3.withPackages (ps: [ (ps.psutil.overrideAttrs (o: { buildInputs = o.buildInputs ++ [ pkgs.darwin.apple_sdk.frameworks.CoreFoundation ]; })) ])' \
  -c python3 -c "import psutil;  print(psutil.disk_io_counters())"
sdiskio(read_count=106957535, write_count=67988818, read_bytes=980611539968, write_bytes=938397880320, read_time=134130953, write_time=485462107)
```

---
[1] In the nix expression for using system CoreFoundation, there's a [hook](https://github.com/NixOS/nixpkgs/blob/d7845680a52e8bbb16f75409f0aa3b242258e909/pkgs/os-specific/darwin/apple-sdk/cf-setup-hook.sh#L6) that forces the the linker to use system corefoundation.

<details>
<summary>`otool -L` comparison</summary>


Without: 
```
❯ otool -L /nix/store/sg1d6cs4kswr8cjsasfhcbjmhi6gz2g1-python3.9-psutil-5.8.0/lib/python3.9/site-packages/psutil/_psutil_osx.cpython-39-darwin.so
/nix/store/sg1d6cs4kswr8cjsasfhcbjmhi6gz2g1-python3.9-psutil-5.8.0/lib/python3.9/site-packages/psutil/_psutil_osx.cpython-39-darwin.so:
	@rpath/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1454.90.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```

With
```
❯ otool -L /nix/store/vgkssvaraqy3j8pzmdyk9s4hfpy1bs69-python3.9-psutil-5.8.0/lib/python3.9/site-packages/psutil/_psutil_osx.cpython-39-darwin.so
/nix/store/vgkssvaraqy3j8pzmdyk9s4hfpy1bs69-python3.9-psutil-5.8.0/lib/python3.9/site-packages/psutil/_psutil_osx.cpython-39-darwin.so:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1349.8.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```

</details>

**Comment by wa1one** [comment] 2021-12-04 21:28
how to resolve the issue?

**Comment by pratikgajjar** [comment] 2022-12-27 18:41
```
Package operations: 48 installs, 0 updates, 0 removals

  • Installing psutil (5.9.1): Failed

  CalledProcessError

  Command '['/Users/pratikgajjar/.venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/Users/pratikgajjar/.venv', '--no-deps', '/Users/pratikgajjar/Library/Caches/pypoetry/artifacts/2c/c1/7d/613aa355414622095ce2c5f0fcf5e6541a40ca83ca5cb6ef7d7d554cba/psutil-5.9.1.tar.gz']' returned non-zero exit status 1.

  at /opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py:524 in run
       520│             # We don't call process.wait() as .__exit__ does that for us.
       521│             raise
       522│         retcode = process.poll()
       523│         if check and retcode:
    →  524│             raise CalledProcessError(retcode, process.args,
       525│                                      output=stdout, stderr=stderr)
       526│     return CompletedProcess(process.args, retcode, stdout, stderr)
       527│
       528│

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/Users/pratikgajjar/.venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/Users/pratikgajjar/.venv', '--no-deps', '/Users/pratikgajjar/Library/Caches/pypoetry/artifacts/2c/c1/7d/613aa355414622095ce2c5f0fcf5e6541a40ca83ca5cb6ef7d7d554cba/psutil-5.9.1.tar.gz'] errored with the following return code 1, and output:
  Processing /Users/pratikgajjar/Library/Caches/pypoetry/artifacts/2c/c1/7d/613aa355414622095ce2c5f0fcf5e6541a40ca83ca5cb6ef7d7d554cba/psutil-5.9.1.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Building wheels for collected packages: psutil
    Building wheel for psutil (pyproject.toml): started
    Building wheel for psutil (pyproject.toml): finished with status 'error'
    error: subprocess-exited-with-error

    × Building wheel for psutil (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [51 lines of output]
        running bdist_wheel
        running build
        running build_py
        creating build
        creating build/lib.macosx-12-arm64-cpython-310
        creating build/lib.macosx-12-arm64-cpython-310/psutil
        copying psutil/_pswindows.py -> build/lib.macosx-12-arm64-cpython-310/psutil
        copying psutil/_common.py -> build/lib.macosx-12-arm64-cpython-310/psutil
        copying psutil/__init__.py -> build/lib.macosx-12-arm64-cpython-310/psutil
        copying psutil/_psosx.py -> build/lib.macosx-12-arm64-cpython-310/psutil
        copying psutil/_psbsd.py -> build/lib.macosx-12-arm64-cpython-310/psutil
        copying psutil/_psaix.py -> build/lib.macosx-12-arm64-cpython-310/psutil
        copying psutil/_pslinux.py -> build/lib.macosx-12-arm64-cpython-310/psutil
        copying psutil/_compat.py -> build/lib.macosx-12-arm64-cpython-310/psutil
        copying psutil/_psposix.py -> build/lib.macosx-12-arm64-cpython-310/psutil
        copying psutil/_pssunos.py -> build/lib.macosx-12-arm64-cpython-310/psutil
        creating build/lib.macosx-12-arm64-cpython-310/psutil/tests
        copying psutil/tests/test_contracts.py -> build/lib.macosx-12-arm64-cpython-310/psutil/tests
        copying psutil/tests/test_connections.py -> build/lib.macosx-12-arm64-cpython-310/psutil/tests
        copying psutil/tests/runner.py -> build/lib.macosx-12-arm64-cpython-310/psutil/tests
        copying psutil/tests/test_unicode.py -> build/lib.macosx-12-arm64-cpython-310/psutil/tests
        copying psutil/tests/test_misc.py -> build/lib.macosx-12-arm64-cpython-310/psutil/tests
        copying psutil/tests/test_posix.py -> build/lib.macosx-12-arm64-cpython-310/psutil/tests
        copying psutil/tests/test_linux.py -> build/lib.macosx-12-arm64-cpython-310/psutil/tests
        copying psutil/tests/test_sunos.py -> build/lib.macosx-12-arm64-cpython-310/psutil/tests
        copying psutil/tests/__init__.py -> build/lib.macosx-12-arm64-cpython-310/psutil/tests
        copying psutil/tests/test_aix.py -> build/lib.macosx-12-arm64-cpython-310/psutil/tests
        copying psutil/tests/test_process.py -> build/lib.macosx-12-arm64-cpython-310/psutil/tests
        copying psutil/tests/test_bsd.py -> build/lib.macosx-12-arm64-cpython-310/psutil/tests
        copying psutil/tests/test_system.py -> build/lib.macosx-12-arm64-cpython-310/psutil/tests
        copying psutil/tests/test_osx.py -> build/lib.macosx-12-arm64-cpython-310/psutil/tests
        copying psutil/tests/test_memleaks.py -> build/lib.macosx-12-arm64-cpython-310/psutil/tests
        copying psutil/tests/test_windows.py -> build/lib.macosx-12-arm64-cpython-310/psutil/tests
        copying psutil/tests/__main__.py -> build/lib.macosx-12-arm64-cpython-310/psutil/tests
        copying psutil/tests/foo.py -> build/lib.macosx-12-arm64-cpython-310/psutil/tests
        copying psutil/tests/test_testutils.py -> build/lib.macosx-12-arm64-cpython-310/psutil/tests
        running build_ext
        building 'psutil._psutil_osx' extension
        creating build/temp.macosx-12-arm64-cpython-310
        creating build/temp.macosx-12-arm64-cpython-310/psutil
        creating build/temp.macosx-12-arm64-cpython-310/psutil/arch
        creating build/temp.macosx-12-arm64-cpython-310/psutil/arch/osx
        clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -I/opt/homebrew/Cellar/gdal/3.5.2/include -I/opt/homebrew/opt/openssl@3/include -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=591 -DPSUTIL_OSX=1 -I/Users/pratikgajjar/-root/.venv/include -I/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c psutil/_psutil_common.c -o build/temp.macosx-12-arm64-cpython-310/psutil/_psutil_common.o
        clang-11: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
        clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -I/opt/homebrew/Cellar/gdal/3.5.2/include -I/opt/homebrew/opt/openssl@3/include -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=591 -DPSUTIL_OSX=1 -I/Users/pratikgajjar/-root/.venv/include -I/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c psutil/_psutil_osx.c -o build/temp.macosx-12-arm64-cpython-310/psutil/_psutil_osx.o
        clang-11: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
        psutil/_psutil_osx.c:31:10: fatal error: 'IOKit/IOKitLib.h' file not found
        #include <IOKit/IOKitLib.h>
                 ^~~~~~~~~~~~~~~~~~
        1 error generated.
        error: command '/nix/store/b9bh3z78rqff14bf0fd78xb07b5cnwdw-clang-wrapper-11.1.0/bin/clang' failed with exit code 1
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for psutil
  Failed to build psutil
  ERROR: Could not build wheels for psutil, which is required to install pyproject.toml-based projects


  at /opt/homebrew/Cellar/poetry/1.2.1/libexec/lib/python3.10/site-packages/poetry/utils/env.py:1476 in _run
      1472│                 output = subprocess.check_output(
      1473│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1474│                 )
      1475│         except CalledProcessError as e:
    → 1476│             raise EnvCommandError(e, input=input_)
      1477│
      1478│         return decode(output)
      1479│
      1480│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  PoetryException

  Failed to install /Users/pratikgajjar/Library/Caches/pypoetry/artifacts/2c/c1/7d/613aa355414622095ce2c5f0fcf5e6541a40ca83ca5cb6ef7d7d554cba/psutil-5.9.1.tar.gz

  at /opt/homebrew/Cellar/poetry/1.2.1/libexec/lib/python3.10/site-packages/poetry/utils/pip.py:51 in pip_install
       47│
       48│     try:
       49│         return environment.run_pip(*args)
       50│     except EnvCommandError as e:
    →  51│         raise PoetryException(f"Failed to install {path.as_posix()}") from e

```

Not sure if related I am getting this error

**Comment by sandangel** [comment] 2023-01-13 01:16
I  also got same error on our CI (linux amd64). Is there a workaround for this?

**Comment by toonn** [comment] 2023-01-17 23:22
Closing because of #191240 which is supposed to address this. And I can't reproduce on x86_64-darwin.

**Closed by toonn** 2023-01-17 23:22 UTC
Labels: 0.kind: bug, 6.topic: python, 6.topic: darwin
