### ISSUE TITLE
lutris: mouse capture issue in World of Warcraft

### ISSUE THREAD

**Issue by ReLoneR1** [NixOS/nixpkgs#333806] opened 2024-08-11 00:41 UTC
Basically i have the same problem, as described in [issue182813](https://github.com/NixOS/nixpkgs/issues/182813)

when i play battle.net in Lutris - i have this in logs:

1) DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.

2) `ntlm_auth: /home/reloner/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libjansson.so.4: no version information available (required by /nix/store/4gcggjvzrbywi92r66p6l15hckxng2q0-samba-4.20.1/lib/samba/libcommon-auth-private-samba.so)`

for 1st warning - i have one rtx gpu with stable 550 driver, and i am on X11. Setting  `VK_DRIVER_FILES=/run/opengl-driver/share/vulkan/icd.d/nvidia_icd.x86_64.json` variable fixed this warning, but the battle.net doesn't launch anymore.

After deleting variable `VK_DRIVER_FILES` - 1st warning returns, but the battle.net actually launches now.

So it just overall some strange behaviour, which cause a bug in the world of warcraft game (This issue doesn't appear in other distros - at least arch and tumbleweed for sure):

-the bug is 'mouse-look lock' not working:

-intendant behaviour: hold right click, cursor disappears, move mouse, release right click, cursor should appear on the same place where we initially pressed right click

-bug behaviour: after releasing right click - in-game cursor appears under new position in which we moved our mouse in mouse-look mode

PS: this issue fixes when using flatpak lutris

**Comment by ReLoneR1** [comment] 2024-08-11 20:01
this issue fixes when using flatpak lutris

**Comment by Atemu** [comment] 2024-08-17 22:36
These two warnings are benign and have nothing to do with the actual error.

Which WINE are you using?

Until you have found a concrete error that is likely to be caused by nixpkgs, I'm going to close this.

**Comment by ReLoneR1** [comment] 2024-08-18 00:29
> Which WINE are you using?
Wine which lutris autoinstalls - wineGE8-26 i believe

**Comment by ReLoneR1** [comment] 2024-09-23 15:53
> Until you have found a concrete error that is likely to be caused by nixpkgs, I'm going to close this.

What is the correct way of installing lutris? 
1) `lutris` or `lutris-unwrapped`?
2) `with pkgs`or `programs.enable`?

Mine installation is `lutris`, `with pkgs`

**Comment by Atemu** [comment] 2024-09-23 20:25
> `lutris` or `lutris-unwrapped`?

The former.

> `with pkgs`or `programs.enable`?

There is no `programs.enable` option for lutris in NixOS, you simply put `pkgs.lutris` into `environment.systemPackages`.

(FYI: `with pkgs;` is just syntax sugar. I'd invite you to research how it works to avoid future confusion.) 

> Mine wine installation was simply `wine`. Should i have used `wineWowPackages.stable`?

Lutris comes with one of our WINE packages and also manages its own WINE packages.

> If you wish to inspect, i can send my nix configuration

That's always advisable. I doubt your issue has anything to do with NixOS though. I'd seek generic help with lutris/WINE in the appropriate forums first.  
If you figure out that this is indeed a NixOS issue in the process, you can of course come back with more details and we can re-open this.

**Comment by ReLoneR1** [comment] 2024-10-05 18:56
at least i can confirm that this problem is not related only to lutris. Bottles on wineGE8-26 also does have this problem with mouse-look bug
So if native and flatpak both have their own same game-runtimes, but on native there is a mouse-look bug in wow. 
Does it mean that the problem is might be in packages that flatpak installs to replace system?

`
Mesa                                       org.freedesktop.Platform.GL.default              24.2.3      23.08            system
Mesa (Extra)                               org.freedesktop.Platform.GL.default              24.2.3      23.08-extra      system
nvidia-550-78                              org.freedesktop.Platform.GL.nvidia-550-78                    1.4              system
Mesa                                       org.freedesktop.Platform.GL32.default            24.2.3      23.08            system
nvidia-550-78                              org.freedesktop.Platform.GL32.nvidia-550-78                  1.4              system
ffmpeg-full                                org.freedesktop.Platform.ffmpeg-full                         23.08            system
i386                                       org.freedesktop.Platform.ffmpeg_full.i386                    23.08            system
openh264                                   org.freedesktop.Platform.openh264                2.1.0       2.2.0            system
GNOME Application Platform version 45      org.gnome.Platform                                           45               system
i386                                       org.gnome.Platform.Compat.i386                               45               system
DXVK                                       org.winehq.Wine.DLLs.dxvk                        2.4.1       stable-23.08     system
Gecko                                      org.winehq.Wine.gecko                                        stable-23.08     system
Mono                                       org.winehq.Wine.mono                                         stable-23.08     system
`

As far as i understand its those three: mesa, nvidia-driver, ffmpeg
Seems logical to me, but i really dont believe that the problem is in nixpkgs in some of those three
So strange bug really

**Comment by Steinhagen** [comment] 2024-10-13 22:04
`ntlm_auth: /home/reloner/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libjansson.so.4: no version information available (required by /nix/store/4gcggjvzrbywi92r66p6l15hckxng2q0-samba-4.20.1/lib/samba/libcommon-auth-private-samba.so)
`
The reason why this issue is happening is because the Lutris FHS that you are running doesn't install `jansson` as a dependency (I just checked). By default the WoW entry tries to prioritize the System's libraries and if it doesn't find something, it will fallback to the Lutris runtime. Since the runtime version is really old, you'll see that error. A PR should probably be created for the Lutris FHS to add it there...

Even so, based on my testing, fixing that version mismatch issue won't solve the mouse issue in WoW. From what I can tell (I'm not a WoW player), Nvidia isn't playing nice with with WoW for quite some time now: https://www.reddit.com/r/wow/comments/8y3p9a/comment/e2byicf/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
In my situation, the mouse reset issue was resolved by enabling rawMouseEnable in-game.

That being said, it would be extremely interesting to see what the Flatpak version is doing, but that is something to be done at a different time.

**Comment by ReLoneR1** [comment] 2024-10-14 00:03
thank you for you time and tinker on this issue. 

> In my situation, the mouse reset issue was resolved by enabling rawMouseEnable in-game.

Are you referring to described by me `mouse-look mode bug`, or this crazy mouse flickering i even forgot to mention about.

The difference between those two is: 
1) `mouse-look mode bug` - after releasing mouse -  in-game cursor appears under **new position** in which we moved our mouse in mouse-look mode
2) `flickering` - after releasing mouse -  in-game cursor appears under **completely random position**

Yes for me - enabling rawMouseEnable also solves this crazy `flickering` indeed 

But for mouse-look mode - it doesnt. I think i tried every /console command i could find on the internet - nothing helped to me with solving this

**Comment by Steinhagen** [comment] 2024-10-14 20:51
This PR should technically fix both the jasson warning and the WoW cursor issues: https://github.com/NixOS/nixpkgs/pull/348533
Please give it a try to see if it works as expected.

**Comment by ReLoneR1** [comment] 2024-10-14 23:38
@Steinhagen 
I definitely want to test it. Could i just please get some help with how to allowUnfree for steam dependency in lutris for your `lutris-fix-libjanson` branch

flake.nix:
```
 inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-24.05";
    lutrisfix.url = "github:Steinhagen/nixpkgs/lutris-fix-libjanson";
};

 outputs = { self, nixpkgs, lutrisfix }: {
    nixosConfigurations = {
      nixos = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [
          ./configuration.nix
];
specialArgs = { inherit lutrisfix; };
};
};
```

configuration.nix
```
{ config, pkgs, lutrisfix, ... }:
{
  environment.systemPackages = with pkgs; [
lutrisfix.legacyPackages."${pkgs.system}".lutris
];
nixpkgs.config.allowUnfree = true;
}
```

**Comment by ReLoneR1** [comment] 2024-10-15 00:54
okay so i managed to install lutris from your `lutris-fix-libjanson` branch as a flake input

I never saw this behavior, but battle.net install script from lutris fails at the very beginning of the installation

here is a an output:
```
Executing cd /home/reloner/.cache/winetricks/corefonts
Downloading https://github.com/pushcx/corefonts/raw/master/arial32.exe to /home/reloner/.cache/winetricks/corefonts
/home/reloner/.local/share/lutris/runtime/winetricks/winetricks: строка 1239:  9151 Segmentation fault      (memory image flushed to disk) ${torify} wget "$@"
Executing cd /home/reloner/.cache/winetricks/corefonts
Downloading https://web.archive.org/web/2000/https://github.com/pushcx/corefonts/raw/master/arial32.exe to /home/reloner/.cache/winetricks/corefonts
/home/reloner/.local/share/lutris/runtime/winetricks/winetricks: строка 1239:  9203 Segmentation fault      (memory image flushed to disk) ${torify} wget "$@"
------------------------------------------------------
warning: Downloading https://web.archive.org/web/2000/https://github.com/pushcx/corefonts/raw/master/arial32.exe failed
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
```
```
Traceback (most recent call last):
  File "/nix/store/jdhpw2wshsck6v5bjqvd1vc0i247v68p-lutris-unwrapped-0.5.17/lib/python3.12/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/jdhpw2wshsck6v5bjqvd1vc0i247v68p-lutris-unwrapped-0.5.17/lib/python3.12/site-packages/lutris/installer/commands.py", line 446, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Command exited with code 256
```

**Comment by Atemu** [comment] 2024-10-15 05:14
> warning: Downloading https://web.archive.org/web/2000/https://github.com/pushcx/corefonts/raw/master/arial32.exe failed

The IA is currently under hostile attack and therefore not operational. (Also boo them for relying on the IA as a CDN :/)

IIRC lutris lets you customise the installation; you should be able to stop it from trying to install the fonts. 

You shouldn't need to re-install battle.net though?

**Comment by Steinhagen** [comment] 2024-10-15 05:22
No, you shouldn't need to reinstall battle.net. The problem was that the Lutris FHS didn't contained a number of xorg packages. Any Bottle should work just fine as it was.

**Comment by ReLoneR1** [comment] 2024-10-15 11:41
i added a battle.net (~/.Games/battle.net) which was installed by my flatpak-lutris - to the lutris from your branch with the help of this comment [lutris forum](https://forums.lutris.net/t/importing-and-running-already-installed-game-files/20270/3)

In the lutris console there are no warnings about jansson
In Game - the mouse-look bug is fixed :)

**Comment by Atemu** [comment] 2024-10-15 12:24
@ReLoneR1 could you add that info to the PR as a review?

**Comment by ReLoneR1** [comment] 2024-10-15 12:31
Should i just copy-paste the same text into the comment section of PR? I dont know how to add it as a `review`

**Closed** 2024-10-16 11:43 UTC
Labels: 0.kind: bug

**Comment by KennethHoff** [comment] 2024-11-20 20:30
I am experiencing this same exact issue using `Heroic Games Launcher`. I'm gonna try out `Lutris` now, to see if that fixes it, but is it possible to migrate these fixes over there as well?

**Comment by Steinhagen** [comment] 2024-11-20 20:45
> I am experiencing this same exact issue using `Heroic Games Launcher`. I'm gonna try out `Lutris` now, to see if that fixes it, but is it possible to migrate these fixes over there as well?

Yes. Those fixes should be ported to Heroic Games Launcher as well. You can give it a try to see if it works, but from looking at the code, the needed xorg packages are missing from the Heroic FHS.

**Comment by KennethHoff** [comment] 2024-11-20 20:49
I've never done anything like this. Started using NixOS last month and I have not looked into packaging things. Considering you seemingly both found the issue _and_ fixed it I assume you have considerable knowledge in this area, would you be willing to do this?

**Comment by KennethHoff** [comment] 2024-11-20 20:55
To be clear, as it seems like there are two issues at play here. The issue I'm experiencing with Heroic is the weirdness with the mouse cursor in World of Warcraft. I might have something in some log file somewhere, but I don't know where that would be.

**Comment by Steinhagen** [comment] 2024-11-20 20:59
I will backport it, but will take a bit to download the thing and see if it works as expected.

**Comment by KennethHoff** [comment] 2024-11-20 21:01
Just for reference, I booted up WoW with Lutris just now, and it _does_ work as it should there!

**Comment by Steinhagen** [comment] 2024-11-21 22:31
I've created a PR that fixes the mouse issues for the Heroic launcher. Based on my testing, everything works as expected. You can give it a try and confirm that everything is working: https://github.com/NixOS/nixpkgs/pull/358010

**Comment by KennethHoff** [comment] 2024-11-22 06:33
I'd love to, but how would I do that? Change the nixpkgs flake input to point to your branch? If so, how would I do that? 😅

**Comment by Steinhagen** [comment] 2024-11-22 08:03
I've left a note in the PR mentioning how you can test the Heroic application from the fix branch via flakes. Probably that's the best way so that you won't completely change your system on top of master.
