### ISSUE TITLE
by-name check failures are an illegible mess

### ISSUE THREAD

**Issue by amjoseph-nixpkgs** [NixOS/nixpkgs#266930] opened 2023-11-11 23:36 UTC
srsl ppl wtf

![screenshot-20231111-153404](https://github.com/NixOS/nixpkgs/assets/54836058/277afb26-96a1-43f6-8e98-cd7c8b90a5e5)

**Comment by FliegendeWurst** [comment] 2023-11-12 22:04
#257748 is related

**Comment by infinisil** [comment] 2023-11-12 23:55
@amjoseph-nixpkgs I really don't appreciate your tone on these issues.. Anyways this is indeed a duplicate of https://github.com/NixOS/nixpkgs/issues/257748.

**Comment by amjoseph-nixpkgs** [comment] 2023-11-13 03:46
> @amjoseph-nixpkgs I really don't appreciate your tone on these issues

I mean do you want to read what's shown in the screenshot above?

I sorta don't appreciate the way the `pkgs/by-name` checks have morphed into a gatekeeping mechanism, and I'm particularly peeved about the fact that we spent ~2 hours on IRC discussing how to make all of this *deterministic* and *not github-dependent* -- a discussion where we clearly seemed to agree on the way forward.  Then you just sort of ignored all of that, implemented the checks in github-ese, and didn't let me know or even request a review.

So yeah, there are a lot of things I don't appreciate about what's going on with the `pkgs/by-name` checks.

**Comment by infinisil** [comment] 2023-11-21 06:08
That's no reason to be double-tracking issues though. But also this is now fixed since https://github.com/NixOS/nixpkgs/pull/267048

**Closed by infinisil** 2023-11-21 06:08 UTC
Labels: 0.kind: bug, 6.topic: developer experience
