### ISSUE TITLE
cups-filters fail to build

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#44305] opened 2018-08-01 16:34 UTC
## Issue description

```
  CC       pdftops-common.o
  CC       pdftops-pdftops.o
  CCLD     pdftops
  CC       rastertoescpx-rastertoescpx.o
  CCLD     rastertoescpx
  CC       rastertopclx-pcl-common.o
  CC       rastertopclx-rastertopclx.o
  CCLD     rastertopclx
  CC       texttopdf-common.o
  CC       texttopdf-pdfutils.o
  CC       texttopdf-textcommon.o
  CC       texttopdf-texttopdf.o
  CCLD     texttopdf
  CXX      rastertopdf-rastertopdf.o
  CXXLD    rastertopdf
  CC       rastertops-rastertops.o
  CCLD     rastertops
  CC       bannertopdf-banner.o
  CC       bannertopdf-bannertopdf.o
  CXX      bannertopdf-pdf.o
filter/pdf.cxx: In function 'int pdf_fill_form(pdf_t*, opt_t*)':
filter/pdf.cxx:740:44: error: invalid conversion from 'const GooString*' to 'GooString*' [-fpermissive]
             field_name = ff->getPartialName();
                          ~~~~~~~~~~~~~~~~~~^~
make[1]: *** [Makefile:3937: bannertopdf-pdf.o] Error 1
make[1]: Leaving directory '/tmp/nix-build-cups-filters-1.20.4.drv-0/cups-filters-1.20.4'
make: *** [Makefile:1975: all] Error 2
builder for '/nix/store/bshxw2d6zg5cw134nv5zch9favrn7gqp-cups-filters-1.20.4.drv' failed with exit code 2
cannot build derivation '/nix/store/dmsyjfllcxp0ppxqqi0lnsvi502fkmh6-cups-progs.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/jgkjj5fqm7lfmzsh37zpczfzpgdpzky2-system-config-printer-1.5.11.drv': 1 dependencies couldn't be built                                                                                                    
cannot build derivation '/nix/store/219wcb4lz5fkp2idg6lsc8hhivnlnff6-unit-cups-browsed.service.drv': 1 dependencies couldn't be built    
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.6, NixOS, 18.09pre146020.e8ec91bb595 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(hyper): `"nixos-18.03pre123638.1258d9a4914"`
 - channels(root): `"nixos-18.09pre147769.333a6646a8b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment] 2018-08-01 16:51
Duplicate of https://github.com/NixOS/nixpkgs/issues/44282

**Closed by jtojnar** 2018-08-01 16:51 UTC
