### ISSUE TITLE
elm fails to build on unstable

### ISSUE THREAD

**Issue by jgillich** [NixOS/nixpkgs#14028] opened 2016-03-18 19:26 UTC
Seeing some weird elm test failures on a trusty travis VM, like:
```
    tests/test-files/good/Soundness/SpecificAnnotationInt.elm: [Failed]

Compiled JS did not match expected JS.

  If the change is intentional, rerun the tests with environment variable: ELM_WRITE_NEW_EXPECTED=1

expected: "Elm.Main = Elm.Main || {};\nElm.Main.make = function (_elm) {\n   \"use strict\";\n   _elm.Main = _elm.Main || {};\n   if (_elm.Main.values) return _elm.Main.values;\n   var _U = Elm.Native.Utils.make(_elm);\n   var _op = {};\n   var px = function (x) {    return \"test\";};\n   return _elm.Main.values = {_op: _op,px: px};\n};"

 but got: "Elm.Main = Elm.Main || {};\nElm.Main.make = function (_elm) {\n       \"use strict\";\n       _elm.Main = _elm.Main || {};\n       if (_elm.Main.values)    return _elm.Main.values;\n       var _U = Elm.Native.Utils.make(_elm);\n       var _op = {};\n       var px = function (x) { return \"test\";};\n       return _elm.Main.values = {_op: _op,px: px};\n    };"
```
https://travis-ci.org/jgillich/mp/builds/116983036

cc @abbradar

**Comment by abbradar** [comment] 2016-03-18 22:03
I've tried to build `master` but run into the same issue. I guess it's an upstream problem (underconstrained dependencies). I need to go now so I can open a bug only tomorrow evening -- if you want you can do it earlier ~_^.

**Comment by jgillich** [comment] 2016-03-18 22:08
But how can it be an upstream problem when we didn't update the package? :confused:

**Comment by abbradar** [comment] 2016-03-18 23:19
Well, it's not strongly "upstream" problem -- I think some dependency has updated and broken Elm, so they need to tighten upper bounds for a library that causes this. The problem is -- we don't know which one.

**Comment by jgillich** [comment] 2016-03-18 23:23
Ah I see. I'll do some digging tomorrow and maybe open a bug (tried asking in IRC, without success).

**Comment by abbradar** [comment] 2016-03-20 00:14
@jgillich Thanks for opening a bug. I spent some time to play around with this but no luck. Developers might know better what generates those strings (and spaces) in the first place.

**Comment by jgillich** [comment] 2016-03-23 17:01
Even is busy with the new release I guess. Would really like to see this fixed, but I also have no idea where to look (and don't know any Haskell).

**Comment by abbradar** [comment] 2016-03-23 18:36
Closed by https://github.com/NixOS/nixpkgs/commit/f0187cb4c3de7455bc595ee73a22c9d2573f2581

**Closed by abbradar** 2016-03-23 18:36 UTC
Labels: 0.kind: bug

**Comment by jgillich** [comment] 2016-03-23 18:43
Yay :+1:
