### ISSUE TITLE
Request: GDLauncher

### ISSUE THREAD

**Issue by cyl3x** [NixOS/nixpkgs#214513] opened 2023-02-04 09:14 UTC
**Project description**
GDLauncher is a simple, yet powerful Minecraft custom launcher with a strong focus on the user experience. 

_Probably the best and easiest Minecraft launcher to use_

**Metadata**

* homepage URL: https://gdlauncher.com
* source URL: https://github.com/gorilla-devs/GDLauncher
* license: GPL 3
* platforms: linux, darwin

**Comment by huantianad** [comment] 2023-11-21 00:38
Duplicate of #151244.

**Closed by huantianad** 2023-11-21 00:38 UTC
Labels: 0.kind: packaging request
