### ISSUE TITLE
When I try to open xxxfile. ipynb in pycharm  ， I get  the error “JCEF is not supported in this env...”

### ISSUE THREAD

**Issue by prehonor** [NixOS/nixpkgs#109347] opened 2021-01-14 08:29 UTC
<details><summary>Log</summary>
<p>

2021-01-14 16:22:22,052 [  16359]  ERROR - tor.impl.FileEditorManagerImpl - JCEF is not supported in this env or failed to initialize 
java.lang.IllegalStateException: JCEF is not supported in this env or failed to initialize
        at com.intellij.ui.jcef.JBCefApp.getInstance(JBCefApp.java:195)
        at com.intellij.ui.jcef.JBCefBrowser.<init>(JBCefBrowser.java:383)
        at org.jetbrains.plugins.notebooks.jupyter.editor.preview.jcefWithWs.JupyterPreviewJCefView.<init>(JupyterPreviewJCefView.kt:27)
        at org.jetbrains.plugins.notebooks.jupyter.editor.preview.jcefWithWs.JupyterPreviewJCefView.<init>(JupyterPreviewJCefView.kt:20)
        at org.jetbrains.plugins.notebooks.jupyter.editor.preview.JupyterWebViewHtmlPanel.<init>(JupyterWebViewHtmlPanel.kt:59)
        at org.jetbrains.plugins.notebooks.jupyter.editor.JupyterSplitFileEditorProvider.createJupyterFileEditor(JupyterSplitFileEditorProvider.kt:16)
        at org.jetbrains.plugins.notebooks.jupyter.editor.JupyterFileEditorProvider.createEditor(JupyterFileEditorProvider.kt:62)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4Edt(FileEditorManagerImpl.java:891)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$17(FileEditorManagerImpl.java:860)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runBulkTabChange(FileEditorManagerImpl.java:1680)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$18(FileEditorManagerImpl.java:859)
        at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:463)
        at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:481)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:858)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl3(FileEditorManagerImpl.java:804)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl2$14(FileEditorManagerImpl.java:785)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:211)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:167)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:153)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:785)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:678)
        at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.java:131)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openEditorImpl$21(FileEditorManagerImpl.java:1149)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:211)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:167)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:153)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditorImpl(FileEditorManagerImpl.java:1147)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileEditor(FileEditorManagerImpl.java:1124)
        at com.intellij.openapi.fileEditor.FileEditorManager.openEditor(FileEditorManager.java:217)
        at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigateInAnyFileEditor(FileNavigatorImpl.java:84)
        at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigateInEditor(FileNavigatorImpl.java:65)
        at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigateInEditorOrNativeApp(FileNavigatorImpl.java:50)
        at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigate(FileNavigatorImpl.java:33)
        at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigate(OpenFileDescriptor.java:90)
        at com.intellij.psi.impl.source.PsiFileImpl.navigate(PsiFileImpl.java:915)
        at com.intellij.codeInsight.navigation.NavigationUtil.lambda$openFileWithPsiElement$2(NavigationUtil.java:178)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:167)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:153)
        at com.intellij.codeInsight.navigation.NavigationUtil.openFileWithPsiElement(NavigationUtil.java:171)
        at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:235)
        at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:245)
        at com.intellij.ide.projectView.impl.nodes.PsiFileNode.navigate(PsiFileNode.java:116)
        at com.intellij.util.OpenSourceUtil.navigateToSource(OpenSourceUtil.java:119)
        at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:74)
        at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:58)
        at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:51)
        at com.intellij.util.OpenSourceUtil.openSourcesFrom(OpenSourceUtil.java:19)
        at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.processDoubleClick(EditSourceOnDoubleClickHandler.java:166)
        at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.onDoubleClick(EditSourceOnDoubleClickHandler.java:160)
        at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
        at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:59)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6650)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
        at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:385)
        at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:45)
        at java.desktop/java.awt.Component.processEvent(Component.java:6415)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5025)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:911)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2021-01-14 16:22:22,054 [  16361]  ERROR - tor.impl.FileEditorManagerImpl - PyCharm 2020.3.2  Build #PY-203.6682.179 
2021-01-14 16:22:22,054 [  16361]  ERROR - tor.impl.FileEditorManagerImpl - JDK: 11.0.7; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2021-01-14 16:22:22,054 [  16361]  ERROR - tor.impl.FileEditorManagerImpl - OS: Linux 
2021-01-14 16:22:22,054 [  16361]  ERROR - tor.impl.FileEditorManagerImpl - Last Action:  
2021-01-14 16:22:22,055 [  16362]  ERROR - tor.impl.FileEditorManagerImpl - Current Command:  

</p>
</details>

**Comment by klDen** [comment] 2021-03-20 16:24
Hi, can you try and use this jdk https://search.nixos.org/packages?channel=20.09&from=0&size=30&sort=relevance&query=jetbrains.jdk

**Comment by klDen** [comment] 2021-03-20 17:51
I tried overriding pycharm jdk , but w/o any success :/
```
(jetbrains.pycharm-professional.override { jdk = pkgs.jdk11; })
```

**Comment by klDen** [comment] 2021-03-20 17:52
Also tried the steps mentioned in https://www.jetbrains.com/help/pycharm/switching-boot-jdk.html, but after restarting, the changes are "reset" to default.

**Comment by niknetniko** [comment] 2023-01-16 12:06
https://github.com/NixOS/nixpkgs/pull/196738

**Comment by kravemir** [comment] 2024-06-28 10:01
@niknetniko the issue is still present, and it seems to be caused by some version mismatch:

```log
INFO - #c.i.p.i.b.AppStarter - boot library path: /nix/store/hv81cwj3p77z4z35rybjmkv7a3d8gymb-jetbrains-jdk-jcef-17.0.8-b1000.8/lib/openjdk/lib


WARN - #c.i.u.j.JBCefApp - JCEF: minimum supported CEF major version is 119, current is 111 (Use JBR bundled with the IDE)

SEVERE - #c.i.o.f.i.FileEditorManagerImpl - JCEF is not supported in this env or failed to initialize
java.lang.IllegalStateException: JCEF is not supported in this env or failed to initialize
	at com.intellij.ui.jcef.JBCefApp.getInstance(JBCefApp.java:157)
	...
```

**Comment by niknetniko** [comment] 2024-06-28 11:18
> @niknetniko the issue is still present, and it seems to be caused by some version mismatch:

Which version of PyCharm/Intellij are you using? And which JDK are you using?

While the versions do become incompatible sometimes when the IDEs are bumped, since https://github.com/NixOS/nixpkgs/pull/309447 was merged, everything works for me.

**Comment by kravemir** [comment] 2024-06-28 12:19
I'm using one packaged in NixOS 24.05, which is using `jetbrains.jdk` (this is by default [all packages](https://github.com/NixOS/nixpkgs/blob/89c49874fb15f4124bf71ca5f42a04f2ee5825fd/pkgs/top-level/all-packages.nix#L31254-L31261)):

```
❯ ls -ldh `which pycharm-professional`
lrwxrwxrwx 1 root root 98 jan  1  1970 /run/current-system/sw/bin/pycharm-professional -> /nix/store/lg7q4zgn7k6b6h0h927am8x2j5fgay1r-pycharm-professional-2024.1.3/bin/pycharm-professional

❯ cat /run/current-system/nixos-version
24.05.1695.dd457de7e08c

❯ export | grep -e JAVA_HOME -e JDK_HOME
declare -x ANDROID_JAVA_HOME="/nix/store/hv81cwj3p77z4z35rybjmkv7a3d8gymb-jetbrains-jdk-jcef-17.0.8-b1000.8/lib/openjdk"
declare -x JAVA_HOME="/nix/store/hv81cwj3p77z4z35rybjmkv7a3d8gymb-jetbrains-jdk-jcef-17.0.8-b1000.8/lib/openjdk"
declare -x JDK_HOME="/nix/store/hv81cwj3p77z4z35rybjmkv7a3d8gymb-jetbrains-jdk-jcef-17.0.8-b1000.8/lib/openjdk"
```

And, it seems to be used as the boot runtime:

![image](https://github.com/NixOS/nixpkgs/assets/1643935/4b2c7991-7a3b-416d-95b1-9315e16f9d3d)

**Comment by kravemir** [comment] 2024-06-28 12:23
> ... since #309447 was merged, everything works for me.

This seems to not be backported to 24.05. I'll try it, if it works.

**Comment by tomodachi94** [comment] 2024-11-13 05:53
Closing per @niknetniko:
> While the versions do become incompatible sometimes when the IDEs are bumped, since https://github.com/NixOS/nixpkgs/pull/309447 was merged, everything works for me.

@kravemir, if you want this on 24.05, I encourage you to [read "Changes acceptable for releases" in CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#changes-acceptable-for-releases) (mostly making sure that no breaking changes occurred in that version bump), and then [manually backport](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#manually-backporting-changes) that commit to `release-24.05`.

**Closed by tomodachi94** 2024-11-13 05:53 UTC
Labels: 0.kind: bug, 6.topic: java, 6.topic: jupyter
