### ISSUE TITLE
SDDM resets selected session type on DE updates

### ISSUE THREAD

**Issue by 2xsaiko** [NixOS/nixpkgs#200942] opened 2022-11-12 21:47 UTC
### Describe the bug
On every Plasma update (though this most likely happens with other DEs as well), SDDM resets selected session from Plasma Wayland to Plasma X11. My guess is that sddm tracks the last selected session as an absolute path to the session file, and since that file is in the store, the path changes on an update, causing the list to reset.

### Steps To Reproduce
1. Boot a configuration with SDDM and Plasma
2. Log in with the Wayland session
3. Boot into another configuration with a different Plasma version
4. Session type is reset to Plasma X11

### Expected behavior
The session dropdown box should keep Wayland as the selected session.

### Notify maintainers

@jtojnar (there's no maintainers for the sddm module as far as I can see, and you touched the value of SessionDir last, so I hope mentioning you is fine)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
% nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.77, NixOS, 22.11 (Raccoon), 22.11.20221109.872fcee`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by jtojnar** [comment] 2022-11-12 22:47
I can only tell you that GDM gets the last used session from AccountsService and we are [forcing the value](https://github.com/NixOS/nixpkgs/blob/a832695c57f971113cb0b93e1b0022046268b0fe/nixos/modules/services/x11/display-managers/gdm.nix#L159) when `services.xserver.displayManager.defaultSession` is set. Not really familiar with SDDM.

**Comment by 2xsaiko** [comment] 2022-11-13 09:39
Ah, setting defaultSession does work, thank you! I completely forgot about that option. While it may not fix this issue, it's probably closest to what I actually want.

**Comment by haizaar** [comment] 2023-06-25 14:47
I get by with `services.xserver.displayManager.defaultSession` as well

**Comment by jtojnar** [comment] 2024-06-21 05:26
Turns out this is caused by Plasma module [setting a default value for `defaultSession` option](https://github.com/NixOS/nixpkgs/commit/ad20e87e39749f1b6176f06e8d9bbb653738f020), which is [not correct usage of the option](https://github.com/NixOS/nixpkgs/issues/291501#issuecomment-2182024013).

**Comment by jtojnar** [comment] 2024-06-21 05:28
Duplicate of #291501

**Closed** 2024-06-21 05:28 UTC
Labels: 0.kind: bug, 6.topic: nixos
