### ISSUE TITLE
Neovim-qt-unwrapped is not compiling

### ISSUE THREAD

**Issue by tfmoraes** [NixOS/nixpkgs#124198] opened 2021-05-23 21:37 UTC
**Describe the bug**

```bash
$ nix log /nix/store/f5fcsfkh3vq0pgyklhxzkrcf2mi0rxla-neovim-qt-unwrapped-0.2.16.1.drv
Neovim-qt-unwrapped is not compiling. This is the error:

@nix { "action": "setPhase", "phase": "qtPreHook" }
qtPreHook
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/f6vybl3nsl97xcr31wp0mg3b2xqvb34n-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
fixing cmake files...
cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_BUILD_RPATH=ON -DCMAKE_INSTALL_LOCALEDIR=/nix/store/3kdwjplipcvhqlm6mgyffy1465sbrg9r-neovim-qt-unwrapped-0.2.16.1/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/3kdwjplipcvhqlm6mgyffy1465sbrg9r-neovim-qt-unwrapped-0.2.16.1/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/3kdwjplipcvhqlm6mgyffy1465sbrg9r-neovim-qt-unwrapped-0.2.16.1/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/3kdwjplipcvhqlm6mgyffy1465sbrg9r-neovim-qt-unwrapped-0.2.16.1/share/doc/neovim-qt -DCMAKE_INSTALL_INFODIR=/nix/store/3kdwjplipcvhqlm6mgyffy1465sbrg9r-neovim-qt-unwrapped-0.2.16.1/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/3kdwjplipcvhqlm6mgyffy1465sbrg9r-neovim-qt-unwrapped-0.2.16.1/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/3kdwjplipcvhqlm6mgyffy1465sbrg9r-neovim-qt-unwrapped-0.2.16.1/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/3kdwjplipcvhqlm6mgyffy1465sbrg9r-neovim-qt-unwrapped-0.2.16.1/include -DCMAKE_INSTALL_SBINDIR=/nix/store/3kdwjplipcvhqlm6mgyffy1465sbrg9r-neovim-qt-unwrapped-0.2.16.1/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/3kdwjplipcvhqlm6mgyffy1465sbrg9r-neovim-qt-unwrapped-0.2.16.1/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/3kdwjplipcvhqlm6mgyffy1465sbrg9r-neovim-qt-unwrapped-0.2.16.1/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_SYSROOT= -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_STRIP=/nix/store/7m6p435s1c9ysfs266n9ppfw9zkii697-binutils-2.35.1/bin/strip -DCMAKE_RANLIB=/nix/store/7m6p435s1c9ysfs266n9ppfw9zkii697-binutils-2.35.1/bin/ranlib -DCMAKE_AR=/nix/store/7m6p435s1c9ysfs266n9ppfw9zkii697-binutils-2.35.1/bin/ar -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/nix/store/3kdwjplipcvhqlm6mgyffy1465sbrg9r-neovim-qt-unwrapped-0.2.16.1 -DUSE_SYSTEM_MSGPACK=1 -DENABLE_TESTS=0 
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /nix/store/jabh25wi8r7v2gpkfyhvm9jaxpzgw73x-gcc-wrapper-10.3.0/bin/gcc
-- Check for working C compiler: /nix/store/jabh25wi8r7v2gpkfyhvm9jaxpzgw73x-gcc-wrapper-10.3.0/bin/gcc - broken
CMake Error at /nix/store/yb03if8wrzdzd4f4rnmaxkj7mr58l0w5-cmake-3.19.7/share/cmake-3.19/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/nix/store/jabh25wi8r7v2gpkfyhvm9jaxpzgw73x-gcc-wrapper-10.3.0/bin/gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /build/source/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/nix/store/8psvlkcgbzlwvazx7w8vnxpf16big6gh-gnumake-4.3/bin/make cmTC_901ba/fast && /nix/store/8psvlkcgbzlwvazx7w8vnxpf16big6gh-gnumake-4.3/bin/make  -f CMakeFiles/cmTC_901ba.dir/build.make CMakeFiles/cmTC_901ba.dir/build
    make[1]: Entering directory '/build/source/build/CMakeFiles/CMakeTmp'
    make[1]: /bin/sh: No such file or directory
    make[1]: *** [CMakeFiles/cmTC_901ba.dir/build.make:84: CMakeFiles/cmTC_901ba.dir/testCCompiler.c.o] Error 127
    make[1]: Leaving directory '/build/source/build/CMakeFiles/CMakeTmp'
    make: *** [Makefile:140: cmTC_901ba/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:8 (project)


-- Configuring incomplete, errors occurred!
See also "/build/source/build/CMakeFiles/CMakeOutput.log".
See also "/build/source/build/CMakeFiles/CMakeError.log".
```

**To Reproduce**
1. Add neovim-qt to your system-packages
2. Switch to a new version

**Expected behavior**

Neovim-qt should compile.

**Screenshots**

**Additional context**

I'm using `flakes` in my system and `neovim-nightly`.

**Notify maintainers**

I don't think this problem is with neovim-qt, so I'm notifying cmake and gcc too.

@peterhoeg @ttuegel @LnL7 @Synthetica9

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.21, NixOS, 21.05.20210523.900115a (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(root): `"nixos-21.03pre250162.34ad166a830"`
 - nixpkgs: `/etc/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by fortuneteller2k** [comment] 2021-05-24 05:23
This also happens with polybar for me

**Comment by leifhelm** [comment] 2021-05-24 05:34
I have the same problem with an other CMake project on a nixos machine with flakes. CMake does work fine in the nix shell environment. It seems like that `/bin/sh` was not patched in the CMake scripts or it is now unavailable in the build environment.

**Comment by fgaz** [comment] 2021-05-24 09:25
Experiencing the same in https://github.com/NixOS/nixpkgs/pull/124208 on aarch64

**Comment by fortuneteller2k** [comment] 2021-05-24 09:32
> I have the same problem with another CMake project on a nixos machine with flakes. CMake does work fine in the nix shell environment. It seems like that `/bin/sh` was not patched in the CMake test scripts or it is now unavailable in the build environment.

#124237 might fix this

**Comment by leifhelm** [comment] 2021-05-24 11:46
#124237 fixed it for me

**Comment by fortuneteller2k** [comment] 2021-05-24 11:50
Rebuilt my system without facing this issue, so I assume the linked PR fixed it.

I will close this now, but feel free to reopen if the problem still occurs.

**Comment by fgaz** [comment] 2021-05-24 12:23
I rebased, and the problem is still occurring for ft2-clone 1.47 on aarch64

**Comment by fgaz** [comment] 2021-05-24 12:26
Oh wait, that change needs a nixos-rebuild switch, doesn't it? Unfortunately I'm using the community builder to test this so I can't do that. I'll wait for an automatic rebuild and re-close the issue if it's fixed.

**Comment by gebner** [comment] 2021-05-24 12:45
Yes, the fix changes the contents of `/etc/nix/nix.conf`, so you need to run `nixos-rebuild switch` before it takes effect.  You can also manually edit the file (replace the symlink by a copy before) and remove the `store-paths =` line.

**Comment by fgaz** [comment] 2021-05-25 08:35
I can confirm that it's fixed

**Closed by fgaz** 2021-05-25 08:35 UTC
Labels: 0.kind: bug

**Comment by tfmoraes** [comment] 2021-05-25 13:38
I think this other problem is related. Now I'm having this problem when I try to update my system:

```bash
❯ nix log /nix/store/9f6q91lh54764lsl8041g3sbyhkg9r2y-nix-ld.drv
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/hrqpv615j7sjhvmsh1azd9f2adfhkwrm-zlmxj2bjrhlraf2pfjhpiwm5sj3v78xq-source
source root is zlmxj2bjrhlraf2pfjhpiwm5sj3v78xq-source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
meson flags: --buildtype=plain         --libdir=/nix/store/a4l48pabmrgz9irqp6g0p3d1c0w4gx8g-nix-ld/lib --libexecdir=/nix/store/a4l48pabmrgz9irqp6g0p3d1c0w4gx8g-nix-ld/libexec         --bindir=/nix/store/a4l48pabmrgz9irqp6g0p3d1c0w4gx8g-nix-ld/bin --sbindir=/nix/store/a4l48pabmrgz9irqp6g0p3d1c0w4gx8g-nix-ld/sbin         --includedir=/nix/store/a4l48pabmrgz9irqp6g0p3d1c0w4gx8g-nix-ld/include         --mandir=/nix/store/a4l48pabmrgz9irqp6g0p3d1c0w4gx8g-nix-ld/share/man --infodir=/nix/store/a4l48pabmrgz9irqp6g0p3d1c0w4gx8g-nix-ld/share/info         --localedir=/nix/store/a4l48pabmrgz9irqp6g0p3d1c0w4gx8g-nix-ld/share/locale         -Dauto_features=enabled         -Dwrap_mode=nodownload         --prefix=/nix/store/a4l48pabmrgz9irqp6g0p3d1c0w4gx8g-nix-ld -Dnix-system=x86_64-linux 
[1mThe Meson build system[0m
Version: 0.57.1
Source dir: [1m/build/zlmxj2bjrhlraf2pfjhpiwm5sj3v78xq-source[0m
Build dir: [1m/build/zlmxj2bjrhlraf2pfjhpiwm5sj3v78xq-source/build[0m
Build type: [1mnative build[0m
Project name: [1mnix-ld[0m
Project version: [1m1[0m
C compiler for the host machine: [1mgcc[0m (gcc 10.3.0 "gcc (GCC) 10.3.0")
C linker for the host machine: [1mgcc[0m ld.bfd 2.35.1
Host machine cpu family: [1mx86_64[0m
Host machine cpu: [1mx86_64[0m
Compiler for C supports arguments -ffast-math: [1;32mYES[0m 
Compiler for C supports arguments -fno-common: [1;32mYES[0m 
Compiler for C supports arguments -fdiagnostics-show-option: [1;32mYES[0m 
Compiler for C supports arguments -fno-strict-aliasing: [1;32mYES[0m 
Compiler for C supports arguments -fvisibility=hidden: [1;32mYES[0m 
Compiler for C supports arguments -fcf-protection: [1;32mYES[0m 
Compiler for C supports arguments --param=ssp-buffer-size=4: [1;32mYES[0m 
Compiler for C supports link arguments -Wl,-z,relro: [1;32mYES[0m 
Compiler for C supports link arguments -Wl,-z,now: [1;32mYES[0m 
Compiler for C supports link arguments -Wl,--gc-sections: [1;32mYES[0m 
Compiler for C supports link arguments -fstack-protector: [1;32mYES[0m 
Configuring [1mconfig.h[0m using configuration
Checking for size of "[1mvoid *[0m" : 8
Program [1msh[0m found: [1;32mYES[0m (/nix/store/a4yw1svqqk4d8lhwinn9xp847zz9gfma-bash-4.4-p23/bin/sh)
Build targets in project: [1m4[0m

Found ninja-1.10.2 at /nix/store/6gzaz26a84m4bn33f1zrnj4zwbnwc8cd-ninja-1.10.2/bin/ninja
meson: enabled parallel building
@nix { "action": "setPhase", "phase": "buildPhase" }
building
build flags: -j16 -l16

[0/8] Compiling C object nix-ld.p/src_nix-ld.c.o[Kninja: fatal: posix_spawn: No such file or directory
```

The content of my `nix.conf`:

```
# WARNING: this file is generated from the nix.* options in
# your NixOS configuration, typically
# /etc/nixos/configuration.nix.  Do not edit it!
build-users-group = nixbld
max-jobs = auto
cores = 0
sandbox = true
sandbox-paths = 

substituters = https://cache.nixos.org/
trusted-substituters = 
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
auto-optimise-store = true
require-sigs = true
trusted-users = root thiago
allowed-users = *
builders =

system-features = nixos-test benchmark big-parallel kvm
sandbox-fallback = false

keep-outputs = true
keep-derivations = true
preallocate-contents = false
experimental-features = nix-command flakes
```

**Comment by fortuneteller2k** [comment] 2021-05-25 13:41
> I think this other problem is related. Now I'm having this problem when I try to update my system:
> 
> 
> 
> ```bash
> 
> ❯ nix log /nix/store/9f6q91lh54764lsl8041g3sbyhkg9r2y-nix-ld.drv
> 
> @nix { "action": "setPhase", "phase": "unpackPhase" }
> 
> unpacking sources
> 
> unpacking source archive /nix/store/hrqpv615j7sjhvmsh1azd9f2adfhkwrm-zlmxj2bjrhlraf2pfjhpiwm5sj3v78xq-source
> 
> source root is zlmxj2bjrhlraf2pfjhpiwm5sj3v78xq-source
> 
> @nix { "action": "setPhase", "phase": "patchPhase" }
> 
> patching sources
> 
> @nix { "action": "setPhase", "phase": "configurePhase" }
> 
> configuring
> 
> meson flags: --buildtype=plain         --libdir=/nix/store/a4l48pabmrgz9irqp6g0p3d1c0w4gx8g-nix-ld/lib --libexecdir=/nix/store/a4l48pabmrgz9irqp6g0p3d1c0w4gx8g-nix-ld/libexec         --bindir=/nix/store/a4l48pabmrgz9irqp6g0p3d1c0w4gx8g-nix-ld/bin --sbindir=/nix/store/a4l48pabmrgz9irqp6g0p3d1c0w4gx8g-nix-ld/sbin         --includedir=/nix/store/a4l48pabmrgz9irqp6g0p3d1c0w4gx8g-nix-ld/include         --mandir=/nix/store/a4l48pabmrgz9irqp6g0p3d1c0w4gx8g-nix-ld/share/man --infodir=/nix/store/a4l48pabmrgz9irqp6g0p3d1c0w4gx8g-nix-ld/share/info         --localedir=/nix/store/a4l48pabmrgz9irqp6g0p3d1c0w4gx8g-nix-ld/share/locale         -Dauto_features=enabled         -Dwrap_mode=nodownload         --prefix=/nix/store/a4l48pabmrgz9irqp6g0p3d1c0w4gx8g-nix-ld -Dnix-system=x86_64-linux 
> 
> [1mThe Meson build system[0m
> 
> Version: 0.57.1
> 
> Source dir: [1m/build/zlmxj2bjrhlraf2pfjhpiwm5sj3v78xq-source[0m
> 
> Build dir: [1m/build/zlmxj2bjrhlraf2pfjhpiwm5sj3v78xq-source/build[0m
> 
> Build type: [1mnative build[0m
> 
> Project name: [1mnix-ld[0m
> 
> Project version: [1m1[0m
> 
> C compiler for the host machine: [1mgcc[0m (gcc 10.3.0 "gcc (GCC) 10.3.0")
> 
> C linker for the host machine: [1mgcc[0m ld.bfd 2.35.1
> 
> Host machine cpu family: [1mx86_64[0m
> 
> Host machine cpu: [1mx86_64[0m
> 
> Compiler for C supports arguments -ffast-math: [1;32mYES[0m 
> 
> Compiler for C supports arguments -fno-common: [1;32mYES[0m 
> 
> Compiler for C supports arguments -fdiagnostics-show-option: [1;32mYES[0m 
> 
> Compiler for C supports arguments -fno-strict-aliasing: [1;32mYES[0m 
> 
> Compiler for C supports arguments -fvisibility=hidden: [1;32mYES[0m 
> 
> Compiler for C supports arguments -fcf-protection: [1;32mYES[0m 
> 
> Compiler for C supports arguments --param=ssp-buffer-size=4: [1;32mYES[0m 
> 
> Compiler for C supports link arguments -Wl,-z,relro: [1;32mYES[0m 
> 
> Compiler for C supports link arguments -Wl,-z,now: [1;32mYES[0m 
> 
> Compiler for C supports link arguments -Wl,--gc-sections: [1;32mYES[0m 
> 
> Compiler for C supports link arguments -fstack-protector: [1;32mYES[0m 
> 
> Configuring [1mconfig.h[0m using configuration
> 
> Checking for size of "[1mvoid *[0m" : 8
> 
> Program [1msh[0m found: [1;32mYES[0m (/nix/store/a4yw1svqqk4d8lhwinn9xp847zz9gfma-bash-4.4-p23/bin/sh)
> 
> Build targets in project: [1m4[0m
> 
> 
> 
> Found ninja-1.10.2 at /nix/store/6gzaz26a84m4bn33f1zrnj4zwbnwc8cd-ninja-1.10.2/bin/ninja
> 
> meson: enabled parallel building
> 
> @nix { "action": "setPhase", "phase": "buildPhase" }
> 
> building
> 
> build flags: -j16 -l16
> 
> 
> 
> [0/8] Compiling C object nix-ld.p/src_nix-ld.c.o[Kninja: fatal: posix_spawn: No such file or directory
> 
> ```
> 
> 
> 
> The content of my `nix.conf`:
> 
> 
> 
> ```
> 
> # WARNING: this file is generated from the nix.* options in
> 
> # your NixOS configuration, typically
> 
> # /etc/nixos/configuration.nix.  Do not edit it!
> 
> build-users-group = nixbld
> 
> max-jobs = auto
> 
> cores = 0
> 
> sandbox = true
> 
> sandbox-paths = 
> 
> 
> 
> substituters = https://cache.nixos.org/
> 
> trusted-substituters = 
> 
> trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
> 
> auto-optimise-store = true
> 
> require-sigs = true
> 
> trusted-users = root thiago
> 
> allowed-users = *
> 
> builders =
> 
> 
> 
> system-features = nixos-test benchmark big-parallel kvm
> 
> sandbox-fallback = false
> 
> 
> 
> keep-outputs = true
> 
> keep-derivations = true
> 
> preallocate-contents = false
> 
> experimental-features = nix-command flakes
> 
> ```
> 
> 

Remove the `sandbox-paths =` line in your `nix.conf` and rebuild.

**Comment by tfmoraes** [comment] 2021-05-25 13:51
Thanks @fortuneteller2k ! It worked!

**Comment by tfmoraes** [comment] 2021-05-26 17:34
@fortuneteller2k `sandbox-paths =` is still being added to `nix.conf`. I needed to create a new `shell.nix` but it was failing to build one of libs because of  `sandbox-paths =`, removing  `sandbox-paths =` make it work.
