### ISSUE TITLE
Emacs as a service:  set EDITOR in tty and set VISUAL

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#34467] opened 2018-01-31 19:46 UTC
## Issue description

When using Emacs as a service in NixOS, in a tty ``EDITOR`` is not set; at least here it's nano.
``VISUAL`` is not set at all.

**Comment by rnhmjoj** [comment] 2018-02-03 20:19
You have to set `services.emacs.defaultEditor = true;`

**Comment by magnetophon** [comment] 2018-02-03 21:46
@rnhmjoj I have.
Did you notice I said "in a tty"?

**Comment by rnhmjoj** [comment] 2018-02-03 22:38
What do you mean with a tty? a linux virtual terminal?
I just tried with a VM and EDITOR is set even in this case.

**Comment by magnetophon** [comment] 2018-02-03 22:52
Yes, a virtual terminal.
For me EDITOR is set to nano in there.

**Comment by rnhmjoj** [comment] 2018-02-03 22:56
Uhm, The variable is being reset or the not picked up. What shell are you using?

**Comment by magnetophon** [comment] 2018-02-03 23:08
I'm using zsh.

**Comment by rvl** [comment] 2018-02-04 08:03
So @magnetophon there are two problems:
1. Although `services.emacs.defaultEditor = true`, the variable `EDITOR` was still not set in a tty. To reproduce this, I could press Ctrl-Alt-F1 to go to text mode, log in as my user, then type `env | grep EDITOR`.
2. `VISUAL` is not set at all.

For 1, I can't reproduce this. Are you sure you have a clean zsh config?
For 2, we can of course set it with #34570. But as far as I can tell [[1]](https://unix.stackexchange.com/questions/4859/visual-vs-editor-whats-the-difference), [[2]](https://en.wikibooks.org/wiki/Guide_to_Unix/Environment_Variables#VISUAL), [[3]](https://wiki.archlinux.org/index.php/environment_variables), it doesn't matter. Do you have a particular program which is not working?

**Comment by magnetophon** [comment] 2018-02-04 08:51
1: I just renamed my .zshrc and logged in to a tty; problem remains.

2: I mostly use magit, but when I occasionally use git on the cli and commit, it drops me in nano.
Setting VISUAL fixes this.

The sources you cite mostly say to set VISUAL, and optionally set EDITOR to the same thing.
They also say that officially ``The EDITOR editor should be able to work without use of "advanced" terminal functionality (like old ed or ex mode of vi).``.
I won't go as far as advocating we actually do this...

**Comment by rvl** [comment] 2018-02-04 09:25
My suggestion is to unset and forget about `VISUAL` because it's not necessary. `git commit` will use `EDITOR` -- if it's set.

We have a [NixOS test case](https://github.com/NixOS/nixpkgs/blob/7e0b231b5386ce8c2b88f204621e318a361b8fa2/nixos/tests/emacs-daemon.nix) that specifically checks for correct setting of the `EDITOR` variable. How does your setup differ from this?

**Comment by magnetophon** [comment] 2018-02-04 10:19
@rvl To be clear: EDITOR *is* set by NixOS for me, just not in a tty.
I figured out why VISUAL was set to nano: it was in my ``.zprofile``.

``git commit`` will use VISUAL and fall back to EDITOR if it's not set, so I still suggest we set VISUAL.

**Comment by rnhmjoj** [comment] 2018-02-05 03:53
So, I tried with zsh and still can't reproduce it. Here's the config
```nix
{ config, pkgs, ...}:

{
  imports = [ <nixpkgs/nixos/modules/virtualisation/qemu-vm.nix> ];

  networking.hostName = "vmhost";
 
  users.extraUsers.vm = {
    isNormalUser = true;
    password     = "vm";
    shell        = "${pkgs.zsh}/bin/zsh";
    extraGroups  = [ "wheel" ];
  };

  services.emacs = {
    enable = true;
    defaultEditor = true;
  };

  programs.zsh = {
    enable = true;
    enableAutosuggestions = true;
    syntaxHighlighting.enable = true;
  };

}
```

I can't think of any reason why the environment would be different in a vt, unless something in your shell setup is specifically doing this.

**Comment by rvl** [comment] 2018-02-05 06:18
Thanks @rnhmjoj.

@magnetophon, try checking all zsh config files listed on [the ArchWiki zsh page](https://wiki.archlinux.org/index.php/zsh#Startup.2FShutdown_files), and the files that they source. The list was written for Arch Linux but also applies to NixOS.

Also, by default, things should work without needing to set the `VISUAL` variable.

**Comment by magnetophon** [comment] 2018-02-05 09:44
I found the issue with the vt; it was indeed in my zsh config.
I didn't think to look there, since it was working in X11.
Sorry for the noise.

> Also, by default, things should work without needing to set the VISUAL variable.
This came about after some discussion in the #ranger IRC channel.
Maybe @toonn or @Vifon could comment on that?

**Comment by toonn** [comment] 2018-02-05 17:32
I recently found out about the proper use of `VISUAL` and `EDITOR`, [my source](https://unix.stackexchange.com/a/334022).

Ranger's always just used `EDITOR` as the user's preferred editor. This behavior would be inconvenient for someone who's doing "the right thing." I updated ranger to prefer `VISUAL` over `EDITOR` and tried to keep the change backwards compatible, I missed the case where `VISUAL`'s configured but `EDITOR` is not, so the latest release is technically not backwards compatible but the next one will be.

Technically `emacs -nw` would fit in `VISUAL` not `EDITOR` and emacs's gui mode fits neither. Whether anyone cares is another issue.
I'd hoped NixOS could resolve this misuse because the config is declarative so it could easily define `VISUAL` instead and every program (Are there many?) that relies exclusively on `EDITOR` could be fairly easily patched in nixpkgs.

**Comment by rvl** [comment] 2018-02-05 21:01
@magnetophon Thanks for the report. Please feel free to close this issue, unless it is stopping you from efficiently using `ed`.

**Comment by toonn** [comment] 2018-02-05 22:20
@rvl your reply reads somewhat glib to me. The issue was already resolved further up in the thread.
If you believe the distinction is pointless on modern systems then please just say so.
- If there are official guidelines on the usage of `VISUAL` and `EDITOR` I would love to find out.
- Would doing "the right thing" actually cause breakage? Afaik most tools check `VISUAL` before `EDITOR`.

**Closed** 2018-02-06 13:27 UTC
