### ISSUE TITLE
Need option to disable IPv6 privacy for selected interfaces

### ISSUE THREAD

**Issue by conferno** [NixOS/nixpkgs#75311] opened 2019-12-08 22:55 UTC
IPv6 privacy (random temporary IPv6 addresses) in enabled for all interfaces.
The only option to configure it is boolean `preferTempAddress`.
There is no option to turn it off.
The temporarily IPv6 addresses are enabled for all `tinc` interfaces, even if they have only IPv4 address.
It does not cause problems but seems useless so I would like to disable IPv6 temporary addresses for the interfaces where they have no sense
`

**Comment by rnhmjoj** [comment] 2019-12-09 11:01
`preferTempAddress = false`?

**Comment by volth** [comment] 2019-12-09 11:32
It changes nothing

**Comment by rnhmjoj** [comment] 2019-12-09 14:39
It's supposed to: there is no need for another option.
What are your configurations? The test I wrote `nixosTests.networking.scripted.privacy` is passing so I don't know understanrd what's wrong.

**Comment by volth** [comment] 2019-12-09 15:40
> What are your configurations? 

Just enable `tinc` (I suspect any other VPN software will go as well)

![](https://i.imgur.com/qLQEBEz.png)

There is nothing wrong except of garbage IPv6 addresses which won't work because `tinc` is a router by itself and all the IPs should be reflected in `tinc`'s configuration.
So, if a program will enumerate interfaces and their IPs (somehow, by parsing `ip a` output or by using java API) it will be fooled with unroutable IPs and with false availability of IPv6.

The real IPs have priority, with `preferTempAddress = false` and `preferTempAddress = true`, there is no connectivity problems caused by introduction of the privacy IPs. But there there is no advantage either.

**Comment by rnhmjoj** [comment] 2019-12-09 20:31
Thank you, it's clear now: the problem is `preferTempAddress = false` still enable privacy extensions while you don't want these addresses at all.
There are three options I can think of:

1. Make the option an enum like the underlying `net.ipv6.conf.ifname.use_tempaddr` sysctl one: `tempAddress` would either be "default", "enabled" or "disabled". 

2. Add another option like `enableTempAddress` that when set to `false` will override the udev rule to not enable the privacy extensions.

3. Same as 2. but using the current `preferTempAddress` option. This makes sense because, like in your case, if one doesn't want the temporary addresses used by default probably doesn't want them laying around doing nothing also.

I'm not sure what's the best way...

**Comment by rnhmjoj** [comment] 2020-01-12 09:42
ping

**Comment by lheckemann** [comment] 2020-02-20 13:20
Assuming until further notice that this is fixed by #78843. Feel free to reopen if this is incorrect!

**Closed by lheckemann** 2020-02-20 13:20 UTC
Labels: 0.kind: bug, 6.topic: nixos
