### ISSUE TITLE
auto-multiple-choice seems broken

### ISSUE THREAD

**Issue by rgrunbla** [NixOS/nixpkgs#214724] opened 2023-02-05 10:19 UTC
### Describe the bug

The auto-multiple-choice program does not start, on NixOS 22.11 :

```
$ auto-multiple-choice
Unknown action gui at /nix/store/xwx2q2052rg2nnpppwy60h2jg6y2181x-auto-multiple-choice-1.5.2/bin/.auto-multiple-choice-wrapped line 88.
$ nix-env -q auto-multiple-choice
auto-multiple-choice-1.5.2
```
1. Install auto-multiple-choice
2. Launch auto-multiple-choice
3. Observe that it's not really working

### Notify maintainers

@thblt 

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.90, NixOS, 22.11 (Raccoon), 22.11.2203.285b3ff0660`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11, nixos-unstable"`
 - channels(remy): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rgrunbla** [comment] 2023-02-06 10:39
I installed it using nix-env. I'll try with the systemPackage option later today.

**Comment by thblt** [comment] 2023-02-06 10:45
> I'm using wayland with sway.

I don't think that's the issue there (also I have the very same setup, on unstable though). This message means that the program can't find the perl source module of its gui component, which indicates an installation/path issue.

**Comment by thblt** [comment] 2023-02-06 11:41
I really can't reproduce, sorry. Please let me know how things go with `systemPackages`. 

Does `/nix/store/xwx2q2052rg2nnpppwy60h2jg6y2181x-auto-multiple-choice-1.5.2/lib/perl/AMC-gui.pl` exist?

**Comment by rgrunbla** [comment] 2023-02-06 12:06
Yup, it exists :

```
remy@typhoon ~> ls -alh /nix/store/xwx2q2052rg2nnpppwy60h2jg6y2181x-auto-multiple-choice-1.5.2/lib/perl/AMC-gui.pl
-r-xr-xr-x 1 root root 4,4K  1 janv.  1970 /nix/store/xwx2q2052rg2nnpppwy60h2jg6y2181x-auto-multiple-choice-1.5.2/lib/perl/AMC-gui.pl
remy@typhoon ~> nix-shell --pure -p auto-multiple-choice

[nix-shell:~]$ echo $PATH
/nix/store/k2b87dvmz4mbs3d29z9fy18ja874q4nf-bash-interactive-5.1-p16/bin:/nix/store/qfzkrv19az50ypgrsgv6ywr3pdw4rm5y-patchelf-0.15.0/bin:/nix/store/a12yx0i0xh7i39bahq13jhmfplmn69ar-gcc-wrapper-11.3.0/bin:/nix/store/s652h8znmysdbxcmwlzzcwrj6bb1xyln-gcc-11.3.0/bin:/nix/store/gfsg0n19r8q8v69kwwjvx4m2y77vi7i8-glibc-2.35-224-bin/bin:/nix/store/ngw3m00r391w31n13q4m2x06amx4mqri-coreutils-9.1/bin:/nix/store/fxg62wi3vym2fd2d5ligiwhhd03prprs-binutils-wrapper-2.39/bin:/nix/store/pnajkjw1fz03z1x27ski1qbx9n3hd4df-binutils-2.39/bin:/nix/store/xwx2q2052rg2nnpppwy60h2jg6y2181x-auto-multiple-choice-1.5.2/bin:/nix/store/ngw3m00r391w31n13q4m2x06amx4mqri-coreutils-9.1/bin:/nix/store/vmm828xyvm8pjwjbx33n7z9r45vv1lk3-findutils-4.9.0/bin:/nix/store/hql6cj43x8rb0zdqmyriwavmlw5168hd-diffutils-3.8/bin:/nix/store/scmjiz80b1hh521k06z4fgbkl6r5k84p-gnused-4.8/bin:/nix/store/njz77ksdp38vy6wyb9bq70dzfjxm5im0-gnugrep-3.7/bin:/nix/store/pndr3yb60iqx4igydv2irxi6s6y8rbvb-gawk-5.1.1/bin:/nix/store/y92har9bzzdb54b5scxx258cid5z56f8-gnutar-1.34/bin:/nix/store/88k0f4k4hb13mjqm1xc0sysjysrrw813-gzip-1.12/bin:/nix/store/86zmbdb5acrmf7z0r2vgpy78rw9c0bsi-bzip2-1.0.8-bin/bin:/nix/store/0vxy2dmivgnng1f7c38q80ypkyl6zn65-gnumake-4.3/bin:/nix/store/wim4mqpn8lxhhr10p2kd070hyj152lil-bash-5.1-p16/bin:/nix/store/frq5sgb0gi61zmapdvd6121jz03jnd6m-patch-2.7.6/bin:/nix/store/bi6ryx26yxzhwq5z8qgvkd68qijjrcaz-xz-5.2.7-bin/bin:/nix/store/plangzrapffqqbrb7qrbvk905mdfagl5-file-5.43/bin

[nix-shell:~]$ auto-multiple-choice
Unknown action gui at /nix/store/xwx2q2052rg2nnpppwy60h2jg6y2181x-auto-multiple-choice-1.5.2/bin/.auto-multiple-choice-wrapped line 88.

[nix-shell:~]$
```

After switching with the system version, I get the same error.
After updating the channels (`sudo nix-channel --update`) and rebuilding (` sudo nixos-rebuild --upgrade switch`) I still get the same error.

**Comment by thblt** [comment] 2023-02-06 12:11
Is there a /lib/ directory at your FS root?

**Comment by rgrunbla** [comment] 2023-02-06 12:16
Yup, there is, it contains a subdirectory (modules) which is empty.

**Comment by thblt** [comment] 2023-02-06 12:30
> Does that mean that auto-multiple-choice is also broken on non nixos installations ?

No, because on those, the Perl modules AMC needs are on the global `/lib/`, or `/usr/lib`, or whatever.

The NixOS package, OTOH, is a self-contained, so-called "portable" build where everything  (libs, executables, doc…) lives in a single directory. Your issue comes from the fact that AMC tries to detect such a portable build by first looking for a global `/lib`, *then* defaulting to  `./lib` dir iff the former doesn't exist:

``` perl
my $mods_dir="/lib/";
…
if(! -d $mods_dir) {
    my ($volume,$directory,$file) = splitpath(__FILE__);
    my $wd=getcwd();
    my $base_dir=catfile(catpath( $volume, $directory ),updir);
    chdir($base_dir);
    $base_dir=getcwd();
    chdir($wd);
    $mods_dir=catfile($base_dir,'lib');
    if(! -d $ENV{'AMCBASEDIR'}) {
	$ENV{'PERL5LIB'}=catfile($base_dir,'perl').":".$ENV{'PERL5LIB'};
	$ENV{'TEXINPUTS'}=catfile($base_dir,'latex').":".$ENV{'TEXINPUTS'};
	$ENV{'AMCBASEDIR'}=$base_dir;
	$ENV{'PATH'}=$ENV{'PATH'}.":".catfile($base_dir,'bin');
    }
}
```

I think I can solve this by just changing the default lib dir, please don't close the issue.

**Comment by thblt** [comment] 2023-02-06 13:18
#214934 will fix this.

**Closed** 2023-02-06 15:30 UTC
Labels: 0.kind: bug

**Comment by thblt** [comment] 2023-02-15 20:28
@rgrunbla #216508 reverted the "fix" to that issue, because it broke everything else (my fault). For the time being you need to make sure there's no `/lib` on your system for AMC to work.

**Comment by rgrunbla** [comment] 2023-02-15 20:30
No problem, good luck with that !
