### ISSUE TITLE
Build failure: botan on x86_64-darwin

### ISSUE THREAD

**Issue by GaetanLepage** [NixOS/nixpkgs#333492] opened 2024-08-09 16:28 UTC
### Steps To Reproduce

1. build `botan` on `x86_46_darwin`

### Build log

```
src/cli/sandbox.cpp:18:13: error: 'sandbox.h' file not found with <angled> include; use "quotes" instead
   #include <sandbox.h>
            ^~~~~~~~~~~
            "sandbox.h"
src/cli/sandbox.cpp:104:9: error: no member named 'sandbox_init' in the global namespace
   if(::sandbox_init(kSBXProfileNoWriteExceptTemporary, SANDBOX_NAMED, nullptr) < 0) {
      ~~^
src/cli/sandbox.cpp:104:22: error: use of undeclared identifier 'kSBXProfileNoWriteExceptTemporary'
   if(::sandbox_init(kSBXProfileNoWriteExceptTemporary, SANDBOX_NAMED, nullptr) < 0) {
                     ^
src/cli/sandbox.cpp:104:57: error: use of undeclared identifier 'SANDBOX_NAMED'
   if(::sandbox_init(kSBXProfileNoWriteExceptTemporary, SANDBOX_NAMED, nullptr) < 0) {
                                                        ^
4 errors generated.
```

### Notify maintainers

cc @7c6f434c @thillux 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.43, NixOS, 24.11 (Vicuna), 24.11.20240804.cb9a96f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/4cpakzyvfw1rmm9v5i3387x6jd2h1v86-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by 7c6f434c** [comment] 2024-08-12 03:10
This is an exact duplicate of #333114 right?

**Comment by GaetanLepage** [comment] 2024-08-12 05:34
> This is an exact duplicate of #333114 right?

Indeed it is, sorry for the useless issue.

**Closed** 2024-08-12 05:34 UTC
Labels: 6.topic: darwin, 0.kind: build failure

**Comment by 7c6f434c** [comment] 2024-08-12 14:13
It's easy to internalise that GitHub search is broken on Nixpkgs (which is mostly true), so perfectly understandable not to find the duplicate given the volume…
