### ISSUE TITLE
Deprecate `loaOf`

### ISSUE THREAD

**Issue by shlevy** [NixOS/nixpkgs#1800] opened 2014-02-20 15:58 UTC
`types.loaOf` only exists for backwards compatibility, and it's kind of a hack and doesn't merge well. We should fix all modules that set a list instead of an attribute set in nixpkgs, then once that's done add a trace message when a config is encountered that uses a list instead of a set.

**Comment by Mathnerd314** [comment] 2015-12-09 17:27
Usages:
As ``type = types.loaOf types.optionSet``:
```
nixos/modules/config/users-groups.nix: users.users, users.groups
nixos/modules/security/pam.nix: security.pam.services
nixos/modules/services/logging/logcheck.nix: ignore, ignoreCron
nixos/modules/services/networking/i2pd.nix: outTunnels, inTunnels
nixos/modules/services/networking/prosody.nix: virtualHosts
nixos/modules/services/networking/tinc.nix: networks
nixos/modules/services/web-servers/zope2.nix: services.zope2.instances
nixos/modules/system/etc/etc.nix: environment.etc
nixos/modules/system/upstart/upstart.nix: jobs
nixos/modules/tasks/filesystems.nix: fileSystems
nixos/modules/tasks/network-interfaces.nix: networking.interfaces
nixos/modules/virtualisation/containers.nix: bindMounts
```
Others:
```
nixos/modules/programs/ssh.nix: knownHosts
nixos/modules/services/networking/tinc.nix: hosts
```

**Comment by jagajaga** [comment] 2016-02-26 21:02
Is it still relevant?

**Comment by Mathnerd314** [comment] 2016-02-26 21:28
The file systems and users/groups are used in a lot of places in NixOS. It would be a lot of work to change them, but possible. Personally I like have the list / attribute set choice.

I still wonder what @shlevy meant by "doesn't merge well", as that seems to be the key point.

**Comment by nbp** [comment] 2016-10-31 18:07
> I still wonder what @shlevy meant by "doesn't merge well", as that seems to be the key point.

The problem is that you cannot make list element modular.  Using list in NixOS breaks the modularity.

**Comment by Ericson2314** [comment] 2018-10-01 17:58
This issue is still valid.

**Comment by Ericson2314** [comment] 2018-10-02 00:01
> I still wonder what @shlevy meant by "doesn't merge well", as that seems to be the key point.

Uniqueness of names can be nicely enforced by the set too.

**Comment by joepie91** [comment] 2019-01-14 14:19
What would replace this type?

**Comment by Ericson2314** [comment] 2019-01-14 19:37
`attrsOf`

**Comment by rnhmjoj** [comment] 2019-07-28 09:28
I have made PR #63103 that should safely deprecate `loaOf` but I need help with testing.
I'm trying to get attention and hopefully speeding this up because maintaining the branch up-to-date is getting complicated as time goes on.

**Comment by worldofpeace** [comment] 2020-01-06 16:01
https://github.com/NixOS/nixpkgs/pull/63103 was merged.

**Closed** 2020-01-06 16:01 UTC
Labels: 0.kind: enhancement
