### ISSUE TITLE
Unreproducible package: cabal-install

### ISSUE THREAD

**Issue by myclevorname** [NixOS/nixpkgs#333965] opened 2024-08-11 18:23 UTC
Building this package multiple times does not yield bit-by-bit identical
results, complicating the detection of Continuous Integration (CI) breaches. For
more information on this issue, visit
[reproducible-builds.org](https://reproducible-builds.org/).

Fixing bit-by-bit reproducibility also has additional advantages, such as
avoiding hard-to-reproduce bugs, making content-addressed storage more effective
and reducing rebuilds in such systems.

#### 1. Build the package

This step will build the package. Specific arguments are passed to the command
to keep the build artifacts so we can compare them in case of differences.

Execute the following command:

Note: My system is running nixos-unstable with git commit 5e0ca22929f3342b19569b21b2f3462f053e497b.

```
nix-build '<nixpkgs>' -A cabal-install && nix-build '<nixpkgs>' -A cabal-install --check --keep-failed
```

Or using the new command line style:

```
nix build nixpkgs#cabal-install && nix build nixpkgs#cabal-install --rebuild --keep-failed
```

#### 2. Compare the build artifacts

If the previous command completes successfully, no differences were found and
there's nothing to do, builds are reproducible.
If it terminates with the error message `error: derivation '<X>' may not be
deterministic: output '<Y>' differs from '<Z>'`, use `diffoscope` to investigate
the discrepancies between the two build outputs. You may need to add the
`--exclude-directory-metadata recursive` option to ignore files and directories
metadata (*e.g. timestamp*) differences.

```
nix run nixpkgs#diffoscopeMinimal -- --exclude-directory-metadata recursive <Y> <Z>
```

#### 3. Examine the build log

To examine the build log, use:

```
nix-store --read-log $(nix-instantiate '<nixpkgs>' -A cabal-install)
```

Or with the new command line style:

```
nix log $(nix path-info --derivation nixpkgs#<package>)
```

### Additional context

Related to #333921.
Diffoscope results: https://gist.github.com/myclevorname/8aa1bbd7e18fdd940a78f0819d96a5b7

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by cdepillabout** [comment] 2024-08-13 07:08
I believe this is a duplicate of https://github.com/NixOS/nixpkgs/issues/151347.

**Closed by cdepillabout** 2024-08-13 07:08 UTC
Labels: 0.kind: enhancement, 6.topic: haskell, 6.topic: reproducible builds
