### ISSUE TITLE
Add a nixos-stable channel

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#87124] opened 2020-05-06 18:02 UTC
There are cases where its useful to be able to refer to the latest stable nixpkgs, and not need to manually update release numbers.

keywords: current stable

**Comment by prusnak** [comment] 2020-05-06 19:08
What are these cases? Don't you want to update manually from old-stable to current-stable? Surely you are running stable for some reason, if you wanted rolling update you would be on unstable already.

**Comment by adisbladis** [comment] 2020-05-06 20:19
This would be very valuable in CI for projects like `poetry2nix` & `emacs-overlay` where we support the latest stable release (whatever that happens to be at the time) & unstable.

**Comment by cole-h** [comment] 2020-05-06 20:21
I think the intention was moreso to allow scripting that wasn't so brittle as to only refer to a single release, but whatever the current release at the time is. Instead of referring to `nixos-20.03` and then needing to update it ~6 months down the line, one could just "set-and-forget" `nixos-stable`.

**Comment by kisik21** [comment] 2020-05-06 21:51
This might also simplify installation, as one might just add "nixos-stable" as a channel instead of figuring out which channel is actually stable. Setting `system.stateVersion` properly (the default generated configuration.nix does) should prevent most breakages that might be caused by automatically jumping to a next stable release.

This will also allow to use an older CD to always install a newer NixOS version automagically as long as the tooling stays similar and the user updates the channel with `nix-channel --update` (or was it `--upgrade`? I'm not using channels much, so I can't tell)

**Comment by veprbl** [comment] 2020-05-08 04:56
https://discourse.nixos.org/t/why-is-there-no-rolling-stable-channel/3322/5

**Comment by FRidh** [comment] 2020-05-08 05:21
This is a discussion for on discourse so closing.

**Closed by FRidh** 2020-05-08 05:21 UTC
