### ISSUE TITLE
XEmbed tray icons on MATE became broken

### ISSUE THREAD

**Issue by ilya-fedin** [NixOS/nixpkgs#122053] opened 2021-05-07 17:18 UTC
**Describe the bug**
One of recent packages updates broke XEmbed tray icons on MATE, they lost transparency and have other graphical artifacts. SNI tray icons displayed by the same applet seem to work fine at the same time.

**To Reproduce**
1. Install MATE on NixOS unstable
2. Probably nothing else?

**Expected behavior**
No graphical artifacts

**Screenshots**
![изображение](https://user-images.githubusercontent.com/17829319/117485409-dd9cfa00-af57-11eb-80e1-d2e7909c8ac4.png)

**Notify maintainers**
@romildo

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.16-zen1, NixOS, 21.05pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - nixpkgs: `/run/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: mate.mate-panel
# a list of nixos modules affected by the problem
module: services.xserver.desktopManager.mate
```

**Comment by romildo** [comment] 2021-05-14 17:33
I have tested with those latest updates of mate on NixOS-20.09 and it works as expected. This issue with the icons in the notification does not appear.

**Comment by ilya-fedin** [comment] 2021-05-14 17:36
I'm on nixos unstable

**Comment by romildo** [comment] 2021-05-14 17:43
I am also on NixOS unstable and I see the issue.
I just wanted to see if the issue manifests at the stable version too. It does not.
It may be related to something outside of mate.

**Comment by ilya-fedin** [comment] 2021-05-14 17:50
Oh, ok. Yeah, I think it could be some library for image manipulation or something like cairo/pango. I saw you tried to ask on freenode as well, but the channel looks dead :(

**Comment by romildo** [comment] 2021-05-14 18:01
I have also reported it upstream: https://github.com/mate-desktop/mate-panel/issues/1225

**Comment by romildo** [comment] 2021-05-14 20:50
I think I have found the commit which is causing this issue: 
https://github.com/NixOS/nixpkgs/commit/963a8cfe25b4df70330495b01fa970516cc54b3d

From PR https://github.com/NixOS/nixpkgs/pull/120625

**Comment by romildo** [comment] 2021-05-15 13:12
I have found that this issue was not present at nixos-unstabale revision 1fe6ed37fd9beb92afe90671c0c2a662a03463dd from Sun Apr 25 12:57:28 AM -03 2021.

It first appeared at the following nixos-unstable revision 8e4fe32876ca15e3d5eb3ecd3ca0b224417f5f17 from Mon Apr 26 04:14:03 PM -03 2021

**Comment by ilya-fedin** [comment] 2021-07-14 20:40
Are there any progress?

**Comment by romildo** [comment] 2021-07-14 21:04
> Are there any progress?

No progress. It seems that this issue was introduced by some dependence package committed just after the update of mate. But I could not isolate it, as there are too many commits and I am not an expert with git.

Here https://github.com/NixOS/nixpkgs/issues/122053#issuecomment-841657290 I have found a git revision without the issue on Apr 25, and another with the issue on Apr 26, both after the mate update.

It seems that upstream could not reproduce the issue.

**Comment by ilya-fedin** [comment] 2021-07-14 21:05
I heard about the same problem from Arch users

**Comment by romildo** [comment] 2021-07-14 21:14
> I heard about the same problem from Arch users

When it was reported here on NixOS, I have tried it on Archlinux, and I could not reproduce it there.

**Comment by ilya-fedin** [comment] 2021-07-14 21:14
> But I could not isolate it, as there are too many commits and I am not an expert with git.

But you said cimg is the culprit :hmm:
I can't find that for some reason, but I remember that and I see a reference in the cimg PR
![image](https://user-images.githubusercontent.com/17829319/125693945-3f97a052-ef73-4bb1-864d-525e8cc21c40.png)

**Comment by romildo** [comment] 2021-07-14 21:30
> But you said cimg is the culprit 

At first I thought it was `cimg` because it has been changed between those two revisions I have mentioned. But now I am not sure. There were too much changes in the repository almost at the same time. And it seems that some of the changes were done without a PR, and because of that I cannot be sure that `cimg` update was the culprit. I have tested only revisions between PRs. I have tried to git bissect, but it would take too much time to finish and I have aborted. And again my git knowledge is not that great.

The help of someone more knowledgeable on git with a more powerful machine to test the revisions would be welcome, I think.

**Comment by ilya-fedin** [comment] 2022-04-03 01:15
So I replaced the default volume/battery/keyboard icons with the built-in volume applet and ayatana-indicator-power + ayatana-indicator-keyboard (there's built-in battstat applet, but it bugs on NixOS by appearing and disappearing randomly, works OK on non-NixOS)
![изображение](https://user-images.githubusercontent.com/17829319/161407052-8528b46d-4989-4678-91e2-ad0eb3c0d028.png)
This is a workaround, but I'm fine while I don't see it.

**Comment by hello-smile6** [comment] 2022-04-03 01:30
Doesn't work at all for me @ilya-fedin 
```
            .-/+oossssoo+/-.               runner@93cb721041af 
        `:+ssssssssssssssssss+:`           ------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.2 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: Google Compute Engine 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.13.0-1021-gcp 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 10 hours, 58 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 141 (apt), 207 (nix-user) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.1.12 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1366x577 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Terminal: xterm 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: AMD EPYC 7B12 (8) @ 2.249GHz 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Memory: 16323MiB / 64311MiB 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/                            
  +sssssssssdmydMMMMMMMMddddyssssssss+                             
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.

```

**Comment by ilya-fedin** [comment] 2022-04-03 01:32
@hello-smile6 is this trolling? :thinking:

**Comment by hello-smile6** [comment] 2022-04-03 01:33
> @hello-smile6 is this trolling? 🤔

No, it doesn't work at all.
```

** (mate-panel:938): WARNING **: 01:33:22.646: Cannot register the panel shell: Cannot spawn a message bus without a machine-id: Invalid machine ID in /nix/store/3jz43ya7j65mh53nj262rilsk1j2jb68-glib-2.68.3/var/lib/dbus/machine-id or /etc/machine-id
runner@93cb721041af:~/vnc-gnome$ 
```

**Comment by ilya-fedin** [comment] 2022-04-03 01:36
> No, it doesn't work at all.

What do you refer by 'it'?

**Comment by hello-smile6** [comment] 2022-04-03 01:41
> > No, it doesn't work at all.
> 
> What do you refer by 'it'?

The `mate-panel` package.

**Comment by ilya-fedin** [comment] 2022-04-03 01:43
You have a problem with dbus it seems, but I don't quite understand how this is related to this issue with icons?

**Comment by hello-smile6** [comment] 2022-04-03 01:44
> You have a problem with dbus it seems, but I don't quite understand how this is related to this issue with icons?

Icons don't work either.
![image](https://user-images.githubusercontent.com/73048226/161407649-c48caf80-7419-4691-9798-305b9639545c.png)

**Comment by ilya-fedin** [comment] 2022-04-03 01:46
Well, this doesn't look like the issue described is the first post of the thread (graphical artifacts on otherwise working icons)

**Comment by hello-smile6** [comment] 2022-04-03 01:46
> Well, this doesn't look like the issue described is the first post of the thread (graphical artifacts on otherwise working icons)

Oh, I was mistaken.

**Comment by romildo** [comment] 2022-04-03 16:01
> So I replaced the default volume/battery/keyboard icons with the built-in volume applet and ayatana-indicator-power + ayatana-indicator-keyboard (there's built-in battstat applet, but it bugs on NixOS by appearing and disappearing randomly, works OK on non-NixOS) ![изображение](https://user-images.githubusercontent.com/17829319/161407052-8528b46d-4989-4678-91e2-ad0eb3c0d028.png) This is a workaround, but I'm fine while I don't see it.

How did you proceed to replace those icons? It is not clear to me what are _default icons_ and _built-in icons_.

**Comment by ilya-fedin** [comment] 2022-04-03 16:24
default icons are icons enabled by default (the ones that broken). I said _built-in applets_, not _built-in icons_. It's the applets provided out-of-the-box by MATE, can be adde by 'Add to panel' in the panel's context menu. For Ayatana indicators, I patched multiple packages in nixpkgs and wrote multiple additional derivations.
https://github.com/ilya-fedin/nur-repository/blob/master/overlays/indicator/default.nix
https://github.com/ilya-fedin/nur-repository/blob/master/pkgs/ayatana-indicator-keyboard/default.nix
https://github.com/ilya-fedin/nur-repository/blob/master/pkgs/ayatana-indicator-power/default.nix
https://github.com/ilya-fedin/nur-repository/blob/master/pkgs/libayatana-common/default.nix
https://github.com/ilya-fedin/nur-repository/blob/master/pkgs/cmake-extras/default.nix

**Comment by bobby285271** [comment] 2022-12-26 05:32
Not stale. This is still an issue to me, from my bisect and testing https://github.com/NixOS/nixpkgs/pull/118479 is the reason. Actually what I tested is 824aac34283bf95f2cd12ff1b0ffdb2b042c16e0 and 9d90e2dda237e7c0f1a4d771a5652e0faa85d9bd, and the issue happens in the latter but not in the former commit. Yeah NixOS 21.05pre in year 2022 :-)


<img src="https://user-images.githubusercontent.com/20080233/209500260-55e43a3b-6c8e-4f12-85cb-036002ffdc94.png" width=50%>

Reproducing the issue in a VM is not that painful, probably because https://github.com/NixOS/nixpkgs/pull/118479 has a [Hydra jobset](https://hydra.nixos.org/jobset/nixpkgs/libGL-headers). But you still have to do something with the Nixpkgs checkout:

- You need to apply acf90e478d970767da3b42652e99598f6dc414bb.
- You need to disable `noto-fonts-emoji` in `nixos/modules/config/fonts/fonts.nix` or you need to disable `enableDefaultFonts` - a dependency fails, not really related to this issue.
- It is possible to avoid building webkitgtk - you need to remove `yelp` and also disable gvfs in `nixos/modules/services/x11/desktop-managers/mate.nix`, also you need to remove mostly all extraPackages (but you probably still need to keep mate-applets, mate-media and mate-terminal since you want to reproduce the issue).

**Comment by bobby285271** [comment] 2022-12-26 08:54
Specifically, reverting cd65dfa14cd2b0e665dd37595ded55b23f1e52cd on nixos-unstable fixes the issue. **But** I am not sure if this is the right way, maybe all we need is find out the package that need mesa as optional dependency and add the missing mesa :thinking: 

<img src="https://user-images.githubusercontent.com/20080233/209527936-e29f283d-67a2-4819-ae4c-1e968523bb30.png" width=50%>

**Comment by bobby285271** [comment] 2022-12-26 10:01
Ah, no. Likely gtk3 can be the issue, [gtk3 itself has some optional dependency](https://gitlab.gnome.org/search?search=xdamage&project_id=665&group_id=8&search_code=true&repository_ref=gtk-3-24). I started a build on my proposed fix.

**Comment by bobby285271** [comment] 2023-01-14 16:45
The fix is now in master

**Closed by bobby285271** 2023-01-14 16:45 UTC
Labels: 0.kind: bug, 2.status: fix-in-staging
