### ISSUE TITLE
gitlab cache directory

### ISSUE THREAD

**Issue by ajrouvoet** [NixOS/nixpkgs#19828] opened 2016-10-24 15:12 UTC
## Issue description

Gitlab tries to precompile CSS to path in store. Errors out on 'readonly filesystem'.
### Steps to reproduce

Enable the gitlab module for nixos.

nixos: 16.09

**Comment by ElessarWebb** [comment] 2016-10-26 09:43
Maybe the gitlab package should run something like `gitlab-rake assets:precompile --trace` as part of the build steps?

**Comment by ElessarWebb** [comment] 2016-10-26 11:08
cc @fpletz

**Comment by fpletz** [comment] 2016-10-26 11:35
Can you show us a log where this is happening and when exactly does this happen? I'm running gitlab with the NixOS module without any problems. As you've discovered, all assets should already be precompiled.

**Comment by ElessarWebb** [comment] 2016-10-26 13:32
Yes of course:

```
Oct 26 12:56:27 chat-server systemd[1]: Starting gitlab.service...
Oct 26 12:56:27 chat-server gitlab-pre-start[5985]: tr: write error: Broken pipe
Oct 26 12:56:27 chat-server gitlab-pre-start[5985]: tr: write error
Oct 26 12:56:27 chat-server gitlab-pre-start[5985]: mkdir -p /var/gitlab/state/home/.ssh: OK
Oct 26 12:56:27 chat-server gitlab-pre-start[5985]: chmod 700 /var/gitlab/state/home/.ssh: OK
Oct 26 12:56:27 chat-server gitlab-pre-start[5985]: NOTICE:  extension "pg_trgm" already exists, skipping
Oct 26 12:56:27 chat-server gitlab-pre-start[5985]: CREATE EXTENSION
Oct 26 12:56:53 chat-server gitlab-pre-start[5985]: /nix/store/p5dbnb5d5mrqrqjw9k92v581b6p0p3q0-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:10: warning: already initialized constant Asana::Errors::APIError
Oct 26 12:56:53 chat-server gitlab-pre-start[5985]: /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:10: warning: previous definition of APIError was here
Oct 26 12:56:53 chat-server gitlab-pre-start[5985]: /nix/store/p5dbnb5d5mrqrqjw9k92v581b6p0p3q0-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:20: warning: already initialized constant Asana::Errors::NotAuthorized
Oct 26 12:56:53 chat-server gitlab-pre-start[5985]: /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:20: warning: previous definition of NotAuthorized was here
Oct 26 12:56:53 chat-server gitlab-pre-start[5985]: /nix/store/p5dbnb5d5mrqrqjw9k92v581b6p0p3q0-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:29: warning: already initialized constant Asana::Errors::Forbidden
Oct 26 12:56:53 chat-server gitlab-pre-start[5985]: /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:29: warning: previous definition of Forbidden was here
Oct 26 12:56:53 chat-server gitlab-pre-start[5985]: /nix/store/p5dbnb5d5mrqrqjw9k92v581b6p0p3q0-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:38: warning: already initialized constant Asana::Errors::NotFound
Oct 26 12:56:53 chat-server gitlab-pre-start[5985]: /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:38: warning: previous definition of NotFound was here
Oct 26 12:56:53 chat-server gitlab-pre-start[5985]: /nix/store/p5dbnb5d5mrqrqjw9k92v581b6p0p3q0-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:49: warning: already initialized constant Asana::Errors::ServerError
Oct 26 12:56:53 chat-server gitlab-pre-start[5985]: /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:49: warning: previous definition of ServerError was here
Oct 26 12:56:53 chat-server gitlab-pre-start[5985]: /nix/store/p5dbnb5d5mrqrqjw9k92v581b6p0p3q0-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:65: warning: already initialized constant Asana::Errors::InvalidRequest
Oct 26 12:56:53 chat-server gitlab-pre-start[5985]: /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:65: warning: previous definition of InvalidRequest was here
Oct 26 12:56:53 chat-server gitlab-pre-start[5985]: /nix/store/p5dbnb5d5mrqrqjw9k92v581b6p0p3q0-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:80: warning: already initialized constant Asana::Errors::RateLimitEnforced
Oct 26 12:56:53 chat-server gitlab-pre-start[5985]: /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:80: warning: previous definition of RateLimitEnforced was here
Oct 26 12:56:54 chat-server gitlab-pre-start[5985]: /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/version.rb:4: warning: already initialized constant Asana::VERSION
Oct 26 12:56:54 chat-server gitlab-pre-start[5985]: /nix/store/p5dbnb5d5mrqrqjw9k92v581b6p0p3q0-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/version.rb:4: warning: previous definition of VERSION was here
Oct 26 12:57:00 chat-server gitlab-pre-start[5985]: Rails Error: Unable to access log file. Please ensure that /nix/store/6hvnar92zpdj88d5y1721kyx3dnaw1av-gitlab-8.12.6/share/gitlab/log/production.log exists and is writable (ie, make it writable for user and group:
Oct 26 12:57:06 chat-server gitlab-pre-start[5985]: ** [Raven] Raven 2.0.2 configured not to capture errors.
Oct 26 12:57:10 chat-server systemd[1]: Started gitlab.service.
Oct 26 12:57:15 chat-server /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/bin/unicorn[6057]: Refreshing Gem list
Oct 26 12:57:30 chat-server bundle[6057]: /nix/store/p5dbnb5d5mrqrqjw9k92v581b6p0p3q0-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:10: warning: already initialized constant Asana::Errors::APIError
Oct 26 12:57:30 chat-server bundle[6057]: /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:10: warning: previous definition of APIError was here
Oct 26 12:57:30 chat-server bundle[6057]: /nix/store/p5dbnb5d5mrqrqjw9k92v581b6p0p3q0-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:20: warning: already initialized constant Asana::Errors::NotAuthorized
Oct 26 12:57:30 chat-server bundle[6057]: /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:20: warning: previous definition of NotAuthorized was here
Oct 26 12:57:30 chat-server bundle[6057]: /nix/store/p5dbnb5d5mrqrqjw9k92v581b6p0p3q0-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:29: warning: already initialized constant Asana::Errors::Forbidden
Oct 26 12:57:30 chat-server bundle[6057]: /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:29: warning: previous definition of Forbidden was here
Oct 26 12:57:30 chat-server bundle[6057]: /nix/store/p5dbnb5d5mrqrqjw9k92v581b6p0p3q0-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:38: warning: already initialized constant Asana::Errors::NotFound
Oct 26 12:57:30 chat-server bundle[6057]: /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:38: warning: previous definition of NotFound was here
Oct 26 12:57:30 chat-server bundle[6057]: /nix/store/p5dbnb5d5mrqrqjw9k92v581b6p0p3q0-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:49: warning: already initialized constant Asana::Errors::ServerError
Oct 26 12:57:30 chat-server bundle[6057]: /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:49: warning: previous definition of ServerError was here
Oct 26 12:57:30 chat-server bundle[6057]: /nix/store/p5dbnb5d5mrqrqjw9k92v581b6p0p3q0-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:65: warning: already initialized constant Asana::Errors::InvalidRequest
Oct 26 12:57:30 chat-server bundle[6057]: /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:65: warning: previous definition of InvalidRequest was here
Oct 26 12:57:30 chat-server bundle[6057]: /nix/store/p5dbnb5d5mrqrqjw9k92v581b6p0p3q0-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:80: warning: already initialized constant Asana::Errors::RateLimitEnforced
Oct 26 12:57:30 chat-server bundle[6057]: /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:80: warning: previous definition of RateLimitEnforced was here
Oct 26 12:57:30 chat-server bundle[6057]: /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/version.rb:4: warning: already initialized constant Asana::VERSION
Oct 26 12:57:30 chat-server bundle[6057]: /nix/store/p5dbnb5d5mrqrqjw9k92v581b6p0p3q0-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/version.rb:4: warning: previous definition of VERSION was here
Oct 26 12:57:34 chat-server bundle[6057]: Rails Error: Unable to access log file. Please ensure that /nix/store/6hvnar92zpdj88d5y1721kyx3dnaw1av-gitlab-8.12.6/share/gitlab/log/production.log exists and is writable (ie, make it writable for user and group: chmod 066
Oct 26 12:57:43 chat-server bundle[6057]: ** [Raven] Raven 2.0.2 configured not to capture errors.
Oct 26 12:57:44 chat-server /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/bin/unicorn[6057]: unlinking existing socket=/var/gitlab/state//tmp/sockets/gitlab.socket
Oct 26 12:57:44 chat-server /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/bin/unicorn[6057]: listening on addr=/var/gitlab/state//tmp/sockets/gitlab.socket fd=11
Oct 26 12:57:44 chat-server /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/bin/unicorn[6057]: worker=0 spawning...
Oct 26 12:57:44 chat-server /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/bin/unicorn[6100]: worker=0 ready
Oct 26 12:57:44 chat-server /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/bin/unicorn[6057]: worker=1 spawning...
Oct 26 12:57:44 chat-server /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/bin/unicorn[6103]: worker=1 ready
Oct 26 12:57:44 chat-server /nix/store/dp5rj3b6sqwb7q8jjkzh4is8h721m8pn-gitlab/lib/ruby/gems/2.2.3/bin/unicorn[6057]: master process ready
Oct 26 12:57:47 chat-server bundle[6057]: Started GET "/users/sign_in" for 10.140.1.118 at 2016-10-26 12:57:47 +0200
Oct 26 12:57:48 chat-server bundle[6057]: Processing by SessionsController#new as HTML
Oct 26 12:57:49 chat-server bundle[6057]: Completed 200 OK in 634ms (Views: 275.7ms | ActiveRecord: 61.5ms)
Oct 26 12:57:49 chat-server bundle[6057]: Started GET "/assets/application-fc596e7bbc989b689b94960672c0c4af5cb7a609cd2a9ac4e9b34bcf27f20456.js" for 10.140.1.118 at 2016-10-26 12:57:49 +0200
Oct 26 12:57:54 chat-server bundle[6057]: Started GET "/assets/application-090580f4d395c3be8b464f0f80eb22b9751c9c2390dae48dc9aac31d0207d27f.css" for 10.140.1.118 at 2016-10-26 12:57:53 +0200
Oct 26 12:57:54 chat-server bundle[6057]: Started GET "/assets/print-68eed6d8135d858318821e790e25da27b2b4b9b8dbb1993fa6765d8e2e3e16ee.css" for 10.140.1.118 at 2016-10-26 12:57:54 +0200
Oct 26 12:58:00 chat-server bundle[6057]: Started GET "/assets/favicon-075eba76312e8421991a0c1f89a89ee81678bcde72319dd3e8047e2a47cd3a42.ico" for 10.140.1.118 at 2016-10-26 12:58:00 +0200
Oct 26 12:58:00 chat-server bundle[6057]: Errno::EROFS (Read-only file system @ utime_internal - /nix/store/6hvnar92zpdj88d5y1721kyx3dnaw1av-gitlab-8.12.6/share/gitlab/tmp/cache/assets/sprockets/v3.0/4W/4WCUUPGXMHZpzGDcJaGX5GyXFodGVk4iLB6XZ8Bo0Ls.cache):
Oct 26 12:58:00 chat-server bundle[6057]:   lib/gitlab/request_profiler/middleware.rb:15:in `call'
Oct 26 12:58:00 chat-server bundle[6057]:   lib/gitlab/middleware/go.rb:16:in `call'
```

from `journalctl -u gitlab`. It happens on the first request, proxy_passed by nginx.

**Comment by ElessarWebb** [comment] 2016-10-28 07:55
@fpletz does that tell you anything?

**Comment by mbrgm** [comment] 2016-11-11 10:56
I can confirm this error on a24728fe295f28648f1812b3565541f7ef6269f1.

**Comment by ElessarWebb** [comment] 2016-12-01 13:15
Since this bug is now confirmed, is there anyone with some experience with gitlab who can help out?

**Comment by mbrgm** [comment] 2017-02-16 20:26
Same problem on current nixos-unstable.

**Comment by mbrgm** [comment] 2017-02-16 23:18
Ok, so it seems the sprockets gem tries to touch the file when it's loaded into the cache. The only reason I can think of is that this is for updating the atime. However, this requires the file to be writable, so I see some options to workaround:

1. Copy the precompiled cache dir into `/run/gitlab/cache` or similar upon startup, symlink that dir from the gitlab package
2. Copy the precompiled cache dir into the state dir on first start, symlink that into `/run/gitab/cache` and symlink that path from the gitlab package
3. Patch the sprockets gem and remove the `touch` part.

(1) could add some delay upon startup, so I don't like that quite much, but imho it's still better than (2), as this would add some distributed, basically immutable files to the place where I would expect all non-reproducible data, which I would also backup etc. Of all three options, (3) is most appealing to me, but it could also have some side effects, which I forgot to consider, so I'd be happy to hear someone else's opinion on that.

@fpletz As maintainer of the module, I think you have the most experience using it -- what do you think? I am still wondering why you are not having the same problem in your deployment. :-/

**Comment by fpletz** [comment] 2017-02-16 23:41
Yeah, this is so weird. Thanks for digging into this, I'll have a look before 17.03 is released.

**Comment by mbrgm** [comment] 2017-02-17 07:12
@fpletz I attached strace to the worker processes of the freshly started gitlab service, then loaded the sign in page. From that I could see the `utimensat()` syscall into the assets cache directory (first one was for the favicon as in @ElessarWebb's log from above). Maybe this helps with your debugging.

**Comment by mbrgm** [comment] 2017-02-17 07:45
So I couldn't stop digging :D 

The file seems to be touched for garbage collection: https://github.com/rails/sprockets/commit/5a43ec169dbbdf35283a586603e8779f7ab05b06

In the [find_caches](https://github.com/rails/sprockets/blob/02814b286684202c3aeca5095e0aedcf9fb2c604/lib/sprockets/cache/file_store.rb#L147..L155) method the cache files are collected and sorted by their mtime, then in [gc!](https://github.com/rails/sprockets/blob/02814b286684202c3aeca5095e0aedcf9fb2c604/lib/sprockets/cache/file_store.rb#L178..L200) a part of them (exceeding some maximum number of cache files) is deleted. Maybe we should refrain from patching the sprockets gem then and ensure the cache dir is writable instead.

**Comment by arianvp** [comment] 2017-03-15 08:28
So 2) seems the most favorable solution right now, right?

**Comment by mbrgm** [comment] 2017-03-15 20:15
@arianvp Yes, at least imho.

**Comment by fpletz** [comment] 2017-04-02 00:35
I've just set up a new gitlab instance and am still not able to reproduce this issue. :sob:

**Comment by mbrgm** [comment] 2017-04-02 12:46
@fpletz Which commit of nixpkgs? Let me try it with that exact same commit myself.

**Comment by mbrgm** [comment] 2017-05-19 22:05
@fpletz Is there a chance you'll be looking at this in the near future? I'd really like to run Gitlab on NixOS, but currently the cache directory issue is blocking this. I already fixed it in my branch of nixpkgs, but as far as I interpret this ticket, other people are having the same problem -- so this fix should become a PR.

**Comment by fpletz** [comment] 2017-05-21 04:14
Could you please open a PR with your changes for review?

**Comment by globin** [comment] 2018-09-25 01:58
Closing, as this has not seen any recent activity and other people have been using gitlab successfully.

**Closed by globin** 2018-09-25 01:58 UTC
Labels: 0.kind: bug
