### ISSUE TITLE
black nixos test linting

### ISSUE THREAD

**Issue by blaggacao** [NixOS/nixpkgs#121066] opened 2021-04-28 18:29 UTC
https://github.com/NixOS/nixpkgs/blob/f93ecc4f6bc60414d8b73dbdf615ceb6a2c604df/nixos/lib/testing-python.nix#L152

This linting is good but it should ignore line length as there might be unpredictable valuables (e.g. nix store paths) rendered into the scripts that break in arbitrary instances.

eg:

```python
      kube.wait_until_succeeds(
          "kubectl apply -f ${config.kubernetes.result}"
      )
```

or

```python
      kube.wait_until_succeeds("kubectl apply -f ${config.kubernetes.result}")
```

depends solely on the length of the actual `config.kubernetes.result` string.

**Comment by dotlambda** [comment] 2021-05-01 14:23
duplicate of https://github.com/NixOS/nixpkgs/issues/72964

**Closed by dotlambda** 2021-05-01 14:23 UTC

**Comment by blaggacao** [comment] 2021-05-01 16:33
Thanks @dotlambda !
