### ISSUE TITLE
virt-manager: Namespace LibvirtGLib not available

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#57107] opened 2019-03-09 06:24 UTC
## Issue description

VirtManager won't start anymore on recent git-master.

```
virt-manager
Traceback (most recent call last):
  File "/nix/store/bglalcfa4is60zinq4mnd18855mh1nwm-virt-manager-2.1.0/share/virt-manager/virt-manager", line 17, in <module>
    gi.require_version('LibvirtGLib', '1.0')
  File "/nix/store/kiw47xswi1041sbvbgrlfy0xs0zlwyvk-python3.7-pygobject-3.30.4/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace LibvirtGLib not available
```

### Steps to reproduce

1. Add virtmanager to the system packages in the configuration.nix
2. Try to start it

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.104, NixOS, 19.09.git.c6aa1dd (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(hyper): `"nixos-19.09pre170705.1233c8d9e9b"`
 - channels(root): `"nixos-19.09pre170705.1233c8d9e9b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment] 2019-03-09 13:00
Duplicate of #56943

**Closed by jtojnar** 2019-03-09 13:00 UTC
