### ISSUE TITLE
Nox-review is broke

### ISSUE THREAD

**Issue by ndowens** [NixOS/nixpkgs#24261] opened 2017-03-24 00:26 UTC
## Issue description
I believe https://github.com/NixOS/nixpkgs/pull/24133 caused nox-review to break as it gives undefind variable gtk in qt-5/5.7.nix 

When looking at the changes I see gtk3 defind, but below i see gnome3.gtk(which would be the undefind one)

### Steps to reproduce

nox-review anything

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by globin** [comment] 2017-03-24 00:34
Fixed on 17.03 at least, thought those were caused by cherry-picking, checking master right now.

**Closed** 2017-03-24 00:35 UTC
