### ISSUE TITLE
Cannot install google-fonts: hash mismatch

### ISSUE THREAD

**Issue by wandernauta** [NixOS/nixpkgs#20282] opened 2016-11-09 18:22 UTC
## Issue description

When I try to install `google-fonts`, the installation fails with a hash mismatch:

    output path ‘/nix/store/n39mbp5nbw8vmrsnhgc2m7sk1p152qn9-google-fonts’ has r:sha256 hash ‘09r9yn95p76symvmanqbwd3zbwai9aiflrdrfjnz9yr2cbnn577r’ when ‘0q03gg0sh2mljlbmhamnxz28d13znh9dzca84p554s7pwg6z4wca’ was expected

### Steps to reproduce

    nix-env -i google-fonts

## Technical details

My system is as follows:

* System: 16.09.975.1e1112e (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "16.09.975.1e1112e"

However, the same error appears on other systems.

**Comment by copumpkin** [comment] 2016-11-09 18:41
https://github.com/NixOS/nixpkgs/blob/master/pkgs/data/fonts/google-fonts/default.nix looks really strange to me, in effect trying to be a "two-level" fixed-output derivation. @manveru, do you know what's up with that?

**Comment by copumpkin** [comment] 2016-11-09 18:42
Oh, it looks like @edolstra did that fairly recently: https://github.com/NixOS/nixpkgs/commit/1681718e2fd81c2613604df0a3fbb259bf213ceb

**Comment by copumpkin** [comment] 2016-11-09 18:44
The danger of making a derivation into a fixed-output derivation like that is that if any of the inputs change their behavior slightly, the FO derivation breaks.

**Comment by edolstra** [comment] 2016-11-14 16:35
I think this was fixed in c015c2910693f47b641f325f66e690158c3d2652.

**Comment by copumpkin** [comment] 2016-11-14 16:37
@edolstra but the hash it was complaining about in OP was the `google-fonts` output hash, not its source hash (which admittedly will also change with a straight `fetchurl`, so the commit you linked to is still useful), so my concern about fragility still stands

**Comment by edolstra** [comment] 2016-11-14 16:38
Note that there is nothing wrong with using a fixed-output derivation. In fact it revealed an actual problem, namely that the build was non-deterministic in a bad way: depending on directory order it would copy different TTF files.

**Comment by sid-kap** [comment] 2016-12-06 16:29
I just had this problem today. I'm on nixos-unstable, so I would expect that the patch should have fixed it. Is there something I can do to check what version of the packages I'm on, to see if the problem persists?

**Comment by vcunat** [comment] 2016-12-09 18:09
It seems OK to me on current nixos-unstable (1c50bdd9).

**Comment by sid-kap** [comment] 2016-12-19 16:28
@vcunat How do I check whether my nix channel contains that commit? My nixpkgs version is:

```bash
$ nix-instantiate --eval -E '(import <nixpkgs> {}).lib.nixpkgsVersion'
"16.09.1086.7596205"
```

**Comment by vcunat** [comment] 2016-12-19 16:49
@sid-kap: you said you were on nixos-unstable, but your version indicates 16.09 (i.e. stable). Still, it does work for me even on your version.

**Comment by vcunat** [comment] 2016-12-19 16:51
...which might be just because `http://tarballs.nixos.org` is used before the original URL.

**Comment by sid-kap** [comment] 2016-12-19 19:48
Hmm, I wonder why that is. I followed the instructions [in Chapter 4 of the Nixos Manual](https://nixos.org/nixos/manual/#sec-upgrading). Is there something else I need to do to switch to unstable?

**Comment by sid-kap** [comment] 2016-12-19 20:01
I ran `nixos-rebuild switch --upgrade`, and now my version is up to "16.09.1272.81428dd". Why did it not upgrade me to unstable? Here is the output of `nix-channel --list`:

```
nixos https://nixos.org/channels/nixos-unstable
```

**Comment by sid-kap** [comment] 2016-12-19 20:03
In case this might be useful, the output of `cat /nix/var/nix/profiles/per-user/root/channels/nixpkgs/.version` is 17.03, but the output of `cat /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/.version` is 16.09.

**Comment by vcunat** [comment] 2016-12-19 20:17
We're getting a bit off-topic, but for `nixos-rebuild` the **root**s channels are what you should look at, e.g. `sudo nixos-channel --list`.  In the manual that's signified as the command lines starting by `#`; I'm not sure if there's some explicit statement.

**Comment by sid-kap** [comment] 2016-12-19 20:32
Thanks, that worked. Google Fonts now installs properly on my machine.

**Comment by vcunat** [comment] 2016-12-19 20:46
Well, let me close. If someone can reproduce the problem on a recent (un)stable channel, we'll reopen.

**Closed by vcunat** 2016-12-19 20:46 UTC
Labels: 0.kind: regression, 6.topic: reproducible builds, 9.needs: community feedback

**Comment by volth** [comment] 2016-12-20 05:33
it is not fixed in 16.09 (stable)

**Comment by vcunat** [comment] 2016-12-21 19:40
I retried ensuring download comes from github, and it succeeded with the same hash we have in 16.09 for months.

**Comment by volth** [comment] 2016-12-22 12:57
I got a hash mispatch like that of the ticket started (although with different hash value) and ended up in adding ```google-fonts = pkgs.google-fonts.overrideDerivation (old: { outputHash
= "0nbbdscjcl3aisf13r5qsyr718xjnfagwzxm62xvlp0dr6lm4n8r"; });``` into ```~/.nixpkgs/config.nix```

**Comment by vcunat** [comment] 2016-12-22 13:57
I did yet another download from github, from a different network, and still the hash we got committed. I've got no idea how some people could get a different one. We could try comparing individual file hashes, etc. but as long as it's just a single package...

**Comment by volth** [comment] 2016-12-22 14:48
It is the second hash, not the hash over the downloaded archive file (this one is matched) but the hash over unpacked files. It looks like the unpacking brings some non-determenism. Perhaps, the order of the files is different?

**Comment by vcunat** [comment] 2016-12-22 14:57
Nix store hashes don't exhibit such "bugs" normally.

**Comment by vcunat** [comment] 2016-12-22 14:58
Still, it's possible that `fetchzip` is buggy in this respect.

**Comment by copumpkin** [comment] 2016-12-22 15:54
> Still, it's possible that fetchzip is buggy in this respect.

@vcunat @volth is talking about the output hash being a mismatch, not the `fetchFromGitHub` one.

**Comment by vcunat** [comment] 2016-12-22 16:09
Ah, right, it's most likely that buggy usage of `find` that we've fixed on master already but haven't backported to 16.09 yet. I somehow missed the difference from master.

**Comment by vcunat** [comment] 2016-12-22 16:13
Picked all those changes now.
