### ISSUE TITLE
irssi 1.4.1 fails to build on darwin arm64

### ISSUE THREAD

**Issue by jbg** [NixOS/nixpkgs#180308] opened 2022-07-06 05:04 UTC
### Steps To Reproduce
1. build *irssi*

### Build log
```
building '/nix/store/0nzqzr7p3dw7hb77qcihn681592cg7nc-irssi-1.4.1.drv'...
unpacking sources
unpacking source archive /nix/store/3lflfyjjpjarria38plcbhlzjg8hl2lc-source
source root is source
patching sources
updateAutotoolsGnuConfigScriptsPhase
configuring
meson flags: --buildtype=plain         --libdir=/nix/store/wibchxh7s5x8svxsansrbbvglv2qfhgk-irssi-1.4.1/lib --libexecdir=/nix/store/wibchxh7s5x8svxsansrbbvglv2qfhgk-irssi-1.4.1/libexec         --bindir=/nix/store/wibchxh7s5x8svxsansrbbvglv2qfhgk-irssi-1.4.1/bin --sbindir=/nix/store/wibchxh7s5x8svxsansrbbvglv2qfhgk-irssi-1.4.1/sbin         --includedir=/nix/store/wibchxh7s5x8svxsansrbbvglv2qfhgk-irssi-1.4.1/include         --mandir=/nix/store/wibchxh7s5x8svxsansrbbvglv2qfhgk-irssi-1.4.1/share/man --infodir=/nix/store/wibchxh7s5x8svxsansrbbvglv2qfhgk-irssi-1.4.1/share/info         --localedir=/nix/store/wibchxh7s5x8svxsansrbbvglv2qfhgk-irssi-1.4.1/share/locale         -Dauto_features=enabled         -Dwrap_mode=nodownload         --prefix=/nix/store/wibchxh7s5x8svxsansrbbvglv2qfhgk-irssi-1.4.1  
The Meson build system
Version: 0.61.2
Source dir: /private/tmp/nix-build-irssi-1.4.1.drv-0/source
Build dir: /private/tmp/nix-build-irssi-1.4.1.drv-0/source/build
Build type: native build
Project name: irssi
Project version: 1.4.1
C compiler for the host machine: clang (clang 11.1.0 "clang version 11.1.0")
C linker for the host machine: clang ld64 530
Host machine cpu family: aarch64
Host machine cpu: arm64
WARNING: You should add the boolean check kwarg to the run_command call.
         It currently defaults to false,
         but it will default to true in future releases of meson.
         See also: https://github.com/mesonbuild/meson/issues/9300
Program perl found: YES (/nix/store/fa4a1vk6pynwwngb2mv5nvnl8iy4fpp6-perl-5.34.1/bin/perl)
Program env found: YES (/nix/store/7lcs7f623978z7ky28f77sp97c7sjlfc-coreutils-9.1/bin/env)
Program utils/irssi-version.sh found: YES (/private/tmp/nix-build-irssi-1.4.1.drv-0/source/utils/irssi-version.sh)
Program utils/file2header.sh found: YES (/private/tmp/nix-build-irssi-1.4.1.drv-0/source/utils/file2header.sh)
Checking for function "inet_addr" : YES 
Checking for function "socket" : YES 
Message: *** If you don't have GLib, you can run meson ... -Dinstall-glib=yes
Message: *** to download and build it automatically
Message: *** Or alternatively install your distribution's package
Message: *** On Debian: sudo apt-get install libglib2.0-dev
Message: *** On Redhat: dnf install glib2-devel
Found pkg-config: /nix/store/wi6p41jfw3gx7zwvrqdysjvkq47kpn90-pkg-config-wrapper-0.29.2/bin/pkg-config (0.29.2)
Run-time dependency glib-2.0 found: YES 2.72.2
Run-time dependency gmodule-2.0 found: YES 2.72.2
Run-time dependency openssl found: YES 1.1.1p
Library utf8proc found: NO
Checking for function "utf8proc_version" with dependency -lutf8proc: NO 
Library tinfo found: YES
Checking for function "setupterm" with dependency -ltinfo: YES 
Compiler for C supports arguments -fPIC: YES 
Checking if "working Perl support" : links: YES 
Run-time dependency libgcrypt found: YES 1.10.1
Run-time dependency libotr found: YES 4.1.1
Library c found: YES
Checking for function "cap_enter" with dependency -lc: NO 
Has header "sys/ioctl.h" : YES 
Has header "sys/resource.h" : YES 
Has header "sys/time.h" : YES 
Has header "sys/utsname.h" : YES 
Has header "dirent.h" : YES 
Has header "term.h" : YES 
Has header "unistd.h" : YES 
Configuring irssi-config.h using configuration
Compiler for C supports arguments -Werror=declaration-after-statement: YES 
Compiler for C supports arguments -fno-strict-aliasing: YES 
Message: *** Irssi configured ***
Message: 
Message: Building text frontend ........... : yes
Message: Building irssi bot ............... : no
Message: Building irssi proxy ............. : no
Message: Building with Perl support ....... : yes
Message: Perl library directory ........... : /nix/store/wibchxh7s5x8svxsansrbbvglv2qfhgk-irssi-1.4.1/lib/irssi/perl
Message:                                      in prefix - prepends to @INC with /set perl_use_lib
Message: Install prefix ................... : /nix/store/wibchxh7s5x8svxsansrbbvglv2qfhgk-irssi-1.4.1
Message: 
Message: Building with true color support.. : no
Message: Building with GRegex ............. : yes
Message: Building with Capsicum ........... : no
Message: Building with utf8proc ........... : no
Message: Building with OTR support ........ : yes
Message: 
Message: If there are any problems, read the INSTALL file.
Message: Now type ninja -C /private/tmp/nix-build-irssi-1.4.1.drv-0/source/build to build Irssi
Message: 
Build targets in project: 29
NOTICE: Future-deprecated features used:
 * 0.58.0: {'meson.get_cross_property'}

irssi 1.4.1

  User defined options
    auto_features: enabled
    bindir       : /nix/store/wibchxh7s5x8svxsansrbbvglv2qfhgk-irssi-1.4.1/bin
    buildtype    : plain
    includedir   : /nix/store/wibchxh7s5x8svxsansrbbvglv2qfhgk-irssi-1.4.1/include
    infodir      : /nix/store/wibchxh7s5x8svxsansrbbvglv2qfhgk-irssi-1.4.1/share/info
    libdir       : /nix/store/wibchxh7s5x8svxsansrbbvglv2qfhgk-irssi-1.4.1/lib
    libexecdir   : /nix/store/wibchxh7s5x8svxsansrbbvglv2qfhgk-irssi-1.4.1/libexec
    localedir    : /nix/store/wibchxh7s5x8svxsansrbbvglv2qfhgk-irssi-1.4.1/share/locale
    mandir       : /nix/store/wibchxh7s5x8svxsansrbbvglv2qfhgk-irssi-1.4.1/share/man
    prefix       : /nix/store/wibchxh7s5x8svxsansrbbvglv2qfhgk-irssi-1.4.1
    sbindir      : /nix/store/wibchxh7s5x8svxsansrbbvglv2qfhgk-irssi-1.4.1/sbin
    wrap_mode    : nodownload

Found ninja-1.10.2 at /nix/store/8lz7f94gz08cx0mp0xqgv8lfkpqrgdk9-ninja-1.10.2/bin/ninja
meson: enabled parallel building
building
build flags: -j8 -l8

     ... [snipped successfully-built targets] ...

[273/285] Linking target tests/fe-common/core/test-formats
FAILED: tests/fe-common/core/test-formats 
clang  -o tests/fe-common/core/test-formats tests/fe-common/core/test-formats.p/test-formats.c.o -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,error src/lib-config/libirssi_config.a src/core/libcore.a src/fe-common/core/libfe_common_core.a /nix/store/f5n48d4f00j5vbl4d1ja8qsansjhm7f5-glib-2.72.2/lib/libglib-2.0.dylib /nix/store/f5n48d4f00j5vbl4d1ja8qsansjhm7f5-glib-2.72.2/lib/libgmodule-2.0.dylib /nix/store/p06fqvj48xvnk6pr30d9fvvz558cxn7m-openssl-1.1.1p/lib/libssl.dylib /nix/store/p06fqvj48xvnk6pr30d9fvvz558cxn7m-openssl-1.1.1p/lib/libcrypto.dylib /nix/store/bc9lijm0g4dr37k4nxbiwihykgm67zm1-libgcrypt-1.10.1/lib/libgcrypt.dylib /nix/store/8yah3kxxp3drwja61m10al3nykdbb9dz-libotr-4.1.1/lib/libotr.dylib
Undefined symbols for architecture arm64:
  "_current_theme", referenced from:
      _format_get_text_theme in libfe_common_core.a(formats.c.o)
      _format_get_text in libfe_common_core.a(formats.c.o)
      _strip_codes in libfe_common_core.a(formats.c.o)
      _format_send_as_gui_flags in libfe_common_core.a(formats.c.o)
      _window_print_daychange in libfe_common_core.a(fe-windows.c.o)
      _printformat_module_dest_charargs in libfe_common_core.a(printtext.c.o)
      _printformat_module_gui_args in libfe_common_core.a(printtext.c.o)
      ...
  "_default_formats", referenced from:
      _format_find_tag in libfe_common_core.a(formats.c.o)
      _format_get_text_theme_args in libfe_common_core.a(formats.c.o)
      _printformat_module_dest_args in libfe_common_core.a(printtext.c.o)
      _printformat_module_gui_args in libfe_common_core.a(printtext.c.o)
ld: symbol(s) not found for architecture arm64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
error: builder for '/nix/store/0nzqzr7p3dw7hb77qcihn681592cg7nc-irssi-1.4.1.drv' failed with exit code 1
```

### Notify maintainers
@fab @lovek323

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.5.0, macOS 12.4`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.9.1`
 - channels: `"nixpkgs, stable-21.11-darwin"`
 - nixpkgs: `~/.nix-defexpr/channels/nixpkgs`
```

**Comment by fabaff** [comment] 2022-07-06 09:06
With https://github.com/NixOS/nixpkgs/pull/177772 the package was migrated to use `mason`. I don't have a `darwin` host at hand,. Thus I would only have the option to disable the builds for `aarch64-darwin` if no @NixOS/darwin-maintainers helps out.

**Comment by jiegec** [comment] 2022-07-09 00:41
I propose another fix for this:

```nix
CFLAGS = ["-fno-common"];
```

**Comment by wegank** [comment] 2022-07-09 03:36
@jiegec Way better than mine! Would you like to make a pull request?

**Comment by jiegec** [comment] 2022-07-09 03:41
> @jiegec Way better than mine! Would you like to make a pull request?

I am still investigating the strange behavior of ld on darwin with regard to COMMON symbols. I can't reproduce the same issue under linux even with -fcommon enabled.

**Comment by jiegec** [comment] 2022-07-11 12:02
> current_theme and default_formats are both declared as extern in themes.h and defined exactly once (in themes.c), do you have any deeper insight why this code would fail to link?

Yes, the one definition rule is obeyed. But the global variables do not have initializers, and they are compiled as COMMON symbols. And the linker has some strange behavior with regard to them when the archive (.a) is passed to the linker.

**Comment by jiegec** [comment] 2022-07-11 12:08
> as far as I understand the C standard, explicit initialisation to zero is not required for static variables?

Yes. It is unrelated to C standard. It was an attempt to become compatible with Fortran code. See https://maskray.me/blog/2022-02-06-all-about-common-symbols.

**Comment by wegank** [comment] 2022-08-29 23:05
Should be building fine [now](https://hydra.nixos.org/job/nixpkgs/nixpkgs-unstable-aarch64-darwin/irssi.aarch64-darwin).

**Closed** 2022-08-30 02:28 UTC
Labels: 6.topic: darwin, 0.kind: build failure
