### ISSUE TITLE
Python package name normalization

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#94629] opened 2020-08-03 22:48 UTC
**Describe the bug**
There's still a few python packages which aren't normalized E.g. `Fabric, FormEncode`

It would be nice if we did a normalization pass, and gave a warning to the user if they do use the non-normalized name.

Ideally this could be done before the 20.09 release

cc @FRidh 

when I have time, i could create an example PR, however, my current plan would be:

```
  Fabric = callPackage ../development/python-modules/Fabric { };
```
to
```
    fabric = callPackage ../development/python-modules/fabric { };
    Fabric = lib.warn "Fabric has been deprecated, please use 'fabric' instead" self.fabric;
```

**Comment by FRidh** [comment] 2020-08-04 08:33
I think we can extend the fixed point with a `mapAttrs` that does this.

**Comment by jonringer** [comment] 2020-08-04 19:58
I would also like to remove the incorrect attrs after 20.09. If we can do that with `mapAttrs` then I'm not opionated on the implementation

**Comment by FRidh** [comment] 2020-08-04 20:04
That's harder. The best we can do is extend the error stating the actual attributes need to be fixed.

**Comment by jonringer** [comment] 2020-08-04 20:08
I was just going to some batches where I did these manually. I don't think there's enough to justify a blanket `mapAttrs` operation to everything. Plus I would like to change the directory names to reflect normalized name as well

**Comment by FRidh** [comment] 2020-08-04 20:10
That would be best. As soon as its done I intend to at least have a `mapAttrs` that asserts all attributes are normalized.

**Comment by jonringer** [comment] 2020-08-04 20:14
I'll put some time into it this week. Hopefully it will be <100 packages

**Comment by FRidh** [comment] 2020-08-29 07:24
Closing as duplicate of https://github.com/NixOS/nixpkgs/issues/49691.

**Closed by FRidh** 2020-08-29 07:24 UTC
Labels: 0.kind: enhancement, 6.topic: python

**Comment by jonringer** [comment] 2020-08-29 07:54
maybe after the 20.09 release, we could just force normalize all python names
