### ISSUE TITLE
libc is broken

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#51939] opened 2018-12-13 11:45 UTC
## Issue description
I thought the segfaults for Google Chrome (Related issue: https://github.com/NixOS/nixpkgs/issues/51870) were an isolated incident, but it happens on more systems; even systems not running any desktop manager. 

@dtzWill said something about this operating system not having various libc patches and being behind a release.

> qemu-system-x86[20107]: segfault at 0 ip 00007f226320a0db sp 00007f20e7381e58 error 4 in libc-2.27.so[7f22630b6000+1aa000]

### Steps to reproduce
???

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.09.git.4f3446f (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1023.06fb0253afa"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by edolstra** [comment] 2018-12-13 15:44
All sorts of application bugs can cause segfaults in libc, so this does not indicate a libc bug.

**Comment by matthewbauer** [comment] 2018-12-13 18:51
Most likely the version google-chrome was compiled with is incompatible with our version. I would recommend just using chromium. IMO we should get rid of these binary-only packages.

**Comment by rasendubi** [comment] 2018-12-13 22:30
Possible duplicate of https://github.com/NixOS/nixpkgs/issues/46890?

**Comment by memberbetty** [comment] 2018-12-14 11:37
This was for qemu-system-x86 for which no alternative exists.

**Comment by vcunat** [comment] 2018-12-14 11:40
I think the report is too vague so far to guess what exactly is wrong.

**Closed** 2018-12-14 12:47 UTC

**Comment by markuskowa** [comment] 2018-12-14 15:15
@matthewbauer google-chrome is still required for streaming services like netflix or amazon prime video due to a DRM module. Those services do not work with chromium.

**Comment by vcunat** [comment] 2018-12-14 16:06
glibc maintains a very high level of binary compatibility, and incompatibilities (which may happen if run-time glibc is _older_ than build-time glibc) should not to be as ugly as segfaults &ndash; typically just missing symbols during load-time.

If you want to move this forward, I'd suggest trying to get more information, e.g. a (partial) stack trace or something.
