### ISSUE TITLE
vim 7.4.23 crashes, runs fine in pure shell

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#73969] opened 2019-11-23 15:40 UTC
**Describe the bug**
vim 7.4.23 installed from revision `009780587f6fa636f01b6b26cd1187545b9cfd66` crashes with this error:

```
vim: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
[1]    31943 abort (core dumped)  vim
```

even if it's installed in an empty user environment. Runs fine from a pure nix-shell.

**To Reproduce**
1. Install vim from above revision and run it

**Expected behavior**
vim shouldn't crash

**Screenshots**
strace output: https://gist.github.com/sagartewari01/f7957a913943c6ccfef6fbaab2636ac9

ldd output suggests that it's using the correct libc:

	linux-vdso.so.1 (0x00007fff3ead7000)
	libm.so.6 => /nix/store/zm4bhsm8lprkzvrjgqr0klfkvr21als4-glibc-2.17/lib/libm.so.6 (0x00007fa308a3b000)
	libncursesw.so.5 => /nix/store/q96qckiwzh055rd2b0fsnkd0a4xr5nis-ncurses-5.9/lib/libncursesw.so.5 (0x00007fa3087e0000)
	libdl.so.2 => /nix/store/zm4bhsm8lprkzvrjgqr0klfkvr21als4-glibc-2.17/lib/libdl.so.2 (0x00007fa3085dc000)
	libc.so.6 => /nix/store/zm4bhsm8lprkzvrjgqr0klfkvr21als4-glibc-2.17/lib/libc.so.6 (0x00007fa30822c000)
	/nix/store/zm4bhsm8lprkzvrjgqr0klfkvr21als4-glibc-2.17/lib/ld-linux-x86-64.so.2 => /nix/store/pnd2kl27sag76h23wa5kl95a76n3k9i3-glibc-2.27/lib64/ld-linux-x86-64.so.2 (0x00007fa308d3b000)

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.80, NixOS, 19.09.976.c75de8bc12c (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jonringer** [comment] 2019-11-26 01:20
this looks to me like it's faililng to load dutch locales, I'm assuming that a --pure nix-shell probably has default locales, so it works.

**Comment by sagartewari01** [comment] 2019-11-26 21:46
I've just `en_US.UTF-8` enabled on my machine.

**Comment by doronbehar** [comment] 2020-08-04 21:18
I'm closing as the user is a ghost and we can't reproduce it.

**Closed by doronbehar** 2020-08-04 21:18 UTC
Labels: 0.kind: bug, 6.topic: vim
