### ISSUE TITLE
Gnome - Nixos [Newly installed software has wrong / temporary thumbnail]

### ISSUE THREAD

**Issue by KCynk** [NixOS/nixpkgs#239635] opened 2023-06-24 20:29 UTC
### Steps To Reproduce
1. Add `gnome.gnome-maps` to: 
    environment.systemPackages = with pkgs; [
        gnome.gnome-maps      
3. `sudo nixos-rebuild switch`
4. Wrong thumbnail appears in gnome activites sections also software is not visible inside gnome-shell-extensions applications menu.

### Expected behavior
After rebuild of the config new proper icon thumbnail should be present inside:
- gnome -> activites
- gnome-shell-extensions applications menu

### Screenshots
![Screenshot from 2023-06-24 22-22-23](https://github.com/NixOS/nixpkgs/assets/23100970/ae35e5e0-28e0-40ad-9559-91261bfd6be8)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
[nix@nixos:~/Downloads] nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.35, NixOS, 23.11 (Tapir), 23.11pre497285.3ae20aa58a6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

[nix@nixos:~/Downloads] gnome-shell --version
GNOME Shell 44.2
```

**Comment by roworu** [comment] 2023-06-25 11:29
I also had this, thumbnails usually appear after logout/reboot.

**Comment by jtojnar** [comment] 2024-05-04 23:11
Duplicate of https://github.com/NixOS/nixpkgs/issues/12757

**Closed by jtojnar** 2024-05-04 23:11 UTC
Labels: 0.kind: bug, 6.topic: GNOME
