### ISSUE TITLE
dockerTools.buildImage breaks with docker 1.12.1

### ISSUE THREAD

**Issue by gilligan** [NixOS/nixpkgs#19477] opened 2016-10-12 09:48 UTC
## Issue description

I just updated my server to 16.09 which introduced docker 1.12.1 - the same dockerTools that worked fine before now fails with: 

```
ApplyLayer duplicates of file paths not supported stdout: {"layerSize":310}
```
### Steps to reproduce

This is the hard part - my problem occurs in an internal project that I cannot share. I am merging several layers and this worked just fine before but now fails with the above error. 
## Technical details
- System: 16.09pre-git (Flounder)
- Nix version: 1.11.4
- Nixpkgs version: "15.09.505.7adab11"

---

\cc @lethalman can you have a look at this?

**Comment by gilligan** [comment] 2016-10-12 14:42
@NeQuissimus i am not really sure if this deserves the "good-first-bug" label but if it turns out to be an easy fix I would be glad. Personally I don't really know what the root cause is at all.

**Comment by domenkozar** [comment] 2016-10-24 09:44
Is this still an issue? Can we get a minimal working nix file to reproduce?

**Comment by gilligan** [comment] 2016-10-24 09:47
Sorry I wasn't able to reproduce it. I will assume for now that it is fixed.

**Comment by gilligan** [comment] 2016-11-03 16:08
I am seeing this exact same error again now. Sadly I still have no clue what triggers it since it works *most* of the time but sometimes fails with this error. 

Suggestions on how to debug this would be *very* welcome. Maybe @adnelson or @lethalman would have an idea how I could proceed?

**Comment by adnelson** [comment] 2016-11-03 16:55
Looking at [this issue](https://github.com/goldmann/docker-squash/issues/118) it looks like it could be that there are some duplicated paths amongst the layers... I don't know enough about how docker layers work to understand what to do here but maybe extracting the tarball and running `tar -tf` on some of the layers would elucidate a bit?

**Comment by gilligan** [comment] 2016-11-04 08:53
So I refactored my layer configuration somewhat because it wasn't ideal and the problem went away. Sadly that did not bring me closer to understanding the root cause. I would have to spend some more time to create a minimal reproducible example.

I do wonder if docker does indeed not support layers to have identical paths. If the paths are indeed identical meaning the files are identical then one would think that this shouldn't be a problem ...

**Comment by globin** [comment] 2017-03-15 08:18
I'll close this since we don't have a reproducible test case. If anyone manages to find one feel free to reopen this ticket or a new one.

**Closed by globin** 2017-03-15 08:18 UTC
Labels: 0.kind: bug, 9.needs: package (update), 9.needs: reporter feedback
