### ISSUE TITLE
nixos-unstable: console.font not applied; systemd-vconsole-setup fails

### ISSUE THREAD

**Issue by mebubo** [NixOS/nixpkgs#124170] opened 2021-05-23 16:27 UTC
**Describe the bug**

With recent nixos-unstable, the `console.font` setting does not seem to be applied: the font does not change during boot as it used to.

When I try to `systemctl restart systemd-vconsole-setup.service`, I get:

```
[...] systemd[1]: Starting Setup Virtual Console...
[...] systemd-vconsole-setup[1626]: sh: gzip: command not found
[...] systemd-vconsole-setup[1625]: setfont: ERROR setfont.c:58 do_loadfont: Bad character height 0
[...] systemd-vconsole-setup[1628]: sh: gzip: command not found
[...] systemd[1]: Finished Setup Virtual Console.
```
The breakage happened somewhere between 83d907fd760 and d42cd445dde.

**To Reproduce**
Build and boot nixos from a nixpkgs checkout at d42cd445dde or 900115a4f7f (the current nixos-unstable).

**Expected behavior**
The console font changes to the one defined by `console.font` (terminus by default) sometime at boot.

**Comment by mebubo** [comment] 2021-05-30 11:30
Remains broken in the same way as of latest nixos-unstable 540dccb2aeaffa9dc69bfdc41c55abd7ccc6baa3.

**Comment by oxalica** [comment] 2021-05-30 14:34
I believe it's caused by #119096 . @davidak 
The patch for path to `gzip` is removed in https://github.com/NixOS/nixpkgs/pull/119096/files#diff-9bf5ed26d6a5084e2a092ff8fb77ca5645fe4a9c07f666006b9a3a6dcd1340f3L41-L44
The original code is renamed to `src/libkbdfile/kbdfile.c` but still need to patch: https://github.com/legionus/kbd/blob/v2.4.0/src/libkbdfile/kbdfile.c#L23-L26

BTW: Another patch is also removed in that PR. It seems to make customization not possible. I'm also wondering why it's removed. https://github.com/NixOS/nixpkgs/blob/7cdc46f4e3cccd17b04ebe120a02e0906a91761f/pkgs/os-specific/linux/kbd/search-paths.patch

**Comment by davidak** [comment] 2021-06-03 18:32
This should be fixed with https://github.com/NixOS/nixpkgs/pull/124971. Please reopen if there is still an issue.

**Closed by davidak** 2021-06-03 18:32 UTC
Labels: 0.kind: bug, 6.topic: nixos

**Comment by AlexChalk** [comment] 2021-06-15 00:59
@davidak I'm seeing this issue in 21.05 (stable), can you help me understand if/when this change will end up there? I'm having a hard time understanding the docs on this: https://nixos.org/manual/nixpkgs/stable/#submitting-changes-commit-policy. Thanks for the fix!

**Comment by oxalica** [comment] 2021-06-15 05:21
@AlexChalk The patch is backported to 21.05 in #125143, but not yet in release channel `nixos-21.05` (maybe still need some time to build everything affected). You can monitor the status in this site: https://nixpk.gs/pr-tracker.html?pr=125143

**Comment by AlexChalk** [comment] 2021-06-18 12:08
Thanks @oxalica, your link says this is now available in `nixos-21.05`, but I'm still seeing the issue with my system after rebuilding. Does that make this worth reopening?

**Comment by mebubo** [comment] 2021-06-20 14:04
An update: this is still broken for me in nixos-unstable (as of 33d42ad7cf2769ce6364ed4e52afa8e9d1439d58), but fixed in nixos-21.05 (as of bad3ccd099ebe9a8aa017bda8500ab02787d90aa).

The fix https://github.com/NixOS/nixpkgs/pull/124971 still hasn't reached nixos-unstable or even master, but https://github.com/NixOS/nixpkgs/pull/125143 has reached nixos-21.05.

**Comment by AlexChalk** [comment] 2021-07-25 21:13
I'm using nixos-21.05 and this is still broken for me.

**Comment by AlexChalk** [comment] 2021-07-31 14:38
I managed to fix this by setting `console.earlySetup = true`.
