### ISSUE TITLE
Package request: Howdy

### ISSUE THREAD

**Issue by AidanV** [NixOS/nixpkgs#344024] opened 2024-09-23 18:53 UTC
**Project description**

Howdy provides Windows Hello™ style authentication for Linux. Use your built-in IR emitters and camera in combination with facial recognition to prove who you are.

Using the central authentication system (PAM), this works everywhere you would otherwise need your password: Login, lock screen, sudo, su, etc.

**Metadata**

* homepage URL: https://github.com/boltgolt/howdy
* source URL: https://github.com/boltgolt/howdy
* license: mit
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MatthewCash** [comment] 2024-09-23 20:10
See #216245

**Comment by SigmaSquadron** [comment] 2024-09-24 11:12
Duplicate of #76928

**Closed** 2024-09-24 11:12 UTC
Labels: 0.kind: packaging request
