### ISSUE TITLE
Bazel fails to execute in a project containing a .bazelversion file

### ISSUE THREAD

**Issue by aherrmann** [NixOS/nixpkgs#80950] opened 2020-02-24 11:37 UTC
**Describe the bug**
Bazel fails to execute in a project containing a `.bazelversion` file. Tools like [bazelisk](https://github.com/bazelbuild/bazelisk) or [Bazel's own wrapper script](https://github.com/bazelbuild/bazel/blob/df329ce6a11ff0dd0888722220c4f7f5d0d288c2/scripts/packages/bazel.sh) use this file to determine which Bazel version to use in a project.

**To Reproduce**
Execute the following steps:
```
$ touch WORKSPACE
$ echo 2.0.0 >.bazelversion
$ nix run -f channel:nixpkgs-unstable bazel -c bazel version
```
This should produce the following error message
```
ERROR: The project you're trying to build requires Bazel 2.0.0 (specified in .../.bazelversion), but it wasn't found in /nix/store/j2j42fq57shn9cr3ww9liz37dyj1f7mm-bazel-2.0.0/bin.

Bazel binaries for all official releases can be downloaded from here:
  https://github.com/bazelbuild/bazel/releases

Please put the downloaded Bazel binary into this location:
  /nix/store/j2j42fq57shn9cr3ww9liz37dyj1f7mm-bazel-2.0.0/bin/bazel-2.0.0-linux-x86_64
```

**Expected behavior**
Bazel should successfully print its version information, e.g.
```
Starting local Bazel server and connecting to it...
Build label: 2.0.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 1 00:00:00 1980 (315532800)
Build timestamp: 315532800
Build timestamp as int: 315532800
```

**Additional context**
Bazel comes with a [wrapper script](https://github.com/bazelbuild/bazel/blob/df329ce6a11ff0dd0888722220c4f7f5d0d288c2/scripts/packages/bazel.sh) that can switch between multiple installed Bazel versions depending on the execution environment (`.bazelversion` or `$USE_BAZEL_VERSION`). Nixpkgs installs that wrapper script as the `bazel` binary, the actual Bazel binary is installed as `bazel-real`. See https://github.com/NixOS/nixpkgs/pull/49799 (cc @Profpatsch @andyscott @mboes).

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.0-40-generic, Ubuntu, 19.10 (Eoan Ermine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(aj): `"nixpkgs-20.09pre214374.1fe82110feb"`
 - nixpkgs: `/home/aj/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: bazel
# a list of nixos modules affected by the problem
module:
```

**Comment by Profpatsch** [comment] 2020-02-24 12:40
What do you suggest we do here? Remove the check? Or how does it check for which version it is? `bazel info` correctly shows `Build label: 2.0.0- (@non-git)`, so why is it not working? Because of the dash at the end of the version number?

**Comment by aherrmann** [comment] 2020-02-24 14:11
@Profpatsch The `-` seems to be the issue. The wrapper [applies `cut -d' ' -f2`](https://github.com/bazelbuild/bazel/blob/df329ce6a11ff0dd0888722220c4f7f5d0d288c2/scripts/packages/bazel.sh#L158-L167) to `bazel --version` which produces e.g. `2.0.0-` under nixpkgs. Note, looking for `bazel-real` is the fallback if no `bazel-<version>` is found. [This comment](https://github.com/bazelbuild/bazel/blob/df329ce6a11ff0dd0888722220c4f7f5d0d288c2/scripts/packages/bazel.sh#L19-L40) in the wrapper script explains the details. We could patch the wrapper script, another workaround may be to create a symlink `bazel-<version>` next to the wrapper that points to `bazel-real`.

**Comment by seh** [comment] 2023-06-24 14:44
I find that this problem persists today when I have a _.bazelversion_ file dominated by a _WORKSPACE.bazel_ file. Invoking _bazelisk_ instead of _bazel_ works, but that's not supposed to be necessary.

**Comment by avdv** [comment] 2023-11-28 09:56
This seems to work fine at least for `bazel_6` and `bazel_5` now:
```console
$ cat .bazelversion 
6.2.0
$ nix run nixpkgs#bazel_6 -- version
Starting local Bazel server and connecting to it...
Build label: 6.2.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 1 00:00:00 1980 (315532800)
Build timestamp: 315532800
Build timestamp as int: 315532800
$ nix run nixpkgs#bazel_5 -- version
ERROR: The project you're trying to build requires Bazel 6.2.0 (specified in /home/claudio/source/rules_haskell/.bazelversion), but it wasn't found in /nix/store/77y5mfzf6zp39zg9byz7vxw8nrv6rn50-bazel-5.4.1/bin.

Bazel binaries for all official releases can be downloaded from here:
  https://github.com/bazelbuild/bazel/releases

Please put the downloaded Bazel binary into this location:
  /nix/store/77y5mfzf6zp39zg9byz7vxw8nrv6rn50-bazel-5.4.1/bin/bazel-6.2.0-linux-x86_64
$ echo 5.4.1 > .bazelversion 
$ nix run nixpkgs#bazel_5 -- version
WARNING: Running Bazel server needs to be killed, because the startup options are different.
Starting local Bazel server and connecting to it...
Build label: 5.4.1- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 1 00:00:00 1980 (315532800)
Build timestamp: 315532800
Build timestamp as int: 315532800
```

**Comment by seh** [comment] 2023-11-28 14:32
That's promising news, Claudio. Do you know of anything that changed that would have led to this working now when it didn't before?

**Comment by avdv** [comment] 2023-11-28 15:41
> That's promising news, Claudio. Do you know of anything that changed that would have led to this working now when it didn't before?

No, I don't know. AFAICS, the wrapper script is looking for an executable `bazel-${bazel_version}-${os_arch_suffix}` inside of the scripts' directory. As soon as that exists, no further version checking (ie. no `bazel --version` call) is done.

Can you still reproduce this issue?

**Comment by seh** [comment] 2023-11-28 16:49
> Can you still reproduce this issue?

Yes, I can:
```
% echo '6.3.2' > .bazelversion
% bazel build //...
ERROR: The project you're trying to build requires Bazel 6.3.2 (specified in /Users/seh/src/my/project/.bazelversion), but it wasn't found in /nix/store/0la06hhgwh7jqv0yia7nss2r6znr1qyk-bazel-6.4.0/bin.

Bazel binaries for all official releases can be downloaded from here:
  https://github.com/bazelbuild/bazel/releases

Please put the downloaded Bazel binary into this location:
  /nix/store/0la06hhgwh7jqv0yia7nss2r6znr1qyk-bazel-6.4.0/bin/bazel-6.3.2-darwin-arm64
```
If instead I write "6.4.0" into the _.bazelversion_ file it works, because that version is already present in Nix's store.

Note that I'm using the "bazel" Nix package, and not the "bazel_6" package as [you had shown](https://github.com/NixOS/nixpkgs/issues/80950#issuecomment-1829473680). You also used _nix run_, as opposed to invoking the _bazel_ program directly.

**Comment by avdv** [comment] 2023-11-29 06:51
@seh You seem to expect that the wrapper script downloads the version you specify in the `.bazelversion` file or somehow makes it available automatically. That is not how this is supposed to work, you should use bazelisk for that.

> If instead I write "6.4.0" into the _.bazelversion_ file it works, because that version is already present in Nix's store.

Yes, so this works as designed. The original problem was that the script reported an error even when the versions matched.

The script does only support multiple versions if you install all versions side-by-side into the wrapper script's folder. This is never going to work for nixpkgs, as each package is living in a separate folder in the nix store (and we only have a single package for each major version anyway):
> ```
> # This wrapper only recognizes Bazel versions installed next to itself, thus
> # if you install this wrapper as /usr/bin/bazel, you'll have to install binaries
> # for individual Bazel binaries as e.g. /usr/bin/bazel-1.0.0.
> ```

**Comment by seh** [comment] 2023-11-29 13:03
I confess that I've been using Bazel as installed via Homebrew on macOS for many years before starting to use Nix this year. When one installs _bazelisk_ with Homebrew, [it sets up a symbolic link from the _bazel_ file to the _bazelisk_ file](https://github.com/Homebrew/homebrew-core/blob/3a8825306d1f7a20e24fc12ac8f89193c2c85ce8/Formula/b/bazelisk.rb#L32). Invoking _bazel_ in that way is really invoking _bazelisk_, which takes care of downloading Bazel versions as you noted.

What I don't understand yet is why _bazelisk_ respects a _.bazeliskrc_ file, but it does not read the _.bazelversion_ file. Perhaps it's sensitive to the name with which it was invoked, and decides that way which of these two control files it should read.

I'd like to use _bazelisk_ with Nix in a similar way, such that it _replaces_ the _bazel_ executable file. Do you recall there ever being discussion as to whether the _bazelisk_ Nix package should offer the option to behave like the Homebrew package?

**Comment by seh** [comment] 2023-11-29 13:07
> What I don't understand yet is why _bazelisk_ respects a _.bazeliskrc_ file, but it does not read the _.bazelversion_ file. Perhaps it's sensitive to the name with which it was invoked, and decides that way which of these two control files it should read.

Answering my own question, per [the _bazelisk_ documentation](https://github.com/bazelbuild/bazelisk/blob/82dba8f3ae272d24a6597442d665923b0735b509/README.md?plain=1#L44-L52), if a _.bazeliskrc_ file is present, _bazelisk_ will read that before it will read a sibling _.bazelversion_ file.

**Comment by avdv** [comment] 2023-11-29 13:21
> I'd like to use _bazelisk_ with Nix in a similar way, such that it _replaces_ the _bazel_ executable file. Do you recall there ever being discussion as to whether the _bazelisk_ Nix package should offer the option to behave like the Homebrew package?

No, I don't remember any discussion around this. I mean, on one hand if you manage the Bazel version with nix (e.g. in a `shell.nix`) you don't need bazelisk at all.

On the other hand, nix is flexible and you can define an ad-hoc package yourself, e.g. `nix-shell -p "(writeScriptBin ''bazel'' ''exec \${bazelisk}/bin/bazelisk \"\$@\"'')"` drops you into a nix shell where `bazel` calls `bazelisk`. You could add this to your `shell.nix` or to your nix profile to make it available project locally or globally for your user.

**Comment by seh** [comment] 2023-11-29 15:21
I appreciate your point that if we're using Nix already, we could use it to choose the Bazel version directly. However, I don't know how to do that. I see that there are both "bazel_5" and "bazel_6" packages, per your earlier example (though _search.nixos.org_ doesn't find them). Is there a technique to specify the exact version down to the patch release number?

That _nix-shell_ invocation is very nice, too. Thank you for that.

**Comment by avdv** [comment] 2023-11-29 16:31
> I appreciate your point that if we're using Nix already, we could use it to choose the Bazel version directly. However, I don't know how to do that. I see that there are both "bazel_5" and "bazel_6" packages, per your earlier example (though _search.nixos.org_ doesn't find them).
If you search for "bazel" you find `bazel_4`, `bazel_5` and `bazel` (`bazel_6` probably not being shown because bazel is a shorter name for the same thing), see https://search.nixos.org/packages?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=bazel

> Is there a technique to specify the exact version down to the patch release number?

Not directly. There is only one package per major version. But there is another dimension to this; meaning if you use a specific nixpkgs commit (via pinning / flake lock) or channel you can choose a specific Bazel version -- as long as this version made its way into the nixpkgs collection. For example `bazel_6` is at version 6.2.0 in nixos-23.05 but at version 6.4.0 in nixos-unstable right now.

**Comment by avdv** [comment] 2024-01-02 08:23
Closing, as this seems to work fine.

**Closed by avdv** 2024-01-02 08:23 UTC
Labels: 0.kind: bug
