### ISSUE TITLE
tmux-2.6 missing manpage

### ISSUE THREAD

**Issue by kballard** [NixOS/nixpkgs#35242] opened 2018-02-20 20:51 UTC
## Issue description
I have tmux-2.6 installed via Nix and it doesn't have any manpages. `~/.nix-profile/share/man/man1` includes manpages for 2 other Nix-installed tools but doesn't have a manpage for tmux.

### Steps to reproduce
I ran `nix-env -i tmux`.

## Technical details

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 16.7.0, macOS 10.12.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixpkgs-18.03pre122433.8a7b2f889dd"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by FRidh** [comment] 2018-02-20 21:25
Closing as duplicate of https://github.com/NixOS/nixpkgs/issues/24717. Also related is https://github.com/NixOS/nixpkgs/issues/25483.

**Closed by FRidh** 2018-02-20 21:25 UTC
