### ISSUE TITLE
Can't build facetimehd-firmware

### ISSUE THREAD

**Issue by lovesegfault** [NixOS/nixpkgs#72064] opened 2019-10-27 05:48 UTC
**Describe the bug**
Upon trying `nixos-rebuild switch --upgrade` I get:
```
builder for '/nix/store/55p8yxb2xsbw067xd4bmxp7gc1id8dfw-osxupd10.11.5.dmg.drv' failed with exit code 1
cannot build derivation '/nix/store/3xn8vykqpsl1wijindxz8677djyc2hh1-facetimehd-firmware-1.43_4.drv': 1 dependencies couldn't be built
```
I can reproduce it with `nix-shell`:
```
bemeurer@aurora> nix-shell -p facetimehd-firmware                                                                                                                                                                                         ~
warning: 'https://standard.cachix.org' does not appear to be a binary cache
these derivations will be built:
  /nix/store/55p8yxb2xsbw067xd4bmxp7gc1id8dfw-osxupd10.11.5.dmg.drv
  /nix/store/m011v5jsmcnfjlblif0zfaxd020l8nbz-unpack.drv
  /nix/store/3xn8vykqpsl1wijindxz8677djyc2hh1-facetimehd-firmware-1.43_4.drv
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/s1xmwhxdszbcngf5lwl7263ynbv089z4-bash-interactive-4.4-p23-dev
copying path '/nix/store/s1xmwhxdszbcngf5lwl7263ynbv089z4-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
building '/nix/store/m011v5jsmcnfjlblif0zfaxd020l8nbz-unpack.drv'...
building '/nix/store/55p8yxb2xsbw067xd4bmxp7gc1id8dfw-osxupd10.11.5.dmg.drv'...

trying https://support.apple.com/downloads/DL1877/en_US/osxupd10.11.5.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download osxupd10.11.5.dmg from any mirror
builder for '/nix/store/55p8yxb2xsbw067xd4bmxp7gc1id8dfw-osxupd10.11.5.dmg.drv' failed with exit code 1
cannot build derivation '/nix/store/3xn8vykqpsl1wijindxz8677djyc2hh1-facetimehd-firmware-1.43_4.drv': 1 dependencies couldn't be built
error: build of '/nix/store/3xn8vykqpsl1wijindxz8677djyc2hh1-facetimehd-firmware-1.43_4.drv' failed
```

**To Reproduce**
1. `nix-shell -p facetimehd-firmware`

**Expected behavior**
The package builds

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.7, NixOS, 19.09.891.80b42e630b2 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.941.27a5ddcf747"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
attribute: facetimehd-firmware
```

**Comment by veprbl** [comment] 2019-10-27 06:48
Duplicate of #71952

**Closed by veprbl** 2019-10-27 06:48 UTC
Labels: 0.kind: bug
