### ISSUE TITLE
Windscribe VPN CLI

### ISSUE THREAD

**Issue by williameast** [NixOS/nixpkgs#214732] opened 2023-02-05 11:09 UTC
**Windscribe CLI**
_the CLI  client for the Windscribe VPN service_

* homepage URL: https://windscribe.net/guides/linux
* source URL: https://github.com/Windscribe/Desktop-App
* license: mit, bsd, gpl2+ , ... gpl2
* platforms: unix, linux, darwin, ... linux

**Comment by pluiedev** [comment] 2024-06-09 21:29
Duplicate of #158368

**Closed by pluiedev** 2024-06-09 21:29 UTC
Labels: 0.kind: packaging request
