### ISSUE TITLE
patch-shebangs.sh should not use inputs from nativeBuildInputs

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#42801] opened 2018-06-30 03:14 UTC
## Issue description
Running into this with git. Basically we don't want nativeBuildInputs to wind up in the closure. Git uses Perl as a native build input but it will wind up in the closure even when perlSupport is false.

**Comment by dezgeg** [comment] 2018-06-30 09:52
Well, not always. See https://github.com/NixOS/nixpkgs/issues/33956 for discussion.

Closing as a duplicate of that.

**Closed by dezgeg** 2018-06-30 09:52 UTC
