### ISSUE TITLE
Package request: thorium

### ISSUE THREAD

**Issue by hexisXz** [NixOS/nixpkgs#262113] opened 2023-10-19 17:08 UTC
The kinda new Browser (thorium) is pretty cool and in a pretty good state. I have been using it for a week now and haven't had any bugs and it's pretty fast. so I was pretty bummed when i found out it's not in the nix repos and I have no idea how to make a nix package.. i have read everything and I feel like an idiot. That's why i am making this request. i have never done this before so if it helps i have the repo here: https://github.com/Alex313031/thorium

**Comment by eclairevoyant** [comment] 2023-10-19 18:51
duplicate of #184823

**Closed by eclairevoyant** 2023-10-19 18:51 UTC
Labels: 0.kind: packaging request
