### ISSUE TITLE
 python3Full.withPackages (ps: [ps.virtualenv]) no longer builds

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#114475] opened 2021-02-26 15:58 UTC
Python `withPackages` environments can no longer include `virtualenv` (and a whole lot of other packages). The command

> nix-build --no-out-link -E 'with (import <nixpkgs> {}); python3Full.withPackages (ps: [ps.virtualenv])' 

fails to build in current versions of `master` because of the following error:

~~~
[...]
Found duplicated packages in closure for dependency 'py':
  py 1.9.0 (/nix/store/rng1bjykyyn9szqkjqp9l2cy4hflwkzy-python3.8-py-1.9.0/lib/python3.8/site-packages)
  py 1.9.0 (/nix/store/scxn78yv6fgcjkxc3rxv5xbyrmh8bwin-python3.8-py-1.9.0/lib/python3.8/site-packages)
Found duplicated packages in closure for dependency 'toml':
  toml 0.10.2 (/nix/store/5z2vm93qapr07m3zwy0xyb3csndray1i-python3.8-toml-0.10.2/lib/python3.8/site-packages)
  toml 0.10.2 (/nix/store/wq9j40q3zc9fps1pmm0xc89dk2wid5jw-python3.8-toml-0.10.2/lib/python3.8/site-packages)
Found duplicated packages in closure for dependency 'wcwidth':
  wcwidth 0.2.5 (/nix/store/47g8s5nhlv956yhpgyanqi5ybbmvk5jf-python3.8-wcwidth-0.2.5/lib/python3.8/site-packages)
  wcwidth 0.2.5 (/nix/store/xk5h4z2ggf38bvj7344qqjv8kbbh1a7i-python3.8-wcwidth-0.2.5/lib/python3.8/site-packages)

Package duplicates found in closure, see above. Usually this happens if two packages depend on different version of the same dependency.
~~~

According to `git bisect`, that issue was introduced in e975b7508269b2f487ffd4a2ecc0aded28ce0ec3 by @fabaff. I'm not sure whether it is really the cause of that issue, though, because I tried reverting it and that did not seem to fix the build.

**Comment by FRidh** [comment] 2021-02-27 07:56
Yikes, these type of errors are bad. Turns out it was a regression from improving cross-compilation support https://github.com/NixOS/nixpkgs/pull/114538.

**Comment by FRidh** [comment] 2021-02-27 10:12
Fixed with https://github.com/NixOS/nixpkgs/pull/114538

**Closed by FRidh** 2021-02-27 10:12 UTC
Labels: 0.kind: regression, 6.topic: python
