### ISSUE TITLE
Package request: windscribe

### ISSUE THREAD

**Issue by johanno** [NixOS/nixpkgs#317025] opened 2024-06-03 21:04 UTC
**Project description**

I would love to have the windscribe desktop app on nixos.

I already tried to do it myself, but I hit several road blocks.
https://github.com/NixOS/nixpkgs/compare/master...johanno:nixpkgs:windscribe_pkg

**Metadata**

* homepage URL: https://windscribe.com/
* source URL: https://github.com/Windscribe/Desktop-App
* license:  gpl2
* platforms: linux, ubuntu, arch, fedora, mac, windows

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pluiedev** [comment] 2024-06-09 21:29
Duplicate of #158368.

**Closed by pluiedev** 2024-06-09 21:29 UTC
Labels: 0.kind: packaging request

**Comment by ParkerrDev** [comment] 2024-11-10 21:20
I've created a repo if anyone would like to contribute: https://github.com/ParkerrDev/nixpkgs-windscribe/
