### ISSUE TITLE
calibre breaks kde 5 on unstable

### ISSUE THREAD

**Issue by yochai** [NixOS/nixpkgs#16278] opened 2016-06-16 20:18 UTC
## Issue description
Installing calibre breaks kde 5, after installing the program I wasn't able to login with sddm and kde 5.

### Steps to reproduce
Add calibre to the config file, rebuild, try to login with kde 5.

## Technical details
Using NixOS, 16.09.git.66964a5.

Kde was built against 5.6.1 and calibre pulls in qt55, will that be the reason ?

**Comment by bennofs** [comment] 2016-06-17 09:59
Thank you for the report! :) 

Can you explain what exactly you mean with "I wasn't able to login"? What exactly did you see when you tried it? Just a black screen and then back to login screen again?

**Comment by yochai** [comment] 2016-06-17 10:11
Sorry for not being clearer, entered user password on sddm, clicked on login.
The password area will turn gray (as in, disabled), and sddm will stop responding.

Waiting led to no changes, but going to tty and back again gave me a black screen with a working pointer. I had nothing to click on.
kwin (?) keyboard events was not handled (alt+f2 for example).

The solution was to restart the display manager. (systemctl restart display-manager).

I found the following line in the log, which shows that sddm is trying to load kde and it crashes:
``xsession[7207]: *** Error in `/nix/store/5g18bmszqcxlp0lhs6iyfffxcyxmrngh-plasma-workspace-5.6.4/bin/ksplashqml': malloc(): memory corruption: 0x000000000124e420 ***``

Removing 'calibre' and rebuilding solved the problem, adding 'calibre' again and rebuilding reintroduced the problem.
Removing cache folders made no difference.

**Comment by peterhoeg** [comment] 2016-07-22 10:12
This is a duplicate of #15498.

**Comment by ttuegel** [comment] 2016-08-30 15:22
> This is a duplicate of #15498.

Then it is fixed in master! :smile:

**Closed by ttuegel** 2016-08-30 15:22 UTC
Labels: 0.kind: bug, 6.topic: qt/kde

**Comment by puffnfresh** [comment] 2016-10-22 12:32
I have this problem on master. I even tried a Docker image containing the closure and could reproduce the problem.
