### ISSUE TITLE
Build failure: vmware-workstation

### ISSUE THREAD

**Issue by yswtrue** [NixOS/nixpkgs#223523] opened 2023-03-28 07:59 UTC
### Steps To Reproduce

```
  virtualisation = {
    vmware = {
      host.enable = true;
      host.package = pkgs.vmware-workstation.override { enableMacOSGuests = true; };
    };
  }

```

### Build log

```
error: builder for '/nix/store/pjhjib32y3id5zczwnkbqwww1a86hq0h-vmware-workstation-17.0.0.drv' failed with exit code 1;
       last 10 log lines:
       > searching for dependencies of /nix/store/8x0n164qxfc11p5b2fb6nhx8byqkv127-vmware-workstation-17.0.0/bin/vmnet-netifup
       > auto-patchelf: 3 dependencies could not be satisfied
       > error: auto-patchelf could not satisfy dependency libcrypt.so.1 wanted by /nix/store/8x0n164qxfc11p5b2fb6nhx8byqkv127-vmware-workstation-17.0.0/lib/vmware-ovftool/libvmacore.so
       > error: auto-patchelf could not satisfy dependency libcrypt.so.1 wanted by /nix/store/8x0n164qxfc11p5b2fb6nhx8byqkv127-vmware-workstation-17.0.0/lib/vmware-vix/Workstation-17.0.0/64bit/libvix.so
       > error: auto-patchelf could not satisfy dependency libcrypt.so.1 wanted by /nix/store/8x0n164qxfc11p5b2fb6nhx8byqkv127-vmware-workstation-17.0.0/bin/vmware-authd
       > auto-patchelf failed to find all the required dependencies.
       > Add the missing dependencies to --libs or use `--ignore-missing="foo.so.1 bar.so etc.so"`.
       > /nix/store/sw36plhp82916wwg6i6097rkzza7d950-stdenv-linux/setup: line 79: pop_var_context: head of shell_variables not a function context
       > /nix/store/sw36plhp82916wwg6i6097rkzza7d950-stdenv-linux/setup: line 1457: pop_var_context: head of shell_variables not a function context
       > /nix/store/sw36plhp82916wwg6i6097rkzza7d950-stdenv-linux/setup: line 1594: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/pjhjib32y3id5zczwnkbqwww1a86hq0h-vmware-workstation-17.0.0.drv'.
(use '--show-trace' to show detailed location information)
```

### Notify maintainers

@cawilliamson @deinferno 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.8, NixOS, 23.05 (Stoat), 23.05.20230324.a64e169`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/store/yrm0pxss7blbv6fnbq0i30dpjzlcnmz5-source`

```

**Comment by wegank** [comment] 2023-03-28 08:39
Duplicate of #223476.

**Closed by wegank** 2023-03-28 08:39 UTC
Labels: 0.kind: build failure
