### ISSUE TITLE
R and OpenBLAS not buildable on MacOS X

### ISSUE THREAD

**Issue by YPares** [NixOS/nixpkgs#10834] opened 2015-11-05 11:17 UTC
Due to the error exposed in https://github.com/xianyi/OpenBLAS/issues/332 , OpenBLAS (and therefore R) cannot be installed.
However this error has been fixed before OpenBLAS v0.2.14 release (which is the one currently in NixPkgs).

**Comment by peti** [comment] 2015-11-05 11:35
I don't quite follow. You're saying there is an error in OpenBLAS that breaks the build on Darwin. But you also seem to say that this error is not present any more in the version of OpenBLAS shipped by Nixpkgs. Don't these two statement contradict each other?

Anyway, work on fixing R for Darwin is well underway in https://github.com/NixOS/nixpkgs/pull/10623.

**Comment by YPares** [comment] 2015-11-05 12:00
Yes, that's exactly what's puzzling me.
OpenBLAS v0.2.15 builds under MacOS X, but I have to check it out and make it manually. Just overriding the derivation ends up with build errors:
```
Undefined symbols for architecture x86_64:
  "_gotoblas_dynamic_init", referenced from:
      _blas_memory_alloc in libopenblas_haswellp-r0.2.15.a(memory.o)
      _gotoblas_init in libopenblas_haswellp-r0.2.15.a(memory.o)
  "_gotoblas_dynamic_quit", referenced from:
      _gotoblas_quit in libopenblas_haswellp-r0.2.15.a(memory.o)
```

I used this code to override:
```
with (import <nixpkgs> {});
lib.overrideDerivation openblas (attrs: {
    name = "openblas-0.2.15";
    src = fetchFromGitHub {
        owner="xianyi";
        repo="OpenBLAS";
        rev="v0.2.15";
        sha256="16f4al6q81dk9icw89nsymjqw4yf63cchll3jbiyv4pcfn7403mw";
    };
})

**Comment by vcunat** [comment] 2015-11-05 12:24
The failure is reported to be Haswell-specific, so some will be getting it and some won't, until we pull that update (/cc maintainer @ttuegel).

**Comment by YPares** [comment] 2015-11-05 13:39
I retried the build and I'm getting errors which don't seem to be haswell-specific:
```
Undefined symbols for architecture x86_64:
  "__gfortran_concat_string", referenced from:
      _sgesvd_ in libopenblasp-r0.2.15.a(sgesvd.o)
      _shseqr_ in libopenblasp-r0.2.15.a(shseqr.o)
      _sormbr_ in libopenblasp-r0.2.15.a(sormbr.o)
      _sormhr_ in libopenblasp-r0.2.15.a(sormhr.o)
      _sormlq_ in libopenblasp-r0.2.15.a(sormlq.o)
      _sormql_ in libopenblasp-r0.2.15.a(sormql.o)
      _sormqr_ in libopenblasp-r0.2.15.a(sormqr.o)
      ...
  "__gfortran_etime", referenced from:
      _second_ in libopenblasp-r0.2.15.a(second_INT_ETIME.o)
      _dsecnd_ in libopenblasp-r0.2.15.a(dsecnd_INT_ETIME.o)
  "__gfortran_pow_r4_i8", referenced from:
      _sggbal_ in libopenblasp-r0.2.15.a(sggbal.o)
      _sgeequb_ in libopenblasp-r0.2.15.a(sgeequb.o)
      _ssyequb_ in libopenblasp-r0.2.15.a(ssyequb.o)
      _spoequb_ in libopenblasp-r0.2.15.a(spoequb.o)
      _sgbequb_ in libopenblasp-r0.2.15.a(sgbequb.o)
      _cggbal_ in libopenblasp-r0.2.15.a(cggbal.o)
      _clargv_ in libopenblasp-r0.2.15.a(clargv.o)
```

**Comment by ttuegel** [comment] 2015-11-05 16:06
@YPares The OpenBLAS issue you referenced is not the cause of the error here. That issue is about a failure of compile-time CPU detection, but we use dynamic architecture detection so there is no CPU detection at compile-time.

It looks like there is some problem with gfortran, maybe because we're using clang? I don't have access to a Darwin machine, so I can't test this, unfortunately.

**Comment by YPares** [comment] 2015-11-05 16:29
Yes, both issues are separate, but the first was fixed by trying to upgrade to v0.2.15.
Hence the second issue.
Actually, running manually unpackPhase/configurePhase/buildPhase in a
`nix-shell myOpenBLASOverride.nix` (code shown hereabove)
works as long as the nix-shell is not pure.

**Comment by YPares** [comment] 2015-11-06 08:22
Apparently I was wrong, it seems to come from the differences in PATH: Lauching a non-pure shell and setting the PATH like it is set in a pure shell makes it fail too when I call `buildPhase`. So it's something on my machine (a very fresh install of OS X El Capitan) that needs to be accessed so the build succeeds.
Although, the error didn't look like a missing executable...

**Comment by YPares** [comment] 2015-11-06 11:06
Ok, we found it!
It's the Makefile of OpenBLAS that supposes the command `which` exists, when it calls `which gfortran`. But on OSX (contrary to Linux) which is not automatically in the dependencies.

**Comment by YPares** [comment] 2015-11-07 10:20
Ok, it's actually more complicated. Apparently, on some shells `which` is a *builtin command* and for others a binary on the PATH (OSX notably).
What's weird is that this divergence also appears in the Linux ecosystem: some of my colleagues with `bash` on NixOS have it as a builtin command, and for others with `bash` on Ubuntu it's a regular binary.

The problem is that I suppose `nix-shell` is unable to ensure that kind of thing? (I.e by default deprive a pure shell of this kind of constructs, to be sure they are listed in the dependencies of the derivation)

**Comment by ttuegel** [comment] 2015-11-07 16:46
> Ok, we found it!
> It's the Makefile of OpenBLAS that supposes the command which exists, when it calls which gfortran. But on OSX (contrary to Linux) which is not transitively in the dependencies.

I cannot find any reference to `which` in the Makefile. Could you show me where this is the case? The package should be patched to use the absolute path to `gfortran` anyway, instead of calling `which`.

**Comment by ttuegel** [comment] 2015-11-07 17:57
Oh, I found it. The `f_check` Perl script uses `which` to make sure the Fortran compiler is available. I think I'll just add `which` to `nativeBuildInputs` on all platforms, for consistency.

**Comment by ttuegel** [comment] 2015-11-07 20:01
Fixed in 9a2d5cb.

**Closed by ttuegel** 2015-11-07 20:01 UTC
Labels: bug, darwin

**Comment by YPares** [comment] 2015-11-13 09:37
@ttuegel Thanks! This part of R build passes. However I've got another problem when going further in the build. R configure phase fails with:
```these derivations will be built:
  /nix/store/kf7acrwhkg8bcw3v6xypxysc8f6qvbpp-R-3.2.2.drv
[...]
checking for ICU... no
checking for ucol_open in -licucore... no
configure: error: library 'icucore' is required for ICU
builder for ‘/nix/store/kf7acrwhkg8bcw3v6xypxysc8f6qvbpp-R-3.2.2.drv’ failed with exit code 1```

**Comment by YPares** [comment] 2015-11-13 10:59
OK, and there's also another problem with X. It's enabled by default, which of course is problematic on OSX.
So I've overriden R derivation so it's configured with:
```
      --with-ICU=no
      --with-x=no
```
Build then it fails when building with:
```
make[3]: Entering directory '/private/var/folders/1t/88tpkbl51430cb1mzy3tx92w0000gn/T/nix-build-R-3.2.2.drv-1/R-3.2.2/src/unix'
/nix/store/k1fixzniy03pwdkqj5a7hv5rr0mzl12s-gfortran-5.1.0/bin/gcc -I. -I../../src/include -I../../src/include   -DHAVE_CONFIG_H   -fopenmp -fPIC  -g -O2  -c Rembedded.c -o Rembedded.o
/nix/store/k1fixzniy03pwdkqj5a7hv5rr0mzl12s-gfortran-5.1.0/bin/gcc -I. -I../../src/include -I../../src/include   -DHAVE_CONFIG_H   -fopenmp -fPIC  -g -O2  -c dynload.c -o dynload.o
/nix/store/k1fixzniy03pwdkqj5a7hv5rr0mzl12s-gfortran-5.1.0/bin/gcc -I. -I../../src/include -I../../src/include   -DHAVE_CONFIG_H   -fopenmp -fPIC  -g -O2  -c system.c -o system.o
/nix/store/k1fixzniy03pwdkqj5a7hv5rr0mzl12s-gfortran-5.1.0/bin/gcc -I. -I../../src/include -I../../src/include   -DHAVE_CONFIG_H   -fopenmp -fPIC  -g -O2  -c sys-unix.c -o sys-unix.o
/nix/store/k1fixzniy03pwdkqj5a7hv5rr0mzl12s-gfortran-5.1.0/bin/gcc -I. -I../../src/include -I../../src/include   -DHAVE_CONFIG_H   -fopenmp -fPIC  -g -O2  -c sys-std.c -o sys-std.o
/nix/store/k1fixzniy03pwdkqj5a7hv5rr0mzl12s-gfortran-5.1.0/bin/gcc -I. -I../../src/include -I../../src/include   -DHAVE_CONFIG_H   -fopenmp -fPIC  -g -O2  -c X11.c -o X11.o
sys-std.c: In function 'Rstd_ReadConsole':
sys-std.c:900:6: error: 'rl_readline_name' undeclared (first use in this function)
      rl_readline_name = "R";
```
