### ISSUE TITLE
Build failure: vimPlugins.rustaceanvim due to Lua module dependency dkjson hash mismatch. 

### ISSUE THREAD

**Issue by HippieMitch** [NixOS/nixpkgs#334393] opened 2024-08-13 14:03 UTC
### Steps To Reproduce

Steps to reproduce the behavior (on a flake-based system):
1. Switch to the nixos-unstable branch.
1. Add pkgs.vimPlugins.rustaceanvim to NixOS configuration.
1. Update flake.lock file for nixos-unstable.
2. Perform a nixos-rebuild switch.

### Build log

```
 dkjson-2.8.tar.gz failed with hash mismatch after ⏱ 0s

┏━ 1 Errors:
┃ error: hash mismatch in fixed-output derivation '/nix/store/jl63hzr355zarhjlr50v887giyq8062n-dkjson-2.8.tar.g…
┃          specified: sha256-CfpgoEECteMiqwa51Zt6oPKcChnHVCFfikHzoWT5SUs=
┃             got:    sha256-JOjNO+uRwchh63uz+8m9QYu/+a1KpdBHGBYlgjajFTI=
```

### Extra Info
The issue appears to be from the dkjson lua module dependency and may be affecting other packages.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.4-cachyos, NixOS, 24.11 (Vicuna), 24.11.20240811.a58bc8a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/h60m1fwahjd2mv6gsg77ji3vb4gpj4dk-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Thiago-Assis-T** [comment] 2024-08-13 14:29
Can confirm, dkjson package has got a hash mismatch...

**Comment by Thiago-Assis-T** [comment] 2024-08-13 14:42
A few suggestions to make the issue clearer: 
1. the title, I understand that you are trying to build rustacenvim, but the issue is with a dependency (namely: dkjson) so much so, that for me it broke building luacheck. So changing the issue's title may be pertinent to convey a clear image of the issue...
2. are you on 24.11 really? I am on unstable and having that issue... so perhaps you are using flakes and `[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"` doesn't really capture that, so say it in the issue for it to be clearer. 
3. I don't think your steps to reproduce are correct... perhaps something like:
   1. change to unstable channel 
   2. run `nix build nixpkgs#brokenPackage` ?

**Comment by dotlambda** [comment] 2024-08-13 17:23
fixed by https://github.com/NixOS/nixpkgs/pull/333779

**Closed by dotlambda** 2024-08-13 17:23 UTC
Labels: 0.kind: build failure
