### ISSUE TITLE
nixos-rebuild failed with systemd-boot

### ISSUE THREAD

**Issue by Vonfry** [NixOS/nixpkgs#151177] opened 2021-12-18 11:21 UTC
### Describe the bug
The system is *not* a fresh installed one. Before I reboot today, it can be rebuilt.

nixpkgs rev:
- previous: `6961edfe6be910db4f7cf5decfafcb29c89201e2`
- current: `928abb47df583359555891c00d20edcb42680e0a`

If rolling back to 11.30 which is possible on previous rev, the error is still existed.

Some configure with `boot.loader.systemd-boot.enable = true`.
Outputs:
```
building the system configuration...
Traceback (most recent call last):
  File "/nix/store/a6l3ajpr23rjw8xnsn38i6wp0829q83j-systemd-boot", line 278, in main
    write_entry(*gen, machine_id)
  File "/nix/store/a6l3ajpr23rjw8xnsn38i6wp0829q83j-systemd-boot", line 116, in write_entry
    kernel = copy_from_profile(profile, generation, specialisation, "kernel")
  File "/nix/store/a6l3ajpr23rjw8xnsn38i6wp0829q83j-systemd-boot", line 90, in copy_from_profile
    copy_if_not_exists(store_file_path, "/boot%s" % (efi_file_path))
  File "/nix/store/a6l3ajpr23rjw8xnsn38i6wp0829q83j-systemd-boot", line 25, in copy_if_not_exists
    shutil.copyfile(source, dest)
  File "/nix/store/5bh6rpya1ar6l49vrhx1rg58dsa42906-python3-3.9.6/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/qqk6myrkksrwalgvc586d3v61xl8rrd5-user-environment/kernel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/a6l3ajpr23rjw8xnsn38i6wp0829q83j-systemd-boot", line 314, in <module>
    main()
  File "/nix/store/a6l3ajpr23rjw8xnsn38i6wp0829q83j-systemd-boot", line 284, in main
    print("ignoring profile '{}' in the list of boot entries because of the following error:\n{}".format(profile, e), file=sys.stderr)
UnboundLocalError: local variable 'profile' referenced before assignment
```
`...-user-environment.../kernel` is existed with `nixos-rebuild test --flake <path>` but it isn't existed in other `/nix/store/...-user-environment...`.

I have searched on google and discourse and the similar issues are caused with `boot.isContainer`. However, my issue is on a real machine and `boot.isContainer = false`.

The rebuild can work if I modify systemd-boot to grub as follows:
```
  boot.loader.grub.enable = true;
  boot.loader.grub.efiSupport = true;
  boot.loader.grub.device = "nodev";
```
### Steps To Reproduce
I have no idea how to reproduce.

### Metadata
Note: the infomation of channel is useless because of flakes.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"emacs-overlay, home-manager-21.11, nixos-21.11.333823.96b4157790f, nixos-unstable-22.05pre334685.8a308775674, nixpkgs-unstable-22.05pre334669.f366af7a1b3"`
 - channels(vonfry): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by floyza** [comment] 2021-12-30 18:26
I also have this issue. I also use systemd-boot and flakes.
I was rebuilding my configuration multiple times with only minor changes, changing some settings in my foot and zsh home-manager configuration, when I got this error.

I did not reboot between rebuilds, or update flake.lock between rebuilds.

The error message I get is very similar, but I'll put it here:
```
Traceback (most recent call last):
  File "/nix/store/4d48b4f5vhskn9qrnd13mpcygpcjh0h4-systemd-boot", line 278, in main
    write_entry(*gen, machine_id)
  File "/nix/store/4d48b4f5vhskn9qrnd13mpcygpcjh0h4-systemd-boot", line 116, in write_entry
    kernel = copy_from_profile(profile, generation, specialisation, "kernel")
  File "/nix/store/4d48b4f5vhskn9qrnd13mpcygpcjh0h4-systemd-boot", line 90, in copy_from_profile
    copy_if_not_exists(store_file_path, "/boot%s" % (efi_file_path))
  File "/nix/store/4d48b4f5vhskn9qrnd13mpcygpcjh0h4-systemd-boot", line 25, in copy_if_not_exists
    shutil.copyfile(source, dest)
  File "/nix/store/rppr9s436950i1dlzknbmz40m2xqqnxc-python3-3.9.9/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/blgb8g5vxsgcwda36k4khy5sqga8amv0-emacs-27.2/kernel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/4d48b4f5vhskn9qrnd13mpcygpcjh0h4-systemd-boot", line 314, in <module>
    main()
  File "/nix/store/4d48b4f5vhskn9qrnd13mpcygpcjh0h4-systemd-boot", line 284, in main
    print("ignoring profile '{}' in the list of boot entries because of the following error:\n{}".format(profile, e), file=sys.stderr)
UnboundLocalError: local variable 'profile' referenced before assignment
warning: error(s) occurred while switching to the new configuration
```

Using grub instead of systemd-boot works, but I get `skipping corrupt system profile entry ‘/nix/var/nix/profiles/system-237-link’`, which seems like the problem.

Like the above, I use flakes, so my nixos channel doesn't matter.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.88, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(root): `"nixos-21.11pre330462.2fa862644fc"`
 - channels(gavin): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by floyza** [comment] 2021-12-30 18:40
After switching from systemd-boot to grub to successfully rebuild my system and then running `nix-collect-garbage -d`, the problem is fixed and I am able to switch back to systemd-boot.

**Comment by floyza** [comment] 2021-12-30 18:43
Looking back at previous issues, it seems that this is a duplicate of #93694 for the systemd-boot error and (at least for me) #144811 for the broken generation.

**Comment by williamdemeo** [comment] 2023-09-05 21:25
I'm having the same issue when doing `sudo nixos-rebuild switch`.  Here's the tail of stdout:

```
building '/nix/store/pyz40fyg37fgyh5vik2346z6k0blmjag-nixos-system-alonzo-23.11pre521611.e56990880811.drv'...
updating systemd-boot from 252.5 to 253.6
Copied "/nix/store/3i9bs65cm7zwl5664yyngxbgla7s54ga-systemd-253.6/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/efi/EFI/systemd/systemd-bootx64.efi".
Copied "/nix/store/3i9bs65cm7zwl5664yyngxbgla7s54ga-systemd-253.6/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/efi/EFI/BOOT/BOOTX64.EFI".
Traceback (most recent call last):
  File "/nix/store/38bfdh3anlicm8qr8damgvz9k0g5ghmn-systemd-boot", line 341, in <module>
    main()
  File "/nix/store/38bfdh3anlicm8qr8damgvz9k0g5ghmn-systemd-boot", line 310, in main
    raise e
  File "/nix/store/38bfdh3anlicm8qr8damgvz9k0g5ghmn-systemd-boot", line 299, in main
    write_entry(*gen, machine_id, current=is_default)
  File "/nix/store/38bfdh3anlicm8qr8damgvz9k0g5ghmn-systemd-boot", line 111, in write_entry
    kernel = copy_from_profile(profile, generation, specialisation, "kernel")
  File "/nix/store/38bfdh3anlicm8qr8damgvz9k0g5ghmn-systemd-boot", line 84, in copy_from_profile
    copy_if_not_exists(store_file_path, "/boot/efi%s" % (efi_file_path))
  File "/nix/store/38bfdh3anlicm8qr8damgvz9k0g5ghmn-systemd-boot", line 29, in copy_if_not_exists
    shutil.copyfile(source, dest)
  File "/nix/store/pkj7cgmz66assy7l18zc7j992npb41nx-python3-3.10.12/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/nix/var/nix/profiles/system-3-link/kernel'
warning: error(s) occurred while switching to the new configuration

~ took 22m10s 
```

**Closed** 2023-11-25 03:21 UTC
Labels: 0.kind: bug, 6.topic: nixos
