### ISSUE TITLE
[Packaging Request] Gamescope

### ISSUE THREAD

**Issue by IceDBorn** [NixOS/nixpkgs#186954] opened 2022-08-16 13:06 UTC
**Project description**
SteamOS session compositing window manager

**Metadata**

* homepage/source URL: https://github.com/Plagman/gamescope
* license: BSD 2-Clause "Simplified"
* platforms: linux

**Comment by SuperSamus** [comment] 2022-08-16 13:08
Duplicate of #162562.

**Closed** 2022-08-16 13:21 UTC
Labels: 0.kind: packaging request
