### ISSUE TITLE
`tor-browser-bundle-bin` cannot run `tor` in the browser

### ISSUE THREAD

**Issue by storopoli** [NixOS/nixpkgs#222693] opened 2023-03-23 09:54 UTC
### Describe the bug
If I add `tor-browser-bundle-bin` to my `configuration.nix` I get this error in the Tor Browser.

![image](https://user-images.githubusercontent.com/43353831/227166535-8cea79b2-d3f6-4607-ac11-dbb468fe5e52.png)

Somehow it connects:
![image](https://user-images.githubusercontent.com/43353831/227166786-4da4a360-a5a9-4473-9a5f-61b922945f69.png)

### Notify maintainers

@offline @matejc @thoughtpolice @joachifm @hax404 @KarlJoad

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/mk5p8a7rqx54qdy557chl7l5cq8kjrgl-nix-info
copying path '/nix/store/mk5p8a7rqx54qdy557chl7l5cq8kjrgl-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.7, NixOS, 23.05 (Stoat), 23.05.20230321.19cf008`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.14.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Tungsten842** [comment] 2023-03-23 20:21
Duplicate of: https://github.com/NixOS/nixpkgs/issues/219750

**Closed** 2023-04-01 08:21 UTC
Labels: 0.kind: bug
