### ISSUE TITLE
wezterm fails to build

### ISSUE THREAD

**Issue by nbraud** [NixOS/nixpkgs#118175] opened 2021-03-31 22:02 UTC
**Describe the bug**
Evaluating the `wezterm` derivation fails as it looks for an inexistent `/wezterm` file.

**To Reproduce**
Run `nix-shell -p wezterm --run wezterm`

**Expected behavior**
`wezterm` is fetched from cache, starts successfully.

**Additional context**
Here is the tail of the output:
```
   Doc-tests tabout

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

Finished cargoCheckHook
installing
patchelf: getting info about '/wezterm': No such file or directory
builder for '/nix/store/hd2xgszfjyr3glrsl7jmagjdcg7qg2wa-wezterm-unstable-2020-11-22.drv' failed with exit code 1
error: build of '/nix/store/hd2xgszfjyr3glrsl7jmagjdcg7qg2wa-wezterm-unstable-2020-11-22.drv' failed
```

**Notify maintainers**
@steveeJ 

**Metadata**
```yaml
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.106, NixOS, 21.05pre277486.f5e8bdd07d1 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(nicoo): `"home-manager"`
 - channels(root): `"nixos-21.05pre279456.04a2b269d89, nixpkgs-20.09pre239808.ddfa2216701"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- wezterm
# a list of nixos modules affected by the problem
module:
```

**Comment by nh2** [comment] 2021-04-02 15:37
The reason is probably that variable `$releaseDir` does not exist, and because the build shell runs without `set -u` (bad idea in my opinion, silent failures are bad), the line:

```
    for artifact in wezterm ...; do
      patchelf --set-rpath "${lib.makeLibraryPath runtimeDeps}" $releaseDir/$artifact
```

becomes

```
      patchelf --set-rpath "${lib.makeLibraryPath runtimeDeps}" /wezterm
```

thus giving:

```
patchelf: getting info about '/wezterm': No such file or directory
```

This is confirmed easily by adding `set -u`:

```
line 1311: releaseDir: unbound variable
```

`wezterm` built fine on commit https://github.com/NixOS/nixpkgs/commit/b9f0b2885b1986b12a1fe1e527b12d5c58e936dd#diff-1abd3beb2bb3cd2e8d735cb6dd514aa414f81d75887bcbbe077bfc257e5eb3f8.

I believe the regression reason is PR #113193, specifically commit 9757c7101a0527c001fa9e9832764d5dc106ff25 - `buildRustPackage: factor out install phase to cargoInstallHook`

`git log -SreleaseDir` shows related fixes for other packages:

```
commit 0177ea48e2a572360291df6bcc004a4e4eaaf00d
Author: yvt <i@yvt.jp>
Date:   Thu Mar 4 01:05:00 2021 +0900

    cfdyndns: fix build
    
    The custom installPhase got broken as the rust build scripts only
    provide $releaseDir in postInstall hooks. The default rust installPhase
    installs the same files, so the custom one is unnecessary.

commit 5e401dcd2bdb769438ef4902faeea231beeaf67a
Author: Jakub Kądziołka <kuba@kadziolka.net>
Date:   Fri Feb 26 21:59:45 2021 +0100

    alacritty: fix build
    
    Use postInstall instead of installPhase to give the cargo hooks a chance
    to set $releaseDir.

commit 3bd0b03fb3fe9c1a274f69fba39d902490ea81ea
Author: Jakub Kądziołka <kuba@kadziolka.net>
Date:   Fri Feb 26 18:55:59 2021 +0100

    tox-node: fix build
    
    The custom installPhase got broken as the rust build scripts only
    provide $releaseDir in postInstall hooks. The default rust installPhase
    installs the same files, so the custom one is unnecessary.
```

The PR #106976 is currently open but does not fix it because it is too old.

CC @danieldk as author of the regressing PR

CC @fanzeyi @steveeJ from the `wezterm` commit history

**Comment by dotlambda** [comment] 2021-04-24 07:26
fixed by https://github.com/NixOS/nixpkgs/pull/118712

**Closed by dotlambda** 2021-04-24 07:26 UTC
Labels: 0.kind: bug
