### ISSUE TITLE
Package request: edgedriver

### ISSUE THREAD

**Issue by dylanmtaylor** [NixOS/nixpkgs#222021] opened 2023-03-19 14:07 UTC
**Project description**

Microsoft Edge WebDriver, similar to chromedriver or geckodriver.

**Metadata**

* homepage URL: https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
* source URL: N/A
* license: proprietary
* platforms: windows, linux, darwin

**Comment by SigmaSquadron** [comment] 2024-10-24 17:15
Duplicate of #192050

**Closed by SigmaSquadron** 2024-10-24 17:15 UTC
Labels: 0.kind: packaging request
