### ISSUE TITLE
Wireguard - waiting for DNS before trying to start the interface

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#30459] opened 2017-10-16 06:42 UTC
## Issue description

I have wireguard installed and I use a domain name for the connection to the wireguard server. Problem is, that upon boot, wg doesn't seem to wait for dns resolution and hence starting the interface fails.

### Steps to reproduce

Add wireguard client configuration like:

```
    # Enable Wireguard
    networking.wireguard.interfaces = {
        wg0 = {
            ips = [ "10.10.0.2/24" ];
            peers = [ {
                allowedIPs = [ "10.10.0.0/24" ];
                endpoint = "wireguard.server.tld:51820";
                publicKey = "yaddayaddayadda";
                persistentKeepalive = 25;
            } ];
            privateKey = "anotheryadda";
        };
    };
```
And often - not always - I get journalctl entries like this

```
Okt 16 08:27:14 subi ip[6066]: Cannot find device "wg0"
Okt 16 08:27:14 subi kernel: wireguard: WireGuard 0.0.20171005 loaded. See www.wireguard.com for information.
Okt 16 08:27:14 subi kernel: wireguard: Copyright (C) 2015-2017 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
Okt 16 08:27:14 subi polkitd[6128]: Started polkitd version 0.113
Okt 16 08:27:14 subi wg[6233]: Name or service not known: `wireguard.server.tld:51820`
Okt 16 08:27:14 subi systemd[1]: wireguard-wg0.service: Main process exited, code=exited, status=1/FAILURE
Okt 16 08:27:14 subi systemd[1]: Failed to start WireGuard Tunnel - wg0.
Okt 16 08:27:14 subi systemd[1]: wireguard-wg0.service: Unit entered failed state.
Okt 16 08:27:14 subi systemd[1]: wireguard-wg0.service: Failed with result 'exit-code'.
```

From what I read is that it can't resolve the dns properly.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

`18.03pre117886.874a3c033c (Impala)`

* Nix version: (run `nix-env --version`)

`nix-env (Nix) 1.11.15`

* Nixpkgs version: (run `nix-instantiate --eval "<nixpkgs>" -A lib.nixpkgsVersion`)

`"18.03pre117939.3ee33f35f8"`

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

`build-use-sandbox = false`

**Comment by Mic92** [comment] 2017-10-16 11:32
This must be solved upstream. In my systemd-networkd pull request I do exponential backoff.

**Comment by Mic92** [comment] 2017-10-16 11:33
cc @zx2c4

**Comment by zx2c4** [comment] 2017-10-16 12:20
>  In my systemd-networkd pull request 
Any plans to finish that soon?

Funny enough I changed the resolv algorithm a bit last night, actually:

https://git.zx2c4.com/WireGuard/commit/?id=76a9bb3898fa7ce8574a32d587014ae91ab34703

This is based on the discussion here:

https://sourceware.org/glibc/wiki/NameResolver

> From the perspective of the application that calls getaddrinfo() it perhaps doesn't matter that much since EAI_FAIL, EAI_NONAME and EAI_NODATA are all permanent failure codes and the causes are all permanent failures in the sense that there is no point in retrying later.

However, it appears that @sjau is receiving EAI_NONAME, which means the above patch won't help. Why is @sjau receiving a _permanent error_ at this stage? @sjau - could you describe in depth your DNS configuration?

**Comment by sjau** [comment] 2017-10-16 12:31
Having a Turris Omni router. In it I run dnsmasq to resolve the server domain name (dyndns address) locally. So that it resolves properly from the lan and from the wan.

The entry for dnsmasq in the /etc/hosts.add file in the TO router is:

`10.0.0.10 wireguard.server.tld`

**Comment by zx2c4** [comment] 2017-10-16 12:34
The hardware used isn't relevant.

What is in your /etc/resolv.conf? `nameserver 127.0.0.1`? What's in your /etc/nsswitch.conf? Does this issue occur because wg is executed before dnsmasq is started? What is the purpose of you using `/etc/hosts.add` in that way, rather than ordinary DNS?

**Comment by sjau** [comment] 2017-10-16 12:37
```
cat /etc/nsswitch.conf 
passwd:    files mymachines systemd
group:     files mymachines systemd
shadow:    files

hosts:     files mymachines mdns_minimal [!UNAVAIL=return] dns mdns myhostname
networks:  files

ethers:    files
services:  files
protocols: files
rpc:       files
```

```
cat /etc/resolv.conf 
# Generated by resolvconf
nameserver 10.10.10.1
nameserver 2a02:169:802::1
nameserver fdfe:f8a3:6ff2::1
options edns0
```

Client doesn't use dnsmasq... that's the router.

**Comment by Mic92** [comment] 2017-10-16 12:37
So either avahi's mdns or the glibc resolver return this.

**Comment by Mic92** [comment] 2017-10-16 12:38
I also remember that I had to treat every error as transient error in networkd.

**Comment by zx2c4** [comment] 2017-10-16 12:46
> Client doesn't use dnsmasq... that's the router.

In that case, I have no idea what belongs to what and what on earth you're talking about. So let's start over:

Our issue is with the client. I don't want to hear about other computers. Just the client. Would you summarize in one post all of the relevant DNS information about the client?

**Comment by sjau** [comment] 2017-10-16 12:48
Well, you wanted to know in depth dns configuration. Since I don't run a dns server on the client, I assumed you meant the dns server that I use... so I gave you that.

That's from the client, the information you requested:

https://github.com/NixOS/nixpkgs/issues/30459#issuecomment-336873587

**Comment by zx2c4** [comment] 2017-10-16 12:58
Okay, thanks for the clarification. So:

```
hosts:     files mymachines mdns_minimal [!UNAVAIL=return] dns mdns myhostname
```

Are any of these tweaked by you? Or is this a standard NixOS situation? For comparison, my line (from a different distro) just looks like:

```
hosts:       files dns
```

So one line in `files mymachines mdns_minimal [!UNAVAIL=return] dns mdns myhostname` is returning EAI_NONAME instead of EAI_AGAIN like it should. Can you figure out which of these is responsible for that?

If this line is your concoction then perhaps fixing it is the right thing to do. If it's a Nix-specific screw-up, then it should be easy enough to change the line in Nix's default nsswitch. If, however, this is some standard degenerate behavior, we may very well be quite unhappy, and I'll have to figure out something unusual for working around it.

**Comment by sjau** [comment] 2017-10-16 13:07
I did set to use Avahi:

```
    services.avahi = {
        enable = true;
        hostName = "${mySecrets.hostname}";
        nssmdns = true;
    };
```

but I don't really need it.

**Comment by fpletz** [comment] 2017-10-23 23:15
Fixed by #30472. Thanks!

**Comment by sjau** [comment] 2017-11-04 17:50
actually, this hasn't been solved yet...

it's still failing

```
-- Reboot --
Nov 04 18:45:18 subi systemd[1]: Starting WireGuard Tunnel - wg_home...
Nov 04 18:45:18 subi ip[5601]: Cannot find device "wg_home"
Nov 04 18:45:18 subi systemd[1]: wireguard-wg_home.service: Main process exited, code=exited, status=1/FAILURE
Nov 04 18:45:18 subi wg[6019]: Name or service not known: `servi.home.sjau.ch:51820'
Nov 04 18:45:18 subi systemd[1]: Failed to start WireGuard Tunnel - wg_home.
Nov 04 18:45:18 subi systemd[1]: wireguard-wg_home.service: Unit entered failed state.
Nov 04 18:45:18 subi systemd[1]: wireguard-wg_home.service: Failed with result 'exit-code'.
```

Wouldn't it be better for wg to retry automatically?

**Comment by vcunat** [comment] 2017-11-04 18:48
On some kinds of "error conditions" it's not much meaningful to retry, as described in https://git.zx2c4.com/WireGuard/commit/?id=76a9bb3898fa7ce8574a32d587014ae91ab34703

but from the log it's not clear what exactly the OS got from DNS.

**Comment by sjau** [comment] 2017-11-04 19:27
How to get different log? That's from journalctl....

**Comment by zx2c4** [comment] 2017-11-05 01:30
Looks like it's returning `EAI_NONAME`. Can you verify the contents of `/etc/resolv.conf` at that point during boot?

**Comment by sjau** [comment] 2017-11-05 06:44
How to do that?

**Comment by vcunat** [comment] 2017-11-05 10:48
Something is probably different, given that restarting the service later fixes the problem.  @sjau: what's your DNS setup?  On the client you get all servers from DHCP only?  DHCP is served by Turris Omnia router and these three addresses belong to it?

Assuming the name is `servi.home.sjau.ch.`, I suspect there might be a problem if IPv6 gets up sooner than IPv4, because that particular name has no AAAA record...

**Comment by sjau** [comment] 2017-11-05 11:05
except for a few entries in the hosts file, I get everything from the TO router.

**Comment by sjau** [comment] 2017-11-05 12:10
Ok, I disabled IPv6 on my notebook and still the same:
```
    networking = {
        # Disable IPv6
        enableIPv6 = false;
```


```
-- Reboot --
Nov 05 13:04:50 subi systemd[1]: Starting WireGuard Tunnel - wg_home...
Nov 05 13:04:50 subi ip[5174]: Cannot find device "wg_home"
Nov 05 13:04:50 subi wg[5575]: Name or service not known: `servi.home.sjau.ch:51820'
Nov 05 13:04:50 subi systemd[1]: wireguard-wg_home.service: Main process exited, code=exited, status=1/FAILURE
Nov 05 13:04:50 subi systemd[1]: Failed to start WireGuard Tunnel - wg_home.
Nov 05 13:04:50 subi systemd[1]: wireguard-wg_home.service: Unit entered failed state.
Nov 05 13:04:50 subi systemd[1]: wireguard-wg_home.service: Failed with result 'exit-code'.
```

**Comment by zx2c4** [comment] 2017-11-05 19:10
Can you post a more substantial log to see the various other things happening?

**Comment by sjau** [comment] 2019-01-08 07:50
My workaround is this:

https://github.com/sjau/nix-expressions/blob/master/wgStartFix.nix

**Comment by timokau** [comment] 2019-01-13 08:57
I can confirm that this is still an issue. A nicer workaround without requiring a separate service to watch wireguard may be:

```nix
networking.wireguard.interfaces.wg0 = {
  preSetup = ''
    # Try to access the DNS for up to 300s
    for i in {1..300}; do
      ${pkgs.iputils}/bin/ping -c1 '<insert domain to resolve here>' && break
      echo "Attempt $i: DNS still not available"
      sleep 1s
    done
  '';
  ...
}
```

On my first try, that succeeded to start the wireguard service after 11 failed attempts (i.e. 11 seconds after network-online).

**Comment by sjau** [comment] 2019-01-13 10:15
The question is why this happens.

Yours works also but what if you have multiple wg up?

**Comment by timokau** [comment] 2019-01-16 19:22
After some research I though the solution would be to add `nss-lookup.target` to the `After` and `Requires` section of the service. Unfortunately that did not improve the situation.

**Comment by Mic92** [comment] 2019-01-16 20:22
@timokau between our glibc resolver and the application is nscd. Maybe that alters the errno returned to the application. Apart from that anything in our `/etc/nsswitch.conf` can change the results.

**Comment by timokau** [comment] 2019-01-16 21:48
I'm not sure I understand that. Why do you assume an error is altered?

**Comment by Mic92** [comment] 2019-01-16 22:15
@timokau because the error returned by our setup seems not to match what other distributions return, when the resolver cannot be reached: https://github.com/NixOS/nixpkgs/issues/30459#issuecomment-336878762

**Comment by sjau** [comment] 2019-02-11 11:22
Hmmm, I just discovered that systemd.network does support now wireguard as well:

https://manpages.debian.org/testing/systemd/systemd.netdev.5.en.html#%5BWIREGUARDPEER%5D_SECTION_OPTIONS

Maybe it's easier to just setup there? According to the nixos options it's not yet supported though.

**Comment by sjau** [comment] 2019-05-23 06:21
Coming back to this ancient problem:

Last night gchristensen and I were talking a bit about this problem. in the end he suggested to add a 

```
    systemd.services.wireguard-wg[...].serviceConfig.Restart = "on-failure";
    systemd.services.wireguard-wg[...].serviceConfig.RestartSec = "5s";
```

To the configuration.nix so that it will restart. However during rebuilding it complained that restart on failure does not go hand-in-hand with "oneshot" systemd type. (There's also an issue on systemd tracker that asks for adding retry on failure to oneshot type:  https://github.com/systemd/systemd/issues/2582 ).

So, I tried to alter the oneshot type to simple by altering

```
          Type = "oneshot";
```
to
```
          Type = "simple";
```

in the `https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/wireguard.nix#L248` file.


Since I didn't know the proper syntax to add `RestartSec = "5s";` in the nix file there, I did just add
```
    systemd.services.wireguard-wg[...].serviceConfig.RestartSec = "5s";
```

to the `configuration.nix`


After that I did rebuild and it works fine. It will now re-try to connect to the wg vpns even if first attempt isn't successfull.


Currently my notebook connects to 3 wg vpns with this and I've had several reboots (for testing) and they always came back up again.


So the question is: What is the benefit of "oneshot" compared to "simple" since "oneshot" seems to prevent wg coming up properly when using a domain name as server traget instead of an ip address.

**Comment by sjau** [comment] 2019-05-26 11:04
This got fixed:

https://github.com/NixOS/nixpkgs/pull/61971

**Comment by sjau** [comment] 2019-06-20 19:03
While #61971 did fix the issue, later changes introduced the same problem again for the wg peers. They will not get started properly because of oneshot type and no dns available at bootup.

**Comment by sjau** [comment] 2020-06-04 04:56
Still important to me

**Comment by llewxam-kache** [comment] 2020-07-09 21:08
Relevant to my interests as well, and I'm also a little confused as to why the systemd service runs as a 'oneshot' instead of continually retrying (maybe at exponential intervals up to 30 seconds)
If you're running this service, presumably you always want it to come up, or at least want to define how many times it tries to restart, right?

**Comment by tgunnoe** [comment] 2021-01-08 17:27
still important to me as well, an easier vpn setup

**Comment by flokli** [comment] 2021-01-09 18:38
Our whole `networking.wireguard` setup is somewhat scripted, so it being handled in oneshot services seems appropriate - there's just no long-running daemon here, but just a bunch of iproute2/wg command invocations.

The oneshot services setting up the interface do wait for `network-online.target` (which means DNS should be reachable), and since 1de35c7f5ecbfe3c5bae252f660068669eb62b7a, all the per-peer scripts depend on that script. They also set `WG_ENDPOINT_RESOLUTION_RETRIES = "infinity"`, which should help with some intermittent DNS blips.

@sjau the original issue seems to be solved. If you still experience problems, please open a new issue with a reproducer and up2date logs.

**Closed by flokli** 2021-01-09 18:38 UTC

**Comment by corbolais** [comment] 2024-07-02 08:44
Just found this https://github.com/sis2022/wireguard-dynip-update seems to be working quite reliably since I started using it a week ago. Running it on a handful of hosts now I got no more connection issues, yay!
If it stays that way, I'm a happy camper. 

It's cronjobbed quite tightly by default but I found it to be a no-brainer and it is easily rescheduled less often if need be.
