### ISSUE TITLE
duplicity not installing anymore

### ISSUE THREAD

**Issue by j4m3s-s** [NixOS/nixpkgs#82695] opened 2020-03-15 23:11 UTC
**Describe the bug**
nix-shell -p duplicity fails because one of its tests don't pass.

**To Reproduce**
on nixos-unstable:
nix-shell -p duplicity

**Expected behavior**
The command above working.

**Metadata**
```
- system: `"x86_64-linux"`
 - host os: `Linux 5.4.23, NixOS, 20.09pre215947.82b54d49066 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre216896.0729b8c55e0"`
 - channels(j4m3s): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jtojnar** [comment] 2020-03-16 11:16
This was fixed in https://github.com/NixOS/nixpkgs/pull/82400.

**Comment by jtojnar** [comment] 2020-03-16 11:18
Also duplicate of https://github.com/NixOS/nixpkgs/issues/82618

**Closed** 2020-03-16 11:53 UTC
Labels: 0.kind: bug
