### ISSUE TITLE
hash mismatch in downloaded file

### ISSUE THREAD

**Issue by lockejan** [NixOS/nixpkgs#179601] opened 2022-06-29 18:20 UTC
### Describe the bug
Due to case insensitivity of darwins filesystem a pretty similar bug ended up in unstable:
https://github.com/NixOS/nixpkgs/pull/178509

However, in this case I don't understand why this happens. I'm not on unstable-channel, but maybe it's because of the same reason?
```
error: hash mismatch in file downloaded from 'https://api.github.com/repos/nixos/nixpkgs/tarball/f2537a505d45c31fe5d9c27ea9829b6f4c4e6ac5':
         specified: sha256:1z28a3gqbv62sxahlssc5a722kh46f26f5ss3arbxpv7a1272vf1
         got:       sha256:1n2z95321nccy3y9h8zw3gsgzwkaigypkybqjva31qd6xb4dl3d1

```

This commit isn't part of the 22.05 darwin release.

### Steps To Reproduce
1. use any recent channel, e.g. https://nixos.org/channels/nixpkgs-unstable or https://nixos.org/channels/nixpkgs-22.05-darwin or even nixpkgs-22.05-nixos (it happens on all of them)
2. sudo -i nix-channel --update
3. darwin-rebuild switch

### Additional context
sudo -i nix-channel --list
```
darwin https://github.com/LnL7/nix-darwin/archive/master.tar.gz
home-manager https://github.com/nix-community/home-manager/archive/release-22.05.tar.gz
nixpkgs https://nixos.org/channels/nixpkgs-22.05-darwin
```

### Notify maintainers

@NixOS/darwin-maintainers 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.5.0, macOS 12.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.8.1`
 - channels(lockejan): `""`
 - channels(root): `"darwin, home-manager-22.05.tar.gz, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

```

**Comment by lockejan** [comment] 2022-06-29 18:27
https://github.com/NixOS/nix/issues/1885

**Comment by SuperSandro2000** [comment] 2022-06-29 20:47
Closing as dupe of the linked issue above. Also this is a nix issue, not nixpkgs.

**Closed by SuperSandro2000** 2022-06-29 20:47 UTC
Labels: 0.kind: bug, 6.topic: darwin
