### ISSUE TITLE
Consider moving user supplied PipeWire config to a separate file.

### ISSUE THREAD

**Issue by pinkisemils** [NixOS/nixpkgs#205289] opened 2022-12-09 11:50 UTC
### Describe the bug
When trying to configure PipeWire to load a module (`libpipewire-module-raop-discover`),  the produced configuration file had the module declared at the start of the modules list. Since this module depends on other modules, `pipewire` will fail to start. Instead of combining the user supplied config with the _default_ config values, maybe it should be stored as a separate file in `/etc/pipewire/pipewire.conf.d/user.conf` ?

### Steps To Reproduce
1. Add the following config option to your NixOS configuration, version 22.11.
```nix
services.pipewire.config.pipewire = {
    "context.modules" = [ { name = "libpipewire-module-raop-discover" ;  } ];
};
```
2. Start or restart pipewire via `systemctl --user restart pipewire` and observe it failing to start.

### Expected behavior
PipeWire should work as intended, not fail to start and load the RAOP module. 

### Additional context
I have worked around this issue by just creating the config file I wanted myself via `environment.etc."pipewire/pipewire.conf.d/...` 

### Notify maintainers
The metadata lists the freedesktop team as the maintainers, so I'm just going by git-blame.
@talyz @jansol 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"
 - host os: `Linux 6.0.11, NixOS, 22.11 (Raccoon), 22.11.726.04a75b2eecc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos-22.11"`
 - channels(emilsp): `"nixos-22.11, nixpkgs-22.11, stable-22.11"`
 - nixpkgs: `/home/emilsp/.nix-defexpr/channels/nixpkgs`
```

**Comment by jansol** [comment] 2022-12-09 12:46
IIRC the problem isn't that the modules you specify are placed at the top of the list (while that would indeed also be a problem) but rather that the list you provide **completely replaces** the default list which includes among other things the pipewire core protocol module that *everything* else depends on. The workaround for this is to add all modules that are listed in the default config to your configuration.nix.

The reason why it works like this is a limitation in Nix: when merging attrsets, any lists will get replaced rather than joined. But even if that wasn't the case we'd want to have a way of removing things from the default config.

I guess one way around it would be to introduce something like an `additionalDaemonModules` config option that specifies a list of modules to be appended to `services.pipewire.config.pipewire."context.modules"`. Personally I would not mind restructuring the pipewire module since the current state of it is very much a least effort conversion from the SPA- JSON config files.

**Comment by flokli** [comment] 2023-01-05 21:09
cc @roberth

**Comment by roberth** [comment] 2023-01-08 13:49
_Lists of submodules_ are definitely something to avoid, because they allow no customization. (Also lists of anything in general, but the more complicated the list item is, the more likely it is you'll want to override it.)

In this case it seems that the list is part of a mapped format. Perhaps we could add an option outside `services.pipewire.config` to generate a module list. That's what I did for [metricbeat modules](https://search.nixos.org/options?channel=unstable&show=services.metricbeat.modules&from=0&size=50&sort=relevance&type=packages&query=metricbeat). Maybe add an `enable = mkOption { default = true }` option if you need users to be able to disable system-provided default modules.

**Comment by GaetanLepage** [comment] 2023-02-13 16:05
Indeed, being able to cleanly add a module to pipewire without overriding all the existing ones would be really helpful !

**Comment by flokli** [comment] 2024-03-10 16:20
I think the originally reported problem doesn't exist anymore.

There's now a deprecation warning both when using `services.pipewire.config` or `environment.etc."pipewire/pipewire.conf.d/roap.conf"`.

The way this should be configured now is:

```nix
extraConfig.pipewire."roap" = {
  "context.modules" = [this can be closed.
    { name = "libpipewire-module-raop-discover"; }
   ];
 };
```

… and with this, my pipewire doesn't fail to restart.

Sure, the ROAP module still is a bit buggy, but that's already reported in the upstream issue tracker and nothing NixOS-specific.

**Comment by flokli** [comment] 2024-03-10 16:23
Closing this issue, feel free to reopen if you disagree.

**Closed by flokli** 2024-03-10 16:23 UTC
Labels: 0.kind: bug
