### ISSUE TITLE
Build more slow python packages in Hydra

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#25630] opened 2017-05-09 02:11 UTC
At some point we stopped building them because most of them are a waste of space and take no time at all on user machines. We currently intentionally tell Hydra to build a couple of those packages because they're slow to build, but not many people know about that mechanism. Currently  I'm building shiboken which is taking a while and it would be nice to have a mechanism integrated in the package set to indicate that we want Hydra to build it. Does `hydraPlatforms` work on Python packages? It might be cool for us to use that a bit more in `pythonPackages` instead of having manual exclusions in `release.nix`.

cc @FRidh

**Comment by FRidh** [comment] 2017-05-09 07:47
@copumpkin I suppose this is in answer to d4dde073fd9d59f104d295df32f60ad8d56889ea?
We stopped building package sets in https://github.com/NixOS/nixpkgs/commit/ccd1029f58a3bb9eca32d81bf3f33cb4be25cc66.

**Comment by FRidh** [comment] 2017-05-09 07:51
The package sets are overridden in `release.nix` with empty sets so that won't work. In any case, in my opinion what Hydra should build is independent of the package set. 

We could add a few more packages, like shiboken, to `release.nix`.
What is more important in my opinion is to have a Hydra job that builds the Python package set and use as input a tested revision, so `nixpkgs-channels/nixpkgs-unstable`, etc.

**Comment by lheckemann** [comment] 2017-05-10 11:08
IMHO building small packages too would be nice. Regressions like #25530 can go undetected because they're not built on hydra. Or is there some other mechanism in place that can detect them?

**Comment by FRidh** [comment] 2017-05-10 11:11
Its not just about detecting, but also about actually fixing. Even when we
were still building Python packages 100-200 were broken at any time.

**Comment by FRidh** [comment] 2017-05-30 17:42
I'm closing this issue because its not very concrete. If you want a certain package built by Hydra, then I referred to the file that can be modified to make it happen.

**Closed by FRidh** 2017-05-30 17:42 UTC
Labels: 6.topic: python
