### ISSUE TITLE
Package: ilua, nice interactive Lua (as a Jupyter kernel)

### ISSUE THREAD

**Issue by bew** [NixOS/nixpkgs#148008] opened 2021-11-30 12:32 UTC
**Project description**
Portable Lua kernel for Jupyter
![image](https://raw.githubusercontent.com/guysv/ilua/955d8fafa2dfbf0e076e3b38dc9f5327aa9960c9/demo.gif)

**Metadata**

* homepage URL: https://github.com/guysv/ilua
* source URL: https://github.com/guysv/ilua
* license: gplv2
* platforms: same & python & lua I think

**Comment by WolfangAukang** [comment] 2022-02-03 03:20
Merged

**Closed by WolfangAukang** 2022-02-03 03:20 UTC
Labels: 6.topic: lua, 0.kind: packaging request

**Comment by bew** [comment] 2022-02-11 10:05
Hello @WolfangAukang I can't get it to work, I'm trying:
```console
$ nix run unstable#python39.pkgs.ilua
[ZMQTerminalIPythonApp] WARNING | Kernelspec name lua cannot be found!
[ZMQTerminalIPythonApp] ERROR | No such kernel named lua
jupyter_client.kernelspec.NoSuchKernel: No such kernel named lua
jupyter_client.kernelspec.NoSuchKernel: No such kernel named lua
... with python tracebacks ...
```
I also tried to add `-i lua` to the `ilua` execution without much success.

Does that work for you?

**Comment by WolfangAukang** [comment] 2022-02-11 14:04
Hey @bew, the issue is that there was no lua kernel installed to test it. I had to test it outside of NixOS because I wasn't able to find a built kernel on nixpkgs, so I installed it, checked that `jupyter kernelspec list` showed it and then ran `ilua -i kernel`, and it worked.
