### ISSUE TITLE
cctools ld segfaults when linking haskellPackages.Agda (2.6.2 only?)

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#149692] opened 2021-12-08 18:41 UTC
[Example Log](https://hydra.nixos.org/build/160900296/nixlog/1):

```
Building executable 'agda' for Agda-2.6.2..
[1 of 1] Compiling Main             ( src/main/Main.hs, dist/build/agda/agda-tmp/Main.o )
Linking dist/build/agda/agda ...
/nix/store/bp55vzlmcyqcx9n08pkzslvks10zybwc-clang-wrapper-11.1.0/bin/ld: line 256: 79105 Segmentation fault: 11  /nix/store/3fl5z9yfnz08kjb4cnhw2w8a2zsm5qim-cctools-binutils-darwin-949.0.1/bin/ld ${extraBefore+"${extraBefore[@]}"} ${params+"${params[@]}"} ${extraAfter+"${extraAfter[@]}"}
clang-11: error: linker command failed with exit code 139 (use -v to see invocation)
`cc' failed in phase `Linker'. (Exit code: 139)
builder for '/nix/store/fyzdyk7a79jqfh4r2gvjc65d9f7w22wd-Agda-2.6.2.drv' failed with exit code 1
```

### Steps To Reproduce

`nix-build -A haskellPackages.Agda` on `aarch64-darwin`

cc @NixOS/darwin-maintainers

**Comment by prusnak** [comment] 2021-12-08 18:45
Does adding `autoSignDarwinBinariesHook` to `nativeBuildInputs` help?

**Comment by prusnak** [comment] 2021-12-08 18:46
> Does adding `autoSignDarwinBinariesHook` to `nativeBuildInputs` help?

Ah, sorry. This is about fixing "Killed: 9" error.

**Comment by sternenseemann** [comment] 2021-12-08 18:47
Yeah, `Agda` is a normal haskell package which [work for the most part](https://hydra.nixos.org/eval/1729112?filter=haskellPackages&compare=1728918&full=#tabs-still-succeed).

**Comment by veprbl** [comment] 2021-12-08 19:07
Would help to post a crash dump from Other -> Console -> User Reports

**Comment by sternenseemann** [comment] 2021-12-08 20:24
Indeed, would be nice if someone could have a look at this locally, I can only check on Hydra logs, really.

**Comment by olebedev** [comment] 2021-12-08 23:18
Getting:

```
Linking dist/build/agda/agda ...
/nix/store/bp55vzlmcyqcx9n08pkzslvks10zybwc-clang-wrapper-11.1.0/bin/ld: line 256: 36953 Segmentation fault: 11  /nix/store/3fl5z9yfnz08kjb4cnhw2w8a2zsm5qim-cctools-binutils-darwin-949.0.1/bin/ld ${extraBefore+"${extraBefore[@]}"} ${params+"${params[@]}"} ${extraAfter+"${extraAfter[@]}"}
clang-11: error: linker command failed with exit code 139 (use -v to see invocation)
`cc' failed in phase `Linker'. (Exit code: 139)
builder for '/nix/store/fyzdyk7a79jqfh4r2gvjc65d9f7w22wd-Agda-2.6.2.drv' failed with exit code 1
error: build of '/nix/store/fyzdyk7a79jqfh4r2gvjc65d9f7w22wd-Agda-2.6.2.drv' failed
```

on 7370b263d797848f9aa391fc94999eece396f35d

**Comment by sternenseemann** [comment] 2021-12-13 12:11
Interesting, let's keep this open in case it happens in another package

**Comment by frontsideair** [comment] 2021-12-23 14:53
I have the exact same error with `haskellPackages.lattices`, as you can see from [Hydra job](https://hydra.nixos.org/build/160898151).

**Comment by sternenseemann** [comment] 2021-12-23 15:29
Agda 2.6.2.1 started failing again as well iirc. I suspect this could possibly be OOM or a segfault, but impossible to test from my position.

**Comment by turion** [comment] 2021-12-30 19:58
Can someone on darwin reproduce and bisect?

**Comment by ZachFontenot** [comment] 2022-03-23 16:29
I'm hitting this locally on `aarch64-darwin` not sure how I can help out though?

**Comment by siraben** [comment] 2022-03-24 06:12
I can't find the commit where this succeeds on `aarch64-darwin`, has anyone found it?

**Comment by sternenseemann** [comment] 2022-03-24 10:15
2c85c77a8a4c2580e7b116f0c62e4fa233b7238d according to hydra

**Comment by ZachFontenot** [comment] 2022-03-25 16:20
```
bff49dab05df8c825b268ca863140e6a119626b1 is the first bad commit
commit bff49dab05df8c825b268ca863140e6a119626b1
Merge: 40d43349e66 a7dda03a2e0
Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Date:   Tue Nov 23 06:01:42 2021 +0000
```

Result of Bisect

**Comment by siraben** [comment] 2022-03-26 14:29
My bisection agrees:
```
bff49dab05df8c825b268ca863140e6a119626b1 is the first bad commit                                                                                                                                                      
commit bff49dab05df8c825b268ca863140e6a119626b1                                                                                                                                                                       
Merge: 40d43349e66 a7dda03a2e0                                                                                                                                                                                        
Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>                                                                                                                                   
Date:   Tue Nov 23 06:01:42 2021 +0000                                                                                                                                                                                
                                                                                                                                                                                                                      
    Merge staging-next into staging                                                                                                                                                                                   
```

**Comment by veprbl** [comment] 2022-05-16 19:29
@unbel13ver That can't be related. Please file a separate issue.

**Comment by soulomoon** [comment] 2022-06-24 09:37
```
    "nixpkgs": {
      "locked": {
        "lastModified": 1645433236,
        "narHash": "sha256-4va4MvJ076XyPp5h8sm5eMQvCrJ6yZAbBmyw95dGyw4=",
        "owner": "nixos",
        "repo": "nixpkgs",
        "rev": "7f9b6e2babf232412682c09e57ed666d8f84ac2d",
        "type": "github"
      },
```

```
building '/nix/store/8zr9cl44sdnr6mg70g3s3xkvl4dkdi0c-Agda-2.6.2.1.drv'...
error: builder for '/nix/store/8zr9cl44sdnr6mg70g3s3xkvl4dkdi0c-Agda-2.6.2.1.drv' failed with exit code 1;
       last 10 log lines:
       > [398 of 400] Compiling Agda.Compiler.JS.Compiler ( src/full/Agda/Compiler/JS/Compiler.hs, dist/build/Agda/Compiler/JS/Compiler.o, dist/build/Agda/Compiler/JS/Compiler.dyn_o )
       > [399 of 400] Compiling Agda.Compiler.Builtin ( src/full/Agda/Compiler/Builtin.hs, dist/build/Agda/Compiler/Builtin.o, dist/build/Agda/Compiler/Builtin.dyn_o )
       > [400 of 400] Compiling Agda.Main        ( src/full/Agda/Main.hs, dist/build/Agda/Main.o, dist/build/Agda/Main.dyn_o )
       > Preprocessing executable 'agda' for Agda-2.6.2.1..
       > Building executable 'agda' for Agda-2.6.2.1..
       > [1 of 1] Compiling Main             ( src/main/Main.hs, dist/build/agda/agda-tmp/Main.o )
       > Linking dist/build/agda/agda ...
       > /nix/store/km02igh4pshp20d0wn89rf5jjfxcm8v5-clang-wrapper-11.1.0/bin/ld: line 256: 44923 Segmentation fault: 11  /nix/store/diz9chv9r9m3pv9rzi7g3p2iq8vgsmr3-cctools-binutils-darwin-949.0.1/bin/ld ${extraBefore+"${extraBefore[@]}"} ${params+"${params[@]}"} ${extraAfter+"${extraAfter[@]}"}
       > clang-11: error: linker command failed with exit code 139 (use -v to see invocation)
       > `cc' failed in phase `Linker'. (Exit code: 139)
       For full logs, run 'nix log /nix/store/8zr9cl44sdnr6mg70g3s3xkvl4dkdi0c-Agda-2.6.2.1.drv'.

```

**Comment by Jake-Gillberg** [comment] 2022-07-07 14:15
For anyone on M1 experiencing this issue, the overriding with the x86_64-darwin package works with Rosetta.

**Comment by CrepeGoat** [comment] 2022-07-09 16:46
> For anyone on M1 experiencing this issue, overriding with the x86_64-darwin package works with Rosetta.

A+ suggestion! In case others (like me 😅) want to try this but aren't familiar with how, here's a blog that talks about configuring nix to build x86_64 programs: https://evanrelf.com/building-x86-64-packages-with-nix-on-apple-silicon

**Comment by denizdogan** [comment] 2022-09-26 21:49
For what it's worth, this is happening to me too, with Ormolu:

```
[11 of 11] Compiling Main             ( tests/Spec.hs, dist/build/tests/tests-tmp/Main.o, dist/build/tests/tests-tmp/Main.dyn_o )
Linking dist/build/tests/tests ...
/nix/store/48py6zrawzim9ghrnkqwm36jl4j1l23x-clang-wrapper-11.1.0/bin/ld: line 256: 70672 Segmentation fault: 11  /nix/store/5wvlj00dr22ivh210b18ccv1i60h6c1q-cctools-binutils-darwin-949.0.1/bin/ld ${extraBefore+"${extraBefore[@]}"} ${params+"${params[@]}"} ${extraAfter+"${extraAfter[@]}"}
clang-11: error: linker command failed with exit code 139 (use -v to see invocation)
`cc' failed in phase `Linker'. (Exit code: 139)
```

It's nice that there's the workaround of compiling for x86_64, but is there really no other way?

**Comment by veprbl** [comment] 2022-09-26 22:20
@denizdogan Please post a stacktrace. You can find it using Other -> Console -> Crash Reports.

**Comment by denizdogan** [comment] 2022-09-26 22:32
[ld-2022-09-27-003114.txt](https://github.com/NixOS/nixpkgs/files/9650036/ld-2022-09-27-003114.txt)

@veprbl

**Comment by turion** [comment] 2023-01-12 20:46
2.6.2.2 failed as well on aarch64-darwin: https://logs.nix.ci/?key=nixos/nixpkgs.210418&attempt_id=fa802878-e6af-4d7a-b890-16bc01482839

**Comment by wildsebastian** [comment] 2023-01-13 11:50
I figured out that it works when I remove `-foptimise-heavily` from https://github.com/NixOS/nixpkgs/blob/518f09f2d0e8829c3ef77c0f535df309f49ed6d9/pkgs/development/haskell-modules/configuration-nix.nix#L943. I do not know enough to explain why this is the case.

**Comment by sternenseemann** [comment] 2023-01-15 18:52
My theory would be that the GHC flags that flag enables cause the object files to become much bigger which cctools ld can't always deal with.

**Comment by domenkozar** [comment] 2023-01-20 09:23
Looking at https://github.com/agda/agda/blob/master/Agda.cabal#L658, this could be a bug in GHC. 

@angerman have you seen this before?

**Comment by domenkozar** [comment] 2023-01-20 11:39
I've noticed that GHC doesn't use llvmPackages supplied to provide clang, but it uses whatever stdenv provides. That's why it's using clang_11 in these builds.

**Comment by sternenseemann** [comment] 2023-01-20 11:51
That should not matter, as aarch64-darwin doesn’t use the LLVM backend. Under normal circumstances you’d also use whatever clang comes with the XCode SDK.On 20. Jan 2023, at 12:39, Domen Kožar ***@***.***> wrote:﻿
I've noticed that GHC doesn't use llvmPackages supplied to provide clang, but it uses whatever stdenv provides. That's why it's using clang_11 in these builds.

**Comment by domenkozar** [comment] 2023-01-20 12:44
@sternenseemann any ideas how to tell GHC to pick linker from a newer llvmPackages? I've tried passing a newer stdenv to generic builder, but that doesn't help.

**Comment by sternenseemann** [comment] 2023-01-20 18:16
@domenkozar GHC gets no linker from `llvmPackages` – on macOS it'll use `cctools`' `ld` which has nothing to do with lld or LLVM.

**Comment by wildsebastian** [comment] 2023-01-22 10:53
I played around with this a little bit more and I have some more information. I am missing a few links there to get the full picture out of this.
On a side note, the `-foptimise-heavily` flag sets these two ghc flags: `-fexpose-all-unfoldings` and `-fspecialise-aggressively`. One by itself works, using both causes `ld` to segfault.
More interestingly, when I use `/usr/bin/ld` it works. I tried this by modifying `clang-wrapper-11.1.0/bin/ld` in my nix store.
It segfaults, when `cctools-binutils-darwin-973.0.1/bin/ld` is used, which is a symlink to `cctools-port-973.0.1/bin/ld`.
I had a look at both executables with `file` and there are two differences in the flags.
`/usr/bin/ld`: flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>
`cctools-port-973.0.1/bin/ld`: flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE>
Currently my guess is a bug in https://github.com/tpoechtrager/cctools-port. Does anyone have a suggestion, where it would make sense to dig deeper?

(Sorry for some information that might be obvious to more experienced contributors/users, but this is part of my notes and I do not know about all the implementation detail)

**Comment by veprbl** [comment] 2023-01-22 17:19
@wildsebastian Maybe try with Apple's cctools #157628

**Comment by domenkozar** [comment] 2023-01-22 23:26
@veprbl it doesn't build on aarch64-darwin for me.

**Comment by domenkozar** [comment] 2023-01-23 14:40
I'm currently trying to upgrade cctools to see if that will fix it, otherwise using the apple version might be our only choice (and it needs to be fixed to build on aarch64-darwin).

**Comment by domenkozar** [comment] 2023-01-24 14:06
Still segfaults, I sadly don't have time to look into fixing the build of apple cctools.

**Comment by cidkidnix** [comment] 2023-01-26 17:26
Currently looking into the build issues with aarch64-darwin of apple-cctools. Also the cctools-port stack trace suggests that it might be stack smashing, though I haven't peered into the code too much

**Comment by reckenrode** [comment] 2023-01-31 01:17
I made some progress building cctools-apple on aarch64-darwin, but I ran into some issues.

* The build on aarch64-darwin is pulling in ncurses from nixpkgs, which conflicts with the headers in the SDK;
* `ld64` needs `dlyd` and `CommonCrypto` added as `buildInputs`;
* `ld64` also requires several items that are only available in the source SDK in nixpkgs: `CrashReporterClient.h` and `corecrypto`.

**Comment by domenkozar** [comment] 2023-02-08 08:48
Could we just use SDK 11?

**Comment by reckenrode** [comment] 2023-05-06 13:30
> Could we just use SDK 11?

Sorry about the delayed response. I missed the notification. Unfortunately, no.

The issues identified above are with the 11.0 SDK. I was able to make some progress by hacking at the SDK in the store, but that’s only good enough to see if it’s possible to build. The 11.0 SDK would need updated to fix those before cctools could be built.

#229210 is a PR to add the 13.3 SDK. I’ve mentioned those issues in that PR in the hope they can be addressed for that SDK, then they can be backported back to the 11.0 SDK if/when it’s refactored.

**Comment by reckenrode** [comment] 2023-05-23 21:06
As part of my testing for #229786, I attempted to build Agda. It builds now. While I have replaced some of cctools with its LLVM equivalents, I didn’t change the linker. I don’t know why it builds now, but I’ll take it.

```shell
$ nix build .#haskellPackages.Agda --out-link result-agda
$ ./result-agda/bin/agda --version
Agda version 2.6.3
$ file ./result-agda/bin/agda
./result-agda/bin/agda: Mach-O 64-bit executable arm64
```

**Comment by reckenrode** [comment] 2023-05-23 21:07
Actually, it looks like it builds on master now, so it’s definitely unrelated. Still, that’s good news.

**Comment by sternenseemann** [comment] 2023-05-24 11:46
@reckenrode The crash is not very consistent. It seemed reproducible for a single nixpkgs revision (if I recall correctly), but would come and go over time due to seemingly unrelated changes. So good news is only tentative…

**Comment by cidkidnix** [comment] 2023-06-09 13:27
Working with some ios64 stuff I've run into this, what seems to fix it every-time for me is passing the compiler "-fwhole-archive-libs" which should stop GHC itself from (dead?, iirc) stripping the resulting executable. 
I don't have a regular aarch64-darwin system to actually check if it works for M1/M2 at the moment but it fixed all iOS builds for me!

**Comment by arjunkathuria** [comment] 2023-06-09 14:13
Hi @cidkidnix , thanks for taking the time to reply to this. I'll try that and see if that fixes things for me.

**Comment by john-rodewald** [comment] 2023-06-12 14:21
> -fwhole-archive-libs

I ran into this segfault trying to compile Hasura on aarch64 and this flag was the final missing puzzle piece. Thank you very much!

**Comment by sternenseemann** [comment] 2023-06-12 14:32
Interesting, we could consider enabling this by default via `haskellPackages.mkDerivation` on `aarch64-darwin`.

Can you compare output size of built libraries with and without this flag? Stripping efficiency would be interesting to know for making this decision.

**Comment by cidkidnix** [comment] 2023-06-12 23:26
```diff
diff --git a/compiler/GHC/Linker/Static.hs b/compiler/GHC/Linker/Static.hs
index aa51a2b7d6..eac801617b 100644
--- a/compiler/GHC/Linker/Static.hs
+++ b/compiler/GHC/Linker/Static.hs
@@ -135,7 +135,7 @@ linkBinary' staticLink logger tmpfs dflags unit_env o_files dep_units = do
     let
       dead_strip
         | gopt Opt_WholeArchiveHsLibs dflags = []
-        | otherwise = if osSubsectionsViaSymbols (platformOS platform)
+        | otherwise = if osSubsectionsViaSymbols platform
                         then ["-Wl,-dead_strip"]
                         else []
     let lib_paths = libraryPaths dflags
diff --git a/compiler/GHC/Platform.hs b/compiler/GHC/Platform.hs
index a5a609d252..e1fcbb1aa1 100644
--- a/compiler/GHC/Platform.hs
+++ b/compiler/GHC/Platform.hs
@@ -227,9 +227,11 @@ osUsesFrameworks _        = False
 platformUsesFrameworks :: Platform -> Bool
 platformUsesFrameworks = osUsesFrameworks . platformOS

-osSubsectionsViaSymbols :: OS -> Bool
-osSubsectionsViaSymbols OSDarwin = True
-osSubsectionsViaSymbols _        = False
+osSubsectionsViaSymbols :: Platform -> Bool
+osSubsectionsViaSymbols plat = case (platformArch plat, platformOS plat) of
+                                 (ArchAArch64, OSDarwin) -> False
+                                 (_, OSDarwin) -> True
+                                 (_, _) -> False

 -- | Minimum representable Int value for the given platform
 platformMinInt :: Platform -> Integer
 ```

 Here's the patch based on GHC master that *should* fix the linking issues on aarch64-darwin. I think it should work for any GHC newer than ~3years

**Comment by yan-sh** [comment] 2023-08-24 16:59
This problem is also actual to me .-. After some updates my project has stopped builing with an error:

`/nix/store/7v4rbxd8i0hsk2hgy8jnd4qn9vk89a86-clang-wrapper-11.1.0/bin/ld: line 269: 30615 Segmentation fault: 11  /nix/store/hwkh5cw8lfm0yhg7amvl4ffcjsvz07l6-cctools-binutils-darwin-973.0.1/bin/ld @<(printf "%q\n" ${extraBefore+"${extraBefore[@]}"} ${params+"${params[@]}"} ${extraAfter+"${extraAfter[@]}"})
clang-11: error: linker command failed with exit code 139 (use -v to see invocation)
ghc: `cc' failed in phase `Linker'. (Exit code: 139)`

I've tried building with 9.4.5 and 9.4.6 version and got same result. But yesterday my project  was building that is weird. I've tried rollback my nix-channel but it had no effect.

My setup: mac m2, ghc 9.4.5/9.4.6

**Comment by reckenrode** [comment] 2023-08-24 17:07
What happens if you run the linker manually directly with no input? If it still crashes, something may have happened to the codesigning.

**Comment by yan-sh** [comment] 2023-08-24 17:12
> What happens if you run the linker manually with no input? If it still crashes, something may have happened to the codesigning.

Do you mean just try to run `ld`? If yes then:

`$ ld
Undefined symbols for architecture arm64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture arm64`

**Comment by reckenrode** [comment] 2023-08-24 17:34
> Do you mean just try to run `ld`?

Yep, thanks. Looks like it works, so it’s not a codesigning issue.

**Comment by yan-sh** [comment] 2023-08-24 17:57
I've read the thread and try pass the option '-fwhole-archive-hs-libs' to GHC and it kind a works :) Thanks all for help!

**Comment by reckenrode** [comment] 2024-04-13 13:32
I’m working on updating cctools and ld64 to the latest versions. These versions are using Apple’s upstream sources and match the versions of those tools included with Xcode 15.3. If _those_ don’t work, then I don’t know.

More details on Discourse: https://discourse.nixos.org/t/darwin-updates-news/42249/10

**Comment by alexfmpe** [comment] 2024-04-23 19:58
Had this same error message on an executable on a M1 with ghc 9.4.8 and package set from recent nixpkgs. 

Both `-fwhole-archive-hs-libs` and `-dynamic` make `nix-shell --run "cabal run"` work, but if `-dynamic` is present then running the executable coming out of the nix-build fails with an rpath error when searching for the package's library

```
dyld[23803]: Library not loaded: @rpath/libHS<package>-0.1-<fingerprint-thing>-ghc9.4.8.dylib
  Referenced from: <some-uuid-thing> /nix/store/<hash>-<package>-0.1/bin/<executable>
  Reason: tried: <lotsa places including mostly variations of /nix/store/very-big-hash-some-dependency>
```
Poking around with `otool -h` I see the executable coming directly from `cabal run` has a 
```
Load command 24
          cmd LC_RPATH
      cmdsize 128
         path <project-path>/dist-newstyle/<blabla>/build
```
and indeed that build directory contain a `libHS<package>-0.1-inplace-ghc9.4.8.dylib` (no fingerprint) which matches what I see in `otool -L`.

As for the `nix-build` executable, `otool -l` shows a `@rpath/` entry where the .dylib name contains a fingerprint but not only am I short one `cmd LC_RPATH` for an external dependency (which I just noticed is not actually being used), but the one for the library is pointing to `path /private/tmp/nix-build-<package>-0.1.drv-0/<executable>dist/build`.

It seems like there's two bugs here, where both flags workaround the first bug that @cidkidnix has a patch for above, but avoiding with `dynamic` triggers a separate bug where the rpath is pointing at an ephemeral build directory?

**Comment by reckenrode** [comment] 2024-04-23 23:46
> Had this same error message on an executable on a M1 with ghc 9.4.8 and package set from recent nixpkgs.

Is this reproducible, and is there a public repo? I’d like to see if it crashes on my ld64 update branch.

**Comment by alexfmpe** [comment] 2024-04-24 05:47
@reckenrode thanks for looking into this - here's a small repro using ghc 9.6 and the `haskell-updates` branch - everything should be cached
https://github.com/alexfmpe/reproducible-segfault-rpath

Doing `nix-build`hits the seg fault, uncommenting `-dynamic` triggers the rpath error when running with `$(nix-build)/bin/a` but if you *instead* uncomment `-fwhole-archive-hs-libs` it should work.

https://github.com/alexfmpe/reproducible-segfault-rpath/blob/2295ad417b963feee9e85105a800d7bbfbc2fe44/a/a.cabal#L21-L25

**Comment by reckenrode** [comment] 2024-04-24 12:30
@alexfmpe Thanks for the repo. I cloned it and confirmed the crash with the haskell-updates branch, then I pointed it at my local ld64 update branch.

```shell
$ cabal build --project-file cabal.project all
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
Resolving dependencies...
Build profile: -w ghc-9.6.4 -O1
In order, the following will be built (use -v for more details):
 - a-0.1 (lib) (first run)
 - a-0.1 (exe:a) (first run)
Configuring library for a-0.1..
Preprocessing library for a-0.1..
Building library for a-0.1..
[1 of 1] Compiling A                ( src/A.hs, /Users/reckenrode/Developer/tmp/reproducible-segfault-rpath/dist-newstyle/build/aarch64-osx/ghc-9.6.4/a-0.1/build/A.o, /Users/reckenrode/Developer/tmp/reproducible-segfault-rpath/dist-newstyle/build/aarch64-osx/ghc-9.6.4/a-0.1/build/A.dyn_o )
Configuring executable 'a' for a-0.1..
Preprocessing executable 'a' for a-0.1..
Building executable 'a' for a-0.1..
[1 of 1] Compiling Main             ( src-bin/main.hs, /Users/reckenrode/Developer/tmp/reproducible-segfault-rpath/dist-newstyle/build/aarch64-osx/ghc-9.6.4/a-0.1/x/a/build/a/a-tmp/Main.o )
[2 of 2] Linking /Users/reckenrode/Developer/tmp/reproducible-segfault-rpath/dist-newstyle/build/aarch64-osx/ghc-9.6.4/a-0.1/x/a/build/a/a
$ cabal run --project-file cabal.project all
it worked
```

It could be the version jump (going from 609 to 951.9) or the source (switching to Apple’s [OSS release][ld64] from [cctools-port][cctools-port]), but I suspect the issue is cctools-port does not appear to build ld64 with `-Wl,-stack_size,0x10000000`. Both the Meson build system I use in my update and Apple’s [Xcode project][1] use that option to expand the stack from 8 MiB to 256 MiB. Having a significantly larger stack would presumably avoid the stack smashing that was observed in https://github.com/NixOS/nixpkgs/issues/149692#issuecomment-1405348679.

[ld64]: https://github.com/apple-oss-distributions/ld64
[cctools-port]: https://github.com/tpoechtrager/cctools-port
[1]: https://github.com/apple-oss-distributions/ld64/blob/47f477cb721755419018f7530038b272e9d0cdea/ld64.xcodeproj/project.pbxproj#L1219

**Comment by alexfmpe** [comment] 2024-04-25 22:48
> suspect the issue is cctools-port does not appear to build ld64 with -Wl,-stack_size,0x10000000

Plausible, since my repro seems to vanish if I don't import from meaty dependencies.
Does the rpath issue persist in your branch?

**Comment by alexfmpe** [comment] 2024-04-26 19:58
> confirmed the crash with the haskell-updates branch, then I pointed it at my local ld64 update branch.

Indeed, I got the same results.


> Does the rpath issue persist in your branch?
It does, and it seems for dynamic linking I should instead be using 
https://cabal.readthedocs.io/en/3.4/cabal-project.html?highlight=enabl#cfg-flag---enable-executable-dynamic

**Comment by reckenrode** [comment] 2024-04-26 20:03
FWIW, if you’re using the ld64 branch in my nixpkgs repo, it’s a bit old. ld64 should be fine, but it’s missing some additional compatibility work I’ve done. Once I’ve built the Darwin channel blockers successfully, I plan to open a draft PR for feedback.

**Comment by bacchanalia** [comment] 2024-06-15 00:17
A note to anyone thinking of using `-fwhole-archive-hs-libs` as a workaround: the debug symbols in the executable will cause the build dependencies to also be added as runtime dependencies by nix.

**Comment by reckenrode** [comment] 2024-07-28 05:59
Unfortunately, the test case @alexfmpe provided still crashes on staging-next (with the ld64 upgrade) with the workaround disabled. The [stack trace][1] is similar to the one posted in https://github.com/NixOS/nixpkgs/issues/149692#issuecomment-1258713020, which points to the following code as the likely culprit.

https://github.com/apple-oss-distributions/ld64/blob/47f477cb721755419018f7530038b272e9d0cdea/src/ld/Resolver.cpp#L1180-L1198

Next I want to try to get it into a debugger, so I see whether it’s infinitely recursing or the same atom, or if this is a pathological case in ld64 that GHC is triggering.

[1]: https://gist.github.com/reckenrode/0b9c90692f52380672205fe20edf1b41

**Comment by reckenrode** [comment] 2024-07-28 13:17
If someone can find a reproducible test case after the ld64 upgrade, please reopen. If I have to do it, I’ll rewrite the recursion to remove it, but the larger default stack size should make this a non-issue now.

Closed via https://github.com/NixOS/nixpkgs/pull/307880.

**Closed by reckenrode** 2024-07-28 13:17 UTC
Labels: 0.kind: bug, 6.topic: darwin, 6.topic: haskell, 6.topic: agda
