### ISSUE TITLE
Package request: Wix Codux

### ISSUE THREAD

**Issue by mbledkowski** [NixOS/nixpkgs#226884] opened 2023-04-18 16:02 UTC
**Project description**

Visually edit projects side-by-side with your code editor. See every change reflected instantly and get your work done faster. 

**Metadata**

* homepage URL: https://www.codux.com/
* source URL: -
* license: Propriatary
* platforms: linux, darwin

**Comment by felschr** [comment] 2023-04-18 19:33
Duplicate of #226878

**Closed by felschr** 2023-04-18 19:33 UTC
Labels: 0.kind: packaging request
