### ISSUE TITLE
Download for oraclejdk8 fails

### ISSUE THREAD

**Issue by nessdoor** [NixOS/nixpkgs#193053] opened 2022-09-26 15:41 UTC
### Steps To Reproduce
1. nix-build -A pkgs.oraclejdk8

### Build log
```
***
Unfortunately, we cannot download file jdk-8u281-linux-x64.tar.gz automatically.
Please go to http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-21>
using either
  nix-store --add-fixed sha256 jdk-8u281-linux-x64.tar.gz
or
  nix-prefetch-url --type sha256 file:///path/to/jdk-8u281-linux-x64.tar.gz

***
```

### Additional context
Discovered while trying to build the Processing derivation. It looks like the download URL for the Oracle JDK has been changed, breaking all packages relying on an upstream Oracle-branded JDK version 8.

### Notify maintainers
@lourkeur (last person who touched the relevant file)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.60, NixOS, 22.05 (Quokka), 22.05.3242.72783a2d0db`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"home-manager-22.05.tar.gz, nixos-22.05, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by lourkeur** [comment] 2022-09-26 21:27
Strictly speaking this is intended behaviour: Nix stopped and printed this message, which it is supposed to do unless the correct file is manually downloaded. OTOH it's asking for an obsolete build, which you can nonetheless find under [Java Archive](https://www.oracle.com/java/technologies/downloads/archive/). (requires creating an account with Oracle either way) Should I treat this as an out-of-date package report then?

ftr I was able to reproduce the issue as well as download and add to the Nix store the file in question.

**Comment by nessdoor** [comment] 2022-09-27 18:21
I would say that updating the package to the latest patch level (which should be freely available without an Oracle account) would save some trouble for whoever is trying to build the dependent packages.

I don't know the exact policy for tagging these issues, but this out-of-date download link is not merely making you build an outdated package, it's blocking your build process (which is OK for my case, but a little bit less desirable if part of an auto-upgrade process on a remote production machine).

Lastly, I don't want to sound like the lazy/radical one here, but I just wanted to carry out some quick work on Processing for a friend, not open an account with Oracle.

P.S. Someone should really update the Processing package, _that_ is outdated.

**Comment by wamserma** [comment] 2022-10-23 19:38
> I would say that updating the package to the latest patch level (which should be freely available without an Oracle account) would save some trouble for whoever is trying to build the dependent packages.

But Oracle requires an account even for the latest version of oraclejdk8...

**Comment by nessdoor** [comment] 2022-10-23 22:57
Oh my, didn't notice that at all.
Well, in that case I think I should close the issue, but this could remain a little bit of a problem that maybe we should keep track of.

Will ask on Discourse.

**Comment by asbachb** [comment] 2022-10-30 19:49
+1 for closing this issue. I don't think this could be handled in another way. It's a licensing problem.

**Closed** 2022-10-30 19:56 UTC
Labels: 6.topic: reproducible builds, 6.topic: java, 0.kind: build failure
