### ISSUE TITLE
firefox fails to build, blocks 20.09 and unstable

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#103070] opened 2020-11-07 11:00 UTC
**Describe the bug**
https://hydra.nixos.org/build/129986842

**Additional context**
```
   Compiling gkrust v0.1.0 (/build/firefox-82.0.2/toolkit/library/rust)
     Running `CARGO=/nix/store/2ppmp5a34c8p1jyck57vq7ag72k2c19b-cargo-1.44.1/bin/.cargo-wrapped CARGO_MANIFEST_DIR=/build/firefox-82.0.2/toolkit/library/rust CARGO_PKG_AUTHORS='nobody@mozilla.org' CARGO_PKG_DESCRIPTION='Rust code for libxul' CARGO_PKG_HOMEPAGE= CARGO_PKG_NAME=gkrust CARGO_PKG_REPOSITORY= CARGO_PKG_VERSION=0.1.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE= LD_LIBRARY_PATH='/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/release/deps:/nix/store/dmqhaa7wh4r3x1vfzvcnrxc7sb422jk0-rustc-1.44.1/lib' /nix/store/dmqhaa7wh4r3x1vfzvcnrxc7sb422jk0-rustc-1.44.1/bin/rustc --crate-name gkrust toolkit/library/rust/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type staticlib --emit=dep-info,link -C opt-level=2 -C panic=abort -Clto --cfg 'feature="cubeb-remoting"' --cfg 'feature="cubeb_pulse_rust"' --cfg 'feature="gecko_profiler"' --cfg 'feature="gecko_profiler_parse_elf"' --cfg 'feature="moz_memory"' --cfg 'feature="moz_places"' --cfg 'feature="new_cert_storage"' --cfg 'feature="quantum_render"' --cfg 'feature="webgpu"' --cfg 'feature="webrtc"' --cfg 'feature="with_dbus"' -C metadata=13e7fecae53e3ed1 -C extra-filename=-13e7fecae53e3ed1 --out-dir /build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -C linker=/build/firefox-82.0.2/build/cargo-linker -L dependency=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/release/deps -L dependency=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/release/deps --extern gkrust_shared=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/release/deps/libgkrust_shared-4e879b5c971ad03f.rlib --extern mozglue_static=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/release/deps/libmozglue_static-4afb20b8933f2e32.rlib --extern mozilla_central_workspace_hack=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/release/deps/libmozilla_central_workspace_hack-d36152670e96efd4.rlib --extern swgl=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/release/deps/libswgl-0c95870e9a3896a7.rlib -C opt-level=2 -C debuginfo=2 --cap-lints warn -C codegen-units=1 -L native=/nix/store/rxapwgz2hrj5y7d8wrqkhw6l7446f23c-dbus-1.12.20-lib/lib -L native=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/release/build/lmdb-rkv-sys-a4c298427eebc317/out -L native=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/release/build/mozglue-static-9d43252c4b8169a5/out -L native=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/dist/bin -L native=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/security/nss/lib/nss/nss_nss3 -L native=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/security/nss/lib/ssl/ssl_ssl3 -L native=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/config/external/nspr/pr -L native=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/release/build/swgl-b996e405f0dade1a/out`
error: could not compile `gkrust`.

Caused by:
  process didn't exit successfully: `CARGO=/nix/store/2ppmp5a34c8p1jyck57vq7ag72k2c19b-cargo-1.44.1/bin/.cargo-wrapped CARGO_MANIFEST_DIR=/build/firefox-82.0.2/toolkit/library/rust CARGO_PKG_AUTHORS='nobody@mozilla.org' CARGO_PKG_DESCRIPTION='Rust code for libxul' CARGO_PKG_HOMEPAGE= CARGO_PKG_NAME=gkrust CARGO_PKG_REPOSITORY= CARGO_PKG_VERSION=0.1.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE= LD_LIBRARY_PATH='/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/release/deps:/nix/store/dmqhaa7wh4r3x1vfzvcnrxc7sb422jk0-rustc-1.44.1/lib' /nix/store/dmqhaa7wh4r3x1vfzvcnrxc7sb422jk0-rustc-1.44.1/bin/rustc --crate-name gkrust toolkit/library/rust/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type staticlib --emit=dep-info,link -C opt-level=2 -C panic=abort -Clto --cfg 'feature="cubeb-remoting"' --cfg 'feature="cubeb_pulse_rust"' --cfg 'feature="gecko_profiler"' --cfg 'feature="gecko_profiler_parse_elf"' --cfg 'feature="moz_memory"' --cfg 'feature="moz_places"' --cfg 'feature="new_cert_storage"' --cfg 'feature="quantum_render"' --cfg 'feature="webgpu"' --cfg 'feature="webrtc"' --cfg 'feature="with_dbus"' -C metadata=13e7fecae53e3ed1 -C extra-filename=-13e7fecae53e3ed1 --out-dir /build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -C linker=/build/firefox-82.0.2/build/cargo-linker -L dependency=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/release/deps -L dependency=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/release/deps --extern gkrust_shared=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/release/deps/libgkrust_shared-4e879b5c971ad03f.rlib --extern mozglue_static=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/release/deps/libmozglue_static-4afb20b8933f2e32.rlib --extern mozilla_central_workspace_hack=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/release/deps/libmozilla_central_workspace_hack-d36152670e96efd4.rlib --extern swgl=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/release/deps/libswgl-0c95870e9a3896a7.rlib -C opt-level=2 -C debuginfo=2 --cap-lints warn -C codegen-units=1 -L native=/nix/store/rxapwgz2hrj5y7d8wrqkhw6l7446f23c-dbus-1.12.20-lib/lib -L native=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/release/build/lmdb-rkv-sys-a4c298427eebc317/out -L native=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/release/build/mozglue-static-9d43252c4b8169a5/out -L native=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/dist/bin -L native=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/security/nss/lib/nss/nss_nss3 -L native=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/security/nss/lib/ssl/ssl_ssl3 -L native=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/config/external/nspr/pr -L native=/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/release/build/swgl-b996e405f0dade1a/out` (signal: 9, SIGKILL: kill)
make[3]: *** [/build/firefox-82.0.2/config/makefiles/rust.mk:303: force-cargo-library-build] Error 101
make[3]: Leaving directory '/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/toolkit/library/rust'
make[2]: *** [/build/firefox-82.0.2/config/recurse.mk:72: toolkit/library/rust/target] Error 2
make[2]: Leaving directory '/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu'
make[1]: *** [/build/firefox-82.0.2/config/recurse.mk:34: compile] Error 2
make[1]: Leaving directory '/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu'
make: *** [/build/firefox-82.0.2/config/rules.mk:384: default] Error 2
builder for '/nix/store/8f54kvfzfncqb32p05dl5gdf103bwfq2-firefox-unwrapped-82.0.2.drv' failed with exit code 2
```

**Notify maintainers**
cc @andir

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment] 2020-11-07 12:01
Reproduced the issue locally.

**Comment by vcunat** [comment] 2020-11-07 13:53
It seems OK on master: https://hydra.nixos.org/job/nixpkgs/trunk/firefox-unwrapped.x86_64-linux

**Comment by vcunat** [comment] 2020-11-07 13:55
BTW, `firefox-esr` on master did have a problem: eb3fd61bb6f

**Comment by andir** [comment] 2020-11-07 15:45
@Fridh can you describe your build host? I've not had any luck reproducing the build error on my machines.

**Comment by aristidb** [comment] 2020-11-07 15:49
I can build firefox locally too, using the release-20.09 branch as of commit e79793fd8596d193e09336b2d0d2629e3b8d4888 

```
...
checking for references to /build/ in /nix/store/b6jdiba838arrwap0cgf4qv91n0vy7pm-firefox-unwrapped-82.0.2...
running install tests
Mozilla Firefox 82.0.2
building '/nix/store/nf0idfzgdl0xfw3q7vydy7xcy2rw84yv-firefox-82.0.2.drv'...
/nix/store/zj8i7q9sx3j4mw6m72jymj3zy1ry1xyr-firefox-82.0.2
```

On master it is even in the binary cache.

**Comment by FRidh** [comment] 2020-11-07 15:51
Guess I made a mistake somewhere.

**Comment by aristidb** [comment] 2020-11-08 11:33
I'll close this issue. Reopen it if you can give more details under which circumstances it can be reproduced.

**Comment by andir** [comment] 2020-11-24 08:46
I think this is still valid. I often have to restart the firefox jobs on hydra. I wonder if it might just be that new single-core linking phase (of rust code?) that I've seen when doing local builds. I've been wondering if firefox should get the `big-parallel` feature so we get a builder that is less packed with other jobs at the same time.

**Comment by vcunat** [comment] 2020-11-24 10:37
I also did some FF restarts on Hydra recently.

**Comment by FRidh** [comment] 2020-11-28 08:05
Firefox and thunderbird need to be restarted often, just as several nixos tests that time out.

Removed the label because it is not *currently* channel blocking.

**Comment by schmittlauch** [comment] 2020-11-29 16:32
@fridh Do they need to be restarted because the build actually hangs, or are theses packages just so resource intensive that the build times out sometimes before they have finished to build?
While investigating #104678 I just discovered that the phenomenon of having to build thunderbird locally is usually caused by thunderbird builds timing out, causing the channel to be advanced without a binary-cached thunderbird. https://hydra.nixos.org/job/nixos/release-20.09/nixpkgs.thunderbird.x86_64-linux

Maybe it could help to increase the timeout limit for these specific builds.

**Comment by vcunat** [comment] 2020-12-11 10:07
I think it will be OK now.  Reopen if the failures start happening again.

**Closed by vcunat** 2020-12-11 10:07 UTC
Labels: 0.kind: bug
