### ISSUE TITLE
git does not work inside of nix-shell

### ISSUE THREAD

**Issue by charles-cooper** [NixOS/nixpkgs#16031] opened 2016-06-07 01:28 UTC
## Issue description
`git` does not work in `nix-shell`. This seems to be an SSL related issue (cf. https://github.com/NixOS/nixpkgs/issues/15933, https://github.com/NixOS/nixpkgs/pull/15571, https://github.com/NixOS/nixpkgs/issues/13744).

### Steps to reproduce
(I have both `git` and `stack` installed in the system-wide environment.)
In a Haskell project:
```
[charles@marmoset:~/machine]$ nix-shell -p git
[nix-shell:~/machine]$ stack build
Updating package index Hackage (mirrored at https://github.com/commercialhaskell                                                                                Running /nix/store/jhn7046bggnbjypibwhz7y014b89azcl-git-2.8.3/bin/git clone https://github.com/commercialhaskell/all-cabal-hashes.git all-cabal-hashes/ --depth 1 -b display in directory /home/charles/.stack/indices/Hackage/git-update/ exited with ExitFailure 128

Cloning into 'all-cabal-hashes'...
fatal: unable to access 'https://github.com/commercialhaskell/all-cabal-hashes.git/': error setting certificate verify locations:
  CAfile: /no-cert-file.crt
  CApath: none
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
```
[nix-shell:~/machine]$ nixos-version 
16.09pre84674.fbde3a7 (Flounder)
```
* Nix version: (run `nix-env --version`)
```
[nix-shell:~/machine]$ nix-env --version
nix-env (Nix) 1.11.2
```
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
`"16.09pre84674.fbde3a7"`

**Comment by mogorman** [comment] 2016-06-07 02:18
```
shellHook = ''
    export SSL_CERT_FILE=${cacert}/etc/ssl/certs/ca-bundle.crt
'';
```
 
will fix your problem

**Comment by FRidh** [comment] 2016-06-07 07:22
You can indeed fix it for now by setting the `shellHook` or, in the case you're running NixOS, by setting `  environment.variables."SSL_CERT_FILE" = "/etc/ssl/certs/ca-bundle.crt";`.
Because this is a duplicate of the issues you refer to I am closing this.

**Closed by FRidh** 2016-06-07 07:22 UTC
