### ISSUE TITLE
Xmonad is out of date

### ISSUE THREAD

**Issue by darealdrzoidberg** [NixOS/nixpkgs#145730] opened 2021-11-13 10:27 UTC
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 0.15
desired version: 0.17

###### Notify maintainers

maintainers:

###### Note for maintainers

Please tag this issue in your PR.

**Comment by jyooru** [comment] 2021-11-13 10:39
maintainer: @peti

**Comment by prusnak** [comment] 2021-11-13 15:05
There is already `xmonad_0_17_0` in hackage packages.

**Comment by jakobneufeld** [comment] 2021-11-13 23:35
Yes but how do I use it with services.x11.windowManager.xmonad

**Comment by 174BD7E8** [comment] 2021-11-15 13:33
@jakobneufeld https://search.nixos.org/packages?channel=unstable&show=haskellPackages.xmonad_0_17_0&from=0&size=50&sort=relevance&type=packages&query=xmonad

**Comment by peti** [comment] 2021-11-21 18:16
Ping @NixOS/haskell.

**Comment by sternenseemann** [comment] 2021-11-21 18:43
> How do I use xmonad _0_17_0 services.x11.windowManager.xmonad

It doesn't seem to be possible easily with how the module is implemented at the moment. You could try using an overlay like this:


```nix
self: super: {
  haskellPackages = super.haskellPackages.override {
    overrides = hself: hsuper: {
     xmonad = self.xmonad_0_17_0;
     xmonad-contrib = self.xmonad-contrib_0_17_0;
    };
  };
}
```

The default xmonad version will change as soon as stackage (lts atm) changes it. We could contemplate ignoring stackage for xmonad to have a more cutting edge version, but this likely means more maintenance work.

**Comment by cdepillabout** [comment] 2021-12-31 01:16
I'm going to close this, since it is currently "by design", since we pin to packages in stackage, and xmonad is in stackage.

**Closed by cdepillabout** 2021-12-31 01:16 UTC
Labels: 0.kind: question, 6.topic: haskell
