### ISSUE TITLE
Build failure: waybar (nixos-unstable)

### ISSUE THREAD

**Issue by catarial** [NixOS/nixpkgs#297518] opened 2024-03-20 19:38 UTC
### Steps To Reproduce

1. build waybar with latest nixpkgs rev as of writing

### Build log

```
l@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/5q3fdaixac9hv71rva2xal78l195lv4n-source
source root is source
/build/source /build
patching script interpreter paths in .
/build
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
mesonConfigurePhase flags: --prefix=/nix/store/77n7cw79znnsrdg5qxa3jv03m7h8pwrl-waybar-0.10.0 --libdir=/nix/store/77n7cw79znnsrdg5qxa3jv03m7h8pwrl-waybar-0.10.0/lib --libexecdir=/nix/store/77n7cw79znnsrdg5qxa3jv03m7h8pwrl-waybar-0.10.0/libexec --bindir=/nix/store/77n7cw79znnsrdg5qxa3jv03m7h8pwrl-waybar-0.10.0/bin --sbindir=/nix/store/77n7cw79znnsrdg5qxa3jv03m7h8pwrl-waybar-0.10.0/sbin --includedir=/nix/store/77n7cw79znnsrdg5qxa3jv03m7h8pwrl-waybar-0.10.0/include --mandir=/nix/store/77n7cw79znnsrdg5qxa3jv03m7h8pwrl-waybar-0.10.0/share/man --infodir=/nix/store/77n7cw79znnsrdg5qxa3jv03m7h8pwrl-waybar-0.10.0/share/info --localedir=/nix/store/77n7cw79znnsrdg5qxa3jv03m7h8pwrl-waybar-0.10.0/share/locale -Dauto_features=enabled -Dwrap_mode=nodownload --buildtype=plain -Dcava=enabled -Ddbusmenu-gtk=enabled -Djack=enabled -Dlibinput=enabled -Dlibnl=enabled -Dlibudev=enabled -Dman-pages=enabled -Dmpd=enabled -Dmpris=enabled -Dpulseaudio=enabled -Drfkill=enabled -Dsndio=enabled -Dsystemd=disabled -Dtests=enabled -Dupower_glib=enabled -Dwireplumber=enabled -Dexperimental=true
[1mThe Meson build system[0m
Version: 1.3.2
Source dir: [1m/build/source[0m
Build dir: [1m/build/source/build[0m
Build type: [1mnative build[0m
Project name: [1mwaybar[0m
Project version: [1m0.10.0[0m
C compiler for the host machine: [1mgcc[0m (gcc 13.2.0 "gcc (GCC) 13.2.0")
C linker for the host machine: [1mgcc[0m ld.bfd 2.41
C++ compiler for the host machine: [1mg++[0m (gcc 13.2.0 "g++ (GCC) 13.2.0")
C++ linker for the host machine: [1mg++[0m ld.bfd 2.41
Host machine cpu family: [1mx86_64[0m
Host machine cpu: [1mx86_64[0m
Compiler for C++ supports link arguments -lc++fs: [1;31mNO[0m 
Compiler for C++ supports link arguments -lstdc++fs: [1;32mYES[0m 
Program [1mgit[0m found: [1;31mNO[0m
Checking if "[1mnl_langinfo with _NL_TIME_WEEK_1STDAY, _NL_TIME_FIRST_WEEKDAY[0m" : links: [1;32mYES[0m 
Run-time dependency [1mthreads[0m found: [1;32mYES[0m
Found pkg-config: [1;32mYES[0m [1m(/nix/store/a3752l19hc76dmzh1wgrxbsxh6lfx67z-pkg-config-wrapper-0.29.2/bin/pkg-config)[0m [1;34m0.29.2[0m
Run-time dependency [1mfmt[0m found: [1;32mYES[0m [36m10.2.1[0m
Run-time dependency [1mspdlog[0m found: [1;32mYES[0m [36m1.13.0[0m
Run-time dependency [1mwayland-client[0m found: [1;32mYES[0m [36m1.22.0[0m
Run-time dependency [1mwayland-cursor[0m found: [1;32mYES[0m [36m1.22.0[0m
Run-time dependency [1mwayland-protocols[0m found: [1;32mYES[0m [36m1.33[0m
Run-time dependency [1mgtkmm-3.0[0m found: [1;32mYES[0m [36m3.24.8[0m
Run-time dependency [1mdbusmenu-gtk3-0.4[0m found: [1;32mYES[0m [36m16.04.0[0m
Run-time dependency [1mgio-unix-2.0[0m found: [1;32mYES[0m [36m2.78.4[0m
Run-time dependency [1mjsoncpp[0m found: [1;32mYES[0m [36m1.9.5[0m
Run-time dependency [1msigc++-2.0[0m found: [1;32mYES[0m [36m2.12.1[0m
Did not find CMake 'cmake'
Found CMake: [1;31mNO[0m
Run-time dependency [1mlibinotify[0m found: [1;31mNO[0m (tried pkgconfig and cmake)
Run-time dependency [1mepoll-shim[0m found: [1;31mNO[0m (tried pkgconfig and cmake)
Run-time dependency [1mlibinput[0m found: [1;32mYES[0m [36m1.25.0[0m
Run-time dependency [1mlibnl-3.0[0m found: [1;32mYES[0m [36m3.8.0[0m
Run-time dependency [1mlibnl-genl-3.0[0m found: [1;32mYES[0m [36m3.8.0[0m
Run-time dependency [1mupower-glib[0m found: [1;32mYES[0m [36m1.90.2[0m
Run-time dependency [1mlibpipewire-0.3[0m found: [1;32mYES[0m [36m1.0.3[0m
Run-time dependency [1mplayerctl[0m found: [1;32mYES[0m [36m2.4.1[0m
Run-time dependency [1mlibpulse[0m found: [1;32mYES[0m [36m17.0[0m
Run-time dependency [1mlibudev[0m found: [1;32mYES[0m [36m255[0m
Run-time dependency [1mlibevdev[0m found: [1;32mYES[0m [36m1.13.1[0m
Run-time dependency [1mlibmpdclient[0m found: [1;32mYES[0m [36m2.22[0m
Run-time dependency [1mxkbregistry[0m found: [1;32mYES[0m [36m1.5.0[0m
Run-time dependency [1mjack[0m found: [1;32mYES[0m [36m1.9.22[0m
Run-time dependency [1mwireplumber-0.4[0m found: [1;31mNO[0m (tried pkgconfig)

meson.build:95:17: [1;31mERROR:[0m Dependency "wireplumber-0.4" not found, tried pkgconfig

A full log can be found at [1m/build/source/build/meson-logs/meson-log.txt[0m
```

### Notify maintainers

@FlorianFranzen
@lovesegfault
@minijackson
@rodrgz
@synthetica
@khaneliman

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.21, NixOS, 24.05 (Uakari), 24.05.20240314.d691274`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/9mf8fkjw3vw1gm4s6j5fqlwrv5wf2knf-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by arthsmn** [comment] 2024-03-20 19:59
Can't reproduce, just updated my repository and built it just fine.

**Comment by arthsmn** [comment] 2024-03-20 20:02
Already fixed in https://github.com/NixOS/nixpkgs/commit/49f83b701e7939079c529f378c79fa8544f4db72.

**Closed by arthsmn** 2024-03-20 20:02 UTC
Labels: 0.kind: build failure

**Comment by paches00** [comment] 2024-03-20 23:32
@arthsmn How would I manually apply the fix in a flake? I'm sort of new to nixos so I would appreciate the help.

**Comment by khaneliman** [comment] 2024-03-21 00:40
> @arthsmn How would I manually apply the fix in a flake? I'm sort of new to nixos so I would appreciate the help.

```nix
waybar.override {
    wireplumber = prev.wireplumber.overrideAttrs rec {
      version = "0.4.17";
      src = prev.fetchFromGitLab {
        domain = "gitlab.freedesktop.org";
        owner = "pipewire";
        repo = "wireplumber";
        rev = version;
        hash = "sha256-vhpQT67+849WV1SFthQdUeFnYe/okudTQJoL3y+wXwI=";
      };
    };
  };
```
