### ISSUE TITLE
syncthingtray: error loading plasmoid's QML

### ISSUE THREAD

**Issue by evilmav** [NixOS/nixpkgs#199596] opened 2022-11-04 23:47 UTC
### Describe the bug
The tray icon appears, but he according window shows:
```
file:///nix/store/s579qmf6md5nl1hyhxnm5agkl75xbgr6-syncthingtray-1.2.3/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/main.qml:13:34: Type FullRepresentation unavailable

file:///nix/store/s579qmf6md5nl1hyhxnm5agkl75xbgr6-syncthingtray-1.2.3/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/FullRepresentation.qml:16:9: Type ToolBar unavailable

file:///nix/store/s579qmf6md5nl1hyhxnm5agkl75xbgr6-syncthingtray-1.2.3/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/ToolBar.qml:7:1: module "martchus.syncthingplasmoid" is not installed
```

### Steps To Reproduce
1. Install syncthingtray (through home.packages in home-manager in my case)
2. Click on the tray icon

### Expected behavior
The proper GUI with shiny buttons and stuff

### Notify maintainers
@doronbehar 

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.6, NixOS, 22.11 (Raccoon), 22.11pre423448.a2a777538d9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos"`
 - channels(maverick): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by EvilMav** [comment] 2022-11-09 22:28
Didn't have time to do actual digging yet, but seems like it's actually a matter of launching it / nixos weirdness rather then the package itself:
  * if I run `syncthingtray` manually from the terminal it actually works as expected.   
  * if I have it launched by plasma's autostart it sits in the tray failed with the message above. 
  * if I have it launched as user systemd service through the according home-manager option, it fails to launch because it can not find the tray altogether (probably launched before plasma is ready).

So the question is, why is it different when launched from autostart... The message shows the right path in `/nix/store/` after all...

**Comment by doronbehar** [comment] 2022-11-10 11:22
I'd investigate this by comparing the environment of your terminal to the environment of autostart's `.desktop` file - try to override the `ExecStart=syncthing` line to something like:

```
ExecStart=sh -c 'env > ~/syncthing-autostart.env; syncthing <other-args>'
```

**Comment by doronbehar** [comment] 2022-11-10 11:24
Oh I see what's the problem.. the `.desktop` file `syncthingtray` generates is pointing in `ExecStart` to the unwrapped executable.. This needs to be patched locally in nixpkgs!

**Comment by EvilMav** [comment] 2022-11-10 11:33
That would explain it. What do you mean by "patched locally"?

**Comment by doronbehar** [comment] 2022-11-10 12:04
I mean this: https://github.com/NixOS/nixpkgs/pull/200524

**Comment by doronbehar** [comment] 2022-11-11 15:31
@EvilMav you are invited to test the fix for your issue in #200524 .

**Comment by EvilMav** [comment] 2022-11-23 23:42
I'm really sorry it took me forever to actually test it - had issues with the system I use it on.

Anyway, the desktop file wasn't my issue either - I didn't realize the thing in tray is not the autostarted desktop file / syncthing process, but the **plasmoid** which is apparently a completely different beast running within the plasmashell process rather then a separate one. It appears automatically in tray unless I use syncthingtray with `.override { plasmoidSupport = false; }` and can not be removed from there. Launching the `syncthingtray` process actually creates a second icon, which behaves properly.

Disabling the override and using autostart does not actually work either, because it seems to be started before the plasmashell and crashes with an error. Which is a separate issue though.

**Comment by doronbehar** [comment] 2022-11-24 10:42
> I'm really sorry it took me forever to actually test it - had issues with the system I use it on.
> 
> Anyway, the desktop file wasn't my issue either - I didn't realize the thing in tray is not the autostarted desktop file / syncthingtray process, but the **plasmoid** which is apparently a completely different beast running within the plasmashell process rather then a separate one. It appears automatically in tray unless I use syncthingtray with `.override { plasmoidSupport = false; }` and can not be removed from there through plasma controls. Launching the `syncthingtray` process actually creates a second icon, which behaves properly.

I'm not sure I followed.. Does it work if you set `syncthingtray.override { plasmoidSupport = true; }`? [PR #200524](https://nixpk.gs/pr-tracker.html?pr=200524) has landed in `nixos-unstable` so the environment issue fixed there should affect you somehow I think. Feel free to reopen the issue.

**Comment by Martchus** [comment] 2022-12-08 17:25
According to the initially reported issue description it is indeed the Plasmoid that's causing problems here. On Plasma the Plasmoid is supposedly the preferred UI. So the goal should be to fix it. If you nevertheless want to use the `syncthingtray` executable instead you can do that of course as well. Then you can simply disable the Plasmoid by removing it from all panels/screen as usual. If the Plasmoid is shown as part of Plasma's system tray Plasmoid, you can disable it via the settings of the system tray Plasmoid.

To fix the actual issue of the Plasmoid: Supposedly a file is missing in the package. The full list of files to be contained by the package should currently look like this:

```
syncthingtray usr/
syncthingtray usr/bin/
syncthingtray usr/bin/syncthingctl
syncthingtray usr/bin/syncthingtray
syncthingtray usr/include/
syncthingtray usr/include/syncthingconnector/
syncthingtray usr/include/syncthingconnector/global.h
syncthingtray usr/include/syncthingconnector/qstringhash.h
syncthingtray usr/include/syncthingconnector/syncthingcompletion.h
syncthingtray usr/include/syncthingconnector/syncthingconfig.h
syncthingtray usr/include/syncthingconnector/syncthingconnection.h
syncthingtray usr/include/syncthingconnector/syncthingconnectionsettings.h
syncthingtray usr/include/syncthingconnector/syncthingconnectionstatus.h
syncthingtray usr/include/syncthingconnector/syncthingdev.h
syncthingtray usr/include/syncthingconnector/syncthingdir.h
syncthingtray usr/include/syncthingconnector/syncthingnotifier.h
syncthingtray usr/include/syncthingconnector/syncthingprocess.h
syncthingtray usr/include/syncthingconnector/syncthingservice.h
syncthingtray usr/include/syncthingconnector/utils.h
syncthingtray usr/include/syncthingconnector/version.h
syncthingtray usr/include/syncthingmodel/
syncthingtray usr/include/syncthingmodel/colors.h
syncthingtray usr/include/syncthingmodel/global.h
syncthingtray usr/include/syncthingmodel/syncthingdevicemodel.h
syncthingtray usr/include/syncthingmodel/syncthingdirectorymodel.h
syncthingtray usr/include/syncthingmodel/syncthingdownloadmodel.h
syncthingtray usr/include/syncthingmodel/syncthingicons.h
syncthingtray usr/include/syncthingmodel/syncthingmodel.h
syncthingtray usr/include/syncthingmodel/syncthingrecentchangesmodel.h
syncthingtray usr/include/syncthingmodel/syncthingsortfiltermodel.h
syncthingtray usr/include/syncthingmodel/syncthingstatuscomputionmodel.h
syncthingtray usr/include/syncthingmodel/syncthingstatusselectionmodel.h
syncthingtray usr/include/syncthingmodel/version.h
syncthingtray usr/include/syncthingwidgets/
syncthingtray usr/include/syncthingwidgets/global.h
syncthingtray usr/include/syncthingwidgets/misc/
syncthingtray usr/include/syncthingwidgets/misc/dbusstatusnotifier.h
syncthingtray usr/include/syncthingwidgets/misc/direrrorsdialog.h
syncthingtray usr/include/syncthingwidgets/misc/internalerror.h
syncthingtray usr/include/syncthingwidgets/misc/internalerrorsdialog.h
syncthingtray usr/include/syncthingwidgets/misc/otherdialogs.h
syncthingtray usr/include/syncthingwidgets/misc/statusinfo.h
syncthingtray usr/include/syncthingwidgets/misc/syncthingkiller.h
syncthingtray usr/include/syncthingwidgets/misc/syncthinglauncher.h
syncthingtray usr/include/syncthingwidgets/misc/textviewdialog.h
syncthingtray usr/include/syncthingwidgets/settings/
syncthingtray usr/include/syncthingwidgets/settings/settings.h
syncthingtray usr/include/syncthingwidgets/settings/settingsdialog.h
syncthingtray usr/include/syncthingwidgets/settings/wizard.h
syncthingtray usr/include/syncthingwidgets/version.h
syncthingtray usr/include/syncthingwidgets/webview/
syncthingtray usr/include/syncthingwidgets/webview/webpage.h
syncthingtray usr/include/syncthingwidgets/webview/webviewdialog.h
syncthingtray usr/lib/
syncthingtray usr/lib/libsyncthingconnector.so
syncthingtray usr/lib/libsyncthingconnector.so.1.3.1
syncthingtray usr/lib/libsyncthingconnector.so.4
syncthingtray usr/lib/libsyncthingmodel.so
syncthingtray usr/lib/libsyncthingmodel.so.1.3.1
syncthingtray usr/lib/libsyncthingmodel.so.4
syncthingtray usr/lib/libsyncthingwidgets.so
syncthingtray usr/lib/libsyncthingwidgets.so.1.3.1
syncthingtray usr/lib/libsyncthingwidgets.so.4
syncthingtray usr/lib/pkgconfig/
syncthingtray usr/lib/pkgconfig/syncthingconnector.pc
syncthingtray usr/lib/pkgconfig/syncthingfileitemaction.pc
syncthingtray usr/lib/pkgconfig/syncthingmodel.pc
syncthingtray usr/lib/pkgconfig/syncthingplasmoid.pc
syncthingtray usr/lib/pkgconfig/syncthingwidgets.pc
syncthingtray usr/lib/qt/
syncthingtray usr/lib/qt/plugins/
syncthingtray usr/lib/qt/plugins/libsyncthingfileitemaction.so
syncthingtray usr/lib/qt/plugins/plasma/
syncthingtray usr/lib/qt/plugins/plasma/applets/
syncthingtray usr/lib/qt/plugins/plasma/applets/libsyncthingplasmoid.so
syncthingtray usr/share/
syncthingtray usr/share/applications/
syncthingtray usr/share/applications/syncthingtray.desktop
syncthingtray usr/share/bash-completion/
syncthingtray usr/share/bash-completion/completions/
syncthingtray usr/share/bash-completion/completions/syncthingctl
syncthingtray usr/share/bash-completion/completions/syncthingtray
syncthingtray usr/share/icons/
syncthingtray usr/share/icons/hicolor/
syncthingtray usr/share/icons/hicolor/scalable/
syncthingtray usr/share/icons/hicolor/scalable/apps/
syncthingtray usr/share/icons/hicolor/scalable/apps/syncthingtray.svg
syncthingtray usr/share/kservices5/
syncthingtray usr/share/kservices5/plasma-applet-martchus.syncthingplasmoid.desktop
syncthingtray usr/share/kservices5/syncthingfileitemaction.desktop
syncthingtray usr/share/metainfo/
syncthingtray usr/share/metainfo/syncthingfileitemaction.appdata.xml
syncthingtray usr/share/metainfo/syncthingplasmoid.appdata.xml
syncthingtray usr/share/metainfo/syncthingtray.appdata.xml
syncthingtray usr/share/plasma/
syncthingtray usr/share/plasma/plasmoids/
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/CompactRepresentation.qml
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/DetailItem.qml
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/DetailView.qml
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/DevicesPage.qml
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/DirectoriesPage.qml
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/DownloadsPage.qml
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/FullRepresentation.qml
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/IconLabel.qml
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/RecentChangesPage.qml
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/StatisticsView.qml
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/TabButton.qml
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/TinyButton.qml
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/ToolBar.qml
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/ToolButton.qml
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/ToolTipTrigger.qml
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/ToolTipView.qml
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/TopLevelItem.qml
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/TopLevelView.qml
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/main.qml
syncthingtray usr/share/plasma/plasmoids/martchus.syncthingplasmoid/metadata.desktop
syncthingtray usr/share/syncthingconnector/
syncthingtray usr/share/syncthingconnector/cmake/
syncthingtray usr/share/syncthingconnector/cmake/syncthingconnectorConfig.cmake
syncthingtray usr/share/syncthingconnector/cmake/syncthingconnectorConfigVersion.cmake
syncthingtray usr/share/syncthingconnector/cmake/syncthingconnectorTargets-release.cmake
syncthingtray usr/share/syncthingconnector/cmake/syncthingconnectorTargets.cmake
syncthingtray usr/share/syncthingfileitemaction/
syncthingtray usr/share/syncthingfileitemaction/cmake/
syncthingtray usr/share/syncthingfileitemaction/cmake/syncthingfileitemactionConfig.cmake
syncthingtray usr/share/syncthingfileitemaction/cmake/syncthingfileitemactionConfigVersion.cmake
syncthingtray usr/share/syncthingfileitemaction/cmake/syncthingfileitemactionTargets-release.cmake
syncthingtray usr/share/syncthingfileitemaction/cmake/syncthingfileitemactionTargets.cmake
syncthingtray usr/share/syncthingmodel/
syncthingtray usr/share/syncthingmodel/cmake/
syncthingtray usr/share/syncthingmodel/cmake/syncthingmodelConfig.cmake
syncthingtray usr/share/syncthingmodel/cmake/syncthingmodelConfigVersion.cmake
syncthingtray usr/share/syncthingmodel/cmake/syncthingmodelTargets-release.cmake
syncthingtray usr/share/syncthingmodel/cmake/syncthingmodelTargets.cmake
syncthingtray usr/share/syncthingplasmoid/
syncthingtray usr/share/syncthingplasmoid/cmake/
syncthingtray usr/share/syncthingplasmoid/cmake/syncthingplasmoidConfig.cmake
syncthingtray usr/share/syncthingplasmoid/cmake/syncthingplasmoidConfigVersion.cmake
syncthingtray usr/share/syncthingplasmoid/cmake/syncthingplasmoidTargets-release.cmake
syncthingtray usr/share/syncthingplasmoid/cmake/syncthingplasmoidTargets.cmake
syncthingtray usr/share/syncthingwidgets/
syncthingtray usr/share/syncthingwidgets/cmake/
syncthingtray usr/share/syncthingwidgets/cmake/syncthingwidgetsConfig.cmake
syncthingtray usr/share/syncthingwidgets/cmake/syncthingwidgetsConfigVersion.cmake
syncthingtray usr/share/syncthingwidgets/cmake/syncthingwidgetsTargets-release.cmake
syncthingtray usr/share/syncthingwidgets/cmake/syncthingwidgetsTargets.cmake
```

Of course the exact paths depend on your install prefix and paths of your Qt and Plasma installation.

Maybe something is not missing but installed to the wrong directory. Did the Plasmoid (*not* the stand-alone executable) ever work with your packaging? If it did then I'd try to compare the last working package with the first bad.

**Comment by Martchus** [comment] 2022-12-08 17:31
Note that an override for the executable path (via a CMake option that then sets a define which is used if present like in your patch) could be upstreamed.

**Comment by doronbehar** [comment] 2022-12-09 07:13
> Note that an override for the executable path (via a CMake option that then sets a define which is used if present like in your patch) could be upstreamed.

I was thinking about it just today, since usually you'd want it to be the permanent symlink `/run/current-system/sw/bin/syncthingtray` and not the `/nix/store/...` path (to the wrapped executable) that might be removed after a garbage collection.. Let's continue this discussion in https://github.com/Martchus/syncthingtray/pull/167

**Comment by aquova** [comment] 2023-08-22 20:19
What is the status on this? I'm still encountering this issue on my machine

**Comment by doronbehar** [comment] 2023-08-23 10:04
I'm not sure what more could I do here.. I will report here after @Martchus comment that there are no much differences between the files installed by our package and what should be installed:

<details><summary><code>diff our-list.txt upstream-list.txt</code></summary>

```diff
4d3
< result/bin/.syncthingctl-wrapped
6d4
< result/bin/.syncthingtray-wrapped
13d10
< result/include/syncthingconnector/syncthingconnectionenums.h
52d48
< result/include/syncthingwidgets/settings/wizardenums.h
60,61c56,57
< result/lib/libsyncthingconnector.so.1.4.5
< result/lib/libsyncthingconnector.so.8
---
> result/lib/libsyncthingconnector.so.1.3.1
> result/lib/libsyncthingconnector.so.4
63,64c59,60
< result/lib/libsyncthingmodel.so.1.4.5
< result/lib/libsyncthingmodel.so.8
---
> result/lib/libsyncthingmodel.so.1.3.1
> result/lib/libsyncthingmodel.so.4
66,67c62,63
< result/lib/libsyncthingwidgets.so.1.4.5
< result/lib/libsyncthingwidgets.so.8
---
> result/lib/libsyncthingwidgets.so.1.3.1
> result/lib/libsyncthingwidgets.so.4
74,79c70,75
< result/lib/qt-5.15.10
< result/lib/qt-5.15.10/plugins
< result/lib/qt-5.15.10/plugins/libsyncthingfileitemaction.so
< result/lib/qt-5.15.10/plugins/plasma
< result/lib/qt-5.15.10/plugins/plasma/applets
< result/lib/qt-5.15.10/plugins/plasma/applets/libsyncthingplasmoid.so
---
> result/lib/qt
> result/lib/qt/plugins
> result/lib/qt/plugins/libsyncthingfileitemaction.so
> result/lib/qt/plugins/plasma
> result/lib/qt/plugins/plasma/applets
> result/lib/qt/plugins/plasma/applets/libsyncthingplasmoid.so
130,134d125
< result/share/syncthingconnector/translations
< result/share/syncthingconnector/translations/syncthingconnector_cs_CZ.qm
< result/share/syncthingconnector/translations/syncthingconnector_de_DE.qm
< result/share/syncthingconnector/translations/syncthingconnector_en_US.qm
< result/share/syncthingconnector/translations/syncthingconnector_zh_CN.qm
141,145d131
< result/share/syncthingfileitemaction/translations
< result/share/syncthingfileitemaction/translations/syncthingfileitemaction_cs_CZ.qm
< result/share/syncthingfileitemaction/translations/syncthingfileitemaction_de_DE.qm
< result/share/syncthingfileitemaction/translations/syncthingfileitemaction_en_US.qm
< result/share/syncthingfileitemaction/translations/syncthingfileitemaction_zh_CN.qm
152,156d137
< result/share/syncthingmodel/translations
< result/share/syncthingmodel/translations/syncthingmodel_cs_CZ.qm
< result/share/syncthingmodel/translations/syncthingmodel_de_DE.qm
< result/share/syncthingmodel/translations/syncthingmodel_en_US.qm
< result/share/syncthingmodel/translations/syncthingmodel_zh_CN.qm
163,171d143
< result/share/syncthingplasmoid/translations
< result/share/syncthingplasmoid/translations/syncthingplasmoid_de_DE.qm
< result/share/syncthingplasmoid/translations/syncthingplasmoid_en_US.qm
< result/share/syncthingtray
< result/share/syncthingtray/translations
< result/share/syncthingtray/translations/syncthingtray_cs_CZ.qm
< result/share/syncthingtray/translations/syncthingtray_de_DE.qm
< result/share/syncthingtray/translations/syncthingtray_en_US.qm
< result/share/syncthingtray/translations/syncthingtray_zh_CN.qm
178,182d149
< result/share/syncthingwidgets/translations
< result/share/syncthingwidgets/translations/syncthingwidgets_cs_CZ.qm
< result/share/syncthingwidgets/translations/syncthingwidgets_de_DE.qm
< result/share/syncthingwidgets/translations/syncthingwidgets_en_US.qm
< result/share/syncthingwidgets/translations/syncthingwidgets_zh_CN.qm
```

</details>

**Comment by Martchus** [comment] 2023-08-23 11:15
Is this a problem affecting all NixOS users or is it just reproducible in the setup of a few people.

For debugging it might help to start `plasmashell` with the env variable `QT_DEBUG_PLUGINS=1` set.

**Comment by Martchus** [comment] 2023-08-23 11:16
I'd only compare the packaging with how other Plasmoids for NixOS are packaged. Maybe there actually *needs* to be a difference compared to my "upstream packaging".

**Comment by doronbehar** [comment] 2023-08-23 11:22
I don't experience this issue, here on Gnome, naturally. Other packages in Nixpkgs, like `kscreen`, `kgamma5` and `kwin` also put files in `plugins/plasma/`, according to [`nix-locate`](https://github.com/nix-community/nix-index).

**Comment by Martchus** [comment] 2023-08-23 12:19
Yes, you would obviously need to start a Plasma session to reproduce the issue. (Or just launch `plasmashell` or `plasmoidviewer` in another session. I suppose `plasmashell` will work in any X11 session and `plasmoidviewer` in any X11 or Wayland session.)

Maybe it makes more sense if the users that actually use Plasma would do further debugging on their side, though.

By the way, how do you use Syncthing Tray under GNOME? Last time I've checked whether it works there was no general support for system tray icons at all and issues like https://gitlab.freedesktop.org/xdg/xdg-specs/-/issues/84 suggest that GNOME has no generic system tray icon support at all right now. If there are any workarounds those might be worth documenting under https://github.com/Martchus/syncthingtray#known-bugs-and-workarounds and https://github.com/Martchus/syncthingtray#supported-platforms could be extended with a remark to the workaround section.

**Comment by aquova** [comment] 2023-08-23 12:21
As a note, I'm a pretty new NixOS user, but I switched yesterday to the unstable channel, and syncthingtray is working completely fine now.

**Comment by doronbehar** [comment] 2023-08-23 12:28
> By the way, how do you use Syncthing Tray under GNOME?

Using [this gnome shell extension](https://github.com/ubuntu/gnome-shell-extension-appindicator).

**Comment by doronbehar** [comment] 2023-08-23 12:30
> As a note, I'm a pretty new NixOS user, but I switched yesterday to the unstable channel, and syncthingtray is working completely fine now.

Thanks for the report. I wonder what was the problem... I'll close this in the meantime, unless someone from the stable channels will give a detailed bug report.

**Closed by doronbehar** 2023-08-23 12:30 UTC
Labels: 0.kind: bug
