### ISSUE TITLE
Build failure: floorp-unwrapped

### ISSUE THREAD

**Issue by Sigmanificient** [NixOS/nixpkgs#326640] opened 2024-07-12 19:50 UTC
### Steps To Reproduce

Trying to switch after a `nix flake update` on nixos unstable fails, due to package `floorp` failling to build.

1. build `floorp` on nixos-unstable, i guess `nix build nixpkgs/nixos-unstable#floorp -I -L ` should do it too
2. wait for about 2h

### Build log

```
floorp-unwrapped>  1:49.64(B make[4]: Entering directory '/build/source/objdir/browser/locales'(B(B
floorp-unwrapped>  1:49.68(B /build/source/python/mozbuild/mozbuild/action/langpack_manifest.py:373: SyntaxWarning: invalid escape sequence '\d'(B(B
floorp-unwrapped>  1:49.68(B   matches = re.compile("[^\d]").search(part)(B(B
floorp-unwrapped>  1:49.85(B /build/source/python/mozbuild/mozbuild/action/langpack_manifest.py:44: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).(B(B
floorp-unwrapped>  1:49.85(B   return datetime.datetime.utcfromtimestamp((B(B
floorp-unwrapped>  1:50.07(B make[4]: Leaving directory '/build/source/objdir/browser/locales'(B(B
floorp-unwrapped>  1:50.07(B make[3]: Leaving directory '/build/source/objdir/browser/locales'(B(B
floorp-unwrapped>  1:50.07(B make[2]: Leaving directory '/build/source/objdir/browser/installer'(B(B
floorp-unwrapped>  1:50.07(B make[1]: Leaving directory '/build/source/objdir/browser/installer'(B(B
floorp-unwrapped>  1:50.07(B make: Leaving directory '/build/source/objdir'(B(B
floorp-unwrapped> Running "pip check" to verify compatibility between the system Python and the "mach" site.
floorp-unwrapped> Running "pip check" to verify compatibility between the system Python and the "common" site.
floorp-unwrapped> Site not up-to-date reason: "/build/source/objdir/_virtualenvs/common" does not exist
floorp-unwrapped> Traceback (most recent call last):
floorp-unwrapped>   File "/build/source/./build/pgo/profileserver.py", line 19, in <module>
floorp-unwrapped>     from mozrunner import CLI, FirefoxRunner
floorp-unwrapped>   File "/build/source/testing/mozbase/mozrunner/mozrunner/__init__.py", line 6, in <module>
floorp-unwrapped>     import mozrunner.base
floorp-unwrapped>   File "/build/source/testing/mozbase/mozrunner/mozrunner/base/__init__.py", line 6, in <module>
floorp-unwrapped>     from .browser import BlinkRuntimeRunner, GeckoRuntimeRunner
floorp-unwrapped>   File "/build/source/testing/mozbase/mozrunner/mozrunner/base/browser.py", line 11, in <module>
floorp-unwrapped>     from ..application import DefaultContext, FirefoxContext
floorp-unwrapped>   File "/build/source/testing/mozbase/mozrunner/mozrunner/application.py", line 8, in <module>
floorp-unwrapped>     from distutils.spawn import find_executable
floorp-unwrapped> ModuleNotFoundError: No module named 'distutils'
error: builder for '/nix/store/0x3pwcndqbi8zlgjm79al78yhlj54msa-floorp-unwrapped-11.14.1.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/36i369p3p0x3rnj30jxi0112bbyb2f1a-floorp-11.14.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/asvcr8llvbir8f8pb4flmnvv0acrh9qb-hm_dunstdunstrc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/22jl03gjcrf61cvk8nq6v5g5ll7q8mik-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/npyz99zidkk2zaprlxx4if18fp5a6dxq-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/5i30gj1252z8vfyiqkas2sx0cddsqcgc-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qj992p0n9ghql4xzibx12g7wpa267584-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/58ldiz5s38vj8c8iy2b9wpmhg41d52cj-nixos-system-Bacon-24.11.20240709.feb2849.drv' failed to build
```

### Additional context

This seems to be a frequent issue due to `disutils` removal on pythn 3.12

### Notify maintainers

@christoph-heiss

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.11 (Vicuna), 24.11.20240703.9f4128e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos-23.05"`
 - channels(sigmanificient): `""`
 - nixpkgs: `/nix/store/dk2rpyb6ndvfbf19bkb2plcz5y3k8i5v-source`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-07-12 20:20
duplicate of https://github.com/NixOS/nixpkgs/issues/325785

follow https://nixpk.gs/pr-tracker.html?pr=326101 for updates

**Closed by eclairevoyant** 2024-07-12 20:20 UTC
Labels: 0.kind: build failure
