### ISSUE TITLE
calibre fails to build (QT incompatibility?)

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#7897] opened 2015-05-18 19:41 UTC
I think this happened in the last couple of days.  It's not clear to me how to address it, though.

> ####### Building headless QPA plugin #######
> Project MESSAGE: This project is using private headers and will therefore be tied to this specific Qt module build version.
> Project MESSAGE: Running this project against other versions of the Qt modules may crash at any arbitrary point.
> Project MESSAGE: This is not a bug, but a result of using Qt internals. You have been warned!
> make: *** No rule to make target '/tmp/nix-build-calibre-2.28.0.drv-0/qmake-calibre-2.28.0/lib/libQt5PlatformSupport.a', needed by '/tmp/nix-build-calibre-2.28.0.drv-0/calibre-2.28.0/src/calibre/plugins/libheadless.so'.  Stop.
> Error while executing: make -j4
> 
> Traceback (most recent call last):
>   File "setup.py", line 99, in <module>
>     sys.exit(main())
>   File "setup.py", line 85, in main
>     command.run_all(opts)
>   File "/tmp/nix-build-calibre-2.28.0.drv-0/calibre-2.28.0/setup/__init__.py", line 181, in run_all
>     self.run_cmd(self, opts)
>   File "/tmp/nix-build-calibre-2.28.0.drv-0/calibre-2.28.0/setup/__init__.py", line 175, in run_cmd
>     self.run_cmd(scmd, opts)
>   File "/tmp/nix-build-calibre-2.28.0.drv-0/calibre-2.28.0/setup/__init__.py", line 178, in run_cmd
>     cmd.run(opts)
>   File "/tmp/nix-build-calibre-2.28.0.drv-0/calibre-2.28.0/setup/extensions.py", line 414, in run
>     self.build_headless()
>   File "/tmp/nix-build-calibre-2.28.0.drv-0/calibre-2.28.0/setup/extensions.py", line 550, in build_headless
>     self.check_call([make] + ['-j%d'%(cpu_count or 1)])
>   File "/tmp/nix-build-calibre-2.28.0.drv-0/calibre-2.28.0/setup/extensions.py", line 486, in check_call
>     subprocess.check_call(*args, **kwargs)
>   File "/nix/store/fzsbv209kna7bz6c89g9h1b2q3hmkaaz-python-2.7.9/lib/python2.7/subprocess.py", line 540, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['make', '-j4']' returned non-zero exit status 2
> builder for ‘/nix/store/2rfhnx9d63d313j5hi2cxz25z5c1ri9a-calibre-2.28.0.drv’ failed with exit code 1
> error: build of ‘/nix/store/2rfhnx9d63d313j5hi2cxz25z5c1ri9a-calibre-2.28.0.drv’ failed

**Comment by pSub** [comment] 2015-05-18 20:03
Yes, somehow `libQt5PlatformSupport.a` seems to be missing. I have looked into this yesterday, but without luck so far, but I'll look into this tomorrow again.

**Comment by pSub** [comment] 2015-05-18 20:30
There is a releated bug in the Arch Linux tracker: https://bugs.archlinux.org/task/38819 and a comment  in extensions.py https://fossies.org/diffs/calibre/2.16.0_vs_2.17.0/setup/extensions.py-diff.html

**Comment by pSub** [comment] 2015-05-18 20:35
cc @ttuegel

**Comment by pSub** [comment] 2015-05-18 20:42
I fixed the build temporarily by using qt53, see commit 3ac31fe04135fe8aa2cbe23a19066c8a1ec37b8c.

**Comment by retrry** [comment] 2015-07-07 14:50
Calibre 2.31 fails to build for me again. Could this be related?
```
/tmp/nix-build-calibre-2.31.0.drv-0/calibre-2.31.0/src/calibre/headless/fontconfig_database.cpp:554:1: error: 'SubpixelAntialiasingType' in 'class QFontEngine' does not name a type
 QFontEngine::SubpixelAntialiasingType subpixelTypeFromMatch(FcPattern *match, bool useXftConf)
 ^
/tmp/nix-build-calibre-2.31.0.drv-0/calibre-2.31.0/src/calibre/headless/fontconfig_database.cpp: In member function 'void QFontconfigDatabase::setupFontEngine(QFontEngineFT*, const QFontDef&) const':
/tmp/nix-build-calibre-2.31.0.drv-0/calibre-2.31.0/src/calibre/headless/fontconfig_database.cpp:864:21: error: 'class QFontEngineFT' has no member named 'forceAutoHint'
             engine->forceAutoHint = fc_autohint;
                     ^
/tmp/nix-build-calibre-2.31.0.drv-0/calibre-2.31.0/src/calibre/headless/fontconfig_database.cpp:879:13: error: 'SubpixelAntialiasingType' is not a member of 'QFontEngine'
             QFontEngine::SubpixelAntialiasingType subpixelType = QFontEngine::Subpixel_None;
             ^
/tmp/nix-build-calibre-2.31.0.drv-0/calibre-2.31.0/src/calibre/headless/fontconfig_database.cpp:879:51: error: expected ';' before 'subpixelType'
             QFontEngine::SubpixelAntialiasingType subpixelType = QFontEngine::Subpixel_None;
                                                   ^
/tmp/nix-build-calibre-2.31.0.drv-0/calibre-2.31.0/src/calibre/headless/fontconfig_database.cpp:880:43: error: 'NoSubpixelAntialias' is not a member of 'QFont'
             if (!(fontDef.styleStrategy & QFont::NoSubpixelAntialias))
                                           ^
/tmp/nix-build-calibre-2.31.0.drv-0/calibre-2.31.0/src/calibre/headless/fontconfig_database.cpp:881:17: error: 'subpixelType' was not declared in this scope
                 subpixelType = subpixelTypeFromMatch(match, useXftConf);
                 ^
/tmp/nix-build-calibre-2.31.0.drv-0/calibre-2.31.0/src/calibre/headless/fontconfig_database.cpp:881:71: error: 'subpixelTypeFromMatch' was not declared in this scope
                 subpixelType = subpixelTypeFromMatch(match, useXftConf);
                                                                       ^
/tmp/nix-build-calibre-2.31.0.drv-0/calibre-2.31.0/src/calibre/headless/fontconfig_database.cpp:882:36: error: 'subpixelType' was not declared in this scope
             engine->subpixelType = subpixelType;
                                    ^
/tmp/nix-build-calibre-2.31.0.drv-0/calibre-2.31.0/src/calibre/headless/fontconfig_database.cpp:884:39: error: 'Subpixel_None' is not a member of 'QFontEngine'
             format = (subpixelType == QFontEngine::Subpixel_None)
                                       ^
Makefile:1153: recipe for target 'fontconfig_database.o' failed
make: *** [fontconfig_database.o] Error 1
Error while executing: make -j4

Traceback (most recent call last):
  File "setup.py", line 99, in <module>
    sys.exit(main())
  File "setup.py", line 85, in main
    command.run_all(opts)
  File "/tmp/nix-build-calibre-2.31.0.drv-0/calibre-2.31.0/setup/__init__.py", line 181, in run_all
    self.run_cmd(self, opts)
  File "/tmp/nix-build-calibre-2.31.0.drv-0/calibre-2.31.0/setup/__init__.py", line 175, in run_cmd
    self.run_cmd(scmd, opts)
  File "/tmp/nix-build-calibre-2.31.0.drv-0/calibre-2.31.0/setup/__init__.py", line 178, in run_cmd
    cmd.run(opts)
  File "/tmp/nix-build-calibre-2.31.0.drv-0/calibre-2.31.0/setup/extensions.py", line 430, in run
    self.build_headless()
  File "/tmp/nix-build-calibre-2.31.0.drv-0/calibre-2.31.0/setup/extensions.py", line 566, in build_headless
    self.check_call([make] + ['-j%d'%(cpu_count or 1)])
  File "/tmp/nix-build-calibre-2.31.0.drv-0/calibre-2.31.0/setup/extensions.py", line 502, in check_call
    subprocess.check_call(*args, **kwargs)
  File "/nix/store/z6vp5aix4ks1zdjdry7v7dahg8dd02sy-python-2.7.10/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j4']' returned non-zero exit status 2
builder for ‘/nix/store/psxfwzd3w8f3h7jiyg2f5ibdknd4csq6-calibre-2.31.0.drv’ failed with exit code 1
```

**Comment by pSub** [comment] 2015-07-07 19:39
This does not look related to this particular bug, which is already fixed in staging. I will try to reproduce your problem tonight or tomorrow.

**Comment by pSub** [comment] 2015-07-08 16:08
@retrry I can reproduce your problem, but I have currently no idea how to fix it.

**Comment by pSub** [comment] 2015-07-09 20:25
Both problems are fixed in staging. Now we just need to wait for staging to be merged.

**Comment by retrry** [comment] 2015-07-10 08:10
Thanks :)

**Comment by vcunat** [comment] 2015-07-20 09:15
Now a python dependency is failing. http://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.calibre.x86_64-linux

**Comment by mdorman** [comment] 2015-07-20 10:35
Looking at the clientform failure, I'm going to venture to guess---I know *nothing* about python infrastructure---that maybe pypi has changed to an https-only model, and the build system is (quite sensibly) unwilling to pull from anywhere other than the listed URL (which is http:, not https:)?

I'm going to try tweaking the URL locally and see if that allows it to build, and if so, I'll send a PR.

**Comment by vcunat** [comment] 2015-07-20 11:12
The error is because it tries to access network during build, which we disallow. Downloads in nix need to be separate in a `fetchurl` or similar fixed-output derivation.

**Comment by mdorman** [comment] 2015-07-20 11:52
I actually figured that out not long after I left the comment.  Oh, well, I don't understand why the `propagatedBuildInput` for `clientform` doesn't seem to produce the desired result.

**Comment by pSub** [comment] 2015-08-04 11:56
Calibre builds and runs fine for me now. Closing.

**Closed by pSub** 2015-08-04 11:56 UTC
Labels: bug
