### ISSUE TITLE
Installing python-bsddb-2.7.9 fails with unrecognized command line option  to gcc

### ISSUE THREAD

**Issue by eduarrrd** [NixOS/nixpkgs#5701] opened 2015-01-10 21:56 UTC
On 15.05pre55818.173f41c installing fails at
```
building '_bsddb' extension
creating build/temp.linux-x86_64-2.7/tmp
creating build/temp.linux-x86_64-2.7/tmp/nix-build-python-bsddb-2.7.9.drv-0
creating build/temp.linux-x86_64-2.7/tmp/nix-build-python-bsddb-2.7.9.drv-0/Python-2.7.9
creating build/temp.linux-x86_64-2.7/tmp/nix-build-python-bsddb-2.7.9.drv-0/Python-2.7.9/Modules
cc -fPIC -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/nix/store/7qrijmqwawvrbn6a1ddc4x2bmam3fgby-db-5.3.28/include -I/nix/store/w5jgkh7p4ywvirrad3bj9c6a0n3f9m6c-python-2.7.9/include -I. -IInclude -I./Include -I/nix/store/w5jgkh7p4ywvirrad3bj9c6a0n3f9m6c-python-2.7.9/include/python2.7 -c /tmp/nix-build-python-bsddb-2.7.9.drv-0/Python-2.7.9/Modules/_bsddb.c -o build/temp.linux-x86_64-2.7/tmp/nix-build-python-bsddb-2.7.9.drv-0/Python-2.7.9/Modules/_bsddb.o
creating build/lib.linux-x86_64-2.7
cc -pthread -shared -lgcc_s build/temp.linux-x86_64-2.7/tmp/nix-build-python-bsddb-2.7.9.drv-0/Python-2.7.9/Modules/_bsddb.o -L/nix/store/7qrijmqwawvrbn6a1ddc4x2bmam3fgby-db-5.3.28/lib -L/nix/store/w5jgkh7p4ywvirrad3bj9c6a0n3f9m6c-python-2.7.9/lib -R/nix/store/7qrijmqwawvrbn6a1ddc4x2bmam3fgby-db-5.3.28/lib -ldb-5.3 -lpython2.7 -o build/lib.linux-x86_64-2.7/_bsddb.so
gcc: error: unrecognized command line option '-R'

Python build finished, but the necessary bits to build these modules were not found:
_curses   _curses_panel   _sqlite3
_ssl     _tkinter   bsddb185
bz2      dl       gdbm  
imageop   nis      readline
sunaudiodev   zlib           
To find the necessary bits, look in setup.py in detect_modules() for the module's name.


Failed to build these modules:
_bsddb                  
```

**Comment by iElectric** [comment] 2015-01-10 22:01
osx?

**Comment by eduarrrd** [comment] 2015-01-10 22:06
nixos

**Comment by rycee** [comment] 2015-01-11 08:05
This looks to be a duplicate of #5655.

**Comment by eduarrrd** [comment] 2015-01-11 20:48
@rycee certainly looks that way!

**Closed** 2015-01-17 13:15 UTC
Labels: python
