### ISSUE TITLE
haskellPackages.Yi is broken

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#14967] opened 2016-04-25 08:07 UTC
Citing from http://hydra.cryp.to/build/1720534/nixlog/1/raw:

~~~~
Building yi-0.12.4...
Preprocessing library yi-0.12.4...
[  1 of 149] Compiling Yi.Char.Unicode  ( src/library/Yi/Char/Unicode.hs, dist/build/Yi/Char/Unicode.o )
<command line>: can't load .so/.DLL for: libstdc++.so (libstdc++.so: cannot open shared object file: No such file or directory)
~~~~

Not sure where this error comes from. It feels like it might be related to recent changes related to multiple outputs.

**Comment by vcunat** [comment] 2016-04-25 09:09
Possibly, but the correct directory is on `-L` path by default.

**Comment by abbradar** [comment] 2016-04-25 15:11
I feel that it may try to dynamically load it for some reason.

**Comment by jagajaga** [comment] 2016-04-28 12:22
cc @Fuuzetsu

**Comment by Fuuzetsu** [comment] 2016-05-03 10:02
Don't really have time to look into it, feel free to mark it as broken until I do.

**Comment by obadz** [comment] 2016-05-03 11:53
FWIW:

```
[nix-shell:~/src/haskell/yi]$ gcc --print-file-name=libc.so
/nix/store/phffgv3pwihmpdyk8xsz3wv8ydysch8w-glibc-2.23/lib/libc.so

[nix-shell:~/src/haskell/yi]$ gcc --print-file-name=libstdc++.so
libstdc++.so
```

https://ghc.haskell.org/trac/ghc/ticket/5289#comment:35

**Comment by obadz** [comment] 2016-05-03 13:06
```bash
strace /nix/store/sz15n5wv657n735lzzp4vs9qggk9lgll-ghc-7.10.3/bin/ghc --make -fbuilding-cabal-package -O -j1 -static -dynamic-too -dynosuf dyn_o -dynhisuf dyn_hi -outputdir dist/build -odir dist/build -hidir dist/build -stubdir dist/build -i -idist/build -isrc/library -idist/build/autogen -Idist/build/autogen -Idist/build -optP-DHINT -optP-DTESTING -optP-DFRONTEND_VTY -optP-include -optPdist/build/autogen/cabal_macros.h -this-package-key yi_67hEfWrgTUeHjorcOozj6R -hide-all-packages -package-db dist/package.conf.inplace -package-id Cabal-1.22.5.0-9ea569737527320f512dad57b36ee312 -package-id QuickCheck-2.8.2-b53a7cfbc18ef315b8477594b46b108c -package-id array-0.5.1.0-960bf9ae8875cc30355e086f8853a049 -package-id base-4.8.2.0-0d6d1084fbc041e1cded9228e80e264d -package-id binary-0.7.5.0-5784fd031a720c3b84e73006e444c7ca -package-id bytestring-0.10.6.0-c60f4c543b22c7f7293a06ae48820437 -package-id containers-0.5.6.2-e59c9b78d840fa743d4169d4bea15592 -package-id data-default-0.5.3-1c1cca67b512f155426e77ce31a9f070 -package-id directory-1.2.2.0-f8e14a9d121b76a00a0f669ee724a732 -package-id dlist-0.7.1.2-dfced2f12f4865c344b65c528c5600e3 -package-id dynamic-state-0.2.2.0-82acfefe8209f6fbdcfe9ae70e7d67bc -package-id dyre-0.8.12-80fb1d7ae2efa0fa01f0f3b9f4a8f895 -package-id exceptions-0.8.2.1-08ed62d2282590eb80eba3e5c42a5f4e -package-id filepath-1.4.0.0-f97d1e4aebfd7a03be6980454fe31d6e -package-id hashable-1.2.4.0-98b6da14b6f369cf8e5b61483ede3e37 -package-id hint-0.5.1-791e461c393645fce82645b73141c7d4 -package-id lens-4.13-24ed1d9029202f6e375d0e0469e1318e -package-id mtl-2.2.1-3af90341e75ee52dfc4e3143b4e5d219 -package-id old-locale-1.0.0.7-0db938eb141b01f4936a21aef6b843bf -package-id oo-prototypes-0.1.0.0-68a343cef9bd2777f84003ff7854b67d -package-id parsec-3.1.9-846510776e95ad6c72d82358c09b4bee -package-id pointedlist-0.6.1-56cc93e1d59385c560fce0bbd769fec7 -package-id process-1.2.3.0-78f206acb2330ea8066c6c19c87356f0 -package-id random-1.1-7d035f9e510822cd64834106e4acc4b7 -package-id safe-0.3.9-e3aa437cf6afe091d2ac3ab91bc10ddd -package-id semigroups-0.18.1-fbb74a95dbeaefffbbe9446e62c06797 -package-id split-0.2.3-8ed100aa18239d92816021c44aa12b38 -package-id stm-2.4.4.1-7050c728ed5b2315e2c6b56d8bf9837f -package-id template-haskell-2.10.0.0-3c4cb52230f347282af9b2817f013181 -package-id text-1.2.2.1-d0adb978563e9f52dc308d1d0db7212c -package-id text-icu-0.7.0.1-5f46e75c770885f46d17e34953211e8e -package-id time-1.5.0.1-edbd1a50e7922b396ada189ab8e8523b -package-id transformers-base-0.4.4-19dc155e74aa624600f63b02f5f0b424 -package-id unix-2.7.1.0-343d4f566f30113da92e819f4a148640 -package-id unix-compat-0.4.1.4-1e201f07f357b593e8ba1a46086e3ec5 -package-id unordered-containers-0.2.7.0-8d62fe61f7bd9f027cec5b56846824b6 -package-id vty-5.4.0-292091ebfc7c89421dbdc182364d1793 -package-id word-trie-0.3.0-0bc144d0f3fb72b6ebafc7819ba67329 -package-id xdg-basedir-0.2.2-356fe621703f556973436d1404327c9d -package-id yi-language-0.2.0-3956eaa35c167ee37e34390fd9974e7b -package-id yi-rope-0.7.0.1-462d72a8fc94776a2537f88cb4fdcc89 -XHaskell2010 -XNondecreasingIndentation Yi Yi.Boot Yi.Boot.Internal Yi.Buffer Yi.Buffer.Adjusted Yi.Buffer.HighLevel Yi.Buffer.Indent Yi.Buffer.Normal Yi.Buffer.Misc Yi.Buffer.Region Yi.Buffer.TextUnit Yi.Buffer.Undo Yi.Command Yi.Command.Help Yi.Completion Yi.Config Yi.Config.Default Yi.Config.Misc Yi.Config.Lens Yi.Config.Simple Yi.Config.Simple.Types Yi.Core Yi.Debug Yi.Dired Yi.Editor Yi.Eval Yi.Event Yi.File Yi.History Yi.Hoogle Yi.Hooks Yi.IReader Yi.IncrementalParse Yi.Interact Yi.JumpList Yi.Keymap Yi.Keymap.Completion Yi.Keymap.Cua Yi.Keymap.Emacs Yi.Keymap.Emacs.KillRing Yi.Keymap.Emacs.Utils Yi.Keymap.Keys Yi.Keymap.Vim Yi.Keymap.Vim.Common Yi.Keymap.Vim.Digraph Yi.Keymap.Vim.Eval Yi.Keymap.Vim.EventUtils Yi.Keymap.Vim.Ex Yi.Keymap.Vim.Ex.Commands.Common Yi.Keymap.Vim.Ex.Commands.Buffer Yi.Keymap.Vim.Ex.Commands.Buffers Yi.Keymap.Vim.Ex.Commands.BufferDelete Yi.Keymap.Vim.Ex.Commands.Cabal Yi.Keymap.Vim.Ex.Commands.Delete Yi.Keymap.Vim.Ex.Commands.Edit Yi.Keymap.Vim.Ex.Commands.Global Yi.Keymap.Vim.Ex.Commands.GotoLine Yi.Keymap.Vim.Ex.Commands.Help Yi.Keymap.Vim.Ex.Commands.Make Yi.Keymap.Vim.Ex.Commands.Nohl Yi.Keymap.Vim.Ex.Commands.Paste Yi.Keymap.Vim.Ex.Commands.Quit Yi.Keymap.Vim.Ex.Commands.Reload Yi.Keymap.Vim.Ex.Commands.Shell Yi.Keymap.Vim.Ex.Commands.Sort Yi.Keymap.Vim.Ex.Commands.Substitute Yi.Keymap.Vim.Ex.Commands.Tag Yi.Keymap.Vim.Ex.Commands.Undo Yi.Keymap.Vim.Ex.Commands.Write Yi.Keymap.Vim.Ex.Commands.Yi Yi.Keymap.Vim.Ex.Types Yi.Keymap.Vim.Ex.Eval Yi.Keymap.Vim.ExMap Yi.Keymap.Vim.InsertMap Yi.Keymap.Vim.MatchResult Yi.Keymap.Vim.Motion Yi.Keymap.Vim.NormalMap Yi.Keymap.Vim.NormalOperatorPendingMap Yi.Keymap.Vim.Operator Yi.Keymap.Vim.ReplaceMap Yi.Keymap.Vim.ReplaceSingleCharMap Yi.Keymap.Vim.Search Yi.Keymap.Vim.SearchMotionMap Yi.Keymap.Vim.StateUtils Yi.Keymap.Vim.StyledRegion Yi.Keymap.Vim.Tag Yi.Keymap.Vim.TextObject Yi.Keymap.Vim.Utils Yi.Keymap.Vim.VisualMap Yi.KillRing Yi.Layout Yi.Main Yi.MiniBuffer Yi.Misc Yi.Mode.Abella Yi.Mode.Buffers Yi.Mode.Compilation Yi.Mode.GHCi Yi.Mode.Haskell Yi.Mode.Haskell.Dollarify Yi.Mode.IReader Yi.Mode.Interactive Yi.Mode.JavaScript Yi.Mode.Latex Yi.Modes Yi.Monad Yi.Paths Yi.PersistentState Yi.Process Yi.Rectangle Yi.Snippets Yi.Snippets.Haskell Yi.Search Yi.Search.Internal Yi.String Yi.Syntax.Driver Yi.Syntax.Haskell Yi.Syntax.JavaScript Yi.Syntax.Latex Yi.Syntax.Layout Yi.Syntax.OnlineTree Yi.Syntax.Paren Yi.Syntax.Tree Yi.Syntax.Strokes.Haskell Yi.Tab Yi.Tag Yi.TextCompletion Yi.Types Yi.UI.Common Yi.UI.Batch Yi.UI.SimpleLayout Yi.UI.TabBar Yi.UI.Utils Yi.Verifier.JavaScript Yi.Window Yi.Char.Unicode Yi.UI.Vty Yi.UI.Vty.Conversions Paths_yi Yi.Buffer.Implementation Parser.Incremental Control.Exc Data.DelayList System.CanonicalizePath System.FriendlyPath -Wall -fno-warn-orphans -ferror-spans 2>&1 | vim -
```

```strace
open("/nix/store/b7i1r1vfygnjig3xx42v4snrim1mzy7i-gmp-6.1.0/lib/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/nix/store/phffgv3pwihmpdyk8xsz3wv8ydysch8w-glibc-2.23/lib/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/nix/store/kxac9yv62zff2pj6k1j4d6hiz8jdi2f3-gcc-5.3.0-lib/lib/tls/x86_64/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/nix/store/kxac9yv62zff2pj6k1j4d6hiz8jdi2f3-gcc-5.3.0-lib/lib/tls/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/nix/store/kxac9yv62zff2pj6k1j4d6hiz8jdi2f3-gcc-5.3.0-lib/lib/x86_64/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/nix/store/kxac9yv62zff2pj6k1j4d6hiz8jdi2f3-gcc-5.3.0-lib/lib/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 10
open("/nix/store/phffgv3pwihmpdyk8xsz3wv8ydysch8w-glibc-2.23/lib/libstdc++.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/nix/store/phffgv3pwihmpdyk8xsz3wv8ydysch8w-glibc-2.23/lib/libstdc++.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
write(2, "<command line>: can't load .so/."..., 128<command line>: can't load .so/.DLL for: libstdc++.so (libstdc++.so: cannot open shared object file: No such file or directory)
```
It finds `libstdc++.so` thing but somehow isn't happy with it.

**Comment by volhovM** [comment] 2016-05-03 17:51
Experiencing the same problem on nixos-unstable with my own haskell project (`stack --nix`).

**Comment by luispedro** [comment] 2016-05-04 07:54
As @volhovM I saw this in my own haskell code. Here's a workaround:

    ln -s $(gcc --print-file-name=libstdc++.so)

which creates a link in the current directory.

**Comment by vcunat** [comment] 2016-05-04 09:12
> [nix-shell:~/src/haskell/yi]$ gcc --print-file-name=libstdc++.so
> libstdc++.so

This seems the root cause of all this, probably a regression since splitting `gcc`.

**Comment by vcunat** [comment] 2016-05-04 09:28
I think we need this:
```diff
diff --git a/pkgs/build-support/cc-wrapper/default.nix b/pkgs/build-support/cc-wrapper/default.nix
index 6cdd047..3af5a74 100644
--- a/pkgs/build-support/cc-wrapper/default.nix
+++ b/pkgs/build-support/cc-wrapper/default.nix
@@ -112,7 +112,7 @@ stdenv.mkDerivation {
         ccLDFlags+=" -L${cc_solib}/lib64"
         ccCFlags+=" -B${cc_solib}/lib64"
       fi
-      ccLDFlags+=" -L${cc_solib}/lib"
+      ccLDFlags+=" -B${cc_solib}/lib"
 
       ${optionalString cc.langVhdl or false ''
         ccLDFlags+=" -L${zlib.out}/lib"
```

According to `man gcc`, directories with libraries for the compiler itself should be specified by `-B`. `--print-file-name=libstdc++.so` seems to work after I add that flag. (This is a stdenv rebuild, unfortunately.)

**Comment by peti** [comment] 2016-05-04 09:31
Nice catch. Thank you!

**Comment by vcunat** [comment] 2016-05-04 09:40
:-) But that diff won't work for some reason.

**Comment by vcunat** [comment] 2016-05-04 09:46
Yeah, this one is promising:
```diff
diff --git a/pkgs/build-support/cc-wrapper/default.nix b/pkgs/build-support/cc-wrapper/default.nix
index 6cdd047..92be4fc 100644
--- a/pkgs/build-support/cc-wrapper/default.nix
+++ b/pkgs/build-support/cc-wrapper/default.nix
@@ -113,6 +113,7 @@ stdenv.mkDerivation {
         ccCFlags+=" -B${cc_solib}/lib64"
       fi
       ccLDFlags+=" -L${cc_solib}/lib"
+      ccCFlags+=" -B${cc_solib}/lib"
 
       ${optionalString cc.langVhdl or false ''
         ccLDFlags+=" -L${zlib.out}/lib"
```

I'll test building stdenv at least.

**Comment by vcunat** [comment] 2016-05-04 11:24
Yeah, with the last diff, stdenv and some testing c++ stuff seem OK, and `--print-file-name=libstdc++.so` as well. I would stage it, but I think we should first find a fix for the mass breakage on staging.

**Comment by peti** [comment] 2016-05-04 11:43
@vcunat, I've fixed that a minute ago. I merged a commit which broke stdenv. :-( It's reverted now.

**Comment by vcunat** [comment] 2016-05-04 12:30
Staged the fix. I haven't tested building `yi`, but I believe at least the `--print*` part of problem is gone now.

**Comment by jagajaga** [comment] 2016-05-04 18:36
@vcunat so it seems to be fixed?

**Comment by volhovM** [comment] 2016-05-05 03:33
I've applied https://github.com/NixOS/nixpkgs/commit/2cbb7bf9d1ce519a480880f257cc569fbe4e6269 to teamspeak (just installed teamspeak_client from the right branch) and it doesn't fail with this error anymore.

**Comment by vcunat** [comment] 2016-05-05 05:29
The Yi problem is probably fixed. I don't know what was wrong with teamspeak.

**Comment by volhovM** [comment] 2016-05-05 05:42
@vcunat it was failing with the same error as Yi (no `libstd++.so.6`).

**Comment by vcunat** [comment] 2016-05-05 05:53
@volhovM: I would expect that's because of line
```
--set-rpath ${stdenv.lib.makeLibraryPath deps}:$(cat $NIX_CC/nix-support/orig-cc)/${libDir} \
```
as libstdc++ is no longer on that RPATH after splitting gcc, but if you say it's fixed now...

**Comment by jagajaga** [comment] 2016-05-12 12:10
Just compiled `yi` with https://github.com/NixOS/nixpkgs/commit/2cbb7bf9d1ce519a480880f257cc569fbe4e6269. It worked
```
yi --version
yi 0.12.4
```

So let's merge this commit into master asap, @vcunat.

**Closed** 2016-05-13 08:33 UTC
Labels: 0.kind: bug, 6.topic: closure-size
