### ISSUE TITLE
dead link for 'real-world NixOS configuration files' in manual

### ISSUE THREAD

**Issue by gour** [NixOS/nixpkgs#14559] opened 2016-04-09 18:30 UTC
## Issue description

Link for [Examples of real-world NixOS configuration files](https://nixos.org/repos/nix/configurations/trunk/) in NixOS [manual](http://nixos.org/nixos/manual/index.html#sec-installation) gives 404 error.

**Comment by joachifm** [comment] 2016-04-09 18:33
Duplicate of https://github.com/NixOS/nixpkgs/issues/14522, fixed by https://github.com/NixOS/nixpkgs/commit/678e1955b10c7d00f86cb2253f16f9ebaee064c5

**Closed by joachifm** 2016-04-09 18:33 UTC
