### ISSUE TITLE
Thunderbird + Enigmail not able to interact with gpg-agent because of pinentry - KDE plasma

### ISSUE THREAD

**Issue by 1000101** [NixOS/nixpkgs#72839] opened 2019-11-05 15:59 UTC
**Describe the bug**
Thunderbird+Enigmail is not able to open encrypted mails.
Maybe relates to https://github.com/NixOS/nixpkgs/issues/72765

**To Reproduce**
1. Open Thunderbird (with Enigmail addon)
2. Open encrypted mail
3. Get error

```
GnuPG cannot query your passphrase via pinentry.

This is a system setup or configuration error that prevents Enigmail from working properly and cannot be fixed automatically.
```

**Expected behavior**
Passphrase dialog shows up.

**Screenshots**
![image](https://user-images.githubusercontent.com/791309/68223215-aceba580-ffec-11e9-8ba7-76b04ccb411d.png)

**Additional context**
I'm using KDE plasma but also have gnome3 and gdm enabled. Removing (commenting) any or each of those doesn't help. Fresh installations of this unstable version (without having gnome and gdm previously enabled) do work properly.

```
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.plasma5.enable = true;
  services.xserver.desktopManager.gnome3.enable = true;
```

**Metadata**
- system: `"x86_64-linux"`
 - host os: `Linux 4.19.81, NixOS, 20.03pre200231.7827d3f4497 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre200231.7827d3f4497"`
 - channels(b1000101): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by jtojnar** [comment] 2019-11-05 16:26
This is indeed a duplicate of #72765. Make sure you have `programs.gnupg.agent.enable = true;` in your `configuration.nix` as per [release notes](https://github.com/NixOS/nixpkgs/blob/a692029726e85656dec6e350b9c4a90cfa0c43b8/nixos/doc/manual/release-notes/rl-2003.xml#L95-L100), and then kill the running `gnupg-agent`. (Also make sure you are not setting `GNUPGHOME` environment variable.)

**Closed** 2019-11-05 16:26 UTC
Labels: 0.kind: bug

**Comment by 1000101** [comment] 2019-11-05 16:53
Adding ```programs.gnupg.agent.enable = true;``` did the trick, thanks.
