### ISSUE TITLE
urllib3 broken in darwin-aarch64

### ISSUE THREAD

**Issue by dbarrosop** [NixOS/nixpkgs#178954] opened 2022-06-25 08:08 UTC
### Describe the bug

Due to commit https://github.com/NixOS/nixpkgs/commit/292269900315d5b952a99ec95aa4ccfc099952e0 urllib3 is broken on darwin-aarch64

### Steps To Reproduce
1. `nix-env -iA nixpkgs.python310Packages.urllib3`

### Expected behavior

Package should work like it used to prior to that commit

### Screenshots

```
$ nix-env -iA nixpkgs.python310Packages.urllib3
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
replacing old 'python3.10-urllib3-1.26.9'
installing 'python3.10-urllib3-1.26.9'
error: Package ‘python3.10-pyopenssl-22.0.0’ in /nix/store/xym41kzvwzfp8amdxrqk3fqz0vq4fqm7-nixpkgs/nixpkgs/pkgs/development/python-modules/pyopenssl/default.nix:73 is marked as broken, refusing to evaluate.

       a) To temporarily allow broken packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_BROKEN=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowBroken = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowBroken = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```

### Additional context

N/A

### Notify maintainers

@SuperSandro2000 @jonringer 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
these 2 paths will be fetched (0.34 MiB download, 2.06 MiB unpacked):
  /nix/store/ja4i3arjc9mi56lqlcm21xhdbzr5qa7i-bash-interactive-5.1-p16-dev
  /nix/store/kqq0a2hmafs7sjlixvkdw81blqs8758k-bash-interactive-5.1-p16-doc
copying path '/nix/store/kqq0a2hmafs7sjlixvkdw81blqs8758k-bash-interactive-5.1-p16-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/ja4i3arjc9mi56lqlcm21xhdbzr5qa7i-bash-interactive-5.1-p16-dev' from 'https://cache.nixos.org'...
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.5.0, macOS 12.4`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.9.1`
 - channels(dbarroso): `"darwin, home-manager, nixpkgs"`
 - nixpkgs: `/Users/dbarroso/.nix-defexpr/channels/nixpkgs`
```

**Comment by azuwis** [comment] 2022-06-25 13:15
Is this why there were 8933 remove packages on aarch64-darwin recently? https://hydra.nixos.org/eval/1767877#tabs-removed

**Comment by dbarrosop** [comment] 2022-06-25 14:39
I wouldn’t be surprised. It is a very popular library in the python world. In my case it broke several applications.

**Comment by SuperSandro2000** [comment] 2022-06-25 20:36
> urllib3 broken in darwin-aarch64

urllib3 is not broken on m1 macs but one of its dependencies, pyopenssl, has no upstream support for m1 macs. See https://github.com/pyca/pyopenssl/issues/873

and dupe of #175875

**Closed by SuperSandro2000** 2022-06-25 20:36 UTC
Labels: 0.kind: bug, 6.topic: darwin

**Comment by dbarrosop** [comment] 2022-06-26 05:44
I don’t think this is a dupe. I understand the root cause but urllib3 worked completely fine until the aforementioned commit was introduced, hence breaking urllib3. Now thousands of apps that worked completely fine are no longer available for M1.

> but one of its dependencies, pyopenssl, has no upstream support for m1 macs

That is not accurate, pyopenssl is an OPTIONAL dependency that isn’t part of the standard installation:

https://github.com/urllib3/urllib3/blob/main/pyproject.toml#L40

**Comment by dbarrosop** [comment] 2022-06-26 06:48
FWIW I opened the following PR to address this issue:

https://github.com/NixOS/nixpkgs/pull/179159

Thanks!
