### ISSUE TITLE
error: build of ‘/nix/store/nln8dljnm2w1cykx5zx1i2zxd6vw9vhx-pandoc-1.13.2.1.drv’ failed

### ISSUE THREAD

**Issue by nomosyn** [NixOS/nixpkgs#7646] opened 2015-04-30 14:28 UTC
![capture d ecran 2015-03-20 a 19 44 18](https://cloud.githubusercontent.com/assets/2693150/6758603/8c764e60-cf39-11e4-9e8a-ecab4b2e8136.png)

```
$ cd .../nixpkgs

$ git rev-parse HEAD
4cdb4a4fef93b54dd41aab93d333c703df4d5803

$ nix-env -u

... [lots of stuff] ...
Cases: 7  Tried: 7  Errors: 1  Failures: 0
Test suite test-zip-archive: FAIL
Test suite logged to: dist/test/zip-archive-0.2.3.7-test-zip-archive.log
0 of 1 test suites (0 of 1 test cases) passed.
builder for ‘/nix/store/02sq40ds8vj3v9z2d1lrglr6qi214j49-haskell-zip-archive-0.2.3.7.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/nln8dljnm2w1cykx5zx1i2zxd6vw9vhx-pandoc-1.13.2.1.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/nln8dljnm2w1cykx5zx1i2zxd6vw9vhx-pandoc-1.13.2.1.drv’ failed
```

**Comment by copumpkin** [comment] 2015-04-30 22:09
I don't know what's up here, but it looks like there might be more information on the 1 error in your "[lots of stuff]" redaction. Can you dig up the specific thing that failed for someone to look at?

**Comment by joelteon** [comment] 2015-05-01 01:37
This is probably because of the libiconv dylib version mismatch, right?

**Comment by nomosyn** [comment] 2015-05-01 15:41
Well, this is all I have (bellow).  Tell me if you need anything else :smile: 

```
$ nix-env -u
upgrading ‘pandoc-1.13.2’ to ‘pandoc-1.13.2.1’
upgrading ‘git-minimal-2.3.5’ to ‘git-minimal-2.3.6’
upgrading ‘nix-1.8’ to ‘nix-1.9pre4100_4bbcfaf’
these derivations will be built:
  /nix/store/02sq40ds8vj3v9z2d1lrglr6qi214j49-haskell-zip-archive-0.2.3.7.drv
  /nix/store/0894sjs9nc11cinfrmrb08hlnpgzz844-test-framework-quickcheck2-0.3.0.3-r1.cabal.drv
  /nix/store/4669a6hhwd621fym5p5a5sim7yw1arq5-tasty-0.10.1.1.tar.gz.drv
  /nix/store/fgjwdsxaixck5a31ifj7ypcy0315kyjb-haskell-tasty-0.10.1.1.drv
  /nix/store/0899bfmfv7sn2d45lqskp3fysa63mbpl-haskell-tasty-ant-xml-1.0.1.drv
  /nix/store/9cjxn41nn0cfil50rqgi78j8wa79p79b-haskell-tasty-hunit-0.9.2.drv
  /nix/store/1jznwv7zvsvp7hk238l4zg97kypcsij7-haskell-tasty-quickcheck-0.8.3.2.drv
  /nix/store/aq8pg7xf96a1x8lmrni4b2bs74mw0ksp-python-2.7.9.drv
  /nix/store/1q5d7mgllp63y5s9v7w4cbf0hv0z7grh-asciidoc-8.6.9.drv
  /nix/store/9yj0vlqsr6rbn8xqh11xxx6bzw9qjlx2-transformers-base-0.4.4-r1.cabal.drv
  /nix/store/w5161vsnydkb0lch10bh9rr06x2xqsgx-haskell-transformers-base-0.4.4.drv
  /nix/store/rlyr3j22dc7r0zs3zpfr5l452ip2cm2g-haskell-monad-control-1.0.0.4.drv
  /nix/store/5hvschm0ccgb7vwarzxkb2lr6xdcwh9p-haskell-lifted-base-0.2.3.6.drv
  /nix/store/36r36xkcq64jgwkiqxzzmh0bpd6inibx-haskell-enclosed-exceptions-1.0.1.1.drv
  /nix/store/h17qzpfn7sw0nzivjdk9pha2hzlnngb2-haskell-test-framework-quickcheck2-0.3.0.3.drv
  /nix/store/7jnjsb4c465j4sl3v043hlxhsm83cmwz-haskell-vector-0.10.12.3.drv
  /nix/store/89pqqq66zfy9vvs4jybs4074kw2mpb8p-haskell-hashable-1.2.3.2.drv
  /nix/store/xqmkzmsqhjfnvrhnk0f6d515gqsqm9ll-haskell-tasty-smallcheck-0.8.0.1.drv
  /nix/store/l40qixrncqmj98zrakysmcjy78fpw8c0-haskell-scientific-0.3.3.8.drv
  /nix/store/4axwvwig34cvdxvdx0xzc1rr4zl8r6j6-haskell-attoparsec-0.12.1.6.drv
  /nix/store/krv8w312wdbgmvrixx6012pjkz6s3bxd-haskell-unordered-containers-0.2.5.1.drv
  /nix/store/96fbwrmgj8lbvj81ccqkq6mjgfcqwdw9-haskell-aeson-0.8.0.2.drv
  /nix/store/q45850hk87qd38319m9r6h1qb4birwr1-haskell-uniplate-1.6.12.drv
  /nix/store/pf663cj1fhp9z4fqpll1sz09xsk183s6-haskell-exceptions-0.8.0.2.drv
  /nix/store/4hc4f0vwni8dk55cxb69fz06q9lxl1mq-haskell-temporary-rc-1.2.0.3.drv
  /nix/store/95kf82nd3bk4fi9v7gm3v0mvw4nkzyj2-haskell-tasty-golden-2.3.0.1.drv
  /nix/store/rqd0xvb52wj889n4phxbd76czgvg1h56-haskell-haskell-src-exts-1.16.0.1.drv
  /nix/store/nz2mqmn9ay084rplgdx437n64bwc7b6q-haskell-haskell-src-meta-0.6.0.9.drv
  /nix/store/495cmq382ic4fz1lg3varhnaxg7lknfd-haskell-aeson-qq-0.7.4.drv
  /nix/store/dnqh97h0jl4kv96m6p15fgd4p26g3v8s-haskell-resourcet-1.1.4.1.drv
  /nix/store/lp623dpkwnzfwi4n0r282hmrqcypbnia-haskell-semigroups-0.16.2.2.drv
  /nix/store/jj5h3zw9wpf69abr1fg1p06kpmaqx8r5-haskell-void-0.7.drv
  /nix/store/xpwpr7ag0i5rwbirgifzqv3zjy16r24l-haskell-conduit-1.2.4.1.drv
  /nix/store/zihi3nns25w44bdzynf2bqnvccij2m47-yaml-0.8.11.tar.gz.drv
  /nix/store/1wq8vpzkg1lwgd42sz7zv01vmr6avcsx-haskell-yaml-0.8.11.drv
  /nix/store/9ib49afi3x7pd4k9lhajzgd5f7w7gzph-haskell-hourglass-0.2.9.drv
  /nix/store/c4ral52a7fr5rp1ps9mnhhadh54i0hys-haskell-asn1-types-0.3.0.drv
  /nix/store/7k7dqbrdkldx51w64z1amy6y9sdva0z1-haskell-asn1-encoding-0.9.0.drv
  /nix/store/26v7jp5vvl10lbn3qaifxcwz5x1czxn3-haskell-asn1-parse-0.9.0.drv
  /nix/store/5wqrpgq5i9ypdp3ji7yfd8bcc1flvqik-w3m-0.5.3.drv
  /nix/store/5lsj9nsmxrvw52s8c0hpswbxrzby4z3x-xmlto-0.0.26.drv
  /nix/store/zmlqfnv05092wzrcyfblgpfw1nnn5f9y-opensp-1.5.2.drv
  /nix/store/2fg721sm443hbfbg0i5qyi3xjhmfvjqn-docbook2X-0.8.8.drv
  /nix/store/9i131qj95ggmg6fm7xpmi8znz4wcn97s-haskell-crypto-random-0.0.9.drv
  /nix/store/33vrjvvnj2ps9sjz9c5djxay1vy2dl2j-haskell-crypto-numbers-0.2.7.drv
  /nix/store/3j86jqahq9ihi1w5v6wnb34yw45yzp29-haskell-cryptohash-0.11.6.drv
  /nix/store/d12lm5bqp13im1h151025a7iywpxv0n5-haskell-base64-bytestring-1.0.0.1.drv
  /nix/store/l462wgnlyqg7b0yx9br6mf7a4g9ccg7r-streaming-commons-0.1.12.tar.gz.drv
  /nix/store/gn6j94cpq64zvmib2iqx1vpb3i4lqf1s-haskell-streaming-commons-0.1.12.drv
  /nix/store/hmvb28incam59rnvq1hhp88ifbyz63g2-haskell-case-insensitive-1.2.0.4.drv
  /nix/store/jslimxfpf44vd89lwp17c5gwi7i1a8gz-haskell-cookie-0.4.1.5.drv
  /nix/store/w978jh0i2gx8w1m9x7faljwya3cm55m3-haskell-quickcheck-instances-0.3.11.drv
  /nix/store/yvjgiyk70jkfy9c6v0hkw6mxn1jlkq0n-haskell-http-types-0.8.6.drv
  /nix/store/4cpbyvzk0kd3flpn7xcaq481lkk2gzs0-haskell-http-client-0.4.11.2.drv
  /nix/store/lnxdpk72bxg16rrglx2s646fwd62qcn7-haskell-crypto-pubkey-types-0.4.3.drv
  /nix/store/4ya4wjgc92kibx2cg7bg98736faxzxgg-haskell-crypto-pubkey-0.2.8.drv
  /nix/store/pb5q96l789ccg5zlpa6wmdwf4039rj3m-sqlite-autoconf-3080900.tar.gz.drv
  /nix/store/8nsv6gdy4nhcmdar7ny2d29gf2258k6i-sqlite-3.8.9.drv
  /nix/store/6dc99hhs6qql82ds3kqn0fqxqfj1117j-perl-DBD-SQLite-1.44.drv
  /nix/store/qqxs9giqs864lsz6c2mkn2c5547h94x4-haskell-crypto-cipher-tests-0.0.11.drv
  /nix/store/6yw001kwlfi9js9mffxz14m5fdznx26c-haskell-cipher-des-0.0.6.drv
  /nix/store/729vd713aa9ajir5jhv2fi7hnqnqmrfs-nix-1.9pre4100_4bbcfaf.drv
  /nix/store/9s86ajy7qbaxnairdm01qp265mr5saj2-haskell-pem-0.2.2.drv
  /nix/store/cbwjyid290k5n42awrq5zkdmgfkrfgvj-haskell-x509-1.5.0.1.drv
  /nix/store/7s57flhxhxqzv3gy2wazkv5pcfp218l9-haskell-x509-store-1.5.0.drv
  /nix/store/8zhk9fhs19mn835dx42cbnjlwk1d2yci-haskell-cipher-rc4-0.1.4.drv
  /nix/store/gsyrmgijicy732wirl2w3al4g3s1090x-haskell-temporary-1.2.0.3.drv
  /nix/store/k71vbkk80hc5rp8yk6ii1142927cqpq8-haskell-pandoc-types-1.12.4.2.drv
  /nix/store/calgzvxpq94ay5cplzs83r9dchsmbsxl-haskell-texmath-0.8.1.drv
  /nix/store/im052kgsnzg1hxhxkvqip7cn9q85r7d8-haskell-x509-validation-1.5.1.drv
  /nix/store/xinldbwc29xci09cvxy2xqafiinsn6vn-haskell-cipher-aes-0.2.10.drv
  /nix/store/n3w69qrhkhpz66j3vlpsckiwmcxwff5c-haskell-tls-1.2.17.drv
  /nix/store/s3zraf4q2jgnc8lgsls4r1yf01cxppyf-haskell-x509-system-1.5.0.drv
  /nix/store/cigrzhn2q8y2qp7f8hfx0qj96fp4df4a-haskell-connection-0.2.4.drv
  /nix/store/cxh4imkwhq1kjnpfdpn7x8kgj5g2f2zl-haskell-SHA-1.6.4.2.drv
  /nix/store/ghjkq3npxqk1vi9s3z39wwzljg2kvq1x-haskell-blaze-markup-0.6.3.0.drv
  /nix/store/cydsx9g848j4lccd20r764j73yil07wv-haskell-blaze-html-0.7.1.0.drv
  /nix/store/g4pk8r1jvq2f11m8hja7sznx8g45wrw3-haskell-JuicyPixels-3.2.4.drv
  /nix/store/j79rmc5s35rrwqj26x0lls75wfhlgm1j-git-2.3.6.drv
  /nix/store/kam7xbgpccskr15blc62012hdqvr72qz-haskell-highlighting-kate-0.5.15.drv
  /nix/store/qi0acf8caz61l8icl81a3pndnmi6f459-haskell-http-client-tls-0.2.2.drv
  /nix/store/nln8dljnm2w1cykx5zx1i2zxd6vw9vhx-pandoc-1.13.2.1.drv
building path(s) ‘/nix/store/fn4g6cbmxzyss5g5gb53ay1ccmh5ghnl-haskell-zip-archive-0.2.3.7’
setupCompilerEnvironmentPhase
Build with /nix/store/jlzqjzv88kzvn94prd8apskyljqigjjx-ghc-7.10.1.
unpacking sources
unpacking source archive /nix/store/f11wmzwjdqg28y7skabkdbzk2hgj4hv1-zip-archive-0.2.3.7.tar.gz
source root is zip-archive-0.2.3.7
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/private/var/folders/t7/nkp35ryj76d5p2j0w1yn2sdm0000gn/T/nix-build-haskell-zip-archive-0.2.3.7.drv-0/package.conf.d -j4 -threaded
[1 of 1] Compiling Main             ( Setup.lhs, /private/var/folders/t7/nkp35ryj76d5p2j0w1yn2sdm0000gn/T/nix-build-haskell-zip-archive-0.2.3.7.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/fn4g6cbmxzyss5g5gb53ay1ccmh5ghnl-haskell-zip-archive-0.2.3.7 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --with-gcc=clang --package-db=/private/var/folders/t7/nkp35ryj76d5p2j0w1yn2sdm0000gn/T/nix-build-haskell-zip-archive-0.2.3.7.drv-0/package.conf.d --ghc-option=-optl=-Wl,-headerpad_max_install_names --ghc-option=-j4 --disable-split-objs --disable-library-profiling --enable-shared --enable-library-vanilla --enable-executable-dynamic --enable-tests
Configuring zip-archive-0.2.3.7...
Flags chosen: executable=False, splitbase=True
Dependency HUnit -any: using HUnit-1.2.5.2
Dependency array -any: using array-0.5.1.0
Dependency base >=4.2 && <5: using base-4.8.0.0
Dependency binary >=0.5: using binary-0.7.3.0
Dependency bytestring >=0.9.0: using bytestring-0.10.6.0
Dependency containers -any: using containers-0.5.6.2
Dependency digest >=0.0.0.1: using digest-0.0.1.2
Dependency directory >=1.1: using directory-1.2.2.0
Dependency filepath -any: using filepath-1.4.0.0
Dependency mtl -any: using mtl-2.2.1
Dependency old-time -any: using old-time-1.1.0.3
Dependency pretty -any: using pretty-1.1.2.0
Dependency process -any: using process-1.2.3.0
Dependency text >=0.11: using text-1.2.0.4
Dependency time -any: using time-1.5.0.1
Dependency unix -any: using unix-2.7.1.0
Dependency zip-archive -any: using zip-archive-0.2.3.7
Dependency zlib -any: using zlib-0.5.4.2
Using Cabal-1.22.2.0 compiled by ghc-7.10
Using compiler: ghc-7.10.1
Using install prefix:
/nix/store/fn4g6cbmxzyss5g5gb53ay1ccmh5ghnl-haskell-zip-archive-0.2.3.7
Binaries installed in:
/nix/store/fn4g6cbmxzyss5g5gb53ay1ccmh5ghnl-haskell-zip-archive-0.2.3.7/bin
Libraries installed in:
/nix/store/fn4g6cbmxzyss5g5gb53ay1ccmh5ghnl-haskell-zip-archive-0.2.3.7/lib/ghc-7.10.1/zip-archive-0.2.3.7
Private binaries installed in:
/nix/store/fn4g6cbmxzyss5g5gb53ay1ccmh5ghnl-haskell-zip-archive-0.2.3.7/libexec
Data files installed in:
/nix/store/fn4g6cbmxzyss5g5gb53ay1ccmh5ghnl-haskell-zip-archive-0.2.3.7/share/x86_64-osx-ghc-7.10.1/zip-archive-0.2.3.7
Documentation installed in:
/nix/store/fn4g6cbmxzyss5g5gb53ay1ccmh5ghnl-haskell-zip-archive-0.2.3.7/share/doc/x86_64-osx-ghc-7.10.1/zip-archive-0.2.3.7
Configuration files installed in:
/nix/store/fn4g6cbmxzyss5g5gb53ay1ccmh5ghnl-haskell-zip-archive-0.2.3.7/etc
No alex found
Using ar found on system at:
/nix/store/ip00ngw8i2xww506r65swcyfd2nqpxqw-cctools-port-862/bin/ar
No c2hs found
No cpphs found
Using gcc version 4.2.1 given by user at:
/nix/store/9k42mhsdwa11jfygvgik59bhg9pzsrhm-clang-wrapper-3.6.0/bin/clang
Using ghc version 7.10.1 found on system at:
/nix/store/jlzqjzv88kzvn94prd8apskyljqigjjx-ghc-7.10.1/bin/ghc
Using ghc-pkg version 7.10.1 found on system at:
/nix/store/jlzqjzv88kzvn94prd8apskyljqigjjx-ghc-7.10.1/bin/ghc-pkg
No ghcjs found
No ghcjs-pkg found
No greencard found
Using haddock version 2.16.0 found on system at:
/nix/store/jlzqjzv88kzvn94prd8apskyljqigjjx-ghc-7.10.1/bin/haddock
No happy found
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.67 found on system at:
/nix/store/jlzqjzv88kzvn94prd8apskyljqigjjx-ghc-7.10.1/bin/hpc
Using hsc2hs version 0.67 found on system at:
/nix/store/jlzqjzv88kzvn94prd8apskyljqigjjx-ghc-7.10.1/bin/hsc2hs
Using hscolour version 1.22 found on system at:
/nix/store/pmgn6b538wdrcibxlz137qkck77y6zsy-hscolour-1.22/bin/HsColour
No jhc found
Using ld found on system at:
/nix/store/9k42mhsdwa11jfygvgik59bhg9pzsrhm-clang-wrapper-3.6.0/bin/ld
No lhc found
No lhc-pkg found
No pkg-config found
Using strip found on system at:
/nix/store/ip00ngw8i2xww506r65swcyfd2nqpxqw-cctools-port-862/bin/strip
Using tar found on system at:
/nix/store/pn7ffaql4bfc5g7lalx7nc4d7h09r74j-gnutar-1.27.1/bin/tar
No uhc found
Using zip found on system at:
/nix/store/77mc1j52n90265v1arlq9yr3mx52p00n-zip-3.0/bin/zip
building
Building zip-archive-0.2.3.7...
Preprocessing library zip-archive-0.2.3.7...
[1 of 1] Compiling Codec.Archive.Zip ( src/Codec/Archive/Zip.hs, dist/build/Codec/Archive/Zip.o )
In-place registering zip-archive-0.2.3.7...
Preprocessing test suite 'test-zip-archive' for zip-archive-0.2.3.7...
[1 of 1] Compiling Main             ( tests/test-zip-archive.hs, dist/build/test-zip-archive/test-zip-archive-tmp/Main.dyn_o )

tests/test-zip-archive.hs:11:1: Warning:
    The import of ‘Control.Applicative’ is redundant
      except perhaps to import instances from ‘Control.Applicative’
    To import instances alone, use: import Control.Applicative()
Linking dist/build/test-zip-archive/test-zip-archive ...
running tests
Running 1 test suites...
Test suite test-zip-archive: RUNNING...
Cases: 7  Tried: 1  Errors: 0  Failures: 0dyld: Library not loaded: /nix/store/07ppnj3bx3ri0d3rk2ps6d0s0zgid1lj-libiconv-1.14/lib/libiconv.2.dylib
  Referenced from: /nix/store/w67mn56sr96g2w136n66x636qfmc86fx-libnatspec-0.2.6/lib/libnatspec.0.dylib
  Reason: Incompatible library version: libnatspec.0.dylib requires version 8.0.0 or later, but libiconv.2.dylib provides version 7.0.0
### Error in:   1                         
test-temp/test4.zip: openBinaryFile: does not exist (No such file or directory)
Cases: 7  Tried: 4  Errors: 1  Failures: 0  adding: LICENSE (deflated 46%)
  adding: src/ (stored 0%)
  adding: LICENSE (deflated 46%)
  adding: src/ (stored 0%)
  adding: src/Codec/ (stored 0%)
  adding: src/Codec/Archive/ (stored 0%)
  adding: src/Codec/Archive/Zip.hs (deflated 74%)
Cases: 7  Tried: 6  Errors: 1  Failures: 0  creating: test-temp/dir1
  creating: test-temp/dir1/dir2
 inflating: test-temp/dir1/dir2/hello
extracting: test-temp/dir1/hi
Cases: 7  Tried: 7  Errors: 1  Failures: 0
Test suite test-zip-archive: FAIL
Test suite logged to: dist/test/zip-archive-0.2.3.7-test-zip-archive.log
0 of 1 test suites (0 of 1 test cases) passed.
builder for ‘/nix/store/02sq40ds8vj3v9z2d1lrglr6qi214j49-haskell-zip-archive-0.2.3.7.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/nln8dljnm2w1cykx5zx1i2zxd6vw9vhx-pandoc-1.13.2.1.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/nln8dljnm2w1cykx5zx1i2zxd6vw9vhx-pandoc-1.13.2.1.drv’ failed
```

**Comment by copumpkin** [comment] 2015-05-01 19:24
Looks like what @joelteon said, thanks!

**Comment by nomosyn** [comment] 2015-05-02 20:51
Seems to pass now... but `nix-env -u` gives me an other error...

**Comment by gridaphobe** [comment] 2015-05-16 22:23
Reopening this since I'm running into it too on master.

It's quite strange, the `libiconv.dylib` referenced in the error **is** version 8.. Apple's libiconv is version 7, but I don't see any references to it :/

**Comment by gridaphobe** [comment] 2015-05-16 22:24
For the time being, I've locally disabled the testsuite for zip-archive, but that's clearly not a long-term solution

**Comment by nomosyn** [comment] 2015-05-17 06:50
Well I would close it because I have the same error again too and I opened an other issue here #7840 after closing this one.

So this issue and #7840 have the same symptoms and I would bet they have the same causes.

Then, if both of them are open, they are most likely duplicate of one an other.

**Comment by gridaphobe** [comment] 2015-05-17 10:03
I'd close the other one as a dup since this issue has a bit more context and discussion already :)

**Comment by peti** [comment] 2015-05-17 10:32
Duplicate of https://github.com/NixOS/nixpkgs/issues/7675.

**Closed by peti** 2015-05-17 10:32 UTC
Labels: darwin
