### ISSUE TITLE
haskell-ng.overrideScope drops all scopes except self

### ISSUE THREAD

**Issue by bennofs** [NixOS/nixpkgs#7873] opened 2015-05-17 17:40 UTC
Example:

```
nix-repl> ((import <nixpkgs> {}).haskellngPackages.callPackage ({ stdenv }: stdenv.lib.licenses.bsd3) {}).overrideScope (_: _: {})
error: anonymous function at "(string)":1:55 called without required argument ‘stdenv’, at "/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/customisation.nix":58:12

nix-repl> ((import <nixpkgs> {}).haskellngPackages.callPackage ({ stdenv }: stdenv.lib.licenses.bsd3) {})
{ deepOverride = «lambda»; fullName = "BSD 3-clause \"New\" or \"Revised\" License"; override = «lambda»; overrideDerivation = «lambda»; overrideScope = «lambda»; shortName = "bsd3"; spdxId = "BSD-3-Clause"; url = "http://spdx.org/licenses/BSD-3-Clause"; }
```

The reason is that in

```
callPackageWithScope = scope: drv: args: (stdenv.lib.callPackageWith scope drv args) // {
  overrideScope = f: callPackageWithScope (fix (extend scope.__unfix__ f)) drv args;
};

defaultScope = pkgs // pkgs.xlibs // pkgs.gnome // self;
callPackage = drv: args: callPackageWithScope defaultScope drv args;
```
`callPackageWithScope` will call `__unfix__` on `defaultScope`. But since only `self` has an `__unfix__` attribute, the resulting scope will not contain any attributes from `pkgs`, `pkgs.xlibs` or `pkgs.gnome` anymore, so only the attributes of self are left.

/cc @peti

**Comment by peti** [comment] 2015-05-17 19:07
Duplicate of https://github.com/NixOS/nixpkgs/issues/6192. In short: we have a fix for this issue, but Nix runs out of memory trying to evaluate the package set with that fix applied.

**Closed by peti** 2015-05-17 19:07 UTC
Labels: haskell
