### ISSUE TITLE
Nix package manager segmentation faults on linux_lqx

### ISSUE THREAD

**Issue by guzz46** [NixOS/nixpkgs#309508] opened 2024-05-06 08:58 UTC
### Describe the bug
The nix package manager segmentation faults when running the liquorix kernel

### Steps To Reproduce
1. Install linux_lqx
2. Reboot into linux_lqx
3. Open a terminal and run any nix command

### Expected behavior
The nix package manager to function

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.9, NixOS, 24.05 (Uakari), 24.05pre621993.25865a40d14b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-05-06 09:24
Duplicate of NixOS/nix#9725 which is solved in 2.21 onwards.

**Closed by eclairevoyant** 2024-05-06 09:24 UTC
Labels: 0.kind: bug
