### ISSUE TITLE
Pipenv can't install anything

### ISSUE THREAD

**Issue by marchgithub** [NixOS/nixpkgs#73489] opened 2019-11-16 09:37 UTC
**Describe the bug**
pipenv will fail to install because pip can't find its required modules.

**To Reproduce**
1. Install pipenv in your system packages.
2. Run pipenv install on a project with a Pipfile that has any dependencies.

**Expected behavior**
The pip script installed by pipenv should import its required modules correctly.

**Screenshots**
```[pipenv.exceptions.InstallError]: ['Traceback (most recent call last):', '  File "/home/$USER/.local/share/virtualenvs/[environment]/bin/pip", line 6, in <module>', '    from pip._internal.main import main', "ModuleNotFoundError: No module named 'pip._internal.main'"]```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.80, NixOS, 19.09.891.80b42e630b2 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels($USER): `"home-manager-19.09.1172.2d896998dc9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment] 2019-11-16 11:04
Duplicate of https://github.com/NixOS/nixpkgs/issues/71178

**Comment by FRidh** [comment] 2019-11-16 11:05
This issue for 19.09 though.

**Comment by FRidh** [comment] 2019-11-16 11:07
As I wrote in that issue, you need to come with a reproducible example.

**Comment by Kazimazi** [comment] 2019-11-16 12:20
try pipenv from the unstable channel till update hits stable

**Comment by jonringer** [comment] 2019-11-16 23:34
did the fixes get backported?

**Comment by pasqui23** [comment] 2020-01-07 15:27
@Kazimazi even pipenv from unstable has the same problem

**Comment by jonringer** [comment] 2020-01-07 17:32
IIRC, it's because you're getting a new version of pip in your closure, and pip refers to the new one instead of the one it was built against. Unfortunately pipenv hasn't been updated in over a year

**Comment by pasqui23** [comment] 2020-01-08 01:17
No,it was because for some reason I as installing it from stable

After doing `nix-env -f . -iA pipenv` it worked

**Comment by jonringer** [comment] 2020-01-08 02:53
going to close then, if someone would like to collect the necessary backports to bring this to stable, then it will be much appreciated. :)

**Closed by jonringer** 2020-01-08 02:53 UTC
Labels: 0.kind: bug, 6.topic: python
