### ISSUE TITLE
Package request: Sozi

### ISSUE THREAD

**Issue by Thatoo** [NixOS/nixpkgs#298183] opened 2024-03-22 22:04 UTC
**Project description**

 A "zooming" presentation editor . Sozi is a presentation tool for SVG documents.

**Metadata**

* homepage URL: http://sozi.baierouge.fr/
* source URL: https://github.com/sozi-projects/Sozi
* license: MPL-2.0 license 
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-03-23 02:36
duplicate of #292536

**Closed by eclairevoyant** 2024-03-23 02:36 UTC
Labels: 0.kind: packaging request
