### ISSUE TITLE
Build failure: calibre

### ISSUE THREAD

**Issue by Cal-Nine** [NixOS/nixpkgs#350670] opened 2024-10-23 08:22 UTC
### Steps To Reproduce

1. build calibre

### Build log
[Calibre Build Log.txt](https://github.com/user-attachments/files/17487530/Calibre.Build.Log.txt)

### Notify maintainers
@AndersonTorres

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.5, NixOS, 24.11 (Vicuna), 24.11pre690827.5633bcff0c61`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kilianar** [comment] 2024-10-23 10:14
This appears to be a duplicate of issue #349755, which was resolved in #349884.

**Closed** 2024-10-23 10:29 UTC
Labels: 2.status: duplicate, 0.kind: build failure
