### ISSUE TITLE
Build failure: nixpkgs.python39Packages.cartopy

### ISSUE THREAD

**Issue by rodrum** [NixOS/nixpkgs#220607] opened 2023-03-11 05:39 UTC
### Steps To Reproduce

1. Run `nix-env -iA  nixpkgs.python39Packages.cartopy`

### Build log

https://gist.github.com/rodrum/b925104a9cca4902eef7310b9a3187a6

### Additional context

I'm running nix under the available docker image.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/a2mfyh90szmc055ivfnv182b5a4naq90-nix-info
copying path '/nix/store/a2mfyh90szmc055ivfnv182b5a4naq90-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.12-300.fc37.x86_64`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by kirillrdy** [comment] 2023-03-11 23:35
@rodrum  I can confirm build failure inside `nixos/nix` docker image

this has been fixed in latest nixpkgs run `nix-channel --update`  and try again

**Comment by kirillrdy** [comment] 2023-03-12 01:03
@rodrum I've also noticed I get rather frequent crashes from inside docker, not sure what thats about, but it builds outside of docker

**Comment by rodrum** [comment] 2023-03-13 05:55
@kirillrdy Thank you! I'll try it with the new docker image tomorrow. Yeah, Docker seems to create some issues, I'm not certain why.

**Comment by rodrum** [comment] 2023-03-19 19:31
@kirillrdy I'm sorry I couldn't test this until today. After updating with `nix-channel --update` inside the docker container, and doing `nix-env -iA nixpkgs.python39Packages.cartopy`, I got a different error:

https://gist.github.com/rodrum/9bb3fa21117afaf9eb80d4e9eff88eac

**Comment by kirillrdy** [comment] 2023-03-20 10:21
@rodrum yes, looks like cartopy is broke again on master

while I am bisecting to find why it failed, to hopefully come up with a fix 

- python 3.9 is no longer built in hydra so there will be no pre compiled binaries coming cache.nixos.org, if you can, switch to 3.10 and 3.11
- while nixos/nix docker image works fine in most cases, I tend not to use it due to: disabled sandox and difficulty of setting up local caching
- building docker images locally outside of docker using nix seems to work much better, although has own disadvantages

What specifically are you trying to do ? since we know a very recent good commit hash for nixpkgs that has working cartopy we can build a docker image using nix.

**Comment by kirillrdy** [comment] 2023-03-22 21:15
- python 3.9 should work fine, you just need to compile more dependencies
- nix-env -i is only useful for packages that provide executables, eg has files in ./bin. I can see that cartopy has ./bin/cartopy_feature_download.py . you wont be able to import cartopy via `nix-env -i`

if you want enviroment where you can import cartopy you can use something like this
``` 
cat cartopy.nix 
{ pkgs ? import (fetchTarball "https://github.com/nixos/nixpkgs/archive/c34e72182fa2a19a471014b849430b84fdedfb3d.tar.gz") { } }:
pkgs.mkShell {
  buildInputs = with pkgs;[ (python3.withPackages (ps: [ ps.cartopy ])) ];
}

[kirillvr@osaka:~]$ nix-shell cartopy.nix 

[nix-shell:~]$ python3
Python 3.10.10 (main, Feb  7 2023, 12:19:31) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cartopy
```

meanwhile we'll keep this issue open, until cartopy is fixed on master

**Closed** 2023-03-31 22:50 UTC
Labels: 0.kind: build failure
