### ISSUE TITLE
General infrastructure for packaging Python packages that use PyO3 / maturin to build native Rust extensions

### ISSUE THREAD

**Issue by glittershark** [NixOS/nixpkgs#83614] opened 2020-03-28 18:51 UTC
I've encountered two separate (not currently provided by nixpkgs) python packages that are built with [maturin](https://github.com/PyO3/maturin) in the last week - [orjson](https://github.com/ijl/orjson) and [tokenizers](https://github.com/huggingface/tokenizers) - and I can only imagine both that there are more out there, and that more are coming. I have orjson packaged [very jankily](https://gist.github.com/glittershark/1d9e87fa2c713bdaa0aa69d4f6327415) by building it as a Rust crate directly using [naersk](https://github.com/nmattia/naersk), then stripping off the env vars from the resulting derivation and throwing them unceremoniously into `buildPythonPackage`. That *works*, but not in a way that I'd even dream of submitting it to nixpkgs - now that I've encountered my second package built using maturin it really is beginning to feel like this is something that `buildPythonPackage` should "just" handle transparently, the way it does Python packages with C extensions built-in. Anyone have any thoughts?

**Comment by FRidh** [comment] 2020-03-28 20:31
In the Python world it is common that a back-end or build tool (often `setuptools` but also `meson`) produces a wheel, and a front-end (typically `pip`) installs it. `buildPythonPackage` does this using hooks.

I'm unfamiliar with the packages in question. I suppose it's some extension modules, and then some Python code. Ideally a build tool is used that can build a wheel. If not, it indeed becomes hacky.

**Comment by FRidh** [comment] 2020-03-28 20:33
So orjson has a `pyproject.toml`. This is the new way for Python packaging. `buildPythonPackage` supports, just pass `format = "pyproject";`. You then need to include this `maturin` in `nativeBuildInputs`.

**Comment by bbigras** [comment] 2020-06-25 16:55
@FRidh any ideas why I get `ModuleNotFoundError: No module named 'maturin'` ?

Should I try to add it to `PATH`?

**default.nix**
```nix
let
  nixpkgs = import <nixpkgs> {};
in
nixpkgs.python3Packages.buildPythonPackage rec {
  name = "something-${version}";
  version = "0.0.1";
  format = "pyproject";

  nativeBuildInputs = [ nixpkgs.maturin ];

  src = ./.;
}
```

**pyproject.toml**
```toml
[build-system]
requires = ["maturin"]
build-backend = "maturin"
```

**log**
```
❯ nix-build .
these derivations will be built:
  /nix/store/4q9c2gja115rjyricl05x47v8c8gg6d8-python3.8-something-0.0.1.drv
building '/nix/store/4q9c2gja115rjyricl05x47v8c8gg6d8-python3.8-something-0.0.1.drv'...
Sourcing python-recompile-bytecode-hook.sh
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
unpacking sources
unpacking source archive /nix/store/9b60bppkmhghwvfjwag5z2lm5xvxhvff-maturin
source root is maturin
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file maturin/pyproject.toml
patching sources
configuring
no configure script, doing nothing
building
Executing pipBuildPhase
Creating a wheel...
WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /build/maturin
    Preparing wheel metadata ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/nix/store/8cxkx34jv9jbwxzb5aix53f1bjrpy6aj-python3.8-pip-20.1.1/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/nix/store/8cxkx34jv9jbwxzb5aix53f1bjrpy6aj-python3.8-pip-20.1.1/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/nix/store/8cxkx34jv9jbwxzb5aix53f1bjrpy6aj-python3.8-pip-20.1.1/lib/python3.8/site-packages/pip/_internal/commands/wheel.py", line 159, in run
    requirement_set = resolver.resolve(
  File "/nix/store/8cxkx34jv9jbwxzb5aix53f1bjrpy6aj-python3.8-pip-20.1.1/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 179, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/nix/store/8cxkx34jv9jbwxzb5aix53f1bjrpy6aj-python3.8-pip-20.1.1/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/nix/store/8cxkx34jv9jbwxzb5aix53f1bjrpy6aj-python3.8-pip-20.1.1/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 314, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/nix/store/8cxkx34jv9jbwxzb5aix53f1bjrpy6aj-python3.8-pip-20.1.1/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 487, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/nix/store/8cxkx34jv9jbwxzb5aix53f1bjrpy6aj-python3.8-pip-20.1.1/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/nix/store/8cxkx34jv9jbwxzb5aix53f1bjrpy6aj-python3.8-pip-20.1.1/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/nix/store/8cxkx34jv9jbwxzb5aix53f1bjrpy6aj-python3.8-pip-20.1.1/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 550, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/nix/store/8cxkx34jv9jbwxzb5aix53f1bjrpy6aj-python3.8-pip-20.1.1/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 535, in _generate_metadata
    return generate_metadata(
  File "/nix/store/8cxkx34jv9jbwxzb5aix53f1bjrpy6aj-python3.8-pip-20.1.1/lib/python3.8/site-packages/pip/_internal/operations/build/metadata.py", line 36, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(
  File "/nix/store/8cxkx34jv9jbwxzb5aix53f1bjrpy6aj-python3.8-pip-20.1.1/lib/python3.8/site-packages/pip/_vendor/pep517/wrappers.py", line 176, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/nix/store/8cxkx34jv9jbwxzb5aix53f1bjrpy6aj-python3.8-pip-20.1.1/lib/python3.8/site-packages/pip/_vendor/pep517/wrappers.py", line 265, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/nix/store/8cxkx34jv9jbwxzb5aix53f1bjrpy6aj-python3.8-pip-20.1.1/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 86, in _build_backend
    obj = import_module(mod_path)
  File "/nix/store/jli50q24fvik6pfsnjs1jd90g3dy4p6y-python3-3.8.3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'maturin'


builder for '/nix/store/4q9c2gja115rjyricl05x47v8c8gg6d8-python3.8-something-0.0.1.drv' failed with exit code 2
error: build of '/nix/store/4q9c2gja115rjyricl05x47v8c8gg6d8-python3.8-something-0.0.1.drv' failed
```

**Comment by martinetd** [comment] 2020-10-26 12:22
Hi @bbigras.
Have you tried again since then?

I'm working on anki update (#78449), and since there is a Cargo.toml/Cargo.lock I found it easier to package that with `buildRustPackage` which does all the heavy lifting on the rust side.
The final product is a `*-cp38-cp38-manylinux1_x86_64.whl` file (that's a wheel?) so definitely a python thing, not sure what I'm missing out by not using `buildPythonPackage` on that front... It's for a pythonApplication which aren't gated by python subversion so I don't really care about the parallel availability within each python namespace but there might be other problems?

Here's what it (currently) looks like: https://github.com/martinetd/nixpkgs/blob/anki/pkgs/games/anki/rspy/default.nix

Now I'm finally done with that, I just noticed I actually need orjson next, so if I publish my work on anki so our interests might coincide a bit.
I'm not sure how clean that is but for now I'll just try doing something similar for it and adding it to pkgs/top-level/python-packages.nix as a rustPackage.. Let's see how that fares and how I can reuse that.

Comments/yells/whatever welcome -- I'll probably open a PR just for orjson to test the water :P

**Comment by martinetd** [comment] 2020-10-26 12:59
gah, orjson requires rust nightly! I don't think we can package anything using nightly? And the common workarounds I found don't work... ugh.. I guess it's about time I gave up on an up to date version of anki as well -_-

Sorry for the noise, keep going, nothing to see here!

**Comment by FRidh** [comment] 2020-10-26 15:01
See https://github.com/NixOS/nixpkgs/pull/101771.

**Comment by bbigras** [comment] 2020-10-28 23:43
> Have you tried again since then?

I still have the same message with the same default.nix and pyproject.toml, without any python files. I wonder if that could be the cause.

**Comment by primeos** [comment] 2021-02-08 14:39
I haven't completely analyzed the situation yet but this will likely be required for Nixpkgs soon as `python3Packages.cryptography` just introduced a Rust dependency in version 3.4: https://cryptography.io/en/latest/changelog.html#v3-4 (though it looks like we can temporarily disable it for 3.4.x: #112402, https://github.com/pyca/cryptography/blob/3.4.1/setup.py#L45)

Unfortunately it also looks like it needs to fetch some Rust dependencies which might be pretty tricky in Nixpkgs:
- https://github.com/pyca/cryptography/blob/3.4.1/src/rust/Cargo.lock
- https://github.com/NixOS/nixpkgs/pull/101771/files#r512162488

I'm not yet familiar with PyO3 and maturin but at least PyO3 and PEP 517 seem to be relevant for Cryptography.

**Comment by SuperSandro2000** [comment] 2021-02-08 20:12
There is also #108447

**Comment by FRidh** [comment] 2021-02-08 20:47
Upstream cryptography issue https://github.com/pyca/cryptography/issues/5771. 

`setuptools-rust` is problematic. Not only does it want to use cargo to build rust, which is fine, it also wants to fetch dependencies. Builds should not fetch dependencies.

**Comment by FRidh** [comment] 2021-02-08 21:05
[Opened a topic](https://discuss.python.org/t/setuptools-rust-maturin-fetching-rust-deps-when-building-wheel/7095) on the `packaging` forum to see how other distributors handle this.

**Comment by FRidh** [comment] 2021-02-08 21:19
Example from @danieldk packaging a Python package using maturin https://github.com/danieldk/nix-packages/blob/81b8444e6864c546cd8f41f393d65fe693c27ca0/pkgs/python-modules/alpino-tokenizer/default.nix#L13

**Comment by danieldk** [comment] 2021-02-09 06:01
> `setuptools-rust` is problematic. Not only does it want to use cargo to build rust, which is fine, it also wants to fetch dependencies. Builds should not fetch dependencies.

`tokenizer` switched from `maturin` to `setuptools-rust`. It works the same way as maturin (let `buildRustPackage` do the fetching + set up the rust environment):

https://github.com/NixOS/nixpkgs/blob/50d34017c234ac075298658c77817499aa713d58/pkgs/development/python-modules/tokenizers/default.nix#L52

**Comment by danieldk** [comment] 2021-02-09 08:59
I have made the cargo vendor handling a hook and I can now build the `tokenizers` package with `buildPythonPackage` and without any of the Rust platform stuff. I have to clean it up a bit and integrate the hook in the regular `buildRustPackage` as well and do a PR.

**Comment by FRidh** [comment] 2021-02-09 09:02
Great, thank you @danieldk !

**Comment by danieldk** [comment] 2021-02-09 10:47
Draft PR: #112500

**Comment by FRidh** [comment] 2021-03-13 16:25
Closing this as done.

**Closed by FRidh** 2021-03-13 16:25 UTC
Labels: 0.kind: packaging request, 6.topic: python, 6.topic: rust
