### ISSUE TITLE
fish-completions don't build on unstable

### ISSUE THREAD

**Issue by haslersn** [NixOS/nixpkgs#56492] opened 2019-02-27 22:46 UTC
## Issue description

I use `fish` and currently when I try to `nixos-rebuild` on **unstable**, it fails because it can't build `fish-completions`.

### Steps to reproduce

* `programs.fish.enable = true;`
* ``` bash
  # nix-channel --add https://nixos.org/channels/nixos-unstable nixos 
  # nixos-rebuild build
  ```

I don't know if that's all or if there are more steps needed to reproduce.

## Technical details

Log contains:

```
collision between `/nix/store/c4mr5y71ri1i8ryv91q755ajkyrla96f-procps-3.3.15-fish-completions/uptime.fish' and `/nix/store/ybgxpd7yz9d6513gg3knwvlzfc0zy9a9-coreutils-8.30-fish-completions/uptime.fish'
builder for '/nix/store/wsfi7zysq6wn14d0f2ka1nhk8kcf03ci-system-fish-completions.drv' failed with exit code 25
```

### `nix-shell -p nix-info --run "nix-info -m"`

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.20.5, NixOS, 19.03pre167858.f2a1a4e93be (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(haslersn): `""`
 - channels(root): `"nixos-19.09pre170705.1233c8d9e9b, nixos-stable-18.09.2266.aabc61049c0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by dotlambda** [comment] 2019-02-28 17:26
duplicate of https://github.com/NixOS/nixpkgs/issues/56432 and https://github.com/NixOS/nixpkgs/issues/56482

**Closed by dotlambda** 2019-02-28 17:26 UTC
