### ISSUE TITLE
insync-v3 server doesn't seem to start

### ISSUE THREAD

**Issue by ajmasia** [NixOS/nixpkgs#152161] opened 2021-12-26 00:41 UTC
### Describe the bug
I've installed insync-v3 and when run `insync start && insync show`, I get this message `Insync doesn't seem to be running. Start it first`

### Steps To Reproduce
1. `insync start`
2. `insync show`

My sytem config:

```bash
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(ajmasia): `"nixpkgs-unstable-22.05pre339357.3e4c1337b93"`
 - channels(root): `"nixos-21.11.334247.573095944e7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```
### Notify maintainers
@siraben @benley

**Comment by sweber83** [comment] 2022-01-03 11:37
I can reproduce this on unstable.
My machine runs unstable @ 395879c28386e1abf20c7ecacd45880759548391
After running `insync start` the journal contains this entry:
```
kernel: .insync-wrapped[684952]: segfault at 1e8 ip 00007f6e10c1eed8 sp 00007ffc3d84fad0 error 4 in libpython3.7m.so.1.0[7f6e10ba3000+1b9000]
```

**Comment by MetalArend** [comment] 2022-01-13 03:02
@benley I saw you added this package back in the day. Maybe you have some insights?

I got the same error as @sweber83, anything I could do to help figure this out?

**Comment by bachp** [comment] 2022-01-16 09:25
Duplicate of https://github.com/NixOS/nixpkgs/issues/139728?

**Comment by hellwolf** [comment] 2022-12-26 02:15
agreed. duplicate of #139728. Can someone close this?

**Comment by benley** [comment] 2022-12-26 02:21
Sorry I haven't been responding here - I have not used insync for quite some time, largely because I wasn't able to get it working after a while.

**Closed by benley** 2022-12-26 02:21 UTC
Labels: 0.kind: bug

**Comment by hellwolf** [comment] 2022-12-26 02:27
@benley no worries, happy to help as a maintainer. I just manage to make it work again for the latest insync binary.
