### ISSUE TITLE
buildFHSUserEnv includes 32bit libraries when building on 64bit

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#15533] opened 2016-05-18 11:22 UTC
## Issue description

For some (to me unknown reason) libstdc++.so is 32bit while other libs are of type 64bit (as they should be). below expression was working ~3 months ago, while rebuilding it last weekend is saw this problem. I'm suspecting that this is a problem with multiple outputs that was merged meanwhile. there i'm pining @vcunat.

### Steps to reproduce

my custom VidyoDesktop expression that suffers from this can be found [here](https://github.com/garbas/dotfiles/blob/master/pkgs/VidyoDesktop/default.nix).

following commands should reproduce an error:

```
% git clone https://github.com/garbas/dotfiles
% nix-build -A VidyoDesktop -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/29644950d4786eb2bc9b28719b6ce0e652077675.tar.gz
% ./result/bin/VidyoDesktop
/opt/vidyo/VidyoDesktop/VidyoDesktop: error while loading shared libraries: libstdc++.so.6: wrong ELF class: ELFCLASS32
% file -L /nix/store/...-VidyoDesktop-fhs/lib/libstdc++.so.6
/nix/store/...-VidyoDesktop-fhs/lib/libstdc++.so.6: ELF 32-bit LSB shared object, Intel 80386, version 1 (GNU/Linux), dynamically linked, stripped
% file -L /nix/store/cbhv6mrmvk9b9g6nz7m9kfn47zfalc7q-VidyoDesktop-fhs/lib/libz.so.1
/nix/store/cbhv6mrmvk9b9g6nz7m9kfn47zfalc7q-VidyoDesktop-fhs/lib/libz.so.1: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped
```

## Technical details

* System: NixOS
* Nix version: ix (Nix) 1.12pre4523_3b81b26
* Nixpkgs version: 16.09pre83100.25e3c09

**Comment by abbradar** [comment] 2016-05-18 14:26
Duplicate of https://github.com/NixOS/nixpkgs/issues/15033

**Closed by abbradar** 2016-05-18 14:26 UTC
