### ISSUE TITLE
Missing Exec line in org.kde.systemmonitor.desktop

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#41083] opened 2018-05-25 17:08 UTC
## Issue description
`kbuildsycoca5` as user `coretemp` returns:
```
kbuildsycoca5 running...
kf5.kservice.services: The desktop entry file "/run/current-system/sw/share/applications/org.kde.systemmonitor.desktop" has Type= "Application" but no Exec line
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.41, NixOS, 18.03.git.33682d9 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - channels(coretemp): `"nixos-18.03.132192.ce0d9d638de"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment] 2018-05-25 21:20
Duplicate of https://github.com/NixOS/nixpkgs/issues/40916

**Comment by FRidh** [comment] 2018-05-27 17:36
Closing as duplicate.

**Closed by FRidh** 2018-05-27 17:36 UTC
