### ISSUE TITLE
Plasma desktop broken in recent updates on 17.03 stable Channel

### ISSUE THREAD

**Issue by johnramsden** [NixOS/nixpkgs#26109] opened 2017-05-26 01:39 UTC
## Issue description

When I moved from Channel revision 17.03.1160.f2c4af4e3b to 17.03.1203.58e227052d My plasma desktop widget stopped working. Instead of my widgets showing up I just got a white box that when pressed gave the error message:

> Error loading QML file: file:///nix/store/smlpa9dvd0n9qc1dn3vni47f2fs47hai-plasma-desktop-5.8.7/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/main.qml:168:9: Cannot assign to non-existent property "enabled" 

This error message also occurred in the test vm when I attempted to run 'nixos-rebuild build-vm'.

### Steps to reproduce

Install the plasma desktop. Certain widgets stopped working, specifically the icons only task menu and task manager are broken on my desktop.

## Technical details

* System: (NixOS: 17.03.1203.58e227052d (Gorilla))
* Nix version: (nix-env (Nix) 1.11.8)
* Nixpkgs version: ("17.03.1203.58e227052d")
* Sandboxing enabled: (true)

**Comment by FRidh** [comment] 2017-05-26 06:44
duplicate of #26080

**Closed by FRidh** 2017-05-26 06:44 UTC
