### ISSUE TITLE
Package darling

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#38628] opened 2018-04-09 01:50 UTC
## Issue description
Darling is a compatibility layer for running macOS apps on Linux (think Wine for macOS). I think it would be interesting to work on with macOS support. They have reverse engineered some headers that Apple doesn't release publicly so having them in "libdarling" could be useful.

https://www.darlinghq.org/

**Comment by davidak** [comment] 2018-04-10 03:14
We already have this part: https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/filesystems/darling-dmg/default.nix

**Comment by clacke** [comment] 2018-07-15 18:37
Just heard of Darling. I would be delighted if it could be used for running `x86_64-darwin` builds on NixOS!

**Comment by davidak** [comment] 2019-08-01 12:47
It seem to be packaged by @matthewbauer, but only for macOS. If i understand the project correctly, that makes no sense. We want it on linux, to run macOS apps.

Also, the package has no version. That's probably because they havn't tagged a version yet. So this is pre-alpha state software.

https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/darwin/darling/default.nix

https://github.com/darlinghq/darling/issues/537

@matthewbauer could you update the package to the commit the "stable" AUR package uses and add a version as described here: https://github.com/NixOS/nixpkgs/blob/1ef7e40a9ce09c35103b4846a78b5dbb190e59c4/doc/coding-conventions.xml#L275 ?

https://aur.archlinux.org/packages/darling/

Then we can close this issue.

**Comment by MetaDark** [comment] 2019-09-12 01:48
It looks like the project has started using tagged versions: https://github.com/darlinghq/darling/releases/tag/v0.2019.8

**Comment by lambdadog** [comment] 2020-06-11 06:06
I'd still be very interested in seeing this added, especially with the hope of future cross-compilation support

**Comment by ShamrockLee** [comment] 2020-09-05 20:28
This would even make it possible to package Mac-binaries for Linux!

**Comment by andrewrk** [comment] 2020-10-27 22:36
I'm interested in this so that I can test cross compiled binaries when running [zig](https://ziglang.org/) tests.

**Comment by andrewrk** [comment] 2021-05-12 18:06
Not stale!!

**Comment by ShamrockLee** [comment] 2021-05-24 15:57
> We already have this part: https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/filesystems/darling-dmg/default.nix

darling-dmg is just part of [darling](https://github.com/darlinghq/darling). To be exact, it is included as a submodule in the source tree of darling.

The darling build will come with kernel modules. It would require knowledge about packaging such kind of things in Nixpkgs.

Build instructions in the Darling Docs:

https://docs.darlinghq.org/build-instructions.html

**Comment by lambdadog** [comment] 2022-05-06 09:26
I'd still like to see this, though largely for much the same reason Andrew mentions at this point -- I've started working with zig and being able to test cross-compiled macos binaries would be brilliant.

**Comment by FedX-sudo** [comment] 2022-07-31 21:11
I have got most of a Darling build file running, but I have found an interesting issue. Wever I build I get the following error: 
```
       > CMake Error at src/CoreAudio/CoreAudio/CMakeLists.txt:20 (add_framework):
       >   Unknown CMake command "add_framework".
       >
       >
```
From this cmake file: 
```
add_framework(CoreAudio
	FAT
    CURRENT_VERSION
    VERSION "A"

    SOURCES
        ${coreaudio_sources}

    DEPENDENCIES
        system
        cxx
        CoreFoundation
        pulse
)
```
As far as I can tell, the `add_framework` command is a special MacOS thing, and I unfortunately do not understand CMake well enough to fix it...

**Comment by FedX-sudo** [comment] 2022-07-31 23:22
Well, turns out the issue is that Darling relies on git-submodules, and it looks like this must be built against the Git repo directly, not against the released tarball...

**Comment by danwdart** [comment] 2022-10-27 14:38
What would therefore be a derivation?

**Comment by Atemu** [comment] 2022-10-28 02:31
What do you mean @danwdart? It's just a `fetchFromGitHub` with `fetchSubmodules = true;`.

**Comment by xieby1** [comment] 2022-10-28 03:35
I tried to re-package the prebuilt deb from darling GitHub releases.
Here is the nix code

default.nix
```nix
let
  pkgs = import <nixpkgs> {};
in {darling = pkgs.callPackage ./darling.nix {};}
```
darling.nix
```nix
{lib, stdenv, fetchurl, dpkg, fakeroot}:
let
  version = "11.5_alpharelease1";
  rpath = ":${stdenv.cc.cc.lib}/lib64";
  src = fetchurl {
    url = "https://github.com/darlinghq/darling/releases/download/v0.1.20220929_update_sources_11_5/darling_0.1.20220929.focal_amd64.deb";
    sha256 = "1jjk2rpqzy1qh5w44vxjsacws04sdaclmk923d1n1wymkgadkcl2";
  };
in
stdenv.mkDerivation {
  pname = "darling";
  inherit version;
  inherit src;
  buildInputs = [ dpkg fakeroot ];
  dontUnpack = true;
  installPhase = ''
    mkdir -p $out
    fakeroot dpkg-deb -x $src $out
    mv $out/usr/* $out/
    rm -r $out/usr
  '';
  postFixup = ''
    for file in $(find $out -type f \( -perm /0111 -o -name \*.so\* \) ); do
      patchelf --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" "$file" || true
      patchelf --set-rpath ${rpath}:$out/lib/x86_64-linux-gnu $file || true
    done
  '';
}
```
Save these  2 snippets as default.nix and darling.nix, then run `nix-build`.

With 2 problems:
1. darling needs setuid/setgid perms, while nix-build would fail if dpkg-deb -x executed directly.
  I use fakeroot to ignore this problem.
2. darlingserver always fails. I am not a darling expert, have no idea.

**Comment by danwdart** [comment] 2022-10-28 08:51
Ah, fantastic, thanks! Looking forward to having this in nixpkgs anyway, but let's see how we go there.

**Comment by ShamrockLee** [comment] 2022-10-28 10:19
> I tried to re-package the prebuilt deb from darling GitHub releases.

It could be named `darling-bin` when entering Nixpkgs.

**Comment by xieby1** [comment] 2022-10-28 12:36
> It could be named `darling-bin` when entering Nixpkgs.

Good suggestion.
I've edited those two scripts.

**Comment by danwdart** [comment] 2022-11-10 11:09
I got as far as finding out that darlingserver doesn't start with that script because it expects /usr/bin, so updating my shell.nix to a `buildFHSUserEnv` version, the next issue was that darlingserver was trying to mount overlayfs on "lowerdir=/usr/libexec/darling,up" (may be incomplete, this is strace output) which did not exist.

**Comment by zhaofengli** [comment] 2023-04-23 10:08
After a bit of tinkering I got Darling to build from source. I opened #227765 with more info. Please give it a try!

**Comment by ShamrockLee** [comment] 2023-04-23 14:55
> The darling build will come with kernel modules. It would need someone with kernel-packaging experience to pack it into Nixpkgs.

It seems that they now use `darling_server` instead of the kernel module. This would make packaging easier.

**Comment by ShamrockLee** [comment] 2023-04-23 15:56
> It seem to be packaged by @matthewbauer, but only for macOS. If i understand the project correctly, that makes no sense. We want it on linux, to run macOS apps.

@matthewbauer What's the purpose of `darwing.darling`? If it is only the sandbox part of Darling, a new name like `darling-sandbox` would bring less confusion.

**Closed** 2023-05-07 19:29 UTC
Labels: 9.needs: package (new)
