### ISSUE TITLE
Package request: firewalld pkg support inside networking option (only iptables and nftables are supported) or please create services.firewalld with options

### ISSUE THREAD

**Issue by KCynk** [NixOS/nixpkgs#249609] opened 2023-08-16 20:14 UTC
**Metadata**

* homepage URL: https://mynixos.com/nixpkgs/option/networking.firewall.package

```
networking.firewall = {
   enable = true
   package = pkgs.firewalld;
};
```

```
[xol@f32219db85cad7598ad495297a3e1b08:~]  sudo nixos-rebuild switch
building Nix...
building the system configuration...
these 14 derivations will be built:
  /nix/store/35hnzjwwdbjxyxs14qq5bhxw6yy5pj66-system-path.drv
  /nix/store/s1j18nvb2gwpj1h8da4kak74l0ng0nv5-dbus-1.drv
  /nix/store/wmr6s1hbna2wwsyxxzzn3wkglxylj9ja-X-Restart-Triggers.drv
  /nix/store/73gwp7w8a5j476gjhszmvhacpx7jsdwf-unit-dbus.service.drv
  /nix/store/qndv8rh9g5928lhpg0f1d9h4c4xxpjz9-X-Restart-Triggers.drv
  /nix/store/c679lvk2wsxklvxg0gagx66qif23am1z-unit-polkit.service.drv
  /nix/store/y76xz0lzkhyabn7xgzxzfr6s1incvd7g-unit-accounts-daemon.service.drv
  /nix/store/qx4hl7mskp3b14yfk8ckzwf2h44xqz1w-system-units.drv
  /nix/store/5v69sfxs0c6z0ndqgbzyngjjl6cibvly-system-crontab.drv
  /nix/store/s134l18218knz6zf0dv9qri5ksjlwzmw-crontabs.drv
  /nix/store/9lwbbzcdwapv3ww2qwshpgjhknmrnd6h-unit-dbus.service.drv
  /nix/store/ygf8gq6bw0j0k85aijm8kzb9k1mzjysk-user-units.drv
  /nix/store/55lnr4kw4r8xqgwqa1977r8syrcc5389-etc.drv
  /nix/store/x4fk72agkl6jn5im4pkk52aaqxdvil9z-nixos-system-f32219db85cad7598ad495297a3e1b08-23.11pre514857.caac0eb6bdca.drv
building '/nix/store/35hnzjwwdbjxyxs14qq5bhxw6yy5pj66-system-path.drv'...
created 16308 symlinks in user environment
gtk-update-icon-cache: Cache file created successfully.
building '/nix/store/qndv8rh9g5928lhpg0f1d9h4c4xxpjz9-X-Restart-Triggers.drv'...
building '/nix/store/s1j18nvb2gwpj1h8da4kak74l0ng0nv5-dbus-1.drv'...
building '/nix/store/5v69sfxs0c6z0ndqgbzyngjjl6cibvly-system-crontab.drv'...
building '/nix/store/y76xz0lzkhyabn7xgzxzfr6s1incvd7g-unit-accounts-daemon.service.drv'...
building '/nix/store/wmr6s1hbna2wwsyxxzzn3wkglxylj9ja-X-Restart-Triggers.drv'...
building '/nix/store/s134l18218knz6zf0dv9qri5ksjlwzmw-crontabs.drv'...
building '/nix/store/c679lvk2wsxklvxg0gagx66qif23am1z-unit-polkit.service.drv'...
building '/nix/store/73gwp7w8a5j476gjhszmvhacpx7jsdwf-unit-dbus.service.drv'...
building '/nix/store/9lwbbzcdwapv3ww2qwshpgjhknmrnd6h-unit-dbus.service.drv'...
building '/nix/store/qx4hl7mskp3b14yfk8ckzwf2h44xqz1w-system-units.drv'...
building '/nix/store/ygf8gq6bw0j0k85aijm8kzb9k1mzjysk-user-units.drv'...
building '/nix/store/55lnr4kw4r8xqgwqa1977r8syrcc5389-etc.drv'...
building '/nix/store/x4fk72agkl6jn5im4pkk52aaqxdvil9z-nixos-system-f32219db85cad7598ad495297a3e1b08-23.11pre514857.caac0eb6bdca.drv'...
stopping the following units: accounts-daemon.service
activating the configuration...
setting up /etc...
reloading user units for xol...
setting up tmpfiles
reloading the following units: dbus.service
restarting the following units: polkit.service
starting the following units: accounts-daemon.service
the following new units were started: libvirtd.service
warning: the following units failed: firewall.service

× firewall.service - Firewall
     Loaded: loaded (/etc/systemd/system/firewall.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Wed 2023-08-16 22:08:49 CEST; 1s ago
   Duration: 12h 38min 5.379s
    Process: 69212 ExecStart=firewall-start (code=exited, status=127)
   Main PID: 69212 (code=exited, status=127)
         IP: 0B in, 0B out
        CPU: 13ms

sie 16 22:08:49 f32219db85cad7598ad495297a3e1b08 systemd[1]: Starting Firewall...
sie 16 22:08:49 f32219db85cad7598ad495297a3e1b08 firewall-start[69235]: /nix/store/j4jg0fn7zdnadkinjki5zc6ly2apy49g-firewall-start/bin/firewall-start: line 4: iptables: command not found
sie 16 22:08:49 f32219db85cad7598ad495297a3e1b08 systemd[1]: firewall.service: Main process exited, code=exited, status=127/n/a
sie 16 22:08:49 f32219db85cad7598ad495297a3e1b08 systemd[1]: firewall.service: Failed with result 'exit-code'.
sie 16 22:08:49 f32219db85cad7598ad495297a3e1b08 systemd[1]: Failed to start Firewall.
warning: error(s) occurred while switching to the new configuration
[xol@f32219db85cad7598ad495297a3e1b08:~] sudo systemctl status firewalld
Unit firewalld.service could not be found.
```

**Comment by KCynk** [comment] 2023-08-16 20:23
Also there is a bug with firewalld
```
  # Exclude packages
  environment.gnome.excludePackages = with pkgs; [
    gnome-tour 
    iptables-legacy
    nftables
  ];

  # Packages to install
  environment.systemPackages = with pkgs; [
    # Gnome
    gnome.nautilus
    gnome.gnome-tweaks
    tilix
    gnome.gnome-calculator
    gnome.gnome-maps
    gnome.eog
    gnome.evince
    gnome.gnome-disk-utility
    gnomeExtensions.hide-activities-button
    gnomeExtensions.no-overview
    gnomeExtensions.ip-finder
    gnomeExtensions.light-shell
    gnomeExtensions.appindicator 
    # Network tools
    wget
    curl
    nmap
    dig
    traceroute
    mtr
    netcat
    gns3-gui
    gns3-server
    # Privacy
    protonvpn-gui
    keepassxc
    # Backup setup guide: https://inv.pistasjis.net/watch?v=asZX2YbTaNE
    vorta
    # Office
    yt-dlp
    vim
    hunspell
    hunspellDicts.pl_PL
    obsidian
    calibre
    freeoffice
    vscodium
    vlc
    krita
    inkscape
    # System
    pstree
    logrotate
    rsyslog
    strace
    sysstat
    lsof
    tree
    virt-manager
    virt-viewer
    ntfs3g
    qemu
    libvirt
    xdg-desktop-portal
    # Programing
    git
    # Automation tools
    ansible
    # Security
    firewalld <-----------------------------
    aide
    chkrootkit
    lynis
    usbguard-notifier
  ];

 2. `sudo nixos-rebuild switch`
 3. 
 ``
[xol@f32219db85cad7598ad495297a3e1b08:~] sudo systemctl status firewalld
Unit firewalld.service could not be found.
```

**Comment by eclairevoyant** [comment] 2024-07-11 06:33
duplicate of #165882

**Closed by eclairevoyant** 2024-07-11 06:33 UTC
Labels: 0.kind: packaging request
