### ISSUE TITLE
Tensorflow v2 fails to build

### ISSUE THREAD

**Issue by mtn** [NixOS/nixpkgs#90025] opened 2020-06-10 07:06 UTC
**Describe the bug**
The derivation for tensorflow v2 fails to build on NixOS with a pip-related error

**To Reproduce**
1. Run the following [`shell.nix`](https://gist.github.com/mtn/5779479e946d3c25bdab348c609eba22)

**Expected behavior**
Tensorflow v2 builds cleanly

**Additional context**
The error:

```
these derivations will be built:
  /nix/store/4n8gn1mfcqs4c40pd3r8r4gvydd35ahx-python3.7-tensorflow-2.1.0.drv
building '/nix/store/4n8gn1mfcqs4c40pd3r8r4gvydd35ahx-python3.7-tensorflow-2.1.0.drv'...
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing wheel setup hook
Using wheelUnpackPhase
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
unpacking sources
Executing wheelUnpackPhase
Finished executing wheelUnpackPhase
patching sources
configuring
/build/dist /build
Unpacking to: unpacked/tensorflow_cpu-2.1.0...OK
Repacking wheel as ./tensorflow_cpu-2.1.0-cp37-cp37m-manylinux2010_x86_64.whl...OK
/build
no configure script, doing nothing
building
no Makefile, doing nothing
installing
Executing pipInstallPhase
/build/dist /build
Processing ./tensorflow_cpu-2.1.0-cp37-cp37m-manylinux2010_x86_64.whl
Requirement already satisfied: absl-py>=0.7.0 in /nix/store/8rdg5inblimnhqwx5ckj8mdmib6q2yvl-python3.7-absl-py-0.9.0/lib/python3.7/site-packages (from tensorflow-cpu==2.1.0) (0.9.0)
Requirement already satisfied: grpcio>=1.8.6 in /nix/store/wn47kbp8ni6xxaaqmzhyfms1vqhcvxbn-python3.7-grpcio-1.27.1/lib/python3.7/site-packages (from tensorflow-cpu==2.1.0) (1.27.1)
Requirement already satisfied: scipy==1.4.1; python_version >= "3" in /nix/store/hn9g90i0hc5xzp5fp74844q3jpf1zz88-python3.7-scipy-1.4.1/lib/python3.7/site-packages (from tensorflow-cpu==2.1.0) (1.4.1)
Requirement already satisfied: gast==0.3.2 in /nix/store/n9xqqbrr4arlgpi15gjjgbhl3zpasgl8-python3.7-gast-0.3.2/lib/python3.7/site-packages (from tensorflow-cpu==2.1.0) (0.3.2)
ERROR: Could not find a version that satisfies the requirement protobuf>=3.8.0 (from tensorflow-cpu==2.1.0) (from versions: none)
ERROR: No matching distribution found for protobuf>=3.8.0 (from tensorflow-cpu==2.1.0)
builder for '/nix/store/4n8gn1mfcqs4c40pd3r8r4gvydd35ahx-python3.7-tensorflow-2.1.0.drv' failed with exit code 1
error: build of '/nix/store/4n8gn1mfcqs4c40pd3r8r4gvydd35ahx-python3.7-tensorflow-2.1.0.drv' failed
```

**Notify maintainers**
@jyp @abbradar 

Sorry if this isn't a bug -- fairly new to using NixOS

**Comment by jmillerpdt** [comment] 2020-07-14 22:56
> Yes (sorry you caught my ninja edit). I'm getting a gast version mismatch with tensorflow-bin_2 on latest nixpkgs (so separate issue).

Is it related to https://github.com/NixOS/nixpkgs/pull/89496?

**Comment by jonringer** [comment] 2020-07-31 06:53
no, I believe that's related to the older PR

**Comment by sheepforce** [comment] 2020-08-27 14:39
The problem in the nixos-20.03 channel is indeed the protobuf version as indicated in your build log and also [here](https://github.com/NixOS/nixpkgs/blob/feff2fa6659799fe7439038b3eba453d62a16e69/pkgs/development/python-modules/tensorflow/2/default.nix#L342). Giving tensorflow a correct protobuf version fixes this at least for the nixos-20.03 branch. I am using an overlay for my project.
```nix
  self: super: {
    # Changes to Python 3.7 packages.
    python37 = super.python37.override {
      packageOverrides = python-self: python-super: {
        # Fixes for binary installation of tensorflow (wrong protobuf versions used).
        tensorflow-bin_2 =
          let
            protobuf = python-self.protobuf.override { protobuf = self.protobuf3_9; };
            grpcio = python-self.grpcio.override { inherit protobuf; };
            tensorflow-tensorboard = python-super.tensorflow-tensorboard_2.override {
              inherit protobuf grpcio;
            };
          in
            python-super.tensorflow-bin_2.override { inherit protobuf grpcio tensorflow-tensorboard; };

        # Fixes for installation from source of tensorflow.
        tensorflow-build_2 =
          let
            protobuf = python-self.protobuf.override { protobuf = self.protobuf3_9; };
            grpcio = python-self.grpcio.override { inherit protobuf; };
            tensorflow-tensorboard_2 = python-super.tensorflow-tensorboard_2.override {
              inherit protobuf grpcio;
            };
            /*
            The whole package set is passed to tensorflow, so again in the entire package set we
            need to override the protobuf version again. At least here we can apply the
            sledgehammer and override protobuf globally.
            */
            pkgs = self // { protobuf = self.protobuf3_9; };
          in
            python-super.tensorflow-build_2.override {
              inherit protobuf grpcio tensorflow-tensorboard_2 pkgs;
            };
      };
    };
  };
```

**Comment by mkg20001** [comment] 2020-09-21 12:56
As I understand, the change is overriding the protobuf version in the grpcio and tensorflow packages to be protobuf3.9?

This patch should fix it, didn't verify it tho


```patch
diff --git a/pkgs/development/python-modules/tensorflow-tensorboard/2/default.nix b/pkgs/development/python-modules/tensorflow-tensorboard/2/default.nix
index 945896dda01..63ef3109c39 100644
--- a/pkgs/development/python-modules/tensorflow-tensorboard/2/default.nix
+++ b/pkgs/development/python-modules/tensorflow-tensorboard/2/default.nix
@@ -8,6 +8,7 @@
 , futures
 , absl-py
 , google-auth-oauthlib
+, protobuf3_9
 }:
 
 # tensorflow/tensorboard is built from a downloaded wheel, because
@@ -34,9 +35,9 @@ buildPythonPackage rec {
   propagatedBuildInputs = [
     numpy
     werkzeug
-    protobuf
+    (protobuf.override({ protobuf = protobuf3_9; }))
     markdown
-    grpcio
+    (grpcio.override({ protobuf = protobuf3_9; }))
     absl-py
     google-auth-oauthlib
     # not declared in install_requires, but used at runtime
diff --git a/pkgs/development/python-modules/tensorflow/2/bin.nix b/pkgs/development/python-modules/tensorflow/2/bin.nix
index acb5f473ec9..4b9d6ec6c46 100644
--- a/pkgs/development/python-modules/tensorflow/2/bin.nix
+++ b/pkgs/development/python-modules/tensorflow/2/bin.nix
@@ -64,11 +64,11 @@ in buildPythonPackage {
   in fetchurl packages.${key};
 
   propagatedBuildInputs = [
-    protobuf
+    (protobuf.override({ protobuf = protobuf3_9; }))
     numpy
     scipy
     termcolor
-    grpcio
+    (grpcio.override({ protobuf = protobuf3_9; }))
     six
     astor
     absl-py
diff --git a/pkgs/development/python-modules/tensorflow/2/default.nix b/pkgs/development/python-modules/tensorflow/2/default.nix
index eedd6e6d0df..f8b825aa545 100644
--- a/pkgs/development/python-modules/tensorflow/2/default.nix
+++ b/pkgs/development/python-modules/tensorflow/2/default.nix
@@ -6,6 +6,7 @@
 , numpy, tensorflow-tensorboard_2, backports_weakref, mock, enum34, absl-py
 , future, setuptools, wheel, keras-preprocessing, keras-applications, google-pasta
 , functools32
+, protobuf3_9
 , opt-einsum
 , termcolor, grpcio, six, wrapt, protobuf, tensorflow-estimator_2
 # Common deps
@@ -371,11 +372,11 @@ in buildPythonPackage {
     keras-preprocessing
     numpy
     six
-    protobuf
+    (protobuf.override({ protobuf = protobuf3_9; }))
     tensorflow-estimator_2
     termcolor
     wrapt
-    grpcio
+    (grpcio.override({ protobuf = protobuf3_9; }))
     opt-einsum
   ] ++ lib.optionals (!isPy3k) [
     mock
```

**Comment by sheepforce** [comment] 2020-09-21 13:13
@mkg20001: correct, i am simply overriding protobuf to version 3.9 in the relevant places (protobuf python package, grpcio, tensorflow-tensorboard_2 and tensorflow-tensorboard). I think your patch misses the lines in `pkgs/development/python-modules/tensorflow/2/default.nix`, where protobuf is again taken from the `pkgs` attribute: [here](https://github.com/NixOS/nixpkgs/blob/773ef5ae78339db744b917c2b35d28812028bd8c/pkgs/development/python-modules/tensorflow/2/default.nix#L68) and [here](https://github.com/NixOS/nixpkgs/blob/773ef5ae78339db744b917c2b35d28812028bd8c/pkgs/development/python-modules/tensorflow/2/default.nix#L154). I have no idea why it is done like this, but i *suspect* this would cause trouble, as this would be mixing protobuf 3.7 and 3.9. This is why i am also applying the sledge-hammer method and say `pkgs = self // { protobuf = self.protobuf3_9; };` before passing this to tensorflow. 

Otherwise i would guess that this fixes the issues :) (although i also did not test due to the very long tensorflow build time).

**Comment by jonringer** [comment] 2020-09-22 16:00
Pinning within python-modules is highly discouraged. This will potentially introduce incompatible versions in a user's environment as either the new pinned version or the original version will be imported at runtime, breaking one of the packages.

The preference to handling this is to relax version bounds in the "install_requires" field. (could be in setup.py, pyproject.toml, requirements or others). In most cases, packages are still compatible with small API changes which may warrant a major version bump. We use test suites to verify that the package still works correctly. 

If the package is still incompatible with the latest major version, then the most proper way to handle this is make an issue with the upstream package to adopt the latest major version. Or if upstream is not very responsive, you are free patch the source to make it compatible.

In very few circumstances, two versions of the same package are allowed to exist if the packages are extremely difficult to package. Some examples of this are tensorflow, which has huge ecosystems built around it and is hard to package. Another is django, which has 2 actively developed versions, and large ecosystems built around each.

One exception to this is applications, due to the way `buildPythonApplication` and `toPythonApplication` functions work, the related derivations will not bleed dependencies between packages. If the package doesn't need to be imported by other python modules, then this package would be a good candidate to convert into application. You can look at https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/admin/awscli/default.nix as an example of using an overlay within a python application. 

Info on `buildPythonApplication` can be found [here](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#buildpythonapplication-function).
Info on `toPythonApplication` can be found [here](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#topythonapplication-function).

**Comment by mkg20001** [comment] 2020-09-22 16:24
The problem is that a C++ compilation error occurs, which might require a patch or possibly a bigger undertaking

Another thing to consider is to see if upstream has released an update, since they probably will also be upgrading

**Comment by jonringer** [comment] 2020-09-22 16:34
That is a big issue.

What you're recommending would fix the build, but could subtlety break other packages at runtime.

Python packaging is a mess.

**Comment by alexvorobiev** [comment] 2021-03-22 17:52
This is still important to me.

**Comment by risicle** [comment] 2021-08-07 18:48
Fixed in stable and unstable now.

**Closed by risicle** 2021-08-07 18:48 UTC
Labels: 0.kind: bug, 6.topic: python
