### ISSUE TITLE
screen killed on logout

### ISSUE THREAD

**Issue by jerith666** [NixOS/nixpkgs#35608] opened 2018-02-26 03:48 UTC
### Steps to reproduce

Connect via ssh, start a screen session, detach it.  Exit ssh session.  In systemd journal:

```
Feb 25 21:40:46 alpha systemd[1]: session-2.scope: Killing process 2796 (screen) with signal SIGTERM.
```

Reconnect via ssh and `screen -RD` starts a new session, the old one is indeed gone.

This began happening when updating from 9b25b9347d9 to 1bf7dfaabea (on `nixos-unstable`).

Among other things that contains an update to systemd (from 234 to 237, eb862c48ddc288243c5447e8decc623b10ef165c).  Nothing in the release notes for those couple of versions looks immediately suspicious to me, but I'm far from a systemd expert.

I've only gotten through one step of bisecting so far, but I'll keep this updated as I go.

```
git bisect good 66b2d84b83a79781c1999849ce9c0f12342ec6ea
git bisect bad 53d274c1818bc6af30bb925476d178cfbddc8a12
git bisect bad 2b851d14d9f7fa09120a407fecf3a81cea12bebe
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.81, NixOS, 18.03.git.2b851d1 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-16.03.1299.a8e0739"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

(That 16.03 channel is an artifact of the way I manage my nixpkgs git checkout, the commits mentioned above are correct.)

**Comment by dtzWill** [comment] 2018-02-26 04:04
Offhand, seems likely to be same problem causing #35415.

**Comment by dtzWill** [comment] 2018-02-26 04:16
Possibly related: http://thread.gmane.org/gmane.comp.sysutils.systemd.devel/2379/focus=2391

Also, lingering options on other thread, haven't tried.

**Comment by dtzWill** [comment] 2018-02-26 12:25
Closing as duplicate of #35415 (but thank you for reporting, I wasn't previously sure this wasn't (somehow!) a tmux thing).

**Closed by dtzWill** 2018-02-26 12:25 UTC
