### ISSUE TITLE
`python312Packages.triton` build failure on x86_64-linux as of `6369dcd1`

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#361276] opened 2024-12-03 00:30 UTC
## Issue description
Build of `python312Packages.triton` failed on x86_64-linux as of 6369dcd1327af7e075dd1b3d57eb8d67aecae88f. This is currently breaking `python3Packages.torch-bin`.

```
error: builder for '/nix/store/bcwp7ili67wb103qrkcckcj7fzz1hd0g-python3.12-triton-3.1.0.drv' failed with exit code 1;
       last 10 log lines:
       > checking for references to /build/ in /nix/store/kwahd53lf8hqylcpiyv15l157iayn1gc-python3.12-triton-3.1.0...
       > patching script interpreter paths in /nix/store/kwahd53lf8hqylcpiyv15l157iayn1gc-python3.12-triton-3.1.0
       > shrinking RPATHs of ELF executables and libraries in /nix/store/j069hgna5bdvyks32dsq58c16b2hn61r-python3.12-triton-3.1.0-dist
       > checking for references to /build/ in /nix/store/j069hgna5bdvyks32dsq58c16b2hn61r-python3.12-triton-3.1.0-dist...
       > patching script interpreter paths in /nix/store/j069hgna5bdvyks32dsq58c16b2hn61r-python3.12-triton-3.1.0-dist
       > Rewriting #!/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/bin/python3.12 to #!/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7
       > wrapping `/nix/store/kwahd53lf8hqylcpiyv15l157iayn1gc-python3.12-triton-3.1.0/bin/proton'...
       > Rewriting #!/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/bin/python3.12 to #!/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7
       > wrapping `/nix/store/kwahd53lf8hqylcpiyv15l157iayn1gc-python3.12-triton-3.1.0/bin/proton-viewer'...
       > chmod: cannot access '/nix/store/kwahd53lf8hqylcpiyv15l157iayn1gc-python3.12-triton-3.1.0/lib/python3.12/site-packages/triton/third_party/cuda/bin/ptxas': No such file or directory
       For full logs, run 'nix log /nix/store/bcwp7ili67wb103qrkcckcj7fzz1hd0g-python3.12-triton-3.1.0.drv'.
error (ignored): error: cannot unlink '/tmp/nix-build-nccl-2.21.5-1.drv-0': Directory not empty
error: 1 dependencies of derivation '/nix/store/y2483brzp9fgyvad62qags60gyd7bxll-python3.12-torch-2.5.1.drv' failed to build
```

[full build log](https://github.com/samuela/nixpkgs-upkeep/actions/runs/12130350515)

python3Packages.torch-bin maintainers cc: @junjihashimoto
python312Packages.triton maintainers cc: @SomeoneSerge @Madouura @derdennisop
Other cc: n/a

### Steps to reproduce
1. Checkout nixpkgs at commit 6369dcd1327af7e075dd1b3d57eb8d67aecae88f
2. Run `nix-build -A python312Packages.triton`

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.0-1025-azure, Ubuntu, 22.04.5 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.16.1`
 - nixpkgs: `/nix/store/dsixppyd2486p7s2r675vig1f4kx6hcn-source`
```

Contents of `~/.config/nixpkgs/config.nix`:
```
{ allowUnfree = true; cudaSupport = true; cudaCapabilities = ["8.0"]; }
```

## Misc.
This issue was automatically generated by [nixpkgs-upkeep](https://github.com/samuela/nixpkgs-upkeep).
- [CI workflow](https://github.com/samuela/nixpkgs-upkeep/actions/runs/12130350515) that created this issue.
- Internal tags: -3430797213651399966 -6343138025477721980

**Comment by junjihashimoto** [comment] 2024-12-03 01:34
```
junji-hashimoto@nixos:~/git/nixpkgs]$ uname -a
Linux nixos 6.6.33 #1-NixOS SMP PREEMPT_DYNAMIC Wed Jun 12 09:13:03 UTC 2024 x86_64 GNU/Linux

[junji-hashimoto@nixos:~/git/nixpkgs]$ git rev-parse HEAD
6369dcd1327af7e075dd1b3d57eb8d67aecae88f

[junji-hashimoto@nixos:~/git/nixpkgs]$ nix-build -A python312Packages.triton ./default.nix
/nix/store/bkg5gkkwb8pvhyjknsisdn8pzbizdlb1-python3.12-triton-3.1.0

```
In my environment, it does not fail.

**Comment by dotlambda** [comment] 2024-12-09 23:10
duplicate of https://github.com/NixOS/nixpkgs/issues/352755

**Closed by dotlambda** 2024-12-09 23:10 UTC
Labels: 0.kind: question
