### ISSUE TITLE
llvmPackages_15.libllvm: linking against llvm fails with undefined symbol errors after updating nixpkgs

### ISSUE THREAD

**Issue by alaidriel** [NixOS/nixpkgs#282695] opened 2024-01-21 21:05 UTC
### Describe the bug
After updating nixpkgs from revision `b604023e0a5549b65da3040a07d2beb29ac9fc63` to `e5d1c87f5813afde2dda384ac807c57a105721cc`, linking against `llvmPackages_15.libllvm` in a Cargo project fails with undefined symbol errors related to missing vtables for various C++ symbols, such as `__cxxabiv1::__pointer_type_info`.

(**note**: `e5d1c87f5813afde2dda384ac807c57a105721cc` is the nixpkgs revision as of running `nix flake update` at time of writing)

### Steps To Reproduce
1. Clone the sample repository: `git clone git@github.com:alaidriel/llvm-weirdness.git`
2. Observe that Cargo builds successfully with the old revision: `nix develop -c cargo build --release`
3. Replace the working nixpkgs revision with the broken nixpkgs revision: `cp flake.lock.broken flake.lock`
4. Observe that Cargo fails to build: `nix develop -c cargo build --release`

I can try to make it more minimal if needed.

### Expected behavior
Cargo should build the example successfully using the updated nixpkgs revision.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/68250402/e4740e6f-9052-43c7-9c9a-e09b45ee539f)

### Additional context
Full linker error on my end: <https://sourceb.in/kL35Tn3mQx>

### Notify maintainers
@Ericson2314 @lovek323 @alyssais @RaitoBezarius @rrbutani @sternenseemann

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.2.0, macOS 14.2.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - nixpkgs: `/Users/aly/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by wegank** [comment] 2024-01-21 21:44
Duplicate of #166205, you might want to apply the workaround in the comments.

**Comment by alaidriel** [comment] 2024-01-21 23:10
Thanks — missed that one while I was searching open issues, sorry.

**Closed** 2024-01-24 02:23 UTC
Labels: 0.kind: bug
