### ISSUE TITLE
lib.mkMerge composes in reverse order

### ISSUE THREAD

**Issue by robinp** [NixOS/nixpkgs#56449] opened 2019-02-27 09:06 UTC
This is mostly apparent for `extraConfig` fields which get concatenated. The content is the reverse order of the contents of the individual fragments. Which can be quite surprising, especially in one expects later fragments to override previous options (which is a fragile way, but still, striving to cause least surprise).

**Comment by TomSmeets** [comment] 2020-06-09 10:19
Yes, this is still relevant.
However this issue is not directly caused by `mkMerge`. But by a strange `reverseList` call inside `lib/modules.nix`. See this issue: https://github.com/NixOS/nixpkgs/issues/56519

**Comment by infinisil** [comment] 2023-08-08 02:01
Closing as duplicate of https://github.com/NixOS/nixpkgs/issues/56519

**Closed by infinisil** 2023-08-08 02:01 UTC
Labels: 6.topic: module system
