### ISSUE TITLE
Discord crashes with OpenASAR

### ISSUE THREAD

**Issue by RGBCube** [NixOS/nixpkgs#269956] opened 2023-11-25 18:28 UTC
### Describe the bug

Discord crashes while trying to load OpenASAR.

### Steps To Reproduce

Add this to your packages, master branch:

```nix
(discord.override {
  withOpenASAR = true;
  withVencord  = true;
})
```

### Expected behavior

For it load normally and run.

### Additional context

```js
[Nix] Disabling updates already done
[Vencord] Starting up...
[Vencord] Loading original Discord app.asar
[OpenAsar > Init] OpenAsar unstable-2023-10-24
[OpenAsar > Settings] /home/nixos/.config/discord/settings.json {
  SKIP_HOST_UPDATE: true,
  DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING: true,
  MIN_WIDTH: 0,
  MIN_HEIGHT: 0,
  openasar: { setup: true, quickstart: true },
  IS_MAXIMIZED: false,
  IS_MINIMIZED: false,
  WINDOW_BOUNDS: { x: 12, y: 52, width: 1896, height: 1016 },
  trayBalloonShown: true,
  MINIMIZE_TO_TRAY: false,
  OPEN_ON_STARTUP: false,
  enableHardwareAcceleration: true
}
[OpenAsar > BuildInfo] { releaseChannel: 'stable', version: '0.0.35' }

(discord:7926): Gtk-WARNING **: 21:28:45.369: Theme parsing error: gtk.css:6691:68: Invalid name of pseudo-class

(discord:7926): Gtk-WARNING **: 21:28:45.428: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
[OpenAsar > Modules] Checking
[Vencord] Installed React Developer Tools
(node:7926) ExtensionLoadWarning: Warnings loading extension at /home/nixos/.config/Vencord/ExtensionCache/fmkadmapgofadopljbjfkapdkoienihi:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

(Use `discord --trace-warnings ...` to show where the warning was created)
Error: Cannot find module 'discord_desktop_core'
Require stack:
- /nix/store/pj08a4bp13dlqj99mid08gfffpsvjr8m-discord-0.0.35/opt/Discord/resources/_app.asar/bootstrap.js
- /nix/store/pj08a4bp13dlqj99mid08gfffpsvjr8m-discord-0.0.35/opt/Discord/resources/_app.asar/index.js
- /nix/store/5vp18khg6hm1ch98yi92zj40xsf2sqi5-vencord-1.6.3/patcher.js
- /nix/store/pj08a4bp13dlqj99mid08gfffpsvjr8m-discord-0.0.35/opt/Discord/resources/_app.asar/index.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109751)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at startCore (/nix/store/pj08a4bp13dlqj99mid08gfffpsvjr8m-discord-0.0.35/opt/Discord/resources/_app.asar/bootstrap.js:1:1517)
    at EventEmitter.<anonymous> (/nix/store/pj08a4bp13dlqj99mid08gfffpsvjr8m-discord-0.0.35/opt/Discord/resources/_app.asar/bootstrap.js:1:2630)
    at Object.onceWrapper (node:events:627:28)
    at EventEmitter.emit (node:events:513:28) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/pj08a4bp13dlqj99mid08gfffpsvjr8m-discord-0.0.35/opt/Discord/resources/_app.asar/bootstrap.js',
    '/nix/store/pj08a4bp13dlqj99mid08gfffpsvjr8m-discord-0.0.35/opt/Discord/resources/_app.asar/index.js',
    '/nix/store/5vp18khg6hm1ch98yi92zj40xsf2sqi5-vencord-1.6.3/patcher.js',
    '/nix/store/pj08a4bp13dlqj99mid08gfffpsvjr8m-discord-0.0.35/opt/Discord/resources/_app.asar/index.js',
    undefined
  ]
} uncaughtException
[OpenAsar > Modules] Update: discord_desktop_core 0 -> 1
[OpenAsar > Modules] Update: discord_erlpack 0 -> 1
[OpenAsar > Modules] Update: discord_spellcheck 0 -> 1
[OpenAsar > Modules] Update: discord_utils 0 -> 1
[OpenAsar > Modules] Update: discord_voice 0 -> 1
```

### Notify Maintainers

@MP2E @Scrumplex @Artturin @Infinidoge @jopejoe1 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.2, NixOS, 24.05 (Uakari), 24.05.20231122.19cbff5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/cwn7ng3g4zhpyqf0rn01rikl6xnmwz5f-source`
```

**Comment by Artturin** [comment] 2023-11-25 23:31
Dupe of https://github.com/NixOS/nixpkgs/issues/208749

**Closed by Artturin** 2023-11-25 23:31 UTC
Labels: 0.kind: bug
