### ISSUE TITLE
Package request: mcpelauncher

### ISSUE THREAD

**Issue by I-like-stuff** [NixOS/nixpkgs#253137] opened 2023-09-03 14:07 UTC
**Project description**
unofficial launcher for the Android version of Minecraft: Bedrock Edition on linux and macOS

**Metadata**
* homepage URL: https://github.com/minecraft-linux/mcpelauncher-manifest
* license: GPL-3.0
* platforms: linux, macos

**Comment by Aleksanaa** [comment] 2023-10-16 03:34
Closing as duplicate of https://github.com/NixOS/nixpkgs/issues/231875

**Closed by Aleksanaa** 2023-10-16 03:34 UTC
Labels: 0.kind: packaging request
