### ISSUE TITLE
Build failure: ueberzugpp

### ISSUE THREAD

**Issue by biscotty666** [NixOS/nixpkgs#335393] opened 2024-08-17 15:09 UTC
### Steps To Reproduce

1. using flakes and home-manager, added to home manager's package. I attached a lockfile

### Build log

```
ueberzugpp>
ueberzugpp>
ueberzugpp> -- Configuring incomplete, errors occurred!
error: builder for '/nix/store/cjfdi947ivzx2pv29d0xpql6rql63a5c-ueberzugpp-2.9.6.drv' failed
       last 10 log lines:
       > -- Found WaylandProtocols: //nix/store/6w627naapy17padgxzkn6w0yzdyjgjwr-wayland-prot
       > CMake Error at /nix/store/sa1yjb7xxrzcbd1bysj3r561vidfxxvb-cmake-3.29.6/share/cmake-
       >   Could NOT find WaylandScanner (missing: WaylandScanner_EXECUTABLE)
       > Call Stack (most recent call first):
       >   /nix/store/sa1yjb7xxrzcbd1bysj3r561vidfxxvb-cmake-3.29.6/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
       >   /nix/store/kdbjfq8zvpzjjxpnp4r8xc65bs2bfn2f-extra-cmake-modules-5.116.0/share/ECM/find-modules/FindWaylandScanner.cmake:74 (find_package_handle_standard_args)
       >   CMakeLists.txt:150 (find_package)
       >
       >
       > -- Configuring incomplete, errors occurred!
       For full logs, run 'nix log /nix/store/cjfdi947ivzx2pv29d0xpql6rql63a5c-ueberzugpp-2.9.6.drv'.
error: 1 dependencies of derivation '/nix/store/z0fss25gkzf1mg28vr5my9v9dmw9ws5x-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rjgiid561gw90nla0plxhpw1ymbkl1p0-home-manager
-generation.drv' failed to build
```

### Additional context

I switched back to ueberzug which builds fine.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.45, NixOS, 24.11 (Vicuna), 24.11.20240814.c3aa7b8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/store/sfycwi72zfjsspidinx56ajaiffpyh17-source`
```
flake version:
```
 • Updated input 'nixpkgs':
        'github:nixos/nixpkgs/a58bc8ad779655e790115244571758e8de055e3d' (2024-08-11)
      → 'github:nixos/nixpkgs/c3aa7b8938b17aebd2deecf7be0636000d62a2b9' (2024-08-14)
```
[flake.lock.txt](https://github.com/user-attachments/files/16645332/flake.lock.txt)
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ghpzin** [comment] 2024-08-17 17:20
Duplicate of https://github.com/NixOS/nixpkgs/issues/334820
Seems to be fixed on master with https://github.com/NixOS/nixpkgs/pull/334833

**Closed** 2024-08-18 00:03 UTC
Labels: 0.kind: build failure
