### ISSUE TITLE
BROKEN PACKAGE: Bottles doesn't start at all after the last update

### ISSUE THREAD

**Issue by saikatdas0790** [NixOS/nixpkgs#226766] opened 2023-04-18 03:36 UTC
### Describe the bug
Bottles gets stuck on the "Starting up" screen showing the "Downloading ~20kb of packages" message.

### Steps To Reproduce
1. Open bottles
2. See the error message

### Expected behavior
Bottles would start

### Screenshots
![image](https://user-images.githubusercontent.com/7412443/232663954-4efae8b7-84b9-4f67-ad4e-f520f0b7dbb7.png)

### Additional context
Additionally an earlier update broke the bottles listing screen. It would only let you have the "Library" tab active, but wouldn't let you click over to the "Bottles" listing screen. But you could still start the ".exe" file by double clicking it from a file explorer while having Bottles open in the background

### Notify maintainers
@psydvl @SuperSamus 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[saikat@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.24, NixOS, 23.05 (Stoat), 23.05pre474575.f00994e78cd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos, nixos-22.11-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SuperSamus** [comment] 2023-04-18 10:35
About the Library tab, it seems that Bottles depends on `programs.dconf.enable` for it to work.
Looking upstream, the cause seems to be [these lines](https://github.com/bottlesdevs/Bottles/blob/084a7987859fcc455f2675e6bdce8c499ac14b13/bottles/frontend/windows/main_window.py#L206-L211).

I'm not knowledgeable on how it should be fixed, though.

**Comment by saikatdas0790** [comment] 2023-04-20 12:14
> About the Library tab, it seems that Bottles depends on `programs.dconf.enable` for it to work. Looking upstream, the cause seems to be [these lines](https://github.com/bottlesdevs/Bottles/blob/084a7987859fcc455f2675e6bdce8c499ac14b13/bottles/frontend/windows/main_window.py#L206-L211).
> 
> I'm not knowledgeable on how it should be fixed, though.

So, if I manually add `programs.dconf.enable = true` to my `configuration.nix`, will that fix it?

**Comment by saikatdas0790** [comment] 2023-04-20 12:15
> Upstream problem [bottlesdevs/Bottles#2788](https://github.com/bottlesdevs/Bottles/issues/2788), it was fixed by [bottlesdevs/Bottles#2809](https://github.com/bottlesdevs/Bottles/pull/2809). I'll see if it's better to backport now or to wait for the next version. (Someone already backported it, [ElXreno@36d1edc](https://github.com/ElXreno/nixpkgs/commit/36d1edc50e000761e71ec06d4688038901227a16))

I'm on the `unstable` channel. Just `nixos-rebuild switch --upgrade` should pull in the fixes, right?

**Closed** 2023-04-20 17:02 UTC
Labels: 0.kind: bug

**Comment by francocalvo** [comment] 2023-04-21 02:38
Maybe I'm doing something wrong, but I have the same problem. I've updated the flake and rebuild, and it hangs in the same place.  I also added `programs.dconf.enable = true`, but it didn't help.

**Comment by SuperSamus** [comment] 2023-04-21 09:15
https://nixpk.gs/pr-tracker.html?pr=226829
It's on `nixpkgs-untable`, but not on `nixos-unstable`.

**Comment by saikatdas0790** [comment] 2023-04-24 06:53
@SuperSamus So, after upgrading to the latest on unstable channel, the app starts again.
And I can list my bottles after adding the `dconf enable` enable bit to my `configuration.nix`

But the flow of starting an executable by double-clicking and selecting the bottle to run under while having bottles open in the background is now broken.

Thoughts?
