### ISSUE TITLE
osu-lazer-bin: unable to open URLs

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#248461] opened 2023-08-11 04:11 UTC
### Describe the bug
to register a new account the game tries to open an URL in the browser, but fails (https://github.com/ppy/osu/issues/24498)
this can be tested by opening a URL from news

### Steps To Reproduce
1. start osu!
2. open menu
3. click last item and scroll down
4. click version
5. click on a link in the news
6. click "Yes" in dialog
7. nothing happens

### Expected behavior

Be able to open URLs.

### Screenshots

![osu_2023-08-11_05-50-30](https://github.com/NixOS/nixpkgs/assets/91113/b7bb92fc-fedc-409b-b9ee-c99b702d5d0c)

### Additional context
It works with the osu-lazer (not -bin) package.

So the **workaround** is to use it to create a new account and then use the other to play.

### Notify maintainers

@delan @stepbrobd

### Metadata

using latest version from unstable with `snow run osu-lazer-bin`

 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.8, NixOS, 22.11 (Raccoon), 22.11.4588.93fddcf640c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by stepbrobd** [comment] 2023-08-11 04:57
I don't have a linux machine with DE, and I was unable to reproduce the issue on aarch64-darwin:

<img width="1800" alt="Screenshot 2023-08-10 at 22 53 23" src="https://github.com/NixOS/nixpkgs/assets/81826728/40114c9a-4205-482f-badd-473d19fbbea8">

**Comment by stepbrobd** [comment] 2023-12-13 23:36
Any update?

**Comment by stepbrobd** [comment] 2023-12-17 19:39
No update since Aug. 11, closing as completed

**Closed by stepbrobd** 2023-12-17 19:39 UTC
Labels: 0.kind: bug
