### ISSUE TITLE
Notifications and other popups are treated like "normal" windows on Plasma Wayland

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#118650] opened 2021-04-06 08:42 UTC
**Describe the bug**
When running Plasma Wayland,  notifications and krunner pop-downs are treated like first-class windows and therefore take focus and appear in the task manager.

This used to be an issue back in the day (https://bugs.kde.org/show_bug.cgi?id=365107) so this is in all likelyhood something we do (wrong) on our side.
    
**To Reproduce**
1. follow the steps in https://github.com/NixOS/nixpkgs/pull/117102 to get wayland running
2. log in to the plasma wayland session
3. wait for a notification or trigger krunner
4. observe the focus steal (for notifications) and appearance in the task manager

**Expected behavior**
Notifications and similar should not be treated as a regular window and therefore not show in task manager or receive focus (krunner should still have focus of course).

**Notify maintainers**
Cc: @NixOS/qt-kde 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.11, NixOS, 21.05.git.d3ff65233f9M (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210326_dd77f71`
 - channels(root): `""`
 - channels(peter): `""`
 - nixpkgs: `/nix/store/w9zhp284bnx3f1ma6mdbsw008jpnq15v-nixpkgs_unstable`

References:
- https://github.com/NixOS/nixpkgs/pull/117102

**Comment by peterhoeg** [comment] 2021-04-06 11:01
https://bugs.kde.org/show_bug.cgi?id=435415

**Comment by samueldr** [comment] 2021-04-06 18:39
Oh, my intuition tells me this could be the root cause of the totally-wonky Plasma Mobile notifications.

**Comment by peterhoeg** [comment] 2021-05-06 00:41
@samueldr - I found this: https://community.kde.org/Plasma/Notifications#DesktopEntry_in_notifyrc

I haven't looked through the code yet (I'm not at all familiar with the plasma code) but it sure sounds like there is a disconnect between kwin, application and desktop file.

  > However, KNotifications uses the application name for identification rather than the desktop entry, so a DesktopEntry hint must be placed in the respective notifyrc file, so they can be filed under "applications".

**Comment by samueldr** [comment] 2021-05-06 16:38
I don't think this is relevant to the "rendering" bits of the notifications. I'm not an expert either, but to me this sounds like it is concerned with the communication between apps and the daemon.

BUT, "However, KNotifications uses the application name for identification rather than the desktop entry" is possibly a similar issue to the one we're having. But it's likely to be something concerning the kwin/KNotifications relationship, rather than KNotifications/app relationship.

**Comment by pasqui23** [comment] 2021-05-14 23:23
The bug @peterhoeg links says that the bug was fixed by these git commit back in the day:
https://invent.kde.org/plasma/kwin/-/commit/c81d8204f9a3a9fc806fedf7a8bb915dc19a7892
https://invent.kde.org/guokaka/kwayland/-/commit/2f4cb0613b1c31ef3a32d6a7d47dbf484e2b85ef
https://invent.kde.org/plasma/kwayland-integration/-/commit/fdb09dc29a3d628a0c64db1ec5eba613d8728b52

**Comment by pasqui23** [comment] 2021-05-15 09:54
So I've followed the instructions given to @peterhoeg in the 2nd bug report
Here are the properties of a notification window on Wayland:
![2021_05_15_11_35_21](https://user-images.githubusercontent.com/6931743/118356128-55c07c80-b563-11eb-8c63-271f4dbcdec5.jpg)
And here the same on X: 
![Screenshot_20210515_113831](https://user-images.githubusercontent.com/6931743/118356140-64a72f00-b563-11eb-82d7-6a7df888a12a.png)
![Screenshot_20210515_113900](https://user-images.githubusercontent.com/6931743/118356141-653fc580-b563-11eb-93e4-413473c0aab0.png)

**Comment by pasqui23** [comment] 2021-05-15 10:15
Of note:Entire window class is `plasmashell-wrapped.org.kde.plasmashell` on Wayland, `plasmashell.plasmashell` on X
SImilarly windows type is Normal window on Wayland, and apparently empty on X

**Comment by samueldr** [comment] 2021-05-15 18:20
> `plasmashell-wrapped`

I would bet this is the issue.

**Comment by pasqui23** [comment] 2021-05-15 21:00
@samueldr where do you think we shpuld look specifically?

**Comment by samueldr** [comment] 2021-05-15 21:47
My hunch is some special casing in kwin. I still haven't taken the time to look into that. That should be the first thing I do when I resume work on the PR monday, since that's a good clue.

**Comment by pasqui23** [comment] 2021-05-27 10:46
@samueldr any news?

**Comment by samueldr** [comment] 2021-06-02 05:43
(All looked at under Plasma Mobile...)

My current line of thoughts is that the window role is lost for some reason. This is supported by your previous screenshots, and my testing under Plasma Mobile shows me the same issue where window type is *Normal*.

AFAICT this condition is never true:

 * https://invent.kde.org/plasma/kwin/-/blob/98424da878e69048eaf1ca8a097fdc44d8090392/xdgshellclient.cpp#L927-930

But if I force any `m_plasmaShellSurface` clients to not accept focus, while it breaks some things, the notification *does* stop taking over the focus.

```diff
--- a/xdgshellclient.cpp
+++ b/xdgshellclient.cpp
@@ -926,6 +926,7 @@ bool XdgToplevelClient::acceptsFocus() const
         }
         if (m_plasmaShellSurface->role() == PlasmaShellSurfaceInterface::Role::Notification ||
             m_plasmaShellSurface->role() == PlasmaShellSurfaceInterface::Role::CriticalNotification) {
+       return false;
             return m_plasmaShellSurface->panelTakesFocus();
         }
     }
```

This is not a solution, far from it. I simply don't know how to debug this kind of issues, and am learning along the way how all of this is setup within kwin, plasma, and friends.

This also does not affect the window sizing in Plasma Mobile, **but** it changes something for sure since it won't put the notification halfway off-screen.

I would assume if the window never lost it

**Comment by peterhoeg** [comment] 2021-06-02 05:58
Can I trouble you to report your findings on the KDE bug tracker? I'm sure the guys over there are able to help.

**Comment by pasqui23** [comment] 2021-06-02 08:02
I suspect https://github.com/NixOS/nixpkgs/issues/107595 is connected

**Comment by samueldr** [comment] 2021-06-02 17:51
@peterhoeg I don't have much confidence in my findings.

Reading through kwin's and plasma-* and kwayland* projects a bit hapazardly I found out that *maybe it's totally expected that window roles are normal under wayland*. Though I'm not confident either in those findings.

**Comment by samueldr** [comment] 2021-06-02 17:53
@pasqui23 AFAIK [this patch](https://github.com/NixOS/nixpkgs/blob/7db379d016a9bad7b7da9b81103ab7454faa3344/pkgs/desktops/plasma-5/kwin/0001-NixOS-Unwrap-executable-name-for-.desktop-search.patch) solved that.

**Comment by samueldr** [comment] 2021-06-03 02:05
Looks like I'm stabbing in the dark, at random, and only hitting irrelevant bits. I'd need a KDE/Plasma person to take a better look at that. It is exhausting to look into, since I'm mostly learning everything from scratch on the spot.

**Comment by pasqui23** [comment] 2021-08-09 21:53
Not yet fixed in 5.22
![image](https://user-images.githubusercontent.com/6931743/128777956-6dd0dc78-5ea3-468c-9b1b-06ec048cf29a.png)
However I have also installed Grid WM and I found that the spectacle window got managed by Grid when on X11 it was not, and the window for unlocking kwallet does not get positioned in the center as it does in X11.

Those put thogether suggest that somehow KWin thinks every window is a normal window.
Also the properties of a notification window on wayland
![image](https://user-images.githubusercontent.com/6931743/128779076-0fbf07be-9307-4460-8f94-2bd42308bd5c.png)
![image](https://user-images.githubusercontent.com/6931743/128779127-868d05ee-1ebe-4291-a72f-d0b3c813a02e.png)

**Comment by pasqui23** [comment] 2021-08-09 21:59
Also the Plasma entry in the tasks list shows up also on openin plasmoid menus like kickoff or the notification menu.
Also the sound menu is put in the top left instead of bottom center
![image](https://user-images.githubusercontent.com/6931743/128779887-c45c9a5c-9c9d-483c-bfeb-b10cb47945af.png)

**Comment by pasqui23** [comment] 2021-08-09 22:06
Also also no clock widget

**Comment by pasqui23** [comment] 2021-08-09 22:09
Ok how do we contact the KDE devs for guidance?

**Comment by pasqui23** [comment] 2021-08-09 22:25
So here are the 3 commits that fixed this problem back in the day
https://invent.kde.org/frameworks/kwayland/-/commit/2f4cb0613b1c31ef3a32d6a7d47dbf484e2b85ef
https://invent.kde.org/plasma/kwin/-/commit/c81d8204f9a3a9fc806fedf7a8bb915dc19a7892
https://invent.kde.org/plasma/kwayland-integration/-/commit/fdb09dc29a3d628a0c64db1ec5eba613d8728b52

@samueldr This suggest that window roles are not expected to be "Normal" for notification,
especially since PlasmaShellSurfaceInterface::Private::setRole remain unchanged in master
https://invent.kde.org/frameworks/kwayland/-/blob/master/src/server/plasmashell_interface.cpp#L218

**Comment by pasqui23** [comment] 2021-08-09 23:04
So controlling the window type on a notification turn out that on X11 is revealed as empty.
Follows wold,possibly incorrect speculation: this suggest that the Notification role somehow is broken and on X11 the broken role behaves like a notification but on Wayland it behaves like a normal window.

**Comment by haizaar** [comment] 2021-09-22 15:03
Devs, how can we, community, help to give some traction to this issue. 
Judging by the complexity of the issue, will setting up a bounty through https://issuehunt.io/ help?

**Comment by samueldr** [comment] 2021-09-22 18:31
Most likely, it's not an issue about "traction" internal to Nixpkgs, but about talent knowledgeable in the intersection of \[Kwin, Wayland, Nixpkgs packaging\]. Most devs involved in this current discussion would be, I assume, knowledgeable with Nixpkgs packaging only.

**Comment by haizaar** [comment] 2021-09-23 00:29
> Most likely, it's not an issue about "traction" internal to Nixpkgs, but about talent knowledgeable in the intersection of [Kwin, Wayland, Nixpkgs packaging]. Most devs involved in this current discussion would be, I assume, knowledgeable with Nixpkgs packaging only.

That's my understanding too hence I'm trying to be creative here. Can someone with the write access try connecting issuehunt.io to this repo and we'll give it a shot?

**Comment by Artturin** [comment] 2021-09-23 03:10
> That's my understanding too hence I'm trying to be creative here. Can someone with the write access try connecting issuehunt.io to this repo and we'll give it a shot?

fyi there are bounty sites that dont need to be connected such as gitpay and bountysource

i have received a bounty via gitpay in https://github.com/NixOS/nixpkgs/issues/130590 
and if needed the maintainer can help if there are issues @alexanmtz

**Comment by pasqui23** [comment] 2021-09-23 10:02
@Artturin what sites you suggest?

**Comment by Artturin** [comment] 2021-09-23 10:46
I've edited bountrysource out of my comment because it appears that they've been acquired by a ["by a blockchain company"](https://www.theblockchain-group.com/) 
https://github.com/bountysource/core/issues/1539

So I suggest gitpay since it's dev is active

**Comment by pasqui23** [comment] 2021-09-23 12:42
Ok I've put $50 on it on gitpay https://gitpay.me/#/task/535

**Comment by haizaar** [comment] 2021-09-23 14:10
# Donate to help make it happen: https://gitpay.me/#/task/535
![image](https://user-images.githubusercontent.com/58201/134522423-9406ce73-db07-41d5-9052-36c9e6cbfb80.png)



(trying to make it to sticking out)

**Comment by alexanmtz** [comment] 2021-09-23 14:19
Thanks, @Artturin for recommending [Gitpay](https://gitpay.me)

And let me know if any of you have any issues, and all feedback will be appreciated 🙏

**Comment by Artturin** [comment] 2021-09-23 19:14
i have seen this issue app_id issue on other wayland programs where the app_id is binname-wrapped

im also experimenting with changing the wrapper to move the wrapped binaries to `$out/.bin/binname` instead of `$out/bin/.binname-wrapped`

**Comment by Artturin** [comment] 2021-09-23 20:23
added instructions to test to the pr

**Comment by andrevmatos** [comment] 2021-09-23 20:30
@Artturin It seems your fix is enough for plasmashell (notifications, this issue), but this mismatch between appIds caused by the wrappers seems likely to cause issues with any other wrapped GUI app on plasma wayland. Would there be a generic fix to ensure any wrapped app keeps its correct `app_id`?

**Comment by Artturin** [comment] 2021-09-23 20:31
im looking in to it 
> im also experimenting with changing the wrapper to move the wrapped binaries to $out/.bin/binname instead of $out/bin/.binname-wrapped. however that will require larger changes

**Comment by CertainLach** [comment] 2021-09-25 13:49
Seems like setting orgDomain/desktopFileName explicitly via `QApplication.{setOrganizationDomain/setDesktopFileName}` for plasmashell fixes this issue too, but i will try to implement this fix via patching unwrapping file name in qt itself, to make it work for every qtwayland app

**Comment by CertainLach** [comment] 2021-09-25 17:49
This issue is not caused by app_id, but something else
PR #139459 fixes app_id, but this issue is still present
![Screenshot_20210925_204702](https://user-images.githubusercontent.com/6235312/134781173-dc1421f1-f9ad-4af3-b4cb-422a953a111e.png)

**Comment by CertainLach** [comment] 2021-09-26 12:55
Seems like this issue is in plasmashell itself, i can see this via `WAYLAND_DEBUG=1`
```
[1470662.098]  -> org_kde_plasma_surface@28.set_role(1)
[1470662.128]  -> org_kde_plasma_surface@28.set_role(1)
[1470884.175]  -> org_kde_plasma_surface@28.set_role(1) -- panels
[1500945.930]  -> org_kde_plasma_surface@39.set_role(2)
[1501766.760]  -> org_kde_plasma_surface@39.set_role(2) -- desktop
```

But no other surface created by plasmashell receives role

**Comment by CertainLach** [comment] 2021-09-26 13:47
`kwayland-integration` `kwindowsystem` plugin is responsible for this (It provides `plugins/kf5/kwindowsystem/KF5WindowSystemKWaylandPlugin.so`), but just adding it to `systemPackages` doesn't help, because `kwindowsystem` is patched to be pure, and only load plugins from itself: https://github.com/NixOS/nixpkgs/blob/nixos-21.05/pkgs/development/libraries/kde-frameworks/kwindowsystem/0001-platform-plugins-path.patch#L32 (`QT_PLUGIN_PATH` is defined at build time)

We also can't just add `kwayland-integration` to its path, as this package itself depends on kwindowsystem

The only way i see here - make `kwindowsystem` plugin loading impure (by removing this patch), and rely on existing `QT_PLUGIN_PATH` being set here: https://github.com/NixOS/nixpkgs/blob/nixos-21.05/nixos/modules/services/x11/display-managers/sddm.nix#L209

**Comment by CertainLach** [comment] 2021-09-26 14:29
Starting session via `startplasma-wayland` with #139459 and #139537 applied on top of 39b5332bd1065fc5bc4446b2a7062ebea9e0a4e5 fixes this issue

**Comment by samueldr** [comment] 2021-09-26 18:31
(Tangentially related, I'll be trying with the plasma-mobile PR tomorrow. Hopefully this is what fixes the issues there too.)

**Comment by samueldr** [comment] 2021-09-26 18:40
@CertainLach do you have a good enough mental model of what is happening to know if, instead of (ab)using the environment through tons of wrappers, we'd instead [allow loading Qt plugins for all dependencies intrinsically regardless of the environment](https://github.com/NixOS/nixpkgs/pull/44047)?

Note that I'm not talking about "unwrapping" the name of `/proc/self/exe`. I'm talking about the general idea of making Qt aware of library paths through a declarative and pure (enough?) method that does not rely on an unreliable method like the environment and wrappers.

I still think that using wrappers and the environment is the worst misfeature in NixOS integration we're still doing.

**Comment by jansol** [comment] 2021-09-27 07:06
If the wrapper magic is the problem, I wonder if the "proper" solution would also make screensharing/recording via pipewire, ssh-agent and fcitx (and presumably other IMEs) finally work on wayland as well.

**Comment by samueldr** [comment] 2021-09-27 17:56
@jansol unlikely that it *alone* would be the fix, but it might be part of making things easier.

It seems that their design for Wayland application "authentication" relies, among other things, on looking at the application names (from `/proc/self/exe`), finding either the desktop file or dbus description for said app. This is where "unwrapping" is currently needed. Without unwrapping, either directly the application name is wrong, or the desktop file / dbus files for `.$app-wrapped` don't exist.

Then there's the possibility that "`.so`" Qt plugins aren't found if a wrapper is missing or misconfigured. Though that one is less likely to be an issue, assuming the wrappers are configured.

It's possible every service needs to be tracked down to their hardcoded special casing in the different Wayland components to know for sure how they work.

**Comment by samueldr** [comment] 2021-09-27 19:37
@CertainLach's fixes works for Plasma Mobile!

<details><summary> :computer::camera: Screenshot </summary>

![image](https://user-images.githubusercontent.com/132835/134973389-e56222e6-804d-4ff3-b310-852ab9ffaf66.png)

</details>

**Comment by CertainLach** [comment] 2021-09-27 20:31
@samueldr 
> we'd instead allow loading Qt plugins for all dependencies intrinsically regardless of the environment?

I agree with that qt wrapping is a mess, but i see the better story with qt plugins much as something like:

- Patch qt to load plugins from something like `/run/current-system/<current derivation hash>/` (I.e `/nix/store/aabbcc-kwindowsystem` would load plugins from `/run/current-system/aabbcc-kwindowsystem`)
- Add nixos module to define plugin directories:
```
enviroment.qtPlugins = {
  "${pkgs.kwindowsystem}" = [
    pkgs.kwayland-integration
  ];
};
```

This way it would be explicit, and pure enough to not break things with errorously loaded plugins

**Comment by samueldr** [comment] 2021-09-27 20:40
> 
> I agree with that qt wrapping is a mess, but i see the better story with qt plugins much as something like:
> 
>     * Patch qt to load plugins from something like `/run/current-system/<current derivation hash>/` (I.e `/nix/store/aabbcc-kwindowsystem` would load plugins from `/run/current-system/aabbcc-kwindowsystem`)
> 
>     * Add nixos module to define plugin directories:

Breaks on non-NixOS systems, user profiles or `nix-shell`.

> This way it would be explicit, and pure enough to not break things with errorously loaded plugins

The way I implemented in that old PR was pure from the inputs of a given derivation, *while still staying compatible* with the less pure automatic loading of plugins from profile directories *that is already in use*.

**Comment by samueldr** [comment] 2021-09-30 02:05
Reopening; I think it also requires #139459, though I never tested for myself.

**Comment by CertainLach** [comment] 2021-09-30 19:20
#139459 doesn't required for this fix, but it fixes other possible problems, i.e kwin has some plugins with hardcoded `app_id`s, i.e `glide` uses this to blacklist animation on shell surfaces

**Comment by haizaar** [comment] 2021-10-01 01:37
Huge thanks for fixing this!
Can someone else confirm it solves the problem for them? (we need to release the bounty :)

**Comment by jansol** [comment] 2021-10-01 08:48
With #139537 applied running `sleep 10; notify-send "foo"` in a terminal does indeed no longer steals focus from typing this comment in my browser. The notification also doesn't show up in the task manager.

**Comment by andrevmatos** [comment] 2021-10-01 15:55
I can also confirm several other plasma wayland issues I was experiencing got fixed by #139537 :
- blur on plasmoids, panel, yakuake/konsole are working again; before, I was only getting normal transparency and no blur
- some other plasmoids popups besides notifications were also stealing focus and having an entry on taskbar, including launcher
- volume/brightness HUD were also stealing focus, and were always localized on the top-left corner of the screen; they now appear in the center, as on X11

**Comment by haizaar** [comment] 2021-10-21 16:26
@CertainLach can you please submit [your PR that fixed this](https://github.com/NixOS/nixpkgs/pull/139537) at the [bounty page](https://gitpay.me/#/task/535) as a solution (to claim the bounty)?

![image](https://user-images.githubusercontent.com/58201/138318738-b4f87e57-64b6-4c16-830f-e3cbdcd03fc0.png)

**Comment by CertainLach** [comment] 2021-10-21 16:33
I tried to do that before, but "The issue is closed on GitHub" check is missing, i though there is some confirmation required from issue creator
![Screenshot_20211021_193138](https://user-images.githubusercontent.com/6235312/138319571-694168d5-cb76-4219-a08f-c6fa115e5b0e.png)

**Closed** 2021-10-21 18:02 UTC
Labels: 0.kind: bug, 6.topic: qt/kde
