### ISSUE TITLE
Package request: SGDBoop

### ISSUE THREAD

**Issue by daemonspudguy** [NixOS/nixpkgs#237833] opened 2023-06-14 22:01 UTC
**Project description**
SGDBoop is a program that is used to add custom artwork to games on Steam, including non-Steam games

**Metadata**

* homepage URL: https://www.steamgriddb.com/boop
* source URL: https://github.com/SteamGridDB/SGDBoop
* license: CC-BY-NC-SA 4.0
* platforms: linux

**Comment by bayazidbh** [comment] 2023-10-07 04:54
Seems to be duplicate of #220937

**Comment by puffnfresh** [comment] 2023-11-22 11:38
Yeah, closing as duplicate.

**Closed by puffnfresh** 2023-11-22 11:38 UTC
Labels: 0.kind: packaging request
