### ISSUE TITLE
Darwin error: build of ‘/nix/store/[...]-pandoc-1.13.2.1.drv’ failed

### ISSUE THREAD

**Issue by nomosyn** [NixOS/nixpkgs#7840] opened 2015-05-14 08:44 UTC
[nix env gist](https://gist.github.com/nomosyn/76cf7959c553b4315a85)

**Comment by peti** [comment] 2015-05-17 10:30
Duplicate of https://github.com/NixOS/nixpkgs/issues/7646.

**Closed by peti** 2015-05-17 10:30 UTC
Labels: darwin, haskell
