### ISSUE TITLE
kde5 konsole terminal isn't working: displaying hundreds of tiny unreadable lines

### ISSUE THREAD

**Issue by fkz** [NixOS/nixpkgs#13519] opened 2016-02-27 22:25 UTC
## Basic info

To make sure that we are on the same page:

* Kernel: (run `uname -a`):
Linux nixos 4.4.2 #1-NixOS SMP Wed Feb 17 20:31:25 UTC 2016 x86_64 GNU/Linux
* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
16.03.git.18b8adc (Emu)
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.2
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
16.03.git.18b8adc (which is 40c586b7ce2c559374df435f46d673baf711c543 + cherry-picked d5a2c4cb05bd4274794fac2c268b2adb1901a749).

## Describe your issue here
konsole isn't working
### Expected result
A terminal is started with about maybe 30 lines
### Actual result
A terminal is started with about 600 lines, so none of them is actually readable. It also takes a few seconds until they're displayed. Other things like the menu are displayed normally.
### Steps to reproduce
`nix-shell -p kde5.konsole --run konsole`
### Workaround
Start konsole from an earlier profile. Or use kde4.konsole or any other terminal

**Comment by fkz** [comment] 2016-03-21 22:37
this is still not working for me. @ttuegel Have you been able to reproduce this?

**Comment by ttuegel** [comment] 2016-03-22 10:34
No, I still haven't been able to reproduce this. Can you take a screenshot? Also, are you using a HiDPI display?

**Comment by FRidh** [comment] 2016-03-30 12:15
Have you checked https://bugs.kde.org/ ?
I have the issue that `kde5.konsole` doesn't show any text. The shell does seem to work.

How is the CPU usage of konsole? And of other applications using the terminal part? (E.g. dolphin and kate when the terminal is active)

**Comment by fkz** [comment] 2016-03-30 12:42
I've checked this with a fresh user account now, and there the issue isn't happening. So it has to be something with my config which might indicate that it's an upstream bug (or possibly misconfiguration on my part, but I haven't found any suspicious setting yet). The terminal plugin (e. g. for kate) has the same issue (this is the most annoying part for me).

I'm not using a HiDPI

@FRidh Maybe you have the same issue, because the lines are so tiny, you don't really see them. For me, only the cursor is shown as a one-pixel white dot and everything else is black (some other letters occasionally produce a white dot, too) so when typing I can see it moving from time to time. Also selecting by the mouse does show white areas. CPU usage is pretty high at the start of the program, selecting is also very slow/cpu-intensitive.

**Comment by FRidh** [comment] 2016-03-30 12:56
@fkz sounds reasonable. Occasionally I do see a thin white line. 

I just tested with a new user as well, and indeed, the problem does not occur in that case.
The question is now what causes this. One would expect it to be the configuration. I've deleted all konsole configuration files, but that didn't solve it though.

**Comment by FRidh** [comment] 2016-03-30 13:09
changing font in konsole solved it.

**Comment by FRidh** [comment] 2016-03-30 13:13
Apparently the default `Arimo` doesn't work so well as a fixed width font. Changing that one in System Settings / Fonts to another one (e.g. monospace) solves it for all applications using terminal part.

**Comment by fkz** [comment] 2016-03-30 13:46
@FRidh indeed changing the font to monospace did solve the problem for me! Now, Arimo isn't even shown as a font choice anymore, so I can't reproduce the old behaviour anymore. Many thanks @FRidh this has been hunting me for a while, for some reason it never occured to me to try to change the font.

**Comment by FRidh** [comment] 2016-03-30 18:20
I'm glad we solved this, since it had been bothering me for a long time as well. As a sidenote, `kde5.yakuake` works good as well :)

I don't think this is a Nix issue but instead something for upstream so I am closing this now.

**Closed by FRidh** 2016-03-30 18:20 UTC
Labels: 6.topic: kde
