### ISSUE TITLE
nixos-rebuild switch kills the network

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#45740] opened 2018-08-29 10:21 UTC
## Issue description
Rebuilding the operating system shouldn't break the network connection ideally at all and certainly not more than 200ms. 

### Steps to reproduce
Unknown, but when only connected via wifi, there is a resource deadlock in the switching logic. I.e., something needs network, but something else has broken the wifi connection. 

Typically, canceling the operation (C-c) and then running it again works, but this is not how it should work, I think. I would like to see some guarantees listed in the manual too. I.e., "running nixos-rebuild switch when not modifying the network configuration will not break your connection", for example. 

I have seen this behavior on every laptop I have installed NixOS on. 

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.63, NixOS, 18.03.git.fde2012 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by basvandijk** [comment] 2018-08-30 22:03
Possibly related: https://github.com/NixOS/nixops/issues/833.

**Comment by l0b0** [comment] 2023-10-18 02:45
Can anyone still reproduce this? Otherwise, presumably it can be closed.

**Comment by nh2** [comment] 2023-10-18 02:54
I have not observed this, only came from the NixOps-on-Hetzner-specific issue in https://github.com/NixOS/nixpkgs/issues/45740#issuecomment-417481824, which was fixed in NixOps and which turned out independent of what's described here.

**Comment by kacperwyczawski** [comment] 2024-04-22 13:53
I think I have similar issue, while using `systemd-networkd` and Wi-Fi connection:

1. I run `nixos-rebuild switch`
2. Wi-Fi gets disconnected 
3. Rebuild fails, because I have `systemd.network.wait-online.anyInterface` set to `true`
4. I can't connect to Wi-Fi through `iwctl` (this is the weird part)

And that's really annoying, because I have to make a wired connection every time I rebuild system.

**Comment by samueldr** [comment] 2024-04-22 20:23
(Triaging)

If anyone is hitting a similar issue, please open a new issue with *your observations*. There might be enough different details that matters in your situation.

Closing as not reproduced, and the involved people are not involved in the community anymore.

**Closed by samueldr** 2024-04-22 20:23 UTC
Labels: 0.kind: bug, 6.topic: nixos
