### ISSUE TITLE
[RFC] i686 support

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#31089] opened 2017-11-01 13:59 UTC
I propose to add a very-low priority jobset following nixos-17.09 that builds for `i686-linux`, as I hear the platform is still useful to *some* people.

Current status on 17.09 and onwards: The big channels still contain i686 minimal ISOs, and a few packages and most NixOS tests get built on i686, but they are not considered channel blockers.

#### Proposed state:
- Additionally have binaries for "everything" on 17.09, but without any guarantees/obligations about them.
- Done via a separate jobset, evaluating (say) once a week, with minimal build shares, no e-mails sent to maintainers.  As it is now, x86 is the least stressed platform pair on Hydra, so this should have minimal impact.
- Possible downside: I'm not sure about the significance of impact on the bills from Amazon :-)  /cc @edolstra.

I can easily set it up myself, once there's rough consensus.
For (links to) related discussions see: https://github.com/NixOS/nixpkgs/pull/27923

**Comment by globin** [comment] 2017-11-01 14:08
We actually build the stdenv + all tests (https://hydra.nixos.org/eval/1406535?filter=i686-linux&compare=1406474&full=#tabs-still-succeed) which should make quite a few packages available in the binary cache.

**Comment by vcunat** [comment] 2017-11-01 14:15
Yes, just the minimal ISOs have ~350 MB compressed, so there's something inside.

**Comment by mkocha2** [comment] 2017-11-18 21:03
I am no longer interested in i686 support for execution, but there is another reason for why i686 support is good, which is as a portability test. Good code runs on every arch.

**Comment by woffs** [comment] 2017-11-21 17:23
It would be great to have more packages in the binary cache for i686. There are still some old but fine 32bit devices here, which run well with NixOS.

**Comment by vklquevs** [comment] 2017-11-26 13:07
I've encountered a common package that will not build on i686 (#32074).
I think supporting any arch other than the two most commonly used (64-bit linux and darwin) would help root out other reliance on externally-built binaries.

**Comment by vcunat** [comment] 2017-11-26 19:11
For reference, `aarch64-linux` is built on Hydra for unstable/master, and it's planned to remain in the following stable releases.

**Comment by volth** [comment] 2017-12-07 02:57
I'am for building all the packages on ```i686```, just to see failures and regressions on Hydra as upstream code and the compilers evolve.
No need to rebuild on every small change nor keep the binaries on cache.nixos.org.
Weekly or even monthly builds are OK.

**Comment by matthewbauer** [comment] 2018-04-17 21:05
Going through old milestones... If there's nothing actionable, is it okay to close this?

**Comment by Ekleog** [comment] 2019-02-16 00:09
This issue would need a RFC on the [RFC repository](https://github.com/NixOS/rfcs/), as the process changed since it was open. Closing for now so that people do not think something is going to happen from this issue alone.

You, reader who came in here looking for i686 builds, feel free to open a RFC! And if you do please remember to send a link to it here so that future readers know they don't have to open another RFC.

**Closed by Ekleog** 2019-02-16 00:09 UTC
Labels: 6.topic: policy discussion, 6.topic: user experience, 9.needs: community feedback
