### ISSUE TITLE
nextcloud-setup (occ): nextcloud is not installed

### ISSUE THREAD

**Issue by dermetfan** [NixOS/nixpkgs#48045] opened 2018-10-08 13:02 UTC
## Issue description

I tried a basic Nextcloud setup via NixOps but cannot get `nextcloud-setup` to finish:

```
systemd[1]: Starting nextcloud-setup.service...
sudo[31851]:     root : TTY=unknown ; PWD=/nix/store/0lmlypcb049nan7lvddy3nc7qr62gi4c-nextcloud-14.0.1 ; USER=nextcloud ; ENV=NEXTCLOUD_CONFIG_DIR=/data/nextcloud/config ; COMMAND=/nix/store/1cspcgbvmgnsf3y940rjxb6asbb5hzd8-php-7.1.22/bin/php -c /nix/store/gk2qihy5m6qhj6rx3x3vv2aypvax2n9m-php.ini occ upgrade
sudo[31851]: pam_unix(sudo:session): session opened for user nextcloud by (uid=0)
vgckadk50sc88hjsri77iy090rb5bxrv-unit-script-nextcloud-setup-start[31845]: Nextcloud is not installed - only a limited number of commands are available
vgckadk50sc88hjsri77iy090rb5bxrv-unit-script-nextcloud-setup-start[31845]:
vgckadk50sc88hjsri77iy090rb5bxrv-unit-script-nextcloud-setup-start[31845]:   Command "upgrade" is not defined.
vgckadk50sc88hjsri77iy090rb5bxrv-unit-script-nextcloud-setup-start[31845]:
sudo[31851]: pam_unix(sudo:session): session closed for user nextcloud
systemd[1]: nextcloud-setup.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: nextcloud-setup.service: Failed with result 'exit-code'.
systemd[1]: Failed to start nextcloud-setup.service.
```

The same configuration works in a nixos-container... except I use the `config.adminpassFile` option, then the same error occurs.

### Steps to reproduce

```nix
services.nextcloud = {
  enable = true;
  hostName = "nextcloud.mydomain.net";
  nginx.enable = true;
  config.adminpass = "secret";
};
```

## Technical details

<details>
<summary>NixOps build machine</summary>

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.74, NixOS, 19.03pre154487.0a7e258012b (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre154487.0a7e258012b"`
 - channels(dermetfan): `"nixos-17.09-17.09.3263.9e1d8b74706, nixos-small-18.03pre119573.30f6d630f1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

</details>

<details>
<summary>NixOps target machine</summary>

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.74, NixOS, 19.03pre154487.0a7e258012b (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(hydra): `"nixpkgs-18.03pre116432.263185aa68"`
 - channels(root): `"nixos-19.03pre154487.0a7e258012b"`
 - channels(dermetfan): `""`
 - channels(hydra-queue-runner): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

</details>

**Comment by eqyiel** [comment] 2018-10-08 23:14
This can happen if you have some bogus state from an existing install, check out what happens immediately before the upgrade command: https://github.com/NixOS/nixpkgs/blob/583e9835a872c1a632369cce352bc7d58f228b3e/nixos/modules/services/web-apps/nextcloud.nix#L307-L312

Maybe try moving your existing `config.php` out of the way and restarting `nextcloud-setup.service`.

**Comment by dermetfan** [comment] 2018-10-09 06:29
Ugh, sometimes it's so simple you don't see it. Purely my fault, thanks for the quick help!

**Comment by tobiasBora** [comment] 2020-09-17 15:45
For people that has the same issue, it also occurs to me, I guess because the first time install failed due to bad permission of password files (I guess). So the home folder of nextcloud was in an inconsistent state, and I needed to first put back the good permission on the file, and then clean it/reinstall using:

    # rm -rf /var/lib/nextcloud ## maybe removing config.php alone is enough
    # nixos-rebuild switch

However, I think that it would be nice to make that clearer for the users. Indeed, as soon as we need to create a password file with permission `nextcloud:nginx`, I don't see how we can make it work on a first install since user nextcloud does not even exist, so I guess that most people will have that issue.

Do you think it's possible to automatically clean this folder if the install never got to the end? Or maybe simpler, to check using another method if nextcloud is installed, for example by creating a file `${cfg.home}/install_successful` if the script goes to its end once, and replacing the test `if [[ ! -e ${cfg.home}/config/config.php ]]; then ` with `f [[ ! -e ${cfg.home}/install_successful ]]; then `?

**Comment by Arteneko** [comment] 2022-12-21 16:22
This issue still exists with fresh instances as of nixpkgs 22.11 with nixos. (unstale)

**Comment by Pikatsuto** [comment] 2023-09-08 18:32
hello i was confronted with the same problem and after looking i found that it comes from this condition that was added for the same for this bug.

the if checks for the presence of the config.php file and does the installation that should generate it if it's not present

the current problem is that if you're using a database other than sqlite, the file is created beforehand to store the database identifiers.

you'd need to add a condition that also launches the installation if you're using a database manager other than sqlite, and then proves that you've done the installation in a file, so you don't have to do it again every time you run the program

i apologize in advance i'm a developer but i'm new to nix so i don't know enough about the language to write this algorithm otherwise i would have done it with pleasure

I also apologize because I don't speak English so I used a translator for this message. I hope it will be perfectly readable.

link of the lines to modify:
https://github.com/NixOS/nixpkgs/blob/583e9835a872c1a632369cce352bc7d58f228b3e/nixos/modules/services/web-apps/nextcloud.nix#L307-L312

**Comment by Arteneko** [comment] 2023-09-09 05:29
Your message is perfectly fine, and thanks for your investigation, it may indeed be the cause.
i’m not currently able to work on a patch for this but if it’s still pending once i have more time i’ll look into it

---
/ Artémis (she/her;it/its)

**Comment by Ma27** [comment] 2024-01-11 15:40
> I guess in my case it was because the first time install failed due to bad permission of password files

This got fixed in the meantime: if `nextcloud-setup` cannot read these files (and the occ command would fail subsequently), it fails early.

So the cause for the reopen doesn't exist anymore.

Existing state from previous installs (original problem) must be cleaned up by the administrator, NixOS doesn't touch application state when a service gets removed and reinstalled. If that needs to change, it should be done via a policy for all modules, not by changing a single module to behave slightly differently.

> the current problem is that if you're using a database other than sqlite, the file is created beforehand to store the database identifiers.

That isn't true. Assuming you mean the parameters for a database connection, these are stored in `override.config.php`.
`config.php` is created by `nextcloud-occ`, not by a mechanism from NixOS, so it is actually created by the installation command.

If I'm misunderstanding you, please open a new issue because that is most likely a different issue (even though the symptom might be similar or the same).

I'll close this now because this is about issues that were solved a while ago.

**Closed by Ma27** 2024-01-11 15:40 UTC

**Comment by dotlambda** [comment] 2024-07-12 21:49
I've had this happen to me twice already. The reason is--I think--that `/var/lib/nextcloud` hadn't been mounted yet when `nextcloud-setup.service` was started.
