### ISSUE TITLE
sway: xwayland: Fractional scaling is broken after suspend 

### ISSUE THREAD

**Issue by asbachb** [NixOS/nixpkgs#90535] opened 2020-06-15 21:59 UTC
**Describe the bug**
Fractional scaling is broken after suspend.

**To Reproduce**
1. Enable fractional scaling in sway config
```
output eDP-1 {
  scale 1.5
  scale_filter linear
}
```
2. Open an Xwayland application like Atom
2. Close lid / suspend
3. Xwayland application scaling is broken

**Expected behavior**
Scaling should be correct after suspend.

**Screenshots**
![20200615_22h55m37s_grim](https://user-images.githubusercontent.com/1482768/84709848-3ee46500-af63-11ea-95f0-a05f262670dc.png)
![20200615_23h20m13s_grim](https://user-images.githubusercontent.com/1482768/84709857-43a91900-af63-11ea-9de9-967a8b60d20f.png)

**Notify maintainers**
@gnidorah @primeos @colemickens 

**Metadata**
```
 ✘ asbachb@nixos  ~  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.46, NixOS, 20.03.2157.db31e48c5c8 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(asbachb): `""`
 - channels(root): `"nixos-20.03.2157.db31e48c5c8, nixos-unstable-20.09pre228204.467ce5a9f45"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: sway xwayland
# a list of nixos modules affected by the problem
module: 
```

**Comment by primeos** [comment] 2020-06-15 22:09
@asbachb could you test setting `Xft.dpi: 96` (or to another fixed value)? See:
- https://github.com/swaywm/sway/wiki#after-unplugging-an-external-display-some-applications-appear-too-large-on-my-hidpi-screen
- https://github.com/swaywm/sway/wiki#xwayland-dpi-increases-after-hotplug

If it only affects X11 applications this could potentially fix it.

**Comment by asbachb** [comment] 2020-06-15 22:55
@primeos does not work for me:

```
 asbachb@nixos  ~  cat ~/.Xresources 
Xft.dpi: 96
 asbachb@nixos  ~  cat ~/.config/sway/config | grep xrd
exec xrdb -load ~/.Xresources
```

Maybe related to: https://gitlab.freedesktop.org/xorg/xserver/-/issues/731

**Comment by primeos** [comment] 2020-06-16 09:35
@asbachb yeah, in your case it might be [this](https://github.com/swaywm/wlroots/issues/2221) where suspending / closing the lid has the same effect as turning the monitor off and on again.

I think [this](https://github.com/swaywm/wlroots/issues/988) is the original report in Sway's issue tracker and it seems like there is finally a [merge request to fix this issue](https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/449).

Anyway, I'll close this issue as this shouldn't be caused by our packaging in Nixpkgs.

**Closed by primeos** 2020-06-16 09:35 UTC
Labels: 0.kind: bug
