### ISSUE TITLE
AX200 Bluetooth doesn't work on NixOS

### ISSUE THREAD

**Issue by lovesegfault** [NixOS/nixpkgs#93452] opened 2020-07-19 00:36 UTC
**Describe the bug**
I just replaced the wifi card on my laptop with an Intel AX200. While WiFi worked right away I could not get bluetooth to work on this card. even `rfkill` wouldn't show any bluetooth devices.

**To Reproduce**
1. Install AX200 card
2. `rfkill` -> check that there is no bluetooth device

**Expected behavior**
For bluetooth to work like it did in my 9560 card

**Screenshots**

**Additional context**

**Notify maintainers**

@jtojnar who has a system with the same card

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.51, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - nixpkgs: `/run/current-system/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by turboMaCk** [comment] 2020-11-09 08:52
I wonder if you're still experiencing this issue.

**Comment by jtojnar** [comment] 2020-11-09 09:00
Already confirmed it on IRC but let’s have it here as well. Both Bluetooth and Wi-Fi work for me on NixOS out of the box (using `linuxPackages_latest`). But I have a desktop system and the Bluetooth needed to be connected separately through a cable to USB 2 header.

**Comment by RaghavSood** [comment] 2021-01-27 07:52
I'm still facing this on linuxPackages_latest - wifi works with no additional set up, but bluetooth isn't detected. Using a PCIe card with ax200


```
[nix-shell:~]$ uname -r
5.9.16
```

**Comment by jeblad** [comment] 2021-02-04 23:32
I have a TP-Link AX3000/Archer TX50E, I believe it is the same as the one sold as TX3000, and it shows up in `lsusb` as “Intel Corp. AX200 Bluetooth”. In `dmesg` it reports after initialization a set of strings like

```bash
[*] Bluetooth: hci0: failed to disable LE scan: status 0x1f
[*] usb 5-1: new full-speed USB device number 36 using ohci-pci
[*] usb 5-1: New USB device found, idVendor=8087, idProduct=0029, bcdDevice= 0.01
[*] usb 5-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[*] Bluetooth: hci0: Firmware revision 0.0 build 121 week 36 2020
```
This is dumped each 10 sec when I search for devices from Preferences.

This is on a pretty plain Ubuntu 20.10, `uname -a`reports “Linux chimera 5.8.0-41-generic #46-Ubuntu SMP Mon Jan 18 16:48:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux” (Yes, it is a tripple core AMD and it is old)

I can do some limited debugging on this computer if necessary.

Some writing on the net seems to indicate that the problems with this chip show up around 19.10-ish, and I wonder if BluetoothLE was included at the same time. That makes the LE scan error interesting. Something is inconsistent, and the chip is somehow reset. After that it does not work properly.

**Comment by jtojnar** [comment] 2021-02-05 00:02
I also have a [TP-Link AX3000 (Archer TX3000E)](https://www.amazon.com/TP-Link-Bluetooth-Ultra-Low-Archer-TX3000E/dp/B07ZV2CJL2). In `lsusb -t -v`, these are probably it

```
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/14p, 480M
    ID 1d6b:0002 Linux Foundation 2.0 root hub
    |__ Port 3: Dev 2, If 0, Class=Wireless, Driver=btusb, 12M
        ID 8087:0029 Intel Corp. 
    |__ Port 3: Dev 2, If 1, Class=Wireless, Driver=btusb, 12M
        ID 8087:0029 Intel Corp. 
```

Weirdly, they take two interfaces.

```
$ lspci | grep AX
02:00.0 Network controller: Intel Corporation Wi-Fi 6 AX200 (rev 1a)
```

`dmesg` is little different

```
[  +0,007199] Bluetooth: hci0: Bootloader revision 0.3 build 0 week 24 2017
[  +0,000972] Bluetooth: hci0: Device revision is 1
[  +0,000003] Bluetooth: hci0: Secure boot is enabled
[  +0,000002] Bluetooth: hci0: OTP lock is enabled
[  +0,000002] Bluetooth: hci0: API lock is enabled
[  +0,000001] Bluetooth: hci0: Debug lock is disabled
[  +0,000002] Bluetooth: hci0: Minimum firmware build 1 week 10 2014
[  +0,000005] Bluetooth: hci0: Found device firmware: intel/ibt-20-1-3.sfi
[  +0,000003] video LNXVIDEO:00: Restoring backlight state
[  +0,000006] PM: suspend exit
[  +0,029815] firewire_core 0000:06:01.0: rediscovered device fw0
[  +1,223484] e1000e: eth1 NIC Link is Down
[  +0,229886] iwlwifi 0000:02:00.0: Applying debug destination EXTERNAL_DRAM
[  +0,059989] Bluetooth: hci0: Waiting for firmware download to complete
[  +0,000004] Bluetooth: hci0: Firmware loaded in 1510643 usecs
[  +0,000028] Bluetooth: hci0: Waiting for device to boot
[  +0,014758] Bluetooth: hci0: Device booted in 14435 usecs
[  +0,000006] Bluetooth: hci0: Found Intel DDC parameters: intel/ibt-20-1-3.ddc
[  +0,001998] Bluetooth: hci0: Applying Intel DDC parameters completed
[  +0,077835] iwlwifi 0000:02:00.0: FW already configured (0) - re-configuring
```

Nothing about LE and both Bluetooth and Wi-Fi work just fine.

That is on Ubuntu 20.04, kernel (5.4.0-62-generic). I thought it was the latest but it got stuck in the LTS pit again :woman_shrugging: let me update. And in the past, I [checked](https://github.com/NixOS/nixpkgs/issues/93452#issuecomment-723871144) that it works fine on NixOS with 5.9 series kernel.

**Comment by jeblad** [comment] 2021-02-05 01:12
Perhaps this is non-comparable, the first could be just the loader while the latter is the actual firmware, but I find it interesting.

This work (from jtojnar)

```
Bluetooth: hci0: Bootloader revision 0.3 build 0 week 24 2017
```

This doesn't work (from my own box)

```
Bluetooth: hci0: Firmware revision 0.0 build 121 week 36 2020
```

Perhaps something broke?

**Comment by jtojnar** [comment] 2021-02-05 03:43
Updated to Ubuntu 20.10 and now I see the same firmware revision as you and Bluetooth still seems to work:

```
[   37.008795] Bluetooth: Core ver 2.22
[   37.008809] Bluetooth: HCI device and connection manager initialized
[   37.008811] Bluetooth: HCI socket layer initialized
[   37.008813] Bluetooth: L2CAP socket layer initialized
[   37.008815] Bluetooth: SCO socket layer initialized
[   37.022877] Bluetooth: hci0: Firmware revision 0.0 build 121 week 36 2020
[   39.644021] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   39.644022] Bluetooth: BNEP filters: protocol multicast
[   39.644025] Bluetooth: BNEP socket layer initialized
[   68.955124] Bluetooth: RFCOMM TTY layer initialized
[   68.955129] Bluetooth: RFCOMM socket layer initialized
[   68.955132] Bluetooth: RFCOMM ver 1.11
[  206.907151] Bluetooth: hci0: HCI reset during shutdown failed
```

The Driver in the lsusb is just the root USB hub to whose USB header on the motherboard we connected the Bluetooth part so that will obviously be motherboard specific.

**Comment by jeblad** [comment] 2021-02-05 04:19
It drops down to 12M, which is USB1.1. Perhaps it is something with the routing, yet I find it unlikely. Can also be something implementation specific with xhci vs ohci.

**Comment by ShamrockLee** [comment] 2021-04-12 15:01
I have an Intel AX201 network card on my new laptop. The bluetooth device is unable to be detected when booting from the NixOS 20.09 Plasma5 Desktop live image built against recent releases-20.09 (a7ff7a57c96).
Result of `nix-info -m` in the live session:
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.100, NixOS, 20.09.3418.89a06218ca0 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3418.89a06218ca0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by ryantm** [comment] 2022-02-20 00:54
I had this problem and the solution for me was to turn off my computer and unplug it for 5 seconds then turn it back on.

**Comment by ryantm** [comment] 2022-02-21 18:36
Since the last two posts are people that have had this issue and it was solved some way, I'm going to close this. If you are still having trouble, please post here and we can reopen!

**Closed by ryantm** 2022-02-21 18:36 UTC
Labels: 0.kind: bug, 6.topic: hardware

**Comment by dr460nf1r3** [comment] 2023-09-05 12:10
For the people finding this: I had to add 
~~~
boot.kernelModules = [ "btintel" ];
~~~
to make it work.
