### ISSUE TITLE
Build failure: feishin/electron

### ISSUE THREAD

**Issue by NovaViper** [NixOS/nixpkgs#369247] opened 2024-12-29 22:14 UTC
## Steps To Reproduce

1. build *feishin* (which will build electron)

## Build log

<details>

<summary>Build Log</summary>

[https://gist.github.com/NovaViper/f8d5e6f50bbc5acaa80b67957d4b983b](https://gist.github.com/NovaViper/f8d5e6f50bbc5acaa80b67957d4b983b)

</details>

## Additional context

It seems like any electron app could also be affected by this vuild failure since it's electron-unwrapped-31.7.6 that is failing to build

## Metadata

```❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.4, NixOS, 25.05 (Warbler), 25.05.20241213.3566ab7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.25.2`
 - nixpkgs: `/nix/store/22r7q7s9552gn1vpjigkbhfgcvhsrz68-source`
```

Trying to update my nixpkgs
```
• Updated input 'nixpkgs':
    'github:nixos/nixpkgs/3566ab7246670a43abd2ffa913cc62dad9cdf7d5?narHash=sha256-AKU6qqskl0yf2%2BJdRdD0cfxX4b9x3KKV5RqA6wijmPM%3D' (2024-12-13)
  → 'github:nixos/nixpkgs/adaa9f280329b5f814e8dc83eceddd42b20f72f4?narHash=sha256-EYaJtjLImMXzYEf9h52hkuPolXqKG/cAJlCOba6emL0%3D' (2024-12-29)
```

## Notify maintainers

@onny
@jlbribeiro
@Yaya
@teutat3s

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by teutat3s** [comment] 2024-12-29 23:35
Duplicate of https://github.com/NixOS/nixpkgs/issues/368172. This was fixed by https://github.com/NixOS/nixpkgs/pull/368966. Now we just need to wait until hydra picks up the latest commits from master.

**Closed** 2024-12-29 23:35 UTC
Labels: 0.kind: build failure
