### ISSUE TITLE
xfce4: Gtk-WARNING **: Unable to locate theme engine in module_path: “adwaita”,

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#27210] opened 2017-07-07 14:33 UTC
## Issue description
Warning displayed on terminal in default configuration.
```
Gtk-WARNING **: Unable to locate theme engine in module_path: “adwaita”, 
```

## Workaround
1. Install `gnome3.gnome_themes_standard`
2. Log out
3. Log in

### Steps to reproduce
Run `xfce4-about`

## Technical details
17.03.1482.1b57bf274a (Gorilla)

**Comment by joepie91** [comment] 2017-07-22 21:06
This is a duplicate of #16268.

**Closed** 2017-07-22 21:07 UTC
