### ISSUE TITLE
Could not connect to wpa_supplicant: (nil) - re-trying

### ISSUE THREAD

**Issue by musq** [NixOS/nixpkgs#59959] opened 2019-04-21 13:38 UTC
## Issue description
As pointed by #1204, the `wpa_cli` gives the following error when installing NixOS from LiveCD

`Could not connect to wpa_supplicant: (nil) - re-trying`

## Steps to reproduce

There are 3 scenarios:

### cli installer
1. Boot up the live CD 19.03
1. Run `wpa_cli` on the prompt from root user
1. Get error. Wifi doesn't work

### gui installer
1. Boot up the live CD 19.03
1. Run `systemctl start display-manager` to start KDE
1. Configure Wifi from the UI
1. Wifi works

### nixos configuration
1. Reboot on successfully installing nixos using the gui installer
1. Make sure to keep `networking.wireless.enable = true;` in `/etc/nixos/configuration.nix`
1. Run `wpa_cli` on the prompt from root user
1. Get error. Wifi doesn't work

Note that in both the cases (cli installer & nixos configuration), I've put the following in `/etc/wpa_supplicant.conf`
```
ctrl_interface=/run/wpa_supplicant
ctrl_interface_group=wheel
```

Running `strace wpa_cli` gives the following error

```
openat(AT_FDCWD, "/var/run/wpa_supplicant", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
```

## Technical details

Live CD: `https://releases.nixos.org/nixos/19.03/nixos-19.03.172306.73c885246fc/nixos-graphical-19.03.172306.73c885246fc-x86_64-linux.iso`
Laptop - `Asus Zenbook 430ua`
System: `x86_64-linux`

**Comment by ashish28ranjan** [comment] 2019-04-21 13:51
I've created this new issue because #1204 only deals with LiveCD installation procedure. However, I am not able to use Wifi even after the installation is complete.

**Comment by Infinisil** [comment] 2019-04-21 19:21
If you were to use the auto-generated config, you'd have to enable `services.networking.wireless.userControlled`, which would add the following: https://github.com/NixOS/nixpkgs/blob/63e5b23bd30cb7839aa1736a0ce940a5f787262e/nixos/modules/services/networking/wpa_supplicant.nix#L8-L10

Maybe give that a try

**Comment by mmahut** [comment] 2019-08-12 20:48
@musq any updates on this issue?

**Comment by musq** [comment] 2019-08-13 09:26
Hi @mmahut. I tried the snippet suggested by @Infinisil, but could not get it to work. I gave up easily assuming I had to read and understand everything about NixOS. So, I postponed it and then forgot about this.
So, no updates. I'm sorry.

**Comment by bobismijnnaam** [comment] 2020-07-25 07:13
For me this is still an issue. I have the following in my configuration.nix:

```
 networking.wireless = {
    enable = true;
    userControlled = {
      enable = true;
      group = "network";
    };
  };

  networking.useDHCP = false;
  networking.interfaces.enp0s31f6.useDHCP = true;
  networking.interfaces.wlp4s0.useDHCP = true;

  users = {
    groups.network = { };
    users.bobe = {
      isNormalUser = true;
      extraGroups = [ "wheel" "network" ];
    };
  };
```

Notably, `/run` only seems to contain the following:

```
$ ls /run
acpid.pid      booted-system   dhcpcd.unpriv.sock  mount             resolvconf  user
acpid.socket   current-system  initctl             nixos             sudo        utmp
agetty.reload  dbus            keys                nscd              systemd     wrappers
binfmt         dhcpcd.pid      lock                opengl-driver     tmpfiles.d  xtables.lock
blkid          dhcpcd.sock     log                 opengl-driver-32  udev
```

So if `/run/wpa_supplicant` is supposed to be used, it does not seem to be there currently. 

I don't know where the nixos-generated wpa_supplicant.conf is placed, so I can't check if it is generated correctly. If anyone knows where it is located or can point me at some documentation on how to find files like this I'd be happy to do some digging. I do have a wpa_supplicant.conf in place now at `/etc/wpa_supplicant.conf` to connect to internet manually, which I suspect might be overriding the nixos-generated one, but again not sure how to check this. (For completeness, this was generated by `wpa_passphrase ssid passwd > /etc/wpa_supplicant.conf` followed by `systemctl restart wpa_supplicant` to use it)

Some system info:

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.52, NixOS, 20.03.2611.bb8f0cc2279 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(bobe): `"home-manager-20.03"`
 - channels(root): `"nixos-20.03.2611.bb8f0cc2279, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

I would like to help resolve this, but not sure how to proceed currently. If anyone has some tips on other leads to investigate that'd be great.

**Comment by bobismijnnaam** [comment] 2020-07-25 11:39
After some looking at the wpa_supplicant nix module it seems that the following line is the problem:

https://github.com/NixOS/nixpkgs/blob/63e5b23bd30cb7839aa1736a0ce940a5f787262e/nixos/modules/services/networking/wpa_supplicant.nix#L7

So the config is only written if any networks are added. In my case, I didn't add any networks, so that would explain it. After adding a network to the `networks` in my config, `/run/wpa_supplicant` appeared and the `wpa_cli` command works. For completeness, my network section in configuration.nix now looks like this:

  ```
  networking.wireless = {
    enable = true;
    userControlled = {
      enable = true;
      group = "network";
    };

    networks = {
      MyNet = {
        psk = "hunter2";
      };
    };
  };
  ```

If this is indeed the cause, then to fix this, I propose to change the condition on line 7 in wpa_supplicant to nix from `if cfg.networks != {}` to `if cfg.networks != {} || cfg.userControlled.enable || cfg.extraConfig != ""` or something similar.

Maybe it can also be documented that if none of these conditions are true, wpa_supplicant is started with the `/etc/wpa_supplicant.conf` file (I know this is the default, but it might be nice to state explicitly this default is not overwritten with some custom nixos location. But maybe I'm being a bit too pedantic here).

**Comment by bobismijnnaam** [comment] 2020-08-24 08:01
Previously the `userControntrolled` flag did not do anything (that is: it fell back on `/etc/wpa_supplicant.conf`) _unless_ you had any networks defined. And since you manage your networks in `wpa_supplicant.conf`, I think in your case the flag did not influence your setup (please correct me if I'm wrong). Since the flag did not do anything previously, maybe you could disable the flag (i.e. remove it from your config)? 

If you do want the configuration that `userControlled` turns on maybe you can put the configuration that nixos generates in your `wpa_supplicant.conf` yourself? It's not very long, and since you manage the config file yourself already I think this might be the best solution. Nixos generates the following two lines for `wpa_supplicant.conf` when `userControlled` is turned on:

```nix
''
  ctrl_interface=DIR=/run/wpa_supplicant GROUP=${cfg.userControlled.group}
  update_config=1
''
```

So you only have to fill in the group (which is wheel by default, but I changed it to network in my setup). This can be pasted just above your networks if I understand correctly.

Finally, if those two options are not possible for you, and if we want to support your use case, we can revert the changes from 71ea6a9a41f1340e6821812f8b7e331072dbd020. However, I think that's undesirable, as previously the configuration was broken. 

(Unfortunately `wpa_supplicant` does not support multiple configurations, or merging configurations, which would also cleanly solve this problem. That's a feature I'd like to have because that would allow separting your wifi passwords and your wifi config, which is (as far as I can tell) impossible now.)

**Comment by bendlas** [comment] 2020-08-24 08:53
I did disable the config adding back the lines, if necessary, works for me.

Thanks for verifying, that the config files can't easily be included. That sucks. Can we find a way to warn the user, though, if there's a `wpa_supplicant.conf`, that we're ignoring? Maybe a wrapper to `wpa_supplicant`, that would check for its presence and print something to stderr?

**Comment by bobismijnnaam** [comment] 2020-08-24 10:08
I think the idiomatic nix solution would be to include the information in `networking.supplicant.<name>.extraConf`. However, if one wants to avoid having your wifi passwords end up in `/nix/store` (which I'm assuming is what you want), using `extraConf` is not an option. So we're stuck until nix gets proper secrets/passwords support.

Adding some machinery somewhere to check for an existing file (e.g. at runtime or at `nixos-rebuild` time) is probably feasible but I'm not sure if it fits the way things are usually done in nix. (If your config is correct, the resulting build of the OS also should be, independent of any pre-existing files I'd say. But I might be wrong about this line of reasoning) I'm not very well acquainted with nix so I'm not sure what the right way forward is currently for your problem @bendlas.

**Comment by bendlas** [comment] 2020-08-25 09:33
> So we're stuck until nix gets proper secrets/passwords support.

Exactly

> Adding some machinery somewhere to check for an existing file (e.g. at runtime or at nixos-rebuild time)

If we were to do that, then runtime, obviously. Such a hand-maintained file is mutable state, hence has no bearing on the build.

> If your config is correct, the resulting build of the OS also should be

I'm not talking about making this an error, mind you. I'd just prefer being able to find the source of this error in the logs, without having to debug the whole networking stack.

I think, just dropping a warning when `wpa_supplicant` starts with a generated config, while `/etc/wpa_supplicant.conf` is also present, could potentially benefit many users.

**Comment by bobismijnnaam** [comment] 2020-08-25 09:40
That sounds like a good enhancement.

**Comment by rnhmjoj** [comment] 2021-08-16 14:09
Summing up, we now:
1. warn if `/etc/wpa_supplicant.conf` is present but unsued (https://github.com/NixOS/nixpkgs/pull/96263)
2. allow mixed declarative and imperative configuration (https://github.com/NixOS/nixpkgs/pull/113716)
3. write the configuration if the control socket is enabled (https://github.com/NixOS/nixpkgs/pull/93813)

The only thing left is enabling the control socket in the NixOS installer, for which I opened: https://github.com/NixOS/nixpkgs/pull/134030.

**Comment by rnhmjoj** [comment] 2021-08-17 10:38
#134030 is merged. Closing.

**Closed by rnhmjoj** 2021-08-17 10:38 UTC
