### ISSUE TITLE
pkgsStatic.xxx with Rust requires to recompile rustc

### ISSUE THREAD

**Issue by markpash** [NixOS/nixpkgs#207435] opened 2022-12-23 16:58 UTC
### Describe the bug
When attempting to statically build a rust package, it needs to compile `rustc` first and doesn't get it from the cache.

### Steps To Reproduce
`nix build nixpkgs#pkgsStatic.bandwhich`

### Expected behavior
It would be expected to fetch the `rustc` from the cache, and use that to build the rust-based package.

**Comment by wucke13** [comment] 2023-02-23 22:48
This is particular annoying, because even when using `pkgsStatic.makeRustPlatform` together with fenix to get a pre-built `rustc` and `cargo`, then instead __both__ gcc and llvm are built against musl (which isn't available in the cache as well). If anyone knows how to build rust stuff with `pkgsStatic` without compiling at least on huge compiler from scratch, please enlighten us :smile:

**Comment by Aleksanaa** [comment] 2023-04-18 23:54
Same here... This solution is nearly unusable

**Comment by hmenke** [comment] 2023-08-03 15:29
Pinging Rust maintainers: @NixOS/rust

**Comment by winterqt** [comment] 2023-08-03 23:56
FWIW, in the meantime, something like https://github.com/DeterminateSystems/nix-installer/blob/c31535a824ec7a410d907c537d39910f1fdce37d/flake.nix#L118 seems to work well in terms of not taking a long time.

This looks like a proper version of what @wucke13 suggested above. (The issue is that you shouldn't have used `pkgsstatic` at all, and just rely on the prebuilt libstd etc targets that Fenix provides.)

**Comment by infinisil** [comment] 2023-09-15 00:02
This does not appear to be fixed by #176694, even after its merge:
```
$ curl -L https://channels.nixos.org/nixpkgs-unstable/git-revision
1697b7d480449b01111e352021f46e5879e47643

$ nix-build channel:nixpkgs-unstable -A bandwhich
this path will be fetched (1.07 MiB download, 4.14 MiB unpacked):
  /nix/store/x35bjv92vj9q7fcb742fgmhqdbln93na-bandwhich-0.20.0
copying path '/nix/store/x35bjv92vj9q7fcb742fgmhqdbln93na-bandwhich-0.20.0' from 'https://cache.nixos.org'...
/nix/store/x35bjv92vj9q7fcb742fgmhqdbln93na-bandwhich-0.20.0

$ nix-build channel:nixpkgs-unstable -A pkgsStatic.bandwhich
these 6 derivations will be built:
  /nix/store/8md7bqsyxi508advdpn0dv5img29ghmd-x86_64-unknown-linux-musl-rustc-1.72.0.drv
  /nix/store/mp0sjq483ikrs8z73i39j4pn2jh320bz-x86_64-unknown-linux-musl-cargo-1.72.0.drv
  /nix/store/2dydbpld31wz2c5av83wyap6mpniaqwx-cargo-check-hook.sh.drv
  /nix/store/5pbkliy0whw2gwz6swq784i4ydpds2ca-cargo-build-hook.sh.drv
  /nix/store/bcjzlxis4ccrzagahqqmz2rxlvr4528d-auditable-x86_64-unknown-linux-musl-cargo-1.72.0.drv
  /nix/store/jm788j83hijgj38an339frk154fhrxwx-bandwhich-static-x86_64-unknown-linux-musl-0.20.0.drv
```

Even though `bandwhich` is cached in the normal package set, building `pkgsStatic.bandwhich` requires building rustc and cargo.

**Comment by infinisil** [comment] 2023-09-28 00:16
A relevant comment was left by @yu-re-ka here: https://github.com/NixOS/nixpkgs/pull/176694#issuecomment-1720737310

> That a rustc derivation appears in the list is to be expected. Within that derivation is should only build the std lib though.

Are you saying that this issue here cannot be fixed? There really is no way to statically compile Rust with the same compiler build as for dynamic compilation?

**Comment by YellowOnion** [comment] 2023-09-28 04:59
Missing secondary outputs will trigger a recompile and something I've stumbled across many times, especially with nix copy / nix-copy-closure. 

I figured out yesterday that ` nix-store --query --outputs` will list all outputs and then you can check which paths are missing.

This might explain what is happening here.

**Comment by infinisil** [comment] 2023-09-28 15:40
Also asked this [on Matrix](https://matrix.to/#/!kjdutkOsheZdjqYmqp:nixos.org/$FHoUKR4OhsWlV_EwT7N6duZhPN7VU_58RS45R7HankE?via=nixos.org&via=matrix.org&via=nixos.dev) where @RaitoBezarius was able to give some pointers.

**Comment by yu-re-ka** [comment] 2023-09-28 15:42
This _is_ fixed. The rust compiler is not rebuilt for cross targets. There is no issue.

**Comment by yu-re-ka** [comment] 2023-09-28 16:10
On master:

```
$ git checkout nixos/master

$ nix build -f . pkgsStatic.buildPackages.rustc
fetching rustc-1.72.0
building x86_64-unknown-linux-musl-rustc-1.72.0
[...]
Building bootstrap
Building crtbegin.o and crtend.o for x86_64-unknown-linux-musl
Building libunwind.a for x86_64-unknown-linux-musl
Building stage1 library artifacts {std} (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-musl)
buildPhase completed in **45 seconds**

$
```

On the other hand, when I revert https://github.com/NixOS/nixpkgs/pull/176694:
```
$ git checkout nixos/master
$ git revert --no-g 9ee10432a4b7

$ nix build -f . pkgsStatic.buildPackages.rustc
fetching rustc-bootstrap-1.71.1
building x86_64-unknown-linux-musl-rustc-1.72.0
[...]
Building bootstrap
Building stage0 library artifacts (x86_64-unknown-linux-gnu)
Building compiler artifacts (stage0 -> stage1, x86_64-unknown-linux-gnu)
Building stage1 library artifacts (x86_64-unknown-linux-gnu)
Building compiler artifacts (stage1 -> stage2, x86_64-unknown-linux-gnu)
Building crtbegin.o and crtend.o for x86_64-unknown-linux-musl
Building libunwind.a for x86_64-unknown-linux-musl
Building stage2 library artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-musl)
Building stage2 tool rust-analyzer-proc-macro-srv (x86_64-unknown-linux-gnu)
Building tool rustdoc (stage1 -> stage2, x86_64-unknown-linux-gnu)
Building bootstrap
Building stage0 tool unstable-book-gen (x86_64-unknown-linux-gnu)
Building stage0 tool rustbook (x86_64-unknown-linux-gnu)
Building stage0 library artifacts (x86_64-unknown-linux-gnu)
Building compiler artifacts (stage0 -> stage1, x86_64-unknown-linux-gnu)
Building stage1 library artifacts (x86_64-unknown-linux-gnu)
Building compiler artifacts (stage1 -> stage2, x86_64-unknown-linux-gnu)
Building tool rustdoc (stage1 -> stage2, x86_64-unknown-linux-gnu)
Building tool error_index_generator (stage1 -> stage2, x86_64-unknown-linux-gnu)
Building stage0 tool lint-docs (x86_64-unknown-linux-gnu)
buildPhase completed in **5 minutes 20 seconds**


$
```

I'm of course interested in optimizing it further, by sharing all the small rust programs that bootstrap.py builds (`` and ``)

**Comment by RaitoBezarius** [comment] 2023-09-28 16:16
Oh that's super awesome, thank you so much @yu-re-ka !

**Comment by infinisil** [comment] 2023-09-28 18:00
Ah I see, so just because it's also called `rustc` doesn't mean it has to compile rustc, neat!

**Closed by infinisil** 2023-09-28 18:00 UTC
Labels: 0.kind: bug, 6.topic: static
