### ISSUE TITLE
`documentation.nixos.includeAllModules = true` causes infinite recursion

### ISSUE THREAD

**Issue by pinpox** [NixOS/nixpkgs#181009] opened 2022-07-10 18:36 UTC
### Describe the bug

`documentation.nixos.includeAllModules = true` causes infinite recursion with specific modules. Specifically importing [this module](https://github.com/pinpox/lollypops/blob/706dc38ccf39b7cbff91977034ecbc1035d213d8/module.nix) and setting the above option results in an infinite recursion. The full stack trace is here: https://gist.github.com/pinpox/edb874416067048a044eae1656207cca

With the kind help of @roberth over on matrix we've narrowed it down to a problem of the manual build when using `specialArgs`:

>  the manual build doesn't include the custom specialArgs

I have tried working around it by setting `buildDocsInSandbox = true` in the module (`false` doesn't work either) and by adding a `defaultText` to each option of the module.

Quoting:

> I think this affects any config that imports from a specialArgs module argument
> the problematic specialArgs is here https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/misc/documentation.nix#L44
> we ought to wire that up somehow. Probably best to add specialArgs as _module.specialArgs in the module system

@roberth let me know if I forgot any useful information. Also pinging @pennae as he might be able to help with this.

### Steps To Reproduce
Steps to reproduce the behaviour:
1. set `documentation.nixos.includeAllModules = true`
2. Import lollypops.nixosModules.lollypops as shown [here](https://github.com/pinpox/nixos/blob/go-task/modules/lollypops-common/default.nix#L4)
3. `nixos-rebuild switch`

### Expected behaviour
Documentation is build without errors

### Additional context
- https://gist.github.com/pinpox/edb874416067048a044eae1656207cca
- https://github.com/pinpox/nixos/blob/go-task/modules/lollypops-common/default.nix#L4
- https://github.com/pinpox/lollypops/blob/706dc38ccf39b7cbff91977034ecbc1035d213d8/module.nix

### Notify maintainers

@roberth @pennae @alyssais @kraem 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.51, NixOS, 22.11 (Raccoon), 22.11.20220708.b39924f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `""`
 - channels(pinpox): `"home-manager"`
 - nixpkgs: `/nix/store/02pg1kr963gyk2qs3m9hg1lvfgvvhmjy-source`
```

**Comment by pennae** [comment] 2022-07-12 04:53
can reproduce the error from pinpox/lollypops#2 (no `hostName`), adding a defaultText to the option there fixes that. the problem there seems to be that `hostName` is defined in a lazy-docs module but all user modules are eager-docs, so this default can't be evaluated because the module `hostName` is defined in won't be loaded when the dependent default is evaluated. the error is a compounding of multiple factors:

* `buildDocsInSandbox` is ignored for user modules
* user modules can reference lazy-docs attributes in their docs without having to provide a `defaultText` or similar
* we can't reliably add error detection for these cases without undoing much of the savings the split build provides

setting `documentation.nixos.options.splitBuild = false` in addition to `documentation.nixos.includeAllModules = true` makes the `hostName` error go away.

we were able to reproduce the infinite recursion by setting `includeAllModules` on `kartoffel`. in that case it really is a problem with using module arguments for things they aren't very good at, the way around that would (in this special case!) be to add the `restic-exporter` import to the unconditional import list in `flake.nix`

> Also pinging @pennae as he might be able to help with this.

they

**Comment by pinpox** [comment] 2022-07-12 08:23
Thanks for the reply! 

> can reproduce the error from [pinpox/lollypops#2](https://github.com/pinpox/lollypops/issues/2) (no `hostName`), adding a defaultText to the option there fixes that.

I'm still not able to reproduce the `hostName` error when all hosts in `nixosConfigurations` have `networking.hostName` set. I created a [minimal flake](https://gist.github.com/pinpox/2fba76132c888b0ef5ce2d8763aa4bfb) example to test this, but I don't know how to run `nixos-rebuild` without deploying it on my notebook. How did you reproduce the error in the `kartoffel` configuration?

> in that case it really is a problem with using module arguments for things they aren't very good at,

Can you elaborate on what you mean by that? Is passing flake inputs to modules not intended, if so what is generally the best practice access the flake inputs in modules? 

> > Also pinging @pennae as he might be able to help with this.
> 
> they

Sorry, apologies.

**Comment by pennae** [comment] 2022-07-12 08:52
> I'm still not able to reproduce the hostName error

added a comment to the gist with a config that does reproduce.

> How did you reproduce the error in the kartoffel configuration?

added `documentation.nixos.includeAllModules = true` to `kartoffel/configuration.nix` and ran `nix eval --raw .#nixosConfigurations.kartoffel.config.system.build.toplevel`

> Can you elaborate on what you mean by that?

in your case you are passing a module in through `specialArgs`, but there's a circular dependency if you fully evaluate `options` because each module argument can be sourced *either* from `specialArgs` *or* from `_module.args`. once you start strictly evaluating this construct you get a circular dependency, which breaks stuff. in the normal system build that's not a problem because it's largely not strict, but the docs build is strict in large parts of the `options` tree.

not really sure what a better way to do this is though, except not doing it. modules should all have an `enable` option that removes their entire configuration unless set, once you've got that you can import all the modules all the time (like nixos itself does) without needing specialArgs at all.

**Comment by pinpox** [comment] 2022-07-12 09:38
Thanks for the explanation, I was able to reproduce it. The `lollypops` module has no `enable` option because it has only very minimal config and is only there to define options, this is [all it does](https://github.com/pinpox/lollypops/blob/main/module.nix#L108-L110)
```nix
  config = {
     environment.systemPackages = with pkgs; [ rsync ];
  };
```
I think putting that behind an enable option would not make much difference? 

The infinite recursion still persists e.g. on kartoffel. I added: `restic-exporter.nixosModules.default` below [this line](https://github.com/pinpox/nixos/blob/main/flake.nix#L154) and removed the import in all other places.

I don't want to bother you too much, but don't really know where else to ask and think this might be helpful for other users using flake with modules: 
Since there is a `nixosModules."<name>" = { config }: { options = {}; config = {}; }; ` output in the flake [output schema](https://nixos.wiki/wiki/Flakes#Output_schema) spec, how are modules defined here supposed to be used? I don't mind rewriting parts of my config or of the lollypops module to do things The Correct Way™ but would like to make module separate from my system configuration so it can be imported and reused as a separate problem and don't know how to do that without using specialArgs or without creating a circular dependency. Just relying non-strict evaluation, hoping parts of the config won't be evaluated sound dangerous.

If you have any pointers on how to refactor this or tips on how to organise it better, that would be awesome.

Lastly, is there any way to just exclude the lollypops module from the documentation to avoid conflicts? While not a real solution it would at least work around the problem for now, but I suspect this problem might occur in other modules in the future with more people using imported flake modules.

**Comment by pennae** [comment] 2022-07-12 09:54
> I think putting that behind an enable option would not make much difference?

for this module, yes. what you've got there are mostly non-local effects due to interdependencies between modules, and those will have to be resolved with eg `defaultText`. it's okay to import that when needed since it doesn't use specialArgs

> The infinite recursion still persists e.g. on kartoffel. I added: restic-exporter.nixosModules.default below [this line](https://github.com/pinpox/nixos/blob/main/flake.nix#L154) and removed the import in all other places.

that's what we did and it eval'd fine. :thinking: 

> how are modules defined here supposed to be used?

if every module has an `enable` option you don't *need* `specialArgs` for them at all, you can list them directly in the `nixosSystem` call without importing them. they'll be available but not enabled, just like the myriad of nixos modules that are always present but disabled—you only get into trouble once you have conflicting option names, and in that case you could replace your `configuration.nix` with a function that instead creates (at least some of) the arguments to `nixosSystem`.

> Lastly, is there any way to just exclude the lollypops module from the documentation to avoid conflicts?

not really. we probably shouldn't add that facility either because it'd just be papering over a problem rather than addressing the root cause.

**Comment by pinpox** [comment] 2022-07-12 10:25
> > The infinite recursion still persists e.g. on kartoffel. I added: restic-exporter.nixosModules.default below [this line](https://github.com/pinpox/nixos/blob/main/flake.nix#L154) and removed the import in all other places.
> 
> that's what we did and it eval'd fine. 

I pushed to a separate branch with the changes so we can ben 100% sure to run the same code 
https://github.com/pinpox/nixos/tree/test-recursion

```
✦ ~/code/github.com/pinpox/nixos test-recursion
❯ nix eval --raw '.#nixosConfigurations.kartoffel.config.system.build.toplevel'
error: infinite recursion encountered

       at /nix/store/a885zpv9ys2p2x7qnzqvxlsy321mclip-source/lib/modules.nix:491:28:

          490|         builtins.addErrorContext (context name)
          491|           (args.${name} or config._module.args.${name})
             |                            ^
          492|       ) (lib.functionArgs f);
(use '--show-trace' to show detailed location information)
```

**Comment by roberth** [comment] 2022-07-12 10:48
@pennae

> in your case you are passing a module in through `specialArgs`, but there's a circular dependency if you fully evaluate `options` because each module argument can be sourced _either_ from `specialArgs` _or_ from `_module.args`.

`specialArgs` takes priority and the module system takes care not to depend on `attrNames _module.args`, so that `imports` resolution is lazy in `_module.args`, as long as all module arguments required by the modules themselves for `imports` resolution are available in `specialArgs`.

Corollarily, the circular dependency only occurs when `specialArgs` is incomplete.

**Comment by pennae** [comment] 2022-07-12 10:53
> Corollarily, the circular dependency only occurs when specialArgs is incomplete.

which is exactly what happens here because `specialArgs` from the documentation-requesting instantiation is not passed to the documentation-generating instantiation. right?

**Comment by roberth** [comment] 2022-07-12 12:38
I think you need something like this https://github.com/NixOS/nixpkgs/pull/181222

**Comment by pinpox** [comment] 2022-07-12 13:18
> I think you need something like this #181222

Sorry, but I don't understand. Where would I put that?

**Comment by roberth** [comment] 2022-07-12 16:58
It's a fix for nixpkgs itself. You could temporarily reference its branch in your flake if you'd like to try it. Something like `inputs.nixpkgs.url = "github:hercules-ci/nixpkgs/module-specialArgs";`

**Comment by pinpox** [comment] 2022-07-13 08:13
> You could temporarily reference its branch in your flake if you'd like to try it
I can confirm this fixes the recursion for me! :tada: 

Just changed the input in my system configuration and followed the `nixpkgs` input for the lollypops module:
```nix
    nixpkgs.url = "github:hercules-ci/nixpkgs/module-specialArgs";
    lollypops = {
      url = "github:pinpox/lollypops";
      inputs = {
        nixpkgs.follows = "nixpkgs";
        utils.follows = "flake-utils";
      };
    };
```
I saw the PR is still a Draft, is there something preventing to merge this?

**Closed** 2022-08-08 09:53 UTC
Labels: 0.kind: bug, 6.topic: nixos
