### ISSUE TITLE
Cannot simultaneously install Python3 packages cairocffi and bokeh

### ISSUE THREAD

**Issue by alexeymuranov** [NixOS/nixpkgs#47285] opened 2018-09-24 17:59 UTC
## Issue description

Since upgrading NixOS to 18.09, I cannot install my Python 3 environment if I include both `cairocffi` and `bokeh` packages.  I can install each of them individually or with other packages.

### Steps to reproduce

If I put this in my `~/.nixpkgs/config.nix`:
```nix
{
  packageOverrides = pkgs: {
    myPythonEnv = pkgs.python36.withPackages (
      pythonPkgs: [
        pythonPkgs.cairocffi
        pythonPkgs.bokeh
      ]
    );
  };
}
```
and try to install `myPythonEnv`, I get:
```ShellSession
$ nix-env -iA nixos.myPythonEnv
replacing old 'python3-3.6.6-env'
installing 'python3-3.6.6-env'
these derivations will be built:
  /nix/store/7qxarg5i94l7k1gs4gjbcmcld2wvwack-python3-3.6.6-env.drv
building '/nix/store/7qxarg5i94l7k1gs4gjbcmcld2wvwack-python3-3.6.6-env.drv'...
collision between `/nix/store/2l451q4974w431hmyz8wxfp984vnlvcz-python3.6-Bottleneck-1.2.1/lib/python3.6/site-packages/.pytest_cache/v/cache/nodeids' and `/nix/store/89p096cqhrxwhbd70mmc4mb6mhkjbn4n-python3.6-cairocffi-0.9.0/lib/python3.6/site-packages/.pytest_cache/v/cache/nodeids'
builder for '/nix/store/7qxarg5i94l7k1gs4gjbcmcld2wvwack-python3-3.6.6-env.drv' failed with exit code 25
error: build of '/nix/store/7qxarg5i94l7k1gs4gjbcmcld2wvwack-python3-3.6.6-env.drv' failed
```

## Technical details

```ShellSession
$  nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/kic17fw8wil74k04kzh3dha43izrr9j3-bash-interactive-4.4-p23-dev
copying path '/nix/store/kic17fw8wil74k04kzh3dha43izrr9j3-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.71, NixOS, 18.09beta521.e4966591ef6 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(alexey): `"nixos-17.03-17.03.1949.78e9665b48f, nixos-17.09-17.09.3238.e984f9e48e1"`
 - channels(root): `"nixos-18.09beta521.e4966591ef6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by matthewbauer** [comment] 2018-09-24 18:53
Looks like https://github.com/NixOS/nixpkgs/issues/40273

**Comment by FRidh** [comment] 2018-10-02 16:17
Closing as duplicate of #40273. The fix is stuck in staging, and should also go to 18.09.

**Closed by FRidh** 2018-10-02 16:17 UTC
