### ISSUE TITLE
Parsec

### ISSUE THREAD

**Issue by shyim** [NixOS/nixpkgs#95160] opened 2020-08-11 10:03 UTC
**Project description**
Allows controlling on remote computers with very low latency  

**Metadata**

* homepage URL: https://parsecgaming.com/downloads/
* source URL: Is closed source
* license: mit, bsd, gpl2+ , ...
* platforms: linux, darwin

**Comment by IvarWithoutBones** [comment] 2020-08-16 13:19
I have a WIP derivation for this, however `parsecd` seems to fail with exit code 2.
```nix
{ stdenv
, fetchurl
, dpkg
, autoPatchelfHook
, libglvnd
, libX11
}:

stdenv.mkDerivation rec {
  pname = "parsec";
  version = "1.0"; # Can't seem to find versioning upstream?

  src = fetchurl {
    url = "https://builds.parsecgaming.com/package/parsec-linux.deb"; # Can't seem to find a link to a specific version, hopefully this wont change invalidating the derivation.
    sha256 = "1hfdzjd8qiksv336m4s4ban004vhv00cv2j461gc6zrp37s0fwhc";
  };

  unpackPhase = "dpkg-deb -x ${src} .";

  nativeBuildInputs = [ dpkg autoPatchelfHook ];
  buildInputs = [ stdenv.cc.cc.lib libglvnd libX11 ];

  installPhase = ''
    mkdir $out
    cp -r ./usr/* $out
  '';

  meta = with stdenv.lib; {
    homepage = "https://parsecgaming.com/";
    description = "Remote streaming service client";
    license = licenses.unfree;
    maintainers = with maintainers; [ ivar ];
    platforms = platforms.linux;
  };
}
```

**Comment by itshaydendev** [comment] 2020-08-17 10:47
@IvarWithoutBones Maybe a missing library?

**Comment by IvarWithoutBones** [comment] 2020-08-17 15:11
`ldd` shows me it's not linking to any more libraries, not sure what the problem is.

**Comment by RaghavSood** [comment] 2020-08-18 09:14
Was also looking for this, it does seem to exist in nur: https://github.com/clefru/nur-packages/blob/master/pkgs/parsecgaming/default.nix

**Comment by shyim** [comment] 2021-03-09 11:04
Got anyone running it? The nur package seems broken. :disappointed:

**Comment by djmaze** [comment] 2021-03-09 19:13
Yes, it is broken, but I got it running using the workaround described at https://github.com/clefru/nur-packages/issues/2#issuecomment-742100611. Not an optimal solution though.

**Comment by shyim** [comment] 2021-03-09 19:39
That didnt worked for me. I built an docker setup for now as workaround https://github.com/shyim/docker-parsec 🙈

**Comment by lucasew** [comment] 2022-03-27 12:38
I've just take a quick look on the deb files and in `usr/share/parsec/skel` there is a .so file

This could be the missing piece to make it work.

**Comment by CerealKiller-John** [comment] 2023-02-20 16:00
Has anyone been successful in getting this to work? I have tried multiple different ways to get it working and haven't been successful yet.

**Comment by qwbarch** [comment] 2023-02-20 22:38
> Has anyone been successful in getting this to work? I have tried multiple different ways to get it working and haven't been successful yet.

I haven't used it in months now, but I was able to get it to work by installing ``parsec-bin`` from the unstable packages

**Comment by abathur** [comment] 2023-05-24 05:43
Closing since it seems like the package request was satisfied by https://github.com/NixOS/nixpkgs/pull/194656

If there are issues with the package, opening a new issue that clearly describes them may help get them resolved.

**Closed by abathur** 2023-05-24 05:43 UTC
Labels: 0.kind: packaging request
