### ISSUE TITLE
gomuks is broken

### ISSUE THREAD

**Issue by pmiddend** [NixOS/nixpkgs#53114] opened 2018-12-31 11:02 UTC
## Issue description

```
 __________
< Oh noes! >
 ‾‾‾\‾‾‾‾‾‾
     \   ^__^
      \  (XX)\_______
         (__)\       )\/\
          U  ||----W |
             ||     ||

A fatal error has occurred.

The stack trace has been saved to /tmp/gomuks-panic-2018-12-31--11-59-52.txt

You can file an issue at https://github.com/tulir/gomuks/issues.
Please provide the contents of that file when filing an issue.
```

### Steps to reproduce

`nix-shell -p gomuks --run gomuks`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.12, NixOS, 19.03pre164581.ae002fe44e9 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(philipp): `""`
 - channels(root): `"nixos-19.03pre164581.ae002fe44e9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by lasers** [comment] 2021-01-30 06:33
Please revisit this again. With your steps to reproduce, I got a ncurse dialog box to `Log in to Matrix`.

**Comment by SuperSandro2000** [comment] 2021-01-31 17:45
Closing because the issue is fixed according to lasers.

**Closed by SuperSandro2000** 2021-01-31 17:45 UTC
