### ISSUE TITLE
plasma5 activation scripts fails with unset/null XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by piotr-szegda** [NixOS/nixpkgs#80713] opened 2020-02-21 11:00 UTC
**Describe the bug**
After upgrade to 20.03 nixos-activation.service don't start .

Error log:
● nixos-activation.service - Run user-specific NixOS activation
   Loaded: loaded (/nix/store/jcv2nvwkdc4hlhfx2dcchw3xgnmgyk8n-unit-nixos-activation.service/nixos-activation.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-02-21 11:57:14 CET; 8s ago
  Process: 11052 ExecStart=/nix/store/6hls8gx0c7prqf6gc2s1q9kp5w57jnb4-unit-script-nixos-activation-start (code=exited, status=1/FAILURE)
 Main PID: 11052 (code=exited, status=1/FAILURE)

lut 21 11:57:14 nixos systemd[1389]: Starting Run user-specific NixOS activation...
lut 21 11:57:14 nixos 6hls8gx0c7prqf6gc2s1q9kp5w57jnb4-unit-script-nixos-activation-start[11052]: /nix/store/6hls8gx0c7prqf6gc2s1q9kp5w57jnb4-unit-script-nixos-activation-start: line 22: XDG_CONFIG_HOME: parameter null or not set
lut 21 11:57:14 nixos systemd[1389]: nixos-activation.service: Main process exited, code=exited, status=1/FAILURE
lut 21 11:57:14 nixos systemd[1389]: nixos-activation.service: Failed with result 'exit-code'.
lut 21 11:57:14 nixos systemd[1389]: Failed to start Run user-specific NixOS activation.

I am using home manager but empty profile without home manager is also broken. After switch channel to 19.09 everything is OK.

**To Reproduce**
1. Upgrade to 20.03

**Additional context**
I am using KDE. Adding XDG_CONFIG_HOME to this file does not solve the problem completely. Service start but for ex. flatpak app not.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.19, NixOS, 20.03beta-475.71be729a58e (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03beta-475.71be729a58e"`
 - channels(piotrek): `"home-manager, nixos-20.03pre212208.8130f3c1c2b, nixpkgs-20.03pre212208.8130f3c1c2b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by AtkinsChang** [comment] 2020-02-21 16:16
caused by d5757a8880108ca267bdfe32e42a069fe0a8cf15

**Comment by Elyhaka** [comment] 2020-02-25 21:27
I had this issue too, and it can be fixed by enabling this :

```
services = {
  dbus.socketActivated = true;
  xserver.startDbusSession = false;
}
```

I am not really sure why, this fix come from another issue that is plasma related.

**Comment by worldofpeace** [comment] 2020-02-26 01:57
cc @ttuegel

**Comment by piotr-szegda** [comment] 2020-02-26 06:05
@Elyhaka: Yes, it's solve error related to XDG_CONFIG_HOME but flatpak app still fail to launch. Starting KeePassXC result in error: The name org.freedesktop.Accounts was not provided by any .service files

**Comment by mdedetrich** [comment] 2020-02-26 09:58
@Elyhaka As far as I understand this is actually a workaround and not a real solution. iirc the suggested workaround was for a now fixed problem where plasma wouldn't start due to a hardcoded limit on env vars

**Comment by Elyhaka** [comment] 2020-02-26 10:35
It is indeed a workaround, sorry for the bad phrasing. I know this is a workaround for another issue that has been merged, but it has fixed the issue for me.

**Closed** 2020-02-27 17:08 UTC
Labels: 0.kind: bug, 0.kind: regression, 1.severity: blocker, 6.topic: nixos, 6.topic: qt/kde
