### ISSUE TITLE
test for nix-env regressions

### ISSUE THREAD

**Issue by lolbinarycat** [NixOS/nixpkgs#297629] opened 2024-03-21 05:54 UTC
nix-env has a reputation for being unreliable, but i would contend that this is not the fault of nix-env, but instead is the result of three factors:
1. there are a few pieces of metadata that are vitaly important to the operation of nix-env, but almost entirely irrelevant everywhere else
2. there is no automated testing done on any of this data
3. there is very little manual testing of nix-env

point 2 is definitely something that can be addressed.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-03-21 11:41
What do people actually use `nix-env` for that can't be handled better by some other commands?

PS some other reasons why `nix-env` is terrible: https://web.archive.org/web/20240310235021/https://stop-using-nix-env.privatevoid.net/

**Comment by lolbinarycat** [comment] 2024-03-22 15:36
advantages of nix-env:
* interface more familiar to traditional package manager users.
* allows upgrading individual packages (useful for users with slow internet connections)
* allows easy installation of local derivations (useful for installing packages not yet included in any package sets)

until `nix profile` is considered stable, we should support `nix-env`.

there's actually not that much surface area to test, it's basically just changes to `meta.priority` and derivation names.

> PS some other reasons why nix-env is terrible: https://web.archive.org/web/20240310235021/https://stop-using-nix-env.privatevoid.net/

several of those

**Comment by SuperSandro2000** [comment] 2024-03-23 11:32
nix-env is to be deprecated and not really recommend to be used. I think it is not worthwhile to invest more time into trying to keeps its broken mechanics working especially with the big footguns it has. Also it would hinder innovation and reworks.

> * allows upgrading individual packages (useful for users with slow internet connections)

This is a big footgun as NixOS doesn't guarantee binary combability when doing this and mixing different glib/driver/etc versions often results in strange and byzantine errors. Also this speaks against the NixOS philosophy of having one true source to your configuration.

> allows easy installation of local derivations (useful for installing packages not yet included in any package sets)

It is trivial to do pkgs.callPackage on a downloaded file from a PR and include that in your configuration. 

> there's actually not that much surface area to test, it's basically just changes to meta.priority and derivation names.

pname can change and enforcing them to be stable just for nix-env would hindere so many tasks (like normalizing pnames in python packages but I doubt that with the current structure how pythonPackages's pname are generated even works good with nix-env) and the correct stable interface nix has is the attr for which we also create aliases when changing. Tools that use pname are broken by design and should be fixed instead.

**Closed by SuperSandro2000** 2024-03-23 11:32 UTC
Labels: 0.kind: bug
