### ISSUE TITLE
`texlive.combined.scheme-full` fails to build due to `clisp` build error

### ISSUE THREAD

**Issue by balacij** [NixOS/nixpkgs#206960] opened 2022-12-20 01:18 UTC
### Steps To Reproduce
1. build `texlive.combined.scheme-full`

### Build log
Important bit
```
base/lisp.run -B . -M base/lispinit.mem -norc -q -i i18n/i18n -i syscalls/posix -i regexp/regexp -i readline/readline -x (saveinitmem "base/lispinit.mem")
;; Loading file /build/clisp-2.49/builddir/i18n/i18n.fas ...
;; Loaded file /build/clisp-2.49/builddir/i18n/i18n.fas
;; Loading file /build/clisp-2.49/builddir/syscalls/posix.fas ...
;; Loaded file /build/clisp-2.49/builddir/syscalls/posix.fas
;; Loading file /build/clisp-2.49/builddir/regexp/regexp.fas ...
;; Loaded file /build/clisp-2.49/builddir/regexp/regexp.fas
;; Loading file /build/clisp-2.49/builddir/readline/readline.fas ...
*** - FFI::FIND-FOREIGN-VARIABLE: foreign variable
      #<FOREIGN-VARIABLE "rl_readline_state" #x00007FFFF7FBC640> does not have
      the required size or alignment

./clisp-link: failed in /build/clisp-2.49/builddir
make: *** [Makefile:2623: base] Error 1
error: builder for '/nix/store/rbykd92038rp80a71diyxqmbiz4m8f60-clisp-2.49.drv' failed with exit code 2
error: 1 dependencies of derivation '/nix/store/5v7rahkfv6hvc6ikgab8in2h6fwiz915-texlive-xindy.bin-2021.drv' failed to build
building '/nix/store/1qxyxlh4l10d514iwx65s3dm0yggf9bv-enummapset-0.6.0.3.drv'...
error: 1 dependencies of derivation '/nix/store/zfx0nfhqc59s4jz579wdmjx3c9vqbyr0-texlive-combined-full-2021-final.drv' failed to build
```

### Notify maintainers
@7c6f434c (raskin)

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 ~/my-machines/ main nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.11, NixOS, 23.05 (Stoat), 23.05pre432338.6e51c97f1c8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager, nixos"`
 - channels(user): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by peterhoeg** [comment] 2022-12-20 04:04
duplicate of #206958

**Closed by peterhoeg** 2022-12-20 04:04 UTC
Labels: 0.kind: build failure

**Comment by balacij** [comment] 2022-12-20 04:36
Oh wow, it looks like that was created right as I was writing this ticket! Thank you @peterhoeg!
