### ISSUE TITLE
google-chrome doesn't to build (curls fail)

### ISSUE THREAD

**Issue by ixxie** [NixOS/nixpkgs#27811] opened 2017-07-31 19:36 UTC
## Issue description

google-chrome is refusing to build, seemingly because curl fails on all the mirrors. 

Since the chrome derivation gets its version numbers from the chromium derivation, it could be that chrome's numbering has started to deviate. Otherwise all the mirrors are outdated, which seems unlikely; in any case I haven't managed to find any official archive of old chrome .debs - it seems in fact google is actively suppressing them.

### Steps to reproduce

Try and build google-chrome

## Technical details

* System: NixOS 17.03
* Nix version: 1.11.11
* Nixpkgs version: 17.03.1623.138313fe01
* Sandboxing enabled: No

**Comment by mogorman** [comment] 2017-08-01 16:22
I have been bitten by this a few times. I even went so far as to track down the exact version elsewhere and nix-

**Comment by ocharles** [comment] 2017-08-02 15:27
```
→ nix-env -iA nixos.google-chrome                                                                                                                          ~
installing ‘google-chrome-58.0.3029.110’
these derivations will be built:
  /nix/store/nwqamzdi5skjpp8l58vrzhakyrdw70nb-google-chrome-stable_58.0.3029.110-1_amd64.deb.drv
  /nix/store/y9vv9y8zifin17yz8g3rz21pkhydv5qi-google-chrome-58.0.3029.110.drv
building path(s) ‘/nix/store/sjkrivkdyfxh8l8vr8vqij39sc93kwzz-google-chrome-stable_58.0.3029.110-1_amd64.deb’

trying https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_58.0.3029.110-1_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 

trying http://95.31.35.30/chrome/pool/main/g/google-chrome-stable/google-chrome-stable_58.0.3029.110-1_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 95.31.35.30 port 80: Connection refused

trying http://mirror.pcbeta.com/google/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_58.0.3029.110-1_amd64.deb
Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.
Warning: Transient problem: timeout Will retry in 2 seconds. 2 retries left.
Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.
curl: (6) Couldn't resolve host 'mirror.pcbeta.com'

trying http://repo.fdzh.org/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_58.0.3029.110-1_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   185  100   185    0     0    305      0 --:--:-- --:--:-- --:--:--   352
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 
error: cannot download google-chrome-stable_58.0.3029.110-1_amd64.deb from any mirror
builder for ‘/nix/store/nwqamzdi5skjpp8l58vrzhakyrdw70nb-google-chrome-stable_58.0.3029.110-1_amd64.deb.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/y9vv9y8zifin17yz8g3rz21pkhydv5qi-google-chrome-58.0.3029.110.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/y9vv9y8zifin17yz8g3rz21pkhydv5qi-google-chrome-58.0.3029.110.drv’ failed
```

is the log against https://d3g5gsiof5omrk.cloudfront.net/nixos/17.03/nixos-17.03.1640.5eb78b6997/nixexprs.tar.xz’

**Comment by ocharles** [comment] 2017-08-02 15:28
Appears to be a duplicate of #25880

**Comment by yegortimoshenko** [comment] 2017-12-23 21:48
This has been fixed:

```
$ nix-build ~/Projects/nixpkgs/ -A google-chrome
these derivations will be built:
  /nix/store/xbi3ycqac34rxnp6jq6kfmj2yifa7dmb-google-chrome-stable_63.0.3239.108-1_amd64.deb.drv
  /nix/store/342zp8bigjj6wdvfnbql6bkif935g1xy-google-chrome-63.0.3239.108.drv
these paths will be fetched (0.61 MiB download, 2.99 MiB unpacked):
  /nix/store/kzapd4m2h0bmwmbriw7r4y6cjsb731l2-wget-1.19.2
  /nix/store/r99rp4qp58mmk8wvf2kmahq4rc1ibrng-libidn2-2.0.4
fetching path ‘/nix/store/r99rp4qp58mmk8wvf2kmahq4rc1ibrng-libidn2-2.0.4’...
building path(s) ‘/nix/store/b97wn8drkfvfzff8rc6cnj4b1n6qbl3b-google-chrome-stable_63.0.3239.108-1_amd64.deb’
[...]
/nix/store/znsdg901cvx1gxr5lfkccv037vrhwn6a-google-chrome-63.0.3239.108
```

**Closed by yegortimoshenko** 2017-12-23 21:48 UTC
