### ISSUE TITLE
Heroic Games Launcher & Legendary

### ISSUE THREAD

**Issue by JoshuaFern** [NixOS/nixpkgs#117293] opened 2021-03-22 22:24 UTC
**Project description**
Heroic is an Open Source Game Launcher for Linux. Right now it supports launching game from the Epic Games Store using Legendary, a Linux CLI alternative to launch epic games. Heroic is built with Web Technologies like: TypeScript, React, NodeJS and Electron.

**Metadata**

* Heroic source URL: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher
* Legendary source URL: https://github.com/derrod/legendary
* license: GPL v3
* platforms: Linux

**Comment by OPNA2608** [comment] 2021-03-23 09:09
Duplicate of #109733

**Closed** 2021-03-23 22:57 UTC
Labels: 0.kind: packaging request
