### ISSUE TITLE
using okular as standalone application does not work

### ISSUE THREAD

**Issue by flosse** [NixOS/nixpkgs#15955] opened 2016-06-03 12:25 UTC
## Issue description
Using `okular` as standalone application does not work.

### Steps to reproduce
```
nix-shell --pure -p kde5.okular
okular file.pdf
```
The GUI tells me `Could not open /home/mk/file.pdf` and
```
Could not find mime types:
"inode/directory"
"inode/blockdevice"
"inode/chardevice"
"inode/socket"
"inode/fifo"
"application/x-shellscript"
"application/x-executable"
"application/x-desktop"
```
On the console I get:

```
okular(3903)/kdeui (KIconLoader): Error: standard icon theme "oxygen" not found! 

okular(3903)/kdeui (KIconLoader): Error: standard icon theme "oxygen" not found! 

okular(3903) KPixmapSequence::Private::loadSequence: Invalid pixmap specified. 
okular(3903) KPixmapSequence::Private::loadSequence: Invalid pixmap specified. 
okular(3903) KPixmapSequence::frameSize: No frame loaded 
okular(3903) KPixmapSequence::Private::loadSequence: Invalid pixmap specified. 
okular(3903) KPixmapSequence::frameSize: No frame loaded 
okular(3903) KPixmapSequence::Private::loadSequence: Invalid pixmap specified. 
okular(3903) KPixmapSequence::frameSize: No frame loaded 
okular(3903) KPixmapSequence::Private::loadSequence: Invalid pixmap specified. 
okular(3903) KPixmapSequence::frameSize: No frame loaded 
okular(3903) KPixmapSequence::Private::loadSequence: Invalid pixmap specified. 
okular(3903) KPixmapSequence::frameSize: No frame loaded 
okular(3903) KPixmapSequence::Private::loadSequence: Invalid pixmap specified. 
okular(3903) KPixmapSequence::frameSize: No frame loaded 
okular(3903)/kdecore (trader) KServiceTypeTrader::defaultOffers: KServiceTypeTrader: serviceType  "okular/Generator"  not found 
okular(3903)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
okular(3903)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
okular(3903)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
okular(3903)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
okular(3903)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
okular(3903)/kdecore (trader): KMimeTypeTrader: couldn't find service type "okular/Generator" 
Please ensure that the .desktop file for it is installed; then run kbuildsycoca4. 
okular(3903)/okular (app) Okular::Document::openDocument: No plugin for mimetype '"text/plain"'.
okular(3903)/kdecore (trader): KMimeTypeTrader: couldn't find service type "okular/Generator" 
Please ensure that the .desktop file for it is installed; then run kbuildsycoca4. 
okular(3903)/okular (app) Okular::Document::openDocument: No plugin for mimetype '"text/plain"'.
okular(3903) KMimeTypePrivate::ensureXmlDataLoaded: Missing <comment> field in "text/plain.xml" 
okular(3903): Couldn't start knotify from knotify4.desktop:  "Could not find service 'knotify4.desktop'." 

okular(3903)/kdeui (KNotification) KNotification::slotReceivedIdError: Error while contacting notify daemon "The name org.kde.knotify was not provided by any .service files" 
okular(3903)/kdeui (KNotification) KNotification::slotReceivedIdError: Error while contacting notify daemon "The name org.kde.knotify was not provided by any .service files" 
```

## Technical details

* System: nixos-version: `16.09pre84674.fbde3a7 (Flounder)`
* Nix version: `nix-env (Nix) 1.11.2`
* Nixpkgs version: `16.09pre84674.fbde3a7`

**Comment by ttuegel** [comment] 2016-06-03 12:33
See also, #15498.

**Comment by rasendubi** [comment] 2016-06-03 13:56
Try next workaround (it works for my `kde4.okular`):
```nix
environment.pathToLink = [ "/share" ];
environment.systemPackages = [ pkgs.shared_mime_info ];
```

**Comment by rasendubi** [comment] 2016-09-09 05:58
Closing as duplicate of #14390

**Closed by rasendubi** 2016-09-09 05:58 UTC
Labels: 0.kind: bug
