### ISSUE TITLE
pkgs.mailman has unresolved dependency on urllib3

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#79222] opened 2020-02-04 13:03 UTC
The `pkgs.mailman` binary fails because of missing dependencies:

~~~
$ nix-shell --run "mailman --help" --packages mailman
Traceback (most recent call last):
  File "/nix/store/bp3s0p4as6cp8nlq1q54v1a9rpfl4s44-python3.7-zope.configuration-4.3.1/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/nix/store/bp3s0p4as6cp8nlq1q54v1a9rpfl4s44-python3.7-zope.configuration-4.3.1/lib/python3.7/site-packages/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/nix/store/bp3s0p4as6cp8nlq1q54v1a9rpfl4s44-python3.7-zope.configuration-4.3.1/lib/python3.7/site-packages/zope/configuration/config.py", line 867, in finish
    args = toargs(context, *self.argdata)
  File "/nix/store/bp3s0p4as6cp8nlq1q54v1a9rpfl4s44-python3.7-zope.configuration-4.3.1/lib/python3.7/site-packages/zope/configuration/config.py", line 1686, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/nix/store/bp3s0p4as6cp8nlq1q54v1a9rpfl4s44-python3.7-zope.configuration-4.3.1/lib/python3.7/site-packages/zope/configuration/fields.py", line 268, in fromUnicode
    v = vt.fromUnicode(s)
  File "/nix/store/bp3s0p4as6cp8nlq1q54v1a9rpfl4s44-python3.7-zope.configuration-4.3.1/lib/python3.7/site-packages/zope/configuration/fields.py", line 171, in fromUnicode
    value = self.context.resolve(name)
  File "/nix/store/bp3s0p4as6cp8nlq1q54v1a9rpfl4s44-python3.7-zope.configuration-4.3.1/lib/python3.7/site-packages/zope/configuration/config.py", line 225, in resolve
    __import__(mname)
  File "/nix/store/inbicm302jijynnf5lsqwz1f1hhkwrk1-python3.7-mailman-3.3.0/lib/python3.7/site-packages/mailman/model/autorespond.py", line 25, in <module>
    from mailman.utilities.datetime import today
  File "/nix/store/inbicm302jijynnf5lsqwz1f1hhkwrk1-python3.7-mailman-3.3.0/lib/python3.7/site-packages/mailman/utilities/datetime.py", line 27, in <module>
    from mailman.testing import layers
  File "/nix/store/inbicm302jijynnf5lsqwz1f1hhkwrk1-python3.7-mailman-3.3.0/lib/python3.7/site-packages/mailman/testing/layers.py", line 43, in <module>
    from mailman.testing.helpers import (
  File "/nix/store/inbicm302jijynnf5lsqwz1f1hhkwrk1-python3.7-mailman-3.3.0/lib/python3.7/site-packages/mailman/testing/helpers.py", line 46, in <module>
    from requests import request
  File "/nix/store/hda8sq9vmyz2p5z1zv08vw8k6wiwpjsx-python3.7-requests-2.22.0/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'
~~~

ping @alyssais

**Comment by peti** [comment] 2020-02-04 13:04
Note that this issue prevents the NixOS mailman module from working, too. The mailman.service cannot start up.

**Comment by peti** [comment] 2020-02-04 13:10
I believe a1eacb900e1b705678b2c199cb97baafc9b77f86 is the commit that broke the `mailman` wrapper.

Ping @vcunat

**Comment by peti** [comment] 2020-02-04 13:41
`mailman-web` has the same problem. It depends on `urllib3`, but the required store path in the generated wrapper is wrong.

**Comment by alyssais** [comment] 2020-02-04 15:21
WTF? I already reverted the commit that caused the problem: https://github.com/NixOS/nixpkgs/commit/76af9e8438cce6c503255be09f73d3b54699a254

**Comment by alyssais** [comment] 2020-02-04 15:38
> The `pkgs.mailman` binary fails because of missing dependencies:
>
> ~~~
> $ nix-shell --run "mailman --help" --packages mailman

I cannot reproduce this on e2867af1b24, which was master just before you
pushed your changes, for either mailman or mailman-web.  Perhaps you
tried to cherry-pick mailman things and didn't notice my earlier revert?
I'm going to revert ce6b241, since it doesn't appear to have been
necessary.

**Comment by alyssais** [comment] 2020-02-04 15:52
If you still get this error with the following, please re-open, but I'm
going to close this for now because I suspect it will work (have tested
on multiple systems):

    NIX_PATH= nix-shell --pure -p mailman \
        --run 'cd $(mktemp -d); mailman --help' \
        -I nixpkgs=https://github.com/NixOS/nixpkgs/tarball/master

(the cd is because mailman likes to create a `var' directory in PWD.)

**Closed** 2020-02-04 15:52 UTC
Labels: 0.kind: bug, 2.status: invalid

**Comment by vcunat** [comment] 2020-02-04 16:33
I was only moving a commit to staging due to large rebuild; otherwise I've had nothing to do with it.
