### ISSUE TITLE
Quicktile

### ISSUE THREAD

**Issue by INIGZ** [NixOS/nixpkgs#218288] opened 2023-02-25 17:18 UTC
**Project description**

Keyboard-driven Window Tiling for your existing X11 window manager

**Metadata**

* homepage URL: 
[quicktile-master.zip](https://github.com/NixOS/nixpkgs/files/10831846/quicktile-master.zip)
https://github.com/ssokolow/quicktile
* source URL: https://github.com/ssokolow/quicktile
* license: gpl2+ 
* platforms: linux

**Comment by pinn3** [comment] 2023-02-25 17:54
Duplicate of https://github.com/NixOS/nixpkgs/issues/164551

**Closed** 2023-05-30 18:12 UTC
Labels: 0.kind: packaging request
