### ISSUE TITLE
haskell-updates haskellPackages.lzma hydra build fail

### ISSUE THREAD

**Issue by maralorn** [NixOS/nixpkgs#118996] opened 2021-04-10 09:36 UTC
**Describe the bug**

As seen here: https://hydra.nixos.org/build/141178201/nixlog/1/tail
that package build fails with:

```
Setup: Missing dependency on a foreign library:
* Missing (or bad) header file: lzma.h
* Missing (or bad) C library: lzma
```

I noticed because it’s a dependency of cachix. /cc @domenkozar 

After a bit of searching I think the breaking change was this one: https://github.com/NixOS/nixpkgs/pull/116335 /cc @SuperSandro2000

**Comment by SuperSandro2000** [comment] 2021-04-10 12:06
The PR has zero package rebuilds for Linux so if it is the door cause there is a recurseInto somewhere missing. It broke a few tests because I overlooked that and the darwin rebuilds are caused by a white space changed on a file torched.

**Comment by maralorn** [comment] 2021-04-10 14:31
I don‘t know, why you couldn‘t find this. `haskellPackages` is recursed into. That PR broke multiple of them. 

There were multiple `{ inherit (pkgs) lzma; }` in `pkgs/development/haskell-modules/hackage-packages.nix` at the time this was merged.
The Haskell tooling has now replaced it with `{ lzma = null; }` because it couldn‘t find the system dep.

We now need to put that rename in the cabal2nix aliases. I checked apparently none of the haskell packages dependent on any other removed alias.

One potential exception being "python" and "python3", but did those aliases get removed @SuperSandro2000?

**Comment by SuperSandro2000** [comment] 2021-04-10 14:56
> I don‘t know, why you couldn‘t find this.

Ofborg didn't find it either.

> The Haskell tooling has now replaced it with { lzma = null; } because it couldn‘t find the system dep.

Shouldn't that have triggered a rebuild? Also I would consider this a bug because it should fail loudly if a package vanishes.

> One potential exception being "python" and "python3", but did those aliases get removed @SuperSandro2000?

python might change some time in the future but python3 points to python38 right now and python39 in the future. They are allowed alias in nixpkgs unlike the ones in aliases.nix.

**Comment by domenkozar** [comment] 2021-04-10 18:07
@SuperSandro2000 hey, are you working on a fix?

**Comment by maralorn** [comment] 2021-04-10 18:21
The correct fix would be to find the list with aliases for haskell system dependencies and introduce an alias "lzma -> xz".
Sadly I can‘t find this list right now. I am not even sure if it‘s in nixpkgs or cabal2nix … \cc @cdepillabout @peti.

**Comment by sternenseemann** [comment] 2021-04-10 20:04
Tested locally and can confirm that <https://github.com/NixOS/cabal2nix/pull/488> fixes `haskellPackages.lzma`. Any other aliases that affect us?

**Comment by domenkozar** [comment] 2021-04-10 20:06
Is there a better temporary fix as this will take another week to get merged?

**Comment by sternenseemann** [comment] 2021-04-10 20:09
This is not an issue on `master`, right? So it should be good enough if we regenerate the package set with that patch before the merge on friday, so we don't break cachix which is working currently.

**Comment by SuperSandro2000** [comment] 2021-04-10 20:49
> @SuperSandro2000 hey, are you working on a fix?

Nope. I couldn't find any aliases in cabal2nix and I have no idea about haskell in general.

**Closed** 2021-04-15 09:15 UTC
Labels: 0.kind: bug, 6.topic: haskell
