### ISSUE TITLE
NixOS channels very slow on IPv6 network

### ISSUE THREAD

**Issue by MasterMind2k** [NixOS/nixpkgs#217137] opened 2023-02-19 12:10 UTC
## Issue description

Use of https://channels.nixos.org/nixos-unstable via IPv6 is slow or not working.

### Steps to reproduce
curl -6 https://channels.nixos.org/nixos-unstable

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.11, NixOS, 23.05 (Stoat), 23.05pre453471.e5530aba13c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixos"`
 - channels(<user>): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by matejc** [comment] 2023-02-19 12:21
Please elaborate. Your "Steps to reproduce" work for me.

**Comment by MasterMind2k** [comment] 2023-02-19 12:47
I execute `curl -6 https://channels.nixos.org/nixos-unstable` and it simply times out.

Other IPv6 sites work as expected.

This is the IPv6 address that get resolved:

```
$ host channels.nixos.org
channels.nixos.org is an alias for dualstack.v2.shared.global.fastly.net.
dualstack.v2.shared.global.fastly.net has address 146.75.122.217
dualstack.v2.shared.global.fastly.net has IPv6 address 2a04:4e42:8e::729
```

**Comment by MasterMind2k** [comment] 2023-02-19 12:52
Doing another round of testing with telnet and found out now it works.

It seems the IPv6 server is overloaded?

**Comment by SuperSandro2000** [comment] 2023-02-19 14:56
> It seems the IPv6 server is overloaded?

To my knowledge ipv4 and ipv6 ends up on the same server in the nixos infra, maybe fastly is doing something different but we don't really have insight into that.

Is IPv6 generally working for you? If not are you using a provider like Vodafone which is known for such problems?

**Comment by MasterMind2k** [comment] 2023-02-20 17:25
Generally, IPv6 works. But it could be related to my ISP, since IPv6 goes to same servers.

**Comment by MasterMind2k** [comment] 2023-02-20 17:31
Right now I have issue with NixOS mirrors. Connectivity to google.com works from my side.

Interesting is also that http responds faster than https.

```
$ time curl -6 http://channels.nixos.org/nixos-unstable
curl -6 http://channels.nixos.org/nixos-unstable  0,00s user 0,00s system 7% cpu 0,046 total
$ time curl -6 https://channels.nixos.org/nixos-unstable
curl -6 https://channels.nixos.org/nixos-unstable  0,03s user 0,00s system 0% cpu 10,622 total
```

I executed these commands 18:31:06 CET.

**Comment by matejc** [comment] 2023-02-20 20:36
Although I am in Helsinki, the IPs are resolving San Francisco
```
❯  curl ipinfo.io/2a04:4e42:400::729
{
  "ip": "2a04:4e42:400::729",
  "city": "San Jose",
  "region": "California",
  "country": "US",
  "loc": "37.3394,-121.8950",
  "org": "AS54113 Fastly, Inc.",
  "postal": "95103",
  "timezone": "America/Los_Angeles",
  "readme": "https://ipinfo.io/missingauth"
}
```

While your one resolves to Amsterdam (IP taken from your post with `host` command)
```
❯  curl ipinfo.io/2a04:4e42:8e::729
{
  "ip": "2a04:4e42:8e::729",
  "city": "Amsterdam",
  "region": "North Holland",
  "country": "NL",
  "loc": "52.3740,4.8897",
  "org": "AS54113 Fastly, Inc.",
  "postal": "1012",
  "timezone": "Europe/Amsterdam",
  "readme": "https://ipinfo.io/missingauth"
}
```

```
❯  seq 10 | xargs -I{} zsh -c "time curl -s -6 https://channels.nixos.org/nixos-unstable &" 2>&1 | awk '{sum+=$11}END{print "HTTPS IPv6="sum/NR}'; seq 10 | xargs -I{} zsh -c "time curl -s -4 https://channels.nixos.org/nixos-unstable &" 2>&1 | awk '{sum+=$11}END{print "HTTPS IPv4="sum/NR}'; seq 10 | xargs -I{} zsh -c "time curl -s -6 http://channels.nixos.org/nixos-unstable &" 2>&1 | awk '{sum+=$11}END{print "HTTP IPv6="sum/NR}'; seq 10 | xargs -I{} zsh -c "time curl -s -4 http://channels.nixos.org/nixos-unstable &" 2>&1 | awk '{sum+=$11}END{print "HTTP IPv4="sum/NR}';
HTTPS IPv6=0.2703
HTTPS IPv4=0.2685
HTTP IPv6=0.1357
HTTP IPv4=0.1675
```

I also added `https://channels.nixos.org/nixos-unstable`  to probes from (Amsterdam, Paris, London and Frankfurt) so I get graphs over time, it is probing with IPv6 every 60s since now. Report back when you notice another ocurrance of delay, we can compare.

**Comment by matejc** [comment] 2023-02-20 20:45
You can also do traceroute at the time of delay and post it here (just remember to obfuscate your IP out of it - not very good to post your own IP publicly)

**Comment by MasterMind2k** [comment] 2023-02-21 08:42
Did a traceoute when things work:
```
$ traceroute -n -I -6 channels.nixos.org
traceroute to channels.nixos.org (2a04:4e42:8e::729), 30 hops max, 80 byte packets
 1  <private>  1.457 ms  1.617 ms  1.870 ms
 2  * * *
 3  <private>  5.824 ms  5.822 ms  5.821 ms
 4  <private>  3.148 ms  5.226 ms  5.224 ms
 5  2001:7f8:13::a505:4113:2  18.009 ms  18.007 ms  18.251 ms
 6  2a04:4e42:8e::729  15.896 ms  16.603 ms  16.431 ms
```

**Comment by SuperSandro2000** [comment] 2023-02-21 16:08
> Interesting is also that http responds faster than https.

because it just responds with a Location header aka redirect instead of content. Add -L to curl to follow redirects.

**Comment by MasterMind2k** [comment] 2023-02-26 10:39
And a trace route when things don't work:
```
[nix-shell:~]$ traceroute -n -I -6 channels.nixos.org
traceroute to channels.nixos.org (2a04:4e42:8e::729), 30 hops max, 80 byte packets
 1  <private>  1.720 ms  1.878 ms  2.405 ms
 2  * * *
 3  <private>  5.525 ms  5.523 ms  5.521 ms
 4  <private>  5.189 ms  5.187 ms  5.515 ms
 5  2001:7f8::d361:0:1  13.933 ms  13.932 ms  14.130 ms
 6  2a04:4e42:8e::729  17.704 ms  16.311 ms  16.154 ms

```

**Comment by MasterMind2k** [comment] 2023-04-01 08:45
It's been a while and I didn't had any serious issues. I believe this is my ISP's problem.

If there aren't any avenues to investigate, you may close this issue.

Thanks for support!

**Closed** 2023-04-01 18:29 UTC
