### ISSUE TITLE
bundlerEnv fails if Gemfile uses File.read to read ruby version from .ruby-version

### ISSUE THREAD

**Issue by cumber** [NixOS/nixpkgs#181693] opened 2022-07-16 05:33 UTC
### Describe the bug

I'm setting up a nix-based development environment for an existing Ruby project. Using bundix and `bundlerEnv` seemed straightforward, but I hit this error when trying to `bundle exec` things:

    [!] There was an error parsing `Gemfile`: No such file or directory @ rb_sysopen - /nix/store/zkdzcalrwffd43csi9hg99rgh34643hl-gemfile-and-lockfile/.ruby-version. Bundler cannot continue.

This turned out to be because the `Gemfile` contained:

    ruby File.read(File.join(__dir__, '.ruby-version')).strip

But when using `bundlerEnv`, bundler is reading the `Gemfile` from that `gemfile-and-lockfile` derivation, not from my repository. That derivation seems to be produced here: https://github.com/NixOS/nixpkgs/blob/b6eeaa827589aa797154deef8dbb184a32314e94/pkgs/development/ruby-modules/bundled-common/default.nix#L81, and it only contains a copy of the `Gemfile` and `Gemfile.lock`, so `.ruby-version` isn't available where the `Gemfile` expects it to be.

I know we probably can't support every possible `Gemfile` if they can read from arbitrary files, but using `.ruby-version` as a single point of control for the desired Ruby version and reading it in the Gemfile like this seems to be a reasonably common idiom.

Do we think it's worth also including the `.ruby-version` file in that `confFiles` derivation, if it's present? Or perhaps instead adding an argument to `bundlerEnv` that would enable extra files to be included?

### Steps To Reproduce

I've created a minimal example repo here: https://github.com/cumber/gemfile-rubyversion-demo

1. Check out the above reposotiry
2. Enter a dev shell with `nix develop`
3. Run `bundle check`

### Expected behavior

It would be nice if the above just worked with no further configuration (would require the `.ruby-version` file to be copied alongside the `Gemfile`). But it would also be okay if I could supply additional configuration to `bundlerEnv` to make this work, even it doesn't work by default.

If just copying `.ruby-version` (if present) is an acceptable solution, I'd be happy to prepare a pull request. I'm just fairly new to the Ruby infrastructure in nixpkgs, and would rather someone who knows what they're doing tell me if that would be a bad idea (e..g would it cause problems by mass invalidating hashes, or something?).

### Notify maintainers

I am not sure who the maintainers would be. From the history, possibly @nyarly or @manveru ? Apologies for the spam if not.

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.49, NixOS, 22.11 (Raccoon), 22.11.20220626.f2537a5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos-21.03pre249162.1dc37370c48"`
 - nixpkgs: `/nix/store/1qz0d0cx49ic26jynvb6fqmzl138rj0s-source`

**Comment by kirillrdy** [comment] 2023-05-31 10:54
greetings !

my 2 cents

- its common for projects to have .ruby-version ( rbenv etc )
- its also common for Gemfile to specify ruby version
- in nix, ruby version is specified in nix derivation

so

- when specifying .ruby-version, there is an expectation that something is going to provide the version (eg rbenv )
- when specifying ruby version in Gemfile, its more of a specification,  so if current ruby version doesnt match you simply get en error
- when specifying ruby version in nix, its not an expectation, it's a parameter for nix to build that version, so its nor requirement nor and expectation, its more like part of code.

with this in mind, I assume if there is a project where some team members use rbenv, and some team members use nix. I think it would be easier to manually maintain .ruby-version and nix env ( either remove requirement from Gemfile or have it hard coded )

as for nixpkgs to also read .ruby-version, I dont have strong preference, probably current best person to reach out is @marsam

**Comment by javier-hcp** [comment] 2023-09-11 15:26
The problem is is now that bundler supports a file argument when declaring a version in the Gemfile. ej
```
# Gemfile
ruby file: '.ruby-version'
```

If the file is not present this results in the validate_ruby! in bundler to fail as it thinks the version specified is the empty string?

```
/nix/store/zxrjx7v9q26k9g2bwy3v3zrd9qmksd62-bundler-2.4.13/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/definition.rb:442:in `validate_ruby!': Your Ruby version is 3.2.2, but your Gemfile specified  (Bundler::RubyVersionMismatch)
```

I understand the general fix would be to read the Gemfile to see if the ruby invocation using the file: argument and copy that file. I can also see why that would be undersirable. Is there a way to tell bundlerEnv to also copy the .ruby-version file? maybe specificing a src attribute?

**Comment by kirillrdy** [comment] 2023-09-11 22:01
at this stage, I would recommend just patching Gemfile, you can do this using something like runCommand, so in your repo Gemfile is untouched

**Comment by PuercoPop** [comment] 2023-09-12 03:33
@kirillrdy Thanks for the suggestion. However I am new enough to nix that I don't know how I would use runCommand for that. I've used postPatch + substituteInPlace for workarounds where I need to modify the source code for reasons that are outside of my control. But I'm don't think I can pass a postPatch hook to bundlerEnv right?

I've submitted a potential fix, letting the user specify additional files to be copied into the store where the Gemfile and Gemfile.lock are so that the ruby version can be determined as a result of evaluating the Gemfile. Let me know what you think :pray:

**Comment by PuercoPop** [comment] 2023-09-14 14:58
@cumber you can use the extraConfigPaths, ej. `extraConfigPaths = [ "${./.}/.ruby-version" ];`. I have verified the option works for the scenario described. The option was added after this issue but it was never linked. Can you verify that it works for you? If so should we close this issue?

**Comment by cumber** [comment] 2024-03-15 02:26
Sorry for the delayed response @PuercoPop; yes, I can confirm this works, when I update to a new enough nixpkgs.

The way the arguments are handled made it a bit hard to find the right nixpkgs commit (I'm having unrelated difficulties upgrading very far beyond the current nixpkgs pin in this project), since `extraConfigPaths` doesn't appear as an explicit argument to the `bundlerEnv` function. It's accepted via `args@{ <explicit-args>, ... }` and passed through to a function in a different file, which also accepts all arguments, meaning that passing `extraConfigPaths` before that feature was implemented just silently does nothing.

It might be better for traceability if `extraConfigPaths` was an explicit argument to `bundlerEnv`, but of course that's not going to fix the old versions where that was a obstacle.

I'm happy that this issue is resolved, anyway.

**Closed** 2024-03-15 02:26 UTC
Labels: 0.kind: bug, 6.topic: ruby
