### ISSUE TITLE
Desktop menu entries are missing from many desktop applications

### ISSUE THREAD

**Issue by danwdart** [NixOS/nixpkgs#111467] opened 2021-01-31 13:17 UTC
**Describe the bug**
Many desktop applications don't come with .desktop files:

- [x] bristol #284846
- [x] polyphone #284827
- [x] ~avogadro~ https://github.com/NixOS/nixpkgs/pull/174634/commits/f1ca7eecbb1346bb67741850b359ea0778fcddab
- [x] armagetronad #284098
- [x] ioquake3 #250100
- [x] mupen64plus (`/nix/store/9dm04393k1jr2lyg0c9lmcj76byylsyn-mupen64plus-2.5.9/share/applications/mupen64plus.desktop`)
- [x] nethack-qt #284080
- [x] nexuiz #279467
- [x] openarena #250105
- [x] quake3e #279461
- [x] quakespasm #132826
- [x] sauerbraten: #145445
- [x] speed_dreams #287524
- [x] torcs #288021
- [x] trigger #288348
- [x] urbanterror #250216
- [x] yquake2 #286107
- [x] soundmodem (sudo soundmodemconfig) #302656
- [x] ~sleepyhead~ #202055
- [x] putty #287037
- [x] xcruiser #285579

**To Reproduce**
1. Install either of the given applications
2. Search in the menu for their shortcuts
3. Observe they are missing

**Expected behavior**
Desktop menus for these applications are missing.

**Screenshots**
Negative screenshots don't make sense

**Additional context**
Installed through configuration.nix, if that makes any difference.

**Notify maintainers**
Unsure who'd be the best person to speak to about this.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.93, NixOS, 20.09.2812.f18fbc33930 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.2812.f18fbc33930, unstable-21.03pre265961.891f607d530"`
 - channels(dwd): `"home-manager-20.09, nixos-20.09.2812.f18fbc33930, unstable-21.03pre265961.891f607d530"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:

Unsure about that. At least packages above and possibly more.

Thank you!

**Comment by fabaff** [comment] 2021-02-01 16:21
The upstream projects should provide `.desktop` files to populate the menus of the various Desktop environments. It would be possible for the maintainer of the affected packages to add an entry according to the [Desktop Menu Specification
](https://specifications.freedesktop.org/menu-spec/menu-spec-latest.html) manually but that's a kind of last resort because other distributions would not benefit.

I check that at least `virt-manager`, `gimp` and `polyphone` have `.desktop` files in their repos. I guess they were not added because there was no demand so far.

**Comment by symphorien** [comment] 2021-02-01 17:08
at least gimp does have a desktop file on my system  /nix/store/4a0d7inzfq8vc09lqbmp5px9n6czvs7y-gimp-2.10.20/share/applications/gimp.desktop

**Comment by danwdart** [comment] 2021-02-01 21:57
Yes, I noticed virt-manager already has one, as does gimp, virt-viewer adds a %u and many others have desktop files on other distros already, so I guess they could be custom or repackaged?

**Comment by symphorien** [comment] 2021-02-02 18:12
My point is: the nix package for gimp has a desktop file, so the problem is probably that you desktop environment fails to display it.
See for example https://github.com/NixOS/nixpkgs/issues/40915

**Comment by danwdart** [comment] 2021-02-02 18:31
Sorry, let me clarify: I removed gimp from the list because I just failed to find it. The rest are definitely not there though.

**Comment by symphorien** [comment] 2021-02-02 20:32
Ok, then it should be reasonably easy to fix this by yourself.
Here is an example where the desktop file is provided by upstream but not installed: https://github.com/NixOS/nixpkgs/pull/100294
Here is an example where the desktop file is created from scratch: https://github.com/NixOS/nixpkgs/pull/86913

**Comment by kip93** [comment] 2022-10-22 09:42
Just having a quick look through a few of these, at least some seem to already include a .desktop file. I'll try to take those available and expose them properly. Besides that, I think we could also just create `.Desktop` entries for those that do not include them. If they decide to add them upstream in the future we can delete our own and use those.

I can try and create these files on some of the upstream projects, but some might be easier than others (e.g., for `bristol` doesn't have the entry, and while it seems to be licensed GPL I can't even find the source code on their website, let alone how to contribute to it), and it could take a while to get them merged, so should we just limit ourselves and twiddle our thumbs waiting?

**Comment by drupol** [comment] 2023-08-19 15:09
Just added desktop item for `ioquake3` and `openarena` in #250105 and #250100

**Comment by danwdart** [comment] 2024-02-12 18:30
Thanks for addressing this.
I personally use it, and think I've seen it, but it's likely one of those things that might need root access or serial/if device capability. I personally think there's value in having `soundmodemconfig` as a desktop entry. Not sure how many agree.

**Comment by Stunkymonkey** [comment] 2024-02-12 23:19
for root-permissions we could use something like `pkexec`?

or maybe we have `security.sudo.extraRules` for this?

both do not feel perfect.

**Comment by Stunkymonkey** [comment] 2024-04-17 18:40
all tasks are now marked as resolved. I guess we can close it.

**Closed by Stunkymonkey** 2024-04-17 18:40 UTC
Labels: 0.kind: bug, 3.skill: sprintable, 3.skill: good-first-bug, 6.topic: freedesktop
