### ISSUE TITLE
imagemagick:  6.9.2 gone from mirrors

### ISSUE THREAD

**Issue by deepfire** [NixOS/nixpkgs#12583] opened 2016-01-24 00:36 UTC
```
[deepfire@andromedae:~]$ nsr /nix/store/h0y1x0gq66x9cqhrc6g0kfjdszv6ssz7-ImageMagick-6.9.2-0.tar.xz.drv
these derivations will be built:
  /nix/store/h0y1x0gq66x9cqhrc6g0kfjdszv6ssz7-ImageMagick-6.9.2-0.tar.xz.drv
building path(s) ‘/nix/store/1l6q2zw854wrq17n6z4dd4q8h54iwa0n-ImageMagick-6.9.2-0.tar.xz’
trying http://www.imagemagick.org/download/releases/ImageMagick-6.9.2-0.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found

trying ftp://ftp.sunet.se/pub/multimedia/graphics/ImageMagick/releases/ImageMagick-6.9.2-0.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (9) Server denied you to change to the given directory

trying http://ftp.sunet.se/pub/multimedia/graphics/ImageMagick/releases/ImageMagick-6.9.2-0.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found

trying ftp://ftp.imagemagick.org/pub/ImageMagick/releases/ImageMagick-6.9.2-0.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
curl: (78) RETR response: 550

trying http://ftp.fifi.org/ImageMagick/releases/ImageMagick-6.9.2-0.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found

trying ftp://ftp.fifi.org/ImageMagick/releases/ImageMagick-6.9.2-0.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (78) RETR response: 550

trying http://imagemagick.mirrorcatalogs.com/releases/ImageMagick-6.9.2-0.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found

trying ftp://imagemagick.mirrorcatalogs.com/imagemagickreleases/ImageMagick-6.9.2-0.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (67) Access denied: 500
error: cannot download ImageMagick-6.9.2-0.tar.xz from any mirror
builder for ‘/nix/store/h0y1x0gq66x9cqhrc6g0kfjdszv6ssz7-ImageMagick-6.9.2-0.tar.xz.drv’ failed with exit code 1
error: build of ‘/nix/store/h0y1x0gq66x9cqhrc6g0kfjdszv6ssz7-ImageMagick-6.9.2-0.tar.xz.drv’ failed
```

**Comment by vcunat** [comment] 2016-01-24 08:34
Duplicate of #12493 and had been fixed already on master. I re-tested that now that it succeeds from a macports mirror in the end.

**Closed by vcunat** 2016-01-24 08:34 UTC
