### ISSUE TITLE
Include-what-you-use not working with cmake

### ISSUE THREAD

**Issue by KoviRobi** [NixOS/nixpkgs#222908] opened 2023-03-24 16:13 UTC
### Describe the bug
Unable to use it with cmake (or standalone, covered by https://github.com/NixOS/nixpkgs/issues/189753)

Repro repo at https://github.com/KoviRobi/nixpkgs-iw-yu-error

> This demonstrates the error with getting to use iwyu with nixpkgs
>
> ```console
> $ direnv allow .
> $ rm -rf build/
> $ cmake -Bbuild -GNinja
> $ cmake --build build
> ```
>
> - Expected: Warning about excess includes.
> - Got: No warning
>
> Also tried running it manually, it hits
> https://github.com/NixOS/nixpkgs/issues/189753
>
> ```console
> $ iwyu_tool.py -p build/
> /tmp/nixpkgs-iw-yu-error/main.c:1:10: fatal error: 'stdio.h' file not found
> #include <stdio.h>
>          ^~~~~~~~~
> 
> /tmp/nixpkgs-iw-yu-error/main.cpp:1:10: fatal error: 'iostream' file not found
> #include <iostream>
>          ^~~~~~~~~~
> ```

### Expected behavior
IWYU giving a warning about unused includes.

### Notify maintainers
Package seems unmaintained. Last commit by @sikmir and last updated by @Luflosi 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.20, NixOS, 23.05 (Stoat), 23.05.20230320.8276a16`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/69zyj3m1id154sxf696clvv1dk1bk14w-source`

```

**Comment by Artturin** [comment] 2023-11-27 23:59
Dupe of https://github.com/NixOS/nixpkgs/issues/189753 (which you linked)

**Closed by Artturin** 2023-11-27 23:59 UTC
Labels: 0.kind: bug
