### ISSUE TITLE
Krita fails to build

### ISSUE THREAD

**Issue by aidalgol** [NixOS/nixpkgs#170135] opened 2022-04-24 20:48 UTC
### Describe the bug
The Krita derivation build fails with a Python import error, and a compilation error.
```console
-- Found OpenColorIO: /nix/store/vnizhdbvky4v4sbl7axxi3z97qm65738-opencolorio-1.1.1-dev/include/OpenColorIO (found suitable version "1.1.1", minimum required is "1.1.1")
Traceback (most recent call last):
  File "/build/krita-5.0.2/cmake/modules/FindSIP.py", line 18, in <module>
    import sipbuild
ModuleNotFoundError: No module named 'sipbuild'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/krita-5.0.2/cmake/modules/FindSIP.py", line 28, in <module>
    import sipconfig
ModuleNotFoundError: No module named 'sipconfig'
```
```console
/build/krita-5.0.2/plugins/impex/raw/3rdparty/libkdcraw/src/kdcraw.cpp: In member function 'bool KDcrawIface::KDcraw::extractRAWData(const QString&, QByteArray&, KDcrawIface::DcrawInfoContainer&, unsigned int)':
/build/krita-5.0.2/plugins/impex/raw/3rdparty/libkdcraw/src/kdcraw.cpp:386:24: error: 'struct libraw_output_params_t' has no member named 'shot_select'
  386 |     raw.imgdata.params.shot_select = shotSelect;
      |                        ^~~~~~~~~~~
```

### Steps To Reproduce
1. Set the `nixpkgs` channel to `https://nixos.org/channels/nixpkgs-unstable`
2. Run `nix-build '<nixpkgs>' -A krita`
3. Run the  `nix log /nix/store/aaaa...-krita-5.0.2.drv` command printed at the end of the output and search for the string "error".

### Expected behavior
For the derivation to build successfully.

### Notify maintainers

@abbradar 

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m"
these 5 paths will be fetched (0.55 MiB download, 2.68 MiB unpacked):
  /nix/store/7b2vmi7cq7lzw8g6kaihzg2kyilj4slm-bash-interactive-5.1-p16-dev
  /nix/store/9pxskbhf92x9cxvg87nbzw2q1kmkrym6-bash-interactive-5.1-p16-info
  /nix/store/f2fnhhjanmxganm3xa5inwgvi6wj2ran-bash-interactive-5.1-p16-doc
  /nix/store/j2r2nlxhwhaiv1ncxz5ip9jhyhmcxc5c-nix-info
  /nix/store/zghsxxqb2gyz460q4r7jfdc2lpg3rgjw-bash-interactive-5.1-p16-man
copying path '/nix/store/f2fnhhjanmxganm3xa5inwgvi6wj2ran-bash-interactive-5.1-p16-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/9pxskbhf92x9cxvg87nbzw2q1kmkrym6-bash-interactive-5.1-p16-info' from 'https://cache.nixos.org'...
copying path '/nix/store/zghsxxqb2gyz460q4r7jfdc2lpg3rgjw-bash-interactive-5.1-p16-man' from 'https://cache.nixos.org'...
copying path '/nix/store/7b2vmi7cq7lzw8g6kaihzg2kyilj4slm-bash-interactive-5.1-p16-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/j2r2nlxhwhaiv1ncxz5ip9jhyhmcxc5c-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.111, NixOS, 21.11 (Porcupine), 21.11.20220415.278ecd2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(aidan): `"nixpkgs-22.05pre372099.3c0f57e36ed"`
 - channels(root): `"nixos-21.11.336755.efea022d6fe, home-manager-21.11.tar.gz"`
 - nixpkgs: `/home/aidan/.nix-defexpr/channels/nixpkgs`
 ```

**Comment by wegank** [comment] 2022-04-24 21:14
Duplicate of #170091

**Comment by aidalgol** [comment] 2022-04-24 21:15
Oops, sorry.

**Closed by wegank** 2022-04-24 21:14 UTC
Labels: 0.kind: bug
