### ISSUE TITLE
Gitit is broken again on 18.09

### ISSUE THREAD

**Issue by dasJ** [NixOS/nixpkgs#46421] opened 2018-09-09 13:15 UTC
## Issue description

Maybe related to #32377
Gitit doesn't install on NixOS 18.09

### Steps to reproduce

```
$ nix-env -iA nixos.haskellPackages.gitit
[snip]
Configuring hoauth2-1.7.2...
CallStack (from HasCallStack):
  die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:958:20 in Cabal-2.2.0.1:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:462:12 in Cabal-2.2.0.1:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:596:20 in Cabal-2.2.0.1:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:67:5 in Cabal-2.2.0.1:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:178:19 in Cabal-2.2.0.1:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:115:27 in Cabal-2.2.0.1:Distribution.Simple
  defaultMain, called at Setup.hs:2:8 in main:Main
Setup: Encountered missing dependencies:
exceptions >=0.8.3 && <0.10
```

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.68, NixOS, 18.09beta78.6f3bd5db2f4 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09beta78.6f3bd5db2f4, nixos-unstable-19.03pre151837.ca2ba44cab4"`
 - channels(janne): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by srhb** [comment] 2018-09-09 18:31
As discussed earlier in #nixos, gitit from upstream master has support for pandoc 2, and hoauth2 does build when jailbroken, so that's probably the overrides we should be using.

**Comment by dasJ** [comment] 2018-09-09 21:11
Also from earlier on #nixos: This is the overlay that fixes the problem: https://gist.github.com/srhb/3485b34083427e8a2c1e3c3f9a1a11eb

**Comment by dotlambda** [comment] 2020-06-07 23:35
Gitit seems to be fixed on master (but is still marked as broken) because it was updated to [0.13.0.0](https://github.com/jgm/gitit/releases/tag/0.13.0.0). Can you confirm?

**Comment by dasJ** [comment] 2020-06-08 13:03
I don't know, I switched to Joplin since gitit doesn't work

**Comment by dotlambda** [comment] 2020-06-10 07:30
closing as duplicate of https://github.com/NixOS/nixpkgs/issues/32377

**Closed by dotlambda** 2020-06-10 07:30 UTC
