### ISSUE TITLE
tensorflow cannot find libcusolver.so.8.0

### ISSUE THREAD

**Issue by jyp** [NixOS/nixpkgs#29798] opened 2017-09-26 09:49 UTC
## Issue description

Tensorflow compiles fine, but when loading it from python, one gets:

```
Traceback (most recent call last):
  File "/nix/store/66ixvph9af5dx71126c2mp8gl1kkc8g7-python3-3.6.2-env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/nix/store/66ixvph9af5dx71126c2mp8gl1kkc8g7-python3-3.6.2-env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/nix/store/66ixvph9af5dx71126c2mp8gl1kkc8g7-python3-3.6.2-env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/nix/store/66ixvph9af5dx71126c2mp8gl1kkc8g7-python3-3.6.2-env/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/nix/store/66ixvph9af5dx71126c2mp8gl1kkc8g7-python3-3.6.2-env/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_lm.py", line 1, in <module>
    import TypedFlow.typedflow_rts as tyf
  File "/home/xbejea/repo/gu/StackRNN/TypedFlow/typedflow_rts.py", line 1, in <module>
    import tensorflow as tf
  File "/nix/store/66ixvph9af5dx71126c2mp8gl1kkc8g7-python3-3.6.2-env/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/nix/store/66ixvph9af5dx71126c2mp8gl1kkc8g7-python3-3.6.2-env/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/nix/store/66ixvph9af5dx71126c2mp8gl1kkc8g7-python3-3.6.2-env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/nix/store/66ixvph9af5dx71126c2mp8gl1kkc8g7-python3-3.6.2-env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/nix/store/66ixvph9af5dx71126c2mp8gl1kkc8g7-python3-3.6.2-env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/nix/store/66ixvph9af5dx71126c2mp8gl1kkc8g7-python3-3.6.2-env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/nix/store/66ixvph9af5dx71126c2mp8gl1kkc8g7-python3-3.6.2-env/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/nix/store/66ixvph9af5dx71126c2mp8gl1kkc8g7-python3-3.6.2-env/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory
```

### Steps to reproduce

Attempt to load tensorflow from python.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

Fedora

* Nix version: (run `nix-env --version`)

nix-env (Nix) 1.11.6

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

commit 01d53df77f26d0e87fea568c612f3aec8280a266

**Comment by jyp** [comment] 2017-09-26 12:09
This bug is caused by 693de5b8c6006e4481ea169507cca1f72f4cede7 : "cudatoolkit: Move libcudart to a separate output". With comment: "This prevents opensubdiv (and thus blender) from having all of cudatoolkit in its closure."

@edolstra As the author of that commit, could you let me know how to re-include libcudart in the closure of tensorflow? (In fact, from my naive point of view, it seems that 693de5b8c6006e4481ea169507cca1f72f4cede7 actually breaks cudatoolkit, so the fix may be in cudatoolkit, not tensorflow). Thanks in advance for your help!

**Comment by jyp** [comment] 2017-09-26 12:10
@abbradar In case you'd wonder why your merge of today does not work; see the above message.

**Comment by abbradar** [comment] 2017-09-26 12:11
@jyp Ah -- I couldn't verify that GPU works because I don't own an nvidia. Should have asked someone to verify...

**Comment by jyp** [comment] 2017-09-26 13:24
@abbradar To be sure, your merge has nothing to do with the problem. Nothing wrong with it.

**Comment by jyp** [comment] 2017-09-29 09:31
In the absence of further information i propose to revert the offending commit:
https://github.com/NixOS/nixpkgs/pull/29920

**Comment by FRidh** [comment] 2017-09-29 19:04
Basically a duplicate of https://github.com/NixOS/nixpkgs/issues/29575
@jyp can you try https://github.com/NixOS/nixpkgs/issues/29575#issuecomment-330679267

**Comment by jyp** [comment] 2017-10-02 12:42
@FRidh Yes, this works. But note that because cudnn is an intermediate dependency, then cudnn itself must depend on the unsplit package.

**Comment by TravisWhitaker** [comment] 2017-10-02 19:15
@jyp I simply "un-split" cudatoolkit this way (leaving cudnn untouched) without any collision issues:

```
unsplit_cudatoolkit = symlinkJoin
{
    name = "unsplit_cudatoolkit";
    paths = [ cudatoolkit.out
              cudatoolkit.lib
            ];
};
```

Granted, I'm using my own TF derivation rather than the one in Nixpkgs, but I don't think that should have an effect on collisions between cudatoolkit and cudnn. What exactly is going wrong on your end?

**Comment by abbradar** [comment] 2017-10-02 21:04
@TravisWhitaker unrelated question -- did you by any chance managed to compile it from source?

**Comment by TravisWhitaker** [comment] 2017-10-02 23:26
I've got a derivation that builds a working `libtensorflow_cc.so` from source with or without cuda support (I haven't tested any of the Python functionality), but it's not pretty and there's still some impurity from Bazel. If there's interest I'll clean it up a bit and stick it in a WIP PR; I'm sure there's someone out there who knows enough about Bazel to work out the remaining kinks.

I suspect getting the TF build system to be totally pure would require significant (and difficult to maintain) patches to the Bazel files, perhaps to a sufficient degree to make a Nix-specific TF build system worth considering, depending on interest and tolerance for impurity.

**Comment by abbradar** [comment] 2017-10-02 23:45
@TravisWhitaker please do, I'll probably be interested in trying to pick it up later.

**Closed** 2017-10-10 12:16 UTC
