### ISSUE TITLE
get_iplayer: broken on aarch64-darwin

### ISSUE THREAD

**Issue by gshpychka** [NixOS/nixpkgs#249578] opened 2023-08-16 17:34 UTC
### Describe the bug
`get_iplayer` produces errors after being called:

```
 get_iplayer --help
/nix/store/3h7nka924q5iy880mjh69a0g4c0lg9l0-perl5.36.0-get_iplayer-3.31/bin/.get_iplayer-wrapped: line 26: package: command not found
/nix/store/3h7nka924q5iy880mjh69a0g4c0lg9l0-perl5.36.0-get_iplayer-3.31/bin/.get_iplayer-wrapped: line 27: my: command not found
/nix/store/3h7nka924q5iy880mjh69a0g4c0lg9l0-perl5.36.0-get_iplayer-3.31/bin/.get_iplayer-wrapped: line 28: my: command not found
/nix/store/3h7nka924q5iy880mjh69a0g4c0lg9l0-perl5.36.0-get_iplayer-3.31/bin/.get_iplayer-wrapped: /nix/store/3h7nka924q5iy880mjh69a0g4c0lg9l0-perl5.36.0-get_iplayer-3.31/bin/get_iplayer: line 29: syntax error near unexpected token `('
/nix/store/3h7nka924q5iy880mjh69a0g4c0lg9l0-perl5.36.0-get_iplayer-3.31/bin/.get_iplayer-wrapped: /nix/store/3h7nka924q5iy880mjh69a0g4c0lg9l0-perl5.36.0-get_iplayer-3.31/bin/get_iplayer: line 29: `$version_text = sprintf("v%.2f", $version) unless $version_text;'
```

### Steps To Reproduce
1. `nix-shell -p get_iplayer`
2. `get_iplayer --help`

### Expected behavior
The command works.

### Notify maintainers

@chewblacka

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.5.0, macOS 13.4.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by chewblacka** [comment] 2023-08-17 18:18
Hi many thanks for the detailed bug report. 
I've released a fix for this issue on nix-darwin which has just been merged into master. It'll be a few days before it gets pushed to nix packages. I'll ping you then to check if the fix works on your end. Many thanks.

**Closed** 2023-08-20 16:49 UTC
Labels: 0.kind: bug, 6.topic: darwin

**Comment by chewblacka** [comment] 2023-08-22 16:37
Hi, the fix is now in the latest edition of nixpkgs. `get_iplayer` should now work as intended on darwin. Let me know if there are any issues!
