### ISSUE TITLE
mdns support for nss does not work when networkd is enabled

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#98050] opened 2020-09-15 15:49 UTC
**Describe the bug**
Remote .local domains cannot be resolved when networkd is enabled

I noticed that `resolve` comes before `mdns_minimal` in the generated `nsswitch.conf`:
```
passwd:    files systemd
group:     files systemd
shadow:    files

hosts:     files mymachines resolve [!UNAVAIL=return] mdns_minimal [NOTFOUND=return] dns mdns myhostname
networks:  files

ethers:    files
services:  files
protocols: files
rpc:       files
```
while archwiki recommended putting `mdns_minimal` before `resolve`: https://wiki.archlinux.org/index.php/Avahi#Hostname_resolution

not sure if this is the cause

**To Reproduce**
1. enable `services.avahi.nssmdns`

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by poscat0x04** [comment] 2020-09-15 16:02
possibly related modules:
- nsswitch
- resolved
- avahi-daemon

**Comment by doronbehar** [comment] 2020-09-19 18:46
> I noticed that resolve comes before mdns_minimal in the generated nsswitch.conf:
> ```
> hosts:     files mymachines resolve [!UNAVAIL=return] mdns_minimal [NOTFOUND=return] dns mdns myhostname
> ```
> While archwiki recommended putting mdns_minimal before resolve: wiki.archlinux.org/index.php/Avahi#Hostname_resolution . Not sure if this is the cause.

IIRC I experienced issues with `.local` name resolving a while ago with a certain printer on a certain network. I can't say I can reproduce the issue reliably though, unfortunately.

@flokli seems to have taken special care in https://github.com/NixOS/nixpkgs/commit/fd21793de61bacf8893d7c5f6e7fdd3c76855dfe to put the `mdns` word after the `dns` word - opposite to what the Arch Wiki recommends:

https://github.com/NixOS/nixpkgs/blob/3d36d46fa4b6f97d7c953ee26a84e676b4d9d4d6/nixos/modules/services/networking/avahi-daemon.nix#L241-L244

I couldn't find any mention in [upstream's docs](https://www.mankier.com/5/nsswitch.conf) to what the arch WiKi says.

**Comment by flokli** [comment] 2020-09-20 15:16
@doronbehar I don't think that commit changed anything - it was merely a code move.

As for the general placement, `nss-resolve(8)` says:

>       To activate the NSS module, add "resolve [!UNAVAIL=return]" to the line starting with "hosts:" in /etc/nsswitch.conf. Specifically, it is recommended to place "resolve" early in /etc/nsswitch.conf's "hosts:" line. It
>       should be before the "files" entry, since systemd-resolved supports /etc/hosts internally, but with caching. To the contrary, it should be after "mymachines", to give hostnames given to local VMs and containers
>       precedence over names received over DNS. Finally, we recommend placing "dns" somewhere after "resolve", to fall back to nss-dns if systemd-resolved.service is not available.

From my understanding, systemd-resolved should also support mDNS (also see https://wiki.archlinux.org/index.php/Systemd-resolved#mDNS), so having it early might make sense w.r.t caching.

I'm not sure if enabling both resolved and `services.avahi.nssmdns` is something that should work or not - I didn't really put much thought into it.

**Comment by lopsided98** [comment] 2020-10-04 04:22
Yes, the problem is that `mdns_minimal` is after `resolve`. It used to work right until the config was split up into multiple modules in #87016, which messed up the order. `mkOrder` can be used to fix it.

**Comment by lopsided98** [comment] 2020-10-04 05:06
See #99530 for a fix.

**Comment by wucke13** [comment] 2021-06-13 21:23
This is still not working for me. I have the following relevant config:

```
services.avahi = {
  enable = true;
  nssmdns = true;
  publish = {
    enable = true;
    domain = true;
    addresses = true;
  };
};

networking = {
  useDHCP = false;
  useNetworkd = true;
  firewall.enable = lib.mkDefault false;
};
```

I can `resolvectl query` my local machine `.local`, but no other machine in the network:

```
resolvectl query othermachine.local
othermachine.local: resolve call failed: No appropriate name servers or networks for name found
```

It works however without `.local`. Why is that?

```
resolvectl query othermachine
othermachine: 10.0.0.13                                -- link: wlan0

-- Information acquired via protocol LLMNR/IPv4 in 115.9ms.
-- Data is authenticated: no
```

I'm on 21.05, so the fix mentioned above should be active?

**Comment by lopsided98** [comment] 2021-06-13 21:54
I don't have a machine with the same config accessible right now, but I think this might be expected. mDNS resolution with Avahi uses NSS, while `resolvectl` only goes through `systemd-resolved`, which doesn't do mDNS resolution with your config. It works without `.local` using LLMNR (basically Microsoft's version of mDNS), which is apparently enabled in your config. I think resolving the local machine works due to special handling with systemd-resolved.

Does `ping othermachine.local` work?

**Comment by flokli** [comment] 2021-06-14 10:02
> […] I think this behavior might be expected. mDNS resolution with Avahi uses NSS, while resolvectl only goes through systemd-resolved, which doesn't do mDNS resolution with your config.

Yes, this is to be expected - avahi goes via nss, and networkd also provides a nss module.

`ping othermachine[.local]` will query nss modules configured in nsswitch.conf and should work.

**Comment by wucke13** [comment] 2021-06-14 10:36
> Does ping othermachine.local work?

Yes. Now I feel stupid. Thank you two for the fast input, I guess that settles it. Only one question left, is there an easy way to make it also work with `resolvectl` ?

**Closed by wucke13** 2021-06-14 10:36 UTC
Labels: 0.kind: bug, 6.topic: nixos

**Comment by lopsided98** [comment] 2021-06-16 22:54
@wucke13 You can use systemd-resolved's mDNS resolver instead of Avahi. Remove all the Avahi related config and add `systemd.network.networks.<name>.networkConfig.MulticastDNS = true` (or `"resolve"` if you want to only resolve and not advertise).

**Comment by Valodim** [comment] 2023-03-16 10:21
For those still searching, this is what worked for me:

```nix
# use resolved for hostname resolution
services.resolved.enable = true;

# enable mdns resolution for resolved on all connections
# see https://man.archlinux.org/man/NetworkManager.conf.5#CONNECTION_SECTION
networking.networkmanager.connectionConfig."connection.mdns" = 2;

# still required (at least mdns resolution didn't work for me without)
services.avahi.enable = true;
# nssmdns is NOT needed, since resolved will do the resolution, not the avahi nss module
# services.avahi.nssmdns = true;
```
