### ISSUE TITLE
Python development mode broken for src != ./.

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#68412] opened 2019-09-10 10:22 UTC
**Describe the bug**

I'm trying to install a local python package in development mode to a nix shell. However, the package isn't installed at all unless the nix shell is launched in the directory where `setup.py` is.

Section 9.14.1.2.3 in https://nixos.org/nixpkgs/manual/#developing-with-python says:

> If we create a shell.nix file which calls buildPythonPackage, and if src is a local source, and if the local source has a setup.py, then development mode is activated. 

But this doesn't seem to work if `src` is something else than `./.`.

**To Reproduce**

I have a very simple Python package `foo`. I have two `shell.nix` files. One in the same directory with `setup.py` and one in a sub-directory `nix`:

```
$ tree
.
├── foo
│   ├── bar.py
│   └── __init__.py
├── nix
│   └── shell.nix
├── setup.py
└── shell.nix
```

I'll add the contents of these files to the end of this report as details.

If I use the `shell.nix` in the same directory as `setup.py`, the Python package is installed properly and I can use it:

```
$ pushd .; nix-shell --run "cd /tmp; python -c 'from foo import bar; bar.hello();'"; popd
~/Workspace/nix-shell-python ~/Workspace/nix-shell-python
Obtaining file:///home/jluttine/Workspace/nix-shell-python
Requirement already satisfied: numpy in /nix/store/5qfb84vbps55ip13kv5qnvh7aml9qfkq-python3.7-numpy-1.17.0/lib/python3.7/site-packages (from foo==0.0.0) (1.17.0)
Installing collected packages: foo
  Running setup.py develop for foo
Successfully installed foo
Hello World!
~/Workspace/nix-shell-python
```

Notice that I change the directory to `/tmp` just to make sure Python uses the installed package, not the source code tree. Everything works fine: no errors and I see "Hello World!".

However, I get the following error if I use `nix/shell.nix` by running nix-shell in `nix` subdirectory and trying to use the Python package:

```
$ pushd nix; nix-shell --run "cd /tmp; python -c 'from foo import bar; bar.hello();'"; popd
~/Workspace/nix-shell-python/nix ~/Workspace/nix-shell-python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'foo'
~/Workspace/nix-shell-python
```

Yet, with `nix/shell.nix` the dependencies are installed correctly, it's just the local development package that's missing because importing NumPy works:

```
$ pushd nix; nix-shell --run "cd /tmp; python -c 'import numpy'"; popd
~/Workspace/nix-shell-python/nix ~/Workspace/nix-shell-python
~/Workspace/nix-shell-python
```

Possibly related: https://github.com/NixOS/nixpkgs/issues/66460

**Expected behavior**

I expected the `foo` package to be properly installed in development mode in both scenarios. That is, I expected the following output:

```
$ pushd nix; nix-shell --run "cd /tmp; python -c 'from foo import bar; bar.hello();'"; popd
~/Workspace/nix-shell-python/nix ~/Workspace/nix-shell-python
Hello World!
~/Workspace/nix-shell-python
```

**Metadata**

```
$ nix run nixpkgs.nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.69, NixOS, 19.09.git.fa0b187 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - nixpkgs: `/etc/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pythonPackages.buildPythonPackage
# a list of nixos modules affected by the problem
module:
```

<details>

`setup.py`:
```
import os

if __name__ == "__main__":

    from setuptools import setup, find_packages
    setup(
        install_requires = ["numpy"],
        packages         = find_packages(),
        name             = "foo",
    )
```

`shell.nix`:

```
with import <nixpkgs> {};
with pkgs.python3Packages;

buildPythonPackage rec {
  name = "foo";
  doCheck = false;
  src = ./.;
  buildInputs = [ numpy ];
}
```

`nix/shell.nix`:

```
with import <nixpkgs> {};
with pkgs.python3Packages;

buildPythonPackage rec {
  name = "foo";
  doCheck = false;
  src = ./..;
  buildInputs = [ numpy ];
}
```

`foo/bar.py`:

```
def hello():
    print("Hello World!")
```

</details>

**Comment by FRidh** [comment] 2019-09-10 11:39
Python development mode is for when you're developing your project. In that case you can modify e.g. your code and use it directly. `nix-shell` is used for this as it can do impure things. The `src` attribute is however not used.

In your situation, we should check what the value of `src` is. 

Note that `src` may actually be in the store. What to do in that case? Abort? A work-around could be to copy it from the source in some temporary directory where you can edit and print the directory on the shell. Of course, at the end your changes could be lost, so what would you gain then.

**Comment by FRidh** [comment] 2019-09-10 11:40
Duplicate of https://github.com/NixOS/nixpkgs/issues/66460

**Closed by FRidh** 2019-09-10 11:40 UTC
Labels: 0.kind: bug, 6.topic: python
