### ISSUE TITLE
GHC 7.10 isn't built with a GHC bindist

### ISSUE THREAD

**Issue by pikajude** [NixOS/nixpkgs#11179] opened 2015-11-21 07:09 UTC
As someone who generally works with master, it's not the most convenient thing to need to build two copies of GHC (40+ minutes on my 8-core i7) to do any dev work.

Has someone tried to add the GHC 7.8 bindist to nixpkgs and it ended up being complicated, or has this issue just not been noticed yet?

**Comment by nbp** [comment] 2015-11-21 10:50
cc @peti, @ocharles

**Comment by peti** [comment] 2015-11-21 11:11
Supporting a post 7.8.x binary snapshot is complicated and I didn't bother to pursue the issue because it's a build-time only dependency. If you want to give it a shot, then I am all for it of course!

**Comment by ocharles** [comment] 2015-11-21 15:46
@pikajude are you using @peti's binary cache server btw? I find that almost always avoids any need for recompilation locally.

**Comment by cstrahan** [comment] 2015-11-21 22:11
> Supporting a post 7.8.x binary snapshot is complicated and I didn't bother to pursue the issue because it's a build-time only dependency. If you want to give it a shot, then I am all for it of course!

@peti Is there particular change since then that complicates things? Or was it just a matter of expedience ?

**Comment by peti** [comment] 2015-11-22 19:50
The binary distribution was built with shared library support enabled, so there were over a dozen `.so` files littered all over the source hierarchy that needed non-trivial `patchelf` logic to find each other. I tried to make the compiler work on NixOS for a while and eventually just have up. It's not a hard problem to solve, it's just tedious.

**Comment by Profpatsch** [comment] 2016-07-23 20:38
(triage) is this still relevant?

**Comment by dtzWill** [comment] 2016-12-15 01:03
I believe this is still relevant, see https://github.com/NixOS/nixpkgs/issues/19926 .

**Comment by peti** [comment] 2016-12-15 14:20
This is a duplicate of https://github.com/NixOS/nixpkgs/issues/19926.

**Closed by peti** 2016-12-15 14:20 UTC
Labels: 0.kind: question, 6.topic: haskell
