### ISSUE TITLE
Package request: actual-budget

### ISSUE THREAD

**Issue by keysmashes** [NixOS/nixpkgs#304343] opened 2024-04-15 18:56 UTC
**Project description**

> Actual Budget is a super fast and privacy-focused app for managing your finances.

It's a budgeting app. You can run it as a webserver (and access via any web browser), or as a standalone Electron app.

**Metadata**

* homepage URL: https://actualbudget.org/
* source URL: https://github.com/actualbudget/actual, https://github.com/actualbudget/actual-server
* license: MIT
* platforms: Linux, macOS, Windows

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-04-16 05:05
duplicate of #269069

**Closed by eclairevoyant** 2024-04-16 05:05 UTC
Labels: 0.kind: packaging request
