### ISSUE TITLE
`virtualisation.docker.enableOnBoot = false` does not work

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#213974] opened 2023-02-01 13:37 UTC
### Describe the bug
`virtualisation.docker.enableOnBoot = false` does not work. docker still starts on boot.

### Steps To Reproduce
1. add  `virtualisation.docker.enableOnBoot; virtualisation.docker.enable = true;`
2. apply configuration
### Expected behavior
docker doesn't start on boot, wantedby not set

### Screenshots
![image](https://user-images.githubusercontent.com/7735145/216056265-fd0f7adc-a53b-4871-94e2-8081ff30424f.png)

### Additional context
Problem is that wantedBy is set by the systemd service file shipped with docker. nixos would have to either disable wantedby with `wantedby=`  or strip it from the service file

Also note that it has been broken for some time, so changing the default for enableOnBoot to true might make sense, since it'll prob confuse users

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.0, NixOS, 23.05 (Stoat), 23.05.20221221.da32bb6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(maciej): `""`
 - nixpkgs: `/nix/store/zrxfs7nrz1ylllgmnhpjy4za0aiv25mq-source`
```

**Comment by IndeedNotJames** [comment] 2023-02-01 16:20
> Also note that it has been broken for some time, so changing the default for enableOnBoot to true might make sense, since it'll prob confuse users

`enableOnBoot`'s default is already `true` :eyes:
See #21326

> Problem is that wantedBy is set by the systemd service file shipped with docker.

`WantedBy=` in the packaged unit file doesn't actually do anything.
See #81138 and https://discourse.nixos.org/t/disable-a-systemd-service-while-having-it-in-nixoss-conf/12732/3

Note that due to `docker.socket`, `docker.service` will start as soon as you interact with the *socket*, which includes almost every command from the `docker` cli.

Can you elaborate on how you checked whether docker is auto-starting?
Because I can't reproduce what you are describing :(

**Comment by IndeedNotJames** [comment] 2023-02-12 12:27
Closing due to @mkg20001 not responding and the reasons outlined in my previous comment.

Feel free to reopen, though.

**Closed by IndeedNotJames** 2023-02-12 12:27 UTC
Labels: 0.kind: bug
