### ISSUE TITLE
network-manager doesn't work

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#61531] opened 2019-05-15 03:54 UTC
## Issue description

On nixos-unstable network stop to work after `nixos-rebuild switch`. Only `systemctl restart network-manager` makes it work again. Does anybody knows what is the issue?

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by worldofpeace** [comment] 2019-05-15 05:57
Can we get your nixpkgs revisions before and after the rebuild switch?

**Comment by samdoshi** [comment] 2019-05-15 08:11
This happens to me too, I believe the issue is a duplicate of #61490

**Comment by teto** [comment] 2019-05-15 08:56
closing as duplicate of #61490

**Closed by teto** 2019-05-15 08:56 UTC
