### ISSUE TITLE
nodePackages.elm-test: No such file or directory

### ISSUE THREAD

**Issue by jasoncarr0** [NixOS/nixpkgs#45280] opened 2018-08-17 21:37 UTC
## Issue description

The elm-test package in nodePackages

### Steps to reproduce

Via nixpkgs:
```
$ nix run nixpkgs.elmPackages.elm nixpkgs.nodePackages.elm-test
$ elm-test init
$ elm-test
Success! Compiled 54 modules.                                       
Successfully generated /dev/null
Unhandled exception while running the tests: { Error: spawn /nix/store/rll733jmgykq2sxrjbjgsm8hy6wzpsv8-node-elm-test-0.18.12/lib/node_modules/elm-test/bin/elm-interface-to-json ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /nix/store/rll733jmgykq2sxrjbjgsm8hy6wzpsv8-node-elm-test-0.18.12/lib/node_modules/elm-test/bin/elm-interface-to-json',
  path: '/nix/store/rll733jmgykq2sxrjbjgsm8hy6wzpsv8-node-elm-test-0.18.12/lib/node_modules/elm-test/bin/elm-interface-to-json',
  spawnargs: [ '--path', '/home/example/empty/tests' ] }
```

Similar results follow from npm install. 

## Technical details

The elm-interface-to-json binary installed via npm does not work with NixOS.
After installing via `npm install`, similar issues arise. The issue was fixed for me by deleting the elm-interface-to-json binary in node_modules/elm-test/bin, and instead linking the copy from the nix store (from elmPackages).

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.56, NixOS, 18.03.132915.d6c6c7fcec6 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.132915.d6c6c7fcec6"`
 - channels(jason): `"bleeding-edge, temp-pijul-0.10, unstable-18.09pre147850.2428f5dda13"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

## Proposed fix

Move elm-test into elmPackages, build it against existing elm-interface-to-json.

**Comment by mdevlamynck** [comment] 2018-10-28 10:49
https://github.com/mdevlamynck/nixpkgs/tree/feature/elm-test
This branch contains a package for elmi-to-json and a package for elm-test (for elm 0.19.0). These were generated with cabal2nix and node2nix. 

Remaining problems:
* elmi-to-json:
  * the dependency rainbow-0.30.0.2 fails to build
* elm-test:
  * the dependency fsevents 1.1.2 fails to build (install script trying to request the url http://www.example.com/glob)
  * the path to the binary elmi-to-json needs to be patched in `lib/runner.js`.

**Comment by domenkozar** [comment] 2018-10-30 11:06
Try using https://github.com/adisbladis/pnpm2nix for nodejs

**Comment by stoeffel** [comment] 2018-12-03 21:42
happy to get rid of rainbow-0.30.0.2. Would totally appreciate a PR ❤️

**Comment by mdevlamynck** [comment] 2018-12-03 23:17
I can try to make a PR but I don't know much about haskell or its ecosystem, what would you replace rainbow with?

**Comment by stoeffel** [comment] 2018-12-04 01:09
@mdevlamynck I would just remove it completely. It's not really necessary. I might get to it next week, but happy to help you if you have questions. I'm @stoeffel on http://elmlang.slack.com.

**Comment by dmvianna** [comment] 2019-03-17 04:27
Any update on this? As it stands, a fairly basic Elm library (its test runner) cannot be used in Nixos. I wasn't able to make it work on OSX either, but it seems that the problem is being pushed down to OSes to fix it. I wonder if anyone have made it run anywhere?

**Comment by domenkozar** [comment] 2019-03-18 03:33
@svanderburg do you have an idea why `binwrap-install` is missing, given that `elmi-to-json` depends on it and tries to execute it?

```
> elmi-to-json@0.19.1 install /nix/store/rwwndxadj3zmryyla7mafaypvy43kdzj-node-elm-test-0.19.0-rev5/lib/node_modules/elm-test/node_modules/elmi-to-json
> binwrap-install

sh: binwrap-install: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! elmi-to-json@0.19.1 install: `binwrap-install`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the elmi-to-json@0.19.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2019-03-18T03_33_36_174Z-debug.log
builder for '/nix/store/awg2k8pvr20dmzsrk1ps6p3sgbj49bwp-node-elm-test-0.19.0-rev5.drv' failed with exit code 1
error: build of '/nix/store/awg2k8pvr20dmzsrk1ps6p3sgbj49bwp-node-elm-test-0.19.0-rev5.drv' failed

```

**Comment by turboMaCk** [comment] 2019-05-14 16:01
This is what I do to fix it for now https://github.com/turboMaCk/nix-elm-tools/blob/master/patch-bin-wrap.nix

basically, I mock `binwrap` with noop script and put `elmi-to-json` to expected location in derivation itself.

**Comment by domenkozar** [comment] 2019-06-24 13:47
This has been fixed by https://github.com/NixOS/nixpkgs/pull/63477

**Closed by domenkozar** 2019-06-24 13:47 UTC
Labels: 0.kind: bug, 6.topic: nodejs

**Comment by turboMaCk** [comment] 2019-06-24 14:23
just a note that `elm-test` was now moved so it's located in `elmPackages.elm-test`
