### ISSUE TITLE
gdk-pixbuf: don't build on darwin

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#10259] opened 2015-10-06 17:36 UTC
`platforms.unix` but i don't know if this is intended for OS X. maybe remove darwin from platform.

```
$ nix-env -i gdk-pixbuf-2.31.7
[...]
  CCLD     gdk-pixbuf-pixdata
  CC       queryloaders.o
  CCLD     gdk-pixbuf-query-loaders
  CC       test-gdk-pixbuf.o
  CCLD     test-gdk-pixbuf
  GISCAN   GdkPixbuf-2.0.gir
  GICOMP   GdkPixbuf-2.0.gir
LOADERS=`echo libpixbufloader-*.la` ; \
if test "x$LOADERS" != 'xlibpixbufloader-*.la' ; then \
          echo "Writing a loaders.cache file to use when running examples before installing gdk-pixbuf."; \
  ../gdk-pixbuf/gdk-pixbuf-query-loaders $LOADERS > ./loaders.cache ;\
else \
          echo "No dynamic modules found; will use only static modules for uninstalled example programs."; \
  touch loaders.cache; \
fi
Writing a loaders.cache file to use when running examples before installing gdk-pixbuf.
make[4]: Leaving directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-gdk-pixbuf-2.31.7.drv-0/gdk-pixbuf-2.31.7/gdk-pixbuf'
make[3]: Leaving directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-gdk-pixbuf-2.31.7.drv-0/gdk-pixbuf-2.31.7/gdk-pixbuf'
make[2]: Leaving directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-gdk-pixbuf-2.31.7.drv-0/gdk-pixbuf-2.31.7/gdk-pixbuf'
Making all in po
make[2]: Entering directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-gdk-pixbuf-2.31.7.drv-0/gdk-pixbuf-2.31.7/po'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-gdk-pixbuf-2.31.7.drv-0/gdk-pixbuf-2.31.7/po'
Making all in docs
make[2]: Entering directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-gdk-pixbuf-2.31.7.drv-0/gdk-pixbuf-2.31.7/docs'
Making all in reference
make[3]: Entering directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-gdk-pixbuf-2.31.7.drv-0/gdk-pixbuf-2.31.7/docs/reference'
Making all in gdk-pixbuf
make[4]: Entering directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-gdk-pixbuf-2.31.7.drv-0/gdk-pixbuf-2.31.7/docs/reference/gdk-pixbuf'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-gdk-pixbuf-2.31.7.drv-0/gdk-pixbuf-2.31.7/docs/reference/gdk-pixbuf'
make[4]: Entering directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-gdk-pixbuf-2.31.7.drv-0/gdk-pixbuf-2.31.7/docs/reference'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-gdk-pixbuf-2.31.7.drv-0/gdk-pixbuf-2.31.7/docs/reference'
make[3]: Leaving directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-gdk-pixbuf-2.31.7.drv-0/gdk-pixbuf-2.31.7/docs/reference'
make[3]: Entering directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-gdk-pixbuf-2.31.7.drv-0/gdk-pixbuf-2.31.7/docs'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-gdk-pixbuf-2.31.7.drv-0/gdk-pixbuf-2.31.7/docs'
make[2]: Leaving directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-gdk-pixbuf-2.31.7.drv-0/gdk-pixbuf-2.31.7/docs'
Making all in tests
make[2]: Entering directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-gdk-pixbuf-2.31.7.drv-0/gdk-pixbuf-2.31.7/tests'
make  all-am
make[3]: Entering directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-gdk-pixbuf-2.31.7.drv-0/gdk-pixbuf-2.31.7/tests'
  CC       pixbuf-read.o
  CCLD     pixbuf-read
  CC       pixbuf-lowmem.o
  CCLD     pixbuf-lowmem
Undefined symbols for architecture x86_64:
  "___libc_free", referenced from:
      _record_bytes in pixbuf-lowmem.o
      _free in pixbuf-lowmem.o
  "___libc_malloc", referenced from:
      _malloc in pixbuf-lowmem.o
      _calloc in pixbuf-lowmem.o
      _realloc in pixbuf-lowmem.o
  "___libc_realloc", referenced from:
      _realloc in pixbuf-lowmem.o
ld: symbol(s) not found for architecture x86_64
clang-3.6: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:1149: recipe for target 'pixbuf-lowmem' failed
make[3]: *** [pixbuf-lowmem] Error 1
```

cc @edolstra

**Comment by vcunat** [comment] 2015-10-06 17:53
Duplicate of #10136.

**Closed by vcunat** 2015-10-06 17:53 UTC
