### ISSUE TITLE
Discussion: jailbreak Python packages by default, when doCheck = true;

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#80416] opened 2020-02-18 08:45 UTC
Inspired by patch list for https://github.com/nixos/nixpkgs/blob/master/pkgs/development/python-modules/apache-airflow/default.nix#L138-L164

Introduce `doJailbreak :: Boolean` for python derivation. When it is true (default when `doCheck = true`), jailbreak all deps by using `sed` on known locations. When false, jails can be specified imperatively with `pythonJailbreak` command:
```
jailbreaks = [ "flask-caching" "jinja2" "pandas" ];
postPatch = ''
  pythonJailbreak --jailbreaks "$jailbreaks" setup.py
  pythonJailbreak --jailbreaks "$jailbreaks" requirements.txt
''
```
Not sure if it's worth making `doJailbreak` a function like haskell infra has. IMO jailbreak list (and jailbreak status) should live as close to `src` as possible.

cc @FRidh

**Comment by FRidh** [comment] 2020-02-18 08:48
Duplicate of https://github.com/NixOS/nixpkgs/issues/21278.

**Closed by FRidh** 2020-02-18 08:48 UTC
Labels: 0.kind: enhancement

**Comment by FRidh** [comment] 2020-02-18 08:49
Note there is a way with pip to disable requirement checking altogether, but not on a per-package level. Also, doing this ourselves will definitely be a best effort and won't always work due to the imperative nature of `setup.py`.
