### ISSUE TITLE
rspamd: sockets for socketActivation are not always correctly ordered

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#47421] opened 2018-09-27 12:53 UTC
## Issue description

By default rspamd uses systemd socket activation to bind its workers.
This is done by `bind_socket = "systemd:$fd_number";`.
However when specified your own workers with socket the order of file descriptors is not correct.
In my case the controller responsible for the web/rest interface received the milter proxy socket.

### Steps to reproduce

```
  services.rspamd = {
    enable = true;
    socketActivation = true;
    workers.controller = {};
    workers.rspamd_proxy = {
      type = "proxy";
      extraConfig = ''
        milter = yes; # Enable milter mode
        timeout = 120s; # Needed for Milter usually
        upstream "local" {
          default = yes;
          self_scan = yes; # Enable self-scan
        }
        count = 1; # Do not spawn too many processes of this type
      '';
      bindSockets = [{
        socket = "/run/rspamd.sock";
        mode = "0666";
        owner = "rspamd";
        group = "rspamd";
      }];
    };
  };
  services.postfix.extraConfig = ''
    smtpd_milters = unix:/run/rspamd.sock
    milter_default_action = accept
  '';

```

In this case `controller` will receive the milter socket from `rspam_proxy` instead of its http socket.
This will make milter clients such as postfix fail when delivering messages.

```
$ systemctl cat rspamd-rspam_proxy-1.socket
[Unit]
Description=Rspamd socket 1 for worker rspamd_proxy
[Socket]
Service=rspamd.service
SocketGroup=rspamd
SocketMode=0666
SocketUser=rspamd
ListenStream=/run/rspamd.sock
```

```
$ systemctl cat rspamd-controller-1.socket
[Unit]
Description=Rspamd socket 1 for worker controller
[Socket]
Service=rspamd.service
ListenStream=127.0.0.1:11334
ListenStream=[::1]:11334
```

Postfix will fail with the following message when trying to connect:

```
Sep 27 11:57:43 eve postfix/smtpd[27863]: warning: milter unix:/run/rspamd.sock: unreasonable packet length: 1213486160 > 1073741823
Sep 27 11:57:43 eve postfix/smtpd[27863]: warning: milter unix:/run/rspamd.sock: read error in initial handshake
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by Mic92** [comment] 2018-09-27 12:54
cc @avnik

**Comment by Mic92** [comment] 2018-09-27 12:56
The current workaround is to use:

```
services.rspamd.socketActivation = true
```

**Comment by Mic92** [comment] 2018-09-27 13:08
cc @griff

**Comment by griff** [comment] 2018-09-27 14:40
I will look into it but I am not 100% sure it is related to socketActivation. I seem to recall that I had the same postfix error at some point but it is some time ago so I might remember wrong.

**Comment by griff** [comment] 2018-09-27 16:40
For now it seems related to the number of `ListenStream` lines. When `rspamd-controller-1.socket` only has one `ListenStream` the ordering is correct.

**Comment by griff** [comment] 2018-09-27 20:59
After reading the systemd socket documentation and digging around in the systemd source code I have come to the conclusion that right now socket activation can't be made to reliably work with rspamd.

The problem is that while systemd supports having multiple socket units be attached to one service, like I did with the rspamd module, the sockets from the units are delivered to the service with no guaranteed order.

It can be made to work with changes to rspamd since the sockets have names that could be used by rspamd to match the correct socket with the correct controller.

**Comment by griff** [comment] 2018-09-27 21:15
Found an issue raised for the rspamd change needed rspamd/rspamd#2035

**Comment by Mic92** [comment] 2018-09-27 21:41
Since this cannot reliable work in all cases, we should disable it by default.

**Comment by Mic92** [comment] 2018-09-27 21:43
@griff is it possible to only have a single socket unit?

**Comment by Mic92** [comment] 2018-09-27 21:49
Parsing of socket units is done in a single-thread context, so in the same socket unit the order should be stable: https://github.com/systemd/systemd/blob/master/src/core/load-fragment.c#L406

**Comment by griff** [comment] 2018-09-27 21:50
Yes but it puts some limits on the config. For one thing different unix sockets can't have different groups, owners or mode. Also you can't have one socket binding to all interfaces and IPv4 and IPv6 and one socket bound to only IPv6.

**Comment by griff** [comment] 2018-09-27 21:53
That doesn't matter. When gathering the sockets here: https://github.com/systemd/systemd/blob/master/src/core/service.c#L1225
They iterate the hash where ordering is based on the hash value of the unit not insertion order.

**Comment by griff** [comment] 2018-09-27 21:54
I think.

**Comment by griff** [comment] 2018-09-27 21:55
See https://github.com/systemd/systemd/blob/master/src/basic/hashmap.h#L359

**Comment by griff** [comment] 2018-09-27 21:57
Sorry I misread your comment. Yes the order of ListenStream will also be the order of fds that come from that socket unit. So if you only have one socket unit the order is predictable.

**Comment by griff** [comment] 2018-09-27 22:00
All in all I would remove the socket activation code until multiple socket units are supported in rspamd since having it is only a gun people can shoot themselves in the foot with.

**Comment by griff** [comment] 2018-09-28 02:07
@Mic92 I have created #47449

**Comment by griff** [comment] 2018-10-02 16:55
@Mic92 Should we close this now that socket activation has been removed from both master and 18.09?

**Closed** 2018-10-02 17:16 UTC
