### ISSUE TITLE
epkowa doesn't recognize x770 USB scanner

### ISSUE THREAD

**Issue by neilmayhew** [NixOS/nixpkgs#88732] opened 2020-05-24 01:05 UTC
**Describe the bug**
Since upgrading to 20.03, the epkowa sane backend isn't working.

**To Reproduce**
Use `scanimage -L` to check for the presence of the scanner:

```shellsession
$ lsusb
Bus 001 Device 008: ID 04b8:0130 Seiko Epson Corp. GT-X770 [Perfection V500]
$ scanimage -L
$ 
```

**Expected behavior**
```shellsession
$ lsusb
Bus 001 Device 008: ID 04b8:0130 Seiko Epson Corp. GT-X770 [Perfection V500]
$ scanimage -L
device `epkowa:interpreter:001:008' is a Epson Perfection V500 flatbed scanner
$ 
```

**Additional context**
1. I've used `SANE_DEBUG_SANEI_USB=3` to view the list of USB IDs being checked for, and `04b8:0130` isn't included.
2. I can run the `scanimage` from 19.09 successfully like this:
```shellsession
$ . /nix/var/nix/profiles/system-369-link/etc/set-environment
$ /nix/var/nix/profiles/system-369-link/sw/bin/scanimage -L
device `epkowa:interpreter:001:008' is a Epson Perfection V500 flatbed scanner
$ 
```

**Notify maintainers**
@symphorien @dominikh

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.42, NixOS, 20.03.1964.a808fe4fcde (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1964.a808fe4fcde"`
 - channels($USER): `"nixpkgs-20.09pre226664.002d38783ab"`
 - nixpkgs: `$HOME/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: epkowa
# a list of nixos modules affected by the problem
module:
```

**Comment by symphorien** [comment] 2020-05-26 19:30
I have no idea what could be the cause as there is no significant commit on epkowa from 19.09 to 20.03, neither on the sane module.
I don't have access to hardware to test at the moment, so I can't investigate much more the quick look I gave at the code...

Maybe try bisecting nixos if you have time to spend ?

**Comment by symphorien** [comment] 2020-06-04 21:01
I could reproduce and I think it is fixed by e22eb2d7b5078f78655e478dcee3a8298821edf3

**Comment by neilmayhew** [comment] 2020-06-07 14:28
Thank you. That does seem to fix it. I had already noticed the existence of that patch, but didn't realize that 20.03 didn't have it in. When I run `scanimage` from today's `nixos-unstable-small` it recognizes my scanner.

Is there any chance of having this backported to 20.03?

**Comment by Ekleog** [comment] 2020-06-07 16:41
With #82909, the backport should now be done, so I'm going to close :) Feel free to complain and/or reopen if the issue is still present!

**Closed by Ekleog** 2020-06-07 16:41 UTC
Labels: 0.kind: bug, 6.topic: hardware

**Comment by neilmayhew** [comment] 2020-06-07 18:32
It's been merged into `master` but not into `release/nixos-20.03`:

```shellsession
$ git merge-base origin/release-20.03 e22eb2d7b5078f78655e478dcee3a8298821edf3
7c0d3f6f70c7a55e8c988e9d6882820b9d26171d
$ git merge-base origin/master e22eb2d7b5078f78655e478dcee3a8298821edf3
e22eb2d7b5078f78655e478dcee3a8298821edf3
```

I'm reopening because I think it's important that this gets into 20.03.

**Comment by neilmayhew** [comment] 2020-06-07 18:36
Correction: I'd _like_ to reopen it, but I don't have the necessary permission level.

**Comment by Ekleog** [comment] 2020-06-07 18:59
Ugh I linked the last wrong PR, sorry! I meant https://github.com/NixOS/nixpkgs/pull/89506 :)

(As for the permission level… that's weird, I thought everyone had the right to reopen issues. Well, if you want to reopen feel free to ask and I'll do :))

**Comment by neilmayhew** [comment] 2020-06-07 20:57
Thanks! That's great. It hasn't hit the channels yet, but I tested it with a NixOS built from the current state of `release-20.03` and everything's fine.
