### ISSUE TITLE
Package request: Mesen

### ISSUE THREAD

**Issue by GuterBenutzername** [NixOS/nixpkgs#367437] opened 2024-12-22 19:45 UTC
## Project description

Multi-system emulator with high accuracy

## Metadata

* homepage URL: [mesen.ca](https://www.mesen.ca/)
* source URL: [Github](https://github.com/SourMesen/Mesen2)
* license: GPLv3
* platforms: Linux, Darwin

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jackwilsdon** [comment] 2024-12-22 23:53
Already requested in #301132 and there's an open PR for it: #301666

**Comment by pluiedev** [comment] 2024-12-24 16:47
Closing as duplicate of #301132

**Closed by pluiedev** 2024-12-24 16:47 UTC
Labels: 0.kind: packaging request
