### ISSUE TITLE
Steam Controller unable to pair

### ISSUE THREAD

**Issue by adz21c** [NixOS/nixpkgs#10646] opened 2015-10-27 13:00 UTC
Hi,
I've recently received my pre-order for a steam controller, but I can't seem to get it working. I plug in the USB adapter and it is identified, however I can't seem to connect the controller within steam. I did some research and apparently steam needs some extra read+write permission which can be handled via udev as per http://askubuntu.com/questions/686214/how-do-i-get-a-steam-controller-working. I've added this to services.udev.extraRules (adjusting the group as appropriate) and still no luck. I also tried changing permissions of uinput directly and I still have no luck. After further research I found nixos has had to jump through a few hoops to get steam to play nice by using chroot, which I suspect is the source of my problems but I am unsure how to proceed from here. Any ideas?

Thanks,
Adam

## Notes
I do have steam working with a PS4 controller via a USB bluetooth adapter. However, the controller must be connected before steam starts as it is unable to pick up the controller dynamically.

### Output of usb-devices
```
T:  Bus=01 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#=  3 Spd=12  MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=28de ProdID=1142 Rev=00.01
S:  Manufacturer=Valve Software
S:  Product=Steam Controller
C:  #Ifs= 5 Cfg#= 1 Atr=a0 MxPwr=100mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=01 Prot=01 Driver=usbhid
I:  If#= 1 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid
I:  If#= 2 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid
I:  If#= 3 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid
I:  If#= 4 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid
```

**Comment by cstrahan** [comment] 2015-11-21 22:49
I'd like to buy and use a Steam controller, so I'll assign this to myself. I'll probably have to wait a week or so for the controller to arrive, though.

**Comment by adz21c** [comment] 2015-11-21 23:27
That's cool. I've had a play today and I am not really getting anywhere, but I'm a little out of my depth as to where to start. I tried adding pciutils as a dependency to steam as I could see error messages on the console output but it made no difference. I also tried installing steam from unstable and that didn't help. I tried to compare the console output of steam using kubuntu and the only difference I could see is when it sees the device it adds a line indicating it knows it is a steam controller (I don't remember the text right now, just that the line began "!!").

Any pointers?

**Comment by domenkozar** [comment] 2015-11-22 19:46
@adz21c mine had been shipped on Friday, so it should be here next week and I'll test it out.

**Comment by domenkozar** [comment] 2015-12-01 11:04
I've also got it now and indeed it doesn't work. I'll look into it.

**Comment by domenkozar** [comment] 2015-12-01 11:09
I've added the following to `configuration.nix`:

```
    services.udev.extraRules = ''
      SUBSYSTEM=="usb", ATTRS{idVendor}=="28de", MODE="0666"
      KERNEL=="uinput", MODE="0660", GROUP="steam", OPTIONS+="static_node=uinput"
    '';
    boot.kernelModules = [ "uinput" ];
```

but it still doesn't recognize it. We have to first test it works outside if chrooted steam, then we can ping @abbradar for help :)

**Comment by domenkozar** [comment] 2015-12-01 11:23
I don't think it's a steam issue, if I plug it in with usb cable, I can use it as a mouse on my desktop.

**Comment by abbradar** [comment] 2015-12-01 13:57
Maybe this: https://aur.archlinux.org/packages/steamcontroller-udev/ can help you?

**Comment by abbradar** [comment] 2015-12-01 13:59
Also,
> 
The new release of the upstream steam package (1.0.0.50-2) also contains a udev rules file, but without the uinput rule.
We may want to take it from here. I don't have the device though, so I can't help by anything but links ^_^.

**Comment by domenkozar** [comment] 2015-12-01 14:23
that's exactly the same as above udev rules, so I'm confused why it doesn't "work"

**Comment by adz21c** [comment] 2015-12-02 18:42
@domenkozar I have the same thing. However, I don't think this is necessarily an indication that it isn't a steam issue. I just tested on kubuntu and the mouse feature on the controller doesn't work until I have paired the device inside steam. Once I've done that all is well while steam is running. As soon as I close steam the mouse feature seases to work.

**Comment by cstrahan** [comment] 2015-12-24 03:32
I received my controller, so I can hopefully give this ago soon. Something to keep in mind is that there are firmware updates that are only available if you opt-in to the Steam beta client.

**Comment by pstn** [comment] 2016-01-15 15:44
I own a steam controller and can reproduce the behaviour that I can use it wired but not wireless.

If anybody wants me to try something out, I'll do it.

**Comment by adz21c** [comment] 2016-01-29 13:43
I've had some success. I think the problem might be an issue with udev. I identified the controller on /dev/bus/usb (using lsusb) and applied 666 permissions. After this the controller seems to be able to pair and function as a mouse etc. My understanding is this is exactly what `SUBSYSTEM=="usb", ATTRS{idVendor}=="28de", MODE="0666"` should be doing for me. I returned the permissions to their previous state (and tested via reboots) and executed `sudo udevadm trigger` and sure enough the permissions were changed as required. I assume this also applied the other udev rules @domenkozar mentioned in an earlier post but I don't really know how to confirm this. The question then is why udev is not applying the rules specified automatically? I've tested with booting, `nixos-rebuild switch` and plugging in the device, the permissions are never applied. I removed the extraRules and attempted `udevadm trigger` then no permissions were applied, so it is definitely using the extraRules when `udevadm trigger` is called. How does this progress from here?

**Comment by pstn** [comment] 2016-01-29 15:21
I can confirm that behaviour. The device node does not become world writeable when I connect the device but as soon as I execute ```sudo udevadm trigger``` but the group always gets set correctly.

We need to set the file to world writeable because there are only a limited number of groups in the chroot. Most of the time this means that the device node is owned by nobody:nogroup there. After discovering that my primary group is in the chroot I set that group up as the owner of the device node and the controller startet to work as expected.

I guess the probable fix here is to transfer all the groups to the chroot, or create a configuration option ```foo.steamcontroller.enabled``` that adds the udev rules with a custom group of our chosing e.g. ```steamcontroller``` that also exists in the chroot and ```foo.steamcontroller.users``` that adds all the users defined in a list to this group.

**Comment by abbradar** [comment] 2016-01-31 11:21
Hm, could you show `udevadm info /dev/bus/usb/BUS/DEV` for the controller with those rules enabled? Also I suppose `udevadm monitor` log would be helpful (disconnect the controller, start the monitor and plug it back).

**Comment by adz21c** [comment] 2016-01-31 11:59
```
$sudo udevadm monitor
monitor will print the received events for:
UDEV - the event which udev sends out after rule processing
KERNEL - the kernel uevent

KERNEL[612.302467] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1 (usb)
KERNEL[612.302674] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0 (usb)
KERNEL[612.304198] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/0003:28DE:1142.0004 (hid)
KERNEL[612.304328] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/0003:28DE:1142.0004/input/input10 (input)
KERNEL[612.304347] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/0003:28DE:1142.0004/input/input10/event7 (input)                                                                                                                                                 
KERNEL[612.304434] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/0003:28DE:1142.0004/input/input10/mouse1 (input)                                                                                                                                                 
KERNEL[612.304569] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/0003:28DE:1142.0004/hidraw/hidraw3 (hidraw)                                                                                                                                                      
KERNEL[612.304582] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.1 (usb)                                                                                                                                                                                            
KERNEL[612.305322] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.1/0003:28DE:1142.0005 (hid)                                                                                                                                                                        
KERNEL[612.306453] add      /class/usbmisc (class)                                                                                                                                                                                                                             
KERNEL[612.306503] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.1/usbmisc/hiddev0 (usbmisc)                                                                                                                                                                        
KERNEL[612.306554] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.1/0003:28DE:1142.0005/hidraw/hidraw4 (hidraw)                                                                                                                                                      
KERNEL[612.306566] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.2 (usb)                                                                                                                                                                                            
UDEV  [612.306744] add      /class/usbmisc (class)                                                                                                                                                                                                                             
KERNEL[612.307438] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.2/0003:28DE:1142.0006 (hid)                                                                                                                                                                        
KERNEL[612.308624] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.2/usbmisc/hiddev1 (usbmisc)                                                                                                                                                                        
KERNEL[612.308709] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.2/0003:28DE:1142.0006/hidraw/hidraw5 (hidraw)                                                                                                                                                      
KERNEL[612.308720] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.3 (usb)                                                                                                                                                                                            
KERNEL[612.309504] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.3/0003:28DE:1142.0007 (hid)                                                                                                                                                                        
KERNEL[612.310714] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.3/usbmisc/hiddev2 (usbmisc)                                                                                                                                                                        
KERNEL[612.310764] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.3/0003:28DE:1142.0007/hidraw/hidraw6 (hidraw)                                                                                                                                                      
KERNEL[612.310791] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.4 (usb)                                                                                                                                                                                            
KERNEL[612.311657] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.4/0003:28DE:1142.0008 (hid)                                                                                                                                                                        
KERNEL[612.312777] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.4/usbmisc/hiddev3 (usbmisc)                                                                                                                                                                        
KERNEL[612.312805] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.4/0003:28DE:1142.0008/hidraw/hidraw7 (hidraw)                                                                                                                                                      
UDEV  [612.313078] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1 (usb)                                                                                                                                                                                                    
UDEV  [612.316263] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0 (usb)                                                                                                                                                                                            
UDEV  [612.316276] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.1 (usb)                                                                                                                                                                                            
UDEV  [612.316321] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.3 (usb)                                                                                                                                                                                            
UDEV  [612.316348] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.2 (usb)                                                                                                                                                                                            
UDEV  [612.325683] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.1/usbmisc/hiddev0 (usbmisc)                                                                                                                                                                        
UDEV  [612.325699] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.4 (usb)                                                                                                                                                                                            
UDEV  [612.326130] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.4/usbmisc/hiddev3 (usbmisc)                                                                                                                                                                        
UDEV  [612.326141] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.1/0003:28DE:1142.0005 (hid)                                                                                                                                                                        
UDEV  [612.326219] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/0003:28DE:1142.0004 (hid)                                                                                                                                                                        
UDEV  [612.326363] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.4/0003:28DE:1142.0008 (hid)                                                                                                                                                                        
UDEV  [612.326579] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/0003:28DE:1142.0004/hidraw/hidraw3 (hidraw)                                                                                                                                                      
UDEV  [612.326613] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.1/0003:28DE:1142.0005/hidraw/hidraw4 (hidraw)                                                                                                                                                      
UDEV  [612.326649] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.4/0003:28DE:1142.0008/hidraw/hidraw7 (hidraw)                                                                                                                                                      
UDEV  [612.326708] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.3/usbmisc/hiddev2 (usbmisc)                                                                                                                                                                        
UDEV  [612.326773] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.2/usbmisc/hiddev1 (usbmisc)                                                                                                                                                                        
UDEV  [612.326814] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.2/0003:28DE:1142.0006 (hid)                                                                                                                                                                        
UDEV  [612.326974] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.2/0003:28DE:1142.0006/hidraw/hidraw5 (hidraw)                                                                                                                                                      
UDEV  [612.327134] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/0003:28DE:1142.0004/input/input10 (input)                                                                                                                                                        
UDEV  [612.327477] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.3/0003:28DE:1142.0007 (hid)                                                                                                                                                                        
UDEV  [612.327634] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.3/0003:28DE:1142.0007/hidraw/hidraw6 (hidraw)                                                                                                                                                      
UDEV  [612.328647] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/0003:28DE:1142.0004/input/input10/mouse1 (input)                                                                                                                                                 
UDEV  [612.328669] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/0003:28DE:1142.0004/input/input10/event7 (input)

$ ls -l /dev/bus/usb/003/002
crw-rw-r-- 1 root root 189, 257 Jan 31 11:43 002

$ sudo udevadm info /dev/bus/usb/003/002
P: /devices/pci0000:00/0000:00:14.0/usb3/3-1
N: bus/usb/003/002
E: BUSNUM=003
E: DEVNAME=/dev/bus/usb/003/002
E: DEVNUM=002
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb3/3-1
E: DEVTYPE=usb_device
E: DRIVER=usb
E: ID_BUS=usb
E: ID_MODEL=Steam_Controller
E: ID_MODEL_ENC=Steam\x20Controller
E: ID_MODEL_ID=1142
E: ID_REVISION=0001
E: ID_SERIAL=Valve_Software_Steam_Controller
E: ID_USB_INTERFACES=:030101:030000:
E: ID_VENDOR=Valve_Software
E: ID_VENDOR_ENC=Valve\x20Software
E: ID_VENDOR_ID=28de
E: MAJOR=189
E: MINOR=257
E: PATH=/nix/store/j5js1wfqjm4snbzmjdzhy99rljnwkqkb-udev-path/bin:/nix/store/j5js1wfqjm4snbzmjdzhy99rljnwkqkb-udev-path/sbin
E: PRODUCT=28de/1142/1
E: SUBSYSTEM=usb
E: TYPE=0/0/0
E: USEC_INITIALIZED=612302475
```

**Comment by abbradar** [comment] 2016-01-31 12:15
And your `extraRules` is...?

**Comment by adz21c** [comment] 2016-01-31 13:00
```
services.udev.extraRules = ''
      SUBSYSTEM=="usb", ATTRS{idVendor}=="28de", MODE="0666"
      KERNEL=="uinput", MODE="0660", GROUP="steam", OPTIONS+="static_node=uinput"
    '';
```

**Comment by abbradar** [comment] 2016-01-31 15:31
Hm, sadly my udev expertise doesn't extend further. Who can we ping for more udev advices?

**Comment by adz21c** [comment] 2016-02-12 00:48
Right, I think I've found the last piece of the puzzle, but it doesn't explain why `udevadm trigger` works.

The problem is when using `services.udev.extraRules` the rule file is prefixed with 10, which means it's one of the first set of rules to be executed. Rules defined in systemd then override the permissions rule which gave the impression nothing has happened. I've added the below to my nix config and it seems to have done the trick (note I found an extra rule on the Gentoo wiki for some sensor).
```
environment.systemPackages = with pkgs; [
  pkgs.steamcontroller-udev-rules
];

nixpkgs.config.packageOverrides = pkgs: {
  steamcontroller-udev-rules = pkgs.writeTextFile {
    name = "steamcontroller-udev-rules";
    text = ''
      # This rule is needed for basic functionality of the controller in
      # Steam and keyboard/mouse emulation
      SUBSYSTEM=="usb", ATTRS{idVendor}=="28de", MODE="0666"

      # This rule is necessary for gamepad emulation; make sure you
      # replace 'pgriffais' with the username of the user that runs Steam
      KERNEL=="uinput", MODE="0660", GROUP="wheel", OPTIONS+="static_node=uinput"
      
      # HTC Vive HID Sensor naming and permissioning
      KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="0bb4", ATTRS{idProduct}=="2c87", MODE="0666"
    '';
    destination = "/etc/udev/rules.d/99-steamcontroller.rules";
  };
};

services.udev.packages = [ pkgs.steamcontroller-udev-rules ];
```
It is also worth noting (although I am unsure if it makes a difference) that when looking at the `udevadm monitor` output that the 4.3 kernel seems to introduce extra events/devices/attributes/whatever than with the 3.x kernel, so I've added `boot.kernelPackages = pkgs.linuxPackages_latest;` as well. The additional output is below.
```
KERNEL[6040.944286] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/0003:28DE:1142.005E/input/input39/input39::numlock (leds)
KERNEL[6040.944302] change   /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/0003:28DE:1142.005E/input/input39/input39::numlock (leds)
KERNEL[6040.944307] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/0003:28DE:1142.005E/input/input39/input39::capslock (leds)
KERNEL[6040.944312] change   /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/0003:28DE:1142.005E/input/input39/input39::capslock (leds)
KERNEL[6040.944317] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/0003:28DE:1142.005E/input/input39/input39::scrolllock (leds)
KERNEL[6040.944321] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/0003:28DE:1142.005E/input/input39/input39::compose (leds)
KERNEL[6040.944325] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/0003:28DE:1142.005E/input/input39/input39::kana (leds)
KERNEL[6040.944330] change   /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/0003:28DE:1142.005E/input/input39/input39::kana (leds)
```
I think the take away from this is the steam package wants a udev rules file with an appropriately high prefix and `services.udev.extraRules` either wants a higher prefix or to take the prefix as an option or take an array of rule files specifying content and name in order to be useful (my opinion that is :)).

If anyone is interested how I tracked this down I executed `udevadm test /devices/pci0000:00/0000:00:14.0/usb3/3-1` and amongst the noise of information noticed the below lines of interest
```
$ sudo udevadm test /devices/pci0000:00/0000:00:14.0/usb3/3-1
calling: test
version 217
...
Reading rules file: /nix/store/svz0hjd6in3kdapyazhfygqiq85rvb70-udev-rules/10-local.rules
...
Reading rules file: /nix/store/vnzbil4i5m75jka0hq1145msf511vyiv-systemd-217/lib/udev/rules.d/50-udev-default.rules
...
MODE 0666 /nix/store/svz0hjd6in3kdapyazhfygqiq85rvb70-udev-rules/10-local.rules:19
...
MODE 0664 /nix/store/vnzbil4i5m75jka0hq1145msf511vyiv-systemd-217/lib/udev/rules.d/50-udev-default.rules:38
...
``

**Comment by abbradar** [comment] 2016-02-17 01:58
https://github.com/NixOS/nixpkgs/pull/13059, I've bumped into this myself with some other piece of hardware.

**Comment by abbradar** [comment] 2016-02-17 02:18
Also, I think I have an idea why `udevadm trigger` helps you -- you don't specify `ACTION=="add"` so your rule fires every time there's something happening with the device, and other rules set mode and group only on ADD.

**Comment by abbradar** [comment] 2016-02-19 15:53
@adz21c, do I understand correctly that now the controller works correctly for you?

**Comment by adz21c** [comment] 2016-02-20 00:31
@abbradar Yes, best I can tell it is working perfectly.

**Comment by abbradar** [comment] 2016-02-20 00:32
OK, let's close this. I want to merge #13059 in some form or the other to prevent future confusion.

**Closed by abbradar** 2016-02-20 00:32 UTC
Labels: 0.kind: bug, 2.status: work-in-progress, 6.topic: nixos, 9.needs: feedback, 9.needs: package (update)
