### ISSUE TITLE
Build failure: waybar in nixos unstable

### ISSUE THREAD

**Issue by ca5ua1** [NixOS/nixpkgs#297419] opened 2024-03-20 09:28 UTC
### Steps To Reproduce

1. build system with waybar in unstable nixos

### Build log

```
error: builder for '/nix/store/wp5d5205rv1kdz2rrz4jgknqjy6y2pm5-waybar-0.10.0.drv' failed with exit code 1;
       last 10 log lines:
       > Run-time dependency libudev found: YES 255
       > Run-time dependency libevdev found: YES 1.13.1
       > Run-time dependency libmpdclient found: YES 2.22
       > Run-time dependency xkbregistry found: YES 1.5.0
       > Run-time dependency jack found: YES 1.9.22
       > Run-time dependency wireplumber-0.4 found: NO (tried pkgconfig)
       >
       > meson.build:95:17: ERROR: Dependency "wireplumber-0.4" not found, tried pkgconfig
       >
       > A full log can be found at /build/source/build/meson-logs/meson-log.txt
       For full logs, run 'nix log /nix/store/wp5d5205rv1kdz2rrz4jgknqjy6y2pm5-waybar-0.10.0.drv'.
error: 1 dependencies of derivation '/nix/store/567iamqjrkw0pkshxz51sy0nm230lahv-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8w2h0j4s25ld98ww3zf02hybdl378lxr-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gy22ixl76a5brlnhspalw7yb4pycj593-unit-script-waybar-start.drv' failed to build
error: 1 dependencies of derivation '/nix/store/00apvzpn7mhwh4m69i9nwnld5y4lmqaq-nixos-system-Casual-PC-24.05.20240319.b06025f.drv' failed to build

```

### Additional context

I guess waybar wants wireplumber v0.4, but unstable have v0.5

### Notify maintainers

@FlorianFranzen Florian Franzen <Florian.Franzen@gmail.com>
@jtbx  Jeremy Baxter <jtbx@duck.com>
 Bernardo Meurer <meurerbernardo@gmail.com>
@minijackson Rémi Nicole <minijackson@riseup.net>
Erik Rodriguez <erik@rodgz.com>
@Synthetica9 Patrick Hilhorst <nix@hilhorst.be>
@khaneliman Austin Horstman <khaneliman12@gmail.com>

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.0-zen1, NixOS, 24.05 (Uakari), 24.05.20240314.d691274`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05, nixpkgs"`
 - channels(casual): `""`
 - nixpkgs: `/home/casual/.nix-defexpr/channels/nixpkgs`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Brisingr05** [comment] 2024-03-20 09:32
Wait for #297158 to get merged into unstable. Track it [here](https://nixpk.gs/pr-tracker.html?pr=297158).

**Comment by 9p4** [comment] 2024-03-20 13:54
Duplicate of #297261

**Comment by leona-ya** [comment] 2024-03-20 15:00
Closing as it's already fixed on master.

**Closed by leona-ya** 2024-03-20 15:00 UTC
Labels: 0.kind: build failure
