### ISSUE TITLE
Budgie-Desktop

### ISSUE THREAD

**Issue by Marc12O** [NixOS/nixpkgs#191580] opened 2022-09-16 23:51 UTC
**Project description**
Budgie is a Desktop Environment

**Metadata**

* homepage URL: https://github.com/BuddiesOfBudgie/budgie-desktop
* source URL: https://github.com/BuddiesOfBudgie/budgie-desktop
* license: gpl2
* platforms: linux

**Comment by OPNA2608** [comment] 2022-09-17 01:17
Duplicate of #190192.

**Closed** 2022-09-17 14:08 UTC
Labels: 0.kind: packaging request
