### ISSUE TITLE
Notifications not shown by default when using XFCE4

### ISSUE THREAD

**Issue by joepie91** [NixOS/nixpkgs#21266] opened 2016-12-18 19:49 UTC
## Issue description

When selecting XFCE as my desktop manager, I do not see any notifications by default, and there's no `org.freedesktop.Notifications` DBus service available. It appears that while `xfce.xfce4notifyd` is *installed* correctly, there's no corresponding service or anything else to make it run automatically with the rest of my system.

When running `xfce4-notifyd`, it appears to work fine, so the issue is limited to it not being run automatically.

### Steps to reproduce

The following is the relevant part of my system configuration, for selecting XFCE4:

```nix
    services = {
        xserver.desktopManager.xfce = {
            enable = true;
            thunarPlugins = with packages; [
                nixpkgs.xfce.thunar-archive-plugin
                nixpkgs.xfce.thunar_volman
            ];
        };

        # ...
    };
```

## Technical details

* System: 16.09.1272.81428dd (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 16.09.1272.81428dd

**Comment by vcunat** [comment] 2016-12-19 08:14
Hmm, I thought this used to work.  Xfce just adds stuff to `systemPackages` and expects dbus to find `dbus-1/services` in there.  Maybe we (now) have to use `services.dbus.packages`...

**Comment by joepie91** [comment] 2016-12-19 13:28
The description for the `services.dbus.packages`:

> Packages whose D-Bus configuration files should be included in the configuration of the D-Bus system-wide or session-wide message bus. Specifically, files in the following directories will be included into their respective DBus configuration paths: pkg/etc/dbus-1/system.d pkg/share/dbus-1/system-services pkg/etc/dbus-1/session.d pkg/share/dbus-1/services

... appears to confirm that requirement. Maybe this was changed at some point?

If this is indeed the issue, I expect many more packages will be affected, and there should probably be some kind of scan done to find other packages that a) produce DBus configuration but b) are not added to `services.dbus.packages`.

**Comment by joachifm** [comment] 2016-12-19 14:58
Is https://github.com/NixOS/nixpkgs/pull/20871 relevant?

**Comment by vcunat** [comment] 2016-12-19 15:15
Yes, I think that might fix this issue.

**Comment by yegortimoshenko** [comment] 2017-12-19 12:08
It seems to have been fixed:

```
$ nix-env -iA nixos.libnotify
$ notify-send It works!
```

**Comment by yegortimoshenko** [comment] 2017-12-19 12:22
@joepie91 has switched to KDE, #20871 has been merged in, and I can't reproduce, so closing.

**Closed by yegortimoshenko** 2017-12-19 12:22 UTC
Labels: 6.topic: xfce
