### ISSUE TITLE
Cannot build gdal for Python 3.6

### ISSUE THREAD

**Issue by joseph-long** [NixOS/nixpkgs#30237] opened 2017-10-08 22:49 UTC
I'm using LnL7/nix-darwin and added Pelican to my list of Python packages to install. This brings in a dependency on Django (?!) and some GIS libs (?!?), one of which fails to build.

```
/nix/store/5j8r4n35rzbwg95ayrfwn5ir07c1v6f6-bash-4.4-p12/bin/bash /private/var/folders/zr/vj346_0x6s50225tpfchjbg00000gn/T/nix-build-python3.6-gdal-2.2.1.drv-0/gdal-2.2.1/libtool --mode=link	c++ -std=gnu++11  gnmanalyse.lo  /private/var/folders/zr/vj346_0x6s50225tpfchjbg00000gn/T/nix-build-python3.6-gdal-2.2.1.drv-0/gdal-2.2.1/libgdal.la -o gnmanalyse
libtool: link: c++ -std=gnu++11 .libs/gnmanalyse.o -o .libs/gnmanalyse  /private/var/folders/zr/vj346_0x6s50225tpfchjbg00000gn/T/nix-build-python3.6-gdal-2.2.1.drv-0/gdal-2.2.1/.libs/libgdal.dylib -L/nix/store/q7rr9lwf67ynriywcwhz037pvxdd2iqh-proj-4.9.3/lib -L/nix/store/zgpr4kw6qag7ibay1m1pw3qzyyzra1xz-poppler-glib-0.56.0-dev/lib -L/nix/store/y6c4pgznfh4l0f5qlasj7wqy0dmbs01q-geos-3.6.1/lib -L/nix/store/v3y9whvkck77hfdlilg31nvk0cwj7y2r-sqlite-3.20.0-dev/lib -L/nix/store/9a9r6cj2shs2z8c3bfncadyr8wbhq06y-netcdf-4.4.1.1/lib -L/nix/store/dp3nyg7ngxd4gaq4cpvgchp6vz0hn12n-hdf-4.2.12-dev -L/nix/store/kilhn21farrlib2vcqw1drzdi6ipl615-libjpeg-8d-dev -L/nix/store/kilhn21farrlib2vcqw1drzdi6ipl615-libjpeg-8d-dev/lib -L/nix/store/s442aif8ss9qnq6fgl5m7l42j5vvf29i-libgeotiff-1.4.2/lib -L/nix/store/kwsdbmn2md42h6pw8hdviyrg66z4al7r-libtiff-4.0.8-dev/lib -L/nix/store/cwnf6ww2zdlnj9z98npx2qs17pa7fpwa-libpng-apng-1.6.31-dev -L/nix/store/cwnf6ww2zdlnj9z98npx2qs17pa7fpwa-libpng-apng-1.6.31-dev/lib -L/nix/store/kqq697hqnn56qa9iikhpjqfs3zhd8sq6-postgresql-9.6.5-lib/lib -L/nix/store/vyjkp26av9ipr0y4h2x7k4xhsbrci9c5-zlib-1.2.11-dev -L/nix/store/vyjkp26av9ipr0y4h2x7k4xhsbrci9c5-zlib-1.2.11-dev/lib -L/nix/store/22nki83cqgcbqsw4zq5mba1af0mj6xdm-libspatialite-4.2.0/lib -L/nix/store/zccr1zxijb3iqh17c0arzzv87dgsw53s-libxml2-2.9.5/lib -L/nix/store/y5cishcwgnaz3fd8yv5bxzad2fwiymxm-curl-7.55.1/lib -L/nix/store/gyrkqis26h1w82v9y2cncym5jfr3w1x7-zlib-1.2.11/lib -L/nix/store/kc34zd7cnjfmxg3h8j2q50k5lwl1hwys-openssl-1.0.2l/lib -L/nix/store/h6m9v1gfvc9az7ylblgmjm1ps52ixqyc-libssh2-1.8.0/lib -L/nix/store/5mlhilicap00y8cjd8i36zvlh48xfgvb-mariadb-client-10.1.26/lib -lpoppler -lexpat -lopenjp2 /nix/store/9a9r6cj2shs2z8c3bfncadyr8wbhq06y-netcdf-4.4.1.1/lib/libnetcdf.dylib -lhdf5_hl -lhdf5 -lmfhdf -lhdf /nix/store/s442aif8ss9qnq6fgl5m7l42j5vvf29i-libgeotiff-1.4.2/lib/libgeotiff.dylib -ljpeg -ltiff -lpng -lpq /nix/store/22nki83cqgcbqsw4zq5mba1af0mj6xdm-libspatialite-4.2.0/lib/libspatialite.dylib /nix/store/zccr1zxijb3iqh17c0arzzv87dgsw53s-libxml2-2.9.5/lib/libxml2.dylib -ldl /nix/store/q7rr9lwf67ynriywcwhz037pvxdd2iqh-proj-4.9.3/lib/libproj.dylib -lpthread -lm -lsqlite3 /nix/store/y6c4pgznfh4l0f5qlasj7wqy0dmbs01q-geos-3.6.1/lib/libgeos_c.dylib /nix/store/y6c4pgznfh4l0f5qlasj7wqy0dmbs01q-geos-3.6.1/lib/libgeos.dylib /nix/store/y5cishcwgnaz3fd8yv5bxzad2fwiymxm-curl-7.55.1/lib/libcurl.dylib /nix/store/h6m9v1gfvc9az7ylblgmjm1ps52ixqyc-libssh2-1.8.0/lib/libssh2.dylib -liconv -lmysqlclient -lz -lssl -lcrypto
ld: warning: directory not found for option '-L/nix/store/kilhn21farrlib2vcqw1drzdi6ipl615-libjpeg-8d-dev/lib'
make[1]: Leaving directory '/private/var/folders/zr/vj346_0x6s50225tpfchjbg00000gn/T/nix-build-python3.6-gdal-2.2.1.drv-0/gdal-2.2.1/apps'
(cd swig; make build)
make[1]: Entering directory '/private/var/folders/zr/vj346_0x6s50225tpfchjbg00000gn/T/nix-build-python3.6-gdal-2.2.1.drv-0/gdal-2.2.1/swig'
for dir in python ; do (cd $dir; make build) || exit; done
make[2]: Entering directory '/private/var/folders/zr/vj346_0x6s50225tpfchjbg00000gn/T/nix-build-python3.6-gdal-2.2.1.drv-0/gdal-2.2.1/swig/python'
rm -f setup_vars.ini
echo 'GNM_ENABLED=yes' >> setup_vars.ini
python setup.py build
running build
running build_py
creating build
creating build/lib.macosx-10.6-x86_64-3.6
copying gdal.py -> build/lib.macosx-10.6-x86_64-3.6
copying ogr.py -> build/lib.macosx-10.6-x86_64-3.6
copying osr.py -> build/lib.macosx-10.6-x86_64-3.6
copying gdalconst.py -> build/lib.macosx-10.6-x86_64-3.6
copying gnm.py -> build/lib.macosx-10.6-x86_64-3.6
copying gdalnumeric.py -> build/lib.macosx-10.6-x86_64-3.6
creating build/lib.macosx-10.6-x86_64-3.6/osgeo
copying osgeo/gnm.py -> build/lib.macosx-10.6-x86_64-3.6/osgeo
copying osgeo/__init__.py -> build/lib.macosx-10.6-x86_64-3.6/osgeo
copying osgeo/gdalnumeric.py -> build/lib.macosx-10.6-x86_64-3.6/osgeo
copying osgeo/osr.py -> build/lib.macosx-10.6-x86_64-3.6/osgeo
copying osgeo/gdal.py -> build/lib.macosx-10.6-x86_64-3.6/osgeo
copying osgeo/ogr.py -> build/lib.macosx-10.6-x86_64-3.6/osgeo
copying osgeo/gdal_array.py -> build/lib.macosx-10.6-x86_64-3.6/osgeo
copying osgeo/gdalconst.py -> build/lib.macosx-10.6-x86_64-3.6/osgeo
Fixing build/lib.macosx-10.6-x86_64-3.6/gdal.py build/lib.macosx-10.6-x86_64-3.6/ogr.py build/lib.macosx-10.6-x86_64-3.6/osr.py build/lib.macosx-10.6-x86_64-3.6/gdalconst.py build/lib.macosx-10.6-x86_64-3.6/gnm.py build/lib.macosx-10.6-x86_64-3.6/gdalnumeric.py build/lib.macosx-10.6-x86_64-3.6/osgeo/gnm.py build/lib.macosx-10.6-x86_64-3.6/osgeo/__init__.py build/lib.macosx-10.6-x86_64-3.6/osgeo/gdalnumeric.py build/lib.macosx-10.6-x86_64-3.6/osgeo/osr.py build/lib.macosx-10.6-x86_64-3.6/osgeo/gdal.py build/lib.macosx-10.6-x86_64-3.6/osgeo/ogr.py build/lib.macosx-10.6-x86_64-3.6/osgeo/gdal_array.py build/lib.macosx-10.6-x86_64-3.6/osgeo/gdalconst.py
Skipping optional fixer: ws_comma
Fixing build/lib.macosx-10.6-x86_64-3.6/gdal.py build/lib.macosx-10.6-x86_64-3.6/ogr.py build/lib.macosx-10.6-x86_64-3.6/osr.py build/lib.macosx-10.6-x86_64-3.6/gdalconst.py build/lib.macosx-10.6-x86_64-3.6/gnm.py build/lib.macosx-10.6-x86_64-3.6/gdalnumeric.py build/lib.macosx-10.6-x86_64-3.6/osgeo/gnm.py build/lib.macosx-10.6-x86_64-3.6/osgeo/__init__.py build/lib.macosx-10.6-x86_64-3.6/osgeo/gdalnumeric.py build/lib.macosx-10.6-x86_64-3.6/osgeo/osr.py build/lib.macosx-10.6-x86_64-3.6/osgeo/gdal.py build/lib.macosx-10.6-x86_64-3.6/osgeo/ogr.py build/lib.macosx-10.6-x86_64-3.6/osgeo/gdal_array.py build/lib.macosx-10.6-x86_64-3.6/osgeo/gdalconst.py
Skipping optional fixer: ws_comma
running build_ext
building 'osgeo._gdal' extension
creating build/temp.macosx-10.6-x86_64-3.6
creating build/temp.macosx-10.6-x86_64-3.6/extensions
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Wno-error=unused-command-line-argument-hard-error-in-future -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -I/nix/store/s92mgxrgjaq7z5wyy2fz5x5x47lz7wcp-python3-3.6.2/include/python3.6m -I/nix/store/i901y2a8gx4pdi0qs3l7q5b5f3msxik3-python3.6-numpy-1.13.1/lib/python3.6/site-packages/numpy/core/include -I/private/var/folders/zr/vj346_0x6s50225tpfchjbg00000gn/T/nix-build-python3.6-gdal-2.2.1.drv-0/gdal-2.2.1/include -c extensions/gdal_wrap.cpp -o build/temp.macosx-10.6-x86_64-3.6/extensions/gdal_wrap.o
clang-4.0: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
warning: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Wunknown-warning-option]
extensions/gdal_wrap.cpp:3092:10: fatal error: 'stdexcept' file not found
#include <stdexcept>
         ^~~~~~~~~~~
1 warning and 1 error generated.
error: command 'clang' failed with exit status 1
make[2]: *** [GNUmakefile:68: build] Error 1
make[2]: Leaving directory '/private/var/folders/zr/vj346_0x6s50225tpfchjbg00000gn/T/nix-build-python3.6-gdal-2.2.1.drv-0/gdal-2.2.1/swig/python'
make[1]: *** [GNUmakefile:30: build] Error 2
make[1]: Leaving directory '/private/var/folders/zr/vj346_0x6s50225tpfchjbg00000gn/T/nix-build-python3.6-gdal-2.2.1.drv-0/gdal-2.2.1/swig'
make: *** [GNUmakefile:103: swig-modules] Error 2
builder for ‘/nix/store/62mbm0ddkf4ic1qdvnn6sxablcr4j09b-python3.6-gdal-2.2.1.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/lnssl2x73v2kzkav03bzdfx4918yi6ih-1.10-gis-libs.template.patch.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/f3r0d14hqm5dcdnscgly9d8fhn3bs091-python3.6-Django-1.11.5.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/m0cbs3l4ni5qprk44mfdr85spkdq47l2-python3.6-typogrify-2.0.7.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/899c7qwam8jyq6zwxljng8r0vs9zjaq1-python3.6-pelican-3.7.1.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/zxjn5mlz9sa5hn0crszpbishv5xikqb1-python3-3.6.2-env.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/hcbm1nhbf6saixmm4f2rg6kx2gr4hb0c-system-applications.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/sh3gb2rvvb34dybnmvnxs4fa9lsz95xq-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/i8dib3bzi6ys8ajx2pa9gg7ghbpmfdgm-darwin-system-18.03pre-git.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/i8dib3bzi6ys8ajx2pa9gg7ghbpmfdgm-darwin-system-18.03pre-git.drv’ failed
```

### Steps to reproduce

Run `nix-shell -p python36Packages.gdal`, wait a long time...

## Technical details

* System: macOS High Sierra + LnL7/nix-darwin
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: 18.03pre116939.d7d774deea
* Sandboxing enabled: `build-use-sandbox = false`

**Comment by jtojnar** [comment] 2017-10-09 01:50
Duplicate of #18194

**Comment by FRidh** [comment] 2017-10-09 16:17
Closing as duplicate.

**Closed by FRidh** 2017-10-09 16:17 UTC
