### ISSUE TITLE
networking.wireless.environmentFile doesn't accept complicated paths

### ISSUE THREAD

**Issue by SebastianStork** [NixOS/nixpkgs#280360] opened 2024-01-11 21:41 UTC
### Describe the bug
The [option](https://search.nixos.org/options?channel=23.11&show=networking.wireless.environmentFile&from=0&size=50&sort=relevance&type=packages&query=wireless.envir) "networking.wireless.environmentFile" doesn't accept paths with more than one "/". 

### Steps To Reproduce
Assign `./wireless.env` or `../wireless.env` to environmentFile (with the files in the correct locations ofc) and rebuild nixos. The rebuild is successful and the environment variables work correctly.
Assign `./secrets/wireless.env` or `../../wireless.env` to the attribute (from my config: `environmentFile = ../secrets/wireless.env;`) and rebuild . The rebuild causes a bunch of errors, among them `wpa_supplicant.service: Failed to load environment files: No such file or directory`.

### Expected behavior
The attribute should accept any kind of value with the data type path.

### Error Message
```console
restarting the following units: wpa_supplicant.service
Job for wpa_supplicant.service failed because of unavailable resources or another system error.
See "systemctl status wpa_supplicant.service" and "journalctl -xeu wpa_supplicant.service" for details.
warning: the following units failed: wpa_supplicant.service

× wpa_supplicant.service - WPA Supplicant instance
     Loaded: loaded (/etc/systemd/system/wpa_supplicant.service; enabled; preset: enabled)
     Active: failed (Result: resources) since Thu 2024-01-11 22:07:29 CET; 257ms ago
   Duration: 6min 19.172s
         IP: 0B in, 0B out
        CPU: 0

Jan 11 22:07:29 dell-laptop systemd[1]: wpa_supplicant.service: Deactivated successfully.
Jan 11 22:07:29 dell-laptop systemd[1]: Stopped WPA Supplicant instance.
Jan 11 22:07:29 dell-laptop systemd[1]: wpa_supplicant.service: Failed to load environment files: No such file or directory
Jan 11 22:07:29 dell-laptop systemd[1]: wpa_supplicant.service: Failed to run 'start' task: No such file or directory
Jan 11 22:07:29 dell-laptop systemd[1]: wpa_supplicant.service: Failed with result 'resources'.
Jan 11 22:07:29 dell-laptop systemd[1]: Failed to start WPA Supplicant instance.
Jan 11 22:07:29 dell-laptop systemd[1]: wpa_supplicant.service: Failed to load environment files: No such file or directory
Jan 11 22:07:29 dell-laptop systemd[1]: wpa_supplicant.service: Failed to run 'start' task: No such file or directory
Jan 11 22:07:29 dell-laptop systemd[1]: wpa_supplicant.service: Failed with result 'resources'.
Jan 11 22:07:29 dell-laptop systemd[1]: Failed to start WPA Supplicant instance.
warning: error(s) occurred while switching to the new configuration
```

### Side Note
I also noticed, that the [documentation](https://search.nixos.org/options?channel=23.11&show=networking.wireless.environmentFile&from=0&size=50&sort=relevance&type=packages&query=wireless.envir) falsely says the path should be in quotes: `networking.wireless.environmentFile = "/run/secrets/wireless.env";`. At least I'm not doing that.

### Notify maintainers
@rnhmjoj 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.71, NixOS, 23.11 (Tapir), 23.11.20240110.3dc440f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by rnhmjoj** [comment] 2024-01-11 23:28
> I also noticed, that the [documentation](https://search.nixos.org/options?channel=23.11&show=networking.wireless.environmentFile&from=0&size=50&sort=relevance&type=packages&query=wireless.envir) falsely says the path should be in quotes: networking.wireless.environmentFile = "/run/secrets/wireless.env";. At least I'm not doing that.

Are you aware of what the [path type](https://nixos.org/manual/nix/stable/language/values#type-path) in the Nix language does?
> evaluating "${./foo.txt}" will cause foo.txt in the current directory to be
> copied into the Nix store and result in the string "/nix/store/<hash>-foo.txt".

Generally if you refer to a file as `./wireless.env` it will be copied to the Nix store exposing it to everyone, so you wouldn't do that for `environmentFile`s, which are in fact meant for sideloading secrets.

That said, the `networking.wireless` module is actually doing `toString cfg.environmentFile` and passing the resulting string directly to systemd.
`toString` prevents the unwanted copying and converts the path value to a usual string.

> The rebuild causes a bunch of errors, among them wpa_supplicant.service: Failed to load environment files: No such file or directory.

What you did, even if likely a mistake, should technically work. Are you sure you're specifying the right path?
Note that a relative path is interpreted relative to the directory of the Nix expression being evaluated.

**Comment by SebastianStork** [comment] 2024-01-12 12:03
Thanks for the help.

The reason why I want to have the wireless.env near my config is because I am planning to back up my wifi passwords in my nixos-config git repo using git crypt (I'm still working on that). I don't really care that my wifi passwords would exposed to everyone with access the the computers.

The reason why I thought that the quotation marks in the documentation were incorrect was because `environmentFile = "./wireless.env";` gives this error: `error: A definition for option `networking.wireless.environmentFile' is not of type `null or path'.` and the same without the quatation marks works fine.

I just tried `environmentFile = "/run/secrets/wireless.env";` and it works fine so maybe I will just use a different way of backing it up.

**Comment by SebastianStork** [comment] 2024-01-28 15:46
I am currently doing it with the absolute path and it's working fine. Should I close this issue? It's a bit weird that relative paths with more than one "/" don't work at all but I agree that it's probably a bad idea anyway.

**Comment by rnhmjoj** [comment] 2024-01-28 19:06
> The reason why I thought that the quotation marks in the documentation were incorrect was because environmentFile = "./wireless.env"; gives this error:

That is because the path must be absolute in order for systemd to load it. A relative path would be interpreted relative to the process cwd (so, proably `/`), not to your configuration.

> and the same without the quotation marks works fine.

This works because the `toString` call is resolving the path value it into a string containg the absolute path.
To be clear, `./wireless.env` would be converted to something like `"/home/sebastian/my_nixos_config/wireless.env"`.

This is a prefectly legitimate way to do it, in fact it's what I do with my secrets. There are two things to note though:

1. The path may not be accessible to the user/service you are intending to configure. This is not an issue with environment files, because they're handled by systemd and it runs as root, however other users won't be able to traverse your home directory and read it. So, be sure the file is accessible.

2. If the module does not post-process you value with `toString` you will leak the secret by copying it to the store. So, remember to always use `toString` to be sure (calling it two times won't cause any issue).

**Comment by rnhmjoj** [comment] 2024-01-28 19:09
> It's a bit weird that relative paths with more than one "/" don't work at all but I agree that it's probably a bad idea anyway.

Yes, I would be interested in figuring this out, but I can't reproduce it. Can you write a minimal example?

**Comment by SebastianStork** [comment] 2024-01-31 18:36
Ok, I just tried to recreate the problem, I even rolled my system back to the stable release, but didn't get the error this time. I am pretty sure I tried everything and did everything right when I tried it 3 weeks ago but apparently not. I am really sorry to have wasted your time. If I somehow do get this error again in the future I will let you know.

**Comment by rnhmjoj** [comment] 2024-01-31 22:28
No problem. I'll just close the issue for now.

**Closed by rnhmjoj** 2024-01-31 22:28 UTC
Labels: 0.kind: bug
