### ISSUE TITLE
Package request: Nix Software Center

### ISSUE THREAD

**Issue by StrongSand94191** [NixOS/nixpkgs#319940] opened 2024-06-15 00:26 UTC
**Project description**

A graphical app store for Nix.

**Metadata**

* homepage URL: https://github.com/snowfallorg/nix-software-center
* source URL: https://github.com/snowfallorg/nix-software-center
* license: GPL-3.0
* platforms: Nix, Flakes

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Shawn8901** [comment] 2024-06-15 13:34
Seems to be the same software https://github.com/NixOS/nixpkgs/issues/212962

**Comment by Aleksanaa** [comment] 2024-06-15 13:36
Duplicate of https://github.com/NixOS/nixpkgs/issues/212962

**Closed by Aleksanaa** 2024-06-15 13:36 UTC
Labels: 0.kind: packaging request
