### ISSUE TITLE
KeePassXC 2.6.6 crashes when opening file chooser (no GSettings schemas)

### ISSUE THREAD

**Issue by underscore-j** [NixOS/nixpkgs#163482] opened 2022-03-09 18:16 UTC
### Describe the bug
Any action that would normally open a file chooser (like attaching a file, or selecting an ssh key) instead results in a crash.
If launched from a terminal, the error message 
```
(keepassxc:55464): GLib-GIO-ERROR **: 19:01:58.207: No GSettings schemas are installed on the system
```
is shown.

### Steps To Reproduce
1. Add a new entry in KeePassXC
2. Go to Advanced, Attachments and click 'add'
3. KeePassXC crashes

### Expected behavior
A file chooser should open, no crash.

### Notify maintainers

@jonafato @turion 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.26, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"home-manager-21.11, nixos-21.11.336340.2ebb6c1e5ae, nixos-master, nixos-stable-21.11.336340.2ebb6c1e5ae, nixos-unstable-22.05pre358986.062a0c5437b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by turion** [comment] 2022-03-10 09:43
I can't reproduce. On the console I get only this output:

```
$ keepassxc 
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
Qt: Session management error: networkIdsList argument is NULL
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2608, resource id: 16779914, major code: 40 (TranslateCoords), minor code: 0
```

What desktop environment & display manager are you using? I'm on KDE.

**Comment by underscore-j** [comment] 2022-03-10 09:59
I'm using i3.

I just found out that the issue is related to Qt5 styles:
`qt5.platformTheme = "gnome"; qt5.style = "adwaita-dark"` crashes,
`qt5.platformTheme = "gtk2"; qt5.style = "gtk2" works fine.

(I was wondering how a qt application would fail with GTK-related errors)

**Comment by turion** [comment] 2022-03-10 10:09
Is it related to `qt5.platformTheme` or to `qt5.style`, or both?

**Comment by underscore-j** [comment] 2022-03-10 10:12
The two settings are related: styles adwaita and adwaita-dark require "gnome", other styles require "gtk2".
If you try to only change one, you get an error.

**Comment by turion** [comment] 2022-03-10 14:12
It seems like similar issues have been resolved by adding `wrapGAppsHook` https://github.com/NixOS/nixpkgs/pull/159331/files

**Comment by turion** [comment] 2022-03-10 21:09
I tried to reproduce your problem, but I couldn't: https://github.com/turion/nixpkgs/pull/new/dev_fix_keepassxc_163482

**Comment by turion** [comment] 2022-03-10 21:13
Maybe i3 is essential to your problem, or some other part of your config?

**Closed** 2022-03-21 11:24 UTC
Labels: 0.kind: bug, 6.topic: qt/kde

**Comment by 7FM** [comment] 2022-11-14 01:14
Seems like I am still hitting this...
Though, I am using the homemanager module to set the qt theme/style:
```
qt = {
  enable = true;
  platformTheme = "gnome";
  style = {
    name = "adwaita-dark";
    package = pkgs.adwaita-qt;
  };
};
```
Combined with starting keepassxc via `XDG_DATA_DIRS= keepassxc` and opening a file chooser results in crashing.
The created keepassxc wrapper does not add gsettings-schemas paths to `$XDG_DATA_DIRS`.
Is the wrapping broken or am I missing something here?
