### ISSUE TITLE
Provide a way to customize the xdg-user-dirs

### ISSUE THREAD

**Issue by tiramiseb** [NixOS/nixpkgs#33282] opened 2018-01-01 17:14 UTC
The xdg-user-dirs package contains a file named `etc/xdg/user-dirs.defaults`.

A module allowing to customize this file would be great.

**Comment by jtojnar** [comment] 2018-01-01 23:55
GNOME users, at least, already have `~/.config/user-dirs.dirs` generated in their profile by the [GNOME module](https://github.com/NixOS/nixpkgs/blob/1a69b2029fa1012ff9ffdd826bd88a3f7eabc1df/nixos/modules/services/x11/desktop-managers/gnome3.nix#L165). That would override the XDG module.

**Comment by tiramiseb** [comment] 2018-01-02 07:23
The `xdg-user-dirs-update` command, executed in the GNOME session script you are referring to, reads the `user-dirs.defaults` file, translates it if needed and places it in `~/.config/user-dirs.dirs`. Yes, this is exactly what I am talking about.

If `etc/xdg/user-dirs.defaults` can be customized, then the GNOME session script would copy the customized one.

**Comment by lasandell** [comment] 2018-01-12 23:34
This looks like a duplicate of #16200.

The environment variable `$XDG_CONFIG_DIRS` determines the search paths for `user-dirs.defaults`. This is currently [defined](https://github.com/NixOS/nixpkgs/blob/bd562949cfa82b76ef5959bd53ee9596bc35e705/nixos/modules/programs/environment.nix#L43) as a profile-relative path variable. For this to work, I think it would also need to define `/etc/xdg` as a profile non-relative path so that a module could produce the `user-dirs.defaults` file in that path.

**Comment by dasj19** [comment] 2019-08-21 17:23
I'm also interested in a way to customize xdg-user-dirs

**Comment by jtojnar** [comment] 2019-08-21 17:43
There is little need for dedicated options, you can just use

```nix
{
  environment.etc."xdg/user-dirs.conf".text = ''
    XDG_DESKTOP_DIR="$HOME/Desktop"
    XDG_DOCUMENTS_DIR="$HOME/Documents"
    XDG_DOWNLOAD_DIR="$HOME/Downloads"
    XDG_MUSIC_DIR="$HOME/Music"
    XDG_PICTURES_DIR="$HOME/Pictures"
    XDG_PUBLICSHARE_DIR="$HOME/Public"
    XDG_TEMPLATES_DIR="$HOME/Templates"
    XDG_VIDEOS_DIR="$HOME/Videos"
  '';
}
```

in your `configuration.nix`.

**Comment by dasj19** [comment] 2019-08-22 08:27
@jtojnar It does not work...
What I have tried so far in a VM:
* removing the user homedir + `nixos-rebuild switch --upgrade`
* changing `environment.etc."xdg/user-dirs.conf".text` to `environment.etc."xdg/user-dirs.dirs".text` + removing the user homedir + `nixos-rebuild switch --upgrade`
* changing `environment.etc."xdg/user-dirs.conf".text` to `environment.etc."xdg/user-dirs.default".text` + removing the user homedir + `nixos-rebuild switch --upgrade`

I am using Gnome as a DE

**Comment by jtojnar** [comment] 2019-08-22 09:22
`nixos-rebuild switch --upgrade` will not be enough. `xdg-user-dirs` relies on `/etc/xdg/autostart` to run so you need to re-login for it to be triggered.

**Comment by dasj19** [comment] 2019-08-22 09:48
I did reboot the VM after every `nixos-rebuild switch --upgrade`

**Comment by jtojnar** [comment] 2019-08-22 11:33
Hmm, apparently, it should have been `user-dirs.defaults`, not `user-dirs.default` or `user-dirs.conf`.

**Comment by dasj19** [comment] 2019-08-24 11:39
@jtojnar ... sorry for the delay...
But I just tried with only this configuration.nix
```

{ config, pkgs, ... }:

{

  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # Use the GRUB 2 boot loader.
  boot.loader.grub.enable = true;
  boot.loader.grub.version = 2;

  # Define on which hard drive you want to install Grub.
  boot.loader.grub.device = "/dev/sda"; # or "nodev" for efi only

  networking.hostName = "nixos"; # Define your hostname.

  # Enable the X11 windowing system.
  services.xserver.enable = true;
  services.xserver.layout = "es";

  # Set your time zone.
  time.timeZone = "Europe/Copenhagen";


  environment.etc."xdg/user-dirs.defaults".text = ''
    XDG_DESKTOP_DIR="$HOME/system/desktop"
    XDG_DOWNLOAD_DIR="$HOME/downloads"
    XDG_TEMPLATES_DIR="$HOME/system/templates"
    XDG_PUBLICSHARE_DIR="$HOME/system/public"
    XDG_DOCUMENTS_DIR="$HOME/documents"
    XDG_MUSIC_DIR="$HOME/media/music"
    XDG_PICTURES_DIR="$HOME/media/photos"
    XDG_VIDEOS_DIR="$HOME/media/video"
  '';

  # Enable the GNOME Desktop Environment.
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome3.enable = true;
}
```

And it does not use the user-dirs I configure above

**Comment by jtojnar** [comment] 2019-08-24 13:36
Okay, there are several issues here:

1. As https://github.com/NixOS/nixpkgs/issues/33282#issuecomment-357383680 correctly points out, `XDG_CONFIG_DIRS` is profile-relative variable and since it is set, `/etc/xdg` will not be used as per the [spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables):

> If `$XDG_CONFIG_DIRS` is either not set or empty, a value equal to /etc/xdg should be used. 

2. We could add `(pkgs.writeTextFile { name = "user-dirs.defaults"; text = "…"; destination = "/etc/xdg/user-dirs.defaults"; })` to `environment.systemPackages` which would add it to `XDG_CONFIG_DIRS` but that will conflict with the file from the preset file from the `xdg-user-dirs` package [installed by `gnome3` module](https://github.com/NixOS/nixpkgs/blob/83d179fc090f2d3c0bb7b26b614dceb05cb8b84a/nixos/modules/services/x11/desktop-managers/gnome3.nix#L236).

3. Okay, I have came up with the following abomination to add to your `configuration.nix`:

```nix
  imports = [
    ({lib, pkgs, ...}: {
      environment.systemPackages = lib.mkBefore [
        (pkgs.writeTextFile {
          name = "user-dirs.defaults";
          text = ''
            XDG_DESKTOP_DIR=system/desktop
            XDG_DOWNLOAD_DIR=downloads
            XDG_TEMPLATES_DIR=system/templates
            XDG_PUBLICSHARE_DIR=system/public
            XDG_DOCUMENTS_DIR=documents
            XDG_MUSIC_DIR=media/music
            XDG_PICTURES_DIR=media/photos
            XDG_VIDEOS_DIR=media/video
          '';
          destination = "/etc/xdg/user-dirs.defaults";
        })
      ];
    })
  ];
```

But again, it does not work. Turns out we are prefixing the `XDG_CONFIG_DIRS` with presets when running [`xdg-user-dirs-update`](https://github.com/NixOS/nixpkgs/blob/ffbad0f656da7cce92c92bde1e2c059df8df7fe8/pkgs/tools/X11/xdg-user-dirs/default.nix#L15). So we need to [patch](https://github.com/NixOS/nixpkgs/pull/67389) as well.

With the patch and the horrendous snippet, I can confirm the expected directories were created.

**Comment by jtojnar** [comment] 2019-08-24 14:14
https://github.com/NixOS/nixpkgs/pull/67389 now contains full fix enabling us to use `environment.etc."xdg/user-dirs.defaults".text` as suggested in https://github.com/NixOS/nixpkgs/issues/33282#issuecomment-523572259.

**Comment by dasj19** [comment] 2019-08-24 14:46
Awesome @jtojnnar .... I just built from your branch https://github.com/jtojnar/nixpkgs/tree/xdg-user-dirs and works like a charm.
Thanks a lot, I owe you one

**Closed** 2019-08-24 17:22 UTC
Labels: 0.kind: enhancement, 6.topic: freedesktop, 6.topic: nixos, 9.needs: module (new)

**Comment by cx405** [comment] 2023-03-17 05:54
@jtojnar @tiramiseb you probably want to reopen this, because functionality implemented here is currently broken. 

Please see: #221604

**Comment by jtojnar** [comment] 2023-03-24 15:32
As mentioned in the [other issue](https://github.com/NixOS/nixpkgs/issues/221604), there is a prerequisite of `environment.systemPackage = [ pkgs.xdg-user-dirs ]` and having something that runs autostart entries (which DEs like GNOME or Plasma do out of the box).
