### ISSUE TITLE
Multiple DEs with GDM

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#24719] opened 2017-04-07 18:25 UTC
## Issue description

Multiple Desktop Environments do not appear to work with GDM on 17.03

### Steps to reproduce

Enable GDM and disable other display managers in configuration.nix.
Enable both GNOME and Plasma.
Rebuild and reboot. Only GNOME loads and you have no option for Plasma.
There should be a cog near the login area on GDM. Nothing there.
nix-env -i xfdesktop (xfce4 desktop) and plasma-desktop.
Both build and install well.
Reboot. 
Again. No selection method on GDM. Login goes straight to GNOME, as expected.

## Technical details

I don't think any are needed. But I can provide whatever is requested.

* System: NixOS: 17.03.889.9626bc7db7 (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "17.03.889.9626bc7db7"

**Comment by bdimcheff** [comment] 2017-05-27 00:32
I just noticed this too... thought I was going crazy.

**Comment by jtojnar** [comment] 2019-06-05 13:08
This was fixed in https://github.com/NixOS/nixpkgs/commit/300af6677760944a3c27f7bf33a1366c380c3317

Duplicate of https://github.com/NixOS/nixpkgs/issues/34101

**Closed by jtojnar** 2019-06-05 13:08 UTC
Labels: 0.kind: bug, 6.topic: gnome3
