### ISSUE TITLE
isl: make musl/bootstrap package bit-by-bit reproducible

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#106587] opened 2020-12-10 19:40 UTC
**Describe the bug**

The closure of the iso-minimal derivation contains a version of the 'isl' library that does not build deterministically.

**To Reproduce**

The 'normal' isl library is reproducible: `nix-build '<nixpkgs>' -A isl --check` succeeds.

However, an isl that is a transitive dependency of busybox-sandbox-shell is not reproducible:

    nix-build $(nix-store --query --graph `nix-instantiate '<nixpkgs>' -A busybox-sandbox-shell` | grep -e "isl-0.20.* -> " | grep musl | cut -d "\"" -f 2 | uniq) --check

I'm not sure how to diagnose what's different with this isl derivation that makes it unreproducible. I also tried `nix-build '<nixpkgs>' --arg crossSystem '(import <nixpkgs> {}).lib.systems.examples.musl64' -A isl --check`, but that also succeeds for me.

**Comment by raboof** [comment] 2020-12-17 15:04
(`nix-build -A pkgs.pkgsMusl.isl` also reproduces fine and is different from the busybox-sandbox-shell dependency)

**Comment by raboof** [comment] 2020-12-27 17:04
> However, an isl that is a transitive dependency of busybox-sandbox-shell is not reproducible:
> 
> ```
> nix-build $(nix-store --query --graph `nix-instantiate '<nixpkgs>' -A busybox-sandbox-shell` | grep -e "isl-0.20.* -> " | grep musl | cut -d "\"" -f 2 | uniq) --check
> ```

Hmm, it's reproducible for me now... let's close this for now and revisit the issue when we see it again.

**Comment by raboof** [comment] 2021-01-04 11:18
Now another isl that is a transitive dependency of busybox-sandbox-shell is not reproducible - not so sure anymore it has to do with musl directly:

    nix-build $(nix-store --query --graph `nix-instantiate '<nixpkgs>' -A busybox-sandbox-shell` | grep -e "isl-0.20.* -> " | grep gcc-9 | cut -d "\"" -f 2 | uniq) --check

**Comment by raboof** [comment] 2021-01-04 20:29
It seems the actual assembly generated by gcc is different, for example for print.o:

https://pastebin.com/SPezTXki

Looking in nix-shell it seems print.o is generated with:

    gcc -DHAVE_CONFIG_H   -I. -I. -I./include -Iinclude/    -O3 -fomit-frame-pointer -malign-double -fstrict-aliasing -ffast-math -MT print.o -MD -MP -MF $depbase.Tpo -c -o print.o print.c

Unfortunately on my machine that consistently produces the same output, which is different from the one we find on cache.nixos.org

**Comment by raboof** [comment] 2021-03-03 08:02
I see differences in the assembly like `add    $0x1,%eax` vs `inc    %eax` - seems like some optimization that does not deterministically trigger? CFLAGS is using -O3

Debian has seen some differences in 0.23 on i386 recently (https://tests.reproducible-builds.org/debian/rb-pkg/unstable/i386/diffoscope-results/isl.html) which look somewhat similar

The build log (`nix-build /nix/store/lj2z3sfxqcr3q3lp0q97lixlags3g1wn-isl-0.20.drv --check` vs `nix log /nix/store/lj2z3sfxqcr3q3lp0q97lixlags3g1wn-isl-0.20.drv`) seem pretty much the same - I did see a change in ordering of the CCLD calls, but I think cmake should make sure that doesn't matter, right?

**Comment by veehaitch** [comment] 2021-04-07 22:56
I'm also running into this on x86_64:

```
# nix build -L --rebuild '/nix/store/lj2z3sfxqcr3q3lp0q97lixlags3g1wn-isl-0.20.drv'
error: derivation '/nix/store/lj2z3sfxqcr3q3lp0q97lixlags3g1wn-isl-0.20.drv' may not be deterministic: output '/nix/store/6gmh9jq83v6fh2l0rqg937w9fxjzac7r-isl-0.20' differs
```

**Comment by veehaitch** [comment] 2021-04-08 12:17
> Now another isl that is a transitive dependency of busybox-sandbox-shell is not reproducible - not so sure anymore it has to do with musl directly:
> 
> ```
> nix-build $(nix-store --query --graph `nix-instantiate '<nixpkgs>' -A busybox-sandbox-shell` | grep -e "isl-0.20.* -> " | grep gcc-9 | cut -d "\"" -f 2 | uniq) --check
> ```

When looking at the [dependencies of `busybox-sandbox-shell`](https://gist.githubusercontent.com/veehaitch/482c2bce3f349ea76551b04b25ee3e60/raw/2d0c91d0095427ba6aeebe639d6b35241c3cbbaa/c514786-busybox-sandbox-shell-derivation.json) from c5147860e23ed75ce9d40298c66b416c00be116

```shell
nix show-derivation -r 'github:nixos/nixpkgs?ref=c5147860e23ed75ce9d40298c66b416c00be116#busybox-sandbox-shell' \
  | jq 'keys' \
  | jq '.[]' \
  | grep 'isl-0.20.drv'
```
I get two `isl` dependencies:

1. `/nix/store/3yy0njks8l23lw4l4pkgdj41vgsnxh8f-isl-0.20.drv`: A dependency of `/nix/store/4f97plism3424fydpbi66i5nl68ri5ff-x86_64-unknown-linux-musl-stage-static-gcc-10.2.0.drv`
2. `/nix/store/lj2z3sfxqcr3q3lp0q97lixlags3g1wn-isl-0.20.drv`: A dependency of `/nix/store/70cx4mag2pdhriw0plrszv1i2y72narp-gcc-10.2.0.drv`

### `3yy0njks8l23lw4l4pkgdj41vgsnxh8f-isl-0.20.drv`

Reproduces just fine.

- [Hydra build log][3yy0njks8l23lw4l4pkgdj41vgsnxh8f-cache]
- [Local build log][3yy0njks8l23lw4l4pkgdj41vgsnxh8f-check] (`nix-build --check`)
- [Difference between both logs][3yy0njks8l23lw4l4pkgdj41vgsnxh8f-diffoscope]


[3yy0njks8l23lw4l4pkgdj41vgsnxh8f-cache]: https://cache.nixos.org/log/3yy0njks8l23lw4l4pkgdj41vgsnxh8f-isl-0.20.drv
[3yy0njks8l23lw4l4pkgdj41vgsnxh8f-check]: https://gist.github.com/veehaitch/482c2bce3f349ea76551b04b25ee3e60/raw/ad799b8c8a9b732ece63b3896cbb05e18769032f/3yy0njks8l23lw4l4pkgdj41vgsnxh8f-isl-0.20.drv.check.log
[3yy0njks8l23lw4l4pkgdj41vgsnxh8f-diffoscope]: https://htmlpreview.github.io/?https://gist.githubusercontent.com/veehaitch/482c2bce3f349ea76551b04b25ee3e60/raw/ad799b8c8a9b732ece63b3896cbb05e18769032f/3yy0njks8l23lw4l4pkgdj41vgsnxh8f-diffoscope-report.html

### `lj2z3sfxqcr3q3lp0q97lixlags3g1wn-isl-0.20.drv`

Doesn't produce the same output.

- [Hydra build log][lj2z3sfxqcr3q3lp0q97lixlags3g1wn-cache]
- [Local build log][lj2z3sfxqcr3q3lp0q97lixlags3g1wn-check] (`nix-build --check`)
- [Difference between both logs][lj2z3sfxqcr3q3lp0q97lixlags3g1wn-diffoscope]

[lj2z3sfxqcr3q3lp0q97lixlags3g1wn-cache]: https://cache.nixos.org/log/lj2z3sfxqcr3q3lp0q97lixlags3g1wn-isl-0.20.drv
[lj2z3sfxqcr3q3lp0q97lixlags3g1wn-check]: https://gist.github.com/veehaitch/482c2bce3f349ea76551b04b25ee3e60/raw/ad799b8c8a9b732ece63b3896cbb05e18769032f/lj2z3sfxqcr3q3lp0q97lixlags3g1wn-isl-0.20.drv.check.log
[lj2z3sfxqcr3q3lp0q97lixlags3g1wn-diffoscope]: https://htmlpreview.github.io/?https://gist.githubusercontent.com/veehaitch/482c2bce3f349ea76551b04b25ee3e60/raw/ad799b8c8a9b732ece63b3896cbb05e18769032f/lj2z3sfxqcr3q3lp0q97lixlags3g1wn-diffoscope-report.html


When looking at the differences between `3yy0njks8l23lw4l4pkgdj41vgsnxh8f` and `lj2z3sfxqcr3q3lp0q97lixlags3g1wn`, both have in common that some CCDL reordering happens (as you, @raboof, already mentioned). The most apparent difference is, however, the check for `-march=k8`, which succeeds for `lj2z3sfxqcr3q3lp0q97lixlags3g1wn` but doesn't for `3yy0njks8l23lw4l4pkgdj41vgsnxh8f`. From the Hydra logs alone, it's hard to tell if this flag ends up in calls to `gcc` but it could be an explanation for the major differences between the outputs.

**Comment by veehaitch** [comment] 2021-04-08 16:38
The CPU machine type could be the problem after all. I executed `nix-build --check '/nix/store/lj2z3sfxqcr3q3lp0q97lixlags3g1wn-isl-0.20.drv'` on a [PC Engines APU2](https://www.pcengines.ch/apu2.htm) (AMD GX-412TC SOC) which passes just fine. My previous comment was referencing builds executed on an Intel machine. Logs for the check run using the APU2:

- [Hydra build log][lj2z3sfxqcr3q3lp0q97lixlags3g1wn-cache]
- [Local build log][lj2z3sfxqcr3q3lp0q97lixlags3g1wn-check] (`nix-build --check`)
- [Difference between both logs][lj2z3sfxqcr3q3lp0q97lixlags3g1wn-diffoscope]

[lj2z3sfxqcr3q3lp0q97lixlags3g1wn-cache]: https://cache.nixos.org/log/lj2z3sfxqcr3q3lp0q97lixlags3g1wn-isl-0.20.drv
[lj2z3sfxqcr3q3lp0q97lixlags3g1wn-check]: https://gist.github.com/veehaitch/eb9f4fe781fea309e4dcff4f6241c010/raw/cbe77cd787243bf8b199a2f2818ca0fcd8af9f8a/lj2z3sfxqcr3q3lp0q97lixlags3g1wn-isl-0.20.drv.check.log
[lj2z3sfxqcr3q3lp0q97lixlags3g1wn-diffoscope]: https://htmlpreview.github.io/?https://gist.githubusercontent.com/veehaitch/eb9f4fe781fea309e4dcff4f6241c010/raw/cbe77cd787243bf8b199a2f2818ca0fcd8af9f8a/lj2z3sfxqcr3q3lp0q97lixlags3g1wn-diffoscope-report.html

**Comment by veehaitch** [comment] 2021-04-08 23:43
The issue is that the `configure` script guesses the architecture of the host. I see two possibilities to approach this:

1. Define an architecture mapping for `stdenv.hostPlatform.system` and pass it using `--with-gcc-arch=`. That's what the `imagemagick` derivation does:
https://github.com/NixOS/nixpkgs/blob/40be12c695e5e22dde20d171afbb20a1418972d8/pkgs/applications/graphics/ImageMagick/7.0.nix#L43

2. Set the `--with-gcc-arch=` option to `generic`. This will, in turn, try to set the GCC options `-march=` and `-mtune=` to `generic`. At least for the `-march` option, `generic` [is not a valid value](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html) but this doesn't cause any harm as the `-march=` option gets omitted altogether then. `libffi` uses this approach: 
https://github.com/NixOS/nixpkgs/blob/1ce6b05ea18de429b2ddf06332b99264cdb49bb1/pkgs/development/libraries/libffi/default.nix#L24

I'd go for the second option as it doesn't require a mapping for all the architectures we support.

**Comment by veehaitch** [comment] 2021-04-26 11:01
Since 13598220a699ec9039323aa79e8145d902657b5e is merged into master now, `isl` reproduces fine for me 🙂 

```
nix build --rebuild -L 'github:nixos/nixpkgs/45e57e917d623aa71e9e72947cf9c2dae4f015dc#isl_0_20'
```

**Comment by raboof** [comment] 2021-04-26 11:05
The reproducibility problems weren't always, erm, reproducible, but this is a good sign! Let's close this until we have reason to suspect further problems.

**Closed** 2021-04-26 11:04 UTC
Labels: 0.kind: bug, 6.topic: reproducible builds
