### ISSUE TITLE
Build failure: guile-git-0.7.0

### ISSUE THREAD

**Issue by Superfly-Johnson** [NixOS/nixpkgs#337090] opened 2024-08-24 21:04 UTC
### Steps To Reproduce

1. run nix-env -i guile-git

### Build log

https://gist.github.com/Superfly-Johnson/d0dc9877b97cb37bc366cf891ddc3d03

### Additional context

I was trying to install GNU GUIX and the package would fail building. 

### Notify maintainers

ethan@ethancedwards.com

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[raphael@nixos-e560:~/git/nixpkgs]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.46, NixOS, 24.11 (Vicuna), 24.11pre669741.c374d94f1536`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by brsvh** [comment] 2024-08-26 01:34
It seems that this issue is caused by `libgit2` version `1.8.1`. To temporarily resolve it, you should consider using the guix/guile-git/libgit2 at commit `2cc76299592fb976313830db8fd6e7887e492d35`.

Relevant links:

- https://gitlab.com/guile-git/guile-git/-/issues/30
- #317275

Once the upstream resolved this issue, it should be fixed without requiring any action in nixpkgs.

**Comment by Superfly-Johnson** [comment] 2024-08-26 02:41
Could updating the guile-guit package so that it uses Libgit2 version 1.7.2 until upstream is solved work as a band-aid fix until then?

**Comment by christoph-blessing** [comment] 2024-08-27 10:49
> It seems that this issue is caused by `libgit2` version `1.8.1`. To temporarily resolve it, you should consider using the guix/guile-git/libgit2 before commit `2cc76299592fb976313830db8fd6e7887e492d35`.
> 
> Relevant links:
> 
>     * https://gitlab.com/guile-git/guile-git/-/issues/30
> 
>     * [libgit2: 1.7.2 -> 1.8.1; python312Packages.pygit2: 1.14.1 -> 1.15.0 #317275](https://github.com/NixOS/nixpkgs/pull/317275)
> 
> 
> Once the upstream resolved this issue, updating to the next version of `guile-git` should resolve this issue.

What do you mean by guix/guile-git/libgit2? Where can I find that?

**Comment by brsvh** [comment] 2024-08-28 02:32
You may choose any commit of `libgit2` earlier than `1.8.1`, but ensure it’s not too outdated. For example, the parent of commit `2cc76299592fb976313830db8fd6e7887e492d35` is `a6c20a73872c4af66ec5489b7241030a155b24c3`.

If you're using Flake, you can add these versions as a new input.

flake.nix
``` Nix
{
  inputs = {
      old-libgit2.url = "github:NixOS/nixpkgs/a6c20a73872c4af66ec5489b7241030a155b24c3";
  };
}
```

Then, use an override to replace the `libgit2` used by `guile-git`.

old-guile-git-overlay.nix
``` Nix
final: prev:
let
  pkgs = import inputs.old-libgit2 {
    system = YOUR-ARCH;
  };
in
{
  guile-git = prev.guile-git.override { libgit2 = pkgs.libgit2; };  
}
```

Finally, apply it wherever you need to use it.

If you are not using Flake, I cannot provide advice on using `nix-channel` since I haven't used it myself.

**Closed** 2024-08-29 10:18 UTC
Labels: 0.kind: build failure
