### ISSUE TITLE
Cursor is too tiny on HiDPI displays

### ISSUE THREAD

**Issue by srid** [NixOS/nixpkgs#34603] opened 2018-02-05 01:29 UTC
## Issue description
Xcursor is not scaled on high dpi displays.

### Steps to reproduce
- Install NixOS and use unstable channel
- Connect a HiDPI display (I have a 5k monitor)
- Nvdia drivers auto detects DPI, and X will have fonts and UI elements scaled as one would expect
- Cursor however remains tiny

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.78, NixOS, 18.03pre126729.2e4aded3669 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(srid): `""`
 - channels(root): `"nixos-18.03pre126729.2e4aded3669"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by srid** [comment] 2018-02-05 01:30
Probably related to https://github.com/NixOS/nixpkgs/issues/22652

**Comment by jmackie** [comment] 2018-04-05 21:46
Same here, cursor is stubbornly tiny no matter what config options I mess with. Using lightdm + Xmonad

**Comment by srid** [comment] 2018-04-05 23:18
FWIW enabling `desktopManager.plasma5` somehow resolved this issue for me. No problems on a 5k 27" display.

**Comment by asheshambasta** [comment] 2019-05-13 08:02
I can confirm this is also an issue for me. Enabling desktopManager.plasma5 has seem to had no effect for me.
In my case, Google chrome also seems to ignore the --force-device-scale-factor value. But the scaling doesn't get detected properly: the google chrome toolbars are comically large.

**Comment by srid** [comment] 2019-05-13 15:29
I've resolved this using home-manager's [`xsession.pointerCursor`](https://github.com/srid/mynixos/blob/c806fd0/nix/home.nix#L53-L57).

**Comment by asheshambasta** [comment] 2019-05-13 18:00
![image](https://user-images.githubusercontent.com/580365/57643245-9c1c2300-75b9-11e9-8cbb-39c360fe3e79.png)
I have a feeling that with my configuration, the problem goes deeper. The screenshot shows that chrome is not scaling correctly.

**Comment by berbiche** [comment] 2019-11-05 01:34
I have the same issue as @asheshambasta  on Chrome and other Electron-based applications (VSCode for instance).
My cursor is also too tiny on Firefox as initially reported by @srid.

In my case, it only occurs on Sway when scaling is not `1`.  Whether I run Sway from a DM doesn't change anything.

I also cannot reproduce this on Gnome since AFAIK it doesn't support fractional scaling (and because I don't use it enough to have encountered this problem).

<details>
<summary>neofetch output</summary>
<pre>
OS: NixOS 19.09.941.27a5ddcf747 (Loris) x86_64 
Host: 20L9001SUS ThinkPad T580 
Kernel: 5.3.7 
Uptime: 4 days, 1 hour, 47 minutes 
Packages: 1434 (nix-system), 1601 (nix-user), 20 (flatpak) 
Shell: zsh 5.7.1 
Resolution: 2560x1440 @ 59.96Hz 
WM: sway 
Theme: Adwaita [GTK2/3] 
Terminal: alacritty 
CPU: Intel i7-8650U (8) @ 4.200GHz [49.0°on] 
Memory: 9018MiB / 31840MiB (28%) 
Battery0: 60% [Discharging] 
Battery1: 5% [Unknown] 
Locale: en_CA.UTF-8 
</pre>
</details>

<details><summary><code>nix-info</code></summary>
<pre>
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.7, NixOS, 19.09.941.27a5ddcf747 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.941.27a5ddcf747"`
 - channels(nicolas): `"home-manager-19.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
</pre>
</details>

<details><summary><code>swaymsg -t get_outputs --pretty | wl-copy</code></summary>
<pre>
Output eDP-1 'Unknown 0x06D7 0x00000000' (focused)
  Current mode: 3840x2160 @ 59.997002 Hz
  Position: 0,0
  Scale factor: 1.500000
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 2
  Available modes:
    3840x2160 @ 59.997002 Hz
</pre>
</details>

**Comment by aaronjanse** [comment] 2019-11-06 17:03
In case it helps anyone, here are the options I set for my hidpi machine:

```nix
{
  environment.variables = {
    GDK_SCALE = "2";
    GDK_DPI_SCALE = "0.5";
    QT_AUTO_SCREEN_SCALE_FACTOR = "1";
  };

  services.xserver.dpi = 227;
}
```

For the cursor, I currently use this for home-manager (under `home-manager.users.ajanse`):

```nix
{
  xsession.pointerCursor = {
    name = "Vanilla-DMZ";
    package = pkgs.vanilla-dmz;
    size = 128;
  };
}
```

But I think I think I used to use the non-home-manager code:
```nix
{
  displayManager.lightdm.greeters.gtk.cursorTheme = {
    name = "Vanilla-DMZ";
    package = pkgs.vanilla-dmz;
    size = 64;
  };
}
```

Assuming the nobody wants tiny scaling on a hidpi screen, is there a reason that the above options aren't the default in NixOS when `services.xserver.dpi` is above a certain value?

**Comment by berbiche** [comment] 2019-11-08 22:17
Thanks for your sharing your configuration.

This configuration is somewhat undesirable though because I don't use a fix setup and the scaling I need would change based on the monitors I have at my disposition.

My use-case is that of a student walking around campus with its laptop and connecting it to various displays with different resolutions and DPIs.

For instance, I need scaling for my laptop's display (15" 4k at 1.5 scale, effectively 2560x1440) while I also use standard 1080p monitors that do not require scaling.

> Is there a reason that the above options aren't the default in NixOS when services.xserver.dpi is above a certain value?

While not a bad solution, __the proposed solution is constrained to a homogeneous environment__.

Not to lessen the efforts made by the contributors to the project, but it _just works™_ on Manjaro (and probably other distros), without any explicit configurations or environment variables (so it is feasible, but how?)

**Comment by barischrooneyj** [comment] 2020-09-01 16:54
Still important to me

**Comment by sagehane** [comment] 2022-01-31 11:02
I use River on NixOS with XWayland disabled, and I've always suffered from this issue.

I just realizing adding `gnome.adwaita-icon-theme` seems to set the `XCURSOR_PATH` and `XCURSOR_SIZE`, which fixed the cursor size for me on Firefox and such.

But it's still ridiculously small on Electron apps (I use `element-desktop`) like others have said.

**Comment by moritzschaefer** [comment] 2022-02-01 06:11
I use gdm an EXWM and have a tiny cursor. Nothing helped so far

**Comment by laech** [comment] 2022-09-09 23:08
I'm using Nix on Fedora and was also experiencing this problem, what solves it for me was to set the `XCURSOR_PATH` environment variable (it was not defined on my system). Either set and export it in your profile or set it when you launch any Nix apps.

To try it:

```sh
XCURSOR_PATH=$HOME/.local/share/icons:$HOME/.nix-profile/share/icons:/usr/share/icons ~/.nix-profile/bin/<your app>
```

This solves the tiny cursors for me (including Electron apps) and make the apps use the host's cursor theme.

**Comment by rnhmjoj** [comment] 2022-11-12 10:16
This should have been fixed in dd38ae1f2c0ae9eb53a3454b0633c2b29f14a0ef.
If you set `services.xserver.dpi` the default cursor will now be scaled automatically.

**Closed by rnhmjoj** 2022-11-12 10:16 UTC

**Comment by mboyea** [comment] 2024-04-02 20:31
The default cursor is not scaled automatically on my machine using xorg.
> OS: NixOS 23.11.20240320.f091af0 (Tapir) x86_64
> Resolution: 3840x2160
> DE: none+i3
> WM: i3
The solution was to add `services.xserver.upscaleDefaultCursor = true;` to my `etc/nixos/configuration.nix`. Altogether, the relevant portion of my config looks like:
```nix
  services.xserver.dpi = 220;
  services.xserver.upscaleDefaultCursor = true;
  environment.variables = {
    GDK_SCALE = "2.2";
    GDK_DPI_SCALE = "0.4";
    _JAVA_OPTIONS = "-Dsun.java2d.uiScale=2.2";
    QT_AUTO_SCREEN_SCALE_FACTOR = "1";
    XCURSOR_SIZE = "64";
  };
```
Now the cursor is the right size, but *only* after a user signs in - this is because these effects are not applied until xserver is started. However, your display manager (login manager) can be used to set your cursor separately. For example, if you use the default lightdm, the cursor will have to be set separately using its settings (see https://mynixos.com/search?q=nix+option+lightdm+cursor for options)

**Comment by rnhmjoj** [comment] 2024-04-02 22:37
> The solution was to add services.xserver.upscaleDefaultCursor = true

Yes, most of the functionality behind `hardware.video.hidpi.enable` was split into different options, essentially because people disagreed on what hidpi means.
