### ISSUE TITLE
Tor service does not start

### ISSUE THREAD

**Issue by mrkkrp** [NixOS/nixpkgs#39640] opened 2018-04-28 07:56 UTC
## Issue description

After a `nixos-rebuild` run, `tor.service` ceased to start.

### Steps to reproduce

I have `tor` in `environment.systemPackages` as well as `services.tor.enable = true;`. I'm on latest `nixos-unstable`. Not sure if this is enough to reproduce.

And here is what `journalctl -xe` has to say:

```
Apr 28 14:47:27 nixos systemd[1]: Starting Tor Daemon...
-- Subject: Unit tor.service has begun start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit tor.service has begun starting up.
Apr 28 14:47:27 nixos systemd[4366]: tor.service: Failed to set up mount namespacing: No such file or directory
Apr 28 14:47:27 nixos systemd[4366]: tor.service: Failed at step NAMESPACE spawning /nix/store/s5ipgml9pvh697k18nm9941fbij3d7kg-unit-script/bin/tor-pre-start: No such file or directory
-- Subject: Process /nix/store/s5ipgml9pvh697k18nm9941fbij3d7kg-unit-script/bin/tor-pre-start could not be executed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The process /nix/store/s5ipgml9pvh697k18nm9941fbij3d7kg-unit-script/bin/tor-pre-start could not be executed and failed.
-- 
-- The error number returned by this process is 2.
```

## Technical details

system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.0, channels(root): "nixos-18.09pre135256.6c064e6b1f3", channels(mark): "", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs

**Comment by dotlambda** [comment] 2018-04-28 19:43
Duplicate of https://github.com/NixOS/nixpkgs/issues/39290.
Has been fixed in #39083.
Upgrading to latest nixos-unstable should solve the problem.

**Closed by dotlambda** 2018-04-28 19:43 UTC
