### ISSUE TITLE
Steam fails to launch

### ISSUE THREAD

**Issue by hazeycode** [NixOS/nixpkgs#191847] opened 2022-09-18 20:28 UTC
### Describe the bug
Steam fails to launch. strace output:

```console
...
Loaded SDL version 2.25.0-7450656
libGL error: MESA-LOADER: failed to open radeonsi: /lib32/libc.so.6: version `GLIBC_2.34' not found (required by /run/opengl-driver-32/lib/dri/radeonsi_dri.so) (search paths /run/opengl-driver-32/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi: /lib32/libc.so.6: version `GLIBC_2.34' not found (required by /run/opengl-driver-32/lib/dri/radeonsi_dri.so) (search paths /run/opengl-driver-32/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /lib32/libc.so.6: version `GLIBC_2.34' not found (required by /run/opengl-driver-32/lib/dri/swrast_dri.so) (search paths /run/opengl-driver-32/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  152
Serial number of failed request:  50
xerror_handler: X failed, continuing
crash_20220918212447_4.dmp[47394]: Uploading dump (out-of-process)
/tmp/dumps/crash_20220918212447_4.dmp
/home/chris/.local/share/Steam/steam.sh: line 796: 47388 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
)    = 1 ([{fd=3, revents=POLLIN}])
read(3, "\21\0\0\0\0\0\0\0\1\0\0\0\274\270\0\0\350\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 128) = 128
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], WNOHANG, NULL) = 47292
exit_group(0)                           = ?
+++ exited with 0 +++
```

### Steps To Reproduce
1. Install steam using method described in docs (https://nixos.wiki/wiki/Steam)
2. Try to run steam client. i.e. `strace steam`

### Expected behavior
Steam starts and presents GUI

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.8, NixOS, 22.05 (Quokka), 22.05.3117.f21492b4132`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05.3117.f21492b4132"`
 - channels(chris): `"home-manager-21.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rumpelsepp** [comment] 2022-09-27 18:48
[log.txt](https://github.com/NixOS/nixpkgs/files/9658820/log.txt)

**Comment by SuperSandro2000** [comment] 2023-02-18 20:54
> ```
> libGL error: MESA-LOADER: failed to open radeonsi: /lib32/libc.so.6: version `GLIBC_2.34' not found (required by /run/opengl-driver-32/lib/dri/radeonsi_dri.so) (search paths /run/opengl-driver-32/lib/dri, suffix _dri)
> libGL error: failed to load driver: radeonsi
> libGL error: MESA-LOADER: failed to open radeonsi: /lib32/libc.so.6: version `GLIBC_2.34' not found (required by /run/opengl-driver-32/lib/dri/radeonsi_dri.so) (search paths /run/opengl-driver-32/lib/dri, suffix _dri)
> libGL error: failed to load driver: radeonsi
> libGL error: MESA-LOADER: failed to open swrast: /lib32/libc.so.6: version `GLIBC_2.34' not found (required by /run/opengl-driver-32/lib/dri/swrast_dri.so) (search paths /run/opengl-driver-32/lib/dri, suffix _dri)
> libGL error: failed to load driver: swrast
> ```

This hints at a glibc version mismatch which is usually caused by one of the following reasons:
- nixos-rebuild updated glibc -> reboot to fix this
- LD_LIBRARY_PATH draws in older glibc versions -> unset
- you are on a distro using an older glibs, see previous point, otherwise impurities need to debugged.


As this works on nixos-unstale I am closing this.

**Closed by SuperSandro2000** 2023-02-18 20:54 UTC
Labels: 0.kind: bug, 6.topic: steam
