### ISSUE TITLE
json.exception.parse_error.101: ill-formed UTF-8 byte

### ISSUE THREAD

**Issue by dbeecham** [NixOS/nixpkgs#138636] opened 2021-09-20 11:54 UTC
### Describe the bug

I added a `flake.nix` to a empty git repository with the following content:

```
{
  outputs = { self, nixpkgs }: {
    defaultPackage.x86_64-linux = nixpkgs.legacyPackages.x86_64-linux.stdenv.mkDerivation {
      name = "hello";
      src = ./.;
    };
  };
}
```

The exact error message is

```
error: [json.exception.parse_error.101] parse error at line 55, column 178: syntax error while parsing value - invalid string: ill-formed UTF-8 byte; last read: '" \n    local fn=\"$1\";\n    local fd;\n    local magic;\n    exec {fd}< \"$fn\";\n    read -r -n 4 -u \"$fd\" magic;\n    exec {fd}>&-;\n    if [[ \"$magic\" = '�'
```

I ran `strace -s 65536 -f nix develop 2>&1 | tee out.strace` and found these leading up to the error

```
[pid 3378176] newfstatat(AT_FDCWD, "/nix/store/9n3in6vhab08s421vk6zhq81ic13lbyx-hello-env", {st_mode=S_IFREG|0444, st_size=57025, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 3378176] openat(AT_FDCWD, "/nix/store/9n3in6vhab08s421vk6zhq81ic13lbyx-hello-env", O_RDONLY|O_CLOEXEC) = 4
[pid 3378176] newfstatat(4, "", {st_mode=S_IFREG|0444, st_size=57025, ...}, AT_EMPTY_PATH) = 0
[pid 3378176] read(4, "{\n  \"bashFunctions\": {\n    \"_activatePkgs\":\" \\n    ...", 65536) = 57025
[pid 3378176] read(4, "", 65536)        = 0
[pid 3378176] close(4)                  = 0
[pid 3378176] getrusage(RUSAGE_SELF, {ru_utime={tv_sec=0, tv_usec=22099}, ru_stime={tv_sec=0, tv_usec=17447}, ...}) = 0
[pid 3378176] close(3)                  = 0
[pid 3378176] write(2, "error: [json.exception.parse_error.101] parse error at line 55, column 178: syntax error while parsing value - invalid string: ill-formed UTF-8 byte; last read: '\" \\n    local fn=\\\"$1\\\";\\n    local fd;\\n    local magic;\\n    exec {fd}< \\\"$fn\\\";\\n    read -r -n 4 -u \\\"$fd\\\" magic;\\n    exec {fd}>&-;\\n    if [[ \\\"$magic\\\" = '\376'\n", 328error: [json.exception.parse_error.101] parse error at line 55, column 178: syntax error while parsing value - invalid string: ill-formed UTF-8 byte; last read: '" \n    local fn=\"$1\";\n    local fd;\n    local magic;\n    exec {fd}< \"$fn\";\n    read -r -n 4 -u \"$fd\" magic;\n    exec {fd}>&-;\n    if [[ \"$magic\" = 'þ'
) = 328
[pid 3378176] exit_group(1)             = ?

```

the line that failed to parse is this line

```
    "isMachO":" \n    local fn=\"$1\";\n    local fd;\n    local magic;\n    exec {fd}< \"$fn\";\n    read -r -n 4 -u \"$fd\" magic;\n    exec {fd}>&-;\n    if [[ \"$magic\" = 'þíúÏ' || \"$magic\" = 'Ïúíþ' ]]; then\n        return 0;\n    else\n        if [[ \"$magic\" = 'þíúÎ' || \"$magic\" = 'Îúíþ' ]]; then\n            return 0;\n        else\n            if [[ \"$magic\" = 'Êþº¾' || \"$magic\" = '¾ºþÊ' ]]; then\n                return 0;\n            else\n                return 1;\n            fi;\n        fi;\n    fi\n",
```

### Steps To Reproduce
1. Create empty folder, run `git init` in it
2. Create above flake.nix file and add it to repo with `git add flake.nix`
3. `nix develop`

### Expected behavior

Development nix shell

### Additional context

output from `locale`:

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Nix version:

```
> nix --version
nix (Nix) 2.4pre20210802_47e96bb
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console

dbe@pp-ws-dbe ~/empty> nix-shell -p nix-info --run "nix-info -m"
error: anonymous function at /nix/store/jcsk94my3vszsm82s1a84j8pdk1nwhv3-nixos-20.03.2685.977000f149b/nixos/pkgs/top-level/default.nix:20:1 called with unexpected argument 'inNixShell'

       at /nix/store/jcsk94my3vszsm82s1a84j8pdk1nwhv3-nixos-20.03.2685.977000f149b/nixos/pkgs/top-level/impure.nix:84:1:

           83|
           84| import ./. (builtins.removeAttrs args [ "system" "platform" ] // {
             | ^
           85|   inherit config overlays crossSystem crossOverlays;

dbe@pp-ws-dbe ~/empty> nix shell nixpkgs#nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.72, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - channels(root): `"nixos-20.03.2685.977000f149b"`
 - channels(dbe): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`


```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by dbeecham** [comment] 2021-09-20 11:56
strace: [strace.txt](https://github.com/NixOS/nixpkgs/files/7195458/strace.txt)
env: [9n3in6vhab08s421vk6zhq81ic13lbyx-hello-env.txt](https://github.com/NixOS/nixpkgs/files/7195463/9n3in6vhab08s421vk6zhq81ic13lbyx-hello-env.txt)

**Comment by dbeecham** [comment] 2021-09-20 12:01
execsnoop during execution:

```
PCOMM            PID    PPID   RET ARGS
nix              3381810 3381795   0 /run/current-system/sw/bin/nix develop
git              3381820 3381810   0 /etc/profiles/per-user/dbe/bin/git -C /home/dbe/empty rev-parse --git-common-dir
git              3381821 3381810   0 /etc/profiles/per-user/dbe/bin/git -C /home/dbe/empty ls-files -z
```

and outputs from the commands

```
dbe@pp-ws-dbe ~/empty> git -C /home/dbe/empty rev-parse --git-common-dir                                                              1
.git
dbe@pp-ws-dbe ~/empty> git -C /home/dbe/empty ls-files -z
flake.lockflake.nix%
```

**Comment by teto** [comment] 2021-09-20 12:36
duplicate of https://github.com/NixOS/nixpkgs/issues/138157

**Closed by teto** 2021-09-20 12:36 UTC
Labels: 0.kind: bug
