### ISSUE TITLE
Requesting Electron on darwin

### ISSUE THREAD

**Issue by Eveeifyeve** [NixOS/nixpkgs#357731] opened 2024-11-21 01:16 UTC
## Issue description

Since electron build from source pr there is a lot of packages that don't have darwin support like element when electron should in theory work on darwin

### Steps to reproduce
1. build `element-desktop` on a darwin machine
2. The unsupported platform warning

## Technical details

```
 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.1.0, macOS 15.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.23.3`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/jfdpyszsgvsnz68y36qi65irx7r6a52q-source`
```

**Comment by TomaSajt** [comment] 2024-11-21 21:10
Element (desktop client for matrix) is called `element-desktop` inside nixpkgs, and should be able to be built, even on darwin.
The `element` package is unrelated.

**Comment by Eveeifyeve** [comment] 2024-11-22 13:55
> Element (desktop client for matrix) is called `element-desktop` inside nixpkgs, and should be able to be built, even on darwin. The `element` package is unrelated.

Well according to the package it only supports the platforms that electron are supported that being linux.

**Comment by TomaSajt** [comment] 2024-11-22 14:37
The non-source `electron` works fine on darwin.
Is the issue that you don't want to use the non-source `electron`?

By the way, what "electron build from source pr" are you talking about?

**Comment by Eveeifyeve** [comment] 2024-11-22 15:33
> The non-source `electron` works fine on darwin. Is the issue that you don't want to use the non-source `electron`?
yes but in this case element-desktop uses source.

> By the way, what "electron build from source pr" are you talking about?
pr https://github.com/NixOS/nixpkgs/pull/254423

**Comment by TomaSajt** [comment] 2024-11-22 16:07
I can't seem to find why it would use the source one if it wasn't supported.

Relevant lines I could find: https://github.com/NixOS/nixpkgs/blob/9069a281a73b9dcc3234c80418071f6783cace8b/pkgs/top-level/all-packages.nix#L7905
https://github.com/NixOS/nixpkgs/blob/9069a281a73b9dcc3234c80418071f6783cace8b/pkgs/top-level/all-packages.nix#L2322-L2325
https://github.com/NixOS/nixpkgs/blob/9069a281a73b9dcc3234c80418071f6783cace8b/pkgs/applications/networking/instant-messengers/element/element-desktop.nix#L156

Are perhaps using an overlay? Or an older release?

I can run `sudo nix build nixpkgs#element-desktop --system aarch64-darwin` on linux to get the successfully built element-desktop package for darwin. The fact that I can do this means it's already cached, so it should build fine on darwin.

**Comment by Eveeifyeve** [comment] 2024-11-22 16:28
> I can't seem to find why it would use the source one if it wasn't supported.
> 
> Relevant lines I could find:
> 
> https://github.com/NixOS/nixpkgs/blob/9069a281a73b9dcc3234c80418071f6783cace8b/pkgs/top-level/all-packages.nix#L7905
> 
> 
> https://github.com/NixOS/nixpkgs/blob/9069a281a73b9dcc3234c80418071f6783cace8b/pkgs/top-level/all-packages.nix#L2322-L2325
> 
> 
> https://github.com/NixOS/nixpkgs/blob/9069a281a73b9dcc3234c80418071f6783cace8b/pkgs/applications/networking/instant-messengers/element/element-desktop.nix#L156
> 
> Are you perhaps using an overlay? Or an older release?
> 
> I can run `sudo nix build nixpkgs#element-desktop --system aarch64-darwin` on linux to get the successfully built element-desktop package for darwin. The fact that I can do this means it's already cached, so it should build fine on darwin.

Well because your on Linux nix still recognises that your still on Linux even if you build it from there, if you were on a actual Darwin machine it would be different.

**Comment by TomaSajt** [comment] 2024-11-22 18:21
--system works if I don't have to actually build anything, because it's already cached.

Also checked on x86_64-darwin yesterday, and it works fine.

Are you overriding your electron somewhere?

How are you trying to build your element-desktop app? Could you send a snippet of code / config file.

**Comment by Eveeifyeve** [comment] 2024-11-26 05:04
> Also checked on x86_64-darwin yesterday, and it works fine.
huh maybe aarch54-darwin?

> Are you overriding your electron somewhere?

 Nope
> How are you trying to build your element-desktop app? Could you send a snippet of code / config file.

By adding the package to my config. https://github.com/eveeifyeve/dotfiles

**Comment by Eveeifyeve** [comment] 2024-11-28 09:44
It builds, but the problem is why is the search nixos website saying it only supports linux that is not right.

**Comment by Eveeifyeve** [comment] 2024-11-28 09:54
I think it's cached but I think depending on what it uses it still electron still needs to be on darwin as it could cause issues like this.

**Comment by TomaSajt** [comment] 2024-11-28 11:05
The website shows this because the website evaluates the meta tags on a linux machine. 
On linux electron = electron-source (which only works on linux) and on darwin electron = electron-bin (which has support for both platforms).

While I agree that darwin should ideally try to use electron-source, using electron-bin is fine, since it at least works.

**Comment by Eveeifyeve** [comment] 2024-11-28 12:35
> The website shows this because the website evaluates the meta tags on a linux machine. 
> On linux electron = electron-source (which only works on linux) and on darwin electron = electron-bin (which has support for both platforms).
> 
> While I agree that darwin should ideally try to use electron-source, using electron-bin is fine, since it at least works. 

Yeah, I am still going to keep this open as electron source is still not available on Darwin machines.

**Comment by emilylange** [comment] 2024-11-30 18:18
> Yeah, I am still going to keep this open as electron source is still not available on Darwin machines.

Duplicate of #296156 then. Closing.

**Closed by emilylange** 2024-11-30 18:18 UTC
Labels: 6.topic: darwin
