### ISSUE TITLE
Cachix breaks `nix-env -qaP` (missing override attribute)

### ISSUE THREAD

**Issue by BadDecisionsAlex** [NixOS/nixpkgs#65007] opened 2019-07-17 22:38 UTC
## Issue description

Cachix on master breaks `nix-env -qaP` and similar tools such as `nix-index` as a result of adding `override` to the package.
I pinned a previous version on my system to get things to behave properly again but this should get patched.

### Steps to reproduce

```sh
> nix-env -qaP
error: attribute 'override' missing, at /nix/store/1wm96xspd9vqf6avb40mfhdgl8zhfrm0-nixos-19.09pre185176.1036dc66416/nixos/pkgs/development/tools/cachix/default.nix:3:2
```

## Technical details

```sh
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.58, NixOS, 19.09pre185176.1036dc66416 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(camus): `"home-manager, nextbookit, nixos-mio"`
 - channels(root): `"nixos-19.09pre185176.1036dc66416, nixos-hardware, nixos-stable-18.09.2574.a7e559a5504"`
 - channels(guest): `"nixos-unstable-19.09pre183392.83ba5afcc96, nixpkgs-19.03.172979.8634c3b6199, nixpkgs-unstable-19.09pre183693.baa75f0c25a, nixos-19.03-19.03.172979.8634c3b6199"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by FRidh** [comment] 2019-07-18 08:36
I cannot reproduce the issue:
```
$ nix-env -f https://github.com/NixOS/nixpkgs/archive/1036dc664169b32613ec11b58cc1740c7511a340.tar.gz -qaP
```
Note the commit I fetch matches the Nixpkgs in which you have the issue.

cc @domenkozar

**Comment by domenkozar** [comment] 2019-07-18 08:42
Completely forgot about https://github.com/NixOS/nixpkgs/pull/57545, fixed in master.

**Closed by domenkozar** 2019-07-18 08:42 UTC

**Comment by domenkozar** [comment] 2019-07-18 08:43
@grahamc shouldn't ofborg detect this?

**Comment by FRidh** [comment] 2019-07-18 08:50
@BadDecisionsAlex Do you happen to have an overlay extending Haskel Packages?
https://github.com/NixOS/nixpkgs/pull/57545#issuecomment-473534108

**Comment by BadDecisionsAlex** [comment] 2019-07-18 12:17
@FRidh
Yeah I do.

**Comment by FRidh** [comment] 2019-07-18 13:27
So that's it then. See the comment I linked. That's why ofBorg did not detect it, because it was actually in Nixpkgs, though probably the way the set can be overridden needs to be improved.
