### ISSUE TITLE
NixOS 24.11 Modrinth seq fault

### ISSUE THREAD

**Issue by SZanko** [NixOS/nixpkgs#369264] opened 2024-12-30 00:04 UTC
## Describe the bug

When I try to execute Modrinth it crashes with an seq fault 

## Steps To Reproduce

1.  `NIXPKGS_ALLOW_UNFREE=1 nix-shell -p --impure modrinth-app`
2.  `ModrinthApp`
3.  Segmentation fault (memory dump written)

## Expected behavior

Launches Modrinth without crashing

## Metadata

- system: `"x86_64-linux"`
 - host os: `Linux 6.6.67, NixOS, 24.11 (Vicuna), 24.11.20241227.d49da4c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.11`
 - nixpkgs: `/nix/store/salp9r9j3pj9cwqf06wchs16hy8g882k-source`

## Notify maintainers

@getchoo 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by getchoo** [comment] 2024-12-30 02:36
Duplicate of #359820

**Closed** 2024-12-30 14:29 UTC
Labels: 0.kind: bug
