### ISSUE TITLE
Package request: Pyfa

### ISSUE THREAD

**Issue by VanDoge** [NixOS/nixpkgs#335069] opened 2024-08-16 09:20 UTC
EvE Online fitting tool

Pyfa, short for python fitting assistant, allows you to create, experiment with, and save ship fittings without being in game. Open source and written in Python, it is available on any platform where Python 3 and wxWidgets are available, including Windows, macOS, and Linux.

**Metadata**

* homepage URL: https://github.com/pyfa-org/Pyfa
* source URL: https://github.com/pyfa-org/Pyfa
* license: GPL-3.0 license 
* platforms: linux, mac, win

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Sigmanificient** [comment] 2024-08-17 19:59
#314934

**Comment by Majiir** [comment] 2024-08-22 18:06
Duplicate of https://github.com/NixOS/nixpkgs/issues/239454

It looks like there have been a couple attempts to package the appimage since there were challenges building from source. When I tried to build from source, I ran into the sqlalchemy version problem noted [here](https://github.com/NixOS/nixpkgs/issues/239454#issuecomment-1667089655).

**Comment by gepbird** [comment] 2024-10-19 07:59
Fixed by https://github.com/NixOS/nixpkgs/pull/314934

**Closed by gepbird** 2024-10-19 07:59 UTC
Labels: 6.topic: python, 0.kind: packaging request
