### ISSUE TITLE
Clockify

### ISSUE THREAD

**Issue by tomgtc** [NixOS/nixpkgs#146395] opened 2021-11-17 14:31 UTC
**Clockify**
_desktop version of web timetracking app_

**Metadata**

* homepage URL: http://clockify.me
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by WolfangAukang** [comment] 2021-11-19 01:09
I was [able](https://github.com/WolfangAukang/nixpkgs/commit/b5703dfc4b2a2afd0d2dcb1a29e08fab79cd9f88) to package it, but I would like someone to try it first and see if it works as intended.

**Comment by baronleonardo** [comment] 2021-11-24 15:09
@WolfangAukang I had tested it and it works like a charm

**Comment by WolfangAukang** [comment] 2021-11-26 12:52
Merged.

**Closed by WolfangAukang** 2021-11-26 12:52 UTC
Labels: 0.kind: packaging request
