### ISSUE TITLE
Add support for zfs's mount generator

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#89396] opened 2020-06-03 10:07 UTC
Since zfs 0.8.4 we have proper systemd support for zfs datasets.

https://github.com/openzfs/zfs/commit/55d80e651a8c19919b8ee6a1c05fb36ad97ab5ad

This can be used to mount zfs datasets with zfs's native mount without relying on legacy mounts.

**Comment by Mic92** [comment] 2020-11-30 12:24
still an issue.

**Comment by Mic92** [comment] 2021-06-03 05:34
.

**Comment by lheckemann** [comment] 2021-06-03 10:01
Duplicate of #62644

**Closed by lheckemann** 2021-06-03 10:01 UTC
