### ISSUE TITLE
Reconsider exporting LD, AS, STRIP etc. in non-cross builds

### ISSUE THREAD

**Issue by dezgeg** [NixOS/nixpkgs#29846] opened 2017-09-27 13:22 UTC
After 3 months of 093cc00cdd9d8cf31ecce5bc1dd3645c460a1b98 being in and roughly 30 variations of unsetting LD, CPP, AS or `LD=$CC` etc. being committed to Nixpkgs as fallout of that commit, it still seems to be causing problems (e.g. https://github.com/NixOS/nixpkgs/pull/29128). So it sounds to me that doing that isn't very safe for all the random build systems out there. Also some of the failures are very obscure, e.g. c24820db93afe3dbffba2d9031c0c496029e363d...

@edolstra @Ericson2314

**Comment by edolstra** [comment] 2017-09-27 14:08
I hadn't noticed that commit before, but it seems pretty ugly to spam the environment with variables like `SIZE=size` and `CMD=windres` (eh?). Having `LD=ld` definitely seems problematic.

**Comment by edolstra** [comment] 2017-09-27 14:09
Maybe revert this on the 17.09 branch? Otherwise we're stuck with it forever.

**Comment by globin** [comment] 2017-09-27 18:02
👎 on reverting this a day before releasing, that will block us from releasing for a few days.

I definitely think this can be in a release and changed afterwards, I'd personally call this an internal implementation detail prone to change and not something we have to stick for forever. It would be nice to mention it in the release notes but definitely something we can change again.

Apart from that as far as I am aware all issues caused by this have been fixed by now and otherwise would only occur with cross builds which is specifically something I'd say we don't want.. IMHO we should keep the environment and configuration of cross builds as close to the non-cross builds as possible. OTOH we might want to investigate if a cleaner implementation of this is possible somehow.

**Comment by Ericson2314** [comment] 2017-09-28 18:44
Sorry to take a while to respond to this; was busy preparing a talk (on my cross compilation work).

@globin basically said everything I wanted to say. Sure, this has been a slight nuisance for native builds, but temporarily while it still new. Going forward, it simplifies things by unifying with the cross case, which is essential if we wish for that to not bit-rot. FWIW, Exherbo, the distribution which pioneered the method of unifying cross and native I've taken, does this and needs the same overrides too: https://git.exherbo.org/arbor.git/tree/packages/dev-lang/perl/perl-5.exlib#n115 --- I only found the overrides after we started adding them too!

On the documentation side, I think I've covered this fairly well already. See: https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-1709.xml#L283 and https://github.com/NixOS/nixpkgs/blob/master/doc/stdenv.xml#L1371.

**Comment by Ekleog** [comment] 2018-10-29 01:08
(triage) Well, if this has been this way for now more than a year, I guess it's now working and the unification is all good? and the `CMD` environment variable has been taken care of in https://github.com/NixOS/nixpkgs/pull/29396. Time to close, maybe?

**Closed** 2018-10-29 17:50 UTC
Labels: 0.kind: regression, 6.topic: cross-compilation
