### ISSUE TITLE
tor-browser-bundle-bin does not have an audio

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#127344] opened 2021-06-18 11:47 UTC
### Steps To Reproduce
0. Install `tor-browser-bundle-bin`
1. Attempt to play any video and expect to not have an audio

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[kreyren@leonid:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.43, NixOS, 21.05.961.1f91fd10406 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.961.1f91fd10406"`
 - channels(kreyren): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```
  
![image](https://user-images.githubusercontent.com/11302521/122556639-0d055300-d03c-11eb-85a5-cc49792b8031.png)

**Comment by Kreyren** [comment] 2021-06-18 11:49
CC @offlinehacker @matejc @thoughtpolice @joachifm @hax404 @scaredmushroom @KarlJoad

**Comment by FliegendeWurst** [comment] 2021-06-18 13:55
This error message in the log seems relevant:
```
1624023996.014 [apulse 63095] Z pa_context_set_subscribe_callback c=0x7faa23703e80, cb=0x7faa31f8d760, userdata=0x7faa23696a60
1624023996.014 [apulse 63095] Z pa_context_subscribe c=0x7faa23703e80, m=0x0080, cb=0x7faa31f8e680, userdata=0x7faa23696a60
1624023996.014 [apulse 63095] Z pa_context_errno c=0x7faa23703e80
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
[apulse] [error] do_connect_pcm: can't open playback device "plug:dmix". Error code -2 (No such file or directory)
[apulse] [error] do_connect_pcm: failed to open ALSA device. Apulse does no resampling or format conversion, leaving that task to ALSA plugins. Ensure that selected device is capable of playing a particular sample format at a particular rate. They have to be supported by either hardware directly, or by "plug" and "dmix" ALSA plugins which will perform required conversions on CPU.
[Child 63226, MediaDecoderStateMachine #1] WARNING: 7f2b22e5c710 OpenCubeb() failed to init cubeb: file /var/tmp/build/firefox-ce3b93d06afb/dom/media/AudioStream.cpp, line 331
[Child 63226, MediaDecoderStateMachine #1] WARNING: Decoder=7f2b22bdd000 [OnMediaSinkAudioError]: file /var/tmp/build/firefox-ce3b93d06afb/dom/media/MediaDecoderStateMachine.cpp, line 3891
[Child 63226, MediaDecoderStateMachine #1] WARNING: Decoder=7f2b22bdd000 Decode error: NS_ERROR_DOM_MEDIA_MEDIASINK_ERR (0x806e000b) - OnMediaSinkAudioError: file /var/tmp/build/firefox-ce3b93d06afb/dom/media/MediaDecoderStateMachine.cpp, line 3470
```

Audio playback works fine when `pulseaudioSupport` is enabled. Is there a reason `apulse` is used by default (since 09a09c892c117513671f61489fb2ad51336d3966)?

**Comment by rnhmjoj** [comment] 2021-06-19 13:19
Is tor-browser built with alsa support? If so, the wrapper is missing `alsaLib`. Firefox used to have the same issue: https://github.com/NixOS/nixpkgs/pull/101314/files

**Comment by Artturin** [comment] 2021-11-21 02:12
Dupe of https://github.com/NixOS/nixpkgs/issues/93316

**Closed** 2021-11-21 02:12 UTC
Labels: 0.kind: bug
