### ISSUE TITLE
please don't force push to haskell-updates

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#113374] opened 2021-02-17 07:50 UTC
It just unnecessarily creates a lot of merge conflicts.
The commit in question: https://github.com/NixOS/nixpkgs/commit/d4d82d63fa9109374cfd10abfafed21933553a6c
cc @peti

**Comment by peti** [comment] 2021-02-17 08:35
I rebase haskell-updates once per week before I merge to clean up the history. This is kinda important because we have so many automatic commits to the branch that would otherwise create an unreadable mess of back and forth merges.

**Comment by poscat0x04** [comment] 2021-02-17 11:48
Maybe we should use the "Rebase and merge" option for haskell-updates then?
cc @cdepillabout

**Comment by cdepillabout** [comment] 2021-02-17 12:06
I'm in full support of whatever is easiest for @peti when he does the weekly updates.

**Comment by maralorn** [comment] 2021-02-17 17:53
Here is what we don‘t do: We don‘t modify the history of haskell-updates during the week.

Here is what we do: On friday evening we cleanup the history of haskell-updates and merge it into master. Then we create a new branch incidentally also called haskell-updates, which at this point is a french branch-off from master. And because there happened a rebase in-between there is no way to fast-forward from the old branch to the new branch.

I don‘t think there is a solution to your problem other than a) not having an ugly history from the start (I don‘t see that happening our whole testing relies on the nightly updates) or b) not rebasing during merge. (Not sure about that solution.)

Incidentally not rebasing would be easier during merge. @peti often has to do some magic incantation to get the rebase right and curses a lot while doing so.^^

Anyways @poscat0x04, I am curious, can you elaborate a bit how that force-pushing actually introduces merge-conflicts which we wouldn‘t have without?

**Comment by poscat0x04** [comment] 2021-02-18 11:36
Yeah, that merge conflict on my pull request was caused by `hackage-packages.nix` which I did not touch at all. While force-pushing doesn't guarantee to create merge conflicts, I think it should be avoided as much as possible on a codebase that multiple people are working on.

If the whole point of rewriting history is to remove merge commits then those merge commits can be entirely avoided by using the "Rebase and merge" option on GitHub and using `git pull --rebase` instead of `git pull --merge`.

**Comment by turboMaCk** [comment] 2021-02-18 17:50
@poscat0x04 I don't think this is to avoid __merge__ commits.

> we have so many automatic commits to the branch

@peti  talks about all commits, not just merge commits. Point is to squash some commits etc.

I also think your suggestion would not help because if you base your branch on a `haskell-updates` and then the commits from haskell-updates would change __which has happen during rebase of haskell-updates against master during merge__ you would still have the same conflicts. These github options as well as `--rebase` and `--ff-only` flags really work only when the target branch doesn't change underneath you. The problem is that `haskell-updates` __must change__ - it must be rebased so it could be merged to master. As far as I know there is no way around this.

The only solution that would prevent these type of conflicts would IMO be to stop rebasing `haskell-updates` which means

a. [never merge](https://imgs.xkcd.com/comics/haskell_2x.png) haskell-updates to master
b. merge `haskell-updates` as `--no-ff`, do the mess in `master` (merge commit jazz) and never ever update `haskell-updates`

Unless I'm missing something (which is possible) I think the current flow is about as sensible as it can be.

What I would recommend is that in case you hit this issue you just force pull haskell-updates, merge haskell-updates to your branch wiith and do `git diff --name-only --diff-filter=U | xargs git checkout --theirs`

**Comment by maralorn** [comment] 2021-02-18 20:53
This is indeed not about avoiding merge commits.

@turboMaCk I feel like your options are overcomplicating this a bit. I am pretty sure the by far easiest option would be to just not rebase anything before merging. And it wouldn‘t be that bad. But still I don‘t think rest of nixpkgs-land would be happy about it.

**Comment by maralorn** [comment] 2021-06-07 13:52
We don‘t do force pushes on haskell-updates anymore.

**Closed by maralorn** 2021-06-07 13:52 UTC
Labels: 6.topic: haskell, infrastructure
