### ISSUE TITLE
mysql cant create custom datadir except default value ？

### ISSUE THREAD

**Issue by prehonor** [NixOS/nixpkgs#151093] opened 2021-12-17 13:25 UTC
This mysql config segment：
services.mysql = {
    user = "root";
    enable = true;
    package = pkgs.mysql80;
    #dataDir = "/ah/prehonor/Programmers/mysql/data_2";
    configFile = pkgs.writeText "my.cnf" ''
      [mysqld]
     #   datadir=/ah/prehonor/Programmers/mysql/data_2 # /var/lib/mysql
        plugin-load-add=auth_socket.so
        user=root
        port=3306
        character_set_server=utf8mb4

        performance_schema=OFF
        skip-external-locking
        max_connections=10
        performance_schema_max_table_instances=60
        table_definition_cache=60
        table_open_cache=16
        innodb_buffer_pool_size=16M
  '';
   
  };
when nixos-rebuild switch ， getting 
Can't create directory '/ah/prehonor/Programmers/mysql/data_2/' (OS errno 13 - Permission denied)

**Comment by aanderse** [comment] 2021-12-17 20:37
I notice you have `services.mysql.dataDir` commented it. If so then the directory won't be created.

**Comment by prehonor** [comment] 2021-12-18 00:49
> I notice you have `services.mysql.dataDir` commented it. If so then the directory won't be created.

Sorry, I 
I got it wrong， this is the right setting：
  services.mysql = {
    # user = "root";
    enable = true;
    package = pkgs.mysql80;
    dataDir = "/ah/prehonor/Programmers/mysql/data_2";
    configFile = pkgs.writeText "my.cnf" ''
      [mysqld]
        datadir=/ah/prehonor/Programmers/mysql/data_2 # /var/lib/mysql
        socket = /tmp/mysql.sock
        plugin-load-add=auth_socket.so
        user=root
        port=3306
        character_set_server=utf8mb4

        performance_schema=OFF
        skip-external-locking
        max_connections=10
        performance_schema_max_table_instances=60
        table_definition_cache=60
        table_open_cache=16
        innodb_buffer_pool_size=16M
  '';
   
  }; 

I got this ：
● mysql.service - MySQL Server
     Loaded: loaded (/nix/store/qb0c265yg7rymkhhkbrpyjavcq3hbhk7-unit-mysql.service/mysql.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2021-12-18 08:43:57 CST; 2min 29s ago
    Process: 6291 ExecStartPre=/nix/store/wvc0hhik0q4m0948v2h16v21i481ichy-unit-script-mysql-pre-start/bin/mysql-pre-start (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
        CPU: 148ms

Dec 18 08:43:57 prehonor mysql-pre-start[6292]: mysqld: Can't create directory '/ah/prehonor/Programmers/mysql/data_2/' (OS errno 13 - Permission denied)
Dec 18 08:43:57 prehonor mysql-pre-start[6292]: 2021-12-18T00:43:57.475833Z 0 [Warning] [MY-000081] [Server] option 'table_definition_cache': unsigned value 60 adjusted to 400.
Dec 18 08:43:57 prehonor mysql-pre-start[6292]: 2021-12-18T00:43:57.479586Z 0 [Warning] [MY-010143] [Server] Ignoring user change to 'mysql' because the user was set to 'root' earlier on the command line
Dec 18 08:43:57 prehonor mysql-pre-start[6292]: 2021-12-18T00:43:57.484167Z 0 [System] [MY-013169] [Server] /nix/store/9ciijxc3m591zasjnxyhfyrq8v1bv6rk-mysql-8.0.26/bin/mysqld (mysqld 8.0.26) initializing of server in progress as proc>
Dec 18 08:43:57 prehonor mysql-pre-start[6292]: 2021-12-18T00:43:57.500244Z 0 [ERROR] [MY-013236] [Server] The designated data directory /ah/prehonor/Programmers/mysql/data_2/ is unusable. You can remove all files that the server adde>
Dec 18 08:43:57 prehonor mysql-pre-start[6292]: 2021-12-18T00:43:57.501023Z 0 [ERROR] [MY-010119] [Server] Aborting
Dec 18 08:43:57 prehonor mysql-pre-start[6292]: 2021-12-18T00:43:57.504718Z 0 [System] [MY-010910] [Server] /nix/store/9ciijxc3m591zasjnxyhfyrq8v1bv6rk-mysql-8.0.26/bin/mysqld: Shutdown complete (mysqld 8.0.26)  Source distribution.
Dec 18 08:43:57 prehonor systemd[1]: mysql.service: Control process exited, code=exited, status=1/FAILURE
Dec 18 08:43:57 prehonor systemd[1]: mysql.service: Failed with result 'exit-code'.
Dec 18 08:43:57 prehonor systemd[1]: Failed to start MySQL Server.

**Comment by aanderse** [comment] 2021-12-18 00:58
What happens if you run the following command in a terminal as `root` and then start the service?
```sh
mkdir -p /ah/prehonor/Programmers/mysql/data_2
```

Can you provide some additional context about your custom `dataDir` please? Is it on a mounted drive? Special file system? What permissions does the existing folder structure have?

I also noticed that you didn't set `services.mysql.user`, which is a problem if you set `user = root` in your `services.mysql.configFile` because `systemd` will run the service as an unprivileged user `mysql`, but the database will try to escalate privileges to `root`.

**Comment by prehonor** [comment] 2021-12-18 01:25
> I changed setting：
services.mysql = {
    user = "root";
    enable = true;
    package = pkgs.mysql80;
    dataDir = "/ah/prehonor/Programmers/mysql/data_2";
    configFile = pkgs.writeText "my.cnf" ''
      [mysqld]
        datadir=/ah/prehonor/Programmers/mysql/data_2 # /var/lib/mysql
        socket = /tmp/mysql.sock
        plugin-load-add=auth_socket.so
        user=root
        port=3306
        character_set_server=utf8mb4

        performance_schema=OFF
        skip-external-locking
        max_connections=10
        performance_schema_max_table_instances=60
        table_definition_cache=60
        table_open_cache=16
        innodb_buffer_pool_size=16M
  '';
   
  };
I got same error.
Filesystem           Type     1K-blocks      Used Available Use% Mounted on
devtmpfs             devtmpfs    608884         0    608884   0% /dev
tmpfs                tmpfs      6088820    119064   5969756   2% /dev/shm
tmpfs                tmpfs      3044412      6428   3037984   1% /run
tmpfs                tmpfs      6088816       816   6088000   1% /run/wrappers
/dev/sdb2            ext4     122031060  43741420  72047784  38% /
/dev/dm-9            ext4      30832548  22621380   6621920  78% /var
/dev/sdb1            vfat        523248     25288    497960   5% /boot
/dev/mapper/vg-home  ext4     463404848 233076096 208795796  53% /gh
/dev/mapper/vg-nopt  ext4      20511312     45092  19401260   1% /opt
/dev/mapper/vg-nhome ext4     205899752  80439112 115986204  41% /home
/dev/mapper/vg-ahome ext4     308587328 203370636  90499376  70% /ah
/dev/mapper/vg-ntmp  ext4      10255636     98592   9616372   2% /tmp
tmpfs                tmpfs      1217760        60   1217700   1% /run/user/1000

ls -al /ah
total 28
drwxr-xr-x  4 prehonor users  4096 May  1  2020 .
drwxr-xr-x 22 root     root   4096 Oct 13 09:52 ..
drwx------  2 prehonor users 16384 Oct 29  2019 lost+found
drwx------ 16 prehonor users  4096 Dec 13 12:53 prehonor

ls -al /ah/prehonor/
total 188
drwx------ 16 prehonor users   4096 Dec 13 12:53 .
drwxr-xr-x  4 prehonor users   4096 May  1  2020 ..


ls -al /ah/prehonor/Programmers/
total 234224
drwxr-xr-x 15 prehonor users      4096 Dec 17 20:35 .
drwx------ 16 prehonor users      4096 Dec 13 12:53 ..

ls -al /ah/prehonor/Programmers/mysql/
total 24
drwxrwxrwx  6 prehonor users 4096 Dec 18 09:18 .
drwxr-xr-x 15 prehonor users 4096 Dec 17 20:35 ..

**Comment by aanderse** [comment] 2021-12-18 01:27
I'll attempt to reproduce your problem and then come up with a solution for it over the next few days. I believe you have provided all the relevant information I need. Thank you.

**Comment by prehonor** [comment] 2021-12-18 01:27
My nix config：https://pastebin.ubuntu.com/p/DWRjwTJZTg/

**Comment by aanderse** [comment] 2021-12-19 01:38
I think this is a configuration that will work for you:
```nix
  services.mysql = {
    enable = true;
    package = pkgs.mysql80;
    user = "prehonor";
    group = "users";
    dataDir = "/ah/prehonor/Programmers/mysql/data_2";
    settings = {
      mysqld = {
        # socket = "/tmp/mysql.sock"; -> our module is hard coded to expect /run/mysql/mysqld.sock
        plugin-load-add = "auth_socket.so";
        character_set_server = "utf8mb4";
        performance_schema = false;
        skip-external-locking = true;
        max_connections = 10;
        performance_schema_max_table_instances = 60;
        table_definition_cache = 60;
        table_open_cache = 16;
        innodb_buffer_pool_size = "16M";
      };
    };
  };
```

Let me know if that solves your problem.

**Comment by prehonor** [comment] 2021-12-19 13:16
It works,but why?

**Comment by aanderse** [comment] 2021-12-19 13:33
You should avoid the `configFile` option unless you have a very specific need for it. This option is considered "advanced" and requires you to understand the `mysql` NixOS module. Using `services.mysql.*` and `services.mysql.settings.*` are a better way to use this module.

> It works,but why?

Some of the values you specified in your configuration file conflicted with what the NixOS `mysql` module expected.

Specifically:
- you were trying to set the user `mysql` runs as in your `services.mysql.configFile` file which conflicted with the NixOS modules `services.mysql.user` definition -> use `services.mysql.user` instead
- you were trying to set the data directory `mysql` uses in your `services.mysql.configFile` file which conducted with the NixOS module -> use `services.mysql.dataDir` instead

I noticed that the `mysql` module makes **many** assumptions that are not documented for the user. I'm hoping to create a series of PRs to improve the situation with this module so the documentation is more clear and there are fewer hard coded assumptions.

If you have any additional questions before we close this issue please don't hesitate to ask. Additionally, if you have any suggestions on documentation improvements based on your experience I would appreciate the feedback.

Thanks.

**Comment by prehonor** [comment] 2021-12-19 14:37
> You should avoid the `configFile` option unless you have a very specific need for it. This option is considered "advanced" and requires you to understand the `mysql` NixOS module. Using `services.mysql.*` and `services.mysql.settings.*` are a better way to use this module.
> 
> > It works,but why?
> 
> Some of the values you specified in your configuration file conflicted with what the NixOS `mysql` module expected.
> 
> Specifically:
> 
> * you were trying to set the user `mysql` runs as in your `services.mysql.configFile` file which conflicted with the NixOS modules `services.mysql.user` definition -> use `services.mysql.user` instead
> * you were trying to set the data directory `mysql` uses in your `services.mysql.configFile` file which conducted with the NixOS module -> use `services.mysql.dataDir` instead
> 
> I noticed that the `mysql` module makes **many** assumptions that are not documented for the user. I'm hoping to create a series of PRs to improve the situation with this module so the documentation is more clear and there are fewer hard coded assumptions.
> 
> If you have any additional questions before we close this issue please don't hesitate to ask. Additionally, if you have any suggestions on documentation improvements based on your experience I would appreciate the feedback.
> 
> Thanks.

Well,I need learn more about  mysql and nixos mysql module on my own，thank you

**Closed** 2021-12-19 14:37 UTC
Labels: 0.kind: bug, 6.topic: nixos
