### ISSUE TITLE
Build failure: gaphor (2.8.2)

### ISSUE THREAD

**Issue by schuelermine** [NixOS/nixpkgs#316868] opened 2024-06-03 10:37 UTC
### Steps To Reproduce

1. build *gaphor*

### Build log

```
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pypa-build-hook
Using pypaBuildPhase
Sourcing python-runtime-deps-check-hook
Using pythonRuntimeDepsCheckHook
Sourcing pypa-install-hook
Using pypaInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/w07w8hahc26aaf87qdnln1zwr8h3ds8h-gaphor-2.8.2.tar.gz
source root is gaphor-2.8.2
setting SOURCE_DATE_EPOCH to timestamp 1643581293 of file gaphor-2.8.2/PKG-INFO
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
Executing pypaBuildPhase
Creating a wheel...
* Getting build dependencies for wheel...
* Building wheel...
2mSuccessfully built gaphor-2.8.2-py3-none-any.whl2m
Finished creating a wheel...
Finished executing pypaBuildPhase
@nix { "action": "setPhase", "phase": "pythonRuntimeDepsCheckHook" }
Running phase: pythonRuntimeDepsCheckHook
Executing pythonRuntimeDepsCheck
Checking runtime dependencies for gaphor-2.8.2-py3-none-any.whl
  - gaphas<4.0.0,>=3.1.0 not satisfied by version 4.0.0
  - jedi<0.19.0,>=0.18.1 not satisfied by version 0.19.1
```

### Notify maintainers

@WolfangAukang

### Metadata

- system: `"x86_64-linux"`
- host os: `Linux 6.9.2, NixOS, 24.11 (Vicuña), 24.11.20240529.ad57eef`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.18.2`
- nixpkgs: `/nix/store/qgbn0imyridkb9527v6gnv6z3jzzprb9-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dawidd6** [comment] 2024-06-03 12:20
Duplicate of https://github.com/NixOS/nixpkgs/issues/291281

**Closed by dawidd6** 2024-06-03 12:20 UTC
Labels: 0.kind: build failure
