### ISSUE TITLE
wkhtmltopdf is using deprecated qtwebkit

### ISSUE THREAD

**Issue by Schweber** [NixOS/nixpkgs#209680] opened 2023-01-08 11:59 UTC
### Describe the bug
`wkhtmltopdf` is using a deprecated versioin of `qtwebkit`. `qtwebkit` also has to be compiled on the users PC which takes a while.

### Steps To Reproduce
1. add `wkhtmltopdf` to `environment.systemPackages`
2. rebuild Nixos

### Expected behavior
`wkhtmltopdf` doesn't use `qtwebkit` but only the needed libraries.

Please see https://github.com/NixOS/nixpkgs/issues/53079 and https://github.com/NixOS/nixpkgs/issues/208707#issuecomment-1374802438

### Notify maintainers
@jb55

**Comment by wegank** [comment] 2023-01-08 13:10
The expected behaviour doesn't seem to be possible (wkhtmltopdf/wkhtmltopdf#3391), and since the project is abandoned upstream, I have no doubt that the project will be removed from nixpkgs in the future.

Closing in favour of #53079.

**Closed by wegank** 2023-01-08 13:10 UTC
Labels: 0.kind: bug
