### ISSUE TITLE
gnome-shell doesn't see new applications without restarting

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#87668] opened 2020-05-12 13:43 UTC
**Describe the bug**
When installing e.g. Slack in my user account, it creates the `slack.desktop` file in `.nix-profile/share/applications` and updates `mimeinfo.cache` as well.

However, Gnome-shell doesn't know about these applications until you restart it (for normal users this means actually rebooting), a bit drastic.

**To Reproduce**
1. Run gnome3 as your desktop
2. get Slack in your profile (nix-env or home-manager)
3. notice gnome-shell doesn't know about Slack

**Expected behavior**
NixOS would kick gnome-shell into rescanning

**Additional context**
It could be that gnome-shell has listeners on the mimeinfo.cache files, but they don't work on NixOS since all store files are immutable and have the same mtime. Furthermore, the parent directories are symlinks.

It seems to me that we need to patch gnome-shell to e.g. poll the inode of the cache files or fix the listener to understand trees of symlinks.

**Notify maintainers**
      @hedning
      @jtojnar
      @worldofpeace

**Comment by emilazy** [comment] 2020-05-12 13:45
Duplicate of #12757, #86647.

**Closed by emilazy** 2020-05-12 13:45 UTC
Labels: 0.kind: bug

**Comment by emilazy** [comment] 2020-05-12 13:46
(I agree that patching gnome-shell seems like probably the best fix there, though I wonder if we couldn't hack something up by making our own shadow symlink tree and ensuring stuff gets touched?)
