### ISSUE TITLE
`remarshal` failed to be installed

### ISSUE THREAD

**Issue by astrojhgu** [NixOS/nixpkgs#159522] opened 2022-02-12 12:06 UTC
### Describe the bug
`remarshal` failed to install

### Steps To Reproduce
1. run `nix-shell -p remarshal`
Immediately fails 

### Expected behavior

It should be installed successfully.

### Screenshots
Error message:
```
ERROR: Could not find a version that satisfies the requirement tomlkit<0.8,>=0.7 (from remarshal) (from versions: none)
ERROR: No matching distribution found for tomlkit<0.8,>=0.7
error: builder for '/nix/store/1g28d5b91w01irxpqry05a0vrhzays05-remarshal-0.14.0.drv' failed with exit code 1;
       last 10 log lines:
       > Finished executing pipBuildPhase
       > installing
       > Executing pipInstallPhase
       > /build/source/dist /build/source
       > Processing ./remarshal-0.14.0-py3-none-any.whl
       > Requirement already satisfied: u-msgpack-python<3.0,>=2.6 in /nix/store/nm9kasrf7iq4n2vv7lf6vma7y0yrrc1d-python3.9-u-msgpack-python-2.7.1/lib/python3.9/site-packages (from remarshal==0.14.0) (2.7.1)
       > Requirement already satisfied: cbor2<6.0,>=5.1 in /nix/store/58ca4fc7wzsc2d2xmxywyx7669q4n0m8-python3.9-cbor2-5.4.2/lib/python3.9/site-packages (from remarshal==0.14.0) (5.4.2)
       > Requirement already satisfied: PyYAML in /nix/store/px28dhnb50z2cj2gg630m5dxplwc4wmk-python3.9-PyYAML-6.0/lib/python3.9/site-packages (from remarshal==0.14.0) (6.0)
       > ERROR: Could not find a version that satisfies the requirement tomlkit<0.8,>=0.7 (from remarshal) (from versions: none)
       > ERROR: No matching distribution found for tomlkit<0.8,>=0.7
       For full logs, run 'nix log /nix/store/1g28d5b91w01irxpqry05a0vrhzays05-remarshal-0.14.0.drv'.
```

### Additional context
This error happens if I enable `services.dnscrypt-proxy2.enable`.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.98, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0`
 - channels(root): `"nixos"`
 - channels(astrojhgu): `"nixos-22.05pre349234.945ec499041"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by zowoq** [comment] 2022-02-12 12:11
Duplicate of #159423

Fixed in https://github.com/NixOS/nixpkgs/pull/159074.

https://nixpk.gs/pr-tracker.html?pr=159074

I'll leave this open until the fix lands in `nixos-unstable`.

**Comment by harrisonthorne** [comment] 2022-02-19 22:57
Is there a workaround to get `remarshal` working for now? Tried to use an overlay to override it with the version from `nixos-unstable-small` but that didn't work.

```
      nextOverlay = final: prev:
        let
          next-pkgs = import nixos-unstable-small { inherit (prev) system; };
        in
        {
          inherit (next-pkgs) kitty remarshal;
        };

```

**Comment by bobvanderlinden** [comment] 2022-02-19 23:03
The next evaluation of nixos-unstable should fix it, due to https://github.com/NixOS/nixos-org-configurations/pull/206 having been merged.
It was confirmed that it solves the issue with large gnome isos.

Hydra already has the build for nixos-unstable in its queue, but apparently hydra is quite busy with other things as well. (https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents)

**Comment by zowoq** [comment] 2022-02-20 03:36
`nixos-unstable` channel has updated.

**Closed by zowoq** 2022-02-20 03:36 UTC
Labels: 0.kind: bug

**Comment by setkeh** [comment] 2022-02-21 12:04
> `nixos-unstable` channel has updated.

Can confirm this update has resolved the issue.
