### ISSUE TITLE
Mangohud no longer appears when loading games

### ISSUE THREAD

**Issue by THERAAB** [NixOS/nixpkgs#230978] opened 2023-05-09 23:56 UTC
### Describe the bug

Mangohud no longer appears on gnome/wayland when opening a game.

   "rev": "d6b863fd9b7bb962e6f9fdf292419a775e772891", (works)
   "rev": "1a411f23ba299db155a5b45d5e145b85a7aafc42", (doesn't)

### Steps To Reproduce
1. Launch a game on gnome/wayland
2. Mangohud doesn't appear even when enabled (worked in previous revision of nixpkgs above)
3. ...

### Expected behavior
Mangohud shows system stats

### Notify maintainers
@kira-bruneau  @r-ryantm 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
➜ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.1, NixOS, 23.05 (Stoat), 23.05.20230506.897876e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/zjpd6dn9kza8zl3l17cwgyifsxbvi3nb-source`
```

**Comment by IceDBorn** [comment] 2023-05-13 07:16
I have the same problem too. I'm using Hyprland btw.

**Comment by kira-bruneau** [comment] 2023-05-13 13:37
Oh weird. I'll try looking into this. The only thing that really sticks out to me in the diff is possibly #228870? - but it seems unlikely. I'll do a git bisect to try to narrow it down better.

**Comment by THERAAB** [comment] 2023-05-14 12:01
If it helps you narrow down, here's my repo with the exact commit where mangohud stopped working. If I revert back to previous commit mangohud starts working again: https://github.com/THERAAB/nix-dotfiles/commit/0c4fb2b4fe61e7abcccfedc0ef79f647c5da1d85

**Comment by Atemu** [comment] 2023-05-14 15:14
I bisected it, it's https://github.com/NixOS/nixpkgs/pull/228870.

cc @K900

**Comment by K900** [comment] 2023-05-14 15:16
mangohud uses its own internal copy of vulkan-headers: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/graphics/mangohud/default.nix#L64

So it's probably the loader? If it is though, it might be tricky to bisect...

**Comment by Atemu** [comment] 2023-05-14 15:43
So, what are we going to do? Especially w.r.t. 23.05 being around the door. I don't think we should ship a broken mangohud in 23.05.

Honestly, I think https://github.com/NixOS/nixpkgs/pull/228870 should have probably not made it to master before branch-off. (Eventhough it was technically merged a few dasy before breaking changes were restricted.)

**Comment by K900** [comment] 2023-05-14 15:44
I'll try to reproduce locally and see if I can bisect vulkan-loader.

**Comment by Atemu** [comment] 2023-05-14 15:44
cc @PedroHLC because of https://github.com/PedroHLC/nixpkgs/commits/vulkan-versioned

**Comment by Atemu** [comment] 2023-05-14 15:47
We could also try updating the headers externally; Mangohud's are really quite old. They use this weird meson wrap thingy rather than letting the distro provide it and it too is very out of date.

Also, this is the error we're getting:

```
INFO | LAYER:     Requested layer "VK_LAYER_MANGOHUD_overlay" was wrong bit-type.
```

**Comment by K900** [comment] 2023-05-14 15:48
It breaks when built with newer headers.

**Comment by kira-bruneau** [comment] 2023-05-14 15:50
Oh sorry, forgot to get back to this! Maybe we need to switch back to using the system headers?

**Comment by K900** [comment] 2023-05-14 15:51
I'm actually pretty sure it's https://github.com/KhronosGroup/Vulkan-Loader/commit/c3eb97de22e9e2eec061be897dcf13f2c0759788 which we probably don't want to revert, but we may need to look into layer ordering?

**Comment by kira-bruneau** [comment] 2023-05-14 15:55
oh no 😞 - yeah i think you're right, i think the duplicate behaviour was added specifically to support multi-arch layers.

**Comment by Atemu** [comment] 2023-05-14 15:55
If it's just an issue of duplicate layers, perhaps we could add _32 and _64 suffixes to the layer names. obs-vkcapture does that too.

**Comment by PedroHLC** [comment] 2023-05-14 15:56
> cc @PedroHLC because of https://github.com/PedroHLC/nixpkgs/commits/vulkan-versioned

I gave up o pursuing this, as seen in https://github.com/NixOS/nixpkgs/pull/229897#issuecomment-1546698008

It works, but for this case here, it's probably better to bump MangoHud to the first commit guaranteed to work with new headers+loader. Cc @flightlessmango

**Comment by Atemu** [comment] 2023-05-14 15:57
Having 64-bit-only mangohud in the implicit layer dir works!

Going to try giving the 32-bit layer a different name now.

**Comment by kira-bruneau** [comment] 2023-05-14 16:02
This is also going to affect vkbasalt too then - I haven't tried yet though - I'll take a look at fixing that too!

**Comment by K900** [comment] 2023-05-14 16:05
> > cc @PedroHLC because of https://github.com/PedroHLC/nixpkgs/commits/vulkan-versioned
> 
> I gave up o pursuing this, as seen in [#229897 (comment)](https://github.com/NixOS/nixpkgs/pull/229897#issuecomment-1546698008)
> 
> It works, but for this case here, it's probably better to bring attention upstream. Cc @flightlessmango

Speaking of, any reason you gave up on that? I personally really liked the good idea.

**Comment by Atemu** [comment] 2023-05-14 16:10
Different suffixes work! PR incoming.

**Comment by PedroHLC** [comment] 2023-05-14 16:17
> Speaking of, any reason you gave up on that? I personally really liked the good idea.

It needed a proper rebase+bump to v1.3.250, and I couldn't figure out how to really take a good benefit from it.

**Comment by K900** [comment] 2023-05-14 16:18
Hm, I'll definitely try to pick it up after branch-off then.

**Comment by PedroHLC** [comment] 2023-05-14 16:29
Peculiarly, obs-vkcapture seem to do this for some time already:
```
VK_LAYER_OBS_vkcapture_32 (OBS Linux game capture) Vulkan version 1.3.249, layer version 1:
VK_LAYER_OBS_vkcapture_64 (OBS Linux game capture) Vulkan version 1.3.249, layer version 1:
```

@Scrumplex MANGOAPP from gamesope might need this fix too.

**Closed** 2023-05-15 11:42 UTC
Labels: 0.kind: bug
