### ISSUE TITLE
Package request: gitbulter

### ISSUE THREAD

**Issue by yswtrue** [NixOS/nixpkgs#298179] opened 2024-03-22 21:50 UTC
**Project description**

**Metadata**

* homepage URL: https://gitbutler.com/
* source URL: https://github.com/gitbutlerapp/gitbutler
* license: FSL-1.1-MIT
* platforms: linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by iynaix** [comment] 2024-03-23 08:33
There's an open PR #289664

**Comment by eclairevoyant** [comment] 2024-03-24 23:05
duplicate of #288567

**Closed by eclairevoyant** 2024-03-24 23:05 UTC
Labels: 0.kind: packaging request
