### ISSUE TITLE
sway: gsettings executed from sway/config fails

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#67704] opened 2019-08-29 15:46 UTC
If one tries to use the Sway wiki's suggested fix for GTK3 app graphical configuration, they will find themselves failing in NixOS. I think I've tracked down why.

Background:
1. GTK3 doesn't respect ~/.config/gtk-3.0/settings.ini, for certain settings, under Wayland.
2. Sway recommends a script that calls `gsettings set` with values from `settings.init` to ensure the values in the dconf backend reflect the same values in the text file:
   * https://github.com/swaywm/sway/wiki/GTK-3-settings-on-Wayland

Executing the script manually, from a terminal under Sway, works as expected. When run from a command in `~/.config/sway/config` as `exec_always`, it fails. I think this is because XDG_DATA_DIRS does not include the schema directories when Sway runs the command.

This is XDG_DATA_DIRS from a terminal under Sway:
```
/nix/store/7kdr875bhq5sgnh7x7xkkbbdq0a3qixv-termite-15/share:/nix/store/9v6jxyn1v2ncj4dnw317ibivzp8lkvzv-gtk+3-3.24.10/share/gsettings-schemas/gtk+3-3.24.10:/nix/store/7066ihqk8zlcd77ccb50m445v6dsxkz7-gsettings-desktop-schemas-3.32.0/share/gsettings-schemas/gsettings-desktop-schemas-3.32.0:/nix/store/9v6jxyn1v2ncj4dnw317ibivzp8lkvzv-gtk+3-3.24.10/share/gsettings-schemas/gtk+3-3.24.10:/nix/store/7066ihqk8zlcd77ccb50m445v6dsxkz7-gsettings-desktop-schemas-3.32.0/share/gsettings-schemas/gsettings-desktop-schemas-3.32.0:/home/cole/.nix-profile/share:/etc/profiles/per-user/cole/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share
```

But this is it when Sway executes it:
```
/home/cole/.nix-profile/share:/etc/profiles/per-user/cole/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share
```

Additionally, if I try to do this from inside the script, it prints "no schemas installed" when run by sway:
```
echo "$(GSETTINGS_BACKEND=dconf gsettings get org.gnome.desktop.interface cursor-theme 2>&1)" >> ~/log
```

Upstream issue: https://github.com/swaywm/sway/issues/4323 (sorta, the issue describe by OP seems somewhat different)

cc: @gnidorah @primeos

**Comment by primeos** [comment] 2019-08-29 20:06
> I think this is because XDG_DATA_DIRS does not include the schema directories when Sway runs the command.

Seems reasonable.

`$XDG_DATA_DIRS` differs in the terminal because `termite` uses `wrapGAppsHook` which adds a wrapper that looks like this:
```
#! /nix/store/xfghy8ixrhz3kyy6p724iv3cxji088dx-bash-4.4-p23/bin/bash -e
export GIO_EXTRA_MODULES='/nix/store/1i2824pmaclhcbddbk7r2yc7ni645x22-dconf-0.32.0-lib/lib/gio/modules'${GIO_EXTRA_MODULES:+':'}$GIO_EXTRA_MODULES
export GIO_EXTRA_MODULES='/nix/store/1i2824pmaclhcbddbk7r2yc7ni645x22-dconf-0.32.0-lib/lib/gio/modules'${GIO_EXTRA_MODULES:+':'}$GIO_EXTRA_MODULES
export GDK_PIXBUF_MODULE_FILE='/nix/store/9asda59pz0hg8bznxa64nx7n45v1szdz-librsvg-2.44.14/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache'
export XDG_DATA_DIRS='/nix/store/inlknqkinymvskvigpj345mfyfdvichx-gtk+3-3.24.10/share/gsettings-schemas/gtk+3-3.24.10:/nix/store/r3g9yn2cw6239szfq65q2cxw4cg35a81-gsettings-desktop-schemas-3.32.0/share/gsettings-schemas/gsettings-desktop-schemas-3.32.0:/nix/store/inlknqkinymvskvigpj345mfyfdvichx-gtk+3-3.24.10/share/gsettings-schemas/gtk+3-3.24.10:/nix/store/r3g9yn2cw6239szfq65q2cxw4cg35a81-gsettings-desktop-schemas-3.32.0/share/gsettings-schemas/gsettings-desktop-schemas-3.32.0'${XDG_DATA_DIRS:+':'}$XDG_DATA_DIRS
export XDG_DATA_DIRS='/nix/store/cp5g9b8rdq48zkqjlbnc47g3kq7l54bz-termite-15/share'${XDG_DATA_DIRS:+':'}$XDG_DATA_DIRS
exec -a "$0" "/nix/store/cp5g9b8rdq48zkqjlbnc47g3kq7l54bz-termite-15/bin/.termite-wrapped"  "${extraFlagsArray[@]}" "$@"
```

If you use another terminal emulator you should see the unmodified `$XDG_DATA_DIRS` like Sway sees it.

We could fix this problem by doing something similar for Sway. However, I'm a bit concerned about the closure size as this affects all users, even if they're not using GTK3 applications. But since most users should have the dependencies already installed and Nix isn't very minimalistic anyway we can probably get away with it. But it might still be best to make this configurable and use conservative defaults. It might be best to split Sway into `sway` and `sway-unwrapped` (but I am open for other ideas, I didn't spend much though on it yet).

**Comment by FlorianFranzen** [comment] 2019-09-05 01:25
I made the missing gsettings schemas available from sway by computing the path like this:
```
schema = pkgs.gsettings-desktop-schemas;
datadir = "${schema}/share/gsettings-schemas/${schema.name}";
```

And then exporting it to sway's environment by adding the following to sway's ```extraSessionCommands```:
```
XDG_DATA_DIRS=${datadir}:$XDG_DATA_DIRS
```
Now the ```org.gnome.desktop.interface``` schema can be accessed from sway.

**Comment by worldofpeace** [comment] 2019-12-09 03:29
cc @jtojnar 

This has my :eyes: because it seems like a simple issue.
Ref https://nixos.org/nixpkgs/manual/#sec-language-gnome, to anyone who hasn't read the newly added docs.

**Comment by jtojnar** [comment] 2019-12-09 17:26
The diagnosis is correct.

We solve the issue in GNOME Photos test by wrapping GSettings tool:

https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/installed-tests/gnome-photos.nix#L11-L25

The proper solution is https://github.com/NixOS/nixpkgs/pull/71079 using 
https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/installed-tests/gnome-photos.nix#L11-L25

**Comment by Elyhaka** [comment] 2019-12-27 14:02
@colemickens Is your issue fixed by #75247 ?

**Comment by eoli3n** [comment] 2020-01-07 19:58
same here, i don't understand how to test the fix ? any light please ?

**Comment by ymarkus** [comment] 2020-05-05 10:18
For me, this issue is still open. Here is my sway configuration:
```
sway = {
  enable = true;
  extraPackages = with pkgs; [ some_packages ];
  wrapperFeatures.gtk = true;
  extraSessionCommands = "export MOZ_ENABLE_WAYLAND=1";
};
```

Is it a config issue on my side?

**Comment by Elyhaka** [comment] 2020-05-05 12:05
There might be a regression with the GTK wrapper for sway, @primeos what do you think of this ?

**Comment by primeos** [comment] 2020-05-05 12:34
> There might be a regression with the GTK wrapper for sway, @primeos what do you think of this?

Don't know. I'm not using the GTK wrapper so far, but from this issue it looks like the GTK wrapper never fixed this problem.

From this thread it looks like we could e.g. solve this issue by adding `gsettings-desktop-schemas` to the build inputs of Sway's `wrapper.nix` (if `withGtkWrapper = true`). But I'm not sure what the best/preferred way to solve this is. Might e.g. be worth it to have a quick look at the X11 and GNOME modules and/or cc the team (or maybe the links from https://github.com/NixOS/nixpkgs/issues/67704#issuecomment-563344512 are already clear enough, I didn't have a closer look). A PR would be nice :) Thanks and good luck ;)

**Comment by Elyhaka** [comment] 2020-05-05 13:46
After some digging, it seems that `wrapGAppsHook` is not applying a "full" context (as opposed to `termite` for instance) to sway.

_generated wrapper for Sway_:

```bash
export GIO_EXTRA_MODULES='/nix/store/4fq6w7ksq1dba80sxpdgzrxpd46kdjgq-dconf-0.36.0-lib/lib/gio/modules'${GIO_EXTRA_MODULES:+':'}$GIO_EXTRA_MODULES
```

_generate wrapper for Termite_:

```bash
export GIO_EXTRA_MODULES='/nix/store/4fq6w7ksq1dba80sxpdgzrxpd46kdjgq-dconf-0.36.0-lib/lib/gio/modules'${GIO_EXTRA_MODULES:+':'}$GIO_EXTRA_MODULES
export GIO_EXTRA_MODULES='/nix/store/4fq6w7ksq1dba80sxpdgzrxpd46kdjgq-dconf-0.36.0-lib/lib/gio/modules'${GIO_EXTRA_MODULES:+':'}$GIO_EXTRA_MODULES
export GDK_PIXBUF_MODULE_FILE='/nix/store/d0r5r3zcjipx1qxqxmf1mqzwbay04vq3-librsvg-2.48.2/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache'
export XDG_DATA_DIRS='/nix/store/6yrlycwcnxlgg6bkhq4jvwmahyrj00id-gtk+3-3.24.17/share/gsettings-schemas/gtk+3-3.24.17:/nix/store/78x2nyfhhili5ijd6l74z3flj63p92s0-gsettings-desktop-schemas-3.36.0/share/gsettings-schemas/gsettings-desktop-schemas-3.36.0'${XDG_DATA_DIRS:+':'}$XDG_DATA_DIRS
export XDG_DATA_DIRS='/nix/store/7m99r1fx36zndgxrilg6kppg8k0d6pjb-termite-15/share'${XDG_DATA_DIRS:+':'}$XDG_DATA_DIRS
```

Adding `gsettings-desktop-schemas` to `buildInputs` has not effect.

I'm still trying to figure out what's the difference between `termite` and sway's wrapper.

**Comment by Elyhaka** [comment] 2020-05-05 15:56
I could not manage to make `wrapGAppsHook` add the missing prefixes to the wrapper. If I add the prefixes manually (like the example from the documentation linked by worldofpeace) it works, but I cannot manage to make `wrapGAppsHook` add them automatically.

If somebody that has more knowledge than me on this subject can help, that would be great :).

**Closed** 2020-05-08 09:45 UTC
Labels: 0.kind: bug
