### ISSUE TITLE
Build failure: rocm-llvm-compiler-rt-6.0.2

### ISSUE THREAD

**Issue by DariusChit** [NixOS/nixpkgs#326799] opened 2024-07-13 11:57 UTC
### Steps To Reproduce

1. build *rocm-llvm-compiler-rt-6.0.2*

### Build log

https://gist.github.com/DariusChit/295e5f383b266232aecaad0bf864e9d6

### Additional context

Build fails when building ollama and opengl libs on amd igpu and dgpu.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.8, NixOS, 24.11 (Vicuna), 24.11.20240709.feb2849`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/xr9wjzx0cdnwkmhzz74h8lphgn5jmyv3-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-07-13 14:08
dupe of #325907

**Closed** 2024-07-13 14:07 UTC
Labels: 0.kind: build failure
