### ISSUE TITLE
Popcorn Time is missing runtime dependencies

### ISSUE THREAD

**Issue by rnhmjoj** [NixOS/nixpkgs#15120] opened 2016-04-30 19:20 UTC
## Issue description

After the latest unstable channel update popcorntime doesn't run anymore: there are missing runtime dependencies. I tried adding every missing dynamic library (from the output of ldd) using patchelf but still the binary won't run. It produces the following output:
```
[10138:0430/193928:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[18135:0430/211734:FATAL:udev_loader.cc(36)] Check failed: false. 
[1]    18135 abort      ./result/bin/popcorntime
ATTENTION: default value of option force_s3tc_enable overridden by environment.                                    
[18153:0430/211734:WARNING:file_descriptor_set_posix.cc(30)] FileDescriptorSet destroyed with unconsumed descriptors: 0/1

```
I tried linking `libudev` and also creating a symlink of the `libudev.so` but still persist.
@bobvanderlinden can you give me a hand here?

**Comment by bobvanderlinden** [comment] 2016-05-01 08:09
The FATAL error has occurred before: https://github.com/NixOS/nixpkgs/issues/8800#issuecomment-121357792

I can't reproduce that error here anymore and cannot rebuild popcorntime because the sources have moved. The package needs to upgrade to the community edition. I'll try to upgrade the package to 0.4.0-2 and nwjs 0.14.

**Comment by bobvanderlinden** [comment] 2016-05-01 13:09
I've got the old version to run with the changes from #15133.

The PR doesn't exactly fix a problem related to udev, but it does allow building/running popcorntime on nixpkgs/master. I'm not entirely sure that'll solve the problem for you, but it is running now here with the udev fix that was applied earlier.

0.4.0-2 also works (https://github.com/bobvanderlinden/nixpkgs/tree/popcorntime-0.4.0-2), but I'll wait with a PR until the nwjs changes are merged.

**Comment by rnhmjoj** [comment] 2016-05-01 18:39
Thank you! It runs fine for me too with your changes.

**Comment by bobvanderlinden** [comment] 2016-05-02 09:28
#15154 is merged with popcorntime 0.4.0-2. Could you give nixpkgs/master a try too? That should be enough to close this issue.

**Comment by rnhmjoj** [comment] 2016-05-02 17:06
It works just fine. It's a different fork though: I'm not sure what's the legit one anymore: they accuse each other of being a scam.

**Comment by bobvanderlinden** [comment] 2016-05-02 18:13
Ugh, I thought one of them was basically dead as the site was down at the time. I guess it isn't. Not sure which one to pick anymore. Suggestions? Should they both be packaged? :-/ (PopcornTime Official, PopcornTime CE, maybe Butter too)

**Comment by rnhmjoj** [comment] 2016-05-02 20:24
I have found some information [here](https://www.reddit.com/r/PopCornTime/comments/3q5cow/the_history_of_popcorn_time_and_the_future) but I honestly don't know: popcorntime.sh development is more or less active but there hasn't been a release in while.

On the other hand popcorntime.ag is lying: they (whoever they are) [say](http://popcorntime.ag/official-statement.html#Malware2) the windows installer of the original version contains a malware and provide this [scan](https://www.virustotal.com/en/file/8865340cf24731a28a8f2916e049dbbaff8424315817b39e0ddffafdb8f38318/analysis/) as a proof. I checked myself with the same service they used and have found [nothing](https://www.virustotal.com/en/file/a7ab4761c353244f1fcabcb1ffc227e2fc29fa94b4d3d0ac5688b0db77b24f6d/analysis/) and [nothing](https://www.virustotal.com/en/url/bb15c6ab9e44c84c785569052d0e3e031f6d16160531e867857aae92b6773816/analysis/). The hash in the analysis they present doesn't match so I can only think they submitted another file.
They also accuse project butter of being a money laundering scheme. Money laundering with an open source project is, by itself, ridiculous even more they only provide this bitcoin address `1Neb2kGPSgay4ETGcqFdXA7xjV8eqgjMJZ` that has received a mere 0.00025 BTC.

They are probably just marketing their own fork but I don't really like this kind of behavior. That said,
popcorntime.ag application seem to use a different api and it didn't import the database of the original application (maybe it's just using a different path) so I'd rather a fork with retro-compatibility.

**Comment by rnhmjoj** [comment] 2016-05-02 20:32
What are other package manager doing? Considering all the controversy and that we are packaging a binary (I mean we could expose users to possible malwares) I also think removing popcorntime from nixpkgs may be an option.

**Comment by joachifm** [comment] 2016-05-02 20:35
@rnhmjoj if that's even a remote possibility, it needs to be removed posthaste, IMO.

**Comment by rnhmjoj** [comment] 2016-05-02 20:50
Yes, I agree. If no one else understanding all of this different forks situation it's better to leave it off nixpkgs.

**Comment by matthewbauer** [comment] 2016-05-03 04:52
Last I checked popcorntime.io was the only legit open source one. I think there was a threatened lawsuit so they closed the website and the git repos. So any of the other forks are pretty much just biding their time until they get popular enough to be threatened with another lawsuit. It might make sense to include "butter" because it supposedly takes all of the questionable parts of popcorntime out.

**Comment by joachifm** [comment] 2016-05-03 14:10
I've marked it as broken for now, next step is removal.

**Comment by bobvanderlinden** [comment] 2016-05-03 21:00
It isn't really broken though. It builds, it runs, etc. It's just a matter of choosing the right fork of PopcornTime. There are 3 of them, I recently switched to PopcornTime CE, as it seemed more up to date at the time. Both PopcornTime CE and PopcornTime Official now both seem questionable forks.

Butter indeed seems like the right way to go, but it doesn't have any stable releases yet.

Until Butter doesn't have a stable release, removing the PopcornTime package is probably the right thing to do, even though it'll be inconvenient and will probably confuse existing users.

**Comment by bobvanderlinden** [comment] 2016-05-05 19:34
Alright, #15245 was merged, which means Popcorntime was removed :cry::tada: Let me know when Butter gets a stable release and I'll happily attempt to create a package for it.

I'm guessing this issue can be closed.

**Closed** 2016-05-05 19:42 UTC

**Comment by copumpkin** [comment] 2016-05-05 23:52
Instead of removing it, perhaps replace the expression with a `throw "Removed from nixpkgs. See https://github.com/NixOS/nixpkgs/issues/15120"`?

**Comment by bobvanderlinden** [comment] 2016-05-06 20:33
@copumpkin Are there any other packages that already do something like this?

**Comment by copumpkin** [comment] 2016-05-10 13:33
@bobvanderlinden #15357 might give us one

**Comment by bobvanderlinden** [comment] 2016-05-10 13:42
@copumpkin Thanks, that seems exactly what we needed.

**Comment by onny** [comment] 2021-06-21 14:06
> It isn't really broken though. It builds, it runs, etc. It's just a matter of choosing the right fork of PopcornTime. There are 3 of them, I recently switched to PopcornTime CE, as it seemed more up to date at the time. Both PopcornTime CE and PopcornTime Official now both seem questionable forks.
> 
> Butter indeed seems like the right way to go, but it doesn't have any stable releases yet.
> 
> Until Butter doesn't have a stable release, removing the PopcornTime package is probably the right thing to do, even though it'll be inconvenient and will probably confuse existing users.

There is a new stable release from PopcornTime "Official" but don't know if it is working and legit https://github.com/popcorn-official/popcorn-desktop/releases/tag/v0.4.5
