### ISSUE TITLE
Update to chromium causes yellow boxes in the UI

### ISSUE THREAD

**Issue by dvc94ch** [NixOS/nixpkgs#17958] opened 2016-08-24 12:32 UTC
## Issue description

![screenshot from 2016-08-24 14-31-04](https://cloud.githubusercontent.com/assets/741807/17930604/6fb3513c-6a07-11e6-8ff0-826825a7bc8a.png)
### Steps to reproduce

nix-env -i chromium

Version 52.0.2743.116 (64-bit)
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
- Nix version: (run `nix-env --version`)
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by abbradar** [comment] 2016-08-25 16:43
Confirmed on Intel video, current master (4dc1823).

**Comment by Baughn** [comment] 2016-08-29 19:50
Confirmed on nVidia, with GL both enabled and disabled. I'm pretty sure it's Chromium.

**Comment by FRidh** [comment] 2016-08-30 12:23
@grahamc had this before https://github.com/NixOS/nixpkgs/pull/12895#issuecomment-239651803 cc

**Comment by gebner** [comment] 2016-08-30 13:33
I don't see this on master (amdgpu with LLVM 3.9).

**Comment by globin** [comment] 2016-08-31 12:19
Do all of you who have the failure use Gnome?

**Comment by grahamc** [comment] 2016-08-31 12:23
I use i3, not gnome

**Comment by abbradar** [comment] 2016-08-31 12:23
Nope, I use xmonad and xfce for session and settings.

**Comment by globin** [comment] 2016-08-31 12:26
I definitely cannot reproduce this in i3 and had unsuccessfully tried to reproduce this in a vbox VM with gnome. (intel and nvidia cards)

**Comment by Baughn** [comment] 2016-08-31 13:12
Also happens in KDE.

**Comment by dfoxfranke** [comment] 2016-09-02 18:56
Confirmed under XMonad and AMD with either amdgpu or ati_unfree driver.

**Comment by grahamc** [comment] 2016-09-30 22:42
(Set to 16.09, since the issue persists in the 16.09 release branch still)

**Comment by grahamc** [comment] 2016-10-01 11:53
@globin are you testing on a hidpi box by chance?

**Comment by abbradar** [comment] 2016-10-01 12:33
For whatever reason I can't reproduce this anymore. I'm on adfcc2d9531e78bf6a9e3b56e2f4fc873cb3d87b

**Comment by abbradar** [comment] 2016-10-01 12:39
Interesting enough, I can't also reproduce this on a commit that had this problem for me earlier (https://github.com/NixOS/nixpkgs/commit/4dc1823e730a61d85961c17b6eda7f6d63c88ca5) when I just run Chromium from it. I suppose that something in NixOS has changed but I'm not sure.

**Comment by mkawalec** [comment] 2016-10-21 07:54
I can repro this as well, on a freshly installed system

**Comment by DamienCassou** [comment] 2016-10-25 18:38
I confirm the problem.

**Comment by ambrop72** [comment] 2016-11-09 17:16
I'm seeing this (NixOS 16.09, NVidia driver, and AMD open source driver).

**Comment by ambrop72** [comment] 2016-11-09 18:09
I've asked in #chromium-support about this and got a hint that it must be due to missing 2x-resolution icons. This makes sense because reducing my DPI (Xfce settings) fixes lots of the icons. But not all, for example the Chromium icon for the settings pane is still yellow.

**Comment by ambrop72** [comment] 2016-11-09 18:29
I see the output (libexec) is missing the file chrome_200_percent.pak, which is present in google-chrome. Looking at the source ui/resources/BUILD.gn, seems like the build system simply does not generate this file.

**Comment by ambrop72** [comment] 2016-11-10 16:23
Please review my pull request https://github.com/NixOS/nixpkgs/pull/20293 which is a fix for this issue. Note, it is against release-16.09. And I only tested with one version of Chromium, is might need adaptations to work with other versions.

**Comment by fpletz** [comment] 2017-01-20 16:50
Fixed. See #20293.

**Closed by fpletz** 2017-01-20 16:50 UTC
Labels: 0.kind: bug
