### ISSUE TITLE
Nixos android sdk license

### ISSUE THREAD

**Issue by husnoo** [NixOS/nixpkgs#23910] opened 2017-03-15 08:25 UTC
## Issue description

Hi,

How do I accept the sdk license on nixos? Thanks!

### Steps to reproduce
```
$ ANDROID_HOME=~/.nix-profile/libexec/ LD_LIBRARY_PATH=/nix/store/23cqmxnpr8
pdg1ivirb399g6ahh3dwlg-ncurses-5.9/lib/ gradle build
...
You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 25].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by aepsil0n** [comment] 2017-06-08 12:44
Running into the same problem trying to build a react-native project on NixOS. In an imperative world, we could just run this:

```
yes | $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-25"
```

However, this fails because `/nix/store` is not writable

I have read elsewhere, that the ANDROID_HOME should be set to a directory in $HOME to allow the SDK to manage its software on its own, but I'm not sure how to work with that setup exactly.

**Comment by uniphil** [comment] 2017-06-12 00:36
This is not a solution, but I hacked my way though a setup that at least lets me get work done in react-native for now, and maybe it will unblock someone else until the right way to do this is shared/documented/fixed:

https://github.com/uniphil/nix-for-devs/blob/bf3612f8635d05426161eae49ec478bb07df8730/README.md#react-native

**Comment by volth** [comment] 2017-08-17 13:29
I see many Travis-CI scripts just do
```
mkdir -p "$ANDROID_SDK/licenses"
echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_SDK/licenses/android-sdk-license"
echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_SDK/licenses/android-sdk-preview-license"
```

**Comment by Abdillah** [comment] 2019-12-18 22:52
Does it possible to run `echo yes | $PATH/bin/sdkmanager --update`? As if the user run the sdk after install. Since user able to install the SDK, it must have accept the license through the expression.

**Comment by Rizary** [comment] 2020-01-24 14:10
I'm using `nixos-20.03pre-git` and my `$HOME/.config/nixpkgs/config.nix` already contained:

```
{ android_sdk.accept_license = true;
}
```

But when I run `nix-shell` inside my android project, I still get an error:

```
You must accept the Android Software Development Kit License Agreement at
https://developer.android.com/studio/terms
by setting nixpkgs config option 'android_sdk.accept_license = true;'
```

I try to use @uniphil hack, but still I got the android sdk license issue.

**Comment by Valodim** [comment] 2020-05-25 19:59
So what I gather from the issues and doing some testing is that the nixos packaged android sdks cannot actually be used for building android apps, because of those missing license files. Is that right? Am I missing something here?

It *seems* like that explanation makes no sense. But there are several people scrambling to figure this out with various workarounds, and I haven't seen anyone say "no, it's working as intended, here's how you do it."

Could someone please shed some light on this? @svanderburg?

**Comment by Limvot** [comment] 2020-05-25 21:23
@Valodim - I'm not sure exactly how it is supposed to work, but for some reason the licenses are successfully accepted for me if I do `config.android_sdk.accept_license = true;` and use `androidenv.buildApp`. Now it doesn't work if I merely depend on the sdk, I actually have to use the androidenv.buildApp. I don't use ant to build my app, so I can't actually build my app this way, but by making the androidenv.buildApp package and then invoking nix-shell, I end up in a shell where the licenses are accepted and the tools work.

In order to get some of the newer platform version 29 / JetPack stuff to work with the new aapt2, I've additionally had to build a FHSUserEnv so the new aapt2 downloaded through google's maven can run unpatched. This might be a bit of overkill for you (and I'm sure this could be made way better) but here's the default.nix that I'm using to build my current app (and note that I just use with nix-shell and call gradlew manually

https://github.com/Limvot/slate/blob/ebc51922db33ee79c5848fb56ecbebd0ac76400e/default.nix

**Comment by Valodim** [comment] 2020-05-25 21:30
@Limvot are you sure the SDK that's used for you is the packaged one? I was fooled there for a while, because I had a local.properties that pointed to a (writable) path in my home directory and between gradlew and android studio stuff worked - but not actually using the nix-provided SDKs.

**Comment by Limvot** [comment] 2020-05-25 21:39
@Valodim Yep, I'm pretty positive. I've developed with on NixOS with android studio in the past, but I've uninstalled it and deleted all of the various android directories out of my home folder, and my default.nix works great. It prints out some warnings as it builds showing that the SDK's path is in the nix store as well.

**Comment by Valodim** [comment] 2020-05-25 22:16
interesting to know, I'll give that a shot. but man, information about this all over the place :( I imagine the 98% thing to be done for android developers that look at the android sdk packaging is "I have a gradlew, how do I build stuff". I've been looking at this stuff for days and couldn't find an answer that didn't feel like a huge hack.

@Limvot Here's a trick to make gradle use the sdk-provided aapt2, might get around the fhs that way:

```
  # override the aapt2 that gradle uses with the nix-shipped version
  GRADLE_OPTS = "-Dorg.gradle.project.android.aapt2FromMavenOverride=${androidSdk}/libexec/android-sdk/build-tools/28.0.3/aapt2";
```

**Comment by tgunnoe** [comment] 2020-05-26 20:48
> @Valodim - I'm not sure exactly how it is supposed to work, but for some reason the licenses are successfully accepted for me if I do `config.android_sdk.accept_license = true;` and use `androidenv.buildApp`. Now it doesn't work if I merely depend on the sdk, I actually have to use the androidenv.buildApp. I don't use ant to build my app, so I can't actually build my app this way, but by making the androidenv.buildApp package and then invoking nix-shell, I end up in a shell where the licenses are accepted and the tools work.
> 
> In order to get some of the newer platform version 29 / JetPack stuff to work with the new aapt2, I've additionally had to build a FHSUserEnv so the new aapt2 downloaded through google's maven can run unpatched. This might be a bit of overkill for you (and I'm sure this could be made way better) but here's the default.nix that I'm using to build my current app (and note that I just use with nix-shell and call gradlew manually)
> 
> https://github.com/Limvot/slate/blob/ebc51922db33ee79c5848fb56ecbebd0ac76400e/default.nix

@Limvot thank you for this description. the first part about the `android_sdk.accept_license = true;` only being valid if you build your app with the SDK `androidenv.buildApp` is particularly telling to [why I wasnt able to get it working with flutter](https://github.com/NixOS/nixpkgs/pull/76420#issuecomment-615344955).

**Comment by numinit** [comment] 2020-06-08 03:27
The changes in #89775 might be relevant here.

**Comment by rawkode** [comment] 2020-07-16 21:55
Has anyone got this working yet? I'm completely stuck :-1:

**Comment by Abdillah** [comment] 2020-07-23 03:39
I think I'm halfway through setup an sdk with license accepted. The missing part would be the content of `licenses/` directory (I've copied @volth's comment and didn't work). But, you can copy the license fromanother machine.

```
{ pkgs ? import <nixpkgs> { 
  config.android_sdk.accept_license = true;
  overlays = [
    (self: super: rec {
      androidPkgs_5_0 = (super.androidenv.composeAndroidPackages {
        platformVersions = [ "21" ];
        abiVersions = [ "x86" "x86_64"];
      });
      androidsdk = androidPkgs_5_0.androidsdk.overrideAttrs (oldAttrs: {
        installPhase = oldAttrs.installPhase + ''
            mkdir -p "$out/licenses";
            echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$out/licenses/android-sdk-license";
            echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$out/licenses/android-sdk-preview-license";
        '';
      });
    })
  ];
} }:

(pkgs.buildFHSUserEnv {
  name = "android-sdk-env";
  targetPkgs = pkgs: (with pkgs;
    [
      jdk
      androidsdk
      glibc
    ]);
  runScript = "bash";
}).env
```

**Comment by GuillaumeDesforges** [comment] 2020-11-23 15:36
Thanks @numinit for #89775 !! Can't wait for it to land on master. :) Currently this is a blocker for me...

**Comment by numinit** [comment] 2020-12-05 21:02
@GuillaumeDesforges No problem. Accepting the EULA declaratively was not the most exciting thing to work on ever, but unblocked lots of Android developers...

**Comment by numinit** [comment] 2021-01-11 05:17
#89775 is merged now.

**Closed** 2021-02-09 09:03 UTC
Labels: 0.kind: question
