### ISSUE TITLE
Package request: Kenku FM

### ISSUE THREAD

**Issue by thomasheartman** [NixOS/nixpkgs#259984] opened 2023-10-09 12:41 UTC
## Project description

Kenku FM is an online tabletop audio sharing app for Discord.

From the readme:

Kenku FM is a desktop application for Windows, MacOS and Linux designed to be the easiest way to share music in a Discord voice call.

-    Use the Kenku Player interface to share your local music and sound effects to your discord calls.
-   Use the built in web browser to share audio from your favourite websites like YouTube and Spotify.
-    Trigger and control sounds with the Kenku FM plugin for the Elgato Stream Deck.
-    If you already have a virtual audio cable setup use Kenku FM as an easy way to connect to Discord with your existing software.

Personally I've been using it for sharing audio when playing D&D online.

## Metadata

* homepage URL: https://www.kenku.fm/
* source URL: https://github.com/owlbear-rodeo/kenku-fm/
* license: GNU General Public License v3.0
* platforms: Requesting packaging specifically for NixOS, but general unix or linux+darwin could be nice, I guess 💁🏼  Binaries are already available for: Windows, MacOS (intel + apple silicon), Debian (x64 and ARM), and Red Hat (x64 and ARM).

**Comment by eclairevoyant** [comment] 2023-10-09 13:46
duplicate of #259472

**Closed by eclairevoyant** 2023-10-09 13:46 UTC
Labels: 0.kind: packaging request

**Comment by thomasheartman** [comment] 2023-10-13 09:49
Thanks for closing it! I searched for this a while ago but couldn't find it, but it must've been before the other one was brought up. Apologies for the extra work. Thanks!
