### ISSUE TITLE
Build failure: nextcloud-client

### ISSUE THREAD

**Issue by cterence** [NixOS/nixpkgs#326635] opened 2024-07-12 19:20 UTC
### Steps To Reproduce

1. build *nextcloud-client*

### Build log

```
❯ sudo nixos-rebuild switch --flake ~/nixos
error: hash mismatch in fixed-output derivation '/nix/store/zg2zsi4nkgnhn92nj3qqmyd12kvban13-source.drv':
         specified: sha256-z4yxWClbs05ZCT8CPJpPY2BWMSXxfJ09Lq3Oottx7dQ=
            got:    sha256-hZjmAdh9QQ2bAIYL3K7scl59kz9Wxnv9f6rKMeuKb7U=
error: 1 dependencies of derivation '/nix/store/x0fg4xc7zr3gbsbaypqaq4xdc9gwyj33-nextcloud-client-3.13.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/sy9qpcrs58jzvl1ddxqn47p7ydg0hbz9-nextcloud-client.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/iqyf13fkk667f9w15clsx150byjzgmad-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/v53vlsaxi10zqm97c3jj7y3srmnxh66y-nixos-system-t14s-24.11.20240709.feb2849.drv' failed to build
```

### Additional context

On nixos-unstable branch, the problem was introduced between commits 9f4128e00b0ae8ec65918efeba59db998750ead6 and feb2849fdeb70028c70d73b848214b00d324a497.

### Notify maintainers

@Kranzes @SuperSandro2000 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.7, NixOS, 24.11 (Vicuna), 24.11.20240703.9f4128e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/dk2rpyb6ndvfbf19bkb2plcz5y3k8i5v-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-07-12 20:21
duplicate of #326258
fixed in #326093

**Closed by eclairevoyant** 2024-07-12 20:21 UTC
Labels: 0.kind: build failure
