### ISSUE TITLE
Add WezTerm

### ISSUE THREAD

**Issue by alexherbo2** [NixOS/nixpkgs#103392] opened 2020-11-11 03:50 UTC
- Name: WezTerm
- Description: A GPU-accelerated cross-platform terminal emulator and multiplexer written by @wez and implemented in Rust.
- Homepage: https://wezfurlong.org/wezterm/
- Repository: https://github.com/wez/wezterm
- License: MIT

**Comment by veprbl** [comment] 2020-11-11 15:37
Duplicate of #90696

**Closed** 2020-11-11 15:50 UTC
Labels: 0.kind: packaging request
