### ISSUE TITLE
DrKonqui unable to find gdb after Plasma 6.2 update

### ISSUE THREAD

**Issue by griffi-gh** [NixOS/nixpkgs#352333] opened 2024-10-30 09:45 UTC
### Describe the bug
Plasma bug reporter used to be able to find GDB before 6.2 update, but not anymore

### Steps To Reproduce
1. Update to plasma 6.2
2. Wait for something to crash
3. Crash reporter unable to find GDB

### Expected behavior
Assuming gdb's installed in `environment.systemPackages`, it should be able to find it.

### Screenshots
![image](https://github.com/user-attachments/assets/de556f7c-510b-4dfe-add6-040e945159a9)

### Additional context
N/A

### Metadata

---

 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.2-zen1, NixOS, 24.11 (Vicuna), 24.11.20241020.1997e4a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.25.0pre20240920_ca3fc169`
 - nixpkgs: `/nix/store/dyzl40h25l04565n90psbhzgnc5vp2xr-source`
 
Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SigmaSquadron** [comment] 2024-10-30 17:16
Please notify the maintainers next time.

@NixOS/qt-kde

**Comment by niknetniko** [comment] 2024-11-02 12:55
This seems like https://github.com/NixOS/nixpkgs/issues/352013, so the fix for that issue (https://github.com/NixOS/nixpkgs/pull/352034) is probably of interest to track.

**Comment by SigmaSquadron** [comment] 2024-11-02 15:51
This is a duplicate of #352013 then.

**Closed by SigmaSquadron** 2024-11-02 15:51 UTC
Labels: 0.kind: bug
