### ISSUE TITLE
Error in texlive-combined-2016

### ISSUE THREAD

**Issue by sid-kap** [NixOS/nixpkgs#25061] opened 2017-04-20 15:21 UTC
When I try to build `pkgs.texlive.combined.scheme-medium`, I get the following output:

```
nix-build
these derivations will be built:
  /nix/store/c52c73h9g3yqyhglvyafch6llzykzgc4-texlive-dvisvgm.bin-2016.drv
  /nix/store/pf8423inffania0nbzbl85x5ih9i8a84-texlive-dvipng.bin-2016.drv
  /nix/store/syly1fzgpas0lmbjrilkldcxnsb383p1-texlive-bibtex-x.bin-2016.drv
  /nix/store/4mdkzj7x413siq784bswzwx3j6w6pj2v-texlive-combined-2016.drv
  /nix/store/zxcwf0v8sssyq5g4pjkpmgssb98xnmkx-texlive-xindy.bin-2016.drv
  /nix/store/1k52a1ss0sli1vfazw3slav1si90k61n-texlive-combined-medium-2016.drv
building path(s) ‘/nix/store/9c2dd12b1n3v85va6f8qvzkz7ll5s24a-texlive-bibtex-x.bin-2016’
building path(s) ‘/nix/store/s8c6r2idiiq2m76ijkghxiqkp61442bv-texlive-dvipng.bin-2016’
building path(s) ‘/nix/store/k9f8syh1gkyf6r2h5p969xp9rb8yr7ly-texlive-dvisvgm.bin-2016’
building path(s) ‘/nix/store/wvh0wn30a54aa204xh0nspnxk3lv824a-texlive-combined-2016’
unpacking sources
unpacking source archive /nix/store/w0iflrjsl6ssqi4d4ml9jvnyyacwb62c-texlive-20160523b-source.tar.xz
unpacking sources
unpacking source archive /nix/store/w0iflrjsl6ssqi4d4ml9jvnyyacwb62c-texlive-20160523b-source.tar.xz
created 22 symlinks in user environment
unpacking sources
unpacking source archive /nix/store/w0iflrjsl6ssqi4d4ml9jvnyyacwb62c-texlive-20160523b-source.tar.xz
rm: cannot remove 'texlinks.sh': No such file or directory
Hmm...  Looks like a unified diff to me...
patching file texlinks.sh
Using Plan A...
Hunk #1 FAILED at 157.
patch: **** Can't reopen file texlinks.sh : No such file or directory
builder for ‘/nix/store/4mdkzj7x413siq784bswzwx3j6w6pj2v-texlive-combined-2016.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/zxcwf0v8sssyq5g4pjkpmgssb98xnmkx-texlive-xindy.bin-2016.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/1k52a1ss0sli1vfazw3slav1si90k61n-texlive-combined-medium-2016.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/1k52a1ss0sli1vfazw3slav1si90k61n-texlive-combined-medium-2016.drv’ failed
``` 

# steps to reproduce
Create a file called `default.nix` containing the following:
```
let 
  pkgs = import <nixpkgs> {};
in
  pkgs.texlive.combined.scheme-medium
```
and then run `nix-build`.

**Comment by jokogr** [comment] 2017-04-22 10:07
Here [1] I cannot reproduce this.

[1]:

```
# nixos-version
17.03.1024.2af7c40ed9 (Gorilla)
# nix-env --version
nix-env (Nix) 1.11.8
# nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.03.1024.2af7c40ed9"
```

**Comment by sid-kap** [comment] 2017-04-22 15:26
@jokogr Thanks for looking into this! I tried again and the test case I used earlier is actually fine. However, the following still fails for me:

```
let 
  pkgs = import <nixpkgs> {};
in
let 
  pkgs = import <nixpkgs> {};
in
  (pkgs.texlive.combine {
    inherit (pkgs.texlive)
    scheme-medium;
  })
```

**Comment by jokogr** [comment] 2017-04-22 19:50
This also works for me and everything is stored in `/nix/store/5cm162xlz2nqhjbx6s6s578g6i1vwv7b-texlive-combined-2016`. Are you overriding anything or using a different branch?

**Comment by lheckemann** [comment] 2017-04-23 22:44
`nix-build -E 'with import <nixpkgs> {}; texlive.combined.scheme-medium'` and `
nix-build -E 'with import <nixpkgs> {}; texlive.combine {inherit (texlive) scheme-medium;}'` both work for me.

- System: 17.03.981.a7ebf59aa7 (Gorilla)
- Nix version: nix-env (Nix) 1.11.8
- Nixpkgs version: "17.03.1033.99dfb6dce3"

**Comment by sid-kap** [comment] 2017-04-24 01:13
@jokogr I am not overriding anything or using a different branch. My nixos-version and nixpkgsVersion are the same as yours.

**Comment by sid-kap** [comment] 2017-04-25 14:32
@lheckemann Do you have any idea of what I could try to debug this? It seems like "texlinks.sh" is missing for some reason. Is there a way to list the files in the texlive directory that it downloads before building, to see if it is there?

**Comment by lheckemann** [comment] 2017-04-25 14:45
You could try
```
nix-build -E 'with import <nixpkgs> {}; texlive.combine {inherit (texlive) scheme-medium;}' --keep-failed
```
and peek into the build directory (in /tmp). Not sure how useful that would be though.

**Comment by sid-kap** [comment] 2017-04-25 15:13
I'm not sure what you mean? I'm just using the standard nixpkgs, I don't have any local overrides.

**Comment by sid-kap** [comment] 2017-09-18 14:29
So I'm trying to debug this, and so I cloned nixpkgs and added an `ls` before the `rm texlinks.sh` stuff in `combine.nix` (see https://github.com/NixOS/nixpkgs/blob/0529e4d90885b4e911162e8f8be077ae22322eba/pkgs/tools/typesetting/tex/texlive/combine.nix#L71). As expected, the file `texlinks.sh` doesn't exist in `$out/share/texmf/scripts/` (though other files, such as `rubibtex.sh`, `rumakeindex.sh` and `texconfig.sh` are there).

Does anyone know which package these scripts are fetched from? (Presumably, it's one of [scheme-medium's dependencies](https://github.com/NixOS/nixpkgs/blob/0529e4d90885b4e911162e8f8be077ae22322eba/pkgs/tools/typesetting/tex/texlive/pkgs.nix#L20512).)

**Comment by yegortimoshenko** [comment] 2017-09-20 16:25
@sid-kap `texlinks.sh` is in tetex package: https://www.ctan.org/pkg/tetex
Inherited by scheme-medium from collection-basic.

**Comment by xeji** [comment] 2018-05-09 15:43
Closing this as both NixOS 17.03 and texlive 2016 are obsolete now.

**Closed by xeji** 2018-05-09 15:43 UTC
