### ISSUE TITLE
gVim does not recognise dead keys (for accents and diacritics)

### ISSUE THREAD

**Issue by alexeymuranov** [NixOS/nixpkgs#23442] opened 2017-03-03 12:53 UTC
## Issue description

I have gVim 7.4.2367 on NixOS, and it does not recognise [dead keys](https://en.wikipedia.org/wiki/Dead_key), so i cannot use some accents in my usual keyboard layout (Canadian French multilingual).

I think my `gvim` comes from `nixos.vimHugeX`  (`vim_configurable-7.4.2367`). I did not install it either imperatively or declaratively (i did first, but then removed).  It must be a dependency of something, i suppose, maybe of GNOME 3.  (*Update*: no, it was not a dependency, see the [comments](https://github.com/NixOS/nixpkgs/issues/23442#issuecomment-283979624) below.)

Dead keys work in terminal version of my Vim, as well as in other applications.

I've found one reference to this issue [in \#nixos IRC log](https://botbot.me/freenode/nixos/2016-06-12/?msg=67733881) from June 2016.

### Steps to reproduce

Start `gvim` from terminal, select Canadian French Multilingual as the input source and hit twice the dead <kbd>^</kbd> (the same key as <kbd>[</kbd> in the US layout).  This should print a single `^`, but it prints nothing.  Alternatively, hit the dead <kbd>^</kbd> and then <kbd>a</kbd>.  This should print `â`, but it prints `a`.

## Technical details

* NixOS: `16.09.1803.40de598 (Flounder)`.
* Nix version: `1.11.6`.
* Nixpkgs version: `16.09.1803.40de598`.

**Comment by 7c6f434c** [comment] 2017-03-03 13:54
Did you try setting GTK_IM_MODULE=xim in your environment? I have dead
keys working fine in gVim, I have this variable set, and I vaguely 
remember that I set it specifically because of dead keys.

**Comment by alexeymuranov** [comment] 2017-03-03 14:15
@7c6f434c, thanks for sharing your experience, where exactly did you set it?  I have just tried
```shell
export GTK_IM_MODULE=xim
gvim -f
```
but it worked the same.

What is `GTK_IM_MODULE=xim` supposed to do? I didn't find much documentation on it right away, but i found a [report](http://unix.stackexchange.com/questions/265042/gtk-im-module-xim-breaks-dead-keys-in-gtk-and-qt-applications) that this option can actually break dead keys.

In any case, not working by default looks like a bug to me.

**Comment by 7c6f434c** [comment] 2017-03-03 14:32
Hm, strange. And now I created a fresh user and ran gvim in a fresh
empty X session, and dead keys work without the extra variable…

**Comment by alexeymuranov** [comment] 2017-03-03 15:13
This is weird: it turns out that the vim i was using in my user account was `vim_configurable` installed imperatively (`nix-env -i`) by the root.  So much for individual user profiles.

I removed it from root account (it became inaccessible in user account), reinstalled in user account, but nothing changed -- dead keys do not work.

Any ideas what to test to debug this?

**Comment by vcunat** [comment] 2017-03-03 15:21
Your `$PATH` doesn't have `/$HOME/.nix-profile/bin` before `/nix/var/nix/profiles/default/bin`?

**Comment by alexeymuranov** [comment] 2017-03-03 15:27
Here is a (split) output of `echo $PATH`:
```
/nix/store/98n4fjyq6pjavrxpizxnmxn1k6bv6jnz-unzip-6.0/bin:
/nix/store/7w1pp05fzjn6xi91m2vndfp2dg0yk7f0-glib-2.48.2-dev/bin:
/home/alexey/bin:
/var/setuid-wrappers:
/home/alexey/.nix-profile/bin:
/home/alexey/.nix-profile/sbin:
/home/alexey/.nix-profile/lib/kde4/libexec:
/nix/var/nix/profiles/default/bin:
/nix/var/nix/profiles/default/sbin:
/nix/var/nix/profiles/default/lib/kde4/libexec:
/run/current-system/sw/bin:
/run/current-system/sw/sbin:
/run/current-system/sw/lib/kde4/libexec
```

**Comment by vcunat** [comment] 2017-03-03 15:31
That seems correct order; no idea how the root-installed one could be run instead, except if your personal one is missing some aliases (e.g. the `gvim` symlink).

**Comment by alexeymuranov** [comment] 2017-03-03 15:39
I've just tried this again.  I reinstalled `nixos.vimHugeX` as both user and root, and removed it from user account:
```
§ nix-env -qaPs vim_configurable
-PS  nixos.vimHugeX  vim_configurable-7.4.2367
---  nixos.vimNox    vim_configurable-7.4.2367
```
However,  `gvim` starts just fine (except for the dead keys).  I bet that if i remove it from the root profile, it will not start any more.

**Comment by 7c6f434c** [comment] 2017-03-03 17:44
Could you also specify your keymap description in terms of Xorg.conf/setxkbmap?

**Comment by 7c6f434c** [comment] 2017-03-03 17:51
Hm! Maybe `GTK_IM_MODULE=xim` helps me because I use an even larger Vim than `vimHugeX`. https://github.com/7c6f434c/7c6f434c-configurations/blob/master/custom-vim.nix (note that I have `ximSupport=true` there). No idea how much this adds to the closure if we make it the default; maybe for Huge and X it would be only logical. Stock `vimHugeX` does have the problem you describe.

**Comment by alexeymuranov** [comment] 2017-03-03 18:03
I hope that since you reproduced this, i do not need to describe my Xorg keyboard settings (i am not such a specialist).  Just in case, here is my output of `setxkbmap -query` in GNOME session:
```
rules:      evdev
model:      pc104
layout:     ca,us,ru,us
variant:    multix,,,
options:    grp:alt_shift_toggle,grp_led:scroll
```

**Comment by vcunat** [comment] 2017-03-03 18:49
For me composing in gvim also doesn't work. (Some older 17.03 + modified colemak layout.)

**Comment by 7c6f434c** [comment] 2017-03-03 20:07
OK, `ximSupport` is the key for this issue, environment variables are not needed, and enabling the option increases closure size by 15KB. Pushed the fix, anyone wants to test?

**Comment by 7c6f434c** [comment] 2017-03-03 20:08
@alexeymuranov by the way, what you have listed is most likely the complete description of your keyboard settings, thanks.

**Comment by vcunat** [comment] 2017-03-03 20:34
Fixed for me.

**Closed by vcunat** 2017-03-03 20:34 UTC

**Comment by vcunat** [comment] 2017-03-03 20:36
I picked it to 17.03, too: 20512381c5,

**Comment by alexeymuranov** [comment] 2017-03-03 20:40
@7c6f434c, thanks!

**Comment by alexeymuranov** [comment] 2017-03-03 20:47
@vcunat, about the visibility of root's applications from user accounts, should i open another issue?  This isn't expected, is it?  I have just tested this on a different machine with NixOS, with `gvim` and another application.  Installing an application as root with `nix-env -i` makes it available to users.

**Comment by 7c6f434c** [comment] 2017-03-03 21:37
About root's applications: it is by design that by default `nix-env` launched as root installs into the system-wide default profile.

**Comment by vcunat** [comment] 2017-03-03 21:46
Yes.  What would be wrong if that root's profile took precedence, but I guess that was just a misunderstanding somewhere.

**Comment by alexeymuranov** [comment] 2017-03-03 22:11
Hm, i thought that root had its own profile `/nix/var/nix/profiles/per-user/root/`, which was different from system profile `/nix/var/nix/profiles/system/`, and that system profile was configured exclusively through `/etc/nixos/configuration.nix`.  Apparently i was confused.  Thanks for the explanation.

I am preparing yet another bug report ;).
