### ISSUE TITLE
DNS fails during nixos-install in Virtualbox

### ISSUE THREAD

**Issue by joehillen** [NixOS/nixpkgs#6066] opened 2015-01-30 00:02 UTC
I've been trying to automate building a NixOS Vagrant image [here](https://github.com/joehillen/nixbox), and I'm running into an issue with DNS.

https://gist.github.com/joehillen/93c3798956a633ecb3fa#file-nixos-install-log-L2799

To reproduce, install virtualbox and [packer](https://www.packer.io/) and run:

    git clone https://github.com/joehillen/nixbox
    cd  nixbox
    make

**Comment by falsifian** [comment] 2015-02-11 06:34
The symptom is similar to https://github.com/NixOS/nixpkgs/issues/5337 . But that should be fixed, so I don't know what's going on here.

You could see if ```nix-prefetch-url mirror://gnu/binutils/binutils-2.23.1.tar.bz2``` works, but I don't really expect it to.

Thinking toward a workaround: What nixpkgs git revision are you using? In theory a compiled ```binutils``` should be available from hydra, so the installer shouldn't be building it. But if your nixpkgs is too old (hydra has limited space) or too new (see hydra status at http://hydra.nixos.org/jobset/nixpkgs/trunk) they won't be available.

**Comment by joehillen** [comment] 2015-02-11 06:43
My nixpkgs is whatever comes on the NixOS-14.12 iso, so maybe that fix didn't quite make it into the release. Considering the timing, it seems likely.

**Comment by falsifian** [comment] 2015-02-11 06:52
Ah, that might explain it. A couple of possible solutions:
* If you can set up nixpkgs somewhere (you don't need full nixos), then it's pretty easy to [build your own installation iso](https://nixos.org/nixos/manual/sec-building-cd.html).
* You might be able to just use the NixOS-14.12 iso and update nixpkgs after booting the installer

**Comment by rbvermaa** [comment] 2015-02-11 12:23
I cannot reproduce this issue at this moment. Everything seems be downloading just fine.

**Comment by rbvermaa** [comment] 2015-02-11 12:32
And it failed for me now too, let's see what we can figure out.

**Comment by rbvermaa** [comment] 2015-02-11 12:56
I have no idea what is going on, but when nixos-install is cancelled and run in the same running VM, it actually succeeds.

**Comment by wmertens** [comment] 2015-02-13 13:46
Well, after you forked the nixbox repo you didn't change anything that would impact DNS resolution, so there must be an issue with something in NixOS. Did you try building with 14.04 to confirm that it worked at some point?

I think the least-effort way forward is doing a bisection, trying to build various 14.04/14.11 versions until you find the set of changes that might be the problem.

**Comment by joehillen** [comment] 2015-02-13 16:01
@wmertens That's my plan, but I'm busy with another project right now. I'll be able to get to it sometime next week.

**Comment by joehillen** [comment] 2015-02-27 04:34
Just wanted to give a little status update on this.

The issue is fixed in master, but I have no idea which commit did it. I tried to do a bisect to find it, but no luck.

Right now I'm working through a bisect of the release-14.12 branch to try to find the commit that caused it.

The tests take a long time, anywhere from 30 minutes to 4 hours each, but hopefully I'll find it.

**Comment by joehillen** [comment] 2015-03-04 15:56
So I have to give up one this issue. The bisect has become hopeless. All I've been able to determine is that the issue was introduced when staging was merged into master, de99c9c. 

The branch base will not build because it's too old, and most of the commits on that branch fail to boot, so I can't determine where this bug was introduced.

**Comment by wmertens** [comment] 2015-03-04 18:38
@joehillen Well thanks for trying in any case.

Did you consider bisecting master instead of the staging branch? I also
don't understand why things won't build when they're old...

**Closed** 2016-02-22 11:49 UTC
Labels: 0.kind: bug
