### ISSUE TITLE
Go's interface to macOS's keychain certificate store is currently broken

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#24127] opened 2017-03-20 14:57 UTC
See #24058 #24124 for context. Basically Go programs should be able to check the system keychain for certificates but they currently segfault when trying to.

**Comment by LnL7** [comment] 2017-03-20 19:08
"turns out" this is actually caused by https://github.com/NixOS/nixpkgs/issues/12346.
The go binary itself links against both the pure CF and Security.framework, the setup-hook added in https://github.com/NixOS/nixpkgs/pull/22571 only rewrites `dyld`s at the moment.

**Comment by LnL7** [comment] 2017-10-04 20:35
Fixed by #27598

**Closed by LnL7** 2017-10-04 20:35 UTC
Labels: 0.kind: bug, 6.topic: golang
