### ISSUE TITLE
How to download the oraclejdk package 

### ISSUE THREAD

**Issue by abhi18av** [NixOS/nixpkgs#47223] opened 2018-09-23 14:17 UTC
Hi everyone,

I'd like to know how can I install the `oraclejdk8` which seems to be listed here 
https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/compilers/oraclejdk

I do need oraclejdk for my workload and so far I've been trying without any success.

Please do help me out :)

**Comment by srhb** [comment] 2018-09-23 14:49
Please see this section on installing unfree software and after setting the relevant settings, try installing it again. It should emit instructions that you can follow.

https://nixos.org/nixpkgs/manual/#sec-allow-unfree

**Comment by Ma27** [comment] 2018-09-23 16:27
ah my bad, I forgot that `requireFile` delivers an error message for this if now `message` is passed to `requireFile`, sorry! :sweat_smile:

**Comment by srhb** [comment] 2018-09-23 16:27
No problem, was just confused as I couldn't reproduce it. :D

**Comment by volth** [comment] 2018-09-23 21:47
generally, overriding ```requireFile``` helps

something like

```
nixpkgs.overlays = [
  (self: super:
  let
    oracleurls = {
      "jdk-8u171-linux-x64.tar.gz"            = http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/jdk-8u171-linux-x64.tar.gz;
      "jdk-8u171-linux-i586.tar.gz"           = http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/jdk-8u171-linux-i586.tar.gz;
      "jdk-8u171-linux-arm32-vfp-hflt.tar.gz" = http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/jdk-8u171-linux-arm32-vfp-hflt.tar.gz;
      "jdk-8u171-linux-arm64-vfp-hflt.tar.gz" = http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/jdk-8u171-linux-arm64-vfp-hflt.tar.gz;

      "jdk-8u181-linux-x64.tar.gz"            = http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.tar.gz;
      "jdk-8u181-linux-i586.tar.gz"           = http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-i586.tar.gz;
      "jdk-8u181-linux-arm32-vfp-hflt.tar.gz" = http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-arm32-vfp-hflt.tar.gz;
      "jdk-8u181-linux-arm64-vfp-hflt.tar.gz" = http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-arm64-vfp-hflt.tar.gz;
    };
    requireFileOracle = {name, sha256, url}: self.stdenv.mkDerivation {
      inherit name;
      outputHashMode = "flat";
      outputHashAlgo = "sha256";
      outputHash = sha256;
      buildCommand = "${self.curl}/bin/curl -L --insecure -o $out -H 'Cookie: oraclelicense=accept-securebackup-cookie' ${oracleurls.${name}}";
    };
  in {
    oraclejdk8 = super.oraclejdk8.override { requireFile = requireFileOracle; };
  })
];
```

**Comment by srhb** [comment] 2018-09-23 21:59
@abhi18av I am closing this since everything appears to be working correctly. Please feel free to leave another comment if you still require assistance.

**Closed by srhb** 2018-09-23 21:59 UTC

**Comment by mardambey** [comment] 2019-02-13 03:30
```
  nixpkgs.config = { 

    allowUnfree = true;
    oraclejdk.accept_license = true;

  }
```

**Comment by cata0309** [comment] 2020-10-05 19:01
How to find the auto generated password ?! I cannot login to sys as sysdba
