### ISSUE TITLE
Add Nativefier

### ISSUE THREAD

**Issue by Zahrun** [NixOS/nixpkgs#212075] opened 2023-01-22 10:47 UTC
**Project description**
Make any web page a desktop application 

**Metadata**

* homepage URL: https://github.com/nativefier/nativefier
* source URL: https://github.com/nativefier/nativefier
* license: mit
* platforms: dos, linux, darwin

**Comment by dit7ya** [comment] 2023-01-22 15:49
Closing as duplicate of #183095.

**Closed by dit7ya** 2023-01-22 15:49 UTC
Labels: 0.kind: packaging request
