### ISSUE TITLE
qtcreator core dumped : Could not initialize GLX

### ISSUE THREAD

**Issue by LuxoftAKutsan** [NixOS/nixpkgs#101202] opened 2020-10-20 18:24 UTC
**Describe the bug**

**To Reproduce**
1.  sh <(curl -L https://nixos.org/nix/install)
2. . ~/.nix-profile/etc/profile.d/nix.sh
2.  nix-shell -p qtcreator --run qtcreator

**Expected behavior**
qtcreator started

**Actual behavior**
QtCreator crashed
```
alex@alex-WorkStation:~$ nix-shell -p qtcreator --run qtcreator 

(process:13640): Gtk-WARNING **: 21:20:27.168: Locale not supported by C library.
	Using the fallback 'C' locale.
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Could not initialize GLX
/tmp/nix-shell-13626-0/rc: line 1: 13640 Aborted                 (core dumped) qtcreator

```

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-48-generic, Linux Mint, 19.3 (Tricia)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(alex): `"nixos-20.03-20.03.3129.d3784204ba1, nixpkgs-20.09pre244104.5e199f944cf"`
 - nixpkgs: `/home/alex/.nix-defexpr/channels/nixpkgs`

**Comment by LuxoftAKutsan** [comment] 2020-10-20 18:25
Also tested on 
 - https://channels.nixos.org/nixpkgs-20.03-darwin 
 - https://channels.nixos.org/nixpkgs-unstable
Results are the same

Tried solution from https://github.com/NixOS/nixpkgs/issues/82959#issuecomment-657306112
Qt creator succesfull started, but crashed on "Open project" dialog 
```
alex@alex-WorkStation:~$ export QT_XCB_GL_INTEGRATION=none 
alex@alex-WorkStation:~$ nix-shell -p qtcreator --run qtcreator 

(process:14240): Gtk-WARNING **: 21:25:06.761: Locale not supported by C library.
	Using the fallback 'C' locale.
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
Qt: Session management error: None of the authentication protocols specified are supported
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled

(qtcreator:14240): GLib-GIO-ERROR **: 21:25:12.557: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
ConnectionServer error: "QLocalSocket: Remote closed" "/run/user/1000/QtCreator-tnEfIy/ClangBackEnd-14240"
/tmp/nix-shell-14228-0/rc: line 1: 14240 Trace/breakpoint trap   (core dumped) qtcreator

```

**Comment by symphorien** [comment] 2020-10-20 19:16
Looks like the generic problem of openGL on non-nixos: https://github.com/guibou/nixGL

**Comment by ppenguin** [comment] 2021-01-10 13:10
> Looks like the generic problem of openGL on non-nixos: https://github.com/guibou/nixGL

Indeed, I had the same problem with `freecad` and can reproduce described behaviour for `qtcreator`, and it works with `nixGL` (in my case `nixGLIntel qtcreator`)

I'd say it would be conducive to have automatic stubs installed that execute any openGL dependent apps with `nixGL` , but it doesn't appear so easy (see [this discussion](https://github.com/NixOS/nixpkgs/issues/9415))

**Comment by BenediktBroich** [comment] 2022-10-23 12:04
I have the same problem on nixos unstable.

**Comment by Artturin** [comment] 2022-10-25 16:28
dupe of https://github.com/NixOS/nixpkgs/issues/82959

**Closed by Artturin** 2022-10-25 16:28 UTC
Labels: 0.kind: bug, 6.topic: qt/kde
