### ISSUE TITLE
`cubicsdr` crashes on start

### ISSUE THREAD

**Issue by mryndzionek** [NixOS/nixpkgs#219206] opened 2023-03-02 17:07 UTC
### Describe the bug
CubicSDR installed from unstable crashes almost immediately.

### Steps To Reproduce
1. Run 'CubicSDR'
2. Observe the crash - 'Program received signal SIGILL, Illegal instruction.'

### Expected behavior
The application should start, GUI should appear.

### Additional context
Backtrace from GDB:
```
Program received signal SIGILL, Illegal instruction.
0x00007ffff7c2cc78 in nco_crcf_create () from /nix/store/h9cm2ycz9yk615fspx59nji6v1z98qd4-liquid-dsp-1.5.0/lib/libliquid.so
(gdb) backtrace 
#0  0x00007ffff7c2cc78 in nco_crcf_create () from /nix/store/h9cm2ycz9yk615fspx59nji6v1z98qd4-liquid-dsp-1.5.0/lib/libliquid.so
#1  0x00000000005a6c4a in SpectrumVisualProcessor::SpectrumVisualProcessor() ()
#2  0x00000000005b3408 in SpectrumVisualDataThread::SpectrumVisualDataThread() ()
#3  0x00000000004bd72b in CubicSDR::OnInit() ()
#4  0x00007ffff6ff8c2a in wxEntry(int&, wchar_t**) () from /nix/store/ihsr9861xnbccs8d2gmz0kbkzjy3ack1-wxwidgets-3.2.2.1/lib/libwx_baseu-3.2.so.0
#5  0x00000000004a9a7e in main ()
```

### Notify maintainers
@lasandell

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-67-generic, Linux Mint, 21.1 (Vera), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.14.0`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`
```

**Comment by lasandell** [comment] 2024-07-10 15:33
Closing as unable to reproduce this with an RTLSDR, but it was likely fixed by #254649. Can reopen if issue persists.

**Closed by lasandell** 2024-07-10 15:33 UTC
Labels: 0.kind: bug
