### ISSUE TITLE
gnome3.geary doesn't build

### ISSUE THREAD

**Issue by dotlambda** [NixOS/nixpkgs#118309] opened 2021-04-02 11:03 UTC
https://hydra.nixos.org/build/140600464

cc @NixOS/gnome

**Comment by lukegb** [comment] 2021-04-02 14:07
From e.g. https://hydra.nixos.org/build/140600464/nixlog/1

```
WKError: Is false, expected true
Composer.PageStateTest/edit_context_font: This call should not be reached
not ok 60 /js/Composer.PageStateTest/edit_context_font
```

**Comment by mweinelt** [comment] 2021-04-02 14:40
Caused by #117991, reported upstream at https://gitlab.gnome.org/GNOME/geary/-/issues/1180.

Fixed in #118326

**Closed** 2021-04-02 16:54 UTC
Labels: 0.kind: bug, 1.severity: channel blocker
