### ISSUE TITLE
AdGuardHome does not start up after updating nixpkgs to e6ab469 (2023-07-29)

### ISSUE THREAD

**Issue by dmoonfire** [NixOS/nixpkgs#246461] opened 2023-08-01 00:31 UTC
### Describe the bug

I recently updated my system and then AdGuardHome ceased to work.

```
• Updated input 'nixpkgs':
    'github:nixos/nixpkgs/12303c652b881435065a98729eb7278313041e49' (2023-07-22)
  → 'github:nixos/nixpkgs/e6ab46982debeab9831236869539a507f670a129' (2023-07-29)
```

The error message in the flake is:

```
adguardhome[22723]: 2023/07/31 19:17:16 [error] Couldn't get logging settings from the configuration: yaml: unmarshal errors:
adguardhome[22723]:   line 7: cannot unmarshal !!seq into filtering.BlockedServices
adguardhome[22723]:   line 28: cannot unmarshal !!seq into filtering.BlockedServices
adguardhome[22723]:   line 85: cannot unmarshal !!seq into filtering.BlockedServices
```

Originally I thought it was because /nix/store/*AdGuardHome.yaml is a JSON file, but it appears it is always that way. I'm not entirely sure what is missing to produce that error. I had a `services.adguardhome.settings` set up for rewriting, but commenting that out continued to produce the error so it doesn't seem to be that.

```
  services.adguardhome = {
    enable = true;
    openFirewall = true;
    allowDHCP = true;
    settings.bind_host = "0.0.0.0";
    settings.bind_port = port;
  };
```

### Steps To Reproduce

1. Set up AdGuardHome using the above stanza.
2. Start up the service.

### Expected behavior

It would start up and protecting my location from the evils of surveillance capitalism.

### Screenshots

N/A

### Additional context

N/A

### Notify maintainers

- @r-ryantm 
- @numkem
- @iagoq
- @rhoriguchi

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.37, NixOS, 23.11 (Tapir), 23.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by CRTified** [comment] 2023-08-01 12:09
Please set a `schema_version` to an older value, or update your configuration to match the upstream [configuration file description](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file).

This behavior is caused by #176701. It essentially fails to consume your config, as it assumes that the YAML produced follows the latest schema.

The problem likely comes from a missing `blocked_services` (under `dns`).

**Comment by CRTified** [comment] 2023-08-01 12:56
You do not need to manually edit the file. You can simply set `settings.schema_version` to the value that was used before. 
In your case, `20` would likely work, as it was the [schema version before the current one](https://github.com/NixOS/nixpkgs/commit/1c4975fb1a652c20362b5e6b49142e3d1af1e13b#diff-573ef3a39c668e9aeccf5556ad1da73d74b2e9ad271876a484039bec0fea572cR19).

I don't see a way to compromise on the default value here, as we'd either never allow newer options by default (e.g. by defaulting to a schema version of `0`), or we sometimes get this breakage.

**Comment by CRTified** [comment] 2023-08-01 13:29
So the idea would be to issue e.g. a warning if `services.adguardhome.settings.schema_version != pkgs.adguardhome.passthru.schema_version`?

I could see that this would work, yes. I think `nextcloud` handles this similarly, but nextcloud could have problems with a missing step in the upgrade path. For adguard home, one `schema_version` could work just fine for all eternity, as the schema gets updated either way on start. That's why the adguardhome test gets away with `schema_version = 0`.

**Comment by dmoonfire** [comment] 2023-08-01 13:44
Since there is a problem with it being out of sync, it has some similarities to nextcloud's update.

Related to the fix, I changed my setting to this:

```
services.adguardhome = {
  enable = true;
  openFirewall = true;
  allowDHCP = true;
  settings.bind_host = "0.0.0.0";
  settings.bind_port = port;

  settings = {
    # https://github.com/NixOS/nixpkgs/issues/246461
    schema_version = 20;
    test = 1;

    dns = {
      rewrites = [
        # Inwood Servers
        {
          domain = "***.home";
          answer = "***.***.***.***";
        }
      ];
    };
  };
};
```

but it produced this file:

```
bind_host: 0.0.0.0
bind_port: 3005
dns:
  rewrites:
    - answer: ***.***.***.***
      domain: ***.home
schema_version: 24
test: 1
```

This doesn't work. I noticed that `schema_version` is still 24, which seems not to fit with the suggested fix.

I did try setting mutableSettings.

```
    settings = {
      mutableSettings = false;
      schema_version = 20;
```

This is in the build output:

```
[info] AdGuard Home, version v0.107.34
[info] Upgrade yaml: 20 to 21
[info] Upgrade yaml: 21 to 22
[info] Upgrade yaml: 22 to 23
[info] Upgrade yaml: 23 to 24
```

But it still failed. I also tried added filtering...

```
    settings = {
      mutableSettings = false;
      schema_version = 24;

      dns = {
        filtering.blocked_services = [];
```

which produced this file:

```
{"bind_host":"0.0.0.0","bind_port":3005,"dns":{"filtering":{"blocked_services":[]},"rewrites":[{"answer":"***.***.***.***","domain":"***.home"}]},"mutableSettings":false,"schema_version":24}
```

which also failed to run.

(at least I know why I see yaml sometimes and json the other times. :)

**Comment by CRTified** [comment] 2023-08-01 14:10
@rhoriguchi This wasn't detected by the tests because they pin the `schema_version` to 0, correct? Maybe we can add another test case for a default `schema_version` :thinking:

**Comment by dmoonfire** [comment] 2023-08-01 14:15
After a bunch of things, I edited `/var/lib/AdGuardHome/AdGuardHome.yaml`, deleted everything but the first few lines, and then did a redeploy. That got rid of a bunch of `blocked_services: []` entries that were in probably when I was manually editing(?) but weren't updated (maybe because the schema was set to 24 before it was copied up in the Nix closure?).

**Comment by sjau** [comment] 2023-08-06 06:34
I could never get AGH to properly configure thought the Nixos settings, so I've just been using the web interface for configuration. However with every update it breaks configuration again.

**Comment by CRTified** [comment] 2023-08-06 10:50
@sjau Can you open a new issue and share the relevant config there? Because that should not happen, at least if you set `services.adguardhome.settings = null;`.

**Comment by sjau** [comment] 2023-08-07 08:46
IMHO this should not be closed.

I just tested the schema_version pinning:

1. I setup a VM using git rev. 04af42f3b31
2. I added this to my config:

```
    # AdGuard Home
    services.adguardhome = {
        enable = true;
        openFirewall = true;
        settings = {
            bind_port = 3000;
            users = [ {
                name = "myUser";
                password = "$........";
            } ];
            upstream_dns =  [ "127.0.0.1:5335" ];
            schema_version = 20;
        };
    };
```

3. That worked fine.
4. Then I updated unstable to rev. 5a8e9243812b
5. I restarted and it failed to start AGH:

```
grep schema_version /data/AdGuardHome/AdGuardHome.yaml
schema_version: 24
```

**Comment by CRTified** [comment] 2023-08-07 11:14
Oh, I think that I understand the problem now. @dmoonfire you're likely correct. To reiterate the problem, and let's assume without loss of generality that the old schema version is `20` and the new one `24`:

 1. Config file in `/var/lib` is on version `20`
 2. AGH gets updated in nixpkgs to schema version `24`
 3. nix-controlled portion of the config file gets recreated by the module
 4. `checkPhase` running the AGH with `24` bumps the schema version and layout in the nix-controlled portion
 5. The generated and the residing configs get merged, where the generated one takes precedence

So the old config is on a schema version pre 24, while the one that gets merged is at 24.

I'd assume one fix would be to bump the residing schema version prior to merging, and another one would be to not merge if residing version < generated version.
I'm preferring the first approach, as the second one does the same, but requires one additional restart. Thanks to the statefulness of it, it is likely sufficient to just add 
```sh
${pkgs.adguardhome}/bin/adguardhome -c "/var/lib/AdGuardHome/AdGuardHome.yaml" --check-config
```
into the `preStart` **prior** to merging, which should bump the residing config to the "new" schema version.

Any objections?

**Comment by sjau** [comment] 2023-08-07 11:17
> Oh, I think that I understand the problem now. [...]

I think that's whats happening. This results in AGH unable to start.

**Comment by dmoonfire** [comment] 2023-08-07 13:43
Upgrading both sides (nix-controlled and previous) before merging sounds like it would a good solution, I'm in favor of your first suggestion.

**Comment by sjau** [comment] 2023-09-23 16:23
Has anyone figured out how to add custom filters to the nixos configuration?

When adding a custom filter through the WUI it will look in the AGH config like this:

```
user_rules:
  - '@@||domain.tld^$important'
  - ""
````

However I don't know how to recreate that in the nixos configuration file.

It did not like this:

```
            filters = [
                {   enabled = true;
                    url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt";
                    name = "AdGuard DNS filter";
                    id = 1; }
                {   enabled = true;
                    url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt";
                    name = "AdAway Default Blocklist";
                    id = 2; }
                    .....
            ];
            user_rules = [
                { '@@||domain.tld^$important'; }
                { ""; }
            ];
```

**Comment by CRTified** [comment] 2023-11-06 21:45
@sjau It is likely not related to this issue. 

You can supply `user_rules` as list of strings, e.g.
```nix
            user_rules = [
                "@@||domain.tld^$important"
            ];
```

**Closed** 2024-06-10 10:46 UTC
Labels: 0.kind: bug
