### ISSUE TITLE
Package request: Unreal Engine

### ISSUE THREAD

**Issue by Yanall-Boutros** [NixOS/nixpkgs#314405] opened 2024-05-24 22:06 UTC
Unreal Engine is a popular engine for developing games with.[ I  was able to get it running in NixOS](https://discourse.nixos.org/t/ue-compile-failures-on-latest-nix/29267/5?u=yanall-boutros) but with some extra work and help from others. This was the case as well for windows since either way you have to create a git account and associate it with Epic.

If the process could be automated to a similar process as installing TensorRT, that would be amazing. Specifically, the build log from `nixos-rebuild switch` would throw a warning and a link [to register your github](https://dev.epicgames.com/documentation/en-us/unreal-engine/downloading-unreal-engine-source-code) to download through git or [to download the zip directly](https://www.unrealengine.com/en-US/linux)

**Metadata**

* homepage URL: https://www.unrealengine.com/
* source URL:  
* * [Downloading the source code](https://dev.epicgames.com/documentation/en-us/unreal-engine/downloading-unreal-engine-source-code)
* * [Building from source (from 4.27 but same steps, prefixed with steam-run, such as steam-run ./UnrealEngine/Engine/Binaries/Linux/UnrealEditor](https://docs.unrealengine.com/4.27/en-US/ProductionPipelines/DevelopmentSetup/BuildingUnrealEngine/)
* license: Not sure, [here's their EULA](https://github.com/EpicGames/UnrealEngine/blob/5.4.1-release/LICENSE.md)
* platforms: unix, linux

---

**Comment by jopejoe1** [comment] 2024-05-25 08:12
Duplicate of #124963

**Closed by jopejoe1** 2024-05-25 08:12 UTC
Labels: 0.kind: packaging request
