### ISSUE TITLE
fmod broken

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#21154] opened 2016-12-14 17:44 UTC
## Issue description
Fmod fails to build, because the download is [no longer available except by registering and explicitly requesting access from FMOD support](http://www.fmod.org/download/#Previous).

```
% nix-build '<nixpkgs>' -A fmod
these derivations will be built:
  /nix/store/qz6ilwx3d6882d9kcggirgwlxah8szd5-fmodapi44441linux.tar.gz.drv
  /nix/store/i57xrjj7j6cs42skyp320r26hwkpsjmy-fmod-4.44.41.drv
building path(s) ‘/nix/store/s4xq3cvn3p8z803wammqk6ilwyxq74pf-fmodapi44441linux.tar.gz’

trying http://www.fmod.org/download/fmodex/api/Linux/fmodapi44441linux.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3240  100  3240    0     0   6851      0 --:--:-- --:--:-- --:--:--  9446
output path ‘/nix/store/s4xq3cvn3p8z803wammqk6ilwyxq74pf-fmodapi44441linux.tar.gz’ has sha256 hash ‘0ll34c78f697f2sn8d1siah2jdla6ykqwa4pbpc9bkgpzy8izacz’ when ‘0qjvbhx9g6ijv542n6w3ryv20f74p1qx6bbllda9hl14683z8r8p’ was expected
cannot build derivation ‘/nix/store/i57xrjj7j6cs42skyp320r26hwkpsjmy-fmod-4.44.41.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/i57xrjj7j6cs42skyp320r26hwkpsjmy-fmod-4.44.41.drv’ failed
```

### Steps to reproduce
`nix-build '<nixpkgs>' -A fmod`

**Comment by abbradar** [comment] 2016-12-16 15:39
The only thing we can do I believe is to change `fetchurl` to `requireFile` with an explanation of how one can get fmod libraries nowadays. Maybe try mailing their support describing the situation and asking for a permalink?

**Comment by lheckemann** [comment] 2016-12-17 01:10
If they wanted to make peoples' lives easy they wouldn't have removed the permalink in the first place... I doubt any efforts in that direction would be fruitful.

**Comment by joachifm** [comment] 2016-12-17 03:52
Looks somewhat related to https://github.com/NixOS/nixpkgs/issues/10213.

**Comment by abbradar** [comment] 2016-12-17 10:11
Duplicate of #10213 (thanks @joachifm!)

**Closed by abbradar** 2016-12-17 10:11 UTC

**Comment by abbradar** [comment] 2016-12-17 12:55
You may be interested in https://github.com/NixOS/nixpkgs/pull/21231
