### ISSUE TITLE
Visual studio code (vscode) only show a blank window after a recent update

### ISSUE THREAD

**Issue by astrojhgu** [NixOS/nixpkgs#259929] opened 2023-10-09 07:20 UTC
### Describe the bug
After a recent update, the `vscode`  only show a blank window after started.

### Steps To Reproduce
1. `nix-shell -p vscode`
2. `code --disable-extensions`

A blank window is shown, and you cannot input any character.

### Expected behavior
it show work normally

### Screenshots
![Screenshot from 2023-10-09 15-18-40](https://github.com/NixOS/nixpkgs/assets/2651231/f3f62fa0-109c-4237-8248-258ef2d4727b)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.11 (Tapir), 23.11pre533189.87828a0e03d1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos"`
 - channels(user): `"home-manager"`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`
```

**Comment by 0x416E64** [comment] 2023-10-09 09:55
Happened to me to, with `code --verbose` was throwing shader compilation error, VS code started with `code  --disable-gpu-driver-bug-workarounds`, so it's somewhere with GPU drivers & electron.

Removing `~/.config/Code/GPUCache/` fixed the issue for me (and for now, supposedly the issue might return) even without the workaround electron flag.

**Comment by astrojhgu** [comment] 2023-10-09 13:25
Yes, removing the GPUCache does fix this issue, at least for the moment.
Thanks.
> Removing `~/.config/Code/GPUCache/` fixed the issue for me (and for now, supposedly the issue might return) even without the workaround electron flag.

**Comment by I-Want-ToBelieve** [comment] 2023-10-17 15:36
The same thing happens on chrome browser

**Comment by DrymarchonShaun** [comment] 2023-10-27 02:07
Effecting `discord` and `heroic` as well, deleting GPUCache does nothing.

**Comment by I-Want-ToBelieve** [comment] 2023-10-28 02:11
It should be an upstream problem

**Comment by jcmsj** [comment] 2023-12-17 06:59
Thanks, deleting GPUCache works for me

**Comment by Tommimon** [comment] 2024-01-23 09:26
The problem has been solved for electron 28 as pointed out in [electron/electron#40366](https://github.com/electron/electron/issues/40366).

We have to wait for vscode to update to electron 28, follow [microsoft/vscode#201935](https://github.com/microsoft/vscode/issues/201935) for news.

**Comment by AndrewKvalheim** [comment] 2024-03-04 19:15
Same issue as #241337?

**Comment by Tommimon** [comment] 2024-04-05 23:23
Updates: 
1) `vscode` bumped electron version and the latest release `1.88` [ships electron 28](https://code.visualstudio.com/updates/v1_88#_engineering).
2) `vscode` was already updated in nixpkgs [#301684](https://github.com/NixOS/nixpkgs/pull/301684).
3) You can [track](https://nixtracker.org/) the pull request and check if the issue is solved when it lends on unstable.

**Comment by SuperSandro2000** [comment] 2024-09-11 19:09
dupe of #244742

**Closed by SuperSandro2000** 2024-09-11 19:09 UTC
Labels: 0.kind: bug, 2.status: wait-for-upstream
