### ISSUE TITLE
Darwin regressions on hydra

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#82893] opened 2020-03-18 23:43 UTC
**Describe the bug**
Seems that many darwin builds are now breaking suddenly. Seems to be a multitude of reasons. Just odd that it all seems to be specific to darwin.

https://hydra.nixos.org/eval/1576403

example error:
```
/nix/store/2kcifdkr7m14csgch00ajbz28irdwhff-bash-4.4-p23/bin/bash: /nix/store/r4fs9daiww3xcjrbdqd6av375ir8v7fn-cmake-3.16.5/bin/cmake: No such file or directory
make[2]: *** [source/blender/
```

**Comment by svend** [comment] 2020-03-20 17:20
```

**Comment by vcunat** [comment] 2020-03-20 20:36
Similar error appear continuously on Hydra &ndash; reference to some *other* package where the file suddenly appears missing or malformed.  I believe there's some problem in the builder set up.  Too aggressive GC (if that's even possible) or some other corruption.  The ones I saw always disappeared.

**Comment by tsaeger** [comment] 2020-03-21 16:43
FWIW - this fixed my go issues on darwin

https://github.com/tsaeger/nixpkgs/commit/39386e9f81552720468acd0eb35becec863c0e37

**Comment by tsaeger** [comment] 2020-03-21 16:58
seems related to: 060a9227c24639ca5a339fbb57b8e05a5eabb92e
reverting that commit also worked for me on darwin.

**Comment by tsaeger** [comment] 2020-03-21 19:31
incoming: https://github.com/NixOS/nixpkgs/pull/83103

**Comment by marsam** [comment] 2020-03-23 02:01
Closing since most of these regressions were because buildGoModule https://github.com/NixOS/nixpkgs/pull/83099

**Closed by marsam** 2020-03-23 02:01 UTC
Labels: 0.kind: bug, 6.topic: darwin

**Comment by vcunat** [comment] 2020-03-23 07:00
Well, yes.  Errors like in the OP and my post seem unrelated (e.g. [`blender`](https://hydra.nixos.org/build/115118520)) and appear non-deterministically for much longer time (i.e. not really recent regressions).
