### ISSUE TITLE
Language packs are not automatically installed for KDE apps

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#63934] opened 2019-06-29 22:51 UTC
## Issue description

Language packs for KDE apps are not installed even when the relevant options are installed
See also https://github.com/NixOS/nixpkgs/issues/3541

### Steps to reproduce

- Add `i18n.defaultLocale="it_IT.UTF_8";environment.systemPackages=[pkgs.ksysguard]`to `/etc/nixos/configutation.nix`
- `nixos-rebuild switch`
- See as some menu in KSysGuard entries are in Italian and other are in English.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.55, NixOS, 19.09pre183832.20b993ef2c9 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre183832.20b993ef2c9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment] 2019-06-30 01:54
Duplicate of #37741

**Comment by lheckemann** [comment] 2019-07-12 05:44
Closing since it's a duplicate

**Closed by lheckemann** 2019-07-12 05:44 UTC
