### ISSUE TITLE
python27Packages.cffi fails to build on master

### ISSUE THREAD

**Issue by eduardosm** [NixOS/nixpkgs#108608] opened 2021-01-06 19:44 UTC
**Describe the bug**

python27Packages.cffi fails to build on master.

[Build log](https://github.com/NixOS/nixpkgs/files/5777832/build-log.txt)

**Notify maintainers**

@domenkozar @lnl7

**Comment by marsam** [comment] 2021-01-08 08:30
Duplicate of https://github.com/NixOS/nixpkgs/issues/108243

**Closed by marsam** 2021-01-08 08:30 UTC
Labels: 0.kind: bug, 6.topic: python
