### ISSUE TITLE
[Build Failure]: Unable to build in texlive from scratch to a custom NIX_STORE

### ISSUE THREAD

**Issue by rowhit** [NixOS/nixpkgs#47157] opened 2018-09-22 01:15 UTC
## Issue description
- Unable to build **texlive** when trying to build to a custom NIX_STORE.

### Steps to reproduce
nix-env -f '<nixpkgs>' -iA texlive 

## Technical details
configure: ** PCRE (Headers)
checking pcre.h usability... yes
checking pcre.h presence... yes
checking for pcre.h... yes
configure: ** PCRE (Functions)
checking for library containing pcre_compile... no
configure: error: cannot find PCRE library
make[1]: Entering directory '/tmp/nix-build-clisp-2.49.drv-0/clisp-2.49/builddir/pcre'
make[1]: *** No rule to make target 'clisp-module'.  Stop.
make[1]: Leaving directory '/tmp/nix-build-clisp-2.49.drv-0/clisp-2.49/builddir/pcre'
make: *** [Makefile:2597: pcre] Error 2

**Comment by xeji** [comment] 2018-09-22 11:41
Sorry, I am unable to reproduce with the information given:
```
$ nix-env -f '' -iA texlive
error: attribute 'texlive' in selection path 'texlive' not found
```

Please paste the result of `nix-shell -p nix-info --run "nix-info -m"`  so we have information about your system, and explain what your custom setup looks like (do you set nix-related environment variables? do you have a custom `nix.conf` etc.).

Also please note that the `texlive` attribute is not a single installable package but an attribute set containing may texlive-related derivations. It is not meant to be installed like you tried to. You would typically install  texlive using a certain package collection, see https://nixos.org/nixpkgs/manual/#sec-language-texlive.

**Comment by rowhit** [comment] 2018-09-23 23:44
@xeji, thanks for the response.

I am building packages using nix on an old version of linux kernel  
Linux $(hostname) 2.6.32-696.13.2.el6.x86_64 #1 SMP Fri Sep 22 12:32:14 EDT 2017 x86_64 GNU/Linux

Therefore, I have a forked version of the nixpkgs repo from tag 17.09.

I am building using following script:
```bash
#!/usr/bin/env bash
#FILENAME: install-pkgs.sh

pkg_name=$1
export NIX_PATH="$NIX_PATH:nixpkgs-dev-1709=$PWD"
nix-env -f "<nixpkgs-dev-1709>" -iA $pkg_name -j 16
```

In order to run the following command, I need to install nix-info. But the compiler fails to build glibc-2.26 stating that kernel is too old. **I am not sure then how other packages have been build without glibc till now.**
```bash
nix-shell -p nix-info --run "nix-info -m"
```

I have ~/.config/nixpkgs/config.nix file to declare packages. But I do not have nix.conf. All the variables need to setup the nix environment are setup by a script nix.sh created by nix itself.
```bash
source ~/.nix-profile/etc/profile.d/nix.sh
```

**Comment by xeji** [comment] 2018-09-24 08:27
Thank you for your reply. I'm afraid I am unable to help you in this situation. You're using 17.09 which is past end-of-life, a private fork which may differ from the official repository/channel, and an old kernel that is apparently incompatible with 17.09. Unfortunately I cannot reproduce or investigate issues you encounter in this setup. 

I recommend you upgrade to a supported version of nixpkgs (currently 18.03, but 18.09 will be released end of September), which will also require a newer kernel.

**Comment by xeji** [comment] 2018-09-24 14:41
As to your glibc question: I would guess that previously you used the prebuilt glibc from `cache.nixos.org`, but some change you made in your local fork triggered a local glibc rebuild, which fails with your old kernel. Or maybe you disabled binary caches and forced a complete rebuild of everything.

Anyway, If you really must use this old kernel, my advice is to use a current version of nixpkgs and not make any modifications that require a local rebuild of glibc or other low level packages, just use the prebuilt versions from the cache. Some things should work with the old kernel, some will not - it's an unsupported configuration.

**Comment by xeji** [comment] 2018-09-26 20:14
Closing because of unsupported configuration.

**Closed by xeji** 2018-09-26 20:14 UTC
Labels: 2.status: invalid
