### ISSUE TITLE
Package request: immich

### ISSUE THREAD

**Issue by luochen1990** [NixOS/nixpkgs#319497] opened 2024-06-13 06:46 UTC
**Project description**

High performance self-hosted photo and video management solution.

**Metadata**

* homepage URL: https://github.com/immich-app/immich
* source URL: https://github.com/immich-app/immich
* license: AGPLv3
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment] 2024-06-13 07:56
Duplicate of https://github.com/NixOS/nixpkgs/issues/279316

**Closed** 2024-06-13 08:01 UTC
Labels: 2.status: duplicate, 0.kind: packaging request
