### ISSUE TITLE
kde remember screen setups for aditional screens, but doesnt allow to change them

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#24408] opened 2017-03-28 14:51 UTC
## Issue description

plasma5 remembered my main screen should be disable when my external monitor is attached,
now that i had a cable issue and the other monitor did not work as expected, it was impossible to alter that setting because whenever i attached the screen not working correctly the one that was working got turned off

i presume this should be an upstream issue?

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by RonnyPfannschmidt** [comment] 2017-03-30 10:11
i reported https://bugs.kde.org/show_bug.cgi?id=378205

**Comment by globin** [comment] 2017-03-30 12:28
Closing as this most probably is not a bug on our side and we have too much issue bloat anyway.

**Closed by globin** 2017-03-30 12:28 UTC
