### ISSUE TITLE
(request for new functionality) nixos-rebuild switch not found duplicated packages in /etc/nixos/configuration.nix during build. 

### ISSUE THREAD

**Issue by KCynk** [NixOS/nixpkgs#229887] opened 2023-05-04 12:13 UTC
### Describe the bug
(request for new functionality)
`nixos-rebuild switch` should detect duplicated packages during build.

### Steps To Reproduce
```
...
  environment.systemPackages = with pkgs; [
    aide
    gnome.gnome-terminal 
    gnome.nautilus 
    gnome.eog 
    evince
    gnome.gnome-tweaks
    gnome.gnome-calculator
    gnomeExtensions.no-overview 
    gnomeExtensions.dash-to-dock
    gnomeExtensions.hide-activities-button
    ansible 
    terraform
    keepassxc 
    calibre 
    obsidian 
    krita
    vim 
    git 
    lsof
    strace
    vscodium
    ntfs3g
    curl 
    wget
    iptables
    wireshark
    docker <------------
    libvirt
    virt-manager
    virt-viewer
    qemu 
    docker <--------------
    xorriso
    libreoffice-qt
  ];
 
  environment.gnome.excludePackages = with pkgs; [
    gnome-tour
  ];  


}

[kamil@nixos:~] sudo nixos-rebuild switch
building Nix...
building the system configuration...
activating the configuration...
setting up /etc...
reloading user units for kamil...
setting up tmpfiles
the following new units were started: libvirtd.service

```
### Additional context

```
[kamil@nixos:~] cat /etc/nixos/configuration.nix 
{ config, pkgs, ... }:

{
  system.stateVersion = "22.11";

  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];
  
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot/efi";
  boot.kernel.sysctl."net.ipv6.conf.enp0s31f6.disable_ipv6" = true;
  boot.kernel.sysctl."net.ipv6.conf.wlp2s0.disable_ipv6" = true;
  boot.kernel.sysctl."net.ipv6.conf.lo.disable_ipv6" = true;
  boot.kernel.sysctl."net.ipv6.conf.docker0.disable_ipv6" = true;
  boot.tmp.cleanOnBoot = true;
  boot.plymouth.enable = true;
  boot.initrd.secrets = {
    "/crypto_keyfile.bin" = null;
  };

  hardware.bluetooth.enable = false;
  hardware.bluetooth.powerOnBoot = false;  

  networking.networkmanager.enable = true;
  networking.tempAddresses = "disabled";
  networking.hostName = "nixos";
  networking.enableIPv6 = false;
  networking.firewall = {
    enable = true;
    allowPing = false;
    logRefusedConnections = true;
  };

  time.timeZone = "Europe/Warsaw";

  i18n.defaultLocale = "en_GB.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "pl_PL.UTF-8";
    LC_IDENTIFICATION = "pl_PL.UTF-8";
    LC_MEASUREMENT = "pl_PL.UTF-8";
    LC_MONETARY = "pl_PL.UTF-8";
    LC_NAME = "pl_PL.UTF-8";
    LC_NUMERIC = "pl_PL.UTF-8";
    LC_PAPER = "pl_PL.UTF-8";
    LC_TELEPHONE = "pl_PL.UTF-8";
    LC_TIME = "pl_PL.UTF-8";
  };

  # Configure console keymap
  console.keyMap = "pl2";

  # Terminal
  environment.variables.EDITOR = "vim";
  environment.sessionVariables = { 
     TERMINAL = "gnome-terminal";
     MOZ_ENABLE_WAYLAND = "1";
  };

  sound.enable = true;

  hardware.pulseaudio.enable = false;

  security.rtkit.enable = true;
  
  users.users.kamil = {
    description = "Kamil";
    isNormalUser = true;
    extraGroups = [ "networkmanager" "wheel" "wireshark" "docker" "dumpcap" "libvirtd" "qemu-libvirtd" "kvm" ];
    packages = with pkgs; [ 
      firefox 
    ];
  };

  users.defaultUserShell = "/run/current-system/sw/bin/bash";

  services.xserver.enable = true;
  services.xserver.excludePackages = [ pkgs.xterm ];
  services.xserver.desktopManager.xterm.enable = false;
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome.enable = true;
  services.xserver.displayManager.autoLogin.enable = true;
  services.xserver.displayManager.autoLogin.user = "nix";
  services.gnome.core-utilities.enable = false;
  services.printing.enable = false;
  # Power management
  services.upower.enable = true;
  services.power-profiles-daemon.enable = true;
  # Avahi
  services.avahi.enable = false;
  services.avahi.openFirewall = false;
  # Openssh
  services.openssh.enable = false;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };
  services.xserver = {
    layout = "pl";
    xkbVariant = "";
  };

  systemd.services."getty@tty1".enable = false;
  systemd.services."autovt@tty1".enable = false;

  virtualisation.containers.enable = true;
  virtualisation.docker.enable = true;
  virtualisation.docker.rootless.package = true;
  virtualisation.libvirtd.enable = true;
  virtualisation.libvirtd.qemu.runAsRoot = false;

  programs.wireshark.enable = true;
  programs.bash.enableCompletion = true;
  programs.bash.promptInit=''
   PS1="[\u@\H:\w\[$(tput sgr0)\]] "
  '';

  nixpkgs.config.allowUnfree = true;

  environment.shellAliases = {
    "wireshark" = "QT_STYLE_OVERRIDE=Adwaita-Dark wireshark";
  };
  environment.systemPackages = with pkgs; [
    aide
    gnome.gnome-terminal 
    gnome.nautilus 
    gnome.eog 
    evince
    gnome.gnome-tweaks
    gnome.gnome-calculator
    gnomeExtensions.no-overview 
    gnomeExtensions.dash-to-dock
    gnomeExtensions.hide-activities-button
    ansible 
    terraform
    keepassxc 
    calibre 
    obsidian 
    krita
    vim 
    git 
    lsof
    strace
    vscodium
    ntfs3g
    curl 
    wget
    iptables
    wireshark
    docker 
    libvirt
    virt-manager
    virt-viewer
    qemu 
    docker
    xorriso
    libreoffice-qt
  ];
 
  environment.gnome.excludePackages = with pkgs; [
    gnome-tour
  ];  


}
```

### Metadata
```
[kamil@nixos:~]  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.26, NixOS, 23.05 (Stoat), 23.05pre480050.1a411f23ba2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by peterhoeg** [comment] 2023-05-16 02:28
What is the problem you are trying to solve here?

**Comment by KCynk** [comment] 2023-05-16 11:16
> What is the problem you are trying to solve here?

In my opinion, when executing the `nixos-rebuild switch` command, it should also validate duplicate entries in `environment.systemPackages = with pkgs;` Currently I have duplicate entries related to docker in it. I think that when executing the command, the system should detect this error and prevent future actions. This is my opinion, of course, and in my opinion it is a bug. If this is not the right section to report this type of error please provide a link.

**Comment by Artturin** [comment] 2023-08-10 12:22
Closing because this behaviour is not a bug

**Closed by Artturin** 2023-08-10 12:22 UTC
Labels: 0.kind: bug
