### ISSUE TITLE
Package request: Free Download Manager

### ISSUE THREAD

**Issue by NazakatUmrani** [NixOS/nixpkgs#286357] opened 2024-02-04 20:18 UTC
**Project description**

Free Download Manager for Windows, macOS, Android, and Linux allows you to adjust traffic usage, organize downloads, control file priorities for torrents, efficiently download large files and resume broken downloads.

**Metadata**

* homepage URL: https://www.freedownloadmanager.org/
* source URL: https://www.freedownloadmanager.org/download-fdm-for-linux.htm
* license: GNU Public
* platforms: Linux, Android, Windows, Macos

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-02-04 23:31
dupe of #225020

**Closed by eclairevoyant** 2024-02-04 23:31 UTC
Labels: 2.status: duplicate, 0.kind: packaging request

**Comment by NazakatUmrani** [comment] 2024-02-10 20:17
I think this can be easily done, I haven't done anything like it, but I think I can do it, should I write a .nix file and test if it works or not, and then add a merge request?

Why it is not planned? Is it because you got no time or is it something else, if it is about time, I can try to contribute, I was thinking of contributing for a long time.

**Comment by eclairevoyant** [comment] 2024-02-11 00:01
It's not related to me personally at all - if there's already a packaging request open for the same software (which there is in this case, see #225020) then we'd encourage upvoting the existing issue rather than creating a duplicate one.

The original request is still open, and anyone is welcome to contribute, yourself included.
