### ISSUE TITLE
[staging] Build failure: coreutils

### ISSUE THREAD

**Issue by Jayman2000** [NixOS/nixpkgs#313700] opened 2024-05-22 14:54 UTC
### Steps To Reproduce

1. Switch to the `staging` branch (31311bf6910f0c55437924277659a845c9667a1d at the moment)
2. `nix-build -A coreutils`

### Build log

<https://gist.github.com/Jayman2000/73ce990a6da460a9ba6b057ce6198d2d>

### Additional context

This bug is blocking me from reporting another bug. At the moment, [I think that there’s a bug with the update script for `staging`’s version of the `git` package](https://github.com/NixOS/nixpkgs/pull/312211#pullrequestreview-2063838736). I can’t try to reproduce that bug at the moment because `coreutils` fails to build.

### Notify maintainers

@dasJ

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.1, NixOS, 23.11 (Tapir), 23.11.7224.a8695cbd09a7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

$ 
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment] 2024-05-22 15:03
Is coreutils failing in checkPhase?

**Comment by JohnRTitor** [comment] 2024-05-22 15:37
Coreutils have been failing for me on staging after the 9.5 upgrade(#299945), not sure why because master is on 9.5 too. Please do share logs and @dasJ might wanna take a look here.

**Comment by eclairevoyant** [comment] 2024-05-22 16:14
I see in the logs:

`FAIL: tests/shred/shred-exact.sh`

Are you testing on some exotic filesystem? See #306760.

**Comment by JohnRTitor** [comment] 2024-05-22 16:22
Not sure about Jayman2000, but I am on bcachefs, yes.

**Comment by dasJ** [comment] 2024-05-22 16:29
Duplicate of #306760, see https://github.com/NixOS/nixpkgs/issues/306760#issuecomment-2080317009

**Closed by dasJ** 2024-05-22 16:29 UTC
Labels: 0.kind: build failure
