### ISSUE TITLE
lldb: unable to find support binaries directory on darwin

### ISSUE THREAD

**Issue by FrothyMarrow** [NixOS/nixpkgs#252838] opened 2023-09-01 20:26 UTC
### Describe the bug
On Darwin, lldb is unable to locate the support binaries directory. Trying to run lldb with a target executable results in it failing with `shell expansion failed (reason: could not get support executable directory for lldb-argdumper tool)`.

### Steps To Reproduce
1. Create a target `lldb ./test`
2. Run the target `(lldb) run`

### Expected behavior
Successfully runs the target executable.

### Additional context
The problem is Darwin specific because of the way lldb locates the `bin` directory. It expects the `lib` and `bin` to be present in the same directory as indicated in the comment [here](https://github.com/llvm/llvm-project/blob/fa1dc06a1b3997f025b0d81539c31a74e6b6ec79/lldb/source/Host/macosx/objcxx/HostInfoMacOSX.mm#L146_L152). As `lib` part of the derivation is a separate output, it cannot locate the `bin` directory and fails to run the executable.

### Notify maintainers
@rrbutani @reckenrode

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.6.0, macOS 13.5`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by risicle** [comment] 2023-09-23 18:17
Can confirm, macos 10.15.

**Comment by jsoo1** [comment] 2023-09-24 21:40
Yes and I have to manually set `LLDB_DEBUGSERVER_PATH` also.

**Comment by donn** [comment] 2023-11-06 20:36
Problem perists:

```
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.1.0, macOS 14.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
 ```

**Comment by n8henrie** [comment] 2023-11-17 00:05
@jsoo1 are you getting it to work with that? No luck here:

```console
$ nix shell nixpkgs#clangStdenv nixpkgs#lldb
$ cat <<'EOF' > foo.cpp
#include <iostream>

int a_function() {
    return 42;
}

int main() {
  std::cout << "Hello, world!" << std::endl;
  std::cout << a_function() << std::endl;
  return 0;
}
EOF
$ clang++ -g ./foo.cpp
$ LLDB_DEBUGSERVER_PATH=$(nix build --print-out-paths nixpkgs#lldb)/bin/lldb-server \
    lldb \
        -o 'break set --name a_function' \
        -o run \
        -o exit \
        a.out
(lldb) target create "a.out"
Current executable set to '/var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/tmp.O6ELMV7YHV/a.out' (arm64).
(lldb) break set --name a_function
Breakpoint 1: where = a.out`a_function() + 4 at foo.cpp:4:5, address = 0x000000010000303c
(lldb) run
error: shell expansion failed (reason: could not get support executable directory for lldb-argdumper tool). consider launching with 'process launch'.
(lldb)
```

**Comment by FrothyMarrow** [comment] 2023-11-17 01:34
> @jsoo1 are you getting it to work with that? No luck here:
> 
> ```
> $ nix shell nixpkgs#clangStdenv nixpkgs#lldb
> $ cat <<'EOF' > foo.cpp
> #include <iostream>
> 
> int a_function() {
>     return 42;
> }
> 
> int main() {
>   std::cout << "Hello, world!" << std::endl;
>   std::cout << a_function() << std::endl;
>   return 0;
> }
> EOF
> $ clang++ -g ./foo.cpp
> $ LLDB_DEBUGSERVER_PATH=$(nix build --print-out-paths nixpkgs#lldb)/bin/lldb-server \
>     lldb \
>         -o 'break set --name a_function' \
>         -o run \
>         -o exit \
>         a.out
> (lldb) target create "a.out"
> Current executable set to '/var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/tmp.O6ELMV7YHV/a.out' (arm64).
> (lldb) break set --name a_function
> Breakpoint 1: where = a.out`a_function() + 4 at foo.cpp:4:5, address = 0x000000010000303c
> (lldb) run
> error: shell expansion failed (reason: could not get support executable directory for lldb-argdumper tool). consider launching with 'process launch'.
> (lldb)
> ```

Use `nixpkgs#llvmPackages.lldb` instead of `nixpkgs#lldb`. The former one does not contain the `lib` output, so you can use an environment variable.
```
$ LLDB_DEBUGSERVER_PATH=/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Resources/debugserver nix run nixpkgs#lldb
```

**Comment by RaitoBezarius** [comment] 2024-01-12 20:07
> @RaitoBezarius What would be the preferable solution from an LLVM maintainers perspective? The lib output could be dropped, or LLVM would need to be patched to look for the support binaries in the correct path.

I would suggest a LLVM patch that could be general enough that we could send back to upstream, worst case, we can reassemble an out and lib just for this usecase in the meantime for Darwin.

**Comment by kuznetsss** [comment] 2024-05-02 16:53
@RaitoBezarius, are you sure it should be fixed on LLVM side? Because lldb from homebrew works fine on macos.

**Comment by reckenrode** [comment] 2024-05-02 18:01
The fix is probably similar to what I did for LTO support (using `substitute` to hardcode the path to the right location in the store).

**Comment by n8henrie** [comment] 2024-05-03 18:25
Here is the homebrew formula: https://github.com/Homebrew/homebrew-core/blob/c841a0bc1c35617d70c5f263751bfa939eabf969/Formula/l/llvm.rb#L1

**Comment by reckenrode** [comment] 2024-05-04 22:11
I’m working on a patch. The fix is to combine `out` and `lib` on Darwin. It’s not possible to patch LLDB to know the location of `out` because that creates a cycle between the two outputs.

**Comment by reckenrode** [comment] 2024-05-05 01:43
I created https://github.com/NixOS/nixpkgs/pull/309165. It doesn’t exhibit the `lldb-argdumper` problem, but it also doesn’t seem to work. It may be that this is as good as it can get without the requisite entitlements.

**Comment by n8henrie** [comment] 2024-05-05 08:51
@reckenrode lldb from your PR seems to work for me, even when I unset `LLDB_DEBUGSERVER_PATH` (my workaround for the prior issues). What wasn't working for you?

```console
$ env | grep '^LL'
$
$ result/bin/lldb -o 'break set --name foo::a_function' -o 'run' target/debug/foo
(lldb) target create "target/debug/foo"
Current executable set to '/var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/tmp.XSv1uqijWg/foo/target/debug/foo' (arm64).
(lldb) break set --name foo::a_function
Breakpoint 1: where = foo`foo::a_function::h7a15528ee39ef97c + 20 at main.rs:2:5, address = 0x000000010000088c
(lldb) run
Process 72578 stopped
* thread #1, name = 'main', queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x000000010000088c foo`foo::a_function::h7a15528ee39ef97c at main.rs:2:5
   1    fn a_function() -> u8 {
-> 2        println!("hello from a function");
   3        7
   4    }
   5
   6    fn main() {
   7        a_function();
Process 72578 launched: '/var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/tmp.XSv1uqijWg/foo/target/debug/foo' (arm64)
```

**Comment by reckenrode** [comment] 2024-05-05 13:11
When I follow the steps you provided in https://github.com/NixOS/nixpkgs/issues/252838#issuecomment-1815522383, I get the following result:

```
$ cat foo.cc
#include <iostream>

int a_function() {
    return 42;
}

int main() {
  std::cout << "Hello, world!" << std::endl;
  std::cout << a_function() << std::endl;
  return 0;
}
$ clang++ -g ./foo.cc
$ LLDB_DEBUGSERVER_PATH=$(nix build --print-out-paths .#lldb)/bin/lldb-server \
                                                                         lldb \
                                                                             -o 'break set --name a_function' \
                                                                             -o run \
                                                                             -o exit \
                                                                             a.out
(lldb) target create "a.out"
Current executable set to '/Users/reckenrode/Developer/nixpkgs/a.out' (arm64).
(lldb) break set --name a_function
Breakpoint 1: where = a.out`a_function() at foo.cc:4:5, address = 0x00000001000030ac
(lldb) run
error: Connection shut down by remote side while waiting for reply to initial handshake packet
(lldb)
```

It only works if I _don’t_ set `LLDB_DEBUGSERVER_PATH`.

**Comment by reckenrode** [comment] 2024-05-05 17:43
Reopening because the change is technically breaking, and we’re in a breaking change freeze before the release.

**Comment by reckenrode** [comment] 2024-05-05 19:47
Note that if you do need this, you can cherry-pick my commit from #309165.

**Comment by n8henrie** [comment] 2024-05-05 20:00
> It only works if I don’t set LLDB_DEBUGSERVER_PATH.

Yes, I see that error with my own MRE (haha) if I set `LLDB_DEBUGSERVER_PATH` to the nix version; it works with `LLDB_DEBUGSERVER_PATH=/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Resources/debugserver` (which I assume is the default anyway).

**Comment by fangjunzhou** [comment] 2024-05-17 03:42
When will this feature typically merged from master to unstable branch?

**Comment by fangjunzhou** [comment] 2024-05-17 03:51
Nvm, just noticed that it was reverted :/

**Comment by reckenrode** [comment] 2024-05-17 16:09
I had to revert because there is a freeze on breaking changes until 24.05 is released. Once 24.05 is released, I’ll reopen the fix PR.

**Comment by fangjunzhou** [comment] 2024-05-17 16:16
I've used the commit you mentioned in previous comments. Thank you!

**Comment by fangjunzhou** [comment] 2024-07-04 01:14
Just want to check some updates. Is this issue solved in 24.05?

**Comment by reckenrode** [comment] 2024-07-04 01:55
> Just want to check some updates. Is this issue solved in 24.05?

It would be a breaking change, so it’d have to target unstable/24.11.

**Comment by reckenrode** [comment] 2024-07-08 11:54
I resubmitted the lldb fix as https://github.com/NixOS/nixpkgs/pull/325525.

**Closed** 2024-07-10 13:59 UTC
Labels: 0.kind: bug, 6.topic: llvm/clang

**Comment by antoineco** [comment] 2025-01-17 11:36
@n8henrie sorry for hijacking an old issue. In https://github.com/NixOS/nixpkgs/issues/252838#issuecomment-2094691733 you claimed that `rust-lldb` was now usable for you without setting `LLDB_DEBUGSERVER_PATH`. I was unable to verify that on the current nixpkgs `master`:

```console
$ /nix/store/301m432ckbfx8k8gdrqqsgzyk6paz6vq-lldb-19.1.5/bin/lldb -o 'break set --name myproject::main' -o 'run' target/debug/myproject
(lldb) target create "target/debug/myproject"
Current executable set to '/myproject/target/debug/myproject' (arm64).
(lldb) break set --name myproject::main
Breakpoint 1: where = myproject`myproject::main::he863cced47d5bd93 + 20 at main.rs:8:9, address = 0x00000001000066ec
(lldb) run
error: unable to locate debugserver
(lldb)
```

This can be solved by exporting `LLDB_DEBUGSERVER_PATH` on my side:
```sh
export LLDB_DEBUGSERVER_PATH=/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Resources/debugserver
```

However, I was under the impression that #325525 has addressed that issue already.

**Comment by fangjunzhou** [comment] 2025-01-17 21:30
@antoineco I was trying to use lldb yesterday and I've also came into the same problem. More strangely, I was using this reverted commit previously: https://github.com/NixOS/nixpkgs/pull/309165 for my nixvim dap, and it also stopped working. The last time I use it was a couple month ago. I'm not sure how this could happen as the nix configuration is declarative. I suspect the lldb artifact being used to build nix lldb is changed somehow? Or it could also be a compatibility issue with the new MacOS system as I've upgraded my system several times during this period.

@reckenrode I aslo want to double check if it's still working on your side.

**Comment by n8henrie** [comment] 2025-01-17 21:42
Hmm, working fine here.

Wonder if I configured something somewhere that I've forgotten about?

```console
$ env | grep -i lldb
$
$ cat src/main.rs 
fn a_function() -> u8 {
    println!("hello from a function");
    7
}

fn main() {
    println!("{}", a_function());
    println!("Hello, world!");
}
$ nix run nixpkgs#lldb -- -o 'break set --name foo::a_function' -o 'run' target/debug/foo
(lldb) target create "target/debug/foo"
Current executable set to '/var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/tmp.Sls9iz9wTS/foo/target/debug/foo' (arm64).
(lldb) break set --name foo::a_function
Breakpoint 1: where = foo`foo::a_function::h76f9beefe262acae + 20 at main.rs:2:5, address = 0x0000000100000a88
(lldb) run
Process 54001 launched: '/var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/tmp.Sls9iz9wTS/foo/target/debug/foo' (arm64)
Process 54001 stopped
* thread #1, name = 'main', queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x0000000100000a88 foo`foo::a_function::h76f9beefe262acae at main.rs:2:5
   1   	fn a_function() -> u8 {
-> 2   	    println!("hello from a function");
   3   	    7
   4   	}
   5   	
   6   	fn main() {
   7   	    println!("{}", a_function());
(lldb) 
```

**Comment by fangjunzhou** [comment] 2025-01-17 22:31
I still got `unable to locate debugserver`

```bash
$ env | grep -i lldb                                                       
$ nix run nixpkgs#lldb -- -o 'break set --name main' -o 'run' build/drawsvg
(lldb) target create "build/drawsvg"
Current executable set to '/Users/fangjun/Documents/stanford/cs248a/cs248a-draw-svg/build/drawsvg' (arm64).
(lldb) break set --name main
Breakpoint 1: 53 locations.
(lldb) run
error: unable to locate debugserver
(lldb) q
```

@n8henrie Which version of MacOS are you using? I suspect it's related to the new system. I saw some posts online saying you are suppose to use `debugserver` instead of `lldb-server` on Darwin system. But lldb on nix only ship with `lldb-server`. Maybe `lldb-server` stopped working on the new system? Not sure if that's related.

```bash
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.2.0, macOS 15.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/Users/fangjun/.nix-defexpr/channels/nixpkgs`
```

**Comment by n8henrie** [comment] 2025-01-17 22:44
```
$ nix-info -m
 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.2.0, macOS 15.2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.11`
 - channels(n8henrie): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/qxk1ib3k5sn1k0k4vvbmdkjy3zdxqz7n-source`

$ sw_vers
ProductName:            macOS
ProductVersion:         15.2
BuildVersion:           24C101
```

**Comment by fangjunzhou** [comment] 2025-01-18 04:34
I finally figured it out!! I've reinstalled my MacOS a few months ago and I haven't installed Xcode after that. I also haven't debug using lldb over the past few month so I didn't notice any issue. When I need to use lldb yesterday, I assume lldb works just fine on nix-darwin, however, it seems that it requires `debugserver` instead of `lldb-server` on MacOS. And as mentioned in https://github.com/NixOS/nixpkgs/issues/252838#issuecomment-2094930192, `LLDB_DEBUGSERVER_PATH` should be set to Xcode lldb `debugserver` by default.

But there's a catch, I thought `debugserver` will be installed with Xcode CLI tools as the lldb shipped with MacOS works just fine. I thought it'll also use some `debugserver` in the CLI tools. But for some reason, the `/usr/bin/lldb` doesn't use `debugserver` at all. So you have to install Xcode from App Store. After open Xcode for the first time, the default `LLDB_DEBUGSERVER_PATH` will be setup, and `lldb` on nix will use that.

So at this point lldb is still using the `debugserver` ship with Xcode. That's how my dap works a few month ago. I think ideally we should set `LLDB_DEBUGSERVER_PATH` to the `debugserver` in nixpkg similar to the environment setup in this post:
https://discourse.nixos.org/t/integrating-vadimcn-codelldb-with-neovim-on-nixos-python-module-error/56639. This will make the environment more reproducible as it won't depend on the external Xcode environment.

**Comment by fangjunzhou** [comment] 2025-01-18 05:41
New issue: the default `$DEVELOPER_DIR` will be overridden by nix dev shell.
```bash
(base) ~/Documents/temp/lldb-env xcode-select -p
/Applications/Xcode.app/Contents/Developer
(base) ~/Documents/temp/lldb-env nix develop 
bash-5.2$ xcode-select -p
/nix/store/a6zrdpm5nmfz3y1f7pa8ka8w2r0cw4hc-apple-sdk-11.3
bash-5.2$ 
```
This will make `debugserver` under `/Applications/Xcode.app/Contents/Developer` no longer available. So setting `LLDB_DEBUGSERVER_PATH` manually is still the only way to get `lldb` working in a nix dev shell. I'm not sure if we should open a new issue to ask nix `lldb` maintainer to ship with `debugserver` for Darwin support.

**Comment by antoineco** [comment] 2025-01-18 08:25
@fangjunzhou two things intrigued me in your previous message: 

> After open Xcode for the first time, the default `LLDB_DEBUGSERVER_PATH` will be setup, and lldb on nix will use that.

What you mean by that? Where is the environment variable supposed to be _set_ after Xcode was opened for the first time?

Right now, `/usr/bin/lldb` fails on my system with an error along the lines of "missing 'lldb' tool".

I'm going to check what `xcode-select` does, thanks for the reference!

> I think ideally we should set `LLDB_DEBUGSERVER_PATH` to the `debugserver` in nixpkg

I suppose you are referring to the `xcode` nixpkgs package itself here? If so, setting that as the default could be complicated since nixpkgs exposes multiple versions of Xcode (`xcode_16_1`, etc.). But maybe this could be configured using an override.

**Comment by reckenrode** [comment] 2025-01-18 13:43
Adding Xcode as a dependency to LLDB would prevent it from building in Hydra. It’s generally not a good idea to depend on `darwin.xcode` in nixpkgs. Fortunately, the [CodeLLDB][1] extension for VS Code ships a copy of `debugserver` that can be fetched and used without needing an Xcode installation. I’m working on a PR to add it as a package and add it to the `lldb` wrapper.

[1]: https://github.com/vadimcn/codelldb

**Comment by reckenrode** [comment] 2025-01-18 16:45
Here is the PR to extract `debugserver` from CodeLLDB and use it with `lldb` in nixpkgs.

https://github.com/NixOS/nixpkgs/pull/374846
