### ISSUE TITLE
Package request: inkscape-extensions.inkstich

### ISSUE THREAD

**Issue by felbinger** [NixOS/nixpkgs#360885] opened 2024-12-01 21:50 UTC
## Project description

Ink/Stitch: an Inkscape extension for machine embroidery design 

## Metadata

* homepage URL: https://inkstitch.org/
* source URL: https://github.com/inkstitch/inkstitch/
* license: gpl3
* platforms: unix, linux, darwin

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pluiedev** [comment] 2024-12-02 11:54
Duplicate of #133180, PR at #358993

**Closed by pluiedev** 2024-12-02 11:54 UTC
Labels: 6.topic: python, 0.kind: packaging request
