### ISSUE TITLE
MongoDB: Non Gsettings schemas are installed

### ISSUE THREAD

**Issue by Ciflire** [NixOS/nixpkgs#285819] opened 2024-02-02 15:17 UTC
### Describe the bug
The application is crashing when trying to open a file

### Steps To Reproduce
1. Try to create a connection
2. In TLS/SSL Open a file
3. The application crashes

### Expected behavior
Supposed to open a file exploer

### Screenshots
```
(mongodb-compass:12752): GLib-GIO-ERROR **: 16:11:39.456: No GSettings schemas are installed on the system
[1]    12752 trace trap (core dumped)  mongodb-compass
```

### Additional context
Using KDE Plasma 5 under wayland

### Notify maintainers

@bryanasdev000 
@r-ryantm 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.2, NixOS, 24.05 (Uakari), 24.05pre577948.97b17f32362e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos, nixpkgs"`
 - channels(ciflire): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by eclairevoyant** [comment] 2024-02-02 22:01
Doesn't build as is, needs some GCC 13 fixes and so on

**Comment by eclairevoyant** [comment] 2024-02-03 01:48
Dupe of #146407

**Closed by eclairevoyant** 2024-02-03 01:48 UTC
Labels: 0.kind: bug
