### ISSUE TITLE
torchvision: Does not use the same compiler as torch when building with CUDA

### ISSUE THREAD

**Issue by ConnorBaker** [NixOS/nixpkgs#217913] opened 2023-02-23 21:46 UTC
### Describe the bug

Unlike `torch`, `torchvision` does not explicitly set the C/C++ compiler when building with CUDA. This is problematic because we can end up linking libraries built by different versions of the compiler built with different language standards. Additionally, we can potentially end up using a compiler which isn't supported by the version of NVCC being used.

`torch` does this in the `preConfigure` phase:

https://github.com/NixOS/nixpkgs/blob/e5bde651a57cb4e136797d794acf33fce4110eea/pkgs/development/python-modules/torch/default.nix#L148-L151

`torchvision` can do it in the same place or in `preBuild`:

https://github.com/NixOS/nixpkgs/blob/e5bde651a57cb4e136797d794acf33fce4110eea/pkgs/development/python-modules/torchvision/default.nix#L47-L50

### Notify maintainers

@ericsagnes

cc @NixOS/cuda-maintainers

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.12-200.fc37.x86_64, Fedora Linux, 37 (Workstation Edition), nobuild`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.14.0pre20230208_ec78896`
 - channels(connorbaker): `"nixpkgs"`
 - nixpkgs: `/home/connorbaker/.nix-defexpr/channels/nixpkgs`
```

**Comment by ConnorBaker** [comment] 2023-02-24 16:29
Would be closed by https://github.com/NixOS/nixpkgs/pull/218035

**Comment by SomeoneSerge** [comment] 2023-02-25 14:48
Duplicate of: https://github.com/NixOS/nixpkgs/issues/217878

**Closed** 2023-03-08 01:15 UTC
Labels: 0.kind: bug, 6.topic: python, 6.topic: cuda
