### ISSUE TITLE
Build failure: prl-tools for Parallels 20 upon upgrade attempt from NixOS 24.05 to 24.11

### ISSUE THREAD

**Issue by gmarler** [NixOS/nixpkgs#364391] opened 2024-12-11 23:43 UTC
## Steps To Reproduce

1. Attempt an upgrade from NixOS 24.05 to 24.11 on a MacBook M2 Pro under Parallels 20.
2. This NixOS config is configured by a flake (after months of successful updates on 24.05), and the upgrade to 24.11 fails on only the prl-tools package, with compile errors indicating possible incompatibility

## Build log

<details>

<summary>Build Log</summary>

```
$ sudo nixos-rebuild test --upgrade  --flake ".#vm-aarch64-prl"
warning: Git tree '/home/gmarler/gitwork/nixos-config' is dirty
building the system configuration...
warning: Git tree '/home/gmarler/gitwork/nixos-config' is dirty
evaluation warning: _1password has been renamed to _1password-cli to better follow upstream name usage
evaluation warning: i18n.inputMethod.enabled will be removed in a future release. Please use .type, and .enable = true instead
error: builder for '/nix/store/69lva8lf1brcras72nvclvsa0i9zpds4-prl-tools-20.1.2-55742.drv' failed with exit code 2;
       last 25 log lines:
       > /build/prl-tools-build/kmods/prl_fs/SharedFolders/Guest/Linux/prl_fs/inode.c: At top level:
       > /build/prl-tools-build/kmods/prl_fs/SharedFolders/Guest/Linux/prl_fs/inode.c:819:5: warning: no previous prototype for 'prlfs_readpage' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wmissing-prototypes-Wmissing-prototypes8;;]
       >   819 | int prlfs_readpage(struct file *file, struct page *page) {
       >       |     ^~~~~~~~~~~~~~
       > /build/prl-tools-build/kmods/prl_fs/SharedFolders/Guest/Linux/prl_fs/inode.c:856:5: warning: no previous prototype for 'prlfs_writepage' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wmissing-prototypes-Wmissing-prototypes8;;]
       >   856 | int prlfs_writepage(struct page *page, struct writeback_control *wbc) {
       >       |     ^~~~~~~~~~~~~~~
       > /build/prl-tools-build/kmods/prl_fs/SharedFolders/Guest/Linux/prl_fs/inode.c: In function 'prlfs_writepage':
       > /build/prl-tools-build/kmods/prl_fs/SharedFolders/Guest/Linux/prl_fs/inode.c:875:17: error: implicit declaration of function 'SetPageError'; did you mean 'SetPageDirty'? [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-function-declaration-Werror=implicit-function-declaration8;;]
       >   875 |                 SetPageError(page);
       >       |                 ^~~~~~~~~~~~
       >       |                 SetPageDirty
       > /build/prl-tools-build/kmods/prl_fs/SharedFolders/Guest/Linux/prl_fs/inode.c: At top level:
       > /build/prl-tools-build/kmods/prl_fs/SharedFolders/Guest/Linux/prl_fs/inode.c:930:27: error: initialization of 'int (*)(struct file *, struct address_space *, loff_t,  unsigned int,  unsigned int,  struct folio *, void *)' {aka 'int (*)(struct file *, struct address_space *, long long int,  unsigned int,  unsigned int,  struct folio *, void *)'} from incompatible pointer type 'int (*)(struct file *, struct address_space *, loff_t,  unsigned int,  unsigned int,  struct page *, void *)' {aka 'int (*)(struct file *, struct address_space *, long long int,  unsigned int,  unsigned int,  struct page *, void *)'} [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wincompatible-pointer-types-Werror=incompatible-pointer-types8;;]
       >   930 |         .write_end      = prlfs_write_end,
       >       |                           ^~~~~~~~~~~~~~~
       > /build/prl-tools-build/kmods/prl_fs/SharedFolders/Guest/Linux/prl_fs/inode.c:930:27: note: (near initialization for 'prlfs_aops.write_end')
       > cc1: some warnings being treated as errors
       > make[4]: *** [/nix/store/6ww3zbbnsqg1v3wx9qsf1lnva2szj1d5-linux-6.12.3-dev/lib/modules/6.12.3/source/scripts/Makefile.build:229: /build/prl-tools-build/kmods/prl_fs/SharedFolders/Guest/Linux/prl_fs/inode.o] Error 1
       > make[3]: *** [/nix/store/6ww3zbbnsqg1v3wx9qsf1lnva2szj1d5-linux-6.12.3-dev/lib/modules/6.12.3/source/Makefile:1936: /build/prl-tools-build/kmods/prl_fs/SharedFolders/Guest/Linux/prl_fs] Error 2
       > make[2]: *** [/nix/store/6ww3zbbnsqg1v3wx9qsf1lnva2szj1d5-linux-6.12.3-dev/lib/modules/6.12.3/source/Makefile:224: __sub-make] Error 2
       > make[2]: Leaving directory '/nix/store/6ww3zbbnsqg1v3wx9qsf1lnva2szj1d5-linux-6.12.3-dev/lib/modules/6.12.3/build'
       > make[1]: *** [Makefile:36: all] Error 2
       > make[1]: Leaving directory '/build/prl-tools-build/kmods/prl_fs/SharedFolders/Guest/Linux/prl_fs'
       > make: *** [Makefile.kmods:70: compile] Error 2
       For full logs, run 'nix log /nix/store/69lva8lf1brcras72nvclvsa0i9zpds4-prl-tools-20.1.2-55742.drv'.
error: 1 dependencies of derivation '/nix/store/chydi09g2j42gk40cfvg5ca2pv57qszm-hwdb.bin.drv' failed to build
error: 1 dependencies of derivation '/nix/store/w9y21gv9y5vwf5icpfwn83szml2pshly-linux-6.12.3-modules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/4lhm39l1wk7fazakwjzir5jbrcjvi9gj-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qmmxn4mv1n6y9hn0zsirxcw9j3a6hcl5-udev-rules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/12djlm4zwcshclhgldrk3vfz4j0k9azb-unit-prlcc.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ayp63viimh4w5rfb3vzpl0hzamwdzhlf-unit-prlcp.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/n9aglmknz3pxjiz08vvm011n75rxjx7j-unit-prldnd.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/978082ik8fdcpzn0wdfh1whgxpg7qbjg-unit-prlsga.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/y48i3lsz2ahfvf92s7bjhqwpqbkb38b4-unit-prlshprint.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/pwwa9gapq1jyvdzdmgg18p101cn5c1xw-unit-prlshprof.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vcn9269wpnahy9yc9lzm0ng7s16d7ys5-unit-prltoolsd.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1k0hvfcbnq4d25ixdyf06dmab76sn6dy-nixos-system-greenbirch-24.11.20241210.a0f3e10.drv' failed to build
```

</details>

## Additional context

The flake only specifies the following input config to install the default prl-tools:

```
hardware.parallels.enable = true;
```

## Metadata

$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.11.0, NixOS, 24.05 (Uakari), 24.05.20240916.086b448`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.6`
 - nixpkgs: `/nix/store/qkzr5clkyq7j6n43qs5ff73in6c3wacv-source`

## Notify maintainers

@wegank  @codgician 
---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by codgician** [comment] 2024-12-12 04:16
Duplicate of #357917

The latest prl-tools does not support kernel version 6.11+, and requires an upstream fix from Parallels.

Or you could apply a custom patch, refering: https://github.com/NixOS/nixpkgs/pull/360709#issuecomment-2511643874

**Comment by gmarler** [comment] 2024-12-12 15:10
Thanks so much!

Trying to specify a slightly earlier LTS kernel for 24.11 as a first attempted workaround in my NixOS flake.

Will then try the patch variant of a solution until the official prl-tools is updated to support Linux 6.12.

**Comment by gmarler** [comment] 2024-12-12 16:08
I was able to get an upgrade to NixOS 24.11 with a working default prl-tools for Parallels 20 by locking the Linux kernel to the last LTS kernel (6.6) via this snippet:

```
boot.kernelPackages = pkgs.linuxPackages_6_6;
```

**Closed** 2024-12-13 02:41 UTC
Labels: 2.status: duplicate, 9.needs: upstream fix, 0.kind: build failure
