### ISSUE TITLE
Package request: Actual Budget

### ISSUE THREAD

**Issue by KCynk** [NixOS/nixpkgs#346655] opened 2024-10-05 12:12 UTC
**Actual Budget is a super fast and privacy-focused app for managing your finances**

* homepage URL: https://actualbudget.org/
* source URL: https://github.com/actualbudget/actual
* license:  MIT license 
* platforms: linux

**Comment by Gaelan** [comment] 2024-10-08 23:40
I think this is a duplicate of https://github.com/NixOS/nixpkgs/issues/269069 ?

**Comment by oddlama** [comment] 2024-10-09 00:26
Yes, this is a duplicate. Closing in favor of the existing issue

**Closed by oddlama** 2024-10-09 00:26 UTC
Labels: 6.topic: nodejs, 0.kind: packaging request
