### ISSUE TITLE
NormCap

### ISSUE THREAD

**Issue by igorlogius** [NixOS/nixpkgs#189702] opened 2022-09-04 09:32 UTC
**Project description**

OCR powered screen-capture tool to capture information instead of images 

**Metadata**

* homepage URL: https://github.com/dynobo/normcap
* source URL: https://github.com/dynobo/normcap
* license: https://github.com/dynobo/normcap/blob/main/LICENSE  (GPL) 
* platforms: linux, windows, macOS

**Comment by pinn3** [comment] 2022-09-04 11:50
Duplicate of https://github.com/NixOS/nixpkgs/issues/166228

**Comment by cafkafk** [comment] 2022-09-04 12:19
As pinn3 noticed, duplicate of #166228, closing

**Closed by cafkafk** 2022-09-04 12:19 UTC
Labels: 2.status: duplicate, 0.kind: packaging request
