### ISSUE TITLE
Building of nvidia driver fails with 'drm/drmP.h: No such file'

### ISSUE THREAD

**Issue by jakubgs** [NixOS/nixpkgs#79189] opened 2020-02-03 23:06 UTC
**Describe the bug**
The `nvidia` driver fails to build with the following error:
```
In file included from /build/kernel/nvidia-drm/nvidia-drm-drv.c:27:
/build/kernel/nvidia-drm/nvidia-drm-fb.h:30:10: fatal error: drm/drmP.h: No such file or directory
   30 | #include <drm/drmP.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```
Full Log: https://gist.github.com/jakubgs/dde8ad4031d7fad997a39a9bafb8f96e

**To Reproduce**
1. Use https://nixos.org/channels/nixpkgs-unstable
2. Try to build with `services.xserver.videoDrivers = [ "nvidia" ];`
3. See the failure due to `drm/drmP.h: No such file`

**Expected behavior**
It builds.

**Additional context**

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.15, NixOS, 20.03pre210639.e59dcf8ccec (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03pre211190.a21c2fa3ea2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
nvidia-x11
services.xserver
```

**Comment by jakubgs** [comment] 2020-02-03 23:10
I tried removing the `unstable` channel from `nix-channels` and rebuild but it seems to build exactly the same version of `nvidia-x11`, which is `440.44-5.5`. Maybe I'm missing something.

**Comment by eadwu** [comment] 2020-02-04 01:21
Expected if you're using NVIDIA's driver, not sure if it'll fix it but I'll put up a PR for `440.59`, though if it doesn't work, downgrade the kernel.

**Comment by veprbl** [comment] 2020-02-04 04:14
Should be now fixed

**Closed by veprbl** 2020-02-04 04:14 UTC
Labels: 0.kind: bug

**Comment by jakubgs** [comment] 2020-02-04 09:18
What do you mean by:

>Expected if you're using NVIDIA's driver

How is that expected? And is there a way for me to pin Nvidia to a working version in case this happens again?

**Comment by jakubgs** [comment] 2020-02-04 10:03
Also, I assume I have to wait for the changes to make their way from `master` branch to [`nixos-unstable`](https://github.com/NixOS/nixpkgs/commits/nixos-unstable) branch, correct? I'm new to this.

**Comment by veprbl** [comment] 2020-02-04 16:58
> Also, I assume I have to wait for the changes to make their way from `master` branch to [`nixos-unstable`](https://github.com/NixOS/nixpkgs/commits/nixos-unstable) branch, correct? I'm new to this.

Yes, if you use the channels, you need to wait for it to update. I think, this shouldn't take more than a day.

**Comment by jakubgs** [comment] 2020-02-04 17:11
Am I correct in assuming that what I want to see is `nixos-unstable` having its `Last Modified` changed here: https://nixos.org/channels/

Also, thanks for the quick fix, appreciate it. I tried downgrading by removing the channel but it just kept using the same version of Nvidia driver. I guess downgrading isn't a thing.

**Comment by veprbl** [comment] 2020-02-04 17:23
> Am I correct in assuming that what I want to see is `nixos-unstable` having its `Last Modified` changed here: https://nixos.org/channels/

See some useful links in the bottom of https://nixos.wiki/wiki/Nix_channels
Looking at hydra now, I see that the version of nixpkgs with the bugfix has not started evaluating yet.
 
> Also, thanks for the quick fix, appreciate it. I tried downgrading by removing the channel but it just kept using the same version of Nvidia driver. I guess downgrading isn't a thing.

I believe, the problem is not with the version of the nvidia driver but with the kernel version being too new for it.
