### ISSUE TITLE
gcc cross-compiles from i686 don't support LTO? (efibootmgr fails to cross-compile from i686)

### ISSUE THREAD

**Issue by dwf** [NixOS/nixpkgs#143901] opened 2021-10-30 20:59 UTC
### Describe the bug

efibootmgr fails to compile from i686 to armv6l (raspberryPi), because `stdenv.isi686` is false and `-flto` is passed in CFLAGS, however the gcc cross-compiler doesn't support the flag.

### Steps To Reproduce

1. From x86-64 Linux, `nix-build -A pkgsi686Linux.pkgsCross.raspberryPi.efibootmgr '<nixpkgs>'`

### Expected behavior
The build to complete successfully.

### Additional context
Changing the efibootmgr derivation to use `stdenv.buildPlatform.isi686` instead of `stdenv.isi686` fixes the build but I'm not sure this is the right fix. It seems that the derivation is perhaps right, and gcc should support LTO on i686 for non-i686 target platforms. Perhaps the references in the gcc sections of pkgs/top-level/all-packages.nix should read `enableLTO = !stdenv.hostPlatform.isi686`?

### Notify maintainers

efibootmgr doesn't have any maintainers listed and I _think_ the actual problem relates to gcc.

@vcunat 
@Synthetica9 
@Ericson2314 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[nix-shell:~]# nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/p5lnl4zr45n7mf9kz9w8yz3rqh001b5c-bash-interactive-4.4-p23-dev
copying path '/nix/store/p5lnl4zr45n7mf9kz9w8yz3rqh001b5c-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.74, NixOS, 21.05.3892.70904d4a992 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.05.3892.70904d4a992, unstable-21.11pre323695.9aeeb7574fb"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by r-burns** [comment] 2021-10-30 21:48
It looks like LTO availability depends on this setting:

https://github.com/NixOS/nixpkgs/blob/86661be08742ffe5270395d3938e0b3a68a68e96/pkgs/top-level/all-packages.nix#L11691-L11697

So immediately I have a few thoughts:

* We should consolidate these definitions and make them available via e.g. gcc.passthru so that packages can check whether they are allowed to use LTO in a non ad-hoc way
* Your buildPlatform modification appears to be correct, as the enableLTO setting depends on gcc's hostPlatform rather than its targetPlatform

**Comment by dwf** [comment] 2021-10-30 22:52
> Your buildPlatform modification appears to be correct, as the enableLTO setting depends on gcc's hostPlatform rather than its targetPlatform

I agree that that's the effect, but is that the intent? Is LTO a problem on i686 hosts or i686 targets, or both? It looks like this was first introduced in 22284b07 by @vcunat who might have some additional context for the change.

**Comment by r-burns** [comment] 2021-10-30 22:57
Good point, usually settings like that affect the target platform. It's possible this was only tested for the native case, so it's a good idea to verify the platform predicate is correct.

**Comment by vcunat** [comment] 2021-10-31 11:26
It was reaction to non-cross problems during bootstrapping.  It's well possible that they won't appear when not bootstrapping (e.g. any cross).  Confirming that gcc builds should be enough for the problems from my commit.

**Comment by dwf** [comment] 2021-11-01 13:36
I see. It sounds like _maybe_ switching on `stdenv.targetPlatform.isi686` is more appropriate, then.

I'm a bit new to Nix, is there a way to force a build from scratch rather than a fetch from cache? The docs are failing me here.

**Comment by Synthetica9** [comment] 2021-11-01 13:52
I think you want `nix-build --check`

**Comment by r-burns** [comment] 2021-11-05 23:03
Linking likely related https://github.com/NixOS/nixpkgs/pull/144778 so I don't forget to look into it along with this

**Comment by thiagokokada** [comment] 2021-11-05 23:05
> Linking likely related #144778 so I don't forget to look into it along with this

Sorry, maybe I merged it too soon :sweat_smile: ?

**Comment by r-burns** [comment] 2021-11-05 23:07
No no worries, I didn't link it there because I don't think the supportsLTO ~ isi686 cleanup is your responsibility. There are probably other locations as well I'll need to look into.

**Comment by r-burns** [comment] 2021-11-06 01:51
Hmm, so I was thinking I'd figure out the right host/target platform distinction for gcc and then expose whether it has LTO with e.g. `stdenv.cc.hasLTO`. But I'm unable to encounter any scenario where LTO doesn't work on i686, so I think we can reenable it fully, and I'll just remove the treewide i686-specific LTO workarounds if that sounds reasonable.

**Comment by r-burns** [comment] 2021-11-06 02:07
Never mind, `efivar` is a reliable reproducer:

```
gcc -O2 -flto -g3 -I/build/source/src/include/   -specs=/build/source/gcc.specs  -L.   -Wl,-z,muldefs      -shared \
  -Wl,-soname,libefivar.so.1 \
  -Wl,--version-script=libefivar.map \
  -o libefivar.so dp.o dp-acpi.o dp-hw.o dp-media.o dp-message.o efivarfs.o error.o export.o guid.o guids.o guid-symbols.o lib.o vars.o -ldl
/build/ccQUJQZh.s: Assembler messages:
/build/ccQUJQZh.s: Error: invalid attempt to declare external version name as default in symbol `efi_set_variable@@LIBEFIVAR_0.24'
lto-wrapper: fatal error: /nix/store/y60g40d6pjz5swkzwgdr8jfxcp9ga4cv-gcc-10.3.0/bin/gcc returned 1 exit status
compilation terminated.
/nix/store/1pza4mwv1i91cda2p0g5qvbj053m9a75-binutils-2.35.2/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[1]: *** [/build/source/Make.rules:20: libefivar.so] Error 1
make[1]: Leaving directory '/build/source/src'
make: *** [Makefile:14: all] Error 2
builder for '/nix/store/7sli8z0swlcaib4cc1s7jszz3z45pdky-efivar-37.drv' failed with exit code 2
```

Going to go ahead with the `stdenv.cc.hasLTO` strategy, happy to discuss alternatives here or in the upcoming PR.

**Closed** 2021-11-08 14:25 UTC
Labels: 0.kind: bug, 6.topic: cross-compilation
