### ISSUE TITLE
Staging merge

### ISSUE THREAD

**Issue by lethalman** [NixOS/nixpkgs#8844] opened 2015-07-15 16:09 UTC
Staging has only about ~4k failures compared to ~7k failures of master. It only has 500 builds left to do. Staging hasn't been touched in a couple of days, and it has a master->staging merge.

What about merging staging into master? Asking for :+1: @domenkozar @vcunat @ttuegel @edolstra @wkennington

**Comment by ttuegel** [comment] 2015-07-15 16:10
:+1:

**Comment by vcunat** [comment] 2015-07-15 18:14
I see ~1.5k new failures in there (Hydra comparison to trunk). There are quite many due to ruby, and perhaps go on darwin (but that feels less important). We can still merge and fixup on master, as the total number of failures decreases sharply, mainly due to haskell stuff :-)

**Comment by wkennington** [comment] 2015-07-15 18:25
Sgtm.

**Comment by vcunat** [comment] 2015-07-15 19:23
Hmm, ruby builds fine for me. Maybe it's been fixed since the last evaluation.

**Comment by domenkozar** [comment] 2015-07-15 21:11
Sure.

**Comment by vcunat** [comment] 2015-07-15 21:53
Don't merge yet, as there are some problems during runtime, e.g. http://sprunge.us/XRJJ (from IRC). Maybe due to 49821433242.

**Comment by wkennington** [comment] 2015-07-15 22:11
Yeah, lightdm was relying on per-package loaders.cache so this change broke
the nixos config. I'm currently testing the following fix.

diff --git a/nixos/modules/services/x11/display-managers/lightdm.nix
b/nixos/modules/services/x11/display-managers/lightdm.nix
index d05edab..bc8f478 100644
--- a/nixos/modules/services/x11/display-managers/lightdm.nix
+++ b/nixos/modules/services/x11/display-managers/lightdm.nix
@@ -33,7 +33,7 @@ let
       makeWrapper ${pkgs.lightdm_gtk_greeter}/sbin/lightdm-gtk-greeter \
         $out/greeter \
         --prefix PATH : "${pkgs.glibc}/bin" \
-        --set GDK_PIXBUF_MODULE_FILE "$(find ${theme} -name
loaders.cache)" \
+        --set GDK_PIXBUF_MODULE_FILE
"${pkgs.gdk_pixbuf}/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache" \
         --set GTK_PATH "${theme}:${pkgs.gtk3}" \
         --set GTK_EXE_PREFIX "${theme}" \
         --set GTK_DATA_PREFIX "${theme}" \

**Comment by vcunat** [comment] 2015-07-15 22:16
Another point is that the latest Hydra evaluation seems not to cover all staging mass-rebuild changes (I had to build quite a lot).

**Comment by wkennington** [comment] 2015-07-15 22:25
Possibly due to 08ef62c1009c27db1c6a5750c80c4af01ee791f2 and 01e37fe92dedabdaa7b9f047de1c59f8a43de45e?

**Comment by lethalman** [comment] 2015-07-15 22:35
Ok so let's wait for the next evaluation without breaking anything.

On Thu, Jul 16, 2015 at 12:25 AM, William A. Kennington III <
notifications@github.com> wrote:

> Possibly due to 08ef62c
> <https://github.com/NixOS/nixpkgs/commit/08ef62c1009c27db1c6a5750c80c4af01ee791f2>
> and 01e37fe
> <https://github.com/NixOS/nixpkgs/commit/01e37fe92dedabdaa7b9f047de1c59f8a43de45e>
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/8844#issuecomment-121766812>.
>



-- 
NixOS Linux <http://nixos.org>

**Comment by wkennington** [comment] 2015-07-15 22:40
Well those changes aren't in staging so it's going to be a mass-ish rebuild once we merge over to master unless we merge those changes into staging.

**Comment by lethalman** [comment] 2015-07-16 08:09
@wkennington staging is mass rebuilding right now.

**Comment by lethalman** [comment] 2015-07-16 08:51
@wkennington and I wonder why setuptools+gnutls didn't go to staging, since it's mass-ish rebuild as you say.

**Comment by lethalman** [comment] 2015-07-16 08:54
Now staging is mass rebuilding, master will mass rebuild, hence the next master->staging merge will mass rebuild. And we will wait another week to merge staging, another more week delayed for the nixos release. So it happened again @wkennington , we talked about this like a couple of days ago.

**Comment by vcunat** [comment] 2015-07-17 04:46
Speaking of release, I'm most worried by the planned systemd update #6671 where I still see no activity to finish/merge it.

**Comment by lethalman** [comment] 2015-07-17 12:20
So nixpkgs trunk has 2k more failures (9k total), and it has 6k in queue currently. Staging 2.5k with 5k in queue, it still hasn't evaluated the master->staging merge of @vcunat . But because gnutls+setuptools+samba triggered 6k builds on master, I believe it would be quite the same on staging. 

Do we want to wait for staging to finish? Because I think we're in good shape now to merge regardless.

@vcunat just for info, setuptools is also quite mass rebuild because qt depends on python ecc..

**Comment by peti** [comment] 2015-07-17 12:32
Please don't merge staging until there are binaries for (the majority of) the state of Nixpkgs *after* the merge. If master contains mass-rebuild changes that aren't in staging yet, then I'd prefer to merge those into staging first and wait until it's been built.

Alternatively, I think it's also quite appropriate the revert the mass-rebuild changes from master and to merge staging now.

**Comment by lethalman** [comment] 2015-07-17 12:44
@peti hydra is already building 6k builds for master and 6k for staging, and I think most of those could be shared, that's why I thought it could be merged.

**Comment by peti** [comment] 2015-07-17 12:57
If those builds can be shared indeed, then merging master into staging one more time before the re-integration ought to be really quick, i.e. the new staging evaluation should add almost no new build jobs.

**Comment by ttuegel** [comment] 2015-07-17 16:07
> Speaking of release, I'm most worried by the planned systemd update #6671 where I still see no activity to finish/merge it.

It's obviously not that important or someone would have stepped up to get it merged one of the last two times the stable release was delayed. At this point, it won't be merged (much less stable) in time. Please don't delay release again for this!

**Comment by peti** [comment] 2015-07-17 16:28
> It's obviously not that important or someone would have stepped up to get it merged one of the last two times the stable release was delayed. At this point, it won't be merged (much less stable) in time. Please don't delay release again for this!

I completely agree. The release-15.07 effort desperately needs some kind of result soon'ish. If that release doesn't come out on time again, then I fear that people will just lose faith in our ability to pull it off.

**Comment by domenkozar** [comment] 2015-07-17 19:24
@edolstra do you plan to work on systemd merge next week? Otherwise I'd release 15.07 without systemd bump.

**Comment by vcunat** [comment] 2015-07-19 06:23
Pushed. Hydra shows a few thousand less failures and it's just finishing the last several builds; I'm running atop staging fine for almost a day. However, there are some nontrivial regressions shown:

- I can't reproduce the gnome3 problems &ndash; maybe they're some parallel-make problem, but the "identifier undeclared" message doesn't seem typical for those http://hydra.nixos.org/build/23764728
- I can reproduce libreOffice not building, but I suspect it's some simple not-really-a-problem that used to be hidden by #7524 /cc maintainers @viric, @7c6f434c.
- I can reproduce qt5 (base) not building. It errors on some missing postgre symbols during linking. It's a bit suspicious to me that it also reports missing *both* alsa and pulseaudio, though that doesn't make it stop and maybe that's normal in the *base* module. /cc @ttuegel.

**Comment by vcunat** [comment] 2015-07-19 09:40
OMG, the master+staging merge introduced another mass hash-change w.r.t. staging :-/

**Comment by vcunat** [comment] 2015-07-19 10:16
No, it's more that Hydra.nixos.org seems to behave suboptimally and confusingly. Details: https://github.com/NixOS/hydra/issues/190#issuecomment-122644897

**Comment by ttuegel** [comment] 2015-07-19 14:16
Something is strange about that Qt/Postgre build failure. Qt is built with Postgre support disabled. Also, the failure does not appear on `i686-linux`. That ALSA and PulseAudio are missing is normal for that module.

**Comment by vcunat** [comment] 2015-07-19 16:09
That Qt5 thing is really strange. I bisected it: I can reproduce the error on d253b3d875d and not on the parent commit (I tried several times), but the only difference is a coreutils test! Note that on the parent I did succeed multiple times, but I was getting different hashes of the output.

**Comment by ttuegel** [comment] 2015-07-19 16:12
@vcunat On the successful Qt builds, is the file `libqsqlpsql.so` part of the output? In other words, do the successful builds link against Postgre? Or, do the successful builds (correctly) disable Postgre support?

**Comment by vcunat** [comment] 2015-07-19 17:04
Yes, it's in there on the parent above.
```-r-xr-xr-x 1 root root 83984 Jan  1  1970 ./result/lib/qt5/plugins/sqldrivers/libqsqlpsql.so```

**Comment by ttuegel** [comment] 2015-07-19 17:53
Ah, my mistake. We do indeed build Qt with Postgre support by default, so that is correct. I will have to look further.

**Comment by ttuegel** [comment] 2015-07-20 12:31
@vcunat It's the hash! d253b3d changes the hash of some Qt dependency. During configure, Qt determines the link flags for Postgre like this:
```
unix|mingw {
    LIBS += $$QT_LFLAGS_PSQL
    !contains(LIBS, .*pq.*):LIBS += -lpq
    QMAKE_CXXFLAGS *= $$QT_CFLAGS_PSQL
} else {
    !contains(LIBS, .*pq.*):LIBS += -llibpq -lws2_32 -ladvapi32
}
```
That's right; Qt adds `-lpq` to the link flags _unless_ they already contain the string `pq`. This was destined to fail at random when the hash of some dependency changed to include `pq`. The solution is to manually override this flag selection. A patch for that (plus some other potential problems I found) is on its way.

**Comment by domenkozar** [comment] 2015-07-20 12:44
:beers:

**Comment by edolstra** [comment] 2015-07-20 12:50
We've run into this before: http://permalink.gmane.org/gmane.linux.distributions.nixos/14106

**Comment by ttuegel** [comment] 2015-07-20 13:51
@edolstra Oh, I must have missed that. Well, it won't happen again; as of 17a65c4bf043aaa35b6224a27a3d0a9df546ca85, the link flags are overridden so that the bad heuristic above is never used.

**Comment by vcunat** [comment] 2015-07-20 20:01
This whole issue has been addressed, I believe.

**Closed by vcunat** 2015-07-20 20:01 UTC
