### ISSUE TITLE
virt-manager error start

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#57085] opened 2019-03-08 19:54 UTC
## Issue description
Error start virt-manager

```
Traceback (most recent call last):
  File "/nix/store/wx0xkbhc00zh12ydyncq4jvyw9rhhg09-virt-manager-2.1.0/share/virt-manager/virt-manager", line 17, in <module>
    gi.require_version('LibvirtGLib', '1.0')
  File "/nix/store/kiw47xswi1041sbvbgrlfy0xs0zlwyvk-python3.7-pygobject-3.30.4/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace LibvirtGLib not available

```

### Steps to reproduce
Install virt-manager - nix-env -iA nixos.virtmanager
and run app

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.20.14, NixOS, 19.09pre172235.9fa52ae9a22 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.09pre172235.9fa52ae9a22"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment] 2019-03-09 00:38
Duplicate of https://github.com/NixOS/nixpkgs/issues/56943

**Closed by jtojnar** 2019-03-09 00:38 UTC
