### ISSUE TITLE
Webapp Manager

### ISSUE THREAD

**Issue by vagabondsajib** [NixOS/nixpkgs#217927] opened 2023-02-23 22:54 UTC
**Run websites as if they were apps.**

**Metadata**

* homepage URL: https://github.com/linuxmint/webapp-manager
* source URL: https://github.com/linuxmint/webapp-manager
* license: gpl3
* platforms: linux

**Comment by pinn3** [comment] 2023-02-23 23:14
Duplicate of https://github.com/NixOS/nixpkgs/issues/212089

**Comment by das-g** [comment] 2023-10-24 12:25
Closing as duplicate of #212089.

**Closed by das-g** 2023-10-24 12:25 UTC
Labels: 0.kind: packaging request
