### ISSUE TITLE
Can I replace systemd with OpenRC or runit on NixOS?

### ISSUE THREAD

**Issue by crocket** [NixOS/nixpkgs#24346] opened 2017-03-26 08:44 UTC
I'd like to dive into NixOS right away, but systemd makes me hesitate.
Gentoo comes with OpenRC and presents systemd as **an option**.
To avoid systemd, I could install Nix on Gentoo or Void Linux, but that's not a proven track to me, yet.

I'd like to know whether it doesn't involve too much work for a poor user without a lot of time to replace systemd with OpenRC or runit on NixOS.

**Comment by joachifm** [comment] 2017-03-26 09:00
The short answer is no.

**Comment by crocket** [comment] 2017-03-26 09:17
Do enough people want to replace systemd with another init system in the near future?
The near future means 2~5 years.

**Comment by vcunat** [comment] 2017-03-26 09:20
There's a recent [ML thread](http://lists.science.uu.nl/pipermail/nix-dev/2017-March/023113.html) &ndash;  it *seems* that a group of people wants to take action in that direction.

**Comment by 0xABAB** [comment] 2017-03-26 09:21
The more interesting question is whether a PR adding support for different backends would be accepted, since there are also costs associated with maintaining these additional backends. 

I don't think it's a smart move to expand the scope of the project, since there are a lot of other issues still open. 

@crocket I like some other init systems better than systemd, but at the same time do I see that systemd is good enough.

If an entity wants to commit development resources, then by all means do it. I might even use it, but I don't see init systems as a large differentiator to overall system performance (usability or otherwise).

**Comment by crocket** [comment] 2017-03-26 09:22
@vcunat Yes, I read that. I wanted to know whether a similar sentiment is shared by enough people that replacing systemd with another init system in the near future will be politically possible. It makes sense to make efforts to do something only if it is politically possible.

**Comment by vcunat** [comment] 2017-03-26 09:25
I don't know.  I haven't seen that topic seriously discussed lately, except for that thread.

**Comment by 0xABAB** [comment] 2017-03-26 09:33
@crocket vendor lock-in is only a problem to entitities who do not understand software. Politically, I would like to rip out systemd too, if that was the question. 

It's not as if systemd is obfuscated or completely undocumented. Additionally, I don't believe it's the case that RedHat has a proprietary version of systemd which works a lot better than the open-source version. So, if it's good enough for RedHat's customers, then it's good enough for me.

**Comment by joachifm** [comment] 2017-03-26 10:46
Closing, as I belive the question has been answered, and I feel like the discussion is heading down an all too familiar path ... @crocket you may want to check out guixsd if systemd is a blocker; otherwise I think there's no way around writing some code yourself at this point (see runix, not-os, &c for inspiration).

**Closed by joachifm** 2017-03-26 10:46 UTC
Labels: 0.kind: question

**Comment by 7c6f434c** [comment] 2017-03-26 11:50
In some sense if you learn to use NixOS, migrating to not-OS or whatever spin-off without systemd there will be will be relatively cheap.

The core boot scripts are cheap to write manually, so you don't need that part to be accepted by larger community; the reason you want a larger community is for packages and services — NixPkgs is usable on Linux anyway, and NixOS supports exporting services as systemd-independent runner scripts.

You can look at
https://github.com/7c6f434c/7c6f434c-configurations/blob/master/init-less-system/generic/tools.nix#L373
This is a couple of helper functions I use to build a configuration on my notebook. Some systemd features actively break things I consider basic functionality, so I run some busybox scripts instead of an init system; the code I link allows me to reuse the parts of NixOS that I like without paying the cost of the parts I don't.

What I want to say is: even if you fail to convince people to merge changes into NixOS, the truly unmergeable part will be small and maintainable by a minimal team, and the large politically-neutral part of work can be shared between communities.

**Comment by globin** [comment] 2017-03-26 12:10
I don't think anyone would be really opposed to having a service abstraction layer and that many would welcome it as long as it actually implemented cleanly :)

**Comment by crocket** [comment] 2017-03-26 12:17
> I like some other init systems better than systemd

@0xABAB I'm just curious of which init systems you prefer to systemd.

> even if you fail to convince people to merge changes into NixOS, the truly unmergeable part will be small and maintainable by a minimal team

I just wanted to know whether NixOS will accept replacement of systemd. It seems that the NixOS core team would allow replacement of systemd if a sufficiently large amount of manpower was directed toward it. So, I surmise NixOS will probably replace systemd in the foreseeable future. That's all I wanted to know for now.

**Comment by globin** [comment] 2017-03-26 12:46
I don't think we'd want to *replace* systemd, only abstract our services to a level where we can switch init systems quite easily.

**Comment by 7c6f434c** [comment] 2017-03-26 13:07
@crocket well, there are some such developments anyway, you could look at notOS keeping in mind that taking single services from NixOS is feasible. I think non-systemd NixPkgs-based system is or will be soon feasible for a user with skills in medium-complexity system administration; I expect that doing anything non-standard with NixOS is hard without these skills.

@globin or we can get one more `enableParallelBuild` story… (I hope we won't — maybe we will even fix the `enableParallelBuild` one eventually)

**Comment by crocket** [comment] 2017-03-26 13:27
> skills in medium-complexity system administration
@7c6f434c Can you define this?

**Comment by 7c6f434c** [comment] 2017-03-26 13:37
Always hard to define such things… Well, configuring a Nix-based anything is writing simple scripts in a domain-specific language not used anywhere else, so I guess if you can comfortably use `man bash` as reference (you may still prefer some other source, of course), if «does any log in `/var/log/` mention the config file you want to use» is a thing that you check without thinking too much about «how», such things…

**Comment by crocket** [comment] 2017-03-26 13:47
That's not too difficult. When I said I was not a programmer, I meant I was no longer a programmer. I used to be a web programmer, and I also used to be a hobbyist system administrator who set up a linux router and submitted dozens of packages to AUR and SlackBuilds(Slackware's manual dependency resolution takes too much time!!). I have used linux for almost 7 years.

After changing my career, my work doesn't involve programming or system administration at all, but I still do some programming and maintenance when I need to for system maintenance.

Recently, I also learned to code in Haskell over several months.

If that was your definition of medium-complexity system administration, I would qualify as one. Still, I have obligations to fulfill, and I can no longer justify pouring long uninterrupted blocks of time into system maintenance for more than a few days per month.

**Comment by 7c6f434c** [comment] 2017-03-26 14:06
You definitely have the qualification to use and to meaningfully 
contribute (there are many one-off things requiring an hour or so in all
the Nix* projects…), but I agree it is a good idea for you to check 
carefully which of the similar projects would take less effort for you
to start using.

**Comment by crocket** [comment] 2017-03-26 14:20
Can you recommend a potential approach to obtaining a non-systemd NixPkgs-based system without spending too much time in the near future? I have yet to learn Nix and NixOS, so I may not understand.

**Comment by 7c6f434c** [comment] 2017-03-26 15:51
I should try Not-OS before recommending or not recommending it, I guess…

I would recommend maybe just using Nix-on-random-Linux to get some familiarity first anyway…

If you can quickly write a bootscript (boot/mount/switch_root) for your system, trying something out can be done quickly, but otherwise I'd need to check out the project before recommending anything…

**Comment by crocket** [comment] 2017-03-27 06:28
@7c6f434c https://github.com/cleverca22/not-os says

> An operating system generator, based on NixOS, that, given a config, outputs a small (47 MB), read-only squashfs for a runit-based operating system, with support for iPXE and signed boot.

Thus, it is not for a desktop computer. RedHat is giving us an up-hill battle.

**Comment by 7c6f434c** [comment] 2017-03-27 08:38
Well, maybe if you skip the image → squashfs step… Will look at it at some point.

**Comment by shevegen** [comment] 2017-08-01 02:19
> Thus, it is not for a desktop computer. RedHat is giving us an up-hill battle.

Precisely. They have also been both the major funders and adopters of systemd and other software stack solutions.

It is being increasingly difficult to avoid any of the larger corporations. Building another company/corporations will not change this but lead to similar problems.

I'd wish it were possible to all have distributed computer systems without being tied to any individual company per se. There are some who try to remain independent - slackware, gentoo. Others are following what red hat gives them.

**Comment by crocket** [comment] 2017-08-01 03:14
I moved to gentoo a few months ago. I am grateful for the freedom it gives me.

**Comment by ORESoftware** [comment] 2019-10-04 23:04
An aside - looking for help with systemd on nixos: https://stackoverflow.com/questions/58243712/how-to-install-systemctl-service-on-nixos

**Comment by brandondrew** [comment] 2020-08-18 18:55
> NixPkgs is usable on Linux anyway, and NixOS supports exporting services as systemd-independent runner scripts.

@7c6f434c  So if I understand you, I could use NixPkgs on Slackware without any problem?

**Comment by 7c6f434c** [comment] 2020-08-18 19:13
>> NixPkgs is usable on Linux anyway, and NixOS supports exporting services as systemd-independent runner scripts.
>@7c6f434c  So if I understand you, I could use NixPkgs on Slackware without any problem?

I mean, I have yet to see a large collection of packages that can be used without _any_ problem, and of course there is some amount of NixOS-like assumptions sneaking in (tip: many of these can be mimicked on Slackware without damaging Slackware in any way, just create some strategically placed symlinks), but a lot of packages from Nixpkgs can be used on any x86_64 or aarch64 Linux as-is with the same experience as on NixOS just by straight nix-build or nix-shell.

**Comment by dm17** [comment] 2020-11-01 13:56
> I moved to gentoo a few months ago. I am grateful for freedom and customization options it gives me.

@crocket How do you do reproducibility on it? Darch (godarch.com)? Figure it is OK to ask you since this thread is closed :)

**Comment by crocket** [comment] 2020-11-01 14:02
Gentoo fetches dependencies before building. Building is done in an offline network namespace.
So, you are going to get the same input every time.

**Comment by dm17** [comment] 2020-11-01 14:16
> Gentoo downloads dependencies into cache directory before building. Building is done in an offline network namespace.
> If build process tries to access network, build fails.
> Dependencies are tied to hashes so that they cannot be altered.
> So, you are going to get the same input every time.
> 
> By the way, I recommend artix linux for people who want a simple linux distribution where you don't have to build.
> I may try artix linux with s6 init system because s6 looks interesting.

@crocket 
I mentioned Darch because like NixOS it should allow for easily reproducible installations. I'm not as concerned with builds failing as reproducible installations and making "DevOps" easy. It should also work with Artix and all sorts of distros.

**Comment by appetrosyan** [comment] 2021-06-18 11:28
The issue here is that nixOS uses `systemd` in a non-mission critical manner. Generations ran fine on grub, and `systemd-boot` isn't really `systemd` the PID-0. At the end of https://github.com/bedrocklinux/bedrocklinux-userland/issues/221 there were a few examples of projects that managed to use a nixOS-like system, that didn't depend on systemd. Considering the strengths of `nix` this is likely the best way forward.

**Comment by NarutoXY** [comment] 2021-09-07 17:14
So what is current status? Can we use nixOS without systemd?

**Comment by 7c6f434c** [comment] 2021-09-07 19:25
>So what is current status? Can we use nixOS without systemd?

No, NixOS mainline requires systemd and there are no signs of that changing,

**Comment by ketzacoatl** [comment] 2021-09-10 13:50
Would NixOS governance be open to an effort to make this possible?

**Comment by inoshy** [comment] 2021-09-22 05:31
meh

**Comment by kskeigrshi** [comment] 2021-12-13 03:02
If you hate systemd that much and think it's some kind of monstorous crap, then you should use GNU's Guix system instead of NixOS because it uses the shepherd init system. Nix is directly integrated with systemd to boot up ans manage daemons efficiently, and adding an extra init system will only make the developers cry as they struggle to implement a wrapper for them too.

**Comment by CamoCatX** [comment] 2024-02-13 02:08
@crocket mentioned gentoo, and I know this is an old issue, but it might be worth looking at this overlay:

https://github.com/trofi/nix-guix-gentoo
