### ISSUE TITLE
Build failure: zig

### ISSUE THREAD

**Issue by wenzlawski** [NixOS/nixpkgs#354820] opened 2024-11-09 18:06 UTC
### Steps To Reproduce

1. nix shell nixpkgs#zig

### Build log

https://gist.github.com/wenzlawski/9a470ed3485996405790be15c2f9fafd

### Additional context

Also tried master branch with https://github.com/mitchellh/zig-overlay, with same outcome.

On nixpkgs 24.05 it manages to build without problems.

It always used to work. Am at a loss for what could be wrong. Somehow Zig does not find any of the dynamic libraries in the paths its looking in. Not sure where they are supposed to be but they are not where Zig is looking for them.

At one point it succeeded building Zig but then the zig executable was broken, never finding the *.dylibs.

### Notify maintainers

@andrewrk 
@AndersonTorres 
@figsoda 

### Metadata

output of `nix-shell -p nix-info --run "nix-info -m"`

 - system: `"x86_64-darwin"`
 - host os: `Darwin 24.1.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `""`
 - nixpkgs: `/Users/mw/.nix-defexpr/channels/nixpkgs`

**Comment by FliegendeWurst** [comment] 2024-11-09 18:59
Duplicate of #353702

**Closed by FliegendeWurst** 2024-11-09 18:59 UTC
Labels: 0.kind: build failure
