### ISSUE TITLE
bundler tries to write to nix store

### ISSUE THREAD

**Issue by pstn** [NixOS/nixpkgs#18784] opened 2016-09-20 11:29 UTC
## Issue description
Every time I try to run bundler following the nixpkgs packaging documentation I get an error because bundle wants to write into my nix store instead of the local directory. I don't think that this is a sensible default.

### Steps to reproduce
run bundler or bundle anywhere on  my system

## Technical details
- What did you do?

  I ran the command `/run/current-system/sw/bin/bundler install --gemfile=Gemfile --local --path=~/mumble-ruby-pluginbot/mumble-ruby-pluginbot/`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EROFS: Read-only file system @ dir_s_mkdir - /nix/store/r3gjzl75v6ciq1yjjgqjzh4gfi2f21yg-gemfile-and-lockfile/.bundle
      /nix/store/dmg399zhnrac554k36pqqqf4q7mqypyv-ruby-2.2.3-p0/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir'
      /nix/store/dmg399zhnrac554k36pqqqf4q7mqypyv-ruby-2.2.3-p0/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
      /nix/store/dmg399zhnrac554k36pqqqf4q7mqypyv-ruby-2.2.3-p0/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
      /nix/store/dmg399zhnrac554k36pqqqf4q7mqypyv-ruby-2.2.3-p0/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
      /nix/store/dmg399zhnrac554k36pqqqf4q7mqypyv-ruby-2.2.3-p0/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
      /nix/store/dmg399zhnrac554k36pqqqf4q7mqypyv-ruby-2.2.3-p0/lib/ruby/2.2.0/fileutils.rb:210:in `each'
      /nix/store/dmg399zhnrac554k36pqqqf4q7mqypyv-ruby-2.2.3-p0/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
      /nix/store/j3jjs21ywsz9p86ps3xrf0x1lrba8x7r-bundler-1.12.5/lib/ruby/gems/2.2.3/gems/bundler-1.12.5/lib/bundler/settings.rb:203:in `block in set_key'
      /nix/store/j3jjs21ywsz9p86ps3xrf0x1lrba8x7r-bundler-1.12.5/lib/ruby/gems/2.2.3/gems/bundler-1.12.5/lib/bundler/shared_helpers.rb:105:in `filesystem_access'
      /nix/store/j3jjs21ywsz9p86ps3xrf0x1lrba8x7r-bundler-1.12.5/lib/ruby/gems/2.2.3/gems/bundler-1.12.5/lib/bundler/settings.rb:202:in `set_key'
      /nix/store/j3jjs21ywsz9p86ps3xrf0x1lrba8x7r-bundler-1.12.5/lib/ruby/gems/2.2.3/gems/bundler-1.12.5/lib/bundler/settings.rb:34:in `[]='
      /nix/store/j3jjs21ywsz9p86ps3xrf0x1lrba8x7r-bundler-1.12.5/lib/ruby/gems/2.2.3/gems/bundler-1.12.5/lib/bundler/cli/install.rb:82:in `run'
      /nix/store/j3jjs21ywsz9p86ps3xrf0x1lrba8x7r-bundler-1.12.5/lib/ruby/gems/2.2.3/gems/bundler-1.12.5/lib/bundler/cli.rb:175:in `install'
      /nix/store/j3jjs21ywsz9p86ps3xrf0x1lrba8x7r-bundler-1.12.5/lib/ruby/gems/2.2.3/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /nix/store/j3jjs21ywsz9p86ps3xrf0x1lrba8x7r-bundler-1.12.5/lib/ruby/gems/2.2.3/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /nix/store/j3jjs21ywsz9p86ps3xrf0x1lrba8x7r-bundler-1.12.5/lib/ruby/gems/2.2.3/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /nix/store/j3jjs21ywsz9p86ps3xrf0x1lrba8x7r-bundler-1.12.5/lib/ruby/gems/2.2.3/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /nix/store/j3jjs21ywsz9p86ps3xrf0x1lrba8x7r-bundler-1.12.5/lib/ruby/gems/2.2.3/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      /nix/store/j3jjs21ywsz9p86ps3xrf0x1lrba8x7r-bundler-1.12.5/lib/ruby/gems/2.2.3/gems/bundler-1.12.5/exe/bundler:21:in `block in <top (required)>'
      /nix/store/j3jjs21ywsz9p86ps3xrf0x1lrba8x7r-bundler-1.12.5/lib/ruby/gems/2.2.3/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /nix/store/j3jjs21ywsz9p86ps3xrf0x1lrba8x7r-bundler-1.12.5/lib/ruby/gems/2.2.3/gems/bundler-1.12.5/exe/bundler:19:in `<top (required)>'
      /run/current-system/sw/bin/bundler:18:in `load'
      /run/current-system/sw/bin/bundler:18:in `<main>'

Environment

  Bundler   1.12.5
  Rubygems  2.6.2
  Ruby      2.2.3p172 (2015-08-18 revision 0) [x86_64-linux]
  GEM_HOME  /nix/store/mwcqza43p60yk6s29y6sdxywgg637k8j-jekyll-3.0.1/lib/ruby/gems/2.2.3
  GEM_PATH  /nix/store/j3jjs21ywsz9p86ps3xrf0x1lrba8x7r-bundler-1.12.5/lib/ruby/gems/2.2.3
  Git       2.9.3

      Bundler settings

  path
    Set for your local app (/nix/store/r3gjzl75v6ciq1yjjgqjzh4gfi2f21yg-gemfile-and-lockfile/.bundle/config): "~/mumble-ruby-pluginbot/mumble-ruby-pluginbot/"
    Set via BUNDLE_PATH: "/nix/store/mwcqza43p60yk6s29y6sdxywgg637k8j-jekyll-3.0.1/lib/ruby/gems/2.2.3"
  gemfile
    Set via BUNDLE_GEMFILE: "/home/philipp/nixpkgs/pkgs/applications/networking/mumble-ruby-pluginbot/Gemfile"
  frozen
    Set via BUNDLE_FROZEN: "1"
  orig_path
    Set via BUNDLE_ORIG_PATH: "/home/philipp/bin:/var/setuid-wrappers:/home/philipp/.nix-profile/bin:/home/philipp/.nix-profile/sbin:/home/philipp/.nix-profile/lib/kde4/libexec:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:/nix/var/nix/profiles/default/lib/kde4/libexec:/run/current-system/sw/bin:/run/current-system/sw/sbin:/run/current-system/sw/lib/kde4/libexec"
  bin_path
    Set via BUNDLE_BIN_PATH: "/nix/store/j3jjs21ywsz9p86ps3xrf0x1lrba8x7r-bundler-1.12.5/lib/ruby/gems/2.2.3/gems/bundler-1.12.5/exe/bundle"

* System: 16.09pre88945.5120af0 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre88945.5120af0

**Comment by pstn** [comment] 2016-09-20 11:33
Paging @zimbatm because you seem to maintain bundler.

**Comment by Mic92** [comment] 2016-09-20 13:09
I use direnv by @zimbatm with the following settings in my .envrc to solve this problem:

```
use nix -p ruby.devEnv
layout ruby
export BUNDLE_PATH=$GEM_HOME
```

**Comment by zimbatm** [comment] 2016-09-20 13:12
Same, I'm using direnv to set the GEM_HOME (that's what `layout ruby` does). I think the issue is that rubygems should default using `$HOME/.ruby` as the default GEM_HOME and it's not doing that for some reason.

**Comment by pstn** [comment] 2016-09-20 13:37
So, what do I do?
I created an .envrc in the directory containing my Gemfile:

    use nix -p ruby.devEnv
    layout ruby
    export GEM_HOME=$HOME/.ruby
    export BUNDLE_PATH=$GEM_HOME````

And run 

     eval "$(direnv hook zsh)"

and then

     direnv exec /run/current-system/sw/bin/bundler install --gemfile=Gemfile --local

but I still get the same error. What am I doing wrong?

**Comment by Mic92** [comment] 2016-09-20 13:42
When change to project root where the Gemfile and .envrc is located, what is the output of `gem env`?
You can `export GEM_HOME=$HOME/.ruby` in this case.

**Comment by zimbatm** [comment] 2016-09-20 13:51
I'm working on a fix as I think it never makes sense to install into the derivation path. Until then the simpler fix is to: `echo "gem: --user-install" > ~/.gemrc`

**Comment by pstn** [comment] 2016-09-20 14:40
gem env:

    RubyGems Environment:
     - RUBYGEMS VERSION: 2.6.6
     - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-linux]
     - INSTALLATION DIRECTORY: /home/philipp/.ruby
     - USER INSTALLATION DIRECTORY: /home/philipp/.gem/ruby/2.3.0
     - RUBY EXECUTABLE: /nix/store/n9x90ki4zisbij53f3fqxgc52iw8mzrl-ruby-2.3.1-p0/bin/ruby
     - EXECUTABLE DIRECTORY: /home/philipp/.ruby/bin
     - SPEC CACHE DIRECTORY: /home/philipp/.gem/specs
     - SYSTEM CONFIGURATION DIRECTORY: /nix/store/n9x90ki4zisbij53f3fqxgc52iw8mzrl-ruby-2.3.1-p0/etc
     - RUBYGEMS PLATFORMS:
        - ruby
        - x86_64-linux
      - GEM PATHS:
         - /home/philipp/.ruby
         - /home/philipp/.gem/ruby/2.3.0
         - /nix/store/n9x90ki4zisbij53f3fqxgc52iw8mzrl-ruby-2.3.1-p0/lib/ruby/gems/2.3.0
      - GEM CONFIGURATION:
         - :update_sources => true
         - :verbose => true
         - :backtrace => false
         - :bulk_threshold => 1000
      - REMOTE SOURCES:
         - https://rubygems.org/
      - SHELL PATH:
         - /home/philipp/nixpkgs/pkgs/applications/networking/mumble-ruby-pluginbot/.direnv/bin
         - /home/philipp/nixpkgs/pkgs/applications/networking/mumble-ruby-pluginbot/.direnv/ruby-/bin
         - /home/philipp/bin
         - /var/setuid-wrappers
         - /home/philipp/.nix-profile/bin
         - /home/philipp/.nix-profile/sbin
         - /home/philipp/.nix-profile/lib/kde4/libexec
         - /nix/var/nix/profiles/default/bin
         - /nix/var/nix/profiles/default/sbin
         - /nix/var/nix/profiles/default/lib/kde4/libexec
         - /run/current-system/sw/bin
         - /run/current-system/sw/sbin
         - /run/current-system/sw/lib/kde4/libexec

Putting

    gem: --user-install

into my (otherwise empty) .gemrc does nothing

**Comment by zimbatm** [comment] 2016-09-20 14:41
Try unsetting the GEM_HOME now

**Comment by zimbatm** [comment] 2016-09-20 14:42
First try to do this: `gem install jsonpp` should install the gem in your home. Once this is fine we can move onto bundler.

**Comment by pstn** [comment] 2016-09-20 14:45
Yes, that worked with:

    Fetching: jsonpp-1.2.1.gem (100%)
    WARNING:  You don't have /home/philipp/.gem/ruby/2.3.0/bin in your PATH,
              gem executables will not run.
    Successfully installed jsonpp-1.2.1
    Parsing documentation for jsonpp-1.2.1
    Installing ri documentation for jsonpp-1.2.1
    Done installing documentation for jsonpp after 0 seconds
    1 gem installed

**Comment by zimbatm** [comment] 2016-10-03 18:27
Fixed in unstable

**Closed by zimbatm** 2016-10-03 18:27 UTC
Labels: 6.topic: ruby
