### ISSUE TITLE
cantata symbol lookup error

### ISSUE THREAD

**Issue by siddharthist** [NixOS/nixpkgs#17887] opened 2016-08-21 07:16 UTC
## Issue description
When starting Cantata, I get the following error:
```
/home/siddharthist/.nix-profile/bin/cantata: symbol lookup error: /nix/store/dycw7iwqlx6dm7jci6qyq8qdxhvijcvm-qtbase-5.5.1/lib/libQt5XcbQpa.so.5: undefined symbol: _ZN22QWindowSystemInterface19registerTouchDeviceEP12QTouchDevice
```

### Steps to reproduce
 1. Install Cantata
 2. Try to start it

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
```
~ > nixos-version
16.09.git.5a501bd (Flounder)
```
* Nix version: (run `nix-env --version`)
```
~ > nix-env --version
nix-env (Nix) 1.11.2
```
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
```
~ > nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.09.git.5a501bd"
```

**Comment by vcunat** [comment] 2016-09-11 13:39
Clearly seems a duplicate of https://github.com/NixOS/nixpkgs/issues/17448.

**Closed by vcunat** 2016-09-11 13:39 UTC

**Comment by siddharthist** [comment] 2016-09-11 23:29
@vcunat Thanks, sorry for the dup!
