### ISSUE TITLE
ocamlPackages.re2 build fails

### ISSUE THREAD

**Issue by mnacamura** [NixOS/nixpkgs#35701] opened 2018-02-27 02:40 UTC
```
% nix-build '<nixpkgs>' -A ocamlPackages.re2
these derivations will be built:
  /nix/store/sl8w658ilnnav3lmj2pdpv5rx4nv4piw-ocaml4.04.2-re2-0.9.0.drv
building '/nix/store/sl8w658ilnnav3lmj2pdpv5rx4nv4piw-ocaml4.04.2-re2-0.9.0.drv'...
unpacking sources
unpacking source archive /nix/store/ykhl3cfv0nl5w245l3xmg8hbwm04q2mm-source
source root is source
patching sources
configuring
no configure script, doing nothing
building
build flags: SHELL=/nix/store/zqh3l3lyw32q1ayb15bnvg9f24j5v2p0-bash-4.4-p12/bin/bash
jbuilder build @install
         gcc src/stubs.o (exit 1)
(cd _build/default/src && /nix/store/gqg2vrcq7krqi9rrl6pphvsg81sb8pjw-gcc-wrapper-7.3.0/bin/gcc -I /nix/store/rs9jig05sn2x5wnsibp0bvfqsa5fw57z-ocaml-4.04.2/lib/ocaml -O2 -fno-strict-aliasing -fwrapv -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT -fPIC -I /nix/store/1jcsbw7z58r9g2crnas2gqn1fdx490dp-ocaml4.04.2-variantslib-0.9.0/lib/ocaml/4.04.2/site-lib/variantslib -I /nix/store/1nfwbjfh0rg2ah7cp17rwf0m5vzxcyvn-ocaml4.04.2-fieldslib-0.9.0/lib/ocaml/4.04.2/site-lib/fieldslib -I /nix/store/2cxvhnz6khkcvfpna12ly3cbi23qry41-ocaml-findlib-1.7.3/lib/ocaml/4.04.2/site-lib/num -I /nix/store/2zvsjqs78kci29xy8b85d1khm1nnq4ac-ocaml4.04.2-sexplib-0.10.0/lib/ocaml/4.04.2/site-lib/sexplib -I /nix/store/2zvsjqs78kci29xy8b85d1khm1nnq4ac-ocaml4.04.2-sexplib-0.10.0/lib/ocaml/4.04.2/site-lib/sexplib/0 -I /nix/store/4czxgqb1xi18hkkmpa13dzv0vmgrljcy-ocaml4.04.2-ppx_hash-0.9.0/lib/ocaml/4.04.2/site-lib/ppx_hash/runtime-lib -I /nix/store/4xw7s9j1hyn82y745fdd7iyz4nn2qm21-ocaml4.04.2-ppx_compare-0.9.0/lib/ocaml/4.04.2/site-lib/ppx_compare/runtime-lib -I /nix/store/6q71f68j6r47hj2g2dyaq16az0db10kg-ocaml4.04.2-base-0.9.4/lib/ocaml/4.04.2/site-lib/base -I /nix/store/6q71f68j6r47hj2g2dyaq16az0db10kg-ocaml4.04.2-base-0.9.4/lib/ocaml/4.04.2/site-lib/base/caml -I /nix/store/6q71f68j6r47hj2g2dyaq16az0db10kg-ocaml4.04.2-base-0.9.4/lib/ocaml/4.04.2/site-lib/base/shadow_stdlib -I /nix/store/8d94bmr1rdg9kcixayn1ca5zx8b5x4i4-ocaml4.04.2-ppx_expect-0.9.0/lib/ocaml/4.04.2/site-lib/ppx_expect/collector -I /nix/store/8d94bmr1rdg9kcixayn1ca5zx8b5x4i4-ocaml4.04.2-ppx_expect-0.9.0/lib/ocaml/4.04.2/site-lib/ppx_expect/common -I /nix/store/8d94bmr1rdg9kcixayn1ca5zx8b5x4i4-ocaml4.04.2-ppx_expect-0.9.0/lib/ocaml/4.04.2/site-lib/ppx_expect/config -I /nix/store/9074sa9f7kv351fiqp04hks7d5nzggvw-ocaml4.04.2-ppx_assert-0.9.0/lib/ocaml/4.04.2/site-lib/ppx_assert/runtime-lib -I /nix/store/b6pfz98zpidb382n8bhi2q3dlxwdgbyc-ocaml-ppx_deriving-4.2.1/lib/ocaml/4.04.2/site-lib/ppx_deriving -I /nix/store/g7p5zh03d1sbwk5p5rcajv9b4416r0i8-ocaml4.04.2-ppx_bench-0.9.0/lib/ocaml/4.04.2/site-lib/ppx_bench/runtime-lib -I /nix/store/hnr4wvzygvgv5jzijxpr7q3z275ng2ld-ocaml4.04.2-bin_prot-0.9.1/lib/ocaml/4.04.2/site-lib/bin_prot -I /nix/store/hnr4wvzygvgv5jzijxpr7q3z275ng2ld-ocaml4.04.2-bin_prot-0.9.1/lib/ocaml/4.04.2/site-lib/bin_prot/shape -I /nix/store/j97ypwmyy5i0jyd6wdqxwzl0rkjidhvg-ocaml4.04.2-result-1.2/lib/ocaml/4.04.2/site-lib/result -I /nix/store/rp45qg0099rz705rpc5nc8mdr3a5hm2l-ocaml4.04.2-stdio-0.9.1/lib/ocaml/4.04.2/site-lib/stdio -I /nix/store/rscva7323jddi5cgvb8h9qqwf5xb0dqc-ocaml4.04.2-jane-street-headers-0.9.0/lib/ocaml/4.04.2/site-lib/jane-street-headers -I /nix/store/yj9s0gzybwzj8kdfjzkg0rv8rdmiicz9-ocaml4.04.2-ppx_inline_test-0.9.2/lib/ocaml/4.04.2/site-lib/ppx_inline_test/config -I /nix/store/yj9s0gzybwzj8kdfjzkg0rv8rdmiicz9-ocaml4.04.2-ppx_inline_test-0.9.2/lib/ocaml/4.04.2/site-lib/ppx_inline_test/runtime-lib -I /nix/store/ywz9k09550ynj05y86xsfxxsgrb2mrah-ocaml4.04.2-core_kernel-0.9.0/lib/ocaml/4.04.2/site-lib/core_kernel -I /nix/store/ywz9k09550ynj05y86xsfxxsgrb2mrah-ocaml4.04.2-core_kernel-0.9.0/lib/ocaml/4.04.2/site-lib/core_kernel/base_for_tests -I /nix/store/zn9bpb9sb87jk829mm8saxb3cxpl0wx5-ocaml4.04.2-typerep-0.9.0/lib/ocaml/4.04.2/site-lib/typerep -I re2_c -g \ -pedantic -I re2_c/libre2 -o stubs.o -c stubs.cpp)
gcc: error: \: No such file or directory
      ocamlc src/.re2.objs/re2__Re2_internal.{cmo,cmt}
File "src/re2_internal.ml", line 129, characters 25-46:
Warning 52: Code should not depend on the actual values of
this constructor's arguments. They are only for information
and may change in future versions. (See manual section 8.5)
    ocamlopt src/.re2.objs/re2__Re2_internal.{cmx,o}
File "src/re2_internal.ml", line 129, characters 25-46:
Warning 52: Code should not depend on the actual values of
this constructor's arguments. They are only for information
and may change in future versions. (See manual section 8.5)
make: *** [Makefile:5: default] Error 1
builder for '/nix/store/sl8w658ilnnav3lmj2pdpv5rx4nv4piw-ocaml4.04.2-re2-0.9.0.drv' failed with exit code 2
error: build of '/nix/store/sl8w658ilnnav3lmj2pdpv5rx4nv4piw-ocaml4.04.2-re2-0.9.0.drv' failed
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.4, NixOS, 18.03pre129076.831ef4756e3 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0pre5968_a6c0b773`
 - channels(mnacamura): `"nixpkgs-18.03pre129212.098c7f3d945"`
 - channels(root): `"nixos-18.03pre129076.831ef4756e3"`
 - nixpkgs: `/home/mnacamura/Repos/nixpkgs`

**Comment by vbgl** [comment] 2018-02-27 09:27
`git bisect` blames e066751227b8ddf9d61c3f52a552e4d7a1da1c2a (#35312).

**Comment by mt-caret** [comment] 2018-02-27 14:08
try
```
    patchPhase = ''
      sed -i 's/"\\\\" //' src/jbuild
    '';
```
my PR (https://github.com/NixOS/nixpkgs/pull/35439) with the fix (and a version bump) is waiting on https://github.com/NixOS/nixpkgs/pull/35418.

**Comment by vbgl** [comment] 2018-02-27 14:14
Is it an upstream bug then? If this is the case, it might be reported there too.

**Comment by mt-caret** [comment] 2018-02-27 14:16
Yeah, I believe so. I'll do that.

**Comment by mt-caret** [comment] 2018-02-27 14:17
I just checked, and there seems to be a fix in the works: https://github.com/janestreet/re2/pull/24

**Comment by vbgl** [comment] 2018-03-02 17:10
I think this has been fixed by #36194. Can someone please confirm?

**Comment by mt-caret** [comment] 2018-03-03 03:12
I can't confirm that; `nix-build -A ocaml-ng.ocamlPackages_4_06.janeStreet.re2` seems to fail with different errors (something about ppx_core).
https://gist.github.com/mt-caret/4bb8a17003c03204899ac76505d27b21

**Comment by vbgl** [comment] 2018-03-03 09:52
This issue is about `ocamlPackages.re2` (i.e. 4.04). `ppx_core` needs to be updated before it works with 4.06.

**Comment by mt-caret** [comment] 2018-03-03 13:42
I just confirmed that https://github.com/NixOS/nixpkgs/pull/36194 does fix the problem for ocamlPackages.re2; I think we can close this.

**Closed** 2018-03-03 14:51 UTC
Labels: 0.kind: bug, 6.topic: ocaml
