### ISSUE TITLE
gitlab test and fresh deployments broken

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#65681] opened 2019-07-31 17:46 UTC
**Describe the bug**
Clean Gitlab installs appeas to be broken, judging from the test

**Describe the bug**
During initialization: 

```
gitlab# [   13.769018] sudo[1049]: pam_unix(sudo:session): session opened for user gitlab by (uid=0)
gitlab# [   13.795292] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/wrap_parameters.rb': Permission denied
gitlab# [   13.800139] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/0_acts_as_taggable.rb': Permission denied
gitlab# [   13.805824] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/0_inflections.rb': Permission denied
gitlab# [   13.812362] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/2_gitlab.rb': Permission denied
gitlab# [   13.818874] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/5_backend.rb': Permission denied
gitlab# [   13.825213] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/6_validations.rb': Permission denied
gitlab# [   13.831837] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/7_redis.rb': Permission denied
gitlab# [   13.838867] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/8_gitaly.rb': Permission denied
gitlab# [   13.845319] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/9_fast_gettext.rb': Permission denied
gitlab# [   13.852062] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/action_mailer_hooks.rb': Permission denied
gitlab# [   13.857392] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/active_record_migration.rb': Permission denied
gitlab# [   13.864460] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/active_record_mysql_timestamp.rb': Permission denied
gitlab# [   13.871134] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/active_record_preloader.rb': Permission denied
gitlab# [   13.877943] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/active_record_schema_ignore_tables.rb': Permission denied
gitlab# [   13.885004] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/active_record_table_definition.rb': Permission denied
gitlab# [   13.892395] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/active_record_verbose_query_logs.rb': Permission denied
gitlab# [   13.899111] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/ar_speed_up_migration_checking.rb': Permission denied
gitlab# [   13.907172] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/backtrace_silencers.rb': Permission denied
gitlab# [   13.912268] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/batch_loader.rb': Permission denied
gitlab# [   13.921306] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/bootstrap_form.rb': Permission denied
gitlab# [   13.927816] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/bullet.rb': Permission denied
gitlab# [   13.932906] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/chronic_duration.rb': Permission denied
gitlab# [   13.939418] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/connection_fix.rb': Permission denied
gitlab# [   13.946013] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/cookies_serializer.rb': Permission denied
gitlab# [   13.949846] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/date_time_formats.rb': Permission denied
gitlab# [   13.958943] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/default_url_options.rb': Permission denied
gitlab# [   13.964582] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/deprecations.rb': Permission denied
gitlab# [   13.971830] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/devise_password_length.rb.example': Permission denied
gitlab# [   13.978152] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/direct_upload_support.rb': Permission denied
gitlab# [   13.983988] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/etag_caching.rb': Permission denied
gitlab# [   13.991382] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/fix_local_cache_middleware.rb': Permission denied
gitlab# [   13.998802] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/flipper.rb': Permission denied
gitlab# [   14.002582] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/fog_google_https_private_urls.rb': Permission denied
gitlab# [   14.007499] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/forbid_sidekiq_in_transactions.rb': Permission denied
gitlab# [   14.011421] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/gitlab_workhorse_secret.rb': Permission denied
gitlab# [   14.014999] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/go_get.rb': Permission denied
gitlab# [   14.018658] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/grpc.rb': Permission denied
gitlab# [   14.022047] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/hamlit.rb': Permission denied
gitlab# [   14.025525] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/health_check.rb': Permission denied
gitlab# [   14.029048] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/kaminari_config.rb': Permission denied
gitlab# [   14.032745] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/mime_types.rb': Permission denied
gitlab# [   14.036292] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/mini_magick.rb': Permission denied
gitlab# [   14.039955] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/mysql_ignore_postgresql_options.rb': Permission denied
gitlab# [   14.043682] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/omniauth.rb': Permission denied
gitlab# [   14.047928] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/pages.rb': Permission denied
gitlab# [   14.051479] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/postgresql_limit_fix.rb': Permission denied
gitlab# [   14.055358] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/query_limiting.rb': Permission denied
gitlab# [   14.058927] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/rack_attack.rb.example': Permission denied
gitlab# [   14.062488] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/rack_attack_git_basic_auth.rb': Permission denied
gitlab# [   14.066430] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/rack_lineprof.rb': Permission denied
gitlab# [   14.070180] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/relative_naming_ci_namespace.rb': Permission denied
gitlab# [   14.076518] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/relative_url.rb.sample': Permission denied
gitlab# [   14.080385] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/request_context.rb': Permission denied
gitlab# [   14.083980] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/request_profiler.rb': Permission denied
gitlab# [   14.088020] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/server_uptime.rb': Permission denied
gitlab# [   14.091739] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/session_store.rb': Permission denied
gitlab# [   14.095608] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/sherlock.rb': Permission denied
gitlab# [   14.099604] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/smtp_settings.rb.sample': Permission denied
gitlab# [   14.103437] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/time_zone.rb': Permission denied
gitlab# [   14.107145] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/workhorse_multipart.rb': Permission denied
gitlab# [   14.110810] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/0_as_concern.rb': Permission denied
gitlab# [   14.114420] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/0_post_deployment_migrations.rb': Permission denied
gitlab# [   14.118420] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/warden.rb': Permission denied
gitlab# [   14.122307] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/fog_core_patch.rb': Permission denied
gitlab# [   14.126031] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/active_record_lifecycle.rb': Permission denied
gitlab# [   14.129888] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/attr_encrypted_no_db_connection.rb': Permission denied
gitlab# [   14.133586] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/correlation_id.rb': Permission denied
gitlab# [   14.137480] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/doorkeeper.rb': Permission denied
gitlab# [   14.141455] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/fill_shards.rb': Permission denied
gitlab# [   14.145434] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/macos.rb': Permission denied
gitlab# [   14.149748] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/rack_attack_global.rb': Permission denied
gitlab# [   14.156320] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/rbtrace.rb': Permission denied
gitlab# [   14.163454] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/routing_draw.rb': Permission denied
gitlab# [   14.172862] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/doorkeeper_openid_connect.rb': Permission denied
gitlab# [   14.179092] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/kaminari_active_record_relation_methods_with_limit.rb': Permission denied
gitlab# [   14.185384] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/new_framework_defaults.rb': Permission denied
gitlab# [   14.190240] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/postgresql_cte.rb': Permission denied
gitlab# [   14.197479] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/sprockets_base_file_digest_key.rb': Permission denied
gitlab# [   14.206089] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/active_record_data_types.rb': Permission denied
gitlab# [   14.212345] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/ar_mysql_jsonb_support.rb': Permission denied
gitlab# [   14.226937] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/mysql_set_length_for_binary_indexes.rb': Permission denied
gitlab# [   14.234941] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/static_files.rb': Permission denied
gitlab# [   14.241598] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/01_secret_token.rb': Permission denied
gitlab# [   14.254813] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/8_devise.rb': Permission denied
gitlab# [   14.260597] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/action_dispatch_http_mime_negotiation.rb': Permission denied
gitlab# [   14.264738] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/active_record_build_select.rb': Permission denied
gitlab# [   14.269980] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/ar_native_database_types.rb': Permission denied
gitlab# [   14.276372] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/gettext_rails_i18n_patch.rb': Permission denied
gitlab# [   14.290225] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/graphql.rb': Permission denied
gitlab# [   14.297281] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/hipchat_client_patch.rb': Permission denied
gitlab# [   14.302215] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/http_hostname_override.rb': Permission denied
gitlab# [   14.310322] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/postgresql_opclasses_support.rb': Permission denied
gitlab# [   14.315991] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/premailer.rb': Permission denied
gitlab# [   14.321196] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/rspec_profiling.rb': Permission denied
gitlab# [   14.325401] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/seed_fu.rb': Permission denied
gitlab# [   14.329468] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/tracing.rb': Permission denied
gitlab# [   14.335357] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/trusted_proxies.rb': Permission denied
gitlab: running command: systemctl --no-pager show "gitlab.service"
gitlab# [   14.340134] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/1_settings.rb': Permission denied
gitlab# [   14.352479] sudo[1049]: pam_unix(sudo:session): session closed for user gitlab
gitlab# [   14.361132] systemd[1]: gitlab.service: Control process exited, code=exited, status=1/FAILURE
gitlab# [   14.368974] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/1_settings.rb.orig': Permission denied
gitlab# [   14.384566] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/7_prometheus_metrics.rb': Permission denied
gitlab# [   14.397971] nvsa4sa64pinbjbzgwla477ldbq4b6xl-unit-script-gitlab-pre-start[1044]: cp: cannot create regular file '/var/gitlab/state/config/initializers/config_initializers_active_record_locking.rb': Permission denied
```

The cause appears to be 52fd300b8cce730e50a8afd9dd3de655df1c8af6 because reinserting the tmpfiles line with the "D" rule for the initializers directory makes it work. cc @globin -- it looks to me like this never worked with fresh installs?

**To Reproduce**

`nix-build nixos/release.nix -A tests.gitlab`

**Comment by jslight90** [comment] 2019-07-31 20:39
Since https://github.com/NixOS/nixpkgs/pull/64550 was merged, I am also receiving an error that the systemd service pre-start script can't run the `rake db:migrate` command:
```
Jul 31 13:27:10 dev-gitlab1 sudo[145951]:     root : TTY=unknown ; PWD=/nix/store/yxnr6b0pfj8d6bin0j0biivpy82vj98n-gitlab-12.0.3/share/gitlab ; USER=gitlab ; COMMAND=/nix/store/27y164wm7ql6gkbl8262bi8ga3n4ni3c-gitlab-rake/bin/gitlab-rake db:migrate
Jul 31 13:27:10 dev-gitlab1 sudo[145951]: pam_unix(sudo:session): session opened for user gitlab by (uid=0)
Jul 31 13:27:14 dev-gitlab1 hvqbxl3719qszdng0xqqsayvf75hayb6-unit-script-gitlab-pre-start[145936]: /var/gitlab/state/config/application.rb:188: warning: already initialized constant Gitlab::Application::LOOSE_EE_APP_ASSETS
Jul 31 13:27:14 dev-gitlab1 hvqbxl3719qszdng0xqqsayvf75hayb6-unit-script-gitlab-pre-start[145936]: /nix/store/yxnr6b0pfj8d6bin0j0biivpy82vj98n-gitlab-12.0.3/share/gitlab/config/application.rb:188: warning: previous definition of LOOSE_EE_APP_ASSETS was here
Jul 31 13:27:14 dev-gitlab1 hvqbxl3719qszdng0xqqsayvf75hayb6-unit-script-gitlab-pre-start[145936]: rake aborted!
```

It is referencing two copies of the same application config file, in both the nix store and `/var/gitlab/state/config`.  It also seems to be caused by the changes in either https://github.com/NixOS/nixpkgs/pull/64550/commits/783c2f61066ff25718df39f4b5d4ef1193ed86d9 or https://github.com/NixOS/nixpkgs/pull/64550/commits/52fd300b8cce730e50a8afd9dd3de655df1c8af6.

**Closed** 2019-08-01 23:08 UTC
Labels: 0.kind: bug

**Comment by Ma27** [comment] 2019-08-05 21:17
test from github-commenter
