### ISSUE TITLE
[Packaging Request] Webcord

### ISSUE THREAD

**Issue by IceDBorn** [NixOS/nixpkgs#198202] opened 2022-10-28 04:22 UTC
**Project description**
A Discord and Fosscord client implemented directly without Discord API.

**Metadata**

* homepage/source URL: https://github.com/SpacingBat3/WebCord
* license: MIT
* platforms:  linux, darwin

**Comment by huantianad** [comment] 2022-10-28 04:46
Duplicate of #183061

**Closed by huantianad** 2022-10-28 04:46 UTC
Labels: 0.kind: packaging request
