### ISSUE TITLE
nerd-fonts: Corrupted font files

### ISSUE THREAD

**Issue by Fryuni** [NixOS/nixpkgs#363677] opened 2024-12-09 18:30 UTC
## Describe the bug

Nerd Fonts files are corrupted after https://github.com/NixOS/nixpkgs/pull/354543. Trying to use them on any program shows an error.

## Steps To Reproduce

1. Update the Nixpkgs flake to refer to a commit after the PR
2. Change the Nerd Fonts to use the new packages from #354543 (in my repo: https://github.com/Fryuni/config-files/commit/b0bd51cc686564996807a9148856209bd982ec44)
3. Try to open the new fonts on Font Viewer or use it on any application.

## Expected behavior

The font should work like before, being applied on applications and readable on Font Viewer.

## Screenshots

| New                                                                                                                                                                          | Old                                                                                                                                                                          |
| ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| ![image](https://github.com/user-attachments/assets/d19c4baf-b399-4d43-a747-35ced32ff23a) | ![image](https://github.com/user-attachments/assets/0b1b8b5e-4e89-49cf-a1fc-a6fb449f66b9) |

## Additional context

Happens with all nerd fonts, not just `JetBrainsMono` from the print.

## Notify maintainers

@doronbehar @rc-zb

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by DerRockWolf** [comment] 2024-12-09 19:01
Also just ran into this. :laughing: 

Can you try running `fc-cache -rf`. For me this fixed it after restarting the affected application.

**Comment by Fryuni** [comment] 2024-12-09 20:32
Just tried. It required running `fc-cache -rf`, restarting the system, and finally rerunning it. But now it is working.

Thank you @DerRockWolf!

I'll leave this open since I think it shouldn't require an extra command and it is happening when using home-manager, not `nixos-rebuild`, so it doesn't seem like solving the issue you linked would solve this. But if that is the intended way then this can be closed.

**Comment by doronbehar** [comment] 2024-12-10 07:49
Duplicate of:
- #57780

**Closed** 2024-12-10 07:49 UTC
Labels: 0.kind: bug

**Comment by DerRockWolf** [comment] 2024-12-10 21:16
> Duplicate of:
> 
>     * [Refresh the font cache after a `nixos-rebuild switch` #57780](https://github.com/NixOS/nixpkgs/issues/57780)

Is `home-manager switch` also covered by the linked issue?

**Comment by doronbehar** [comment] 2024-12-11 10:05
> > Duplicate of:
> > ```
> > * [Refresh the font cache after a `nixos-rebuild switch` #57780](https://github.com/NixOS/nixpkgs/issues/57780)
> > ```
> 
> Is `home-manager switch` also covered by the linked issue?

Technically, Home manager is not a Nixpkgs program, so it doesn't have to be :), so you can file an issue there or look it up there.
