### ISSUE TITLE
librewolf browser

### ISSUE THREAD

**Issue by DaxGoon** [NixOS/nixpkgs#117825] opened 2021-03-27 18:53 UTC
**Project description**
Add librewolf browser to nixos packages repo.

**Metadata**

* homepage URL: https://librewolf-community.gitlab.io/
* source URL: https://gitlab.com/librewolf-community/browser
* license: Mozilla Public License 2.0.
* platforms: gnu/linux, darwin, windows

**Comment by dotlambda** [comment] 2021-03-28 16:58
duplicate of https://github.com/NixOS/nixpkgs/issues/94918

**Closed by dotlambda** 2021-03-28 16:58 UTC
Labels: 0.kind: packaging request
