### ISSUE TITLE
can't install 32bit nixos

### ISSUE THREAD

**Issue by igorvkuznetsov** [NixOS/nixpkgs#44218] opened 2018-07-30 06:20 UTC
## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by igorvkuznetsov** [comment] 2018-07-30 06:56
it seems very likely that this is the problem. 64 version is installed fine

**Comment by vcunat** [comment] 2018-07-30 07:54
Yeah, certainly a duplicate of the other threads.

**Closed by vcunat** 2018-07-30 07:54 UTC
