### ISSUE TITLE
Incus:  does not include openvswitch in path

### ISSUE THREAD

**Issue by cmspam** [NixOS/nixpkgs#290427] opened 2024-02-21 12:52 UTC
### Describe the bug
When using incus with openvswitch, incus needs to have openvswitch in its path for features involving openvswitch to work. As a result, when attaching an openvswitch as a bridged interface in incus, we encounter issues such as veth interface remaining active when it should be cleaned up, not being able to use openvswitch to make bridges, etc. It is not so urgent because it's easy enough to add it to the path, but it caused me some trouble until I figured out the cause.

### Steps To Reproduce
Enable openvswitch, enable incus, run "incus network create BRIDGENAME —type bridge bridge.driver=openvswitch" and notice that incus does not detect openvswitch.

### Expected behavior
If openvswitch is enabled, openvswitch will be added to incus's path, and the above command will not fail.

### Additional context
Can be resolved by adding 
systemd.services.incus.path = [ pkgs.openvswitch ];

Maybe just need to check if openvswitch enabled, and if so, add it to the path by default?

### Notify maintainers

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamcstephens** [comment] 2024-02-21 14:25
Do you have a vswitch configuration you're able to share?

**Comment by cmspam** [comment] 2024-02-21 14:36
Yes, but if I configure it using nixos, I get other problems (incus is deleting the whole bridge whenever I shut down a container and I don’t know what part of nixos is responsible for it), so I have switched to configuring it with networkmanager, where it all works well, as long as I add openvswitch to path.

But here is a very simple example with a nixos configuration:
  virtualisation.vswitch.enable = true;
  networking.vswitches =
  {
    br0 = {
      interfaces = {
        eth0 = { };
      };
    };
  };
  networking.interfaces.vmbr0.useDHCP = true;

Just adjust eth0 to whatever device you want to add to the bridge.

Then in incus, we can add a profile. Easy way to do this is set up the default profile. Then we copy it to a new one:

incus copy profile default ovstest

and edit it

incus profile edit ovstest

Then replace the networking eth0 part with the below:

devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic

Then make a container on the profile:

incus launch images:debian/bookworm mycontainer —profile ovstest


It should work fine, but (this is a bug I think I haven’t reported because it could be my own stupidity) when you stop the container

incus stop mycontainer

All of your configured bridges will be missing, completely.

So the way I do it now is enabling network manager. We can add eth0 to a network manager-defined ovs bridge this way:
https://blog.oddbit.com/post/2020-02-15-configuring-open-vswitch-with/￼

Setting it up like this, and adding the line below, everything is working as expected.

(If I don’t add the path = line, the virtual ethernet devices don’t get cleaned up when incus shuts down a container, which is why I filed the bug report to try to have it included default)

systemd.services.incus = {
    path = [ pkgs.openvswitch ];


Hopefully this answers what you are looking for.

**Comment by adamcstephens** [comment] 2024-02-22 05:08
Thanks! Sounds like you have a workaround until this can get fixed in the module.

**Comment by cmspam** [comment] 2024-02-22 11:48
> Thanks! Sounds like you have a workaround until this can get fixed in the module.
> 
> I'm not quite sure why your bridge is being removed when the container is stopped. You could try creating a bridge instead, but then it looks like you should be setting `bridge.driver` https://linuxcontainers.org/incus/docs/main/reference/network_bridge/#network-bridge
> 
> I tried to test this, but creating an ovs bridge yields:
> 
> ```
> ─❯ incus network create test1 --type=bridge bridge.driver=openvswitch
> Error: open /proc/sys/net/ipv6/conf/test1/disable_ipv6: no such file or directory
> ```

I think it is because that ovs bridge doesn't exist yet.
If you just attach a pre-existing ovs bridge to the container, it will work.

Regular linux bridges defined with the nixos configuration also have the same disappearing problem, but with networkmanager work fine.

**Comment by adamcstephens** [comment] 2024-02-22 12:47
Actually the error I encountered is a bug. https://github.com/lxc/incus/pull/518

**Comment by adamcstephens** [comment] 2024-02-22 14:04
I'm not able to reproduce your issue where the stopping of the container removes a bridge from the host. Are you on 23.11 or unstable?

**Comment by cmspam** [comment] 2024-02-22 15:24
This is on 23.11.

**Comment by adamcstephens** [comment] 2024-02-22 15:56
If you are able, can you try and reproduce using nixos unstable?

**Comment by cmspam** [comment] 2024-02-22 16:01
Sure, I will give it a go.

**Comment by cmspam** [comment] 2024-02-22 16:20
So, yes, I can reproduce it on unstable. Both with linux switches and with openvswitch switches.

Here is all of the configuration related to networking. You can see the commented lines would be how I set up the linux bridges when testing them.

  virtualisation.vswitch.enable = true;
  virtualisation.vswitch.resetOnStart = true;
  networking.useDHCP = false;
  networking.hostName = "boss";
#  networking.bridges.vmbr0.interfaces = [ "eth0" ];
  networking.iproute2.enable = true;
  networking.vswitches.vmbr0.interfaces.eth0.name = "eth0";
  networking.interfaces.vmbr0.ipv4.addresses = [{
    address = "192.168.0.2";
    prefixLength = 24;
  }];
  networking.interfaces.vmbr0.ipv4.routes = [{
    address = "0.0.0.0";
    prefixLength = 0;
    via = "192.168.0.1";
    options = {
      metric = "100";
    };
  }];
#  networking.bridges.vmbr1.interfaces = [ "eth1" ];
  networking.vswitches.vmbr1.interfaces.eth1.name = "eth1";
  networking.interfaces.vmbr1.ipv4.addresses = [{
    address = "192.168.1.2";
    prefixLength = 24;
  }];
  networking.interfaces.vmbr1.ipv4.routes = [{
    address = "0.0.0.0";
    prefixLength = 0;
    via = "192.168.1.1";
    options = {
      metric = "101";
    };
  }];
  boot.kernel.sysctl."net.ipv6.conf.eth2.disable_ipv6" = true;
  networking.firewall.enable = false;
  networking.nameservers = ["1.1.1.1" "8.8.8.8”];

**Comment by cmspam** [comment] 2024-03-10 14:54
I have created a pull request to resolve the path issues.

https://github.com/NixOS/nixpkgs/pull/294754

**Closed** 2024-03-12 02:56 UTC
Labels: 0.kind: bug
