### ISSUE TITLE
Multimc

### ISSUE THREAD

**Issue by jakobneufeld** [NixOS/nixpkgs#147389] opened 2021-11-25 18:09 UTC
###### Checklist

- [ ] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [ ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: multimc-unstable

current version: 2021-09-08
desired version: 0.6.13

###### Notify maintainers

maintainers: @cleverca22 @starcraft66 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by lourkeur** [comment] 2021-11-26 08:01
2021-09-08 is identical to 0.6.13, they both map to commit e2355eb276bf355ca4acf526a0f3cc390aa88f8b in MultiMC. The difference is purely cosmetic.

(I have a patch for that sleeping in 38916c3999bcb082c784e19fc43514fa27176428 if it's needed)

**Comment by jakobneufeld** [comment] 2021-11-26 10:26
But, why does Multimc then not support microsoft accounts?
\

**Comment by lourkeur** [comment] 2021-11-26 11:38
Please refer to [this document on the Wiki](https://nixos.wiki/wiki/MultiMC) to enable microsoft accounts for MultiMC.

duplicate of #144912

**Closed by lourkeur** 2021-11-26 11:38 UTC
Labels: 9.needs: package (update)
