### ISSUE TITLE
Package request: PearAI

### ISSUE THREAD

**Issue by InSelfControll** [NixOS/nixpkgs#363781] opened 2024-12-10 02:12 UTC
## Project description

PearAI is a code editor that have AI builtin.
## Metadata

* homepage URL: https://trypear.ai/
* source URL: https://github.com/trypear/pearai-app
* license: MIT license
* platforms: unix, linux, darwin

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].
+1
[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nang-dev** [comment] 2024-12-10 07:05
+1!

**Comment by pluiedev** [comment] 2024-12-10 09:10
Duplicate of #355773

**Closed by pluiedev** 2024-12-10 09:10 UTC
Labels: 0.kind: packaging request
