### ISSUE TITLE
jellyfin: NVENC ffmpeg fails when called by jellyfin but works as user 

### ISSUE THREAD

**Issue by seandheath** [NixOS/nixpkgs#141298] opened 2021-10-11 22:27 UTC
## Issue description
Enabled Nvidia NVENC on Jellyfin. The transcoding command works when run as a user but Jellyfin logs show an error `no CUDA-capable device is detected`

### Steps to reproduce
1. Enable Nvidia NVENC on Jellyfin in settings > admin dashboard > playback
2. Play movie through web client
3. Look at ffmpeg log and see that it fails because `no CUDA-capable device is detected`
4. Copy the ffmpeg command from near the top of the log file
5. Run the ffmpeg command using `sudo -u jellyfin <command>`
6. ffmpeg command appears to work correctly

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.71, NixOS, 21.05.3740.ce7a1190a0f (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.05.3740.ce7a1190a0f"`
 - channels(user): `"home-manager-21.05, nixgl, nixos-unstable-21.11pre322215.9bf75dd50b7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by justinas** [comment] 2021-10-16 20:21
> Presumably due to aggressive `systemd` sandboxing.
> 
> ping @nyanloutre @minijackson

I would believe that is the case. I am experiencing the same with VAAPI / Intel QuickSync. I would assume that at least access to `/dev/dri/renderD128` is required for VAAPI. However, I did not investigate further, simply ripping out *all* hardening options works for me now.

**Comment by aanderse** [comment] 2021-10-16 21:07
Someone should make a PR so NixOS users don't have a bad `jellyfin` experience. Any takers?

**Comment by minijackson** [comment] 2021-10-17 17:22
This should be solved by #108224, which has been pending for a while now, sorry about that. I'm not finding myself having a lot of free time nowadays, so I'd appreciate if someone could contact upstream to propose hardening the systemd service. @seandheath could you test if #108224 works for you ? We can probably merge it in the meantime if it works. I will also accept a PR removing some hardening options altogether, if you feel it'd be best without it.

**Comment by matthiasdv** [comment] 2021-12-06 22:06
Ran into this issue on my Intel Coffee Lake machine too. Can confirm the options work on Intel / VAAPI. I created an upstream issue and PR to get some eyes on this: 

https://github.com/jellyfin/jellyfin/issues/6952
https://github.com/jellyfin/jellyfin/pull/6953

**Comment by nialov** [comment] 2024-12-04 21:25
As this issue i still open, I will shamelessly bump. I have the exact same issue as the original poster. Transcoding on an NVIDIA GPU works as root and as a regular user but the `jellyfin` service does not have access. I had to completely overwrite the `systemd` service definition of `nixpkgs` to finally get it working. See below.

~~~nix
# TODO: Configuration from NixOS does not work due to some hardening
# Or user permissions, group permissions, file permissions. Who knows.
{ config, lib, ... }:

let cfg = config.services.jellyfin;

in {

  services.jellyfin = {
    enable = false;
    dataDir = "/var/lib/jellyfin";
    configDir = "/var/lib/jellyfin/config";
    logDir = "/var/lib/jellyfin/log";
    cacheDir = "/var/lib/jellyfin/cache";
    user = "root";
  };
  systemd = {
    tmpfiles.settings.jellyfinDirs = {
      "${cfg.dataDir}"."d" = {
        mode = "777";
        user = "root";
      };
      "${cfg.configDir}"."d" = {
        mode = "777";
        user = "root";
      };
      "${cfg.logDir}"."d" = {
        mode = "777";
        user = "root";
      };
      "${cfg.cacheDir}"."d" = {
        mode = "777";
        user = "root";
      };
    };
    services = {
      jellyfin = { enable = false; };
      jellyfin-nialov = {
        description = "jellyfin-nialov Media Server";
        after = [ "network-online.target" ];
        wants = [ "network-online.target" ];
        wantedBy = [ "multi-user.target" ];

        serviceConfig = {
          Type = "simple";
          User = cfg.user;
          WorkingDirectory = cfg.dataDir;
          ExecStart = "${
              lib.getExe cfg.package
            } --datadir '${cfg.dataDir}' --configdir '${cfg.configDir}' --cachedir '${cfg.cacheDir}' --logdir '${cfg.logDir}'";
          Restart = "on-failure";
          TimeoutSec = 15;
          SuccessExitStatus = [ "0" "143" ];
        };
      };
    };
  };
}
~~~

I tried all the tricks posted in previous posts of this/similar issues:

https://github.com/jellyfin/jellyfin/issues/6952
https://github.com/NixOS/nixpkgs/pull/149715
https://github.com/NixOS/nixpkgs/pull/108224
https://github.com/NixOS/nixpkgs/pull/175439
https://github.com/NixOS/nixpkgs/issues/356535

But none of them worked. I tried to figure out which exact `systemd` hardening flag caused the problem but eventually just went with this nuclear option as I did not have the motivation to debug it until the end.

My suggestion is, if it seems like others run into this same issue, that the hardening is significantly reduced from the `jellyfin` service by default or an option is created that can be used to disable all the hardening so that people can see if the hardening is the cause for issues. There are many other hard to debug things about NVIDIA GPUs, so it would probably be nice if the default hardening of the `nixpkgs` `jellyfin` service unit was not one of them. Especially as it is not mentioned in the documentation of it.

**Comment by justinas** [comment] 2024-12-04 22:14
> As this issue i still open, I will shamelessly bump. I have the exact same issue as the original poster. Transcoding on an NVIDIA GPU works as root and as a regular user but the `jellyfin` service does not have access. I had to completely overwrite the `systemd` service definition of `nixpkgs` to finally get it working. See below.
> I tried all the tricks posted in previous posts of this/similar issues:

PR 356535 is not related to Nvidia at all. The issue there is Intel's OpenCL implementation dropping support for earlier generations of hardware.

To be sure that it is "the exact same issue", could you post the relevant parts of logs (both the Jellyfin log, and the individual FFmpeg invocation logs)?

I just tested on my machine (24.11, Nvidia RTX 4070), `services.jellyfin.enable = true;` and literally no other configuration related to Jellyfin in Nix. I then enabled NVENC in Jellyfin's settings, including tonemapping, and it seems to work.

I did see massive CPU usage while transcoding and that initially made me think that FFmpeg is falling back to CPU software encoding, but I don't think it would silently do that? I also see a GPU power usage increase and a few hundred megs of VRAM used by `ffmpeg` in `nvidia-smi`. Not to mention that it is transcoding at several times the framerate compared to software transcoding.

Here's what Jellyfin is successfully invoking using these settings (formatted for easier reading):

<details>
<summary>FFmpeg command-line</summary>

```
/nix/store/0llgi4x4fl2i29dsf63w70l1bbjpmmfn-jellyfin-ffmpeg-7.0.2-5-bin/bin/ffmpeg
  -analyzeduration 200M
  -probesize 1G
  -f matroska
  -init_hw_device cuda=cu:0
  -filter_hw_device cu
  -i file:"/Movies/***.mkv"
  -map_metadata
  -1
  -map_chapters
  -1
  -threads 0
  -map 0:0
  -map 0:1
  -map
  -0:s
  -codec:v:0 h264_nvenc
  -preset p1
  -b:v 31762095
  -maxrate 31762095
  -bufsize 63524190
  -profile:v:0 high
  -g:v:0 72
  -keyint_min:v:0 72
  -vf "setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc,scale=trunc(min(max(iw\,ih*a)\,min(3840\,2080*a))/2)*2:trunc(min(max(iw/a\,ih)\,min(3840/a\,2080))/2)*2,format=yuv420p10le,hwupload=derive_device=cuda,tonemap_cuda=format=yuv420p:p=bt709:t=bt709:m=bt709:tonemap=bt2390:peak=100:desat=0"
  -codec:a:0 aac
  -ac 2
  -ab 256000
  -af "volume=2"
  -copyts
  -avoid_negative_ts disabled
  -max_muxing_queue_size 2048
  -f hls
  -max_delay 5000000
  -hls_time 3
  -hls_segment_type fmp4
  -hls_fmp4_init_filename "54c25bf20c420adc3da18cdcfdda56fc-1.mp4"
  -start_number 0
  -hls_segment_filename "/var/cache/jellyfin/transcodes/54c25bf20c420adc3da18cdcfdda56fc%d.mp4"
  -hls_playlist_type vod
  -hls_list_size 0
  -y "/var/cache/jellyfin/transcodes/54c25bf20c420adc3da18cdcfdda56fc.m3u8"
```

</details>

Note `-init_hw_device cuda=cu:0`, `-codec:v:0 h264_nvenc`, etc. This makes me believe that GPU acceleration is being used.

For completeness sake, here's my graphics settings:

```
{
  hardware.graphics = {
    enable32Bit = true;
    enable = true;
    extraPackages = with pkgs; [ vaapiVdpau libvdpau-va-gl ];
  };

  hardware.nvidia = {
    modesetting.enable = true;
    open = true;
  };
}
```

**Comment by nialov** [comment] 2024-12-05 21:28
> To be sure that it is "the exact same issue", could you post the relevant parts of logs (both the Jellyfin log, and the individual FFmpeg invocation logs)?

Yes you are right, I might have been getting ahead of myself by saying it is the same issue. Mostly just meant my issue follows the same formula of `ffmpeg` not having access under the `jellyfin` service whereas normal and root users do have it and I could run the exact same `ffmpeg` commands with those users successfully whereas it failed with permission issues under the `jellyfin` service.

I will re-enable the standard `jellyfin` service definition and post the logs in a few days time!

**Comment by justinas** [comment] 2024-12-14 12:30
I'm glad it worked out for you. I think we should close this issue for now - it's been 3 years, the root cause of device permissions / excessive hardening seems to have been solved, further issues with NVENC should be discussed separately.

**Closed by justinas** 2024-12-14 12:30 UTC
