### ISSUE TITLE
Qt/KDE applications segfault on start due to stale qmlcache

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#177720] opened 2022-06-15 06:35 UTC
### Describe the bug

We've had a recurring problem since 2017 that manifests itself with Qt based applications (and therefore a lot of KDE) that fail to launch as they segfault on start due to a stale `qmlcache` directory.

Some examples:
- https://github.com/NixOS/nixpkgs/issues/32072
- https://github.com/NixOS/nixpkgs/issues/32577
- https://github.com/NixOS/nixpkgs/issues/35013
- https://github.com/NixOS/nixpkgs/issues/125545
- https://github.com/NixOS/nixpkgs/issues/152284
- https://github.com/NixOS/nixpkgs/issues/174019
  
Apart from being an annoyance whenever individual components are affected by this, when *critical* components (such as parts of the plasma desktop) face this, people are left with environments they cannot get into.

Additionally, there are 2 types of affected programs that most likely will require different solutions:
a. those that run at a system level (such as sddm)
b. user level applications
   
The purpose of this ticket is to see if we can come up with a proper solution once and for all.

The following is a workaround for the current user only:

```sh
# substitute -delete for -print if you want to see what happens instead of actually deleting the files
find ${XDG_CACHE_HOME:-$HOME/.cache}/**/qmlcache -type f -delete
```

Any comments?

Cc: @NixOS/qt-kde 

#### System level applications

So far I only know of `sddm` and it was fixed by using `tmpfiles` to clear out the directory on boot. I propose dealing with other system level applications (if any) the same way as they should have a known `$HOME` and we should know up front which applications require the workaround.

##### an activation script 

The script runs as root and finds all `qmlcache` directories under `/home` and empties them.

Pros:
 - very easy to do and reason about
 - covers almost all cases
 
Cons:
 - doesn't work for users with encrypted home that are not logged in
 - it's heavy-handed in the sense that it deletes data far more often than technically necessary
 - suddenly having directories yanked out from underneath may cause applications to crash
 - if home-manager is in use and *not* included as a NixOS module, we would need cooperation from home-manager in order to run the same script on activation of a new home-manager generation but this would only handle the current user unless the user can `sudo/doas`.

   
##### script run on a timer

Runs the activation script but scheduled instead.

Pros:
 - can't really think of any
   
Cons:
 - same as above but with the added complexity of the user(s) not knowing when it happens

##### systemd user unit runs script on login

Runs the activation script but on login through a systemd user oneshot service

Pros:
 - handles encrypted home
 - handles all users incl those that are not logged in when a new generation is activated

Cons:
 - doesn't handle the case where a new generation is activated without the user logging out and back in
 - it's heavy-handed in the sense that it deletes data far more often than technically necessary

   
##### hybrid activation/login

Have both the activation scripts (NixOS/home-manager) and a systemd user unit execute the same clean-up script.

Pros:
 - covers pretty much all scenarios
   
Cons:
 - it's heavy-handed in the sense that it deletes data far more often than technically necessary
 - suddenly having directories yanked out from underneath may cause applications to crash
   
### Not viable

- tmpfiles on its own as we cannot glob and clean out directories
- wrap every application potentially affected by this with a script that clears out the relevant directory. It's a maintenance nightmare and re-active.

**Comment by viperML** [comment] 2022-06-15 06:54
I've had a similiar problem with a 3rd party extension after an update: #165383

The solution was also to remove some parts of `~/.cache`

**Comment by ulrikstrid** [comment] 2022-06-15 06:58
Looks like this might be a valid fix? https://github.com/mozilla-mobile/mozilla-vpn-client/issues/2487#issuecomment-999784529

It seems to have issues on macOS and Windows but they should not be a problem for NixOS

**Comment by ajs124** [comment] 2022-06-15 12:46
Do we know why this cache becomes stale/does not get invalidated properly?

**Comment by symphorien** [comment] 2022-06-15 20:25
Some applications can be built to not use the qmlcache and compile the qml stuff at build time: https://github.com/NixOS/nixpkgs/pull/99121#issuecomment-727165392

**Comment by eliasp** [comment] 2022-06-19 18:33
IMHO, the lifetime of qmlcache objects should be bound to the derivation - so any change to any of the inputs of an application would invalidate older cache objects.

I'm just digging through the Qt docs regarding the QML Disk Cache - trying to find out whether and how this could achieved, but IMHO everything else is either hackish or bound to fail sooner or later.

I feel like the place to handle this (mostly guessing, I don't know enough about the Qt/QML internals) that the [`QHash`](https://github.com/qt/qtdeclarative/blob/0dc4fd240a2897c5c443a0ef6d84c416843e4938/src/qmlcompiler/qqmljscompiler.cpp#L229) usage in [`qCompileQmlFile`](https://github.com/qt/qtdeclarative/blob/0dc4fd240a2897c5c443a0ef6d84c416843e4938/src/qmlcompiler/qqmljscompiler.cpp#L190-L346) might be the right place to handle this on a Qt level, but I'm struggling right now to imagine how an application's build-ID/derivation-hash/… could be passed into this.

**Comment by eduarrrd** [comment] 2022-07-04 20:30
Drive-by comment about the first post:

> So far I only know of sddm and it was fixed by using tmpfiles to clear out the directory on boot.

I don't think "fixed" is fully true. I found *this* bug exactly due to SDDM segfaulting. Emptying the cache manually using `rm -r` did fix the issue for me. I'm reasonably confident that the bad cache survived multiple reboots. I'm not filing a bug for this now b/c I don't have logs (systemd-tmpfiles is quite quiet without the right env var) and I can't reproduce it (in fact, in my current session `.cache` is empty). I guess the takeaway might be that even the tmpfiles.d workaround is non-trivial.

**Comment by ttuegel** [comment] 2022-07-05 16:17
> Do we know why this cache becomes stale/does not get invalidated properly?

Yes: Qt ties cache invalidation only to file modification time.

> I'm struggling right now to imagine how an application's build-ID/derivation-hash/… could be passed into this.

@eliasp What if we included the entire input filename when computing the hash? That would implicitly include the derivation hash, unless I'm missing something.

**Comment by eliasp** [comment] 2022-07-05 17:35
> Qt ties cache invalidation only to file modification time.
…which is pretty useless, when all file mtimes in the Nix store are 1970-01-01 (for good reasons) :shrug: 

> @eliasp What if we included the entire input filename when computing the hash? That would implicitly include the derivation hash, unless I'm missing something.
That's probably ultimately the lesser problem - finding something that's unique for this use-case - but yeah, the canonical filepath might work just fine!
I'm still struggling a bit with where to exactly hook into Qt/QML to achieve this - if you have ideas, feel free to give it a try! 

But when actually using the filepath as suggested by you, this could actually work with a single central modification in Qt/QML without having to inject this into each and every QML-based application, as the QML cache logic already evaluates the file for getting the mtime, so we'd just have to change the mtime input to a filepath input.

**Comment by eliasp** [comment] 2022-07-05 18:25
I believe to have found the right places to tackle in qt/qtdeclarative:
```diff
diff --git a/src/qml/qml/qqmlscriptblob.cpp b/src/qml/qml/qqmlscriptblob.cpp
index dac21f7ee7..bb2d159a0e 100644
--- a/src/qml/qml/qqmlscriptblob.cpp
+++ b/src/qml/qml/qqmlscriptblob.cpp
@@ -73,6 +73,7 @@ void QQmlScriptBlob::dataReceived(const SourceCodeData &data)
         QQmlRefPointer<QV4::ExecutableCompilationUnit> unit
                 = QV4::ExecutableCompilationUnit::create();
         QString error;
+        // TODO: replace `sourceTimeStamp` with absolute path or other unique attribute like the file's hash
         if (unit->loadFromDisk(url(), data.sourceTimeStamp(), &error)) {
             initializeFromCompilationUnit(unit);
             return;
@@ -137,6 +138,7 @@ void QQmlScriptBlob::dataReceived(const SourceCodeData &data)
         QString errorString;
         if (executableUnit->saveToDisk(url(), &errorString)) {
             QString error;
+            // TODO: replace `sourceTimeStamp` with absolute path or other unique attribute like the file's hash
             if (!executableUnit->loadFromDisk(url(), data.sourceTimeStamp(), &error)) {
                 // ignore error, keep using the in-memory compilation unit.
             }
diff --git a/src/qml/qml/qqmltypedata.cpp b/src/qml/qml/qqmltypedata.cpp
index 92a90ea677..df62ba77f5 100644
--- a/src/qml/qml/qqmltypedata.cpp
+++ b/src/qml/qml/qqmltypedata.cpp
@@ -143,6 +143,7 @@ bool QQmlTypeData::tryLoadFromDiskCache()
     QQmlRefPointer<QV4::ExecutableCompilationUnit> unit = QV4::ExecutableCompilationUnit::create();
     {
         QString error;
+        // TODO: replace `sourceTimeStamp` with absolute path or other unique attribute like the file's hash
         if (!unit->loadFromDisk(url(), m_backupSourceCode.sourceTimeStamp(), &error)) {
             qCDebug(DBG_DISK_CACHE) << "Error loading" << urlString() << "from disk cache:" << error;
             return false;
@@ -784,6 +785,7 @@ void QQmlTypeData::compile(const QQmlRefPointer<QQmlTypeNameCache> &typeNameCach
         QString errorString;
         if (m_compiledData->saveToDisk(url(), &errorString)) {
             QString error;
+            // TODO: replace `sourceTimeStamp` with absolute path or other unique attribute like the file's hash
             if (!m_compiledData->loadFromDisk(url(), m_backupSourceCode.sourceTimeStamp(), &error)) {
                 // ignore error, keep using the in-memory compilation unit.
             }
```

**Comment by eliasp** [comment] 2022-07-05 18:28
This is an issue, which will ultimately not only affect NixOS, but also all other distributions/ISVs/etc. making use of [reproducible builds](https://reproducible-builds.org/) using a fixed timestamp, so it might make sense to raise this as an upstream issue or get someone from the Reproducible Builds project ppl on board…

**Comment by eliasp** [comment] 2022-07-05 22:58
Here's a 1st stab at an implementation which uses a content-based QCryptographicHash as input for the cache (in-)validation:
https://github.com/qt/qtdeclarative/commit/844f225af8c42bb8efe0448d56b53694c031508a (just hacked it together, didn't test yet whether this actually compiles & works)

**Comment by peterhoeg** [comment] 2022-07-06 05:34
Or as mentioned by @symphorien - we prebuild the cache and distribute it with the applications.

**Comment by eliasp** [comment] 2022-07-07 22:52
> This looks interesting! With this patch, could we load old cache files? They will have a different header format.

@ttuegel no - existing cache objects won't be used (as intended), esp. due to the now different header


After digging a bit deeper into this, my current outcome looks like this:

- pre-compiling as used by @symphorien might help a bit, but it seems it's not a magical silver bullet as some code-paths still only evaluate at runtime, so there'll be still a lot of caching going on.
- pre-compiling (at least until Qt 6.3/6.4) seems to come with a performance hit compared to using runtime-cached bytecode

Sources:
- https://www.qt.io/blog/the-new-qtquick-compiler-technology
- https://www.qt.io/blog/the-new-qt-quick-compiler-is-coming-in-qt

So I believe we still need proper (non-mtime based) handling of cache objects to fully fix this issue, no matter whether we should decide to globally or per package make use of qtquickcompiler.

I'll try to continue with my initial QCrytpographicHash-based approach during the next days to see whether this has the desired effect. My ultimate goal would be to upstream this at some point, as IMHO using the mtime of the binary's compile time is a fundamentally broken approach which:
- doesn't work for deterministic/reproducible builds
- is not immune to collisions, e.g. in massive build-farms when rebuilding many different packages at the same time and therefore potentially two different versions of the same package as well

**Comment by tpwrules** [comment] 2022-09-13 01:05
Qt maintainer Thiago Macieira has told me on IRC essentially that, on the contrary, it is Nix which is fundamentally broken for having a fixed mtime, and this proposed patch would not be accepted upstream due to the speed penalty of having to read in and hash every .qml file every startup. I don't know if his opinions are similar to the rest of the Qt project's, but it is a valid data point.

I will try to test your patch next week or so and see if it solves my problems with qmlcaches and Qt Creator projects. I think using the content hash is the obviously correct approach, maybe there is a way to pre-generate it at compile time in the case where the .qml files are linked in to the executable as a resource. I'm not sure how common this is though.

There are also some [disk cache environment variables](https://doc.qt.io/qt-5/qmldiskcache.html). Caching could be turned off by default or a cache path could be generated which includes the derivation path and these variables could be set by `wrapQtAppsHook`. I'm not sure how close this is to the listed not viable approach of "wrap every application potentially affected by this with a script that clears out the relevant directory".

Alternately I would support mixing the .qml file's canonical absolute path into the hash key as Thiago Macieira seemed to believe it was already done. This wouldn't work for projects built through Qt Creator or help other distros, but it would align more with upstream and solve the problem completely on Nix.

**Comment by eliasp** [comment] 2022-09-13 07:54
> Qt maintainer Thiago Macieira has told me on IRC essentially that, on the contrary, it is Nix which is fundamentally broken for having a fixed mtime, and this proposed patch would not be accepted upstream due to the speed penalty of having to read in and hash every .qml file every startup. I don't know if his opinions are similar to the rest of the Qt project's, but it is a valid data point.

It's disappointing to hear this, but I believe it's not a NixOS-specific issue, as based on current adoption uptake, sooner or later every distribution/ISV/build-process will utilize reproducible build paradigms, [heavily relying on deterministic timestamps](https://reproducible-builds.org/docs/timestamps/). We might have to build a comprehensive set of arguments to convince the Qt community of this approach and why it is the right one. 

If this happens on startup, the performance impact would be IMHO negligible, as the file has to be read into memory anyways and hashing is quite inexpensive (in terms of CPU consumption) nowadays, esp. since some CPUs now even have hashing instructions, e.g. [Intel® SHA Extensions](https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sha-extensions.html).

> I will try to test your patch next week or so and see if it solves my problems with qmlcaches and Qt Creator projects.

I didn't get around yet to actually test it, this was blindly hacked together and I didn't even try to compile it yet - you might be lucky and it "simply works", but expect some fiddling with it before it builds.

> I think using the content hash is the obviously correct approach, maybe there is a way to pre-generate it at compile time in the case where the .qml files are linked in to the executable as a resource. I'm not sure how common this is though.

Instead of hashing at runtime, I'd be happy to see QML doing hashing at build-time as well as it avoids the runtime performance penalty completely, but this might be far more complex implementation wise as it would change the Qt build process to add the hash as some kind of metadata as a final step. I have right now no idea how to tackle this, although I like this approach from a theoretical perspective.

> There are also some [disk cache environment variables](https://doc.qt.io/qt-5/qmldiskcache.html). Caching could be turned off by default or a cache path could be generated which includes the derivation path and these variables could be set by `wrapQtAppsHook`. I'm not sure how close this is to the listed not viable approach of "wrap every application potentially affected by this with a script that clears out the relevant directory".

AFAIK this will generate a new user-specific cache directory for each build on the first application startup which won't be cleaned up in any way, so users will end up accumulating huge caches over time which they'll have to clean up manually.

> Alternately I would support mixing the .qml file's canonical absolute path into the hash key as Thiago Macieira seemed to believe it was already done. This wouldn't work for projects built through Qt Creator or help other distros, but it would align more with upstream and solve the problem completely on Nix.

IIRC this was something I found out not to be the case [verification needed] and it wasn't the absolute path that was used. Furthermore, this won't help with embedded QML resources which are loaded via `qrc:///`, referring to QML resources relative to the project's root.

**Comment by tpwrules** [comment] 2022-09-23 23:17
> It's disappointing to hear this, but I believe it's not a NixOS-specific issue, as based on current adoption uptake, sooner or later every distribution/ISV/build-process will utilize reproducible build paradigms, [heavily relying on deterministic timestamps](https://reproducible-builds.org/docs/timestamps/). We might have to build a comprehensive set of arguments to convince the Qt community of this approach and why it is the right one.

While I agree with you wholeheartedly, it's not quite as clean for us in particular because the Nix store and package NAR format simply cannot represent an mtime that's not `1`. Other build systems could theoretically set SOURCE_DATE_EPOCH to the total number of package builds, or a truncated hash of the source, and (probably) work. But Nix, uniquely I believe, cannot do this, and this is more what Thiago was criticizing earlier.

> If this happens on startup, the performance impact would be IMHO negligible, as the file has to be read into memory anyways and hashing is quite inexpensive (in terms of CPU consumption) nowadays, esp. since some CPUs now even have hashing instructions, e.g. [Intel® SHA Extensions](https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sha-extensions.html).

I think on modern systems and use cases you are correct. More data would have to be read, as the .qml file must be read to hash it if its cache file exists. But since disks and hashing are so fast these days on desktop systems, and this caching was added relatively recently (5 or so years ago), it's not a serious concern in my mind for Nixpkgs.

It probably is a more serious concern for embedded-type Qt applications and the global Qt ecosystem. It's also possible AFAIK to load QML files over any URI so in theory this could result in network access too; it's fair to say upstream Qt has more to take into account than Nixpkgs.

> Instead of hashing at runtime, I'd be happy to see QML doing hashing at build-time as well as it avoids the runtime performance penalty completely, but this might be far more complex implementation wise as it would change the Qt build process to add the hash as some kind of metadata as a final step. I have right now no idea how to tackle this, although I like this approach from a theoretical perspective.

I'm not sure what a "build" might mean for a QML loaded over a network dynamically, but I somewhat doubt this actually happens in Nixpkgs. The process I was referring to here was the QRC mechanism, which must touch the QML files already. I hypothesize this is how essentially all QML files exist in Nixpkgs.

> AFAIK this will generate a new user-specific cache directory for each build on the first application startup which won't be cleaned up in any way, so users will end up accumulating huge caches over time which they'll have to clean up manually.

Yes, this is true. Theoretically it is also the case if the user uninstalls some application as its cache files will never be deleted, but with Nix the user will have lots of versions so this a much greater problem. I wonder if it could be paired with a cleanup or expiry script, perhaps built into Qt itself. But this could lead to (somewhat improbable) race conditions.

Please also keep in mind I am not knowledgeable on the Qt ecosystem or internals to any significant degree.

**Comment by samueldr** [comment] 2022-09-24 00:18
Sorry to jump in "late" with this suggestion, which I quickly looked around and haven't seen mentioned: do we know how badly it affects Qt software if the cache is removed entirely in our builds? Maybe there's some way the cache could be per-process, if cache gains are important in a single process's lifetime?

In other words, can we cheat and literally ignore most of the problem?

**Comment by tpwrules** [comment] 2022-09-24 00:45
I don’t think it would be that bad, after all it did not exist for 2/3rds of QMLs life. There is a simple environment variable to disable it, and of course the code could be patched out. You are the one with stake in lower spec mobile hardware which is where I would expect it to matter most.

Based on my limited understanding, I don’t think the cache helps at all during a process’s lifetime. But I could be wrong.

**Comment by tpwrules** [comment] 2022-09-27 23:42
@eliasp I gave your patch a try but could not get it to work. It applies with a minor tweak but the qmlcache does not seem to get invalidated properly. I recompile software with changed .qml files and am unable to see that change reflected until I delete the cache directory. There's still some possibility I'm overriding wrong. Just wanted to confirm it wasn't ready.

But I did confirm that `SOURCE_DATE_EPOCH` is respected by Qt and stored in the QRC files. I changed the .qml files and `SOURCE_DATE_EPOCH` and those changes are reflected immediately next time the app starts. I believe there is a build hook which can automatically set the SOURCE_DATE_EPOCH according to the source code's timestamp instead of to a fixed value. Maybe it would be worth doing this as a stopgap as this should resolve the problem for users the majority of the time. I welcome input from the Nixpkgs Qt maintainers.

**Comment by samueldr** [comment] 2022-09-28 00:05
> I believe there is a build hook which can automatically set the SOURCE_DATE_EPOCH according to the source code's timestamp instead of to a fixed value.

Yes

 - https://github.com/NixOS/nixpkgs/blob/bc71a15e46269cafe7f702946ce2ab232d4df448/doc/stdenv/stdenv.chapter.md#set-source-date-epoch-to-latestsh-set-source-date-epoch-to-latestsh

IIRC it'll work fine only when unpacking files as source input. If the files are somehow already unpacked in the Nix store (builtins.fetchGit?) those files will not have the expected modified time.

**Comment by tpwrules** [comment] 2022-10-16 16:21
It looks like that build hook always runs. But in most cases (e.g. using `fetchFromGitHub`) the files are stored with a time of 1 so that hook doesn't do anything. I did some further perusing of Qt's source code and it looks like `SOURCE_DATE_EPOCH` is treated as a `QDateTime` so the idea of setting it to a hash or something and not a real time scares me slightly.

It does look like patching out the disk cache is quite simple and safe though. That seems like a good temporary fix until we can settle on a better cache key. Or determine that the performance loss is low enough to not be concerned with.

**Comment by samueldr** [comment] 2022-10-16 21:20
I would indeed be somewhat concerned about messing with dates and KDE things. Not exactly related, but see:

 - https://github.com/NixOS/mobile-nixos/commit/70de5008f33fd0c750ebaee2262fd466da1c9159

**Comment by tpwrules** [comment] 2022-10-20 22:55
I did some lightly scientific benchmarking to see how much the QML cache really mattered. My test system is an ODROID-C4 with a 64GB Sandisk Extreme memory card as storage and an older commit of NixOS 22.05. Not bottom of the barrel, but pretty low end as far as systems on which it is reasonable to run a full-fat desktop environment. Note also that this is not a daily driver system so there aren't loads of services running or applications installed (though it's not deliberately stripped down).

I first tried cool-retro-term as I found it on GitHub as using a lot of QML. It ends up with about 388K of compiled QML data across 29 files. I ran each command below to simply list some files and exit immediately, ignoring times where the GUI actually visibly started. Each command was run three times and real time recorded.

* disk cache enabled: `time cool-retro-term -e ls`: 2.147s, 2.172s, 2.143s
* disk cache disabled: `time QML_DISABLE_DISK_CACHE=1 cool-retro-term -e ls`: 2.428s, 2.411s, 2.426s
* disk cache enabled but deleted `rm -rf ~/.cache/cool-retro-term/qmlcache && time cool-retro-term -e ls`: 2.598s, 2.581s, 2.575s

It seems that disabling the disk cache imposes a launch penalty of about 10%. However, having the disk cache enabled but deleting the files imposes an additional penalty of 7-8%, presumably due to the time required to search for the cache files and write them back out. I don't imagine the CPU work would change significantly here.

I then wanted to try Plasma as it is a bigger program (3.5M of QML cache in 220 files) and one thing upstream Qt specifically mentioned they targeted with the cache is disk thrashing during startup. So I set up my system to auto log in to Plasma and added `environment.sessionVariables = { QML_DISABLE_DISK_CACHE = "1"; };` to my configuration to globally disable the disk cache for all programs. I then used a stopwatch to time how long it took from when I hit the enter key to select the system generation in Tow-Boot to when my desktop icons appeared. I ran each trial three times.

* disk cache enabled: 66s, 65s, 65s
* disk cache disabled (as above): 66s, 66s, 66s
* disk cache enabled but deleted: 70s, 70s, 69s

It looks here like the QML cache helps less as my system is disk-limited during boot. But here the additional time required to check for and fail to find cached files is measurable. So adding a system service to delete the files is not a great option, and adding an additional step to read in and hash the source may cause slowdowns too.

Based on this data, it seems quite reasonable to patch the disk cache out of Qt. This would finally stop mysterious crashes and glitches in Qt applications and only slightly slow down application launches, and not slow down boot at all. These effects will likely be less noticeable too on more powerful systems people typically use. I will propose a patch for this shortly and hope we can get it in in time for 22.11.

**Comment by ttuegel** [comment] 2022-11-05 11:28
I think we can close this given #197010: the issue has been resolved on our end as much as it can be until upstream develops a different attitude.

**Closed by ttuegel** 2022-11-05 11:28 UTC
Labels: 0.kind: bug, 6.topic: qt/kde

**Comment by eliasp** [comment] 2022-11-06 22:22
…and as predicted, other projects making use of reproducible builds ran into the same issue:
https://cordlandwehr.wordpress.com/2022/11/05/reproducible-builds-read-only-fs-and-how-a-persistent-qml-cache-then-can-ruin-your-day/

**Comment by Vogtinator** [comment] 2023-07-20 17:20
> …and as predicted, other projects making use of reproducible builds ran into the same issue: https://cordlandwehr.wordpress.com/2022/11/05/reproducible-builds-read-only-fs-and-how-a-persistent-qml-cache-then-can-ruin-your-day/

We also kind-of hit this in openSUSE once, but that was caused because `$SOURCE_DATE_EPOCH` was set incorrectly due to a bug. Other than this one time the mechanism works fine here, with reproducible builds.

I agree with Thiago that having wrong mtimes like this is broken by design, but also agree that looking just at mtime is not reliable.

**Comment by Apteryks** [comment] 2023-07-20 19:50
> …and as predicted, other projects making use of reproducible builds ran into the same issue:
> https://cordlandwehr.wordpress.com/2022/11/05/reproducible-builds-read-only-fs-and-how-a-persistent-qml-cache-then-can-ruin-your-day/

And of course, GNU Guix :-) https://issues.guix.gnu.org/64605.  Happy to see a resolution here, even if it's in the form of a workaround.
