### ISSUE TITLE
Update Glibc to 2.23

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#13104] opened 2016-02-18 20:43 UTC
Branch: https://github.com/NixOS/nixpkgs/tree/glibc-2.22

Will set up a Hydra jobset.

**Comment by vcunat** [comment] 2016-02-19 07:20
The locale problems when mixing versions should be no longer fatal, after a patch we had, right?

**Comment by edolstra** [comment] 2016-02-19 09:47
Yeah (and 2.22 contains that patch).

**Comment by codyopel** [comment] 2016-02-20 07:24
@vcunat @edolstra 

fyi, 2.23 was just released.

https://sourceware.org/git/?p=glibc.git;a=blob;f=NEWS;utm_source=anzwix;h=c0276cf81b7e838becaa252c09d3900cce6cd277;hb=refs/heads/release/2.23/master

**Comment by vcunat** [comment] 2016-02-20 07:50
Shall we skip to 2.23 then, even for 16.03? Assuming the new unicode support won't break locales again, I wouldn't expect compatibility problems.

**Comment by vcunat** [comment] 2016-02-21 09:37
2.23 builds for me now.

**Comment by edolstra** [comment] 2016-02-23 11:03
I guess we need to decide whether we want the bleeding edge or not :-) I guess I could fire off a jobset to see how much breakage 2.23 causes.

Meanwhile, there is a jobset for 2.22: http://hydra-test.nixos.org/jobset/nixpkgs/glibc-2.22. (This is also a test of the new Hydra queue runner that uploads build results directly to an S3 binary cache. The cache is `http://nix-test-cache.s3.amazonaws.com/`, public key `test.nixos.org-1:pjXm8QJl1Gsxfxjpe+R9acIs5kNvW1lIS/i/bAFnHgM=`).

**Comment by vcunat** [comment] 2016-02-23 13:37
I've got all my system running on 2.23 (+closure-size, coreutils and other stuff), and I see no problems. Maybe it *is* rather new to get into 16.03, I don't know. /cc also @domenkozar

**Comment by domenkozar** [comment] 2016-02-23 13:47
I see no problem going to 2.23 given that hydra builds all of the packages and proves most of them build :) But there's left than a week to test that.

**Comment by edolstra** [comment] 2016-02-25 10:30
@vcunat I see you merged 2.23, but it does have a bunch of new build failures: http://hydra-test.nixos.org/eval/2#tabs-now-fail

**Comment by edolstra** [comment] 2016-02-25 10:32
(And that's just the 2.22 -> 2.23 build failures, not 2.21 -> 2.22.)

**Comment by vcunat** [comment] 2016-02-25 10:51
I somehow didn't notice that jobset (or forgot it), but there's no mass breakage. Most of this seems due to webkitgtk, and it looks like it shouldn't be too hard to fix by some patch. I'll look into that.

**Comment by edolstra** [comment] 2016-02-25 11:25
Yeah, most of it looks pretty simple (some errors about `isnan` not being found, probably due to some increased header strictness).

**Comment by vcunat** [comment] 2016-02-25 12:21
The relevant ticket, most likely: https://sourceware.org/bugzilla/show_bug.cgi?id=19439

**Comment by vcunat** [comment] 2016-02-25 12:23
Aha, we might want to patch glibc instead by https://sourceware.org/git/gitweb.cgi?p=glibc.git;a=commitdiff;h=3c47c83a9730c20e602694505b9278c25637b0d0;hp=1233be76694ca81454f61e2ba5a2fb5830840191

**Comment by vcunat** [comment] 2016-02-25 12:53
Ignore the above comment. (That patch is actually contained in 2.23.)

The situation with 2.23 and isnan is unclear to me. I suppose it will be better to choose 2.22 for the upcoming release. Shall I revert 59617de6d7f8a on staging?

**Comment by vcunat** [comment] 2016-02-25 13:02
Let me ask upstream at least, as this part of the regression still seems to be without any response: https://sourceware.org/bugzilla/show_bug.cgi?id=19439#c8

**Comment by vcunat** [comment] 2016-02-25 17:59
ATM it looks most likely that a majority of the new failures was just glibc exposing non-conforming c++ header usage, as only `std::isnan` is normally (guaranteed to be) put into scope.

**Comment by vcunat** [comment] 2016-02-27 12:24
I think all the larger breakages due to glibc 2.22 -> 2.23 should be fixed in master now (libreoffice, webkitgtk, libksysguard). Only a couple individual packages aren't, and I'll leave them broken ATM.

**Closed** 2016-02-27 12:24 UTC
Labels: 1.severity: mass-rebuild
