### ISSUE TITLE
Package request: firefoxpwa

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#261299] opened 2023-10-16 00:13 UTC
**Project description**

 A tool to install, manage and use Progressive Web Apps (PWAs) in Mozilla Firefox 

**Metadata**

* homepage URL: https://pwasforfirefox.filips.si/
* source URL: https://github.com/filips123/PWAsForFirefox
* license: MPL-2.0
* platforms: linux, ?

note: this in the first place pertains the native component, a package written in rust

**Comment by Aleksanaa** [comment] 2023-10-16 03:27
closing as duplicate of https://github.com/NixOS/nixpkgs/issues/186961

**Closed by Aleksanaa** 2023-10-16 03:27 UTC
Labels: 0.kind: packaging request
