### ISSUE TITLE
Anki 2.1.40

### ISSUE THREAD

**Issue by YellowOnion** [NixOS/nixpkgs#112849] opened 2021-02-12 03:03 UTC
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: anki

current version: 2.1.15
desired version: 2.1.40

###### Notify maintainers

maintainers: @oxij @Profpatsch

###### Note for maintainers

Please tag this issue in your PR.

**Comment by iblech** [comment] 2021-02-12 16:01
Thank you for bringing this to our collective attention! First I thought that this would be a trivial version bump, but it's not so simple as the patches no longer apply. For instance, the file `aqt/anki.py` no longer exists. For the moment I'm pausing my work on this issue.

**Comment by iblech** [comment] 2021-02-12 16:12
I take that back, I was confused by a simple directory reorganization. Pull request fixing this issue is underway. :-)

**Comment by legendofa** [comment] 2021-07-11 15:26
What about the `anki-bin` package, version `2.1.44`: https://github.com/NixOS/nixpkgs/blob/nixos-21.05/pkgs/games/anki/bin.nix
Maybe it is possible to merge this with `anki` even if it is a dependency.

**Comment by austinbutler** [comment] 2022-01-03 01:55
Duplicate of https://github.com/NixOS/nixpkgs/issues/78449.

**Closed by austinbutler** 2022-01-03 01:55 UTC
Labels: 9.needs: package (update)
