### ISSUE TITLE
JFX program (Jabref) builds but won't run

### ISSUE THREAD

**Issue by jackwoodside** [NixOS/nixpkgs#220470] opened 2023-03-10 11:58 UTC
### Describe the bug
The program Jabref will build, but give a JFX related error upon trying to run the program.

### Steps To Reproduce
1. `nix-shell -p jabref`
2. `jabref`

### Expected behavior
The program launches as it used to.

### Additional context
```console
[nix-shell:~]$ jabref
Loading library glassgtk3 from resource failed: java.lang.UnsatisfiedLinkError: /home/jack/.openjfx/cache/18.0.1+2/libglassgtk3.so: libXtst.so.6: cannot open shared object file: No such file or directory
java.lang.UnsatisfiedLinkError: /home/jack/.openjfx/cache/18.0.1+2/libglassgtk3.so: libXtst.so.6: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:395)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:234)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:176)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
	at java.base/java.lang.Runtime.load0(Runtime.java:785)
	at java.base/java.lang.System.load(System.java:1979)
	at javafx.graphics@18.0.1/com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
	at javafx.graphics@18.0.1/com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
	at javafx.graphics@18.0.1/com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
	at javafx.graphics@18.0.1/com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at javafx.graphics@18.0.1/com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:221)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at javafx.graphics@18.0.1/com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:200)
	at javafx.graphics@18.0.1/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
	at javafx.graphics@18.0.1/com.sun.glass.ui.Application.run(Application.java:146)
	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)
	at javafx.graphics@18.0.1/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:293)
	at javafx.graphics@18.0.1/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at javafx.graphics@18.0.1/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at javafx.graphics@18.0.1/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at javafx.graphics@18.0.1/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "main" java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: no glassgtk3 in java.library.path: /nix/store/q2yraw31h6hk6i2gzvwhspjl50rhqa4n-jabref-5.7/lib/
	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:300)
	at javafx.graphics@18.0.1/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:293)
	at javafx.graphics@18.0.1/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at javafx.graphics@18.0.1/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at javafx.graphics@18.0.1/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at javafx.graphics@18.0.1/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.UnsatisfiedLinkError: no glassgtk3 in java.library.path: /nix/store/q2yraw31h6hk6i2gzvwhspjl50rhqa4n-jabref-5.7/lib/
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2434)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:848)
	at java.base/java.lang.System.loadLibrary(System.java:2015)
	at javafx.graphics@18.0.1/com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:166)
	at javafx.graphics@18.0.1/com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at javafx.graphics@18.0.1/com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:221)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at javafx.graphics@18.0.1/com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:200)
	at javafx.graphics@18.0.1/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
	at javafx.graphics@18.0.1/com.sun.glass.ui.Application.run(Application.java:146)
	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)
	... 6 more
```

### Notify maintainers

@gebner @linsui 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.15, NixOS, 23.05 (Stoat), 23.05pre461539.c90c4025bb6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(username): `"home-manager"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by linsui** [comment] 2023-03-10 12:24
It's fixed in https://github.com/NixOS/nixpkgs/pull/205299 but hasn't been merged.

**Closed** 2023-03-11 07:54 UTC
Labels: 0.kind: bug

**Comment by thanhnguyen2187** [comment] 2023-10-24 13:25
Hi. Sorry for digging this up, but I'm having the same error for starting a JFX application inside Intellij IDEA, where `libglassgtk3` is unable to find `libXtst.so.6` (or `libXtst`).

```
Loading library glassgtk3 from resource failed: java.lang.UnsatisfiedLinkError: /home/thanh/.openjfx/cache/17.0.6/libglassgtk3.so: libXtst.so.6: cannot open shared object file: No such file or directory
java.lang.UnsatisfiedLinkError: /home/thanh/.openjfx/cache/17.0.6/libglassgtk3.so: libXtst.so.6: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
...
```

My hack to resolve this involves:

- Make sure that there is `libXtst` within your `/nix/store` (`/nix/store/96p0ggnqip216j5pydc1krx8j4af88ql-libXtst-1.2.3/lib/` for example)
- Add the path to `LD_LIBRARY_PATH`:

  ```shell
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/nix/store/96p0ggnqip216j5pydc1krx8j4af88ql-libXtst-1.2.3/lib/
  ```

- Start Intellij IDEA from the shell.

I felt like this is worth a separate issue (Intellij and JFX related), but wanted to ask it here first.

Many thanks!

**Comment by linsui** [comment] 2023-10-24 14:26
I can't understand what you want to ask... This issue is caused by the reason said in https://github.com/NixOS/nixpkgs/pull/205299#issuecomment-1454426952.

**Comment by thanhnguyen2187** [comment] 2023-10-24 14:41
@linsui I think I meant I had the same issue (missing `libXtst` for `libglassgtk3`), but in another context, and was wondering instead of that hacky workaround, is there any way to make my JFX application starts with no error.
