### ISSUE TITLE
`nixos-rebuild switch --upgrade` breaks channel list

### ISSUE THREAD

**Issue by thblt** [NixOS/nixpkgs#264660] opened 2023-10-31 20:51 UTC
### Describe the bug

After running `nixos-rebuild switch --upgrade`, the file `/root/.nix-channels` contains quotation marks that make it invalid, breaking (among other things) subsequent calls to  `nixos-rebuild switch --upgrade`

### Steps To Reproduce
1. On NixOS unstable:
2. Observe that `/root/.nix-channels` contains the single line `https://nixos.org/channels/nixos-unstable nixos`
3. Run `sudo nixos-rebuild switch --upgrade`. Let it finish.
4. Try to run it again, observe that it fails with:
  ```
 error: reading symbolic link '/nix/var/nix/profiles/per-user/root/channels/"': No such file or directory
 ```
5. Observe that `/root/.nix-channels` now contains:
 ```
"https://nixos.org/channels/nixos-unstable nixos
"  
```
 (Extra quotation marks, also no trailing `\n`, but `\n` before the closing quotation mark)
6. `sudo nix-channel --update` also fails with `error: unable to download '"': URL using bad/illegal format or missing URL (3)`

### Expected behavior

`nixos-rebuild --upgrade` and `nix-channels --update` should keep working.

### Additional context

Appeared after a very recent update of Unstable. No significant changes to `configuration.nix` 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.53, NixOS, 23.11 (Tapir), 23.11pre542330.0cbe9f69c234`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos"`
 - channels(thblt): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jpds** [comment] 2023-10-31 22:27
Duplicate of #264602.

**Closed** 2023-10-31 22:39 UTC
Labels: 0.kind: bug
