### ISSUE TITLE
Cuneiform fails to build on Nixos Unstable Small

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#31406] opened 2017-11-08 19:32 UTC
## Issue description

Tried to update Nixos Unstable Small on my notebook and it failed - at cuneiform according from what I gather:

```
checking whether gcc accepts -g... -- Performing Test LIBCXX_SUPPORTS_WNO_CXX14_COMPAT_FLAG - Success
-- Performing Test LIBCXX_SUPPORTS_WNO_ERROR_FLAG
yes
checking whether gcc and cc understand -c and -o together... -- Performing Test LIBCXX_SUPPORTS_WNO_ERROR_FLAG - Success
-- Performing Test LIBCXX_SUPPORTS_EHSC_FLAG
configure: creating cache ./config.cache
[ 11%] Building CXX object cuneiform_src/Kern/std/CMakeFiles/std32.dir/src/stdassrt.cpp.o
checking whether make sets $(MAKE)... yes
checking for a BSD-compatible install... /nix/store/0abay33zgwqgchdzzq6h88ac4963smwf-coreutils-8.28/bin/install -c
checking whether NLS is requested... yes
checking for msgfmt... /nix/store/c1bvhykprzd775km6snicsd756w4xb2g-gettext-0.19.8/bin/msgfmt
checking for gmsgfmt... /nix/store/c1bvhykprzd775km6snicsd756w4xb2g-gettext-0.19.8/bin/msgfmt
yes
checking for POSIXized ISC... no
checking for working const... checking for xgettext... -- Performing Test LIBCXX_SUPPORTS_EHSC_FLAG - Failed
-- Performing Test LIBCXX_SUPPORTS_FPIC_FLAG
/nix/store/c1bvhykprzd775km6snicsd756w4xb2g-gettext-0.19.8/bin/xgettext
checking for msgmerge... yes
checking for inline... /nix/store/c1bvhykprzd775km6snicsd756w4xb2g-gettext-0.19.8/bin/msgmerge
checking for x86_64-unknown-linux-gnu-gcc... gcc
[ 11%] Building CXX object cuneiform_src/Kern/std/CMakeFiles/std32.dir/src/stdbits.cpp.o
inline
checking for a BSD compatible install... /nix/store/0abay33zgwqgchdzzq6h88ac4963smwf-coreutils-8.28/bin/install -c
checking how to run the C preprocessor... gcc -E
checking for sys/file.h... yes
checking for sys/param.h... checking for C compiler default output file name... yes
checking for limits.h... -- Performing Test LIBCXX_SUPPORTS_FPIC_FLAG - Success
-- Performing Test LIBCXX_SUPPORTS_STD_EQ_CXX14_FLAG
yes
checking for stdlib.h... yes
checking for malloc.h... [ 12%] Building CXX object cuneiform_src/Kern/std/CMakeFiles/std32.dir/src/stdconsl.cpp.o
yes
-- Adding Benchmark: filesystem.bench.cpp
-- Adding Benchmark: string.bench.cpp
-- Adding Benchmark: unordered_set_operations.bench.cpp
-- Adding Benchmark: util_smartptr.bench.cpp
-- Adding Benchmark: vector_operations.bench.cpp
yes
-- Configuring done
checking for sys/time.h... -- Generating done
  Manually-specified variables were not used by the project:

    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_LIBDIR
    LIBCXX_LIBCPPABI_VERSION
    LIBCXX_LIBCXXABI_LIB_PATH


yes
-- Build files have been written to: /tmp/nix-build-libc++-4.0.1.drv-0/libcxx-4.0.1.src/build
building
build flags: -j1 -l1 SHELL=/nix/store/4ada72n7785wwazv42fhsnxjvilaa3aj-bash-4.4-p12/bin/bash
checking for time.h... 
checking for suffix of object files... yes
checking for sys/resource.h... o
checking whether we are using the GNU C compiler... [ 12%] Building CXX object cuneiform_src/Kern/std/CMakeFiles/std32.dir/src/stdfilchecking for sys/pstat.h... checking build system type... x86_64-unknown-linux-gnu
checking host system type... no
checking for sys/sysmp.h... x86_64-unknown-linux-gnu
checking for x86_64-unknown-linux-gnu-ranlib... ranlib
checking for library containing strerror... [ 12%] Building CXX object cuneiform_src/Kern/std/CMakeFiles/std32.dir/src/stdiface.cpp.o
In file included from /tmp/nix-build-libc++-4.0.1.drv-0/libcxx-4.0.1.src/include/ios:216:0,
                 from /tmp/nix-build-libc++-4.0.1.drv-0/libcxx-4.0.1.src/include/ostream:138,
                 from /tmp/nix-build-libc++-4.0.1.drv-0/libcxx-4.0.1.src/include/istream:163,
                 from /tmp/nix-build-libc++-4.0.1.drv-0/libcxx-4.0.1.src/include/random:1646,
                 from /tmp/nix-build-libc++-4.0.1.drv-0/libcxx-4.0.1.src/src/algorithm.cpp:11:
/tmp/nix-build-libc++-4.0.1.drv-0/libcxx-4.0.1.src/include/__locale:39:22: fatal error: xlocale.h: No such file or directory
 # include <xlocale.h>
compilation terminated.
yes
checking for strings.h... [ 12%] Building CXX object cuneiform_src/Kern/std/CMakeFiles/std32.dir/src/stderror.cpp.o
-- Adding Benchmark: algorithms.bench.cpp
-- Adding Benchmark: filesystem.bench.cpp
-- Adding Benchmark: string.bench.cpp
-- Adding Benchmark: unordered_set_operations.bench.cpp
-- Adding Benchmark: util_smartptr.bench.cpp
-- Adding Benchmark: vector_operations.bench.cpp
yes
-- Configuring done
checking for sys/time.h... -- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_LIBDIR
    LIBCXX_LIBCPPABI_VERSION
    LIBCXX_LIBCXXABI_LIB_PATH


yes
-- Build files have been written to: /tmp/nix-build-libc++-4.0.1.drv-0/libcxx-4.0.1.src/build
building
build flags: -j1 -l1 SHELL=/nix/store/4ada72n7785wwazv42fhsnxjvilaa3aj-bash-4.4-p12/bin/bash
checking for time.h...
checking for suffix of object files... yes
checking for sys/resource.h... o
checking whether we are using the GNU C compiler... [ 12%] Building CXX object cuneiform_src/Kern/std/CMakeFiles/std32.dir/src/stdfile.cpp.o
yes
checking for sys/stat.h... yes
checking whether gcc accepts -g... yes
checking for sys/mman.h... Scanning dependencies of target cxx_objects
[  2%] Building CXX object lib/CMakeFiles/cxx_objects.dir/__/src/algorithm.cpp.o
yes
checking for gcc option to accept ISO C89... yes
checking for fcntl.h... yes
checking for alloca.h... none needed
yes
checking for sys/pstat.h... checking build system type... x86_64-unknown-linux-gnu
checking host system type... no
checking for sys/sysmp.h... x86_64-unknown-linux-gnu
checking for x86_64-unknown-linux-gnu-ranlib... ranlib
checking for library containing strerror... [ 12%] Building CXX object cuneiform_src/Kern/std/CMakeFiles/std32.dir/src/stdiface.cpp.o
In file included from /tmp/nix-build-libc++-4.0.1.drv-0/libcxx-4.0.1.src/include/ios:216:0,
                 from /tmp/nix-build-libc++-4.0.1.drv-0/libcxx-4.0.1.src/include/ostream:138,
                 from /tmp/nix-build-libc++-4.0.1.drv-0/libcxx-4.0.1.src/include/istream:163,
                 from /tmp/nix-build-libc++-4.0.1.drv-0/libcxx-4.0.1.src/include/random:1646,
                 from /tmp/nix-build-libc++-4.0.1.drv-0/libcxx-4.0.1.src/src/algorithm.cpp:11:
/tmp/nix-build-libc++-4.0.1.drv-0/libcxx-4.0.1.src/include/__locale:39:22: fatal error: xlocale.h: No such file or directory
 # include <xlocale.h>
                      ^
compilation terminated.
make[2]: *** [lib/CMakeFiles/cxx_objects.dir/build.make:63: lib/CMakeFiles/cxx_objects.dir/__/src/algorithm.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:388: lib/CMakeFiles/cxx_objects.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
builder for ‘/nix/store/igfdianb1mly1v033h8ycgbilyj3wyhj-libc++-4.0.1.drv’ failed with exit code 2
building path(s) ‘/nix/store/pnk2rb71l2zym9wbyv6k4cgzxn6hjci8-fc-00-nixos-cache.conf’
cannot build derivation ‘/nix/store/wmwfh4fbwr8hn7g5q2dixrqrg007zps2-teamspeak-client-3.1.6.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/ylc4fphpxlrcrfcbkp4rhwbrlg3jf2fb-teamviewer_12.0.76279_i386.deb’
building path(s) ‘/nix/store/7bjfk3ly9ldh8lxiylcxd3wjssvnhzzl-torrc’
building path(s) ‘/nix/store/krcm1hydqvdrvw0qn8wn3g62jyrzrfh4-torsocks.conf’
building path(s) ‘/nix/store/ii32vfvm3fcip34qg8mkdgs7bn1frzdr-locale.conf’
cannot build derivation ‘/nix/store/gd039r8lh3i1hadk2qpgifdlb80fbci6-system-path.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/as0kmy0fqxslcrqkrvffl29yrxd6ngfb-udev-rules’
building path(s) ‘/nix/store/z1775ikb75sbdl9yfbshj42ab7vd5xy2-unit-alsa-store.service’
building path(s) ‘/nix/store/31dxqz47wsfzf4aqniy3nz9vi9wy60mw-unit-audit.service’
cannot build derivation ‘/nix/store/biw0j4lmnqkx3zqpz7q6187p5qidwhr1-nixos-system-subi-18.03pre119884.c4dbbbd890.drv’: 1 dependencies couldn't be built
```

### Steps to reproduce

Try to get cuneiform running on Nixos Unstable Small

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

`18.03pre119756.4db6d35891 (Impala)`

* Nix version: (run `nix-env --version`)

`nix-env (Nix) 1.11.15`

* Nixpkgs version: (run `nix-instantiate --eval "<nixpkgs>" -A lib.nixpkgsVersion`)

`"18.03pre119884.c4dbbbd890"`

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

`build-use-sandbox = false`

**Comment by pbogdan** [comment] 2017-11-08 19:49
> /tmp/nix-build-libc++-4.0.1.drv-0/libcxx-4.0.1.src/include/__locale:39:22: fatal error: xlocale.h: No such file or directory

Sounds to me it failed on `libcxx` and this would be a duplicate of https://github.com/NixOS/nixpkgs/issues/31403

**Comment by sjau** [comment] 2017-11-08 19:50
I guess you're right.

**Comment by sjau** [comment] 2017-11-09 06:29
Actually, it seems the libcxx issue was solved but cuneiform still gives problems:

```
checking whether calloc is declared... [ 70%] Building C object cuneiform_src/Kern/rblock/CMakeFiles/rblock.dir/sources/winc/_adaptive.c.o
[  8%] Building CXX object interfaces/CMakeFiles/KDevPlatformInterfaces.dir/isourceformatter.cpp.o
[ 70%] Building C object cuneiform_src/Kern/rblock/CMakeFiles/rblock.dir/sources/new_c/_debug.c.o
yes
checking whether free is declared... In file included from /nix/store/xd2mlzvlgmskbyyb33lz2vdq15k74xpr-glibc-2.26-75-dev/include/string.h:431:0,
                 from /tmp/nix-build-cuneiform-1.1.0.drv-0/cuneiform-linux-1.1.0/cuneiform_src/Kern/rblock/../hhh/tigerh/h/c_types.h:82,
                 from /tmp/nix-build-cuneiform-1.1.0.drv-0/cuneiform-linux-1.1.0/cuneiform_src/Kern/rblock/../hhh/tigerh/h/iolib.h:65,
                 from /tmp/nix-build-cuneiform-1.1.0.drv-0/cuneiform-linux-1.1.0/cuneiform_src/Kern/rblock/sources/new_c/_debug.c:57:
/tmp/nix-build-cuneiform-1.1.0.drv-0/cuneiform-linux-1.1.0/cuneiform_src/Kern/rblock/../hhh/tigerh/h/strings.h:113:12: error: unknown type name 'uchar'
            uchar     language; // Pit 02-??-94
            ^~~~~
/tmp/nix-build-cuneiform-1.1.0.drv-0/cuneiform-linux-1.1.0/cuneiform_src/Kern/rblock/../hhh/tigerh/h/strings.h:122:12: error: unknown type name 'uint16_t'
            uint16_t     wFirst;
            ^~~~~~~~
/tmp/nix-build-cuneiform-1.1.0.drv-0/cuneiform-linux-1.1.0/cuneiform_src/Kern/rblock/../hhh/tigerh/h/strings.h:123:12: error: unknown type name 'uint16_t'
            uint16_t     wLast;
            ^~~~~~~~
/tmp/nix-build-cuneiform-1.1.0.drv-0/cuneiform-linux-1.1.0/cuneiform_src/Kern/rblock/../hhh/tigerh/h/strings.h:150:8: error: unknown type name 'Bool'
 extern Bool bNeedFreeString;
        ^~~~
make[2]: *** [cuneiform_src/Kern/rblock/CMakeFiles/rblock.dir/build.make:111: cuneiform_src/Kern/rblock/CMakeFiles/rblock.dir/sources/new_c/_debug.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2278: cuneiform_src/Kern/rblock/CMakeFiles/rblock.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
builder for ‘/nix/store/cq22hrpylyihbzvrbsy4kcr0la0arlzr-cuneiform-1.1.0.drv’ failed with exit code 2
building path(s) ‘/nix/store/0n1d63hzvkgb0kignprjph6vqw9jl4j0-fontconfig-etc’
cannot build derivation ‘/nix/store/pynwkf620nv611gkqvy665p4mqcizakc-pdfForts-git.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/s8rnnqndfyh10qn9clw31bx0kx8y08xh-php.ini’
building path(s) ‘/nix/store/p9hdfhq2hazbw7h7ljk33b6r5bm2l1mr-pluginsdk_3.1.1.1.zip’
building path(s) ‘/nix/store/qlgf6pkbxgmxzxpqzvmvf19ra85cw0vc-privoxy.conf’
building path(s) ‘/nix/store/nddql4m810ngwhjbw6h623laazdzfj0d-keymap’
cannot build derivation ‘/nix/store/p0f528sm5n8aa3s38z25xyq18ijpa157-system-path.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/7bjfk3ly9ldh8lxiylcxd3wjssvnhzzl-torrc’
building path(s) ‘/nix/store/krcm1hydqvdrvw0qn8wn3g62jyrzrfh4-torsocks.conf’
building path(s) ‘/nix/store/as0kmy0fqxslcrqkrvffl29yrxd6ngfb-udev-rules’
cannot build derivation ‘/nix/store/jl16c99casv7vvd5f25kcpvpryvh62gn-nixos-system-subi-18.03pre119946.b8abd97c3b.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/jl16c99casv7vvd5f25kcpvpryvh62gn-nixos-system-subi-18.03pre119946.b8abd97c3b.drv’ failed
```

**Closed** 2017-12-23 17:03 UTC
