### ISSUE TITLE
libpipeline fails to build on OSX

### ISSUE THREAD

**Issue by gilligan** [NixOS/nixpkgs#15694] opened 2016-05-25 13:11 UTC
## Issue description
libpipeline fails to build on OSX with nixpkgs/master

```
make[2]: Entering directory '/private/var/folders/l7/bqwl4z8s45l_tk_406_bwjm40000gn/T/nix-build-libpipeline-1.4.1.drv-0/libpipeline-1.4.1/lib'
  CC       libpipeline_la-appendstr.lo
  CC       libpipeline_la-debug.lo
  CC       libpipeline_la-pipeline.lo
  CCLD     libpipeline.la
warning: /nix/store/avllgxhrpfg44i8sxmcxlc428fiw1cai-cctools-binutils-darwin/bin/nm: no name list
warning: /nix/store/avllgxhrpfg44i8sxmcxlc428fiw1cai-cctools-binutils-darwin/bin/nm: no name list
warning: /nix/store/avllgxhrpfg44i8sxmcxlc428fiw1cai-cctools-binutils-darwin/bin/nm: no name list
warning: /nix/store/avllgxhrpfg44i8sxmcxlc428fiw1cai-cctools-binutils-darwin/bin/nm: no name list
warning: /nix/store/avllgxhrpfg44i8sxmcxlc428fiw1cai-cctools-binutils-darwin/bin/nm: no name list
Undefined symbols for architecture x86_64:
  "_program_name", referenced from:
      _error in libgnu.a(error.o)
      _error_at_line in libgnu.a(error.o)
ld: symbol(s) not found for architecture x86_64
clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:1175: recipe for target 'libpipeline.la' failed
make[2]: *** [libpipeline.la] Error 1
make[2]: Leaving directory '/private/var/folders/l7/bqwl4z8s45l_tk_406_bwjm40000gn/T/nix-build-libpipeline-1.4.1.drv-0/libpipeline-1.4.1/lib'
Makefile:1172: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/private/var/folders/l7/bqwl4z8s45l_tk_406_bwjm40000gn/T/nix-build-libpipeline-1.4.1.drv-0/libpipeline-1.4.1'
Makefile:1104: recipe for target 'all' failed
make: *** [all] Error 2
builder for ‘/nix/store/rsnm4w0gdkwyw6y3xwzf77v5iiszqhl3-libpipeline-1.4.1.drv’ failed with exit code 2
error: build of ‘/nix/store/rsnm4w0gdkwyw6y3xwzf77v5iiszqhl3-libpipeline-1.4.1.drv’ failed
/Users/tpflug/.nix-profile/bin/nix-shell: failed to build all dependencies
```

### Steps to reproduce
$ nix-shell -p libpipeline

## Technical details
* System: OSX
* Nix version: 1.11.2
* Nixpkgs version: 16.09pre-git

**Comment by gilligan** [comment] 2016-05-25 13:45
I found some reference here: http://stackoverflow.com/questions/36824434/libpipeline-fails-to-compile-on-mac-os-x

The steps with the modified CFLAGS and creating windows.h with the described contents actually works but obviously `windows.h` should not be included in the first place so something is weird.

**Comment by gilligan** [comment] 2016-05-26 09:09
Also what I don't understand is: where does the error actually come from? libpipeline has not changed in a while. Don't understand why this is suddenly failing for me now.

**Comment by matthewbauer** [comment] 2016-05-29 22:46
We should be able to close this? @gilligan

**Closed** 2016-05-30 06:10 UTC
Labels: 0.kind: bug, 6.topic: darwin

**Comment by copumpkin** [comment] 2016-05-30 23:56
I ran a bisect and found that this was caused by @vcunat's commit b9df4311dc1f50253ec86be6b7908fa620070ffd which switched the default `man` provider to `man-db`, which I'm guessing has never worked on darwin. For now I'd like to switch it back. Any objections? I'm also not convinced that @gilligan's patch for `libpipeline` is the right approach, since it seems like a bug in `gnulib`. Unfortunately, these packages seem to all bundle gnulib in their source, so we can't just patch it in a single place, but I would ideally like to aim for a reusable patch.

**Comment by matthewbauer** [comment] 2016-05-31 00:32
man-db actually did build in Darwin in nixpkgs@42358f0 but I think it broke when they upgraded gnulib (see http://git.savannah.gnu.org/cgit/man-db.git/commit/?id=9396caadc5dbb98f7a0932952be15cff8f3428d2)

**Comment by copumpkin** [comment] 2016-05-31 02:19
Yeah, so I think we'll have to apply something like [this patch (which was never accepted upstream)](https://lists.gnu.org/archive/html/bug-gnulib/2015-02/msg00079.html) to anything that uses gnulib, and ideally lobby to fix it upstream. Anyone wanna email the list and see if they can revive interest?
