### ISSUE TITLE
Owncloudclient build is failing on 16.03

### ISSUE THREAD

**Issue by r-raymond** [NixOS/nixpkgs#17016] opened 2016-07-16 18:05 UTC
## Issue description
The package `owncloudclient` fails to compile.

### Steps to reproduce
Add `owncloudclient` to `configure.nix` and do a `nixos-rebuild`.

## Technical details
The package fails with

`/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c:45:26: error: ISO C does not support '__FUNCTION__' `

The issue is that gcc 5 complains about the nonstandard `__FUNCTION__.` This issue can be fixed by replacing `__FUNCTION__` with `__func__`.

There exists a patch on [Archlinux](http://www.mailbrowse.com/archlinux-arch-commits/281592.html) (rev 134339, owncloud-client/trunk/gcc-5.patch)

* System: (NixOS: 16.03)
* Nix version: 1.11.2
* Nixpkgs version: 16.03.973.8bf31d7

**Comment by joachifm** [comment] 2016-07-16 18:45
cc maintainer @qknight. It might be sufficient to bump the package to the latest version.

**Comment by 0xABAB** [comment] 2016-07-16 20:52
I think shows another weakness in Nix build infrastructure. IMHO, how this should work is that such ISO C warnings (which have existed for longer than gcc 5) should be detected and then there should be an automated fall back to a previous version of gcc. 

This way such incompatibilities would *not* be found by users, but instead by the developers of the up stream project. 

I.e., Nix current model assumes that upstream projects write heavingly perfect code, while in fact a lot of open-source is written by amateurs who don't know any better. 

As such I propose that by default we should have an automated fallback like above enabled. There could be a flag saying "I only want to compile with the latest compiler", but that would be for the geeky paranoid users in the community.

**Comment by r-raymond** [comment] 2016-07-16 21:40
IMHO packages should not be distributed to compile with `-Werror`, which is really a development tool.

**Comment by joachifm** [comment] 2016-07-16 22:02
The cc wrapper script could be extended to filter out `-Werror`. In the meantime, one possibility is to specify `NIX_CFLAGS_COMPILE = "-Wno-error=pedantic"` and so on as necessary, or explicitly set the `std` assumed by upstream (as I recall, lots of failures during the GCC5 transition were simply due to the change in the default `std`, which turned previously valid/accepted code into warnings/errors).

That said, depending on the error, we might *want* the build to fail if upstream is incapable of releasing code that passes their own warning levels ...

**Comment by qknight** [comment] 2016-07-17 09:40
@0xABAB this so said weakness is persistent in all linux deployments and not specific to nix. if the targets don't provide a unit-test, and we do have the `checkPhase` then we can't know if the software in question works.

also in regards to `GCC` fallback automation, hydra makes it pretty easy to compare previous builds to newer builds with changed dependencies. also it makes it easy to reproduce the build locally. but currently i don't know if there is any library making use of this knowledge, and i think it is mainly used manually ATM. 

that said, it would be nice to have a library to access the hydra results from nix-build and build-logs.

**Comment by qknight** [comment] 2016-07-17 09:47
@joachifm bumping to the latest owncloudclient sounds good.

**Comment by vcunat** [comment] 2016-07-17 15:03
> The cc wrapper script could be extended to filter out -Werror.

Adding more of such magic might be confusing, and we would have to ensure this does *not* happen outside "standard nixpkgs builds", e.g. when run by user by hand or in a nix-shell.

**Comment by r-raymond** [comment] 2016-07-28 14:29
I researched the problem a little and it turns out that on `nixos-16.03` the provided owncloud-client version is `1.7.1` released in Dec '14. Cherrypicking the commit `64585c24e1768ba0d0cc43043bd51de5512fe15e` (which updates `1.7.1` to `2.1.1`) fixes the problem.

However I don't know if this change is acceptable for 16.03 stable.

**Comment by joachifm** [comment] 2016-07-28 17:18
@r-raymond please open a PR against the release branch; my understanding is that the maintainer would be happy to accept a version bump to fix the problem.

**Comment by bjornfor** [comment] 2016-09-05 06:15
Fixed with https://github.com/NixOS/nixpkgs/commit/6a4afcded09bb1a0431d1e4568d12abc187ab64e.

**Closed by bjornfor** 2016-09-05 06:15 UTC
Labels: 9.needs: port to stable
