### ISSUE TITLE
Packaged Kate doesn't include Nix syntax highlighting

### ISSUE THREAD

**Issue by NoraCodes** [NixOS/nixpkgs#161537] opened 2022-02-23 15:05 UTC
### Describe the bug
While KDE's Kate text editor does support syntax highlighting for the Nix language, the version of Kate available in NixOS associates `.nix` files with Bash.

### Steps To Reproduce
1. Open Kate
2. Open a `.nix` Nix language file
3. Observe incorrect syntax highlighting and, if the LSP client is enabled, an error about a failure to launch the Bash language server.

### Expected behavior
Kate installed through NixOS should probably work out of the box with the Nix language. 

### Additional context
The syntax file for Nix is here: https://kate-editor.org/syntax/data/syntax/nix.xml

### Notify maintainers
@ttuegel 

### Metadata

```console
[nora@calembel:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.96, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.336103.40ef692a55b"`
 - channels(nora): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by hqurve** [comment] 2022-02-23 22:32
Nix syntax highlight support was added to kdeframeworks in 5.88 (https://kde.org/announcements/frameworks/5/5.88.0/) however, nixos-21.11 uses frameworks 5.87. According to the help center in kate, you can add custom highlighting by placing the file in`$HOME/.local/share/org.kde.syntax-highlighting/syntax/` [(online source)](https://docs.kde.org/stable5/en/kate/katepart/highlight.html#katehighlight-xml-format)

**Comment by tpwrules** [comment] 2023-03-22 00:16
Confirmed this is fixed on the unstable channel, presumably because that component was upgraded.

**Closed by tpwrules** 2023-03-22 00:16 UTC
Labels: 0.kind: bug
