### ISSUE TITLE
Gnome 3.20 Limited User Management Functionality

### ISSUE THREAD

**Issue by bfrog** [NixOS/nixpkgs#17646] opened 2016-08-10 20:22 UTC
## Issue description

Unable to set a users picture or name in the gnome settings users page
### Steps to reproduce

Install gnome 3.20, try to change a users display name or picture
## Technical details
- System: 16.09pre88063.43da8b1 (Flounder)
- Nix version: 1.11.2
- Nixpkgs version: "16.09pre88063.43da8b1"

**Comment by bfrog** [comment] 2016-08-11 00:50
The picture can't be changed because of this error

```
(gnome-control-center:16443): AccountsService-WARNING **: SetIconFile call failed: GDBus.Error:org.freedesktop.Accounts.Error.Failed: reading file '/nix/store/bgf5b30jxd4czq4cgsz8hb78p4v9nh0h-gnome-control-center-3.18.2/share/pixmaps/faces/energy-arc.jpg' failed: Failed to execute child process "/bin/cat" (No such file or directory)
```

**Comment by bfrog** [comment] 2016-08-11 00:51
User name change failed because of this error

```
(gnome-control-center:16443): AccountsService-WARNING **: SetRealName call failed: GDBus.Error:org.freedesktop.Accounts.Error.Failed: running '/usr/sbin/usermod' failed: Failed to execute child process "/usr/sbin/usermod" (No such file or directory)
```

**Comment by abbradar** [comment] 2016-08-11 10:09
I imagine fixing this would require sed-patching AccountService sources to fix those paths.

cc @lethalman

**Comment by jtojnar** [comment] 2017-09-30 15:31
Duplicate of #10025

**Closed** 2017-09-30 23:20 UTC
Labels: 0.kind: bug, 6.topic: gnome3, 6.topic: nixos
