### ISSUE TITLE
amdgpu-pro fails to build

### ISSUE THREAD

**Issue by simendsjo** [NixOS/nixpkgs#20390] opened 2016-11-13 17:58 UTC
## Issue description

There are both errors and warnings while compiling

```
make flags: SHELL=/nix/store/28wl3f34vfjpw0y5809bgr6382wqdscf-bash-4.3-p48/bin/bash -C /nix/store/fpix87xkclr4ywd47r84i3jhwdq7ccx3-linux-4.8.7-dev/lib/modules/4.8.7/build modules M=/tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407   
make: Entering directory '/nix/store/fpix87xkclr4ywd47r84i3jhwdq7ccx3-linux-4.8.7-dev/lib/modules/4.8.7/build'
  CC [M]  /tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/amdgpu_drv.o
  CC [M]  /tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/amdgpu_device.o
  CC [M]  /tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/amdgpu_kms.o
  CC [M]  /tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/amdgpu_atombios.o
  CC [M]  /tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/atombios_crtc.o
  CC [M]  /tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/amdgpu_connectors.o
  CC [M]  /tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/atom.o
  CC [M]  /tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/amdgpu_fence.o
  CC [M]  /tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/amdgpu_ttm.o
/tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/amdgpu_ttm.c: In function 'amdgpu_move_blit':
/tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/amdgpu_ttm.c:291:18: error: incompatible type for argument 4 of 'ttm_bo_move_accel_cleanup'
           evict, no_wait_gpu, new_mem);
                  ^
In file included from /tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/../backport/include/kcl/kcl_ttm.h:6:0,
                 from /tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/../backport/backport.h:9,
                 from <command-line>:0:
/nix/store/fpix87xkclr4ywd47r84i3jhwdq7ccx3-linux-4.8.7-dev/lib/modules/4.8.7/source/include/drm/ttm/ttm_bo_driver.h:1032:12: note: expected 'struct ttm_mem_reg *' but argument is of type 'bool {aka _Bool}'
 extern int ttm_bo_move_accel_cleanup(struct ttm_buffer_object *bo,
            ^
/tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/amdgpu_ttm.c:290:6: error: too many arguments to function 'ttm_bo_move_accel_cleanup'
  r = ttm_bo_move_accel_cleanup(bo, fence,
      ^
In file included from /tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/../backport/include/kcl/kcl_ttm.h:6:0,
                 from /tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/../backport/backport.h:9,
                 from <command-line>:0:
/nix/store/fpix87xkclr4ywd47r84i3jhwdq7ccx3-linux-4.8.7-dev/lib/modules/4.8.7/source/include/drm/ttm/ttm_bo_driver.h:1032:12: note: declared here
 extern int ttm_bo_move_accel_cleanup(struct ttm_buffer_object *bo,
            ^
/tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/amdgpu_ttm.c: In function 'amdgpu_move_vram_ram':
/tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/amdgpu_ttm.c:337:6: error: too few arguments to function 'ttm_bo_move_ttm'
  r = ttm_bo_move_ttm(bo, true, no_wait_gpu, new_mem);
      ^
In file included from /tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/../backport/include/kcl/kcl_ttm.h:6:0,
                 from /tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/../backport/backport.h:9,
                 from <command-line>:0:
/nix/store/fpix87xkclr4ywd47r84i3jhwdq7ccx3-linux-4.8.7-dev/lib/modules/4.8.7/source/include/drm/ttm/ttm_bo_driver.h:979:12: note: declared here
 extern int ttm_bo_move_ttm(struct ttm_buffer_object *bo,
            ^
/tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/amdgpu_ttm.c: In function 'amdgpu_move_ram_vram':
/tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/amdgpu_ttm.c:370:2: error: the address of 'tmp_mem' will always evaluate as 'true' [-Werror=address]
  r = ttm_bo_move_ttm(bo, true, no_wait_gpu, &tmp_mem);
  ^
/tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/amdgpu_ttm.c:370:6: error: too few arguments to function 'ttm_bo_move_ttm'
  r = ttm_bo_move_ttm(bo, true, no_wait_gpu, &tmp_mem);
      ^
In file included from /tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/../backport/include/kcl/kcl_ttm.h:6:0,
                 from /tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/../backport/backport.h:9,
                 from <command-line>:0:
/nix/store/fpix87xkclr4ywd47r84i3jhwdq7ccx3-linux-4.8.7-dev/lib/modules/4.8.7/source/include/drm/ttm/ttm_bo_driver.h:979:12: note: declared here
 extern int ttm_bo_move_ttm(struct ttm_buffer_object *bo,
            ^
/tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/amdgpu_ttm.c: In function 'amdgpu_bo_move':
/tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/amdgpu_ttm.c:432:7: error: too few arguments to function 'ttm_bo_move_memcpy'
   r = ttm_bo_move_memcpy(bo, evict, no_wait_gpu, new_mem);
       ^
In file included from /tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/../backport/include/kcl/kcl_ttm.h:6:0,
                 from /tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/../backport/backport.h:9,
                 from <command-line>:0:
/nix/store/fpix87xkclr4ywd47r84i3jhwdq7ccx3-linux-4.8.7-dev/lib/modules/4.8.7/source/include/drm/ttm/ttm_bo_driver.h:1002:12: note: declared here
 extern int ttm_bo_move_memcpy(struct ttm_buffer_object *bo,
            ^
cc1: all warnings being treated as errors
make[4]: *** [/nix/store/fpix87xkclr4ywd47r84i3jhwdq7ccx3-linux-4.8.7-dev/lib/modules/4.8.7/source/scripts/Makefile.build:290: /tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu/amdgpu_ttm.o] Error 1
make[3]: *** [/nix/store/fpix87xkclr4ywd47r84i3jhwdq7ccx3-linux-4.8.7-dev/lib/modules/4.8.7/source/scripts/Makefile.build:440: /tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407/amd/amdgpu] Error 2
make[2]: *** [/nix/store/fpix87xkclr4ywd47r84i3jhwdq7ccx3-linux-4.8.7-dev/lib/modules/4.8.7/source/Makefile:1471: _module_/tmp/nix-build-amdgpu-pro-16.30-4.8.7.drv-0/amdgpu-pro-driver/root/usr/src/amdgpu-pro-16.30.3-315407] Error 2
make[1]: *** [Makefile:150: sub-make] Error 2
make: *** [Makefile:24: __sub-make] Error 2
make: Leaving directory '/nix/store/fpix87xkclr4ywd47r84i3jhwdq7ccx3-linux-4.8.7-dev/lib/modules/4.8.7/build'
builder for ‘/nix/store/ynm7qary3vggw9d46rr7h6iadrqd1yl4-amdgpu-pro-16.30-4.8.7.drv’ failed with exit code 2
```

### Steps to reproduce

Set `services.xserver.videoDrivers = [ "amdgpu-pro" ];`

## Technical details

* System: 16.09.1024.c859ea0 (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "16.09.1024.c859ea0"

**Comment by vcunat** [comment] 2016-11-13 18:46
I think AMD tends to lag with support of newest kernel branches; I expect it would work with older kernels. /cc maintainer @corngood.

**Comment by corngood** [comment] 2016-11-13 21:45
Amdgpu-pro 16.40 was merged in https://github.com/NixOS/nixpkgs/pull/19936.

I tested it today with 4.8.6.

**Comment by simendsjo** [comment] 2016-11-14 20:44
I'm not sure how the branching works. Will this be added to the `release-16.09` branch (which is what I'm using I believe)? I'm actually just hoping this will fix the flickering bugs I'm seeing.

**Comment by vcunat** [comment] 2016-11-14 20:51
Well, it's a decision to make. Changes are hand-picked for the release branch and IMO this isn't a completely clear case.

**Comment by Mounium** [comment] 2017-12-03 13:15
I'm not sure if the problem is related but amdgpu-pro still doesn't build on current master: 

`glamor_picture.c: In function '_glamor_upload_bits_to_pixmap_texture':
../include/os.h:78:32: error: implicit declaration of function 'reallocarray' [-Werror=implicit-function-declaration]
 #define xallocarray(num, size) reallocarray(NULL, (num), (size))
                                ^
glamor_picture.c:621:26: note: in expansion of macro 'xallocarray'
         converted_bits = xallocarray(h, stride);
                          ^~~~~~~~~~~
glamor_picture.c:621:9: warning: nested extern declaration of 'reallocarray' [-Wnested-externs]
         converted_bits = xallocarray(h, stride);
         ^~~~~~~~~~~~~~
glamor_picture.c:621:24: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         converted_bits = xallocarray(h, stride);
                        ^
glamor_picture.c: In function 'glamor_upload_sub_pixmap_to_texture':
glamor_picture.c:836:18: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         sub_bits = xallocarray(h, stride);
                  ^
  CC       glamor_pixmap.lo
cc1: some warnings being treated as errors
make[1]: *** [Makefile:723: glamor_picture.lo] Error 1
make[1]: Leaving directory '/tmp/nix-build-xwayland-1.18.4.drv-0/xorg-server-1.18.4/glamor'
make: *** [Makefile:771: all-recursive] Error 1
builder for ‘/nix/store/1zn4hl5xqz58q9na4krlrdb94gqj1rk4-xwayland-1.18.4.drv’ failed with exit code 2`

**Comment by vcunat** [comment] 2017-12-03 13:45
I don't think that's current master.  `xwayland` is a different version now, and it [does build on Hydra](https://hydra.nixos.org/job/nixpkgs/trunk/xwayland.x86_64-linux).

**Comment by vcunat** [comment] 2017-12-03 13:47
I believe `amdgpu-pro` builds on both maintained branches now, and the issue would be different anyway...

**Closed by vcunat** 2017-12-03 13:47 UTC
Labels: 0.kind: bug, 9.needs: reporter feedback

**Comment by vcunat** [comment] 2017-12-03 15:24
Oh, I forgot that `amdgpu-pro` forces older server branch.  It builds on master _now_ (e001bd2c).
