### ISSUE TITLE
Package request: ente-auth

### ISSUE THREAD

**Issue by universish** [NixOS/nixpkgs#350357] opened 2024-10-21 21:56 UTC
Ente Auth

Authenticator App

It is the only authenticator program that works on all desktop and mobile platforms. It is a very useful application as it works on all operating systems and all platforms, and also works on the web. Moreover, since the database is in the cloud, there is no need to back up or restore from backup.

* homepage URL: https://ente.io/auth/
* source URL: https://github.com/ente-io/ente/tree/main/auth
* download URL: https://github.com/ente-io/ente/releases?q=tag%3Aauth-v4
* license: AGPL3
* platforms: gnu-linux, gnu-linux libre, flathub, net (ms's), darwin (apple's), android, web
* distribution format of software: appimage, flatpak, rpm, deb, pacman, dmg, exe, apk
* OSs: GNU/Linux distros, GNU/Linux Libre distros, Windows, MacOS, iOS, android OS (f-droid and play store), web

**Comment by dotlambda** [comment] 2024-10-21 22:04
duplicate of https://github.com/NixOS/nixpkgs/issues/336291

**Closed by dotlambda** 2024-10-21 22:04 UTC
Labels: 0.kind: packaging request
