### ISSUE TITLE
Packaging request: sway-borders

### ISSUE THREAD

**Issue by sei40kr** [NixOS/nixpkgs#163191] opened 2022-03-07 18:03 UTC
**Project description**

Fork of sway with some extra features, mainly related to borders.

**Metadata**

* homepage URL:
* source URL: https://github.com/fluix-dev/sway-borders
* license: mit
* platforms: linux

**Comment by ModdedGamers** [comment] 2022-03-08 14:25
I don't think that this is good to package, as there hasn't been a stable release of this in nearly 2 years, and as the maintainer said [here](https://github.com/fluix-dev/sway-borders/issues/35#issuecomment-855308869),
> However, I just haven't been too happy with this fork. It... _works_ (and I use it daily of course), but there's still some bugs and my intention is to redo most of the work in a way that also allows new features. 
Therefore, I think it's better to wait this one out.

**Comment by abathur** [comment] 2022-08-07 15:00
Closing since this appears to be a duplicate of:
- #134334

Happy to reopen if there's a distinction I'm missing.

**Closed by abathur** 2022-08-07 15:00 UTC
Labels: 0.kind: packaging request
