### ISSUE TITLE
JDownloader packaging request.

### ISSUE THREAD

**Issue by aarzoo8810** [NixOS/nixpkgs#186299] opened 2022-08-12 15:03 UTC
**Project description**: 

JDownloader is a free, [open-source](https://support.jdownloader.org/Knowledgebase/Article/View/setup-ide-eclipse) download management tool with a [huge community](https://board.jdownloader.org/) that makes downloading as easy and fast as it should be. Users can start, stop or pause downloads, set bandwith limitations, auto-extract archives and much more. It's an easy-to-extend framework that can save hours of your valuable time every day!
_describe the project a little_

**Metadata**

* homepage URL: https://jdownloader.org/
* source URL:  https://support.jdownloader.org/Knowledgebase/Article/View/setup-ide-eclipse
* license: 
* platforms: linux, windows,

**Comment by pinn3** [comment] 2022-08-13 16:01
Duplicate of https://github.com/NixOS/nixpkgs/issues/41321

**Closed** 2022-08-13 23:09 UTC
Labels: 0.kind: packaging request
