### ISSUE TITLE
Tracking issue: ensure `strictDeps = true`

### ISSUE THREAD

**Issue by AndersonTorres** [NixOS/nixpkgs#279658] opened 2024-01-08 19:25 UTC
Among other confusing corners of Nixpkgs is that `strictDeps` attribute.

I believe we should set it to true always when possible and explain why it needed to be set as false.

However I have few to no experience on Nixpkgs internals.

**Comment by roberth** [comment] 2024-01-08 23:02
- Duplicate of #178468

**Comment by AndersonTorres** [comment] 2024-01-09 08:20
Good to know.
I didn't find it on search.

Closing.

**Closed** 2024-01-09 08:21 UTC
Labels: 0.kind: enhancement
