### ISSUE TITLE
20.03 Installer: Manual opens in Editor

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#86095] opened 2020-04-27 03:53 UTC
**Describe the bug**

On the 20.03 graphical installer livesystem, the manual on desktop or "View NixOS documentation in a web browser" item from menu actually open the manual source code in Kate (editor)!

This is a horrible first impression of NixOS and many people will probably newer try it again. So fix this ASAP!

And add a test, so it will not happen again after that.

**To Reproduce**
1. download latest graphical iso
2. boot it
3. click manual on desktop

**Expected behavior**
manual opens in browser

**Screenshots**
![Screenshot from 2020-04-27 05-29-31](https://user-images.githubusercontent.com/91113/80331840-754a1180-8849-11ea-8e21-6c287f5498bc.png)

**Additional context**
I heard that experience from a friend and also read about it on twitter.

>#NixOS first impressions:
after you click on "NixOS Manual" on the desktop,
a nixos-manual-html/share/doc/nixos/index.html will open in a notepad.exe equivalent
>
>this is the most authentic linux experience i had since random update removed the luxury of have GUI on manjaro

https://twitter.com/dym_sh/status/1253813769114923008

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.35, NixOS, 20.03.1577.74a80c5a9ab (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1577.74a80c5a9ab"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Xel** [comment] 2020-04-27 10:21
I just came here to report the same. Can reproduce

**Comment by worldofpeace** [comment] 2020-04-27 16:20
@davidak I've read the same thing on hackernews, rather annoying.

**Comment by worldofpeace** [comment] 2020-04-27 17:10
See https://github.com/NixOS/nixpkgs/issues/86137 for my investigation.
This issue is triggered because in 20.03 we use nixos's nixos-manual.desktop, and before we made a manual desktop item that forced to open firefox.

**Comment by worldofpeace** [comment] 2020-04-28 18:12
This should be fixed by https://github.com/NixOS/nixpkgs/pull/86147

**Closed by worldofpeace** 2020-04-28 18:12 UTC
Labels: 0.kind: bug, 1.severity: blocker, 6.topic: nixos

**Comment by arianvp** [comment] 2020-04-29 11:27
Relatedly since switching to NixOS 20.03  Gnome insists on opening HTML files with the Signal Desktop application and I have no idea how to convince it otherwise. Signal has nothing to do with HTML either.

**Comment by Git-Balance** [comment] 2024-11-10 19:32
I recently had the same issue, only the NixOS Manual opened is Calibre. [This discussion](https://discourse.nixos.org/t/nixos-manual-on-desktop-doesnt-launch-correctly/33869) fixed the problem, and allowed the manual to open in Firefox.
