### ISSUE TITLE
DLL missing in game running through Proton on Steam, possible NixOS wrapper issue?

### ISSUE THREAD

**Issue by jmc-figueira** [NixOS/nixpkgs#150319] opened 2021-12-11 22:24 UTC
### Describe the bug
The game Killing Floor 2 (with the Steam AppID 232090) fails to run through Proton Experimental on NixOS unstable (22.05pre337103.581d2d6c9cd), as described in https://github.com/ValveSoftware/Proton/issues/1328#issuecomment-991394264.

Weirdness with (apparently falsely reported) `ulimit` values, as reported by the provided log file, as well as the documentation in the wiki suggesting some libraries may need to be linked manually for some games leads me to believe it is a NixOS-specific issue, although I have not been able to confirm further.

### Steps To Reproduce
1. Install Steam by setting `programs.steam.enable = true`
2. Install Killing Floor 2 through Steam, using Proton Experimental and the Soldier runtime
3. Experience the error message "BugSplatRC resource DLL not found" after the game's splash screen, with subsequent crash

### Expected behavior
The game should run normally, as it is reported to be runnable through Proton, with a Platinum score on [ProtonDB](https://www.protondb.com/app/232090).

### Screenshots
![image](https://user-images.githubusercontent.com/6634716/145693385-5d04fcd9-377e-43e7-b757-92e54022af12.png)

### Additional context
Compressed log by running the game with `PROTON_LOG=1`: [steam-232090.zip](https://github.com/NixOS/nixpkgs/files/7697823/steam-232090.zip)

### Notify maintainers

@jagajaga @jonringer 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.6, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.0pre20211206_d1aaa7e`
 - channels(root): `"home-manager, nixos-22.05pre337103.581d2d6c9cd"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by YellowOnion** [comment] 2021-12-12 07:10
I have KF2 I'll try reproduce tomorrow.

**Comment by SuperSamus** [comment] 2022-11-03 11:22
Is this still an issue? (I don't own the game)

**Comment by Atemu** [comment] 2022-11-13 06:26
Me neither but since there is no more interest in this issue, I'll close it for now.

Please reopen this if it still doesn't work.

**Closed by Atemu** 2022-11-13 06:26 UTC
Labels: 0.kind: bug
