### ISSUE TITLE
ROS2 Humble

### ISSUE THREAD

**Issue by realsnick** [NixOS/nixpkgs#190619] opened 2022-09-10 03:24 UTC
The Robot Operating System, is a meta operating system for robots.

* homepage URL: https://ros.org/
* source URL: https://github.com/ros2 
* license: Creative Commons Attribution 4.0 International
* platforms: linux

**Comment by jtojnar** [comment] 2022-09-10 17:59
Duplicate of https://github.com/NixOS/nixpkgs/issues/11713. And it should be available in https://github.com/lopsided98/nix-ros-overlay.

**Comment by ibootstrapper** [comment] 2022-09-10 18:28
Thank you

**Closed** 2024-02-01 23:33 UTC
Labels: 0.kind: packaging request
