### ISSUE TITLE
python3.7-apsw fails tests on 20.03

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#90097] opened 2020-06-10 21:45 UTC
**Describe the bug**
The tests for python3.7-apsw fails on 20.03. This breaks `weechat-matrix` for me.

**To Reproduce**
1. `nix-build -A python3Packages.apsw`

**Additional context**
```
/nix/store/wpr0wiflmp7q738kykaz0nzhcwzzwpai-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/setuptools/dist.py:476: UserWarning: Normalizing '3.30.1-r1' to '3.30.1.post1'
  normalized_version,
running test
                Python /nix/store/izgnj066l940pn1gy3zg3m2mpp7lh21a-python3-3.7.6/bin/python3.7 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
Testing with APSW file /nix/store/vz0fg0vrfgb2xiqjh9fkwp85p53syi6a-python3.7-apsw-3.30.1-r1/lib/python3.7/site-packages/apsw.cpython-37m-x86_64-linux-gnu.so
          APSW version 3.30.1-r1
    SQLite lib version 3.32.2
SQLite headers version 3032002
    Using amalgamation False
.............................................................F.........................
======================================================================
FAIL: testScalarFunctions (tests.APSW)
Verify scalar functions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests.py", line 1325, in testScalarFunctions
    self.assertEqual(c.execute("select deterministic()=deterministic()").fetchall()[0][0], 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 87 tests in 100.179s

FAILED (failures=1)
builder for '/nix/store/y1f81nk5170gayb3gjmxr95js3yd7bpj-python3.7-apsw-3.30.1-r1.drv' failed with exit code 1
```

**Notify maintainers**

No maintainer for package :(

**Metadata**
release-20.03 @ 20.03-713-gd3bfabe7b5b

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python3Packages.apsw
# a list of nixos modules affected by the problem
module:
```

**Comment by priegger** [comment] 2020-06-12 14:40
I had a quick look at this. What I found so far:

The issue was discussed on the sqlite forum (https://sqlite.org/forum/forumpost/552e8e236a) and a fix was committed in apsw 16 days ago (https://github.com/rogerbinns/apsw/commit/e19b2f2ac49d5daa7c6e0bde54441d0fa417ec7c#diff-f4bc68ff01eef7bed2f3a64cad7d37ca). The latest release (3.32.2-r1) contains the fix.

**Comment by FRidh** [comment] 2020-06-12 20:26
Right. That update will land in `staging` soon (2f72c426e19b07915e706e2c615e07ea72e9d7e4) and then eventually in `master`. I suppose in this case we could backport it as well.

**Comment by kuznero** [comment] 2020-06-12 20:27
For me it breaks Calibre on current release.

**Comment by FRidh** [comment] 2020-06-12 20:33
OK I've pushed db31e48c5c8d99dcaf4e5883a96181f6ac4ad6f6 to release-20.03. It should land in the channel soon.

**Closed by FRidh** 2020-06-12 20:33 UTC
Labels: 0.kind: bug, 6.topic: python, 9.needs: port to stable

**Comment by priegger** [comment] 2020-06-12 20:40
@FRidh: I was also trying this, I did not know about the fix in python-unstable. I think the apsw version needs to be in sync with sqlite, so w eneed 3.31 or an sqlite version bump.

**Comment by FRidh** [comment] 2020-06-12 20:41
apsw tests don't fail so I "trust" that it works

**Comment by priegger** [comment] 2020-06-12 20:46
@FRidh: I had compile errors (missing symbols) with reverse dependencies of apsw. I'll see if I can reproduce it with current release-20.03.

**Comment by teto** [comment] 2020-06-12 21:08
was looking at this right now since aspw broke buku, I check against staging and master for an aspw update but didn't think of the python-update damn ! aspw 3.32 effectively requires sqlite 3.32 otherwise tests fail.

**Comment by FRidh** [comment] 2020-06-13 07:01
sqlite is at 3.32.2 on 20.03, security update d68215db6fb2012ad8ff57fac0708a7e1b09100f
Yes, these version bumps are annoying.

**Comment by zeorin** [comment] 2020-06-13 15:16
I have this same problem with python2.7-apsw:
```
/nix/store/9w74pnr8vh69324g0xjbwlsgjz2gnrq1-python2.7-setuptools-44.0.0/lib/python2.7/site-packages/setuptools/dist.py:476: UserWarning: Normalizing '3.30.1-r1' to '3.30.1.post1'
  normalized_version,
running test
                Python /nix/store/xrfvivl9jbwjws6p1ahf6ixbhm6zn2x2-python-2.7.18/bin/python2.7 sys.version_info(major=2, minor=7, micro=18, releaselevel='final', serial=0)
Testing with APSW file /nix/store/2xd7bc156fjv44pig9im07jz063i6n4q-python2.7-apsw-3.30.1-r1/lib/python2.7/site-packages/apsw.so
          APSW version 3.30.1-r1
    SQLite lib version 3.32.2
SQLite headers version 3032002
    Using amalgamation False
.............................................................F.........................
======================================================================
FAIL: testScalarFunctions (tests.APSW)
Verify scalar functions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests.py", line 1325, in testScalarFunctions
    self.assertEqual(c.execute("select deterministic()=deterministic()").fetchall()[0][0], 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 87 tests in 118.127s

FAILED (failures=1)
builder for '/nix/store/nlhqm39177wxk9ll6072im7nm3haiv2b-python2.7-apsw-3.30.1-r1.drv' failed with exit code 1
cannot build derivation '/nix/store/w3g8z714bn22461w6rv25mkyr8x3a6zx-calibre-4.8.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/05r8kg4pjd921j09d4hgqi2g7s9md6xh-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/6gg7sjvfl084ai7xq5zhlj8flnz7bz4a-nixos-system-guru-20.03.2141.8b071be7512.drv': 1 dependencies couldn't be built
error: build of '/nix/store/6gg7sjvfl084ai7xq5zhlj8flnz7bz4a-nixos-system-guru-20.03.2141.8b071be7512.drv' failed
```
