### ISSUE TITLE
Package request: SpotiFlyer

### ISSUE THREAD

**Issue by YorQat** [NixOS/nixpkgs#232315] opened 2023-05-16 23:30 UTC
**Project description**

Kotlin Multiplatform Music Downloader ,supports Spotify, Youtube, Gaana, Jio-Saavn and SoundCloud.

**Metadata**

* homepage URL: https://github.com/Shabinder/SpotiFlyer
* source URL: https://github.com/Shabinder/SpotiFlyer
* license: gpl3
* platforms: unix, linux, darwin

**Comment by nim65s** [comment] 2023-06-23 13:45
This is a duplicate of #213630

**Closed by nim65s** 2023-06-23 13:45 UTC
Labels: 0.kind: packaging request
