### ISSUE TITLE
Trouble running waydroid

### ISSUE THREAD

**Issue by maralorn** [NixOS/nixpkgs#147596] opened 2021-11-27 13:57 UTC
### Describe the bug
My waydroid container is stuck in a crashing boot loop. 
`waydroid session start` outputs:
```
[14:45:39] Failed to add service waydroidusermonitor: -1
[14:45:39] Failed to add service waydroidclipboard: -1
```
And the logcat shows: https://gist.github.com/maralorn/6349368693468548a4f90b24938990ea (This get’s repeated about every 3 seconds.)

I a second terminal:
```
maralorn@zeus> waydroid show-full-ui
[14:56:20] Failed to get service waydroidplatform, trying again...
[14:56:21] Failed to get service waydroidplatform, trying again...
```

### Steps To Reproduce
1. Run `sudo rm -rf /var/lib/waydroid /home/.waydroid ~/waydroid ~/.share/waydroid ~/.local/share/applications/*aydroid* ~/.local/share/waydroid`.
2. I entered the following into my `configuration.nix`:
    ```
    boot.kernelPackages = pkgs.linuxPackages_xanmod;
    virtualisation.waydroid.enable = true;
    ```
3. `nixos-rebuild switch` and `reboot`.
4. Run `sudo waydroid init`
5. Run `sudo systemctl start waydroid-container`
6. Run `waydroid session start`.

### Expected behavior
The waydroid container to start successfully.

### Additional context
```
services.xserver.desktopManager.gnome.enable = true; # I run definitely on wayland.
boot.kernelParams = [ "amdgpu.cik_support=1" ];
boot.initrd.kernelModules = [ "amdgpu" ];
```
Channel: nixos-unstable, commit 73369f8d (from Nov 25).
`configuration.nix`: https://git.maralorn.de/nixos-config/tree/nixos/machines/zeus/configuration.nix

### Notify maintainers
@CajuM

### Metadata
```console
[maralorn@zeus:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.2-xanmod1-tt, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/etc/nix-path/nixpkgs`
```

**Comment by KouAkitaki** [comment] 2021-11-27 14:32
I'm observing the same issue. Attempting to start the waydroid session gives the following errors.

```
$ waydroid session start
[14:28:06] Failed to add service waydroidclipboard: -1
[14:28:06] Failed to add service waydroidusermonitor: -1
```

The setup is a little bit unusual here though, as it's on a NixOS guest running in virt-manager with virtio for 3d acceleration. The nixpkgs is also at 73369f8:

```
$ nix flake metadata
Resolved URL:  git+file:///etc/nixos
Locked URL:    git+file:///etc/nixos?ref=master&rev=1743b14ded01c066c9386f1a614c95dfe14bc86f
Description:   Experimental flakes NixOS config
Path:          /nix/store/bdz0n2zj79wjgy2wk6y8645y1g28r209-source
Revision:      1743b14ded01c066c9386f1a614c95dfe14bc86f
Revisions:     4
Last modified: 2021-11-27 14:18:38
Inputs:
└───nixpkgs: github:nixos/nixpkgs/73369f8d0864854d1acfa7f1e6217f7d6b6e3fa1
```

**Comment by CajuM** [comment] 2021-11-27 15:34
@maralorn I noticed in you configuration that `/var/lib/waydroid` has it's owner:group set to root:user, I think it should be root:root, but it may not be relevant. Can you check that `data` is mounted inside the container? `cat /proc/$(pgrep lxc-start)/mountinfo | grep waydroid`. Also inside the container `/data/user/0` should point to `/data/data`, can you chack that it's not dangling? `sudo waydroid shell` should give you a shell.

**Comment by CajuM** [comment] 2021-11-28 06:31
@KouAkitaki could you paste the output of `sudo waydroid logcat`?

**Comment by KouAkitaki** [comment] 2021-11-28 07:36
@CajuM Below is a link to the output of `sudo waydroid logcat`.

https://gist.github.com/KouAkitaki/21ddf15f99189df1c708d9a192fef969

**Comment by CajuM** [comment] 2021-11-28 13:39
@KouAkitaki are you using virito-gpu-gl-pci? If so, there is an issue with how waydroid loads the binder_linux module... it should be fixed by #145768 but it hasn't been merged yet. As a workaround, you can disable the `waydroid-container` service and load binder_linux before running `waydroid container start`: `modrobe binder_linux devices=binder,hwbinder,vndbinder`.

**Comment by KouAkitaki** [comment] 2021-11-28 14:10
> are you using virito-gpu-gl-pci?

I am not sure how to check that.

**Comment by KouAkitaki** [comment] 2021-11-28 14:13
I did
* `modrobe binder_linux devices=binder,hwbinder,vndbinder`
* `waydroid container start`
* `waydroid session start`
, and I'm observing the same result:

```
$ waydroid session start
[22:05:20] Failed to add service waydroidclipboard: -1
[22:05:20] Failed to add service waydroidusermonitor: -1
```

> @KouAkitaki are you using virito-gpu-gl-pci?

I'm not sure how do I check that. This is the output of `lsmod | grep virtio`, if it's of any use:

```
vmw_vsock_virtio_transport_common    36864  1 vsock_loopback
vsock                  45056  6 vmw_vsock_virtio_transport_common,vsock_loopback,vmw_vsock_vmci_transport
virtio_gpu             69632  80
virtio_dma_buf         16384  1 virtio_gpu
drm_kms_helper        270336  3 virtio_gpu
drm                   581632  20 drm_kms_helper,virtio_gpu
virtio_net             57344  0
virtio_blk             20480  3
net_failover           20480  1 virtio_net
virtio_pci             24576  0
virtio_pci_modern_dev    16384  1 virtio_pci
virtio_rng             16384  0
rng_core               20480  1 virtio_rng
virtio_console         36864  1
virtio_balloon         24576  0
virtio_ring            45056  7 virtio_rng,virtio_console,virtio_balloon,virtio_gpu,virtio_pci,virtio_blk,virtio_net
virtio                 16384  7 virtio_rng,virtio_console,virtio_balloon,virtio_gpu,virtio_pci,virtio_blk,virtio_net
```

**Comment by CajuM** [comment] 2021-11-28 14:18
You can check how Qemu was launched, for example: `-vga virtio` and `-device virtio-gpu-pci` will give you a virtio-gpu without OpenGL. To launch with virtio-gpu-gl, you can use `-vga none -device virtio-gpu-gl-pci -display gtk,gl=on`

**Comment by KouAkitaki** [comment] 2021-11-28 14:44
I tried checking from inside the VM as suggested, and it indeed reported `virgl`.

<img src="https://user-images.githubusercontent.com/17219127/143772521-c7c0a38e-c146-41f0-9870-1b2d62d602d8.png" width=50% height=50%>

**Comment by CajuM** [comment] 2021-11-28 15:36
I forgot to mention that you have to create a `/etc/gbinder.d/waydroid.conf` file with the following contents:
```
[Protocol]
/dev/binder = aidl2
/dev/vndbinder = aidl2
/dev/hwbinder = hidl

[ServiceManager]
/dev/binder = aidl2
/dev/vndbinder = aidl2
/dev/hwbinder = hidl
```
If you modified `/var/lib/waydroid/waydroid_base.prop`, it is not required for virgl.
Other than that I'm out of ideas.

**Comment by KouAkitaki** [comment] 2021-11-28 15:43
The `/etc/gbinder.d/waydroid.conf` file is already there with the said contents (I didn't create it manually), so I think that's not the cause.

**Comment by CajuM** [comment] 2021-11-28 16:05
Ok, you can start from the following vm.nix and adjust to you needs:
```
{ pkgs, lib, config, ... }:

{
  virtualisation.cores = 4;
  virtualisation.graphics = true;
  virtualisation.memorySize = 8192;

  virtualisation.qemu.options = [
    "-vga" "none"
    "-device" "virtio-gpu-gl-pci"
    "-display" "sdl,gl=on"
  ];

  nixos-shell.mounts = {
    mountHome = false;
    mountNixProfile = false;
  };

  boot.kernelPackages = pkgs.linuxPackages_xanmod;
  boot.kernelModules = [ "binder-linux" ];

  boot.extraModprobeConfig = ''
    options binder_linxu devices=binder,hwbinder,vndbinder
  '';

  environment.systemPackages = with pkgs; [
    alacritty
    mesa-demos
    waydroid
  ];

  programs.sway.enable = true;

  virtualisation.waydroid.enable = true;
}
```

`waydroid show-full-ui` should work out of the box.

**Comment by noneucat** [comment] 2021-11-30 23:07
Having same issue described in original post; also on an AMD GPU.

**Comment by poly3dfree** [comment] 2021-12-02 08:25
I need to use waydroid for testing things. I want to switch to NixOS but want a functional waydroid session. Installing nix  on a virtualbox and following instructions didn't helped me either. I'm also providing a log so it can improve : https://pastebin.com/L9HisMif

Note : This was done on new Nixos install in virtualbox with plasma desktop and wayland selected on sddm. and the above vm.nix file is added to /etc/nixos/ and in configuration file it is added as ./vm.nix other things like binder loading and xanmod kernel is running fine.

Can anyone confirm if waydroid is working for him/her and tell correctly how to do it in one single post from fresh install.

**Comment by Madouura** [comment] 2021-12-03 11:30
I'd love for this to work.
Do we know if it's an upstream or a nix problem?

**Comment by CajuM** [comment] 2021-12-03 20:01
I think it's both, #145768 should reach nixos-unstable in several days. We can add `boot.kernelModules = [ "binder_linux" ];` for now. Some GPUs do not work, in that case software rendering can be enabled, see: https://wiki.archlinux.org/title/Waydroid#GPU_Requirements

**Comment by CajuM** [comment] 2021-12-03 20:28
Looks like `binder_linux` is misbehaving, it might be a kernel issue...

**Comment by mkg20001** [comment] 2021-12-03 20:30
I'm currently running linuxPackages_latest with https://github.com/NixOS/nixpkgs/pull/145768 applied and things seem to work, perhaps that could resolve some issues once it's released in unstable.

**Comment by CajuM** [comment] 2021-12-03 22:24
If anyone sees `Failed to add service waydroidhardware:` in the output of `waydroid container start`, it's likely due to a bad/missing `/etc/gbinder.d/waydroid.conf`. As a solution you can set `virtualisation.waydroid.enable = true;`

If Waydroid complains about `/dev/binder` missing, it's likely due to bad modprobe paramters, it can be fixed by setting: `boot.kernelModules = [ "binder_linux" ];  boot.kernelPackages = pkgs.linuxPackages_xanmod;` until #145768 gets into nixos-unstable.

If `waydroid show-full-ui` does not display anything, it might be due to a GPU problem, in that case you could enable software rendering: https://wiki.archlinux.org/title/Waydroid#GPU_Requirements.

**Comment by maralorn** [comment] 2021-12-03 23:50
@CajuM, thank you for your help!

1. `boot.kernelModules = [ "binder_linux" ];` was a good hint. I now get less errors than before.

Sadly my android is still stuck in a boot loop. The symlink `/data/user/0 -> /data/data` exists. But the folder `/data/data` does not exist. No clue why, the data mount seems to exist.
`1124 32 0:28 /home/maralorn/.local/share/waydroid/data /disk/persist/var/lib/waydroid/data rw,relatime shared:1 - tmpfs tmpfs rw`

Note: My /var/lib is a tmpfs and /var/lib/waydroid a symlink onto a disk. Maybe this is causing issues?

**Comment by CajuM** [comment] 2021-12-04 06:54
Waydroid should create `/data/data/` automatically at boot, if it's missing. I think lxc/Waydroid got confused when it tried mounting the container's filesystem. It seems Android doesn't like it when its `/data` is a tmpfs. I don't think `/home/maralorn/.local/share/waydroid/data` should be on a tmpfs?

**Comment by CajuM** [comment] 2021-12-11 01:24
As a workaround, you can `sudo install -d -G root -o root -m 0755 /var/lib/misc`. That directory is generally created by the networkmanager module using systemd-tmpfiles.

**Comment by weewoo22** [comment] 2021-12-12 17:10
Okay, now I'm getting a few errors spammed in `dmesg`:
- `Could not find 'android.hardware.graphics.composer@2.1::IComposer/default' for ctl.interface_start`
- `libprocessgroup: Failed to make and chown /acct/uid_0: Read-only file system`
- `init: createProcessGroup(0, 730) failed for service 'vendor.hwcomposer-2-1': Read-only file system`
- `init: Unable to set property 'ro.init.updatable_crashing_process_name' to 'vendor.hwcomposer-2-1' from uid:0 gid:0 pid:1: Read-only property was already set`
- `init: Unable to set property 'ro.init.updatable_crashing' to '1' from uid:0 gid:0 pid:1: Read-only property was already set`

**Comment by maralorn** [comment] 2021-12-12 22:40
Thank you @CajuM, putting `~/.local/share/waydroid` on a real disk filesystem and creating `/var/lib/misc` fixed all my issues and I can no launch waydroid.

**Comment by CajuM** [comment] 2021-12-18 20:34
@weewoo22 could you post the output of `sudo waydroid logcat`?

**Comment by tgunnoe** [comment] 2022-03-03 10:55
@CajuM I'm` having the same issue as the above poster.  

Here's the logcat output:
https://gist.github.com/tgunnoe/72f772084b676fc8b70bc7c271440112

I tried switching from nixos-unstable's latest kernel to xanmod and added `"binder_linux" `to `boot.kernelModules`, troubleshooted with directory steps above, etc.  Not sure what's missing

**Comment by CajuM** [comment] 2022-03-04 20:57
@tgunnoe binder_linux and ashmem made it into nixos-unstable as static kernel modules. There should be no need to switch to xanmod or modify boot.kernelModules. Your GPU would seem to be at fault, have you tried following https://wiki.archlinux.org/title/Waydroid#GPU_Requirements?

**Comment by CajuM** [comment] 2022-03-05 11:38
@tgunnoe `binder_linux` and `ashmem` have made into nixos-unstable in mainline Linux as static modules. There should be no need to switch to xanmod or modify `boot.kernelModules`. I have managed to reproduce the issue, but only on sway, gnome and plasma work fine.

**Comment by tgunnoe** [comment] 2022-03-05 18:05
@CajuM thank you. It could very well be sway then I will try it with another desktop

**Comment by maralorn** [comment] 2022-03-10 20:20
Since my original issue doesn’t seem to be a bug I suggest closing this issue.

**Closed** 2022-03-11 08:55 UTC
Labels: 0.kind: bug

**Comment by Afsalmc** [comment] 2022-04-04 11:38
I followed this guide and it solved my issue .

https://linux32bituefi.blogspot.com/2021/12/install-waydroid-in-opensuse-tumbleweed.html
