### ISSUE TITLE
Adding mount options for swap

### ISSUE THREAD

**Issue by gcerar** [NixOS/nixpkgs#6603] opened 2015-02-28 12:00 UTC
Is it possible to implement mount options for swap partition? This feature could be useful for machines with SSD only drive(s). User could change to `defaults,discard` options for automatic trimming. [Man pages](http://man7.org/linux/man-pages/man8/swapon.8.html) of this feature.

**Comment by joelmo** [comment] 2015-02-28 14:59
I think this is what you want https://github.com/NixOS/nixos/blob/master/modules/tasks/filesystems.nix#L43

**Comment by GCerar** [comment] 2015-03-01 12:59
I still can't figure out solution with documentation @joelmo pointed out. If I put
```
swapDevices =
[
    label = "swap";
    options = "defaults,discard";  # <--- raises error
]
```
raises an error. I am using NixOS 14.12 stable.
```
fileSystems =
{
    # ...
    "???" = {  # What to put here?
        label = "nix-swap";
        fsType = "swap";
        options = "defaults,discard";
    };
};
```
As far as I know swap partition does not have mounting point.

**Comment by ikervagyok** [comment] 2015-03-22 23:20
@GCerar: you may do it like this:
```
fileSystems =
{
  "swap" = {label = "swap"; fsType = "swap"; mountPoint = "none"; options = "defaults,discard";}
}
```
even though, i didn't test it, but using ```mountPoint``` like this should work

regards, iker

**Comment by peti** [comment] 2015-03-24 19:37
Still, it would be nice if there were a more idiomatic way to accomplish that.

**Comment by GCerar** [comment] 2015-10-29 22:35
Sorry for long pause. After some research, setting discard on swap is NOT good idea. (see [source](https://www.linuxquestions.org/questions/linux-hardware-18/should-trim-be-used-on-swap-partition-901701/)). Setting it, would trigger trim command every time block clears, which leads to poor performance when swap is under pressure.

Issue can be closed.

**Comment by AleXoundOS** [comment] 2019-12-22 22:59
@GCerar, according to the [man page](http://man7.org/linux/man-pages/man8/swapon.8.html) there is a single `discard=once` variant:
> perform a single-time discard operation for the whole swap area at swapon

**Comment by Ferroin** [comment] 2020-02-29 19:08
On top of the case pointed out by @AleXoundOS of doing a oneshot discard of swap space on startup, there are some situations where there really isn't much of any performance impact.

As a simple example, I'm running NixOS in a VM, and the hypervisor translates TRIM/UNMAP/DISCARD commands into calls to fallocate() with the FL_PUNCH_HOLE flag on the host side. This ends up completing almost instantly due to how my storage stack is set up (and will in most cases where people are using file-backed VM disks), and more importantly, it can be queued on the VM side because it's on an emulated SCSI device. There's literally no measurable performance impact in this case, but there's a big impact on the host side in terms of simplifying space management.

Even ignoring use of virtualization, 90% of the performance issue for inline discards in general (not just for swap space) is due to most commodity hardware not being able to queue them, which results in them having about the same impact as an FUA request. Some hardware, however (notably most SCSI and NVMe devices) _can_ queue them, and they have very little impact on performance there.

**Comment by ikervagyok** [comment] 2020-03-01 16:18
since this issue got new visits again, i've uploaded https://github.com/ikervagyok/nixpkgs/commit/d02c472d668e55e54e455493a0b495dc0d2db371, which is a start. I've also looked into unifying `filesystems` and `swapDevices`, but it seems a lot of work if such a change doesn't get merged.

**Comment by AleXoundOS** [comment] 2021-01-30 18:39
@gcerar, the issue still remains. Can you reopen, please?

**Comment by cyounkins** [comment] 2021-06-24 02:00
I'm using nixos 21.05 and want to add the "nofail" option for swap devices that are in raid1.

Options:

1. I can send a PR for a `swapDevices.*.options` option that gets passed to `fstab`. I have this and can put it up quickly. This mirrors `fileSystems.<name>.options`.
2. I can send a PR for a specific `swapDevices.*.nofail` option.
3. I can use `fileSystems."swapN"`, which can support arbitrary options. But then `hardware-configuration.nix` won't be reproduced correctly.

Any opinions?

**Comment by Ferroin** [comment] 2021-06-24 15:15
The `swapDevices.*.options` approach would get my vote, as it avoids any possibility of arguments between users and developers when a user wants to use an option the developer thinks should not be used (such as the `discard` option that started all of this).

**Comment by Artturin** [comment] 2021-06-24 20:28
#128032

**Closed** 2021-07-23 08:45 UTC
Labels: 0.kind: enhancement, 6.topic: nixos
