### ISSUE TITLE
service.uwsgi not creating runDir directory

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#110691] opened 2021-01-24 13:08 UTC
**Describe the bug**

NixOS service `service.uwsgi` doesn't create the directory `runDir`. This means that the user must manually create that directory and set its ownership and permissions properly, otherwise uwsgi systemd service fails. It'd be nice if those were created automatically because it's not trivial for the user to realize that the failure means that this needs to be done and also it's not trivial how exactly to create the directory (path, ownership, permissions).

**To Reproduce**

If needed, I can add this a bit later when I have more time.

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module: service.uwsgi
```

**Comment by aanderse** [comment] 2021-01-24 22:11
Your statement is conditionally true: the directory is created if the value of `runDir` is left as the default value. The `description` of the `runDir` option needs to be updated to read something similar to [this](https://search.nixos.org/options?channel=unstable&show=services.mpd.dataDir&from=0&size=50&sort=relevance&query=services.mpd.dataDir). Maybe:

```
The directory in which uWSGI communication sockets are created. If left as the default value this directory will automatically be created on system activation, otherwise the sysadmin is responsible for ensuring the directory exists with appropriate ownership and permissions. 
```

How does that sound @rnhmjoj?

**Comment by jluttine** [comment] 2021-01-25 06:20
I don't have `runDir` set, and still the directory isn't created. This seems relevant from the file: https://github.com/NixOS/nixpkgs/blob/aa8868c7cca8d30706a68a876d048968c83e1cf1/nixos/modules/services/web-servers/uwsgi.nix#L195-L197

But there the condition is that if `runDir` is NOT the default, then that is done.

Could you point where the directory is created if the value of `runDir` is left as the default value. I can't find that..

But anyway, it would be nice if the directory was created similarly whatever value `runDir` has.

Before the latest updates in the file, there was this section: https://github.com/NixOS/nixpkgs/blob/b96a4dcc6079e9c7ea94f9f06b7399a4e10a9e05/nixos/modules/services/web-servers/uwsgi.nix#L154-L157

I wonder why it was removed..? It seems it was exactly what I'd hope for. Or maybe set the directory permissions as `chmod 775 ${cfg.runDir}` too. But I suppose there has been some reason to remove it?

My config is basically this:
```nix
services.uwsgi = {
  enable = true;
  user = "nginx";
  group = "nginx";
  plugins = [ "python3" ];
  instance = {
    type = "emperor";
    vassals = {
      foobar = {
        type = "normal";
        socket = "${config.services.uwsgi.runDir}/foobar.sock";
        ...
      };
    };
  };
};
```

**Comment by rnhmjoj** [comment] 2021-01-25 07:20
> I wonder why it was removed..? It seems it was exactly what I'd hope for. Or maybe set the directory permissions as chmod 775 ${cfg.runDir} too. But I suppose there has been some reason to remove it?

I removed it because the service is now running as an underpriviliged user: `preStart` can't be used to set up the directory (technically there's [PermissionsStartOnly](https://github.com/NixOS/nixpkgs/issues/53852) but it's deprecated). I must have missed the `cfg.runDir != "/run/uwsgi"` condition: I would just remove it and let it always manage the directory.
Does this sounds good for you?

**Comment by jluttine** [comment] 2021-01-25 08:06
@rnhmjoj I'm not too familiar with `tmpfiles.d` (or `systemd.tmpfiles.rules` in NixOS), but as far as I understand from the man pages, it sounds like a perfect solution as far as I understand.

**Comment by aanderse** [comment] 2021-01-25 12:35
I misread! And to clarify, `tmpfiles` is **not** the best solution. Directories are not created on every service start, so there is possibility the directory can be deleted. `StateDirectory` is superior and should be used, when possible.

**Comment by jluttine** [comment] 2021-01-25 12:53
Ah, ok! So, could `RuntimeDirectory` be used here? It would create the directory during every service start and deletes it at every service stop?

**Comment by aanderse** [comment] 2021-01-25 12:55
Yes, that is what `RuntimeDirectory` would do, which is **far** superior. It comes at a cost, though... `RuntimeDirectory` can only create directories under `/run`, like `/run/uwsgi`, etc... "Worth it" in my opinion, though.

**Comment by jluttine** [comment] 2021-01-25 13:09
Ah, right! :+1: So, `RuntimeDirectory` couldn't be used if custom `runDir` wasn't under `/run/`. Maybe then use `RuntimeDirectory` if `runDir` is under `/run/` and otherwise tell the user to create the directory manually?

Or, alternatively, a backwards incompatible change could be that `runDir` is interpreted to mean the path under `/run`. So, `runDir = "uwsgi"` would mean `RuntimeDirectory=uwsgi` which means `/run/uwsgi` path. But, indeed, this is backwards incompatible as such. Unless, `runDir` is interpreted as `RuntimeDirectory` if it has no leading slash.. So, `runDir = "/foo/bar"` would mean `/foo/bar` but `runDir = "foo/bar"` would mean `/run/foo/bar`... Ok, I'm getting a bit carried away.. :smile: But I would find it sufficient if the users were forced to use `RuntimeDirectory` instead of abitrary path.

**Comment by rnhmjoj** [comment] 2021-01-25 13:17
I used `RuntimeDirectory="uwsgi"` only if `runDir` is unchanged, which reproduce the old behavior.

**Comment by rnhmjoj** [comment] 2021-01-25 14:04
Should be fixed in the next channel update, sorry for the trouble.

**Closed by rnhmjoj** 2021-01-25 14:04 UTC
Labels: 0.kind: bug, 6.topic: nixos
