### ISSUE TITLE
KDE help pages broken

### ISSUE THREAD

**Issue by benley** [NixOS/nixpkgs#23201] opened 2017-02-26 06:50 UTC
## Issue description

If you hit F1 in a KDE app on release-16.09, the help browser comes up with the following error (including the &lt;br&gt; tag split across lines):

```
The requested help file could not be parsed:<br 
/>/run/current-system/sw/share/doc/HTML/en//dolphin/index.docbook
```

The mentioned file does exist and appears to be a valid docbook document, so perhaps that newline has something to do with it?

### Steps to reproduce

Run KDE 5 on nixos 16.09.  In Dolphin or Konqueror (or probably any KDE app), hit F1 or use the Help menu to bring up the help browser.  Notice that most of the pages are broken.

## Technical details

* System: NixOS 16.09
* Nix version: 1.11.6
* Nixpkgs version: 16.09pre-git (at ec7a66c035fa5fd3225d42afdc50c2d212a17f85 with a few local patches)

**Comment by ttuegel** [comment] 2017-02-28 15:42
Whitespace is illegal inside XML tags, so that is surely the problem. I don't yet know how it got there.

**Comment by Ekleog** [comment] 2018-10-03 01:31
(triage) Is this still happening? I can't reproduce with either kcachegrind or dolphin.

**Comment by johnalotoski** [comment] 2018-10-03 02:18
I've had the same issue on a Nix 18.03 system, since I installed it AFAIK, where all KDE help selections from the KDE Help Center yield those messages.  I can try and help with debugging if you have any suggestions.

John

**Comment by Ekleog** [comment] 2018-10-03 03:10
Hmm, on 18.03 too, when I press F1 on dolphin I get a webpage that opens in firefox, not the KDE Help Center? Maybe it's because I don't actually use all of KDE and just did `nix-shell -p dolphin` for the test, the same reason for which [khelpcenter doesn't execute here](https://github.com/NixOS/nixpkgs/issues/47698).

Anyway, it looks like this is still happening, and I'll be able to do little to help… maybe if you try to figure out where in your store is the file like OP's `/run/current-system/sw/share/doc/HTML/en//dolphin/index.docbook`, and look for whether there's anything weird in it / whether another docbook parser is able to handle it?

**Comment by johnalotoski** [comment] 2018-10-04 02:38
Thanks for the ideas.  I found the file the OP mentioned above, and there is nothing obviously strange about it.  I also receive the same or similar errors a large number of other docbook files in khelpcenter, not just for Dolphin.  If I run khelpcenter from the command line and try clicking one of the broken help files (okular in the example below), the output on the command line shows:

`org.kde.khelpcenter: could not start process ("--stylesheet", "/run/current-system/sw/share/khelpcenter/table-of-contents.xslt", "--output", "/home/user1/.cache/khelpcenter/help/__en__okular__index.docbook", "/home/user1/.nix-profile/share/doc/HTML/en//okular/index.docbook")`

and xsession logging observed with ksystemlog shows:

`I/O warning: failed to load external entity ""`
`error`
`xsltParseStylsheetFile : cannot parse`

I don't see any obvious permissions problems at the paths involved.  I'll poke around a little more as I have time.  Perhaps there is a missing kde nix package that is needed.  I didn't install all kde packages with this installation, but only those with seemed to be needed to support the apps I wanted.  My nix user config is here: [https://github.com/johnalotoski/nixos-user/blob/master/config.nix](https://github.com/johnalotoski/nixos-user/blob/master/config.nix)

A similar (but quite old) bug is seen at Redhat bugzilla and was root caused to a missing library; I'm trying to figure out if that has any relevance here: [https://bugzilla.redhat.com/show_bug.cgi?id=446435](https://bugzilla.redhat.com/show_bug.cgi?id=446435)

John

**Comment by Ekleog** [comment] 2018-10-04 03:03
Hmm… the error messages you quote look like it's missing the process to call? Then I'm no expert on KDE (don't even use it), so I won't be able to do much more than that, sorry :/

**Comment by johnalotoski** [comment] 2018-10-04 03:44
No worries.  I can live with this issue anyway -- not a big deal.  I'll post an update if I get it resolved.  Thanks.

**Comment by johnalotoski** [comment] 2018-10-04 22:04
It looks like @matthewbauer successfully root caused this issue and merged a fix for NixOS master via issue [https://github.com/NixOS/nixpkgs/issues/46539](https://github.com/NixOS/nixpkgs/issues/46539) and PR [https://github.com/NixOS/nixpkgs/pull/47205](https://github.com/NixOS/nixpkgs/pull/47205).  Thanks Matthew!

**Closed** 2018-10-04 22:11 UTC
Labels: 0.kind: bug, 6.topic: qt/kde

**Comment by matthewbauer** [comment] 2018-10-04 22:17
Yeah this issue was fixed. We can backport it too if needed. There are still some issues with images not showing up. Also the man pages seem to not work.

**Comment by johnalotoski** [comment] 2018-10-04 22:43
Cool, thanks for the info and good to know about the remaining issues going forward.

**Comment by lboklin** [comment] 2024-03-24 08:32
This is a problem in 24.05 (Plasma version 6.0.2) as well.
