### ISSUE TITLE
Webcord

### ISSUE THREAD

**Issue by nilnail** [NixOS/nixpkgs#187766] opened 2022-08-21 16:43 UTC
**Project description**
_describe the project a little_
A Discord and Fosscord(https://fosscord.com/) client implemented directly without [Discord API]. Made with the Electron framework.
**Metadata**

* homepage URL: https://github.com/SpacingBat3/WebCord
* source URL: https://github.com/SpacingBat3/WebCord
* license: mit
* platforms: unix, linux, darwin,

**Comment by figsoda** [comment] 2022-09-07 19:34
duplicate of #183061

**Closed by figsoda** 2022-09-07 19:34 UTC
Labels: 0.kind: packaging request
