### ISSUE TITLE
http-parser: build fails on Darwin

### ISSUE THREAD

**Issue by mnacamura** [NixOS/nixpkgs#48804] opened 2018-10-22 02:00 UTC
### Build log

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/39cxiikhq5bay8yjhmw6vc4kbgz7rjz3-v2.8.1.tar.gz
source root is http-parser-2.8.1
setting SOURCE_DATE_EPOCH to timestamp 1522476475 of file http-parser-2.8.1/test.c
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/x3rg29m48h5lkn200mysqz3kr8vq7rz8-build-shared.patch
patching file http_parser.gyp
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
Traceback (most recent call last):
  File "/nix/store/jhd79gr0q6vsnn2iwpkia4zs49iqkw64-python2.7-gyp-2015-06-11/bin/.gyp-wrapped", line 12, in <module>
    sys.exit(script_main())
  File "/nix/store/jhd79gr0q6vsnn2iwpkia4zs49iqkw64-python2.7-gyp-2015-06-11/lib/python2.7/site-packages/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/nix/store/jhd79gr0q6vsnn2iwpkia4zs49iqkw64-python2.7-gyp-2015-06-11/lib/python2.7/site-packages/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/nix/store/jhd79gr0q6vsnn2iwpkia4zs49iqkw64-python2.7-gyp-2015-06-11/lib/python2.7/site-packages/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/nix/store/jhd79gr0q6vsnn2iwpkia4zs49iqkw64-python2.7-gyp-2015-06-11/lib/python2.7/site-packages/gyp/generator/make.py", line 2159, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/nix/store/jhd79gr0q6vsnn2iwpkia4zs49iqkw64-python2.7-gyp-2015-06-11/lib/python2.7/site-packages/gyp/generator/make.py", line 795, in Write
    self.Pchify))
  File "/nix/store/jhd79gr0q6vsnn2iwpkia4zs49iqkw64-python2.7-gyp-2015-06-11/lib/python2.7/site-packages/gyp/generator/make.py", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "/nix/store/jhd79gr0q6vsnn2iwpkia4zs49iqkw64-python2.7-gyp-2015-06-11/lib/python2.7/site-packages/gyp/xcode_emulation.py", line 545, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File "/nix/store/jhd79gr0q6vsnn2iwpkia4zs49iqkw64-python2.7-gyp-2015-06-11/lib/python2.7/site-packages/gyp/xcode_emulation.py", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "/nix/store/jhd79gr0q6vsnn2iwpkia4zs49iqkw64-python2.7-gyp-2015-06-11/lib/python2.7/site-packages/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/nix/store/jhd79gr0q6vsnn2iwpkia4zs49iqkw64-python2.7-gyp-2015-06-11/lib/python2.7/site-packages/gyp/xcode_emulation.py", line 1240, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
```

### Steps to reproduce

```
nix build -f '<nixpkgs>' http-parser
```

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.7.0, macOS 10.13.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(mnacamura): `"darwin, nixpkgs-19.03pre152857.947ae71dcec"`
 - channels(root): `"nixpkgs-18.03pre129189.c2fbd472a4e"`
 - nixpkgs: `/Users/mnacamura/repos/nixpkgs`

**Comment by LnL7** [comment] 2018-10-23 19:03
We use clang instead of Xcode with nix which the detection from gyp can't handle. We've patched this in a few places since all the build usually needs is a compiler, but using `xcbuild` could also work and might be an easier solution.

**Comment by LnL7** [comment] 2018-10-23 19:08
Both channel revisions mentioned look pretty old, the hydra build has been green for a while now https://hydra.nixos.org/job/nixpkgs/trunk/http-parser.x86_64-darwin.

**Comment by danieldk** [comment] 2018-10-25 07:03
The build of http-parser also fails on my machine with macOS Mojave (Xcode 10.0). Building using `xcbuild` solves the problem. Shall I do a pull request?

**Comment by LnL7** [comment] 2018-10-26 10:03
I'm not sure since I can't reproduce the issue and it seems to work fine on hydra.

**Comment by Ekleog** [comment] 2019-02-12 01:32
@mnacamura Reading @LnL7's comments it looks like your issue can't be reproduced with recent channel builds. Closing for now, feel free to reopen if you still have this issue on recent versions of nixpkgs.

**Closed by Ekleog** 2019-02-12 01:32 UTC
Labels: 6.topic: darwin
