### ISSUE TITLE
AMI release for 21.05

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#125808] opened 2021-06-05 15:10 UTC
**Project description**

Upload the AMIs to amazon.

This has been requested via issues at least half of the time, so it doesn't seem to be part of the release process. We do upload them each time though, so not doing it in the release just wastes community energy with people trying to figure out who to contact etc.

 - [x] add AMI upload to release process
 - [ ] upload 21.05 AMIs
 - [ ] same for aarch64 images #52779

Previous requests:
 - 20.09 https://github.com/NixOS/nixpkgs/issues/72132
 - 20.03 https://github.com/NixOS/nixpkgs/issues/85857
 - 18.09 https://github.com/NixOS/nixpkgs/issues/48222
 - 17.09 https://github.com/NixOS/nixpkgs/issues/29976

cc @jonringer @edolstra

**Comment by jonringer** [comment] 2021-06-05 15:24
cc @AmineChikhaoui

**Comment by jonringer** [comment] 2021-06-05 15:58
unfortunately, this has to be done by an individual with access to the s3 bucket

**Comment by samuela** [comment] 2021-06-05 22:36
Is there not a way that we could just do this in CI?

**Comment by jonringer** [comment] 2021-06-05 22:59
> Is there not a way that we could just do this in CI?

I'm assuming the issue is secret management

**Comment by roberth** [comment] 2021-06-05 23:03
I'd be happy to help with a suitable CI including secrets management.

**Comment by samuela** [comment] 2021-06-06 00:24
Awesome, happy to help if necessary! IIRC GitHub actions has a security feature for some jobs to only be run trusted commits from admins.

**Comment by jonringer** [comment] 2021-06-07 00:09
Addressed in https://github.com/NixOS/nixpkgs/pull/125976 https://github.com/NixOS/nixpkgs/pull/125972

**Closed by jonringer** 2021-06-07 00:09 UTC
Labels: 0.kind: packaging request, 6.topic: release process
