### ISSUE TITLE
Package request: Thorium-browser

### ISSUE THREAD

**Issue by xkkx3** [NixOS/nixpkgs#261700] opened 2023-10-17 19:52 UTC
**Project description**

It's a super fast chromium-based browser. Apparently, it's the fastest browser out there.

**Metadata**

* homepage URL: https://thorium.rocks/
* source URL: https://github.com/Alex313031/thorium
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by SoftwareRat** [comment] 2023-10-18 15:52
It must be added to NixOS immediately

**Comment by eclairevoyant** [comment] 2023-10-18 16:39
duplicate of #184823

**Closed by eclairevoyant** 2023-10-18 16:39 UTC
Labels: 0.kind: packaging request
