### ISSUE TITLE
`~/.profile` never gets called 

### ISSUE THREAD

**Issue by jraygauthier** [NixOS/nixpkgs#5200] opened 2014-12-02 03:49 UTC
Where should I perform my user profile environment setup then? Searched options, but there seemed to be no options for user specific environment setup.

Attempted something funky like:

``` .bash
  environment.extraInit = 
    ''
    if [-e $HOME/.profile] then;
        . $HOME/.profile
    fi  
    '';
```

in `configuration.nix`. It simply crashed my `sudo` command and did not source `~/.profiles`. 
As a result, reverted to the previous generation.

Feels like it would be much simpler to have `.profile` called as in many other linux distros. 

I want user installed packages to be based on my `nixpkgs` git repository while keeping 14.04's stability for the system. However, `import <nixpkgs>` directive uses the root user's channel 
instead of the `nixpkgs` repository tucked in `.nix-defexpr/nixpkgs/` while `nix-env` do use my repository.  Setting `NIX_PATH` however seemed to be recognized perfectly by the `import`
command. Hence the need get a permanent alteration of user profile's environment.

I actually do not plan in the short term to upgrade my system to something unstable. Any
possible workaround?

**Comment by kirelagin** [comment] 2015-01-04 22:04
Personally I believe that `~/.profile` is very important as it is the single place to export things like `$PATH` so that it gets set _both_ in shells and in desktop environment. Indeed this depends on desktop manager configuration, distro etc. but I believe that desktop managers should source this file (lightdm does) and RC files of shells should source it too (I had to do this myself).

**Comment by listx** [comment] 2015-06-28 06:19
I use Slim as well and got bit by the "not reading ~/.profile" behavior.
I'm using gpg-agent with `services.xserver.startGnuPGAgent = true;` [1] because I need to use a Yubikey for SSH logins.
The magic one-liner command that gets everything working (after I log in to X) is:

```
gpg-connect-agent updatestartuptty /bye
```

.
See [2].
Without this line, the pinentry box never shows up in my X terminals when I invoke SSH to login to a box with my Yubikey.
Here is a section of the gpg document explaining the need for this:

> Note: in case the gpg-agent receives a signature request, the user might need to
> be prompted for a passphrase, which is necessary for decrypting the stored key.
> Since the ssh-agent protocol does not contain a mechanism for telling the agent
> on which display/terminal it is running, gpg-agent's ssh-support will use the
> TTY or X display where gpg-agent has been started.

I've looked at verbose outputs of `ssh` when trying to connect to the remote server with my Yubikey and indeed that server asks for a "signature request" --- because without that `gpg-connect-agent` command, it fails right after this point (ssh output):

```
debug3: sign_and_send_pubkey: RSA SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

.
Now, I'd like to read `~/.profile` one time (when I log in) to execute the command above, but as discussed in the previous comments, Slim never executes `/bin/sh` as a login shell, so this is a bit annoying.
I do like Slim, and this is an upstream quirk, but still, I thought it was worth repeating here to break the myth that `~/.profile` is always read because it is a "standard" location.

For my problem, I could just scrap `startGnuPGAgent` and invoke gpg-agent manually in my config somewhere, but as I'm using SLiM there is no easy way to say "run this one time on login" --- because it does not read ~/.profile (I mean, sure, I could write a hack around it, but I feel like it's a natural thing for the 'login shell' feature of shells).
I've tried using /etc/profile (which is indeed run on login), but the problem is I need to call `gpg-connect-agent` much later.
I've also tried using `services.xserver.displayManager.sessionCommands` but it also did not work.

[1]: http://lists.science.uu.nl/pipermail/nix-dev/2014-July/013686.html
[2]: https://www.gnupg.org/documentation/manuals/gnupg-devel/Agent-Options.html

**Comment by kirelagin** [comment] 2015-06-28 08:02
Arguable the distribution (that is, NixOS in our case) is responsible for maintaining this kind of consistensy of user experience.

For example, Gentoo ensures that `~/.profile` (and `~/.xprofile`) are sourced by placing [this](https://github.com/gentoo/gentoo-portage-rsync-mirror/blob/master/x11-misc/slim/files/Xsession-r3#L12) in `/usr/share/slim/Xsession`

**Comment by wmertens** [comment] 2015-06-28 11:11
:+1: for sourcing .profile on X login, there is no way the shell can detect
that otherwise.

(or is there? what about instead executing the window manager from a login
shell? I suppose that's up to the session manager? Perhaps this is a bug in
there?)

On Sun, Jun 28, 2015, 10:03 AM Kirill Elagin <notifications@github.com>
wrote:

> Arguable the distribution (that is, NixOS in our case) is responsible for
> maintaining this kind of consistensy of user experience.
>
> For example, Gentoo ensures that ~/.profile (and ~/.xprofile) are sourced
> by placing this
> <https://github.com/gentoo/gentoo-portage-rsync-mirror/blob/master/x11-misc/slim/files/Xsession-r3#L12>
> in /usr/share/slim/Xsession
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/5200#issuecomment-116218562>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by kirelagin** [comment] 2015-06-28 11:47
> what about instead executing the window manager from a login
shell? I suppose that's up to the session manager? Perhaps this is a bug in
there?

This might be considered a bug in NixOS indeed, as the slim module executes shell without the `-login` flag. On the other hand, NixOS’s xsession sources `/etc/profile` itself and _that_ might be the reason, why `-login` is ommited. See my comment in #8538 for details.

I believe this part of NixOS is somewhat old (2009/2010). The `. /etc/profile` line was added in 2012 to make gpg-agent work, as the commit message claims. So I’d say all this stuff is a little bit random and can be improved considerably.

**Comment by vcunat** [comment] 2015-06-29 12:19
Is there some kind of UNIX-like documentation saying what is supposed to be sourced at what occasions?

**Comment by edolstra** [comment] 2015-06-29 14:44
Why was this issue reopened? ~/.profile clearly does get sourced for interactive login shells, just as described in the bash manpage.

**Comment by vcunat** [comment] 2015-06-29 17:35
The reason was: one might expect to get env from ~/.profile also if only using graphical login. Some distros (at least) ensure that, as reported above, but I know of no standard specifying whether it should be sourced (e.g. along with ~/.xprofile).

**Comment by kirelagin** [comment] 2015-06-29 18:39
I don’t think there is something like a definition of `.profile` and how it should to be used.
Basically, I think, it is safe to assume that the shell spawned by whatever desktop manager we use is a non-interactive login one, so that the rest is left to bash.

**Comment by spinus** [comment] 2015-10-12 12:53
@kirelagin +1

**Comment by chairmanK** [comment] 2016-01-30 18:35
This issue relates to (at least) two overlapping questions:

1. In which scenarios (interactive shell, login via display manager, etc.) do we expect `~/.profile` be sourced?
2. Do we expect the per-user `~/.profile` to be automatically sourced after the system-wide `/etc/profile`?

I am agnostic about question (1). I observe that `/etc/profile` is read when I login. I don't care why or how this happens.

However, I am interested in question (2). Why is `~/.profile` ignored even though `/etc/profile` is read? My naive expectation is that `/etc/profile` ought to automatically source `~/.profile`.

To get this behavior, I updated my nix configuration to populate a `/etc/profile.local` file:

```
environment.etc."profile.local".text = 
  ''
  # /etc/profile.local: DO NOT EDIT - this file has been generated automatically.

  if test -f "$HOME/.profile"; then
    . "$HOME/.profile"
  fi
  '';
```

`/etc/profile` reads `/etc/profile.local`, if it exists (https://github.com/NixOS/nixpkgs/blob/3f417e627221f33d0f1807a01ae6749c71f7391f/nixos/modules/programs/bash/bash.nix#L164).

This is a kludgy workaround, but it's not as bad as sourcing `~/.profile` in `~/.bashrc` or another place, which is simply backwards.

I don't have an opinion about whether this ought to be the default behavior. If people want it, then I'll gladly make a pull request.

**Comment by matthiasbeyer** [comment] 2017-01-12 12:37
I guess this issue can be closed, as 14.04 is long dead now @jraygauthier @chairmank

**Comment by vcunat** [comment] 2017-01-12 12:57
I don't know of any evidence that the situation has changed since then.

I don't have any strong opinion on either way (`.profile`, `.xprofile`, etc).  Perhaps *if* "most systems" use one way, it might be good to behave the same.

**Comment by chairmank** [comment] 2017-01-14 03:54
I confirmed that the behavior is the same in a recent version of NixOS (maybe not bleeding edge, but the latest release in the 16.09 series). And the code looks the same: 

https://github.com/NixOS/nixpkgs/blob/7c7e88b45e137d2f0458bae167ede9d5fe551df2/nixos/modules/programs/bash/bash.nix

I think that it would be good to change the `environment.etc."profile".text` value to include something like

```
        # Read per-user modifications.
        if test -f "$HOME/.profile"; then
          . "$HOME/.profile"
        fi
```

after the lines that source `/etc/profile.local`.

**Comment by spy-tech** [comment] 2017-01-28 20:55
The reason why we should close this issue is, because exactly there is no standard which says that it needs to be done in this particular way.

Indeed as has been said earlier, but not quoted:

> --noprofile
              Do  not read either the system-wide startup file /etc/profile or any of the personal initialization files ~/.bash_profile, ~/.bash_login, or ~/.profile.  By default, bash
              reads these files when it is invoked as a login shell (see INVOCATION below).

It's a waste of time to leave this issue open. Please close it @vcunat. I would do it myself, if I had the credentials to do so.

**Comment by vcunat** [comment] 2017-01-28 21:13
To me it seems confusing at least.  It would be nice if the behavior was at least described somewhere (like our docs), i.e. making our own standard &ndash; preferably in a way consistent with some other systems, but I don't even see a good particular place where to put the information.

**Comment by kirelagin** [comment] 2017-03-01 14:25
I don’t think this issue can be closed until there is a definite answer to the question “Where does one put exports that are applied universally on login?” in the documentation.

**Comment by FRidh** [comment] 2018-06-25 09:55
Note we should also consider the (future) scenario with Wayland, which doesn't source any of these files.
https://unix.stackexchange.com/questions/317282/set-environment-variables-for-gnome-on-wayland-and-bash-on-virtual-terminals-or#326161

**Comment by whoizit** [comment] 2019-04-08 00:41
I came across this problem. I cannot set the environment variables in the files ~/.bash_profile and ~/.profile as if they are not used. And I could not find a solution

**Comment by cnnrro** [comment] 2019-12-30 22:47
Came across this issue as well.

Using this workaround, which seems to make sense to me, for the time being:

```
environment.loginShellInit = ''
	if [ -e $HOME/.profile ]
	then
		. $HOME/.profile
	fi
'';
```

**Comment by sersorrel** [comment] 2021-08-02 17:09
I just ran into this. I was confused by the note at the top of /etc/profile that reads "This file is read for login shells.": if the shell is a login shell, then it should be reading my ~/.profile too, but it doesn't. I am reasonably sure that e.g. Ubuntu sources ~/.profile by default in graphical sessions, too, and most of my Linux experience is on Ubuntu.

**Comment by shashurup** [comment] 2022-07-04 12:33
On Arch LightDM sources ~/.profile which seem reasonable to me. On nix I have to duplicate the contents of my ~/.profile into ~/.xprofile which doesn't look like a good solution in general. I think that ~/.profile is intended to be a place where I can define variables for both graphical and cosole sessions.

**Comment by kira-bruneau** [comment] 2022-08-17 23:28
The main problem here was that display managers don't source the login shell environment, a workaround has been applied in #185987.

We now source `~/.profile` in `xsessionWrapper`, but I think we'll eventually want to generalize this to load the actual login shell environment for the given `$SHELL`. The way we have it hard-coded right now is intended to emulate the login shell environment for sh.

**Closed by kira-bruneau** 2022-08-17 23:28 UTC
Labels: 6.topic: nixos, 9.needs: documentation
