### ISSUE TITLE
Update request: openra release-20190314 → release-20230225

### ISSUE THREAD

**Issue by RTUnreal** [NixOS/nixpkgs#219422] opened 2023-03-03 22:23 UTC
- Package name: openra
- Latest released version: 20230225
- Current version on the unstable channel: 20190314
- Current version on the stable/release channel: 20190314

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@fusion809 @msteen @rardiol

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by mdarocha** [comment] 2023-03-12 20:11
Duplicate of https://github.com/NixOS/nixpkgs/issues/96600

**Closed by mdarocha** 2023-03-12 20:11 UTC
Labels: 9.needs: package (update)
