### ISSUE TITLE
Doesn't start from shortcut in GNOME system. Runs in the terminal. The shortcut does not work.

### ISSUE THREAD

**Issue by apolon210788** [NixOS/nixpkgs#191335] opened 2022-09-15 13:56 UTC
### Steps To Reproduce
1. ...
2. ...
3. ...

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by apolon210788** [comment] 2022-09-15 13:57
Doesn't start from shortcut in GNOME system. Runs in the terminal. The shortcut does not work.

**Comment by buckley310** [comment] 2022-09-19 03:57
Looks like this report didn't get finished?
Is this issue a duplicate of one of the other similar ones from around this time?

**Comment by jtojnar** [comment] 2022-11-09 16:47
Closing as there is not enough info for us to act upon.

**Closed** 2022-11-09 16:47 UTC
Labels: 0.kind: bug, 6.topic: GNOME
