### ISSUE TITLE
mitmproxy: checks fail while building

### ISSUE THREAD

**Issue by bouk** [NixOS/nixpkgs#170902] opened 2022-04-29 12:35 UTC
### Describe the bug

mitmproxy tests fail while building

### Steps To Reproduce
Steps to reproduce the behavior: `nix-shell -p mitmproxy`

### Expected behavior

I'm able to run `mitmproxy`

### Screenshots

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/97820/165945159-f3628b8e-c535-4495-b943-cfa88b1cdd3a.png">

### Additional context

Full build log can be found here: https://gist.github.com/bouk/cb7a8864fd6f224736f735b226b6e08a

The error in the failing tests seems to be `MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this.`

### Notify maintainers

@fpletz @kamilchm

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.3.0, macOS 12.2.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.7.0`
 - channels(bouke): `"darwin, nixpkgs"`
 - channels(root): `""`
 - nixpkgs: `/Users/bouke/.nix-defexpr/channels/nixpkgs`
```

**Comment by fabaff** [comment] 2022-04-30 13:47
This could be a darwin issue. `nix-shell -p mitmproxy` works for me on x86_64.

**Comment by bouk** [comment] 2022-05-05 12:42
It seems to be a `pyOpenSSL` issue: https://github.com/pyca/pyopenssl/issues/873

Interestingly, installing the Homebrew version does work. From the issue linked, it seems that upgrading Python to 3.10 might work.

**Comment by SuperSandro2000** [comment] 2022-06-25 20:50
dupe of #175875

**Closed by SuperSandro2000** 2022-06-25 20:50 UTC
Labels: 0.kind: bug
