### ISSUE TITLE
`python39Packages.flax` build failure on x86_64-linux as of `7d9f27f9`

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#186020] opened 2022-08-11 00:13 UTC
## Issue description
Build of `python39Packages.flax` failed on x86_64-linux as of 7d9f27f92df31b59cac7b922a7a4e7ca07cca428. This is currently breaking `python39Packages.flax`.

```
error: builder for '/nix/store/2mygyb58xqqldbc4fyc1z7c9f9xqxgcg-python3.9-flax-0.5.2.drv' failed with exit code 1;
       last 10 log lines:
       > Executing pipInstallPhase
       > /build/source/dist /build/source
       > Processing ./flax-0.5.2-py3-none-any.whl
       > Requirement already satisfied: matplotlib in /nix/store/f3gyqvdlan732fp262rkfgpcqykxb73j-python3.9-matplotlib-3.5.2/lib/python3.9/site-packages (from flax==0.5.2) (3.5.2)
       > Requirement already satisfied: PyYAML>=5.4.1 in /nix/store/pmz6svgrsd52l341gxxcnrc9a773i99i-python3.9-pyyaml-6.0/lib/python3.9/site-packages (from flax==0.5.2) (6.0)
       > Requirement already satisfied: typing-extensions>=4.1.1 in /nix/store/wzyjzir2ns21fi64zaqsrh8666pp6bzd-python3.9-typing-extensions-4.3.0/lib/python3.9/site-packages (from flax==0.5.2) (4.3.0)
       > Requirement already satisfied: numpy>=1.12 in /nix/store/n8mb6hlv95r2153srgqpkflnb4sbkpbi-python3.9-numpy-1.23.1/lib/python3.9/site-packages (from flax==0.5.2) (1.23.1)
       > ERROR: Could not find a version that satisfies the requirement rich~=11.1 (from flax) (from versions: none)
       > ERROR: No matching distribution found for rich~=11.1
       > 
       For full logs, run 'nix log /nix/store/2mygyb58xqqldbc4fyc1z7c9f9xqxgcg-python3.9-flax-0.5.2.drv'.
```

[full build log](https://github.com/samuela/nixpkgs-upkeep/actions/runs/2836537058)

python39Packages.flax maintainers cc: @ndl
python39Packages.flax maintainers cc: @ndl
Other cc: n/a

### Steps to reproduce
1. Checkout nixpkgs at commit 7d9f27f92df31b59cac7b922a7a4e7ca07cca428
2. Run `nix-build -A python39Packages.flax`

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-1014-azure, Ubuntu, 20.04.4 LTS (Focal Fossa), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - nixpkgs: `/nix/store/qj71476bphwg02khm2wy9rhvkzp9wmx7-source`
```

## Misc.
This issue was automatically generated by [nixpkgs-upkeep](https://github.com/samuela/nixpkgs-upkeep).
- [CI workflow](https://github.com/samuela/nixpkgs-upkeep/actions/runs/2836537058) that created this issue.
- Internal tags: 8301404242985698878 -7385833574874187433

**Comment by onny** [comment] 2022-08-17 11:44
Duplicate of https://github.com/NixOS/nixpkgs/issues/187044

**Closed by onny** 2022-08-17 11:44 UTC
Labels: 6.topic: python
