### ISSUE TITLE
wxwidgets fails to build on OSX

### ISSUE THREAD

**Issue by epipping** [NixOS/nixpkgs#16066] opened 2016-06-08 09:21 UTC
## Issue description

Here's the output that I get:

```
In file included from ./include/wx/osx/private.h:4:
./include/wx/osx/core/private.h:55:10: fatal error: 'Carbon/Carbon.h' file not found
#include <Carbon/Carbon.h>
         ^
4 warnings and 1 error generated.
Makefile:28754: recipe for target 'basedll_filefn.o' failed
make: *** [basedll_filefn.o] Error 1
builder for ‘/nix/store/ab4il1siki6x8vbr8lmjr0mp472674bi-wxwidgets-3.0.2.drv’ failed with exit code 2
```
### Steps to reproduce

E.g. `nix-env -i wxmaxima`.
## Technical details
- System: OS X 10.11.6 Beta (15G7b)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.09pre83147.df89584"

**Comment by FRidh** [comment] 2016-06-08 16:27
Do you know whether wxPython 3.0 functioned before #15764 ?

**Comment by FRidh** [comment] 2016-06-08 16:29
It seems like it should just be a matter of adding some dependencies for Darwin/OSX.
@copumpkin were you using Nix on Darwin?

**Comment by pipping** [comment] 2016-06-08 16:31
@FRidh I don't, unfortunately. I've only tried this today, for the first time.

**Comment by mbucc** [comment] 2016-08-28 14:52
Same error here:

* System: OS X 10.9.5
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre-git"

Pulled from github.com/nixpkgs this morning.

**Comment by FRidh** [comment] 2016-08-28 15:07
I guess `darwin.Carbon` needs to be added

**Comment by mbucc** [comment] 2016-08-28 15:16
@FRidh Dunno.  @matthewbauer pull request says it fixes this issue; I'm trying that now.

**Comment by FRidh** [comment] 2016-08-28 15:20
Seems it will use Cocoa now https://github.com/NixOS/nixpkgs/pull/16192/files#diff-820eed189b664d8e60bb47d4055b0189R32

**Comment by mbucc** [comment] 2016-08-28 15:37
Had wxmac installed and got this error message after building @matthewbauer's patch:

```
collision between ‘/nix/store/v937kg1xdjjdnr9pk2hn79jvqs9d12hk-wxwidgets-3.1.0/bin/wx-config’ and ‘/nix/store/8abyzj37rfxk82bdbmq48zsqsyc8in8k-wxmac-3.0.2/bin/wx-config’; use ‘nix-env --set-flag priority NUMBER PKGNAME’ to change the priority of one of the conflicting packages
builder for ‘/nix/store/gw8cigzlbmyj56a91hmvsvqiim8y2bs1-user-environment.drv’ failed with exit code 255
error: build of ‘/nix/store/gw8cigzlbmyj56a91hmvsvqiim8y2bs1-user-environment.drv’ failed
```

uninstalling wxmac worked

```
~/src/nixpkgs$ nix-env --uninstall wxmac
uninstalling ‘wxmac-3.0.2’
~/src/nixpkgs$ nix-env -i wxwidgets-3.1.0
warning: there are multiple derivations named ‘wxwidgets-3.1.0’; using the first one
installing ‘wxwidgets-3.1.0’
building path(s) ‘/nix/store/nsmdkv3bl1cias1y9qdg2dxl17fxryqc-user-environment’
created 513 symlinks in user environment
~/src/nixpkgs$ 
```

**Comment by mdaiter** [comment] 2016-12-25 16:43
This still fails when building 2.8 (default version) due to wxGTK being unable to find specific framework versions (10.6) of Carbon. The default go-to is to download the 10.6 Carbon version and pass the argument to the configure script. How should we go about fixing this?


I have a PR-ready version of the package which pulls in all appropriate frameworks (Carbon, Cocoa, CoreServices).

**Comment by veprbl** [comment] 2017-02-15 02:17
(triage) Steps to reproduce from this ticket doesn't fail currently (probably because it uses wxMac30 now). Is there still a problem?

**Comment by matthewbauer** [comment] 2017-04-21 06:35
Looks like we can close this.

**Comment by vcunat** [comment] 2017-11-05 09:52
Yes, seems OK on Hydra.

**Closed by vcunat** 2017-11-05 09:52 UTC
Labels: 0.kind: bug
