### ISSUE TITLE
Build failure: mosh

### ISSUE THREAD

**Issue by Samasaur1** [NixOS/nixpkgs#349449] opened 2024-10-18 04:44 UTC
### Steps To Reproduce

1. build mosh

### Build log

<https://gist.github.com/Samasaur1/73a8f81618835b9e78f1b8603ab7f437>

This gist contains the log (in "mosh log", and I also reran the build with `--keep-failed` and uploaded the `config.log` file referenced by the build log.

### Additional context

`mosh` builds fine on x86_64-linux. I don't have an `aarch64-linux` machine to test.

It fails on `x86_64-darwin`, with what looks like the same error.

### Notify maintainers

@skeuchel 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix run nixpkgs#nix-info -- -m
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.6.0, macOS 14.6.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source`
```

```console
[user@system:~]$ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.20.5`
 - nixpkgs: `/nix/store/0az17ihialzgdlg2r9jinzmh23dka8qz-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ilyagr** [comment] 2024-10-19 18:23
Adding a couple more people that might know something about the mosh package and protobuf problems (which I think caused this): @yu-re-ka @razielgn @GaetanLepage @tobim

**Comment by skeuchel** [comment] 2024-10-20 13:31
A git bisect (with pinning tzdata) shows that indeed [7cdaa0b80c9da64b2acb6cc8e8f73d2f4489aaeb](https://github.com/NixOS/nixpkgs/commit/7cdaa0b80c9da64b2acb6cc8e8f73d2f4489aaeb) is the first bad commit. Digging a bit deeper shows that the protobuf_CFLAGS are a bit messed up on darwin.

The following
```
$ nix develop nixpkgs#mosh
$ pkg-config --cflags protobuf
```
yields CFLAGS with a lot of repetition (which I reduced below) and the offending SHELL arguments
```
-DPROTOBUF_USE_DLLS
-Wno-float-conversion -Wno-implicit-float-conversion -Wno-implicit-int-float-conversion -Wno-unknown-warning-option -DNOMINMAX
-Wno-float-conversion -Wno-implicit-float-conversion -Wno-implicit-int-float-conversion -Wno-unknown-warning-option -DNOMINMAX
...
-Wno-float-conversion -Wno-implicit-float-conversion -Wno-implicit-int-float-conversion -Wno-unknown-warning-option -DNOMINMAX
-Wno-float-conversion -Wno-implicit-float-conversion -Wno-implicit-int-float-conversion -Wno-unknown-warning-option -DNOMINMAX
SHELL:-Xarch_x86_64 -maes SHELL:-Xarch_x86_64 -msse4.1 SHELL:-Xarch_arm64 -march=armv8-a+crypto -Wno-unused-command-line-argument
-Wno-float-conversion -Wno-implicit-float-conversion -Wno-implicit-int-float-conversion -Wno-unknown-warning-option -DNOMINMAX
SHELL:-Xarch_x86_64 -maes SHELL:-Xarch_x86_64 -msse4.1 SHELL:-Xarch_arm64 -march=armv8-a+crypto -Wno-unused-command-line-argument
-Wno-float-conversion -Wno-implicit-float-conversion -Wno-implicit-int-float-conversion -Wno-unknown-warning-option -DNOMINMAX
-Wno-float-conversion -Wno-implicit-float-conversion -Wno-implicit-int-float-conversion -Wno-unknown-warning-option -DNOMINMAX
...
-Wno-float-conversion -Wno-implicit-float-conversion -Wno-implicit-int-float-conversion -Wno-unknown-warning-option -DNOMINMAX
-Wno-float-conversion -Wno-implicit-float-conversion -Wno-implicit-int-float-conversion -Wno-unknown-warning-option -DNOMINMAX
-I/nix/store/6k6nd7v0giy0xg9vqgn7kzfirs1bw275-protobuf-28.2/include
-I/nix/store/rlwy1nw8svzvyfv6lqxxczqrgvzg19w1-abseil-cpp-20240722.0/include
```

**Comment by skeuchel** [comment] 2024-10-20 14:14
So it turns out this is a regression of abseil-cpp 20240722 which was introduced in https://github.com/abseil/abseil-cpp/pull/1710 and fixed by https://github.com/abseil/abseil-cpp/pull/1738 which is not yet in an upstream release of abseil.

**Comment by skeuchel** [comment] 2024-10-24 08:48
Compiled successfully for [aarch64-darwin on hydra](https://hydra.nixos.org/job/nixpkgs/staging-next/mosh.aarch64-darwin). The [x86_64-darwin job](https://hydra.nixos.org/build/276206067) is still queued but I built it locally.

**Closed by skeuchel** 2024-10-24 08:48 UTC
Labels: 6.topic: darwin, 0.kind: build failure
