### ISSUE TITLE
GPG: No pinentry

### ISSUE THREAD

**Issue by ysndr** [NixOS/nixpkgs#35464] opened 2018-02-24 11:11 UTC
## Issue description
Changing `pinentry-program` to an alternative pinentry in `~/.gnupg/gpg-agent.conf` results in gpg not being able to find the pinentry.
I specifically tried with pinentry-kwallet and pinentry-qt

### Steps to reproduce
add
   
```
...
pinentry-program /home/<user>/.nix-profile/bin/pinentry-kwallet
...
```
to `~/.gnupg/gpg-agent.conf`

(I don't really know which of these is actually necessary)

```
$ gpgconf --reload gpg-agent
$ gpg-connect-agent /bye

$ gpg-connect-agent <<EOT
GET_CONFIRMATION Hello
EOT

> ERR 67108949 No pinentry <GPG Agent>
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.82, NixOS, 17.09.3031.d09e425aea3 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-unstable-18.03pre127921.9b25b9347d9, nixos-17.09.3031.d09e425aea3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by rnhmjoj** [comment] 2018-02-24 11:52
Are you sure the path of the executable is correct?
I have `pinentry-program /run/current-system/sw/bin/pinentry-curses` in my config and it's working; I tried also pinentry-qt and pinentry-gtk but I and the all work ok.

**Comment by ysndr** [comment] 2018-02-24 12:45
I have pinentry and kwalletcli (for pinentry-kwallet) installed to my user profile in contrast to having it declared in configuration.nix... I'll try changing this and report back.

**Comment by ysndr** [comment] 2018-02-24 13:00
actually I recognized that if I stop the gpg-agent socket manually (`systemctl --user stop  gpg-agent.socket`) the gpg-agent starts itself up again using the correct pinentry. Yet, after a reboot or even login it breaks again but can be resolved the same way..

**Comment by rnhmjoj** [comment] 2018-02-24 13:45
`gpgconf --reload gpg-agent` was enough for it to change the pinentry program. I don't use the user service but start the agent from the shell, the old way. That must be the cause or related at least.

**Comment by bfortz** [comment] 2018-04-24 11:13
My experience is that the gpg-agent socket launched at session start by systemd does not play well with user-set agents in gpg-agent.conf. If you have programs.gnupg.agent = true; in your configuration.nix file, removing it should solve your problem. (If you use nixpkgs on another linux distribution, systemctl disable gpg-agent.socket should do the trick).

**Comment by ysndr** [comment] 2018-04-24 18:09
Hmm interesting
I actually got it kinda working by using the override of the gnupg package so everything else can be set using options

**Comment by bburdette** [comment] 2020-09-30 14:52
This is still broken for me; the `gpgconf --reload gpg-agent` trick works but that shouldn't be necessary.

**Comment by rnhmjoj** [comment] 2020-09-30 16:25
Are you using NixOS? What's your configuration?
There have been some changes to how the gpg-agent is set up, see #72597.

**Comment by bburdette** [comment] 2020-09-30 16:47
Yes I'm using nixos.  What do you mean by configuration?  I use xmonad and I don't have gnome, if that's what you mean.  I haven't set `programs.gnupg.agent.enable = true` in my configuration.nix.  I installed gpg, pinentry, pinentry-curses, and gnupg1 by putting them in my environment.systemPackages.  I'm on nixos-20.03.  I wasn't aware that gpg required a gpg-agent so I didn't look that up in the nixos options.

**Comment by rnhmjoj** [comment] 2020-10-01 10:56
> I haven't set programs.gnupg.agent.enable = true

Ok, that's what I was asking. 

> I wasn't aware that gpg required a gpg-agent so I didn't look that up in the nixos options.

No, it's not, or at least it's shouldn't be.

Since I'm using that module myself I'm not sure, I'll have to try it out.
In any case gnupg is built with pinentry (pinentry-gtk I think) support so it should work. However I'm not sure about setting the pinentry-program from the configuration.

**Comment by rnhmjoj** [comment] 2020-10-15 07:49
So, I did a little bit of research and figured that yes, in the past it was possible to use gnupg without an agent but starting with 2.0 is mandatory. See [here](https://dev.gnupg.org/T2858#92654) for an explanation.

What's happening here is that `gpg` check if an agent is already running; if not it spawns a new one, which proceeds to check if pinetry is available but fails because it can't find the binary on NixOS. The solution is to either let NixOS manage the agent or start the agent manually.

**Comment by srid** [comment] 2020-11-26 03:05
Has anyone figured a solution to this problem? Is gpg-agent entirely broken in nixpkgs? What the heck is "pinentry" anyway?

**Comment by rnhmjoj** [comment] 2020-11-26 07:35
> What the heck is "pinentry" anyway?

The pinentry is a program that prompts for the passphrase needed to decrypt your private key. There's more than one: pinentry-curses uses ncurses to draw the prompt in the terminal, pinentry-gtk and pinentry-qt are graphical and open a window, pinentry-gnome is for gnome, etc.

> Has anyone figured a solution to this problem? 

As I said, gpg2 requires an agent to handle the keys, which in turns uses pinentry to ask for passphrases when necessary.
You can either use NixOS (or home-manager) to manage the agent *or* do it manually, but you have to make sure the agent knows the path to the pinentry binary.

If you start the agent manually you can add `--pinentry-program=/run/current-system/sw/bin/pinentry-whatever`. Or you can add the same option to `$GPG_HOME/gpg-agent.conf`

> Is gpg-agent entirely broken in nixpkgs?

No

**Comment by srid** [comment] 2020-11-26 17:31
@rnhmjoj Here's my Nix config: https://github.com/srid/nix-config/commit/02b77250447c9acfd88a0b104e862203945dee6c

You can see it has `programs.gnupg.agent` enabled. And I can start it with `systemctl --user start gpg-agent`, which runs the agent with the appropriate pinentry:

```
$ ps -ef  | grep gpg
srid     11459  2099  0 12:25 ?        00:00:00 /nix/store/jy6afw1bkmrmc68jb13asvhzhxy47w4w-gnupg-2.2.23/bin/gpg-agent --supervised --pinentry-program /nix/store/nr7sh8crr6z3rb88s30ykdz1wkw1iqmw-pinentry-1.1.0-curses/bin/pinentry
srid     11470  7942  0 12:26 pts/4    00:00:00 grep gpg
```

**However**, running gpg elsewhere somehow replaces this process with something else?

```
$ gpg-connect-agent
gpg-connect-agent: no running gpg-agent - starting '/nix/store/jy6afw1bkmrmc68jb13as
gpg-connect-agent: waiting for the agent to come up ... (5s)
gpg-connect-agent: connection to agent established

[srid@bebe:~]$ ps -ef | grep gpg
srid     11946     1  0 12:27 ?        00:00:00 gpg-agent --homedir /home/srid/.gnupg --use-standard-socket --daemon
srid     12205 11681  0 12:29 pts/5    00:00:00 grep gpg
```

>> Is gpg-agent entirely broken in nixpkgs?
> No

What could be wrong in my configuration?

**Comment by rnhmjoj** [comment] 2020-11-26 20:19
Your config is correct: It must be gpg is looking for the agent socket in the wrong place, somehow.
Do you happen to have `GNUPGHOME` set? That can cause [problems](https://github.com/NixOS/nixpkgs/issues/72597#issuecomment-549095697).

**Comment by srid** [comment] 2020-11-26 21:36
No, I only have GPG_TTY set.

![image](https://user-images.githubusercontent.com/3998/100392707-5c981900-302f-11eb-8a23-3c7ea606b8aa.png)

Unsetting that env produces the same error.

![image](https://user-images.githubusercontent.com/3998/100392743-746f9d00-302f-11eb-8910-6c0c864dfd98.png)

**Comment by srid** [comment] 2020-11-26 21:40
FWIW, the systemctl one has `--supervised`; whereas the only manually launched uses `--use-standard-socket --daemon`.

**Comment by rnhmjoj** [comment] 2020-11-27 12:26
Try running this: `strace gpg-connect-agent /bye 2>&1 | grep S.gpg-agent`.
It should print which socket gpg is trying to access:
```shell
stat("/run/user/1000/gnupg/S.gpg-agent", {st_mode=S_IFSOCK|0600, st_size=0, ...}) = 0
stat("/run/user/1000/gnupg/S.gpg-agent", {st_mode=S_IFSOCK|0600, st_size=0, ...}) = 0
connect(3, {sa_family=AF_UNIX, sun_path="/run/user/1000/gnupg/S.gpg-agent"}, 34) = 0
```

**Comment by srid** [comment] 2020-11-27 17:29
Looks like it is trying to locate the sockets in wrong location:

```
stat("/run/user/1000/gnupg/S.gpg-agent", 0x7fffa0c079d0) = -1 ENOENT (No such file or directory)
stat("/run/user/1000/gnupg/S.gpg-agent", 0x7fffa0c079d0) = -1 ENOENT (No such file or directory)
connect(3, {sa_family=AF_UNIX, sun_path="/run/user/1000/gnupg/S.gpg-agent"}, 34) = -1 ENOENT (No such file or directory)
stat("/run/user/1000/gnupg/S.gpg-agent", 0x7fffa0c079d0) = -1 ENOENT (No such file or directory)
stat("/run/user/1000/gnupg/S.gpg-agent", 0x7fffa0c079d0) = -1 ENOENT (No such file or directory)
connect(3, {sa_family=AF_UNIX, sun_path="/run/user/1000/gnupg/S.gpg-agent"}, 34) = -1 ENOENT (No such file or directory)
stat("/run/user/1000/gnupg/S.gpg-agent", {st_mode=S_IFSOCK|0700, st_size=0, ...}) = 0
stat("/run/user/1000/gnupg/S.gpg-agent", {st_mode=S_IFSOCK|0700, st_size=0, ...}) = 0
connect(3, {sa_family=AF_UNIX, sun_path="/run/user/1000/gnupg/S.gpg-agent"}, 34) = 0
```

The `gpg-agent` launched by systemd does not create any socket under `/run/user/1000/gnupg/`. That is *very strange*, because its logs do indicate that:

```
Nov 27 12:28:00 bebe gpg-agent[18372]: using fd 3 for std socket (/run/user/1000/gnupg/S.gpg-agent)
```

**Comment by rnhmjoj** [comment] 2020-11-27 18:02
The location is the right one: the user service *should* be opening the socket there.
Can you check again with this? `lsof -Uap (pidof gpg-agent)`

**Comment by srid** [comment] 2020-11-27 19:12
```
[nix-shell:~/nix-config]$ lsof -Uap $(pidof gpg-agent)
COMMAND     PID USER   FD   TYPE             DEVICE SIZE/OFF    NODE NAME
gpg-agent 24537 srid    1u  unix 0x0000000000000000      0t0 1371850 type=STREAM (CONNECTED)
gpg-agent 24537 srid    2u  unix 0x0000000000000000      0t0 1371850 type=STREAM (CONNECTED)
gpg-agent 24537 srid    3u  unix 0x0000000000000000      0t0   84811 /run/user/1000/gnupg/S.gpg-agent type=STREAM (LISTEN)

[nix-shell:~/nix-config]$ stat /run/user/1000/gnupg/S.gpg-agent
stat: cannot statx '/run/user/1000/gnupg/S.gpg-agent': No such file or directory

[nix-shell:~/nix-config]$ ls -al /run/user/1000/gnupg/
total 0
drwx------  2 srid users  40 Nov 27 14:11 .
drwx------ 16 srid users 600 Nov 27 12:38 ..

[nix-shell:~/nix-config]$
```

**Comment by cirno-999** [comment] 2020-11-27 21:33
I think I have the same issue?

```
$ gpg --full-gen-key
[...]
Change (N)ame, (C)omment, (E)mail or (O)kay/(Q)uit? o
We need to generate a lot of random bytes. It is a good idea to perform
some other action (type on the keyboard, move the mouse, utilize the
disks) during the prime generation; this gives the random number
generator a better chance to gain enough entropy.
gpg: agent_genkey failed: No pinentry
Key generation failed: No pinentry
```
gpg-connect-agent works, I think.
```
[cirno@berlin:~]$ gpg-connect-agent
>
```

**Comment by rnhmjoj** [comment] 2020-11-28 09:03
@srid It looks like something deleted the socket file, but it's still open by the gpg-agent service.  I have no idea how.
What does `systemctl status gpg-agent` says? I would try to log out and in again to see if the file is recreated.

@cirno-999 To confirm, try running `lsof -Uap (pidof gpg-agent)` and `strace gpg-connect-agent /bye 2>&1 | grep S.gpg-agent` and post te output.

**Comment by cirno-999** [comment] 2020-11-28 12:24
> @cirno-999 To confirm, try running `lsof -Uap (pidof gpg-agent)` and `strace gpg-connect-agent /bye 2>&1 | grep S.gpg-agent` and post te output.

[cirno@berlin:~]$ lsof -Uap $(pidof gpg-agent)
COMMAND    PID  USER   FD   TYPE             DEVICE SIZE/OFF    NODE NAME
gpg-agent 7373 cirno    3u  unix 0x0000000000000000      0t0 2147950 /run/user/1002/gnupg/S.gpg-agent type=STREAM
gpg-agent 7373 cirno    4u  unix 0x0000000000000000      0t0 2147952 /run/user/1002/gnupg/S.gpg-agent.extra type=STREAM
gpg-agent 7373 cirno    5u  unix 0x0000000000000000      0t0 2147954 /run/user/1002/gnupg/S.gpg-agent.browser type=STREAM
gpg-agent 7373 cirno    6u  unix 0x0000000000000000      0t0 2147956 /run/user/1002/gnupg/S.gpg-agent.ssh type=STREAM

[cirno@berlin:~]$ strace gpg-connect-agent /bye 2>&1 | grep S.gpg-agent
stat("/run/user/1002/gnupg/S.gpg-agent", {st_mode=S_IFSOCK|0700, st_size=0, ...}) = 0
stat("/run/user/1002/gnupg/S.gpg-agent", {st_mode=S_IFSOCK|0700, st_size=0, ...}) = 0
connect(3, {sa_family=AF_UNIX, sun_path="/run/user/1002/gnupg/S.gpg-agent"}, 34) = 0

**Comment by rnhmjoj** [comment] 2020-11-28 18:09
It's connecting to the agent all right, It's not the same issue. I'm not sure what's going on: you could try tracing `gpg --full-gen-key`.

**Comment by cirno-999** [comment] 2020-11-28 19:56
>tracing
might be a dumb question, but how?

**Comment by rnhmjoj** [comment] 2020-11-29 00:51
Sorry, I meant something like this `strace gpg --full-generate-key 2>log`. 
gpg should try to contact the agent (just after confirming the key info), around the same time, in the `log` file you should see:
```strace
getuid()                                = 1000
stat("/run/user/1000/gnupg/S.gpg-agent", {st_mode=S_IFSOCK|0600, st_size=0, ...}) = 0
socket(AF_UNIX, SOCK_STREAM, 0)         = 4
stat("/run/user/1000/gnupg/S.gpg-agent", {st_mode=S_IFSOCK|0600, st_size=0, ...}) = 0
connect(4, {sa_family=AF_UNIX, sun_path="/run/user/1000/gnupg/S.gpg-agent"}, 34) = 0
read(4, "OK Pleased to meet you, process "..., 1002) = 37
write(4, "RESET", 5)                    = 5
write(4, "\n", 1)                       = 1
read(4, "OK\n", 1002)                   = 3
write(4, "OPTION ttyname=/dev/tty1", 24) = 24
write(4, "\n", 1)                       = 1
read(4, "OK\n", 1002)                   = 3
write(4, "OPTION ttytype=rxvt-256color", 28) = 28
write(4, "\n", 1)                       = 1
read(4, "OK\n", 1002)                   = 3
write(4, "OPTION lc-ctype=en_GB.UTF-8", 27) = 27
write(4, "\n", 1)                       = 1
read(4, "OK\n", 1002)                   = 3
write(4, "OPTION lc-messages=en_GB.UTF-8", 30) = 30
write(4, "\n", 1)                       = 1
read(4, "OK\n", 1002)                   = 3
write(4, "GETINFO version", 15)         = 15
write(4, "\n", 1)                       = 1
read(4, "D 2.2.23\nOK\n", 1002)         = 12
write(4, "OPTION allow-pinentry-notify", 28) = 28
write(4, "\n", 1)                       = 1
read(4, "OK\n", 1002)                   = 3
write(4, "OPTION agent-awareness=2.1.0", 28) = 28
write(4, "\n", 1)                       = 1
read(4, "OK\n", 1002)                   = 3
```
In your case, it should try to connect to the socket `/run/user/1002/gnupg/S.gpg-agent`.

**Comment by cirno-999** [comment] 2020-11-29 01:56
I've had to restart my PC for some reason, and now it works... I guess no point in debugging now ''^^

**Comment by srid** [comment] 2021-01-15 21:42
Same. Restarting fixed it.

**Comment by milahu** [comment] 2021-01-24 08:22
had to restart the `gpg-agent`

```
nix-shell -p killall --run 'killall gpg-agent'
```

**Comment by mixmixmix** [comment] 2021-01-27 10:07
I tried restarting and different settings suggested here. I was using gpg with pinentry-curses without issues until today when I updated packages and I get "No pinentry" error. 

Not sure even where to start. I don't understand why gpg doesn't read the `gpg-agent.conf` file nor why it doesn't just use default `pinentry` that works if I type it in a console. 

Clearly gpg-related environment on NixOS is a bit different than on other distros. Is there any documentation that would help explain what is the correct way of configuring it? 

This issue was closed when @ysndr "got it kinda working", but it keeps coming back with every update.

Thanks for any directions,
M

**Comment by ysndr** [comment] 2021-01-27 11:14
I see this is wtill real problem so I consider reopening the issue as there seems to be no real solution to it yet.

**Comment by rnhmjoj** [comment] 2021-01-27 12:54
Following this discussion is very difficult because there actually three or more different issues:

1. @bburdette issue: a gpg-agent **must** be installed and running to use gpg2. Solution: https://github.com/NixOS/nixpkgs/issues/35464#issuecomment-708968597

2. @srid issue: the gpg-agent socket is missing, possibly it was deleted. Check to confirm the issue: https://github.com/NixOS/nixpkgs/issues/35464#issuecomment-734811503

3. @cirno-999 issue: unknown cause, stopped investigating.

Please close this issue and stop writing here. If you want help, open a new issue in which you describe in detail your setup:

1. What's your NixOS configuration? Example:
    ```
    programs.gnupg.agent = {
      enable = true;
      enableSSHSupport = true;
      pinentryFlavor = "curses";
    };
    ```
2. What's in your `gpg-agent.conf`? Example:
    ```
   enable-ssh-support
   disable-scdaemon
   default-cache-ttl 21600
   default-cache-ttl-ssh 21600
   max-cache-ttl 21600
   max-cache-ttl-ssh 21600
    ```
3. Are you using the systemd user service (with or without socket activation)? Provide the output of `systemctl --user status gpg-agent` if so.

4. Do the gpg sockets files exist? Check with `ls /run/user/$(id -u)/gnupg`

otherwise it's impossible to help you and probably make matters more confusing for other users.

**Closed** 2021-01-27 12:56 UTC

**Comment by steve-chavez** [comment] 2021-08-22 20:56
The below worked for me(couldn't reboot because it was a server):

```bash
gpgconf --kill gpg-agent
```

**Comment by KenMacD** [comment] 2022-03-30 22:51
I ran in to this issue. For some reason gpg isn't finding the sockets in `XDG_RUNTIME_DIR`. For others that might find the same, this is what worked for me:

```bash
ln -t ~/.gnupg/ -s $XDG_RUNTIME_DIR/gnupg/S.gpg-agent
ln -t ~/.gnupg/ -s $XDG_RUNTIME_DIR/gnupg/S.gpg-agent.browser
ln -t ~/.gnupg/ -s $XDG_RUNTIME_DIR/gnupg/S.gpg-agent.extra
ln -t ~/.gnupg/ -s $XDG_RUNTIME_DIR/gnupg/S.gpg-agent.ssh
ln -t ~/.gnupg/ -s $XDG_RUNTIME_DIR/gnupg/S.scdaemon
```

**Comment by mcdonc** [comment] 2023-07-18 16:43
Note that the "bug" of "no pinentry" still exists in 23.05 but a reboot seems to fix it.

**Comment by Kreyren** [comment] 2023-12-25 05:18
> Note that the "bug" of "no pinentry" still exists in 23.05 but a reboot seems to fix it.

In 23.11

**Comment by codingCoffee** [comment] 2024-03-17 20:35
Faced this issue on `nixos-unstable` branch, but `gpgconf --reload gpg-agent` fixed it for me

**Comment by Kreyren** [comment] 2024-05-28 02:07
In 24.05, the `gpgconf --reload gpg-agent` doesn't fix the issue for me.

```
$  echo test | gpg --clear-sign
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

test
gpg: signing failed: No pinentry
gpg: [stdin]: clear-sign failed: No pinentry

$ gpgconf --reload gpg-agent

$ echo test | gpg --clear-sign
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

test
gpg: signing failed: No pinentry
gpg: [stdin]: clear-sign failed: No pinentry

$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.10-xanmod1, NixOS, 24.05 (Uakari), 24.05.20240524.d12251e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-23.05"`
 - channels(raptor): `"home-manager-23.05.tar.gz, nixpkgs-23.05, nixpkgs-unstable-23.05"`
 - nixpkgs: `/home/kreyren/.nix-defexpr/channels/nixpkgs
 
$ gpgconf --kill gpg-agent
 
$ echo test | gpg --clear-sign
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

test
gpg: signing failed: No pinentry
gpg: [stdin]: clear-sign failed: No pinentry
```
