### ISSUE TITLE
Build failure: llvm-16.0.6

### ISSUE THREAD

**Issue by cwp** [NixOS/nixpkgs#284056] opened 2024-01-26 16:49 UTC
### Steps To Reproduce

1. build -A libllvm

### Build log

[9gc2yymj7m5fc0hxxma2afyifbn86yj6-llvm-16.0.6.log](https://gist.github.com/cwp/4468627c2fbc3717a45344d8d1bb5da6)

### Additional context

Discovered this when trying to test #275701 

### Notify maintainers

Dunno who would be appropriate

### Metadata

```console
~> nix-shell -p nix-info --run "nix-info -m"
these 2 paths will be fetched (0.01 MiB download, 0.11 MiB unpacked):
  /nix/store/hrcw8p4cymhyb959w21ha5g1n3dm69n4-DarwinTools-1
  /nix/store/x2v35n7y8ihdwl73dzvjzjlgg4h4lsq9-nix-info
copying path '/nix/store/hrcw8p4cymhyb959w21ha5g1n3dm69n4-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/x2v35n7y8ihdwl73dzvjzjlgg4h4lsq9-nix-info' from 'https://cache.nixos.org'...
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.1.0, macOS 14.1.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixpkgs"`
 - channels(cwp): `"23.11-23.11-darwin"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
 ```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by domenkozar** [comment] 2024-01-28 07:58
Maybe @toonn can help

**Comment by bergey** [comment] 2024-02-05 09:49
I have been encountering this failure on my Mac and finally got around to investigating.  This was [reported upstream](https://github.com/llvm/llvm-project/issues/64908) with [a patch to disable on Darwin](https://reviews.llvm.org/D158560#) but the patch was not accepted.  I skipped the test by adding `rm test/tools/llvm-objcopy/ELF/strip-preserve-atime.test` to [this postPatch phase where we remove other tests](https://github.com/nixos/nixpkgs/blob/master/pkgs/development/compilers/llvm/16/llvm/default.nix#L223).  This unblocks my work, although I suppose it would be better for Nixpkgs to only disable on Darwin, or for someone upstream to trace what is touching the file mid-test.

**Comment by toonn** [comment] 2024-02-06 16:17
I don't have a better workaround to this but I'm also not sure we should include such a workaround since Hydra appears to be unaffected?

Are there any common quirks to your respective setups, like mounting /tmp noatime or the file system?

**Comment by bergey** [comment] 2024-02-07 00:03
I think it's plausible that Crowdstrike reads the test file and updates the atime in the middle of the test.  (Company-owned Mac, so I can't turn this off to test.).  

Does Hydra build for ARM Macs?  Searching for llvm, I only see `aarch64-linux` and `x86_64-darwin`.  I've been assuming that this is why I'm building these locally, when I would prefer to download them from Hydra, but I could easily be wrong.

**Comment by toonn** [comment] 2024-02-07 19:14
It does, yes. At least AFAICT?
[This should be llvm 16 for aarch64-darwin](https://hydra.nixos.org/build/247527249)

This interaction between a test run and antivirus software would be pretty unfortunate. I wonder if upstream would be more amenable to finding a workaround?
Could they maybe unlink the file and pass it in by FD instead or something? To at least minimize the odds of another process getting a hold of it?

**Comment by 3541** [comment] 2024-02-07 22:41
I have been able to reliably reproduce the issue on a work machine running Crowdstrike, while it does not appear on my personal laptop.

**Comment by bergey** [comment] 2024-02-11 19:42
I'm glad we have this record of what's going on for the next person who runs into this.  It's not clear to me what the right packaging answer is.  I agree that upstream in llvm would be better than in nixpkgs, since I assume the problem is not unique to nixpkgs.

**Comment by rhoriguchi** [comment] 2024-02-16 00:18
The same issue arises with version `17.0.6` and `Microsoft Defender`.

**Comment by philiptaron** [comment] 2024-02-29 18:53
I'm blocked on x86_64-darwin by this silly issue. We already skip one test in this suite; it does no harm to skip this one, for much the same reasons (the exact filesystem on which this test is run is noisier than desired). Since the test failure causes the whole derivation to fail, it's more severe than just a flaky test.

**Comment by philiptaron** [comment] 2024-03-08 23:14
Fixed by https://github.com/NixOS/nixpkgs/pull/292379; when this hits master, we shouldn't see this issue any more.

**Closed by philiptaron** 2024-03-08 23:14 UTC
Labels: 0.kind: build failure
