### ISSUE TITLE
texdoc crashing

### ISSUE THREAD

**Issue by rayhogenson** [NixOS/nixpkgs#54286] opened 2019-01-18 21:19 UTC
## Issue description
What happens when I run texdoc:

    user@host ~> texdoc tikz
    [string "/nix/store/9x5lchlazvq333g3hg5568i7w5qzxn0d-t..."]:569: assertion failed!

Instead, I would like it to show me documentation.

When I run texdoc with no argument, it shows the help text, but any argument makes it crash.

### Steps to reproduce
Run texdoc with any argument at all

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/4m253khy42mqrv3l3kih6ar75fvi0wl5-bash-interactive-4.4-p23-dev
copying path '/nix/store/4m253khy42mqrv3l3kih6ar75fvi0wl5-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.92, NixOS, 18.09.1898.001b34abcb4 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(ray): `""`
 - channels(root): `"nixos-18.09.1898.001b34abcb4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by dotlambda** [comment] 2019-01-20 11:03
I've had this happen once. I think it was because I had multiple versions of TeX Live installed.

**Comment by leotaku** [comment] 2019-03-28 16:48
I also experience this issue. I have also tried installing TeXLive (nix-shell) on another machine that did not have any other TeX version installed.

@dotlambda 	would you mind explaining what you mean by "having multiple versions of TeXLive installed"?

**Comment by dotlambda** [comment] 2019-03-28 16:50
> @dotlambda would you mind explaining what you mean with "having multiple versions of TeXLive installed"?

e.g. having one in `environment.systemPackages` and installing the other via `nix-env -i`

**Comment by leotaku** [comment] 2019-03-28 17:01
@dotlambda 	So `texdoc` works for you when you only have one TeXLive distribution installed?

**Comment by dotlambda** [comment] 2019-03-28 17:12
Actually, I just tried and I'm getting the exact same error:
```
$ texdoc scrbook
[string "/nix/store/35p7wa7mikxrxzpy6bpnqxgyzzc4vqj7-t..."]:569: assertion failed!
```

**Comment by dotlambda** [comment] 2019-03-28 17:15
cc @vcunat

**Comment by veprbl** [comment] 2019-03-28 21:52
I can reproduce this on macOS. Can someone try on texlive-2017 or older?

**Comment by veprbl** [comment] 2019-03-28 22:15
https://github.com/TeX-Live/texdoc/issues/20

**Comment by veprbl** [comment] 2021-04-07 21:37
Closing in favor of #118757

**Closed by veprbl** 2021-04-07 21:37 UTC
Labels: 0.kind: bug, 6.topic: TeX
