### ISSUE TITLE
Package request: label-studio

### ISSUE THREAD

**Issue by Semnodime** [NixOS/nixpkgs#304914] opened 2024-04-17 22:15 UTC
**Project description**

**Metadata**

* homepage URL: https://labelstud.io/
* source URL: https://github.com/HumanSignal/label-studio
* license: [Apache 2.0 LICENSE](https://github.com/HumanSignal/label-studio/blob/develop/LICENSE)
* platforms: linux, docker

**Comment by pluiedev** [comment] 2024-12-28 15:22
Duplicate of #263060

**Closed by pluiedev** 2024-12-28 15:22 UTC
Labels: 6.topic: python, 6.topic: nodejs, 0.kind: packaging request
