### ISSUE TITLE
Package request: Immich

### ISSUE THREAD

**Issue by fliiiix** [NixOS/nixpkgs#279316] opened 2024-01-07 08:33 UTC
**Project description**

A self hosted alternative to google photos.

**Metadata**

* homepage URL: https://immich.app/
* source URL: https://github.com/immich-app/immich
* license: MIT
* platforms: Preferred unix-based operating system (Ubuntu, Debian, MacOS, etc) (https://immich.app/docs/install/requirements)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MikaelFangel** [comment] 2024-01-07 16:26
Duplicate of #267869

**Closed** 2024-01-07 16:26 UTC
Labels: 0.kind: packaging request

**Comment by fliiiix** [comment] 2024-01-07 16:48
woops no idea how i missed that, thanks :+1:
