### ISSUE TITLE
jl: build failure due to ghc 9

### ISSUE THREAD

**Issue by schuelermine** [NixOS/nixpkgs#168256] opened 2022-04-11 09:52 UTC
### Describe the bug
```
builder for '/nix/store/rhspfhlw8414pfy394l77v9mp7fyqahv-jl-0.0.5.drv' failed with exit code 1;
last 10 log lines:
>    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [7 of 9] Compiling JL.Inferer       ( src/JL/Inferer.hs, dist/build/JL/Inferer.o, dist/build/JL/Inferer.dyn_o )
>
> src/JL/Inferer.hs:12:1: warning: [-Wunused-imports]
>     The import of ‘Control.Monad.Writer’ is redundant
>       except perhaps to import instances from ‘Control.Monad.Writer’
>     To import instances alone, use: import Control.Monad.Writer()
>    |
> 12 | import           Control.Monad.Writer
>    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
For full logs, run 'nix log /nix/store/rhspfhlw8414pfy394l77v9mp7fyqahv-jl-0.0.5.drv'.
```

### Steps To Reproduce
1. Build `pkgs.jl`

### Notify maintainers
@fgaz 
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.1, NixOS, 22.05 (Quokka), 22.05.20220403.bc4b9ee`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220322_d5d4d98`
 - channels(root): `"nixos, nixpkgs"`
 - channels(anselmschueler): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by iblech** [comment] 2022-04-11 12:32
Thank you for reporting this issue; I can reproduce it. The problem is not in the warning displayed in the last 10 log lines, but in an earlier error:

```
[4 of 9] Compiling JL.Serializer    ( src/JL/Serializer.hs, dist/build/JL/Serializer.o, dist/build/JL/Se
rializer.dyn_o )

src/JL/Serializer.hs:39:30: error:
    • Couldn't match type ‘Data.HashMap.Internal.HashMap Text’
                     with ‘Data.Aeson.KeyMap.KeyMap’
      Expected: Object
        Actual: Data.HashMap.Internal.HashMap Text Value
    • In the first argument of ‘Object’, namely ‘(fmap coreToValue hm)’
      In the expression: Object (fmap coreToValue hm)
      In a case alternative:
          RecordCore hm -> Object (fmap coreToValue hm)
   |     
39 |     RecordCore hm -> Object (fmap coreToValue hm)
   |                              ^^^^^^^^^^^^^^^^^^^
```

Unfortunately I don't think that I will be able to contribute further to this issue.

**Comment by fgaz** [comment] 2022-04-14 19:37
I'm aware of this failure, but fixing it will require a bit of patching. Upstream didn't update the package to ghc 9 yet. Right now I don't have much time to do that, so in the meantime you could install it from stable, where it does build.

Please change the title to something like "jl: build failure due to ghc 9"

**Comment by cdepillabout** [comment] 2022-04-21 01:42
This has been correctly marked broken in [3e6d4c0](https://github.com/NixOS/nixpkgs/pull/168049/commits/3e6d4c00a9ad98fcdceb476aab68de2f92b752b2).

See also https://github.com/NixOS/nixpkgs/pull/168049 where there was a small amount of discussion about marking this broken.

**Comment by neilmayhew** [comment] 2022-05-15 19:54
I've created an upstream [PR](https://github.com/chrisdone/jl/pull/23).

**Comment by neilmayhew** [comment] 2022-05-18 02:28
The PR is now merged, and the package is now on Hackage for the first time. However, since it's not been added to Stackage Nightly yet, it won't make its way into `hackagePackages` for quite some time. I'll update the derivation to use the new version directly from Hackage.

**Closed** 2022-05-18 05:16 UTC
Labels: 6.topic: haskell, 9.needs: upstream fix, 0.kind: build failure
