### ISSUE TITLE
Package request: Polonium

### ISSUE THREAD

**Issue by Anseryde** [NixOS/nixpkgs#266479] opened 2023-11-09 15:16 UTC
**Project description**

Polonium is an unofficial successor to Bismuth built on 5.27, and a descendant of autotile.

**Metadata**

 homepage URL: https://github.com/zeroxoneafour/polonium
 source URL: https://github.com/zeroxoneafour/polonium
 license: MIT
 platforms: unix, linux, darwin, ...

**Comment by SuperSamus** [comment] 2023-11-09 15:57
Duplicate of #239369.

**Closed** 2023-11-09 23:25 UTC
Labels: 0.kind: packaging request
