### ISSUE TITLE
patch `bluez` to fix device disconnecting issues.

### ISSUE THREAD

**Issue by iosmanthus** [NixOS/nixpkgs#117663] opened 2021-03-26 06:55 UTC
**Describe the bug**
`bluez` 5.56 has a [bug](https://github.com/bluez/bluez/issues/113) that causes some Bluetooth devices to disconnect frequently. Archlinux have already released a [hotfix](https://github.com/archlinux/svntogit-packages/commit/674c53af0aaa856e91c8fa73735cd520a312317c#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a) to `bluez` 5.56.

**To Reproduce**
1. Upgrade to `bluez` 5.56
2. Connect to `JBL Go 2`, after a while it will disconnect at a random point.

**Additional context**

https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/732#note_849446

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.106, NixOS, 21.05pre277486.f5e8bdd07d1 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre278406.d3f7e969b98"`
 - channels(iosmanthus): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module: hardware.bluetooth
```

**Comment by GTrunSec** [comment] 2021-03-26 09:43
@ymatsiuk Do you have any idea to merge this patch to master ? https://gist.github.com/ymatsiuk/685fe9519723d77ae34e5aa6e59172f9. the downgrade of firmware-linux-nonfree must be here?

**Comment by ymatsiuk** [comment] 2021-03-26 10:44
@GTrunSec I wouldn't dare 🙂 I would expect that `bluez` guys will release a hotfix release ASAP if this is very critical and affects lots of people. Otherwise I don't see the reason of submitting this patch into master as it might impact other people's experience.

In my particular case the fix was:
* downgrade firmware
* install `pipewire` (`0.3.24`) and `bluez` (`5.56`) from `nixos-unstable`

**Comment by ymatsiuk** [comment] 2021-03-26 11:08
☝🏻 submitted the patch

**Comment by teto** [comment] 2021-03-26 12:51
so that was it ! hehe thanks

**Comment by ymatsiuk** [comment] 2021-04-09 11:20
Finally `bluez` 5.58 has been released and contains mentioned fix. Just got merged into `staging` #118746

**Comment by iosmanthus** [comment] 2021-04-14 09:49
#off-topic: After one week of tests, I still suffer from the disconnection but with a lower probability. 😆

**Comment by ymatsiuk** [comment] 2021-04-14 09:58
@iosmanthus disconnects are caused by combination of bugs:
- bluez (`5.56` + patch that is currently in `unstable`) --> `5.58` is on the way
- firmware (`2020-12-18` for `AX201` based Intel devices)

**Comment by iosmanthus** [comment] 2021-04-14 12:03
> @iosmanthus disconnects are caused by combination of bugs:
> 
>     * bluez (`5.56` + patch that is currently in `unstable`) --> `5.58` is on the way
> 
>     * firmware (`2020-12-18` for `AX201` based Intel devices)

Cool!

**Comment by ymatsiuk** [comment] 2021-04-16 17:50
@iosmanthus did you manage to test latest unstable with firmware I've mentioned? Can we close this issue?


the firmware override that works for me:
```nix
  hardware.firmware = with pkgs; [
    sof-firmware
    (firmwareLinuxNonfree.overrideAttrs (oldAttrs: rec {
      version = "2020-12-18";
      outputHash = "sha256-hgTfrOmKKpVK+qGuaFtFURLCwcG/cCiT4UYx7qCw+9w=";
    }))
  ];
```

**Comment by iosmanthus** [comment] 2021-04-16 17:51
> @iosmanthus did you manage to test latest unstable with firmware I've mentioned? Can we close this issue?
> 
> 
> the firmware override that works for me:
> ```nix
>   hardware.firmware = with pkgs; [
>     sof-firmware
>     (firmwareLinuxNonfree.overrideAttrs (oldAttrs: rec {
>       version = "2020-12-18";
>       outputHash = "sha256-hgTfrOmKKpVK+qGuaFtFURLCwcG/cCiT4UYx7qCw+9w=";
>     }))
>   ];
> ```

yes,it works! closing it. THX

**Closed** 2021-04-16 17:51 UTC
Labels: 0.kind: bug, 6.topic: hardware

**Comment by ymatsiuk** [comment] 2021-04-21 06:46
JFYI: this is the new *unreleased* version of firmware with the fix for disconnects

```nix
    (firmwareLinuxNonfree.overrideAttrs (oldAttrs: rec {
      outputHash = "sha256-97dh9N6KHmK1TfMU0EaNPfZ1Mx7zm/Y3lAfASUSxzXM=";
      src = pkgs.fetchgit {
        url = "https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git";
        rev = "73144e02dcff54529ab42d951de682740d204180";
        sha256 = "sha256-6VYtF7MbsCcPFmmOJCapQs9kHZNPRQ9HFZBhTaE2ecE=";
      };
    }))
```

**Comment by ymatsiuk** [comment] 2022-02-24 12:41
@marcelarie this has been fixed by upstream. If you experience the same issue again try to rollback the firmware and see if that helps. Otherwise please report a new issue and provide more details

**Comment by iosmanthus** [comment] 2022-02-25 06:41
> Is this fixed? I have random disconnects on my Bluetooth headset with the `unstable` branch.

It should be a new issue, I have rollbacked to an older firmware and it's a workaround.

**Comment by marcelarie** [comment] 2022-02-25 08:07
Thanks to both.
