### ISSUE TITLE
`home-manager` NixOS module's `sharedModules` stopped supplying `pkgs` argument

### ISSUE THREAD

**Issue by zseri** [NixOS/nixpkgs#140879] opened 2021-10-07 19:10 UTC
### Describe the bug
After running `nix flake update`, the system derivation stopped building, leading to an "module called without argument `pkgs`" error.

The update:
```
• Updated input 'home-manager':
    'github:nix-community/home-manager/b0651cc2173427857b172604f85da6afe69e1d41' (2021-09-23)
  → 'github:nix-community/home-manager/d9fe208f3ccd7047a29eb31fd0cd3191c4445323' (2021-10-06)
• Updated input 'nixpkgs':
    'github:nixos/nixpkgs/c92f96b079bc9710234cfd7054c605a9d2c2bd2c' (2021-09-25)
  → 'github:nixos/nixpkgs/a362961fafb1898e9938380d30f9f6383ac5c024' (2021-10-07)
```
before that update, it worked flawlessly.

The error:
```
error: anonymous function at /nix/store/v8x4bl6rb2p7jcxw50asprp00ip3hn9m-source/users/default.nix:1:1 called without required argument 'pkgs'

       at /nix/store/6vg1w4vpdb6vjxzx7fzyad6y6fx2l27x-source/lib/types.nix:199:25:

          198|                 file = def.file;
          199|                 value = def.value arg;
             |                         ^
          200|               }) defs);
```

### some code snippets

`users/default.nix`:
```nix
{ config, lib, pkgs, ... }: {
  options = {
    ytrizja = {
      tiling.enable = lib.mkEnableOption "Tiling Window Manager utilities";
      workdesk.enable = lib.mkEnableOption "work desk + GUI apps";
    };
  };

  config = lib.mkMerge [
    {
      programs.home-manager.enable = true;
      home.keyboard = null;
      xdg.configFile."nixpkgs/config.nix".source = ../utils/user-nixpkgs-config.nix;
      # nmd breaks the NixOS-from-non-NixOS install
      manual.manpages.enable = false;
    }
    (lib.mkIf config.ytrizja.tiling.enable {
      programs.rofi.enable = true;
      services.dunst.enable = true;
      home.packages = with pkgs; [
        i3lock
        xcompmgr
      ];
    })
    (lib.mkIf config.ytrizja.workdesk.enable {
      # needed at least for gedit
      dconf.enable = true;

      programs.direnv.enable = true;
      programs.direnv.nix-direnv = {
        enable = true;
        enableFlakes = true;
      };

      home.packages = with pkgs; [
        /* .... */
      ];
    })
  ];
}
```

`flake.nix`:
```nix
  let
  /* nixosModule for shared hm config */
        hm-base = {
          home-manager.useGlobalPkgs = true;
          home-manager.useUserPackages = true;
          home-manager.sharedModules = [(import ./users)];
        };
  in
  {
  /* ... */
  }
```

Trying to replace the section above from `flake.nix` with the following:
```nix
  let
  /* nixosModule for shared hm config */
        hm-base = { pkgs, ... }: {
          home-manager.useGlobalPkgs = true;
          home-manager.useUserPackages = true;
          home-manager.sharedModules = [({ config, lib, ... }: (import ./users { inherit config lib pkgs; }))];
        };
  in
  {
  /* ... */
  }
```
leads to infinite recursion, instead.

### Expected behavior
`home-manager.sharedModules = [(import ./users)];` should work, which means that it should supply `users/default.nix` at least with the `config`, `lib`, and `pkgs` arguments, as before.

### Additional context
system flake repository: https://github.com/zseri/nixos-configs
just rolling back `home-manager` didn't fix it, which leads to the conclusion that a change in `nixpkgs` is probably responsible.

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.62, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210909_25b6b74`
 - nixpkgs: `/etc/nix-flake-channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - home-manager
```

**Comment by Misterio77** [comment] 2021-10-11 01:41
I can reproduce the issue, and bisecting it led me to the exact same commit.

**Comment by babariviere** [comment] 2021-10-12 11:52
Made a PR here: https://github.com/nix-community/home-manager/pull/2396

I wasn't able to use `hmModule` since it causes infinite recursion (hmModule use sharedModules).

**Comment by babariviere** [comment] 2021-10-30 09:11
Can be closed since the push on home-manager as been merged.

**Closed by babariviere** 2021-10-30 09:11 UTC
Labels: 0.kind: bug, 6.topic: nixos
