### ISSUE TITLE
Latest AMI doesn't resize root partition to match volume size

### ISSUE THREAD

**Issue by mlieberman85** [NixOS/nixpkgs#34538] opened 2018-02-02 18:45 UTC
## Issue description
Latest 17.09 Ami -nixos-17.09.2681.59661f21be6-x86_64-hvm-ebs (ami-40bee63a) doesn't resize root partition to match volume size.

Unsure if related to https://github.com/NixOS/nixpkgs/issues/22211

### Steps to reproduce

Spin up an ec2 instance with EBS storage optimized, with a root volume of any size.

## Technical details
Output of fdisk and df:
```

Disk /dev/nvme0n1: 100 GiB, 107374182400 bytes, 209715200 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x373af4ea

Device         Boot Start     End Sectors Size Id Type
/dev/nvme0n1p1       2048 4194303 4192256   2G 83 Linux

Filesystem               1M-blocks  Used Available Use% Mounted on
devtmpfs                       385     0       385   0% /dev
tmpfs                         3847     0      3847   0% /dev/shm
tmpfs                         1924     4      1921   1% /run
tmpfs                         3847     1      3847   1% /run/wrappers
/dev/disk/by-label/nixos      1983   765      1100  42% /
tmpfs                         3847     0      3847   0% /sys/fs/cgroup
tmpfs                          770     0       770   0% /run/user/0
```

Volume is 100G and I would expect the root partition to be also 100G.

**Comment by mlieberman85** [comment] 2018-02-02 19:27
Here's the output of journalctl during startup around resizing the filesystem:

```
Feb 02 19:21:12 localhost kernel: random: lvm: uninitialized urandom read (4 bytes read)
Feb 02 19:21:12 localhost stage-1-init: FAILED: partition-number must be a number
Feb 02 19:21:12 localhost stage-1-init: checking /dev/disk/by-label/nixos...
Feb 02 19:21:12 localhost stage-1-init: fsck (busybox 1.27.2)
Feb 02 19:21:12 localhost stage-1-init: [fsck.ext4 (1) -- /mnt-root/] fsck.ext4 -a /dev/disk/by-label/nixos
Feb 02 19:21:12 localhost stage-1-init: nixos: clean, 55628/131072 files, 209994/524032 blocks
Feb 02 19:21:12 localhost stage-1-init: resizing /dev/disk/by-label/nixos...
Feb 02 19:21:12 localhost kernel: input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input0
Feb 02 19:21:12 localhost kernel: random: fast init done
Feb 02 19:21:12 localhost stage-1-init: nixos: 55628/131072 files (0.1% non-contiguous), 209994/524032 blocks
Feb 02 19:21:12 localhost stage-1-init: resize2fs 1.43.4 (31-Jan-2017)
Feb 02 19:21:12 localhost stage-1-init: The filesystem is already 524032 (4k) blocks long.  Nothing to do!
Feb 02 19:21:12 localhost stage-1-init: mounting /dev/disk/by-label/nixos on /...
Feb 02 19:21:12 localhost kernel: EXT4-fs (nvme0n1p1): mounted filesystem with ordered data mode. Opts: (null)
Feb 02 19:21:12 localhost stage-1-init: getting EC2 instance metadata...
Feb 02 19:21:12 localhost stage-1-init: wget: server returned error: HTTP/1.1 404 Not Found
Feb 02 19:21:12 localhost stage-1-init: skipping unknown device type /dev/xvd[abcde]*
Feb 02 19:21:12 localhost kernel: EXT4-fs (nvme0n1p1): re-mounted. Opts: (null)
Feb 02 19:21:12 localhost unknown: booting system configuration /nix/store/qgnvn1gz06c7m55l2nqjq04h8ady4wxs-nixos-system-unnamed-17.09.2681.59661f21be6
```

**Comment by copumpkin** [comment] 2018-02-02 19:30
```
Feb 02 19:21:12 localhost kernel: EXT4-fs (nvme0n1p1): mounted filesystem with ordered data mode. Opts: (null)
Feb 02 19:21:12 localhost stage-1-init: skipping unknown device type /dev/xvd[abcde]*
```

Perhaps to do with the new NVME devices not resizing properly?

**Comment by mlieberman85** [comment] 2018-02-02 19:38
I was able to confirm using an m4 instance works. Using an m5 appears to use nvme for ebs volumes which doesn't work.

**Comment by copumpkin** [comment] 2018-02-02 20:54
Ah yeah, this is the issue:

https://github.com/NixOS/nixpkgs/blob/eddf30cc93e1b778b6bc10d0eb1bb175385d034f/nixos/modules/virtualisation/amazon-image.nix#L92-L96

Probably just needs to expand the pattern, or use a more robust heuristic to talk about devices.

**Comment by edolstra** [comment] 2018-02-02 22:18
Closing as dupe of #33417.

**Closed by edolstra** 2018-02-02 22:18 UTC
