### ISSUE TITLE
bundler hash error on 15.09

### ISSUE THREAD

**Issue by mogorman** [NixOS/nixpkgs#12370] opened 2016-01-13 20:40 UTC
output path ‘/nix/store/v7kmrgydx4zdfnvbfby3rh7aj1gnps7f-bundler-a2343c9’ should have r:sha256 hash ‘1p7kzhmicfljy9n7nq3qh6lvrsckiq76ddypf6s55gfh1l98z4k9’, instead has ‘07ay4prgqshy85gwvgvfy5xxgyqd87b3m0hkjm5a3a2zm7kyxls9’
cannot build derivation ‘/nix/store/fnqaz0776sxfycjnmr4nyn8h1yh84zhg-ruby_2.1.3_p0-bundler-2015-01-11.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/r196z5lja8904ns0c7y9xp1sc123adlj-gitlab.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/ba1dhxhd8vzxdgnbhlpqwa665vz5jdwr-gitlab-runner.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/pq3w0qg3il11x8aalp7982nn3rqfsidm-unit-gitlab-sidekiq.service.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/9qb4b0xpnxv2isy6zfq3slzv77w9cdd7-unit-gitlab.service.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/pc55i0g1p962jnrz4vbzix9inav461h3-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/y36hc8q3ymfbs0jnxcaqcz2xhhasgyy9-system-units.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/xa3ydvjh3gp2xaaavj96kxmk7w6az6rz-nixos-15.09.911.53286a8.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/6aqb36ygrczanfi9yc0ldqypvsbx27sa-etc-file.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/cixrkarb36j19bv9xavs33ncb2i79xa7-etc.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/cghampnz2amnnajarhwnyiplgynm7kg2-nixos-15.09.911.53286a8.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/cghampnz2amnnajarhwnyiplgynm7kg2-nixos-15.09.911.53286a8.drv’ failed

**Comment by copumpkin** [comment] 2016-01-13 20:44
Looks like it's using `fetchgit` with `leaveDotGit = true`, which is known (https://github.com/NixOS/nixpkgs/issues/8567) to be unreliable: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/ruby/bundler-head.nix#L5-L10

This might also be a dupe of #9005.

**Comment by copumpkin** [comment] 2016-01-13 20:46
I think the right solution, @cstrahan/@pikajude, is to stop using `leaveDotGit` and patch out the parts that look for the git metadata.

**Comment by mogorman** [comment] 2016-01-13 20:57
yup its definetly that.  although oddly. i have no problem install bundler_HEAD by hand, only when its called by my gitlab derivation does this happen

**Comment by fpletz** [comment] 2016-03-17 05:34
This should be fixed by #12787. Please reopen if you still have problems.

**Closed by fpletz** 2016-03-17 05:34 UTC
