### ISSUE TITLE
Host lookup fails when using wins nss plugin.

### ISSUE THREAD

**Issue by xastor** [NixOS/nixpkgs#43607] opened 2018-07-16 10:20 UTC
## Issue description
I'm having an issue looking up a host using getent on the wins service.

### Steps to reproduce
I installed samba using this configuration section : 

```
    services.samba = {
      enable = true;
      nsswins = true;
      enableNmbd = true; 
    };
```

Lookup using nmblookup works fine (part of the samba package). Below I'm looking up host "Sirius" : 

```
[pieter@officepib-nixos:/nix/store]$ nmblookup Sirius
192.168.1.147 Sirius<00>
10.0.75.1 Sirius<00>
```

Wins is correctly configured :

```
[pieter@officepib-nixos:/nix/store]$ cat /etc/nsswitch.conf 
passwd:    files mymachines systemd
group:     files mymachines systemd
shadow:    files

hosts:     files mymachines wins dns myhostname
networks:  files

ethers:    files
services:  files
protocols: files
rpc:       files
```

Looking up using getent returns nothing : 

```
[pieter@officepib-nixos:/nix/store]$ getent -s wins hosts Sirius
```

Ping returns a system error : 

```
[pieter@officepib-nixos:/nix/store]$ ping Sirius
ping: Sirius: System error
```

I'm not an expert, but when I run strace, I see that getent does not search for libnss_wins.so.2 in the correct location (the samba package).  I'm not sure if I'm on to something here? 

```
[pieter@officepib-nixos:/nix/store]$ strace getent -s wins hosts Sirius
execve("/run/current-system/sw/bin/getent", ["getent", "-s", "wins", "hosts", "Sirius"], 0x7fff099a2970 /* 69 vars */) = 0
brk(NULL)                               = 0x886000
access("/etc/ld-nix.so.preload", R_OK)  = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/run/opengl-driver/lib/tls/x86_64/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/run/opengl-driver/lib/tls/x86_64/x86_64", 0x7ffdcfcb93c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/run/opengl-driver/lib/tls/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/run/opengl-driver/lib/tls/x86_64", 0x7ffdcfcb93c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/run/opengl-driver/lib/tls/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/run/opengl-driver/lib/tls/x86_64", 0x7ffdcfcb93c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/run/opengl-driver/lib/tls/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/run/opengl-driver/lib/tls", {st_mode=S_IFDIR|0555, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/run/opengl-driver/lib/x86_64/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/run/opengl-driver/lib/x86_64/x86_64", 0x7ffdcfcb93c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/run/opengl-driver/lib/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/run/opengl-driver/lib/x86_64", 0x7ffdcfcb93c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/run/opengl-driver/lib/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/run/opengl-driver/lib/x86_64", 0x7ffdcfcb93c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/run/opengl-driver/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/run/opengl-driver/lib", {st_mode=S_IFDIR|0555, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/run/opengl-driver-32/lib/tls/x86_64/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/run/opengl-driver-32/lib/tls/x86_64/x86_64", 0x7ffdcfcb93c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/run/opengl-driver-32/lib/tls/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/run/opengl-driver-32/lib/tls/x86_64", 0x7ffdcfcb93c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/run/opengl-driver-32/lib/tls/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/run/opengl-driver-32/lib/tls/x86_64", 0x7ffdcfcb93c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/run/opengl-driver-32/lib/tls/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/run/opengl-driver-32/lib/tls", {st_mode=S_IFDIR|0555, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/run/opengl-driver-32/lib/x86_64/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/run/opengl-driver-32/lib/x86_64/x86_64", 0x7ffdcfcb93c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/run/opengl-driver-32/lib/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/run/opengl-driver-32/lib/x86_64", 0x7ffdcfcb93c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/run/opengl-driver-32/lib/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/run/opengl-driver-32/lib/x86_64", 0x7ffdcfcb93c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/run/opengl-driver-32/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/run/opengl-driver-32/lib", {st_mode=S_IFDIR|0555, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/tls/x86_64/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/tls/x86_64/x86_64", 0x7ffdcfcb93c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/tls/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/tls/x86_64", 0x7ffdcfcb93c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/tls/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/tls/x86_64", 0x7ffdcfcb93c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/tls/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/tls", 0x7ffdcfcb93c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/x86_64/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/x86_64/x86_64", 0x7ffdcfcb93c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/x86_64", 0x7ffdcfcb93c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/x86_64", 0x7ffdcfcb93c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260\34\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0555, st_size=2011232, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f3ca5677000
mmap(NULL, 3881376, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f3ca50a1000
mprotect(0x7f3ca524b000, 2097152, PROT_NONE) = 0
mmap(0x7f3ca544b000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1aa000) = 0x7f3ca544b000
mmap(0x7f3ca5451000, 14752, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f3ca5451000
close(3)                                = 0
arch_prctl(ARCH_SET_FS, 0x7f3ca5678540) = 0
mprotect(0x7f3ca544b000, 16384, PROT_READ) = 0
mprotect(0x605000, 4096, PROT_READ)     = 0
mprotect(0x7f3ca5679000, 4096, PROT_READ) = 0
brk(NULL)                               = 0x886000
brk(0x8a7000)                           = 0x8a7000
openat(AT_FDCWD, "/run/current-system/sw/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0444, st_size=126969360, ...}) = 0
mmap(NULL, 126969360, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f3c9d78a000
close(3)                                = 0
stat("/etc/resolv.conf", {st_mode=S_IFREG|0644, st_size=96, ...}) = 0
openat(AT_FDCWD, "/etc/host.conf", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0444, st_size=8, ...}) = 0
read(3, "multi on", 4096)               = 8
read(3, "", 4096)                       = 0
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/resolv.conf", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=96, ...}) = 0
read(3, "# Generated by resolvconf\nnamese"..., 4096) = 96
read(3, "", 4096)                       = 0
close(3)                                = 0
uname({sysname="Linux", nodename="officepib-nixos", ...}) = 0
openat(AT_FDCWD, "/run/opengl-driver/lib/tls/libnss_wins.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/run/opengl-driver/lib/libnss_wins.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/run/opengl-driver-32/lib/tls/libnss_wins.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/run/opengl-driver-32/lib/libnss_wins.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/libnss_wins.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/etc/resolv.conf", {st_mode=S_IFREG|0644, st_size=96, ...}) = 0
exit_group(2)                           = ?
+++ exited with 2 +++
```

## Technical details

```[pieter@officepib-nixos:/nix/store]$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.06 MiB download, 0.31 MiB unpacked):
  /nix/store/bcrwa5b8z54xrl95ipfrq6nqhb0530yi-stdenv-linux
  /nix/store/svqz53x33gsjh41h357azm8fk755ynma-bash-interactive-4.4-p23-dev
copying path '/nix/store/svqz53x33gsjh41h357azm8fk755ynma-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/bcrwa5b8z54xrl95ipfrq6nqhb0530yi-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.54, NixOS, 18.09pre145679.dae9cf6106d (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(pieter): `"nixos-unstable-18.09pre138687.1b1be29bf82"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by flokli** [comment] 2019-06-14 12:27
@xastor normally, glibc should pipe all nss lookups to nscd, which gets configured to use the nss modules configured in `system.nssModules`. Is `nscd` running on your system?

**Comment by dasJ** [comment] 2020-04-09 21:15
@flokli I have the same issue. The problem (as you can see from the strace) is that glibc doesn't even try to access the nscd socket.

**Comment by dasJ** [comment] 2020-04-09 21:20
Workaround (but ugly):
```nix
environment.etc."ld-nix.so.preload".text = ''
  ${pkgs.samba4Full}/lib/libnss_winbind.so.2
'';
```

cc @arianvp @Mic92 @FRidh

**Comment by flokli** [comment] 2020-04-09 21:22
Can you provide a quick reproducer / vm test so I can debug this locally for testing?

**Comment by ajs124** [comment] 2020-04-09 21:36
An empty test vm should be enough. As in
```
# go to a nixpkgs checkout, in my case at 939fcdcbddf5713552a9a4ed61389f13f4a88188
unset NIX_PATH  # this part is important
nix-build nixos --arg configuration '{ users.users.root.password = "asdf"; }' -A vm
./result/bin/run-nixos-vm
```
Log in as `root` with password `asdf`. Observe `nscd.service` is running, e.g. with `systemctl`.
Run `getent passwd`. Observe no `Dynamic User`. There really should be one, as `nscd` itself is running as one. Run something like `strace -f -s 5000 getent passwd`. See that no attempt to open a connection to nscd is made and getent tries and fails to load `libnss_systemd.so.2`.

**Comment by dasJ** [comment] 2020-04-09 21:39
That probably also explains why UIDs/GIDs of files owned by dynamic users are not resolvable:
```
# ls -la
total 0
drwx------  3 root  root   19 Mar 22 06:11 .
drwxr-xr-x 16 root  root  223 Mar 30 14:58 ..
drwxr-xr-x  2 64237 64237  47 Apr  9 19:04 dhcpd
```
(I use a modified dhcpd with `DynamicUser`)

**Comment by flokli** [comment] 2020-04-11 08:38
Dynamic user lookup seems to work here:

```
systemd-run --pty --property=Type=oneshot --property=DynamicUser=yes id                                                        
Running as unit: run-u6172.service
Press ^] three times within 1s to disconnect TTY.
uid=64124(run-u6172) gid=64124(run-u6172) groups=64124(run-u6172)
```

I can also look up the user with `getent passwd $uid` while the command is running - as an example, take a look at the owner of `/proc/$(pidof nscd)` - it's nscd, even though `getent passwd` doesn't show that user. That's probably expected and fine - thinking of non-local users, you probably can't get a listing of all users via that as well.

So I think it's safe to say custom NSS modules should work (as `nss-systemd` is such a module) - so I'd need a reproducer of the winbind issue to investigate hee.

**Comment by dasJ** [comment] 2020-04-11 15:02
Umm, that's weird. On my unstable machine, the same does not work:
```
systemd-run --pty --property=Type=oneshot --property=DynamicUser=yes id
[sudo] password for janne:
Running as unit: run-u54.service
Press ^] three times within 1s to disconnect TTY.
uid=62338 gid=62338 groups=62338
```

Neither does it work on my 19.09 machine.

**Comment by ajs124** [comment] 2020-04-11 16:40
> That's probably expected and fine - thinking of non-local users, you probably can't get a listing of all users via that as well.

Nope. If `getent` finds the required library, it can list the users. Try this: 
```
LD_LIBRARY_PATH=$(nix-build --no-out-link '<nixpkgs>' -A systemd)/lib getent passwd
# note that the empty test vm is missing any channels, you you either need to find that path some other way or run nix-channel --update
```

Which sort of isn't the point anyways. `getent` and therefore the relevant glibc calls, like `getaddrinfo` seem to not try to contact nscd, at all. Just run strace. It never attempts to open a socket connection to nscd.

![LD_LIBRARY_PATH set](https://user-images.githubusercontent.com/1229027/79049373-34cc8000-7c1b-11ea-9110-426049fb72d3.png)
vs.
![LD_LIBRARY_PATH not set](https://user-images.githubusercontent.com/1229027/79049389-4f9ef480-7c1b-11ea-9d99-e3834ead0c11.png)

The same example works for `samba/lib` in the `LD_LIBRARY_PATH` or `LD_PRELOAD`. You can absolutely list users, host and so on that way.

**Comment by flokli** [comment] 2020-04-25 09:43
We can't really populate nss modules to a mutable store path, and add this to `LD_LIBRARY_PATH`. This would bite us every time we try run a binary linked against another glibc version (similar to how we have this problem with OpenGL drivers), as explained in https://github.com/NixOS/nixpkgs/issues/55276.

https://github.com/NixOS/nixpkgs/issues/55276#issuecomment-460722492 says `nscd` is the way to provide these in a ABI-neutral way, and on NixOS, we do that by enabling nscd, setting `LD_LIBRARY_PATH` for `nscd.service`, and rely on "common userland" to go via nscd.

Having the uid lookup via `ps -fp $(pgrep nscd)` still makes me think it should work for "common userland". Could it be `getent` is somewhat special here, not using `nscd` on purpose (as it's a glibc low-level util)?

On the other hand, the initial report says "ping" for `wins` is broken, so /that/ would be an example of a broken "common userland" application. @xastor, if you could get me an `strace` output of the ping command, and a `systemctl cat nscd.service` to see how `LD_LIBRARY_PATH` looks there (and what's in these folders), I could guess.

If I'd get a reproducer VM config, I could even debug it by myself ;-)

**Comment by dasJ** [comment] 2020-04-25 10:52
So to give you some background: @ajs124 and I disable nscd by default because we don't think we need it on all systems.
I enabled the service on the Samba DC so winbindd works. Today, I rebooted the server and suddenly, it works. Is it possible that for some reason toggling nscd requires a reboot (ie a restart of all processes)?

**Comment by flokli** [comment] 2020-04-25 11:52
Processes might cache the fact that nscd is not available, I'm not sure.

I'd strongly recommend having nscd enabled, as even in a minimal configuration, you'll miss the systemd-provided nss modules.

**Comment by ajs124** [comment] 2020-04-25 12:31
Ok, so doing some more testing, it seems like `getent`, for some reason, behaves differently from other things, like `ls`. Which is just great…

**Comment by flokli** [comment] 2020-04-25 16:15
Related PRs:
 - https://github.com/NixOS/nixpkgs/pull/85998
 - https://github.com/NixOS/nixpkgs/pull/86010

**Comment by flokli** [comment] 2020-04-25 16:16
So when enabling nscd (and maybe rebooting/starting various services), wins nss lookups work?

**Comment by dasJ** [comment] 2020-04-25 22:30
I can confirm that the systemd module works in htop and ps.

I can also confirm the winbind module (also Samba) with `getent passwd $REALM\\Administrator`

I'm not using wins, but I guess it'll also work.

**Comment by dasJ** [comment] 2020-04-25 22:31
If you need any more information that doesn't need to go into this issue, feel free to contact me via Matrix at `@janne.hess:helsinki-systems.de` or via IRC as das_j ;)

**Comment by flokli** [comment] 2020-04-27 12:33
okay, let's close this issue, as it seems to be fixed. Thanks @ajs124 and @dasJ for debugging!

**Closed by flokli** 2020-04-27 12:33 UTC
