### ISSUE TITLE
Specifying multiple pythons results in collision

### ISSUE THREAD

**Issue by dinko-pehar** [NixOS/nixpkgs#194090] opened 2022-10-02 15:34 UTC
I'm using home-manager to manage packages and I've stumbled upon Python collisions.
I'm trying to install multiple python versions (`python3.8`, `python3.9`, `python3.10`...) but they all have collision on below line:

https://github.com/NixOS/nixpkgs/blob/9cac45850280978a21a3eb67b15a18f34cbffa2d/pkgs/development/interpreters/python/cpython/default.nix#L402

I understand all these pythons try to make them as default one (_python3_), but is there a way to have multiple Python versions enabled, but as default, let's say `python3.10` ?

Thank you

**Comment by LunNova** [comment] 2022-10-03 03:36
The conventional solution is to have a `shell.nix` or `flake.nix` with a dev shell for any project you're working on, which should specify the desired python interpreter and packages.

Installing multiple pythons on your system or user path doesn't fit the nix model very well.

If you just want them available to use interactively to test things you could make a wrapper package which only has `$out/bin/python3.x` as a link to the particular python version you want, which would avoid collisions.

**Comment by dinko-pehar** [comment] 2022-10-03 07:44
@LunNova 

I understand that solution, I will work with that in future.
What I hoped for, as in `Brew` package manager:

- `python@3.8` -> `Python38` _(nix variant)_
- `python@3.9` -> `Python39` _(nix variant)_
- `python@3.10` -> `Python310` _(nix variant)_

is that Brew supports installed all of these Python's together, but only Python 3.10 is marked as Python3. Which results in `python3` pointing to `python3.10`, but `python3.9` is available. I don't see a reason to try to link every python to `python3` ?

**Comment by FRidh** [comment] 2022-10-03 12:26
Behind the scenes home-manager probably uses `buildEnv` to which you can pass the option to ignore collisions. I don't recommend it but it might be an acceptable work-around for you.

The reason is that we cannot depending on the environment we install to choose which symlinks we create. So either we say "let's link python3 to the latest python in Nixpkgs" or "let's not link at all" or "let's link all of them". The former is very arbitrary, and can result in unexpected behaviour. The second is problematic, because tools unfortunately search by `python`, so the latter was chosen.

I'm going to close this because there is nothing at the Nixpkgs side that can be done here.

**Closed by FRidh** 2022-10-03 12:26 UTC
