### ISSUE TITLE
Package request: SVP

### ISSUE THREAD

**Issue by ninjarai4** [NixOS/nixpkgs#44333] opened 2018-08-02 03:22 UTC
SVP is an application that performs motion interpolation on videos so that you can watch them at a higher framerate.
https://www.svp-team.com/wiki/Main_Page
https://www.svp-team.com/wiki/SVP:Linux

If we are going to add this package there are some caveats. The file served from https://www.svp-team.com/wiki/Download changes every time there is an update and old versions are not hosted anywhere on the site (except for a few very old versions).
The maintainer for the AUR package solves this by hosting old versions on github. We might want to point to that download instead of the one hosted on SVP's site.
https://aur.archlinux.org/packages/svp/

**Comment by OpenSourceAnarchist** [comment] 2019-04-14 23:46
This is the package I really want to see made available in NixOS. It's a large part of my desktop usage and I don't think it will work out of the box on NixOS. I will test when I get a working installation, but I'd love to see this get included in the main channels!

**Comment by VolodiaPG** [comment] 2022-09-10 15:09
Duplicate of https://github.com/NixOS/nixpkgs/issues/64344 ?

Also, there is a NUR package providing SVP, c.f. the issue.

**Closed** 2024-05-06 03:22 UTC
Labels: 9.needs: package (new)
