### ISSUE TITLE
Package request: kinto

### ISSUE THREAD

**Issue by carleeto** [NixOS/nixpkgs#268808] opened 2023-11-20 20:59 UTC
**Project description**

Mac-style shortcut keys for Linux

[Setup video](https://www.youtube.com/watch?v=kd4al45XD1g)

**Metadata**

* homepage URL: https://github.com/rbreaves/kinto
* source URL: https://github.com/rbreaves/kinto
* license: gpl2
* platforms: unix, linux, darwin

**Comment by eclairevoyant** [comment] 2023-11-25 20:18
dupe of #137698

**Closed by eclairevoyant** 2023-11-25 20:18 UTC
Labels: 0.kind: packaging request
