### ISSUE TITLE
KDE cannot read Android device using MTP protocol

### ISSUE THREAD

**Issue by oxalica** [NixOS/nixpkgs#79803] opened 2020-02-11 07:37 UTC
**Describe the bug**
I'm on nixos unstable with KDE.

When I plugged my android device and switch usb mode to MTP File Transfer, it can be detected in "Device Notifier". (Screenshot 1) But when clicked, it fails with `Unknow protocol 'mtp'` and do nothing. (Screenshot 2)

I found #71509 and add `services.udev.packages = [ pkgs.android-udev-rules ];` but it doesn't work. The issue is closed by #73926 which fixed "viewing Android phones on Dolphin". Seems break again?

More info: I used to transfer files to the android phone using MTP on the same system without problem, but I don't know when does it break.

**To Reproduce**
1. Run nixos with KDE installed.
2. Plug an android device and set it to MTP mode.
3. Click the device in "Device Notifier" prompted.

**Expected behavior**
Open an dolphin explorer and show files in android devices using MTP.

**Screenshots**
![image](https://user-images.githubusercontent.com/14816024/74217111-8de26b00-4ce1-11ea-9c2e-91debb143c71.png)
![errmsg](https://user-images.githubusercontent.com/14816024/74217184-b9fdec00-4ce1-11ea-8e45-9b9e399e812e.png)

**Additional context**
nixos-unstable 8130f3c1c2bb0e533b5e150c39911d6e61dcecc2

**Metadata**
- system: `"x86_64-linux"`
- host os: `Linux 5.4.17, NixOS, 20.03pre212208.8130f3c1c2b (Markhor)`
- multi-user?: `no`
- sandbox: `yes`
- version: `nix-env (Nix) 2.3.2`
- channels(root): `"nixos-20.03pre212208.8130f3c1c2b, oxa-config"`
- channels(oxa): `"home-manager, nixpkgs-mozilla, rust-analyzer-overlay"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

cc @ttuegel @mmahut

**Comment by ttuegel** [comment] 2020-02-11 14:53
This is a duplicate of #79707.

**Closed by ttuegel** 2020-02-11 14:53 UTC
Labels: 0.kind: bug, 6.topic: qt/kde
