### ISSUE TITLE
$ guake: [ERROR] Unable to start Guake, missing mandatory dependency: Vte

### ISSUE THREAD

**Issue by dubiouscript** [NixOS/nixpkgs#57494] opened 2019-03-12 07:44 UTC
## Issue description

non nixos nixpkgs guake 

as in the title : Unable to start Guake, missing mandatory dependency: Vte

### Steps to reproduce
```
$ nix-env -iA nixpkgs.guake 
installing 'guake-3.4.0'
these paths will be fetched (50.98 MiB download, 236.29 MiB unpacked):
......
$ guake 
[ERROR] Unable to start Guake, missing mandatory dependency: Vte >= 0.42

$ nix-env -iA nixpkgs.vte
installing 'vte-0.54.3' 
these paths will be fetched (9.98 MiB download, 37.79 MiB unpacked):

$ guake 
[ERROR] Unable to start Guake, missing mandatory dependency: Vte >= 0.42
```
WTF ??
https://github.com/NixOS/nixpkgs/issues?utf8=%E2%9C%93&q=is%3Aissue+guake

**Comment by hedning** [comment] 2019-03-12 09:55
See #56943 for the cause. Putting `gobject-introspection` in `buildInput` should fix it for now.

**Comment by dubiouscript** [comment] 2019-03-12 11:56
0.o
thanks! for the info !!

**Comment by jtojnar** [comment] 2019-03-12 14:00
Yeah, this is duplicate of #56943.

**Closed by jtojnar** 2019-03-12 14:00 UTC
Labels: 6.topic: gnome3, 6.topic: python

**Comment by dubiouscript** [comment] 2019-03-13 09:40
any idea 
- how to apply this so guake works ?
or tips on 
- how to find an old working version ??

**Comment by jtojnar** [comment] 2019-03-13 11:00
Add `strictDeps = false;` to the package with a comment linking to #56943
