### ISSUE TITLE
steam: cannot download libvulkan1.deb from any mirror

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#49485] opened 2018-10-30 20:10 UTC
## Issue description

some steam sources are unavailable again.

```
...
building '/nix/store/cpk56d6l6qyqqf5vqhb8c5zlr64vbh5v-libvpx1.deb.drv'...
building '/nix/store/kk8p9c0r73lsdyjc2nkqrlicar3q3w3l-libvpx1.deb.drv'...
building '/nix/store/i27jrai6yizpc5zp5wvrl7fc1yilcxyf-libvulkan1.deb.drv'...
building '/nix/store/ia8g6grzgmajmi0jrlz3b7b4n097klvx-libvulkan1.deb.drv'...
building '/nix/store/1sd5wg0xv8q4qa7yaq6mm7p5d8xrgkrx-libwind0-heimdal.deb.drv'...
building '/nix/store/xldsxpp6c7w5f1ncmwmbv13v22vw14ld-libwind0-heimdal.deb.drv'...
building '/nix/store/522drkrann203gww0samd6fxxfipg2wn-libwrap0.deb.drv'...
building '/nix/store/69d1sminpc4hb7zjmrmxz1jvirg5vsac-libwrap0.deb.drv'...

trying http://repo.steampowered.com/steamrt/pool/main/libv/libvpx/libvpx1_1.0.0-1+srt4_i386.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

trying http://repo.steampowered.com/steamrt/pool/main/libv/libvpx/libvpx1_1.0.0-1+srt4_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

trying http://repo.steampowered.com/steamrt/pool/main/v/vulkan-loader/libvulkan1_1.0.3~git20160215-0.1+steamos5+srt1_amd64.deb

trying http://repo.steampowered.com/steamrt/pool/main/v/vulkan-loader/libvulkan1_1.0.3~git20160215-0.1+steamos5+srt1_i386.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

trying http://repo.steampowered.com/steamrt/pool/main/h/heimdal/libwind0-heimdal_1.6~git20120311.dfsg.1-2+srt4_i386.deb

trying http://repo.steampowered.com/steamrt/pool/main/h/heimdal/libwind0-heimdal_1.6~git20120311.dfsg.1-2+srt4_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

trying http://repo.steampowered.com/steamrt/pool/main/t/tcp-wrappers/libwrap0_7.6.q-21+srt4_i386.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

trying https://abbradar.net/steamrt/pool/main/v/vulkan-loader/libvulkan1_1.0.3~git20160215-0.1+steamos5+srt1_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

trying https://abbradar.net/steamrt/pool/main/h/heimdal/libwind0-heimdal_1.6~git20120311.dfsg.1-2+srt4_i386.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

trying https://abbradar.net/steamrt/pool/main/libv/libvpx/libvpx1_1.0.0-1+srt4_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

trying https://abbradar.net/steamrt/pool/main/libv/libvpx/libvpx1_1.0.0-1+srt4_i386.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

trying https://abbradar.net/steamrt/pool/main/t/tcp-wrappers/libwrap0_7.6.q-21+srt4_i386.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

trying https://abbradar.net/steamrt/pool/main/v/vulkan-loader/libvulkan1_1.0.3~git20160215-0.1+steamos5+srt1_i386.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

trying https://abbradar.net/steamrt/pool/main/h/heimdal/libwind0-heimdal_1.6~git20120311.dfsg.1-2+srt4_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download libvulkan1.deb from any mirror
builder for '/nix/store/i27jrai6yizpc5zp5wvrl7fc1yilcxyf-libvulkan1.deb.drv' failed with exit code 1
building '/nix/store/bqwd6dqz1by3w4ws4zkmby4cjpfxj8kd-libx11-6.deb.drv'...
building '/nix/store/yxdkq7kss2m3zf38h2lk7g1blxv2bvia-libx11-data.deb.drv'...
building '/nix/store/8qw01bqf7g81702x418yhckf7szdcr4m-libx11-xcb1.deb.drv'...
building '/nix/store/l8am6mc6bkmsw0561zd6g2kqn7pgm1jr-libxau6.deb.drv'...
cannot build derivation '/nix/store/9mlzzq3987l20x3zmjg04pwa61cw2m4a-steam-runtime.json.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/qbv8n217r8rz5z5k7s4qi6yf9lw63kzc-steam-runtime-2016-08-13.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/37bbn4c85rgbhw93sbwzrwaxbk8xyw70-steam-runtime-wrapped.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/l83jkpz16izg67pw0za5gh2kp92ks45s-steam-run-usr-target.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/f7sjy35acqy02ylyph1gbw947ayc587c-steam-usr-target.drv': 1 dependencies couldn't be built
building '/nix/store/626mysgbl1jznxm167jlbl0yh67rwfcn-login.pam.drv'...
building '/nix/store/mfhwhmb1imrmrcn0yixx9bmyaj2lly37-mesa-drivers+txc-18.1.7.drv'...
building '/nix/store/171m09b0dqsiml6z9cv359v41ilg9kgd-nixos-hires.png.drv'...
building '/nix/store/9rgi1851cy9v4flsr0n3vwc309smv72i-passwd.pam.drv'...
building '/nix/store/wfk178hxypx8alyq00a886zvdv4nzhv3-plymouth-themes.drv'...
building '/nix/store/8ijfm4fjkv3yv70wss0kfvrdkn7mk3fl-polkit-1.pam.drv'...
building '/nix/store/ba3354nah8ij8kwk7inraxl49m53rhi5-qemu.conf.drv'...
building '/nix/store/dabbmb8agykh4sfz5gi638ngiydncly8-runuser-l.pam.drv'...
cannot build derivation '/nix/store/3klmqlrh2c2b2xcymzj7bgikb0iylvw8-steam-fhs.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/1xfc2ndw7yrm38wkmsvpajvdnyrbziw5-steam-run-fhs.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/irn082sib2b1x7lfsm6sc2ym33vb0nmz-steam-init.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/14s9vdg6vlsiiz4yf7c4z8axvq99j3dy-steam-run-init.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ljmilark38ldrbrx2kkna111k7aa1w9k-steam-run.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/b7s0afcapczqdj0q0cm1jzzcj8jm3mzs-steam.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ly4n9xldvixcv0j1vlr1b03785vrbyzk-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/k5zbai35fn9d9f16d1ki5nwxc1xb8pmd-nixos-system-imac-18.09.1023.06fb0253afa.drv': 1 dependencies couldn't be built
error: build of '/nix/store/k5zbai35fn9d9f16d1ki5nwxc1xb8pmd-nixos-system-imac-18.09.1023.06fb0253afa.drv' failed
```

cc @abbradar @hrdinka

### Steps to reproduce

rebuild with steam installed

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.09.932.09195057114 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09.1023.06fb0253afa, nixos-hardware, nixos-unstable-19.03pre155751.45a419ab5a2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by dywedir** [comment] 2018-10-30 20:15
See https://github.com/NixOS/nixpkgs/issues/49048

**Comment by FRidh** [comment] 2018-10-30 20:20
Duplicate of https://github.com/NixOS/nixpkgs/issues/49048

**Closed by FRidh** 2018-10-30 20:20 UTC
