### ISSUE TITLE
Unstable channel is severely outdated

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#27502] opened 2017-07-19 17:46 UTC
## Issue description

https://nixos.org/channels/nixos-unstable still redirects to a hydra build from july 4th.

### Steps to reproduce

Visit in your browser/use https://nixos.org/channels/nixos-unstable channel. Observe it being fairly outdated.

## Technical details

* System: 17.09pre110213.01c3847b9c
* Nix version: nix-env (Nix) 1.11.11

**Comment by volth** [comment] 2017-07-21 15:32
On github they stopped about 11-12 July
https://github.com/NixOS/nixpkgs-channels/commits/nixos-unstable
https://github.com/NixOS/nixpkgs-channels/commits/nixos-unstable-small

**Comment by edolstra** [comment] 2017-07-21 16:49
See here for the broken builds that are blocking a channel update:
* http://hydra.nixos.org/job/nixos/unstable-small/tested#tabs-constituents
* http://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents

**Comment by jeremejevs** [comment] 2017-07-23 14:35
Has this issue (unstable channel getting "stuck" regularly) been discussed in the past? I'm curious whether this is considered to be working as intended or not, and why, and what are the recommendations/plans, if any. I understand why any failed test fails the whole build, but it would be nice if there were processes/incentives in place, to ensure that the build doesn't remain stuck for several days in a row, not to mention weeks.

**Comment by joachifm** [comment] 2017-07-23 20:19
@jeremejevs it's a recurring thing. I can't speak to the original intent of the unstable channel, but I think history strongly recommends *not* following it (except to develop against it).

**Comment by Infinisil** [comment] 2017-07-23 21:11
@grahamc @cleverca22 and me have looked into this a bit today. There is a recurring scenario of the test failing early (before the actual tests even start) with the message "error: timed out waiting for the VM to connect". @cleverca22 was able to reproduce this error very rarely and was able to [narrow it down](https://gist.github.com/cleverca22/25b44f4f4c76aefe8a5e32fb60eaa226) to [this command](https://github.com/NixOS/nixpkgs/blob/26cf940da87e5f1059d90e7bcd63c22f819421b3/nixos/modules/virtualisation/qemu-vm.nix#L399) not terminating. @grahamc restarted the failing jobs and sure enough, almost all of them passed this time. Where previously about 10 failed with this error, now only 3 do. Restarting those would probably get them to pass too.

Unrelated, the keymap tests were occasionally failing, resulting in a "`1 out of 2 tests succeeded`" log. I tested this repeatedly locally and am now estimating the chance of it happening to be about 1 in 12, probably increasing with the machines current load. Restarting the keymap tests made all of them pass.

And lastly, we didn't look into this, the tests for ssdm and plasma5 are failing for some other reason.

**Comment by jeremejevs** [comment] 2017-07-23 21:33
@joachifm The channel is *unstable* after all, so it's understandable for it to be unstable, but I have a feeling that there's a non-negligible amount of people using NixOS as a rolling release distro, like myself, and it would be nice if there was a channel we could rely on (unstable fulfills that role well enough, except for the occasional testing accidents).

Semi-off-topic: Theoretically, I could be content with a stable channel, but in practice it just meant twice the amount of troubleshooting and maintenance (been on 16.09 for 1-2 months, when I was starting out with Nix, and I kept stumbling into things which were broken/missing on stable, and fixed on unstable, and my `configuration.nix` was borrowing so much from the master, that I just eventually gave up).

**Comment by joachifm** [comment] 2017-07-23 21:53
@jeremejevs but nixos *is* a release oriented distro. There's nothing *preventing* someone from committing to consistently staying ontop of unstable test failures, but that just isn't happening ... Realistically, users wishing to make rolling-release more viable must be prepared to put in non-trivial amount of work. Until then please consider using the -small channel or release.

**Comment by NeQuissimus** [comment] 2017-07-23 22:03
I have found using stable for the OS and unstable-small for the user environment to be a good combo :)

**Comment by jeremejevs** [comment] 2017-07-23 22:21
@joachifm Okay, thanks, that's what I wanted to know. I guess NixOS might never have an Arch-like channel, without the whole project switching to rolling-release-first, since unstable is good enough as it is (the delay never results in something breaking, it's just an inconvenience).

@NeQuissimus That might be a viable compromise, but `unstable-small` is 12 days behind right now too.

**Comment by rnhmjoj** [comment] 2017-07-24 01:59
@jeremejevs When the channel is "stuck" I keep the system updated like this: on my local copy of nixpkgs I have a `current` branch pointing to the latest successful build. I cherry-pick the commits I want that haven't reached the channel yet: usually fixes, security patches, new packages... then I build the system with `nixos-rebuild switch -I nixpkgs=$HOME/src/nixpkgs`.

**Comment by NeQuissimus** [comment] 2017-07-24 02:30
I sometimes do what @rnhmjoj described if I want a certain set of updates badly.
Or, if I don't want an update coming from the channel, I have also had copies of "old" derivations linked into my `configuration.nix` or my user `config.nix`. That's also pretty simple to keep up-to-date.

**Comment by volth** [comment] 2017-07-24 07:19
It is very lucky that ```unstable``` got stuck 12 days ago, just before ```master``` got broken.
Now there is no newer nixos, unless you make a custom one by cherry-piking individual commits to ```unstable``` or reverting breaking changes in ```master```

**Comment by fpletz** [comment] 2017-07-26 05:36
Restarted all failing tests multiple times in the last few hours. Tested job is now finished. Unstable channel bump coming up: https://hydra.nixos.org/build/57060626

**Comment by NeQuissimus** [comment] 2017-07-26 12:04
According to https://howoldis.herokuapp.com/ everything has updated in the last few hours \o/

**Closed by NeQuissimus** 2017-07-26 12:04 UTC
