### ISSUE TITLE
nut: tries to start upsd and upsdrv in netclient mode (should only start upsmon)

### ISSUE THREAD

**Issue by ppenguin** [NixOS/nixpkgs#177139] opened 2022-06-10 07:32 UTC
### Steps To Reproduce
1. set `power.ups = { enable = true; mode = "netclient"; }`
2. rebuild switch
3. observe in syslog/systemd that upsd and upsdrv tried to start but failed

### Expected behavior
Only the service `upsmon` is configured, enabled and started when in `netclient` mode.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.0, NixOS, 22.05 (Quokka), 22.05.20220606.f05e7d3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.0`
 - channels(root): `""`
 - nixpkgs: `/nix/store/c9p9vibs97r2n06gpzvbkg87dl643nm4-source`
```

(Not using channels but a flake, I'm on `22.05`).

**Comment by Majiir** [comment] 2023-01-21 21:52
Duplicate of https://github.com/NixOS/nixpkgs/issues/113735.

**Closed by Majiir** 2023-01-21 21:52 UTC
Labels: 0.kind: bug, 6.topic: nixos
