### ISSUE TITLE
Build failure: pkgsStatic.python3 (only >= 3.12)

### ISSUE THREAD

**Issue by superherointj** [NixOS/nixpkgs#325302] opened 2024-07-07 16:20 UTC
### Steps To Reproduce

1. nix build .#pkgsStatic.python3

### Build log

logs: https://termbin.com/m9x0

### Additional context

* Only breaks Python >= 3.12.
* Python <= 3.11 builds fine.

* Bisect: https://github.com/NixOS/nixpkgs/commit/737b5cd4f2f0113727312a12b4dfceee877a88c3 <details>
  <summary>bisect history</summary>
  <p>git bisect good db863ae6a444853ba42ef89f52197041002587d2 # liburing PR</p>
  <p>git bisect bad c7411f7d53204c98e5561eafe49d35845a92342c # master</p>
  <p>git bisect good 6c00b7166219073f25c87900a0f8dc2cf5a16bdc # Merge branch 'master' into master</p>
  <p>git bisect good 6ca504a59ac29ff04f9c8134d6a0d5d896a2c092 # Merge pull request #324268 from hercules-ci/modules-lib-hygiene</p>
  <p>git bisect bad 30cfd4445f829c08e9d50af761a652de56ab028a # Merge master into staging-next</p>
  <p>git bisect bad 1af1b56504bd63c3d0601a993f196135b7fc4d17 # python3Packages.redis: 5.0.3 -> 5.0.6</p>
  <p>git bisect bad 353978c64b889d76a6b2c7d777eced0485863fc4 # python3Packages.container-inspector: 32.0.1 -> 33.0.0</p>
  <p>git bisect good ce08ce6dacfb2ee4be50e0b96bb37d4b3351f23c # Merge pull request #321998 from NixOS/revert-321095-rust-write-config.toml-not-config</p>
  <p>git bisect bad 888a6c36869bfb4b1d5fb846fff010c295c53040 # python3Packages.ansible-navigator: 24.2.0 -> 24.3.2</p>
  <p>git bisect good 326d84112cbfdb124a9a285843b4f3e9067d2bc2 # Merge #316079: pciutils: 3.12.0 -> 3.13.0</p>
  <p>git bisect bad 67bdfbe30be81269ac9e62627e352635d2fb4b6d # python311Packages.respx: 0.20.2 -> 0.21.0</p>
  <p>git bisect good 1766c845a88dd9d4f303b8c1f639e9f2ac2aa4a2 # Merge #318438: xkeyboard_config: 2.41 -> 2.42</p>
  <p>git bisect bad d1c243dca5fc6bbeaf96282511de64c24908bcc6 [ripper]</p>
  <p>git bisect bad 42699ee57d333ded3e3240b29e74f7a97332074d</p>
  <p>Culprit: 737b5cd4f2f0113727312a12b4dfceee877a88c3 python3: 3.11.9 -> 3.12.4 </p>
</details>

### Notify maintainers

?

**Comment by anmonteiro** [comment] 2024-07-07 20:59
likely a duplicate of https://github.com/NixOS/nixpkgs/pull/325218, fixed in https://github.com/NixOS/nixpkgs/pull/325218

**Comment by superherointj** [comment] 2024-07-07 22:00
> likely a duplicate of #325218, fixed in #325218

That PR is already merged and in master, and master fails the same. Thanks for suggesting though.

**Comment by t4ccer** [comment] 2024-08-20 13:46
Fixed by https://github.com/NixOS/nixpkgs/pull/335986 and builds on master as of now (b2b8d7ce72d51b55ee5903d50d6382705449f9c3)

**Closed by t4ccer** 2024-08-20 13:46 UTC
Labels: 6.topic: python, 6.topic: static, 0.kind: build failure
