### ISSUE TITLE
Package request: vinegar

### ISSUE THREAD

**Issue by ardishco-the-great** [NixOS/nixpkgs#267254] opened 2023-11-13 17:31 UTC
**Project description**

 An open-source, minimal, configurable, fast bootstrapper for running Roblox on Linux. 

**Metadata**

* homepage URL: https://github.com/vinegarhq/vinegar
* source URL: https://github.com/vinegarhq/vinegar
* license: gpl3+
* platforms: linux

**Comment by ayes-web** [comment] 2023-11-14 01:47
Duplicate of #251690

**Closed** 2023-11-14 15:27 UTC
Labels: 2.status: duplicate, 0.kind: packaging request
