### ISSUE TITLE
Packaging request: tuxedo-control-center

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#199506] opened 2022-11-04 11:20 UTC
**Project description**

Tuxedo laptops are Linux laptops from Germany. From their web page:

> The TUXEDO Control Center (short: TCC) gives TUXEDO laptop users full control over their hardware like CPU cores, fan speed and more. To get a more detailed description of features, plans and the ideas behind please check our press release ([english](https://www.tuxedocomputers.com/en/Infos/News/Everything-under-control-with-the-TUXEDO-Control-Center.tuxedo) | [german](https://www.tuxedocomputers.com/de/Infos/News/Alles-unter-Kontrolle-mit-dem-TUXEDO-Control-Center_1.tuxedo)) and info pages ([english](https://www.tuxedocomputers.com/en/TUXEDO-Control-Center.tuxedo#) | [german](https://www.tuxedocomputers.com/de/TUXEDO-Control-Center.tuxedo)).

**Metadata**

* homepage URL: https://github.com/tuxedocomputers/tuxedo-control-center
* source URL: https://github.com/tuxedocomputers/tuxedo-control-center.git
* license: GPL3
* platforms: linux

**Comment by bjornfor** [comment] 2022-11-06 17:08
Duplicate of https://github.com/NixOS/nixpkgs/issues/132206.

**Closed by bjornfor** 2022-11-06 17:08 UTC
Labels: 0.kind: packaging request
