### ISSUE TITLE
KDE's Mouse Settings Lost in unstable-small

### ISSUE THREAD

**Issue by Obikawa** [NixOS/nixpkgs#132890] opened 2021-08-06 12:11 UTC
### Describe the bug
My mouse behavior has reverted to the defaults.
The KCM for mouse settings is gone.

### Steps To Reproduce
Build the current version of KDE in the unstable-small channel.

### Expected behavior
Existence of the mouse KCM is System Settings, ability to configure my mouse.

### Additional context
During the offending update, I have also configured installation of Steam.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.11pre306695.f48eda66dc3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by hqurve** [comment] 2021-08-06 19:38
I just updated nixos-unstable and I also am experiencing the same problem

**Comment by hqurve** [comment] 2021-08-07 17:28
Ping @ttuegel @nyanloutre

**Comment by billksun** [comment] 2021-08-24 15:18
Same issue with nixos-unstable, the mouse KCM is missing.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.60, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - channels(root): `"nixos-21.11pre310725.870959c7fb3"`
 - channels(bill): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by L-as** [comment] 2021-09-13 11:46
Bisecting to find the commit that caused it is likely a good idea if you want this to be fixed.

**Comment by Obikawa** [comment] 2021-09-13 13:09
Does NixOS have an archive of derivations?

**Comment by hqurve** [comment] 2021-09-13 23:31
@Obikawa Hi, I dont know if this is what youre talking about, but there is a history of channels at https://channels.nix.gsc.io/

**Comment by oxalica** [comment] 2021-09-14 10:36
@L-as 
> Bisecting to find the commit that caused it is likely a good idea if you want this to be fixed.

I just ran a bisect. The issue first appears in around 0a9174fd4b948b9db5b1e103825565c9e5f0c726..c4c5c49fa64b7f4a19d1f2141cdac88cd15063da when upgrading KDE-related packages.
The commit in that range 3198bfe23b2535ad7cd3d8078dc72d03f724560a make the default KDE environment failed to build. When it build again in c4c5c49fa64b7f4a19d1f2141cdac88cd15063da, the issue already exists.

**Comment by L-as** [comment] 2021-09-14 12:05
I can't see anything that stands out, maybe it's a bug caused by an upstream change?

**Comment by oxalica** [comment] 2021-09-14 13:02
> I can't see anything that stands out, maybe it's a bug caused by an upstream change?

No. I tested Arch Linux with archive on 2021-08-05, which contains the same version of `plasma-desktop@5.22.4` and `plasma-framework@5.84.0`. It has no issue about Mouse Setting. I believe it's a packaging issue on our side.

**Comment by Artturin** [comment] 2021-09-14 19:38
arch package has kcm_mouse.so but we dont https://archlinux.org/packages/extra/x86_64/plasma-desktop/files/
```
 nix-locate --top-level "plugins/kcm_keyboard.so"
plasma-desktop.out                              519,136 x /nix/store/93l1xk2wcvjcwp5rhryl0dxhsfnminm1-plasma-desktop-5.22.4/lib/qt-5.15.2/plugins/kcm_keyboard.so
 nix-locate --top-level "plugins/kcm_mouse.so"
 nix-locate --top-level "plugins/kcm_clock.so"
plasma-desktop.out                              147,400 x /nix/store/93l1xk2wcvjcwp5rhryl0dxhsfnminm1-plasma-desktop-5.22.4/lib/qt-5.15.2/plugins/kcm_clock.so
```

**Comment by Artturin** [comment] 2021-09-14 20:19
plasma-desktop at `9ec1f8f88f7818aacce7df23ad3d775e8d9f8ed8` has it `/nix/store/7ygqnv13yi4yb2cqpn437bdgm1yafasn-plasma-desktop-5.21.5/lib/qt-5.15.2/plugins/kcm_mouse.so`

build logs for nixos-unstable and at 9ec1f https://gist.github.com/Artturin/4ceaede555b076e3affef8a874749beb

**Comment by Artturin** [comment] 2021-09-14 21:09
i've made a pr in whichthere's a kcm_mouse.so so the issue should be fixed
https://nixos.wiki/wiki/Nixpkgs/Reviewing_changes

**Closed** 2021-09-17 22:24 UTC
Labels: 0.kind: bug, 6.topic: qt/kde
