### ISSUE TITLE
autogenerated Unsupported git:// github URLs causing problems

### ISSUE THREAD

**Issue by tysonzero** [NixOS/nixpkgs#165246] opened 2022-03-22 09:30 UTC
### Describe the bug
There are a variety of `git://` URLs in nixpkgs, and they are [no longer supported](https://github.blog/2021-09-01-improving-git-protocol-security-github/). In my specific case it is the `ghcjs-base` one that's breaking the build.

### Steps To Reproduce
Build any package that uses a `git://` URL that isn't already cached.
On a fresh install, building `ghcjs-base` should do the trick:
```
exporting git://github.com/ghcjs/ghcjs-base (rev 85e31beab9beffc3ea91b954b61a5d04e708b8f2) into /nix/store/0fnf3zdl50j7awsv8znc3q9axlygpvla-ghcjs-base-85e31be
Initialized empty Git repository in /nix/store/0fnf3zdl50j7awsv8znc3q9axlygpvla-ghcjs-base-85e31be/.git/
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
Unable to checkout 85e31beab9beffc3ea91b954b61a5d04e708b8f2 from git://github.com/ghcjs/ghcjs-base.
```

### Expected behavior
Build success

### Notify maintainers
@ElvishJerricco @dfordivam

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.1.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by austinbutler** [comment] 2022-03-23 16:53
I've noticed this, too. Added a workaround to the Javascript docs recently: https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/javascript.section.md#git-protocol-error

Seeing it now in some Python packages as well. It's easy enough to work around locally, but does Hydra have any of the same config in place to work around the issue? Should it?

**Comment by lucc** [comment] 2022-03-24 21:38
I have opened #165691 because it seemed easy enough.  I hope that is ok and I did not go ahead of somebody who is already working on this.

This is the remaining list from `git grep --files-with-matches git://github`:

- `doc/contributing/coding-conventions.chapter.m`
   should be kept because it compares different url schemes
- `doc/languages-frameworks/javascript.section.md`
   the docs mentioned by @austinbutler.
- `pkgs/development/lisp-modules/from-quicklisp/barebones-quicklisp-expression.sh`
   the script does some checks about the git:// urls and also about https:// urls; it does not use them directly so I think it is ok to keep it
- `pkgs/development/lua-modules/generated-packages.nix`
   autogenerated file
- `pkgs/development/node-packages/node-packages.nix`
   autogenerated file
- `pkgs/servers/matrix-appservice-discord/yarn-dependencies.nix`
- `pkgs/servers/web-apps/frab/Gemfile.lock`
- `pkgs/servers/web-apps/frab/gemset.nix`
- `pkgs/tools/package-management/nixui/default.nix`
- `pkgs/tools/package-management/nixui/node-packages.nix`
   autogenerated file
- `pkgs/tools/security/onlykey/default.nix`
- `pkgs/tools/security/onlykey/node-packages.nix`
   autogenerated file

I am not sure about the autogenerated files. The script maintainers/scripts/update-luarocks-packages for example updates the versions of many other lua packages in `pkgs/development/lua-modules/generated-packages.nix`.

**Comment by dtzWill** [comment] 2022-03-25 00:55
As mentioned above, some python package(s) are failing.   I'm seeing this in `pythonPackages.editorconfig` (consider checking `pythonPackages.editorconfig.src` to get right to it):

```
this derivation will be built:
  /nix/store/abck0qdmd3l8ypm455fyy51jyvrrmwpa-source.drv
building '/nix/store/abck0qdmd3l8ypm455fyy51jyvrrmwpa-source.drv'...
exporting https://github.com/editorconfig/editorconfig-core-py.git (rev v0.12.3) into /nix/store/k6c0q67axsll5cx1ldnzgpxmlpz44040-source
Initialized empty Git repository in /nix/store/k6c0q67axsll5cx1ldnzgpxmlpz44040-source/.git/
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 31 (delta 0), reused 14 (delta 0), pack-reused 0
Unpacking objects: 100% (31/31), 22.90 KiB | 2.08 MiB/s, done.
From https://github.com/editorconfig/editorconfig-core-py
 * tag               v0.12.3    -> FETCH_HEAD
Switched to a new branch 'fetchgit'
Submodule 'tests' (git://github.com/editorconfig/editorconfig-core-test.git) registered for path 'tests'
Initialized empty Git repository in /nix/store/k6c0q67axsll5cx1ldnzgpxmlpz44040-source/tests/.git/
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
Unable to checkout e407c1592df0f8e91664835324dea85146f20189 from git://github.com/editorconfig/editorconfig-core-test.git.
```

I mention this because it's first time I've seen someone mention where this gets particularly unfortunate: git submodules that point to `git://`.  Not sure how to best find all the packages that have issues with that (hopefully not many!), do we still have a "check all the downloads" mode/feature?  Or maybe just look for packages that have the submodules flag set to true.

This is an unfortunate change in terms of the impact it has on reproducibility of Nixpkgs pacakges (especially "historically", even recently), and I'm glad at least we host a bunch of tarballs content-addressed ( http://tarballs.nixos.org/ ).  Even so, this might mean a bunch of stuff from older releases doesn't work anymore and that's a shame.

Important packages will likely fix their own trees re:git-submodules.

I couldn't get the `.gitconfig` change to work, but I didn't look too hard at where nix's git was reading its config from.  If we injected that redirection into `fetchgit` or whichever, would that change hashes, or maybe that's an idea?

**Comment by lucc** [comment] 2022-03-25 09:52
Regeneration of pkgs/development/node-packages/node-env.nix failed because at some point it tries to pull git://github.com/btc21/btc-rpc-client .  This package is not referenced in nixpkgs elsewhere so I assume it is some node dependency of some node package that nixpkgs has. It is also a fork of https://github.com/ruimarinho/bitcoin-core which was not updated since 2019.

So I think here the same issue arises as with the python example above: we have to tell the git config in the nix sandbox that it should switch to https under the hood.

**Comment by SuperSandro2000** [comment] 2022-03-28 08:15
Going to fix python39Packages.editorconfig right now.

**Comment by lucc** [comment] 2022-03-28 11:40
I am not sure if this should have been closed by  #165691. I added the `Fix` note very early and the later half of the discussion revealed that the problem is bigger than I initially thought (node packages, python packages).

@tysonzero your original example with ghcjs-base should be fixed but for @dtzWill and @austinbutler can you confirm that this is really fixed?

**Comment by lucc** [comment] 2022-03-28 13:22
Maybe the developers of node2nix and similar tools can be urged to implement a fix for the: replacing `git://github` urls with `https://github` urls before writing the generated .nix files. That way not only NixOS but other users of these tools would also benefit from the fix and some old node (or whatever) packages could still be installed via nix even if the upstream project takes a long time to fix the problem in their dependency list.

**Comment by lilyinstarlight** [comment] 2022-03-31 12:54
> Maybe the developers of node2nix and similar tools can be urged to implement a fix for the: replacing `git://github` urls with `https://github` urls before writing the generated .nix files.

I just happened to notice this issue, but the problem with node2nix generating `git://github.com` URLs instead of `https://github.com` URLs has been fixed in svanderburg/node2nix#280. A release just hasn't been made since that PR was merged

**Comment by lucc** [comment] 2022-04-01 07:27
@Mic92 may I ask the question from https://github.com/NixOS/nixpkgs/pull/165691#issuecomment-1079003985 again:

> frab also references git://github.com but it seems that frab was removed in [6fa3728](https://github.com/NixOS/nixpkgs/commit/6fa3728805f04ec367b8f42ba3d3fc77e3d96513) a long time ago. @Mic92 can you shed some light on why the folder `pkgs/servers/web-apps/frab/` and its contents exist even though you deleted the default.nix in [6fa3728](https://github.com/NixOS/nixpkgs/commit/6fa3728805f04ec367b8f42ba3d3fc77e3d96513)?

**Comment by SuperSandro2000** [comment] 2022-04-11 09:41
> I just happened to notice this issue, but the problem with node2nix generating git://github.com URLs instead of https://github.com URLs has been fixed in https://github.com/svanderburg/node2nix/pull/280. A release just hasn't been made since that PR was merged

We already have A patch collection for node2nix. We can just add that commit to there.

**Comment by Fuuzetsu** [comment] 2022-04-12 02:25
>We already have A patch collection for node2nix. We can just add that commit to there.

It doesn't apply cleanly. It seems better to just drop all the patches we have and use the most recent git version. The below seems to compile though I'm unsure if the node dependencies are correct.

```patch
diff --git a/pkgs/development/node-packages/default.nix b/pkgs/development/node-packages/default.nix
index d31da0892e4..e24224693ed 100644
--- a/pkgs/development/node-packages/default.nix
+++ b/pkgs/development/node-packages/default.nix
@@ -254,39 +254,11 @@ let
       # So we pin the patched commit instead. The commit actually contains two other newer commits
       # since the last (1.9.0) release, but actually this is a good thing since one of them is a
       # Hydra-specific fix.
-      src = applyPatches {
-        src = fetchFromGitHub {
+      src = fetchFromGitHub {
           owner = "svanderburg";
           repo = "node2nix";
-          rev = "node2nix-1.9.0";
-          sha256 = "0l4wp1131nhl9c14cn8bwawb8f77h1nfbnswgi5lp5m3kzkb27jn";
-        };
-
-        patches = [
-          # remove node_ name prefix
-          (fetchpatch {
-            url = "https://github.com/svanderburg/node2nix/commit/b54d45207427ff46e90f16f2f32771fdc8bff5a4.patch";
-            sha256 = "sha256-ubUdF0q3l4xxqZ7f9EiQEUQzyqxi9Q6zsRPETHlfzh8=";
-          })
-          # set meta platform
-          (fetchpatch {
-            url = "https://github.com/svanderburg/node2nix/commit/58736093161f2d237c17e75a96529b018cd0ac64.patch";
-            sha256 = "0sif7803c9g6gjmmdniw5qxrq5igiz9nqdmdrcf1hxfi5x43a32h";
-          })
-          # Extract common logic from composePackage to a shell function
-          (fetchpatch {
-            url = "https://github.com/svanderburg/node2nix/commit/e4c951971df6c9f9584c7252971c13b55c369916.patch";
-            sha256 = "0w8fcyr12g2340rn06isv40jkmz2khmak81c95zpkjgipzx7hp7w";
-          })
-          # handle package alias in dependencies
-          # https://github.com/svanderburg/node2nix/pull/240
-          #
-          # TODO: remove after node2nix 1.10.0
-          (fetchpatch {
-            url = "https://github.com/svanderburg/node2nix/commit/644e90c0304038a446ed53efc97e9eb1e2831e71.patch";
-            sha256 = "sha256-sQgVf80H1ouUjzHq+2d9RO4a+o++kh+l+FOTNXfPBH0=";
-          })
-        ];
+          rev = "d5ea8f0c2e35257350fb893ad1c27d9ea28e9e8b";
+          sha256 = "sha256-3ihOD8dzcMGWhfum3nkU6ZjKWxxUdfn4ix11t4Clxr8=";
       };
       postInstall = ''
         wrapProgram "$out/bin/node2nix" --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.nix ]}
```

**Comment by SuperSandro2000** [comment] 2022-04-12 12:23
Great, open a PR and we will see if it works.

**Comment by Fuuzetsu** [comment] 2022-04-12 13:53
I can make one for node2nix but it seems to take well over an hour for updating node packages which I'm not really willing to sit through... I gave up trying to update vscode rust analyzer in tree (how I hit this issue to start with) due to this and just extracted it out of nixpkgs. Maybe I'm doing something wrong: do people really wait hours when updating anything using node packages?

**Comment by SuperSandro2000** [comment] 2022-04-13 10:37
> do people really wait hours when updating anything using node packages?

Yes but I assume they mostly let it run in the background.

**Comment by happysalada** [comment] 2022-05-02 04:48
alright, I took a shot at it https://github.com/NixOS/nixpkgs/pull/171195
I would ideally like to merge in not too long.

**Comment by dasJ** [comment] 2022-05-21 17:08
I'd like to remind the people here that branch-off is scheduled for tomorrow and depending on how good the staging builds progress, we will branch off rather soon.

**Comment by mweinelt** [comment] 2022-05-22 09:40
Is this resolved after https://github.com/NixOS/nixpkgs/pull/165691?

**Closed** 2022-05-23 12:12 UTC
Labels: 0.kind: bug
