### ISSUE TITLE
pinentry-tty: skip build qt5 and gtk2 libraries

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#96306] opened 2020-08-25 20:08 UTC
**Describe the bug**
When building the pinentry-tty package, the qt5 and gtk2 libraries are prebuilding.
How can I skip prebuilding qt5 and gtk2 libraries?

**Temporary solution**
Remove `"gtk2"`, `"qt"` from `enabledFlavors` and change `pinentryMkDerivation = stdenv.mkDerivation;`
```
diff --git a/pkgs/tools/security/pinentry/default.nix b/pkgs/tools/security/pinentry/default.nix
index e6d07888d1d..fc3dbfa2b14 100644
--- a/pkgs/tools/security/pinentry/default.nix
+++ b/pkgs/tools/security/pinentry/default.nix
@@ -2,7 +2,7 @@
 , libgpgerror, libassuan, qtbase, wrapQtAppsHook
 , ncurses, gtk2, gcr
 , libcap ? null, libsecret ? null
-, enabledFlavors ? [ "curses" "tty" "gtk2" "qt" "gnome3" "emacs" ]
+, enabledFlavors ? [ "curses" "tty" "gnome3" "emacs" ]
 }:

 with stdenv.lib;
@@ -10,10 +10,7 @@ with stdenv.lib;
 assert isList enabledFlavors && enabledFlavors != [];

 let
-  pinentryMkDerivation =
-    if (builtins.elem "qt" enabledFlavors)
-      then mkDerivation
-      else stdenv.mkDerivation;
+  pinentryMkDerivation = stdenv.mkDerivation;

   mkFlag = pfxTrue: pfxFalse: cond: name:
     "--${if cond then pfxTrue else pfxFalse}-${name}";
@@ -31,9 +28,7 @@ let
   flavorInfo = {
     curses = { bin = "curses"; flag = "curses"; buildInputs = [ ncurses ]; };
     tty = { bin = "tty"; flag = "tty"; };
-    gtk2 = { bin = "gtk-2"; flag = "gtk2"; buildInputs = [ gtk2 ]; };
     gnome3 = { bin = "gnome3"; flag = "gnome3"; buildInputs = [ gcr ]; nativeBuildInputs = [ wrapGAppsHook ]; };
-    qt = { bin = "qt"; flag = "qt"; buildInputs = [ qtbase ]; nativeBuildInputs = [ wrapQtAppsHook ]; };
     emacs = { bin = "emacs"; flag = "emacs"; buildInputs = []; };
   };
```

cc @matthewbauer @worldofpeace @flokli @fpletz

**Comment by worldofpeace** [comment] 2020-08-25 20:13
@Izorkin There isn't actually a `pinentry-tty` in `all-packages.nix`
One could add
```
pinentry-tty =  (stdenv.lib.getOutput "tty" pinentry);
```

**Comment by Izorkin** [comment] 2020-08-25 20:23
I have tested with this configuration:
```
  programs.gnupg.agent = {
    enable = true;
    pinentryFlavor = "tty";
  };
```
With `pinentry-tty =  (stdenv.lib.getOutput "tty" pinentry);`:

```
[2/0/5 built, 0.0 MiB DL] building qtquickcontrols-5.14.2 (installPhase): /nix/store/qcxqlgs73pjhx0aahnn0f7mziwldj35a-qtbase-5.14.2-dev/bin/qmake -install qinstall /build/qtquick
```

**Comment by flokli** [comment] 2020-08-27 10:06
This works as intended. Pinentry is a multi-output derivation, and if for some reason you need to rebuild it, you need to pass in all dependencies. The different outputs contain the respective flavors, so just *substituting* (not building) the gtk flavor wouldn't pull in the qt libraries.

**Comment by Izorkin** [comment] 2020-08-27 12:27
Qt libraries are starting to build on my server, but eventually they are not used. How do I skip a build qt?

**Comment by flokli** [comment] 2020-08-27 17:15
Do you do anything weird (some override deep in the chain) on that server, that causes pinentry to be rebuilt? It should be in the cache…

**Comment by Izorkin** [comment] 2020-08-27 17:19
Me using custom patches and using this PR - #81172

**Comment by flokli** [comment] 2020-09-10 19:25
Yeah, this PR triggers a world-rebuild (and hydra doesn't build every PR), see https://github.com/NixOS/nixpkgs/pull/81172#issuecomment-666953033.

**Comment by flokli** [comment] 2020-11-04 08:37
I still think having to rebuild things by yourself if you base your system on a world-rebuilding PR that's not covered by hydra is expected.

The pinentry expression isn't set up in a way to support building it without any graphical inputs.

The runtime closure of the individual non-graphical pinentries don't include qt. I don't think complicating the pinentry recipe to make building without graphical *inputs* is worthwile.

Do you really need pinentry? Wouldn't a gpg with `enableMinimal = true`, and `pinentry = null` be sufficient? (for pointers, look at the `gnupg` that's passed into `systemd`).

**Comment by flokli** [comment] 2020-11-04 08:40
So, to reply to the issue description: No, there's currently no way to skip building these, and I don't think it'll be beneficial - I'd suggest bulding gnupg without pinentry support for these usecases, which already is supported.

**Comment by Izorkin** [comment] 2020-11-04 08:58
I am using pinentry for signing in git commits. I don't use the graphical shell on the server.

**Comment by flokli** [comment] 2020-11-04 09:01
Well, if you don't want to rebuild the world, I propose not using the nftables PR for now, or substituting from a cache that builds things for you.

**Comment by Izorkin** [comment] 2020-11-04 09:04
Splitting the pinentry package into separate pinentry-tty pinentry-qt packages is not possible?

**Comment by arianvp** [comment] 2020-11-04 11:13
Instead of modifying the derivation; why not just use an `override` ?  Does adding this to your overlay fix it for you?:
```nix
self: super: {
  pinentry-tty =  super.pinentry.override { enabledFlavors = [ "curses" "tty" ];};
};
```

the arguments are there for you to supply if you want something custom.

**Comment by Izorkin** [comment] 2020-11-05 04:51
Thanks for help. Working with this variant:
```
self: super: {
  pinentry = super.pinentry.override { enabledFlavors = [ "curses" "tty" ]; };
}
```

**Comment by arianvp** [comment] 2020-11-05 11:26
Okay. I will close this issue then for now.

**Closed by arianvp** 2020-11-05 11:26 UTC
Labels: 0.kind: bug
