### ISSUE TITLE
Build failure: jetbrains.clion

### ISSUE THREAD

**Issue by stepech** [NixOS/nixpkgs#223734] opened 2023-03-29 11:39 UTC
### Steps To Reproduce

1. build jetbrains.clion on unstable branch

### Build log

```console
error: builder for '/nix/store/j8c544hm2sbf76z0mywsjk10hc8hhv17-clion-2022.3.3.drv' failed with exit code 1;
       last 10 log lines:
       > setting RPATH to: /nix/store/shasq3azl2298vqkvq5mc7vivdqp3yrj-gcc-12.2.0-lib/lib
       > setting interpreter of /nix/store/2h515x04qwhhp2kh0m6g7239snn61j2b-clion-2022.3.3/clion/bin/ninja/linux/x64/ninja
       > searching for dependencies of /nix/store/2h515x04qwhhp2kh0m6g7239snn61j2b-clion-2022.3.3/clion/bin/ninja/linux/x64/ninja
       >     libstdc++.so.6 -> found: /nix/store/shasq3azl2298vqkvq5mc7vivdqp3yrj-gcc-12.2.0-lib/lib
       > setting RPATH to: /nix/store/shasq3azl2298vqkvq5mc7vivdqp3yrj-gcc-12.2.0-lib/lib
       > auto-patchelf: 1 dependencies could not be satisfied
       > error: auto-patchelf could not satisfy dependency libcrypt.so.1 wanted by /nix/store/2h515x04qwhhp2kh0m6g7239snn61j2b-clion-2022.3.3/clion/bin/lldb/linux/x64/lib/python3.8/lib-dynload/_crypt.cpython-38-x86_64-linux-gnu.so
       > auto-patchelf failed to find all the required dependencies.
       > Add the missing dependencies to --libs or use `--ignore-missing="foo.so.1 bar.so etc.so"`.
       > /nix/store/sw36plhp82916wwg6i6097rkzza7d950-stdenv-linux/setup: line 136: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/j8c544hm2sbf76z0mywsjk10hc8hhv17-clion-2022.3.3.drv'.
```

### Additional context

flake.lock:
```json
"unstable": {
      "locked": {
        "lastModified": 1679944645,
        "narHash": "sha256-e5Qyoe11UZjVfgRfwNoSU57ZeKuEmjYb77B9IVW7L/M=",
        "owner": "NixOs",
        "repo": "nixpkgs",
        "rev": "4bb072f0a8b267613c127684e099a70e1f6ff106",
        "type": "github"
      },
      "original": {
        "owner": "NixOs",
        "ref": "nixos-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    },

```

### Notify maintainers

@edwtjo @Mic92 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.21, NixOS, 22.11 (Raccoon), 22.11.20230328.5b7cd5c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by dev-null-undefined** [comment] 2023-03-30 22:31
Duplicate of #223677 which has been resolved in #223685.

**Closed** 2023-03-31 15:32 UTC
Labels: 0.kind: build failure
