### ISSUE TITLE
lm-math font packaged 4 times

### ISSUE THREAD

**Issue by Mathnerd314** [NixOS/nixpkgs#76923] opened 2020-01-04 05:48 UTC
A grep of `lm-math`:
```
pkgs/data/fonts/lm-math/default.nix:  url = "http://www.gust.org.pl/projects/e-foundry/lm-math/download/latinmodern-math-1959.zip";
pkgs/data/fonts/lmodern/lmmath.nix:  url = "http://www.gust.org.pl/projects/e-foundry/lm-math/download/lmmath0903otf";
pkgs/tools/typesetting/satysfi/default.nix:  lm-math = fetchzip {
pkgs/tools/typesetting/satysfi/default.nix:    url = "http://www.gust.org.pl/projects/e-foundry/lm-math/download/latinmodern-math-1959.zip";
pkgs/tools/typesetting/satysfi/default.nix:      cp -r ${lm-math}/otf/latinmodern-math.otf lib-satysfi/dist/fonts/
pkgs/tools/typesetting/tex/texlive/fixedHashes.nix:"lm-math-1.959"="j995x0y357lac8mn1kzn9v8p3v995bz7";
```

The latest version is 1.959 per http://www.gust.org.pl/projects/e-foundry/lm-math/download.

I'd say that the texlive and fonts/lm-math versions can stay as they have different paths (`fonts/opentype/public/lm-math/latinmodern-math.otf` vs `share/fonts/opentype/latinmodern-math.otf`), although ideally just the texlive version would stay, but the others are not helping anything at all.

**Comment by Mathnerd314** [comment] 2020-01-04 19:41
cc @langston-barrett @7c6f434c @mt-caret @vbgl @veprbl for comments

**Comment by veprbl** [comment] 2020-01-07 01:47
* `latinmodern-math` [pkgs/data/fonts/lm-math/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/data/fonts/lm-math/default.nix) – has meta, unpacks only the needed files
* `lmmath` [pkgs/data/fonts/lmodern/lmmath.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/data/fonts/lmodern/lmmath.nix) – resides in the same directory with `lmodern`, tries to provide texmf

So, perhaps, we should keep the implementation of `latinmodern-math` under the name `lmmath` and make `latinmodern-math` an alias. The satysfi needs to be fixed to use existing packages (also implements a duplicate of `lmodern`).

**Comment by Mathnerd314** [comment] 2020-01-07 17:54
Well, for texmf one would presumably use the TexLive package, as it has separated `run` and `doc` outputs unlike the other packages. And it auto-updates along with the rest of TexLive.

The only issue with using it as the sole package is that it's not a multiple output derivation so using it in the fonts list looks like
```nix
builtins.elemAt texlive.lm-math.pkgs 0
```
rather than just `texlive.lm-math`.

It shouldn't be that hard to set up TexLive to have attributes usable directly, by setting `outPath` and so forth. Nix doesn't support multiple outputs for fixed-output derivations, so it'd be a bit of a hack.

**Comment by veprbl** [comment] 2020-01-07 18:15
The "packages" in `texlive` are set up to be used with `texlive.combine`. They were not intended to be used in any other way.

**Closed** 2020-03-19 03:55 UTC
Labels: 0.kind: bug, 9.needs: clean-up
