### ISSUE TITLE
dockerTools.buildLayeredImage: files modified time are lost

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#54955] opened 2019-01-30 17:58 UTC
## Issue description

Maybe it's a limitation of the nix store but I'm using `dockerTools.buildLayeredImage` to ship web apps and the static files are served with `last-modified: Thu, 01 Jan 1970 00:00:01 GMT` which caused problems with a web server that would return 304 if the last-modified date matched but not the etag.

### Steps to reproduce

default.nix
```nix
with (import <nixpkgs> {});
stdenv.mkDerivation {
  name = "test-docker-mtime";

  src = /home/me/dev/nix-docker/staging;

  installPhase = ''
    mkdir -p $out
    cp $src/test $out/test
  '';
}
```

docker.nix
```nix
with import <nixpkgs> {};

let
  test-docker-mtime = import ./default.nix;
in pkgs.dockerTools.buildLayeredImage {
  created = "now";
  name = "test-docker-mtime";
  tag = "latest";

  contents = [
     test-docker-mtime
     pkgs.bash
     pkgs.coreutils
  ];
}
```

mkdir staging
touch staging/test

nix-build docker.nix && docker load < ./result
docker run -it --rm test-docker-mtime bash

**inside the container:**
bash-4.4# ls -l test
lrwxrwxrwx 1 0 0 66 Jan  1  1970 test -> /nix/store/99jka132ijzvvgxag0mlimvdim4k0d4f-test-docker-mtime/test
bash-4.4# ls -l /nix/store/99jka132ijzvvgxag0mlimvdim4k0d4f-test-docker-mtime/test
-r--r--r-- 1 0 0 0 Jan  1  1970 /nix/store/99jka132ijzvvgxag0mlimvdim4k0d4f-test-docker-mtime/test

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.16, NixOS, 19.03.git.bc41317 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-18.09.1985.749a3a0d00b, nixos-unstable-19.03pre166987.bc41317e243"`
 - channels(bbigras2): `"home-manager-18.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by arianvp** [comment] 2019-02-06 16:50
I don't think we can do much about this? We set time to 1970 on purpose to keep builds reproducible

**Comment by roberth** [comment] 2020-02-28 14:08
We could allow passing a different value for [`mtime`](https://github.com/NixOS/nixpkgs/blob/8c1cb557c6dbd77281a2b16804310385faf27ca7/pkgs/build-support/docker/default.nix#L375).
That doesn't make the build impure, but does allow the caller to specify a better time.

**Comment by bbigras** [comment] 2020-08-26 19:50
> We could allow passing a different value for mtime.
That doesn't make the build impure, but does allow the caller to specify a better time.

Would that be the same mtime for **every** files?

**Comment by roberth** [comment] 2020-08-26 20:37
That's one option.
My thoughts right now are that this should only apply to the customization layer / `extraCommands`, which is where you get to do things on the root filesystem. Changing the mtime on store paths is a bad idea, because those are expected to be set to 1970 +1s. Some code may rely on that.
This is not much of a limitation, because if you want mtimes in your image you need to do something extra anyway, so you might as well put it in `/opt/something`.
In case the store path being served is part of some package, that's a already a problem that should be solved by configuring or patching the package to work with etags instead. The store hash is suitable as an etag, or for an optimized solution you could hash the individual files to produce the etag.

As to why modified times are not so great, imagine the scenario
 - commit `111` is built with mtime Aug 26 and deployed
 - client loads the site, caches the resources
 - commit `222` is built with mtime Aug 27 and deployed
 - client loads the site, caches the updated resources
 - commit `222` is reverted and deployed. The build from 26 aug is still on the server so deployment was quick, yay!
 - client loads the site, with cached incompatible resources from `222`

So if you really want to take the risk and get a time from somewhere, you might be able to do it outside the container's store with `extraCommands`, at the cost of losing the ability to cache the package. I can't recommend it.

**Comment by arianvp** [comment] 2020-08-27 12:10
I'd be in favor of closing this.

**Closed** 2020-08-27 12:29 UTC
