### ISSUE TITLE
Python 3.8 and virtualenv 16.7.9 don't seem to work together

### ISSUE THREAD

**Issue by nicksloan** [NixOS/nixpkgs#85791] opened 2020-04-22 16:35 UTC
virtualenv 16.7.9 reports a failure to create a virtualenvironment due to sys.prefix pointing at the system install with Python 3.8.2.

**To Reproduce**
1. Here is a minimal shell.nix:
```
with import <nixpkgs> {};

stdenv.mkDerivation rec {
  name = "testing";
  env = buildEnv { name = name; paths = buildInputs; };
  buildInputs = [
    (python38.withPackages (pypkgs: [ pypkgs.pip pypkgs.virtualenv ]))
  ];
  shellHook = ''
    # set SOURCE_DATE_EPOCH so that we can use python wheels
    SOURCE_DATE_EPOCH=$(date +%s)
  '';
}
```
2. `nix-shell`
3. `virtualenv venv`
4. You should receive the error output:
```
ERROR: The executable /Users/redacted/testing/venv/bin/python3.8 is not functioning
ERROR: It thinks sys.prefix is '/nix/store/brjnpp33n93756g91h7i67mfpa1glzwh-python3-3.8.2-env' (should be '/Users/redacted/testing/venv')
ERROR: virtualenv is not compatible with this system or executable
```

I would expect the virtualenvironment to be created successfully, as it is with Python 3.7 (you can verify by replacing 3.8 with 3.7 in the shell.nix above).

Mentioning @FRidh because they seem involved in the Python package.

**Metadata**
```
these paths will be fetched (0.01 MiB download, 0.03 MiB unpacked):
  /nix/store/y0nssfi6jbigi086956byiccgfbqnp7l-nix-info
  /nix/store/ymhnvv1pljb5asj7k4ab80dx6i7dx6a7-DarwinTools-1
copying path '/nix/store/ymhnvv1pljb5asj7k4ab80dx6i7dx6a7-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/y0nssfi6jbigi086956byiccgfbqnp7l-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.2.0, macOS 10.15.2`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.2`
 - channels(nicksloan): `"nixpkgs-20.09pre221814.10100a97c89"`
 - nixpkgs: `/Users/nicksloan/.nix-defexpr/channels/nixpkgs`
```

**Comment by FRidh** [comment] 2020-04-22 16:38
Duplicate of https://github.com/NixOS/nixpkgs/issues/66366.

**Closed by FRidh** 2020-04-22 16:38 UTC
Labels: 0.kind: bug, 6.topic: python

**Comment by FRidh** [comment] 2020-04-22 16:55
Also https://github.com/NixOS/nixpkgs/issues/79702.

**Comment by FRidh** [comment] 2020-04-22 16:59
When possible, I recommend *not* using `virtualenv` but `venv`, which is part of the standard library in Python 3.

**Comment by jonringer** [comment] 2020-04-22 18:45
@nicksloan to get you unstuck, please refer to https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#how-to-consume-python-modules-using-pip-in-a-virtual-environment-like-i-am-used-to-on-other-operating-systems . Should get you started with a valid dev environment.

I generally also have to do:
```
  postShellHook = ''
    # Allow the use of wheels.
    unset SOURCE_DATE_EPOCH

    PYTHONPATH=$PWD/$venvDir/${python.sitePackages}:$PYTHONPATH
  '';
```
for python to pick up the newly installed packages
