### ISSUE TITLE
systemctl --user is broken

### ISSUE THREAD

**Issue by anders-memsql** [NixOS/nixpkgs#15653] opened 2016-05-23 21:14 UTC
## Issue description

I've just upgraded to the latest nixos-unstable, and now all systemctl commands fail when passed the --user option.
### Steps to reproduce
# reboot to get as clean a state as possible

```
$ systemctl --user
Failed to list units: Process org.freedesktop.systemd1 exited with status 1
$ echo $?
1
```
## Technical details

$ nixos-version 
16.09.git.cc41cb3M (Flounder)
$ nix-env --version
nix-env (Nix) 1.11.2
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.09.git.cc41cb3M"

**Comment by DamienCassou** [comment] 2016-05-24 09:03
works for me

```
$ nixos-version
16.09.git.13f67b9 (Flounder)
$ nix-env --version
nix-env (Nix) 1.11.2
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.09.git.13f67b9"
```

**Comment by joelmo** [comment] 2016-05-24 19:49
Works here too:
```
[joelmo@jmdesk:~]$ nixos-version 
16.09pre83955.cc41cb3 (Flounder)

[joelmo@jmdesk:~]$ systemctl --user
UNIT                                LOAD   ACTIVE SUB       DES
sys-devices-pci0000:00-0000:00:17.0-ata1-host0-target0:0:0-0:0:
sys-devices-pci0000:00-0000:00:17.0-ata1-host0-target0:0:0-0:0:
```

**Comment by makefu** [comment] 2016-07-20 22:39
having the same issue
```
~ nixos-version
16.09.git.125ffff (Flounder)
~ systemctl --user
Failed to list units: Process org.freedesktop.systemd1 exited with status 1
```

**Comment by domenkozar** [comment] 2016-07-22 13:07
```
$ nixos-version 
16.03.1111.f231b2b (Emu)

$ systemctl --user
Failed to connect to bus: No such file or directory
```

**Comment by grahamc** [comment] 2016-07-22 13:13
```
$ nixos-version
16.03.1083.d745044 (Emu)
$ systemctl --user
UNIT                                                  LOAD   ACTIVE SUB     DESCRIPTION
...
```

**Comment by siddharthist** [comment] 2016-07-29 22:58
Works for me:
```
~ > systemctl --user --no-pager
UNIT                           LOAD   ACTIVE SUB     DESCRIPTION
~ > nixos-version
16.09pre85931.125ffff (Flounder)
~ > nix-env --version 
nix-env (Nix) 1.11.2
```
Can we close this?

**Comment by makefu** [comment] 2016-07-30 09:29
@siddhanathan the problem persists for me unfortunately.
```
~ systemctl --user --no-pager          
Failed to list units: Process org.freedesktop.systemd1 exited with status 1
~ nixos-version
16.09.git.125ffff (Flounder)
~ nix-env --version
nix-env (Nix) 1.11.2
~ date
Sat Jul 30 11:26:43 CEST 2016
```

The thing is, the issue is somewhat flakey and sometimes i even have it seen disappear. i do not know how to triage this. maybe it is due to low disk space. i will update the comment once i cleaned my root disk

**Comment by michalrus** [comment] 2016-09-21 10:45
Still happens on…

```
% nixos-version
16.09beta335.7617e7e (Flounder)
% systemctl --user
Failed to list units: Process org.freedesktop.systemd1 exited with status 1
% export | grep ^XDG
XDG_CONFIG_DIRS=/home/m/.nix-profile/etc/xdg:/nix/var/nix/profiles/default/etc/xdg:/run/current-system/sw/etc/xdg
XDG_DATA_DIRS=/home/m/.nix-profile/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/m
XDG_SEAT=seat0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_DESKTOP='none + i3'
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SESSION_TYPE=x11
XDG_VTNR=7
%
```

Please note, that `XDG_RUNTIME_DIR` is **not** exported, and it should be.

**Comment by ericsagnes** [comment] 2016-10-16 15:23
Same problem here, setting `XDG_RUNTIME_DIR` solves the problem:

```
$ systemctl --user
Failed to list units: Process org.freedesktop.systemd1 exited with status 1
```
but the following works:

```
$ XDG_RUNTIME_DIR="/run/user/$UID" systemctl --user
```

**Comment by Mic92** [comment] 2016-10-16 21:23
This should be set by pam_systemd on login. What is your session manager? @makefu, @michalrus

**Comment by ericsagnes** [comment] 2016-10-16 23:35
> What is your session manager? 

Using slim here.

```
cat --squeeze-blank /etc/pam.d/slim
# Account management.
account sufficient pam_unix.so

# Authentication management.

auth sufficient pam_unix.so nullok likeauth try_first_pass

auth required pam_deny.so

# Password management.
password requisite pam_unix.so nullok sha512

# Session management.
session required pam_env.so envfile=/nix/store/p6hd08lri1yi72jllc35lsdci1a0zdi0-pam-environment

session required pam_unix.so
session required pam_loginuid.so

session optional /nix/store/gslg75qdm4q88rpq1cfpgzhclcx1jipv-systemd-231/lib/security/pam_systemd.so
```

**Comment by michalrus** [comment] 2016-10-16 23:51
@Mic92, and I’m using LightDM (+ i3).

**Comment by makefu** [comment] 2016-10-19 11:11
using `slim` + `awesomewm` issue also occurs *sometimes*, setting XDG_RUNTIME_DIR indeed fixes the issue.
The `/etc/pam.d/slim` of @ericsagnes is equal to mine (except for store paths)

**Comment by Mic92** [comment] 2016-10-23 14:18
For me `XDG_RUNTIME_DIR` is always set.

**Comment by michalrus** [comment] 2016-10-27 13:34
Hey, I’ve got some new insight (perhaps).

Everytime when this happens (still does sometimes), running just `systemctl` highlights:

```
● user@31337.service                                      loaded failed     failed
        User Manager for UID 31337
```

All other services are running correctly.

**Comment by Mic92** [comment] 2016-10-27 13:52
What is the status of this service, when it happen? `systemctl status user@31337.service`

**Comment by michalrus** [comment] 2016-10-27 13:55
I’ll try to catch this situation again and then paste the status.

**Comment by ericsagnes** [comment] 2016-12-10 03:25
The latest nixos-unstable update fixed it for me.

**Closed** 2017-09-08 11:51 UTC
Labels: 0.kind: bug, 6.topic: nixos

**Comment by jpotier** [comment] 2018-09-05 17:10
Hmmm, I bumped into this today. My nixos-version: 18.09pre150708.083220867c7 (Jellyfish)

**Comment by chrissound** [comment] 2019-01-15 11:48
I ran into this issue by accidentally removing all my permissions on my root drive (`/`), and then restoring them. 


Setting `XDG_RUNTIME_DIR` does not seem to make a difference.
```
export XDG_RUNTIME_DIR=/run/user/$(id -u); systemctl --user
Failed to list units: Process org.freedesktop.systemd1 exited with status 1
```

**Comment by chrissound** [comment] 2019-01-15 11:51
@globin why has this issue been closed?

**Comment by grahamc** [comment] 2019-01-15 12:03
@chrissound what is your / filesystem? How did you restore them? systemd's journalctl, for example, requires facls set up.

**Comment by Mic92** [comment] 2019-01-15 17:43
@chrissound The permissions of `/run` should be fixed after reboot.

**Comment by chrissound** [comment] 2019-01-15 18:20
filesystem is ext4, permissions were restored with `getfacl` and `setfacl`.

Working fine after a reboot though.

**Comment by chrissound** [comment] 2019-01-21 10:48
I kept randomly running into this error:
```
systemctl status user@1000.service
● user@1000.service - User Manager for UID 1000
   Loaded: loaded (/nix/store/kinpd6wss80pf2d04jnvvmw25lzkrlbq-systemd-239/example/systemd/system/user@.service; static; vendor preset: enabled)
  Drop-In: /nix/store/4q9hrmcg2l83cvypzdi2mrbh69zm9nss-system-units/user@.service.d
           └─overrides.conf
   Active: failed (Result: protocol) since Mon 2019-01-21 09:21:36 GMT; 1h 17min ago
  Process: 1243 ExecStart=/nix/store/kinpd6wss80pf2d04jnvvmw25lzkrlbq-systemd-239/lib/systemd/systemd --user (code=exited, status=1/FAILURE)
 Main PID: 1243 (code=exited, status=1/FAILURE)

Jan 21 09:21:36 nixos systemd[1]: Starting User Manager for UID 1000...
Jan 21 09:21:36 nixos systemd[1243]: pam_unix(systemd-user:session): session opened for user chris by (uid=0)
Jan 21 09:21:36 nixos systemd[1243]: Failed to fully start up daemon: Permission denied
Jan 21 09:21:36 nixos systemd[1]: user@1000.service: Failed with result 'protocol'.
Jan 21 09:21:36 nixos systemd[1]: Failed to start User Manager for UID 1000.
```
journalctl -u user@1000.service:
```
Jan 21 09:21:36 nixos systemd[1]: Starting User Manager for UID 1000...
Jan 21 09:21:36 nixos systemd[1243]: pam_unix(systemd-user:session): session opened for user chris by (uid=0)
Jan 21 09:21:36 nixos systemd[1243]: Failed to fully start up daemon: Permission denied
Jan 21 09:21:36 nixos systemd[1]: user@1000.service: Failed with result 'protocol'.
Jan 21 09:21:36 nixos systemd[1]: Failed to start User Manager for UID 1000.
```

When it does happen, just restarting the unit seems to work:
```
systemctl restart user@1000.service
````

**Comment by xaverdh** [comment] 2019-12-12 15:56
I get this state consistently when setting `systemd.unified_cgroup_hierarchy=1` on the kernel command line.

**Comment by theAkito** [comment] 2022-11-27 04:53
> XDG_RUNTIME_DIR="/run/user/$UID" systemctl --user

Works for me on `22.05.4334.0faaf0a9bb6 (Quokka)`.

I changed almost nothing about the installed operating system, except adding some users. That's it.

So, definitely not some random user-setup specific issue.
