### ISSUE TITLE
Raspberry Pi 3 B+ doesn't boot on kernel 5.4.23

### ISSUE THREAD

**Issue by ertw** [NixOS/nixpkgs#82455] opened 2020-03-13 01:02 UTC
**Describe the bug**
Following the ARM guide in the wiki, I attempted to boot using `boot.kernelPackages = pkgs.linuxPackages_latest;` After fiddling around with my config for a while, I eventually discovered that I could get it to boot with `boot.kernelPackages = pkgs.linuxPackages_4_19;`

Using 5.4.23, I'm able to select which generation to boot into, but selecting one with 5.4.23 never gets past `Starting kernel ...`

I'm able to press ctrl-alt-delete at that stage to reboot and successfully boot into a generation with 4.19.107. 

**To Reproduce**
1. Follow the wiki guide, and copy the recommended default config for Raspberry Pi 3
1. Run `nixos-rebuild switch` and reboot

**Expected behavior**
Boot into latest kernel

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"aarch64-linux"`
 - host os: `Linux 4.19.107, NixOS, 19.09.2201.7d31bbceaa1 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-unstable-20.09pre215947.82b54d49066, nixos-19.09.2201.7d31bbceaa1"`
 - channels(ertw): `"nixpkgs-unstable-20.09pre215991.93ba4ecd586"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by ertw** [comment] 2020-03-26 13:14
I've been continuing to try to get this working, and am still unable to do so. One thing I noticed was that I was on unstable, so I switched back to stable, and then tried `boot.kernelPackages = pkgs.linuxPackages_latest;` again. Still no luck though, and boot never gets past `Starting kernel...`. I've attached a photo of the display output in case that is helpful.

![image](https://user-images.githubusercontent.com/3650623/77650197-de3c2200-6f49-11ea-96b9-436809246d6f.png)

Interestingly it isn't totally hung here- I can press ctrl-alt-delete to reboot, and then select a previous generation and boot into it fine. Is there any way for me to get additional debug output at this point to better understand where it is getting stuck?

**Comment by 1000101** [comment] 2020-03-27 11:49
Same problem here. Doesn't boot on 5.4.28 either, only 4.19.x work.

**Comment by mebubo** [comment] 2020-03-31 19:21
5.5.13 from the today's nixos-unstable (ae6bdcc5358) also doesn't work for me, hangs at "Starting kernel ..."

**Comment by mebubo** [comment] 2020-03-31 21:23
It turns out that for me the 5.5.13 _does_ boot, it just doesn't initialize hdmi (kudos to Valodim from #nixos-arch64 for the tip).

**Comment by matthewbauer** [comment] 2020-04-01 00:51
I think https://github.com/NixOS/nixpkgs/issues/66960 might be related. /cc @samueldr

**Comment by samueldr** [comment] 2020-04-03 20:01
For now this issue has been tentatively documented here:

 * https://nixos.wiki/wiki/NixOS_on_ARM/Raspberry_Pi#HDMI_output_issue_with_kernel_5.4_.28NixOS_20.03_or_NixOS_unstable.29

**Comment by leonardp** [comment] 2020-04-04 08:01
> Using the following unmodified image:
> 
>     * https://hydra.nixos.org/build/115752495


I was able to boot this image with a Pi 3B+ using hdmi output with a desktop monitor.
Bluetooth was complaining a lot after booting and i couldn't get a serial terminal.

**Comment by Evils-Devils** [comment] 2020-04-04 08:10
i can confirm that my Raspberry Pi 3B+ with [build 115752495](https://github.com/NixOS/nixpkgs/pull/83301/files#diff-f04df51e5409f2d9431186c36d042339R37) boots

there's some odd stuff going on with video output though
- if connected to an active hdmi to vga adapter and then to power, it shows the entire boot process
- if connected to a monitor via a passive hdmi to dvi adapter and then to power, the display gets stuck at displaying `starting kernel...`, but it does boot
- if power is applied (for >1 minute for in this case), and then hdmi directly to an hdmi tv, it starts showing its boot from the start, i can't confirm if it was booted already
- if power is applied, and nothing else, then a keyboard, sshd enabled and a password set (blindly), and then ethernet, i can log in via ssh
  - no video output is available on either hdmi to dvi or hdmi to vga, i did not try it on the hdmi tv

**Comment by leonardp** [comment] 2020-04-04 10:22
> Using the following unmodified image:
> 
>     * https://hydra.nixos.org/build/115752495

to get a proper serial output from this image using a pi 3b+ i needed to:
edit the "APPEND" parameter in NIXOS_SD/boot/extlinux/extlinux.conf so that the
only console argument is
```
console=ttyS1,115200n8
```
without doing that, the serial console stops it's output after  "Starting Kernel".
i also disabled the bluetooth overlay by adding `dtoverlay=disable-bt` to FIRMARE/config.txt
however i don't think that is strictly necessary

plugging in HDMI before booting works but plugging it in after booting gave "No Signal" .

**Comment by samueldr** [comment] 2020-04-04 16:40
Plugging-in HDMI after booting I would assume was never supported by mainline, for the VT at least. Though that's a baseless assumption.

* * *

It does look like it is setup-dependent, which makes this hard to test.

**Comment by Valodim** [comment] 2020-04-04 21:15
I downloaded the image from hydra mentioned above and tried it in two Rpi3B (non-plus) several times, with oddly different results:

* I tried it with HDMI on an LG projector first, no adapter. The first pi got stuck at "Starting kernel...", the second cut off output right after the same message.
* I flashed the sd card again, and tried the same two Pis first on a Samsung monitor, and then an LG one. All those configurations worked as expected.
* I went back to the LG projector, but used the HDMI cable from the monitors before to exclude that source of errors. Everything worked as expected.
* I went back to the LG projector with the original HDMI cable - and everything still worked as expected.

It's possible the errors were caused flashing the sd card for the first time - I have no idea. I now can't reproduce the error state anymore, it just seems to work on the Rpi3B.

**Comment by leonardp** [comment] 2020-04-05 07:27
and if i understand correctly the firmware package supplied with nixpkgs is 1.20190925 while 1.20200212 is available.
i think [this](https://github.com/raspberrypi/firmware/commit/d737daa826adaab8679f83018c3cdc8783d49b59) could be a potential candidate for the observed issues as a mode change occurs after the kernel is initialized (don't quote me on that).
maybe upgrading the raspberrypi firmware could resolve this?

**Comment by mebubo** [comment] 2020-04-05 14:21
Observation:

- if I reboot into a 5.4 from a powered-up state (either by unplugging the power for a second, or by issuing a reboot command), the display always gets stuck on 'Starting kernel...'
- if I unplug the pi, let it and the power supply cool down, and then boot directly into 5.4, the HDMI is initialized correctly

I think this issue may have something to do with power, temperature, dynamic frequency scaling etc.

The commit message in raspberrypi/firmware linked in the comment above mentions turbo clocks. As far as I understand, 5.4 has dynamic frequency scaling for pi which 4.19 lacks?

**Comment by Valodim** [comment] 2020-04-05 16:40
In my weird case (see my last comment), the status went from not working "cold" to working after a while. The previous comment led me to test the setup again. Everything else being exactly the same, booting and hdmi still all works as expected. Leads me to believe I did something wrong on the first test and things are generally working again on the Rpi 3B non-plus

**Comment by lloeki** [comment] 2020-05-16 10:43
Raspberry Pi B failing to display anything past `Starting Kernel` here on a LG TV. The above suggested image did not work. Tried multiple HDMI cables, to no avail.

Steps:

- download latest 20.03 img as of today from Hydra
- `diskutil list`, `diskutil unmountdisk disk5`
- `sudo dd if=nixos-sd-image-20.03.1879.91cdcf31357-aarch64-linux.img of=/dev/rdisk5 bs=1m`
- `diskutil eject disk5`
- mount root fs on another machine able to mount ext4 RW (I'm on macOS, so I used a linux VM and passed the USB card reader to VMware Fusion)
- `mkdir /mnt/path/home/nixos/.ssh && chmod 700 /mnt/path/home/nixos/.ssh`
- added my pubkeys to `/mnt/path/home/nixos/.ssh/authorized_keys` and `chmod 600  /mnt/path/home/nixos/.ssh/authorized_keys`
- boot sd card on Pi while plugged via ethernet, wait ~1min
- find IP via router's dhcp client table (alternatively, scan with `nmap` for closed but unfiltered port 22)
- blindly press enter a couple of times, then `sudo systemctl start sshd`
- wait a bit, then attempt `ssh nixos@<ip>`

It's supposed to be a headless system ultimately, so not too bothersome, but typing thinks blindly when you're unfamiliar with nix can leave one dumbfounded (I ventured the default auto-login user was root so missed `sudo`)

**Comment by lloeki** [comment] 2020-05-16 11:30
Has anyone tried kernel flags such as `nomodeset` to rule out any kms framebuffer issue? (still getting the hang of NixOS so can't try this just yet).

**Comment by lloeki** [comment] 2020-05-17 11:24
Tried `nomodeset`, unsuccessfully.

**Comment by matthewbauer** [comment] 2020-05-17 20:11
@lloeki If Linux 5.x isn't important, you might want to try Nixiosk:

https://github.com/matthewbauer/nixiosk/

It should at least get you ssh + mdns so you can ssh via `root@<hostname>`.

**Comment by lloeki** [comment] 2020-05-17 20:48
Thanks, but I did manage to get in and setup what I needed, as I can live with headless and 5.x.

I did go down to 4.19 ultimately though, but that was because `wlan0` wasn't showing up *at all* as an interface and wanted to check if it did on 4.19 (and it does show up there, but wifi performance is bad with dropped packets and wildly varying latencies, which is something I had on ArchLinux a long time ago but not on RetroPie 4.5.1 where it was perfect).

**Comment by lafka** [comment] 2020-06-16 15:09
Can confirm no HDMI display RPI 3B+ with [build 122365321](https://hydra.nixos.org/build/122365321).

Booting up with serial console (first setting `console=ttyS1,115200n8` in `/boot/extlinux/extlinux.conf`)
Setting up minimal configuration and reverting to 4.19 kernel works:

```
{ config, pkgs, lib, ... }:
{
  boot.loader.grub.enable = false;
  boot.loader.generic-extlinux-compatible.enable = true;
 
  boot.kernelPackages = pkgs.linuxPackages_4_19;
  
  boot.kernelParams = ["cma=32M"];
    
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/NIXOS_SD";
      fsType = "ext4";
    };
  };
}
```
Going back to latest kernel does not have any effect. Connected to VGA on monitor, HDMI adapter used on rpi.

One question, what power supply do you use? I'm using a 2.4A supply but still getting a few "undervoltage" messages on console, maybe related?

**Comment by mebubo** [comment] 2020-06-28 00:20
I still reliably get the display output if I cool the board down to below ~18°C prior to boot, and no output if it's warmer %)

I compared dmesg in the 2 cases and there are multiple entries like this in the failure case but not in the success case:

```
bcm2835-power bcm2835-power: Timeout waiting for grafx power OK
```

It seems like it has to do with the upstream switching from a firmware-based driver to bcm2835-power in 5.1: https://github.com/raspberrypi/linux/issues/3046

The revert https://github.com/raspberrypi/linux/issues/3046#issuecomment-607982630 seems to be applied upstream in 5.8-rc1.

**Comment by lloeki** [comment] 2020-06-28 06:43
Looks like there could be a workaround

> arm_freq=1200, no cpufreq => no timeout

https://github.com/raspberrypi/linux/issues/3046#issuecomment-526678860

**Comment by lloeki** [comment] 2020-06-28 07:41
I tried a shot [at this one](https://github.com/raspberrypi/linux/issues/3046#issuecomment-549117016) and HDMI spawned to life.

Use at your own risk.

```
curl -O https://github.com/raspberrypi/linux/files/3801365/bcm2837-rpi-3-b.dtb.zip
echo '660e6bc6bb652257f969db60d048670a34456ebf78ba4d76ed6c6daeacea8614  bcm2837-rpi-3-b.dtb.zip' | sha256sum --check
unzip bcm2837-rpi-3-b.dtb.zip
cat /boot/extlinux/extlinux.conf | grep -A5 'LABEL nixos-default' | grep FDTDIR | awk '{ print $2 }'
ls /boot/extlinux/$(cat /boot/extlinux/extlinux.conf | grep -A5 'LABEL nixos-default' | grep FDTDIR | awk '{ print $2 }')/broadcom/bcm2837-rpi-3-b.dtb
cat bcm2837-rpi-3-b.dtb > /boot/extlinux/$(cat /boot/extlinux/extlinux.conf | grep -A5 'LABEL nixos-default' | grep FDTDIR | awk '{ print $2 }')/broadcom/bcm2837-rpi-3-b.dtb 
```

**Comment by lloeki** [comment] 2020-06-28 09:43
> Unfortunately, at the moment 5.7 completely hangs at boot on my 3B+ (green LED stops flashing) (but for now I only tried 5.7.4, the latest in nixos-unstable).

I have the same problem. Rolled back to 5.6.13.

**Comment by deifactor** [comment] 2020-07-02 21:53
Another datapoint: I was able to get my 3B+ to boot fine using 5.4.50 (by setting `boot.kernelPackages = pkgs.linuxPackages_5_4`). Using 5.7 didn't work, though I'm not sure if it was a complete hang or just the 'boots but HDMI breaks' issue.

**Comment by renanqts** [comment] 2020-07-12 08:57
Same issue here.

**Comment by benley** [comment] 2020-07-12 18:45
Here as well: 5.7.x wouldn't boot, but 5.4.x and 5.6.x are both working.  In my case it was _not_ a "boots but breaks HDMI" issue as the system in question is headless.

**Comment by ajsalminen** [comment] 2020-07-20 22:43
My Model 3B also seemed to have this issue with 5.7 but not with 5.6.

**Comment by tobiasBora** [comment] 2020-09-03 04:00
Hum, I can confirm like benley that the issue is not just a "boots but breaks HDMI" in my case: after some upgrade, it appears that I also can't boot anymore (since I don't reboot often, it quite surprising to lose complete ssh access). It hangs at "Starting kernel" while it starts the kernel 5.7.18, even if I configure in `/config.txt`:

    enable_uart=1
    force_turbo=1
 
and if I add in the console parameters `console=ttyS1,115200n8`. I installed this system quite a while ago, in 2018, and I was not having any issue so far. However, the kernel 5.6 is still booting fine. Will try to reinstall the new image to see if it helps.

**Comment by tobiasBora** [comment] 2020-09-04 02:04
The new image still have an issue with kernel 5.7, so maybe it is a different bug. I filled a new bug https://github.com/NixOS/nixpkgs/issues/97064.

**Comment by n8henrie** [comment] 2021-05-26 23:12
I'm fairly new to NixOS, so sorry if my `+1` doesn't have all of the important details, but my previously working Raspberry Pi 3 on NixOS now won't get past `Starting kernel ...`, and this seems to be the top relevant Google result ¯\\_(ツ)_/¯

I can get it to boot if I use the boot menu to go back a few iterations (config number 4 works, from sometime in May 2020).

The working kernel is `5.6.14`.

I don't think the others are suffering from just an HDMI issue, since SSH never comes up either, though I'm sure I could be wrong.

I'm not sure if this has helpful info on the non-booting versions or not:

```console
$ ls -lh /boot/nixos/
total 137M
-r--r--r--  1 root root 7.4M May 23  2020 54i0xpp1s0llkd9q9srfsfvc74jfv5mv-initrd-linux-5.4.42-initrd
-r--r--r--  1 root root 7.4M May 23  2020 bs488cw4q794za7hmzds5dxnm5n1814r-initrd-linux-5.6.14-initrd
-r--r--r--  1 root root 7.8M May 21  2020 cj229kfgx5gvsj04ywfnvyd4k7cm2m61-initrd-linux-5.4.42-initrd
dr-xr-xr-x 28 root root 4.0K May 21  2020 j2lsn0dw9ag254cdzswd8aqqk2z7g5ga-linux-5.4.42-dtbs
-r--r--r--  1 root root  35M May 21  2020 j2lsn0dw9ag254cdzswd8aqqk2z7g5ga-linux-5.4.42-Image
dr-xr-xr-x 29 root root 4.0K May 23 09:17 jdpxscl5rx8nzhs2v0m61mngangljsbv-linux-5.7.19-dtbs
-r--r--r--  1 root root  38M May 23 09:16 jdpxscl5rx8nzhs2v0m61mngangljsbv-linux-5.7.19-Image
dr-xr-xr-x 29 root root 4.0K May 23  2020 k3w7xwqmyxykpn5cib0xfr1883mgma54-linux-5.6.14-dtbs
-r--r--r--  1 root root  36M May 23  2020 k3w7xwqmyxykpn5cib0xfr1883mgma54-linux-5.6.14-Image
-r--r--r--  1 root root 7.4M May 23 09:16 zc186l88irywwnzp6a0nwbs7yngb1nr0-initrd-linux-5.7.19-initrd
```

I hope this is helpful!

**Comment by tobiasBora** [comment] 2021-05-27 09:54
I think you are hitting this issue: the kernels seems to be too big for uboot with default configuration. Several workarounds are presented, the simplest is maybe to pin an older kernel, for instance via:

```
boot.kernelPackages = pkgs.linuxPackages_rpi3;
```

A patch is also given, and a PR https://github.com/NixOS/nixpkgs/pull/108975  has been merged to support bigger kernels, but it only applies to new installs I think. To apply it to new install, again, several methods are proposed, like:

> For reference: If you are experiencing this issue on an existing installation, try to replace the files in your firmware partition with those from a recent sdImage.

**Comment by n8henrie** [comment] 2021-05-28 13:41
Thanks for your response and detailed instructions!

I changed the kernel to the `_rpi3` as you noted, and after a `nixos-rebuild switch` I get boot text and then a blank screen and no SSH access (ethernet, never shows up on my network, so I don't think it's just HDMI). ¯\\_(ツ)_/¯

Maybe I'll try to find a new SD card image and try that method.

**Comment by n8henrie** [comment] 2021-05-31 22:32
I used `sudo rsync -av --delete` to copy over the sdimage's partition 1 (firmware) files from a recent image (`nixos-sd-image-20.09.4211.ad3dcab698f-aarch64-linux.img.zst`) to partition 1 of my sd card -- no luck. Next I tried copying over the whole partition 1 with `dd` (both were 30M), still no luck.

I am still using `kernelPackages = pkgs.linuxPackages_rpi3;`.

On the uboot screen, if I go a few versions back I can get it to boot:

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 5.6.14, NixOS, 20.03.1950.48723f48ab9 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.3328.6d1a044fc9f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

After `sudo nixos-rebuild switch` and a reboot, I am still stuck at `Starting kernel...`. No SSH comes up, never joins network (ethernet), unplugging and replugging HDMI and keyboard have no effect.

**Comment by n8henrie** [comment] 2021-06-08 13:59
As a quick update, I never got this working. Eventually I gave up and reinstalled from scratch with 21.05. Seems to be working now.

**Comment by Mic92** [comment] 2021-06-26 12:09
I followed now https://discourse.nixos.org/t/cant-boot-into-new-configuration-after-nix-rebuild-raspberry-pi3-b/7812/3?u=mic92 and used `uboot`, which seemed to work with the latest kernel as well. In my case the rpi3 kernel crashed each time after copying 15GB from my hdd to my backup drive.

**Comment by Gerschtli** [comment] 2021-11-03 18:14
There is an easier than reinstalling everything: The problem is just out-of-date firmware.

Currently, the firmware is only written on sd-image creation. If you want to have the latest updates, you need to update it manually. To get the firmware files, I built a small nix-file.

`build-firmware.nix`:
```nix
{ config, pkgs, ... }:

{
  imports = [
    <nixpkgs/nixos/modules/installer/sd-card/sd-image-aarch64.nix>
  ];

  system.build.firmware = pkgs.runCommand "firmware" {} ''
    mkdir firmware $out

    ${config.sdImage.populateFirmwareCommands}

    cp -r firmware/* $out
  '';
}
```

Steps to update firmware:
```sh
# mount firmware partition
mount /dev/disk/by-label/FIRMWARE /mnt

# backup old firmware
mkdir firmware.bak
cp /mnt/* firmware.bak

# build latest firmware
nix-build "<nixpkgs/nixos>" -I nixos-config=path/to/build-firmware.nix -A config.system.build.firmware

# install firmware
rm /mnt/*
cp result/* /mnt

# unmount and reboot
umount /mnt
reboot
```

**Comment by samueldr** [comment] 2021-11-03 20:07
@Gerschtli good writeup of the steps to update the firmware partition for Raspberry Pi devices!

Though this solution is about issues with all Raspberry Pi devices with 5.**14**, not 3B+ only with 5.**4** :).

**Comment by samueldr** [comment] 2021-11-03 20:11
(Closing this issue as it was solved already, and now even better solved.)

**Closed by samueldr** 2021-11-03 20:11 UTC
Labels: 0.kind: bug, 6.topic: nixos, 6.topic: hardware
