### ISSUE TITLE
Nextcloud won't install

### ISSUE THREAD

**Issue by Alexnortung** [NixOS/nixpkgs#195415] opened 2022-10-10 20:55 UTC
### Describe the bug
Trying to use the NixOS Nextcloud service doesn't seem to work when installing from scratch.

EDIT: I guess I should also post some logs:

```
warning: the following units failed: nextcloud-cron.service, nextcloud-setup.service

× nextcloud-cron.service
     Loaded: loaded (/etc/systemd/system/nextcloud-cron.service; linked; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2022-10-10 22:39:25 CEST; 1s ago
TriggeredBy: ● nextcloud-cron.timer
    Process: 60404 ExecStart=/nix/store/8h70lra167w42k018qvahrd5vjcxz2gd-php-with-extensions-8.0.22/bin/php -f /nix/store/ylblvy03xmq1nrp6w7nnlhw3d6i2lbkd-nextcloud-24.0.4/cron.php (code=exited, status=1/FAILURE)
   Main PID: 60404 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
        CPU: 208ms

Oct 10 22:39:25 end Nextcloud[60404]: {"reqId":"nQwm8DeH4EoLGQ0VjEgz","level":3,"time":"2022-10-10T20:39:25+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"{\"Exception\":\"Exception\",\"Message\":\"Not installed\",\"Code\":0,\"Trace\":[{\"file\":\"/nix/store/ylblvy03xmq1nrp6w7nnlhw3d6i2lbkd-nextcloud-24.0.4/lib/base.php\",\"line\":663,\"function\":\"checkInstalled\",\"class\":\"OC\",\"type\":\"::\",\"args\":[{\"__class__\":\"OC\\\\SystemConfig\"}]},{\"file\":\"/nix/store/ylblvy03xmq1nrp6w7nnlhw3d6i2lbkd-nextcloud-24.0.4/lib/base.php\",\"line\":1104,\"function\":\"init\",\"class\":\"OC\",\"type\":\"::\",\"args\":[]},{\"file\":\"/nix/store/ylblvy03xmq1nrp6w7nnlhw3d6i2lbkd-nextcloud-24.0.4/cron.php\",\"line\":43,\"args\":[\"/nix/store/ylblvy03xmq1nrp6w7nnlhw3d6i2lbkd-nextcloud-24.0.4/lib/base.php\"],\"function\":\"require_once\"}],\"File\":\"/nix/store/ylblvy03xmq1nrp6w7nnlhw3d6i2lbkd-nextcloud-24.0.4/lib/base.php\",\"Line\":282,\"CustomMessage\":\"--\"}","userAgent":"--","version":"24.0.4.1"}
Oct 10 22:39:25 end php[60404]: Exception: Not installed in /nix/store/ylblvy03xmq1nrp6w7nnlhw3d6i2lbkd-nextcloud-24.0.4/lib/base.php:282
Oct 10 22:39:25 end php[60404]: Stack trace:
Oct 10 22:39:25 end php[60404]: #0 /nix/store/ylblvy03xmq1nrp6w7nnlhw3d6i2lbkd-nextcloud-24.0.4/lib/base.php(663): OC::checkInstalled(Object(OC\SystemConfig))
Oct 10 22:39:25 end php[60404]: #1 /nix/store/ylblvy03xmq1nrp6w7nnlhw3d6i2lbkd-nextcloud-24.0.4/lib/base.php(1104): OC::init()
Oct 10 22:39:25 end php[60404]: #2 /nix/store/ylblvy03xmq1nrp6w7nnlhw3d6i2lbkd-nextcloud-24.0.4/cron.php(43): require_once('/nix/store/ylbl...')
Oct 10 22:39:25 end php[60404]: #3 {main}
Oct 10 22:39:25 end systemd[1]: nextcloud-cron.service: Main process exited, code=exited, status=1/FAILURE
Oct 10 22:39:25 end systemd[1]: nextcloud-cron.service: Failed with result 'exit-code'.
Oct 10 22:39:25 end systemd[1]: Failed to start nextcloud-cron.service.

× nextcloud-setup.service
     Loaded: loaded (/etc/systemd/system/nextcloud-setup.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2022-10-10 22:39:25 CEST; 1s ago
    Process: 60381 ExecStart=/nix/store/c1ws8a9wps8j5q0r8rcj8v90ncl1xis4-unit-script-nextcloud-setup-start/bin/nextcloud-setup-start (code=exited, status=1/FAILURE)
   Main PID: 60381 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
        CPU: 294ms

Oct 10 22:39:25 end systemd[1]: Starting nextcloud-setup.service...
Oct 10 22:39:25 end nextcloud-setup-start[60403]: Nextcloud is not installed - only a limited number of commands are available
Oct 10 22:39:25 end nextcloud-setup-start[60403]:
Oct 10 22:39:25 end nextcloud-setup-start[60403]:   Command "upgrade" is not defined.
Oct 10 22:39:25 end nextcloud-setup-start[60403]:
Oct 10 22:39:25 end systemd[1]: nextcloud-setup.service: Main process exited, code=exited, status=1/FAILURE
Oct 10 22:39:25 end systemd[1]: nextcloud-setup.service: Failed with result 'exit-code'.
Oct 10 22:39:25 end systemd[1]: Failed to start nextcloud-setup.service.
```

I guess these are the most relevant ones

### Steps To Reproduce
Use the following config for nextcloud

```nix
{
  services.nextcloud = {
    enable = true;
    https = true;
    hostName = url;
    config = {
      adminpassFile = config.age.secrets.nextcloud-admin-pass.path;
      dbtype = "sqlite";
      # dbtype = "mysql";
      # dbport = 3306;
    };
  };
}
```

### Expected behavior
I expected nextcloud to run normally

### Additional context
I have installed agenix to handle the adminpassFile.
I am also using deply.rs to try and deploy nextcloud to my server.

nginx is also running on the server and uses port 80. I have not set up a virtual host for nextcloud yet.

### Notify maintainers

@ma27 @fpletz @globin @bachp @schneefux

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Server:

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.63, NixOS, 22.05 (Quokka), 22.05.20220901.b82ccaf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Local machine:

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.63, NixOS, 22.05 (Quokka), 22.05.20220901.b82ccaf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by kfiz** [comment] 2022-11-15 11:55
Seeing this as well. 
Would assume that this line is causing the `Command "upgrade" is not defined.` error:
https://github.com/NixOS/nixpkgs/blob/8c8f38c1367fa90ff87d28a44b82fd8e59dc088d/nixos/modules/services/web-apps/nextcloud.nix#L892

Not sure how to best debug this.

**Comment by kfiz** [comment] 2022-11-15 22:46
Ok. So this is a duplicate of #111175. There is also a comment on this issue in the official manual.

**Comment by teto** [comment] 2023-07-04 12:30
original ticket looks fixed thus closing, feel free to reopen if not the case

**Closed by teto** 2023-07-04 12:30 UTC
Labels: 0.kind: bug, 6.topic: nixos
