### ISSUE TITLE
 clang-tools-13 doesn't point to a clangd binary

### ISSUE THREAD

**Issue by lednakashim** [NixOS/nixpkgs#146977] opened 2021-11-22 09:08 UTC
### Describe the bug

clangd is a popular language server for C++ codes and provides linting for C++ programs compiled with a variety of compilers (such as clang,gcc,icc).

In the installed package the last line of clangd points to a binary that isn't deployed?

exec -a "$0" /nix/store/1f8vwdir1p2z48ppqm6zcm29y73r2q1x-clang-13.0.0/bin/$(basename $0) "$@"

The file indeed doesn't exist, is it actually installed as part of clang-tools? How do we get it?

### Steps To Reproduce
Install clang-tools (13)

`nix-env -iA nixpkgs.clang-tools`

run clangd

`clangd`

get

`/home/foo/.nix-profile/bin/clangd: line 27: /nix/store/1f8vwdir1p2z48ppqm6zcm29y73r2q1x-clang-13.0.0/bin/clangd: No such file or directory`

### Expected behavior
clangd should run, just like in the previous version 12 package

### Notify maintainers

Andreas Herrmann <andreash87@gmx.ch>

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-1098-gcp, Ubuntu, 16.04.7 LTS (Xenial Xerus)`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.3.17`
 - channels(root): `"nixpkgs-21.03pre248787.7ad5e816fab"`
 - channels(mkandel): `"nixos-21.11pre332033.715f6341195, nixpkgs-21.11pre332842.8afc4e54366"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by bjornfor** [comment] 2021-11-22 10:45
Duplicate of https://github.com/NixOS/nixpkgs/issues/146659.

**Closed by bjornfor** 2021-11-22 10:45 UTC
Labels: 0.kind: bug

**Comment by bjornfor** [comment] 2021-11-22 10:46
A fix has already been merged, but it takes some time for it to be available in the channel.

**Comment by lednakashim** [comment] 2021-12-03 21:09
@bjornfor  So I just tried `nix-env -iA nixpkgs.clang-tools` and I still get the reported issue. Shall we re-open the ticket? Any idea when its supposed to appear?

**Comment by bjornfor** [comment] 2021-12-03 21:24
nixpkgs-unstable has been slow to update it seems. But it's on its way: https://nixpk.gs/pr-tracker.html?pr=146814

And for nixos-21.11: https://nixpk.gs/pr-tracker.html?pr=148232
