### ISSUE TITLE
kdenlive: crash at start up

### ISSUE THREAD

**Issue by ASHGOLDOFFICIAL** [NixOS/nixpkgs#318770] opened 2024-06-10 11:22 UTC
### Describe the bug
For months now, I haven't been able to open `kdenlive` provided by `kdePackages.kdenlive`. `libsForQt5.kdenlive` works as expected.

### Steps To Reproduce
1. Run `kdenlive` in the terminal
2. Shows loading screen.
3. Suggests to reset configuration.
4. Crashes.

### Additional context
Desktop environment isn't KDE Plasma (if that matters), but GNOME. Crashes with error:
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
Qt: Session management error: Could not open network socket
Could not detect package type, probably default? App dir is "/nix/store/s12zlf8zrvx8mfci6c7f04xd84dl5d0m-kdenlive-24.05.0/bin"
 = = = =
GOT Deleted file:  "/home/ashgoldofficial/.config/kdenliverc"
QPaintDevice: Cannot destroy paint device that is being painted
```

### Notify maintainers
(couldn't find any in [here](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/kde/gear/kdenlive/default.nix))

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.3, NixOS, 24.11 (Vicuña), 24.11.20240531.57610d2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/5jgh89kgmrb687c254wxdac4cj5hqjw8-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-06-29 07:13
this is how I'd get the list of maintainers:

```
$ nix eval --impure --expr 'with import <nixpkgs> {}; map (builtins.getAttr "github") kdePackages.kdenlive.meta.maintainers'
[ "ilya-fedin" "K900" "LunNova" "mjm" "NickCao" "SuperSandro2000" "ttuegel" ]
```

**Comment by turion** [comment] 2024-07-01 09:31
I can't reproduce exactly. How do you install and run `kdenlive` exactly?

**Comment by SuperSandro2000** [comment] 2024-08-16 08:55
Closing because author didn't answer and we fixed kdenlive issues in the past weeks.

**Closed by SuperSandro2000** 2024-08-16 08:55 UTC
Labels: 0.kind: bug

**Comment by ASHGOLDOFFICIAL** [comment] 2024-08-17 06:15
Sorry, I somehow missed all the questions. But I've just tested and can confirm that the problem is solved.
