### ISSUE TITLE
Build failure: msmtp

### ISSUE THREAD

**Issue by mhwombat** [NixOS/nixpkgs#268492] opened 2023-11-19 13:00 UTC
### Steps To Reproduce

1. Add `msmtp` to `environment.systemPackages`.
2. `sudo nixos-rebuild switch --upgrade`

### Build log

Full log is [here](https://gist.github.com/mhwombat/cb8181cf8f29bfd62821689124334388), but I think the relevant part is:

```
Processing ./pip-20.3.4-py2.py3-none-any.whl
Installing collected packages: pip
  File "/nix/store/qzdnf36li7zrnr95dhpc1w1i61ifw4s6-catch_conflicts.py", line 16
    f"{dist._normalized_name} {dist.version} ({dist._path})"
                                                           ^
SyntaxError: invalid syntax
error: builder for '/nix/store/v76sg0q8rhlzkgwwq1rp545iydlnzmc1-python2.7-wheel-0.37.1.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/04h3ndcbb0mw9vl22nfmx1yaqn2qbz5r-setuptools-setup-hook.drv' failed to build
error: 1 dependencies of derivation '/nix/store/c5wqjjyk8f3awa1fbxz51v9aq1jcj9fl-resholve-0.9.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kzdfs5klslkh3yaqw39iya66x41cxf2f-msmtp-scripts-1.8.22.drv' failed to build
error: 1 dependencies of derivation '/nix/store/spi8m78m5swi7cwnzl131pzhv2gs16gs-msmtp-1.8.22.drv' failed to build
error: 1 dependencies of derivation '/nix/store/837bk2if99k8nxj51gqxg0h21db9p94q-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fgcyv2rdg69ikmnankzxnz0hk2x02rk8-nixos-system-wombat11k-23.11pre549786.c757e9bd77b1.drv' failed to build
```

### Additional context

None

### Notify maintainers

@peterhoeg 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
✦ ❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.62, NixOS, 23.11 (Tapir), 23.11pre549786.c757e9bd77b1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by amesgen** [comment] 2023-11-19 22:21
Duplicate of #268297

**Closed** 2023-11-20 00:44 UTC
Labels: 0.kind: build failure
