### ISSUE TITLE
Graphics disturbances and tearing in Firefox, OBS, and others

### ISSUE THREAD

**Issue by juselius** [NixOS/nixpkgs#85663] opened 2020-04-21 09:20 UTC
**Describe the bug**

About two weeks ago, after an update of my Lenovo ThinkCentre 920q,  the graphics in Firefox started misbehaving badly. The graphics  is sluggish, and there is a kind of tearing effect during transitions (hover, tabs, scroll, etc., see videos below) . I was too stressed with work at the time it first occurred, and didn't have time to investigate. 

The problem does not affect all programs. All Chrome/Chromium/Electron apps are working fine. But at least the following apps are affected:

* Firefox
* OBS Studio (only menus!)
* Flameshot
* Simplescreenrecorder
* Remmina

Programs that work include:

* Google Chrome
* Krita
* Bluetooth and NetworkManager applets
* VS Code 
* Electron (wavebox, signal, keybase, slack)

By now I have tried all sorts of things, like disabling OpenGL, tweaking MESA drivers, tweaking the Intel graphics settings, upgrading to kernel 5.6, all to no avail.  At one point I thought it might be a hardware problem, and I updated all firmware. No change. Then I did a `nixos-update switch --upgrade` on my Lenovo Carbon X1 7th Gen, and got the same problem on that unit. It's clearly a software problem, most likely in some underlying library. I have tried to find common factors between apps that work and apps that don't using `ldd`, but I have not found the offending lib.

**To Reproduce**

Install NixOS unstable on rececent Lenovo hardware, perhaps?

**Expected behavior**

Clear and crisp graphics, without tearing.

**Screenshots**

Since the problem only occurs in transitions, I have added to movies. I'm sorry for the poor quality, I had to film the screen with my phone, since the screen captures came out perfect without the effect.

https://www.dropbox.com/s/3xs197vmq64jf7g/2020-04-21%2009.02.50.mov?dl=0
https://www.dropbox.com/s/9l34df4cknc6ta9/2020-04-21%2008.59.52.mov?dl=0

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.33, NixOS, 20.09pre222138.b3c3a0bd183 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.09pre222138.b3c3a0bd183"`
 - channels(jonas): `"home-manager, nixos-20.09pre222138.b3c3a0bd183"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by chillja** [comment] 2020-04-23 12:57
I second this, tearing in Firefox on nixos-20.03 after upgrading from 19.09 on a Lenovo device.

**Comment by andrewrk** [comment] 2020-04-24 23:16
I have the same issue as OP, confirmed the video matches my experience, and I can offer the following extra information:

 * It happened when I upgraded from  20.09pre221322.8686922e68d to 20.09pre222244.22a3bf9fb9e
 * **Reverting** back to 20.09pre221322.8686922e68d **does not make the problem go away**

**Comment by andrewrk** [comment] 2020-04-24 23:35
This is a pretty disturbing problem, and I would be interested if anyone knows any workarounds.

**Comment by andrewrk** [comment] 2020-04-26 17:58
OK I have solved the problem by switching to the 20.03 stable channel. I'm not sure why the revert I mentioned earlier did not solve the problem, but perhaps I made a mistake. With `20.03.1574.4b6bfecc0bd (Markhor)` I do not experience the problem.

**Comment by juselius** [comment] 2020-04-26 19:45
I reverted to nixos-20.03, and the problems disappeared. Now we just have to wait for the bug to creep into stable, and we are screwed yet again ;)

**Comment by chillja** [comment] 2020-05-16 13:14
Hm, I cannot confirm. After I rolled back to a previous (19.09) state, I first upgraded to stable 20.03 today (which currently is `nixos-20.03.1879.91cdcf31357`), and then upgraded to the aforementioned `20.03.1574.4b6bfecc0bd`, both are tearing if firefox is in fullscreen (on sway).

**Comment by gnidorah** [comment] 2020-05-26 04:50
Same effect as on video on laptop with Intel HD 620, seen in Telegram program. Temporary fixed by `services.picom.enable = true;`

**Comment by gnidorah** [comment] 2020-06-29 17:56
Seems to be this issue https://gitlab.freedesktop.org/mesa/mesa/-/issues/2721
Should be fixed in nixos-unstable thanks to https://github.com/NixOS/nixpkgs/commit/04b1ed0440efc753f35488fe07a12fb7f8070d9a#diff-3b1d4d1d207d109c5b8c02b059b5e02c
Anyone to confirm?

**Comment by gnidorah** [comment] 2020-07-11 22:26
Not reproducable anymore

**Closed by gnidorah** 2020-07-11 22:26 UTC
Labels: 0.kind: bug
