### ISSUE TITLE
BashOnWindows needs patch for lndir

### ISSUE THREAD

**Issue by cstrahan** [NixOS/nixpkgs#27808] opened 2017-07-31 19:03 UTC
As @pikajude found in https://github.com/Microsoft/BashOnWindows/issues/2229, BashOnWindows will need a patch for xorg's `lndir` in order for `symlinkJoin` to work there. As noted in that issue, a strong argument can be made that this is a bug in `lndir`. I think we (by which I probably mean "I", if I can find the time soon) should send a patch upstream for the sake of our Windows users, so I'm tracking that objective here in this issue.

**Comment by pierrebeaucamp** [comment] 2017-09-01 20:10
In case it helps, there is an implementation of `lndir` in X11 using `/bin/sh`:
https://opensource.apple.com/source/X11/X11-0.46.4/lndir.sh

**Comment by Artturin** [comment] 2021-12-05 16:22
dupe of https://github.com/NixOS/nixpkgs/issues/26506

**Closed** 2021-12-05 16:23 UTC
Labels: 6.topic: windows
