### ISSUE TITLE
Build failure: nose-1.3.7 not supported for interpreter python3.12

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#325754] opened 2024-07-09 06:10 UTC
### Describe the bug
Using NixOS unstable I get now:

error: nose-1.3.7 not supported for interpreter python3.12

### Steps To Reproduce
1. Use NixOS unstable
2. Try to use nose package
3. get error

### Notify maintainers
@afh

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.11 (Vicuna), 24.11pre646099.00d80d13810d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by surfaceflinger** [comment] 2024-07-09 06:17
kinda related: https://github.com/NixOS/nixpkgs/issues/311054

**Comment by liff** [comment] 2024-07-09 09:06
Duplicate of #325657.

**Closed** 2024-07-09 12:43 UTC
Labels: 0.kind: bug

**Comment by pjlover95** [comment] 2024-07-10 08:23
@dotlambda One package that triggered this for me: tremc

**Comment by sjau** [comment] 2024-07-12 07:49
> @sjau You didn't state which package, that uses nose, fails to build. Nose won't become compatible with Python 3.12.

For me it's flexget
