### ISSUE TITLE
makeOverridable forces its original attrset rendering assert+override unusable

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#53487] opened 2019-01-06 09:36 UTC
```nix
# test.nix
with import <nixpkgs> {};

let
  f = { dep ? null, feature ? true }:
    assert feature1-> dep != null;
    hello;
in
  lib.makeOverridable f { }
```

```
› nix eval '(import ./test.nix).override { feature = false; }'
error: assertion failed at /private/tmp/test.nix:6:5
```

`makeOverridable` is not being lazy enough and [forces](https://github.com/NixOS/nixpkgs/blob/be1c03ddaf867e9a58499cd790d5cd72cffc6fca/lib/customisation.nix#L72) a call to the function with the original set of arguments before adding the `.override` attr. This behaviour renders `assert feature -> dep != null` (which is a common pattern in `nixpkgs`) somewhat useless: it is impossible to disable a feature whose dependency is missing with an `.override` as the original assert will trigger in any case.

I discovered this trying to install `lighttpd` (which does `assert enableWebDAV -> libuuid != null`) on darwin, but it won’t let me unset `enableWebDAV` or even override `libuuid` with some implementation.

AFAICT, @edolstra’s original `makeOverridable` made `.override` available before forcing anything, which is what I would expect, but this was changed in 9e4202d273e05c4585466385bc383581ac74d142 (@urkud) so that it can work on functions.

_P.S. To be honest, I am not sure that my analysis is correct, as this change is 8.5 (😮) years old and, apparently, no one noticed, which seems unlikely, but 🤷‍♂️. I’m not sure if there is any policy in place that says that all dep+feature asserts should evaluate to `true` by default, but if there is one, then it is probably what helps here, but then the `lighttpd` expression violates it (#40623, @rkoe, @xeji)._

(FYI @shlevy @ElvishJerricco as I saw you work on `makeOverridable`)

**Comment by kirelagin** [comment] 2019-01-06 09:41
Oh well, lighttpd is no supported on Darwin anyway :(.

**Comment by veprbl** [comment] 2019-11-10 21:27
@kirelagin
In your analysis you seem to conclude that the regression has happened in 9e4202d273e05c4585466385bc383581ac74d142. I would argue this is not true. Consider this:
```
nix-repl> ((assert false; 239) // { override = 30; }).override
error: assertion failed at (string):1:3
```
This seems to prove that the `//` is not as lazy as one could think. I guess, it must, at very least, evaluate its first argument to ensure that it is an attrset to begin with.

I tried to tweak the implementation of `makeOverridable` to ignore the original failure. If the problem was just with the evaluation of `builtins.isAttrs ff`, then it would be easy to just wrap it with `builtins.tryEval` and optimistically assume that "if it doesn't evaluate, it's an attrset". But one also needs to wrap the `ff` in `(ff // { override = ...`, which don't know how to do in a satisfactory way.

Another way would be to get rid of the asserts that are now polluting nixpkgs. For example I was always puzzled by these:
https://github.com/NixOS/nixpkgs/blob/84c44d8cafd909105a78bfcf191a0f6c7858c54d/pkgs/misc/ghostscript/default.nix#L9
Is it really a concern that someone will accidentally have this derivation in a context where `cups = null` and that will cause a subtle failure?

The asserts stand in the way of naively evaluating nixpkgs and this complicates a lot of the introspection that can be done. Those few that implement some more sensible constraints can be implemented via `meta.broken` instead.

**Comment by veprbl** [comment] 2019-11-10 21:50
Well, see #36229

**Comment by kirelagin** [comment] 2019-11-11 10:07
@veprbl Hmmm, yes, I think, you are right. `//` needs to force the set of keys, to be able to merge the attrsets 🤔.

**Comment by ElvishJerricco** [comment] 2019-11-12 01:06
Yea, attrsets are strict in the keys, lazy in the values. So it *must* call the function to determine what keys will be present before it can add any keys like `override. I'd recommend closing this issue, @FRidh.

**Closed** 2020-02-11 00:16 UTC

**Comment by veprbl** [comment] 2020-09-30 19:59
Lazy attribute names support discussed here https://github.com/NixOS/nix/issues/4090
