### ISSUE TITLE
bluetuith

### ISSUE THREAD

**Issue by kennethbruskiewicz** [NixOS/nixpkgs#201660] opened 2022-11-17 18:10 UTC
**Project description**

A Bluetooth connection manager via TUI

**Metadata**

* homepage URL: https://golangexample.com/a-tui-based-bluetooth-connection-manager-which-can-interact-with-bluetooth-adapters-and-devices/
* source URL: https://github.com/darkhz/bluetuith
* license: MIT
* platforms: Linux

**Comment by pinn3** [comment] 2022-11-17 20:47
Duplicate of https://github.com/NixOS/nixpkgs/issues/198612

It's already packaged and available in the unstable channel

**Closed** 2022-11-20 12:58 UTC
Labels: 0.kind: packaging request
