### ISSUE TITLE
python3Packages.cherrypy fails to build on 19.03

### ISSUE THREAD

**Issue by adamtulinius** [NixOS/nixpkgs#65333] opened 2019-07-24 13:12 UTC
**Describe the bug**
`python3Packages.cherrypy` fails to build after upgrading to python 3.7.4. Samme issue that was fixed in master already.

**To Reproduce**
```
$ nix-shell -p python3Packages.cherrypy
[...]
-------------------------------------------------------------------------------
TOTAL                                             13375   2909    78%

15 files skipped due to complete coverage.
Coverage XML written to file coverage.xml

=========================== short test summary info ============================
XFAIL cherrypy/test/test_logging.py::test_tracebacks
  failing
XPASS cherrypy/test/test_caching.py::CacheTest::test_antistampede #1536
XPASS cherrypy/test/test_conn.py::LimitedRequestQueueTests::test_queue_full #1535
XPASS cherrypy/test/test_static.py::StaticTest::test_file_stream #1475
SKIPPED [1] /build/CherryPy-18.1.0/cherrypy/test/helper.py:330: skipped (not running HTTPS)...
SKIPPED [4] /build/CherryPy-18.1.0/cherrypy/test/test_session.py:412: memcached not available
SKIPPED [1] cherrypy/test/test_static.py:194: Windows only
 1 failed, 277 passed, 6 skipped, 10 deselected, 1 xfailed, 3 xpassed, 654 warnings in 98.43 seconds
builder for '/nix/store/2rl28qx5plfk0gp5dzs4r8qvvb9c52qd-python3.7-CherryPy-18.1.0.drv' failed with exit code 1
error: build of '/nix/store/2rl28qx5plfk0gp5dzs4r8qvvb9c52qd-python3.7-CherryPy-18.1.0.drv' failed
```

**Expected behavior**
No build failures ;-)

**Additional context**
This PR needs to be backported to 19.03: https://github.com/NixOS/nixpkgs/pull/65217

**Metadata**
```
$ nix run nixpkgs.nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.16, NixOS, 19.03.git.ef4753d (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - nixpkgs: `/etc/nixos/nixpkgs`
```

(on `nixos-19.03` at ef4753de2aa07424fdbb4b691bf612ea2787d909)

**Comment by johanot** [comment] 2019-07-24 13:15
same as #65030

**Comment by johanot** [comment] 2019-07-24 13:47
ping @marsam @FRidh . don't know if you're aware of this?

**Comment by spiderbit** [comment] 2019-08-06 10:27
Have the same Problem

**Comment by spiderbit** [comment] 2019-08-30 17:36
How can that not be backported in over a month?

**Comment by marsam** [comment] 2019-08-30 17:49
@spiderbit sorry, I tried to backport it, but it doesn't apply cleanly. I'm going to try again this weekend

**Comment by spiderbit** [comment] 2019-08-30 18:18
is there some workaround tried something like that:
    (let newpkgs = import (fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz) {};
     in
       newpkgs.flexget)

also with cherrypy but it does not work... some overwrite attribute magic?

**Comment by spiderbit** [comment] 2019-10-11 15:46
Bump here can't rebuild my server since 3 months because of this bug? Really nobody trying to solve this?

**Comment by FRidh** [comment] 2019-10-11 16:23
@spiderbit feel free to open a PR with a fix

**Comment by spiderbit** [comment] 2019-10-11 16:44
if Nixos would use a good programming language like lisp in a eyeblink but this very strange Programming language and project structure makes it very hard to contribute to.

Also I don't understand that 
1. I never got such requests when I reported bugs in other distros
2. I don't get why people update something when it just brakes it, why not keep it intact instead of doing work to create a regression? 
3. As far as I understand everybody that tries to build it will become the same error so how could that go through any quality system?
4. why does nobody just revert the commit that upgraded that package to the defect version?

**Comment by spiderbit** [comment] 2019-10-11 16:52
If somebody guarantees that if I find the commit that introduced that bug and revert it and send that as PR it get's accepted I do it.

**Comment by spiderbit** [comment] 2019-10-11 17:10
Yes 19.09 works or at least the rebuild works. I don't know if that is good enough to close that bug and how well 19.03 is still supported?

**Comment by jonringer** [comment] 2019-10-20 18:22
builds on master and 19.09, I'm in favor of closing

@FRidh thoughts?

**Comment by spiderbit** [comment] 2019-10-21 00:41
it's ok with me but I don't know how nixos handles their stable branches when do you stop "supporting" stable branches after the next is out?

**Comment by jonringer** [comment] 2019-10-21 00:46
You would have to ask the release managers, but seeing as NixOS is largely volunteer driven, I wouldn't expect too long

**Closed** 2019-10-21 07:28 UTC
Labels: 0.kind: regression, 6.topic: python, 9.needs: port to stable
