### ISSUE TITLE
chromium.enableWideVine does not build

### ISSUE THREAD

**Issue by moretea** [NixOS/nixpkgs#26299] opened 2017-06-01 14:23 UTC
## Issue description

When setting `chromium.enableWideVine = true` in `~/.nixpkgs/config.nix`,

### Steps to reproduce
1. Set `chromium.enableWideVine = true` in `~/.nixpkgs/config.nix`,
2. `nix-env -u chromium`  

Output log:
```
[maarten@maarten-laptop:~]$ nix-env -i chromium
warning: name collision in input Nix expressions, skipping ‘/home/maarten/.nix-defexpr/channels_root/nixos’
replacing old ‘chromium-58.0.3029.110’
installing ‘chromium-58.0.3029.110’
these derivations will be built:
  /nix/store/2wnyw84bgi9fi24yw3djnf7vxbb6j8ma-chromium-58.0.3029.110.drv
  /nix/store/dcp02yxms8y02yz8wrb58ypvq8sf0253-chromium-binary-plugin-widevine.drv
  /nix/store/dvpfi6j90advgvwkkma5qdixqw22b008-chromium-58.0.3029.110.drv
building path(s) ‘/nix/store/hycrmcxqayl6rdka8qzhhkppglnzyghg-chromium-58.0.3029.110-sandbox’, ‘/nix/store/iwj7apjzn4ibh8hmk5m6gx6mpcx246y9-chromium-58.0.3029.110’
building path(s) ‘/nix/store/59wp59dc5fsawv8bfmibb9wcwmbhd13l-chromium-binary-plugin-widevine’
unpacking sources
unpacking source archive /nix/store/sjkrivkdyfxh8l8vr8vqij39sc93kwzz-google-chrome-stable_58.0.3029.110-1_amd64.deb
unpacking sources
unpacking source archive /nix/store/3wjzmkl1gh8417alzc4w3nl9yq2dwflr-chromium-58.0.3029.110.tar.xz
source root is plugins
setting SOURCE_DATE_EPOCH to timestamp 1494304666 of file plugins/libwidevinecdmadapter.so
patching sources
installing
install: creating directory '/nix/store/59wp59dc5fsawv8bfmibb9wcwmbhd13l-chromium-binary-plugin-widevine'
install: creating directory '/nix/store/59wp59dc5fsawv8bfmibb9wcwmbhd13l-chromium-binary-plugin-widevine/lib'
'libwidevinecdm.so' -> '/nix/store/59wp59dc5fsawv8bfmibb9wcwmbhd13l-chromium-binary-plugin-widevine/lib/libwidevinecdm.so'
'libwidevinecdmadapter.so' -> '/nix/store/59wp59dc5fsawv8bfmibb9wcwmbhd13l-chromium-binary-plugin-widevine/lib/libwidevinecdmadapter.so'
running tests
	libglib-2.0.so.0 => not found
	libnss3.so => not found
	libnssutil3.so => not found
	libnspr4.so => not found
	libglib-2.0.so.0 => not found
	libnss3.so => not found
	libnssutil3.so => not found
	libnspr4.so => not found
builder for ‘/nix/store/dcp02yxms8y02yz8wrb58ypvq8sf0253-chromium-binary-plugin-widevine.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/dvpfi6j90advgvwkkma5qdixqw22b008-chromium-58.0.3029.110.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/dvpfi6j90advgvwkkma5qdixqw22b008-chromium-58.0.3029.110.drv’ failed
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
```
17.09pre106916.c5badb123a (Hummingbird)
```

* Nix version: (run `nix-env --version`)
```
nix-env (Nix) 1.11.9
```

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"17.09pre106916.c5badb123a"

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
```
[maarten@maarten-laptop:~]$ grep build-use-sandbox /etc/nix/nix.conf
build-use-sandbox = true
```

**Comment by bjornfor** [comment] 2017-06-01 17:05
I was going to say "duplicate of https://github.com/NixOS/nixpkgs/issues/22333", but the build error is different.

**Comment by moretea** [comment] 2017-06-01 17:07
I have created a patch that allows chromium to build, it's just taking ages...

**Comment by clhodapp** [comment] 2017-06-09 05:07
This looks just like the error I got when I tried locally to get Chromium building under a stdenv with the patchelf from the head of master (with the fixes @edolstra references in #22333). I guess upstream Chrome are publishing valid Widevine ELFs again, but the dependency set has changed (grown). And yeah, it's shocking how long Chromium takes to build. I wonder if #22333 should be closed in favor of this issue...

**Comment by moretea** [comment] 2017-06-09 06:34
The patch I linked to did not solve the problem, Netflix still complained about not being able to play DRM content.

**Comment by NickHu** [comment] 2017-07-27 18:40
@moretea I tried your patch, and it solved the problem for Spotify at least, which also wants widevine.

That being said, the build time on Chromium is unholy...

**Comment by domenkozar** [comment] 2018-07-13 11:09
@moretea how come your patch was never PR'd? :)

**Comment by BadDecisionsAlex** [comment] 2019-05-10 22:33
Same problem here :(

**Comment by bendlas** [comment] 2019-09-14 12:56
fixed https://github.com/NixOS/nixpkgs/pull/60833

**Closed by bendlas** 2019-09-14 12:56 UTC

**Comment by zarelit** [comment] 2019-09-15 09:45
@bendlas Thank you for the fix!
