### ISSUE TITLE
macvlans example rendering broken

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#91393] opened 2020-06-24 05:10 UTC
**Describe the bug**
![Screenshot from 2020-06-24 07-08-15](https://user-images.githubusercontent.com/91113/85503335-b2344980-b5e9-11ea-8ff4-861cc2a2a6a9.png)

**To Reproduce**
https://nixos.org/nixos/options.html#macvlans

**Expected behavior**
show the actual example

https://github.com/NixOS/nixpkgs/blob/54ad1864617eb2a66b762e67d9a6ea06641bcbbf/nixos/modules/tasks/network-interfaces.nix#L690-L694

**Comment by flokli** [comment] 2020-06-24 09:25
`literalExample` needs a string - see other occurences of it.

This seems quite an easy fix - can you file a PR for it?

**Comment by flokli** [comment] 2020-12-22 10:43
I can't reproduce this on 20.09 docs and master. Probably has been fixed by 2e4a45c92171ad1712dcdcebffcd178f794c7d7f already.

**Closed by flokli** 2020-12-22 10:43 UTC
Labels: 0.kind: bug
