### ISSUE TITLE
Xorg programs missing from "command-not-found"

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#11996] opened 2015-12-28 08:18 UTC
```
$ xeyes
xeyes: command not found
$ xclock
xclock: command not found
```

(I expect nix to suggest a command-line to install missing programs.)

Add ```meta.platforms = unix``` to ```generate-expr-from-tarballs.pl```?

**Comment by vcunat** [comment] 2015-12-29 12:39
> Add meta.platforms = unix to generate-expr-from-tarballs.pl?

I suppose so, though I'm not certain people really use such programs... Currently there's only an explicit list in https://github.com/nixos/nixpkgs/tree/master/pkgs/top-level/release.nix#L242.

**Comment by bjornfor** [comment] 2015-12-29 12:49
I don't _use_ them myself, they are programs that I run once in a while when I need a dummy X client program. So it is an issue that I hit from time to time ("which attrpath should I use to get xeyes"?). But more importantly, I think everything that is built by the build farm should be advertised as such (i.e. be in the "command-not-found" database).

@vcunat: What do you suggest we do? Adding to the explicit platform list or the generator script?

**Comment by vcunat** [comment] 2015-12-29 12:58
I suspect some of these aren't even built on Hydra.

> What do you suggest we do? Adding to the explicit platform list or the generator script?

Probably, but I can't write perl myself. The `xf86*` packages don't seem to make sense on Darwin, but most of the rest could get `platforms.unix` by default. We could then override some cases manually in `overrides.nix`.

**Comment by bjornfor** [comment] 2015-12-30 11:50
@vcunat: I extended the generator script with "meta.platforms" here: https://github.com/NixOS/nixpkgs/pull/12034

**Comment by zimbatm** [comment] 2016-05-09 18:54
command-not-found is not working for me at the moment. can someone check if this issue has been fixed on nixos-unstable now ?

**Comment by vcunat** [comment] 2016-05-09 22:01
@zimbatm: see https://github.com/NixOS/nixos-channel-scripts/issues/4 which "blocks" this issue.

**Comment by zimbatm** [comment] 2016-05-09 22:48
thanks for the pointer

**Comment by bjornfor** [comment] 2016-08-27 21:30
```xclock``` is in command-not-found on NixOS 16.09pre as of today (8512747ca5120a4cf6cd41ad9e049866e37a351c). But ```xeyes``` is not. Both packages have ```meta.platforms = unix``` in the .nix file.

Searching for "xeyes" or "xclock" jobs on hydra gives no result. Not sure why even ```xclock``` is built by hydra then...

**Comment by dezgeg** [comment] 2016-08-28 14:23
The problem is probably because of https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/release.nix#L283 drops all other `xorg.*` jobs than those specified there. I think that could just be dropped.

**Closed** 2016-08-28 14:47 UTC
Labels: 0.kind: enhancement
