### ISSUE TITLE
Package request: itch

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#152256] opened 2021-12-26 17:31 UTC
**Project description**
The best way to play itch.io games.

**Metadata**

* homepage URL: https://itch.io
* source URL:https://github.com/itchio/itch
* license: mit
* platforms: unix, windows

**Comment by davidak** [comment] 2022-02-11 01:38
Duplicate of https://github.com/NixOS/nixpkgs/issues/90233. Please check for existing issues before opening a new one.

**Closed by davidak** 2022-02-11 01:38 UTC
Labels: 0.kind: packaging request

**Comment by pasqui23** [comment] 2022-02-11 09:45
The linked issue is closed.
