### ISSUE TITLE
Luarocks package versions override Vim Plugin versions

### ISSUE THREAD

**Issue by fmoda3** [NixOS/nixpkgs#188302] opened 2022-08-25 16:55 UTC
### Describe the bug
Not sure if this is intended behavior or not, but while trying to track down a bug in gitsigns-nvim plugin, I realized that the version of the plugin I had installed in neovim was not actually the version specified in the the vim plugins generated file.

A recent neovim change started producing an error when using the gitsigns plugin.  The author recently put in a fix, and the version specified in the vim plugin file includes the fix for this error: https://github.com/NixOS/nixpkgs/blob/963d27a0767422be9b8686a8493dcade6acee992/pkgs/applications/editors/vim/plugins/generated.nix#L3163

However, I was still running into the error and had reported it to the plugin author.  After some back and forth, and a bunch of digging, I realized that the version that was actually installed in my neovim was a much earlier version, and thats when I discovered that this plugin (and presumably Plenary as well), gets overridden with the version in Luarocks here: https://github.com/NixOS/nixpkgs/blob/03428dbaaa23d6bf458770907b0927b377c873a8/pkgs/development/lua-modules/generated-packages.nix#L515

Is this intended behavior?  If so, is there a way to make it more obvious to end users that these plugins in the vim generated plugins file is effectively ignored?

### Steps To Reproduce
1. Setup neovim in nix with the gitsigns-nvim plugin
2. Observe that the installed gitsigns plugin uses the luarocks version

### Expected behavior
I possibly expect it to use the gitsigns version specified in the vim plugin generated file.

### Notify maintainers
@Scoder12 @teto 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.10.3`
 - channels(fmoda3): `""`
 - channels(root): `"nixpkgs-21.11pre329302.d14ae62671f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by teto** [comment] 2022-08-25 22:52
thanks for the report, it's a known issue. Closing as duplicate of https://github.com/NixOS/nixpkgs/issues/185397. I tried to regenerate the package set when I hit https://github.com/NixOS/nixpkgs/issues/188090

**Closed by teto** 2022-08-25 22:52 UTC
Labels: 0.kind: bug, 6.topic: vim

**Comment by fmoda3** [comment] 2022-08-26 00:09
Ahh, didn't realize there was already a ticket!  As for https://github.com/NixOS/nixpkgs/issues/188090, I clicked the tarball link and it downloaded.  Maybe the archive site is back?

**Comment by Scoder12** [comment] 2022-08-26 00:14
Attempting to update all the lua packages now in #185723
