### ISSUE TITLE
Module option request: configuring weston for SDDM

### ISSUE THREAD

**Issue by crftbt** [NixOS/nixpkgs#317253] opened 2024-06-04 17:40 UTC
**Project description**

I've determine a way to rotate the SDDM Wayland login display with Weston documented here https://github.com/crftbt/NixOSSDDMWaylandRotate/. Is there a better way to do this? Ideally a services.weston.config or something similar to modify the existing weston.ini would remove the need for a rw copy of the weston.ini.

**Metadata**

* homepage URL: https://gitlab.freedesktop.org/wayland/weston
* source URL: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/window-managers/weston/default.nix#L74
* license: mit
* platforms: i686-linux, aarch64-linux, x86_64-linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-06-06 20:35
Currently this is how the config file is generated:
https://github.com/NixOS/nixpkgs/blob/ef5142ec5bf85037a16572da3f4d59085833aad0/nixos/modules/services/display-managers/sddm.nix#L112-L126

which you can use this as a starting point to set the compositor command (`services.displayManager.sddm.wayland.compositorCommand`)

CC @peterhoeg @K900 for input on how they want to handle this

**Comment by K900** [comment] 2024-06-06 20:37
Generally, wrongly rotated screens should be fixed at DRM level, not with hacks like these.

**Comment by crftbt** [comment] 2024-06-07 02:07
> Generally, wrongly rotated screens should be fixed at DRM level, not with hacks like these.

Not really sure what this means. Would you provide some more guidance to help me understand?

**Comment by K900** [comment] 2024-06-07 08:49
Do you have a device where the display orientation is incorrect? Or is your monitor physically rotated from its normal orientation?

**Comment by crftbt** [comment] 2024-06-07 15:36
Yes

**Comment by K900** [comment] 2024-06-07 15:38
So which is it?

**Comment by crftbt** [comment] 2024-06-07 15:40
The goal is to update the weston.ini configuration file in NixOS. See original post for details.

**Comment by RaitoBezarius** [comment] 2024-06-07 21:04
This is not a good way to interact with developers from the NixOS project, consider changing your ways or we can close the issue here, to be honest.

**Comment by RaitoBezarius** [comment] 2024-06-07 21:04
This is not a good way to interact with developers from the NixOS project, consider changing your ways or we can close the issue here, to be honest.

**Closed** 2024-06-07 22:13 UTC
Labels: 9.needs: module (update)

**Comment by OsiPog** [comment] 2024-07-01 13:49
Consider a monitor setup where one monitor is manually rotated to portrait orientation. Usually monitors don't come with built-in settings for rotation of the displayed screen, so the software must make that adjustment.
I wouldn't consider that a "hack" as it's just a customization of the weston monitor setup. 

When using some XDisplay compositor it's recommended to just use the `DisplayCommand=` setting in the `/etc/ssd.conf` pointing to a script that executes some `xrandr` commands. The problem is that when the compositor is using wayland that script isn't called. 

So the idea is to modify the `weston.ini` config itself.
