### ISSUE TITLE
pythonRelaxDepsHook 

### ISSUE THREAD

**Issue by fabaff** [NixOS/nixpkgs#176695] opened 2022-06-07 10:57 UTC
### Describe the bug
It looks like that the new `pythonRelaxDepsHook` is handling more that just the dependencies if there is name match.
 
### Steps To Reproduce

Use `pythonRelaxDepsHook` for a module that starts with the name of the module which should be handled by the hook, `pytest-*` and the constraint on `pytest` should be removed.

```bash
$ nix-build -A python310Packages.pytest-annotate
[...]
adding 'pytest_annotate-1.0.4.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
/build/pytest-annotate-1.0.4/dist /build/pytest-annotate-1.0.4
Bad wheel filename ''
[...]
```

I haven't investigated this further or with other combinations. It works fine if the constraints are removed with `sed` or `substituteInPlace`.

### Expected behavior
Only the dependencies should be touched.

### Notify maintainers

@thiagokokada

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.39, NixOS, 22.11 (Raccoon), 22.11pre381914.f1c167688a6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by fabaff** [comment] 2022-06-07 13:34
This is another case:

```nix
{ lib
, buildPythonPackage
, fetchFromGitHub
, poetry-core
, pysigma
, pytestCheckHook
, pythonOlder
, pythonRelaxDepsHook
}:

buildPythonPackage rec {
  pname = "pysigma-backend-insightidr";
  version = "0.1.5";
  format = "pyproject";

  disabled = pythonOlder "3.8";

  src = fetchFromGitHub {
    owner = "SigmaHQ";
    repo = "pySigma-backend-insightidr";
    rev = "refs/tags/v${version}";
    hash = "sha256-RjBRFNMIpjW/x5vShXUgi25oOmvRlD2zP6mNQJ7sG8M=";
  };

  nativeBuildInputs = [
    poetry-core
    pythonRelaxDepsHook
  ];

  propagatedBuildInputs = [
    pysigma
  ];

  pythonRelaxDeps = [
    "pysigma"
  ];

  checkInputs = [
    pytestCheckHook
  ];

  pythonImportsCheck = [
    "sigma.backends.insight_idr"
    "sigma.pipelines.insight_idr"
  ];

  meta = with lib; {
    description = "Library to support the Rapid7 InsightIDR backend for pySigma";
    homepage = "https://github.com/SigmaHQ/pySigma-backend-insightidr";
    license = with licenses; [ lgpl21Only ];
    maintainers = with maintainers; [ fab ];
  };
}
````

**Comment by thiagokokada** [comment] 2022-06-07 14:19
I think the issue is the `-` separating the package name. I didn't test any case like this.

**Comment by thiagokokada** [comment] 2022-06-07 20:13
Here is the fix: https://github.com/NixOS/nixpkgs/pull/176721

**Comment by thiagokokada** [comment] 2022-06-16 09:44
Merged https://github.com/NixOS/nixpkgs/pull/176721, should be fixed once it gets to `master`.

**Closed** 2022-08-21 01:25 UTC
Labels: 0.kind: bug, 6.topic: python
