### ISSUE TITLE
Can't open links from Dino in Chromium

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#82722] opened 2020-03-16 11:12 UTC
**Describe the bug**
When i click on a http(s) link in Dino, the cursor shows that something is happening, but then nothing happens. stack trace is visible in journal

```
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: /nix/store/wx1vk75bpdr65g6xwxbj4rw0pk04v5j3-glibc-2.27/lib/libm.so.6: version `GLIBC_2.29' not found (required by /nix/store/d9pbazhmjia1j2kiw2wqirqk38yhpj9a-spidermonkey-60.9.0/lib/libmozjs-60.so)
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: Failed to load module: /nix/store/2y5d7j56z91z012aiycy9hk8gwh7jzry-glib-networking-2.62.3/lib/gio/modules/libgiolibproxy.so
Mar 16 12:02:49 ethmoid chromium[3447]: Could not load a pixbuf from icon theme.
                                        This may indicate that pixbuf loaders or the mime database could not be found.
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: **
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: Gtk:ERROR:../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/current-system/sw/share/icons/elementary/status/16/image-missing.svg: Unable to load image-loading module: /nix/store/giq6qdg140n314jqafk86s7ymgcaj27m-librsvg-2.46.4/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /nix/store/wx1vk75bpdr65g6xwxbj4rw0pk04v5j3-glibc-2.27/lib/libm.so.6: version `GLIBC_2.29' not found (required by /nix/store/giq6qdg140n314jqafk86s7ymgcaj27m-librsvg-2.46.4/lib/librsvg-2.so.2) (gdk-pixbuf-error-quark, 5)
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: Received signal 6
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #0 0x5635284be159 base::debug::CollectStackTrace()
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #1 0x56352842a643 base::debug::StackTrace::StackTrace()
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #2 0x5635284bdcf1 base::debug::(anonymous namespace)::StackDumpSignalHandler()
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #3 0x7f6bf6c06860 <unknown>
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #4 0x7f6bf510bbe0 __GI_raise
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #5 0x7f6bf510cdc1 __GI_abort
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #6 0x7f6bf68b7dc3 g_assertion_message.cold.16
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #7 0x7f6bf69130ce g_assertion_message_error
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #8 0x7f6bf596cc25 ensure_surface_for_gicon
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #9 0x7f6bf596d2d7 gtk_icon_helper_load_surface
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #10 0x7f6bf596d3f4 gtk_icon_helper_ensure_surface.part.4
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #11 0x7f6bf596d5d8 _gtk_icon_helper_get_size
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #12 0x7f6bf5980c6d gtk_image_get_content_size
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #13 0x7f6bf58e05b3 gtk_css_custom_gadget_get_preferred_size
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #14 0x7f6bf58e4731 gtk_css_gadget_get_preferred_size
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #15 0x7f6bf59813d3 gtk_image_get_preferred_height_and_baseline_for_width
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #16 0x7f6bf5a3eca1 gtk_widget_query_size_for_orientation
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #17 0x7f6bf5a3eec0 gtk_widget_compute_size_for_orientation
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #18 0x7f6bf5a3f1f5 gtk_widget_get_preferred_height_and_baseline_for_width
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #19 0x7f6bf58e05b3 gtk_css_custom_gadget_get_preferred_size
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #20 0x7f6bf58e4731 gtk_css_gadget_get_preferred_size
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #21 0x7f6bf589cb43 gtk_button_get_preferred_height_and_baseline_for_width
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #22 0x7f6bf5a3eca1 gtk_widget_query_size_for_orientation
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #23 0x7f6bf5a3eec0 gtk_widget_compute_size_for_orientation
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #24 0x7f6bf5a3f1f5 gtk_widget_get_preferred_height_and_baseline_for_width
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #25 0x7f6bf588f5c4 gtk_box_get_content_size
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #26 0x7f6bf58e05b3 gtk_css_custom_gadget_get_preferred_size
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #27 0x7f6bf58e4731 gtk_css_gadget_get_preferred_size
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #28 0x7f6bf588ff63 gtk_box_get_preferred_height_and_baseline_for_width
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #29 0x7f6bf5a3eca1 gtk_widget_query_size_for_orientation
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #30 0x7f6bf5a3eec0 gtk_widget_compute_size_for_orientation
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #31 0x7f6bf5a3e3c1 gtk_widget_get_preferred_height
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #32 0x7f6bf5968614 add_child_size
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #33 0x7f6bf5968926 gtk_header_bar_get_content_size
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #34 0x7f6bf58e05b3 gtk_css_custom_gadget_get_preferred_size
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #35 0x7f6bf58e4731 gtk_css_gadget_get_preferred_size
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #36 0x7f6bf59683ed gtk_header_bar_get_preferred_height
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #37 0x7f6bf5a3e75b gtk_widget_query_size_for_orientation
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #38 0x7f6bf5a3eec0 gtk_widget_compute_size_for_orientation
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #39 0x7f6bf5a3e3c1 gtk_widget_get_preferred_height
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #40 0x7f6bf5afd5f6 gtk_window_get_preferred_height
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #41 0x7f6bf5a3e75b gtk_widget_query_size_for_orientation
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #42 0x7f6bf5a3eec0 gtk_widget_compute_size_for_orientation
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #43 0x7f6bf5a3f1f5 gtk_widget_get_preferred_height_and_baseline_for_width
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #44 0x7f6bf5a3f343 _gtk_widget_get_preferred_size_and_baseline
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #45 0x7f6bf5aff034 gtk_window_compute_configure_request
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #46 0x7f6bf5b033fa gtk_window_realize
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #47 0x7f6bf69d0d5d g_closure_invoke
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #48 0x7f6bf69e3ccc signal_emit_unlocked_R
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #49 0x7f6bf69eca5e g_signal_emit_valist
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #50 0x7f6bf69ed11f g_signal_emit
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #51 0x7f6bf5af3ef6 gtk_widget_realize.localalias.119
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #52 0x56352ad199dc libgtkui::GtkUi::GtkUi()
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #53 0x56352ad1e87b BuildGtkUi()
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #54 0x56352abc7805 ChromeBrowserMainExtraPartsViewsLinux::ToolkitInitialized()
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #55 0x56352834a92a ChromeBrowserMainParts::ToolkitInitialized()
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #56 0x563526560464 content::BrowserMainLoop::InitializeToolkit()
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #57 0x5635265611b2 content::BrowserMainRunnerImpl::Initialize()
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #58 0x56352655c15d content::BrowserMain()
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #59 0x563527fa9e95 content::ContentMainRunnerImpl::RunServiceManager()
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #60 0x563527fa9b93 content::ContentMainRunnerImpl::Run()
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #61 0x563528004c23 service_manager::Main()
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #62 0x563527fa7ea3 content::ContentMain()
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #63 0x5635257b3938 ChromeMain
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #64 0x7f6bf50f8b8e __libc_start_main
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: #65 0x5635257b376a _start
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]:   r8: 0000000000000000  r9: 00007fff59ae0190 r10: 0000000000000008 r11: 0000000000000246
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]:  r12: 00007f6bf69bae00 r13: 00007fff59ae03d0 r14: 00007f6bf5bd59c0 r15: 00007f6bf5bd59c0
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]:   di: 0000000000000002  si: 00007fff59ae0190  bp: 0000000000000232  bx: 00000df6fc312000
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]:   dx: 0000000000000000  ax: 0000000000000000  cx: 00007f6bf510bbe0  sp: 00007fff59ae0208
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]:   ip: 00007f6bf510bbe0 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]:  trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: [end of stack trace]
Mar 16 12:02:49 ethmoid io.elementary.cerbere.desktop[1529]: Calling _exit(1). Core file will not be generated.
```

**To Reproduce**
1. open dino
2. join some chatroom where links are posted
3. click link

**Expected behavior**
link opens in default browser like with other applications

**Additional context**
I'm using the pantheon desktop.

Full config: https://github.com/davidak/nixos-config/blob/master/machines/ethmoid/configuration.nix

@worldofpeace didn't we had this issue before? maybe in combination with some crash? could it be fixed in next stable release?

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.109, NixOS, 19.09.2260.3b9b10e49be (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-19.09.2260.3b9b10e49be, nixos-hardware, nixos-unstable-20.09pre216896.0729b8c55e0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: dino
# a list of nixos modules affected by the problem
module:
```

**Comment by davidak** [comment] 2020-03-22 21:34
Same with Fractal (Gtk Matrix Client):

```
[davidak@X230:~]$ fractal 
fractal_gtk::app::backend_loop: Query error: RoomDetail(Err(MatrixError(Object({"errcode": String("M_NOT_FOUND"), "error": String("Event not found.")}))))
Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"

(chromium:2147): Gtk-WARNING **: 22:30:51.090: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /nix/store/48h8wfjff0szkcnhld67zygf458inw0b-elementary-icon-theme-5.0.4/share/icons/elementary/status/16/image-missing.svg: Unable to load image-loading module: /nix/store/18l8ly5235r94s2rr122i3cfichccxqn-librsvg-2.46.4/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /nix/store/wx1vk75bpdr65g6xwxbj4rw0pk04v5j3-glibc-2.27/lib/libm.so.6: version `GLIBC_2.29' not found (required by /nix/store/18l8ly5235r94s2rr122i3cfichccxqn-librsvg-2.46.4/lib/librsvg-2.so.2) (gdk-pixbuf-error-quark, 5)
Received signal 6
#0 0x55e020e9b159 base::debug::CollectStackTrace()
#1 0x55e020e07643 base::debug::StackTrace::StackTrace()
#2 0x55e020e9acf1 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7fd80873a860 <unknown>
#4 0x7fd806c3fbe0 __GI_raise
#5 0x7fd806c40dc1 __GI_abort
#6 0x7fd8083ebdc3 g_assertion_message.cold.16
#7 0x7fd8084470ce g_assertion_message_error
#8 0x7fd8074a0c25 ensure_surface_for_gicon
#9 0x7fd8074a12d7 gtk_icon_helper_load_surface
#10 0x7fd8074a13f4 gtk_icon_helper_ensure_surface.part.4
#11 0x7fd8074a15d8 _gtk_icon_helper_get_size
#12 0x7fd8074b4c6d gtk_image_get_content_size
#13 0x7fd8074145b3 gtk_css_custom_gadget_get_preferred_size
#14 0x7fd807418731 gtk_css_gadget_get_preferred_size
#15 0x7fd8074b53d3 gtk_image_get_preferred_height_and_baseline_for_width
#16 0x7fd807572ca1 gtk_widget_query_size_for_orientation
#17 0x7fd807572ec0 gtk_widget_compute_size_for_orientation
#18 0x7fd8075731f5 gtk_widget_get_preferred_height_and_baseline_for_width
#19 0x7fd8074145b3 gtk_css_custom_gadget_get_preferred_size
#20 0x7fd807418731 gtk_css_gadget_get_preferred_size
#21 0x7fd8073d0b43 gtk_button_get_preferred_height_and_baseline_for_width
#22 0x7fd807572ca1 gtk_widget_query_size_for_orientation
#23 0x7fd807572ec0 gtk_widget_compute_size_for_orientation
#24 0x7fd8075731f5 gtk_widget_get_preferred_height_and_baseline_for_width
#25 0x7fd8073c35c4 gtk_box_get_content_size
#26 0x7fd8074145b3 gtk_css_custom_gadget_get_preferred_size
#27 0x7fd807418731 gtk_css_gadget_get_preferred_size
#28 0x7fd8073c3f63 gtk_box_get_preferred_height_and_baseline_for_width
#29 0x7fd807572ca1 gtk_widget_query_size_for_orientation
#30 0x7fd807572ec0 gtk_widget_compute_size_for_orientation
#31 0x7fd8075723c1 gtk_widget_get_preferred_height
#32 0x7fd80749c614 add_child_size
#33 0x7fd80749c926 gtk_header_bar_get_content_size
#34 0x7fd8074145b3 gtk_css_custom_gadget_get_preferred_size
#35 0x7fd807418731 gtk_css_gadget_get_preferred_size
#36 0x7fd80749c3ed gtk_header_bar_get_preferred_height
#37 0x7fd80757275b gtk_widget_query_size_for_orientation
#38 0x7fd807572ec0 gtk_widget_compute_size_for_orientation
#39 0x7fd8075723c1 gtk_widget_get_preferred_height
#40 0x7fd8076315f6 gtk_window_get_preferred_height
#41 0x7fd80757275b gtk_widget_query_size_for_orientation
#42 0x7fd807572ec0 gtk_widget_compute_size_for_orientation
#43 0x7fd8075731f5 gtk_widget_get_preferred_height_and_baseline_for_width
#44 0x7fd807573343 _gtk_widget_get_preferred_size_and_baseline
#45 0x7fd807633034 gtk_window_compute_configure_request
#46 0x7fd8076373fa gtk_window_realize
#47 0x7fd808504d5d g_closure_invoke
#48 0x7fd808517ccc signal_emit_unlocked_R
#49 0x7fd808520a5e g_signal_emit_valist
#50 0x7fd80852111f g_signal_emit
#51 0x7fd807627ef6 gtk_widget_realize.localalias.119
#52 0x55e0236f69dc libgtkui::GtkUi::GtkUi()
#53 0x55e0236fb87b BuildGtkUi()
#54 0x55e0235a4805 ChromeBrowserMainExtraPartsViewsLinux::ToolkitInitialized()
#55 0x55e020d2792a ChromeBrowserMainParts::ToolkitInitialized()
#56 0x55e01ef3d464 content::BrowserMainLoop::InitializeToolkit()
#57 0x55e01ef3e1b2 content::BrowserMainRunnerImpl::Initialize()
#58 0x55e01ef3915d content::BrowserMain()
#59 0x55e020986e95 content::ContentMainRunnerImpl::RunServiceManager()
#60 0x55e020986b93 content::ContentMainRunnerImpl::Run()
#61 0x55e0209e1c23 service_manager::Main()
#62 0x55e020984ea3 content::ContentMain()
#63 0x55e01e190938 ChromeMain
#64 0x7fd806c2cb8e __libc_start_main
#65 0x55e01e19076a _start
  r8: 0000000000000000  r9: 00007ffc1a84c8f0 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007fd8084eee00 r13: 00007ffc1a84cb30 r14: 00007fd8077099c0 r15: 00007fd8077099c0
  di: 0000000000000002  si: 00007ffc1a84c8f0  bp: 0000000000000263  bx: 00003d0f83d18a00
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007fd806c3fbe0  sp: 00007ffc1a84c968
  ip: 00007fd806c3fbe0 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

---

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.107, NixOS, 19.09.2284.bf7c0f0461e (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(davidak): `""`
 - channels(root): `"nixos-19.09.2284.bf7c0f0461e, nixos-hardware, nixos-unstable-20.09pre217537.d96bd3394b7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment] 2020-03-23 18:30
Woah, this is weird.

**Comment by sorpaas** [comment] 2020-04-05 22:14
Having the same `version `GLIBC_2.29' not found` issue, but this happens for me when compiling some Rust source code.

**Comment by terlar** [comment] 2020-04-29 18:53
I am not sure if it is related, but I had some libraries that I built with nix and deployed to a lambda "librdkafka" (rdkafka). But I am not sure why it is pinned to GLIBC 2.29. I do have glibc 2.30 as part of NixOS release 20.03 but I built some other libs and they could be used on Amazon Linux 2 which is running Glibc 2.26.

**Comment by scalavision** [comment] 2020-06-12 07:59
I also have this:

```
Failed to load module: /nix/store/iikifn19pk3qwv2xgh06kr0f8590sf0b-glib-networking-2.62.3/lib/gio/modules/libgiognomeproxy.so
/nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27/lib/libm.so.6: version `GLIBC_2.29' not found (required by /nix/store/0vlmnzpvy7as4m28yn541030yvjxrc1h-spidermonkey-60.9.0/lib/libmozjs-60.so)
```
When using igv 2.8.3.

**Comment by blm768** [comment] 2022-01-13 06:01
I'm seeing a similar error message with GNUCash 4.5 on NixOS 11 (KDE Plasma, `nixpkgs` revision b2168f22fd68bb01345dcd374dae266da51d479b).

```
(gnucash:71084): Gtk-WARNING **: 21:56:15.436: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/current-system/sw/share/icons/breeze/status/64/image-missing.svg: Unable to load image-loading module: /nix/store/7ywc6c8rxnglpmvgqmqmz7z4z7chspfz-librsvg-2.52.4/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /nix/store/nprym6lf8lzhp1irb42lb4vp8069l5rj-glibc-2.32-54/lib/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/7ywc6c8rxnglpmvgqmqmz7z4z7chspfz-librsvg-2.52.4/lib/librsvg-2.so.2) (gdk-pixbuf-error-quark, 5)
Bail out! Gtk:ERROR:../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/current-system/sw/share/icons/breeze/status/64/image-missing.svg: Unable to load image-loading module: /nix/store/7ywc6c8rxnglpmvgqmqmz7z4z7chspfz-librsvg-2.52.4/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /nix/store/nprym6lf8lzhp1irb42lb4vp8069l5rj-glibc-2.32-54/lib/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/7ywc6c8rxnglpmvgqmqmz7z4z7chspfz-librsvg-2.52.4/lib/librsvg-2.so.2) (gdk-pixbuf-error-quark, 5)

```

**Comment by jrvidal** [comment] 2023-10-31 08:42
Similar issue when I try to open the help menu in Meld:

```
$ meld
Couldn't set the locale: unsupported locale setting; falling back to 'C' locale

(.meld-wrapped:1776298): Gtk-WARNING **: 08:44:58.325: Locale not supported by C library.
	Using the fallback 'C' locale.

(yelp:1776323): Gtk-WARNING **: 08:45:02.017: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Pop/16x16/status/image-missing.svg: Unable to load image-loading module: /nix/store/090fi55giyisb0glc2lmng7wrz01jr6w-librsvg-2.56.3/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /nix/store/090fi55giyisb0glc2lmng7wrz01jr6w-librsvg-2.56.3/lib/librsvg-2.so.2) (gdk-pixbuf-error-quark, 5)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Pop/16x16/status/image-missing.svg: Unable to load image-loading module: /nix/store/090fi55giyisb0glc2lmng7wrz01jr6w-librsvg-2.56.3/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /nix/store/090fi55giyisb0glc2lmng7wrz01jr6w-librsvg-2.56.3/lib/librsvg-2.so.2) (gdk-pixbuf-error-quark, 5)
```

## Nix info
```
 $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.4-76060504-generic, Pop!_OS, 22.04 LTS, nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/kii30vrsz832yg94v9w2imlwn8pp69xq-source`
```

(I'm pinging some GNOME maintainers, hope I'm not missing the mark too much)

@bobby285271 @jtojnar

**Comment by SuperSandro2000** [comment] 2024-03-23 18:07
Can't reproduce on master and since this is really old I am closing it.

**Closed by SuperSandro2000** 2024-03-23 18:07 UTC
Labels: 0.kind: bug
