### ISSUE TITLE
Package request: Spacedrive

### ISSUE THREAD

**Issue by dougkeiller** [NixOS/nixpkgs#273417] opened 2023-12-10 21:34 UTC
[**Project description**](https://www.spacedrive.com/)

Unify files from all your devices and clouds into a single, easy-to-use explorer.
Designed for creators, hoarders and the painfully disorganized.

**Metadata**

* homepage URL: https://github.com/spacedriveapp/spacedrive
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment] 2023-12-10 23:07
Duplicate of https://github.com/NixOS/nixpkgs/issues/170254

`spacedrive` is already in nixos-unstable

**Closed by donovanglover** 2023-12-10 23:07 UTC
Labels: 0.kind: packaging request
