### ISSUE TITLE
perl536Packages.ModuleBuild fails to cross compile for i686 due to missing file

### ISSUE THREAD

**Issue by RossComputerGuy** [NixOS/nixpkgs#202112] opened 2022-11-20 23:50 UTC
### Steps To Reproduce
1. build *perl536Packages.ModuleBuild* for i686

### Build log
```
# running Build.PL --prefix /nix/store/qsdnzv43695y6ipdkqjlrf48nykgb7az-perl5.36.0-Module-Build-0.4231-i686-unknown-linux-gnu --installdirs site --config perl=/nix/store/aabd54wnc0vjcpysfs7xkm8ss4mr09n7-perl-i686-unknown-linux-gnu-5.36.0-mini/bin/perl --fullperl "/nix/store/1zlrx8g7xs6ar0ggca4h3p6hmapq2p2h-perl-5.36.0/bin/perl"
Checking prerequisites...
  test_requires:
    !  Couldn't find a $VERSION in prerequisite File::Temp

Checking optional features...
inc_bundling_support....disabled
  requires:
    ! inc::latest is not installed

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
of the modules indicated above before proceeding with this installation

Attempt to reload Scalar/Util.pm aborted.
Compilation failed in require at /nix/store/14qn960rvd40hf2jf4h01wxb8rb27xz0-perl-i686-unknown-linux-gnu-5.36.0/lib/perl5/5.36.0/i686-linux/Data/Dumper.pm line 284.
Couldn't run Build.PL: No such file or directory at lib/Module/Build/Compat.pm line 341.
```

### Additional context

Found on my Hydra server, [build job](http://hydra.expidusos.com/build/59).

[View raw log](http://hydra.expidusos.com/log/bnirnfrsxqjvizzrb4liw0vfg3cg9b2a-perl5.36.0-Module-Build-0.4231-i686-unknown-linux-gnu.drv)

### Notify maintainers

@anthonyroussel

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.74, NixOS, 22.05 (Quokka), 22.05.3848.c132d0837df`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - channels(ross): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by Artturin** [comment] 2022-11-21 21:17
dupe of https://github.com/NixOS/nixpkgs/issues/66741

**Closed by Artturin** 2022-11-21 21:17 UTC
Labels: 0.kind: build failure
