### ISSUE TITLE
journalctl doesn't get new content

### ISSUE THREAD

**Issue by wwat** [NixOS/nixpkgs#5553] opened 2015-01-03 18:52 UTC
`journalctl` should contain new information after for example a reboot or a nixos-rebuild switch. It actually contains zero new entries since over a month. 

I am sure that this works on certain systems (for example, it works on a VM), but it doesn't on all.

**Comment by bjornfor** [comment] 2015-01-03 18:57
Do you run journalctl with enough permissions? What's the output of ```ls -lR /var/log/journal/```?
Try running strace on journalctl.

**Comment by wwat** [comment] 2015-01-03 19:04
```
[root@nixos:~]# ls -lR /var/log/journal/
/var/log/journal/:
total 49
drwxr-xr-x 2 root root 9 Jan  3 13:03 0ff2d82976064a17a734c027e1c7ca91

/var/log/journal/0ff2d82976064a17a734c027e1c7ca91:
total 81972
-rw-r-----  1 root root 16777216 Nov 19 20:20 system@0005083b1b577c4b-e388b89d67a3306f.journal~
-rw-r-----  1 root root  8388608 Nov 22 17:24 system@00050874fefb46ea-9597e8c30b8e02fc.journal~
-rw-r-----  1 root root 16777216 Jan  3 12:34 system@19b4251be7b34901835779e495bde6a6-0000000000000001-00050874fef59712.journal
-rw-r-----  1 root root  8388608 Jan  3 13:03 system@19b4251be7b34901835779e495bde6a6-0000000000004e02-00050bbdd7a00154.journal
-rw-r-----  1 root root 16777216 Jan  3 20:01 system.journal
-rw-r-----+ 1 root root  8388608 Jan  3 13:03 user-1000@f5cc890e2f464d1aa61bc18a507afdaf-00000000000004c4-000507ef1d3cad23.journal
-rw-r-----+ 1 root root  8388608 Jan  3 19:50 user-1000.journal
```

Going to the end of journalctl and then pressing end returns "Waiting for data", but that's normal. strace merely shows that journalctl does one write systemcall per line or so, but shows nothing of interest. I think the data is just not there.

**Comment by bjornfor** [comment] 2015-01-03 19:19
Paste the full journalctl command line, with output. Also paste the output of 'id' for the user you run journalctl as.

**Comment by 7c6f434c** [comment] 2015-01-03 19:21
>Paste the full journalctl command line, with output. Also paste the output of 'id' for the user you run journalctl as.

Also tell us for how long you have waited for journalctl to complete and
what iotop said during that time.

**Comment by wwat** [comment] 2015-01-03 19:25
I ran it again under strace and it returns almost instantly (0.2 seconds) or so. 

uid=0(root) gid=0(root) groups=0(root),121(grsecurity)

**Comment by wwat** [comment] 2015-01-03 19:43
@bjornfor I don't really see the point of pasting the whole contents of output which hasn't changed in over one month. There are 8000 lines in it and they contain just generic log information, but nothing recent. 

The component which is responsible for writing new messages clearly is not working (and this is something which should be verified). So, there should be a method to add a message to journalctl and ideally there would be some kind of self-test. Not to start that whole systemd discussion again, but this has never happened without systemd. 

The last entry is from somewhere in November 2014.

**Comment by bjornfor** [comment] 2015-01-03 20:54
Right. Old data makes little sense. You could use "journalctl -b" to get everything since the last boot. If that's empty, we know something weird is going on.

Anyway, one way to test it is with ```echo hello | systemd-cat```. On my system I can see the output immediately in another terminal running ```journalctl -f```.

**Comment by wwat** [comment] 2015-01-03 21:04
I am seeing a lot of entries like:
```Jan 03 21:58:21 nixos ntpd[17979]: bind(24) AF_INET6 fe80::d250:99ff:fe46:c2e7%3%3#123 flags 0x11 failed: Cannot assign requested address
Jan 03 21:58:21 nixos ntpd[17979]: unable to create socket on enp8s0 (212) for fe80::d250:99ff:fe46:c2e7%3#123
```
I don't have an external ipv6 address, but the device which supplies the ipv6 addresses (another router) does support both ipv6 and ipv4, I think. 

I did your test, and `journalctl -f works` fine. However, journalctl only displays output until somewhere in November. In particular 'hello' is not displayed.  

`journalctl -b ` also works fine (contains all the ipv6 messages).

**Comment by bjornfor** [comment] 2015-01-03 21:14
If nobody else can reproduce this, I guess you will have to do some more debugging yourself. Compare everything you can between your working NixOS VM and your non-working system. Eventually you'll find the error :-)

**Comment by 7c6f434c** [comment] 2015-01-03 21:16
>If nobody else can reproduce this, I guess you will have to do some more debugging yourself. Compare everything you can between your working NixOS VM and your non-working system. Eventually you'll find the error :-)

Maybe wiping the /var/log/journal and rebooting may help...
(wiping = moving all files to /var/log/corrupted-journal/)

**Comment by wwat** [comment] 2015-01-03 21:43
After wiping, and running `journalctl` (after a `nixos-rebuild switch`), we have:
```
journalctl 
No journal files were found.
```

**Comment by 7c6f434c** [comment] 2015-01-03 21:46
>After wiping, and running `journalctl` (after a `nixos-rebuild switch`), we have:
>```
>journalctl 
>No journal files were found.
>```

Maybe you need to reboot or to restart systemd-journald in some other 
way.

**Comment by bjornfor** [comment] 2015-07-12 10:22
@wwat: Is this still an issue?

**Comment by wwat** [comment] 2015-07-12 12:46
@bjornfor I don't know. I think a fix would be to first document when journalctl is supposed to work (i.e., what its contract is) within NixOS. When that's done, someone can evaluate whether or not it's actually working or not. 

At this moment in time I have no interest in this issue. I am unsubscribing from this ticket.

**Comment by bjornfor** [comment] 2015-07-12 13:11
I guess journalctl is supposed to always work. And for me it seems to do that (I don't have big unexpected "holes" in the log). And I guess it works for most other people as well, or else I'd expect more comments on this bug in the ~6 months it has been open.

I'll close this then.

**Closed by bjornfor** 2015-07-12 13:11 UTC
