### ISSUE TITLE
Incorrect license for Albert (No longer GPL)

### ISSUE THREAD

**Issue by Thymelizabeth** [NixOS/nixpkgs#279280] opened 2024-01-07 03:24 UTC
### Describe the bug
Since version 0.21.0, Albert is no longer GPL licensed, and cannot be distributed in binary form without written permission.

### Steps To Reproduce
1. Check license of Albert in [its package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/albert/default.nix)
2. Check license of Albert on its [Github](https://github.com/albertlauncher/albert/blob/master/LICENSE.md)

### Expected behavior
The license in the package should match the one on Github.

### Additional context
See [this issue](https://web.archive.org/web/20210225183856/https://github.com/albertlauncher/albert/issues/765) for the developer's intentions.

### Notify maintainers
@ericsagnes @Synthetica9

**Comment by donovanglover** [comment] 2024-01-07 04:52
Duplicate of https://github.com/NixOS/nixpkgs/issues/279226

**Closed by donovanglover** 2024-01-07 04:52 UTC
Labels: 0.kind: bug
