### ISSUE TITLE
lldb: unable to debug executable on macOS

### ISSUE THREAD

**Issue by naturecodevoid** [NixOS/nixpkgs#277958] opened 2023-12-31 19:18 UTC
### Describe the bug

On macOS, lldb fails to debug an executable with the error `shell expansion failed (reason: could not get support executable directory for lldb-argdumper tool). consider launching with 'process launch'.`.

### Steps To Reproduce
1. `nix-shell -p lldb`
2. `lldb <some executable>`
3. Enter `run` command
4. Observe error: `shell expansion failed (reason: could not get support executable directory for lldb-argdumper tool). consider launching with 'process launch'.`

### Expected behavior

lldb to successfully run and debug the executable.

### Additional context

[This StackOverflow answer](https://stackoverflow.com/a/58806739) suggested using `process launch -X 0 --` instead of `run`. This does not work, but gives another error: `unable to locate debugserver`. Might be an indication of another issue with lldb on macOS.

Xcode's lldb works perfectly fine.

### Notify maintainers

@dtzWill @Ericson2314 @lovek323 @alyssais @RaitoBezarius @rrbutani @sternenseemann 

### Metadata

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.2.0, macOS 14.2.1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.2`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by RaitoBezarius** [comment] 2024-01-12 18:51
I am really sorry but I am code owner of LLVM for the Linux side, I really have too much on my plate to take care of macOS, I recommend @reckenrode for this if they have some time to spare.

**Comment by nrabulinski** [comment] 2024-01-12 19:18
As a stopgap solution you can run your lldb like this - `LLDB_DEBUGSERVER_PATH=/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Resources/debugserver lldb`

**Comment by reckenrode** [comment] 2024-01-12 19:37
Duplicate of https://github.com/NixOS/nixpkgs/issues/252838.

**Comment by reckenrode** [comment] 2024-01-12 19:37
Duplicate of https://github.com/NixOS/nixpkgs/issues/252838.

**Closed by reckenrode** 2024-01-12 19:37 UTC
Labels: 0.kind: bug
