### ISSUE TITLE
Libreoffice Version: 7.3.7.2 not building on unstable

### ISSUE THREAD

**Issue by alciono** [NixOS/nixpkgs#213502] opened 2023-01-30 03:47 UTC
### Steps To Reproduce
1. build *X*

### Build log
```
checking for exit in -lboost_date_time... yes
checking whether the Boost::Filesystem library is available... yes
checking for exit in -lboost_filesystem... yes
checking whether the Boost::IOStreams library is available... yes
checking for exit in -lboost_iostreams... yes
checking whether the Boost::Locale library is available... yes
checking for exit in -lboost_locale... yes
checking for boost/shared_ptr.hpp... yes
checking for boost/spirit/include/classic_core.hpp... yes
checking which mdds to use... external
checking for mdds-2.0 >= 2.0.0... no
configure: error: Package requirements (mdds-2.0 >= 2.0.0) were not met:

No package 'mdds-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables MDDS_CFLAGS
and MDDS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
error: builder for '/nix/store/ag2ibpx124yh0lj6dgffd4yap2fmfkmj-libreoffice-7.3.7.2.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/damv46qg69z04d829b1jg2cfag8w0xi3-libreoffice-7.3.7.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/yskzn9vcmyhvskxc6pcxim28fkh8frkk-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ga77m4zjn5dz385r3066cz3jj26aa8n8-nixos-system-bx26-23.05pre447289.9b97ad7b433.drv' failed to build
...


### Notify maintainers
<!--
https://github.com/domenkozar  https://github.com/7c6f434c  https://github.com/vcunat
-->

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.85, NixOS, 23.05 (Stoat), 23.05pre447289.9b97ad7b433`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos"`
 - channels(k): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by wegank** [comment] 2023-01-30 03:49
Duplicate of #212556, #212937, #212985.

**Closed by wegank** 2023-01-30 03:49 UTC
Labels: 0.kind: build failure

**Comment by alciono** [comment] 2023-02-05 04:13
### Libreoffice  not building on unstable (23/02/05).
...
checking for exit in -lboost_iostreams... yes
checking whether the Boost::Locale library is available... yes
checking for exit in -lboost_locale... yes
checking for boost/shared_ptr.hpp... yes
checking for boost/spirit/include/classic_core.hpp... yes
checking which mdds to use... external
checking for mdds-2.0 >= 2.0.0... no
configure: error: Package requirements (mdds-2.0 >= 2.0.0) were not met:

No package 'mdds-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables MDDS_CFLAGS
and MDDS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
error: builder for '/nix/store/gr8vnr6avsfrlhss1an6j5jzwvnx646k-libreoffice-7.4.2.3.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/h4fmw5n49z1k3vfcz7qd94gaf7q6lpf1-libreoffice-7.4.2.3.drv' failed to build
error: 1 dependencies of derivation '/nix/store/v0zb5qwir973za12zlldpvzcsmv7174y-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xx95dcnczf9jg2jd9vp8xyqnf2yxjasz-nixos-system-bx26-23.05pre447289.9b97ad7b433.drv' failed to build

**Comment by wegank** [comment] 2023-02-05 04:16
> ### Libreoffice not building on unstable (23/02/05).

Please update your nix channels.

https://hydra.nixos.org/eval/1790195?filter=libreoffice&compare=1790182&full=
