### ISSUE TITLE
bcompare fails to start due to missing libraries

### ISSUE THREAD

**Issue by catern** [NixOS/nixpkgs#141019] opened 2021-10-08 20:59 UTC
### Describe the bug
bcompare fails to launch with a message about missing libraries:
```
$ nix-env -iA nixpkgs.bcompare
...
$ bcompare
Some Shared Libraries were not found
/nix/store/vv368fk6vqq1k1hyl71w9cv6gf61vhw0-bcompare-4.4.0.25886/lib/beyondcompare/BCompare: /nix/store/90illc73xfs933d06daq6d41njs8yh66-glibc-2.32-37/lib/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/7bkqfx75mf0ryhlay3fbaa0qvz243qi3-libX11-1.7.2/lib/libX11.so.6)
/nix/store/vv368fk6vqq1k1hyl71w9cv6gf61vhw0-bcompare-4.4.0.25886/lib/beyondcompare/BCompare: /nix/store/90illc73xfs933d06daq6d41njs8yh66-glibc-2.32-37/lib/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/0kiykyrnrpfhmjwxwx89kxr20hmf5304-gcc-10.3.0-lib/lib/libstdc++.so.6)
/nix/store/vv368fk6vqq1k1hyl71w9cv6gf61vhw0-bcompare-4.4.0.25886/lib/beyondcompare/BCompare: /nix/store/90illc73xfs933d06daq6d41njs8yh66-glibc-2.32-37/lib/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/94iv84rv2d1cl0fk1l1mkmmbnxg7fyzz-glib-2.68.3/lib/libglib-2.0.so.0)
/nix/store/vv368fk6vqq1k1hyl71w9cv6gf61vhw0-bcompare-4.4.0.25886/lib/beyondcompare/BCompare: /nix/store/90illc73xfs933d06daq6d41njs8yh66-glibc-2.32-37/lib/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/nqvvv6zmj0a3nw8hisq3rkkl9pp2x052-freetype-2.11.0/lib/libfreetype.so.6)
/nix/store/vv368fk6vqq1k1hyl71w9cv6gf61vhw0-bcompare-4.4.0.25886/lib/beyondcompare/BCompare: /nix/store/90illc73xfs933d06daq6d41njs8yh66-glibc-2.32-37/lib/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/kjqi104glvb41nqznyr95s3fxkzsj4sl-fontconfig-2.13.94-lib/lib/libfontconfig.so.1)
/nix/store/vv368fk6vqq1k1hyl71w9cv6gf61vhw0-bcompare-4.4.0.25886/lib/beyondcompare/BCompare: /nix/store/90illc73xfs933d06daq6d41njs8yh66-glibc-2.32-37/lib/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/h83s9s9jm9y9gz8ikaxfh2588v5vycag-libXau-1.0.9/lib/libXau.so.6)
	linux-vdso.so.1 (0x00007ffd51bc4000)
	librt.so.1 => /nix/store/90illc73xfs933d06daq6d41njs8yh66-glibc-2.32-37/lib/librt.so.1 (0x00007f1b05794000)
	libbz2.so.1.0 => /nix/store/vv368fk6vqq1k1hyl71w9cv6gf61vhw0-bcompare-4.4.0.25886/lib/beyondcompare/libbz2.so.1.0 (0x00007f1b05781000)
	lib7z.so => /nix/store/vv368fk6vqq1k1hyl71w9cv6gf61vhw0-bcompare-4.4.0.25886/lib/beyondcompare/lib7z.so (0x00007f1b052fe000)
	libpthread.so.0 => /nix/store/90illc73xfs933d06daq6d41njs8yh66-glibc-2.32-37/lib/libpthread.so.0 (0x00007f1b052dd000)
	libc.so.6 => /nix/store/90illc73xfs933d06daq6d41njs8yh66-glibc-2.32-37/lib/libc.so.6 (0x00007f1b0511c000)
	libdl.so.2 => /nix/store/90illc73xfs933d06daq6d41njs8yh66-glibc-2.32-37/lib/libdl.so.2 (0x00007f1b05115000)
	libQt4Pas.so.5 => /nix/store/vv368fk6vqq1k1hyl71w9cv6gf61vhw0-bcompare-4.4.0.25886/lib/beyondcompare/libQt4Pas.so.5 (0x00007f1b04cba000)
	libX11.so.6 => /nix/store/7bkqfx75mf0ryhlay3fbaa0qvz243qi3-libX11-1.7.2/lib/libX11.so.6 (0x00007f1b04b75000)
	libz.so.1 => /nix/store/dc3r2nbhckwn41hq5vaxxbj7z0lqdwb1-zlib-1.2.11/lib/libz.so.1 (0x00007f1b04b58000)
	libstdc++.so.6 => /nix/store/0kiykyrnrpfhmjwxwx89kxr20hmf5304-gcc-10.3.0-lib/lib/libstdc++.so.6 (0x00007f1b04983000)
	libgcc_s.so.1 => /nix/store/0kiykyrnrpfhmjwxwx89kxr20hmf5304-gcc-10.3.0-lib/lib/libgcc_s.so.1 (0x00007f1b04967000)
	/nix/store/9bh3986bpragfjmr32gay8p95k91q4gy-glibc-2.33-47/lib/ld-linux-x86-64.so.2 => /nix/store/90illc73xfs933d06daq6d41njs8yh66-glibc-2.32-37/lib64/ld-linux-x86-64.so.2 (0x00007f1b057a1000)
	libQtGui.so.4 => /nix/store/vv368fk6vqq1k1hyl71w9cv6gf61vhw0-bcompare-4.4.0.25886/lib/beyondcompare/qt4/libQtGui.so.4 (0x00007f1b03bd2000)
	libQtCore.so.4 => /nix/store/vv368fk6vqq1k1hyl71w9cv6gf61vhw0-bcompare-4.4.0.25886/lib/beyondcompare/qt4/libQtCore.so.4 (0x00007f1b036c2000)
	libxcb.so.1 => /nix/store/ga1d9fvjgrhfr2i9daa3fzla7badj9av-libxcb-1.14/lib/libxcb.so.1 (0x00007f1b03696000)
	libm.so.6 => /nix/store/9bh3986bpragfjmr32gay8p95k91q4gy-glibc-2.33-47/lib/libm.so.6 (0x00007f1b03553000)
	libgthread-2.0.so.0 => /nix/store/94iv84rv2d1cl0fk1l1mkmmbnxg7fyzz-glib-2.68.3/lib/libgthread-2.0.so.0 (0x00007f1b0354e000)
	libglib-2.0.so.0 => /nix/store/94iv84rv2d1cl0fk1l1mkmmbnxg7fyzz-glib-2.68.3/lib/libglib-2.0.so.0 (0x00007f1b03418000)
	libfreetype.so.6 => /nix/store/nqvvv6zmj0a3nw8hisq3rkkl9pp2x052-freetype-2.11.0/lib/libfreetype.so.6 (0x00007f1b0334e000)
	libXrender.so.1 => /nix/store/4zm077aprw0wam4m8fcxnqkqd9l6kmpv-libXrender-0.9.10/lib/libXrender.so.1 (0x00007f1b03341000)
	libfontconfig.so.1 => /nix/store/kjqi104glvb41nqznyr95s3fxkzsj4sl-fontconfig-2.13.94-lib/lib/libfontconfig.so.1 (0x00007f1b032f3000)
	libXext.so.6 => /nix/store/bmg6gajc7mb9hvkq5cz0vlb052zc9j6a-libXext-1.3.4/lib/libXext.so.6 (0x00007f1b032de000)
	libXau.so.6 => /nix/store/h83s9s9jm9y9gz8ikaxfh2588v5vycag-libXau-1.0.9/lib/libXau.so.6 (0x00007f1b032d9000)
	libXdmcp.so.6 => /nix/store/aa5xb38ry37cq1w2rn9s900mmkl21x3v-libXdmcp-1.1.3/lib/libXdmcp.so.6 (0x00007f1b032d1000)
	libpcre.so.1 => /nix/store/6jr0k1iz0iv2y339qmbbs9hj1l1qif5y-pcre-8.44/lib/libpcre.so.1 (0x00007f1b03256000)
	libpng16.so.16 => /nix/store/4vgamrjcxl91w10j47rmd3j5851nj2wi-libpng-apng-1.6.37/lib/libpng16.so.16 (0x00007f1b0321c000)
	libexpat.so.1 => /nix/store/irsmdyfvxkh67f2c1r7gm8r7b3lirv63-expat-2.4.1/lib/libexpat.so.1 (0x00007f1b031eb000)
```

My suspicion is that this is due to a mismatch between the glibc version used by the `ldd` found on PATH and the glibc version used by bcompare.

### Steps To Reproduce
1. Install ldd from one Nixpkgs version
2. Install bcompare from a Nixpkgs version with a different glibc version
3. Run bcompare

### Expected behavior
bcompare runs successfully.

### Additional context
This is the code causing this in the bcompare launch script (bin/bcompare):

```
#check to see if we have all of the shared libraries.
if ldd "$EXEC" | grep -q "not found" ; then
   #if not then add our qt4 libraries in and see if that fixes problem
   export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$BC_LIB/qt4"
   if ldd "$EXEC" | grep -q "not found" ; then
       echo Some Shared Libraries were not found
       ldd "$EXEC"
        exit 1
   fi
fi
```

The fix is to either delete this code in the package, or resolve these "ldd" lookups at package build time.

### Notify maintainers
@ktor 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.100, NixOS, 21.05.3208.8dd8bd8be74 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(ksongnichols): `"nixpkgs-20.09pre224406.5f14d99efed"`
 - channels(sbaugh): `"nixpkgs-21.11pre313955.b72ad04a8a3"`
 - channels(root): `"nixos-21.05.3208.8dd8bd8be74, nixos-unstable-21.11pre316684.79c444b5bde"`
 - nixpkgs: `/home/sbaugh/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: bcompare
# a list of nixos modules affected by the problem
module:
```

**Comment by catern** [comment] 2021-10-08 21:01
@ktor for review

**Comment by veprbl** [comment] 2021-10-09 12:51
Likely a duplicate of #84043

**Comment by ktor** [comment] 2021-11-24 21:06
fixed in master

**Closed by ktor** 2021-11-24 21:06 UTC
Labels: 0.kind: bug
