### ISSUE TITLE
workrave fails to compile on nixos-unstable

### ISSUE THREAD

**Issue by uzytkownik** [NixOS/nixpkgs#178300] opened 2022-06-20 04:51 UTC
### Steps To Reproduce
Build workrave

### Build log
```
CPPFLAGS="-Wno-cast-function-type" CFLAGS="-g -O2" LDFLAGS="" CC="gcc" PKG_CONFIG="pkg-config" GI_HOST_OS="" DLLTOOL="false"  /nix/store/fzi3lmlx93alqmdi8ahxnspxrpchgr63-gobject-introspection-1.72.0-dev/bin/g-ir-scanner  --add-include-path=. --add-include-path=./../include --warn-all --include GObject-2.0 --include Gtk-3.0 --include cairo-1.0 --namespace=Workrave --nsversion=1.0 --libtool="/nix/store/zwjm0gln1vk7x1akpyz0yxjsd1yc46gi-bash-5.1-p16/bin/bash ../../../../libtool"  --include=GObject-2.0    --library=libworkrave-private-1.0.la  --cflags-begin  -I/nix/store/05i1vqf87i34paws4ssg7axm4d1ylm5p-glib-2.72.1-dev/include -I/nix/store/05i1vqf87i34paws4ssg7axm4d1ylm5p-glib-2.72.1-dev/include/glib-2.0 -I/nix/store/ckj0g3ycva2an405zf4mh4bvqhj44zr5-glib-2.72.1/lib/glib-2.0/include -I/nix/store/pf2zxhxpp6iz52xspkni9d4gxlrd8qsf-glibmm-2.66.4-dev/include/giomm-2.4 -I/nix/store/p1j2aphjaxvvklc42zhczv3rv2sws2g1-glibmm-2.66.4/lib/giomm-2.4/include -I/nix/store/pf2zxhxpp6iz52xspkni9d4gxlrd8qsf-glibmm-2.66.4-dev/include/glibmm-2.4 -I/nix/store/p1j2aphjaxvvklc42zhczv3rv2sws2g1-glibmm-2.66.4/lib/glibmm-2.4/include -I/nix/store/rp097s6ns75jwa1k0c01vss3pz6a2yvg-libsigc++-2.10.8/include/sigc++-2.0 -I/nix/store/rp097s6ns75jwa1k0c01vss3pz6a2yvg-libsigc++-2.10.8/lib/sigc++-2.0/include -I/nix/store/6s48s8wx9ib0c19jipqni09czv92fvzz-gtkmm-3.24.6-dev/include/gtkmm-3.0 -I/nix/store/ywh629a0swrz8pmhnhk6fb9dyd2knffc-gtkmm-3.24.6/lib/gtkmm-3.0/include -I/nix/store/6s48s8wx9ib0c19jipqni09czv92fvzz-gtkmm-3.24.6-dev/include/gdkmm-3.0 -I/nix/store/ywh629a0swrz8pmhnhk6fb9dyd2knffc-gtkmm-3.24.6/lib/gdkmm-3.0/include -I/nix/store/qjcx0f8ypilx5aihrp25ngnnvrrvg2s1-gtk+3-3.24.34-dev/include/gtk-3.0/unix-print -I/nix/store/qjcx0f8ypilx5aihrp25ngnnvrrvg2s1-gtk+3-3.24.34-dev/include/gtk-3.0 -I/nix/store/m3kfyz7p7h645nvi0s0qmnkix1z2vw55-atk-2.38.0-dev/include/atk-1.0 -I/nix/store/7q2wg81xgs5svgini137wr2smag1h3cg-cairo-1.16.0-dev/include/cairo -I/nix/store/0iyadd7k48mwx2g21rms14y6a8k13ca7-freetype-2.12.1-dev/include/freetype2 -I/nix/store/0iyadd7k48mwx2g21rms14y6a8k13ca7-freetype-2.12.1-dev/include -I/nix/store/k8gdc3ljmwh4ig16fbdng108zyi2asgy-gdk-pixbuf-2.42.8-dev/include/gdk-pixbuf-2.0 -I/nix/store/x4fambwvf7lbn9xjzws5cih98p9fwkzq-pango-1.50.7-dev/include/pango-1.0 -I/nix/store/7jwmq82i6scrw5b840bh2azvjpbv2m8y-harfbuzz-3.3.2-dev/include/harfbuzz -I/nix/store/fbn610scm90vl147zfs6nj997j2zwnr0-atkmm-2.28.2-dev/include/atkmm-1.6 -I/nix/store/cp4vs6hqnfk8wdql0hwmjdlnq1wgvxpq-atkmm-2.28.2/lib/atkmm-1.6/include -I/nix/store/jq9q4d4nxsk650g034nlk717n3vpvqp6-cairomm-1.14.3-dev/include/cairomm-1.0 -I/nix/store/8mpmpbgx79456yf73g59n63zr0hi08wx-cairomm-1.14.3/lib/cairomm-1.0/include -I/nix/store/blamm3s9pfb7m4x6wa0nk66v0hr095gb-pangomm-2.46.2-dev/include/pangomm-1.4 -I/nix/store/bf22yxyb5pgdirdml7swda55wanf02sj-pangomm-2.46.2/lib/pangomm-1.4/include -I./../include --cflags-end  timebar.c timerbox.c control.c ../include/timerbox.h ../include/timebar.h libworkrave-private-1.0.la --output Workrave-1.0.gir
Traceback (most recent call last):
  File "/nix/store/fzi3lmlx93alqmdi8ahxnspxrpchgr63-gobject-introspection-1.72.0-dev/bin/g-ir-scanner", line 94, in <module>
    from giscanner.utils import dll_dirs
  File "/nix/store/nq9bphg86yk33dz8wy0xcdxvx09haq7c-gobject-introspection-1.72.0/lib/gobject-introspection/giscanner/utils.py", line 29, in <module>
    from typing import Dict
  File "/nix/store/953sy41qycqbnjy33wcrcsw19qskhdl1-python2.7-typing-3.10.0.0/lib/python2.7/site-packages/typing.py", line 782, in <module>
    AnyStr = TypeVar('AnyStr', bytes, unicode)
NameError: name 'unicode' is not defined
make[5]: *** [/nix/store/fzi3lmlx93alqmdi8ahxnspxrpchgr63-gobject-introspection-1.72.0-dev/share/gobject-introspection-1.0/Makefile.introspection:156: Workrave-1.0.gir] Error 1
make[5]: Leaving directory '/build/source/frontend/applets/common/src'
make[4]: *** [Makefile:488: all-recursive] Error 1
make[4]: Leaving directory '/build/source/frontend/applets/common'
make[3]: *** [Makefile:488: all-recursive] Error 1
make[3]: Leaving directory '/build/source/frontend/applets'
make[2]: *** [Makefile:488: all-recursive] Error 1
make[2]: Leaving directory '/build/source/frontend'
make[1]: *** [Makefile:619: all-recursive] Error 1
make[1]: Leaving directory '/build/source'
make: *** [Makefile:521: all] Error 2
```

### Additional context
N/A

### Notify maintainers
Workrave: @prikhi 
GI: @bobby285271 @hedning @jtojnar @dasj19 @maxeaubrey 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.43, NixOS, 22.11 (Raccoon), 22.11pre386147.e0a42267f73`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jtojnar** [comment] 2022-06-20 11:34
See https://github.com/NixOS/nixpkgs/issues/167216, or https://github.com/NixOS/nixpkgs/issues/118452, of which this is likely a duplicate.

**Comment by joepie91** [comment] 2022-08-19 00:43
This is now making `workrave` uninstallable on 22.05. Whatever that workaround was meant to accomplish, it apparently didn't fix Workrave...

**Comment by jtojnar** [comment] 2022-08-20 07:24
That workaround was only for pycairo. The underlying problem was not fixed.

**Comment by kirillrdy** [comment] 2023-03-18 06:39
builds on latest master c1329a147a5fc2bb49367f6c2cd84bdfeccade43

```
 nix-build -A workrave
/nix/store/ivyx301p1c5fcc2yz5g62kpjx4grbkz4-workrave-1.10.50
```

**Comment by jtojnar** [comment] 2023-03-18 15:17
Closing as a duplicate of https://github.com/NixOS/nixpkgs/issues/118452, with the specific instance being worked around by https://github.com/NixOS/nixpkgs/commit/4f30fc6b4d94d1099934dd3629e31c8f658ae86d.

**Closed by jtojnar** 2023-03-18 15:17 UTC
Labels: 0.kind: build failure
