### ISSUE TITLE
python37Packages.tox not working

### ISSUE THREAD

**Issue by fkarg** [NixOS/nixpkgs#84353] opened 2020-04-05 13:01 UTC
**Describe the bug**
`tox` is a generic virtualenv management and test command line tool (more information [here](https://tox.readthedocs.io/en/latest/)), and installing the corresponding package (`python37Packages.tox`) does not give you a working version.

**To Reproduce**

    $ nix-shell -p python37Packages.tox --run 'tox --version'
    Traceback (most recent call last):
      File "/nix/store/81ql72znimxxgygy0zvcjp9x6cqy9igd-python3.7-tox-3.7.0/bin/.tox-wrapped", line 7, in <module>
        from tox import cmdline
      File "/nix/store/81ql72znimxxgygy0zvcjp9x6cqy9igd-python3.7-tox-3.7.0/lib/python3.7/site-packages/tox/__init__.py", line 32, in <module>
        from .session import cmdline  # noqa
      File "/nix/store/81ql72znimxxgygy0zvcjp9x6cqy9igd-python3.7-tox-3.7.0/lib/python3.7/site-packages/tox/session.py", line 19, in <module>
        import pkg_resources
    ModuleNotFoundError: No module named 'pkg_resources'

**Expected behavior**
A working `tox` package.

**Metadata**
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.28, NixOS, 19.09.2345.6d445f8398d (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-19.09.2345.6d445f8398d"`
 - channels(fkarg): `"nixos-19.09.2284.bf7c0f0461e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by petersjt014** [comment] 2020-04-08 04:53
I think this might be a common-ish python problem. I just tried to use the package `greg` and:

````
Traceback (most recent call last):
  File "/nix/store/m3jh6lp8p3is9x7p2jdlxvif4v2kd6f4-greg-0.4.7/bin/.greg-wrapped", line 7, in <module>
    from greg.parser import main
  File "/nix/store/m3jh6lp8p3is9x7p2jdlxvif4v2kd6f4-greg-0.4.7/lib/python3.7/site-packages/greg/parser.py", line 22, in <module>
    import greg.commands as commands
  File "/nix/store/m3jh6lp8p3is9x7p2jdlxvif4v2kd6f4-greg-0.4.7/lib/python3.7/site-packages/greg/commands.py", line 24, in <module>
    import greg.classes as c
  File "/nix/store/m3jh6lp8p3is9x7p2jdlxvif4v2kd6f4-greg-0.4.7/lib/python3.7/site-packages/greg/classes.py", line 32, in <module>
    from pkg_resources import resource_filename
ModuleNotFoundError: No module named 'pkg_resources'
````

Same error at the bottom, and the first line also pertains to a wrapper.
This might warrant an issue/later fix higher up the food chain.

**Comment by kalekseev** [comment] 2020-06-25 21:07
Can't reproduce tox problem in master so I think that can be closed.
dosage works too, greg fixed in https://github.com/NixOS/nixpkgs/pull/91512

**Comment by bjornfor** [comment] 2020-12-01 12:48
Works on release-20.09 and master. Closing.

```
$ nix-shell -p python37Packages.tox --run 'tox --version' -I nixpkgs=$PWD
3.19.0 imported from /nix/store/v1cddil55g5nmwfs9hijpdfmlbsimvg4-python3.7-tox-3.19.0/lib/python3.7/site-packages/tox/__init__.py
```

(Also tested the default (python3Packages) and that works too.)

**Closed by bjornfor** 2020-12-01 12:48 UTC
Labels: 0.kind: bug, 6.topic: python
