### ISSUE TITLE
Package request: legacylauncher / TL legacy

### ISSUE THREAD

**Issue by Sk7Str1pe** [NixOS/nixpkgs#350327] opened 2024-10-21 19:57 UTC
**Project description**

minimal minecraft launcher
**Metadata**

* homepage URL: https://llaun.ch/ru
* source URL: https://llaun.ch/source
* license: ??? mit ???
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Frontear** [comment] 2024-10-21 23:26
This could easily get us into legal trouble with Mojang, so I'm opposed to such a thing.

**Comment by Sk7Str1pe** [comment] 2024-10-22 13:44
why prismlauncher packaged then

**Comment by Frontear** [comment] 2024-10-22 16:37
Prism isnt a cracked launcher. That would be the main difference

**Comment by FliegendeWurst** [comment] 2024-10-22 18:06
Duplicate of #336763

**Closed** 2024-10-22 18:06 UTC
Labels: 0.kind: packaging request
