### ISSUE TITLE
plugin "fancy" in Claws Mail is not working

### ISSUE THREAD

**Issue by wedens** [NixOS/nixpkgs#10421] opened 2015-10-16 16:50 UTC
I have `enablePluginFancy` enabled in my config:
```nix
    packageOverrides = pkgs: {
     clawsMail = pkgs.clawsMail.override { enablePluginFancy = true; };
    };
```
after loading "Fancy" plugin and opening html email, it show page source instead of rendering html.

P.S.: I don't have this issue in arch linux.

/cc @khumba

**Comment by khumba** [comment] 2015-10-16 17:21
Hi @wedens, I'm assuming you're running NixOS and not just Nix on Arch.  Can you please post the output of the following:

    $ nixos-version
    $ sudo nix-channel --list
    $ nix-store -qR $(which claws-mail) | grep webkit
    $ grep -C3 plugin ~/.claws-mail/clawsrc
    $ cat ~/.claws-mail/clawsrc | perl -ne 'if (/^\[/) {$p = !!/\[fancy]/i;} if ($p) {print}'

Does it show the source for all HTML emails?  If you start Claws from a terminal, does it print anything when you try to open the an HTML message for the first time?

**Comment by khumba** [comment] 2015-10-16 17:25
(edit: commands improved slightly)

**Comment by wedens** [comment] 2015-10-16 18:05
```
~ ❯ nixos-version
15.09.597.71e29b4 (Dingo)
~ ❯ sudo nix-channel --list 
nixos https://nixos.org/channels/nixos-15.09
~ ❯ ls -l $(which claws-mail)
lrwxrwxrwx 1 root nixbld 76 Jan  1  1970 /run/current-system/sw/bin/claws-mail -> /nix/store/0dlf3wh0g3lqmkavvarybyx8nfdsprdv-claws-mail-3.11.1/bin/claws-mail*
~ ❯ nix-store -qR $(which claws-mail) | grep webkit
/nix/store/j0mdz0f23f0m7ni8jwxf72p0f87hzam0-webkitgtk-2.4.9
~ ❯ grep -C3 plugin ~/.claws-mail/clawsrc
display_header=1
display_xface=1
render_html=1
invoke_plugin_on_html=1
promote_html_part=0
line_space=2
never_send_retrcpt=0
--
addressbookeditpersonwin_height=320
addressbookeditgroupwin_width=580
addressbookeditgroupwin_height=340
pluginswin_width=423
pluginswin_height=300
prefswin_width=700
prefswin_height=550
folderitemwin_width=500
--
[Plugins_Common]

[Plugins_GTK2]
/nix/store/wyspdbyhimbkyk9jwhycvsri3v08im1r-claws-mail-3.11.1/lib/claws-mail/plugins/notification.so
/nix/store/0dlf3wh0g3lqmkavvarybyx8nfdsprdv-claws-mail-3.11.1/lib/claws-mail/plugins/fancy.so

[NotificationPlugin]
include_mail=1
--
enable_images=1
enable_remote_content=1
enable_scripts=0
enable_plugins=0
open_external=1
zoom_level=100
enable_java=0
~ ❯ cat ~/.claws-mail/clawsrc | perl -ne 'if (/^\[/) {$p = !!/\[fancy]/i;} if ($p) {print}'
[fancy]
enable_images=1
enable_remote_content=1
enable_scripts=0
enable_plugins=0
open_external=1
zoom_level=100
enable_java=0
enable_proxy=0
proxy_server=http://SERVERNAME:PORT
stylesheet=

```

**Comment by khumba** [comment] 2015-10-16 18:21
Thanks!  I'll have to look into this more later.  The one thing that jumps out at me is that you're loading the notification plugin from an old version of Claws (`/nix/store/wysp...`), which might cause some weirdness with dynamic linking.  I'd recommend changing the `[Plugins_GTK2]` section to have version-agnostic paths (e.g. `/run/current-system/sw/lib/claws-mail/plugins/...`).  It's a pain to do this when loading the plugins through the UI, because you can tell the file picker to use the `/run/current-system` path, but the next time you open the dialog, it's resolved the symlinks and is using the `/nix/store` path so you have to navigate all over again.

I'm not entirely sure Claws how uses this section though.  I share `~/.claws-mail` between Gentoo and NixOS so it only had `/usr/lib64/claws-mail/plugins` paths in it, but the NixOS Claws still found its plugins somehow (maybe falling back to its install dir; if this is the case then this section should probably just not be used on Nix).

Updating my system to where you are on the channel now, we'll see if that causes problems :).

**Comment by wedens** [comment] 2015-10-16 18:26
Thanks for looking into this!
changing paths haven't changed anything :(

**Comment by khumba** [comment] 2015-10-17 20:43
Thanks for testing that.  I've now reproduced this by creating a new minimal NixOS install with only Claws and basic X stuff present.  Now to determine the key difference between that and my main NixOS system.

**Comment by khumba** [comment] 2015-10-17 21:34
Very sorry about this, this is fixed in master but is not on the release-15.09 branch.  `shared_mime_info` needs to be a dependency of Claws.  @vcunat, @lethalman, would it be possible to cherry-pick 268b4d5 onto release-15.09 to fix this issue, and also c39a557 and 4eb5068  to fix subsequent file conflicts with `hicolor_icon_theme` and `shared_mime_info`, please?

**Comment by khumba** [comment] 2015-10-17 21:36
@wedens, as a workaround, install shared_mime_info manually.

**Comment by wedens** [comment] 2015-10-18 03:57
@khumba adding `shared_mime_info` to `systemPackages` hasn't solved the issue :(

**Comment by vcunat** [comment] 2015-10-18 06:54
Pushed. I guess changing `systemPackages` wasn't enough because `mime.patch` is also required.

**Comment by khumba** [comment] 2015-10-18 07:14
@vcunat thanks!  Hopefully that's the case, since I haven't looked into what code is actually failing.  On my test system, `systemPackages = [... shared_mime_info]` was sufficient :/.

**Comment by wedens** [comment] 2015-10-18 07:23
how can I get this changes? just update my current channel?

**Comment by vcunat** [comment] 2015-10-18 07:42
No, channels [lag behind](https://nixos.org/wiki/FAQ#What_are_channels_and_how_they_get_updated.3F), so it will take some time to get there (hours, days, difficult to guess). In the meantime, you can build from git, branch release-15.09.

**Comment by wedens** [comment] 2015-10-18 09:04
sorry, NixOS newbie here. should I do `nix-env -f https://github.com/NixOS/nixpkgs/archive/release-15.09.zip -iA clawsMail` ? 
what about
```
    packageOverrides = pkgs: {
     clawsMail = pkgs.clawsMail.override { enablePluginFancy = true; };
    };
```
I have in my `configuration.nix`?

**Comment by vcunat** [comment] 2015-10-18 09:11
Yes, except that `packageOverrides` from `configuration.nix` don't affect `nix-env` (sadly) which is configured separately in `~/.nixpgs/config.nix`. Example for that is on the wiki: https://nixos.org/wiki/Nix_Modifying_Packages#Creating_a_config.nix_File.

**Comment by wedens** [comment] 2015-10-18 09:19
It works! thanks @vcunat, @khumba

**Comment by vcunat** [comment] 2015-10-18 09:26
:-)

**Comment by wedens** [comment] 2015-10-18 09:36
:( there is another problem now. It unable to load something via `https` `TLS/SSL support not available; install glib-networking`

**Comment by vcunat** [comment] 2015-10-18 09:53
@khumba: sounds like it needs a wrapper setting ``--prefix GIO_EXTRA_MODULES : ${glib_networking}/lib/gio/modules``.

**Comment by khumba** [comment] 2015-10-21 00:42
Trying to take a look at this, but now Fancy's back to just showing source for me...  Wat.

**Comment by wedens** [comment] 2015-10-21 03:35
@khumba same. after installing from updated channel :confused:

**Comment by khumba** [comment] 2015-10-21 05:38
So what it seems like is that even with the patches, I have to add `shared_mime_info` explicitly to `systemPackages` for Fancy to work at all.  It's not enough for it to be a dependency.  Odd, perhaps Claws is looking in system paths still (although I don't know yet what for).  (Didn't check if it worked in a user environment vs. `systemPackages`.)

For the TLS/SSL message, I created a test message containing some `<img src="https://...">`s and don't see that message, but nor do HTTPS images load.  @vcunat's suggestion worked, although glib crashed without access to gsettings schemas so I also added `gsettings_desktop_schemas` via `wrapGAppsHook` (<- is it right for me to use this for a non-Gnome app?).  khumba@a33d38c is the patch.  @wedens, would you be interested in testing this out?  (Fetch and checkout that commit in a Git repo then `nix-env -f /path/to/repo.git -iA clawsMail`.)

**Comment by wedens** [comment] 2015-10-21 05:48
@khumba sure, I'll try it (if it won't cause webkit rebuild as one of my attempts to install claws-mail from repo)

**Comment by khumba** [comment] 2015-10-21 05:52
Ha :).  It shouldn't, I deliberately tried to avoid that.  Thanks.

**Comment by vcunat** [comment] 2015-10-21 07:57
`wrapGApps` handles mainly glib stuff (and some gstreamer); I think it's suitable to use it there.

**Comment by wedens** [comment] 2015-10-21 16:05
@khumba 
1. as you said,  adding `shared_mime_info` to `systemPackages` solved the problem of Fancy not working at all.
2. it works when installed via `nix-env` without `shared_mime_info`
3. derivation from your repo works fine with https ;)

**Comment by wedens** [comment] 2015-11-12 06:19
@khumba can you send a PR with your fix?

**Comment by khumba** [comment] 2015-11-12 07:05
Yes; I got heavily distracted, apologies.  Will do.

**Comment by khumba** [comment] 2015-11-17 04:35
PRs created.  I'm still confused by shared-mime-info.  Some Claws
builds I have work without it being in the environment, and some
don't.  In all cases, running Claws with --debug shows that the Webkit
viewer is being created, at least.

**Comment by wedens** [comment] 2015-11-17 10:59
@khumba thanks

**Comment by wedens** [comment] 2015-12-06 12:41
@khumba for some reason in master plugin stopped working completely and just displays raw html text (I have `shared_mime_info` in `systemPackages`

**Comment by khumba** [comment] 2015-12-06 18:02
@wedens I'll investigate when I get back home on Monday or Tuesday, am out of town right now.

**Comment by khumba** [comment] 2015-12-09 04:12
When it displays raw text, do you at least see the toolbar that fancy adds to the bottom of the message pane, below the HTML source?  I'm not sure the problem is with Claws, since (on release-15.09) it seems to be loading webkitgtk successfully in its eyes when this happens.  I suspect something is missing from webkitgtk2 (cc maintainer @iyzsong).  For example maybe it's relying on XDG_DATA_DIRS instead of looking at shared_mime_info directly.  (AFAICT, the only difference between having shared_mime_info in my user profile and not is the directories it creates in ~/.nix-profile, since I'm not logging out and back in after installing it; and the only things shared_mime_info provides are a bin/ and a share/.)

I'll try poking at webkitgtk2, experimenting with it will take time though.  I've also got a lot of building to do to be able to check the current state of master, since the bash-4.3-42 patch hash changed :).

**Comment by khumba** [comment] 2015-12-09 04:15
> and the only things shared_mime_info provides are a bin/ and a share/.

...in addition to the set of things in the environment that could rely on this being very small:

    [khumba@nixos:~]$ set | grep --color=force -Fe .nix-profile/bin -e .nix-profile/share
    INFOPATH=/home/khumba/.nix-profile/info:/home/khumba/.nix-profile/share/info:/nix/var/nix/profiles/default/info:/nix/var/nix/profiles/default/share/info:/run/current-system/sw/info:/run/current-system/sw/share/info
    PATH=/home/khumba/bin:/var/setuid-wrappers:/home/khumba/.nix-profile/bin:/home/khumba/.nix-profile/sbin:/home/khumba/.nix-profile/lib/kde4/libexec:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:/nix/var/nix/profiles/default/lib/kde4/libexec:/run/current-system/sw/bin:/run/current-system/sw/sbin:/run/current-system/sw/lib/kde4/libexec
    TERMINFO_DIRS=/home/khumba/.nix-profile/share/terminfo:/nix/var/nix/profiles/default/share/terminfo:/run/current-system/sw/share/terminfo
    XDG_DATA_DIRS=/home/khumba/.nix-profile/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share
    
    [khumba@nixos:~/claws.git]$ git grep XDG_DATA
    (nada)

**Comment by wedens** [comment] 2015-12-09 05:18
@khumba yeah. statusbar is visible

**Comment by khumba** [comment] 2015-12-09 06:00
Okay, good.  So, still on release-15.09, adding shared_mime_info to XDG_DATA_DIRS via a wrapper fixes this bug's original issue of needing it to be installed.

    postInstall = ''
      wrapProgram $out/bin/claws-mail --prefix XDG_DATA_DIRS : ${shared_mime_info}/share
      ...existing stuff...
    '';

I'm building master currently to check the state of things there, but this seems like a good fix for now, although I don't know why it works.  If this works for you, @wedens, I'll create a PR.

**Comment by wedens** [comment] 2015-12-13 06:24
It works after removing `wrapGAppsHook` and 
```
  postInstall = ''
    wrapProgram $out/bin/claws-mail \
      --prefix XDG_DATA_DIRS : "${shared_mime_info}/share:$XDG_ICON_DIRS:$GSETTINGS_SCHEMAS_PATH"

    mkdir -p $out/share/applications
    cp claws-mail.desktop $out/share/applications
  '';
```

**Comment by fpletz** [comment] 2015-12-13 15:38
@wedens Thanks for the hint! I opened a PR that wraps `XDG_DATA_DIRS` with `wrapGAppsHook`. The fancy plugin now works for me.

**Closed** 2015-12-13 21:52 UTC
