### ISSUE TITLE
KDE 5 applications do not have menu icons

### ISSUE THREAD

**Issue by viric** [NixOS/nixpkgs#20696] opened 2016-11-24 21:32 UTC
I'm trying to run kdenlive from NixOS 16.09, and it does not have most of the icons. The same happens to kcalc, so I guess it is a general KDE5 application problem.

I enabled desktopManager.kde5.enable in nixos, and that has not given any improvement. I'm not using KDE 5 as desktopmanager, though. I just run the dwm window manager.

I guess there is one package missing somewhere (system profile, the kde5 wrapper, ...) but I don't know which one. Any idea?

cc @ttuegel

**Comment by ttuegel** [comment] 2016-11-28 14:21
> I guess there is one package missing somewhere (system profile, the kde5 wrapper, ...) but I don't know which one. Any idea?

`kdeWrapper` is designed so that it is not necessary to install any packages into the profile. I checked the wrapper for `kcalc`, and the wrapper does set `XDG_DATA_DIRS` correctly, so the Breeze icons should be found. However, I cannot reproduce this issue yet; I will try again from a clean VM later.

**Comment by ttuegel** [comment] 2016-11-29 13:24
I can't reproduce this in a VM. Could you provide a configuration to reproduce this?

**Comment by ttuegel** [comment] 2016-12-21 16:47
I am closing this issue as unreproducible.

**Closed by ttuegel** 2016-12-21 16:47 UTC
Labels: 6.topic: qt/kde

**Comment by vcunat** [comment] 2016-12-22 11:01
Maybe it only happens if you install KDE5 but don't run it ATM (as reported).

**Comment by ttuegel** [comment] 2016-12-22 14:01
> Maybe it only happens if you install KDE5 but don't run it ATM (as reported).

That's what I tried to do in a clean VM installation, and I couldn't reproduce it.
