### ISSUE TITLE
KDE wallet crashes on start (plasma5)

### ISSUE THREAD

**Issue by Mindavi** [NixOS/nixpkgs#77290] opened 2020-01-08 00:16 UTC
**Describe the bug**
During boot, kwalletd5-wrap dumps core: `systemd-coredump[1204]: Process 1095 (.kwalletd5-wrap) of user 1000 dumped core.`
This prevents kde wallet to authenticate together with my session, and I need to re-enter the password after logging in.

**To Reproduce**
1. Configure system with kde plasma5 and sddm
2. Boot it

**Expected behavior**

kdewallet should not crash on boot

**Additional context**

Probably related to #68316.
@tenaf0 in that thread seems to have the same issue.

Display manager info:

- sddm
- plasma5

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.8-hardened, NixOS, 20.03pre208261.9beb0d1ac2e (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(rick): `""`
 - channels(root): `"nixos-20.03pre208261.9beb0d1ac2e, nixpkgs-20.03pre207249.7e8454fb856"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by matthewbauer** [comment] 2020-01-10 19:41
I'm getting the same thing on nixos-unstable. We probably need to run a git bisect to figure out when this originated.

**Comment by Mindavi** [comment] 2020-02-12 22:48
I wouldn't mind picking this up, however I'm not sure how to do this exactly. Could you give me some pointers @matthewbauer ? (or anyone else ofc)

**Comment by matthewbauer** [comment] 2020-02-12 23:08
> I wouldn't mind picking this up, however I'm not sure how to do this exactly. Could you give me some pointers @matthewbauer ? (or anyone else ofc)

To be honest, I'm as confused as you are. `coredumpctl info PID` and `coredumpctl debug PID` will give you some more information. It looks like the same thing as https://github.com/NixOS/nixpkgs/issues/68316 where QT_PLUGIN_PATH / QML2_IMPORT_PATH / XDG_DATA_DIRS / XDG_CONFIG_DIRS is set to the wrong value. Perhaps try replacing wrapQtApp with a `export XDG_DATA_DIRS=...` header in https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/plasma-5/kwallet-pam.nix#L11.

**Comment by Mindavi** [comment] 2020-02-13 08:16
How to install a package from my local repository? `nix-build ./nixpkgs -A kwallet-pam` works, but what's next? Should I install everything from my local repo using `nixos-rebuild -I nixpkgs=$NIXPKGS switch` while trying to find why the package crashes on every reboot? Or is there an option to only install the kwallet-pam package with different versions?

**Comment by Mindavi** [comment] 2020-02-13 10:25
Might have something to do with this update: https://cgit.kde.org/kwalletmanager.git/commit/?id=00dfdbecf60609d5a2a354d8cfadf152dc43b8d4

**Comment by worldofpeace** [comment] 2020-04-03 20:44
I believe @ttuegel mentioned in the GO / NO-GO that it's likely fixed in a plasma update (think it was said it works on master).
So perhaps a specific patch will be backported.

**Comment by Mindavi** [comment] 2020-04-03 21:10
I'm not sure, but I'm running unstable and it's not fixed there.

```
rick@nixos-asus:~$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.9-hardened, NixOS, 20.09pre217537.d96bd3394b7 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(rick): `""`
 - channels(root): `"nixos-20.09pre218613.ae6bdcc5358, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by worldofpeace** [comment] 2020-04-03 22:06
(not sure if what was mentioned was merged to staging)

**Comment by Mindavi** [comment] 2020-04-04 23:11
Mm, just built a master (`167ed907498ed6cd4cff1d5045fa9164d5ed8f1c`) configuration, but the issue still persists.

<details><summary>the used system config</summary>

```
# configuration.nix
# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.kernelPackages = pkgs.linuxPackages_latest_hardened;

  networking.hostName = "nixos-asus-testing"; # Define your hostname.
  networking.networkmanager.enable = true;

  # The global useDHCP flag is deprecated, therefore explicitly set to false here.
  # Per-interface useDHCP will be mandatory in the future, so this generated config
  # replicates the default behaviour.
  networking.useDHCP = false;
  #networking.interfaces.enp3s0f1.useDHCP = true;
  networking.interfaces.wlp2s0.useDHCP = true;

  # Set your time zone.
  time.timeZone = "Europe/Amsterdam";

  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
    vim
    htop
  ];
  
  programs.bash.enableCompletion = true;

  networking.firewall.allowedTCPPorts = [ ];
  networking.firewall.allowedUDPPorts = [ ];
  # Or disable the firewall altogether.
  networking.firewall.enable = true;

  # Enable sound.
  sound.enable = false;

  # Enable the X11 windowing system.
  services.xserver.enable = true;
  services.xserver.layout = "us";

  # Enable touchpad support.
  services.xserver.libinput.enable = true;

  # Enable the KDE Desktop Environment.
  services.xserver.displayManager.sddm.enable = true;
  services.xserver.desktopManager.plasma5.enable = true;

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.rick = {
    isNormalUser = true;
    home = "/home/rick";
    extraGroups = [ "wheel" "networkmanager" "dialout" "docker"];
    initialPassword = "rikkert";
  };

  # This value determines the NixOS release with which your system is to be
  # compatible, in order to avoid breaking some software such as database
  # servers. You should change this only after NixOS release notes say you
  # should.
  system.stateVersion = "19.09"; # Did you read the comment?

}
```

```
# hardware-configuration.nix
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/cd1f909e-dbc4-4293-9df5-5dd216f38f7f";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B47E-DAC3";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/377e5198-807d-4aee-8a52-f3f6b9a9e41f"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
```

</details>

**Comment by ttuegel** [comment] 2020-04-05 15:26
> I believe @ttuegel mentioned in the GO / NO-GO that it's likely fixed in a plasma update (think it was said it works on master).

Sorry, someone said that it worked on `master`, and I said _if_ it works on `master`, then it was the Plasma version bump because nothing addressing this issue has been merged.

**Comment by matthewbauer** [comment] 2020-04-08 05:18
A fix is available at https://github.com/NixOS/nixpkgs/pull/84689. If someone else can verify it works, I think we can merge it to master and then release-20.03.

**Comment by Mindavi** [comment] 2020-04-08 06:14
Mm, it seems like it's still happening for me.

Just to be sure, here the steps I've taken to verify:

- Clone your nixpkgs at branch fix-77290 (40deb26f3f3d95daf5b047c71a6242bfdeac2fbe)
- Use the configuration listed below to build a vm with `nixos-rebuild -I nixpkgs=/the/local/copy/of/fixed/nixpkgs -I nixos-config=configuration.nix build-vm`
- After the build, copy `result/bin/run-nixos-testing-vm` to the working directory and change the max memory from `384` to `2048`, change the max processor cores from `1` to `4` (otherwise it's too slow to work with)
- Start the VM, login (see default password in config) and check `journalctrl -p warn`
- The error `kwalletd5-wrap` dumped core` is still visible in the log

<details>
<summary>The used configuration</summary>

```
$ cat configuration.nix 
# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

{
  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.kernelPackages = pkgs.linuxPackages_latest_hardened;

  networking.hostName = "nixos-testing"; # Define your hostname.

  # The global useDHCP flag is deprecated, therefore explicitly set to false here.
  # Per-interface useDHCP will be mandatory in the future, so this generated config
  # replicates the default behaviour.
  networking.useDHCP = false;

  # Set your time zone.
  time.timeZone = "Europe/Amsterdam";

  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
    vim
    htop
  ];
  
  programs.bash.enableCompletion = true;
  
  # Enable the X11 windowing system.
  services.xserver.enable = true;
  services.xserver.layout = "us";

  # Enable touchpad support.
  services.xserver.libinput.enable = true;

  # Enable the KDE Desktop Environment.
  services.xserver.displayManager.sddm.enable = true;
  services.xserver.desktopManager.plasma5.enable = true;

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.rick = {
    isNormalUser = true;
    home = "/home/rick";
    extraGroups = [ "wheel" "networkmanager" ];
    initialPassword = "rikkert";
  };

  # This value determines the NixOS release with which your system is to be
  # compatible, in order to avoid breaking some software such as database
  # servers. You should change this only after NixOS release notes say you
  # should.
  system.stateVersion = "19.09"; # Did you read the comment?
}
```

</details>

**Comment by matthewbauer** [comment] 2020-04-08 20:06
Ugh - it looks like I was missing some things. I definitely had it working at one point. Will retry to verify the fix actually works.

**Comment by semaj** [comment] 2020-04-08 20:19
I have nothing productive to add here other than how excited I am at the prospect of having this fixed! Re-entering my password every time I log in is extremely frustrating.

**Comment by matthewbauer** [comment] 2020-04-08 20:28
> Mm, it seems like it's still happening for me.
> 
> Just to be sure, here the steps I've taken to verify:
> 
> * Clone your nixpkgs at branch fix-77290 ([40deb26](https://github.com/NixOS/nixpkgs/commit/40deb26f3f3d95daf5b047c71a6242bfdeac2fbe))
> * Use the configuration listed below to build a vm with `nixos-rebuild -I nixpkgs=/the/local/copy/of/fixed/nixpkgs -I nixos-config=configuration.nix build-vm`
> * After the build, copy `result/bin/run-nixos-testing-vm` to the working directory and change the max memory from `384` to `2048`, change the max processor cores from `1` to `4` (otherwise it's too slow to work with)
> * Start the VM, login (see default password in config) and check `journalctrl -p warn`
> * The error `kwalletd5-wrap dumped core` is still visible in the log
> 
> The used configuration
> Just as a sidenote, on my own system this is an issue because some applications immediately need the wallet to be unlocked. Of course, because the set of applications in the VM is limited (on purpose), it doesn't show the kwallet login screen immediately. However, I'm fairly certain it will show if I'd start a system that needs the keychain unlocked.

Thanks for testing! I think the issue is fixed in https://github.com/NixOS/nixpkgs/commit/8021f0a4a54b03bc9cd1f4c1d40e00fa28ec6ad9. If you could try that out it would be greatly appreciated.

**Comment by mdevlamynck** [comment] 2020-04-09 10:26
I tested 8021f0a and beside the build issue (I needed to put back kwallet in the buildInputs), the wallet was correctly unlocked after login :)

**Closed** 2020-04-09 14:49 UTC
Labels: 0.kind: bug, 6.topic: qt/kde

**Comment by mrkkrp** [comment] 2020-09-21 17:37
I tried today to move my NixOS pin to 441a7da8080352881bb52f85e910d8855e83fc55 and ran into the same issue.

**Comment by schlichtanders** [comment] 2021-04-20 10:16
just made a fresh nixos install and I also seem to get this problem... kdewallet wants to have a password
some help about how to investigate, workaround or fix it would be highly appreciated

**Comment by schlichtanders** [comment] 2021-04-21 07:23
I have solved my issue which finally was something totally different, but may still help others who run into the same:
I setup my user with initialpassword and then changed the user password with `passwd` utility, 
and it seems that because of this my kwallet's password was still set to the initial password (it took me very long to figure this out :D) and wasn't changed to the new password.

After entering kwallet's password correctly (I was truly surprised that there was a correct password), I could change it to my new password and everything worked, including auto-log-in at startup time.

Maybe there should be a warning with the option initialpassword mentioning this rather critical side-effect of initializing the kwallet (and maybe other things as well).
Hope it helps some.
