### ISSUE TITLE
`haskell.lib.justStaticExecutables` doesn't seem to reduce closure size

### ISSUE THREAD

**Issue by vaibhavsagar** [NixOS/nixpkgs#42095] opened 2018-06-16 11:03 UTC
## Issue description

`haskell.lib.justStaticExecutables` doesn't seem to reduce closure size as reported by `du -sch $(nix-store -qR $path)`. Is this the expected behaviour, and if so what is the way to remove unneeded dependencies to reduce closure size?

### Steps to reproduce

```bash
$ du -sch $(nix-store -qR $(nix-build -E "with import <nixpkgs> {}; pkgs.haskell.lib.justStaticExecutables pkgs.haskellPackages.pandoc"))
<...>
1.1G    /nix/store/hjvv3ayhyddz2piydw8rra85pczbsz9j-ghc-8.2.2
<...>
2.0G    total
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.47, NixOS, 18.03.132645.43c77db3aa5 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(vaibhavsagar): `""`
 - channels(root): `"nixos-18.03.132645.43c77db3aa5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by vaibhavsagar** [comment] 2018-06-16 11:12
I've tried this with `scotty` and `hakyll` and in that case it does seem to reduce the closure size. Maybe this is something `pandoc` specific?

**Comment by vaibhavsagar** [comment] 2018-06-16 11:30
This looks like a duplicate of https://github.com/NixOS/nixpkgs/issues/34376, closing.

**Comment by lf-** [comment] 2022-10-05 23:06
This *is* a duplicate of that issue for pandoc (that issue is scoped to just pandoc, however!), but strip does not seem to fix it on my aarch64-darwin, while building a large (currently proprietary) binary with GHC-9.2.4.

Nixpkgs commit d6490a0bd9dfb298fcd8382d3363b86870dc7340

Paths to libraries that are affected (big app!):

```
/nix/store/cjwzzk4lwkzhl5d81ycxll46v7lkh04q-warp-3.3.21/etc
/nix/store/cjwzzk4lwkzhl5d81ycxll46v7lkh04q-warp-3.3.21/libexec/aarch64-osx-ghc-9.2.4/warp-3.3.21
/nix/store/cjwzzk4lwkzhl5d81ycxll46v7lkh04q-warp-3.3.21/share/aarch64-osx-ghc-9.2.4/warp-3.3.21
/nix/store/cjwzzk4lwkzhl5d81ycxll46v7lkh04q-warp-3.3.21/lib/ghc-9.2.4/aarch64-osx-ghc-9.2.4
/nix/store/cjwzzk4lwkzhl5d81ycxll46v7lkh04q-warp-3.3.21/lib/ghc-9.2.4/aarch64-osx-ghc-9.2.4/warp-3.3.21-KgMrgV3QBolBwpD4
ttB2Wl
/nix/store/cjwzzk4lwkzhl5d81ycxll46v7lkh04q-warp-3.3.21/bin
/nix/store/rpva2yd70cisdq7a0w88b1s834m39llz-hs-opentelemetry-sdk-0.0.3.3/etc
/nix/store/rpva2yd70cisdq7a0w88b1s834m39llz-hs-opentelemetry-sdk-0.0.3.3/libexec/aarch64-osx-ghc-9.2.4/hs-opentelemetry-
sdk-0.0.3.3
/nix/store/rpva2yd70cisdq7a0w88b1s834m39llz-hs-opentelemetry-sdk-0.0.3.3/share/aarch64-osx-ghc-9.2.4/hs-opentelemetry-sd
k-0.0.3.3
/nix/store/rpva2yd70cisdq7a0w88b1s834m39llz-hs-opentelemetry-sdk-0.0.3.3/lib/ghc-9.2.4/aarch64-osx-ghc-9.2.4
/nix/store/rpva2yd70cisdq7a0w88b1s834m39llz-hs-opentelemetry-sdk-0.0.3.3/lib/ghc-9.2.4/aarch64-osx-ghc-9.2.4/hs-opentele
metry-sdk-0.0.3.3-4okP8RUIhRPJ82kxo9f3AG
/nix/store/rpva2yd70cisdq7a0w88b1s834m39llz-hs-opentelemetry-sdk-0.0.3.3/bin
```

**Closed** 2022-10-05 23:17 UTC
Labels: 6.topic: haskell
