### ISSUE TITLE
marksman

### ISSUE THREAD

**Issue by pinkcreeper100** [NixOS/nixpkgs#202562] opened 2022-11-23 17:34 UTC
**Project description**
marksman is a language server protocol for markdown documents

**Metadata**

* homepage URL: https://github.com/artempyanykh/marksman
* source URL: https://github.com/artempyanykh/marksman
* license: MIT
* platforms: Unix, Linux, Darwin

**Comment by pinn3** [comment] 2022-11-24 11:20
Duplicate of https://github.com/NixOS/nixpkgs/issues/184873

**Comment by pinkcreeper100** [comment] 2022-11-24 14:21
Understood, I should have checked

**Closed** 2022-11-24 14:20 UTC
Labels: 0.kind: packaging request
