### ISSUE TITLE
Cannot mix incompatbile Qt library after commit af6b20c (release 18.09)

### ISSUE THREAD

**Issue by petrkr** [NixOS/nixpkgs#55994] opened 2019-02-18 12:35 UTC
After commit af6b20c0fa14c3907ecf9836cef4d53e07baf515 KDE desktop won't run and journalctl says:

`org.kde.ActivityManager: Cannot mix incompatible Qt library (version 0x50b01) with this library (0x50b03)`

### Steps to reproduce
nix rebuild with nixpkgs pointed to commit af6b20c0fa14c3907ecf9836cef4d53e07baf515

**Comment by Soft** [comment] 2019-02-23 15:57
I ran into this issue after updating my system. Failing activity manager prevents KDE from starting at all. I wonder if there is a known solution to the problem?

**Comment by EvilFreelancer** [comment] 2019-02-23 23:45
I also has same issue after upgrade, how to reproduce (upgrade then login to kde and exec un konsole):
```
~ $ kactivitymanagerd status
The service is running, version:
~ $ kactivitymanagerd stop
Service not running
Service stopped
~ $ kactivitymanagerd start
Cannot mix incompatible Qt library (version 0x50b01) with this library (version 0x50b03)
Service started, version:
```

**Comment by timor** [comment] 2019-02-24 22:15
Same problem here.

**Comment by timor** [comment] 2019-02-24 22:56
Ok, this was a mean one (at least for me):

I checked the output of `nix-store -qR ~/nix-profile |grep qt` and still saw references to 5.11.1 qt library versions.  In my case, it was older versions of qdirstat and smplayer which I installed via `nix-env`.

After running `nix-env -u --eq` the problem was gone.

It seems that somehow older qt library versions still installed in the user profile leak into kde startup. (cc @ttuegel)

**Comment by timor** [comment] 2019-02-25 12:57
This is actually pretty bad.  KDE stops working right in the middle of a session, when an automatic system update has finished, and the logged-in user has an application installed in her user environment when that references old qt library versions.

**Comment by EvilFreelancer** [comment] 2019-02-25 13:28
> After running `nix-env -u --eq` the problem was gone.
This is not helped to me, because I don't have applications installed to user namespace.
And some application installed to root depends on old Qt, and whole KDE is not want to work by this reason.
Maybe you know how to detect the application, which depends on old Qt? (for removing from my system of course)

**Comment by timor** [comment] 2019-02-25 14:47
Maybe there is some old software in your system?  In any case, checking for that is always the same, e.g. `nix-store -qR /run/current-system | grep qt` and search for version 5.11.1.

Other than that, if you installed anything via `nix-env` as root, it should show up under `/nix/var/nix/profiles/default`, and you can check for old qt stuff there as well with `nix-store -qR /nix/var/nix/profiles/default |grep qt`.  If you find one, you can use `nix-store -q --references ...` on the store path in question to see what depends on it.

These are the three "roots", that I know of, which have an influence on your runtime environment as a user.

As a test, you could also try and see whether you get the same behavior using a fresh user.

**Comment by timor** [comment] 2019-02-25 15:23
This is probably a duplicate of #47552.

**Comment by Soft** [comment] 2019-02-25 17:56
> Ok, this was a mean one (at least for me):
> 
> I checked the output of `nix-store -qR ~/.nix-profile |grep qt` and still saw references to 5.11.1 qt library versions. In my case, it was older versions of `qdirstat` and `smplayer` which I had installed a while ago via `nix-env`.
> 
> After running `nix-env -u --eq` the problem was gone.
> 
> It seems that somehow older qt library versions still installed in the user profile leak into kde startup. (cc @ttuegel)

This was indeed the issue in my case and the proposed solution solved the problem.

**Comment by jtojnar** [comment] 2019-03-14 23:57
Dupe of https://github.com/NixOS/nixpkgs/issues/37864

**Closed by jtojnar** 2019-03-14 23:57 UTC
