### ISSUE TITLE
Python 3.9 doesn't detect libraries installed using withPackages

### ISSUE THREAD

**Issue by flexagoon** [NixOS/nixpkgs#140174] opened 2021-10-01 17:20 UTC
### Describe the bug
I install python libraries like described on nixos.wiki, so
```
with pkgs;
let
  my-python-packages = python-packages: with python-packages; [
    pandas
    requests
    # other python packages you want
  ]; 
  python-with-my-packages = python3.withPackages my-python-packages;
in ...
```
And when I use python38, it all works fine, and python can see those libraries. However, if I just use python3 (which is python 3.9 by default on unstable), python does not see those libraries and instead just gives an import error
```
>>> import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'requests'
```

### Steps To Reproduce
1. Install any python 3.9 libraries with `python3.withPackages` or `python39.withPackages`
2. Launch python 3.9
3. Try to import the installed library

### Expected behavior
Python sees the library and imports it successfully

### Additional context
When I try to install the same library with `nix-shell -p python3Packages.requests`, it all works fine, and python is able to detect it.

### Notify maintainers
@FRidh 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.19, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.11pre319562.c21ba4f7bb4"`
 - channels(flexagoon): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
    - python3
    - python39
```

**Comment by tomprince** [comment] 2021-10-01 21:45
Are you running the python from the `python-with-my-packages` derivation? It isn't clear from your reproduction steps.

**Comment by flexagoon** [comment] 2021-10-02 05:22
> Are you running the python from the `python-with-my-packages` derivation? It isn't clear from your reproduction steps.

Yes, I am

**Comment by applePrincess** [comment] 2021-10-02 11:43
I couldn't reproduce the bug either. I have tried `nix-shell --pure` below shell.nix

```nix
with import <nixpkgs> {};
let
  my-python-packages = python-packages: with python-packages; [
    pandas
    requests
  ];
  python-with-my-packages = python3.withPackages my-python-packages;
in mkShell {
  buildInputs = [
    python-with-my-packages
  ];
}
```
which produces
```text
[alice@applePrincess:/tmp/example]$ nix-shell --pure
this derivation will be built:
  /nix/store/l05rgrw2gwxcb3cpyz175f5l6d8qz8l5-python3-3.8.8-env.drv
these 21 paths will be fetched (49.38 MiB download, 291.18 MiB unpacked):
  /nix/store/56ncqwrhx3f6xfpal4k70f8ni8b86ry2-python3.8-numpy-1.19.1
  /nix/store/7bjcygchy1qc5h23ihafl69dl36435dx-python3.8-et_xmlfile-1.0.1
  /nix/store/82lv93djq2kv9z1qc4lpxa7709fhh6vk-python3.8-pandas-1.1.1
  /nix/store/bzhwxhki4lh4g2ljhvfqcaa65njaad5g-python3.8-xlrd-1.2.0
  /nix/store/h5955s62wzfp92hswc4sissqh7450b0j-python3.8-scipy-1.5.2
  /nix/store/hmgnc9100kzb64xyixxs61dnpzqn5jm5-hdf5-1.10.6
  /nix/store/hwjcxgh86fcqjp093g1w3yw7hdppkyv7-python3.8-openpyxl-3.0.5
  /nix/store/imyizdkaszqsafhldr9wg89wsyf8mlgb-blas-3-dev
  /nix/store/jazbdaynlrcsvx8ffj2d7dk075x7a9a3-python3.8-jdcal-1.4.1
  /nix/store/lryv580dc7mrkh4mdp8zg159j80zdfjf-blas-3
  /nix/store/ls5mb9swbzj7mkxljkbrmkn3r1mnvb96-python3.8-lxml-4.6.3
  /nix/store/p4iy3jibxl5slqw4srw1r61xmxxjdb9q-python3.8-beautifulsoup4-4.9.1
  /nix/store/pw7vpy2x39sc50ydmqf2klqaymi51cqf-python3.8-SQLAlchemy-1.3.19
  /nix/store/q9x01xl1cmips9vh3ccji7f8mdxwdh53-lapack-3-dev
  /nix/store/rbds49rivnqhsprgk0gvcnak0w9n1p6a-python3.8-Bottleneck-1.3.2
  /nix/store/vz1dmbf1jfd2kdqr64451a7g0n8hj9jz-lapack-3
  /nix/store/wms4ig88n8w0kndibd0k55jgm1q6x7vf-c-blosc-1.20.0
  /nix/store/xnk3zyrzinbdh8k2s9qb56kdwfgs76kw-python3.8-tables-3.6.1
  /nix/store/xp866w89l80w30qi3ii0y25rzw7yjlj4-python3.8-soupsieve-2.0.1
  /nix/store/z5frgf1g3f2jz99mxmxpxj8k9rbn6jc4-python3.8-xlwt-1.3.0
  /nix/store/zp8gwfp3dh1x11wa23mcfzsblcr9zhsv-python3.8-numexpr-2.7.1
copying path '/nix/store/wms4ig88n8w0kndibd0k55jgm1q6x7vf-c-blosc-1.20.0' from 'https://cache.nixos.org'...
copying path '/nix/store/pw7vpy2x39sc50ydmqf2klqaymi51cqf-python3.8-SQLAlchemy-1.3.19' from 'https://cache.nixos.org'...
copying path '/nix/store/7bjcygchy1qc5h23ihafl69dl36435dx-python3.8-et_xmlfile-1.0.1' from 'https://cache.nixos.org'...
copying path '/nix/store/jazbdaynlrcsvx8ffj2d7dk075x7a9a3-python3.8-jdcal-1.4.1' from 'https://cache.nixos.org'...
copying path '/nix/store/ls5mb9swbzj7mkxljkbrmkn3r1mnvb96-python3.8-lxml-4.6.3' from 'https://cache.nixos.org'...
copying path '/nix/store/xp866w89l80w30qi3ii0y25rzw7yjlj4-python3.8-soupsieve-2.0.1' from 'https://cache.nixos.org'...
copying path '/nix/store/bzhwxhki4lh4g2ljhvfqcaa65njaad5g-python3.8-xlrd-1.2.0' from 'https://cache.nixos.org'...
copying path '/nix/store/z5frgf1g3f2jz99mxmxpxj8k9rbn6jc4-python3.8-xlwt-1.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/lryv580dc7mrkh4mdp8zg159j80zdfjf-blas-3' from 'https://cache.nixos.org'...
copying path '/nix/store/hmgnc9100kzb64xyixxs61dnpzqn5jm5-hdf5-1.10.6' from 'https://cache.nixos.org'...
copying path '/nix/store/vz1dmbf1jfd2kdqr64451a7g0n8hj9jz-lapack-3' from 'https://cache.nixos.org'...
copying path '/nix/store/p4iy3jibxl5slqw4srw1r61xmxxjdb9q-python3.8-beautifulsoup4-4.9.1' from 'https://cache.nixos.org'...
copying path '/nix/store/hwjcxgh86fcqjp093g1w3yw7hdppkyv7-python3.8-openpyxl-3.0.5' from 'https://cache.nixos.org'...
copying path '/nix/store/q9x01xl1cmips9vh3ccji7f8mdxwdh53-lapack-3-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/imyizdkaszqsafhldr9wg89wsyf8mlgb-blas-3-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/56ncqwrhx3f6xfpal4k70f8ni8b86ry2-python3.8-numpy-1.19.1' from 'https://cache.nixos.org'...
copying path '/nix/store/rbds49rivnqhsprgk0gvcnak0w9n1p6a-python3.8-Bottleneck-1.3.2' from 'https://cache.nixos.org'...
copying path '/nix/store/zp8gwfp3dh1x11wa23mcfzsblcr9zhsv-python3.8-numexpr-2.7.1' from 'https://cache.nixos.org'...
copying path '/nix/store/h5955s62wzfp92hswc4sissqh7450b0j-python3.8-scipy-1.5.2' from 'https://cache.nixos.org'...
copying path '/nix/store/xnk3zyrzinbdh8k2s9qb56kdwfgs76kw-python3.8-tables-3.6.1' from 'https://cache.nixos.org'...
copying path '/nix/store/82lv93djq2kv9z1qc4lpxa7709fhh6vk-python3.8-pandas-1.1.1' from 'https://cache.nixos.org'...
building '/nix/store/l05rgrw2gwxcb3cpyz175f5l6d8qz8l5-python3-3.8.8-env.drv'...
created 329 symlinks in user environment

[nix-shell:/tmp/example]$ python3
Python 3.8.8 (default, Feb 19 2021, 11:04:50) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> 
```

**Comment by applePrincess** [comment] 2021-10-02 11:49
If I changed to `nixos-unstable` instead of `nixpkgs`. It successfully finds library.
```text
[alice@applePrincess:/tmp/example]$ nix-shell --pure
this derivation will be built:
  /nix/store/2db93faj9kq05qgbabbpwzy67hrwlrrk-python3-3.9.6-env.drv
these 17 paths will be fetched (17.43 MiB download, 102.87 MiB unpacked):
  /nix/store/202rlzl358ddalkrj2b1alg61fiq8qza-python3.9-soupsieve-2.2.1
  /nix/store/6mc1s28skd4849zjf2vx04zmm1qhnl4h-c-blosc-1.21.0
  /nix/store/88qpsgnbw234n7y1ap23n5bp891pl33d-python3.9-greenlet-1.1.1
  /nix/store/ai7zznhm4k18c4b5h272zyz7cvfn9524-hdf5-1.10.6
  /nix/store/cpva1bmw5d87ys57n9a5jyq17zp59vfk-python3.9-beautifulsoup4-4.10.0
  /nix/store/dzxhykjgiix9vph392rdvwwifpz2jf1i-python3.9-openpyxl-3.0.7
  /nix/store/k450nkqycvciyk1zrxgy0f90r5gnx32y-python3.9-xlrd-2.0.1
  /nix/store/m23ba8vj8gcalbysycg8c8j4ipb832xd-python3.9-jdcal-1.4.1
  /nix/store/p1jvp85li52pb619ip6lp3dydj1b6xa3-python3.9-Bottleneck-1.3.2
  /nix/store/pa71l35mzcbb70ah6amvgzr2rna7c8yc-python3.9-xlwt-1.3.0
  /nix/store/racqgc8pf0fzgkizi4bn8z12kh9nndnb-python3.9-SQLAlchemy-1.4.23
  /nix/store/rkm6cirv5liqxwnnwjjd9vmi9hayf188-python3.9-pandas-1.3.2
  /nix/store/s28ynd51brcrdl8qifxsj7abym0iacpj-python3.9-numexpr-2.7.3
  /nix/store/s66b6fsqwhyf35cv1nir13y7zr2qdxbq-python3.9-webencodings-0.5.1
  /nix/store/sij9ii7nqa3rg2whm055zj38rbigd74q-python3.9-et_xmlfile-1.0.1
  /nix/store/v4i0r3kwyx8calh4sfn014qwwbiq7f6a-python3.9-html5lib-1.1
  /nix/store/y3fib1rrbr1sfda3szynavnwjcr51kc1-python3.9-tables-3.6.1
copying path '/nix/store/6mc1s28skd4849zjf2vx04zmm1qhnl4h-c-blosc-1.21.0' from 'https://cache.nixos.org'...
copying path '/nix/store/p1jvp85li52pb619ip6lp3dydj1b6xa3-python3.9-Bottleneck-1.3.2' from 'https://cache.nixos.org'...
copying path '/nix/store/sij9ii7nqa3rg2whm055zj38rbigd74q-python3.9-et_xmlfile-1.0.1' from 'https://cache.nixos.org'...
copying path '/nix/store/88qpsgnbw234n7y1ap23n5bp891pl33d-python3.9-greenlet-1.1.1' from 'https://cache.nixos.org'...
copying path '/nix/store/m23ba8vj8gcalbysycg8c8j4ipb832xd-python3.9-jdcal-1.4.1' from 'https://cache.nixos.org'...
copying path '/nix/store/s28ynd51brcrdl8qifxsj7abym0iacpj-python3.9-numexpr-2.7.3' from 'https://cache.nixos.org'...
copying path '/nix/store/202rlzl358ddalkrj2b1alg61fiq8qza-python3.9-soupsieve-2.2.1' from 'https://cache.nixos.org'...
copying path '/nix/store/s66b6fsqwhyf35cv1nir13y7zr2qdxbq-python3.9-webencodings-0.5.1' from 'https://cache.nixos.org'...
copying path '/nix/store/k450nkqycvciyk1zrxgy0f90r5gnx32y-python3.9-xlrd-2.0.1' from 'https://cache.nixos.org'...
copying path '/nix/store/pa71l35mzcbb70ah6amvgzr2rna7c8yc-python3.9-xlwt-1.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/ai7zznhm4k18c4b5h272zyz7cvfn9524-hdf5-1.10.6' from 'https://cache.nixos.org'...
copying path '/nix/store/v4i0r3kwyx8calh4sfn014qwwbiq7f6a-python3.9-html5lib-1.1' from 'https://cache.nixos.org'...
copying path '/nix/store/racqgc8pf0fzgkizi4bn8z12kh9nndnb-python3.9-SQLAlchemy-1.4.23' from 'https://cache.nixos.org'...
copying path '/nix/store/cpva1bmw5d87ys57n9a5jyq17zp59vfk-python3.9-beautifulsoup4-4.10.0' from 'https://cache.nixos.org'...
copying path '/nix/store/dzxhykjgiix9vph392rdvwwifpz2jf1i-python3.9-openpyxl-3.0.7' from 'https://cache.nixos.org'...
copying path '/nix/store/y3fib1rrbr1sfda3szynavnwjcr51kc1-python3.9-tables-3.6.1' from 'https://cache.nixos.org'...
copying path '/nix/store/rkm6cirv5liqxwnnwjjd9vmi9hayf188-python3.9-pandas-1.3.2' from 'https://cache.nixos.org'...
building '/nix/store/2db93faj9kq05qgbabbpwzy67hrwlrrk-python3-3.9.6-env.drv'...
warning: creating dangling symlink `/nix/store/fr06mfcxnpg6mwlr6mb705zdzdqvr5pw-python3-3.9.6-env//include/python3.9/python3.9m' -> `/nix/store/i1m8r7mv8h47wr850cdsxksy22lv6gsz-python3-3.9.6/include/python3.9/python3.9m' -> `../python3.9m'
created 435 symlinks in user environment

[nix-shell:/tmp/example]$ python3
Python 3.9.6 (default, Jun 28 2021, 08:57:49) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> 
```

nix-info result:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.7, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210922_bcd73eb`
 - channels(root): `"nixos-20.09.4404.a13824fe5e3, nixos-unstable-21.11pre319562.c21ba4f7bb4"`
 - channels(alice): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by flexagoon** [comment] 2021-10-02 16:03
@applePrincess that's because you use nix-shell. if I use nix-shell, I dont have the issue as well. It only occurs when I try to install libraries with home-manager

**Comment by applePrincess** [comment] 2021-10-03 05:16
I don't use home-manager though
I ran `home-manager switch` with below `home.nix` in vm
```nix
{ config, pkgs, ... }: 
let 
  unstable = import <nixpkgs-unstable> {}; 
  my-python-packages = python-packages: with python-packages; [
    pandas
    requests
  ];
  python-with-my-packages = unstable.python3.withPackages my-python-packages;
in {
  programs.home-manager.enable = true;
  home.username = "root";
  home.homeDirectory = "/root";
  home.packages = [
    python-with-my-packages
  ];
  home.stateVersion = "21.11";
}
```

I can still import requests
```
[root@nixos:~]# python3
Python 3.9.6 (default, Jun 28 2021, 08:57:49) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> 
```

**Comment by FRidh** [comment] 2022-03-29 11:45
@flexagoon I am going to close this. If you have a minimal reproducible example we can open this again.

**Closed by FRidh** 2022-03-29 11:45 UTC
Labels: 0.kind: bug, 6.topic: python
