### ISSUE TITLE
Build failure: influxdb2

### ISSUE THREAD

**Issue by Scrumplex** [NixOS/nixpkgs#320019] opened 2024-06-15 09:35 UTC
### Steps To Reproduce

1. build influxdb2

### Build log

```
libflux-v0.193.0> error: methods `into_type` and `location` are never used
libflux-v0.193.0>     --> flux-core/src/semantic/types.rs:2192:8
libflux-v0.193.0>      |
libflux-v0.193.0> 2189 | pub(crate) trait TypeLike {
libflux-v0.193.0>      |                  -------- methods in this trait
libflux-v0.193.0> ...
libflux-v0.193.0> 2192 |     fn into_type(self) -> MonoType;
libflux-v0.193.0>      |        ^^^^^^^^^
libflux-v0.193.0> 2193 |     fn error(&self, error: Error) -> Self::Error;
libflux-v0.193.0> 2194 |     fn location(&self) -> crate::ast::SourceLocation;
libflux-v0.193.0>      |        ^^^^^^^^
libflux-v0.193.0>      |
libflux-v0.193.0> note: the lint level is defined here
libflux-v0.193.0>     --> flux-core/src/lib.rs:1:38
libflux-v0.193.0>      |
libflux-v0.193.0> 1    | #![cfg_attr(feature = "strict", deny(warnings, missing_docs))]
libflux-v0.193.0>      |                                      ^^^^^^^^
libflux-v0.193.0>      = note: `#[deny(dead_code)]` implied by `#[deny(warnings)]`
libflux-v0.193.0> error: could not compile `flux-core` (lib) due to 1 previous error
libflux-v0.193.0> warning: build failed, waiting for other jobs to finish...
libflux-v0.193.0> error: could not compile `flux-core` (lib) due to 1 previous error
error: builder for '/nix/store/wnyr9nwcy0q399iqbq9am6v421m7n1v1-libflux-v0.193.0.drv' failed with exit code 101;
       last 25 log lines:
       >    Compiling chrono v0.4.19
       >    Compiling ordered-float v3.2.0
       >    Compiling flux-core v0.154.0 (/build/source/libflux/flux-core)
       > error: methods `into_type` and `location` are never used
       >     --> flux-core/src/semantic/types.rs:2192:8
       >      |
       > 2189 | pub(crate) trait TypeLike {
       >      |                  -------- methods in this trait
       > ...
       > 2192 |     fn into_type(self) -> MonoType;
       >      |        ^^^^^^^^^
       > 2193 |     fn error(&self, error: Error) -> Self::Error;
       > 2194 |     fn location(&self) -> crate::ast::SourceLocation;
       >      |        ^^^^^^^^
       >      |
       > note: the lint level is defined here
       >     --> flux-core/src/lib.rs:1:38
       >      |
       > 1    | #![cfg_attr(feature = "strict", deny(warnings, missing_docs))]
       >      |                                      ^^^^^^^^
       >      = note: `#[deny(dead_code)]` implied by `#[deny(warnings)]`
       >
       > error: could not compile `flux-core` (lib) due to 1 previous error
       > warning: build failed, waiting for other jobs to finish...
       > error: could not compile `flux-core` (lib) due to 1 previous error
       For full logs, run 'nix log /nix/store/wnyr9nwcy0q399iqbq9am6v421m7n1v1-libflux-v0.193.0.drv'.
error: 1 dependencies of derivation '/nix/store/vx1hs2nv3mvy9ilx1sk9ybhv8z5svbld-influxdb-2.7.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rdjy97r4q70kc2ivk5ji4xvpnai2ifp2-influxdb2.drv' failed to build
```

### Additional context

This was fixed upstream, but I wasn't able to backport this commit myself and the latest release of influxdb doesn't a version with this patch yet.

https://github.com/influxdata/flux/commit/68c831c40b396f0274f6a9f97d77707c39970b02

### Notify maintainers

@abbradar

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.3-zen1, NixOS, 24.11 (Vicuna), 24.11.20240613.e9ee548`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0-beta.1`
 - channels(scrumplex): `""`
 - nixpkgs: `/etc/nix/channels/nixpkgs`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-06-15 12:10
dupe of #319973

**Closed by eclairevoyant** 2024-06-15 12:10 UTC
Labels: 0.kind: build failure
