### ISSUE TITLE
sddm : boot.cleanTmpDir = true makes login impossible

### ISSUE THREAD

**Issue by heydojo** [NixOS/nixpkgs#12375] opened 2016-01-14 05:34 UTC
If I express :
```
services.xserver.desktopManager.kde5.enable = false;
services.xserver.displayManager.sddm.enable = true;
services.xserver.displayManager.kdm.enable = false;
services.xserver.desktopManager.kde4.enable = true;
services.xserver.desktopManager.xfce.enable = true;
```
in configuration.nix sddm starts and the greeter appears.
However, when I place the caret inside the input box, type the password for the user account and press enter; nothing at all happens. The same applies if I select an xfce or kde4 session using the greeter.
I found sddm complaining about QIODevice: :write(QLocalSocket): device not open in journalctl.

So the issue is that I cannot login to any desktop if I enable sddm as the default display manager.
I am using the latest from unstable master's entire tree up to commit https://github.com/NixOS/nixpkgs/commit/a1be498630f5dcaeb45a5e44cc5a5c415db07dd9
I have tried deleting /var/lib/sddm.
I have tried switching between the open source radeon and ati_unfree display drivers.
If anyone could shed some light on this it would be a great help.

**Comment by abbradar** [comment] 2016-01-14 13:25
Can you please try to get `systemctl status display-manager` output (to check what daemons are running and to see log entries)?

**Comment by heydojo** [comment] 2016-01-15 05:36
Here is the output of systemctl status :
```
● Grimlock
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Fri 2016-01-15 05:28:06 UTC; 39s ago
   CGroup: /
           ├─init.scope
           │ └─1 systemd
           ├─system.slice
           │ ├─dbus.service
           │ │ └─659 /nix/store/r04mccrfm48jvgn86db8v8qp322qlq5v-dbus-tools-1.8.20/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
           │ ├─privoxy.service
           │ │ └─849 /nix/store/415vgp8mx9lx9x5nlj4kdkysj5nc2hfm-privoxy-3.0.22/sbin/privoxy --no-daemon --user privoxy /nix/store/50kjgci3swj1kgncxxyhxwah4cb27jq1-privoxy.conf
           │ ├─pulseaudio.service
           │ │ └─722 /nix/store/k3mv2wb43agh0ywp1gq67srj63j24j1b-pulseaudio-7.1/bin/pulseaudio -D --log-level=notice --system --use-pid-file -n --file=/nix/store/k3mv2wb43agh0ywp1gq67srj63j24j1b-pulseaudio-7.1/etc/pulse/default.pa
           │ ├─wpa_supplicant.service
           │ │ └─884 /nix/store/nps5v9inq97diyfq5a5ly1i75z8g44x5-wpa_supplicant-2.5/sbin//wpa_supplicant -u
           │ ├─nscd.service
           │ │ └─649 nscd -f /nix/store/5xm18kzfbkh5lwky00d2lqz22i9fav2i-nscd.conf
           │ ├─systemd-journald.service
           │ │ └─417 /nix/store/baij4in1g0swyjqqqxgk41k6kdm9ydcd-systemd-228/lib/systemd/systemd-journald
           │ ├─dbus-org.bluez.service
           │ │ └─606 /nix/store/h2gbap5zraxh3gil4cs00qv4k9n190ij-bluez-4.101/sbin/bluetoothd -n
           │ ├─samba-nmbd.service
           │ │ └─622 /nix/store/5r6s7lspjigl1fqpx4fnfnwb0ndbik3m-samba-4.3.1/sbin/nmbd -F
           │ ├─ntpd.service
           │ │ └─653 ntpd -g -c /nix/store/9n4v4sxp62k7nka82djc3w2lqw5khdac-ntp.conf -u ntp:nogroup
           │ ├─samba-smbd.service
           │ │ ├─625 /nix/store/5r6s7lspjigl1fqpx4fnfnwb0ndbik3m-samba-4.3.1/sbin/smbd -F
           │ │ ├─863 /nix/store/5r6s7lspjigl1fqpx4fnfnwb0ndbik3m-samba-4.3.1/sbin/smbd -F
           │ │ └─868 /nix/store/5r6s7lspjigl1fqpx4fnfnwb0ndbik3m-samba-4.3.1/sbin/smbd -F
           │ ├─display-manager.service
           │ │ ├─814 /nix/store/qgaf9nh5npba1yk1h7pwrg4l0579djm5-sddm-unwrapped-0.13.0/bin/sddm
           │ │ └─847 /nix/store/9kqdpbny5yf8mpql0sgzx4hy42p4q9rw-xorg-server-1.17.4/bin/X -ac -terminate -config /nix/store/719cgp8k9sfbwj1bha1v9kb1qn8pqhpz-xserver.conf -xkbdir /nix/store/ksapvpxj43z38qsvjlqgx5azk5skvhxz-xkeyboard-config-2.15/etc/X11/xkb :0 vt7 -logfile /var/log/X.0.log -nolisten tcp -nolisten tcp -auth /var/run/sddm/{2112fce8-22d0-4688-b3d8-33ab534d8889} -background none -noreset -displayfd 17 vt7
           │ ├─systemd-logind.service
           │ │ └─791 /nix/store/baij4in1g0swyjqqqxgk41k6kdm9ydcd-systemd-228/lib/systemd/systemd-logind
           │ ├─system-getty.slice
           │ │ └─getty@tty2.service
           │ │   └─937 agetty --login-program /nix/store/pmx7lyylfw5cav4bkmy4d1nar0gk76jp-shadow-4.2.1/bin/login --noclear --keep-baud tty2 115200 38400 9600 linux
           │ ├─systemd-udevd.service
           │ │ └─455 /nix/store/baij4in1g0swyjqqqxgk41k6kdm9ydcd-systemd-228/lib/systemd/systemd-udevd
           │ ├─samba-winbindd.service
           │ │ ├─623 /nix/store/5r6s7lspjigl1fqpx4fnfnwb0ndbik3m-samba-4.3.1/sbin/winbindd -F
           │ │ └─896 /nix/store/5r6s7lspjigl1fqpx4fnfnwb0ndbik3m-samba-4.3.1/sbin/winbindd -F
           │ ├─polkit.service
           │ │ └─885 /nix/store/98czmz83hda62h5mgjrbqff6d1jkbhy0-polkit-0.113/lib/polkit-1/polkitd --no-debug
           │ ├─network-manager.service
           │ │ └─654 /nix/store/7qw3zqhisscc4rb0r62w1a1bnwd83j8x-network-manager-1.0.6/sbin/NetworkManager --no-daemon
           │ └─acpid.service
           │   └─765 acpid --confdir /nix/store/xkg64gkchknz9n8n5fz0xa9v8rxw9h5x-acpi-events
           └─user.slice
             ├─user-1000.slice
             │ ├─user@1000.service
             │ │ ├─init.scope
             │ │ │ ├─944 /nix/store/baij4in1g0swyjqqqxgk41k6kdm9ydcd-systemd-228/lib/systemd/systemd --user
             │ │ │ └─946 (sd-pam
             │ │ └─ssh-agent.service
             │ │   └─953 /nix/store/pkixdknsjv1ic17q6xbqhf6w86ardgq6-openssh-6.9p1/bin/ssh-agent -a /run/user/1000/ssh-agent
             │ └─session-2.scope
             │   ├─902 /nix/store/pmx7lyylfw5cav4bkmy4d1nar0gk76jp-shadow-4.2.1/bin/login --     
             │   ├─954 -bash
             │   └─966 systemctl status
             └─user-175.slice
               ├─session-c1.scope
               │ ├─865 /nix/store/qgaf9nh5npba1yk1h7pwrg4l0579djm5-sddm-unwrapped-0.13.0/libexec/sddm-helper --socket /tmp/sddm-auth45e60ed4-fce7-458e-8b77-01cf8dc0c571 --id 2 --start /nix/store/qgaf9nh5npba1yk1h7pwrg4l0579djm5-sddm-unwrapped-0.13.0/bin/sddm-greeter --socket /tmp/sddm-:0-aimaRc --theme /nix/store/0lz139f0mjiqfcfpybv0qw6xvkcd77sl-sddm-0.13.0/share/sddm/themes/maui --user sddm --greeter
               │ └─911 /nix/store/qgaf9nh5npba1yk1h7pwrg4l0579djm5-sddm-unwrapped-0.13.0/bin/sddm-greeter --socket /tmp/sddm-:0-aimaRc --theme /nix/store/0lz139f0mjiqfcfpybv0qw6xvkcd77sl-sddm-0.13.0/share/sddm/themes/maui
               └─user@175.service
                 ├─init.scope
                 │ ├─901 /nix/store/baij4in1g0swyjqqqxgk41k6kdm9ydcd-systemd-228/lib/systemd/systemd --user
                 │ └─903 (sd-pam
                 └─ssh-agent.service
                   └─910 /nix/store/pkixdknsjv1ic17q6xbqhf6w86ardgq6-openssh-6.9p1/bin/ssh-agent -a /run/user/175/ssh-agent
```
I noticed also that if I ctrl+alt+f2 the greeter disappears and cannot be returned to. I don't think it should work like that.

**Comment by abbradar** [comment] 2016-01-15 06:08
One thing that bothers me is that you don't have `sddm-helper` running. I suspect that's the core of the problem (it died at done point?) but I don't know what can we do with this. 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by heydojo** [comment] 2016-01-15 06:49
It is I believe
```
├─session-c1.scope
               │ ├─865 /nix/store/qgaf9nh5npba1yk1h7pwrg4l0579djm5-sddm-unwrapped-0.13.0/libexec/sddm-helper --socket /tmp/sddm-auth45e60ed4-fce7-458e-8b77-01cf8dc0c571 --id 2 --start /nix/store/qgaf9nh5npba1yk1h7pwrg4l0579djm5-sddm-unwrapped-0.13.0/bin/sddm-greeter --socket /tmp/sddm-:0-aimaRc --theme /nix/store/0lz139f0mjiqfcfpybv0qw6xvkcd77sl-sddm-0.13.0/share/sddm/themes/maui --user sddm --greeter
```

**Comment by abbradar** [comment] 2016-01-15 16:26
Ah, indeed, I looked for it in `sddm.service` group.
Back to the square one!

**Comment by heydojo** [comment] 2016-01-16 05:28
I found it.
```
boot.cleanTmpDir = true;
```
in configuration.nix. I think it was cleaning out /tmp after the sockets were being created.
The system should really wait until boot.cleanTmpDir has completed until the go ahead is given to start anything which needs to write into /tmp.

That being said; I am pretty happy because I can now run kde 5.
So the issue is a systemd service issue relating to boot.cleanTmpDir.
IMO boot.cleanTmpDir should really be a shutdown clean tmp dir instead. I can't think of any reasons to need to clean tmp at start up.

**Comment by abbradar** [comment] 2016-01-16 18:20
Funny that I also have this option enabled but I haven't had such problems -- but of course problems like this are very random in nature. I agree that cleaning `/tmp` on shutdown sounds more reasonable, too. I see that we use `systemd-tmpfiles` to clean `/tmp` -- it may have flags or hooks to specify cleaning at special moments in time. Who can we ping for `systemd` expertise?

**Comment by globin** [comment] 2016-01-17 17:16
ping @edolstra

**Comment by jgeerds** [comment] 2016-01-17 20:56
same problem: https://github.com/NixOS/nixpkgs/issues/6037

**Comment by edolstra** [comment] 2016-01-18 10:37
Closing as dupe of #4825.

**Closed by edolstra** 2016-01-18 10:37 UTC
Labels: 0.kind: bug, 0.kind: question, 6.topic: nixos
