### ISSUE TITLE
Package request: posting

### ISSUE THREAD

**Issue by cor** [NixOS/nixpkgs#354076] opened 2024-11-06 20:09 UTC
**Project description**

## Posting

The API client that lives in your terminal.
Posting is a beautiful open-source terminal app for developing and testing APIs.

Fly through your API workflow with an approachable yet powerful keyboard-centric interface. Run it locally or over SSH on remote machines and containers. Save your requests in a readable and version-control friendly format.

**Metadata**

* homepage URL: https://posting.sh
* source URL: https://github.com/darrenburns/posting
* license: Apache 2
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by arcuru** [comment] 2024-11-06 20:20
Duplicate of #327855

**Closed by arcuru** 2024-11-06 20:20 UTC
Labels: 0.kind: packaging request
