### ISSUE TITLE
fwupd: Cannot upgrade Lenovo T460s firmware

### ISSUE THREAD

**Issue by tadfisher** [NixOS/nixpkgs#45075] opened 2018-08-15 17:20 UTC
## Issue description

`fwupdmgr` fails to upgrade my T460s firmware.

### Steps to reproduce

```sh
$ sudo fwupmgr get-devices
# ...
20F9CTO1WW System Firmware
  DeviceId:             444a229da2b21bc0d24faf814d1c58c5bff3315f
  Guid:                 42f29620-3d63-4f09-950b-9b7055570f28
  Guid:                 230c8b18-8d9b-53ec-838b-6cfc0383493a
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|supported|registered|needs-reboot
  Version:              0.1.33
  VersionLowest:        0.1.22
  Icon:                 computer
  Created:              2018-08-14
  Modified:             2018-08-15
  UpdateState:          failed
  UpdateError:          {error #0} util.h:323 get_file(): could not open file "/sys/devices/pci0000:00/firmware_node/uid" for reading: No such file or directory	{error #1} linux.c:436 device_get(): parsing pci failed: No such file or directory	{error #2} creator.c:194 efi_va_generate_file_device_path_from_esp(): could not get ESP disk info: No such file or directory	{error #3} creator.c:383 efi_generate_file_device_path(): could not generate File DP from ESP: No such file or directory	{error #4} util.h:323 get_file(): could not open file "/sys/devices/pci0000:00/firmware_node/uid" for reading: No such file or directory	{error #5} linux.c:436 device_get(): parsing pci failed: No such file or directory	{error #6} creator.c:194 efi_va_generate_file_device_path_from_esp(): could not get ESP disk info: No such file or directory	{error #7} creator.c:383 efi_generate_file_device_path(): could not generate File DP from ESP: No such file or directory: failed to efi_generate_file_device_path(/boot/efi/EFI/nixos/fw/fwupd-42f29620-3d63-4f09-950b-9b7055570f28.cap)
# ...
```

```sh
$ sudo fwupdmgr update
Downloading 0.1.37 for 20F9CTO1WW System Firmware...
Fetching firmware https://fwupd.org/downloads/46c382fbcc171b023b66b0f579a7f7ff31d90ff9-Lenovo-ThinkPad-T460s-SystemFirmware-1.37.cab
Downloading…           [***************************************]
Updating 0.1.37 on 20F9CTO1WW System Firmware...
Decompressing…         [***************************************]
Authenticating…        [***************************************]
Scheduling…            [***************************************]
{error #0} util.h:323 get_file(): could not open file "/sys/devices/pci0000:00/firmware_node/uid" for reading: No such file or directory	{error #1} linux.c:436 device_get(): parsing pci failed: No such file or directory	{error #2} creator.c:194 efi_va_generate_file_device_path_from_esp(): could not get ESP disk info: No such file or directory	{error #3} creator.c:383 efi_generate_file_device_path(): could not generate File DP from ESP: No such file or directory	{error #4} util.h:323 get_file(): could not open file "/sys/devices/pci0000:00/firmware_node/uid" for reading: No such file or directory	{error #5} linux.c:436 device_get(): parsing pci failed: No such file or directory	{error #6} creator.c:194 efi_va_generate_file_device_path_from_esp(): could not get ESP disk info: No such file or directory	{error #7} creator.c:383 efi_generate_file_device_path(): could not generate File DP from ESP: No such file or directory	{error #8} util.h:323 get_file(): could not open file "/sys/devices/pci0000:00/firmware_node/uid" for reading: No such file or directory	{error #9} linux.c:436 device_get(): parsing pci failed: No such file or directory	{error #10} creator.c:194 efi_va_generate_file_device_path_from_esp(): could not get ESP disk info: No such file or directory	{error #11} creator.c:383 efi_generate_file_device_path(): could not generate File DP from ESP: No such file or directory: failed to efi_generate_file_device_path(/boot/efi/EFI/nixos/fw/fwupd-42f29620-3d63-4f09-950b-9b7055570f28.cap)
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.0, NixOS, 18.09pre149044.6afd19e699c (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09pre149044.6afd19e699c"`
 - channels(tad): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment] 2018-08-15 18:57
This looks like a progress from https://github.com/NixOS/nixpkgs/issues/39386.

cc @superm1 @Moredread

**Comment by superm1** [comment] 2018-08-15 19:01
Is this fwupd 1.1.1 or fwupd 1.1.0?

**Comment by superm1** [comment] 2018-08-15 19:04
Also where is your ESP located?  I'm guessing it's `/boot/efi` If it's `/boot`, then i would expect it to fail on fwupd 1.1.0 due to missing https://github.com/hughsie/fwupd/commit/9bdbbc5ca8349661f2d664c8f9529070159c6e37

It would be good if you can please share the output from the daemon in verbose mode (add `--verbose` to the unit `ExecStart`).

**Comment by superm1** [comment] 2018-08-15 19:05
@jtojnar Yes there is some new support in fwupd 1.1.x that will handle dynamic location of the ESP, installation of the EFI binaries and safety checks.  They already are confirmed to help the arch folks that were having problems, and I suspect 1.1.1 should help NixOS too.

**Comment by jtojnar** [comment] 2018-08-15 20:30
@superm1 That would be 1.1.0.

```ShellSession
$ cat /etc/fwupd/uefi.conf 
[uefi]
OverrideESPMountPoint=/boot
```

@tadfisher Adding the following to your `configuration.nix` should work:

```nix
systemd.services.fwupd.serviceConfig.ExecStart = [
  "" # we need to clear the attribute first (see the last paragraph of https://www.freedesktop.org/software/systemd/man/systemd.unit.html#id-1.14.3)
  "${pkgs.fwupd}/libexec/fwupd/fwupd --verbose"
];
```

**Comment by jtojnar** [comment] 2018-08-15 20:37
@tadfisher Also please try https://github.com/NixOS/nixpkgs/pull/45084

**Comment by tadfisher** [comment] 2018-08-15 21:14
@superm1 

`fwupd` is 1.1.0. 

ESP is at `/boot/efi`.

Gist of verbose log: https://gist.github.com/tadfisher/68177cad660e3d19b2bde51e78c0172d

Contents of `/etc/fwupd/uefi.conf`:

```
[uefi]
OverrideESPMountPoint=/boot/efi
```

**Comment by superm1** [comment] 2018-08-16 15:07
@tadfisher  sorry I should have been clearer, I want to see the verbose output that includes the attempt at running the update not just starting up the daemon.

**Comment by tadfisher** [comment] 2018-08-16 16:53
@superm1 This is the log output when running `sudo fwupdmgr update`:

```
Aug 16 09:51:45 curie fwupd[1585]: 16:51:45:0142 Fu  Called GetDevices()
Aug 16 09:51:45 curie fwupd[1585]: 16:51:45:0143 Fu  Called GetUpgrades(444a229da2b21bc0d24faf814d1c58c5bff3315f)
Aug 16 09:51:45 curie fwupd[1585]: 16:51:45:0143 Fu  firmware archive contained no signature
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0789 Fu  Called GetDevices()
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0790 Fu  Called GetUpgrades(444a229da2b21bc0d24faf814d1c58c5bff3315f)
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0790 Fu  firmware archive contained no signature
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0791 Fu  Called GetRemotes()
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0821 Fu  Called Install(444a229da2b21bc0d24faf814d1c58c5bff3315f,7)
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0821 Fu  got option reason
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0821 Fu  got option filename
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0823 Fu  Emitting PropertyChanged('Status'='decompressing')
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0846 Fu  processing folder: 1/1
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0846 Fu  processing file: firmware.metainfo.xml
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0846 Fu  processing release: 0.1.37
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0865 Fu  processing file: firmware.bin
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0865 Fu  processing file: README.txt
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0865 Fu  processing file: firmware.bin.asc
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0889 Fu  Emitting PropertyChanged('Status'='idle')
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0890 Fu  Emitting PropertyChanged('Status'='idle')
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0921 Fu  Using keyring at /var/lib/fwupd/gnupg
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0925 Fu  Adding GnuPG public key /nix/store/89w6y6kaimpdb86vs116dgkprgrvz3gj-fwupd-1.1.0/etc/pki/fwupd/GPG-KEY-Hughski-Limited
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0932 Fu  importing key 7E5439F64986F7A9E973809BAD8A528FEC44881E [0] Success
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0933 Fu  Adding GnuPG public key /nix/store/89w6y6kaimpdb86vs116dgkprgrvz3gj-fwupd-1.1.0/etc/pki/fwupd/GPG-KEY-Linux-Foundation-Firmware
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0939 Fu  importing key F2F0325648E1AE4956710198C6361787A0A849E1 [0] Success
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0939 Fu  Adding GnuPG public key /nix/store/89w6y6kaimpdb86vs116dgkprgrvz3gj-fwupd-1.1.0/etc/pki/fwupd/GPG-KEY-Linux-Vendor-Firmware-Service
Aug 16 09:51:51 curie fwupd[1585]: 16:51:51:0944 Fu  importing key 3FC6B804410ED0840D8F2F9748A6D80E4538BAC2 [0] Success
Aug 16 09:51:52 curie fwupd[1585]: 16:51:52:0015 Fu  returned signature fingerprint 3FC6B804410ED0840D8F2F9748A6D80E4538BAC2
Aug 16 09:51:52 curie fwupd[1585]: 16:51:52:0015 Fu  marking payload as trusted
Aug 16 09:51:52 curie fwupd[1585]: 16:51:52:0015 Fu  Emitting PropertyChanged('Status'='waiting-for-auth')
Aug 16 09:51:52 curie fwupd[1585]: 16:51:52:0016 Fu  Emitting PropertyChanged('Status'='idle')
Aug 16 09:51:52 curie fwupd[1585]: 16:51:52:0016 Fu  performing update_prepare() on upower
Aug 16 09:51:52 curie fwupd[1585]: 16:51:52:0027 Fu  FuHistory: remove device 20F9CTO1WW System Firmware [444a229da2b21bc0d24faf814d1c58c5bff3315f]
Aug 16 09:51:52 curie fwupd[1585]: 16:51:52:0039 Fu  FuHistory: add device 20F9CTO1WW System Firmware [444a229da2b21bc0d24faf814d1c58c5bff3315f]
Aug 16 09:51:52 curie fwupd[1585]: 16:51:52:0051 Fu  FuHistory: trying to open database '/var/lib/fwupd/pending.db'
Aug 16 09:51:52 curie fwupd[1585]: 16:51:52:0052 Fu  FuHistory: got schema version of 2
Aug 16 09:51:52 curie fwupd[1585]: 16:51:52:0052 Fu  FuHistory: get device
Aug 16 09:51:52 curie fwupd[1585]: 16:51:52:0052 Fu  FuHistory: got sql result 444a229da2b21bc0d24faf814d1c58c5bff3315f
Aug 16 09:51:52 curie fwupd[1585]: 16:51:52:0052 Uefi Performing UEFI capsule update
Aug 16 09:51:52 curie fwupd[1585]: 16:51:52:0052 Fu  Emitting PropertyChanged('Status'='scheduling')
Aug 16 09:51:52 curie fwupd[1585]: 16:51:52:0052 Fu  Emitting PropertyChanged('Status'='scheduling')
Aug 16 09:51:52 curie fwupd[1585]: 16:51:52:0052 Uefi failed to upload UEFI UX capsule text: BGRT is not supported
Aug 16 09:51:52 curie fwupd[1585]: 16:51:52:0052 Fwupd looking for os-release at /etc/os-release
Aug 16 09:51:52 curie fwupd[1585]: 16:51:52:0052 Fu  creating path /boot/efi/EFI/nixos/fw
Aug 16 09:51:52 curie fwupd[1585]: 16:51:52:0052 Fu  writing /boot/efi/EFI/nixos/fw/fwupd-42f29620-3d63-4f09-950b-9b7055570f28.cap with 9417280 bytes
Aug 16 09:51:52 curie fwupd[1585]: 16:51:52:0070 Fu  FuHistory: modifying device 20F9CTO1WW System Firmware [444a229da2b21bc0d24faf814d1c58c5bff3315f], only version old 0.1.33
Aug 16 09:51:52 curie fwupd[1585]: 16:51:52:0079 Fu  Emitting PropertyChanged('Status'='idle')
```

**Comment by superm1** [comment] 2018-08-16 16:59
Can you check in your firmware setup if you have BootOrder locking turned on? (see https://blogs.gnome.org/hughsie/2018/08/06/please-welcome-lenovo-to-the-lvfs/ for Lenovo)

**Comment by tadfisher** [comment] 2018-08-23 23:13
@superm1 Boot Order Locking is not not enabled in UEFI settings.

In addition, I've removed all supervisor passwords and disabled firmware-update security requirements, but I still see the same errors.

It appears that some kernel feature is not enabled for fwupdmgr (or its efibootmgr dependency) to get information about the ESP. The `sys/devices/pci0000:00/firmware_node/uid` error in particular makes me suspect this.

**Comment by tadfisher** [comment] 2018-08-23 23:15
Also note that this is still happening on `fwupd` version 1.1.1.

**Comment by superm1** [comment] 2018-08-23 23:43
Is there some extra sandboxing being run? Can processes not access certain /sys directories?

**Comment by tadfisher** [comment] 2018-08-24 17:45
@superm1 Not that I know about. The `sys/devices/pci0000:00/firmware_node/uid` does not exist on this system.

I'll try updating the firmware via another method and see if that creates that sysfs node.

**Comment by superm1** [comment] 2018-08-24 17:49
Does `efibootmgr` work for you? it operates pretty similarly.  You should be able to set boot next from it.

**Comment by tadfisher** [comment] 2018-08-24 21:57
Nope:

```
efibootmgr --verbose --create-only --label Linux-Firmware-Updater --loader '\EFI\fwupdx64.efi' -p 3
Could not prepare Boot variable: No such file or directory
```

`/dev/sda3` is mounted at `/boot/efi`.

**Comment by tadfisher** [comment] 2018-08-28 18:46
I've traced this to code in `efivar` which appears to have been changed since the latest release:

https://github.com/rhboot/efivar/blob/36/src/linux-pci.c#L104

[This commit](https://github.com/rhboot/efivar/commit/6b62aa40cfa1feb924609a065098da98c99e925c) seems to avoid reading `firmware_node/uid` for ACPI root nodes. I'll try overriding the `efivar` package and give this a shot.

**Comment by tadfisher** [comment] 2018-08-28 19:30
Tried with `efivar` master, same issue. I reported an issue on [their tracker](https://github.com/rhboot/efivar/issues/120).

**Comment by superm1** [comment] 2018-08-28 19:41
So I guess for now, can you try to downgrade to efivar 35 to confirm that fixes it (and use that as a workaround?)

**Comment by tadfisher** [comment] 2018-08-28 19:48
What I meant was that both version 36 and master exhibit this issue, not that I suspect a change in 35->36 caused it. I'll try version 35 anyway to see if that helps.

**Comment by tadfisher** [comment] 2018-08-28 19:55
Same issue on version 35.

**Comment by superm1** [comment] 2018-08-28 19:56
Thanks for confirming.  I've personally tested using 34 on a variety of machines.  that's also what Debian & Ubuntu are carrying right now.  So you might have more luck there?

**Comment by superm1** [comment] 2018-08-29 17:28
Hum.  Is it tied to a newer kernel and the interface that efivar is using maybe then?

**Comment by tadfisher** [comment] 2018-08-29 20:31
Just tried with both 34 and 36 on 4.14, no dice. I also moved the ESP to /dev/sda1, thinking the partition detection is the problem, but that still emits the same errors.

I also did all of the above after manually flashing to the latest firmware, thinking the ACPI tables might be different in the newer firmware version and it might provide the `_SB_.PCI0._UID` method, but it doesn't. `/sys/devices/pci0000:00/firmware_node/uid` is just not a thing on this machine.

**Comment by tadfisher** [comment] 2018-09-20 17:33
I was able to complete an update using `efivar` master (commit https://github.com/rhboot/efivar/commit/cff35642eac6699e30549db2db3341e7657bf4a6).

However, something in the process wiped all EFI boot entries, so I'll have to recover from install media. Not sure if this is a problem with `efivar`, `fwupd`, or the Lenovo updater.

**Comment by superm1** [comment] 2018-09-20 17:38
Sounds like https://github.com/hughsie/fwupd/issues/709

From my opinion of reading the circumstances around it it sounds like a Lenovo bug to me, but you can share the `efibootmgr` output that was cached before the update to that bug to add some statistics to it that maybe will lead the lenovo guys to conclude what's wrong (don't know if they actually look at this stuff tough).

**Comment by Emantor** [comment] 2020-04-30 06:31
Closing since the initial issue has been solved by an update to `efivar` master (which surely has reached NixOS by now), the Lenovo firmware bug is a separate issue.

**Closed by Emantor** 2020-04-30 06:31 UTC
Labels: 0.kind: bug, 6.topic: hardware
