### ISSUE TITLE
parted: build failure

### ISSUE THREAD

**Issue by hyperfekt** [NixOS/nixpkgs#56737] opened 2019-03-02 23:13 UTC
## Issue description
GNU parted fails to build (be it on master, unstable, 18.09 or random commits from last year or 2015) because the test 0000 is failing.
t0000-basic.log:
```
parted (GNU parted) 3.2
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by <http://git.debian.org/?p=parted/parted.git;a=blob_plain;f=AUTHORS>.
--- exp 2019-03-02 22:22:55.534192084 +0000
+++ out 2019-03-02 22:22:55.527192037 +0000
@@ -1,3 +1,3 @@
 WARNING: You are not superuser.  Watch out for permissions.
 Warning: The existing disk label on DEVICE will be destroyed and all data on this disk will be lost. Do you want to continue?
-Yes/No? y
+Yes/No?
\ No newline at end of file
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.20.0, NixOS, 18.09.2275.060bcd6df50 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2280.80754f5cfd6, nixos-unstable-19.09pre171582.26d8a8c0eb2"`

**Comment by xeji** [comment] 2019-03-04 12:41
Cannot reproduce on current master. It does build fine on Hydra as well: https://hydra.nixos.org/jobset/nixpkgs/trunk/jobs-tab?filter=parted.

**Comment by hyperfekt** [comment] 2019-03-04 19:56
That's very weird. Any ideas why this could be happening just for me?

**Comment by xeji** [comment] 2019-03-05 09:15
Difficult to tell. I see that you have both 18.09 and master channels on your system. Mixing stable and unstable packages has occasionally created problems for me - for instance when the user environment and the NixOS system are on different releases. Overlays can also have weird side effects.

**Comment by hyperfekt** [comment] 2019-03-05 12:44
That's why I've made sure to build from the directory instead of the channels - that should have been enough for purity, should it not? Otherwise I would expect the `doCheck = false` overlay that I created as a reaction to first encountering this to hide the error. I've defined all my overlays via nixpkgs.overlays, there are none in `.config/nixpkgs/overlays`.
I've also made sure to ťry with both a nix-daemon of version 2.1.3 and 2.2.

**Comment by Enteee** [comment] 2020-03-16 18:15
Can not reproduce with current master (https://github.com/NixOS/nixpkgs/commit/fab05f17d15e4e125def4fd4e708d205b41d8d74). @hyperfekt I do not know what went wrong in your environment but without more information I would suggest closing this issue. Thank you.

**Comment by xeji** [comment] 2020-07-30 20:06
Closing since the mentioned NixOS versions are end-of-life. Please feel free to open a new issue if the problem reappears with a current version.

**Closed by xeji** 2020-07-30 20:06 UTC
