### ISSUE TITLE
GIMP was incorrectly upgraded to a plugin package

### ISSUE THREAD

**Issue by Hentioe** [NixOS/nixpkgs#115289] opened 2021-03-06 20:15 UTC
**Describe the bug**

When I run the `nix-env -u` command, `gimp-2.10.22` is upgraded to `gimp-2.10.22-plugin-wavelet-sharpen-0.1.2`.

**To Reproduce**

```bash
➜  ~ nix-env -iA nixos.gimp                                                                                           ~
installing 'gimp-2.10.22'
these paths will be fetched (0.26 MiB download, 2.79 MiB unpacked):
  /nix/store/653rbk2c1m7b7g7qay2xr18igz4m7pq6-libspiro-20200505
  /nix/store/nkp5fvmjqzxcgh956j82wyijdac9sv30-gegl-0.4.26-dev
  /nix/store/qnz8q16vwifr71d2f4xl7swgazy1m4l8-json-glib-1.6.2-dev
  /nix/store/sipz9rirjr2s74xm8jjy5qb0dji2pwxl-babl-0.1.84-dev
  /nix/store/sxff10pazkalfyhbc8z5ddwkmxw57j8g-gimp-2.10.22-dev
copying path '/nix/store/sipz9rirjr2s74xm8jjy5qb0dji2pwxl-babl-0.1.84-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/qnz8q16vwifr71d2f4xl7swgazy1m4l8-json-glib-1.6.2-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/653rbk2c1m7b7g7qay2xr18igz4m7pq6-libspiro-20200505' from 'https://cache.nixos.org'...
copying path '/nix/store/nkp5fvmjqzxcgh956j82wyijdac9sv30-gegl-0.4.26-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/sxff10pazkalfyhbc8z5ddwkmxw57j8g-gimp-2.10.22-dev' from 'https://cache.nixos.org'...
building '/nix/store/par3f3ia1l07gis3c006kfrmsq4avkp2-user-environment.drv'...
created 2423 symlinks in user environment
➜  ~ nix-env -u                                                                                                       ~
upgrading 'gimp-2.10.22' to 'gimp-2.10.22-plugin-wavelet-sharpen-0.1.2'
➜  ~
```

**Expected behavior**

Keep the version unchanged or upgrade the version of the GIMP package instead of being replaced by another package.

**Additional context**

In **unstable** channels.

**Notify maintainers**

@jtojnar 

**Metadata**

```bash
➜  ~ nix-shell -p nix-info --run "nix-info -m"                                                                        ~
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/zbiyhpj0gk7c5kbqj4nh4c5zhscmxpg4-bash-interactive-4.4-p23-dev
copying path '/nix/store/zbiyhpj0gk7c5kbqj4nh4c5zhscmxpg4-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.100, NixOS, 21.05pre274021.d496205cf22 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre274021.d496205cf22"`
 - channels(hentioe): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

➜  ~  
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

I don’t know how to write here, sorry.

**Comment by jtojnar** [comment] 2021-03-06 20:30
Duplicate of #114995

**Closed by jtojnar** 2021-03-06 20:30 UTC
Labels: 0.kind: bug
