### ISSUE TITLE
Package request: Webbot

### ISSUE THREAD

**Issue by Techno274721** [NixOS/nixpkgs#226529] opened 2023-04-16 20:52 UTC
**Project description**

Web automation library for simple and easy end to end testing and web browser automation that offers super charged features while keeping it simple to use and master

Read the dev article about this library : [https://dev.to/nateshmbhat/automate-your-web-pages-with-webbot-without-much-code-6ih](https://dev.to/nateshmbhat/automate-your-web-pages-with-webbot-without-much-code-6ih)

**Metadata**

* homepage URL: [pypi.org/project/webbot/](https://pypi.org/project/webbot/)
* source URL: https://github.com/nateshmbhat/webbot
* license: [MPL 2.0](https://github.com/nateshmbhat/webbot/blob/master/LICENSE)
* platforms: unix, linux, darwin.

**Comment by figsoda** [comment] 2023-05-16 02:58
duplicate of #159106

**Closed by figsoda** 2023-05-16 02:58 UTC
Labels: 0.kind: packaging request
