### ISSUE TITLE
duplicity-0.8.10 fails its test suite

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#82618] opened 2020-03-14 22:12 UTC
Current versions of `master` can no longer build `duplicity` because of the following test suite failures:

~~~
___________________________ Par2BackendTest.test_get ___________________________

self = <testing.unit.test_backend_instance.Par2BackendTest testMethod=test_get>

    def test_get(self):
        if self.backend is None:
            return
        self.backend._put(self.local, b'a')
        getfile = path.Path(u'testfiles/getfile')
>       self.backend._get(b'a', getfile)

unit/test_backend_instance.py:61: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../duplicity/backends/par2backend.py:125: in get
    self.wrapped_backend._get(par2file.get_filename(), par2file)
../duplicity/backends/localbackend.py:62: in _get
    local_path.writefileobj(source_path.open(u"rb"))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = ((b'a.par2',) b'testfiles/output/a.par2' None), mode = 'rb'

    def open(self, mode=u"rb"):
        u"""
        Return fileobj associated with self
    
        Usually this is just the file data on disk, but can be
        replaced with arbitrary data using the setfileobj method.
        """
        assert not self.opened
        if self.fileobj:
            result = self.fileobj
        else:
>           result = open(self.name, mode)
E           FileNotFoundError: [Errno 2] No such file or directory: b'testfiles/output/a.par2'

../duplicity/path.py:591: FileNotFoundError
__________________________ Par2BackendTest.test_move ___________________________

self = <testing.unit.test_backend_instance.Par2BackendTest testMethod=test_move>

    def test_move(self):
        if self.backend is None:
            return
        if not hasattr(self.backend, u'_move'):
            return
    
        copy = path.Path(u'testfiles/copy')
        self.local.copy(copy)
    
        self.backend._move(self.local, b'a')
        self.assertTrue(b'a' in self.backend._list())
        self.assertFalse(self.local.exists())
    
        getfile = path.Path(u'testfiles/getfile')
>       self.backend._get(b'a', getfile)

unit/test_backend_instance.py:141: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../duplicity/backends/par2backend.py:125: in get
    self.wrapped_backend._get(par2file.get_filename(), par2file)
../duplicity/backends/localbackend.py:62: in _get
    local_path.writefileobj(source_path.open(u"rb"))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = ((b'a.par2',) b'testfiles/output/a.par2' None), mode = 'rb'

    def open(self, mode=u"rb"):
        u"""
        Return fileobj associated with self
    
        Usually this is just the file data on disk, but can be
        replaced with arbitrary data using the setfileobj method.
        """
        assert not self.opened
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = ((b'a.par2',) b'testfiles/output/a.par2' None), mode = 'rb'

    def open(self, mode=u"rb"):
        u"""
        Return fileobj associated with self
    
        Usually this is just the file data on disk, but can be
        replaced with arbitrary data using the setfileobj method.
        """
        assert not self.opened
        if self.fileobj:
            result = self.fileobj
        else:
>           result = open(self.name, mode)
E           FileNotFoundError: [Errno 2] No such file or directory: b'testfiles/output/a.par2'

../duplicity/path.py:591: FileNotFoundError
__________________________ Par2BackendTest.test_move ___________________________

self = <testing.unit.test_backend_instance.Par2BackendTest testMethod=test_move>

    def test_move(self):
        if self.backend is None:
            return
        if not hasattr(self.backend, u'_move'):
            return
    
        copy = path.Path(u'testfiles/copy')
        self.local.copy(copy)
    
        self.backend._move(self.local, b'a')
        self.assertTrue(b'a' in self.backend._list())
        self.assertFalse(self.local.exists())
    
        getfile = path.Path(u'testfiles/getfile')
>       self.backend._get(b'a', getfile)

unit/test_backend_instance.py:141: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../duplicity/backends/par2backend.py:125: in get
    self.wrapped_backend._get(par2file.get_filename(), par2file)
../duplicity/backends/localbackend.py:62: in _get
    local_path.writefileobj(source_path.open(u"rb"))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = ((b'a.par2',) b'testfiles/output/a.par2' None), mode = 'rb'

    def open(self, mode=u"rb"):
        u"""
        Return fileobj associated with self
    
        Usually this is just the file data on disk, but can be
        replaced with arbitrary data using the setfileobj method.
        """
        assert not self.opened
        if self.fileobj:
            result = self.fileobj
        else:
>           result = open(self.name, mode)
E           FileNotFoundError: [Errno 2] No such file or directory: b'testfiles/output/a.par2'

../duplicity/path.py:591: FileNotFoundError
============ 2 failed, 427 passed, 11 skipped in 586.37s (0:09:46) =============
~~~

It feels like b5126937b4031cfb30733559935c3e2f4afcb5e5 might be the cause.

Ping @FRidh.

**Comment by FRidh** [comment] 2020-03-15 09:01
I just build b512693 locally, although it did not appear to build on Hydra. This is a regression then due to a dependency change.

**Comment by FRidh** [comment] 2020-03-15 09:02
These seem to be `par2backend` tests that are failing. We did recently update `par2cmdline` from 0.7.3 to 0.8.0 and 0.8.0 to 0.8.1 in 9ccb0f39554d4b7fdb75dcf757e9862029821694 and 5a0bbfa7f27e554866f4a248d0ab2d6c3de9e78d.

**Comment by FRidh** [comment] 2020-03-15 09:06
Reverting 5a0bbfa7f27e554866f4a248d0ab2d6c3de9e78d solves this issue. There is also duplicity 0.8.1 which includes a workaround for par2cmdline 0.8.1 according to the changelog. cc @jtojnar

**Comment by jtojnar** [comment] 2020-03-15 09:44
Let's merge https://github.com/NixOS/nixpkgs/pull/82400 then.

**Comment by jtojnar** [comment] 2020-03-16 11:17
Fixed by https://github.com/NixOS/nixpkgs/pull/82400

**Closed** 2020-03-16 12:04 UTC
Labels: 0.kind: regression, 6.topic: python
