### ISSUE TITLE
Haskell major version alias

### ISSUE THREAD

**Issue by guibou** [NixOS/nixpkgs#109257] opened 2021-01-13 08:56 UTC
**Describe the bug**

Currently we can access ghc and haskell packaging using either:

- An arbitrary version (the "current" one) using either `ghc` or `haskellPackages`
- A precise version, including minor version number, using for example `ghc.compiler.ghc8103` and `haskell.packages.ghc8103`.

The problem with this approach is that:

- binary caches may only provides cached version for the "latest" minor version. for example, if `ghc8101`, `ghc8102` and `ghc8103` exists, there may only be cached version for `ghc8103`.
- user may want to depend on a specific "major" version of GHC, for example `ghc 8.10` (i.e. `ghc810x`) and update "automatically" to the latest "minor" version available.

**Expected behavior**

I propose to introduce aliases for major ghc version. for example, `ghc810x` -> `ghc8103`.

However, a "safety" mecanism must be introduced in nixpkgs in order to ensure that the alias stays in sync.

**Notify maintainers**

@peti

**Comment by cole-h** [comment] 2021-01-13 19:32
Dupe of https://github.com/NixOS/nixpkgs/issues/109256 (double-posted by accident?). Only difference is the title.

**Closed by cole-h** 2021-01-13 19:32 UTC
Labels: 0.kind: bug, 6.topic: haskell

**Comment by guibou** [comment] 2021-01-14 09:41
(Sorry, github chock when posting with a "fatal error", I just go back in history, change the now empty title, and submited again.
