### ISSUE TITLE
Build failure: nextcloud-client

### ISSUE THREAD

**Issue by Soliprem** [NixOS/nixpkgs#326706] opened 2024-07-13 04:56 UTC
### Steps To Reproduce

1. build nextcloud-client on the nixos-unstable branch

### Build log

```
error: hash mismatch in fixed-output derivation '/nix/store/zg2zsi4nkgnhn92nj3qqmyd12kvban13-source.drv':
         specified: sha256-z4yxWClbs05ZCT8CPJpPY2BWMSXxfJ09Lq3Oottx7dQ=
            got:    sha256-hZjmAdh9QQ2bAIYL3K7scl59kz9Wxnv9f6rKMeuKb7U=
```

### Additional context
I assume changing the hash at https://github.com/NixOS/nixpkgs/blob/85de798ad5cd3910527b47386257aa801e38cfe2/pkgs/applications/networking/nextcloud-client/default.nix#L37 to sha256-z4yxWClbs05ZCT8CPJpPY2BWMSXxfJ09Lq3Oottx7dQ= would fix the issue

### Notify maintainers

@Ma27 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
fetching path input 'path:/nix/store/xr9wjzx0cdnwkmhzz74h8lphgn5jmyv3-source'
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.37, NixOS, 24.11 (Vicuna), 24.11.20240709.feb2849`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0-rc1`
 - nixpkgs: `/nix/store/xr9wjzx0cdnwkmhzz74h8lphgn5jmyv3-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-07-13 05:01
duplicate of #326258
fixed in #326093

**Closed by eclairevoyant** 2024-07-13 05:01 UTC
Labels: 0.kind: build failure
