### ISSUE TITLE
Package request: howdy

### ISSUE THREAD

**Issue by renhiyama** [NixOS/nixpkgs#254188] opened 2023-09-09 07:48 UTC
**Project description**

Howdy provides Windows Hello™ style authentication for Linux. Use your built-in IR emitters and camera in combination with facial recognition to prove who you are.

Using the central authentication system (PAM), this works everywhere you would otherwise need your password: Login, lock screen, sudo, su, etc.

**Metadata**

* homepage URL: https://github.com/boltgolt/howdy/wiki/Common-issues
* source URL: https://github.com/boltgolt/howdy
* license: mit
* platforms: linux

**Comment by kashw2** [comment] 2023-09-10 13:02
https://github.com/NixOS/nixpkgs/pull/216245

**Comment by kashw2** [comment] 2023-09-11 02:41
duplicate of https://github.com/NixOS/nixpkgs/issues/76928

**Closed by kashw2** 2023-09-11 02:41 UTC
Labels: 0.kind: packaging request
