### ISSUE TITLE
nixos-activation script failing to start due to missing XDG_CONFIG_HOME env variable

### ISSUE THREAD

**Issue by mdedetrich** [NixOS/nixpkgs#81066] opened 2020-02-25 23:16 UTC
**Describe the bug**
When updating a system on the nixos-unstable channel that is using kde, you get the following message.

```
Job for `nixos-activation.service` failed because the control process exited with error code.
See "systemctl --user status nixos-activation.service" and "journalctl --user -xe" for details.
```

**To Reproduce**
1. Have a nixos system on nixos-unstable using kde.
2. Update system with sudo nixos-rebuild switch

**Expected behavior**
The `nixos-activation.service` service restarts without issues.

**Additional context**
The journal ctl log is here
```
-- Reboot --
Feb 26 00:03:04 mdedetrich-nixos-laptop systemd[1317]: Starting Run user-specific NixOS activation...
Feb 26 00:03:04 mdedetrich-nixos-laptop z07ggcqgi0b6imajc5z045x7isipbgf5-unit-script-nixos-activation-start[19333]: removed '/home/mdedetrich/.cache/icon-cache.kcache'
Feb 26 00:03:04 mdedetrich-nixos-laptop z07ggcqgi0b6imajc5z045x7isipbgf5-unit-script-nixos-activation-start[19333]: /nix/store/z07ggcqgi0b6imajc5z045x7isipbgf5-unit-script-nixos-activation-start: line 22: XDG_CONFIG_HOME: parameter null or not set
Feb 26 00:03:04 mdedetrich-nixos-laptop systemd[1317]: nixos-activation.service: Main process exited, code=exited, status=1/FAILURE
Feb 26 00:03:04 mdedetrich-nixos-laptop systemd[1317]: nixos-activation.service: Failed with result 'exit-code'.
Feb 26 00:03:04 mdedetrich-nixos-laptop systemd[1317]: Failed to start Run user-specific NixOS activation.
```

**Metadata**
```
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/8zqljq8rbb29whgz9m7jv1i9n24llswi-bash-interactive-4.4-p23-dev
copying path '/nix/store/8zqljq8rbb29whgz9m7jv1i9n24llswi-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.5, NixOS, 20.09pre214664.d363be93b49 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre214664.d363be93b49"`
 - channels(mdedetrich): `"nixpkgs-20.09pre214374.1fe82110feb"`
 - nixpkgs: `/home/mdedetrich/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
attribute: kde
```

**Comment by worldofpeace** [comment] 2020-02-26 01:57
duplicate of https://github.com/NixOS/nixpkgs/issues/80713

**Closed by worldofpeace** 2020-02-26 01:57 UTC
Labels: 0.kind: bug
