### ISSUE TITLE
Build failure: python311Packages.afdko (with utf8cpp 4.0.4+)

### ISSUE THREAD

**Issue by spiage** [NixOS/nixpkgs#278546] opened 2024-01-03 19:32 UTC
#276579 was reverted since it breaks `python311Packages.afdko`, with

```
error: builder for '/nix/store/af6l5pc3zm9zdiamr0q5f9fkr86ql015-python3.11-afdko-4.0.0.drv' failed with exit code 1;
       last 10 log lines:
       > ../../nix/store/6dsx7y855a79l3ynz9vpk0y2fddyl5pj-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/pkg_resources/__init__.py:2350
       >   /nix/store/6dsx7y855a79l3ynz9vpk0y2fddyl5pj-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/pkg_resources/__init__.py:2350: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('fs')`.
       >   Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
       >     declare_namespace(parent)
       >
       > -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
       > =========================== short test summary info ============================
       > FAILED tests/tx_test.py::test_alt_missing_glyph - AssertionError: assert False
       > = 1 failed, 1448 passed, 6 skipped, 90 deselected, 8 xfailed, 4 warnings in 70.83s (0:01:10) =
       > /nix/store/d4jf1cbbk494zwgbqz31pxgigpsbh6w2-stdenv-linux/setup: line 1553: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/af6l5pc3zm9zdiamr0q5f9fkr86ql015-python3.11-afdko-4.0.0.drv'.
```

_Originally posted by @spiage in https://github.com/NixOS/nixpkgs/issues/276579#issuecomment-1875862095_

**Comment by spiage** [comment] 2024-01-03 19:37
[Build_issue_with_python3.11-afdko-4.0.0.log](https://github.com/NixOS/nixpkgs/files/13822699/Build_issue_with_python3.11-afdko-4.0.0.log)

**Comment by LunNova** [comment] 2024-01-14 01:49
`nixpkgs#python3Packages.afdko --rebuild` still fails after the revert, but the package is cached and works.

I think afdko broke due to some impurity (test which needed the year to be 2023? :thinking: ) and the old cached build is ok, the utf8cpp bump wasn't the cause of the issue but made it visible by causing a rebuild.

That or it's inconsistent and succeeds sometimes.

@wegank

**Comment by lilyinstarlight** [comment] 2024-01-19 11:48
> test which needed the year to be 2023?

Yeah looks like they were checking copyright year for some test...

It seems the fix for not checking that anymore was included in https://github.com/adobe-type-tools/afdko/pull/1730 so it might just need to be bumped to afdko 4.0.1 to fix the issue for good

**Comment by wegank** [comment] 2024-01-19 15:30
Closed by https://github.com/NixOS/nixpkgs/commit/9dbb6cc654601658c33773206382f2db008a056a.

**Closed by wegank** 2024-01-19 15:30 UTC
