### ISSUE TITLE
Upgrade digikam: 6.2.0 -> 6.4.0

### ISSUE THREAD

**Issue by kuznero** [NixOS/nixpkgs#77581] opened 2020-01-12 21:58 UTC
**Project description**

GitHub repository is stale, instead [this](https://invent.kde.org/kde/digikam.git) one should be used.

I have made an [attempt](https://github.com/kuznero/nixpkgs/tree/kuznero/digikam) to upgrade it, but it fails unable to resolve `${exiv2.dev}/include` somehow.

**Metadata**

* homepage URL:
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by evanjs** [comment] 2020-07-24 23:06
https://digikam.org/news/2020-07-19-7.0.0_release_announcement/

Tempted to see if there are any issues building 7.0.0

**Comment by callahad** [comment] 2020-08-08 20:38
Thinking out loud: I'm similarly interested in updating digiKam. I've tried building 7.0.0 and also ran into issues with cmake and exiv2:

```
CMake Error at /nix/store/svp61b8162v6vfh4gk5a4bmxz4nbvy1z-exiv2-0.27.2-dev/lib/cmake/exiv2/exiv2Config.cmake:85 (message):
  The imported target "exiv2-xmp" references the file

     "/nix/store/svp61b8162v6vfh4gk5a4bmxz4nbvy1z-exiv2-0.27.2-dev/lib/libexiv2-xmp.a"

  but this file does not exist.
```

So it looks like it's looking for `/lib/libexiv2-xmp.a` inside `${exiv2.dev}`, but that file is actually present in the default `out` target, not the `dev` one. Not entirely sure how to resolve, but I'll poke at bit by bit over the coming days.

**Comment by evanjs** [comment] 2020-08-08 21:15
> Thinking out loud: I'm similarly interested in updating digiKam. I've tried building 7.0.0 and also ran into issues with cmake and exiv2:
> 
> ```
> CMake Error at /nix/store/svp61b8162v6vfh4gk5a4bmxz4nbvy1z-exiv2-0.27.2-dev/lib/cmake/exiv2/exiv2Config.cmake:85 (message):
>   The imported target "exiv2-xmp" references the file
> 
>      "/nix/store/svp61b8162v6vfh4gk5a4bmxz4nbvy1z-exiv2-0.27.2-dev/lib/libexiv2-xmp.a"
> 
>   but this file does not exist.
> ```
> 
> So it looks like it's looking for `/lib/libexiv2-xmp.a` inside `${exiv2.dev}`, but that file is actually present in the default `out` target, not the `dev` one. Not entirely sure how to resolve, but I'll poke at bit by bit over the coming days.

Thanks for taking a look at this! I initially found this and totally forgot to post... 

Everything seems to be present but the `buildPhase` acts like it can’t find anything. 

As far as I know, files in either `out` or `dev` should be fine, so I’m not sure what is going on with this one.
 
Interested to know if you or anybody else finds anything on this, though.

**Comment by callahad** [comment] 2020-08-08 21:33
Looks similar to the clang problem fixed in #33953

Taking the same approach with exiv2 yields the following patch to its `postInstall` script:

```patch
diff --git a/pkgs/development/libraries/exiv2/default.nix b/pkgs/development/libraries/exiv2/default.nix
index 8a6dfd1983e..c22802f563d 100644
--- a/pkgs/development/libraries/exiv2/default.nix
+++ b/pkgs/development/libraries/exiv2/default.nix
@@ -106,6 +106,10 @@ stdenv.mkDerivation rec {
       rm *
       mv .exiv2 exiv2
     )
+
+    # Ensure libs can be found
+    substituteInPlace $out/lib/cmake/exiv2/exiv2Config-release.cmake \
+          --replace "\''${_IMPORT_PREFIX}/lib/libexiv2" "$out/lib/libexiv2"
   '';
 
   enableParallelBuilding = true;
```

After the above patch, digiKam *is* able to find exiv2... now to wait and see if it actually builds successfully... :)

**Comment by callahad** [comment] 2020-08-08 22:40
Built successfully with the above patch and this:

```patch
diff --git a/pkgs/applications/graphics/digikam/default.nix b/pkgs/applications/graphics/digikam/default.nix
index 63b8d7b3f60..4b1d0561d3c 100644
--- a/pkgs/applications/graphics/digikam/default.nix
+++ b/pkgs/applications/graphics/digikam/default.nix
@@ -1,4 +1,4 @@
-{ mkDerivation, lib, fetchFromGitHub, cmake, doxygen, extra-cmake-modules, wrapGAppsHook
+{ mkDerivation, lib, fetchurl, cmake, doxygen, extra-cmake-modules, wrapGAppsHook
 
 # For `digitaglinktree`
 , perl, sqlite
@@ -26,6 +26,8 @@
 , exiv2
 , ffmpeg
 , flex
+, graphviz
+, imagemagick
 , jasper ? null, withJpeg2k ? false  # disable JPEG2000 support, jasper has unfixed CVE
 , lcms2
 , lensfun
@@ -41,6 +43,7 @@
 , opencv3
 , pcre
 , threadweaver
+, x265
 
 # For panorama and focus stacking
 , enblend-enfuse
@@ -52,13 +55,11 @@
 
 mkDerivation rec {
   pname   = "digikam";
-  version = "6.2.0";
+  version = "7.0.0";
 
-  src = fetchFromGitHub {
-    owner  = "KDE";
-    repo   = "digikam";
-    rev    = "v${version}";
-    sha256 = "1l1nb1nwicmip2jxhn5gzr7h60igvns0zs3kzp36r6qf4wvg3v2z";
+  src = fetchurl {
+    url = "mirror://kde/stable/${pname}/${version}/${pname}-${version}.tar.xz";
+    sha256 = "04g94s5lvkx5nr0kc1i75pqn3vbzg57b8rsky3br5rii03iih1yw";
   };
 
   nativeBuildInputs = [ cmake doxygen extra-cmake-modules kdoctools wrapGAppsHook ];
@@ -70,6 +71,8 @@ mkDerivation rec {
     exiv2
     ffmpeg
     flex
+    graphviz
+    imagemagick
     lcms2
     lensfun
     libgphoto2
@@ -82,6 +85,7 @@ mkDerivation rec {
     libGLU
     opencv3
     pcre
+    x265
 
     qtbase
     qtxmlpatterns
```

Will submit a proper pull request in a few days

**Comment by evanjs** [comment] 2020-08-09 00:05
Mmmmm x265. 

Thanks, @callahad!

**Comment by callahad** [comment] 2020-08-10 15:55
Yep, everything seems to work as expected. Opening pull requests shortly.

**Comment by jtojnar** [comment] 2020-08-12 01:59
That makes no sense. The files are as follows:

### `exiv2Config.cmake`

```cmake
# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget exiv2-xmp exiv2lib)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
set(_IMPORT_PREFIX "/nix/store/s34c5w0h7kdbb46114m1x6a0ascyiqdj-exiv2-0.27.2")
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target exiv2-xmp
add_library(exiv2-xmp STATIC IMPORTED)

set_target_properties(exiv2-xmp PROPERTIES
  INTERFACE_LINK_LIBRARIES "/nix/store/pg71kfxk5wh3g9djymgm7v55b3hs29bx-expat-2.2.8/lib/libexpat.so"
)

# Create imported target exiv2lib
add_library(exiv2lib SHARED IMPORTED)

set_target_properties(exiv2lib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/nix/store/yvaci842j7ciy3wpi300q11r7pxl2r4n-exiv2-0.27.2-dev/include"
)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/exiv2Config-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
```

### `exiv2Config-release.cmake`

```cmake
#----------------------------------------------------------------
# Generated CMake target import file for configuration "Release".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "exiv2-xmp" for configuration "Release"
set_property(TARGET exiv2-xmp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(exiv2-xmp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libexiv2-xmp.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS exiv2-xmp )
list(APPEND _IMPORT_CHECK_FILES_FOR_exiv2-xmp "${_IMPORT_PREFIX}/lib/libexiv2-xmp.a" )

# Import target "exiv2lib" for configuration "Release"
set_property(TARGET exiv2lib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(exiv2lib PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libexiv2.so.0.27.2"
  IMPORTED_SONAME_RELEASE "libexiv2.so.27"
  )

list(APPEND _IMPORT_CHECK_TARGETS exiv2lib )
list(APPEND _IMPORT_CHECK_FILES_FOR_exiv2lib "${_IMPORT_PREFIX}/lib/libexiv2.so.0.27.2" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
```

so the `exiv2-xmp` should be located in `${_IMPORT_PREFIX}/lib/libexiv2-xmp.a` and the `${_IMPORT_PREFIX}` variable is set up correctly.

**Comment by jtojnar** [comment] 2020-08-12 02:16
I can reproduce with

```nix
let
  nixpkgs = import (fetchTarball {
    url = "https://github.com/NixOS/nixpkgs/archive/eac5ef8aa9c0ddd948b20e83d9d7b37cd0132a81.tar.gz";
    sha256 = "1hf4cc8snllb8wxa4c5rvwrdg892sqcq7p7qjq08i5yfj4ifbn9n";
  }) {};
  cmakelists = nixpkgs.writeText "CMakeLists.txt" ''
    project(foo CXX)
    find_package(exiv2)
  '';

in
nixpkgs.runCommandCC "test" {
  nativeBuildInputs = [ nixpkgs.cmake ];
  buildInputs = [ nixpkgs.exiv2 ];
} ''
  cp ${cmakelists} CMakeLists.txt
  cmake .
  touch $out
''
```

Super weird.

**Comment by callahad** [comment] 2020-08-12 02:39
Looks like the way digiKam located exiv2 changed between versions 6.3.0 and 6.4.0.

In prior versions of digiKam, there was a file `core/cmake/modules/FindExiv2.cmake`, but this was removed in [06e77271d72fe5e4abeb38641f3addc2cfbff126](https://invent.kde.org/graphics/digikam/-/commit/06e77271d72fe5e4abeb38641f3addc2cfbff126) with the commit message:

> Exiv2 is now released with exported targets using cmake rules. No need to have a dedicated find exiv2 cmake script. Bump minimal version to 0.27.1

...it then tries to add exiv2 as `target_link_libraries(digikamcore PRIVATE ... exiv2lib)`, which fails.

**Comment by callahad** [comment] 2020-08-12 03:30
Looks like exiv2 is fixed in `master`, so a PR to upgrade to digikam 7.0.0 should now be possible. Will submit that tomorrow.

**Comment by tyrion** [comment] 2020-09-19 16:07
Hello, any progress on this?

I tried building digikam 7.1.0 from nixos-unstable (I added graphviz, imagemagick and x265 to buildInputs) and after a very long compilation it failed like this:
```
[ 93%] Linking CXX executable showfoto
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/frsdjclamwdk7n2ycd71vc2f25d90ay1-qtdeclarative-5.15.0/lib/libQt5Quick.so.5: undefined reference to `QStringRef::split(QChar, QFlags<Qt::SplitBehaviorFlags>, Qt::CaseSensitivity) const@Qt_5'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/awih3w3lh1idkkc2zsf60z1d0ifv22wd-kcoreaddons-5.73.0/lib/libKF5CoreAddons.so.5.73.0: undefined reference to `QString::split(QString const&, QFlags<Qt::SplitBehaviorFlags>, Qt::CaseSensitivity) const@Qt_5'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/g8rgxkb290nclz82j38hh8fjxsbpw44m-kwidgetsaddons-5.73.0/lib/libKF5WidgetsAddons.so.5.73.0: undefined reference to `QLabel::pixmap(Qt::ReturnByValueConstant) const@Qt_5'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/frsdjclamwdk7n2ycd71vc2f25d90ay1-qtdeclarative-5.15.0/lib/libQt5Quick.so.5: undefined reference to `Qt::dec(QTextStream&)@Qt_5'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/cjhjrbj0jypqhz7y366jai7v9gvgf55k-kservice-5.73.0/lib/libKF5Service.so.5.73.0: undefined reference to `QString::splitRef(QChar, QFlags<Qt::SplitBehaviorFlags>, Qt::CaseSensitivity) const@Qt_5'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/frsdjclamwdk7n2ycd71vc2f25d90ay1-qtdeclarative-5.15.0/lib/libQt5Qml.so.5: undefined reference to `QMetaProperty::isRequired() const@Qt_5'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/igx53ifhndz1qpbg4h51pxb0ss4y7h33-knotifyconfig-5.73.0/lib/libKF5NotifyConfig.so.5.73.0: undefined reference to `qt_version_tag@Qt_5.15'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/frsdjclamwdk7n2ycd71vc2f25d90ay1-qtdeclarative-5.15.0/lib/libQt5Qml.so.5: undefined reference to `Qt::right(QTextStream&)@Qt_5'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/1c6f8migfylfhwrvz3csb3mnrslkawfq-qtwebengine-5.14.2/lib/libQt5WebEngine.so.5: undefined reference to `QtWebEngineCore::WebContentsAdapter::runUserNotificationRequestCallback(QUrl const&, bool)@Qt_5'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/frsdjclamwdk7n2ycd71vc2f25d90ay1-qtdeclarative-5.15.0/lib/libQt5Quick.so.5: undefined reference to `QAbstractSocket::errorOccurred(QAbstractSocket::SocketError)@Qt_5'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/7g8sv9w9kdyvif614jvr0r2sx5b0z200-qtwebchannel-5.15.0/lib/libQt5WebChannel.so.5: undefined reference to `Qt::endl(QTextStream&)@Qt_5'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/frsdjclamwdk7n2ycd71vc2f25d90ay1-qtdeclarative-5.15.0/lib/libQt5Quick.so.5: undefined reference to `Qt::hex(QTextStream&)@Qt_5'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/igx53ifhndz1qpbg4h51pxb0ss4y7h33-knotifyconfig-5.73.0/lib/libKF5NotifyConfig.so.5.73.0: undefined reference to `QString::split(QChar, QFlags<Qt::SplitBehaviorFlags>, Qt::CaseSensitivity) const@Qt_5'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/awih3w3lh1idkkc2zsf60z1d0ifv22wd-kcoreaddons-5.73.0/lib/libKF5CoreAddons.so.5.73.0: undefined reference to `QString::splitRef(QRegularExpression const&, QFlags<Qt::SplitBehaviorFlags>) const@Qt_5'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/frsdjclamwdk7n2ycd71vc2f25d90ay1-qtdeclarative-5.15.0/lib/libQt5Quick.so.5: undefined reference to `QColorSpace::operator QVariant() const@Qt_5'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/frsdjclamwdk7n2ycd71vc2f25d90ay1-qtdeclarative-5.15.0/lib/libQt5Quick.so.5: undefined reference to `QRhi::newSampler(QRhiSampler::Filter, QRhiSampler::Filter, QRhiSampler::Filter, QRhiSampler::AddressMode, QRhiSampler::AddressMode, QRhiSampler::AddressMode)@Qt_5_PRIVATE_API'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/frsdjclamwdk7n2ycd71vc2f25d90ay1-qtdeclarative-5.15.0/lib/libQt5Qml.so.5: undefined reference to `QMetaType::name() const@Qt_5'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/7g8sv9w9kdyvif614jvr0r2sx5b0z200-qtwebchannel-5.15.0/lib/libQt5WebChannel.so.5: undefined reference to `QJsonArray::QJsonArray(QJsonArray&&)@Qt_5'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/frsdjclamwdk7n2ycd71vc2f25d90ay1-qtdeclarative-5.15.0/lib/libQt5Quick.so.5: undefined reference to `QThread::wait(QDeadlineTimer)@Qt_5'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/dq9y4k8lm0ir10b41071w040gz3brm0h-qtlocation-5.15.0/lib/libQt5Positioning.so.5: undefined reference to `QJsonObject::QJsonObject(QJsonObject&&)@Qt_5'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/cjhjrbj0jypqhz7y366jai7v9gvgf55k-kservice-5.73.0/lib/libKF5Service.so.5.73.0: undefined reference to `QJsonValue::swap(QJsonValue&)@Qt_5'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/ip5cxw19qka2d7fq9ck3pc5zddn9ykhv-kxmlgui-5.73.0/lib/libKF5XmlGui.so.5.73.0: undefined reference to `QPushButton::hitButton(QPoint const&) const@Qt_5'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/1c6f8migfylfhwrvz3csb3mnrslkawfq-qtwebengine-5.14.2/lib/libQt5WebEngine.so.5: undefined reference to `QtWebEngineCore::WebContentsAdapter::runGeolocationRequestCallback(QUrl const&, bool)@Qt_5'
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: /nix/store/rp26gfdwlfn3ww3m7cls41cnlmc7hbnw-kcodecs-5.73.0/lib/libKF5Codecs.so.5.73.0: undefined reference to `QRegularExpression::anchoredPattern(QStringView)@Qt_5'
collect2: error: ld returned 1 exit status
make[2]: *** [core/showfoto/CMakeFiles/showfoto.dir/build.make:481: core/showfoto/showfoto] Error 1
make[1]: *** [CMakeFiles/Makefile2:19144: core/showfoto/CMakeFiles/showfoto.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
builder for '/nix/store/kinibm7kd992pd8wfili976dj1077bns-digikam-7.1.0.drv' failed with exit code 2
```

**Comment by callahad** [comment] 2020-09-19 17:20
Unfortunately, I got swept up in the wave of Mozilla layoffs last month, so
my free time has been fully dedicated to a job search instead of updating
this derivation.

The good news is I expect to be done with all of that next week, and --
since I don't have a job -- this is now the top item on my software to-do
list.

If I don't have a pull request ready by this time next week, I'll mail a
vintage Mozilla sticker to the first person to call me out on my failing. 😉

**Comment by callahad** [comment] 2020-09-25 08:16
Closing this issue; master has 6.4.0 as of commit 347ef4f7689566aa7b8d4c097d0e75029d5ce98a, so the title is misleading.

Pull request to upgrade from 6.4.0 to 7.1.0 is at https://github.com/NixOS/nixpkgs/pull/98721

Note that video playback is currently broken due to 5194e7c0cbb4601df1a57531bf5955c35bbf4314, which I intend to address after 7.1.0 gets merged.

**Closed by callahad** 2020-09-25 08:16 UTC
Labels: 0.kind: packaging request, 6.topic: qt/kde, 9.needs: package (update)
