### ISSUE TITLE
_module.args.name gets merged on assignment

### ISSUE THREAD

**Issue by sphaugh** [NixOS/nixpkgs#53458] opened 2019-01-05 19:11 UTC
## Issue description

If I have an option `"foo"` of type `attrsOf (submodule bar)` and I assign an attrset with `_module.args.name` `"bar"`, the configuration of `submodule bar` will see its name as `"foobar"`.

This is because `_module.args` is `types.unspecified` which follows the default merging rules, but I'm not sure how to fix it (or if it's working as designed).

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.91, NixOS, 18.09.1834.9d608a6f592 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(sean): `"nixos-19.03pre165037.eebd1a92637, nixpkgs-19.03pre165019.c06debd3f9d"`
 - channels(root): `"nixos-18.09.1834.9d608a6f592"`
 - nixpkgs: `/home/sean/.nix-defexpr/channels/nixpkgs`

**Comment by furrycatherder** [comment] 2019-01-05 19:13
https://github.com/NixOS/nixpkgs/pull/53443 This was my attempt but it seems to break things horribly.

**Comment by danbst** [comment] 2019-01-06 09:05
I'm not saying, that issue will be fixed when you provide reproduction steps of your issue, but that would be a great start. For example, I don't follow where `programs.neomutt.mailboxes` option comes from

**Comment by furrycatherder** [comment] 2019-01-06 16:15
@danbst Sure, let me see if I can provide a MWE so people can play with it. The root cause is in the issue description, though, afaict.

https://github.com/furrycatherder/mwe-nixpkgs-53458

This configuration:
```
{ config, lib, ... }:
{
  has."sensei" = { item = "chicken katsu"; };

  wants."jonas" = config.has."sensei";
}
```
```
nix-repl> mwe = import (fetchGit { url = "https://github.com/furrycatherder/mwe-nixpkgs-53458"; ref = "master"; })

nix-repl> mwe
fetching Git repository 'https://github.com/furrycatherder/mwe-nixpkgs-53458'warning: no common commits
{ config = { ... }; options = { ... }; }

nix-repl> mwe.config.wants.jonas
{ _module = { ... }; factoid = "senseijonas wants chicken katsu"; item = "chicken katsu"; }
```

**Comment by danbst** [comment] 2019-01-07 08:51
@furrycatherder yeah, nasty bug. I've combined your example into one file:
```
with import <nixpkgs> {};
let

  option = lib: lib.mkOption {
    type = with lib.types; attrsOf (submodule {});
  };

  module = { config, lib, ... }: {
    options.o1 = option lib;
    options.o2 = option lib;
  };

  configuration = { config, ... }: {
    o1.a = {};

    o2.a = config.o1.a;
    # counterintuitive, but same as
    #o2.a = {
    #  _module.args.name = "a";
    #};

    # Causes infinite recursion
    #o1.b = config.o2.a;
  };

in with lib.evalModules {
  modules = [
    module
    configuration
  ];
};
config
```
And result of invocation:
```
$ nix eval '(import ./test.nix)' --json | jq
{
  "_module": {
    "args": {},
    "check": true
  },
  "o1": {
    "a": {
      "_module": {
        "args": {
          "name": "a"
        },
        "check": true
      }
    }
  },
  "o2": {
    "a": {
      "_module": {
        "args": {
          "name": "aa"
        },
        "check": true
      }
    }
  }
}
```
I can't think of what exactly is wrong here. Surely, `name` shouldn't merge. But should this code pattern be allowed at all? cc @nbp

**Comment by Infinisil** [comment] 2020-09-29 21:09
Still a problem, here's a repro that works after https://github.com/NixOS/nixpkgs/pull/82751:
```nix
with import ./lib;
evalModules {
  modules = [({ lib, ... }: {
    options.value = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule ({ name, ... }: {
        options.nameValue = lib.mkOption {
          default = name;
        };
      }));
    };

    config.value.x = {
      _module.args.name = "y";
    };

  })];
}
```

**Comment by roberth** [comment] 2022-02-17 18:24
@Infinisil, replacing `types.unspecified` by `types.raw` (#160489) seems excessive, losing the ability to `mkForce`. What about `types.anything`? It seems to have a reasonable merge function.

**Comment by Infinisil** [comment] 2022-02-17 18:48
@roberth See https://github.com/NixOS/nixpkgs/pull/160489#issuecomment-1043295380, `mkForce` and co. still work

**Closed** 2022-02-23 13:08 UTC
Labels: 6.topic: module system

**Comment by dminuoso** [comment] 2022-06-02 09:19
This change is unfortunate.

Right now we place utility functions into _module.args.utils, and this happens across several modules (split across several git repositories, even). This change breaks this ability and likely affects more users that haven't started migrating yet.

Could we perhaps change to a submodule with freeformType undefined, such that individual options like `name` can pick their suitable merge strategy?

**Comment by roberth** [comment] 2022-06-02 18:22
> Right now we place utility functions into _module.args.utils, and this happens across several modules (split across several git repositories, even).

This is asking for trouble. Logic is better represented by either 
1. submodules that compute (e.g. `mkOption { readOnly = true; ... }`), or
2. library expressions that you can import as usual

The latter is easiest to test.

> Could we perhaps change to a submodule with freeformType undefined,

We'll want to set its freeformType to `lazyAttrsOf raw` though, as `_module.args` has always been open for extension like that. The point of freeformType is that it doesn't prevent the improvement of types.
Since https://github.com/NixOS/nixpkgs/pull/156533, you don't even have to specify that you're type-merging with the `_module.args` submodule anymore, so you'd be able to say directly: `_module.args.foo = mkOption { }`.

**Comment by roberth** [comment] 2022-06-02 21:07
@dminuoso I don't think we have a viable solution within the module system.

For now I can only recommend to avoid merging in `_module.args.<name>`. You can merge in another option beforehand if you must. E.g. `{ config, lib, ... }: { options.myOption = mkOption xyz; config._module.args.myOption = config.myOption; }`.
