### ISSUE TITLE
`python3Packages.jaxlib` build failure on x86_64-linux as of `7cdce123`

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#246125] opened 2023-07-30 01:49 UTC
## Issue description
Build of `python3Packages.jaxlib` failed on x86_64-linux as of 7cdce123f56f970e3de40f24f6ec4fafe7cd52b4. This is currently breaking `python3Packages.tensorflow-bin`.

```
error: builder for '/nix/store/5zjs2kkz6gqd7gdjr0q8hh80impsrj94-bazel-build-jaxlib-0.4.4.drv' failed with exit code 1;
       last 10 log lines:
       > [6,419 / 7,410] Compiling llvm/lib/CodeGen/MIRFSDiscriminator.cpp; 2s local ... (2 actions running)
       > [6,637 / 7,531] Compiling llvm/lib/Transforms/Scalar/LowerMatrixIntrinsics.cpp; 1s local ... (2 actions running)
       > ERROR: /build/output/external/org_tensorflow/tensorflow/compiler/xla/service/cpu/BUILD:1047:11: Compiling tensorflow/compiler/xla/service/cpu/runtime_single_threaded_matmul.cc failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF ... (remaining 155 arguments skipped)
       > Target //build:build_wheel failed to build
       > Use --verbose_failures to see the command lines of failed build steps.
       > INFO: Elapsed time: 4779.885s, Critical Path: 97.51s
       > INFO: 6883 processes: 3845 internal, 3038 local.
       > FAILED: Build did NOT complete successfully
       > FAILED: Build did NOT complete successfully
       > 
       For full logs, run 'nix log /nix/store/5zjs2kkz6gqd7gdjr0q8hh80impsrj94-bazel-build-jaxlib-0.4.4.drv'.
       note: build failure may have been caused by lack of free disk space
error: 1 dependencies of derivation '/nix/store/2afamz9b43zkb0lwzmkf5h0ivmbxvq8n-python3.10-jaxlib-0.4.4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rncwac4b9f4q0rfzzkzf1l1n8kiqdvw4-python3.10-jax-0.4.5.drv' failed to build
error: 1 dependencies of derivation '/nix/store/p30w5vlw4dylh0c9diq0s7pf05lxki40-python3.10-tensorflow-gpu-2.12.0.drv' failed to build
```

[full build log](https://github.com/samuela/nixpkgs-upkeep/actions/runs/5703177512)

python3Packages.tensorflow-bin maintainers cc: @jyp @abbradar
python3Packages.jaxlib maintainers cc: @ndl
Other cc: n/a

### Steps to reproduce
1. Checkout nixpkgs at commit 7cdce123f56f970e3de40f24f6ec4fafe7cd52b4
2. Run `nix-build -A python3Packages.jaxlib`

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-1041-azure, Ubuntu, 22.04.2 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.16.1`
 - nixpkgs: `/nix/store/kpns6hp2947rcsc8kx4l9zsqgsyxk3ld-source`
```

Contents of `~/.config/nixpkgs/config.nix`:
```
{ allowUnfree = true; cudaSupport = true; cudaCapabilities = ["8.0"]; }
```

## Misc.
This issue was automatically generated by [nixpkgs-upkeep](https://github.com/samuela/nixpkgs-upkeep).
- [CI workflow](https://github.com/samuela/nixpkgs-upkeep/actions/runs/5703177512) that created this issue.
- Internal tags: 1575986320684125267 3459837116179608377

**Comment by dotlambda** [comment] 2023-08-02 17:12
@samuela Please don't assign others unless they actually agreed to work on the issue.

**Comment by samuela** [comment] 2023-08-02 18:40
@dotlambda @ndl is the maintainer of the failing package, hence they are assigned the issue

**Comment by samuela** [comment] 2023-08-02 21:32
This is not meant as a slight against @ndl individually in any way, but as a general rule if folks are not able to uphold their maintainership commitments they should be removed as maintainers.

**Comment by dotlambda** [comment] 2023-08-02 21:46
@samuela Your comment doesn't touch the issue at hand. The same thing could happen with someone who's just away for a short time.

**Comment by dotlambda** [comment] 2023-08-02 21:50
duplicate of https://github.com/NixOS/nixpkgs/issues/241395

**Closed by dotlambda** 2023-08-02 21:50 UTC
Labels: 6.topic: python, 0.kind: build failure
