### ISSUE TITLE
haskell-packages: ghc-syb-utils tests failing

### ISSUE THREAD

**Issue by Chattered** [NixOS/nixpkgs#26689] opened 2017-06-18 09:18 UTC
## Issue description
Regression test for this package fails:

```
running tests
Running 1 test suites...
Test suite regression-tests: RUNNING...

<no location info>: error:
    can't find file: /tmp/nix-build-ghc-syb-utils-0.2.3.1.drv-0/ghc-syb-utils-0.2.3.1/test/test-cases/GithubIssue9.hs
Test suite regression-tests: FAIL
Test suite logged to: dist/test/ghc-syb-utils-0.2.3.1-regression-tests.log
0 of 1 test suites (0 of 1 test cases) passed.
builder for ‘/nix/store/aj4rkxv1iwsna463cwjj8v7pihj5sdyx-ghc-syb-utils-0.2.3.1.drv’ failed with exit code 1
error: build of ‘/nix/store/aj4rkxv1iwsna463cwjj8v7pihj5sdyx-ghc-syb-utils-0.2.3.1.drv’ failed
/run/current-system/sw/bin/nix-shell: failed to build all dependencies
```

### Steps to reproduce
On nixos-unstable:

nix-shell -p haskellPackages.ghc-syb-utils

## Technical details

* System: 17.09pre109180.0d4431cfe9 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.10
* Nixpkgs version: 17.09pre109180.0d4431cfe9
* Sandboxing enabled: No

**Comment by mdorman** [comment] 2017-06-18 11:18
This is a problem with the upstream package (it failed to include that file), and has already been fixed in the 0.2.3.2 release; so once the haskell package set is updated this will go away.

I think @peti is producing an updated package set for 17.03 right now, but perhaps there will be an update to unstable before long.  In the meantime you could override `doCheck`.

**Comment by peti** [comment] 2017-06-18 14:34
We haven't updated yet, because LTS Haskell hasn't updated yet.  :-/

I committed https://github.com/peti/nixpkgs/commit/6f0ebfd3fa0544940162e594f72c8d55cfd61420 to remedy that situation. It will land on `master` in a day or two.

**Closed** 2017-06-19 20:44 UTC
Labels: 6.topic: haskell

**Comment by pbogdan** [comment] 2017-06-27 13:02
0.2.3.2 also fails to build, the test suite builds but fails with an error. It might be because GHCs >= 8.0 aren't officially supported by the project according to their README. The tests pass when building with ghc7103.
Versions of the package prior to 0.2.3.1 didn't contain a test suite.

**Comment by peti** [comment] 2017-06-27 13:43
Is upstream aware of these issues?

**Comment by pbogdan** [comment] 2017-06-27 14:33
[They are](https://github.com/nominolo/ghc-syb/blob/master/Makefile#L10).

**Comment by pbogdan** [comment] 2017-06-27 18:19
Investigated a bit more and relayed the details to upstream in https://github.com/nominolo/ghc-syb/issues/20 As noted on that issue I don't know what a proper fix might consist of but hopefully someone more knowledgeable will, and this will get addressed upstream.

**Comment by peti** [comment] 2017-06-28 16:59
I'll disable the test suite for GHC 8.x. That will make the build succeed.

**Comment by sfultong** [comment] 2017-06-29 22:12
How did this get into 17.03? Doesn't travis run before merges?

**Comment by peti** [comment] 2017-06-30 07:44
@sfultong, we have build instructions for 11,881 Haskell packages and nobody is getting paid to make sure they all compile ...

**Comment by sfultong** [comment] 2017-06-30 13:05
@peti Sorry, I didn't mean to be critical. Would it be feasible to rent a build box for this, or would it simply be impractical? I'd be willing to donate towards this effort.

**Comment by peti** [comment] 2017-06-30 13:14
@sfultong, test-building these packages is no issue. In fact, we do compile `haskellPackages` at http://hydra.nixos.org/jobset/nixpkgs/haskell-updates before merging changes. The issue is not knowing whether a package builds or not, the issue is doing something about those 6,417 packages that we *know* not to compile.
