### ISSUE TITLE
Remove Python 2 from closure for minimal system

### ISSUE THREAD

**Issue by lukegb** [NixOS/nixpkgs#105392] opened 2020-11-29 19:36 UTC
I'd like to remove python2.7 from the system closure for the NixOS minimal installation ISO. This bug is here to track this effort.

Known instances:
* parted
* asciidoc
* wafHook

Fixed instances:
???

**Comment by FRidh** [comment] 2020-11-29 19:51
Duplicate of https://github.com/NixOS/nixpkgs/issues/101964.

**Closed by FRidh** 2020-11-29 19:51 UTC
Labels: 0.kind: bug

**Comment by lukegb** [comment] 2020-11-29 19:55
Hrm, I mostly wanted to have a separate tracking issue for specifically the minimal system ISO, but... I defer to you.
