### ISSUE TITLE
Can't build texlive scheme-full

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#10051] opened 2015-09-25 05:51 UTC
I have that in `system.nix`:

```nix
{
  texlive = texlive.combine {
    inherit (texlive) scheme-full;
  };
}
```

```
download-from-binary-cache.pl: still waiting for ‘http://hydra.nixos.org/rdahcmi7f8792c25idhgd6zwkfd37fr4.narinfo’ after 5 seconds...
these derivations will be built:
  /nix/store/6vbgnp1hawagf2kv2phhxln4jdc59702-texlive-combined-2015.drv
building path(s) ‘/nix/store/rdahcmi7f8792c25idhgd6zwkfd37fr4-texlive-combined-2015’
while setting up the build environment: executing ‘/nix/store/bfd579lvzlgcqcsbbs4n4aji7sxm45nx-bash-4.3-p42/bin/bash’: Argument list too long
builder for ‘/nix/store/6vbgnp1hawagf2kv2phhxln4jdc59702-texlive-combined-2015.drv’ failed with exit code 1
error: build of ‘/nix/store/6vbgnp1hawagf2kv2phhxln4jdc59702-texlive-combined-2015.drv’ failed
```

Is it possible that this `Argument list too long` comes from the too large `scheme-full`?

**Comment by vcunat** [comment] 2015-09-25 08:48
Yes, that's another duplicate of #9757.

**Closed by vcunat** 2015-09-25 08:48 UTC
Labels: bug
