### ISSUE TITLE
yubikey-manager tests fail with "dictionary size changed during iteration"

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#29169] opened 2017-09-10 03:06 UTC
This appears to have started recently: https://hydra.nixos.org/job/nixpkgs/trunk/yubikey-manager.x86_64-linux

I'm disabling the tests for now but I'm guessing something changed in the python infrastructure that would have caused that.

```
  File "nix_run_setup.py", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 63, in <module>
    'Topic :: Utilities'
  File "/private/var/folders/6j/566zczg137j_zbvhjh2zcpr80000gn/T/nix-build-python2.7-yubikey-manager-0.4.0.drv-2/yubikey-manager-0.4.0/ykman/yubicommon/setup/__init__.py", line 124, in setup
    return _setup(**kwargs)
  File "/nix/store/w8zld7z4gq4b36z0szgrh6yv5zi30915-python-2.7.13/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/nix/store/w8zld7z4gq4b36z0szgrh6yv5zi30915-python-2.7.13/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/nix/store/w8zld7z4gq4b36z0szgrh6yv5zi30915-python-2.7.13/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/nix/store/j6mdcbimr51ac4an2isad9f3y1xl0hi5-python2.7-bootstrapped-pip-9.0.1/lib/python2.7/site-packages/setuptools/command/test.py", line 215, in run
    self.run_tests()
  File "/nix/store/j6mdcbimr51ac4an2isad9f3y1xl0hi5-python2.7-bootstrapped-pip-9.0.1/lib/python2.7/site-packages/setuptools/command/test.py", line 238, in run_tests
    **exit_kwarg
  File "/nix/store/w8zld7z4gq4b36z0szgrh6yv5zi30915-python-2.7.13/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/nix/store/w8zld7z4gq4b36z0szgrh6yv5zi30915-python-2.7.13/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/nix/store/w8zld7z4gq4b36z0szgrh6yv5zi30915-python-2.7.13/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/nix/store/w8zld7z4gq4b36z0szgrh6yv5zi30915-python-2.7.13/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/nix/store/w8zld7z4gq4b36z0szgrh6yv5zi30915-python-2.7.13/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/nix/store/j6mdcbimr51ac4an2isad9f3y1xl0hi5-python2.7-bootstrapped-pip-9.0.1/lib/python2.7/site-packages/setuptools/command/test.py", line 43, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/nix/store/w8zld7z4gq4b36z0szgrh6yv5zi30915-python-2.7.13/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/nix/store/w8zld7z4gq4b36z0szgrh6yv5zi30915-python-2.7.13/lib/python2.7/test/regrtest.py", line 184, in <module>
    for module in sys.modules.itervalues():
RuntimeError: dictionary changed size during iteration
```

cc @benley @FRidh 

Edit: the `doCheck = false` is in https://github.com/NixOS/nixpkgs/commit/15502421c72de368f23ee13f1df56ebb1f424935

**Comment by FRidh** [comment] 2017-09-10 06:51
Duplicate of #29103. 

The `yubikey-manager` archive contains tests so the test runner invocation should be fixed instead.

**Closed by FRidh** 2017-09-10 06:51 UTC

**Comment by copumpkin** [comment] 2017-09-10 19:43
@FRidh I don't quite understand how the distutils.cfg thing causes this error. I checked the other ticket but that didn't clarify for me; I'm happy to fix something in `yubikey-manager` if needed but am not sure what to do yet.

**Comment by FRidh** [comment] 2017-09-10 19:58
Our default `checkPhase` runs `python setup.py test`, which asks `setuptools` to find and execute tests. `setuptools` then uses `easy_install` to download and install test dependencies. This can be configured with `distutils.cfg`. Therefore, this is likely a bug somewhere in `setuptools` or `distutils`. An easy solution would likely be to manually specify the `checkPhase`.
