### ISSUE TITLE
logstash isn't available on executable path

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#12966] opened 2016-02-13 02:39 UTC
I installed the `logstash` package and then tried running `logstash`

```
> logstash
logstash: command not found
```

It doesn't seem like it's actually getting installed?

**Comment by jgillich** [comment] 2016-02-13 17:00
I can not reproduce. How did you install it and what does `nixos-version` return?

**Comment by chris-martin** [comment] 2016-02-13 22:33
I installed by adding it to my configuration:

```
environment.systemPackages = with pkgs; [
    # ...
    logstash
];
```

```
> nixos-version
15.09.git.2090c60M (Dingo)
```

**Comment by grahamc** [comment] 2016-02-15 03:41
Looks like this has been resolved by #12981.

**Closed** 2016-02-15 03:44 UTC
Labels: 0.kind: bug
