### ISSUE TITLE
Build failure: backblaze-b2

### ISSUE THREAD

**Issue by linyinfeng** [NixOS/nixpkgs#298601] opened 2024-03-24 11:11 UTC
### Steps To Reproduce

1. `nix build github:nixos/nixpkgs/11d9b9e97bcb5091c8414bbf9e50eb0d5cd745a9#backblaze-b2`

`11d9b9e97bcb5091c8414bbf9e50eb0d5cd745a9` is the commit of current master.

### Build log

https://gist.github.com/linyinfeng/6f6f331ab82566dfd3f177b6438f05da

### Notify maintainers

@hrdinka @tomhoule

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.1, NixOS, 24.05 (Uakari), 24.05.20240319.b06025f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by tomhoule** [comment] 2024-03-24 19:26
Looks like a breaking change from a dependency, potentially. I'm unlikely to have time to debug in the coming days unfortunately.

**Comment by teto** [comment] 2024-03-24 19:31
till then you can do 
```
  doCheck = false;
  doInstallCheck = false;
```

**Comment by alyraffauf** [comment] 2024-03-27 03:42
Just sent a pull request #299394 that fixes this by disabling a few tests. Seems to work well from my testing!

`  disabledTests = [
    # require network
    "test_files_headers"
    "test_integration"

    # fixed by https://github.com/Backblaze/B2_Command_Line_Tool/pull/915
    "TestRmConsoleTool"

    "TestConsoleTool"
    "TestNonUTF8TerminalSupport"
    "TestVersionConsoleTool"
  ];`

**Comment by tomhoule** [comment] 2024-03-27 07:22
Amazing, I can confirm the CLI builds and seems to work on your branch.

**Closed** 2024-03-27 23:46 UTC
Labels: 0.kind: build failure
