### ISSUE TITLE
running kde5 applications without kde as desktop manager

### ISSUE THREAD

**Issue by flosse** [NixOS/nixpkgs#13715] opened 2016-03-06 14:09 UTC
## Basic info

To make sure that we are on the same page:

* Kernel: Linux 4.4.4 / `x86_64 GNU/Linux`
* System: `16.09pre78286.0bf8a1a (Emu)`
* Nix version: `1.11.2`

## Describe your issue here

e.g. running `kile` or `dolphin` causes this error:
`couldn't create slave: "Keine Verbindung zu klauncher: The name org.kde.klauncher5 was not provided by any .service files"`.
Running `okular` works fine.
Moreover the icons don't work (see #11556).

### Steps to reproduce

1. Don't use kde as desktop maneger (`desktopManager.kde5.enable = false;`) and
2. install `kde5.kile` or `kde5.dolphin`
3. run `kile` or `dolphin`

**Comment by ttuegel** [comment] 2016-03-07 18:34
The missing service error is about some D-Bus service. I will check it out, but it's probably related to NixOS not installing `share/` files into the profile by default. The icon issue is related to Awesome not being XDG-compliant.

**Comment by ambrop72** [comment] 2016-04-12 20:27
Hey,
I've found a solution (hack?) for the missing icons problem. While setting `XDG_CURRENT_DESKTOP=kde` globally does fix the icons, it also breaks the Xfce panel. So I changed the existing Qt5 application wrapper to set this. The diff is below. It takes time to rebuild applications but finally KDE5 apps seem to run all right in Xfce.

See some details about the issue is available in an [ubuntu bug report](https://bugs.launchpad.net/ubuntu/+source/dolphin/+bug/1509562). They say it can also be fixed by some "libqt5libqgtk2" package.

```
--- a/pkgs/development/libraries/qt-5/5.5/make-qt-wrapper.sh
+++ b/pkgs/development/libraries/qt-5/5.5/make-qt-wrapper.sh
@@ -15,6 +15,7 @@ wrapQtProgram() {
         --prefix QML2_IMPORT_PATH : "$QML2_IMPORT_PATH" \
         --prefix XDG_CONFIG_DIRS : "$XDG_CONFIG_DIRS" \
         --prefix XDG_DATA_DIRS : "$XDG_DATA_DIRS" \
+        --set XDG_CURRENT_DESKTOP "kde" \
         "$@"
 }
 
@@ -29,6 +30,7 @@ makeQtWrapper() {
         --prefix QML2_IMPORT_PATH : "$QML2_IMPORT_PATH" \
         --prefix XDG_CONFIG_DIRS : "$XDG_CONFIG_DIRS" \
         --prefix XDG_DATA_DIRS : "$XDG_DATA_DIRS" \
+        --set XDG_CURRENT_DESKTOP "kde" \
         "$@"
 }
```

**Comment by flosse** [comment] 2016-04-12 22:34
> I've found a solution (hack?)

great! Are there any downsides?

**Comment by ambrop72** [comment] 2016-04-13 07:30
@flosse, I'm not aware of downsides, but some considerations:
- If you launch some other app from within the kde5 application, it will also run with XDG_CURRENT_DESKTOP=kde
- I've just noticed that KCalc still has an issue with icons (error in console: Icon theme "breeze" not found).

**Comment by ttuegel** [comment] 2016-05-31 16:21
The missing-services issue has been fixed by propagating packages as necessary. The `XDG_CURRENT_DESKTOP` issue can be fixed by installing `qt56.qtbase.gtk`.

**Closed by ttuegel** 2016-05-31 16:21 UTC
Labels: 6.topic: kde

**Comment by mikefaille** [comment] 2017-03-28 15:19
Adding qt56.qtbase.gtk dont work on nixos v17.03

**Comment by ttuegel** [comment] 2017-03-28 17:59
> Adding qt56.qtbase.gtk dont work on nixos v17.03

Our Qt 5.6 build no longer supports GTK integration, but now that it is disabled, it is not necessary for applications to work correctly.

**Comment by mikefaille** [comment] 2017-03-28 18:06
Maybe but I don't get icons in dolphin when my main env. is Gnome.

**Comment by ttuegel** [comment] 2017-03-28 23:19
@cleverca22 You removed the GTK references from Qt 5.6 in dd3e27f2e72ec3da756df0382b2031eae9f900ce which seemed to fix this problem. Can you still reproduce this with NixOS 17.03?

@mikefaille Could you please double-check which Qt version your Dolphin is built with? You can check under `Help > About Dolphin > Libraries`.

**Comment by gnidorah** [comment] 2017-04-12 09:20
Same for i3 wm and KDE apps. For gtk3 apps I just installed gnome3.adwaita-icon-theme and icons showed. But for apps like Gwenview and Spectacle I haven't found a way to fix icons :-(

**Comment by fredlebel** [comment] 2017-07-10 17:33
Still getting this issue under bspwm, here are my versions.

NixOS: 17.03
KDE Frameworks 5.33.0
Qt 5.8.0
The xcb windowing system

I did try enabling plasma5 desktopManager and using the `XDG_CURRENT_DESKTOP` export but didn't work.

**Comment by shadowxnex** [comment] 2017-09-06 21:15
I have had the similar problem.

When I launched dolphin without KDE desktop manager with exported "XDG_CURRENT_DESKTOP=gnome" variable -
 everything was working good, the icons was visible. But when exported variable was equals "XDG_CURRENT_DESKTOP=kde", icons wasn't been visible.

Then I have been tracing system calls via 'strace' utility and have discovered, that dolphin application needs next resource:
`stat("/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/.", 0x7ffff0f3eeb0) = -1 ENOENT (No such file or directory)`

The content of this resource belongs to libqt5libqgtk2 package:

```
pc ~ # dpkg -S libqgtk2.so
	libqt5libqgtk2:amd64: /usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgtk2.so

pc ~ # dpkg -L libqt5libqgtk2
	/.
	/usr
	/usr/share
	/usr/share/doc
	/usr/share/doc/libqt5libqgtk2
	/usr/share/doc/libqt5libqgtk2/LGPL_EXCEPTION.txt
	/usr/share/doc/libqt5libqgtk2/changelog.gz
	/usr/share/doc/libqt5libqgtk2/changelog.Debian.gz
	/usr/share/doc/libqt5libqgtk2/copyright
	/usr/lib
	/usr/lib/x86_64-linux-gnu
	/usr/lib/x86_64-linux-gnu/qt5
	/usr/lib/x86_64-linux-gnu/qt5/plugins
	/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes
	/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgtk2.so
	
pc ~ # dpkg -s libqt5libqgtk2
	Package: libqt5libqgtk2
	Status: install ok installed
	Priority: optional
	Section: libs
	Installed-Size: 409
	Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
	Architecture: amd64
	Multi-Arch: same
	Source: qtbase-opensource-src
	Version: 5.6.1+dfsg-3ubuntu1~xenialoverlay1~4+fix1
	Replaces: libqt5gui5 (<< 5.4.1+dfsg-3~)
	Depends: libqt5gui5 (= 5.6.1+dfsg-3ubuntu1~xenialoverlay1~4+fix1), libc6 (>= 2.14), libglib2.0-0 (>= 2.12.0), libgtk2.0-0 (>= 2.24.0), libpango-1.0-0 (>= 1.14.0), libqt5core5a (>= 5.6.1), libqt5dbus5 (>= 5.0.2), libstdc++6 (>= 5), libx11-6, qtbase-abi-5-6-1
	Breaks: libqt5gui5 (<< 5.4.1+dfsg-3~)
```
But this package is deprecated, and something work was been done. The package libqt5libqgtk2  was been renamed to qt5-gtk-platformtheme since version 5.7.0. You can see this at changelog: http://metadata.ftp-master.debian.org/changelogs/main/q/qtbase-opensource-src/unstable_changelog

```
pc ~ # apt-file list qt5-gtk-platformtheme
qt5-gtk-platformtheme: /usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgtk3.so
qt5-gtk-platformtheme: /usr/share/doc/qt5-gtk-platformtheme/LGPL_EXCEPTION.txt
qt5-gtk-platformtheme: /usr/share/doc/qt5-gtk-platformtheme/changelog.Debian.gz
qt5-gtk-platformtheme: /usr/share/doc/qt5-gtk-platformtheme/copyright
```

One more package that you need to install is plasma-integration with its dependencies. It has neccessary library - KDEPlasmaPlatformTheme.so. 
```
 plugins # dpkg -L plasma-integration
...
/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes
/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/KDEPlasmaPlatformTheme.so
...
```

And now, in newest version of repo (zesty), if you want to see icons in dolphin, without KDE display manager, you must install
* qt5-gtk-platformtheme package - https://packages.ubuntu.com/zesty/qt5-gtk-platformtheme
* plasma-integration - https://packages.ubuntu.com/zesty/plasma-integration

Enjoy yourself!)
