### ISSUE TITLE
Clementine is badly broken

### ISSUE THREAD

**Issue by mrkkrp** [NixOS/nixpkgs#39409] opened 2018-04-24 16:50 UTC
## Issue description

I did `sudo nix-channel --update nixos` and then `sudo nixos-rebuild switch` and `clementine` appears to be broken now. 

### Steps to reproduce

First, here is some info that allows to track derivation that I have on my system:

```
[mark@nixos:~]$ ls -l $(which clementine)
lrwxrwxrwx 1 root root 80 Jan  1  1970 /etc/profiles/per-user/mark/bin/clementine -> /nix/store/r7m7rnsp0dmpx24p5yjz6cbwq5kpf6z5-clementine-free-1.3.1/bin/clementine
```

Then you launch `clementine` and play a FLAC file (I don't have music in other formats). It crashes. Using console I see the following:

```
[mark@nixos:~]$ clementine
23:14:23.875 WARN  unknown                          libpng warning: iCCP: known incorrect sRGB profile 
23:14:23.986 WARN  unknown                          QPainter::begin: Paint device returned engine == 0, type: 2 
23:14:24.645 ERROR unknown                          JSonScanner::yylex - error while reading from io device  
23:14:24.645 ERROR unknown                          json_parser - syntax error found,  forcing abort, Line 1 Column 1  

(clementine:15224): GStreamer-CRITICAL **: 23:14:36.332: gst_object_unref: assertion 'object != NULL' failed
Segmentation fault
[mark@nixos:~]$ echo $?
139
```

I certainly was able to enjoy music before without witnessing this issue.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.33, NixOS, 18.09pre135256.6c064e6b1f3 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.09pre135256.6c064e6b1f3"`
 - channels(mark): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by matthewbauer** [comment] 2018-04-24 18:04
We recently upgraded to GStreamer 1.14. I bet that clementine has not updated yet. Can you open an issue in their repo?

Also helpful to know the last .git-revision that worked for you.

**Comment by mrkkrp** [comment] 2018-04-24 18:17
Seems to be reported here: https://github.com/clementine-player/Clementine/issues/5753. But it’s still not fixed.

**Comment by matthewbauer** [comment] 2018-04-24 18:25
Okay just as a sanity check though: can you verify that "rhythmbox" (which uses the same gstreamer version) can play the file?

**Comment by jtojnar** [comment] 2018-04-24 20:44
I tested the GStreamer playback of FLAC and MP3 files in GNOME Music and Quod Libet and it worked fine. Actually, Rhythmbox did not build with GStreamer 1.14, I fixed it in bfd213aa2d1 and verified it plays as well.

Regarding Clementine, the upstream issue seems to be reported against GStreamer 1.10 so the recent GStreamer update is probably not be relevant.

**Comment by jtojnar** [comment] 2018-04-24 21:00
This would actually be a duplicate of https://github.com/NixOS/nixpkgs/issues/30894

**Closed** 2018-04-24 21:05 UTC

**Comment by jtojnar** [comment] 2018-04-24 21:16
Actually, it was broken in https://github.com/NixOS/nixpkgs/commit/ef5e212d20959d4d883df2ff2a54e5ef4b2512a5#r28723596
