### ISSUE TITLE
nixos-install: This software may cause boot or other problems in the future. Please ask its authors not to store data in the boot track

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#44587] opened 2018-08-07 03:59 UTC
## Issue description

I'm not sure if it's a grub problem or with nixos-install. I installed NixOS today using the latest minimal iso.

I followed [the manual](https://nixos.org/nixos/manual/index.html#sec-installation). 8G swap partition...

BIOS (not UEFI).

![image](https://user-images.githubusercontent.com/24027/43753558-65353636-99d4-11e8-93a7-61ceab779c42.png)

**Comment by xeji** [comment] 2018-08-07 21:09
Closing since this is not a nixpkgs/nixos issue but intended behavior of grub2.

**Closed by xeji** 2018-08-07 21:09 UTC
