### ISSUE TITLE
buildPythonApplication shouldn't add dependencies to PATH and PYTHONPATH

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#26146] opened 2017-05-27 07:07 UTC
## Issue description

For Python applications, Nix adds `propagatedBuildInputs` into `PATH` and `PYTHONPATH`. This makes sense for Python modules, but as far as I understand, I think this shouldn't be done for Python applications, which are run as executables. If I install some Python application `foobar` which uses `jupyter`, I don't want to get `python` and `jupyter` into my `PATH`. I just wanted `foobar` and I don't care that it happens to be written in Python. Also, I might want to install different versions of `python` and `jupyter` into the same environment so there would be conflicts just because `foobar` happens to depend on them too. In my opinion, the right way to install Python applications would be such that only the `bin` directory of the Python application is added to `PATH` but none of its dependencies. The dependencies should be made available only for the Python application with wrapping. Any comments or ideas?

EDIT: And even the Python application itself shouldn't be added to `PYTHONPATH`, only to `PATH`. Again, because it's just an application, it's not supposed to be used as a Python module.

### Steps to reproduce

Let's try with `nbstripout`. Create a clean environment for it:
```
$ nix-shell -p nbstripout -p which --pure
```

Now, `python` and `jupyter` have been added to `PATH`:
```
$ which python
/nix/store/83xv5vjqs8qxzdsqs8dmni23wfkbx43a-python-2.7.13/bin/python
$ which jupyter
/nix/store/78iqhpa3k46ywjc5b9vm2gm5paarpf9p-python2.7-jupyter_core-4.3.0/bin/jupyter
```

Also, the Python dependencies are in `PYTHONPATH`:
```
$ python -c "import nbformat"; echo $?
0
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
```
$ nixos-version
17.09.git.65477dc (Hummingbird)
```

* Nix version: (run `nix-env --version`)
```
$ nix-env --version
nix-env (Nix) 1.11.9
```

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
```
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.09.git.65477dcd34"
```

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
```
$ grep build-use-sandbox /etc/nix/nix.conf
build-use-sandbox = true
```

**Comment by FRidh** [comment] 2017-05-27 09:59
This is mostly a duplicate of https://github.com/NixOS/nixpkgs/issues/24128.

**Comment by FRidh** [comment] 2017-05-28 07:46
I'm closing this because
- this is mostly about `nix-shell` where this is expected (#26151)
- we do have an issue with the wrapper including too much (#24128)

**Closed by FRidh** 2017-05-28 07:46 UTC
Labels: 6.topic: python

**Comment by FRidh** [comment] 2017-05-28 07:48
See also the placeholder with Python-related issues https://github.com/NixOS/nixpkgs/issues/1819.
