### ISSUE TITLE
pitivi: Could not import 'gi'

### ISSUE THREAD

**Issue by apeyroux** [NixOS/nixpkgs#28674] opened 2017-08-29 09:47 UTC
## Issue description

```
nix-shell -p pitivi --run pitivi
Could not import 'gi'. Make sure you have pygobject available.
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

```
nixos-version 
17.03.1759.e56d163c96 (Gorilla)
```

* Nix version: (run `nix-env --version`)

```
nix-env --version
nix-env (Nix) 1.11.13
```

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.03.1759.e56d163c96"
```

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

```
false
```

**Comment by FRidh** [comment] 2017-08-29 11:33
Duplicate of #20449.

**Closed by FRidh** 2017-08-29 11:33 UTC
