### ISSUE TITLE
Mesa drivers problem and GLIBC version not found (wrong version)

### ISSUE THREAD

**Issue by TheMenko** [NixOS/nixpkgs#263940] opened 2023-10-28 11:06 UTC
### Describe the bug
Running some software that uses gpu drivers (mesa) throws and issue ```version `GLIBC_2.38' not found```.
Mesa version is 23.1.9 (current unstable)
ldd --version output is ```ldd (GNU libc) 2.38```
It appears by error messages that nix is using the older glibc, 2.37 (current stable)
There were previous issues like this and only fix they had is to unset ```LD_LIBRARY_PATH``` from env, 
however running ```env | grep LD``` doesn't output anything.

part of the output when running vulkaninfo --summary:
```console
$ vulkaninfo --summary
ERROR: [Loader Message] Code 0 : /nix/store/whypqfa83z4bsn43n4byvmw80n4mg3r8-glibc-2.37-45/lib/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/0lfnrz6nq5myv787cih78knzaqy9z9fc-mesa-23.1.9-drivers/lib/libvulkan_dzn.so)
ERROR: [Loader Message] Code 0 : loader_icd_scan: Failed loading library associated with ICD JSON /nix/store/0lfnrz6nq5myv787cih78knzaqy9z9fc-mesa-23.1.9-drivers/lib/libvulkan_dzn.so. Ignoring this JSON
```
In my configuration.nix file i have the following set:
```console
boot.initrd.kernelModules = [ "amdgpu" ];
environment.variables.AMD_VULKAN_ICD = "RADV";
hardware.opengl = {
    enable = true;
    package = unstable.mesa.drivers;
    driSupport32Bit = true;
    driSupport = true;
};
```

### Steps To Reproduce
1. run vulkaninfo

### Expected behavior
No glibc errors, shows output of vulkaninfo

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/29785008/78707ebf-d539-4b07-b212-060f7b87041d)

### Notify maintainers
@vcunat 

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.7-xanmod1, NixOS, 23.05 (Stoat), 23.05.4527.60b9db998f71`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05, unstable"`
 - channels(menko): `"home-manager-23.05.tar.gz, nixpkgs-23.05"`
 - nixpkgs: `/home/menko/.nix-defexpr/channels/nixpkgs`
```

**Comment by vcunat** [comment] 2023-10-28 18:00
Yes, unfortunately mesa is prone to issues when you mix versions, i.e. running packages from (very) different versions of nixpkgs that the NixOS version.

**Comment by vcunat** [comment] 2023-12-08 17:17
A single nixpkgs commit only has a single glibc (version).

**Comment by SuperSandro2000** [comment] 2023-12-14 01:58
duplicate of #216361

**Closed by SuperSandro2000** 2023-12-14 01:58 UTC
Labels: 0.kind: bug
