### ISSUE TITLE
KiCAD 5 unable to render 3D models

### ISSUE THREAD

**Issue by crawford** [NixOS/nixpkgs#49090] opened 2018-10-25 04:47 UTC
## Issue description

I'm trying to add some 3D models to my footprints, but they do not show up in the 3D viewer. I've tried a custom model as well as the ones installed with KiCAD. I don't see any messages on stdout or stderr other than:

```
/nix/store/7qgqr1qvw84r6lfbw4yv43qi0glhwhd5-python2.7-wxPython-3.0.2.0/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py:16629: UserWarning: wxPython/wxWidgets release number mismatch     
  warnings.warn("wxPython/wxWidgets release number mismatch")
```

### Steps to reproduce

1. `nix-env -i kicad`
2. Launch the footprint editor
3. Open a footprint that has an associated model
4. Observe that the 3D model doesn't render

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.09.932.09195057114 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09.932.09195057114"`
 - channels(alex): `"nixpkgs-18.09pre151052.4477cf04b67"`
 - nixpkgs: `/home/alex/.nix-defexpr/channels/nixpkgs`
```

**Comment by hlandau** [comment] 2018-11-17 19:19
I'm also seeing this. It appears the issue is that 3D model importation is implemented via plugins which are shared libraries. These are found in `/nix/store/...-kicad-5.0.1/lib/kicad/plugins/3d`. However, the code which searches for these plugins (https://github.com/KiCad/kicad-source-mirror/blob/abe1ffabda2df3d13f2224917906f89826a30c8d/3d-viewer/3d_cache/3d_plugin_manager.cpp#L151) makes assumptions which don't hold for NixOS. Thus, the search attempt fails, as shown by strace:
```
[pid 15839] stat("/nix/store/qqa0fy130586yk8fx3zksir1kyz3k7ha-kicad-5.0.1/nix/store/qqa0fy130586yk8fx3zksir1kyz3k7ha-kicad-5.0.1/lib/kicad/plugins/3d", 0x7ffc52d03320) = -1 ENOENT (No such file or directory)
```

A temporary workaround is as follows, which uses the user-local search path:
```
$ mkdir -p ~/.kicad/plugins
$ cd ~/.kicad/plugins
$ ln -s /nix/store/qqa0fy130586yk8fx3zksir1kyz3k7ha-kicad-5.0.1/lib/kicad/plugins/3d
```

cc @berce

**Comment by ThibautMarty** [comment] 2019-03-13 18:38
This had been fixed in 5.1.0: https://github.com/KiCad/kicad-source-mirror/commit/9490fd9d301b5ce3342d8b186c0ec2ea6f5fbda8
We should close this issue after having updated the package and tested.

**Comment by gebner** [comment] 2019-04-30 15:42
This should work now with the new `kicad-with-packages3d` package.

**Comment by Evils-Devils** [comment] 2019-10-15 14:39
you may need to `rm .config/kicad/kicad_common` so it'll update the paths there on the next start (or do so manually)

**Closed** 2020-01-03 19:14 UTC
