### ISSUE TITLE
PulseAudio doesn't start because of malloc assertion failure after 21.11 update

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#165418] opened 2022-03-23 09:14 UTC
### Describe the bug

> Assertion 'size < (1024*1024*96)' failed at pulse/xmalloc.c:72, function pa_xmalloc0(). Aborting.

### Steps To Reproduce
1. Upgrade to latest 21.11
2. Reboot

### Expected behavior

PulseAudio should start.

### Additional context

[Log](https://gist.github.com/l0b0/dd4151dfe186f8d38649b010e78d3346)

### Notify maintainers

@lovek323 

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.106, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.336619.01e87b327aa"`
 - channels(username): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by hqurve** [comment] 2022-03-25 12:22
After looking around, I saw two similar issues

- https://www.odi.ch/weblog/posting.php?posting=721. They used `strace` to determine that pulse was failing while opening a file under `$HOME/.pulse`. They removed that directory and it solved the issue
- https://together.jolla.com/question/144623/solved-no-more-sound-nor-microphone-pulseaudio-problem/. They removed everything under `$HOME/.config/pulse` to solve their issue

The issue is likely one of state being corrupted. Do you have a folder `$HOME/.config/pulse` containing what appears to be some state files? If so, try removing them (or temporarily renaming the directory. Idk what exactly it is that is stored there) and then rebooting

**Comment by dasj19** [comment] 2022-03-25 19:56
@hqurve I have the same issue and I tried your tip and moved `$HOME/.config/pulse` to `$HOME/.config/pulse.old` but did not solve the issue. any other suggestions?

**Comment by hqurve** [comment] 2022-03-25 21:28
Okay, for what its worth. I made a vm with kde and pulseaudio and I experience no such issue. Are you using a desktop environment or are you using a wm only?

I could propose a quick sanity check. If you create a new user, does the issue translate there as well?

**Comment by l0b0** [comment] 2022-03-26 10:59
@hqurve Thank you! The following (or a subset of it; the daemon-reload was probably unnecessary) fixed my system:

```
mv ~/.config/pulse{,.old}
systemctl --user daemon-reload
systemctl --user restart pulseaudio
```

**Comment by dasj19** [comment] 2022-03-26 17:03
I can also confirm that pulseaudio works now after the upgrade from Gnome 41 to Gnome 42.

I propose to close this issue.

**Closed** 2022-03-26 17:36 UTC
Labels: 0.kind: bug, 6.topic: nixos
