### ISSUE TITLE
linux: no longer reproducible

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#227800] opened 2023-04-23 13:23 UTC
Building this package twice does not produce the bit-by-bit identical result each time, making it harder to detect CI breaches. You can read more about this at https://reproducible-builds.org/ .

Fixing bit-by-bit reproducibility also has additional advantages, such as avoiding hard-to-reproduce bugs, making content-addressed storage more effective and reducing rebuilds in such systems.

### Steps To Reproduce

```
nix-build '<nixpkgs>' -A linux --check --keep-failed
```

You can use `diffoscope` to analyze the differences in the output of the two builds.

To view the build log of the build that produced the artifact in the binary cache:

```
nix-store --read-log $(nix-instantiate '<nixpkgs>' -A linux)
```

### Additional context

Seems to be a symbol order problem:

```
--- ./lib/modules/6.1.24/kernel/fs/qnx6/qnx6.ko.xz
+++ ../g8ck7a3j1jlq305qlnpg7rchzi9gsp8h-linux-6.1.24/./lib/modules/6.1.24/kernel/fs/qnx6/qnx6.ko.xz
├── qnx6.ko
│ ├── strings --all --bytes=8 {}
│ │┄ Ordering differences only
│ │ @@ -139,24 +139,24 @@
│ │  qnx6_check_first_superblock
│ │  qnx6_statfs
│ │  qnx6_readahead
│ │  qnx6_read_folio
│ │  qnx6_get_block
│ │  qnx6_remount
│ │  qnx6_show_options
│ │ -qnx6_lookup
│ │  qnx6_long_dir_entry
│ │  de_unknown
│ │  de_long_inode
│ │  de_checksum
│ │  qnx6_long_filename
│ │  lf_fname
│ │  res_page
│ │  qnx6_find_entry
│ │  qnx6_readdir
│ │ +qnx6_lookup
│ │  qnx6_mmi_super_block
│ │  sb_spare0
│ │  sb_spare1
│ │  qnx6_mmi_fill_super
│ │  qnx6_mmi_copy_sb
│ │  qnx6_bmap
│ │  qnx6_get_block
│ ├── readelf --wide --decompress --hex-dump=.BTF {}
│ │ @@ -1,123 +1,123 @@
│ │  
│ │  Hex dump of section '.BTF':
│ │    0x00000000 9feb0100 18000000 00000000 fc060000 ................
│ │ -  0x00000010 fc060000 32040000 e67b1900 00000008 ....2....{......
│ │ -  0x00000020 45000000 ed7b1900 00000008 4a000000 E....{......J...
│ │ -  0x00000030 f47b1900 00000008 4d000000 fb7b1900 .{......M....{..
│ │ -  0x00000040 0e000004 80000000 0c7c1900 de6e0100 .........|...n..
│ │ -  0x00000050 00000000 147c1900 dd6e0100 40000000 .....|...n..@...
│ │ -  0x00000060 1b7c1900 dd6e0100 60000000 227c1900 .|...n..`..."|..
│ │ -  0x00000070 dd6e0100 80000000 2b7c1900 dd6e0100 .n......+|...n..
│ │ -  0x00000080 a0000000 347c1900 dd6e0100 c0000000 ....4|...n......
│ │ -  0x00000090 3d7c1900 dd6e0100 e0000000 467c1900 =|...n......F|..
│ │ -  0x000000a0 dc6e0100 00010000 4e7c1900 dc6e0100 .n......N|...n..
│ │ -  0x000000b0 10010000 5a7c1900 e06e0100 20010000 ....Z|...n.. ...
│ │ -  0x000000c0 677c1900 40000000 20030000 757c1900 g|..@... ...u|..
│ │ -  0x000000d0 40000000 28030000 7f7c1900 bb1e0000 @...(....|......
│ │ -  0x000000e0 30030000 8b7c1900 e16e0100 40030000 0....|...n..@...
│ │ -  0x000000f0 00000000 00000003 00000000 dd6e0100 .............n..
│ │ -  0x00000100 48000000 10000000 00000000 00000003 H...............
│ │ -  0x00000110 00000000 dd6e0100 48000000 06000000 .....n..H.......
│ │ -  0x00000120 947c1900 03000004 20000000 a37c1900 .|...... ....|..
│ │ -  0x00000130 dd6e0100 00000000 ac7c1900 40000000 .n.......|..@...
│ │ -  0x00000140 20000000 b47c1900 91510000 28000000  ....|...Q..(...
│ │ -  0x00000150 bd7c1900 05000004 50000000 d7200000 .|......P.... ..
│ │ -  0x00000160 de6e0100 00000000 89940200 e06e0100 .n...........n..
│ │ -  0x00000170 40000000 37d00a00 40000000 40020000 @...7...@...@...
│ │ -  0x00000180 ba390000 40000000 48020000 2e430100 .9..@...H....C..
│ │ -  0x00000190 cf1e0000 50020000 cc7c1900 13000004 ....P....|......
│ │ -  0x000001a0 88010000 dd7c1900 dd6e0100 00000000 .....|...n......
│ │ -  0x000001b0 e67c1900 dd6e0100 20000000 f27c1900 .|...n.. ....|..
│ │ -  0x000001c0 de6e0100 40000000 fc7c1900 dd6e0100 .n..@....|...n..
│ │ -  0x000001d0 80000000 057d1900 dd6e0100 a0000000 .....}...n......
│ │ -  0x000001e0 c2810200 dd6e0100 c0000000 0e7d1900 .....n.......}..
│ │ -  0x000001f0 dc6e0100 e0000000 1a7d1900 dc6e0100 .n.......}...n..
│ │ -  0x00000200 f0000000 267d1900 cf000000 00010000 ....&}..........
│ │ -  0x00000210 327d1900 dd6e0100 80010000 3f7d1900 2}...n......?}..
│ │ -  0x00000220 dd6e0100 a0010000 4d7d1900 dd6e0100 .n......M}...n..
│ │ -  0x00000230 c0010000 5c7d1900 dd6e0100 e0010000 ....\}...n......
│ │ -  0x00000240 6a7d1900 dd6e0100 00020000 797d1900 j}...n......y}..
│ │ -  0x00000250 dd6e0100 20020000 877d1900 e36e0100 .n.. ....}...n..
│ │ -  0x00000260 40020000 8d7d1900 e36e0100 c0040000 @....}...n......
│ │ -  0x00000270 947d1900 e36e0100 40070000 9d7d1900 .}...n..@....}..
│ │ -  0x00000280 e36e0100 c0090000 a57d1900 08000004 .n.......}......
│ │ -  0x00000290 38000000 b27d1900 283f0000 00000000 8....}..(?......
│ │ -  0x000002a0 eee10200 e66e0100 40000000 b97d1900 .....n..@....}..
│ │ -  0x000002b0 48000000 80000000 c47d1900 48000000 H........}..H...
│ │ -  0x000002c0 a0000000 ce7d1900 35000000 c0000000 .....}..5.......
│ │ -  0x000002d0 da7d1900 48000000 00010000 8a370000 .}..H........7..
│ │ -  0x000002e0 9f020000 40010000 e47d1900 9f020000 ....@....}......
│ │ -  0x000002f0 80010000 00000000 00000002 e46e0100 .............n..
│ │ -  0x00000300 ed7d1900 04000004 b8020000 5a7c1900 .}..........Z|..
│ │ -  0x00000310 e06e0100 00000000 677c1900 40000000 .n......g|..@...
│ │ -  0x00000320 00020000 fd7d1900 4a000000 20020000 .....}..J... ...
│ │ -  0x00000330 fbea0200 9d020000 40020000 00000000 ........@.......
│ │ -  0x00000340 02000006 04000000 107e1900 00000000 .........~......
│ │ -  0x00000350 1b7e1900 01000000 00000000 02000006 .~..............
│ │ -  0x00000360 04000000 267e1900 00000000 bc7a1000 ....&~.......z..
│ │ -  0x00000370 01000000 00000000 00000002 e76e0100 .............n..
│ │ -  0x00000380 00000000 00000002 e56e0100 00000000 .........n......
│ │ -  0x00000390 00000002 df6e0100 00000000 00000002 .....n..........
│ │ -  0x000003a0 e36e0100 00000000 00000002 e26e0100 .n...........n..
│ │ -  0x000003b0 307e1900 0000000c 01000000 3d7e1900 0~..........=~..
│ │ -  0x000003c0 0000000c 8f000000 4a7e1900 0000000c ........J~......
│ │ -  0x000003d0 cf760000 557e1900 0000000c ae1d0000 .v..U~..........
│ │ -  0x000003e0 657e1900 0000000c ac1e0000 00000000 e~..............
│ │ -  0x000003f0 0200000d 9f020000 eee10200 a5020000 ................
│ │ -  0x00000400 974e0000 3c000000 767e1900 0000000c .N..<...v~......
│ │ -  0x00000410 f46e0100 00000000 0200000d 9f020000 .n..............
│ │ -  0x00000420 0e1c0000 a5020000 141c0000 ed6e0100 .............n..
│ │ -  0x00000430 807e1900 0000000c f66e0100 00000000 .~.......n......
│ │ -  0x00000440 0200000d 78000000 692d0000 87010000 ....x...i-......
│ │ -  0x00000450 ab570000 78000000 937e1900 0000000c .W..x....~......
│ │ -  0x00000460 f86e0100 9d7e1900 0000000c 061e0000 .n...~..........
│ │ -  0x00000470 ac7e1900 0000000c c3650100 00000000 .~.......e......
│ │ -  0x00000480 0300000d 283f0000 0e1c0000 a5020000 ....(?..........
│ │ -  0x00000490 65260000 48000000 a46c1100 48000000 e&..H....l..H...
│ │ -  0x000004a0 bc7e1900 0000000c fc6e0100 d87e1900 .~.......n...~..
│ │ -  0x000004b0 0000000c 736d0000 e47e1900 0000000c ....sm...~......
│ │ -  0x000004c0 53b10000 f37e1900 0000000c 55b10000 S....~......U...
│ │ -  0x000004d0 037f1900 0000000c 5fb10000 127f1900 ........_.......
│ │ -  0x000004e0 0000000c 2bf00000 1f7f1900 0000000c ....+...........
│ │ -  0x000004f0 d2570000 317f1900 0000000c 011e0000 .W..1...........
│ │ -  0x00000500 3d7f1900 05000004 10000000 a37c1900 =............|..
│ │ -  0x00000510 dd6e0100 00000000 ac7c1900 40000000 .n.......|..@...
│ │ -  0x00000520 20000000 517f1900 3e050000 28000000  ...Q...>...(...
│ │ -  0x00000530 5c7f1900 dd6e0100 40000000 6a7f1900 \....n..@...j...
│ │ -  0x00000540 dd6e0100 60000000 767f1900 02000004 .n..`...v.......
│ │ -  0x00000550 00020000 897f1900 dc6e0100 00000000 .........n......
│ │ -  0x00000560 917f1900 076f0100 10000000 00000000 .....o..........
│ │ -  0x00000570 00000003 00000000 40000000 48000000 ........@...H...
│ │ -  0x00000580 fe010000 00000000 00000002 056f0100 .............o..
│ │ -  0x00000590 00000000 00000002 066f0100 00000000 .........o......
│ │ -  0x000005a0 0400000d 3c000000 27280000 48000000 ....<...'(..H...
│ │ -  0x000005b0 a7520000 9f020000 ae070000 38000000 .R..........8...
│ │ -  0x000005c0 9a7f1900 b4010000 a37f1900 0000000c ................
│ │ -  0x000005d0 0a6f0100 b37f1900 0000000c ff1d0000 .o..............
│ │ -  0x000005e0 c07f1900 0f000004 80010000 dd7c1900 .............|..
│ │ -  0x000005f0 dd6e0100 00000000 e67c1900 dd6e0100 .n.......|...n..
│ │ -  0x00000600 20000000 f27c1900 de6e0100 40000000  ....|...n..@...
│ │ -  0x00000610 d57f1900 0e6f0100 80000000 df7f1900 .....o..........
│ │ -  0x00000620 0e6f0100 e0000000 327d1900 dd6e0100 .o......2}...n..
│ │ -  0x00000630 40010000 3f7d1900 dd6e0100 60010000 @...?}...n..`...
│ │ -  0x00000640 4d7d1900 dd6e0100 80010000 5c7d1900 M}...n......\}..
│ │ -  0x00000650 dd6e0100 a0010000 6a7d1900 dd6e0100 .n......j}...n..
│ │ -  0x00000660 c0010000 e57f1900 430e0000 e0010000 ........C.......
│ │ -  0x00000670 877d1900 e36e0100 00020000 8d7d1900 .}...n.......}..
│ │ -  0x00000680 e36e0100 80040000 947d1900 e36e0100 .n.......}...n..
│ │ -  0x00000690 00070000 9d7d1900 e36e0100 80090000 .....}...n......
│ │ -  0x000006a0 00000000 00000003 00000000 40000000 ............@...
│ │ -  0x000006b0 48000000 0c000000 00000000 00000002 H...............
│ │ -  0x000006c0 0d6f0100 00000000 0200000d e66e0100 .o...........n..
│ │ -  0x000006d0 0e1c0000 a5020000 a46c1100 48000000 .........l..H...
│ │ -  0x000006e0 ef7f1900 0000000c 106f0100 00000000 .........o......
│ │ -  0x000006f0 0200000d 00000000 03801900 e66e0100 .............n..
│ │ -  0x00000700 eee10200 0f6f0100 07801900 0000000c .....o..........
│ │ -  0x00000710 126f0100 5f5f6673 3136005f 5f667333 .o..__fs16.__fs3
│ │ +  0x00000010 fc060000 32040000 f77b1900 00000008 ....2....{......
│ │ +  0x00000020 42000000 fe7b1900 00000008 45000000 B....{......E...
│ │ +  0x00000030 057c1900 00000008 48000000 0c7c1900 .|......H....|..
│ │ +  0x00000040 0e000004 80000000 1d7c1900 fe6e0100 .........|...n..
│ │ +  0x00000050 00000000 257c1900 fd6e0100 40000000 ....%|...n..@...
│ │ +  0x00000060 2c7c1900 fd6e0100 60000000 337c1900 ,|...n..`...3|..
│ │ +  0x00000070 fd6e0100 80000000 3c7c1900 fd6e0100 .n......<|...n..
│ │ +  0x00000080 a0000000 457c1900 fd6e0100 c0000000 ....E|...n......
│ │ +  0x00000090 4e7c1900 fd6e0100 e0000000 577c1900 N|...n......W|..
│ │ +  0x000000a0 fc6e0100 00010000 5f7c1900 fc6e0100 .n......_|...n..
│ │ +  0x000000b0 10010000 6b7c1900 006f0100 20010000 ....k|...o.. ...
│ │ +  0x000000c0 787c1900 3e000000 20030000 867c1900 x|..>... ....|..
│ │ +  0x000000d0 3e000000 28030000 907c1900 d1080000 >...(....|......
│ │ +  0x000000e0 30030000 9c7c1900 016f0100 40030000 0....|...o..@...
│ │ +  0x000000f0 00000000 00000003 00000000 fd6e0100 .............n..
│ │ +  0x00000100 44000000 10000000 00000000 00000003 D...............
│ │ +  0x00000110 00000000 fd6e0100 44000000 06000000 .....n..D.......
│ │ +  0x00000120 a57c1900 03000004 20000000 b47c1900 .|...... ....|..
│ │ +  0x00000130 fd6e0100 00000000 bd7c1900 3e000000 .n.......|..>...
│ │ +  0x00000140 20000000 c57c1900 43400000 28000000  ....|..C@..(...
│ │ +  0x00000150 ce7c1900 05000004 50000000 071e0000 .|......P.......
│ │ +  0x00000160 fe6e0100 00000000 78f80000 006f0100 .n......x....o..
│ │ +  0x00000170 40000000 25110600 3e000000 40020000 @...%...>...@...
│ │ +  0x00000180 97510000 3e000000 48020000 34400100 .Q..>...H...4@..
│ │ +  0x00000190 c4190000 50020000 dd7c1900 13000004 ....P....|......
│ │ +  0x000001a0 88010000 ee7c1900 fd6e0100 00000000 .....|...n......
│ │ +  0x000001b0 f77c1900 fd6e0100 20000000 037d1900 .|...n.. ....}..
│ │ +  0x000001c0 fe6e0100 40000000 0d7d1900 fd6e0100 .n..@....}...n..
│ │ +  0x000001d0 80000000 167d1900 fd6e0100 a0000000 .....}...n......
│ │ +  0x000001e0 8f390100 fd6e0100 c0000000 1f7d1900 .9...n.......}..
│ │ +  0x000001f0 fc6e0100 e0000000 2b7d1900 fc6e0100 .n......+}...n..
│ │ +  0x00000200 f0000000 377d1900 c2010000 00010000 ....7}..........
│ │ +  0x00000210 437d1900 fd6e0100 80010000 507d1900 C}...n......P}..
│ │ +  0x00000220 fd6e0100 a0010000 5e7d1900 fd6e0100 .n......^}...n..
│ │ +  0x00000230 c0010000 6d7d1900 fd6e0100 e0010000 ....m}...n......
│ │ +  0x00000240 7b7d1900 fd6e0100 00020000 8a7d1900 {}...n.......}..
│ │ +  0x00000250 fd6e0100 20020000 987d1900 036f0100 .n.. ....}...o..
│ │ +  0x00000260 40020000 9e7d1900 036f0100 c0040000 @....}...o......
│ │ +  0x00000270 a57d1900 036f0100 40070000 ae7d1900 .}...o..@....}..
│ │ +  0x00000280 036f0100 c0090000 b67d1900 08000004 .o.......}......
│ │ +  0x00000290 38000000 c37d1900 c6170000 00000000 8....}..........
│ │ +  0x000002a0 07440400 066f0100 40000000 ca7d1900 .D...o..@....}..
│ │ +  0x000002b0 44000000 80000000 d57d1900 44000000 D........}..D...
│ │ +  0x000002c0 a0000000 df7d1900 35000000 c0000000 .....}..5.......
│ │ +  0x000002d0 eb7d1900 44000000 00010000 4b4d0000 .}..D.......KM..
│ │ +  0x000002e0 16050000 40010000 f57d1900 16050000 ....@....}......
│ │ +  0x000002f0 80010000 00000000 00000002 046f0100 .............o..
│ │ +  0x00000300 fe7d1900 04000004 b8020000 6b7c1900 .}..........k|..
│ │ +  0x00000310 006f0100 00000000 787c1900 3e000000 .o......x|..>...
│ │ +  0x00000320 00020000 0e7e1900 45000000 20020000 .....~..E... ...
│ │ +  0x00000330 0b1b0500 14050000 40020000 00000000 ........@.......
│ │ +  0x00000340 02000006 04000000 217e1900 00000000 ........!~......
│ │ +  0x00000350 2c7e1900 01000000 00000000 02000006 ,~..............
│ │ +  0x00000360 04000000 377e1900 00000000 53f80700 ....7~......S...
│ │ +  0x00000370 01000000 00000000 00000002 076f0100 .............o..
│ │ +  0x00000380 00000000 00000002 056f0100 00000000 .........o......
│ │ +  0x00000390 00000002 ff6e0100 00000000 00000002 .....n..........
│ │ +  0x000003a0 036f0100 00000000 00000002 026f0100 .o...........o..
│ │ +  0x000003b0 417e1900 0000000c 01000000 4e7e1900 A~..........N~..
│ │ +  0x000003c0 0000000c 65000000 5b7e1900 0000000c ....e...[~......
│ │ +  0x000003d0 b55b0000 667e1900 0000000c 93260000 .[..f~.......&..
│ │ +  0x000003e0 767e1900 0000000c bf5b0000 00000000 v~.......[......
│ │ +  0x000003f0 0200000d 16050000 07440400 1c050000 .........D......
│ │ +  0x00000400 2f700000 3c000000 877e1900 0000000c /p..<....~......
│ │ +  0x00000410 146f0100 00000000 0200000d 16050000 .o..............
│ │ +  0x00000420 453f0000 1c050000 4b3f0000 0d6f0100 E?......K?...o..
│ │ +  0x00000430 917e1900 0000000c 166f0100 00000000 .~.......o......
│ │ +  0x00000440 0200000d 6c010000 a6650000 67030000 ....l....e..g...
│ │ +  0x00000450 5b920000 6c010000 a47e1900 0000000c [...l....~......
│ │ +  0x00000460 186f0100 ae7e1900 0000000c f9390000 .o...~.......9..
│ │ +  0x00000470 bd7e1900 0000000c 5a4b0100 00000000 .~......ZK......
│ │ +  0x00000480 0300000d c6170000 453f0000 1c050000 ........E?......
│ │ +  0x00000490 b3500000 44000000 21f90700 44000000 .P..D...!...D...
│ │ +  0x000004a0 cd7e1900 0000000c 1c6f0100 e97e1900 .~.......o...~..
│ │ +  0x000004b0 0000000c ad350000 f57e1900 0000000c .....5...~......
│ │ +  0x000004c0 5e9c0000 047f1900 0000000c 8a350000 ^............5..
│ │ +  0x000004d0 147f1900 0000000c d01d0100 237f1900 ............#...
│ │ +  0x000004e0 0000000c bb5b0000 307f1900 0000000c .....[..0.......
│ │ +  0x000004f0 0d3a0000 427f1900 05000004 10000000 .:..B...........
│ │ +  0x00000500 b47c1900 fd6e0100 00000000 bd7c1900 .|...n.......|..
│ │ +  0x00000510 3e000000 20000000 567f1900 31070000 >... ...V...1...
│ │ +  0x00000520 28000000 617f1900 fd6e0100 40000000 (...a....n..@...
│ │ +  0x00000530 6f7f1900 fd6e0100 60000000 7b7f1900 o....n..`...{...
│ │ +  0x00000540 02000004 00020000 8e7f1900 fc6e0100 .............n..
│ │ +  0x00000550 00000000 967f1900 266f0100 10000000 ........&o......
│ │ +  0x00000560 00000000 00000003 00000000 3e000000 ............>...
│ │ +  0x00000570 44000000 fe010000 00000000 00000002 D...............
│ │ +  0x00000580 246f0100 00000000 00000002 256f0100 $o..........%o..
│ │ +  0x00000590 00000000 0400000d 3c000000 36540000 ........<...6T..
│ │ +  0x000005a0 44000000 a76e0000 16050000 9f0f0000 D....n..........
│ │ +  0x000005b0 39000000 9f7f1900 90030000 a87f1900 9...............
│ │ +  0x000005c0 0000000c 296f0100 b87f1900 0000000c ....)o..........
│ │ +  0x000005d0 50350000 c57f1900 0000000c 5a350000 P5..........Z5..
│ │ +  0x000005e0 d17f1900 0f000004 80010000 ee7c1900 .............|..
│ │ +  0x000005f0 fd6e0100 00000000 f77c1900 fd6e0100 .n.......|...n..
│ │ +  0x00000600 20000000 037d1900 fe6e0100 40000000  ....}...n..@...
│ │ +  0x00000610 e67f1900 2e6f0100 80000000 f07f1900 .....o..........
│ │ +  0x00000620 2e6f0100 e0000000 437d1900 fd6e0100 .o......C}...n..
│ │ +  0x00000630 40010000 507d1900 fd6e0100 60010000 @...P}...n..`...
│ │ +  0x00000640 5e7d1900 fd6e0100 80010000 6d7d1900 ^}...n......m}..
│ │ +  0x00000650 fd6e0100 a0010000 7b7d1900 fd6e0100 .n......{}...n..
│ │ +  0x00000660 c0010000 f67f1900 e2080000 e0010000 ................
│ │ +  0x00000670 987d1900 036f0100 00020000 9e7d1900 .}...o.......}..
│ │ +  0x00000680 036f0100 80040000 a57d1900 036f0100 .o.......}...o..
│ │ +  0x00000690 00070000 ae7d1900 036f0100 80090000 .....}...o......
│ │ +  0x000006a0 00000000 00000003 00000000 3e000000 ............>...
│ │ +  0x000006b0 44000000 0c000000 00000000 00000002 D...............
│ │ +  0x000006c0 2d6f0100 00000000 0200000d 066f0100 -o...........o..
│ │ +  0x000006d0 453f0000 1c050000 21f90700 44000000 E?......!...D...
│ │ +  0x000006e0 00801900 0000000c 306f0100 00000000 ........0o......
│ │ +  0x000006f0 0200000d 00000000 14801900 066f0100 .............o..
│ │ +  0x00000700 07440400 2f6f0100 18801900 0000000c .D../o..........
│ │ +  0x00000710 326f0100 5f5f6673 3136005f 5f667333 2o..__fs16.__fs3
│ │    0x00000720 32005f5f 66733634 00716e78 365f696e 2.__fs64.qnx6_in
│ │    0x00000730 6f64655f 656e7472 79006469 5f73697a ode_entry.di_siz
│ │    0x00000740 65006469 5f756964 0064695f 67696400 e.di_uid.di_gid.
│ │    0x00000750 64695f66 74696d65 0064695f 6d74696d di_ftime.di_mtim
│ │    0x00000760 65006469 5f617469 6d650064 695f6374 e.di_atime.di_ct
│ │    0x00000770 696d6500 64695f6d 6f646500 64695f65 ime.di_mode.di_e
│ │    0x00000780 78745f6d 6f646500 64695f62 6c6f636b xt_mode.di_block
│ │ @@ -162,23 +162,23 @@
│ │    0x000009f0 6865636b 5f666972 73745f73 75706572 heck_first_super
│ │    0x00000a00 626c6f63 6b00716e 78365f73 74617466 block.qnx6_statf
│ │    0x00000a10 7300716e 78365f72 65616461 68656164 s.qnx6_readahead
│ │    0x00000a20 00716e78 365f7265 61645f66 6f6c696f .qnx6_read_folio
│ │    0x00000a30 00716e78 365f6765 745f626c 6f636b00 .qnx6_get_block.
│ │    0x00000a40 716e7836 5f72656d 6f756e74 00716e78 qnx6_remount.qnx
│ │    0x00000a50 365f7368 6f775f6f 7074696f 6e730071 6_show_options.q
│ │ -  0x00000a60 6e78365f 6c6f6f6b 75700071 6e78365f nx6_lookup.qnx6_
│ │ -  0x00000a70 6c6f6e67 5f646972 5f656e74 72790064 long_dir_entry.d
│ │ -  0x00000a80 655f756e 6b6e6f77 6e006465 5f6c6f6e e_unknown.de_lon
│ │ -  0x00000a90 675f696e 6f646500 64655f63 6865636b g_inode.de_check
│ │ -  0x00000aa0 73756d00 716e7836 5f6c6f6e 675f6669 sum.qnx6_long_fi
│ │ -  0x00000ab0 6c656e61 6d65006c 665f7369 7a65006c lename.lf_size.l
│ │ -  0x00000ac0 665f666e 616d6500 7265735f 70616765 f_fname.res_page
│ │ -  0x00000ad0 00716e78 365f6669 6e645f65 6e747279 .qnx6_find_entry
│ │ -  0x00000ae0 00716e78 365f7265 61646469 7200716e .qnx6_readdir.qn
│ │ +  0x00000a60 6e78365f 6c6f6e67 5f646972 5f656e74 nx6_long_dir_ent
│ │ +  0x00000a70 72790064 655f756e 6b6e6f77 6e006465 ry.de_unknown.de
│ │ +  0x00000a80 5f6c6f6e 675f696e 6f646500 64655f63 _long_inode.de_c
│ │ +  0x00000a90 6865636b 73756d00 716e7836 5f6c6f6e hecksum.qnx6_lon
│ │ +  0x00000aa0 675f6669 6c656e61 6d65006c 665f7369 g_filename.lf_si
│ │ +  0x00000ab0 7a65006c 665f666e 616d6500 7265735f ze.lf_fname.res_
│ │ +  0x00000ac0 70616765 00716e78 365f6669 6e645f65 page.qnx6_find_e
│ │ +  0x00000ad0 6e747279 00716e78 365f7265 61646469 ntry.qnx6_readdi
│ │ +  0x00000ae0 7200716e 78365f6c 6f6f6b75 7000716e r.qnx6_lookup.qn
│ │    0x00000af0 78365f6d 6d695f73 75706572 5f626c6f x6_mmi_super_blo
│ │    0x00000b00 636b0073 625f7370 61726530 0073625f ck.sb_spare0.sb_
│ │    0x00000b10 69640073 625f7370 61726531 00716e78 id.sb_spare1.qnx
│ │    0x00000b20 365f6d6d 695f6669 6c6c5f73 75706572 6_mmi_fill_super
│ │    0x00000b30 00717362 00716e78 365f6d6d 695f636f .qsb.qnx6_mmi_co
│ │    0x00000b40 70795f73 6200                       py_sb.
```

possibly the same cause as #223584

**Comment by delroth** [comment] 2023-05-17 14:19
Reopening -- tested on staging-next, the BTF issue is fixed and the diff is significantly cleaner than before, but there's still a bzImage diff due to two 20 bytes fields in .rodata (which I presume to be SHA1 build-ids).

![image](https://github.com/NixOS/nixpkgs/assets/202798/02944047-2e97-4ad3-9985-9394fd3bcf24)

**Comment by delroth** [comment] 2023-05-17 14:44
Confirmed: these are two build-ids, for the 64 bit and 32 bit VDSO respectively (which are embedded as ELF files in the vmlinux rodata section).

```
[nix-shell:~/unrepro/1]$ dd if=vmlinux.rodata of=vdso.elf count=8192 skip=$((0x2fe000)) bs=1
8192+0 records in
8192+0 records out
8192 bytes (8.2 kB, 8.0 KiB) copied, 0.025571 s, 320 kB/s

[nix-shell:~/unrepro/1]$ dd if=vmlinux.2.rodata of=vdso.2.elf count=8192 skip=$((0x2fe000)) bs=1
8192+0 records in
8192+0 records out
8192 bytes (8.2 kB, 8.0 KiB) copied, 0.0262738 s, 312 kB/s

[nix-shell:~/unrepro/1]$ readelf -a vdso.elf | grep 'Build ID'
    Build ID: aac00e8b4db0964161b2570df3e83149697378d1

[nix-shell:~/unrepro/1]$ readelf -a vdso.2.elf | grep 'Build ID'
    Build ID: f5fb64ccd9c2f152048dac3561d936824771ea34
```

**Comment by delroth** [comment] 2023-05-17 15:35
This might be because Nix has silently decided to not run my kernel build in its sandbox (https://github.com/NixOS/nix/issues/8165) -- would be useful to check if someone can repro in a build that they can guarantee is sandboxed. Otherwise I'll check tomorrow or on friday.

**Comment by delroth** [comment] 2023-05-17 22:26
As it turns out this wasn't my sandboxing being broken, see https://github.com/NixOS/nixpkgs/pull/232508 for the root cause.

**Comment by delroth** [comment] 2023-05-20 03:25
Confirmed fixed on staging.

**Closed by delroth** 2023-05-20 03:25 UTC
Labels: 0.kind: enhancement, 6.topic: kernel, 6.topic: reproducible builds, 0.kind: regression
