### ISSUE TITLE
Package request: ns-usbloader

### ISSUE THREAD

**Issue by Soundtoxin** [NixOS/nixpkgs#85652] opened 2020-04-21 03:52 UTC
**Project description**
Software for interacting with a Nintendo Switch running custom firmware. Can install homebrew software over USB or the network, as well as send boot payloads.

**Metadata**

* homepage URL: https://developersu.blogspot.com/search/label/NS-USBloader
* source URL: https://github.com/developersu/ns-usbloader
* license: GPL-3.0+
* platforms: unix, linux, darwin,

**Comment by Soundtoxin** [comment] 2020-10-18 05:09
Still valid! Not yet packaged.

**Comment by Soundtoxin** [comment] 2021-04-19 16:14
.

**Comment by Niols** [comment] 2022-04-10 16:04
I mean it makes sense, considering it's not being packaged, to close this issue at some point. I will package this eventually, when I have the time.

**Comment by Spaxly** [comment] 2023-06-28 23:43
.

**Comment by Soundtoxin** [comment] 2023-06-28 23:54
> I mean it makes sense, considering it's not being packaged, to close this issue at some point. I will package this eventually, when I have the time.

I would only close it if it gets packaged or if for some reason it can't/won't ever be packaged. The culture of closing issues without solving them just to keep the numbers down is not one I am a fan of (but close any duplicates, of course). Not all issues are equal priority or difficulty, some may stay open for years. That's fine.

**Comment by soupglasses** [comment] 2023-07-28 19:28
Got a concept up and running. It took a while, mainly due to the jar file it generates is not reproducible out of the box. It is in the PR. If you want something today while the PR gets worked out, you can run `nix run github:soupglasses/dotfiles?dir=home-manager#ns-usbloader`. However, i make no promises for keeping this around after the PR.

**Closed** 2023-07-31 09:56 UTC
Labels: 0.kind: packaging request
