### ISSUE TITLE
can't load .so/.DLL for: /nix/store ....  GLIBC_PRIVATE not defined in file libc.so.6 with link time reference)

### ISSUE THREAD

**Issue by tanzeelrana** [NixOS/nixpkgs#31846] opened 2017-11-20 05:00 UTC
## Issue description
Preprocessing library aeson-1.1.2.0 fails with error

<command line>: can't load .so/.DLL for: /nix/store/zpg78y1mf0di6127q6r51kgx2q8cxsvv-glibc-2.25-49/lib/libdl.so (/nix/store/zpg78y1mf0di6127q6r51kgx2q8cxsvv-glibc-2.25-49/lib/libdl.so: symbol _dl_catch_error, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference)

### Steps to reproduce
followed these steps :
https://cardanodocs.com/for-contributors/building-from-source/

**Comment by domenkozar** [comment] 2017-11-20 15:29
Can you output `echo $LD_PRELOAD`

**Comment by domenkozar** [comment] 2017-11-20 15:30
I think it's a duplicate of https://github.com/NixOS/nixpkgs/issues/29064

**Comment by vcunat** [comment] 2017-11-20 20:02
`haskellPackages.aeson` (1.1.2.0) builds on master, `x86_64-linux`.

**Comment by tanzeelrana** [comment] 2017-11-21 06:11
No output for echo `$LD_PRELOAD`

**Comment by domenkozar** [comment] 2017-11-21 10:52
@tanzeelrana could you do:

```
git clone https://github.com/NixOS/nixpkgs.git
cd nixpkgs
nix-build -A haskellPackages..aeson --check
```

and see if it builds?

**Comment by vcunat** [comment] 2017-11-21 14:33
Could it be a build without sandboxing (perhaps some dependency), picking up some impurity?

**Comment by vcunat** [comment] 2017-11-21 14:34
@domenkozar: my understanding is that it's the nix build of `haskellPackages.aeson` what fails.

**Comment by domenkozar** [comment] 2017-11-21 15:13
This is output from `stack build --nix`, which uses `nix-shell --pure`

**Comment by tanzeelrana** [comment] 2017-11-21 23:30
tanzeel@tanzeel-HP-Compaq-dx7500-SFF:~$ cd nixpkgs/
tanzeel@tanzeel-HP-Compaq-dx7500-SFF:~/nixpkgs$ nix-build -A haskellPackages..aeson --check

error: empty attribute name in selection path ‘haskellPackages..aeson’

**Comment by tanzeelrana** [comment] 2017-11-21 23:53
hey @domenkozar  you mean 

nix-build -A haskellPackages.aeson --check

not

nix-build -A haskellPackages..aeson --check

I tried these steps and I get the following warning: 
`   Data/Aeson/Types/FromJSON.hs:470:3: warning: [-Winline-rule-shadowing]
    Rule "FromJSONKeyCoerce: fmap id" may never fire
      because ‘id’ might inline first
    Probable fix: add an INLINE[n] or NOINLINE[n] pragma for ‘id’ 

warning: rewriting hashes in ‘/nix/store/dy6fgcgjabf9akc7wkb9pna4nrzjd8ci-aeson-1.1.2.0-doc’; cross fingers
warning: rewriting hashes in ‘/nix/store/z07gd9fvzr65vp65yjqypldp3zvxar32-aeson-1.1.2.0’; cross fingers
error: derivation ‘/nix/store/xfzsgd0g6bzak43mndw1z8953bgny7sy-aeson-1.1.2.0.drv’ may not be deterministic: output ‘/nix/store/z07gd9fvzr65vp65yjqypldp3zvxar32-aeson-1.1.2.0’ differs`

**Comment by tanzeelrana** [comment] 2017-11-21 23:58
https://github.com/NixOS/nix/issues/1695

**Comment by tanzeelrana** [comment] 2017-11-22 03:33
*** Downloading ‘https://cache.nixos.org/nar/0m03h59ka5hdf012svzz8p4jb77qcilfzcgkn0hidlr8k4ppr4aj.nar.xz’ to ‘/nix/store/r556bjkg62fh4mxpfqpa9rpjcvbylg6z-xz-5.2.3-bin’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 41864  100 41864    0     0  41864      0  0:00:01 --:--:--  0:00:01  196k

fetching path ‘/nix/store/izkijl7w7qkjdfr09qk43v1n3bnbdnvm-stdenv’...

*** Downloading ‘https://cache.nixos.org/nar/1x9zq6j2dcik9qdm9afbic1k78pli3jcgjri0hxq8w3dgk2kqk61.nar.xz’ to ‘/nix/store/izkijl7w7qkjdfr09qk43v1n3bnbdnvm-stdenv’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9220  100  9220    0     0   9220      0  0:00:01 --:--:--  0:00:01 57267

fetching path ‘/nix/store/vj04r9vz6ml68cj67n68p9yf15js65qv-stdenv’...

*** Downloading ‘https://cache.nixos.org/nar/146s1fcj5if8iapdmdg27s9z34r9zb5zj150rml5qy95ysh9pvjm.nar.xz’ to ‘/nix/store/vj04r9vz6ml68cj67n68p9yf15js65qv-stdenv’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9188  100  9188    0     0   9188      0  0:00:01 --:--:--  0:00:01 41954

building path(s) ‘/nix/store/nk1s8b0sbzi79cpg3yimdn2svlvi31f7-remove-references-to’
checking path(s) ‘/nix/store/dy6fgcgjabf9akc7wkb9pna4nrzjd8ci-aeson-1.1.2.0-doc’, ‘/nix/store/z07gd9fvzr65vp65yjqypldp3zvxar32-aeson-1.1.2.0’
setupCompilerEnvironmentPhase
Build with /nix/store/d7pa43zz28cxmmbnk8aw1fsdlwhizcmm-ghc-8.0.2.
unpacking sources
unpacking source archive /nix/store/srh2sihjrrsnknd0ykp7m632i1inmk49-aeson-1.1.2.0.tar.gz
source root is aeson-1.1.2.0
setting SOURCE_DATE_EPOCH to timestamp 1492708024 of file aeson-1.1.2.0/tests/UnitTests/NullaryConstructors.hs
patching sources
Replace Cabal file with edited version from http://hackage.haskell.org/package/aeson-1.1.2.0/revision/1.cabal.
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-aeson-1.1.2.0.drv-0/package.conf.d -j4 -threaded
[1 of 1] Compiling Main             ( Setup.lhs, /tmp/nix-build-aeson-1.1.2.0.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --docdir=/nix/store/1qdb93rd0rc6b4hz4gzzhcxdfammn8k7-aeson-1.1.2.0-doc/share/doc --with-gcc=gcc --package-db=/tmp/nix-build-aeson-1.1.2.0.drv-0/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0/lib/ghc-8.0.2/aeson-1.1.2.0 --ghc-option=-j4 --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-library-vanilla --enable-executable-dynamic --disable-tests --ghc-option=-split-sections
Configuring aeson-1.1.2.0...
Flags chosen: cffi=True, bytestring-builder=False, fast=False, developer=False
Dependency attoparsec >=0.13.0.1: using attoparsec-0.13.1.0
Dependency base >=4.5 && <5: using base-4.9.1.0
Dependency base-compat >=0.9.1 && <0.10: using base-compat-0.9.3
Dependency bytestring >=0.10.4: using bytestring-0.10.8.1
Dependency containers >=0.2.4.1: using containers-0.5.7.1
Dependency deepseq >=1.3: using deepseq-1.4.2.0
Dependency dlist >=0.2: using dlist-0.8.0.3
Dependency ghc-prim >=0.2: using ghc-prim-0.5.0.0
Dependency hashable >=1.1.2.0: using hashable-1.2.6.1
Dependency scientific >=0.3.4.7 && <0.4: using scientific-0.3.5.2
Dependency tagged >=0.8.3 && <0.9: using tagged-0.8.5
Dependency template-haskell >=2.7: using template-haskell-2.11.1.0
Dependency text >=1.1.1.0: using text-1.2.2.2
Dependency time >=1.1.1.4: using time-1.6.0.1
Dependency time-locale-compat >=0.1.1 && <0.2: using
time-locale-compat-0.1.1.3
Dependency unordered-containers >=0.2.5.0: using unordered-containers-0.2.8.0
Dependency uuid-types >=1.0.3 && <1.1: using uuid-types-1.0.3
Dependency vector >=0.8: using vector-0.12.0.1
Using Cabal-1.24.2.0 compiled by ghc-8.0
Using compiler: ghc-8.0.2
Using install prefix:
/nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0
Binaries installed in:
/nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0/bin
Libraries installed in:
/nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0/lib/ghc-8.0.2/aeson-1.1.2.0
Dynamic libraries installed in:
/nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0/lib/ghc-8.0.2/x86_64-linux-ghc-8.0.2
Private binaries installed in:
/nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0/libexec
Data files installed in:
/nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0/share/x86_64-linux-ghc-8.0.2/aeson-1.1.2.0
Documentation installed in:
/nix/store/1qdb93rd0rc6b4hz4gzzhcxdfammn8k7-aeson-1.1.2.0-doc/share/doc
Configuration files installed in:
/nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0/etc
No alex found
Using ar found on system at:
/nix/store/yha4q7zgm6y0ci0b57a8hbmzwyvv1w44-binutils-2.28.1/bin/ar
No c2hs found
No cpphs found
Using gcc version 6.4.0 given by user at:
/nix/store/yjh21h38fmw3i4h2b5r557p4ggbvrd0v-gcc-wrapper-6.4.0/bin/gcc
Using ghc version 8.0.2 found on system at:
/nix/store/d7pa43zz28cxmmbnk8aw1fsdlwhizcmm-ghc-8.0.2/bin/ghc
Using ghc-pkg version 8.0.2 found on system at:
/nix/store/d7pa43zz28cxmmbnk8aw1fsdlwhizcmm-ghc-8.0.2/bin/ghc-pkg
No ghcjs found
No ghcjs-pkg found
No greencard found
Using haddock version 2.17.3 found on system at:
/nix/store/d7pa43zz28cxmmbnk8aw1fsdlwhizcmm-ghc-8.0.2/bin/haddock
No happy found
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.67 found on system at:
/nix/store/d7pa43zz28cxmmbnk8aw1fsdlwhizcmm-ghc-8.0.2/bin/hpc
Using hsc2hs version 0.68.1 found on system at:
/nix/store/d7pa43zz28cxmmbnk8aw1fsdlwhizcmm-ghc-8.0.2/bin/hsc2hs
Using hscolour version 1.24 found on system at:
/nix/store/bx21s5qjz1l75kb40pjg8kkppj7gk3g1-hscolour-1.24.1/bin/HsColour
No jhc found
Using ld found on system at:
/nix/store/yjh21h38fmw3i4h2b5r557p4ggbvrd0v-gcc-wrapper-6.4.0/bin/ld
No lhc found
No lhc-pkg found
No pkg-config found
Using strip version 2.28 found on system at:
/nix/store/yha4q7zgm6y0ci0b57a8hbmzwyvv1w44-binutils-2.28.1/bin/strip
Using tar found on system at:
/nix/store/7lx6bha6l22vi5h9c31nri1p7rqs7v1d-gnutar-1.29/bin/tar
No uhc found
building
Building aeson-1.1.2.0...
Preprocessing library aeson-1.1.2.0...
[ 1 of 21] Compiling Data.Aeson.Types.Internal ( Data/Aeson/Types/Internal.hs, dist/build/Data/Aeson/Types/Internal.o )
[ 2 of 21] Compiling Data.Aeson.Types.Generic ( Data/Aeson/Types/Generic.hs, dist/build/Data/Aeson/Types/Generic.o )
[ 3 of 21] Compiling Data.Aeson.Parser.UnescapeFFI ( ffi/Data/Aeson/Parser/UnescapeFFI.hs, dist/build/Data/Aeson/Parser/UnescapeFFI.o )
[ 4 of 21] Compiling Data.Aeson.Parser.Unescape ( Data/Aeson/Parser/Unescape.hs, dist/build/Data/Aeson/Parser/Unescape.o )
[ 5 of 21] Compiling Data.Aeson.Parser.Internal ( Data/Aeson/Parser/Internal.hs, dist/build/Data/Aeson/Parser/Internal.o )
[ 6 of 21] Compiling Data.Aeson.Parser ( Data/Aeson/Parser.hs, dist/build/Data/Aeson/Parser.o )
[ 7 of 21] Compiling Data.Aeson.Internal.Time ( Data/Aeson/Internal/Time.hs, dist/build/Data/Aeson/Internal/Time.o )
[ 8 of 21] Compiling Data.Aeson.Parser.Time ( Data/Aeson/Parser/Time.hs, dist/build/Data/Aeson/Parser/Time.o )
[ 9 of 21] Compiling Data.Aeson.Internal.Functions ( Data/Aeson/Internal/Functions.hs, dist/build/Data/Aeson/Internal/Functions.o )
[10 of 21] Compiling Data.Aeson.Types.FromJSON ( Data/Aeson/Types/FromJSON.hs, dist/build/Data/Aeson/Types/FromJSON.o )

Data/Aeson/Types/FromJSON.hs:470:3: warning: [-Winline-rule-shadowing]
    Rule "FromJSONKeyCoerce: fmap id" may never fire
      because ‘id’ might inline first
    Probable fix: add an INLINE[n] or NOINLINE[n] pragma for ‘id’
[11 of 21] Compiling Data.Aeson.Internal ( Data/Aeson/Internal.hs, dist/build/Data/Aeson/Internal.o )
[12 of 21] Compiling Data.Aeson.Encoding.Builder ( Data/Aeson/Encoding/Builder.hs, dist/build/Data/Aeson/Encoding/Builder.o )
[13 of 21] Compiling Data.Aeson.Encoding.Internal ( Data/Aeson/Encoding/Internal.hs, dist/build/Data/Aeson/Encoding/Internal.o )
[14 of 21] Compiling Data.Aeson.Encoding ( Data/Aeson/Encoding.hs, dist/build/Data/Aeson/Encoding.o )
[15 of 21] Compiling Data.Aeson.Types.ToJSON ( Data/Aeson/Types/ToJSON.hs, dist/build/Data/Aeson/Types/ToJSON.o )
[16 of 21] Compiling Data.Aeson.Types.Class ( Data/Aeson/Types/Class.hs, dist/build/Data/Aeson/Types/Class.o )
[17 of 21] Compiling Data.Aeson.Types ( Data/Aeson/Types.hs, dist/build/Data/Aeson/Types.o )
[18 of 21] Compiling Data.Aeson.Text  ( Data/Aeson/Text.hs, dist/build/Data/Aeson/Text.o )
[19 of 21] Compiling Data.Aeson       ( Data/Aeson.hs, dist/build/Data/Aeson.o )
[20 of 21] Compiling Data.Aeson.Encode ( Data/Aeson/Encode.hs, dist/build/Data/Aeson/Encode.o )
[21 of 21] Compiling Data.Aeson.TH    ( Data/Aeson/TH.hs, dist/build/Data/Aeson/TH.o )
haddockPhase
Running Haddock for aeson-1.1.2.0...
Running hscolour for aeson-1.1.2.0...
Preprocessing library aeson-1.1.2.0...
Preprocessing library aeson-1.1.2.0...
Haddock coverage:
  97% ( 33 / 34) in 'Data.Aeson.Types.Internal'
  Missing documentation for:
    JSONPath (Data/Aeson/Types/Internal.hs:105)
  30% (  3 / 10) in 'Data.Aeson.Types.Generic'
  Missing documentation for:
    IsRecord (Data/Aeson/Types/Generic.hs:46)
    AllNullary (Data/Aeson/Types/Generic.hs:68)
    Tagged2 (Data/Aeson/Types/Generic.hs:82)
    True (Data/Aeson/Types/Generic.hs:86)
    False (Data/Aeson/Types/Generic.hs:87)
    And (Data/Aeson/Types/Generic.hs:89)
    ProductSize (Data/Aeson/Types/Generic.hs:106)
   0% (  0 /  2) in 'Data.Aeson.Parser.UnescapeFFI'
  Missing documentation for:
    Module header
    unescapeText (ffi/Data/Aeson/Parser/UnescapeFFI.hs:50)
   0% (  0 /  2) in 'Data.Aeson.Parser.Unescape'
  Missing documentation for:
    Module header
    unescapeText (ffi/Data/Aeson/Parser/UnescapeFFI.hs:50)
  73% ( 11 / 15) in 'Data.Aeson.Parser.Internal'
  Missing documentation for:
    decodeWith (Data/Aeson/Parser/Internal.hs:236)
    decodeStrictWith (Data/Aeson/Parser/Internal.hs:245)
    eitherDecodeWith (Data/Aeson/Parser/Internal.hs:253)
    eitherDecodeStrictWith (Data/Aeson/Parser/Internal.hs:263)
  73% ( 11 / 15) in 'Data.Aeson.Parser'
  Missing documentation for:
    decodeWith (Data/Aeson/Parser/Internal.hs:236)
    decodeStrictWith (Data/Aeson/Parser/Internal.hs:245)
    eitherDecodeWith (Data/Aeson/Parser/Internal.hs:253)
    eitherDecodeStrictWith (Data/Aeson/Parser/Internal.hs:263)
  33% (  2 /  6) in 'Data.Aeson.Internal.Time'
  Missing documentation for:
    fromPico (Data/Aeson/Internal/Time.hs:34)
    toPico (Data/Aeson/Internal/Time.hs:31)
    diffTimeOfDay64 (Data/Aeson/Internal/Time.hs:54)
    toTimeOfDay64 (Data/Aeson/Internal/Time.hs:60)
 100% (  8 /  8) in 'Data.Aeson.Parser.Time'
 100% (  4 /  4) in 'Data.Aeson.Internal.Functions'
  96% ( 43 / 45) in 'Data.Aeson.Types.FromJSON'
  Missing documentation for:
    Module header
    parseOptionalFieldWith (Data/Aeson/Types/FromJSON.hs:226)
  88% (  7 /  8) in 'Data.Aeson.Internal'
  Missing documentation for:
    JSONPath (Data/Aeson/Types/Internal.hs:105)
  48% ( 10 / 21) in 'Data.Aeson.Encoding.Builder'
  Missing documentation for:
    emptyArray_ (Data/Aeson/Encoding/Builder.hs:156)
    emptyObject_ (Data/Aeson/Encoding/Builder.hs:159)
    object (Data/Aeson/Encoding/Builder.hs:105)
    day (Data/Aeson/Encoding/Builder.hs:188)
    localTime (Data/Aeson/Encoding/Builder.hs:257)
    utcTime (Data/Aeson/Encoding/Builder.hs:253)
    timeOfDay (Data/Aeson/Encoding/Builder.hs:205)
    zonedTime (Data/Aeson/Encoding/Builder.hs:261)
    ascii2 (Data/Aeson/Encoding/Builder.hs:162)
    ascii4 (Data/Aeson/Encoding/Builder.hs:166)
    ascii5 (Data/Aeson/Encoding/Builder.hs:171)
  22% ( 17 / 76) in 'Data.Aeson.Encoding.Internal'
  Missing documentation for:
    Module header
    encodingToLazyByteString (Data/Aeson/Encoding/Internal.hs:93)
    retagEncoding (Data/Aeson/Encoding/Internal.hs:97)
    pair (Data/Aeson/Encoding/Internal.hs:125)
    pair' (Data/Aeson/Encoding/Internal.hs:128)
    nullEncoding (Data/Aeson/Encoding/Internal.hs:140)
    emptyArray_ (Data/Aeson/Encoding/Internal.hs:143)
    emptyObject_ (Data/Aeson/Encoding/Internal.hs:146)
    wrapObject (Data/Aeson/Encoding/Internal.hs:152)
    wrapArray (Data/Aeson/Encoding/Internal.hs:149)
    null_ (Data/Aeson/Encoding/Internal.hs:155)
    bool (Data/Aeson/Encoding/Internal.hs:158)
    text (Data/Aeson/Encoding/Internal.hs:219)
    lazyText (Data/Aeson/Encoding/Internal.hs:222)
    string (Data/Aeson/Encoding/Internal.hs:227)
    list (Data/Aeson/Encoding/Internal.hs:168)
    empty (Data/Aeson/Encoding/Internal.hs:197)
    >< (Data/Aeson/Encoding/Internal.hs:204)
    econcat (Data/Aeson/Encoding/Internal.hs:200)
    int8 (Data/Aeson/Encoding/Internal.hs:246)
    int16 (Data/Aeson/Encoding/Internal.hs:249)
    int32 (Data/Aeson/Encoding/Internal.hs:252)
    int64 (Data/Aeson/Encoding/Internal.hs:255)
    int (Data/Aeson/Encoding/Internal.hs:258)
    word8 (Data/Aeson/Encoding/Internal.hs:261)
    word16 (Data/Aeson/Encoding/Internal.hs:264)
    word32 (Data/Aeson/Encoding/Internal.hs:267)
    word64 (Data/Aeson/Encoding/Internal.hs:270)
    word (Data/Aeson/Encoding/Internal.hs:273)
    integer (Data/Aeson/Encoding/Internal.hs:276)
    float (Data/Aeson/Encoding/Internal.hs:279)
    double (Data/Aeson/Encoding/Internal.hs:282)
    scientific (Data/Aeson/Encoding/Internal.hs:285)
    int8Text (Data/Aeson/Encoding/Internal.hs:298)
    int16Text (Data/Aeson/Encoding/Internal.hs:301)
    int32Text (Data/Aeson/Encoding/Internal.hs:304)
    int64Text (Data/Aeson/Encoding/Internal.hs:307)
    intText (Data/Aeson/Encoding/Internal.hs:310)
    word8Text (Data/Aeson/Encoding/Internal.hs:313)
    word16Text (Data/Aeson/Encoding/Internal.hs:316)
    word32Text (Data/Aeson/Encoding/Internal.hs:319)
    word64Text (Data/Aeson/Encoding/Internal.hs:322)
    wordText (Data/Aeson/Encoding/Internal.hs:325)
    integerText (Data/Aeson/Encoding/Internal.hs:328)
    floatText (Data/Aeson/Encoding/Internal.hs:331)
    doubleText (Data/Aeson/Encoding/Internal.hs:334)
    scientificText (Data/Aeson/Encoding/Internal.hs:337)
    day (Data/Aeson/Encoding/Internal.hs:344)
    localTime (Data/Aeson/Encoding/Internal.hs:347)
    utcTime (Data/Aeson/Encoding/Internal.hs:350)
    timeOfDay (Data/Aeson/Encoding/Internal.hs:353)
    zonedTime (Data/Aeson/Encoding/Internal.hs:356)
    value (Data/Aeson/Encoding/Internal.hs:363)
    comma (Data/Aeson/Encoding/Internal.hs:234)
    colon (Data/Aeson/Encoding/Internal.hs:234)
    openBracket (Data/Aeson/Encoding/Internal.hs:234)
    closeBracket (Data/Aeson/Encoding/Internal.hs:234)
    openCurly (Data/Aeson/Encoding/Internal.hs:234)
    closeCurly (Data/Aeson/Encoding/Internal.hs:234)
  25% ( 15 / 61) in 'Data.Aeson.Encoding'
  Missing documentation for:
    encodingToLazyByteString (Data/Aeson/Encoding/Internal.hs:93)
    pair (Data/Aeson/Encoding/Internal.hs:125)
    pair' (Data/Aeson/Encoding/Internal.hs:128)
    nullEncoding (Data/Aeson/Encoding/Internal.hs:140)
    emptyArray_ (Data/Aeson/Encoding/Internal.hs:143)
    emptyObject_ (Data/Aeson/Encoding/Internal.hs:146)
    text (Data/Aeson/Encoding/Internal.hs:219)
    lazyText (Data/Aeson/Encoding/Internal.hs:222)
    string (Data/Aeson/Encoding/Internal.hs:227)
    list (Data/Aeson/Encoding/Internal.hs:168)
    null_ (Data/Aeson/Encoding/Internal.hs:155)
    bool (Data/Aeson/Encoding/Internal.hs:158)
    int8 (Data/Aeson/Encoding/Internal.hs:246)
    int16 (Data/Aeson/Encoding/Internal.hs:249)
    int32 (Data/Aeson/Encoding/Internal.hs:252)
    int64 (Data/Aeson/Encoding/Internal.hs:255)
    int (Data/Aeson/Encoding/Internal.hs:258)
    word8 (Data/Aeson/Encoding/Internal.hs:261)
    word16 (Data/Aeson/Encoding/Internal.hs:264)
    word32 (Data/Aeson/Encoding/Internal.hs:267)
    word64 (Data/Aeson/Encoding/Internal.hs:270)
    word (Data/Aeson/Encoding/Internal.hs:273)
    integer (Data/Aeson/Encoding/Internal.hs:276)
    float (Data/Aeson/Encoding/Internal.hs:279)
    double (Data/Aeson/Encoding/Internal.hs:282)
    scientific (Data/Aeson/Encoding/Internal.hs:285)
    int8Text (Data/Aeson/Encoding/Internal.hs:298)
    int16Text (Data/Aeson/Encoding/Internal.hs:301)
    int32Text (Data/Aeson/Encoding/Internal.hs:304)
    int64Text (Data/Aeson/Encoding/Internal.hs:307)
    intText (Data/Aeson/Encoding/Internal.hs:310)
    word8Text (Data/Aeson/Encoding/Internal.hs:313)
    word16Text (Data/Aeson/Encoding/Internal.hs:316)
    word32Text (Data/Aeson/Encoding/Internal.hs:319)
    word64Text (Data/Aeson/Encoding/Internal.hs:322)
    wordText (Data/Aeson/Encoding/Internal.hs:325)
    integerText (Data/Aeson/Encoding/Internal.hs:328)
    floatText (Data/Aeson/Encoding/Internal.hs:331)
    doubleText (Data/Aeson/Encoding/Internal.hs:334)
    scientificText (Data/Aeson/Encoding/Internal.hs:337)
    day (Data/Aeson/Encoding/Internal.hs:344)
    localTime (Data/Aeson/Encoding/Internal.hs:347)
    utcTime (Data/Aeson/Encoding/Internal.hs:350)
    timeOfDay (Data/Aeson/Encoding/Internal.hs:353)
    zonedTime (Data/Aeson/Encoding/Internal.hs:356)
    value (Data/Aeson/Encoding/Internal.hs:363)
  93% ( 27 / 29) in 'Data.Aeson.Types.ToJSON'
  Missing documentation for:
    Module header
    ToJSONKeyFunction (Data/Aeson/Types/ToJSON.hs:461)
  99% ( 66 / 67) in 'Data.Aeson.Types.Class'
  Missing documentation for:
    ToJSONKeyFunction (Data/Aeson/Types/ToJSON.hs:461)
  99% ( 90 / 91) in 'Data.Aeson.Types'
  Missing documentation for:
    ToJSONKeyFunction (Data/Aeson/Types/ToJSON.hs:461)
 100% (  3 /  3) in 'Data.Aeson.Text'
  99% ( 88 / 89) in 'Data.Aeson'
  Missing documentation for:
    ToJSONKeyFunction (Data/Aeson/Types/ToJSON.hs:461)
  33% (  1 /  3) in 'Data.Aeson.Encode'
  Missing documentation for:
    encode (Data/Aeson/Encode.hs:24)
    encodeToTextBuilder (Data/Aeson/Encode.hs:28)
 100% ( 25 / 25) in 'Data.Aeson.TH'
Warning: Data.Aeson.Types: could not find link destinations for:
    CoerceText AllNullary ParseSum FromProduct ProductSize ConsFromJSON SumToJSON WriteProduct ConsToJSON SumToEncoding EncodeProduct ConsToEncoding
Warning: Data.Aeson: could not find link destinations for:
    CoerceText AllNullary ParseSum FromProduct ProductSize ConsFromJSON SumToJSON WriteProduct ConsToJSON SumToEncoding EncodeProduct ConsToEncoding
Warning: Data.Aeson.TH: could not find link destinations for:
    StarKindStatus
Documentation created: dist/doc/html/aeson/index.html,
dist/doc/html/aeson/aeson.txt
installing
Installing library in
/nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0/lib/ghc-8.0.2/aeson-1.1.2.0
Creating package registration file:
/nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0/lib/ghc-8.0.2/package.conf.d/aeson-1.1.2.0.conf
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0
shrinking /nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0/lib/ghc-8.0.2/x86_64-linux-ghc-8.0.2/libHSaeson-1.1.2.0-7Re5aZ6MrFBBjqn2gRS4FJ-ghc8.0.2.so
stripping (with flags -S) in /nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0/lib 
patching script interpreter paths in /nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0
checking for references to /tmp/nix-build-aeson-1.1.2.0.drv-0 in /nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0...
shrinking RPATHs of ELF executables and libraries in /nix/store/1qdb93rd0rc6b4hz4gzzhcxdfammn8k7-aeson-1.1.2.0-doc
patching script interpreter paths in /nix/store/1qdb93rd0rc6b4hz4gzzhcxdfammn8k7-aeson-1.1.2.0-doc
checking for references to /tmp/nix-build-aeson-1.1.2.0.drv-0 in /nix/store/1qdb93rd0rc6b4hz4gzzhcxdfammn8k7-aeson-1.1.2.0-doc...
warning: rewriting hashes in ‘/nix/store/dy6fgcgjabf9akc7wkb9pna4nrzjd8ci-aeson-1.1.2.0-doc’; cross fingers
warning: rewriting hashes in ‘/nix/store/z07gd9fvzr65vp65yjqypldp3zvxar32-aeson-1.1.2.0’; cross fingers
error: derivation ‘/nix/store/xfzsgd0g6bzak43mndw1z8953bgny7sy-aeson-1.1.2.0.drv’ may not be deterministic: output ‘/nix/store/z07gd9fvzr65vp65yjqypldp3zvxar32-aeson-1.1.2.0’ differs
tanzeel@tanzeel01:~/nixpkgs$

**Comment by domenkozar** [comment] 2017-11-22 18:26
Solved downstream.

The gist is: `stack setup` installs system GHC, which then leaks system glibc to the Nix build.

**Closed by domenkozar** 2017-11-22 18:26 UTC
Labels: 6.topic: haskell

**Comment by drewboardman** [comment] 2020-01-29 22:22
I'm getting this same error, but only on my test files:

```shell
"can't load .so/.DLL for: /nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27/lib/libpthread.so (/nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27/lib/libpthread.so.0: undefined symbol: __libc_vfork, version GLIBC_PRIVATE)"
```

**Comment by drewboardman** [comment] 2020-01-30 18:03
> Hi @domenkozar,
> 
> I am currently experiencing this very issue. I saw it first in relation to compiling aeson and now when compiling wreq.. either way the problem is the same:
> 
> ```
> <command line>: can't load .so/.DLL for: /nix/store/z0b60y0khix9jb74ka56gw7b7n9s8awx-glibc-2.26-131/lib/libdl.so (/nix/store/z0b60y0khix9jb74ka56gw7b7n9s8awx-glibc-2.26-131/lib/libdl.so: symbol _dl_catch_error, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference)
> ```
> 
> I have tried all sort of things.. nuking `~/.stack` , updating to latest nixpkgs, then latest unstable, with and without stack integration. No dice.
> 
> Thanks in advance!

What OS/distro are you running? I'm suspecting this has to do with using nix on a non-NixOS system. It seems like a linker error.
