### ISSUE TITLE
nixos-rebuild build-vm-with-bootloader fails

### ISSUE THREAD

**Issue by globin** [NixOS/nixpkgs#23443] opened 2017-03-03 13:26 UTC
vm.nix:
```
{ ... }:
{
  boot.loader.grub.memtest86.enable = true;
  users.extraUsers.root = {
    initialPassword = "";
  };
}
```

```
nixos-rebuild build-vm-with-bootloader -I nixos-config=./vm.nix
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/f66b04r2j796jig4wkclyqjhnin4gy8w-nixos-boot-disk.drv
  /nix/store/f4q0vai863x1syqzjgdg19zgswl50kky-run-nixos-vm.drv
  /nix/store/jj3zi0b8i9dcs5l091nwnh6ifm45a60c-nixos-vm.drv
building path(s) ‘/nix/store/wy7g7w49mvxwnq6s1k0gnkxhjfyhirqa-nixos-boot-disk’
Formatting '/nix/store/wy7g7w49mvxwnq6s1k0gnkxhjfyhirqa-nixos-boot-disk/disk.img', fmt=qcow2 size=41943040 encryption=off cluster_size=65536 lazy_refcounts=off refcount_bits=16
QEMU 2.8.0 monitor - type 'help' for more information
(qemu) char device redirected to /dev/pts/0 (label serial0)
builder for ‘/nix/store/f66b04r2j796jig4wkclyqjhnin4gy8w-nixos-boot-disk.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/f4q0vai863x1syqzjgdg19zgswl50kky-run-nixos-vm.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/jj3zi0b8i9dcs5l091nwnh6ifm45a60c-nixos-vm.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/jj3zi0b8i9dcs5l091nwnh6ifm45a60c-nixos-vm.drv’ failed
```

cc @edolstra @ts468

**Comment by bjornfor** [comment] 2017-03-03 14:18
Duplicate of https://github.com/NixOS/nixpkgs/issues/18783.

**Closed by bjornfor** 2017-03-03 14:18 UTC
Labels: 0.kind: bug
