### ISSUE TITLE
Update request: rocmPackages.hipblas  5.7.1 → 6.0.0

### ISSUE THREAD

**Issue by ca5ua1** [NixOS/nixpkgs#285279] opened 2024-01-31 13:53 UTC
- Package name: rocmPackages.hipblas
- Latest released version: 6.0.0? [hipBLAS 2.0.0 for ROCm 6.0.0](https://github.com/ROCm/hipBLAS/releases/tag/rocm-6.0.0)

- Current version on the unstable channel: 5.7.1
- Current version on the stable/release channel: 5.7.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

Well, there is https://github.com/NixOS/nixpkgs/issues/197885 and there was acknowledgement of 
> ROCm 6.0.0 has been released.

And I guess it's **pretty** relevant.

Also worth to mention that I create this issue because [Ollama's update](https://github.com/NixOS/nixpkgs/issues/280030) needs `libhipblas.so.2` library.

**Notify maintainers**
@Madouura 
@Flakebi 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Tungsten842** [comment] 2024-01-31 22:35
duplicate of: https://github.com/NixOS/nixpkgs/issues/280927

**Closed** 2024-01-31 22:35 UTC
Labels: 9.needs: package (update)

**Comment by mschwaig** [comment] 2024-02-06 13:06
This should be closed as not planned, since it's a duplicate.
