### ISSUE TITLE
powerline commands fail due to a missing module

### ISSUE THREAD

**Issue by alexvorobiev** [NixOS/nixpkgs#20167] opened 2016-11-04 18:21 UTC
## Issue description
I have installed powerline but all commands I tried (powerline-config, powerline-daemon) show an error message:
```
$ powerline-config bash setup
Traceback (most recent call last):
  File "/nix/store/fqilwb46il7f15s2a8wslpcj05mny12z-python2.7-powerline-2.1.4/bin/.powerline-config-wrapped", line 12, in <module>
    from powerline.commands.config import get_argparser
ImportError: No module named commands.config
```

### Steps to reproduce
```
nix-env -iA nixpkgs.python27Packages.powerline
powerline-config bash setup
```

## Technical details

* System:
```
$ lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.8 (Santiago)
Release:        6.8
Codename:       Santiago
```
* Nix version: `nix-env (Nix) 1.11.4`
* Nixpkgs version: "16.09pre90254.6b20d5b"

**Comment by pSub** [comment] 2016-12-13 20:56
I cannot reproduce the issue. I build it using the nixpkgs revision you provided, but the execution of the above command leads to:

```
usage: powerline-config [-h] [-p PATH] {tmux,shell} ...
powerline-config: error: invalid choice: 'bash' (choose from 'tmux', 'shell')
```

cc maintainer @lovek323  Maybe you have an idea?

**Comment by pSub** [comment] 2017-03-28 15:51
Closing this for now. If this problem should persists feel free to comment or reopen.

**Closed by pSub** 2017-03-28 15:51 UTC

**Comment by EdwardBetts** [comment] 2017-08-29 08:35
I had the same error, it was because I had an old copy of powerline in my home dir.
The fix is to remove ~/.local/lib/python2.7/site-packages/powerline
