### ISSUE TITLE
[24.05] Build failure: ffmpeg_7-full

### ISSUE THREAD

**Issue by Eveeifyeve** [NixOS/nixpkgs#335351] opened 2024-08-17 11:34 UTC
### Steps To Reproduce

1. build ffmpeg_7-full on `aarch64-darwin`.

### Build log

```
CC      tests/checkasm/v210dec.o
1 warning generated.
CC      tests/checkasm/v210enc.o
CC      tests/checkasm/vc1dsp.o
CC      tests/checkasm/vf_blend.o
CC      tests/checkasm/vf_bwdif.o
CC      tests/checkasm/vf_colorspace.o
CC      tests/checkasm/vf_convolution.o
CC      tests/checkasm/vf_eq.o
18 warnings generated.
CC      tests/checkasm/vf_gblur.o
CC      tests/checkasm/vf_hflip.o
CC      tests/checkasm/vf_nlmeans.o
CC      tests/checkasm/vf_threshold.o
CC      tests/checkasm/videodsp.o
CC      tests/checkasm/vorbisdsp.o
CC      tests/checkasm/vp8dsp.o
CC      tests/checkasm/vp9dsp.o
CC      tests/checkasm/vvc_mc.o
AR      libavdevice/libavdevice.a
AR      libpostproc/libpostproc.a
CC      tests/api/api-threadmessage-test.o
CC      tests/api/api-flac-test.o
CC      tests/api/api-seek-test.o
HOSTCC  tests/audiogen.o
HOSTCC  tests/videogen.o
COPY    tests/data/filtergraphs/anequalizer
COPY    tests/data/filtergraphs/firequalizer
COPY    tests/data/filtergraphs/compand
COPY    tests/data/filtergraphs/channelmap_one_int
GEN     tests/data/hls-list.m3u8
GEN     tests/data/hls-list-append.m3u8
COPY    tests/data/filtergraphs/channelmap_one_str
COPY    tests/data/filtergraphs/overlay
COPY    tests/data/filtergraphs/overlay_rgb
make: *** [tests/fate/filter-audio.mak:209: tests/data/hls-list.m3u8] Error 134
make: *** Waiting for unfinished jobs....
make: *** [tests/fate/filter-audio.mak:219: tests/data/hls-list-append.m3u8] Error 134
```

### Additional context

This is an issue something to with ffmpeg internals with nix on `aarch64-darwin`.

### Notify maintainers

@Atemu, @arthsmn @jopejoe1 

### Metadata

```console
warning: ignoring untrusted substituter 'https://nix-community.cachix.org', you are not a trusted user.
Run `man nix.conf` for more information on the `substituters` configuration option.
 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.0.0, macOS 15.0`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.23.3`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jopejoe1** [comment] 2024-08-17 12:25
This was fixed on unstable by the following prs #322724 #328424 #329380, but this was not backported to 24.05.

**Comment by Eveeifyeve** [comment] 2024-08-18 04:58
I have updated my channel trying to build the package again.

**Comment by Eveeifyeve** [comment] 2024-08-18 04:59
But I am on unstable anyways so this shouldn't be a problem.

**Comment by Eveeifyeve** [comment] 2024-08-18 05:46
I just had to update my channel and that seemed to fix the issue.
For flake update using `nix flake update` and non-flakes use `nix-channel --update`

**Comment by Atemu** [comment] 2024-08-18 11:50
I also just checked nixos-24.05 just to be sure and ffmpeg_7-full builds just fine.

**Comment by jopejoe1** [comment] 2024-08-18 18:07
> I also just checked nixos-24.05 just to be sure and ffmpeg_7-full builds just fine.

Strange i was checking hydra and the build for ffmpeg_7-full on darwin-24.05 was failing.

https://hydra.nixos.org/job/nixpkgs/nixpkgs-24.05-darwin/ffmpeg_7-full.aarch64-darwin

**Comment by Atemu** [comment] 2024-08-18 21:02
Ohhh, darwin. Right.

Not sure whether we want to bother backporting that. I don't think it's worth it personally.

**Comment by Eveeifyeve** [comment] 2024-08-24 13:30
> Ohhh, darwin. Right.
> 
> Not sure whether we want to bother backporting that. I don't think it's worth it personally.

It's failing at `make: *** [tests/fate/filter-audio.mak:209: tests/data/hls-list.m3u8] Error 134` for aarch64-darwin.

### x86_64 stripped errors: 
```
libavdevice/avfoundation.m:765:41: error: must use 'enum' tag to refer to type 'AVMediaType'
static NSArray* getDevicesWithMediaType(AVMediaType mediaType) {
                                        ^
                                        enum 
libavdevice/avfoundation.m:816:50: error: incompatible integer to pointer conversion sending 'enum AVMediaType' to parameter of type 'NSString *' [-Wint-conversion]
    return [AVCaptureDevice devicesWithMediaType:mediaType];
                                                 ^~~~~~~~~
libavdevice/avfoundation.m:829:54: error: incompatible pointer to integer conversion passing 'NSString *const' to parameter of type 'enum AVMediaType' [-Wint-conversion]
    NSArray *devices       = getDevicesWithMediaType(AVMediaTypeVideo);
                                                     ^~~~~~~~~~~~~~~~
libavdevice/avfoundation.m:830:54: error: incompatible pointer to integer conversion passing 'NSString *const' to parameter of type 'enum AVMediaType' [-Wint-conversion]
    NSArray *devices_muxed = getDevicesWithMediaType(AVMediaTypeMuxed);
                                                     ^~~~~~~~~~~~~~~~
libavdevice/avfoundation.m:865:43: error: incompatible pointer to integer conversion passing 'NSString *const' to parameter of type 'enum AVMediaType' [-Wint-conversion]
        devices = getDevicesWithMediaType(AVMediaTypeAudio);
                                          ^~~~~~~~~~~~~~~~
libavdevice/avfoundation.m:989:52: error: incompatible pointer to integer conversion passing 'NSString *const' to parameter of type 'enum AVMediaType' [-Wint-conversion]
        NSArray *devices = getDevicesWithMediaType(AVMediaTypeAudio);
                                                   ^~~~~~~~~~~~~~~~
libavdevice/avfoundation.m:1002:52: error: incompatible pointer to integer conversion passing 'NSString *const' to parameter of type 'enum AVMediaType' [-Wint-conversion]
        NSArray *devices = getDevicesWithMediaType(AVMediaTypeAudio);
                                                   ^~~~~~~~~~~~~~~~

make: *** [ffbuild/common.mak:87: libavdevice/avfoundation.o] Error 1
```

**Comment by Atemu** [comment] 2024-08-24 15:24
We know the cause (it's already fixed on unstable), we're just deliberating whether we should bother to backport because it was broken on 24.05 from the beginning.

Given @jopejoe1 appears to have the same opinion as me, I don't think we will.

**Closed by Atemu** 2024-08-24 15:24 UTC
Labels: 6.topic: darwin, 0.kind: build failure
