### ISSUE TITLE
linuxPackages.rtl8821ce can't be compiled

### ISSUE THREAD

**Issue by lerhyd** [NixOS/nixpkgs#88068] opened 2020-05-18 13:06 UTC
**Describe**
The package rtl8821ce can't be compiled due to errors.
https://github.com/NixOS/nixpkgs/blob/8568f68e612d203c54c14f39f38350d0043364b6/pkgs/os-specific/linux/rtl8821ce/default.nix

**Comment by msfjarvis** [comment] 2020-05-18 21:47
The package is [rather behind](https://github.com/tomaspinho/rtl8821ce/compare/ab6154e150bbc7d12b0525d4cc1298ae196e45de...master) the upstream GitHub repository it tracks which is the cause of this breakage. Bumping it to master should suffice in resolving this.

**Comment by msfjarvis** [comment] 2020-05-24 19:40
https://github.com/NixOS/nixpkgs/pull/88809 fixes this for me and WiFi works perfectly.

**Closed** 2020-06-26 02:37 UTC
Labels: 0.kind: bug, 6.topic: kernel
