### ISSUE TITLE
plasma6: black screen with a cursor after login

### ISSUE THREAD

**Issue by CHN-beta** [NixOS/nixpkgs#315246] opened 2024-05-28 04:38 UTC
### Describe the bug

After logging in using a fresh user, plasma6 showed only a black screen with a cursor. (see screenshot 1)

`plasmashell` refused to start, as it could not connect to `kactivitymanagerd`.

```
kde.plasmashell: Aborting shell load: The activity manager daemon (kactivitymanagerd) is not running.
kde.plasmashell: If this Plasma has been installed into a custom prefix, verify that its D-Bus services dir is known to the system for the daemon to be activatable.
```

Full log see [plasmashell.txt](https://github.com/NixOS/nixpkgs/files/15464153/plasmashell.txt).

However, `kactivitymanagerd` seem started normally.

```
May 28 12:42:16 pc systemd[2838]: Started KActivityManager Activity manager Service
```

Full log see [kactivitymanagerd.txt](https://github.com/NixOS/nixpkgs/files/15464158/kactivitymanagerd.txt).

In d-spy, `org.kde.ActivityManager` could be found in session dbus (see screenshot 2).

dbus services complained a lot of "duplicate name". See [dbus.txt](https://github.com/NixOS/nixpkgs/files/15464160/dbus.txt).

All logs (`journalctl -b 0`) see [log.txt](https://github.com/NixOS/nixpkgs/files/15464165/log.txt).

### Steps To Reproduce

Use [this](https://github.com/CHN-beta/nixos/tree/next) flake. (`nixosConfigurations.pc`)

I have tried these modifications but nothing works (on branch `next-debug`):

1. switch to default kernel (`linuxPackages`) without any custom patch.
2. disable cuda and `hostPlatform.gcc.arch = "znver4"`.
3. disable all home-manager stuff and impermanence mount about directories under the user home, to keep the home directory as clean as possible.
4. use X11 instead of Wayland.
5. switch between Nvidia graphic card only and amd+nvidia hybrid offload.
6. add `nvidia-drm.fbdev=1` to the kernel parameter. 

The same problem also exist on @Cryolitia 's GPD ([This flake](https://github.com/cryolitia/nixos-config), `nixosConfigurations.cryolitia-gpd-nixos`).

### Expected behavior

Plasma started with the default wallpaper and status bar.

### Screenshots

![](https://github.com/NixOS/nixpkgs/assets/35858462/a9ccb9b1-8dff-4c6d-aeef-43da142f2bc1)

![](https://github.com/NixOS/nixpkgs/assets/35858462/7b7305fa-c9cd-4eca-87be-cfa35281dac5)

### Notify maintainers

I am not sure which people should I notify, as I could not which part of nixpkgs led to this problem.

### Metadata

- system: `"x86_64-linux"`
- host os: `Linux 6.9.1-cachyos, NixOS, 24.05 (Uakari), 24.05`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.18.2`
- nixpkgs: `/nix/store/gy21mdwskf5343sdmwra2x1rm9z24bix-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Cryolitia** [comment] 2024-05-28 04:40
Same on me

**Comment by CoelacanthusHex** [comment] 2024-05-28 06:00
A strange thing is why plasmashell 6 tries to load qt5 plugins.
```
May 28 12:42:16 pc plasmashell[3466]: kf.coreaddons: The plugin "/nix/store/r57jxbq8xzwplvp221kpp691jk5ldgg7-system-path/lib/qt-5.15.12/plugins/plasma/containmentactions/plasma_containmentactions_applauncher.so" explicitly states an Id in the embedded metadata, which is different from the one derived from the filename The Id field from the KPlugin object in the metadata should be removed
```

**Comment by CoelacanthusHex** [comment] 2024-05-28 06:39
There is some guess, from
```
May 28 12:42:16 pc plasmashell[3466]: kde.plasmashell: Aborting shell load: The activity manager daemon (kactivitymanagerd) is not running.
May 28 12:42:16 pc plasmashell[3466]: kde.plasmashell: If this Plasma has been installed into a custom prefix, verify that its D-Bus services dir is known to the system for the daemon to be activatable.
May 28 12:42:16 pc kactivitymanagerd[3506]: kf.windowsystem: virtual void KX11Extras::connectNotify(const QMetaMethod&) may only be used on X11
May 28 12:42:16 pc kactivitymanagerd[3506]: kf.windowsystem: virtual void KX11Extras::connectNotify(const QMetaMethod&) may only be used on X11
May 28 12:42:16 pc plasmashell[3466]: kde.plasmashell: Aborting shell load: The activity manager daemon (kactivitymanagerd) is not running.
May 28 12:42:16 pc plasmashell[3466]: kde.plasmashell: If this Plasma has been installed into a custom prefix, verify that its D-Bus services dir is known to the system for the daemon to be activatable.
May 28 12:42:16 pc systemd[2838]: Started KActivityManager Activity manager Service.
```
it may be a race condition. Try `systemctl --user restart plasmashell.service` to check this guess.

If not caused by this, write `export QT_LOGGING_RULES="org.kde.kactivities.*.debug=true"` in `~/.config/plasma-workspace/env/debug.sh` to enable debug log for KActivityManagerd (sadly, there is no debug log in KActivities library), and then open a tty/ssh and execute `dbus-monitor --session "interface='org.kde.ActivityManager'" &> dbus.log` to monitor any request to KAMD. Then switch back to SDDM and log in to Plasma. Finally, post the dbus.log and journalctl output here.

**Comment by CHN-beta** [comment] 2024-05-28 07:00
> it may be a race condition. Try `systemctl --user restart plasmashell.service` to check this guess.

It does not work.

> If not caused by this, write `export QT_LOGGING_RULES="org.kde.kactivities.*.debug=true"` in `~/.config/plasma-workspace/env/debug.sh` to enable debug log for KActivityManagerd (sadly, there is no debug log in KActivities library), and then open a tty/ssh and execute `dbus-monitor --session "interface='org.kde.ActivityManager'" &> dbus.log` to monitor any request to KAMD. Then switch back to SDDM and log in to Plasma. Finally, post the dbus.log and journalctl output here.

There are only two item in dbus.log:

```
signal time=1716878876.363339 sender=org.freedesktop.DBus -> destination=:1.3 serial=4294967295 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
string ":1.3"
signal time=1716878876.363359 sender=org.freedesktop.DBus -> destination=:1.3 serial=4294967295 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
string ":1.3"
```

Here is `journalctl -b -1` after reboot: [journalctl.log](https://github.com/NixOS/nixpkgs/files/15465234/journalctl.log)

**Comment by CHN-beta** [comment] 2024-05-28 12:37
I have found the problem. Some theme packages (such as `utterly-nord-plasma`) contain a file named `nix-support/propagated-user-env-packages` whose content is some qt5 library pathes. If I add these theme packages into `environment.systemPackages`, the qt5 libraries listed in the file will also be added to the environment, causing a conflict with qt6 and plasma6.
Solution is to remove these packages from `environment.systemPackages`.

**Comment by Cryolitia** [comment] 2024-05-28 14:42
It's still a problem that should be fixed, do not close.

I remember that I uses `pkgs.nordic`, that's probably why I met the problem, too.

CC @romildo if you have any idea.

**Closed** 2024-05-29 17:54 UTC
Labels: 0.kind: bug, 6.topic: qt/kde

**Comment by mlncn** [comment] 2024-11-15 19:09
How do you check the package dependency chain for qt5 libraries instead of qt6?  (May have run into this same problem, but don't have any of the same packages mentioned so far.)

**Comment by CHN-beta** [comment] 2024-11-16 09:15
> How do you check the package dependency chain for qt5 libraries instead of qt6? (May have run into this same problem, but don't have any of the same packages mentioned so far.)

Try to find some packages that are installed on your machine but merely installed on other people's machines. Remove them and see if the issue has gone. If yes, you may be probably meeting the same issue.

**Comment by Jonas-Sander** [comment] 2024-12-14 13:11
> Try to find some packages that are installed on your machine but merely installed on other people's machines.

I don't understand what you're saying.

**Comment by CHN-beta** [comment] 2024-12-14 16:58
> I don't understand what you're saying.

Some packages are only installed by very few people (mostly some theme packages), so they may be still packaged using qt5 instead of qt6, and the problem may not be reported. Install these packages together with kde6 will cause problem discussed in this issue.
