### ISSUE TITLE
flask-restful tests fail with pytz 2024.2

### ISSUE THREAD

**Issue by WojciechSadowski** [NixOS/nixpkgs#351143] opened 2024-10-25 10:54 UTC
### Describe the bug
Commit https://github.com/NixOS/nixpkgs/commit/15f9d09c26267c391b79a1be98e257a888731c03 has updated pytz from 2024.1 to 2024.2 which causes flask-restful tests to fail.

### Steps To Reproduce
Build flask-restful after commit https://github.com/NixOS/nixpkgs/commit/15f9d09c26267c391b79a1be98e257a888731c03 (`nix-shell -p changedetection-io` using unstable channel)
tests ``test_iso8601_date_field_with_offset`` and ``test_rfc822_date_field_with_offset`` fails.

### Build log
```
=================================== FAILURES ===================================
______________ FieldsTestCase.test_iso8601_date_field_with_offset ______________

self = <tests.test_fields.FieldsTestCase testMethod=test_iso8601_date_field_with_offset>

    def test_iso8601_date_field_with_offset(self):
        obj = {"bar": datetime(2011, 8, 22, 20, 58, 45, tzinfo=pytz.timezone('CET'))}
        field = fields.DateTime(dt_format='iso8601')
>       self.assertEqual("2011-08-22T20:58:45+01:00", field.output("bar", obj))
E       AssertionError: '2011-08-22T20:58:45+01:00' != '2011-08-22T20:58:45+00:18'
E       - 2011-08-22T20:58:45+01:00
E       ?                       ^^^
E       + 2011-08-22T20:58:45+00:18
E       ?                      ++ ^

tests/test_fields.py:378: AssertionError
______________ FieldsTestCase.test_rfc822_date_field_with_offset _______________

self = <tests.test_fields.FieldsTestCase testMethod=test_rfc822_date_field_with_offset>

    def test_rfc822_date_field_with_offset(self):
        obj = {"bar": datetime(2011, 8, 22, 20, 58, 45, tzinfo=pytz.timezone('CET'))}
        field = fields.DateTime()
>       self.assertEqual("Mon, 22 Aug 2011 19:58:45 -0000", field.output("bar", obj))
E       AssertionError: 'Mon, 22 Aug 2011 19:58:45 -0000' != 'Mon, 22 Aug 2011 20:40:45 -0000'
E       - Mon, 22 Aug 2011 19:58:45 -0000
E       ?                  ^^ ^^
E       + Mon, 22 Aug 2011 20:40:45 -0000
E       ?                  ^^ ^^

tests/test_fields.py:368: AssertionError
=============================== warnings summary ===============================
tests/test_api.py:39
  tests/test_api.py:39: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_unpack will be ignored
    def test_unpack():

tests/test_fields.py:28
  tests/test_fields.py:28: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_float will be ignored
    def test_float():

tests/test_fields.py:38
  tests/test_fields.py:38: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_boolean will be ignored
    def test_boolean():

tests/test_fields.py:50
  tests/test_fields.py:50: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_rfc822_datetime_formatters will be ignored
    def test_rfc822_datetime_formatters():

tests/test_fields.py:64
  tests/test_fields.py:64: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_iso8601_datetime_formatters will be ignored
    def test_iso8601_datetime_formatters():

tests/test_inputs.py:68
  tests/test_inputs.py:68: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_bad_urls will be ignored
    def test_bad_urls():

tests/test_inputs.py:90
  tests/test_inputs.py:90: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_bad_url_error_message will be ignored
    def test_bad_url_error_message():

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_fields.py::FieldsTestCase::test_iso8601_date_field_with_offset - AssertionError: '2011-08-22T20:58:45+01:00' != '2011-08-22T20:58:45+00:18'
FAILED tests/test_fields.py::FieldsTestCase::test_rfc822_date_field_with_offset - AssertionError: 'Mon, 22 Aug 2011 19:58:45 -0000' != 'Mon, 22 Aug 2011 20:4...
====== 2 failed, 310 passed, 3 deselected, 7 xfailed, 7 warnings in 0.70s ======
error: builder for '/nix/store/k2d2p1c7dvyasi4mycb7lc6ffzlmb509-python3.12-flask-restful-0.3.10.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/q69py1dahagqkkz0yawr544znniwp1zf-changedetection-io-0.46.04.drv' failed to build
error: 1 dependencies of derivation '/nix/store/iqr6mqfmb5z90na3cdxg7c208a7b4kjz-system-path.drv' failed to build

````

### Metadata

- system: `"x86_64-linux"`
 - host os: `Linux 6.6.58, NixOS, 24.11 (Vicuna), 24.11.20241023.2768c7d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fabaff** [comment] 2024-10-25 16:14
This was already fixed with https://github.com/NixOS/nixpkgs/commit/382fb553fd14695bad1ff69c6a0d1c2b2d4fb628 (currently in `staging-next`).

**Closed** 2024-10-26 10:48 UTC
Labels: 0.kind: bug

**Comment by CountingBeeps** [comment] 2024-11-11 17:27
I'm currently getting the exact same build crash on the latest unstable. It's been long enough that the fix there should have hit unstable by now, so I don't know what the issue is.
