### ISSUE TITLE
Clang++ wrapper does not add standard header

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#28604] opened 2017-08-27 08:55 UTC
## Issue description

clang++ should receive its standard C++ include path from its wrapper.
However this is not the case.

### Steps to reproduce

```bash
cat foo.cpp <<EOF
#include <iostream>
int main() { }
EOF
nix-shell -p clang --command 'clang++ foo.cpp'
foo.cpp:1:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
1 error generated.
```

manually including works fixes it:f

```
clang++ -isystem /nix/store/vqc58c85wih3gcxpv8jn8n456b5m77da-gcc-6.4.0/include/c++/6.4.0 -isystem /nix/store/vqc58c85wih3gcxpv8jn8n456b5m77da-gcc-6.4.0/include/c++/6.4.0/x86_64-pc-linux-gnu foo.cpp
```
## Technical details

* System: 17.09.git.5e4faeb (Hummingbird)
* Nix version:  nix-env (Nix) 1.12pre5511_c94f3d55
* Nixpkgs version: 9d74fd3e0730ca7e63016b2573950acb8402d372
* Sandboxing enabled: yes

I attached the output of `bash -x clang++ foo.cpp`
[clang++.txt](https://github.com/NixOS/nixpkgs/files/1254244/clang.txt)

**Comment by Ericson2314** [comment] 2017-08-27 18:21
Hmm. Yet again, it seems something is wrong with `CXXSTDLIB_*. (Déjà vu of https://github.com/NixOS/nixpkgs/pull/26474!)

How are you getting access to clang? `nix-shell`. `nix-env`, something else? Right now there is no use of those env vars in the trace you uploaded, just `add-flags boilerplate collecting it.

**Comment by gebner** [comment] 2017-08-27 18:31
This is another duplicate of #28223.

**Closed** 2017-08-27 18:49 UTC

**Comment by Mic92** [comment] 2017-08-28 12:52
@Ericson2314 I used `nix-shell`:

```
$ nix-shell -p clang --command 'clang++ foo.cpp'
```
