### ISSUE TITLE
cairo: Build fails due to hash mismatch of fix-racket.diff (nixos master)

### ISSUE THREAD

**Issue by rzetterberg** [NixOS/nixpkgs#7229] opened 2015-04-07 08:45 UTC
I was trying to build a python package that uses cairo. The [fix-racket.diff](https://github.com/NixOS/nixpkgs/commit/e75fe2e528d745610eb4924e418aee0d85cc582f#diff-c03d6bd547d67ac01dab38702705fda7R24) hash match failed with:

```
trying http://cgit.freedesktop.org/cairo/patch/?id=2de69581c28bf115852037ca41eba13cb7335976
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1271    0  1271    0     0   3192      0 --:--:-- --:--:-- --:--:--  3193
output path ‘/nix/store/d1k14kqxaaics8k54b3h6w3vfqvksxgq-fix-racket.diff’ should have sha256 hash ‘0mk2fd9fwxqzravlmnbbrzwak15wqspn7609y0yn6qh87va5i0x4’, instead has ‘0mdqa9w1p6cmli6976v4wi0sw9r4p5prkj7lzfd1877wk11c9c73’
cannot build derivation ‘/nix/store/sfryldn1fn4hnzykhqlp2f5c0gcqjpfc-cairo-1.14.0.drv’: 1 dependencies couldn't be built
```

I used nix-env inside the nixpkgs dir with `nix-env -f . -iA python34Packages.mynewpackage` when the problem happened.

The wierd thing is that if I use prefetch the hash is different from that error message:

```
[richard@workstation:~]$ nix-prefetch-url --type sha256 http://cgit.freedesktop.org/cairo/patch/?id=2de69581c28bf115852037ca41eba13cb7335976
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1141    0  1141    0     0   2898      0 --:--:-- --:--:-- --:--:--  2903
path is ‘/nix/store/4lm65v6jspnd0pxhn0w73xxz9fmd77wi-?id=2de69581c28bf115852037ca41eba13cb7335976’
1pfdlg7kcrgnazff300p7psxfgqzbcsy98w35aqhdpa3d14894mf
```

I'm on the e52e16019082081c902844f475a3ff76c1a31393 commit on master.

**Comment by vcunat** [comment] 2015-04-07 09:30
That thing isn't weird, as the used ``fetchpatch`` function strips unimportant stuff from the patch to improve determinism, as some parts tend to change due to (c)git updates, etc.

I was in the process of testing a release of cairo including the patch inside, and I expect to push it to staging this week with other changes. In the meantime, you can work around it in any way you like: specify the hash it gives, drop the patch (as it's probably only significant for racket), ...

**Comment by rzetterberg** [comment] 2015-04-07 09:36
Ah, I see!

In the future, should I open tickets for problems encountered in master? Or should I refrain from doing so, since some things can be work in progress?

**Comment by vcunat** [comment] 2015-04-07 09:45
No, this was fine. You could hardly know I was updating cairo (the work wasn't in the main repo, and maybe not even on my github account), and I also didn't know there was a problem with the patch.  

As an alternative workaround, you might want to pick the updating patch 4247ab207.
```
curl https://github.com/NixOS/nixpkgs/commit/4247ab2076236.patch | git am
```

**Comment by rzetterberg** [comment] 2015-04-07 11:12
Alright, good! Just want to make sure I don't cause extra noise/work. 

Thanks for the help!

**Comment by vcunat** [comment] 2015-04-07 11:52
:-) I'm keeping this open until the problem is resolved in master. And I see release-14.12 should have the same problem as well.

**Comment by vcunat** [comment] 2015-06-02 17:42
In master for a long time d3399ca45baffd, and now in 14.12 as well 582ee6ec3.

**Closed by vcunat** 2015-06-02 17:42 UTC
