### ISSUE TITLE
Transmission: Setting `services.transmission.home` results in error

### ISSUE THREAD

**Issue by rasmus-kirk** [NixOS/nixpkgs#291883] opened 2024-02-27 17:00 UTC
### Describe the bug

Setting the `services.transmission.home` option results in error an error complaining that the path you set does not contain `.config/transmission-daemon`

### Steps To Reproduce
Set the `services.transmission.home` option to a directory that does not contain `.config/transmission-daemon`

### Expected behavior
I would expect the service to create the directory and set permissions using `systemd.tmpfiles.rules` or something similar as is what seems to be done in the service module for other directories.

### Notify maintainers

@julm

### Tempoary fix for readers

Set the following option to your config:

```nix
      systemd.tmpfiles.rules = [
        "d /path/to/set/transmission/home/.config/transmission-daemon 0700 transmission root - -"
      ];
```

Or simply create and set permissions of the directory statefully.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by linsui** [comment] 2024-08-26 15:01
Duplicate of https://github.com/NixOS/nixpkgs/issues/183429.

**Closed by linsui** 2024-08-26 15:01 UTC
Labels: 0.kind: bug
