### ISSUE TITLE
`cargo metadata` complains about that `GLIBCXX_3.4.30` was not found

### ISSUE THREAD

**Issue by MathiasSven** [NixOS/nixpkgs#217880] opened 2023-02-23 17:41 UTC
### Describe the bug
In a directory with a `Cargo.toml` running  `cargo metadata` results in an error with this `shell.nix`
```nix
{ pkgs ? import <nixpkgs> { }
}:
with pkgs;

mkShell {
  packages = with pkgs; [
    cargo
    rustc
  ];

  RUST_BACKTRACE = 1;
  RUST_SRC_PATH = "${rustPlatform.rustLibSrc}";
}
```
The error being:
```console
warning: please specify `--format-version` flag explicitly to avoid compatibility problems
error: process didn't exit successfully: `rustc -vV` (exit status: 1)
--- stderr
rustc: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /nix/store/yvcnhajqbwcq35vpnsm1waw557dxcn5v-llvm-15.0.7-lib/lib/libLLVM-15.so)
```

### Steps To Reproduce
1. `nix-shell` on a directory with the `shell.nix` above
2. run `cargo metadata` on the directory with `Cargo.toml`

### Additional context
I initially encountered this "`GLIBCXX_3.4.30` not found" issue after updating my channels, resulting in no longer being able to call `rustc` from a `vscode-fhs` terminal with the `shell.nix` activated plus `rust-analyzer` no longer working. After I realized that this issue was specific to `vscode-fhs` (presumably because of FHS) I performed a `home-manager switch` and `sudo nixos-rebuild switch`... This solved the issue where I was able to run the `rustc` command from inside `vscode-fhs`, however `rust-analyzer` would still not work.

I seems that this was caused by `cargo metadata` exiting with an error, but this time this error was not tied to any FHS. Both running it from inside `vscode-fhs` and `Alacritty` had the same behavior.

### Notify maintainers
@retrry

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.12-zen1, NixOS, 23.05 (Stoat), 23.05pre456838.f5dad40450d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixos"`
 - channels(mathiassven): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by winterqt** [comment] 2023-02-23 17:42
cc @NixOS/rust

**Comment by alyssais** [comment] 2023-02-23 17:50
I couldn't reproduce.  What Nixpkgs commit?  Does anything special need to be in the Cargo.toml?  I tested with 7ce8e7c4cf90492a631e96bcfe70724104914381, which is current master.

**Comment by SuperSandro2000** [comment] 2023-02-23 18:06
Are you by chance mixing different glibc versions? If so you should check how. Maybe LD_LIBRARY_PATH is impurely drawing in an old version?

**Comment by MathiasSven** [comment] 2023-02-23 18:15
After trying to isolate the project folder I tried doing a couple of other things, in the end, it seems that deleting all non-source files resulted in it working again. I apologize if this might have been a trivial issue... As I mentioned I first encountered this issue in a rather roundabout way

**Comment by alyssais** [comment] 2023-02-23 18:41
Can we close this, then?  You'd be welcome to reopen if you can reproduce it in future.

**Closed** 2023-02-23 19:06 UTC
Labels: 0.kind: bug, 6.topic: rust
