### ISSUE TITLE
Cabal derivations with `editedCabalFile` field are broken by new hackage metadata revisions

### ISSUE THREAD

**Issue by jraygauthier** [NixOS/nixpkgs#7532] opened 2015-04-23 23:49 UTC
The problem
----------------

Here's my compiler output:

~~~
setupCompileFlags: -package-db=/tmp/nix-build-haskell-intervals-0.7.1.drv-0/package.conf.d -j1
[1 of 1] Compiling Main             ( Setup.lhs, /tmp/nix-build-haskell-prelude-extras-0.4.drv-0/Main.o )
[1 of 1] Compiling Main             ( Setup.hs, /tmp/nix-build-haskell-parallel-3.2.0.6.drv-0/Main.o )
Linking Setup ...
Linking Setup ...
[1 of 1] Compiling Main             ( Setup.lhs, /tmp/nix-build-haskell-intervals-0.7.1.drv-0/Main.o )

trying http://hackage.haskell.org/package/lens-4.7/lens.cabal
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14484    0 14484    0     0  75285      0 --:--:-- --:--:-- --:--:-- 97864
output path ‘/nix/store/jajagqi8sq7rgz2qdlijkgln0mvzc1y6-lens.cabal’ should have sha256 hash ‘0xaprn01zc22h6lgipdifb0r5s7dkc3rpffhrmpj4j6kkixx74d9’, instead has ‘1cbw7p9daamg5c8y98lwgi25dqxxkgj1jgd2m8h81p2lq743dx5v’
building path(s) ‘/nix/store/rmbi6iadjz398lva4ic7hv7vdwbf71is-gtk2hs-buildtools-0.13.0.3’
cannot build derivation ‘/nix/store/swbs9vxibspsbaic2nkxxg3rfmjiv39k-haskell-lens-4.7.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/gcji0idq19pc2jp76lgfnjxrdfyqk2n7-profunctors-4.4.1.tar.gz’
building path(s) ‘/nix/store/6v97xx2pgv7h0rj905hgp58havhgilmw-reflection-1.5.1.2.tar.gz’
building path(s) ‘/nix/store/3r3r60cgybrhphcfnqfiv2f9lcm4q9ca-semigroupoids-4.3.tar.gz’
cannot build derivation ‘/nix/store/fsdcmcbgvsq7adb0x9jw6iwg2v6s0pni-ghc-7.8.4.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/wcv6y6sn6ghv8pz1y25pfxd7abg19n38-haskell-diagrams-builder-0.6.0.3.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/6wkq86x8wm2zv26zdqkb6rjwhk35s70b-diagrams-builder.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/ni48c7va6kwj37gz7dcbzr6aibm0jj1f-myEnv.drv’: 1 dependencies couldn't be built
~~~

Note the mention: `trying http://hackage.haskell.org/package/lens-4.7/lens.cabal`
which according to the output resulted in SHA: `1cbw7p9daamg5c8y98lwgi25dqxxkgj1jgd2m8h81p2lq743dx5v`

but should have given:
‘0xaprn01zc22h6lgipdifb0r5s7dkc3rpffhrmpj4j6kkixx74d9’

Some supplementary analysis results
-----------------------------------------------

Here we see that the actual value has been properly calculated:

~~~
> $ nix-prefetch-url http://hackage.haskell.org/package/lens-4.7/lens.cabal
...
1cbw7p9daamg5c8y98lwgi25dqxxkgj1jgd2m8h81p2lq743dx5v
~~~

And that it maps to the fifth metadata revision:

~~~
> $ nix-prefetch-url http://hackage.haskell.org/package/lens-4.7/revision/5.cabal;
...
1cbw7p9daamg5c8y98lwgi25dqxxkgj1jgd2m8h81p2lq743dx5v
~~~

Which you can explore here: <http://hackage.haskell.org/package/lens-4.7/revisions/>.

Now, performing some supplementary queries, we can see that the
expected SHA maps to the first metadata revision.

~~~
> $ nix-prefetch-url http://hackage.haskell.org/package/lens-4.7/revision/1.cabal;
...
0xaprn01zc22h6lgipdifb0r5s7dkc3rpffhrmpj4j6kkixx74d9
~~~

Here's the package expressions:

~~~
  "lens" = callPackage
    ({ mkDerivation, array, base, bifunctors, bytestring, comonad
     , containers, contravariant, deepseq, directory, distributive
     , doctest, exceptions, filepath, free, generic-deriving, ghc-prim
     , hashable, hlint, HUnit, mtl, nats, parallel, primitive
     , profunctors, QuickCheck, reflection, semigroupoids, semigroups
     , simple-reflect, split, tagged, template-haskell, test-framework
     , test-framework-hunit, test-framework-quickcheck2
     , test-framework-th, text, transformers, transformers-compat
     , unordered-containers, vector, void
     }:
     mkDerivation {
       pname = "lens";
       version = "4.7";
       sha256 = "1z2ydc90m0cq76yamdaws4677lpi476f9z25xrz8r7y5kxh2aq4s";
       editedCabalFile = "a991d37b9cd348226fcdd0b99b079bede892c172b1ddf8a88142b01f80cd5775";
       buildDepends = [
         array base bifunctors bytestring comonad containers contravariant
         distributive exceptions filepath free ghc-prim hashable mtl
         parallel primitive profunctors reflection semigroupoids semigroups
         split tagged template-haskell text transformers transformers-compat
         unordered-containers vector void
       ];
       testDepends = [
         base bytestring containers deepseq directory doctest filepath
         generic-deriving hlint HUnit mtl nats parallel QuickCheck
         semigroups simple-reflect split test-framework test-framework-hunit
         test-framework-quickcheck2 test-framework-th text transformers
         unordered-containers vector
       ];
       homepage = "http://github.com/ekmett/lens/";
       description = "Lenses, Folds and Traversals";
       license = stdenv.lib.licenses.bsd3;
     }) {};
~~~

Whose `editedCabal` file I can match with:

~~~
> $ curl http://hackage.haskell.org/package/lens-4.7/revision/1.cabal | sha256sum
...
a991d37b9cd348226fcdd0b99b079bede892c172b1ddf8a88142b01f80cd5775
~~~

My understanding
----------------------

I had a cabal nix expression that I could build at some point in time, but now
some time later (such as this case), the package maintainer decides to
update the package's metadata for some reason. Now, I cannot build
my nix expression.

I seem to me that it defeats the purpose of nix / having repeatable
builds.

It seem reasonable to think that we should use the full url to the
specific cabal file revision at the point of generating the expression
(e.g.: <http://hackage.haskell.org/package/lens-4.7/revision/1.cabal>)
instead of the url to the current revision of the file 
(e.g.: <http://hackage.haskell.org/package/lens-4.7/lens.cabal>).

That would imply adding a revision field alongside or within `editedCabalFile`
field.

Now I understand that retrieving the revision would have to be automated
if not already as part of *hackage2nix*.

Meanwhile
-------------

Is there any quick fix in the meantime so that I can get my build running
again?

### Update ###

As a quick fix suggested in [5920#issuecomment-71218347](https://github.com/NixOS/nixpkgs/issues/5920#issuecomment-71218347), I used the following command to
find a new value for the `editedCabalFile`:
~~~
curl http://hackage.haskell.org/package/lens-4.7/revision/5.cabal | sha256sum
...
bbf436c8c154dc8020aaa23d19e49bbde356447c9ca2e4112baf2ad5d23d7cb1
~~~

**Comment by jraygauthier** [comment] 2015-04-24 01:16
Found the code snipped that would have to be adapted:

~~~
              ${let newCabalFile = fetchurl {
                      url = "http://hackage.haskell.org/package/${self.fname}/${self.pname}.cabal";
                      sha256 = self.editedCabalFile;
                    };
                in
                  optionalString (self.editedCabalFile or "" != "") ''
                    echo "Replace Cabal file with edited version ${newCabalFile}."
                    cp ${newCabalFile} ${self.pname}.cabal
                  ''
              }${optionalString self.jailbreak "${jailbreakCabal}/bin/jailbreak-cabal ${self.pname}.cabal"}
~~~

in <https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/cabal/default.nix#L249>

**Comment by jraygauthier** [comment] 2015-04-24 01:35
Also found my answer for the meanwhile sections as part of:

[5920#issuecomment-71218347](https://github.com/NixOS/nixpkgs/issues/5920#issuecomment-71218347)

**Comment by jraygauthier** [comment] 2015-04-24 05:27
I had a quick glance at hackage2nix / cabal2nix source code and it seems it is pretty much ready
for this.

`fetchOrFromDB` would have to take into account the optional revision already present in `Source`
(`sourceRevision`) to generate the url.

`Derivation` returned by `cabal2nix` also already have the `revision` field.

Now, there would be `generatePackageSet`'s following snippet to adapt so that
it tries to find the latest revision and then always fetches it by revision:

~~~
descr = hackage Map.! name Map.! pkgversion
~~~

and then, update `Derivation.revision` with it.

And at the very end, ensure the `revision` field gets printed in:

~~~
return $ nest 2 $ hang (string attr <+> equals <+> text "callPackage") 2 (parens (pPrint drv)) <+> (braces overrides <> semi)
~~~

**Comment by peti** [comment] 2015-04-24 07:20
This is a duplicate of https://github.com/NixOS/nixpkgs/issues/6914.

**Closed** 2015-04-24 07:21 UTC
Labels: duplicate

**Comment by jraygauthier** [comment] 2015-04-24 10:52
Arhgg, I was looking at the wrong cabal builder on git hub repo... Good job for the fix.

Now however this old `haskellPackages`, surrounding tools and individual packages of
are become really irrelevant and a serious pitfall to people trying to understand what's
occurring with their haskellngPackages / haskellngPackages builds. This is even more
the case, now that  ` nixpkgs/pkgs/build-support/cabal/default.nix` has been proven
broken and still contains broken code.

I think it has become the time to do one of 2 things:

 1.  Completely remove all this old broken stuff.
 2.  In all these broken files, add a big noticeable comment specifying
      that this is **deprecated** and possibly broken, specify what is the
      proper alternative file that does the job now (specifying the distinction between
      haskellng and haskellOld and add a reference to the procedure
      how to migrate from one to this other maybe adding some
      convincing points as to why migrate such as this issue). A link to
      such reference would do: 
      <http://lists.science.uu.nl/pipermail/nix-dev/2015-January/015591.html>, a
      wiki entry would be even better.

**Comment by peti** [comment] 2015-04-24 11:05
Please see https://github.com/NixOS/nixpkgs/pull/7465.

**Comment by jraygauthier** [comment] 2015-04-24 12:12
Thanks.
