### ISSUE TITLE
Spotify + PulseAudio : No Sound

### ISSUE THREAD

**Issue by aakropotkin** [NixOS/nixpkgs#64686] opened 2019-07-12 23:06 UTC
## Issue description

You know the deal :(
This has been happening with a lot of my apps with PulseAudio recently. I'm getting no sound from the app and PulseAudio doesn't even seem to detect Spotify.

### Steps to reproduce

```nix
# configuration.nix
{
  hardware.pulseaudio.enable = true;
  environment.systemPackages = with pkgs; [spotify];
}
```

## Technical details

```sh
 - system: `"x86_64-linux"`                
 - host os: `Linux 4.19.57, NixOS, 19.09pre184855.beff2f8d75e (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(camus): `"home-manager, nextbookit, nixos-mio"`
 - channels(root): `"home-manager, nixos-19.09pre184855.beff2f8d75e, nixos-hardware, nixos-stable-18.09.2574.a7e559a5504"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by alexarice** [comment] 2019-07-13 08:42
I can not reproduce this. I have the following pulseaudio setup
```
hardware = {
  pulseaudio = {
    enable = true;
    support32Bit = true;
    package = pkgs.pulseaudioFull;
  };
};
```

**Comment by worldofpeace** [comment] 2019-07-13 14:56
@BadDecisionsAlex I would assume this fix for you would be the same as the other ones.
Adding `libpulseaudio` to `rpath`.

**Comment by gloaming** [comment] 2019-07-14 00:07
@BadDecisionsAlex it's really strange that the PulseAudio ALSA plugin is not working for you. Are you on a Z390 chipset or other recent hardware? Give this a try:
`boot.kernelPackages = pkgs.linuxPackages_latest;`

I had multiple audio and graphical problems before doing that.

That said, I assume we should fix as before.

**Comment by CMCDragonkai** [comment] 2019-08-03 05:22
I'm getting this as well. Spotify doesn't play anything and the it's just stick on 0:00 and I don't see any device on pavucontrol corresponding to spotify.

**Comment by alexameen** [comment] 2019-08-03 05:37
The issue persists with the latest kernel unfortunately

**Comment by timokau** [comment] 2019-08-03 18:01
The discussion [here](https://github.com/NixOS/nixpkgs/pull/65602#issuecomment-517888194) may be relevant, if anyone has ideas.

**Comment by angristan** [comment] 2019-08-04 13:06
Which Spotify version are you running? `1.0.96.181` should still work (but since we upgraded it and rolled back two times already...)

**Comment by alexameen** [comment] 2019-08-06 15:14
I am using 1.0.96.181, it does not work with Pulse. It works fine if I explicitly set `hardware.pulseaudio.enable = false` (to override Gnome's activation of pulse)

**Comment by Ma27** [comment] 2020-03-13 23:58
@alexameen can you please re-test the issue on either release-20.03 and/or master? I'm a pretty heavy spotify user and I'm using pulseaudio by default on my laptop, so I'd be happy to debug this if it still exists :)

**Comment by skykanin** [comment] 2020-07-30 22:20
> @alexameen can you please re-test the issue on either release-20.03 and/or master? I'm a pretty heavy spotify user and I'm using pulseaudio by default on my laptop, so I'd be happy to debug this if it still exists :)

I'm just got the same issue on my NixOS system today. Spotify stuck at 0:00 and not showing up in pavucontrol. More info:
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.10, NixOS, 20.09pre236091.28fce082c8c (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200721_ff314f1`
 - channels(root): `"nixos-20.09pre236419.a45f68ccac4, stable-20.03.2668.7c85b915892"`
 - channels(skykanin): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

My pulseaudio setup:
```
hardware = {
  pulseaudio = {
    enable = true;
    support32Bit = true;
    package = pkgs.pulseaudioFull;
  };
};
```

**Comment by alexarice** [comment] 2020-07-30 22:23
@skyanin I think you're issue might be https://github.com/NixOS/nixpkgs/issues/93955

**Comment by Riey** [comment] 2021-09-03 15:03
I think it's because spotifyd package doesn't include pulseaudio feature default you should override it

https://github.com/NixOS/nixpkgs/blob/3da1c959408f90cb9299d383e5e48a6b2cf13cb3/pkgs/applications/audio/spotifyd/default.nix#L1-L5

**Comment by Ma27** [comment] 2021-09-03 15:05
@Riey I thought this is about spotify, not spotifyd?

**Comment by Riey** [comment] 2021-09-03 15:09
@Ma27 Oops sorry

**Comment by Ma27** [comment] 2021-09-03 15:18
Anyways, I can't remember any similar issues in the last year, so I think that this issue is gone now and we can close it.
If I'm wrong, just re-open or file a new bug :)

**Closed by Ma27** 2021-09-03 15:18 UTC
Labels: 6.topic: nixos
