### ISSUE TITLE
Unity3D "no usable version of libssl was found"

### ISSUE THREAD

**Issue by ilikefrogs101** [NixOS/nixpkgs#250448] opened 2023-08-21 01:23 UTC
### Describe the bug
Cannot use unity 3D editor because of "no usable version of libssl was found"

### Steps To Reproduce
1. Install unity editor from hub
2. open or create a project
3. Error will be in editor console

### Expected behavior
I should able to compile stuff and generally use the editor without a compilation error that does not go away

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/87593516/85141836-1126-4386-abbc-3408926ec5d2)

### Notify maintainers
@tesq0 
@huantianad 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.45, NixOS, 23.05 (Stoat), 23.05.2801.09a137528c3a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by huantianad** [comment] 2023-08-21 01:26
Duplicate of #205019, see bottom comment there for solution.

**Closed** 2023-08-21 01:26 UTC
Labels: 0.kind: bug

**Comment by ilikefrogs101** [comment] 2023-08-21 01:54
I tried that but it only works with unity 2022 and ive had nothing but issues with it lol, I just wanna use the latest version of 2021 and that fix sadly does not appear to work for it, if there is no way I guess I will use 22 but it'd be nice to use 21 if possible

**Comment by ilikefrogs101** [comment] 2023-08-21 02:18
@huantianad I tried that but it only works with unity 2022 and ive had nothing but issues with it lol, I just wanna use the latest version of 2021 and that fix sadly does not appear to work for it, if there is no way I guess I will use 22 but it'd be nice to use 21 if possible

**Comment by huantianad** [comment] 2023-08-21 02:25
Weird, are you sure that adding `openssl_1_1` doesn't work for 2021? I though I had tested it before and it did work. Did you make sure to restart unityhub and make sure that the one you're launching is the one with the added library?

**Comment by ilikefrogs101** [comment] 2023-08-21 06:49
Alright so I feel dumb or annoyed or something now but It wasn't working when I had it like this
```nix
 (pkgs.unityhub.override {
    extraLibs = pkgs: with pkgs; [
      openssl_1_1
    ];
  })
```

it was not working then.

Now when I use 

```nix
  (unityhub.override {
    extraLibs = pkgs: with pkgs; [
      openssl_1_1
    ];
  })
``` it does work

who knows, I just decided to try that and it seems to work so I am very confused but at least its working lol

**Comment by huantianad** [comment] 2023-08-21 20:37
That's very strange 🤔 I have no idea why that would be the case
