### ISSUE TITLE
The result of (nixos-install && nixos-enter) lacks the /tmp directory

### ISSUE THREAD

**Issue by pvgoran** [NixOS/nixpkgs#39140] opened 2018-04-19 07:57 UTC
## Issue description

I have a process that creates a "clean" NixOS filesystem tree for later usage. First, I create the minimal NixOS configuration files at $ROOT/etc/nixos, then I run:

```
nixos-install --no-bootloader --no-root-passwd --root "$ROOT"
nixos-enter --root "$ROOT" -- true
```

(Before 18.03, it worked without `nixos-enter`. I'm not very happy that now I need an additional step, and I'll probably create a separate issue about this. But I can understand that `nixos-install` creates a minimal installation and `nixos-enter` activates it.)

I expect to be able to chroot into the resulting filesystem tree and have a fully-working NixOS system. However, these steps don't create the `/tmp` directory, which prevents `nixos-rebuild` from working:

```
[root@nixos-seed:/]# nixos-rebuild dry-build
mktemp: failed to create directory via template ‘/tmp/nixos-rebuild.XXXXXX’: No such file or directory
```

### Steps to reproduce

Build the NixOS tree:

```
mkdir seed
mkdir -p seed/etc/nixos
cat >seed/etc/nixos/configuration.nix <<END
{ config, pkgs, ... }:
{
  boot.loader.grub.enable = true;
  boot.loader.grub.version = 2;
  boot.loader.grub.device = "/dev/dummy";

  fileSystems."/" =
    { device = "/dev/dummy";
      fsType = "ext4";
    };
}
END
nixos-install --no-bootloader --no-root-passwd --root $(realpath seed)
nixos-enter --root $(realpath seed) -- true
```

Then try to work in it:

```
nixos-enter --root $(realpath seed) -- nixos-rebuild dry-build
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.34, NixOS, 18.03.132021.c0c5571ec1a (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(paul): `""`
 - channels(root): `"nixos-18.03.132021.c0c5571ec1a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by pvgoran** [comment] 2018-11-16 05:34
@CMCDragonkai The seed is packed into a squashfs image which is transferred to the target system. Then a script is run which mounts the image, chroots into it, rsyncs the seed onto the target system's root, and finally chroots the second time into the root to run `nixos-rebuild boot`.

**Comment by chkno** [comment] 2020-02-22 02:00
For concreteness: A fix for this problem would cause [this test](https://github.com/chkno/nixpkgs/commit/231467aeae52e72e34a0740b1e8856750778804d) to pass, or at least fail for a different reason.  Currently this test fails with this output:

```
$ nix-build nixos/tests/installer.nix -A simple
...
Can build things in the installed environment
machine: must succeed: nixos-enter -- nix-build ...
machine # setting up /etc...
machine # error: getting status of '/tmp': No such file or directory
machine: output:
error: command `nixos-enter -- nix-build ... failed (exit code 1)
```

[Adding `mkdir --mode 1777 /mnt/tmp` allows the test to continue](https://github.com/chkno/nixpkgs/commit/d0bfdae9a31dcf97f866450b185d8d66b9c40bc7).

---

It looks like `/tmp` is normally created by the `systemd-tmpfiles-setup` systemd service which runs at boot.  Starting up systemd seems out-of-scope for `nixos-enter`.  [Perhaps it should just run `systemd-tmpfiles --create --remove --exclude-prefix=/dev`](https://github.com/NixOS/nixpkgs/pull/80769) like `switch-to-configuration.pl` does.

**Comment by pvgoran** [comment] 2020-08-20 03:07
This issue is still relevant.

**Comment by Mikilio** [comment] 2022-11-03 04:50
This issue should be reopened as it is the root cause of other problems like #73404. The line added with the fix (#80769) of this issue seems to fail on many uses of [nixos-install.sh](https://github.com/NixOS/nixpkgs/blob/46ec9351bbda7758d7c75392a5c7cdf812ebd3a7/nixos/modules/installer/tools/nixos-install.sh#L198) which calls nixos-enter.sh when attempting to install the bootloader. The error given is not being able to find the command 'systemd-tmpfiles' when using chroot at this stage. Does anyone know why 'systemd-tmpfiles' was supposed to be in PATH here in the first place? I can not understand how this fix used to work before.

**Comment by nh2** [comment] 2022-11-03 12:14
Reopening based on reports above.

**Comment by Mikilio** [comment] 2022-11-03 22:36
Regarding my previous comment, I have confirmed that systemd-tmpfiles is indeed not in the PATH and one should not assume that it would be there. That is because the dependency of nixos-enter on systemd hasn't been declared in [`tools.nix`](https://github.com/Mikilio/nixpkgs/blob/e0b861b3275ded7f7ae91386c2b39787478b56ec/nixos/modules/installer/tools/tools.nix#L64-L68) where it should be. The fix should be easy, so I will submit a pull request.

**Comment by ncfavier** [comment] 2023-01-01 11:05
Fixed by https://github.com/NixOS/nixpkgs/pull/199425

**Closed by ncfavier** 2023-01-01 11:05 UTC
