### ISSUE TITLE
tdesktop (telegram-desktop) fails to build

### ISSUE THREAD

**Issue by siraben** [NixOS/nixpkgs#94988] opened 2020-08-09 06:30 UTC
**Describe the bug**
Telegram desktop fails to build.

**To Reproduce**
1. On the updated unstable channel, run `nix-env -iA nixos.tdesktop`.

**Expected behavior**
`tedesktop` should build.

**Notify maintainers**
@primeos @abbradar

**Comment by primeos** [comment] 2020-08-09 09:59
Duplicate of #94905 and already fixed in https://github.com/NixOS/nixpkgs/commit/e7987936c1b28b0de3d774731bc26cde47c24c44.

**Closed by primeos** 2020-08-09 09:59 UTC
Labels: 0.kind: bug
