### ISSUE TITLE
ungoogle-chromium's sandbox fails to build

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#123995] opened 2021-05-22 08:42 UTC
**Describe the bug**

For `ungoogled-chromium` attribute, the build fails: https://hydra.nixos.org/build/143434434 . The log is here: https://nix-cache.s3.amazonaws.com/log/c3i89xjqcr2a6570lhw6lbywnsn1zvw1-chromium-unwrapped-90.0.4430.212.drv

**To Reproduce**

`nix-build -A ungoogled-chromium` on [current](https://github.com/NixOS/nixpkgs/commit/d42cd445dde587e9a993cd9434cb43da07c4c5de) `nixos-unstable` branch.

**Expected behavior**

Build doesn't fail.

**Additional context**

Regular chromium doesn't fail to build

**Notify maintainers**

@primeos @squalus 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
attribute: ungoogled-chromium
```

**Comment by primeos** [comment] 2021-05-22 09:41
Is that build failure reproducible? Previous `ungoogled-chromium-90.0.4430.212` builds where fine so this isn't due to an `ungoogled-chromium` change/update and `stdenv-linux/setup: line 1325: 45938 Killed                  ninja -C "out/Release" -j$NIX_BUILD_CORES -l$NIX_BUILD_CORES "chrome"` sounds to me like the build process was simply killed by the OS (maybe `wendy` went OOM?).

**Comment by primeos** [comment] 2021-05-23 10:15
The next `nixpkgs:trunk` build succeeded again: https://hydra.nixos.org/build/143687975

https://hydra.nixos.org/job/nixpkgs/trunk/ungoogled-chromium.x86_64-linux:
![image](https://user-images.githubusercontent.com/7537109/119256313-6ce51700-bbc0-11eb-9c68-e231af596f98.png)

So I guess we can close this.

**Closed by primeos** 2021-05-23 10:15 UTC
Labels: 0.kind: bug
