### ISSUE TITLE
master: python-rlp build failure

### ISSUE THREAD

**Issue by deepfire** [NixOS/nixpkgs#44373] opened 2018-08-02 17:28 UTC
```
building '/nix/store/259lk8n561lxni9j6vpiwpcxlhiifdv9-python3.6-rlp-1.0.1.drv'...
builder for '/nix/store/259lk8n561lxni9j6vpiwpcxlhiifdv9-python3.6-rlp-1.0.1.drv' failed with exit code 1; last 10 log lines:
      replace_conflicting=replace_conflicting
    File "/nix/store/pyvd05namlbgacai4vr5xcpy5wlhhcb2-python3.6-bootstrapped-pip-18.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1056, in best_match
      return self.obtain(req, installer)
    File "/nix/store/pyvd05namlbgacai4vr5xcpy5wlhhcb2-python3.6-bootstrapped-pip-18.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1068, in obtain
      return installer(requirement)
    File "/nix/store/pyvd05namlbgacai4vr5xcpy5wlhhcb2-python3.6-bootstrapped-pip-18.0/lib/python3.6/site-packages/setuptools/dist.py", line 581, in fetch_build_egg
      return cmd.easy_install(req)
    File "/nix/store/pyvd05namlbgacai4vr5xcpy5wlhhcb2-python3.6-bootstrapped-pip-18.0/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 670, in easy_install
      raise DistutilsError(msg)
  distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools-markdown')
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.11, NixOS, 18.09.git.17ee0a8 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-17.03.899.c87abfae79"`
 - nixpkgs: `/home/deepfire/nixpkgs`

**Comment by xeji** [comment] 2018-08-02 20:12
`rlp` was bumped from 0.6.0 -> 1.0.1 in 3a2734bbad18fca62cec80f1538d91cca2ce935e as part of #43972.
This bump had been tried and reverted before: 367a7ae138b55193d4ddea60940d01f2b10a5cb0
Should we revert again? 
@FRidh @Profpatsch

**Comment by dotlambda** [comment] 2018-08-02 23:10
Duplicate of #44224.
No, we shouldn't revert again but package the new dependencies. The bump would happen again during the next batch upgrade.

**Closed by dotlambda** 2018-08-02 23:10 UTC
Labels: 6.topic: python
