### ISSUE TITLE
zoom-us segfaults at startup

### ISSUE THREAD

**Issue by meditans** [NixOS/nixpkgs#60784] opened 2019-05-02 17:50 UTC
## Issue description
`zoom-us` segfaults at startup, in NixOS. I'd like to undertstand how I could debug this further.

### Steps to reproduce
Add the `zoom-us` package in your `/etc/nixos/configuration.nix` and:

```
$ zoom-us                                           
zoom started.
[1]    16172 segmentation fault  zoom-us
```

## Technical details

Output of `nix-shell -p nix-info --run "nix-info -m"`:

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.30, NixOS, 19.09pre177651.aeb464dfd37 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(carlo): `""`
 - channels(root): `"nixos-19.09pre177651.aeb464dfd37"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by meditans** [comment] 2019-05-02 17:50
pinging @flokli to continue the discussion ^

**Comment by matthewbauer** [comment] 2019-05-02 17:56
It's useful to get the version of zoom-us you are using. You can get the drv like this:

```
$ nix-store -qd $(command -v zoom-us)
/nix/store/f4fixp5ylql7fff0w7nyyr2wnqdl75rf-zoom-us-2.7.162522.0121.drv
```

Also uploading the core file is always helpful (```core.*```).

**Comment by meditans** [comment] 2019-05-02 18:00
@matthewbauer thanks, here's the version of zoom-us:

```
$ nix-store -qd $(command -v zoom-us)
/nix/store/dnjl9vhal6sxi09l3464angvcjhw0a0i-zoom-us-2.8.183302.0415.drv
```

But I wouldn't know what the core file is or how to get it!

**Comment by meditans** [comment] 2019-05-02 18:59
Here's an useful trace, thanks to @matthewbauer:

```
$ (cd $(dirname $(readlink -f $(command -v zoom-us)))/.. && nix run nixpkgs.gdb -c gdb ./share/zoom-us/zoom)
GNU gdb (GDB) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./share/zoom-us/zoom...
warning: Loadable section ".dynstr" outside of ELF segments
(no debugging symbols found)...done.
(gdb) run
Starting program: /nix/store/hbjs5m97ppp2ddsqfz6lx28r2glcm7bv-zoom-us-2.8.183302.0415/share/zoom-us/zoom 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27/lib/libthread_db.so.1".
warning: File "/nix/store/k4v41as11lyg5rbm80vdxwmbqnbc3a3r-gcc-7.4.0-lib/lib/libstdc++.so.6.0.24-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /nix/store/k4v41as11lyg5rbm80vdxwmbqnbc3a3r-gcc-7.4.0-lib/lib/libstdc++.so.6.0.24-gdb.py
line to your configuration file "/home/carlo/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/carlo/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
[Detaching after fork from child process 30483]
zoom started.
[New Thread 0x7fffdf9f3700 (LWP 30484)]

Thread 1 "zoom" received signal SIGSEGV, Segmentation fault.
0x00007fffe0f0e4d8 in ?? ()
   from /nix/store/jj2wmjrm1jq2kqyrc2qwmp3zpflmx5x0-qtbase-5.9.3-bin/lib/qt-5.9/plugins/platforms/../../../../../3f7m3k4f12a9bacacgzjq3szsfrpi2zl-qtbase-5.9.3/lib/libQt5XcbQpa.so.5

```

So it seems that the problem is correlated with the `libQt5` library

**Comment by flokli** [comment] 2019-05-02 19:39
This might be yet another invocation of https://github.com/NixOS/nixpkgs/issues/37864.

Could you try the workarounds described in https://github.com/NixOS/nixpkgs/issues/38139?

**Comment by meditans** [comment] 2019-05-02 20:29
This is a test meant to check whether my environment variables were the problem here:

```
nix run --ignore-environment -k DISPLAY -k XDG_RUNTIME_DIR -k XAUTHORITY -k LD_LIBRARY_PATH -f channel:nixpkgs-unstable zoom-us -c zoom-us
```
the `--ignore-environment` tells nix to ignore all my environment variables, while keeping only the one designated with the `-k` option, the `-f` flag specifies the channel, and `-c` the command that we invoke (the `-c` flag can be chained).

This command worked for me, so actually the problem was something in my environment variables.
I'll see if the problem is the same you mentioned in your comment, @flokli, but I don't think I'll try the suggested workaround (removing my ~/.nix-profile and ~/.nix-defexpr folder) because the above command a better solution.

Thanks for the help @matthewbauer and @flokli

**Comment by flokli** [comment] 2019-05-03 08:26
Ok, closing then.

**Comment by matthewbauer** [comment] 2019-05-03 17:54
Let's keep it open. I still want to track down what is causing this.

**Comment by jtojnar** [comment] 2019-05-03 18:25
You can try `env QT_PLUGIN_PATH= result/bin/zoom-us` to see if it is the same issue.

**Comment by zarybnicky** [comment] 2019-06-10 14:18
I'm trying with the latest unstable after the previous version from 18.09 stopped working (due to zoom's server changes), and I'm running into the same problem with a segfault.

Trying the 'nix run' command it takes forever to go through the fixupPhase (100% CPU utilzation), but Zoom works this way. I'm wondering if this would work if I updated my whole system to 19.03...

Running with only a PATH, XAUTHORITY, DISPLAY, and XDG_RUNTIME_DIR (`env -i PATH=... zoom-us`) fails with the same segfault.

I'm trying to use strace, but I suspect that strace somehow doesn't track children for this process, as the last few thousand syscalls are getpid...

**Comment by danbst** [comment] 2019-12-16 04:56
I think this Qt version mismatch bug should no longer happen because of new Qt infra.

**Closed by danbst** 2019-12-16 04:56 UTC

**Comment by danbst** [comment] 2019-12-16 05:08
Uhm, I think it was really too fast to close this issue. The problem is still there. But anyway, let's consider this to be a duplicate of https://github.com/NixOS/nixpkgs/issues/74273
