### ISSUE TITLE
Build failure: Calibre

### ISSUE THREAD

**Issue by RekitRalph** [NixOS/nixpkgs#350126] opened 2024-10-21 02:04 UTC
### Steps To Reproduce

1. build  calibre from unstable pkgs.

### Build log

```
building the system configuration...
error: builder for '/nix/store/pnbs60kxzjql345dg97ckvk8wjcb16sq-calibre-7.16.0.drv' failed with exit code 139;
       last 10 log lines:
       > Test socket activation ... ok [0.0 s]
       > test_ssl (calibre.srv.tests.loop.LoopTest.test_ssl)
       > Test serving over SSL ... ok [0.2 s]
       > test_workers (calibre.srv.tests.loop.LoopTest.test_workers)
       > Test worker semantics ... ok [0.2 s]
       > test_websocket_perf (calibre.srv.tests.web_sockets.WebSocketTest.test_websocket_perf) ... ok [0.5 s]
       > Fontconfig error: Cannot load default config file: No such file: (null)
       > test_char_count (calibre.srv.tests.content.ContentTest.test_char_count) ... ok [0.1 s]
       > test_get (calibre.srv.tests.content.ContentTest.test_get)
       > Test /get ... /nix/store/ncv68hjnidcd2bm5abkhklrijhn0cgn6-stdenv-linux/setup: line 1721: 20766 Segmentation fault      (core dumped) python setup.py test ${EXCLUDED_FLAGS[@]}
       For full logs, run 'nix log /nix/store/pnbs60kxzjql345dg97ckvk8wjcb16sq-calibre-7.16.0.drv'.
error: 1 dependencies of derivation '/nix/store/kcgiq5wlk4dlzyp8vahmcbb8ws85bmz4-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6kk96nv37vbgziqr8knighzvgw5l44hn-nixos-system-nixos-24.11.20241018.4c2fcb0.drv' failed to build
```
Full log: https://gist.github.com/RekitRalph/d8498f7d0666a8f17ffc5b8843d08019

### Additional context

Usings flakes unstable packages. I just did a flake update and calibre fails to build.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.2-xanmod1, NixOS, 24.11 (Vicuna), 24.11.20241009.5633bcf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment] 2024-10-21 02:20
Duplicate of https://github.com/NixOS/nixpkgs/issues/349755

Fixed by https://github.com/NixOS/nixpkgs/pull/349884

**Closed** 2024-10-21 02:20 UTC
Labels: 2.status: duplicate, 0.kind: build failure
