### ISSUE TITLE
`dockerTools.mergeImages` fails during `cp -R --no-clobber inputs/*/* image/`

### ISSUE THREAD

**Issue by MaxDaten** [NixOS/nixpkgs#248616] opened 2023-08-12 01:44 UTC
### Describe the bug

Relevant snippet

```nix
allImages = pkgs.dockerTools.mergeImages [pkgs.dockerTools.examples.bash pkgs.dockerTools.examples.editors];
```

while building it fails with

```console
merge-docker-images> cp: not replacing 'image/manifest.json'
merge-docker-images> cp: not replacing 'image/repositories'
```

I copied over the `mergeImages` for debugging, this is the full output:

```console
merge-docker-images> ++ cp --version
merge-docker-images> cp (GNU coreutils) 9.3
merge-docker-images> Packaged by https://nixos.org
merge-docker-images> Copyright (C) 2023 Free Software Foundation, Inc.
merge-docker-images> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
merge-docker-images> This is free software: you are free to change and redistribute it.
merge-docker-images> There is NO WARRANTY, to the extent permitted by law.
merge-docker-images> Written by Torbjorn Granlund, David MacKenzie, and Jim Meyering.
merge-docker-images> ++ cp -R --no-clobber inputs/akjqhxwizhq4lsayp6d84jhizhb0d2f5-docker-image-editors.tar.gz/384aa297696e62821c05f5f17971159261bdfee72165798dded1c5a60c560b6e.json inputs/akjqhxwizhq4lsayp6d84jhizhb0d2f5-docker-image-editors.tar.gz/b6ec94e71300b779d937b6f5cacf60812de422f93a9f39e1a26367a5d415d0d9 inputs/akjqhxwizhq4lsayp6d84jhizhb0d2f5-docker-image-editors.tar.gz/manifest.json inputs/akjqhxwizhq4lsayp6d84jhizhb0d2f5-docker-image-editors.tar.gz/repositories inputs/jqph7v8indv6gxbzxg9kgr2zwks7chf2-docker-image-bash.tar.gz/62558baac1ad9937e169eaf1749967ff0eef434c6e8f5e93100b6ead11d1ab70.json inputs/jqph7v8indv6gxbzxg9kgr2zwks7chf2-docker-image-bash.tar.gz/cd0ccc67279db10259d3aaceded3d8b77774f52bf3efa06f2a2cb958608ef8ce inputs/jqph7v8indv6gxbzxg9kgr2zwks7chf2-docker-image-bash.tar.gz/manifest.json inputs/jqph7v8indv6gxbzxg9kgr2zwks7chf2-docker-image-bash.tar.gz/repositories image/
merge-docker-images> cp: not replacing 'image/manifest.json'
merge-docker-images> cp: not replacing 'image/repositories'
``` 

### Steps To Reproduce
1. Add snippet as flake default output 
2. `nix build .#packages.aarch64-linux.default -L -v`

> I can provide a minimal example flake tomorrow, if necessary

### Expected behavior

Build should succeed and images should be loadable via `docker load < result`

### Additional context

Patching the `cp` as follows:

```bash
cp -R --no-clobber inputs/*/* image/ || true
``` 

fixes the problem, but would probably hide other cp errors.

Maybe the behavior of coreutils/cp changed in the recent versions. At least the current manual states it will fail silently.
https://www.gnu.org/software/coreutils/manual/coreutils.html#index-_002dn-11

### Notify maintainers

@roberth @utdemir @considerate 

### Metadata

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.6.0, macOS 13.5`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(jloos): `"home-manager-22.05.tar.gz"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
 ```

I'm using a linux-builder on my machine.

**Comment by considerate** [comment] 2023-08-12 13:39
@MaxDaten Thank you for reporting this. I’ll try to replicate this locally.

The lines
```
merge-docker-images> cp: not replacing 'image/manifest.json'
merge-docker-images> cp: not replacing 'image/repositories'
```

do not look like errors to me. It looks like `cp` is informing that those files already exist in the output and thus are skipped (—no-clobber). However, if the build is failing there’s something going wrong.

**Comment by considerate** [comment] 2023-08-12 15:25
Thank you for linking the manual. It looks like `cp` will exit with a non-zero status code in case of files that are already present now.

The coreutils changelog states that `--update=none` now reproduces the behavior `--no-clobber` had at the time I wrote the mergeImages script.

https://github.com/coreutils/coreutils/blob/f31229ebd1b339b85d54c24e3b79a8262b3202d2/NEWS#L148-L150

I was able to build `dockerTools.examples.mergedBashAndRedis` by changing `--no-clobber` to `--update=none`.

I don't know how to best go about obtaining the `--update=none` behavior everywhere, should the flag be dependent on the version of `stdenv.coreutils` somehow? Maybe we can just assume that `cp` in `runCommand` will be a new version from now so that we can use `--update=none` everywhere?

Given that all files that are present in both docker images apart from the manifest.json and repositories files should be content addressed the only issue with removing `--no-clobber` is that time is spent unnecessarily writing content that's already present, so removing the `--no-clobber` flag altogether might make sense.

**Comment by MaxDaten** [comment] 2023-08-12 19:51
Thanks for investigating!

> I don't know how to best go about obtaining the `--update=none` behavior everywhere, should the flag be dependent on the version of `stdenv.coreutils` somehow? Maybe we can just assume that `cp` in `runCommand` will be a new version from now so that we can use `--update=none` everywhere?

I'm not familiar with the backward compatibility policy of the nix ecosystem, but I would assume that the most recent version of `mergeImage` can assume most recent coreutils. Might happen that someone is overlaying old coreutils but then you might just need to overlay the old `mergeImages` too, if you can pinpoint it down to coreutils cp.

**Comment by roberth** [comment] 2023-08-16 13:16
> Might happen that someone is overlaying old coreutils

True, but then apparently they have a legacy software problem, in which case they should use overrides only where it is necessary, instead of a blanket override in an overlay. It is not realistic to expect all of Nixpkgs to work with arbitrary changes.
The cost of such compat logic isn't worth it; certainly not in this case, until proven otherwise. If they contribute a full time maintainer it is worth it, and if they have a legacy software problem they probably can.

**Closed** 2023-08-19 15:58 UTC
Labels: 0.kind: bug, 6. topic: docker tools
