### ISSUE TITLE
scribusUnstable: PDF import fails

### ISSUE THREAD

**Issue by liamdiprose** [NixOS/nixpkgs#71154] opened 2019-10-15 00:55 UTC
**Describe the bug**
Scribus allows PDF's to be imported into image frames, but running inside `nix-shell --pure` leads to no PDF appearing.

**To Reproduce**
1. `nix-shell --pure -p scribusUnstable`
2. `scribus`
3. Create a new 'Single Page'
4. Create an image frame (Next to 'T' on top toolbar, `i` on the keyboard)
5. Double click the empty Image frame
6. Select any PDF
7. Image frame remains blank

**Expected behavior**
The top left portion of the imported PDF should appear in Image frame.

**Workaround**
- Copying the PATH variable from an impure scribusUnstable shell on Ubuntu to the pure shell fixes the problem. 

**Metadata**

```yaml
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-62-generic, Ubuntu, 18.04.3 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(liam): `"nixpkgs-20.03pre196811.7818f30cc4b"`
 - nixpkgs: `/home/liam/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: scribusUnstable
# a list of nixos modules affected by the problem
module:
```

**Comment by turion** [comment] 2021-03-17 18:50
Can you launch Scribus from the command line and see whether any errors pop up there?

This might be https://bugs.ghostscript.com/show_bug.cgi?id=703706.

**Comment by turion** [comment] 2021-03-17 18:52
Also, which exact scribus version is that?

**Comment by liamdiprose** [comment] 2021-03-17 23:11
I've since moved to NixOS fully, with a flake-based setup.

My nixpkgs is pinned at `github:nixos/nixpkgs/29a15e2c1f5ad64c235d78ba5e29a56fe520ad45`

scribusUnstable refers to Scribus 1.5.1

I'm still able to recreate the bug I described, and no mention of ghostscript or any PDF errors on the command line. 

If I run scribus with ghostscript included in the shell, the bug goes away.

scribus (the package, refering to Scribus 1.4.8), works as expected.

**Comment by liamdiprose** [comment] 2021-03-17 23:18
I think its clear what scribusUnstable is missing:

https://github.com/NixOS/nixpkgs/blob/0408ccf4ffe0eb4c56b2086ed6bec72589cabb5f/pkgs/applications/office/scribus/default.nix#L32-L36

**Comment by turion** [comment] 2021-03-18 11:29
I can reproduce with `nix-shell --pure -p scribusUnstable ghostscript` in scribus 1.5.6.

What's strange is that I can _import_ PDFs in scribus 1.5.6, I was assuming this calls ghostscript as well?

**Comment by turion** [comment] 2021-03-18 12:31
> I think its clear what scribusUnstable is missing:
> 
> https://github.com/NixOS/nixpkgs/blob/0408ccf4ffe0eb4c56b2086ed6bec72589cabb5f/pkgs/applications/office/scribus/default.nix#L32-L36

You're right. Adding that `postPatch` fixes it. I'll send a MR.

**Comment by erictapen** [comment] 2021-04-26 01:19
I can't reproduce this with scribus 1.5.7 anymore. So this might be fixed with https://github.com/NixOS/nixpkgs/pull/120683?
Feel free to reopen if it's not the case.

**Closed by erictapen** 2021-04-26 01:19 UTC
Labels: 0.kind: bug
