### ISSUE TITLE
JetBrains JDK does not support JCEF

### ISSUE THREAD

**Issue by niknetniko** [NixOS/nixpkgs#160468] opened 2022-02-17 13:29 UTC
### Describe the bug
The JetBrains JDK seems to be built without JCEF support.

### Steps To Reproduce
1. Run something (e.g. Intellij) with the JetBrains JDK
2. Expect JCEF to work.
3. It doesn't.

### Expected behavior
JCEF should be supported.

### Additional context
This is probably the cause of #143122, #109347 and #150579.

### Notify maintainers

@edwtjo @petabyteboy

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.7, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0`
 - channels(niko): `""`
 - channels(root): `"android, nix-ld, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by pschyska** [comment] 2022-02-18 15:10
I tried to build JBR with JCEF multiple times, but got stuck providing the JCEF binaries in the required format. There doesn't seem to be any documentation on how to get them, and jetbrains gets them from somewhere within their infra IIRC. I wasn't able to reproduce them with their JCEF fork repo.
For the time being, I'm using a patched binary from them:

```nix
{ self, sources, ... }:
let inherit (self) lib;
in { stdenv, zlib, xorg, freetype, alsa-lib, atk, at-spi2-atk, at-spi2-core, cups, dbus
, expat, fontconfig, glib, libdrm, libxkbcommon, mesa, nspr, nss, libglvnd, libudev
, setJavaClassPath }:
let
  result = stdenv.mkDerivation {
    pname = "p-jetbrains-jdk-bin";
    inherit (sources.p-jetbrains-jdk-bin) version src;

    dontStrip = true; # See: https://github.com/NixOS/patchelf/issues/10
    postFixup = ''
      rpath="$out/lib/jli:$out/lib/server:$out/lib:${
        lib.makeLibraryPath [
          zlib
          xorg.libX11
          xorg.libXext
          xorg.libXtst
          xorg.libXi
          xorg.libXrender
          freetype
          alsa-lib

          atk
          at-spi2-atk
          at-spi2-core
          cups
          dbus
          expat
          fontconfig
          glib
          libdrm
          libxkbcommon
          mesa
          nspr
          nss
          stdenv.cc.cc.lib
          xorg.libxcb
          xorg.libXcomposite
          xorg.libXcursor
          xorg.libXdamage
          xorg.libXfixes
          xorg.libXrandr
          xorg.libxshmfence
          xorg.libXxf86vm
          # runtime?
          libglvnd
          libudev
          mesa.drivers
        ]
      }"

      for f in $(find $out -name "*.so") $(find $out -type f -perm -0100); do
        patchelf --interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" "$f" || true
        patchelf --set-rpath   "$rpath"                                    "$f" || true
      done

      for f in $(find $out -name "*.so") $(find $out -type f -perm -0100); do
        if ldd "$f" | fgrep 'not found'; then echo "in file $f"; fi
      done
    '';

    installPhase = ''
      mv ../$sourceRoot $out

      mkdir -p $out/nix-support
      printWords ${setJavaClassPath} > $out/nix-support/propagated-build-inputs

      # Set JAVA_HOME automatically.
      cat <<EOF >> $out/nix-support/setup-hook
      if [ -z "\''${JAVA_HOME-}" ]; then export JAVA_HOME=$out; fi
      EOF
    '';

    passthru.jre = result;
    passthru.home = result;
    meta = with lib; { platforms = [ "x86_64-linux" ]; };
  };
in result

```

where sources is

```nix
{
  sources = {
    p-jetbrains-jdk-bin = {
      pname = "p-jetbrains-jdk-bin";
      version = "17_0_2-linux-x64-b315.1";
      src = fetchurl {
        url = "https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-17_0_2-linux-x64-b315.1.tar.gz";
        sha256 = "sha256-ImnQgErO3f7lNVHSSCKaPAD3RMsK2jmdA6VWX2WI2qA=";
      };
    };
  };
}
```
This is using jbr 17.0.2 though. You can check for releases of it at https://github.com/JetBrains/JetBrainsRuntime/releases. It should be easy to adapt this to jbr 11.x.

With the following overlay:
```nix
final: prev: {
  jetbrains = prev.jetbrains // { jdk = final.p-jetbrains-jdk-bin; };
}
```

You can use it with jetbrains editors (I'm only using idea-ultimate, YMMV with other products).

Note that JetBrains wasn't prepared for the "suprising" deprecation of illegal reflection access in Java 17, which requires untold amounts of --add-opens. For idea-ultimate I collected so far:

```shell
    --add-opens=java.base/java.lang=ALL-UNNAMED
    --add-opens=java.base/java.text=ALL-UNNAMED
    --add-opens=java.base/java.util=ALL-UNNAMED
    --add-opens=java.base/jdk.internal.vm=ALL-UNNAMED
    --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
    --add-opens=java.desktop/com.apple.eawt=ALL-UNNAMED
    --add-opens=java.desktop/com.apple.eawt.event=ALL-UNNAMED
    --add-opens=java.desktop/com.apple.laf=ALL-UNNAMED
    --add-opens=java.desktop/java.awt=ALL-UNNAMED
    --add-opens=java.desktop/java.awt.event=ALL-UNNAMED
    --add-opens=java.desktop/java.awt.peer=ALL-UNNAMED
    --add-opens=java.desktop/javax.swing=ALL-UNNAMED
    --add-opens=java.desktop/javax.swing.plaf.basic=ALL-UNNAMED
    --add-opens=java.desktop/javax.swing.text.html=ALL-UNNAMED
    --add-opens=java.desktop/sun.awt=ALL-UNNAMED
    --add-opens=java.desktop/sun.awt.datatransfer=ALL-UNNAMED
    --add-opens=java.desktop/sun.awt.image=ALL-UNNAMED
    --add-opens=java.desktop/sun.awt.windows=ALL-UNNAMED
    --add-opens=java.desktop/sun.awt.X11=ALL-UNNAMED
    --add-opens=java.desktop/sun.font=ALL-UNNAMED
    --add-opens=java.desktop/sun.java2d=ALL-UNNAMED
    --add-opens=java.desktop/sun.swing=ALL-UNNAMED
    --add-opens=jdk.attach/sun.tools.attach=ALL-UNNAMED
    --add-opens=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED
    --add-opens=jdk.jdi/com.sun.tools.jdi=ALL-UNNAMED
    --add-opens=jdk.jdi/com.sun.tools.jdi=ALL-UNNAMED'
```
Not sure if all are still necessary, and if some are missing which I didn't notice because I never used a particular feature. Good luck 🙂

**Comment by niknetniko** [comment] 2022-02-21 11:56
@pschyska Thanks for this! I have adjusted it to use JDK 11 for now, and it works wonderfully, aside from my cursor theme being ignored (but hey, markdown preview and better js debugger are very nice).

Perhaps we can consider going back to using the binary instead of building from source in nixpkgs? I know source builds are preferred, but the JCEF support is a big reason one would use the JetBrains JDK over the normal JDK.

**Comment by pschyska** [comment] 2022-02-21 14:11
@niknetniko I remember hitting the cursor theme bug, when I was using a HiDPI config that scaled the cursor (I'm not anymore). It might be #50344, and I don't think I found a fix in the build (a user in that ticket worked around the issue with a fhs env for idea).

**Comment by VergeDX** [comment] 2022-04-18 05:43
https://github.com/JetBrains/JetBrainsRuntime/issues/86

**Comment by VergeDX** [comment] 2022-04-18 11:45
It seems we should build `cef` (https://bitbucket.org/chromiumembedded/cef/wiki/MasterBuildQuickStart) first.
Then build `java-cef`, the JetBrains fork (https://github.com/JetBrains/jcef/blob/8be3c18cfeab739f6b7fca53ea19ccfa87047d63/cmake/DownloadCEF.cmake).
Last, we opt-in JCEF in JetBrains JDK build process, and got the JB JDK with JCEF, which can rendered Markdown doc.

Given the complexity of the process, I recommend make a new pkgs `jetbrains-jdk-bin`,
or only use JB JDK with JCEF binary in JetBrains products only, it seems JB IDE contains FHS Env already.

**Comment by VergeDX** [comment] 2022-04-18 14:27
That's works fine for me, I tested on: `IDEA Ultimate 2022.1` + jbr `11_0_14_1-b2043.25`.

**Comment by pschyska** [comment] 2022-04-18 19:55
@VergeDX I tried twice to build CEF+JCEF, but got frustrated and setteled on patching the binary as I described above. 

Here is the latest stuff from my dead code archive (very rough, did get a derivation but it crashed at runtime IIRC). openjfx business is maybe not necessary anymore, as openjfx17 is available in nixpkgs meanwhile. Also the jdk build is the nixpkgs openjdk build with jetbrains additions, which didn't exist in version 17 back then. Maybe it would be better to rebase all of this on current openjdk17 again.
Take a stab if you like, I'm pretty sure I won't 🙂 

Cheers

# CEF

Didn't even attempt to build it, as it looked like it would be way beyond my time budget for these things - basically like building chrome I guess, and maybe lots can be reused from nixpkgs' chromium ¯\\_(ツ)_/¯. So here is an attempt at patching the binary.

```nix
with import <nixpkgs> { };
with pkgs;
let cefVersion = "88.2.6+gd717f0e+chromium-88.0.4324.150";
in stdenv.mkDerivation {
  name = "cef-bin-${cefVersion}";
  src = fetchurl {
    name = "cef_binary_${cefVersion}_linux64.tar.bz2";
    url = "https://cef-builds.spotifycdn.com/cef_binary_${
        lib.replaceStrings [ "+" ] [ "%2B" ] cefVersion
      }_linux64.tar.bz2";
    hash = "sha256-WvjwaywouKZG5JH5Qr7s9YXPZVg0xVyGsiQUmz/D9Qg=";
  };
  nativeBuildInputs = [ autoPatchelfHook ];
  buildInputs = [
    glib
    nss
    nspr
    at-spi2-core
    at-spi2-atk
    expat
    libdrm
    alsa-lib
    libxkbcommon
    libva
    cups
    mesa
    dbus
    atk
    libudev
  ] ++ (with xlibs; [
    libxcb
    libX11
    libXau
    libXdamage
    libXcomposite
    libXfixes
    libXrandr
    libXext
  ]);
  dontBuild = true;
  installPhase = ''
    mkdir -p $out
    cp -r . $out
  '';
}
```

# JCEF

```nix
with import <nixpkgs/nixos> { };
with pkgs;
let
  cefVersion = "88.2.6+gd717f0e+chromium-88.0.4324.150";
  cefBin = (import ./cef.nix);
in stdenv.mkDerivation rec {

  name = "java-cef-${version}";
  version = "88.2.6.282+g62432af";
  src = fetchgit {
    rev = "62432af095e85bae5fa73eaab7b0efe62197fc6a";
    url = "https://github.com/JetBrains/jcef.git";
    leaveDotGit = true;
    sha256 = "sha256-WemnIj0vlH2MwJoBYE3qQtf5z/IhXmWw1kJYjsTjNeI=";
  };
  patches = [ ./clang_format.patch ];

  nativeBuildInputs = [ git cmake clang-tools makeWrapper autoPatchelfHook ];
  buildInputs = [ python jdk11 xlibs.libX11 libudev ];
  cmakeFlags = [ "-DCMAKE_BUILD_TYPE=Release" ];
  dontUseCmakeBuildDir = true;
  cmakeDir = "..";
  postUnpack = ''
    ln -sf "${cefBin}" $sourceRoot/third_party/cef/cef_binary_88.2.6+gd717f0e+chromium-88.0.4324.150_linux64
  '';
  postPatch = ''
    patchShebangs .
  '';
  preConfigure = ''
    mkdir -p jcef_build
    cd jcef_build
  '';
  postBuild = ''
    PATH=''${PATH:+"$PATH:"}${lib.makeBinPath [ rsync ]}
    ../tools/compile.sh linux64
    ../tools/make_distrib.sh linux64
  '';
  installPhase = ''
    mkdir -p $out
    cp -a ../binary_distrib/linux64/* $out
    wrapProgram $out/run.sh \
      --set PATH "${lib.makeBinPath [ jdk11 coreutils ]}"
  '';
}
```
## clang-format.patch
```clang-format.patch
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -254,26 +254,26 @@ file(COPY "${CEF_ROOT}/README.txt" DESTI
-if(OS_WINDOWS)
-  set(GS_PLATFORM "win32")
-  set(GS_HASHPATH "win/clang-format.exe.sha1")
-elseif(OS_MACOSX)
-  set(GS_PLATFORM "darwin")
-  set(GS_HASHPATH "mac/clang-format.sha1")
-elseif(OS_LINUX)
-  set(GS_PLATFORM "linux*")
-  set(GS_HASHPATH "linux64/clang-format.sha1")
-endif()
-
-message(STATUS "Downloading clang-format from Google Storage...")
-execute_process(
-  COMMAND "${PYTHON_EXECUTABLE}"
-          "tools/buildtools/download_from_google_storage.py"
-          "--no_resume"
-          "--platform=${GS_PLATFORM}"
-          "--no_auth"
-          "--bucket" "chromium-clang-format"
-          "-s" "tools/buildtools/${GS_HASHPATH}"
-  WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
-  RESULT_VARIABLE EXECUTE_RV
-  )
-if(NOT EXECUTE_RV STREQUAL "0")
-  message(FATAL_ERROR "Execution failed with unexpected result: ${EXECUTE_RV}")
-endif()
+#if(OS_WINDOWS)
+#  set(GS_PLATFORM "win32")
+#  set(GS_HASHPATH "win/clang-format.exe.sha1")
+#elseif(OS_MACOSX)
+#  set(GS_PLATFORM "darwin")
+#  set(GS_HASHPATH "mac/clang-format.sha1")
+#elseif(OS_LINUX)
+#  set(GS_PLATFORM "linux*")
+#  set(GS_HASHPATH "linux64/clang-format.sha1")
+#endif()
+#
+#message(STATUS "Downloading clang-format from Google Storage...")
+#execute_process(
+#  COMMAND "${PYTHON_EXECUTABLE}"
+#          "tools/buildtools/download_from_google_storage.py"
+#          "--no_resume"
+#          "--platform=${GS_PLATFORM}"
+#          "--no_auth"
+#          "--bucket" "chromium-clang-format"
+#          "-s" "tools/buildtools/${GS_HASHPATH}"
+#  WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
+#  RESULT_VARIABLE EXECUTE_RV
+#  )
+#if(NOT EXECUTE_RV STREQUAL "0")
+#  message(FATAL_ERROR "Execution failed with unexpected result: ${EXECUTE_RV}")
+#endif()
```
# jbr (17) build using it
```nix
with import <nixpkgs/nixos> { };
with pkgs;

let
  major = "17";
  update = "";
  build = "+15";
  repover = "${major}${update}${build}";
  gradle_ = (gradleGen.override { java = openjdk16_headless; }).gradle_7;
  makePackage = args:
    ccacheStdenv.mkDerivation ({
      version = "${major}${update}${build}";

      src = fetchFromGitHub {
        owner = "openjdk";
        repo = "jfx";
        rev = repover;
        sha256 = "sha256-vsCCksmCwPA0vn0TVYh3NTOCt8LNOZdUuj5qDSOm6nk=";
      };

      buildInputs = [ gtk2 gtk3 xorg.libXtst xorg.libXxf86vm glib alsa-lib ffmpeg ];
      nativeBuildInputs = [ gradle_ perl pkg-config cmake gperf python3 ruby ];

      dontUseCmakeConfigure = true;

      config = writeText "gradle.properties" (''
        CONF = Release
        JDK_HOME = ${openjdk16_headless.home}
      '' + args.gradleProperties or "");

      #avoids errors about deprecation of GTypeDebugFlags, GTimeVal, etc.
      NIX_CFLAGS_COMPILE = [ "-DGLIB_DISABLE_DEPRECATION_WARNINGS" ];

      buildPhase = ''
        runHook preBuild

        export GRADLE_USER_HOME=$(mktemp -d)
        ln -s $config gradle.properties
        export NIX_CFLAGS_COMPILE="$(pkg-config --cflags glib-2.0) $NIX_CFLAGS_COMPILE"
        gradle --no-daemon $gradleFlags sdk

        runHook postBuild
      '';
    } // args);

  # Fake build to pre-download deps into fixed-output derivation.
  # We run nearly full build because I see no other way to download everything that's needed.
  # Anyone who knows a better way?
  deps = makePackage {
    pname = "openjfx-deps";

    # perl code mavenizes pathes (com.squareup.okio/okio/1.13.0/a9283170b7305c8d92d25aff02a6ab7e45d06cbe/okio-1.13.0.jar -> com/squareup/okio/okio/1.13.0/okio-1.13.0.jar)
    installPhase = ''
      find $GRADLE_USER_HOME -type f -regex '.*/modules.*\.\(jar\|pom\|zip\)' \
        | perl -pe 's#(.*/([^/]+)/([^/]+)/([^/]+)/[0-9a-f]{30,40}/([^/\s]+))$# ($x = $2) =~ tr|\.|/|; "install -Dm444 $1 \$out/$x/$3/$4/$5" #e' \
        | sh
      rm -rf $out/tmp
    '';

    outputHashAlgo = "sha256";
    outputHashMode = "recursive";
    # Downloaded AWT jars differ by platform.
    outputHash = {
      x86_64-linux = "sha256-hKFxXn1PBcwpso/I+SsdV4gsIbbLOLTa2vut5jfvJZM=";
      i686-linux = "0hx69p2z96p7jbyq4r20jykkb8gx6r8q2cj7m30pldlsw3650bqx";
    }.${stdenv.system} or (throw "Unsupported platform");

    gradleProperties = ''
      COMPILE_WEBKIT = true
    '';
  };

  openjfx = makePackage {
    pname = "openjfx-modular-sdk";

    gradleProperties = ''
      COMPILE_MEDIA = true
      COMPILE_WEBKIT = true
    '';

    preBuild = ''
      swtJar="$(find ${deps} -name org.eclipse.swt\*.jar)"
      icu4c="$(find ${deps} -name icu4c-\*-data-bin-l-\.zip)"
      substituteInPlace build.gradle \
        --replace 'icu name: "icu4c-''${icuVersion}-data-bin-l", ext: "zip"' "icu files('$icu4c')" \
        --replace 'mavenCentral()' 'mavenLocal(); maven { url uri("${deps}") }' \
        --replace 'name: SWT_FILE_NAME' "files('$swtJar')"
    '';

    installPhase = ''
      cp -r build/modular-sdk $out
    '';

    # glib-2.62 deprecations
    NIX_CFLAGS_COMPILE = "-DGLIB_DISABLE_DEPRECATION_WARNINGS";

    stripDebugList = [ "." ];

    postFixup = ''
      # Remove references to bootstrap.
      export openjdkOutPath='${openjdk16_headless.outPath}'
      find "$out" -name \*.so | while read lib; do
        new_refs="$(patchelf --print-rpath "$lib" | perl -pe 's,:?\Q$ENV{openjdkOutPath}\E[^:]*,,')"
        patchelf --set-rpath "$new_refs" "$lib"
      done
    '';

    disallowedReferences = [ openjdk16_headless ];

    passthru.deps = deps;

    meta = with lib; {
      homepage = "http://openjdk.java.net/projects/openjfx/";
      license = licenses.gpl2;
      description = "The next-generation Java client toolkit";
      maintainers = with maintainers; [ abbradar ];
      platforms = [ "i686-linux" "x86_64-linux" ];
    };
  };
  v = {
    feature = "17";
    interim = "0";
    build = "0";
  };
in ccacheStdenv.mkDerivation rec {
  version = "${v.feature}+${v.build}";
  name = "jetbrains-jdk-${version}";
  src = fetchFromGitHub {
    owner = "JetBrains";
    repo = "JetBrainsRuntime";
    rev = "ad0ce132e91b2d794001072b7322266d6735c39e";
    sha256 = "sha256-kt28jqptj0J0vNOIv/kBNcNfBmmqU6TVQYXAW1HjSl4=";
  };
  nativeBuildInputs = [ pkg-config autoconf unzip ];
  buildInputs = [
    cpio
    file
    which
    zip
    perl
    zlib
    cups
    freetype
    alsa-lib
    libjpeg
    giflib
    libpng
    zlib
    lcms2
    xorg.libX11
    xorg.libICE
    xorg.libXrender
    xorg.libXext
    xorg.libXtst
    xorg.libXt
    xorg.libXtst
    xorg.libXi
    xorg.libXinerama
    xorg.libXcursor
    xorg.libXrandr
    fontconfig
    openjdk16
    gtk3
    gnome2.gnome_vfs
    gnome2.GConf
    glib
  ];

  patches = openjdk16.drvAttrs.patches;

  prePatch = ''
    chmod +x configure
    patchShebangs --build configure
  '';

  JBSDK_VERSION = version;
  JDK_BUILD_NUMBER = "1";
  build_number = "1";
  bundle_type = "jcef";
  JBSDK_VERSION_WITH_DOTS = toString version;
  JCEF_PATH = pkgs.callPackage ./jcef.nix { };
  VENDOR_NAME = "JetBrains s.r.o.";
  VENDOR_VERSION_STRING =
    "JBR-${JBSDK_VERSION_WITH_DOTS}.${JDK_BUILD_NUMBER}-${build_number}-${bundle_type}";

  do_reset_changes = 1;
  do_reset_dcevm = 0;
  HEAD_REVISION = 0;
  RELEASE_NAME = "linux-x86_64-server-release";

  IMAGES_DIR = "build/${RELEASE_NAME}/images";
  JSDK = "${IMAGES_DIR}/jdk";
  JSDK_MODS_DIR = "${IMAGES_DIR}/jmods";
  JBRSDK_BUNDLE = "jbrsdk";

  preConfigure = ''
    configureFlagsArray=(
      --with-boot-jdk=${openjdk16.home}
      --with-version-pre=
      --enable-unlimited-crypto
      --with-native-debug-symbols=internal
      --with-libjpeg=system
      --with-giflib=system
      --with-libpng=system
      --with-zlib=system
      --with-lcms=system
      --with-stdc++lib=dynamic
      --with-jvm-features=zgc,shenandoahgc
      --with-import-modules=${openjfx}
      # jbr
      --with-debug-level=release
      --with-vendor-name="${VENDOR_NAME}"
      --with-vendor-version-string=${VENDOR_VERSION_STRING}
      --with-version-pre=
      --with-version-build=${JDK_BUILD_NUMBER}
      --with-version-opt=b${build_number}
      --enable-cds=yes
    )
  '';

  separateDebugInfo = true;

  NIX_CFLAGS_COMPILE = "-Wno-error";

  NIX_LDFLAGS = toString [
    "-lfontconfig"
    "-lcups"
    "-lXinerama"
    "-lXrandr"
    "-lmagic"
    "-lgtk-3"
    "-lgio-2.0"
    "-lgnomevfs-2"
    "-lgconf-2"
  ];

  makeFlags = [ "CONF=${RELEASE_NAME}" ];
  buildFlags = [ "images" ];
  postBuild = ''
    set -x
    patch -p0 < jb/project/tools/patches/add_jcef_module.patch
    . jb/project/tools/common/scripts/common.sh
    update_jsdk_mods ${JSDK} ${JCEF_PATH}/jmods ${JSDK}/jmods ${JSDK_MODS_DIR}
    cp ${JCEF_PATH}/jmods/* ${JSDK_MODS_DIR} # $JSDK/jmods is not changed
    modules=$(xargs < modules.list | sed s/" "//g)
    create_image_bundle "jbr_jcef" "jbr" ${JSDK_MODS_DIR} "$modules"

    modules=$(cat ${JSDK}/release | grep MODULES | sed s/MODULES=//g | sed s/' '/','/g | sed s/\"//g | sed s/\\n//g)
    modules=$modules,$(get_mods_list "${JCEF_PATH}"/jmods)
    create_image_bundle "${JBRSDK_BUNDLE}_jcef" ${JBRSDK_BUNDLE} ${JSDK_MODS_DIR} "$modules"
  '';

  installPhase = ''
    mkdir -p $out/lib

    mv build/*/images/jdk $out/lib/openjdk

    # Remove some broken manpages.
    rm -rf $out/lib/openjdk/man/ja*

    # Mirror some stuff in top-level.
    mkdir -p $out/share
    ln -s $out/lib/openjdk/include $out/include
    ln -s $out/lib/openjdk/man $out/share/man
    ln -s $out/lib/openjdk/lib/src.zip $out/lib/src.zip

    # jni.h expects jni_md.h to be in the header search path.
    ln -s $out/include/linux/*_md.h $out/include/

    # Remove crap from the installation.
    rm -rf $out/lib/openjdk/demo

    ln -s $out/lib/openjdk/bin $out/bin
  '';

  preFixup = ''
    # Propagate the setJavaClassPath setup hook so that any package
    # that depends on the JDK has $CLASSPATH set up properly.
    mkdir -p $out/nix-support
    #TODO or printWords?  cf https://github.com/NixOS/nixpkgs/pull/27427#issuecomment-317293040
    echo -n "${setJavaClassPath}" > $out/nix-support/propagated-build-inputs

    # Set JAVA_HOME automatically.
    mkdir -p $out/nix-support
    cat <<EOF > $out/nix-support/setup-hook
    if [ -z "\''${JAVA_HOME-}" ]; then export JAVA_HOME=$out/lib/openjdk; fi
    EOF
  '';

  postFixup = ''
    # Build the set of output library directories to rpath against
    LIBDIRS=""
    for output in $outputs; do
      if [ "$output" = debug ]; then continue; fi
      LIBDIRS="$(find $(eval echo \$$output) -name \*.so\* -exec dirname {} \+ | sort | uniq | tr '\n' ':'):$LIBDIRS"
    done
    # Add the local library paths to remove dependencies on the bootstrap
    for output in $outputs; do
      if [ "$output" = debug ]; then continue; fi
      OUTPUTDIR=$(eval echo \$$output)
      BINLIBS=$(find $OUTPUTDIR/bin/ -type f; find $OUTPUTDIR -name \*.so\*)
      echo "$BINLIBS" | while read i; do
        patchelf --set-rpath "$LIBDIRS:$(patchelf --print-rpath "$i")" "$i" || true
        patchelf --shrink-rpath "$i" || true
      done
    done
  '';

  disallowedReferences = [ openjdk16 ];

  meta = with lib; {
    description = "An OpenJDK fork to better support Jetbrains's products.";
    longDescription = ''
      JetBrains Runtime is a runtime environment for running IntelliJ Platform
      based products on Windows, Mac OS X, and Linux. JetBrains Runtime is
      based on OpenJDK project with some modifications. These modifications
      include: Subpixel Anti-Aliasing, enhanced font rendering on Linux, HiDPI
      support, ligatures, some fixes for native crashes not presented in
      official build, and other small enhancements.

      JetBrains Runtime is not a certified build of OpenJDK. Please, use at
      your own risk.
    '';
    homepage = "https://bintray.com/jetbrains/intellij-jdk/";
    inherit (openjdk16.meta) license platforms mainProgram;
  };

  passthru = {
    architecture = "";
    inherit gtk3;
    home = "${out}/lib/openjdk";
  };
}
```

**Comment by VergeDX** [comment] 2022-04-19 02:23
Thanks for your contribution! I will consider making a NUR package.

**Comment by pschyska** [comment] 2022-04-19 19:20
Ping me if you get something running

**Comment by pschyska** [comment] 2022-06-17 14:37
@VergeDX I recently got a problem similar to https://github.com/NixOS/nixpkgs/issues/50344, where the cursor theme and size in my Xresources wasn't respected any longer. In addition to JBR getting `libXcursor` patchelfed in, it must be in intellij-idea's `LD_LIBRARY_PATH`.
 I've updated my intellij-idea derivation in https://github.com/NixOS/nixpkgs/issues/160468#issuecomment-1044677552 accordingly.
Additionally, I've had the chance to try out JBR11 builds, and they seem to work as well (with the derivation I gave above). To start intellij-idea with jbr 11, you could/should remove all the `--add-opens`, and you can't use ZGC but must use another gc (e.g. `-XX:+UseG1GC` or `-XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC`, optionally adding the recommended `-XX:-UseBiasedLocking -XX:+DisableExplicitGC` and `-XX:ShenandoahGCMode=iu` if you are feeling adventurous 🙂 )

Did you progress in your project packaging JBR from sources?

**Comment by DAlperin** [comment] 2022-07-18 07:33
@VergeDX @pschyska this is a fix I would really like to see. What needs to get done at this point to get this mainlined? I'd be interested in trying to figure that out.

**Comment by DAlperin** [comment] 2022-07-30 21:38
@pschyska if you were interested in making JCEF at least usable, I'd be happy to offer a bounty in the $200 range. If that sounds interesting to you, shoot me an email at opensource@dov.dev. Totally fine if not, but I like to support open source I use when possible :)

**Comment by abeforgit** [comment] 2022-09-06 12:09
Just wanted to chime in and say I've also managed to get the setup @pschyska described working (the patched binary)
Works like a charm with the (as of now) latest 17.0.4  binaries
I just had to add `pango` and `cairo` to the dependencies in the `makeLibraryPath` argument
Thank you!

**Comment by Clindbergh** [comment] 2023-01-06 17:18
> Works like a charm with the (as of now) latest 17.0.4 binaries

@abeforgit / @pschyska Does the setup still work for you? Do you have a fork of your nixpkgs by any chance? I'm unsure on where these files have to be located.

**Comment by abeforgit** [comment] 2023-01-10 17:06
yes it does still work, here's a link to my (quite cursed, be warned) nixos config:
https://github.com/abeforgit/nixos-config

i've added a package for the jdk, which I then import and use in an overlay here https://github.com/abeforgit/nixos-config/blob/6c54ca7a5931e317a0a01fa469de9e05e755ec74/flake.nix#L92


there is also [this pr](https://github.com/NixOS/nixpkgs/pull/196738) which seems almost ready to be merged

**Comment by Clindbergh** [comment] 2023-01-13 17:10
Thanks a lot for sharing @abeforgit!

**Closed** 2023-01-14 16:01 UTC
Labels: 0.kind: bug
