### ISSUE TITLE
Build failure: python-3.10-qtile-0.22.1

### ISSUE THREAD

**Issue by Zemrod** [NixOS/nixpkgs#252769] opened 2023-09-01 12:28 UTC
### Steps To Reproduce

1. run `nixos-rebuild boot --upgrade`

### Build log

[qtile build fail log](https://gist.github.com/Zemrod/2b4dd102246e6643b3a378f426916b4e)

### Additional context

the unstable branch is used

### Notify maintainers

@arjan-s
@kamilchm

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.46, NixOS, 23.11 (Tapir), 23.11pre517472.b85ed9dcbf18`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by fabaff** [comment] 2023-09-02 08:30
This PR (https://github.com/NixOS/nixpkgs/pull/252901) could be the first step to solve the issue.

```bash
       >     raise DistutilsError(str(e)) from e
       > distutils.errors.DistutilsError: Command '['/nix/store/rfrlbr8h85rlzwrccaqbqilsggs0n9ig-python3-3.11.4/bin/python3.11', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmpfpn363np', '--quiet', 'xcffib>=1.4.0']' returned non-zero exit status 1.
       > /nix/store/1qxkj91n172qnypdrqdybh4p203nax7g-stdenv-linux/setup: line 1596: pop_var_context: head of shell_variables not a function context
```

**Comment by siph** [comment] 2023-09-02 16:42
I think this is a duplicate of #252320

**Comment by arjan-s** [comment] 2023-09-04 09:59
It's not a duplicate, that issue was from someone who was trying to build Qtile from its master branch.

Qtile in nixpkgs-unstable is currently failing to build because of https://github.com/NixOS/nixpkgs/pull/252901 or https://github.com/NixOS/nixpkgs/pull/247249 because those packages were updated without waiting for Qtile to release a version that supports them.

For people running qtile from nixos-unstable, you should install `cairocffi` and `xcffib` from `nixos-23.05` to make Qtile build again. Once Qtile releases 0.23.0, we will update the package in unstable and then the dependencies will align again. This is probably still some time in the future though.

**Comment by siph** [comment] 2023-09-05 01:00
The simplist way to fix this is to set `qtile.package` to the `nixpkgs/nixos-23.05` version of `qtile`.

If you're using flakes you can [add multiple `nixpkgs` channels](https://nixos.wiki/wiki/Flakes#Importing_packages_from_multiple_channels) and do something like:
```nix
{
  services.xserver.windowManager.qtile = {
    enable = true;
    package = pkgs.stable.qtile;
  };
}
```
Or use whatever method you prefer to get `nixpkgs/nixos-23.05`.

**Comment by Zemrod** [comment] 2023-09-08 12:33
Worked like a charm
a non flake solution if someone is as un-flake as I

`nix-channel --add https://nixos.org/channels/nixos-23.05 stable`

```nix
nixpkgs.config = {
  packageOverrides = pkgs: {
    stable = import <stable> {
      config = config.nixpkgs.config;
    };
  };
};

services.xserver.windowManager.qtile = {
  enable = true;
  package = pkgs.stable.qtile;
};
```

**Comment by toh995** [comment] 2023-09-09 17:01
> The simplist way to fix this is to set `qtile.package` to the `nixpkgs/nixos-23.05` version of `qtile`.
> 
> If you're using flakes you can [add multiple `nixpkgs` channels](https://nixos.wiki/wiki/Flakes#Importing_packages_from_multiple_channels) and do something like:
> 
> ```nix
> {
>   services.xserver.windowManager.qtile = {
>     enable = true;
>     package = pkgs.stable.qtile;
>   };
> }
> ```
> 
> Or use whatever method you prefer to get `nixpkgs/nixos-23.05`.

This didn't work for me. But I got it working by downgrading my entire config to stable 23.05. :shrug:

**Comment by Panadestein** [comment] 2023-09-15 21:07
@Zemrod which display manager are you using? I tried that with Lightdm, but I get a black screen when I try to login, and then get dropped back to Lightdm after some seconds. I didn't find anything in the qtile logs, or in journalctl. Very strange. I did something similar to what you did, but with flakes

**Comment by Zemrod** [comment] 2023-09-16 04:29
> @Zemrod which display manager are you using? I tried that with Lightdm, but I get a black screen when I try to login, and then get dropped back to Lightdm after some seconds. I didn't find anything in the qtile logs, or in journalctl. Very strange. I did something similar to what you did, but with flakes

@Panadestein 
i use startx instead of a DisplayManager

but if you get thrown back into lightdm after a while, the qtile logs should show something
i recommend asking in the discord or the forum, someone there can probably help you better

**Comment by 0xfabio** [comment] 2023-09-16 08:48
> @Zemrod which display manager are you using? I tried that with Lightdm, but I get a black screen when I try to login, and then get dropped back to Lightdm after some seconds. I didn't find anything in the qtile logs, or in journalctl. Very strange. I did something similar to what you did, but with flakes

I had the same problem, fixed it with the following by overriding the xsession package that was called.
You would need to add the stable release as an overlay (as described earlier in this thread).
I am using qtile-unwrapped, if you use standard qtile, you would probably need to update the package name.

```nix
    windowManager.session = [{
      name = "qtile";
      start = ''
        ${pkgs.stable.qtile-unwrapped}/bin/qtile start -b x11 \
        --config  /home/fabio/.config/qtile/config.py &
        waitPID=$!
      '';
    }];
```

**Comment by nieomylnieja** [comment] 2023-09-21 20:23
> @Zemrod which display manager are you using? I tried that with Lightdm, but I get a black screen when I try to login, and then get dropped back to Lightdm after some seconds. I didn't find anything in the qtile logs, or in journalctl. Very strange. I did something similar to what you did, but with flakes

Not sure If it's the same issue or If you haven't missed it, but I had the same problem and journalctl did catch the issue:

```
...xsession: line 8: /nix/store/h7xp423qy2s05glh2gw5a8gjprf5xfnv-python3-3.10.12-env/bin/qtile: No such file or directory
```

**Comment by Panadestein** [comment] 2023-09-21 20:31
@nieomylnieja  I was checking for critical errors `journalctl -p 3 -xb`, and this error is definitely not there. But thanks for sharing, I should have look in the full logs. Unfortunately, the solution proposed by @0xfabio did not work for me out of the box, I haven't had the time to investigate further. Did you in the meantime found a workaround?

**Comment by Thlr** [comment] 2023-09-22 08:35
Unfortunately the solution proposed in https://github.com/NixOS/nixpkgs/issues/252769#issuecomment-1705808486, did not work for me. Rebuilding the system went fine but the problem comes when booting as Qtile just won't start :

```
2023-09-22 10:12:46,030 ERROR libqtile start.py:start():L92 Qtile crashed
Traceback (most recent call last):
  File "/nix/store/x1q1ynf510fd01cds54jza199fkvi1l3-python3-3.10.12-env/lib/python3.10/site-packages/libqtile/scripts/start.py", line 90, in start
    q.loop()
  File "/nix/store/x1q1ynf510fd01cds54jza199fkvi1l3-python3-3.10.12-env/lib/python3.10/site-packages/libqtile/core/manager.py", line 198, in loop
    asyncio.run(self.async_loop())
  File "/nix/store/wlxpsdzfvdanfzh704qmgyzb42qvy4fr-python3-3.10.12/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/nix/store/wlxpsdzfvdanfzh704qmgyzb42qvy4fr-python3-3.10.12/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/nix/store/x1q1ynf510fd01cds54jza199fkvi1l3-python3-3.10.12-env/lib/python3.10/site-packages/libqtile/core/manager.py", line 226, in async_loop
    self.finalize()
  File "/nix/store/x1q1ynf510fd01cds54jza199fkvi1l3-python3-3.10.12-env/lib/python3.10/site-packages/libqtile/core/manager.py", line 306, in finalize
    self.core.finalize()
  File "/nix/store/x1q1ynf510fd01cds54jza199fkvi1l3-python3-3.10.12-env/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 170, in finalize
    self.conn.conn.core.DeletePropertyChecked(
  File "/nix/store/x1q1ynf510fd01cds54jza199fkvi1l3-python3-3.10.12-env/lib/python3.10/site-packages/xcffib/xproto.py", line 2828, in DeleteProperty
    return self.send_request(19, buf, is_checked=is_checked)
  File "/nix/store/x1q1ynf510fd01cds54jza199fkvi1l3-python3-3.10.12-env/lib/python3.10/site-packages/xcffib/__init__.py", line 392, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/nix/store/x1q1ynf510fd01cds54jza199fkvi1l3-python3-3.10.12-env/lib/python3.10/site-packages/xcffib/__init__.py", line 577, in wrapper
    self.invalid()
  File "/nix/store/x1q1ynf510fd01cds54jza199fkvi1l3-python3-3.10.12-env/lib/python3.10/site-packages/xcffib/__init__.py", line 567, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-09-22 10:12:46,031 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
```

@arjan-s , in https://github.com/NixOS/nixpkgs/issues/252769#issuecomment-1704972913 you say that the problem comes from another package that was updated and broke the current release of qtile. I don't wand to be rude and maybe I don't understand fully the problem but isn't the core promise of nix (and nixos) to enable devs to **pin** dependencies and package them **with** their application?

I would try your solution of installing the missing libs myself but I am not sure how to proceed here (if you would indulge me I would appreciate a lot). I would also build qtile from master but that looks like a whole other story with its own set of problems.

I think basing my whole system on unstable packages was a mistake in the first place and I should expect these problems but a dependency problem just feels weird.

In lack of a better solution I'll just bite the bullet and move to gnome or hyprland.

**Comment by cbsirb** [comment] 2023-09-25 06:42
The [version 0.23](https://github.com/qtile/qtile/releases/tag/v0.23.0) was released a few hours ago and theoretically it should fix the [cairocffi dependency](https://github.com/qtile/qtile/issues/4346) (see the latest comments)

**Comment by Thlr** [comment] 2023-09-25 07:54
Great news :)

**Comment by vinnymeller** [comment] 2023-09-26 06:04
> > @Zemrod which display manager are you using? I tried that with Lightdm, but I get a black screen when I try to login, and then get dropped back to Lightdm after some seconds. I didn't find anything in the qtile logs, or in journalctl. Very strange. I did something similar to what you did, but with flakes
> 
> I had the same problem, fixed it with the following by overriding the xsession package that was called. You would need to add the stable release as an overlay (as described earlier in this thread). I am using qtile-unwrapped, if you use standard qtile, you would probably need to update the package name.
> 
> ```nix
>     windowManager.session = [{
>       name = "qtile";
>       start = ''
>         ${pkgs.stable.qtile-unwrapped}/bin/qtile start -b x11 \
>         --config  /home/fabio/.config/qtile/config.py &
>         waitPID=$!
>       '';
>     }];
> ```
> 
> This is basically just copied from the [nixpkgs module](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/window-managers/qtile.nix#L54) and there is probably a better way on how to achive this. (I am just getting started)

i cannot believe i overlooked this for like two straight weeks :man_facepalming:

**Comment by arjan-s** [comment] 2023-09-26 08:03
> @arjan-s , in [#252769 (comment)](https://github.com/NixOS/nixpkgs/issues/252769#issuecomment-1704972913) you say that the problem comes from another package that was updated and broke the current release of qtile. I don't wand to be rude and maybe I don't understand fully the problem but isn't the core promise of nix (and nixos) to enable devs to **pin** dependencies and package them **with** their application?

In theory, you're right about being able to pin dependencies. But that isn't how nixpkgs works. Packages usually have a single version available at any point in time in nixpkgs, and those can be updated independently, breaking other packages in the process. PR submitters should account for that and make sure their PRs don't break other packages, but this isn't always done fully or sometimes isn't even possible without building every single package in nixpkgs.

Pinning dependencies can be easily done **outside** nixpkgs though. In your local repo you could define your own overlays or packages in which you force for instance `cairocffi` and `xcffib` to a specific version. Or you could pin `qtile` to a specific revision from their master repo. And if you would be the dev of qtile, you could indeed publish your own flake.nix that pins all dependencies to known working versions.

> I think basing my whole system on unstable packages was a mistake in the first place and I should expect these problems but a dependency problem just feels weird.

Basing a system on `nixos-unstable` is a choice that everyone can make, but can be annoying sometimes. In my case, I have regular (every 1 to 2 weeks) evaluation or build failures that make me unable to update my systems. But those build time failures are really one of nixos's strengths, because those failures don't make their way into my live system. Run time failures happen almost never, so even on nixos-unstable my systems are always rock solid.

Regarding build failures like this, I think there are essentially 3 choices:
- Fix it locally, either by mixing in packages from stable, pinning dependencies/versions or by applying some patch. Note that you need at least some nix skills to be able to do this
- Wait for someone else to fix it and don't update your system in the mean time
- Switch to the latest stable release

**Comment by Thlr** [comment] 2023-09-26 09:57
@arjan-s thank you, that is a summary I can get behind.

It actually wasn't obvious to me that you couldn't pin nixpkgs, inside nixpkgs. How so?
You can fetch any external repository from nixpkgs to get the actual source code. Can you do that with these two librairies? Do you have to rely on nixpkgs? Aren't these just additional python dependencies?

**Comment by arjan-s** [comment] 2023-09-26 10:34
In theory, yes. But in practice all dependencies are also packages in nixpkgs that just get referenced. Due to the pure evaluation of nix code in nixpkgs, you can't just do `pip install <whatever>` in a build script, because the inputs and outputs of a derivation (package in this case) must be known beforehand, which in turn means it has to be available in nixpkgs. This also means the build process of nixpkgs packages can't have internet access and can't download anything from build scripts. So, as a `qtile` package maintainer I could add specific version-pinned inputs (derivations) for `cairocffi` and `xcffib`, but then I would be duplicating the pre-existing packages in nixpkgs with slightly different inputs. In some cases, like `wlroots`, multiple versions are available in nixpkgs due to the incompatibilities between versions, but that's not the usual approach.

**Closed** 2023-09-28 05:00 UTC
Labels: 0.kind: build failure
