### ISSUE TITLE
Permissions for instance-specific folders on AWS EC2 AMIs are incorrect

### ISSUE THREAD

**Issue by ellie-idb** [NixOS/nixpkgs#348565] opened 2024-10-14 16:20 UTC
### Describe the bug
I'm running a plain, relatively vanilla version of NixOS, using the AMI specified [here](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/amazon-ec2-amis.nix). I went to add my SSH key in, only to find out that I wasn't being let into my system for an unknown reason. After doing some further digging, I found that sshd was complaining due to bad permissions:
![CleanShot 2024-10-14 at 12 15 39@2x](https://github.com/user-attachments/assets/26d6c94f-2683-4063-b02f-f24758f011f0)

This seemed strange to me, as I had not run any commands inside of the system to change the permissions. Upon further investigation, I found that /etc/sshd was owned by '755:root':
![image](https://github.com/user-attachments/assets/ad653e0c-fcb4-434b-aaea-3d69a9a2551f)
As well, /etc/ec2-metadata is also owned by '755:root':
![image](https://github.com/user-attachments/assets/45ac0d58-e9c9-4547-9e7b-c1a7c9597d6c)
  
### Steps To Reproduce
1. Launch a new EC2 instance with one of the NixOS AMIs
2. Add a new user, and set the openssh.authorizedKeys.keys attr to a key that you control
3. Attempt to SSH into the instance
4. ...
5. Bang your head against the wall

### Expected behavior
/etc/ssh and /etc/ec2-metadata should be owned by `root:root`

### Notify maintainers
@arianvp 

### Metadata

```console
[root@ip-172-31-33-110:~]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.79, NixOS, 24.11 (Vicuna), 24.11.20241010.b69de56`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/mln6wr5z539qgldmsm4j1k8k0dm19yvz-source`
```

**Comment by ellie-idb** [comment] 2024-10-14 16:21
FWIW, my configuration for my system is:
```nix
{ pkgs, lib, modulesPath, ... }: 
{
  imports = ["${modulesPath}/virtualisation/amazon-image.nix"];

  config = {
    programs.fish.enable = true;

    services.openssh = {
      enable = true;
      settings.PasswordAuthentication = false;
      settings.KbdInteractiveAuthentication = false;
    };

    users.users."ellie" = {
      openssh.authorizedKeys.keys = [
        # wallsocket yubikey
        "ssh-rsa ..."
      ];
      isNormalUser = true;
      
      group = "wheel";
      shell = pkgs.fish;
      createHome = true;
    };
  }; 
}
```
So, nothing crazy. This should just work, right?

**Comment by arianvp** [comment] 2024-10-14 16:26
Unfortunately you're running into a bug we accidentally shipped. See more info here:

https://discourse.nixos.org/t/breaking-changes-announcement-for-unstable/17574/63?u=arianvp

**Comment by arianvp** [comment] 2024-10-14 16:26
I will upload a fixed version of the AMI as soon as the fix lands on unstable

**Comment by ellie-idb** [comment] 2024-10-14 16:28
thanks! didn't see that. would you like to close this issue or leave it open until the fix lands?

**Comment by arianvp** [comment] 2024-10-14 16:57
Could you do me a favor and tell me the ami-id that you used? I can then also deprecate it in the AWS console

**Comment by arianvp** [comment] 2024-10-14 17:01
Hmm just to double check. You deployed a nixos-unstable release to this machine right? As I wouldn't expect this to happen on 24.05

**Comment by arianvp** [comment] 2024-10-14 17:46
Closing this as duplicate of https://github.com/NixOS/nixpkgs/issues/347672

**Closed by arianvp** 2024-10-14 17:46 UTC
Labels: 0.kind: bug
