### ISSUE TITLE
hash mismatch jaxlib (built with bazel and cuda support)

### ISSUE THREAD

**Issue by SpidFightFR** [NixOS/nixpkgs#346686] opened 2024-10-05 15:10 UTC
https://github.com/NixOS/nixpkgs/blob/6e6b3dd395c3b1eb9be9f2d096383a8d05add030/pkgs/development/python-modules/jaxlib/default.nix#L377

I get the following error (with cuda enabled):
```
error: hash mismatch in fixed-output derivation '/nix/store/wf16dhdpavb09vqssd0lvx622wy7n616-bazel-build-jaxlib-0.4.28-deps.tar.gz.drv':
         specified: sha256-VGNMf5/DgXbgsu1w5J1Pmrukw+7UO31BNU+crKVsX5k=
            got:    sha256-IjsUIfCLcZiAdwNAmM1ul0dxT6XAHpQCDNFnjIPp1gc=
```

**Comment by nixupp** [comment] 2024-10-07 18:36
I get the same error so I'll file a 

# Proper bug report
### Describe the bug
Package  python311Packages.jaxlib (bazel-build-jaxlib) have a mismatched hash if `cudaSupport = true`

```
error: hash mismatch in fixed-output derivation '/nix/store/wf16dhdpavb09vqssd0lvx622wy7n616-bazel-build-jaxlib-0.4.28-deps.tar.gz.drv':
         specified: sha256-VGNMf5/DgXbgsu1w5J1Pmrukw+7UO31BNU+crKVsX5k=
            got:    sha256-IjsUIfCLcZiAdwNAmM1ul0dxT6XAHpQCDNFnjIPp1gc=
```

### Steps To Reproduce
Steps to reproduce the behavior:
1. Set `cudaSupport = true`
2. Add `python311Packages.jaxlib` to system environment packages
3. `nixos-rebuild test`
4. Get the mismatch

### Expected behavior
Hash matches

### Notify maintainers
@ndl Could you please fix this?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.54, NixOS, 24.05 (Uakari), 24.05.5532.90fe4c010368`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos-24.05-small"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Also, should this go under [6.topic: reproducible builds](https://github.com/NixOS/nixpkgs/labels/6.topic%3A%20reproducible%20builds)?

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by tomodachi94** [comment] 2024-10-28 06:36
Appears to be a duplicate of https://github.com/NixOS/nixpkgs/issues/321920

**Closed by tomodachi94** 2024-10-28 06:36 UTC
Labels: 0.kind: build failure
