### ISSUE TITLE
Add pgadmin4

### ISSUE THREAD

**Issue by PanAeon** [NixOS/nixpkgs#29770] opened 2017-09-25 11:32 UTC
A new version of pgadmin has been released. It has a new revamped interface and it is compatible with new releases of postgres.

* System: 17.x
* Nix version:  1.11.14
* Nixpkgs version: 17.03.1850.9e228fc2d8

**Comment by periklis** [comment] 2017-09-25 12:20
This is not so easy as you may think. I've tried in the past to integrate pgadmin4 in our nixpkgs, but failed mostly on the fact that we can't provide self-contained qt-apps as pgadmin4 is one. This is not a technical limitation but rather a bunch of work to make the qt-5 dependencies to provide this feature under nixos, too.

Disclaimer: My trials took place over a year ago with qt-5.6. We are currently on qt-5.9 and i am maybe missing any major overhaul since.

**Comment by PanAeon** [comment] 2017-09-25 12:43
I tried to build it, and the QT part worked very well, I just run `nix-shell -p qt5.full` and it worked. The python part is kind of problem for me, I have used pypi2nix, but it couldn't build `unittest2` because of the problem in the `unittest2` itself. 
@periklis I don't understand the problem with the standalone application. Does it have to be a self-contained Qt app? What if we link to qt libs? I looked at amarok for example, and it's linked to kdelibs4 if I'm not mistaken.

**Comment by periklis** [comment] 2017-09-26 11:18
I tried to integrate pgadmin4 as an [AppBundle](https://git.postgresql.org/gitweb/?p=pgadmin4.git;a=blob;f=pkg/mac/build.sh;h=870216587172d4c2e74b39d865e3c8c9dd1b2095;hb=HEAD) which needs to build the qt-based runtime and in turn all the qt-standalone app features for building app-bundles on mac.

My intention was to have something like pgadmin.app like in the pgadmin3 days.

**Comment by cinemast** [comment] 2019-05-01 14:28
I think this is a duplicate of #33103 and one of these can be closed.

**Comment by periklis** [comment] 2019-05-02 14:45
Indeed it's a duplicate.

**Closed by periklis** 2019-05-02 14:45 UTC
