### ISSUE TITLE
Steam cannot connect to friends network

### ISSUE THREAD

**Issue by mat8913** [NixOS/nixpkgs#44254] opened 2018-07-31 08:02 UTC
## Issue description

The Steam client cannot connect to the friends network. I'm still able to browse the Steam store and download games. I tried disabling the firewall, that had no effect.

### Steps to reproduce

1. Install Steam: `nix-env -iA nixos.steam`
2. Open Steam and log in
3. Wait a little bit, and a new window will open attempting to connect to Steam friends network
4. Get message:

    ```
    FRIENDS NETWORK UNREACHABLE
    This failure may indicate that your local network is offline or that the Steam Friends servers are currently offline.
    ```

## Technical details 

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.56, NixOS, 18.03.132915.d6c6c7fcec6 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(matthew): `"nixos-18.03"`
 - channels(root): `"nixos-18.03.132915.d6c6c7fcec6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by puffnfresh** [comment] 2018-07-31 09:04
Yeah, I can confirm the new friends feature doesn't work on NixOS.

**Comment by Enzime** [comment] 2018-08-01 09:40
Temporary fix is to launch `steam` with the flags `-nochatui -nofriendsui`, Steam should launch and use the old Friends list system.

**Comment by TomSmeets** [comment] 2018-08-02 14:14
I can't reproduce this issue on my machine tracking the `nixos-unstable` channel.
Everything works fine here.

```shell
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.54, NixOS, 18.09pre145679.dae9cf6106d (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09pre145679.dae9cf6106d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by mat8913** [comment] 2018-08-03 08:36
I've been experimenting with `nixos-rebuild build-vm` and discovered that the problem only occurs when I have this line in my configuration.nix:

    time.timeZone = "Australia/Sydney";

Temporary workaround: launch Steam as `TZ=UTC steam`.

**Comment by vcunat** [comment] 2018-08-03 08:47
I wonder if this could be something like https://github.com/NixOS/nixpkgs/issues/38991 but with the timezone format instead of locale.

**Comment by Vodurden** [comment] 2018-08-05 06:11
As an Australian who uses steam on NixOS I can confirm I'm experiencing the same issue. And that using `TZ=UTC steam` fixes the issue.

I've modified steam in my local nixpkgs to apply the workaround by adding `TZ=UTC` to the profile used by the chroot: https://github.com/Vodurden/nixpkgs/commit/2a7f0a49659af2cecb36ca5d5f798ffb4a24f914

I also noticed that this workaround only solves the issue if I launch steam through `steam &` on the command line or with `Command Line: run steam` in the plasma application launcher. If I launch steam through the Applications shortcut it doesn't seem to work. Not sure if that helps with diagnosing the root cause but I figure every detail helps \:)

**Comment by mat8913** [comment] 2018-08-05 07:27
Perhaps I should've tried this earlier, but launching Steam as `TZ="Australia/Sydney" steam` also works for me.

I have a theory that when TZ is not set, Steam figures out the timezone by doing the equivalent of `readlink /etc/localtime`.

On NixOS, this results in:

    /nix/store/sf38jy6fka7w2h06gjlxfh8z122j2v5r-steam-usr-target/etc/localtime

and Steam isn't able to figure anything out. However, on Debian (where Steam
chat still works), this results in:

    /usr/share/zoneinfo/Australia/Sydney

and Steam can figure out the timezone.

**Comment by instantepiphany** [comment] 2018-09-16 01:31
@mat8913's fix works on my machine. Just copied it to my local checkout of nixpkgs, did `nixos-rebuild switch`, opened steam and the new friends chat UI loaded and works fine!

**Comment by mat8913** [comment] 2018-09-16 11:39
@instantepiphany 

If you're referring to the `steam: Set TZ to detected timezone on startup` commit, I've opened a PR at #44602.

**Comment by GreatBigWhiteWorld** [comment] 2018-10-02 13:49
Any progress? Have had this problems for months and no fix coming?

**Comment by vcunat** [comment] 2018-10-02 13:54
@GreatBigWhiteWorld: did you try that PR and failed?  (I know it's not merged yet.)

**Comment by instantepiphany** [comment] 2018-10-07 03:59
@GreatBigWhiteWorld That PR by @mat8913 worked for me - https://github.com/NixOS/nixpkgs/pull/44602
After applying that patch I have had no problems so far!

**Comment by GreatBigWhiteWorld** [comment] 2018-10-09 04:39
Sorry I don't know how to apply a PR. I ain't no programmer....

**Comment by rthoo** [comment] 2018-10-20 20:08
I've changed the Download Region in Settings -> Downloads to US - Boston and it's fine now.

![image](https://user-images.githubusercontent.com/44326873/47260076-d0e45380-d48a-11e8-99b7-653a88d7ea1c.png)

**Comment by instantepiphany** [comment] 2018-10-20 23:14
@GreatBigWhiteWorld Knowing how to apply patches and having basic git skills will help if you want to use NixOS. 

But look at @rthoo's response, try that and see if it helps.

**Comment by GreatBigWhiteWorld** [comment] 2018-10-24 03:07
@Enzime So adding -nochatui -nofriendsui after the command worked until the last update, which broke it again. Good job valve.
@instantepiphany Change download region to Boston doesn't work for me.

**Comment by Infinisil** [comment] 2018-11-10 03:17
Closed with https://github.com/NixOS/nixpkgs/pull/44602

**Closed by Infinisil** 2018-11-10 03:17 UTC
