### ISSUE TITLE
Packaging Request: OpenSnitch

### ISSUE THREAD

**Issue by herrmoltke** [NixOS/nixpkgs#117783] opened 2021-03-27 12:43 UTC
**Project description**
OpenSnitch is an application firewall. It is a port of MacOS' Little Snitch.

**Metadata**

* homepage URL: https://github.com/evilsocket/opensnitch
* source URL: https://github.com/evilsocket/opensnitch
* license: GPL 3.0
* platforms: Linux

**Comment by prusnak** [comment] 2021-03-27 14:52
Duplicate of https://github.com/NixOS/nixpkgs/issues/76610

**Closed by prusnak** 2021-03-27 14:52 UTC
Labels: 0.kind: packaging request
