### ISSUE TITLE
Build failure: mosh

### ISSUE THREAD

**Issue by fbettag** [NixOS/nixpkgs#351301] opened 2024-10-25 23:05 UTC
### Steps To Reproduce

1. nix-shell -p mosh

### Build log

```
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/8ys8xqlgm6gqc9j8g82iqvggblaqvqq5-source
source root is source
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
applying patch /nix/store/nr2bhsbrmx0asvpg1yl1kj822kpfa63p-ssh_path.patch
patching file scripts/mosh.pl
Hunk #1 succeeded at 75 (offset 9 lines).
applying patch /nix/store/j4vacfp465nc675g8cwm877cz3ljg3wh-mosh-client_path.patch
patching file scripts/mosh.pl
applying patch /nix/store/lg1jpvmqk4vhjxp5cwbd01sw9llm9bla-bash_completion_datadir.patch
patching file configure.ac
Hunk #1 succeeded at 568 (offset 92 lines).
applying patch /nix/store/w5ygqi4kys6p1v8810vfnfqqlik0mskv-eee1a8cf413051c2a9104e8158e6990>
patching file configure.ac
Running phase: autoreconfPhase
@nix { "action": "setPhase", "phase": "autoreconfPhase" }
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /nix/store/pdxvzsirysww48qi34bfhjb9ga09ipc8-autoconf-2.72/bin/autocon>
configure.ac:325: warning: The macro 'AC_HELP_STRING' is obsolete.
configure.ac:325: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1553: AC_ARG_WITH is expanded from...
configure.ac:325: the top level
autoreconf: running: /nix/store/pdxvzsirysww48qi34bfhjb9ga09ipc8-autoconf-2.72/bin/autohea>
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:23: installing './ar-lib'
configure.ac:15: installing './compile'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
src/crypto/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
autoreconf: './install-sh' is updated
autoreconf: Leaving directory '.'
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
patching script interpreter paths in ./configure
./configure: interpreter directive changed from "#! /bin/sh" to "/nix/store/0w0hhy7rmn5xis>
configure flags: --disable-static --disable-dependency-tracking --prefix=/nix/store/r6l5rf>
configure: WARNING: unrecognized options: --disable-static
checking for a BSD-compatible install... /nix/store/b7j95xd7yccclshfln10k843q2qf20yg-coreu>
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /nix/store/b7j95xd7yccclshfln10k843q2qf20yg-coreutils>
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to build with code coverage support... no
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether clang accepts -g... yes
checking for clang option to enable C11 features... none needed
checking whether clang understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of clang... none
checking whether the compiler supports GNU C++... yes
checking whether clang++ accepts -g... yes
checking for clang++ option to enable C++11 features... none needed
checking dependency style of clang++... none
checking for ranlib... ranlib
checking for protoc... /nix/store/xpzlxkhgnm53fvihlvpdznssbv42x8cq-protobuf-28.2/bin/protoc
checking the archiver (ar) interface... ar
checking whether clang++ supports C++17 features with -std=gnu++17... yes
checking whether C++ compiler accepts -fno-strict-overflow... no
checking whether C++ compiler accepts -D_FORTIFY_SOURCE=2... yes
checking whether the linker accepts -fstack-protector-all... yes
checking whether C++ compiler accepts -Wstack-protector... yes
checking whether C++ compiler accepts --param ssp-buffer-size=1... yes
checking whether C++ compiler accepts -fPIE... yes
checking whether the linker accepts -fPIE -pie... no
checking whether the linker accepts -fPIE -Wl,-pie... yes
checking whether the linker accepts -Wl,-z,relro... no
checking whether C++ compiler accepts -fno-default-inline... no
checking whether C++ compiler accepts -pipe... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for utempter_remove_record in -lutempter... no
configure: WARNING: Unable to find libutempter; utmp entries will not be made.
checking for compress in -lz... yes
checking for library containing socket... none required
checking for library containing inet_addr... none required
checking for library containing clock_gettime... none required
checking for fcntl.h... yes
checking for langinfo.h... yes
checking for limits.h... yes
checking for locale.h... yes
checking for netdb.h... yes
checking for netinet/in.h... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for inttypes.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for sys/ioctl.h... yes
checking for sys/resource.h... yes
checking for sys/socket.h... yes
checking for sys/stat.h... (cached) yes
checking for sys/time.h... yes
checking for termios.h... yes
checking for unistd.h... (cached) yes
checking for wchar.h... yes
checking for wctype.h... yes
checking for pty.h... no
checking for util.h... yes
checking for libutil.h... no
checking for paths.h... yes
checking for endian.h... no
checking for sys/endian.h... no
checking for utmpx.h... yes
checking for termio.h... no
checking for sys/uio.h... yes
checking for memory... yes
checking for tr1/memory... no
checking for inline... inline
checking for int64_t... yes
checking for pid_t... yes
checking for C/C++ restrict keyword... no
checking for size_t... yes
checking for ssize_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for uintptr_t... yes
checking for gettimeofday... yes
checking for posix_memalign... yes
checking for cfmakeraw... yes
checking for pselect... yes
checking for pledge... no
checking pkg-config is at least version 0.9.0... yes
checking for TINFO... yes
checking for CommonCrypto/CommonCrypto.h... yes
checking for OpenSSL... yes
checking for AES_encrypt in -lcrypto... yes
checking for EVP_aes_128_ocb in -lcrypto... yes
checking for Nettle... no
checking for clang++ -std=gnu++17 options needed to detect all undeclared functions... non>
checking whether forkpty is declared... no
checking for library containing forkpty... none required
checking whether FD_ISSET() argument is const... yes
checking whether std::shared_ptr is available... yes
checking whether std::tr1::shared_ptr is available... no
checking whether clock_gettime() is supported... yes
checking whether mach_absolute_time is declared... yes
checking whether __builtin_ctz is declared... no
checking whether ffs is declared... yes
checking whether be64toh is declared... no
checking whether betoh64 is declared... no
checking whether bswap64 is declared... no
checking whether __builtin_bswap64 is declared... no
checking whether OSSwapHostToBigInt64 is declared... yes
checking whether IP_MTU_DISCOVER is declared... no
checking whether IP_RECVTOS is declared... yes
checking whether __STDC_ISO_10646__ is declared... no
configure: WARNING: C library doesn't advertise wchar_t is Unicode (OS X works anyway with>
checking whether IUTF8 is declared... yes
checking for protobuf... yes
checking whether protoc matches protobuf... no
clang-16: error: no such file or directory: 'SHELL:-Xarch_x86_64'
clang-16: error: no such file or directory: 'SHELL:-Xarch_x86_64'
clang-16: error: no such file or directory: 'SHELL:-Xarch_arm64'
clang-16: error: no such file or directory: 'SHELL:-Xarch_x86_64'
clang-16: error: no such file or directory: 'SHELL:-Xarch_x86_64'
clang-16: error: no such file or directory: 'SHELL:-Xarch_arm64'
configure: error: in '/private/tmp/nix-build-mosh-1.4.0.drv-0/source':
configure: error: Could not build output generated by protoc (/nix/store/xpzlxkhgnm53fvihl>
Check that protoc matches the installed protobuf headers and libraries.
See 'config.log' for more details
```

### Additional context

Running on OSX Sequoia.

### Notify maintainers

@skeuchel 

### Metadata

 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.1.0, macOS 15.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/lsy6c2f9alj2gkjj36h754kk63x6701l-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jackwilsdon** [comment] 2024-10-26 03:16
This seems to be a duplicate of #349449 - the fix is #350035: https://nixpk.gs/pr-tracker.html?pr=350035

**Closed** 2024-10-26 09:21 UTC
Labels: 6.topic: darwin, 0.kind: build failure
