### ISSUE TITLE
pulseeffects can't find most of its plugins

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#60383] opened 2019-04-28 17:20 UTC
I'm using the latest `pulseeffects` from `master` and it works fine, mostly. I notice the following errors during start-up, though:

~~~
.pulseeffects-w[7916]: limiter plugin was not found!
.pulseeffects-w[7916]: filter plugin was not found!
.pulseeffects-w[7916]: reverb plugin was not found!
.pulseeffects-w[7916]: bass_enhancer plugin was not found!
.pulseeffects-w[7916]: exciter plugin was not found!
.pulseeffects-w[7916]: multiband_compressor plugin was not found!
.pulseeffects-w[7916]: gate plugin was not found!
.pulseeffects-w[7916]: multiband_gate plugin was not found!
.pulseeffects-w[7916]: deesser plugin was not found!
.pulseeffects-w[7916]: stereo_tools plugin was not found!
.pulseeffects-w[7916]: limiter plugin was not found!
.pulseeffects-w[7916]: filter plugin was not found!
.pulseeffects-w[7916]: reverb plugin was not found!
.pulseeffects-w[7916]: gate plugin was not found!
.pulseeffects-w[7916]: deesser plugin was not found!
.pulseeffects-w[7916]: multiband_compressor plugin was not found!
.pulseeffects-w[7916]: multiband_gate plugin was not found!
.pulseeffects-w[7916]: unable to send notifications through org.freedesktop.Notifications: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
~~~

Looking at the build it seems like all recommended dependencies are there so it doesn't seem likely that those plugins weren't built, no? But why are they missing at run-time? And why are others (like the equalizer) *not* missing?

**Comment by Infinisil** [comment] 2019-04-28 19:03
After some bisecting I found https://github.com/NixOS/nixpkgs/pull/57309 to be the cause of this, reverting it fixes it. I'm not entirely sure why that is though, investigating..

**Comment by Infinisil** [comment] 2019-04-28 19:15
Was fixed in calf with https://github.com/calf-studio-gear/calf/pull/213, which is in the latest version, I have opened a PR to update calf

**Closed** 2019-04-28 19:58 UTC
Labels: 0.kind: bug
