### ISSUE TITLE
plex: EasyAudioEncoder binary has the wrong linker

### ISSUE THREAD

**Issue by izuk** [NixOS/nixpkgs#25502] opened 2017-05-04 16:44 UTC
## Issue description

After installing plex, things go well until I try to play a video with AC3 audio.  Then I see this in the logs:

```
May 04, 2017 07:04:35.000 [0x7f12203fd700] ERROR - [Transcoder] [ac3_eae @ 0x28e5a60] EAE timeout! EAE not running, or wrong folder? Could not read '/tmp/pms-88462e58-7912-4406-8d29-ddd80a432a67/EasyAudioEncoder/Convert to WAV (to 8ch or less)/2xsve3k7i5bkyahzcpgco9a4_8725-1-2.wav'
May 04, 2017 07:04:35.000 [0x7f120ffed700] ERROR - [Transcoder] [ac3_eae @ 0x28e5a60] error reading output
May 04, 2017 07:04:35.001 [0x7f12187fe700] ERROR - [Transcoder] Error while decoding stream #0:1: Input/output error
```

The problem is that somewhere in the install process the EasyAudioEncoder binary was installed with the wrong linker:

```
$ file "/var/lib/plex/Plex Media Server/Codecs/EasyAudioEncoder-133-linux-ubuntu-x86_64/EasyAudioEncoder/EasyAudioEncoder"
/var/lib/plex/Plex Media Server/Codecs/EasyAudioEncoder-133-linux-ubuntu-x86_64/EasyAudioEncoder/EasyAudioEncoder: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.4.0, stripped, with debug_info
```

### Steps to reproduce

Play a video with AC3 audio, that triggers audio transcoding.  Then look in the PMS log in /var/lib/plex.

## Technical details

* System: 17.09pre106916.c5badb123a (Hummingbird)
* Nix version: nix-env (Nix) 1.11.9
* Nixpkgs version: 17.09pre106916.c5badb123a

**Comment by thanegill** [comment] 2018-03-11 19:30
Looks like the codec that plex dynamically downloads just has the wrong interpreter:

```
$ patchelf --print-interpreter EasyAudioEncoder
/lib64/ld-linux-x86-64.so.2
```

I can confirm that patching it fixes the issue:

```
$ patchelf --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" EasyAudioEncoder
```

Is there a way we could patch this after plex has downloaded the codec?

**Comment by solson** [comment] 2019-03-22 04:52
This is still a problem (and running patchself manually still fixes it).

**Comment by bachp** [comment] 2019-04-25 07:25
@solson Is this still an issue not that #56565 is merged?

**Comment by solson** [comment] 2019-06-27 22:50
I finally got around to updating and testing this, and I can confirm that Plex is automatically downloading new codecs and they are working. Thanks to everyone who worked on this! I think the issue can be closed.

**Comment by dywedir** [comment] 2019-06-27 23:17
Thank you for looking into this!

**Closed by dywedir** 2019-06-27 23:17 UTC
