### ISSUE TITLE
Suspend to RAM gone in 18.09?

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#47760] opened 2018-10-03 14:08 UTC
## Issue description
It used to be possible to press Alt-F2 in Plasma5, and then type Suspend which would then complete to Suspend to RAM. This is no longer possible. 

Similarly, in the K menu, there is also no option anymore to suspend to RAM.

## Workaround
Press sleep function key (which likely calls some systemd thing). 

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.73, NixOS, 18.09.git.3e44d2f (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by lheckemann** [comment] 2018-10-03 15:19
Does `systemctl suspend` in a terminal (as a normal user) work for you?

**Comment by coretemp** [comment] 2018-10-03 16:19
It does.

**Comment by lheckemann** [comment] 2018-10-03 16:37
I guess that narrows it down to being a plasma-specific issue, which unfortunately I don't really know anything about.

**Comment by peterhoeg** [comment] 2018-10-04 07:06
FWIW, that works fine on unstable.

**Comment by peterhoeg** [comment] 2018-10-07 04:42
This has nothing to do with batteries - I'm using this on a desktop that I suspend every evening (and a laptop that gets suspended several times a day). I didn't do anything to enable it.

> For a good desktop experience in releases, there should be a test that makes sure that all the basics are there. Not sure how you fake the existence of a battery in a VM, but that is possible, IIRC. Longterm it's probably best to cooperate with the Plasma5 developers to make them write such tests. Is there any contact with the Plasma5 community from the NixOS side?

@ttuegel has been the one doing most of the KDE/Qt work but I have no idea to what extent he coordinates with upstream.

**Comment by ttuegel** [comment] 2018-10-08 02:16
> I have no idea to what extent he coordinates with upstream.

I do not coordinate with upstream to any extent.

**Comment by coretemp** [comment] 2018-10-16 19:20
![image](https://user-images.githubusercontent.com/34454443/47041463-1e11ae00-d189-11e8-97dc-7eadd65a0e67.png)

@ttuegel This image shows another symptom of the issue. I never disabled any startup service (nor is it possible to enable it via the UI). I don't recall doing anything in the Nix configuration to disable this.

**Comment by lheckemann** [comment] 2018-10-17 06:35
Ooh, this could be helpful! Is upower running on your system? You may need to enable it, perhaps the default or KDE's effect on the option `services.upower.enable` changed.

**Comment by coretemp** [comment] 2018-10-18 12:40
Does this help?

```
nixos-option services.upower.enable
Value:
true

Default:
false

Example:


Description:

"Whether to enable Upower, a DBus service that provides power\nmanagement support to applications.\n"

Declared by:
  "/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/hardware/upower.nix"

Defined by:
  "/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/x11/desktop-managers/plasma5.nix"
```

**Comment by lheckemann** [comment] 2018-10-18 13:02
OK no, but I did a quick search inspired by the screenshot you posted, and it looks like:
 - Plasma uses powerdevil for PM
 - powerdevil is enabled by the plasma module only if [powerManagement.enable](https://nixos.org/nixos/options.html#powermanagement.enable) is set to true. So that might be a good next thing to try…

And perhaps to have the plasma module set that option by default, if it is indeed what's missing for it to work for you.

**Comment by lheckemann** [comment] 2018-10-18 13:07
Update: no, that probably won't be it since powerManagement.enable defaults to true anyway. Is powerdevil running? `pgrep -a org_kde_powerdevil`

**Comment by coretemp** [comment] 2018-10-18 15:09
```
nixos-option powerManagement.enable 
Value:
true
<snip>
```

`pgrep -a org_kde_powerdevil` returns no output and an exit status of 1.

**Comment by lheckemann** [comment] 2018-10-18 16:05
Does `$(nix-build --no-out-link '<nixpkgs>' -A powerdevil)/lib/libexec/org_kde_powerdevil` change the situation at all or maybe spit out some useful information?

**Comment by lheckemann** [comment] 2018-10-19 11:03
That's odd, for me it prints some stuff and just continues running:

```
QDBusArgument: read from a write-only object
QDBusArgument: read from a write-only object
QDBusArgument: read from a write-only object
kf5.kauth: Tried to start an invalid action
powerdevil: org.kde.powerdevil.discretegpuhelper.hasdualgpu failed
powerdevil: "Tried to start an invalid action"
powerdevil: Backend loaded, loading core
powerdevil: Core loaded, initializing backend
powerdevil: No outputs have backlight property
powerdevil: Xrandr not supported, trying ddc, helper
powerdevil: [DDCutilBrightness] compiled without DDC/CI support
powerdevil: Falling back to helper to get brightness
kf5.kauth: Tried to start an invalid action
powerdevil: org.kde.powerdevil.backlighthelper.brightness failed
powerdevil: "Tried to start an invalid action"
powerdevil: Backend is ready, KDE Power Management system initialized
virtual QStringList Solid::Backends::UPower::UPowerManager::allDevices()  error:  "org.freedesktop.DBus.Error.ServiceUnknown"
powerdevil: Session path: "/org/freedesktop/login1/session/_311"
powerdevil: ACTIVE SESSION PATH: "/org/freedesktop/login1/session/_311"
powerdevil: Current session is now active
powerdevil: fd passing available: true
powerdevil: systemd powersave events handling inhibited, descriptor: 17
powerdevil: systemd support initialized
powerdevil: Got a valid offer for  "DPMSControl"
powerdevil: Core is ready, registering various services on the bus...
powerdevil: Can't contact ck
powerdevil: We are now into activity  "00000000-0000-0000-0000-000000000000"
powerdevil: () ()
powerdevil: () ()
powerdevil: No batteries found, loading AC
powerdevil: Activity is not forcing a profile
powerdevil: The profile  "AC" tried to activate "DimDisplay" a non-existent action. This is usually due to an installation problem, or to a configuration problem, or simply the action is not supported
powerdevil: Handle button events action could not check for screen configuration
```

**Comment by coretemp** [comment] 2018-10-22 08:02
After a reboot and logging in to a new session of my existing user I saw a popup in the right lower corner of my screen with the message:
```
KDE Power Management System could not be initialized. The backend reported the following error: No valid Power Management backend plugins are available. A new installation might solve this problem.
Please check your system configuration 
```

**Comment by Softsapiens** [comment] 2018-11-06 23:43
+1
me too, rolling back to 18.03   :-(

**Comment by coretemp** [comment] 2018-11-14 08:49
Since I am not the only person with this issue, can this be fixed and perhaps documented as an errata?

**Comment by lheckemann** [comment] 2018-11-14 10:22
Yes, a fix would be nice. Unfortunately nobody here seems to have worked out why this is happening, let alone how to fix it, yet. Feel free to do so or find another volunteer. Likewise, a PR documenting this bug is likely to be merged if you create one.

**Comment by jcrben** [comment] 2019-01-31 05:15
These buttons both work good for me on unstable (both using the Plasma Search Bar and the menu). On 19.03pre166987.bc41317e243 (Koi). I wonder how common this bug is.

**Comment by rimmington** [comment] 2019-03-15 02:48
Could this be #24563? I ran into the same Power Management configuration disabled error, and disabling session restore + restarting the session fixed the issue.

**Comment by AluisioASG** [comment] 2019-04-12 03:23
Just hit this issue upgrading from 18.09 to 19.03. Logging into a fresh, unrestored KDE session does work.

**Comment by seqizz** [comment] 2019-04-12 11:35
Same same for 19.03, also switching to a tty with ctrl-alt-f3 and logging in as a root and running loginctl kill-user $myuser and removing /home/$myuser/.config/ksmserverrc wiped all the weirdness:
https://github.com/NixOS/nixpkgs/issues/24563#issuecomment-434022760

**Comment by JohnAZoidberg** [comment] 2020-02-16 13:40
Can anyone reproduce this issue on 19.09 or a recent unstable?

**Comment by jtojnar** [comment] 2020-08-15 00:22
Closing as stale and without feedback. Please comment with more info if you still experience this issue.

**Closed by jtojnar** 2020-08-15 00:23 UTC
Labels: 6.topic: qt/kde
