### ISSUE TITLE
Package request: protonmail-desktop

### ISSUE THREAD

**Issue by urandom2** [NixOS/nixpkgs#296556] opened 2024-03-17 01:52 UTC
**Project description**

The Proton Mail desktop app gives you the full Proton Mail and Proton Calendar experience from the convenience of your desktop.

**Metadata**

* homepage URL: https://proton.me/support/mail-desktop-app
* source URL: https://github.com/ProtonMail/inbox-desktop
* license: gpl3.0: https://github.com/ProtonMail/inbox-desktop/blob/main/LICENSE
* platforms: linux ([deb](https://proton.me/download/mail/linux/ProtonMail-desktop-beta.deb) [rpm](https://proton.me/download/mail/linux/ProtonMail-desktop-beta.rpm)), [darwin](https://proton.me/download/mail/macos/ProtonMail-desktop.dmg)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment] 2024-03-17 03:08
Duplicate of https://github.com/NixOS/nixpkgs/issues/296107

**Closed by donovanglover** 2024-03-17 03:08 UTC
Labels: 0.kind: packaging request
