### ISSUE TITLE
request for packaging lunarvim

### ISSUE THREAD

**Issue by jackyliu16** [NixOS/nixpkgs#215251] opened 2023-02-08 04:50 UTC
**Project description**
An improved version of neovim out of the box

**Metadata**

* homepage URL:https://www.lunarvim.org/
* source URL:https://github.com/LunarVim/LunarVim
* license:  GPL-3.0 license
* platforms: unix, linux, darwin, ...

**Comment by pinn3** [comment] 2023-02-08 12:26
Duplicate of https://github.com/NixOS/nixpkgs/issues/178488

**Comment by siph** [comment] 2023-02-15 09:39
Closed as duplicate.

**Closed by siph** 2023-02-15 09:39 UTC
Labels: 0.kind: packaging request
