### ISSUE TITLE
initrd ipv6 support broken in 19.03

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#56822] opened 2019-03-04 13:48 UTC
## Issue description

On 19.03 IPv6 addresses cannot be configured within initrd, this is a regression from 18.09. The reponse from `ip addr add` is 

> Operation not supported

### Steps to reproduce

Add `"ipv6"` to `boot.inird.availableKernelModules`.

Enable initrd networking and configure IPv6 addresses in `postCommands`.

```nix
{
  boot.initrd = {
    network = {
      enable = true;
      postCommands = "
        ${pkgs.iproute}/bin/ip addr add 2001:db8::1/64 dev eth0
        ${pkgs.iproute}/bin/ip route add default via fe80::1 dev eth0
      ";
    };
  };
}
```

## Technical details

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.104, NixOS, 19.03.git.dcb55ff (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03.170684.07e2b59812d, nixos-unstable-19.09pre170705.1233c8d9e9b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by primeos** [comment] 2019-03-06 19:01
I can confirm this bug. The problem is that the `ipv6` module is not actually loaded. It works with `boot.initrd.kernelModules = [ "ipv6" ];`.

The regression is either in `boot.inird.availableKernelModules` or `iproute2` (assuming `iproute2` has to request that the `ipv6` module will be loaded - unfortunately I do not know how this mechanism works).

**Comment by primeos** [comment] 2019-03-27 11:09
@mweinelt I just tested this on 18.09 but it did not work either (the `ipv6` module was loaded by neither NixOS nor iproute2 and I got the `Operation not supported` error). Are you sure that you did not change anything else?

**Comment by primeos** [comment] 2019-04-08 19:52
I'll close this for now because I could not get it to work on `18.09`, but it might e.g. be a regression in another NixOS module. Feel free to re-open it, but we'd probably need some more information to analyze this.

**Closed by primeos** 2019-04-08 19:52 UTC
