### ISSUE TITLE
imhex doesn't work on wayland

### ISSUE THREAD

**Issue by upidapi** [NixOS/nixpkgs#312970] opened 2024-05-19 19:28 UTC
Running imhex on wayland causes it to instantly crash

### Terminal output:
```
[nix-shell:~]$ imhex
[21:16:04] [INFO]  [main | Main]               Welcome to ImHex 1.33.2!
[21:16:04] [INFO]  [main | Main]               Compiled using commit Unknown@Unknown
[21:16:04] [INFO]  [main | Main]               Running on Linux 6.6.30 #1-NixOS SMP PREEMPT_DYNAMIC Thu May  2 14:32:50 UTC 2024 (x86_64)
[21:16:04] [FATAL] [main | Main]               Failed to initialize GLFW!
```

### Steps To Reproduce
1. nix-shell -p imhex
2. imhex

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.30, NixOS, 24.05 (Uakari), 24.05.20240515.33d1e75`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/0qd773b63yg8435w8hpm13zqz7iipcbs-source`
```

@kashw2 @cafkafk

**Comment by cafkafk** [comment] 2024-05-20 04:00
Thanks for the report, this is a duplicate of #309532, you can follow any progress there :)

**Closed by cafkafk** 2024-05-20 04:00 UTC
Labels: 0.kind: bug
