### ISSUE TITLE
Apps built with Qt 5.3 can locate Qt 5.4 files from QML2_IMPORT_PATH and fail to start

### ISSUE THREAD

**Issue by dezgeg** [NixOS/nixpkgs#7457] opened 2015-04-19 06:31 UTC
Launching `cool-retro-term` on my machine produces this error:

```
QQmlApplicationEngine failed to load component
qrc:/main.qml:21 a component declaration requires two or three arguments, but 1 were provided
```

I discovered that unsetting `QML2_IMPORT_PATH` provided by the standard NixOS environment causes the app to start correctly. The problematic directory in `QML2_IMPORT_PATH` seems to be `/run/current-system/sw/lib/qt5/qml`:

````
[tmtynkky@nixvm:~]$ ls -la /run/current-system/sw/lib/qt5/qml
total 56
dr-xr-xr-x 2 root nixbld 4096 Jan  1  1970 .
dr-xr-xr-x 4 root nixbld 4096 Jan  1  1970 ..
lrwxrwxrwx 1 root nixbld   71 Jan  1  1970 org -> /nix/store/gc59rgcl882vv5p3jpz9188pnha3vf7l-solid-5.7.0/lib/qt5/qml/org
lrwxrwxrwx 1 root nixbld   78 Jan  1  1970 Qt -> /nix/store/9xkk61fnkg3rz8z6fabdls7zzznlzvr3-qtdeclarative-5.4.0/lib/qt5/qml/Qt
lrwxrwxrwx 1 root nixbld   99 Jan  1  1970 QtGraphicalEffects -> /nix/store/f9z1z7knvdjcv22cnzsrbqbq6wzsjiag-qtgraphicaleffects-5.4.0/lib/qt5/qml/QtGraphicalEffects
lrwxrwxrwx 1 root nixbld   83 Jan  1  1970 QtLocation -> /nix/store/iv3drl40s3hd70l7fpw1nqrn3fksqab1-qtlocation-5.4.0/lib/qt5/qml/QtLocation
lrwxrwxrwx 1 root nixbld   87 Jan  1  1970 QtMultimedia -> /nix/store/qx20dqwhydvncxc0xh8hzf7j1an6zryn-qtmultimedia-5.4.0/lib/qt5/qml/QtMultimedia
lrwxrwxrwx 1 root nixbld   86 Jan  1  1970 QtPositioning -> /nix/store/iv3drl40s3hd70l7fpw1nqrn3fksqab1-qtlocation-5.4.0/lib/qt5/qml/QtPositioning
lrwxrwxrwx 1 root nixbld   81 Jan  1  1970 QtQml -> /nix/store/9xkk61fnkg3rz8z6fabdls7zzznlzvr3-qtdeclarative-5.4.0/lib/qt5/qml/QtQml
lrwxrwxrwx 1 root nixbld   83 Jan  1  1970 QtQuick -> /nix/store/9xkk61fnkg3rz8z6fabdls7zzznlzvr3-qtdeclarative-5.4.0/lib/qt5/qml/QtQuick
lrwxrwxrwx 1 root nixbld   85 Jan  1  1970 QtQuick.2 -> /nix/store/9xkk61fnkg3rz8z6fabdls7zzznlzvr3-qtdeclarative-5.4.0/lib/qt5/qml/QtQuick.2
lrwxrwxrwx 1 root nixbld   81 Jan  1  1970 QtSensors -> /nix/store/4fydd31wappvwjj12yvraxi7mkpha09c-qtsensors-5.4.0/lib/qt5/qml/QtSensors
lrwxrwxrwx 1 root nixbld   82 Jan  1  1970 QtTest -> /nix/store/9xkk61fnkg3rz8z6fabdls7zzznlzvr3-qtdeclarative-5.4.0/lib/qt5/qml/QtTest
lrwxrwxrwx 1 root nixbld   79 Jan  1  1970 QtWebKit -> /nix/store/pw4lcxdrysy9b7rz3w4yk19gmah7a3dl-qtwebkit-5.4.0/lib/qt5/qml/QtWebKit
````

Those are all Qt 5.4 components, wheras `cool-retro-term` itself links against Qt 5.3:

````
[tmtynkky@nixvm:~]$ ldd /nix/store/0a3d8by27lp7761sa4nbgsw20mmm3g0d-cool-retro-term-1.0.0/bin/.cool-retro-term-wrapped  | grep -i qt
        libQt5Quick.so.5 => /nix/store/ygkk31wps56pvayzlj904h34lpdjng81-qt-5.3.2/lib/libQt5Quick.so.5 (0xb73a7000)
        libQt5Qml.so.5 => /nix/store/ygkk31wps56pvayzlj904h34lpdjng81-qt-5.3.2/lib/libQt5Qml.so.5 (0xb6fcc000)
        libQt5Widgets.so.5 => /nix/store/ygkk31wps56pvayzlj904h34lpdjng81-qt-5.3.2/lib/libQt5Widgets.so.5 (0xb69db000)
        libQt5Sql.so.5 => /nix/store/ygkk31wps56pvayzlj904h34lpdjng81-qt-5.3.2/lib/libQt5Sql.so.5 (0xb699d000)
        libQt5Network.so.5 => /nix/store/ygkk31wps56pvayzlj904h34lpdjng81-qt-5.3.2/lib/libQt5Network.so.5 (0xb684c000)
        libQt5Gui.so.5 => /nix/store/ygkk31wps56pvayzlj904h34lpdjng81-qt-5.3.2/lib/libQt5Gui.so.5 (0xb633b000)
        libQt5Core.so.5 => /nix/store/ygkk31wps56pvayzlj904h34lpdjng81-qt-5.3.2/lib/libQt5Core.so.5 (0xb5e1d000)
````

So it looks like `cool-retro-term` is failing due to loading Qt 5.4 libraries from QML2_IMPORT_PATH when it itself is linked against Qt 5.3

**Comment by ttuegel** [comment] 2015-04-24 23:43
This is fixed in staging. The root of the issue is that we really must not have different versions of Qt 5 on the system, period. If applications are going to pin themselves to old versions of Qt 5, they need to wrap themselves for paths.

**Closed by ttuegel** 2015-04-24 23:43 UTC
