### ISSUE TITLE
Package request: niri

### ISSUE THREAD

**Issue by etrigan63** [NixOS/nixpkgs#286358] opened 2024-02-04 20:23 UTC
**Project description**

A scrollable-tiling Wayland compositor.

**Metadata**

* homepage URL: https://github.com/YaLTeR/niri
* source URL: https://github.com/YaLTeR/niri
* license: gpl3
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by etrigan63** [comment] 2024-02-04 20:25
They have a nix flake available, but I think a proper package should be built. No, I don't know how to do that and I find most Nix docs impenetrable. I always get someone to give me the Cliff Notes version.

**Comment by pinn3** [comment] 2024-02-04 21:24
Duplicate of https://github.com/NixOS/nixpkgs/issues/262804

**Closed** 2024-02-04 23:29 UTC
Labels: 0.kind: packaging request
