### ISSUE TITLE
Build failure: entangle

### ISSUE THREAD

**Issue by alex-robbins** [NixOS/nixpkgs#221918] opened 2023-03-18 23:21 UTC
### Steps To Reproduce

1. build a system with entangle installed

### Build log

```
error: builder for '/nix/store/rcvxs7aihh4fcx47cjk36vr5pgi11syp-entangle-3.0.drv' failed with exit code 1;
       last 10 log lines:
       > Run-time dependency gdk-pixbuf-2.0 found: NO
       >
       > meson.build:38:0: ERROR: Dependency lookup for gdk-pixbuf-2.0 with method 'pkgconfig' failed: Could not generate cargs for gdk-pixbuf-2.0:
       > Package libdeflate was not found in the pkg-config search path.
       > Perhaps you should add the directory containing `libdeflate.pc'
       > to the PKG_CONFIG_PATH environment variable
       > Package 'libdeflate', required by 'libtiff-4', not found
       >
       >
       > A full log can be found at /build/source/build/meson-logs/meson-log.txt
       For full logs, run 'nix log /nix/store/rcvxs7aihh4fcx47cjk36vr5pgi11syp-entangle-3.0.drv'.
```

### Additional context

Possibly related to #216181?

### Notify maintainers

@ShamrockLee 

### Metadata

Using nixpkgs commit 7067edc68c0

**Comment by ShamrockLee** [comment] 2023-03-22 10:58
This is caused by libdeflate moving toward CMake build and providing `.pc` output, and `pkg-config` expecting `libdeflate` alongside `libtiff`. It therefore should be fixed at the `libtiff` side by propagating `libdeflate` using the `propagateBuildInputs`.

As fixes on the `libtiff` build triggers mass rebuilds, I put the PR on the `staging` branch, and it would take a while (a month maybe) to go into nixos-unstable after being merged. Before that, you can workaround this issue by using
```nix
entangle.overrideAttrs (prevAttrs: { buildInputs = prevAttrs.buildInputs ++ [ libdeflate ]; })
```
as `entangle`.

Here is a nice PR tracker:
https://nixpk.gs/pr-tracker.html?pr=222518

**Comment by ShamrockLee** [comment] 2023-06-02 14:25
Entangle now builds on channel `nixos-23.05` and `nixos-unstable`, please take a look. We can close this issue after making sure it's resolved.

**Closed** 2023-12-19 10:49 UTC
Labels: 0.kind: build failure
