### ISSUE TITLE
WebCord

### ISSUE THREAD

**Issue by huantianad** [NixOS/nixpkgs#183061] opened 2022-07-27 05:05 UTC
**Project description**
Alternate Discord and Fosscord client made to be private, secure, customizable, and Linux friendly.

**Metadata**

* homepage URL: https://github.com/SpacingBat3/WebCord
* source URL: https://github.com/SpacingBat3/WebCord
* license: MIT
* platforms: x86_64 and aarch64 on linux, darwin, windows

**Comment by epetousis** [comment] 2022-09-12 14:47
I had a shot at trying to package this from source, but it seems that for whatever reason, the nixpkgs' Electron crashes with SIGTRAP when trying to run with source. I haven't had much luck using `strace` on Electron to find a root cause either. Might end up having to be an AppImage-based derivation.

**Comment by huantianad** [comment] 2022-09-12 23:57
I don't think the appimage will have much difference, but I've also gotten the same error. There is now a [flake](https://github.com/fufexan/webcord-flake) that uses dream2nix to package it properly

**Comment by epetousis** [comment] 2022-10-23 05:51
I made a derivation that doesn't use dream2nix, and it's available at https://github.com/epetousis/dotfiles/tree/main/overlays/webcord. The SIGTRAP issue was just a bad Electron version, from what I could tell. I haven't submitted this to nixpkgs yet purely because I want #189539 merged first.

**Comment by huantianad** [comment] 2022-10-23 19:20
Ah it would make sense for the SIGTRAP to be an electron version issue, I've had it on a few other electron apps too.

Your derivation looks pretty good, might try it out. Wonder how long it will take the pr you mentioned to be finished tho

**Comment by epetousis** [comment] 2022-10-24 01:58
The PR has been marked as a blocker for 22.11, so at the very latest, end of November. May be an excessive amount of time to wait, though.

**Comment by huantianad** [comment] 2022-11-26 19:55
Now that `buildNpmPackage` is mostly done and merged, I've used it to make a nice and simple derivation for it: https://github.com/huantianad/nixos-config/blob/main/packages/webcord.nix

**Comment by epetousis** [comment] 2022-11-28 04:20
Looks great. Not sure if you're planning on submitting this to nixpkgs, but if you are it might be worth adding arm64 support as well.

**Comment by huantianad** [comment] 2022-11-28 04:36
Yeah it would be nice to get this to work on aarch64 and/or darwin too, but I don’t have any devices to test it on. Can you help with this? The package might already even work on arm since we're just wrapping nixpkgs electron.

I’m also down to put this on nixpkgs, might wanna do a bit more testing and tweaking; if you can see any places for improvement that'd be great!

**Comment by TheArcaneBrony** [comment] 2022-12-09 11:29
is there anything that would stop this package from running on i686?

**Closed** 2023-01-26 21:12 UTC
Labels: 0.kind: packaging request
