### ISSUE TITLE
Motrix

### ISSUE THREAD

**Issue by chengen12** [NixOS/nixpkgs#182977] opened 2022-07-26 14:02 UTC
**Project description**:  A full-featured download manager
_describe the project a little_:  it is a download manager that Support downloading HTTP, FTP, BitTorrent, Magnet, etc. I think it is a substitute for idm. You know, idm can only run on windows

**Metadata**

* homepage URL: https://motrix.app/
* source URL: https://github.com/agalwood/Motrix
* license: mit, bsd, gpl2+ , ... :  The MIT License
* platforms: unix, linux, darwin, ...  it provide opensource for linux , window, macos

**Comment by fabaff** [comment] 2022-07-29 19:12
Duplicate of #157984

**Comment by zendo** [comment] 2022-11-29 00:58
https://github.com/NixOS/nixpkgs/pull/185804

**Comment by oluceps** [comment] 2022-11-29 06:09
#185804 Merged.

**Closed by oluceps** 2022-11-29 06:09 UTC
Labels: 0.kind: packaging request
