### ISSUE TITLE
nix-prefetch-url cannot be called in buildPhase

### ISSUE THREAD

**Issue by dingxiangfei2009** [NixOS/nixpkgs#43093] opened 2018-07-06 02:03 UTC
## Issue description
`nix-prefetch-url` when called in `buildPhase` of `mkDerivation`, exits with the following error:

```
cannot open connection to remote store 'daemon': reading from file: Connection reset by peer
```

Either the documentation should be updated with notes on forbidding `nix-prefetch-url` calls in `nix-build`, or this is an unexpected result.

### Steps to reproduce

Not reproducible on `macos`, but on `NixOS 18.03`.
Call `nix-build` on the following `default.nix`:

```nix
with import <nixpkgs> { };
stdenv.mkDerivation {
  name = "test";
  src = ./.;
  buildInputs = [nix cacert];
  buildPhase = ''
    nix-prefetch-url https://www.google.com --name abc
  '';
  installPhase = ''
  mkdir -p $out
  '';
}
```

## Technical details

`nix-shell -p nix-info --run "nix-info -m"`:

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.51, NixOS, 18.03.132768.94d80eb7247 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by peterhoeg** [comment] 2018-07-06 03:43
The build users to not have access to connect to nix-daemon so the behaviour you are seeing is expected and all inputs are expected to be available *before* the build starts so you are not supposed to be fetching things in the build phase.

Additionally, when building with the sandbox enabled there is no network connectivity at all.

Any thoughts on how to improve the documentation?

**Comment by dingxiangfei2009** [comment] 2018-07-06 03:50
Then this is very strange that this script works in macos Nix setup.

**Comment by peterhoeg** [comment] 2018-07-06 03:57
I am assuming this has to do with single vs multi-user nix mode. In multi-user mode the nix-daemon will spawn the builds using the build users (which cannot connect back to nix-daemon) but on macOS, the builds are (presumably) running as the current user (which can connect).

**Comment by dingxiangfei2009** [comment] 2018-07-06 04:08
So, should we fix this by stopping `nix-prefetch-url` from running if a build is in the progress?

**Comment by peterhoeg** [comment] 2018-07-06 04:37
There really isn't anything to fix (apart from possibly the documentation) - this is all expected behaviour.

**Comment by peterhoeg** [comment] 2018-07-06 05:53
But it has nothing to with ```nix-prefetch-url``` as such. If you can ```sudo``` on your machine, you would be able to ```sudo``` as part of a single-user build, but it will fail in a ```multi-user``` build. Different environments will by definition allow you to do different things. That why the "gold standard" is sandboxed, multi-user builds on NixOS but even it works there, you might still need to tweak the build for building on macOS due to system-level libraries "polluting" the macOS build.

**Comment by peterhoeg** [comment] 2018-07-08 12:40
I'm closing this as it isn't actually an issue.

**Closed by peterhoeg** 2018-07-08 12:40 UTC
