### ISSUE TITLE
aspell cannot find installed dictionaries when using nix-shell

### ISSUE THREAD

**Issue by yegle** [NixOS/nixpkgs#34308] opened 2018-01-26 23:08 UTC
## Issue description

```
$ nix-shell -p aspell aspellDicts.en

[nix-shell:~]$ aspell dump dicts
<no result>
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.0-5-amd64, Debian GNU/Linux, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(ych): `"nixpkgs-18.03pre126020.931a0b8be80"`
 - nixpkgs: `$HOME/.nix-defexpr/channels/nixpkgs`

**Comment by FRidh** [comment] 2018-01-28 13:13
By default `aspell` searches only in `NIX_PROFILES`, and not in derivations that are added in`nix-shell`. The following is supported though:
```
nix-shell -p aspellWithDicts(ps: [ ps.en ])
```

**Comment by bjornfor** [comment] 2018-01-28 15:40
I wonder how difficult it would be to teach nix-shell to set up NIX_PROFILES.

**Comment by FRidh** [comment] 2018-01-28 15:44
That is, make the contents of the `nix-shell` available as a profile?

**Comment by bjornfor** [comment] 2018-01-28 20:35
Yes. nix-shell could create one "profile directory" in the nix store, linking all deps into this dir (FHS style) and add it to NIX_PROFILES. Tools running inside this shell can then iterate over NIX_PROFILES.

**Comment by FRidh** [comment] 2018-01-29 17:23
That would be a large change to the functionality of `nix-shell` and/or `nix run`. Creating that directory could be done with `buildEnv`. However, merging parts into a new derivation is typically not enough as wrappers may need to be updated as well. Anyway, it's out of scope of this issue.

**Comment by yegle** [comment] 2018-01-30 00:12
Hmm, I was actually asking an [XY problem](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem). The actual problem I have is that weechat cannot find aspell dicttionaries: `/aspell listdicts` gave empty result.

I was using the following `shell.nix` file:
```
with import <nixpkgs> {};

let
  aspell_with_dict = aspellWithDicts(ps: [ps.en]);
in
stdenv.mkDerivation rec {
  name = "my-shell";
  env = buildEnv {
    name = name;
    paths = buildInputs;
  };
  buildInputs = [
    aspell_with_dict
    weechat
    python
  ];
}
```

**Comment by expipiplus1** [comment] 2018-04-02 13:11
@yegle Did you find a solution to getting aspell working with weechat?

**Comment by yegle** [comment] 2018-04-02 18:23
@expipiplus1 No, weechat still cannot find aspell dicts.

One attempted workaround was to add `dict-dir path/to/my/dicts/directory` to `~/.aspell.conf`. After that, when I run `strace aspell dump dicts` I can see it does read `~/.aspell.conf` but there's no attempt to open `path/to/my/dicts/directory`. I'm not familiar with `aspell` to debug further.

**Comment by expipiplus1** [comment] 2018-04-03 02:11
I managed to get it working with both enchant and aspell yesterday. It's
not the nicest solution as it involves patching weechat. I'll upload my nix
expression tonight and think about getting something merged upstream.

**Comment by expipiplus1** [comment] 2018-04-03 13:37
@yegle please see https://github.com/NixOS/nixpkgs/pull/38393

If you could try it out and see if it works for you that would be really helpful!

**Comment by yegle** [comment] 2018-05-15 20:17
@expipiplus1 

I'm not very familiar with how nix works so not sure how i can test out #38393. But for some reason weechat does spell check now.

I'm using https://github.com/yegle/dotfiles/blob/master/nix/shell.nix in case someone else find it useful.

**Comment by lasers** [comment] 2021-01-29 23:30
Please revisit this again.

```
~ ❯ nix-shell -p aspell aspellDicts.en

[nix-shell:~]$ aspell dump dicts
en
en-variant_0
en-variant_1
...
...

[nix-shell:~]$ aspell dump dicts | wc -l
32
```

**Comment by piegamesde** [comment] 2021-01-30 10:25
@lasers If you have `aspell` dictionaries installed in your environment, please try again with `--pure`.

**Comment by lasers** [comment] 2021-01-30 10:46
@piegamesde Ah I see. Thank you.
```
~ ❯ nix-shell -p aspell aspellDicts.en --pure

[nix-shell:~]$ 
```

**Comment by piegamesde** [comment] 2021-07-30 11:02
To be honest I'm in favor of closing this as "wontfix; works as intended". We have `aspellWithDicts`, this is the same mechanism we have for Python (`python3.withPackages`) and I wouldn't consider that a bug either.

**Closed** 2021-08-09 09:28 UTC

**Comment by alkeryn** [comment] 2023-03-31 13:45
@piegamesde it's a old thread but there is still no way of making aspell work from a nix-shell for developpement, we have to install it with nix-env which isn't practical imo.

**Comment by aschleck** [comment] 2023-09-04 17:00
@alkeryn I may be misunderstanding you but here's a `default.nix` that works for me:
```
{ pkgs ? import <nixpkgs> {} }:

let
  aspellWithEn = pkgs.aspellWithDicts(ps: [ps.en]);
in
pkgs.mkShell {
  nativeBuildInputs = with pkgs.buildPackages; [ aspellWithEn ];
}
```

**Comment by ALameLlama** [comment] 2025-07-30 12:03
I know this is an old thread but I tried to install multiple languages inside of a nix shell
```
            (aspellWithDicts (
              dicts: with dicts; [
                en
                en-computers
                en-science
              ]
            ))
```

and when I run `aspell dump dicts` I get a bunch of it's missing en-computers and en-science

```
aspell -a --lang=en
Error: The file "/nix/store/iirjzkidw12rk4w3xjifymb48k0mkykz-aspell-env/lib/aspell/en-computers" can not be opened for reading.
(nix:nix-shell-env)
```
