### ISSUE TITLE
Stretchly is out of date

### ISSUE THREAD

**Issue by Coda-Coda** [NixOS/nixpkgs#119283] opened 2021-04-13 03:19 UTC
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: stretchly

current version: 1.2.0
desired version: 1.5.0

###### Notify maintainers

maintainers: @1000101 

###### Note for maintainers

I have tried to update this myself by simply changing the version number and hash, but I get the following error on running `stretchly`:
```bash
App threw an error during load
Error: No such module was linked: electron_common_v8_util
    at process._linkedBinding (internal/bootstrap/loaders.js:118:34)
    at Object.getElectronBinding (/nix/store/6pw7n55am9y1d2z5wg758cmklr2cicbj-stretchly-1.5.0/share/stretchly/app.asar/node_modules/@electron/remote/dist/src/common/get-electron-binding.js:6:24)
    at Object.<anonymous> (/nix/store/6pw7n55am9y1d2z5wg758cmklr2cicbj-stretchly-1.5.0/share/stretchly/app.asar/node_modules/@electron/remote/dist/src/main/server.js:12:39)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
15:16:16.683 › Error: No such module was linked: electron_common_v8_util
    at process._linkedBinding (internal/bootstrap/loaders.js:118:34)
    at Object.getElectronBinding (/nix/store/6pw7n55am9y1d2z5wg758cmklr2cicbj-stretchly-1.5.0/share/stretchly/app.asar/node_modules/@electron/remote/dist/src/common/get-electron-binding.js:6:24)
    at Object.<anonymous> (/nix/store/6pw7n55am9y1d2z5wg758cmklr2cicbj-stretchly-1.5.0/share/stretchly/app.asar/node_modules/@electron/remote/dist/src/main/server.js:12:39)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
electron/js2c/browser_init.js:846
    throw new Error('dialog module can only be used after app is ready');
    ^

Error: dialog module can only be used after app is ready
    at checkAppInitialized (electron/js2c/browser_init.js:846:11)
    at messageBox (electron/js2c/browser_init.js:935:3)
    at Object.showMessageBox (electron/js2c/browser_init.js:1029:12)
    at process.<anonymous> (/nix/store/6pw7n55am9y1d2z5wg758cmklr2cicbj-stretchly-1.5.0/share/stretchly/app.asar/main.js:15:10)
    at process.emit (events.js:215:7)
    at process._fatalException (internal/process/execution.js:150:25)
```

There have been various updates to stretchly between 1.2.0 and 1.5.0 (e.g. one minor but annoying issue fixed after 1.2.0 is described at https://github.com/hovancik/stretchly/issues/777)

Please tag this issue in your PR.

**Comment by Coda-Coda** [comment] 2021-04-14 04:27
Thanks 🙂, works for me. Nice to see how few changes are needed to make it work. Thanks for the quick response!

**Comment by Coda-Coda** [comment] 2021-04-14 04:51
@1000101 Thanks for the help so far, but actually, it still doesn't quite work as expected 🙁
The main issue is that the icon doesn't appear anymore (the Stretchly UI is missing).
This might be related to https://github.com/hovancik/stretchly/issues/849 and `libappindicator`. I am not sure.
A .electron-wrapp process does appear to stay running after running `stretchly`.

It would be nice to have this fixed please - but no pressure, it's really not critical 🙂
I've tried a bit myself, but am mostly making wild guesses, happy to learn from what you might do though.

If I run `stretchly` I now get the following:
```bash
$ stretchly 
Stretchly command instance: started

Error: command /nix/store/dgkyb9r0f4qckh2l7gfrb7hb5drrc4gb-stretchly-1.5.0/share/stretchly/app.asar is not supported
Forwarding command to main instance
16:33:13.568 › Stretchly: loading settings
16:33:13.574 › Stretchly: starting Idle time monitoring
16:33:13.575 › Stretchly: starting DND monitoring
(node:4732) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
```

**Comment by 1000101** [comment] 2021-04-14 11:47
> @1000101 Thanks for the help so far, but actually, it still doesn't quite work as expected slightly_frowning_face
> The main issue is that the icon doesn't appear anymore (the Stretchly UI is missing).
> This might be related to [hovancik/stretchly#849](https://github.com/hovancik/stretchly/issues/849) and `libappindicator`. I am not sure.
> A .electron-wrapp process does appear to stay running after running `stretchly`.
> 
> It would be nice to have this fixed please - but no pressure, it's really not critical slightly_smiling_face
> I've tried a bit myself, but am mostly making wild guesses, happy to learn from what you might do though.
> 
> If I run `stretchly` I now get the following:
> 
> ```shell
> $ stretchly 
> Stretchly command instance: started
> 
> Error: command /nix/store/dgkyb9r0f4qckh2l7gfrb7hb5drrc4gb-stretchly-1.5.0/share/stretchly/app.asar is not supported
> Forwarding command to main instance
> 16:33:13.568 › Stretchly: loading settings
> 16:33:13.574 › Stretchly: starting Idle time monitoring
> 16:33:13.575 › Stretchly: starting DND monitoring
> (node:4732) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
> ```

@Coda-Coda was it working in v1.2.0? Do you use GNOME, what tray extension do you use? I've had these problems right from the start (no tray icon), but I don't use a tray extension - other than that, it's been working ok - other people reported that tray icon works fine for them, so I didn't dig any deeper than I needed to (core functionality was working and I haven't had the time).

Testing both old and new versions with https://search.nixos.org/packages?channel=20.09&from=0&size=50&sort=relevance&query=gnomeExtensions.appindicator seems to work fine.

So, does this sound familiar? Is this the problem you're currently facing (stretchly running, no tray icon / UI available)? 
What about running `rm -rf ~/.config/Stretchly/` ?

**Comment by Coda-Coda** [comment] 2021-04-15 01:20
Firstly, thanks for your help on this relatively minor issue 🙂

> @Coda-Coda was it working in v1.2.0? 

Yes, the tray icon and associated UI work for me in v1.2.0

> Do you use GNOME, what tray extension do you use?

Yes, I'm using GNOME 3.36.5 with the defaults that come with 20.09 (which is Wayland too as far as I'm aware).
```
$ gnome-shell --version
GNOME Shell 3.36.5
```
For tray extension I use `gnomeExtensions.appindicator` (usually from nixpkgs-unstable but I also tried 20.09) and it appears in the Extensions list as "KStatusNotifierItem/AppIndicator Support".

> I've had these problems right from the start (no tray icon), but I don't use a tray extension - other than that, it's been working ok - other people reported that tray icon works fine for them, so I didn't dig any deeper than I needed to (core functionality was working and I haven't had the time).

Fair enough, though I do find it useful to be able to click "Pause Breaks" > x hours in particular. And for settings tweaks, I realise modifying the `~/.config/Stretchly/config.json` file is not too bad but the UI for some settings is nice too.

> Testing both old and new versions with https://search.nixos.org/packages?channel=20.09&from=0&size=50&sort=relevance&query=gnomeExtensions.appindicator seems to work fine.

By this ^ do you mean the icon was working with 1.5.0?
I tried the following (as I'm usually on nixpkgs-unstable) (dec334 is the HEAD of nixos-20.09 as of now):
```
let pkgsUnstablePinned = import (fetchTarball https://github.com/nixos/nixpkgs/archive/dec334fa196a4aeedb1b60d8f7d61aa00d327499.tar.gz) {}; in
home.packages = with pkgs; [
    pkgsUnstablePinned2.gnomeExtensions.appindicator # Needed for tray icons, such as for stretchly
   ...
];
```

> So, does this sound familiar? Is this the problem you're currently facing (stretchly running, no tray icon / UI available)?

Yes, stretchly is running but no tray icon is available.

> What about running `rm -rf ~/.config/Stretchly/` ?

It still does not show the icon 🙁. It does show the UI the first time it runs (to choose language etc) but after that is done and closed there is no UI or icon.

**Comment by 1000101** [comment] 2021-04-15 07:20
> Firstly, thanks for your help on this relatively minor issue slightly_smiling_face

Appreciate it :).

> Fair enough, though I do find it useful to be able to click "Pause Breaks" > x hours in particular. 

It's far from ideal and although I don't use tray, I agree that the tray icon should work as it is generally very useful for the majority of people.

> Yes, I'm using GNOME 3.36.5 with the defaults that come with 20.09 (which is Wayland too as far as I'm aware).

Huh, me too (GNOME 3.36.5 + Wayland). I'm running latest stable though 
```
 - host os: `Linux 5.4.109, NixOS, 20.09.3824.dec334fa196 (Nightingale)`
```

I've even tried the latest unstable, works fine there, too:
```
 - host os: `Linux 5.10.27, NixOS, 21.05pre282432.311ceed827f (Okapi)`
```

> By this ^ do you mean the icon was working with 1.5.0?

Yes. Using the very same extension (enabled through `Tweaks`) on stable works for me (for both 1.2.0 and 1.5.0).

> It still does not show the icon slightly_frowning_face. It does show the UI the first time it runs (to choose language etc) but after that is done and closed there is no UI or icon.

Alright, works the same for me. I thought there might have been some local differences there.

Moreover, I looked at https://github.com/hovancik/stretchly/issues/849 but building the app with `libappindicator` in `buildInputs` doesn't seem to alter the behavior and it seems that `libappindicator` is needed only for Unity (as stated in lib description).
Have you tried to build it yourself and install such version?
```
{
,stdenv
...
, libappindicator
...
stdenv.mkDerivation rec {
...
  buildInputs = [ libappindicator ];
```

I'm sorry, I've tried everything I could think about but I can't seem to reproduce the issue on current stable nor unstable.

**Comment by 1000101** [comment] 2021-04-15 08:15
Ah wait, did you say `nixpkgs-unstable` ? I've only tried latest `nixos-unstable`.

**Comment by Coda-Coda** [comment] 2021-04-16 05:58
Thanks - I can’t now but I’ll have another look next week.

**Comment by 1000101** [comment] 2021-04-16 17:36
> Thanks - I can’t now but I’ll have another look next week.

Right, I'll close this issue since Stretchly was updated (and a new version just came out https://github.com/NixOS/nixpkgs/pull/119646). Please try testing it with more stable channel or with the suggestion above. If the problems persists, please, do open a new issue and we'll try to take it from there!

**Closed by 1000101** 2021-04-16 17:36 UTC
Labels: 9.needs: package (update)

**Comment by Coda-Coda** [comment] 2021-04-20 11:41
It works 🙂. I am now on `nixpkgs-unstable` and have Stretchly 1.6.0 running with the icon and UI available.

I'm not sure what the issue I was encountering was but it is resolved now. (I just tried with 1.6.0 directly, not 1.5.0).

Thanks for your help!

**Comment by 1000101** [comment] 2021-04-20 13:18
Happy to help!
