### ISSUE TITLE
latexindent is missing dependencies

### ISSUE THREAD

**Issue by furrycatherder** [NixOS/nixpkgs#54452] opened 2019-01-22 05:04 UTC
## Issue description
```console
swim@loefah ~/d/resume> latexindent
Can't locate Log/Log4perl.pm in @INC (you may need to install the Log::Log4perl module) (@INC contains: /nix/store/xsqannmcjdya7ydp5y5g082b8cx06v0c-texlive-latexindent-3.5/scripts/latexindent /nix/store/2fj08qk4jgi7ddl4bzx072091wwpsr0a-texlive-combined-2018/share/texmf/scripts/texlive /nix/store/mbwav8kz8b3y471wjsybgzw84mrh4js9-perl-5.28.1/lib/perl5/site_perl/5.28.1/x86_64-linux-thread-multi /nix/store/mbwav8kz8b3y471wjsybgzw84mrh4js9-perl-5.28.1/lib/perl5/site_perl/5.28.1 /nix/store/mbwav8kz8b3y471wjsybgzw84mrh4js9-perl-5.28.1/lib/perl5/5.28.1/x86_64-linux-thread-multi /nix/store/mbwav8kz8b3y471wjsybgzw84mrh4js9-perl-5.28.1/lib/perl5/5.28.1) at /nix/store/xsqannmcjdya7ydp5y5g082b8cx06v0c-texlive-latexindent-3.5/scripts/latexindent/LatexIndent/LogFile.pm line 22.
BEGIN failed--compilation aborted at /nix/store/xsqannmcjdya7ydp5y5g082b8cx06v0c-texlive-latexindent-3.5/scripts/latexindent/LatexIndent/LogFile.pm line 22.
Compilation failed in require at /nix/store/xsqannmcjdya7ydp5y5g082b8cx06v0c-texlive-latexindent-3.5/scripts/latexindent/LatexIndent/Document.pm line 25.
BEGIN failed--compilation aborted at /nix/store/xsqannmcjdya7ydp5y5g082b8cx06v0c-texlive-latexindent-3.5/scripts/latexindent/LatexIndent/Document.pm line 25.
Compilation failed in require at /nix/store/xsqannmcjdya7ydp5y5g082b8cx06v0c-texlive-latexindent-3.5/scripts/latexindent/latexindent.pl line 27.
BEGIN failed--compilation aborted at /nix/store/xsqannmcjdya7ydp5y5g082b8cx06v0c-texlive-latexindent-3.5/scripts/latexindent/latexindent.pl line 27.
```

### Steps to reproduce

```
nix-shell -p "texlive.combine { inherit (texlive) scheme-minimal latexindent; }" \
  --pure --run latexindent
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.83-gentoo, Gentoo, noversion`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09.1922.97e0d53d669, nixpkgs-19.03pre166887.db8e3654e2c"`
 - channels(swim): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by veprbl** [comment] 2019-02-24 18:29
duplicate of https://github.com/NixOS/nixpkgs/issues/35537

**Closed by veprbl** 2019-02-24 18:29 UTC
Labels: 6.topic: TeX
