### ISSUE TITLE
git 2.36 installCheck uses LD_PRELOAD

### ISSUE THREAD

**Issue by wh0** [NixOS/nixpkgs#176999] opened 2022-06-09 07:25 UTC
https://github.com/git/git/commit/131b94a10a77e40eb3b3ba276d07fb663e220cd1 Git tests now try to LD_PRELOAD something from glibc >= 2.34. but on nix it can't find that file because it's not installed in the usual place. this results in a few failures such as this, in cases where the test suite checks an invocation's output:

```
'error' is not empty, it contains:
ERROR: ld.so: object 'libc_malloc_debug.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
not ok 8 - stash -p with split hunk
#	
#		git reset --hard &&
#		cat >test <<-\EOF &&
#		aaa
#		bbb
#		ccc
#		EOF
#		git add test &&
#		git commit -m "initial" &&
#		cat >test <<-\EOF &&
#		aaa
#		added line 1
#		bbb
#		added line 2
#		ccc
#		EOF
#		printf "%s\n" s n y q |
#		git stash -p 2>error &&
#		test_must_be_empty error &&
#		grep "added line 1" test &&
#		! grep "added line 2" test
#	

# failed 1 among 8 test(s)
```

### Steps To Reproduce
1. be on a computer with older glibc in the base OS :skull: 
2. disable build sandboxing :skull: :skull: 
3. try to build git-minimal

### Build log
just the excerpt of the failure:
```
t3904-stash-patch.sh ............................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/8 subtests 
t3701-add-interactive.sh ........................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 3/70 subtests 
```

### Additional context
- so like, is there a way we can rewrite that .so file reference to a nix store path? I notice that the libc_malloc_debug.so.0 file is properly included in nix's glibc release
- https://github.com/git/git/blob/9c897eef06347cc5a3eb07c3ae409970ab1052c8/t/test-lib.sh#L551 there is this flag we can set to disable this part of the testing
- I notice there's a `disable_test` system in our preInstallCheck, maybe we could disable these tests if we don't want to do either of the above

### Notify maintainers

@primeos @wmertens @globin , if I may

### Metadata
this env is too weird and I'm not allowed to have a copy of nixpkgs due to mentions of ethminer :skull: so I can't even run this command, sorry folks

```console
$ nix-shell -p nix-info --run "nix-info -m"
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I), at (string):1:13
```

I'm using nix as a package manager on Ubuntu (very old; thus the OS's own glibc doesn't have a libc_malloc_debug.so.0), using nixos-22.05 channel; custom store dir so everything is being built from source; sandboxing not working due to lack of permissions

**Comment by abathur** [comment] 2023-05-28 21:56
@primeos @wmertens @globin I'm closing this as a wontfix since the same failures were reported in #174934 and @primeos didn't seem to think that one was actionable--but I'm hoping one of you can object if you think I'm drawing the wrong conclusion. Happy to reopen if anyone yells.

In case it helps, while evaluating this I confirmed:
- the code introduced in the commit the OP linked is still there present upstream
- we haven't already disabled `t3701` or `t3904`

**Closed by abathur** 2023-05-28 21:56 UTC
Labels: 0.kind: build failure

**Comment by wh0** [comment] 2023-05-29 12:05
I just realized I didn't encounter this in the latest build of git from nixpkgs. I'm looking at the updated test-lib.sh, but I don't see anything that would change the behavior. but closing would be fine with me, thanks.
