### ISSUE TITLE
Build failure: python312Packages.tree-sitter-languages

### ISSUE THREAD

**Issue by thistlehog** [NixOS/nixpkgs#331260] opened 2024-07-31 10:57 UTC
### Steps To Reproduce

1. build `python312Packages.tree-sitter-languages`

### Build log

```
building the system configuration...
error:
       … while calling the 'head' builtin

         at /nix/store/xblysc3prg1zqsi59fr36nj6wdiqryzp-source/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'

         at /nix/store/xblysc3prg1zqsi59fr36nj6wdiqryzp-source/lib/modules.nix:821:9:

          820|     in warnDeprecation opt //
          821|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          822|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: tree-sitter0_21-0.21.3 not supported for interpreter python3.12
```

### Additional context

Originally found building `python312Packages.textual`

### Notify maintainers

@doronbehar

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.0, NixOS, 24.11 (Vicuna), 24.11.20240725.5ad6a14`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/xblysc3prg1zqsi59fr36nj6wdiqryzp-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by doronbehar** [comment] 2024-08-01 08:01
That's not a build failure, but an evaluation failure. If you want to make `textual` not depend on `tree-sitter0_21`, you need to figure out where does this dependency comes from, and try to remove it. The reason we disabled `tree-sitter0_21` is documented in the code:

https://github.com/NixOS/nixpkgs/blob/a4b56f9941b41ab6520767823dea941b6b9162eb/pkgs/development/python-modules/tree-sitter0_21/default.nix#L16-L17

Note that although the issue is fixed, we intentionally provide an expression for `tree-sitter0_21`, so that we can build `tree-sitter-languages` with it. See also:

https://github.com/NixOS/nixpkgs/blob/a4b56f9941b41ab6520767823dea941b6b9162eb/pkgs/development/python-modules/tree-sitter-languages/default.nix#L40-L43

You can work around this issue by using `python311Packages` instead, or try to be creative and make `python312Packages.tree-sitter-languages` depend on the latest `tree-sitter` (and not `tree-sitter0_21`), by fixing the upstream issue https://github.com/grantjenks/py-tree-sitter-languages/issues/67 . Good luck!

**Comment by doronbehar** [comment] 2024-08-01 08:06
I'm closing this, as this is an upstream issue. Ideally it would have been possible to declaratively write with Nix why packages are disabled for certain Python implementation, and that would have improved the evaluation failure message you observed. I think I saw discussion about such a feature, but I can't find any links now unfortunately.

**Closed by doronbehar** 2024-08-01 08:06 UTC
Labels: 0.kind: build failure
