### ISSUE TITLE
vboxnet0.service failed

### ISSUE THREAD

**Issue by jgeerds** [NixOS/nixpkgs#6037] opened 2015-01-28 21:42 UTC
I just activated `services.virtualboxHost.enable` and had to recognize that my machine takes almost 3 minutes to start:

```
$ systemd-analyze blame
    2min 19.714s vboxnet0.service
          3.381s systemd-remount-fs.service
          1.662s systemd-udev-settle.service
          [...]
```

```
$ systemctl status -l vboxnet0.service
● vboxnet0.service - VirtualBox vboxnet0 Interface
   Loaded: loaded (/nix/store/3gvwsj2nzynp0zlcrmbkf128jd5gs39l-unit-vboxnet0.service/vboxnet0.service)
   Active: failed (Result: exit-code) since Mi 2015-01-28 22:27:10 CET; 9min ago
  Process: 1600 ExecStart=/nix/store/ady78xbk0rmaj53rpyy3h5xdf8fxci5v-unit-script/bin/vboxnet0-start (code=exited, status=1/FAILURE)
 Main PID: 1600 (code=exited, status=1/FAILURE)

Jan 28 22:27:10 moon vboxnet0-start[1600]: VBoxManage: error: Assertion failed: [SUCCEEDED(hrc)] at '/tmp/nix-build-virtualbox-4.3.20-3.18.3.drv-0/VirtualBox-4.3.20/src/VBox/Main/src-server/HostImpl.cpp' (1303) in virtual nsresult Host::CreateHostOnlyNetworkInterface(IHostNetworkInterface**, IProgress**).
Jan 28 22:27:10 moon vboxnet0-start[1600]: VBoxManage: error: COM RC = NS_ERROR_FAILURE (0x80004005).
Jan 28 22:27:10 moon vboxnet0-start[1600]: VBoxManage: error: Please contact the product vendor!
Jan 28 22:27:10 moon vboxnet0-start[1600]: VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component Host, interface IHost, callee nsISupports
Jan 28 22:27:10 moon vboxnet0-start[1600]: VBoxManage: error: Context: "CreateHostOnlyNetworkInterface (hif.asOutParam(), progress.asOutParam())" at line 62 of file VBoxManageHostonly.cpp
Jan 28 22:27:10 moon systemd[1]: vboxnet0.service: main process exited, code=exited, status=1/FAILURE
Jan 28 22:27:10 moon systemd[1]: Failed to start VirtualBox vboxnet0 Interface.
Jan 28 22:27:10 moon systemd[1]: Unit vboxnet0.service entered failed state.
Jan 28 22:27:10 moon systemd[1]: vboxnet0.service failed.
```

Any idea?

**Comment by lethalman** [comment] 2015-01-29 08:55
cc @aszlig

**Comment by geerds** [comment] 2015-02-17 21:12
Any idea @aszlig ?

**Comment by aszlig** [comment] 2015-02-17 21:44
Ah, sorry for keeping you waiting so long, I'm currently moving.
Can you post a configuration.nix where this can be reproduced? Something that can be `nix-build -E 'import <nixpkgs/nixos> { configuration = /the/config.nix }'`ed?

**Comment by geerds** [comment] 2015-02-17 22:03
No big deal.

How does such a config.nix look like? Something special?
My machine config is available [on GitHub](https://github.com/geerds/nixos-configuration/blob/master/moon.nix). Let me know if this config isn't helpful

**Comment by aszlig** [comment] 2015-02-17 22:45
okay, testing that config...

**Comment by aszlig** [comment] 2015-02-18 06:49
Okay, this will take a while longer, the connection here is **very** unstable... :-/

**Comment by aszlig** [comment] 2015-02-18 17:11
Okay, this issue is blocked on the connection issues now (without a [freifunk](http://freifunk.net/) whitelist this probably will take days), let's see if we can unblock the issue:

@mmunz: Can you please whitelist `tishtushi` for the roof AP as well (same MAC as before)? Thanks in advance :-)

**Comment by mmunz** [comment] 2015-02-18 19:59
@aszlig done, the client is now whitelisted on 10-11-0-15 aka bg23dach. if that wasn't the right roof node let me know.

**Comment by aszlig** [comment] 2015-02-19 05:04
@mmunz: Thanks a lot, the connection isn't much faster but at least it's stable now :-)

Okay, I have been able to reproduce it via:

```shell
nix-build -E 'import <nixpkgs/nixos/tests/make-test.nix> {
  machine.boot.cleanTmpDir = true;
  machine.services.virtualboxHost.enable = true;
  testScript = "$machine->waitForUnit(\"vboxnet0.service\");";
}'
```

So the `vboxnet0.service` is running `VBoxManage hostonlyif create` within a private `/tmp` namespace. Unfortunately, the tmpfiles reaper causes a race condition during that command, because it is accessing the `/tmp` directory via `VBOX_USER_HOME` and the reaper cannot properly map the VBoxManager pid (or really: pid**S**) to those files.

In order to fix this I'd ensure that the outer shell process (`script` within the service) is holding `$(mktemp -d)`, which in turn is passed to `VBOX_USER_HOME`.

@geerds: Can you please confirm that it is indeed the `boot.cleanTmpDir` option?

**Comment by geerds** [comment] 2015-02-19 17:50
@aszlig It works with disabled `boot.cleanTmpDir`! Thank you very much for your commitment :grinning:

**Comment by edolstra** [comment] 2016-01-18 10:38
Possibly a dupe of #4825.

**Comment by Profpatsch** [comment] 2018-06-23 18:07
Closing because the issue is very old and seems to depend on other issues.

**Closed by Profpatsch** 2018-06-23 18:07 UTC
Labels: 0.kind: bug
