### ISSUE TITLE
yubikey-manager fails to build

### ISSUE THREAD

**Issue by martsa1** [NixOS/nixpkgs#155110] opened 2022-01-15 13:29 UTC
### Describe the bug
Building `yubikey-manager` on nixosUnstable fails to build.

### Steps To Reproduce
1. `nix-shell --pure -p yubikey-manager`

### Expected behavior
yubikey-manager is built without issue (enabling the use of `yubioath-desktop`).

### Screenshots
```
nix --extra-experimental-features nix-command log /nix/store/aba8lahylkx7q6vj3kvwbgcx4baqkxm4-python3.9-yubikey-manager-4.0.7.drv
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing pytest-check-hook
Using pytestCheckPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/2x9dw5bin2lkl3z6w05xfls8sw1k1csb-source
source root is source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/yubikit/yubiotp.py
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
substituteStream(): WARNING: pattern '/usr/bin/pkill' doesn't match anything in file 'ykman/pcsc/__init__.py'
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Executing pipBuildPhase
Creating a wheel...
[33mWARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.[0m
Processing /build/source
  Running command /nix/store/dn4fwp0yx6nsa85cr20cwvdmg64xwmcy-python3-3.9.9/bin/python3.9 /nix/store/kq65p5y7l8zvhh7lh6bm7ihmga58pmy0-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /build/tmpujrbxac9
  Preparing metadata (pyproject.toml) ... [?25l[?25hdone
Building wheels for collected packages: yubikey-manager
  Running command /nix/store/dn4fwp0yx6nsa85cr20cwvdmg64xwmcy-python3-3.9.9/bin/python3.9 /nix/store/kq65p5y7l8zvhh7lh6bm7ihmga58pmy0-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /build/tmp891bfdxn
  Building wheel for yubikey-manager (pyproject.toml) ... [?25l[?25hdone
  Created wheel for yubikey-manager: filename=yubikey_manager-4.0.7-py3-none-any.whl size=154707 sha256=30ed01c4b05fa8678bfefe2116130dbf13d7f06a5551655050fa1ab73459d706
  Stored in directory: /build/pip-ephem-wheel-cache-k7rozfzl/wheels/4e/ad/e4/8b34a2d71a66bf6c38e937ebdd6e1b8340c5ad8008d77a009a
Successfully built yubikey-manager
Finished creating a wheel...
Finished executing pipBuildPhase
@nix { "action": "setPhase", "phase": "installPhase" }
installing
Executing pipInstallPhase
/build/source/dist /build/source
Processing ./yubikey_manager-4.0.7-py3-none-any.whl
Requirement already satisfied: pyscard<3.0,>=1.9 in /nix/store/1q2g13w5k9m48rgj0k8xrj8f22074hji-python3.9-pyscard-2.0.2/lib/python3.9/site-packages (from yubikey-manager==4.0.7) (2.0.2)
Requirement already satisfied: pyOpenSSL>=0.15.1 in /nix/store/kxm0wp6x06bv3six4vfjh46lz1jnwasd-python3.9-pyopenssl-20.0.1/lib/python3.9/site-packages (from yubikey-manager==4.0.7) (20.0.1)
Requirement already satisfied: click<9.0,>=6.0 in /nix/store/nckfzfxmw7ywdzzsp1h06w8k94ryc7m5-python3.9-click-8.0.3/lib/python3.9/site-packages (from yubikey-manager==4.0.7) (8.0.3)
[31mERROR: Could not find a version that satisfies the requirement cryptography<4.0,>=2.1 (from yubikey-manager) (from versions: none)[0m
[31mERROR: No matching distribution found for cryptography<4.0,>=2.1[0m

```

### Notify maintainers
@benley @lassulus @pinpox

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.11, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(sam): `"home-manager"`
 - channels(root): `"nixos-22.05pre345234.b2737d4980a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Lassulus** [comment] 2022-01-15 13:40
duplicate of https://github.com/NixOS/nixpkgs/issues/154673

**Comment by Lassulus** [comment] 2022-01-15 13:40
will be fixed when the channel finally progresses

**Closed by Lassulus** 2022-01-15 13:40 UTC
Labels: 0.kind: bug, 6.topic: python

**Comment by martsa1** [comment] 2022-01-15 15:47
Ah! Apologies for missing the existing ticket.
