### ISSUE TITLE
Question: Is it possible to sign packages with cosign?

### ISSUE THREAD

**Issue by developer-guy** [NixOS/nixpkgs#221031] opened 2023-03-13 18:02 UTC
## Issue description

[cosign](https://github.com/sigstore/cosign) is a new standard to sign container images, blobs, etc. It supports keyful which requires a private key to manage and keyless approach which does not require any keys to manage to sign things. Since signing software provides a strong guarantee that the software has not been tampered with, so, I just thought that signing packages in NixOS would be a great addition to have from such a perspective.

WDYT?

**Comment by MaxHearnden** [comment] 2023-03-26 12:04
Duplicate of https://github.com/NixOS/nix/issues/7216

**Closed** 2023-03-26 12:35 UTC

**Comment by andsens** [comment] 2026-02-19 08:46
IIUC cosign is a _tool_ for signing, while sigstore is a centralized service that delegates trust via OIDC. One need not support the entirety of sigstore to support cosign. I would argue that this should be reopened so the (likely) rejection of sigstore support doesn't kill the effort of supporting an independent and fairly well-designed signing standard.
