### ISSUE TITLE
Unable to build ghc-7.10.1 using ghc-7.4.2-binary

### ISSUE THREAD

**Issue by plcplc** [NixOS/nixpkgs#8244] opened 2015-06-09 11:57 UTC
On my Nixos laptop (32bit intel) I am unable build ghc-7.10.1. It fails already when trying to start the binary ghc-7.4.2 it seems.

The source is from the nixos-unstable channel as of today.

    plc-laptop% nix-env -iA nixos.pkgs.haskellPackages.ghc
    replacing old ‘ghc-7.8.3-wrapper’
    installing ‘ghc-7.10.1’
    these derivations will be built:
      /nix/store/viqf7nwqshzackfslj2im9xg7af4s1nm-ghc-7.4.2-binary.drv
      /nix/store/5fa0cic2l33ldz5sg7yp20bgf3hrimn2-ghc-7.8.4.drv
      /nix/store/bgkkz1h6s1pc63ggf6xw605x252zi244-ghc-7.10.1.drv
    building path(s) ‘/nix/store/ygp6s44nxv4z7am2g8g52iwqkbgxj04h-ghc-7.4.2-binary’
    unpacking sources
    unpacking source archive /nix/store/4zj30pw1rzvqshnrcsl9dw1ahdxhlz0z-ghc-7.4.2-    i386-unknown-linux.tar.bz2
    source root is ghc-7.4.2
    not an ELF executable
    cannot find section .interp
    missing ELF header
    cannot find section .interp
    cannot find section .interp
    (... repeated some 20~ times, snipped away here for clarity)
    cannot find section .interp
    cannot find section .interp
    not an ELF executable
    not an ELF executable
    patching sources
    configuring
    checking for path to top of build tree... /tmp/nix-build-ghc-7.4.2-binary.drv-0/ghc-7.4.2
    ghc/stage2/build/tmp/ghc-stage2: error while loading shared libraries: libncurses.so.5: cannot     open shared object file: No such file or directory
    Can't work out build platform
    builder for ‘/nix/store/viqf7nwqshzackfslj2im9xg7af4s1nm-ghc-7.4.2-binary.drv’ failed with exit    code 1
    cannot build derivation ‘/nix/store/5fa0cic2l33ldz5sg7yp20bgf3hrimn2-ghc-7.8.4.drv’: 1    dependencies couldn't be built
    cannot build derivation ‘/nix/store/bgkkz1h6s1pc63ggf6xw605x252zi244-ghc-7.10.1.drv’: 1 dependencies couldn't be built
    error: build of ‘/nix/store/bgkkz1h6s1pc63ggf6xw605x252zi244-ghc-7.10.1.drv’ failed

The error message seems similar to https://github.com/NixOS/nixpkgs/issues/286, but doesn't otherwise appear related to it.

**Comment by peti** [comment] 2015-06-09 12:48
This is caused by https://github.com/NixOS/nixpkgs/issues/7810. The fix has been in `master` for a while and will reach the `nixos-unstable` channel soon.

**Closed** 2015-06-09 12:48 UTC
