### ISSUE TITLE
Can't launch Telegram on Cinnamon: Gtk-WARNING **: 22:14:48.808: Unable to locate theme engine in module_path: "murrine"

### ISSUE THREAD

**Issue by alexnils** [NixOS/nixpkgs#353111] opened 2024-11-02 12:46 UTC
### Describe the bug
I recently started getting problems using the unstable version of Telegram using Cinnamon (stable, i.e. 6.0.4). I'm also using the same Telegram version (5.6.3) on GNOME stable and it works without problems, so I guess this has something to do with Cinnamon.

I first got this error when launching Telegram:

`(.telegram-desktop-wrapped:2143): Gtk-WARNING **: 22:14:48.808: Unable to locate theme engine in module_path: "murrine",`

Just to test, I added `gtk-engine-murrine` to my configuration and now I get this error:

`zsh: segmentation fault (core dumped)  telegram-desktop`

When any of these two errors occur, the application will not run.

### Notify maintainers
@NickCao 

### Metadata

- system: `"x86_64-linux"`
 - host os: `Linux 6.6.58, NixOS, 24.05 (Uakari), 24.05.6122.080166c15633`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by NickCao** [comment] 2024-11-02 13:47
Using GUI software from unstable channel on a stable nixos installation is not "that much" a supported configuration. Since gtk/qt all tend to load some plugins from the system, and fails to load them/crashes when there's a version mismatch, which is likely the cause of what you are seeing. Speaking of telegram-desktop specifically, we do allow and want to backport updates to the stable channel, see https://github.com/NixOS/nixpkgs/pull/342783, and it would be great if you can help testing it out.

**Comment by NickCao** [comment] 2024-12-03 19:07
24.11 has been released with the latest version of telegram-desktop, please upgrade if possible.

**Closed by NickCao** 2024-12-03 19:07 UTC
Labels: 0.kind: bug
