### ISSUE TITLE
Build failure: waybar

### ISSUE THREAD

**Issue by IceDBorn** [NixOS/nixpkgs#297409] opened 2024-03-20 08:26 UTC
### Steps To Reproduce

1. build *waybar* on latest unstable

### Build log

```
error: builder for '/nix/store/wp5d5205rv1kdz2rrz4jgknqjy6y2pm5-waybar-0.10.0.drv' failed with exit code 1;
       last 10 log lines:
       > Run-time dependency libudev found: YES 255
       > Run-time dependency libevdev found: YES 1.13.1
       > Run-time dependency libmpdclient found: YES 2.22
       > Run-time dependency xkbregistry found: YES 1.5.0
       > Run-time dependency jack found: YES 1.9.22
       > Run-time dependency wireplumber-0.4 found: NO (tried pkgconfig)
       >
       > meson.build:95:17: ERROR: Dependency "wireplumber-0.4" not found, tried pkgconfig
       >
       > A full log can be found at /build/source/build/meson-logs/meson-log.txt
       For full logs, run 'nix log /nix/store/wp5d5205rv1kdz2rrz4jgknqjy6y2pm5-waybar-0.10.0.drv'.
error: 1 dependencies of derivation '/nix/store/pq0a8n4hb8fdlbjb0fibv2wwll0q93gk-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/p8jg9bsan3ab7yikk6nnr57afihb1afi-nixos-system-work-24.05.20240319.b06025f.drv'
 failed to build
```

### Additional context

I managed to fix the issue with this [overlay](https://github.com/IceDBorn/nerivations/commit/cdb739c3a9c1db287dd36cba43a45df0f44809ad). I can make a PR with this pin, but I'm not sure if this is the correct way to fix this.

### Notify maintainers

@FlorianFranzen
@lovesegfault
@minijackson
@rodrgz
@synthetica
@khaneliman

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.1-cachyos, NixOS, 24.05 (Uakari), 24.05.20240319.b06025f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/zaza7mgggz4m5h6z18kajabf4wciaj47-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by expenses** [comment] 2024-03-20 08:46
Thanks for the overlay!

**Comment by kashw2** [comment] 2024-03-20 09:00
duplicate of https://github.com/NixOS/nixpkgs/issues/297261
fixed on master with https://github.com/NixOS/nixpkgs/pull/297158

**Closed by kashw2** 2024-03-20 09:00 UTC
Labels: 0.kind: build failure
