### ISSUE TITLE
mpv: --hwdec=nvdec dont work in unstable

### ISSUE THREAD

**Issue by 3JlOy-PYCCKUi** [NixOS/nixpkgs#218859] opened 2023-02-28 19:33 UTC
### Describe the bug

mpv with --hwdec=nvdec throws errors

```
[ffmpeg/video] h264: Cannot load libnvcuvid.so.1
[ffmpeg/video] h264: Failed loading nvcuvid.
[ffmpeg/video] h264: Failed setup for format cuda: hwaccel initialisation returned error.
```

### Steps To Reproduce
1. Open h264 video with mpv from nixos-unstable (it is 7f5639fa3b68054ca0b062866dc62b22c3f11505 commit now)
2. Get errors

### Expected behavior
No errors printed

### Additional context

Problem exists in current master (4a6cd14f37b22c9d2f90e3774b8ea9601025ad6b), unstable (7f5639fa3b68054ca0b062866dc62b22c3f11505)

But no issue on commit c2f4e0d0d154545f11fb9656584c6895040e6214 (last commit pkgs/applications/video/mpv dir was touched)

i tested this via `nix shell github:NixOS/nixpkgs/<commit>#mpv` and then open video (direct link to video - https://0x0.st/s/jPdDkhUx1W-W5saPzei__Q/HzN-.mp4)

### Notify maintainers

@AndersonTorres
@fpletz
@globin
@Ma27
@tadeokondrak

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.13-xanmod1, NixOS, 23.05 (Stoat), 23.05.20230226.7f5639f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - nixpkgs: `/nix/store/glny4n684v2j01d43l5cy4qixxjarpi6-mzwhfnrlcij1iqvx52pjb8r699xdgvyi-source`
```

**Comment by AndersonTorres** [comment] 2023-03-03 14:23
Oh boy. I can't help with nvidia hardware things.

**Comment by SomeoneSerge** [comment] 2023-03-07 14:08
nix shell github:NixOS/nixpkgs/<commit>#mpv

That'd use ffmpeg built without the cudaSupport flag. Unless nvcuvid is one of the "impurely deployed" libraries (go into /run), neither ffmpeg nor MPV would know about it

**Comment by SomeoneSerge** [comment] 2023-03-29 23:35
@3JlOy-PYCCKUi `(ffmpeg_5.override { withCuda = true; })`

**Comment by SomeoneSerge** [comment] 2023-03-30 15:11
Weird that `libnvcuvid.so` comes with the driver (`nvidia_x11`), I didn't expect that.

I see we have a broken derivation `nixpkgs#nvidia-video-sdk` (which currently fails at `fetchurl`), and it probably should refer to the samples

**Comment by SomeoneSerge** [comment] 2023-03-30 15:13
@3JlOy-PYCCKUi can you verify if the problem is gone with https://nixpk.gs/pr-tracker.html?pr=217044 being merged? If it's not there must some libs we forgot to patchelf, and we should just migrate ffmpeg from `addOpenGLRunpath` to `cudaPackages.autoAddOpenGLRunpathHook`

**Comment by SomeoneSerge** [comment] 2023-04-02 00:02
May 31st, the problem appears to have been solved by https://github.com/NixOS/nixpkgs/pull/217044. Closing the issue, feel free to follow up

```bash
❯ # Mpv from a two weeks old nixos-unstable. Can reproduce the nvcuvid error
❯ readlink -f $(which mpv)
/nix/store/maqw3rlx5sq60hkflm40n6lg5j0k7w1m-mpv-with-scripts-0.35.1/bin/mpv
❯ mpv --hwdec=nvdec nix-du-xdot-2.mp4
Error parsing option cache-default (option not found)
/home/ss/.config/mpv/mpv.conf:3: setting option cache-default='4000000' failed.
 (+) Video --vid=1 (*) (h264 3828x2108 10.000fps)
[ffmpeg/video] h264: Cannot load libnvcuvid.so.1
[ffmpeg/video] h264: Failed loading nvcuvid.
[ffmpeg/video] h264: Failed setup for format cuda: hwaccel initialisation returned error.
VO: [gpu] 3828x2108 yuv420p
V: 00:00:00 / 00:00:41 (0%)

Exiting... (Quit)
❯ nix shell --expr '(import (builtins.getFlake github:NixOS/nixpkgs/master) { config = { cudaSupport = true; allowUnfree = true; }; }).mpv' --impure
❯ mpv --hwdec=nvdec nix-du-xdot-2.mp4
Error parsing option cache-default (option not found)
/home/ss/.config/mpv/mpv.conf:3: setting option cache-default='4000000' failed.
 (+) Video --vid=1 (*) (h264 3828x2108 10.000fps)
[ffmpeg/video] h264: Cannot load libnvcuvid.so.1
[ffmpeg/video] h264: Failed loading nvcuvid.
[ffmpeg/video] h264: Failed setup for format cuda: hwaccel initialisation returned error.
VO: [gpu] 3828x2108 yuv420p
V: 00:00:00 / 00:00:41 (0%)

Exiting... (Quit)
```

**Closed by SomeoneSerge** 2023-04-02 00:02 UTC
Labels: 0.kind: bug
