### ISSUE TITLE
🦝 NixOS 22.11 - Feature Freeze & Release Blockers

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#194208] opened 2022-10-03 10:52 UTC
Hey everyone, we are [Janne Heß](https://github.com/dasJ) & [Martin Weinelt](https://github.com/mweinelt), the release managers for NixOS 22.11 🦝 ("*Raccoon*").

Today it's time to talk about the feature freeze for the upcoming release. We have two upcoming dates that we'd like to mention in that context:

- **2022-10-17** Updates to release critical packages are restricted
- **2022-10-31** Breaking changes in general are restricted, with the exception of desktop environments

The complete timeline can be found in the

- https://github.com/NixOS/nixpkgs/issues/193585.

So with two weeks to the first restrictions kicking in, we want to encourage all teams to check in now and mention possible roadblocks, so we get a good overview of what's ahead.

## Blockers

Whether you were pinged or not, we encourage everyone to create issues for release blockers and add them to the [22.11 Blockers](https://github.com/orgs/NixOS/projects/13) project.

## Check-In

Please comment your status quo and possible issues as soon as possible. We'll check teams once they have checked in.

If you think some subsystem, person or team should be added to or removed from this list, update `maintainers/team-list.nix` in time before the next feature freeze announcement.

### Desktop environments
- [x] Cinnamon: @bobby285271 @mkg20001
- [x] Enlightenment: @NixOS/enlightenment
- [x] GNOME: @NixOS/gnome @bobby285271 @dasj19 @maxeaubrey
- [x] MATE: @romildo @johannesloetzsch
- [x] Lumina: @NixOS/lumina
- [x] LXQt: @NixOS/lxqt
- [x] Pantheon: @NixOS/pantheon
- [ ] Qt / KDE: @NixOS/qt-kde
- [x] XFCE: @romildo

### Platforms
- [ ] Darwin: @NixOS/darwin-maintainers
- [x] Mobile: @NixOS/mobile-nixos 

### Languages
- [x] BEAM: @NixOS/beam @minijackson
- [x] C: @matthewbauer @Mic92
- [x] Coq: @CohenCyril @Zimmi48 @siraben @vbgl
- [x] Dhall: @Gabriella439 @ehmry
- [x] Go: @c00w @kalbasit @Mic92 @zowoq
- [x] Haskell: @NixOS/haskell
- [x] lua: @NixOS/lua 
- [ ] Perl: @stigtsp 
- [x] PHP: @NixOS/php
- [x] Python: @FRidh @mweinelt @jonringer
- [x] R: @bcdarwin @jbedo
- [x] Ruby: @marsam
- [x] Rust: @LnL7 @Mic92 @zowoq

### Modules
- [x] ACME: @m1cr0man @aanderse @andrew-d @arianvp @emilazy @flokli
- [x] systemd: @NixOS/systemd

### Internals

- [x] Docs: @ryantm @pennae 
- [ ] Marketing: @garbas @tomberek
- [ ] Nix/nix-cli ecosystem: @Profpatsch @edolstra @grahamc @nbp
- [x] NixOS modules & internals: @Ericson2314 @infinisil @alyssais @roberth
- [x] NixOS tests: @tfc

## Finally

No issue is too big or too small, but let's remember that we are all working on the project voluntarily in our free time here, so let's focus on issues that can be realistically addressed in the remaining time before the release.

We thank everyone for their contribution!

**Comment by mweinelt** [comment] 2022-10-03 10:53
(reserved)

**Comment by bobby285271** [comment] 2022-10-03 11:35
- Cinnamon: We successfully landed [5.4](https://github.com/NixOS/nixpkgs/pull/181918) already so no blockers from my side. I do aware that [mozjs78 removal](https://github.com/NixOS/nixpkgs/issues/157874) is added as a blocker and cjs still uses it for language bindings, we will surely take action when update is possible.
- Pantheon: Also no blocking issues but GNOME 43 do [affect this DE](https://discourse.nixos.org/t/help-testing-gnome-pantheon-cinnamon-co-needed/21935/11) and we are trying to minimize the regression it brings.

**Comment by samueldr** [comment] 2022-10-03 18:04
Not a blocker per se, but it would be nice to have the help to bring the almost complete Plasma Mobile PR in

  - https://github.com/NixOS/nixpkgs/pull/185191 (to fix AArch64 builds)
  - https://github.com/NixOS/nixpkgs/pull/193858

Main unsolved issue is that plasma phone dialer segfault, everything else has solutions written-up already. So reviewing

**Comment by Gabriella439** [comment] 2022-10-03 19:34
No blockers for Dhall

**Comment by jbedo** [comment] 2022-10-03 21:34
No blockers for R

**Comment by infinisil** [comment] 2022-10-03 21:55
No blockers for NixOS modules & internals

**Comment by romildo** [comment] 2022-10-03 22:36
No blockers for:
- Enlightenment
- MATE
- Lumina
- LXQt
- XFCE

**Comment by happysalada** [comment] 2022-10-04 00:47
No blockers for beam languages

**Comment by sternenseemann** [comment] 2022-10-04 12:52
No blockers per se, since we've been lacking the time to do the bigger jobs we have in mind this release cycle. A couple things that would be nice to have are #194391 and #190536 which should be no trouble to get in time.

Additionally I want to bring attention to #184041, even though we *should not block* on it (since I can't guarantee it gets done in time and it's backportable): It would help if M1 users could test it and a careful review of the patch is still needed as well.

**Comment by jonringer** [comment] 2022-10-04 16:26
Python up-to-date for https://nixos.org/manual/nixpkgs/unstable/#id-1.5.8.29.7

**Comment by flokli** [comment] 2022-10-04 18:03
No blockers on the systemd side. We're landing some small fixes and UX improvements, especially on the experimental systemd-in-initrd backend, but that's not release relevant.

**Comment by teto** [comment] 2022-10-04 21:12
I've just created 1 PR to add the lua team to the list.
Not blocking per-se but nice to have:
- add some testing infra to lua https://github.com/NixOS/nixpkgs/pull/177556 , having it in the next release will make some stuff easier to backport
- The way buildNeovimPlugin works right now is really confusing (it ignores the generated source) and this  https://github.com/NixOS/nixpkgs/pull/190824 should fix it.

I am in charge of both and there should be no problem getting those finished for the release.

**Comment by m1cr0man** [comment] 2022-10-04 21:53
No blockers in ACME. Some nice to have PRs are outstanding but ready to merge:

- Lego client update to 4.9.0 #194302 which includes full support for CNAMEs.
- #191861 which resolves a random runtime increase during renewals and fixing HTTP-01 validation with the built-in web server.
- A small docs update #190052 correcting the DIY DNS-01 example.

**Comment by marsam** [comment] 2022-10-07 02:30
No blockers for:
- Node.js
- Ruby
- PostgreSQL.    
   No blocking per-se, I plan to merge https://github.com/NixOS/nixpkgs/pull/167047 and https://github.com/NixOS/nixpkgs/pull/185751 during this week

**Comment by etu** [comment] 2022-10-07 06:37
As for @NixOS/php we have one thing we would like to complete before 22.11, it's not the end of the world if we don't manage (some of us have busy lives at the moment).

So we will try to finish #194172 before the branching off. Otherwise I think we're good :slightly_smiling_face:

**Comment by Mic92** [comment] 2022-10-07 08:37
No blockers I am aware of for rust and C.

**Comment by jtojnar** [comment] 2022-10-08 22:24
For GNOME, we want to merge the 43 upgrade https://github.com/NixOS/nixpkgs/pull/182618, which is ready on the GNOME side but may bring a lot of breakage to other package sets (as can be seen on Pantheon).

But we will also want to get in fixes from 43.1, which is [due on Oct 22](https://wiki.gnome.org/FortyThree).

**Comment by sg2002** [comment] 2022-10-12 19:31
Can someone decide if #195710 can be considered a blocker?

**Comment by vbgl** [comment] 2022-10-13 06:40
Coq is in good shape, AFAICT.

**Comment by jtojnar** [comment] 2022-10-13 10:03
We will also want https://github.com/NixOS/nixpkgs/pull/195748, otherwise parsing HTML using `DomDocument` when running a script using `mod_php` on Apache creates an empty document: https://gitlab.gnome.org/GNOME/libxml2/-/issues/399

**Comment by jonringer** [comment] 2022-10-15 21:06
I would like to see the [RFC 121 PRs] merged:
- [Update nixos options from opengl to hardware.drivers](https://github.com/NixOS/nixpkgs/pull/158079)
- [Update `addOpenGLRunpath` -> `addHardwareRunpath`](https://github.com/NixOS/nixpkgs/pull/196174)

The reason why these should be release blockers, is that we would like a longer transition period where the existing `/run/opengl-driver/` and new `/run/current-system/drivers` paradigms both exist. So that when the old `opengl-driver` gets dropped it, users will be less likely to have issues around `/run/current-system/drivers` not existing.

**Comment by mweinelt** [comment] 2022-10-17 01:00
Breaking updates to the following packages are restricted as of today:

- binutils
- gcc
- glibc
- llvm
- systemd

https://nixos.github.io/release-wiki/Release-Critical-Packages.html

**Comment by vlinkz** [comment] 2022-10-19 17:24
https://github.com/NixOS/nixpkgs/pull/193041 and https://github.com/NixOS/nixpkgs/pull/191822 are needed to fix some errors with the calamares installer. See https://github.com/NixOS/nixpkgs/issues/196335

**Comment by Mic92** [comment] 2022-10-25 09:43
I just found a crash in our acme service (lego), which looks like a release blocker to me: https://github.com/NixOS/nixpkgs/pull/197702

**Comment by sternenseemann** [comment] 2022-10-26 13:34
Consider looking into https://github.com/NixOS/nixpkgs/issues/197907.

**Comment by tfc** [comment] 2022-10-27 13:31
NixOS tests: All good, there are no blockers.

**Comment by bryanasdev000** [comment] 2022-10-28 09:05
This maybe useful https://github.com/NixOS/nixpkgs/pull/171680 for a "better safe than sorry" approach around ZFS and hibernation. Feedback is welcome.

**Comment by Ericson2314** [comment] 2022-11-01 12:08
https://github.com/NixOS/nixpkgs/pull/82131 I would like to land first. I think it is ready. CC @alyssais in case you want someone else to review it.

**Comment by mweinelt** [comment] 2022-11-02 16:23
> Can someone decide if #195710 can be considered a blocker?

I don't think it should be.

**Comment by flokli** [comment] 2022-11-05 08:50
I added https://github.com/NixOS/nixpkgs/pull/199618 to the board - there's some fixes in there that I'd like to see 22.11 shipped with if possible. We've mostly been backporting point releases to stable previously, 252 needs to wait until after the branchoff.

**Comment by vcunat** [comment] 2022-11-10 19:17
https://github.com/NixOS/nixpkgs/issues/198668
I'd like this issue and related ones to get more community feedback... and hopefully move to a somewhat better overall state, despite perhaps not fully satisfying everyone.  And before 22.11, as the changes around the topic happened after 22.05.

**Comment by azahi** [comment] 2022-11-13 22:42
- [ ] #199881 This is definitely not a blocker but it should fix a really annoying behavior for display managers.

**Comment by rnhmjoj** [comment] 2022-11-24 14:44
> > Can someone decide if #195710 can be considered a blocker?
> 
> I don't think it should be.

Why? It's a pretty serious issue. See also https://github.com/NixOS/nixpkgs/issues/193646.

As I understand, OpenSSL has deprecated old ciphers and signatures that rely on SHA1 (which is insecure) and this obviously causes authentication failures with old APs and from all vendords that haven't been updating their TLS in like forever.

It could leave people without internet connection or lock them out of their machine. It should at least be documented in the release notes as a backward incompatibility.

**Comment by mweinelt** [comment] 2022-11-24 15:13
The referenced issue is about i686-linux, not about openssl.

**Closed** 2023-01-14 15:34 UTC
Labels: 6.topic: nixos
