### ISSUE TITLE
Unable to replace musl used as GCC as libc by overlay

### ISSUE THREAD

**Issue by manueljacob** [NixOS/nixpkgs#40779] opened 2018-05-19 17:28 UTC
My goal is to build a package which is linked against a custom version of musl. I'm using this nix expression:
```
(import <nixpkgs> {
  crossSystem = (import <nixpkgs/lib>).systems.examples.musl64;
  overlays = [(self: super: {
    musl = self.stdenv.mkDerivation {
      name = "musl";
      src = builtins.fetchGit {
        url = "git://git.musl-libc.org/musl/";
        ref = "v1.1.18";
      };
      dontDisableStatic = true;
    };
  })];
}).pkgs
```

However, when building the "hello" package from this, it still links to the standard musl:
```
% ldd /nix/store/qs9lyvjdk9cmdimzbxbnkbj0kbrvw61d-hello-2.10-x86_64-unknown-linux-musl/bin/hello 
	linux-vdso.so.1 (0x00007ffd0c7e3000)
	libc.so => /nix/store/k23gcrzg18yyspkk9dflrgn6h9j1chbs-musl-1.1.19-x86_64-unknown-linux-musl/lib/libc.so (0x00007f16284bd000)
```

I'm not sure whether this should work as I expected. If not, please close this issue and give me a pointer what to do instead.

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.16.9-1-ARCH, Arch Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - nixpkgs: `/home/manu/vcs/nixpkgs`
```

**Comment by veprbl** [comment] 2018-05-19 20:34
cc @dtzWill

**Comment by matthewbauer** [comment] 2018-05-23 18:39
You should try overriding "muslCross" instead.

https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L9151-L9153

We should be using an override there, I think.

**Comment by matthewbauer** [comment] 2018-10-31 03:56
Closing as a dupe of #26004.

**Closed** 2018-10-31 03:56 UTC
