### ISSUE TITLE
Package request: recyclarr

### ISSUE THREAD

**Issue by noelpilled** [NixOS/nixpkgs#241368] opened 2023-07-03 23:32 UTC
**Project description**
Automatically sync TRaSH guides to your Sonarr and Radarr instances 
**Metadata**

* homepage URL: https://recyclarr.dev/
* source URL: https://github.com/recyclarr/recyclarr
* license: mit
* platforms: linux, macOS, windows

**Comment by figsoda** [comment] 2023-07-03 23:42
duplicate of #239851, there is a PR in progress: #240119

**Closed by figsoda** 2023-07-03 23:42 UTC
Labels: 0.kind: packaging request
