### ISSUE TITLE
Nixos-install not work combined with system.etc.overlay.enable

### ISSUE THREAD

**Issue by benys** [NixOS/nixpkgs#364006] opened 2024-12-10 18:41 UTC
## Describe the bug

nixos-install is not compatible with system.etc.overlay enabled.
In my opinion during executing:
https://github.com/NixOS/nixpkgs/blob/9ad61cfc19c1f66e7d7d1ac9c71ae1b187065580/nixos/modules/system/etc/etc.nix#L232-L245
Enviroment varialbe TMPDIR is pointed to absolute path "root path" not "chrooted path".

Installation failed because of:
```
installing the boot loader...
remounting /etc...
mktemp: failed to create directory via template ‘/mnt/tmp.c4Gagx63Wy/nixos-etc-metadata.XXXXXXXXXX’: No such file or directory
mount: /nix/store/0fi088xpw8irvwzk64byvk9jb21v39vz-etc-metadata.erofs: can't find in /etc/fstab.
mktemp: failed to create directory via template ‘/mnt/tmp.c4Gagx63Wy/nixos-etc.XXXXXXXXXX’: No such file or directory
mount: bad usage
Try 'mount --help' for more information.
mount: overlay: can't find in /etc/fstab.
findmnt: can't read /proc/mounts: No such file or directory
Moving mount
Mounting beneath top mount
Success | move-mount.c: 443: main: Invalid number of arguments 1
umount: failed to parse /proc/self/mountinfo: No such file or directory
umount: : umount failed: No such file or directory.
rmdir: failed to remove '': No such file or directory
findmnt: can't read /proc/mounts: No such file or directory
Activation script snippet 'etc' failed (1)
warning: /root/.nix-defexpr/channels exists, but channels have been disabled.
warning: /nix/var/nix/profiles/per-user/root/channels exists, but channels have been disabled.
Due to https://github.com/NixOS/nix/issues/9574, Nix may still use these channels when NIX_PATH is unset.
Delete the above directory or directories to prevent this.
Error: Failed to parse os-release
```
## Steps To Reproduce

1. I check out https://git.sr.ht/~r-vdp/nixos-config/ configuration
2. sudo nix --experimental-features "nix-command flakes" run 'github:nix-community/disko' -- --mode disko --flake "path://$PWD#hostname"
3. sudo nixos-install --root /mnt --flake .#hostname --impure

## Expected behavior

nixos-install should work normaly

## Additional context

A few months ago, installation worked (on my current computer). 

## Metadata
 
Nixos run from installation disc:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.61, NixOS, 24.05 (Uakari), 24.05.6668.e8c38b73aeb2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos-24.05.6668.e8c38b73aeb2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

## Notify maintainers
@r-vdp is your configuration :-) maybe you can check it

**Comment by r-vdp** [comment] 2024-12-10 18:56
Interesting. I've only used nixos-anywhere with this config.
It's definitely a bug if this doesn't work though.

**Comment by benys** [comment] 2024-12-10 18:57
I also tried "nixos-anywhere" I received similar result :-(

**Comment by r-vdp** [comment] 2024-12-10 19:06
Ah OK, I probably didn't reinstall any machine since I switched to using the overlay then.

**Comment by Mic92** [comment] 2024-12-10 20:53
Weird that we don't have `/proc` inside the chroot?

```
umount: failed to parse /proc/self/mountinfo: No such file or directory
```

**Comment by benys** [comment] 2024-12-11 09:06
Yes I can confirm, that /proc doesn't exist inside the chroot.

Also command:
`nix run 'nixpkgs#nixos-anywhere' -- -L  --flake '.#hostname' --option pure-eval false root@xxx.xxx.xxx.xxx`
returns:
```
copying path '/nix/store/f41fq6in6vsp4dl5klkmds311fndl33j-libreoffice-24.8.3.2-wrapped' from 'https://cache.nixos.org'...
copying path '/nix/store/8p1kpfcj4jl9l62q5madwm4qph57214r-mbrola-3.3' from 'https://cache.nixos.org'...
copying path '/nix/store/jwm74hh1fi0qi9yp7b5y0ss2vcc928gj-espeak-ng-1.51.1' from 'https://cache.nixos.org'...
copying path '/nix/store/nnkxa3x44gyinb6ikl86dawsk6q26ba8-speech-dispatcher-0.11.5' from 'https://cache.nixos.org'...
copying path '/nix/store/2lgkm1632il4nms286azmrqy7hbadcyy-libreoffice-24.8.3.2-wrapped' from 'https://cache.nixos.org'...
### Installing NixOS ###
Pseudo-terminal will not be allocated because stdin is not a terminal.
Warning: Permanently added 'xxx.xxx.xxx.xxx' (ED25519) to the list of known hosts.
installing the boot loader...
remounting /etc...
mktemp: failed to create directory via template ‘/mnt/tmp.uat5RdJJaS/nixos-etc-metadata.XXXXXXXXXX’: No such file or directory
mount: /nix/store/4kvn6bs0wgbngsq5bxhc8xv6yhf7bz9b-etc-metadata.erofs: can't find in /etc/fstab.
mktemp: failed to create directory via template ‘/mnt/tmp.uat5RdJJaS/nixos-etc.XXXXXXXXXX’: No such file or directory
mount: bad usage
Try 'mount --help' for more information.
mount: overlay: can't find in /etc/fstab.
findmnt: can't read /proc/mounts: No such file or directory
Moving mount
Mounting beneath top mount
Success | move-mount.c: 443: main: Invalid number of arguments 1
umount: failed to parse /proc/self/mountinfo: No such file or directory
umount: : umount failed: No such file or directory.
rmdir: failed to remove '': No such file or directory
findmnt: can't read /proc/mounts: No such file or directory
Activation script snippet 'etc' failed (1)
Error: Failed to parse os-release

Caused by:
    0: Failed to read /etc/os-release
    1: No such file or directory (os error 2)
```

**Comment by r-vdp** [comment] 2024-12-11 14:08
Could you try again with the above PR?

**Comment by r-vdp** [comment] 2024-12-11 14:12
Closing this as a duplicate of #319533

**Closed by r-vdp** 2024-12-11 14:12 UTC
Labels: 0.kind: bug
