### ISSUE TITLE
dwarf-fortress: dfhack fatal error

### ISSUE THREAD

**Issue by patrl** [NixOS/nixpkgs#49779] opened 2018-11-05 10:17 UTC
## Issue description

On both latest stable channel and also confirmed latest unstable, running `dfhack` from the `dwarf-fortress-full` package results in a fatal error:

```
This DF version is missing from hack/symbols.xml, and
you have compiled DFHack with a df-structures (xml)
version that does *not* match the version tracked in git.

If you are not actively working on df-structures and you
expected DFHack to work, you probably forgot to run

    git submodule update

If this does not sound familiar, read Compile.rst and
recompile.
More details can be found in stderr.log in this folder.

DFHack fatal error: Not a known DF version - XML version mismatch (see console or stderr.log)
DFHack will now deactivate.
```

Cleaning `~/.local/share/fdf_linux` doesn't help.

cc @numinit @bendlas et al

### Steps to reproduce

Install `dwarf-fortress-full` (or a variation containing `dfhack`) and run `dfhack`.

## Technical details

```
- system: `"x86_64-linux"`
 - host os: `Linux 4.14.78, NixOS, 18.09.1185.9ea650bb5de (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2pre6526_9f99d624`
 - channels(root): `"nixos-18.09.1185.9ea650bb5de, nixos-unstable-19.03pre156996.c70ad805d21"`
 - channels(patrl): `"nixos-18.09.1023.06fb0253afa, nixos-unstable-19.03pre156996.c70ad805d21"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bendlas** [comment] 2018-11-05 14:04
The problem is in this commit 0d57159eca8f3bfc2d009da57a253298d127d0e4
It fixes the vanilla build, but in turn leaves dfhack unusable.
@Lassulus can you take a look?

**Comment by Lassulus** [comment] 2018-11-05 20:51
hey, I think I fixed the issue in https://github.com/NixOS/nixpkgs/pull/49803 but can someone who uses dfhack actually test it?
thanks :)

**Comment by bendlas** [comment] 2018-11-06 00:06
merged the PR to master and stable. @patrl can you close the issue, after verifying the fix?

**Comment by patrl** [comment] 2018-11-06 08:51
@bendlas @Lassulus just tested it, and dfhack loads now. Thanks!

There's still the following warning about the ruby library, but I think that was there before too:

```
Cannot initialize ruby plugin: failed to load ruby library
```

**Closed** 2018-11-06 08:52 UTC
