### ISSUE TITLE
Package request: JDownloader2

### ISSUE THREAD

**Issue by Froztmuffins** [NixOS/nixpkgs#242408] opened 2023-07-09 04:08 UTC
**Project description**
Download manager, written in Java, for one-click hosting sites like Rapidshare and Megaupload. Uses its own updater.

**Metadata**

* homepage URL:https://jdownloader.org/jdownloader2
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by Shawn8901** [comment] 2023-07-10 16:26
Seems to be a duplicate of #41321

**Closed** 2023-07-10 19:49 UTC
Labels: 0.kind: packaging request
