### ISSUE TITLE
xournalpp / xournal++ crashes at startup

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#63715] opened 2019-06-24 05:11 UTC
## Issue description

Xournalpp crashes immediately.

### Steps to reproduce'

I don't have KDE nor GNOME installed in case that matters.

```
$ nix-build '<nixpkgs>' -A xournalpp
$ result/bin/xournalpp


** (xournalpp:2719): WARNING **: 08:08:07.696: Failed to load "colornames.ini" (/home/jluttine/.xournalpp/colornames.ini): No such file or directory

ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2636:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2636:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2636:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Icon 'image-missing' not present in theme breeze (gtk-icon-theme-error-quark, 0)

** (xournalpp:2719): WARNING **: 08:08:07.827: [Crash Handler] Crashed with signal 6

** (xournalpp:2719): WARNING **: 08:08:07.832: [Crash Handler] Wrote crash log to: /home/jluttine/.xournalpp/errorlogs/errorlog.20190624-080807.log
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found

** (xournalpp:2719): WARNING **: 08:08:07.942: Trying to emergency save the current open document…

** (xournalpp:2719): WARNING **: 08:08:07.943: Successfully saved document to "/home/jluttine/.xournalpp/emergencysave.xopp"

```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.47, NixOS, 19.09.git.4ab1c14 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by jtojnar** [comment] 2019-06-24 07:50
Do you have an icon theme installed?

**Comment by jluttine** [comment] 2019-06-24 08:00
I don't know, so maybe not..

**Comment by jtojnar** [comment] 2019-06-24 08:01
https://github.com/NixOS/nixpkgs/issues/63089#issuecomment-502201837

**Comment by KoviRobi** [comment] 2019-12-06 06:31
Installing `gnome3.adwaita-icon-theme` as per #63089 fixed it for me (but I tried `hicolor-icon-theme` first, which didn't). Though crashing is by no means a good or descriptive way to tell the user to install icons. I wonder if there is a fallback icon (not an icon set, just a single one) we could bundle with things to stop this

**Comment by wucke13** [comment] 2020-02-07 14:28
This should be fixed IMO. It is very against the nix ideology to require one package to be installed for another to function.
cc @andrew-d  @sikmir

**Comment by andrew-d** [comment] 2020-02-10 06:16
I'd be happy to take a fix to xournalpp here, but I'm not quite sure what the best approach is. My understanding is that GTK+ itself is what's crashing if the "image-missing" icon isn't found - see [here](https://github.com/GNOME/gtk/blob/cc22987b1bcbc9aee2c591705d61a064e3de6a81/gtk/gtkiconhelper.c#L113-L118).

As I understand it, we have the following options:
* Unconditionally wrap `xournalpp` with some icon theme; I'm not sure how this interacts with allowing users to still customize things themselves.
* Fix GTK+ to not crash if the icon is missing; I don't know how to do this
* Try to detect this case in `xournalpp` or other utilities and throw an error; I could probably write a wrapper that searched `XDG_ICON_DIRS`, but I'm not 100% sure this works, and it feels too hacky.
* Maybe create an "empty" icon theme that's always linked by default and contains only the `image-missing.png` image?

**Comment by andrew-d** [comment] 2020-02-10 06:41
I haven't had the chance to test it, but if anyone else wants to: here's an example of a Nix derivation for an icon theme that only contains the `image-missing.png` images from the Adwaita icon theme:
https://gist.github.com/andrew-d/41f2942a32b02249fac2dadf934cecec

**Comment by wucke13** [comment] 2020-02-10 12:02
Why isn't

> Unconditionally wrap xournalpp with some icon theme; I'm not sure how this interacts with allowing users to still customize things themselves.

The obvious solution? It is still possible to set another icon theme locally (if using `.gtkrc` and pendants), provided it is also installed to the regarding environment?

**Comment by KoviRobi** [comment] 2020-02-10 12:47
I guess it's mostly a question of icons are large (ish) and we don't want to install unnecessary icons. I am pro the image-missing solution, provided we also document it somewhere (not sure if NixOS manual is the best place, could apply to non-NixOS nix installations, so the Nix manual).

Also, the `.gtkrc` is an annoying solution as it's not part of the nixos config, I guess.

**Comment by jtojnar** [comment] 2020-02-10 15:52
@KoviRobi

> I guess it's mostly a question of icons are large (ish) and we don't want to install unnecessary icons. I am pro the image-missing solution, provided we also document it somewhere (not sure if NixOS manual is the best place, could apply to non-NixOS nix installations, so the Nix manual).

This is indeed the primary reason, see the discussion in #43150.

@andrew-d 

> * Unconditionally wrap `xournalpp` with some icon theme; I'm not sure how this interacts with allowing users to still customize things themselves.

Customization is still possible (the theme used will be still the one set in profile, defaulting to Adwaita), the closure is the main concern.

> * Fix GTK+ to not crash if the icon is missing; I don't know how to do this

I talked with GTK devs on IRC a few days ago and they also said that GTK should use the [image-missing from GTK](https://gitlab.gnome.org/GNOME/gtk/blob/3.24.13/gtk/icons/16x16/status/image-missing.png) and the [source code](https://gitlab.gnome.org/GNOME/gtk/blob/3.24.12/gtk/gtkiconhelper.c#L490) looks like that is what should be happening but to no avail.

Actually, it seems to somewhat work – try running `env XDG_DATA_DIRS= (nix-build -A gtk3.dev --no-out-link)/bin/gtk3-icon-browser`, it will have the `image-missing` in the CSD.

> * Maybe create an "empty" icon theme that's always linked by default and contains only the `image-missing.png` image?

Brilliant idea. This would be an acceptable compromise, I think, until it is fixed in GTK. We should probably use `fetchurl { url = "https://gitlab.gnome.org/GNOME/gtk/blob/3.24.13/gtk/icons/16x16/status/image-missing.png"; }` to avoid depending on Adwaita, and add it to `hicolor-icon-theme` instead of new theme. Then we can add the icon theme to `wrapGAppsHook`.

> * Try to detect this case in `xournalpp` or other utilities and throw an error; I could probably write a wrapper that searched `XDG_ICON_DIRS`, but I'm not 100% sure this works, and it feels too hacky.

We might still want something like this to let users know they should install an icon theme. But we can worry about that once we prevent the crash.

**Comment by gebner** [comment] 2020-08-25 14:36
This is still an issue.

**Comment by sikmir** [comment] 2020-09-07 15:54
Just in case, the same problem with MyPaint (https://github.com/NixOS/nixpkgs/pull/54677), it crashes at startup.

**Comment by scaredmushroom** [comment] 2021-03-12 10:53
It is still an issue.

**Comment by vojta001** [comment] 2021-11-16 15:54
I can only reproduce it when trying to export a pdf with `xournalpp -p out.pdf in.xopp`, which might be a different issue (yet still annoying).

What about you @sikmir @jluttine?

**Comment by sikmir** [comment] 2021-11-16 16:00
> I can only reproduce it when trying to export a pdf with `xournalpp -p out.pdf in.xopp`, which might be a different issue (yet still annoying).
> 
> What about you @sikmir @jluttine?

I really cannot reproduce the crash neither at startup, nor with `xournalpp -p out.pdf in.xopp`. Could you please provide crash dump or backtrace? Otherwise it's hard to say what is going wrong.

**Comment by jluttine** [comment] 2021-11-16 16:59
Seems to work for me now. I don't know what has changed. Should I close this or is it still an issue for someone?

**Comment by atilaTrackfy** [comment] 2021-11-22 13:29
I still have this problem.

**Comment by sikmir** [comment] 2022-02-13 21:47
Try https://github.com/NixOS/nixpkgs/pull/159902, maybe it helps.

**Comment by vojta001** [comment] 2022-02-14 19:26
@sikmir I cannot reproduce the problem anymore. Good catch!

**Closed** 2022-02-15 11:43 UTC

**Comment by jotapesse** [comment] 2023-10-07 14:49
Hello, this is still an issue for me! On a NixOS unstable 23.11 install with KDE Plasma. Same error as original post:

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.5, NixOS, 23.11 (Tapir), 23.11pre531102.fdd898f8f79e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

```
$ xournalpp
xopp-Message: 15:37:02.273: TEXTDOMAINDIR = (null), Platform-specific locale dir = /nix/store/dn1g7biypbl60pamj5zsc4lhaq8zxggi-xournalpp-1.2.1/share/xournalpp/../locale, chosen directory = /nix/store/dn1g7biypbl60pamj5zsc4lhaq8zxggi-xournalpp-1.2.1/share/xournalpp/../locale
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2737:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2737:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2737:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
xopp-Message: 15:37:02.324: Plugin "MigrateFontSizes" UI initialized

(com.github.xournalpp.xournalpp:93805): xopp-WARNING **: 15:37:02.401: No device found. Is Xournal++ running in debugger / Eclipse...?
Probably this is the reason for not finding devices!


(com.github.xournalpp.xournalpp:93805): xopp-WARNING **: 15:37:02.418: No device found. Is Xournal++ running in debugger / Eclipse...?
Probably this is the reason for not finding devices!

**
Gtk:ERROR:../gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Icon 'image-missing' not present in theme Adwaita (gtk-icon-theme-error-quark, 0)
Bail out! Gtk:ERROR:../gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Icon 'image-missing' not present in theme Adwaita (gtk-icon-theme-error-quark, 0)

(com.github.xournalpp.xournalpp:93805): xopp-WARNING **: 15:37:02.455: [Crash Handler] Crashed with signal 6

(com.github.xournalpp.xournalpp:93805): xopp-WARNING **: 15:37:02.455: [Crash Handler] Wrote crash log to: /home/joao/.cache/xournalpp/errorlogs/errorlog.20231007-153702.log
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found
sh: line 1: addr2line: command not found

(com.github.xournalpp.xournalpp:93805): xopp-WARNING **: 15:37:02.586: Trying to emergency save the current open document…

(com.github.xournalpp.xournalpp:93805): xopp-WARNING **: 15:37:02.586: Successfully saved document to "/home/joao/.config/xournalpp/emergencysave.xopp"
```

**Comment by LucaGawa** [comment] 2023-10-10 22:02
installing
  gnome.adwaita-icon-theme
solved the problem for me

**Comment by jotapesse** [comment] 2023-10-10 23:54
Thanks. I can confirm that it solves the issues. But if it is a known requirement/dependency for so long already shouldn't the xournalpp package install it in the first place?
