### ISSUE TITLE
[Staging] Binutils 2.23.1 -> 2.25 breaks ld

### ISSUE THREAD

**Issue by wkennington** [NixOS/nixpkgs#7274] opened 2015-04-08 18:29 UTC
Some binaries are not being linked correctly after the version bump of binutils in the staging branch. An example is building samba which builds fine if you revert the binutils bump but does not link fine with the current binutils 2.25.

**Comment by domenkozar** [comment] 2015-04-08 18:35
Duplicate of #909

**Comment by peti** [comment] 2015-04-08 19:04
We should revert the `binutils` update from `staging` until that issue has been fixed. `staging` is supposed to be used for tested code only so that we can merge it at any time we want to. With the `binutils` update in place, we cannot do that.

**Comment by wkennington** [comment] 2015-04-08 19:16
Done 91221f5941a7a23807eaf90d4c5f35f11521a175

**Comment by domenkozar** [comment] 2015-04-19 23:17
Closing this in favor of #909

**Closed by domenkozar** 2015-04-19 23:17 UTC
Labels: blocker, bug, mass-rebuild
