### ISSUE TITLE
Manual should tip nixos container users to add system.stateVersion

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixpkgs#31220] opened 2017-11-04 01:04 UTC
## Issue description

I was believing that NixOS containers would inherit the host's `system.stateVersion`, though, that's part of me not really paying attention. Nothing was explicit in making me believe so, I assumed that it might be managed.

I think that it's important to remember the users of containers that they should use `system.stateVersion`, especially since the example is using PostgreSQL, which in the transition from 17.03 to 17.09 has breaking changes. By following the manual, it is possible to break a working system.

(I'm tracking the issue instead of opening a PR since I'm not a technical writer, and I don't know really know how to formulate this in a concise manner and clearly enough.)

**Comment by FRidh** [comment] 2017-11-04 08:56
Duplicate of #30056.

**Closed by FRidh** 2017-11-04 08:56 UTC
