### ISSUE TITLE
nix/nixos randomly loosing access to /dev/null

### ISSUE THREAD

**Issue by sss123next** [NixOS/nixpkgs#286716] opened 2024-02-06 10:17 UTC
### Describe the bug
`nix-build`, `nix-env`, `nixos-rebuild` randomly loosing access to `/dev/null`

### Steps To Reproduce
1. `nix-env -iA nixos.hello`
2. or `nix-build '<nixpkgs>' -A hello`
3. or `nixos-rebuild switch`

### Expected behavior
package should be built/installed

### Additional context

```
error: build of '/nix/store/gpsdv7dvr5gwmj73nph9fv2pidq2ibs2-vigra-unstable-2022-01-11.drv' on 'ssh://nix-builder@192.168.0.22' failed: builder for '/nix/store/gpsdv7dvr5gwmj73nph9fv2pidq2ibs2-vigra-unstable-2022-01-11.drv' failed with exit code 1;
       last 10 log lines:
       > /nix/store/kv5wkk7xgc8paw9azshzlmxraffqcg0i-stdenv-linux/setup: line 109: /dev/null: Permission denied
       > /nix/store/kv5wkk7xgc8paw9azshzlmxraffqcg0i-stdenv-linux/setup: line 111: /dev/null: Permission denied
       > /nix/store/kv5wkk7xgc8paw9azshzlmxraffqcg0i-stdenv-linux/setup: line 128: /dev/null: Permission denied
       > /nix/store/kv5wkk7xgc8paw9azshzlmxraffqcg0i-stdenv-linux/setup: line 109: /dev/null: Permission denied
       > /nix/store/kv5wkk7xgc8paw9azshzlmxraffqcg0i-stdenv-linux/setup: line 111: /dev/null: Permission denied
       > /nix/store/kv5wkk7xgc8paw9azshzlmxraffqcg0i-stdenv-linux/setup: line 128: /dev/null: Permission denied
       > /nix/store/gczmm06wzciqvj36n0kbv3fx9jxl5mcj-cmake-3.27.7/nix-support/setup-hook: line 2: $1: unbound variable
       > /nix/store/kv5wkk7xgc8paw9azshzlmxraffqcg0i-stdenv-linux/setup: line 128: /dev/null: Permission denied
       > /nix/store/kv5wkk7xgc8paw9azshzlmxraffqcg0i-stdenv-linux/setup: line 109: /dev/null: Permission denied
       > /nix/store/kv5wkk7xgc8paw9azshzlmxraffqcg0i-stdenv-linux/setup: line 111: /dev/null: Permission denied
       For full logs, run 'nix log /nix/store/gpsdv7dvr5gwmj73nph9fv2pidq2ibs2-vigra-unstable-2022-01-11.drv'.
error: builder for '/nix/store/gpsdv7dvr5gwmj73nph9fv2pidq2ibs2-vigra-unstable-2022-01-11.drv' failed with exit code 1;
       last 10 log lines:
       > /nix/store/kv5wkk7xgc8paw9azshzlmxraffqcg0i-stdenv-linux/setup: line 109: /dev/null: Permission denied
       > /nix/store/kv5wkk7xgc8paw9azshzlmxraffqcg0i-stdenv-linux/setup: line 111: /dev/null: Permission denied
       > /nix/store/kv5wkk7xgc8paw9azshzlmxraffqcg0i-stdenv-linux/setup: line 128: /dev/null: Permission denied
       > /nix/store/kv5wkk7xgc8paw9azshzlmxraffqcg0i-stdenv-linux/setup: line 109: /dev/null: Permission denied
       > /nix/store/kv5wkk7xgc8paw9azshzlmxraffqcg0i-stdenv-linux/setup: line 111: /dev/null: Permission denied
       > /nix/store/kv5wkk7xgc8paw9azshzlmxraffqcg0i-stdenv-linux/setup: line 128: /dev/null: Permission denied
       > /nix/store/gczmm06wzciqvj36n0kbv3fx9jxl5mcj-cmake-3.27.7/nix-support/setup-hook: line 2: $1: unbound variable
       > /nix/store/kv5wkk7xgc8paw9azshzlmxraffqcg0i-stdenv-linux/setup: line 128: /dev/null: Permission denied
       > /nix/store/kv5wkk7xgc8paw9azshzlmxraffqcg0i-stdenv-linux/setup: line 109: /dev/null: Permission denied
       > /nix/store/kv5wkk7xgc8paw9azshzlmxraffqcg0i-stdenv-linux/setup: line 111: /dev/null: Permission denied
       For full logs, run 'nix log /nix/store/gpsdv7dvr5gwmj73nph9fv2pidq2ibs2-vigra-unstable-2022-01-11.drv'.
error: 1 dependencies of derivation '/nix/store/ffl3f46zsl2qmdx08l2v9frsmsg3wrhq-enblend-enfuse-unstable-2022-03-06.drv' failed to build
error: 2 dependencies of derivation '/nix/store/38bv0y86kp2g3ly1ywlizhvzi3lb3a1z-hugin-2022.0.0.drv' failed to build
```

```
/nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 111: /dev/null: Permission denied
/nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 128: /dev/null: Permission denied
/nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 109: /dev/null: Permission denied
/nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 111: /dev/null: Permission denied
/nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 128: /dev/null: Permission denied
/nix/store/01nygk9550khsba4msxd751bvgs8jj23-pkg-config-wrapper-0.29.2/nix-support/setup-hook: line 87: $1: unbound variable
/nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 128: /dev/null: Permission denied
/nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 109: /dev/null: Permission denied
/nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 111: /dev/null: Permission denied
error: build of '/nix/store/dmwj6l1ipj1ibg8vhfik71pnpwx1jzm2-postgresql-15.5.drv' on 'ssh://nix-builder@192.168.0.22' failed: builder for '/nix/store/dmwj6l1ipj1ibg8vhfik71pnpwx1jzm2-postgresql-15.5.drv' failed with exit code 1;
       last 10 log lines:
       > /nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 109: /dev/null: Permission denied
       > /nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 111: /dev/null: Permission denied
       > /nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 128: /dev/null: Permission denied
       > /nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 109: /dev/null: Permission denied
       > /nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 111: /dev/null: Permission denied
       > /nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 128: /dev/null: Permission denied
       > /nix/store/01nygk9550khsba4msxd751bvgs8jj23-pkg-config-wrapper-0.29.2/nix-support/setup-hook: line 87: $1: unbound variable
       > /nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 128: /dev/null: Permission denied
       > /nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 109: /dev/null: Permission denied
       > /nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 111: /dev/null: Permission denied
       For full logs, run 'nix log /nix/store/dmwj6l1ipj1ibg8vhfik71pnpwx1jzm2-postgresql-15.5.drv'.
error: builder for '/nix/store/dmwj6l1ipj1ibg8vhfik71pnpwx1jzm2-postgresql-15.5.drv' failed with exit code 1;
       last 10 log lines:
       > /nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 109: /dev/null: Permission denied
       > /nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 111: /dev/null: Permission denied
       > /nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 128: /dev/null: Permission denied
       > /nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 109: /dev/null: Permission denied
       > /nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 111: /dev/null: Permission denied
       > /nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 128: /dev/null: Permission denied
       > /nix/store/01nygk9550khsba4msxd751bvgs8jj23-pkg-config-wrapper-0.29.2/nix-support/setup-hook: line 87: $1: unbound variable
       > /nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 128: /dev/null: Permission denied
       > /nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 109: /dev/null: Permission denied
       > /nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 111: /dev/null: Permission denied
       For full logs, run 'nix log /nix/store/dmwj6l1ipj1ibg8vhfik71pnpwx1jzm2-postgresql-15.5.drv'.
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.3, NixOS, 23.11 (Tapir), 23.11.4048.382debecd3aa`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"alien, android-nixpkgs, nixgl, nixos-23.11-small, nixpkgs1809-18.09-small, nixpkgs2003-20.03-small, nixpkgs2009-20.09-small, nixpkgs2105-21.05-small, nixpkgs2111-21.11-small, nixpkgs2205-22.05-small, nixpkgs2211-22.11-small, nixpkgs2305-23.05-small, nixpkgs2311-23.11-small, nixpkgsmaster, nixpkgsunstable, nur"`
 - channels(sss): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lolbinarycat** [comment] 2024-02-22 02:22
unable to reproduce on nixos 23.11

**Comment by sss123next** [comment] 2024-02-22 05:31
unfortunately it happens randomly and not specific to  nixpkgs version/commit.
i guessing it may be related to something in configuration nix, because it does not happening on non-nixos nix installation

**Comment by lolbinarycat** [comment] 2024-02-22 22:55
can you show the output of `cat /etc/passwd && ls -l /dev/null` on the misbehaving system?

**Comment by sss123next** [comment] 2024-02-22 23:36
first one:
```
 cat /etc/passwd && ls -l /dev/null 
root:x:0:0:System administrator:/root:/run/current-system/sw/bin/zsh
messagebus:x:4:4:D-Bus system message bus daemon user:/run/dbus:/run/current-system/sw/bin/nologin
cups:x:36:20:CUPS printing services:/var/empty:/run/current-system/sw/bin/nologin
chrony:x:61:61:chrony daemon user:/var/lib/chrony:/run/current-system/sw/bin/nologin
systemd-journal-gateway:x:110:110::/var/empty:/run/current-system/sw/bin/nologin
systemd-network:x:152:152::/var/empty:/run/current-system/sw/bin/nologin
systemd-resolve:x:153:153::/var/empty:/run/current-system/sw/bin/nologin
rpc:x:271:65534::/var/empty:/run/current-system/sw/bin/nologin
systemd-oom:x:985:993:systemd-oomd service user:/var/empty:/run/current-system/sw/bin/nologin
sshd:x:986:994:SSH privilege separation user:/var/empty:/run/current-system/sw/bin/nologin
nscd:x:987:995::/var/empty:/run/current-system/sw/bin/nologin
nix-ssh:x:988:996:Nix SSH store user:/var/empty:/run/current-system/sw/bin/zsh
nix-builder:x:989:997::/home/nix-builder:/run/current-system/sw/bin/bash
guixbuilder09:x:990:998::/var/empty:/bin/nologin
guixbuilder08:x:991:998::/var/empty:/bin/nologin
guixbuilder07:x:992:998::/var/empty:/bin/nologin
guixbuilder06:x:993:998::/var/empty:/bin/nologin
guixbuilder05:x:994:998::/var/empty:/bin/nologin
guixbuilder04:x:995:998::/var/empty:/bin/nologin
guixbuilder03:x:996:998::/var/empty:/bin/nologin
guixbuilder02:x:997:998::/var/empty:/bin/nologin
guixbuilder01:x:998:998::/var/empty:/bin/nologin
guix-builder:x:999:998::/home/guix-builder:/run/current-system/sw/bin/zsh
sss:x:1000:100::/home/sss:/run/current-system/sw/bin/zsh
nixbld1:x:30001:30000:Nix build user 1:/var/empty:/run/current-system/sw/bin/nologin
nixbld2:x:30002:30000:Nix build user 2:/var/empty:/run/current-system/sw/bin/nologin
nixbld3:x:30003:30000:Nix build user 3:/var/empty:/run/current-system/sw/bin/nologin
nixbld4:x:30004:30000:Nix build user 4:/var/empty:/run/current-system/sw/bin/nologin
nixbld5:x:30005:30000:Nix build user 5:/var/empty:/run/current-system/sw/bin/nologin
nixbld6:x:30006:30000:Nix build user 6:/var/empty:/run/current-system/sw/bin/nologin
nixbld7:x:30007:30000:Nix build user 7:/var/empty:/run/current-system/sw/bin/nologin
nixbld8:x:30008:30000:Nix build user 8:/var/empty:/run/current-system/sw/bin/nologin
nixbld9:x:30009:30000:Nix build user 9:/var/empty:/run/current-system/sw/bin/nologin
nixbld10:x:30010:30000:Nix build user 10:/var/empty:/run/current-system/sw/bin/nologin
nixbld11:x:30011:30000:Nix build user 11:/var/empty:/run/current-system/sw/bin/nologin
nixbld12:x:30012:30000:Nix build user 12:/var/empty:/run/current-system/sw/bin/nologin
nixbld13:x:30013:30000:Nix build user 13:/var/empty:/run/current-system/sw/bin/nologin
nixbld14:x:30014:30000:Nix build user 14:/var/empty:/run/current-system/sw/bin/nologin
nixbld15:x:30015:30000:Nix build user 15:/var/empty:/run/current-system/sw/bin/nologin
nixbld16:x:30016:30000:Nix build user 16:/var/empty:/run/current-system/sw/bin/nologin
nixbld17:x:30017:30000:Nix build user 17:/var/empty:/run/current-system/sw/bin/nologin
nixbld18:x:30018:30000:Nix build user 18:/var/empty:/run/current-system/sw/bin/nologin
nixbld19:x:30019:30000:Nix build user 19:/var/empty:/run/current-system/sw/bin/nologin
nixbld20:x:30020:30000:Nix build user 20:/var/empty:/run/current-system/sw/bin/nologin
nixbld21:x:30021:30000:Nix build user 21:/var/empty:/run/current-system/sw/bin/nologin
nixbld22:x:30022:30000:Nix build user 22:/var/empty:/run/current-system/sw/bin/nologin
nixbld23:x:30023:30000:Nix build user 23:/var/empty:/run/current-system/sw/bin/nologin
nixbld24:x:30024:30000:Nix build user 24:/var/empty:/run/current-system/sw/bin/nologin
nixbld25:x:30025:30000:Nix build user 25:/var/empty:/run/current-system/sw/bin/nologin
nixbld26:x:30026:30000:Nix build user 26:/var/empty:/run/current-system/sw/bin/nologin
nixbld27:x:30027:30000:Nix build user 27:/var/empty:/run/current-system/sw/bin/nologin
nixbld28:x:30028:30000:Nix build user 28:/var/empty:/run/current-system/sw/bin/nologin
nixbld29:x:30029:30000:Nix build user 29:/var/empty:/run/current-system/sw/bin/nologin
nixbld30:x:30030:30000:Nix build user 30:/var/empty:/run/current-system/sw/bin/nologin
nixbld31:x:30031:30000:Nix build user 31:/var/empty:/run/current-system/sw/bin/nologin
nixbld32:x:30032:30000:Nix build user 32:/var/empty:/run/current-system/sw/bin/nologin
nobody:x:65534:65534:Unprivileged account (don't use!):/var/empty:/run/current-system/sw/bin/nologin
crw-rw-rw- 1 root root 1, 3 фев 18 22:45 /dev/null
```

second one:
```
cat /etc/passwd && ls -l /dev/null
root:x:0:0:System administrator:/root:/run/current-system/sw/bin/zsh
messagebus:x:4:4:D-Bus system message bus daemon user:/run/dbus:/run/current-system/sw/bin/nologin
cups:x:36:20:CUPS printing services:/var/empty:/run/current-system/sw/bin/nologin
chrony:x:61:61:chrony daemon user:/var/lib/chrony:/run/current-system/sw/bin/nologin
systemd-journal-gateway:x:110:110::/var/empty:/run/current-system/sw/bin/nologin
systemd-network:x:152:152::/var/empty:/run/current-system/sw/bin/nologin
systemd-resolve:x:153:153::/var/empty:/run/current-system/sw/bin/nologin
rpc:x:271:65534::/var/empty:/run/current-system/sw/bin/nologin
systemd-oom:x:982:986:systemd-oomd service user:/var/empty:/run/current-system/sw/bin/nologin
nscd:x:983:987::/var/empty:/run/current-system/sw/bin/nologin
nix-builder:x:984:990::/home/nix-builder:/run/current-system/sw/bin/bash
guixbuilder09:x:985:991::/var/empty:/bin/nologin
guixbuilder08:x:986:991::/var/empty:/bin/nologin
guixbuilder07:x:987:991::/var/empty:/bin/nologin
guixbuilder06:x:988:991::/var/empty:/bin/nologin
guixbuilder05:x:989:991::/var/empty:/bin/nologin
guixbuilder04:x:990:991::/var/empty:/bin/nologin
guixbuilder03:x:991:991::/var/empty:/bin/nologin
guixbuilder02:x:992:991::/var/empty:/bin/nologin
guixbuilder01:x:993:991::/var/empty:/bin/nologin
guix-builder:x:994:991::/home/guix-builder:/run/current-system/sw/bin/zsh
sshd:x:995:994:SSH privilege separation user:/var/empty:/run/current-system/sw/bin/nologin
nix-ssh:x:997:997:Nix SSH store user:/var/empty:/run/current-system/sw/bin/zsh
sss:x:1000:100::/home/sss:/run/current-system/sw/bin/zsh
nixbld1:x:30001:30000:Nix build user 1:/var/empty:/run/current-system/sw/bin/nologin
nixbld2:x:30002:30000:Nix build user 2:/var/empty:/run/current-system/sw/bin/nologin
nixbld3:x:30003:30000:Nix build user 3:/var/empty:/run/current-system/sw/bin/nologin
nixbld4:x:30004:30000:Nix build user 4:/var/empty:/run/current-system/sw/bin/nologin
nixbld5:x:30005:30000:Nix build user 5:/var/empty:/run/current-system/sw/bin/nologin
nixbld6:x:30006:30000:Nix build user 6:/var/empty:/run/current-system/sw/bin/nologin
nixbld7:x:30007:30000:Nix build user 7:/var/empty:/run/current-system/sw/bin/nologin
nixbld8:x:30008:30000:Nix build user 8:/var/empty:/run/current-system/sw/bin/nologin
nixbld9:x:30009:30000:Nix build user 9:/var/empty:/run/current-system/sw/bin/nologin
nixbld10:x:30010:30000:Nix build user 10:/var/empty:/run/current-system/sw/bin/nologin
nixbld11:x:30011:30000:Nix build user 11:/var/empty:/run/current-system/sw/bin/nologin
nixbld12:x:30012:30000:Nix build user 12:/var/empty:/run/current-system/sw/bin/nologin
nixbld13:x:30013:30000:Nix build user 13:/var/empty:/run/current-system/sw/bin/nologin
nixbld14:x:30014:30000:Nix build user 14:/var/empty:/run/current-system/sw/bin/nologin
nixbld15:x:30015:30000:Nix build user 15:/var/empty:/run/current-system/sw/bin/nologin
nixbld16:x:30016:30000:Nix build user 16:/var/empty:/run/current-system/sw/bin/nologin
nixbld17:x:30017:30000:Nix build user 17:/var/empty:/run/current-system/sw/bin/nologin
nixbld18:x:30018:30000:Nix build user 18:/var/empty:/run/current-system/sw/bin/nologin
nixbld19:x:30019:30000:Nix build user 19:/var/empty:/run/current-system/sw/bin/nologin
nixbld20:x:30020:30000:Nix build user 20:/var/empty:/run/current-system/sw/bin/nologin
nixbld21:x:30021:30000:Nix build user 21:/var/empty:/run/current-system/sw/bin/nologin
nixbld22:x:30022:30000:Nix build user 22:/var/empty:/run/current-system/sw/bin/nologin
nixbld23:x:30023:30000:Nix build user 23:/var/empty:/run/current-system/sw/bin/nologin
nixbld24:x:30024:30000:Nix build user 24:/var/empty:/run/current-system/sw/bin/nologin
nixbld25:x:30025:30000:Nix build user 25:/var/empty:/run/current-system/sw/bin/nologin
nixbld26:x:30026:30000:Nix build user 26:/var/empty:/run/current-system/sw/bin/nologin
nixbld27:x:30027:30000:Nix build user 27:/var/empty:/run/current-system/sw/bin/nologin
nixbld28:x:30028:30000:Nix build user 28:/var/empty:/run/current-system/sw/bin/nologin
nixbld29:x:30029:30000:Nix build user 29:/var/empty:/run/current-system/sw/bin/nologin
nixbld30:x:30030:30000:Nix build user 30:/var/empty:/run/current-system/sw/bin/nologin
nixbld31:x:30031:30000:Nix build user 31:/var/empty:/run/current-system/sw/bin/nologin
nixbld32:x:30032:30000:Nix build user 32:/var/empty:/run/current-system/sw/bin/nologin
nobody:x:65534:65534:Unprivileged account (don't use!):/var/empty:/run/current-system/sw/bin/nologin
crw-rw-rw- 1 root root 1, 3 фев 18 22:37 /dev/null
```


it seems i found source of problem...
need to do some more tests, but looks like it does not happening anymore.

i have used hack to write core dumps into /dev/null
```
/etc/sysctl.d/50-coredump.conf

kernel.core_pattern=/dev/null
```
, suggested by  https://wiki.archlinux.org/title/Core_dump

and it looks like after i disabled it, problem does not happening anymore.

**Comment by SuperSandro2000** [comment] 2024-03-22 22:45
Closing, as the article got edited to no longer suggest this

**Closed by SuperSandro2000** 2024-03-22 22:45 UTC
Labels: 0.kind: bug
