### ISSUE TITLE
fetchcargo is non-deterministic

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#14125] opened 2016-03-22 20:13 UTC
## Basic info

To make sure that we are on the same page:
- Kernel: (run `uname -a`) 4.5.0
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...) 16.09.git.cd86f80 (Flounder)
- Nix version: (run `nix-env --version`) 1.11.2
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) 16.09.git.cd86f80
## Describe your issue here

During testing of https://github.com/NixOS/nixpkgs/pull/14088 I managed to get at least two different hashes for `exa`. After some discussion with @jgillich it seems that this derivation can produce non-deterministic output.
### Expected result

Hashes of `fetchcargo` outputs are always the same.
### Actual result

They are not.
### Steps to reproduce

Build `exa` several times.

**Comment by despairblue** [comment] 2016-08-23 15:37
How would one work around that? It basically means the system cannot be rebuild :cry:

**Comment by abbradar** [comment] 2016-08-23 15:40
cc @wizeman

**Comment by abbradar** [comment] 2016-08-23 15:41
@despairblue You can work around it by updating SHA checksum in the affected package locally.

**Comment by despairblue** [comment] 2016-08-24 15:53
@abbradar :confused: Is there any documentation you could point me too. I know how I would to it for packages that I install as a user:

1. checking out nixpkgs repo
2. find the last commit that build for unstable on hydra
3. check that out
4. change the exa's default.nix file
5 run `nix-env -f ~/git/nixpkgs -i exa`

But I think it's also possible to override it in a nix expression, like the one in `/etc/nixos/configuration.nix`, since I installed it as a systems package. The thing is that all ressources I find either explain how to do it for [`.nixpkgs/config.nix`](https://nixos.org/wiki/Nix_Modifying_Packages#Overriding_Existing_Packages) or are [that much out of date](https://stackoverflow.com/questions/29075927/how-to-modify-a-nixos-package-configuration) that they link to [non existent documentation](https://nixos.org/nixos/manual/sec-package-management.html#sec-customising-packages)

**Comment by despairblue** [comment] 2016-08-24 16:07
I changed my configuration.nix to include that: 

```
  environment.systemPackages = with pkgs; [
    # ...
    (pkgs.lib.overrideDerivation pkgs.exa (attrs: {
      depsSha256 = "1klg78ynqvj5gbs4cqsah4vmdfv8iv2va4fsv41l3g0ssja6z5xm";
    }))
    # ...
  ];
```

but to no avail :confused:

**Comment by abbradar** [comment] 2016-08-24 16:37
Sadly we don't have a mechanism to override `depsSha256` (it needs to be supported). However, you can rebuild your whole NixOS from a modified repository:
```
$ nixos-rebuild switch -I nixpkgs=/absolute/path/to/patched/nixpkgs
```

**Comment by abbradar** [comment] 2016-08-24 16:39
Another way to do it is to call patched nixpkgs from your `configuration.nix`:
```
(import /path/to/nixpkgs {}).exa
```

**Comment by despairblue** [comment] 2016-08-24 16:54
Thanks for your help! I really appreciate it.

I tried your last suggestions, but that leads to:

```
building path(s) ‘/nix/store/2w7vws133m7x7ib31js9ric1gpq5wys7-exa-2016-04-20’
unpacking sources
unpacking source archive /nix/store/884pf1gxkcxiydpkfcjfrwvy3jsxax1l-exa-110a1c716bfc4a7f74f74b3c4f0a881c773fcd06-src
source root is exa-110a1c716bfc4a7f74f74b3c4f0a881c773fcd06-src
Using cargo deps from /nix/store/7h2gz0ghd9xsqjymhp22q893ync0zzaa-exa-2016-04-20-fetch
Using indexHash '-ba82b75dd6681d6f'
Using rust registry from /nix/store/wcl2cfdl2v1hfgmgklqwdh71gpb62dwf-rustRegistry-2016-08-10-fe018be
warning: custom registry support via the `registry.index` configuration is being removed, this functionality will not work in the future
    Updating git repository `https://github.com/rust-datetime/zoneinfo-compiled.git`
warning: spurious network error (2 tries remaining): [12/-1] curl error: Couldn't resolve host 'github.com'

warning: spurious network error (1 tries remaining): [12/-1] curl error: Couldn't resolve host 'github.com'

error: failed to load source for a dependency on `zoneinfo_compiled`

Caused by:
  Unable to update https://github.com/rust-datetime/zoneinfo-compiled.git#f56921ea

Caused by:
  failed to fetch into /tmp/nix-build-exa-2016-04-20.drv-0/deps/git/db/zoneinfo-compiled-4887a505c85fb388

To learn more, run the command again with --verbose.
builder for ‘/nix/store/zs8481q35d8xl5gjqvw4v6zv61qgx2rg-exa-2016-04-20.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/l6k5mknhb3hn7g5k43q5iwv471ndbapn-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/4l9cc5l452h5p2mqz56ck96sq4jn86az-nixos-system-firefly-16.09pre88945.5120af0.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/4l9cc5l452h5p2mqz56ck96sq4jn86az-nixos-system-firefly-16.09pre88945.5120af0.drv’ failed
```

It looks like some network hick up, but I tried it multiple times and I opened the github repository from the same machine and it loads fine.

**Comment by abbradar** [comment] 2016-08-24 21:34
Hm, unfortunately I have no idea what's going on -- you've fixed the hash, so it seems like another problem in `fetchcargo`.

**Comment by despairblue** [comment] 2016-08-25 15:27
Still thanks for the help. I learned a lot!

**Comment by globin** [comment] 2016-08-25 22:38
`exa` depends on a git repository in `Cargo.toml` which doesn't work with `fetchcargo`

**Comment by Mic92** [comment] 2016-10-10 08:31
maybe fetchcargo could take an argument to pin git-based dependencies on a certain commit?

**Comment by ticki** [comment] 2017-05-31 18:07
I can confirm that this is still an issue when building `exa`:
```

error: failed to load source for a dependency on `zoneinfo_compiled`

Caused by:
  Unable to update https://github.com/rust-datetime/zoneinfo-compiled.git#f56921ea

```

through AUR/exa-git.

cc @ogham

**Comment by mmahut** [comment] 2019-08-25 18:31
Are there any updates on this issue, please?

**Comment by Mic92** [comment] 2019-08-27 06:06
Should be fixed.

**Closed by Mic92** 2019-08-27 06:06 UTC
Labels: 0.kind: bug
