### ISSUE TITLE
vesktop: cannot enable cloud integrations

### ISSUE THREAD

**Issue by jirafey** [NixOS/nixpkgs#334132] opened 2024-08-12 13:08 UTC
### Describe the bug
Cannot turn on the Cloud Vesktop

### Steps To Reproduce
https://github.com/jirafey/nixconfig/commit/94b67df8fe1e85c45151a58de0dbb885615775a8
my config (does not include a flake to run)
0. Install Vesktop by adding it to your `/etc/nixos/configuration.nix` file. Have Wayland, Gnome, NixOS 24.05
1. Run Vesktop
2. Open settings
3. Open Vencord/Cloud settings
4. Click on the `Enable Cloud Integrations`
5. See that it does not work.

### Expected behavior
1. Run Vesktop
2. Open settings
3. Open Vencord/Cloud settings
4. Click on the `Enable Cloud Integrations`
6. Expect it to turn green and let you use other options

### Screenshots
![image](https://github.com/user-attachments/assets/0ad79860-12f8-4e5c-9c07-fc59931c10a5)

Was able to use Brave to enable Cloud and export settings and import them on Vesktop and see the following (was able to even turn it off):

![image](https://github.com/user-attachments/assets/45956691-5da6-46eb-a258-1171a2fa31fa)
![image](https://github.com/user-attachments/assets/09b2ddea-9fe6-4388-ba6c-cf9b81795977)

### Notify maintainers
**(Sorry got the wrong maintainers before, ping can be ignored)**
@getchoo @Scrumplex @vgskye @pluiedev 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.42, NixOS, 24.05 (Uakari), 24.05.20240727.8c50662`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"home-manager-24.05.tar.gz, nixos-24.05, nixos-hardware"`
 - nixpkgs: `/nix/store/d6533m6b80n3c9lia5kvaz59ad3fynwk-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bddvlpr** [comment] 2024-08-21 14:23
Cannot reproduce this issue, could you try temporarily moving your `.config/vesktop` and let it regenerate?

**Comment by jirafey** [comment] 2024-08-29 18:32
> Cannot reproduce this issue, could you try temporarily moving your `.config/vesktop` and let it regenerate?


I don't have a NixOS machine anymore, please continue this issue without me or just close it.

**Comment by bddvlpr** [comment] 2024-08-29 20:04
Closing as I cannot reproduce this issue. Feel free to reopen if you run in to this issue.

**Closed by bddvlpr** 2024-08-29 20:04 UTC
Labels: 0.kind: bug
