### ISSUE TITLE
Package request: Stirling-PDF 

### ISSUE THREAD

**Issue by hufforguk** [NixOS/nixpkgs#286869] opened 2024-02-07 02:38 UTC
**Project description**

**Metadata**

* homepage URL: https://github.com/Stirling-Tools/Stirling-PDF
* source URL: https://github.com/Stirling-Tools/Stirling-PDF
* license: GPL3
* platforms: Linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment] 2024-02-07 07:29
duplicate of https://github.com/NixOS/nixpkgs/issues/282169

**Closed by dotlambda** 2024-02-07 07:29 UTC
Labels: 0.kind: packaging request
