### ISSUE TITLE
tor-browser-bundle-bin: download error

### ISSUE THREAD

**Issue by pinpox** [NixOS/nixpkgs#108954] opened 2021-01-10 14:43 UTC
**Describe the bug**
The download for `tor-browser-bundle-bin` fails with a 404 error.

**To Reproduce**
```
nix-shell -p pkgs.tor-browser-bundle-bin
```

**Expected behavior**
Tor installs

**Additional context**
```
these 2 derivations will be built:
  /nix/store/pwq01c17ayvzv6hjdxgl838dcgc1bs4f-tor-browser-linux64-10.0.5_en-US.tar.xz.drv
  /nix/store/4bm785cxyvap0ykl8y23c5ibq9433x0q-tor-browser-bundle-bin-10.0.5.drv
Resolved derivation: '/nix/store/pwq01c17ayvzv6hjdxgl838dcgc1bs4f-tor-browser-linux64-10.0.5_en-US.tar.xz.drv' -> '/nix/store/fa4w72m6pwhp1fzfcg83jpcd1m013n0d-tor-browser-linux64-10.0.5_en-US.tar.xz.drv'...
building '/nix/store/fa4w72m6pwhp1fzfcg83jpcd1m013n0d-tor-browser-linux64-10.0.5_en-US.tar.xz.drv'...

trying https://dist.torproject.org/torbrowser/10.0.5/tor-browser-linux64-10.0.5_en-US.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download tor-browser-linux64-10.0.5_en-US.tar.xz from any mirror
error: --- Error --- nix-daemon
builder for '/nix/store/fa4w72m6pwhp1fzfcg83jpcd1m013n0d-tor-browser-linux64-10.0.5_en-US.tar.xz.drv' failed with exit code 1; last 7 log lines:

  trying https://dist.torproject.org/torbrowser/10.0.5/tor-browser-linux64-10.0.5_en-US.tar.xz
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  curl: (22) The requested URL returned error: 404 Not Found
  error: cannot download tor-browser-linux64-10.0.5_en-US.tar.xz from any mirror
error: --- Error --------------------------------------- nix-shell
path '/nix/store/0yy6si2r8sd4y1dvjggmnhf29779arsw-tor-browser-linux64-10.0.5_en-US.tar.xz' is not valid
```

**Notify maintainers**
@offlinehacker @matejc @doublec @thoughtpolice @joachifm @hax404 @scaredmushroom @KarlJoad

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.87, NixOS, 21.03.20210107.f211631 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `"nixos-21.03pre257339.83cbad92d73"`
 - channels(pinpox): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: tor-browser-bundle-bin
```

**Comment by lourkeur** [comment] 2021-01-10 16:45
> * channels(root): `"nixos-21.03pre257339.83cbad92d73"`

Can you update your channel please? 83cbad92d73 is 5 weeks old and as a result, TBB 10.0.5 is out-of-date. This should be fixed in e924c5d80f6a.

Likely duplicate of #107141.

**Comment by pinpox** [comment] 2021-01-10 21:25
Huh, that's strange. I just did:

```bash
nix flake update --recreate-lock-file
nixos-rebuild --flake ".#kartoffel" switch
```
Is that not enought to update a flake-enabled system config?

**Comment by lourkeur** [comment] 2021-01-10 21:28
@pinpox are you using nixflk?

**Comment by pinpox** [comment] 2021-01-10 21:51
@lourkeur no, I'm using this flake: https://github.com/pinpox/nixos/blob/main/flake.nix

**Comment by lourkeur** [comment] 2021-01-10 21:53
can you try `nix shell nixpkgs#tor-browser-bundle-bin` real quick? I'll help you out with the legacy commands right after.

**Comment by pinpox** [comment] 2021-01-10 21:55
@lourkeur Sorry, I just ran:
```
nix-channel --update
sudo nix-channel --update
```
and now it builds fine with `nix shell nixpkgs#tor-browser-bundle-bin`. But I'm a quite confused, I thought updating channels was nothing I should be doing at all with flakes?

**Comment by lourkeur** [comment] 2021-01-10 22:05
> and now it builds fine with `nix shell nixpkgs#tor-browser-bundle-bin`. But I'm a quite confused, I thought updating channels was nothing I should be doing at all with flakes?

The general advice is more along the line of not mixing flakes and channels if possible. In your case what happens is your $NIX_PATH probably contains a reference to `/nix/var/nix/profiles/per-user/root/channels/nixos`, which is an out-of-date channel (installed by default because flakes are still experimental). What I do and what you might want to do is nuke root's channels, and set `nix.nixPath = [ "nixpkgs=${nixpkgs}" ]` to keep hyphenated commands up-to-date and happy during the transition period. ([example](https://github.com/nrdxp/nixflk/blob/9f561b8cead52cd7840ca0bcf75def8f9eb9d207/configuration.nix#L29))

**Comment by pinpox** [comment] 2021-01-10 22:42
@lourkeur Huge thanks, that works. For reference in case anyone finds this:

I remove the nixos channel for `root` and for my user
```
nix-channel --remove nixos
sudo nix-channel --remove nixos
```

Then added to the configuration of all my machines
```nix
nix.nixPath = [ "nixpkgs=${nixpkgs}" ];
```

By adding it to the imports as so:
https://github.com/pinpox/nixos/blob/683caef1306df91420de53f2937fb01c8c2b688b/flake.nix#L22-L25

After rebuilding the configuration (or deploying) I had to logout and in again for $NIX_PATH to be set. It is now 

for my user: `/home/pinpox/.nix-defexpr/channels:nixpkgs=/nix/store/02bj12ja21vibib3c1k065568x1d17ds-source`
for root: `/root/.nix-defexpr/channels:nixpkgs=/nix/store/02bj12ja21vibib3c1k065568x1d17ds-source`

and I can run commands like `nix-shell -p pkgs.tor-browser-bundle-bin` without problems on both accounts. The only issue I still have, is that after rebuilding/rebooting the `nixos` channel seems to "reappear" in `nix-channel --list`. Does it get added automatically?

**Comment by lourkeur** [comment] 2021-01-10 23:02
> @lourkeur Huge thanks, that works. For reference in case anyone finds this:
> 
> I removed the nixos channel for `root` and for my user
> 
> ```
> nix-channel --remove nixos
> sudo nix-channel --remove nixos
> ```
> 
> Then added to the configuration of all my machines
> 
> ```nix
> nix.nixPath = [ "nixpkgs=${nixpkgs}" ];
> ```
> 
> By adding it to the imports as so:
> https://github.com/pinpox/nixos/blob/683caef1306df91420de53f2937fb01c8c2b688b/flake.nix#L22-L25
> 
> After rebuilding the configuration (or deploying) I had to logout and in again for $NIX_PATH to be set. It is now
> 
> for my user: `/home/pinpox/.nix-defexpr/channels:nixpkgs=/nix/store/02bj12ja21vibib3c1k065568x1d17ds-source`
> for root: `/root/.nix-defexpr/channels:nixpkgs=/nix/store/02bj12ja21vibib3c1k065568x1d17ds-source`
> 
> and I can run commands like `nix-shell -p pkgs.tor-browser-bundle-bin` without problems on both accounts. The only issue I still have, is that after rebuilding/rebooting the `nixos` channel seems to "reappear" in `nix-channel --list`. Does it get added automatically?

Good point, it does it on my machines too and comes from [here](https://github.com/NixOS/nixpkgs/blob/8d5eb691015063863e5f962268d62c24b73c6ca7/nixos/modules/services/misc/nix-daemon.nix#L582). Eh. Just ignore it, it'll get fixed eventually.

Have a nice day!

**Closed by lourkeur** 2021-01-10 23:02 UTC
Labels: 0.kind: bug, 2.status: duplicate

**Comment by pinpox** [comment] 2021-01-10 23:26
You too, thanks again for the help. I'll just ingore the channels being still listed then, if that's no problem
