### ISSUE TITLE
GNOME 3 does not start with SDDM

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#24298] opened 2017-03-24 20:19 UTC
## Issue description
using slim since both gdm and sddm failed before

[lastboot.log.txt](https://github.com/NixOS/nixpkgs/files/869082/lastboot.log.txt)

**Comment by vcunat** [comment] 2017-03-25 09:14
I can't see any indication of problems in the log, except for:
```
display-manager.service: Main process exited, code=exited, status=1/FAILURE
```

You may want to try lightdm; IMHO it's the least problematic one.  However, if you tried three already, it seems likely it's not in display manager at all.

**Comment by abbradar** [comment] 2017-03-25 10:31
SDDM was fixed in the current channel. Not sure about GDM.

**Comment by RonnyPfannschmidt** [comment] 2017-03-25 10:48
sdmm works on master for starting plasma5, it wont start gnome3

**Comment by abbradar** [comment] 2017-03-25 10:50
Not sure if that's expected behaviour, it may be that GNOME 3 really requires GDM nowadays. Maybe see if that works on Fedora/Arch?

**Comment by RonnyPfannschmidt** [comment] 2017-03-25 10:55
@globin just just verified that gnome3 is broken

**Comment by globin** [comment] 2017-03-25 14:01
see also #24172

**Comment by hdonnay** [comment] 2017-11-03 03:00
`gsd-datetime` segfaults, which causes `gnome-session` to bail out, if you have automatic timezone management enabled. This can be undone via grubbing around with `dconf` on a tty: `dconf reset /org/gnome/desktop/datetime/automatic-timezone` (see #30022)

Any attempts by gnome to deal with user accounts seem to be broken on my system, as gdm lists nothing and the user control widget segfaults.

**Comment by alexeymuranov** [comment] 2017-11-03 08:59
Just in case: there is an issue #19164 with logging in with GDM into a new account.

**Comment by jtojnar** [comment] 2017-12-15 21:49
@abbradar

> Not sure if that's not expected behaviour, it may be that GNOME 3 really requires GDM nowadays. Maybe see if that works on Fedora/Arch?

GNOME Shell should still be independent of the display manager. It works at least with LightDM.

**Comment by jtojnar** [comment] 2018-08-06 23:07
With https://github.com/NixOS/nixpkgs/pull/43992, GNOME starts in SDDM.

**Closed by jtojnar** 2018-08-06 23:07 UTC
Labels: 6.topic: gnome3

**Comment by alexeymuranov** [comment] 2018-09-29 17:40
Hm, currently, on NixOS 18.09, I cannot even enable both SDDM display manager and GNOME3 desktop manager, apparently because enabling GNOME3 automatically enables GDM, which conflicts with SDDM:
```console
# nixos-rebuild boot
building Nix...
building the system configuration...
error: The unique option `services.xserver.displayManager.job.execCmd' is defined multiple times, in `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/x11/display-managers/sddm.nix' and `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/x11/display-managers/gdm.nix'.
(use '--show-trace' to show detailed location information)
```

**Comment by jtojnar** [comment] 2018-09-29 19:54
Yup: https://github.com/NixOS/nixpkgs/commit/fc035da4a4a39d860e0edea0c95c6ca2de79e889

You can explicitly disable it with `services.xserver.displayManager.gdm.enable = false`.  However, note that GNOME does not really support other DMs and some features (screen lock, IIRC) might be missing.
