### ISSUE TITLE
python modules depending on pyexpat broken, wide-spread downstream breakage

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#23497] opened 2017-03-04 18:31 UTC
## Issue description

Re-opening this issue, because it was prematurely closed by @FRidh 

### Steps to reproduce

Sync `nixpkgs` to master, attempt to build, for instance, `borgbackup`:

```
~/src/nixpkgs $ git fetch --all
Fetching nixos
Fetching origin
Fetching peti
~/src/nixpkgs $ git checkout nixos/master
Note: checking out 'nixos/master'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 56e71f62dc... Add locateDominatingFile lib function
~/src/nixpkgs $ git show
commit 56e71f62dc49e64fcd37768cc7d1ec219d4990e6
Author: Shea Levy <shea@shealevy.com>
Date:   Sat Mar 4 13:15:23 2017 -0500

    Add locateDominatingFile lib function

diff --git a/lib/default.nix b/lib/default.nix
index c0d7899b88..09a64f754d 100644
--- a/lib/default.nix
+++ b/lib/default.nix
@@ -34,6 +34,9 @@ let
   sandbox = import ./sandbox.nix;
   fetchers = import ./fetchers.nix;
 
+  # Eval-time filesystem handling
+  filesystem = import ./filesystem.nix;
+
 in
   { inherit trivial
             attrsets lists strings stringsWithDeps
@@ -41,7 +44,7 @@ in
             modules options types
             licenses platforms systems
             debug generators misc
-            sandbox fetchers;
+            sandbox fetchers filesystem;
   }
   # !!! don't include everything at top-level; perhaps only the most
   # commonly used functions.
diff --git a/lib/filesystem.nix b/lib/filesystem.nix
new file mode 100644
index 0000000000..91b04d81c1
--- /dev/null
+++ b/lib/filesystem.nix
@@ -0,0 +1,26 @@
+{ # locateDominatingFile :  RegExp
+  #                      -> Path
+  #                      -> Nullable { path : Path;
+  #                                    matches : [ MatchResults ];
+  #                                  }
+  # Find the first directory containing a file matching 'pattern'
+  # upward from a given 'file'.
+  # Returns 'null' if no directories contain a file matching 'pattern'.
+  locateDominatingFile = pattern: file:
+    let go = path:
+          let files = builtins.attrNames (builtins.readDir path);
+              matches = builtins.filter (match: match != null)
+                          (map (builtins.match pattern) files);
+          in
+            if builtins.length matches != 0
+              then { inherit path matches; }
+              else if path == /.
+                then null
+                else go (dirOf path);
+        parent = dirOf file;
+        isDir =
+          let base = baseNameOf file;
+              type = (builtins.readDir parent).${base} or null;
+          in file == /. || type == "directory";
+    in go (if isDir then file else parent);
+}
~/src/nixpkgs $ nix-env --file ~/src/nixpkgs --install --attr borgbackup
installing ‘borgbackup-1.0.9’
these derivations will be built:
  /nix/store/f1dw36idhfhav9b4vaq1429b8b6n4wiy-python3.4-setuptools-30.2.0.drv
  /nix/store/644s9fabv3j72zcn2p8575fvnyp0g5zd-python3.4-pbr-1.8.1.drv
  /nix/store/i33csbiwjdki3zbrahwrbwyfg1548vas-python3.4-linecache2-1.0.0.drv
  /nix/store/h2a8zn545wnakr6w38wzg9r9qq5wjj7g-python3.4-traceback2-1.4.0.drv
  /nix/store/g7869fpp1ggdrr48vvayygxng70s1ffs-python3.4-py-1.4.31.drv
  /nix/store/glbjk955z7a8krb2fml0ws9vs6ha2qvf-python3.4-hypothesis-3.6.0.drv
  /nix/store/9csviv0a7hz6rqq2mpa50sipl9l16fag-python3.4-pytest-3.0.6.drv
  /nix/store/nr98nzhrnfk320ghd2r9lmnfrbzsmxna-python3.4-six-1.10.0.drv
  /nix/store/cgjpn6ba5lb5q32na7k1b4hgxcxbks7r-python3.4-unittest2-1.1.0.drv
  /nix/store/2l3s56apdppwpw6zwvcbf7xhp1vy8d6c-python3.4-funcsigs-1.0.2.drv
  /nix/store/kljwf5lqpan4wi2anfay3slyka60z8sp-python3.4-mock-2.0.0.drv
  /nix/store/qypk677p8959xi99zjj4r3xskqn4q36h-python3.4-coverage-4.0.1.drv
  /nix/store/18qjgi6dghkvmilhg8q861dx544bamav-python3.4-nose-1.3.7.drv
  /nix/store/7wx5gn2brvs0vn8rcxq5fpxjy6rlzjkl-python3.4-pretend-1.0.8.drv
  /nix/store/dm21rhar5ypasc5kxf50jp1ln63a32fj-python3.4-virtualenv-15.0.3.drv
  /nix/store/iyg18pnwfyxi6ma9i63snrdahf5hkyqw-python3.4-scripttest-1.3.drv
  /nix/store/b1y2pkvk8aa9hmn6ba2rnr9c073fja78-python3.4-pip-9.0.1.drv
  /nix/store/izp7l5pl5l5z6vq25p97nkl36471lm62-python3.4-setuptools_scm-1.11.1.drv
  /nix/store/27m2mgm9711565a13vjzl6n435j7rbg5-python3.4-pytest-runner-2.6.2.drv
  /nix/store/3s0jq1gk5qjjimfg9cwn80v1lgidchsw-python3.4-pytz-2016.6.1.drv
  /nix/store/4fp8zvwhwdin2y5vamfkyyp55kssgbvr-python3.4-markupsafe-0.23.drv
  /nix/store/8mx2i7xk5a75pkkm3b44hazmdw9v10bk-python3.4-sphinx_rtd_theme-0.1.9.drv
  /nix/store/8pqjvji070annp1mswlby4wk6zvkw3nd-python3.4-contextlib2-0.5.3.drv
  /nix/store/972n0csgmf481in5lykmda72bl6rs6nx-python3.4-llfuse-1.0.drv
  /nix/store/5hxf1cqrha5bvssqpbmaahd61vm2d2sx-python3.4-requests-2.13.0.drv
  /nix/store/71rk5qhla707lmnifyz95vjymrlba1yg-python3.4-Jinja2-2.9.5.drv
  /nix/store/5h2p6w6rz1r80bm8l7mh0shng7g2qxxn-python3.4-mccabe-0.5.3.drv
  /nix/store/a05xja542ns22q42i4bl2fiblnyfx4n7-python3.4-pycodestyle-2.0.0.drv
  /nix/store/g0w1577simgjqfch2014mqkc60w03fi9-python3.4-pyflakes-1.3.0.drv
  /nix/store/5s8liq2r84c7c42ccdagb8zdfirdkwyz-python3.4-flake8-3.2.1.drv
  /nix/store/mrfrc7jicx17qcl9aimml0zq1q1h8dg8-python3.4-u-msgpack-python-2.3.0.drv
  /nix/store/h9bhv26xmxgd5w1ihjqnp46fdy6zafm3-python3.4-pytest-expect-1.1.0.drv
  /nix/store/l8wfwj31w3rw4i95pk1qqmqakl91lamg-python3.4-webencodings-0.5.drv
  /nix/store/82rfznn6waspdmxaxykmjc2pf4ax8wk3-python3.4-html5lib-0.999999999.drv
  /nix/store/8vxklgizaw0qqljf2id2swbhkqrx42qr-python3.4-Whoosh-2.7.4.drv
  /nix/store/c5673fbwksya6jkg8k3asp9aqdm7qzb0-python3.4-imagesize-0.7.0.drv
  /nix/store/f3wc6ixa2230y8v2dcc101ndvjz6slgs-python3.4-apipkg-1.4.drv
  /nix/store/j4xbflkxbx94z32g3mn2bj8m5fbjdbbs-python3.4-execnet-1.4.1.drv
  /nix/store/rwzbyrg35y01xkbgprq798hpqw5mgsxl-python3.4-pytest-xdist-1.8.drv
  /nix/store/crqrph237mrrwq6g1mnnfll72cnsd0fl-python3.4-SQLAlchemy-1.0.15.drv
  /nix/store/jinz4yydnz31skqs2izgnyaw9187izkc-python3.4-docutils-0.13.1.drv
  /nix/store/jcd67x5wv0309fs0018czcz8wwybnh8w-python3.4-Pygments-2.2.0.drv
  /nix/store/dhix0az70kngd8s69p35cng1fpf62xpj-python3.4-alabaster-0.7.7.drv
  /nix/store/drabn4p1fyglz79y2b80wf6l2aidjh0f-python3.4-simplejson-3.8.1.drv
  /nix/store/jv73mryv8qj82mlc1smipghrl9lbi23s-python3.4-Babel-2.3.4.drv
  /nix/store/jlzwwqz4zq4c9r289w85ig2ycdlkxdv5-python3.4-PyStemmer-1.3.0.drv
  /nix/store/l9l3phc9zjy099if1vzphkzlnndkqb60-python3.4-snowballstemmer-1.2.1.drv
  /nix/store/dz7b5ngvkpynbndf69g180bj0lhyi18g-python3.4-Sphinx-1.5.2.drv
  /nix/store/n5q8q1l970xgz0kjshrbhab8q07sbppz-python3.4-numpy-1.11.3.drv
  /nix/store/n8g5fxz7hgys43lpx2323qyl4l1ixvlz-python3.4-Cython-0.25.2.drv
  /nix/store/nf4rpgpl5nz7l2n6da7hiaiv7n98yyb6-python3.4-msgpack-python-0.4.7.drv
  /nix/store/4hys2a9ia42bw6gy0h4dk4zc3zn28hmc-borgbackup-1.0.9.drv
building path(s) ‘/nix/store/p3mha6n09lnl7vbkw71g6db5snfs3rfn-python3.4-setuptools-30.2.0’
unpacking sources
unpacking source archive /nix/store/70xydxh5ik64fc3r7rswhqqgly512n26-setuptools-30.2.0.tar.gz
source root is setuptools-30.2.0
setting SOURCE_DATE_EPOCH to timestamp 1480866953 of file setuptools-30.2.0/setuptools.egg-info/top_level.txt
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import setuptools
  File "/tmp/nix-build-python3.4-setuptools-30.2.0.drv-0/setuptools-30.2.0/setuptools/__init__.py", line 10, in <module>
    from setuptools.extern.six.moves import filter, filterfalse, map
  File "/tmp/nix-build-python3.4-setuptools-30.2.0.drv-0/setuptools-30.2.0/setuptools/extern/__init__.py", line 1, in <module>
    from pkg_resources.extern import VendorImporter
  File "/tmp/nix-build-python3.4-setuptools-30.2.0.drv-0/setuptools-30.2.0/pkg_resources/__init__.py", line 35, in <module>
    import plistlib
  File "/nix/store/xqs40n8lq4faidjgj3y1lq25qarzrns0-python3-3.4.6/lib/python3.4/plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
  File "/nix/store/xqs40n8lq4faidjgj3y1lq25qarzrns0-python3-3.4.6/lib/python3.4/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: No module named 'pyexpat'
builder for ‘/nix/store/f1dw36idhfhav9b4vaq1429b8b6n4wiy-python3.4-setuptools-30.2.0.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/4hys2a9ia42bw6gy0h4dk4zc3zn28hmc-borgbackup-1.0.9.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/4hys2a9ia42bw6gy0h4dk4zc3zn28hmc-borgbackup-1.0.9.drv’ failed
```

If I revert 57ded03833df30d15fbfe9238f02ddf1a88d2c65, which specifically mentions changing how `expat` is handled for python-3.4, the builds work again.

**Comment by vcunat** [comment] 2017-03-05 07:06
I believe this is duplicate of https://github.com/NixOS/nixpkgs/issues/23325, and it should be fixed in master ATM (channels can take some time).

**Closed by vcunat** 2017-03-05 07:06 UTC

**Comment by FRidh** [comment] 2017-03-05 09:48
The fix wasn't yet in the revision you refer to here.
