### ISSUE TITLE
caff crashes

### ISSUE THREAD

**Issue by sim6** [NixOS/nixpkgs#355399] opened 2024-11-12 11:33 UTC
### Describe the bug
caff crashes

### Steps To Reproduce
1. Run `nix-shell -p signing-party` (or install via nixos configuration) 
2. Run `caff`
3. Crash
```
Can't locate Sub/HandlesVia.pm in @INC (you may need to install the Sub::HandlesVia module) (@INC entries checked: /nix/store/0viin4ajpic7rkjw32cpv32nrh5xp596-perl5.38.2-Text-Template-1.61/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /nix/store/0viin4ajpic7rkjw32cpv32nrh5xp596-perl5.38.2-Text-Template-1.61/lib/perl5/site_perl/5.38.2 /nix/store/0viin4ajpic7rkjw32cpv32nrh5xp596-perl5.38.2-Text-Template-1.61/lib/perl5/site_perl /nix/store/g5icw4lfa4xx28qaj5mnzw95zsidxcb1-perl5.38.2-MIME-tools-5.509/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /nix/store/g5icw4lfa4xx28qaj5mnzw95zsidxcb1-perl5.38.2-MIME-tools-5.509/lib/perl5/site_perl/5.38.2 /nix/store/g5icw4lfa4xx28qaj5mnzw95zsidxcb1-perl5.38.2-MIME-tools-5.509/lib/perl5/site_perl /nix/store/gv3kaxw3773cqh73faqmmgr00y8n9jlp-perl5.38.2-MailTools-2.21/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /nix/store/gv3kaxw3773cqh73faqmmgr00y8n9jlp-perl5.38.2-MailTools-2.21/lib/perl5/site_perl/5.38.2 /nix/store/gv3kaxw3773cqh73faqmmgr00y8n9jlp-perl5.38.2-MailTools-2.21/lib/perl5/site_perl /nix/store/5pxv45ldd7hr76p5q7gvm5vgi6ivng4v-perl5.38.2-TimeDate-2.33/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /nix/store/5pxv45ldd7hr76p5q7gvm5vgi6ivng4v-perl5.38.2-TimeDate-2.33/lib/perl5/site_perl/5.38.2 /nix/store/5pxv45ldd7hr76p5q7gvm5vgi6ivng4v-perl5.38.2-TimeDate-2.33/lib/perl5/site_perl /nix/store/jrl6mn1vwbhwj91a1vm14jfk7w5cci82-perl5.38.2-Net-IDN-Encode-2.500/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /nix/store/jrl6mn1vwbhwj91a1vm14jfk7w5cci82-perl5.38.2-Net-IDN-Encode-2.500/lib/perl5/site_perl/5.38.2 /nix/store/jrl6mn1vwbhwj91a1vm14jfk7w5cci82-perl5.38.2-Net-IDN-Encode-2.500/lib/perl5/site_perl /nix/store/jz12rrsj35p68kwi98ji6fbs4fjzgfvv-perl5.38.2-strictures-2.000006/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /nix/store/jz12rrsj35p68kwi98ji6fbs4fjzgfvv-perl5.38.2-strictures-2.000006/lib/perl5/site_perl/5.38.2 /nix/store/jz12rrsj35p68kwi98ji6fbs4fjzgfvv-perl5.38.2-strictures-2.000006/lib/perl5/site_perl /nix/store/212q1hgy7lbw4a52df5yi1lqdyry9q7a-perl5.38.2-Class-Method-Modifiers-2.15/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /nix/store/212q1hgy7lbw4a52df5yi1lqdyry9q7a-perl5.38.2-Class-Method-Modifiers-2.15/lib/perl5/site_perl/5.38.2 /nix/store/212q1hgy7lbw4a52df5yi1lqdyry9q7a-perl5.38.2-Class-Method-Modifiers-2.15/lib/perl5/site_perl /nix/store/qgx1lw16bd3h11km4fnvhrvjxgjb598l-perl5.38.2-Data-Perl-0.002011/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /nix/store/qgx1lw16bd3h11km4fnvhrvjxgjb598l-perl5.38.2-Data-Perl-0.002011/lib/perl5/site_perl/5.38.2 /nix/store/qgx1lw16bd3h11km4fnvhrvjxgjb598l-perl5.38.2-Data-Perl-0.002011/lib/perl5/site_perl /nix/store/d11ak37llrwb2am7bb0kkizica555ihw-perl5.38.2-Devel-GlobalDestruction-0.14/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /nix/store/d11ak37llrwb2am7bb0kkizica555ihw-perl5.38.2-Devel-GlobalDestruction-0.14/lib/perl5/site_perl/5.38.2 /nix/store/d11ak37llrwb2am7bb0kkizica555ihw-perl5.38.2-Devel-GlobalDestruction-0.14/lib/perl5/site_perl /nix/store/r25mmcp0kp3vkiq7s6qkcmsnxys9cj9h-perl5.38.2-Exporter-Tiny-1.006002/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /nix/store/r25mmcp0kp3vkiq7s6qkcmsnxys9cj9h-perl5.38.2-Exporter-Tiny-1.006002/lib/perl5/site_perl/5.38.2 /nix/store/r25mmcp0kp3vkiq7s6qkcmsnxys9cj9h-perl5.38.2-Exporter-Tiny-1.006002/lib/perl5/site_perl /nix/store/q54hffii6xgl8afxpr517r8vgx8d0vrh-perl5.38.2-GnuPG-Interface-1.03/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /nix/store/q54hffii6xgl8afxpr517r8vgx8d0vrh-perl5.38.2-GnuPG-Interface-1.03/lib/perl5/site_perl/5.38.2 /nix/store/q54hffii6xgl8afxpr517r8vgx8d0vrh-perl5.38.2-GnuPG-Interface-1.03/lib/perl5/site_perl /nix/store/x99l36xb47aq2xi0zzysd5vr0qn04a1j-perl5.38.2-List-MoreUtils-0.430/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /nix/store/x99l36xb47aq2xi0zzysd5vr0qn04a1j-perl5.38.2-List-MoreUtils-0.430/lib/perl5/site_perl/5.38.2 /nix/store/x99l36xb47aq2xi0zzysd5vr0qn04a1j-perl5.38.2-List-MoreUtils-0.430/lib/perl5/site_perl /nix/store/bhjim3zhm7mh4pgbbw6xrhm26ag8hvm4-perl5.38.2-Module-Runtime-0.016/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /nix/store/bhjim3zhm7mh4pgbbw6xrhm26ag8hvm4-perl5.38.2-Module-Runtime-0.016/lib/perl5/site_perl/5.38.2 /nix/store/bhjim3zhm7mh4pgbbw6xrhm26ag8hvm4-perl5.38.2-Module-Runtime-0.016/lib/perl5/site_perl /nix/store/4lvi27z131kf356h0xchp473mr96cz80-perl5.38.2-Moo-2.005005/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /nix/store/4lvi27z131kf356h0xchp473mr96cz80-perl5.38.2-Moo-2.005005/lib/perl5/site_perl/5.38.2 /nix/store/4lvi27z131kf356h0xchp473mr96cz80-perl5.38.2-Moo-2.005005/lib/perl5/site_perl /nix/store/cd4cpjg93fn03g22c42l0ybg87mlz94z-perl5.38.2-MooX-HandlesVia-0.001009/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /nix/store/cd4cpjg93fn03g22c42l0ybg87mlz94z-perl5.38.2-MooX-HandlesVia-0.001009/lib/perl5/site_perl/5.38.2 /nix/store/cd4cpjg93fn03g22c42l0ybg87mlz94z-perl5.38.2-MooX-HandlesVia-0.001009/lib/perl5/site_perl /nix/store/17ni6cc5fwhzahw3b16w53sb94m2mhfl-perl5.38.2-MooX-late-0.100/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /nix/store/17ni6cc5fwhzahw3b16w53sb94m2mhfl-perl5.38.2-MooX-late-0.100/lib/perl5/site_perl/5.38.2 /nix/store/17ni6cc5fwhzahw3b16w53sb94m2mhfl-perl5.38.2-MooX-late-0.100/lib/perl5/site_perl /nix/store/n16n3ln0mwn4nr1avbikj5yk0wm048az-perl5.38.2-Role-Tiny-2.002004/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /nix/store/n16n3ln0mwn4nr1avbikj5yk0wm048az-perl5.38.2-Role-Tiny-2.002004/lib/perl5/site_perl/5.38.2 /nix/store/n16n3ln0mwn4nr1avbikj5yk0wm048az-perl5.38.2-Role-Tiny-2.002004/lib/perl5/site_perl /nix/store/6h0kgs88nbmh9xfdg2l61k2yafvh0j3x-perl5.38.2-Sub-Exporter-Progressive-0.001013/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /nix/store/6h0kgs88nbmh9xfdg2l61k2yafvh0j3x-perl5.38.2-Sub-Exporter-Progressive-0.001013/lib/perl5/site_perl/5.38.2 /nix/store/6h0kgs88nbmh9xfdg2l61k2yafvh0j3x-perl5.38.2-Sub-Exporter-Progressive-0.001013/lib/perl5/site_perl /nix/store/xg7sax3n31svx4w6h3czmvg0q5hblfls-perl5.38.2-Sub-Quote-2.006008/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /nix/store/xg7sax3n31svx4w6h3czmvg0q5hblfls-perl5.38.2-Sub-Quote-2.006008/lib/perl5/site_perl/5.38.2 /nix/store/xg7sax3n31svx4w6h3czmvg0q5hblfls-perl5.38.2-Sub-Quote-2.006008/lib/perl5/site_perl /nix/store/y4r93d0pvxzf47fpcrf621383zamrfrq-perl5.38.2-Type-Tiny-2.004000/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /nix/store/y4r93d0pvxzf47fpcrf621383zamrfrq-perl5.38.2-Type-Tiny-2.004000/lib/perl5/site_perl/5.38.2 /nix/store/y4r93d0pvxzf47fpcrf621383zamrfrq-perl5.38.2-Type-Tiny-2.004000/lib/perl5/site_perl /nix/store/0q18w9117lnqyx99dpv0iygqk15zsibb-perl-5.38.2/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /nix/store/0q18w9117lnqyx99dpv0iygqk15zsibb-perl-5.38.2/lib/perl5/site_perl/5.38.2 /nix/store/0q18w9117lnqyx99dpv0iygqk15zsibb-perl-5.38.2/lib/perl5/5.38.2/x86_64-linux-thread-multi /nix/store/0q18w9117lnqyx99dpv0iygqk15zsibb-perl-5.38.2/lib/perl5/5.38.2) at /nix/store/17ni6cc5fwhzahw3b16w53sb94m2mhfl-perl5.38.2-MooX-late-0.100/lib/perl5/site_perl/5.38.2/MooX/late.pm line 81.
BEGIN failed--compilation aborted at /nix/store/q54hffii6xgl8afxpr517r8vgx8d0vrh-perl5.38.2-GnuPG-Interface-1.03/lib/perl5/site_perl/5.38.2/GnuPG/Interface.pm line 16.
Compilation failed in require at /nix/store/h3ckil4630y9v00213kz7pfhdbxp0k66-signing-party-2.11/bin/.caff-wrapped line 427.
BEGIN failed--compilation aborted at /nix/store/h3ckil4630y9v00213kz7pfhdbxp0k66-signing-party-2.11/bin/.caff-wrapped line 427.
```

### Expected behavior
caff runs and explain their options

### Notify maintainers
@primeos

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.58, NixOS, 24.05 (Uakari), 24.05.6529.9256f7c71a19`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by samueltardieu** [comment] 2024-11-12 11:47
(duplicate of #352117)

**Closed** 2024-11-12 11:46 UTC
Labels: 0.kind: bug

**Comment by sim6** [comment] 2024-11-15 16:35
Can it be ported to
