### ISSUE TITLE
Onboard fails to start

### ISSUE THREAD

**Issue by rittelle** [NixOS/nixpkgs#43675] opened 2018-07-17 15:36 UTC
## Issue description

Onboard (the virtual keyboard) fails to start with:
```
$ onboard
Traceback (most recent call last):
  File "/nix/store/hz0nis98ajx70sdhqkg45mgskczs3z2j-onboard-1.4.1/bin/..onboard-wrapped-wrapped", line 36, in <module>
    from Onboard.OnboardGtk import OnboardGtk as Onboard
  File "/nix/store/hz0nis98ajx70sdhqkg45mgskczs3z2j-onboard-1.4.1/lib/python3.6/site-packages/Onboard/OnboardGtk.py", line 35, in <module>
    require_gi_versions()
  File "/nix/store/hz0nis98ajx70sdhqkg45mgskczs3z2j-onboard-1.4.1/lib/python3.6/site-packages/Onboard/Version.py", line 24, in require_gi_versions
    gi.require_version('Gtk', '3.0')
  File "/nix/store/wjbcd5x8ixql6j0d9wwibk00a0svs1d0-python3.6-pygobject-3.26.1/lib/python3.6/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

### Steps to reproduce

Run `nix-shell -p onboard --run onboard` in a shell.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.54, NixOS, 18.03.132847.aec217852f2 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by rittelle** [comment] 2018-07-17 16:22
I just noticed that this is fixed in unstable.
I'm leaving this open until it is fixed in stable.

**Comment by vcunat** [comment] 2018-07-28 11:56
Merged.

**Closed by vcunat** 2018-07-28 11:56 UTC

**Comment by isaacwhanson** [comment] 2019-06-08 16:30
I am commenting here because this same symptom is seen again with the onboard package.  However, I believe the cause is different.  I think this is the same issue as resolved in this MR:
https://github.com/NixOS/nixpkgs/pull/59968/commits/184f7f2ad857fef2bb1992d2018329b37c8ff9f0

I was able to fix this in my system by overriding attribute strictDeps, setting it to false.
