### ISSUE TITLE
ps: UNKNOWN version reported by ps

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#40224] opened 2018-05-09 13:18 UTC
## Issue description
```nix-shell -I nixpkgs=channel:nixos-unstable -p procps --run 'ps --version'```
returns
`ps from procps-ng UNKNOWN`

**Comment by xeji** [comment] 2018-05-09 15:12
duplicate of #39538 , fix is in staging and will move to master in due course.

**Closed by xeji** 2018-05-09 15:12 UTC
