### ISSUE TITLE
Wrong default value for `services.openssh.ciphers` in search.nixos.org

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#136733] opened 2021-09-04 23:55 UTC
The `services.openssh.ciphers` has wrong example on https://search.nixos.org/options?channel=21.05&show=services.openssh.ciphers&from=0&size=50&sort=relevance&type=packages&query=openssh

The website has unexpected `,`:

![image](https://user-images.githubusercontent.com/11302521/132110647-624eccf3-ae64-41ab-82ac-8ff4c4a17b41.png)

Which are not present in the code definition:

https://github.com/NixOS/nixpkgs/blob/nixos-21.05/nixos/modules/services/networking/ssh/sshd.nix#L304

And cause syntax error:

![image](https://user-images.githubusercontent.com/11302521/132110665-4e5e7a75-64c9-4b6a-8435-eb2484bae7da.png)

**Comment by wamserma** [comment] 2021-09-05 07:02
This can also be observed with other options, e.g. https://search.nixos.org/options?channel=21.05&show=boot.blacklistedKernelModules&from=0&size=50&sort=relevance&type=packages&query=boot.BlacklistedkernelModules

The issue is already tracked in the appropriate repository, see https://github.com/NixOS/nixos-search/issues/351, so I'm closing this issue here.

**Closed by wamserma** 2021-09-05 07:02 UTC
