### ISSUE TITLE
useOSProber fails to detect (LVM-installed) OSes

### ISSUE THREAD

**Issue by jakobrs** [NixOS/nixpkgs#76690] opened 2019-12-30 11:54 UTC
**Describe the bug**
Setting `boot.loader.grub.useOSProber = true;` in `configuration.nix` does *not* add Ubuntu to GRUB, despite `sudo os-prober` finding it. Ubuntu is on an LVM partition, but NixOS is not.

**To Reproduce**
1. `Add boot.loader.grub.useOSProber = true;` to `configuration.nix`
2. `sudo nixos-rebuild switch --install-bootloader`

**Expected behavior**
Ubuntu appearing in GRUB

**Additional context**
- [Configuration](https://github.com/jakobrs/nixos-configuration/blob/os-prober-madness/configuration.nix)
- UEFI
- Partition format:
  ```
  /dev/sda
  + /dev/sda1             FAT32 ESP system partition
  + /dev/sda2             LVM partition
  | + /dev/vgubuntu/root  Ubuntu root
  | + /dev/vgubuntu/swap  Ubuntu swap
  + /dev/sda3             ext4 partition with NixOS
  ```
- Running `nix-shell -p os-prober --run "sudo os-prober"` yields
  ```
  /dev/mapper/vgubuntu-root:Ubuntu 19.10 (19.10):Ubuntu:linux
  ```
- **This *did* work with a previous installation of Ubuntu that was not using LVM.**

**Metadata**
- system: `"x86_64-linux"`
- host os: `Linux 5.4.1, NixOS, 19.09.1529.808d3c6d123 (Loris)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.3`
- channels(jakob): `"nixpkgs-20.03pre206749.5a3c1eda46e"`
- nixpkgs: `/home/jakob/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by symphorien** [comment] 2019-12-30 14:16
Can you run os-prober as root to see if it detects the other os ?

**Comment by symphorien** [comment] 2019-12-30 14:21
Ah sorry, you wrote it does detect it.
Can you check that the expected configuration is present in /boot/grub/grub.cfg ?
Can you check that the expected configuration is output to the systemd-journal ? `journalctl | grep -C 50  "BEGIN /etc/grub.d/30_os-prober"`

**Comment by symphorien** [comment] 2019-12-30 14:33
Can you also paste the output of `linux-boot-prober /dev/mapper/vgubuntu-root` ?

**Comment by jakobrs** [comment] 2019-12-30 14:53
- Ubuntu is not mentioned in grub.cfg. GitHub doesn't let me attach the file, so [here](https://gist.github.com/jakobrs/538da12704ff5311f7c859cd9011b347) it is as a gist. There's nothing interesting in it though.
- `journalctl`'s output is also in [the same gist](https://gist.github.com/jakobrs/538da12704ff5311f7c859cd9011b347).
- Output of `linux-boot-prober`:
  ```
  /dev/mapper/vgubuntu-root:/dev/mapper/vgubuntu-root:Ubuntu:/boot/vmlinuz-5.3.0-24-generic:/boot/initrd.img-5.3.0-24-generic:root=/dev/mapper/vgubuntu-root ro quiet splash $vt_handoff
  /dev/mapper/vgubuntu-root:/dev/mapper/vgubuntu-root:Ubuntu, with Linux 5.3.0-24-generic:/boot/vmlinuz-5.3.0-24-generic:/boot/initrd.img-5.3.0-24-generic:root=/dev/mapper/vgubuntu-root ro quiet splash $vt_handoff
  /dev/mapper/vgubuntu-root:/dev/mapper/vgubuntu-root:Ubuntu, with Linux 5.3.0-24-generic (recovery mode):/boot/vmlinuz-5.3.0-24-generic:/boot/initrd.img-5.3.0-24-generic:root=/dev/mapper/vgubuntu-root ro recovery nomodeset
  /dev/mapper/vgubuntu-root:/dev/mapper/vgubuntu-root:Ubuntu, with Linux 5.3.0-23-generic:/boot/vmlinuz-5.3.0-23-generic:/boot/initrd.img-5.3.0-23-generic:root=/dev/mapper/vgubuntu-root ro quiet splash $vt_handoff
  /dev/mapper/vgubuntu-root:/dev/mapper/vgubuntu-root:Ubuntu, with Linux 5.3.0-23-generic (recovery mode):/boot/vmlinuz-5.3.0-23-generic:/boot/initrd.img-5.3.0-23-generic:root=/dev/mapper/vgubuntu-root ro recovery nomodeset
```

**Comment by symphorien** [comment] 2019-12-30 15:39
Next possible culprit:
```
pkgdatadir=$(nix-build '<nixpkgs>' -A grub2 --no-out-link)/share/grub $(nix-build '<nixpkgs>' -A grub2 --no-out-link)/etc/grub.d/30_os-prober 
```
as root in a shell where os-prober is available.
If this does not output anything, try debugging with bash -x.
If this does output something, then the problem is that for some reason nixos-rebuild does not reinstall the bootloader.

**Comment by jakobrs** [comment] 2019-12-30 15:44
That does output something. I'll update the gist.

**Comment by symphorien** [comment] 2019-12-30 15:48
The offending code is here: 

https://github.com/NixOS/nixpkgs/blob/release-19.09/nixos/modules/system/boot/loader/grub/install-grub.pl#L518-L522

I don't see why it wouldn't run.

**Comment by jakobrs** [comment] 2020-01-02 10:55
It appears that those lines *are* getting run, which I've verified using this patch:
```diff
diff --git a/nixos/modules/system/boot/loader/grub/install-grub.pl b/nixos/modules/system/boot/loader/grub/install-grub.pl
index a09c5dc4761..c7540acaef7 100644
--- a/nixos/modules/system/boot/loader/grub/install-grub.pl
+++ b/nixos/modules/system/boot/loader/grub/install-grub.pl
@@ -518,6 +518,8 @@ my $efiTarget = getEfiTarget();
 # Append entries detected by os-prober
 if (get("useOSProber") eq "true") {
     my $targetpackage = ($efiTarget eq "no") ? $grub : $grubEfi;
+    print $targetpackage;
+    system(get("shell"), "-c", "echo Hello from install-grub.pl");
     system(get("shell"), "-c", "pkgdatadir=$targetpackage/share/grub $targetpackage/etc/grub.d/30_os-prober >> $tmpFile");
 }
```

**Comment by jakobrs** [comment] 2020-01-02 19:54
I believe I might have figured out the problem. `install-grub.pl` calls `30_os-prober`, which calls `os-prober`, which calls `.os-prober-wrapped`, which, at one point, calls `lvs`.
```bash
# Also detect OSes on LVM volumes (assumes LVM is active)
if type lvs >/dev/null 2>&1; then
	echo "$(LVM_SUPPRESS_FD_WARNINGS=1 log_output lvs --noheadings --separator : -o vg_name,lv_name |
		sed "s|-|--|g;s|^[[:space:]]*\(.*\):\(.*\)$|/dev/mapper/\1-\2|")"
fi
```
If `lvs` is missing, the script continues to run without showing any errors, which is what is happening in this case. The problem can be reproduced in an interactive shell using `--pure`.

Replacing `lvs` with a hard-coded path makes OS probing work, although there are a lot of error messages about "Internal error: unreleased memory pool(s) found".

There may also be similar problems with `log-output`, `dmraid`, `udevadm`, and `udevinfo`.

**Comment by symphorien** [comment] 2020-01-02 21:00
Nice finding!
Then you can add the package containing `lvs` to this list:

https://github.com/NixOS/nixpkgs/blob/eab4ee0c27c5c6f622aa0ca55091c394a9e33edd/pkgs/tools/misc/os-prober/default.nix#L54

And the problem should be solved. Feel free to make a PR :)

I have already seen the warnings about memory, so at least they are not a regression. I have no idea what they mean.

**Comment by worldofpeace** [comment] 2020-02-02 00:34
Fixed by https://github.com/NixOS/nixpkgs/pull/76843

**Closed by worldofpeace** 2020-02-02 00:34 UTC
Labels: 0.kind: bug, 6.topic: nixos
