### ISSUE TITLE
nixpkgs-unstable has not updated in several days

### ISSUE THREAD

**Issue by acowley** [NixOS/nixpkgs#19460] opened 2016-10-11 19:31 UTC
## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by domenkozar** [comment] 2016-10-11 20:45
Hmmm, there are no new jobs in http://hydra.nixos.org/job/nixpkgs/trunk/unstable#tabs-constituents

Pretty sure this was caused by https://github.com/NixOS/nixpkgs/commit/69e614d1e64cb50cb9b5b24a4c1668a649d54eec, but I don't understand why. 

@edolstra a bug in Hydra?

**Comment by domenkozar** [comment] 2016-10-11 21:05
It's interesting because http://hydra.nixos.org/job/nixpkgs/trunk/tested#tabs-constituents does pass.

**Comment by domenkozar** [comment] 2016-10-11 21:07
Aha, it could be due to `rec` being used now.

**Comment by domenkozar** [comment] 2016-10-11 21:09
I've pushed a fix for that, but darwin stuff still needs to be fixed. cc @copumpkin 

http://hydra.nixos.org/job/nixpkgs/trunk/tested#tabs-constituents

**Comment by domenkozar** [comment] 2016-10-11 21:10
Tarball also fails due to https://github.com/NixOS/nixpkgs/pull/19334#issuecomment-253047300

**Comment by domenkozar** [comment] 2016-10-13 16:25
Fixed the tarball. Darwin still failing due to recent stdenv changes: http://hydra.nixos.org/build/41976530/nixlog/1/raw

**Comment by domenkozar** [comment] 2016-10-13 16:25
cc @copumpkin

**Comment by copumpkin** [comment] 2016-10-13 17:24
@domenkozar oh duh, I forgot to push my make-bootstrap-tools.nix changes. Will do that when I get back to the computer that has them, probably in a few hours. Sorry for the mixup!

**Comment by copumpkin** [comment] 2016-10-14 02:33
I just pushed a new `make-bootstrap-tools.nix` which I hope will fix the issue.

**Comment by domenkozar** [comment] 2016-10-14 11:11
@copumpkin that helps, but yields another error: http://hydra.nixos.org/build/42087478/nixlog/2/raw

**Comment by domenkozar** [comment] 2016-10-18 13:19
All green now: http://howoldis.herokuapp.com/

PS: I'm working on major improvements to howoldis that will hopefully give us more transparency and warning into the process.

**Closed by domenkozar** 2016-10-18 13:19 UTC
Labels: 1.severity: blocker, 6.topic: darwin

**Comment by acowley** [comment] 2016-10-18 13:23
Thank you, @copumpkin and @domenkozar!
