### ISSUE TITLE
Package request: Nix Configuration Editor

### ISSUE THREAD

**Issue by StrongSand94191** [NixOS/nixpkgs#319941] opened 2024-06-15 00:28 UTC
**Project description**

A simple NixOS configuration editor application. The goal of this project is to provide a simple graphical tool for modifying and managing desktop NixOS configurations.

**Metadata**

* homepage URL: https://github.com/snowfallorg/nixos-conf-editor
* source URL: https://github.com/snowfallorg/nixos-conf-editor
* license: GPL-3.0
* platforms: Nix, Flakes

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-06-15 03:03
duplicate of #212963

**Closed by eclairevoyant** 2024-06-15 03:03 UTC
Labels: 0.kind: packaging request
