### ISSUE TITLE
NixOS fails to boot after upgrade and *none* of the 15 other versions work either

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#14789] opened 2016-04-17 20:49 UTC
This is *not* what I expect to see after a successful upgrade (i.e. one that has an exit status of zero). 

![brokennixos](https://cloud.githubusercontent.com/assets/16732294/14589901/b15a6000-04ed-11e6-995f-3d0984f0ff22.png)

How can this situation be salvaged? None of the grub entries work. I do use ZFS, but that's it complexity wise. I would like to receive some assistance in getting this to work again. 

If I could have run some VM automatically to verify the setup next time, I would have preferred to do that, instead of having to write this bug report again. 

But with releases like this, I am not sure whether it is wise to call it an "upgrade". IMHO, this (16.03) should never have been released in the first place. 

Should I use some kind of rescue CD?

**Comment by wmertens** [comment] 2016-04-18 09:29
It looks like it can't find the kernel where it expected it, so your boot config is wrong somehow. Try finding where it should get the kernel from by going into the grub command line and using tab completion on the disks.

**Comment by domenkozar** [comment] 2016-04-18 09:51
There was a range of nixpkgs commits when Grub was broken. Try to edit the grub when you boot and prepend `/nix/store` to all the hash parts you see for a single entry to boot.

And when you boot, please write `nixos-version` here so we can see if you're really using the old commit or something is really broken.

**Comment by abbradar** [comment] 2016-04-18 11:11
Hm, maybe this is related somehow to ZFS indeed, but I'm not sure. Either way -- sounds not nice at all. You mentioned that you have updated -- if so I think you can at least revert by booting from 15.09 installation CD, mounting everything as you would do to install NixOS and then running `nixos-install` -- it would build 15.09 per your current configuration and re-install GRUB, hopefully fixing the problem.

**Comment by 0xABAB** [comment] 2016-04-22 08:26
@domenkozar Are you also saying that `/nix/store/*linux-4.4.6` should exist?

**Comment by domenkozar** [comment] 2016-04-22 09:43
Yes.

**Comment by 0xABAB** [comment] 2016-04-23 11:44
For completeness this is what Grub2 tries to do: 

![image](https://cloud.githubusercontent.com/assets/16732294/14761190/11706aa6-0959-11e6-8444-1fcd54e41eb8.png)

The repetition of `//` and `@//` seems suspicious indeed. Can we have an assertion somewhere that any configuration which has two subsequent `/` characters is *not* considered to be a valid configuration?

**Comment by domenkozar** [comment] 2016-04-23 11:51
@aszlig another place :-)

**Comment by domenkozar** [comment] 2016-04-23 11:52
@0xABAB can you provide what `nixos-version` you're using?

**Comment by 0xABAB** [comment] 2016-04-23 11:55
This is what I get now, after putting nix/store in the various places. "nix" is a rather unqualified location, which is also not something I like.

![image](https://cloud.githubusercontent.com/assets/16732294/14761252/e70a9528-095a-11e6-9179-e571df08ead5.png)

**Comment by 0xABAB** [comment] 2016-04-23 11:56
@domenkozar I upgraded to the 16.03 release. Various numbers can be found in the screenshots above. I cannot actually run NixOS now, as you know.

**Comment by 0xABAB** [comment] 2016-04-23 12:10
@domenkozar Any more ideas?

**Comment by domenkozar** [comment] 2016-04-23 12:26
@0xABAB can you provide the configuration file? It's hard to guess without exacts steps to reproduce.

**Comment by 0xABAB** [comment] 2016-04-23 12:30
@domenkozar I was still only in hacking around mode with NixOS. So, it's all on the machine itself. I am now running the latest stable NixOS CD, but I need to figure out how to mount my ZFS pools. I don't get why it doesn't do that by default (i.e., detect and just mount them under /mnt/zfs/whatever).

**Comment by 0xABAB** [comment] 2016-04-23 12:39
@domenkozar `zfs list` as root returns `no datasets available` when booted from the 16.03 Stable CD. Does that mean that all my data is gone with the wind?

**Comment by 0xABAB** [comment] 2016-04-23 12:42
Hmm, it's not *that* bad.

**Comment by 0xABAB** [comment] 2016-04-23 12:54
@domenkozar Which configuration file do you want to have?

**Comment by 0xABAB** [comment] 2016-04-23 12:56
For future reference: 

`mount -t zfs -o zfsutil zpool/nixos /mymountpoint` can be used as a hack to not have to set zfs mountpoint variables.

**Comment by 0xABAB** [comment] 2016-04-23 13:15
I also would prefer to not see any WARNINGs in processes involving a kernel:

![image](https://cloud.githubusercontent.com/assets/16732294/14761590/07497484-0966-11e6-93af-8bafc4c33703.png)

**Comment by 0xABAB** [comment] 2016-04-23 13:56
@abbradar  My system is alive again, which was partially sped up by your contribution to this thread. Thanks.

I would say this issue can be closed once we know or have a good guess as to what caused this. I have the impression that @domenkozar and @aszlig have such a good guess, but I think it's clear that this stuff should never happen.

**Comment by Shados** [comment] 2016-05-10 03:27
@0xABAB To help with determining what caused the issue: did you make changes to your `/etc/nixos/` config to get it running again, or did you re-install from a 15.09 livecd as abbradar suggested? If the former, what did you change? If the latter, can you pastebin the contents of your `/etc/nixos/` files? 

Also, did you did the `nixos-rebuild switch --upgrade` the same day you posted about this issue?

**Comment by aszlig** [comment] 2016-05-10 12:26
Would be probably a good idea to have an installer test for ZFS, especially if ZFS was the issue here to also serve as a regression test.

**Comment by 0xABAB** [comment] 2016-05-10 15:52
@Shados I followed @abbradar's instructions with some command to make the zpool available, etc. 

To answer your last question: yes.

**Comment by bjornfor** [comment] 2016-05-14 10:18
I just hit this issue too, but I'm on NixOS 15.09. I didn't notice anything bad during "nixos-rebuild switch". Rebooted and none of the grub entries worked. All "linux" and "initrd" entries were missing "/nix/store/" prefix; instead they had just two slashes "//" (so the system couldn't find the file(s) and failed to boot). Editing the command line in grub worked, booted and ran "nixos-rebuild switch" again. Now grub entries are fixed. Scary.

**Comment by domenkozar** [comment] 2016-05-14 20:27
@bjornfor did you mount /nix/store as writeable by any chance?

**Comment by bjornfor** [comment] 2016-05-14 21:18
@domenkozar: Yes I did! Spot on! (Thank you!)

I had completely forgotten about that. I was working on a proprietary package and had temporarily writeable nix store as a way to investigate what files the package wanted to write to (it was segfaulting on startup). Not a good idea in retrospect. But on the other hand, WHY ON EARTH did nixos-rebuild break like that?

**Comment by domenkozar** [comment] 2016-05-14 21:19
See https://github.com/NixOS/nixpkgs/issues/14999

**Comment by domenkozar** [comment] 2016-05-17 10:00
@0xABAB is this also your case? If so, let's close this issue :)

**Comment by 0xABAB** [comment] 2016-05-17 10:24
@domenkozar I am not 100% sure, but that's likely. The sanity checks should still be added. I would be happy if those sanity checks are there in combination with the fix for #14999. 

In fact, before rebooting there should be some checks that some kernel files actually exist and have a reasonable size (pick some useful lower bound according to your own insight). I know that on some operating systems in certain circumstances (for example with hardware RAID) there are lies about which files actually exist, even though in theory this issues should never occur. 

So, from an engineering point of view, I would love to see some additional stat calls too. You could split this off as a separate feature request.

**Comment by domenkozar** [comment] 2016-06-27 07:26
I'll close this in favor of #14999 for now as it appears to be a duplicate.

**Closed by domenkozar** 2016-06-27 07:26 UTC
Labels: 0.kind: question
