### ISSUE TITLE
yuzu-mainline doesn't build on 21.05

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#128239] opened 2021-06-26 18:08 UTC
**Describe the bug**

`yuzu-mainline` fails to build.

**To Reproduce**
1. add `yuzu-mainline` to `environment.systemPackages`.
2. `nixos-rebuild switch`
3. observe failure

**Expected behavior**

**Screenshots**

**Additional context**

most relevant part of build log:
```
[ERROR] fatal: git cat-file: could not get object info
[ERROR] Unrecognized git object type:
[ERROR] Unable to checkout eac2416b8fdb2cb9c867a538100bf95326bad75b from https://github.com/yuzu-emu/mbedtls.
[ERROR] builder for '/nix/store/dqa14b10hb9w2s4758v6zqhr9wyn9m5g-source.drv' failed with exit code 1
```

**Notify maintainers**

@IvarWithoutBones 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
builtins.fetchTarball {
  name = "nixos-stable-2021-06-25";
  url = "https://github.com/nixos/nixpkgs/archive/b72bde7c4a1f9c9bf1a161f0c267186ce3c6483c.tar.gz";
  sha256 = "1cihs542msfldcawcsk6s2bs8bpz82ldy6axsrax8ngw2gllqrcd";
}
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: yuzu-mainline
# a list of nixos modules affected by the problem
module:
```

**Comment by IvarWithoutBones** [comment] 2021-07-05 22:06
Not quite sure what the cause of this issue is, but updating the package seems to have fixed it. The latest version of yuzu depends on `fmt` 8.0.0+, which currently isn't in nixpkgs. 

I'll PR some updates + fixes for the latest version of yuzu when #129378 gets merged.

**Closed** 2021-07-09 00:59 UTC
Labels: 0.kind: bug
