### ISSUE TITLE
libreoffice-fresh 7.4.2.3 fails to build on nixos-unstable.

### ISSUE THREAD

**Issue by nikstur** [NixOS/nixpkgs#213563] opened 2023-01-30 11:48 UTC
### Steps To Reproduce

Build `libreoffice-fresh` on nixos-unstable (9b97ad7b4330aacda9b2343396eb3df8a853b4fc)

### Build log
```
error: builder for '/nix/store/gr8vnr6avsfrlhss1an6j5jzwvnx646k-libreoffice-7.4.2.3.drv' failed with exit code 1;
       last 10 log lines:
       > configure: error: Package requirements (mdds-2.0 >= 2.0.0) were not met:
       >
       > No package 'mdds-2.0' found
       >
       > Consider adjusting the PKG_CONFIG_PATH environment variable if you
       > installed software in a non-standard prefix.
       >
       > Alternatively, you may set the environment variables MDDS_CFLAGS
       > and MDDS_LIBS to avoid the need to call pkg-config.
       > See the pkg-config man page for more details.
       For full logs, run 'nix log /nix/store/gr8vnr6avsfrlhss1an6j5jzwvnx646k-libreoffice-7.4.2.3.drv'.
```

### Notify maintainers
@7c6f434c 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
- system: `"x86_64-linux"`
- host os: `Linux 6.1.7, NixOS, 23.05 (Stoat), 23.05.20230123.1b1f506`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.12.0`
- channels(root): `"home-manager, nixos"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by wegank** [comment] 2023-01-30 12:34
Duplicate of #212556, #212937, #212985, and #213502.

**Closed by wegank** 2023-01-30 12:34 UTC
Labels: 0.kind: build failure

**Comment by nikstur** [comment] 2023-01-30 12:49
Ah my bad, I didn't search for closed issues. Sorry for that!
