### ISSUE TITLE
boot.binfmt.emulatedSystems = [ "aarch64-linux" ] makes nixOS unusable and unbootable, Too many levels of symbolic links

### ISSUE THREAD

**Issue by Yeshey** [NixOS/nixpkgs#239806] opened 2023-06-25 18:48 UTC
### Describe the bug
In the oracle server arm VMs with nixOS installed in a btrfs file system, adding the line `boot.binfmt.emulatedSystems = [ "aarch64-linux" ]`, and doing `nixos-rebuild switch` breaks with this error:
```
warning: Git tree '/home/yeshey/.setup' is dirty
building the system configuration...
warning: Git tree '/home/yeshey/.setup' is dirty
activating the configuration...
setting up /etc...
reloading user units for yeshey...
setting up tmpfiles
restarting the following units: nix-daemon.service
open3: exec of /nix/store/j1c20f57gn0y9y9kr61dlgjll2hlhbnp-system-path/bin/busctl --json=short call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager ListUnitsByPatterns asas 0 0 failed: Too many levels of symbolic links at /nix/store/82a9ld0177rnnsfklwlf27bvk733vyln-perl-5.36.0/lib/perl5/5.36.0/IPC/Cmd.pm line 1531.
warning: error(s) occurred while switching to the new configuration
/nix/store/y0yp1wyhlkgd8vy638pajania07ycmxm-nixos-rebuild/bin/nixos-rebuild: line 384: /nix/store/sdfpzhcksqwsfya89ldci3yhvw6sywg9-coreutils-9.1/bin/rm: Too many levels of symbolic links
```
After that I can use almost no commands, and the system won't reboot correctly (I can't ssh back into it):
```
➜  ~ sudo                                      
zsh: too many levels of symbolic links: sudo
➜  ~ neofetch       
command_not_found_handler:1: too many levels of symbolic links: /run/current-system/sw/bin/command-not-found
➜  ~ x86_64-windows
➜  ~ sudo su    
zsh: too many levels of symbolic links: sudo
➜  ~ 
➜  ~ 
➜  ~ 
➜  ~ ls                    
zsh: too many levels of symbolic links: ls
➜  ~ ls
zsh: too many levels of symbolic links: ls
➜  ~ bash
zsh: too many levels of symbolic links: bash
➜  ~ cd ..
➜  /home ls
zsh: too many levels of symbolic links: ls
➜  /home tree
zsh: too many levels of symbolic links: tree
➜  /home wget
zsh: too many levels of symbolic links: wget
➜  /home readlink -f sudo      
zsh: too many levels of symbolic links: readlink
➜  /home readlink        
zsh: too many levels of symbolic links: readlink
➜  /home
```

### Steps To Reproduce
I don't know if this will happen in every arm device, or in every VM in a arm device, but here I'm describing the process I did to make this happen, the issue happened twice for me, so these steps are reproducible:

1. Make an Oracle free Arm server with nixOS
    1. Make an [Oracle cloud account](https://www.oracle.com/cloud/sign-in.html)
    2. Go to Create a VM instance
    3. In the "image and shape" section, change image to Ubuntu and shape to Ampere (Arm based processor)
    4. Select `VM.Standard.E2.1.Micro`
    5. Other options selected: `Use in-transit encryption`, `Custom boot volume` of 150GB and `Boot volume performance` of 20 VPU.
    6. Also selected `Paste public keys`, and pasted my created public key from ~/.ssh
    7. Install nixOS in the server from ubuntu with btrfs file system
        1. Follow the [blog referenced in this post, with the changes in that same post applied](https://discourse.nixos.org/t/nixos-on-free-oracle-cloud-arm-a1/17474/23?u=yeshey)
        2. Instead of making a boot partition of 10GB, I made it of 1GB. 
        3. Instead of making the main partition `ext4`, I made it `btrfs` and added `options = [ "compress=zstd" ];` for compression in the `hardware-configuration.nix` so the btrfs partition in the nix file was something like:
          ```
            fileSystems."/" =
              { device = "/dev/disk/by-uuid/0cf115a9-96fb-4991-bdee-bfbd9ce49fa6";
                fsType = "btrfs";
                options = [ "compress=zstd" ];
              };
          ``` 
2. Adding the configuration `boot.binfmt.emulatedSystems = [ "aarch64-linux" ]` should reproduce the problem. 
    1. It's worth noting that I was running under this flake configuration of mine: <https://github.com/Yeshey/nixOS-Config/commit/0883eb3cb735b8034b7954da010b575ea5728785>
    2. Some notes that might be important are:
        1. Using the `zsh` shell
        2. Had the option:
          ```
            environment.systemPackages = with pkgs; [
              qemu
            ]; 
          ```
        3. Using flakes to manage the system
        4. BTRFS filesystem
I wasn't able to create a Virtual machine with aarch64 architecture yet to test..

### Expected behaviour
An error should be given if the option is not correct, the system shouldn't self destruct.

### Notify maintainers

@wegank 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.05 (Stoat), 23.05.20230611.bb8b573`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05, nixpkgs-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

```console
➜  ~ nix-shell -p neofetch --run neofetch
          ▗▄▄▄       ▗▄▄▄▄    ▄▄▄▖            yeshey@nixOS-arm-oracle 
          ▜███▙       ▜███▙  ▟███▛            ----------------------- 
           ▜███▙       ▜███▙▟███▛             OS: NixOS 23.05.20230611.bb8b573 (Stoat) aarch64 
            ▜███▙       ▜██████▛              Host: KVM Virtual Machine virt-4.2 
     ▟█████████████████▙ ▜████▛     ▟▙        Kernel: 6.1.31 
    ▟███████████████████▙ ▜███▙    ▟██▙       Uptime: 1 hour, 46 mins 
           ▄▄▄▄▖           ▜███▙  ▟███▛       Packages: 690 (nix-system), 228 (nix-user) 
          ▟███▛             ▜██▛ ▟███▛        Shell: bash 5.2.15 
         ▟███▛               ▜▛ ▟███▛         Resolution: 1024x768 
▟███████████▛                  ▟██████████▙   Terminal: /dev/pts/2 
▜██████████▛                  ▟███████████▛   CPU: (4) 
      ▟███▛ ▟▙               ▟███▛            GPU: Red Hat, Inc. Virtio 1.0 GPU 
     ▟███▛ ▟██▙             ▟███▛             Memory: 790MiB / 23980MiB 
    ▟███▛  ▜███▙           ▝▀▀▀▀
    ▜██▛    ▜███▙ ▜██████████████████▛                                
     ▜▛     ▟████▙ ▜████████████████▛                                 
           ▟██████▙       ▜███▙
          ▟███▛▜███▙       ▜███▙
         ▟███▛  ▜███▙       ▜███▙
         ▝▀▀▀    ▀▀▀▀▘       ▀▀▀▘
```

**Comment by wegank** [comment] 2023-06-26 04:41
I'm probably not the one to notify, but honestly, I've never tried or dared to put the native platform in `boot.binfmt.emulatedSystems`. It seems that this should be explicitly forbidden?

**Comment by Artturin** [comment] 2023-06-28 22:58
Dupe of https://github.com/NixOS/nixpkgs/issues/218465

**Closed by Artturin** 2023-06-28 22:58 UTC
Labels: 0.kind: bug
