### ISSUE TITLE
Package request: klassy

### ISSUE THREAD

**Issue by machadofguilherme** [NixOS/nixpkgs#365745] opened 2024-12-17 01:05 UTC
## Project description

Klassy (formerly ClassiK/ClassikStyles) is a highly customizable binary Window Decoration, Application Style and Global Theme plugin for recent versions of the KDE Plasma desktop. Initially taking inspiration from the iconography of KDE 1, the Klassy defaults are an attempt to create a usable and appealing look for the modern Plasma desktop.

## Metadata

* homepage URL: https://github.com/paulmcauley/klassy
* source URL: https://github.com/paulmcauley/klassy
* license: BSD-3-Clause, CC0-1.0, GPL-2.0-only, GPL-2.0-or-later, GPL-3.0-only, LicenseRef-KDE-Accepted-GPL, MIT
* platforms: linux

**Comment by Gliczy** [comment] 2024-12-17 01:24
Duplicate of https://github.com/NixOS/nixpkgs/issues/272566.

**Closed by Gliczy** 2024-12-17 01:24 UTC
Labels: 0.kind: packaging request
