### ISSUE TITLE
Python 3.10 fails to build on Darwin

### ISSUE THREAD

**Issue by takeda** [NixOS/nixpkgs#158091] opened 2022-02-04 08:51 UTC
### Steps To Reproduce

```sh
nix-shell -p python310
```

### Expected behavior

A shell with python3.10 running

### Screenshots

```console
clang-11: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
clang-11: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
LC_ALL=C sed -e 's,\$(\([A-Za-z0-9_]*\)),\$\{\1\},g' < Misc/python-config.sh >python-config
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall    -fno-semantic-interposition -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration
      -DGITVERSION="\"`LC_ALL=C `\"" \
      -DGITTAG="\"`LC_ALL=C `\"" \
      -DGITBRANCH="\"`LC_ALL=C `\"" \
      -o Modules/getbuildinfo.o ./Modules/getbuildinfo.c
clang-11: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
rm -f libpython3.10.a
clang -dynamiclib -Wl,-single_module -L/nix/store/yv38x2kry0ykifs5v86yymr775jx8pr0-zlib-1.2.11/lib -L/nix/store/3nry9zb4dy4n3kbn8vkylr11dbyz79pd-bzip2-1.0.6.0.2/lib -L/nix/store/q3vxmy3n5s0ip9f1am1pvznn4knc42kg-expat-2.4.2/lib -L/nix/store/jvj5vibhgz87ww17si8hjfb6kcq4bp

ar rcs libpython3.10.a Modules/getbuildinfo.o Parser/token.o  Parser/pegen.o Parser/parser.o Parser/string_parser.o Parser/peg_api.o Parser/myreadline.o Parser/tokenizer.o Objects/abstract.o Objects/accu.o Objects/boolobject.o Objects/bytes_methods.o Objects/bytearrayob
ld: warning: directory not found for option '-L/nix/store/xw8z8xa6n2z4vs19b5arr33l1ayq5wdh-configd-453.19/lib'
ld: warning: directory not found for option '-L/nix/store/8yqkvkwrkbngj8vpmp94qgihpr4l1vmq-tzdata-2021e/lib'
ld: warning: directory not found for option '-L/nix/store/xw8z8xa6n2z4vs19b5arr33l1ayq5wdh-configd-453.19/lib'
ld: warning: directory not found for option '-L/nix/store/8yqkvkwrkbngj8vpmp94qgihpr4l1vmq-tzdata-2021e/lib'
/nix/store/c0bzs8wvys6nzlkclxq20zdrafhggcwv-cctools-port-949.0.1/bin/ranlib: file: libpython3.10.a(dynamic_annotations.o) has no symbols
/nix/store/c0bzs8wvys6nzlkclxq20zdrafhggcwv-cctools-port-949.0.1/bin/ranlib: file: libpython3.10.a(pymath.o) has no symbols
clang -L/nix/store/yv38x2kry0ykifs5v86yymr775jx8pr0-zlib-1.2.11/lib -L/nix/store/3nry9zb4dy4n3kbn8vkylr11dbyz79pd-bzip2-1.0.6.0.2/lib -L/nix/store/q3vxmy3n5s0ip9f1am1pvznn4knc42kg-expat-2.4.2/lib -L/nix/store/jvj5vibhgz87ww17si8hjfb6kcq4bpv6-xz-5.2.5/lib -L/nix/store/6f
clang -L/nix/store/yv38x2kry0ykifs5v86yymr775jx8pr0-zlib-1.2.11/lib -L/nix/store/3nry9zb4dy4n3kbn8vkylr11dbyz79pd-bzip2-1.0.6.0.2/lib -L/nix/store/q3vxmy3n5s0ip9f1am1pvznn4knc42kg-expat-2.4.2/lib -L/nix/store/jvj5vibhgz87ww17si8hjfb6kcq4bpv6-xz-5.2.5/lib -L/nix/store/6f
ld: warning: ld: warning: directory not found for option '-L/nix/store/xw8z8xa6n2z4vs19b5arr33l1ayq5wdh-configd-453.19/lib'directory not found for option '-L/nix/store/xw8z8xa6n2z4vs19b5arr33l1ayq5wdh-configd-453.19/lib'

ld: warning: ld: warning: directory not found for option '-L/nix/store/8yqkvkwrkbngj8vpmp94qgihpr4l1vmq-tzdata-2021e/lib'directory not found for option '-L/nix/store/8yqkvkwrkbngj8vpmp94qgihpr4l1vmq-tzdata-2021e/lib'

ld: warning: directory not found for option '-L/nix/store/xw8z8xa6n2z4vs19b5arr33l1ayq5wdh-configd-453.19/lib'ld: warning:
directory not found for option '-L/nix/store/xw8z8xa6n2z4vs19b5arr33l1ayq5wdh-configd-453.19/lib'
ld: warning: directory not found for option '-L/nix/store/8yqkvkwrkbngj8vpmp94qgihpr4l1vmq-tzdata-2021e/lib'ld: warning:
directory not found for option '-L/nix/store/8yqkvkwrkbngj8vpmp94qgihpr4l1vmq-tzdata-2021e/lib'
DYLD_LIBRARY_PATH=/private/tmp/nix-build-python3-3.10.1.drv-2/Python-3.10.1 ./python.exe -E -S -m sysconfig --generate-posix-vars ;\
if test $? -ne 0 ; then \
        echo "generate-posix-vars failed" ; \
        rm -f ./pybuilddir.txt ; \
        exit 1 ; \
fi
/nix/store/z6rd8wq02azalrlm2m5k08iy53klg624-bash-5.1-p12/bin/bash: line 6: 86869 Killed: 9               DYLD_LIBRARY_PATH=/private/tmp/nix-build-python3-3.10.1.drv-2/Python-3.10.1 ./python.exe -E -S -m sysconfig --generate-posix-vars
generate-posix-vars failed
make: *** [Makefile:615: pybuilddir.txt] Error 1
```

### Notify maintainers
@FRidh 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.6.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.5.1`
 - channels(dk255056): `"darwin, home-manager, nixpkgs-22.05pre349906.7f65e4abd5e"`
 - channels(root): `"darwin, home-manager, nixpkgs-22.05pre349906.7f65e4abd5e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
 ```

**Comment by veprbl** [comment] 2022-02-04 12:51
Duplicate of #154120

**Closed** 2022-03-15 21:31 UTC
Labels: 0.kind: bug
