### ISSUE TITLE
Build failure: jasper 4.2.1 (unstable)

### ISSUE THREAD

**Issue by mayersj1** [NixOS/nixpkgs#294067] opened 2024-03-07 15:17 UTC
### Steps To Reproduce

1. nix flake update
2. home-manager --flake <myFlake> switch

### Build log

```
building '/nix/store/xxqxfjrskz4zqlngql8hf8ffldga6mbs-jasper-4.2.1.drv'...                                                 │
error: cycle detected in build of '/nix/store/xxqxfjrskz4zqlngql8hf8ffldga6mbs-jasper-4.2.1.drv' in the references of outpu│
t 'lib' from output 'out'  
```

### Additional context

Platform: aarch64-darwin
Nix: Unstable
Japser version: 4.2.1

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 nix-shell -p nix-info --run "nix-info -m"                                                                                │
these 2 paths will be fetched (0.01 MiB download, 0.11 MiB unpacked):                                                      │
  /nix/store/xkkpiw8wj0cglvkzpp8gd2h5mgsq1kik-DarwinTools-1                                                                │
  /nix/store/highid3c54gk59sxhibjhkyq2s2yvrch-nix-info                                                                     │
copying path '/nix/store/xkkpiw8wj0cglvkzpp8gd2h5mgsq1kik-DarwinTools-1' from 'https://cache.nixos.org'...                 │
copying path '/nix/store/highid3c54gk59sxhibjhkyq2s2yvrch-nix-info' from 'https://cache.nixos.org'...                      │
 - system: `"aarch64-darwin"`                                                                                              │
 - host os: `Darwin 23.3.0, macOS 14.3.1`                                                                                  │
 - multi-user?: `yes`                                                                                                      │
 - sandbox: `no`                                                                                                           │
 - version: `nix-env (Nix) 2.20.3`                                                                                         │
 - channels(root): `""`                                                                                                    │
 - nixpkgs: `/nix/store/8ny3r3jvj17ljzc89h9rpfr56a7nyn8c-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mayersj1** [comment] 2024-03-07 15:19
I'm not sure where to go look for the build log. More than happy to upload it here if someone can tell me where it's located.

**Comment by mayersj1** [comment] 2024-03-07 20:57
Verified that this fails in the same way on both my MacOS machines running home-manager.

**Comment by mayersj1** [comment] 2024-03-07 21:00
Also verified that if I run 'nix shell nixpkgs#jasper', it succeeds and jasper is available in the nix shell.

**Comment by jmarmstrong1207** [comment] 2024-03-08 08:13
Cannot reproduce on x86_64 Linux. I'd assume this is a MacOS specific issue that the derivation missed

**Comment by jmarmstrong1207** [comment] 2024-03-08 08:13
@AndersonTorres

**Comment by expenses** [comment] 2024-03-08 09:06
Also happening on x86_64 darwin

**Comment by iynaix** [comment] 2024-03-08 14:11
I think this is fixed by #293480

**Comment by AndersonTorres** [comment] 2024-03-08 19:24
Since nomacs (https://github.com/NixOS/nixpkgs/pull/292808) was hit by this same problem and it was now accepted, I will close this as solved in master.

**Closed by AndersonTorres** 2024-03-08 19:24 UTC
Labels: 0.kind: build failure

**Comment by AndersonTorres** [comment] 2024-03-08 19:26
> Steps to reproduce the behavior:
> 
>     nix flake update
>     home-manager --flake switch

Ehr, it is not really helpful, but I will not pursue this issue further.

**Comment by mayersj1** [comment] 2024-03-08 20:45
okay, so where is the tracking ticket as to when this will show up in 'unstable'? Is there a standard time between merge and availability?  Thanks.

**Comment by mayersj1** [comment] 2024-03-08 20:45
> > Steps to reproduce the behavior:
> > ```
> > nix flake update
> > home-manager --flake switch
> > ```
> 
> Ehr, it is not really helpful, but I will not pursue this issue further.

Might not be helpful, but that's what I did when the error occurred.  What else would be useful in a case like this?

**Comment by AndersonTorres** [comment] 2024-03-08 23:22
> okay, so where is the tracking ticket as to when this will show up in 'unstable'? Is there a standard time between merge and availability? Thanks.

You can track it by using the following webapp from Alyssais:

https://nixpk.gs/pr-tracker.html

Enter 293480.

> Might not be helpful, but that's what I did when the error occurred. What else would be useful in a case like this?

This is a bit more complicated, since a well-formed bug report would provide a minimal and accurate procedure in order to allow other people to reproduce the bug.

**Comment by mayersj1** [comment] 2024-03-09 22:47
...and those are things that can be asked for if needed. Nothing worse than a report full of non-useful information.  As I believe this is an indirect dependency brought in by the Wireshark app, there is no direct configuration made in any of my files (simply a flake.nix and a home.nix) so I didn't think it was relevant.
