### ISSUE TITLE
OBS Studio crash at launch

### ISSUE THREAD

**Issue by Wlnfr** [NixOS/nixpkgs#369061] opened 2024-12-29 10:25 UTC
## Describe the bug
Running `obs` crashes at launch with `Illegal instruction (core dumped)`

## Steps To Reproduce

1. Run `obs`

## Expected behavior
OBS launches

## Screenshots
![2024-12-29_11-49](https://github.com/user-attachments/assets/5b61e800-3e2a-4be6-8c52-876b6d240bdc)

## Additional context
Nix config for obs:
![2024-12-29_11-53](https://github.com/user-attachments/assets/b7499c5f-1e55-4c47-8bd2-6fd8eaf7c0a8)
[Backtrace](https://gist.github.com/Wlnfr/3c709f3cf665ae75b93cab2dcc9720aa)
OBS installed via official flatpak works as intended. OBS worked as intended with the config above on 24.05
Considering that it's `Illegal instruction` here's some basic information about PC and Desktop:
 - CPU: Core Quad Q9650
 - GPU: GT 1030, driver 565.77
 - RAM: 16 GB DDR2 800 mhz
 - DE: Plasma 6, X11

## Metadata

 
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.64, NixOS, 24.11 (Vicuna), 24.11.711615.1c6e20d41d6a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos-24.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

## Notify maintainers
@fpletz @materusPL @jb55 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Atemu** [comment] 2024-12-30 14:37
Pretty sure this is a duplicate of https://github.com/NixOS/nixpkgs/issues/368440.

Though it's also caused by obs-studio using ffmpeg-full which it really shouldn't: https://github.com/NixOS/nixpkgs/issues/271863.

I haven't gotten around to doing that yet though.

**Closed by Atemu** 2024-12-30 14:37 UTC
Labels: 0.kind: bug
