### ISSUE TITLE
Getting "secret key is corrupt" on most commands

### ISSUE THREAD

**Issue by cah6** [NixOS/nixpkgs#45339] opened 2018-08-19 15:08 UTC
## Issue description
It seems like any command that tries to fetch a cached binary is failing with:
`error: secret key is corrupt`

### Steps to reproduce
Not sure how I get into this state but current behavior is:
```
$ nix-env -i zip
warning: name collision in input Nix expressions, skipping '/Users/christian.henry/.nix-defexpr/channels_root/nixpkgs'
installing 'zip-3.0'
these paths will be fetched (0.15 MiB download, 0.54 MiB unpacked):
  /nix/store/cpja0xjyi9nxb715nljbkpii7l6zmhyk-zip-3.0
error: secret key is corrupt
```

## Technical details
`nix-shell -p nix-info --run "nix-info -m"` actually fails too:
```
$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (2.01 MiB download, 11.35 MiB unpacked):
  /nix/store/1bzafpp9bhbs70kbg4k3ya1xz9bnd26k-bash-4.4-p19-doc
  /nix/store/1c995fhi4rqn7ss7qv4l5mbcl5ajyspf-adv_cmds-osx-10.5.8-locale
  /nix/store/20n07wawwvn0af8dr7xxl7zpkfyh9324-bash-4.4-p19-man
  /nix/store/2hwayv4fhak2kl7y6hjyi18gxh7ncvx8-readline-7.0p3
  /nix/store/614viw8ffn0qfmfrcidfv487qz8rnjcj-bash-4.4-p19-dev
  /nix/store/72dvq0f1rpmrnk4d0h7by8m6ln70l0b9-bash-4.4-p19-info
  /nix/store/8p3izl58ny7hr52jwh1fpnwgc0zxk8xc-DarwinTools-1
  /nix/store/bj2m0fb1kik3dxn1nx763s3lmmy7jgwv-nix-info
  /nix/store/dr80a9mwy52yqaxc9n9lw35mqm4yc08p-stdenv-darwin
  /nix/store/k5wbwf1nsywpbbrypjd82hcn7pbd69wh-bash-4.4-p19-info
  /nix/store/lvymdjrcixv781ss1byny6zjqmfxq828-bash-4.4-p19-dev
  /nix/store/p17frn8zgghjfpr0j38mfbasvsjcfpbp-bash-4.4-p19
  /nix/store/xsbwr7ns6wxrmhis72q5x9m2vlcw6rgi-bash-4.4-p19-man
  /nix/store/y9s019svvv488abp0sazjm6qa0nwmgc7-bash-4.4-p19-doc
error: secret key is corrupt
```
but I have:
```
$ nix --version
nix (Nix) 2.0.2
```
and
```
$ nix-channel --list
nixpkgs http://nixos.org/channels/nixpkgs-unstable
```
and I'm on OSX 10.13.4. Is there any way to regenerate the secret key used by nix or something? I don't even know where stuff like that is stored.

**Comment by xeji** [comment] 2018-08-21 10:14
cc @edolstra

**Comment by edolstra** [comment] 2018-08-21 10:31
What does your `nix.conf` look like?

**Comment by cah6** [comment] 2018-08-21 13:39
Gahh forgot that some keys were there. Looks like at some point my nix.conf lost a line and so it became 
```
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI=binary-caches = https://cache.nixos.org https://nixcache.reflex-frp.org
```
instead of 
```
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI=
binary-caches = https://cache.nixos.org https://nixcache.reflex-frp.org
```
Feel free to resolve this however you want.

**Comment by xeji** [comment] 2018-08-21 13:42
Glad you found the cause of your problem. Closing as not-a-bug.

**Closed by xeji** 2018-08-21 13:42 UTC
