### ISSUE TITLE
systemd-timsyncd failing to start on nixos-unstable

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#66690] opened 2019-08-15 19:04 UTC
**Describe the bug**
When switching to nixos-unstable from nixos-19.03, I started getting this error:

```
● systemd-timesyncd.service - Network Time Synchronization
   Loaded: loaded (/nix/store/md7jdq475ij8cpifxb5rrh7y51qrfypq-systemd-242/example/systemd/system/systemd-timesyncd.service; enabled; vendor preset: enabled)
  Drop-In: /nix/store/6x8wf3bc69prnahjw0bz9cp96kbzw6ki-system-units/systemd-timesyncd.service.d
           └─overrides.conf
   Active: failed (Result: exit-code) since Thu 2019-08-15 14:59:24 EDT; 24ms ago
     Docs: man:systemd-timesyncd.service(8)
  Process: 5572 ExecStart=/nix/store/md7jdq475ij8cpifxb5rrh7y51qrfypq-systemd-242/lib/systemd/systemd-timesyncd (code=exited, status=238/STATE_DIRECTORY)
 Main PID: 5572 (code=exited, status=238/STATE_DIRECTORY)

Aug 15 14:59:24 dellbook systemd[1]: systemd-timesyncd.service: Service has no hold-off time (RestartSec=0), scheduling restart.
Aug 15 14:59:24 dellbook systemd[1]: systemd-timesyncd.service: Scheduled restart job, restart counter is at 5.
Aug 15 14:59:24 dellbook systemd[1]: Stopped Network Time Synchronization.
Aug 15 14:59:24 dellbook systemd[1]: systemd-timesyncd.service: Start request repeated too quickly.
Aug 15 14:59:24 dellbook systemd[1]: systemd-timesyncd.service: Failed with result 'exit-code'.
Aug 15 14:59:24 dellbook systemd[1]: Failed to start Network Time Synchronization.
```

I believe it is related to the systemd upgrade to 242. stateVersion is unset.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.66, NixOS, 19.09pre188690.8746c77a383 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre188690.8746c77a383"`
 - channels(mbauer): `"nixpkgs-19.09pre188239.c0e56afddbc"`
 - nixpkgs: `/home/mbauer/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: services.timesyncd
```

**Comment by Infinisil** [comment] 2019-08-15 21:37
Closing as duplicate of https://github.com/NixOS/nixpkgs/issues/64922

**Closed by Infinisil** 2019-08-15 21:37 UTC
Labels: 0.kind: bug
