### ISSUE TITLE
ssb-patchwork 3.17.7 crashing when clicking on icon "Chose profile image..."

### ISSUE THREAD

**Issue by alciono** [NixOS/nixpkgs#93246] opened 2020-07-16 11:50 UTC
**The bug**
ssb-patchwork crashing when clicking on icon "Chose profile image"

**To Reproduce**

1. After starting the app click on "Profile".
2. Click on "Edit Your Profile".
3. Click on icon "Chose Profile Image...".
4. The app crashes and disappears all together...

**Expected behavior**

Expecting to be able to add an Image  and keep editing the profile.

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.51, NixOS, 20.09pre234242.c71518e75bf (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre234242.c71518e75bf"`
 - channels(k): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by mkf** [comment] 2020-11-23 12:15
It fails with
```
(ssb-patchwork:2): GLib-GIO-ERROR **: 13:07:02.956: Settings schema 'org.gtk.Settings.FileChooser' is not installed
```

Which appears to be fixable just the way it was fixed in #84449 in commit d89ed04ea4670664d637fc80129ad03561b53fea, that is, by adding `wrapGAppsHook` in the arguments and in the `nativeBuildInputs`

I would like to add that I see all kinds of programs that use image/file choosers crash upon attempting to open such, one other example being, iirc, Zim (the local desktop wiki software).

**Comment by mkf** [comment] 2020-11-23 12:38
Mentioning maintainers: @asymmetric @NinjaTrappeur

**Comment by NinjaTrappeur** [comment] 2020-11-23 13:16
This issue is a duplicate of https://github.com/NixOS/nixpkgs/issues/76743

Potential fix:

- https://github.com/NixOS/nixpkgs/pull/83705

I currently work around that by lauching ssb from a terminal. It seems to inject the appropriate gsettings schema.

**Closed** 2020-11-23 13:18 UTC
Labels: 0.kind: bug, 2.status: duplicate

**Comment by mkf** [comment] 2020-11-23 14:10
> I currently work around that by lauching ssb-patchwork from a terminal. It seems to inject the appropriate gsettings schema.

The way I obtained the error message was by launching it from a terminal. It clearly doesn't do that for me. I use awesomewm and xterm.
