### ISSUE TITLE
firefox is slower than firefox-bin

### ISSUE THREAD

**Issue by ivan** [NixOS/nixpkgs#76484] opened 2019-12-25 04:40 UTC
**Describe the bug**

Repeated test runs of https://browserbench.org/Speedometer2.0/ in a clean Firefox profile show that nixpkgs firefox scores about 68.5, while Mozilla's firefox-bin scores 82 (both tested on Intel 4790K).

Mozilla builds Firefox with [Clang and LTO](https://glandium.org/blog/?p=3888), maybe should do that too?

**To Reproduce**
1. Install firefox and firefox-bin on NixOS master.
2. Run https://browserbench.org/Speedometer2.0/ a few times using both
3. Observe firefox result is ~83% of the firefox-bin result

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.5-hardened, NixOS, 20.03.git.14e375c (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`

cc maintainers @edolstra @andir

**Comment by andir** [comment] 2019-12-25 12:29
IIRC they are also doing some profile based optimizations and not just LTO. We can probably dig that out of their source trees or the build logs..

e.g. here is a log of an x86_64-linux optimized build: https://firefox-ci-tc.services.mozilla.com/tasks/X7r7t9OyTBWrJZ31Kg3itg/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FX7r7t9OyTBWrJZ31Kg3itg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

**Comment by lovesegfault** [comment] 2019-12-25 17:51
I recently tried enabling LTO for Thunderbird and ran into a myriad of issues before giving up. The Gentoo ebuilds support both LTO and PGO, but porting the support is not trivial, I think.

**Comment by lovesegfault** [comment] 2019-12-25 17:52
c.f. https://gitweb.gentoo.org/repo/gentoo.git/tree/www-client/firefox/firefox-71.0-r1.ebuild

Grep for `pgo` and `lto`

**Comment by wamserma** [comment] 2020-03-30 20:53
> c.f. https://gitweb.gentoo.org/repo/gentoo.git/tree/www-client/firefox/firefox-71.0-r1.ebuild
> 
> Grep for `pgo` and `lto`

here's a stable link https://gitweb.gentoo.org/repo/gentoo.git/tree/www-client/firefox/firefox-74.0-r2.ebuild?id=da126193051d51f5bf90d079b16883f553476cad

**Comment by S-NA** [comment] 2020-08-13 03:32
I have successfully built Firefox v79 with LTO using lld and clang from `llvmPackages_10` (i.e., `stdenv = super.overrideCC super.stdenv super.llvmPackages_10.lldClang;`) with some hardships of course.

The change in performance was a ~15% percent increase compared to the default `firefox` build under the Speedometer 2.0 benchmark. Note this is not a comparison to `firefox-bin`. As well as compared to the `firefox` build I patched in `sndio` support and had some extra configureFlags set such as `--enable-rust-simd`, etc., so your mileage may vary and this is a far from scientific result.

Some peculiar things likely due to using lld as the linker was the binaries produced by `firefox-unwrapped` had missing libraries, namely libunwind.so.1. I was able to fix this by using `patchelf --replace-needed` as well as setting `doInstallCheck = false`. The reason why `doInstallCheck` had to be set to `false` was because of the following error:

```
XPCOMGlueLoad error for file /nix/store/h7m3nb7i0l2a2qr954dcnwydjyxvfl9n-firefox-unwrapped-79.0/lib/firefox/libxul.so:
/nix/store/h7m3nb7i0l2a2qr954dcnwydjyxvfl9n-firefox-unwrapped-79.0/lib/firefox/libxul.so: undefined symbol: _ZN7mozilla11SandboxInfo10sSingletonE
Couldn't load XPCOM.
```

This was fixed by in the firefox wrapper setting `libs = "${self.firefox.passthru.unwrapped}/lib/firefox:" + oldAttrs.libs;` so the produced shell script exec's firefox works. Though directly launching the `firefox-unwrapped` variant does not. You can of course set `LD_LIBRARY_PATH` manually to `$out/lib/firefox` make it find the libraries.

I should mention this was all done in an overlay.

**Comment by lovesegfault** [comment] 2020-08-13 03:35
Could you share your work @S-NA? I've gone down this road before a few times and I've never succeeded past the "Couldn't load XPCOM" point in the installCheck, I'm glad you got it working!

If you put this up I can start playing with trying out PGO as well as LTO.

**Comment by S-NA** [comment] 2020-08-13 03:57
I have not had the chance to clean up the expression so it is a bit messy but sure here you go:
https://gist.github.com/S-NA/b8ed8fe9b1cb2b56d92f7201a11c4ad7

Enjoy.

**Comment by S-NA** [comment] 2020-10-05 20:57
I have a draft of LTO support (and some other stuff) into my firefox's [`common.nix`](https://github.com/S-NA/nixpkgs/blob/wip/firefox/pkgs/applications/networking/browsers/firefox/common.nix) for awhile now (since Firefox 79). The main change is Firefox is now built using `clang` and `lld` which allows easy LTO support. Going from Firefox 79 to 80 (and possibly 81 if it builds) required no significant changes which seems good.

I find it cleaner than what I originally had cobbled together to get LTO in https://github.com/NixOS/nixpkgs/issues/76484#issuecomment-673231152. I recently [hopefully] modified it to support Firefox 81. (It currently is building.) If someone is interested in testing it, make sure to override `ltoSupport = true;`. The main reason I have not tried to upstream it is the non-LTO Firefox configuration needs to be tested. In the event LTO breaks rather than delay an update, falling back to non-LTO should be easy. However, I am starting to wonder if that is really needed. Nevertheless, it needs more testing which is hard do because of long build times (which is purely from my own hardware limitations).

**Comment by wamserma** [comment] 2020-10-06 05:22
How about upstreaming it as `firefox-lto`? This would allow for painless testing and a smooth switchover once it has matured.

**Comment by colemickens** [comment] 2020-10-08 23:13
This gets a +1 from me. I've been wanting this. Are we actually worried about LTO causing regressions?

**Comment by colemickens** [comment] 2020-10-08 23:13
cc: @worldofpeace since they were interested in and merged my last firefox PR

**Comment by S-NA** [comment] 2020-10-09 03:57
> This gets a +1 from me. I've been wanting this. Are we actually worried about LTO causing regressions?

My apologies, I should have mentioned I created PR #99922 for this. As for LTO causing regressions it is a possibility but not one I think is worth being concerned about anymore. LTO support which implies `clang` and `lld` brings us closer to what upstream tooling is like for their Linux builds which is good.

Darwin is currently a mystery but it probably doesn't build. `lld` is unsupported there so it needs to be handled. I pushed a commit to place `--enable-linker=lld` behind a conditional to fix this but then realized `overrideCC` selection probably needs some more logic for Darwin. While investigating what needed to be done I learned LTO is broken across Darwin so for now I've asserted LTO doesn't work there. It should build but not with LTO unfortunately. I would appreciate if someone could verify that.

**Comment by worldofpeace** [comment] 2020-10-10 03:33
@colemickens I approved on @S-NA PR :sparkles: I will leave the merge up to andir.

**Comment by S-NA** [comment] 2021-01-21 05:42
I was able to build firefox with clang+lld+lto+pgo here: https://github.com/S-NA/nixpkgs/tree/wip/firefox-pgo
It is the bare minimum for what needs to be done to have PGO.

Ideally there should be a script to help maintainers obtain the correct PGO profiles for firefox versions. As the branch stands you have to manually hunt down the PGO profiles from the mozilla-release mercurial repository, and use the corresponding changeset id in taskcluster to obtain the download links.

Another issue would be that it seems Mozilla only publishes PGO profiles for Linux meaning PGO on Darwin is not possible for now. Not that was something possible in the first place since performing LTO on Darwin is apparently broken (in nixpkgs).

Benchmarks show it brings nixpkg's firefox to comparable performance of Mozilla's firefox-bin. 

<details>
<summary>Raw benchmark numbers</summary>
firefox with clang+lld+lto+pgo:
Iteration 1     62.71 runs/min
Iteration 2     62.08 runs/min
Iteration 3     62.84 runs/min
Iteration 4     62.94 runs/min
Iteration 5     63.52 runs/min
Iteration 6     63.19 runs/min
Iteration 7     60.45 runs/min
Iteration 8     62.82 runs/min
Iteration 9     63.28 runs/min
Iteration 10    62.19 runs/min
Arithmetic Mean:62.6 ± 0.63 (1.0%)

firefox-bin:
Iteration 1     62.69 runs/min
Iteration 2     62.49 runs/min
Iteration 3     60.64 runs/min
Iteration 4     62.02 runs/min
Iteration 5     61.49 runs/min
Iteration 6     63.66 runs/min
Iteration 7     62.98 runs/min
Iteration 8     62.94 runs/min
Iteration 9     61.17 runs/min
Iteration 10    63.22 runs/min
Arithmetic Mean:62.3 ± 0.70 (1.1%)
</details>

**Comment by lovesegfault** [comment] 2021-01-21 05:49
@S-NA Awesome! Any plans to start further work on this in a PR? I'm excited to try it!

**Comment by Atemu** [comment] 2021-01-21 12:44
> PGO on Darwin is not possible for now. Not that was something possible in the first place since performing LTO on Darwin is apparently broken (in nixpkgs).

Not possible anyways because you cannot even build Nixpkgs' regular FF on Darwin currently. (Not even `firefox-bin`.)

Speaking of variants, doesn't PGO make FF non-reproducible? If so, I think there should be a separate `firefox-pgo` package with a note in its description.

**Comment by wamserma** [comment] 2021-01-21 12:51
> Speaking of variants, doesn't PGO make FF non-reproducible? If so, I think there should be a separate `firefox-pgo` package with a note in its description.

Not a problem here, as profiling is done outside of Nixpkgs and the results of the profiling are provided as a static input.

**Comment by S-NA** [comment] 2021-01-21 23:39
> @S-NA Awesome! Any plans to start further work on this in a PR? I'm excited to try it!

Unfortunately I probably will not have the time to work on this to get it to a decent state any time soon. I would be happy if someone was able to turn the rough example into something that is suitable for merging. In the future if someone else does not get around to it, I will probably do it but as it stands, not any time soon, sorry.

> Not possible anyways because you cannot even build Nixpkgs' regular FF on Darwin currently. (Not even firefox-bin.)

This is nice to know but also is a bit sad.

> Speaking of variants, doesn't PGO make FF non-reproducible? If so, I think there should be a separate firefox-pgo package with a note in its description.

While this has been answered, I want to add on that I am unsure if Firefox is or was ever reproducible for nixpkgs. Has anyone actively build Firefox locally and compared it against the Firefox built on Hydra? [Upstream has a bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=885777) which mentions that clang itself sometimes generates non-deterministic code. However, this is not to say GCC does not either especially with a code base as large as Firefox. Upstream does not rigorously test (if at all) Firefox built with GCC, so non-determinism might be going by unnoticed.

**Comment by Atemu** [comment] 2021-01-22 07:29
What are the currently outstanding issues that would have to be fixed?

**Comment by S-NA** [comment] 2021-01-22 16:28
> What are the currently outstanding issues that would have to be fixed?

In the branch I shared, I added a profdata attribute which is used to supply the PGO profile for the corresponding Firefox version. It works but is probably not the right way to do things. For one, the PGO profile is different per platform yet this is not obvious since the meta attribute says `lib.platforms.unix` which includes Darwin. I understand that Darwin builds are broken so it is not that big of an issue but I would still prefer that profdata attribute/PGO profile is more obviously dependent on the platform. That being said I am not sure what is the best way to go about doing this.

Another issue is maintenance, I take that those who keep Firefox up to date rely on using the updateScript feature. I do not want to create a burden on the maintainers to manually fetch the PGO profiles or drastically change their workflow for keeping Firefox up to date. This means extending the updateScript feature to have knowledge about fetching the correct PGO profiles.

**Comment by ajs124** [comment] 2021-01-22 16:59
> I take that those who keep Firefox up to date rely on using the updateScript feature

I can only speak for myself, but for the updates I did, I did used that.

Firefox is without an official maintainer (besides @edolstra, whose last commit in the package was in 2019). IMO the package is quite a mess with too many features already, e.g. the long broken, but still in there, darwin support or pipewire, which works, but which I cannot test.

Which isn't to say that I'm against this, actually I'd like for Firefox to perform better, but someone should really do some spring cleaning and throw away all that unused and broken stuff, before we add more things in there.

**Comment by Kranzes** [comment] 2021-07-03 16:46
Any new updates about the state of this PR?

**Comment by S-NA** [comment] 2021-07-07 06:43
> Any new updates about the state of this issue?

See the mentioned PR above, it is not quite where I would like things. Namely, fetching the hashes for the PGO data. If anyone has an idea how to make it so that fetching the hashes for the PGO data is possible or a better solution I am happy to listen. It should work though if you are interested in trying it out.

**Comment by norpol** [comment] 2021-07-26 19:14
@Kranzes  Thunderbird is generally incredible slow for me, both ArchLinux and nixos, so I'm not sure whether these two things are related. I tried to find some tickets that describe this behavior, but I couldn't find anything.

**Comment by S-NA** [comment] 2021-10-09 03:37
What Atemu said, but some additional information if anyone is interested.

The consensus is the Firefox nix expression should generate its own profiles. Unfortunately, it seems generating our own profiles during a build is tricky for unclear reasons. During profile generation Firefox attempts to spin up a local server, and communicate via an extension. In the python script (build/pgo/profileserver.py) that oversees this process, it hits a wall waiting for Firefox to do something which it never does/fails to do. I have not had the time to dig into this so that is where it stands for now.

**Closed** 2022-03-28 19:42 UTC
Labels: 0.kind: enhancement
