### ISSUE TITLE
gcc-arm-embedded: arm-none-gdb Python exception

### ISSUE THREAD

**Issue by phodina** [NixOS/nixpkgs#352219] opened 2024-10-29 22:30 UTC
### Describe the bug
The `gdb` utility does not work as expected as it fails to start due to Python issue.

### Steps To Reproduce
```
$ nix-shell -p gcc-arm-embedded

[nix-shell:/tmp]$ arm-none-eabi-gdb
Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/nix/store/ir75m3g0dhjw942a7va6glhxssh5mqbw-python3-3.9.19/lib/python3.9/site.py", line 73, in <module>
    import os
  File "/nix/store/ir75m3g0dhjw942a7va6glhxssh5mqbw-python3-3.9.19/lib/python3.9/os.py", line 29, in <module>
    from _collections_abc import _check_methods
  File "/nix/store/ir75m3g0dhjw942a7va6glhxssh5mqbw-python3-3.9.19/lib/python3.9/_collections_abc.py", line 12, in <module>
    GenericAlias = type(list[int])
TypeError: 'type' object is not subscriptable
```

### Expected behavior
The `gdb` starts and waits for commands to debug binary.

### Additional context
```
$ arm-none-eabi-gcc --version
arm-none-eabi-gcc (Arm GNU Toolchain 12.3.Rel1 (Build arm-12.35)) 12.3.1 20230626
```

### Notify maintainers

@prusnak 
@mweinelt
@prtzl

### Metadata
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.3, NixOS, 24.05 (Uakari), 24.05.20240805.883180e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/79j6vc975md1w3f2fgli3xw657zyxxyc-source`
```

**Comment by prusnak** [comment] 2024-10-29 22:36
duplicate of https://github.com/NixOS/nixpkgs/issues/303651

**Closed by prusnak** 2024-10-29 22:36 UTC
Labels: 0.kind: bug
