### ISSUE TITLE
siunitx in latex is broken

### ISSUE THREAD

**Issue by avnik** [NixOS/nixpkgs#16366] opened 2016-06-20 17:15 UTC
## Issue description

`siunitx` in latex is broken (possible not `siunitx`, but `expl3` or even latex itself)

```
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/NixOS.org) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(./repro.tex
LaTeX2e <2014/05/01>
Babel <3.9l> and hyphenation patterns for 81 languages loaded.

(/nix/store/pr51dz57j6jd22jd8z54yb6jrclvdvfq-texlive-combined-full-2015/share/t
exmf/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class

(/nix/store/pr51dz57j6jd22jd8z54yb6jrclvdvfq-texlive-combined-full-2015/share/t
exmf/tex/latex/base/size10.clo))
(/nix/store/pr51dz57j6jd22jd8z54yb6jrclvdvfq-texlive-combined-full-2015/share/t
exmf/tex/latex/siunitx/siunitx.sty
(/nix/store/pr51dz57j6jd22jd8z54yb6jrclvdvfq-texlive-combined-full-2015/share/t
exmf/tex/latex/l3kernel/expl3.sty
(/nix/store/pr51dz57j6jd22jd8z54yb6jrclvdvfq-texlive-combined-full-2015/share/t
exmf/tex/latex/l3kernel/expl3-code.tex
(/nix/store/pr51dz57j6jd22jd8z54yb6jrclvdvfq-texlive-combined-full-2015/share/t
exmf/tex/latex/etex-pkg/etex.sty))
(/nix/store/pr51dz57j6jd22jd8z54yb6jrclvdvfq-texlive-combined-full-2015/share/t
exmf/tex/latex/l3kernel/l3unicode-data.def)
(/nix/store/pr51dz57j6jd22jd8z54yb6jrclvdvfq-texlive-combined-full-2015/share/t
exmf/tex/latex/l3kernel/l3dvips.def))

LaTeX Warning: You have requested, on input line 16, version
               `2015/09/11' of package expl3,
               but only version
               `2015/03/01 v5547 L3 programming layer (loader) '
               is available.


(/nix/store/pr51dz57j6jd22jd8z54yb6jrclvdvfq-texlive-combined-full-2015/share/t
exmf/tex/latex/l3packages/xparse/xparse.sty)

! Package siunitx Error: Support package expl3 too old
```
### Steps to reproduce

``` tex
\documentclass{article}
\usepackage{siunitx}
\begin{document}
foo
\end{document}
```

Then executing `latex repro.tex`  produce message above
## Technical details

nixos-version == 16.09.git.fd768f2 (Flounder)
(master built from yesterday's snapshot)

Also I know at lest one person who hit similiar problem on unstable (will ask him to reproduce and confirm).

PS summoning @vcunat  to thread

**Comment by laMudri** [comment] 2016-06-20 17:51
Confirmed on `nixos-unstable` using this `default.nix`:
```nix
let
  pkgs = import <nixpkgs> {};
  inherit (pkgs) stdenv texlive;

  tex-env = texlive.combine {
    inherit (texlive) scheme-small siunitx;
  };
in stdenv.mkDerivation {
  name = "siunitx-test";
  src = ./.;
  buildInputs = [ tex-env ];
}
```

**Comment by avnik** [comment] 2016-06-20 18:08
@laMudri Nice addition

Amendament: I tried on `texlive.combined.scheme-full` in system environment

**Comment by vcunat** [comment] 2016-06-20 19:18
This was introduced by 7abe192b05eea, and reverting that fixes the problem for me; e.g. it works on 16.03. I [was apprehensive](https://github.com/NixOS/nixpkgs/issues/10026#issuecomment-218441989) when the commit was done but I don't have a real solution.

**Comment by vcunat** [comment] 2016-06-20 19:36
To be more precise, I don't have enough time now to create and test a consistent texlive update.

**Comment by avnik** [comment] 2016-06-20 20:06
@vcunat I can try to fix it, but need some guidance/help

**Comment by vcunat** [comment] 2016-06-20 20:19
There seem to be multiple people interested in this. I'll think on how to best do this.

**Comment by vcunat** [comment] 2016-06-21 10:27
The test case seems OK with https://github.com/NixOS/nixpkgs/pull/16391

**Comment by Profpatsch** [comment] 2018-06-23 22:46
@vcunat is this fixed in newer texlive versions?

**Comment by vcunat** [comment] 2018-06-24 08:54
The test case works for me now on 18.03 with
```
nix-shell -p 'texlive.combine { inherit (texlive) scheme-small siunitx; }' -Q
```

It's probably OK since texlive-2016, and just noone's recalled this ticket.

**Closed by vcunat** 2018-06-24 08:54 UTC

**Comment by rnhmjoj** [comment] 2018-06-24 13:30
I can confirm it works on 18.03.132686.3a87c1aabae.
