### ISSUE TITLE
`buildPythonApplication` no longer checks that the dependencies are satisfied for `pyproject`

### ISSUE THREAD

**Issue by GrigorenkoPV** [NixOS/nixpkgs#253872] opened 2023-09-07 14:58 UTC
### Steps To Reproduce
1. Have a project like this one:
  * `default.nix`:
```nix
let
  pkgs = import <nixpkgs> { };
  python = pkgs.python310;
in
{
  build = python.pkgs.buildPythonApplication {
    name = "example";
    format = "pyproject";
    buildInputs = with python.pkgs; [ setuptools ];
    propagatedBuildInputs = with python.pkgs; [
      #emoji
    ];
    src = ./.;
  };
}
```
  * `pyproject.toml`:
```toml
[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "example"
description = "Sample Text"
version = "1.0.0"
requires-python = "~=3.10"
dependencies = ["emoji~=2.0"]

[tool.setuptools]
py-modules = ["example"]

[project.scripts]
example = "example:main"
```
  * `example.py`:
```python
import emoji

def main():
    print(emoji.emojize('Python is :thumbs_up:'))
```
2. Run `nix-build`

### Expected behavior

It fails to build:
```
Successfully built example
Finished creating a wheel...
Finished executing pipBuildPhase
installing
Executing pipInstallPhase
/build/test/dist /build/test
Processing ./example-1.0.0-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement emoji~=2.0 (from example) (from versions: none)
ERROR: No matching distribution found for emoji~=2.0

error: builder for '/nix/store/h5sj5gnr47p030xw4n8s3g8952y3sqfq-example.drv' failed with exit code 1;
       last 10 log lines:
       > Successfully built example
       > Finished creating a wheel...
       > Finished executing pipBuildPhase
       > installing
       > Executing pipInstallPhase
       > /build/test/dist /build/test
       > Processing ./example-1.0.0-py3-none-any.whl
       > ERROR: Could not find a version that satisfies the requirement emoji~=2.0 (from example) (from versions: none)
       > ERROR: No matching distribution found for emoji~=2.0
       > 
       For full logs, run 'nix-store -l /nix/store/h5sj5gnr47p030xw4n8s3g8952y3sqfq-example.drv'.
```

### Actual behavior
It builds successfully. Running the built program reveals missing dependencies:
```shell
$ ./result/bin/example
Traceback (most recent call last):
  File "/nix/store/60am1awx2jrjpdz9hjdk3vikjvnvzx1x-example/bin/.example-wrapped", line 6, in <module>
    from example import main
  File "/nix/store/60am1awx2jrjpdz9hjdk3vikjvnvzx1x-example/lib/python3.10/site-packages/example.py", line 1, in <module>
    import emoji
ModuleNotFoundError: No module named 'emoji'
```

### Additional context

I've run git bisect.

The first bad commit is e1cafe642a5e7d265d7b1dc55e2ddda81d219377.
The last good commit is e8cca499a84e06147d5d990dd0ae20ae17b21c66.
The three commits between those (6c85fff302615c62bf4f632bca661bc48298b0a3, 0d7647889c6701d8a0e6fa784e886012011ca2d8, & 349f57fb426225483f12e082e5ab5da8137eefe8) just cause `nix-build` to go unresponsive and eat more and more RAM indefinitely.

### Notify maintainers

@FRidh
@mweinelt
@jonringer
@tjni
@fabaff

**Comment by FRidh** [comment] 2023-09-07 15:04
Duplicate of #253131.

**Closed by FRidh** 2023-09-07 15:04 UTC
Labels: 0.kind: bug
