### ISSUE TITLE
Package request: zen-browser

### ISSUE THREAD

**Issue by Nika03** [NixOS/nixpkgs#349095] opened 2024-10-16 17:24 UTC
**Project description**

Beautifully designed, privacy-focused, packed with features web browser based on Firefox.

**Metadata**

* homepage URL: https://zen-browser.app/
* source URL: https://github.com/zen-browser/desktop/tree/stable
* license: MPL-2.0
* platforms: Windows, Linux, MacOS

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by clementpoiret** [comment] 2024-10-16 18:09
Duplicate of https://github.com/NixOS/nixpkgs/issues/327982
PR at https://github.com/NixOS/nixpkgs/pull/347222 (x86_64-linux only for now)

**Closed** 2024-10-16 18:11 UTC
Labels: 0.kind: packaging request
