### ISSUE TITLE
cartopy cannot find geos library

### ISSUE THREAD

**Issue by husnoo** [NixOS/nixpkgs#24805] opened 2017-04-10 21:16 UTC
## Issue description

Following this: http://nixos.org/nixpkgs/manual/#handling-dependencies, `propagatedBuildInputs` should link in run time dependencies. 

### Steps to reproduce
default.nix:
```
with import <nixpkgs> {};

(let cartopy = pkgs.pythonPackages.buildPythonPackage rec{
  name = "cartopy-${version}";
  version = "";

  src = pkgs.fetchurl{
  url = "mirror://pypi/c/cartopy/cartopy-0.11.0.tar.gz";
    sha256 = "85eb55d6ce16be5f7e745fcc2870b3fa7450db3a77899daade8b18711532be45";
  };
  doCheck = false;
  
  propagatedBuildInputs =  [ gcc pkgs.geos proj pythonPackages.numpy  pythonPackages.cffi pythonPackages.cython];
};
in python.buildEnv.override {
  extraLibs = [
    cartopy
    pkgs.geos
    proj
];
  ignoreCollisions = true;
}).env
```
Running it:
```
$ nix-shell
[nix-shell:~/]$ python
Python 2.7.13 (default, Dec 17 2016, 20:05:07) 
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cartopy
Failed `CDLL(libgeos_c.so.1)`
>>> 
>>> 
[nix-shell:~/]$ LD_LIBRARY_PATH=/nix/store/6ln1621k5rmnvc92dmcyf18614py37va-geos-3.6.1/lib/ python
Python 2.7.13 (default, Dec 17 2016, 20:05:07) 
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cartopy
>>> 
```

## Technical details
```
[nix-shell:~/]$ nixos-version
17.03.git.ac3cae0 (Gorilla)

[nix-shell:~/]$ nix-env --version
nix-env (Nix) 1.11.8

[nix-shell:~/]$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.03.git.ac3cae0631"

```

**Comment by husnoo** [comment] 2017-04-10 21:24
Related? https://github.com/NixOS/nixpkgs/issues/7307
I think ctypes is trying to load the library at runtime, so somehow I need to set LD_LIBRARY_PATH in my default.nix, preferably without the hash in the /nix/store/..............geos/lib/.

Any ideas?

thanks!

**Comment by FRidh** [comment] 2017-04-11 06:42
With Python on Nix you cannot rely on ctypes and have to patch code to use an absolute path to a library.
Therefore, in this case, you will have to patch the cartopy code to use an absolute path to refer to `libgeos_c.so.1`.

**Comment by FRidh** [comment] 2017-04-11 06:59
The issue here seems to be a bit different since `ctypes` or `cffi` doesn't seem to be used. The only references in `cartopy` to `geos` I can find are in `_trace.h` and `trace.pyx`. If Cython is used then `cartopy` should be able to find the library during runtime.

I took your Nix expression and built `cartopy` but got 
```
$ python
Python 2.7.13 (default, Dec 17 2016, 20:05:07) 
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cartopy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/h48zwwlpy3jf6idsql6svx5xzr32ayi7-python-2.7.13-env/lib/python2.7/site-packages/cartopy/__init__.py", line 23, in <module>
    import shapely.speedups
ImportError: No module named shapely.speedups
```

The NixOS version you mention is not a revision that is available via https://github.com/NixOS/nixpkgs/. What other changes did you make?

**Comment by husnoo** [comment] 2017-04-11 17:08
https://github.com/husnoo/nixpkgs/commit/ac3cae063135b1010d118b8d1dd643b422e64465

I only removed the system images from android, as not everyone has a 1 TB hdd.

I did have a few more libraries installed, I'll check later.

so I need to patch cartopy at  build time? it's that in the let.. clause above?

**Comment by husnoo** [comment] 2017-04-11 20:52
Full default.nix

```
with import <nixpkgs> {};

(let cartopy = pkgs.pythonPackages.buildPythonPackage rec{
  name = "cartopy-${version}";
  version = "";

  src = pkgs.fetchurl{
  url = "mirror://pypi/c/cartopy/cartopy-0.11.0.tar.gz";
    sha256 = "85eb55d6ce16be5f7e745fcc2870b3fa7450db3a77899daade8b18711532be45";
  };
  doCheck = false;
  
  propagatedBuildInputs =  [ gcc pkgs.geos proj pythonPackages.numpy  pythonPackages.cffi pythonPackages.cython];
};
in python.buildEnv.override {
  extraLibs = [
    cartopy
    pkgs.geos
    proj
    pkgs.pythonPackages.pygments
    pkgs.pythonPackages.pyaml
    pkgs.pythonPackages.markdown
    pkgs.pythonPackages.numpy
    pkgs.pythonPackages.msgpack
    pkgs.pythonPackages.scipy
    pkgs.pythonPackages.tables
    pkgs.pythonPackages.sqlalchemy
    pkgs.pythonPackages.scikitlearn
    pkgs.pythonPackages.sympy
    pkgs.pythonPackages.pyqt4
    pkgs.pythonPackages.shapely
    pkgs.pythonPackages.pyshp
    pkgs.pythonPackages.tensorflowWithoutCuda
    pkgs.pythonPackages.gnureadline
    pkgs.pythonPackages.h5py
    pkgs.pythonPackages.pandas
    pkgs.pythonPackages.dask
    pkgs.pythonPackages.scrapy
    pkgs.pythonPackages.matplotlib
    pkgs.pythonPackages.statsmodels
    pkgs.pythonPackages.seaborn
    pkgs.pythonPackages.bokeh
    pkgs.pythonPackages.requests2
    pkgs.pythonPackages.jupyter
    pkgs.pythonPackages.ipython
    pkgs.pythonPackages.cffi
    pkgs.pythonPackages.imageio
    pkgs.theano
];
  ignoreCollisions = true;
}).env
```

**Comment by husnoo** [comment] 2017-04-11 21:12
I think this issue was closed by accident - but I don't think I can re-open it. Should I submit a new one? thanks!

**Comment by husnoo** [comment] 2017-04-11 21:21
I attempted to supply the -I and -L paths at build time, but it didn't help.
```
  setupPyBuildFlags = ["-I${geos}/include" "-L${geos}/lib"];
```
FRidh, what's the recommended way to patch the path to geos?

thanks!

**Comment by FRidh** [comment] 2017-04-11 21:26
No, it wasn't closed by accident. You describe an issue with a package that is not part of Nixpkgs tree. Furthermore, I cannot reproduce your issue. I tried again, with nixos-17.03 @ 69d9061908162bd973fcf34d0fc6dc9d9f8cf9ed and again I could not reproduce your issue. 

I took the trace and made some fixes, but now another module is needed but missing (`shapefile`). I'm closing this again until you provide a minimal working example.

**Comment by husnoo** [comment] 2017-04-11 21:54
Hi, sorry I misunderstood your earlier request. Having deleted most of the libraries above, and then tried it, I had the same problem you mention with shapely, shapefile and six. this example is the smallest I can make it and reproduce the missing geos business:
```
with import <nixpkgs> {};

(let cartopy = pkgs.pythonPackages.buildPythonPackage rec{
  name = "cartopy-${version}";
  version = "";

  src = pkgs.fetchurl{
  url = "mirror://pypi/c/cartopy/cartopy-0.11.0.tar.gz";
    sha256 = "85eb55d6ce16be5f7e745fcc2870b3fa7450db3a77899daade8b18711532be45";
  };
  doCheck = false;
  setupPyBuildFlags = ["-I${geos}/include" "-L${geos}/lib"];
  propagatedBuildInputs =  [ gcc pkgs.geos proj pythonPackages.numpy  pythonPackages.cffi pythonPackages.cython pythonPackages.shapely pythonPackages.six pythonPackages.pyshp];
};


in python.buildEnv.override {
  extraLibs = [
    cartopy
];
  ignoreCollisions = true;
}).env
```

```
[nix-shell:~/nixshellish]$ python
Python 2.7.13 (default, Dec 17 2016, 20:05:07) 
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cartopy
Failed `CDLL(libgeos_c.so.1)`
>>> 
```

**Comment by husnoo** [comment] 2017-04-11 21:56
No such problem if I set the LD_LIBRARY_PATH:
```
[nix-shell:~/nixshellish]$ LD_LIBRARY_PATH=/nix/store/6ln1621k5rmnvc92dmcyf18614py37va-geos-3.6.1/lib/ python
Python 2.7.13 (default, Dec 17 2016, 20:05:07) 
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cartopy
>>> 
```

**Comment by husnoo** [comment] 2017-04-12 11:47
is this enough information to reopen please?

**Comment by FRidh** [comment] 2017-04-14 12:49
THanks

**Comment by FRidh** [comment] 2017-04-14 12:50
Now I can reproduce your issue, thank you.

**Comment by FRidh** [comment] 2017-04-14 13:08
I think the issue is with Shapely, I seem to be getting errors there with e.g. `from shapely.geometry import Point`.

**Comment by FRidh** [comment] 2017-04-14 13:22
Yep, shapely needs a bit more patching. Because it currently has no maintainers I think its up to you to fix it :)

**Comment by husnoo** [comment] 2017-04-14 15:04
Good catch! Apparently it's already being handled:

```
[nix-shell:~/data/analysis]$ find /nix/store/ | grep shapely | grep ".py$" | xargs grep libgeos_c.so
/nix/store/644s1aciw6c5mnqsy4l8ls5sca79iin5-python2.7-Shapely-1.5.15/lib/python2.7/site-packages/shapely/geos.py:    _lgeos = load_dll('geos_c', fallbacks=['/nix/store/6ln1621k5rmnvc92dmcyf18614py37va-geos-3.6.1/lib/libgeos_c.so'])
/nix/store/644s1aciw6c5mnqsy4l8ls5sca79iin5-python2.7-Shapely-1.5.15/lib/python2.7/site-packages/shapely/geos.py:        _lgeos = load_dll('geos_c', fallbacks=['/nix/store/6ln1621k5rmnvc92dmcyf18614py37va-geos-3.6.1/lib/libgeos_c.so'])
/nix/store/644s1aciw6c5mnqsy4l8ls5sca79iin5-python2.7-Shapely-1.5.15/lib/python2.7/site-packages/shapely/geos.py:    _lgeos = load_dll('geos_c', fallbacks=['/nix/store/6ln1621k5rmnvc92dmcyf18614py37va-geos-3.6.1/lib/libgeos_c.so'])
/nix/store/644s1aciw6c5mnqsy4l8ls5sca79iin5-python2.7-Shapely-1.5.15/lib/python2.7/site-packages/shapely/geos.py:    _lgeos = load_dll('geos_c', fallbacks=['/nix/store/6ln1621k5rmnvc92dmcyf18614py37va-geos-3.6.1/lib/libgeos_c.so'])
/nix/store/644s1aciw6c5mnqsy4l8ls5sca79iin5-python2.7-Shapely-1.5.15/lib/python2.7/site-packages/shapely/_buildcfg.py:                         fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
/nix/store/644s1aciw6c5mnqsy4l8ls5sca79iin5-python2.7-Shapely-1.5.15/lib/python2.7/site-packages/shapely/_buildcfg.py:                         fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
/nix/store/644s1aciw6c5mnqsy4l8ls5sca79iin5-python2.7-Shapely-1.5.15/lib/python2.7/site-packages/shapely/_buildcfg.py:                         fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
```

Further testing shows the cartopy library is working (or subtly broken, depending on whether or not I'm exercising the correct path...). So I guess the "Failed" is just sort of a warning, as it's falling back on the correct path:

```
>>> import shapely
>>> shapely.geos._lgeos._name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'geos'
>>> import shapely.geometry
Failed `CDLL(libgeos_c.so.1)`
>>> shapely.geos._lgeos._name
'/nix/store/6ln1621k5rmnvc92dmcyf18614py37va-geos-3.6.1/lib/libgeos_c.so'
>>>
```

**Comment by FRidh** [comment] 2017-04-14 17:54
Ah yes, now I see. Shapely has a function `load_dll` which loads a shared library. It first tries to find the library name, and then it checks the list of fallback names. Looking at the patch we have in Nixpkgs we pass the full library via the list of fallback names. That's why it fails initially but can be found afterall.

So, that means your issue *is* solved so now I can close this :)

**Closed by FRidh** 2017-04-14 17:54 UTC
Labels: 6.topic: python

**Comment by husnoo** [comment] 2017-04-14 19:48
Yes, thank you :-)
