### ISSUE TITLE
Dota 2 no longer works on NixOS after nemestice update

### ISSUE THREAD

**Issue by dali99** [NixOS/nixpkgs#128021] opened 2021-06-24 15:52 UTC
**Describe the bug**
After launching dota 2, the logo pops up, but game hangs after: see https://github.com/ValveSoftware/Dota-2/issues/1950 for another user of NixOS with same problem @Jwsonic

```
GameAction [AppID 570, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0/home/dan/.local/share/Steam/ubuntu12_32/../ubuntu12_32/reaper SteamLaunch AppId=570 -- '/mnt/henning/SteamLibrary/steamapps/common/dota 2 beta/game/dota.sh' +engine_experimental_drop_frame_ticks 1 +@panorama_min_comp_layer_dimension 0 -prewarm_panorama -vulkan_disable_steam_shader_cache  -vulkan -map dota\0
Game update: AppID 570 "", ProcID 654674, IP 0.0.0.0:0
ERROR: ld.so: object '/home/dan/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/dan/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/dan/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 654676 != 654675, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/dan/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Starting app 570
>>> Adding process 654674 for game ID 570
GameAction [AppID 570, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/dan/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 570, ActionID 1] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/dan/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 654675 for game ID 570
>>> Adding process 654677 for game ID 570
ERROR: ld.so: object '/home/dan/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 654678 for game ID 570
>>> Adding process 654679 for game ID 570
Installing breakpad exception handler for appid(steam)/version(1623193086)
Using breakpad crash handler
[S_API] SteamAPI_Init(): Loaded '/home/dan/.local/share/Steam/linux64/steamclient.so' OK.
Game update: AppID 570 "", ProcID 654678, IP 0.0.0.0:0
RecordSteamInterfaceCreation (PID 654678): SteamUtils010 / 
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
RecordSteamInterfaceCreation (PID 654678): SteamUser021 / User
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198053885117 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561198053885117
RecordSteamInterfaceCreation (PID 654678): SteamUtils010 / 
RecordSteamInterfaceCreation (PID 654678): SteamUser021 / 
Setting breakpad minidump AppID = 373300
RecordSteamInterfaceCreation (PID 654678): SteamFriends017 / 
RecordSteamInterfaceCreation (PID 654678): SteamMatchMaking009 / 
RecordSteamInterfaceCreation (PID 654678): SteamMatchGameSearch001 / 
RecordSteamInterfaceCreation (PID 654678): SteamMatchMakingServers002 / 
RecordSteamInterfaceCreation (PID 654678): STEAMUSERSTATS_INTERFACE_VERSION012 / 
RecordSteamInterfaceCreation (PID 654678): STEAMAPPS_INTERFACE_VERSION008 / 
RecordSteamInterfaceCreation (PID 654678): SteamNetworking006 / 
RecordSteamInterfaceCreation (PID 654678): STEAMREMOTESTORAGE_INTERFACE_VERSION014 / 
RecordSteamInterfaceCreation (PID 654678): STEAMSCREENSHOTS_INTERFACE_VERSION003 / 
RecordSteamInterfaceCreation (PID 654678): STEAMHTTP_INTERFACE_VERSION003 / 
RecordSteamInterfaceCreation (PID 654678): SteamController007 / 
RecordSteamInterfaceCreation (PID 654678): STEAMUGC_INTERFACE_VERSION014 / 
RecordSteamInterfaceCreation (PID 654678): STEAMAPPLIST_INTERFACE_VERSION001 / 
RecordSteamInterfaceCreation (PID 654678): STEAMMUSIC_INTERFACE_VERSION001 / 
RecordSteamInterfaceCreation (PID 654678): STEAMMUSICREMOTE_INTERFACE_VERSION001 / 
RecordSteamInterfaceCreation (PID 654678): STEAMHTMLSURFACE_INTERFACE_VERSION_005 / 
RecordSteamInterfaceCreation (PID 654678): STEAMINVENTORY_INTERFACE_V003 / 
RecordSteamInterfaceCreation (PID 654678): STEAMVIDEO_INTERFACE_V002 / 
RecordSteamInterfaceCreation (PID 654678): STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / 
RecordSteamInterfaceCreation (PID 654678): SteamInput001 / 
Attempting to create OpenGL context: v3.3 (Core profile)...success. Checking entry points...success.
WARNING: radv is not a conformant vulkan implementation, testing use only.
Fossilize INFO: Overriding serialization path: "/mnt/henning/SteamLibrary/steamapps/shadercache/570/fozpipelinesv5/steamapprun_pipeline_cache".
Fontconfig warning: "/mnt/henning/SteamLibrary/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/mnt/henning/SteamLibrary/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
RecordSteamInterfaceCreation (PID 654678): SteamUser021 / 
RecordSteamInterfaceCreation (PID 654678): SteamFriends017 / 
RecordSteamInterfaceCreation (PID 654678): SteamUtils010 / 
RecordSteamInterfaceCreation (PID 654678): SteamMatchMaking009 / 
RecordSteamInterfaceCreation (PID 654678): SteamMatchGameSearch001 / 
RecordSteamInterfaceCreation (PID 654678): SteamMatchMakingServers002 / 
RecordSteamInterfaceCreation (PID 654678): STEAMUSERSTATS_INTERFACE_VERSION012 / 
RecordSteamInterfaceCreation (PID 654678): STEAMAPPS_INTERFACE_VERSION008 / 
RecordSteamInterfaceCreation (PID 654678): SteamNetworking006 / 
RecordSteamInterfaceCreation (PID 654678): STEAMREMOTESTORAGE_INTERFACE_VERSION014 / 
RecordSteamInterfaceCreation (PID 654678): STEAMSCREENSHOTS_INTERFACE_VERSION003 / 
RecordSteamInterfaceCreation (PID 654678): STEAMHTTP_INTERFACE_VERSION003 / 
RecordSteamInterfaceCreation (PID 654678): SteamController007 / 
RecordSteamInterfaceCreation (PID 654678): STEAMUGC_INTERFACE_VERSION014 / 
RecordSteamInterfaceCreation (PID 654678): STEAMAPPLIST_INTERFACE_VERSION001 / 
RecordSteamInterfaceCreation (PID 654678): STEAMMUSIC_INTERFACE_VERSION001 / 
RecordSteamInterfaceCreation (PID 654678): STEAMMUSICREMOTE_INTERFACE_VERSION001 / 
RecordSteamInterfaceCreation (PID 654678): STEAMHTMLSURFACE_INTERFACE_VERSION_005 / 
RecordSteamInterfaceCreation (PID 654678): STEAMINVENTORY_INTERFACE_V003 / 
RecordSteamInterfaceCreation (PID 654678): STEAMVIDEO_INTERFACE_V002 / 
RecordSteamInterfaceCreation (PID 654678): STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / 
RecordSteamInterfaceCreation (PID 654678): SteamInput001 / 
RecordSteamInterfaceCreation (PID 654678): SteamUtils009 / Utils
RecordSteamInterfaceCreation (PID 654678): SteamNetworkingSocketsSerialized004 / 
RecordSteamInterfaceCreation (PID 654678): SteamUser020 / User
RecordSteamInterfaceCreation (PID 654678): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 654678): SteamUser021 / 
RecordSteamInterfaceCreation (PID 654678): SteamFriends017 / 
RecordSteamInterfaceCreation (PID 654678): SteamUtils010 / 
RecordSteamInterfaceCreation (PID 654678): SteamMatchMaking009 / 
RecordSteamInterfaceCreation (PID 654678): SteamMatchGameSearch001 / 
RecordSteamInterfaceCreation (PID 654678): SteamMatchMakingServers002 / 
RecordSteamInterfaceCreation (PID 654678): STEAMUSERSTATS_INTERFACE_VERSION012 / 
RecordSteamInterfaceCreation (PID 654678): STEAMAPPS_INTERFACE_VERSION008 / 
RecordSteamInterfaceCreation (PID 654678): SteamNetworking006 / 
RecordSteamInterfaceCreation (PID 654678): STEAMREMOTESTORAGE_INTERFACE_VERSION014 / 
RecordSteamInterfaceCreation (PID 654678): STEAMSCREENSHOTS_INTERFACE_VERSION003 / 
RecordSteamInterfaceCreation (PID 654678): STEAMHTTP_INTERFACE_VERSION003 / 
RecordSteamInterfaceCreation (PID 654678): SteamController007 / 
RecordSteamInterfaceCreation (PID 654678): STEAMUGC_INTERFACE_VERSION014 / 
RecordSteamInterfaceCreation (PID 654678): STEAMAPPLIST_INTERFACE_VERSION001 / 
RecordSteamInterfaceCreation (PID 654678): STEAMMUSIC_INTERFACE_VERSION001 / 
RecordSteamInterfaceCreation (PID 654678): STEAMMUSICREMOTE_INTERFACE_VERSION001 / 
RecordSteamInterfaceCreation (PID 654678): STEAMHTMLSURFACE_INTERFACE_VERSION_005 / 
RecordSteamInterfaceCreation (PID 654678): STEAMINVENTORY_INTERFACE_V003 / 
RecordSteamInterfaceCreation (PID 654678): STEAMVIDEO_INTERFACE_V002 / 
RecordSteamInterfaceCreation (PID 654678): STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / 
RecordSteamInterfaceCreation (PID 654678): SteamInput001 / 
 failed to dlopen "/mnt/henning/SteamLibrary/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libcairo.so" error=/mnt/henning/SteamLibrary/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libcairo.so: cannot open shared object file: No such file or directory
RecordSteamInterfaceCreation (PID 654678): SteamUser021 / 
RecordSteamInterfaceCreation (PID 654678): SteamFriends017 / 
RecordSteamInterfaceCreation (PID 654678): SteamUtils010 / 
RecordSteamInterfaceCreation (PID 654678): SteamMatchMaking009 / 
RecordSteamInterfaceCreation (PID 654678): SteamMatchGameSearch001 / 
RecordSteamInterfaceCreation (PID 654678): SteamMatchMakingServers002 / 
RecordSteamInterfaceCreation (PID 654678): STEAMUSERSTATS_INTERFACE_VERSION012 / 
RecordSteamInterfaceCreation (PID 654678): STEAMAPPS_INTERFACE_VERSION008 / 
RecordSteamInterfaceCreation (PID 654678): SteamNetworking006 / 
RecordSteamInterfaceCreation (PID 654678): STEAMREMOTESTORAGE_INTERFACE_VERSION014 / 
RecordSteamInterfaceCreation (PID 654678): STEAMSCREENSHOTS_INTERFACE_VERSION003 / 
RecordSteamInterfaceCreation (PID 654678): STEAMHTTP_INTERFACE_VERSION003 / 
RecordSteamInterfaceCreation (PID 654678): SteamController007 / 
RecordSteamInterfaceCreation (PID 654678): STEAMUGC_INTERFACE_VERSION014 / 
RecordSteamInterfaceCreation (PID 654678): STEAMAPPLIST_INTERFACE_VERSION001 / 
RecordSteamInterfaceCreation (PID 654678): STEAMMUSIC_INTERFACE_VERSION001 / 
RecordSteamInterfaceCreation (PID 654678): STEAMMUSICREMOTE_INTERFACE_VERSION001 / 
RecordSteamInterfaceCreation (PID 654678): STEAMHTMLSURFACE_INTERFACE_VERSION_005 / 
RecordSteamInterfaceCreation (PID 654678): STEAMINVENTORY_INTERFACE_V003 / 
RecordSteamInterfaceCreation (PID 654678): STEAMVIDEO_INTERFACE_V002 / 
RecordSteamInterfaceCreation (PID 654678): STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / 
RecordSteamInterfaceCreation (PID 654678): SteamInput001 / 
RecordSteamInterfaceCreation (PID 654678): SteamAppDisableUpdate001 / 
RecordSteamInterfaceCreation (PID 654678): SteamGameCoordinator001 / 
RecordSteamInterfaceCreation (PID 654678): SteamUser021 / User
Installing breakpad exception handler for appid(steam)/version(1623193086)
RecordSteamInterfaceCreation (PID 654678): SteamUser021 / 
RecordSteamInterfaceCreation (PID 654678): SteamFriends017 / 
RecordSteamInterfaceCreation (PID 654678): SteamUtils010 / 
RecordSteamInterfaceCreation (PID 654678): SteamMatchMaking009 / 
RecordSteamInterfaceCreation (PID 654678): SteamMatchGameSearch001 / 
RecordSteamInterfaceCreation (PID 654678): SteamMatchMakingServers002 / 
RecordSteamInterfaceCreation (PID 654678): STEAMUSERSTATS_INTERFACE_VERSION012 / 
RecordSteamInterfaceCreation (PID 654678): STEAMAPPS_INTERFACE_VERSION008 / 
RecordSteamInterfaceCreation (PID 654678): SteamNetworking006 / 
RecordSteamInterfaceCreation (PID 654678): STEAMREMOTESTORAGE_INTERFACE_VERSION014 / 
RecordSteamInterfaceCreation (PID 654678): STEAMSCREENSHOTS_INTERFACE_VERSION003 / 
RecordSteamInterfaceCreation (PID 654678): STEAMHTTP_INTERFACE_VERSION003 / 
RecordSteamInterfaceCreation (PID 654678): SteamController007 / 
RecordSteamInterfaceCreation (PID 654678): STEAMUGC_INTERFACE_VERSION014 / 
RecordSteamInterfaceCreation (PID 654678): STEAMAPPLIST_INTERFACE_VERSION001 / 
RecordSteamInterfaceCreation (PID 654678): STEAMMUSIC_INTERFACE_VERSION001 / 
RecordSteamInterfaceCreation (PID 654678): STEAMMUSICREMOTE_INTERFACE_VERSION001 / 
RecordSteamInterfaceCreation (PID 654678): STEAMHTMLSURFACE_INTERFACE_VERSION_005 / 
RecordSteamInterfaceCreation (PID 654678): STEAMINVENTORY_INTERFACE_V003 / 
RecordSteamInterfaceCreation (PID 654678): STEAMVIDEO_INTERFACE_V002 / 
RecordSteamInterfaceCreation (PID 654678): STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / 
RecordSteamInterfaceCreation (PID 654678): SteamInput001 / 
```

**To Reproduce**
Install dota 2, launch.

**Notify maintainers**

@jonringer @jagajaga

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.43, NixOS, 21.05.993.93963c27b93 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(dan): `"dan, home-manager-21.05, nixos-unstable-21.11pre297244.d2b489b24ae, nur"`
 - channels(root): `"nixos-21.05.1153.0ccd0d91361"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - steam
# a list of nixos modules affected by the problem
module:
```

**Comment by dali99** [comment] 2021-06-24 15:54
An AMD R9 290

**Comment by dali99** [comment] 2021-06-24 15:56
I've tried it with both the vulkan backend and opengl backend

**Comment by jonringer** [comment] 2021-06-24 15:57
You are probably hit with https://github.com/NixOS/nixpkgs/issues/126428

**Comment by dali99** [comment] 2021-06-24 16:00
I will try the linked PR (#126435) to see if it resolves the issue, thanks

**Comment by jonringer** [comment] 2021-06-24 16:23
the linked issue that you have shouldn't be applicable:
```
$ ./result/bin/steam-run bash
$ ls /lib/libcairo.so
/lib/libcairo.so
```
libcairo already exists in steamFHS

**Comment by dali99** [comment] 2021-06-24 16:34
The comments on the linked issue (https://github.com/ValveSoftware/Dota-2/issues/1950) are unrelated to the actual issue of the original author I think. Regardless dota 2 is complaining about not finding libcairo on nixos as well (from my logs above):
```
RecordSteamInterfaceCreation (PID 654678): SteamInput001 / 
 failed to dlopen "/mnt/henning/SteamLibrary/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libcairo.so" error=/mnt/henning/SteamLibrary/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libcairo.so: cannot open shared object file: No such file or directory
```

I tried steam from #126435 which didn't resolve the issue.
On vulkan I got a ton of fossilize warnings, but on opengl nothing changed.

**Comment by shpinog** [comment] 2021-06-24 17:15
Have this problem too

**Comment by jonringer** [comment] 2021-06-24 18:05
I'll install dota2 and try myself

**Comment by jonringer** [comment] 2021-06-24 19:24
This is a valve issue. They didn't distribute a library which they added as an absolute NEEDED library:

```
 failed to dlopen "/home/jon/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libcairo.so" error=/home/jon/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libcairo.so: cannot open shared object file: No such file or directory
 ```
```
$ ls /home/jon/.local/share/Steam/steamapps/common/dota\ 2\ beta/game/bin/linuxsteamrt64/
cairo.so                libicuuc.so            libpanorama_text_pango.so  libsoundsystem.so             libvgui2.so
dota2                   libinputsystem.so      libparticles.so            libsteam_api.so               libvguirendersurface.so
fltlnx64.flt            liblocalize.so         libphonon.so               libsteamaudio.so              libvideo.so
libanimationsystem.so   libmaterialsystem2.so  librendersystemempty.so    libsteamnetworkingsockets.so  libvphysics2.so
libavcodec.so.57        libmeshsystem.so       librendersystemgl.so       libswscale.so.4               libvr.so
libavformat.so.57       libmpg123.so.0         librendersystemvulkan.so   libtcmalloc_minimal.so.0      libvscript.so
libavresample.so.3      libnetworksystem.so    libresourcesystem.so       libtier0.so                   libworldrenderer.so
libavutil.so.55         libopenvr_api.so       libscenefilecache.so       libv8.so                      steam_appid.txt
libengine2.so           libpango-1.0.so        libscenesystem.so          libv8_libbase.so              WINDOWSTEMPDIR_FONTCONFIG_CACHE
libfilesystem_stdio.so  libpangoft2-1.0.so     libschemasystem.so         libv8_libplatform.so
libicui18n.so           libpanorama.so         libSDL2-2.0.so.0           libvconcomm.so
```

**Comment by jonringer** [comment] 2021-06-24 19:40
but even adding a libcairo.so doesn't fix the hang.... My assumption is that some shader is failing to build, so the loading screen which is waiting for it to complete, will not ever see it complete:
```
CEntitySystem::BuildEntityNetworking (parallel build of server) took 104.826 msecs for 1246 out of 1266 classes
Failed to load mutations file! scripts/battlepass/ti2018/mutations.txt
No valid vcs file found for shader generic.vfx
material2.cpp(1262): Error creating shader generic.vfx for material dev/panorama_world_panel_lit_opaque.vmat!
material2.cpp(1262): Error creating shader generic.vfx for material dev/panorama_world_panel_lit_opaque.vmat!
material2.cpp(1262): Error creating shader generic.vfx for material dev/panorama_world_panel_lit_opaque.vmat!
material2.cpp(1262): Error creating shader generic.vfx for material dev/panorama_world_panel_lit_opaque.vmat!
material2.cpp(1262): Error creating shader generic.vfx for material dev/panorama_world_panel_lit_default.vmat!
material2.cpp(1262): Error creating shader generic.vfx for material dev/panorama_world_panel_lit_default.vmat!
material2.cpp(1262): Error creating shader generic.vfx for material dev/panorama_world_panel_lit_default.vmat!
material2.cpp(1262): Error creating shader generic.vfx for material dev/panorama_world_panel_lit_default.vmat!
material2.cpp(1262): Error creating shader generic.vfx for material materials/dev/luminaire.vmat!
material2.cpp(1262): Error creating shader generic.vfx for material materials/dev/luminaire.vmat!
material2.cpp(1262): Error creating shader generic.vfx for material materials/dev/luminaire.vmat!
material2.cpp(1262): Error creating shader generic.vfx for material materials/dev/luminaire.vmat!
Error loading resource file "soundevents/soundevents_test.vsndevts_c" (Error: ERROR_FILEOPEN)
src/common/pipes.cpp (761) : Assertion Failed: bReceivedSomething
src/common/pipes.cpp (761) : Assertion Failed: bReceivedSomething
[STEAM] [S_API WARN] CUserRemoteStorage::GetFileSize( user.vcfg ) file not found
name[ 0 ] changing from 'unnamed' to 'xxx'
src/common/pipes.cpp (761) : Assertion Failed: bReceivedSomething
src/common/pipes.cpp (761) : Assertion Failed: bReceivedSomething
[STEAM] [S_API WARN] CUserRemoteStorage::GetFileSize( user_keys.vcfg ) file not found
CHostStateMgr::QueueNewRequest( Idle (levelload), 1 )
ChangeGameUIState: DOTA_GAME_UI_STATE_INVALID -> DOTA_GAME_UI_STATE_LOADING_SCREEN
Source2Init OK
```

**Comment by dali99** [comment] 2021-06-24 19:44
I was about to say the libcairo thing is probably a red herring, other distros _can_ launch the game with their native runtime even with the missing library. And since it "works on linux" that unfortunately usually means we'll somehow have to figure out why and fix this ourselves :confused:

**Comment by dali99** [comment] 2021-06-24 19:54
The patch that just came out: ~15 minutes ago #11853007 did not include a fix for this either

**Comment by p-h** [comment] 2021-06-24 20:37
```
% grep "Creating shader local hit cache directory" ~/.local/share/Steam/logs/shader_log.previous.txt
[2021-06-19 03:22:34] Creating shader local hit cache directory: /home/user/.local/share/Steam/userdata/62963436/config/shaderhitcache/33b9596faa80c826/009855639ea52e5ac8fa363d1093fd3c
[2021-06-19 03:23:04] Creating shader local hit cache directory: /home/user/.local/share/Steam/userdata/62963436/config/shaderhitcache/SteamSwarm/VulkanPipelinesV5
[2021-06-24 15:52:38] Creating shader local hit cache directory: /home/user/.local/share/Steam/userdata/62963436/config/shaderhitcache//nix/store/283097rcrw7lskm22lmam4nj2si1m0y1-mesa-21.0.1-drivers/bcb5ac8d6546e01e3f6175f51ee1ec9d2e3ad85d
[2021-06-24 16:19:56] Creating shader local hit cache directory: /home/user/.local/share/Steam/userdata/62963436/config/shaderhitcache//nix/store/283097rcrw7lskm22lmam4nj2si1m0y1-mesa-21.0.1-drivers/b03219d08417ddb4810bbbbe9f99d4553cd701d4
```

This looks suspicious. It seems the way the directory was named has changed since the update. This might also explain why the error only occurs in NixOS

**Comment by nh2** [comment] 2021-06-24 22:08
@p-h Those dirs are old for me though:

```
$ ls -l ~/.local/share/Steam/userdata/*/config/shaderhitcache/nix/store        

drwxr-xr-x 3 niklas users 3 Dec 29 01:42 90x38s26s6n5aq314iy0q8xh8bhwjmwf-mesa-20.1.7-drivers
drwxr-xr-x 4 niklas users 4 Mar 10 01:03 s4szd8c4dhy4bx9f0s9chlamcpdkx8cf-mesa-20.1.10-driver
```

Note `Dec 29` and `Mar 10`. Also, one folder for each mesa version. (Note I use NVIDIA currently, having an Optimus setup with both Intel and NVIDIA.)

**Comment by nh2** [comment] 2021-06-24 22:13
Moving the `shaderhitcache` away, after restarting I only get

```
config/shaderhitcache/fc815ab9a96b3321/009855639ea52e5ac8fa363d1093fd3c
```

So no more `/nix/store` in there. So that might be unrelated to our problem here.

**Comment by shpinog** [comment] 2021-06-24 22:25
> I was about to say the libcairo thing is probably a red herring, other distros _can_ launch the game with their native runtime even with the missing library. And since it "works on linux" that unfortunately usually means we'll somehow have to figure out why and fix this ourselves confused

I copied cairo to the directory indicated by the error, the error disappeared, but the game still hangs on the logo.

**Comment by p-h** [comment] 2021-06-24 22:27
@nh2 Ok, for me it regenerated it after I removed it. Also on an Optimus Setup.

@shpinog I tried to symlink it. Same result.

**Comment by nh2** [comment] 2021-06-24 22:41
`steam-run ~/.steam/steam/steamapps/common/dota\ 2\ beta/game/bin/linuxsteamrt64/dota2` **starts the game for me**.

Starting it via the `Play` button in the Steam UI does not work.

**Comment by p-h** [comment] 2021-06-24 22:46
@nh2 Does not work for me. Do you also get a bunch of `Fossilize WARN` messages?

**Comment by nh2** [comment] 2021-06-24 22:49
> @nh2 Does not work for me. Do you also get a bunch of `Fossilize WARN` messages?

@p-h No, my full output when playing on Vulkan is:

```
$ steam-run ~/.steam/steam/steamapps/common/dota\ 2\ beta/game/bin/linuxsteamrt64/dota2

Using breakpad crash handler
[S_API] SteamAPI_Init(): Loaded '/home/niklas/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198075047064 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561198075047064
Setting breakpad minidump AppID = 373300
Attempting to create OpenGL context: v3.3 (Core profile)...success. Checking entry points...success.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

Fossilize INFO: Overriding serialization path: "/home/niklas/.local/share/Steam/steamapps/shadercache/570/fozpipelinesv5/steamapprun_pipeline_cache".
Fontconfig warning: "/home/niklas/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/niklas/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
 failed to dlopen "/home/niklas/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libcairo.so" error=/home/niklas/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libcairo.so: cannot open shared object file: No such file or directory
 failed to dlopen "libtensorflow.so" error=libtensorflow.so: cannot open shared object file: No such file or directory
```

I have these in `environment.systemPackages`:

```
    (steam.override { extraProfile = ''unset VK_ICD_FILENAMES''; }) # TODO: Remove override when https://github.com/NixOS/nixpkgs/issues/108598#issuecomment-853489577 is fixed.
    steam-run-native
```

**Comment by p-h** [comment] 2021-06-24 22:55
@nh2 Ok, the #108598 workaround fixed that for me. Ty

**Comment by dali99** [comment] 2021-06-25 12:51
running steam-run from steam-run-native on dota2.sh works for me with no changes

**Comment by YellowOnion** [comment] 2021-07-01 12:17
Proton version of Dota 2 also hangs.

**Comment by neirenoir** [comment] 2021-07-01 21:37
I'm getting the same issue on ALL Proton games too. Final Fantasy XIV manages to launch up to the launcher, but after trying to log in and boot up the actual game, it crashes. Same happens with Risk of Rain 2 and others. This happened after upgrading my NixOS yesterday and the issue can be fixed by rolling back to the previous generation, so it is definitely something in our end.

**Comment by jansol** [comment] 2021-07-04 15:38
Sounds like it might be the same problem as #127068 then? From what i've seen in the output from Cloudbuilt (uses OpenGL and runs in proton), it seems it can't find graphics drivers at all. DXVK-backed games fail too but with less useful errors. Native OpenGL-based games seem to work though (Everspace, Shadow of the Tomb Raider).

**Comment by TredwellGit** [comment] 2021-07-10 00:33
Please test https://github.com/NixOS/nixpkgs/pull/129805.

**Comment by nh2** [comment] 2021-07-10 01:15
> Please test #129805.

Doesn't help for me (see https://github.com/NixOS/nixpkgs/pull/129805#issuecomment-877530443).

**Comment by TethysSvensson** [comment] 2021-08-03 11:03
This issue has now been fixed for me, possibly by another update to Dota 2.

**Comment by jtrees** [comment] 2021-08-03 12:27
Confirmed. Works for me now too.

**Comment by legendofmiracles** [comment] 2021-09-15 01:20
Can the issue be closed now?

**Closed** 2021-09-15 01:38 UTC
Labels: 0.kind: bug
