### ISSUE TITLE
cdemu Fails to Run Due to ImportError

### ISSUE THREAD

**Issue by JoNilsson** [NixOS/nixpkgs#325191] opened 2024-07-07 07:29 UTC
### Describe the bug:

Attempting to run `cdemu`, but encounter an error which prevents successful run. 
when checking the status with command `cdemu status` results in an `ImportError` related to `GLib`. 
Below is the detailed traceback from the command.

### Steps To Reproduce

1. Try to run `cdemu`, does not run.
2. Execute the command `cdemu status` in the terminal.

Output of command;
```sh
Traceback (most recent call last):
  File "/nix/store/ii25vcywqfbmkw3lzpr1fagj1ndxynwr-cdemu-client-3.2.5/bin/.cdemu-wrapped", line 33, in <module>
    from gi.repository import GLib
  File "/nix/store/40cddha2iiqzbqd6dpal3rlrgvb4p0yc-python3.11-pygobject-3.48.2/lib/python3.11/site-packages/gi/importer.py", line 133, in create_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name GLib, introspection typelib not found

```

### Expected behavior
`cdemu` should build, install and run.  The `cdemu status` command should execute without any errors, displaying the current status of cdemu.

### Screenshots
n/a

### Notify maintainers
Herwig Hochleitner aka @bendlas 

### Metadata
```console
[nix-shell:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.30-rt30, NixOS, 24.05 (Uakari), 24.05.20240507.b211b39`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `""`
 - nixpkgs: `/nix/store/f0ssy3p6898x9k880l23mhd0fl6rvrb2-source`
```
---

**Comment by JoNilsson** [comment] 2024-07-13 01:03
> > ```
> >  - host os: `Linux 6.6.30-rt30, NixOS, 24.05 (Uakari), 24.05.20240507.b211b39`
> > ```
> 
> I can't reproduce this issue on `release-24.05` or `unstable`. It looks like you may be running an outdated version. 

Excuse me,  an outdated version of what?    I'm running the most recent stable, and acquired `cdemu` from that channel. 

The problem persists.  This seems an issue with the package, not my system, or kernel. 

![image](https://github.com/user-attachments/assets/3fb9c07b-62bc-4432-86b1-c8b2cc1c4651)

**Comment by bendlas** [comment] 2024-07-13 08:58
> > > ```
> > >  - host os: `Linux 6.6.30-rt30, NixOS, 24.05 (Uakari), 24.05.20240507.b211b39`
> > > ```
> > 
> > 
> > I can't reproduce this issue on `release-24.05` or `unstable`. It looks like you may be running an outdated version.
> 
> Excuse me, an outdated version of what? I'm running the most recent stable, and acquired `cdemu` from that channel.

Of `nixpkgs`. Are you really sure? I'm having doubts, given that:

- Your timestamp says `20240507` ....
- .... which incidentally is 8 days before the conclusion of the linked PR, which fixed an issue with the **exact same error message**, as you're describing
- .... and the commit hash links to this one https://github.com/NixOS/nixpkgs/commit/b211b39

IDK ... can you reproduce it in a fresh vm or something?

**Comment by bendlas** [comment] 2024-07-22 05:39
closing as a likely PEBKAC, please reopen if the problem is observed on a current revision of `nixpkgs`

**Closed by bendlas** 2024-07-22 05:39 UTC
Labels: 0.kind: bug
