### ISSUE TITLE
iso: error nixos-install with nur packages

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#53582] opened 2019-01-07 17:46 UTC
## Issue description
Error nixos-install with nur packages
```
building the configuration in /mnt/etc/nixos/configuration.nix...
nix: src/libexpr/primops.cc:56: void nix::EvalState::realiseContext(const PathSet&): Assertion `store->isStorePath(ctx)' failed.
/run/current-system/sw/bin/nixos-install: line 99:  1531 Aborted                 nix build --out-link "$outLink" --store "$mountPoint" "${extraBuildFlags[@]}" --extra-substituters "$sub" -f '<nixpkgs/nixos>' system -I "nixos-config=$NIXOS_CONFIG"

```
### Steps to reproduce
Add to configuration
```
{ config, pkgs, fetchFromGitHub, ... }:
let
  nur = import (builtins.fetchTarball "https://github.com/nix-community/NUR/archive/master.tar.gz") { inherit pkgs; };

in {
  environment = {
    systemPackages = with pkgs; [
      nur.repos.mypkgs
    ];
  };
}
```
and run
nixos-install --root /mnt

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.20.0, NixOS, 19.03.git.16413c0 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2pre6526_9f99d624`
 - channels(root): `"nixos-19.03.git.16413c0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Mic92** [comment] 2019-01-08 09:17
cc @edolstra

**Comment by evanjs** [comment] 2019-05-26 19:55
AFAIK this is not a problem limited to NUR, but more the fetch functions during install in general (I think?)
#42557
https://github.com/NixOS/nix/issues/2497
Not sure if there's a more official issue, though.

**Comment by joepie91** [comment] 2019-06-11 20:21
Probably a duplicate of NixOS/nix#2405.

**Comment by evanjs** [comment] 2019-06-26 19:00
If so, it seems like https://github.com/NixOS/nix/commit/06010eaf199005a393f212023ec5e8bc97978537 should fix this.

**Comment by Izorkin** [comment] 2019-06-28 17:35
I checked, does not work:
nixos-install --root /mnt
```
building the configuration in /mnt/etc/nixos/configuration.nix...
nix: src/libexpr/primops.cc:56: void nix::EvalState::realiseContext(const PathSet&): Assertion `store->isStorePath(ctx)' failed.
/run/current-system/sw/bin/nixos-install: line 99:  1303 Aborted                 nix build --out-link "$outLink" --store "$mountPoint" "${extraBuildFlags[@]}" --extra-substituters "$sub" -f '<nixpkgs/nixos>' system -I "nixos-config=$NIXOS_CONFIG"
```
nix --version
```
nix (Nix) 2.3pre6779_324a5dc9
```
nix-info -m
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.15, NixOS, 19.09pre184217.74e217e6af5 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3pre6779_324a5dc9`
 - channels(root): `"nixos-19.09pre184217.74e217e6af5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Izorkin** [comment] 2019-06-28 17:35
cc @edolstra

**Comment by Mic92** [comment] 2020-06-02 16:57
Looks like https://github.com/NixOS/nix/commit/06010eaf199005a393f212023ec5e8bc97978537 is still non in any stable version of nix.

**Closed** 2020-06-02 18:27 UTC
