### ISSUE TITLE
22.05 Feature Freeze

### ISSUE THREAD

**Issue by dasJ** [NixOS/nixpkgs#167025] opened 2022-04-03 11:33 UTC
It's time for another feature freeze!

Let's clarify any blocking concerns for the 22.05 release in this thread, which will go live on May 30th.
Feature Freeze issue of th previous release: #140168
Release Schedule: #165792

**Edit**: I have crossed out subsystems that have responded that there are no blockers

Nix/nix-cli ecosystem: @Profpatsch @edolstra @grahamc @nbp
Mobile: @samueldr
~~NixOS Modules / internals: @ericson2314 @infinisil @alyssais @roberth~~
~~NixOS tests: @tfc~~
Marketing: @garbas @tomberek
~~Docs: @ryantm~~
Release: @NixOS/nixos-release-managers
Darwin: @NixOS/darwin-maintainers

~~BEAM: @NixOS/beam @minijackson~~
C: @matthewbauer @mic92
Coq: @CohenCyril @Zimmi48 @siraben @vbgl
~~Dhall: @Gabriel439 @ehmry~~
~~Emacs: @adisbladis~~
~~Vim/Neovim: @jonringer @softinio @teto~~
Go: @c00w @cstrahan @Frostman @kalbasit @mic92 @orivej @rvolosatovs @zowoq
Haskell: @NixOS/haskell
~~Python: @fridh @mweinelt @jonringer~~
Perl: @stigtsp
~~PHP: @NixOS/php @ma27~~
Ruby: @marsam
Rust: @andir @lnl7 @mic92 @zowoq
~~R: @bcdarwin @jbedo~~

Bazel: @mboes @marsam @uri-canva @avdv @olebedev @groodt @aherrmann @ylecornec
Blockchains: @mmahut @RaghavSood
Cinnamon: @mkg20001
~~DockerTools: @roberth @utdemir~~
GNOME: @NixOS/gnome @bobby285271 @dasj19 @maxeaubrey
~~Pantheon: @NixOS/pantheon~~
Podman: @NixOS/podman
PostgreSQL: @thoughtpolice
Qt / KDE: @NixOS/qt-kde
systemd: @NixOS/systemd

Everyone else: @NixOS/nixpkgs-committers @NixOS/release-engineers

If you think some subsystem/person/GitHub team should be added or removed for the next release, you can modify the list [here](https://github.com/NixOS/nixpkgs/blob/master/maintainers/team-list.nix#L17).

No issue is too big or too small, but let's remember that we are all working on the project voluntarily in our free time here, so let's focus on the issues that can be realistically addressed by release time. Thanks everyone!

**Comment by dasJ** [comment] 2022-04-03 11:35
Additional mentions because GitHub seems to stop pinging after I pinged too many people:

Blockchains: @mmahut @RaghavSood
Cinnamon: @mkg20001
DockerTools: @roberth @utdemir
GNOME: @bobby285271 @dasj19 @maxeaubrey
PostgreSQL: @thoughtpolice

**Comment by DianaOlympos** [comment] 2022-04-03 15:13
For @NixOS/beam i do not think we have anything that could be blocking on the docket.

**Comment by peterhoeg** [comment] 2022-04-03 15:22
For Crystal, we have the crystal-lang team.

Two issues that I absolutely want to get in before 22.05 is released:

- https://github.com/NixOS/nixpkgs/issues/164648
- https://github.com/NixOS/nixpkgs/issues/167044

**Comment by dasJ** [comment] 2022-04-03 15:29
@peterhoeg Thanks, I added them to the Blockers project. If you want to add the team to the next announcement, you can just set the `featureFreezePing` flag in the list :)

**Comment by ryantm** [comment] 2022-04-03 15:51
I'm not really up on what is going on with the docs themselves, but I'm not aware of anything blocking the technical aspect of generating the docs. I don't have much to report on progress with generating the docs either. `mmdoc` is now packaged in nixpkgs, but it still needs more work to be a polished solution.

**Comment by bobby285271** [comment] 2022-04-03 16:16
No blockers for @NixOS/Pantheon, we are already shipping the latest Pantheon 6.1 and Pantheon 7 is not likely to happen in this release due to upstream delay.

**Comment by teto** [comment] 2022-04-03 17:51
since I've noticed you started crossing topics: 
- no blocker for the lua ecosystem
- for (neo)vim, there will be a neovim release in 2 weeks and I would like to merge https://github.com/NixOS/nixpkgs/pull/166941 . None should be an issue though, I've already updated the required dependencies for neovim master

**Comment by etu** [comment] 2022-04-03 18:18
No blocker for PHP as far as I know :)

**Comment by drupol** [comment] 2022-04-03 18:23
> No blocker for PHP as far as I know :)

I think we should tackle this at the next version: https://github.com/NixOS/nixpkgs/issues/154774

**Comment by mweinelt** [comment] 2022-04-03 18:27
Python is currently in a good state. We're doing regular package set updates and have one more cycle in #166489 that we'll hopefully get into the next staging cycle.

PyPy3 currently fails to build due a regression after the zlib update.

**Comment by etu** [comment] 2022-04-03 19:08
> > No blocker for PHP as far as I know :)
> 
> I think we should tackle this at the next version: #154774

For sure, but we're too close to a release for that. We can do that right after branchoff which isn't relevant for this thread.

**Comment by SomeoneSerge** [comment] 2022-04-03 19:21
On behalf of the newly created @NixOS/cuda-maintainers, we're finishing an important major bump ([cudnn 7.6 -> 8.3](https://github.com/NixOS/nixpkgs/pull/166784/), cuda 10.1 -> 11.4) that we'd like to get into the release. There are a few failing packages that hadn't been tested with CUDA until now, that we would like to meet the release in an already fixed state: https://github.com/NixOS/nixpkgs/issues/167068

P.S. Keep in mind we're just getting acquainted with the release process:)

**Comment by jtojnar** [comment] 2022-04-03 19:38
For GNOME, we will want to include

- https://github.com/NixOS/nixpkgs/pull/166298
- https://github.com/NixOS/nixpkgs/pull/166096

And there are still some annoying regression. For some of them, we expect them to be fixed in GNOME 42.1 ([April 23](https://wiki.gnome.org/FortyTwo)).

- One of those makes GNOME Shell crash when clicking close button in window overview (Activities): https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5137 so we would want to update at least Shell and Mutter to 42.1.
- Some NetworkManager VPN plug-ins do not support GTK 4 so when one tries to configure them in GNOME Settings, they will only see `(Error: unable to load VPN connection editor)`. Not sure what to do about that. Perhaps we could merge https://github.com/NixOS/nixpkgs/pull/164531 and do not include them by default, since they are unmaintained any way.

----

For docs, we want:

- https://github.com/NixOS/nixpkgs/pull/166509

**Comment by roberth** [comment] 2022-04-03 20:39
* **NixOS module system**: no blocking issues.
Infinisil and I have made some quality of life improvements that have been merged for some time. We'll take it easy until branch-off, as far as I'm concerned.

 * **dockerTools**: also no blocking issues.

**Comment by Gabriel439** [comment] 2022-04-03 23:23
No blocking issues for Dhall

**Comment by mweinelt** [comment] 2022-04-04 03:13
The hydra package is currently failing to build which should be considered a blocker. Mostly expecting #160202 to get finished.

**Comment by jbedo** [comment] 2022-04-04 03:59
No blockers for R

**Comment by bhankas** [comment] 2022-04-04 04:49
Emacs 28.1 was cut yesterday.

Release tar: https://git.savannah.gnu.org/cgit/emacs.git/snapshot/emacs-28.1.tar.gz

 Perhaps @adisbladis can comment on requirement to be in the release.

**Comment by tfc** [comment] 2022-04-05 06:24
No blockers for the integration test driver

**Comment by Synthetica9** [comment] 2022-04-05 11:42
I'd really like to get #158175 fixed, but I'm not sure how feasible that is

**Comment by yeongsheng-tan** [comment] 2022-04-06 05:58
Could we please have [MySQL8.0.28 build issue in macOS](https://github.com/NixOS/nixpkgs/issues/159191) added to the 22.05 release?

**Comment by wamserma** [comment] 2022-04-06 08:04
"LXQt 1.1.0 will be released in the second half of April."
https://lxqt-project.org/blog/2022/03/31/lxqt-1.1.0-preview-second-part/

The window for DM changes closes on May 1st.

**Comment by teutat3s** [comment] 2022-04-07 20:44
> I'd really like to get #158175 fixed, but I'm not sure how feasible that is

The upstream fix was released, for all programs bundling their own version of electron I guess we'll have to wait until new versions get released containing the corresponding electron versions.
[The fix](https://github.com/electron/electron/pull/33499) is in `electron_17`: [17.3.1](https://github.com/electron/electron/releases/tag/v17.3.1)
`electron_18`: [18.0.1](https://github.com/electron/electron/releases/tag/v18.0.1)
but not backported to `electron_16` yet.

**Comment by samuela** [comment] 2022-04-08 20:16
apache-beam is currently broken: https://github.com/NixOS/nixpkgs/issues/167445 along with some other things in the JAX/TensorFlow ecosystem ([treex](https://github.com/NixOS/nixpkgs/issues/167522), [optax](https://github.com/NixOS/nixpkgs/issues/167520), [tensorflow-datasets](https://github.com/NixOS/nixpkgs/issues/167521), [tensorflow-bin](https://github.com/NixOS/nixpkgs/issues/167442), [flax](https://github.com/NixOS/nixpkgs/issues/167519), [dm-haiku](https://github.com/NixOS/nixpkgs/issues/167473))

**Comment by samueldr** [comment] 2022-04-08 21:04
Nothing to report for what I maintain.

**Comment by vlinkz** [comment] 2022-04-12 17:25
Any chance we can get #161788 in before release? This would replace the current graphical ISO images with ones containing the [calamares](https://calamares.io) installer. @davidak and I have done a decent amount of testing and are currently testing what I hope is the final version. Although before merging we should move [calamares-nixos-extensinos](https://github.com/vlinkz/calamares-nixos-extensions) to the NixOS org. When merged this could really help make NixOS more accessible to new users.

**Comment by dasJ** [comment] 2022-04-13 09:38
While I think that calamares should go into 22.05 (and I hope it does), it's still only a draft and I don't see a good reason to block the release on this.

**Comment by davidak** [comment] 2022-04-13 15:40
When Calamares is not polished enough in time, it should not go in and not block the release. Agreed!

**Comment by tpwrules** [comment] 2022-04-13 17:48
I'd really like to see #165876 and #165892 in before the feature freeze. People will end up testing them a lot before the actual release, and it will be easy to identify that there's a problem and revert if there's some situation where they break.

**Comment by vcunat** [comment] 2022-04-13 18:20
Will end up testing them a lot?  Can you explain?  I thought that users don't install so often.

Also, generally I'd like to dissuade people trying to squash as many "large changes" as possible in the last allowed moment.  (As we see such tendencies before every release.)  What's wrong with getting just into nixos-unstable for now?  My understanding is that most of contributors don't use the stable releases anyway.  For almost all packages the freeze is relatively short, just two or three weeks.

**Comment by tpwrules** [comment] 2022-04-13 18:56
I guess I hoped that people would boot the installer in order to make sure all that stuff was working. Especially if the Calamares version makes it in.

**Comment by cab404** [comment] 2022-04-14 06:49
We probably need to do something about sway 1.7 and https://github.com/electron/electron/issues/32487. If that doesn't get merged in electron till 22.05, I propose adding a separate derivation for sway 1.6 and defaulting to it.

**Comment by sternenseemann** [comment] 2022-04-15 13:06
No big changes blocking a release scheduled for Haskell anymore, but we have some prominent failures / regressions due to recent changes (see also https://github.com/NixOS/nixpkgs/issues/167859):

* `hasura-graphql-engine`
* `spago`
* `jl`

Out of those, at least `spago` should probably be fixed for 22.05.

**Comment by ehmry** [comment] 2022-04-15 14:57
At least two packages are breaking at runtime because of an icon related flaw in GTK. #163107 #168381

**Comment by vcunat** [comment] 2022-04-15 15:11
They sound like bugs, maybe the fixes will be quite simple.  Overall I find it unlikely that the feature freeze applies there, with fixes hopefully possible to backport at any later point.

**Comment by Madouura** [comment] 2022-04-16 02:21
We should probably ensure that #168303 is in 22.05, as it's a blocker for cross-compilation, in my case riscv64.

**Comment by mweinelt** [comment] 2022-04-16 02:23
> We should probably ensure that #168303 is in 22.05, as it's a blocker for cross-compilation, in my case riscv64.

Already part of #168737.

**Comment by adisbladis** [comment] 2022-04-20 19:37
Regarding Emacs:
Emacs 28 was merged in https://github.com/NixOS/nixpkgs/pull/168076 which is great timing for the release. No blockers.

**Comment by siraben** [comment] 2022-04-22 15:48
@CohenCyril @vbgl @Zimmi48 should we update the default version of Coq to the latest version (8.15)? No other blockers AFAIK.

**Comment by vbgl** [comment] 2022-04-22 19:23
Yes. I’m working on it.

**Comment by adisbladis** [comment] 2022-04-27 06:55
Enabling both `libcontainer` based software such as `runc`/`podman` and NixOS containers have been broken for years (https://github.com/NixOS/nixpkgs/issues/77925) and is fixed by moving configuration/state directories.

This is addressed by https://github.com/NixOS/nixpkgs/pull/87268 which should go in 22.05.

**Comment by jaen** [comment] 2022-04-28 22:02
Apologies in advance if this is the wrong place to talk about this (whether this is considered a breaking change or a release-worthy topic) as I never participated in a release, but maybe it would be useful to get https://github.com/NixOS/nixpkgs/pull/170655 in? At least for me I couldn't get VAAPI working in Brave without those changes, so it might be useful for other people to have this working OOtB in 22.05?

**Comment by mweinelt** [comment] 2022-04-28 22:41
Java/OpenJDK is pretty much unmaintained. We don't have OpenJDK 18. We do Have 17, 11 and8 (all LTS). But we also Have 16, 15, 14, 13, 12. 

https://github.com/NixOS/nixpkgs/issues/170825

@edwtjo @asbachb

**Comment by primeos** [comment] 2022-04-30 17:54
We could also really need additional LLVM maintainers as we barely manage to keep things up-to-date and working.
I finally opened a dedicated issue regarding that (this was long overdue): https://github.com/NixOS/nixpkgs/issues/171047
(Sorry for hijacking this issue but this seems relevant in general (LLVM is a [release critical package](https://nixos.github.io/release-wiki/Release-Critical-Packages.html), `llvmPackages_latest` will already be outdated for 22.05 (https://github.com/NixOS/nixpkgs/pull/165701), and it will probably be worse for the next stable release if we don't find additional maintainers.)

**Comment by Madouura** [comment] 2022-05-01 03:55
I know we're already in the 3rd stage of the release schedule, but I would **highly** recommend we include these commits in 22.05, even if breaking.

Not breaking
- #169380
- #166992

Potentially breaking
- #170991
- #170121

**Comment by vcunat** [comment] 2022-05-01 06:23
These will be included.  The minor update wouldn't be considered breaking anyway.  Support for riscv in NixPkgs is... [experimental?](https://github.com/nixos/rfcs/blob/master/rfcs/0046-platform-support-tiers.md), so I think there it's fine.  (Though I'm a bit doubtful about which riscv users will use stable?)

**Comment by SomeoneSerge** [comment] 2022-05-01 08:30
A silly question: we branch off master, things that are now in master are included?

**Comment by ulrikstrid** [comment] 2022-05-01 16:59
Does this need to be fixed before? https://github.com/NixOS/nixpkgs/issues/170897

**Comment by rnhmjoj** [comment] 2022-05-01 17:31
> A silly question: we branch off master, things that are now in master are included?

I think so: according to the release [schedule](https://github.com/NixOS/nixpkgs/issues/165792), the branch off is supposed to occur on May 22.

**Comment by 0x4A6F** [comment] 2022-05-01 22:22
#73404 is blocking installation if `config.boot.initrd.secrets` is set.

**Comment by nrdxp** [comment] 2022-05-02 00:21
> #73404 is blocking installation if `config.boot.initrd.secrets` is set.

Not sure if it is related, but I also have initrd secrets set, and on latest `nixos-unstable` I have a strange "not a git repo" error if I call `sudo nixos-rebuild`, but if I instead pass the `--use-remote-sudo` flag it rebuilds just fine :shrug:

**Comment by jaen** [comment] 2022-05-02 08:20
Seconding the "strange «not a git repo» error", since a while I need my rebuild process has to look like this to work:

  * run `nix build .#nixosConfigurations.host.config.system.build.toplevel` (it fails when `.git` is absent),
  * move `.git` folder away,
  * run `sudo nixos-rebuild boot  --flake.#host` (it fails when `.git is present`),
  * move `.git` folder back.

Specifically, the errors look like this:
```terminal
# When `.git` is present
╭─jaen@host /path/to/my/config/flake
╰─$ nix build .#nixosConfigurations.host.config.system.build.toplevel
error: '/path/to/my/config/flake' is not a Git repository

       … while fetching the input 'git+file:///path/to/my/config/flake'

# When `.git` is absent
╭─jaen@host /path/to/my/config/flake <some-branch>
╰─$ sudo nixos-rebuild boot --flake .#host --show-trace
[sudo] password for jaen:
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
usage: git diff --no-index [<options>] <path> <path>

# `git diff` help text follows

error: program 'git' failed with exit code 129

       … while fetching the input 'git+file:///path/to/my/config/flake'
```  

I don't think I'm doing anything out of ordinary in my config flake. The issue is pretty annoying for me, but in the end manageable – for someone new to NixOS it's just gonna scare them away if that's their first upgrade experience.

**Comment by rnhmjoj** [comment] 2022-05-02 08:53
> I have a strange "not a git repo" error if I call sudo nixos-rebuild

See https://github.com/NixOS/nixpkgs/issues/169193

**Comment by jtojnar** [comment] 2022-05-02 15:56
Regarding GNOME, there two more potentially problematic changes:

- adwaita-icon-theme removed majority of non-symbolic (colour) icons, which can make apps look [inconsistent](https://gitlab.gnome.org/GNOME/evolution/-/issues/1848) and in the worst case even make them unusable or crash (so far I have only encountered that in [Meld](https://github.com/NixOS/nixpkgs/pull/171273)). Probably something to note into ZHF.

- webkitgtk 3.36.0 does not render HTML on some systems e.g. [in Evolution](https://github.com/NixOS/nixpkgs/issues/168645), [gnucash](https://github.com/NixOS/nixpkgs/pull/170070), we need to check if 3.36.1 fixes that. Though that update breaks [tests of liferea](https://github.com/NixOS/nixpkgs/pull/170538#issuecomment-1114595744). And there is also [this issue](https://github.com/NixOS/nixpkgs/issues/169201), which might require us to switch back to wpe renderer. I would really appreciate if someone could help with webkitgtk maintenance, as I currently lack time for that.

**Comment by kjeremy** [comment] 2022-05-02 18:42
> Does this need to be fixed before? #170897

Whatever is going on with GLIBC here is breaking a lot of packages.

**Comment by dasJ** [comment] 2022-05-02 21:36
Since a lot of people are (probably) subscribed to this issue due to `@NixOS/nixpkgs-committers` being pinged, I'd prefer this issue to only have a minimal conversation.
This conversation should be about what issues may or should be blocking the release, issue-specific topics should be discussed in the respective issues/pull requests.

Now about some of these comments:
- #170897 is important because I don't know if the next update will be during the 22.05 cycle. This is not blocking imo because documentation can easily be backported or just referenced from the unstable manual
- #73404 is important and I think a fix should go into the release while not blocking the release since this is not a regression
- #169193 is important to flakes users. I'm not a flake user myself but from what I can gather from the issue, this should be backported in nix and not nixpkgs and is also a problem on 21.11 so not a regression
- I have no idea about the adwaita-icon-theme issue, me not caring about how consistent my icons look is a me-topic so the GNOME team should judge how critical the issue is
- The webkitgtk issue seems more severe and might be worth blocking the release (at least regarding more widely used tools), again the team should judge this. Some issues regarding this already seem to be resolved

This comment is my judgement on how blocking these issues are to the release. If you disagree with me, feel free to ping me in the respective issues to continue the discussion there rather than here.
Also, not being critical to the release does not mean I think these issues are not important. Something to consider is that we have a very well working backport wokflow now and some issues can be fixed during the release (like the documentation).

**Comment by NorfairKing** [comment] 2022-05-09 10:09
I would love to get a new stack release into nixos 22.05: https://github.com/commercialhaskell/stack/issues/5733 :D

**Comment by ners** [comment] 2022-05-16 08:56
I would love to get 22.05 ISOs VM-friendly, but it seems stuck in merge limbo: https://github.com/NixOS/nixpkgs/pull/172668

**Closed** 2022-05-30 19:12 UTC
Labels: 6.topic: release process
