### ISSUE TITLE
weechat: ImportError: No module named _sysconfigdata_nd

### ISSUE THREAD

**Issue by davidar** [NixOS/nixpkgs#11646] opened 2015-12-12 10:39 UTC
I'm having trouble running `weechat` on a standalone Nix install (on Debian):

``` sh
$ nix-env -i weechat
$ weechat
Traceback (most recent call last):
File "/nix/store/x3gfdavv38ghprna3z47grarwblgwb7f-python2.7-setuptools-18.2/lib/python2.7/site-packages/site.py", line 75, in <module>
  __boot()
File "/nix/store/x3gfdavv38ghprna3z47grarwblgwb7f-python2.7-setuptools-18.2/lib/python2.7/site-packages/site.py", line 35, in __boot
  imp.load_module('site',stream,path,descr)
File "/usr/lib/python2.7/site.py", line 563, in <module>
  main()
File "/usr/lib/python2.7/site.py", line 545, in main
  known_paths = addusersitepackages(known_paths)
File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
  user_site = getusersitepackages()
File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
  user_base = getuserbase() # this will also set USER_BASE
File "/usr/lib/python2.7/site.py", line 237, in getuserbase
  USER_BASE = get_config_var('userbase')
File "/usr/lib/python2.7/sysconfig.py", line 582, in get_config_var
  return get_config_vars().get(name)
File "/usr/lib/python2.7/sysconfig.py", line 528, in get_config_vars
  _init_posix(_CONFIG_VARS)
File "/usr/lib/python2.7/sysconfig.py", line 412, in _init_posix
  from _sysconfigdata import build_time_vars
File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
  from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdata_nd
```

**Comment by davidar** [comment] 2015-12-12 10:44
The bit which seems to go wrong is

```python
# This should actually reload the current module
imp.load_module('site',stream,path,descr)
```

which, instead of reloading the module, loads the Debian python library instead of the Nix one.

**Comment by grantwwu** [comment] 2016-02-12 03:22
I'm getting the same issue with weechat-1.4 on Debian as well.

**Comment by grahamc** [comment] 2016-12-17 17:23
I'm not having this issue at all with weechat on darwin or on nixos  (x86-64), closing. Please reopen if it isn't fixed for you :)

**Closed by grahamc** 2016-12-17 17:23 UTC
Labels: 0.kind: bug, 6.topic: python

**Comment by expipiplus1** [comment] 2018-03-22 12:46
I have encountered this with weechat-2.0 on Ubuntu 16.04

It's clearly getting the wrong python from somewhere:

```
Traceback (most recent call last):
File "/usr/lib/python2.7/site.py", line 563, in <module>
main()
File "/usr/lib/python2.7/site.py", line 545, in main
known_paths = addusersitepackages(known_paths)
File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
user_site = getusersitepackages()
File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
user_base = getuserbase() # this will also set USER_BASE
File "/usr/lib/python2.7/site.py", line 237, in getuserbase
USER_BASE = get_config_var('userbase')
File "/usr/lib/python2.7/sysconfig.py", line 582, in get_config_var
return get_config_vars().get(name)
File "/usr/lib/python2.7/sysconfig.py", line 528, in get_config_vars
_init_posix(_CONFIG_VARS)
File "/usr/lib/python2.7/sysconfig.py", line 412, in _init_posix
from _sysconfigdata import build_time_vars
File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdata_nd
```

**Comment by expipiplus1** [comment] 2018-03-22 13:01
This is necessary to build without python support as a workaround: https://github.com/NixOS/nixpkgs/pull/37622

**Comment by bdesham** [comment] 2019-08-01 16:26
I opened a dupe of this, #64167, because I hadn’t seen this issue. I also opened a PR, #64262—it hasn’t been merged yet but it seems to be ready!
