### ISSUE TITLE
FIlezilla cannot be installed on NixOS with `nix-env -iA`

### ISSUE THREAD

**Issue by totoroot** [NixOS/nixpkgs#164246] opened 2022-03-15 10:36 UTC
### Describe the bug
When installing Filezilla from unstable (Version 3.57.0) or 21.11 (Version 3.55.1) it aborts with the following error:

```
error: file 'REPEAT' was not found in the Nix search path (add it using $NIX_PATH or -I)
```

I can install it without a problem as a user package with home-manager, but not as a system package.

### Steps To Reproduce

`nix-env -iA nixos.filezilla`
or
`nix-env -iA unstable.filezilla`

### Expected behavior
Install Filezilla as system package.

### Notify maintainers

Pinging @pSub, as the package's maintainer 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.12, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(mathym): `"unstable"`
 - nixpkgs: `/nix/store/0zkxkjl7jzbkfwdxpw3rilwf831w5qpq-source`
```

**Comment by Artturin** [comment] 2022-03-15 11:05
Dupe of https://github.com/NixOS/nixpkgs/issues/163374

**Closed by Artturin** 2022-03-15 11:05 UTC
Labels: 0.kind: bug

**Comment by totoroot** [comment] 2022-03-15 11:07
Thanks, wasn't aware of that issue
