### ISSUE TITLE
`findutils` does not provide the command `locate`

### ISSUE THREAD

**Issue by UlyssesZh** [NixOS/nixpkgs#279004] opened 2024-01-05 20:37 UTC
### Describe the bug
`findutils` does not provide the command `locate`, but command-not-found claims that one can use `nix-shell -p findutils` to use the command `locate`.

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 23.11 (Tapir), 23.11.2561.b0b2c5445c64`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment] 2024-01-05 22:39
According to the long.description:

>       The tools supplied with this package are:
> 
>           * find - search for files in a directory hierarchy;
>           * xargs - build and execute command lines from standard input.
> 
>       The following are available in the locate output:
> 
>           * locate - list files in databases that match a pattern;
>           * updatedb - update a file name database;
   
So to use locate you have to do:
       
    nix-shell -p findutils.locate

**Comment by UlyssesZh** [comment] 2024-01-05 22:42
Then it seems like it's a case that command-not-found does not consider.

**Comment by SuperSandro2000** [comment] 2024-01-06 15:19
Yes, it is a known problem that cnf doesn't know about outputs.

Closing as dupe of #129713

**Closed by SuperSandro2000** 2024-01-06 15:19 UTC
Labels: 0.kind: bug
