### ISSUE TITLE
Windscribe 2.0 desktop client

### ISSUE THREAD

**Issue by gregoriomoss** [NixOS/nixpkgs#195429] opened 2022-10-10 23:07 UTC
**Project description**
Windscribe 2.0 desktop client for Windows, Mac and Linux 

**Metadata**

* homepage URL: https://windscribe.com/
* source URL: https://github.com/Windscribe/Desktop-App
* license: , GPL-2.0 license 
* platforms:  Windows, Mac and Linux

**Comment by wegank** [comment] 2022-10-10 23:44
Duplicate of #158368.

**Closed by wegank** 2022-10-10 23:44 UTC
Labels: 0.kind: packaging request
