### ISSUE TITLE
Komorebi Package Request

### ISSUE THREAD

**Issue by JoolthePlanet** [NixOS/nixpkgs#195664] opened 2022-10-12 13:00 UTC
**Project description**
Animated wallpaper manager for Linux.

**Purpose**
I wanted to set live wallpapers, but I can't find a good program to set live wallpapers seamlessly.

**Metadata**

* homepage URL: https://github.com/cheesecakeufo/komorebi
* source URL: https://github.com/cheesecakeufo/komorebi
* license: gpl3
* platforms: linux

**Comment by JoolthePlanet** [comment] 2022-10-12 13:06
Do I need to put (unofficial) if I didn't write this program?

**Comment by pinkcreeper100** [comment] 2022-10-12 16:47
no afaik

**Comment by dit7ya** [comment] 2022-10-13 06:24
Closing as duplicate of #190814.

**Closed by dit7ya** 2022-10-13 06:24 UTC
Labels: 0.kind: packaging request
