### ISSUE TITLE
Package request: thorium

### ISSUE THREAD

**Issue by MNkoder** [NixOS/nixpkgs#261701] opened 2023-10-17 19:58 UTC
**Project description**

<-- Describe the project a little:
It's basically a chromium fork.. and according to the dev.. it's the fastest browser on Earth. Although I'm no expert in these stuff, I second that statement. It's really faster than floorp (another great firefox fork (just checked and got to know that this isn't available as a nix package either, would be grateful if this package was added too)) and chromium. I compared them side by side and thorium was way faster -->

**Metadata**

* homepage URL: https://thorium.rocks/
* source URL: https://github.com/Alex313031/thorium
* license: BSD 3-Clause License
* platforms: Linux, Windows, MacOS, Android, and Raspberry Pi

**Comment by marijanp** [comment] 2023-10-18 09:50
Duplicate of #261700

**Comment by MNkoder** [comment] 2023-10-18 13:57
> Duplicate of #261700

ah nvm i just thought more requests would increase the chance of the project getting packaged

**Closed** 2023-10-18 15:26 UTC
Labels: 0.kind: packaging request

**Comment by MikaelFangel** [comment] 2023-10-18 15:28
Closed as duplicate.
