### ISSUE TITLE
Nixos tests fails depending on its name

### ISSUE THREAD

**Issue by symphorien** [NixOS/nixpkgs#34393] opened 2018-01-29 18:35 UTC
## Issue description

Nixos tests may fail depending on their name

### Steps to reproduce

```
$ cat a.nix
with import <nixpkgs/nixos/lib/testing.nix> { system="x86_64-linux"; };
makeTest {
  name = "run-predictableInterfaceNames-predictable-with-networkd";

  machine = { config, pkgs, ... }: {
  };

  testScript = ''
    $machine->succeed("true");
  '';
}
$  nix-build a.nix     
these derivations will be built:
  /nix/store/2844j0qrnxjzyxa1s3cwg9nnxdfw3zsj-vm-test-run-run-predictableInterfaceNames-predictable-with-networkd.drv
building path(s) ‘/nix/store/zc5fz0nry32k354gqchiw135mdn9hhgg-vm-test-run-run-predictableInterfaceNames-predictable-with-networkd’
starting VDE switch for network 1
running the VM test script
machine: must succeed: true
machine: waiting for the VM to finish booting
machine: starting vm
machine# Formatting '/tmp/nix-build-vm-test-run-run-predictableInterfaceNames-predictable-with-networkd.drv-0/vm-state-machine/machine.qcow2', fmt=qcow2 size=536870912 cluster_size=65536 lazy_refcou6
machine# qemu-system-x86_64: -usbdevice tablet: '-usbdevice' is deprecated, please use '-device usb-...' instead
machine# qemu-system-x86_64: -monitor unix:./monitor: Failed to connect socket ./monitor: No such file or directory
error: Can't use an undefined value as a symbol reference at /nix/store/22rg6kabcnqjadb6ajfdxqk8sq415dq3-nixos-test-driver/lib/perl5/site_perl/Machine.pm line 275.
Can't use an undefined value as a symbol reference at /nix/store/22rg6kabcnqjadb6ajfdxqk8sq415dq3-nixos-test-driver/lib/perl5/site_perl/Machine.pm line 275.
vde_switch: EOF on stdin, cleaning up and exiting
cleaning up
builder for ‘/nix/store/2844j0qrnxjzyxa1s3cwg9nnxdfw3zsj-vm-test-run-run-predictableInterfaceNames-predictable-with-networkd.drv’ failed with exit code 4
error: build of ‘/nix/store/2844j0qrnxjzyxa1s3cwg9nnxdfw3zsj-vm-test-run-run-predictableInterfaceNames-predictable-with-networkd.drv’ failed
```

If you change the name to "blah" the test succeeds.

At some point I thought it may be due to the length of the name, but if I change the name to
`blablahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahh`
I get a different failure:
```
building path(s) ‘/nix/store/h9sf3b5ls0s4s3kbj6nk9g8rwq2h4fr5-vm-test-run-blablahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahb’
starting VDE switch for network 1
Died at /nix/store/22rg6kabcnqjadb6ajfdxqk8sq415dq3-nixos-test-driver/bin/.nixos-test-driver-wrapped line 45, <$stdoutR> line 1.
vde_switch: EOF on stdin, cleaning up and exiting
cleaning up
builder for ‘/nix/store/y5hx2j4kfppa3pzspy9iszk8ay5adiyh-vm-test-run-blablahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahbl2
error: build of ‘/nix/store/y5hx2j4kfppa3pzspy9iszk8ay5adiyh-vm-test-run-blablahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahbld
```
## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.77, NixOS, 18.03pre125953.5402412b972 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre125953.5402412b972"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by srhb** [comment] 2018-01-30 21:32
I think the culprit is here: 
```
machine# qemu-system-x86_64: -monitor unix:./monitor: Failed to connect socket ./monitor: No such file or directory
```

However, something strange is going on with your setup. It appears to be building in /tmp despite your nix-info claiming that you have `nix.useSandbox = true;`. Are you sure that's set correctly? I believe the builder path should in that case be `/build/...` and I think the problem is related somehow as I can only reproduce it by disabling the sandbox.

**Comment by pbogdan** [comment] 2018-01-30 22:44
I believe 1.11 uses `/tmp` and only `nixUnstable` uses `/build`?

**Comment by pbogdan** [comment] 2018-01-30 23:25
Interesting. I think, after all, it _might_ be related to the length of the name. According to http://man7.org/linux/man-pages/man7/unix.7.html the max length of a path to a Unix domain socket is 108 bytes. With the test name:

> run-predictableInterfaceNames-predictable-with-networkd

under Nix 1.11.16 the path to the socket is 113 character long:

> /tmp/nix-build-vm-test-run-run-predictableInterfaceNames-predictable-with-networkd.drv-0/vm-state-machine/monitor

and indeed, deleting 5 random bytes from the name appears to fix the issue for me.

It's unclear why a different error is triggered with the much longer name `blah....` and doesn't occur without sandboxing?

**Comment by rnhmjoj** [comment] 2018-01-31 01:33
Strange, I don't get error `Died at /nix/store/...` nor `Failed to connect socket ./monitor`.
Counting the characters of the output path (/nix/store/...) this is what happens:

| count | result |
|:-------:|:-------|
| 0<n≤192 | *builds* |
| 192<n≤226 | `error: getting status of '/nix/store/...` |
| \>226 | `error: opening lock file '/nix/store/...'` |

I'm using nixUnstable (Nix 1.12pre5849_74f75c85) and NixOS (18.03pre125953.5402412b972).

**Comment by pbogdan** [comment] 2018-01-31 13:51
Hmm, at least for me the failure with the long `blah...` name seems to be due to another socket, namely `$builddir/vde1.ctl/ctl`. Since that's shorter than `$builddir/vm-state-machine/monitor` it would make sense a longer name is required to trigger this particular error. But wait, there is more!

> error: cannot bind shell socket: Address already in use

With a right name the monitor and shell socket will be attempted to be created at the same (truncated) path:

```
27614 lstat("/tmp/nix-build-vm-test-run-234567run-predictableInterfaceNames-predictable-with-networkd.drv-0/vm-state-machine/monitor", 0x7fffffffd010) = -1 ENOENT (No such file or directory)
27614 socket(AF_UNIX, SOCK_STREAM, 0)   = 8
27614 ioctl(8, TCGETS, 0x7fffffffce80)  = -1 ENOTTY (Inappropriate ioctl for device)
27614 lseek(8, 0, SEEK_CUR)             = -1 ESPIPE (Illegal seek)
27614 ioctl(8, TCGETS, 0x7fffffffce80)  = -1 ENOTTY (Inappropriate ioctl for device)
27614 lseek(8, 0, SEEK_CUR)             = -1 ESPIPE (Illegal seek)
27614 fcntl(8, F_SETFD, FD_CLOEXEC)     = 0
27614 bind(8, {sa_family=AF_UNIX, sun_path="/tmp/nix-build-vm-test-run-234567run-predictableInterfaceNames-predictable-with-networkd.drv-0/vm-state-mach"}, 110) = 0
27614 listen(8, 1)                      = 0
27614 lstat("/tmp/nix-build-vm-test-run-234567run-predictableInterfaceNames-predictable-with-networkd.drv-0/vm-state-machine/shell", 0x7fffffffd010) = -1 ENOENT (No such file or directory)
27614 socket(AF_UNIX, SOCK_STREAM, 0)   = 9
27614 ioctl(9, TCGETS, 0x7fffffffce80)  = -1 ENOTTY (Inappropriate ioctl for device)
27614 lseek(9, 0, SEEK_CUR)             = -1 ESPIPE (Illegal seek)
27614 ioctl(9, TCGETS, 0x7fffffffce80)  = -1 ENOTTY (Inappropriate ioctl for device)                                                                                                                                
27614 lseek(9, 0, SEEK_CUR)             = -1 ESPIPE (Illegal seek)                                                                                                                                                  
27614 fcntl(9, F_SETFD, FD_CLOEXEC)     = 0                                                                                                                                                                         
27614 bind(9, {sa_family=AF_UNIX, sun_path="/tmp/nix-build-vm-test-run-234567run-predictableInterfaceNames-predictable-with-networkd.drv-0/vm-state-mach"}, 110) = -1 EADDRINUSE (Address already in use)           
```

**Comment by symphorien** [comment] 2018-01-31 19:51
So if I understand well, the issue is triggered when too long sockets are created, failing when creating different sockets depending on the name of the derivation.
What would be nice, then, is that a error message explains that the derivation name is too long instead of the current behavior. There doesn't seem to be anything else we can do, right ?

**Comment by rnhmjoj** [comment] 2018-01-31 19:53
@symphorien I thought the same thing. I think it's a reasonable solution.

**Comment by manveru** [comment] 2018-02-19 11:21
@FRidh you think that's a reasonable "fix"?

**Comment by manveru** [comment] 2018-02-20 15:01
@symphorien does the new behavior work for you too?

**Comment by vcunat** [comment] 2018-03-04 13:46
Verified to be fixed by the PR (i.e. reported during evaluation).

**Closed by vcunat** 2018-03-04 13:46 UTC
Labels: 1.severity: blocker
