### ISSUE TITLE
PowerShell fails to build

### ISSUE THREAD

**Issue by schuelermine** [NixOS/nixpkgs#139746] opened 2021-09-28 12:06 UTC
### Describe the bug
PowerShell fails to build:
```
$ nix-build -E '(import <nixpkgs> {}).powershell`
### large number of lines skipped ###
error: builder for '/nix/store/gzii0y28w6zd93w5l6ash0bjj821j4xq-powershell-7.1.4.drv' failed with exit code 1;
       last 10 log lines:
       > searching for dependencies of /nix/store/3r2x0nfm904x44c9d1w7r09hwzpnx0p6-powershell-7.1.4/share/powershell/libSystem.IO.Compression.Native.so
       >   libz.so.1 -> found: /nix/store/43zy3j9a11icz158b336ahzf3bg7ykm1-zlib-1.2.11/lib/libz.so.1
       > setting RPATH to: /nix/store/43zy3j9a11icz158b336ahzf3bg7ykm1-zlib-1.2.11/lib
       > searching for dependencies of /nix/store/3r2x0nfm904x44c9d1w7r09hwzpnx0p6-powershell-7.1.4/share/powershell/createdump
       >   libmscordaccore.so -> found: /nix/store/3r2x0nfm904x44c9d1w7r09hwzpnx0p6-powershell-7.1.4/share/powershell/libmscordaccore.so
       >   libstdc++.so.6 -> found: /nix/store/vyqnqbp3yczrzjx2byk6p680q3mzanyw-gcc-10.3.0-lib/lib/libstdc++.so.6
       > setting RPATH to: /nix/store/3r2x0nfm904x44c9d1w7r09hwzpnx0p6-powershell-7.1.4/share/powershell:/nix/store/vyqnqbp3yczrzjx2byk6p680q3mzanyw-gcc-10.3.0-lib/lib
       > searching for dependencies of /nix/store/3r2x0nfm904x44c9d1w7r09hwzpnx0p6-powershell-7.1.4/share/powershell/libSystem.IO.Ports.Native.so
       > autoPatchelfHook could not satisfy dependency liblttng-ust.so.0 wanted by /nix/store/3r2x0nfm904x44c9d1w7r09hwzpnx0p6-powershell-7.1.4/share/powershell/libcoreclrtraceptprovider.so
       > Add the missing dependencies to the build inputs or set autoPatchelfIgnoreMissingDeps=true
       For full logs, run 'nix log /nix/store/gzii0y28w6zd93w5l6ash0bjj821j4xq-powershell-7.1.4.drv'.
```

### Steps To Reproduce
1. `nix-build -E '(import <nixos> {}).powershell`

### Expected behavior
PowerShell is built.

### Notify maintainers
@yrashk
@srgom

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```none
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.7, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210908_3c56f62`
 - channels(root): `"nixos-unstable-21.11pre318500.51bcdc4cdaa, nixos-stable-21.05.3314.83413f47809, nixos-21.11pre318500.51bcdc4cdaa"`
 - channels(anselmschueler): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: powershell
```

**Comment by Artturin** [comment] 2021-09-28 18:08
dupe of https://github.com/NixOS/nixpkgs/issues/138008

**Closed by Artturin** 2021-09-28 18:08 UTC
Labels: 0.kind: bug
