### ISSUE TITLE
/nix/store is writable inside root nix-shell

### ISSUE THREAD

**Issue by symphorien** [NixOS/nixpkgs#27362] opened 2017-07-13 21:07 UTC
## Issue description

Inside a nix-shell, but as root only, `/nix/store` is a rw bind mount

### Steps to reproduce

```
$ grep store /proc/self/mountinfo  
25 24 254:2 /nix/store /nix/store ro,relatime shared:13 - ext4 /dev/disk/by-uuid/f2eb657e-4c6c-4a53-b3db-67d1c4f7812d rw,data=ordered
$ nix-shell -p bash --run "grep store /proc/self/mountinfo" 
25 24 254:2 /nix/store /nix/store ro,relatime shared:13 - ext4 /dev/disk/by-uuid/f2eb657e-4c6c-4a53-b3db-67d1c4f7812d rw,data=ordered
$ sudo -s
[sudo] Mot de passe de root : 
# grep store /proc/self/mountinfo
25 24 254:2 /nix/store /nix/store ro,relatime shared:13 - ext4 /dev/disk/by-uuid/f2eb657e-4c6c-4a53-b3db-67d1c4f7812d rw,data=ordered
# nix-shell -p bash --run "grep store /proc/self/mountinfo"
178 151 254:2 /nix/store /nix/store rw,relatime shared:13 - ext4 /dev/disk/by-uuid/f2eb657e-4c6c-4a53-b3db-67d1c4f7812d rw,data=ordered
```

## Technical details

* System: NixOS 17.03.1368.cb90e6a036 (Gorilla)
* Nix version:  1.11.10
* Nixpkgs version: 17.03.1368.cb90e6a036
* Sandboxing enabled: yes

**Comment by FRidh** [comment] 2017-07-14 07:48
Is this a duplicate of https://github.com/NixOS/nix/issues/1336? In any case, this is a Nix issue and not a Nixpkgs issue so I am closing this. Please report it on the Nix tracker.

**Closed by FRidh** 2017-07-14 07:48 UTC
