### ISSUE TITLE
Cannot Install google-chrome (404).

### ISSUE THREAD

**Issue by AshtonKem** [NixOS/nixpkgs#25880] opened 2017-05-18 02:31 UTC
## Issue description

I cannot upgrade my older installation of NixOs from the 16.09 channel to 17.03. I am getting 404 errors around google-chrome. Here is the error that I get:

```
building path(s) ‘/nix/store/j9gg9jq5kwkgf2iwxd43sg706kr619c2-google-chrome-stable_57.0.2987.110-1_amd64.deb’

trying https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_57.0.2987.110-1_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 

trying http://95.31.35.30/chrome/pool/main/g/google-chrome-stable/google-chrome-stable_57.0.2987.110-1_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

trying http://mirror.pcbeta.com/google/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_57.0.2987.110-1_amd64.deb
Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.
Warning: Transient problem: timeout Will retry in 2 seconds. 2 retries left.
Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.
curl: (6) Couldn't resolve host 'mirror.pcbeta.com'

trying http://repo.fdzh.org/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_57.0.2987.110-1_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   185  100   185    0     0    578      0 --:--:-- --:--:-- --:--:--   579
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 
error: cannot download google-chrome-stable_57.0.2987.110-1_amd64.deb from any mirror
builder for ‘/nix/store/ma09gjhvhjl6036mldfn6wpfhq1dqxjf-google-chrome-stable_57.0.2987.110-1_amd64.deb.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/0w5ymgwxc61xnk59w2ir8yd7vbj89g0k-google-chrome-57.0.2987.110.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/cxpbg5kr91q1lrjvh7zlfwm8m6yxjk37-kernel-modules-shrunk’
cannot build derivation ‘/nix/store/4i4rjb076lxlgbdgg1ccrq3niriccq21-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/9cgbfk6habfmpk663qbg4g1plmq7pk3i-nixos-system-nixos-16.09.1942.28dc5c7d22.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/9cgbfk6habfmpk663qbg4g1plmq7pk3i-nixos-system-nixos-16.09.1942.28dc5c7d22.drv’ failed
```

### Steps to reproduce

Add google-chrome to the systemPackages

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
16.09.1903.c80a791 (Flounder)
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.8
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"16.09.1942.28dc5c7d22"
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
build-use-sandbox = false

**Comment by pbogdan** [comment] 2017-05-22 12:03
Is your 17.03 channel up to date? Chrome stable should on 57.0.2987.133 in 17.03 - https://github.com/NixOS/nixpkgs/blob/release-17.03/pkgs/applications/networking/browsers/chromium/upstream-info.nix#L16 and perhaps 57.0.2987.110 .deb is already gone.

**Comment by DCPRevere** [comment] 2017-07-23 21:23
@AshtonKem can you try running `sudo nix-channel --update` and then `sudo nixos-rebuild switch`? This worked for me.

**Comment by chris-martin** [comment] 2017-07-31 05:05
Chrome still does not build on `17.03`.

```
curl: (22) The requested URL returned error: 404
error: cannot download google-chrome-stable_58.0.3029.110-1_amd64.deb from any mirror
```

It seems fine on `unstable`, though.

**Comment by mogorman** [comment] 2017-07-31 14:40
having same problem even though i found the file elsewhere and did a nix-store --add  google-chrome-stable_58.0.3029.110-1_amd64.deb

**Comment by ixxie** [comment] 2017-08-04 07:11
I can confirm that moving from 17.03 to unstable fixed this issue.

**Comment by PierreR** [comment] 2017-08-09 15:34
Same problem for me (also using 17.03 stable) ... Very annoying as I did not expect such a failure on the stable branch.

**Comment by ocharles** [comment] 2017-08-16 13:03
Could we please get this ported from `unstable` to 17.03? It's quite frustrating that we haven't had a working Google Chrome for three months on the recommended branch!

**Comment by ixxie** [comment] 2017-08-16 18:15
@ocharles - you can port it yourself. I have the following in my `configuration.nix`:

    nixpkgs.config = 
    {
        # Allow proprietary packages
        allowUnfree = true;

        # Create an alias for the unstable channel
        packageOverrides = pkgs: 
        {
            unstable = import <nixos-unstable> 
                { 
                    config = config.nixpkgs.config; 
                };
        };
    };

Which allows you to switch particular packages to the unstable channel:

    environment = 
    {
        systemPackages = 
            with pkgs; 
            [
                ddate
                devilspie2
                evince
                unstable.google-chrome
                ...
                zsh
	    ]; 
    };

**Comment by ocharles** [comment] 2017-08-17 17:21
While that works, we really need to get this into stable.

**Comment by PierreR** [comment] 2017-08-22 10:05
Still not fixed in stable but hopefully it is a matter of days now.

 I concur with @ocharles These kind of issues on the stable branch are really a pain on the end user side.

By the way,  would `firefox` be a better choice as a stable browser on nixos-stable ?

**Comment by instantepiphany** [comment] 2017-08-23 11:01
I am having the same issue.

I am very thankful that I get to use NixOS on my machines, so with that in mind, could one of the lead developers update us on what is happening?

If I understand correctly, stable 17.03 references chrome versions that are out of date, and so aren't mirrored anywhere.

I thought for a minute that they should be mirrored on Hydra, but Hydra only caches projects it has built, which means it won't cache Chrome as Chrome is non-free, correct?

Is this something that someone with less nixpkgs packaging experience could help update? I have added a few Vim plugins and written a few local packages for basic compiled programs, but don't have nixpkgs experience other than that (apart from using it to manage my personal system).

**Comment by PierreR** [comment] 2017-08-23 19:57
As a side note, whoever fix this could take the opportunity to add himself as a maintainer: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/google-chrome/default.nix#L141
(I doubt the sole member of the set is still around)

@instantepiphany Thanks for your input

**Comment by chris-martin** [comment] 2017-09-23 02:23
Can this issue be closed since google-chrome is working in 17.09, or is there something that needs to be future-proofed to prevent this from happening again?

**Comment by ocharles** [comment] 2017-09-23 08:35
Well 17.09 isn't even out, so I don't think it can be closed yet. I'm still rather unhappy with the situation, but maybe the solution is to scratch the itch and become a maintainer for this.

**Comment by yegortimoshenko** [comment] 2017-12-23 21:49
See https://github.com/NixOS/nixpkgs/issues/27811#issuecomment-353750050.

Also I think we should close issues immediately as they are fixed in master, otherwise it's impossible to track what has been fixed and what still needs fixing.

**Closed by yegortimoshenko** 2017-12-23 21:49 UTC
Labels: 0.kind: regression, 3.skill: good-first-bug, 9.needs: package (update)
