### ISSUE TITLE
update-users-groups.pl malformed JSON string, neither array, object, number, string or atom, at character offset 0

### ISSUE THREAD

**Issue by nixinator** [NixOS/nixpkgs#126971] opened 2021-06-15 16:49 UTC
**Describe the bug**

update-users-groups.pl fails with malfomed JSON :-(

nixos-rebuild switch

building Nix...
building the system configuration...
activating the configuration...
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "\x{0}\x{0}\x{0}\x{0}...") at /nix/store/iczcvcwxd9pz9agwci6m1f65aywa2jyi-update-users-groups.pl line 294.
Activation script snippet 'users' failed (2)
setting up /etc...
reloading user units for sddm...
reloading user units for user...
setting up tmpfiles
warning: error(s) occurred while switching to the new configuration

**To Reproduce**

nixos-rebuild switch

**Expected behavior**

uid and gid tables to be build successfully.

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.3.11, channels(root): "nixos-20.09.4321.115dbbe82eb", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
system

# a list of nixos modules affected by the problem
module:
```
system

**Comment by MatthewCroughan** [comment] 2021-08-14 20:25
Check the contents of `/var/lib/nixos/auto-subuid-map` and ensure that it is valid JSON like:
```
❯ cat /var/lib/nixos/auto-subuid-map 
{"matthew":100000}
```

**Comment by MatthewCroughan** [comment] 2021-08-14 20:50
In private chat, we discovered that the `auto-subuid-map` file had been corrupted somehow:

```
[matthew@nasa:~]$ cat /var/lib/nixos/auto-subuid-map.bak 

[matthew@nasa:~]$ cat /var/lib/nixos/auto-subuid-map
{"l33":165536,"matthew":100000,"astral0":165536}

[matthew@nasa:~]$ xxd /var/lib/nixos/auto-subuid-map.bak 
00000000: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000010: 0000 0000 0000 0000 0000 0000 0000 0000  ................

[matthew@nasa:~]$ xxd /var/lib/nixos/auto-subuid-map
00000000: 7b22 6c33 3322 3a31 3635 3533 362c 226d  {"l33":165536,"m
00000010: 6174 7468 6577 223a 3130 3030 3030 2c22  atthew":100000,"
00000020: 6173 7472 616c 3022 3a31 3635 3533 367d  astral0":165536}
00000030: 0a                                       .
````

The issue has been fixed by removing the file with `rm /var/lib/nixos/auto-subuid-map`.

**Closed** 2021-08-14 22:44 UTC
Labels: 0.kind: bug, 6.topic: nixos

**Comment by superherointj** [comment] 2023-01-25 17:30
I also had this issue of `malformed JSON string`, solved by deleting files:
* /var/lib/nixos/gid-map
* /var/lib/nixos/uid-map
And rebuilding NixOS.

**Comment by nixinator** [comment] 2023-01-25 17:46
The question remains, how is this getting corrupted . A race condition....this is going to be hard to reproduce.

**Comment by q3k** [comment] 2024-02-15 11:59
My guess is that this is a bug in File::Slurp's atomic implementation of `write_file`. A bug in the sense that it doesn't actually persist the writes to disk, and file corruption can occur if the FS isn't fully synced before power off.

This is where we use this function: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/update-users-groups.pl#L23

And this is its source, emphasis on the atomic code path: https://metacpan.org/dist/File-Slurp/source/lib/File/Slurp.pm#L330

Unfortunately, `write(tmp, data), rename(tmp, new)` is not enough for an atomic write. You also need to `fsync(tmp)` in between `write()` and `rename()`. A plain `rename()` is atomic in the sense that the rename operation is atomic, but it doesn't ensure that whatever was in the old file is actually synced to disk.

See this `google/renameio` Go library bug for more explanation: https://github.com/google/renameio/issues/11

**Comment by etehtsea** [comment] 2026-04-29 05:21
Just in case, this one is still an issue.
Dropping corrupted file helps, but the source of the issue is still here
