### ISSUE TITLE
pytorch / pytorch-bin behave diffrently wrt cuda

### ISSUE THREAD

**Issue by lizelive** [NixOS/nixpkgs#189372] opened 2022-09-01 23:02 UTC
### Describe the bug
pytorch / pytorch-bin behave handle cuda differently

### Steps To Reproduce
`nix-shell -p python310Packages.pytorch --run 'python3 -c "import torch; print(torch.cuda.is_available())"'`
False
`nix-shell -p python310Packages.pytorch-bin --run 'python3 -c "import torch; print(torch.cuda.is_available())"'`
True

### Expected behavior
i would expect the same behavior
Ideally both would return True if cuda is supported

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[lizelive@l05:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.63, NixOS, 22.05 (Quokka), 22.05.2785.cc634d9aa08`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by lizelive** [comment] 2022-09-01 23:04
(for tensorflow they both don't have cuda)

**Comment by tpwrules** [comment] 2022-09-02 01:14
Not sure there's much to be done here. The binary Pytorch wheels ship with the redistributable CUDA binaries because that's how upstream has chosen to distribute them them, and evidently Tensorflow wheels don't come with them. Nixpkgs does not enable CUDA support in source builds by default, both because CUDA is unfree software so Hydra will not build them anyway, and because CUDA toolkits cannot be redistributed with the source components.

You are welcome to build Pytorch from source with CUDA yourself simply by overriding with `cudaSupport = true;` but be warned this will take a few dozen CPU hours; less if you set the `cudaArchList` to only what you need for your specific card. Alternately, you can use the Nixpkgs CUDA maintainers cache as described [on the wiki](https://nixos.wiki/wiki/CUDA), or just use the binary distribution of Pytorch.

**Comment by samuela** [comment] 2022-10-27 00:51
For future googlers, check out the `python3Packages.torchWithCuda` package which should do what you want. However, `cache.nixos.org` doesn't keep binary caches for that package since it includes CUDA which is unfree, but if you use the [cuda-maintainers](https://app.cachix.org/cache/cuda-maintainers#pull) cache you should be able to avoid having to build from source. You can find more info [in the wiki here](https://nixos.wiki/wiki/CUDA).

I'm going to close this for now, since I think this is basically working as intended (or at least as closely as possible) as @tpwrules notes.

**Closed by samuela** 2022-10-27 00:51 UTC
Labels: 0.kind: bug
