### ISSUE TITLE
SANE and OpenGL modules conflictingly set LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#20489] opened 2016-11-17 01:35 UTC
I've recently started getting this error message from `nixos-rebuild`
on my laptop:

> error: The unique option \`environment.sessionVariables.LD_LIBRARY_PATH' is defined multiple times, in \`/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/services/hardware/sane.nix' and \`/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/hardware/opengl.nix'.

The laptop runs NixOS version `17.03pre94694.fa4167c (Gorilla)`, according to `nixos-version`. My
desktop computer, which runs the same version of NixOS, does not
appear to be affected.

**Comment by vcunat** [comment] 2016-11-17 09:38
Duplicate of https://github.com/NixOS/nixpkgs/issues/20420

**Closed by vcunat** 2016-11-17 09:38 UTC
Labels: 6.topic: nixos

**Comment by 8573** [comment] 2016-11-18 06:36
My apologies, I seem to have quite forgotten to check for existing reports.
