### ISSUE TITLE
ZFS snapshot dir not accessible in non-root `neededForBoot` mounts

### ISSUE THREAD

**Issue by amarshall** [NixOS/nixpkgs#257505] opened 2023-09-26 20:59 UTC
### Describe the bug

ZFS provides a `<mountpoint>/.zfs/snapshot` directory that automounts snapshots for easy access. This does not work for non-root mounts that are `neededForBoot = true`.

### Steps to reproduce

```nix
{
  fileSystems = {
    "/" = { type = "zfs"; device = "rootpool/root"; };
    # Should `zfs set mountpoint=legacy rootpool/foo`
    "/foo" = { type = "zfs"; device = "rootpool/foo"; neededForBoot = true; };
  };
}
```

```
touch /foo/bar
zfs snapshot create rootpool/foo@test
ls /foo/.zfs/snapshot/test
```

### Expected behavior

Expected to find the snapshot files (e.g. `bar`) in `/foo/.zfs/snapshot/test`, but is empty.

### Additional context

- `/proc/spl/kstat/zfs/dbgmsg` contains lines like
   > zfs_ctldir.c:1109:zfsctl_snapshot_mount(): Unable to automount /.zfs/snapshot/test error=512

- This appears to be related to https://github.com/openzfs/zfs/issues/9461, however the dataset mounted at `/` does not exhibit this problem, only nested mounts.

- Removing `neededForBoot = true` resolves

- `mount -t zfs rootpool/foo -o remount` resolves.

### Notify maintainers

Unsure who…

### Metadata

Using recent nixos-unstable (e35dcc04a3853da485a396bdd332217d0ac9054f).

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.54, NixOS, 23.11 (Tapir), 23.11.20230922.e35dcc0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
```

**Comment by matthiasdotsh** [comment] 2024-03-26 19:33
Same here.

**Comment by Shawn8901** [comment] 2024-04-11 20:56
actually tried to double check on my system, that is using zfsutil for mounting and it seems that i can not directly reproduce with that, so either something else has been fixed or using zfsutil (so non legacy mountpoints) does not trigger the issue


```nix
   "/persist" = {
      device = "rpool/safe/persist";
      fsType = "zfs";
      options = [
        "zfsutil"
        "X-mount.mkdir"
      ];
      neededForBoot = true;
    };
```

```console
─ ls /persist/.zfs/snapshot
zrepl_20240409_202739_000  zrepl_20240410_201732_000  zrepl_20240411_195737_000
```

**Comment by Enzime** [comment] 2024-09-13 08:12
@matthiasdotsh Try with the dataset instead of the snapshot

```
sudo mount -t zfs rpool/encrypted/safe -o remount
```

I've managed to reproduce this issue with both the legacy stage1 as well as the systemd stage1

The easiest workaround for this issue is to run `mount -a -t zfs -o remount`

In my personal setup I just add it as an extra command to the `zfs-mount.service`:

```nix
systemd.services.zfs-mount = {
  serviceConfig = {
    ExecStart = [ "${lib.getExe' pkgs.util-linux "mount"} -a -t zfs -o remount" ];
  };
};
```

This works with both legacy (`mountpoint=legacy`) and native (`mountpoint=/...`) ZFS datasets that have `neededForBoot = true;`

cc @ElvishJerricco

**Comment by Enzime** [comment] 2024-09-15 08:31
I did some further testing and my previous setting led to my system being broken in some weird ways, the easiest workaround I have found is to set the `mountpoint` on all my datasets:

```
$ zfs set -u mountpoint=/ rpool/root
```

The `-u` flag means it'll update the `mountpoint` without unmounting/mounting anything which allows you to do it on an online system

Then instead I use this snippet:

```nix
systemd.services.zfs-mount = {
  serviceConfig = {
    ExecStart = [ "${config.boot.zfs.package}/sbin/zfs mount -a -o remount" ];
  };
};
```

All my ZFS datasets are marked as `neededForBoot`, so I'm not sure if this will cause issues if you also have non-legacy ZFS datasets that aren't needed for boot

**Comment by Shawn8901** [comment] 2024-10-03 06:31
> For what it’s worth, this _seems_ to not be a problem with `boot.initrd.systemd.enable = true` (I haven’t A/B tested it yet, but I recently changed and no longer have that problem—or a lot of other issues tbh.)

I am also using systems on all of my hosts, so that could be the reason that I wasn't able to reproduce it.

**Comment by Enzime** [comment] 2024-10-03 06:51
When I tested it I believe I was able to reproduce it with systemd stage1 and with the legacy stage1.

@Shawn8901 Did you check if the contents of the `/persist/.zfs/snapshot/zrepl_20240409_202739_000` is correct?

**Comment by Shawn8901** [comment] 2024-10-03 07:33
> When I tested it I believe I was able to reproduce it with systemd stage1 and with the legacy stage1.
> 
> @Shawn8901 Did you check if the contents of the `/persist/.zfs/snapshot/zrepl_20240409_202739_000` is correct?

Okay now I got it. Can repro. Hadn't read the inital content careful enough.

**Comment by iynaix** [comment] 2024-11-06 04:15
The remount workaround used to work for me on zfs 2.2, but sadly it no longer does on zfs 2.3rc2.

**Comment by n-elderbroom** [comment] 2024-11-27 18:41
This seems to be fixed for me in 2.3.0-rc3. The snapshot dirs all appeared empty for me previously, but work after updating. I didn't implement any of the workarounds for this bug, and made no config changes other than the update.

**Comment by Enzime** [comment] 2024-11-28 00:46
Looks like this PR should fix it https://github.com/openzfs/zfs/pull/16646

**Comment by Hyffer** [comment] 2024-12-05 05:28
Same here. now upgrade to zfs 2.3.0-rc3 and it works like a charm

**Comment by ElvishJerricco** [comment] 2024-12-09 03:07
I'll close this then. Feel free to re-open if ZFS 2.3 did not resolve the issue.

**Closed by ElvishJerricco** 2024-12-09 03:07 UTC
Labels: 0.kind: bug
