### ISSUE TITLE
running updatedb on the cli tries to write to /nix/store which is a read-only file system

### ISSUE THREAD

**Issue by mwasilew2** [NixOS/nixpkgs#24250] opened 2017-03-23 20:50 UTC
## Issue description

updatedb tries to write to /nix/store which is a read-only file system:
`/nix/store/95vfigaqdg8jg5bk961k1x06j86p5fh0-findutils-4.6.0/var/locatedb.n: Read-only file system`

this path comes from updatedb shell script: `/nix/store/95vfigaqdg8jg5bk961k1x06j86p5fh0-findutils-4.6.0/bin/updatedb`
which was modified in nix (this line is different in the gnu sources):
186: ${LOCATE_DB=/nix/store/95vfigaqdg8jg5bk961k1x06j86p5fh0-findutils-4.6.0/var/locatedb}

### Steps to reproduce

run as root or normal user in a login shell: `updatedb`

## Technical details

* System: VERSION="16.09.1836.067e66a (Flounder)"
* Nix version: nix-env (Nix) 1.11.7
* Nixpkgs version: "16.09.1836.067e66a"

**Comment by rlupton20** [comment] 2017-03-23 22:35
By the looks of it the derivations is doing a pretty standard build from a Makefile:

https://github.com/NixOS/nixpkgs/blob/067e66a9b324b335723224b74520be10cddf1499/pkgs/tools/misc/findutils/default.nix#L26

I think what this probably means is all the paths are indiscriminately rewritten to `$out` (i.e. in the nix-store). Need to confirm that suspicion, but that also raises the question of what it should write to, because it'll depend on which user is using it.

**Comment by rlupton20** [comment] 2017-03-23 22:46
Yep:

in `configure` in the gnu sources
```
1985:localstatedir='${prefix}/var'
```

and `locate/Makefile.am`
```
4:LOCATE_DB = $(localstatedir)/locatedb
```
`nix` will rewrite `prefix` to a path in the `nix` store.

So that's the cause of the `updatedb` script looking like it does - now to decide what we ought to do with it.

**Comment by rlupton20** [comment] 2017-03-25 17:37
This is fixed with this commit:

https://github.com/NixOS/nixpkgs/commit/417dbaf6a34552f0c7d959e5a63e6672ff85c4d7#diff-8e7fcdc2b11daa4074e040076c6163cf

Can be made to work on 16.09 by pulling `findutils` from `unstable`.

Not quite sure why my search pulled up an old version, but that's another matter!

**Comment by rlupton20** [comment] 2017-03-25 17:41
Tested and working. Suggest can be closed.

**Comment by gleber** [comment] 2017-12-17 07:17
This seem to have been fixed. Works for me on 18.03.git.4e7deb7. Please close.

**Comment by baracoder** [comment] 2019-04-29 09:45
Ping: This can be closed

**Closed** 2019-06-13 16:28 UTC
