### ISSUE TITLE
Shotcut 21.09.20 crash to desktop (NixOS 23.11)

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#290687] opened 2024-02-22 19:33 UTC
### Describe the bug
Shotcut Crash to desktop when adding media to timeline from preview.

### Steps To Reproduce
1. Right click any video file and open with shotcut
2. Media opens to preview panel within shotcut
3. Attempt to drag and drop to timeline; watch crash to desktop.

### Expected behavior
Shotcut should simply add the media to the timeline for project edits.

### Notify maintainers
@cillianderoiste 
@woffs 
@peti 
@turion 

### Metadata
`  - system: `"x86_64-linux"`
 - host os: `Linux 6.7.5, NixOS, 23.11 (Tapir), 23.11.4575.526d051b128b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
`

Terminal Debug Output from point of adding media.

```
[Debug  ] <MainWindow::open> "/mnt/Garage/THERAK/Projects/OBS_Studio/2024-02-22 12-43-21.mp4" 
[h264 @ 0x11d9000] Reinit context to 3440x1440, pix_fmt: yuv420p
[h264 @ 0x11d9000] Increasing reorder buffer to 1
[h264 @ 0x11d9000] Increasing reorder buffer to 2
[h264 @ 0x3842480] Reinit context to 3440x1440, pix_fmt: yuv420p
[h264 @ 0x3842480] Increasing reorder buffer to 1
[h264 @ 0x3842480] Increasing reorder buffer to 2
[h264 @ 0x5a18200] Reinit context to 3440x1440, pix_fmt: yuv420p
[h264 @ 0x5a18200] Increasing reorder buffer to 1
[h264 @ 0x5a18200] Increasing reorder buffer to 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[AVIOContext @ 0x1dba280] Statistics: 464489 bytes read, 3 seeks
[AVIOContext @ 0x58d4c00] Statistics: 458028 bytes read, 0 seeks
[AVIOContext @ 0x5b6d5c0] Statistics: 458028 bytes read, 0 seeks
[h264 @ 0x3844f80] Reinit context to 3440x1440, pix_fmt: yuv420p
[h264 @ 0x3844f80] Increasing reorder buffer to 1
[h264 @ 0x3844f80] Increasing reorder buffer to 2
[h264 @ 0x5b50640] Reinit context to 3440x1440, pix_fmt: yuv420p
[h264 @ 0x5b50640] Increasing reorder buffer to 1
[h264 @ 0x5b50640] Increasing reorder buffer to 2
[h264 @ 0x58e6f00] Reinit context to 3440x1440, pix_fmt: yuv420p
[h264 @ 0x58e6f00] Increasing reorder buffer to 1
[h264 @ 0x58e6f00] Increasing reorder buffer to 2
[AVIOContext @ 0x1dba280] Statistics: 464489 bytes read, 3 seeks
[Debug  ] <MLT> [producer avformat] "/mnt/Garage/THERAK/Projects/OBS_Studio/2024-02-22 12-43-21.mp4" checking VFR: pkt.duration 16
[h264 @ 0x3844f80] Reinit context to 3440x1440, pix_fmt: yuv420p
[Debug  ] <Mlt::Controller::setPreviewScale> 3440 x 1440 
[AVIOContext @ 0x5ae6400] Statistics: 458028 bytes read, 0 seeks
[AVIOContext @ 0x58e8300] Statistics: 987336 bytes read, 3 seeks
[h264 @ 0x3844f80] Reinit context to 3440x1440, pix_fmt: yuv420p
[h264 @ 0x3844f80] Increasing reorder buffer to 1
[h264 @ 0x3844f80] Increasing reorder buffer to 2
[h264 @ 0x5bed480] Reinit context to 3440x1440, pix_fmt: yuv420p
[h264 @ 0x5bed480] Increasing reorder buffer to 1
[h264 @ 0x5bed480] Increasing reorder buffer to 2
[h264 @ 0x82f3780] Reinit context to 3440x1440, pix_fmt: yuv420p
[h264 @ 0x82f3780] Increasing reorder buffer to 1
[h264 @ 0x82f3780] Increasing reorder buffer to 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[AVIOContext @ 0x1dba280] Statistics: 464489 bytes read, 3 seeks
[AVIOContext @ 0x6ed0540] Statistics: 458028 bytes read, 0 seeks
[AVIOContext @ 0x5a14540] Statistics: 458028 bytes read, 0 seeks
[h264 @ 0x63eed40] Reinit context to 3440x1440, pix_fmt: yuv420p
[h264 @ 0x63eed40] Increasing reorder buffer to 1
[h264 @ 0x63eed40] Increasing reorder buffer to 2
[h264 @ 0x58d5640] Reinit context to 3440x1440, pix_fmt: yuv420p
[h264 @ 0x58d5640] Increasing reorder buffer to 1
[h264 @ 0x58d5640] Increasing reorder buffer to 2
[h264 @ 0x5a1f040] Reinit context to 3440x1440, pix_fmt: yuv420p
[h264 @ 0x5a1f040] Increasing reorder buffer to 1
[h264 @ 0x5a1f040] Increasing reorder buffer to 2
[AVIOContext @ 0x5a166c0] Statistics: 464489 bytes read, 3 seeks
[Debug  ] <MainWindow::setAudioChannels> 2 
[Debug  ] <Mlt::Controller::setAudioChannels> 2 
[Debug  ] <MLT> [producer avformat-novalidate] "/mnt/Garage/THERAK/Projects/OBS_Studio/2024-02-22 12-43-21.mp4" checking VFR: pkt.duration 16
[h264 @ 0x63eed40] Reinit context to 3440x1440, pix_fmt: yuv420p
[Debug  ] <VideoVectorScopeWidget::profileChanged> 709 
[Info   ] <MainWindow::open> "/mnt/Garage/THERAK/Projects/OBS_Studio/2024-02-22 12-43-21.mp4" 
[Info   ] <MLT> [consumer sdl2_audio] Audio Opened: driver=pulseaudio channels=2 frequency=48000
[Debug  ] <Timeline::AddTrackCommand::redo> video 
[Debug  ] <Timeline::OverwriteCommand::redo> trackIndex 0 position 0 
[h264 @ 0x5ac36c0] Reinit context to 3440x1440, pix_fmt: yuv420p
[h264 @ 0x63eed40] Reinit context to 3440x1440, pix_fmt: yuv420p
[h264 @ 0x5ac36c0] Increasing reorder buffer to 1
[h264 @ 0x5ac36c0] Increasing reorder buffer to 2
[h264 @ 0x5ac56c0] Reinit context to 3440x1440, pix_fmt: yuv420p
[h264 @ 0x5ac56c0] Increasing reorder buffer to 1
[h264 @ 0x5ac56c0] Increasing reorder buffer to 2
[h264 @ 0x4840d00] Reinit context to 3440x1440, pix_fmt: yuv420p
[h264 @ 0x4840d00] Increasing reorder buffer to 1
[h264 @ 0x4840d00] Increasing reorder buffer to 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[AVIOContext @ 0x5be5d00] Statistics: 464489 bytes read, 3 seeks
[Debug  ] <Player::setIn> in -1 out 74256 
[Debug  ] <Player::setOut> in -1 out -1 
[h264 @ 0x7fe4d400cf80] Reinit context to 3440x1440, pix_fmt: yuv420p
[h264 @ 0x7fe37c009300] Reinit context to 3440x1440, pix_fmt: yuv420p
[Debug  ] <MLT> [chain avformat-novalidate] "/mnt/Garage/THERAK/Projects/OBS_Studio/2024-02-22 12-43-21.mp4" checking VFR: pkt.duration 16
[h264 @ 0x5ac36c0] Reinit context to 3440x1440, pix_fmt: yuv420p
[h264 @ 0x7fe4d400cf80] Increasing reorder buffer to 1
[h264 @ 0x7fe37c009300] Increasing reorder buffer to 1
[h264 @ 0x7fe4d400cf80] Increasing reorder buffer to 2
[h264 @ 0x7fe37c009300] Increasing reorder buffer to 2
[1]    31922 segmentation fault (core dumped)  shotcut
```
The video is in MKV format but labeled as mp4 as I'm no programmer and I thought that it was worth a shot to rename lol

**Comment by woffs** [comment] 2024-02-22 20:35
I can confirm this.

This bug does not occur in nixos-unstable (shotcut-24.01.31 or later), so I'd just run `nix run nixpkgs/nixos-unstable#shotcut` and be happy. Or wait for 24.05, or backport the shotcut updates to 23.11. I'm not sure what's the preferred policy in NixOS.

**Comment by Alpha-Obeisance** [comment] 2024-02-22 20:47
> I can confirm this.
> 
> This bug does not occur in nixos-unstable (shotcut-24.01.31 or later), so I'd just run `nix run nixpkgs/nixos-unstable#shotcut` and be happy. Or wait for 24.05, or backport the shotcut updates to 23.11. I'm not sure what's the preferred policy in NixOS.

I'm new to NixOs as of yesterday so I was unaware of this potential fix. Thanks for learning me something!

**Comment by eclairevoyant** [comment] 2024-02-22 22:00
> or backport the shotcut updates to 23.11. I'm not sure what's the preferred policy

the backporting guidelines are in [`CONTRIBUTING.md`](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#changes-acceptable-for-releases).

**Comment by woffs** [comment] 2024-03-03 16:44
> > or backport the shotcut updates to 23.11. I'm not sure what's the preferred policy
> 
> the backporting guidelines are in [`CONTRIBUTING.md`](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#changes-acceptable-for-releases).

This has to be done with care because of the dependencies to mlt and Qt.

**Comment by flexiondotorg** [comment] 2024-09-27 14:38
This was fixed via https://github.com/NixOS/nixpkgs/commit/66f8bb337ade76dbe6e0ddf2e62593046753ac90

**Closed by flexiondotorg** 2024-09-27 14:38 UTC
Labels: 0.kind: bug
