### ISSUE TITLE
Build failure: vinegar

### ISSUE THREAD

**Issue by U2C9727A4** [NixOS/nixpkgs#291211] opened 2024-02-24 18:38 UTC
### Steps To Reproduce

1. build vinegar

### Additional context

package vinegar fails to build because wine-wow dosent build which causes the entire thing to come crashing down

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.77, NixOS, 24.05 (Uakari), 24.05pre584422.a4d4fe8c5002`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
`
---

**Comment by kirillrdy** [comment] 2024-02-24 21:35
caused by https://github.com/NixOS/nixpkgs/issues/291206 being worked at https://github.com/NixOS/nixpkgs/pull/290761

**Comment by kirillrdy** [comment] 2024-02-25 05:44
i think there is an other issue with building `vinegar`, unrelated to icu

**Comment by kirillrdy** [comment] 2024-02-25 19:33
resolved by https://github.com/NixOS/nixpkgs/pull/289265

**Closed by kirillrdy** 2024-02-25 19:33 UTC
Labels: 0.kind: build failure

**Comment by U2C9727A4** [comment] 2024-02-26 06:54
Thanks lads!
