### ISSUE TITLE
How can the lua interpreter find packages if nix doesn't set LUA_(C)PATH ?

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#29474] opened 2017-09-16 15:37 UTC
## Issue description

Lua (in general) seems broken to me. Unlike python which generates an interpreter wrapper with a valid PYTHONHOME, LUA_PATH and LUA_CPATH are not accounted for in lua. Thus `nix-shell -p lua52Packages.cjson -p lua` wont find cjson for instance :/

I believe the buildLuaPackage function should be improved according to the python model and generate a wrapper with valid LUA_PATH/LUA_CPATH.

### Steps to reproduce
```
$ nix-shell -p lua52Packages.cjson -p lua
[nix-shell] $ lua -e "require 'cjson'"
```

will generate
```
lua: (command line):1: module 'cjson' not found:
	no field package.preload['cjson']
	no file '/usr/local/share/lua/5.3/cjson.lua'
	no file '/usr/local/share/lua/5.3/cjson/init.lua'
	no file '/usr/local/lib/lua/5.3/cjson.lua'
	no file '/usr/local/lib/lua/5.3/cjson/init.lua'
	no file './cjson.lua'
	no file './cjson/init.lua'
	no file '/usr/local/lib/lua/5.3/cjson.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './cjson.so'
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...) 18.03.git.365f631
* Nix version: (run `nix-env --version`) 1.11.14
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) nixpkgs-unstable

EDIT: Just found https://github.com/NixOS/nixpkgs/pull/25846/files and https://github.com/NixOS/nixpkgs/issues/25830 about this

**Comment by vcunat** [comment] 2017-09-16 20:44
Yes.  Duplicate of https://github.com/NixOS/nixpkgs/issues/25830, basically.

**Closed by vcunat** 2017-09-16 20:44 UTC
