### ISSUE TITLE
Package request: steamlink

### ISSUE THREAD

**Issue by spikespaz** [NixOS/nixpkgs#277905] opened 2023-12-31 12:24 UTC
**Project description**

Here is what I have tried so far:
```nix
# Updates: https://repo.steampowered.com/steamlink/>
{ stdenv, autoPatchelfHook, fetchzip, libsForQt5, xorg, libdrm, libva, libvdpau
, SDL2 }:
stdenv.mkDerivation (self: {
  pname = "steamlink";
  version = "1.3.9.258";

  dontWrapQtApps = true;

  # autoPatchelfIgnoreMissingDeps = [ "" ];

  nativeBuildInputs = [ autoPatchelfHook ];
  buildInputs = [
    libsForQt5.qtbase
    libsForQt5.qt5.qtsvg
    xorg.libX11
    libdrm
    libva
    libvdpau
    SDL2
  ];

  src = fetchzip {
    url =
      "https://repo.steampowered.com/steamlink/${self.version}/steamlink-${self.version}.tgz";
    hash = "sha256-HHP5YuspjKRVRwcuFMi7EYLuqpjI8RGqiTOUCxqcKgc=";
  };

  installPhase = ''
    mkdir -p $out/{bin,lib}
    cp $src/bin/* -t $out/bin
    cp $src/lib/* -t $out/lib
  '';
})

```

I am stuck on:
```
steamlink: symbol lookup error: steamlink: undefined symbol: _ZN7QWidget15controllerEventEP16QControllerEvent, version Qt_5
```
Tried with and without `pkgs.libsForQt5.callPackage` and adjusting lambda arguments accordingly.

**Metadata**

* homepage URL: https://repo.steampowered.com/steamlink/
* source URL: https://repo.steampowered.com/steamlink/
* license: custom "Steam Link License" for Flathub
* platforms: Linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Chaostheorie** [comment] 2023-12-31 23:33
Afaict, the error originates from steam link requiring a patched qtbase (5), for reference see the [flatpak manifest for steamlink](https://github.com/flathub/com.valvesoftware.SteamLink/blob/59a69bd5f358fc28be05b7dacb281576cd655779/com.valvesoftware.SteamLink.yml#L21-L58). They also appear to apply patches the other qt dependencies.

However the nixpkgs [`libsForQt5.qtbase`](https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/development/libraries/qt-5/modules/qtbase.nix) doesn't appear to include any of the relevant KDE patches. The patches are open source so we may be able to include them via an override if required.

**Comment by WolfangAukang** [comment] 2024-02-21 19:09
Duplicate of #77026

**Closed** 2024-02-21 19:09 UTC
Labels: 6.topic: steam, 0.kind: packaging request
