### ISSUE TITLE
vesktop: Unable to screenshare on Wayland

### ISSUE THREAD

**Issue by spikespaz** [NixOS/nixpkgs#277230] opened 2023-12-28 02:25 UTC
### Describe the bug

When I attempt to screen share using `xdg-desktop-portal-hyprland` (xdph), I see the following errors (in [Additional Context](#additional-context)) in the console (I started `vencorddesktop` from Bash). I have not tested on Sway.

### Steps To Reproduce

1. `$ vencorddesktop`
2. Join a call from DMs.
3. Try to share my screen, observe the output (in additional context).

### Expected behavior

Vesktop should be able to screen share just like ArmCord.

Developers exhibit polite and respectful behavior to new users.

### Screenshots

A screenshot would be useless, but Vesktop freezes and does not respond to input (or it might, but is very very slow).

### Additional context

```
[46538:1227/163949.950135:ERROR:shared_screencast_stream.cc(241)] PipeWire stream state error: no more input formats
[46538:1227/163949.950174:ERROR:shared_screencast_stream.cc(204)] PipeWire remote error: no more input formats
Warning: vkCreateInstance: Found no drivers!
Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
    at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:101)
    at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:493)
    at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:379)
    at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:301)
    at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:556)
```

Original issues:
<https://github.com/Vencord/Vesktop/issues/306>
<https://github.com/Vencord/Vesktop/issues/307>
~~<https://github.com/Vencord/Vesktop/issues/308>~~ <https://gist.github.com/spikespaz/9cd3dba9be2ef110c8ecbdafcfd0f4da>

### Notify maintainers

@getchoo @Scrumplex @vgskye @pluiedev

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.8, NixOS, 24.05 (Uakari), 24.05.20231222.6df37dc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by getchoo** [comment] 2023-12-29 00:24
i'm not able to reproduce this when running vesktop from e1fa12d4f6c6fe19ccb59cac54b5b3f25e160870 on nixpkgs-unstable; screen sharing and venmic's audio sharing work as expected. it seems to be an internal webrtc error judging by the file path `shared_screencast_stream.cc`, which can be found [here](https://webrtc.googlesource.com/src/+/refs/heads/main/modules/desktop_capture/linux/wayland/shared_screencast_stream.cc).

i'm thinking this might be an `xdg-desktop-portal-hyprland` issue, as i'm using `xdg-desktop-portal-gnome` and unaware of any issues with other portals. after looking at the upstream tracker, [there](https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/97) [are](https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/102) [a](https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/126) [good](https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/131) [number](https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/132) [of](https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/136) [issues](https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/137) relating to failed screenshares, so you might have better luck using a different portal implementation

**Comment by jh-devv** [comment] 2024-01-03 21:10
> i'm thinking this might be an `xdg-desktop-portal-hyprland` issue, as i'm using `xdg-desktop-portal-gnome` and unaware of any issues with other portals. after looking at the upstream tracker, [there](https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/97) [are](https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/102) [a](https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/126) [good](https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/131) [number](https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/132) [of](https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/136) [issues](https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/137) relating to failed screenshares, so you might have better luck using a different portal implementation

AFAIK the seems to be no other portal implementations for Hyprland at the moment?

**Comment by getchoo** [comment] 2024-01-04 20:10
i don't use hyprland myself, but according to the hyprland [wiki](https://wiki.hyprland.org/Useful-Utilities/Hyprland-desktop-portal/) their fork of wlroots implementation is not required. however considering this line, it might not be the best choice:

> You don’t need XDPH. Hyprland will work with XDPW, but XDPH has more features, like e.g. window sharing.

i would still recommend trying it though with full screen sharing (since i'm assuming it's only window sharing that's missing as that's not mentioned, correct me if i'm wrong), as that could help us confirm if this is a bug in hyprland's implementation rather than vesktop or electron

**Comment by RadovanSk** [comment] 2024-01-05 04:04
I also had this issue after 30th December and now I have finally fixed the issue at least for myself. If you are using hyprland flake just like me, then you most likely use ``xdg-desktop-portal-hyprland`` flake too so you have both on the latest version. 

However, if you are using ``programs.hyprland.enable = true;`` then there's the problem. It seems that this module enables the older version of ``xdg-desktop-portal-hyprland`` instead of the current one, unlike with hyprland.  That is my theory at least.

So what I have done is added this to my config ``programs.hyprland.portalPackage = inputs.xdg-desktop-portal-hyprland.packages."${pkgs.system}".xdg-desktop-portal-hyprland;`` and after rebuilding streaming started working. I believe adding the input into extraPortals should work too but it didn't for me for some reason. I might try it again but either way the streaming at least works now!

And yeah, I agree with you that the Vencord team could have been more respectful. My experience with them isn't goot either.

**Comment by getchoo** [comment] 2024-01-06 23:55
it looks like the fixes for screen sharing were included in [v1.3.0](https://github.com/hyprwm/xdg-desktop-portal-hyprland/releases/tag/v1.3.0), so this should be resolved in nixpkgs with https://github.com/NixOS/nixpkgs/pull/278784

**Comment by getchoo** [comment] 2024-01-18 21:41
https://github.com/NixOS/nixpkgs/pull/278784 has been merged and hit nixos-unstable; can anyone confirm this is no longer an issue in our version of the portal?

**Comment by spikespaz** [comment] 2024-01-19 04:38
I am currently re-working the portal implementation on NixOS for Hyprland, and will test once handling for the new load order mechanism has been finished.

**Comment by sioodmy** [comment] 2024-01-20 22:56
> #278784 has been merged and hit nixos-unstable; can anyone confirm this is no longer an issue in our version of the portal?

Can confirm. Screensharing works fine for me now

**Comment by getchoo** [comment] 2024-01-21 01:14
> Can confirm. Screensharing works fine for me now

thanks! guess it's time to close then. i would recommend forwarding further issues to `xdg-desktop-portal-hyprland` maintainers/upstream :)

**Closed by getchoo** 2024-01-21 01:14 UTC
Labels: 0.kind: bug
