### ISSUE TITLE
hplip broken in 17.03

### ISSUE THREAD

**Issue by mkocha2** [NixOS/nixpkgs#27968] opened 2017-08-05 18:33 UTC
## Issue description

Using http://nixos.org/channels/nixos-17.03/nixexprs.tar.xz:

```
/tmp/nix-build-hplip-3.16.5.drv-0/hplip-3.16.5/missing: line 52: autoconf: command not found
/tmp/nix-build-hplip-3.16.5.drv-0/hplip-3.16.5/missing: line 52: automake-1.11: command not found
WARNING: `autoconf' is missing on your system.  You should only need it if
         you modified `configure.in'.  You might want to install the
         `Autoconf' and `GNU m4' packages.  Grab them from any GNU
         archive site.
WARNING: `automake-1.11' is missing on your system.  You should only need it if
         you modified `Makefile.am', `acinclude.m4' or `configure.in'.
         You might want to install the `Automake' and `Perl' packages.
         Grab them from any GNU archive site.
```

**Comment by FRidh** [comment] 2017-08-05 21:10
seems like the autoreconfhook is missing

**Comment by FRidh** [comment] 2017-08-06 08:00
What command did you invoke that gave this error? I cannot reproduce a failing `hplip`.

**Comment by FRidh** [comment] 2017-08-10 08:15
@mkocha2 is this issue still occurring?

**Comment by mkocha2** [comment] 2017-08-12 21:21
@FRidh Yes, I still have the same problem. Try to add it to your system environment instead. 

Weird that you can't reproduce it.

**Comment by mkocha2** [comment] 2017-09-25 20:01
@FRidh `/run/current-system/sw/bin/nix-build -A hplip`
outputs : `error getting status of ‘/home/mkocha/default.nix'`.

**Comment by FRidh** [comment] 2017-09-26 07:26
@mkocha2 that is something with your `NIX_PATH` likely

**Comment by FRidh** [comment] 2017-09-26 07:27
You really need to give more information regarding your environment. I'm closing this for now.

**Closed by FRidh** 2017-09-26 07:27 UTC
