### ISSUE TITLE
lens: Always break .config/Lens permissions on exit

### ISSUE THREAD

**Issue by otavio** [NixOS/nixpkgs#135852] opened 2021-08-27 02:37 UTC
This is very annoying and I couldn't figure if this is a NixOS specific issue or an application bug.

Every time I close the app, the next time I open it I see the permission error. Attached is the screenshot.

### Screenshots
![image](https://user-images.githubusercontent.com/25278/131062515-7aa61418-6838-4703-8f3a-b715f3180f6f.png)

### Notify maintainers
@dbirks 
@oxzi 

### Metadata
```console
[user@system:~]$` nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.12, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(otavio): `"nixpkgs-21.11pre303435.077b2825cd3"`
 - channels(root): `"nixos-21.11pre311000.5bc8b980b91, home-manager, nixpkgs-unstable-21.11pre303315.16105403bdd"`
 - nixpkgs: `/home/otavio/.nix-defexpr/channels/nixpkgs`
```

**Comment by oxzi** [comment] 2021-08-28 08:10
Oddly enough, I get a similar message on startup, but not on exit. Since I've only had to use Lens sporadically for work so far, I haven't tried debugging it yet, but will look out for it soon.

**Comment by teto** [comment] 2021-08-28 21:50
duplicate of https://github.com/NixOS/nixpkgs/issues/123688

**Closed by teto** 2021-08-28 21:50 UTC
Labels: 0.kind: bug

**Comment by jan-kouba** [comment] 2021-12-23 16:35
This issue is still not fixed and I'm still seeing exactly the same error message as described in this issue, just with newer version.
It seems that Lens try to re-create extension directories on every start, but they create the extension directories without write permission. Then, on next start, when they try to delete files from the directories, it fails.

```
[node1:~/.config/Lens/extensions]$ ls -la
total 0
drwxr-xr-x 1 honza honza 240 23. pro 17.17 .
drwx------ 1 honza honza 992 23. pro 17.20 ..
dr-xr-xr-x 1 honza honza 128 23. pro 17.17 kube-object-event-status
dr-xr-xr-x 1 honza honza  50 23. pro 17.17 lenscloud-lens-extension
dr-xr-xr-x 1 honza honza 104 23. pro 17.17 license-menu-item
dr-xr-xr-x 1 honza honza 136 23. pro 17.17 metrics-cluster-feature
dr-xr-xr-x 1 honza honza 108 23. pro 17.17 node-menu
dr-xr-xr-x 1 honza honza 106 23. pro 17.17 pod-menu
dr-xr-xr-x 1 honza honza 102 23. pro 17.17 survey
dr-xr-xr-x 1 honza honza 108 23. pro 17.17 telemetry
```
