### ISSUE TITLE
Mindustry fails to start

### ISSUE THREAD

**Issue by 12Boti** [NixOS/nixpkgs#109798] opened 2021-01-18 16:28 UTC
**Describe the bug**
Trying to launch mindustry, I get this output:
```
[nix-shell:~]$ mindustry
sh: xdg-mime: command not found
[I] Initialized Discord rich presence.
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class arc.backend.sdl.jni.SDL
	at mindustry.desktop.DesktopLauncher.message(DesktopLauncher.java:316)
	at mindustry.desktop.DesktopLauncher.lambda$handleCrash$8(DesktopLauncher.java:177)
	at mindustry.desktop.DesktopLauncher.handleCrash(DesktopLauncher.java:177)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:45)
```

Additionally, after failing to launch, mindustry leaves a file named `libsdl-arc64.so` in the current directory.

**To Reproduce**
```
$ nix-shell --pure -p mindustry --run mindustry
```

**Expected behavior**
Mindustry should start without error and show the title screen.

**Notify maintainers**
@fgaz @petabyteboy

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.87, NixOS, 20.09.2538.0cfd08f4881 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(boti): `""`
 - channels(root): `"nixos-21.03pre263901.68398d2dd50"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Pacman99** [comment] 2021-01-18 17:44
I think the error is because you're running nix-shell with --pure. I don't why it would prevent mindustry from running, perhaps it needs access to a file which is forbidden in pure mode. But I got a similar error as you with --pure and it runs fine without it.

**Comment by 12Boti** [comment] 2021-01-18 19:04
Running it without --pure fixes the xdg-mime error, but the other error remains. And as I understand, it should work with --pure too, although it's not a big problem for me if it doesn't.

**Comment by Pacman99** [comment] 2021-01-18 19:24
Huh well then I guess I just can't reproduce then, it works fine for me on master and nixos-unstable. 
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.89, NixOS, 21.03.20210117.68398d2 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(pachums): `""`
 - nixpkgs: `/nix/store/qh1497vqx38yl6qcpdgf83jd45i96ahi-source`
```

**Comment by petabyteboy** [comment] 2021-01-18 19:34
What is SDL_VIDEODRIVER set to?

**Comment by 12Boti** [comment] 2021-01-19 06:03
SDL_VIDEODRIVER isn't set.

**Comment by petabyteboy** [comment] 2021-01-19 06:12
Are you on wayland or something?

**Comment by petabyteboy** [comment] 2021-01-19 06:26
Interesting observation:

Running `nix-shell --pure -p mindustry --run mindustry -I nixpkgs=channel:nixos-unstable` in my home directory will produce a `sprites` directory, a `libsdl-arc64.so` file and then crash. Running the same thing in any other directory I tested did not produce `sprites` or `libsd-arc64.so` and did not crash.

**Comment by 12Boti** [comment] 2021-01-19 06:30
Weird, for me it always creates a `libsdl-arc64.so`, but never a `sprites` dir. It doesn't matter what directory I run it in.

**Comment by petabyteboy** [comment] 2021-01-19 11:13
```
# doesn't work
nix-shell --pure -p mindustry -I nixpkgs=channel:nixos-unstable

# works
nix-shell --pure -p mindustry glew -I nixpkgs=channel:nixos-unstable

# now this works as well
nix-shell --pure -p mindustry -I nixpkgs=channel:nixos-unstable
```

**Comment by petabyteboy** [comment] 2021-01-19 11:40
@12Boti please try this:

```
rm -rf /tmp/arc ./*.so
nix-shell --pure -p mindustry --run mindustry -I nixpkgs=https://github.com/petabyteboy/nixpkgs/archive/feature/mindustry-fix.tar.gz

**Comment by 12Boti** [comment] 2021-01-19 12:34
For me, after
```nix-shell --pure -p mindustry glew -I nixpkgs=channel:nixos-unstable```
and running mindustry, it prints:
```
[nix-shell:~]$ mindustry
sh: xdg-mime: command not found
[I] Initialized Discord rich presence.
No protocol specified
arc.backend.sdl.SDLError: No available video device
	at arc.backend.sdl.SdlApplication.check(SdlApplication.java:180)
	at arc.backend.sdl.SdlApplication.init(SdlApplication.java:71)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:28)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
[E] Failed to save local crash report.: java.lang.NullPointerException: Cannot invoke "mindustry.mod.Mods.list()" because "mindustry.Vars.mods" is null
	at mindustry.net.CrashSender.createReport(CrashSender.java:29)
	at mindustry.net.CrashSender.send(CrashSender.java:87)
	at mindustry.desktop.DesktopLauncher.handleCrash(DesktopLauncher.java:187)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:45)

[I] Sending crash report.
java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1261)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1194)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1082)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1016)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1375)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1350)
	at arc.util.NetJavaImpl.lambda$http$0(NetJavaImpl.java:67)
	at arc.util.async.AsyncExecutor.lambda$submit$2(AsyncExecutor.java:31)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
Even sending the crash report fails (my internet works fine).

**Comment by 12Boti** [comment] 2021-01-19 12:43
I can confirm that it stays on this output even when I do
```nix-shell --pure -p mindustry -I nixpkgs=channel:nixos-unstable```
without `glew`.

**Comment by 12Boti** [comment] 2021-01-19 12:59
@petabyteboy That gave the same output too.

**Comment by 12Boti** [comment] 2021-01-19 13:20
After rebooting my computer, it works now... I have no idea why it didn't.

**Comment by Mindavi** [comment] 2021-03-15 19:01
I'm seeing this issue too. I had mindustry working, and now it stopped working again. The server just works, but the client seems to be quite finnicky.

**Comment by petabyteboy** [comment] 2021-03-15 20:52
Can you clear /tmp, change to a different working directory and try again? I noticed sometimes it seems to leave extracted assets or whatever and that can create issues on the next try.

**Comment by Mindavi** [comment] 2021-03-15 21:12
Doesn't seem to help. However, I do see that these files are generated in /tmp every time:

```
arc
b2da18653298600856021017078.tmp (partially random, but always starts with b2....)
hsperfdata_rick
jna-3500255
```

The b2da... file and the `libsdl-arc64.so` file which is dropped in the current working directory appear to be the same file (diff shows no differences).

<details><summary>This strace log may be onto something...</summary>

```
[pid 29340] <... openat resumed>)       = -1 ENOENT (No such file or directory)
[pid 29340] openat(AT_FDCWD, "/tmp/arc/b2da1865/libsdl-arc64.so", O_RDONLY|O_NONBLOCK <unfinished ...>
[pid 29340] <... openat resumed>)       = 10
[pid 29340] openat(AT_FDCWD, "/tmp/b2da18651644785283376836588.tmp", O_RDWR|O_CREAT|O_EXCL, 0666 <unfinished ...>
[pid 29340] <... openat resumed>)       = 10
[pid 29340] openat(AT_FDCWD, "/tmp/b2da18651644785283376836588.tmp", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 10
[pid 29340] openat(AT_FDCWD, "/tmp/b2da18651644785283376836588.tmp", O_RDONLY) = 10
[pid 29340] openat(AT_FDCWD, "/tmp/b2da18651644785283376836588.tmp", O_RDONLY|O_CLOEXEC) = 10
[pid 29340] openat(AT_FDCWD, "/nix/store/k58g6biziz8vpk6zw5n9bym2c6wxjrpd-SDL2-2.0.14/lib/libSDL2.so", O_RDONLY|O_CLOEXEC) = 10
[pid 29340] openat(AT_FDCWD, "/nix/store/lv1wa6wryjdln5d349n9ypkrzyijnfz4-glew-2.2.0/lib/libGLEW.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 29340] openat(AT_FDCWD, "/tmp/b2da18651644785283376836588.tmp", O_RDONLY|O_NONBLOCK) = 10
[pid 29340] openat(AT_FDCWD, "/home/rick/.arc/b2da1865/libsdl-arc64.so", O_RDONLY) = 10
[pid 29340] openat(AT_FDCWD, "/home/rick/.arc/b2da1865/libsdl-arc64.so", O_RDONLY) = 10
[pid 29340] openat(AT_FDCWD, "/home/rick/.arc/b2da1865/libsdl-arc64.so", O_RDONLY|O_CLOEXEC) = 10
[pid 29340] openat(AT_FDCWD, "/nix/store/k58g6biziz8vpk6zw5n9bym2c6wxjrpd-SDL2-2.0.14/lib/libSDL2.so", O_RDONLY|O_CLOEXEC) = 10
[pid 29340] openat(AT_FDCWD, "/nix/store/lv1wa6wryjdln5d349n9ypkrzyijnfz4-glew-2.2.0/lib/libGLEW.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 29340] openat(AT_FDCWD, "/home/rick/.arc/b2da1865/libsdl-arc64.so", O_RDONLY|O_NONBLOCK) = 10
[pid 29340] openat(AT_FDCWD, ".temp/b2da1865/libsdl-arc64.so", O_RDONLY) = 10
[pid 29340] openat(AT_FDCWD, "/home/rick/tmp/empty/.temp/b2da1865/libsdl-arc64.so", O_RDONLY) = 10
[pid 29340] openat(AT_FDCWD, "/home/rick/tmp/empty/.temp/b2da1865/libsdl-arc64.so", O_RDONLY|O_CLOEXEC) = 10
[pid 29340] openat(AT_FDCWD, "/nix/store/k58g6biziz8vpk6zw5n9bym2c6wxjrpd-SDL2-2.0.14/lib/libSDL2.so", O_RDONLY|O_CLOEXEC) = 10
[pid 29340] openat(AT_FDCWD, "/nix/store/lv1wa6wryjdln5d349n9ypkrzyijnfz4-glew-2.2.0/lib/libGLEW.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 29340] openat(AT_FDCWD, "/home/rick/tmp/empty/.temp/b2da1865/libsdl-arc64.so", O_RDONLY|O_NONBLOCK) = 10
[pid 29340] openat(AT_FDCWD, "libsdl-arc64.so", O_RDONLY) = 10
[pid 29340] openat(AT_FDCWD, "/home/rick/tmp/empty/libsdl-arc64.so", O_RDONLY) = 10
[pid 29340] openat(AT_FDCWD, "/home/rick/tmp/empty/libsdl-arc64.so", O_RDONLY|O_CLOEXEC) = 10
[pid 29340] openat(AT_FDCWD, "/nix/store/k58g6biziz8vpk6zw5n9bym2c6wxjrpd-SDL2-2.0.14/lib/libSDL2.so", O_RDONLY|O_CLOEXEC) = 10
[pid 29340] openat(AT_FDCWD, "/nix/store/lv1wa6wryjdln5d349n9ypkrzyijnfz4-glew-2.2.0/lib/libGLEW.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 29340] openat(AT_FDCWD, "/home/rick/tmp/empty/libsdl-arc64.so", O_RDONLY|O_NONBLOCK) = 10
```

</details>

**Comment by Mindavi** [comment] 2021-03-15 21:24
Ok, so running `nix-shell -p glew` helps. Mindustry starts again after that. That means that somehow it (glew) is not properly picked up as a dependency. Why is a big question to me.

**Comment by Mindavi** [comment] 2021-09-14 07:43
Still relevant, I guess glew should be added to the RPATH. Mindustry is now marked broken due to not being compatible with java 15 and not yet updated.

**Comment by fgaz** [comment] 2021-09-14 07:54
> and not yet updated

this is because new releases are still marked as pre-releases by the way

**Comment by Mindavi** [comment] 2021-11-18 22:30
I made a PR to unbreak mindustry, please have a look.

**Closed** 2021-11-25 19:11 UTC
Labels: 0.kind: bug
