### ISSUE TITLE
Autoconf not aviable in the build enviroment.

### ISSUE THREAD

**Issue by Miko4** [NixOS/nixpkgs#11098] opened 2015-11-17 16:25 UTC
the "autoconf" binary (and depencies such as sed) are not found in the $PATH ($PATH is set to the value "/path-not-set", it is in fact set to something) in the build environment, even tough  it is specified in buildInputs. After asking in the IRC I think the nix-expression is correct and this is a bug.

How to reproduce: create a new dir and change to it.
create a file builder.sh:
```sh
autoconf
libtoolize -qi
./configure
make
make install
```

create a file default.nix:
```
with import <nixpkgs> {};

stdenv.mkDerivation {
  name = "es-shell-0.9-beta1";
  builder = ./builder.sh;
  buildInputs = [ autoconf ];
  src = fetchFromGitHub {
        owner = "wryun";
        repo = "es-shell";
        rev = "2fc4b45521b87aab3e0d1786f604ae09892d78da";
        sha256 = "1vnd8p32n5yi5mi2w1kmycc0j3nrbsywprjr5m6rfzy2a5lamxz2";
  };
  meta = {
    description = "A shell with higher-order functions";
    license = "Public Domain";
  };
}
```

Run ```nix-build --show-trace default.nix```. Expected result: a directory called result with a binary. Actual result: 
```
These derivations will be built:
  /nix/store/xxcx9616ma4rg92xpiy24s22cnqr709i-es-shell-0.9-beta1.drv
building path(s) ‘/nix/store/bhhyvixn6jsca4ikqw12ypq57klz39nb-es-shell-0.9-beta1’
/nix/store/3af8kk0ixbb12ddzx5q8fdqsp9cw9a6g-builder.sh: line 1: autoconf: command not found
builder for ‘/nix/store/xxcx9616ma4rg92xpiy24s22cnqr709i-es-shell-0.9-beta1.drv’ failed with exit code 127
error: build of ‘/nix/store/xxcx9616ma4rg92xpiy24s22cnqr709i-es-shell-0.9-beta1.drv’ failed
```

**Comment by peti** [comment] 2015-11-17 16:28
If you specify the `builder` attribute, you replace the entire default builder with the script you provide, which means that all other attributes you've set have no longer any effect.

The proper way to do what you're trying to achieve is to set

    preConfigure = "autoconf && libtoolize -qi";

and to remove the `builder`.

**Comment by lethalman** [comment] 2015-11-17 16:30
You can also use `autoreconfHook` which does that automatically.

**Comment by lethalman** [comment] 2015-11-17 16:31
Closing, this is not a bug... sorry if you got said that on IRC.

**Closed by lethalman** 2015-11-17 16:31 UTC
