### ISSUE TITLE
NixOS installer leaves dangling gcroot pointers

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#83207] opened 2020-03-23 12:35 UTC
**Describe the bug**
On OS Images that we build I always have:
```
$ ls /nix/var/nix/gcroots
lrwxrwxrwx 1 root root   32 Apr 14  2019 profiles -> /build/root/nix/var/nix/profiles
```
and on installs that I have on my machines I always have
```$ ls /nix/var/nix/gcroots
lrwxrwxrwx 1 root root   32 Apr 14  2019 profiles -> /mnt/root/nix/var/nix/profiles
```

these are dangling pointers that are somehow created during installation and images building process. 

Furthermore, they seem redundant as recently an (undocumented) feature has been added to nix that makes `/nix/var/nix/profiles` a direct gcroot even without symlink. I have a feeling this bug has been introduced with this change

https://github.com/NixOS/nix/issues/3060

**To Reproduce**
1. Install NixOS or boot a NixOS cloud image

**Expected behavior**
No dangling pointers

**Screenshots**

**Additional context**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by 101100** [comment] 2020-04-23 22:06
@arianvp Can that dangling link be removed or should it be updated to a different target?

**Comment by arianvp** [comment] 2020-04-24 09:29
I have no clue! If you look at the related nix issue the profile is a direct GC root anyway.

**Comment by dudebout** [comment] 2020-05-23 13:56
From the facts that:
* despite the dangling symlink garbage collection works correctly
* [profiles are handled explicitly in the code](https://github.com/NixOS/nix/blob/master/src/libstore/gc.cc#L320)
I think that symlink should simply be removed, not repointed.

On a related note, there used to be a non-dangling symlink (/nix/var/nix/gcroots/profiles -> /nix/var/nix/profiles) installed by the nix installer as well. I am not sure if it is still being installed, but it is not needed either.

**Comment by arianvp** [comment] 2020-11-20 09:27
Not stale. still happens on 20.09

**Comment by sersorrel** [comment] 2021-08-06 23:46
this still happened for me on 21.05.

**Comment by alex-robbins** [comment] 2021-11-05 20:59
I think this is a duplicate of #73812 (although that one doesn't mention the link to `/build/root/nix/var/nix/profiles`).

**Closed** 2024-11-25 18:49 UTC
Labels: 0.kind: bug
