### ISSUE TITLE
Build failure: ddcci-driver

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#297312] opened 2024-03-20 01:02 UTC
### Steps To Reproduce

1. Add `config.boot.kernelPackages.ddcci-driver;` to your kernel modules on `linux_latest` - Specifically 6.8.1 at the moment.

### Build log

```
ddcci-driver> /build/source/ddcci/ddcci.c: In function 'ddcci_detect':
ddcci-driver> /build/source/ddcci/ddcci.c:1669:9: error: implicit declaration of function 'strlcpy'; did you mean 'strscpy'? [-Werror=implicit-function-declaration]
ddcci-driver>  1669 |         strlcpy(info->type, (outer_addr == DDCCI_DEFAULT_DEVICE_ADDR) ? "ddcci" : "ddcci-dependent", I2C_NAME_SIZE);
ddcci-driver>       |         ^~~~~~~
ddcci-driver>       |         strscpy
ddcci-driver> /build/source/ddcci/ddcci.c: At top level:
ddcci-driver> /build/source/ddcci/ddcci.c:1827:27: error: 'I2C_CLASS_DDC' undeclared here (not in a function); did you mean 'I2C_CLASS_SPD'?
ddcci-driver>  1827 |         .class          = I2C_CLASS_DDC,
ddcci-driver>       |                           ^~~~~~~~~~~~~
ddcci-driver>       |                           I2C_CLASS_SPD
ddcci-driver> cc1: some warnings being treated as errors
ddcci-driver> make[4]: *** [/nix/store/0rpkcbcrr8wx2rx889psyqbaw9wyi5x6-linux-6.8.1-dev/lib/modules/6.8.1/source/scripts/Makefile.build:243: /build/source/ddcci/ddcci.o] Error 1
ddcci-driver> make[3]: *** [/nix/store/0rpkcbcrr8wx2rx889psyqbaw9wyi5x6-linux-6.8.1-dev/lib/modules/6.8.1/source/Makefile:1921: /build/source/ddcci] Error 2
ddcci-driver> make[2]: *** [/nix/store/0rpkcbcrr8wx2rx889psyqbaw9wyi5x6-linux-6.8.1-dev/lib/modules/6.8.1/source/Makefile:240: __sub-make] Error 2
ddcci-driver> make[2]: Leaving directory '/nix/store/0rpkcbcrr8wx2rx889psyqbaw9wyi5x6-linux-6.8.1-dev/lib/modules/6.8.1/build'
ddcci-driver> make[1]: *** [Makefile:38: ddcci.ko] Error 2
ddcci-driver> make[1]: Leaving directory '/build/source/ddcci'
ddcci-driver> make: *** [Makefile:28: ddcci] Error 2

```

### Additional context

I'm trying to set up my desktop so I can control the backlights.

### Notify maintainers

As there is currently [none listed](https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/os-specific/linux/ddcci/default.nix#L39) I think what I'll do is the same as the [last time this happened](https://github.com/NixOS/nixpkgs/issues/245395) and @ the same people

@erdnaxe @ElvishJerricco @sweenu

(Sorry if you're the wrong people to ping!)

### Metadata

Please run `"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.1, NixOS, 23.11 (Tapir), 23.11.20240317.614b461`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/27rg15w6bjjh2hkbdqajhvqd7b02v5cb-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by sweenu** [comment] 2024-03-20 09:32
The relevant issue: https://gitlab.com/ddcci-driver-linux/ddcci-driver-linux/-/issues/39

**Comment by sweenu** [comment] 2024-03-20 10:10
https://gitlab.com/ddcci-driver-linux/ddcci-driver-linux/-/merge_requests/15/diffs
This should do. Build works. Still have to try the result.
You can try it with this overlay and tell me if you want:
```nix
final: prev: {
  ddcci-driver = prev.ddcci-driver.overrideAttrs (old: {
    patches = [
      (prev.fetchpatch {
        url = "https://gitlab.com/Sweenu/ddcci-driver-linux/-/commit/7f851f5fb8fbcd7b3a93aaedff90b27124e17a7e.patch";
        hash = "sha256-Y1ktYaJTd9DtT/mwDqtjt/YasW9cVm0wI43wsQhl7Bg=";
      })
    ];
  });
}
```

**Comment by Krutonium** [comment] 2024-03-20 16:14
Compiled and seems to work :+1:

**Comment by sweenu** [comment] 2024-03-20 16:17
Thanks for testing. Let's get this merged then: https://github.com/NixOS/nixpkgs/pull/297430 because it can take some time before it gets merged upstream.
@ElvishJerricco could you check the PR and merge if all's good for you?

**Comment by ElvishJerricco** [comment] 2024-03-25 21:57
It builds but it doesn't *work* for me on 6.7

**Comment by hughobrien** [comment] 2024-03-26 16:33
```❯ uname -a
Linux fw 6.8.1 #1-NixOS SMP PREEMPT_DYNAMIC Fri Mar 15 18:19:29 UTC 2024 x86_64 GNU/Linux
```
6.8.1 works at least.

**Comment by Mikilio** [comment] 2024-05-09 10:17
I applied the patch by @sweenu, and it compiles, however it doesn't really work as intended. I can most likely rule out, that my configuration has a problem because the same configuration worked on older kernel versions.

Unfortunately, it seems to not add devices to `/sys/bus/ddcci/devices` or `/sys/class/backlight` where they should be.
A manual workaround that I can confirm to work would be to call something this as root:
```cmd
echo ddcci 0x37 >| /sys/bus/i2c/devices/< Name of ic2-device to add >/new_device
```
This can probably be automated with a systemd-service executing at the right time.
My experience in working with kernel modules is low, so the only additional insights I can give are those boring Kernel logs:
```cmd
> journalctl -k | grep -E 'ddcci|i2c'
May 09 11:47:10 homestation kernel: ddcci: loading out-of-tree module taints kernel.
May 09 11:47:10 homestation kernel: i2c_dev: i2c /dev entries driver
```

**Comment by sweenu** [comment] 2024-05-09 13:07
Yes, you are right. It doesn't fix the underlying problem. The manual workaround is needed for now. The patch got merged upstream, but I don't know when we'll have a real fix. The maintainer's last message 6 days ago: https://gitlab.com/ddcci-driver-linux/ddcci-driver-linux/-/merge_requests/15#note_1890655664

**Comment by sweenu** [comment] 2024-05-09 13:14
Anyway, the build failure was fixed: https://github.com/NixOS/nixpkgs/pull/309948
No need for an open issue here, we have to watch upstream now.

**Closed by sweenu** 2024-05-09 13:14 UTC
Labels: 0.kind: build failure
