### ISSUE TITLE
Observations/issues on Sony Vaio Pro 13

### ISSUE THREAD

**Issue by arno01** [NixOS/nixpkgs#6304] opened 2015-02-11 13:15 UTC
Following are my observation while using NixOS on Sony Vaio Pro 13 for ~3 weeks, basically some things aren't working 'out-of-a-box', and it would be nice to fix it :)

I'm using XFCE4.

1) Android storage devices can be seen only when the following option was set in `/etc/nixos/configuration.nix`
  `services.udev.packages = [ pkgs.libmtp ];`

2) `/dev/mmcblk0` device (SD card) can be seen only after executing following command:
  `echo 1 | tee /sys/bus/pci/rescan`

3) So that a user in wheel group can mount storage and do other operations on disks and storage devices

```
  security.polkit.extraConfig =
  ''
    // so that a user in wheel group can mount storage and do other operations on disks and storage devices (pkaction)
    polkit.addRule(function(action, subject) {
        if (action.id.indexOf("org.freedesktop.udisks2.") == 0 &&
            subject.isInGroup("wheel")) {
            return polkit.Result.YES;
        }
    });
  '';
```

4) Sound over HDMI should Not be a primary on Sony Vaio Pro 13

```
[root@nixos:~]# lspci -nn |grep -i audio
00:03.0 Audio device [0403]: Intel Corporation Haswell-ULT HD Audio Controller [8086:0a0c] (rev 09)
00:1b.0 Audio device [0403]: Intel Corporation 8 Series HD Audio Controller [8086:9c20] (rev 04)
```

```
  boot.extraModprobeConfig = 
  ''
    ##
    # Fixing order of audio devices, based on: lspci -nn |grep -i audio
    ##
    #  PCH goes first
    options snd-hda-intel index=0 model=auto vid=8086 pid=0a0c
    #  HDMI goes second
    options snd-hda-intel index=1 model=auto vid=8086 pid=9c20
  '';
```

5) I tried different approach to use openbox (along with obconf, obmenu, fbpanel, ...) instead of XFCE, however I didn't even find "startx"... it's not a problem to write a script which would launch everything I need (X, openbox, ...), but it would be very nice to see that it could be done with just `desktopManager.openbox.enable = true;` :-)  // I don't have plenty of time to write all the commits on my own, however I do not want my observations to be lost in time & space :-) //

6) Backlight in console changes to minimum when switching from xorg to console
I've found couple of bugs opened for that, seems the issue lies in Xorg
https://bugzilla.kernel.org/show_bug.cgi?id=79541
https://bugs.freedesktop.org/show_bug.cgi?id=80987
It would be nice if someone will come up with a good solution so that we could merge it into master :-)

**Comment by iElectric** [comment] 2015-02-17 10:27
1) Could be fixed by having `programs.mtp.enable` option.

**Comment by andrewrk** [comment] 2015-08-22 17:35
Thank you so much for tip (1). I have been trying to get this to work for a long time now, and that did it.

**Comment by Profpatsch** [comment] 2016-07-23 14:25
(triage) status?

**Comment by arno01** [comment] 2016-07-24 14:13
@Profpatsch cannot report since I have not been using NixOS for quiet some time...

**Comment by Profpatsch** [comment] 2016-07-25 06:39
But it looks like it worked for @andrewrk, I guess we can close. cc @domenkozar

**Comment by domenkozar** [comment] 2016-07-25 07:05
Should be migrated to the hardware repo

**Comment by Profpatsch** [comment] 2016-07-25 12:55
@arno01 Can you add your findings to https://github.com/NixOS/nixos-hardware, in form of a deployable hardware config? I think it’s okay to add „soft“ miscellanea as markdown files as well.

**Comment by yegortimoshenko** [comment] 2018-06-10 23:03
Closing because this is likely to not be applicable anymore: I can't reproduce any of the issues on any of hardware available to me, either on Xfce or GNOME.

**Closed by yegortimoshenko** 2018-06-10 23:03 UTC
