### ISSUE TITLE
Build failure: xivauncher

### ISSUE THREAD

**Issue by ciferkey** [NixOS/nixpkgs#229476] opened 2023-05-02 13:39 UTC
### Steps To Reproduce

1. add xivlauncher to packages

### Build log

```
❯ sudo nixos-rebuild switch --show-trace
warning: Git tree '/etc/nixos' is dirty
building the system configuration...
warning: Git tree '/etc/nixos' is dirty
error: builder for '/nix/store/gxz4gmhc3l54547rjdv5b1pm87fy3gvb-XIVLauncher-1.0.3-dependencies-source.drv' failed with exit code 139;
       last 1 log lines:
       > /nix/store/a4v3az5zmqfc2x3gyjgds5azgdhf9b54-stdenv-linux/setup: line 1560:     7 Segmentation fault      (core dumped) nuget init "/nix/store/dm2j46r2v3d8hsprgkkafnxl7p2zqgxx-XIVLauncher-1.0.3-nuget-deps" "$out/lib"
       For full logs, run 'nix log /nix/store/gxz4gmhc3l54547rjdv5b1pm87fy3gvb-XIVLauncher-1.0.3-dependencies-source.drv'.
error: 1 dependencies of derivation '/nix/store/bl5iv53dbzmh7a076sba79318pjsxbxs-XIVLauncher-1.0.3-nuget-source.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rmf7z8yc2x0wq2rykav3d0sni0dymdxf-dotnet-configure-hook.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8hwm9dq8v6m0srkwkcmal6n7axcq2s71-XIVLauncher-1.0.3.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9ch1hpjip3aa9yyn3rkknz57iz1q6730-XIVLauncher-1.0.3-fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gpicn0bwp9dnxcyqhn6xwgx668vzv5gb-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vx7pxyxssy6h38h8fzpgf9gqy777d0vs-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vgq4v6kjx4q04imb6gf8mk3h8lzsi5xa-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ww0yg3wjkz3n8sdxvn76aggz01gnjlaz-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/njq682f328kzxnpjig0ki1k9138nq3sr-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/p9jynbrgsfcb86vb69p8md4ww817m5gd-nixos-system-nixos-23.05.20230430.da45bf6.drv' failed to build
```

Pinned nixpkgs version from `flake.lock`
```
    "nixpkgs": {
      "locked": {
        "lastModified": 1680213900,
        "narHash": "sha256-cIDr5WZIj3EkKyCgj/6j3HBH4Jj1W296z7HTcWj1aMA=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "e3652e0735fbec227f342712f180f4f21f0594f2",
        "type": "github"
      },
      "original": {
        "owner": "NixOS",
        "ref": "nixos-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
```

### Notify maintainers
@sersorrel @witchof0x20

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.0, NixOS, 23.05 (Stoat)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Let me know if there are any other details I can pull to help figure this out.

**Comment by sersorrel** [comment] 2023-05-02 19:38
I'm bisecting this; b04b334 (current `master` or so) is bad, da45bf6 (my current `nixos-version --hash`) is good, currently building cc5ea7e, but it's going to take a very long time. (if you have a tighter bound, like "what was your nixpkgs revision before it broke", that would be extremely useful!)

e3652e0735fbec227f342712f180f4f21f0594f2 appears good for me, which is unnerving... could you checkout that commit and try `nix-build -A xivlauncher` and see if it works? and also check b04b334?

**Comment by ciferkey** [comment] 2023-05-02 19:54
Thanks for checking!

The last time I did a `flake update` was [6 days ago](https://github.com/ciferkey/NixOSConfig/blob/master/flake.lock#L81).

It looks like the has was `sha256-2cKh4O6t1rQ8Ok+v16URynmb0rV7oZPEbXkU0owNLQs=`. I'm also just noticing I have two nixpkgs entries in my lock but I believe the 2nd is the right one. The first has a date of March 30th.

I'll go ahead and try to build those two commits.

**Comment by sersorrel** [comment] 2023-05-02 20:28
don't worry too much, fwiw, I found a faster way to test (`xivlauncher.passthru.nuget-source` has substantially fewer inputs but still exposes the build problem)

on cc5ea7e, mono fails to build:

```
error: builder for '/nix/store/8r8xam5f9znxc0nm1h8bl4y6hgkfw9qg-mono-6.12.0.182.drv' failed with exit code 2;
       last 20 log lines:
       > cd /build/mono-6.12.0.182/mcs && make --no-print-directory -s NO_DIR_CHECK=1 PROFILES='binary_reference_assemblies net_4_x xbuild_12 xbuild_14              ' CC='gcc' all-profiles
       > mkdir -p -- build/deps
       > /nix/store/5jlqnj59y7pdfl64fs1r2vbmrrrasgh9-bash-5.2-p15/bin/bash: line 1: mono: command not found
       > make[6]: *** [build/profiles/build.make:134: build/deps/basic-profile-check.exe] Error 127
       > *** The runtime 'mono' doesn't appear to be usable.
       > *** Trying the 'monolite-linux/1A5E0066-58DC-428A-B21C-0AD6CDAE2789' directory.
       > make[8]: *** [build/profiles/build.make:134: build/deps/basic-profile-check.exe] Segmentation fault (core dumped)
       > *** The contents of your 'monolite-linux/1A5E0066-58DC-428A-B21C-0AD6CDAE2789' directory may be out-of-date
       > *** You may want to try 'make get-monolite-latest'
       > make[8]: *** [build/profiles/build.make:117: do-profile-check-monolite] Error 1
       > make[7]: *** [build/profiles/build.make:93: do-profile-check] Error 2
       > make[6]: *** [build/profiles/build.make:129: do-profile-check-monolite] Error 2
       > make[5]: *** [build/profiles/build.make:93: do-profile-check] Error 2
       > make[4]: *** [Makefile:58: profile-do--build--all] Error 2
       > make[3]: *** [Makefile:54: profiles-do--all] Error 2
       > make[2]: *** [Makefile:709: all-mcs] Error 2
       > make[2]: Leaving directory '/build/mono-6.12.0.182/runtime'
       > make[1]: *** [Makefile:602: all-recursive] Error 1
       > make[1]: Leaving directory '/build/mono-6.12.0.182'
       > make: *** [Makefile:530: all] Error 2
       For full logs, run 'nix log /nix/store/8r8xam5f9znxc0nm1h8bl4y6hgkfw9qg-mono-6.12.0.182.drv'.
```

b2f87d7 is bad. 69db871 can't build mono. now building da2aa5a.

**Comment by ciferkey** [comment] 2023-05-02 20:29
The first commit fails for me: 

```console
nixpkgs (e3652e0) 
❯ nix-build -A xivlauncher
these 9 derivations will be built:
  /nix/store/041lz5rijcxnsjnv3jd59zf44i7347h1-dotnet-fixup-hook.drv
  /nix/store/vwhkq28l0h6zhdcj2fsn0gxms8wf853y-XIVLauncher-1.0.3-nuget-deps.drv
  /nix/store/saj8hkbz7k1mmzf4w52aq7x59nj3c57s-XIVLauncher-1.0.3-dependencies-source.drv
  /nix/store/bv8134w1ll052f7mkmd6cdas15k7qk11-XIVLauncher-1.0.3-nuget-source.drv
  /nix/store/ndhk9jlmzf8pr3cn6vln38i2r1aj1c4n-dotnet-check-hook.drv
  /nix/store/y16k8nxpxz8zzifg63wxq7fzzm1l49w7-source.drv
  /nix/store/y42b1xzkyqagn71d8fc0w2qvgbfwnm4q-xivlauncher.desktop.drv
  /nix/store/zgic8dqp80bg8p0k89g0dysmms7cjdb7-dotnet-configure-hook.drv
  /nix/store/qcga3ca7s5lp8h4pvyd7smqcmbvdglyx-XIVLauncher-1.0.3.drv
these 16 paths will be fetched (917.49 MiB download, 1352.57 MiB unpacked):
  /nix/store/0vnihcby4ird8dwbqcl4dxbp4zqcj7bv-make-shell-wrapper-hook
  /nix/store/1f105vz6hf6fgv7bc5m71iq8pg908r5s-copy-desktop-items-hook
  /nix/store/715n8aaghhlvw57nk5i48nh7a5pajdc6-gst-plugins-ugly-1.20.3-dev
  /nix/store/8i76xilfd3s4cbxv8nndgjcl7hfknn97-gstreamer-1.20.3-dev
  /nix/store/b1gqghikz5pa84gr3hwr48p8sxahyx1j-Nuget-6.3.1.1
  /nix/store/dpcyg8x7i9124f8nsw2gby4npr1xcibg-dotnet-build-hook
  /nix/store/dx80k13p25ry0mz31n4f2b5v9mhkbh23-gst-plugins-good-1.20.3-dev
  /nix/store/fy0w0hvncs4mnj2vjv2vc6nwla8rwnv3-gst-libav-1.20.3-dev
  /nix/store/kiccylqmqy9n8k05mvcv38bi1pgsg6a0-git-minimal-2.39.2
  /nix/store/kzsks85yjy6p48ybf62sxhnh6f5569c3-gst-plugins-base-1.20.3-dev
  /nix/store/ngnbbyr13mw5lg1ssvdkf6adbzd8081i-gst-plugins-bad-1.20.3-dev
  /nix/store/r04bnvsq19hpds9i7cdrlzcn2cbrs701-dotnet-sdk-6.0.407
  /nix/store/r1f63r7hny4qkqff6agz0fvyspik32iz-xml2-0.5
  /nix/store/xfn8j7h0x8yaa276nc6sdhkhni01dd4j-dotnet-sdk-6.0.407-source
  /nix/store/xs0lhfb70s6blif46bmib0qq77782m8x-die-hook
  /nix/store/z1dph2iy98s6ylnzqaw37yxlg87wv1x7-dotnet-install-hook
copying path '/nix/store/1f105vz6hf6fgv7bc5m71iq8pg908r5s-copy-desktop-items-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/xs0lhfb70s6blif46bmib0qq77782m8x-die-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/r04bnvsq19hpds9i7cdrlzcn2cbrs701-dotnet-sdk-6.0.407' from 'https://cache.nixos.org'...
copying path '/nix/store/fy0w0hvncs4mnj2vjv2vc6nwla8rwnv3-gst-libav-1.20.3-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/ngnbbyr13mw5lg1ssvdkf6adbzd8081i-gst-plugins-bad-1.20.3-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/dx80k13p25ry0mz31n4f2b5v9mhkbh23-gst-plugins-good-1.20.3-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/715n8aaghhlvw57nk5i48nh7a5pajdc6-gst-plugins-ugly-1.20.3-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/8i76xilfd3s4cbxv8nndgjcl7hfknn97-gstreamer-1.20.3-dev' from 'https://cache.nixos.org'...
building '/nix/store/y42b1xzkyqagn71d8fc0w2qvgbfwnm4q-xivlauncher.desktop.drv'...
copying path '/nix/store/xfn8j7h0x8yaa276nc6sdhkhni01dd4j-dotnet-sdk-6.0.407-source' from 'https://cache.nixos.org'...
building '/nix/store/041lz5rijcxnsjnv3jd59zf44i7347h1-dotnet-fixup-hook.drv'...
copying path '/nix/store/kiccylqmqy9n8k05mvcv38bi1pgsg6a0-git-minimal-2.39.2' from 'https://cache.nixos.org'...
copying path '/nix/store/b1gqghikz5pa84gr3hwr48p8sxahyx1j-Nuget-6.3.1.1' from 'https://cache.nixos.org'...
copying path '/nix/store/r1f63r7hny4qkqff6agz0fvyspik32iz-xml2-0.5' from 'https://cache.nixos.org'...
building '/nix/store/vwhkq28l0h6zhdcj2fsn0gxms8wf853y-XIVLauncher-1.0.3-nuget-deps.drv'...
copying path '/nix/store/kzsks85yjy6p48ybf62sxhnh6f5569c3-gst-plugins-base-1.20.3-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/0vnihcby4ird8dwbqcl4dxbp4zqcj7bv-make-shell-wrapper-hook' from 'https://cache.nixos.org'...
building '/nix/store/saj8hkbz7k1mmzf4w52aq7x59nj3c57s-XIVLauncher-1.0.3-dependencies-source.drv'...
building '/nix/store/y16k8nxpxz8zzifg63wxq7fzzm1l49w7-source.drv'...
exporting https://github.com/goatcorp/XIVLauncher.Core.git (rev 1.0.3) into /nix/store/k0kx0gzrcy1zwmia4b615a8ybwqxm9c2-source
/nix/store/z91202lpbgihd3n45ppwy9ax23m25h7b-stdenv-linux/setup: line 1560:     7 Segmentation fault      (core dumped) nuget init "/nix/store/083aryq202lc26m5gqq0g6j1cjr9zcjg-XIVLauncher-1.0.3-nuget-deps" "$out/lib"
error: builder for '/nix/store/saj8hkbz7k1mmzf4w52aq7x59nj3c57s-XIVLauncher-1.0.3-dependencies-source.drv' failed with exit code 139;
       last 1 log lines:
       > /nix/store/z91202lpbgihd3n45ppwy9ax23m25h7b-stdenv-linux/setup: line 1560:     7 Segmentation fault      (core dumped) nuget init "/nix/store/083aryq202lc26m5gqq0g6j1cjr9zcjg-XIVLauncher-1.0.3-nuget-deps" "$out/lib"
       For full logs, run 'nix log /nix/store/saj8hkbz7k1mmzf4w52aq7x59nj3c57s-XIVLauncher-1.0.3-dependencies-source.drv'.
error: 1 dependencies of derivation '/nix/store/bv8134w1ll052f7mkmd6cdas15k7qk11-XIVLauncher-1.0.3-nuget-source.drv' failed to build
error: 1 dependencies of derivation '/nix/store/zgic8dqp80bg8p0k89g0dysmms7cjdb7-dotnet-configure-hook.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qcga3ca7s5lp8h4pvyd7smqcmbvdglyx-XIVLauncher-1.0.3.drv' failed to build

```

and here is the second commit

```console
nixpkgs (b04b334) 
❯ nix-build -A xivlauncher
these 14 derivations will be built:
  /nix/store/nsc0vkayka73cqw123wzblp0r9h9b8zl-libva-minimal-1.8.3.drv
  /nix/store/36kxj2s6lj6wc29k5bcniwmgpp7agm68-libva-1.8.3.drv
  /nix/store/b6695g5f13gp1yfp6c16fyfdg4xadpz5-libIDL-0.8.14.drv
  /nix/store/kcs5flm6dram53rrrwa4sicc5zd36plp-ORBit2-2.14.19.drv
  /nix/store/vbzprkdxy12ac6dwzipz9a3rsrji32ah-gconf-3.2.6.drv
  /nix/store/0i8zbbg89n42mfc3ci7znnylmgdxfm3b-steam-run-usr-multi.drv
  /nix/store/p7mb65kxz97s88a8jg9iiqaq158hsc8v-steam-run-usr-target.drv
  /nix/store/5igdbw6vr0maqk94yjnxm22hwhqbnfyy-steam-run-fhs.drv
  /nix/store/bbpka1d6zxwl3jjs5nd867s5gdinzmmh-XIVLauncher-1.0.3-dependencies-source.drv
  /nix/store/kqkdd60szibkh56q7ivqlwsd5j5jr65q-XIVLauncher-1.0.3-nuget-source.drv
  /nix/store/qqlc5xvnrng9yfgay5rcrkinr5453g7j-dotnet-configure-hook.drv
  /nix/store/rv8yazhwjg9inpj9is3m0b2l35hwdksv-steam-run-bwrap.drv
  /nix/store/sf6lp9xsc2iaby1x45xakj9ai7wcv5bm-steam-run.drv
  /nix/store/jkhf2j03lign5xr29rmyzg7pnr52964n-XIVLauncher-1.0.3.drv
building '/nix/store/p7mb65kxz97s88a8jg9iiqaq158hsc8v-steam-run-usr-target.drv'...
building '/nix/store/bbpka1d6zxwl3jjs5nd867s5gdinzmmh-XIVLauncher-1.0.3-dependencies-source.drv'...
building '/nix/store/nsc0vkayka73cqw123wzblp0r9h9b8zl-libva-minimal-1.8.3.drv'...
building '/nix/store/b6695g5f13gp1yfp6c16fyfdg4xadpz5-libIDL-0.8.14.drv'...
warning: collision between `/nix/store/fykfx8rhs51lr4xp4irj7ygbyx5hd16b-glibc-multi-2.37-8-bin/bin/ldconfig' and `/nix/store/j2cb1f5f7gx98msfali98zqgg6dgk6qs-ldconfig/bin/ldconfig'
warning: collision between `/nix/store/wgxab548i7qrww1s4zwkhd1mi9ai91c1-glibc-multi-2.37-8/lib/locale/locale-archive' and `/nix/store/073qd3m5hbvrcvs3g6b5w14lwkxk3m9f-glibc-locales-2.37-8/lib/locale/locale-archive'
unpacking sources
unpacking source archive /nix/store/rnjfs2snrhqifr5z2337qzjh021x68sv-source
source root is source
unpacking sources
unpacking source archive /nix/store/ykxma695alyk47pywcjvsjl0s32ddiz1-libIDL-0.8.14.tar.bz2
patching sources
autoreconfPhase
/nix/store/2s0i8w7717g97wmj0r3rhdlhlwac0hj8-stdenv-linux/setup: line 1560:     7 Segmentation fault      (core dumped) nuget init "/nix/store/lks8smldv26i9macaj0v98bmw1d6ayjc-XIVLauncher-1.0.3-nuget-deps" "$out/lib"
error: builder for '/nix/store/bbpka1d6zxwl3jjs5nd867s5gdinzmmh-XIVLauncher-1.0.3-dependencies-source.drv' failed with exit code 139;
       last 1 log lines:
       > /nix/store/2s0i8w7717g97wmj0r3rhdlhlwac0hj8-stdenv-linux/setup: line 1560:     7 Segmentation fault      (core dumped) nuget init "/nix/store/lks8smldv26i9macaj0v98bmw1d6ayjc-XIVLauncher-1.0.3-nuget-deps" "$out/lib"
       For full logs, run 'nix log /nix/store/bbpka1d6zxwl3jjs5nd867s5gdinzmmh-XIVLauncher-1.0.3-dependencies-source.drv'.
error: 1 dependencies of derivation '/nix/store/kqkdd60szibkh56q7ivqlwsd5j5jr65q-XIVLauncher-1.0.3-nuget-source.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qqlc5xvnrng9yfgay5rcrkinr5453g7j-dotnet-configure-hook.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jkhf2j03lign5xr29rmyzg7pnr52964n-XIVLauncher-1.0.3.drv' failed to build
```

**Comment by sersorrel** [comment] 2023-05-02 23:40
ok. if I bisect between ec879c71aa4 (good, xivlauncher builds) and b04b334 (bad, xivlauncher does not build due to `nuget init` segfaulting), I see that ea86534 is good and 1e9a150 is bad, but trying to go further than that results in a big range where mono fails to build.

<details><summary>some rambling about that mono build failure</summary>

I tracked this down a bit: in e2d6e8e19d4, mono fails to build, but in `e2d6e8e19d4~` (ec879c71aa4), mono and xivlauncher build fine.

e2d6e8e19d4 is a merge commit, merging 8f57ffce3dc9a69ef168f5ba221c1602c0809e81 in; at 8f57ffce3dc9a69ef168f5ba221c1602c0809e81, mono fails to build, but at its parent 804dc945940ba1bb75994f49d6cd6397b94eb596, mono builds ok (but xivlauncher doesn't build due to the `nuget init` segfault).

the layout is something like this:

```
*   e2d6e8e19d4 (HEAD) Merge pull request #219400 from symphorien/debug_nvim Matthieu Coudron 2 weeks ago
|\
| * 8f57ffce3dc libuv: add debug output Guillaume Girol 9 weeks ago
| * 804dc945940 neovim-unwrapped: add debug output Guillaume Girol 9 weeks ago
* |   ec879c71aa4 Merge staging-next into staging github-actions[bot] 2 weeks ago
```

</details>

after much effort, I got the bisect to give me this:

```
The merge base ec879c71aa41065af101d1cce61966417e8d53c9 is bad.
This means the bug has been fixed between ec879c71aa41065af101d1cce61966417e8d53c9 and [54abe781c482f51ff4ff534ebaba77db5bd97442 5f93eceab193e255b87e06348b69148647c9d2d9 ea865346a07d965645b520478283d5f003c45227 ec879c71aa41065af101d1cce61966417e8d53c9].
```

which I interpreted as "you should run four new bisects between the merge base and those four other commits", but that turned up absolutely nothing at all. also, the last commit listed _is_ the merge base, which is [enormously confusing](https://stackoverflow.com/q/76159503/5951320).

I am way out of my depth at this point – I have no idea what could be causing the segfault during the xivlauncher build, and I don't understand why I'm unable to get git-bisect to give me anything useful. sorry to ping you, but @kuznero @mdarocha as dotnet maintainers do you have any idea what's happening here?

**Comment by ciferkey** [comment] 2023-05-03 19:14
> My current guess is that we're hitting a new kernel bug

I booted into a previous generation with and older kernel version and was able to build!

**Comment by Ultra980** [comment] 2023-05-06 05:47
> My current guess is that we're hitting a new kernel bug in 6.1

Would it work on 6.2?

**Comment by TheArcaneBrony** [comment] 2023-05-07 17:51
Having this same issue on kernel 6.3.1

**Comment by Ultra980** [comment] 2023-05-08 09:02
> Having this same issue on kernel 6.3.1

Same here after upgrading the kernel.

**Comment by witchof0x20** [comment] 2023-05-08 23:57
Chiming in to say I'm getting this issue with `Linux zero 6.1.26 #1-NixOS SMP PREEMPT_DYNAMIC Wed Apr 26 12:28:44 UTC 2023 x86_64 GNU/Linux`, so it might not be a kernel regression.

**Comment by witchof0x20** [comment] 2023-05-09 02:10
Rebooted into 6.1.25 and the build is working now. https://github.com/NixOS/nixpkgs/commit/3f8dd842b6c5b1aab5c71ad9feb7acb86cd8e15b is the exact point of the 6.1.26 upgrade, so I set my flake to use `d9487020e9c92ababbe6236ce7dd52304a7ba15f`

**Comment by witchof0x20** [comment] 2023-05-09 03:03
Working on the long process of bisecting between 6.1.25 and 6.1.26

**Comment by peterhoeg** [comment] 2023-05-09 03:37
We really should rename this issue as it isn't specific to xivauncher, but anything that uses `nuget`.

**Comment by witchof0x20** [comment] 2023-05-09 04:03
going through https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.1.y
manually building system using the kernel version, rebooting, and running `nix build .#xivlauncher` on master
Progress so far:
```
13 days	mm/mmap: regression fix for unmapped_area{_topdown}	Liam R. Howlett	1	-5/+43 BAD
13 days	mm: page_alloc: skip regions with hugetlbfs pages when allocating 1G pages	Mel Gorman	1	-0/+3
13 days	mm: kmsan: handle alloc failures in kmsan_vmap_pages_range_noflush()	Alexander Potapenko	3	-19/+34
13 days	mm: kmsan: handle alloc failures in kmsan_ioremap_page_range()	Alexander Potapenko	3	-19/+59
13 days	mm/huge_memory.c: warn with pr_warn_ratelimited instead of VM_WARN_ON_ONCE_FOLIO	Naoya Horiguchi	1	-2/+3
13 days	mm/khugepaged: check again on anon uffd-wp during isolation	Peter Xu	1	-0/+4
13 days	mm/userfaultfd: fix uffd-wp handling for THP migration entries	David Hildenbrand	1	-2/+12 GOOD
```

**Comment by witchof0x20** [comment] 2023-05-09 04:40
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-6.1.y&id=7e6631f782a16dcf528679478a9a6a8f71215d6f

Identified the specific regression. Going to ask around and see if I can report this, but anyone who actually knows what they're doing WRT the kernel mailing list, please pre-empt me on this.

**Comment by witchof0x20** [comment] 2023-05-09 04:46
https://lore.kernel.org/all/20230414185919.4175572-1-Liam.Howlett@oracle.com/T/#m00a0ac8a72bf2f26711b7f8cc56612a8ef62c3d0

Upstream seems to be aware

**Comment by sersorrel** [comment] 2023-05-09 18:59
that commit ([7e6631f782a16dcf528679478a9a6a8f71215d6f](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-6.1.y&id=7e6631f782a16dcf528679478a9a6a8f71215d6f)) reverts cleanly on 6.3.0 and appears to make xivlauncher build, using something like:

```nix
{
  boot.kernelPatches = [
    {
      name = "mmap-regression.patch";
      patch = pkgs.fetchpatch {
        url = "https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/patch/?id=7e6631f782a16dcf528679478a9a6a8f71215d6f";
        sha256 = "sha256-pwtXBd5D8DnHiw64fwamVB06TD0PDnCi+3NH4dgk0N0=";
        revert = true;
      };
    }
  ];
}
```

I don't know whether doing so has bad side-effects, though.

**Comment by witchof0x20** [comment] 2023-05-10 18:04
This is such a nice example of what NixOS can do.... That said, given that I'm not sure about removing this patch either (ostensibly it fixed another regression), personally I plan on waiting for upstream to fix it. In the meantime, we have plenty of ad-hoc mitigations, and #229851 looks promising as well.

**Comment by mdarocha** [comment] 2023-05-12 20:33
Since https://github.com/NixOS/nixpkgs/pull/229851 got merged, can we consider this issue resolved and close it? You can create a separate issue for the underlying kernel issue, but I think that's better tracked upstream?

**Comment by raphaelr** [comment] 2023-05-13 07:05
Yep

**Closed by raphaelr** 2023-05-13 07:05 UTC
Labels: 0.kind: build failure
