### ISSUE TITLE
Regression: macbook pro 8,2 backlight no longer works right on 17.03

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#23594] opened 2017-03-07 13:22 UTC
## Issue description
In 16.09, `xbacklight` would correctly modify the screen brightness. In 17.03, it does not report failure and changes are reflected in the output of `xbacklight get`, but the screen brightness is not affected.

### Steps to reproduce

`xbacklight +20`
`xbacklight -20`

## Technical details

* System: 17.03beta251.c0ecd31 (Gorilla)
* Nix version: 1.11.7
* Kernel version: 4.9.13
* Xorg version: 1.19.2
* Hardware version: macbookpro8,2 (Early 2011)

The sysfs control in `/sys/class/backlight/gmux_backlight` still works; there is also one at `/sys/class/backlight/intel_backlight`, which seems to be what xbacklight is now controlling and has no effect on the screen brightness.

**Comment by abbradar** [comment] 2017-03-10 13:21
See https://wiki.archlinux.org/index.php/backlight#xbacklight -- it seems you need to specify to Xorg what interface to use. Ideally the kernel won't just expose the broken interface; maybe this needs to be filled as a kernel bug?

**Comment by lheckemann** [comment] 2017-03-10 13:22
Awesome, thanks for pointing me there. I've asked on #intel-gfx on freenode a couple of times about this, but never received a response. I also don't have a clue about reporting kernel bugs, nor where bugs for such specific things as the intel graphics driver go...

**Comment by abbradar** [comment] 2017-03-10 13:27
I think you need [freedesktop.org's bug tracker](https://bugs.freedesktop.org/buglist.cgi?component=DRM%2FIntel&product=DRI&resolution=---). Just report your kernel, xorg and other versions, your hardware model and describe a bug. It should be enough given that it's not something hardly reproduced.

**Comment by abbradar** [comment] 2017-03-10 13:28
Closing because it's an upstream problem.

**Closed by abbradar** 2017-03-10 13:28 UTC

**Comment by lheckemann** [comment] 2017-03-13 12:30
https://bugs.freedesktop.org/show_bug.cgi?id=100148#c2

Seems like it's an X bug, not an intel graphics driver one — X should be preferring the "platform" backlight interface.
