### ISSUE TITLE
Nextcloud warns about being unable to write to its configuration directory.

### ISSUE THREAD

**Issue by bronson** [NixOS/nixpkgs#194951] opened 2022-10-07 17:46 UTC
### Describe the bug

Nextcloud warns about being unable to write to its configuration directory.

If you add `config_is_read_only = true` to config.php, that should make Nextcloud happy.

### Steps To Reproduce

1. Start Nextcloud 24.
2. Look at your log messages

### Expected behavior

One would expect Nextcloud to start without complaint.

### Screenshots

Example log:

```log
    Oct 06 18:50:37 jorne php[6416]: Cannot write into "config" directory!
    Oct 06 18:50:37 jorne php[6416]: This can usually be fixed by giving the web server write access to the config directory.
    Oct 06 18:50:37 jorne php[6416]: But, if you prefer to keep config.php file read only, set the option "config_is_read_only" to true in it.
    Oct 06 18:50:37 jorne php[6416]: See https://docs.nextcloud.com/server/24/go.php?to=admin-config
```

### Additional context

The link at the end of the log message tells more: https://docs.nextcloud.com/server/24/go.php?to=admin-config

### Notify maintainers

I don't see any maintainers in nextcloud.nix.

### Metadata

```console
[user@jorne:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.70, NixOS, 22.05 (Quokka), 22.05.3373.13cbe534ebe`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05.3373.13cbe534ebe"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
output here
```

**Comment by RaitoBezarius** [comment] 2022-10-29 14:09
paging maintainers @bachp @schneefux @globin @Ma27

**Comment by augustebaum** [comment] 2024-02-10 23:03
Also encountered this weird issue

**Comment by Ma27** [comment] 2024-06-25 22:42
Why is this file read-only in the first place?
To quote the docs linked:

> Furthermore, when updating Nextcloud it is required to make the configuration file writable again and to set this switch to false for the update process.

This is _not_ supported by the module, so upgrades will fail anyways.

**Comment by purefan** [comment] 2024-08-02 20:39
Getting this on a fresh install (no update)

**Comment by Ma27** [comment] 2024-08-02 21:53
If you report issues, please give a few more details so that I have a chance to reason about what's wrong in your case.

Why is `config.php` read-only? Or rather, which permissions does it have (and it's parent directories)
Anything interesting in the logs?
Is there anything special about your setup (in terms of filesystems or whatnot)?
And a config to reproduce that would help.

**Comment by Kidplayer666** [comment] 2024-12-20 21:42
> Getting this on a fresh install (no update)

Same here

**Comment by Ma27** [comment] 2024-12-21 15:21
So, this issue was severely lacking details and feedback already and messages stating "same here" without actually replying to the questions I asked doesn't help me to reproduce and subsequently fix it.

If somebody is actually interested in a fix, please open a new issue with an appropriate level of details and answering the questions I asked above.

Closing (and unsubscribing), since I don't see how this is getting anywhere.

**Closed by Ma27** 2024-12-21 15:21 UTC
Labels: 0.kind: bug
