### ISSUE TITLE
glXChooseFBConfig fails on non-NixOS

### ISSUE THREAD

**Issue by alex-fu27** [NixOS/nixpkgs#197695] opened 2022-10-25 08:52 UTC
### Describe the bug
Programs installed with Nix on non-NixOS (Arch in this case) say they are unable to get information about the display, and as far as I can tell it is because `glXChooseFBConfig` returns a null pointer.

### Steps To Reproduce
To reproduce the behavior, e.g.:
```console
$ nix-env -iA nixpkgs.prusa-slicer
$ which prusa-slicer
/home/alex/.nix-profile/bin/prusa-slicer
$ prusa-slicer
[2022-10-25 10:20:52.866820] [0x00007fdb022a5b40] [trace]   Initializing StaticPrintConfigs
Gtk-Message: 10:20:52.879: Failed to load module "xapp-gtk3-module"
Gtk-Message: 10:20:52.879: Failed to load module "canberra-gtk-module"
./src/unix/glx11.cpp(626): assert ""Assert failure"" failed in InitVisual(): Failed to get a XVisualInfo for the requested attributes.
```
(An Error message window actually opens, so gtk works!)

### Expected behavior
The error does not occur.

### Additional context
The error occurs in wxWidgets' `InitVisual()`, which calls `glXChooseFBConfig`.

This problem occured to me with other programs, too: I wanted to build a program ([LDSO](https://github.com/tum-vision/LDSO)) in a pure nix-shell. It depends on `pangolin` which is in nixpkgs, and the program crashes with 
```console
terminate called after throwing an instance of 'std::runtime_error'
  what():  Pangolin X11: Unable to retrieve framebuffer options
Aborted (core dumped)
```
after calling `glXChooseFBConfig`, but I thought I just didn't configure my nix-shell correctly and built in on my Arch...

### Notify maintainers
@primeos for libglvnd where the function comes from and maybe @vcunat for libGL?

### Metadata
```console
alex@alexnb ~> nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/q1drpnp5qifc38akiv4r169ll7cizisp-nix-info
copying path '/nix/store/q1drpnp5qifc38akiv4r169ll7cizisp-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.1-arch2-1, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixpkgs"`
 - channels(alex): `"home-manager"`
 - channels(mintech): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by vcunat** [comment] 2022-10-25 08:57
I don't have bandwidth to really help with GL on non-NixOS.  (neither now nor longer-term)  The whole situation isn't easy, as there are dependencies between the HW, kernel drivers and user-space (e.g. libGL).

**Comment by alex-fu27** [comment] 2022-10-25 09:40
This is indeed a workaround:

        Maybe https://github.com/guibou/nixGL would help.

_Originally posted by @NickCao in https://github.com/NixOS/nixpkgs/issues/197647#issuecomment-1290244699_

**Comment by Artturin** [comment] 2022-10-25 16:28
dupe of https://github.com/NixOS/nixpkgs/issues/82959

**Closed by Artturin** 2022-10-25 16:28 UTC
Labels: 0.kind: bug, 6.topic: non-nixos
