### ISSUE TITLE
Raspberry Pi Image building hangs on `cptofs`

### ISSUE THREAD

**Issue by RaitoBezarius** [NixOS/nixpkgs#76780] opened 2020-01-01 12:36 UTC
**Describe the bug**
When I try to produce an SD image for AArch64 with WiFi & SSH, I use the `nixpkgs/nixos/modules/installer/cd-dvd/sd-image-aarch64.nix`, it hangs forever at the ext4 image creation part, especially on `cptofs`.

I should mention I'm not on AArch64, so I use `qemu-aarch64-static`.
I see it's being used also for `cptofs` (unsure if it's right).

I have a fairly decent CPU: `Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz`.

It has been running for more than 11 hours according to htop. I tried to strace/gdb attach to the process, and it seems like stuck in a very long syscall with 100 % of CPU consumption.

Also, I'm using Arch Linux with Nix daemon to perform those builds, I added the extra-platform stuff.

**To Reproduce**
1. Try to create a SD card image under non-NixOS, non-AArch64 machine.
2. See if it completes.

**Expected behavior**
It should take a reasonable amount of time.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.91-1-lts, Arch Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixpkgs-20.03pre200828.1e7ddf233a5"`
 - channels(raito): `"nixpkgs-20.03pre206786.62ef779f2a5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module: nixpkgs/nixos/modules/installer/cd-dvd/sd-image-aarch64.nix
```

**Comment by matthewbauer** [comment] 2020-01-02 16:40
This looks very similar to https://github.com/NixOS/nixpkgs/issues/59867.

**Comment by matthewbauer** [comment] 2020-06-30 23:27
Duplicate of #59867

**Closed by matthewbauer** 2020-06-30 23:27 UTC
Labels: 0.kind: bug, 6.topic: non-nixos
