### ISSUE TITLE
inkscape segfauls on start

### ISSUE THREAD

**Issue by simendsjo** [NixOS/nixpkgs#57990] opened 2019-03-20 21:15 UTC
## Issue description
Segfaults on start

### Steps to reproduce

Run the binary

## Technical details

```
$ inkscape

(inkscape:12665): Gtk-WARNING **: 22:12:41.367: Unable to locate theme engine in module_path: "adwaita",

(inkscape:12665): Gtk-WARNING **: 22:12:41.370: Unable to locate theme engine in module_path: "adwaita",

Emergency save activated!
Emergency save completed. Inkscape will close now.
If you can reproduce this crash, please file a bug at www.inkscape.org
with a detailed description of the steps leading to the crash, so we can fix it.
[1]    12665 segmentation fault (core dumped)  inkscape
$ coredumpctl debug -1                                                                                                                           ✘ 139 
           PID: 12665 (inkscape)
           UID: 1000 (simendsjo)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Wed 2019-03-20 22:12:41 CET (7s ago)
  Command Line: inkscape
    Executable: /nix/store/hrw09b4byrjpcv3j26a8imrb3rwh8c3k-inkscape-0.92.4/bin/inkscape
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (simendsjo)
       Boot ID: e21182ae0bfa4991993059985830b605
    Machine ID: 364755d828e04978b38862dcb5fb81ec
      Hostname: simendsjo-laptop
       Storage: /var/lib/systemd/coredump/core.inkscape.1000.e21182ae0bfa4991993059985830b605.12665.1553116361000000.lz4
       Message: Process 12665 (inkscape) of user 1000 dumped core.

GNU gdb (GDB) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /nix/store/hrw09b4byrjpcv3j26a8imrb3rwh8c3k-inkscape-0.92.4/bin/inkscape...(no debugging symbols found)...done.
[New LWP 12665]
[New LWP 12666]
[New LWP 12667]
[New LWP 12670]
[New LWP 12669]
[New LWP 12671]
[New LWP 12672]
[New LWP 12668]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27/lib/libthread_db.so.1".
Core was generated by `inkscape'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f822aa93b24 in __memmove_avx_unaligned_erms () from /nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27/lib/libc.so.6
[Current thread is 1 (Thread 0x7f8226e13c00 (LWP 12665))]
warning: File "/nix/store/hlnxw4k6931bachvg5sv0cyaissimswb-gcc-7.4.0-lib/lib/libstdc++.so.6.0.24-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /nix/store/hlnxw4k6931bachvg5sv0cyaissimswb-gcc-7.4.0-lib/lib/libstdc++.so.6.0.24-gdb.py
line to your configuration file "/home/simendsjo/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/simendsjo/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
(gdb) bt
#0  0x00007f822aa93b24 in __memmove_avx_unaligned_erms () from /nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27/lib/libc.so.6
#1  0x00007f822c3df6c5 in png_combine_row () from /nix/store/dyaz53db6gwi169w9a2vybvranlllvk3-libpng-apng-1.6.36/lib/libpng16.so.16
#2  0x00007f822c3d287f in png_read_row () from /nix/store/dyaz53db6gwi169w9a2vybvranlllvk3-libpng-apng-1.6.36/lib/libpng16.so.16
#3  0x00007f822c3d43fa in png_read_image () from /nix/store/dyaz53db6gwi169w9a2vybvranlllvk3-libpng-apng-1.6.36/lib/libpng16.so.16
#4  0x00007f821acc60ee in gdk_pixbuf.png_image_load ()
   from /nix/store/sny8s9zg6xlwgli1653n2xqwsfvamid6-gdk-pixbuf-2.36.12/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so
#5  0x00007f822b4e2f19 in gdk_pixbuf_new_from_file () from /nix/store/pcsmi0gs7mlpnh55qg7qxqk7sr5zziwd-gdk-pixbuf-2.38.0/lib/libgdk_pixbuf-2.0.so.0
#6  0x00007f821bc59119 in pixbuf_cache_value_new () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/gtk-2.0/2.10.0/engines/libpixmap.so
#7  0x00007f822cd0e2b5 in g_cache_insert () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libglib-2.0.so.0
#8  0x00007f821bc59e78 in theme_pixbuf_get_pixbuf () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/gtk-2.0/2.10.0/engines/libpixmap.so
#9  0x00007f821bc59f42 in theme_pixbuf_render () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/gtk-2.0/2.10.0/engines/libpixmap.so
#10 0x00007f821bc56cb8 in draw_simple_image.isra () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/gtk-2.0/2.10.0/engines/libpixmap.so
#11 0x00007f821bc57daa in draw_box () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/gtk-2.0/2.10.0/engines/libpixmap.so
#12 0x00007f822bb5b817 in _gtk_button_paint () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0
#13 0x00007f822bb5b8e9 in gtk_button_expose () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0
#14 0x00007f822bc013ab in _gtk_marshal_BOOLEAN__BOXED () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0
#15 0x00007f822d224841 in g_closure_invoke () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libgobject-2.0.so.0
#16 0x00007f822d237b60 in signal_emit_unlocked_R () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libgobject-2.0.so.0
#17 0x00007f822d241c04 in g_signal_emit_valist () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libgobject-2.0.so.0
#18 0x00007f822d24289f in g_signal_emit () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libgobject-2.0.so.0
#19 0x00007f822bd17f9c in gtk_widget_event_internal () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0
#20 0x00007f822bb875ae in gtk_container_propagate_expose () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0
#21 0x00007f822bb52593 in gtk_box_forall () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0
#22 0x00007f822bb8602e in gtk_container_expose () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0
#23 0x00007f822bc013ab in _gtk_marshal_BOOLEAN__BOXED () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0
#24 0x00007f822d224841 in g_closure_invoke () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libgobject-2.0.so.0
#25 0x00007f822d237b60 in signal_emit_unlocked_R () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libgobject-2.0.so.0
#26 0x00007f822d241c04 in g_signal_emit_valist () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libgobject-2.0.so.0
#27 0x00007f822d24289f in g_signal_emit () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libgobject-2.0.so.0
#28 0x00007f822bd17f9c in gtk_widget_event_internal () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0
#29 0x00007f822bb875ae in gtk_container_propagate_expose () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0
#30 0x00007f822bb52593 in gtk_box_forall () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0
#31 0x00007f822bb8602e in gtk_container_expose () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--c
#32 0x00007f822bc013ab in _gtk_marshal_BOOLEAN__BOXED () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0
#33 0x00007f822d224841 in g_closure_invoke () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libgobject-2.0.so.0
#34 0x00007f822d237b60 in signal_emit_unlocked_R () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libgobject-2.0.so.0
#35 0x00007f822d241c04 in g_signal_emit_valist () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libgobject-2.0.so.0
#36 0x00007f822d24289f in g_signal_emit () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libgobject-2.0.so.0
#37 0x00007f822bd17f9c in gtk_widget_event_internal () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0
#38 0x00007f822bb875ae in gtk_container_propagate_expose () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0
#39 0x00007f822bb8602e in gtk_container_expose () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0
#40 0x00007f822bc013ab in _gtk_marshal_BOOLEAN__BOXED () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0
#41 0x00007f822d22492d in g_closure_invoke () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libgobject-2.0.so.0
#42 0x00007f822d237b60 in signal_emit_unlocked_R () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libgobject-2.0.so.0
#43 0x00007f822d241c04 in g_signal_emit_valist () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libgobject-2.0.so.0
#44 0x00007f822d24289f in g_signal_emit () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libgobject-2.0.so.0
#45 0x00007f822bd17f9c in gtk_widget_event_internal () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0
#46 0x00007f822bbffc88 in gtk_main_do_event () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0
#47 0x00007f822b74376f in _gdk_window_process_updates_recurse () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgdk-x11-2.0.so.0
#48 0x00007f822b7401f3 in gdk_window_process_updates_internal () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgdk-x11-2.0.so.0
#49 0x00007f822b740b80 in gdk_window_process_all_updates () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgdk-x11-2.0.so.0
#50 0x00007f822bb85d01 in gtk_container_idle_sizer () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0
#51 0x00007f822b71f98c in gdk_threads_dispatch () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgdk-x11-2.0.so.0
#52 0x00007f822cd4bf65 in g_main_context_dispatch () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libglib-2.0.so.0
#53 0x00007f822cd4c3d0 in g_main_context_iterate.isra () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libglib-2.0.so.0
#54 0x00007f822cd4c8e2 in g_main_loop_run () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libglib-2.0.so.0
#55 0x00007f822bb88ed6 in gtk_dialog_run () from /nix/store/jja4b3lmiakblkanchy23xl6kcv629i7-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0
#56 0x00007f822e1085b5 in Inkscape::Application::crash_handler(int) () from /nix/store/hrw09b4byrjpcv3j26a8imrb3rwh8c3k-inkscape-0.92.4/bin/../lib/inkscape/libinkscape_base.so
#57 <signal handler called>
#58 0x00007f822aa93bb2 in __memmove_avx_unaligned_erms () from /nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27/lib/libc.so.6
#59 0x00007f822c3df6c5 in png_combine_row () from /nix/store/dyaz53db6gwi169w9a2vybvranlllvk3-libpng-apng-1.6.36/lib/libpng16.so.16
#60 0x00007f822c3d287f in png_read_row () from /nix/store/dyaz53db6gwi169w9a2vybvranlllvk3-libpng-apng-1.6.36/lib/libpng16.so.16
#61 0x00007f822c3d43fa in png_read_image () from /nix/store/dyaz53db6gwi169w9a2vybvranlllvk3-libpng-apng-1.6.36/lib/libpng16.so.16
#62 0x00007f821acc60ee in gdk_pixbuf.png_image_load () from /nix/store/sny8s9zg6xlwgli1653n2xqwsfvamid6-gdk-pixbuf-2.36.12/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so
#63 0x00007f822b4e2f19 in gdk_pixbuf_new_from_file () from /nix/store/pcsmi0gs7mlpnh55qg7qxqk7sr5zziwd-gdk-pixbuf-2.38.0/lib/libgdk_pixbuf-2.0.so.0
#64 0x00007f822ddbe322 in Inkscape::UI::Dialogs::ColorItem::_regenPreview(_EekPreview*) () from /nix/store/hrw09b4byrjpcv3j26a8imrb3rwh8c3k-inkscape-0.92.4/bin/../lib/inkscape/libinkscape_base.so
#65 0x00007f822ddbf036 in Inkscape::UI::Dialogs::ColorItem::getPreview(Inkscape::UI::PreviewStyle, Inkscape::UI::ViewType, PreviewSize, unsigned int, unsigned int) () from /nix/store/hrw09b4byrjpcv3j26a8imrb3rwh8c3k-inkscape-0.92.4/bin/../lib/inkscape/libinkscape_base.so
#66 0x00007f822dd0056e in Inkscape::UI::PreviewHolder::rebuildUI() () from /nix/store/hrw09b4byrjpcv3j26a8imrb3rwh8c3k-inkscape-0.92.4/bin/../lib/inkscape/libinkscape_base.so
#67 0x00007f822deffa2e in Inkscape::UI::Dialogs::SwatchesPanel::_rebuild() () from /nix/store/hrw09b4byrjpcv3j26a8imrb3rwh8c3k-inkscape-0.92.4/bin/../lib/inkscape/libinkscape_base.so
#68 0x00007f822df07211 in Inkscape::UI::Dialogs::SwatchesPanel::SwatchesPanel(char const*) () from /nix/store/hrw09b4byrjpcv3j26a8imrb3rwh8c3k-inkscape-0.92.4/bin/../lib/inkscape/libinkscape_base.so
#69 0x00007f822e025862 in SPDesktopWidget::init(SPDesktopWidget*) () from /nix/store/hrw09b4byrjpcv3j26a8imrb3rwh8c3k-inkscape-0.92.4/bin/../lib/inkscape/libinkscape_base.so
#70 0x00007f822d24b955 in g_type_create_instance () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libgobject-2.0.so.0
#71 0x00007f822d229fb0 in g_object_new_internal () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libgobject-2.0.so.0
#72 0x00007f822d22c2c5 in g_object_new_with_properties () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libgobject-2.0.so.0
#73 0x00007f822d22ccd1 in g_object_new () from /nix/store/5fcij33f8q8yk127kvl45ydi9z7gmggj-glib-2.58.2/lib/libgobject-2.0.so.0
#74 0x00007f822e025180 in SPDesktopWidget::createInstance(SPNamedView*) () from /nix/store/hrw09b4byrjpcv3j26a8imrb3rwh8c3k-inkscape-0.92.4/bin/../lib/inkscape/libinkscape_base.so
#75 0x00007f822e0256a6 in sp_desktop_widget_new(SPNamedView*) () from /nix/store/hrw09b4byrjpcv3j26a8imrb3rwh8c3k-inkscape-0.92.4/bin/../lib/inkscape/libinkscape_base.so
#76 0x00007f822e0e056a in sp_file_new(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /nix/store/hrw09b4byrjpcv3j26a8imrb3rwh8c3k-inkscape-0.92.4/bin/../lib/inkscape/libinkscape_base.so
#77 0x00007f822e0e0992 in sp_file_new_default() () from /nix/store/hrw09b4byrjpcv3j26a8imrb3rwh8c3k-inkscape-0.92.4/bin/../lib/inkscape/libinkscape_base.so
#78 0x000000000040bb15 in sp_main_gui(int, char const**) ()
#79 0x00007f822a963b8e in __libc_start_main () from /nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27/lib/libc.so.6
#80 0x000000000040716a in _start ()
(gdb) 
```

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.105, NixOS, 18.09.2366.45456fecc74 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2366.45456fecc74"`
 - channels(simendsjo): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment] 2019-03-21 12:07
Looks like a duplicate of https://github.com/NixOS/nixpkgs/issues/54278. You need to make sure Inkscape uses the same gkd-pixbuf as the impure loaders from your environment.

**Closed by jtojnar** 2019-03-21 12:07 UTC
