### ISSUE TITLE
Tor Browser giving fatal allocator error

### ISSUE THREAD

**Issue by iloveyoulucie** [NixOS/nixpkgs#168887] opened 2022-04-16 07:12 UTC
### Describe the bug

Tor Browser inconsistently fails to launch on NixOS unstable.

### Steps To Reproduce
1. Add tor-browser-bundle-bin to systemPackages
2. Rebuild the system
3. Run tor-browser

### Expected behavior
I expected Tor to run

### Additional context

```fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
user@host ~> tor-browser                                                                            
fatal allocator error: invalid uninitialized allocator usage
Redirecting call to abort() to mozalloc_abort

fish: Job 1, 'tor-browser' terminated by signal SIGSEGV (Address boundary error)
user@host ~ [SIGSEGV]> 
```

I am running NixOS unstable, and using Wayland (Sway) in case it is relevant

### Notify maintainers
@offlinehacker 
@matejc 
@thoughtpolice 
@hax404 
@KarlJoad 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
leo@coriander ~> nix-shell -p nix-info --run "nix-info -m"                                              
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.32, NixOS, 22.05 (Quokka), 22.05pre365028.710fed5a248`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"home-manager, nixos"`
 - channels(leo): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

leo@coriander ~> 
```

**Comment by Artturin** [comment] 2022-04-16 21:59
Dupe of https://github.com/NixOS/nixpkgs/issues/146401

**Closed by Artturin** 2022-04-16 21:59 UTC
Labels: 0.kind: bug
