### ISSUE TITLE
VirtualBox network service is broken?

### ISSUE THREAD

**Issue by chekoopa** [NixOS/nixpkgs#39609] opened 2018-04-27 16:08 UTC
## Issue description

One day I've booted non-reconfigured NixOS, and it suddenly became broken. 1 and a half minute of plain wait for nothing, but fortunately networking is still functional (when set to "Bridged Adapter" mode). 
Yes, it worked before, no refreshes or upgrades were made.

``` апр 27 19:59:38 ckopo-nix systemd[1]: sys-subsystem-net-devices-vboxnet0.device: Job sys-subsystem-net-devices-vboxnet0.device/start timed out.
апр 27 19:59:38 ckopo-nix systemd[1]: Timed out waiting for device sys-subsystem-net-devices-vboxnet0.device.
апр 27 19:59:38 ckopo-nix systemd[1]: Dependency failed for Link configuration of vboxnet0.
апр 27 19:59:38 ckopo-nix systemd[1]: network-link-vboxnet0.service: Job network-link-vboxnet0.service/start failed with result 'dependency'.
апр 27 19:59:38 ckopo-nix systemd[1]: Dependency failed for Address configuration of vboxnet0.
апр 27 19:59:38 ckopo-nix systemd[1]: network-addresses-vboxnet0.service: Job network-addresses-vboxnet0.service/start failed with result 'dependency'.
апр 27 19:59:38 ckopo-nix systemd[1]: sys-subsystem-net-devices-vboxnet0.device: Job sys-subsystem-net-devices-vboxnet0.device/start failed with result 'timeout'.
```

UDP: Also, got systemd logs, hope it would help.

```[user@ckopo-nix:~]$ systemctl status vboxnet0.service
● vboxnet0.service - VirtualBox vboxnet0 Interface
   Loaded: loaded (/nix/store/1z3mi0m860bghxs8axz9pw6if2n8ss7a-unit-vboxnet0.service/vboxnet0.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2018-04-28 23:23:52 +08; 2min 36s ago
  Process: 908 ExecStopPost=/nix/store/69sdla5sqzhc0p05pq661zdsmmzllxcq-unit-script/bin/vboxnet0-post-stop (code=exited, status=1/FAILURE)
  Process: 841 ExecStart=/nix/store/y5ip6qrc0jm1a7n4wi1dnn019i0sx8av-unit-script/bin/vboxnet0-start (code=exited, status=1/FAILURE)
 Main PID: 841 (code=exited, status=1/FAILURE)

апр 28 23:23:52 ckopo-nix vboxnet0-start[841]: VBoxManage: error: Code NS_ERROR_SOCKET_FAIL (0xC1F30200) - IPC daemon socket error (extended info not available)
апр 28 23:23:52 ckopo-nix vboxnet0-start[841]: VBoxManage: error: Most likely, the VirtualBox COM server is not running or failed to start.
апр 28 23:23:52 ckopo-nix systemd[1]: vboxnet0.service: Main process exited, code=exited, status=1/FAILURE
апр 28 23:23:52 ckopo-nix vboxnet0-post-stop[908]: VBoxManage: error: Failed to create the VirtualBox object!
апр 28 23:23:52 ckopo-nix vboxnet0-post-stop[908]: VBoxManage: error: Code NS_ERROR_SOCKET_FAIL (0xC1F30200) - IPC daemon socket error (extended info not available)
апр 28 23:23:52 ckopo-nix vboxnet0-post-stop[908]: VBoxManage: error: Most likely, the VirtualBox COM server is not running or failed to start.
апр 28 23:23:52 ckopo-nix systemd[1]: vboxnet0.service: Control process exited, code=exited status=1
апр 28 23:23:52 ckopo-nix systemd[1]: Failed to start VirtualBox vboxnet0 Interface.
апр 28 23:23:52 ckopo-nix systemd[1]: vboxnet0.service: Unit entered failed state.
апр 28 23:23:52 ckopo-nix systemd[1]: vboxnet0.service: Failed with result 'exit-code'.

```

### Steps to reproduce

- have VirtualBox installed
- try rebooting or abnormal poweroffs

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.83, NixOS, 17.09.3047.8bce347f02f (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.3047.8bce347f02f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by chekoopa** [comment] 2018-04-30 05:05
@Infinisil You mean, switching channel to 18.03? Gonna try it, when I get off mobile network.

Again, it's a generation-independent issue. Maybe 18.03 rebuild would fix that, who knows. But I'm afraid that reinstall is inescapable. 

I've tried `nixos-rebuild` with `--repair` flag. It doesn't fix this issue, setting a warning:
```warning: the following units failed: vboxnet0.service

● vboxnet0.service - VirtualBox vboxnet0 Interface
   Loaded: loaded (/nix/store/1z3mi0m860bghxs8axz9pw6if2n8ss7a-unit-vboxnet0.service/vboxnet0.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-04-30 13:03:04 +08; 1min 30s ago
  Process: 28871 ExecStopPost=/nix/store/69sdla5sqzhc0p05pq661zdsmmzllxcq-unit-script/bin/vboxnet0-post-stop (code=exited, status=1/FAILURE)
  Process: 28840 ExecStart=/nix/store/y5ip6qrc0jm1a7n4wi1dnn019i0sx8av-unit-script/bin/vboxnet0-start (code=exited, status=1/FAILURE)
 Main PID: 28840 (code=exited, status=1/FAILURE)

апр 30 13:03:04 ckopo-nix vboxnet0-start[28840]: VBoxManage: error: Code NS_ERROR_SOCKET_FAIL (0xC1F30200) - IPC daemon socket error (extended info not available)
апр 30 13:03:04 ckopo-nix vboxnet0-start[28840]: VBoxManage: error: Most likely, the VirtualBox COM server is not running or failed to start.
апр 30 13:03:04 ckopo-nix systemd[1]: vboxnet0.service: Main process exited, code=exited, status=1/FAILURE
апр 30 13:03:04 ckopo-nix vboxnet0-post-stop[28871]: VBoxManage: error: Failed to create the VirtualBox object!
апр 30 13:03:04 ckopo-nix vboxnet0-post-stop[28871]: VBoxManage: error: Code NS_ERROR_SOCKET_FAIL (0xC1F30200) - IPC daemon socket error (extended info not available)
апр 30 13:03:04 ckopo-nix vboxnet0-post-stop[28871]: VBoxManage: error: Most likely, the VirtualBox COM server is not running or failed to start.
апр 30 13:03:04 ckopo-nix systemd[1]: vboxnet0.service: Control process exited, code=exited status=1
апр 30 13:03:04 ckopo-nix systemd[1]: Failed to start VirtualBox vboxnet0 Interface.
апр 30 13:03:04 ckopo-nix systemd[1]: vboxnet0.service: Unit entered failed state.
апр 30 13:03:04 ckopo-nix systemd[1]: vboxnet0.service: Failed with result 'exit-code'.
warning: error(s) occurred while switching to the new configuration
```

**Comment by chekoopa** [comment] 2018-05-01 02:25
I can't now upgrade other than reinstalling #39730

**Comment by coretemp** [comment] 2018-05-02 11:26
Just here to confirm this issue; it has been broken since at least 17.09.

**Comment by matthewbauer** [comment] 2018-05-15 21:25
So to be clear, this is a MacOS Host & a NixOS Guest?

Could you try the solution here:

https://forums.virtualbox.org/viewtopic.php?f=8&t=87275

**Comment by coretemp** [comment] 2018-05-16 08:29
Even without a guest this problem happens on various versions of NixOS.

**Comment by matthewbauer** [comment] 2018-05-16 19:55
I think you can disable this with ```options.virtualisation.virtualbox.host.addNetworkInterface = false;```.

It must have been broken between VirtualBox updates. I wonder if this interface works for anyone? We could try making the default false. Someone will have to take the time to fix it.

**Comment by matthewbauer** [comment] 2018-05-16 20:01
Actually is this a dupe of https://github.com/NixOS/nixpkgs/issues/6037?

**Comment by coretemp** [comment] 2018-05-17 13:35
I haven't seen it happen during boot myself, but perhaps I lowered the timeout at some point. It could be a dupe.

**Comment by Ekleog** [comment] 2019-05-21 00:16
I seem to remember I had this issue for a while and it vanished after either the switch to 18.09 or to 19.03. So I guess the problem is now fixed. Feel free to reopen if you're still having this issue.

**Closed by Ekleog** 2019-05-21 00:16 UTC
