### ISSUE TITLE
ltrace does not show function calls to selfmade shared library

### ISSUE THREAD

**Issue by castilma** [NixOS/nixpkgs#45152] opened 2018-08-16 20:39 UTC
## Issue description
(title)

### Steps to reproduce

```
//foo.c
int bar(int a) {
	return a+1;
}
```
```
//main.c
int bar(int);
int main() {
    return bar(1);
}
```
`gcc -shared -o libfoo.so foo.c`
`gcc -o main main.c -L. -lfoo -Wl,-rpath=$(pwd)`
```
$ ltrace ./m
+++ exited (status 2) +++
```
I expected to see the call to bar.

## Technical details

ltrace version 0.7.3.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.62, NixOS, 18.03.133065.e42c07d78a1 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(mcd): `""`
 - channels(root): `"nixos-18.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by dtzWill** [comment] 2018-08-16 22:48
I can reproduce on 18.03, but not on master.

Haven't checked but appears 3ecad270323a6f05879be9786579da6dd4ed91c3 isn't on 18.03 and may have fixed it.

Does using master resolve the issue for you? If so we may want to test if cherry-picking that commit to 18.03 works as well.

Hope this helps!

**Comment by castilma** [comment] 2018-08-17 11:06
with master you mean nixos-unstable?
it does not work after:
`nix-channel --add https://nixos.org/channels/nixos-unstable; nix-channel --update; nix-env -iA nixos.ltrace;`

**Comment by bjornfor** [comment] 2018-08-28 08:32
Not sure if this is the same issue, but I'm throwing it out there. I once spent a lot of time wondering why ltrace "didn't work" with programs built in Nix environments. In the end I found that I had to "export hardeningDisable=all" before invoking gcc.

**Comment by dtzWill** [comment] 2018-08-28 12:34
> with master you mean nixos-unstable?
> it does not work after:
> nix-channel --add https://nixos.org/channels/nixos-unstable; nix-channel --update; nix-env -iA nixos.ltrace;

No I mean master branch of this repository.  But I'd expect unstable too, just didn't check.



> Not sure if this is the same issue, but I'm throwing it out there. I once spent a lot of time wondering why ltrace "didn't work" with programs built in Nix environments. In the end I found that I had to "export hardeningDisable=all" before invoking gcc.

Ahh, good call.  Probably bind-now or something? I'll check if that was playing a role, don't remember if I was building the binary using each shell's gcc or not.  Probably since it's part of the OP's message.

**Tests a bit**

Indeed, looks like disabling hardening fixes this in my testing on 18.03.  This seems related to discussion of disabling hardening when using compilers outside of Nix since that was a frequent source of confusion.  It appears this is now how things are done (master as well as on unstable), which is why that worked.

Furthermore as expected it's particularly the 'bindnow' option that makes ltrace work/not work.

A solution is in sight! :)

**Comment by dtzWill** [comment] 2018-08-28 12:41
Bit more on the subject: https://bugzilla.redhat.com/show_bug.cgi?id=1333481

**Comment by dtzWill** [comment] 2018-08-28 13:30
Oh and it appears the disabling of hardening only occurs when using `nix run`, not `nix-shell`? I'll open an issue about that shortly, if nothing else it'd be good to ensure this behavior is intended/expected.

**Comment by Enteee** [comment] 2020-03-29 10:49
```
$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.25, NixOS, 20.09pre217526.9b3515eb95d (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"home-manager, nixos-20.09pre217537.d96bd3394b7, nixos-hardware, nixpkgs-20.09pre217526.9b3515eb95d"`
 - channels(ente): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
$ nix-shell -p ltrace
$ cat <<EOF > foo.c
> int bar(int a) {
> return a+1;
> }
> EOF
$ cat <<EOF >main.c
> int bar(int);
> int main() {
>     return bar(1);
> }
> EOF
$ gcc -shared -o libfoo.so foo.c
$ gcc -o main main.c -L. -lfoo -Wl,-rpath=$(pwd)
$ ltrace ./main 
bar(1, 0x7fff915f8778, 0x7fff915f8788, 0x7fa39c0cb578)                                                                             = 2
+++ exited (status 2) ++
```

@castilma looks like this is solved, please close the issue
@dtzWill as you can see from the example above, work even in `nix-shell` now.

**Closed** 2020-03-29 11:35 UTC
