### ISSUE TITLE
gobject-introspection fails to crossbuild: tests failing

### ISSUE THREAD

**Issue by Split7fire** [NixOS/nixpkgs#139442] opened 2021-09-25 14:14 UTC
### Describe the bug
I'm trying to crosscompile qt5 on linux. I use pkgsCross.mingwW64.buildPackages.qt5.full and pkgsCross.mingwW64.buildPackages.gcc. While gobject-introspection crossbuild fine, gitypelibtest fails. This is output I get:
`GI_TYPELIB_PATH=/build/gobject-introspection-1.68.0/build/gir:/build/gobject-introspection-1.68.0/build/tests:/build/gobject-introspection-1.68.0/build/tests/scanner MALLOC_PERTURB_=73 LD_LIBRARY_PATH=/build/gobject-introspection-1.68.0/build/tests/scanner /build/gobject-introspection-1.68.0/build/tests/repository/gitypelibtest
 ✀  
stderr:

** (process:3454): WARNING **: 13:57:22.620: Failed to load shared library '/nix/store/4ky10n38z8g0834b27xx68mwx8dpjsr9-gobject-introspection-1.68.0/lib/libregress-1.0.so' referenced by the typelib: /nix/store/4ky10n38z8g0834b27xx68mwx8dpjsr9-gobject-introspection-1.68.0/lib/libregress-1.0.so: cannot open shared object file: No such file or directory
` 

### Steps To Reproduce
1. Start building pkgsCross.mingwW64.buildPackages.qt5.full and pkgsCross.mingwW64.buildPackages.gcc on linux x64.

### Expected behavior
Qt5 crosscompiled fine.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 5.13.13-zen1, NixOS, 21.05.3314.83413f47809 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.05.3314.83413f47809"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Mindavi** [comment] 2021-09-26 13:39
Duplicate of https://github.com/NixOS/nixpkgs/issues/72868?

**Comment by Split7fire** [comment] 2021-09-26 13:42
@Mindavi May be. In fact I tried to disable test altogether for entire package. I tried like this:
`let
  gobject-introspection = pkgs.gobject-introspection.override {
    doCheck = false;
  };
in`
But it don't work. Any ideas how to overcome this?

**Comment by Mindavi** [comment] 2022-04-19 06:15
Sorry for not responding anymore. But I don't actually have an idea how to resolve the gobject issues.

**Comment by Mindavi** [comment] 2022-04-19 06:16
Also, closing in favor of the related issue which has more discussion.

**Closed by Mindavi** 2022-04-19 06:16 UTC
Labels: 0.kind: bug, 6.topic: cross-compilation
