### ISSUE TITLE
NixOS option boot.extraModprobeConfig not avaible in initrd

### ISSUE THREAD

**Issue by ck3d** [NixOS/nixpkgs#25456] opened 2017-05-02 20:13 UTC
## Issue description
I want to pass options to the kernel module hid_apple by setting the appropriated string to NixOS option _boot.extraModprobeConfig_. This configuration is not taken into account, because the module is loaded during first stage boot phase.

## Technical details
in _nixos/modules/system/boot/stage-1.nix_ definition of initialRamdisk misses object /etc/modprobe.d/nixos.conf

Is there a reason, why it is not available in initrd?

* System: NixOS: 17.03.1082.4aab5c5798 (Gorilla)
* Nix version: 1.11.8
* Nixpkgs version: 17.03.1082.4aab5c5798

**Comment by Mic92** [comment] 2017-05-02 20:37
the module is enabled in the kernel:

```
$ zgrep HID_APPLE /proc/config.gz
CONFIG_HID_APPLE=m
CONFIG_HID_APPLEIR=m
```

**Comment by Mic92** [comment] 2017-05-02 20:39
Is the following helpful: https://github.com/NixOS/nixos-hardware/blob/master/apple/macbook-pro-10-1.nix ?
If not, but you manage to find a solution please feel free to extend.

**Comment by ck3d** [comment] 2017-05-02 23:30
The driver hid_apple is part of initrd and it is loaded during the first boot phase without problems.

To configure a kernel module, you normally extend modprobe.conf. In NixOS you define boot.extraModprobeConfig. So far so good, but this do not work for modules, which are loaded during the first boot phase. In my special case the kernel module hid_apple, which I need for my Apple keyboard.

**Comment by dezgeg** [comment] 2017-05-03 06:35
Sounds like it would make sense to include the contents of `boot.extraModprobeConfig` to the initrd as well.

**Comment by waldheinz** [comment] 2017-10-10 10:55
I have root on ZFS, and my

```
boot.extraModprobeConfig = "options zfs zfs_arc_max=4194304";
```

seems to be ignored because of this as well.

**Comment by soredake** [comment] 2018-04-23 05:44
Any progress?

**Comment by vith** [comment] 2019-03-14 23:01
Looks like a dupe of https://github.com/NixOS/nixpkgs/issues/20906

**Comment by arcnmx** [comment] 2020-01-29 15:44
I just ran into this for another module and had to move some options to `kernelParams` as a result. It would be nice if a proper solution could be found...

So it looks like there's a story behind this way back from 2014: It was fixed in #3505 and then quickly reverted again: 4a4c051a95b6b8da3a13d7955087e915e6dd4bf7. The problem appears to be that `options firmware_class path=/nix/store/...-firmware/lib/firmware` can be set in modprobe.conf, which I guess blows up the initrd closure/image?

**Comment by arcnmx** [comment] 2020-07-27 16:08
> 180 days

That seems kind of short..? that's barely even a single nixos release cycle... Bugs don't just magically get fixed if they're ignored for a few months :<

**Comment by Mic92** [comment] 2020-07-27 16:26
> > 180 days
> 
> That seems kind of short..? that's barely even a single nixos release cycle... Bugs don't just magically get fixed if they're ignored for a few months :<

We won't close them automatically. It just a reminder to have a look at the issue again and see if it was fixed or still applies. Sometimes issue don't get not closed also the issue has been resolved.

**Comment by arcnmx** [comment] 2021-04-10 13:47
fwiw I've been using [this module](https://github.com/arcnmx/nixexprs/blob/master/modules/nixos/modprobe.nix) for a while to get around this, it appends the options set by it to initrd (unless explicitly excluded for situations like the firmware closure)

**Comment by Luflosi** [comment] 2021-11-07 21:37
I created #145013 to fix this issue properly.

**Comment by bb2020** [comment] 2021-11-08 10:19
> I want to pass options to the kernel module hid_apple by setting the appropriated string to NixOS option _boot.extraModprobeConfig_. This configuration is not taken into account, because the module is loaded during first stage boot phase.

How about `boot.kernelParams = [ "hid_apple.fnmode=2" "hid_apple.swap_opt_cmd=1" ];`

**Closed** 2022-01-24 22:35 UTC
