### ISSUE TITLE
Package request: windsurf

### ISSUE THREAD

**Issue by Nathan13888** [NixOS/nixpkgs#360073] opened 2024-11-29 08:34 UTC
## Project description

Another VS-code based editor similar to Cursor ([website](https://www.cursor.com/), [nixpkg](https://github.com/NixOS/nixpkgs/issues/309541)).

* https://windsurf.ai/
* https://x.com/codeiumdev/status/1856741823768879172

## Metadata

* homepage URL: https://codeium.com/windsurf
* source URL: https://codeium.com/windsurf/download_linux
https://windsurf-stable.codeiumdata.com/linux-x64/stable/d33d40f6cd3a4d7e451b22e94359230a4aa8c161/Windsurf-linux-x64-1.0.5.tar.gz
```
curl -fsSL "https://windsurf-stable.codeiumdata.com/wVxQEIWkwPUEAGf3/windsurf.gpg" | sudo gpg --dearmor -o /usr/share/keyrings/windsurf-stable-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/windsurf-stable-archive-keyring.gpg arch=amd64] https://windsurf-stable.codeiumdata.com/wVxQEIWkwPUEAGf3/apt stable main" | sudo tee /etc/apt/sources.list.d/windsurf.list > /dev/null
```
* license: mit, NON-FREE
* platforms: linux
---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by NikSneMC** [comment] 2024-12-02 19:00
Looks like duplicate of# #356478

**Closed** 2024-12-03 18:26 UTC
Labels: 0.kind: packaging request

**Comment by joyanhui** [comment] 2025-02-08 07:04
https://github.com/NixOS/nixpkgs/pull/380284
