### ISSUE TITLE
Plasma5 task manager is too slow

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#49162] opened 2018-10-26 16:00 UTC
## Issue description
This is probably an upstream issue, but since we don't know that yet:

When I click on Konsole (I have 50 terminals open) in the task manager, I have to wait 2-3 seconds, before the menu with the items and the scrollbar exists allowing me to select the Konsole instance of interest. I suspect quadratic scaling in this feature, which makes it too slow for interactive use. 

### Steps to reproduce
Create 50 instances of Konsole and try to switch to the lowest one.

## Technical details
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.1.1, nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos

**Comment by worldofpeace** [comment] 2018-10-26 16:57
> This is probably an upstream issue, but since we don't know that yet

I don't see how this could be related to NixOS.

I think it would be a good idea to report this at their [bugtracker](https://bugs.kde.org/).

**Comment by coretemp** [comment] 2018-10-27 13:35
I opened https://bugs.kde.org/show_bug.cgi?id=400364.

Just because you cannot see a direct connection (neither can I), doesn't mean there is no connection. Reporting issues in this particular way by including the two communities increases the cache hit rate for other people that might have the same issue.

Also, if you take the stance that NixOS is a full operating system (like FreeBSD) then it is a bug in NixOS. If you don't have this stance, then you are essentially saying that we just throw some components together and hope it sticks. Not sure whether there is a specific policy for this.  

I read Slackware doesn't (or didn't) distribute Plasma5, because it was considered a broken system. One of the main contributors to Slackware made significant contributions to Plasma5 to improve its state, however. I hope this piece of context shows that there exist distributions that consider the complete user experience and are building a full *system*. Whether NixOS is such a system, I don't know. Currently, I see it more as an operating system toolkit than an operating system. What are your thoughts on this?

**Comment by jcrben** [comment] 2018-10-27 18:33
I don't agree with reporting upstream in both places as a general matter. There's just too many, and it confuses where the fix lies. Do you have a machine running another system? If so, can you try it there? If it's not caused by NixOS, I hope you consider closing this.

NixOS does tend to have unique issue affecting core packages sometimes. One way that I check if it's really a NixOS issue is to run different distributions off a USB drive. For example you can install Arch following http://valleycat.org/linux/arch-usb.html?i=2 - I also installed Ubuntu on a USB drive (altho it was a pain as the installer has bugs; manually installed bootloader roughly following https://gist.github.com/0x414A/7f1c27ac24f05a42ed43aa73946a7033).

I sometimes hang out on KDE areas, but when I get the chance I recommend that they pull more of their stuff into plugins and do not explicitly support it in the core. I recommend that NixOS does the same - if we could modularize KDE to have as few widgets shipping into NixOS by default as possible, we reduce our maintenance burden and your complaint about "full system". I feel like 50 Konsole tabs is a bit niche anyhow.

**Comment by worldofpeace** [comment] 2018-10-27 21:13
> Also, if you take the stance that NixOS is a full operating system (like FreeBSD) then it is a bug in NixOS. If you don't have this stance, then you are essentially saying that we just throw some components together and hope it sticks. Not sure whether there is a specific policy for this.

I agree downstreams should take responsibility for the software that is being distributed.

> Also, if you take the stance that NixOS is a full operating system (like FreeBSD) then it is a bug in NixOS. If you don't have this stance, then you are essentially saying that we just throw some components together and hope it sticks. Not sure whether there is a specific policy for this.

 It is really preferable and better for everyone to just improve the ecosystem that you participate in anyway they can. NixOS can have strange issues at times so it can be fine to open an issue, if it is of high severity. However general performance of an application in this case, it's not feasible to keep track of here. (or actionable)

**Comment by dotlambda** [comment] 2019-02-13 22:23
Has been solved upstream: https://bugs.kde.org/show_bug.cgi?id=400364#c2.

**Closed by dotlambda** 2019-02-13 22:23 UTC
