### ISSUE TITLE
Quarto-cli

### ISSUE THREAD

**Issue by Kupac** [NixOS/nixpkgs#189017] opened 2022-08-30 20:39 UTC
**Project description**
Quarto: an open-source scientific and technical publishing system

**Metadata**

* homepage URL: https://quarto.org/
* source URL: https://github.com/quarto-dev/quarto-cli
* license: gpl2+
* platforms: unix, linux, darwin, win?

**Comment by Kupac** [comment] 2022-08-30 20:40
Sorry, just saw it's a duplicate

**Comment by milahu** [comment] 2022-08-31 17:37
duplicate of #160911

@Kupac please close this issue

**Closed** 2022-08-31 21:00 UTC
Labels: 0.kind: packaging request
