### ISSUE TITLE
Build failure: awscli2

### ISSUE THREAD

**Issue by cterence** [NixOS/nixpkgs#298023] opened 2024-03-22 12:27 UTC
### Steps To Reproduce

1. build *awscli2*

### Build log

```
Running phase: configurePhase
patching script interpreter paths in ./configure
./configure: interpreter directive changed from "#! /bin/sh" to "/nix/store/5lr5n3qa4day8l1ivbwlcby2nknczqkq-bash-5.2p26/bin/sh"
configure flags: --prefix=/nix/store/gh4r6pp80ghgznzm57q096c3k9rckwq6-awscli2-2.15.15 --bindir=/nix/store/gh4r6pp80ghgznzm57q096c3k9rckwq6-awscli2-2.15.15/bin --sbindir=/nix/store/gh4r6pp80ghgznzm57q096c3k9rckwq6-awscli2-2.15.15/sbin --includedir=/nix/store/gh4r6pp80ghgznzm57q096c3k9rckwq6-awscli2-2.15.15/include --oldincludedir=/nix/store/gh4r6pp80ghgznzm57q096c3k9rckwq6-awscli2-2.15.15/include --mandir=/nix/store/gh4r6pp80ghgznzm57q096c3k9rckwq6-awscli2-2.15.15/share/man --infodir=/nix/store/gh4r6pp80ghgznzm57q096c3k9rckwq6-awscli2-2.15.15/share/info --docdir=/nix/store/gh4r6pp80ghgznzm57q096c3k9rckwq6-awscli2-2.15.15/share/doc/awscli --libdir=/nix/store/gh4r6pp80ghgznzm57q096c3k9rckwq6-awscli2-2.15.15/lib --libexecdir=/nix/store/gh4r6pp80ghgznzm57q096c3k9rckwq6-awscli2-2.15.15/libexec --localedir=/nix/store/gh4r6pp80ghgznzm57q096c3k9rckwq6-awscli2-2.15.15/share/locale
checking for a Python interpreter with version >= 3.8... python
checking for python... /nix/store/7wz6hm9i8wljz0hgwz1wqmn2zlbgavrq-python3-3.11.8/bin/python
checking for python version... 3.11
checking for python platform... linux
checking for GNU default python prefix... ${prefix}
checking for GNU default python exec_prefix... ${exec_prefix}
checking for python script directory (pythondir)... ${PYTHON_PREFIX}/lib/python3.11/site-packages
checking for python extension module directory (pyexecdir)... ${PYTHON_EXEC_PREFIX}/lib/python3.11/site-packages
checking for sqlite3... yes
checking for --with-install-type... system-sandbox
checking for --with-download-deps... Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/build/source/./backends/build_system/__main__.py", line 125, in <module>
    main()
  File "/build/source/./backends/build_system/__main__.py", line 121, in main
    parsed_args.func(parsed_args)
  File "/build/source/./backends/build_system/__main__.py", line 49, in validate
    validate_env(parsed_args.artifact)
  File "/build/source/./backends/build_system/validate_env.py", line 36, in validate_env
    unmet_deps = _get_unmet_dependencies(requirements)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/./backends/build_system/validate_env.py", line 81, in _get_unmet_dependencies
    if not requirement.is_in_range(actual_version):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/./backends/build_system/utils.py", line 90, in is_in_range
    return self._meets_constraints(version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/./backends/build_system/utils.py", line 93, in _meets_constraints
    return all(
           ^^^^
  File "/build/source/./backends/build_system/utils.py", line 94, in <genexpr>
    self._meets_constraint(version, constraint)
  File "/build/source/./backends/build_system/utils.py", line 103, in _meets_constraint
    version, constraint_version = self._normalize(version, constraint_version)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/./backends/build_system/utils.py", line 111, in _normalize
    v1_parts = [int(v) for v in v1.split(".")]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/./backends/build_system/utils.py", line 111, in <listcomp>
    v1_parts = [int(v) for v in v1.split(".")]
                ^^^^^^
ValueError: invalid literal for int() with base 10: 'post0'
configure: error: "Python dependencies not met."
```

### Additional context

New to NixOS, I ran `nix flake update` and `sudo nixos-rebuild switch --upgrade --flake ~/nixos#pc`. Removing and reinstalling the package did not fix the issue.

### Notify maintainers

@bhipple @davegallant @bryanasdev000 @devusb @anthonyroussel 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.22, NixOS, 24.05 (Uakari), 24.05.20240321.20f77aa`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/store/wa8lhchql76i6czzvad3bqz6lvnjnbr5-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by anthonyroussel** [comment] 2024-03-22 13:39
Hello
Thank you for reporting the issue.

Indeed, I have a PR to upgrade awscli2 to 2.15.29 whose the build is failing now after rebasing it with master: https://github.com/NixOS/nixpkgs/pull/296007

Looks like the issue could be caused by this python-updates PR merged into staging branch: https://github.com/NixOS/nixpkgs/pull/294305/files (and then merged into master yesterday: https://github.com/NixOS/nixpkgs/pull/295458)

Looks like python-dateutil being updated to 2.9.0.post0 could be the cause.
I will take a look.

**Comment by anthonyroussel** [comment] 2024-03-22 13:51
Indeed, [backends/build_system/utils.py backend build system script](https://github.com/aws/aws-cli/blob/v2/backends/build_system/utils.py) used to check if the installed dependencies meets constraints does only supports simple version numbers (X.Y.Z).

And `2.9.0.post0` version does not parse and the script fails (`2.9.0.post0` is also not semver compliant).

**Comment by Sgiath** [comment] 2024-03-22 21:29
I am also experiencing the same issue

**Comment by devusb** [comment] 2024-03-23 02:41
Looks like upstream may be trying to avoid this version too for now, they made [this change](https://github.com/aws/aws-cli/commit/1fb4dacc44cf09be53fe73cd29fd955a2a331fb7) recently pinning it to `<=2.8.2`.

**Comment by anthonyroussel** [comment] 2024-03-23 11:22
@devusb Thanks for your help.
Indeed, looks like pinning python-dateutil to 2.8.2 is a resolution: https://github.com/NixOS/nixpkgs/pull/296007/files
Yes, I added the fix in my upgrade PR.

**Comment by anthonyroussel** [comment] 2024-03-26 08:42
The build has just passed on Hydra: https://hydra.nixos.org/build/254227260

**Comment by tlvince** [comment] 2024-03-26 20:32
Its arrived in [nixos-unstable](https://nixpk.gs/pr-tracker.html?pr=296007). I think this can be closed now 👍🏻

**Comment by anthonyroussel** [comment] 2024-03-26 20:33
Yes we can close now :)

**Closed by anthonyroussel** 2024-03-26 20:33 UTC
Labels: 0.kind: build failure
