### ISSUE TITLE
Channel blocker: aarch64 nixos-sd-image

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#90285] opened 2020-06-14 07:17 UTC
**Describe the bug**
Output limit exceeded
https://hydra.nixos.org/build/122144214

```
Checking for unused clusters.
firmware_part.img: 20 files, 12115/15321 clusters
61440+0 records in
61440+0 records out
31457280 bytes (31 MB, 30 MiB) copied, 3.43497 s, 9.2 MB/s
/nix/store/v243glwi4vp4cx7jb12jrwgflnbkd5cn-nixos-sd-image-20.09pre229527.6ce032f79b2-aarch64-linux.img/sd-image/nixos-sd-image-20.09pre229527.6ce032f79b2-aarch64-linux.img : 23.69%   (2790121472 => 661003449 bytes, /nix/store/v243glwi4vp4cx7jb12jrwgflnbkd5cn-nixos-sd-image-20.09pre229527.6ce032f79b2-aarch64-linux.img/sd-image/nixos-sd-image-20.09pre229527.6ce032f79b2-aarch64-linux.img.zst) 
```

**Comment by vcunat** [comment] 2020-06-14 08:21
That's duplicate of https://github.com/NixOS/nixpkgs/issues/90230 and it [succeeds on Hydra](https://hydra.nixos.org/build/122151526) already.

**Closed by vcunat** 2020-06-14 08:21 UTC
Labels: 0.kind: bug, 1.severity: channel blocker, 2.status: duplicate
