### ISSUE TITLE
buildStackProject can not be used an an imported nix buildInput

### ISSUE THREAD

**Issue by bbarker** [NixOS/nixpkgs#84757] opened 2020-04-08 23:49 UTC
**Describe the bug**
When a shell (say `outer.nix`) uses another nix expression that is imported as a buildInput, and that other nix expression uses `buildStackProject` instead of mkDerivation, the build fails due to network activity in the build phase. It looks like this:

```
$ nix-shell
these derivations will be built:
  /nix/store/n448wi8w0rj5x6f907frwryvismj4930-impureMatlabEnv.drv
building '/nix/store/n448wi8w0rj5x6f907frwryvismj4930-impureMatlabEnv.drv'...
patching sources
configuring
no configure script, doing nothing
building
Writing implicit global project config file to: /build/.stack/global-project/stack.yaml
Note: You can change the snapshot via the resolver field there.
HttpExceptionRequest Request {
  host                 = "s3.amazonaws.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("Accept","application/json"),("User-Agent","The Haskell Stack")]
  path                 = "/haddock.stackage.org/snapshots.json"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host name: Just "s3.amazonaws.com", service name: Just "443"): does not exist (Name or service not known))
builder for '/nix/store/n448wi8w0rj5x6f907frwryvismj4930-impureMatlabEnv.drv' failed with exit code 1
error: build of '/nix/store/n448wi8w0rj5x6f907frwryvismj4930-impureMatlabEnv.drv' failed
```

**To Reproduce**
1. create inner.nix using `buildStackProject`
2. create outer.nix using inner.nix as an imported buildInput
3. `nix-shell outer.nix`

**Expected behavior**
I would expect the shell to execute since calling `nix-shell inner.nix` is not an issue.

**Additional context**

An [example of inner.nix](https://github.com/CornellCAC/haskell-matlab/blob/update_and_run_in_stack_nix/shell.nix). 

Rough sketch of an outer.nix:

```nix
with import <nixpkgs> {};
let
  gurobiPlatform = "linux64";
  myGurobi = (import nix/packages/gurobi/default.nix);
  myMatlab = (import nix/shells/MATLAB/default.nix);  # here is the `inner.nix`
  cobraToolboxLocal = stdenv.mkDerivation {
    name = "cobraToolbox-local";
    src = fetchgit {
      url = "https://github.com/opencobra/cobratoolbox.git";
      rev = "92518352da3dc1f63b7ef781345786f5cf73034c";
      sha256 = "0dsz2046vjxv89imifacv15jkv6avg8xrssig6n7kxsv98i1rm29";
    };
    buildInputs =  [ ];
    builder = builtins.toFile "builder.sh" ''
      source $stdenv/setup
      mkdir -p $out
      cp -R $src/* $out/
    '';
  };
in
haskell.lib.buildStackProject {
  name = "cobraMatlabHaskellEnv";
  dontUnpack = true;
  buildInputs = [
    makeWrapper
    myMatlab
    zlib
  ];

  src = null;
  shellHook = ''
    # Copied or modified from MATLAB's default.nix:
    export MATLAB_PATH=${myMatlab.matlabPath}
    export PATH=$PATH:$MATLAB_PATH/bin
    source ${./nix/shells/MATLAB/patchMATLAB.sh}
  '';
```

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.113, NixOS, 19.09.2350.d011e474945 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(nixos): `""`
 - channels(root): `"nixos-19.09.2350.d011e474945"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
# a list of nixos modules affected by the problem
module:
```

**Comment by cdepillabout** [comment] 2020-04-09 04:15
@bbarker Sorry you're having trouble with this.

`buildStackProject` is not expected to work to actually build derivations (unless you disable sandboxing).  It is really only to support `stack`'s native nix-support.

What you have to do is add all the required packages to your `stack.yaml` (in the `extra-deps` section?).  The top-level `buildStackProject` should be passed `buildInputs` that are necessary for the given package, and _all_ dependencies.  This is quite unlike a normal packaging style in nixpkgs.

If you have trouble getting this working, please feel free to post a simple, reproducible example for me (or someone else) to take a look at.

I'd suggest looking at stack's nix documentation, as well as https://github.com/cdepillabout/post-about-nix-and-haskell/blob/master/2019-08-03-q-and-as-about-nix-for-haskellers.md.

I'm going to close this, since `buildStackProject` is not supposed to be used this way, but please feel free to re-open if I've misunderstood what you're asking.

**Closed by cdepillabout** 2020-04-09 04:15 UTC
Labels: 0.kind: bug, 6.topic: haskell
