### ISSUE TITLE
pidgin needs GST_PLUGIN_SYSTEM_PATH for audio notifications

### ISSUE THREAD

**Issue by ben0x539** [NixOS/nixpkgs#13719] opened 2016-03-06 20:05 UTC
## Basic info

```
$ uname -a
Linux $hostname 4.4.2 #1-NixOS SMP Wed Feb 17 20:31:25 UTC 2016 x86_64 GNU/Linux
$ nixos-version
16.03pre77568.40c586b (Emu)
$ nix-env --version
nix-env (Nix) 1.11.2
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.09pre78286.0bf8a1a"
```

## Describe your issue here

pidgin can't play sound by itself. It can run aplay or similar to play its sound files, but out of the box it silently fails to play notification sounds.

afaict pidgin requires and installs gstreamer but isn't set up to find what it needs at runtime. if i manually set GST_PLUGIN_SYSTEM_PATH to a value cribbed from some other package's wrapper script (like firefox), it successfully emits sound.

### Expected result

Notification sounds play out of the box

### Actual result

Notification sounds do not play

### Steps to reproduce

* `nix-env -iA nixos.pidgin` in a fairly empty user environment (no desktop environment or anything fancy)
* go to Tools > Preferences > Sounds
* press the "Preview" button at the bottom

**Comment by vcunat** [comment] 2016-03-06 21:39
This is probably a duplicate of #10556, but that isn't important...

**Comment by hrdinka** [comment] 2016-03-06 23:15
Please check if https://github.com/NixOS/nixpkgs/pull/13722 fixes your issue.

**Comment by ben0x539** [comment] 2016-03-07 00:05
Yeah, that fixes it. Thank you!

**Closed** 2016-03-07 06:12 UTC
Labels: 0.kind: bug
