### ISSUE TITLE
Cron does not execute /etc/crontab

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#15373] opened 2016-05-10 21:40 UTC
## Issue description

Cron does not execute the system crontab.
### Steps to reproduce

Install and configure crontab:
/etc/nixos/configuration
`services.cron.enable = true;
 services.cron.systemCronJobs = [ "* * * * * wall CRON WORKS"];`

No message is received after 1 minute.
## Technical details
- System: 16.09pre82105.7465bcd (Flounder)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.09pre82105.7465bcd"

**Comment by peti** [comment] 2016-05-11 13:29
I don't think `wall` is a good choice here. Would you mind trying to execute `date >>/tmp/cron-is-alive` instead?

**Comment by d4g** [comment] 2016-05-12 19:54
I tried that beforehand. It did not work as well. Not even touch worked. The wall test was to check, whether there were some weird access right issues.

**Comment by kevincox** [comment] 2016-08-05 18:58
Can you verify if the cron service is running? (`systemctl status cron`)

**Comment by mogorman** [comment] 2016-08-26 18:39
if i had to guess you hit same problem with cron i did. cron isnt on the write path.  I did an echo ${PATH} on my cli and copied that into my cron file as PATH=result of my echo and it started to function correctly.

**Comment by roxma** [comment] 2016-11-13 02:23
Same issue here.

## Reproducing steps:

Follow the instructions [here](https://nixos.org/wiki/Installing_NixOS_in_a_VirtualBox_guest) to do a Minimal Install (For Servers)

```nix
{ config, pkgs, ...} :
{
  boot.loader.grub.device = "/dev/sda";

  # Enable virtualbox guest additions
  virtualisation.virtualbox.guest.enable = true;
  
  # Enable the sshd daemon so you can ssh
  # into the 
  services.openssh.enable = true;
  
  fileSystems = [
    { mountPoint = "/";
      label = "nixos";
    }
  ];
}
```

install, shutdown, remove .iso disk, boot the server.

Then change the configuration into:

```nix
{ config, pkgs, ...} :
{
  boot.loader.grub.device = "/dev/sda";

  # Enable virtualbox guest additions
  virtualisation.virtualbox.guest.enable = true;
  
  # Enable the sshd daemon so you can ssh
  # into the 
  services.openssh.enable = true;
  services.cron.enable = true;
  services.cron.systemCronJobs = [
    "* * * * * echo echo Hello world > /tmp/cronout"
  ];
  fileSystems = [
    { mountPoint = "/";
      label = "nixos";
    }
  ];
}
```

apply the new config

```
nixos-rebuild switch
reboot
```


## Results:

```
[root@nixos:/]# systemctl status cron
● cron.service - Cron Daemon
   Loaded: loaded (/nix/store/pb8nbbfl5khaql4qp5k04ndks02f0fxq-unit-cron.service/cron.service; bad; vendor preset: enabled)
   Active: active (running) since Sun 2016-11-13 02:25:06 UTC; 1min 37s left
  Process: 505 ExecStartPre=/nix/store/8xabcn2f9pq9n7lxvfyffmfq17dzpibg-unit-script/bin/cron-pre-start (code=exited, status=0/SUCCESS)
 Main PID: 544 (cron)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/cron.service
           └─544 /nix/store/da425yixg567w33knnd8w6mxzkc71kzf-cron-4.1/bin/cron -n

Nov 13 02:25:06 nixos systemd[1]: Starting Cron Daemon...
Nov 13 02:25:06 nixos systemd[1]: Started Cron Daemon.

[root@nixos:/]# cat /etc/crontab 
SHELL=/nix/store/28wl3f34vfjpw0y5809bgr6382wqdscf-bash-4.3-p48/bin/bash
PATH=/nix/store/q2caan69wn30vd5bmlgicvvql0rpfr5c-system-path/bin:/nix/store/q2caan69wn30vd5bmlgicvvql0rpfr5c-system-path/sbin

NIX_CONF_DIR=/etc/nix
* * * * * echo echo Hello world > /tmp/cronout


[root@nixos:/]# ls /tmp/
ca-cert.crt  root

```

**Comment by kevincox** [comment] 2016-11-13 10:40
@shlevy @rbvermaa are the last to touch the cron service so maybe they can help.

**Comment by maxxll** [comment] 2017-02-22 14:14
Hello
I have similar problem.

**Comment by mmai** [comment] 2017-03-25 14:29
In `/etc/crontab` you must specify the user executing the command, `echo` is not a valid user.
It works with this line : `* * * * * root echo Hello world > /tmp/cronout`

**Comment by jakubpawlowicz** [comment] 2017-07-28 09:53
@mmai adding `root` saved my day, thanks!

**Comment by gleber** [comment] 2017-11-21 22:43
Looks like the issue was caused by an incorrect configuration provided in `services.cron.systemCronJobs`. Unless we make that option into an attrset, there does not seem to be much to do here. I suggest closing the issue.

**Comment by bjornfor** [comment] 2017-11-22 06:40
@d4g: Can you confirm?

**Comment by d4g** [comment] 2017-11-24 20:02
Hello, thanks for the feedback.
I can confirm, that adding the user fixes the issue.

What still seems to be an issue is adding the correct path for requiered packages in system cron jobs.
It is a possibility to use systemd.timers instead.

Thank you for resolving the issue.

**Closed** 2017-11-24 20:02 UTC
Labels: 0.kind: question, 6.topic: nixos

**Comment by ORESoftware** [comment] 2019-07-08 23:23
Question for nixos ppl, is this enough to schedule cron jobs:

```
  # Enable cron service
  services.cron = {
    enable = true;
    systemCronJobs = [
      "*/5 * * * *      root    date >> /tmp/cron.log"
    ];
  };
```

I put the above in /etc/nixos/configuration.nix, will cron jobs start happening every 30 minutes now?

Or do I need to do more?

**Comment by mixmixmix** [comment] 2019-07-19 20:03
@ORESoftware - it worked for me.

**Comment by eliasp** [comment] 2024-09-10 06:12
Just a note, since many here suggest writing/touching a test file in `/tmp`:

This is a common pitfall in such scenarios, since most systemd services nowadays might be configured with `PrivateTmp=yes`.
This results in files written to `/tmp` not being visible to regular users, since the corresponding service uses a private/namespaced `/tmp` whose actual content is then located in `/tmp/systemd-private-<Boot-ID>-<ServiceName>.service.<ID>`.

So you might end up with a cron successfully writing to `/tmp`, but you continue to assume it's not working, because you can't see the file there.

**Comment by guttermonk** [comment] 2024-10-06 15:59
Based on everything above, shouldn't one of these cron jobs work?

configuration.nix:
```
    cron = {
      enable = true;
      systemCronJobs = [
        "*/5 * * * * guttermonk . /etc/profile; ${pkgs.bash}/bin/bash /home/guttermonk/Programs/hyprpaper-switcher.sh"
        "*/5 * * * * guttermonk . /etc/profile; bash /home/guttermonk/Programs/hyprpaper-switcher.sh"
      ];
    };
```
hyprpaper-switcher.sh:
```
#!/usr/bin/env bash

directory=~/.config/wallpapers
monitor=`hyprctl monitors | grep Monitor | awk '{print $2}'`

if [ -d "$directory" ]; then
    random_background=$(ls $directory/* | shuf -n 1)

    hyprctl hyprpaper unload all
    hyprctl hyprpaper preload $random_background
    hyprctl hyprpaper wallpaper "$monitor, $random_background"

fi
```
