### ISSUE TITLE
cannot install owncloud-client

### ISSUE THREAD

**Issue by AlexanderKoshkarov** [NixOS/nixpkgs#18168] opened 2016-08-31 18:26 UTC
## Issue description
owncloud-client is not building on my system

### Steps to reproduce
add: owncloud-client into /etc/nixos/configuration.nix
then
$ nixos-rebuild switch

###Error msg
`$ sudo nixos-rebuild switch                                                                                                                                  ~
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/ji6wfd3mrqk3kdg6wx3k4s7c9ywzgmn6-owncloud-client-1.7.1.drv
  /nix/store/0h5wd0683rccfmb67p8v2sbhrblr0nzz-system-path.drv
  /nix/store/cbkx76rld38rbhv0fpps0rx3s8ps02w5-dbus-conf.drv
  /nix/store/38jii37a9bqhzf6ikx40xhdk2zsxrv1y-unit-dbus.service.drv
  /nix/store/x9ad25w4j1p0g78pdzvmhicxl4h9h3ni-unit-polkit.service.drv
  /nix/store/8m16vwz3q06m3859lypp4iklb5zs5gz7-system-units.drv
  /nix/store/xvicmlb1qfza9l8wcayqihxfpq20g3yf-etc.drv
  /nix/store/nms28r6xm7z9yj63yv1q1p576flzpxxw-nixos-system-kosh-pc-16.03.1242.c5cbda2.drv
building path(s) ‘/nix/store/z4mxw4m4a5jy08x3q3xjvzq9plgyas5f-owncloud-client-1.7.1’
unpacking sources
unpacking source archive /nix/store/vlky19gcrcvja2mv11cxzxilbk1s86ga-mirall-1.7.1.tar.bz2
source root is mirall-1.7.1
setting SOURCE_DATE_EPOCH to timestamp 1418903149 of file mirall-1.7.1/translations/mirall_zh_TW.ts
patching sources
configuring
fixing cmake files...
cmake flags: -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_BUILD_RPATH=ON -DCMAKE_INSTALL_NAME_DIR=/nix/store/z4mxw4m4a5jy08x3q3xjvzq9plgyas5f-owncloud-client-1.7.1/lib -DCMAKE_INSTALL_PREFIX=/nix/store/z4mxw4m4a5jy08x3q3xjvzq9plgyas5f-owncloud-client-1.7.1  
-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler: /nix/store/m0pbxxvs7zz4ixk4sxyq9shwazpd3kwq-gcc-wrapper-5.3.0/bin/gcc
-- Check for working C compiler: /nix/store/m0pbxxvs7zz4ixk4sxyq9shwazpd3kwq-gcc-wrapper-5.3.0/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /nix/store/m0pbxxvs7zz4ixk4sxyq9shwazpd3kwq-gcc-wrapper-5.3.0/bin/g++
-- Check for working CXX compiler: /nix/store/m0pbxxvs7zz4ixk4sxyq9shwazpd3kwq-gcc-wrapper-5.3.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could not find Qt5, searching for Qt4 instead...
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /nix/store/qcjm58npy1lfvm6vwc12038pcnfm0p80-qt-4.8.7/bin/qmake (found suitable version "4.8.7", minimum required is "4.7.0") 
-- Found PkgConfig: /nix/store/5nvb6aj242dz9p0ijckypmpxn564dnh6-pkg-config-0.29/bin/pkg-config (found version "0.29") 
-- Checking for module 'neon'
--   Found neon, version 0.30.1
-- Found Neon: /nix/store/axxihxx9dsx66aqj0vd2xj2j35zii93l-neon-0.30.1/lib/libneon.so  
-- neon-config executable: /nix/store/axxihxx9dsx66aqj0vd2xj2j35zii93l-neon-0.30.1/bin/neon-config
-- libneon has not been compiled with LFS support, rely on OS
-- Found QtKeychain: /nix/store/xdcszpc44dvzrkm6gf8m4zb0mhbqbmqf-qtkeychain-0.4.0/lib64/libqtkeychain.so  
-- Found INOTIFY: /nix/store/gwl3ppqj4i730nhd4f50ncl5jc4n97ks-glibc-2.23/include  
-- Could NOT find Sphinx (missing:  SPHINX_EXECUTABLE) 
-- Could NOT find PdfLatex (missing:  PDFLATEX_EXECUTABLE) 
-- Checking for module 'sqlite3'
--   Found sqlite3, version 3.9.2
-- Found SQLite3: /nix/store/2q5hjn9dwng5bxg5z4jm9k459m2nwial-sqlite-3.9.2/lib/libsqlite3.so (Required is at least version "3.8.0") 
-- Performing Test WITH_FPIC
-- Performing Test WITH_FPIC - Success
-- Performing Test WITH_STACK_PROTECTOR
-- Performing Test WITH_STACK_PROTECTOR - Success
-- Performing Test WITH_FORTIFY_SOURCE
-- Performing Test WITH_FORTIFY_SOURCE - Success
-- Looking for iconv.h
-- Looking for iconv.h - found
-- Looking for sys/iconv.h
-- Looking for sys/iconv.h - not found
-- Looking for iconv
-- Looking for iconv - found
-- Checking prototype iconv for HAVE_ICONV_CONST - False
-- Found Iconv: /nix/store/gwl3ppqj4i730nhd4f50ncl5jc4n97ks-glibc-2.23/include  
-- Looking for argp.h
-- Looking for argp.h - found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for dlopen in dl
-- Looking for dlopen in dl - found
-- Looking for asprintf
-- Looking for asprintf - found
-- Looking for fnmatch
-- Looking for fnmatch - found
-- Looking for timegm
-- Looking for timegm - found
-- Looking for strerror_r
-- Looking for strerror_r - found
-- Looking for utimes
-- Looking for utimes - found
-- Looking for lstat
-- Looking for lstat - found
-- neon-config executable: /nix/store/axxihxx9dsx66aqj0vd2xj2j35zii93l-neon-0.30.1/bin/neon-config
-- libneon has not been compiled with LFS support, rely on OS
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/build
building
make flags: SHELL=/nix/store/i7hx6w6zy3bv53f2xm1r23ya8qbzn4is-bash-4.3-p42/bin/bash    
Scanning dependencies of target httpbf
[  0%] Building C object csync/src/httpbf/CMakeFiles/httpbf.dir/src/httpbf.c.o
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c: In function 'hbf_splitlist':
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c:45:26: error: ISO C does not support '__FUNCTION__' predefined identifier [-Wpedantic]
         transfer->log_cb(__FUNCTION__, buf, transfer->user_data);    \
                          ^
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c:116:5: note: in expansion of macro 'DEBUG_HBF'
     DEBUG_HBF("File descriptor is invalid.");
     ^
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c:45:26: error: ISO C does not support '__FUNCTION__' predefined identifier [-Wpedantic]
         transfer->log_cb(__FUNCTION__, buf, transfer->user_data);    \
                          ^
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c:121:5: note: in expansion of macro 'DEBUG_HBF'
     DEBUG_HBF("Failed to stat the file descriptor: errno = %d", errno);
     ^
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c:45:26: error: ISO C does not support '__FUNCTION__' predefined identifier [-Wpedantic]
         transfer->log_cb(__FUNCTION__, buf, transfer->user_data);    \
                          ^
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c:134:3: note: in expansion of macro 'DEBUG_HBF'
   DEBUG_HBF("block_size: %" PRId64 " threshold: %" PRId64 " st_size: %" PRId64, transfer->block_size, transfer->threshold, sb.st_size );
   ^
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c:45:26: error: ISO C does not support '__FUNCTION__' predefined identifier [-Wpedantic]
         transfer->log_cb(__FUNCTION__, buf, transfer->user_data);    \
                          ^
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c:159:3: note: in expansion of macro 'DEBUG_HBF'
   DEBUG_HBF("num_blocks: %" PRId64 " rmainder: %" PRId64 " blk_size: %" PRId64, num_blocks, remainder, blk_size );
   ^
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c:45:26: error: ISO C does not support '__FUNCTION__' predefined identifier [-Wpedantic]
         transfer->log_cb(__FUNCTION__, buf, transfer->user_data);    \
                          ^
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c:191:11: note: in expansion of macro 'DEBUG_HBF'
           DEBUG_HBF("created block %d   (start: %" PRId64 "  size: %" PRId64 ")", cnt, block->start, block->size );
           ^
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c: In function '_hbf_dav_request':
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c:45:26: error: ISO C does not support '__FUNCTION__' predefined identifier [-Wpedantic]
         transfer->log_cb(__FUNCTION__, buf, transfer->user_data);    \
                          ^
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c:292:5: note: in expansion of macro 'DEBUG_HBF'
     DEBUG_HBF("Block: %d , Start: %" PRId64 " and Size: %" PRId64 "", blk->seq_number, blk->start, blk->size );
     ^
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c: In function '_hbf_transfer_no_chunk':
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c:45:26: error: ISO C does not support '__FUNCTION__' predefined identifier [-Wpedantic]
         transfer->log_cb(__FUNCTION__, buf, transfer->user_data);    \
                          ^
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c:417:5: note: in expansion of macro 'DEBUG_HBF'
     DEBUG_HBF("HBF: chunking not supported for %s", transfer->url);
     ^
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c: In function 'hbf_transfer':
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c:45:26: error: ISO C does not support '__FUNCTION__' predefined identifier [-Wpedantic]
         transfer->log_cb(__FUNCTION__, buf, transfer->user_data);    \
                          ^
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c:448:9: note: in expansion of macro 'DEBUG_HBF'
         DEBUG_HBF("%s request to %s", verb, transfer->url);
         ^
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c: In function 'hbf_transfer_etag':
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c:45:26: error: ISO C does not support '__FUNCTION__' predefined identifier [-Wpedantic]
         transfer->log_cb(__FUNCTION__, buf, transfer->user_data);    \
                          ^
/tmp/nix-build-owncloud-client-1.7.1.drv-0/mirall-1.7.1/csync/src/httpbf/src/httpbf.c:587:17: note: in expansion of macro 'DEBUG_HBF'
                 DEBUG_HBF( "WARN: etags are not equal in blocks of one single transfer." );
                 ^
csync/src/httpbf/CMakeFiles/httpbf.dir/build.make:62: recipe for target 'csync/src/httpbf/CMakeFiles/httpbf.dir/src/httpbf.c.o' failed
make[2]: *** [csync/src/httpbf/CMakeFiles/httpbf.dir/src/httpbf.c.o] Error 1
CMakeFiles/Makefile2:219: recipe for target 'csync/src/httpbf/CMakeFiles/httpbf.dir/all' failed
make[1]: *** [csync/src/httpbf/CMakeFiles/httpbf.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
builder for ‘/nix/store/ji6wfd3mrqk3kdg6wx3k4s7c9ywzgmn6-owncloud-client-1.7.1.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/0h5wd0683rccfmb67p8v2sbhrblr0nzz-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/nms28r6xm7z9yj63yv1q1p576flzpxxw-nixos-system-kosh-pc-16.03.1242.c5cbda2.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/nms28r6xm7z9yj63yv1q1p576flzpxxw-nixos-system-kosh-pc-16.03.1242.c5cbda2.drv’ failed

`

## Technical details

* System: NixOS: 16.03.1242.c5cbda2 (Emu)
* Nix version: 1.11.2

**Comment by AlexanderKoshkarov** [comment] 2016-09-03 18:24
solve, by moving to unstable channel.

**Comment by fleimgruber** [comment] 2016-09-05 05:50
Duplicate of #17016.

**Comment by bjornfor** [comment] 2016-09-05 06:12
Fixed with 6a4afcded09bb1a0431d1e4568d12abc187ab64e.

**Closed by bjornfor** 2016-09-05 06:12 UTC
