### ISSUE TITLE
kdenlive: Unsupported video codec: libaom-av1

### ISSUE THREAD

**Issue by kevincox** [NixOS/nixpkgs#272526] opened 2023-12-06 18:05 UTC
### Describe the bug
kdenlive can't encode to AV1 due to missing access to libaom-av1

### Steps To Reproduce
1. Start a new project.
2. Project → Render
3. Presets → Ultra-High Definition (4K)

### Expected behavior

WebM-AV1/Opus (libre) is available. instead it is disabled.

### Screenshots
![Screenshot of Render dialog with AV1 disabled.](https://github.com/NixOS/nixpkgs/assets/494012/c1e5e927-f360-4bb4-bac3-9ecada3315e1)

### Additional context

This is strange because the package appears to try an use the `ffmpeg-full`:

https://github.com/NixOS/nixpkgs/blob/91050ea1e57e50388fa87a3302ba12d188ef723a/pkgs/applications/kde/kdenlive/default.nix#L25

I also have ffmpeg installed in my PATH with libaom-av1 support:

<details>
<summary><code>% ffmpeg -help encoder=libaom-av1</code></summary>

```
ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.3.0 (GCC)
  configuration: --disable-static --prefix=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-full-6.0 --target_os=linux --arch=x86_64 --pkg-config=pkg-config --enable-gpl --enable-version3 --disable-nonfree --enable-shared --enable-pic --disable-small --enable-runtime-cpudetect --enable-gray --enable-swscale-alpha --enable-hardcoded-tables --enable-safe-bitstream-reader --enable-pthreads --disable-w32threads --disable-os2threads --enable-network --enable-pixelutils --datadir=/nix/store/k3696rn7b276i7d8yn53w64h6gn2h0n5-ffmpeg-full-6.0-data/share/ffmpeg --enable-ffmpeg --enable-ffplay --enable-ffprobe --bindir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-full-6.0-bin/bin --enable-avcodec --enable-avdevice --enable-avfilter --enable-avformat --enable-avutil --enable-postproc --enable-swresample --enable-swscale --libdir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-full-6.0-lib/lib --incdir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-full-6.0-dev/include --enable-doc --enable-htmlpages --enable-manpages --mandir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-full-6.0-man/share/man --enable-podpages --enable-txtpages --docdir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-full-6.0-doc/share/doc/ffmpeg --enable-alsa --enable-bzlib --enable-libcelt --enable-cuda --enable-cuda-llvm --enable-libdav1d --disable-libfdk-aac --disable-libflite --enable-fontconfig --enable-libfreetype --enable-frei0r --enable-libfribidi --enable-libgme --enable-gnutls --enable-libgsm --enable-ladspa --enable-libmp3lame --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdc1394 --enable-libdrm --enable-iconv --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmysofa --enable-libopus --enable-libplacebo --enable-librsvg --enable-libsrt --enable-libssh --disable-libtensorflow --enable-libtheora --enable-libv4l2 --enable-v4l2-m2m --enable-vaapi --enable-vdpau --enable-libvorbis --enable-libvmaf --enable-libvpx --enable-libwebp --enable-xlib --enable-libxcb --enable-libxcb-shm --enable-libxcb-xfixes --enable-libxcb-shape --enable-libxml2 --enable-lzma --enable-cuvid --enable-nvdec --enable-nvenc --enable-openal --enable-opencl --enable-libopencore-amrnb --disable-opengl --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-libpulse --enable-librav1e --enable-libsvtav1 --disable-librtmp --enable-sdl2 --enable-libsoxr --enable-libspeex --enable-libvidstab --enable-libvo-amrwbenc --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-libzimg --enable-zlib --enable-vulkan --enable-libglslang --enable-libsmbclient --disable-debug --enable-optimizations --disable-extra-warnings --disable-stripping
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Encoder libaom-av1 [libaom AV1]:
    General capabilities: dr1 delay threads 
    Threading capabilities: other
    Supported pixel formats: yuv420p yuv422p yuv444p gbrp yuv420p10le yuv422p10le yuv444p10le yuv420p12le yuv422p12le yuv444p12le gbrp10le gbrp12le gray gray10le gray12le
libaom-av1 encoder AVOptions:
  -cpu-used          <int>        E..V....... Quality/Speed ratio modifier (from 0 to 8) (default 1)
  -auto-alt-ref      <int>        E..V....... Enable use of alternate reference frames (2-pass only) (from -1 to 2) (default -1)
  -lag-in-frames     <int>        E..V....... Number of frames to look ahead at for alternate reference frame selection (from -1 to INT_MAX) (default -1)
  -arnr-max-frames   <int>        E..V....... altref noise reduction max frame count (from -1 to INT_MAX) (default -1)
  -arnr-strength     <int>        E..V....... altref noise reduction filter strength (from -1 to 6) (default -1)
  -aq-mode           <int>        E..V....... adaptive quantization mode (from -1 to 4) (default -1)
     none            0            E..V....... Aq not used
     variance        1            E..V....... Variance based Aq
     complexity      2            E..V....... Complexity based Aq
     cyclic          3            E..V....... Cyclic Refresh Aq
  -error-resilience  <flags>      E..V....... Error resilience configuration (default 0)
     default                      E..V....... Improve resiliency against losses of whole frames
  -crf               <int>        E..V....... Select the quality for constant quality mode (from -1 to 63) (default -1)
  -static-thresh     <int>        E..V....... A change threshold on blocks below which they will be skipped by the encoder (from 0 to INT_MAX) (default 0)
  -drop-threshold    <int>        E..V....... Frame drop threshold (from INT_MIN to INT_MAX) (default 0)
  -denoise-noise-level <int>        E..V....... Amount of noise to be removed (from -1 to INT_MAX) (default -1)
  -denoise-block-size <int>        E..V....... Denoise block size  (from -1 to INT_MAX) (default -1)
  -undershoot-pct    <int>        E..V....... Datarate undershoot (min) target (%) (from -1 to 100) (default -1)
  -overshoot-pct     <int>        E..V....... Datarate overshoot (max) target (%) (from -1 to 1000) (default -1)
  -minsection-pct    <int>        E..V....... GOP min bitrate (% of target) (from -1 to 100) (default -1)
  -maxsection-pct    <int>        E..V....... GOP max bitrate (% of target) (from -1 to 5000) (default -1)
  -frame-parallel    <boolean>    E..V....... Enable frame parallel decodability features (default auto)
  -tiles             <image_size> E..V....... Tile columns x rows
  -tile-columns      <int>        E..V....... Log2 of number of tile columns to use (from -1 to 6) (default -1)
  -tile-rows         <int>        E..V....... Log2 of number of tile rows to use (from -1 to 6) (default -1)
  -row-mt            <boolean>    E..V....... Enable row based multi-threading (default auto)
  -enable-cdef       <boolean>    E..V....... Enable CDEF filtering (default auto)
  -enable-global-motion <boolean>    E..V....... Enable global motion (default auto)
  -enable-intrabc    <boolean>    E..V....... Enable intra block copy prediction mode (default auto)
  -enable-restoration <boolean>    E..V....... Enable Loop Restoration filtering (default auto)
  -usage             <int>        E..V....... Quality and compression efficiency vs speed trade-off (from 0 to INT_MAX) (default good)
     good            0            E..V....... Good quality
     realtime        1            E..V....... Realtime encoding
     allintra        2            E..V....... All Intra encoding
  -tune              <int>        E..V....... The metric that the encoder tunes for. Automatically chosen by the encoder by default (from -1 to 1) (default -1)
     psnr            0            E..V.......
     ssim            1            E..V.......
  -still-picture     <boolean>    E..V....... Encode in single frame mode (typically used for still AVIF images). (default false)
  -enable-rect-partitions <boolean>    E..V....... Enable rectangular partitions (default auto)
  -enable-1to4-partitions <boolean>    E..V....... Enable 1:4/4:1 partitions (default auto)
  -enable-ab-partitions <boolean>    E..V....... Enable ab shape partitions (default auto)
  -enable-angle-delta <boolean>    E..V....... Enable angle delta intra prediction (default auto)
  -enable-cfl-intra  <boolean>    E..V....... Enable chroma predicted from luma intra prediction (default auto)
  -enable-filter-intra <boolean>    E..V....... Enable filter intra predictor (default auto)
  -enable-intra-edge-filter <boolean>    E..V....... Enable intra edge filter (default auto)
  -enable-smooth-intra <boolean>    E..V....... Enable smooth intra prediction mode (default auto)
  -enable-paeth-intra <boolean>    E..V....... Enable paeth predictor in intra prediction (default auto)
  -enable-palette    <boolean>    E..V....... Enable palette prediction mode (default auto)
  -enable-flip-idtx  <boolean>    E..V....... Enable extended transform type (default auto)
  -enable-tx64       <boolean>    E..V....... Enable 64-pt transform (default auto)
  -reduced-tx-type-set <boolean>    E..V....... Use reduced set of transform types (default auto)
  -use-intra-dct-only <boolean>    E..V....... Use DCT only for INTRA modes (default auto)
  -use-inter-dct-only <boolean>    E..V....... Use DCT only for INTER modes (default auto)
  -use-intra-default-tx-only <boolean>    E..V....... Use default-transform only for INTRA modes (default auto)
  -enable-ref-frame-mvs <boolean>    E..V....... Enable temporal mv prediction (default auto)
  -enable-reduced-reference-set <boolean>    E..V....... Use reduced set of single and compound references (default auto)
  -enable-obmc       <boolean>    E..V....... Enable obmc (default auto)
  -enable-dual-filter <boolean>    E..V....... Enable dual filter (default auto)
  -enable-diff-wtd-comp <boolean>    E..V....... Enable difference-weighted compound (default auto)
  -enable-dist-wtd-comp <boolean>    E..V....... Enable distance-weighted compound (default auto)
  -enable-onesided-comp <boolean>    E..V....... Enable one sided compound (default auto)
  -enable-interinter-wedge <boolean>    E..V....... Enable interinter wedge compound (default auto)
  -enable-interintra-wedge <boolean>    E..V....... Enable interintra wedge compound (default auto)
  -enable-masked-comp <boolean>    E..V....... Enable masked compound (default auto)
  -enable-interintra-comp <boolean>    E..V....... Enable interintra compound (default auto)
  -enable-smooth-interintra <boolean>    E..V....... Enable smooth interintra mode (default auto)
  -aom-params        <dictionary> E..V....... Set libaom options using a :-separated list of key=value pairs
```

</details>

### Notify maintainers

@turion 

### Metadata

The exact package I am using is `/nix/store/qfd2d8c3s42j83ffhlq8wpg4y5hq95w2-kdenlive-23.08.3` which is available in https://cache.nixos.org.

`% nix-shell -p nix-info --run "nix-info -m"`
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.64, NixOS, 24.05 (Uakari), 24.05pre555097.91050ea1e57e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by turion** [comment] 2023-12-07 09:38
Can reproduce.

**Comment by turion** [comment] 2023-12-07 10:59
Is this related to https://forum.kde.org/viewtopic.php%3Ff=272&t=172796.html ?

**Comment by turion** [comment] 2023-12-07 11:12
I'm not sure, but it might be that the encoding libraries are actually not limited by the `ffmpeg` that `kdenlive` uses, but by `mlt`, which still uses `ffmpeg_4` (and not the full version).

**Comment by turion** [comment] 2023-12-07 11:31
> I'm not sure, but it might be that the encoding libraries are actually not limited by the `ffmpeg` that `kdenlive` uses, but by `mlt`, which uses `ffmpeg` and not `ffmpeg-full`.

Yes, this seems to be the issue.

**Comment by ShalokShalom** [comment] 2024-02-14 20:59
Hi there :)

I updated my channels and then rebuild, and still haven't gotten this fix. 
It still shows the same error, as in the original screenshot. 

I even added libaom by hand, still the same.

**Comment by turion** [comment] 2024-02-15 10:21
@ShalokShalom Which channels have you updated, and to which versions?

**Comment by ShalokShalom** [comment] 2024-02-15 19:14
23.11 and with nix-channel --update

**Comment by turion** [comment] 2024-02-16 09:09
Ah ok, as you see the issue was reported after release of 23.11, so it is fixed only in `nixos-unstable` (and the next release).

**Comment by devurandom** [comment] 2024-04-28 20:56
I am on NixOS unstable (`24.05.20240425.7bb2ccd`) and Kdenlive 24.02.2 still reports "Unsupported video codec: libaom-av1".

**Comment by kevincox** [comment] 2024-04-28 20:59
Yes, it seems to have regressed for me as well.

**Comment by kevincox** [comment] 2024-04-28 22:37
I can't easily bisect the kdenlive derivation itself as it fails to load pipewire shared libraries probably due to skew between my base system and the built kdenlive.

However I ran a bisection on `mlt` with the `ffmpeg-full` override and found e92546a987a7667ff12aa138f673f495ec3fb8a6 to be the culprit. At first glance this seems like it should be unrelated.

<details><summary>bisect script</summary>

```zsh
#!/usr/bin/env zsh

set -ux

nix-build -E '
	let
		inherit (import ./. {}) pkgs;
	in
		pkgs.mlt.override { ffmpeg = pkgs.ffmpeg-full; }
' || exit 125
codecs=$(result/bin/melt -query video_codecs)
[[ $? = 0 ]] || exit 125

grep -wF libaom-av1 <<<$codecs
```

</details>

**Comment by kevincox** [comment] 2024-04-28 22:46
So before this change `mlt` depends on both ffmpeg 4 and 6. After this change only 6 is in the dependency graph. Maybe 4 was somehow being used and that is needed for `libaom-av1` to work?

**Comment by kevincox** [comment] 2024-04-28 22:49
`pkgs.mlt.override { ffmpeg = pkgs.ffmpeg_4-full; }` does have libaom-av1. So presumably something isn't working with ffmpeg 6. Reverting to 4 for now is a possible solution but likely has a lot of downsides as well.

**Comment by kevincox** [comment] 2024-04-28 22:52
It is worth noting that ffmpeg 6 does have libaom support. So it is possibly an incompatibility between mlt and ffmpeg.

```sh
% nix-shell -p ffmpeg-full --run 'ffmpeg -codecs | grep -i aom'
ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.2.0 (GCC)
  configuration: --disable-static --prefix=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-full-6.1.1 --target_os=linux --arch=x86_64 --pkg-config=pkg-config --enable-gpl --enable-version3 --disable-nonfree --disable-static --enable-shared --enable-pic --disable-thumb --disable-small --enable-runtime-cpudetect --enable-gray --enable-swscale-alpha --enable-hardcoded-tables --enable-safe-bitstream-reader --enable-pthreads --disable-w32threads --disable-os2threads --enable-network --enable-pixelutils --datadir=/nix/store/4mzq505wb9g0wrpvja0ym75q1yrsqijw-ffmpeg-full-6.1.1-data/share/ffmpeg --enable-ffmpeg --enable-ffplay --enable-ffprobe --bindir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-full-6.1.1-bin/bin --enable-avcodec --enable-avdevice --enable-avfilter --enable-avformat --enable-avutil --enable-postproc --enable-swresample --enable-swscale --libdir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-full-6.1.1-lib/lib --incdir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-full-6.1.1-dev/include --enable-doc --enable-htmlpages --enable-manpages --mandir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-full-6.1.1-man/share/man --enable-podpages --enable-txtpages --docdir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-full-6.1.1-doc/share/doc/ffmpeg --enable-alsa --enable-libaom --disable-appkit --enable-libaribcaption --enable-libass --disable-audiotoolbox --disable-avfoundation --enable-libbluray --enable-libbs2b --enable-bzlib --enable-libcaca --enable-libcelt --enable-chromaprint --disable-coreimage --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-libdav1d --enable-libdc1394 --enable-libdrm --disable-libfdk-aac --enable-ffnvcodec --enable-libflite --enable-fontconfig --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libfribidi --enable-libgme --enable-gnutls --enable-libgsm --enable-libharfbuzz --enable-iconv --enable-libjack --enable-ladspa --enable-lzma --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-nvdec --enable-nvenc --enable-openal --enable-opencl --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-opengl --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librav1e --enable-librtmp --enable-libsmbclient --enable-sdl2 --enable-libshaderc --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-librsvg --enable-libsvtav1 --disable-libtensorflow --enable-libtheora --enable-libv4l2 --enable-v4l2-m2m --enable-vaapi --enable-vdpau --disable-libvpl --disable-videotoolbox --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-vulkan --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxcb --enable-libxcb-shape --enable-libxcb-shm --enable-libxcb-xfixes --enable-xlib --enable-libxml2 --enable-libxvid --enable-libzimg --enable-zlib --enable-libzmq --disable-debug --enable-optimizations --disable-extra-warnings --disable-stripping
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
 DEV.L. av1                  Alliance for Open Media AV1 (decoders: libdav1d libaom-av1 av1 av1_cuvid av1_qsv) (encoders: libaom-av1 librav1e libsvtav1 av1_nvenc av1_vaapi)
```

**Comment by kevincox** [comment] 2024-04-28 22:54
I do see that we are linking two versions of ffmpeg. -full and non-full.

So possibly what is happening is that when the other version was 4 it wasn't getting used, so full was. But now that both are 6 the wrong one happens to get used.

**Comment by kevincox** [comment] 2024-04-28 23:03
```patch
diff --git a/pkgs/development/libraries/mlt/default.nix b/pkgs/development/libraries/mlt/default.nix
index ded5a5990a60..2b20bbea4d62 100644
--- a/pkgs/development/libraries/mlt/default.nix
+++ b/pkgs/development/libraries/mlt/default.nix
@@ -73,7 +73,7 @@ stdenv.mkDerivation rec {
     libvorbis
     libxml2
     movit
-    opencv4
+    (opencv4.override { enableFfmpeg = false; })
     rtaudio
     rubberband
     sox
```

This fixes the issue. Maybe the best solution is updating `opencv4` to use the same `ffmpeg` as `mlt`. However this makes me think that this isn't the best solution in general.

**Comment by kevincox** [comment] 2024-04-28 23:22
Created https://github.com/NixOS/nixpkgs/pull/307581 to propagate the ffmpeg version through `mlt`.

I don't know if this fix is the most maintainable solution, but it solves this problem and doesn't harm maintainability.

**Closed** 2024-05-20 15:09 UTC
Labels: 0.kind: bug
