### ISSUE TITLE
Electron app (Obsidian) launches black screen

### ISSUE THREAD

**Issue by Halfarne** [NixOS/nixpkgs#249287] opened 2023-08-15 07:44 UTC
### Describe the bug
Obsidian app can't find some shared binaries in `/run/opengl-driver/lib/dri/`

### Steps To Reproduce
1. add obsidian to configuration.nix packages
2. add `hardware.nvidia.modesetting.enable = true;` to configuration.nix
3. launching obsidian:
```console
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open nvidia-drm: /run/opengl-driver/lib/dri/nvidia-drm_dri.so: cannot open shared object file: Permission denied (search paths /run/opengl-driver/lib/dri, suffix _dri)
MESA-LOADER: failed to open zink: /run/opengl-driver/lib/dri/zink_dri.so: cannot open shared object file: Permission denied (search paths /run/opengl-driver/lib/dri, suffix _dri)
MESA-LOADER: failed to open kms_swrast: /run/opengl-driver/lib/dri/kms_swrast_dri.so: cannot open shared object file: Permission denied (search paths /run/opengl-driver/lib/dri, suffix _dri)
MESA-LOADER: failed to open swrast: /run/opengl-driver/lib/dri/swrast_dri.so: cannot open shared object file: Permission denied (search paths /run/opengl-driver/lib/dri, suffix _dri)
2023-08-15 06:59:34 Success.
2023-08-15 06:59:34 Latest version is 1.3.7
2023-08-15 06:59:34 App is up to date.

```

### Expected behavior
When launching the obsidian it launches, but it shows only black screen

### Notify maintainers
@qbit 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
~ > nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.1-zen1, NixOS, 23.05 (Stoat), 23.05.2561.9607b9149c9d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05"`
 - channels(halfarne): `"nixos"`
 - channels(hm): `"home-manager-22.11.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by qbit** [comment] 2023-08-17 12:54
"Permission denied" makes me think the user you are running obsidian as needs to be in an extra group.

What are the permissions on `/run/opengl-driver/lib/dri/` ? What's reported by `id` when run as your user?

**Comment by qbit** [comment] 2023-08-17 13:39
NM. it seems to be related to this: https://github.com/NixOS/nixpkgs/issues/244742

**Comment by qbit** [comment] 2023-08-17 13:53
Might try `rm -rf ~/.config/obsidian/GPUCache/` ?

**Comment by Halfarne** [comment] 2023-08-17 14:59
After removing the `~/.config/obsidian/GPUCache/` it still didn't work
I tried to run obsidian with `--disable-gpu` mentioned as a workaround in #244742 in https://discussion.fedoraproject.org/t/chromium-based-browsers-display-garbled-web-pages-after-mesa-is-updated/83438 and it worked.

**Comment by Ilirski** [comment] 2023-08-22 15:37
This is also related to #224332.

**Comment by SuperSandro2000** [comment] 2023-09-27 21:51
closing as dupe of the linked issues

**Closed by SuperSandro2000** 2023-09-27 21:51 UTC
Labels: 0.kind: bug
