### ISSUE TITLE
Build failure: nvidia_x11_latest

### ISSUE THREAD

**Issue by Aleod-m** [NixOS/nixpkgs#286313] opened 2024-02-04 15:45 UTC
### Steps To Reproduce

1. build the package from the branch "nixpkgs/nixos-23.11"

### Build log

```
 $> nixos-rebuild build  --flake .#nixos-pc
building the system configuration...
warning: Git tree '/media/Drive2/Documents/dev/nix/nix-machine' is dirty
error: builder for '/nix/store/4n0fb6y3d1vyqbgnpflwm7q69s92dzn2-nvidia-x11-545.29.02-6.1.76.drv' failed with exit code 2;
       last 10 log lines:
       >   LD [M]  /build/NVIDIA-Linux-x86_64-545.29.02/kernel/nvidia-peermem.o
       >   LD [M]  /build/NVIDIA-Linux-x86_64-545.29.02/kernel/nvidia-drm.o
       >   MODPOST /build/NVIDIA-Linux-x86_64-545.29.02/kernel/Module.symvers
       > ERROR: modpost: GPL-incompatible module nvidia.ko uses GPL-only symbol '__rcu_read_lock'
       > ERROR: modpost: GPL-incompatible module nvidia.ko uses GPL-only symbol '__rcu_read_unlock'
       > make[3]: *** [/nix/store/kpwm0vhi68njzhcqfbym2jj4jp9h740x-linux-6.1.76-dev/lib/modules/6.1.76/source/scripts/Makefile.modpost:126: /build/NVIDIA-Linux-x86_64-545.29.02/kernel/Module.symvers] Error 1
       > make[2]: *** [/nix/store/kpwm0vhi68njzhcqfbym2jj4jp9h740x-linux-6.1.76-dev/lib/modules/6.1.76/source/Makefile:1966: modpost] Error 2
       > make[1]: *** [Makefile:238: __sub-make] Error 2
       > make[1]: Leaving directory '/nix/store/kpwm0vhi68njzhcqfbym2jj4jp9h740x-linux-6.1.76-dev/lib/modules/6.1.76/source'
       > make: *** [Makefile:82: modules] Error 2
       For full logs, run 'nix log /nix/store/4n0fb6y3d1vyqbgnpflwm7q69s92dzn2-nvidia-x11-545.29.02-6.1.76.drv'.
error: 1 dependencies of derivation '/nix/store/a3mjd9n2cynryq5ggg0z8r1mq4jnra74-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ml17cmgv4aixkpqb8fc4ffrkfzljb76m-linux-6.1.76-modules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/554miy4j8drx73xgh6i5ncak476wwbac-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/b803hk6gkchr9cajixl1fff8v2a73fcv-nixos-system-nixos-pc-23.11.20240201.25e3d4c.drv' failed to build
```

### Additional context
Nvidia config module: https://github.com/Aleod-m/nix-machine/blob/b23ce3b58f45be7ad6f83ee1c2eba64acc78bd27/machines/modules/nvidia.nix
Hardware config: https://github.com/Aleod-m/nix-machine/blob/b23ce3b58f45be7ad6f83ee1c2eba64acc78bd27/machines/nixos-pc/hardware.nix

### Notify maintainers
@jonringer @Kiskae @edwtjo

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.65, NixOS, 23.11 (Tapir), 23.11.20231207.b4372c4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Kiskae** [comment] 2024-02-04 15:47
Will be fixed when #286084 makes its way into the cache.

**Comment by deviantsemicolon** [comment] 2024-02-04 22:01
Also getting build issues for nvidia 535 drivers. Will those be fixed as well?

**Comment by deviantsemicolon** [comment] 2024-02-04 22:01
I'm on nixos-unstable

**Comment by Kiskae** [comment] 2024-02-04 22:08
I believe I've fixed all the affected drivers that we officially publish for 23.11 and unstable, the cache just needs time to catch up to those commits.

**Comment by GGG-KILLER** [comment] 2024-02-05 00:41
If anyone on unstable wants to check whether they'll be able to build or not, check https://nixpk.gs/pr-tracker.html?pr=286058

**Comment by BirdeeHub** [comment] 2024-02-05 09:46
Not a permenant solution but lmaoooo it works

The rest of my stuff is on nixos-unstable but I pinned my kernel to master until this is fixed XD

I imported nixpkgs-unstable in flake inputs and then did this XD

```nix
  nixpkgs.overlays = [ (self: super: (let
    master_pkgs = import inputs.nixpkgs_master {
      inherit (self) system;
      config.allowUnfree = true;
    };
  in {
    linuxPackages_latest = master_pkgs.linuxPackages_latest;
  })) ];
  hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.stable;
  boot.kernelPackages = pkgs.linuxPackages_latest;

```

**Comment by BirdeeHub** [comment] 2024-02-05 12:59
So, thats what I put in my comment.

The issue is I dont know which kernel packages were patched. I need to check. I know how to override specific kernel modules as of an hour ago, but now I need to know which specifically were patched so that I can override only the relevant ones

**Comment by Kreyren** [comment] 2024-02-05 23:07
N$ said that they will fix that in next release and patching that to work is more than likely a license violation

https://forums.developer.nvidia.com/t/linux-6-7-3-545-29-06-550-40-07-error-modpost-gpl-incompatible-module-nvidia-ko-uses-gpl-only-symbol-rcu-read-lock/280908/19

**Comment by Kreyren** [comment] 2024-02-06 02:02
> How long till they fix it then? Will this patch continue to work in the meantime? -- @BirdeeHub (https://github.com/NixOS/nixpkgs/issues/286313#issuecomment-1928550187)

I'm worry that this is a case of nvidia fixing it whenever they feel like it while ignoring the urgency

**Closed** 2024-02-06 07:23 UTC
Labels: 0.kind: build failure
