### ISSUE TITLE
Build failure: libpng

### ISSUE THREAD

**Issue by zeuner** [NixOS/nixpkgs#278130] opened 2024-01-01 20:23 UTC
### Steps To Reproduce

1. `nix-build --option substitute false -A libpng`

### Build log

```
this derivation will be built:
  /nix/store/hziy2dc91s6jqn00zsv1dqzcgwr8qs3j-libpng-apng-1.6.40.drv
building '/nix/store/hziy2dc91s6jqn00zsv1dqzcgwr8qs3j-libpng-apng-1.6.40.drv'...
Running phase: unpackPhase
unpacking source archive /nix/store/jpqz1p52xw3jlhc8w143v92k0iaar2i4-libpng-1.6.40.tar.xz
do not know how to unpack source archive /nix/store/jpqz1p52xw3jlhc8w143v92k0iaar2i4-libpng-1.6.40.tar.xz
error: builder for '/nix/store/hziy2dc91s6jqn00zsv1dqzcgwr8qs3j-libpng-apng-1.6.40.drv' failed with exit code 1
```

### Additional context

This happened on recent checkouts of `nixpkgs` `master`.

### Notify maintainers

Will do.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.0-8-amd64, Ubuntu, 20.04.6 LTS (Focal Fossa), nobuild`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.16.1`
 - nixpkgs: `/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by arthsmn** [comment] 2024-01-01 22:36
Could not reproduce. It unpacks and builds just fine on my x86_64-linux machine.

**Comment by zeuner** [comment] 2024-01-01 22:47
Just pulled `master` again, but it still fails. If you wish to close, please provide instructions to build `libpng`.

**Comment by arthsmn** [comment] 2024-01-01 22:56
> Just pulled `master` again, but it still fails. If you wish to close, please provide instructions to build `libpng`, or for further debugging issue.

I just used the command you used. Can you clear your nix-store? You might have downloaded a broken archive and it's not being recognized.

**Comment by zeuner** [comment] 2024-01-01 23:07
> > Just pulled `master` again, but it still fails. If you wish to close, please provide instructions to build `libpng`, or for further debugging issue.
> 
> I just used the command you used. Also, the extractor is able to extract .tar.xz archives.
>

Sure, but as far as I understand `nix`, these things are supposed to be reproducible on different machines. So I do hope it's possible to find out what causes the error.

> Can you clear your nix-store? You might have downloaded a broken archive and it's not being recognized.

```
$ nix-store --delete /nix/store/jpqz1p52xw3jlhc8w143v92k0iaar2i4-libpng-1.6.40.tar.xz
1 store paths deleted, 0.97 MiB freed
$ nix-build --option substitute false -A libpng
these 2 derivations will be built:
  /nix/store/h3i4z4dym34jscn0jcixba478v2w00wx-libpng-1.6.40.tar.xz.drv
  /nix/store/hziy2dc91s6jqn00zsv1dqzcgwr8qs3j-libpng-apng-1.6.40.drv
building '/nix/store/h3i4z4dym34jscn0jcixba478v2w00wx-libpng-1.6.40.tar.xz.drv'...

trying https://downloads.sourceforge.net/libpng/libpng-1.6.40.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   382  100   382    0     0    598      0 --:--:-- --:--:-- --:--:--   598
100   363  100   363    0     0    137      0  0:00:02  0:00:02 --:--:--   364
100  997k  100  997k    0     0   367k      0  0:00:02  0:00:02 --:--:--  367k
building '/nix/store/hziy2dc91s6jqn00zsv1dqzcgwr8qs3j-libpng-apng-1.6.40.drv'...
Running phase: unpackPhase
unpacking source archive /nix/store/jpqz1p52xw3jlhc8w143v92k0iaar2i4-libpng-1.6.40.tar.xz
do not know how to unpack source archive /nix/store/jpqz1p52xw3jlhc8w143v92k0iaar2i4-libpng-1.6.40.tar.xz
error: builder for '/nix/store/hziy2dc91s6jqn00zsv1dqzcgwr8qs3j-libpng-apng-1.6.40.drv' failed with exit code 1
```

Doesn't seem to change anything.

**Comment by zeuner** [comment] 2024-01-01 23:32
> Also, the extractor is able to extract .tar.xz archives.

Indeed I see other packages (e.g. `gcc`) that don't complain about their `.tar.xz` source from `fetchurl`. I've yet to see whether I see any difference that could explain the erroneous result.

**Comment by vcunat** [comment] 2024-01-02 18:35
I've seen this happening with libpng on hydra.nixos.org as well, sometime in the past few weeks.  No idea how it happens, though.

**Comment by marmolak** [comment] 2024-01-16 20:07
Hello. I'm trying to build image (cross compile and create image for SD card) for rpizero w, and it seems like build process nixos machine (23.11) from aws ends with same error: 

error: builder for '/nix/store/vy12b7lmf3y548whsjfv3m81vlm8g2zz-libpng-apng-armv6l-unknown-linux-gnueabihf-1.6.40.drv' failed with exit code 1;
       last 3 log lines:
       > unpacking sources
       > unpacking source archive /nix/store/jpqz1p52xw3jlhc8w143v92k0iaar2i4-libpng-1.6.40.tar.xz
       > do not know how to unpack source archive /nix/store/jpqz1p52xw3jlhc8w143v92k0iaar2i4-libpng-1.6.40.tar.xz
       For full logs, run 'nix log /nix/store/vy12b7lmf3y548whsjfv3m81vlm8g2zz-libpng-apng-armv6l-unknown-linux-gnueabihf-1.6.40.drv'.

**Comment by vcunat** [comment] 2024-01-17 17:55
On Hydra it always gets worked around by retrying.

**Comment by zeuner** [comment] 2024-01-17 18:44
> On Hydra it always gets worked around by retrying.

It reproducibly fails for me when retrying to `nix-build` `libpng`. Does Hydra refresh anything else when retrying?

**Comment by nsaunders** [comment] 2024-01-20 23:32
Consistently fails for me. Really wish the issue hadn't been closed.

**Comment by vcunat** [comment] 2024-01-21 08:53
The issue is open, but that by itself doesn't make a big difference IMO.

**Comment by hannes-hochreiner** [comment] 2024-02-04 07:25
I ran into the same problem trying to cross-compile an sd-card image for a Raspberry Pi Zero W. I solved the problem by writing an overlay using the `.tar.gz` packaged sources.

`(final: prev: {libpng = prev.libpng.overrideAttrs ( old: { src = prev.fetchurl {
      url = "mirror://sourceforge/libpng/libpng-1.6.40.tar.gz";
      hash = "sha256-j3ILNjqghoPJvypWMjb0UxOvLFXVQrVIGuF92NGDu0I=";
    };});})`

I have not created a PR making the same changes. However, it should be easy to do.

**Comment by vcunat** [comment] 2024-02-04 08:15
Well, was it really a solution.  Because for me it gets solved by retrying the unchanged derivation on the same build machine...

**Comment by hannes-hochreiner** [comment] 2024-02-04 11:01
With "solved" I meant that it solved my immediate problem of getting the library to build. I did not do a full root cause analysis for want of time and ability. So, I am happy to call it a workaround.

For context: my aim was to prepare an SD-card image. The build failed reproducibly due to the issue described in the ticket. Other packages in the same format presumably built without an issue. This led me to believe that the toolchain is not the problem. Hence, I tried with a different package format and it worked. My hope is that it would also work for other people, which we may be able to judge by future comments/reactions in this thread.

I have since downloaded the source package in xz format and tested it with "xz -t" with no issues coming up. I also tried to unpack it on the desktop, which worked just fine. So, it might still be a toolchain problem or some issue that only comes up with certain packages.

Your report that it sometimes works for you and sometimes not without changing anything worries me. I am working with Nix and NixOS mainly for its reproducibility. Unreproducible results in building the package would warrant their own bug report from my point of view, unless they are for well understood reasons. However, I do not see this behavior in the environments I have tested.

Anyways, thank you for your work as maintainer!

**Comment by vcunat** [comment] 2024-02-04 11:05
Yes, it's weird.  And we have no reports of this happening for a different package than libpng.

**Comment by vcunat** [comment] 2024-02-05 08:29
Actually why not try switching to .tar.gz.  Disadvantages are negligible, and there seems to be a decent chance of working around this annoying issue.

**Comment by zeuner** [comment] 2024-02-05 22:47
Turns out that `xz` is killed by `SIGPIPE` for some reason, making the unpack hook fail.

It can also be worked around keeping the `tar.xz` archive by decompressing into a file before untaring: (https://github.com/NixOS/nixpkgs/pull/286579/files, https://github.com/zeuner/nixpkgs/blob/xz-unpack-issue-workaround/pkgs/development/libraries/libpng/setup-xz-workaround.sh#L1051).

**Comment by zeuner** [comment] 2024-02-05 22:50
> Yes, it's weird. And we have no reports of this happening for a different package than libpng, even though `.tar.xz` is very common in nixpkgs.

Actually, while it seems to happen very seldomly, there is at least one issue that looks very similar: https://github.com/NixOS/nixpkgs/issues/20950 (also `tar.xz`).

**Comment by zeuner** [comment] 2024-02-05 22:57
The `tar.gz` workaround works for me (as does the intermediary file workaround). Considering that this looks like it can blow up randomly on any other packages that use `tar.xz` in the future, I'd suggest we try to investigate and fix it. I have one `nixpkgs` setup here where it reproducibly fails, so I could help testing.

**Comment by vcunat** [comment] 2024-02-06 06:16
SIGPIPE would probably mean that the `tar` part exited.

**Comment by zeuner** [comment] 2024-02-06 09:56
> SIGPIPE would probably mean that the `tar` part exited.

Presuming that `tar` knows when everything is ok, it should then suffice to disregard the error code from the `xz` invocation (https://github.com/zeuner/nixpkgs/blob/xz-unpack-issue-workaround/pkgs/development/libraries/libpng/setup-xz-workaround.sh#L1051).

**Comment by vcunat** [comment] 2024-02-06 10:21
🤔 yes, I suppose such a race might be possible.  `xz` writing all that's needed into the pipe, then `tar` recognizing that it's the whole archive and finishing (and thus closing the pipe between them), then `xz` getting SIGPIPE and failing, even though it perhaps has nothing else to write.  When your CPUs are not fully utilized, `xz` would more likely manage to finish fast enough to avoid the signal.

**Closed** 2024-02-24 20:38 UTC
Labels: 0.kind: build failure
