### ISSUE TITLE
The configuration.nix man page requires very wide terminals

### ISSUE THREAD

**Issue by viric** [NixOS/nixpkgs#4538] opened 2014-10-15 08:03 UTC
With a 90-column terminal (half my screen width), "man configuration.nix" fills the screen with stderr warnings, that break completely the 'less' painting of the terminal. Lines are like this:
   <standard input>:10480: warning [p 2, 163.7i]: can't break line

I think it's related to the very long strings of nix file names. In MySQL they got this problem, and they managed to use some docbook tags that improved that: http://bugs.mysql.com/bug.php?id=45484

They say: "After further investigation, I think the source of the problem is that <entry> is subject to "pernicious mixed content." By wrapping the affected cell within <para> tags, better word wrapping occurs and improves the man page output."

**Comment by matthiasbeyer** [comment] 2015-01-10 12:11
Can you provide some more details to reproduce? I can't reproduce this either in a Konsole nor in a TTY - I'm on nixos-unstable, though!

**Comment by zimbatm** [comment] 2016-02-26 11:26
Closing to keep the number of open issues down. You're welcome to re-open with a reproducible case obviously !

**Comment by viric** [comment] 2016-02-26 11:30
On 15.09, xterm on 81 columns, I see full of that. No idea of master.

**Comment by viric** [comment] 2016-02-26 11:55
tv on irc reports to use this, to avoid the noise: https://gist.github.com/4z3/afac172c65d8775153c4

**Comment by 4z3** [comment] 2016-02-26 12:14
I can reproduce the warnings like this:
```console
$ nroff -mandoc /run/current-system/sw/share/man/man5/configuration.nix >/dev/null
/run/current-system/sw/share/man/man5/configuration.nix.5:1206: warning [p 13, 7.7i]: can't break line
...
```

The workaround adds `-Wbreak` to man's nroff command line, which mutes that warning. I'm not sure muting warnings should be the default for NixOS (or nixpkgs's man) because the error still exists (i.e. lines couldn't be wrapped). Instead, maybe the manpage generation can be tuned.

**Comment by pSub** [comment] 2016-02-26 12:17
I can definitely reproduce the error, too. No matter on which version and since a long time. I also investigated rather deeply on how to fix this problem starting from the MySQL Bug linked above. However, I was not able to find a solution that worked. But I don't have much experience in this area so that doesn't mean much. Maybe I can give it an other try at the weekend.

**Comment by vcunat** [comment] 2016-02-26 22:10
Hmm, it's the *Declared by* path names that seem to be unbreakable, judging from formatting with a thin terminal and viewing then in a wider one (without re-formatting).

**Comment by vcunat** [comment] 2016-02-26 22:15
Apparently it's just because slashes aren't considered as possible places to break a line. I've got no idea whether/how that can be changed.

**Closed** 2016-03-19 17:01 UTC
Labels: 0.kind: enhancement
