### ISSUE TITLE
generate transitive closure of dependencies in `texlive.combine`

### ISSUE THREAD

**Issue by cxandru** [NixOS/nixpkgs#104392] opened 2020-11-20 17:30 UTC
## Issue description
If one wants to use a minimal set of `texlive` packages one runs into the issue that the way `pkgs.nix` in https://github.com/NixOS/nixpkgs/tree/master/pkgs/tools/typesetting/tex/texlive is generated means that the user has to handle transitive dependencies themselves. 

It seems though that `tlmgr` is perfectly capable of creating a transitive dependency closure (see https://github.com/TeX-Live/texlive-source/blob/trunk/texk/texlive/linked_scripts/texlive/tlmgr.pl#L3669)

From what I found in a case study of the package `subfiles` which has as dependency the packages `import` and `verbatim`, there is no clear file where packages declare their dependencies, so I guess `tlmgr` does its job in an ad-hoc manner (e.g. it seems that `RequirePackage` calls seem a good heuristic for dependencies, though knowing tex, there are probably many others)

I just wanted to open an issue for this since it seems like something that the tex community would also benefit from, and I didn't find a ticket for this on any other bug tracker.

**Comment by 7c6f434c** [comment] 2020-11-20 17:56
>It seems though that `tlmgr` is perfectly capable of creating a transitive dependency closure (see https://github.com/TeX-Live/texlive-source/blob/trunk/texk/texlive/linked_scripts/texlive/tlmgr.pl#L3669)

tlmgr relies on TL PDB, apparently?

And why pkgs.nix would need to care about transitive closure, Nix can give you the closure of a package

>From what I found in a case study of the package `subfiles` which has as dependency the packages `import` and `verbatim`, there is no clear file where packages declare their dependencies, so I guess `tlmgr` does its job in an ad-hoc manner (e.g. it seems that `RequirePackage` calls seem a good heuristic for dependencies, though knowing tex, there are probably many others)

So you want to say that upstream TL PDB does not list the «import» dependency? Is it not an upstream issue then?

**Comment by veprbl** [comment] 2020-11-20 18:08
As far as I know we are respecting all of the upstream dependencies. If you have any new additions please send them to the upstream bug tracker at tex-live@tug.org. If there is an interest, we can add overrides for missing dependencies to our overrides https://github.com/NixOS/nixpkgs/blob/7cf7fb7948ea9fae7821a0f4ce5d5872ba979cae/pkgs/tools/typesetting/tex/texlive/default.nix#L60

This is a duplicate of #56840

**Comment by veprbl** [comment] 2020-11-20 18:09
Duplicate of #56840

**Comment by cxandru** [comment] 2020-11-20 18:23
Thanks for pointing me further! I hadn't found out about the tlpdb. I'll have a look at reporting this case there.

**Comment by FRidh** [comment] 2020-11-23 07:37
Closing as duplicate.

**Closed by FRidh** 2020-11-23 07:37 UTC
Labels: 6.topic: TeX
