### ISSUE TITLE
lesspipe: cross-compilation regressed

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#295072] opened 2024-03-11 17:48 UTC
### Steps To Reproduce

This is on nixos-unstable 3030f185:

```
> nix-build -A  pkgsCross.aarch64-multiplatform.lesspipe
...
Traceback (most recent call last):
  File "/nix/store/3ny4ai6x7warnq39hpspqjxxcfv2ibgs-resholve-0.9.1/bin/.resholve-wrapped", line 4748, in <module>
    sys.exit(punshow())
  File "/nix/store/3ny4ai6x7warnq39hpspqjxxcfv2ibgs-resholve-0.9.1/bin/.resholve-wrapped", line 947, in punshow
    resolve_cmdlikes()
  File "/nix/store/3ny4ai6x7warnq39hpspqjxxcfv2ibgs-resholve-0.9.1/bin/.resholve-wrapped", line 3119, in resolve_cmdlikes
    cmdlike.resolve()
  File "/nix/store/3ny4ai6x7warnq39hpspqjxxcfv2ibgs-resholve-0.9.1/bin/.resholve-wrapped", line 3091, in resolve
    self._resolve_invocations(solution)
  File "/nix/store/3ny4ai6x7warnq39hpspqjxxcfv2ibgs-resholve-0.9.1/bin/.resholve-wrapped", line 3050, in _resolve_invocat
ions
    source.look_for_external_sub_execution(self.name, invocation)
  File "/nix/store/3ny4ai6x7warnq39hpspqjxxcfv2ibgs-resholve-0.9.1/bin/.resholve-wrapped", line 4046, in look_for_externa
l_sub_execution
    if handler(parsed, invocation):
  File "/nix/store/3ny4ai6x7warnq39hpspqjxxcfv2ibgs-resholve-0.9.1/bin/.resholve-wrapped", line 3717, in handle_external_
sed
    if self._find_sed_e_cmd(first):
  File "/nix/store/3ny4ai6x7warnq39hpspqjxxcfv2ibgs-resholve-0.9.1/bin/.resholve-wrapped", line 3659, in _find_sed_e_cmd
    close_fds=True,
  File "/nix/store/mxwqwa270lp03z996zz6s6vy23cp67di-python-2.7.18.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/nix/store/mxwqwa270lp03z996zz6s6vy23cp67di-python-2.7.18.7/lib/python2.7/subprocess.py", line 1046, in _execute_
child
    child_exception = pickle.loads(data)
  File "/nix/store/mxwqwa270lp03z996zz6s6vy23cp67di-python-2.7.18.7/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/nix/store/mxwqwa270lp03z996zz6s6vy23cp67di-python-2.7.18.7/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/nix/store/mxwqwa270lp03z996zz6s6vy23cp67di-python-2.7.18.7/lib/python2.7/pickle.py", line 977, in load_string
    self.append(rep.decode("string-escape"))
  File "/nix/store/mxwqwa270lp03z996zz6s6vy23cp67di-python-2.7.18.7/lib/python2.7/encodings/__init__.py", line 100, in se
arch_function
    level=0)
TypeError: _oildev_import() got an unexpected keyword argument 'fromlist'
/nix/store/4jq69bbd4fmb7gi48qbpx005ly6vgbvf-stdenv-linux/setup: line 131: pop_var_context: head of shell_variables not a
function context
error: builder for '/nix/store/khs61hf5q34vfbqlffdyn1lrnhcxlmxc-lesspipe-aarch64-unknown-linux-gnu-2.11.drv' failed with
exit code 1;
```

IDK why the log is truncated in the web view, it looks fine in markdown. idgi.

```
TypeError: _oildev_import() got an unexpected keyword argument 'fromlist'
```

### Build log

```
log here if short otherwise a link to a gist
```

### Additional context

cc: @abathur 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by abathur** [comment] 2024-03-11 18:54
Also tracking this in:
- https://github.com/abathur/resholve/issues/115

I've been trying to pick at a fix (in https://github.com/abathur/resholve/tree/fix_build_time_sed_cross), but I'm in a few weeks where I don't have much free time so I'll also context dump on the off chance someone's able to push on it. I think I may have patched around the various exec/format errors, but at the moment it's gummed up around a hang on the initialization of `subprocess.Popen` to invoke sed (i.e., at https://github.com/abathur/resholve/commit/719aa7321fb4429bdef3f49d0db0aff375ee4d36#diff-3791dcc7805ec6044570664bd7360fb4e9441c5987f7df8641b50e8bdac2df48R3697-R3705):
- CI build that hangs: https://github.com/abathur/resholve/actions/runs/8207553253/job/22449073657
- straced run of same: https://github.com/abathur/resholve/actions/runs/8207747438/job/22449713631

I haven't had much time to actually try to debug this beyond getting it reproduced in CI and confirming where it's hanging.

**Comment by Mic92** [comment] 2024-03-25 21:50
Similar regression + fix in xdg-utils: https://github.com/NixOS/nixpkgs/pull/299023

I would suggest not to add resholve in important packages until this problem is resolved.

**Comment by abathur** [comment] 2024-03-25 22:03
Can you see if it's necessary if you cherry-pick https://github.com/NixOS/nixpkgs/pull/298515?

**Comment by danielbarter** [comment] 2024-03-26 22:51
@abathur:

its not fixed on your branch, because gnupg is failing to build for a completely unrelated reason: https://github.com/NixOS/nixpkgs/pull/298001

should be good with both commits though.

**Comment by danielbarter** [comment] 2024-03-27 03:49
Can confirm that lesspipe cross compiling is working with https://github.com/NixOS/nixpkgs/pull/298515 and https://github.com/NixOS/nixpkgs/pull/298001. `xdg-utils` is still having issues though. Will ping abathur in the corresponding issue.

**Comment by samueldr** [comment] 2024-04-23 03:41
Just checked today, `pkgsCross.aarch64-multiplatform.xdg-utils` built fine on `nixos-unstable` 6143fc5eeb9c4f00163267708e26191d1e918932.

Assumed fixed.

@abathur: if the issue you have "tracked in" still needs to be solved, would it be too much to ask you to open a new issue detailing this one in details? Thanks!

**Closed by samueldr** 2024-04-23 03:41 UTC
Labels: 0.kind: build failure

**Comment by abathur** [comment] 2024-04-23 03:48
> Just checked today, `pkgsCross.aarch64-multiplatform.xdg-utils` built fine on `nixos-unstable` [6143fc5](https://github.com/NixOS/nixpkgs/commit/6143fc5eeb9c4f00163267708e26191d1e918932).
> 
> Assumed fixed.
> 
> @abathur: if the issue you have "tracked in" still needs to be solved on Nixpkgs's side, would it be too much to ask you to open a new issue detailing this one in details? Thanks!

I agree. Was just waiting to close until it was in unstable and someone confirmed it worked. Closed the issue on resholve's side.
