### ISSUE TITLE
20.09 channel advances before thunderbird is built

### ISSUE THREAD

**Issue by sbourdeauducq** [NixOS/nixpkgs#104678] opened 2020-11-23 16:16 UTC
Often when rebuilding 20.09 systems, it downloads the Thunderbird source and compiles it, which takes a lot of time. Since this is a common package, shouldn't the channel advance only when binary substitutes are available?

I've seen this happen with libreoffice as well, though not recently.

Is my channel configuration correct?
```
$ sudo nix-channel --list
nixos https://nixos.org/channels/nixos-20.09
```

The affected package is `pkgs.thunderbird`.

**Comment by vcunat** [comment] 2020-11-29 09:51
If I look right, thunderbird isn't a blocking package for `nixos-*` channels.  They still wait for builds to finish so mostly you should be OK, but if such a package fails for some reason...  and that may happen even "randomly" &ndash; cross-ref e.g. https://github.com/NixOS/nixpkgs/issues/103070#issuecomment-735072523

**Comment by sbourdeauducq** [comment] 2020-11-30 04:20
The issue just occurred again, building 20.09 compiles thunderbird right now.

**Comment by vcunat** [comment] 2020-12-01 09:30
Yes, we had [a series of timeouts](https://hydra.nixos.org/build/131560211#tabs-buildsteps) on Hydra for that particular build.  I don't know why and I could never reproduce these locally (which isn't an overloaded machine but maybe that's not a significant difference here).  For now I kept restarting it until it succeeded.

**Comment by vcunat** [comment] 2020-12-11 10:08
I think those timeouts shouldn't happen anymore. Reopen if the failures start happening again.  (There's still not a guarantee due to these packages not being marked as channel-critical.)

**Closed by vcunat** 2020-12-11 10:08 UTC
Labels: 0.kind: bug
