### ISSUE TITLE
ffmpeg-full: ffplay is missing

### ISSUE THREAD

**Issue by mateon1** [NixOS/nixpkgs#24783] opened 2017-04-09 20:55 UTC
## Issue description

ffplay seems to be missing in Nixpkgs. Installing packages `ffmpeg` and/or `ffmpeg-full` does not provide `ffplay` to the user.

### Steps to reproduce

1. Install `ffmpeg-full`
2. Observe that trying to run `ffplay` gives `ffplay: command not found`.

## Technical details

* System: NixOS: 17.03beta240.5c1fdb1 (Gorilla)
* Nix version: nix-env (Nix) 1.11.7
* Nixpkgs version: 17.03beta240.5c1fdb1

**Comment by vcunat** [comment] 2017-04-10 15:39
Duplicate of https://github.com/NixOS/nixpkgs/issues/24658

**Closed by vcunat** 2017-04-10 15:39 UTC
