### ISSUE TITLE
virtualbox: Unable to compile VirtualBox kernel modules with kernel 5.10

### ISSUE THREAD

**Issue by asbachb** [NixOS/nixpkgs#107648] opened 2020-12-26 17:21 UTC
**Describe the bug**
VirtualBox kernel modules are not able to compile with `kernel_latest`.

`configuration.nix`
```
...
boot.kernelPackages = pkgs.linuxPackages_latest;
...
virtualisation.virtualbox.host.enable = true;
...
```

```
 asbachb@nixo-t14s  ~  sudo nixos-rebuild switch
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/q7fyvhkz53pryr8bxh6r6zdz87lz479r-system-path.drv
  /nix/store/dbylza6h4dr36i39y2yx2g52y44dfrcc-dbus-1.drv
  /nix/store/0nhc7z7zda2amhlzlbi0a7svp8lckskk-unit-dbus.service.drv
  /nix/store/jmjh19xfhsjwm5lbdc3s1h967zrbwhbh-unit-dbus.service.drv
  /nix/store/qxp8zmc88irr3n5pwd0w5ngkg7qnqmr4-unit-systemd-fsck-.service.drv
  /nix/store/z8fdcsf3dwj5icwxf648789x6nws4m9y-unit-polkit.service.drv
  /nix/store/13krbx2g227viybw4498g31hxfvaw02b-system-units.drv
  /nix/store/far87ahiirm9i2dghqzi974fsqw0f8m6-virtualbox-modules-6.1.16-5.10.2.drv
  /nix/store/jww9dbspydkv86fnclijrxa02hbcn0i9-linux-5.10.2-modules.drv
  /nix/store/w25ppabibq4a795730xnqlb0hmrj83lg-linux-5.10.2-modules-shrunk.drv
  /nix/store/4s01w1i4cgjw6yd9rrm3nyn9r9b0wads-stage-1-init.sh.drv
  /nix/store/n4nr93sjv8a9jcnpih71qh9gc5zlgpjx-user-units.drv
  /nix/store/94pagcnsfgyyvikkhiwm69jbvd1w9zcy-etc.drv
  /nix/store/fhbb3q2jsgrx66azr1qhb4nfi0svqp8v-initrd-linux-5.10.2.drv
  /nix/store/qa56gv400bln95vaifnfc4rwjsf2w5rn-kernel-modules.drv
  /nix/store/x8hjrmi4w8dcdiyr7sjv3apjzr7i0bqc-nixos-system-nixo-t14s-21.03pre259711.be0b453d7c7.drv
building '/nix/store/q7fyvhkz53pryr8bxh6r6zdz87lz479r-system-path.drv'...
building '/nix/store/far87ahiirm9i2dghqzi974fsqw0f8m6-virtualbox-modules-6.1.16-5.10.2.drv'...
unpacking sources
unpacking source archive /nix/store/q12mjnim3j4mx009816y2j2rn8lbc5px-virtualbox-6.1.16-modsrc
source root is virtualbox-6.1.16-modsrc
patching sources
configuring
no configure script, doing nothing
building
build flags: -j16 -l16 SHELL=/nix/store/4l7wsi6h6283194r6fqy1731qxlagq62-bash-4.4-p23/bin/bash INSTALL_MOD_PATH=\$\(out\)
=== Building 'vboxdrv' module ===
make[1]: Entering directory '/build/virtualbox-6.1.16-modsrc/vboxdrv'
make V= CONFIG_MODULE_SIG= CONFIG_MODULE_SIG_ALL= -C /nix/store/vfjkakb00wa967gphgbrw72lhqlhrh6j-linux-5.10.2-dev/lib/modules/5.10.2/build M=/build/virtualbox-6.1.16-modsrc/vboxdrv SRCROOT=/build/virtualbox-6.1.16-modsrc/vboxdrv -j16 modules
make[2]: Entering directory '/build/virtualbox-6.1.16-modsrc/vboxdrv'
make[2]: warning: -j16 forced in submake: resetting jobserver mode.
collision between `/nix/store/3ln42pm0g5iak1iddi8wj6qp2l31i2hx-nix-bash-completions-0.6.8/share/bash-completion/completions/nixos-container' and `/nix/store/gmgddv8s3qnhx9d940rpl9gczawz40gy-nixos-container/share/bash-completion/completions/nixos-container'
created 8507 symlinks in user environment
building '/nix/store/dbylza6h4dr36i39y2yx2g52y44dfrcc-dbus-1.drv'...
building '/nix/store/z8fdcsf3dwj5icwxf648789x6nws4m9y-unit-polkit.service.drv'...
building '/nix/store/qxp8zmc88irr3n5pwd0w5ngkg7qnqmr4-unit-systemd-fsck-.service.drv'...
building '/nix/store/0nhc7z7zda2amhlzlbi0a7svp8lckskk-unit-dbus.service.drv'...
building '/nix/store/jmjh19xfhsjwm5lbdc3s1h967zrbwhbh-unit-dbus.service.drv'...
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/linux/SUPDrv-linux.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/SUPDrv.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/SUPDrvGip.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/SUPDrvSem.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/SUPDrvTracer.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/SUPLibAll.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/alloc-r0drv.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/initterm-r0drv.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/memobj-r0drv.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/mpnotification-r0drv.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/powernotification-r0drv.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/assert-r0drv-linux.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/alloc-r0drv-linux.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/initterm-r0drv-linux.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/memobj-r0drv-linux.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/memuserkernel-r0drv-linux.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/mp-r0drv-linux.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/mpnotification-r0drv-linux.o
building '/nix/store/n4nr93sjv8a9jcnpih71qh9gc5zlgpjx-user-units.drv'...
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/process-r0drv-linux.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/rtStrFormatKernelAddress-r0drv-linux.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/semevent-r0drv-linux.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/semeventmulti-r0drv-linux.o
/build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/memobj-r0drv-linux.c: In function 'rtR0MemObjLinuxVMap':
/build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/memobj-r0drv-linux.c:560:34: error: implicit declaration of function 'alloc_vm_area' [-Werror=implicit-function-declaration]
  560 |                 pMemLnx->pArea = alloc_vm_area(pMemLnx->Core.cb, papPtes); /* Note! pArea->nr_pages is not set. */
      |                                  ^~~~~~~~~~~~~
/build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/memobj-r0drv-linux.c:560:32: warning: assignment to 'struct vm_struct *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  560 |                 pMemLnx->pArea = alloc_vm_area(pMemLnx->Core.cb, papPtes); /* Note! pArea->nr_pages is not set. */
      |                                ^
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/semfastmutex-r0drv-linux.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/semmutex-r0drv-linux.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/spinlock-r0drv-linux.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/thread-r0drv-linux.o
/build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/memuserkernel-r0drv-linux.o: warning: objtool: VBoxHost_RTR0MemKernelCopyFrom()+0x13: redundant CLD
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/thread2-r0drv-linux.o
building '/nix/store/13krbx2g227viybw4498g31hxfvaw02b-system-units.drv'...
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/threadctxhooks-r0drv-linux.o
/build/virtualbox-6.1.16-modsrc/vboxdrv/SUPDrvTracer.o: warning: objtool: .text+0x7: indirect jump found in RETPOLINE build
/build/virtualbox-6.1.16-modsrc/vboxdrv/SUPDrvTracer.o: warning: objtool: supdrvTracerProbeFireStub() is missing an ELF size annotation
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/time-r0drv-linux.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/timer-r0drv-linux.o
  CC [M]  /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/generic/semspinmutex-r0drv-generic.o
cc1: some warnings being treated as errors
make[4]: *** [/nix/store/vfjkakb00wa967gphgbrw72lhqlhrh6j-linux-5.10.2-dev/lib/modules/5.10.2/source/scripts/Makefile.build:279: /build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/memobj-r0drv-linux.o] Error 1
make[4]: *** Waiting for unfinished jobs....
/build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/threadctxhooks-r0drv-linux.o: warning: objtool: rtThreadCtxHooksLnxSchedOut()+0x1f: call to __x86_indirect_thunk_rax() with UACCESS enabled
/build/virtualbox-6.1.16-modsrc/vboxdrv/r0drv/linux/threadctxhooks-r0drv-linux.o: warning: objtool: rtThreadCtxHooksLnxSchedIn()+0x29: call to __x86_indirect_thunk_rax() with UACCESS enabled
make[3]: *** [/nix/store/vfjkakb00wa967gphgbrw72lhqlhrh6j-linux-5.10.2-dev/lib/modules/5.10.2/source/Makefile:1805: /build/virtualbox-6.1.16-modsrc/vboxdrv] Error 2
make[2]: *** [/nix/store/vfjkakb00wa967gphgbrw72lhqlhrh6j-linux-5.10.2-dev/lib/modules/5.10.2/source/Makefile:185: __sub-make] Error 2
make[2]: Leaving directory '/nix/store/vfjkakb00wa967gphgbrw72lhqlhrh6j-linux-5.10.2-dev/lib/modules/5.10.2/build'
make[1]: *** [/build/virtualbox-6.1.16-modsrc/vboxdrv/Makefile-footer.gmk:117: vboxdrv] Error 2
make[1]: Leaving directory '/build/virtualbox-6.1.16-modsrc/vboxdrv'
make: *** [Makefile:60: vboxdrv] Error 2
builder for '/nix/store/far87ahiirm9i2dghqzi974fsqw0f8m6-virtualbox-modules-6.1.16-5.10.2.drv' failed with exit code 2
cannot build derivation '/nix/store/qa56gv400bln95vaifnfc4rwjsf2w5rn-kernel-modules.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/jww9dbspydkv86fnclijrxa02hbcn0i9-linux-5.10.2-modules.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/x8hjrmi4w8dcdiyr7sjv3apjzr7i0bqc-nixos-system-nixo-t14s-21.03pre259711.be0b453d7c7.drv': 1 dependencies couldn't be built
error: build of '/nix/store/x8hjrmi4w8dcdiyr7sjv3apjzr7i0bqc-nixos-system-nixo-t14s-21.03pre259711.be0b453d7c7.drv' failed

```

**Notify maintainers**
-

**Metadata**
```
 ✘ asbachb@nixo-t14s  ~  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.2, NixOS, 21.03pre259711.be0b453d7c7 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.03pre259711.be0b453d7c7, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

/cc @Magicloud @Ma27 @flokli @B4dM4n @bryanasdev000

**Comment by asbachb** [comment] 2020-12-26 17:23
Upstream bug: https://www.virtualbox.org/ticket/20055

**Comment by bryanasdev000** [comment] 2020-12-28 01:10
Well, seriously thinking about using full QEMU + KVM.

I can confirm the bug here, but from a quick read, there is still no version with this fix (test versions only), so I'm not sure of the best way here, we can add a patch for now (if the maintainers agree) or wait for the next release.

**Comment by flokli** [comment] 2020-12-28 12:22
Yeah, upstream seems pretty bad in keeping up to date with kernel updates. Assuming the patches circulating in the issue tracker don't break the build in older kernels, `fetchpatch`'ing them in nixpkgs before there's a release is fine. Can you send a PR?

**Comment by bryanasdev000** [comment] 2020-12-29 06:35
> Yeah, upstream seems pretty bad in keeping up to date with kernel updates. Assuming the patches circulating in the issue tracker don't break the build in older kernels, `fetchpatch`'ing them in nixpkgs before there's a release is fine. Can you send a PR?

I can try, will search how to first lol

**Comment by bryanasdev000** [comment] 2020-12-29 08:02
Ok, after a few rounds I found what to change, reading it calmly, there seems to be 3 patches involved in the problem, one to fix the initial problem described in that issue and two to fix the DRM and shared folders in this kernel version. It's pretty late around here so I'm leaving my laptop compiling with the initial patch to test, as my biggest use of the Virtualbox is with Vagrant it is quite possible that I won't find the other two problems, but I'll investigate as well.

First patch is this one: https://github.com/sergiomb2/VirtualBox/commit/2a6e3cf63f58e289802a11faad5fb495e2d04e97

A PR would have to change these lines: https://github.com/NixOS/nixpkgs/blob/23adfcf87dc8d7863335ab181f1b44409205f0a2/pkgs/applications/virtualization/virtualbox/default.nix#L91

I'm using this expression to test the patch:

```
nixpkgs = {
    config = {
      allowUnfree = true;
      packageOverrides = pkgs: rec {
        virtualbox = pkgs.virtualbox.overrideAttrs (attrs: {
          patches = attrs.patches ++ [ /root/first.patch ];
        });
      };
    };
...
  };
```

**Comment by bryanasdev000** [comment] 2020-12-29 18:22
People, for me, running the latest version of Zen, the first patch was all I needed, graphics ok, shared folder ok. I tested a Windows 10 previously created and two Debian 10 (via vagrant) one already provisioned and another new.

Can anyone else test before sending a PR?

In the meantime I will look for the possibility of using an IF for kernel versions >= 5.10 and applying the patch only to them.

![virtualbox-510](https://user-images.githubusercontent.com/53131727/103305290-80150180-49e9-11eb-9195-49d29ce85b74.png)

**Comment by flokli** [comment] 2020-12-29 19:17
> In the meantime I will look for the possibility of using an IF for kernel versions >= 5.10 and applying the patch only to them.

Patches should be applied unconditionally (so they fail loudly when they don't apply), not only in corner cases. They of course then needs to be written to work with both kernels (but that should be the case here)

**Comment by bryanasdev000** [comment] 2020-12-29 19:32
> > In the meantime I will look for the possibility of using an IF for kernel versions >= 5.10 and applying the patch only to them.
> 
> Patches should be applied unconditionally (so they fail loudly when they don't apply), not only in corner cases. They of course then needs to be written to work with both kernels (but that should be the case here)

Okay, I got lost here, in theory this patch is only necessary from 5.10 onwards, so should we test it on a lower one and if everything works add it?

It can also have some other side effect, for now I'm just using via vagrant (as I usually do) and I would like someone else to test it too.

**Comment by flokli** [comment] 2021-01-01 22:56
Yes, but the patch includes ifdefs, so it should work on both kernel versions.

Only adding patches in some conditions is discouraged in nixpkgs. After doing version bumps, patches might not apply cleanly anymore, but it's not caught during review if only tested on a variant where the patch is "hidden by the condition".

In the case of virtualbox, imagine a reviewer testing manually while on a stable kernel. They'll never realize the patch doesn't apply anymore, as it's not in the derivation they built.

**Comment by bryanasdev000** [comment] 2021-01-01 23:52
> Yes, but the patch includes ifdefs, so it should work on both kernel versions.
> 
> Only adding patches in some conditions is discouraged in nixpkgs. After doing version bumps, patches might not apply cleanly anymore, but it's not caught during review if only tested on a variant where the patch is "hidden by the condition".
> 
> In the case of virtualbox, imagine a reviewer testing manually while on a stable kernel. They'll never realize the patch doesn't apply anymore, as it's not in the derivation they built.

First, happy new year!

Second, thanks for explaining, I understand.

As I am not at the computer these days, I am going to do a quick test with this patch in 5.10 Vanilla and 5.9, if everything goes well I will return with PR to merge this patch.

Thank you!

**Comment by bryanasdev000** [comment] 2021-01-03 05:28
Created PR https://github.com/NixOS/nixpkgs/pull/108285.

**Comment by bryanasdev000** [comment] 2021-01-22 22:44
Opened https://github.com/NixOS/nixpkgs/pull/110550, which include the latest release with fix.

**Comment by flokli** [comment] 2021-01-22 23:28
Let's close this in favor of https://github.com/NixOS/nixpkgs/pull/110550.

**Comment by asbachb** [comment] 2021-01-22 23:31
I think the issue should remain opened until the issue is fixed in master.

**Comment by flokli** [comment] 2021-01-22 23:35
Indeed - I confused this with https://github.com/NixOS/nixpkgs/pull/108285. Sorry!

**Closed** 2021-01-25 15:36 UTC
Labels: 0.kind: bug
