### ISSUE TITLE
Move wayland compositors in a separate module

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#53394] opened 2019-01-04 09:48 UTC
For example, `services.wayland.*`. Right now they all live in `programs.*` and thus are harder to discover.

**Comment by jtojnar** [comment] 2019-01-04 17:23
I think it might make sense to use

- `services.xserver.displayManager.gdm` → `services.desktop.displayManager.gdm`
- `services.xserver.desktopManager.gnome3` → `services.desktop.desktopEnvironment.gnome3`

The display server the DM or DE is running is just an implementation detail.

Not sure where to fit the slim WMs like Sway or OpenBox into this, since I would expect `desktopEnvironment` to handle things like XDG modules as well — my uncertainty probably stems from the lack of composability of modules.

**Comment by suhr** [comment] 2020-07-19 09:32
This is still relevant.

**Comment by doronbehar** [comment] 2020-08-30 11:47
Is it possible to run gdm and Gnome without X on the system at all? I mean, does setting `services.xserver.displayManager.gdm.enable = true` runs gdm in Xorg?

**Comment by primeos** [comment] 2020-08-30 18:22
> Is it possible to run gdm and Gnome without X on the system at all?

Didn't check, but likely not yet.

> For example, services.wayland.*. Right now they all live in programs.* and thus are harder to discover.

I'd also appreciate having something like `services.wayland.*`. Or rather something like `nixos/modules/services/x11/display-managers/default.nix` (`xsessionWrapper`) that each Wayland compositor module can reuse.

**Comment by suhr** [comment] 2021-03-05 18:25
Still relevant.

**Comment by suhr** [comment] 2021-09-03 09:53
And relevant still.

**Comment by doronbehar** [comment] 2021-09-30 12:43
Duplicate of https://github.com/NixOS/nixpkgs/issues/102542

**Closed** 2021-11-16 12:45 UTC
Labels: 6.topic: nixos
