### ISSUE TITLE
apple-sdk-13

### ISSUE THREAD

**Issue by shyim** [NixOS/nixpkgs#199730] opened 2022-11-05 17:47 UTC
**Project description**
nixpkgs contains currently only apple-sdk 12. When you want to compile stuff like https://github.com/Code-Hex/vz you need the newest version because of newer functionalities. 

https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/darwin/apple-sdk/default.nix

**Comment by veprbl** [comment] 2022-11-05 17:59
Duplicate of https://github.com/NixOS/nixpkgs/issues/101229
being worked on, see progress reports in https://discourse.nixos.org/t/nix-macos-monthly/12330/18
Often one can patch-out use of non-essential features of the newer SDKs. There is also an impure 11.0 SDK using #176661.

**Closed** 2022-11-05 17:59 UTC
Labels: 6.topic: darwin, 0.kind: packaging request
