### ISSUE TITLE
vlc doesn't work

### ISSUE THREAD

**Issue by allowthere** [NixOS/nixpkgs#57214] opened 2019-03-10 04:54 UTC
## Issue description

vlc doesn't work. It outputs: `Cannot mix incompatible Qt library (version 0x50b01) with this library (version 0x50b03)`

### Steps to reproduce

run vlc

## Technical details

these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/ial8a56ys2rswfq4j2abm3cl99li5b6p-bash-interactive-4.4-p23-dev
copying path '/nix/store/ial8a56ys2rswfq4j2abm3cl99li5b6p-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.105, NixOS, 18.09.2327.37694c8cc0e (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2327.37694c8cc0e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by SmilingHorse** [comment] 2019-03-14 16:28
same:
```
$ vlc
VLC media player 3.0.4 Vetinari (revision 3.0.4-0-gf615db6332)
[0000000001d225d0] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
Cannot mix incompatible Qt library (version 0x50b01) with this library (version 0x50b03)
Aborted
```

cvlc works fine for both audio and video files though without the on-screen interface so you're limited to the keybindings for navigation: https://wiki.videolan.org/QtHotkeys/

**Comment by jtojnar** [comment] 2019-03-14 23:54
Duplicate of https://github.com/NixOS/nixpkgs/issues/55994, https://github.com/NixOS/nixpkgs/issues/30551, https://github.com/NixOS/nixpkgs/issues/37864…

Make sure you are not mixing different versions of Qt in your apps installed through `configuration.nix` and `nix-env`.

**Closed by jtojnar** 2019-03-14 23:54 UTC
Labels: 6.topic: qt/kde

**Comment by SmilingHorse** [comment] 2019-03-15 19:47
yeah a nix-env --upgrade did the trick. thanks!
