### ISSUE TITLE
Package the alfaview client

### ISSUE THREAD

**Issue by neumantm** [NixOS/nixpkgs#147916] opened 2021-11-29 18:21 UTC
**Project description**
alfaview is a video conferencing tool developed and hosted in Germany.
To use their service, a client is needed.

The project is proprietary, but they provide a .deb as download.

**Metadata**

* homepage URL: https://alfaview.com/en/
* source URL: -
* license: proprietary
* platforms: linux

**Comment by WolfangAukang** [comment] 2021-11-30 02:01
I was able to build it, but it would be nice if someone could test it to ensure what's built works as intended.

**Comment by WolfangAukang** [comment] 2021-11-30 16:40
Merged

**Closed by WolfangAukang** 2021-11-30 16:40 UTC
Labels: 0.kind: packaging request
