### ISSUE TITLE
coreutils: can't build

### ISSUE THREAD

**Issue by nyarly** [NixOS/nixpkgs#158022] opened 2022-02-03 18:58 UTC
### Describe the bug

I cannot currently update one of my nixos systems, because it wants to build coreutils, and a test on dd fails.

### Steps To Reproduce

I'm advised that most users are able to fetch coreutils without building it. I'm not sure why my system want to build it, so I'm not clear how to reproduce, but `sudo nixos-rebuild switch` is sufficient on my system.

### Expected behavior

System update. coreutils needing to build shouldn't be a blocker.

### Screenshots
```
FAIL: tests/dd/direct
=====================

dd: error reading 'short': Invalid argument
0+0 records in
0+0 records out
0 bytes copied, 9.4146e-05 s, 0.0 kB/s
15+1 records in
15+1 records out
8191 bytes (8.2 kB, 8.0 KiB) copied, 0.0179904 s, 455 kB/s
16+1 records in
16+1 records out
8193 bytes (8.2 kB, 8.0 KiB) copied, 0.0106462 s, 770 kB/s
FAIL tests/dd/direct.sh (exit status: 1)
```
...
```
============================================================================
Testsuite summary for GNU coreutils 8.32
============================================================================
# TOTAL: 621
# PASS:  464
# SKIP:  156
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./tests/test-suite.log
Please report to bug-coreutils@gnu.org
============================================================================
make[4]: *** [Makefile:13025: tests/test-suite.log] Error 1
make[4]: Leaving directory '/build/coreutils-8.32'
make[3]: *** [Makefile:13133: check-TESTS] Error 2
make[3]: Leaving directory '/build/coreutils-8.32'
make[2]: *** [Makefile:13388: check-am] Error 2
make[2]: Leaving directory '/build/coreutils-8.32'
make[1]: *** [Makefile:12910: check-recursive] Error 1
make[1]: Leaving directory '/build/coreutils-8.32'
make: *** [Makefile:13390: check] Error 2
error: builder for '/nix/store/x2jjj1fk5j0cyldn8zmgw20cccfcc723-coreutils-8.32.drv' failed with exit code 2
error: 1 dependencies of derivation '/nix/store/l55ccwnwl37yyfzrxqaq3qlwqzdgm0hv-openssl-1.1.1l.drv' failed to build
error: 1 dependencies of derivation '/nix/store/q7x7skram1wzqpni4xx37xb7b69d6lwr-curl-7.76.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rklkl0hm41nijshmj1b08ghr74g3gm36-scout-runtime-0.20211102.0.tar.gz.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mqf640clr4kzadpydwdl1q05mpywjmil-steam-runtime-0.20211102.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jkk12444nyy4rd3bv44r691kwk247a0n-steam-runtime-wrapped.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kqxjp2xshs9g7g5z2fwzkr4q6js8ac0r-steam-run-usr-multi.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vcmnk3w10hpi0crv17sp4a6fzvissjdy-steam-usr-multi.drv' failed to build
error: 1 dependencies of derivation '/nix/store/3858f7z906xk19la3japnhy7vkigm9ln-steam-fhs.drv' failed to build
error: 1 dependencies of derivation '/nix/store/30rzha4ialm99n17m12hmclf0fk8bz0g-steam-run-fhs.drv' failed to build
error: 1 dependencies of derivation '/nix/store/d8lkl7hz8r6c3h3yvh3qcqwxxcglbydc-steam-run.drv' failed to build
error: 1 dependencies of derivation '/nix/store/x97v2s07a9qgvpx0khw6b5ny52jsb0vx-steam.drv' failed to build
error: 1 dependencies of derivation '/nix/store/5rl2yp3x4pn89qc2551mh0r4ax768kji-steam-run.drv' failed to build
error: 1 dependencies of derivation '/nix/store/bw52acb5kadw0dprw54mr1i0fqqbf4a5-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/012170i9xw3qxi6d32kiqh7nkaw26h15-nixos-system-neumann-21.05.4719.0fd9ee1aa36.drv' failed to build
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.79, NixOS, 21.05.4255.d5b65f812cd (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20211006_53e4794`
 - channels(root): `"home-manager-21.05, nixos-21.05.4719.0fd9ee1aa36, nixpkgs-21.05.4719.0fd9ee1aa36"`
 - channels(judson): `"home-manager-21.05, nixpkgs-21.05.4719.0fd9ee1aa36"`
 - nixpkgs: `/home/judson/.nix-defexpr/channels/nixpkgs`
```

**Comment by jonringer** [comment] 2022-02-04 01:06
I see that all of your nix channels are quite old. Do you mind updating them before attmpting to upgrade?

**Comment by jonringer** [comment] 2022-02-04 01:07
also, looks like steam is causing the issue. Most likely because it's usting `glibc_multi`. You can just remove steam, update, add it back.

**Comment by panicgh** [comment] 2022-02-05 22:34
I have a similar problem, just not with `dd` but maybe they are related?

```console
$ sudo nixos-rebuild --upgrade boot --max-jobs 1 --cores 1
...
patching /nix/store/9lb8886s5rprb91675i7pp3phphc5mxz-extra-utils/bin/v4l_id...
patching /nix/store/9lb8886s5rprb91675i7pp3phphc5mxz-extra-utils/bin/cryptsetup-askpass...
patchelf: not an ELF executable
patching /nix/store/9lb8886s5rprb91675i7pp3phphc5mxz-extra-utils/bin/scsi_id...
patching /nix/store/9lb8886s5rprb91675i7pp3phphc5mxz-extra-utils/bin/cryptsetup...
patching /nix/store/9lb8886s5rprb91675i7pp3phphc5mxz-extra-utils/bin/busybox...
patching /nix/store/9lb8886s5rprb91675i7pp3phphc5mxz-extra-utils/bin/cdrom_id...
patching /nix/store/9lb8886s5rprb91675i7pp3phphc5mxz-extra-utils/bin/fido_id...
testing patched programs...
hello world
249
builder for '/nix/store/2r64adzqd1k0i1i0vm6my1hz6cppw35k-extra-utils.drv' failed with exit code 1
building '/nix/store/46n1dhnfdsdxz6vii81pjcnwbrd26h2c-asound.conf.drv'...
cannot build derivation '/nix/store/apj1ffz3djqy33rsj2idkvam1v405yzy-stage-1-init.sh.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/x7a1m81ydyngiaaqq9qlfhgih9xacywz-initrd-linux-5.10.95.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/974jis60gh4mcap0hkkcr1k96rfsgmr0-nixos-system-NAME-21.11.335733.f6ddd55d5f9.drv': 1 dependencies couldn't be built
error: build of '/nix/store/974jis60gh4mcap0hkkcr1k96rfsgmr0-nixos-system-NAME-21.11.335733.f6ddd55d5f9.drv' failed
```

I updated the system on 2022-01-15 for the last time:

```console
[user@system:~]$ nix-shell -p nix-info --run 'nix-info -m'
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.90, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(user): `""`
 - channels(root): `"nixos-21.11.335733.f6ddd55d5f9"`
```

Rolling back the channel to 2022-01-15 (`"nixos-21.11.335130.386234e2a61"`) works for the rebuild (of the old version). On another machine that saw more updates in-between this works:

```console
[user@system2:~]$ nix-build /nix/store/2r64adzqd1k0i1i0vm6my1hz6cppw35k-extra-utils.drv --no-out-link --check
...
patching /nix/store/9lb8886s5rprb91675i7pp3phphc5mxz-extra-utils/bin/fido_id...
patching /nix/store/9lb8886s5rprb91675i7pp3phphc5mxz-extra-utils/bin/mdadm...
patching /nix/store/9lb8886s5rprb91675i7pp3phphc5mxz-extra-utils/bin/busybox...
patching /nix/store/9lb8886s5rprb91675i7pp3phphc5mxz-extra-utils/bin/e2fsck...
patching /nix/store/9lb8886s5rprb91675i7pp3phphc5mxz-extra-utils/bin/systemd-sysctl...
patching /nix/store/9lb8886s5rprb91675i7pp3phphc5mxz-extra-utils/bin/tune2fs...
testing patched programs...
hello world
249
mdadm - v4.1 - 2018-10-01
cryptsetup 2.4.3
/nix/store/9lb8886s5rprb91675i7pp3phphc5mxz-extra-utils
```

**Comment by nyarly** [comment] 2022-02-08 01:03
Updating to 21.11 fixed the issue for me.

**Comment by panicgh** [comment] 2022-02-12 12:44
This issue can be closed, can't it?

**Comment by nyarly** [comment] 2022-02-12 19:09
If 21.05 is no longer supported, I suppose. It seems like everyone was getting coreutils from the nix cache, but that meant anything that relied on a different coreutils would break an install. To be honest, I don't know if 21.11 builds coreutils, either.

Overrides are a part of the nixpkgs featureset, so being able to build an important package locally seems like a real bug until it's confirmed fixed?

**Comment by Atemu** [comment] 2022-02-20 17:37
Both 21.11 and 22.05 coreutils build just fine for me (using `--check`). Are you able to reproduce this still @nyarly?

**Comment by SuperSandro2000** [comment] 2023-12-15 06:54
closing because the affected versions are EOL

**Closed by SuperSandro2000** 2023-12-15 06:54 UTC
Labels: 0.kind: bug
