### ISSUE TITLE
systemd 254 breaks boot.initrd.systemd.enable

### ISSUE THREAD

**Issue by tmuehlbacher** [NixOS/nixpkgs#258180] opened 2023-09-30 11:04 UTC
since updating

```
systemd: 253.6 → 254.3, +1099.5 KiB
```

I had to remove `boot.initrd.systemd.enable` because it would break in some weird ways. I am using impermanence with a tmpfs, LUKS and btrfs subvolumes for `/nix` and `/home`.

One of the symptoms of the issue is that `/sysroot` stays around and has `var/lib` and `var/log` with contents in it.

`bluetoothd` also cannot find my paired devices anymore when using systemd in the initrd. So what I think is happening is that it's already running before pivoting to the real `/` and has some files open in `/sysroot` so that also cannot be unmounted or removed?

Another small change that I have noticed and maybe has something to do with this is that /mnt is no longer created automatically anymore. This is true for either initrds.

After disabling systemd in the initrd, things are looking pretty normal again for now.

Please let me know if there is anything else that I can test or if any info is missing. :)

### Notify maintainers

@RaitoBezarius 

@flokli 
@Kloenk 
@Mic92 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.5, NixOS, 23.11 (Tapir), 23.11.20230927.8a86b98`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by RaitoBezarius** [comment] 2023-09-30 11:35
Probably fixed by https://github.com/NixOS/nixpkgs/pull/257693 which didn't hit your channel yet. Let's reopen if it doesn't fix it.

**Closed by RaitoBezarius** 2023-09-30 11:35 UTC
Labels: 0.kind: bug

**Comment by ElvishJerricco** [comment] 2023-09-30 14:07
Yea, this is a duplicate of #258022

**Comment by tmuehlbacher** [comment] 2023-10-01 12:57
Yes, I can confirm that this has fixed by the mentioned PR, thanks! Sorry about the duplicate
