### ISSUE TITLE
megasync crashes immediately when launched

### ISSUE THREAD

**Issue by rhoriguchi** [NixOS/nixpkgs#113351] opened 2021-02-17 00:58 UTC
**Describe the bug**
Megasync used to work with no issue after updating system it crashes immediately with no log output what's wrong.

**To Reproduce**
1. add `megasync` pkg to system
2. start megasync in terminal or with desktop shortcut

**Expected behavior**
Megasync should start.

**Additional context** 
Before opening this bug I've removed the package and deleted `/.local/share/data/Mega Limited/MEGAsync` and cleared the nix store and added it again.

Log generated by megasync in `/.local/share/data/Mega Limited/MEGAsync/logs` when started:
```
----------------------------- program start -----------------------------
02/17-00:38:14.712679 139652510687552 INFO Device pixel ratio on 'DVI-I-3-2': 1.000000 [:-1]
02/17-00:38:14.712711 139652510687552 INFO Device pixel ratio on 'eDP-1': 1.000000 [:-1]
02/17-00:38:14.734008 139652510687552 DBG  cURL version: 7.74.0 [net.cpp:199]
02/17-00:38:14.734010 139652510687552 DBG  SSL version: OpenSSL/1.1.1i [net.cpp:204]
02/17-00:38:14.734013 139652510687552 DBG  libz version: 1.2.11 [net.cpp:228]
02/17-00:38:14.734014 139652510687552 DBG  IPv6 enabled: 1 [net.cpp:247]
02/17-00:38:14.734017 139652510687552 DBG  Initializing OpenSSL locking callbacks [net.cpp:271]
02/17-00:38:14.734178 139652510687552 DBG  DNS servers: 192.168.1.1,fdaa:bbcc:ddee:0:ae84:c9ff:fe5f:a933 [net.cpp:457]
02/17-00:38:14.735666 139652510687552 CRIT ***CRASH DETECTED: FLUSHING AND CLOSING***
```

**Notify maintainers**
@michojel 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.97, NixOS, 21.05pre269929.ff96a0fa563 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre269929.ff96a0fa563, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- megasync
# a list of nixos modules affected by the problem
module:
```

**Comment by michojel** [comment] 2021-02-17 05:53
Sorry for the inconvenience. Looks to be a duplicate of #112572. Closing, feel free to re-open if you otherwise.

**Closed by michojel** 2021-02-17 05:53 UTC
Labels: 0.kind: bug
