### ISSUE TITLE
option request: services.baloo.enable

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#63489] opened 2019-06-19 00:31 UTC
something like the title - an option for turning the KDE baloo file indexer stuff on and off
Edit: maybe under services.kde or whatever is appropriate

**Comment by peterhoeg** [comment] 2019-06-24 08:26
For the longest time, I have been using baloo running as a systemd user service because the older baloo versions had a tendency to run wild and it was quite convenient to be able to definitely kill it.

The problem is that the running of various KDE subsystems is all set up in ksystemsettings5. So if you were to run it as a systemd user service, you wouldn't have a way to disable it again from inside KDE. 

There is some work under way to have ```ksmserver``` use systemd user services and when that happens, this will be much easier to expose properly as a nixos option.

**Comment by deliciouslytyped** [comment] 2019-06-25 15:10
Is there any way to control things through ksystemsettings?

**Comment by peterhoeg** [comment] 2019-06-26 03:34
As of this moment, no. But it's WIP according to: http://blog.davidedmundson.co.uk/

**Comment by DavHau** [comment] 2019-11-13 16:16
On my nixos 19.09 baloo is extremely buggy. It leads to crashes because it has a memory leak. I need to kill it manually all the time. Reseaching a bit reveals that baloo has these problems since years and many people just recommend disabling it by default. There should definately be an option for disabling it i think. Seems to be a very common usecase.

**Comment by codygman** [comment] 2019-12-08 23:13
Yeah, I just found this after seeing in syslog that baloo is constantly running:

```
Dec 08 17:10:15 nixos xsession[27723]: "/home/cody/emacs-config/straight/repos/org/lisp/ob-haskell.el" id seems to have changed. Perhaps baloo was not running, and this file was deleted + re-created
Dec 08 17:10:15 nixos xsession[27723]: mdb.c:2127: Assertion 'rc == 0' failed in mdb_page_dirty()
Dec 08 17:10:15 nixos systemd[1]: Started Process Core Dump (PID 31064/UID 0).
Dec 08 17:10:15 nixos systemd-coredump[31065]: Process 31056 (.baloo_file_ext) of user 1000 dumped core.
Dec 08 17:10:15 nixos systemd[1]: systemd-coredump@4284-31064-0.service: Succeeded.
Dec 08 17:10:15 nixos xsession[27723]: "/home/cody/emacs-config/straight/repos/org/lisp/ob-haskell.el" id seems to have changed. Perhaps baloo was not running, and this file was deleted + re-created
Dec 08 17:10:15 nixos xsession[27723]: mdb.c:2127: Assertion 'rc == 0' failed in mdb_page_dirty()
Dec 08 17:10:15 nixos systemd[1]: Started Process Core Dump (PID 31074/UID 0).
```

It's also constantly using 4% of my cpu.

**Comment by peterhoeg** [comment] 2019-12-09 02:31
This probably doesn't help you very much, but I'd like to point out that baloo has gotten a lot better than it was in the past and the only cases where where it has run wild recently has been because it just did what it was supposed to - index files.

You probably want to exclude network file systems and remote FUSE systems (I had a particularly bad experience with MP3FUSE) but as long as it just does local files, it absolutely flies.

**Comment by codygman** [comment] 2019-12-09 02:34
This was a local directory synced by syncthing if that matters.

**Comment by DavHau** [comment] 2019-12-09 11:02
> This probably doesn't help you very much, but I'd like to point out that baloo has gotten a lot better than it was in the past and the only cases where where it has run wild recently has been because it just did what it was supposed to - index files.

Good, to know that it has improved but i have to disagree with you. For me it re-indexed the same two files over and over again in an endless loop taking my whole system into an out of memory state after a few hours. It was a normal file on my btrfs. I don't use any kind of network sync. I'm quite sure that there was no process running changing anything in those files. And even if it did, baloo should not 'memory leak'. So it is definitely buggy. I commented my problem on some exiting bug report which seemed similar to mine: See here: https://bugs.kde.org/show_bug.cgi?id=413694

**Comment by peterhoeg** [comment] 2019-12-10 03:35
That definitely doesn't look good.

That being said, we should close this issue for now as we don't have a mechanism to properly disable this until the ksmserver is done.

**Comment by deliciouslytyped** [comment] 2019-12-11 00:44
Not to bikeshed, but I don't think "need to wait for upstream to provide mechanism" is reasonable for closing an issue? I'd just wait till upstream does indeed "do the thing", and then continue...

**Comment by bugQ** [comment] 2020-01-15 22:31
agree, it seems strange to close this, even if there is nothing to be done at the moment.  also here to mention that since upgrading to 19.09 my machine produced hundreds of baloo coredumps every startup, thrashing my CPU and disk.

that is, until i found that ksystemsettings does in fact let you disable baloo now.  it's the Enable File Search checkbox on the Search pane.  hope this saves somebody else from nightmares

**Comment by bugQ** [comment] 2020-01-16 16:02
forgot to mention that i also use btrfs.

**Comment by peterhoeg** [comment] 2020-01-17 14:17
baloo can indeed be disabled from the systemsettings (this has been the case for years) but it really isn't a system level setting as it very much depends on the individual users and a system level knob doesn't make much sense.

If anything this should belong in home-manager.

Once upstream transitions to systemd user sessions, it will be trivially easy to disable by masking the unit, but that doesn't mean we should do it here.

**Comment by ducis** [comment] 2020-03-25 16:12
How to disable baloo on the command line? Maybe we can put the shell commands into the nix files.

**Comment by DavHau** [comment] 2020-03-25 16:58
I disabled it via `balooctl disable`. I guess this could be baked into some service.

**Comment by codygman** [comment] 2020-03-26 00:42
> baloo can indeed be disabled from the systemsettings (this has been the case for years) but it really isn't a system level setting as it very much depends on the individual users and a system level knob doesn't make much sense.

I respect the KDE project and all it does, but respectfully my experience with baloo has been unstable. A system level knob makes sense if baloo is unstable. Doubly so if nix used KDE and baloo by default.

**Comment by KouAkitaki** [comment] 2021-07-01 15:07
Still importange to me.

**Comment by Fedcomp** [comment] 2021-12-12 11:03
Bumping it, so bot don't stale this issue again.

**Comment by milahu** [comment] 2022-05-12 21:26
still a problem. baloo was torturing my cpu for hours, and i never need it. should be default off

**Comment by wolfsprite** [comment] 2022-10-15 22:07
I didn't even know what Baloo was until today while trying to determine what was repeatedly locking up my system. :/

Is there still no declarative Nix method of disabling Baloo so it doesn't decide to use up all my CPU?

**Comment by AleXoundOS** [comment] 2023-01-12 08:48
Still important. NixOS 22.11.

**Comment by AleXoundOS** [comment] 2023-01-12 09:18
Maybe as a radical solution baloo indexer can be just excluded when building NixOS KDE packages? And such build variant might be controlled in `configuration.nix`.

**Comment by milahu** [comment] 2023-01-13 08:25
i made a feature request
[feat: read system-wide default configs from /etc/kde/](https://bugs.kde.org/show_bug.cgi?id=464228)

**Comment by Artturin** [comment] 2023-01-14 16:33
did some grepping and found that there's a defaultFolderExcludeFilters in the baloo source https://github.com/KDE/plasma-desktop/blob/d450e5605f4a5b2bf08054fe316b440400e5b3d7/kcms/baloo/fileexcludefilters.cpp#L68-L94

**Comment by peterhoeg** [comment] 2023-03-24 06:23
> i made a feature request

As mentioned in that feature request there is already a way to do this. Just FYI, flakes or no flakes plays no role in this and in the report `XDG_DATA_DIRS` is mentioned which is a mistake - it's supposed to be `XDG_CONFIG_DIRS`.

Upstream stated that kconfig (which baloo uses) respects `XDG_CONFIG_DIRS` which can be confirmed by running `strace balooctl status` and the file `/etc/xdg/baloofilerc` is indeed being opened and read.

So that means that for a user that does not _explicitly_ enable baloo in `$XDG_CONFIG_DIR/baloofilerc` _and_ with the following configuration, baloo will _not_ run:

```nix
{
  environment = {
    etc."xdg/baloofilerc".source = (pkgs.formats.ini {}).generate "baloorc" {
      "Basic Settings" = {
        "Indexing-Enabled" = false;
      };
    };
  };
}
```

``` sh
$ balooctl status
Baloo is currently disabled. To enable, please run balooctl enable
```

You don't technically need to create the file via `pkgs.formats.ini`, but it's much nicer than manually writing out ini files.

**Comment by tastyblob** [comment] 2024-03-10 14:26
Still important. NixOS 23.11

**Comment by brookst** [comment] 2024-04-09 21:11
I came through here looking to outright remove Baloo. I found there's a [environment.plasma6.excludePackages](https://search.nixos.org/options?channel=unstable&show=environment.plasma6.excludePackages&from=0&size=50&sort=relevance&type=packages&query=environment.plasma6.excludePackages) which can be set to a list like `[ pkgs.kdePackages.baloo ]`. There's a matching version for plasma5 also.

I'm not even sure how I came across this option but it's worked for me so thought I ought to post it in case it's what anyone else is looking for.

**Comment by SuperSandro2000** [comment] 2024-04-21 14:57
Since plasma6 baloo by default only indexes the users home directory which shouldn't be such a big problem. For anyone still wanting to disable it, they got multiple options mentioned in the thread.
Because of the changed default setting, I don't think we need to add any option here.

**Closed by SuperSandro2000** 2024-04-21 14:57 UTC
Labels: 0.kind: enhancement, 6.topic: nixos, 6.topic: qt/kde, 9.needs: module (update), 6.topic: user experience

**Comment by MatthiasvB** [comment] 2025-06-28 10:47
> I came through here looking to outright remove Baloo. I found there's a [environment.plasma6.excludePackages](https://search.nixos.org/options?channel=unstable&show=environment.plasma6.excludePackages&from=0&size=50&sort=relevance&type=packages&query=environment.plasma6.excludePackages) which can be set to a list like `[ pkgs.kdePackages.baloo ]`. There's a matching version for plasma5 also.
> 
> I'm not even sure how I came across this option but it's worked for me so thought I ought to post it in case it's what anyone else is looking for.

This worked for me on NixOS 24.11 with Plasma 5. On NixOS 25.05 with Plasma 6 the (equivalent) option does not seem to have an effect
