### ISSUE TITLE
Mathematica 13.2 fails to start

### ISSUE THREAD

**Issue by perlinm** [NixOS/nixpkgs#211117] opened 2023-01-16 17:46 UTC
### Describe the bug
After installing and activating Mathematica 13.2, I can use it *once*, but then if I close it and run `mathematica` from the terminal, it fails to open.

### Steps To Reproduce
1. Install Mathematica 13.2 from the `unstable` channel (this requires first acquiring a Mathematica install file [here](https://wolfram.com/get-upgrade/), and adding it to the nix store with `nix-store --add-fixed sha256 <INSTALL-FILE>`).
3. Run `mathematica`, activate it with an activation key (not publicly available, sorry...).
4. Close Mathematica, try to open it again by running `mathematica` from the terminal.

### Expected behavior
Mathematica should open (and work!).  Note that it *does* work just fine immediately after activation, before it is closed.

### Screenshots
The mathematica startup process gets to here:
![image](https://user-images.githubusercontent.com/567092/212735682-6705f852-c895-4e9c-85af-44c99940a8db.png)
and then opens this popup dialog:
![image](https://user-images.githubusercontent.com/567092/212733358-7cfa5b36-efc4-4211-8384-369cea61f395.png)
If I close the dialog, a new one opens up with different garbage at the bottom (after `The error was:`).  After the fourth dialog, Mathematica just crashes and prints the following to the terminal (from which I ran `mathematica`):
```
/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathematica-13.2.0/libexec/Mathematica/Executables/.mathematica-wrapped: line 154: 69844 Segmentation fault      (core dumped) "${MathematicaFE}" ${MESA_FLAG} -topDirectory "${TopDirectory}" "$@"

LinkConnect::linkc: -- Message text not found -- (LinkObject[8sni3_shm, 3, 1])
```
Note that line 154 of `/nix/store/.../.mathematica-wrapped` is the last non-empty line of that file.

### Additional context

I also get the error `sh: line 1: /bin/uname: No such file or directory` in the terminal as soon as I run `mathematica`.  However, this error might be a red herring.

The **GOOD NEWS** is that I found a hack to make Mathematica work: delete the file `~/.Mathematica/Autoload/PacletManager/Configuration/FrontEnd/init_13.2.0.0.m`.  Mathematica will re-write this file every time it opens, so my fix is to have a shell alias that deletes this file and runs `mathematica`.  Note that I still get the error `sh: line 1: /bin/uname: No such file or directory` every time I run `mathematica`, but everything (that I have tried thus far) still works otherwise.

I am attaching the offending `init_13.2.0.0.m` file [here](https://github.com/NixOS/nixpkgs/files/10428234/init_13.2.0.0.m.txt) in case it helps (it's a plain text file, so added a `.txt` extension as otherwise github would not let me attach it).

### Notify maintainers
@herberteuler

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.10-zen2, NixOS, 22.11 (Raccoon), 22.11.1580.e285dd0ca97`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, nixos-hardware, nixos-unstable"`
 - channels(perlinm): `"home-manager-22.11.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by herberteuler** [comment] 2023-01-17 09:01
First of all, I cannot reproduce this error here. Secondly, the missing of `/bin/uname` should not be the cause of the problem as it has existed for a very long time and doesn't prevent Mathematica from starting. So according to your clues, it appears that `init_13.2.0.0.m` has something to do with the crash. Instead of deleting the whole file, what will happen if you put an empty file under the same name?

**Comment by perlinm** [comment] 2023-01-18 03:30
Oh, silly of me to forget: I am using the `sway` window manager, so this could be a `sway` (or `wayland`) issue.  I'll test out other window managers to see if that causes a difference.  I'm about to be off the grid for a few weeks though, so I'll probably get back to this issue in about a month.

I agree that the missing `/bin/uname` is unlikely to be the problem.  I mentioned that error just in case.

As for `init-13.2.0.0.m`: replacing it with an empty file (`rm init_13.2.0.0.m && touch init_13.2.0.0.m`) seems to have the same effect as deleting it.  Mathematica starts up and works, but then it re-writes this file with the same content as before (after which Mathematica won't start unless the file is deleted or cleared).  The same happens if I try to write a trivial init file with `echo SetOptions[] > init_13.2.0.0.m`.

**Comment by herberteuler** [comment] 2023-01-18 07:49
FYI below is the differences between the `init_13.2.0.0.m` you presented and on my machine:

```
2,4c2,4
< PalettePath -> {FrontEnd`FileName[{$UserBaseDirectory, "Paclets", 
<     "Repository", "PresenterTools-1.9.9", "FrontEnd", "Palettes"}, 
<    "PacletManager" -> True, "Prepend" -> True], 
---
> PalettePath -> {FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47l\
> y0-mathematica-13.2.0/libexec/Mathematica/SystemFiles/Components/CodeFormatte\
> r/FrontEnd", "Palettes"}, "PacletManager" -> True, "Prepend" -> True], 
6c6
< -13.2.0/libexec/Mathematica/SystemFiles/Components/CodeFormatter/FrontEnd", 
---
> -13.2.0/libexec/Mathematica/SystemFiles/Components/CodeInspector/FrontEnd", 
9c9
< -13.2.0/libexec/Mathematica/SystemFiles/Components/CodeInspector/FrontEnd", 
---
> -13.2.0/libexec/Mathematica/SystemFiles/Components/PresenterTools/FrontEnd", 
16,29c16,17
< 47ly0-mathematica-13.2.0/libexec/Mathematica/SystemFiles/Components/CloudDial\
< ogs/FrontEnd", "StyleSheets"}, "PacletManager" -> True, "Prepend" -> True], 
<   FrontEnd`FileName[{$UserBaseDirectory, "Paclets", "Repository", 
<     "PresenterTools-1.9.9", "FrontEnd", "StyleSheets"}, 
<    "PacletManager" -> True, "Prepend" -> True], 
<   FrontEnd`FileName[{$UserBaseDirectory, "Paclets", "Repository", 
<     "QuestionFramework-1.5.9", "FrontEndStyles", "StyleSheets"}, 
<    "PacletManager" -> True, "Prepend" -> True], 
<   FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathematica\
< -13.2.0/libexec/Mathematica/SystemFiles/Components/WolframAlphaClient/FrontEn\
< d", "StyleSheets"}, "PacletManager" -> True, "Prepend" -> True], 
<   FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathematica\
< -13.2.0/libexec/Mathematica/SystemFiles/Links/DataResource/FrontEnd", 
<     "StyleSheets"}, "PacletManager" -> True, "Prepend" -> True], 
---
> 47ly0-mathematica-13.2.0/libexec/Mathematica/SystemFiles/Links/DataResource/F\
> rontEnd", "StyleSheets"}, "PacletManager" -> True, "Prepend" -> True], 
36a25,27
> -13.2.0/libexec/Mathematica/SystemFiles/Components/CloudDialogs/FrontEnd", 
>     "StyleSheets"}, "PacletManager" -> True, "Prepend" -> True], 
>   FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathematica\
48a40,45
> -13.2.0/libexec/Mathematica/SystemFiles/Components/PresenterTools/FrontEnd", 
>     "StyleSheets"}, "PacletManager" -> True, "Prepend" -> True], 
>   FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathematica\
> -13.2.0/libexec/Mathematica/SystemFiles/Components/QuestionFramework/FrontEnd\
> Styles", "StyleSheets"}, "PacletManager" -> True, "Prepend" -> True], 
>   FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathematica\
51a49,51
> -13.2.0/libexec/Mathematica/SystemFiles/Components/WolframAlphaClient/FrontEn\
> d", "StyleSheets"}, "PacletManager" -> True, "Prepend" -> True], 
>   FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathematica\
66c66
< ca-13.2.0/libexec/Mathematica/SystemFiles/Components/CloudDialogs/FrontEnd", 
---
> ca-13.2.0/libexec/Mathematica/SystemFiles/Links/CloudObject/FrontEnd", 
68,82d67
<     FrontEnd`FileName[{$UserBaseDirectory, "Paclets", "Repository", 
<       "CloudObject-13.2.2", "FrontEnd", "TextResources"}, 
<      "PacletManager" -> True, "Prepend" -> True], 
<     FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathemati\
< ca-13.2.0/libexec/Mathematica/SystemFiles/Components/NotebookToolbar/FrontEnd\
< ", "TextResources"}, "PacletManager" -> True, "Prepend" -> True], 
<     FrontEnd`FileName[{$UserBaseDirectory, "Paclets", "Repository", 
<       "PresenterTools-1.9.9", "FrontEnd", "TextResources"}, 
<      "PacletManager" -> True, "Prepend" -> True], 
<     FrontEnd`FileName[{$UserBaseDirectory, "Paclets", "Repository", 
<       "QuestionFramework-1.5.9", "FrontEnd", "TextResources"}, 
<      "PacletManager" -> True, "Prepend" -> True], 
<     FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathemati\
< ca-13.2.0/libexec/Mathematica/SystemFiles/Components/WolframAlphaClient/Front\
< End", "TextResources"}, "PacletManager" -> True, "Prepend" -> True], 
89a75,77
> ca-13.2.0/libexec/Mathematica/SystemFiles/Components/CloudDialogs/FrontEnd", 
>       "TextResources"}, "PacletManager" -> True, "Prepend" -> True], 
>     FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathemati\
101a90,92
> ca-13.2.0/libexec/Mathematica/SystemFiles/Components/NotebookToolbar/FrontEnd\
> ", "TextResources"}, "PacletManager" -> True, "Prepend" -> True], 
>     FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathemati\
104a96,104
> ca-13.2.0/libexec/Mathematica/SystemFiles/Components/PresenterTools/FrontEnd"\
> , "TextResources"}, "PacletManager" -> True, "Prepend" -> True], 
>     FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathemati\
> ca-13.2.0/libexec/Mathematica/SystemFiles/Components/QuestionFramework/FrontE\
> nd", "TextResources"}, "PacletManager" -> True, "Prepend" -> True], 
>     FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathemati\
> ca-13.2.0/libexec/Mathematica/SystemFiles/Components/WolframAlphaClient/Front\
> End", "TextResources"}, "PacletManager" -> True, "Prepend" -> True], 
>     FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathemati\
114,154c114,154
< ls7qr47ly0-mathematica-13.2.0/libexec/Mathematica/SystemFiles/Components/Clou\
< dDialogs/FrontEnd", "SystemResources"}, "PacletManager" -> True, 
<      "Prepend" -> True], FrontEnd`FileName[{$UserBaseDirectory, "Paclets", 
<       "Repository", "CloudObject-13.2.2", "FrontEnd", "SystemResources"}, 
<      "PacletManager" -> True, "Prepend" -> True], 
<     FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathemati\
< ca-13.2.0/libexec/Mathematica/SystemFiles/Components/NotebookToolbar/FrontEnd\
< ", "SystemResources"}, "PacletManager" -> True, "Prepend" -> True], 
<     FrontEnd`FileName[{$UserBaseDirectory, "Paclets", "Repository", 
<       "PresenterTools-1.9.9", "FrontEnd", "SystemResources"}, 
<      "PacletManager" -> True, "Prepend" -> True], 
<     FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathemati\
< ca-13.2.0/libexec/Mathematica/SystemFiles/Components/WolframAlphaClient/Front\
< End", "SystemResources"}, "PacletManager" -> True, "Prepend" -> True], 
<     FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathemati\
< ca-13.2.0/libexec/Mathematica/SystemFiles/Components/CodeFormatter/FrontEnd", 
<       "SystemResources"}, "PacletManager" -> True, "Prepend" -> True], 
<     FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathemati\
< ca-13.2.0/libexec/Mathematica/SystemFiles/Components/DrawingTools/FrontEnd", 
<       "SystemResources"}, "PacletManager" -> True, "Prepend" -> True], 
<     FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathemati\
< ca-13.2.0/libexec/Mathematica/SystemFiles/Components/FormNotebook/FrontEnd", 
<       "SystemResources"}, "PacletManager" -> True, "Prepend" -> True], 
<     FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathemati\
< ca-13.2.0/libexec/Mathematica/SystemFiles/Components/PredictiveInterface/Fron\
< tEnd", "SystemResources"}, "PacletManager" -> True, "Prepend" -> True], 
<     FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathemati\
< ca-13.2.0/libexec/Mathematica/AddOns/Applications/ChatTools/FrontEnd", 
<       "SystemResources"}, "PacletManager" -> True, "Prepend" -> True], 
<     FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathemati\
< ca-13.2.0/libexec/Mathematica/AddOns/Applications/DocumentationTools/FrontEnd\
< ", "SystemResources"}, "PacletManager" -> True, "Prepend" -> True], 
<     ParentList, FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47l\
< y0-mathematica-13.2.0/libexec/Mathematica/SystemFiles/Components/BingSearch/F\
< rontEnd", "SystemResources"}, "PacletManager" -> True], 
<     FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathemati\
< ca-13.2.0/libexec/Mathematica/SystemFiles/Components/GoogleCustomSearch/Front\
< End", "SystemResources"}, "PacletManager" -> True], 
<     FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathemati\
< ca-13.2.0/libexec/Mathematica/SystemFiles/Components/GoogleTranslate/FrontEnd\
< ", "SystemResources"}, "PacletManager" -> True], 
---
> ls7qr47ly0-mathematica-13.2.0/libexec/Mathematica/SystemFiles/Links/CloudObje\
> ct/FrontEnd", "SystemResources"}, "PacletManager" -> True, 
>      "Prepend" -> True], FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3n\
> lls7qr47ly0-mathematica-13.2.0/libexec/Mathematica/SystemFiles/Components/Clo\
> udDialogs/FrontEnd", "SystemResources"}, "PacletManager" -> True, 
>      "Prepend" -> True], FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3n\
> lls7qr47ly0-mathematica-13.2.0/libexec/Mathematica/SystemFiles/Components/Cod\
> eFormatter/FrontEnd", "SystemResources"}, "PacletManager" -> True, 
>      "Prepend" -> True], FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3n\
> lls7qr47ly0-mathematica-13.2.0/libexec/Mathematica/SystemFiles/Components/Dra\
> wingTools/FrontEnd", "SystemResources"}, "PacletManager" -> True, 
>      "Prepend" -> True], FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3n\
> lls7qr47ly0-mathematica-13.2.0/libexec/Mathematica/SystemFiles/Components/For\
> mNotebook/FrontEnd", "SystemResources"}, "PacletManager" -> True, 
>      "Prepend" -> True], FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3n\
> lls7qr47ly0-mathematica-13.2.0/libexec/Mathematica/SystemFiles/Components/Not\
> ebookToolbar/FrontEnd", "SystemResources"}, "PacletManager" -> True, 
>      "Prepend" -> True], FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3n\
> lls7qr47ly0-mathematica-13.2.0/libexec/Mathematica/SystemFiles/Components/Pre\
> dictiveInterface/FrontEnd", "SystemResources"}, "PacletManager" -> True, 
>      "Prepend" -> True], FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3n\
> lls7qr47ly0-mathematica-13.2.0/libexec/Mathematica/SystemFiles/Components/Pre\
> senterTools/FrontEnd", "SystemResources"}, "PacletManager" -> True, 
>      "Prepend" -> True], FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3n\
> lls7qr47ly0-mathematica-13.2.0/libexec/Mathematica/SystemFiles/Components/Wol\
> framAlphaClient/FrontEnd", "SystemResources"}, "PacletManager" -> True, 
>      "Prepend" -> True], FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3n\
> lls7qr47ly0-mathematica-13.2.0/libexec/Mathematica/AddOns/Applications/ChatTo\
> ols/FrontEnd", "SystemResources"}, "PacletManager" -> True, 
>      "Prepend" -> True], FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3n\
> lls7qr47ly0-mathematica-13.2.0/libexec/Mathematica/AddOns/Applications/Docume\
> ntationTools/FrontEnd", "SystemResources"}, "PacletManager" -> True, 
>      "Prepend" -> True], ParentList, FrontEnd`FileName[
>      {"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathematica-13.2.0/libexec\
> /Mathematica/SystemFiles/Components/BingSearch/FrontEnd", "SystemResources"}, 
>      "PacletManager" -> True], FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc\
> 69ax3nlls7qr47ly0-mathematica-13.2.0/libexec/Mathematica/SystemFiles/Componen\
> ts/GoogleCustomSearch/FrontEnd", "SystemResources"}, 
>      "PacletManager" -> True], FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc\
> 69ax3nlls7qr47ly0-mathematica-13.2.0/libexec/Mathematica/SystemFiles/Componen\
> ts/GoogleTranslate/FrontEnd", "SystemResources"}, "PacletManager" -> True], 
168,180c168
< y0-mathematica-13.2.0/libexec/Mathematica/SystemFiles/Components/CloudDialogs\
< /FrontEnd", "SystemResources", "Bitmaps"}, "PacletManager" -> True, 
<      "Prepend" -> True], FrontEnd`FileName[{$UserBaseDirectory, "Paclets", 
<       "Repository", "CloudObject-13.2.2", "FrontEnd", "SystemResources", 
<       "Bitmaps"}, "PacletManager" -> True, "Prepend" -> True], 
<     FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathemati\
< ca-13.2.0/libexec/Mathematica/SystemFiles/Components/NotebookToolbar/FrontEnd\
< ", "SystemResources", "Bitmaps"}, "PacletManager" -> True, 
<      "Prepend" -> True], FrontEnd`FileName[{$UserBaseDirectory, "Paclets", 
<       "Repository", "PresenterTools-1.9.9", "FrontEnd", "SystemResources", 
<       "Bitmaps"}, "PacletManager" -> True, "Prepend" -> True], 
<     FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathemati\
< ca-13.2.0/libexec/Mathematica/SystemFiles/Components/WolframAlphaClient/Front\
---
> y0-mathematica-13.2.0/libexec/Mathematica/SystemFiles/Links/CloudObject/Front\
182a171,173
> lls7qr47ly0-mathematica-13.2.0/libexec/Mathematica/SystemFiles/Components/Clo\
> udDialogs/FrontEnd", "SystemResources", "Bitmaps"}, "PacletManager" -> True, 
>      "Prepend" -> True], FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3n\
191a183,189
> lls7qr47ly0-mathematica-13.2.0/libexec/Mathematica/SystemFiles/Components/Not\
> ebookToolbar/FrontEnd", "SystemResources", "Bitmaps"}, 
>      "PacletManager" -> True, "Prepend" -> True], 
>     FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathemati\
> ca-13.2.0/libexec/Mathematica/SystemFiles/Components/PredictiveInterface/Fron\
> tEnd", "SystemResources", "Bitmaps"}, "PacletManager" -> True, 
>      "Prepend" -> True], FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3n\
193c191
< dictiveInterface/FrontEnd", "SystemResources", "Bitmaps"}, 
---
> senterTools/FrontEnd", "SystemResources", "Bitmaps"}, 
196,197c194,198
< ca-13.2.0/libexec/Mathematica/AddOns/Applications/ChatTools/FrontEnd", 
<       "SystemResources", "Bitmaps"}, "PacletManager" -> True, 
---
> ca-13.2.0/libexec/Mathematica/SystemFiles/Components/WolframAlphaClient/Front\
> End", "SystemResources", "Bitmaps"}, "PacletManager" -> True, 
>      "Prepend" -> True], FrontEnd`FileName[{"/nix/store/4s185wg02szp1wc69ax3n\
> lls7qr47ly0-mathematica-13.2.0/libexec/Mathematica/AddOns/Applications/ChatTo\
> ols/FrontEnd", "SystemResources", "Bitmaps"}, "PacletManager" -> True, 
242,243c243,245
<    {$UserBaseDirectory, "Paclets", "Repository", "SpellingData-1.0.10", 
<     "SpellingDictionaries"}, "PacletManager" -> True]}
---
>    {"/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathematica-13.2.0/libexec/M\
> athematica/SystemFiles/Components/SpellingData/SpellingDictionaries"}, 
>    "PacletManager" -> True]}
```

It's not a huge difference.

On another thought, what will happen if you back up the whole `~/.Mathematica` directory and start Mathematica fresh?

**Comment by perlinm** [comment] 2023-01-18 08:07
Deleting the `~/.Mathematica` and starting fresh causes Mathematica to behave as if I freshly installed it.  I get a prompt to activate Mathematica, after which it behaves exactly as described above.  In fact, that is how I discovered my hack with `init-13.2.0.0.m`: I tried deleting directories within `~/.Mathematica` one by one until I found a difference in behavior.

**Comment by herberteuler** [comment] 2023-01-18 08:56
Okay, I started Mathematica fresh and can reproduce the issue here. The `init_13.2.0.0.m` file is quite similar to yours. I'll dig into it later.

**Comment by jys1670** [comment] 2023-01-18 13:46
I've also ran into this problem, as well as several others. It seems that mathematica-cuda does not work on `13.2` due to missing libraries, while working on `13.0` or so at the same time. Also bunch of older mathematica versions do not start due to annoying `qt platform plugin` error, that was supposed to be fixed, but randomly returns.
I believe that it's caused by some dependency conflicts, probably autopatchelf patches way too many things, didn't dig deeper into that though.

Instead I decided to use FHS hack, it provides some benefits:
1) Update of dependencies does not trigger long reinstallation process, also it's easier to debug stuff. My list of dependencies turned out to be significantly smaller than in generic.nix.
2) Cuda works, no qt platform plugin errors (at least on `13.2`)

[Here is file](https://gist.github.com/jys1670/23d901f53daff842eb2fd984686d2361), with example usage as follows:
```nix
mathematica-fhs = pkgs.callPackage ./mathematica-fhs.nix {
      nvidia_x11 = config.boot.kernelPackages.nvidia_x11;
      cudaPackages = cudaPackages_11_6;
}
```

**Comment by herberteuler** [comment] 2023-01-18 13:46
I spent some time but found no solution yet. In the meantime, `mathematica -clean` can be used to run Mathematica, albeit without customized preferences.

**Comment by herberteuler** [comment] 2023-01-18 15:11
@jys1670 I see the missing `libnvrtc.so` error, which I'll fix in another PR, thanks. Also, do you mind if I adopt your FHS approach later?

Anyway, you running into the same problem here sounds like the problem is introduced by the new version instead of the installation script, which needs more investigation.

**Comment by jys1670** [comment] 2023-01-18 16:38
> @jys1670 I see the missing `libnvrtc.so` error, which I'll fix in another PR, thanks. Also, do you mind if I adopt your FHS approach later?
> 
> Anyway, you running into the same problem here sounds like the problem is introduced by the new version instead of the installation script, which needs more investigation.

Sure, I don't mind! 

As for installation script, I think that  "generalization" of installation process of different mathematica version causes problems.
A while ago I tried to update `13.0.1` to `13.1.0` and old `qt platform plugin` error occurred. I solved it with bruteforce approach: randomly reduced amount of elements in `buildInputs` from nixpkgs mathematica until it worked. It was funny, if you put more things than needed - error appears, if you put too few - error, but different one. Okay, version `13.1.0` worked, but looks like old ones became broken (I don't remember which version I tried exactly, but whatever, I was happy with `13.1.0`).

Then, once `13.2.0` got released, my derivation for `13.1.0` with replaced 13.2 `src` did not seem to work, once again `qt platform plugin` error. This is when i gave up on autopatchelf approach, it just takes too much time to test.
Instead I used that FHS hack and `strace -f -e trace=openat mathematica-fhs` to track minimum amount of needed dependencies (creation of different FHS envs is really fast, mathematica is not reinstalled) and got it working.

**Comment by herberteuler** [comment] 2023-01-31 11:17
Update: I'm contacting a Wolfram employee for help. I'll post all updates later on.

**Comment by herberteuler** [comment] 2023-05-24 00:17
> The fundamental problem is that Nix store paths are hardcoded into Mathematica's config files at runtime, right? So it would seem that the FHS env is not a hack, but the right approach here to make this proprietary piece of software work. Can confirm the `--clean`/`--cleanStart` workaround works if you're not overly attached to your preferences.

Right, that is a possible reason. I have just finished a vital course last Friday, so I will have time to test the FHS solution in the following days.

**Comment by herberteuler** [comment] 2023-06-03 13:32
FWIW, here is the relevant `strace` log seemingly related to the strange file name:

```
53319:[pid   221] openat(AT_FDCWD, "/nix/store/cmwmvjya6crz4b4f8mz43sq2l2icv6cs-mathematica-unpacked-13.2.1/libexec/Mathematica/SystemFiles/FrontEnd/StyleSheets/StylesheetFormatting.nb", O_RDWR) = -1 EACCES (Permission denied)
53320:[pid   221] openat(AT_FDCWD, "/nix/store/cmwmvjya6crz4b4f8mz43sq2l2icv6cs-mathematica-unpacked-13.2.1/libexec/Mathematica/SystemFiles/FrontEnd/StyleSheets/StylesheetFormatting.nb", O_RDONLY) = 79
53326:[pid   221] openat(AT_FDCWD, "/nix/store/cmwmvjya6crz4b4f8mz43sq2l2icv6cs-mathematica-unpacked-13.2.1/libexec/Mathematica/SystemFiles/FrontEnd/StyleSheets/StylesheetFormatting.nb", O_RDONLY) = 80
53404:[pid   221] access("/nix/store/cmwmvjya6crz4b4f8mz43sq2l2icv6cs-mathematica-unpacked-13.2.1/libexec/Mathematica/SystemFiles/Links/DataResource/FrontEnd/StyleSheets", F_OK <unfinished ...>
53407:[pid   221] access("/nix/store/cmwmvjya6crz4b4f8mz43sq2l2icv6cs-mathematica-unpacked-13.2.1/libexec/Mathematica/SystemFiles/Links/DataResource/FrontEnd/StyleSheets/English/X/Linux-x86-64/\\.80\\:6170\\:6b63\\:7461\\:2f61\\:696c\\:6369\\:7953\\:6578\\:6369", R_OK) = -1 ENOENT (No such file or directory)
```

The Wolfram employee I contacted before told me the issue he reported internally had yet to receive a response. Earlier today, I wrote to Wolfram support for this issue. Hope there will be more information from them.

**Comment by arnoudbuzing** [comment] 2023-06-13 15:50
@herberteuler -- Are you the developer of this installer package?

I work for Wolfram and can try to help, but I am 100% unfamiliar with NixOS.

Perhaps as a first question, can you confirm that this directory exists on  a system that shows that startup problem?

```
/nix/store/4s185wg02szp1wc69ax3nlls7qr47ly0-mathematica-13.2.0/libexec/Mathematica
```

Assuming it exists, can you check the file permissions (obviously the user who starts the process should have read and execute permissions on the files in the Mathematica product layout). Please show me that this is the case, for example for the file with the 'permission denied' warning given by strace:

```
53319:[pid   221] openat(AT_FDCWD, "/nix/store/cmwmvjya6crz4b4f8mz43sq2l2icv6cs-mathematica-unpacked-13.2.1/libexec/Mathematica/SystemFiles/FrontEnd/StyleSheets/StylesheetFormatting.nb", O_RDWR) = -1 EACCES (Permission denied)

```

**Comment by herberteuler** [comment] 2023-06-13 23:35
Hi Arnoud, thanks for the help!

Yes, I am the developer of the installer package. For the directory and file, I can confirm that they are accessible:

```
$ ls -l /nix/store/cmwmvjya6crz4b4f8mz43sq2l2icv6cs-mathematica-unpacked-13.2.1/libexec/
total 4
dr-xr-xr-x 7 nobody nogroup 4096 Jan  1  1970 Mathematica
$ ls -l /nix/store/cmwmvjya6crz4b4f8mz43sq2l2icv6cs-mathematica-unpacked-13.2.1/libexec/Mathematica/SystemFiles/FrontEnd/StyleSheets/StylesheetFormatting.nb 
-r--r--r-- 1 nobody nogroup 25686 Jan  1  1970 /nix/store/cmwmvjya6crz4b4f8mz43sq2l2icv6cs-mathematica-unpacked-13.2.1/libexec/Mathematica/SystemFiles/FrontEnd/StyleSheets/StylesheetFormatting.nb
```

The user, group, and mtime are modified by Nix during derivation realization and should not affect the accessibility of the files.

Meanwhile, I got the following reply from Wolfram Support:

> This issue has been recently reported on other Linux distributions currently supported by Mathematica. Our developers have found that the fully resolved installation path is changing from one launch to the next, however, they couldn't pinpoint the root cause for this behavior and they are still working on it.

I will forward any updates thereafter here as well.

**Comment by herberteuler** [comment] 2023-07-26 06:10
With Mathematica 13.3.0, the issue has gone away here. Could someone else please verify it?

**Comment by perlinm** [comment] 2023-07-30 16:45
I do not have this issue any more, although I am using Mathematica 13.2.1.  Should I try to install 13.3.0 as well to check?

**Comment by herberteuler** [comment] 2023-07-30 17:59
> I do not have this issue any more, although I am using Mathematica 13.2.1. Should I try to install 13.3.0 as well to check?

Only if it is convenient for you as an upgrade could take a long time; otherwise, there will always be the next time when you inevitably need to upgrade.

**Comment by jys1670** [comment] 2023-07-30 19:41
> With Mathematica 13.3.0, the issue has gone away here. Could someone else please verify it?

Yep, now I don't have any problems on second machine with 13.3.0
Also I managed to completely avoid this error on my main PC by keeping old `.Mathematica` folder (every Mathematica update used old settings and error never occurred)

**Comment by herberteuler** [comment] 2023-07-31 00:11
Okay, I am closing this issue for now. If someone still has it, we will reopen this one.

**Closed by herberteuler** 2023-07-31 00:11 UTC
Labels: 0.kind: bug
