### ISSUE TITLE
Package request: icestudio

### ISSUE THREAD

**Issue by alxpettit** [NixOS/nixpkgs#279137] opened 2024-01-06 10:38 UTC
**Project description**

Ice Studio is a self-contained visual IDE for FPGA programming and development. It's available in source tarball, AppImage, and prebuilt zips.

**Metadata**

* homepage URL: https://icestudio.io/
* source URL: https://github.com/FPGAwars/icestudio
* license: gpl2
* platforms: linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-01-06 22:51
duplicate of #275765

**Closed by eclairevoyant** 2024-01-06 22:51 UTC
Labels: 2.status: duplicate, 0.kind: packaging request

**Comment by alxpettit** [comment] 2024-01-06 23:57
Whoops! Totally forgot about that, sorry. :P
