### ISSUE TITLE
Build failure: bitwarden-cli

### ISSUE THREAD

**Issue by multivac61** [NixOS/nixpkgs#320997] opened 2024-06-19 10:55 UTC
### Steps To Reproduce

1. build bitwarden-cli on aarch64-darwin on unstable

### Build log

![CleanShot 2024-06-19 at 10 54 40@2x](https://github.com/NixOS/nixpkgs/assets/4436129/a83e219f-54f1-4e56-95de-6b93ebe7b0fa)

### Notify maintainers

@dotlambda 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.5.0, macOS 14.5`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.22.1`
 - channels(root): `"unstable"`
 - nixpkgs: `/nix/store/5w7nhyvrgsa81h0kyifmbl6j97hvlzh5-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by afh** [comment] 2024-06-23 20:21
This seems to be a duplicate of #315667

**Comment by multivac61** [comment] 2024-06-24 07:14
Correct. Let's close this.

**Closed** 2024-06-24 07:14 UTC
Labels: 6.topic: darwin, 0.kind: build failure
