### ISSUE TITLE
clang-tidy no longer include in llvm 13

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#147302] opened 2021-11-24 21:43 UTC
### Describe the bug

```
$ nix-shell -p clang-tools --run 'clang-tidy --help'
/nix/store/8v1mjgjahw321256p3ndl8mpk2gmnlx6-clang-tools-13.0.0/bin/clang-tidy: line 27: /nix/store/avxqsg0jzw64m6imirvwyif2mjr5dl1m-clang-13.0.0/bin/clang-tidy: No such file or directory
```

While llvmPackages_12.clang-unwrapped still has clang-tidy, llvmPackages_13 no longer has it.
I assume we have to switch our build system to be llvm components: https://github.com/archlinux/svntogit-packages/blob/packages/clang/trunk/PKGBUILD

Rather than changing to the clang directory and build tools from there.

**Comment by Mic92** [comment] 2021-11-24 21:50
Workaround is to build clang-tools like this:

```
(clang-tools.override { llvmPackages = llvmPackages_12; }) 
```

**Comment by quantmint** [comment] 2021-12-06 12:07
It does work now, this issue should be closed.

**Comment by bjornfor** [comment] 2021-12-06 17:45
Duplicate of https://github.com/NixOS/nixpkgs/issues/146659, which is fixed.

**Closed by bjornfor** 2021-12-06 17:45 UTC
Labels: 0.kind: bug
