### ISSUE TITLE
Discord out of date

### ISSUE THREAD

**Issue by YellowOnion** [NixOS/nixpkgs#98085] opened 2020-09-16 09:27 UTC
![Screenshot from 2020-09-16 21-24-14](https://user-images.githubusercontent.com/364160/93318700-1f5f2000-f863-11ea-9ead-20621820bf00.png)

**Notify maintainers**

@ldesgoui @MP2E @tadeokondrak

**Comment by tadeokondrak** [comment] 2020-09-16 09:34
Duplicate of https://github.com/NixOS/nixpkgs/issues/97828

**Closed by tadeokondrak** 2020-09-16 09:34 UTC
Labels: 0.kind: bug
