### ISSUE TITLE
Build failure: python3.12-fabric

### ISSUE THREAD

**Issue by Xelef2000** [NixOS/nixpkgs#350160] opened 2024-10-21 06:58 UTC
### Steps To Reproduce

1. build azure-cli

### Build log

```
Successfully built azure_mgmt_synapse-2.1.0b5-py3-none-any.whl
Finished creating a wheel...
Finished executing pypaBuildPhase
Running phase: pythonRuntimeDepsCheckHook
Executing pythonRuntimeDepsCheck
Checking runtime dependencies for azure_mgmt_synapse-2.1.0b5-py3-none-any.whl
Running phase: pythonRemoveBinBytecodePhase
Running phase: pythonImportsCheckPhase
Executing pythonImportsCheckPhase
Check whether the following modules can be imported: fabric
Finished executing pythonRuntimeDepsCheck
Running phase: installPhase
Executing pypaInstallPhase
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "/nix/store/wfbjq35kxs6x83c3ncpfxdyl5gbhdx4h-python3-3.12.6/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/nix/store/0qqgcr7xvw922xqg7rkbzyg10ymgj6c5-python3.12-fabric-3.2.2/lib/python3.12/site-packages/fabric/__init__.py", line 3, in <module>
    from .connection import Config, Connection
  File "/nix/store/0qqgcr7xvw922xqg7rkbzyg10ymgj6c5-python3.12-fabric-3.2.2/lib/python3.12/site-packages/fabric/connection.py", line 9, in <module>
    from paramiko.agent import AgentRequestHandler
  File "/nix/store/hdsahpv8zxkcgl16gmkkxnks1f0dv8xw-python3.12-paramiko-3.5.0/lib/python3.12/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import (
  File "/nix/store/hdsahpv8zxkcgl16gmkkxnks1f0dv8xw-python3.12-paramiko-3.5.0/lib/python3.12/site-packages/paramiko/transport.py", line 99, in <module>
    from paramiko.ed25519key import Ed25519Key
  File "/nix/store/hdsahpv8zxkcgl16gmkkxnks1f0dv8xw-python3.12-paramiko-3.5.0/lib/python3.12/site-packages/paramiko/ed25519key.py", line 22, in <module>
    import nacl.signing
ModuleNotFoundError: No module named 'nacl'
error: builder for '/nix/store/dqn1gxci2qg165ymj8xichazan5pf4j0-python3.12-fabric-3.2.2.drv' failed with exit code 1;
       last 25 log lines:
       > Executing pythonImportsCheckPhase
       > Check whether the following modules can be imported: fabric
       > Traceback (most recent call last):
       >   File "<string>", line 1, in <module>
       >   File "<string>", line 1, in <lambda>
       >   File "/nix/store/wfbjq35kxs6x83c3ncpfxdyl5gbhdx4h-python3-3.12.6/lib/python3.12/importlib/__init__.py", line 90, in import_module
       >     return _bootstrap._gcd_import(name[level:], package, level)
       >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
       >   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
       >   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
       >   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
       >   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
       >   File "/nix/store/0qqgcr7xvw922xqg7rkbzyg10ymgj6c5-python3.12-fabric-3.2.2/lib/python3.12/site-packages/fabric/__init__.py", line 3, in <module>
       >     from .connection import Config, Connection
       >   File "/nix/store/0qqgcr7xvw922xqg7rkbzyg10ymgj6c5-python3.12-fabric-3.2.2/lib/python3.12/site-packages/fabric/connection.py", line 9, in <module>
       >     from paramiko.agent import AgentRequestHandler
       >   File "/nix/store/hdsahpv8zxkcgl16gmkkxnks1f0dv8xw-python3.12-paramiko-3.5.0/lib/python3.12/site-packages/paramiko/__init__.py", line 22, in <module>
       >     from paramiko.transport import (
       >   File "/nix/store/hdsahpv8zxkcgl16gmkkxnks1f0dv8xw-python3.12-paramiko-3.5.0/lib/python3.12/site-packages/paramiko/transport.py", line 99, in <module>
       >     from paramiko.ed25519key import Ed25519Key
       >   File "/nix/store/hdsahpv8zxkcgl16gmkkxnks1f0dv8xw-python3.12-paramiko-3.5.0/lib/python3.12/site-packages/paramiko/ed25519key.py", line 22, in <module>
       >     import nacl.signing
       > ModuleNotFoundError: No module named 'nacl'
       For full logs, run 'nix log /nix/store/dqn1gxci2qg165ymj8xichazan5pf4j0-python3.12-fabric-3.2.2.drv'.
error (ignored): error: cannot unlink '"/tmp/nix-build-python3.12-azure-cli-core-2.64.0.drv-1/build/azure-cli-2.64.0-src/src/azure-cli/azure/cli/command_modules/resource/tests"': Directory not empty
error: 1 dependencies of derivation '/nix/store/l6d69jfwwmn25jk8wl4qrniqdalrp8y1-python3.12-azure-cli-2.64.0.drv' failed to build

```

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.54, NixOS, 24.11 (Vicuna), 24.11.20241018.4c2fcb0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/riqkpszjqk02bi1wppfg8ip5xvh102qd-source`

```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fabaff** [comment] 2024-10-21 07:37
`paramiko`'s input were adjusted. Change is in `staging-next`.

**Comment by katexochen** [comment] 2024-10-23 07:46
Duplicate of https://github.com/NixOS/nixpkgs/issues/348995

**Comment by AkechiShiro** [comment] 2024-11-01 01:03
Anyone would know, when would the fix be expected to land in nixpkgs unstable from staging next ?

**Comment by katexochen** [comment] 2024-11-04 06:10
Fix is now in `unstable`.

**Closed by katexochen** 2024-11-04 06:10 UTC
Labels: 6.topic: python, 0.kind: build failure, 2.status: fix-in-staging
