### ISSUE TITLE
Build failure: smartgithg

### ISSUE THREAD

**Issue by e-sushi** [NixOS/nixpkgs#311142] opened 2024-05-12 19:07 UTC
### Steps To Reproduce

1. try to build package smartgithg from unstable repo

### Build log
```
trying https://www.syntevo.com/downloads/smartgit/smartgit-linux-23_1_2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
copying path '/nix/store/z2z69j5pdg9bdarl7d00ygr66zaq9igh-wrap-gapps-hook' from 'https://cache.nixos.org'...
100   250    0   250    0     0    305      0 --:--:-- --:--:-- --:--:--   305
100 38933    0 38933    0     0  42561      0 --:--:-- --:--:-- --:--:-- 42561
error: hash mismatch in fixed-output derivation '/nix/store/mbaxv105k7ldi18n6wi0lm0nd91f8pji-smartgit-linux-23_1_2.tar.gz.drv':
         specified: sha256-gXfHmRPUhs8s7IQIhN0vQyx8NpLrS28ufNNYOMA4AXw=
            got:    sha256-H+zE5kWqoGy3yNd83Ppinn7ptf/puw99KMr7LSG7jSI=

error: 1 dependencies of derivation '/nix/store/zbgnx69zarsbi6ijyda0d3wnaw5zi89v-smartgithg-23.1.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/05np8lw2agfga72160l3hi96iw31gx1d-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/4qjzy74q1a7967jvzg17jk609svv70rj-home-manager-generation.drv' failed to build
```

### Additional context

I'm using home-manager and trying to pull the package from unstable. It seems like just a problem with the hash not being set right and I don't know how or if I could fix that myself.

### Notify maintainers

@jraygauthier 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.82, NixOS, 23.11 (Tapir), 23.11.5648.44733514b72e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by MikaelFangel** [comment] 2024-05-13 12:14
Similar to: #225278

**Comment by gepbird** [comment] 2024-05-14 18:53
Duplicate of the aforementioned issue.

This is fixed by https://github.com/NixOS/nixpkgs/pull/311262, at least until upstream makes another release and deletes the current version used in nixpkgs.

**Closed by gepbird** 2024-05-14 18:53 UTC
Labels: 0.kind: build failure
