### ISSUE TITLE
NIX_SSL_CERT_FILE with mercurial (hg) on MacOS

### ISSUE THREAD

**Issue by layus** [NixOS/nixpkgs#27928] opened 2017-08-04 08:10 UTC
_opening a new issue for https://github.com/NixOS/nix/issues/921#issuecomment-320059299 from @xpe, and moved away from https://github.com/NixOS/nix/issues/1501_

**Original content:**

I think I might be facing a related problem. I'm using a recently updated macOS Nix installation with Nix-installed version of Mercurial (hg) and I'm getting this error:

hg clone https://bitbucket.org/eigen/eigen/
abort: could not find web.cacerts: /etc/ssl/certs/ca-certificates.crt

echo $NIX_SSL_CERT_FILE
/Users/xpe/.nix-profile/etc/ssl/certs/ca-bundle.crt

I'm using macOS 10.12.6 with nix-env (Nix) 1.11.13.

What should I try to diagnose, debug, and fix or workaround?

**Comment by layus** [comment] 2017-08-04 08:11
@xpe Looking into it, it seems that mercurial has a `cacert = /etc/ssl/certs/ca-certificates.crt` in https://github.com/NixOS/nixpkgs/blob/11e13306f7084c0b60a62dc5dd6a3cff92d41e79/pkgs/applications/version-management/mercurial/default.nix#L50. That path does not exist on MacOS, so it explains the failure.

Could you  try to add `cacerts = ` in your .hgrc ? Or `cacerts = $NIX_SSL_CERT_FILE` ? Or directly `cacerts =  /Users/xpe/.nix-profile/etc/ssl/certs/ca-bundle.crt` and report what works ?

**Comment by LnL7** [comment] 2017-08-05 13:32
Do you see the same issues with curl/git from nixpkgs or is it just mercurial?

**Comment by layus** [comment] 2017-08-17 07:26
@xpe, your input is most welcome here. I cannot test on darwin myself.

**Comment by jamtrott** [comment] 2017-08-18 14:01
Hi, @layus and @LnL7.

I just experienced this exact same problem myself.  I can confirm that it was fixed by adding the following to ~/.hgrc:

> [web]
> cacerts = $NIX_SSL_CERT_FILE


Moreover, I have not had any such problem with git, so it seems to be just mercurial.


Hope this helps!

**Comment by layus** [comment] 2017-08-18 14:21
@jamtrott Thanks!
Does it also work with no value, like this ?
```
[web]
cacerts = 
```

**Comment by jamtrott** [comment] 2017-08-18 14:24
@layus, no problem.  Yes, it does indeed seem to also work with no value.

**Closed** 2017-08-22 01:39 UTC
