### ISSUE TITLE
Plasma Wayland

### ISSUE THREAD

**Issue by bkchr** [NixOS/nixpkgs#43757] opened 2018-07-18 19:28 UTC
I finally want to get Plasma working on Wayland with Nixos.
After trying today the whole day getting this working, I'm desperate.
I think that the problem is something with missing permissions.
My current output is:
```
startplasmacompositor: Starting up...
dbus-daemon[28346]: [session uid=1000 pid=28346] Activating service name='org.freedesktop.systemd1' requested by ':1.1' (uid=1000 pid=28374 comm="/nix/store/6vc0h4kldq30wz0v3424srx3n456ivir-dbus-1")
dbus-daemon[28346]: [session uid=1000 pid=28346] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
dbus-update-activation-environment: warning: error sending to systemd: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.systemd1 exited with status 1
No backend specified through command line argument, trying auto resolution
FATAL ERROR: backend failed to initialize, exiting now
startplasmacompositor: Shutting down...
startplasmacompositor: Done.
```

I have the following patch applied:
```
diff --git a/nixos/modules/services/x11/display-managers/sddm.nix b/nixos/modules/services/x11/display-managers/sddm.nix
index 426b899586f..66e481bc6f5 100644
--- a/nixos/modules/services/x11/display-managers/sddm.nix
+++ b/nixos/modules/services/x11/display-managers/sddm.nix
@@ -58,6 +58,8 @@ let
 
     [Wayland]
     EnableHidpi=${if cfg.enableHidpi then "true" else "false"}
+    SessionCommand=${lib.getBin pkgs.sddm}/share/sddm/scripts/wayland-session
+    SessionDir=/etc/wayland
 
     ${optionalString cfg.autoLogin.enable ''
     [Autologin]
@@ -262,10 +264,21 @@ in
       home = "/var/lib/sddm";
       group = "sddm";
       uid = config.ids.uids.sddm;
+      extraGroups = [ "video" ];
     };
 
     environment.etc."sddm.conf".source = cfgFile;
 
+    environment.etc."wayland/plasma-wayland.desktop".text = ''
+      [Desktop Entry]
+      Encoding=UTF-8
+      Type=Application
+      Exec=/run/current-system/sw/bin/dbus-run-session ${lib.getBin pkgs.plasma-workspace}/bin/startplasmacompositor
+      TryExec=${lib.getBin pkgs.plasma-workspace}/bin/startplasmacompositor
+      DesktopNames=KDE
+      Name=Plasma-wayland
+    '';
+
     users.groups.sddm.gid = config.ids.gids.sddm;
 
     environment.systemPackages = [ sddm ];
```

Anyone has any further ideas? @peterhoeg @ttuegel @worldofpeace @adisbladis

**Comment by worldofpeace** [comment] 2018-07-18 21:49
I think I got this working from the command line. For sddm no though.

**Comment by peterhoeg** [comment] 2018-07-19 04:03
I've had it running since 5.11 (maybe 5.10) from sddm but haven't used it due to missing features: https://community.kde.org/Plasma/5.13_Errata

This should do it:
```
diff --git a/nixos/modules/services/x11/display-managers/sddm.nix b/nixos/modules/services/x11/display-managers/sddm.nix
index 8db7414e811..8f6e150df49 100644
--- a/nixos/modules/services/x11/display-managers/sddm.nix
+++ b/nixos/modules/services/x11/display-managers/sddm.nix
@@ -69,6 +69,8 @@ let
 
     [Wayland]
     EnableHidpi=${if cfg.enableHidpi then "true" else "false"}
+    SessionCommand=${lib.getBin pkgs.sddm}/share/sddm/scripts/wayland-session
+    SessionDir=/etc/wayland
 
     ${optionalString cfg.autoLogin.enable ''
     [Autologin]
@@ -277,6 +279,16 @@ in
 
     environment.etc."sddm.conf".source = cfgFile;
 
+    environment.etc."wayland/plasma-wayland.desktop".text = ''
+      [Desktop Entry]
+      Encoding=UTF-8
+      Type=Application
+      Exec=${lib.getBin pkgs.plasma-workspace}/bin/startplasmacompositor
+      TryExec=${lib.getBin pkgs.plasma-workspace}/bin/startplasmacompositor
+      DesktopNames=KDE
+      Name=Plasma-wayland
+    '';
+
     users.groups.sddm.gid = config.ids.gids.sddm;
 
     environment.systemPackages = [ sddm ];
```

**Comment by peterhoeg** [comment] 2018-07-19 05:38
>   @peterhoeg with that patch sddm seems to get stuck when authenticating in
>   a vm with the wayland session and has to be manually restarted.

I have admittedly not tried it recently but it definitely was working in the past.

**Comment by bkchr** [comment] 2018-07-23 17:16
I got a step further, adding my user to the `video` group, brings me further in executing Kwin. So this means, it is really a permission problem. I thought that `logind` should be responsible for setting up the correct permissions...
However, KWin still does not work as expected, the screen seems to not refresh.

**Comment by bkchr** [comment] 2018-07-23 22:37
I got it working! :D Now I just need to cleanup all the stuff :D

**Comment by bkchr** [comment] 2018-07-26 21:32
Here is my pr: https://github.com/NixOS/nixpkgs/pull/44139
The changes are not that big.
The next big question is, how do we want to support wayland in SDDM/Nixos? As I have written in the pr, the patch for setting up SDDM is still required. I did not wanted to change that much, because I don't know what is the preferred way.

**Comment by peterhoeg** [comment] 2018-07-29 08:52
I suggest having a look at how the X11 session files are handled and then simply doing it the same way. Polluting ```/etc/wayland``` isn't really the way to go but I did that on my side because it was easy to fiddle with.

**Comment by bkchr** [comment] 2018-07-29 08:56
Yeah I know, that is really hacky. The x11 desktop files are generated by us, but there is some work going on to switch to the provided desktop files.

**Comment by Chiiruno** [comment] 2018-09-25 05:57
Any updates on this?
I'd really like to be able to use Wayland, I remember it being great (but sometimes buggy) in GNOME!

**Comment by bkchr** [comment] 2018-09-25 06:40
Currently nothing new. I think there was some work to support Wayland desktop files from the login manager. That is the last piece that is missing, AFAIK

**Comment by Chiiruno** [comment] 2018-09-25 06:42
Is there a PR for that?
What's the different between that and the patch in #44139?

**Comment by bkchr** [comment] 2018-09-25 06:46
Not yet, the work that was done, was for gnome.
The patch you mentioned is just a hack. KDE already ships the desktop file, we just need to make sddm aware of it.

**Comment by Chiiruno** [comment] 2018-09-25 07:18
Okay.
Should probably add an issue to the project, since I did some limited testing.
Plasma on Wayland is very very choppy, lots of microstutters as if vsync was multiplied like 10 times.

**Comment by peterhoeg** [comment] 2018-09-25 07:29
I created that project as a place to gather all wayland related issues - it isn't as such a concerted effort to get plasma going. I haven't spent real time on it as wayland KDE is still missing features for my use case(s).

**Comment by peterhoeg** [comment] 2018-09-26 03:39
As a data point, I tried launching a KDE wayland session y'day which worked fine (except for the missing features).

**Comment by Chiiruno** [comment] 2018-09-26 03:40
It wasn't stuttery at all?

**Comment by Chiiruno** [comment] 2018-09-26 03:42
Perhaps my issue has to due with something between AMDGPU and KDE/Wayland...

**Comment by peterhoeg** [comment] 2018-09-26 09:34
I tried it on a laptop with haswell graphics fwiw - no graphics issues.

**Comment by Chiiruno** [comment] 2018-09-26 10:06
How strange. Latest nixpkgs, right?
I did test it out with x.org too to see if it wasn't some other issue, but who knows.

**Comment by matklad** [comment] 2019-02-26 19:54
Am I correct that the only missing bit is getting `plasma (wayland)` entry to SDDM? Could we close this issue and open a separate, specific one, about SDDM support? This is the top google result for `nixos plasma wayland`, and it's hard to get the accurate status from the comments here :)

**Comment by bkchr** [comment] 2019-02-26 20:01
I need to find some time to bring plasma Wayland to sddm. Should not be that hard anymore.

**Comment by peterhoeg** [comment] 2019-02-27 12:42
While you're at it, how about plasma 5.15 as well? ;-)

**Comment by bkchr** [comment] 2019-02-27 15:28
@peterhoeg there is already a pr: https://github.com/NixOS/nixpkgs/pull/55650

**Comment by florianjacob** [comment] 2019-02-27 19:09
On NixOS 18.09, with the sddm patch applied, when I choose wayland, I only get a black screen and then get back into sddm, without any meaningful error message in journal. As you all seem to be on unstable, I guess I'll wait for 19.03 and hope that it'll just work then.

**Comment by bkchr** [comment] 2019-02-27 21:46
I didn't use the patch currently, so maybe something broke in the meantime.

**Comment by bkchr** [comment] 2019-03-06 21:14
Here we go: https://github.com/NixOS/nixpkgs/pull/56988

**Comment by nrdxp** [comment] 2019-12-27 03:57
I'm getting:
```
qt.qpa.plugin: Could not load the Qt platform plugin "wayland-org.kde.kwin.qpa" in "" even though it was found.
```

when trying to run manually with:
```
dbus-run-session /nix/store/...plasma-workspace.../bin/startplasmacompositor
```

I got the SDDM session file to load by simply adding `pkgs.plasma-workspace` to `services.xserver.displayManager.extraSessionFilePackages`, but it doesn't work. Most likely with the same error as found above, though can't confirm since there are no journal messages.

**Comment by shatsky** [comment] 2020-04-23 22:49
@nrdxp same problem here. It's kwin_wayland which fails. With `env QT_DEBUG_PLUGINS=1` this message is preceded with:
`loaded library "/nix/store/1j0qllx2y9990hv9y5194c5wx7mgb2za-kwin-5.17.5-bin/lib/qt-5.12.7/plugins/platforms/KWinQpaPlugin.so"`

I've tracked this error to https://code.qt.io/cgit/qt/qtbase.git/tree/src/gui/kernel/qguiapplication.cpp?h=dev#n1234 . I see there's some magic happening in the line
`QGuiApplicationPrivate::platform_integration = QPlatformIntegrationFactory::create(name, arguments, argc, argv, platformPluginPath);`
Then it's expected that `QGuiApplicationPrivate::platform_integration` pointer becomes... something. However if it's nullptr, program aborts.

`loaded library` suggests that plugin library was successfully located and loaded (but failed to do something). There are no preceding "loaded library" messages, so it's probably not because of a conflict with some other plugin. 

Nix store path suggests that it's the instance of this plugin library which had been built from the same source with the same toolchain as the kwin_wayland binary (I'm explicitly launching `/nix/store/1j0qllx2y9990hv9y5194c5wx7mgb2za-kwin-5.17.5-bin/bin/kwin_wayland` to avoid any unwanted effects).

If I understand correctly, .cpp file with platform plugin loading logic is compiled into libQt5Core.so.5; ldd output for kwin_wayland tells that libQt5Core.so.5 dep is resolved into `/nix/store/bs23h160pamahkj9h47yqs0k6y97lnbj-qtbase-5.12.7/lib/libQt5Core.so.5` , under Nix store path which is dependency of kwin Nix store path within Nix dependency graph, so the instance of the library which loads the plugin library is the one which the kwin_wayland binary had been built against.

Regular Qt/KDE apps can be launched under Weston successfully (without Xwayland).

**Comment by shatsky** [comment] 2020-04-28 14:22
Now, the problem is that hardware acceleration is not working in kwin_wayland if it's launched with drm backend (i. e. from tty). I've tracked this to kwin compositing plugin selection mechanism ("SceneOpenGL" compositing plugin is responsible for initializing EGL, calling the code in mesa which actually adds wayland globals to compositor registry allowing clients to create hardware accelerated rendering contexts). For x11 backend, kwin_wayland instantiates "SceneOpenGL"; however, when run with drm backend, it initalizes "SceneQPainter" backend, which doesn't initialize EGL at all. Relevant code is in composite.cpp, `Compositor::setupStart()`. What I've already checked:
- KWinSceneOpenGL.so path (/nix/store/${kwin-output-bin}/lib/qt-5.12.7/plugins/org.kde.kwin.scenes/KWinSceneOpenGL.so) is among paths searched by `KPluginLoader::findPlugins()` (it is logged with `env QT_LOGGING_RULES="*.debug=true"` ; anyway, KWinSceneQPainter.so is in the same dir and wouldn't load otherwise)
- HAVE_GBM which is required for "SceneOpenGL" selection and EGL initialization on drm platform is possibly not set because of missing mesa dependency, but I've added overridden kwin to pkgs like
```
    kwin_with_gbm = pkgs.plasma5.kwin.overrideAttrs (oldAttrs: rec { 
      buildInputs = oldAttrs.buildInputs ++ [ pkgs.mesa ];
    });
```
and assured it's reported by cmake during build:
`-- Found gbm: /nix/store/8y2nakqqmqncp35w8ifdx4gc9b7lrzfn-mesa-19.3.3/lib/libgbm.so (found version "19.3.3") `
however, when I run this kwin_wayland binary which I identified like
```
nix-repl> :l <nixpkgs/nixos>         
Added 6 variables.

nix-repl> pkgs.kwin_with_gbm.outPath
"/nix/store/44ranqmbhxyc3wj46h4kjnv7xry1xxkz-kwin-5.17.5-bin"
```
, "SceneQPainter" is still instantiated instead of "SceneOpenGL"

**Comment by shatsky** [comment] 2020-05-01 21:13
Now, the problem is that normal Plasma Wayland startup routines (ones that run when `startplasma-wayland` is launched) fail because constructed environment becomes too large for kinit to handle, even with https://github.com/NixOS/nixpkgs/commit/c75860918f0e470bcc881414bd039d7c6c541a21 :
`/nix/store/6i37rkjvalxd903gmkd63bzp5bgddsyb-kinit-5.66.0/libexec/kf5/start_kdeinit: exceeded environment length limit`
`/nix/store/6i37rkjvalxd903gmkd63bzp5bgddsyb-kinit-5.66.0/libexec/kf5/start_kdeinit_wrapper" ("--kded", "+kcminit_startup") exited with code 1`

I have submitted proposal to change Qt plugin paths handling in nixpkgs, https://github.com/NixOS/nixpkgs/issues/86369 ; I think it will eradicate the need for these wrappers which build enormous env vars.

**Comment by pasqui23** [comment] 2020-10-28 22:41
still important to me

**Comment by hellst0rm** [comment] 2020-11-07 21:55
still important to me

**Comment by zyansheep** [comment] 2020-12-31 23:11
This would be cool, I've always wanted to move away from X but can't figure out how to configure wayland : (

**Comment by peterhoeg** [comment] 2021-03-22 12:57
This PR (and the one-liner mentioned in a comment) basically gets it going: https://github.com/NixOS/nixpkgs/pull/117102

**Closed** 2021-11-08 04:00 UTC
Labels: 6.topic: qt/kde
