### ISSUE TITLE
Expandable variables must be wrapped in {}

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#69631] opened 2019-09-27 05:16 UTC
**Describe the bug**

Noticed some weird errors in journalctl log so I thought I'd report them here in case they are important:

```
Sep 27 08:10:08 leevi sudo[1940]: jluttine : TTY=pts/1 ; PWD=/home/jluttine ; USER=root ; COMMAND=/run/wrappers/bin/su
Sep 27 08:10:08 leevi sudo[1940]: pam_env(sudo:session): Expandable variables must be wrapped in {} <$HOME/.icons:$HOME/.local/share/icons:@{HOME}/.nix-profile/share/icons:@{HOME}/.nix-profile/share/pixmaps:/etc/profiles/per-user/@{PAM_USER}/share/icons:/etc/profiles/per->
Sep 27 08:10:08 leevi sudo[1940]: pam_env(sudo:session): Expandable variables must be wrapped in {} <$HOME/.local/share/icons:@{HOME}/.nix-profile/share/icons:@{HOME}/.nix-profile/share/pixmaps:/etc/profiles/per-user/@{PAM_USER}/share/icons:/etc/profiles/per-user/@{PAM_US>
Sep 27 08:10:08 leevi sudo[1940]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 27 08:10:08 leevi su[1941]: Successful su for root by root
Sep 27 08:10:08 leevi su[1941]: pam_env(su:session): Expandable variables must be wrapped in {} <$HOME/.icons:$HOME/.local/share/icons:@{HOME}/.nix-profile/share/icons:@{HOME}/.nix-profile/share/pixmaps:/etc/profiles/per-user/@{PAM_USER}/share/icons:/etc/profiles/per-user>
Sep 27 08:10:08 leevi su[1941]: pam_env(su:session): Expandable variables must be wrapped in {} <$HOME/.local/share/icons:@{HOME}/.nix-profile/share/icons:@{HOME}/.nix-profile/share/pixmaps:/etc/profiles/per-user/@{PAM_USER}/share/icons:/etc/profiles/per-user/@{PAM_USER}/>
Sep 27 08:10:08 leevi su[1941]: pam_unix(su:session): session opened for user root by (uid=0)
```

**To Reproduce**
1. `sudo su`

I don't see anything broken, so maybe this doesn't matter. But they are in red color in the logs so it looks like they are important.

**Expected behavior**

No `Expandable variables must be wrapped ...` messages in the logs.

**Metadata**

```
$ nix run nixpkgs.nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.74, NixOS, 20.03.git.0adcf14 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by worldofpeace** [comment] 2019-09-27 05:24
Duplicate of https://github.com/NixOS/nixpkgs/issues/69316, I'll get around to fixing eventually (or hopefully someone more available could contribute this)

**Closed by worldofpeace** 2019-09-27 05:24 UTC
Labels: 0.kind: bug
