### ISSUE TITLE
Howdy: pam Face auth

### ISSUE THREAD

**Issue by peterromfeldhk** [NixOS/nixpkgs#169572] opened 2022-04-21 11:33 UTC
**Project description**
Windows Hello™ style authentication for Linux.
Face ID pam

**Metadata**

* homepage URL: https://github.com/boltgolt/howdy
* source URL: https://github.com/boltgolt/howdy
* license: mit
* platforms: linux

**Comment by ishammahajan** [comment] 2022-10-09 22:40
This would be wonderful to have as a package. I can try making it with my preliminary NixOS knowledge if no one else is on it.

**Comment by bjornfor** [comment] 2023-01-15 16:07
Duplicate of https://github.com/NixOS/nixpkgs/issues/76928.

**Closed by bjornfor** 2023-01-15 16:07 UTC
Labels: 0.kind: packaging request
