### ISSUE TITLE
Guake won't start on NixOS 19.03

### ISSUE THREAD

**Issue by markuskowa** [NixOS/nixpkgs#59930] opened 2019-04-20 19:17 UTC
## Issue description
I am trying to start the guake terminal under a gnome3 desktop and get 
```
[ERROR] Unable to start Guake, missing mandatory dependency: Keybinder 3
```
Looking at its derivation `keybinder3` is part of the `buildInputs` and should be there. Any ideas what's going wrong here? 

### Steps to reproduce
```
nix-env -i guake
guake
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.35, NixOS, 19.03.172286.8ea36d73256 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172286.8ea36d73256"`
 - channels(markus): `"nixpkgs-19.03.172286.8ea36d73256"`

**Comment by jtojnar** [comment] 2019-04-21 16:02
Possibly a duplicate of https://github.com/NixOS/nixpkgs/issues/57494

**Comment by markuskowa** [comment] 2019-04-21 16:15
@jtojnar Thanks! Setting `strictDeps=false` fixes the problem.

**Closed** 2019-04-22 03:26 UTC
