### ISSUE TITLE
KDE shutting down when idle

### ISSUE THREAD

**Issue by yokto** [NixOS/nixpkgs#13808] opened 2016-03-10 10:21 UTC
## Basic info

unstable branch
loginmanager: sddm
## Describe your issue here

KDE just randomly shuts down when i'm afk. As far as I can see there are no errors anywhere it just shutsdown.

[xsession-errors.txt](https://github.com/NixOS/nixpkgs/files/166920/xsession-errors.txt)

**Comment by ttuegel** [comment] 2016-03-10 11:15
When you say it shuts down, do you mean the desktop manager logs your user out, or it actually powers the computer down?

**Comment by yokto** [comment] 2016-03-10 15:38
It logs the user out

**Comment by yokto** [comment] 2016-03-10 15:59
I think it's the Screen Energy Saving option. Just now, I turned it to one minute and after it comes back plasma isn't there anymore (only the windows are left).

**Comment by vcunat** [comment] 2016-03-10 17:27
Huh, this part of log is really fishy:
```
kscreen.kded: Config saved on:  "/home/silvio/.local/share/kscreen/8face9386bd27118161153bc9198ce7d"
+ test 253 -eq 255
++ /nix/store/iq7nddbqqgv80h06zsrscj0pqnscam59-kconfig-5.19.0/bin/kreadconfig5 --file startkderc --group WaitForDrKonqi --key Enabled --default true
+ wait_drkonqi=true
+ test xtruex = xtruex
++ /nix/store/iq7nddbqqgv80h06zsrscj0pqnscam59-kconfig-5.19.0/bin/kreadconfig5 --file startkderc --group WaitForDrKonqi --key Timeout --default 900
+ wait_drkonqi_timeout=900
+ wait_drkonqi_counter=0
+ /nix/store/ckhjsf456gdlnbqrsnhcp6i2f5x72psv-qttools-5.5.1/bin/qdbus
+ /nix/store/y50jbamh4iw1nhgyi3xdxg14fd8hslpg-gnugrep-2.22/bin/grep '^[^w]*org.kde.drkonqi'
kscreen.kded: Change detected
+ echo 'startkde: Shutting down...'
startkde: Shutting down...
+ test -n 1109
+ kill 1109
+ /nix/store/h737hpza82cxrkwv1cdl384dm551q6ix-kinit-5.19.0/bin/kdeinit5_shutdown
klauncher: Exiting on signal 1
klauncher: Exiting on signal 11
KCrash: Application 'kdeinit5' crashing...
KCrash: Attempting to start /run/current-system/sw/lib/libexec/drkonqi from kdeinit
Warning: connect() failed: : No such file or directory
KCrash: Attempting to start /run/current-system/sw/lib/libexec/drkonqi directly
```

... but I certainly don't see the cause. I can't even decide if it just crashed or it tried to shut down and crashed during that.

**Comment by ttuegel** [comment] 2016-12-21 16:42
I am closing this issue as unreproducible.

**Closed by ttuegel** 2016-12-21 16:42 UTC
Labels: 0.kind: bug, 6.topic: qt/kde
