### ISSUE TITLE
Package request: Thorium 

### ISSUE THREAD

**Issue by Gamoid786** [NixOS/nixpkgs#264825] opened 2023-11-01 14:19 UTC
**Project description**
Chromium fork for Linux, Windows, MacOS, Android, and Raspberry

The fastest browser on Earth.

Highlights:
Flying Thorium
Compiler optimizations include SSE4.2, AVX, AES, and modifications to CFLAGS, LDFLAGS, thinLTO flags, import_instr_limit flags, and PGO, as well as other compiler flags.
LLVM LOOP optimizations as -mllvm flags
Learn more about these compiler optimizations and how they work [Here](https://thorium.rocks/optimizations).
UI Changes and Patches for Linux and Windows that fix bugs, enhance useability, and strengthen privacy/security.

This nets a [8-38% performance](https://thorium.rocks/performance) improvement over vanilla Chromium, depending on the benchmark and OS. See [PATCHES.md](https://github.com/Alex313031/Thorium/blob/main/infra/PATCHES.md) for a detailed overview of all modifications compared to vanilla Chromium regarding performance, security and useability.

**Metadata**

* homepage URL: https://thorium.rocks/
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by iynaix** [comment] 2023-11-01 14:49
There's already an open pr for it: #261718

**Comment by eclairevoyant** [comment] 2023-11-01 15:19
dupe of #184823

**Closed by eclairevoyant** 2023-11-01 15:19 UTC
Labels: 2.status: duplicate, 0.kind: packaging request
