### ISSUE TITLE
buildRustCrate fails to build rustversion 1.0.2

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#78412] opened 2020-01-24 13:20 UTC
**Describe the bug**

`buildRustCrate` will clobber the source directory of the rustversion crate and it will subsequently fail to build with an error like this:

```
builder for '/nix/store/qzmcgmdyl3vhsj3y5gzfc1miqjxmddxn-rust_rustversion-1.0.2.drv' failed with exit code 1; last 10 log lines:
  Building src/lib.rs (rustversion)
  Running rustc --crate-name rustversion src/lib.rs --out-dir target/lib --emit=dep-info,link -L dependency=target/deps --cap-lints allow -C opt-level=3 -C codegen-units=16 --extern proc_macro2=/nix/store/p0aydc61mn5r4nw4l3c3zmpz1cv4dh4d-rust_proc-macro2-1.0.8-lib/lib/libproc_macro2-436ab8affb.rlib --extern quote=/nix/store/18vbqj8sj4dpnrr7dm19l2vaiail59y6-rust_quote-1.0.2-lib/lib/libquote-3ffc3269a3.rlib --extern syn=/nix/store/2mplqk67f8kfjnl1c2qnmy4md9sz2lf3-rust_syn-1.0.14-lib/lib/libsyn-121d03fbaa.rlib --cfg feature="default" --edition 2018 -C metadata=9fc8a6261b -C extra-filename=-9fc8a6261b --crate-type proc-macro -L /build/rustversion-1.0.2/target/build/rustversion.out --color always
  error: expected one of `!` or `::`, found `{`
   --> src/version.rs:1:9
    |
  1 | Version {
    |         ^ expected one of `!` or `::`

  error: aborting due to previous error
```

The reason this happens is because:

1. rustversion's build script [generates `$OUT_DIR/version.rs`](https://github.com/dtolnay/rustversion/blob/b1f7dcc0374cea28af247a9828940f7303b1efa1/build/build.rs#L45);
2. buildRustCrate [copies it over the original `src/version.rs`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/rust/build-rust-crate/configure-crate.nix#L142-L149).

**To Reproduce**
1. `crate2nix` a crate dependent on rustversion (or maybe rustversion itself?)
2. `nix build`

**Expected behavior**

The original source file should not be replaced. I don’t believe this copying code should exist at all.

cc @andir

**Comment by kolloch** [comment] 2020-01-26 14:09
This might be a duplicate of https://github.com/NixOS/nixpkgs/issues/74071

**Closed** 2020-01-30 11:26 UTC
Labels: 0.kind: bug, 6.topic: rust
