### ISSUE TITLE
VirtualBox GUI crashes

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#25890] opened 2017-05-18 11:53 UTC
## Issue description

Virtual Box GUI crashes when trying to use it

### Steps to reproduce

1. Start VirtualBox GUI.
2. Select (for example) "Machine > Add"
3. VirtualBox GUI is crashed

When starting the GUI from a Terminal, I get this output:

```

** (VirtualBox:20864): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Qt WARNING: libpng warning: iCCP: known incorrect sRGB profile

(VirtualBox:20864): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
Trace/breakpoint trap

```

## Technical details

* System: 17.09pre107265.0afb6d789c (Hummingbird)
* Nix version: nix-env (Nix) 1.11.9
* Nixpkgs version: "17.09pre107265.0afb6d789c"
* Sandboxing enabled: build-use-sandbox = true

**Comment by IreneKnapp** [comment] 2017-06-25 04:36
I am also experiencing this.

**Comment by matthiasbeyer** [comment] 2017-06-25 09:35
It was solved on my side with my latest update, but I'll leave it open for you!

**Comment by IreneKnapp** [comment] 2017-07-06 20:32
I believe my experience was caused by #24512. I worked around it, as described there. So I'm closing this bug.

**Comment by IreneKnapp** [comment] 2017-07-06 20:33
Okay, I guess I don't have permissions to close it. :) But at any rate, anyone seeing this should feel free to.

**Closed** 2017-07-06 20:56 UTC
