### ISSUE TITLE
Package request: bizhawk

### ISSUE THREAD

**Issue by Orisphera** [NixOS/nixpkgs#335884] opened 2024-08-19 19:02 UTC
**Project description**

BizHawk is a multi-platform emulator with full rerecording support and [Lua scripting](https://tasvideos.org/Bizhawk/LuaFunctions). BizHawk focuses on core accuracy and power user tools while still being an easy-to-use emulator for casual gaming.

**Metadata**

* homepage URL: https://tasvideos.org/BizHawk
* source URL: https://github.com/TASEmulators/BizHawk
* license: mit
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Charging1948** [comment] 2024-08-20 08:56
Duplicate of: https://github.com/NixOS/nixpkgs/issues/301131

**Closed** 2024-08-20 15:08 UTC
Labels: 0.kind: packaging request

**Comment by YoshiRulz** [comment] 2024-09-12 00:36
We have an expression checked-in to our repo. See https://github.com/TASEmulators/BizHawk#nixnixos to get started.
