### ISSUE TITLE
Plasma Night Color is broken

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#118579] opened 2021-04-05 10:25 UTC
**Describe the bug**
Plasma's Night Color feature is broken in X11 (and maybe Wayland, too) because the module cannot communicate with the window manager.

**To Reproduce**
1. Open `System Settings`.
2. Navigate to `Display and Monitor > Night Color`.
3. Observe.

**Expected behavior**
The Night Color module connects to the window manager.

**Screenshots**
![Screenshot_20210405_052326](https://user-images.githubusercontent.com/563054/113564620-4bf44280-95cf-11eb-8828-d3398ce24648.png)

**Notify maintainers**
@NixOS/qt-kde 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.108, NixOS, 21.05.git.0afce22758a (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - nixpkgs: `/etc/nixos/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by peterhoeg** [comment] 2021-04-05 13:19
I'm thinking this might be related to https://github.com/NixOS/nixpkgs/pull/116549

**Comment by samueldr** [comment] 2021-04-05 19:09
Might be an adjacent issue. I haven't tried on Plasma, or X11, but with plasma mobile (on wayland) it doesn't work.

I haven't taken the time to look into it, bigger issues are siphoning my time :).

**Comment by ttuegel** [comment] 2021-04-05 19:44
Of course! This is not a blocking issue. I'm documenting what I find so that we know later if there is a regression. :smiley:

**Comment by samueldr** [comment] 2021-04-05 20:26
No worries, it's great to see it's (maybe) not a Plasma Mobile specific issue!

Could you specify whether this was on X11 or wayland in the initial report?

**Comment by solson** [comment] 2021-04-10 13:40
Duplicate of #117036

**Comment by peterhoeg** [comment] 2021-05-03 09:29
Closing as it's a dupe.

**Closed by peterhoeg** 2021-05-03 09:29 UTC
Labels: 0.kind: bug, 6.topic: qt/kde
