### ISSUE TITLE
libcec fails to communicate via HDMI-CEC on Raspberry Pi 3B

### ISSUE THREAD

**Issue by lloeki** [NixOS/nixpkgs#88299] opened 2020-05-20 09:43 UTC
**Describe the bug**

`libcec` fails to communicate with HDMI on Raspberry Pi 3B.

Build information reports no `RPi` support:

```
# cec-client -i
libCEC version: 4.0.4,  compiled on Sun May 10 17:39:07 UTC 2020 by nixbld on Linux 4.19.116 (aarch64), features: P8_USB, DRM, P8_detect
```

An example of a libcec build having `RPi` in its feature list:

```
libCEC version: 4.0.3, git revision: libcec-4.0.3, compiled on Tue Nov  5 21:42:57 UTC 2019 by root@c6a286913f8d on Linux 4.14.98-v7 (armv7l), features: P8_USB, DRM, P8_detect, RPi
```

From what I gather from the links below, it appears sufficient to build `libcec` against `libraspberrypi` with `cmake`'s `-DRPI_INCLUDE_DIR=` and `-DRPI_LIB_DIR=`.

**To Reproduce**
1. boot Pi 3B on nixos
2. nix-env -iA nixos.libcec
3. echo 'scan' | cec-client -s -d 1

**Expected behavior**

Should list HDMI-CEC compatible devices. Example:

```
# echo 'scan' | cec-client -s -d 1
opening a connection to the CEC adapter...
requesting CEC bus information ...
CEC bus information
===================
device #0: TV
address:       0.0.0.0
active source: no
vendor:        Samsung
osd string:    TV
CEC version:   1.4
power status:  on
language:      eng

device #1: Recorder 1
address:       1.0.0.0
active source: no
vendor:        Pulse Eight
osd string:    CECTester
CEC version:   1.4
power status:  on
language:      eng

currently active source: unknown (-1)
```

**Screenshots**

```
# echo 'scan' | cec-client -s -d 1
autodetect FAILED
```

**Additional context**

- `cec-client` usage: https://www.linuxuprising.com/2019/07/raspberry-pi-power-on-off-tv-connected.html
- Similar issue at Home Assistant, tracing to the cause: https://github.com/home-assistant/hassio-addons/issues/815
- Reference to the change that enables Raspberry Pi support in `libcec` fo Home Assistant: https://github.com/home-assistant/hassio-addons/commit/7e6adcab3280f458172d6d6a5653276c16f80107

**Notify maintainers**

@tkerber 

**Metadata**

```
# nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/xb1mym4yd3azdv5gz48r969qhyqxlqrr-bash-interactive-4.4-p23-dev
copying path '/nix/store/xb1mym4yd3azdv5gz48r969qhyqxlqrr-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"aarch64-linux"`
 - host os: `Linux 5.6.13, NixOS, 20.03.1879.91cdcf31357 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1879.91cdcf31357"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixos.libcec
# a list of nixos modules affected by the problem
module:
```

**Comment by aanderse** [comment] 2020-05-20 10:26
@lloeki are you able to fix, test, and file a PR?

**Comment by tkerber** [comment] 2020-05-20 10:34
Did you enable raspberry pi support for libcec? This is a compile time option which it did not make sense to enable by default. You should be able to use it with the following overlay:

```nix
self: super: {
  libcec = super.libcec.override { inherit (self) libraspberrypi; };
}
```

**Comment by lloeki** [comment] 2020-05-22 12:44
@aanderse I'm still a nix beginner so it would take a bit of time! Nonetheless I wanted to hear the opinion of @tkerber, noted as maintainer.

@tkerber not yet, that was my plan as soon as I had some time (although I'd have gone through the trouble of a custom build through a nix file since I'm still trying to wrap my head around the nix features such as overlays)

**Comment by tkerber** [comment] 2020-05-22 12:54
That's understandable. If you want to try it out from the shell, try the following on your RPi

```
$ nix-shell -p 'libcec.override { inherit libraspberrypi; }'
```

I'm not completely confident, but I suspect that you could make this work with `nix-env` too -- I do not use this tool myself.

As this is the intended usage, I'm going to close this issue -- there are a number of packages with this kind of override-enabled flag, and they could probably be signposted better, but that's a different discussion.

**Closed by tkerber** 2020-05-22 12:54 UTC
Labels: 0.kind: bug

**Comment by madorian** [comment] 2024-04-13 12:44
I'm still seeing this on Pi 4. 

I have this override. 

```
  nixpkgs.overlays = [
    (self: super: {
      libcec = super.libcec.override { inherit (self) libraspberrypi; };
    }
    )
  ];

```

, but I'm still getting: 

```
$ echo 'scan' | cec-client -s -d 1
autodetect FAILED
```

**Comment by aanderse** [comment] 2024-04-13 12:51
this has changed, as seen [here](https://github.com/NixOS/nixpkgs/blob/1042fd8b148a9105f3c0aca3a6177fd1d9360ba5/pkgs/development/libraries/libcec/default.nix#L8C3-L8C21)

now you should use `libcec.override { withLibraspberrypi = true; }`

please ping back so we know if the issue is resolved or not

**Comment by madorian** [comment] 2024-04-13 21:19
Great, thanks; now it compiles with this: 
```
  nixpkgs.overlays = [
    (self: super: {
      libcec = super.libcec.override { withLibraspberrypi = true; };
    }
    )
  ];

```

, but it doesn't really work;) It's super slow to output anything in the terminal and I get Segmentation Fault. 

It's [this](https://github.com/Pulse-Eight/libcec/issues/476) issue, it seems. I have the HDMI port closest to the power plug, so it's not that that's causing it.

**Comment by aanderse** [comment] 2024-04-14 17:36
i would recommend we figure out your kernel issue first as who knows what other issues that could potentially be causing

please create a topic on discourse or go on matrix chat, etc... and we can figure that out then proceed troubleshooting here if needed

feel free to cc me in in case something potentially relevant comes up

**Comment by madorian** [comment] 2024-04-19 19:38
I've discovered that it fails to boot any newer image. I made a thread [here](https://discourse.nixos.org/t/whats-the-latest-kernel-on-pi/43354).

**Comment by madorian** [comment] 2024-04-22 13:17
Seems it's broken, but what kernel version are you using?

**Comment by madorian** [comment] 2024-04-24 19:46
ok, I've now managed to update, but I still get this

```
[root@pi:~]# echo 'scan' | cec-client -s -d 1
opening a connection to the CEC adapter...
requesting CEC bus information ...
CEC bus information
===================
device #0: TV
address:       0.0.0.0
active source: no
vendor:        Unknown
osd string:    TV
CEC version:   unknown
power status:  unknown
language:      ???


device #1: Recorder 1
address:       1.0.0.0
active source: no
vendor:        Pulse Eight
osd string:    CECTester
CEC version:   1.4
power status:  on
language:      eng


currently active source: unknown (-1)
Segmentation fault (core dumped)

[
```

```
[root@pi:~]# uname -a
Linux pi 6.8.7 #1-NixOS SMP Wed Apr 17 09:23:43 UTC 2024 aarch64 GNU/Linux
```
