### ISSUE TITLE
`cargo-watch` build failure on aarch64-darwin

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#146349] opened 2021-11-17 06:29 UTC
### Describe the bug
The `cargo-watch` package fails to build on aarch64-darwin. This appears to be related to a failure running the build script for the crate [mac-notification-sys](https://github.com/h4llow3En/mac-notification-sys).

### Steps To Reproduce
1. Try building `cargo-watch` on aarch64-darwin.
2. Observe failure.

### Expected behavior
The package to build.

### Screenshots
n/a

### Additional context
See https://gist.github.com/samuela/64da4e242830cd92054121030828a691 for the complete build log.

### Notify maintainers

@xrelkd @ivan

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.1.0, macOS 12.0.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4`
 - channels(samuelainsworth): `"darwin, home-manager, nixpkgs-21.11pre330734.5cb226a06c4"`
 - channels(root): `"nixpkgs-21.11pre330734.5cb226a06c4"`
 - nixpkgs: `/Users/samuelainsworth/.nix-defexpr/channels/nixpkgs`
 ```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: cargo-watch
# a list of nixos modules affected by the problem
module:
```

**Comment by samuela** [comment] 2021-11-17 06:36
Installing via `cargo install cargo-watch` does work OTOH.

**Comment by Artturin** [comment] 2021-11-17 07:06
CoreFoundation and Foundation need to be added to the buildInputs

**Comment by samuela** [comment] 2021-11-17 07:25
https://github.com/NixOS/nixpkgs/blob/b45b1d643907e5a323d712cddab49f1988b0f97f/pkgs/development/tools/rust/cargo-watch/default.nix#L16
`Foundation` is already in `buildInputs`. I just tried adding `CoreFoundation` as well but that didn't seem to make any difference.

**Comment by rpearce** [comment] 2022-01-16 04:04
Ran into this, too, but `cargo install cargo-watch` doesn't seem to work
```
warning: In file included from objc/notify.m:1:
warning: objc/notify.h:1:9: fatal error: 'Foundation/Foundation.h' file not found
warning: #import <Foundation/Foundation.h>
warning:         ^~~~~~~~~~~~~~~~~~~~~~~~~
warning: 1 error generated.

error: failed to run custom build command for `mac-notification-sys v0.3.0`
```

**Comment by nigelgbanks** [comment] 2022-01-22 20:50
`cargo install cargo-watch` works for me.

```bash
cargo --version 
cargo 1.58.0 (7f08ace4f 2021-11-24)

uname -a
Darwin macbook 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.2.0, macOS 12.1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixpkgs-22.05pre346778.1caf78f4bf5"`
 - nixpkgs: `/etc/nixpkgs`
# I use flakes so the channels(root) here can be ignored I'm on nixpkgs-21.11-darwin 2c9afd35b57f22dc69803972df147b7a331ee596
```

Building via nix however, fails. 

```
error: failed to run custom build command for `mac-notification-sys v0.3.0`

Caused by:
  process didn't exit successfully: `/private/tmp/nix-build-cargo-watch-8.1.1.drv-0/source/target/release/build/mac-notification-sys-35a1d46b2ce92018/build-scri
  --- stdout
  TARGET = Some("aarch64-apple-darwin")
  OPT_LEVEL = Some("3")
  HOST = Some("aarch64-apple-darwin")
  CC_aarch64-apple-darwin = Some("/nix/store/7sfdssd4p5c6gh5dr2j1fy06fxky195q-clang-wrapper-11.1.0/bin/cc")
  CFLAGS_aarch64-apple-darwin = None
  CFLAGS_aarch64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = None
  running: "/nix/store/7sfdssd4p5c6gh5dr2j1fy06fxky195q-clang-wrapper-11.1.0/bin/cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-fmo
  cargo:warning=error: unable to open output file '/homeless-shelter/.cache/clang/ModuleCache/34TQMRHFQU7QU/Foundation-20C0ANTXDRONG.pcm': 'No such file or dire
  cargo:warning=In file included from objc/notify.m:1:
  cargo:warning=objc/notify.h:1:9: fatal error: could not build module 'Foundation'
  cargo:warning=#import <Foundation/Foundation.h>
  cargo:warning= ~~~~~~~^
  cargo:warning=error: unable to open output file '/homeless-shelter/.cache/clang/ModuleCache/34TQMRHFQU7QU/ObjectiveC-3KPV63CE69HU8.pcm': 'No such file or dire
  cargo:warning=error: unable to open output file '/homeless-shelter/.cache/clang/ModuleCache/34TQMRHFQU7QU/CoreServices-2ZSMMJ1VHU9R1.pcm': 'No such file or di
  cargo:warning=4 errors generated.
  exit status: 1

  --- stderr


  error occurred: Command "/nix/store/7sfdssd4p5c6gh5dr2j1fy06fxky195q-clang-wrapper-11.1.0/bin/cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch


warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by kgtkr** [comment] 2022-03-09 11:38
Currently `cargo install cargo-watch` succeeds

**Comment by rpearce** [comment] 2022-03-13 19:23
In lieu of not being able to use `cargo-watch` on an M1 through nix, I've now got all this running through Docker and the `nixos/nix` image, but it ain't pretty yet and isn't ready for sharing. I might even go so far as to just put my whole dev environment in this eventually.

**Comment by Artturin** [comment] 2022-03-13 19:25
@NixOS/darwin-maintainers

**Comment by uri-canva** [comment] 2022-03-14 00:43
Same underlying issue: https://github.com/NixOS/nixpkgs/issues/160876.

**Comment by uri-canva** [comment] 2022-03-14 00:44
Issue opened for a possible root cause: https://github.com/NixOS/nixpkgs/issues/163052

**Comment by schickling** [comment] 2022-08-27 16:51
Is there any progress on this issue or any known workarounds?

**Comment by toonn** [comment] 2022-09-05 09:31
@schickling, @tjni is still chipping away at #163052, latest findings in  #185569.

**Comment by tjni** [comment] 2022-10-12 00:19
Fix for this is now in `master`, so I'm going to close this issue. It should be on `nixpkgs-unstable` soon if not already.

**Closed by tjni** 2022-10-12 00:19 UTC
Labels: 6.topic: darwin, 6.topic: rust, 0.kind: build failure

**Comment by schickling** [comment] 2022-10-12 10:25
🎉
