### ISSUE TITLE
Xpra failing to start on 16.03

### ISSUE THREAD

**Issue by kototama** [NixOS/nixpkgs#14540] opened 2016-04-08 19:31 UTC
Xpra fails to start on NixOS 16.03.526.567b65d. I also tried to install the `rencode` Python module as a fix ; without success.

```
[root@nixos:~]# xpra start :222
2016-04-08 21:27:49,615 rencode import error: No module named rencode

Warning: running as root

[root@nixos:~]# Entering daemon mode; any further errors will be reported to:
  /root/.xpra/:222.log


[root@nixos:~]# nix-env -iA nixos.python27Packages.rencode
replacing old ‘python2.7-rencode-git20150810’
installing ‘python2.7-rencode-git20150810’

[root@nixos:~]# xpra start :222
2016-04-08 21:28:00,934 rencode import error: No module named rencode

Warning: running as root

[root@nixos:~]# Entering daemon mode; any further errors will be reported to:
  /root/.xpra/:222.log
^C

[root@nixos:~]# cat /root/.xpra/:222.log

X.Org X Server 1.17.4
Release Date: 2015-10-28
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.14.54 i686 
Current Operating System: Linux nixos 4.4.6 #1-NixOS SMP Wed Mar 16 15:43:17 UTC 2016 i686
Kernel command line: BOOT_IMAGE=(hd0,msdos1)/nix/store/kszxdc6wxbzbc3mhvpzrjlina9ynriwq-linux-4.4.6/bzImage systemConfig=/nix/store/x99zi6ncq50qc3hjhgg8ydmjysxahjvs-nixos-system-nixos-16.03.498.f8a5d1e init=/nix/store/x99zi6ncq50qc3hjhgg8ydmjysxahjvs-nixos-system-nixos-16.03.498.f8a5d1e/init loglevel=4
Build Date: 30 March 2016  09:59:32AM

Current version of pixman: 0.34.0
    Before reporting problems, check http://wiki.x.org
    to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
    (++) from command line, (!!) notice, (II) informational,
    (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/root/.xpra/Xorg.:222.log", Time: Fri Apr  8 21:28:00 2016
(==) Using system config directory "/nix/store/s4r2s1rgqxqgcwrh1b6c0pq73skjdcr4-xorg-server-1.17.4/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
     at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/root/.xpra/Xorg.:222.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.

```

**Comment by abbradar** [comment] 2016-04-09 00:02
I've tried to add `rencode` to [this line](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/X11/xpra/default.nix#L32). When I tried to run command that you tested then it crashed my X session. I'm not sure how xpra is supposed to work, so I don't know if this fixed it or more is needed.

**Comment by kototama** [comment] 2016-04-09 19:54
It should not crash your X session. `xpra start :222` should starts in the background, you could then do something like that to launch a program on the xpra display:

```
xpra attach :222
DISPLAY=:222 xterm
```

**Comment by kototama** [comment] 2016-04-09 19:57
You should also be able to do that as non-root user.

**Comment by abbradar** [comment] 2016-04-10 14:55
I've managed to at least fix installation of xpra's `xorg.conf` and fix several paths to point where actually needed. At this point it needs to be pointed at several Xorg modules (`dummy`, `mouse` and `kbd`), so probably its `xorg.conf` needs to be patched. I don't have more time to look at this further now -- someone who actually uses xpra should look at it. My WIP branch is https://github.com/abbradar/nixpkgs/tree/xpra

**Comment by FRidh** [comment] 2016-04-11 08:31
@kototama 

> I also tried to install the rencode Python module as a fix ; without success.

That would not work in Nix. Even though you would have `rencode` in your profile, the module is not on your `PYTHONPATH` or in any relevant `pth` file. If `rencode` is needed, it should be made a dependency of `xpra`.

@abbradar added this package to PYTHONPATH in his branch.

**Comment by Jookia** [comment] 2016-09-23 20:11
Xpra now crashes X. Hmm.

**Comment by dmayle** [comment] 2016-11-30 05:04
It looks like this was fixed by: https://github.com/NixOS/nixpkgs/commit/34363d77b0cbb9bc8046691b12d21fa4463f8233

**Comment by vcunat** [comment] 2016-11-30 17:42
It seems so. Reopen/comment if you can still reproduce it.

**Comment by leo60228** [comment] 2020-01-27 13:07
This seems to have regressed, I now have an identical issue on 19.09.

**Comment by mjlbach** [comment] 2020-03-01 08:07
Also having this issue:
```
[mjlbach@nixos:~/Repositories/GibsonEnvV2]$ cat /run/user/1000/xpra/:3.log
2020-03-01 00:03:59,762 cannot use uinput for virtual devices:
2020-03-01 00:03:59,763  [Errno 19] Failed to open the uinput device: No such device

X.Org X Server 1.20.7
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.19.92 x86_64
Current Operating System: Linux nixos 4.19.106 #1-NixOS SMP Mon Feb 24 07:34:54 UTC 2020 x86_64
Kernel command line: BOOT_IMAGE=(hd2,gpt5)//kernels/454ar0mw1pjylarz448siildaxib5ml9-linux-4.19.106-bzImage systemConfig=/nix/store/czm2lckhikgw06mpikxn6vd6rcp129y5-nixos-system-nixos-19.09.2163.d0b3ab3b249 init=/nix/store/czm2lckhikgw06mpikxn6vd6rcp129y5-nixos-system-nixos-19.09.2163.d0b3ab3b249/init loglevel=4
Build Date: 13 January 2020  10:57:44PM

Current version of pixman: 0.38.4
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/run/user/1000/xpra/Xorg.:3.log", Time: Sun Mar  1 00:03:59 2020
(++) Using config file: "/nix/store/kk0jcmq3r5j50ihvz0cj9zlx3k67y9hw-xpra-3.0.6/etc/xpra/xorg.conf"
(==) Using system config directory "/nix/store/wa73k9mvspylka2c224waq626z4x4ss4-xorg-server-1.20.7/share/X11/xorg.conf.d"
(EE)
Fatal server error:
(EE) no screens found(EE)
(EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
(EE) Please also check the log file at "/run/user/1000/xpra/Xorg.:3.log" for additional information.
(EE)
(EE) Server terminated with error (1). Closing log file.
2020-03-01 00:04:02,789 Error: failed to connect to display :3
2020-03-01 00:04:02,789  could not connect to X server on display ':3' after 3 seconds

[mjlbach@nixos:~/Repositories/GibsonEnvV2]$
```

**Comment by leo60228** [comment] 2020-03-03 13:12
Passing `--xvfb=Xvfb` works as a workaround. This shouldn't be the default, as Xdummy is faster.

**Comment by leo60228** [comment] 2020-03-03 13:12
Wait... is it possible that Xpra is picking up my system Xorg.conf?

**Comment by samueldr** [comment] 2020-06-08 19:37
Closing, as with #87985, it is assumed this issue should be fixed.

If *this particular issue* is not fixed, feel free to reopen, or ask to reopen. For another problem, open a new issue, and CC the relevant people working on better Xpra support (see #86164).

Thanks!

**Closed by samueldr** 2020-06-08 19:37 UTC
Labels: 0.kind: bug
