### ISSUE TITLE
regression: thunderbird + enigmail not able to interact with gpg agent due to non-gui pinentry

### ISSUE THREAD

**Issue by andrewrk** [NixOS/nixpkgs#72765] opened 2019-11-04 07:03 UTC
**Describe the bug**
Attempting to use thunderbird + enigmail to send an email gives this error message:

> Your GnuPG installation is configured to use the console for pinentry. However, when using Enigmail you need a graphical version of pinentry.

> This is a system setup or configuration error that prevents Enigmail from working properly and cannot be fixed automatically.

> We strongly recommend that you consult our support web site at https://enigmail.net/faq.

**To Reproduce**

1. 
```nix
  programs.gnupg.agent = {
    enable = true;
    enableSSHSupport = true;
  };
```
2. install thunderbird and enigmail
3. set up a gpg key in your .gnupg/ directory
3. send an email with a signature

**Expected behavior**
gui based pinentry pops up, type in gpg key password, email is sent

**Screenshots**
![Screenshot_2019-11-04_02-00-48](https://user-images.githubusercontent.com/106511/68103956-f8943700-fea6-11e9-8eb7-6b93683f904a.png)

**Additional context**
Related: https://github.com/NixOS/nixpkgs/issues/72597#issuecomment-549217306

This is a regression from the previous unstable revision that I was running. I will be happy to provide that version info if someone tells me the command to run on my system to list the previous derivations.

As an additional clue, when I use signed git commits, the gui window pinentry no longer shows up; instead it is a terminal-based one.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.8, NixOS, 20.03pre199897.471869c9185 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre199897.471869c9185"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by jtojnar** [comment] 2019-11-04 09:36
If you enable gnupg agent, you should have pinentry based on your desktop environment:

https://github.com/NixOS/nixpkgs/blob/cdc5bcdea543406814bbf12f3efefa8358065cc7/nixos/modules/programs/gnupg.nix#L11-L20

If you are getting curses, that must be caused by `pinentry-gnome` pointing to a wrong output, I do not think we use it anywhere else. It should be fixed by https://github.com/NixOS/nixpkgs/commit/1c74b29b05a55f1a66afb595fd5796cb52879aa3. 

I would say if you were getting curses, the pinentry was being set correctly, so maybe you need to run `systemctl --user daemon-reload` or `systemctl --user restart gnupg-agent`.

**Comment by andrewrk** [comment] 2019-11-04 17:35
Desktop manager is 

```
  services.xserver = {
    desktopManager.xfce4-14.enable = true;
  };
```

I tried adding 

```
  programs.gnupg.agent.pinentryFlavor = "gtk2";
```

and running `systemctl --user daemon-reload`. That didn't make the changes take effect. But then I did `gpgconf --kill gpg-agent` and it worked. Thanks for the tips.

It looks like that code `nixpkgs/nixos/modules/programs/gnupg.nix` needs to be updated to take into account xfce-4-14.

**Comment by jtojnar** [comment] 2019-11-04 17:47
> It looks like that code `nixpkgs/nixos/modules/programs/gnupg.nix` needs to be updated to take into account xfce-4-14.

It should be handled by the `xserverCfg.enable` condition.

Forgot about also needing https://github.com/NixOS/nixpkgs/commit/7240566f74ffe0112e439dc971d655634d47a2dd for `gnome3` frontend.

**Comment by andrewrk** [comment] 2019-11-04 18:47
> It should be handled by the `xserverCfg.enable` condition.

I think you are not seeing the difference. The logic is checking for `xfce` but in upgraded configs, the value is `xfce4-14`.

So on my system that logic would select "gnome3" which is incorrect. I had to override it to select "gtk2" to make it work, because the logic is looking for `xfce` rather than `xfce4-14`.

**Comment by andrewrk** [comment] 2019-11-04 18:48
To further clarify, I think this would fix it:

```
 defaultPinentryFlavor = 
   if xserverCfg.desktopManager.lxqt.enable 
   || xserverCfg.desktopManager.plasma5.enable then 
     "qt" 
   else if xserverCfg.desktopManager.xfce.enable
   || xserverCfg.desktopManager.xfce4-14.enable then 
     "gtk2" 
   else if xserverCfg.enable || config.programs.sway.enable then 
     "gnome3" 
   else 
     null; 
```

**Comment by jtojnar** [comment] 2019-11-04 19:03
> I think you are not seeing the difference. The logic is checking for `xfce` but in upgraded configs, the value is `xfce4-14`.

Xfce 4.14 uses GTK 3 so we do not want GTK 2.

**Comment by andrewrk** [comment] 2019-11-04 19:04
> Xfce 4.14 uses GTK 3 so we do not want GTK 2.

oh, I see, so I can remove my workaround, and apply https://github.com/NixOS/nixpkgs/commit/7240566f74ffe0112e439dc971d655634d47a2dd ? let me try that.

**Comment by worldofpeace** [comment] 2019-11-04 19:08
I believe I raised this in the original PR that an extra condition for XFCE 4.14 wasn't needed because they're removing gtk2 support anyways.

**Comment by ashkitten** [comment] 2019-11-23 04:07
should people that use other window managers (i3, for instance) need to specify their pinentry flavor, then?

**Comment by multun** [comment] 2019-12-29 21:12
I have the same issue running i3 btw

**Comment by jtojnar** [comment] 2019-12-30 00:08
Please re-open if you still experience this.

**Closed** 2019-12-30 00:08 UTC
Labels: 0.kind: bug

**Comment by jtojnar** [comment] 2019-12-30 00:09
Please re-open if you still experience this.
