### ISSUE TITLE
NixOS: XMonad requires xterm disabled / not respecting `desktopManager.default = "none";`

### ISSUE THREAD

**Issue by aaronlevin** [NixOS/nixpkgs#4300] opened 2014-09-28 02:50 UTC
I'm not sure if this is desired behavior or an issue. After successfully getting NixOS installed and running on my laptop, I decided to copy my [`/etc/nixos/configuration.nix`](https://github.com/aaronlevin/dotfiles/blob/178fd09817925f475203532ffe7c856468275e9f/nix/configuration.nix) to my desktop. To my surprise the following happened:

1. At the login screen, instead of "**Session: none + xmonad**" at the bottom it just stated: "**Session: xterm**"
2. After logging in, it seemed like my display manager was just a single xterm (hard to describe, but I had a terminal in the top-left of my screen, and then default / generic background for the rest).
3. running `xmonad --recompile` gave me a `ghc`-related error
4. running `ls -ln \`which xmonad\`` gave me what looked like the desired result (xmonad was properly installed).

### Steps to Recreate Issue

1. install NixOS
2. use this configuration: [`/etc/nixos/configuration.nix`](https://github.com/aaronlevin/dotfiles/blob/178fd09817925f475203532ffe7c856468275e9f/nix/configuration.nix)
3. login as `aaronlevin`

### Steps to "Fix" / "Hack" Issue

To fix this, I had to add the following line to my `/etc/nixos/configuration.nix`:

      services.xserver.desktopManager.xterm.enable = false;

### Desired Behaviour

If I set `xmonad` as my window manager, I shouldn't have to disable `xterm` as a desktop manager. Further, setting `desktopManager.default = "none";` should work disable `xterm`.

### Other Notes

Note that this line was absent from my laptop configuration. I believe some kind of referential transparency was broken (perhaps on purpose), because when I first setup my laptop I included that line having seen it on a blog somewhere. I later removed it.

**Comment by peti** [comment] 2015-02-25 19:41
I understand that there's been some re-factoring in the xmonad module for NixOS recently. Does this issue still exist in the current version?

**Comment by NoxDeleo** [comment] 2015-04-18 07:42
I just started using NixOS yesterday, and I can confirm this bug is still present. I have `services.xserver.desktopManager.default = "none";` in my configuration as well.

**Comment by seagreen** [comment] 2015-05-01 15:39
I'm also having this issue. Strangely, I can work around it by intentionally failing my first login attempt. "Session: none + xmonad" then shows up correctly and things work from there.

**Comment by NoxDeleo** [comment] 2015-05-01 20:15
@seagreen Since my last post, I stumbled across the F1 key which seems to cycle the selected session in SLiM. A bit quicker than failing a login. That'd get old really fast.

**Comment by seagreen** [comment] 2015-05-01 23:37
@NoxDeleo: Thanks:)

**Comment by peti** [comment] 2015-05-07 09:22
Can we close this bug then?

**Comment by aaronlevin** [comment] 2015-05-07 12:24
@peti has it been solved? Or is the `F1` solution acceptable? I really found this bug puzzling and as it happens early on in a user's first experience of NixOS, it would be good to fix (I know bandwidth and volunteering is limited, so I say that with that in mind)

**Comment by peti** [comment] 2015-05-07 13:21
Well, if anyone knows how to configure the session type `slim` chooses by default, then please don't hesitate to submit a PR! It's just that this issue has been open for 6+ months without significant activity, and I don't see what we gain by keeping it open much longer without anyone doing anything about it.

**Comment by NoxDeleo** [comment] 2015-05-07 18:45
According to [this](https://wiki.gentoo.org/wiki/SLiM#Default_configuration_.28no_default_session.29), it can be done using the XSESSION environment variable. I'll give that a test next chance I get.

**Comment by peti** [comment] 2015-05-13 11:22
If anyone has a suggestion how to improve NixOS in that regard, please open a PR!

**Closed by peti** 2015-05-13 11:22 UTC
Labels: bug, nixos

**Comment by nonetrix** [comment] 2022-06-28 19:30
``` services.xserver.desktopManager.xterm.enable = false;``` doesn't work for me at all
