### ISSUE TITLE
BUG WEBBOT

### ISSUE THREAD

**Issue by dmaxdeman** [NixOS/nixpkgs#232141] opened 2023-05-16 02:32 UTC
### Describe the bug
It says
from webbot import browser 
ModuleNotFoundError: No module named 'webbot'
### Steps To Reproduce
Got to this replit and fork then run it
https://replit.com/@yodaluca23/Selenium-Browser?v=1

### Expected behavior
It should pop up with a UI similar to googles
### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/112894537/4ac427eb-351a-4d84-bece-e5ecb2113189)

### Additional context

![Screenshot 2023-05-15 22 31 40](https://github.com/NixOS/nixpkgs/assets/112894537/2bc73ebc-b212-4188-8e24-fdadd778c6c0)
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by figsoda** [comment] 2023-05-16 02:59
webbot doesn't seem to be packaged in nixpkgs: #159106

**Comment by FliegendeWurst** [comment] 2024-11-02 16:54
Duplicate of #159106

**Closed by FliegendeWurst** 2024-11-02 16:54 UTC
Labels: 0.kind: bug
