### ISSUE TITLE
AWS CLI v2: urllib3 Dependency Version Issue

### ISSUE THREAD

**Issue by dansheikh** [NixOS/nixpkgs#288382] opened 2024-02-12 20:38 UTC
### Describe the bug
AWS CLI v2 (2.13.33) package includes urllib3 version 2.0.7 which apparently is incompatible with the included botocore, see following error trace:

> Traceback (most recent call last):
>   File "/nix/store/iblfnc4k15nkyzn1idgffwha8msf0mbr-awscli2-2.13.33/bin/.aws-wrapped", line 20, in <module>
>     import awscli.clidriver
>   File "/nix/store/iblfnc4k15nkyzn1idgffwha8msf0mbr-awscli2-2.13.33/lib/python3.11/site-packages/awscli/clidriver.py", line 21, in <module>
>     import botocore.session
>   File "/nix/store/iblfnc4k15nkyzn1idgffwha8msf0mbr-awscli2-2.13.33/lib/python3.11/site-packages/awscli/botocore/session.py", line 27, in <module>
>     import botocore.client
>   File "/nix/store/iblfnc4k15nkyzn1idgffwha8msf0mbr-awscli2-2.13.33/lib/python3.11/site-packages/awscli/botocore/client.py", line 16, in <module>
>     from botocore import UNSIGNED, waiter, xform_name
>   File "/nix/store/iblfnc4k15nkyzn1idgffwha8msf0mbr-awscli2-2.13.33/lib/python3.11/site-packages/awscli/botocore/waiter.py", line 17, in <module>
>     from botocore.docs.docstring import WaiterDocstring
>   File "/nix/store/iblfnc4k15nkyzn1idgffwha8msf0mbr-awscli2-2.13.33/lib/python3.11/site-packages/awscli/botocore/docs/__init__.py", line 15, in <module>
>     from botocore.docs.service import ServiceDocumenter
>   File "/nix/store/iblfnc4k15nkyzn1idgffwha8msf0mbr-awscli2-2.13.33/lib/python3.11/site-packages/awscli/botocore/docs/service.py", line 14, in <module>
>     from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
>   File "/nix/store/iblfnc4k15nkyzn1idgffwha8msf0mbr-awscli2-2.13.33/lib/python3.11/site-packages/awscli/botocore/docs/client.py", line 16, in <module>
>     from botocore.docs.example import ResponseExampleDocumenter
>   File "/nix/store/iblfnc4k15nkyzn1idgffwha8msf0mbr-awscli2-2.13.33/lib/python3.11/site-packages/awscli/botocore/docs/example.py", line 13, in <module>
>     from botocore.docs.shape import ShapeDocumenter
>   File "/nix/store/iblfnc4k15nkyzn1idgffwha8msf0mbr-awscli2-2.13.33/lib/python3.11/site-packages/awscli/botocore/docs/shape.py", line 19, in <module>
>     from botocore.utils import is_json_value_header
>   File "/nix/store/iblfnc4k15nkyzn1idgffwha8msf0mbr-awscli2-2.13.33/lib/python3.11/site-packages/awscli/botocore/utils.py", line 33, in <module>
>     import botocore.httpsession
>   File "/nix/store/iblfnc4k15nkyzn1idgffwha8msf0mbr-awscli2-2.13.33/lib/python3.11/site-packages/awscli/botocore/httpsession.py", line 21, in <module>
>     from urllib3.util.ssl_ import (
> **ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/nix/store/0hqxlnv2k8vay7acydvd3mdnp0hwf205-python3.11-urllib3-2.0.7/lib/python3.11/site-packages/urllib3/util/ssl_.py)**

### Steps To Reproduce
1. [Install AWS CLI v2 package.](https://search.nixos.org/packages?channel=23.11&show=awscli2&from=0&size=50&sort=relevance&type=packages&query=awscli2)
2. Run `aws --version`

### Notify maintainers
@bhipple @davegallant @bryanasdev000 @devusb @anthonyroussel

**Comment by surfaceflinger** [comment] 2024-02-13 16:14
Hmm, works fine for me from master as of me writing this

**Comment by AndrewKvalheim** [comment] 2024-02-27 22:30
I just hit this due to #108516 and had success with this workaround:

```console
$ env --unset PYTHONPATH aws --version
aws-cli/2.13.33 Python/3.11.6 Linux/6.1.79 source/x86_64.nixos.23 prompt/off
```

**Comment by fstamour** [comment] 2024-03-21 17:39
Looks like a duplicate of #267864

**Comment by anthonyroussel** [comment] 2024-04-07 15:14
Duplicate of https://github.com/NixOS/nixpkgs/issues/267864

**Closed by anthonyroussel** 2024-04-07 15:14 UTC
Labels: 0.kind: bug, 6.topic: python
