### ISSUE TITLE
Logseq fails to open external links

### ISSUE THREAD

**Issue by vrinek** [NixOS/nixpkgs#218471] opened 2023-02-26 16:47 UTC
### Describe the bug

When I click on an HTTP/HTTPS link, instead of it opening in my default browser, nothing happens.

### Steps To Reproduce

1. install Logseq
   - picking either faab5d47a896ef3c40fa678588607b107cac0dc5 or 7db6808335f5307f94f0f49d73669e565f526f46 should work to reproduce the issue
   - eg `nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/7db6808335f5307f94f0f49d73669e565f526f46.tar.gz -p logseq`
3. run it
   - preferably from a terminal to be able to inspect the logs
5. click on an HTTP/HTTPS link
   - if you've never used Logseq before, the demo graph it presents on first run contains a few sample links

### Expected behavior

The line `new-window https://chrismcveigh.com/cm/welcome.html` is printed in the terminal where logseq is running from, but the URL is not opened on Firefox.

### Screenshots

_no applicable screenshots_

### Additional context

Logseq from 63f96b8e028fa93e63722a41e13d8d35b059a388 behaves fine, opening links on Firefox as it should.

I am on Gnome 43.2, Wayland.

```
❯ xdg-mime query default x-scheme-handler/http
firefox.desktop

❯ xdg-mime query default x-scheme-handler/https
firefox.desktop
```

`xdg-open https://chrismcveigh.com/cm/welcome.html` works fine from my terminal (Alacritty).

Initially I started the conversation on Logseq's repo, https://github.com/logseq/logseq/issues/8662. After some testing I noticed that this bug appears on a commit that repackages Logseq without bumping the version number. I assume this is a packaging issue, thus I moved the discussion here.

### Notify maintainers

@weihua-lu 

### Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.94, NixOS, 22.11 (Raccoon), 22.11.2643.0cf4274b5d0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, unstable"`
 - channels(vrnk): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by kilianar** [comment] 2023-02-26 17:32
This could be due to the switch to `run-appimage` in #205057. cc @LoveIsGrief

**Comment by LoveIsGrief** [comment] 2023-02-28 07:09
Darn, i think it's best to revert the changes I made. Appimage-run unfortunately runs the extracted app image in a chroot env. I think that would need portals like snap or flatpak to successfully call other apps like Firefox and the like - or extra work to make everything work as normal and I'm not the guy for that.

If someone has time to create a PR that reverts my changes, please feel free to make it. I don't know if I'll have the time this week.

It will break exporting the graph, but that's a compromise we can make, IMO. If there are clojure developers out there who would like to contribute a fix directly to logseq, your contribution would be very welcome! Somebody already wrote the beginnings of a fix but abandoned it because of the contributor license agreement. 

I'm on my phone right now and can't search for the relevant links.

**Comment by vrinek** [comment] 2023-02-28 11:13
I'll take a look into it, but I remember that Logseq from https://github.com/NixOS/nixpkgs/commit/63f96b8e028fa93e63722a41e13d8d35b059a388 does not work with Logseq Sync.

I'll revert the changes and see if this fixes the issue.

@LoveIsGrief when you have the time, please shoot me some instructions how to publish a graph. I want to run some tests and see if I can make it work.

**Comment by LoveIsGrief** [comment] 2023-02-28 19:37
@vrinek  the [logseq documentation](https://docs.logseq.com/#/page/publishing) has the step for publishing a graph.

As for Logseq Sync, last I heard it's a beta, paid only, closed source feature, and thus probably prone to break, so until it's stable, I'm not sure it would be worth investigating the issue.

**Comment by heinwol** [comment] 2023-03-26 18:52
> Expected behavior
> 
> The line `new-window https://chrismcveigh.com/cm/welcome.html` is printed in the terminal where logseq is running from, but the URL is not opened on Firefox.

I confirm the issue is still there, although I'm on xorg. Maybe irrelevant, but the behavior is exactly the same.
```
 - host os: `Linux 5.15.104, NixOS, 23.05 (Stoat), 23.05pre467130.a64e169e396`
```

**Comment by LoveIsGrief** [comment] 2023-04-05 16:45
@heinwol could you check if your installed logseq is now using electron?


Mine does (using master, which has https://github.com/NixOS/nixpkgs/pull/223625 merged into it)
```bash
$ grep electron $(which logseq)
exec "/nix/store/s1fcc5w9k5lp57asqm6d7n1jmvviz9hy-electron-23.1.1/bin/electron"  /nix/store/8cm0dw9mg9rqdgxcbr2jfhavjl48rs8j-logseq-0.9.1/share/logseq/resources/app "$@"
```

**Comment by heinwol** [comment] 2023-04-05 21:26
@LoveIsGrief Oh well, it's really working now! And yes, it's version 0.9.1 of logseq and yes, it uses electron now. Seems like that's it for this issue?

This is strange however. Nothing really changed except for upgrading from 0.8.18 to 0.9.1. Maybe it was an upstream issue?

**Comment by LoveIsGrief** [comment] 2023-04-05 22:01
My bad, I had the wrong PR number. It's this one. https://github.com/NixOS/nixpkgs/pull/219281

I fixed an issue by using `appimage-run`, but that runs in a chroot environment. The programs installed outside of the chroot env can't be run from within the chroot env, which was the root of this issue (and others, as mentioned in the PR). The PR reverted it and it probably just took a while to get backported.

@vrinek  can you confirm that it works for you now? (please check that your logseq now uses electron and not `appimage-run`)

**Comment by jtrees** [comment] 2023-04-06 20:20
I can confirm that I'm running the Electron version of logseq 0.9.1. and it's fixed for me now. Thanks!

**Comment by LoveIsGrief** [comment] 2023-04-07 09:31
For some reason it looks I can close this. It seems justified now that 3 affected people (including me) have confirmed that it's not an issue anymore.

**Closed by LoveIsGrief** 2023-04-07 09:31 UTC
Labels: 0.kind: bug
