### ISSUE TITLE
some keyboard keys are not working in latest nixos on asus vivobook x705ua

### ISSUE THREAD

**Issue by BjornMelgaard** [NixOS/nixpkgs#34554] opened 2018-02-03 11:53 UTC
## Issue description

after downloading latest iso (nixos-graphical-17.09.2905.c1d9aff56e0-x86_64-linux.iso), I've tried to install nixos, but:
- backspace key deletes characters, but instead of showing removal - it inserts space
- right key is not working, shows gibberish
- maybe other keys too are not working, haven't tried 

this issue is present in virtual console and in terminal inside graphical environment
this issue is not present in latest archlinux iso (archlinux-2018.02.01-x86_64.iso)

**Comment by dezgeg** [comment] 2018-02-03 12:01
Duplicate of #34364.

**Closed by dezgeg** 2018-02-03 12:01 UTC

**Comment by BjornMelgaard** [comment] 2018-02-03 12:22
Thanks, fixed in unstable
