### ISSUE TITLE
Package request: GLAuth

### ISSUE THREAD

**Issue by codyjamestechnical** [NixOS/nixpkgs#246893] opened 2023-08-03 02:34 UTC
**Project description**
Go-lang LDAP Authentication (GLAuth) is a secure, easy-to-use, LDAP server w/ configurable backends.

**Metadata**

* homepage URL: https://glauth.github.io
* source URL: https://github.com/glauth/glauth
* license: mit
* platforms: linux, darwin, windows

**Comment by pinn3** [comment] 2023-08-03 11:10
Duplicate of https://github.com/NixOS/nixpkgs/issues/239396

**Closed** 2023-09-11 09:33 UTC
Labels: 0.kind: packaging request
