### ISSUE TITLE
Build failure: ocrmypdf

### ISSUE THREAD

**Issue by ryane** [NixOS/nixpkgs#312332] opened 2024-05-17 02:18 UTC
### Steps To Reproduce

1. nix run nixpkgs#ocrmypdf on aarch64-darwin

### Build log

```
error: builder for '/nix/store/cxbk9533jlskl1mcnjyq5rfhwmyxqraa-python3.11-pillow-heif-0.16.0.drv' failed with exit code 132;
       last 10 log lines:
       >   File "/nix/store/0sirs1a62ajkl1jv6mj6ql9939i7kxxi-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_hooks.py", line 501 in __call__
       >   File "/nix/store/0fxw7kl4mwl8dkddk8rjnrahyh8kywbj-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/config/__init__.py", line 174 in main
       >   File "/nix/store/0fxw7kl4mwl8dkddk8rjnrahyh8kywbj-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/config/__init__.py", line 197 in console_main
       >   File "/nix/store/0fxw7kl4mwl8dkddk8rjnrahyh8kywbj-python3.11-pytest-8.1.1/lib/python3.11/site-packages/pytest/__main__.py", line 7 in <module>
       >   File "<frozen runpy>", line 88 in _run_code
       >   File "<frozen runpy>", line 198 in _run_module_as_main
       >
       > Extension modules: PIL._imaging, PIL._imagingmath, _pillow_heif, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, PIL._webp, cv2, PIL._imagingcms, _testcapi (total: 20)
       > /nix/store/x93s1hhc7864y6nqvmkqfs5dzsis7nga-pytest-check-hook/nix-support/setup-hook: line 53:  2785 Illegal instruction: 4  /nix/store/nmy6fyvrl4lyvn69nsliigpk0rhi4b4f-python3-3.11.9/bin/python3.11 -m pytest -k "not test_decode_threads and not test_opencv_crash"
       > /nix/store/g224xn9nwzf16jr94f1jx4jsnlazkl2a-stdenv-darwin/setup: line 1588: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/cxbk9533jlskl1mcnjyq5rfhwmyxqraa-python3.11-pillow-heif-0.16.0.drv'.
error: 1 dependencies of derivation '/nix/store/dqi0q22070c6lgk9lc4vkbgvazh557gx-python3.11-ocrmypdf-16.2.0.drv' failed to build
```

### Notify maintainers

@kiwi @dotlambda

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.4.0, macOS 14.4.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/3a8654qh4l49ssnzkwmf9iffyks8v7i3-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Guekka** [comment] 2024-06-09 16:34
Seems to be fixed by #316315. I cannot reproduce the issue

**Comment by Guekka** [comment] 2024-06-09 16:36
Actually, I was using an aarch64 but not darwin. Can you confirm it is fixed @ryane?

**Comment by ginkogruen** [comment] 2024-06-09 16:47
It builds fine for me on aarch64-darwin

**Comment by Guekka** [comment] 2024-06-09 17:14
Closing the issue then, thank you

**Closed by Guekka** 2024-06-09 17:14 UTC
Labels: 6.topic: darwin, 0.kind: build failure

**Comment by ryane** [comment] 2024-06-09 18:04
yep, it now builds for me on aarch64-darwin as well. thanks
