### ISSUE TITLE
Build failure: python311Packages.curio (impurity issue?)

### ISSUE THREAD

**Issue by Qyriad** [NixOS/nixpkgs#312780] opened 2024-05-19 02:14 UTC
### Steps To Reproduce

1. `nix build 'github:NixOS/nixpkgs/master#python311Packages.curio' --rebuild`
2. Observe that the test `tests/test_workers.py::test_cpu` fails

Note the `--rebuild`, as this package is [successfully building in Hydra](https://hydra.nixos.org/build/259896940), so I can only assume this is an impurity or non-determinism issue.

### Build log

https://gist.github.com/Qyriad/f2387d0fd7ebb61f5270dc6a3d3b544d

### Additional context

- I reproduced this on Nixpkgs commit 68ead29211bb9890f494af3a8b5643a831d9d4c4.
- `python312Packages.curio` *and* `python310Packages.curio` both succeed without issue

### Notify maintainers

@pbsds 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.30, NixOS, 24.05 (Uakari), 24.05.20240517.4a6b83b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0-lixpre20240518-62b1adf
 - nixpkgs: `/nix/store/0aavdx9m5ms1cj5pb1dx0brbrbigy8ij-source`
```

(Note: it says "Lix" as that's the primary Nix on my system, but I also reproduced this with Nix 2.18 with `sudo nix run 'nixpkgs#nixVersions.nix_2_18' -- build 'github:NixOS/nixpkgs/master#python311Packages.curio' --rebuild --store local`, so this is certainly not a Lix-specific issue)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Qyriad** [comment] 2024-05-19 02:18
Build for `python39Packages.curio` just finished successfully, so this is *just* failing on 3.11

**Comment by pbsds** [comment] 2024-05-19 12:35
Thank you. I was unable to reproduce even while running `stress`, but the provided log proved a race condition i found while reading the test. Fixed in https://github.com/NixOS/nixpkgs/pull/312874

**Closed** 2024-06-07 17:51 UTC
Labels: 6.topic: python, 6.topic: reproducible builds, 0.kind: build failure, 2.status: fix-in-staging
