### ISSUE TITLE
systemctl reload causes Prosody to read wrong configuration file

### ISSUE THREAD

**Issue by majewsky** [NixOS/nixpkgs#72367] opened 2019-10-31 13:39 UTC
I'm using the Prosody module with [this configuration](https://github.com/majewsky/nixos-modules/blob/e983aa57de6406906290c670e0d0d8be7aff6deb/prosody.nix). When I do `systemctl restart prosody.service`, everything works as expected:

```
Okt 31 14:22:13 hostname systemd[1]: Stopped Prosody XMPP server.
Okt 31 14:22:13 hostname prosody[11963]: socket: try to close server with id: 28179a0
Okt 31 14:22:13 hostname prosody[11963]: socket: closing client with id: 28179a0 server to close
Okt 31 14:22:13 hostname prosody[11963]: general: Shutting down...
Okt 31 14:22:13 hostname systemd[1]: prosody.service: Consumed 286ms CPU time, received 24.1K IP traffic, sent 19.6K IP traffic.
Okt 31 14:22:13 hostname prosody[11963]: general: Shutdown status: Cleaning up
Okt 31 14:22:13 hostname prosody[11963]: general: Shutdown complete
Okt 31 14:22:17 hostname systemd[1]: Starting Prosody XMPP server...
Okt 31 14:22:17 hostname prosody[13882]: mod_posix: Prosody is about to detach from the console, disabling further console output
Okt 31 14:22:17 hostname prosody[13884]: mod_posix: Successfully daemonized to PID 13884
Okt 31 14:22:17 hostname prosodyctl[13881]: Started
Okt 31 14:22:17 hostname systemd[1]: Started Prosody XMPP server.
```

However, when I do `systemctl reload prosody.service` instead (as one would like to do e.g. when rolling over to a new TLS cert in `security.acme.certs.${domainName}.postRun`), it says this instead:

```
Okt 31 14:13:39 hostname systemd[1]: Reloading Prosody XMPP server.
Okt 31 14:13:39 hostname prosody[11963]: mod_posix: Received SIGHUP
Okt 31 14:13:39 hostname systemd[1]: Reloaded Prosody XMPP server.
Okt 31 14:13:39 hostname prosody[11963]: startup: Reloading configuration file
Okt 31 14:13:39 hostname prosody[11963]: certmanager: Searching /nix/store/yq9k33s4n50rrfp1vxqyxxm5q9d3sjhw-prosody-0.11.2/etc/prosody/certs for a key and certificate for example.com...
Okt 31 14:13:39 hostname prosody[11963]: certmanager: No certificate/key found for example.com
Okt 31 14:13:39 hostname prosody[11963]: certmanager: Searching /nix/store/yq9k33s4n50rrfp1vxqyxxm5q9d3sjhw-prosody-0.11.2/etc/prosody/certs for a key and certificate for com...
Okt 31 14:13:39 hostname prosody[11963]: certmanager: No certificate/key found for com
Okt 31 14:13:39 hostname prosody[11963]: certmanager: Searching /nix/store/yq9k33s4n50rrfp1vxqyxxm5q9d3sjhw-prosody-0.11.2/etc/prosody/certs for a key and certificate for example.com...
Okt 31 14:13:39 hostname prosody[11963]: certmanager: No certificate/key found for example.com
Okt 31 14:13:39 hostname prosody[11963]: certmanager: Searching /nix/store/yq9k33s4n50rrfp1vxqyxxm5q9d3sjhw-prosody-0.11.2/etc/prosody/certs for a key and certificate for com...
Okt 31 14:13:39 hostname prosody[11963]: certmanager: No certificate/key found for com
Okt 31 14:13:39 hostname prosody[11963]: certmanager: Searching /nix/store/yq9k33s4n50rrfp1vxqyxxm5q9d3sjhw-prosody-0.11.2/etc/prosody/certs for a key and certificate for example.com...
Okt 31 14:13:39 hostname prosody[11963]: certmanager: No certificate/key found for example.com
Okt 31 14:13:39 hostname prosody[11963]: certmanager: Searching /nix/store/yq9k33s4n50rrfp1vxqyxxm5q9d3sjhw-prosody-0.11.2/etc/prosody/certs for a key and certificate for com...
Okt 31 14:13:39 hostname prosody[11963]: certmanager: No certificate/key found for com
```

I'm not entirely sure why it's trying to read from `/nix/store/yq9k33s4n50rrfp1vxqyxxm5q9d3sjhw-prosody-0.11.2/etc/prosody/certs` when I've set it up to read from `/var/lib/prosody/certs` in my configuration. My hypothesis is that it's reading `/nix/store/yq9k33s4n50rrfp1vxqyxxm5q9d3sjhw-prosody-0.11.2/etc/prosody/prosody.cfg.lua` instead of `/etc/prosody/prosody.cfg.lua`, because the former references the `certs` directory that Prosody is looking at.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.80, NixOS, 19.09.976.c75de8bc12c (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(stefan): `""`
 - channels(root): `"nixos-19.09.976.c75de8bc12c, nixos-unstable-20.03pre198214.4cd2cb43fb3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- services.prosody
```

**Comment by flokli** [comment] 2020-05-23 17:28
@majewsky can you check if this is still the case on `master`? There have been some changes in the meantime.

Also cc @petabyteboy due to 24d5e30b5fcbcd27121047ed210f506273755832.

**Comment by majewsky** [comment] 2020-05-23 18:19
Yes, I can reproduce on the 20.03 channel. Last `nixos-rebuild switch --update` succeeded this morning.

**Comment by flokli** [comment] 2020-05-23 18:43
@NinjaTrappeur, can you take a look at this?

**Comment by NinjaTrappeur** [comment] 2020-05-24 06:44
:+1: I'll have a look tonight.

**Comment by NinjaTrappeur** [comment] 2020-05-24 18:05
First of all, thanks for the detailed report Stefan.

We recently heavily reworked this module (more details in
https://github.com/NixOS/nixpkgs/pull/86067 and in the [unstable
manual](https://hydra.nixos.org/build/119310661/download/2/nixos/index.html#module-services-prosody)),
that being said, we did not back-ported these changes to 20.03, they
are currently living only in unstable.

I cannot reproduce the bug you're experiencing on unstable. That being
said, I did manage to reproduce this on 20.03. While I can see the same
error as you in the logs, the prosody server seems to use the right
certificate. (Note: I performed this repro in a NixOS VM test with a
self-signed certificates.)

The main difference between 20.03 and unstable here seems to be that
20.03 is still pinning prosody 0.11.3 while unstable is pinning 0.11.5.
I just read the 0.11.4 and 0.11.5 changelog, there's no mention of this
behaviour. That being said, this could have been fixed without appearing
in the changelog.

I don't think prosody is loading the builtin conf file
(/nix/store/xxxx-prosody-xxxx/etc/prosody.cfg.lua) in your case.
Instead, I think prosody is trying to load the certificates from the
specified path, using this nix store as a fallback mechanism. Note: I
did not observed this behaviour with the 0.11.5 version.

We reload prosody by sending SIGHUP to the running process using `kill
-HUP $MAINPID` as per suggested in https://issues.prosody.im/280. This
is also what Debian and Fedora are doing, I guess the problem is not
coming from here.

Now, what could you do?

Honestly, I think moving to unstable is the easiest option for you
here. You'll benefit from the module improvement and won't experience
the same bug.

If that's not an option for you, I'd like you to check whether or not
prosody is sending the right certificate to its peers.

In any case, I think we should backport
ce2a2afac79052b2d0286ff32996fe2097f0d8bfb. This version bump shouldn't
introduce any configuration change and may fix this bug. I'll open a
backport PR shortly.

---------

Unrelated Note for OP: you could spare this letsencrypt key dance by
sharing the keys using a specific group:

```
  security.acme = {
    (snip)
    certs = {
      "example.com" = {
        allowKeysForGroup = true;
        group = "examplecomcertgr";
        (snip)
      };
    };
    (snip)
  };

  users = {
    groups.sslcertgr = {
      name = "examplecomcertgr";
      members = [ "prosody" ];
    };
```

**Comment by NinjaTrappeur** [comment] 2020-05-24 18:20
Backport PR there: https://github.com/NixOS/nixpkgs/pull/88798

**Comment by flokli** [comment] 2020-05-24 21:54
@majewsky can you give this PR a try and report back if it changes things?

**Comment by majewsky** [comment] 2020-06-04 21:02
Moving to unstable is not an option for me unless stuff were actively broken.

With Prosody 0.11.5 on 20.03, the log output for reloading does not reference /nix/store paths anymore, but I still get:

```
Jun 04 22:59:36 bet systemd[1]: Reloading Prosody XMPP server.
Jun 04 22:59:36 bet systemd[1]: Reloaded Prosody XMPP server.
Jun 04 22:59:36 bet prosody[1081]: mod_posix: Received SIGHUP
Jun 04 22:59:36 bet prosody[1081]: startup: Reloading configuration file
Jun 04 22:59:36 bet prosody[1081]: example.com:tls: Creating context for c2s
Jun 04 22:59:36 bet prosody[1081]: certmanager: Searching /etc/prosody/certs for a key and certificate for example.com...
Jun 04 22:59:36 bet prosody[1081]: certmanager: No certificate/key found for example.com
Jun 04 22:59:36 bet prosody[1081]: certmanager: Searching /etc/prosody/certs for a key and certificate for com...
Jun 04 22:59:36 bet prosody[1081]: certmanager: No certificate/key found for com
Jun 04 22:59:36 bet prosody[1081]: example.com:tls: Creating context for s2sout
Jun 04 22:59:36 bet prosody[1081]: certmanager: Searching /etc/prosody/certs for a key and certificate for example.com...
Jun 04 22:59:36 bet prosody[1081]: certmanager: No certificate/key found for example.com
Jun 04 22:59:36 bet prosody[1081]: certmanager: Searching /etc/prosody/certs for a key and certificate for com...
Jun 04 22:59:36 bet prosody[1081]: certmanager: No certificate/key found for com
Jun 04 22:59:36 bet prosody[1081]: example.com:tls: Creating context for s2sin
Jun 04 22:59:36 bet prosody[1081]: certmanager: Searching /etc/prosody/certs for a key and certificate for example.com...
Jun 04 22:59:36 bet prosody[1081]: certmanager: No certificate/key found for example.com
Jun 04 22:59:36 bet prosody[1081]: certmanager: Searching /etc/prosody/certs for a key and certificate for com...
Jun 04 22:59:36 bet prosody[1081]: certmanager: No certificate/key found for com
```

However, my client doesn't complain about invalid certs when connecting after the server reload, so either Prosody eventually seems to pick up the correct certificate or it continues with the previous certificate.

**Comment by petabyteboy** [comment] 2020-06-05 07:47
Interesting, maybe this is actually the same behavior we have on unstable. I really don't understand what causes it to load a wrong configuration file. `prosodyctl` is actually wrapped to include a `--config` parameter.

**Comment by petabyteboy** [comment] 2020-06-05 08:23
Okay I found out why I don't have this issue. Back then (tm) when I set up my prosody, I found out that reloading does not update the certificate correctly, so I told my acme client to `systemctl restart prosody` after a successful renewal. Maybe this is an acceptable workaround for you.

**Comment by flokli** [comment] 2020-12-02 22:32
20.03 is marked as EOL since November 27th.

Does that issue still appear in 20.09? @petabyteboy, did you check if only reloading prosody gets it to re-read the new config files?

**Comment by petabyteboy** [comment] 2020-12-02 22:37
I'm not 100% sure how to check if the right config file was read. But this is how it looks after a reload:

```
Dec 02 23:33:46 schinken systemd[1]: Reloading Prosody XMPP server.
Dec 02 23:33:46 schinken prosody[2564]: mod_posix: Received SIGHUP
Dec 02 23:33:46 schinken prosody[2564]: startup: Reloading configuration file
Dec 02 23:33:46 schinken systemd[1]: Reloaded Prosody XMPP server.
Dec 02 23:33:47 schinken prosody[2564]: petabyteboy.de:tls: Certificates reloaded
```

But then again I never saw bad log messages.

**Comment by flokli** [comment] 2020-12-03 11:15
Can you `strace` prosody while it's during reload, to confirm?

**Comment by petabyteboy** [comment] 2020-12-03 11:26
```
openat(AT_FDCWD, "/etc/prosody/prosody.cfg.lua", O_RDONLY) = 40
fstat(40, {st_mode=S_IFREG|0444, st_size=5256, ...}) = 0
```

**Comment by flokli** [comment] 2020-12-03 13:08
Then I'd say prosody will successfully read our updated configuration file during reload. If it still doesn't pick up updated certs in that config file, that'd be an upstream bug. Let's close this one.

**Closed by flokli** 2020-12-03 13:08 UTC
Labels: 0.kind: bug, 6.topic: nixos
