### ISSUE TITLE
VirtualBox Guest Additions screen resizing not working with VMSVGA since recent update

### ISSUE THREAD

**Issue by angryzor** [NixOS/nixpkgs#243671] opened 2023-07-15 15:26 UTC
### Describe the bug
Before a recent update of my system (running VirtualBox Guest Additions 6.1.40 r154048), guest screen resizing worked using the VMSVGA video adapter. A recent update of NixOS updates the Guest Additions to 7.0.8 r156879 and now this feature is no longer working properly.

### Steps To Reproduce
1. Run NixOS in a VirtualBox VM, configure VMSVGA adapter.
2. Enable guest additions with `virtualisation.virtualbox.guest.enable = true;`.
3. Try to resize the VM window.

### Expected behavior
Guest screen should resize to fill window.

### Additional context
Relevant diff of the VBox log between the 2 NixOS generations:

```diff
1679,1691d1679
< VMMDev: Guest Log: 14:55:06.645003 main     VBoxService 6.1.40 r154048 (verbosity: 0) linux.amd64 (Oct 11 2022 16:03:32) release log
< VMMDev: Guest Log: 14:55:06.645005 main     Log opened 2023-07-15T14:55:06.644996000Z
< VMMDev: Guest Log: 14:55:06.645067 main     OS Product: Linux
< VMMDev: Guest Log: 14:55:06.645108 main     OS Release: 5.15.113
< VMMDev: Guest Log: 14:55:06.645128 main     OS Version: #1-NixOS SMP Wed May 24 16:36:55 UTC 2023
< VMMDev: Guest Log: 14:55:06.645147 main     Executable: /nix/store/ip7v78fvhv8aq0s8ihsvj63nqakyyzvs-VirtualBox-GuestAdditions-6.1.40-5.15.113/bin/VBoxService
< VMMDev: Guest Log: 14:55:06.645147 main     Process ID: 645
< VMMDev: Guest Log: 14:55:06.645148 main     Package type: LINUX_64BITS_GENERIC
< VMMDev: Guest Log: 14:55:06.648322 main     6.1.40 r154048 started. Verbose level = 0
< VMMDev: Guest Log: 14:55:06.648547 main     vbglR3GuestCtrlDetectPeekGetCancelSupport: Supported (#1)
< Guest Control: GUEST_MSG_REPORT_FEATURES: 0x7, 0x8000000000000000
< GUI: UISession::sltAdditionsChange: GA state change event came, notifying listeners
< GUI: UIMachineLogicNormal::sltCheckForRequestedVisualStateType: Requested-state=1, Machine-state=6
---
> VMMDev: Guest Log: 15:02:04.335656 main     VBoxService 7.0.8 r156879 (verbosity: 0) linux.amd64 (Apr 17 2023 18:38:33) release log
> VMMDev: Guest Log: 15:02:04.335659 main     Log opened 2023-07-15T15:02:04.335650000Z
> VMMDev: Guest Log: 15:02:04.335734 main     OS Product: Linux
> VMMDev: Guest Log: 15:02:04.336580 main     OS Release: 6.1.37
> VMMDev: Guest Log: 15:02:04.336655 main     OS Version: #1-NixOS SMP PREEMPT_DYNAMIC Sat Jul  1 11:16:27 UTC 2023
> VMMDev: Guest Log: 15:02:04.336726 main     Executable: /nix/store/53d62dqgh899r0lwrr34qh8pvmnqp1g2-VirtualBox-GuestAdditions-7.0.8-6.1.37/bin/VBoxService
> VMMDev: Guest Log: 15:02:04.336727 main     Process ID: 654
> VMMDev: Guest Log: 15:02:04.336727 main     Package type: LINUX_64BITS_GENERIC
> VMMDev: Guest Log: 15:02:04.350156 main     VMSVGA DRM resizing client not started, rc=VERR_FILE_NOT_FOUND
> VMMDev: Guest Log: 15:02:04.350234 main     7.0.8 r156879 started. Verbose level = 0
> VMMDev: Guest Log: 15:02:04.350638 main     vbglR3GuestCtrlDetectPeekGetCancelSupport: Supported (#1)
> GUI: UISession::sltAdditionsChange: GA state change event came, notifying listeners
> GUI: UIMachineLogicNormal::sltCheckForRequestedVisualStateType: Requested-state=1, Machine-state=6
> Guest Control: GUEST_MSG_REPORT_FEATURES: 0xf, 0x8000000000000000
```

Note the line `VMSVGA DRM resizing client not started, rc=VERR_FILE_NOT_FOUND`

I found out that `VBoxClient --vmsvga` is not running (`ps` output):

```
user      932       1  0 17:01 ?        00:00:00 /nix/store/53d62dqgh899r0lwrr34qh8pvmnqp1g2-VirtualBox-GuestAdditions-7.0.8-6.1.37/bin/VBoxClient --clipboard
user      934     932  0 17:01 ?        00:00:00 /nix/store/53d62dqgh899r0lwrr34qh8pvmnqp1g2-VirtualBox-GuestAdditions-7.0.8-6.1.37/bin/VBoxClient --clipboard
user      947       1  0 17:01 ?        00:00:00 /nix/store/53d62dqgh899r0lwrr34qh8pvmnqp1g2-VirtualBox-GuestAdditions-7.0.8-6.1.37/bin/VBoxClient --seamless
user      949     947  0 17:01 ?        00:00:00 /nix/store/53d62dqgh899r0lwrr34qh8pvmnqp1g2-VirtualBox-GuestAdditions-7.0.8-6.1.37/bin/VBoxClient --seamless
user      955       1  0 17:01 ?        00:00:00 /nix/store/53d62dqgh899r0lwrr34qh8pvmnqp1g2-VirtualBox-GuestAdditions-7.0.8-6.1.37/bin/VBoxClient --draganddrop
user      957     955  0 17:01 ?        00:00:00 /nix/store/53d62dqgh899r0lwrr34qh8pvmnqp1g2-VirtualBox-GuestAdditions-7.0.8-6.1.37/bin/VBoxClient --draganddrop
```

Manually running `/nix/store/53d62dqgh899r0lwrr34qh8pvmnqp1g2-VirtualBox-GuestAdditions-7.0.8-6.1.37/bin/VBoxClient --vmsvga` fixes the problem for the current session.

### Notify maintainers

@K900 , @erdnaxe 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.37, NixOS, 23.05 (Stoat), 23.05.1532.aed4b19d312`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"home-manager-21.05.tar.gz, nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by angryzor** [comment] 2023-07-20 16:53
I took some time to look at it myself and it seems like this is not a bug in the NixOS scripts, but a change in the VBox Guest Additions themselves.

**Comment by angryzor** [comment] 2023-07-20 17:24
Ok so it seems to be multiple problems:

The new version of the guest additions starts the resizing service as `VBoxClient --vmsvga-session`, a new service that relies on a kernel module called `vmwgfx`. This kernel module fails to start on my machine:

```
May 28 08:42:48 devbox kernel: [drm:vmw_msg_ioctl [vmwgfx]] *ERROR* Failed to open channel.
May 28 08:42:48 devbox kernel: [drm:vmw_msg_ioctl [vmwgfx]] *ERROR* Failed to open channel.
```

Aside of that, normally `VBoxClient --vmsvga-session` then falls back to `VBoxClient --vmsvga` using a fork. This, however, also fails:

```
17:03:10.957034 main     VBoxClient 7.0.8 r156879 (verbosity: 4) linux.amd64 (Apr 17 2023 18:38:34) release log
17:03:10.957035 main     Log opened 2023-07-20T17:03:10.957031000Z
17:03:10.957138 main     OS Product: Linux
17:03:10.957168 main     OS Release: 6.1.37
17:03:10.957195 main     OS Version: #1-NixOS SMP PREEMPT_DYNAMIC Sat Jul  1 11:16:27 UTC 2023
17:03:10.957220 main     Executable: /nix/store/53d62dqgh899r0lwrr34qh8pvmnqp1g2-VirtualBox-GuestAdditions-7.0.8-6.1.37/bin/VBoxClient
17:03:10.957221 main     Process ID: 1659
17:03:10.957221 main     Package type: LINUX_64BITS_GENERIC
17:03:10.957289 main      VBoxClient 7.0.8 r156879 started. Verbose level = 4. Wayland environment detected: no
17:03:10.957315 main      Service: VMSVGA display assistant
17:03:10.959266 main      Initializing service ...
17:03:10.959286 main     VBoxClient VMSVGA: probing Desktop Environment helper 'GNOME3'
17:03:10.959292 main     VBoxClient VMSVGA: probing Desktop Environment helper 'GENERIC'
17:03:10.959633 dcm-task VBoxClient VMSVGA: vbcl_hlp_generic_display_change_event_monitor_worker started
17:03:10.960153 main     VBoxClient VMSVGA: attempt to start display change monitor thread, rc=VINF_SUCCESS
17:03:10.960163 main     VBoxClient VMSVGA: using Desktop Environment specific display helper 'GENERIC'
17:03:10.960181 main     VBoxClient VMSVGA: Error: unable to connect to IPC server, rc=VERR_FILE_NOT_FOUND
17:03:10.960258 dcm-task VBoxClient VMSVGA: vbcl_hlp_generic_display_change_event_monitor_worker ended
17:03:10.960268 main     VBoxClient VMSVGA: helper service terminated, rc=VINF_SUCCESS
17:03:10.960280 main     VBoxClient VMSVGA: starting legacy service, rc=VERR_FILE_NOT_FOUND
17:03:10.960283 main     VBoxClient VMSVGA: Service is not availabe, skipping
17:03:10.960329 main     VBoxClient VMSVGA: End of log file - Log started 2023-07-20T17:03:10.957031000Z
```

The reason for this is that it is trying to run `/usr/bin/VBoxClient --vmsvga`:

```
/** Defines the DRM client executable (image). */
# define VBOX_DRMCLIENT_EXECUTABLE           "/usr/bin/VBoxDRMClient"
# define VBOX_DRMCLIENT_LEGACY_EXECUTABLE    "/usr/bin/VBoxClient"
/** Defines the guest property that defines if the DRM resizing client needs to be active or not. */
# define VBOX_DRMCLIENT_GUEST_PROP_RESIZE    "/VirtualBox/GuestAdd/DRMResize"

VBGLR3DECL(int) VbglR3DrmLegacyClientStart(void)
{
#if defined(RT_OS_LINUX)
    const char *apszArgs[3] = { VBOX_DRMCLIENT_LEGACY_EXECUTABLE, "--vmsvga", NULL };
    return VbglR3DrmStart(VBOX_DRMCLIENT_LEGACY_EXECUTABLE, apszArgs);
#else
    return VERR_NOT_SUPPORTED;
#endif
}
```

which of course doesn't exist on NixOS.

**Comment by angryzor** [comment] 2023-07-20 17:55
It looks like the first failure is caused originally by the same problem as the second failure:

```
00:22:42.099971 VMMDev: Guest Log: 16:55:51.835845 main     VBoxService 7.0.8 r156879 (verbosity: 0) linux.amd64 (Apr 17 2023 18:38:33) release log
00:22:42.099984 VMMDev: Guest Log: 16:55:51.835847 main     Log opened 2023-07-20T16:55:51.835840000Z
00:22:42.100273 VMMDev: Guest Log: 16:55:51.836165 main     OS Product: Linux
00:22:42.100307 VMMDev: Guest Log: 16:55:51.836206 main     OS Release: 6.1.37
00:22:42.100340 VMMDev: Guest Log: 16:55:51.836238 main     OS Version: #1-NixOS SMP PREEMPT_DYNAMIC Sat Jul  1 11:16:27 UTC 2023
00:22:42.100377 VMMDev: Guest Log: 16:55:51.836270 main     Executable: /nix/store/53d62dqgh899r0lwrr34qh8pvmnqp1g2-VirtualBox-GuestAdditions-7.0.8-6.1.37/bin/VBoxService
00:22:42.100384 VMMDev: Guest Log: 16:55:51.836271 main     Process ID: 668
00:22:42.100387 VMMDev: Guest Log: 16:55:51.836272 main     Package type: LINUX_64BITS_GENERIC
00:22:42.110010 VMMDev: Guest Log: 16:55:51.845886 main     VMSVGA DRM resizing client not started, rc=VERR_FILE_NOT_FOUND
00:22:42.110123 VMMDev: Guest Log: 16:55:51.846011 main     7.0.8 r156879 started. Verbose level = 0
00:22:42.110347 VMMDev: Guest Log: 16:55:51.846225 main     vbglR3GuestCtrlDetectPeekGetCancelSupport: Supported (#1)
```
->
```c
VBGLR3DECL(int) VbglR3DrmClientStart(void)
{
#if defined(RT_OS_LINUX)
    const char *apszArgs[2] = { VBOX_DRMCLIENT_EXECUTABLE, NULL }; /** @todo r=andy Pass path + process name as argv0? */
    return VbglR3DrmStart(VBOX_DRMCLIENT_EXECUTABLE, apszArgs);
#else
    return VERR_NOT_SUPPORTED;
#endif
}
```

I'll see if I can make a patch.

**Comment by ChanceHarrison** [comment] 2023-08-19 08:35
@angryzor Do you still plan on trying to make a patch for this or would it be good if someone else picked this up?

**Comment by puterboy** [comment] 2023-09-27 05:59
I am having the same problem. Is anybody planning on fixing this?
If not is it possible to patch this individually? If so what do we need to do to fix it?

**Comment by puterboy** [comment] 2023-09-27 06:01
Note you can get resizing to work if you "downgrade" to `VBoxSVGA` (instead of `VMSVGA`) and if you **disable** 3D acceleration.
Still would be good to get this fixed to work with the preferred graphics driver.

**Comment by kjeremy** [comment] 2023-09-27 15:15
> The new version of the guest additions starts the resizing service as `VBoxClient --vmsvga-session`, a new service that relies on a kernel module called `vmwgfx`. This kernel module shows errors on my machine. I'm currently not sure if they are relevant:
> 
> ```
> May 28 08:42:48 devbox kernel: [drm:vmw_msg_ioctl [vmwgfx]] *ERROR* Failed to open channel.
> May 28 08:42:48 devbox kernel: [drm:vmw_msg_ioctl [vmwgfx]] *ERROR* Failed to open channel.
> ```

`vmwgfx` is VMWare's guest driver. I would be surprised if Virtual Box was using it.

**Comment by angryzor** [comment] 2023-09-28 11:43
> @angryzor Thanks for opening this issue and for the root-cause analysis you have done.
> 
> Do you still plan on trying to make a patch for this or would it be good if someone else picked this up?

I've been a bit preoccupied with other things lately, I'm sorry for the radio silence. The issue is that this is a lot more complex than I initially thought. I thought it was just some variables to be set during compilation or a small patch to be added to the derivation, but this specific guest additions package currently packages a binary distribution built by Oracle itself, so the strings are compiled into the binary.

I could try using buildFHSEnv to create an FHS wrapper environment, but it's kind of dirty since the source code for the guest additions seems to be available: the main virtualbox package is built from source and the source package it uses includes (as far as I can see, unless I'm missing something) the source code for the guest additions, so I'm not sure why the guest additions package instead uses the prebuilt binaries.

The better solution is probably to instead rework the package to build from source... However, I'm a bit out of my depth with building an entire package from scratch, and also kind of afraid that I would break things with such a large change.

I'll have another look at it this weekend, if I can't figure it out I'll pass on the torch.

> > The new version of the guest additions starts the resizing service as `VBoxClient --vmsvga-session`, a new service that relies on a kernel module called `vmwgfx`. This kernel module shows errors on my machine. I'm currently not sure if they are relevant:
> > ```
> > May 28 08:42:48 devbox kernel: [drm:vmw_msg_ioctl [vmwgfx]] *ERROR* Failed to open channel.
> > May 28 08:42:48 devbox kernel: [drm:vmw_msg_ioctl [vmwgfx]] *ERROR* Failed to open channel.
> > ```
> 
> `vmwgfx` is VMWare's guest driver. I would be surprised if Virtual Box was using it.

It does, their VMSVGA driver is an implementation of VMWare's protocol.

**Comment by AnhQuanTrl** [comment] 2023-11-12 02:43
Having the similar issue with VirtualBox. Is anyone still working on it?

**Comment by AnhQuanTrl** [comment] 2023-11-12 15:52
Hi everyone. I have been able to fix this issue. Documenting it here in case someone in the future would need. The issue is due to Wayland (sigh). I am using Gnome with GDM. When I logged in, I need to switch session from `gnome` to `gnome-xorg`. Afterward, I fired up the terminal and execute `VBoxClient --vmsvga` and it worked!!!
I am now able to use multiple screens feature as well as auto resizing.

**Comment by ChanceHarrison** [comment] 2023-11-12 17:52
@AnhQuanTrl Knowing that switching back to X is a workaround is good; thanks for sharing that. I wouldn't call it a fix, though. Something still needs to be discovered or fixed to support Wayland sessions.

**Comment by C0RD** [comment] 2023-11-14 08:41
> > The new version of the guest additions starts the resizing service as `VBoxClient --vmsvga-session`, a new service that relies on a kernel module called `vmwgfx`. This kernel module shows errors on my machine. I'm currently not sure if they are relevant:
> > ```
> > May 28 08:42:48 devbox kernel: [drm:vmw_msg_ioctl [vmwgfx]] *ERROR* Failed to open channel.
> > May 28 08:42:48 devbox kernel: [drm:vmw_msg_ioctl [vmwgfx]] *ERROR* Failed to open channel.
> > ```
> 
> `vmwgfx` is VMWare's guest driver. I would be surprised if Virtual Box was using it.

as the smvga-driver used in Virtualbox is taken from vmware it makes sense to rely on vmgfx.

```
Graphics Controller: Specifies the graphics adapter type used by the guest VM. Note that
you must install the Guest Additions on the guest VM to specify the VBoxSVGA or VMSVGA
graphics controller. The following options are available:

– VBoxSVGA: The default graphics controller for new VMs that use Windows 7 or later. This graphics controller improves performance and 3D support when compared to the
legacy VBoxVGA option.

- VBoxVGA: Use this graphics controller for legacy guest OSes. This is the default graphics controller for Windows versions before Windows 7 and for Oracle Solaris. 3D acceleration is not supported for this graphics controller.

- VMSVGA: Use this graphics controller to emulate a VMware SVGA graphics device. This is the default graphics controller for Linux guests.

- None: Does not emulate a graphics adapter type

```

**Comment by dlouwers** [comment] 2023-11-15 10:04
Hi, I am a new user of NixOS and would like to learn how to work with NixOS through VirtualBox. Is there currently a known working configuration that won't require me to run the VBoxClient everytime I start the system?  I am ok with it being X11 instead of wayland, as long as it enables me to comfortably work with a NixOS desktop environment with guest additions working until a permanent fix has been developed.

**Comment by Yarny0** [comment] 2023-11-22 15:25
> Is there currently a known working configuration that won't require me to run the VBoxClient everytime I start the system?

<details>
<summary>I'm using this module in my VBox machine configurations (with X11) as a workaround</summary>

```nix
{ config, lib, pkgs, ... }:

let

  inherit (config.boot.kernelPackages) virtualboxGuestAdditions;

  path = lib.strings.makeBinPath [
    pkgs.gnugrep
    pkgs.xorg.xorgserver.out
    pkgs.which
  ];

in

{
  config.services.xserver.displayManager.sessionCommands = ''
    PATH=${path}:$PATH  ${lib.meta.getExe' virtualboxGuestAdditions "VBoxClient"} --vmsvga
  '';
}
```

</details>

**Comment by dlouwers** [comment] 2023-11-27 16:38
Thanks @Yarny0, have had an opportunity to try it out on a fresh AMD64 Gnome install. `nixos-rebuild1` is complaining about the single quote after `getExe`. If I remove that instead I get `attempt to call something which is not a function but a string with context`. These are not things I am experienced enough with to debug I am afraid. After all I am just installing to be able to learn NixOS. Perhaps it's better for me to write off running NixOS as a desktop guest in VirtualBox as unsupported and try a server installation instead, using SSH to dial in?

**Comment by Yarny0** [comment] 2023-11-27 17:08
> `nixos-rebuild` is complaining about the single quote after `getExe`.

Oh, on which channel are you?  The functions `getExe` and `getExe'` are actually two different functions with exactly these names (the single quote is just part of the function name of the second function).

But: `getExe'` is quite new and not available in NixOS 23.05.

You can replace the offending line with this one, which should have the same outcome (not tested!):

```nix
PATH=${path}:$PATH  ${virtualboxGuestAdditions}/bin/VBoxClient --vmsvga
```

**Comment by dlouwers** [comment] 2023-11-27 20:12
I have downloaded the standard ISO from https://nixos.org/download.html#nixos-iso
Looking at the last line of my config this seems to indeed be 23.05.
Your alternative line seems to have worked. It produced a valid rebuild after which I did a reboot. However I still don't seems to have things like automatic resizing and clipboard support working. Do they need to be enabled separately somehow?

**Comment by Yarny0** [comment] 2023-11-28 11:20
Clipboard etc. should also work without auto-resizing.  Is `virtualisation.virtualbox.guest.enable = true;` enabled in your config?  Is any of the vboxclient-Processes running when you're logged in (`ps aux | grep -i vbox`)?

**Comment by dlouwers** [comment] 2023-11-28 13:08
Yes, virtualbox is enabled in the configuration. `VBoxService --foreground` is running as root, but no `VBoxClient`.

**Comment by Yarny0** [comment] 2023-11-29 11:17
It works with this configuration (host and guest fresh NixOS 23.05, `vbox-fix.nix` is the workaround module stated earlier).

<details>
<summary>configuration.nix</summary>

```nix
{
  imports = [
    ./hardware-configuration.nix
    ./vbox-fix.nix
  ];
  boot.loader.grub.enable = true;
  boot.loader.grub.efiSupport = true;
  boot.loader.grub.efiInstallAsRemovable = true;
  boot.loader.grub.device = "nodev";
  boot.loader.efi.canTouchEfiVariables = false;
  networking.hostName = "nixos";
  networking.networkmanager.enable = true;
  services.xserver.enable = true;
  services.xserver.displayManager.lightdm.enable = true;
  services.xserver.desktopManager.xfce.enable = true;
  users.users.alice.isNormalUser = true;
  system.stateVersion = "23.05";
}
```

</details>

Maybe my solution isn't compatible with your display manager something, or similar...

You might try this config and then gradually change it towards yours until it breaks.

Otherwise, I'm out of ideas.

**Comment by dlouwers** [comment] 2023-11-29 11:40
@Yarny0 Ok, that seems to work for now. Will try to reconstruct the default Gnome installation and see what element breaks VBox support. Thanks for your help so far. Will post back any findings.

**Comment by dlouwers** [comment] 2023-11-29 11:53
Surprisingly it looks like having a regular user already breaks it. When I log in with a non-root user it complains that it failed to register resizing support.

**Comment by FriedrichAltheide** [comment] 2024-02-16 07:07
I am currently rewriting the guest addition package description. Current state: resizing and clipboard are working on gnome with wayland as well as X11.

If someone wants to give it a try. My changes can be found here: https://github.com/FriedrichAltheide/nixpkgs/tree/release-23.11-virtualboxGuestAdditionsFixes

**Comment by dsharp-pivotal** [comment] 2024-03-08 00:21
FWIW, I gave both your release-23.11 branch and #290122 a spin and they seem to work.

I'm new to NixOS; this is how I figured out to test:
`nixos-rebuild -I nixpkgs=https://github.com/FriedrichAltheide/nixpkgs/archive/refs/heads/release-23.11-virtualboxGuestAdditionsFixes.tar.gz switch`
or:
`nixos-rebuild -I nixpkgs=https://github.com/FriedrichAltheide/nixpkgs/archive/refs/heads/virtualbox-guest-additions-fixes.tar.gz switch`
Not sure if there's a better or more targeted way to test.

x86_64 Linux guest, Windows host. Virtualbox 7.0.14

**Closed** 2024-03-28 08:42 UTC
Labels: 0.kind: bug

**Comment by nebulorum** [comment] 2024-03-28 10:53
Total noob question. I was investigation this exact issue. How that it's merge how do I update my version? `nixos-rebuild switch --upgrade`. I was dabbling with unstable but this is not a program as far as I get it. Sorry for the dumb questions, but would love to get this tested on my VM.

**Comment by K900** [comment] 2024-03-28 10:55
You need to wait for the PR to reach the channel you're using, and then `nixos-rebuild switch --upgrade`. You can use https://nixpk.gs/pr-tracker.html?pr=290122 to track it.

**Comment by nebulorum** [comment] 2024-03-28 12:00
Cool, so it will get to unstable first, and then I still need somehow update from the unstable branch. Will continue googling then.

**Comment by nebulorum** [comment] 2024-04-01 22:30
I've seen that the package is now on unstable, and have bee trying to build and failing. Lot's of learning, but I assume I'm doing something dumb. https://discourse.nixos.org/t/install-unstable-virtualbox-7-0-14/42502/2
