### ISSUE TITLE
openshot-qt icons do not appear

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#17964] opened 2016-08-24 16:18 UTC
## Issue description

The play/stop/etc. icons on openshot don't show up for. @tohl, do they show up for you?

This renders the app unsable:

![image](https://cloud.githubusercontent.com/assets/3359345/17938614/94429b04-6a1e-11e6-8f0b-db73f62177fd.png)
### Steps to reproduce

`nix-build '<nixpks>' -A openshot-qt && ./result/bin/openshot-qt`

I've tried adding `wrapGAppsHook` & `gnome3.adwaita-icon-theme` without success.
## Technical details
- Nixpkgs version: 99cb230

**Comment by tohl** [comment] 2016-08-24 20:50
> The play/stop/etc. icons on openshot don't show up for. @tohl, do they
> show up for you?

You are right, they dont show for me now.

This works:

nix-build '<nixpkgs>' -A openshot-qt -I nixpkgs=https://nixos.org/channels/nixos-unstable/nixexprs.tar.xz

Does it also work for you?

Tomas

**Comment by bjornfor** [comment] 2017-03-05 21:23
@obadz: Still an issue? I have icons in master, release-17.03 and release-16.09.

My NixOS system is on master, so I ran the program like ```nix-build -A openshot-qt && ./result/bin/openshot-qt``` from my nixpkgs tree. Hoping it doesn't pick up a lot of stuff from my system/user profiles.

**Comment by obadz** [comment] 2017-03-13 22:49
@bjornfor, I ran the exact same command on f51f167008 and still no icons.

**Comment by davidak** [comment] 2017-12-20 15:00
I do have Icons. So is it fixed now, @obadz?

![screenshot_2017-12-20_15-58-23](https://user-images.githubusercontent.com/91113/34213168-b88cb718-e59e-11e7-9ec2-2a7c74124af6.png)

---
 - desktop: Xfce
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.70, NixOS, 17.09.2430.ed3b1bc8448 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.2430.ed3b1bc8448"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by aanderse** [comment] 2019-02-17 02:59
@obadz please confirm issue still exists or close.

**Comment by davidak** [comment] 2019-02-17 22:38
It still works for me, using GNOME 3 now.

`nix run nixpkgs.openshot-qt -c openshot-qt`

![screenshot from 2019-02-17 23-35-43](https://user-images.githubusercontent.com/91113/52920457-cccb2400-330c-11e9-9f57-a6eea6bb9afa.png)

---

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.98, NixOS, 18.09.2137.168cbb39691 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(davidak): `""`
 - channels(root): `"nixos-18.09.2137.168cbb39691, nixos-hardware, nixos-unstable-19.03pre169108.36f31600749"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by peti** [comment] 2019-09-03 15:48
I believe this problem has been fixed a while ago. I cannot reproduce it either. Please ping me if anyone still has this issue on `master`.

**Closed by peti** 2019-09-03 15:48 UTC
