### ISSUE TITLE
Add one line xkb config to add hyper to the keymap

### ISSUE THREAD

**Issue by IvanMalison** [NixOS/nixpkgs#130594] opened 2021-07-19 02:53 UTC
It would be really cool, if there were one line nixos configs that would make e.g. the right super/win key behave as a hyper key. A template for how this might be done can be found here: https://gist.github.com/toroidal-code/ec075dd05a23a8fb8af0

I'm not sure I know enough about nixos/Xorg internals to make this work properly though.

**Comment by rnhmjoj** [comment] 2021-07-19 07:33
By looking at the source of XKB, Hyper does not seem to be a real keycode, so it can't be simply mapped from the hwdb. You have to make a simple XKB layout to swap the keys. It's actually pretty easy on NixOS:

```nix
{
  services.xserver = {
    enable = true;
    layout = "hyper";

    extraLayouts.hyper = {
      description = "Standard US layout with hyper key";
      languages = [ "eng" ];
      symbolsFile = pkgs.writeText "hyper" ''
        partial modifier_keys
        xkb_symbols "hyper" {
          include "us(basic)"
          key <RALT> { [ Hyper_R ] };
          modifier_map Mod3 { <HYPR>, Hyper_R };
        };
      '';
    };

  };

}
```

**Comment by rnhmjoj** [comment] 2021-07-19 08:19
If you add a `console.useXkbConfig = true;` it should also work in a Linux vt.

**Comment by IvanMalison** [comment] 2021-07-20 04:39
@rnhmjoj hmmm this caused a crazy amount of recompilation for me, and then did not even seem to work properly.

XKB is an annoying and confusing beast...

**Comment by rnhmjoj** [comment] 2021-07-20 06:30
That's expected: unfortunately It's not possible to install an arbitrary layout without at least recompiling these packages: `setxkbmap`, `xkbcomp`, `xorgserver`.

How did you test it? If I built a VM with this configuration and pressing right alt in `xev` shows correctly the key is sending `Hyper_R`.

**Comment by IvanMalison** [comment] 2021-07-21 02:28
> That's expected: unfortunately It's not possible to install an arbitrary layout without at least recompiling these packages: `setxkbmap`, `xkbcomp`, `xorgserver`.

Why do they need to be recompiled though. The current solution that I use is to use this script:
https://github.com/IvanMalison/dotfiles/blob/bb080a73179eb7d645dc068317fa4ea122475de6/dotfiles/lib/bin/load_xkb_map.sh

together with the symbols and keymaps files here: https://github.com/IvanMalison/dotfiles/tree/master/dotfiles/xkb

That essentially amounts to an invocation of xkbcomp which ends up doing what I want `xkbcomp -I"$XKBDIR" "$XKBMAPFILE" "${DISPLAY%%.*}"`

Is there really not a way to do something equivalent by changing a configuration file somewhere?

> How did you test it? I built a VM with this configuration and pressing right alt in xev shows correctly the key is sending Hyper_R.

Yeah, so the change does work, I just wasn't paying attention and wanted an rwin change (not an ralt change), which is what your example configuration provided. When I switched it to be an rwin change it worked as expected.

**Comment by rnhmjoj** [comment] 2021-07-21 06:29
> That essentially amounts to an invocation of xkbcomp which ends up doing what I want xkbcomp -I"$XKBDIR" "$XKBMAPFILE" "${DISPLAY%%.*}"

Changes to the layout done using `setxkbmap` or `xkbcomp` are lost if you unplug the keyboard or restart the X server.
There is no way to make them permanent: you must run the command with a timer or maybe by listening to udev events, which is quite complicated.

> Is there really not a way to do something equivalent by changing a configuration file somewhere?

No, there is no configuration file for XKB layouts: it's not something that can be changed at runtime.

The layouts are defined by the `xkeyboard_config` package and adding a new one requires editing a couple of files manually and then rebuilding the package.
Since most X11 programs are configured at build time with something like `--with-xkb-path=${xkeyboard_config}/share/X11/xkb`, overriding `xkeyboard_config` forces a huge recompilation. The `extraLayouts` module is already minimising the amount of recompilation by only replacing XKB in the programs that are actually involved in setting a layout, those I mentioned before.

To be fair, recently XKB added a mean to include a custom layout without rebuilding the package, but this is limited to a single `symbols` file and doesn't work for variants, which is the case of `hyper`. See https://github.com/NixOS/nixpkgs/issues/117657

I think it could be possible to point all X11 programs to `/etc/X11/xkb` and link the output of `xkeyboard_config` there. This would save all the recompilations, but it will likely break the desktop on non-NixOS system entirely.

**Comment by IvanMalison** [comment] 2021-07-25 19:25
@rnhmjoj Okay, I understand what you are saying, but this seems insanely stupid to me. It seems like it should be possible to configure the packages to point them at a different xkeyboardconfig without recompiling them.

I'm assuming that the need for "recompilation" is not because the binaries are actually subtantively in any way different, just that they need to be pointed at different directories.

I suppose that when you're not in NixOS land you can just go edit /share/X11/xkb manually so perhaps upstream does not see it as much of an issue for that reason?




> I think it could be possible to point all X11 programs to `/etc/X11/xkb` and link the output of `xkeyboard_config` there. This would save all the recompilations, but it will likely break the desktop on non-NixOS system entirely.

Seems like it should be possible then to have a "special" version of the X11 programs (which is still available in the Nix cache), just for the purposes of NixOS.

**Comment by rnhmjoj** [comment] 2021-07-30 07:24
> I'm assuming that the need for "recompilation" is not because the binaries are actually subtantively in any way different, just that they need to be pointed at different directories.

Yes,  the problem is that the path is hardcoded into the program once built and can't be easily changed.

> I suppose that when you're not in NixOS land you can just go edit /share/X11/xkb manually so perhaps upstream does not see it as much of an issue for that reason?

Well, actually it's pretty inconvenient on other distros too: you must have root access and your changes are likely overwritten in a major system update. I think people editing their keyboard layouts are just not that common for the X developers to spend time simplifying this workflow.

> Seems like it should be possible then to have a "special" version of the X11 programs (which is still available in the Nix cache), just for the purposes of NixOS.

An idea could be to patch the necessary programs (xkbcomp, xserver, etc.) to look for a particular directory first, say /etc/X11/nixos-xkb, and fallback to the hardcoded /nix/store/...-xkeyboard-config otherwise. This should make sure the programs continue to work outside of NixOS.

**Comment by rnhmjoj** [comment] 2021-09-22 08:06
FYI since #138207 we don't need to rebuild anymore. I closing this issue, but feel free to reopen if you have more troubles.

**Closed by rnhmjoj** 2021-09-22 08:06 UTC
Labels: 6.topic: nixos, 0.kind: packaging request
