### ISSUE TITLE
nixos/tests/k3s: can't run tests: error: 'k3s_1_24' has been removed from nixpkgs as it has reached end of life

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#302883] opened 2024-04-09 17:21 UTC
### Describe the bug

```sh
❯ nix-build default.nix -A multi-node
error:
       … while evaluating the 'name' attribute of a derivation

         at «none»:0: (source not available)

       … while evaluating the attribute 'value'

         at /home/bbigras/src/nixpkgs/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: 'k3s_1_24' has been removed from nixpkgs as it has reached end of life
❯ nix-build default.nix -A single-node
error:
       … while evaluating the 'name' attribute of a derivation

         at «none»:0: (source not available)

       … while evaluating the attribute 'value'

         at /home/bbigras/src/nixpkgs/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: 'k3s_1_24' has been removed from nixpkgs as it has reached end of life
```

### Steps To Reproduce
1. cd nixpkgs/nixos/tests/k3s
2. `nix-build default.nix -A single-node` or `nix-build default.nix -A multi-node`

### Expected behavior

success

### Notify maintainers

@euank @mic92 @superherointj @yajo

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.2, NixOS, 24.05 (Uakari), 24.05.20240406.ff0dbd9`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `not found`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by superherointj** [comment] 2024-04-09 18:18
https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/networking/cluster/k3s

**Comment by superherointj** [comment] 2024-04-09 18:30
I was able to reproduce the problem you mention.

We don't have that problem because we run tests as:
> nix build .#k3s.passthru.tests.single-node .#k3s.passthru.tests.multi-node .#k3s.passthru.tests.etcd

**Comment by superherointj** [comment] 2024-04-09 18:39
I suspect `nix-build` is using some extraneous old nixpkgs version that has `k3s` pointing out to `k3s_1_24` still.
So you get this mismatch from your system and nixpkgs.

**Comment by superherointj** [comment] 2024-04-09 21:19
@bbigras Can I close this?

**Closed** 2024-04-09 22:27 UTC
Labels: 9.needs: reporter feedback

**Comment by superherointj** [comment] 2024-04-23 09:12
@bbigras Did you have any other fix in mind for this?
