### ISSUE TITLE
Bottles: Can't switch from "Library" to "Bottles" tab because `ca.desrt.dconf` dbus service is missing

### ISSUE THREAD

**Issue by deftdawg** [NixOS/nixpkgs#270565] opened 2023-11-28 06:03 UTC
### Describe the bug
Attempting to switch from `Library` tab to `Bottles` fails.

When run in a terminal, each attempt to switch produces the following terminal output complaining about missing `ca.desrt.dconf` service:
```
(bottles:275578): dconf-WARNING **: 00:52:01.982: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by any .service files
```

### Steps To Reproduce
1. Install "bottles"
2. Open "bottles"
3. `Create a new bottle`  while on the `Library` tab
4. Try to switch to the `Bottles` tab to use your new bottle, the tab will flash your bottles and immediately switch back to `Library`

### Expected behavior
Expected behaviour is the application's tab switches and you can run your bottles

### Notify maintainers
@psydvl @shamilton 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.2, NixOS, 24.05 (Uakari), 24.05pre552293.5a09cb4b393d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - channels(deftdawg): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment] 2023-11-28 08:33
The thread below suggests this issue can (& should) be fixed with the option `programs.dconf.enable` to your system `configuration.nix`.

https://github.com/nix-community/home-manager/issues/3113

**Comment by chewblacka** [comment] 2023-11-28 19:56
> Ideally from a user experience standpoint `guess if you need an option and which one` kinda sucks. It would be better if dependant options could automatically be enabled or if wrappers could pop-up warnings prior to the program running that a dependency/option wasn't configured.

I agree that there needs to be a way to communicate extra information from the package maintainer to the end user. However I don't think this can be done programmatically as you have to also cater for non-NixOS usage of nix packages. In this case on non-NixOS there is no option to be set, rather the user has to make sure that dconf is installed on their host OS. Also it's not always easy to check programmatically whether an option exists / is set etc. 

The only universal solution I can think of is an Arch style wiki, where each nix package gets it's own entry which contains extra information about the settings / other packages needed in order for the package to work as intended. What do you think?

**Comment by deftdawg** [comment] 2023-11-29 04:39
> I 100% agree that there needs to be a way to communicate extra information from the package maintainer to the end user. However I don't think this can be done programmatically as you have to also cater for non-NixOS usage of nix packages. In this case on non-NixOS there is no option to be set, rather the user has to make sure that dconf is installed on their host OS. Also it's not always easy to check programmatically whether an option exists / is set etc.

I'm not convinced writing run-time dependency checks is that hard, perhaps I'm underthinking it... My feeling is writing the wrappers that make Nix packages run with everything in /nix/store is quite a bit harder, it's more a problem of not knowing what checks are required until someone hits a problem with a dependency being missing.

> The only universal solution I can think of is an Arch style wiki, where each nix package gets it's own entry which contains extra information about the settings / other packages needed etc. in order for the package to work as intended. What do you think?

Additional notes on the nix-package search page would potentially be helpful, but it still requires the user to go hunt it down.   

Better would be to modify the wrapper when their's a known dependency such as in this case (or as I discovered earlier this year KDE Partition Manager requiring `programs.partition-manager.enable = true;` in [order to open](https://github.com/NixOS/nixpkgs/issues/196280)) to open a popup that get's the user's attention advising them of a runtime problem.  This can potentially bring the solution to the user rather then asking them go hunt..  That could even be your wiki idea if it's a complex issue.

Bottles wrapper is written in python, but if we were to pretend it was a shell script for a second... 

1. Incorporate a utility like [script-dialog](https://github.com/deftdawg/script-dialog) into the OS (I didn't write it, just patched it for bash location)
2. When a wrapper is invoked to start the program, check something like this and notify the user of an issue and fix:

```sh
# Check the runtime requirement
dbus-send --session --dest=ca.desrt.dconf --type=method_call --print-reply /ca/desrt/dconf org.freedesktop.DBus.Introspectable.Introspect >/dev/null || (
  # Failed, now pop-up a dialog telling the user what the issue is so they can go fix it
  APP_NAME="Bottles wrapper"
  WINDOW_ICON=$(standardIconError)
  [ -f /etc/NIXOS ] \ 
    && messagebox "Error: 'ca.desrt.dconf' dbus service is missing - On NixOS 'programs.dconf.enable = true;' must be applied to your configuration.nix" \
    || messagebox "Error: 'ca.desrt.dconf' dbus service is missing - please insure dbus service 'ca.desrt.dconf' is installed and running then try again."
  fi
  # exit?
)
...
# do wrapper stuff
# run bottles binary
```

**Comment by SuperSamus** [comment] 2023-11-30 11:19
`programs.dconf.enable` is enabled by default on almost every desktop environment.
I say "almost" because it isn't enabled on Plasma for some reason #266234.

**Closed** 2023-12-04 21:21 UTC
Labels: 0.kind: bug

**Comment by bernadinm** [comment] 2024-05-24 21:50
Should this configuration be in bottles or at least error mentioning that this is required for this to be installed on nixos?

**Comment by SuperSamus** [comment] 2024-05-24 22:13
It is impossible to assert this in a package.

Something that could be done is to create an option `programs.bottle.enable` that also enables Dconf[^1], but:
- It would be overkill (IMO), since enabling Dconf would be (almost) the _only_ thing it does, and it is very likely to be enabled already.
- Nothing can "force" the user to use the option instead of the package directly (see #222431).

[^1]: And install vkBasalt, currently the toggle for it is always visible, but it doesn't do anything if it isn't installed in `environment.systemPackages`.

**Comment by FERNANDOHYDE** [comment] 2024-07-27 18:47
Ran into this issue as well running wayland/plasma and adding 'programs.dconf.enable = true;' to my config did not fix the issue. I am still getting the same error as OP in bottles.
