### ISSUE TITLE
sioyek not starting with `Could not Initialize GLX`

### ISSUE THREAD

**Issue by pretentious7** [NixOS/nixpkgs#197647] opened 2022-10-25 02:48 UTC
### Describe the bug
 sioyek fails with the following error:
```console
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

(process:65354): Gtk-WARNING **: 22:42:24.574: Locale not supported by C library.
	Using the fallback 'C' locale.
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 3.3, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::CoreProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 3.3, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::CoreProfile)
Could not initialize GLX
Aborted
```

### Steps To Reproduce
In terminal:
1. nix-shell -p sioyek
2. sioyek
3. 

### Expected behavior
I expect sioyek to start in a new window

### Additional context
I've checked that the appimage behaves as expected.

### Notify maintainers
@podocarp 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/q1drpnp5qifc38akiv4r169ll7cizisp-nix-info
copying path '/nix/store/q1drpnp5qifc38akiv4r169ll7cizisp-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.0-rc7-amd64, Debian GNU/Linux, 11 (bullseye), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(abhishek): `"nixpkgs-22.11pre417468.31d56784625"`
 - nixpkgs: `/home/abhishek/.nix-defexpr/channels/nixpkgs`

```

**Comment by alex-fu27** [comment] 2022-10-25 09:03
@podocarp might this be caused by #197695 ?

**Comment by NickCao** [comment] 2022-10-25 09:18
Maybe https://github.com/guibou/nixGL would help.

**Comment by pretentious7** [comment] 2022-10-25 16:10
> Maybe https://github.com/guibou/nixGL would help.

O that looks promising, I'll give it a try tonight.

**Comment by Artturin** [comment] 2022-10-25 16:28
dupe of https://github.com/NixOS/nixpkgs/issues/82959

**Closed by Artturin** 2022-10-25 16:28 UTC
Labels: 0.kind: bug, 6.topic: non-nixos
