### ISSUE TITLE
Slack crashes with NIXOS_OZONE_WL=1 enabled

### ISSUE THREAD

**Issue by tuxinaut** [NixOS/nixpkgs#180678] opened 2022-07-08 09:31 UTC
### Describe the bug

`Slack` crashes with `NIXOS_OZONE_WL=1` option activated

### Steps To Reproduce

1. Start slack with option `NIXOS_OZONE_WL=1`
1. Start a call
1. Start screensharing and select a desktop
1. Slack crashes with `libwayland: xdg_surface@78: error 3: xdg_surface has never been configured`

### Expected behavior

Screensharing starts.

### Additional context

Log output

```
[07/08/22, 11:11:25:093] info: [SCREENS] (T8MMQ651A) Available screens:
-- | ----- | ------ | - | - | ----------- | --------
id | width | height | x | y | scaleFactor | rotation
-- | ----- | ------ | - | - | ----------- | --------
41 | 1920  | 1080   | 0 | 0 | 1           | 0
43 | 2560  | 1440   | 0 | 0 | 1           | 0

[07/08/22, 11:11:25:260] error: SCREENS (T8MMQ651A) Could not find matching display for screen 0 with id
[07/08/22, 11:11:25:266] error: SCREENS (T8MMQ651A) Could not find matching display for screen 1 with id
[07/08/22, 11:11:25:298] warn: (T8MMQ651A) No toast queue found for team T8MMQ651A
[07/08/22, 11:11:25:300] warn: (T8MMQ651A) No toast queue found for team T8MMQ651A
[07/08/22, 11:11:25:516] error: SCREENS (T8MMQ651A) Could not find matching display for screen 0 with id
[07/08/22, 11:11:25:518] error: SCREENS (T8MMQ651A) Could not find matching display for screen 1 with id
[07/08/22, 11:11:26:015] info: [API-Q] (T8MMQ651A) 16362376-1657271485.974 users.interactions.list called with reason: huddle-discovery-calls
[07/08/22, 11:11:26:015] info: [API-Q] (T8MMQ651A) 16362376-1657271485.974 users.interactions.list is ENQUEUED
[07/08/22, 11:11:26:015] info: [API-Q] (T8MMQ651A) 16362376-1657271485.974 users.interactions.list is ACTIVE
[07/08/22, 11:11:26:016] error: SCREENS (T8MMQ651A) Could not find matching display for screen 0 with id
[07/08/22, 11:11:26:017] error: SCREENS (T8MMQ651A) Could not find matching display for screen 1 with id
[07/08/22, 11:11:26:163] info: [API-Q] (T8MMQ651A) 16362376-1657271485.974 users.interactions.list is RESOLVED
[07/08/22, 11:11:26:461] info: [FREE-WILLY-SDK] (T8MMQ651A) API/DefaultAudioVideoFacade/d0f3f13a-bcd5-433f-8bcb-24c5e7120706/bfee086f-de20-7ffb-a39b-1cda5fd710cb/getRTCPeerConnectionStats null
[07/08/22, 11:11:27:263] info: [RTM] (T8MMQ651A) Processed 1 recent_status_changed event(s) over 60.30ms
[07/08/22, 11:11:27:265] info: [RTM] Setting a timeout of 34 ms to process more rtm events
[07/08/22, 11:11:27:300] info: [RTM] Waited 34 ms, processing more rtm events now
[07/08/22, 11:11:28:461] info: [FREE-WILLY-SDK] (T8MMQ651A) API/DefaultAudioVideoFacade/d0f3f13a-bcd5-433f-8bcb-24c5e7120706/bfee086f-de20-7ffb-a39b-1cda5fd710cb/getRTCPeerConnectionStats null
[07/08/22, 11:11:28:988] info: [(?)] Screenshare start: screen-picker, screenId = screen:424:0, zoomLevel = 0
[07/08/22, 11:11:29:008] info: [FREE-WILLY-SDK] (T8MMQ651A) API/DefaultAudioVideoFacade/d0f3f13a-bcd5-433f-8bcb-24c5e7120706/bfee086f-de20-7ffb-a39b-1cda5fd710cb/realtimeSendDataMessage
[07/08/22, 11:11:29:009] info: [FREE-WILLY-SDK] (T8MMQ651A) API/DefaultAudioVideoFacade/d0f3f13a-bcd5-433f-8bcb-24c5e7120706/bfee086f-de20-7ffb-a39b-1cda5fd710cb/chooseVideoInputDevice null
[07/08/22, 11:11:29:009] info: [FREE-WILLY-SDK] (T8MMQ651A) video send has ideal max bandwidth 1400 kbps
[07/08/22, 11:11:29:010] info: [FREE-WILLY-CONTENT-SH] (T8MMQ651A) Starting screen share with zoomLevel = 0
[07/08/22, 11:11:29:011] info: [FREE-WILLY-CONTENT-SH] (T8MMQ651A) Starting unconstrained content share with chime API's startContentShareFromScreenCapture
[07/08/22, 11:11:29:011] info: [FREE-WILLY-SDK] (T8MMQ651A) API/DefaultAudioVideoFacade/d0f3f13a-bcd5-433f-8bcb-24c5e7120706/bfee086f-de20-7ffb-a39b-1cda5fd710cb/setContentAudioProfile {"audioBitrateBps":128000}
[07/08/22, 11:11:29:012] info: [FREE-WILLY-SDK] (T8MMQ651A) API/DefaultAudioVideoFacade/d0f3f13a-bcd5-433f-8bcb-24c5e7120706/bfee086f-de20-7ffb-a39b-1cda5fd710cb/startContentShareFromScreenCapture
[07/08/22, 11:11:29:028] info: [FREE-WILLY-SDK] (T8MMQ651A) API/DefaultDeviceController/chooseVideoInputDevice null
[07/08/22, 11:11:29:029] info: [FREE-WILLY-SDK] (T8MMQ651A) API/DefaultAudioVideoFacade/d0f3f13a-bcd5-433f-8bcb-24c5e7120706/bfee086f-de20-7ffb-a39b-1cda5fd710cb/stopLocalVideoTile
[144006:0708/111129.079496:ERROR:wayland_event_watcher.cc(25)] libwayland: xdg_surface@78: error 3: xdg_surface has never been configured

Trace/breakpoint trap (core dumped)
```

Even if Slack is started with this command it crashes.

`slack --ozone-platform=wayland --enable-features=UseOzonePlatform,WebRTCPipeWireCapture`

### Notify maintainers

@mmahut 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.50, NixOS, 22.05 (Quokka), 22.05.1490.316b762afdb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(dschaefer): `"home-manager-22.05.tar.gz"`
 - channels(root): `"nixos-22.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by tuxinaut** [comment] 2022-08-25 13:29
I just tested it again with the following command and what should I write... it now works as expected and is stable :tada:

`slack --enable-features=WebRTCPipeWireCapturer %U`

`Home Manager` overlay to make it more convenient.

```
  nixpkgs.overlays = [(
    self: super: {
      slack  = super.slack.overrideAttrs (old: {
        installPhase = old.installPhase + ''
          rm $out/bin/slack

          makeWrapper $out/lib/slack/slack $out/bin/slack \
          --prefix XDG_DATA_DIRS : $GSETTINGS_SCHEMAS_PATH \
          --prefix PATH : ${lib.makeBinPath [pkgs.xdg-utils]} \
          --add-flags "--enable-features=WebRTCPipeWireCapturer %U"
        '';
      });
    };
  )];
```

**Comment by SebTM** [comment] 2023-01-26 03:23
I've came across the issue yesterday and made a PR for it, also I can't reproduce the problem issue of this issue anymore so when merged I would like to going forward, closing this? :)

**Closed** 2023-03-01 10:06 UTC
Labels: 0.kind: bug
