### ISSUE TITLE
Android: SDK Tools is deprecated. Switch to cmdline-tools instead

### ISSUE THREAD

**Issue by kjeremy** [NixOS/nixpkgs#169634] opened 2022-04-21 20:59 UTC
Android SDK Tools have been deprecated for a while: https://developer.android.com/studio/releases/sdk-tools

`androidEnv.composeAndroidPackages` should migrate to using the `cmdline-tools` package for the latest in Android development. This should also fix `flutter doctor` not finding the Android tools.

@miallo
@SuperSandro2000
@numinit

**Comment by SuperSandro2000** [comment] 2022-04-21 23:40
I don't remember being a maintainer for this. I would appreciate if I don't get pinged for random packages which I merged PRs for or changed one little thing a while back and the issue is unrelated to this.

**Comment by kjeremy** [comment] 2022-04-22 02:54
Sorry I used git blame and didn't realize that you had just merged in a PR.

**Comment by axelkar** [comment] 2024-01-09 17:19
Is this still applicable? I can see references of `cmdline-tools` in `androidenv`.
https://github.com/NixOS/nixpkgs/blob/f7be52b7fc55a487d406031cbd55218e69ea490e/doc/languages-frameworks/android.section.md?plain=1#L46-L49

**Comment by numinit** [comment] 2024-01-10 02:01
This is OBE.

**Closed by numinit** 2024-01-10 02:01 UTC
Labels: 0.kind: bug
