### ISSUE TITLE
$NIX_GHC_DOCDIR points to non-existent directory

### ISSUE THREAD

**Issue by ParetoOptimalDev** [NixOS/nixpkgs#214204] opened 2023-02-02 16:09 UTC
### Describe the bug

related to  #150968 and found while writing  a feature request for haskell language server support for local nix documentation in haskell/haskell-language-server#3475

### Steps To Reproduce
1. `git clone https://github.com/ParetoOptimalDev/apecs-shmup-example.git`
2. `cd apecs-shmup-example`
3. `nix develop -c bash -c "ls $NIX_GHC_DOCDIR"`

Get:

```
ls: cannot access '/nix/store/0g44g3x3qc5rpmr8n1m4bldl0fwlc4z0-ghc-9.2.4-with-packages/share/doc/ghc/html': No such file or directory
```

### Expected behavior

It returns the correct directory which seems to be different for each package and not nested anywhere, e.g. apecs:

```
/nix/store/pmyb1ayz7vxlmim1bd12sjpss3s7pddy-apecs-0.9.4-doc/share/doc/apecs-0.9.4/html/src/Apecs.Util.html
```

### Additional context

The reason for wanting this is to simplify implementing hover links in haskell language server being able to link to local nix generated hackage docs and source as in feature request haskell/haskell-language-server#3475

### Notify maintainers

@maralorn @sternenseemann @KAction @cdepillabout @expipiplus1 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by sternenseemann** [comment] 2023-02-02 16:50
Duplicate of #150666, fixed in #210762.

**Closed by sternenseemann** 2023-02-02 16:50 UTC
Labels: 0.kind: bug
