### ISSUE TITLE
buildInputs of python3.4 broken by commit

### ISSUE THREAD

**Issue by codyopel** [NixOS/nixpkgs#12300] opened 2016-01-10 16:12 UTC
a7f478a3685248ff4238991c8fededa63227d6af

needs 'buildInputs = buildInputs ++ other inputs'

**Comment by domenkozar** [comment] 2016-01-10 16:44
@codyopel can you explain what's wrong exactly, how to reproduce?

**Comment by codyopel** [comment] 2016-01-10 17:05
buildInputs is being defined twice, so the first instance is ignored, the lists need to be combined like my previous example.  see "let ... in" for the ignored buildInputs

**Comment by copumpkin** [comment] 2016-01-10 17:06
@codyopel good point. I'm trying to understand how it worked before that commit though. I didn't see any `inherit buildInputs` before!

**Comment by FRidh** [comment] 2016-01-10 20:29
@copumpkin because they're called in `configureFlagsArray` and are therefore present at build time, at least that's what I think.

**Comment by garbas** [comment] 2016-05-14 20:56
@codyopel could you provide a command that breaks for you and on which platorm? all python versions build fine for me.

**Comment by FRidh** [comment] 2016-10-11 15:12
This was fixed in #15477.

**Closed by FRidh** 2016-10-11 15:12 UTC
Labels: 6.topic: python
