### ISSUE TITLE
Build failure: ripgrep-all-0.9.6_fish-completions

### ISSUE THREAD

**Issue by ionutnechita** [NixOS/nixpkgs#250373] opened 2023-08-20 15:33 UTC
building the system configuration...
error: builder for '/nix/store/md5x85n2jdc3rxxi8i8nbb63g3qvp866-ripgrep-all-0.9.6.drv' failed with exit code 1;
       last 25 log lines:
       > adapter: zip
       > adapter: tar
       > adapter: poppler
       > adapter: poppler
       > adapter: zip
       > adapter: poppler
       > adapter: pandoc
       > Unknown option --atx-headers.
       > Try pandoc --help for more information.
       > Error: Broken pipe (os error 32)
       > -------------------------------------------------------------------------------
       > exampledir/tar/test.tar.bz2: preprocessor command failed: '"/nix/store/z8d0i9krp1f48sgvyzki48sd8bv2dkpj-ripgrep-all-0.9.6/bin/rga-preproc" "exampledir/tar/test.tar.bz2"':
       > -------------------------------------------------------------------------------
       > adapter: decompress
       > adapter: tar
       > adapter: poppler
       > adapter: poppler
       > adapter: zip
       > adapter: poppler
       > adapter: pandoc
       > Unknown option --atx-headers.
       > Try pandoc --help for more information.
       > Error: Broken pipe (os error 32)
       > -------------------------------------------------------------------------------
       > ERROR: test1 failed! Could not find the word 'hello' 26 times in the sample data.
       For full logs, run 'nix log /nix/store/md5x85n2jdc3rxxi8i8nbb63g3qvp866-ripgrep-all-0.9.6.drv'.
error: 1 dependencies of derivation '/nix/store/41qsd7h5x8fa1cxyfmr7cdk2lg7nranq-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/p3r52w6xd91g638clpf5rx2n6kg0566i-ripgrep-all-0.9.6_fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1fkflds02l0hk8vwjgdnrwrj0r3h8lmh-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ffh8wc8hhkiv1gcqgvxw3i7dnn6f6alv-nixos-system-23.11.19700101.dirty.drv' failed to build

**Comment by amrsoll** [comment] 2023-09-03 10:02
Possible duplicate of #250306

**Comment by eclairevoyant** [comment] 2023-09-03 14:24
duplicate

**Closed by eclairevoyant** 2023-09-03 14:24 UTC
Labels: 0.kind: build failure
