### ISSUE TITLE
Problem during build with home-manager.users.kcynk.programs.wezterm.enable = true;

### ISSUE THREAD

**Issue by KCynk** [NixOS/nixpkgs#334875] opened 2024-08-15 14:44 UTC
### Describe the bug
Problem during build with home-manager.users.kcynk.programs.wezterm.enable = true;
Today after rebuild wezterm can't be compiled and build will fail

**Comment by celesteornato** [comment] 2024-08-15 14:59
Seconding the issue, wezterm currently cannot compile on nixos-unstable.  This is presumably due to Rust Stable 1.80 not being able to compile the code anymore.

**Comment by dotlambda** [comment] 2024-08-15 15:09
duplicate of https://github.com/NixOS/nixpkgs/issues/334650

**Closed by dotlambda** 2024-08-15 15:09 UTC
Labels: 0.kind: bug
