### ISSUE TITLE
`vterm` crashes Emacs if compiled with `imagemagick = unstable.imagemagickBig`

### ISSUE THREAD

**Issue by matthew-piziak** [NixOS/nixpkgs#66295] opened 2019-08-07 20:23 UTC
**Describe the bug**

On 19.03, `emacs-libvterm` crashes Emacs upon invoking `(require 'vterm)`. No reports are dumped to `.xsession-errors`.

**To Reproduce**
1. On 19.03, install `emacs.emacsWithPackages(p: with p; [ emacs-libvterm ])`
2. Open Emacs
3. Run `M-: (require 'vterm)`
4. Note that Emacs hard crashes immediately.

**Attempted workaround**

I tried installing a newer version of the package…
```
{ config, pkgs, ... }:
let
  vterm-src = pkgs.fetchFromGitHub {
    owner = "akermu";
    repo = "emacs-libvterm";
    rev = "99511023cfc5bb524e157914fe943ca450b89942";
    sha256 = "136h31bkdiqsdm6vgkb4566qzh090cgikjnny47gwqy6xyz5w2c0";
  };
  emacs-custom = (pkgs.stable1903.emacs.override {
    imagemagick = pkgs.unstable.imagemagickBig;
    srcRepo = true;
    withXwidgets = true;
  }).overrideAttrs (old: rec {
    name = "emacs-${version}${versionModifier}";
    version = "27.0.50";
    versionModifier = "-git";
    src = pkgs.fetchFromGitHub {
      owner = "emacs-mirror";
      repo = "emacs";
      rev = "0a5212b99666b9ba0543a62cdbb12ee0685820f3";
      sha256 = "038kasdll0332vdpyc29xlkdj801sivz3ssnyz0dqr3gcavpk5yv";
    };
    patches = [ ];
  });
  emacs-overrides = (self: super: rec {
    emacs-libvterm = super.emacs-libvterm.overrideAttrs (attrs: {
      src = vterm-src;
      buildInputs = attrs.buildInputs ++ (with pkgs; [ git curl ]);
    });
  });
  custom-emacs =
    ((pkgs.stable1903.emacsPackagesNgGen emacs-custom).overrideScope'
    emacs-overrides);
  custom-emacs-and-packages = custom-emacs.emacsWithPackages
    (p: with p; [ pdf-tools proof-general emacs-libvterm ]);
in {
  environment.systemPackages = [ custom-emacs-and-packages ];
}
```
…but the installation failed with `git clone` errors:
```
[ 16%] Performing download step (git clone) for 'libvterm'
Cloning into 'libvterm'...
fatal: unable to access 'https://github.com/neovim/libvterm.git/': Could not resolve host: github.com
Cloning into 'libvterm'...
fatal: unable to access 'https://github.com/neovim/libvterm.git/': Could not resolve host: github.com
Cloning into 'libvterm'...
fatal: unable to access 'https://github.com/neovim/libvterm.git/': Could not resolve host: github.com
-- Had to git clone more than once:
          3 times.
CMake Error at /build/source/build/libvterm-prefix/tmp/libvterm-gitclone.cmake:66 (message):
  Failed to clone repository: 'https://github.com/neovim/libvterm.git'
```

I know I'm doing something wrong here but I don't know what.

**Comment by adisbladis** [comment] 2019-08-07 20:38
I cannot reproduce on 19.03. It probably have something to do with your overrides.

**Comment by matthew-piziak** [comment] 2019-08-14 04:51
I just went and recompiled `unstable.emacs` with no overrides and `unstable.vterm` (the new name for `emacs-libvterm`). Still, **boom**, Emacs crashes immediately upon calling `(require 'vterm)`.

**Comment by matthew-piziak** [comment] 2019-08-14 04:55
I just went and recompiled `unstable.emacs` with no overrides and `unstable.vterm` (the new name for `emacs-libvterm`). Still, **boom**, Emacs crashes immediately upon calling `(require 'vterm)`.

**Comment by matthew-piziak** [comment] 2019-08-14 23:58
I have narrowed this down to `imagemagick`.

If you configure `emacs` with `imagemagick = pkgs.unstable.imagemagickBig`, `vterm` crashes Emacs.

**Comment by akermu** [comment] 2019-08-16 17:30
Do yo have a backtrace? Maybe I can tell you what went wrong?

**Comment by matthew-piziak** [comment] 2019-08-16 20:49
@akermu No Emacs backtrace (since it crashes) and no errors in `~/.xsession`. I'll have to test it out with `gdb`. Anyone know how to compile Emacs with debug flags on NixOS?

**Comment by matthew-piziak** [comment] 2019-08-17 02:35
I compiled with `imagemagick = pkgs.unstable.imagemagickBig;` and `CFLAGS = attrs.CFLAGS + " " + "-ggdb3 -O0";`, but then I ran `gdb emacs` and got `No executable file specified`. Where does Emacs put core dumps?

**Comment by acowley** [comment] 2020-05-08 05:02
I'm seeing this, too. I don't have time to debug it, but `gdb` is indeed suggesting something bad happening in GhostScript.

```
Thread 1 ".emacs-28.0.50-" received signal SIGSEGV, Segmentation fault.
0x00007f088238fc5b in codepoint_to_utf8 ()
   from /nix/store/gaxsyaalmnj1il2j24grvg8kr24fi0sg-ghostscript-9.50/lib/libgs.so.9
(gdb) bt
#0  0x00007f088238fc5b in codepoint_to_utf8 ()
   from /nix/store/gaxsyaalmnj1il2j24grvg8kr24fi0sg-ghostscript-9.50/lib/libgs.so.9
#1  0x00007f0871df8d79 in refresh_lines ()
   from /nix/store/2byhxklvci4wfcpfalp6x324xhg0wg2b-emacs-packages-deps/share/emacs/site-lisp/elpa/vterm-20200418.1610/vterm-module.so                                                                            
#2  0x00007f0871df959e in term_redraw ()
   from /nix/store/2byhxklvci4wfcpfalp6x324xhg0wg2b-emacs-packages-deps/share/emacs/site-lisp/elpa/vterm-20200418.1610/vterm-module.so                                                                            
#3  0x00007f0871df95d8 in Fvterm_redraw ()
   from /nix/store/2byhxklvci4wfcpfalp6x324xhg0wg2b-emacs-packages-deps/share/emacs/site-lisp/elpa/vterm-20200418.1610/vterm-module.so                                                                            
#4  0x00000000005b3cce in funcall_module ()
#5  0x0000000000587407 in Ffuncall ()
#6  0x00000000005c3438 in exec_byte_code ()
#7  0x0000000000587407 in Ffuncall ()
#8  0x00000000005878b2 in Fapply ()
#9  0x00000000005874b3 in Ffuncall ()
#10 0x00000000005c3438 in exec_byte_code ()
#11 0x0000000000587407 in Ffuncall ()
#12 0x000000000058756a in call1 ()
#13 0x00000000005103e6 in timer_check ()
#14 0x00000000005106c5 in readable_events ()
#15 0x00000000005148d7 in get_input_pending ()
#16 0x0000000000514a4f in detect_input_pending_run_timers ()
#17 0x00000000005ce474 in wait_reading_process_output ()
#18 0x0000000000433626 in sit_for ()
#19 0x000000000051841b in read_char ()
#20 0x000000000051894e in read_key_sequence ()
#21 0x000000000051a399 in command_loop_1 ()
#22 0x000000000058679f in internal_condition_case ()
#23 0x000000000050b048 in command_loop_2 ()
#24 0x0000000000586703 in internal_catch ()
#25 0x000000000050afd6 in command_loop ()
#26 0x000000000050e30f in recursive_edit_1 ()
#27 0x000000000050e62d in Frecursive_edit ()
#28 0x0000000000429b6b in main ()
```

**Comment by DamienCassou** [comment] 2020-08-02 12:13
This is an upstream issue: https://github.com/akermu/emacs-libvterm/issues/327. I'm closing this issue. Please reopen if you feel there is something we can do at the Nix level.

**Closed by DamienCassou** 2020-08-02 12:13 UTC
Labels: 0.kind: bug
