### ISSUE TITLE
Packaging request: CoBang

### ISSUE THREAD

**Issue by onny** [NixOS/nixpkgs#149074] opened 2021-12-06 17:19 UTC
**Project description**
CoBang is a native GTK app for scanning and reading QR codes

**Metadata**

* homepage URL: https://github.com/hongquan/CoBang
* source URL: https://github.com/hongquan/CoBang
* license: gpl3
* platforms: linux

**Comment by WolfangAukang** [comment] 2021-12-06 18:07
Some observations:

- Needs `single-version` and `kiss-headers`, and they are not packaged yet.
- As this uses `poetry.masonry.api`for building, it is probable `poetry-core` will give an issue, so `poetry` would be the way to go
- If someone can get this to build with meson, that would be cool. I got issues where it tries to build the flatpack (not necessary), but a patch could solve it.

**Comment by onny** [comment] 2021-12-07 17:06
Sounds really difficult but at least you got some dependencies packaged :) Maybe I could give it a try too

**Comment by WolfangAukang** [comment] 2021-12-07 17:12
> Sounds really difficult but at least you got some dependencies packaged :) Maybe I could give it a try too

If you can somehow package zbar (the Python library), then I think this is done :)

**Comment by WolfangAukang** [comment] 2021-12-08 01:00
FYI, I got the zbar package working. It is not the one from Sourceforge as it doesn't build with Python 3, but there is a repo on Github with the most updated version.

Now, the problem is that I can't get the application to show the camera, as shown here:
![image](https://user-images.githubusercontent.com/8378365/145129651-1225f2b9-1de9-4732-9929-9706ae8dc6ba.png)

**Comment by onny** [comment] 2021-12-08 07:39
Thank you for your work, looks really promising. Could we merge the dependencies already?
The gtksink probably needs more debugging. Maybe environment variables needs to be passed with a wrapper script?

**Comment by WolfangAukang** [comment] 2021-12-08 22:05
> The gtksink probably needs more debugging. Maybe environment variables needs to be passed with a wrapper script?

Good news, the issue with gtksink is that I needed to enable gtkSupport for the GStreamer good plugins. It was a similar case to what happened to the corebird/cawbird package. After enabling it, now it shows the camera.

Did a cleanup of unnecessary packages and threw the PR. If you can test it, I would appreciate it a bunch :)

**Comment by WolfangAukang** [comment] 2022-03-08 01:27
Merged

**Closed by WolfangAukang** 2022-03-08 01:27 UTC
Labels: 0.kind: packaging request
