### ISSUE TITLE
obsidian refuses to upgrade (electron version is EOL)

### ISSUE THREAD

**Issue by gerardbosch** [NixOS/nixpkgs#274666] opened 2023-12-16 08:45 UTC
### Describe the bug

Using `nix profile` can't upgrade `nixpkgs#obsidian`. It seems that depends on a deprecated end-of-life version of `electron`.

This is the error:

```
error: Package ‘electron-25.9.0’ in /nix/store/yxld2qw84ka591fay1xkh5jflbgxjqa1-source/pkgs/development/tools/electron/binary/generic.nix:35 is marked as insecure, refusing to evaluate.


       Known issues:
        - Electron version 25.9.0 is EOL

       You can install it anyway by allowing this package, using the
       following methods:

       a) To temporarily allow all insecure packages, you can use an environment
          variable for a single invocation of the nix tools:

            $ export NIXPKGS_ALLOW_INSECURE=1

          Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
                then pass `--impure` in order to allow use of environment variables.

       b) for `nixos-rebuild` you can add ‘electron-25.9.0’ to
          `nixpkgs.config.permittedInsecurePackages` in the configuration.nix,
          like so:

            {
              nixpkgs.config.permittedInsecurePackages = [
                "electron-25.9.0"
              ];
            }

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
          ‘electron-25.9.0’ to `permittedInsecurePackages` in
          ~/.config/nixpkgs/config.nix, like so:

            {
              permittedInsecurePackages = [
                "electron-25.9.0"
              ];
            }
```

### Steps To Reproduce

```
NIXPKGS_ALLOW_UNFREE=1 nix profile upgrade --impure '.*'
```

Or simply `nix profile upgrade <NUMBER>`

### Expected behavior

Obsidian is upgraded and `nix profile upgrade` return with success.

### Notify maintainers

@sandro-fugro @claudiiii @kashw2 @qbit

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.0-14-generic, Ubuntu, 23.10 (Mantic Minotaur)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(gerard): `"nixgl, nixpkgs-22.05pre337745.e7caea7700d"`
 - nixpkgs: `/home/gerard/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kirillrdy** [comment] 2023-12-16 09:23
duplicate of https://github.com/NixOS/nixpkgs/issues/273611

**Closed** 2023-12-16 10:44 UTC
Labels: 0.kind: bug
