### ISSUE TITLE
qutebrowser - Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by iskyd** [NixOS/nixpkgs#308290] opened 2024-05-01 14:05 UTC
### Describe the bug
Can't run qutebrowser on Ubuntu 22.04 using Wayland

### Steps To Reproduce
```
nix-shell qutebrowser
qutebrowser
```

### Expected behavior
Expect quterbwoser to run correctly

### Notify maintainers
@dotlambda 
@rnhmjoj 
@timd

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.0-28-generic, Ubuntu, 22.04.4 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.20.4`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by rnhmjoj** [comment] 2024-05-01 14:33
Does it start with `nix-shell --pure -p qutebrowser --run qutebrowser`?

**Comment by iskyd** [comment] 2024-05-01 14:58
@rnhmjoj it doens't give any errors but I got no GUI running.

**Comment by iskyd** [comment] 2024-05-01 16:08
Tried with [nixGL](https://github.com/nix-community/nixGL) and it works fine.

**Comment by rnhmjoj** [comment] 2024-05-01 16:15
> Tried with [nixGL](https://github.com/nix-community/nixGL) and it works fine.

With or without `nix-shell --pure`?

On a non-NixOS system I'm afraid you need to use nixGL, unless you disable hardware acceleration entirely.
The canberrak-gtk-module error, though, is probably due to an impurity in your environment, given it disappears when running in `nix-shell --pure`.

**Comment by iskyd** [comment] 2024-05-01 18:19
I'm running it without using 
`nix --extra-experimental-features "nix-command flakes" run --impure github:nix-community/nixGL -- qutebrowser`

Indeed I'm still getting 
`Gtk-Message: 20:16:54.042: Failed to load module "canberra-gtk-module"`
but everything seems to work fine.

I don't know how to run the same thing using --pure

**Comment by rnhmjoj** [comment] 2024-05-01 19:06
> Gtk-Message: 20:16:54.042: Failed to load module "canberra-gtk-module"

Ok, it's not a fatal error, then.

Since the problem is openGL, I'm closing as duplicate of https://github.com/NixOS/nixpkgs/issues/9415.

**Closed by rnhmjoj** 2024-05-01 19:06 UTC
Labels: 0.kind: bug
