### ISSUE TITLE
The `tor-browser-bundle-bin-10.0.17` package fails to install with message: "Assertion failed: size_ < capacity_ (src/libexpr/attr-set.hh: push_back: 54)".

### ISSUE THREAD

**Issue by nothingnesses** [NixOS/nixpkgs#126669] opened 2021-06-12 13:21 UTC
### Description
The `tor-browser-bundle-bin-10.0.17` package fails to install with message: "Assertion failed: size_ < capacity_ (src/libexpr/attr-set.hh: push_back: 54)".

### Reproduction

```
$ nix-env -iA nixpkgs.tor-browser-bundle-bin
```

### Expected behaviour
The package is installed succesfully.

### Actual behaviour
The following messages are outputted:

```
installing 'tor-browser-bundle-bin-10.0.17'
Assertion failed: size_ < capacity_ (src/libexpr/attr-set.hh: push_back: 54)
Aborted
```

### Notify maintainers
@offline @matejc @thoughtpolice @joachifm @hax404 @cap @KarlJoad

### Metadata
```
$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/rmhwi0jcya8f87gzk2jjdwv4hifmmbb4-nix-info
copying path '/nix/store/rmhwi0jcya8f87gzk2jjdwv4hifmmbb4-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.22_1, void, noversion`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.9`
 - channels(a): `"nixpkgs-21.11pre294471.51bb9f3e9ab"`
 - nixpkgs: `/home/a/.nix-defexpr/channels/nixpkgs`

```

**Comment by FliegendeWurst** [comment] 2021-06-17 08:48
Duplicate of #112465
This issue is fixed by NixOS/nix#4634 in Nix 2.3.11+ (you're currently running 2.3.9)

**Closed** 2021-06-18 13:46 UTC
Labels: 0.kind: bug, 2.status: duplicate
