### ISSUE TITLE
openrazer daemon stopped working

### ISSUE THREAD

**Issue by Algram** [NixOS/nixpkgs#92959] opened 2020-07-11 20:01 UTC
**Describe the bug**
The openrazer daemon service can not start on my system

**To Reproduce**
1. `hardware.openrazer.enable = true;`
2. install `razerGenie`
3. Error occurs (see screenshot below)

**Expected behavior**
The openrazer daemon works.

**Screenshots**
![image](https://user-images.githubusercontent.com/5053729/87232773-e10c3700-c3c1-11ea-8d1c-36f1525a0491.png)

**Additional context**
It is also pretty weird that I can not see the razer daemon status with the following command:
![image](https://user-images.githubusercontent.com/5053729/87232786-000ac900-c3c2-11ea-8b88-03827c60f644.png)

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.51, NixOS, 20.09pre234194.8d05772134f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre234194.8d05772134f, nixos-unstable-20.09pre234194.8d05772134f, nixpkgs-20.09pre234236.c87c474b17a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by f4814** [comment] 2020-07-11 22:04
For some reason I can only reproduce the part where `sudo systemctl status openrazer-daemon` does not work.

Razergenie works and there is a running openrazer process for some reason.

I think I have seen a similar error message from razergenie once while packaging it. However it resolved itself before I could investigate further.

#### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.50, NixOS, 20.03.2506.68c599acd58 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2506.68c599acd58, nixcfg"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Algram** [comment] 2020-07-12 07:26
Very weird, it would help tremendously for debugging if I could see the logs of the service and find out why it fails to start. Do you have a suggestion how I might be able to do that if the status command does not work?

**Comment by Algram** [comment] 2020-07-12 07:29
Edit: I think I found something:
![image](https://user-images.githubusercontent.com/5053729/87241309-219b9d00-c422-11ea-8ef1-0f9d84f30e90.png)

**Comment by f4814** [comment] 2020-07-12 09:53
You can kill the running openrazer process and manually start it. This way you might be able to get some debug information.

**Comment by Algram** [comment] 2020-07-12 11:23
Hm it is super suspect, if I manually start the daemon with:
![image](https://user-images.githubusercontent.com/5053729/87245083-cd54e500-c442-11ea-93dd-a3b65f176b6a.png)

It works. If it gets started via nixos it does not.

**Comment by f4814** [comment] 2020-07-12 11:33
CC @roelvandijk @evanjs

**Comment by Algram** [comment] 2020-07-12 13:16
Maybe an update to the latest version of openrazer would help (`2.8.0`). I am currently trying to do that but I am struggling a little with the overlay since I am not very experienced with it.

**Comment by evanjs** [comment] 2020-07-12 17:31
OpenRazer is a user service IIRC. 

Can you see if `systemctl status --user openrazer` works on your end?

**Comment by evanjs** [comment] 2020-07-12 17:39
I updated the [docs](https://openrazer.github.io/#nixos) on the OpenRazer site after this module was merged into nixpkgs, but perhaps the nix side needs to be better documented.

**Comment by f4814** [comment] 2020-07-12 18:05
> Can you see if systemctl status --user openrazer works on your end?

Should be `openrazer-daemon`. And yes, I can see the output now.

**Comment by evanjs** [comment] 2020-07-12 23:01
Mmyup `openrazer-daemon`. 
Alright, sweet. 
And @Algram?

**Comment by Algram** [comment] 2020-07-13 15:21
@evanjs  thanks for your help, Yeah I can see the output to and it states `active and loaded` for the service. Logs look good too. As soon as I start razergenie though it tells me that the service is not present..

**Comment by evanjs** [comment] 2020-07-13 15:27
Seems to work on my end.
I recall other users having issues in the past, I think it might've been dbus-related?
I want to say that enabling `services.dbus.socketActivated` had an effect, but I can't quite remember if that was the solution.

What window manager are you using, anyhow?

**Comment by Algram** [comment] 2020-07-13 15:50
I am running sway. Setting `services.dbus.socketActivated = true` did not have an effect.

This is the "error" razerGenie produces:
![image](https://user-images.githubusercontent.com/5053729/87325133-5b0efe00-c531-11ea-865e-be98aeaddd4b.png)

**Comment by Algram** [comment] 2020-07-13 15:58
I think there must be something that is missing from the openrazer nix module. It only shows in sway because most other window managers probably add the missing config per default by chance already.

**Comment by evanjs** [comment] 2020-07-13 16:20
Yeah, I haven't been able to pin down the cause entirely, but it seems to work fine in XMonad, even without `services.dbus.socketActivated`.
If it is something that is activated by chance, I'm not sure what it might be, but am happy to add whatever if we can determine what the missing option is.

**Comment by Algram** [comment] 2020-07-14 06:59
@evanjs I changed my setup so that sway gets started via GDM. Now it works! It seems like something the displayManager adds is needed for openrazer.

One follow up question: Is there an easy way to quickly test openrazer 2.8.0? I have a Razer Viper Ultimate and support for this mouse is only in the latest release.

Thanks a lot!

**Comment by evanjs** [comment] 2020-07-25 15:41
Curious, any other Razer users with merge/write permissions?

Not sure what else I can do (or who would be best to ping) aside from e.g. 
@GrahamcOfBorg build openrazer-daemon
or etc

**Closed** 2020-07-26 17:58 UTC
Labels: 0.kind: bug, 6.topic: hardware, 6.topic: nixos
