### ISSUE TITLE
Package request: Unrud/video-downloader

### ISSUE THREAD

**Issue by matleborgne** [NixOS/nixpkgs#249936] opened 2023-08-18 11:00 UTC
**Project description**

This is an easy video downloader app, for youtube or other websites.

I build it manually from source until now.
I put here the code, because the python-wrapping is quite tricky (for a Nix newbie like me).

If it can help...

PS : even if it is not the place to do that, I'm open to advices to improve my nix-usage (via private message or anything). Thanks !

```nix
{ config, lib, pkgs, ... }:
let
  pname = "video-downloader";
  version = "v0.12.8";
  rev = "29c651584b3170f31d6825a86847874a65c5d70c";
  sha256 = "KtwJH461HQHgAxqhJNCXDeMQ2PUs+m3+NJFdfxCc60A=";

  python =
    with import <nixpkgs> {};
    python3.withPackages (ps : with ps; [ pygobject3 yt-dlp ]);

in
{
  environment.systemPackages =
  let
    video-downloader =
      with import <nixpkgs> {};
      stdenv.mkDerivation rec {
        inherit pname;
        inherit version;

        src = fetchFromGitHub {
          owner = "Unrud";
          repo = "${pname}";
          inherit rev;
          inherit sha256;
        };

        nativeBuildInputs = [
          desktop-file-utils
          appstream-glib
          meson
          ninja
          pkg-config
          python3
          wrapGAppsHook4
        ];

        buildInputs = [
          gtk4
          libadwaita
          haskellPackages.gi-gdk
          haskellPackages.gi-gtk
          yt-dlp
          ffmpeg
        ];

        preFixup = ''
          wrapProgram $out/bin/$pname \
            --prefix PYTHONPATH : ${python}/${python.sitePackages} \
        '';

      };

  in [
    video-downloader
  ];    

}

```

**Metadata**

* homepage URL: https://github.com/Unrud/video-downloader
* source URL: https://github.com/Unrud/video-downloader
* license:  GPL-3.0 license 
* platforms: linux

**Comment by Aleksanaa** [comment] 2024-03-28 15:34
Duplicate of https://github.com/NixOS/nixpkgs/issues/239832

**Closed by Aleksanaa** 2024-03-28 15:34 UTC
Labels: 0.kind: packaging request
