### ISSUE TITLE
scribus fails to build on unstable

### ISSUE THREAD

**Issue by turboMaCk** [NixOS/nixpkgs#83003] opened 2020-03-20 15:47 UTC
**Describe the bug**
`$ nix-env -i scribus` fails during compilation.

**To Reproduce**
1. nix-env -i scribus

**Expected behavior**
Scribus should be build (and cached in binary cache)

**Error**

<details>

```
/build/scribus-1.5.5/scribus/plugins/import/pdf/slaoutput.cpp: In member function 'void SlaOutputDev::startDoc(PDFDoc*, XRef*, Catalog*)':
/build/scribus-1.5.5/scribus/plugins/import/pdf/slaoutput.cpp:1232:16: error: 'class GlobalParams' has no member named 'getEnableFreeType'
 1232 |  globalParams->getEnableFreeType(),
      |                ^~~~~~~~~~~~~~~~~
[ 91%] Linking CXX shared module libimportidml.so
make[2]: *** [scribus/plugins/import/pdf/CMakeFiles/importpdf.dir/build.make:114: scribus/plugins/import/pdf/CMakeFiles/importpdf.dir/slaoutput.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3131: scribus/plugins/import/pdf/CMakeFiles/importpdf.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 91%] Building CXX object scribus/plugins/barcodegenerator/CMakeFiles/barcodegenerator.dir/barcodegeneratorrenderthread.cpp.o
[ 91%] Built target importidml
[ 91%] Building CXX object scribus/plugins/import/odg/CMakeFiles/importodg.dir/moc_importodg.cpp.o
[ 91%] Linking CXX shared module libimportai.so
[ 91%] Linking CXX shared module libuniconvertorplugin.so
[ 91%] Building CXX object scribus/plugins/import/wpg/CMakeFiles/importwpg.dir/moc_importwpg.cpp.o
[ 91%] Building CXX object scribus/plugins/import/odg/CMakeFiles/importodg.dir/moc_importodgplugin.cpp.o
[ 91%] Linking CXX shared module libimportemf.so
[ 91%] Linking CXX shared module libimportpages.so
[ 91%] Built target uniconvertorplugin
[ 91%] Building CXX object scribus/plugins/import/wpg/CMakeFiles/importwpg.dir/moc_importwpgplugin.cpp.o
[ 91%] Built target importai
[ 91%] Building CXX object scribus/plugins/barcodegenerator/CMakeFiles/barcodegenerator.dir/moc_barcode.cpp.o
[ 91%] Building CXX object scribus/plugins/barcodegenerator/CMakeFiles/barcodegenerator.dir/moc_barcodegenerator.cpp.o
[ 91%] Built target importpages
[ 91%] Building CXX object scribus/plugins/barcodegenerator/CMakeFiles/barcodegenerator.dir/moc_barcodegeneratorrenderthread.cpp.o
[ 91%] Built target importemf
[ 91%] Building CXX object scribus/plugins/import/xps/CMakeFiles/importxps.dir/importxpsplugin.cpp.o
[ 91%] Building CXX object scribus/plugins/import/xps/CMakeFiles/importxps.dir/xpsimportoptions.cpp.o
[ 91%] Building CXX object scribus/plugins/import/xps/CMakeFiles/importxps.dir/moc_importxps.cpp.o
[ 91%] Building CXX object scribus/plugins/import/xps/CMakeFiles/importxps.dir/moc_importxpsplugin.cpp.o
[ 91%] Building CXX object scribus/plugins/import/xfig/CMakeFiles/importxfig.dir/importxfigplugin.cpp.o
[ 91%] Building CXX object scribus/plugins/import/xfig/CMakeFiles/importxfig.dir/moc_importxfig.cpp.o
[ 91%] Building CXX object scribus/plugins/import/xfig/CMakeFiles/importxfig.dir/moc_importxfigplugin.cpp.o
[ 91%] Building CXX object scribus/plugins/import/xps/CMakeFiles/importxps.dir/moc_xpsimportoptions.cpp.o
[ 91%] Building CXX object scribus/plugins/import/xar/CMakeFiles/importxar.dir/importxarplugin.cpp.o
[ 91%] Linking CXX shared module libimportodg.so
[ 91%] Linking CXX shared module libimportwpg.so
[ 91%] Building CXX object scribus/plugins/import/svm/CMakeFiles/importsvm.dir/importsvmplugin.cpp.o
[ 91%] Built target importodg
[ 91%] Building CXX object scribus/plugins/import/svm/CMakeFiles/importsvm.dir/moc_importsvm.cpp.o
[ 91%] Building CXX object scribus/plugins/import/svm/CMakeFiles/importsvm.dir/moc_importsvmplugin.cpp.o
[ 91%] Built target importwpg
[ 92%] Building CXX object scribus/plugins/import/xar/CMakeFiles/importxar.dir/moc_importxar.cpp.o
[ 92%] Building CXX object scribus/plugins/import/xar/CMakeFiles/importxar.dir/moc_importxarplugin.cpp.o
[ 92%] Building CXX object scribus/plugins/import/viva/CMakeFiles/importviva.dir/importvivaplugin.cpp.o
[ 92%] Building CXX object scribus/plugins/import/viva/CMakeFiles/importviva.dir/moc_importviva.cpp.o
[ 92%] Building CXX object scribus/plugins/import/viva/CMakeFiles/importviva.dir/moc_importvivaplugin.cpp.o
[ 92%] Linking CXX shared module libbarcodegenerator.so
[ 92%] Linking CXX shared module libimportxfig.so
[ 92%] Built target barcodegenerator
[ 92%] Built target importxfig
[ 93%] Linking CXX shared module libimportsvm.so
[ 93%] Linking CXX shared module libimportxar.so
[ 93%] Linking CXX shared module libimportviva.so
[ 94%] Linking CXX shared module libimportxps.so
[ 94%] Built target importsvm
[ 94%] Built target importviva
[ 94%] Built target importxar
[ 94%] Built target importxps
make: *** [Makefile:152: all] Error 2
builder for '/nix/store/9qwl54cvym0dzrdlppr99ssf047sqny4-scribus-1.5.5.drv' failed with exit code 2
error: build of '/nix/store/9qwl54cvym0dzrdlppr99ssf047sqny4-scribus-1.5.5.drv' failed
```

</details>

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.24, NixOS, 20.09pre217446.ddf87fb1baf (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(marek): `"nixos-20.03pre212208.8130f3c1c2b"`
 - channels(root): `"nixos-20.09pre217446.ddf87fb1baf, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: scribus
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment] 2020-03-20 21:46
This is a regression due to a poppler bump. #77186
We already had a fix for `scribusUnstable` in #79585
cc @nh2 @Kiwi 
Upstream fix:
https://scribus.net/websvn/comp.php?repname=Scribus&compare%5B%5D=%2Ftrunk%2FScribus%2F%4023429&compare%5B%5D=%2Ftrunk%2FScribus%2F%4023428

**Comment by nh2** [comment] 2020-03-21 01:43
@veprbl I think the issue description is slightly inaccurate/confusing: It says `nix-env -i scribus` but the build logs show `scribus-1.5.5`, which is `pkgs.scribusUnstable` (only that version has 1.5.5).

@turboMaCk I think your nixpkgs version is too old. Your metadata shows `- channels(marek): `"nixos-20.03pre212208.8130f3c1c2b"``, which is commit 8130f3c1c2b, which does not have the fix from #79585 (commit 89e9f68).

I think you simply need to update.

I cannot reproduce it on current branches: Both `pkgs.scribus` and `pkgs.scribusUnstable` download fine for me from the binary cache on the nixpkgs `master` and `nixos-unstable` branches.

Closing optimistically; please reopen if my guess is wrong.

**Closed by nh2** 2020-03-21 01:43 UTC
Labels: 0.kind: bug

**Comment by veprbl** [comment] 2020-03-21 01:53
@nh2 I actually suspected that you didn’t miss anything, but those couple things really got me of the trail here.

**Comment by turboMaCk** [comment] 2020-03-21 08:41
@nh2 I can confirm this was the case indeed. Sorry for the oversight. After updating my user channel it works as expected.
