### ISSUE TITLE
Mindustry

### ISSUE THREAD

**Issue by eoli3n** [NixOS/nixpkgs#77200] opened 2020-01-07 09:24 UTC
**Project description**
Mindustry is a hybrid tower-defense sandbox factory game. Create elaborate supply chains of conveyor belts to feed ammo into your turrets, produce materials to use for building, and defend your structures from waves of enemies. Features include a map editor, 24 built-in maps, cross-platform multiplayer and large-scale PvP unit battles.

**Metadata**

* homepage URL: https://anuke.itch.io/mindustry
* source URL: https://github.com/Anuken/Mindustry
* license: gpl3 https://github.com/Anuken/Mindustry/blob/master/LICENSE
* platforms: linux

**Comment by petabyteboy** [comment] 2020-01-10 01:08
Duplicate of https://github.com/NixOS/nixpkgs/issues/72001

**Closed** 2020-01-13 10:01 UTC
Labels: 0.kind: packaging request
