### ISSUE TITLE
ActivityWatch

### ISSUE THREAD

**Issue by AnzenKodo** [NixOS/nixpkgs#223109] opened 2023-03-25 17:34 UTC
**Project description**

ActivityWatch is an app that automatically tracks how you spend time on your devices.

It is open source, privacy-first, cross-platform, and a great alternative to services like RescueTime, ManicTime, and WakaTime.

It can be used to keep track of your productivity, time spent on different projects, bad screen habits, or just to understand how you spend your time.

**Metadata**

* homepage URL: https://activitywatch.net/
* source URL: https://github.com/ActivityWatch/activitywatch
* license: mpl2
* platforms: unix, linux

**Comment by pinn3** [comment] 2023-03-25 18:06
Duplicate of https://github.com/NixOS/nixpkgs/issues/97379

**Closed** 2023-03-25 19:08 UTC
Labels: 0.kind: packaging request
