### ISSUE TITLE
Replace command-not-found with nix-index

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#88590] opened 2020-05-22 08:02 UTC
Our command-not-found depends on channels, which is soon replaced by flakes and no longer contain the sqlite database. An alternative could be to ship [nix-index](https://github.com/bennofs/nix-index) which has a [similar functionality](https://github.com/bennofs/nix-index#usage-as-a-command-not-found-replacement). However its index is comparable large (27mb). As an alternative we could split of all filenames in `./bin` into its own database and ship it independently. As an experiment I exported this sqlite database to csv and than compressed it with bzip2. The result is 273.5K large. Users than can unlock the whole feature set of `nix-index` by generating their own index.

**Comment by bennofs** [comment] 2020-06-04 21:26
Nix-index could also be extended with a feature to support split databases.

**Comment by matthewbauer** [comment] 2020-06-08 22:13
Duplicate of #39789

**Closed** 2020-06-08 22:32 UTC
Labels: 0.kind: bug
