### ISSUE TITLE
maintainers/scripts/update.nix does not work with some packages

### ISSUE THREAD

**Issue by fgaz** [NixOS/nixpkgs#112583] opened 2021-02-09 20:56 UTC
**Describe the bug**

I noticed that maintainers/scripts/update.nix does not work with certain packages that set passthru.updateScript.
Specifically, I tried with all the ones that use unstableGitUpdater. Weirdly, only some of those are affected.

**To Reproduce**

* `nix-shell maintainers/scripts/update.nix --argstr maintainer fgaz`
* there is no "qbe" package despite it having a passthru.updateScript

**Expected behavior**

Among the packages to update, there should be "qbe" and others

**Notify maintainers**

@jtojnar 

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.77, NixOS, 20.09.2642.88f00e7e12d (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.2642.88f00e7e12d"`
 - channels(fgaz): `"nixpkgs-21.03pre264143.7d71001b796, stable-20.09.2642.88f00e7e12d"`
 - nixpkgs: `/home/fgaz/.nix-defexpr/channels/nixpkgs`
```

nixpkgs rev 93498b15264bb796d4ff3a08971b96847cdd9391

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - qbe
 - littlegptracker
 - lobster
 - cht-sh
# a list of nixos modules affected by the problem
module:
```

I'm updating some updateScripts so that list will become obsolete soon

**Comment by jtojnar** [comment] 2021-02-09 21:05
I suspect this might be because packages are deduplicated based on the value of `updateScript`. If multiple packages use the same value, as will be more and more common now that we pass the updated attribute using an environment variable.

Perhaps we should change the nubbing to `package.meta.position`:

https://github.com/NixOS/nixpkgs/blob/a6fa79639a8334087c06e2ca9446ba0a9ce730af/maintainers/scripts/update.nix#L50

**Comment by fgaz** [comment] 2021-02-09 21:23
Aha. That's probably it then. unstableGitUpdater works with no inputs in the common case (when the src has a url attr)

**Comment by fgaz** [comment] 2022-01-07 17:55
Still important

**Comment by lilyinstarlight** [comment] 2022-10-21 20:06
I just hit this problem myself while adding `updateScript` attrs to packages I maintain

I can confirm that #160453 fixes the issue for me, so are there any concerns preventing that PR from being merged @jtojnar?

**Comment by jtojnar** [comment] 2022-10-21 21:43
I do not recall, maybe I was just not able to reproduce @fgaz’s issue. Feel free to merge it.

**Comment by lilyinstarlight** [comment] 2022-10-22 01:42
> Feel free to merge it

I'm not a committer so I can't merge it myself (if that statement was directed to me), but it would be nice to get it merged if there weren't any issues with it since it fixes at least my use case

**Closed** 2022-10-23 02:16 UTC
Labels: 0.kind: bug, 6.topic: updaters

**Comment by fgaz** [comment] 2022-10-24 10:26
I confirm the issue is fixed
