### ISSUE TITLE
Antora `site-generator` is missing

### ISSUE THREAD

**Issue by hqurve** [NixOS/nixpkgs#155113] opened 2022-01-15 13:38 UTC
### Describe the bug
When attempting to generate a site with antora, the following error message is displayed

```
FATAL (antora): Generator not found or failed to load. Try installing the '@antora/site-generator' package.
```

### Steps To Reproduce
1. Run `antora <playbook file>`

### Expected behavior
Antora runs

### Additional context
The package `site-generator-default` has been named to `site-generator` (see https://gitlab.com/antora/antora/-/issues/886). I have fixed this problem locally by using node2nix on a package set depending only on `@antora/antora` and `@antora/site-generator` and using the build logic  at https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/documentation/antora/default.nix to generate the package.

~My proposed fix is to rename `@antora/site-generator-default` to `@antora/site-generator` in both the antora file and https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/node-packages/node-packages.json. Sadly, node2nix takes very long on the nixpkgs, so I am requesting assistance.~

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by bjornfor** [comment] 2023-04-23 17:15
Not stale -- still happens on master branch.

**Comment by bjornfor** [comment] 2023-05-18 13:24
I cannot reproduce it anymore, I think it was fixed by https://github.com/NixOS/nixpkgs/pull/229512 (2 weeks ago).

**Closed by bjornfor** 2023-05-18 13:24 UTC
Labels: 0.kind: bug
