### ISSUE TITLE
Discord withVencord override not working

### ISSUE THREAD

**Issue by kutu-dev** [NixOS/nixpkgs#318608] opened 2024-06-09 19:24 UTC
### Describe the bug
Vencord settings at Discord doesn't appear when using the override on `aarch64-darwin`

### Steps To Reproduce
Set up Discord with the override on Home Manager:
```nix
home.packages = with pkgs; [
    neovim
    just
    fish
    eza
    fortune
    wezterm
    (discord.override {
      withVencord = true;
    })
  ];
```

### Expected behavior
Be able to access the Vencord options in the Discord settings.

### Screenshots
<img width="217" alt="image" src="https://github.com/NixOS/nixpkgs/assets/87788540/6ec31be7-9d73-4fb3-9b46-561189d3de4e">

### Notify maintainers
@Scrumplex
@artturin
@infinidoge 
@jopejoe1

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.2.0, macOS 14.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Infinidoge** [comment] 2024-06-09 19:28
What version of nixpkgs are you using? This was a Vencord bug that got fixed in recent versions of Vencord. The nixpkgs-unstable should work properly as far as I am aware.

**Comment by kutu-dev** [comment] 2024-06-09 19:30
As far as I know I've set up right the unstable in my flake:
```nix
inputs = {
  nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
}
```

**Comment by kutu-dev** [comment] 2024-06-09 20:00
I think it may be related with `nix-darwin`, this is how i'm setting it right now: https://github.com/kutu-dev/nubosa/blob/090b1a0c260d8caa1395c39436032d17f32c7933/modules/macos/darwin.nix

**Comment by Scrumplex** [comment] 2024-06-09 21:10
It is possible that it doesn't work on darwin :O

**Comment by kutu-dev** [comment] 2024-06-09 22:41
There is some sort of package that reports which nixpkgs channel was use to install it? Just to be sure is not an issue on my side, by the way `withOpenASAR` works just fine so overriding is not the problem by itself.

**Comment by Scrumplex** [comment] 2024-06-13 07:39
I just tested this on my work MacBook, and it seems to work fine. Is it possible that you still have a previous (non-Nix) Discord version that interferes here?

**Comment by kutu-dev** [comment] 2024-06-13 09:30
No luck so far, I've removed everything with Discord in its name that `fzf` reported to not be in a nix related directory. The Discord logs doen't say anything related with Vencord. I'm in a Macbook Air M2 if this helps.

**Comment by Qyriad** [comment] 2024-06-13 16:54
> As far as I know I've set up right the unstable in my flake:

That could still be a `nixos-unstable` locked before the fix.

When was the last time you updated that Nixpkgs input in your flake lockfile, and/or what commit is listed in the lockfile entry for Nixpkgs?

**Comment by Rexcrazy804** [comment] 2024-06-19 10:31
I kinda have a similar issue with overriding Vencord, whenever I try to open the settings page it crashes with the following:
![image](https://github.com/NixOS/nixpkgs/assets/37258415/b7de564e-3c40-4feb-b163-771e6046d2f6)

I initially expected it to be an issue with openAsar but after disabling the open asar override the error persists. It works as expected the the vencord override disabled.

**Comment by Infinidoge** [comment] 2024-06-19 11:47
With the latest Discord updates, Vencord is currently completely broken for reasons that are unrelated to Nix.

**Comment by pluiedev** [comment] 2024-06-19 12:07
> I kinda have a similar issue with overriding Vencord, whenever I try to open the settings page it crashes with the following:

This is caused by a breaking change from upstream Discord — see https://github.com/Vendicated/Vencord/issues/2584. This issue should be reserved for Nix-specific problems only.

**Closed** 2024-07-18 11:48 UTC
Labels: 0.kind: bug
