### ISSUE TITLE
Build failure: `libdevil` on `x86_64-darwin`

### ISSUE THREAD

**Issue by CrepeGoat** [NixOS/nixpkgs#309078] opened 2024-05-04 17:29 UTC
### Steps To Reproduce

1. `nix-shell -p libdevil`

### Build log

full log - https://gist.github.com/CrepeGoat/39fcb16f0c03812d409768f9dcffcf3a
log excerpt:
```console
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../include/IL -I ./../src-IL/include -I ./../include -fgnu89-inline -msse -msse2 -msse3 -I/nix/store/g51kbsic8hm1pqiyrznkdzl9wwjfsxcx-openexr-2.5.10-dev/include/OpenEXR -I/nix/store/g51kbsic8hm1pqiyrznkdzl9wwjfsxcx-openexr-2.5.10-dev/include -I/nix/store/g51kbsic8hm1pqiyrznkdzl9wwjfsxcx-openexr-2.5.10-dev/include/OpenEXR -g -O2 -c ./../src-IL/src/il_wbmp.c  -fno-common -DPIC -o .libs/libIL_la-il_wbmp.o
/nix/store/dcd018g56mxjpa6vq8hm0d7xvwbxsjqx-bash-5.2p26/bin/bash ../libtool --tag=CXX   --mode=compile clang++ -DHAVE_CONFIG_H -I. -I../include/IL  -I ./../src-IL/include -I ./../include  -I/nix/store/g51kbsic8hm1pqiyrznkdzl9wwjfsxcx-openexr-2.5.10-dev/include/OpenEXR -I/nix/store/g51kbsic8hm1pqiyrznkdzl9wwjfsxcx-openexr-2.5.10-dev/include -I/nix/store/g51kbsic8hm1pqiyrznkdzl9wwjfsxcx-openexr-2.5.10-dev/include/OpenEXR  -O3 -c -o libIL_la-il_squish.lo `test -f './../src-IL/src/il_squish.cpp' || echo './'`./../src-IL/src/il_squish.cpp
In file included from ./../src-IL/src/il_nvidia.cpp:16:
./../src-IL/include/il_manip.h:61:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register int s =  (i >> 16) & 0x00008000;
        ^~~~~~~~~
./../src-IL/include/il_manip.h:62:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register int e = ((i >> 23) & 0x000000ff) - (127 - 15);
        ^~~~~~~~~
./../src-IL/include/il_manip.h:63:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register int m =   i        & 0x007fffff;
        ^~~~~~~~~
3 errors generated.
make[1]: *** [Makefile:1372: libIL_la-il_nvidia.lo] Error 1
```

### Additional context

This is a dependency for `jellyfin` -> `nix-shell -p jellyfin` also fails for me atm.

### Notify maintainers

No maintainers listed for `libdevil` - https://github.com/NixOS/nixpkgs/blob/383ffe076d9b633a2e97b6e4dd97fc15fcf30159/pkgs/development/libraries/libdevil/default.nix#L75

Last users to edit this definition:
- @Ericson2314
- @SuperSandro2000

Maintainers for `jellyfin`, which is also affected by this:
- @nyanloutre
- @minijackson
- @purcell
- @jojosch

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.7.0, macOS 10.13.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(work): `"darwin"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-05-04 18:36
Looks like it's been broken for months: https://hydra.nixos.org/build/258216954

possibly related to #233265?

**Comment by purcell** [comment] 2024-05-06 18:09
BTW I'm pretty sure this is _not_ a dependency of `jellyfin`: I just built the latter locally on Darwin and its dependency tree does not include `libdevil`.

**Comment by CrepeGoat** [comment] 2024-05-06 18:29
> I just built the latter locally on Darwin and its dependency tree does not include `libdevil`.

Interesting. Tbh trying to build `jellyfin` is the only reason I submitted this bug in the first place. Any idea what the discrepancy between your and my experiences might be? E.g.:

- maybe it's not a dependency for your darwin version but it is for mine?
- are we on the same version of `nixpkgs`?

I'm neither a jellyfin nor darwin nor nix expert, any suggestions are very welcome.

**Comment by eclairevoyant** [comment] 2024-05-06 18:41
I'm on linux but I do see libdevil in the buildtime closure of jellyfin:
```
nix why-depends /nix/store/3wwki9m8nvcj4afxjqii5zm8gyfd4r47-jellyfin-10.8.13.drv /nix/store/idg2395nyyg30dn0l35g7dk312hx20mk-libdevil-1.7.8.drv        
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/3wwki9m8nvcj4afxjqii5zm8gyfd4r47-jellyfin-10.8.13.drv^*'
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/idg2395nyyg30dn0l35g7dk312hx20mk-libdevil-1.7.8.drv^*'
/nix/store/3wwki9m8nvcj4afxjqii5zm8gyfd4r47-jellyfin-10.8.13.drv
└───/nix/store/70kaa0nz0ivlhpz058ajiisg2ds1qiqi-jellyfin-ffmpeg-6.0.1-6.drv
    └───/nix/store/10mswrr1r07vb644f28bjl0c0z8xxyk6-avisynthplus-3.7.3.drv
        └───/nix/store/idg2395nyyg30dn0l35g7dk312hx20mk-libdevil-1.7.8.drv
```

**Comment by purcell** [comment] 2024-05-07 10:07
I checked with nix-tree on Darwin, and used its search function. There's no dependency on `avisynthplus` from `jellyfin-ffmpeg` on Darwin due to this line: https://github.com/NixOS/nixpkgs/blob/5132ef795eb8e01250b20f439ca817d33ad470d0/pkgs/development/libraries/ffmpeg/generic.nix#L43

**Comment by eclairevoyant** [comment] 2024-05-07 12:15
Yeah, that was added yesterday in #309423. So #309417 seems like a duplicate of this issue then.

**Closed** 2024-05-08 04:58 UTC
Labels: 6.topic: darwin, 0.kind: build failure
