### ISSUE TITLE
steam package is broken in unstable

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#49647] opened 2018-11-02 16:19 UTC
## Issue description
It seems, that the referenced packages are not available anymore. Package probably needs to be updated.

```none
trying http://repo.steampowered.com/steam/pool/steam/s/steam/steam_1.0.0.56.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

trying http://repo.steampowered.com/steamrt/pool/main/libv/libvpx/libvpx1_1.0.0-1+srt4_amd64.deb

trying http://repo.steampowered.com/steamrt/pool/main/v/vulkan-loader/libvulkan1_1.0.3~git20160215-0.1+steamos5+srt1_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

trying http://repo.steampowered.com/steamrt/pool/main/libv/libva/libva1_1.3.1-3+steamrt4+srt1_i386.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2831k  100 2831k    0     0  3080k      0 --:--:-- --:--:-- --:--:-- 3077k
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

trying https://abbradar.net/steamrt/pool/main/libv/libvpx/libvpx1_1.0.0-1+srt4_amd64.deb

trying https://abbradar.net/steamrt/pool/main/v/vulkan-loader/libvulkan1_1.0.3~git20160215-0.1+steamos5+srt1_amd64.deb

trying https://abbradar.net/steamrt/pool/main/libv/libva/libva1_1.3.1-3+steamrt4+srt1_i386.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
                                 Dload  Upload   Total   Spent    Left  Speed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
building '/nix/store/ibfk5z3s70fpnic2xm8bgadiwyfagmww-libvulkan1.deb.drv'...
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download libvulkan1.deb from any mirror
builder for '/nix/store/3z6bhrxplysiz2wqsr69kmw6rqpfdqkx-libvulkan1.deb.drv' failed with exit code 1
building '/nix/store/v08vm1vvs6awgkvrhpfgqixhihvcy3ww-libwind0-heimdal.deb.drv'...
building '/nix/store/r4x5k4lgf24phw3xbw3w5biwspbpiksc-libwrap0.deb.drv'...
cannot build derivation '/nix/store/ahp328fak98vr7d72rr9ripr67vv659y-steam-runtime.json.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/k90b408fg23sk1f5a2a3fyfyjhq1nicn-steam-runtime-2016-08-13.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/13ahnc934xnx1gs7y55ql5f6j8zhcgws-steam-runtime-wrapped.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/q6pmb2ryd3b6ngrhx0x13dxaggm91rwc-steam-usr-target.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/bzlgy7clw0jvn8lq5xff7n9z0s22f99q-steam-fhs.drv': 1 dependencies couldn't be built
building '/nix/store/giyrzk2rv7xb9lby4sdixggnh6fjzhaz-steam-original-1.0.0.56.drv'...
cannot build derivation '/nix/store/9m1i6818hfwzv5k66ffrmspynibw0mhc-steam-init.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/6smp2llycynssqzdjd1yybgsqlpdbw7l-steam.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/wlssidzrk4ljm3crjs8jgmw99fvy9y5r-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/n8f23ggqxmsa5032b48aaqqvpvbrp4nm-nixos-system-dagNix-19.03pre156996.c70ad805d21.drv': 1 dependencies couldn't be built
error: build of '/nix/store/n8f23ggqxmsa5032b48aaqqvpvbrp4nm-nixos-system-dagNix-19.03pre156996.c70ad805d21.drv' failed
```

### Steps to reproduce
- try to install steam in unstable

### NixOS details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.0, NixOS, 19.03pre156996.c70ad805d21 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre156996.c70ad805d21"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 - nix-channel: `https://nixos.org/channels/nixos-unstable`

### Device details
 - device: `20DLCTO1WW ThinkPad S1 Yoga 12`
 - cpu: `Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz`
 - gpu: `Intel Corporation HD Graphics 5500 (rev 09)`

**Comment by dywedir** [comment] 2018-11-02 18:34
Duplicate of https://github.com/NixOS/nixpkgs/issues/49048

**Closed** 2018-11-02 18:34 UTC
