### ISSUE TITLE
Calibre expression got broken recently

### ISSUE THREAD

**Issue by AmandaCameron** [NixOS/nixpkgs#65313] opened 2019-07-23 20:12 UTC
**Describe the bug**
Calibre on unstable is failing to launch, citing an ImportError

**To Reproduce**
1. Try and launch the calibre desktop app, via your DE of choice, or from the terminal with `calibre`
2. Get a happy little stack trace wherever the output goes.

**Expected behavior**
Calibre launches and displays my E-Book collection

**Additional context**
The stack trace output when it fails to launch is this: 

```
Traceback (most recent call last):
  File "/nix/store/jd2a76h89awrp9dnppafcicvw9q2ydv1-calibre-3.45.2/bin/..calibre-wrapped-wrapped", line 21, in <module>
    sys.exit(calibre())
  File "/nix/store/jd2a76h89awrp9dnppafcicvw9q2ydv1-calibre-3.45.2/lib/calibre/calibre/gui_launch.py", line 73, in calibre
    main(args)
  File "/nix/store/jd2a76h89awrp9dnppafcicvw9q2ydv1-calibre-3.45.2/lib/calibre/calibre/gui2/main.py", line 554, in main
    gui_debug=gui_debug)
  File "/nix/store/jd2a76h89awrp9dnppafcicvw9q2ydv1-calibre-3.45.2/lib/calibre/calibre/gui2/main.py", line 389, in run_gui
    from calibre.gui2.ui import Main
  File "/nix/store/jd2a76h89awrp9dnppafcicvw9q2ydv1-calibre-3.45.2/lib/calibre/calibre/gui2/ui.py", line 42, in <module>
    from calibre.gui2.init import LibraryViewMixin, LayoutMixin
  File "/nix/store/jd2a76h89awrp9dnppafcicvw9q2ydv1-calibre-3.45.2/lib/calibre/calibre/gui2/init.py", line 19, in <module>
    from calibre.gui2.book_details import BookDetails
  File "/nix/store/jd2a76h89awrp9dnppafcicvw9q2ydv1-calibre-3.45.2/lib/calibre/calibre/gui2/book_details.py", line 15, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ImportError: No module named QtWebKitWidgets
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.60, NixOS, 19.09pre186408.3d84cffe955 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(amandac): `""`
 - channels(root): `"nixos-19.09pre186408.3d84cffe955, nixos-unstable-19.09pre182971.a1dd419c1ff"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment] 2019-07-24 06:17
related https://github.com/NixOS/nixpkgs/pull/65150

**Comment by averelld** [comment] 2019-07-31 18:51
I think this was closed on accident due to the "..., partially fixes #65313" message.

There is a typo in --prefix that the colon is attached to PYTHONPATH and PATH. Additionally the qtWrapperArgs are not shell-evaluated in wrapQtApp, so that could be fixed by moving the python --prefix to the wrapping in the installPhase directly like so: `wrapQtApp $program --prefix PYTHONPATH : $PYTHONPATH`
After that the original / other partial problem returns, and I think @FRidh is fixing that in #56354

**Comment by FRidh** [comment] 2019-07-31 18:59
Oops, it's indeed not evaluated.

**Comment by ToxicFrog** [comment] 2019-08-05 13:19
With `--prefix` fixed, it builds, but fails to find msgpack at runtime:

    $ /nix/store/xf6f217jd593z1i06yxaczygj6z9gfxx-calibre-3.45.2/bin/calibre       
    Traceback (most recent call last):
      File "/nix/store/xf6f217jd593z1i06yxaczygj6z9gfxx-calibre-3.45.2/bin/..calibre-wrapped-wrapped", line 20, in <module>
        from calibre.gui_launch import calibre
      File "/nix/store/xf6f217jd593z1i06yxaczygj6z9gfxx-calibre-3.45.2/lib/calibre/calibre/__init__.py", line 23, in <module>
        from calibre.startup import winutil, winutilerror
      File "/nix/store/xf6f217jd593z1i06yxaczygj6z9gfxx-calibre-3.45.2/lib/calibre/calibre/startup.py", line 143, in <module>
        set_translators()
      File "/nix/store/xf6f217jd593z1i06yxaczygj6z9gfxx-calibre-3.45.2/lib/calibre/calibre/utils/localization.py", line 222, in set_translators
        mpath = get_lc_messages_path(lang)
      File "/nix/store/xf6f217jd593z1i06yxaczygj6z9gfxx-calibre-3.45.2/lib/calibre/calibre/utils/localization.py", line 109, in get_lc_messages_path
        if lang in available_translations():
      File "/nix/store/xf6f217jd593z1i06yxaczygj6z9gfxx-calibre-3.45.2/lib/calibre/calibre/utils/localization.py", line 23, in available_translations
        stats = msgpack_loads(open(stats, 'rb').read())
      File "/nix/store/xf6f217jd593z1i06yxaczygj6z9gfxx-calibre-3.45.2/lib/calibre/calibre/utils/serialize.py", line 112, in msgpack_loads
        import msgpack
    ImportError: No module named msgpack

**Comment by worldofpeace** [comment] 2019-09-29 01:41
I can't reproduce this on master. Believe it was fixed.

**Closed by worldofpeace** 2019-09-29 01:41 UTC
Labels: 0.kind: bug, 6.topic: python
