### ISSUE TITLE
Build failure: gitstatus

### ISSUE THREAD

**Issue by s-aditya-k** [NixOS/nixpkgs#358800] opened 2024-11-24 20:29 UTC
## Steps To Reproduce

1. build *gitstatus*

## Build log

<details>

<summary>Build Log</summary>

```
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/pn5xs822bapfv625apn8yddylclv79qh-source
source root is source
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
no configure script, doing nothing
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
build flags: SHELL=/nix/store/fhngvmgagwwxhak8nzrx5vqbg4g4qiac-bash-5.2p37/bin/bash
mkdir -p -- obj
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -MM -MT obj/tag_db.o src/tag_db.cc >obj/tag_db.dep
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -Wall -c -o obj/tag_db.o src/tag_db.cc
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -MM -MT obj/arena.o src/arena.cc >obj/arena.dep
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -Wall -c -o obj/arena.o src/arena.cc
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -MM -MT obj/strings.o src/strings.cc >obj/strings.dep
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -Wall -c -o obj/strings.o src/strings.cc
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -MM -MT obj/gitstatus.o src/gitstatus.cc >obj/gitstatus.dep
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -Wall -c -o obj/gitstatus.o src/gitstatus.cc
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -MM -MT obj/repo_cache.o src/repo_cache.cc >obj/repo_cache.dep
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -Wall -c -o obj/repo_cache.o src/repo_cache.cc
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -MM -MT obj/repo.o src/repo.cc >obj/repo.dep
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -Wall -c -o obj/repo.o src/repo.cc
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -MM -MT obj/thread_pool.o src/thread_pool.cc >obj/thread_pool.dep
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -Wall -c -o obj/thread_pool.o src/thread_pool.cc
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -MM -MT obj/timer.o src/timer.cc >obj/timer.dep
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -Wall -c -o obj/timer.o src/timer.cc
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -MM -MT obj/request.o src/request.cc >obj/request.dep
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -Wall -c -o obj/request.o src/request.cc
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -MM -MT obj/response.o src/response.cc >obj/response.dep
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -Wall -c -o obj/response.o src/response.cc
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -MM -MT obj/check_dir_mtime.o src/check_dir_mtime.cc >obj/check_dir_mtime.dep
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -Wall -c -o obj/check_dir_mtime.o src/check_dir_mtime.cc
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -MM -MT obj/git.o src/git.cc >obj/git.dep
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -Wall -c -o obj/git.o src/git.cc
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -MM -MT obj/logging.o src/logging.cc >obj/logging.dep
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -Wall -c -o obj/logging.o src/logging.cc
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -MM -MT obj/options.o src/options.cc >obj/options.dep
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -Wall -c -o obj/options.o src/options.cc
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -MM -MT obj/index.o src/index.cc >obj/index.dep
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -Wall -c -o obj/index.o src/index.cc
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -MM -MT obj/dir.o src/dir.cc >obj/dir.dep
clang++ -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=v1.5.5 -Wall  -Wall -c -o obj/dir.o src/dir.cc
clang++  obj/tag_db.o  obj/arena.o  obj/strings.o  obj/gitstatus.o  obj/repo_cache.o  obj/repo.o  obj/thread_pool.o  obj/timer.o  obj/request.o  obj/response.o  obj/check_dir_mtime.o  obj/git.o  obj/logging.o  obj/options.o  obj/index.o  obj/dir.o -pthread  -lgit2  -o usrbin/gitstatusd
ld: library not found for -lgit2
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:25: usrbin/gitstatusd] Error 1
```

</details>

## Additional context

Issue noticed when trying to use powerlevel10k, failure to build this package

## Metadata

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 22.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/csfywra6032psdbgna9qcbdads87gmzw-source`
```

## Notify maintainers

@mmlb 
@mweinelt 
@SuperSandro2000 

---

Note for maintainers: Please tag this issue in your PR.
tested with `--sandbox` and no `--sandbox`. frankly I am new to nix on mac, used to NixOS or nix on linux otherwise.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mweinelt** [comment] 2024-11-24 20:56
My guess would be this is due to bf4d9cd72342e25a1c2b7f299fc0bbdf20bae29c.

**Comment by mweinelt** [comment] 2024-11-24 20:58
Duplicate of https://github.com/NixOS/nixpkgs/issues/358116

**Closed by mweinelt** 2024-11-24 20:58 UTC
Labels: 0.kind: build failure

**Comment by s-aditya-k** [comment] 2024-11-25 00:18
My apologizes, didn't notice.
