### ISSUE TITLE
transmission service broke after 15.09 -> 16.03 upgrade

### ISSUE THREAD

**Issue by blueberry** [NixOS/nixpkgs#15361] opened 2016-05-10 15:55 UTC
## Issue description

I had a working transmission service configured in 15.09. I upgraded to 16.03. The service is there, but does not work properly. The settings are practically the defaults:

```nix
services.transmission = {
    enable = true;
    settings = { rpc-whitelist = "127.0.0.1,192.168.*.*"; };
  };
```

The service is active, but I cannot connect to it neither with web interface, nor with transmission-qt (both worked previously).

systemctl status shows line such as this for all torrents that I already had in the download queue:
`May 10 17:41:25 g190 transmission-daemon[885]: [2016-05-10 17:41:25.466] Kolor biblioteka (6 - 11) Scrape error: Could not connect to tracker (announcer.c:1279)`

@bjornfor @unaizalakain @hrdinka  @wizeman So, obviously something changed in the way transmission should be configured in the meantime, but I couldn't find any documentation. Can anyone help, or at least share theirs configuration that works?

### Steps to reproduce

Upgrade from NixOS 15.09 -> 16.03

## Technical details

* System: NixOS: `16.03`
* Nix version: `1.11.2`

**Comment by bjornfor** [comment] 2016-05-10 17:37
I haven't fully switched to NixOS 16.03 yet (only my laptop run 16.03, but it doesn't have transmission service). Maybe I'll have time to look at it later.

**Comment by bjornfor** [comment] 2016-05-12 08:53
I cannot reproduce the issue.

Here is what I did. I took a NixOS 15.09 machine (latest commit, 91371c2bb6e20fc0df7a812332d99c38b21a2bda), copied your config and activated. Transmission works (webUI is up), as expected. Then I switched to release-16.03 branch (latest commit, d3456dc1e490289094684f97648c6180ee1cc0f0), and ran ```sudo nixos-rebuild switch -I nixpkgs=.```. Transmission webUI was still up. Rebooted the machine, so no previous (runtime) state could interfere. Transmission webUI is still up. Added a .torrent in the webUI and watched it get downloaded.

Note that I get "Could not connect to tracker" message on both NixOS 15.09 and 16.03, although in 16.03 the message is prefixed with "Scrape error:". But transmission still works, the webUI is up and I can see it downloads files.

**Comment by bjornfor** [comment] 2016-05-12 09:07
After switching back and forth between 15.09 and 16.03, I no longer get the "Scrape error:" prefix, just "Could not connect to tracker (announcer.c:996)". Weird.

**Comment by comonoid** [comment] 2016-05-17 11:55
Me too.
After upgrading to 16.03, there was some issues with transmission.
I reowned directories to the same (!) users/groups (there were proper access permissions, but...) and it began to work! But transmission service was running _under_root_...
Now (after upgrading today) it doesn't.
systemctl status says that there was not enough wmem_max and rmem_max.
I manually sysctl'ed this parameters, status seems to be almost OK
(i don't know what is  Port Forwarding State changed from "Starting" to "???"), but it doesn't work.
Maybe it worth to add another issue...

**Comment by bjornfor** [comment] 2016-05-17 12:29
Could it be some old state left in ```/var/lib/transmission```? The service should auto-create the needed directories, so a test could be to complete remove /var/lib/transmission and see if the service works OK then. (Or instead of removing: ```[sudo] mv /var/lib/transmission{,.bak}```.)

Hm... two days ago I updated a 15.09 machine to 16.03 that have had transmission running for a while... probably since somewhere in the 14.12 release cycle. And it still works; the webUI is up and I can download new torrents.

What is going on here?

**Comment by comonoid** [comment] 2016-05-17 12:47
> Could it be some old state left in /var/lib/transmission?
But it works fine when i run it manually (under root!)...
su transmission -c 'transmission-daemon -f' 
says "This account is currently not available."...

**Comment by bjornfor** [comment] 2016-05-17 13:11
I'm pretty sure it  does not use /var/lib/transmission as state dir when run as root. At least, when I run it as my own user, "transmission-daemon -f", it uses $HOME/.config/transmission-daemon/.

**Comment by comonoid** [comment] 2016-05-17 13:17
Yes, /var/lib/transmission/ is empty (but have proper permissions and owner)...
It uses /root/.config/transmission-daemon/ (as i can see from logs)

**Comment by blueberry** [comment] 2016-05-23 06:17
I just want to confirm that, in my case, re-owning (`sudo chown -P transmission:transmission /var/lib/transmission`) helped.

**Comment by joachifm** [comment] 2016-05-23 06:30
@blueberry perhaps that should be added to the `preStart` script.

**Comment by blueberry** [comment] 2016-05-23 06:30
...but not for long. Previously, the list of torrents appeared in transmission-qt connected from the other machine, but the newly added download stalled after a few hundred kilobytes, and now nothing appears in the list, and I cannont connect again.

**Comment by blueberry** [comment] 2016-05-23 06:30
@joachifm again not working.

**Comment by blueberry** [comment] 2016-05-23 06:36
So, after nixos-rebuild and reowning again, it works again (for now).

**Comment by bjornfor** [comment] 2016-05-23 06:41
...so to sum up... it _might_ have something to do with permissions/ownership of /var/lib/transmission?

**Comment by blueberry** [comment] 2016-05-23 06:45
It definitely has.

**Comment by bjornfor** [comment] 2016-05-23 06:55
@blueberry: So what caused the issue in the first place? And was the fix simply ```sudo chown -P transmission:transmission /var/lib/transmission```? You said it broke for a while after that chown, you had to do nixos-rebuild + another chown to fix it?

**Comment by blueberry** [comment] 2016-05-23 06:57
As in the top message, transmission broke after 15.09 -> 16.03 upgrade.
After the first chown it appeared to work, but quickly was broken again.
After nixos-rebuild and the second chown, it works now, and I downloaded a torrent and resumed old downloads.

**Comment by blueberry** [comment] 2016-06-25 16:02
Problem reappears and I have  to do the chown line each time to recover...

**Comment by bjornfor** [comment] 2016-06-25 16:11
What is the ownership (user+group) of /var/lib/transmission when things break?

**Comment by blueberry** [comment] 2016-06-25 16:22
transmission:transmission, as far as I remember (now I cannot check because I've chowned it)

**Comment by bjornfor** [comment] 2016-07-19 18:11
@blueberry: Has transmission caused any more issues for you on NixOS 16.03?

**Comment by comonoid** [comment] 2016-07-19 18:14
After that problem was solved —
all is ok with transmission daemon.

**Comment by bjornfor** [comment] 2016-07-19 18:17
Close issue?

**Comment by blueberry** [comment] 2016-07-19 18:19
*not for me, though*
It breaks each time I reboot the machine.

**Comment by blueberry** [comment] 2016-07-19 18:20
The service was working, then I rebooted - now it is not, and here is what systemctl status says:

```bash
● transmission.service - Transmission BitTorrent Service
   Loaded: loaded (/nix/store/pc146ia54cq17f2sxak5ncvy62sbk4c9-unit-transmission.service/transmission.service; bad; vendor preset: enabled)
   Active: active (running) since Tue 2016-07-19 20:15:57 CEST; 53s ago
  Process: 880 ExecStartPre=/nix/store/i7hx6w6zy3bv53f2xm1r23ya8qbzn4is-bash-4.3-p42/bin/bash -c mkdir -p /var/lib/transmission /var/lib/transmission/.config/transmission-daemon /var/lib/transmission/Downloads /var/lib/transmission/.incomp
 Main PID: 886 (transmission-da)
   CGroup: /system.slice/transmission.service
           └─886 /nix/store/wbjqmalsp5s16587bv2f4x4rhx6ml3h7-transmission-2.92/bin/transmission-daemon -f --port 9091

Jul 19 20:15:59 g190 transmission-daemon[886]: [2016-07-19 20:15:59.596] RPC Server Whitelist enabled (rpc-server.c:1114)
Jul 19 20:15:59 g190 transmission-daemon[886]: [2016-07-19 20:15:59.596] UDP Failed to set receive buffer: requested 4194304, got 425984 (tr-udp.c:84)
Jul 19 20:15:59 g190 transmission-daemon[886]: [2016-07-19 20:15:59.596] UDP Please add the line "net.core.rmem_max = 4194304" to /etc/sysctl.conf (tr-udp.c:89)
Jul 19 20:15:59 g190 transmission-daemon[886]: [2016-07-19 20:15:59.596] UDP Failed to set send buffer: requested 1048576, got 425984 (tr-udp.c:95)
Jul 19 20:15:59 g190 transmission-daemon[886]: [2016-07-19 20:15:59.596] UDP Please add the line "net.core.wmem_max = 1048576" to /etc/sysctl.conf (tr-udp.c:100)
Jul 19 20:15:59 g190 transmission-daemon[886]: [2016-07-19 20:15:59.596] DHT Reusing old id (tr-dht.c:307)
Jul 19 20:15:59 g190 transmission-daemon[886]: [2016-07-19 20:15:59.596] DHT Bootstrapping from 100 IPv4 nodes (tr-dht.c:156)
Jul 19 20:15:59 g190 transmission-daemon[886]: [2016-07-19 20:15:59.596] Using settings from "/var/lib/transmission/.config/transmission-daemon" (daemon.c:528)
Jul 19 20:15:59 g190 transmission-daemon[886]: [2016-07-19 20:15:59.596] Saved "/var/lib/transmission/.config/transmission-daemon/settings.json" (variant.c:1266)
Jul 19 20:15:59 g190 transmission-daemon[886]: [2016-07-19 20:15:59.596] Port Forwarding State changed from "Not forwarded" to "???" (port-forwarding.c:92)
```bash

**Comment by blueberry** [comment] 2016-07-19 18:22
It is on a headless machine that I access through transmission-qt. It appears to be connected, but do not accept torrents, Test Port never finishes, etc...
The problem still appears to be the same.

**Comment by comonoid** [comment] 2016-07-19 18:39
blueberry: And when you restart transmission-daemon, it works?

**Comment by blueberry** [comment] 2016-07-19 21:18
I'm afraid it doesn't. To make it work, I always have to do the `chown` dance.

**Comment by blueberry** [comment] 2016-07-19 21:20
@bjornfor Now I can answer your question about the user/group that you asked 24 days ago:

When things break user:group is transmission:transmission too.

**Comment by comonoid** [comment] 2016-07-20 08:49
Where is your "download-dir"?
Is it "far" from some system paths?
I set it into my home ;-)
Also, transmission daemon must be able to write it.
A made it :transmission and proper chowns.
It's all obvious things, but sometimes i may forget something...

**Comment by blueberry** [comment] 2016-07-20 08:59
When I was installing it for the first time (a year ago) I left everything as default (see the first post). Download dir is `/var/lib/transmission/Downloads`. It has permissions, but does not work. If I chown the permissions to the same transmission:transmission it starts working. When I reboot, it does not work again. It worked like a charm until the 15.9->16.03 upgrade.

**Comment by comonoid** [comment] 2016-07-20 09:13
At least, it's obviously too early to close this ticket.
I had some similar symptoms and cured it very strangely.
I don't understand how it worked, but it worked.
May be i lost some little thing in config...

**Comment by joachifm** [comment] 2016-07-31 09:16
The problem description makes no sense. Without more information I don't know how anybody can help you.

If `chown`ing a directory that already has the correct ownership somehow fixes the problem for you, I suggest you add it to the transmission `preStart` script in your configuration.nix.

**Comment by joachifm** [comment] 2016-08-18 13:55
Closing, I can't see what we can do here.

**Closed by joachifm** 2016-08-18 13:55 UTC
Labels: 0.kind: bug, 6.topic: nixos
