### ISSUE TITLE
Stuck trying to add a binary cache

### ISSUE THREAD

**Issue by Thra11** [NixOS/nixpkgs#64359] opened 2019-07-05 22:20 UTC
## Issue description
This may be user error...

I followed the instructions in the wiki to install the armv6l sd-card image and run it on a raspberry pi zerow. However, I seem to be in a catch-22 situation with respect to binary caches:
1. I want to add `http://nixos-arm.dezgeg.me/channel` as a binary cache.
2. `/etc/nix/nix.conf` is a symlink to a file in the nix store: to change its contents, I need to edit `/etc/nixos/configuration.nix` and run `nixos-rebuild switch`.
3. If I run `nixos-rebuild switch` without an armv6l binary cache configured, it tries to rebuild the world, which simply isn't practical on such a feeble processor.
4. I try to use `--option binary-caches "http://nixos-arm.dezgeg.me/channel"` to specify the binary cache: It fails because the 
5. As far as I can tell, there's no way to specify `binaryCachePublicKeys` or disable `requireSignedBinaryCaches` on the command line.
6. I can specify `binaryCachePublicKeys` or disable `requireSignedBinaryCaches` in `/etc/nixos/configuration.nix`, but it won't take effect until I successfully run `nixos-rebuild`
7. Goto 3.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
 - system: `"armv6l-linux"`
 - host os: `Linux 4.14.50, NixOS, 19.03.git.ca2ba44cab4 (Koi)`
 - multi-user?: `yes`

**Comment by 7c6f434c** [comment] 2019-07-06 06:27
>3. If I run `nixos-rebuild switch` without an armv6l binary cache configured, it tries to rebuild the world, which simply isn't practical on such a feeble processor.
>4. I try to use `--option binary-caches "http://nixos-arm.dezgeg.me/channel"` to specify the binary cache: It fails because the 
>5. As far as I can tell, there's no way to specify `binaryCachePublicKeys` or disable `requireSignedBinaryCaches` on the command line.
>6. I can specify `binaryCachePublicKeys` or disable `requireSignedBinaryCaches` in `/etc/nixos/configuration.nix`, but it won't take effect until I successfully run `nixos-rebuild`

I sometimes copy `/etc/nix`  elsewhere and run (as root) with set `NIX_CONF_DIR=/path/to/copy` and `NIX_REMOTE=`

I guess there is another option, but I am too lazy to find out.

**Comment by addict3d** [comment] 2019-07-06 17:57
Did you try adding (both) of the following options? `--option binary-caches http://nixos-arm.dezgeg.me/channel --option binary-cache-public-keys nixos-arm.dezgeg.me-1:xBaUKS3n17BZPKeyxL4JfbTqECsT+ysbDJz29kLFRW0=%`

**Comment by Thra11** [comment] 2019-07-07 12:14
> Try the following options (both) `--option binary-caches http://nixos-arm.dezgeg.me/channel --option binary-cache-public-keys nixos-arm.dezgeg.me-1:xBaUKS3n17BZPKeyxL4JfbTqECsT+ysbDJz29kLFRW0=%`

I thought I had tried that, although looking back through the history, it appears I had a typo, so it failed, and given that `--option binary-caches` is explicitly mentioned in the docs, while `--option binary-cache-public-keys` isn't, I assumed it wasn't allowed.

It does work with nixos-rebuild on arm btw (well it doesn't error: I haven't done any meaningful testing as I have the binary cache set in nix.conf now)

**Comment by lheckemann** [comment] 2019-08-08 07:36
For the sake of completeness, but with the caveat that you probably don't really want to do this, you can disable signature checking completely using `--option require-sigs false`.

Closing, as the issue is resolved AFAIU.

**Closed by lheckemann** 2019-08-08 07:36 UTC
