### ISSUE TITLE
Add support for db generation to the dconf module

### ISSUE THREAD

**Issue by tiramiseb** [NixOS/nixpkgs#33275] opened 2018-01-01 15:43 UTC
Currently, the dconf module allows creating profiles.
Additionally, if we want to set relocatable gsettings schemas, we cannot override them with 
`services.xserver.desktopManager.gnome3.extraGSettingsOverrides`. An option is to add dbs to dconf. This blog post explains the problem & solution: https://blog.chapus.net/more-gnome-unity-system-defaults/.

That's why I think dbs support in the dconf module would be useful.

I tried hacking the module (in `dconf.nix`), trying to imitate what has been done in `environment.etc`, but I failed at it: I'm not confident enough with the nix language. So I have no patch to suggest, sorry.

**Comment by tiramiseb** [comment] 2018-01-01 15:58
Additionally, being able to provide the dconf profile as an in-line text (like the "text" option for etc files) would be great too, especially for such a file which would generally have 2 or 3 lines...

**Comment by jtojnar** [comment] 2018-02-13 13:15
This looks interesting: https://groups.google.com/d/msg/nix-devel/AesfG_5tabs/w53MZv-6AwAJ

**Comment by tiramiseb** [comment] 2018-02-13 13:55
jtojnar: "this" is my current workaround :)

**Comment by jtojnar** [comment] 2019-06-26 06:43
Hmm, I forgot about this isuee and opened a new one. Closing as a duplicate of https://github.com/NixOS/nixpkgs/issues/54150

**Closed by jtojnar** 2019-06-26 06:43 UTC
Labels: 0.kind: enhancement, 6.topic: gnome3, 6.topic: nixos
