### ISSUE TITLE
In package `libfprint-2-tod1-broadcom`, `update-fw.py`  is broken due to `glib` > `gobject-introspection` breaking change

### ISSUE THREAD

**Issue by ahydronous** [NixOS/nixpkgs#343134] opened 2024-09-19 22:04 UTC
### Describe the bug
The script `update-fw.py` errors out with

```
Traceback (most recent call last):
  File "/home/Username/Downloads/libfprint-2-tod1-broadcom/./debian/update-fw.py", line 3, in <module>
    from gi.repository import GLib, Gio
ModuleNotFoundError: No module named 'gi'
```

This is also visible in `journalctl -u fprintd`
```
sep 19 11:55:11 mylaptop fprintd[11789]: FwUpgradeError. Check Firmware Files or CID used or Hardware etc.
```

Installing `glib` , the error becomes
```
Traceback (most recent call last):
  File "/home/Username/Downloads/libfprint-2-tod1-broadcom/./debian/update-fw.py", line 3, in <module>
    from gi.repository import GLib, Gio
  File "/nix/store/4gw93n1msss5jgfpjlhv2nrcpwqj51nr-python3-3.12.5-env/lib/python3.12/site-packages/gi/importer.py", line 133, in create_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name GLib, introspection typelib not found
```
Found this issue, followed its example: https://github.com/NixOS/nixpkgs/issues/310205
(the problem is also refered to [here](https://discourse.nixos.org/t/python-glib-introspection-fails/47391) , its apparently been since 24.05)
Installed `gobject-introspection`, `wrapGAppsHook3` and `python3Packages.wrapPython` to my `systemPackages`, still the same error.

### Notify maintainers
@pitkling 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pitkling** [comment] 2024-09-24 17:29
I'll have a look at this later this week, @ahydronous. I'm not quite sure what exactly the `update-fw.py` script does (which firmware versions are updated to which, etc.) and for which systems it is needed (or whether it figures this out automatically?).

The update `update-fw.py` script is actually currently not part of nixpkgs' `libfprint-2-tod1-broadcom` driver package (also not of the [Arch Linux package](https://aur.archlinux.org/packages/libfprint-2-tod1-broadcom), which I used in parts for reference). But if some systems require a firmware update for the driver to work properly, it should probably be provided (maybe as an extra package?).

I'll update this thread when I had time to take a closer look.

**Comment by Artturin** [comment] 2024-11-03 01:35
You need to wrap the script.

**Comment by pitkling** [comment] 2024-11-03 16:50
Yep, sorry, I must admit I got sidetracked and didn't look into this yet. I will try to wrap the script later this week and add it to the driver package for now.

@ahydronous (and maybe @Artturin?): Would you be willing to test the wrapped script, once I added it to the driver package? Not sure that I can test it well myself, since my chipset seems not to need the firmware update.

**Comment by Artturin** [comment] 2024-11-03 17:21
I don't have this HW

You can wrap it by installing the script in to `$out/bin` (Preferably with a more descriptive name)

Adding `wrapGAppsNoGuiHook` and `python3Packages.wrapPython` to `nativeBuildInputs`
Adding `glib` to `buildInputs`
`dontWrapGApps = true`
Using the `preFixup` and `postFixup` from this example For how to wrap it see https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/networking/networkd-dispatcher/default.nix

**Comment by pitkling** [comment] 2024-11-18 20:18
@ahydronous

I wrapped the `update-fw.py` script locally and had a closer look what it actually does. As far as I can see, the script just triggers the fingerprint driver once, causing it to load the updated firmware (the broadcom driver bundles the firmware update and seems to install it automatically when loaded). Thus, one can achieve the same effect as the script by a simple reboot, at least according to [the driver's changelog](https://git.launchpad.net/~oem-solutions-engineers/libfprint-2-tod1-broadcom/+git/libfprint-2-tod1-broadcom/tree/debian/changelog?h=jammy-staging#n40).

So I would actually assume that the driver should have automatically updated your firmware after a reboot. If you're still having problem with this hardware, it must be some other issue. Can you let me know if it's currently working? If not, we can try to figure out whether the problem is really the firmware or something else.

Concerning bundling the script: I'm reluctant to add the `update-fw.py` script to the bundle. It adds quite some dependencies (python3, glib, …), effectively doubling the closure size. Given that the same can be achieved with a simple reboot, this seems too much overhead.

**Comment by pitkling** [comment] 2024-12-17 10:27
I'm closing this for now, as the script is not really necessary as far as I can see (see my previous comment).

**Closed by pitkling** 2024-12-17 10:27 UTC
Labels: 0.kind: bug
