### ISSUE TITLE
Can't set console font in 21.05

### ISSUE THREAD

**Issue by zanculmarktum** [NixOS/nixpkgs#125521] opened 2021-06-03 16:01 UTC
I use the exact same `configuration.nix` from the previous version (`20.09`).

My `configuration.nix`:

```
{ options, pkgs, ... }:

{
  console = {
    font = "ter-112n";
    packages = options.console.packages.default ++ [ pkgs.terminus_font ];
  };
  environment.pathsToLink = [
    "/share/consolefonts"
  ];
}
```

The issue is that it simply doesn't change the console font to Terminus despite the necessary options have been defined.

I'd argue it's caused by the `setfont` not being able to locate the font (despite it's already in `/run/current-system/sw/share/consolefonts/ter-112n.psf.gz`), i.e.

```
# setfont ter-112n
setfont: ERROR setfont.c:421 kfont_load_font: Unable to find file: ter-112n
```

But it works if I enter the full path, i.e.

```
# setfont $(nix-build --no-out-link '<nixpkgs>' -A terminus_font)/share/consolefonts/ter-112n.psf.gz
```

**Notify maintainers**

@davidak

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.05.20210601.5237039 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(root): `"nixos-21.05.641.5237039cc1e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by zanculmarktum** [comment] 2021-06-03 16:24
Apparently it works with `setfont` from `20.09`, i.e.

```
# $(nix-build --no-out-link -E 'with import (builtins.fetchTarball { name = "source"; url = "https://releases.nixos.org/nixos/20.09/nixos-20.09.4215.85960bea533/nixexprs.tar.xz"; sha256 = "03zx29f7n1m2n6q8jp2lq5nyfm4w92wmrxrif11liw2am01qy6bi"; }) {}; kbd')/bin/setfont ter-112n
```

Very interesting.

**Comment by davidak** [comment] 2021-06-03 18:31
Thanks for your report.

This is probably already fixed with https://github.com/NixOS/nixpkgs/pull/124971.

**Comment by zanculmarktum** [comment] 2021-06-03 18:44
May I ask why `./search-paths.patch` was being dropped in `21.05`?

```patch
--- a/pkgs/os-specific/linux/kbd/default.nix
+++ b/pkgs/os-specific/linux/kbd/default.nix
@@ -18,13 +25,8 @@ stdenv.mkDerivation rec {
     "--disable-nls"
   ];
 
-  patches = [ ./search-paths.patch ];
-
   postPatch =
     ''
```

**Comment by davidak** [comment] 2021-06-03 19:00
The patches did not apply anymore and it wasn't clear if they are still needed.

Can you test if the issue is fixed when the fix hits the channel? https://nixpk.gs/pr-tracker.html?pr=125143

**Comment by zanculmarktum** [comment] 2021-06-03 19:07
Sure, but I'm not too familiar with this.

What's this nixpkgs-review stuff?

**Comment by zanculmarktum** [comment] 2021-06-03 19:42
Anyway, just tested the https://github.com/NixOS/nixpkgs/pull/125143/commits/b35b0a5f041cc00e2d38980166e1325585b90e0f, doesn't seem to work.

```
# $(nix-build --no-out-link -E 'with import (builtins.fetchTarball { name = "source"; url = "https://releases.nixos.org/nixos/21.05/nixos-21.05.641.5237039cc1e/nixexprs.tar.xz"; sha256 = "006025hw2613ihh232r09722p5i37mr7an30pq9zpr7crah8pwg5"; }) { }; callPackage (builtins.fetchurl { url = "https://github.com/NixOS/nixpkgs/raw/b35b0a5f041cc00e2d38980166e1325585b90e0f/pkgs/os-specific/linux/kbd/default.nix"; sha256 = "0lv7hkl8j6ryhcmgaz1kzxqxqhajc9wp3ylkv3iyil5cmqj4j9g0"; }) {}')/bin/setfont ter-112n
setfont: ERROR setfont.c:421 kfont_load_font: Unable to find file: ter-112n
```

On the other hand, I've updated the [search-paths.patch](https://github.com/NixOS/nixpkgs/files/6593914/search-paths.txt).

Seems to work.

```
# $(nix-build --no-out-link -E 'with import (builtins.fetchTarball { name = "source"; url = "https://releases.nixos.org/nixos/21.05/nixos-21.05.641.5237039cc1e/nixexprs.tar.xz"; sha256 = "006025hw2613ihh232r09722p5i37mr7an30pq9zpr7crah8pwg5"; }) { }; kbd.overrideAttrs (drv: { patches = (drv.patches or []) ++ [ (builtins.fetchurl { url = "https://github.com/NixOS/nixpkgs/files/6593914/search-paths.txt"; sha256 = "0qvvd3181544pkdhvzgkw12hyv3da3mwylnrdca93fywrya6zk3y"; }) ]; })')/bin/setfont ter-112n
```

**Comment by davidak** [comment] 2021-06-03 20:29
[nixpkgs-review](https://github.com/Mic92/nixpkgs-review) is a tool to test pull requests.

Could you create a pull request to fix this issue and in best case also add a test?

**Comment by zanculmarktum** [comment] 2021-06-04 14:23
Do I push it to `staging` branch or `master`?

**Comment by nikp123** [comment] 2023-02-26 13:25
This still seems relevant
```
× systemd-vconsole-setup.service - Setup Virtual Console
     Loaded: loaded (/etc/systemd/system/systemd-vconsole-setup.service; linked; preset: enabled)
     Active: failed (Result: exit-code) since Sun 2023-02-26 14:07:28 CET; 8s ago
       Docs: man:systemd-vconsole-setup.service(8)
             man:vconsole.conf(5)
    Process: 246192 ExecStart=/nix/store/dxjk0fcjd7ww8d20kha0i5rd02rksqd5-systemd-251.11/lib/systemd/systemd-vconsole-setup (code=exited, status=1/FAILURE)
   Main PID: 246192 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
        CPU: 48ms

феб 26 14:07:28 NotThink systemd[1]: Starting Setup Virtual Console...
феб 26 14:07:28 NotThink systemd-vconsole-setup[246193]: setfont: ERROR setfont.c:417 kfont_load_font: Unable to find file: cp437
феб 26 14:07:28 NotThink systemd-vconsole-setup[246192]: /nix/store/lyxids8klmindjf15gikkkkg6vq1f4d9-kbd-2.5.1/bin/setfont failed with exit status 66.
феб 26 14:07:28 NotThink systemd-vconsole-setup[246192]: Setting source virtual console failed, ignoring remaining ones
феб 26 14:07:28 NotThink systemd[1]: systemd-vconsole-setup.service: Main process exited, code=exited, status=1/FAILURE
феб 26 14:07:28 NotThink systemd[1]: systemd-vconsole-setup.service: Failed with result 'exit-code'.
феб 26 14:07:28 NotThink systemd[1]: Failed to start Setup Virtual Console.
```

**Comment by nikp123** [comment] 2023-02-26 13:26
Though it works after it failed, so not sure what's going on.

**Comment by jtojnar** [comment] 2023-12-27 19:30
This should have been fixed by https://github.com/NixOS/nixpkgs/pull/125704. @nikp123 you are probably experiencing https://github.com/NixOS/nixpkgs/issues/257904.

**Closed by jtojnar** 2023-12-27 19:30 UTC
Labels: 0.kind: bug, 6.topic: nixos
