### ISSUE TITLE
Some icons (SVG?) are not displayed in Xfce in 16.09beta172

### ISSUE THREAD

**Issue by michalrus** [NixOS/nixpkgs#18536] opened 2016-09-12 12:53 UTC
## Issue description

I’ve tentatively updated my mother’s laptop—her DM is Xfce—to 16.09beta172 and some of the icons are gone:
- Chromium’s,
- battery applet,
- “Applications” menu in the corner of the display,
- LibreOffice.

Also, this might be of importance, `gtk-update-icon-cache` is gone from the `PATH`. It was there, previously.
### Steps to reproduce
1. Enable Xfce on 16.09beta172.
2. Install, e.g., Chromium → no icon shown in Xfce.
## Technical details
- System: 16.09beta172.e3bdf6b (Flounder)
- Nix version: nix-env (Nix) 1.11.4
- Nixpkgs version: "16.09beta172.e3bdf6b"

**Comment by rasendubi** [comment] 2016-09-12 21:57
Could you post your system config?

**Comment by michalrus** [comment] 2016-09-12 22:02
@rasendubi, okay, but it’s not minimal. :blush: 

https://github.com/michalrus/dotfiles/blob/e1a97b9f9bae9aa4fad5c6037b674a52eee30823/.nixos-config.symlink/machines/desktop/hardware/mother.nix

It does import this one, here’s where Xfce is enabled:

https://github.com/michalrus/dotfiles/blob/e1a97b9f9bae9aa4fad5c6037b674a52eee30823/.nixos-config.symlink/machines/desktop/base-parents.nix

Thank you for taking interest in this issue!

**Comment by michalrus** [comment] 2016-09-12 22:05
The same exact config with nix-channel switched back to 16.03 displays the icons correctly.

**Comment by rasendubi** [comment] 2016-09-12 22:30
I'll try to reproduce the issue with VM at the weekend.

**Comment by michalrus** [comment] 2016-09-12 22:31
Thank you!

**Comment by vcunat** [comment] 2016-09-13 21:11
I see what's the problem. `gtk-update-icon-cache` is the key trigger. I've put it into the `.dev` output and that isn't installed by default, so the cache doesn't get (re)generated.

**Comment by vcunat** [comment] 2016-09-13 21:17
The tool is so tiny that I think I shall put it into `.out` (again).

**Comment by rasendubi** [comment] 2016-09-27 08:12
@vcunat has this been fixed?

**Comment by vcunat** [comment] 2016-09-27 19:33
@rasendubi: I believe so. I didn't experience it in noticeable way recently, so I hope there wasn't something else also going on.

**Comment by rasendubi** [comment] 2016-09-27 21:31
Cool. I'm closing this then.

@michalrus, feel free to reopen if you still experience this.

**Comment by yegortimoshenko** [comment] 2017-10-21 22:35
I still have this issue, for example, with `xfce.xfce4-power-manager_gtk3`:

![screenshot_2017-10-21_22-31-32](https://user-images.githubusercontent.com/1643293/31856416-fee6b2b8-b6af-11e7-99d2-6f6964677695.png)

```
[chronos@yegatool:~]$ cat /run/current-system/sw/share/applications/xfce4-power-manager-settings.desktop 
[Desktop Entry]
Version=1.0
Name=Power Manager
Comment=Settings for the Xfce Power Manager
Exec=xfce4-power-manager-settings
Icon=xfce4-power-manager-settings
Terminal=false
Type=Application
Categories=XFCE;GTK;Settings;DesktopSettings;X-XFCE-SettingsDialog;X-XFCE-HardwareSettings;
NotShowIn=GNOME;KDE;Unity;
StartupNotify=true
X-XfcePluggable=true
X-XfceHelpComponent=xfce4-power-manager
X-XfceHelpPage=start
[chronos@yegatool:~]$ ls /run/current-system/sw/share/icons/hicolor/scalable/status/xfce4-power-manager-settings.svg 
/run/current-system/sw/share/icons/hicolor/scalable/status/xfce4-power-manager-settings.svg
```

**Comment by yegortimoshenko** [comment] 2017-10-21 23:15
Oh, OK. This makes SVG icons work:

```
environment.extraInit = ''
    export GDK_PIXBUF_MODULE_FILE="$(echo ${pkgs.librsvg.out}/lib/gdk-pixbuf-2.0/*/loaders.cache)";
'';
```

Thanks to @Pitometsu https://github.com/NixOS/nixpkgs/issues/16268#issuecomment-226964988 and @joncfoo https://github.com/NixOS/nixpkgs/issues/13537#issuecomment-332327760.

**Comment by yegortimoshenko** [comment] 2017-10-21 23:16
I think this should be reopened since SVG icons indeed do not show up in XFCE.

**Comment by rasendubi** [comment] 2017-10-23 11:22
Does the following configuration snippet fixes the issue?
```nix
{
  environment.pathsToLink = [ "/lib/gdk-pixbuf-2.0" ];
}
```

If it does, could you open a PR to add it to https://github.com/NixOS/nixpkgs/blob/710973e354cc0f1c18a2d201f631d54420c6084a/nixos/modules/services/x11/desktop-managers/xfce.nix#L123-L124?

**Comment by yegortimoshenko** [comment] 2017-10-31 19:22
@rasendubi Neither snippet fixes the issue, unfortunately.

**Comment by davidak** [comment] 2017-12-17 22:45
Adding this to my configuration fixes it for me. See in the linked issue.

```
  environment.variables = {
     GDK_PIXBUF_MODULE_FILE = "$(ls ${pkgs.librsvg.out}/lib/gdk-pixbuf-*/*/loaders.cache)";
  };
```
@yegortimoshenko could you test it?

**Comment by yegortimoshenko** [comment] 2017-12-17 22:53
@davidak I already do that in https://github.com/NixOS/nixpkgs/issues/18536#issuecomment-338438919, it works.

**Comment by davidak** [comment] 2017-12-17 22:55
Great. Then we should add it to Xfce.

**Closed** 2017-12-18 16:13 UTC
Labels: 0.kind: bug, 6.topic: nixos

**Comment by pshirshov** [comment] 2021-11-21 19:57
It's funny, but this is broken for me on unstable...
