### ISSUE TITLE
VSCodium patching error

### ISSUE THREAD

**Issue by mohnishkodnani** [NixOS/nixpkgs#230787] opened 2023-05-09 00:14 UTC
### Describe the bug
When using VSCodium on MAC aarch64 darwin, the patching for the sources fails. 
```console
error: builder for '/nix/store/hwnjakcz1rbayxsqs2zx5jll8a4ncky6-vscodium-1.77.3.23102.drv' failed with exit code 1;
       last 7 log lines:
       > unpacking sources
       > unpacking source archive /nix/store/a9rw5anrxqj3vxn7d2jvl0m3n4n6qc0v-VSCodium-darwin-arm64-1.77.3.23102.zip
       > source root is VSCodium.app
       > setting SOURCE_DATE_EPOCH to timestamp 1681330400 of file VSCodium.app/Contents/_CodeSignature/CodeResources
       > patching sources
       > chmod: cannot access 'resources/app/node_modules/node-pty/build/Release/spawn-helper': No such file or directory
       > /nix/store/w71caj9pkfsin952sslh62rn7kxqx5h4-stdenv-darwin/setup: line 145: pop_var_context: head of shell_variables not a function context
```

### Steps To Reproduce
1. Create a flake with nix-unstable.
2. Add vscodium with extensions as dependency for devShells.
3. build the flake.

### Expected behavior
Build should be successful to create vscodium with the requested extensions.

### Additional context
I am using nix-vscode-extensions to install extensions, however, in this case this fails with VSCodium build itself.
Also, nix-22.11 works with that version of vscodium . I believe its 1.72 in 22.11. 
### Notify maintainers

@r-ryantm 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.4.0, macOS 13.3.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `""`
 - nixpkgs: `/nix/store/acdw88ki5wlgx4r893q19blrjmbggpfh-source`
```

**Comment by bobby285271** [comment] 2023-05-09 02:39
Duplicate of #230675. You can check http://nixpk.gs/pr-tracker.html?pr=230681 for whether the fix has reached the channel you use

**Closed by bobby285271** 2023-05-09 02:39 UTC
Labels: 0.kind: bug
