### ISSUE TITLE
tor-browser-bundle-bin 7.0.2 tabs crash

### ISSUE THREAD

**Issue by jcumming** [NixOS/nixpkgs#27759] opened 2017-07-30 04:00 UTC
## Issue description

After installing the tor-browser from nixpkgs/master and starting it, all tabs crash with the 'Gah! This tab has crashed). 

### Steps to reproduce

nix-env -iA pkgs.tor-browser-bundle-bin
rm -rf ~/.local/share/tor-browser
tor-browser (wait for tor to start)
go anywhere

## Technical details

* System: 17.09.git.f0ac08b (Hummingbird)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: 17.09.git.f0ac08b927M
* Sandboxing enabled: true

**Comment by joachifm** [comment] 2017-07-30 08:39
I can't reproduce this. What do you see when running from the terminal (it should print some information about what it is doing).

**Comment by jcumming** [comment] 2017-07-30 09:25
```
Jul 30 02:23:27.000 [notice] Bootstrapped 100%: Done
[Parent 9371] WARNING: pipe error (41): Connection reset by peer: file /home/debian/build/tor-browser/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, lin
[Parent 9371] WARNING: pipe error (44): Connection reset by peer: file /home/debian/build/tor-browser/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, lin
[Parent 9371] WARNING: pipe error (46): Connection reset by peer: file /home/debian/build/tor-browser/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, lin
[Parent 9371] WARNING: pipe error (48): Connection reset by peer: file /home/debian/build/tor-browser/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, lin

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0083,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x2C006A,name=PBrowser::Msg_LoadURL) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0087,name=PBrowser::Msg_SetDocShellIsActive) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x2C006B,name=PBrowser::Msg_UpdateDimensions) Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv

[Parent 9371] WARNING: FileDescriptorSet destroyed with unconsumed descriptors: file /home/debian/build/tor-browser/ipc/chromium/src/chrome/common/file_descri

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0086,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

[Parent 9371] WARNING: waitpid failed pid:10539 errno:10: file /home/debian/build/tor-browser/ipc/chromium/src/base/process_util_posix.cc, line 268
0 migrated.
1501406609200   addons.xpi      WARN    Attempting to activate an already active default theme
1501406609200   addons.xpi      WARN    Attempting to activate an already active default theme
Jul 30 02:23:29.000 [notice] New control connection opened.
Jul 30 02:23:29.000 [notice] New control connection opened.
```

**Comment by NeQuissimus** [comment] 2017-07-30 22:29
I actually get the same thing:

```bash
tor-browser 
Fontconfig warning: line 145: blank doesn't take any effect anymore. please remove it from your fonts.conf
Jul 30 18:26:10.758 [notice] Tor 0.3.0.9 (git-22b3bf094e327093) running on Linux with Libevent 2.0.22-stable, OpenSSL 1.0.2k and Zlib 1.2.11.
Jul 30 18:26:10.758 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jul 30 18:26:10.759 [notice] Read configuration file "/nix/store/qmr3fsdd39qiz6jc4qq9mp4c9jp3nisl-tor-browser-7.0.2/share/tor-browser/TorBrowser/Data/Tor/torrc-defaults".
Jul 30 18:26:10.759 [notice] Read configuration file "/home/nequi/.local/share/tor-browser/TorBrowser/Data/Tor/torrc".
Jul 30 18:26:10.764 [notice] Opening Socks listener on 127.0.0.1:9150
Jul 30 18:26:10.764 [notice] Opening Control listener on 127.0.0.1:9151
Jul 30 18:26:10.000 [notice] Parsing GEOIP IPv4 file /nix/store/qmr3fsdd39qiz6jc4qq9mp4c9jp3nisl-tor-browser-7.0.2/share/tor-browser/TorBrowser/Data/Tor/geoip.
Jul 30 18:26:10.000 [notice] Parsing GEOIP IPv6 file /nix/store/qmr3fsdd39qiz6jc4qq9mp4c9jp3nisl-tor-browser-7.0.2/share/tor-browser/TorBrowser/Data/Tor/geoip6.
Jul 30 18:26:11.000 [notice] Bootstrapped 0%: Starting
Jul 30 18:26:11.000 [notice] New control connection opened from 127.0.0.1.
Jul 30 18:26:11.000 [notice] Starting with guard context "default"
Jul 30 18:26:11.000 [notice] New control connection opened from 127.0.0.1.
Jul 30 18:26:11.000 [notice] Bootstrapped 5%: Connecting to directory server
Jul 30 18:26:12.000 [notice] Bootstrapped 10%: Finishing handshake with directory server
Jul 30 18:26:12.000 [notice] Bootstrapped 15%: Establishing an encrypted directory connection
Jul 30 18:26:12.000 [notice] Bootstrapped 20%: Asking for networkstatus consensus
Jul 30 18:26:12.000 [notice] Bootstrapped 25%: Loading networkstatus consensus
Jul 30 18:26:13.000 [notice] Bootstrapped 45%: Asking for relay descriptors
Jul 30 18:26:13.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 72/6840, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 4% of exit bw = 0% of path bw.)
Jul 30 18:26:13.000 [notice] Bootstrapped 50%: Loading relay descriptors
Jul 30 18:26:14.000 [notice] Bootstrapped 55%: Loading relay descriptors
Jul 30 18:26:15.000 [notice] Bootstrapped 62%: Loading relay descriptors
Jul 30 18:26:15.000 [notice] Bootstrapped 67%: Loading relay descriptors
Jul 30 18:26:15.000 [notice] Bootstrapped 72%: Loading relay descriptors
Jul 30 18:26:15.000 [notice] Bootstrapped 80%: Connecting to the Tor network
Jul 30 18:26:15.000 [notice] Our directory information is no longer up-to-date enough to build circuits: We're missing descriptors for some of our primary entry guards
Jul 30 18:26:15.000 [notice] Bootstrapped 85%: Finishing handshake with first hop
Jul 30 18:26:15.000 [notice] We now have enough directory information to build circuits.
Jul 30 18:26:17.000 [notice] Bootstrapped 90%: Establishing a Tor circuit
Jul 30 18:26:18.000 [notice] Tor has successfully opened a circuit. Looks like client functionality is working.
Jul 30 18:26:18.000 [notice] Bootstrapped 100%: Done
[Parent 3161] WARNING: pipe error (40): Connection reset by peer: file /home/debian/build/tor-browser/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 322
[Parent 3161] WARNING: pipe error (43): Connection reset by peer: file /home/debian/build/tor-browser/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 322
[Parent 3161] WARNING: pipe error (45): Connection reset by peer: file /home/debian/build/tor-browser/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 322
[Parent 3161] WARNING: pipe error (47): Connection reset by peer: file /home/debian/build/tor-browser/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 322

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0083,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x2C006A,name=PBrowser::Msg_LoadURL) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0087,name=PBrowser::Msg_SetDocShellIsActive) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x2C006B,name=PBrowser::Msg_UpdateDimensions) Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv

[Parent 3161] WARNING: FileDescriptorSet destroyed with unconsumed descriptors: file /home/debian/build/tor-browser/ipc/chromium/src/chrome/common/file_descriptor_set_posix.cc, line 22

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0086,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

[Parent 3161] WARNING: waitpid failed pid:3273 errno:10: file /home/debian/build/tor-browser/ipc/chromium/src/base/process_util_posix.cc, line 268
Jul 30 18:26:20.000 [notice] New control connection opened from 127.0.0.1.
Jul 30 18:26:20.000 [notice] New control connection opened from 127.0.0.1.
[Parent 3161] WARNING: pipe error (47): Connection reset by peer: file /home/debian/build/tor-browser/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 322
[Parent 3161] WARNING: pipe error (60): Connection reset by peer: file /home/debian/build/tor-browser/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 322

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0083,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

[Parent 3161] WARNING: pipe error (62): Connection reset by peer: file /home/debian/build/tor-browser/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 322
[Parent 3161] WARNING: pipe error (64): Connection reset by peer: file /home/debian/build/tor-browser/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 322

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C006A,name=PBrowser::Msg_LoadURL) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0087,name=PBrowser::Msg_SetDocShellIsActive) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x2C006B,name=PBrowser::Msg_UpdateDimensions) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x2C006D,name=PBrowser::Msg_Activate) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0001,name=PBrowser::Msg_AsyncMessage) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0001,name=PBrowser::Msg_AsyncMessage) Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv

[Parent 3161] WARNING: FileDescriptorSet destroyed with unconsumed descriptors: file /home/debian/build/tor-browser/ipc/chromium/src/chrome/common/file_descriptor_set_posix.cc, line 22

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0086,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

[Parent 3161] WARNING: waitpid failed pid:3345 errno:10: file /home/debian/build/tor-browser/ipc/chromium/src/base/process_util_posix.cc, line 268

```

**Comment by NeQuissimus** [comment] 2017-07-30 22:48
I think I found a workaround, as per SeleniumHQ/docker-selenium#388

**Comment by joachifm** [comment] 2017-07-31 06:45
Hm, according to `about:support` multiprocess windows *is* enabled for me, but no crashing tabs. Oh, well ...

**Comment by NeQuissimus** [comment] 2017-07-31 12:36
When e10 was new, there were addons that made it crash... But if you're not having this issue... hmmm... I tried turning off my firewall and anything security-related and even booted into a standard 4.9.x kernel, still crashing tabs.

**Comment by joachifm** [comment] 2017-07-31 14:42
@jcumming can you try
```
packageOverrides = super: {
  tor-browser-bundle-bin = super.tor-browser-bundle-bin.override {
    extraPrefs = ''
      lockPref("browser.tabs.remote.autostart", false);
      lockPref("browser.tabs.remote.autostart.2", false);
    '';
  };
}
```
per the fix suggested by @NeQuissimus ?

**Comment by jcumming** [comment] 2017-08-02 02:18
That fixes it, thanks!

**Comment by ylwghst** [comment] 2017-08-18 20:46
In 7.0.3 tor-browser all tabs are still crashing.

Can be fixed with browser.tabs.remote.autostart = false,browser.tabs.remote.autostart.2 = false.

We need to set this by default.

**Comment by NeQuissimus** [comment] 2017-08-19 09:41
@grahamc disagrees in #27781 :) I don't really swing either way...

**Comment by joachifm** [comment] 2017-08-19 14:04
This won't be the default without an explanation of *why* it is necessary and only for some users (i.e., not for me). Ideally, the underlying issue would be fixed instead, which is either some problem in the packaging or an upstream issue.

**Comment by ylwghst** [comment] 2017-08-19 16:08
@joachifm It simply doesn't work out of the box. On fresh NixOS install after nix-env -iA torbrowser wil user get non-functional browser bundle. Then user needs spend time searching how to fix it. Why do we should this do every time? Why do users should do it again and again? Official bundle from tor-project doesn't work on NixOS. Tor-browsers users rely only on this nix package.

**Comment by joachifm** [comment] 2017-08-19 16:27
But it does work for me, I need more technical details to be convinced. The reason I'm hesitant is that silently disabling security features is undesirable, esp. for something like this.

**Comment by ylwghst** [comment] 2017-08-19 19:25
Ok. Here we go. Here are some. Just tell me what else I can provide you.

Steps:

1. Install NixOS
nixos-install

2. Run GDM, GNOME Shell 3.22.0 Session, nouevau VideoDriver
$ systemctl start display-manager

3. Install tor-browser bundle package
$ nix-env -iA nixos.torbrowser

4. Run tor-browser
 $ tor-browser

5. Open www.google.com in new tab

6. Gah. Your tab just crashed.

Screenshot: https://i.imgur.com/3vh66HH.png

Error log:  https://gist.github.com/ylwghst/056d7c760e37c345c3fdd3731c5c568b

System:
$ uname -a
Linux nixOs 4.9.40 #1-NixOS SMP Thu Jul 27 22:08:24 UTC 2017 x86_64 GNU/Linux

$ lspci
https://gist.github.com/ylwghst/339205274c162a6e8243618fac775869

# X Window System
  services.xserver = {
      enable = true;
      videoDrivers = [ "nouveau" ];
      autorun = false;
      layout = "us";
  };

  services.xserver.desktopManager.gnome3.enable = true;
  services.xserver.displayManager.gdm.enable = true;

**Comment by ylwghst** [comment] 2017-08-19 20:06
## VirtualBox Machine
The same error reproduced in NixOS live cd system running in Virtual Box:

https://gist.github.com/anonymous/a57a0c4fa48d14469cdea2414b403c3a

**Comment by joachifm** [comment] 2017-08-19 20:24
I should clarify that I'm not doubting that the error occurs, I'm looking to understand whether reducing security for all users is the only viable solution.

**Comment by joachifm** [comment] 2017-08-19 20:29
@ylwghst thank you, I'll look through that for clues.

**Comment by joachifm** [comment] 2017-09-15 09:46
Now it is consistently reproducible for me as well, on both NixOS and non-NixOS. I'm leaning towards adding a toggle to enable the work-around, which will be on by default , despite being an awful non-solution.

**Closed** 2017-09-22 22:19 UTC
