### ISSUE TITLE
Package request: swhkd

### ISSUE THREAD

**Issue by rxf4el** [NixOS/nixpkgs#239242] opened 2023-06-22 19:14 UTC
swhkd is a display protocol-independent hotkey daemon made in Rust. swhkd uses an easy-to-use configuration system inspired by sxhkd, so you can easily add or remove hotkeys.

It also attempts to be a drop-in replacement for sxhkd, meaning your sxhkd config file is also compatible with swhkd.

**Metadata**
* homepage URL: https://github.com/waycrate/swhkd
* source URL: https://github.com/waycrate/swhkd
* license: BSD 2-Clause "Simplified" License
* platforms: linux

**Comment by gekoke** [comment] 2023-07-01 00:03
Duplicate of #180942

**Closed** 2023-07-01 00:35 UTC
Labels: 0.kind: packaging request
