### ISSUE TITLE
Cannot compile Chromium with WideVine enabled on NixOS unstable

### ISSUE THREAD

**Issue by travisbhartwell** [NixOS/nixpkgs#22922] opened 2017-02-17 22:40 UTC
## Issue description

For the last few updates to NixOS Unstable, I have been unable to build Chromium with the WideVine plugin enabled.

I believe the relevant portion of the build log is this:

```
setting SOURCE_DATE_EPOCH to timestamp 1485926926 of file plugins/libwidevinecdmadapter.so
patching sources
patchelf: patchelf.cc:1046: void ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym>::modifyRPath(ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym>::RPathOp, std::__cxx11::string) [with Elf_Ehdr = Elf64_Ehdr; Elf_Phdr = Elf64_Phdr; Elf_Shdr = Elf64_Shdr; Elf_Addr = long unsigned int; Elf_Off = long unsigned int; Elf_Dyn = Elf64_Dyn; Elf_Sym = Elf64_Sym; std::__cxx11::string = std::__cxx11::basic_string<char>]: Assertion `strTabAddr == rdi(shdrDynStr.sh_addr)' failed.
/nix/store/slk6v56b8i569mlg7jy9fafj807ym5bm-stdenv/setup: line 882:    67 Aborted                 patchelf --set-rpath "/nix/store/qhncpl9rbw7yvakjy8bhjsn8bpm3l8rc-gcc-5.4.0-lib/lib64:/nix/store/qhncpl9rbw7yvakjy8bhjsn8bpm3l8rc-gcc-5.4.0-lib/lib" "$sofile"
```

For my entire build log see https://gist.github.com/travisbhartwell/d92a32c252c39b768f7eb75427c00692

I'm just sure how to pull out that which is related to just the Chromium derivation.

### Steps to reproduce

I have `chromium` listed in my `environment.systemPackages` and also this in my `configuration.nix`:

```
  nixpkgs.config = {
    chromium = {
      enablePepperFlash = true;
      enablePepperPDF = true;
      enableWideVine = true;
    };
  };
```

I have run the update to the latest version like I usually do:
```
sudo nixos-rebuild switch --upgrade 2>&1 | tee ~/rebuild.out
```

## Technical details

* System: `17.03pre99759.f66d782` but trying to update to `17.03pre100522.01fef3f`
* Nix version: 1.11.6
* Nixpkgs version: `17.03pre101267.a9584c9`

**Comment by globin** [comment] 2017-02-18 12:03
Duplicate of #22333

**Closed by globin** 2017-02-18 12:03 UTC
