### ISSUE TITLE
Flask doesn't work with nix-shell

### ISSUE THREAD

**Issue by AntonyBrand** [NixOS/nixpkgs#42924] opened 2018-07-03 17:08 UTC
## Issue description
When creating a project, flask messed up the $PATH horribly. Something to do with setuptools

### Steps to reproduce
1.  Create default.nix:
```
with import<nixpkgs> {};
stdenv.mkDerivation rec {
  name = "env";
  env = buildEnv { name = name; paths = buildInputs; };
  buildInputs = [
  python3
  python36Packages.flask
  ];
}
```
2. Run `nix-shell`, see:

```
[nix-shell:~/repos/the_glastonbury_map]$ ./run_server 
 * Serving Flask app "application.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
  File "/nix/store/jx467x1rpga9ic0fjp5qygd1ja3rsnli-python3.6-Flask-1.0.2/bin/flask", line 2
    export PATH='/nix/store/89ammdpygm0cx2y4184x4kfvsncc0dsr-python3-3.6.5/bin:/nix/store/jx467x1rpga9ic0fjp5qygd1ja3rsnli-python3.6-Flask-1.0.2/bin:/nix/store/amah49jgii6lbvq3igmncjmll34qm71i-python3.6-setuptools-39.2.0/bin'${PATH:+':'}$PATH
              ^
SyntaxError: invalid syntax
```
(note that run_server comes from @rebeccaskinner  [demo repo](https://github.com/rebeccaskinner/py-todo) which accompanies her [blog post](http://rebeccaskinner.net/blog/python_and_nix/)

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
[nix-shell:~/repos/the_glastonbury_map]$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.01 MiB download, 0.03 MiB unpacked):
  /nix/store/5ljwbw3adks6cwxbc9mvvn2k0zb7b1d2-DarwinTools-1
  /nix/store/fvr8sb8ad6yjramxn4nqlyijmbhx3rk2-nix-info
copying path '/nix/store/5ljwbw3adks6cwxbc9mvvn2k0zb7b1d2-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/fvr8sb8ad6yjramxn4nqlyijmbhx3rk2-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-darwin"`
 - host os: `Darwin 15.4.0, macOS 10.11.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(antonybrand): `"unstable-18.09pre144939.14a9ca27e69"`
 - channels(root): `"nixpkgs-18.09pre144939.14a9ca27e69"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by dotlambda** [comment] 2018-07-03 20:36
You should probably use `python36.withPackages`: https://nixos.org/nixpkgs/manual/#using-python

**Comment by AntonyBrand** [comment] 2018-07-03 21:17
@dotlambda Is that in addition to using python3 or instead of?

**Comment by dotlambda** [comment] 2018-07-03 21:20
Instead of both, python and flask.

**Comment by gavinrogers** [comment] 2018-07-03 21:28
I've reproduced this working without ```FLASK_ENV=1```, but when I add it in, I get the error. I've got it [a branch to demonstrate](/gavinrogers/theglastonburymap/tree/nixpkgs_issue_42924) 

If you check out that branch, ```nix-shell``` followed by ```./run_works```  works fine. Using ```./run_broken``` doesn't: seems like flask debug is making this go horribly wrong?

**Comment by gavinrogers** [comment] 2018-07-03 21:38
@dotlambda The manual is vague, how would you use withPackages in this situation? A comment with pseudo-code would probably suffice. Thanks!

**Comment by dotlambda** [comment] 2018-07-03 21:40
Just put `(python3.withPackages (ps: with ps; [ flask ]))` into `buildInputs`.

**Comment by gavinrogers** [comment] 2018-07-03 21:55
Ok I've tried it several ways, doesn't seem to improve anything.

**Comment by dotlambda** [comment] 2018-07-03 22:37
After looking closer, it seems like Flask is trying to run its executable as a Python script (`Restarting with stat`). Therefore we get a `SyntaxError`.
This is caused by Werkzeug doing some shady stuff for determining what to execute when reloading: https://github.com/pallets/werkzeug/blob/9cdcb93e3aa31f101bdf9477e54c48c40023b110/werkzeug/_reloader.py#L59-L73
I think this should be fixed upstream. Maybe you can create a stripped-down test case for them: When not on Nixpkgs, just create a flask wrapper manually, add that to your PATH and try to run an app that causes reloading.

Anyway, in this specific case, it will work if you add
```
postPatch = ''
  substituteInPlace werkzeug/_reloader.py \
    --replace "rv = [sys.executable]" "print(sys.executable); return sys.argv"
'';
doCheck = false;
```
to the expression for Werkzeug.

**Comment by gavinrogers** [comment] 2018-07-04 09:51
@dotlambda Before I open an issue with upstream, does it make sense to find out why the PATH seems mangled in the error message? The part that doesn't look right to me is ```bin'${PATH:+':'}$PATH``` at the end.

**Comment by dotlambda** [comment] 2018-07-04 12:24
There is no syntax error: this is perfectly valid bash. But Werkzeug is trying to execute it as Python.

**Comment by bjornfor** [comment] 2018-07-15 02:02
> I think this should be fixed upstream.

Isn't this issue self-inflicted by nixpkgs wrapping python programs as bash scripts?

**Comment by dotlambda** [comment] 2018-07-16 14:43
> Isn't this issue self-inflicted by nixpkgs wrapping python programs as bash scripts?

Yes, but I think there's no way around that if we don't want Python libraries to be installed globally.

**Comment by bjornfor** [comment] 2018-07-16 22:53
The is a possible long-term solution: make wrappers in the language of the wrapped program.

**Comment by kidd** [comment] 2018-07-26 15:57
Regarding https://github.com/NixOS/nixpkgs/issues/42924#issuecomment-402311690 , how exactly should I add that postPatch phase for werkzeug in the default.nix?  I'm still very new writing nix expressions :(.  Any chance at completing this default.nix from the OP?
```with import<nixpkgs> {};
stdenv.mkDerivation rec {
  name = "env";
  env = buildEnv { name = name; paths = buildInputs; };
  buildInputs = [
  python3
  python36Packages.flask
  ];
}```

Thanks!

**Comment by CMCDragonkai** [comment] 2018-07-27 02:04
Has this been reported upstream?

**Comment by dotlambda** [comment] 2018-07-27 07:24
@kidd That `shell.nix` should use `python36.withPackages`. You can use `packageOverrides` to override the `werkzeug` package: https://nixos.org/nixpkgs/manual/#building-packages-and-applications

**Comment by carlosdagos** [comment] 2018-07-31 05:40
@kidd, I think that what @dotlambda is saying is to try something like this in your `default.nix`:

```
with import <nixpkgs> {};

let myWerkzeug = python3Packages.werkzeug.overrideAttrs (oldAttrs: rec {
  postPatch = ''
  substituteInPlace werkzeug/_reloader.py \
    --replace "rv = [sys.executable]" "return sys.argv"
  '';
  doCheck = false;
}); in stdenv.mkDerivation rec {
  name = "env";
  env = buildEnv { name = name; paths = buildInputs; };
  buildInputs = [
    python3
    python3Packages.flask
    myWerkzeug
  ];
}
```

I'm using `overrideAttrs` because I think that's a shorter version. Also not using `python3.withPackages`. Hope it's useful 😄

**Closed** 2018-08-07 22:33 UTC
Labels: 2.status: wait-for-upstream, 6.topic: python
