### ISSUE TITLE
Steam crashes when opened

### ISSUE THREAD

**Issue by jjpe** [NixOS/nixpkgs#275384] opened 2023-12-19 11:11 UTC
### Describe the bug
The Steam application crashes when opened

### Steps To Reproduce
1. Install Steam
2. execute `steam` e.g. from Bash

### Expected behavior
I expected steam to open.

### Additional context
```
[j@lear:~]$ steam
steam.sh[8697]: Running Steam on nixos 24.05 64-bit
steam.sh[8697]: STEAM_RUNTIME is enabled automatically
setup.sh[8777]: Steam runtime environment up-to-date!
steam.sh[8697]: Steam client's requirements are satisfied
[2023-12-19 12:01:41] Startup - updater built Dec  8 2023 00:32:59
[2023-12-19 12:01:41] Startup - Steam Client launched with: '/home/j/.local/share/Steam/ubuntu12_32/steam'
12/19 12:01:41 Init: Installing breakpad exception handler for appid(steam)/version(1702079146)/tid(8813)
Authorization required, but no authorization protocol specified

src/steamexe/updateui_xwin.cpp (339) : Could not open connection to X
src/steamexe/updateui_xwin.cpp (339) : Could not open connection to X
12/19 12:01:41 Init: Installing breakpad exception handler for appid(steam)/version(1702079146)/tid(8813)
/usr/bin/zenity: /home/j/.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by /lib64/libgio-2.0.so.0)
/usr/bin/zenity: /home/j/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libxml2.so.2: version `LIBXML2_2.9.0' not found (required by /nix/store/x1swpwd1izrwbk1ksjg03zmpk6y8dj1h-appstream-0.15.5/lib/libappstream.so.4)
src/steamexe/main.cpp (1223) : failed to initialize update status ui, or create initial window
src/steamexe/main.cpp (1223) : failed to initialize update status ui, or create initial window
assert_20231219120141_4.dmp[8818]: Uploading dump (out-of-process)
/tmp/dumps/assert_20231219120141_4.dmp

[j@lear:~]$ assert_20231219120141_4.dmp[8818]: Finished uploading minidump (out-of-process): success = yes
assert_20231219120141_4.dmp[8818]: response: CrashID=bp-5733e3f7-da23-4623-876f-0e6272231219
assert_20231219120141_4.dmp[8818]: file ''/tmp/dumps/assert_20231219120141_4.dmp'', upload yes: ''CrashID=bp-5733e3f7-da23-4623-876f-0e6272231219''
```

### Notify maintainers

@jagajaga 
@jonringer 
@bobby285271

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```
[j@lear:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.68, NixOS, 24.05 (Uakari), 24.05pre560622.91a00709aebb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - channels(j): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

I'm using the `nixos-unstable` channel.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by 2xsaiko** [comment] 2023-12-19 12:12
How did you "install" it?

**Comment by jjpe** [comment] 2023-12-19 12:19
I added `steam` to `environment.systemPackages` in my `/etc/nixos/configuration.nix` file.

**Comment by 2xsaiko** [comment] 2023-12-19 12:26
Steam needs to set up extra stuff (such as 32-bit drivers which I think is the problem here), you should use `programs.steam.enable = true` instead.

**Comment by jjpe** [comment] 2023-12-19 12:36
As it turns out, `programs.steam.enable = true` was also in my configuration.nix.
I've disabled the `environment.systemPackages` entry, and still get the same issue.

So I guess the problem is with whatever `programs.steam.enable = true` does.

**Comment by 2xsaiko** [comment] 2023-12-19 12:51
Hm, weird. Anyway, I think the initial problem is this here: 

> src/steamexe/updateui_xwin.cpp (339) : Could not open connection to X
> src/steamexe/updateui_xwin.cpp (339) : Could not open connection to X

I think the libxml error is just a result of Steam trying to run zenity due it not being able to open its window to show an error message. Should probably be fixed as well but it's not the main problem.

**Comment by jjpe** [comment] 2023-12-19 13:15
Just rolled back to my previous system update @ December 15. 
Steam works, confirming a window of `15-12-2023` - `19-12-2023` for this bug to have crept in.

> Should probably be fixed as well but it's not the main problem.
I'm not really sure what that is though, or what to do about it.

Though if there's any other info or help I can provide, please let me know;
Steam works, but I'm invested in this bug being squashed quickly, because I use an NVidia card.
The driver for NVidia cards is recompiled for each kernel update (breaking the other kernels w.r.t. gfx accel), and so games have a horrible frame rate.

**Comment by predmore** [comment] 2023-12-19 19:24
I am having the same problem with an NVidia GPU running on KDE.

**Comment by jjpe** [comment] 2023-12-19 20:57
An AppStream PR was [merged](https://github.com/NixOS/nixpkgs/pull/272049) by @bobby285271 about 2 weeks ago.
I can't say for sure, but given the delay between merge and it popping up in unstable, perhaps that backport is related?

**Comment by lucasew** [comment] 2023-12-19 21:30
> Hm, weird. Anyway, I think the initial problem is this here:
> 
> > src/steamexe/updateui_xwin.cpp (339) : Could not open connection to X
> > src/steamexe/updateui_xwin.cpp (339) : Could not open connection to X
> 
> I think the libxml error is just a result of Steam trying to run zenity due it not being able to open its window to show an error message. Should probably be fixed as well but it's not the main problem.

Are you using a Wayland-based desktop environmnent such as GNOME? Maybe Xwayland is missing in your setup.

**Comment by pabloaul** [comment] 2023-12-19 21:34
Can't open it too when running on Plasma (X11), although it works when starting with Plasma (Wayland).

**Comment by Cybolic** [comment] 2023-12-19 22:08
Same exact issue with an AMD card, using the mesa packages (`mesa.driver` + 32bit and `mesa.opencl`) on KDE Plasma X11.

**Comment by jjpe** [comment] 2023-12-19 22:24
> Are you using a Wayland-based desktop environmnent such as GNOME? Maybe Xwayland is missing in your setup.

I am using KDE / Xorg. 
I did try KDE / Wayland today, but Steam itself was flickering so wildly it was plausibly seizure-inducing.
That's something I've never seen before on Xorg, so I went back to my regular KDE / Xorg session.

**Comment by Cybolic** [comment] 2023-12-20 00:09
Pinning just the `steam` package to revision 195248b  lets it work again. This is the commit just before the three last commits (on 2023-12-14) to the steam package.
It would seem the first of those three commits (195248b) is what broke steam as none of the later ones work.

**Comment by ImUrX** [comment] 2023-12-20 02:20
> Pinning just the `steam` package to revision [195248b](https://github.com/NixOS/nixpkgs/commit/195248b6c101f3d58002d5c7e15be38231780786) lets it work again.

I'm guessing you mean pinning to db04185bc923d2b168a5dd3b2aa05b7627fda5d6 works, idk what happened but previously for me steam was getting stuck loading after logging in.
I'm still getting a weird error that makes Steam switch between No Connection and Online and don't know the reason why it happens :sob:

**Comment by huantianad** [comment] 2023-12-20 03:56
Just for clarification, https://github.com/NixOS/nixpkgs/commit/195248b6c101f3d58002d5c7e15be38231780786 doesn't work for me, but it's parent 452b8162ecc995793d906cde424b652fa3dd1314 does work. I am testing with `nix run nixpkgs/HASH#steam` though, so it may have different results when installed.

**Comment by ImUrX** [comment] 2023-12-20 04:00
Yeah that makes more sense lol

**Comment by Cybolic** [comment] 2023-12-20 08:32
@ImUrX Almost, I meant 452b816 - like @huantianad mentions. Sorry - copy-paste fail from my side.

**Comment by jys1670** [comment] 2023-12-20 20:26
> Just for clarification, [195248b](https://github.com/NixOS/nixpkgs/commit/195248b6c101f3d58002d5c7e15be38231780786) doesn't work for me, but it's parent [452b816](https://github.com/NixOS/nixpkgs/commit/452b8162ecc995793d906cde424b652fa3dd1314) does work. I am testing with `nix run nixpkgs/HASH#steam` though, so it may have different results when installed.

Same here on KDE/Xorg with intel gpu
Current nixos-unstable is broken, `452b816` works fine for me

**Comment by Icy-Thought** [comment] 2023-12-21 02:13
Can confirm that the solution mentioned by @huantianad seems to temporarily resolve the issue. (Thanks! :blush:)

```nix
nix run --impure nixpkgs/452b8162ecc995793d906cde424b652fa3dd1314#steam
```

**Comment by devusb** [comment] 2023-12-21 04:22
Same -- not working on X11/AMD, does work on Wayland though. Works on X11 if I revert to my previous generation.

**Comment by relief-melone** [comment] 2023-12-21 13:41
Can also confirm the same issue on X11/KDE and Nvidia GPU. Reverting to a generation from last week also works for me as of now.

**Comment by devusb** [comment] 2023-12-21 14:30
Binding my current `xauth` file into the FHS lets it load with X11 - - trying to figure out how to predictably know what the name will be or find another way to ensure this is available inside the environemnt.

In `fhsenv.nix`:
```
  extraBwrapArgs = [
    "--bind-try /tmp/dumps /tmp/dumps"
    "--bind-try /tmp/xauth_AeHaYj /tmp/xauth_AeHaYj" # addition
  ] ++ args.extraBwrapArgs or [];
```

**Comment by tejing1** [comment] 2023-12-21 15:30
It definitely works on some X11 setups as well. I tested it primarily on X11/i3.

I wonder if the location of the X authority is dependent on the display manager used? Can you all share what display managers you're using? I tested on lightdm with no problem.

I really should have made `privateTmp` an overrideable option on the steam package itself...

**Comment by devusb** [comment] 2023-12-21 15:36
Plasma here -- Wayland working, X11 not working.

**Comment by tejing1** [comment] 2023-12-21 15:43
Display manager, not desktop environment. I'm guessing sddm, to go with plasma?

**Comment by devusb** [comment] 2023-12-21 15:46
Yeah, sddm, sorry -- read on my phone and answered too fast :)

**Comment by MinerSebas** [comment] 2023-12-21 15:49
I think the reason for only triggering for sddm is this explanation from #273537

> It turned out that these display managers set the XAUTHORITY environment variable to something other than $HOME/.Xauthority (/run/user/$UID/gdm/Xauthority in case of gdm, or /tmp/xauth_${random_string} in case of sddm >= 0.20),

**Comment by tejing1** [comment] 2023-12-21 15:53
Ok, so the proper fix is to add some bash code to `buildFHSEnv` that checks if `XAUTHORITY` starts with `/tmp`, and if it does, bind it to itself?

**Comment by tejing1** [comment] 2023-12-21 16:40
Fixed in the above PR. I also made `privateTmp` overrideable with `steam.override`, so you can turn it off if it's causing problems.

**Comment by Icy-Thought** [comment] 2023-12-21 16:54
@tejing1 that is rather odd. I am using `lightdm` myself (`mini-greeter`) and I am experiencing crashes.

**Closed** 2023-12-21 17:37 UTC
Labels: 0.kind: bug

**Comment by dltacube** [comment] 2023-12-21 17:41
How does this work now that the PR is merged into master. Does it take a while for the update to show up on a `nixos-rebuild` command?

**Comment by tejing1** [comment] 2023-12-21 17:43
it will make its way into `nixos-unstable` once hydra finishes building the next batch of packages without blocking errors. You can track it with https://nixpk.gs/pr-tracker.html?pr=275857

**Comment by dltacube** [comment] 2023-12-21 17:45
Nice! I was tracking it (erroneously) with the backport gh action.

**Comment by Icy-Thought** [comment] 2023-12-21 19:00
As I'd thought, the `nixpkgs` rev in my  `flake.lock` happens to be 91a00709aebb3602f172a0bf47ba1ef013e34835. Therefore it should already contain the `buildFHS` changes you submitted not so long ago, @tejing1.

I wonder what else could be causing this issue?

**Comment by zackattackz** [comment] 2023-12-21 19:35
Thank you all for the quick fix :)

> it will make its way into `nixos-unstable` once hydra finishes building the next batch of packages without blocking errors. You can track it with https://nixpk.gs/pr-tracker.html?pr=275857

Sorry to crowd this issue, had a question. How can one tell from [Hydra](https://hydra.nixos.org/job/nixpkgs/trunk/unstable#tabs-constituents) whether this built successfully or not and is merged into nixpkgs-unstable?

**Comment by tejing1** [comment] 2023-12-21 19:52
You probably mean `nixos-unstable` rather than `nixpkgs-unstable`, and if so, the relevant jobset is [nixos/trunk-combined](https://hydra.nixos.org/jobset/nixos/trunk-combined). You can see the status of evaluations there and what commit of nixpkgs they're from. But it's hard to tell whether the channel advanced from the hydra interface, since it does advance in the presence of some errors.

Also, hydra doesn't actually build steam, because it's unfree, so there's no specific job to look at. If what you want to know is whether a given PR has hit unstable yet, alyssa's tracker is the best way.

**Comment by zackattackz** [comment] 2023-12-21 20:13
@tejing1 
Awesome, thank you

**Comment by jjpe** [comment] 2023-12-22 00:57
> Can confirm that the solution mentioned by @huantianad seems to temporarily resolve the issue. (Thanks! 😊)
> 
> ```nix
> nix run --impure nixpkgs/452b8162ecc995793d906cde424b652fa3dd1314#steam
> ```

This doesn't quite work on my box, but the modified form
```
export NIXPKGS_ALLOW_UNFREE=1;  nix  --extra-experimental-features nix-command  --extra-experimental-features flakes  run --impure nixpkgs/452b8162ecc995793d906cde424b652fa3dd1314#steam
```
does work for me :)

**Comment by Icy-Thought** [comment] 2023-12-22 04:13
@jjpe apologies, should've mentioned that I have both `ALLOW_UNFREE=1` and `experimental-features` enabled in my flakes setup. Your command should work for everyone without the prerequisites that I'd mentioned.

**Comment by guzz46** [comment] 2023-12-24 09:09
I can confirm switching from sddm to lightdm with slick greeter fixes it for me, for some reason .Xauthority wasn't being created with sddm.

**Comment by tejing1** [comment] 2023-12-24 11:05
It's just how sddm chooses to place the x authority cookie. lightdm puts it in `~/.Xauthority`, gdm puts it in `/run/user/<uid>` somewhere, and sddm puts it in `/tmp/xauth_<random characters>`. It normally doesn't actually matter where it puts it as long as the `XAUTHORITY` environment variable contains the path to it.

The problem here was that I changed the steam package's fhs environment to run with a separate `/tmp` in order to workaround a steam bug, and that broke sddm's placement.

The fix has now reached `nixos-unstable`, incidentally, so there should be no need to switch anymore. :-)

**Comment by Icy-Thought** [comment] 2023-12-24 11:12
Can confirm that the changes you last merged fixed the issue. Appreciate the fix!
