### ISSUE TITLE
RetroArch UI missing icons / looks ugly

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#206696] opened 2022-12-18 12:27 UTC
### Describe the bug
RetroArch from Nixpkgs lacks icons / assets (see screenshots below) and looks ugly.

I believe it's been like this for years, but I thought it'd be good to document. AFAIR, upstream mixes user data and program data in their config (e.g. `~/.config/retroarch/retroarch.cfg`), which could mean that we might need fix some of this upstream. (IMHO, assets is part of the program, not user data.)

### Steps To Reproduce
1. `nix-build -A retroarch` (or `nix-build -A retroarchFull`)
2. `./result/bin/retroarch`
3. Look at the ugly UI without icons.

### Expected behavior
I expect the UI to have icons and look OK, like it does with the flatpak package.

### Screenshots
RetroArch from Nixpkgs (bad):
![retroarch](https://user-images.githubusercontent.com/133602/208297751-79806030-2be4-41b3-989b-6b0eec8b52c3.png)

RetroArch from flathub (good):
![retroarch-flatpak](https://user-images.githubusercontent.com/133602/208297830-fa16d8c2-c1c8-4d9b-8ee3-d10bbdbff414.png)

### Notify maintainers
@thiagokokada @matthewbauer @kolbycrouch @aanderse @edwtjo @MP2E 

### Metadata
Nixpkgs master and release-22.11. (And probably all the way back to the initial Nix expression.)

**Comment by thiagokokada** [comment] 2022-12-18 12:30
This is expected, we don't ship assets at all since RetroArch itself can download the assets. Just run `Online Updater -> Update Assets` and the issue should be fixed.

**Comment by bjornfor** [comment] 2022-12-18 12:43
Does the flatpak also require manual download? I don't remember doing that.

IMHO it's strange (and annoying) to have to manually complete the program install like that though.

**Comment by thiagokokada** [comment] 2022-12-18 12:50
> Does the flatpak also require manual download? I don't remember doing that.

Not sure, but it is not like shipping without assets is unexpected behavior. AFAIR Android builds are like this, or used to be at least.

There is even a prompt at the first run saying you do to this, so upstream fully expects that some releases will not include assets.

> IMHO it's strange (and annoying) to have to manually complete the program install like that though.

It is not like I am against shipping assets though. The refactor in https://github.com/NixOS/nixpkgs/pull/198271 was originally done so we could support adding more files inside the wrapper (now done with `symlinkJoin`), and this could support the assets case.

However we still need to patch the `retroarch` derivation so it points inside `symlinkJoin` path, and this gets pretty messy (the reason why `retroarchBare` itself still depends on `libretro-core-info` instead being done inside the wrapper).

If you can think a way to get out of this mess, I would be happy to review/merge your solution.

**Comment by thiagokokada** [comment] 2022-12-18 13:59
Started a PR in https://github.com/NixOS/nixpkgs/pull/206707, however as I said I got in the ugly issue where `retroarch` itself needs a patch to point out the assets directory to the `symlinkJoin` path, however I don't have a good way to get the path from `symlinkJoin` instead of `retroarch` itself.

Helps are welcome to fix this issue.

**Comment by bjornfor** [comment] 2022-12-18 16:29
@thiagokokada: Thanks for the input! (And for the PR.)

I didn't know (or had completely forgotten?) upstreams attitude towards the UI assets (rely on installing at runtime). If it's difficult to workaround in nixpkgs, then I'm fine with waiting for that to be fixed upstream (if ever). (I cannot imagine their reasoning for the current behaviour.)

**Comment by thiagokokada** [comment] 2022-12-22 17:32
Closed by #206707.

**Closed by thiagokokada** 2022-12-22 17:32 UTC
Labels: 0.kind: bug

**Comment by thiagokokada** [comment] 2022-12-23 11:39
Upstreamed a few changes: https://github.com/libretro/RetroArch/pull/14756

I still don't know how to properly hardcode the core info files, so for now we will still need out-of-tree patches. But with this PR above we can practically drop the assets patch (except for the part where we change it to always load from the defaults, but this is trivial).

**Comment by thiagokokada** [comment] 2022-12-23 12:20
Upstreamed core info patch: https://github.com/libretro/RetroArch/pull/14761.

With the changes now the patches are trivial: https://github.com/thiagokokada/nixpkgs/commit/7cc47607376b7afa1bbce5adf49d55f545cbd467

**Comment by antekone** [comment] 2023-04-17 05:53
I think that the default asset directory installed by the package is nonexistant, also root-owned, so the "download assets" option doesn't work by default? Asset.zip extraction also doesn't report any errors when trying to update them without changing the directory to user-owned, but I guess this part is upstream's fault. After changing the directory to user-owned, asset downloading succeeded and the problem went away.

**Comment by ASHGOLDOFFICIAL** [comment] 2024-06-13 15:07
@thiagokokada, sorry for asking but can I now pass `retroarch-assets` and `retroarch-joypad-autoconfig` to `retroarch`? I don't want to download them through Online Updater because they are in the repos. Can I override something to use repo's versions?
