### ISSUE TITLE
Clang++ works in nix-shell, but doesn't when installed into the user profile

### ISSUE THREAD

**Issue by Xaltonon** [NixOS/nixpkgs#44860] opened 2018-08-10 07:13 UTC
## Issue description

When used in nix-shell, `clang++` works perfectly and is able to produce working c++ binaries.  However, if it's installed with `nix-env -i clang`, it fails to compile a test c++ program.

### Steps to reproduce

Compile the following program:
```cpp
// hello.cpp
#include <iostream>

int main()
{
    std::cout << "hello\n";
}
```

`nix-shell -p clang --run "clang++ -v hello.cpp"`

```
clang version 5.0.2 (tags/RELEASE_502/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /nix/store/lwhakjfxvz93dswnwicxcmqr4p6ckiqc-clang-5.0.2/bin
Found candidate GCC installation: /nix/store/5d2njc16vdwq5ivc8y53cdlr63vmbzpf-gcc-7.3.0/lib/gcc/x86_64-unknown-linux-gnu/7.3.0
Found candidate GCC installation: /nix/store/5d2njc16vdwq5ivc8y53cdlr63vmbzpf-gcc-7.3.0/lib64/gcc/x86_64-unknown-linux-gnu/7.3.0
Selected GCC installation: /nix/store/5d2njc16vdwq5ivc8y53cdlr63vmbzpf-gcc-7.3.0/lib64/gcc/x86_64-unknown-linux-gnu/7.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/nix/store/lwhakjfxvz93dswnwicxcmqr4p6ckiqc-clang-5.0.2/bin/clang-5.0" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name hello.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -momit-leaf-frame-pointer -v -dwarf-column-info -debugger-tuning=gdb -nostdsysteminc -resource-dir /nix/store/sn0yjh2wcd7243chgb1yyz1vg26lis7g-clang-wrapper-5.0.2/resource-root -idirafter /nix/store/z10kkr081zb02kyjw8ybf2s9zll49cvx-glibc-2.27-dev/include -isystem /nix/store/pi0lr4cj88vig3s5bwl6dpnrvvpc9css-compiler-rt-5.0.2-dev/include -isystem /nix/store/pi0lr4cj88vig3s5bwl6dpnrvvpc9css-compiler-rt-5.0.2-dev/include -isystem /nix/store/pi0lr4cj88vig3s5bwl6dpnrvvpc9css-compiler-rt-5.0.2-dev/include -isystem /nix/store/5d2njc16vdwq5ivc8y53cdlr63vmbzpf-gcc-7.3.0/include/c++/7.3.0 -isystem /nix/store/5d2njc16vdwq5ivc8y53cdlr63vmbzpf-gcc-7.3.0/include/c++/7.3.0/x86_64-unknown-linux-gnu -D _FORTIFY_SOURCE=2 -internal-isystem /nix/store/sn0yjh2wcd7243chgb1yyz1vg26lis7g-clang-wrapper-5.0.2/resource-root/include -O2 -Wformat -Wformat-security -Werror=format-security -fdeprecated-macro -fdebug-compilation-dir /home/user/dl -ferror-limit 19 -fmessage-length 94 -fwrapv -stack-protector 2 -stack-protector-buffer-size 4 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -vectorize-loops -vectorize-slp -o /run/user/1000/hello-c1959f.o -x c++ hello.cpp
clang -cc1 version 5.0.2 based upon LLVM 5.0.2 default target x86_64-unknown-linux-gnu
ignoring duplicate directory "/nix/store/pi0lr4cj88vig3s5bwl6dpnrvvpc9css-compiler-rt-5.0.2-dev/include"
ignoring duplicate directory "/nix/store/pi0lr4cj88vig3s5bwl6dpnrvvpc9css-compiler-rt-5.0.2-dev/include"
#include "..." search starts here:
#include <...> search starts here:
 /nix/store/pi0lr4cj88vig3s5bwl6dpnrvvpc9css-compiler-rt-5.0.2-dev/include
 /nix/store/5d2njc16vdwq5ivc8y53cdlr63vmbzpf-gcc-7.3.0/include/c++/7.3.0
 /nix/store/5d2njc16vdwq5ivc8y53cdlr63vmbzpf-gcc-7.3.0/include/c++/7.3.0/x86_64-unknown-linux-gnu
 /nix/store/sn0yjh2wcd7243chgb1yyz1vg26lis7g-clang-wrapper-5.0.2/resource-root/include
 /nix/store/z10kkr081zb02kyjw8ybf2s9zll49cvx-glibc-2.27-dev/include
End of search list.
 "/nix/store/sn0yjh2wcd7243chgb1yyz1vg26lis7g-clang-wrapper-5.0.2/bin/ld" --eh-frame-hdr -m elf_x86_64 -o a.out /nix/store/v7hg431d55q30gy7hqlpiji3jnvi8gs3-glibc-2.27/lib/crt1.o /nix/store/v7hg431d55q30gy7hqlpiji3jnvi8gs3-glibc-2.27/lib/crti.o /nix/store/5d2njc16vdwq5ivc8y53cdlr63vmbzpf-gcc-7.3.0/lib64/gcc/x86_64-unknown-linux-gnu/7.3.0/crtbegin.o -L/nix/store/v7hg431d55q30gy7hqlpiji3jnvi8gs3-glibc-2.27/lib -L/nix/store/pw9l7c9girm5mkhzrll3rc7rfwzyiqgf-clang-5.0.2-lib/lib -L/nix/store/5d2njc16vdwq5ivc8y53cdlr63vmbzpf-gcc-7.3.0/lib64/gcc/x86_64-unknown-linux-gnu/7.3.0 -L/nix/store/5d2njc16vdwq5ivc8y53cdlr63vmbzpf-gcc-7.3.0/lib64/gcc/x86_64-unknown-linux-gnu/7.3.0/../../../../lib64 -L/nix/store/5d2njc16vdwq5ivc8y53cdlr63vmbzpf-gcc-7.3.0/lib64/gcc/x86_64-unknown-linux-gnu/7.3.0/../../.. -L/nix/store/lwhakjfxvz93dswnwicxcmqr4p6ckiqc-clang-5.0.2/bin/../lib -dynamic-linker /nix/store/v7hg431d55q30gy7hqlpiji3jnvi8gs3-glibc-2.27/lib/ld-linux-x86-64.so.2 /run/user/1000/hello-c1959f.o -rpath /nix/store/9j8wqd410a46wgijmm89c3ynpaa0whka-shell/lib64 -rpath /nix/store/9j8wqd410a46wgijmm89c3ynpaa0whka-shell/lib -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /nix/store/5d2njc16vdwq5ivc8y53cdlr63vmbzpf-gcc-7.3.0/lib64/gcc/x86_64-unknown-linux-gnu/7.3.0/crtend.o /nix/store/v7hg431d55q30gy7hqlpiji3jnvi8gs3-glibc-2.27/lib/crtn.o
```

Using `nix-env -i clang && clang++ -v hello.cpp`:

```
clang version 5.0.2 (tags/RELEASE_502/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /nix/store/lwhakjfxvz93dswnwicxcmqr4p6ckiqc-clang-5.0.2/bin
Found candidate GCC installation: /nix/store/5d2njc16vdwq5ivc8y53cdlr63vmbzpf-gcc-7.3.0/lib/gcc/x86_64-unknown-linux-gnu/7.3.0
Found candidate GCC installation: /nix/store/5d2njc16vdwq5ivc8y53cdlr63vmbzpf-gcc-7.3.0/lib64/gcc/x86_64-unknown-linux-gnu/7.3.0
Selected GCC installation: /nix/store/5d2njc16vdwq5ivc8y53cdlr63vmbzpf-gcc-7.3.0/lib64/gcc/x86_64-unknown-linux-gnu/7.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/nix/store/lwhakjfxvz93dswnwicxcmqr4p6ckiqc-clang-5.0.2/bin/clang-5.0" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name hello.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -v -dwarf-column-info -debugger-tuning=gdb -nostdsysteminc -resource-dir /nix/store/sn0yjh2wcd7243chgb1yyz1vg26lis7g-clang-wrapper-5.0.2/resource-root -idirafter /nix/store/z10kkr081zb02kyjw8ybf2s9zll49cvx-glibc-2.27-dev/include -internal-isystem /nix/store/sn0yjh2wcd7243chgb1yyz1vg26lis7g-clang-wrapper-5.0.2/resource-root/include -fdeprecated-macro -fdebug-compilation-dir /home/user/dl -ferror-limit 19 -fmessage-length 94 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -o /tmp/hello-a005be.o -x c++ hello.cpp
clang -cc1 version 5.0.2 based upon LLVM 5.0.2 default target x86_64-unknown-linux-gnu
#include "..." search starts here:
#include <...> search starts here:
 /nix/store/sn0yjh2wcd7243chgb1yyz1vg26lis7g-clang-wrapper-5.0.2/resource-root/include
 /nix/store/z10kkr081zb02kyjw8ybf2s9zll49cvx-glibc-2.27-dev/include
End of search list.
hello.cpp:1:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
1 error generated.
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.59, NixOS, 18.09pre147850.2428f5dda13 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(user): `"nixos-18.03-18.03"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Xaltonon** [comment] 2018-08-10 07:15
By comparing the environment variables of the shell and my user profile, I was able to narrow the problem down to two environment variables being missing from my user profile:

```
NIX_TARGET_CXXSTDLIB_COMPILE= -isystem /nix/store/5d2njc16vdwq5ivc8y53cdlr63vmbzpf-gcc-7.3.0/include/c++/7.3.0 -isystem /nix/store/5d2njc16vdwq5ivc8y53cdlr63vmbzpf-gcc-7.3.0/include/c++/7.3.0/x86_64-unknown-linux-gnu
NIX_CC_WRAPPER_x86_64_unknown_linux_gnu_TARGET_TARGET=1
```

Using these fixes the problem, though I don't know why clang's wrapper isn't setting them up properly.

**Comment by symphorien** [comment] 2018-08-10 11:25
I'd say this is by design: https://nixos.wiki/wiki/FAQ/I_installed_a_library_but_my_compiler_is_not_finding_it._Why%3F

**Comment by matthewbauer** [comment] 2018-08-10 14:58
No stdenv should include C++. This is definitely a bug, but one that I hope is fixed in #44221.

**Comment by dezgeg** [comment] 2018-08-11 00:55
Yeah, while I agree with the general idea of https://nixos.wiki/wiki/FAQ/I_installed_a_library_but_my_compiler_is_not_finding_it._Why%3F, a small number of packages need to use the compiler at runtime (for instance https://cffi.readthedocs.io/en/latest/cdef.html#letting-the-c-compiler-fill-the-gaps). Which means the compiler should work outside a nix-shell even if it doesn't (and shouldn't!) search `~/.nix-profile/include` or `~/.nix-profile/lib` for headers and libraries.

**Comment by Xaltonon** [comment] 2018-08-13 00:31
The reason I found this in the first place is all the tooling based off of clang that I need in my user profile also broke. (clang-tidy, irony-server, etc)

**Comment by matthewbauer** [comment] 2019-02-22 18:56
This is fixed in master.

**Closed by matthewbauer** 2019-02-22 18:56 UTC
