### ISSUE TITLE
Build failure: kicad & kicad-small

### ISSUE THREAD

**Issue by Nydragon** [NixOS/nixpkgs#327141] opened 2024-07-14 15:46 UTC
### Steps To Reproduce

1. build kicad or kicad-small

### Build log

```
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'kicad-small-8.0.3'
         whose name attribute is located at /nix/store/yzkx7gx2cn73dh3c7zg5rvgkp3yli1cd-source/pkgs/stdenv/generic/make-derivation.nix:332:7

       … while evaluating attribute 'base' of derivation 'kicad-small-8.0.3'

         at /nix/store/yzkx7gx2cn73dh3c7zg5rvgkp3yli1cd-source/pkgs/applications/science/electronics/kicad/default.nix:161:3:

          160|   passthru.callPackage = newScope { inherit addonPath python3; };
          161|   base = callPackage ./base.nix {
             |   ^
          162|     inherit stable testing baseName;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: wxpython-4.2.1 not supported for interpreter python3.12
```

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.37, NixOS, 24.11 (Vicuna), 24.11.20240708.655a58a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/store/yzkx7gx2cn73dh3c7zg5rvgkp3yli1cd-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Nydragon** [comment] 2024-07-14 15:47
@evils

**Comment by wentasah** [comment] 2024-07-14 17:22
Duplicate of #325952. Closing.

**Closed by wentasah** 2024-07-14 17:22 UTC
Labels: 0.kind: build failure
