### ISSUE TITLE
Building weechat fails on Darwin (El Capitan)

### ISSUE THREAD

**Issue by jhrr** [NixOS/nixpkgs#13032] opened 2016-02-16 13:39 UTC
```
Scanning dependencies of target perl
[ 63%] Building C object src/plugins/perl/CMakeFiles/perl.dir/weechat-perl.o
In file included from /private/var/folders/5g/3kx3mc191y93shpp91bg7jyh0000gn/T/nix-build-weechat-1.4.drv-0/weechat-1.4/src/plugins/perl/weechat-perl.c:26:
In file included from /nix/store/xvmmc5k08v90d9n6bn8239419kdv23yd-perl-5.20.3/lib/perl5/5.20.3/darwin-2level/CORE/perl.h:5199:
/nix/store/xvmmc5k08v90d9n6bn8239419kdv23yd-perl-5.20.3/lib/perl5/5.20.3/darwin-2level/CORE/inline.h:311:9: warning: nonnull parameter 'pv' will evaluate to 'true' on first encounter [-Wpointer-bool-conversion]
    if (pv && len > 1) {
        ^~ ~~
1 warning generated.
[ 63%] Building C object src/plugins/perl/CMakeFiles/perl.dir/weechat-perl-api.o
In file included from /private/var/folders/5g/3kx3mc191y93shpp91bg7jyh0000gn/T/nix-build-weechat-1.4.drv-0/weechat-1.4/src/plugins/perl/weechat-perl-api.c:27:
In file included from /nix/store/xvmmc5k08v90d9n6bn8239419kdv23yd-perl-5.20.3/lib/perl5/5.20.3/darwin-2level/CORE/perl.h:5199:
/nix/store/xvmmc5k08v90d9n6bn8239419kdv23yd-perl-5.20.3/lib/perl5/5.20.3/darwin-2level/CORE/inline.h:311:9: warning: nonnull parameter 'pv' will evaluate to 'true' on first encounter [-Wpointer-bool-conversion]
    if (pv && len > 1) {
        ^~ ~~
1 warning generated.
[ 64%] Linking C shared module perl.so
ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-Libsystem-osx-10.9.5/lib'
[ 64%] Built target perl
Scanning dependencies of target python
[ 64%] Building C object src/plugins/python/CMakeFiles/python.dir/weechat-python.o
[ 65%] Building C object src/plugins/python/CMakeFiles/python.dir/weechat-python-api.o
[ 65%] Linking C shared module python.so
ld: framework not found python
clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
src/plugins/python/CMakeFiles/python.dir/build.make:121: recipe for target 'src/plugins/python/python.so' failed
make[2]: *** [src/plugins/python/python.so] Error 1
CMakeFiles/Makefile2:977: recipe for target 'src/plugins/python/CMakeFiles/python.dir/all' failed
make[1]: *** [src/plugins/python/CMakeFiles/python.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
builder for ‘/nix/store/8h87kl47zbqd7njkrfcww69wpmvvr9wr-weechat-1.4.drv’ failed with exit code 2
error: build of ‘/nix/store/8h87kl47zbqd7njkrfcww69wpmvvr9wr-weechat-1.4.drv’ failed
```

OS X 10.11.3, Nix 1.11, using a local nixpkgs checked-out at HEAD - `1a9e00`.

**Comment by pSub** [comment] 2016-02-16 14:09
This issue might be related to #9156.

**Comment by domenkozar** [comment] 2016-02-16 14:49
`ld: framework not found python` cc @copumpkin

**Comment by tfheen** [comment] 2016-03-20 14:04
I've worked around this by putting:

`cmakeFlags = with stdenv.lib; ["-DCMAKE_FIND_FRAMEWORK=LAST"]`

in `nixpkgs/pkgs/applications/networking/irc/weechat/default.nix`

The problem is that cmake defaults to looking for frameworks before dylibs, and so ends up with the system python instead of the nix-provided one. I don't think my fix is the right one, I suspect this should rather be fixed by either having python providing a framework or flipping the default order for cmake.

**Comment by copumpkin** [comment] 2016-10-22 16:08
I think this should work now, so I'm closing. Please comment here if you still see the issue.

**Closed by copumpkin** 2016-10-22 16:08 UTC
Labels: 6.topic: darwin
