### ISSUE TITLE
python3Packages.autopep8: test failure

### ISSUE THREAD

**Issue by azahi** [NixOS/nixpkgs#205764] opened 2022-12-12 11:09 UTC
### Steps To Reproduce
1. Switch to the `master` or `nixpkgs-unstable` branch.
2. `nix build .#python310Packages.autopep8`

### Build log
https://gist.github.com/azahi/240ba067a714f8c91b60c213be7e478e
https://hydra.nixos.org/build/201651606

### Additional context
Possibly related to #202425. Marking `doCheck = false` allows the build to pass.

### Notify maintainers
@bjornfor @SFrijters

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.7-xanmod1, NixOS, 23.05 (Stoat), 23.05.20221212.ffca9ff`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - nixpkgs: `/nix/store/kd83mlwxgj1w1a2r0rm2mn6ncylwgyf9-source`

**Comment by GaetanLepage** [comment] 2022-12-12 11:11
Duplicate of: https://github.com/NixOS/nixpkgs/issues/205733

**Closed** 2022-12-12 11:12 UTC
Labels: 6.topic: python, 0.kind: build failure
