### ISSUE TITLE
virtualbox incompatible with plasma desktop on 20.09

### ISSUE THREAD

**Issue by tokudan** [NixOS/nixpkgs#101023] opened 2020-10-18 19:21 UTC
**Describe the bug**
When running VirtualBox I get the error "Qt FATAL: Cannot mix incompatible Qt library (version 0x50c07) with this library (version 0x50e02)", which means that there are two incompatible library versions of Qt involved: 5.12 (0x50c) and 5.14 (0x50e).
I'm using the plasma desktop on 20.09beta.

**To Reproduce**
1. services.xserver.desktopManager.plasma5.enable = true;
    virtualisation.virtualbox.host.enable = true;
2. Try to start VirtualBox from a terminal in Plasma.

**Expected behavior**
VirtualBox shows its graphical interface.

**Screenshots**
```
$ LANG=C VirtualBox
Qt FATAL: Cannot mix incompatible Qt library (version 0x50c07) with this library (version 0x50e02)
Aborted (Speicherabzug geschrieben)
```

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.70, NixOS, 20.09beta1181.a8da27d4b07 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09beta1181.a8da27d4b07"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
$ (sudo nix-env -q; nix-env -q) | wc -l
0
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment] 2020-11-01 13:01
Please check with https://github.com/NixOS/nixpkgs/pull/102347, I was not able to reproduce the issue there.

**Comment by doronbehar** [comment] 2020-11-01 18:19
Made https://github.com/NixOS/nixpkgs/pull/102347 Fix this.

**Comment by doronbehar** [comment] 2020-11-04 14:41
From some reason the backport PR didn't close this automatically.

**Closed by doronbehar** 2020-11-04 14:41 UTC
Labels: 0.kind: bug, 6.topic: qt/kde

**Comment by tokudan** [comment] 2020-11-07 12:55
Sorry for the late testing, just to confirm: it's working.
