### ISSUE TITLE
Slack URL handler

### ISSUE THREAD

**Issue by sheenobu** [NixOS/nixpkgs#18791] opened 2016-09-20 15:34 UTC
## Issue description

These are magic sign-in URLs. It would be a nice enhancement to the slack package to include the support files for that. It may already have pieces of it but support seems broken or incomplete.

Even with slack installed; firefox, chromium, and xdg-open do not understand slack:// URLs.  Firefox just says the address wasn't understood and chromium attempts to use xdg-open, which chokes on it and opens a browser window.

The slack.desktop entry does reference a URL handler (which xdg-mime sees) but the package may not have adequate support files to hook register this x-schema-handler to the environment.

slack.desktop:

```
[Desktop Entry]
Name=Slack
Comment=Slack Desktop
GenericName=Slack Client for Linux
Exec=/usr/bin/slack --disable-gpu %U
Icon=/usr/share/pixmaps/slack.png
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Network;InstantMessaging;
MimeType=x-scheme-handler/slack;
```

```
$ xdg-mime query default x-scheme-handler/slack
slack.desktop
```

```
$ xdg-open slack://x
/run/current-system/sw/bin/xdg-open: line 656: : command not found
```
### Steps to reproduce
- Install slack.
- Try to open a slack URL via firefox, chromium, or xdg-open.

Workaround is that i just use slack slack:// for any urls I get.
## Technical details
- System: 16.03.1287.6ac7ffd (Emu) 
- Nix version:nix-env (Nix) 1.11.2
- Nixpkgs version: 16.03.1287.6ac7ffd

**Comment by layus** [comment] 2017-01-09 14:40
Hi @sheenobu ,

Not sure if it was fixed recently of so, but it works correctly for me.
Could you confirm that it works correctly on an updated system ?

It may have been fixed by https://github.com/NixOS/nixpkgs/commit/7081325518c275b3d40f19c3be54fddfb7355c71 or https://github.com/NixOS/nixpkgs/commit/b6c80ee36c56071c99e016569a351eeadd408720

If fixed, would you mind closing this issue ?

**Comment by sheenobu** [comment] 2017-01-10 01:45
@layus 

The generated .desktop file looks good and xdg-mime query default x-scheme-handler/slack still reports slack.desktop but my browser (Chromium) decides to open slack via xdg-open, and xdg-open just launches a new chromium window. I'm going to try in an isolated vm to filter out any local garbage.

**Comment by sheenobu** [comment] 2017-01-10 01:55
@layus Yes it's working with a very simple setup. Chromium opens slack:// urls with xdg-open and xdg-open launches slack properly. Whatever new issue is a local config one. 

Calling this resolved.

**Comment by layus** [comment] 2017-02-28 10:36
@sheenobu Just to keep you updated. I recently had an issue where slack urls were not opened correctly. Was an issue with the mime/applications database. See #13134.

**Comment by emilianoesteban** [comment] 2019-11-12 13:16
i installed now ubuntu and slack, the local config it's the default, and i can't login

**Comment by nh2** [comment] 2020-01-20 19:17
Reopening; this is still not working with the Slack app and Firefox on NixOS 19.09.

* When I install and start the Slack app, it shows the `Sign In` button.
* Clicking it opens Firefox.
* I enter my workspace name and it redirects to a page showing this:

![image](https://user-images.githubusercontent.com/399535/72751807-e29e3480-3bc0-11ea-920e-2c43e773a5aa.png)

> **Signing you in to Slack...** -- You will be redirected in a few moments.

The Slack app does not open though.

Clicking the **App didn't open? Try again** link, I get this:

![image](https://user-images.githubusercontent.com/399535/72751956-445e9e80-3bc1-11ea-9047-e6c7f405bc8b.png)

> The address wasn’t understood

with `slack://T0AEDEVFX/magic-login/91...` in the Firefox URL bar.

**Copying this URL into the clipboard, and re-focusing the Slack app then suddenly signs me in.**

---

Trying the same thing again, at the time I click the **App didn't open? Try again** link, I now get a different page, not a Firefox "The address wasn’t understood" error:

![image](https://user-images.githubusercontent.com/399535/72752045-81c32c00-3bc1-11ea-943e-53792239e7a6.png)

> It looks like your browser didn't redirect you back to the Slack app.
>
> To finish signing in, copy your sign-in key below and open the Slack desktop app.
>
> No need to paste the sign-in key anywhere — you'll be automatically signed in when you open the Slack app.

This explains why copy-pasting the link into the clipboard worked last time -- apparently the app watches the clipboard.

---

**I'm reopening this bug because the `slack://` URL should have made Firefox `xdg-open` it, when it didn't.

Running `xdg-open` manually on the URL seems to work, so at least that part seems to have improved since this issue was filed. We just have to fix Firefox calling `xdg-open`. Anybody have an idea how to do that?

**Comment by layus** [comment] 2020-01-20 21:13
@nh2  Could it have been solved by https://github.com/NixOS/nixpkgs/pull/75825 ?

**Comment by layus** [comment] 2020-01-20 21:14
If so, you can ask there for a backport on 19.09.

**Comment by siers** [comment] 2020-05-06 15:24
It does work for me on 20.03, though I had to install it in the system rather than from user env, unsurprinsingly.

**Comment by ogroendal** [comment] 2020-07-14 13:13
I have the same issue on Nixos 20.03, I installed the slack app (slack-black) directly in my configuration.nix
@nh2  your suggestion with putting it in to the clipboard worked great for me.

**Comment by maxon755** [comment] 2022-07-25 11:53
The only workaround that helped me to log in to desktop slack on Manjaro Linux is: 
1. Add an argument logging to the xdg-open script
`echo $1 > /some-log-file`
2. Press the button Sign in to Slack in the desktop app
3. Choose your workspace and press xdg-open
4. Go to the file with logs and copy the URL
5. Run in the terminal
`xdg-open slack://TRB94HEAU/magic-login...`

**Comment by dunnl** [comment] 2022-10-07 18:49
I'm still having issues with Slack and its URLs. I'm on Nixos 22.05
```
>nixos-version
22.05.2568.9b9f4bb4e11 (Quokka)
```

and Slack installed with `nix-env -iA nixos.slack` doesn't reliably handle magic links. I'm trying to open `slack://` URLs from Chrome, which is calling `xdg-open`. Running `slack` from a shell shows that Slack is in fact getting the message. I see
```
[10/07/22, 14:32:18:847] info: Store: HANDLE_DEEP_LINK {
  "url": "slack://t01165hkflk/magic-login/<my magic login hash>"
} 
```
However, nothing is happening in Slack's GUI. This behavior does not change when I install Slack system-wide. My DE is Plasma if that makes any difference. (Hard for me to tell with this sort of thing.)

**Comment by CMCDragonkai** [comment] 2022-12-01 01:13
Confirming this is broken now on 22.05.

**Comment by CMCDragonkai** [comment] 2022-12-01 01:16
This was the work around: https://github.com/NixOS/nixpkgs/issues/18791#issuecomment-1193952677

Although I couldn't edit my xdg-open, it was readonly. I had to create a separate xdg-open script and make it ahead on the `$PATH`.

**Comment by SebTM** [comment] 2023-01-25 22:23
I retested the described behavior and can't confirm it on unstable, is the issue still present for you and can you provide more information please? :)

**Comment by dunnl** [comment] 2023-02-02 17:54
I now get the desired behavior (I can log in to Slack from via the web browser) with
```
>nixos-version
22.05.4690.08741686397 (Quokka)
```

**Comment by SebTM** [comment] 2023-02-02 17:59
I would wait a little more and then close the issue as solved then if no one raises issues ✌🏻

**Comment by basile-henry** [comment] 2023-02-13 10:10
I have the same issue, slack sees the magic link from `xdg-open` (both manually run and from chrome) but doesn't seem to do anything with it:

```
[02/13/23, 11:04:52:998] info: Store: HANDLE_DEEP_LINK {
  "url": "slack://<some-hash>/magic-login/<my magic link login hash>"
}
```

I have tried to update all my nix-channels and upgrade everything. I have tried to use slack both from nixpkgs 22.11 and unstable. I usually have slack installed via home-manager but I also tried installing it at the NixOS system level.

Here is the most recent version (unstable) I tried (that still didn't work):

```bash
❯ slack --version
4.29.149

❯ nixos-version
22.11.2523.1b82144edfc (Raccoon)
```

**Comment by SebTM** [comment] 2023-02-13 14:37
@basile-henry Which desktop-environment/window-manager are you using? Can't reproduce on the same slack-version on nixos `23.05.20230212.dirty (Stoat)` (unstable)

**Comment by basile-henry** [comment] 2023-02-13 15:14
I'm using KDE/plasma. Do you think I should try unstable for NixOS itself, not just for slack?

**Comment by basile-henry** [comment] 2023-02-13 15:32
I have just clicked on "forget my workspaces" in slack and then tried to sign in from scratch and while it was quite slow it did actually work. So maybe my specific issue was unrelated to this :man_shrugging:

**Comment by SebTM** [comment] 2023-02-13 15:41
> I'm using KDE/plasma. Do you think I should try unstable for NixOS itself, not just for slack?

I would generally not recommend switching to unstable for your system just for that :v:

> I have just clicked on "forget my workspaces" in slack and then tried to sign in from scratch and while it was quite slow it did actually work. So maybe my specific issue was unrelated to this man_shrugging

Sounds good, than let's close it and if something/someone came up we can reopen it again :v:

**Closed by SebTM** 2023-02-13 15:41 UTC
Labels: 0.kind: enhancement
