### ISSUE TITLE
fetchpatch filter out move hunks

### ISSUE THREAD

**Issue by tanshihaj** [NixOS/nixpkgs#182141] opened 2022-07-19 21:41 UTC
### Describe the bug
`fetchurl` derivation uses `lsdiff` + `filterdiff` bash magic to clear git-dependent stuff from downloaded patch. But it seems that it is filter out file move hunks as well.

### Steps To Reproduce
1. Create `shell.nix` with following content:
    ``` nix
    { pkgs ? import <nixpkgs> {} }:
      pkgs.fetchpatch {
          url = "https://github.com/Mushroom/qtbase/commit/abc52460201bc5c7603505bb187138b0c59291aa.diff";
          sha256 = "sha256-zdsKPXjyZiAdam/+Gj6htQhZ4UnGEixY408+IbVY4uo=";
      }
    ```
2. Run `nix-build shell.nix`
3. Open filtered `./result` patch and compare with the https://github.com/Mushroom/qtbase/commit/abc52460201bc5c7603505bb187138b0c59291aa.diff - there is no `a/mkspecs/macx-clang/Info.plist.app` -> `b/mkspecs/macx-clang-arm64/Info.plist.app`, `a/mkspecs/macx-clang/Info.plist.dSYM.in` -> `b/mkspecs/macx-clang-arm64/Info.plist.dSYM.in` and other hunks which moves files without changing file content.
4. !PROFIT

### Expected behavior
`fetchpatch` did not remove move hunk from patch since it can be important to build.

### Notify maintainers
@vcunat

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.2.0, macOS 12.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.6.1`
 - channels(root): `"nixpkgs"`
 - channels(zaripov-kamil): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by Artturin** [comment] 2022-07-20 19:13
Dupe of https://github.com/NixOS/nixpkgs/issues/32084

**Closed** 2022-07-20 19:13 UTC
Labels: 0.kind: bug
