### ISSUE TITLE
Package request: jdk17

### ISSUE THREAD

**Issue by VergeDX** [NixOS/nixpkgs#138273] opened 2021-09-17 12:44 UTC
**Project description**
openjdk 17 is General Availability now.

**Metadata**

* homepage URL: https://openjdk.java.net/projects/jdk/17/
* source URL: https://github.com/openjdk/jdk
* license: gpl2
* platforms: unix, linux, darwin, ...

**Comment by wamserma** [comment] 2021-09-17 15:08
Closing as duplicate of https://github.com/NixOS/nixpkgs/issues/137956

**Closed by wamserma** 2021-09-17 15:08 UTC
Labels: 0.kind: packaging request
