### ISSUE TITLE
Unfree packages are hard to discover.

### ISSUE THREAD

**Issue by TravisWhitaker** [NixOS/nixpkgs#18348] opened 2016-09-06 02:45 UTC
## Issue description
It is very difficult for the uninitiated user to find unfree packages. [The search page](http://nixos.org/nixos/packages.html) does not display them, nor does `nix-env -qa`. This is especially problematic if a user is unaware of `nixpkgs.config.allowUnfree`.

At a bare minimum the `nixpkgs.config.allowUnfree` attribute should be documented in the manual. Ideally `nix-env -qa` (and the search page, which I assume is simply an index of that program's output) would list all available packages with a note on packages that have unfree licenses, although I'm not sure how challenging this would be to implement.

### Steps to reproduce
Wonder whether or not Nix provides some unfree software X, Google Chrome for example. Notice that the [the search page](http://nixos.org/nixos/packages.html) and `nix-env qa` do not list this package. Dig through this repository and discover that there is in-fact an expression for the software. Defer to a local Nix expert to inform you of `nixpkgs.config.allowUnfree`.

## Technical details

* System: Any
* Nix version: 1.11.3
* Nixpkgs version: 16.09pre90369.202d9e2

**Comment by ericsagnes** [comment] 2016-09-06 04:29
duplicate of #17126

**Comment by domenkozar** [comment] 2016-09-06 07:13
And https://github.com/NixOS/nixpkgs/pull/5628 and https://github.com/NixOS/nix/issues/432

**Closed by domenkozar** 2016-09-06 07:13 UTC
