### ISSUE TITLE
libredirect dlopen wrapper rewrite call causes CentOS6 to fail to load libraries

### ISSUE THREAD

**Issue by d10n** [NixOS/nixpkgs#61554] opened 2019-05-15 21:32 UTC
## Issue description
Testing on CentOS 6.10
90f3a237eb51d7e3173f1502d468e99ff777d1b9 from #59916 adds a dlopen wrapper to libredirect.c, but the call to rewrite in the wrapper causes sublime 3 to fail to start.
This change causes sublime 3 to start, but it seems to defeat the point of the wrapper:
```diff
index dcf3a2016bc..e4c7a3fbfa9 100644
--- a/pkgs/build-support/libredirect/libredirect.c
+++ b/pkgs/build-support/libredirect/libredirect.c
@@ -171,5 +171,5 @@ void *dlopen(const char *filename, int flag)
 {
     void * (*__dlopen_real) (const char *, int) = dlsym(RTLD_NEXT, "dlopen");
     char buf[PATH_MAX];
-    return __dlopen_real(rewrite(filename, buf), flag);
+    return __dlopen_real(filename, flag);
 }
```
What should be done?

### Steps to reproduce
Unfortunately long:
1. Install CentOS 6.10 in a VM
2. Install nix (disable sandbox)
3. `nix-env -f https://github.com/NixOS/nixpkgs/archive/90f3a237eb51d7e3173f1502d468e99ff777d1b9.tar.gz -iA sublime3`
4. `subl`
    sublime does not open and produces output like below:
    ```
    % subl                                                                                                            
    Unable to load cairo_clip from libcairo.so
    Unable to load cairo_create from libcairo.so
    Unable to load cairo_destroy from libcairo.so
    Unable to load cairo_fill from libcairo.so
    Unable to load cairo_font_options_create from libcairo.so
    [...]
    ```

The previous commit works:
1. `nix-env -f https://github.com/NixOS/nixpkgs/archive/cd8697da9fe25604a5379274f347ce37526670c5.tar.gz -iA sublime3`
2. `subl`
    (sublime opens)

## Technical details

```
% nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 2.6.32-754.12.1.el6.x86_64`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.1`
 - channels(dev): `"nixpkgs-19.09pre173445.796a8764ab8"`
 - nixpkgs: `/home/me/.nix-defexpr/channels/nixpkgs`
```

cc @jtojnar

**Comment by jtojnar** [comment] 2019-05-15 21:53
Duplicate of https://github.com/NixOS/nixpkgs/issues/60807

**Closed by jtojnar** 2019-05-15 21:53 UTC

**Comment by d10n** [comment] 2019-05-15 22:08
Thanks, sorry!
