### ISSUE TITLE
qtcreator cannot start in rhel9 by nix

### ISSUE THREAD

**Issue by cathaysia** [NixOS/nixpkgs#195615] opened 2022-10-12 03:52 UTC
### Describe the bug

I install nix on rhel9, and run qtcreator by:

> nix-shell -p qt5Full qtcreator --run qtcreator --pure

then qtcreator core dumped: 

```
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Could not initialize GLX
/tmp/nix-shell-25019-0/rc: line 3: 27562 Aborted                 (core dumped) qtcreator
```
I know I can make it work by set QT_XCB_GL_INTEGRATION=none, but in this way, QmlDesign and QmlProfiler plugin cannot work. Did there has a better way?

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.0-70.26.1.el9_0.x86_64, Red Hat Enterprise Linux, 9.0 (Plow), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(tea): `"nixpkgs-22.05"`
 - nixpkgs: `/home/tea/.nix-defexpr/channels/nixpkgs`
```

notes: 

- Dell Inc. Dell G15 5511
- 11th Gen Intel® Core™ i7-11800H @ 2.30GHz × 16 
- NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] / Mesa Intel® UHD Graphics (TGL GT1)

**Comment by veprbl** [comment] 2022-10-14 23:11
Duplicate of #9415 and others

**Closed** 2022-10-18 04:13 UTC
Labels: 0.kind: bug, 6.topic: qt/kde, 6.topic: non-nixos
