### ISSUE TITLE
dnsmasq doesn't answer DHCP requests

### ISSUE THREAD

**Issue by globin** [NixOS/nixpkgs#8967] opened 2015-07-23 22:50 UTC
dnsmasq doesn't answer any DHCP requests when running as a NixOS service.

/cc @fpletz

**Comment by fpletz** [comment] 2015-08-04 14:05
When using isc-dhcp-server (attribute name `dhcp` ) instead, it just works. I have only tested this on a bridge with LXC containers. The dhcp requests show up in tcpdump when dumping the traffic of the bridge from the host but never make it to dnsmasq (checked with strace), even though it is listening on port 67 UDP.

Using a dedicated LXC container with Ubuntu trusty that just does DHCP with dnsmasq on the same bridge, it works, so it has to be related to NixOS. Disabling the firewall doesn't help.

**Comment by globin** [comment] 2015-09-27 21:02
Caused by #10101

**Comment by rasendubi** [comment] 2016-07-26 19:30
(triage) close as duplicate of #10101

**Comment by fpletz** [comment] 2016-08-16 18:55
Fixed in #17325.

**Closed by fpletz** 2016-08-16 18:55 UTC
Labels: 6.topic: nixos
