### ISSUE TITLE
Package request: Komorebi

### ISSUE THREAD

**Issue by Froztmuffins** [NixOS/nixpkgs#242410] opened 2023-07-09 04:12 UTC
**Project description**
Komorebi is an awesome animated wallpapers manager for all Linux platforms

Komorebi is an awesome animated wallpapers manager for all Linux platforms
**Metadata**

* homepage URL:
* source URL:https://github.com/cheesecakeufo/komorebi
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by kaleocheng** [comment] 2023-07-11 11:29
duplicate of https://github.com/NixOS/nixpkgs/issues/190814

**Closed** 2023-07-15 12:56 UTC
Labels: 0.kind: packaging request
