### ISSUE TITLE
Clangd issues with clang and clang-tools package.

### ISSUE THREAD

**Issue by ErinaInit** [NixOS/nixpkgs#308482] opened 2024-05-02 09:57 UTC
### Describe the bug
I'm developing a cpp project and I have some fuzz with clangd.

### Steps To Reproduce
1. Here's my devshell flake:
```
                  packages = with pkgs; [
                    clang
                    clang-tools
                    cmake
                    cmakeCurses
                    xorg.libX11
                    xorg.libXi
                    boost
                  ];

```
2. Go into the shell and find clangd, which resides in /nix/store/bcjr80nk9cxy2bwhmz8pdl7zxd30mxba-clang-17.0.6/bin/clangd
as a binary file. And it does failed to find the libraries.

### Expected behavior
Clangd should come from clang-tools instead and be a script, residing in /nix/store/brxm6ld0k4ipciq4rmh013p48mvqmj8r-clang-tools-17.0.6/bin/clangd

### Screenshots
![test](https://github.com/NixOS/nixpkgs/assets/161044739/7e5a02d9-34b1-4825-a6c1-85f1db7dc7ba)
![test](https://github.com/NixOS/nixpkgs/assets/161044739/8961fe36-c749-42c3-8da5-1ec184d9f9ec)

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.28, NixOS, 24.05 (Uakari), 24.05.20240427.58a1abd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/801l7gvdz7yaibhjsxqx82sc7zkakjbq-source`
```

**Comment by ErinaInit** [comment] 2024-05-02 12:10
This worked. I wonder if we should fix this though.

**Comment by deng232** [comment] 2024-08-23 23:08
nothing work in ```nix-shell```

**Comment by deng232** [comment] 2024-08-24 02:08
```direnv``` however, make ```nix-shell``` work. This things is breaking the deterministic build system idea. hope it will be fix someday.

**Comment by Patryk27** [comment] 2024-11-09 12:38
Status: duplicate of https://github.com/NixOS/nixpkgs/issues/76486.

**Closed by Patryk27** 2024-11-09 12:38 UTC
Labels: 0.kind: bug
