### ISSUE TITLE
Build failure: `cargo-update` (macOS)

### ISSUE THREAD

**Issue by poliorcetics** [NixOS/nixpkgs#288053] opened 2024-02-11 14:54 UTC
### Steps To Reproduce

1. `nix-shell -p cargo-update` **on macOS**

### Build log

```
  1) Failure:
network::url::parse::hostname_implied_root_empty_port [/tmp/nix-build-libgit2-1.5.1.drv-0/source/tests/libgit2/network/url/parse.c:68]
  Function call failed: (git_net_url_parse(&conndata, "http://example.com:"))
  error -12 - malformed URL 'http://example.com:'

  2) Failure:
network::url::parse::hostname_empty_port [/tmp/nix-build-libgit2-1.5.1.drv-0/source/tests/libgit2/network/url/parse.c:134]
  Function call failed: (git_net_url_parse(&conndata, "http://example.com:/resource"))
  error -12 - malformed URL 'http://example.com:/resource'

  3) Failure:
network::url::parse::ipv4_implied_root_empty_port [/tmp/nix-build-libgit2-1.5.1.drv-0/source/tests/libgit2/network/url/parse.c:224]
  Function call failed: (git_net_url_parse(&conndata, "http://192.168.1.1:"))
  error -12 - malformed URL 'http://192.168.1.1:'

  4) Failure:
network::url::parse::ipv4_empty_port [/tmp/nix-build-libgit2-1.5.1.drv-0/source/tests/libgit2/network/url/parse.c:288]
  Function call failed: (git_net_url_parse(&conndata, "http://192.168.1.1:/resource"))
  error -12 - malformed URL 'http://192.168.1.1:/resource'

  5) Failure:
network::url::parse::ipv6_implied_root_empty_port [/tmp/nix-build-libgit2-1.5.1.drv-0/source/tests/libgit2/network/url/parse.c:376]
  Function call failed: (git_net_url_parse(&conndata, "http://[fe80::dcad:beff:fe00:0001]:"))
  error -12 - malformed URL 'http://[fe80::dcad:beff:fe00:0001]:'

  6) Failure:
network::url::parse::ipv6_empty_port [/tmp/nix-build-libgit2-1.5.1.drv-0/source/tests/libgit2/network/url/parse.c:440]
  Function call failed: (git_net_url_parse(&conndata, "http://[fe80::dcad:beff:fe00:0001]:/resource"))
  error -12 - malformed URL 'http://[fe80::dcad:beff:fe00:0001]:/resource'

error: builder for '/nix/store/jjqxgs8nx2nwmidn406cv0lmjzvsbahc-libgit2-1.5.1.drv' failed with exit code 6;
       last 10 log lines:
       >   5) Failure:
       > network::url::parse::ipv6_implied_root_empty_port [/tmp/nix-build-libgit2-1.5.1.drv-0/source/tests/libgit2/network/url/parse.c:376]
       >   Function call failed: (git_net_url_parse(&conndata, "http://[fe80::dcad:beff:fe00:0001]:"))
       >   error -12 - malformed URL 'http://[fe80::dcad:beff:fe00:0001]:'
       >
       >   6) Failure:
       > network::url::parse::ipv6_empty_port [/tmp/nix-build-libgit2-1.5.1.drv-0/source/tests/libgit2/network/url/parse.c:440]
       >   Function call failed: (git_net_url_parse(&conndata, "http://[fe80::dcad:beff:fe00:0001]:/resource"))
       >   error -12 - malformed URL 'http://[fe80::dcad:beff:fe00:0001]:/resource'
       >
       For full logs, run 'nix-store -l /nix/store/jjqxgs8nx2nwmidn406cv0lmjzvsbahc-libgit2-1.5.1.drv'.
error: 1 dependencies of derivation '/nix/store/xnvgzr7xb57zv71wjp1ni352i9rcvj79-cargo-update-13.3.0.drv' failed to build
```

### Additional context

I don't have the issue when I do `nix-shell -p libgit2`.

Initially I saw it by trying to add `cargo-update` to my home-manager config. I thought something like `pkgs.cargo-update.override { doInstallCheck = false; }` would fix it but it hasn't (and it's already `false` by default on macOS anyway)

### Notify maintainers

@gerschtli @Br1ght0ne @johntitor @matthiasbeyer

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.3.0, macOS 14.3`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/Users/alexis/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bbigras** [comment] 2024-02-13 02:49
related to #288064

**Comment by SuperSandro2000** [comment] 2024-02-16 23:21
dupe of #288064

**Closed by SuperSandro2000** 2024-02-16 23:21 UTC
Labels: 6.topic: darwin, 0.kind: build failure
