### ISSUE TITLE
OrganicMaps shows only black screen

### ISSUE THREAD

**Issue by sleirsgoevy** [NixOS/nixpkgs#331344] opened 2024-07-31 17:55 UTC
## Issue description

The OrganicMaps app only shows a black screen if llvmpipe driver is forced using LIBGL_ALWAYS_SOFTWARE=1, the map is not displayed. The Flathub version of OrganicMaps works fine.

### Steps to reproduce

`nix-shell -p organicmaps --run 'LIBGL_ALWAYS_SOFTWARE=1 OMaps'`

Then confirm the open-source notice and download any region, and the broken map view will open.

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32, NixOS, 24.05 (Uakari), 24.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by sleirsgoevy** [comment] 2024-07-31 20:28
Seems to be an upstream issue: https://github.com/organicmaps/organicmaps/issues/7838

**Comment by biodranik** [comment] 2024-07-31 21:53
What's your QT version?

**Comment by rnhmjoj** [comment] 2024-08-01 07:26
Yes, the organic-maps has been broken by the [update to Qt 6.7](https://github.com/NixOS/nixpkgs/commit/2c35581d1df90df767241f03236b9790b0dfa6ae).
In Nixpkgs we only keep a single Qt version per minor release and organic-maps doesn't build against Qt 5 anymore, so it's up to upstream to [fix it](https://github.com/organicmaps/organicmaps/issues/7838).

Until then you can install an older version. Note there is a very narrow window where organic-maps was actually working in Nixpkgs because before it was broken by https://github.com/organicmaps/organicmaps/pull/5823, which was fixed in https://github.com/organicmaps/organicmaps/pull/7485 but soon later Qt 6.7 rolled in.

For example, this [build](https://hydra.nixos.org/build/255650264) is working. You can install it as follows:
```
$ nix-env -i /nix/store/1fgqik698pqg2pq756zqqfbi8xaak3i1-organicmaps-2024.03.31-8 --option binary-caches https://cache.nixos.org
```

**Comment by fgaz** [comment] 2024-11-22 17:38
Looks like it's starting to affect other packages https://github.com/flathub/app.organicmaps.desktop/issues/83

Hopefully this will get the issue some attention

**Comment by fgaz** [comment] 2024-11-22 17:40
Also let's reopen this. The fact that we are waiting for upstream doesn't mean the issue is fixed

**Closed** 2024-12-11 20:11 UTC
Labels: 9.needs: upstream fix
