### ISSUE TITLE
perl failing to build on os x

### ISSUE THREAD

**Issue by mmerickel** [NixOS/nixpkgs#9783] opened 2015-09-10 23:07 UTC
I just installed nix 1.10 and tried to run `nix-shell -p python27` on OS X 10.10.5. It looks like perl expecting a version of the `find` command that doesn't work on os x. Is there a workaround?

```
...
strip: can't process non-object and non-archive file: /nix/store/fj08s8j4dfpiz7dyi90cs713dwg82n8v-perl-5.20.2/bin/ptardiff
strip: can't process non-object and non-archive file: /nix/store/fj08s8j4dfpiz7dyi90cs713dwg82n8v-perl-5.20.2/bin/ptargrep
strip: can't process non-object and non-archive file: /nix/store/fj08s8j4dfpiz7dyi90cs713dwg82n8v-perl-5.20.2/bin/s2p
strip: can't process non-object and non-archive file: /nix/store/fj08s8j4dfpiz7dyi90cs713dwg82n8v-perl-5.20.2/bin/shasum
strip: can't process non-object and non-archive file: /nix/store/fj08s8j4dfpiz7dyi90cs713dwg82n8v-perl-5.20.2/bin/splain
strip: can't process non-object and non-archive file: /nix/store/fj08s8j4dfpiz7dyi90cs713dwg82n8v-perl-5.20.2/bin/xsubpp
strip: can't process non-object and non-archive file: /nix/store/fj08s8j4dfpiz7dyi90cs713dwg82n8v-perl-5.20.2/bin/zipdetails
patching script interpreter paths in /nix/store/fj08s8j4dfpiz7dyi90cs713dwg82n8v-perl-5.20.2
find: -perm: /0100: illegal mode string
builder for ‘/nix/store/v16mzzb4dajbj3d13f5fl9sdy1b3ds4i-perl-5.20.2.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/qrajznbph77yw7ishi9nvkwd7p95qjqf-openssl-1.0.1p.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/ry1xfxg5rm02caqzszjidqrgvzhp75hg-zlib-1.2.8’
killing process 63435
cannot build derivation ‘/nix/store/6bj1h78vlx4zrjdaadj9wvyg5c6jmd0m-curl-7.43.0.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/k207hrhnrks9ivfa8nsmhv3anlw8w6a0-sed-4.2.2.tar.bz2.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/2rxp8yj0mjf0wwpvp3hdi5bs0n94amhh-xz-5.2.1.tar.bz2.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/gfbnb9s14xq6f77m8gimknml5kdybllj-gnused-4.2.2.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/6gjvcw8f6sf6kal1zf06jh1z5ygg78dh-xz-5.2.1.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/3fvwri55235nqj14xszi756rlbqp7vpx-stdenv-darwin-boot-2.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/77sz7kg2x2aq67d9yskyy7mliifjsqif-bash-4.3-p39.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/77sz7kg2x2aq67d9yskyy7mliifjsqif-bash-4.3-p39.drv’ failed
/Users/michael/.nix-profile/bin/nix-shell: failed to build all dependencies
```

**Comment by edolstra** [comment] 2015-09-11 06:54
Dupe of #9044.

**Closed by edolstra** 2015-09-11 06:54 UTC
