### ISSUE TITLE
sage: ships it's own curl with no SSL support

### ISSUE THREAD

**Issue by Meizikyn** [NixOS/nixpkgs#41955] opened 2018-06-14 03:24 UTC
Found out `sage` i.e. SageMath comes with it's own `curl` binary that is compiled without ssl support, instead of linking the system `curl` as a dependency. 

having sagemath installed into the system and/or profile causes all other applications that call it from `PATH` to fail when accessing an https address.

original post:
```
curl/libcurl/git lacks SSL support
i.e. curl: option --ssl: the installed libcurl version doesn't support this

curl is no longer compiled with SSL support from nix binary cache
```

**Comment by Meizikyn** [comment] 2018-06-14 16:29
Cracked open curl/default.nix expression and found "sslSupport ? false"
attempted nix-env -iA nixos.curl --arg sslSupport true

Same problem occurs, am I using this incorrectly?

**Comment by matthewbauer** [comment] 2018-06-14 19:11
Duplicate of https://github.com/NixOS/nixpkgs/issues/38777.

**Closed by matthewbauer** 2018-06-14 19:11 UTC
