### ISSUE TITLE
Genymotion - does not work with QEMU

### ISSUE THREAD

**Issue by rastarr** [NixOS/nixpkgs#308396] opened 2024-05-02 00:03 UTC
### Describe the bug

I used Genymotion for a long time on macOS but with Virtualbox.
I switch to Linux/nixOS about 5 months ago and was pleasantly surprised to read Genymotion now supported the QEMU engine.

Alas, myself and a few other of my friends were never able to get Genymotion to work using QEMU, which is the preferred Hypervisor.

I've tried to source some help at https://discourse.nixos.org/t/anyone-got-waydroid-or-genymotion-working/44397/12 but to no avail.

### Steps To Reproduce
1. Have a running working QEMU installation. Presumably with at least 1 functional VM too
2. Install Genymotion
3. Setup Genymotion, ensure QEMU is selected as the Hypervisor
4. Select a random Android device, add it and run it.
5. You'll first get a 'can't start virtual device' error
6. Manually trying to start the Android device again gives a 'Another QEMU process appears to be using the same resources' error

### Expected behavior
I'd expect Genymotion to start the Android device using QEMU, naturally

### Notify maintainers

@puffnfresh 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

``` - system: `"x86_64-linux"`
 - host os: `Linux 6.7.12, NixOS, 24.05 (Uakari), 24.05.20240403.fd281bd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/n2g5cqwv8qf5p6vjxny6pg3blbdij12k-source`
```


---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
![no-start](https://github.com/NixOS/nixpkgs/assets/2160922/1c2be4d3-5103-4b3b-ace8-57e4a96a6cc8)
![geny-qemu](https://github.com/NixOS/nixpkgs/assets/2160922/09821288-f74b-47fe-bb67-661cec3c3df6)
[genymotion-player.log](https://github.com/NixOS/nixpkgs/files/15182367/genymotion-player.log)
[genymotion.log](https://github.com/NixOS/nixpkgs/files/15182368/genymotion.log)
[qemu.log](https://github.com/NixOS/nixpkgs/files/15182369/qemu.log)

**Comment by rastarr** [comment] 2024-05-02 00:05
[genymotion-player.log](https://github.com/NixOS/nixpkgs/files/15182377/genymotion-player.log)
[genymotion.log](https://github.com/NixOS/nixpkgs/files/15182378/genymotion.log)
[qemu.log](https://github.com/NixOS/nixpkgs/files/15182379/qemu.log)
![geny-qemu](https://github.com/NixOS/nixpkgs/assets/2160922/69410e1f-3eba-4845-9796-e7a663d14282)
![no-start](https://github.com/NixOS/nixpkgs/assets/2160922/b00b3c81-8e10-4e9f-a4ad-41d896fc9710)

**Comment by wegank** [comment] 2024-05-02 07:32
Duplicate of #226867.

**Comment by rastarr** [comment] 2024-05-03 03:27
@wegank I'm not really sure this is a duplicate but that's up to you.
I'm not a coder so had no idea what to do with that old 'work-around' either. I had a colleague who kindly looked at it, spent some time, and turned it in to a flake which can be found at https://github.com/fillon/nix-genymotion

And now the broken Genymotion functions great with QEMU.

Perhaps the flake code can help in fixing the package.
Thanks for the pointer to the old work-around

**Closed** 2024-05-03 18:47 UTC
Labels: 0.kind: bug
