### ISSUE TITLE
Pleroma

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#39479] opened 2018-04-25 12:33 UTC
As @erictapen suggested in https://github.com/NixOS/nixpkgs/issues/24600, it might be easier to write a nixpkg for Pleroma than it has proven to be for Mastodon.

As I need to get Pleroma on my VPS running NixOS as soon as possible, I'm willing to try and write the nixpkg myself.

I still have an awful lot to learn about NixOS so I'm definitely going to ask many questions, a good share of which might be really stupid, and my PR will probably need some tough reviewing.

どうぞよろしくお願いします。

**Comment by jpotier** [comment] 2018-04-25 13:32
Count me in for review

**Comment by s4sha** [comment] 2018-05-02 06:34
A little update : I got pleroma running on our VPS but I had to do things quick and dirty so I haven't manage to package pleroma yet. I've just updated my branch to follow master and will keep trying to make a package with the knowledge I got in the process.

**Comment by andir** [comment] 2018-06-25 06:51
It's a shame that branch did disappear now that the user is gone. Anyone got a link to that? I'd like to attempt packaging it for NixOS. At first just for myself to see how and what (never used elixir before). Finally I'd want to have a NixOS module for it.

If there are multiple people interested in working on this we could probably try to build an overlay (once we got something substantial).

**Comment by brainrape** [comment] 2018-09-03 18:05
Can we close this until someone opens a PR?

**Comment by erictapen** [comment] 2018-09-03 18:31
I'd think it would make sense to close it. Haven't heard of any progress in a while.

**Comment by andir** [comment] 2018-09-03 23:29
I have a rough version somewhere.. it wasn't done yet but I intend to follow up on this. We can close it but is there really a difference?

**Comment by barrucadu** [comment] 2018-09-21 22:13
@andir If you have it available, could you share your rough version?

**Comment by Moredread** [comment] 2019-03-24 23:11
@andir do you still have it?

**Comment by andir** [comment] 2019-03-25 14:38
No, sorry. I check for that a while ago but never reported back. I tried regenerating what I did manually back then but failed with the current tooling :/

**Comment by fgaz** [comment] 2021-02-24 10:03
Still interested

**Comment by happysalada** [comment] 2021-05-29 01:18
@fgaz there is a pleroma option on nixos. Are you looking for something else?

**Comment by fgaz** [comment] 2021-05-29 09:03
That's it, thanks! Duplicate of #62820, fixed in #103138.

**Closed by fgaz** 2021-05-29 09:03 UTC
Labels: 9.needs: package (new)
