### ISSUE TITLE
NixOS on ARM documentation

### ISSUE THREAD

**Issue by dhess** [NixOS/nixpkgs#25653] opened 2017-05-09 19:02 UTC
Now that the wiki has been shut down, there is no official or semi-official source for NixOS on ARM documentation. Previously, the wiki was the best (only?) source:

https://nixos.org/wiki/NixOS_on_ARM

The best we have for now is archive.org, though the last capture was Sept 11 2016, so I'm not sure if anything changed between then and the shutdown time:

https://web.archive.org/web/20160911022116/https://nixos.org/wiki/NixOS_on_ARM

Anyway, now that the wiki is gone, this critical information should be added to the NixOS manual as soon as it's feasible. In the meantime, since support for the platform is still somewhat experimental (esp. for `aarch64`), perhaps we can use GitHub Issues as a documentation dump.

/cc @dezgeg

**Comment by Mic92** [comment] 2017-05-09 19:06
duplicate of: https://github.com/NixOS/nixpkgs/issues/13290

**Comment by dhess** [comment] 2017-05-09 19:14
Is it a dupe? That issue refers explicitly to the wiki, and as such I would expect all such issues to be closed soon. This issue should track the adding of the ARM documentation to the manual.

**Comment by vcunat** [comment] 2017-05-09 19:31
Yes, every wiki page has had a ticket open for a long time, but reviewing and migrating the content doesn't seem very popular thing todo.  Let's concentrate the information in a single thread.

**Closed by vcunat** 2017-05-09 19:31 UTC
Labels: 2.status: duplicate
