### ISSUE TITLE
fetchurl failing if chosen mirror fails

### ISSUE THREAD

**Issue by noonien** [NixOS/nixpkgs#55395] opened 2019-02-07 15:32 UTC
## Issue description
When downloading something using fetchurl with a mirror:// url, if the selected mirror is down, no other mirrors are tried.

### Steps to reproduce
I tried installing the `steam` package, however, one of the mirrors, `https://abbradar.net` appears to be down, which resulted in the build failing.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.97, NixOS, 18.09.2108.8008d0bbc69 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2108.8008d0bbc69, nixos-unstable-19.03pre167858.f2a1a4e93be"`
 - channels(george): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by noonien** [comment] 2019-02-07 18:29
It appears I was mistaken, the first mirror seems to be tried first, which fails, then the second, and only one left, fails as well.

The actual bug is #55274, solved by #55269.

**Comment by pSub** [comment] 2019-02-07 20:23
Closing as a duplicate of #55274.

**Closed by pSub** 2019-02-07 20:23 UTC
