### ISSUE TITLE
gcc5 and gcc6 cannot compile static binaries: undefined reference to __memcpy_chk

### ISSUE THREAD

**Issue by djhshih** [NixOS/nixpkgs#21630] opened 2017-01-04 03:37 UTC
## Issue description

I tried to build a static executable within a `nix-shell` using glibc-2.24-static and either `gcc-5.4.0` or `gcc-6.3.0` from `nixpkgs`. In either case, I get a compile error due to undefined reference to __memcpy_chk. The vanilla `memcpy` is correctly linked. I tried turning off `SOURCE_FORTIFY` but `nixpkgs.gcc` did not comply.

The same build scripts works as expected on Archlinux with the system's `glibc-2.24-static` (or `nixpkgs`' `glibc-2.24-static`) and the system's `gcc-6.2.1`. The scripts also works as expected on CentOS with `nixpkgs`' `glibc-2.24-static` with the system's `gcc-4.4.1` inside a `nix-shell`.

So there appears to be two problems

1. `nixpkgs.gcc5` and `nixpkgs.gcc6` cannot have fortify disabled
2. `nixpkgs.glibc.static` is missing `__memcpy_chk` ( I found a possibly [related fix for glibc-2.22]( https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=132a1328eccd20621b77f7810eebbeec0a1af187), but I am not sure why `nixpkgs`' `glibc-2.24-static` still has a similar problem. )

### Steps to reproduce

A minimum example is available at https://github.com/djhshih/glibc-memcpy-chk-bug

```
$ git clone https://github.com/djhshih/glibc-memcpy-chk-bug memcpy
$ cd memcpy
```
```
$ nix-shell default.nix 
```
```
[nix-shell]$  make memcpy-static
gcc -static -o memcpy-static memcpy.c
/run/user/1000/ccrBBIcE.o: In function `main':
memcpy.c:(.text.startup+0x64): undefined reference to `__memcpy_chk'
collect2: error: ld returned 1 exit status
make: *** [Makefile:24: memcpy-static] Error 1
```
```
[nix-shell]$  make memcpy-static-nofort
gcc -static -D_FORTIFY_SOURCE=0 -fno-stack-protector -o memcpy-static-nofort memcpy.c
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined
<command-line>:0:0: note: this is the location of the previous definition
/run/user/1000/ccuefIWF.o: In function `main':
memcpy.c:(.text.startup+0x64): undefined reference to `__memcpy_chk'
collect2: error: ld returned 1 exit status
make: *** [Makefile:30: memcpy-static-nofort] Error 1
```

Despite `-D_FORTIFY_SOURCE=0`, `memcpy-nofort` (dynamic build) is linked to `__memcpy_chk` instead of `memcpy`:

```
[nix-shell]$  make
[nix-shell]$  make check
# dynamic link
nm memcpy | grep memcpy
                 U memcpy@@GLIBC_2.14
nm memcpy-fort | grep memcpy
                 U __memcpy_chk@@GLIBC_2.3.4
nm memcpy-nofort | grep memcpy
                 U __memcpy_chk@@GLIBC_2.3.4
# static link
nm memcpy-static | grep memcpy
nm: 'memcpy-static': No such file
make: *** [Makefile:10: check] Error 1
```

On both CentOS and Archlinux with `gcc-4.4.1` or `gcc-6.2.1`, the build scripts compile successfully and the fortify flag is honoured:

```
[nix-shell]$  make
[nix-shell]$  make check
# dynamic link
nm memcpy | grep memcpy
                 U memcpy@@GLIBC_2.14
nm memcpy-fort | grep memcpy
                 U __memcpy_chk@@GLIBC_2.3.4
nm memcpy-nofort | grep memcpy
                 U memcpy@@GLIBC_2.14
# static link
nm memcpy-static | grep memcpy
000000000041a5d0 T memcpy
000000000045d2d0 W wmemcpy
000000000045d2d0 T __wmemcpy
nm memcpy-static-fort | grep memcpy	
000000000041a470 T memcpy
0000000000434ce0 T __memcpy_chk
000000000045d350 W wmemcpy
000000000045d350 T __wmemcpy
nm memcpy-static-nofort | grep memcpy
000000000041a5d0 T memcpy
000000000045d2d0 W wmemcpy
000000000045d2d0 T __wmemcpy
```

The same build works on either system within a `nix-shell` but using the system's `gcc` at `/usr/bin/gcc`.
However, the static build fails when I turned on fortify:

```
[nix-shell]$ CC=/usr/bin/gcc make
/usr/bin/gcc -o memcpy memcpy.c
/usr/bin/gcc -O2 -D_FORTIFY_SOURCE=2 -o memcpy-fort memcpy.c
/usr/bin/gcc -D_FORTIFY_SOURCE=0 -fno-stack-protector -o memcpy-nofort memcpy.c
/usr/bin/gcc -static -o memcpy-static memcpy.c
/usr/bin/gcc -O2 -static -D_FORTIFY_SOURCE=2 -o memcpy-static-fort memcpy.c
/tmp/ccpz2oDo.o: In function `main':
memcpy.c:(.text+0x5c): undefined reference to `__memcpy_chk'
collect2: ld returned 1 exit status
make: *** [Makefile:29: memcpy-static-fort] Error 1
```

```
[nix-shell]$ CC=/usr/bin/gcc make check
# dynamic link
nm memcpy | grep memcpy
                 U memcpy@@GLIBC_2.2.5
nm memcpy-fort | grep memcpy
                 U __memcpy_chk@@GLIBC_2.3.4
nm memcpy-nofort | grep memcpy
                 U memcpy@@GLIBC_2.2.5
# static link
nm memcpy-static | grep memcpy
000000000045e1e0 T __wmemcpy
000000000041ab00 T memcpy
000000000045e1e0 W wmemcpy
nm memcpy-static-fort | grep memcpy
nm: 'memcpy-static-fort': No such file
make: *** [Makefile:13: check] Error 1
```

I confirmed that dynamically linked binaries are linked against `nixpkgs.glibc`:
```
$ ldd memcpy
        linux-vdso.so.1 =>  (0x00007ffc617d6000)
        libc.so.6 => /nix/store/8lbpq1vmajrbnc96xhv84r87fa4wvfds-glibc-2.24/lib/libc.so.6 (0x00007fdfeff7c000)
        /lib64/ld-linux-x86-64.so.2 (0x00000034f5600000)
```

Everything works as expected using the Archlinux's or CentOS's `gcc` and `glibc` (outside `nix-shell`):
```
$ make check
# dynamic link
nm memcpy | grep memcpy
                 U memcpy@@GLIBC_2.14
nm memcpy-fort | grep memcpy
                 U __memcpy_chk@@GLIBC_2.3.4
nm memcpy-nofort | grep memcpy
                 U memcpy@@GLIBC_2.14
# static link
nm memcpy-static | grep memcpy
000000000041a5d0 T memcpy
000000000045d2d0 W wmemcpy
000000000045d2d0 T __wmemcpy
nm memcpy-static-fort | grep memcpy	
000000000041a470 T memcpy
0000000000434ce0 T __memcpy_chk
000000000045d350 W wmemcpy
000000000045d350 T __wmemcpy
nm memcpy-static-nofort | grep memcpy
000000000041a5d0 T memcpy
000000000045d2d0 W wmemcpy
000000000045d2d0 T __wmemcpy

$ which gcc
/usr/bin/gcc

$ gcc --version
gcc (GCC) 6.2.1 20160830
```

## Technical details

* System: `nix-shell` within CentOS6 and Archlinux 
```
CentOS uname -a: Linux box1 2.6.32-642.6.2.el6.x86_64 #1 SMP Mon Oct 24 10:22:33 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
Archlinux uname -a: Linux box2 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
```
* Nix version: 1.11.4

* Nixpkgs version: 17.03pre98135.3ac20e9

**Comment by joachifm** [comment] 2017-01-06 21:01
This might be another instance of https://github.com/NixOS/nixpkgs/issues/18995. The cc wrapper expects `hardeningDisable = [ "fortify" ]`. Invoking cc from the cmdline would require you to set `hardeningDisable="fortify"` or somesuch, I think.

**Comment by djhshih** [comment] 2017-01-06 21:41
Thanks for the pointer.

Based on #18995, I confirmed that adding the disable hardening flag in the init script for `nix-shell`:
```
hardeningDisable = [ "all" ];
```
resolves problem 1: nixpkgs.gcc5 and nixpkgs.gcc6 cannot have fortify disabled.

But problem 2 still persists: nixpkgs.glibc.static is missing __memcpy_chk

In the example I gave, I can now compile `memcpy-static` and `memcpy-static-nofort` but not `memcpy-static-fort`:

```
$ git clone https://github.com/djhshih/glibc-memcpy-chk-bug memcpy
$ cd memcpy
$ nix-shell default.nix 
```

```
[nix-shell]$ make memcpy-static-fort
gcc -O2 -static -D_FORTIFY_SOURCE=2 -o memcpy-static-fort memcpy.c
/tmp/cc4Z3WfB.o: In function `main':
memcpy.c:(.text.startup+0x4c): undefined reference to `__memcpy_chk'
collect2: error: ld returned 1 exit status
make: *** [Makefile:29: memcpy-static-fort] Error 1
```

According to [this note](https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=132a1328eccd20621b77f7810eebbeec0a1af187), the undefined reference to `__memcpy_chk` problem in glibc should have been fixed in `glibc-2.22`, but `nixpkgs`' `glibc-2.24-static` still has this problem, while `glibc-2.24` from Archlinux does not ... Could it have something to do with one of the patches that Nix applies to `glibc-2.24`?

**Comment by cstrahan** [comment] 2017-07-24 00:47
@djhshih You aren't still having trouble with this, are you?

With a recent checkout of nixpkgs, this is what I get:

```
$ make check
# dynamic link
nm memcpy | grep memcpy
                 U memcpy@@GLIBC_2.14
nm memcpy-fort | grep memcpy
                 U __memcpy_chk@@GLIBC_2.3.4
nm memcpy-nofort | grep memcpy
                 U memcpy@@GLIBC_2.14
# static link
nm memcpy-static | grep memcpy
000000000041a970 T memcpy
000000000045e400 W wmemcpy
000000000045e400 T __wmemcpy
nm memcpy-static-fort | grep memcpy
000000000041a800 T memcpy
00000000004353c0 T __memcpy_chk
000000000045e490 W wmemcpy
000000000045e490 T __wmemcpy
nm memcpy-static-nofort | grep memcpy
000000000041a970 T memcpy
000000000045e400 W wmemcpy
000000000045e400 T __wmemcpy
```

I'll close this issue shortly if there aren't any similar outstanding issues.

Might be interesting to bisect and see where/when things changed, but I have more pressing things to tend to... (brownie points for anyone who does this :P)

**Comment by fpletz** [comment] 2017-07-25 20:06
This is a duplicate of #18995.

**Closed by fpletz** 2017-07-25 20:06 UTC
Labels: 0.kind: bug
