### ISSUE TITLE
[HaskellNG] Document HaskellNG

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#7688] opened 2015-05-04 12:53 UTC
There is basically no documentation about haskell-ng at the moment.

What is needed:

1. In-code reasoning about how it works internally (I don’t know how much there is)
2. API- and Function Documentation (where should that go? btw. there should be a nixdocs (read: haddock for nix) soon)
3. Tutorials
    - on the wiki
    - in the language section of the nixpkgs manual

**Comment by peti** [comment] 2015-05-04 13:11
Duplicate of https://github.com/NixOS/nixpkgs/issues/4941.

**Comment by Profpatsch** [comment] 2015-05-04 13:30
@peti Superset of #4941.

**Closed** 2015-05-11 17:19 UTC
Labels: duplicate
