### ISSUE TITLE
Figuring out *where* a package is marked as broken is difficult

### ISSUE THREAD

**Issue by bgamari** [NixOS/nixpkgs#100854] opened 2020-10-17 17:56 UTC
**Describe the bug**
In 0b8799ecaaf0dc6b4c11583a3c96ca5b40fcfdfb I was faced with the following error when trying to build `elisa`:
```
$ nix run -f . elisa
error: Package ‘breeze-qt5-5.18.5’ in /opt/exp/nixpkgs/pkgs/desktops/plasma-5/default.nix:96 is marked as broken, refusing to evaluate.
```

However, nothing in `pkgs/desktops/plasma-5/breeze-qt5.nix` suggests that `breeze-qt5` is marked as broken. I looked in the "obvious" places, (e.g. `all-packages.nix`, `pkgs/desktops/plasma-5/default.nix`) yet have been utterly unable to locate the `broken` declaration in question. Presumably there is something somewhere which *does* mark it as broken. However, I haven't the slightest idea how one would find it.

**To Reproduce**
1. Try building a broken derivation
2. Encounter error
3. Try in vain to find the `broken` attribute

**Expected behavior**

The error should tell you the source location of the `broken` attribute.

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.14, NixOS, 20.09beta1057.0b8799ecaaf (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09beta1057.0b8799ecaaf, nixpkgs-20.09beta1057.0b8799ecaaf"`
 - channels(ben): `"nixpkgs-20.09beta1083.51aaa3fa1b6, nixpkgs-20_03-20.03.3122.ff6fda61600, nixpkgs-unstable-21.03pre246624.cfed29bfcb2, nixos-18.09-18.09.2574.a7e559a5504"`
 - nixpkgs: `/home/ben/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by doronbehar** [comment] 2020-10-28 14:48
Indeed that's not trivial. See:

https://github.com/NixOS/nixpkgs/blob/630f19b3ef9cebef1b85bc5c8c6e1fe2a3c6aa01/pkgs/desktops/plasma-5/default.nix#L86

And:

https://github.com/NixOS/nixpkgs/commit/575b3a053aacd5630b44cc73c4e5505baebfe6d5

And the fix: #101369

**Comment by doronbehar** [comment] 2020-10-28 14:54
The problem is that we impose such breakage on a whole set, which should perhaps trigger a different message - like what python says when you try to evaluate a python3 only package from `python2.pkgs`.

**Comment by doronbehar** [comment] 2020-10-30 19:06
@bgamari with your permission I will close this with #101369 ,and hopefully in the future we won't apply a broken meta tag for so many attributes, not directly as was with kde's sets.

**Closed** 2020-11-01 10:05 UTC
Labels: 0.kind: bug, 6.topic: qt/kde
