### ISSUE TITLE
Package request: waveterm

### ISSUE THREAD

**Issue by Marin-Kitagawa** [NixOS/nixpkgs#321609] opened 2024-06-21 21:50 UTC
**Project description**

It is a modern terminal for Linux and MacOS. It has the concept of workspaces besides the tabs.

**Metadata**

* homepage URL: https://waveterm.dev/
* source URL: https://github.com/wavetermdev/waveterm
* license: Apache-2. 0
* platforms: Linux, Darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-06-21 21:52
duplicate of #280566

**Closed by eclairevoyant** 2024-06-21 21:52 UTC
Labels: 0.kind: packaging request
