### ISSUE TITLE
Travis build fails more often than it doesn't

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#6652] opened 2015-03-03 21:22 UTC
I'm not sure who's responsible for it or whether it's progressing, but if it's not being actively developed/improved, can we just disable it?

**Comment by spwhitt** [comment] 2015-03-03 23:30
Maybe Travis should be given a more lightweight task, like running nixpkgs lint and checking for evaluation errors.

**Comment by offlinehacker** [comment] 2015-03-04 01:40
I agree, travis.ci is really not the right tool, i think this should be implemented in hydra.

**Comment by devhell** [comment] 2015-03-04 13:02
Except Hydra isn't running any tests anymore as far as I can see. I might be wrong, but I think this coincides with Travis not checking successfully anymore.

**Comment by peti** [comment] 2015-03-04 13:19
The number of false-positives generated by those travis-ci jobs is so high that a "failure" outcome is next to meaningless, really. I would like to see those builds disabled, because their presence confuses contributors who spent their time worrying about bugs in their submission because those builds fail, when in fact it's just the build that's broken, not their PR.

**Comment by lethalman** [comment] 2015-03-04 13:22
I benefit from travis, I merged many PR just by looking at the outcome of travis.

**Comment by peti** [comment] 2015-03-04 13:23
Ping @madjar.

**Comment by copumpkin** [comment] 2015-03-04 13:28
As I suggested in my original question, I'm not necessarily opposed to leaving it in place if it's actively developed and there's a plan to improve it soon. But currently it generates so many false failures that I pretty much just ignore it, which means all its really doing is adding noise. Sure, a pass might be a good sign, but if they're rare and the system otherwise confuses new contributors, that doesn't seem good.

**Comment by madjar** [comment] 2015-03-04 14:17
Hello there

The travis job check that the tarball still build (`nix-build pkgs/top-level/release.nix -A tarball`), but this has been broken for a month. Also, on my local machine, this requires 2Go of RAM, so it fails on travis which is much more limited.

As a quick fix, I'll disable that check, but I think those two problems should also be fixed.

**Comment by copumpkin** [comment] 2015-03-04 14:19
Ah, if it's a legitimate failure then whoever broke it should probably fix
it! My main issue is that I don't know when it's legitimate so I mostly
ignore it, and I expect that whoever broke it in the first place probably
did the same.

**Comment by rzetterberg** [comment] 2015-03-09 14:39
I think a small part of the problem is that the travis results shown on github are not consistent with what you see on travis.

On travis you can see 3 different results: pass (green), fail (red) and error (grey).

But when you see travis results on github both fail (red) and error (grey) are shown as fail (red).

If I understand correctly, error (grey) is used when something unrelated to the test fails, such as too much memory used, no output within a certain time frame, too much output etc.

If github also showed fail and error as separate colors/icons you would get a better overview what PRs actually failed due to tests or unrelated issues.

**Comment by manveru** [comment] 2015-10-31 15:29
Well, here's the two results I get from travis, both equally unhelpful and false positives from the same commmit: https://github.com/NixOS/nixpkgs/pull/10755

One is failing if I base my branch on nixos-unstable and PR against master: https://travis-ci.org/NixOS/nixpkgs/builds/88525959
The other is based on upstream/master and simply generates a log that's over 4MB, so it also fails (mostly because qt build logs are huge): https://travis-ci.org/NixOS/nixpkgs/builds/88522075

I really didn't expect contributing to become more difficult since the last time I worked with nixpkgs, which is maybe a year ago when tests were still based on hydra.

**Comment by domenkozar** [comment] 2015-10-31 21:14
travis-ci is just a helper, not something we are strict about.

**Comment by vcunat** [comment] 2015-11-01 00:49
Lately it even seems to cause more harm than good. New people don't (immediately) realize what's going on and they spend time analyzing errors that have nothing to do with the PR. I just learned not to look at the errors at all, as I lately saw no added value in reading them.

**Comment by peti** [comment] 2015-11-01 09:52
IMHO, a test hook that generates about 10% false-positives is useless. I'd be perfectly happy if we'd just disable the travis-ci builds for Nipkgs.

**Comment by domenkozar** [comment] 2015-11-02 11:12
Every CI tool we use will have false positives until we provide a heuristic what changes we should build and what changes we want to skip because they're too "big".

There are still improvements that can be made to travis.

- use `nixos-channels` as a base instead of `nixpkgs` repository
- estimate build times using hydra information

Regarding log size we can hardly do anything otherwise we'd lose all debugging output.

**Comment by vcunat** [comment] 2015-11-02 11:17
> use nixos-channels as a base instead of nixpkgs repository

Maybe I don't understand you &ndash; do you mean it should (somehow) automatically rebase the PRs? (Currently it depends on the submitter where (s)he bases the PR on, I believe.)

**Comment by domenkozar** [comment] 2015-11-02 11:19
Yeah, it already re-bases on top of master.

**Comment by domenkozar** [comment] 2015-11-02 11:25
I think we should collect statistics when travis-ci fails and under what conditions and then decide what can be solved or not.

**Comment by vcunat** [comment] 2015-11-02 11:25
Personally, I'd prefer to address this particular problem by holding to the agreement that master should **not** get any mass-rebuild changes (before binaries are available).

**Comment by domenkozar** [comment] 2015-11-02 11:26
Agreed.

**Comment by domenkozar** [comment] 2015-11-02 11:39
I see a number of things that can be improved, I'll open a PR with more details.

**Comment by domenkozar** [comment] 2015-11-02 12:06
By looking at first two pages of PRs, I've noticed following issues with travis-ci:

1) 8 builds ran out of memory (example https://travis-ci.org/NixOS/nixpkgs/builds/88628057)
2) 2 builds stopped because of no output (example https://travis-ci.org/NixOS/nixpkgs/builds/88626974)
3) 4 builds failed on merge conflict (example https://travis-ci.org/NixOS/nixpkgs/builds/88626701)
4) 4 builds failed due to too long log 4MB (example https://travis-ci.org/NixOS/nixpkgs/builds/88621524)
5) 6 builds successfully caught an error
6) 1 build failed because PR had no title (example https://travis-ci.org/NixOS/nixpkgs/builds/87937406)

The rest of the builds passed. Now, I'd say we can address of all these.

1) Fixed in 11b123662717ad20c3bb3100503786b35adfb158
2) This one is the hardest to solve. More memory will help, but we should limit travis when changes are too big. I'd consider this one an positive, meaning it's mass-rebuild.
3) I haven't dig into merge conflict, but merge buttons seems to be green.
4) We could slience `curl`, implement http://docs.travis-ci.com/user/uploading-artifacts/  or my most favourite, fix https://github.com/NixOS/nix/issues/443
5) YAY
6) Should be fixed in nox

**Comment by vcunat** [comment] 2015-11-02 12:23
1) nice :-)
4) that's not the **cause** of failure, at least not in the example that you link &ndash; it failed due to OOM, and it doesn't **display** the full log due to being too long (you can view it raw https://s3.amazonaws.com/archive.travis-ci.org/jobs/88621525/log.txt).

**Comment by domenkozar** [comment] 2015-11-02 12:26
4) Yeah, bad example, see https://s3.amazonaws.com/archive.travis-ci.org/jobs/88522076/log.txt

**Comment by vcunat** [comment] 2015-11-02 12:29
I wonder if they provide an option to keep a tail of the log. 4 MB is way too much to keep for these purposes anyway.

**Comment by vcunat** [comment] 2015-11-02 12:41
Actually, why not simply pipe the output through `tail -c 100k` or similar? Would anyone read a longer part of the log?

**Comment by domenkozar** [comment] 2015-11-02 12:46
7) And for completeness there is also https://github.com/madjar/nox/issues/22, but we just need a better way to detect changes even if `recurseIntoAttrset` is not used.

**Comment by domenkozar** [comment] 2016-02-15 13:17
I did another round of testing. Here are the results for latest 50 PRs:

- 2 fail due to merge conflicts (still needs investigation)
- 2 fail due to EOF using curl to download binaries (do we need a feature in Nix to retry?)
- 1 fail due to hydra saying `410 Gone` (do we need to fix Nix to support that?)
- 2 fail due to job timeout (not much we can do here)
- 5 actual errors in code (yay, that's 10% of failures caught)
- 9 fail due to max log size reached (see #13006)

**Comment by domenkozar** [comment] 2016-09-04 08:47
This is getting worse and worse. I wonder if we should really just disable travis and work on Hydra that tests PRs.

**Comment by FRidh** [comment] 2016-09-04 09:00
For the PR's I've been looking at Travis appears to be working quite well now. The problem is that currently on master and I think also 16.09 the tarball cannot be build (https://github.com/NixOS/nixpkgs/issues/18209#issuecomment-244576612). A problem I did find is that Travis often reports a fail of the first test job for no apparent reason.

**Comment by siddharthist** [comment] 2016-09-26 23:09
On https://github.com/NixOS/nixpkgs/pull/18376, we resolved not to disable Travis for now. Seems like it's not pressing/can wait until we can use Hydra. Can we close this for now?

**Comment by vcunat** [comment] 2016-09-28 15:35
I'm not convinced someone really is working actively on that Hydra support, but I'm hopeful.

**Comment by matthewbauer** [comment] 2016-12-13 05:37
Okay, some notes on Travis issues from (https://travis-ci.org/NixOS/nixpkgs/pull_requests):

- Nox-review shouldn't bite off more than it can chew (https://travis-ci.org/NixOS/nixpkgs/jobs/183271042)
   - perhaps just don't build more than ~20 dependencies? (could cause false positives)
- Changes to the stdenv is probably always going to cause headaches
- When Hydra binary cache gets behind, Travis tries to build them
  - maybe rebase on last fully built evaluation? (could break some PRs)
- Travis sets hard limit of 4MB log size that we frequently go over.
  - see NixOS/nix#443 for ideas
  - nox-review could try to build with "-Q"

**Comment by vcunat** [comment] 2016-12-13 12:49
> Travis sets hard limit of 4MB log size that we frequently go over.

Filtering the output through `tail` might be a nice way.

**Comment by matthewbauer** [comment] 2017-07-10 20:39
Update on this: Travis has been failing a lot lately on MacOS because of travis-ci/travis-ci#7628. I've opened travis-ci/travis-build#1104 to hopefully fix it.

**Comment by Mic92** [comment] 2017-11-13 11:22
Now, that we have pr bots, can we disable travis? It confuses new people.

**Closed** 2017-11-15 19:33 UTC
