### ISSUE TITLE
multimc: 0.6.14

### ISSUE THREAD

**Issue by lourkeur** [NixOS/nixpkgs#149923] opened 2021-12-09 20:42 UTC
https://github.com/MultiMC/Launcher/blob/70d400f205952912cbfa0a13cd8c84687ef06baa/changelog.md#multimc-0614

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: unstable (technically 0.6.13)
desired version: 0.6.14

###### Notify maintainers

maintainers: @starcraft66 @cleverca22

###### Note for maintainers

Please tag this issue in your PR.

**Comment by huantianad** [comment] 2021-12-10 03:05
Out of curiosity, with the branding changes, would we use our own assets or are we still going to use the "official" assets.

A Minecraft dirt block with the Nix logo would be a kinda funny alternative :stuck_out_tongue:

**Comment by starcraft66** [comment] 2021-12-11 18:07
I plan to use the default unbranded assets for the initial update but we can work out our own assets for sure.

**Comment by starcraft66** [comment] 2021-12-11 18:07
This is currently blocked by https://github.com/MultiMC/Launcher/issues/4328 because the latest version of MultiMC can no longer be launched from the read-only Nix store.

**Comment by starcraft66** [comment] 2021-12-11 18:18
Draft PR is up here, just waiting for upstream https://github.com/NixOS/nixpkgs/pull/150285

**Comment by thelegy** [comment] 2021-12-22 00:27
As upstream seems to make no movement to address the issue, maybe we can fix it on our end. (The upstream issue was closed as "Working as intended")
https://github.com/MultiMC/Launcher/issues/4328#issuecomment-991923874 suggests the `-d` or better `--dir` option would fix the issue. Can we set it in a wrapper and point it to something like `${XDG_DATA_HOME:-~/.local/share}/multimc`?

**Comment by huantianad** [comment] 2021-12-22 05:53
@thelegy I believe this is mentioned and implemented over in the [PR](https://github.com/NixOS/nixpkgs/pull/150285#pullrequestreview-829644371).

**Comment by starcraft66** [comment] 2022-01-08 06:39
I have been made aware of the existance of a new MultiMC fork created due to the hostility of MultiMC's developer towards maintainers of 3rd party packages: https://github.com/PolyMC/PolyMC

I think it might be worthwhile to package this and see where that fork goes given the backwards-compatibility issues the de-branded launcher currently pose. Perhaps the "logging to the wrong location bug" MultiMC's maintainers refused to fix could be patched in PolyMC at the same time.

**Comment by starcraft66** [comment] 2022-01-08 06:44
I have opened the following issue: https://github.com/PolyMC/PolyMC/issues/23

**Comment by legendofmiracles** [comment] 2022-01-08 12:57
Another PR that would update multimc: https://github.com/NixOS/nixpkgs/pull/150285

**Comment by starcraft66** [comment] 2022-01-08 21:30
New PR open: https://github.com/NixOS/nixpkgs/pull/154051/files

**Comment by thelegy** [comment] 2022-01-16 11:02
As #154051 was merged, which also removes multimc from nixpkgs, I would like to close this.

**Closed by thelegy** 2022-01-16 11:02 UTC
Labels: 9.needs: package (update)
