### ISSUE TITLE
Cannot Install Mono

### ISSUE THREAD

**Issue by AshtonKem** [NixOS/nixpkgs#80217] opened 2020-02-15 23:51 UTC
**Describe the bug**
Compilation error on Mono using nixpkgs-unstable.

**To Reproduce**
Install mono package

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.16, NixOS, 20.03pre211344.d5bf8b23592 (Markhor)`


 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(ashton): `"nixos-stable-19.09.2070.b9cb3b2fb2f"`
 - channels(root): `"nixos-20.09pre213040.f77e057cda6, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
<details><summary>Revelant Log Output</summary>

> CSC     [build-linux] System.Text.Encoding.dll
> CSC     [build-linux] System.Threading.dll
> /nix/store/f4kzmcylzxn15kg4xbmpwmkkr6a8wb42-binutils-2.31.1/bin/ld: cannot find -lgcc
> AOT of image ./../../class/lib/build-linux//mscorlib.dll failed.
> Mono Ahead of Time compiler - compiling assembly /build/mono-5.20.1.27/mcs/class/lib/build-linux/mscorlib.dll
> AOTID 2E7A87E3-4FE6-744E-138F-2F178B725D0F
> Using profile data file './../../class/lib/build/csc.corlib.dll.aotprofile'
> Using profile data file './../../class/lib/build/csc.System.Core.dll.aotprofile'
> Added 142 methods from profile.
> Added 134 methods from profile.
> Code: 5132736(60%) Info: 154580(1%) Ex Info: 2638631(31%) Unwind Info: 17609(0%) Class Info: 107570(1%) PLT: 128250(1%) GOT Info: 176144(2%) Offsets: 105092(1%) GOT: 167432
> Compiled: 23513/23513 (100%), No GOT slots: 0 (0%), Direct calls: 0 (0%)
> Executing the native assembler: "as" --64  -o /build/mono_aot_Dph27A.o /build/mono_aot_Dph27A
> Executing the native linker: "ld"  -shared -o /build/mono-5.20.1.27/mcs/class/lib/build-linux/mscorlib.dll.so.tmp  /build/mono_aot_Dph27A.o 
> make[7]: *** [Makefile:61: ../../class/lib/build-linux//mscorlib.dll.so] Error 1
> make[7]: *** Waiting for unfinished jobs....
> CSC     [build-linux] System.Diagnostics.Debug.dll
> CSC     [build-linux] System.Linq.Expressions.dll
> CSC     [build-linux] System.IO.dll
> CSC     [build-linux] System.Collections.Concurrent.dll
> [688/1378] CXX obj/v8/torque_generated_initializers/iterator-tq-csa.oq-csa.o
> warning: unknown warning option '-Wno-implicit-int-float-conversion'; did you mean '-Wno-implicit-float-conversion'? [-Wunknown-warning-option]
> warning: unknown warning option '-Wno-final-dtor-non-final-class'; did you mean '-Wno-abstract-final-class'? [-Wunknown-warning-option]
> warning: unknown warning option '-Wno-bitwise-conditional-parentheses'; did you mean '-Wno-bitwise-op-parentheses'? [-Wunknown-warning-option]
> warning: unknown warning option '-Wno-builtin-assume-aligned-alignment' [-Wunknown-warning-option]
> warning: unknown warning option '-Wno-deprecated-copy'; did you mean '-Wno-deprecated'? [-Wunknown-warning-option]
> 5 warnings generated.
> /nix/store/f4kzmcylzxn15kg4xbmpwmkkr6a8wb42-binutils-2.31.1/bin/ld: cannot find -lgcc
> AOT of image /build/mono-5.20.1.27/external/roslyn-binaries/Microsoft.Net.Compilers/Microsoft.Net.Compilers.2.8.2/tools//Microsoft.CodeAnalysis.CSharp.dll failed.
> Mono Ahead of Time compiler - compiling assembly /build/mono-5.20.1.27/external/roslyn-binaries/Microsoft.Net.Compilers/Microsoft.Net.Compilers.2.8.2/tools/Microsoft.CodeAnalysis.CSharp.dll
> AOTID E62B3153-7A53-0183-FE8C-4C8D595D2A79
> Using profile data file './../../class/lib/build/csc.corlib.dll.aotprofile'
> Using profile data file './../../class/lib/build/csc.System.Core.dll.aotprofile'
> Added 223 methods from profile.
> Added 224 methods from profile.
> Code: 6435532(61%) Info: 213409(2%) Ex Info: 3044373(28%) Unwind Info: 22719(0%) Class Info: 300091(2%) PLT: 176210(1%) GOT Info: 223564(2%) Offsets: 123708(1%) GOT: 249824
> Compiled: 29999/29999 (100%), No GOT slots: 0 (0%), Direct calls: 0 (0%)
> Executing the native assembler: "as" --64  -o /build/mono_aot_sydsRu.o /build/mono_aot_sydsRu
> Executing the native linker: "ld"  -shared -o ./../../class/lib/build-linux//Microsoft.CodeAnalysis.CSharp.dll.so.tmp  /build/mono_aot_sydsRu.o 
> make[7]: *** [Makefile:67: ../../class/lib/build-linux//Microsoft.CodeAnalysis.CSharp.dll.so] Error 1
> make[6]: *** [../../build/rules.make:216: do-all] Error 2
> make[5]: *** [build/rules.make:237: all-recursive] Error 1
> make[4]: *** [Makefile:54: profile-do--build--all] Error 2
> make[3]: *** [Makefile:50: profiles-do--all] Error 2
> make[2]: *** [Makefile:660: all-mcs] Error 2
> make[2]: Leaving directory '/build/mono-5.20.1.27/runtime'
> make[1]: *** [Makefile:568: all-recursive] Error 1
> make[1]: Leaving directory '/build/mono-5.20.1.27'
> make: *** [Makefile:498: all] Error 2
> CSC     [build-linux] System.Dynamic.Runtime.dll
> builder for '/nix/store/7s1135zyd0l3yig0fkiz30p39hwhlgh1-mono-5.20.1.27.drv' failed with exit code 2
> cannot build derivation '/nix/store/asqax45amfp89srjmf75vslhf3hicdyn-steam-usr-target.drv': 1 dependencies couldn't be built
> cannot build derivation '/nix/store/nd4ri5hzxxjvsdg2k6m189hhsdbbfsq5-steam-fhs.drv': 1 dependencies couldn't be built
> cannot build derivation '/nix/store/q9rfgnlnh8j3qi28598bkxis1ac4mhzs-steam-init.drv': 1 dependencies couldn't be built
> cannot build derivation '/nix/store/qyzscyylimv8419xgwlx2j1nf0lxcx5c-steam.drv': 1 dependencies couldn't be built
> cannot build derivation '/nix/store/3gxqjnrpn3w0ncxm0v15krk014w4wnrs-system-path.drv': 1 dependencies couldn't be built
> cannot build derivation '/nix/store/w9lvw8g11kr0251pflvlcz0xi8mc9d9d-nixos-system-nixos-20.09pre213040.f77e057cda6.drv': 1 dependencies couldn't be built
> error: build of '/nix/store/w9lvw8g11kr0251pflvlcz0xi8mc9d9d-nixos-system-nixos-20.09pre213040.f77e057cda6.drv' failed
</details>

**Comment by jul1u5** [comment] 2020-02-16 00:59
Duplicate of #79841

**Comment by AshtonKem** [comment] 2020-02-16 01:00
I’m not sure if it is a duplicate, since the error message is slightly different, and the commit to fix #79841 was re-merged.

**Comment by jul1u5** [comment] 2020-02-16 01:33
The [howoldis site](https://howoldis.herokuapp.com/) says, that nixos-unstable has only been updated 6 days ago. I think the fix hasn't landed yet on the unstable channel.

**Comment by AshtonKem** [comment] 2020-02-16 01:36
Ah, that explains it. I assumed that unstable would update more often than that.

**Comment by jul1u5** [comment] 2020-02-16 01:45
Yeah, I am not sure why it's taking so long.

**Comment by FRidh** [comment] 2020-02-16 09:29
It's fixed on master. There was an issue with Hydra which, as far as I know, has been resolved by now and the last evaluation was successful so there should be a channel update today.

**Closed by FRidh** 2020-02-16 09:29 UTC
Labels: 0.kind: bug
