### ISSUE TITLE
nixos-rebuild --upgrade failing

### ISSUE THREAD

**Issue by umeat** [NixOS/nixpkgs#268827] opened 2023-11-20 22:15 UTC
### Describe the bug

`nixos-rebuild --upgrade switch` erroring with issue in mk-python-derivation:

```
$ sudo nixos-rebuild --upgrade switch 
unpacking channels...
building Nix...
building the system configuration...
error:
       … while calling the 'head' builtin

         at /nix/store/6zjbvw6yynp7fj77y1p435d2gchdzv3r-nixos/nixos/lib/attrsets.nix:850:11:

          849|         || pred here (elemAt values 1) (head values) then
          850|           head values
             |           ^
          851|         else

       … while evaluating the attribute 'value'

         at /nix/store/6zjbvw6yynp7fj77y1p435d2gchdzv3r-nixos/nixos/lib/modules.nix:807:9:

          806|     in warnDeprecation opt //
          807|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          808|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: assertion '((pyproject != null) -> (format == null))' failed

       at /nix/store/6zjbvw6yynp7fj77y1p435d2gchdzv3r-nixos/nixos/pkgs/development/interpreters/python/mk-python-derivation.nix:110:1:

          109|
          110| assert (pyproject != null) -> (format == null);
             | ^
          111|
```

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.9, NixOS, 23.11 (Tapir), 23.11pre541036.63678e9f3d3a`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by kirillrdy** [comment] 2023-11-20 22:56
duplicate of https://github.com/NixOS/nixpkgs/issues/268737

**Closed** 2023-11-20 22:56 UTC
Labels: 0.kind: bug
