### ISSUE TITLE
tor-browser-bundle-bin mirror for 9.5 is down

### ISSUE THREAD

**Issue by sk33z3r** [NixOS/nixpkgs#94576] opened 2020-08-02 22:32 UTC
**Describe the bug**
`tor-browser-bundle-bin` fails to install because the mirror for 9.5 appears to be down/obsolete

**To Reproduce**
Add `tor-browser-undle-bin` to your nix config (via 20.03 or unstable channels, both are broken) and switch
or
`nix-env -i tor-browser-bundle-bin`

**Expected behavior**
The derivation is built successfully

**Screenshots**
The terminal output for `nix-env`:
```
~> nix-env -i tor-browser-bundle-bin
warning: there are multiple derivations named 'tor-browser-bundle-bin-9.5'; using the first one
installing 'tor-browser-bundle-bin-9.5'
these derivations will be built:
  /nix/store/s6vpr5m3vcx2fbysr86rd5rm6i5a6cpd-tor-browser-linux64-9.5_en-US.tar.xz.drv
  /nix/store/c43ggk12gikr5f80cxabppqb8zkjivmk-tor-browser-bundle-bin-9.5.drv
building '/nix/store/s6vpr5m3vcx2fbysr86rd5rm6i5a6cpd-tor-browser-linux64-9.5_en-US.tar.xz.drv'...

trying https://dist.torproject.org/torbrowser/9.5/tor-browser-linux64-9.5_en-US.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download tor-browser-linux64-9.5_en-US.tar.xz from any mirror
builder for '/nix/store/s6vpr5m3vcx2fbysr86rd5rm6i5a6cpd-tor-browser-linux64-9.5_en-US.tar.xz.drv' failed with exit code 1
cannot build derivation '/nix/store/c43ggk12gikr5f80cxabppqb8zkjivmk-tor-browser-bundle-bin-9.5.drv': 1 dependencies couldn't be built
error: build of '/nix/store/c43ggk12gikr5f80cxabppqb8zkjivmk-tor-browser-bundle-bin-9.5.drv' failed
```

**Notify maintainers**
@joachifm @offlinehacker @matejc @doublec @thoughtpolice

Looks like the latest available (as of this writing) is for 9.5.3:
https://www.torproject.org/dist/torbrowser/9.5.3/tor-browser-linux64-9.5.3_en-US.tar.xz

**Comment by prusnak** [comment] 2020-08-03 14:58
Duplicate of https://github.com/NixOS/nixpkgs/issues/91062

Fixed in #94019

**Closed by prusnak** 2020-08-03 14:58 UTC
Labels: 0.kind: bug
