### ISSUE TITLE
Prebuilt Python 3.9.1 ctypes.util.find_library broken on Big Sur

### ISSUE THREAD

**Issue by dillon-giacoppo** [NixOS/nixpkgs#107519] opened 2020-12-24 04:42 UTC
**Describe the bug**

Big Sur support was added to Python 3.9.1 via https://github.com/python/cpython/pull/22855/files. That PR fixes `ctypes.util.find_library` by checking for libraries in the shared dylib cache.

However, it appears that the prebuilt binary for 3.9.1 is not compiled with `HAVE_DYLD_SHARED_CACHE_CONTAINS_PATH` therefore ctypes are still broken using Python 3.9.1 with Nix.  Not sure if this is a consequence of the package being compiled on a MacOS Catalina machine (although I have no idea how the macos build system works for nix).

e.g:
```py
import ctypes.util
ctypes.util.find_library('c')  # Expecting '/usr/lib/libc.dylib', but get None
```

The root cause of this is that `_dyld_shared_cache_contains_path` is not compiled into `_ctypes` where it is expected in `ctypes/macholib/dyld.py` for Big Sur:

```py
try:
    from _ctypes import _dyld_shared_cache_contains_path
except ImportError:
    def _dyld_shared_cache_contains_path(*args):
        raise NotImplementedError
# ...

def dyld_find(name, executable_path=None, env=None):
# ...
        try:
            if _dyld_shared_cache_contains_path(path):  # <-- Expecting the libraries to be picked up here
                return path
        except NotImplementedError:  # <-- But they end up being skipped over.
            pass
```

This is in turn appears to be caused by the build machine missing the `_dyld_shared_cache_contains_path` function in `<mach-o/dyld.h>` indicating it is MacOS < 11.

**To Reproduce**

```sh
nix run -f channel:nixos-20.09 python39 -c python3 -c "import sysconfig; print(f\"HAVE_DYLD_SHARED_CACHE_CONTAINS_PATH: {sysconfig.get_config_vars().get('HAVE_DYLD_SHARED_CACHE_CONTAINS_PATH', -1)}\")"
```

**Expected behavior**

Python 3.9.1 should be compiled with `HAVE_DYLD_SHARED_CACHE_CONTAINS_PATH=1` on Big Sur.

**Additional context**

**Notify maintainers**
@FRidh 

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.2.0, macOS 10.16` <- this should be macOS 11.1 (not sure why nix-info printed 10.16)
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.1`
 - channels(dillon): `"nixpkgs-21.03pre259358.b67ba0bfcc7"`
 - nixpkgs: `/Users/dillon/.nix-defexpr/channels/nixpkgs`

**Comment by FRidh** [comment] 2022-03-29 12:00
If I understand correctly this is a duplicate of https://github.com/NixOS/nixpkgs/issues/105038.

**Comment by abathur** [comment] 2023-05-29 17:36
Closing since I agree this is a duplicate and the issue appears to have been resolved. See my comment in the other issue for justification; happy to reopen if I'm mistaken.

**Closed by abathur** 2023-05-29 17:36 UTC
Labels: 0.kind: bug, 2.status: duplicate, 6.topic: python, 6.topic: darwin
