### ISSUE TITLE
Package request: Hardinfo2

### ISSUE THREAD

**Issue by boustanihani** [NixOS/nixpkgs#360753] opened 2024-12-01 12:25 UTC
Display information about your hardware and operating system

Hardinfo2 is based on hardinfo, which has not been released >10 years.
Hardinfo2 is the reboot that was needed.

Websites: 
- https://hardinfo2.org/
- https://github.com/hardinfo2/hardinfo2

Licenses:
- [GPL-3.0 license](https://github.com/hardinfo2/hardinfo2#)
- [LGPL-2.1 license](https://github.com/hardinfo2/hardinfo2#)

**Comment by FliegendeWurst** [comment] 2024-12-01 18:27
Duplicate of #323355

PR to add was just merged :) #330051

**Closed by FliegendeWurst** 2024-12-01 18:27 UTC
Labels: 0.kind: packaging request
