### ISSUE TITLE
hyperv-daemons cannot find ip, awk, hv_get_dns_info, or hv_get_dhcp_info

### ISSUE THREAD

**Issue by ivan** [NixOS/nixpkgs#48621] opened 2018-10-17 12:42 UTC
## Issue description

When installed in a Hyper-V guest, NixOS installs hyperv-daemons, but `hv_kvp_daemon` spews log messages about being unable to find the executables it depends on.

### Steps to reproduce

1. Install NixOS 18.09 in a Hyper-V guest (Generation 2 VM - not sure if necessary) on Windows 10 1803.
2. Observe a lot of this in `journalctl`:

```
Oct 17 12:32:10 hydra hv_kvp_daemon[849]: sh: ip: command not found
Oct 17 12:32:10 hydra hv_kvp_daemon[849]: sh: awk: command not found
Oct 17 12:32:10 hydra hv_kvp_daemon[849]: sh: ip: command not found
Oct 17 12:32:10 hydra hv_kvp_daemon[849]: sh: awk: command not found
Oct 17 12:32:10 hydra hv_kvp_daemon[849]: sh: /usr/libexec/hypervkvpd/hv_get_dns_info: No such file or directory
Oct 17 12:32:10 hydra hv_kvp_daemon[849]: sh: /usr/libexec/hypervkvpd/hv_get_dhcp_info: No such file or directory
Oct 17 12:32:10 hydra hv_kvp_daemon[849]: sh: ip: command not found
Oct 17 12:32:10 hydra hv_kvp_daemon[849]: sh: awk: command not found
Oct 17 12:32:10 hydra hv_kvp_daemon[849]: sh: ip: command not found
Oct 17 12:32:10 hydra hv_kvp_daemon[849]: sh: awk: command not found
Oct 17 12:32:10 hydra hv_kvp_daemon[849]: sh: /usr/libexec/hypervkvpd/hv_get_dns_info: No such file or directory
Oct 17 12:32:10 hydra hv_kvp_daemon[849]: sh: /usr/libexec/hypervkvpd/hv_get_dhcp_info: No such file or directory
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.09.892.c06f5302f63 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09.892.c06f5302f63"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

```
# ps auxw | grep hyperv
root        849  0.0  0.0  11236  1888 ?        Ss   12:31   0:00 /nix/store/lvhm5d9khgwkqygy8yr68hq1in2ldjbp-hyperv-daemons-bin-4.14.76/bin/hv_kvp_daemon -n
root        850  0.0  0.0   4260   196 ?        Ss   12:31   0:00 /nix/store/lvhm5d9khgwkqygy8yr68hq1in2ldjbp-hyperv-daemons-bin-4.14.76/bin/hv_vss_daemon -n
```

The relevant bit of the Linux source appears to be:

```c
static void kvp_get_ipconfig_info(char *if_name,
				 struct hv_kvp_ipaddr_value *buffer)
{
	char cmd[512];
	char dhcp_info[128];
	char *p;
	FILE *file;

	/*
	 * Get the address of default gateway (ipv4).
	 */
	sprintf(cmd, "%s %s", "ip route show dev", if_name);
	strcat(cmd, " | awk '/default/ {print $3 }'");

	/*
	 * Execute the command to gather gateway info.
	 */
	kvp_process_ipconfig_file(cmd, (char *)buffer->gate_way,
				(MAX_GATEWAY_SIZE * 2), INET_ADDRSTRLEN, 0);

	/*
	 * Get the address of default gateway (ipv6).
	 */
	sprintf(cmd, "%s %s", "ip -f inet6  route show dev", if_name);
	strcat(cmd, " | awk '/default/ {print $3 }'");

	/*
	 * Execute the command to gather gateway info (ipv6).
	 */
	kvp_process_ipconfig_file(cmd, (char *)buffer->gate_way,
				(MAX_GATEWAY_SIZE * 2), INET6_ADDRSTRLEN, 1);


	/*
	 * Gather the DNS  state.
	 * Since there is no standard way to get this information
	 * across various distributions of interest; we just invoke
	 * an external script that needs to be ported across distros
	 * of interest.
	 *
	 * Following is the expected format of the information from the script:
	 *
	 * ipaddr1 (nameserver1)
	 * ipaddr2 (nameserver2)
	 * .
	 * .
	 */

	sprintf(cmd, KVP_SCRIPTS_PATH "%s",  "hv_get_dns_info");

	/*
	 * Execute the command to gather DNS info.
	 */
	kvp_process_ipconfig_file(cmd, (char *)buffer->dns_addr,
				(MAX_IP_ADDR_SIZE * 2), INET_ADDRSTRLEN, 0);

	/*
	 * Gather the DHCP state.
	 * We will gather this state by invoking an external script.
	 * The parameter to the script is the interface name.
	 * Here is the expected output:
	 *
	 * Enabled: DHCP enabled.
	 */

	sprintf(cmd, KVP_SCRIPTS_PATH "%s %s", "hv_get_dhcp_info", if_name);

	file = popen(cmd, "r");
	if (file == NULL)
		return;

	p = fgets(dhcp_info, sizeof(dhcp_info), file);
	if (p == NULL) {
		pclose(file);
		return;
	}

	if (!strncmp(p, "Enabled", 7))
		buffer->dhcp_enabled = 1;
	else
		buffer->dhcp_enabled = 0;

	pclose(file);
}
```

**Comment by peterhoeg** [comment] 2018-10-23 08:13
Are you enabling this via ```virtualisation.hypervGuest.enable = true;``` ?

**Comment by ivan** [comment] 2018-10-23 11:57
Yes, I have a `virtualisation.hypervGuest.enable = true;` that `nixos-install` placed into `hardware-configuration.nix`.

**Comment by peterhoeg** [comment] 2018-11-06 04:57
I'm seeing none of this:

```
[root@sin-util-1:~]# systemctl status hv-kvp
● hv-kvp.service - Hyper-V key-value pair (KVP) daemon
   Loaded: loaded (/nix/store/4xlhrbzjg1ndv5412kk73vmg1yr7qab1-hyperv-daemons-4.18.16-lib/lib/systemd/system/hv-kvp.service; linked; vendor preset: enabled)
   Active: active (running) since Wed 2018-10-31 17:38:58 +08; 5 days ago
 Main PID: 56317 (.hv_kvp_daemon-)
    Tasks: 1 (limit: 1120)
   Memory: 532.0K
      CPU: 49ms
   CGroup: /hyperv.slice/hv-kvp.service
           └─56317 /nix/store/rdhksz0c12k318885bs6j0snb531q4pi-hyperv-daemons-bin-4.18.16/bin/hv_kvp_daemon -n

Oct 31 17:38:58 sin-util-1 systemd[1]: Started Hyper-V key-value pair (KVP) daemon.
Oct 31 17:38:58 sin-util-1 KVP[56317]: KVP starting; pid is:56317
Oct 31 17:38:58 sin-util-1 KVP[56317]: KVP LIC Version: 3.1
```

Could you try with the latest kernel instead of 4.14?

**Comment by ivan** [comment] 2018-11-06 05:06
I had to stop using Hyper-V because it could not keep the virtual Ethernet reliably plugged into my guest VM ("carrier lost"), so I can no longer test with Hyper-V.

**Comment by peterhoeg** [comment] 2018-11-06 05:55
We run NixOS as guests on Windows Server 2012, 2012R2 and 2016 without issues. I'm going to close this for now as "unable to reproduce".

**Closed by peterhoeg** 2018-11-06 05:55 UTC
