### ISSUE TITLE
Packaging Gradle-based applications

### ISSUE THREAD

**Issue by bobvanderlinden** [NixOS/nixpkgs#17342] opened 2016-07-28 14:52 UTC
## Issue description

I have a (closed) application that I'd like to package and place on my NixOS server. The application can be built using Gradle, however since Gradle downloads its dependencies online it is unable to be build using Nix as-is.

It seemed all application that are based on Java/Ant/Maven/Gradle are being packaged based on binaries, instead of the source. Is this the recommended way to use Java-based applications on Nix?

While trying to find a solution, I have found [mvn2nix-maven-plugin](https://github.com/NixOS/mvn2nix-maven-plugin), but it was unclear how to use it for other projects. Especially the ones built with Gradle.

**Comment by spacekitteh** [comment] 2017-02-19 21:58
Seconding this. I'd really like to figure this out.

**Comment by NeQuissimus** [comment] 2017-02-19 22:04
There is #20444 :-)

**Comment by spacekitteh** [comment] 2017-02-24 12:59
Aye, but Gradle is needed for Android apps

**Comment by auntieNeo** [comment] 2017-12-06 13:30
I am especially interested in building Android apps with Gradle. Recent apps created with Android studio no longer work with ant.

I wonder if androidenv can be extended to work with the Gradle wrapper. Or maybe that's not a viable approach.

**Comment by bobvanderlinden** [comment] 2018-06-04 21:27
Gradle 4.7 was just released. It includes locking of versions, which might be useful for Nix:

https://docs.gradle.org/current/release-notes.html#locking-of-dynamic-dependencies

**Comment by tadfisher** [comment] 2018-06-06 21:45
@bobvanderlinden Very cool, a `gradle2nix` tool is feasible now.

**Comment by bobvanderlinden** [comment] 2018-06-07 11:13
The lock file only includes the groupId, artifactId and the version. See https://docs.gradle.org/current/userguide/dependency_locking.html#_lock_state_location_and_format

We still need a way to know the URLs for these packages.

**Comment by tadfisher** [comment] 2018-06-07 19:06
@bobvanderlinden That's fine. What I'd do is make a Gradle plugin that emits a Nix configuration for a task, and apply it using `gradle --init-script`. This would actually work without dependency locking.

**Comment by bobvanderlinden** [comment] 2018-06-07 21:12
Oh wow. I didn't know Gradle could do that. Nice.

https://docs.gradle.org/current/userguide/init_scripts.html#sec:basic_usage

> Register build listeners. External tools that wish to listen to Gradle events might find this useful.

Though I cannot find how to hook into the downloader.

Another useful plugin is one that downloads all dependencies:

https://github.com/mdietrichstein/gradle-offline-dependencies-plugin

**Comment by lheckemann** [comment] 2018-09-22 14:06
https://docs.gradle.org/4.8/release-notes.html#locking-of-dynamic-dependencies Fixed link for earlier comment

**Comment by deliciouslytyped** [comment] 2019-03-27 22:21
Any news here?

**Comment by tadfisher** [comment] 2019-04-01 17:03
Here's a POC for a `gradle2nix` tool: https://github.com/tadfisher/gradle2nix

It should be able to build itself with the included `default.nix`. Use it with `gradle2nix` in a project root.

There are a few pitfalls that I'm working out:

- It builds against Gradle 5.3, but there are a couple of APIs that it uses that aren't available on older Gradle versions, so it only supports Gradle 5.3+ right now.
- It only supports Maven dependencies. Ivy support is slightly less trivial but I will add it after writing tests.
- It resolves plugin marker dependencies and plugin repositories with internal APIs, which might be unavoidable.
- It's currently a `gradle` plugin in order to resolve plugins. However, this requires application via an init script. It could potentially resolve plugins as a `settings` plugin, and the project dependency resolution could be split out into a `project` plugin.
- I haven't looked into resolving `buildSrc` dependencies or overriding repos for `buildSrc` projects.

**Comment by tadfisher** [comment] 2019-06-19 21:51
I've reworked `gradle2nix` to use the Gradle Tooling API, so the implementation is a bit cleaner.

- It's now compatible with Gradle 4.4 and up, with a test suite for regressions.
- I've added some rudimentary support for included builds and `buildSrc`, but I haven't gotten around to testing it.

**Comment by deliciouslytyped** [comment] 2019-06-29 00:13
@tadfisher This looks pretty good, I'm not intimately familiar with gradle, how do I run this if I want to package something?

**Comment by tadfisher** [comment] 2019-06-29 02:52
You should be able to build the `gradle2nix` application using the included `default.nix` script, then just run `[result]/bin/gradle2nix` in a Gradle project directory. This will generate a `gradle-env.json` and `gradle-env.nix` pair. You can then import the Nix expression and use it to build the project. See `default.nix` in the gradle2nix project itself for an example.

**Comment by NorfairKing** [comment] 2019-08-18 15:21
+1

**Comment by deliciouslytyped** [comment] 2019-11-04 03:40
For later reference, here is an example of something using Gradle without any extra fancy tooling (I think) https://github.com/NixOS/nixpkgs/pull/72306

**Comment by tadfisher** [comment] 2019-11-04 07:40
@deliciouslytyped Unfortunately, that solution will break whenever one of its SNAPSHOT dependencies publishes a new version. In general, you can't make a fixed-output derivation from the dependencies fetched for a build, because Gradle allows dynamic dependency versions and can resolve different artifacts from run to run. Therefore, you need tooling to extract the resolved artifact sources in order to make the build reproducible.

**Comment by petabyteboy** [comment] 2020-01-10 05:35
I made an attempt to use gradle2nix in nixpkgs: https://github.com/NixOS/nixpkgs/issues/17342

**Comment by petabyteboy** [comment] 2020-01-10 05:35
I made an attempt to use gradle2nix in nixpkgs: #77422

**Comment by NorfairKing** [comment] 2020-07-08 07:35
"still important to me"

**Comment by doronbehar** [comment] 2021-01-04 20:55
Still important.

**Comment by gytis-ivaskevicius** [comment] 2021-04-08 10:09
Welp, this is the moment I have been training my whole life. Ahem... It is still important!!

**Comment by randomnetcat** [comment] 2021-04-29 04:06
> Unfortunately, that solution will break whenever one of its SNAPSHOT dependencies publishes a new version. In general, you can't make a fixed-output derivation from the dependencies fetched for a build, because Gradle allows dynamic dependency versions and can resolve different artifacts from run to run. Therefore, you need tooling to extract the resolved artifact sources in order to make the build reproducible.

As of Gradle 6.2, Gradle can verify hashes and signatures of artifacts and metadata. See https://docs.gradle.org/current/userguide/dependency_verification.html

**Comment by bobvanderlinden** [comment] 2024-04-21 06:16
Some updates:

https://github.com/NixOS/nixpkgs/pull/272380 is an effort to have a setup hook available for gradle projects in nixpkgs.

https://github.com/NixOS/GSoC/issues/19 is a project proposal for Google Summer of Code to create better gradle tooling.

**Comment by tadfisher** [comment] 2024-05-30 01:40
[gradle2nix v2](https://github.com/tadfisher/gradle2nix/pull/62) is available for testing, with a novel approach to extracting artifact information by leveraging Gradle's module cache. I have successfully compiled Kotlin from source with it, which is no small feat. Please give it a try, and I intend to contribute this to nixpkgs if all goes well.

**Comment by Atemu** [comment] 2024-10-24 17:18
https://github.com/NixOS/nixpkgs/pull/272380 has been merged and useable for a while now.

**Closed by Atemu** 2024-10-24 17:18 UTC
Labels: 0.kind: enhancement
