### ISSUE TITLE
rpcbind service fails breaking some tests

### ISSUE THREAD

**Issue by 7c6f434c** [NixOS/nixpkgs#175339] opened 2022-05-29 19:14 UTC
### Describe the bug

In NixOS VM tests, `rpcbind` service sometimes fails to start. This breaks e.g. GlusterFS tests.

### Steps To Reproduce

Building `nixosTests.glusterfs` — GlusterFS service fails due to dependency on RPC Bind service.

See also https://github.com/NixOS/nixpkgs/pull/174688

### Expected behavior

Some result related to GlusterFS.

### Notify maintainers

Have not yet had time to bisect and determine what's going on.

**Comment by tylerjl** [comment] 2022-11-21 03:17
Hey, @7c6f434c! I started down this path looking for an updated Glusterfs package, then found the paused PR, which linked here. Fortunately, I think I know the root cause.

As you noted, the `glusterd` failure is due to a dependency failure on `rpcbind` - the error message in journald is:

> Nov 21 00:45:19 server1 rpcbind[475]: rpcbind: /var/run/rpcbind.lock: No such file or directory

This was sort of confusing, but I found [this Fedora issue](https://bugzilla.redhat.com/show_bug.cgi?id=1401561#c38) that led me to `systemd-tmpfiles`. The NixOS `/etc/tmpfiles.d/var.conf` config includes:

    L /var/run - - - - ../run

So my suspicion is that `rpcbind` starts before `systemd-tmpfiles-setup.service` and can't check for the lockfile. Since there's no `var-run.mount` unit, which was my first guess, I've instead been adding `wants` and `after` tied to `systemd-tmpfiles-setup.service`, which makes the tests pass. The diff that makes this work is:

```patch
diff --git a/nixos/tests/glusterfs.nix b/nixos/tests/glusterfs.nix
index ef09264a021..2023a51435d 100644
--- a/nixos/tests/glusterfs.nix
+++ b/nixos/tests/glusterfs.nix
@@ -15,6 +15,11 @@ let
     networking.firewall.enable = false;
     services.glusterfs.enable = true;
 
+    systemd.services.rpcbind = {
+      wants = [ "systemd-tmpfiles-setup.service" ];
+      after = [ "systemd-tmpfiles-setup.service" ];
+    };
+
     # create a mount point for the volume
     boot.initrd.postDeviceCommands = ''
       ${pkgs.e2fsprogs}/bin/mkfs.ext4 -L data /dev/vdb
```

Obviously we should probably make this fix in NixOS proper, but I want to double-check with you that such a wider-impact change is safe to make. The proposed _global_ fix for NixOS would be:

```patch
diff --git a/nixos/modules/services/networking/rpcbind.nix b/nixos/modules/services/networking/rpcbind.nix
index aa04214debb..d0c392d055b 100644
--- a/nixos/modules/services/networking/rpcbind.nix
+++ b/nixos/modules/services/networking/rpcbind.nix
@@ -35,6 +35,8 @@ with lib;
 
     systemd.services.rpcbind = {
       wantedBy = [ "multi-user.target" ];
+      wants = [ "systemd-tmpfiles-setup.service" ];
+      after = [ "systemd-tmpfiles-setup.service" ];
     };
 
     users.users.rpc = {
```

@7c6f434c thoughts/feedback? I can PR the fix if this all sounds right.

**Comment by 7c6f434c** [comment] 2022-11-21 18:53
The real problem is that I am competent about neither rpcbind nor systemd-tmpfiles (otherwise I would try to write a more sensible complaint).

Maybe PR the change (if it indeed fixes rpcbind judging from logs + fixes GlusterFS tests + doesn't break any NixOS tests that passed right before) and see if more competent people show up? It does feel to me that ideally tmpfiles should not depend on rpcbind and if they do (dunno, because we have /tmp on GlusterFS???) we are doomed anyway…

**Comment by tylerjl** [comment] 2022-11-21 19:04
> The real problem is that I am competent about neither rpcbind nor systemd-tmpfiles

You and I are in the same boat, friend :joy: I'm only rpcbind-aware as it applies to GlusterFS, so I don't count myself as an expert, either.

The only reason I feel confident enough to PR a fix is that all the pieces line up here and the passing tests make me think that this does indeed strike at the root cause. If NixOS is shipping with that tmpfiles configuration to bootstrap `/var/run`, then I think it makes sense for the downstream NixOS module to accomodate how NixOS is handling `/var/run`. So my initial instinct of patching upstream `rpcbind` _probably_ doesn't apply since distros are probably handling `/var/run` differently. 

I'll PR the change and we can see about additional feedback for us.

**Comment by tylerjl** [comment] 2023-04-07 16:10
I'm feeling pretty confident that #202245 fixed the rpcbind problem - are there any nixosTests that should be re-enabled now that rpcbind reliably runs? I looked around for disabled tests but am not sure where those might live, if any are still disabled. Otherwise, I think we can close this :crossed_fingers:

**Comment by 7c6f434c** [comment] 2023-04-07 17:34
(looked at the tests, doesn't look like there is a ton of disabled ones)

**Closed** 2023-04-07 17:34 UTC
Labels: 0.kind: bug, 6.topic: testing
