### ISSUE TITLE
Package request: astrojs-language-server

### ISSUE THREAD

**Issue by hervyqa** [NixOS/nixpkgs#280404] opened 2024-01-12 03:03 UTC
**Project description**

Astro language server.
(@astrojs/language-server)

**Metadata**

* homepage URL: https://github.com/withastro/language-tools
* source URL: https://github.com/withastro/language-tools/tree/main/packages/language-server
* license: MIT
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment] 2024-01-12 09:40
Duplicate of https://github.com/NixOS/nixpkgs/issues/270992 https://github.com/NixOS/nixpkgs/issues/255184 https://github.com/NixOS/nixpkgs/issues/221330

Upstream issue: https://github.com/NixOS/nixos-search/issues/293

**Closed by donovanglover** 2024-01-12 09:40 UTC
Labels: 0.kind: packaging request

**Comment by hervyqa** [comment] 2024-01-12 23:55
this bug is interesting. thanks
