### ISSUE TITLE
nixos-rebuild switch fails with error: Nix daemon out of memory

### ISSUE THREAD

**Issue by tex** [NixOS/nixpkgs#36799] opened 2018-03-11 13:43 UTC
## Issue description
nixos-rebuild switch fails with error: Nix daemon out of memory

There is 4GiB on the system and I has never had problem with this.

### Steps to reproduce
milan@nixos> sudo nixos-rebuild switch                                                                                                                 /etc/nixos/nixpkgs
[sudo] password for milan: 
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/g69sqs5i79rmgrm5vb9gr57dnfb91frz-python-2.7.14-env.drv
  /nix/store/41l5cqahbczx2clvs126b3gxwzcf8jgf-neovim.drv
  /nix/store/bk9dbbgkqxyvwwm8mkzb67lvrcfydf4g-android-studio-3.0.1.0.drv
  /nix/store/ky344y46cw1jqamp51rcdzczr6zzibmq-nixos-version.drv
  /nix/store/pyyx4zrsfzg1hc50wwn8a7gad9fyavla-zathura-with-plugins-0.3.8.drv
  /nix/store/zh0ayk8jxas29i2y3xq5dkkfwdwjhd7l-firefox-58.0.2.drv
  /nix/store/102s4hv675s4a5mbk4rbpaz70g7pxhfy-system-path.drv
  /nix/store/1sm5da2cql2iqciangds255x35313si2-unit-nix-optimise.service.drv
  /nix/store/23x8dp5jgyg27dbgznpaf0r2id6frcbl-unit-script.drv
  /nix/store/jrqg78wglffvdbsw1820xahm15p0cnrw-dbus-1.drv
  /nix/store/398hdgczh39j2h25dr8ygavf13hy3si7-unit-dbus.service.drv
  /nix/store/4j0yhkc6r6izkrnwl9v435j97jsd8il9-unit-cups.service.drv
  /nix/store/4npdbbzla7arrmrxjahgjgg8gs781hj7-unit-docker.service.drv
  /nix/store/7d59zyr56y0b4zwq3m9pr4q6daa1vw4g-unit-polkit.service.drv
  /nix/store/9l1ghy69h6ihhims4nrkzmlrwxzmpryf-unit-udisks2.service.drv
  /nix/store/nl6j89cxigrc1bpvdambz0711vd219s8-unit-script.drv
  /nix/store/cna10jxhafzyahl82vm8jh881l1vs8xn-unit-nix-gc.service.drv
  /nix/store/jrczfcm7892yi0w17f55alp7gnlbv4jm-unit-script.drv
  /nix/store/diaxnri3im9wfh2mjw6h8jksj79k7imk-unit-docker-prune.service.drv
  /nix/store/sscxqqhf09hx52nh702m6is2qgl10ndl-unit-script.drv
  /nix/store/l63baiq9szxalz6gmd1v41q15v3670cd-unit-nixos-upgrade.service.drv
  /nix/store/m78wmgbzka69aawdnwmvfdcylxh060ly-unit-systemd-fsck-.service.drv
  /nix/store/xw4dgz07j1fq1yd3iss9sh8n6pip4l6y-unit-nix-daemon.service.drv
  /nix/store/zs0qr2zj7vj7yycd0fam324qdwgc9xzz-unit-systemd-udevd.service.drv
  /nix/store/2bhv9x69ibgzfxlwcd1zng9p9dbqc59k-system-units.drv
  /nix/store/35a4azib8hqai8nxbg2z8pkpb3qws3f9-udev-rules.drv
  /nix/store/4bk0gwxmm2dcrhxw4ayi3fhx1hawd6d3-etc-os-release.drv
  /nix/store/6myp0cyz0nvdidnvkl0cw1mgksqq9jx5-opengl-drivers.drv
  /nix/store/929fsgvjmx5hwrr1mz8x84yz5f2qf10f-etc-zshenv.drv
  /nix/store/mkcb4cpcpaabkddpq88hbrambm9lnbgh-xsession.drv
  /nix/store/m1pvd8fgf8sjhg8bxnsyg3941jl2i3p1-desktops.drv
  /nix/store/9impviksb2g0hchy7w5i2ldc4d4pdg7i-lightdm.conf.drv
  /nix/store/9zf2yi3jprasqgwhdq7wmdv5vz6vpys8-hwdb.bin.drv
  /nix/store/dw96kyrh9ipb7m9d6h278kpv5vjq6l4j-firmware.drv
  /nix/store/fjza382aqlwl72v4biim0a46ydq4k9w9-kernel-modules-shrunk.drv
  /nix/store/iaj2cxz63z1k2dirlq4wqfqjvj3zf39z-stage-1-init.sh.drv
  /nix/store/av2wx1nkjvxgd8gj1lfxhq3adwhh5ra4-initrd.drv
  /nix/store/b6a6d8rxf5wk68l6mnlzc9fqr1j6n786-user-units.drv
  /nix/store/gjaylzr74ygxg9glzj7g9yfmjrzr4g12-etc-profile.drv
  /nix/store/i457pgqzkj7jz2dmdkrcrgv1gyclax68-issue.drv
  /nix/store/qrvjyimsxjd5r4i5n078z8r5cnxfbgs2-etc-nixos.conf.drv
  /nix/store/lhwridw6vpdil5wh2683w36dpzm9adx2-etc.drv
  /nix/store/da31akzhyjd77yjrya1y212z04svsjl8-nixos-system-nixos-18.09.git.beff602.drv
these paths will be fetched (303.28 MiB download, 2120.38 MiB unpacked):
  /nix/store/0iyb2x555adgmq0ss04vp6v5sj6r7whw-uuid-types-1.0.3
  /nix/store/0k5x5aafgmhf3sxirg90z0pn798078hq-transformers-compat-0.5.1.4
  /nix/store/15wcrblf4jyj2llkr4lsx01b3bv21l1s-vector-0.12.0.1
  /nix/store/18gbwmpdyz60sm0nf2z2rmp2q6g2yif7-pandoc-types-1.17.3.1
  /nix/store/1m5m4n897affa0hvzrxjak343kq3r5zh-scientific-0.3.5.2-doc
  /nix/store/1v2xk00qaz77xvwz4c3ay1lia0x5087l-sweethome3d-application-5.4
  /nix/store/2a82psq5lsrxgdzp125sssd3avss0783-xfce4-power-manager-1.4.4
  /nix/store/2fsq0q5xavwfwccn86g3wqa5rmq0cfj0-libreoffice-5.4.5.1
  /nix/store/2vm5r0yag53rncd6i31pd208wh1rcv79-samba-4.7.5-dev
  /nix/store/33dljxk58gk44jhjylfrdlnaww3rqwds-xfce4-session-4.12.1
  /nix/store/3fz6ng0jq6pyj9s7prl7pzj2c25q0j81-th-abstraction-0.2.6.0-doc
  /nix/store/451q96qvfl6j59im6ar3pxhnivrmgav1-xfdesktop-4.12.3
  /nix/store/48dlh166fcf8l464s4m5p9sk3marf3zm-tagged-0.8.5-doc
  /nix/store/4f0i1nlgxai1chji4jqxz3pqwg5k6bl6-thunar-build-1.6.10
  /nix/store/5k964klfarykq1fxj075zpznf87vp5k0-thunar-build-with-plugins
  /nix/store/5n6hvblinrnsy4imz4as1h8vrbgfv54j-integer-logarithms-1.0.2
  /nix/store/5pba8id1nbykphxjd1cixqbxsqkzc79x-tf-random-0.5-doc
  /nix/store/5pdi7kl32x4bq5lkp3mdpsnb8hlf5jbz-dlist-0.8.0.4
  /nix/store/676x20533y2w8y27ghbj3nbya2mym539-parsec-3.1.13.0
  /nix/store/6c12xrl02h1naqfjvlm0098hpan8wc70-text-1.2.2.2
  /nix/store/6nk36yibb7qghp9sj2cg5qdl7lgw5sb2-network-uri-2.6.1.0
  /nix/store/74x7fiyl9cq3viiyd2i4ihxx54pdhgv3-tagged-0.8.5
  /nix/store/84xwlvf2grfbzrnipzq34kbasynia5k0-thunar-1.6.10
  /nix/store/8nwghvpinv8zp0l5bl2s28lqf6cf7ypn-cups-files.conf
  /nix/store/8wiplirpxz6zqs36wrpbiwy503lp12iv-kio-5.43.0-bin
  /nix/store/9lzgalk5cxskzajcl7smcy33q9inrvgc-scientific-0.3.5.2
  /nix/store/9rnd4impqpp0sryhz0a9pqy14fg8sk9i-aeson-1.2.4.0
  /nix/store/b9k5wkv3yrmp9bmv2hykhkyjw2kcwxg5-QuickCheck-2.10.1
  /nix/store/csylin138r0rjjpxq354mic37b2nigkw-hashable-1.2.6.1-doc
  /nix/store/d62r06k76yb0lz71gnzm51vmyg1jm7jc-random-1.1
  /nix/store/dqmm29pk69s113g3zi6g377y5h2y0x2b-aeson-1.2.4.0-doc
  /nix/store/dvij2ids5lvfh9dy59nd86248zq6d9q9-vlc-2.2.8
  /nix/store/fkx1aicsb82kf20xlr0h47w5zfrz0vh2-HTTP-4000.3.9
  /nix/store/g02yi160ygyqiy2dwyznvb8csmkrhcxw-udisks-2.1.6
  /nix/store/g3609zfc4amg1ib46gnghdnjicb0158q-mtl-2.2.2
  /nix/store/g7mjahj68kaa6bjas00sxzkh8z4d6y06-unordered-containers-0.2.8.0
  /nix/store/g8amkgj2kbq4zys63qd3i85kr3c6g8zz-xfce4-volumed-pulse-0.2.2
  /nix/store/gd2fknps5h9n6hnzf24ch0mvq7jkh88j-xfce4-panel-4.12.1
  /nix/store/gd9ifbkzal7cnwznbsz7hfawm1967hsz-xfce4-mixer-4.10.0
  /nix/store/gm3g692as4s6agr20xbqglbigwwra8mg-th-abstraction-0.2.6.0
  /nix/store/gr13qbnp56c61x4qmy5052px22mfinnz-primitive-0.6.3.0
  /nix/store/gvgcs91cj0vx12i7ma71hbrwnjwxc8cm-filelight-17.12.2
  /nix/store/h2xgs873nppynv0gsryarpcb7daaz4gh-vector-0.12.0.1-doc
  /nix/store/hnpnlqxjgblkl3j9a5qiszh379f0vxnp-youtube-dl-2018.03.03
  /nix/store/ihgnp6vih9hw0ndlcy6p55vr18pj8npc-tf-random-0.5
  /nix/store/ika1s7gk8wfiar87p1m96vm7mdmscf94-syb-0.7-doc
  /nix/store/iyavi02xwi3s2gvlvb99zfk3vzr3143s-cups-progs
  /nix/store/jfjq13ilayrk5c49agpbnjld8v11wj1s-unordered-containers-0.2.8.0-doc
  /nix/store/jzdk6s92l2hwnfk0jiil5vmxc5qn2l2d-gvfs-1.34.2.1
  /nix/store/k0zpn9jgdwqm1bqijz2n9c3xd8klnhx5-attoparsec-0.13.2.2
  /nix/store/k39npbbj7m6p62y9g8g73xm19vgarxng-time-locale-compat-0.1.1.3-doc
  /nix/store/kl50jjg6740c8dqpb0p62pfi6n9lvcn7-ghc-8.2.2
  /nix/store/lqb6gbz1xw6avnlgvr5y57nmc8d7aglc-attoparsec-0.13.2.2-doc
  /nix/store/m51rwaiq76gzpyvrl8wk09cpgp7mg238-udiskie-1.7.3
  /nix/store/mlpkkl5h1aqyp3ss6lzgsbfw4xqlx2vl-krita-3.3.3
  /nix/store/mp84l7a53nm2waqywzdcdy5p26hjnary-parsec-3.1.13.0-doc
  /nix/store/n79bfnrb892l8plj7r914lcr8kd5pv99-pandoc-2.0.6-data
  /nix/store/nafx1d6qnxzv9f9v86xmxk1p94zhsqjn-pandoc-types-1.17.3.1-doc
  /nix/store/nj2ak3b9k9961nrphaqsnjccwffvbv1q-udisks-2.1.6-dev
  /nix/store/npli173hgkgf3mq6li8762g4k7sbgsnz-pandoc-2.0.6
  /nix/store/nw5niij0dd0h6yzfgsvr0qy9clq1wvkk-NetworkManager-strongswan-1.4.1
  /nix/store/pc1y2c9qywvywgrv6zb69czhsqjg7rag-hashable-1.2.6.1
  /nix/store/pph1bkji76g777b0kafvwi7k2gjx3paj-QuickCheck-2.10.1-doc
  /nix/store/pq92q96p88lvcgdi9l9hc560vpv3sian-network-2.6.3.4
  /nix/store/qavyj0r3apzl0z1dsykizvwkd3krirah-additional-cups-backends
  /nix/store/qgb8jlv7qfs1jr2kmh59i48s6f3cf5nr-transformers-compat-0.5.1.4-doc
  /nix/store/r4m9j4a8fnx9na4sc4idx0aaffcfb9n1-cups-progs
  /nix/store/rb0wwpy3j8a5354sm5sd4bnqmdcq4xp9-syb-0.7
  /nix/store/sd5259rmawhis9d5sf0cqwfy1yinbjjv-samba-4.7.5
  /nix/store/sfnm28m6cc862r5laq0115jmc7pfygi2-old-locale-1.0.0.7
  /nix/store/sz0zd51pjzsk6ph76pkwn2v009y4ia1w-zathura-pdf-mupdf-0.3.2
  /nix/store/v1if4g2hm92vsmyi974aihv0i2irf8bm-gvfs-1.34.2.1
  /nix/store/wx7l2r8xy7d0gy3h27prhmy0kl45mplj-kparts-5.43.0-bin
  /nix/store/x5xb3hbbc91mprqakcl98cg78h0pm9kw-python2.7-htmltreediff-v0.1.2
  /nix/store/xv2fzk8va20xgmmh0bnzzhjhzhmky4by-base-compat-0.9.3
  /nix/store/xx507b2my3bzhj5fb3ra2sz1c3sp288h-text-1.2.2.2-doc
  /nix/store/yc8hddn0dc3hyqhfaj6qcl8bgx4dc6gb-strongswan-5.6.2
  /nix/store/ypjkc18a8z5l6v2n7vgd17i785y8hq7r-uuid-types-1.0.3-doc
  /nix/store/yz0zwsgnnnndqkyx7620a28bk36gs6z9-xfce4-screenshooter-1.8.2
  /nix/store/z09nh3l3hpdvhaprqhi6sky21zbkrh48-time-locale-compat-0.1.1.3
building '/nix/store/4bk0gwxmm2dcrhxw4ayi3fhx1hawd6d3-etc-os-release.drv'...
building '/nix/store/i457pgqzkj7jz2dmdkrcrgv1gyclax68-issue.drv'...
building '/nix/store/dw96kyrh9ipb7m9d6h278kpv5vjq6l4j-firmware.drv'...
building '/nix/store/6myp0cyz0nvdidnvkl0cw1mgksqq9jx5-opengl-drivers.drv'...
copying path '/nix/store/kl50jjg6740c8dqpb0p62pfi6n9lvcn7-ghc-8.2.2' from 'https://cache.nixos.org'...
copying path '/nix/store/8wiplirpxz6zqs36wrpbiwy503lp12iv-kio-5.43.0-bin' from 'https://cache.nixos.org'...
created 79 symlinks in user environment
copying path '/nix/store/2fsq0q5xavwfwccn86g3wqa5rmq0cfj0-libreoffice-5.4.5.1' from 'https://cache.nixos.org'...
created 341 symlinks in user environment
copying path '/nix/store/n79bfnrb892l8plj7r914lcr8kd5pv99-pandoc-2.0.6-data' from 'https://cache.nixos.org'...
copying path '/nix/store/x5xb3hbbc91mprqakcl98cg78h0pm9kw-python2.7-htmltreediff-v0.1.2' from 'https://cache.nixos.org'...
copying path '/nix/store/wx7l2r8xy7d0gy3h27prhmy0kl45mplj-kparts-5.43.0-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/mlpkkl5h1aqyp3ss6lzgsbfw4xqlx2vl-krita-3.3.3' from 'https://cache.nixos.org'...
copying path '/nix/store/gvgcs91cj0vx12i7ma71hbrwnjwxc8cm-filelight-17.12.2' from 'https://cache.nixos.org'...
copying path '/nix/store/sd5259rmawhis9d5sf0cqwfy1yinbjjv-samba-4.7.5' from 'https://cache.nixos.org'...
copying path '/nix/store/yc8hddn0dc3hyqhfaj6qcl8bgx4dc6gb-strongswan-5.6.2' from 'https://cache.nixos.org'...
copying path '/nix/store/qavyj0r3apzl0z1dsykizvwkd3krirah-additional-cups-backends' from 'https://cache.nixos.org'...
copying path '/nix/store/nw5niij0dd0h6yzfgsvr0qy9clq1wvkk-NetworkManager-strongswan-1.4.1' from 'https://cache.nixos.org'...
copying path '/nix/store/r4m9j4a8fnx9na4sc4idx0aaffcfb9n1-cups-progs' from 'https://cache.nixos.org'...
copying path '/nix/store/2vm5r0yag53rncd6i31pd208wh1rcv79-samba-4.7.5-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/8nwghvpinv8zp0l5bl2s28lqf6cf7ypn-cups-files.conf' from 'https://cache.nixos.org'...
copying path '/nix/store/1v2xk00qaz77xvwz4c3ay1lia0x5087l-sweethome3d-application-5.4' from 'https://cache.nixos.org'...
copying path '/nix/store/iyavi02xwi3s2gvlvb99zfk3vzr3143s-cups-progs' from 'https://cache.nixos.org'...
copying path '/nix/store/ika1s7gk8wfiar87p1m96vm7mdmscf94-syb-0.7-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/48dlh166fcf8l464s4m5p9sk3marf3zm-tagged-0.8.5-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/xx507b2my3bzhj5fb3ra2sz1c3sp288h-text-1.2.2.2-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/5pba8id1nbykphxjd1cixqbxsqkzc79x-tf-random-0.5-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/csylin138r0rjjpxq354mic37b2nigkw-hashable-1.2.6.1-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/pph1bkji76g777b0kafvwi7k2gjx3paj-QuickCheck-2.10.1-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/mp84l7a53nm2waqywzdcdy5p26hjnary-parsec-3.1.13.0-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/1m5m4n897affa0hvzrxjak343kq3r5zh-scientific-0.3.5.2-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/3fz6ng0jq6pyj9s7prl7pzj2c25q0j81-th-abstraction-0.2.6.0-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/lqb6gbz1xw6avnlgvr5y57nmc8d7aglc-attoparsec-0.13.2.2-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/k39npbbj7m6p62y9g8g73xm19vgarxng-time-locale-compat-0.1.1.3-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/qgb8jlv7qfs1jr2kmh59i48s6f3cf5nr-transformers-compat-0.5.1.4-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/g02yi160ygyqiy2dwyznvb8csmkrhcxw-udisks-2.1.6' from 'https://cache.nixos.org'...
copying path '/nix/store/jfjq13ilayrk5c49agpbnjld8v11wj1s-unordered-containers-0.2.8.0-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/ypjkc18a8z5l6v2n7vgd17i785y8hq7r-uuid-types-1.0.3-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/h2xgs873nppynv0gsryarpcb7daaz4gh-vector-0.12.0.1-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/jzdk6s92l2hwnfk0jiil5vmxc5qn2l2d-gvfs-1.34.2.1' from 'https://cache.nixos.org'...
copying path '/nix/store/v1if4g2hm92vsmyi974aihv0i2irf8bm-gvfs-1.34.2.1' from 'https://cache.nixos.org'...
copying path '/nix/store/dqmm29pk69s113g3zi6g377y5h2y0x2b-aeson-1.2.4.0-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/nj2ak3b9k9961nrphaqsnjccwffvbv1q-udisks-2.1.6-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/dvij2ids5lvfh9dy59nd86248zq6d9q9-vlc-2.2.8' from 'https://cache.nixos.org'...
copying path '/nix/store/nafx1d6qnxzv9f9v86xmxk1p94zhsqjn-pandoc-types-1.17.3.1-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/m51rwaiq76gzpyvrl8wk09cpgp7mg238-udiskie-1.7.3' from 'https://cache.nixos.org'...
copying path '/nix/store/gd2fknps5h9n6hnzf24ch0mvq7jkh88j-xfce4-panel-4.12.1' from 'https://cache.nixos.org'...
error: Nix daemon out of memory

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.7, NixOS, 18.09.git.f5f71c0 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(milan): `"nixos-17.03pre96925.1c50bdd"`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/nixpkgs`

**Comment by davidak** [comment] 2018-03-11 14:11
@tex do you have swap enabled?

**Comment by tex** [comment] 2018-03-11 14:21
no swap

KiB Mem :  3924140 total,  1229156 free,   421604 used,  2273380 buff/cache

never before any not enought memory problem 

but good point, will try to enable swap in a file

**Comment by davidak** [comment] 2018-03-11 14:55
It's recommended to have swap. 4 GB is not so much these days.

**Comment by dtzWill** [comment] 2018-03-11 15:44
Still, unfortunate that 4GB isn't enough! :disappointed:

**Comment by davidak** [comment] 2018-03-11 16:00
There are some open issues in the Nix repo about the memory usage:
https://github.com/NixOS/nix/search?q=memory&state=open&type=Issues&utf8=%E2%9C%93

This is probably a duplicate of https://github.com/NixOS/nix/issues/1681

**Comment by tex** [comment] 2018-03-11 19:19
Adding swap helped. Created 4GiB file and used it as swap. What I saw is that nix-daemon usually want reasonable amount of ram, but I saw one spike that required 1.4GiB - with my free ram ~1.0GiB that probably caused the error.
The thing is that previous year I had the same amount of RAM and I have never seen this out of memory error. Something has change in few last days?
Feel free to close this issue...

**Comment by rawtaz** [comment] 2018-03-11 22:08
@tex Please close this issue as it's resolved (you have a Close button in your commenting area).

**Closed** 2018-03-12 05:53 UTC

**Comment by AresAndy** [comment] 2019-01-07 15:18
Unfortunately I need this to be reopened.
I just encountered the same issue with NixOS 18.09 (Nix is 2.1.3). Even though I am monitoring memory usage, and it does not reach the limit. At first glance I thought 4GB of RAM + 2GB of swap was insufficient, I added another GiB of swap, still nothing

**Comment by mstone** [comment] 2019-01-30 20:47
I am also running into this issue on an 8GB machine (w/o swap).

As a workaround, I am `nixos-rebuild build`ing a smaller version of my actual target configuration from which I am going to try to either build the full version (with an up-to-date `nix-daemon`) or revert.
