### ISSUE TITLE
difference package version between nix-shell and nix-env

### ISSUE THREAD

**Issue by clojurians-org** [NixOS/nixpkgs#70959] opened 2019-10-11 08:02 UTC
i have no idea why nix-shell use the old cargo-1.32.0 version.
```
[nix-shell:~/my-repo]$ nix-shell --version
nix-shell (Nix) 2.2.2

[nix-shell:~/my-repo]$ nix-env --version
nix-env (Nix) 2.2.2

[nix-shell:~/my-repo]$ nix-channel --list
nixpkgs https://nixos.org/channels/nixos-19.03
nixpkgs-static https://github.com/NixOS/nixpkgs/archive/88ae8f7d.tar.gz
nixpkgs-unstable https://nixos.org/channels/nixpkgs-unstable

[nix-shell:~/my-repo]$ nix-env -f '<nixpkgs-unstable>' -qa cargo | head
cargo-1.37.0

[nix-shell:~/my-repo]$ nix-shell '<nixpkgs-unstable>' -p cargo --run 'cargo new aaa' 
these paths will be fetched (107.63 MiB download, 330.38 MiB unpacked):
  /nix/store/2admd4nddkppaq6viiihp8fcg5cgf5mn-rustc-1.32.0
  /nix/store/5ki3q47nihlmyx5h89pbxb1v972fjr6b-libgit2-0.26.6
  /nix/store/a0rz4s781sw9gfi2hvncw577ahh74x3r-libffi-3.2.1
  /nix/store/bz1afvq6whfiqi7i64cnw7wrdvpqp3f7-llvm-7.0.1-lib
  /nix/store/lxwiqmrq3j16s9p2vn9cg6fkl4i1cx1f-cargo-1.32.0
  /nix/store/mdqgbiwlri4mrn1wlk371vxncfpy706z-http-parser-2.9.0
  /nix/store/v0rhfdxfhr29rqj45fng3gjp58wk5w43-nss-cacert-3.46
  /nix/store/v29r87frw519ypibh0khi86q3lfq75fn-libxml2-2.9.9
copying path '/nix/store/v0rhfdxfhr29rqj45fng3gjp58wk5w43-nss-cacert-3.46' from 'https://cache.nixos.org'...
copying path '/nix/store/mdqgbiwlri4mrn1wlk371vxncfpy706z-http-parser-2.9.0' from 'https://cache.nixos.org'...
copying path '/nix/store/a0rz4s781sw9gfi2hvncw577ahh74x3r-libffi-3.2.1' from 'https://cache.nixos.org'...
copying path '/nix/store/v29r87frw519ypibh0khi86q3lfq75fn-libxml2-2.9.9' from 'https://cache.nixos.org'...
copying path '/nix/store/5ki3q47nihlmyx5h89pbxb1v972fjr6b-libgit2-0.26.6' from 'https://cache.nixos.org'...
^Cerror: interrupted by the user

```

**Comment by veprbl** [comment] 2019-10-11 19:04
@clojurians-org 
I believe nix-shell ignores the path argument and always uses `<nixpkgs>` for the "-p" option.

**Comment by schmittlauch** [comment] 2019-10-11 23:05
@clojurians-org Unfortunately, @veprbl is correct. `nix-shell` and `nix-env` have a different argument structure.
For using the nixpkgs-unstable channel with `nix-shell`, you need to invoke it as `nix-shell -I nixpkgs="<nixpkgs-unstable>" -p cargo --run "cargo --version`

**Comment by schmittlauch** [comment] 2019-10-11 23:07
Unless you suspect a bug, such future questions are probably better off at the [NixOS Community Discourse Forum](https://discourse.nixos.org).

**Comment by clojurians-org** [comment] 2019-10-12 00:20
thanks. i refer the command for man page:
```
EXAMPLES
       To build the dependencies of the package Pan, and start an interactive shell in which to build it:

           $ nix-shell '<nixpkgs>' -A pan
           [nix-shell]$ unpackPhase
           [nix-shell]$ cd pan-*
           [nix-shell]$ configurePhase
           [nix-shell]$ buildPhase
           [nix-shell]$ ./pan/gui/pan

       To clear the environment first, and do some additional automatic initialisation of the interactive shell:

           $ nix-shell '<nixpkgs>' -A pan --pure \
               --command 'export NIX_DEBUG=1; export NIX_CORES=8; return'
```

**Comment by veprbl** [comment] 2019-10-19 22:34
Closing as this is not a bug in nixpkgs

**Closed by veprbl** 2019-10-19 22:34 UTC
Labels: 0.kind: question
