### ISSUE TITLE
`python312Packages.triton` build failure on x86_64-linux as of `dc74870c`

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#356042] opened 2024-11-15 00:20 UTC
## Issue description
Build of `python312Packages.triton` failed on x86_64-linux as of dc74870c2b7588fcbe9ee3e5c3f5035a8aea8599. This is currently breaking `python3Packages.torch-bin`.

```
error: builder for '/nix/store/cf7szbrnldr88h9v8n3qvyz4rm2mbp4n-python3.12-triton-3.1.0.drv' failed with exit code 1;
       last 10 log lines:
       > checking for references to /build/ in /nix/store/afirz64vp03cvc0n6cr6zy525dizan1q-python3.12-triton-3.1.0...
       > patching script interpreter paths in /nix/store/afirz64vp03cvc0n6cr6zy525dizan1q-python3.12-triton-3.1.0
       > shrinking RPATHs of ELF executables and libraries in /nix/store/q7gmkdmai5my9i11sainq00rizf0fqrn-python3.12-triton-3.1.0-dist
       > checking for references to /build/ in /nix/store/q7gmkdmai5my9i11sainq00rizf0fqrn-python3.12-triton-3.1.0-dist...
       > patching script interpreter paths in /nix/store/q7gmkdmai5my9i11sainq00rizf0fqrn-python3.12-triton-3.1.0-dist
       > Rewriting #!/nix/store/px2nj16i5gc3d4mnw5l1nclfdxhry61p-python3-3.12.7/bin/python3.12 to #!/nix/store/px2nj16i5gc3d4mnw5l1nclfdxhry61p-python3-3.12.7
       > wrapping `/nix/store/afirz64vp03cvc0n6cr6zy525dizan1q-python3.12-triton-3.1.0/bin/proton'...
       > Rewriting #!/nix/store/px2nj16i5gc3d4mnw5l1nclfdxhry61p-python3-3.12.7/bin/python3.12 to #!/nix/store/px2nj16i5gc3d4mnw5l1nclfdxhry61p-python3-3.12.7
       > wrapping `/nix/store/afirz64vp03cvc0n6cr6zy525dizan1q-python3.12-triton-3.1.0/bin/proton-viewer'...
       > chmod: cannot access '/nix/store/afirz64vp03cvc0n6cr6zy525dizan1q-python3.12-triton-3.1.0/lib/python3.12/site-packages/triton/third_party/cuda/bin/ptxas': No such file or directory
       For full logs, run 'nix log /nix/store/cf7szbrnldr88h9v8n3qvyz4rm2mbp4n-python3.12-triton-3.1.0.drv'.
error: 1 dependencies of derivation '/nix/store/irh96adazbqn11928iqhjw6xsqwg4333-python3.12-torch-2.5.1.drv' failed to build
```

[full build log](https://github.com/samuela/nixpkgs-upkeep/actions/runs/11847753126)

python3Packages.torch-bin maintainers cc: @junjihashimoto
python312Packages.triton maintainers cc: @SomeoneSerge @Madouura @derdennisop
Other cc: n/a

### Steps to reproduce
1. Checkout nixpkgs at commit dc74870c2b7588fcbe9ee3e5c3f5035a8aea8599
2. Run `nix-build -A python312Packages.triton`

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.0-1025-azure, Ubuntu, 22.04.5 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.16.1`
 - nixpkgs: `/nix/store/w2447bx31visqdf2yd2g93792jsfrpn3-source`
```

Contents of `~/.config/nixpkgs/config.nix`:
```
{ allowUnfree = true; cudaSupport = true; cudaCapabilities = ["8.0"]; }
```

## Misc.
This issue was automatically generated by [nixpkgs-upkeep](https://github.com/samuela/nixpkgs-upkeep).
- [CI workflow](https://github.com/samuela/nixpkgs-upkeep/actions/runs/11847753126) that created this issue.
- Internal tags: 6522401898499021816 7967263956609282610

**Comment by dotlambda** [comment] 2024-12-09 23:10
duplicate of https://github.com/NixOS/nixpkgs/issues/352755

**Closed by dotlambda** 2024-12-09 23:10 UTC
Labels: 0.kind: build failure
