### ISSUE TITLE
Build failure: pkgsStatic.perl

### ISSUE THREAD

**Issue by nrakochy** [NixOS/nixpkgs#347946] opened 2024-10-11 15:44 UTC
### Steps To Reproduce

`nix build -I nixpkgs=flake:github:NixOS/nixpkgs/24.05 nixpkgs#nginx`

### Build log

```
building '/nix/store/lzkwyka929nqvb7jq6gmsa67cax9xwlh-perl-5.38.2.drv'...
error: builder for '/nix/store/lzkwyka929nqvb7jq6gmsa67cax9xwlh-perl-5.38.2.drv' failed with exit code 2;
       last 10 log lines:
       > cc -c -DPERL_CORE -fno-common -DPERL_DARWIN -mmacosx-version-min=11.0 -DNO_POSIX_2008_LOCALE -fno-strict-aliasing -pipe -fstack-protector-strong -I/nix/store/ai5w4kd950rdj7djm4yn565
9rkbcn5h7-libSystem-11.0.0/include -std=c99 -O3 -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wno-declaration-after-statement -Wc++-compat -Wwrite-strings time64.c
       > cc -c -DPERL_CORE -fno-common -DPERL_DARWIN -mmacosx-version-min=11.0 -DNO_POSIX_2008_LOCALE -fno-strict-aliasing -pipe -fstack-protector-strong -I/nix/store/ai5w4kd950rdj7djm4yn565
9rkbcn5h7-libSystem-11.0.0/include -std=c99 -O3 -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wno-declaration-after-statement -Wc++-compat -Wwrite-strings miniperlmain.c
       > cc -mmacosx-version-min=11.0 -fstack-protector-strong -L/nix/store/ai5w4kd950rdj7djm4yn5659rkbcn5h7-libSystem-11.0.0/lib -force_flat_namespace -o miniperl \
       >     opmini.o perlmini.o universalmini.o  gv.o toke.o perly.o pad.o regcomp.o regcomp_debug.o regcomp_invlist.o regcomp_study.o regcomp_trie.o regexec.o dump.o util.o mg.o reentr.o m
ro_core.o keywords.o builtin.o class.o hv.o av.o run.o pp_hot.o sv.o pp.o scope.o pp_ctl.o pp_sys.o peep.o doop.o doio.o utf8.o taint.o deb.o globals.o perlio.o numeric.o mathoms.o locale.o
pp_pack.o pp_sort.o caretx.o dquote.o time64.o  miniperlmain.o
       > DYLD_LIBRARY_PATH=/private/tmp/nix-build-perl-5.38.2.drv-2/perl-5.38.2 ./miniperl -w -Ilib -Idist/Exporter/lib -MExporter -e '<?>' || sh -c 'echo >&2 Failed to build miniperl.  Plea
se run make minitest; exit 1'
       > DYLD_LIBRARY_PATH=/private/tmp/nix-build-perl-5.38.2.drv-2/perl-5.38.2 ./miniperl -Ilib -f write_buildcustomize.pl
       > rm -f pod/perl5382delta.pod
       > /nix/store/n0z3xb9d90qqm8qp13r271x6a9r109gi-bootstrap-stage0-clang/bin/ln -s perldelta.pod pod/perl5382delta.pod
       > DYLD_LIBRARY_PATH=/private/tmp/nix-build-perl-5.38.2.drv-2/perl-5.38.2 ./miniperl -Ilib autodoc.pl
       > make: *** [GNUmakefile:442: pod/perlintern.pod] Killed: 9
```

### Additional context

This appears to be the same issue reported in #295608, which is a Perl bug in 5.38.2 fixed in nixpkgs `staging`. I also tried 

```nix
     nginx-override = pkgs.nginx.overrideAttrs (_final: _prev: {
              withPerl = false;
    });

```
which I would have expected to work.  Since `perl` is defined [as a buildInput](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/servers/http/nginx/generic.nix#L67), perhaps it does not honor the flag for this particular build error. Could this `perl` dependency be made optional? 

It might just work™️  to bump the perl dependency 🤷 

### Notify maintainers

Thanks for taking a look, pinging based on commit history 🙏 

@RaitoBezarius @Izorkin 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.6.0, macOS 14.7`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - 
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Atemu** [comment] 2024-10-13 08:38
> `nix build -I nixpkgs=flake:github:NixOS/nixpkgs/24.05 nixpkgs#nginx`

This doesn't do what you think it does. This builds master, the NIX_PATH modification has no effect with flakes.

> This appears to be the same issue reported in #295608

This is a duplicate of #295608 then.

**Closed by Atemu** 2024-10-13 08:38 UTC
Labels: 0.kind: build failure

**Comment by nrakochy** [comment] 2024-10-13 13:07
What? tldr- nginx is busted in my flake usage. How do I fix it?

**Comment by Atemu** [comment] 2024-10-13 14:29
It will be "busted" until #295608 is resolved.

Please also note that it's pkgsStatic we're talking about here which is not maintained on the same level as the regular old shared glibc `pkgs`. Fixes for pkgsStatic are unlikely to be prioritised or given much attention.

By far the easiest method to fix this is to stop using pkgsStatic.

**Comment by nrakochy** [comment] 2024-10-13 20:44
I added that step to make repro as simple as possible. 

The actual usage I have is adding nginx as a build input in my flake using nixpkgs.

Why is Perl a hard dependency of nginx?

**Comment by Atemu** [comment] 2024-10-13 20:58
> The actual usage I have is adding nginx as a build input in my flake using nixpkgs.

That does not tell me anything. Please clarify.

> Why is Perl a hard dependency of nginx?

Perl is a dependency deep down the dependency tree and used for many things that are required to even build the dependencies of nginx. You're not going to get rid of perl in your build-time closure.

***

We need two things from you:

1. The exact revision of Nixpkgs that you experience the error on.
2. A command that uses this revision of nixpkgs and has a build error.

**Comment by nrakochy** [comment] 2024-10-15 16:07
Unfortunately I do not have a public repo I can share, the aforementioned `nix build` cmd is the simplest repro I have

```
nix build -I nixpkgs=flake:github:NixOS/nixpkgs/24.05 nixpkgs#nginx
```

>  This builds master, the NIX_PATH modification has no effect with flakes.

I suppose I am misunderstanding the `nix build -I` docs. If `nix build` does not honor this path, then I suppose we are at an impasse

<img width="1672" alt="Screenshot 2024-10-15 at 10 57 31 AM" src="https://github.com/user-attachments/assets/4f9c93cd-65bb-4612-8999-fd2c7b261060">

**Comment by Atemu** [comment] 2024-10-16 10:34
We need the exact revision of Nixpkgs you're using. If you cannot give us that, we cannot help you.

You appear to be using flakes, so those should record that info in the lockfiles somewhere.
