### ISSUE TITLE
Package request: mcpelauncher

### ISSUE THREAD

**Issue by Dekomoro** [NixOS/nixpkgs#238155] opened 2023-06-16 22:16 UTC
**Project description**
A launcher for minecraft bedrock for linux that utilizes legitimate copies

**Metadata**

* homepage URL: https://mcpelauncher.readthedocs.io/
* source URL: https://github.com/minecraft-linux/mcpelauncher-manifest
* license: gpl3
* platforms: linux

**Comment by figsoda** [comment] 2023-06-17 12:58
duplicate of #231875

**Closed by figsoda** 2023-06-17 12:58 UTC
Labels: 2.status: duplicate, 0.kind: packaging request
