### ISSUE TITLE
Some node packages broken with `npm ERR! Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by oxalica** [NixOS/nixpkgs#100077] opened 2020-10-09 11:45 UTC
**Describe the bug**
`vscode-extensions.matklad.rust-analyzer` and `vscode-extensions.vadimcn.vscode-lldb` failed to build due to dependencies from nodePackages having `npm install` failure.

I run `git bisect` on it and the first bad commit is 6d7aafccbf9d9f6863d620e1a4378cd5aac8524e , which is part of #96509 and most changes are reverted in #100015 (also merged into master).
But strangely I still got these errors on current master.

Note that both two package are packaged by myself, and I'm not sure if I made it in a wrong way.
I tested some other packages with build dependency to nodePackages like `iosevka` and `spacegun`, but they are built well.

**To Reproduce**
1. Checkout nixpkgs/master (4da09d369baa2200edb9df27fe9c88453b0ea6cf)
2. `nix build -f . vscode-extensions.matklad.rust-analyzer -L`
3. See the build failue.

**Expected behavior**
Built successfully.

**Additional context**

<details>
<summary>Npm log from <code>/build/.npm/_logs/</code> (through breakpointHook and cntr)</summary>

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/bin/node',
1 verbose cli   '/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/bin/npm',
1 verbose cli   '--offline',
1 verbose cli   '--nodedir=/nix/store/zqkl3wh1whmi6c6sl7hlwpwk5nlyfwr7-node-sources',
1 verbose cli   '--production',
1 verbose cli   'install'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.4
4 verbose npm-session d2a1d21844bdc359
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall rust-analyzer@0.4.0-dev
7 info lifecycle rust-analyzer@0.4.0-dev~preinstall: rust-analyzer@0.4.0-dev
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 553ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 5ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 234ms
16 silly install loadAllDepsIntoIdealTree
17 silly fetchPackageMetaData error for es-abstract@1.18.0-next.1 request to https://registry.npmjs.org/es-abstract failed: cache mode is 'only-if-cached' but no cached response available.
18 verbose stack RangeError: Maximum call stack size exceeded
18 verbose stack     at RegExp.test (<anonymous>)
18 verbose stack     at isDepOptional (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:425:27)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:441:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
19 verbose cwd /nix/store/c64sy72n4n1jh7l0gz0gaqhf2qjwk8ph-node_rust-analyzer-0.4.0-dev/lib/node_modules/rust-analyzer
20 verbose Linux 5.4.66
21 verbose argv "/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/bin/node" "/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/bin/npm" "--offline" "--nodedir=/nix/store/zqkl3wh1whmi6c6sl7hlwpwk5nlyfwr7-node-sources" "--production" "install"
22 verbose node v12.18.4
23 verbose npm  v6.14.6
24 error Maximum call stack size exceeded
25 verbose exit [ 1, true ]
```

</details>

Full build log (through `nix log`): https://gist.github.com/oxalica/c29e4722ee6051da246c714158827870

**Notify maintainers**

@oxalica (me)

cc @jtojnar @jonringer 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```yaml
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.66, NixOS, 21.03pre246062.420f89ceb26 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre246062.420f89ceb26"`
 - channels(oxa): `"home-manager, mozilla"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - vscode-extensions.matklad.rust-analyzer
  - vscode-extensions.vadimcn.vscode-lldb
# a list of nixos modules affected by the problem
module:
```

**Comment by jtojnar** [comment] 2020-10-09 15:49
Only a regular update remains from the PR now so I would expect it to be caused by some change in NPM or missed failure during node2nix execution.

See also the debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/bin/node',
1 verbose cli   '/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/bin/npm',
1 verbose cli   '--offline',
1 verbose cli   '--nodedir=/nix/store/zqkl3wh1whmi6c6sl7hlwpwk5nlyfwr7-node-sources',
1 verbose cli   '--production',
1 verbose cli   'install'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.4
4 verbose npm-session 4899ebfe94a1da23
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall rust-analyzer@0.4.0-dev
7 info lifecycle rust-analyzer@0.4.0-dev~preinstall: rust-analyzer@0.4.0-dev
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 572ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 3ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 234ms
16 silly install loadAllDepsIntoIdealTree
17 silly fetchPackageMetaData error for es-abstract@1.18.0-next.1 request to https://registry.npmjs.org/es-abstract failed: cache mode is 'only-if-cached' but no cached response available.
18 verbose stack RangeError: Maximum call stack size exceeded
18 verbose stack     at RegExp.test (<anonymous>)
18 verbose stack     at isDepOptional (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:425:27)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:441:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
18 verbose stack     at failedDependency (/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/lib/node_modules/npm/lib/install/deps.js:457:9)
19 verbose cwd /nix/store/4c16im9hbl792il9jxbwgwjd1dx7jggg-node_rust-analyzer-0.4.0-dev/lib/node_modules/rust-analyzer
20 verbose Linux 5.4.0-48-generic
21 verbose argv "/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/bin/node" "/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/bin/npm" "--offline" "--nodedir=/nix/store/zqkl3wh1whmi6c6sl7hlwpwk5nlyfwr7-node-sources" "--production" "install"
22 verbose node v12.18.4
23 verbose npm  v6.14.6
24 error Maximum call stack size exceeded
25 verbose exit [ 1, true ]
```

Could you try to regenerate the node files?

**Comment by oxalica** [comment] 2020-10-09 18:08
@jtojnar
> Could you try to regenerate the node files?

Of course. And it results in the same failure.
Regenerating `node-packages.nix` does not even change the drv hash of `vscode-extension.vadimcn.vscode-lldb`, which is still `/nix/store/qs4ajisj9hby0cczkmq7j6c1fk9xsvs8-vscode-extension-vscode-lldb.drv`.

> Only a regular update remains from the PR now

Yeah, so it may not be the root cause.
Is it possible that the `buildNodePackage` produces a too deep `node_modules`, which eventually break `npm`?
But as far as I know, it's usually quite deep though. `npm` should handle it well. :thinking:

**Comment by matthewess** [comment] 2020-10-30 15:08
Hey! Just noting that vscode+rust debugging on nixos seems to be pretty difficult until #101179  is merged? My current workaround is to add oxalica's fork as a channel and pull the package from there. Just wanted to throw my +1 in for getting that merged, and see if maybe there was another workaround in the meantime?

**Comment by poscat0x04** [comment] 2020-12-08 08:39
It seems that this issue is no longer present on the master branch.

**Closed** 2021-04-20 14:01 UTC
Labels: 0.kind: bug, 6.topic: nodejs
