### ISSUE TITLE
Terminator doesn't work

### ISSUE THREAD

**Issue by karolchmist** [NixOS/nixpkgs#56934] opened 2019-03-06 07:41 UTC
## Issue description

Terminator doesn't work on latest `nixos-unstable`. It used to work until the last update of my NixOS.

### Steps to reproduce

While trying to run `terminator`, I get 
```
You need to install the python bindings for gobject, gtk and pango to run Terminator.
```

My terminator links to 
```
/nix/store/wqlm1fi4d50wzzqan3bq4hqskrckxzhy-terminator-1.91/bin/terminator
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.104, NixOS, 19.09.git.34aa254 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(karol): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/nixpkgs`

**Comment by karolchmist** [comment] 2019-03-06 07:42
Pinging @bjornfor or @globin , could you have a look please ?

**Comment by jtojnar** [comment] 2019-03-06 15:24
Yeah, this is probably the same as https://github.com/NixOS/nixpkgs/issues/56943

**Comment by borisbabic** [comment] 2019-03-06 15:40
Adding `gobject-introspection` to `propagatedBuildInputs` got it working for me.

**Comment by jtojnar** [comment] 2019-03-06 22:53
Closing as a duplicate of #56943

**Closed by jtojnar** 2019-03-06 22:53 UTC
