### ISSUE TITLE
Package request: zen-browser

### ISSUE THREAD

**Issue by 248nonny** [NixOS/nixpkgs#338561] opened 2024-08-31 06:55 UTC
**Project description**

A fork of firefox that focuses on privacy and performance.

**Metadata**

* homepage URL: https://www.zen-browser.app/
* source URL: https://github.com/zen-browser/desktop
* license: Mozilla Public Licence (MPL)
* platforms: Linux, Windows, MacOS

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Gliczy** [comment] 2024-08-31 07:21
Duplicate of https://github.com/NixOS/nixpkgs/issues/327982

**Closed by Gliczy** 2024-08-31 07:21 UTC
Labels: 0.kind: packaging request
