### ISSUE TITLE
pycurl test multi_memory_mgmt_test.py fails on 19.09 upgrade

### ISSUE THREAD

**Issue by FelschR** [NixOS/nixpkgs#71975] opened 2019-10-25 09:28 UTC
**Describe the bug**
Upgrading my NixOS errors with a failing pycurl test today.

**To Reproduce**
1. run `nixos-rebuild switch --upgrade` on NixOS 19.09

**Expected behavior**
The upgrade should finish successfully.

**Additional context**
```
=================================== FAILURES ===================================
____________ MultiMemoryMgmtTest.test_opensocketfunction_collection ____________

self = <tests.multi_memory_mgmt_test.MultiMemoryMgmtTest testMethod=test_opensocketfunction_collection>

    def test_opensocketfunction_collection(self):
>       self.check_callback(pycurl.M_SOCKETFUNCTION)

tests/multi_memory_mgmt_test.py:18:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/multi_memory_mgmt_test.py:42: in check_callback
    self.assertTrue(new_object_count in (object_count, object_count-1))
E   AssertionError: False is not true
=============================== warnings summary ===============================
/nix/store/31x1b2x2qyy918bhvkqfi8z4hid9ifdx-python3.7-bottle-0.12.16/lib/python3.7/site-packages/bottle.py:87
  /nix/store/31x1b2x2qyy918bhvkqfi8z4hid9ifdx-python3.7-bottle-0.12.16/lib/python3.7/site-packages/bottle.py:87: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    from collections import MutableMapping as DictMixin

tests/setopt_lifecycle_test.py:19
  /build/pycurl-7.43.0.3/tests/setopt_lifecycle_test.py:19: PytestCollectionWarning: cannot collect test class 'TestString' because it has a __new__ constructor (from: tests/setopt_lifecycle_test.py)
    class TestString(str):

tests/memory_mgmt_test.py::MemoryMgmtTest::test_form_bufferptr_memory_leak_gh267
  /build/pycurl-7.43.0.3/tests/memory_mgmt_test.py:320: DeprecationWarning: Please use assertTrue instead.
    self.assert_(after_object_count <= before_object_count + 1000, 'Grew from %d to %d objects' % (before_object_count, after_object_count))

tests/memory_mgmt_test.py::MemoryMgmtTest::test_postfields_unicode_memory_leak_gh252
  /build/pycurl-7.43.0.3/tests/memory_mgmt_test.py:300: DeprecationWarning: Please use assertTrue instead.
    self.assert_(after_object_count <= before_object_count + 1000, 'Grew from %d to %d objects' % (before_object_count, after_object_count))

tests/setopt_test.py::SetoptTest::test_set_httpheader_none
  /build/pycurl-7.43.0.3/tests/setopt_test.py:75: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals(util.b('foo'), io.getvalue())

tests/setopt_test.py::SetoptTest::test_set_httpheader_none
  /build/pycurl-7.43.0.3/tests/setopt_test.py:81: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals(util.b(''), io.getvalue())

tests/setopt_test.py::SetoptTest::test_unset_httpheader
  /build/pycurl-7.43.0.3/tests/setopt_test.py:61: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals(util.b('foo'), io.getvalue())

tests/setopt_test.py::SetoptTest::test_unset_httpheader
  /build/pycurl-7.43.0.3/tests/setopt_test.py:67: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals(util.b(''), io.getvalue())

-- Docs: https://docs.pytest.org/en/latest/warnings.html
===Flaky Test Report===

test_getinfo passed 1 out of the required 1 times. Success!
test_getinfo_times passed 1 out of the required 1 times. Success!
test_cyclic_gc passed 1 out of the required 1 times. Success!
test_debugfunction_collection passed 1 out of the required 1 times. Success!
test_form_bufferptr_memory_leak_gh267 passed 1 out of the required 1 times. Success!
test_headerfunction_collection failed (2 runs remaining out of 3).
        <class 'AssertionError'>
        False is not true
        [<TracebackEntry /build/pycurl-7.43.0.3/tests/memory_mgmt_test.py:243>, <TracebackEntry /build/pycurl-7.43.0.3/tests/util.py:192>, <TracebackEntry /build/pycurl-7.43.0.3/tests/memory_mgmt_test.py:285>]
test_headerfunction_collection passed 1 out of the required 1 times. Success!
test_headerfunction_refcounting passed 1 out of the required 1 times. Success!
test_ioctlfunction_collection failed (2 runs remaining out of 3).
        <class 'AssertionError'>
        False is not true
        [<TracebackEntry /build/pycurl-7.43.0.3/tests/memory_mgmt_test.py:259>, <TracebackEntry /build/pycurl-7.43.0.3/tests/util.py:192>, <TracebackEntry /build/pycurl-7.43.0.3/tests/memory_mgmt_test.py:285>]
test_ioctlfunction_collection passed 1 out of the required 1 times. Success!
test_multi_collection passed 1 out of the required 1 times. Success!
test_multi_cycle passed 1 out of the required 1 times. Success!
test_opensocketfunction_collection passed 1 out of the required 1 times. Success!
test_postfields_unicode_memory_leak_gh252 passed 1 out of the required 1 times. Success!
test_progressfunction_collection passed 1 out of the required 1 times. Success!
test_readdata_refcounting passed 1 out of the required 1 times. Success!
test_readfunction_collection passed 1 out of the required 1 times. Success!
test_readfunction_refcounting passed 1 out of the required 1 times. Success!
test_refcounting_bug_in_reset passed 1 out of the required 1 times. Success!
test_reference_counting passed 1 out of the required 1 times. Success!
test_seekfunction_collection passed 1 out of the required 1 times. Success!
test_share_collection passed 1 out of the required 1 times. Success!
test_share_cycle passed 1 out of the required 1 times. Success!
test_writedata_refcounting passed 1 out of the required 1 times. Success!
test_writefunction_collection passed 1 out of the required 1 times. Success!
test_writefunction_refcounting passed 1 out of the required 1 times. Success!
test_writeheader_refcounting passed 1 out of the required 1 times. Success!
test_xferinfofunction_collection passed 1 out of the required 1 times. Success!
test_curl_ref passed 1 out of the required 1 times. Success!
test_opensocketfunction_collection failed (2 runs remaining out of 3).
        <class 'AssertionError'>
        False is not true
        [<TracebackEntry /build/pycurl-7.43.0.3/tests/multi_memory_mgmt_test.py:18>, <TracebackEntry /build/pycurl-7.43.0.3/tests/multi_memory_mgmt_test.py:42>]
test_opensocketfunction_collection failed (1 runs remaining out of 3).
        <class 'AssertionError'>
        False is not true
        [<TracebackEntry /build/pycurl-7.43.0.3/tests/multi_memory_mgmt_test.py:18>, <TracebackEntry /build/pycurl-7.43.0.3/tests/multi_memory_mgmt_test.py:42>]
test_opensocketfunction_collection failed; it passed 0 out of the required 1 times.
        <class 'AssertionError'>
        False is not true
        [<TracebackEntry /build/pycurl-7.43.0.3/tests/multi_memory_mgmt_test.py:18>, <TracebackEntry /build/pycurl-7.43.0.3/tests/multi_memory_mgmt_test.py:42>]
test_seekfunction_collection passed 1 out of the required 1 times. Success!
test_multi_socket_select passed 1 out of the required 1 times. Success!
test_pause_via_call passed 1 out of the required 1 times. Success!
test_pause_via_return passed 1 out of the required 1 times. Success!
test_post_byte_buffer passed 1 out of the required 1 times. Success!
test_post_fields_with_ampersand passed 1 out of the required 1 times. Success!
test_post_file passed 1 out of the required 1 times. Success!
test_post_list_of_list_of_lists passed 1 out of the required 1 times. Success!
test_post_list_of_tuple_of_tuples passed 1 out of the required 1 times. Success!
test_post_multiple_fields passed 1 out of the required 1 times. Success!
test_post_single_field passed 1 out of the required 1 times. Success!
test_post_tuple_of_lists_of_tuples passed 1 out of the required 1 times. Success!
test_post_tuple_of_tuple_of_lists passed 1 out of the required 1 times. Success!
test_post_tuple_of_tuples_of_tuples passed 1 out of the required 1 times. Success!
test_post_unicode_buffer passed 1 out of the required 1 times. Success!
test_post_with_null_byte passed 1 out of the required 1 times. Success!

===End Flaky Test Report===
===== 1 failed, 381 passed, 9 skipped, 9 deselected, 8 warnings in 42.93s ======
checking for struct fsstat.f_fstypename... no
checking for library containing getmntent... none required
part1part2
builder for '/nix/store/wdhdxrs78axph8j66dpd9cbbaf6h147x-python3.7-pycurl-7.43.0.3.drv' failed with exit code 1
cannot build derivation '/nix/store/3y5lmk45aihims9jv40svzfvzz4414gp-system-config-printer-1.5.11.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/m9sqkgy4bcrdgcbzjnks3i7dn2r2a36k-dbus-1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/z8mkwcgjvz0khq9yvsng63ypsr1ns26r-hwdb.bin.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ysf1kx9pnjyjk9xv7l4dfvq7gwjiqa68-system-generators.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/d1wpss9ighwdj1fs2yf7hxsby1qlgkx2-system-shutdown.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/nklh3f6f6a01sla8jaf3m0kdpgvc6f56-system-units.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/bd6bh9nldc31hc9wkqm9cpqwxyl26m1p-udev-rules.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/c4g1kgmmsxgf8xpkn8128w4598jw5z3x-user-units.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/xgnzf22gndqg3pbs2pivj39ynjzm54fm-etc.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/7dg78qsrc9vs5zg58srwcj1yvk36qr29-nixos-system-pilot1-nixos-19.09.907.f6dac808387.drv': 1 dependencies couldn't be built
error: build of '/nix/store/7dg78qsrc9vs5zg58srwcj1yvk36qr29-nixos-system-pilot1-nixos-19.09.907.f6dac808387.drv' failed
```

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.6, NixOS, 19.09.840.8bf142e001b (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.907.f6dac808387, home-manager-19.09, nixos-unstable-20.03pre196836.1c40ee6fc44"`
 - channels(felschr): `"nixpkgs-unstable-20.03pre197736.91d5b3f07d2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python37Packages.pycurl
# a list of nixos modules affected by the problem
module: 
```

**Comment by worldofpeace** [comment] 2019-10-25 12:51
So, I was able to build `python3.pkgs.pycurl` on the `nixos-19.09` branch with success. However it wasn't cached from hydra, which does make me think this particular test is being flaky with timing related issues etc.

**Comment by alexeymuranov** [comment] 2019-10-26 12:54
Got a similar failure but starting with `MemoryMgmtTest.test_readfunction_collection`.

**Comment by worldofpeace** [comment] 2019-10-26 13:02
cc @jonringer @FRidh. Intriguing that it's just the stable branch.

**Comment by pacien** [comment] 2019-10-27 15:36
I'm experiencing a similar issue on one of my machines, with multiple tests failing, blocking the upgrade from 19.03 to 19.09.

```
=================================== FAILURES ===================================
_________________ MemoryMgmtTest.test_ioctlfunction_collection _________________

self = <tests.memory_mgmt_test.MemoryMgmtTest testMethod=test_ioctlfunction_collection>

    def test_ioctlfunction_collection(self):
>       self.check_callback(pycurl.IOCTLFUNCTION)

tests/memory_mgmt_test.py:259:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/util.py:192: in decorated
    return fn(*args, **kwargs)
tests/memory_mgmt_test.py:285: in check_callback
    self.assertTrue(new_object_count in (object_count, object_count-1))
E   AssertionError: False is not true
______________ MemoryMgmtTest.test_opensocketfunction_collection _______________

self = <tests.memory_mgmt_test.MemoryMgmtTest testMethod=test_opensocketfunction_collection>

    def test_opensocketfunction_collection(self):
>       self.check_callback(pycurl.OPENSOCKETFUNCTION)

tests/memory_mgmt_test.py:262:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/util.py:192: in decorated
    return fn(*args, **kwargs)
tests/memory_mgmt_test.py:285: in check_callback
    self.assertTrue(new_object_count in (object_count, object_count-1))
E   AssertionError: False is not true
_______________ MemoryMgmtTest.test_progressfunction_collection ________________

self = <tests.memory_mgmt_test.MemoryMgmtTest testMethod=test_progressfunction_collection>

    def test_progressfunction_collection(self):
>       self.check_callback(pycurl.PROGRESSFUNCTION)

tests/memory_mgmt_test.py:249:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/util.py:192: in decorated
    return fn(*args, **kwargs)
tests/memory_mgmt_test.py:285: in check_callback
    self.assertTrue(new_object_count in (object_count, object_count-1))
E   AssertionError: False is not true
```

**Comment by ikervagyok** [comment] 2019-12-27 09:24
This is still an issue: building latest master with ssh connections active and Firefox open failed MemoryMgmtTest and MultiMemoryMgmtTest, while it succeeded with no other open programs except KDE. (Some other tests were also failing, but i forgot to take a note)

People encountering this erratic behavior and fluent in python/flaky could help upstream: https://github.com/pycurl/pycurl/issues/545

**Comment by jonringer** [comment] 2019-12-30 07:27
this is also annoying as it builds fine locally, but fails on hydra :(

**Comment by Infinisil** [comment] 2020-01-19 19:23
Marking as duplicate of https://github.com/NixOS/nixpkgs/issues/77304

**Closed by Infinisil** 2020-01-19 19:23 UTC
Labels: 0.kind: bug, 1.severity: blocker, 6.topic: python
