### ISSUE TITLE
firefox has broken U2F support

### ISSUE THREAD

**Issue by Ralith** [NixOS/nixpkgs#34747] opened 2018-02-08 18:11 UTC
## Issue description
U2F 2-factor authentication fails when using the Nix firefox build. [A similar issue](https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1741768) has been reported for ubuntu, so it's probably not just us. Chromium authenticates successfully on the same system; udev rules are set correctly.

### Steps to reproduce

1. Navigate to https://demo.yubico.com/u2f?tab=register
2. Enter made-up credentials and press "Next"
3. See `Exception: FIDO Client error: 1 (OTHER ERROR)`

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.72, NixOS, 17.09.2961.3d985c45905 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.2961.3d985c45905"`
 - channels(ralith): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by drdaeman** [comment] 2018-02-09 13:49
I believe this is caused by `/dev/hidraw*` permissions. After `sudo chmod 0777 /dev/hidraw*` (which is **NOT** a proper solution but only a crude and insecure workaround) I got the page working.

There is https://github.com/amluto/u2f-hidraw-policy which tries to detect U2F devices (Yubikey, Ledger, etc) and sets `ID_U2F_TOKEN=1` and `ID_SECURITY_TOKEN=1` on such, so udev can apply `uaccess` rule (haven't found where this is supposed to actually happen, could be a Fedora/RH-specific thingy, not sure)

I think, as a quick solution you can try adding a custom rule for your specific device:

    services.udev.extraRules = ''
        # My U2F token
        KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="...", ATTRS{idProduct}=="...", TAG+="uaccess"
    '';

I don't have Yubikey (and too lazy too search), so please look up its vendor and product IDs with lsusb.

**Comment by Ralith** [comment] 2018-02-10 06:32
Yes, on NixOS proper permissions can be achieved by setting `udev.packages = [ pkgs.libu2f-host ];`. I think there's a more obvious but functionally equivalent setting in 18.03, but regardless, I have the proper rules in place.

**Comment by bjornfor** [comment] 2018-02-10 08:32
> I think there's a more obvious but functionally equivalent setting in 18.03 [...]

Correct: ```hardware.u2f.enable = true;```.

**Comment by aaronlevin** [comment] 2018-04-19 06:47
This is not working for me (`18.03`). I've tried both `hardware.u2f.enable = true;` and adding the `udev` packages as above. I've also confirmed that this _works_ with google chrome.

Does anyone know what's going on?

**Comment by Ralith** [comment] 2018-04-19 07:32
Still affecting me as well.

**Comment by mmlb** [comment] 2018-05-10 01:44
Is this still happening? I just tried on FF 60.b8 and the yubico demo is working without a hitch.

**Comment by Ralith** [comment] 2018-05-10 05:41
Still happening on nixos-18.03, which has firefox 59.0.2.

**Comment by ciil** [comment] 2018-05-31 13:21
Can't reproduce desired behavior with Firefox 60.0.1. It still errors out with the same error as before: `FIDO Client error: 1 (OTHER ERROR)`.

Chromium continues to work. Updated through `nixos-rebuild switch` from current master at 56023ac0ba5d24708a3210db7ba087ebd86e3d6c.

**Comment by penguin359** [comment] 2018-06-01 02:55
Have you enabled security.webauth.u2f in the about:config settings for Firefox? I had to do that before U2F keys worked.

**Comment by xeji** [comment] 2018-06-25 11:00
should be fixed on master by #42547

**Comment by ciil** [comment] 2018-06-27 07:54
This seems to do the trick.

**Comment by grahamc** [comment] 2018-07-11 22:08
Fixed in 18.03 in 411cc559c052feb6e20a01fc6d5fa63cba09ce9a

**Closed by grahamc** 2018-07-11 22:08 UTC

**Comment by rudolph9** [comment] 2020-04-07 21:09
For those who stumbled on this trying to get a yubikey to work with firefox on nixOS adding:
```
hardware.u2f.enable = true;
```
to `/etc/nixos/configuration.nix` then running:
```
# nixos-rebuild switch
```
then logging out and logging in again should get it working.

I'm on 19.09.
