### ISSUE TITLE
Nixpkgs master breaks nixops

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#34253] opened 2018-01-25 13:46 UTC
## Issue description
With nixops being:
/run/current-system/sw/bin/nixops: symbolic link to /nix/store/nm6iyrkjxyrz2br1cv8fiap9rwpj3cqy-nixops-1.5.1/bin/nixops

using the master branch of nixpkgs, the following failure output appears with deployment target `libvirtd`.

```
keepalive.> mounting Nix store...
keepalive.> mounting host's temporary directory...
keepalive.> starting stage 2 (/nix/store/9ksdkg15y6k620xzlch8w5vkjvvlj09m-vm-run-stage2)
keepalive.> Information: You may need to update /etc/fstab.
keepalive.>
Information: You may need to update /etc/fstab.
keepalive.>
mknod: /dev/vda1: File exists
keepalive.> [    1.087000] reboot: Power down
keepalive.> builder for ‘/nix/store/jssfngvvww49icqv9j8kvl4zwbwdxgc4-libvirtd-image.drv’ failed with exit code 1
keepalive.> cannot build derivation ‘/nix/store/qg65rxvyy6cn6hzssikdlq0lgwg5rd2w-libvirtd-ssh-image.drv’: 1 dependencies couldn't be built
keepalive.> error: build of ‘/nix/store/qg65rxvyy6cn6hzssikdlq0lgwg5rd2w-libvirtd-ssh-image.drv’ failed
```
When using a release branch (17.09) this problem does not exist.

**Comment by teto** [comment] 2018-01-25 14:25
A priori it's fixed on nixops dev.

**Comment by coretemp** [comment] 2018-01-25 20:49
@teto What do you mean? There is nixops master, but `nixops dev` doesn't mean anything for me.

**Comment by fpletz** [comment] 2018-01-31 00:32
Only the current master of nixops seems to work as verified by `__red__` on IRC.

I can't update `nixopsUnstable` because the nixops tarball hasn't been built on Hydra for a while: https://hydra.nixos.org/jobset/nixops/master#tabs-evaluations

The reason is an evaluation error: https://hydra.nixos.org/jobset/nixops/master#tabs-evaluations

Somehow I fail to reproduce that error by evaluation `release.nix` from the `nixops` repo.

@domenkozar Do you know what's going on there?

**Comment by fpletz** [comment] 2018-02-22 23:55
nixops now fails because `system.nixosVersion` was renamed to `system.nixos.version`. Who is currently maintaining nixops?

**Comment by domenkozar** [comment] 2018-02-23 10:54
I'll look into this :)

**Comment by domenkozar** [comment] 2018-02-24 21:36
cc @rbvermaa actually can you? :)

**Comment by fpletz** [comment] 2018-03-04 08:09
@rbvermaa fixed this in nixops master but the jobset is still broken. We can't update nixops.

@rbvermaa is there a new nixops release before 18.03 planned?

**Comment by rbvermaa** [comment] 2018-03-04 15:44
@fpletz Yes, I would like to release new nixops version this week.

**Comment by fpletz** [comment] 2018-03-12 20:24
Deploying 18.03 over 17.09 fails for me: https://github.com/NixOS/nixops/issues/907

**Comment by garbas** [comment] 2018-03-17 21:39
@rbvermaa was release already done? can we close this ticket?

**Comment by fpletz** [comment] 2018-03-22 22:08
This is a major release blocker. We need to have a working nixops version in 18.03 beta so people can test before the final.

@rbvermaa @domenkozar Could one of you please change the config of [nixops:master jobset](https://hydra.nixos.org/jobset/nixops/master#tabs-configuration) and bump the nixpkgs branch to `release-18.03`? I've verified that this fixes the problem [on another Hydra](https://hydra.mayflower.de/jobset/nixops/master#tabs-configuration) because I lack the privileges to modify the jobset on hydra.nixos.org.

**Closed** 2018-03-29 14:44 UTC
Labels: 0.kind: regression, 1.severity: blocker

**Comment by fpletz** [comment] 2018-03-29 14:45
Nixops 1.6 was released. Merged the PR to fix compatibility with older nixops versions anyway to be able to deploy a 18.03 machine with 17.09.
