### ISSUE TITLE
`python310Packages.nbconvert` build failure on x86_64-linux as of `bdf1b57c`

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#187043] opened 2022-08-17 00:12 UTC
## Issue description
Build of `python310Packages.nbconvert` failed on x86_64-linux as of bdf1b57cd2cd2a27abadb6714c116f5777d56979. This is currently breaking `python3Packages.augmax`.

```
error: builder for '/nix/store/pf08plc8c821ncdd391nj2qpyc72h1fg-python3.10-nbconvert-6.5.0.drv' failed with exit code 1;
       last 10 log lines:
       > Requirement already satisfied: jupyter-core>=4.7 in /nix/store/ffwqjdi09ig0midgi18lllh81cq1vy4a-python3.10-jupyter_core-4.9.2/lib/python3.10/site-packages (from nbconvert==6.5.0) (4.9.2)
       > Requirement already satisfied: bleach in /nix/store/80p3h00qff3zlihk607g6h94k26k7sjy-python3.10-bleach-5.0.1/lib/python3.10/site-packages (from nbconvert==6.5.0) (5.0.1)
       > Requirement already satisfied: nbformat>=5.1 in /nix/store/had7mhd7w5vndfc20dk8i013skq3caah-python3.10-nbformat-5.4.0/lib/python3.10/site-packages (from nbconvert==6.5.0) (5.4.0)
       > Requirement already satisfied: pygments>=2.4.1 in /nix/store/wgc1ad6r43slrkc3567ga1gr9h2ax6gh-python3.10-pygments-2.12.0/lib/python3.10/site-packages (from nbconvert==6.5.0) (2.12.0)
       > Requirement already satisfied: entrypoints>=0.2.2 in /nix/store/5br535k383clg99abi4pqp9f3m2pri98-python3.10-entrypoints-0.4/lib/python3.10/site-packages (from nbconvert==6.5.0) (0.4)
       > Requirement already satisfied: packaging in /nix/store/khi1d0hlb14ryimzbl3cx9z8180hn6wb-python3.10-packaging-21.3/lib/python3.10/site-packages (from nbconvert==6.5.0) (21.3)
       > Requirement already satisfied: jinja2>=3.0 in /nix/store/si7qmg4zr0l3lz8jvckcim6qxrl5zy6r-python3.10-Jinja2-3.1.2/lib/python3.10/site-packages (from nbconvert==6.5.0) (3.1.2)
       > ERROR: Could not find a version that satisfies the requirement mistune<2,>=0.8.1 (from nbconvert) (from versions: none)
       > ERROR: No matching distribution found for mistune<2,>=0.8.1
       > 
       For full logs, run 'nix log /nix/store/pf08plc8c821ncdd391nj2qpyc72h1fg-python3.10-nbconvert-6.5.0.drv'.
error: 1 dependencies of derivation '/nix/store/iq8g5qinvrfvrqf9q3lnv9f8s4blprl3-python3.10-einops-0.4.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mn6nn5w6504s6j6xj9fbgcyg2ib1vs7p-python3.10-augmax-unstable-2022-02-19.drv' failed to build
```

[full build log](https://github.com/samuela/nixpkgs-upkeep/actions/runs/2871902377)

python3Packages.augmax maintainers cc: @samuela
python310Packages.nbconvert maintainers cc: @FRidh
Other cc: n/a

### Steps to reproduce
1. Checkout nixpkgs at commit bdf1b57cd2cd2a27abadb6714c116f5777d56979
2. Run `nix-build -A python310Packages.nbconvert`

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-1017-azure, Ubuntu, 20.04.4 LTS (Focal Fossa), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - nixpkgs: `/nix/store/4z9klgabh35a7009wh8lh9qj0s9vh89b-source`
```

## Misc.
This issue was automatically generated by [nixpkgs-upkeep](https://github.com/samuela/nixpkgs-upkeep).
- [CI workflow](https://github.com/samuela/nixpkgs-upkeep/actions/runs/2871902377) that created this issue.
- Internal tags: 7864299911714004290 -4854701549462004657

**Comment by onny** [comment] 2022-08-17 17:09
Duplicate of https://github.com/NixOS/nixpkgs/issues/187045

**Closed by onny** 2022-08-17 17:09 UTC
