### ISSUE TITLE
opengl programs fail to launch (like kitty terminal)

### ISSUE THREAD

**Issue by dnkmmr69420** [NixOS/nixpkgs#239977] opened 2023-06-18 21:23 UTC
**Describe the bug**

on non NixOS systems, if you install the kitty terminal, it can't launch it because it uses opengl

**Steps To Reproduce**

1. type `nix profile install nixpkgs#kitty`
2. Type kitty
3. You get this error

```
Failed to set locale with LANG: en_US.UTF-8
[glfw error 65542]: GLX: No GLXFBConfigs returned
[glfw error 65545]: GLX: Failed to find a suitable GLXFBConfig
Failed to create GLFW temp window! This usually happens because of old/broken OpenGL drivers. kitty requires
```

**Expected behavior**

kitty launches normally

Nix version 2.15.1

**Additional context**

No opengl or vulkan programs can start

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by veprbl** [comment] 2023-06-26 18:11
Duplicate of #82959 and many others

**Closed** 2023-06-26 18:11 UTC
Labels: 0.kind: bug, 6.topic: non-nixos

**Comment by jonahbron** [comment] 2024-04-03 21:46
For reference to anyone else with this issue, invoking kitty through nixGL gets it working.
