### ISSUE TITLE
python31xPackages.polars is broken

### ISSUE THREAD

**Issue by bcdarwin** [NixOS/nixpkgs#263799] opened 2023-10-27 14:44 UTC
### Describe the bug

The `python31xPackages.polars` are completely broken [update: on x86 NixOS/non-NixOS Linux, no idea about aarch64 or Darwin] seemingly due to some sort of shared library issue.  Unfortunately the tests aren't enabled so they didn't catch this.

According to `git bisect`, this breakage occured in 799fff889b1e8058ea392f93400fbbb8923edc86 from PR #243324.

@happysalada

### Steps To Reproduce

Already very suspicious:

```
$ nix-shell -I nixpkgs=~/nixpkgs -p 'python310.withPackages(ps: with ps; [ polars ])' --pure --command 'python3 -c "import polars as pl"'
/nix/store/pfk7rv72dx8cgdh8qn19x308pbaj3qv5-python3-3.10.12-env/lib/python3.10/site-packages/polars/utils/build_info.py:5: UserWarning: polars binary missing!
  from polars.utils.polars_version import get_polars_version
```

Total breakage:

```
$ nix-shell -I nixpkgs=~/nixpkgs -p 'python310.withPackages(ps: with ps; [ polars ])' --pure --command 'python3 -c "import polars as pl; pl.read_csv(\"/tmp/existent-or-nonexistent.csv\")"'
/nix/store/pfk7rv72dx8cgdh8qn19x308pbaj3qv5-python3-3.10.12-env/lib/python3.10/site-packages/polars/utils/build_info.py:5: UserWarning: polars binary missing!
  from polars.utils.polars_version import get_polars_version
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/pfk7rv72dx8cgdh8qn19x308pbaj3qv5-python3-3.10.12-env/lib/python3.10/site-packages/polars/io/csv/functions.py", line 354, in read_csv
    df = pl.DataFrame._read_csv(
  File "/nix/store/pfk7rv72dx8cgdh8qn19x308pbaj3qv5-python3-3.10.12-env/lib/python3.10/site-packages/polars/dataframe/frame.py", line 766, in _read_csv
    self._df = PyDataFrame.read_csv(
NameError: name 'PyDataFrame' is not defined. Did you mean: 'DataFrame'?
```

(and the same with Python 3.11)

**Comment by happysalada** [comment] 2023-10-27 22:43
Are you on darwin by any chance ?

Ive just checked the recent cargo.toml and it looks like on darwin the allocator used is mimalloc

I think with passing this as a dependency it should improve the situatuion
Also, the package is in need of an update.

Im a little stretched at the moment, how interested are you in contributing ? (No pressure, im just asking in case you are)
If you are, i would be happy to help you get a PR merged.

**Comment by bcdarwin** [comment] 2023-10-27 23:58
NixOS/Linux only, don't use Darwin at all currently.  (Sorry, I mean to post `nix-info` output.)

**Comment by bcdarwin** [comment] 2023-10-27 23:59
Happy to investigate on the Linux side though.

**Comment by happysalada** [comment] 2023-10-28 04:58
If you have time to update the package first, it might save you some headaches.
Thanks for taking the time to look into this!

**Comment by a-n-n-a-l-e-e** [comment] 2023-12-05 04:58
unable to reproduce. looks like it was fixed with PR https://github.com/NixOS/nixpkgs/pull/264373

**Closed by a-n-n-a-l-e-e** 2023-12-05 04:58 UTC
Labels: 0.kind: bug
