### ISSUE TITLE
Package request: Windscribe VPN

### ISSUE THREAD

**Issue by mystic-githuber** [NixOS/nixpkgs#298871] opened 2024-03-25 08:18 UTC
Windscribe VPN

Opensource VPN that's an alternative to Proton, iVPN and Mullvad

**Metadata**

* homepage URL: https://windscribe.com/
* source URL: https://github.com/Windscribe/Desktop-App
* license: GPL-2.0 license 
* platforms: Ubuntu, Fedora, Arch

---

**Comment by pluiedev** [comment] 2024-06-09 21:30
Duplicate of #158368

**Closed by pluiedev** 2024-06-09 21:30 UTC
Labels: 0.kind: packaging request
