### ISSUE TITLE
su does not retain `XDG_RUNTIME_DIR`

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#34042] opened 2018-01-19 12:03 UTC
## Issue description
I expect to be able to run `systemsettings5` without it displaying that `XDG_RUNTIME_DIR` is not set.

```
Login as a plain user and then do
$ sudo su - 
# systemsettings5 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
```
## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.4, NixOS, 17.09.git.39cd40f (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment] 2018-01-19 12:06
Try running `sudo` with `--preserve-env` option.

**Comment by coretemp** [comment] 2018-01-19 12:21
Same result.

Just `su -` without sudo also has the same result.

**Comment by jtojnar** [comment] 2018-01-19 12:34
`su` removes the environment variables too.

**Comment by coretemp** [comment] 2018-01-19 16:15
Can you write down a sequence of such commands as I have done which you think should work without additional configuration? 

It might also be that you believe that what I did shouldn't work in the first place.

**Comment by jtojnar** [comment] 2018-01-19 16:23
```ShellSession
~ $ sudo --preserve-env su --preserve-environment -
~ # echo $XDG_RUNTIME_DIR
/run/user/1000
```

**Comment by coretemp** [comment] 2018-01-19 16:36
Should the below generate the `wrong ownership` line or not?

```
$ sudo --preserve-env su --preserve-environment -
# echo $XDG_RUNTIME_DIR
# systemsettings5 
QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
```
I think one of the command sequences above (i.e. running systemsettings5) as root in the desktop environment shell of another user should work. Specifically, the command sequence I specified in the first message in this conversation. Thoughts?

**Comment by jtojnar** [comment] 2018-01-19 16:38
It would be useful if you could share why are you trying to run the program in `su`.

`su` does not really initialize session so it is not suitable for any desktop applications. You can use `machinectl shell --uid=anotheruser` if you want to create session for another user (see https://unix.stackexchange.com/a/348008/41260).

**Comment by coretemp** [comment] 2018-01-19 17:11
This is also not the output I was looking for:
```
machinectl shell --uid=1000
systemsettings5 
QXcbConnection: Could not connect to display 
Aborted
```

**Comment by jtojnar** [comment] 2018-01-19 17:45
Do you want to achieve something specific? Why not just log in as the user?

**Comment by coretemp** [comment] 2018-01-19 18:02
A long time ago running something as root would do the same thing as running as a user (before XDG_ existed); I would expect them to not break that behavior or to simply refuse to run, because it is not a supported configuration to run in. 

Now, when you run systemsettings5 as root, you don't see any icons being displayed for example, creating a degraded experience. 

I don't know what systemsettings5 is supposed to do, but I would like it to either say "you are not supposed to run this as root", or run in some way in which it can run as root without any rendering defects. The current situation is that it just does something and it doesn't work.

I wasn't expecting to spend so much time on this, however, since it is only a minor issue. Perhaps a KDE developer could figure out what it is supposed to be doing?

**Comment by jtojnar** [comment] 2018-01-19 18:12
Running (modern) graphical applications as a different user never worked well – there were some issues with `ICE_Authority` and other files changing ownership breaking the user session. PolicyKit actually solves this issue, but you need to create a policy file (see https://unix.stackexchange.com/questions/203136/how-do-i-run-gui-applications-as-root-by-using-pkexec/203149). 

As I understand it, `systemsettings5` is KDE’s variant of Control Center. Why would you want to run that as root?

**Comment by coretemp** [comment] 2018-01-22 14:37
Running as root can sometimes help test whether there is a permissions problem. If running as root is not a supported operation, then I would much rather just see an error message, instead of a degraded experience, but a Plasma developer should probably also have a say in this. If the option is degraded experience or a message like "Running as root is not supported", then I would prefer such a message.

**Comment by jtojnar** [comment] 2018-01-22 14:48
Running graphical applications through sudo is often what causes a permissions problem.

Anyways, it is not a Plasma issue – no modern graphical application supports it; if it works, it is only by accident. Though some applications, for example, Wireshark, do show a warning you propose.

**Comment by rnhmjoj** [comment] 2018-01-22 20:21
`su` and `sudo` have always been resetting the environment. It's most likely that systemsettings5 started using some environment variable in a critical way. The issue is not root itself but that you don't have a proper environment set up for running such programs.
To spawn a shell with a different user while preserving the current environment do `sudo -sE`.

**Comment by jtojnar** [comment] 2018-01-22 20:36
@rnhmjoj if the app did not check for ownership (as QT thankfully does, see [above](https://github.com/NixOS/nixpkgs/issues/34042#issuecomment-359019816)), it would most definitely break the user session by transferring some critical files to root.

**Closed** 2018-05-07 02:35 UTC
Labels: 0.kind: question
