### ISSUE TITLE
Inkscape throws segementation fault

### ISSUE THREAD

**Issue by taha-yassine** [NixOS/nixpkgs#276811] opened 2023-12-25 23:43 UTC
### Describe the bug
Inkscape throws a segmentation fault in certain conditions.

### Steps To Reproduce
1. Create a LaTeX document test.tex with the following content:
    ```tex
    \documentclass{article}
    \pagestyle{empty}
    \begin{document}
    $x=1+2$
    \end{document}
    ```
3. Compile the file using
    ```
    pdflatex test.tex -interaction=nonstopmode -halt-on-error
    ```
5. Run Inkscape to generate the `.svg` file
    ```
    inkscape --export-type=svg pages=1 test.svg test.pdf
    ```
A segmentation fault is thrown but the file is still produced.
<details>
  <summary>Logs</summary>
      ```
      Emergency save activated!
      Emergency save completed. Inkscape will close now.
      If you can reproduce this crash, please file a bug at https://inkscape.org/report
      with a detailed description of the steps leading to the crash, so we can fix it.
      ** Message: 00:27:11.615: Error:
      0# Inkscape::Application::crash_handler(int) in /nix/store/pfgw3im92g02blfxvmr2q8qrvlshq4j2-inkscape-1.3.2/bin/../lib/inkscape/libinkscape_base.so.1.3.2.0
      1# 0x00007FFBE5375A70 in /nix/store/9y8pmvk8gdwwznmkzxa6pwyah52xy3nk-glibc-2.38-27/lib/libc.so.6
      2# 0x00007FFBE5ECA9DA in /nix/store/b58rkvfpkhw66jj6njc5d5xw6hyywfly-gtk+3-3.24.38/lib/libgtk-3.so.0
      3# 0x00007FFBE6215FEF in /nix/store/b58rkvfpkhw66jj6njc5d5xw6hyywfly-gtk+3-3.24.38/lib/libgtk-3.so.0
      4# 0x00007FFBE7AC9863 in /nix/store/2if9iy5cy0bicwafllpa2aiq30v26app-glib-2.78.1/lib/libgio-2.0.so.0
      5# 0x00007FFBE7ACA663 in /nix/store/2if9iy5cy0bicwafllpa2aiq30v26app-glib-2.78.1/lib/libgio-2.0.so.0
      6# 0x00007FFBE7B3276C in /nix/store/2if9iy5cy0bicwafllpa2aiq30v26app-glib-2.78.1/lib/libgio-2.0.so.0
      7# 0x00007FFBE7AC9863 in /nix/store/2if9iy5cy0bicwafllpa2aiq30v26app-glib-2.78.1/lib/libgio-2.0.so.0
      8# 0x00007FFBE7ACA663 in /nix/store/2if9iy5cy0bicwafllpa2aiq30v26app-glib-2.78.1/lib/libgio-2.0.so.0
      9# 0x00007FFBE7B26202 in /nix/store/2if9iy5cy0bicwafllpa2aiq30v26app-glib-2.78.1/lib/libgio-2.0.so.0
      10# 0x00007FFBE7AC9863 in /nix/store/2if9iy5cy0bicwafllpa2aiq30v26app-glib-2.78.1/lib/libgio-2.0.so.0
      11# 0x00007FFBE7AC9899 in /nix/store/2if9iy5cy0bicwafllpa2aiq30v26app-glib-2.78.1/lib/libgio-2.0.so.0
      12# 0x00007FFBE78C0F8B in /nix/store/2if9iy5cy0bicwafllpa2aiq30v26app-glib-2.78.1/lib/libglib-2.0.so.0
      13# 0x00007FFBE78C3FF7 in /nix/store/2if9iy5cy0bicwafllpa2aiq30v26app-glib-2.78.1/lib/libglib-2.0.so.0
      14# g_main_context_iteration in /nix/store/2if9iy5cy0bicwafllpa2aiq30v26app-glib-2.78.1/lib/libglib-2.0.so.0
      15# g_application_run in /nix/store/2if9iy5cy0bicwafllpa2aiq30v26app-glib-2.78.1/lib/libgio-2.0.so.0
      16# main in /nix/store/pfgw3im92g02blfxvmr2q8qrvlshq4j2-inkscape-1.3.2/bin/inkscape
      17# 0x00007FFBE535FFCE in /nix/store/9y8pmvk8gdwwznmkzxa6pwyah52xy3nk-glibc-2.38-27/lib/libc.so.6
      18# __libc_start_main in /nix/store/9y8pmvk8gdwwznmkzxa6pwyah52xy3nk-glibc-2.38-27/lib/libc.so.6
      19# _start in /nix/store/pfgw3im92g02blfxvmr2q8qrvlshq4j2-inkscape-1.3.2/bin/inkscape
      zsh: segmentation fault (core dumped)  inkscape --export-type=svg --pages=1 test.
      ```
</details>
 
### Expected behavior
Produce the file without errors.

### Additional context
This causes issues when trying to use certain extensions as well like Formula (builtin) and TexText (3rd party). Running the Formula extension for example results in the same segmentation fault.

### Notify maintainers

@jtojnar

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.67, NixOS, 23.11 (Tapir), 23.11.20231212.cf28ee2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/dg2g5qwvs36dhfqj9khx4sfv0klwl9f0-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment] 2023-12-25 23:59
This looks like a duplicate of https://github.com/NixOS/nixpkgs/issues/274240, it should be resolved by #275702

**Closed by jtojnar** 2023-12-25 23:59 UTC
Labels: 0.kind: bug
