### ISSUE TITLE
Nixops deployment builds "all-cabal-hashes" repository for callHackage on the remote machine

### ISSUE THREAD

**Issue by 3noch** [NixOS/nixpkgs#20012] opened 2016-10-31 06:37 UTC
@peti In using `callHackage` I found that when trying to deploy my derivation to a tiny GCE machine via nixops, the deployment would start running build steps on the remote server. Even though, during a build, pulling all-cabal-hashes is safe (albeit, slow and somewhat annoying), it is far more troublesome during deploys. The non-determinism means I can't rely entirely on my local cache to supply the closure for my deploy. Since I'm running macOS as my host, it's especially critical to me that my local cache be 100% sufficient to deploy the server. All that said, I'm new to nix and nixops so I might be missing something.

**Comment by peti** [comment] 2016-10-31 12:45
Could you please be more specific? What exactly is the remote server building? Do you have logs of the deployment process that show what's going on exactly?

**Comment by 3noch** [comment] 2016-10-31 12:52
@peti I wish I could be more specific. I'm running macOS locally, so if I want to deploy to a NixOS machine then it will need to build all my Haskell binaries on the machine since I can't build them locally (binary format mismatch). Since my server is very small, I instead deploy locally to VirtualBox so that all the binaries get built locally. Then I deploy to GCE with the idea that the closure should be 100% fulfilled already. But when I used `callHackage` to setup up some dependencies, it became very unpredictable whether or not my local deploy would *actually* have everything the server needed. When I attempted a deployment, nixops started downloading all-cabal-hashes **on the remote server** (not locally). I was never able to get the deploy to go beyond that point (it would freeze). I'm guessing it was trying to actually update some Haskell packages on the remote and the server wasn't powerful enough.

So, I replaced all my uses of `callHackage` with similar uses of `fetchUrl + cabal2nix` where I pulled directly from GitHub using a commit hash. This meant my build never needed to update any dependencies. After this change, I was able to successfully get my VirtualBox deployment to build the entire closure for my app and then deploy it to my tiny GCE server without running any Haskell dependencies on the server.

Does that help?

**Comment by peti** [comment] 2016-10-31 13:18
Without detailed logs of what was going on during the deployment I cannot debug this issue. I have no idea what your machines were doing and why, so I cannot help much I'm afraid.

**Comment by 3noch** [comment] 2016-10-31 13:46
@peti Well my point is that because `callHackage` *always* pulls down a new version of all-cabal-hashes, the dependency closure for *any* derivation that uses `callHackage` is non-deterministic. Although in practice it works out fine for builds (because it all ends up being the same anyway), to `nix` it appears non-deterministic which makes nixops do more work than necessary.

**Comment by peti** [comment] 2016-10-31 14:34
@3noch, without detailed logs of what was going on during the deployment I cannot debug this issue. I have no idea what your machines were doing and why, so I cannot help much I'm afraid.

**Comment by 3noch** [comment] 2016-10-31 14:38
Do we agree that `callHackage` will depend on a new version of all-cabal-hashes non-deterministically? That is fundamentally the problem.

**Comment by peti** [comment] 2016-10-31 14:52
I don't see why the remote machine should ever evaluate any Nix expressions when all store paths it needs are provided from the outside, i.e. the machine running Nixops. The behavior you've described makes no sense to me. Which is why I cannot say anything about it without some investigation. I cannot investigate, however, because I cannot easily duplicate your setup. Therefore, I cannot help you with this issue.

**Comment by 3noch** [comment] 2016-10-31 16:06
@peti: Ah I see your confusion. For Haskell, nix must build executable binaries but my host macOS machine *cannot* be used to build anything Haskell-related if it needs to run on NixOS (because GHC is not able to cross-compile, at least not as it is in nixpkgs today). This is why things end up getting built on the remote server: it's the only server that nixops knows about that can properly build the binaries. I can get around this issue, but deploying to a NixOS VM locally. Then my host (macOS) nix store will end up containing the closure for a NixOS build. I then deploy to the remote and the closure gets copied. But...when using `callHackage`, the closure is not 100% deterministic. So deploying to my NixOS VM first is *not* enough to create the entire NixOS-compatible closure on my macOS host. So when I deploy to the remote server, nixops (sometimes) ends up needing to fulfill the all-cabal-hashes (since it's not deterministic) and it decides, for some reason, that it cannot be done on my macOS host and must instead be done on the NixOS remote. But this is a domino effect that then requires my remote to re-evaluate all the cabal expressions, etc.

My main, primary, point is: all-cabal-hashes really does need to be deterministic to support edge cases like mine.

**Comment by copumpkin** [comment] 2016-10-31 18:57
@3noch I think I can see what you're saying, but I'd urge you to provide some sort of minimized reproduction of the issue so someone else can not only reproduce it but verify that they've fixed it.

**Comment by 3noch** [comment] 2016-10-31 19:47
@copumpkin Non-determinism is very hard to reproduce 😉 . The fact that all-cabal-hashes is non-deterministic is obvious from its source! I'm merely suggesting that we just do what nix normally encourages and actually be deterministic like we should.

@peti and I discussed this on #nixos IRC a couple days ago and people were expressing concern that all-cabal-hashes (and therefore `callHackage`) is not deterministic. We concluded that it was sort of "ok" since it would still end up resulting in the same artifacts even though it would actually do work in the process. This issue is meant to point out that we really need to change all-cabal-hashes to be deterministic after all.

**Comment by 3noch** [comment] 2016-10-31 20:38
Maybe I'm doing a terrible job communicating. I don't think there's a bug anywhere. I really just think we should make all-cabal-hashes deterministic (like nix expressions ought to be) and this is one reason why: deployment from macOS. Please forgive me if I'm distracting the point with all the other tangential detail.

**Comment by copumpkin** [comment] 2016-10-31 21:03
Oh, I see. This looks really scary, I agree: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/default.nix#L9-L15

**Comment by peti** [comment] 2016-11-01 17:40
Fixed by dbdb27bd6337aa960534d18e1ca7edc30eced5a2 and fac1168816a132694a3f21f2e00654f69ab44e5f.

**Closed by peti** 2016-11-01 17:40 UTC
Labels: 0.kind: question, 6.topic: haskell

**Comment by 3noch** [comment] 2016-11-01 17:54
@peti  Wow! Great job! That's a great approach. That way I can override all-cabal-hashes to a newer version at my discretion. Thanks so much!
