### ISSUE TITLE
Package request: mercury-browser

### ISSUE THREAD

**Issue by ilovethensa** [NixOS/nixpkgs#312616] opened 2024-05-18 08:54 UTC
**Project description**

**Metadata**

* homepage URL: https://thorium.rocks/mercury
* source URL: https://github.com/Alex313031/Mercury
* license: MPL-2
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-06-30 23:06
duplicate of #255399

**Closed by eclairevoyant** 2024-06-30 23:06 UTC
Labels: 0.kind: packaging request
