### ISSUE TITLE
python2Packages.protobuf3_2 build is failing

### ISSUE THREAD

**Issue by rnhmjoj** [NixOS/nixpkgs#27016] opened 2017-07-01 14:56 UTC
## Issue description
A test for `python2Packages.protobuf3_2` is failing:

```
testMergeFrom (google.protobuf.internal.message_test.Proto3Test) ... /nix/store/bl48w7h24n6379fa200yv60n4pwynd9c-stdenv/setup: line 918:
  556 Segmentation fault /nix/store/frnm6ahmm6kzlh7sqrn09hdkkfyy9q39-python-2.7.13/bin/python2.7 nix_run_setup.py test
```

Bisecting proved the culprit is 1856119466211694ff15e20a8472ca68c4a3c4a6. `protobuf` depends on `gflags` indirectly via `google_apputils`.

I'm not sure what to do here: disable the tests or downgrade gflags?

@FRidh

**Comment by rnhmjoj** [comment] 2017-07-01 14:59
It looks like the update has breaking changes. It's probably better to keep both versions.

**Comment by FRidh** [comment] 2017-07-01 15:09
I cannot reproduce the issue:
```
$ nix-build -A python2.pkgs.protobuf3_2
/nix/store/96bjzvi232xpgip162sd5n0y7vq6g5q7-python2.7-protobuf-3.2.0
```
Maybe transient?

**Comment by rnhmjoj** [comment] 2017-07-01 15:21
Uhm, this is strange. I wonder what's causing the segfault.

**Comment by rnhmjoj** [comment] 2017-07-03 15:38
It really seems to happen only on my computer. I have to figure why nix is trying to build it instead of pulling the package from the binary cache.

**Comment by FRidh** [comment] 2017-07-03 15:41
maybe you have something like an overlay that modifies a dependency?

**Comment by rnhmjoj** [comment] 2017-07-03 17:02
None that I'm aware of. How can I be sure? I tried building this and it still fails:

```nix
{ pkgs ? import <nixpkgs> {} }:

let
  src = pkgs.fetchFromGitHub {
    owner  = "nixos";
    repo   = "nixpkgs";
    rev    = "57f394572d2236c77f99aa48d98e62a4362d510c";
    sha256 = "0sxbcay5a8ccs3ldwcmhzb8nvlfmy1nmga0rk2i1nmz63k58fqm1";
  };
  nixpkgs = import src { };
in
  nixpkgs.python2Packages.protobuf3_2
```

**Comment by rnhmjoj** [comment] 2017-07-06 21:00
I have built a VM identical to my system and inside it I could install protobuf3_2. Whatever it's causing this it's not in the global nixos configuration.

**Comment by FRidh** [comment] 2017-07-07 07:34
```
{ pkgs ? import <nixpkgs> {} }:

let
  src = pkgs.fetchFromGitHub {
    owner  = "nixos";
    repo   = "nixpkgs";
    rev    = "57f394572d2236c77f99aa48d98e62a4362d510c";
    sha256 = "0sxbcay5a8ccs3ldwcmhzb8nvlfmy1nmga0rk2i1nmz63k58fqm1";
  };
  nixpkgs = import src {config={}; };
in
  nixpkgs.python2Packages.protobuf3_2
```
I made one change: explicitly setting an empty config.

**Comment by rnhmjoj** [comment] 2017-07-07 10:58
I can't test this anymore. After inspecting everything I could think of I gave up. I formatted the / partition and reinstalled nixos: It's gone. I would still like to know how to prevent it from happening again.

**Comment by FRidh** [comment] 2017-07-07 13:01
Maybe should have checked the store for corruption. Anyway, closing then.

**Closed by FRidh** 2017-07-07 13:01 UTC
Labels: 6.topic: python

**Comment by rnhmjoj** [comment] 2017-07-07 13:16
Sorry for the trouble.
