### ISSUE TITLE
Package request: Portmaster

### ISSUE THREAD

**Issue by MH0386** [NixOS/nixpkgs#362252] opened 2024-12-06 00:35 UTC
## Project description

Portmaster is a free and open-source application firewall that does the heavy lifting for you. Restore privacy and take back control over all your computer's network activity. 

## Metadata

* homepage URL: https://safing.io
* source URL: https://github.com/safing/portmaster

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment] 2024-12-06 01:32
Duplicate of https://github.com/NixOS/nixpkgs/issues/174194

**Closed** 2024-12-06 01:32 UTC
Labels: 2.status: duplicate, 0.kind: packaging request
