### ISSUE TITLE
Build failure: python3Packages.pyside6

### ISSUE THREAD

**Issue by ConnorBaker** [NixOS/nixpkgs#314020] opened 2024-05-23 15:16 UTC
### Steps To Reproduce

1. Check out Nixpkgs at `master` (the log was captured running against 33696fc539b79870c8a53b334838e87767d6be60)
2. `nix build -L .#python312Packages.pyside6`

It is also reproducible with `.#python311Packages.pyside6`.

### Build log

```
pyside6> /build/pyside-setup-everywhere-src-6.7.0/sources/pyside6/build/PySide6/QtMultimedia/PySide6/QtMultimedia/qaudiosource_wrapper.cpp: In function 'PyObject* Sbk_QAudioSourceFunc_error(PyObject*)':
pyside6> /build/pyside-setup-everywhere-src-6.7.0/sources/pyside6/build/PySide6/QtMultimedia/PySide6/QtMultimedia/qaudiosource_wrapper.cpp:792:162: error: 'SBK_QtAudio_Error_IDX' was not declared in this scope; did you mean 'SBK_QCamera_Error_IDX'?
pyside6>   792 |             pyResult = Shiboken::Conversions::copyToPython(PepType_SETP(reinterpret_cast<SbkEnumType *>(Shiboken::Module::get(SbkPySide6_QtMultimediaTypeStructs[SBK_QtAudio_Error_IDX])))->converter, &cppResult);
pyside6>       |                                                                                                                                                                  ^~~~~~~~~~~~~~~~~~~~~
pyside6>       |                                                                                                                                                                  SBK_QCamera_Error_IDX
pyside6> /build/pyside-setup-everywhere-src-6.7.0/sources/pyside6/build/PySide6/QtMultimedia/PySide6/QtMultimedia/qaudiosource_wrapper.cpp: In function 'PyObject* Sbk_QAudioSourceFunc_state(PyObject*)':
pyside6> /build/pyside-setup-everywhere-src-6.7.0/sources/pyside6/build/PySide6/QtMultimedia/PySide6/QtMultimedia/qaudiosource_wrapper.cpp:1120:162: error: 'SBK_QtAudio_State_IDX' was not declared in this scope; did you mean 'SBK_Qt_WindowState_IDX'?
pyside6>  1120 |             pyResult = Shiboken::Conversions::copyToPython(PepType_SETP(reinterpret_cast<SbkEnumType *>(Shiboken::Module::get(SbkPySide6_QtMultimediaTypeStructs[SBK_QtAudio_State_IDX])))->converter, &cppResult);
pyside6>       |                                                                                                                                                                  ^~~~~~~~~~~~~~~~~~~~~
pyside6>       |                                                                                                                                                                  SBK_Qt_WindowState_IDX
pyside6> [918/1818] Building CXX object PySide6/QtMultimedia/CMakeFiles/QtMultimedia.dir/PySide6/QtMultimedia/qcameradevice_wrapper.cpp.o
pyside6> [919/1818] Building CXX object PySide6/QtMultimedia/CMakeFiles/QtMultimedia.dir/PySide6/QtMultimedia/qaudiosink_wrapper.cpp.o
pyside6> FAILED: PySide6/QtMultimedia/CMakeFiles/QtMultimedia.dir/PySide6/QtMultimedia/qaudiosink_wrapper.cpp.o
pyside6> /nix/store/9bv7dcvmfcjnmg5mnqwqlq2wxfn8d7yi-gcc-wrapper-13.2.0/bin/g++ -DNDEBUG -DPy_LIMITED_API=0x03060000 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_LEAN_HEADERS=1 -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQtMultimedia_EXPORTS -I/build/pyside-setup-everywhere-src-6.7.0/sources/pyside6/PySide6/QtMultimedia/QtMultimedia -I/build/pyside-setup-everywhere-src-6.7.0/sources/pyside6/PySide6/QtMultimedia -I/build/pyside-setup-everywhere-src-6.7.0/sources/pyside6/build/PySide6/QtMultimedia -I/build/pyside-setup-everywhere-src-6.7.0/sources/pyside6/libpyside -I/build/pyside-setup-everywhere-src-6.7.0/sources/pyside6/build/PySide6/QtCore/PySide6/QtCore -I/build/pyside-setup-everywhere-src-6.7.0/sources/pyside6/build/PySide6/QtGui/PySide6/QtGui -I/build/pyside-setup-everywhere-src-6.7.0/sources/pyside6/build/PySide6/QtNetwork/PySide6/QtNetwork -I/build/pyside-setup-everywhere-src-6.7.0/sources/pyside6/PySide6 -isystem /nix/store/ikqvl8jq0d7vlp25d9zlbh44m4hljahc-qtbase-6.7.1/include/QtCore -isystem /nix/store/ikqvl8jq0d7vlp25d9zlbh44m4hljahc-qtbase-6.7.1/include/QtGui -isystem /nix/store/ikqvl8jq0d7vlp25d9zlbh44m4hljahc-qtbase-6.7.1/include/QtNetwork -isystem /nix/store/13k4sx3pjjg5mq27q39slnzq20lh0zmf-qtmultimedia-6.7.1/include/QtMultimedia -isystem /nix/store/ikqvl8jq0d7vlp25d9zlbh44m4hljahc-qtbase-6.7.1/mkspecs/linux-g++ -isystem /nix/store/l8razkiw8wmq61bqhm54lda75cr4lvm0-shiboken6-6.7.0/include/shiboken6 -isystem /nix/store/c7ycrgwv039nqglbif98yggx211sdbcl-python3-3.12.3/include/python3.12 -Wall -Wextra -Wno-strict-aliasing -Wno-cast-function-type -fvisibility=hidden -Os -DNDEBUG -std=gnu++17 -fPIC   -fPIC -ffunction-sections -fdata-sections -fno-exceptions -fPIC -MD -MT PySide6/QtMultimedia/CMakeFiles/QtMultimedia.dir/PySide6/QtMultimedia/qaudiosink_wrapper.cpp.o -MF PySide6/QtMultimedia/CMakeFiles/QtMultimedia.dir/PySide6/QtMultimedia/qaudiosink_wrapper.cpp.o.d -o PySide6/QtMultimedia/CMakeFiles/QtMultimedia.dir/PySide6/QtMultimedia/qaudiosink_wrapper.cpp.o -c /build/pyside-setup-everywhere-src-6.7.0/sources/pyside6/build/PySide6/QtMultimedia/PySide6/QtMultimedia/qaudiosink_wrapper.cpp
pyside6> /build/pyside-setup-everywhere-src-6.7.0/sources/pyside6/build/PySide6/QtMultimedia/PySide6/QtMultimedia/qaudiosink_wrapper.cpp: In function 'PyObject* Sbk_QAudioSinkFunc_error(PyObject*)':
pyside6> /build/pyside-setup-everywhere-src-6.7.0/sources/pyside6/build/PySide6/QtMultimedia/PySide6/QtMultimedia/qaudiosink_wrapper.cpp:792:162: error: 'SBK_QtAudio_Error_IDX' was not declared in this scope; did you mean 'SBK_QCamera_Error_IDX'?
pyside6>   792 |             pyResult = Shiboken::Conversions::copyToPython(PepType_SETP(reinterpret_cast<SbkEnumType *>(Shiboken::Module::get(SbkPySide6_QtMultimediaTypeStructs[SBK_QtAudio_Error_IDX])))->converter, &cppResult);
pyside6>       |                                                                                                                                                                  ^~~~~~~~~~~~~~~~~~~~~
pyside6>       |                                                                                                                                                                  SBK_QCamera_Error_IDX
pyside6> /build/pyside-setup-everywhere-src-6.7.0/sources/pyside6/build/PySide6/QtMultimedia/PySide6/QtMultimedia/qaudiosink_wrapper.cpp: In function 'PyObject* Sbk_QAudioSinkFunc_state(PyObject*)':
pyside6> /build/pyside-setup-everywhere-src-6.7.0/sources/pyside6/build/PySide6/QtMultimedia/PySide6/QtMultimedia/qaudiosink_wrapper.cpp:1120:162: error: 'SBK_QtAudio_State_IDX' was not declared in this scope; did you mean 'SBK_Qt_WindowState_IDX'?
pyside6>  1120 |             pyResult = Shiboken::Conversions::copyToPython(PepType_SETP(reinterpret_cast<SbkEnumType *>(Shiboken::Module::get(SbkPySide6_QtMultimediaTypeStructs[SBK_QtAudio_State_IDX])))->converter, &cppResult);
pyside6>       |                                                                                                                                                                  ^~~~~~~~~~~~~~~~~~~~~
pyside6>       |                                                                                                                                                                  SBK_Qt_WindowState_IDX
```

### Additional context

Full log: https://gist.github.com/ConnorBaker/4ad6572022181e9d8553ea6959b08ced

### Notify maintainers

@gebner @Enzime

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.9, NixOS, 24.05 (Uakari), 24.05.20240515.33d1e75`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.22.1`
 - nixpkgs: `/nix/store/0qd773b63yg8435w8hpm13zqz7iipcbs-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by natsukium** [comment] 2024-05-23 15:25
duplicate of https://github.com/NixOS/nixpkgs/issues/313908

**Closed by natsukium** 2024-05-23 15:25 UTC
Labels: 0.kind: build failure
