### ISSUE TITLE
neovim/wrapper.nix bug, wrapperArgs applied twice to makeWrapper

### ISSUE THREAD

**Issue by Dulanjala007** [NixOS/nixpkgs#231172] opened 2023-05-10 21:46 UTC
https://github.com/NixOS/nixpkgs/blob/80e3487ed40c1e976f2484cb06bb8cce41ef9da2/pkgs/applications/editors/neovim/wrapper.nix#L38

 wrapperArgsStr  <<  lib.escapeShellArgs wrapperArgs

https://github.com/NixOS/nixpkgs/blob/80e3487ed40c1e976f2484cb06bb8cce41ef9da2/pkgs/applications/editors/neovim/wrapper.nix#L42

https://github.com/NixOS/nixpkgs/blob/80e3487ed40c1e976f2484cb06bb8cce41ef9da2/pkgs/applications/editors/neovim/wrapper.nix#L62-L66

finalMakeWrapperArgs << commonWrapperArgs  << wrapperArgs

https://github.com/NixOS/nixpkgs/blob/80e3487ed40c1e976f2484cb06bb8cce41ef9da2/pkgs/applications/editors/neovim/wrapper.nix#L132

makeWrapper  (finalMakeWrapperArgs: has wrapperArgs) (wrapperArgsStr: has wrapperArgs) <--- `wrapperArgs` applied twice..

**Comment by pschyska** [comment] 2023-06-16 13:16
This leads to my vim config failing because I'm getting to many --cmd's.
Is there a workaround @teto  ?

**Comment by pschyska** [comment] 2023-06-16 17:52
> what's your config like, you should be allowed 10 --cmd so that's weird. Are you on stable-23.05 ?

It's an elaborate recursively wrapped custom build... It might have been close to 10 -c's or --cmd's easily and a few duplicated ones pushed me over 🙂 . I had to roll back to restore the config temporarily and can't reproduce it right now. I'll get back to you when I try again.

**Comment by pschyska** [comment] 2023-06-26 11:16
@teto Sorry for the noise, I think I have another issue. I must have broken quoting when trying to unroll my wrappers manually to debug, noticed the duplication and got vim's "too many --cmd's" error.
I'm not close to 10 -c or --cmd, and only the lowest wrapper duplicates the args - the following layers are `makeWrapper` based anyways.

**Comment by teto** [comment] 2023-06-26 12:39
Not sure I understand, do you still have issues with it ? 
I've unassigned myself from the issue since I only use unstable and am working on some heavy changes https://github.com/NixOS/nixpkgs/pull/237425 with the goal of making configuration easier for 23.11 (and lua support hopefully). Happy to review a PR that fixes the issue at hand.

**Comment by teto** [comment] 2023-10-23 00:13
should be fixed now

**Closed by teto** 2023-10-23 00:13 UTC
Labels: 6.topic: vim
