### ISSUE TITLE
Unable to build Haskell libraries that depend on OS X shared libraries

### ISSUE THREAD

**Issue by newhoggy** [NixOS/nixpkgs#15759] opened 2016-05-27 15:06 UTC
## Issue description

Linking fails when building Haskell library `memory` using `cabal`.

### Steps to reproduce

This should be sufficient to reproduce the problem.

```
01:00 $ nix-shell -p haskell.compiler.ghc7103 -p cabal-install -p cabal2nix -p zlib -p libiconv

[nix-shell:~/wrk/haskell-works/hw-all/hw-json]$ cabal install memory
Resolving dependencies...
Notice: installing into a sandbox located at
/Users/jky/wrk/haskell-works/hw-all/hw-json/.cabal-sandbox
Configuring memory-0.13...
Building memory-0.13...
Failed to install memory-0.13
Build log ( /Users/jky/wrk/haskell-works/hw-all/hw-json/.cabal-sandbox/logs/memory-0.13.log ):
Configuring memory-0.13...
Building memory-0.13...
Preprocessing library memory-0.13...
ld: malformed mach-o, symbol table not in __LINKEDIT file '/nix/store/01a8nfwswqra5szdrd76di2x7cv3910c-libiconv-osx-10.9.5/lib/libiconv.dylib' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
linking dist/dist-sandbox-16a84bee/build/Data/Memory/MemMap/Posix_hsc_make.o failed (exit code 1)
command was: /usr/bin/gcc dist/dist-sandbox-16a84bee/build/Data/Memory/MemMap/Posix_hsc_make.o dist/dist-sandbox-16a84bee/build/Data/Memory/MemMap/Posix_hsc_utils.o -o dist/dist-sandbox-16a84bee/build/Data/Memory/MemMap/Posix_hsc_make -m64 -L/nix/store/g2xpd8z4drs9ylahrc28hc29y12a8isq-ghc-7.10.3/lib/ghc-7.10.3/bytes_6VWy06pWzJq9evDvK2d4w6 -L/nix/store/g2xpd8z4drs9ylahrc28hc29y12a8isq-ghc-7.10.3/lib/ghc-7.10.3/deeps_6vMKxt5sPFR0XsbRWvvq59 -L/nix/store/g2xpd8z4drs9ylahrc28hc29y12a8isq-ghc-7.10.3/lib/ghc-7.10.3/array_67iodizgJQIIxYVTp4emlA -L/nix/store/g2xpd8z4drs9ylahrc28hc29y12a8isq-ghc-7.10.3/lib/ghc-7.10.3/base_HQfYBxpPvuw8OunzQu6JGM -L/nix/store/01a8nfwswqra5szdrd76di2x7cv3910c-libiconv-osx-10.9.5/lib -liconv -L/nix/store/g2xpd8z4drs9ylahrc28hc29y12a8isq-ghc-7.10.3/lib/ghc-7.10.3/integ_2aU3IZNMF9a7mQ0OzsZ0dS -L/nix/store/9h0y52vcpf74w141ynlb7i6gil3qscqa-gmp-6.1.0/lib -lgmp -L/nix/store/g2xpd8z4drs9ylahrc28hc29y12a8isq-ghc-7.10.3/lib/ghc-7.10.3/ghcpr_8TmvWUcS1U1IKHT0levwg3 -L/nix/store/g2xpd8z4drs9ylahrc28hc29y12a8isq-ghc-7.10.3/lib/ghc-7.10.3/rts -lm -ldl
cabal: Error: some packages failed to install:
memory-0.13 failed during the building phase. The exception was:
ExitFailure 1
```

## Technical details

```
$ uname -a
Darwin Delevant 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

$ xcodebuild -version
Xcode 7.3.1
Build version 7D1014

$ nix-env --version
nix-env (Nix) 1.11.2

$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.09pre83147.df89584"
```

**Comment by newhoggy** [comment] 2016-05-27 15:07
This used to work.  I'm wondering if it has anything to do with upgrade of XCode recently.

**Comment by matthewbauer** [comment] 2016-05-27 15:32
This is either related or a duplicate of #15335.

**Comment by peti** [comment] 2016-09-10 20:36
I believe that passing `--with-gcc=clang` on the command line fixes this issue.

**Closed by peti** 2016-09-10 20:36 UTC
Labels: 6.topic: darwin, 6.topic: haskell
