### ISSUE TITLE
Package request: Safing Portmaster

### ISSUE THREAD

**Issue by saikatdas0790** [NixOS/nixpkgs#227913] opened 2023-04-24 03:48 UTC
**Project description**

Portmaster is a free and open-source application firewall that does the heavy lifting for you. Restore privacy and take back control over all your computer's network activity.

**Metadata**

* homepage URL: https://safing.io/
* source URL: https://github.com/safing/portmaster
* license: [AGPL-3.0 license](https://github.com/safing/portmaster/blob/develop/LICENSE)
* platforms: unix, linux

**Comment by Lord-Valen** [comment] 2023-06-22 04:30
#213735

**Comment by figsoda** [comment] 2023-07-09 14:41
duplicate of #174194

**Closed by figsoda** 2023-07-09 14:41 UTC
Labels: 0.kind: packaging request
