### ISSUE TITLE
Package request: Parabolic

### ISSUE THREAD

**Issue by rastarr** [NixOS/nixpkgs#257552] opened 2023-09-27 03:34 UTC
**Project description**

- A basic yt-dlp frontend ([supported sites](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md))
- Supports downloading videos in multiple formats (mp4, webm, mp3, opus, flac, and wav)
- Run multiple downloads at a time
- Supports downloading metadata and video subtitles

**Metadata**

* homepage URL: https://github.com/NickvisionApps/Parabolic
* source URL: https://github.com/NickvisionApps/Parabolic
* license: mit, bsd, gpl2+ , ... MIT license
* platforms: unix, linux, darwin, ... Linux, flathub, snapstore

**Comment by eclairevoyant** [comment] 2023-09-27 03:59
duplicate of 256853

**Closed by eclairevoyant** 2023-09-27 03:59 UTC
Labels: 0.kind: packaging request
