### ISSUE TITLE
Package request: HybridBar

### ISSUE THREAD

**Issue by byrongibson** [NixOS/nixpkgs#244433] opened 2023-07-20 00:28 UTC
**Project description**

A simple status bar focused on wlroots Wayland compositors, usable with KDE and tiling window managers like Hyprland.

**Metadata**

* homepage URL:  https://github.com/vars1ty/HybridBar
* source URL:  https://github.com/vars1ty/HybridBar
* license: mit
* platforms: linux

**Comment by Aleksanaa** [comment] 2023-08-03 08:01
duplicate of https://github.com/NixOS/nixpkgs/issues/195684

**Closed by Aleksanaa** 2023-08-03 08:01 UTC
Labels: 0.kind: packaging request
