### ISSUE TITLE
`command-not-found` database entry for `dig` is incorrect

### ISSUE THREAD

**Issue by joee** [NixOS/nixpkgs#191221] opened 2022-09-14 18:28 UTC
### Describe the bug
The `command-not-found` database entry for `dig` is incorrect.

### Steps To Reproduce
```
$ nix-shell -p bind
$ dig example.com
The program 'dig' is not in your PATH. You can make it available in an
ephemeral shell by typing:
  nix-shell -p bind

$ nix-shell -p dnsutils
$ type dig
dig is /nix/store/670wb9zzc339pfkrba5rvi262iari987-bind-9.18.3-dnsutils/bin/dig
```

### Expected behavior
I expected the system to tell me to use `dnsutils`.

### Notify maintainers
@lovesegfault

### Metadata
 - system: `"aarch64-linux"`
 - host os: `Linux 5.15.67, NixOS, 22.05 (Quokka), 22.05.3050.d86a4619b7e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by zowoq** [comment] 2022-09-14 23:43
Duplicate of https://github.com/NixOS/nixpkgs/issues/129713

**Closed by zowoq** 2022-09-14 23:43 UTC
Labels: 0.kind: bug
