### ISSUE TITLE
systemd-boot: nixos-rebuild switch fails with non-zero exit status

### ISSUE THREAD

**Issue by volisoft** [NixOS/nixpkgs#169693] opened 2022-04-22 05:16 UTC
### Describe the bug
After updating to the latest nixos-unstable `nixos-rebuild switch` fails with error. 
```console
building the system configuration...
warning: Git tree '/home/dev/x/my/prj/nix' is dirty
updating systemd-boot from (249.7) to (250.4)
Source file "/nix/store/h5k31zlk8j216523prxwwqxn8bdlakpl-systemd-250.4/lib/systemd/boot/efi/systemd-bootaa64.efi" does not carry version information!
Source file "/nix/store/h5k31zlk8j216523prxwwqxn8bdlakpl-systemd-250.4/lib/systemd/boot/efi/systemd-bootaa64.efi" does not carry version information!
Traceback (most recent call last):
  File "/nix/store/53c7jabsxd2wizryywviz4n8jk9cyb9y-systemd-boot", line 316, in <module>
    main()
  File "/nix/store/53c7jabsxd2wizryywviz4n8jk9cyb9y-systemd-boot", line 267, in main
    subprocess.check_call(["/nix/store/h5k31zlk8j216523prxwwqxn8bdlakpl-systemd-250.4/bin/bootctl", "--path=/boot", "update"])
  File "/nix/store/9zncdsgdwz3h7hnmfqnc0ya0c27hwfi7-python3-3.9.12/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/h5k31zlk8j216523prxwwqxn8bdlakpl-systemd-250.4/bin/bootctl', '--path=/boot', 'update']' returned non-zero exit status 1.
warning: error(s) occurred while switching to the new configuration

```
### Steps To Reproduce
1. run `sudo nixos-rebuild switch --flake '.#dev-system`

### Expected behavior
The system should be updated without an error.

### Screenshots
N/A
### Additional context
The system is built using nix flakes
### Notify maintainers

@flokli @Kloenk @Mic92  @trofi 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/vxi9xxfb59slzql57hbvrkvrac8khmkj-bash-interactive-5.1-p12-dev
copying path '/nix/store/vxi9xxfb59slzql57hbvrkvrac8khmkj-bash-interactive-5.1-p12-dev' from 'https://cache.nixos.org'...
 - system: `"aarch64-linux"`
 - host os: `Linux 5.15.13, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(root): `"nixos-22.05pre338578.a2e281f5770"`
 - channels(dev): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

```console
[user@system:~]$  sudo nixos-rebuild boot
building Nix...
building the system configuration...
updating systemd-boot from (249.7) to (249.5)
Skipping "/boot/EFI/systemd/systemd-bootaa64.efi", since a newer boot loader version exists already.
Skipping "/boot/EFI/BOOT/BOOTAA64.EFI", since a newer boot loader version exists already.
Traceback (most recent call last):
  File "/nix/store/s03ypdz6dwlgx97p74hqlx428rvwi6kn-systemd-boot", line 314, in <module>
    main()
  File "/nix/store/s03ypdz6dwlgx97p74hqlx428rvwi6kn-systemd-boot", line 267, in main
    subprocess.check_call(["/nix/store/f4sblwaj2d09kgr3k1imw3mq8cxq3gk9-systemd-249.5/bin/bootctl", "--path=/boot", "update"])
  File "/nix/store/aa9jdd3ijz3icvpahyl87z2dk0hlbw10-python3-3.9.6/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/f4sblwaj2d09kgr3k1imw3mq8cxq3gk9-systemd-249.5/bin/bootctl', '--path=/boot', 'update']' returned non-zero exit status 1.
warning: error(s) occurred while switching to the new configuration
dev@devbox:~/x/my/prj/nix$ bootctl --path /boot status; echo $?
Failed to read "/boot/EFI/systemd": Permission denied
Failed to open "/boot/loader/loader.conf": Permission denied
System:
     Firmware: UEFI 2.70 (EDK II 1.00)
  Secure Boot: disabled
   Setup Mode: user
 TPM2 Support: no
 Boot into FW: supported

Current Boot Loader:
      Product: systemd-boot 249.7
     Features: ✓ Boot counting
               ✓ Menu timeout control
               ✓ One-shot menu timeout control
               ✓ Default entry control
               ✓ One-shot entry control
               ✓ Support for XBOOTLDR partition
               ✓ Support for passing random seed to OS
               ✓ Boot loader sets ESP information
          ESP: /dev/disk/by-partuuid/bdd476a4-8770-4e2f-8ec3-913e47fdf753
         File: └─/EFI/systemd/systemd-bootaa64.efi

Random Seed:
 Passed to OS: no
 System Token: not set
       Exists: no

Available Boot Loaders on ESP:
          ESP: /boot (/dev/disk/by-partuuid/bdd476a4-8770-4e2f-8ec3-913e47fdf753)

Boot Loaders Listed in EFI Variables:
        Title: Linux Boot Manager
           ID: 0x0004
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/bdd476a4-8770-4e2f-8ec3-913e47fdf753
         File: └─/EFI/systemd/systemd-bootaa64.efi

Boot Loader Entries:
        $BOOT: /boot (/dev/disk/by-partuuid/bdd476a4-8770-4e2f-8ec3-913e47fdf753)

1
[user@system:~]$  bootctl status --no-variables
Failed to read "/boot/EFI/systemd": Permission denied
Failed to open "/boot/loader/loader.conf": Permission denied
System:
     Firmware: UEFI 2.70 (EDK II 1.00)
  Secure Boot: disabled
   Setup Mode: user
 TPM2 Support: no
 Boot into FW: supported

Current Boot Loader:
      Product: systemd-boot 249.7
     Features: ✓ Boot counting
               ✓ Menu timeout control
               ✓ One-shot menu timeout control
               ✓ Default entry control
               ✓ One-shot entry control
               ✓ Support for XBOOTLDR partition
               ✓ Support for passing random seed to OS
               ✓ Boot loader sets ESP information
          ESP: /dev/disk/by-partuuid/bdd476a4-8770-4e2f-8ec3-913e47fdf753
         File: └─/EFI/systemd/systemd-bootaa64.efi

Random Seed:
 Passed to OS: no
 System Token: not set
       Exists: no

Available Boot Loaders on ESP:
          ESP: /boot (/dev/disk/by-partuuid/bdd476a4-8770-4e2f-8ec3-913e47fdf753)

Boot Loaders Listed in EFI Variables:
        Title: Linux Boot Manager
           ID: 0x0004
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/bdd476a4-8770-4e2f-8ec3-913e47fdf753
         File: └─/EFI/systemd/systemd-bootaa64.efi

Boot Loader Entries:
        $BOOT: /boot (/dev/disk/by-partuuid/bdd476a4-8770-4e2f-8ec3-913e47fdf753)
```

**Comment by trofi** [comment] 2022-04-22 07:04
For me `bootctl status` Just Works:

```
$ bootctl --path=/boot status |& head -n3
System:
     Firmware: UEFI 2.70 (American Megatrends 5.17)
  Secure Boot: disabled (setup)
...
```

> $ bootctl --path /boot status
> Failed to read "/boot/EFI/systemd": Permission denied
> Failed to open "/boot/loader/loader.conf": Permission denied

That looks problematic. Do you know why it's not accessible for you?

**Comment by volisoft** [comment] 2022-04-22 15:33
May be a permission setup. It does work with sudo. However, I run `switch` command with sudo as well, but it still fails.
Here's there `bootctl` commands output with sudo:
 ```console
[user@system:~]$ sudo bootctl status --no-variables
System:
     Firmware: UEFI 2.70 (EDK II 1.00)
  Secure Boot: disabled
   Setup Mode: user
 TPM2 Support: no
 Boot into FW: supported

Current Boot Loader:
      Product: systemd-boot 249.7
     Features: ✓ Boot counting
               ✓ Menu timeout control
               ✓ One-shot menu timeout control
               ✓ Default entry control
               ✓ One-shot entry control
               ✓ Support for XBOOTLDR partition
               ✓ Support for passing random seed to OS
               ✓ Boot loader sets ESP information
          ESP: /dev/disk/by-partuuid/bdd476a4-8770-4e2f-8ec3-913e47fdf753
         File: └─/EFI/systemd/systemd-bootaa64.efi

Random Seed:
 Passed to OS: no
 System Token: not set
       Exists: yes

Available Boot Loaders on ESP:
          ESP: /boot (/dev/disk/by-partuuid/bdd476a4-8770-4e2f-8ec3-913e47fdf753)
         File: └─/EFI/systemd/systemd-bootaa64.efi (systemd-boot 249.7)
         File: └─/EFI/BOOT/BOOTAA64.EFI (systemd-boot 249.7)

Boot Loaders Listed in EFI Variables:
        Title: Linux Boot Manager
           ID: 0x0004
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/bdd476a4-8770-4e2f-8ec3-913e47fdf753
         File: └─/EFI/systemd/systemd-bootaa64.efi

Boot Loader Entries:
        $BOOT: /boot (/dev/disk/by-partuuid/bdd476a4-8770-4e2f-8ec3-913e47fdf753)

Default Boot Loader Entry:
        title: NixOS (Generation 54 NixOS 22.05.20220109.8928525, Linux Kernel 5.15.13, Built on 2022-04-22)
           id: nixos-generation-54.conf
       source: /boot/loader/entries/nixos-generation-54.conf
      version: Generation 54 NixOS 22.05.20220109.8928525, Linux Kernel 5.15.13, Built on 2022-04-22
   machine-id: a1d2389f6ae3486fa5dac1d639e62d29
        linux: /efi/nixos/zrqzpn9q5m45ah0i6psd2g79hsh0q431-linux-5.15.13-Image.efi
       initrd: /efi/nixos/zr53q3rzfc92gv2afz58rwfjvrdj993v-initrd-linux-5.15.13-initrd.efi
      options: init=/nix/store/8ama4mxlvbjrirkxiz1q0qm8karj4iz5-nixos-system-devbox-22.05.20220109.8928525/init console=tty0 loglevel=4


[user@system:~]$ sudo bootctl --path /boot status; echo $?
System:
     Firmware: UEFI 2.70 (EDK II 1.00)
  Secure Boot: disabled
   Setup Mode: user
 TPM2 Support: no
 Boot into FW: supported

Current Boot Loader:
      Product: systemd-boot 249.7
     Features: ✓ Boot counting
               ✓ Menu timeout control
               ✓ One-shot menu timeout control
               ✓ Default entry control
               ✓ One-shot entry control
               ✓ Support for XBOOTLDR partition
               ✓ Support for passing random seed to OS
               ✓ Boot loader sets ESP information
          ESP: /dev/disk/by-partuuid/bdd476a4-8770-4e2f-8ec3-913e47fdf753
         File: └─/EFI/systemd/systemd-bootaa64.efi

Random Seed:
 Passed to OS: no
 System Token: not set
       Exists: yes

Available Boot Loaders on ESP:
          ESP: /boot (/dev/disk/by-partuuid/bdd476a4-8770-4e2f-8ec3-913e47fdf753)
         File: └─/EFI/systemd/systemd-bootaa64.efi (systemd-boot 249.7)
         File: └─/EFI/BOOT/BOOTAA64.EFI (systemd-boot 249.7)

Boot Loaders Listed in EFI Variables:
        Title: Linux Boot Manager
           ID: 0x0004
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/bdd476a4-8770-4e2f-8ec3-913e47fdf753
         File: └─/EFI/systemd/systemd-bootaa64.efi

Boot Loader Entries:
        $BOOT: /boot (/dev/disk/by-partuuid/bdd476a4-8770-4e2f-8ec3-913e47fdf753)

Default Boot Loader Entry:
        title: NixOS (Generation 54 NixOS 22.05.20220109.8928525, Linux Kernel 5.15.13, Built on 2022-04-22)
           id: nixos-generation-54.conf
       source: /boot/loader/entries/nixos-generation-54.conf
      version: Generation 54 NixOS 22.05.20220109.8928525, Linux Kernel 5.15.13, Built on 2022-04-22
   machine-id: a1d2389f6ae3486fa5dac1d639e62d29
        linux: /efi/nixos/zrqzpn9q5m45ah0i6psd2g79hsh0q431-linux-5.15.13-Image.efi
       initrd: /efi/nixos/zr53q3rzfc92gv2afz58rwfjvrdj993v-initrd-linux-5.15.13-initrd.efi
      options: init=/nix/store/8ama4mxlvbjrirkxiz1q0qm8karj4iz5-nixos-system-devbox-22.05.20220109.8928525/init console=tty0 loglevel=4
0

```

**Comment by trofi** [comment] 2022-04-22 17:18
Can you clarify what is your permission setup for `/boot`? Chances are others could reproduce the failure in a VM and at least improve error message.

**Comment by volisoft** [comment] 2022-04-22 20:13
Boot has only permissions for root. Though, this doesn't explain why switch to new configuration fails, since I'm running the command as sudo. There's something with the upgrade of systemd to 250.4. 
```console
$ sudo ls -la /boot
total 32
drwx------  5 root root 16384 Jan  1  1970 .
drwxr-xr-x 20 root root  4096 Feb 15 23:13 ..
drwx------  2 root root  4096 Dec 16 22:40 cc111dcf9f9f45ef855a4a7cda35ac7a
drwx------  6 root root  4096 Dec 16 22:40 EFI
drwx------  3 root root  4096 Apr 22 02:24 loader
```

**Comment by wernerb** [comment] 2022-04-23 11:18
With a brand new installation I can confirm this. after doing a `nixos-rebuild boot` I get the following error as well:

```
[root@rpi2:/home/werner]# bootctl --path=/boot updateoot update  
Source file "/nix/store/h5k31zlk8j216523prxwwqxn8bdlakpl-systemd-250.4/lib/systemd/boot/efi/systemd-bootaa64.efi" does not carry version information!
Source file "/nix/store/h5k31zlk8j216523prxwwqxn8bdlakpl-systemd-250.4/lib/systemd/boot/efi/systemd-bootaa64.efi" does not carry version information!
```

**Comment by trofi** [comment] 2022-04-23 11:19
Reproduced locally:
- added `options = [ "umask=0077" "dmask="0077" "fmask="0077" ]` for `/boot vfat`
- rebooted into new configuration
- rolled back systemd to 250.3 in `$PWD` to force bootloader update
- ran `sudo nixos-rebuild switch -I nixpkgs=$PWD`

Got `bootctl` update` failure. Exploring how permissions change.

**Comment by trofi** [comment] 2022-04-23 11:51
Boot permissions ended up being a distraction.

The real cause of failure is an attempt to downgrade the boot loader: `Skipping "/boot/EFI/BOOT/BOOTAA64.EFI", since a newer boot loader version exists already.`. Happens on vanilla system when I try to downgrade systemd from `250.4` to `250.3`.

# How it fails
`switch-to-configuration` calls `systemd-boot-builder.py` considers `bootctl` error a fatal error: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/loader/systemd-boot/systemd-boot-builder.py#L246-L267

The error message comes from `bootctl` binary itself when there is a version mismatch: https://github.com/systemd/systemd/blob/main/src/boot/bootctl.c#L816

**Comment by wernerb** [comment] 2022-04-23 13:27
@trofi 

Indeed permissions is not the issue. Isn't your warning just because you are downgrading?

For me it feels like the aarch64 version:
```
"/nix/store/h5k31zlk8j216523prxwwqxn8bdlakpl-systemd-250.4/lib/systemd/boot/efi/systemd-bootaa64.efi
```
Has something wrong. It would explain why the actual update command is not working which I referred to already. 

This error is happening:
```
Source file "/nix/store/h5k31zlk8j216523prxwwqxn8bdlakpl-systemd-250.4/lib/systemd/boot/efi/systemd-bootaa64.efi" does not carry version information!
```

I am guessing because this issue is not getting as much attention that it is only a problem for the aarch64 efi file of systemd-250.4

**Comment by wernerb** [comment] 2022-04-23 13:33
Scratch my previous comment. There is nothing wrong with `systemd-bootaa64.efi`. The file I have now in `/boot/EFI/systemd` is the exact same as the efi it wants to install. It must be in `bootctl` perhaps the versioning was added on ?

**Comment by kim0** [comment] 2022-04-23 14:08
I just hit this, trying to run nightly on qemu on apple M1 system. Afaict, this function is parsing the binary looking for a string like `218 ####` where it parses the 218 as a version. No such string `####` exists in efi file indeed.
https://github.com/systemd/systemd/blob/main/src/boot/bootctl.c#L360
No idea why this string doesn't exist though!

**Comment by trofi** [comment] 2022-04-23 14:21
Can you upload your built binary? We can try to inspect it and check what differs from x86_64.

**Comment by kim0** [comment] 2022-04-23 14:41
@trofi HYG https://transfer.sh/nv73OB/systemd-bootaa64.efi

**Comment by trofi** [comment] 2022-04-23 15:10
> @trofi HYG https://transfer.sh/nv73OB/systemd-bootaa64.efi

Thank you! I don't see any remnants of nixos or nixpkgs there at all. `#### LoaderInfo:` is not present as well. When I build `nix-build -A pkgsCross.aarch64-multiplatform.systemd` locally I also don't see a signature in there. Looks like a bug. I'll explore it locally.

**Comment by trofi** [comment] 2022-04-23 17:13
It's an effect of stripping EFI binary in one of nixpkgs hooks. Loking at how selectively disable it.

**Comment by trofi** [comment] 2022-04-23 18:00
Brave souls can try https://github.com/NixOS/nixpkgs/pull/169985. I wonder if it fixes the install for you.

**Comment by kim0** [comment] 2022-04-23 23:36
My test system doesn't have ssh .. so I cannot paste large scripts in it .. I'm also very new to nixos, so probably cannot effectively test this. But looking forward to it landing soon. Thanks!
cc @wernerb

**Comment by tpwrules** [comment] 2022-04-24 02:05
For anyone encountering this issue, you can force the bootloader to be reinstalled and make the switch work until the issue is fixed by passing `--install-bootloader`.

**Comment by wernerb** [comment] 2022-04-24 20:15
Also new to nixos. (These are fresh installs on 3 raspberry pi 4's using UEFI)

I pinned to that commit using:
```
nix-channel --add https://github.com/NixOS/nixpkgs/archive/77a189e066a839b1c8bb7cb8c125d434d15854ac.tar.gz nix
```
Using `nixos-rebuild --upgrade switch` and I saw it recompile systemd and other packages in staging.


I got the following at the end:

```
created 5953 symlinks in user environment
building '/nix/store/3k1y00zp40xqlh6753c2xb4c1g622qm3-dbus-1.drv'...
building '/nix/store/79szadkq3n6fclclnja2ah615157i0dn-unit-polkit.service.drv'...
building '/nix/store/irl328kadqbw84rckx0a2ck14c3yrmh8-unit-systemd-fsck-.service.drv'...
building '/nix/store/3mcg7pd1nqnpm1ccsizgjgdmdp7glgh2-unit-dbus.service.drv'...
building '/nix/store/r5k4zzgcgz4y4ijkgircsmzb3lsh10wy-unit-dbus.service.drv'...
building '/nix/store/f1qba9052jd36llsvch9r5lf8djsh1w4-system-units.drv'...
building '/nix/store/37mbk9xdxzmp91jmsy7xrhirpig7xmaq-user-units.drv'...
building '/nix/store/dkrplm2dkmx18bxfxlhr8qpak54kf3mm-etc.drv'...
building '/nix/store/v0j4vp759jc4jmfbw3kk14dmnjnk7a96-nixos-system-rpi2-22.05pre-git.drv'...
could not find any previously installed systemd-boot, installing.
Skipping "/boot/EFI/systemd/systemd-bootaa64.efi", since it's owned by another boot loader.
Skipping "/boot/EFI/BOOT/BOOTAA64.EFI", since it's owned by another boot loader.
Traceback (most recent call last):
  File "/nix/store/njqg3dr1df08613swf9ygr3zyiqsld3g-systemd-boot", line 316, in <module>
    main()
  File "/nix/store/njqg3dr1df08613swf9ygr3zyiqsld3g-systemd-boot", line 267, in main
    subprocess.check_call(["/nix/store/w0n6sz2b3jb123nhjqr46610ikskpxxn-systemd-250.4/bin/bootctl", "--path=/boot", "update"])
  File "/nix/store/9zncdsgdwz3h7hnmfqnc0ya0c27hwfi7-python3-3.9.12/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/w0n6sz2b3jb123nhjqr46610ikskpxxn-systemd-250.4/bin/bootctl', '--path=/boot', 'update']' returned non-zero exit status 1.
warning: error(s) occurred while switching to the new configuration
```

Running it as sudo locally:
```
[root@rpi2:/home/werner]# /nix/store/w0n6sz2b3jb123nhjqr46610ikskpxxn-systemd-250.4/bin/bootctl update
Skipping "/boot/EFI/systemd/systemd-bootaa64.efi", since it's owned by another boot loader.
Skipping "/boot/EFI/BOOT/BOOTAA64.EFI", since it's owned by another boot loader.
```

When i remove those two files then the update command does succeed.

**Comment by trofi** [comment] 2022-04-24 20:52
Nice! At least something is working \o/ I think that in order to get past `Skipping "/boot/EFI/BOOT/BOOTAA64.EFI", since it's owned by another boot loader.` you could use `nixos-rebuild switch --install-bootloader`.

**Comment by tpwrules** [comment] 2022-04-24 23:18
Yes, if you installed the bad version of the bootloader, even after you've gotten a nixpkgs with the issue fixed, you'll have to either remove those files or add the flag to replace them once to get a set with the right identifiers installed. Further updates will work properly though.

**Comment by volisoft** [comment] 2022-04-25 20:50
> For anyone encountering this issue, you can force the bootloader to be reinstalled and make the switch work until the issue is fixed by passing `--install-bootloader` to `nixos-rebuild`.

This worked, thanks for sharing the tip. Are there any reasons we should keep this ticket open?

**Comment by trofi** [comment] 2022-04-25 21:12
I'd say it can be closed once https://github.com/NixOS/nixpkgs/pull/169985 is merged (`Closes:` tag should do it automatically).

**Comment by jian-lin** [comment] 2022-04-27 11:50
> I'd say it can be closed once #169985 is merged (`Closes:` tag should do it automatically).

IIRC, only PRs meregd into the default branch, which is `master`, have this feature to close the related issue.

**Closed** 2022-05-09 05:20 UTC
Labels: 0.kind: bug, 6.topic: systemd

**Comment by CMCDragonkai** [comment] 2023-02-15 00:39
Weirdly enough the upgrade from 21.05 to 21.11 resulted in a downgrade of the bootloader, so I had to use the same fix as https://github.com/NixOS/nixpkgs/issues/169693#issuecomment-1109028051.

**Comment by l0b0** [comment] 2023-06-01 10:26
Same for me when upgrading to 23.05 on one out of two NixOS machines.
