### ISSUE TITLE
fractal-next breaks on startup

### ISSUE THREAD

**Issue by Ma27** [NixOS/nixpkgs#219216] opened 2023-03-02 18:27 UTC
### Describe the bug
When trying to run `fractal` from `fractal-next` I get the following output:
```
2023-03-02T18:23:32.449048Z  INFO fractal::application: Fractal (org.gnome.Fractal)    
2023-03-02T18:23:32.449071Z  INFO fractal::application: Version: 5-alpha1 ()    
2023-03-02T18:23:32.449075Z  INFO fractal::application: Datadir: /nix/store/2mriqdv49r81klnmrv1dybfbr7c1b6qg-fractal-next-5-alpha1/share/fractal    
thread 'main' panicked at 'Failed to retrieve template child. Please check that it has been bound and has a #[template_child] attribute.', /build/cargo-deps-vendor.tar.gz/gtk4/src/subclass/widget.rs:1305:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Steps To Reproduce
1. `nix-build -A fractal-next`
2. `./result/bin/fractal`

### Expected behavior
To not crash :upside_down_face: 

### Screenshots
n/a

### Additional context
Reproducible on `master` (0b47e5eaf2451ad2991cb7824b68d2287c018e85).

### Notify maintainers

@schuelermine 
from GNOME team (also maintainers of the package): @bobby285271 @hedning @jtojnar @dasj19 @maxeaubrey 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.13, NixOS, 22.11 (Raccoon), 22.11.20230224.01db36b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - nixpkgs: `/nix/store/2qi4qi0ym0jfjha53amf129rx8bxv951-s4yj54mj335syxkh86c5y6qzn6j96c3i-source`
```

**Comment by schuelermine** [comment] 2023-03-03 19:18
I believe this is related to #216770. I will look into it again soon, sorry, I had a buncha things to do recently!

**Comment by uzytkownik** [comment] 2023-03-18 05:53
> I believe this is related to #216770. I will look into it again soon, sorry, I had a buncha things to do recently!

Doesn't seems to be if the #216770 is closed as I can still reproduce it.

**Comment by jtojnar** [comment] 2023-03-18 15:22
> Doesn't seems to be if the #216770 is closed as I can still reproduce it.

Yes, it is the same issue mentioned in https://github.com/NixOS/nixpkgs/issues/216770#issuecomment-1434912211. It was caused by Rust 1.67 update and all apps using gtk-rs (or at least those using templates, which the majority does) are broken. The only fix is updating the gtk-rs dependency in each of the apps.

**Comment by schuelermine** [comment] 2023-03-18 16:44
I tried updating to `master` but got an error about failing to set up a cargo workspace, which I didn’t know how to fix. I will try again soon

**Comment by Ma27** [comment] 2023-03-18 16:55
@schuelermine I have something in my git stash where I fixed this issue among a few other things. Will post it later today here :)

**Comment by Ma27** [comment] 2023-03-19 08:56
OK, here's the diff:

```diff
diff --git a/pkgs/applications/networking/instant-messengers/fractal-next/default.nix b/pkgs/applications/networking/instant-messengers/fractal-next/default.nix
index 360234ba3c6..d5926042459 100644
--- a/pkgs/applications/networking/instant-messengers/fractal-next/default.nix
+++ b/pkgs/applications/networking/instant-messengers/fractal-next/default.nix
@@ -19,25 +19,71 @@
 , pipewire
 , libshumate
 , wrapGAppsHook4
+, libxml2
+, fetchurl
 }:
 
 stdenv.mkDerivation rec {
   pname = "fractal-next";
-  version = "5-alpha1";
+  version = "unstable-2023-03-12";
 
   src = fetchFromGitLab {
     domain = "gitlab.gnome.org";
     owner = "GNOME";
     repo = "fractal";
-    rev = version;
-    hash = "sha256-gHMfBGrq3HiGeqHx2knuc9LomgIW9QA9fCSCcQncvz0=";
+    rev = "6dd37a0593dbfe8f51660c9eff7fb87d7d26e22d";
+    hash = "sha256-iD6Ym1RQ6GkTBqBCkuu4ElQ7SdGGsdjjBz31v9t0oT8=";
   };
 
   cargoDeps = rustPlatform.fetchCargoTarball {
     inherit src;
-    hash = "sha256-fTETUD/OaOati5HvNxto5Cw26wMclt6mxPLm4cyE3+0=";
+    hash = "sha256-53+wRbE0XbraGpmSdIwGjJIakoSNZ3BmRLSIzBTu1/Q=";
   };
 
+  prePatch = ''
+    cat >../cargo-deps-vendor.tar.gz/Cargo.toml <<EOF
+    [workspace]
+    members = [
+      ${lib.concatMapStrings (x: ''
+        "${x}",
+      '') [
+        "matrix-sdk"
+        "matrix-sdk-base"
+        "matrix-sdk-common"
+        "matrix-sdk-crypto"
+        "matrix-sdk-indexeddb"
+        "matrix-sdk-qrcode"
+        "matrix-sdk-sled"
+        "matrix-sdk-store-encryption"
+      ]}
+    ]
+    [workspace.package]
+    rust-version = "1.65"
+    [workspace.dependencies]
+    anyhow = "1.0.68"
+    async-stream = "0.3.3"
+    async-trait = "0.1.60"
+    base64 = "0.21.0"
+    byteorder = "1.4.3"
+    ctor = "0.1.26"
+    dashmap = "5.2.0"
+    eyeball = "0.1.5"
+    eyeball-im = "0.1.1"
+    futures-util = { version = "0.3.26", default-features = false, features = ["alloc"] }
+    http = "0.2.6"
+    ruma = "0.8.2"
+    ruma-common = "0.11.3"
+    once_cell = "1.16.0"
+    serde = "1.0.151"
+    serde_html_form = "0.2.0"
+    serde_json = "1.0.91"
+    thiserror = "1.0.38"
+    tracing = { version = "0.1.36", default-features = false, features = ["std"] }
+    vodozemac = { git = "https://github.com/matrix-org/vodozemac", rev = "fb609ca1e4df5a7a818490ae86ac694119e41e71" }
+    zeroize = "1.3.0"
+    EOF
+  '';
+
   nativeBuildInputs = [
     glib
     gtk4
@@ -51,6 +97,7 @@ stdenv.mkDerivation rec {
     desktop-file-utils
     appstream-glib
     wrapGAppsHook4
+    libxml2
   ];
 
   buildInputs = [
@@ -60,7 +107,17 @@ stdenv.mkDerivation rec {
     gst-plugins-bad
     gtk4
     gtksourceview5
-    libadwaita
+    (libadwaita.overrideAttrs (lib.const rec {
+      name = "libadwaita-${version}";
+      version = "1.3.rc";
+      src = fetchFromGitLab {
+        domain = "gitlab.gnome.org";
+        owner = "GNOME";
+        repo = "libadwaita";
+        rev = version;
+        sha256 = "sha256-Xb1sNT1KpWspRkjuPBcAaRMXtVpXnjhm+V2FkNthEKk=";
+      };
+    }))
     libsecret
     openssl
     pipewire
diff --git a/pkgs/development/libraries/gtk/4.x.nix b/pkgs/development/libraries/gtk/4.x.nix
index 764dc36d7db..4f1beb497e1 100644
--- a/pkgs/development/libraries/gtk/4.x.nix
+++ b/pkgs/development/libraries/gtk/4.x.nix
@@ -63,7 +63,7 @@ in
 
 stdenv.mkDerivation rec {
   pname = "gtk4";
-  version = "4.8.3";
+  version = "4.10.0";
 
   outputs = [ "out" "dev" ] ++ lib.optionals x11Support [ "devdoc" ];
   outputBin = "dev";
@@ -75,7 +75,7 @@ stdenv.mkDerivation rec {
 
   src = fetchurl {
     url = "mirror://gnome/sources/gtk/${lib.versions.majorMinor version}/gtk-${version}.tar.xz";
-    sha256 = "s2L5aNCFtNPZNA1NOMcGN33tnVN05pSitrfmKS48unQ=";
+    sha256 = "sha256-jcHnw7OkZ3Lw+kFqjKP9IdDQs7A/swfS5zJ+vuaWJuQ=";
   };
 
   depsBuildBuild = [
diff --git a/pkgs/development/libraries/gtksourceview/5.x.nix b/pkgs/development/libraries/gtksourceview/5.x.nix
index 100e3e44a88..81ca1fdb7b3 100644
--- a/pkgs/development/libraries/gtksourceview/5.x.nix
+++ b/pkgs/development/libraries/gtksourceview/5.x.nix
@@ -25,7 +25,7 @@
 
 stdenv.mkDerivation (finalAttrs: {
   pname = "gtksourceview";
-  version = "5.6.2";
+  version = "5.7.2";
 
   outputs = [ "out" "dev" "devdoc" ];
 
@@ -33,7 +33,7 @@ stdenv.mkDerivation (finalAttrs: {
     inherit (finalAttrs) pname version;
   in fetchurl {
     url = "mirror://gnome/sources/${pname}/${lib.versions.majorMinor version}/${pname}-${version}.tar.xz";
-    sha256 = "HxRsFW8TWmBJnZeeNXfJm24VoRFEV2er5iGbs0xUXHc=";
+    sha256 = "sha256-v5JfEp3z+Kh9cfXh7194uOqdKMUzNum4OviYhFWO3o4=";
   };
 
   patches = [
@@ -41,13 +41,6 @@ stdenv.mkDerivation (finalAttrs: {
     # but not from its own datadr (it assumes it will be in XDG_DATA_DIRS).
     # Since this is not generally true with Nix, let’s add $out/share unconditionally.
     ./4.x-nix_share_path.patch
-
-    # Add Nix syntax highlighting.
-    # https://gitlab.gnome.org/GNOME/gtksourceview/-/merge_requests/303
-    (fetchpatch2 {
-      url = "https://gitlab.gnome.org/GNOME/gtksourceview/-/commit/2cc7fd079f9fc8b593c727c68a2c783c82299562.patch";
-      sha256 = "bTYWjEDpdbnUxcYNKl2YtSLfYlMfcbQSSYQjhixOGS8=";
-    })
   ];
 
   nativeBuildInputs = [
diff --git a/pkgs/development/libraries/libadwaita/default.nix b/pkgs/development/libraries/libadwaita/default.nix
index 75e70ff1ddd..a06d434bdc0 100644
--- a/pkgs/development/libraries/libadwaita/default.nix
+++ b/pkgs/development/libraries/libadwaita/default.nix
@@ -74,7 +74,7 @@ stdenv.mkDerivation rec {
   #
   # In file included from ../tests/test-style-manager.c:10:
   # ../src/adw-settings-private.h:16:10: fatal error: 'adw-enums-private.h' file not found
-  doCheck = !stdenv.isDarwin;
+  doCheck = false;
 
   checkPhase = ''
     runHook preCheck
```

It starts fine, but I didn't manage to test the full functionality yet.
And I know it's pretty dirty, didn't manage to clean things up last weekend when I hacked this together :D

**Comment by schuelermine** [comment] 2023-05-20 16:20
Fixed

**Comment by schuelermine** [comment] 2023-05-20 16:21
Sorry that it took so long

**Closed by schuelermine** 2023-05-20 16:20 UTC
Labels: 0.kind: bug
