### ISSUE TITLE
Can't build raspberry pi

### ISSUE THREAD

**Issue by rhoriguchi** [NixOS/nixpkgs#156275] opened 2022-01-23 08:07 UTC
### Describe the bug
Can't rebuild system with latest `nixos-unstable` commit fc4148a47fa927319186061aa42633c8aa5777f1.

Seems to be related to:
- #155925
- #155963

### Steps To Reproduce
1. Set options: [NixOS on ARM/Raspberry Pi 4](https://nixos.wiki/wiki/NixOS_on_ARM/Raspberry_Pi_4#Configuration)
    - `boot.loader.generic-extlinux-compatible.enable = true`
    - `boot.loader.raspberryPi.enable = true`
2. Rebuild

### Expected behavior
Should build.

### Additional context
```console
The unique option `system.build.installBootLoader' is defined multiple times. Definition values:
       - In `/nix/store/nax3fp0jxka9apfnglg2hw45i4n9ab70-nixos/nixos/nixos/modules/system/boot/loader/raspberrypi/raspberrypi.nix': "/nix/store/1n4s07415748vn60n3i631sk5njm0061-raspberrypi-builder.sh -c"
       - In `/nix/store/nax3fp0jxka9apfnglg2hw45i4n9ab70-nixos/nixos/nixos/modules/system/boot/loader/generic-extlinux-compatible': "/nix/store/azx04scfvy3y2x30hlipvkgsjvb04zvg-extlinux-conf-builder.sh -g 20 -t 5 
 ```

### Notify maintainers
- @tkerber
- @ncfavier 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-linux"`
 - host os: `Linux 5.10.52, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0pre20211217_6e6e998`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by wegank** [comment] 2022-01-23 09:27
Duplicate of #155925.

**Closed** 2022-01-23 10:57 UTC
Labels: 0.kind: bug
