### ISSUE TITLE
Package request:mergiraf 

### ISSUE THREAD

**Issue by unhitched9271** [NixOS/nixpkgs#354822] opened 2024-11-09 18:16 UTC
**Project description**

Mergiraf can solve [a wide range of Git merge conflicts](https://mergiraf.org/conflicts.html). That's because it's aware of the trees in your files! Thanks to [its understanding of your language](https://mergiraf.org/languages.html), it can often reconcile the needs of both sides.

You can [teach Mergiraf a new language](https://mergiraf.org/adding-a-language.html) in a completely declarative way. It's a nonviolent animal, so it prefers that over imperatives.

**Metadata**

* homepage URL: https://mergiraf.org/
* source URL: https://codeberg.org/mergiraf/mergiraf
* license: GPLv3
* platforms:  linux/darwin

---

**Comment by kacperwyczawski** [comment] 2024-11-10 15:51
It would be nice to have this available under `programs.git` somehow.

**Comment by thomaseizinger** [comment] 2024-11-10 23:48
I got as far as this:

```nix
{ lib, rustPlatform, fetchFromGitea, ... }:

rustPlatform.buildRustPackage rec {
  pname = "mergiraf";
  version = "0.2.0";

  src = fetchFromGitea {
    domain = "codeberg.org";
    owner = "mergiraf";
    repo = "mergiraf";
    rev = "v${version}";
    sha256 = "sha256-egtX2daCbPXi5rX2OxbEZA/VI9R4HMj5LRKbUEBFo+E=";
  };

  cargoLock = {
    lockFile = "${src}/Cargo.lock";
    outputHashes = {
      "tree-sitter-go-0.23.1" = "sha256-elPqkvVYs0vADOuN/umDteWP5hqcXhQAoSkqYDtTxaU=";
      "tree-sitter-xml-0.7.0" = "sha256-RTWvOUAs3Uql9DKsP1jf9FZZHaZORE40GXd+6g6RQZw=";
      "tree-sitter-yaml-0.6.1" = "sha256-gS+SjOnGl/86U9VV/y1ca7naYIe7DAOvOv++jCRLTKo=";
    };
  };

  meta = with lib; {
    description = "A syntax-aware git merge driver for a growing collection of programming languages and file formats.";
    homepage = "https://codeberg.org/mergiraf/mergiraf";
    license = licenses.gpl3;
    maintainers = [ ];
  };
}
```

But now the build is failing because `cargo` wants to update the lockfile :(

```
error: builder for '/nix/store/hf1mg0gswydbas0fp1hkfx06mwl8ki6z-mergiraf-0.2.0.drv' failed with exit code 101;
       last 10 log lines:
       > Executing cargoSetupPostPatchHook
       > Validating consistency between /build/source/Cargo.lock and /build/cargo-vendor-dir/Cargo.lock
       > Finished cargoSetupPostPatchHook
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > Running phase: buildPhase
       > Executing cargoBuildHook
       > ++ env CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/r6k305g2rn0qqkvdxfvzqg7mhh7rw679-gcc-wrapper-13.2.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/r6k305g2rn0qqkvdxfvzqg7mhh7rw679-gcc-wrapper-13.2.0/bin/c++ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/r6k305g2rn0qqkvdxfvzqg7mhh7rw679-gcc-wrapper-13.2.0/bin/cc CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/r6k305g2rn0qqkvdxfvzqg7mhh7rw679-gcc-wrapper-13.2.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/r6k305g2rn0qqkvdxfvzqg7mhh7rw679-gcc-wrapper-13.2.0/bin/c++ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/r6k305g2rn0qqkvdxfvzqg7mhh7rw679-gcc-wrapper-13.2.0/bin/cc CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu HOST_CC=/nix/store/r6k305g2rn0qqkvdxfvzqg7mhh7rw679-gcc-wrapper-13.2.0/bin/cc HOST_CXX=/nix/store/r6k305g2rn0qqkvdxfvzqg7mhh7rw679-gcc-wrapper-13.2.0/bin/c++ cargo build -j 16 --target x86_64-unknown-linux-gnu --frozen --profile release
       > error: the lock file /build/source/Cargo.lock needs to be updated but --frozen was passed to prevent this
       > If you want to try to generate the lock file without accessing the network, remove the --frozen flag and use --offline instead.
```

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/xpw8lfslaib4iipln677vbvj6jc40myb-source
source root is source
Executing cargoSetupPostUnpackHook
Finished cargoSetupPostUnpackHook
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
Executing cargoSetupPostPatchHook
Validating consistency between /build/source/Cargo.lock and /build/cargo-vendor-dir/Cargo.lock
Finished cargoSetupPostPatchHook
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
Executing cargoBuildHook
++ env CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/r6k305g2rn0qqkvdxfvzqg7mhh7rw679-gcc-wrapper-13.2.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/r6k305g2rn0qqkvdxfvzqg7mhh7rw679-gcc-wrapper-13.2.0/bin/c++ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/r6k305g2rn0qqkvdxfvzqg7mhh7rw679-gcc-wrapper-13.2.0/bin/cc CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/r6k305g2rn0qqkvdxfvzqg7mhh7rw679-gcc-wrapper-13.2.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/r6k305g2rn0qqkvdxfvzqg7mhh7rw679-gcc-wrapper-13.2.0/bin/c++ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/r6k305g2rn0qqkvdxfvzqg7mhh7rw679-gcc-wrapper-13.2.0/bin/cc CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu HOST_CC=/nix/store/r6k305g2rn0qqkvdxfvzqg7mhh7rw679-gcc-wrapper-13.2.0/bin/cc HOST_CXX=/nix/store/r6k305g2rn0qqkvdxfvzqg7mhh7rw679-gcc-wrapper-13.2.0/bin/c++ cargo build -j 16 --target x86_64-unknown-linux-gnu --frozen --profile release
error: the lock file /build/source/Cargo.lock needs to be updated but --frozen was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --frozen flag and use --offline instead.
```

**Comment by ChrisPWillAtl** [comment] 2024-11-11 02:24
I haven't had experience packaging a Rust tool yet, so keep in mind these are just debugging help questions, but based on https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md did you try running with `lib.fakeSha256` first to get the correct hashes? Also, did you copy the `Cargo.lock` file into the directory as recommended?

**Comment by thomaseizinger** [comment] 2024-11-11 02:40
> Also, did you copy the `Cargo.lock` file into the directory as recommended?

As far as I understand, that should not be necessary because it is part of the source-tree? See https://codeberg.org/mergiraf/mergiraf/src/branch/main/Cargo.lock.

The hashes are correct I think, I got them through compiling with an empty hash first and replacing it with what Nix output in the error message.

I don't think the hashes are the problem, it is `cargo` that fails because it wants to update the lockfile upon invocation but is not allowed to due to `--frozen`. I am only familiar with Rust, not so much with Nix so I don't know what `buildRustPackage` does to mess with the lockfile so that `cargo` is no longer happy?

**Comment by ChrisPWillAtl** [comment] 2024-11-11 03:38
The part of the docs referring to copying the Cargo.lock file is before the part that mentions repositories missing a `Cargo.lock` - you either need a `cargoHash` or a vendored lock file. Doing a search suggests most Nix packaged crates are vendoring the lock file as per the docs e.g. https://github.com/NixOS/nixpkgs/blob/87e3803821210c537acfce075adf5cd030e963b3/pkgs/by-name/ta/tabby/package.nix#L128

I'm not sure as to the reasoning it has to be this way or if it's the root cause of your error though, simply pointing out that the docs aren't being followed and it isn't consistent with the other Rust packages in this repo.

**Comment by ChrisPWill** [comment] 2024-11-11 23:46
Okay I checked it out on my main machine to have a look (sorry haven't had time to raise an actual PR) but it seems like the author forgot to commit the 0.2.0 lock file - see [the history here](https://codeberg.org/mergiraf/mergiraf/commits/tag/v0.2.0/Cargo.lock). I recommend one of three things:

* Generate a new lock file and follow the instructions on https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md to patch the old one
* Clone 0.2.1 on master and use the lock file currently committed there
* Get the 0.2.0 tag updated in the author's repo to include an up to date lock file

**Comment by wetneb** [comment] 2024-11-12 16:12
Sorry about the mess, I made 0.3.0 which hopefully solves the problem!

**Comment by thomaseizinger** [comment] 2024-11-12 23:18
It looks like the original repo contains a flake now: https://codeberg.org/mergiraf/mergiraf/src/branch/main/flake.nix

Do we even still need to package this here or should users just depend on that directly?

**Comment by genga898** [comment] 2024-11-13 10:57
> It looks like the original repo contains a flake now: https://codeberg.org/mergiraf/mergiraf/src/branch/main/flake.nix
> 
> Do we even still need to package this here or should users just depend on that directly?

I already had a working derivation for version 0.3.0

**Closed** 2024-11-13 21:40 UTC
Labels: 6.topic: rust, 0.kind: packaging request
