### ISSUE TITLE
idea.pycharm-professional: Upstream file not available anymore

### ISSUE THREAD

**Issue by Moredread** [NixOS/nixpkgs#25728] opened 2017-05-12 07:49 UTC
## Issue description

Installing pycharm-professional I get 

```
these derivations will be built:
  /nix/store/mm0xjqw56gra6n3k5pzh8sp8y1iqqk9z-pycharm-professional-2017.1.tar.gz.drv
  /nix/store/wkliby3shhf2m667ldmhv07i35laqcji-pycharm-professional-2017.1.drv
building path(s) ‘/nix/store/z0cfw0xh3db5ik7wnk91xxwsg1dacn63-pycharm-professional-2017.1.tar.gz’

trying https://download.jetbrains.com/python/pycharm-professional-2017.1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154  100   154    0     0    742      0 --:--:-- --:--:-- --:--:--   885
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden
error: cannot download pycharm-professional-2017.1.tar.gz from any mirror
builder for ‘/nix/store/mm0xjqw56gra6n3k5pzh8sp8y1iqqk9z-pycharm-professional-2017.1.tar.gz.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/wkliby3shhf2m667ldmhv07i35laqcji-pycharm-professional-2017.1.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/wkliby3shhf2m667ldmhv07i35laqcji-pycharm-professional-2017.1.drv’ failed
```

### Steps to reproduce

nix-shell -p idea.pycharm-professional

## Technical details

* System: 17.03.1123.4a7a03913d (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "17.03.1123.4a7a03913d"
* Sandboxing enabled: yes

**Comment by Taeradan** [comment] 2017-05-12 08:51
#25673

**Comment by Taeradan** [comment] 2017-05-12 08:52
The problem is addressed by PR #25673, not merged yet.

**Comment by Moredread** [comment] 2017-05-12 16:28
@Taeradan Sorry, didn't see it. Thanks for the hint!

**Comment by FRidh** [comment] 2017-05-30 17:33
#25673 has been merged so I suppose we can close this.

**Closed by FRidh** 2017-05-30 17:33 UTC
