### ISSUE TITLE
Cemu: crash with Vulkan

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#236482] opened 2023-06-07 17:07 UTC
### Describe the bug

When i start BotW with Vulkan graphic API, it crashes after loading screen.

Terminal output:

```
Aborted!
Error: signal 6:
cemu() [0x706581]
/nix/store/vnwdak3n1w2jjil119j65k8mw1z23p84-glibc-2.35-224/lib/libc.so.6(+0x3dbf0) [0x7f53e7e3dbf0]
/nix/store/vnwdak3n1w2jjil119j65k8mw1z23p84-glibc-2.35-224/lib/libc.so.6(+0x8abc7) [0x7f53e7e8abc7]
/nix/store/vnwdak3n1w2jjil119j65k8mw1z23p84-glibc-2.35-224/lib/libc.so.6(raise+0x16) [0x7f53e7e3db46]+0x16) [0x7f53e7e3db46]
/nix/store/vnwdak3n1w2jjil119j65k8mw1z23p84-glibc-2.35-224/lib/libc.so.6(abort+0xd7) [0x7f53e7e284b5]+0xd7) [0x7f53e7e284b5]
/nix/store/pnw5839aphgiqnlmv7lif5124hkhnqij-amdvlk-2022.Q3.5/lib/amdvlk64.so(+0x325a1f) [0x7f5272925a1f]
/nix/store/pnw5839aphgiqnlmv7lif5124hkhnqij-amdvlk-2022.Q3.5/lib/amdvlk64.so(+0x1741d98) [0x7f5273d41d98]
/nix/store/pnw5839aphgiqnlmv7lif5124hkhnqij-amdvlk-2022.Q3.5/lib/amdvlk64.so(+0x1745672) [0x7f5273d45672]
/nix/store/pnw5839aphgiqnlmv7lif5124hkhnqij-amdvlk-2022.Q3.5/lib/amdvlk64.so(+0x173fa67) [0x7f5273d3fa67]
/nix/store/pnw5839aphgiqnlmv7lif5124hkhnqij-amdvlk-2022.Q3.5/lib/amdvlk64.so(+0x174a075) [0x7f5273d4a075]
/nix/store/pnw5839aphgiqnlmv7lif5124hkhnqij-amdvlk-2022.Q3.5/lib/amdvlk64.so(+0x174cc27) [0x7f5273d4cc27]
/nix/store/pnw5839aphgiqnlmv7lif5124hkhnqij-amdvlk-2022.Q3.5/lib/amdvlk64.so(+0x174f132) [0x7f5273d4f132]
/nix/store/pnw5839aphgiqnlmv7lif5124hkhnqij-amdvlk-2022.Q3.5/lib/amdvlk64.so(+0x19ff54c) [0x7f5273fff54c]
/nix/store/pnw5839aphgiqnlmv7lif5124hkhnqij-amdvlk-2022.Q3.5/lib/amdvlk64.so(+0x2cd4ba0) [0x7f52752d4ba0]
/nix/store/pnw5839aphgiqnlmv7lif5124hkhnqij-amdvlk-2022.Q3.5/lib/amdvlk64.so(+0x253f35a) [0x7f5274b3f35a]
/nix/store/pnw5839aphgiqnlmv7lif5124hkhnqij-amdvlk-2022.Q3.5/lib/amdvlk64.so(+0x2cd56f4) [0x7f52752d56f4]
/nix/store/pnw5839aphgiqnlmv7lif5124hkhnqij-amdvlk-2022.Q3.5/lib/amdvlk64.so((anonymous namespace)::TGlslangToSpvTraverser::createBinaryOperation(glslang::TOperator, (anonymous namespace)::(anonymous namespace)::OpDecorations&, unsigned int, unsigned int, unsigned int, glslang::TBasicType, bool)+a61) [0x7f5272f83141]
/nix/store/pnw5839aphgiqnlmv7lif5124hkhnqij-amdvlk-2022.Q3.5/lib/amdvlk64.so((anonymous namespace)::TGlslangToSpvTraverser::createInvocationsOperation(glslang::TOperator, unsigned int, std::vector<unsigned int, std::allocator<unsigned int> >&, glslang::TBasicType)+d2d) [0x7f5272f8457d]
/nix/store/pnw5839aphgiqnlmv7lif5124hkhnqij-amdvlk-2022.Q3.5/lib/amdvlk64.so(RegisterWindow::RegisterWindow(DebuggerWindow2&, wxPoint const&, wxSize const&)+9d7) [0x7f5272de3f67]
/nix/store/pnw5839aphgiqnlmv7lif5124hkhnqij-amdvlk-2022.Q3.5/lib/amdvlk64.so(RegisterWindow::OnFPViewModePress(wxCommandEvent&)+94e) [0x7f5272de755e]
/nix/store/pnw5839aphgiqnlmv7lif5124hkhnqij-amdvlk-2022.Q3.5/lib/amdvlk64.so(SaveTransfer::OnTransfer(wxCommandEvent&)+e51) [0x7f5272ded681]
/nix/store/pnw5839aphgiqnlmv7lif5124hkhnqij-amdvlk-2022.Q3.5/lib/amdvlk64.so(+0x46c9e3) [0x7f5272a6c9e3]
/nix/store/pnw5839aphgiqnlmv7lif5124hkhnqij-amdvlk-2022.Q3.5/lib/amdvlk64.so(+0x3dfefa) [0x7f52729dfefa]
/nix/store/pnw5839aphgiqnlmv7lif5124hkhnqij-amdvlk-2022.Q3.5/lib/amdvlk64.so(+0x42c6bc) [0x7f5272a2c6bc]
/nix/store/pnw5839aphgiqnlmv7lif5124hkhnqij-amdvlk-2022.Q3.5/lib/amdvlk64.so(+0x42f668) [0x7f5272a2f668]
/nix/store/pnw5839aphgiqnlmv7lif5124hkhnqij-amdvlk-2022.Q3.5/lib/amdvlk64.so(+0x412c04) [0x7f5272a12c04]
cemu() [0x6f4b2a]
cemu() [0x6fcfdb]
cemu() [0x6ffc7c]
cemu() [0x8e05b2]
cemu() [0x6d11a8]
cemu() [0x59f32b]
/nix/store/6plx60y4x4q2lfp6n7190kaihyxr7m1w-gcc-11.3.0-lib/lib/libstdc++.so.6(+0xdf3d4) [0x7f53e82df3d4]
/nix/store/vnwdak3n1w2jjil119j65k8mw1z23p84-glibc-2.35-224/lib/libc.so.6(+0x88e86) [0x7f53e7e88e86]
/nix/store/vnwdak3n1w2jjil119j65k8mw1z23p84-glibc-2.35-224/lib/libc.so.6(+0x10fd70) [0x7f53e7f0fd70]
Aborted (core dumped)
```

Is that something we can fix or does upstream has to fix it?

### Steps To Reproduce
1. Start game
2. See title screen
3. Crash

### Expected behavior
working game

### Additional context
It works with OpenGL, but performance is very bad (20fps at 720p).

### Notify maintainers

@zhaofengli @baduhai

### Metadata

cemu-2.0-13

Intel i9 CPU + AMD 6600 XT GPU

 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.10, NixOS, 22.11 (Raccoon), 22.11.4479.d4a9ff82fc1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by baduhai** [comment] 2023-06-08 02:07
Cannot reproduce. Vulkan works just fine for me on my RX 6700XT.

**Comment by davidak** [comment] 2023-06-08 16:09
@baduhai do you use NixOS 23.05? maybe it's fixed there.

**Comment by baduhai** [comment] 2023-06-08 16:15
Considering 22.11 is now deprecated, it's what you should be using anyway. But I'm on unstable.

**Comment by lasers** [comment] 2023-07-22 08:31
>cemu-2.0-13

We'll be on cemu-45 soon enough. Is this still a nixpkg issue?

**Comment by baduhai** [comment] 2023-07-27 14:51
> > cemu-2.0-13
> 
> We'll be on cemu-45 soon enough. Is this still a nixpkg issue?

I don't know if this is a nixpkgs issue or not, but I haven't been able to reproduce it either on unstable or on 23.05. Closing since OP hasn't replied in a while.

**Closed by baduhai** 2023-07-27 14:51 UTC
Labels: 0.kind: bug
