### ISSUE TITLE
texlive broken fira font in lualatex (with fontsetup)

### ISSUE THREAD

**Issue by benneti** [NixOS/nixpkgs#278718] opened 2024-01-04 15:33 UTC
### Describe the bug
When I compile documents on nixos that use fira in lualatex with fontsetup the resulting documents have an unreadable font, see screenshot.

### Steps To Reproduce
1. install nixos
2. create a file `test.tex` with content
``` latex
\documentclass[]{article}
\usepackage[fira]{fontsetup}
\usepackage{lipsum}

\begin{document}
\lipsum
\end{document}
```
3. in the same directory as the file run `nix-shell -p texliveFull --run 'lualatex test.tex'
`

### Expected behavior
Have the correct (working) font.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/11725645/f9d4928a-b177-4611-afc7-630a8fcb564c)

### Additional context
according to the log it uses the otf file shipped with texlive not the system wide fira font files (making it even stranger that it is broken).

### Notify maintainers
@veprbl

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 23.11 (Tapir), 23.11.20240101.2d2ea8e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/rzphaas2lw2d5376k9f619580hcn4niq-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by veprbl** [comment] 2024-01-04 17:04
Can't reproduce.

![image](https://github.com/NixOS/nixpkgs/assets/245573/1fcda072-4b63-4680-a74f-35b9ea50af2a)
```
lualatex test.tex
This is LuaHBTeX, Version 1.15.0 (Web2C 2022/nixos.org) 
 restricted system commands enabled.
(./test.tex
LaTeX2e <2022-11-01> patch level 1
 L3 programming layer <2023-02-22>
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class

(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/base/size10.clo))
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/fontsetup/fontsetup.sty
fontsetup: Easy font setup by Antonis Tsolomitis

(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/fontspec/fontspec.sty
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/l3packages/xparse/xparse.sty
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/l3kernel/expl3.sty
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/l3backend/l3backend-luatex.def)))
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/fontspec/fontspec-luatex.sty
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/base/fontenc.sty)
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/fontspec/fontspec.cfg)))
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/base/ifthen.sty)
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/generic/iftex/iftex.sty)
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/fontsetup/fspfiraot.sty
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/unicode-math/unicode-math.sty
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/unicode-math/unicode-math-luatex.sty
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/l3packages/l3keys2e/l3keys2e.sty)
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/base/fix-cm.sty
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/base/ts1enc.def))
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.

(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/amsmath/amstext.sty
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/amsmath/amsgen.sty))
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/amsmath/amsbsy.sty)
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/amsmath/amsopn.sty))
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/lualatex/lualatex-math/lualatex-math.sty
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/etoolbox/etoolbox.sty))
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/unicode-math/unicode-math-table.tex)))))
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/lipsum/lipsum.sty
(/nix/store/8qk9nl1rsfwawdlq8x517l877f9zmzdk-texlive-combined-full-2022.2022122
7-texmf/tex/latex/lipsum/lipsum.ltd.tex))
No file test.aux.

Package lipsum Warning: Unknown language 'latin'. Hyphenation patterns for
(lipsum)                'english' will be used instead.
(lipsum)                
(lipsum)                With LuaTeX, lipsum requires babel to get proper
(lipsum)                hyphenation (you can use \usepackage[base]{babel}).

[1{/nix/store/6fwx1sd2gdv6gn72rp8icjpr97nx28iw-texlive-combined-full-2022.20221
227/share/texmf-var/fonts/map/pdftex/updmap/pdftex.map}] [2] (./test.aux))
 484 words of node memory still in use:
   6 hlist, 2 vlist, 2 rule, 2 glue, 4 kern, 1 glyph, 6 attribute, 52 glue_spec
, 6 attribute_list, 1 write nodes
   avail lists: 2:38,3:41,4:14,5:1024,6:11,7:7347,9:118,10:9,11:554
</nix/store/yqk0id5a7c7fqjkgj5npvg8cfyl0paws-texlive-fira-4.3/fonts/opentype/pu
blic/fira/FiraSans-Regular.otf>
Output written on test.pdf (2 pages, 10771 bytes).
Transcript written on test.log.
```

cc @xworld21

**Comment by benneti** [comment] 2024-01-04 17:18
thats strange, comparing with my log
```
nix-shell -p texliveFull --run 'lualatex test.tex'                                                                                                                                                                                                                                                             
these 4 paths will be fetched (122.29 MiB download, 265.22 MiB unpacked):
  /nix/store/rwpw4zlapbs7vvs5i1bgpqv8h0v0qyv2-fonts.conf
  /nix/store/5adwn1af7whrgiacc60hvzci0z7m76hx-texlive-2022-env
  /nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist
  /nix/store/x826vqcz42l8qysshnhzmppg6fr80vys-texlive-2022-env-texmfroot
copying path '/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist' from 'https://cache.nixos.org'...
copying path '/nix/store/x826vqcz42l8qysshnhzmppg6fr80vys-texlive-2022-env-texmfroot' from 'https://cache.nixos.org'...
copying path '/nix/store/rwpw4zlapbs7vvs5i1bgpqv8h0v0qyv2-fonts.conf' from 'https://cache.nixos.org'...
copying path '/nix/store/5adwn1af7whrgiacc60hvzci0z7m76hx-texlive-2022-env' from 'https://cache.nixos.org'...
This is LuaHBTeX, Version 1.15.0 (TeX Live 2022/nixos.org) 
 restricted system commands enabled.
(./test.tex
LaTeX2e <2022-11-01> patch level 1
 L3 programming layer <2023-02-22>
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class

(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/base/size10.clo))
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/fontsetup/fontsetup.sty
fontsetup: Easy font setup by Antonis Tsolomitis

(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/fontspec/fontspec.sty
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/l3packages/xparse/xparse.sty
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/l3kernel/expl3.sty
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/l3backend/l3backend-luatex.def)))
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/fontspec/fontspec-luatex.sty
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/base/fontenc.sty)
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/fontspec/fontspec.cfg)))
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/base/ifthen.sty)
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/gen
eric/iftex/iftex.sty)
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/fontsetup/fspfiraot.sty
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/unicode-math/unicode-math.sty
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/unicode-math/unicode-math-luatex.sty
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/l3packages/l3keys2e/l3keys2e.sty)
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/base/fix-cm.sty
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/base/ts1enc.def))
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.

(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/amsmath/amstext.sty
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/amsmath/amsgen.sty))
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/amsmath/amsbsy.sty)
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/amsmath/amsopn.sty))
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lua
latex/lualatex-math/lualatex-math.sty
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/etoolbox/etoolbox.sty))
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/unicode-math/unicode-math-table.tex)))))
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/lipsum/lipsum.sty
(/nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/tex/lat
ex/lipsum/lipsum.ltd.tex)) (./test.aux)

Package lipsum Warning: Unknown language 'latin'. Hyphenation patterns for
(lipsum)                'english' will be used instead.
(lipsum)                
(lipsum)                With LuaTeX, lipsum requires babel to get proper
(lipsum)                hyphenation (you can use \usepackage[base]{babel}).


Overfull \hbox (0.17552pt too wide) in paragraph at lines 7--7
\TU/FiraSans-Regular.otf(0)/m/n/10 mau-ris. Nam arcu libero, non-ummy eget, con
-sectetuer id, vulpu-tate a, magna.

Overfull \hbox (2.42223pt too wide) in paragraph at lines 7--7
\TU/FiraSans-Regular.otf(0)/m/n/10 Donec ve-hic-ula au-gue eu neque. Pel-len-te
sque habi-tant morbi tris-tique senec-
[1{/nix/store/5adwn1af7whrgiacc60hvzci0z7m76hx-texlive-2022-env/share/texmf-var
/fonts/map/pdftex/updmap/pdftex.map}] [2] (./test.aux))
(see the transcript file for additional information)
 484 words of node memory still in use:
   6 hlist, 2 vlist, 2 rule, 2 glue, 4 kern, 1 glyph, 6 attribute, 52 glue_spec
, 6 attribute_list, 1 write nodes
   avail lists: 2:38,3:39,4:10,5:623,6:11,7:7343,9:118,10:8,11:554
</nix/store/1l41gakysqd5hhcq0kyv752y4gx6xa6s-texlive-2022-env-texmfdist/fonts/o
pentype/public/fira/FiraSans-Regular.otf>
Output written on test.pdf (2 pages, 11482 bytes).
Transcript written on test.log.
```
yours seems to load the font from the `texlive-fira` package while mine loads from the combined environment, I have no idea whether this helps to narrow down the problem.

**Comment by benneti** [comment] 2024-01-04 17:24
nevermind, your log helped me figure it out. lualatex generates a fontcache in .texlive2022 which resulted in the broken font.
I am not sure if there is anything we can do about this in nix to avoid this.

**Comment by veprbl** [comment] 2024-01-04 17:30
The log that I've posted wash from texlive.combined.scheme-full. texliveFull produces different paths, but otherwise same result:
```
# rm -rf ~/.texlive2022
# nix-shell -I nixpkgs=channel:nixpkgs-unstable -p texliveFull --pure --run 'lualatex test.tex' 
This is LuaHBTeX, Version 1.15.0 (TeX Live 2022/nixos.org) 
 restricted system commands enabled.
(./test.tex
LaTeX2e <2022-11-01> patch level 1
 L3 programming layer <2023-02-22>
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class

(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/base/size10.clo
luaotfload | db : Font names database not found, generating new one.
luaotfload | db : This can take several minutes; please be patient.))
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/fontsetup/fontsetup.sty
fontsetup: Easy font setup by Antonis Tsolomitis

(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/fontspec/fontspec.sty
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/l3packages/xparse/xparse.sty
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/l3kernel/expl3.sty
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/l3backend/l3backend-luatex.def)))
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/fontspec/fontspec-luatex.sty
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/base/fontenc.sty)
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/fontspec/fontspec.cfg)))
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/base/ifthen.sty)
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/gen
eric/iftex/iftex.sty)
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/fontsetup/fspfiraot.sty
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/unicode-math/unicode-math.sty
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/unicode-math/unicode-math-luatex.sty
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/l3packages/l3keys2e/l3keys2e.sty)
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/base/fix-cm.sty
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/base/ts1enc.def))
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.

(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/amsmath/amstext.sty
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/amsmath/amsgen.sty))
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/amsmath/amsbsy.sty)
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/amsmath/amsopn.sty))
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lua
latex/lualatex-math/lualatex-math.sty
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/etoolbox/etoolbox.sty))
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/unicode-math/unicode-math-table.tex)))))
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/lipsum/lipsum.sty
(/nix/store/las8ff1qk473jy0312flsr7ds7b5qxng-texlive-2022-env-texmfdist/tex/lat
ex/lipsum/lipsum.ltd.tex)) (./test.aux)

Package lipsum Warning: Unknown language 'latin'. Hyphenation patterns for
(lipsum)                'english' will be used instead.
(lipsum)                
(lipsum)                With LuaTeX, lipsum requires babel to get proper
(lipsum)                hyphenation (you can use \usepackage[base]{babel}).

[1{/nix/store/g6m9k0m4vr4bvmga9imv49wn552rfl6c-texlive-2022-env/share/texmf-var
/fonts/map/pdftex/updmap/pdftex.map}] [2] (./test.aux))
 484 words of node memory still in use:
   6 hlist, 2 vlist, 2 rule, 2 glue, 4 kern, 1 glyph, 6 attribute, 52 glue_spec
, 6 attribute_list, 1 write nodes
   avail lists: 2:38,3:41,4:14,5:1024,6:11,7:7347,9:118,10:9,11:554
</nix/store/yqk0id5a7c7fqjkgj5npvg8cfyl0paws-texlive-fira-4.3/fonts/opentype/pu
blic/fira/FiraSans-Regular.otf>
Output written on test.pdf (2 pages, 10774 bytes).
Transcript written on test.log.
```

If there is something to be fixed, let's find a reproducer.

**Comment by benneti** [comment] 2024-01-04 17:37
Yes, still it pointed me into the right direction, my path changed after I cleared the lua font cache by removing `$HOME/.texlive` which apparently contained a broken font.
I think this issue can be closed, except if there is a mechanism that could ensure that this cache is not mismatched with the nix store (which I doubt).

**Comment by xworld21** [comment] 2024-01-04 17:57
> if there is a mechanism that could ensure that this cache is not mismatched with the nix store (which I doubt)

This sounds like a duplicate of #180639: can/should we generate a system font cache for Lua directly within the TeX Live environment? Would that solve the issue at hand? I have no idea! And one should weight the benefits against the build time costs which may (or may not) be significant.

**Comment by benneti** [comment] 2024-01-04 18:09
indeed it looks very related.
Also I think generating the fontcache could avoid this issue, as I was able to fix it by removing the fontcache and generating a new one.
I think it might be feasible to at least add a comment to the docs stating that problems with the fontcache might arise with lualatex.
Would `doc/languages-frameworks/texlive.section.md` be appropriate, if you want I could add a section at the end of the file?

**Closed** 2024-01-12 15:47 UTC
Labels: 0.kind: bug, 6.topic: TeX
