### ISSUE TITLE
kmod: patch fails on darwin

### ISSUE THREAD

**Issue by lilyball** [NixOS/nixpkgs#184862] opened 2022-08-02 17:47 UTC
### Steps To Reproduce
1. build `kmod` on darwin

### Build log
```
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/i4q069m3d29gi7dw1ijhjrp4hxw1c2l4-module-dir.patch
patching file Makefile.am
patching file configure.ac
Hunk #1 succeeded at 276 with fuzz 2 (offset 74 lines).
patching file libkmod/libkmod.c
Hunk #1 succeeded at 208 (offset 2 lines).
Hunk #2 succeeded at 224 (offset 2 lines).
patching file tools/static-nodes.c
applying patch /nix/store/k6h6xgq4440gp3gwn3wbg4nqbggnd24q-darwin.patch
patching file Makefile.am
Hunk #1 succeeded at 99 (offset 19 lines).
Hunk #2 succeeded at 109 (offset 19 lines).
patching file libkmod/libkmod-module.c
Hunk #1 succeeded at 849 with fuzz 1 (offset 62 lines).
Hunk #2 succeeded at 946 (offset 63 lines).
patching file libkmod/libkmod-signature.c
Hunk #1 succeeded at 17 with fuzz 2.
patching file shared/macro.h
patching file shared/missing.h
patching file shared/util.c
Hunk #1 succeeded at 370 (offset 3 lines).
patching file shared/util.h
Hunk #1 FAILED at 7.
1 out of 1 hunk FAILED -- saving rejects to file shared/util.h.rej
```

### Additional context
`kmod` was updated in https://github.com/NixOS/nixpkgs/pull/181170 but it seems nobody tested it on darwin.

### Notify maintainers
@Artturin 

### Metadata

 - system: `"x86_64-darwin"`
 - host os: `Darwin 22.0.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.10.3`
 - channels(lily): `"darwin, home-manager"`
 - channels(root): `"nixpkgs-21.11pre329221.c11d08f0239"`
 - nixpkgs: `github:NixOS/nixpkgs/07c6ff07ce85fde644679aa36560ee67404b2804`

**Comment by Artturin** [comment] 2022-08-02 18:15
Dupe of https://github.com/NixOS/nixpkgs/issues/184213

**Closed by Artturin** 2022-08-02 18:15 UTC
Labels: 0.kind: build failure
