### ISSUE TITLE
qtbase: Creates stray dir in nix-shell

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#11552] opened 2015-12-08 13:32 UTC
`qt-test.nix`:
```nix
with (import <nixpkgs> {});

stdenv.mkDerivation {
  name = "qttest";
  buildInputs = [pkgs.qt5.base];
}
```

```
> mkdir tmp && cd tmp
> nix-shell ../qt-test.nix
qmake: File exists
shell> ls
qmake-qttest
^D
> ls
qmake-qttest
> nix-shell ../qt-test.nix 
cp: cannot create regular file ‘/home/<user>/nixpkgs/tmp/qmake-qttest/bin/qmake’: Permission denied
```

It creates a stateful directory in the *current working dir* and fails to delete it, causing a second evocation to completely fail. Joy.
The created directory is named `qmake-${name}`.

cc @qknight @ttuegel (no idea who bbenoist is)

**Comment by ttuegel** [comment] 2015-12-08 15:02
Duplicate of #10273. I will reopen it, as I thought this was fixed.

**Closed by ttuegel** 2015-12-08 15:02 UTC
