### ISSUE TITLE
Dolphin doesn't show all (WEBP) image previews

### ISSUE THREAD

**Issue by donottellmetonottellyou** [NixOS/nixpkgs#345723] opened 2024-10-01 16:14 UTC
### Describe the bug
Dolphin supports image previews, however it does not work with WEBP out-of-the-box.

### Steps To Reproduce
1. set `services.desktopManager.plasma6.enable = true`
2. Open Dolphin with previews enabled and icon view
3. Open a folder with WEBP images
4. Images show a placeholder icon
5. Can open in Gwenview as usual

### Expected behavior
I expect that all image formats supported by Gwenview would also be supported by Dolphin for previews.

Gwenview has a dependency on `qtimageformats`, and is installed with plasma by default. Adding `qtimageformats` to my config fixes this issue. Perhaps `qtimageformats` could be added as an optional dependency of `plasma6`, since `kimageformats` is already a required dependency in this way.

This is possibly also applicable to `plasma5`, since it doesn't use `qtimageformats` either.

### Screenshots
![image](https://github.com/user-attachments/assets/a50aca14-e02a-4534-9e2d-494a468f83ef)

### Notify maintainers

@SuperSandro2000 @K900 @omentic @oxalica @stuebinm @peterhoeg @Stzx @eclairevoyant @MinerSebas @fpletz @mjm 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.52, NixOS, 24.05 (Uakari), 24.05.5366.fbca5e745367`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"home-manager-24.05.tar.gz, nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by christoph-cullmann** [comment] 2024-10-16 15:59
I have a similar issue in unstable. But for me the

/nix/store/cy5gab6y2hiqbx7a35cmr0z3j7c6y7wq-kimageformats-6.7.0/lib/qt-6/plugins/

in the QT_PLUGIN_PATH of my Plasma 6 session. That breaks e.g. jpegxl backgrounds.

**Comment by K900** [comment] 2024-10-16 16:01
It looks like Qt 6.8 broke things wrt plugin discovery: https://bugreports.qt.io/browse/QTBUG-130109

We have a patch and I'll send it to staging-next once it's merged upstream.

**Comment by christoph-cullmann** [comment] 2024-10-16 16:04
Thanks!

**Comment by kik4444** [comment] 2024-10-23 21:34
I believe I have a similar issue, except that in my case not even gwenview can open the images, let alone Dolphin preview them. If I try to open e.g. an avif image it says `Gwenview cannot display documents of type image/avif` even though I have explicitly installed libavif and kimageformats and qtimageformats

**Comment by K900** [comment] 2024-10-24 06:19
Yes, this is the same regression, fix is in staging-next.

**Comment by kik4444** [comment] 2024-10-31 06:20
How long until it hits unstable?

**Comment by K900** [comment] 2024-10-31 06:21
A couple days, probably.

**Comment by kik4444** [comment] 2024-11-08 12:37
This is fixed for me now on unstable

**Closed** 2024-11-08 12:38 UTC
Labels: 0.kind: bug, 6.topic: qt/kde

**Comment by donottellmetonottellyou** [comment] 2025-03-01 12:15
This fix never made it into 24.11

**Comment by K900** [comment] 2025-03-01 12:16
Qt 6.8.2 contains the fix.

**Comment by donottellmetonottellyou** [comment] 2025-03-01 12:19
> Qt 6.8.2 contains the fix.

Stable is 6.8.1

**Comment by K900** [comment] 2025-03-01 12:24
It's in current staging-next-24.11, which should be ready in a few days.

**Comment by donottellmetonottellyou** [comment] 2025-03-14 21:11
> Qt 6.8.2 contains the fix.

It doesn't, unfortunately. My system still doesn't display WEBP in dolphin with that Qt version. They also do not display on the desktop or anywhere. Some files still have cached icons from before I disabled the fix, but any newer files do not display previews, and the zoomed in preview on the side doesn't show.

**Comment by K900** [comment] 2025-03-15 06:05
Are you running Plasma 6?

**Comment by donottellmetonottellyou** [comment] 2025-03-15 21:38
> Are you running Plasma 6?

Yes

**Comment by K900** [comment] 2025-03-16 05:52
Oh I see, https://github.com/NixOS/nixpkgs/pull/306227 was never backported. Doing that now.
