### ISSUE TITLE
Update request: anydesk 6.3.1 → 6.3.2

### ISSUE THREAD

**Issue by sicet7** [NixOS/nixpkgs#306631] opened 2024-04-24 20:26 UTC
- Package name: anydesk
- Latest released version: 6.3.2

- Current version on the unstable channel: 6.3.1
- Current version on the stable/release channel: 6.3.0

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@shyim 
@cheriimoya 
-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AmeerTaweel** [comment] 2024-04-29 03:44
Should this be closed since the PR has been merged?

**Comment by AmeerTaweel** [comment] 2024-04-29 03:47
Also, it seems that AnyDesk only keeps the latest version and deletes the older ones from their servers. Thus breaking reproducibility  of derivations. Is making a copy of the sources using the Wayback machine and using that as a fallback link a good idea?

**Comment by JohnRTitor** [comment] 2024-04-29 05:25
Closed as #306850 is merged.

**Closed by JohnRTitor** 2024-04-29 05:25 UTC
Labels: 9.needs: package (update)
