### ISSUE TITLE
interception-tools does not function whatsoever

### ISSUE THREAD

**Issue by MonAaraj** [NixOS/nixpkgs#185967] opened 2022-08-10 19:36 UTC
### Describe the bug
Upon configuring interception tools correctly (the configuration is at the bottom), it doesn't do anything to change the behavior of the keys as the configuration mentions. The configuration has been done as the documentation suggests, to my knowledge.

Also, it doesn't install `uinput` if i `services.interception-tools.enable = true;`. nor `intercept-input`.
This is my entire configuration repository: https://git.sr.ht/~monaaraj/nixos-config

### Steps To Reproduce
1.I set, in my default.nix file:
```nix
      services.interception-tools = {
        enable = true;
        plugins = [ pkgs.interception-tools-plugins.dual-function-keys ];
        udevmonConfig = ''
          - JOB: "intercept-input -g $DEVNODE | dual-function-keys -c ./dual-function-keys.yml | uinput -d $DEVNODE"
            DEVICE:
              NAME: "SEMICO USB Keyboard"
        '';
      };
```
2. Create a file in the same directory as my default.nix, called `dual-function-keys.yml`, with the contents:
```yml
TIMING:
  TAP_MILLISEC: 200
  DOUBLE_TAP_MILLISEC: -1

MAPPINGS:
  - KEY: KEY_CAPSLOCK
    TAP: KEY_ESC
    HOLD: KEY_LEFTMETA
```
3. Rebuild. Notice that the `uinput` and `intercept-input` haven't been installed. Also, the behavior described in `dual-function-keys.yml` as well as `udevmonConfig` is not being executed by interception-tools. **NOTE THAT YOU NEED TO CHANGE THE `NAME` FIELD TO YOUR OWN KEYBOARD, IF YOU'RE GOING TO TEST THIS CONFIGURATION.**

### Expected behavior
Installs `uinput` and `intercept-input`, and when my capslock is tapped, it acts as escape. if my capslock is held with any other key, it would act as SUPER
### Notify maintainers
@vyp @ncfavier 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

/nix/store/83l8wwrx7xs3mh9sbbj6whmyx8y4cz36-stdenv-linux/setup:14: command not found: shopt
_nix_shell_clean_tmpdir: command not found: rm

```

**Comment by MonAaraj** [comment] 2022-08-10 19:38
Furthermore, it looks like @vyp has been inactive for about a year by now, should a new maintainer be attributed?

**Comment by MonAaraj** [comment] 2022-08-10 19:39
Also, I forgot to mention @pennae

**Comment by ncfavier** [comment] 2022-08-10 19:40
Why was I pinged? I don't maintain that package

**Comment by MonAaraj** [comment] 2022-08-10 19:42
Ah, sorrry :/ it looks like GitHub put you in the commit history of that file for doing some documentation change. I really apologize!

**Comment by pennae** [comment] 2022-08-10 19:44
same here, only changed docs.

**Comment by MonAaraj** [comment] 2022-08-10 19:49
Alright! I apologize as well. If the original maintainer does not reply, I think I'll step forward to maintain the package.

**Comment by pennae** [comment] 2022-08-10 22:06
as for your bug report, here's a guess:
```diff
       services.interception-tools = {
         enable = true;
         plugins = [ pkgs.interception-tools-plugins.dual-function-keys ];
         udevmonConfig = ''
-           - JOB: "intercept-input -g $DEVNODE | dual-function-keys -c ./dual-function-keys.yml | uinput -d $DEVNODE"
+           - JOB: "intercept-input -g $DEVNODE | dual-function-keys -c ${./dual-function-keys.yml} | uinput -d $DEVNODE"
             DEVICE:
               NAME: "SEMICO USB Keyboard"
         '';
       };
``

**Comment by MonAaraj** [comment] 2022-08-10 22:44
Nope, it still has the same behavior for whatever reason. But thank you very much for your guess!

**Comment by pennae** [comment] 2022-08-10 22:53
looking at the package it also seems that there is no `intercept-input`, only an `intercept`. there's also a `uinput`, both of which will be available to the service. the service definition looks like it'll add all those to the path of the service, maybe it's just not logging exec failures?

**Comment by MonAaraj** [comment] 2022-08-10 23:12
Both `intercept` and `uinput` aren't runnable despite enabling the service on my shell.

**Comment by pennae** [comment] 2022-08-10 23:15
not runnable from the shell or not runnable from the service itself? (the module does not add them to the global environment, only that specific service will have access to them)

are there any logs in the journal for this service?

**Comment by MonAaraj** [comment] 2022-08-11 06:44
Yes, not runnable from the shell, I had guessed that this is the reason it didn't work, but I suppose it's just intended behavior. `journalctl -u udevmon` seems to hang indefinitely, for whatever reason. Is there another way to get the logs for the service? Is there nothing in the nix code that might imply it's going wrong, just that it doesn't work for me?

**Comment by pennae** [comment] 2022-08-11 06:48
the service isn't `udevmon`, it's `interception-tools.service`. but just passing `-f`, restarting the service and doing something that should work should produce all the log message you'd ever expect to see from it failing

**Comment by MonAaraj** [comment] 2022-08-11 06:53
```
Aug 11 09:52:55 nixos systemd[1]: Stopping Interception tools...
Aug 11 09:52:56 nixos systemd[1]: interception-tools.service: Deactivated successfully.
Aug 11 09:52:56 nixos systemd[1]: Stopped Interception tools.
Aug 11 09:52:56 nixos systemd[1]: Started Interception tools.
Aug 11 09:52:56 nixos polkitd[7995]: Unregistered Authentication Agent for unix-process:18208:915979 (system bus name :1.105, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Aug 11 09:52:56 nixos udevmon[18244]: sh: line 1: intercept-input: command not found
Aug 11 09:52:56 nixos udevmon[18245]: sh: line 1: dual-function-keys: command not found
Aug 11 09:52:56 nixos udevmon[18246]: sh: line 1: uinput: command not found
Aug 11 09:52:56 nixos udevmon[18248]: sh: line 1: intercept-input: command not found
Aug 11 09:52:56 nixos udevmon[18249]: sh: line 1: dual-function-keys: command not found
Aug 11 09:52:56 nixos udevmon[18250]: sh: line 1: uinput: command not found
```
here's the relevant part

**Comment by MonAaraj** [comment] 2022-08-11 06:55
So, this tells me a couple of things: 1. It detects when I press my capslock, because it printed these the 2 times i pressed capslock to test. 2. The package *not* providing these commands makes for a major issue.

**Comment by MonAaraj** [comment] 2022-08-11 18:53
After some discussions on the matrix, I have discovered that firstly, the documentation of this package is wholly incorrect. Secondly, that this is a known issue with the interception-tools projects themselves. https://gitlab.com/interception/linux/tools/-/issues/58

What I have done to solve this, is simply refer to these binaries by their full paths.

**Comment by MonAaraj** [comment] 2022-08-11 20:48
I think I'll keep this issue open until the documentation gets fixed, which I might PR later on.

**Comment by infinisil** [comment] 2022-09-09 18:51
Recently, @lheckemann posted a patch to the above issue: https://gitlab.com/interception/linux/tools/-/issues/58#note_1078552203

I think it would be best to just apply that patch to our interception-tools package, then we don't need to update the documentation and the NixOS module can work as-is.

**Comment by MonAaraj** [comment] 2022-09-09 19:24
Sounds good. Thank you very much.

**Comment by lheckemann** [comment] 2022-09-10 09:08
Duplicate of #126681 where there's some discussion about the "right" approach to fix this

**Closed by lheckemann** 2022-09-10 09:08 UTC
Labels: 0.kind: bug, 6.topic: nixos
