### ISSUE TITLE
Package request: Dangerzone

### ISSUE THREAD

**Issue by DarkOnion0** [NixOS/nixpkgs#268336] opened 2023-11-18 17:10 UTC
**Project description**

Take potentially dangerous PDFs, office documents, or images and convert them to safe PDFs 

**Metadata**

* homepage URL: https://dangerzone.rocks/
* source URL: https://github.com/freedomofpress/dangerzone
* license: MIT
* platforms: linux, darwin, windows

**Comment by eclairevoyant** [comment] 2024-03-18 13:03
duplicate of #189761

**Closed by eclairevoyant** 2024-03-18 13:03 UTC
Labels: 0.kind: packaging request
