### ISSUE TITLE
Build failure: bitwarden-desktop

### ISSUE THREAD

**Issue by ugur-a** [NixOS/nixpkgs#349491] opened 2024-10-18 09:24 UTC
### Steps To Reproduce

1. build bitwarden-desktop

### Build log
The failure seems to happen during `checkPhase`:
``` log
Running phase: checkPhase
@nix { "action": "setPhase", "phase": "checkPhase" }
~/source/apps/desktop/desktop_native ~/source
Executing cargoCheckHook
environment: line 7: prependToVar: command not found
```
Full log: https://gist.github.com/ugur-a/d742c480029d52144ef4df754102e1dd

### Additional context
I've tried digging a little.
1. `cargoCheckHook` is defined at https://github.com/NixOS/nixpkgs/blob/a3c0b3b21515f74fd2665903d4ce6bc4dc81c77c/pkgs/build-support/rust/hooks/cargo-check-hook.sh
2. `prependToVar` is first used on line 15: https://github.com/NixOS/nixpkgs/blob/a3c0b3b21515f74fd2665903d4ce6bc4dc81c77c/pkgs/build-support/rust/hooks/cargo-check-hook.sh#L15
3. ... and defined at https://github.com/NixOS/nixpkgs/blob/a3c0b3b21515f74fd2665903d4ce6bc4dc81c77c/pkgs/stdenv/generic/setup.sh#L322

So theoretically, `prependToVar` should be found, but for some reason it isn't.

I couldn't find any recent commits touching any of these.

### Notify maintainers
@amarshall (though I'm unsure whether Bitwarden actually has anything to do with this)
@dotlambda (because of #343097)

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.53, NixOS, 24.11 (Vicuna), 24.11.20241001.27e30d1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/lryfc8mhk1czqsa421di2y5nzz5c3b8m-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jackwilsdon** [comment] 2024-10-18 09:34
I can't seem to reproduce this on master or 27e30d1 (from your `nix-info`):

```text
Running phase: checkPhase
~/source/apps/desktop/desktop_native ~/source
Executing cargoCheckHook
+ cargo test -j 2 --profile release --target x86_64-unknown-linux-gnu --offline -- --test-threads=2 --skip=password::password::tests::test
warning: `/build/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
   Compiling proc-macro2 v1.0.86
   Compiling unicode-ident v1.0.12
   Compiling serde v1.0.209
   Compiling quote v1.0.37
   Compiling syn v2.0.77
   Compiling equivalent v1.0.1
   Compiling libc v0.2.155
   Compiling hashbrown v0.14.5
   Compiling indexmap v2.5.0
   Compiling toml_datetime v0.6.8
   Compiling serde_spanned v0.6.7
   Compiling cfg-if v1.0.0
   Compiling winnow v0.6.18
   ... continues and build completes ...
```

**Comment by Atemu** [comment] 2024-10-18 09:42
Duplicate of https://github.com/NixOS/nixpkgs/issues/348920

**Closed by Atemu** 2024-10-18 09:42 UTC
Labels: 0.kind: build failure
