### ISSUE TITLE
prowlarr: not working correctly without user

### ISSUE THREAD

**Issue by Stunkymonkey** [NixOS/nixpkgs#155475] opened 2022-01-18 13:43 UTC
### Describe the bug
when using:
```
services.prowlarr.enable = true;
```
the resulting service is having multiple errors and does not work like intended:
```
2022-01-18 14:21:35.8|Fatal|ProwlarrErrorPipeline|Request Failed. GET /api/v1/update

[v0.1.8.1231] System.Net.WebException: The SSL connection could not be established, see inner exception.: 'https://prowlarr.servarr.com/v1/update/develop/changes?version=0.1.8.1231&os=linux&arch=Arm64&runtime=netc
ore&runtimeVer=6.0.0&prevVersion=0.1.2.1060&active=false'
 ---> System.Net.WebException: The SSL connection could not be established, see inner exception.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.InvalidOperationException: The home directory of the current user could not be determined.
```

### Steps To Reproduce
1. `services.prowlarr.enable = true;`

### Expected behavior
No errors and the applications works

### Possible ugly fix:
adding:
```
users.users.prowlarr = {
  isSystemUser = true;
  home = "/var/lib/prowlarr";
  group = "prowlarr";
  uid = 61654;
};
users.groups.prowlarr.gid = 61654;
```

### Notify maintainers

@jdreaver

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/vs01795cwqz8mf3fxvhh85dhwh3w9h6d-bash-interactive-5.1-p8-dev
copying path '/nix/store/vs01795cwqz8mf3fxvhh85dhwh3w9h6d-bash-interactive-5.1-p8-dev' from 'https://cache.nixos.org'...
 - system: `"aarch64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.335288.3ddd960a3b5, nixos-unstable-22.05pre343321.78cd22c1b86"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Alexnortung** [comment] 2022-01-30 11:39
I am having the same issue.
I have tried using the fix and it seems to work for me.

**Comment by wyndon** [comment] 2022-04-08 11:27
Prowlarr is (still) broken.

**Comment by newAM** [comment] 2022-04-09 04:13
@wyndon the recent breakage may be due to a different issue, see #167916

**Comment by justinas** [comment] 2022-04-09 11:30
I had *some* issue with prowlarr at one point, and this solved it:

```nix
systemd.services.prowlarr.environment.HOME = "/var/empty";
```

Might be the same problem, as I vaguely remember something about SSL, and this seemed to help (without needing to make prowlarr run under a "proper", non-dynamic user).

**Comment by hacker1024** [comment] 2023-03-17 03:00
> I had _some_ issue with prowlarr at one point, and this solved it:
> 
> ```nix
> {
>   systemd.services.prowlarr.environment.HOME = "/var/empty";
> }
> ```
> 
> Might be the same problem, as I vaguely remember something about SSL, and this seemed to help (without needing to make prowlarr run under a "proper", non-dynamic user).
> 
> dotnet seems to not like `$HOME` being unset (which I assume is what happens when running under `DynamicUser`). Not sure why this does not happen with other *arr-s.

This is a good fix. It should be added to the NixOS module.

**Comment by justinas** [comment] 2023-03-17 15:50
> This is a good fix. It should be added to the NixOS module.

@hacker1024 Is this still an issue on current 22.11/nixos-unstable? I am willing to contribute the fix to the module, however:
1. From what I remember, I was never able to reproduce this consistently (prowlarr would fail on my server, but work on my personal workstation)
2. There's a NixOS test for prowlarr and it passes, so it doesn't help us verify that the issue would be fixed by this.

**Comment by hacker1024** [comment] 2023-03-18 11:45
> > This is a good fix. It should be added to the NixOS module.
> 
> @hacker1024 Is this still an issue on current 22.11/nixos-unstable? I am willing to contribute the fix to the module, however:
> 
>     1. From what I remember, I was never able to reproduce this consistently (prowlarr would fail on my server, but work on my personal workstation)
> 
>     2. There's a NixOS test for prowlarr and it passes, so it doesn't help us verify that the issue would be fixed by this.

It definitely does happen on nixos-unstable, though indeed inconsistently - I only faced this issue after my server's last monthly upgrade, though Prowlarr had been running just fine for months!

**Comment by justinas** [comment] 2023-03-18 12:13
> It definitely does happen on nixos-unstable, though indeed inconsistently - I only faced this issue after my server's last monthly upgrade, though Prowlarr had been running just fine for months!

Got it. Feel free to create a PR, should be easy enough to add this to NixOS module. You should be able to test it with your server as well. Else, I'll do it sometime in the coming days hopefully :slightly_smiling_face:

**Comment by Stunkymonkey** [comment] 2023-10-29 17:28
I reinstalled my machine and it worked perfectly. Not sure if this is still a valid issue.

**Comment by dlip** [comment] 2024-01-17 04:08
still getting this issue

**Comment by purepani** [comment] 2024-05-22 06:21
Got this issue after upgrading(haven't upgraded in a while).

**Comment by justinas** [comment] 2024-06-05 12:31
@purepani @dlip Could you confirm that the option suggested in https://github.com/NixOS/nixpkgs/issues/155475#issuecomment-1093940244 fixes your problems? If so, I will make a PR to include it in the `prowlarr` module.

Sorry I kind of forgot about this issue, since I've applied this fix in my configuration and did not encounter the problem afterwards.

**Comment by purepani** [comment] 2024-06-05 12:33
Yes, including that line fixed the issues.

**Comment by purepani** [comment] 2024-06-11 17:01
On my phone rn so I can't test it, but does starting it before "network-online.target" make it deterministically fail, by chance?

**Closed** 2024-09-03 10:08 UTC
Labels: 0.kind: bug, 6.topic: nixos

**Comment by leoperegrino** [comment] 2025-02-09 22:25
FYI I was trying to setup prowlarr in a nixos-container and mount it's data directory so it could be persisted but this kept failing with [`Device or resource busy`](https://github.com/systemd/systemd/issues/29226). Searched arround a bit and it seems to be related to how [`DynamicUser`](https://0pointer.net/blog/dynamic-users-with-systemd.html) works in systemd and how it hardens the filesystem security.

Since prowlarr is [configured as a DynamicUser](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/misc/prowlarr.nix#L34) this was able to allow the mount:

```nix
container."prowlarr".config = {...}: {
# ...
  systemd.services.prowlarr.serviceConfig.DynamicUser = lib.mkForce false;
  systemd.services.prowlarr.serviceConfig.User = "prowlarr";
  systemd.services.prowlarr.serviceConfig.Group = "prowlarr";
  systemd.services.prowlarr.environment.HOME = lib.mkForce null;
# ...
};
```

maybe this serves as a heads up for future systemd service implementations as DynamicUser and it's consequences
