### ISSUE TITLE
pidgin does not find icon for SIPE plugin

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#9874] opened 2015-09-15 13:58 UTC
I'm not sure whether this is a pidgin or pidgin-sipe (the plugin) issue, but the result is no icon.

I see in the log that pidgin-sipe looks for its icon in pidgin directory:

```
$ pidgin -d
...
(15:51:57) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file /nix/store/adb6bqnpnyb4crb8wl2ibq0sywmgfnp5-pidgin-2.10.11/share/pixmaps/pidgin/protocols/16/sipe.png: Failed to open file '/nix/store/adb6bqnpnyb4crb8wl2ibq0sywmgfnp5-pidgin-2.10.11/share/pixmaps/pidgin/protocols/16/sipe.png': No such file or directory
```

sipe.png is found in *pidgin-sipe* output:

```
$ find /nix/store/1i0mdncw7a34jp23hifmvcdk5kk4dimj-pidgin-sipe-1.18.1 -name sipe.png
/nix/store/1i0mdncw7a34jp23hifmvcdk5kk4dimj-pidgin-sipe-1.18.1/share/pixmaps/pidgin/protocols/24/sipe.png                                                                                                                                    
/nix/store/1i0mdncw7a34jp23hifmvcdk5kk4dimj-pidgin-sipe-1.18.1/share/pixmaps/pidgin/protocols/48/sipe.png                                                                                                                                    
/nix/store/1i0mdncw7a34jp23hifmvcdk5kk4dimj-pidgin-sipe-1.18.1/share/pixmaps/pidgin/protocols/22/sipe.png                                                                                                                                    
/nix/store/1i0mdncw7a34jp23hifmvcdk5kk4dimj-pidgin-sipe-1.18.1/share/pixmaps/pidgin/protocols/16/sipe.png                                                                                                                                    
/nix/store/1i0mdncw7a34jp23hifmvcdk5kk4dimj-pidgin-sipe-1.18.1/share/pixmaps/pidgin/protocols/32/sipe.png                                                                                                                                    
```

I use ```pidgin-with-plugins.override { plugins = [ pidginsipe ]; }```.

**Comment by vcunat** [comment] 2015-09-15 14:11
Duplicate of #8999.

**Closed by vcunat** 2015-09-15 14:11 UTC
Labels: duplicate
