### ISSUE TITLE
mesa: using a newer mesa version for drivers crashes DEs under wayland

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#223729] opened 2023-03-29 11:01 UTC
### Describe the bug

Changing mesa version via `hardware.opengl.mesaPackage` apparently causes modern DEs and login managers to crash:

https://github.com/NixOS/nixpkgs/issues/223458
https://github.com/NixOS/nixpkgs/issues/223331
https://github.com/NixOS/nixpkgs/issues/223535

https://github.com/NixOS/nixpkgs/pull/223530

### Expected behavior

It should "just work".

### Additional context

Perhaps this is due to some direct dependance on mesa's libGL. If that's the case, we could make them depend on the vendor-agnostic libGL instead.

If it's due to libgbm, we might have a problem on our hands as that essentially makes `hardware.opengl.mesaPackage` useless on modern software stacks.

### Notify maintainers

@R-VdP @K900 @vcunat 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by pr0ton11** [comment] 2023-03-31 21:46
Hi
Could this be prioritized? I can not boot my workstation with mesa 23 anymore.
I can help with logs if you need anything

**Comment by Atemu** [comment] 2023-03-31 21:49
@pr0ton11 wdym by "anymore"? Did it work before?

**Comment by SuperSandro2000** [comment] 2023-03-31 23:53
> Could this be prioritized? I can not boot my workstation with mesa 23 anymore.

The revert that made mesa_23 the default is already reverted and soon in nixos-unstable.

**Comment by vcunat** [comment] 2023-04-01 05:26
I believe it _was_ in all channels already.  Historical data are harder to show, but it certainly is at this moment: https://nixpk.gs/pr-tracker.html?pr=223530

And BTW, you can switch the default around easily in your config, e.g. in case you want to temporarily use something else than the latest channels.

**Comment by ElvishJerricco** [comment] 2023-04-02 23:17
Just stream-of-consciousness'ing our findings in a Matrix channel with @K900.

Symptoms: When GDM starts, the display goes to sleep. I can switch VTs, but once I switch back to the GDM VT, the existing image remains and nothing happens. It *is* responsive though. I can pretend as though it's visible and use the keyboard to log in. When I do, the image on the screen remains frozen, but the sessions is successfully running invisibly.

Gnome Shell seems to be saying this:

```
Apr 02 13:30:46 jace .gnome-shell-wr[3962]: Running GNOME Shell (using mutter 43.3) as a Wayland display server
Apr 02 13:30:46 jace .gnome-shell-wr[3962]: Device '/dev/dri/card0' prefers shadow buffer
Apr 02 13:30:46 jace .gnome-shell-wr[3962]: Added device '/dev/dri/card0' (amdgpu) using atomic mode setting.
Apr 02 13:30:46 jace .gnome-shell-wr[3962]: Device '/dev/dri/card1' prefers shadow buffer
Apr 02 13:30:46 jace .gnome-shell-wr[3962]: Added device '/dev/dri/card1' (amdgpu) using atomic mode setting.
Apr 02 13:30:46 jace .gnome-shell-wr[3962]: Created gbm renderer for '/dev/dri/card0'
Apr 02 13:30:46 jace .gnome-shell-wr[3962]: Created gbm renderer for '/dev/dri/card1'
Apr 02 13:30:46 jace .gnome-shell-wr[3962]: Boot VGA GPU /dev/dri/card0 selected as primary
Apr 02 13:30:46 jace .gnome-shell-wr[3962]: Failed to allocate onscreen framebuffer for /dev/dri/card0: EGL failed to allocate resources for the requested operation.
```

Setting `services.xserver.displayManager.gdm.wayland = false;` gets me to a working desktop though.

We found [this](https://gitlab.freedesktop.org/mesa/mesa/-/issues/8729).

Tried [this](https://gitlab.freedesktop.org/mesa/mesa/-/commit/9c90deefb2356c970520a404375b0e1796df1535) from [here](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/22170) to fix it. No luck. Same behavior.

Sway worked fine.

[This might be related](https://gitlab.freedesktop.org/mesa/mesa/-/issues/8431).

We wanted to try with `MUTTER_DEBUG_SEND_KMS_MODIFIERS=0`, but couldn't figure out how to get the environment variable passed into the `gnome-shell` process. `systemd.services.display-manager.environment` didn't do it, `services.xserver.displayManager.setupCommands` didn't do it, and `services.xserver.displayManager.job.environment` didn't do it.

Rebuilding the world with an overlay that sets `mesa = final.mesa_23;` *does* result in a working desktop though, so there must be some incompatibility between mesa 22 libs and mesa 23 drivers.

**Comment by pr0ton11** [comment] 2023-04-03 07:26
> @pr0ton11 wdym by "anymore"? Did it work before?

No, it didn't. I am using the workaround of setting mesa to 22 atm, awaiting a fix for mesa 23 (I would profit from this because I use a new AMD card).

**Comment by K900** [comment] 2023-04-03 07:28
I think we'll just have to upstream with this unless someone with the requisite knowledge can get their hands on a device that's affected and debug locally...

**Comment by K900** [comment] 2023-04-03 07:31
Also, just for statistics' sake, if you are affected, can you please post your specs (specifically _all_ GPUs, even if you don't use some of them), kernel version and which compositors are affected (Sway seems to be a good test to see if it's all of them or only some).

**Comment by R-VdP** [comment] 2023-04-03 08:47
> Also, just for statistics' sake, if you are affected, can you please post your specs (specifically _all_ GPUs, even if you don't use some of them), kernel version and which compositors are affected (Sway seems to be a good test to see if it's all of them or only some).

I was affected, I run an intel core i7 1260P with integrated graphics, no other GPU on the system.
Latest kernel from unstable, so 6.2.8.
Standard Gnome DE.

**Comment by Atemu** [comment] 2023-04-03 14:48
Also very important is wayland/Xorg.

**Comment by asininemonkey** [comment] 2023-04-03 17:26
For what it's worth you can simulate this breakage in a Parallels VM on macOS. I'm running unstable with mesa_22 in both my VM and my AMD 6800XT based home system:

Kernel: 6.2.8
GNOME: 43.3

**Comment by baduhai** [comment] 2023-04-05 14:54
If I run anything other than `hardware.opengl.mesaPackage = pkgs.mesa_22;` Plasma Wayland doesn't work, I just get a black screen. This is reproducible with both on my Ryzen desktop with an RX 6700X GPU, and my Intel laptop using the i5-10210U iGPU.

**Comment by Atemu** [comment] 2023-04-06 10:47
Does Xorg work?

**Comment by K900** [comment] 2023-04-07 18:02
Can someone test https://github.com/NixOS/nixpkgs/pull/225192 ?

**Comment by ElvishJerricco** [comment] 2023-04-07 18:43
@K900 I just tested it. I still get the same behavior.

- CPU: Ryzen 7950X
- iGPU: OpenGL renderer string: AMD Radeon Graphics (gfx1036, LLVM 15.0.7, DRM 3.49, 6.1.21)
- GPU: OpenGL renderer string: AMD Radeon RX 7900 XT (gfx1100, LLVM 15.0.7, DRM 3.49, 6.1.21)

**Comment by K900** [comment] 2023-04-07 20:01
So it looks like upstream just flat out doesn't support what we're doing anymore: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/20069

I have a cursed idea though...

**Comment by vcunat** [comment] 2023-04-10 07:53
Let's close this.  The `mesaPackage` option was reverted in PR #225325.

There will most likely be some related followups.  I even fear that at some point the mismatch between libgbm and drivers might be an issue (as libgbm is pure now and drivers from the OS, by default).

**Closed by vcunat** 2023-04-10 07:53 UTC
Labels: 0.kind: bug

**Comment by devmattrick** [comment] 2023-04-11 02:30
Is there an alternative/ workaround for those of us who need more recent Mesa drivers? RDNA 3 cards don't run the best on Mesa 22 in my experience, but 23 ran fine (well, until this issue of course). The impression that I'm getting is that there's not really anything I can do to get the Mesa 23 running with most DEs?

**Comment by ElvishJerricco** [comment] 2023-04-11 04:42
@devmattrick No, there isn't really a workaround, because the issue is that mesa upstream doesn't support mixing different versions anymore. i.e. There *will* be bugs if you try to mix 22 and 23 like this. The only thing you can really do is add an overlay causing *all of nixpkgs* to use 23, which requires you to recompile a ton of stuff.

**Comment by pr0ton11** [comment] 2023-04-11 13:38
@vcunat Could you add another comment here when it's merged, so I get pinged?

**Comment by Atemu** [comment] 2023-04-11 13:52
@pr0ton11 https://nixpk.gs/pr-tracker.html?pr=223238
