### ISSUE TITLE
`enableDebugging` does not work anymore: `error: attribute 'override' missing`

### ISSUE THREAD

**Issue by trofi** [NixOS/nixpkgs#136756] opened 2021-09-05 07:49 UTC
### Describe the bug

I tried to build a `nixpkgs` package with debug symbols today and failed. NixOS wiki and nixpkgs repository comments say the following should work:

### Steps To Reproduce

```
$ nix-build -E 'with import <nixpkgs> {}; enableDebugging hello'

error: attribute 'override' missing

       at /nix/store/0skp33kj13x8fyx141qbcfn5q6a4xghw-nixos-21.11pre312407.8a2ec31e224/nixos/pkgs/stdenv/adapters.nix:210:5:

          209|   keepDebugInfo = stdenv:
          210|     stdenv.override (old: {
             |     ^
          211|       mkDerivationFromStdenv = extendMkDerivationArgs old (args: {
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.13, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - channels(root): `"nixos-21.11pre312407.8a2ec31e224"`
 - channels(slyfox): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by trofi** [comment] 2021-09-05 08:08
It worked in Aug 2018: https://discourse.nixos.org/t/debug-symbols-for-nix-shell-and-nix-build/804/2?u=trofi

Bisected down to breakage at f110a182a66005782c0e58091bcda7243bf2a0ae:

```
$ git bisect bad
f110a182a66005782c0e58091bcda7243bf2a0ae is the first bad commit
commit f110a182a66005782c0e58091bcda7243bf2a0ae
Author: John Ericson <John.Ericson@Obsidian.Systems>
Date:   Mon Aug 16 21:16:29 2021 -0400

    stdenv: Fix overriding + `overrideAttrs`

    The old stdenv adapters were subtly wrong in two ways:

     - `overrideAttrs` leaked the original, unoverridden `mkDerivation`.

     - `stdenv.override` would throw away any manually-set `mkDerivation`
       from a stdenv reverting to the original.

    Now, `mkDerivation` is controlled (nearly directly) via an argument, and
    always correctly closes over the final ("self") stdenv. This means the
    adapters can work entirely via `.override` without any manual `stdenv //
    ...`, and both those issues are fixed.

    Note hashes are changed, because stdenvs no previously overridden like
    `stdenvNoCC` and `crossLibcStdenv` now are. I had to add some
    `dontDisableStatic = true` accordingly. The flip side however is that
    since the overrides compose, we no longer need to override anything but
    the default `stdenv` from which all the others are created.

 pkgs/os-specific/linux/musl/default.nix |   1 +
 pkgs/stdenv/adapters.nix                | 125 +++++++++++++++++++-------------
 pkgs/stdenv/generic/default.nix         |   8 +-
 pkgs/stdenv/generic/make-derivation.nix |  13 ++--
 pkgs/top-level/stage.nix                |   7 +-
 pkgs/top-level/static.nix               |  24 ------
 6 files changed, 94 insertions(+), 84 deletions(-)
 ```
 
 Looks like it stems from the fact that `hello.stdenv` does not expose `.override` anymore, only `.overrides`.

/cc @Ericson2314 https://github.com/NixOS/nixpkgs/pull/134463

**Comment by Ericson2314** [comment] 2021-09-05 15:12
Woah. master and `f110a182a66005782c0e58091bcda7243bf2a0ae` both work for me with nix stable.

**Comment by trofi** [comment] 2021-09-06 20:59
That's surprising. Here is my attempt at current master checkout:

```
$ nix-build -I nixpkgs=. -E 'with import <nixpkgs> {}; enableDebugging hello'
error: attribute 'override' missing

       at /tmp/nixpkgs/pkgs/stdenv/adapters.nix:210:5:

          209|   keepDebugInfo = stdenv:
          210|     stdenv.override (old: {
             |     ^
          211|       mkDerivationFromStdenv = extendMkDerivationArgs old (args: {
```

I tried removing `~/.nixpkgs` and seeing the same failure. I wonder why it works for you. Might be a different stdenv?

**Comment by trofi** [comment] 2021-09-06 21:03
```
$ nix repl -I nixpkgs=. '<nixpkgs>'

Welcome to Nix version 2.4pre20210802_47e96bb. Type :? for help.

Loading '<nixpkgs>'...
Added 14887 variables.

nix-repl> stdenv
«derivation /nix/store/ikgr1jlpvyqa7nci7p8r138n440vy7q2-stdenv-linux.drv»

nix-repl> pkgs.hello.stdenv
«derivation /nix/store/ikgr1jlpvyqa7nci7p8r138n440vy7q2-stdenv-linux.drv»

nix-repl> stdenv.override
{ __functionArgs = { ... }; __functor = «lambda @ /tmp/nixpkgs/lib/trivial.nix:327:19»; }

nix-repl> pkgs.hello.stdenv.override<tab>
pkgs.hello.stdenv.overrides
```

Does it mean `stdenv` and `pkgs.hello.stdenv` are the same object?

**Comment by Artturin** [comment] 2021-09-08 17:24
i can reproduce

**Comment by alyssais** [comment] 2021-09-09 17:32
I can also reproduce with stable Nix (2.3.14):

```
$ NIX_PATH=nixpkgs=. nix-build -E 'with import <nixpkgs> {}; enableDebugging hello'
error: attribute 'override' missing, at /home/src/nixpkgs/pkgs/stdenv/adapters.nix:210:5
```

**Comment by Ericson2314** [comment] 2021-09-10 23:11
Hmm, the issue is that `callPackage`/`makeOverridable` slaps the `.override` on `stdenv` *after* `stdenv.makeDerivation` is defined, closing over the old `stdenv`. In Smalltalk paralance, this would be an issue of insufficiently "late binding".

**Comment by symphorien** [comment] 2021-10-01 18:24
Still reproducible on current master (2652e0b47bc693be8241415d98cdc917c4c8d946)

**Comment by expipiplus1** [comment] 2021-11-11 10:13
There should be a test for this :)

**Comment by cab404** [comment] 2021-11-26 15:58
Gonna spend next hour or two trying to fix this.

**Comment by cab404** [comment] 2021-11-26 16:28
Things that are also missing:
```
[ "__bootPackages" "__hatPackages" "override" "overrideDerivation" ]
```

**Comment by cab404** [comment] 2021-11-26 19:19
https://github.com/NixOS/nixpkgs//blob/6078f094c638faabc63cffe285dc91af4e04a741/pkgs/stdenv/booter.nix#L89

So, this function is not executed on passed through stdenv. Not yet sure why.

**Comment by cab404** [comment] 2021-11-26 22:17
Yeah, I've fixed it (thanks, @mrgutkun, for being there :heart:)

**Comment by cab404** [comment] 2021-11-26 22:28
https://github.com/NixOS/nixpkgs/pull/147544

**Comment by cab404** [comment] 2021-11-27 00:05
Post-mortem: always read threads. Solution was kinda already provided in https://github.com/NixOS/nixpkgs/issues/136756#issuecomment-917264024, but I delved right in without knowing that)

**Comment by Artturin** [comment] 2021-11-27 00:43
atleast you now know more about stdenv :slightly_smiling_face:

**Comment by wesleywright** [comment] 2021-12-10 18:38
How is the PR looking? I've been waiting on this for a couple of weeks to debug an intermittent crash I'm having with xfce4-sesion :)

**Closed** 2021-12-10 20:29 UTC
Labels: 0.kind: bug, 6.topic: stdenv
