### ISSUE TITLE
docker-1.13.0 man page is called "docker.1.gz.gz"

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#22861] opened 2017-02-16 11:23 UTC
The `docker.man` derivation in `master` has all man pages gzipped twice, which means that `man` won't find them:

~~~
$ man docker
/run/current-system/sw/bin/man: warning: /run/current-system/sw/share/man/man1/docker.1.gz.gz: ignoring bogus filename
No manual entry for docker
~~~~

Cc: @vdemeester

**Comment by dezgeg** [comment] 2017-02-16 12:19
Seems a dupe of #21777

**Comment by peti** [comment] 2017-02-16 12:34
@dezgeg, it might be .. the outcome here looks different from what I got in that bug report though.

**Comment by vcunat** [comment] 2017-02-16 22:22
Yes, it does seem to be another instance of that.

**Closed** 2017-02-22 09:44 UTC
Labels: 0.kind: bug, 2.status: duplicate
