### ISSUE TITLE
GNOME's Search Result for Settings app is broken

### ISSUE THREAD

**Issue by Ashvith10** [NixOS/nixpkgs#261679] opened 2023-10-17 18:00 UTC
### Describe the bug
GNOME Search Result is buggy for the settings app. When I try opening "Mouse and Touchpad" or "Display", nothing happens.

### Steps To Reproduce
1. Type in "Mouse and Touchpad" in GNOME's Search bar
2. Try opening that particular option
3. Nothing happens

### Expected behavior
The Settings app should have launched to the specific page

### Screenshots
Do notice the mouse load:

[Screencast from 2023-10-17 23-10-29.webm](https://github.com/NixOS/nixpkgs/assets/113123021/5cbdf69d-fa50-4ce1-9c43-725df15fcfba)

### Additional context
\-

### Notify maintainers
@davidak 
@bobby285271 
@jtojnar
@Artturin

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.57, NixOS, 23.11 (Tapir), 23.11pre534806.5e4c2ada4fcd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(ashvith): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jtojnar** [comment] 2023-10-17 19:45
Is there anything in the journal?

Mouse might be #253928 but I am not aware of any issue with Displays.

**Comment by Ashvith10** [comment] 2023-10-18 03:15
Looks like none of the entries in the "Setting" search result are working.

I am not sure if this fixed it, but I tried reordering the duplicated setting list, making sure to drag on entry before the other, and it was working for some time. But I am not able to replicate it - post probably, it was because the Settings app was already opened?

#253928 probably forgot to document the rest of the entries.

This is what I was able to find from `journalctl`:
```
Oct 18 08:33:43 lenovo-s540 .gnome-control-[3354]: GstPlay: 'playbin' element not found, please check your setup
Oct 18 08:33:43 lenovo-s540 systemd-coredump[3383]: Process 3354 (.gnome-control-) of user 1000 dumped core.
                                                    #20 0x00000000004d0680 cc_split_row_set_default_illustration_resource (.gnome-control-center-wrapped + 0xd0680)
                                                    #21 0x00000000004a1a04 setup_illustrations (.gnome-control-center-wrapped + 0xa1a04)
                                                    #26 0x000000000045e89c cc_panel_loader_load_by_name (.gnome-control-center-wrapped + 0x5e89c)
                                                    #27 0x0000000000462c0a set_active_panel_from_id.constprop.0 (.gnome-control-center-wrapped + 0x62c0a)
                                                    #32 0x0000000000460d56 row_activated_cb (.gnome-control-center-wrapped + 0x60d56)
                                                    #40 0x000000000046137a cc_panel_list_set_active_panel (.gnome-control-center-wrapped + 0x6137a)
                                                    #41 0x00000000004626c4 cc_window_constructed (.gnome-control-center-wrapped + 0x626c4)
                                                    #45 0x000000000046321e cc_window_new (.gnome-control-center-wrapped + 0x6321e)
                                                    #46 0x000000000045c604 cc_application_startup (.gnome-control-center-wrapped + 0x5c604)
                                                    #53 0x000000000045bcab main (.gnome-control-center-wrapped + 0x5bcab)
                                                    #56 0x000000000045bf65 _start (.gnome-control-center-wrapped + 0x5bf65)
```

**Comment by Ashvith10** [comment] 2023-10-18 03:16
Here's what I've tried:
- Mouse and Touchpad
- Display
- Bluetooth
- Region and Language
- Accessibility
- Keyboard
- About

None of these options will launch.

**Comment by schuelermine** [comment] 2023-10-18 04:37
Have you ever previously opened the Mouse and Touchpad section? Does opening Settings by itself work?

**Comment by Ashvith10** [comment] 2023-10-18 04:44
@schuelermine I'm adding pictures for reference.

Only the Settings app in the GNOME app menu works.
![image](https://github.com/NixOS/nixpkgs/assets/113123021/76ee6c20-30ad-4df3-9ceb-6f6253ca2c94)

The settings icon in the control panel also works.
![image](https://github.com/NixOS/nixpkgs/assets/113123021/53ab7905-cc4e-48f5-9ed3-d3ac466fccec)

None of the options below work (including Settings and all of it's suboptions).
![image](https://github.com/NixOS/nixpkgs/assets/113123021/853dd158-1c3c-44ed-9409-473962695f34)

**Comment by Ashvith10** [comment] 2023-10-18 04:51
@schuelermine "Mouse and Touchpad" works for me when I open the settings app via the first two methods. It also works when I try:
```console
nix run nixpkgs#gnome.gnome-control-center
```

And then choose the "Mouse and Touchpad" options. I'm on NixOS Unstable, btw.

**Comment by pearsche** [comment] 2023-11-24 17:53
it seems this was fixed on gnome 45? I can't reproduce. it just opens fine.

**Comment by Ashvith10** [comment] 2023-11-24 17:57
@pearsche Yes, can confirm. I'm on 23.11-beta, and this works fine now. Should I close this?

**Comment by bjornfor** [comment] 2023-11-24 19:55
FYI, I'm on NixOS 23.05 and can open "Mouse and touchpad" directly from GNOME Shell search, or by first opening Settings and then Ctrl+F and search (and open) from within the Settings app.

**Closed by bjornfor** 2023-11-24 19:55 UTC
Labels: 0.kind: bug

**Comment by jtojnar** [comment] 2023-11-24 20:40
The trace above looks like the mouse thing issue fixed by https://github.com/NixOS/nixpkgs/pull/262568. I think the crashes when trying other panels must have been just from the mouse panel before it could be switched to the new one. g-c-c will now reset the panel when it detects it crashed previously so that should not happen either.
