### ISSUE TITLE
GIMP: does not reuse already running GIMP instance

### ISSUE THREAD

**Issue by rkoe** [NixOS/nixpkgs#36341] opened 2018-03-05 13:02 UTC
## Issue description

When GIMP is already running and I open another image from the commandline, the image should be opened in the already running GIMP instance (except if I use --new-instance).

But this is not the case; instead, a new GIMP instance is opened.

### Steps to reproduce

$ gimp a
wait until GIMP has started
$ gimp b

Now, there are 2 GIMP instances / 2 GIMP windows instead of one.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.75, NixOS, 17.09.3037.883a4ebe7ee (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.12pre5788_e3013543`
 - channels(root): `"nixos-17.09.3037.883a4ebe7ee"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment] 2018-03-05 13:52
Weird, I am almost sure that it opened files in the existing instance previously.

**Comment by nixy** [comment] 2018-04-03 02:54
Is this a regression in the nixpkg for GIMP (that is, did it open separate instances before) or is this just expected behavior for GIMP?

Looking at GIMP on my system I suspect this is because it's launched with a wrapper.

```
$ cat $(which gimp)
#! /nix/store/jgw8hxx7wzkyhb2dr9hwsd9h2caaasdc-bash-4.4-p12/bin/bash -e
...
...
...
exec -a "$0" "/nix/store/2ldffql8sbq1ifbwdcp5nd6bmsm7pjrc-gimp-2.8.22/bin/.gimp-wrapped"  "${extraFlagsArray[@]}" "$@"
```

I'm not 100% on this, but I'm pretty sure with the way this is being `exec`ed this would always start a new process.

**Comment by JohnAZoidberg** [comment] 2019-12-04 17:32
It works for me on NixOS unstable (`nixos-20.03pre202088.e89b21504f3`).
Can you reproduce this?

**Comment by jtojnar** [comment] 2019-12-04 18:57
Wrapper should have nothing to do with this – new process would be started even without it.

The way this is usually implemented is that the new process will notice another instance is already running and pass its arguments to it via IPC. GApplication is common implementation of this, replacing the deprecated libunique, but GIMP predates it so it is probably not using that.

**Comment by jtojnar** [comment] 2020-06-01 23:51
Closing as irreproducible and without feedback. Please comment with more info if you still experience this issue.

**Closed by jtojnar** 2020-06-01 23:51 UTC
Labels: 0.kind: bug, 9.needs: reporter feedback
