### ISSUE TITLE
Radarr fails to handle Gzip encoded requests

### ISSUE THREAD

**Issue by janstenpickle** [NixOS/nixpkgs#167506] opened 2022-04-06 09:03 UTC
### Describe the bug

On Nixos, the current version of Radarr (`4.0.5.5981`) fails to accept or make HTTP requests due to a missing (I think) Dotnet dependency (`liblibSystem.IO.Compression.Native`).

Making requests without compression enabled does work, however search inside of Radarr doesn't as the Dotnet HTTP seems to also depend on Zlib.

### Steps To Reproduce
1. Set up Radarr with with `services.radar...` options
2. Ensure `services.radar.openFirewall` is set to `true`
3. Rebuild the system
4. Browse to `<hostname>:7878`
6. See error in systemd journal for `radarr.service`

### Expected behavior

Radarr should be able to respond to and make HTTP requests with zlib compression enabled.

### Screenshots

Technically not a screenshot, but a stacktrace

```
[v3.2.2.5080] System.IO.Compression.ZLibException: The underlying compression routine could not be loaded correctly.
 ---> System.DllNotFoundException: Unable to load shared library 'libSystem.IO.Compression.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSystem.IO.Compression.Native: cannot open shared object file: No such file or directory
   at Interop.zlib.DeflateInit2_(ZStream& stream, CompressionLevel level, CompressionMethod method, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
   at System.IO.Compression.ZLibNative.ZLibStreamHandle.DeflateInit2_(CompressionLevel level, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
   at System.IO.Compression.Deflater..ctor(CompressionLevel compressionLevel, Int32 windowBits)
   --- End of inner exception stack trace ---
   at System.IO.Compression.Deflater..ctor(CompressionLevel compressionLevel, Int32 windowBits)
   at System.IO.Compression.DeflateStream.InitializeDeflater(Stream stream, Boolean leaveOpen, Int32 windowBits, CompressionLevel compressionLevel)
   at System.IO.Compression.DeflateStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen, Int32 windowBits, Int64 uncompressedSize)
   at System.IO.Compression.GZipStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen)
   at Radarr.Http.Extensions.Pipelines.GzipCompressionPipeline.WriteGZipStream(Action`1 innerContent, Stream targetStream) in D:\a\1\s\src\Radarr.Http\Extensions\Pipelines\GZipPipeline.cs:line 73
   at Radarr.Http.Extensions.Pipelines.GzipCompressionPipeline.<>c__DisplayClass6_0.<CompressResponse>b__1(Stream responseStream) in D:\a\1\s\src\Radarr.Http\Extensions\Pipelines\GZipPipeline.cs:line 51
   at Nancy.Owin.NancyMiddleware.RequestComplete(NancyContext context, IDictionary`2 environment, Func`2 performPassThrough, Func`2 next)
   at Nancy.Owin.NancyMiddleware.<>c__DisplayClass2_1.<<UseNancy>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Owin.WebSocketAcceptAdapter.<>c__DisplayClass6_0.<<AdaptWebSockets>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Radarr.Host.Middleware.SignalRMiddleware.<Attach>b__7_0(HttpContext context, Func`1 next) in D:\a\1\s\src\NzbDrone.Host\WebHost\Middleware\SignalRMiddleware.cs:line 51
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Additional context
I tried both inside and outside of a Nix container, which yielded the same result.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.89, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(chris): `""`
 - channels(root): `"nixos-21.11.336824.ccb90fb9e11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by illiusdope** [comment] 2022-04-06 18:42
Came to report this.  It started after the zlib update for 21.11, however on the unstable channel it works again.  This suggests that some other library hasn't been updated for 21.11 (though I'm struggling to find it because both mono and radarr don't seem to have any recent updates in either branch).

**Comment by GoogleBot42** [comment] 2022-04-07 06:38
The same issue seems to affect prowlarr.  It might affect other *arr as well.

**Comment by janstenpickle** [comment] 2022-04-07 07:26
I doesn't seem to affect Sonarr, but that runs under [Mono](https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/sonarr/default.nix#L19=) instead of the [Dotnet](https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/radarr/default.nix#L34=) runtime.

**Comment by GoogleBot42** [comment] 2022-04-07 14:52
Looks like *arr services like to use the latest dotnet core versions.  Since they seem to only test with and use dotnet I think we should stick with that.  Converting the *arr services to use [dotnet-runtime](https://search.nixos.org/packages?channel=21.11&from=0&size=50&sort=relevance&type=packages&query=dotnet-runtime) should keep it up to date.

**Comment by GoogleBot42** [comment] 2022-04-07 23:50
@illiusdope radarr does not work for me in nixos-unstable.

**Comment by GoogleBot42** [comment] 2022-04-08 00:23
ok some progress I think. The following two seem to work correctly in nixos 21.11 (and probably unstable as well)

```
nix-shell -p prowlarr --run Prowlarr
nix-shell -p radarr --run Radarr
```

But when it's pure it fails with the same stack trace.

```
nix-shell --pure -p prowlarr --run Prowlarr
nix-shell --pure -p radarr --run Radarr
```

So it is probably a missing dependency.

**Comment by GoogleBot42** [comment] 2022-04-08 02:12
Not why it isn't already included somehow but adding zlib to LD_LIBRARY_PATH seems to fix it for me.  After someone else confirms it works for them, I'll open a PR.  I also set it to use latest `dotnet-runtime` instead of the 3.1 runtime since upstream seems to test on the latest.

```
  nixpkgs.overlays = [
    (final: prev: {
      radarr = prev.radarr.overrideAttrs (old: rec {
        installPhase = ''
          runHook preInstall
          mkdir -p $out/{bin,share/${old.pname}-${old.version}}
          cp -r * $out/share/${old.pname}-${old.version}/.
          makeWrapper "${final.dotnet-runtime}/bin/dotnet" $out/bin/Radarr \
            --add-flags "$out/share/${old.pname}-${old.version}/Radarr.dll" \
            --prefix LD_LIBRARY_PATH : ${lib.makeLibraryPath [
              final.curl final.sqlite final.libmediainfo final.mono final.openssl final.icu final.zlib ]}
          runHook postInstall
        '';
      });

      prowlarr = prev.prowlarr.overrideAttrs (old: {
        installPhase = ''
          runHook preInstall
          mkdir -p $out/{bin,share/${old.pname}-${old.version}}
          cp -r * $out/share/${old.pname}-${old.version}/.
          makeWrapper "${final.dotnet-runtime}/bin/dotnet" $out/bin/Prowlarr \
            --add-flags "$out/share/${old.pname}-${old.version}/Prowlarr.dll" \
            --prefix LD_LIBRARY_PATH : ${lib.makeLibraryPath [
              final.curl final.sqlite final.libmediainfo final.mono final.openssl final.icu final.zlib ]}
          runHook postInstall
        '';
      });
    })
  ];
```

**Comment by NULLx76** [comment] 2022-04-08 10:14
I can confirm that @GoogleBot42's fix works for me as well

**Comment by andir** [comment] 2022-04-08 13:49
FWIW I just dropped this in my configuration:
> systemd.services.prowlarr.environment.LD_LIBRARY_PATH="${lib.getLib pkgs.zlib}/lib"

Good enough until we have a fix in nixos.

**Comment by MatthiasBenaets** [comment] 2022-04-08 15:44
Thank you for the temporary fix @GoogleBot42.

For those who are waiting it out until a solution is merged, don't forget to stop radarr.serivce, otherwise stuff like bazarr will not fully function or exit out.

**Comment by janstenpickle** [comment] 2022-04-08 15:45
Confirmed that @GoogleBot42's fix works in a Nix container too. Thank you @GoogleBot42!

**Comment by GoogleBot42** [comment] 2022-04-08 19:53
PRs https://github.com/NixOS/nixpkgs/pull/167916 https://github.com/NixOS/nixpkgs/pull/167917

**Comment by GoogleBot42** [comment] 2022-05-11 01:18
the fix is now merged in master

**Comment by NULLx76** [comment] 2022-06-11 20:04
seems fixed, closing the issue

**Closed by NULLx76** 2022-06-11 20:04 UTC
Labels: 0.kind: bug
