### ISSUE TITLE
nautilus use incorrect file associations

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#34349] opened 2018-01-28 08:31 UTC
## Issue description
I installed nautilus via nix-env -iA nautilus, mostly because I don't like having such big software in my configuration.nix.
Nautilus doesn't seem to respect at all my mime type configuration and basically the last application I setup as default is used for all filetypes.
This has happened for as long as I remember (=months). I do have a $HOME/.config/mimeapps.list available. 
My window manager is i3 so I might miss some gnome services. I tried asking on #gnome to no avail.

### Steps to reproduce
1/ nix-env -iA nautilus
2/ start nautilus
3/ Right lick on a file to see what's the default associated program (there is a good chance filetype association would be wrong)
4/ fix the associated program. For instance for an html file I right click on it -> "Properties" -> "Open with" -> set firefox as default 
5/ then open a file which is not an html one, it will open with firefox 

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.13, NixOS, 18.03.git.a4f433c (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.2378.af7e47921c4"`
 - channels(teto): `"nixos-18.03pre121925.3eccd0b11d1"`
 - nixpkgs: `/home/teto/nixpkgs`

**Comment by jtojnar** [comment] 2018-01-28 13:35
File associations tend to be non-deterministic for some reason. What is the contents of your `mimeapps.list`? Try running `gio info filename | grep content-type` or `xdg-mime query filetype` to see what file type the file is recognized as.

**Comment by teto** [comment] 2018-01-28 14:40
my $XDG_CONFIG_HOME/mimeapps.list
```
[Default Applications]
video/x-matroska=mpv.desktop
video/mp4=mpv.desktop
text/csv=sublime_text.desktop
video/x-msvideo=mpv.desktop
application/x-matroska=mpv.desktop
text/x-csrc=gedit.desktop
text/x-chdr=sublime_text.desktop
text/html=firefox.desktop
x-scheme-handler/http=firefox.desktop
x-scheme-handler/https=firefox.desktop
x-scheme-handler/ftp=firefox.desktop
x-scheme-handler/chrome=firefox.desktop
application/x-extension-htm=firefox.desktop
application/x-extension-html=firefox.desktop
application/x-extension-shtml=firefox.desktop
application/xhtml+xml=firefox.desktop
application/x-extension-xhtml=firefox.desktop
application/x-extension-xht=firefox.desktop
application/pdf=zathura.desktop
image/png=sxiv.desktop
text/plain=sublime.desktop

[Added Associations]
video/x-matroska=vlc.desktop;mpv.desktop;
video/mp4=vlc.desktop;mpv.desktop;userapp-mpv-DXOVBY.desktop;
text/csv=sublime_text.desktop;
video/x-msvideo=mpv.desktop;
application/x-matroska=mpv.desktop;
text/x-csrc=gedit.desktop;
text/x-patch=sublime_text.desktop;
text/x-chdr=sublime_text.desktop;
application/binary=sublime_text.desktop;
text/x-rockspec=sublime_text.desktop;

```
but nautilus doesn't seem to follow that file. If I run $ xdg-open todo.png, it loads (correctly) sxiv (an image viewer). If I open the same file from nautilus, it opens sublime text (fun fact: sublime text can actually render images :/). 
Btw, I don't have the `gio` binary. Maybe that's the reson why natuilus acts so randomly ?

**Comment by jtojnar** [comment] 2018-01-28 15:01
`gio` is just part of `glib.dev` and it should not be needed (I think it should internally use the same glib functions as Nautilus). What type do you see in the properties of the file in Nautilus?

Also maybe `#nautilus` can be more helpful.

**Comment by teto** [comment] 2018-01-28 15:08
arf nautilus sees "Type text/plain" for an image os that's why it opens it
with sublime. I'll try to ask on #nautilus what's hte detection mechanism.

2018-01-29 0:01 GMT+09:00 Jan Tojnar <notifications@github.com>:

**Comment by dywedir** [comment] 2018-01-28 22:21
@teto do you have `shared_mime_info` installed?

**Comment by teto** [comment] 2018-01-29 02:06
@dywedir installing shared_mime_info seems to fix it ty. I leave the issue open as I am not sure what's the proper fix (make shared_mime_info a propagatedBuilInput of nautilus ?).

**Comment by jtojnar** [comment] 2018-01-29 02:32
This seems to be a duplicate of https://github.com/NixOS/nixpkgs/issues/12280. I think adding `shared_mime_info` to `XDG_DATA_DIRS` like we do for Evince (https://github.com/NixOS/nixpkgs/pull/14217) would be the most proper solution.

**Closed by jtojnar** 2018-01-29 02:32 UTC
