### ISSUE TITLE
logcheck service can't be built

### ISSUE THREAD

**Issue by r-raymond** [NixOS/nixpkgs#31738] opened 2017-11-16 12:01 UTC
## Issue description
enabling logcheck and rebuilding fails with

```
rm: cannot remove '/nix/store/hpb436ns0596slhmak5kr6qqscx1jpa3-logcheck-default-rules/logcheck.logfiles.d': Is a directory
builder for ‘/nix/store/q9j4wg379rm120b1iy2j7sq5sgv87zjc-logcheck-default-rules.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/0lb0k7nz6v6sj2vp8b0qq530lpiapbmg-logcheck-rules-dir.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/javg11sqs1ray7q4vd5hb84p1d1hfxzg-system-crontab.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/5xylxy6s949x9sj0g02a9d8lk5ysf5z0-crontabs.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/33gg6cr43wjv2qi8199nm03009917fkv-etc.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/54jsznh81gfwmwzdqa3vljkn19qlc2kf-nixos-system-desktop-17.09.2029.ab36c74390.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/54jsznh81gfwmwzdqa3vljkn19qlc2kf-nixos-system-desktop-17.09.2029.ab36c74390.drv’ failed
```

### Steps to reproduce
add 
```
services.logcheck.enable = true;
```
to `configuration.nix` then `nixos-rebuilt switch`

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.61, NixOS, 17.09.2029.ab36c74390 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2029.ab36c74390, unstable-17.09pre110213.01c3847b9c"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by phdoerfler** [comment] 2017-12-07 23:04
This looks like a duplicate of https://github.com/NixOS/nixpkgs/issues/29906 to me.

**Comment by r-raymond** [comment] 2017-12-08 08:18
Absolutely. Don't know how I missed that. Whoever wants to investigate this, the obvious fix of adding `-r` to https://github.com/NixOS/nixpkgs/blob/6dbe55ca689cacebc31fa8d38b8660a819e14d81/nixos/modules/services/logging/logcheck.nix#L11 "fixes" the problem. I didn't investigate if I want that folder though.

**Closed** 2017-12-08 08:19 UTC
Labels: 0.kind: bug, 6.topic: nixos
