### ISSUE TITLE
Package request: ZEN Browser

### ISSUE THREAD

**Issue by voyager6868** [NixOS/nixpkgs#355490] opened 2024-11-12 19:18 UTC
**Project description**

Customizeable Firefox based Browser

**Metadata**

* homepage URL: https://zen-browser.app/
* source URL: https://zen-browser.app/
* license: MPL2
* platforms: linux, darwin, windows

**Comment by Gliczy** [comment] 2024-11-12 19:29
Duplicate of https://github.com/NixOS/nixpkgs/issues/327982

**Closed by Gliczy** 2024-11-12 19:29 UTC
Labels: 0.kind: packaging request
