### ISSUE TITLE
riot-desktop starts and just displays "Riot is misconfigured"

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#64543] opened 2019-07-09 20:13 UTC
## Issue description

See screenshot:
![output](https://user-images.githubusercontent.com/327028/60919742-ca0aa480-a296-11e9-9af4-5d46e86ee546.png)

### Steps to reproduce

1. install `riot-desktop`.
2. try to start it

**Comment by ejpcmac** [comment] 2019-07-12 09:17
I can reproduce it. It seems that `config.json.sample` is not copied to `config.json` in `riot-web`. Not sure why it has worked before and not anymore though.

This seems to create the configuration only if it is not null. Maybe we could use the default configuration if none is provided.

https://github.com/NixOS/nixpkgs/blob/06cf681b6a4f601990169edb8b411b611b088843/pkgs/applications/networking/instant-messengers/riot/riot-web.nix#L19

**Comment by ejpcmac** [comment] 2019-07-12 11:30
As a workaround, I’ve put this in my personal overlay:

```nix
self: super:

{
  riot-web = super.riot-web.overrideAttrs (old : rec {
    installPhase = old.installPhase + ''
      cp $out/config.sample.json $out/config.json
    '';
}
```

This, however, overrides any user-defined configuration. Maybe the maintainers know for what the `conf` variable is used?

**Comment by colemickens** [comment] 2019-07-12 18:28
cc: @pacien any ideas? I looked to see if maybe riot-web used to ship a config.json, but as many as 6 months ago, it was just providing the sample config file.

Maybe ALL users of this package have always specified their own Riot config (to use with their own matrix servers?) but that seems somewhat unlikely...

**Comment by colemickens** [comment] 2019-07-12 19:29
I tried to patch this in nixpkgs proper and go ahead and start updating to the latest riot-desktop release (1.3.0 is at rc2 so I figured I'd get ready for 1.3.0's release)... but I have no idea what is going on with this package definition, in particular, the fact that it seems to ship its own copy? variant? of `yarn2nix`. And the docs in the riot-desktop.nix comments are insufficient to complete this update, so we may need to wait for @pacien to weigh in.

**Comment by pacien** [comment] 2019-07-12 19:40
Probably due to upstream change: https://github.com/vector-im/riot-web/pull/9496.

It seems that we now have to copy `config.sample.json` to `config.json` if there's no user-specified configuration in `riot-web.nix`. We should perhaps also accept a `conf` parameter in `riot-desktop.nix` as well and pass it to `riot-web`.

**Comment by pacien** [comment] 2019-07-13 17:23
Should be fixed by #64687.

**Closed** 2019-07-13 17:30 UTC

**Comment by commando-crypto** [comment] 2019-11-01 18:39
I'm having this issue currently on current master (20 minutes ago) 

![2019-11-01-182152_1052x686_scrot](https://user-images.githubusercontent.com/39086617/68047624-bf0cd180-fcd6-11e9-8183-089df62a33a8.png)


```

[nix-shell:~/repos/nixpkgs]$ git log | head
commit 895874d2145862249df3f78335f4dcf62ef01626
Author: Gabriel Ebner <gebner@gebner.org>
Date:   Fri Nov 1 17:59:14 2019 +0100

```

Steps to reproduce:



```
[cc@lappy386:~/repos/nixpkgs]$ nix-build -I ./ -A riot-web                                    these paths will be fetched (9.77 MiB download, 38.41 MiB unpacked):                                
  /nix/store/lk1j6w23p121r8nnr1clizmkp3vv513z-riot-web-1.5.0                                        copying path '/nix/store/lk1j6w23p121r8nnr1clizmkp3vv513z-riot-web-1.5.0' from 'https://cache.nixos.
org'...                                                                                             /nix/store/lk1j6w23p121r8nnr1clizmkp3vv513z-riot-web-1.5.0                                                                                                    
 [cc@lappy386:~/repos/nixpkgs]$ ls -la /nix/store/lk1j6w23p121r8nnr1clizmkp3vv513z-riot-web-1.5
.0/                                                                                                 bundles/            fonts/              index.html          mobile_guide/       themes/
welcome/                                                                                            config.json         i18n/               manifest.json       olm.35f4ef0.wasm    vector-icons/
welcome.html                                                                                        
config.sample.json  img/                media/              olm_legacy.js       version             

[cc@lappy386:~/repos/nixpkgs]$ ls -la /nix/store/lk1j6w23p121r8nnr1clizmkp3vv513z-riot-web-1.5
.0/index.html
-r--r--r-- 1 root root 4074 Jan  1  1970 /nix/store/lk1j6w23p121r8nnr1clizmkp3vv513z-riot-web-1.5.0/
index.html

```


![2019-11-01-182152_1052x686_scrot](https://user-images.githubusercontent.com/39086617/68047640-c9c76680-fcd6-11e9-9cef-7f85b2d09dcf.png)

**Comment by pacien** [comment] 2019-11-01 21:11
@commando-crypto Because of restrictions enforced by most web browsers, Riot web doesn't work when accessed with `file://...`. You need to either use the Electron wrapper (riot-desktop) or serve riot-web with a web server (`cd /nix/store/mw1z2jb1pckvwvwqjpdkwy60gsrwzq03-riot-web-1.5.0; python3 -m http.server 8080`).
