### ISSUE TITLE
ldc fails to build

### ISSUE THREAD

**Issue by mogorman** [NixOS/nixpkgs#78552] opened 2020-01-26 14:40 UTC
**Describe the bug**
I have tilix installed on my system one of the dependencies is ldc, which has dmd as a dependency. dmd fails to build 
**To Reproduce**
1. install tilix
2. ...
3. ...

**Expected behavior**
tilix installs 

**Screenshots**
```
 ... fail_compilation/testhtml2.html -O (-d -dw)
 ... fail_compilation/testhtml.html -O (-d -dw)
make[1]: Target 'run_all_tests' not remade because of errors.
make: *** [Makefile:413: start_all_tests] Error 2
make: Leaving directory '/build/ldc-1.16.0-src/tests/d2/dmd-testsuite'


The following tests passed:
        clean-dmd-testsuite-debug
        clean-dmd-testsuite

50% tests passed, 2 tests failed out of 4

Total Test time (real) = 488.95 sec

The following tests FAILED:
        1602 - dmd-testsuite-debug (Failed)
        1604 - dmd-testsuite (Failed)
Errors while running CTest
builder for '/nix/store/37vz9cxafw3y53b12fzax3ljlap1v2kl-ldc-1.16.0.drv' failed with exit code 8
cannot build derivation '/nix/store/98fdpza2rlx8aiprrygdip4q2z2mi20y-dmd-2.085.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/0md02a60v9xqx1hkmlc155xskm1vhva8-tilix-unstable-2019-08-03.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/kk8m73ss7lsdmg8jb9y0rqi8wckabzb7-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/wpa0knsrbv70jpqpvaynx6hfv9ws2zvm-nixos-system-ford-19.09.1957.57c35c63004.drv': 1 dependencies couldn't be built
error: build of '/nix/store/wpa0knsrbv70jpqpvaynx6hfv9ws2zvm-nixos-system-ford-19.09.1957.57c35c63004.drv' failed
```

**Additional context**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.8, NixOS, 19.09.1803.db5273ce2ab (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.1957.57c35c63004, home-manager-19.09, nixos-hardware, oldstable-19.03.173684.c8db7a8a16e, unstable-20.03pre210531.73a59af35bb"`
 - channels(mog): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`


```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment] 2020-01-26 20:20
cc @ThomasMader

**Comment by ThomasMader** [comment] 2020-01-27 08:46
The problem is that impure test which fails [2] since the beginning of the year because in the old version it's still 2019 and should be 2020.
This problem is already fixed in master [1].
@veprbl could you please port this change to stable.

[1] https://github.com/NixOS/nixpkgs/commit/4b102f0f0718d99cc80e331607f3d853e377f75a#diff-a9931c506e99f6acd6420fb8c119b55cR52

[2] ... compilable/ddocYear.d          -D -Dd../../../build/dmd-testsuite/compilable -o- -O ()
Test compilable/ddocYear.d failed.  The logged output:
Executing post-test script: tools/postscript.sh compilable/extra-files/ddocYear-postscript.sh compilable ddocYear ../../../build/dmd-testsuite/b6ddf7f353e9b18496a4bf179416aac6ff6518d274dc117d04f47f77cbf0b36
+ source compilable/extra-files/ddocYear-postscript.sh
+++ date +%Y
++ YEAR=2020
++ sed s/__YEAR__/2020/ compilable/extra-files/ddocYear.html
++ grep -v 'Generated by Ddoc from' ../../../build/dmd-testsuite/compilable/ddocYear.html
++ diff -pu --strip-trailing-cr ../../../build/dmd-testsuite/compilable/ddocYear.html.1 ../../../build/dmd-testsuite/compilable/ddocYear.html.2
--- ../../../build/dmd-testsuite/compilable/ddocYear.html.1     2020-01-17 11:55:41.272406410 +0000
+++ ../../../build/dmd-testsuite/compilable/ddocYear.html.2     2020-01-17 11:55:41.274406479 +0000
@@ -537,7 +537,7 @@
   <section class="section ddoc_sections">
   <div class="ddoc_summary">
   <p class="para">
-    2019
+    2020
   </p>
 </div>
 
/build/ldc-1.16.0-src/build/bin/ldmd2 -conf= -m64 -Icompilable -D -Dd../../../build/dmd-testsuite/compilable -o- -O  -od../../../build/dmd-testsuite/compilable -of../../../build/dmd-testsuite/compilable/ddocYear_0.o  -c compilable/ddocYear.d

**Closed** 2020-01-27 18:47 UTC
Labels: 0.kind: bug
