### ISSUE TITLE
unexpected interaction between python.withPackages and Python applications in nix-shell/nix develop

### ISSUE THREAD

**Issue by bcdarwin** [NixOS/nixpkgs#228362] opened 2023-04-26 17:48 UTC
The application Python leaks out onto $PATH:
```
$ nix-shell -p 'python310.withPackages (ps: with ps; [ pandas ])' which --pure
[nix-shell]$ which python3
/nix/store/xinwvh0r443zqys86hqs7sp5sbg5fzl5-python3-3.10.10-env/bin/python3
^D
$ nix-shell -p 'python310.withPackages (ps: with ps; [ pandas ])' snakemake which --pure
[nix-shell]$ which python3
/nix/store/syz2y6j53y5hpzbs7l0965zwxshi8iyl-python3-3.10.10/bin/python3
```

**Comment by teto** [comment] 2023-04-27 19:26
duplicate of https://github.com/NixOS/nixpkgs/issues/170887 I think

**Closed** 2023-04-27 20:01 UTC
Labels: 0.kind: bug
