### ISSUE TITLE
Build failure: docs (aarch64-darwin, sandbox issue)

### ISSUE THREAD

**Issue by n8henrie** [NixOS/nixpkgs#326380] opened 2024-07-11 20:46 UTC
I can't build the docs on `aarch64-darwin`. I searched but may have missed a previous discussion or open issue.

### Steps To Reproduce

`nix-build doc`

### Build log

https://gist.github.com/n8henrie/2eaf4776c6f0acfa8319fc6670f7d57d

### Additional context

Projects often encourage users to contribute to documentation, especially if they are less technically inclined or less familiar with a project but eager to pitch in.

If feasible, I think it would make sense to facilitate building the `nixpkgs` documentation on `darwin`, possibly opening up contributions from a whole new group of users.

### Notify maintainers

@NixOS/documentation-team 
@NixOS/darwin-maintainers 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.5.0, macOS 14.5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.6`
 - channels(n8henrie): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/h5m0sr1l5cwqga83zfdm7qbbrnm1iill-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by thecaralice** [comment] 2024-07-12 02:20
Cannot reproduce on 6794d064edc69918bb0fc0e0eda33ece324be17a (`master` at the time of writing this). Which nixpkgs revision are you on?

**Comment by n8henrie** [comment] 2024-07-12 02:53
Was on 212defe037698e18fc9521dfe451779a8979844c

Just reset to 6794d064edc69918bb0fc0e0eda33ece324be17a and I get the same error -- and this is my first time trying to build ./doc -- so I assume it's a problem on my side and will close.

**Comment by n8henrie** [comment] 2024-07-12 13:25
@thecaralice are you on aarch64-darwin?

**Comment by n8henrie** [comment] 2024-07-12 20:27
Think I might have sorted it out

[my zip error](https://gist.github.com/n8henrie/2eaf4776c6f0acfa8319fc6670f7d57d#file-gistfile0-txt-L219) (permission denied) kind of looks like a sandbox error, so sure enough `--option sandbox false` allows me to build the docs.

**Comment by paparodeo** [comment] 2024-07-13 03:48
i believe this was fixed in nix with https://github.com/NixOS/nix/pull/11031 and has been working its way back to nixpkgs with https://github.com/NixOS/nixpkgs/pull/326163 and the PRs it references

**Comment by emilazy** [comment] 2024-07-13 03:56
I don’t think so; 2.19.6 is one of the fixed versions, and on broken ones sandbox builds just won’t start at all. Not sure what is going on here, though, since `/tmp` is writeable in the sandbox, for better or worse.

**Closed** 2024-07-13 07:58 UTC
Labels: 6.topic: darwin, 0.kind: build failure

**Comment by n8henrie** [comment] 2024-07-13 12:51
@paparodeo thanks for the link! reckenrode had notified me about @emilazy's sandbox-relevant PR in matrix, but I had trouble finding it (I was searching nixos/nixpkgs instead of nixos/nix, which I should have known since I've spent a fair amount of time on the `pattern serialization length` sandbox error error in nixos/nix).

@emilazy thanks for your input -- any chance it's related to the `/tmp` vs `/private/tmp` discrepancy on macOS? I was recently working on https://github.com/NixOS/nixpkgs/issues/262131 and noted that `--remap-path-prefix "$PWD" .` failed whereas `--remap-path-prefix /private/"$PWD" .` worked.
