### ISSUE TITLE
Package request: Portmaster

### ISSUE THREAD

**Issue by Marin-Kitagawa** [NixOS/nixpkgs#327912] opened 2024-07-17 13:14 UTC
**Project description**
It is an application firewall

**Metadata**

* homepage URL: https://safing.io
* source URL: https://github.com/safing/portmaster
* license: GPLv3
* platforms: *nix, Windows

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-07-17 13:34
duplicate of #174194

**Closed by eclairevoyant** 2024-07-17 13:34 UTC
Labels: 0.kind: packaging request
