### ISSUE TITLE
Firefox 112.0+ crashes on Wayland with scaling

### ISSUE THREAD

**Issue by SebTM** [NixOS/nixpkgs#226539] opened 2023-04-16 22:49 UTC
### Describe the bug
Recurring but sudden crashes.

### Steps To Reproduce
Using it over multiple hours / days (without reboot) on unstable

### Expected behavior
No crashes or within reproducible actions 

### Screenshots
---

### Additional context
https://crash-stats.mozilla.org/report/index/d38cdbf0-bd3a-450f-9840-522800230416
https://crash-stats.mozilla.org/report/index/404af7aa-94ac-449d-8ec8-adff10230416
https://crash-stats.mozilla.org/report/index/be5b9392-9784-425f-886e-b8c730230414
https://crash-stats.mozilla.org/report/index/817396ba-c909-4873-b746-632d30230414

(four examples in the past three days)

### Notify maintainers

@lovesegfault
@hexa

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.11, NixOS, 23.05 (Stoat), 23.05.20230416.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/gs6fkh869l6nj9dws2dd8w217iq60337-source`
```

**Comment by sg-qwt** [comment] 2023-04-18 08:16
I noticed the same after recent upgrade. firefox crashed on me at least twice just in past two days on wayland.

.gnome-shell-wr[1640]: WL: error in client communication (pid 10140)
firefox.desktop[10140]: ExceptionHandler::GenerateDump cloned child 249298
firefox.desktop[10140]: ExceptionHandler::SendContinueSignalToChild sent continue signal to child
firefox.desktop[249298]: ExceptionHandler::WaitForContinueSignal waiting for continue signal...
firefox.desktop[211962]: Exiting due to channel error.
firefox.desktop[249176]: Exiting due to channel error.

**Comment by SebTM** [comment] 2023-04-18 13:33
Maybe @vcunat, @meinelt or @jopejoel can help us out, as they are more often work with the related code?

**Comment by Nehctarg** [comment] 2023-04-18 15:00
Isn't that merge request only relevant while using Gnome? Using river, I'm experiencing the same Firefox issue.

**Comment by vcunat** [comment] 2023-04-18 15:02
My reading is that Firefox breaks the protocol and gnome tolerated it until now.  I haven't looked at others.

**Comment by SebTM** [comment] 2023-04-18 15:21
Using sway (without xwayland enabled) - for reference

**Comment by Kiskae** [comment] 2023-04-18 21:49
Ran into this bug as well and did some debugging with `MOZ_LOG` before I thought to check the issue tracker.

The final lines of the log before a crash were:
> 2023-04-18 20:51:26.548518 UTC - [Parent 77578: Main Thread]: D/WidgetWayland moz_container_wayland_surface_create_locked [7fe696fd3800]
> 2023-04-18 20:51:26.548533 UTC - [Parent 77578: Main Thread]: D/WidgetWayland     gtk wl_surface 7fe6781c09c0 ID 82
> 2023-04-18 20:51:26.548543 UTC - [Parent 77578: Main Thread]: D/WidgetWayland     created frame callback ID 83
> 2023-04-18 20:51:26.548555 UTC - [Parent 77578: Main Thread]: D/WidgetWayland     created surface 7fe679cfcbf0 ID 116
> 2023-04-18 20:51:26.548561 UTC - [Parent 77578: Main Thread]: D/WidgetWayland moz_container_wayland_invalidate [7fe696fd3800]
> 2023-04-18 20:51:26.559782 UTC - [Parent 77578: Main Thread]: D/WidgetWayland moz_container_wayland_frame_callback_handler [7fe696fd3800] frame_callback_handler 7fe67b82e790 ready_to_draw 0 (set to true) initial_draw callback 2
> 2023-04-18 20:51:26.560097 UTC - [Parent 77578: Renderer]: D/WidgetWayland WindowSurfaceWaylandMB::Lock [7fe696fd3800] [0,0] -> [1173 x 128] rects 1
> 2023-04-18 20:51:26.560107 UTC - [Parent 77578: Renderer]: D/WidgetWayland   new window size [1173 x 128]
> 2023-04-18 20:51:26.560183 UTC - [Parent 77578: Renderer]: D/WidgetWayland WaylandBufferSHM Created [7fe679c8a510] WaylandDisplay [7fe6b6a44d80]
> 2023-04-18 20:51:26.560728 UTC - [Parent 77578: Renderer]: D/WidgetWayland WindowSurfaceWaylandMB::Commit [7fe696fd3800] damage rect [0, 0] -> [1173 x 128] Window [1173 x 128]
> 2023-04-18 20:51:26.560735 UTC - [Parent 77578: Renderer]: D/WidgetWayland WaylandBuffer::AttachAndCommit [7fe679c8a510] wl_surface 7fe679cfcbf0 ID 116 wl_buffer 7fe679c8a920 ID 83
> 2023-04-18 20:51:26.650421 UTC - [Parent 77578: Renderer]: D/WidgetWayland WindowSurfaceWaylandMB::Lock [7fe696fd3800] [0,0] -> [1173 x 128] rects 1
> 2023-04-18 20:51:26.650692 UTC - [Parent 77578: Renderer]: D/WidgetWayland WaylandBufferSHM Created [7fe67b82ed30] WaylandDisplay [7fe6b6a44d80]
> 2023-04-18 20:51:26.651141 UTC - [Parent 77578: Renderer]: D/WidgetWayland WindowSurfaceWaylandMB::Commit [7fe696fd3800] damage rect [0, 0] -> [1173 x 128] Window [1173 x 128]
> 2023-04-18 20:51:26.651156 UTC - [Parent 77578: Renderer]: D/WidgetWayland WaylandBuffer::AttachAndCommit [7fe67b82ed30] wl_surface 7fe679cfcbf0 ID 116 wl_buffer 7fe67b91f600 ID 117
> 2023-04-18 20:51:26.651159 UTC - [Parent 77578: Renderer]: D/WidgetWayland WindowSurfaceWaylandMB::Commit [7fe696fd3800] flush failed

Which backs up the crash report that it is trying to create a surface with an invalid resolution.

**Comment by SebTM** [comment] 2023-04-18 22:07
I came across something:
https://github.com/NixOS/nixpkgs/pull/226283#issuecomment-1509871420
https://bugzilla.mozilla.org/show_bug.cgi?id=1826583#a303442_580271

**Comment by Kiskae** [comment] 2023-04-18 22:17
The crashes looks similar because they are both wayland errors that end up in the crash handler, but the crashes in the original issue won't be fixed by those patches.

**Comment by Atemu** [comment] 2023-04-19 10:08
Since nobody managed to get his username right cc @mweinelt.

**Comment by SebTM** [comment] 2023-04-19 10:13
Sorry my bad though I copied it 🙈

**Comment by mweinelt** [comment] 2023-04-19 10:13
https://bugzilla.mozilla.org/show_bug.cgi?id=1828763

**Comment by vcunat** [comment] 2023-04-19 10:24
Certainly not all of people here.  sway already reported above.

**Comment by Kiskae** [comment] 2023-04-19 11:12
At the suggestion in the linked bugzilla report I've been running nightly and it hasn't crashed yet.

Looking through the linked regression it looks like this will be fixed in firefox 113:
> status-firefox113: --- → fixed
https://bugzilla.mozilla.org/show_bug.cgi?id=1803016#c19

**Comment by vcunat** [comment] 2023-04-19 11:18
@mweinelt is already looking at us applying that patch.  (Mozilla set 112 to wontfix.)

**Comment by mweinelt** [comment] 2023-04-19 11:27
Feel free to test #227045, if you have the resources to build firefox.

**Closed** 2023-04-19 13:12 UTC
Labels: 0.kind: bug, 2.status: wait-for-upstream
