### ISSUE TITLE
error: ati drivers are no longer supported by any kernel >=4.1

### ISSUE THREAD

**Issue by mudrii** [NixOS/nixpkgs#123972] opened 2021-05-22 05:36 UTC
**Describe the bug**
During system update with 'nixos-rebuild switch' getting the error `error: ati drivers are no longer supported by any kernel >=4.1`

**To Reproduce**
1. nix-channel --update
2. nixos-rebuild switch
```
nixos-rebuild switch
building Nix...
building the system configuration...
error: ati drivers are no longer supported by any kernel >=4.1
(use '--show-trace' to show detailed location information)
```

**Expected behavior**
System update

**Additional context**
No ati drivers installed or specified in configuration.nix Current systems is using Nvidia drivers configuration and no other changes for config was done prior to getting the error .

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
nix-shell -p nix-info --run "nix-info -m"                                            8.7m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.21, NixOS, 20.09.4159.a7064e23973 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(root): `"home-manager-20.09, nixos-20.09.4159.a7064e23973, unstable-21.05pre291103.d42cd445dde"`
 - channels(mudrii): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**show-trace**

```
nixos-rebuild switch --show-trace
building Nix...
building the system configuration...
error: ati drivers are no longer supported by any kernel >=4.1

       … while evaluating anonymous lambda

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/options.nix:110:23:

          109|     if defs == [] then abort "This case should never happen."
          110|     else foldl' (val: def:
             |                       ^
          111|       if def.value != val then

       … from call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/options.nix:110:10:

          109|     if defs == [] then abort "This case should never happen."
          110|     else foldl' (val: def:
             |          ^
          111|       if def.value != val then

       … while evaluating 'mergeEqualOption'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/options.nix:108:27:

          107|   /* "Merge" option definitions by checking that they all have the same value. */
          108|   mergeEqualOption = loc: defs:
             |                           ^
          109|     if defs == [] then abort "This case should never happen."

       … from call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:499:59:

          498|       if isDefined then
          499|         if all (def: type.check def.value) defsFinal then type.merge loc defsFinal
             |                                                           ^
          500|         else let firstInvalid = findFirst (def: ! type.check def.value) null defsFinal;

       … while evaluating the attribute 'mergedValue'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:497:5:

          496|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          497|     mergedValue =
             |     ^
          498|       if isDefined then

       … while evaluating 'apply'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/boot/kernel.nix:40:15:

           39|       type = types.unspecified // { merge = mergeEqualOption; };
           40|       apply = kernelPackages: kernelPackages.extend (self: super: {
             |               ^
           41|         kernel = super.kernel.override {

       … from call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:458:35:

          457|       # yield a value computed from the definitions
          458|       value = if opt ? apply then opt.apply res.mergedValue else res.mergedValue;
             |                                   ^
          459|

       … while evaluating the option `boot.kernelPackages':

       … while evaluating the attribute 'value'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:465:9:

          464|     in warnDeprecation opt //
          465|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          466|         inherit (res.defsFinal') highestPrio;

       … while evaluating anonymous lambda

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:98:72:

           97|           # For definitions that have an associated option
           98|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
           99|

       … from call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:279:20:

          278|               then recurse (path ++ [name]) value
          279|               else f (path ++ [name]) value;
             |                    ^
          280|         in mapAttrs g set;

       … while evaluating 'g'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:276:19:

          275|           g =
          276|             name: value:
             |                   ^
          277|             if isAttrs value && cond value

       … from call site

       … while evaluating the attribute 'boot.kernelPackages.kernel'

       … while evaluating the attribute 'content'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:633:14:

          632|     { _type = "if";
          633|       inherit condition content;
             |              ^
          634|     };

       … while evaluating 'dischargeProperties'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:549:25:

          548|   */
          549|   dischargeProperties = def:
             |                         ^
          550|     if def._type or "" == "merge" then

       … from call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:555:11:

          554|         if def.condition then
          555|           dischargeProperties def.content
             |           ^
          556|         else

       … while evaluating 'dischargeProperties'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:549:25:

          548|   */
          549|   dischargeProperties = def:
             |                         ^
          550|     if def._type or "" == "merge" then

       … from call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:478:137:

          477|         defs' = concatMap (m:
          478|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          479|         ) defs;

       … while evaluating definitions from `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/boot/kernel.nix':

       … while evaluating anonymous lambda

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:477:28:

          476|         # Process mkMerge and mkIf properties.
          477|         defs' = concatMap (m:
             |                            ^
          478|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … from call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:477:17:

          476|         # Process mkMerge and mkIf properties.
          477|         defs' = concatMap (m:
             |                 ^
          478|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating the attribute 'values'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:590:7:

          589|     in {
          590|       values = concatMap (def: if getPrio def == highestPrio then [(strip def)] else []) defs;
             |       ^
          591|       inherit highestPrio;

       … while evaluating the attribute 'values'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:491:9:

          490|       in {
          491|         values = defs''';
             |         ^
          492|         inherit (defs'') highestPrio;

       … while evaluating the attribute 'mergedValue'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:497:5:

          496|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          497|     mergedValue =
             |     ^
          498|       if isDefined then

       … while evaluating the option `assertions':

       … while evaluating the attribute 'value'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:465:9:

          464|     in warnDeprecation opt //
          465|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          466|         inherit (res.defsFinal') highestPrio;

       … while evaluating anonymous lambda

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:98:72:

           97|           # For definitions that have an associated option
           98|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
           99|

       … from call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:279:20:

          278|               then recurse (path ++ [name]) value
          279|               else f (path ++ [name]) value;
             |                    ^
          280|         in mapAttrs g set;

       … while evaluating 'g'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:276:19:

          275|           g =
          276|             name: value:
             |                   ^
          277|             if isAttrs value && cond value

       … from call site

       … while evaluating the attribute 'assertions'

       … while evaluating 'fold''

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:55:15:

           54|       len = length list;
           55|       fold' = n:
             |               ^
           56|         if n == len

       … from call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:59:8:

           58|         else op (elemAt list n) (fold' (n + 1));
           59|     in fold' 0;
             |        ^
           60|

       … while evaluating 'foldr'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:52:20:

           51|   */
           52|   foldr = op: nul: list:
             |                    ^
           53|     let

       … from call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/top-level.nix:128:12:

          127|   # Replace runtime dependencies
          128|   system = fold ({ oldDependency, newDependency }: drv:
             |            ^
          129|       pkgs.replaceDependency { inherit oldDependency newDependency drv; }

       … while evaluating the attribute 'config.system.build.toplevel'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/top-level.nix:293:5:

          292|
          293|     system.build.toplevel = system;
             |     ^
          294|
```

**Comment by totoroot** [comment] 2021-05-22 11:22
Same here. No ati drivers should be installed as my system has an NVIDIA GPU...
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.16, NixOS, 20.09.20210511.f34eb30 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(mathym): `"unstable-21.05pre291220.5dbd28d7541"`
 - nixpkgs: `/nix/store/7cq726an8m9x6mr5n0smnvkadlf93v88-source`
```

**Comment by samuelgrf** [comment] 2021-05-22 11:42
Fixed by https://github.com/NixOS/nixpkgs/pull/123904.
It may take some time for this to be built by Hydra and the channel to be updated, until then you can rebuild from nixpkgs master.

**Comment by jonringer** [comment] 2021-05-23 16:41
I apologize for the failure. Should have done more ripgrepping :(

**Comment by mudrii** [comment] 2021-05-24 07:03
any workaround is available? As I am unable to install any app due to the error?
@samuelgrf Please would you provide a timeline when we can expect the sync and issue fixed?

**Comment by samuelgrf** [comment] 2021-05-24 07:24
You can see the channel build status on https://status.nixos.org/ .
nixos-unstable is at rev `900115a4f7fd` right now which includes the fix, try updating your channels again.

**Comment by samuelgrf** [comment] 2021-05-24 07:27
FWIW this is the workaround I had in my configuration before https://github.com/NixOS/nixpkgs/pull/123904 , updating the channel should already fix the issue though:
```nix
nixpkgs.overlays = [
  (_: prev: {

    prev.linuxPackagesFor = kernel:
      (prev.linuxPackagesFor kernel).extend (_: _: { ati_drivers_x11 = null; });

  })
];
```

**Comment by mudrii** [comment] 2021-05-24 09:21
> FWIW this is the workaround I had in my configuration before #123904 , updating the channel should already fix the issue though:
> 
> ```nix
> nixpkgs.overlays = [
>   (_: prev: {
> 
>     prev.linuxPackagesFor = kernel:
>       (prev.linuxPackagesFor kernel).extend (_: _: { ati_drivers_x11 = null; });
> 
>   })
> ];
> ```

Workaround didn't work for me :(  and Just syncup from and nofix yet in the channel. will; wait for a wile

**Comment by samuelgrf** [comment] 2021-05-24 12:16
Just took a look at your config, the workaround isn't working because it isn't applied to the unstable channel that is imported here: https://github.com/mudrii/nixlenovodot/blob/master/configuration.nix#L9 .
It should look like this:
```nix
let
  unstable = import <unstable> {
    config.allowUnfree = true;
    overlays = [
      (_: prev: {

        prev.linuxPackagesFor = kernel:
          (prev.linuxPackagesFor kernel).extend (_: _: { ati_drivers_x11 = null; });

      })
    ];
  };
in
```

Alos can you post the output of `nix-shell -p nix-info --run "nix-info -m"` again (after updating yout channels), would be good to know what nixpkgs revision this happens on.

**Comment by mudrii** [comment] 2021-05-24 12:30
Thank you @samuelgrf I got confused on unstable part.
made the change but the same error 

```sh
head -18 /etc/nixos/configuration.nix
# Edit this configuration file to define what should be installed on
# your system. Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ inputs, config, options, pkgs, lib, callPackage, ... }:

let
  unstable = import <unstable> {
    config.allowUnfree = true;
     overlays = [
      (_: prev: {
        prev.linuxPackagesFor = kernel:
          (prev.linuxPackagesFor kernel).extend (_: _: { ati_drivers_x11 = null; });
      })
    ];
  };
in
______________________________________________________________________________________________
sudo nixos-rebuild switch
building Nix...
building the system configuration...
error: ati drivers are no longer supported by any kernel >=4.1
(use '--show-trace' to show detailed location information)
______________________________________________________________________________________________
nix-shell -p nix-info --run "nix-info -m"                                                         2409ms
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.21, NixOS, 20.09.4159.a7064e23973 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(root): `"home-manager-20.09, nixos-20.09.4169.ac60476ed94, unstable-21.05pre291486.900115a4f7f"`
 - channels(mudrii): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
______________________________________________________________________________________________
sudo cat /root/.nix-channels
https://github.com/rycee/home-manager/archive/release-20.09.tar.gz home-manager
https://nixos.org/channels/nixos-20.09 nixos
https://nixos.org/channels/nixos-unstable unstable
````

**Comment by samuelgrf** [comment] 2021-05-24 13:10
I made a mistake while searching through the git log, the fix is not included in the channel at the moment :(.

It would have been included in the latest Hydra evaluation but the tested build job has failed, see: https://hydra.nixos.org/job/nixos/trunk-combined/tested .
The channel will only update when the tested build job succeeds on a future Hydra evaluation.

As for the workaround, can you also add the overlay to [home-manager.nix#L6](https://github.com/mudrii/nixlenovodot/blob/db5ddb4ae88619c7d757645bbd1b9cbc67883b1e/home-manager.nix#L6) and any other `import <unstable>` that I might have missed.

**Comment by mudrii** [comment] 2021-05-24 13:27
Thx @samuelgrf   I tried all combinations and same results :(

**Comment by samuelgrf** [comment] 2021-05-24 13:43
You should be able to override the channel with a local nixpkgs checkout including the fix by doing `nixos-rebuild -I unstable=/path/to/nixpkgs`.

**Comment by mudrii** [comment] 2021-05-24 14:02
Yes I know but seems too much trouble :)  I decided to revert back to a stable kernel until the issue is fixed  and published into unstable

Appreciate your help

**Comment by rvolosatovs** [comment] 2021-05-25 20:09
I import some packages from unstable via overlays, but mostly using stable on my systems, where both are local git checkouts.
Surprisingly, applying both PRs to my local "stable" check out did not fix the issue, but simply removing `ati_drivers_x11` worked. I could not find any reference to `ati_drivers_x11` via ripgrep either.

**Comment by DieracDelta** [comment] 2021-05-25 20:53
I'm pulling off master and am still encountering this issue. Last commit ccb0f0080dbdb7155f45e107794f45a46b5a32ee.

**Comment by jonringer** [comment] 2021-05-26 05:13
Do you mind posting your configuration? If your modules and packages are being taken from master, this shouldn't occur

**Comment by baloo** [comment] 2021-05-26 20:45
I had a line like:
```
boot.kernelPackages = pkgs.linuxPackages_latest;
```

Defined twice in two files (my configuration is splitted in different imports) and was getting the same error.
If I pull either one off, then it builds fine.

**Comment by jonringer** [comment] 2021-05-26 22:24
I'm starting to suspect that something is eagerly evaluating the entire package set. Which would force the `throw` to be evaluated. Also doesn't help that there hasn't been another release since I put in the module fix https://status.nixos.org/

**Comment by baloo** [comment] 2021-05-26 22:56
(again this is running `nixpkgs.git@master` not sure this is impacted by the release)

**Comment by DieracDelta** [comment] 2021-05-26 23:10
@jonringer https://github.com/DieracDelta/flakes/blob/flakes/flake.nix with `nix build .#nixosConfigurations.desktop.config.system.build.toplevel -L`. I apologize since my config files are pretty messy. The TLDR is that I am setting an overlay with the master's version of nixpkgs that generates a `latest_kernel` here: https://github.com/DieracDelta/flakes/blob/flakes/flake.nix#L194. Then I am importing https://github.com/DieracDelta/flakes/blob/flakes/hosts/hw/desktop.nix. This imports https://github.com/DieracDelta/flakes/blob/flakes/hosts/hw/gpu_passthrough.nix and https://github.com/DieracDelta/flakes/blob/flakes/hosts/hw/shared.nix. None of these files seem particularly suspicious, and this was working on an earlier commit (before the ATI fix was pushed). I am not sure why it's failing.

**Comment by tomberek** [comment] 2021-05-27 01:00
I can confirm this occurs when boot.kernelPackages is set twice. In my case it was in my own configuration.nix and in a nixos-hardware module.

**Comment by hdhog** [comment] 2021-05-27 04:46
In my case `kernelPackages` set single for each machine config. 
if i set `unstable.linuxPackages_latest` i catching this issue. If i use kernel from  nixos-small or stable i have other problem this nvidia driver on my laptop.

**Comment by jonringer** [comment] 2021-05-27 18:09
There shouldn't be a need to pick kernel packages from master.... as the kernel versions should be gettting updated in lockstep

```
[11:06:57] jon@jon-desktop /home/jon/projects/nixpkgs (master)
$ nix eval .#linuxPackages_5_10.kernel.version
"5.10.37
[11:07:30] jon@jon-desktop /home/jon/projects/nixpkgs (release-20.09)
$ nix eval .#linuxPackages_5_10.kernel.version
"5.10.37"
```

If a broken nvidia package is forcing people to choose, then we should fix that module.

**Comment by DieracDelta** [comment] 2021-05-27 20:54
@jonringer the reason I was pulling kernel packages from master was because on stable the specific versions of binutils and elfutils conflict with each other. Specifically, I was running into this [issue](https://wiki.gentoo.org/wiki/Binutils_2.32_upgrade_notes/elfutils_0.175:_unable_to_initialize_decompress_status_for_section_.debug_info) when I was compiling the `vendor-reset` kernel module. Master's stdenv had a more recent version of binutils, fixing this issue. Maybe binutils will be bumped in the next release (I have not checked on this).

**Comment by TLATER** [comment] 2021-05-27 23:19
> If a broken nvidia package is forcing people to choose, then we should fix that module.

@jonringer - I broke that particular problem out into a separate issue; should have written it a long time ago but figured it'd be solved with 21.05 ;)

**Comment by jonringer** [comment] 2021-05-28 00:07
It should :), works on unstable

**Comment by miangraham** [comment] 2021-05-28 08:31
Just another "oh hey I'm fixed" voice chiming in to confirm that a single `boot.kernelPackages = unstable.linuxPackages` was breaking on this and moving to `stable.linuxPackages` got me rebuilding again.

**Comment by jnetod** [comment] 2021-05-29 15:53
> FWIW this is the workaround I had in my configuration before #123904 , updating the channel should already fix the issue though:
> 
> ```nix
> nixpkgs.overlays = [
>   (_: prev: {
> 
>     prev.linuxPackagesFor = kernel:
>       (prev.linuxPackagesFor kernel).extend (_: _: { ati_drivers_x11 = null; });
> 
>   })
> ];
> ```

It worked for me. Just had to change `prev.linuxPackagesFor = kernel:` for `linuxPackagesFor = kernel:`.

```nix
nixpkgs.overlays = [
  (_: prev: {
    linuxPackagesFor = kernel:
      (prev.linuxPackagesFor kernel).extend (_: _: { ati_drivers_x11 = null; });
  })
];
```

**Comment by alsvartr** [comment] 2021-05-31 00:24
Any chance this would be fixed?

**Comment by mudrii** [comment] 2021-05-31 04:55
@alsvartr  the fix  @jnetod proposed for @samuelgrf  works for me  https://github.com/mudrii/nixlenovodot/blob/master/configuration.nix#L9

**Comment by jonringer** [comment] 2021-05-31 22:46
Hmm, I have a suspicion that something is eagerly evaluating the package set, which causes the `throw` to be evaluated. This shouldn't be the case... but it might be prudent to just remove the entry altogether.

**Comment by baloo** [comment] 2021-06-01 01:50
I've been trying to understand what was evaluating it. The only guess I had was the `apply` in the `boot.kernelPackages` option, but I don't know how to verify that.

**Comment by mudrii** [comment] 2021-06-02 16:51
Post updating to 21.05 issue went away

**Comment by baloo** [comment] 2021-06-02 17:05
FWIW, issue is still present on `master`.

**Comment by applePrincess** [comment] 2021-06-03 09:41
I suspect that ati module is not properly removed given running tab completion, `ati_drivers_x11` appers.
```
[... /nixpkgs]$ nix eval .#linuxPackages_5_12.
Display all 106 possibilities? (y or n)
.#linuxPackages_5_12.__unfix__                 .#linuxPackages_5_12.evdi                      .#linuxPackages_5_12.mwprocapture              .#linuxPackages_5_12.r8125                     .#linuxPackages_5_12.tmon
.#linuxPackages_5_12.acpi_call                 .#linuxPackages_5_12.exfat-nofuse              .#linuxPackages_5_12.mxu11x0                   .#linuxPackages_5_12.r8168                     .#linuxPackages_5_12.tp_smapi
.#linuxPackages_5_12.akvcam                    .#linuxPackages_5_12.extend                    .#linuxPackages_5_12.ndiswrapper               .#linuxPackages_5_12.recurseForDerivations     .#linuxPackages_5_12.turbostat
.#linuxPackages_5_12.amdgpu-pro                .#linuxPackages_5_12.facetimehd                .#linuxPackages_5_12.netatop                   .#linuxPackages_5_12.rtl8192eu                 .#linuxPackages_5_12.tuxedo-keyboard
.#linuxPackages_5_12.anbox                     .#linuxPackages_5_12.fwts-efi-runtime          .#linuxPackages_5_12.nvidiaPackages            .#linuxPackages_5_12.rtl8723bs                 .#linuxPackages_5_12.usbip
.#linuxPackages_5_12.asus-wmi-sensors          .#linuxPackages_5_12.gcadapter-oc-kmod         .#linuxPackages_5_12.nvidia_x11                .#linuxPackages_5_12.rtl8812au                 .#linuxPackages_5_12.v4l2loopback
.#linuxPackages_5_12.ati_drivers_x11           .#linuxPackages_5_12.hid-nintendo              .#linuxPackages_5_12.nvidia_x11_beta           .#linuxPackages_5_12.rtl8814au                 .#linuxPackages_5_12.v86d
.#linuxPackages_5_12.batman_adv                .#linuxPackages_5_12.hyperv-daemons            .#linuxPackages_5_12.nvidia_x11_legacy340      .#linuxPackages_5_12.rtl8821au                 .#linuxPackages_5_12.vendor-reset
.#linuxPackages_5_12.bbswitch                  .#linuxPackages_5_12.intel-speed-select        .#linuxPackages_5_12.nvidia_x11_legacy390      .#linuxPackages_5_12.rtl8821ce                 .#linuxPackages_5_12.vhba
.#linuxPackages_5_12.bcc                       .#linuxPackages_5_12.isHardened                .#linuxPackages_5_12.nvidia_x11_vulkan_beta    .#linuxPackages_5_12.rtl8821cu                 .#linuxPackages_5_12.virtualbox
.#linuxPackages_5_12.bpftrace                  .#linuxPackages_5_12.isLibre                   .#linuxPackages_5_12.nvidiabl                  .#linuxPackages_5_12.rtl88x2bu                 .#linuxPackages_5_12.virtualboxGuestAdditions
.#linuxPackages_5_12.broadcom_sta              .#linuxPackages_5_12.isZen                     .#linuxPackages_5_12.oci-seccomp-bpf-hook      .#linuxPackages_5_12.rtl88xxau-aircrack        .#linuxPackages_5_12.wireguard
.#linuxPackages_5_12.callPackage               .#linuxPackages_5_12.isgx                      .#linuxPackages_5_12.odp-dpdk                  .#linuxPackages_5_12.rtlwifi_new               .#linuxPackages_5_12.x86_energy_perf_policy
.#linuxPackages_5_12.can-isotp                 .#linuxPackages_5_12.it87                      .#linuxPackages_5_12.openafs                   .#linuxPackages_5_12.rtw88                     .#linuxPackages_5_12.xpadneo
.#linuxPackages_5_12.chipsec                   .#linuxPackages_5_12.ixgbevf                   .#linuxPackages_5_12.openafs_1_8               .#linuxPackages_5_12.sch_cake                  .#linuxPackages_5_12.zenpower
.#linuxPackages_5_12.cpupower                  .#linuxPackages_5_12.jool                      .#linuxPackages_5_12.openafs_1_9               .#linuxPackages_5_12.stdenv                    .#linuxPackages_5_12.zfs
.#linuxPackages_5_12.cryptodev                 .#linuxPackages_5_12.kernel                    .#linuxPackages_5_12.openrazer                 .#linuxPackages_5_12.sysdig                    .#linuxPackages_5_12.zfsStable
.#linuxPackages_5_12.ddcci-driver              .#linuxPackages_5_12.kernelAtLeast             .#linuxPackages_5_12.perf                      .#linuxPackages_5_12.system76                  .#linuxPackages_5_12.zfsUnstable
.#linuxPackages_5_12.digimend                  .#linuxPackages_5_12.kernelOlder               .#linuxPackages_5_12.phc-intel                 .#linuxPackages_5_12.system76-acpi             
.#linuxPackages_5_12.dpdk                      .#linuxPackages_5_12.lttng-modules             .#linuxPackages_5_12.pktgen                    .#linuxPackages_5_12.system76-io               
.#linuxPackages_5_12.e1000e                    .#linuxPackages_5_12.mba6x_bl                  .#linuxPackages_5_12.ply                       .#linuxPackages_5_12.systemtap                 
.#linuxPackages_5_12.ena                       .#linuxPackages_5_12.mbp2018-bridge-drv        .#linuxPackages_5_12.prl-tools                 .#linuxPackages_5_12.tbs                       
```

Sure enough it fails to evaluate.
```
[... /nixpkgs]$ nix eval .#linuxPackages_5_12.ati_drivers_x11 
error: ati drivers are no longer supported by any kernel >=4.1
```

Even though `grep "./ati.nix" nixos/modules/module-list.nix` returns nothing.

Nixpkgs git commit ID:  `3cf17240f014282a1f40bc27e5fc7b21868f517a`

**Closed** 2021-06-04 05:22 UTC
Labels: 0.kind: bug, 6.topic: hardware
