### ISSUE TITLE
nix search doesn't give any results

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#70054] opened 2019-09-30 12:03 UTC
**Describe the bug**
`nix search` doesn't give any results even when called with the `-u` flag

**To Reproduce**
```
nix-channel --list                                                                
nixos https://nixos.org/channels/nixos-unstable
 nix-channel --update                                                              
unpacking channels...
nix search -u gcc                                                                  
error: no results for the given search term(s)!
```

**Expected behavior**
`nix search` gives a list of packages

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.17, NixOS, 20.03pre194293.2436c27541b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20190922_382aa05`
 - channels(root): `"nixos-20.03pre194293.2436c27541b"`
 - channels(paki): `"nixos-20.03pre194293.2436c27541b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - nix
# a list of nixos modules affected by the problem
module:
```

**Comment by jonringer** [comment] 2019-09-30 13:50
do you mind doing `sudo nix-channel --list`?

**Comment by worldofpeace** [comment] 2019-09-30 15:26
IIRC `nix search -u` updates just updates the cache. It doesn't perform a nix search after updating the cache with it.

**Comment by jonringer** [comment] 2019-09-30 15:34
that's not the behavior I have:
```
$ nix search -u gcc
* nixpkgs.distccMasquerade (distcc-masq-gcc)

* nixpkgs.gcc (gcc-wrapper)
  GNU Compiler Collection, version 8.3.0 (wrapper script)
...
```

**Comment by dermetfan** [comment] 2019-10-16 23:23
In my case this was caused by a faulty overlay. Once I removed that I was able to run `nix search -u` with success.

**Comment by jonringer** [comment] 2019-10-17 00:33
closing issue as it seems to have been resolved :)

**Closed by jonringer** 2019-10-17 00:33 UTC
Labels: 0.kind: bug
