### ISSUE TITLE
Package Request: Cockpit

### ISSUE THREAD

**Issue by j0hax** [NixOS/nixpkgs#88823] opened 2020-05-24 22:19 UTC
**Project description**
_Cockpit makes GNU/Linux discoverable. See your server in a web browser and perform system tasks with a mouse. It’s easy to start containers, administer storage, configure networks, and inspect logs._

**Metadata**

* homepage URL: https://cockpit-project.org/
* source URL: https://github.com/cockpit-project/cockpit
* license: LGPL v2.1+
* platforms: linux

**Comment by stuartpb** [comment] 2020-06-09 22:36
duplicate of #38161

**Comment by aanderse** [comment] 2020-06-09 22:56
We'll close this one and track the request in the other issue then.

**Closed by aanderse** 2020-06-09 22:56 UTC
Labels: 0.kind: packaging request
