### ISSUE TITLE
libeatmydata binary does not work

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#8665] opened 2015-07-06 14:31 UTC
Steps to reproduce, with a fresh nixpkgs repo:

    ❯ nix-env -f nixpkgs -iA pkgs.libeatmydata                                                                           ~
    replacing old ‘libeatmydata-82’
    installing ‘libeatmydata-82’
    building path(s) ‘/nix/store/3yad1r4aim4bnzq4778djpsfa4z4yidv-user-environment’
    created 1621 symlinks in user environment
    ❯ eatmydata anycommand                                                                                                  ~
    eatmydata error: unable to find 'eatmydata' in PATH

I'm not sure if the specific error is indicating some mis-setup of my PATH, but I don't know how to test that either.

**Comment by srhb** [comment] 2015-07-06 14:54
Apparently not reproducible by the kind folks on IRC. Must be my shell setup.

**Comment by lihop** [comment] 2015-07-06 15:00
On IRC, I said that I couldn't reproduce this, but I wasn't paying enough attention.
I get this error too.

**Comment by pSub** [comment] 2015-07-06 15:33
I can reproduce this error as well. I am really sure whats going on. Adding eatmydata's bin directory to PATH seems to work, but I am not sure why it is attempting to call itself in the first place.

@srhb Can you try to add it to PATH like

```PATH=/nix/store/*-libeatmydata-*/bin:$PATH eatmydata echo```

and test if this does the correct thing?

**Comment by srhb** [comment] 2015-07-06 15:42
Yes, this:

    ❯ PATH=/nix/store/x26ch4jk4zwwxnl7hrb13fxsrf7mw222-libeatmydata-82/bin:$PATH eatmydata uname
    Linux

works correctly.

**Comment by pSub** [comment] 2015-07-06 15:49
I have pushed a fix to master. It seems hacky to me, so it would make sense to investigate whether that fix is really adequate.

**Comment by srhb** [comment] 2015-07-10 21:02
Your fix Works For Me^(tm), so perhaps we should consider this closed for now?

**Comment by pSub** [comment] 2015-07-10 21:05
Yes, I think this can be closed. If there are problems with this fix in the future we just open a new ticket.

**Closed by pSub** 2015-07-10 21:05 UTC
