### ISSUE TITLE
Incorrect app icon used after app is installed on GNOME

### ISSUE THREAD

**Issue by ram-on** [NixOS/nixpkgs#328433] opened 2024-07-19 12:57 UTC
### Describe the bug
After a GUI application is installed via configuration.nix, GNOME uses an incorrect icon for the application -- in fact it uses the default place holder icon, refer to the below:

![image](https://github.com/user-attachments/assets/a78b11b9-feba-45da-b13f-fb088938690d)

### Steps To Reproduce
1. Add a GUI application to `configuration.nix` while running GNOME and save file.
2. Execute `sudo nixos-rebuild switch`
3. Press `WIN` key and search the application.  If the app is launch, the default place holder icon will be displayed in the dock/dash as well.

### Expected behavior
The correct icon should be used.

### Screenshots

Incorrect icon used within dock/dash:

![image](https://github.com/user-attachments/assets/20622125-8c47-458b-9ce7-c3bee9276102)

Incorrect icon used within the apps menu:
![image](https://github.com/user-attachments/assets/d7312b0d-b865-417e-86c7-81924a0961d2)

### Additional context

The correct icons will be loaded once user log out of GNOME and logs back in.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.39, NixOS, 24.05 (Uakari), 24.05.2933.c716603a63ac`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"home-manager-24.05.tar.gz, nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-07-19 16:32
duplicate of #12757

**Closed by eclairevoyant** 2024-07-19 16:32 UTC
Labels: 0.kind: bug, 6.topic: GNOME
