### ISSUE TITLE
CLASSPATH not set

### ISSUE THREAD

**Issue by kalhauge** [NixOS/nixpkgs#9847] opened 2015-09-13 23:11 UTC
When installing java libraries with nix, they do not appear in the CLASSPATH, when installed in $out/shared/java/. Even though it should, given the documentation. I'm using jdk8. 

Simple example:

``` bash
$ tree
.
├── default.nix
├── libtest
│   └── Test.java
└── test
    └── Main.java
``` 

I have listed the files below. Everything compiles fine if I first build libtest using `nix-build -A libtest` and then add the result folde as a class path:

CLASSPATH=../result/share/java/libtest.jar javac Main.java

But it does not work if I run `nix-build -A test`.
```
these derivations will be built:
  /nix/store/nh4d1yr2g3pcrn39az4fqp56w7drkjzn-test.drv
building path(s) ‘/nix/store/lkygy0zi7l2fa9djj1i35nrm4wnqdiac-test’
unpacking sources
unpacking source archive /nix/store/py67xcr8pg4pf1a2ca1ghn056wa9jbkv-test
source root is test
patching sources
configuring
no configure script, doing nothing
building
Main.java:1: error: package libtest does not exist
import libtest.Test;
              ^
Main.java:6: error: cannot find symbol
        Test.hello();
        ^
  symbol:   variable Test
  location: class Main
2 errors
builder for ‘/nix/store/nh4d1yr2g3pcrn39az4fqp56w7drkjzn-test.drv’ failed with exit code 1
error: build of ‘/nix/store/nh4d1yr2g3pcrn39az4fqp56w7drkjzn-test.drv’ failed
```

Which is not strange given, that the classpath is empty.
```
> nix-shell -A test
> echo $CLASSPATH

```

### default.nix
``` nix
let pkgs = import <nixpkgs> {};
in 
{stdenv ? pkgs.stdenv, jdk ? pkgs.jdk8}:
rec { 
  libtest = stdenv.mkDerivation { 
    name = "libtest";
    src = ./.;
    buildInputs = [ jdk ];
    buildPhase = '' javac libtest/Test.java '';
    installPhase = ''
      mkdir -p $out/share/java
      jar cf $out/share/java/libtest.jar libtest/Test.class
    '';
  };
  test = stdenv.mkDerivation { 
    name = "test";
    src = ./test;
    buildInputs = [ jdk libtest ];
    buildPhase = "javac Main.java";
    installPhase = ''
      mkdir -p $out/share/java
      jar cf $out/share/java/test.jar Main.class
    '';
  };
}
```
### Test.java
``` java
package libtest;
public class Test {
    public static void hello () {
        System.out.println("Hello, World");
    }
}
```
### Main.java
``` java
import libtest.Test;

public class Main { 

    public static void main (String[] args) { 
        Test.hello();
    }
}
```

**Comment by vbgl** [comment] 2015-09-19 17:13
Cannot reproduce (with current `nixpkgs-unstable`, on fedora linux x86_64). When I try to do what you describe, the `CLASSPATH` variable is properly set and `test` builds correctly.

**Comment by kalhauge** [comment] 2015-09-20 17:47
I have tried to update the channel to the newest version, but it still doesn't work. I have put the code in a repository, so that it is easier to reproduce. I'm using nixos.

https://github.com/kalhauge/classpath-test

**Comment by edolstra** [comment] 2015-09-21 08:25
This was broken in our OpenJDK 8 package. It's fixed in b0fd35e17482d72772b245cb779bffcc198d2c4e.

**Closed by edolstra** 2015-09-21 08:25 UTC

**Comment by kalhauge** [comment] 2015-09-21 18:04
Is this changed already active at `nixpkgs-unstable`? If so it does not work.

**Comment by kalhauge** [comment] 2015-09-21 18:56
Using the lastest version form github-master. I can confirm that it has indeed been fixed, but not moved to nixpkgs-unstable jet.

**Comment by edolstra** [comment] 2015-09-22 09:13
It should be in nixpkgs-unstable now.

**Comment by Isomorph70** [comment] 2024-11-21 09:56
I am having the same problem.  Now many years later.  
[Discourse link](https://discourse.nixos.org/t/nlp-natural-language-processing-service/55749)

I added  buildInputs = [ jdk ];, but it did not help.
