### ISSUE TITLE
utop does not work with OCaml 4.04 (ocamlPackages_latest)

### ISSUE THREAD

**Issue by Zimmi48** [NixOS/nixpkgs#25499] opened 2017-05-04 13:37 UTC
## Issue description

```
$ nix-shell -I nixpkgs=. -p ocamlPackages_latest.utop --run utop
/nix/store/v1z8h3b9wa9z411bza3i6mlgvnj4kdsr-utop-1.19.3/bin/utop not found or is not a bytecode executable file
```

This is exactly the same error I reported for camlp5 here #25367 and fixed in #25442 by adding:

```
  dontStrip = true;
```

to the derivation.

I thought the same fix would fix the problem for utop as well since:

```
$ ls -l /nix/store/v1z8h3b9wa9z411bza3i6mlgvnj4kdsr-utop-1.19.3/bin/utop
-r-xr-xr-x 1 root root 975  1 janv.  1970 /nix/store/v1z8h3b9wa9z411bza3i6mlgvnj4kdsr-utop-1.19.3/bin/utop
```

we clearly see that the file has been improperly shrinked, but when I tested this it seemed that it wouldn't change anything (as if the attribute was not taken into account).

## Technical details

```
$ nixos-version 
17.03.1098.a162c6c828 (Gorilla)
```

cc the maintainer of utop @FlorentBecker (BTW you appear as @gal_bolle in the maintainer list, and this clearly isn't you GitHub handle anymore)
cc @vbgl @vcunat

**Comment by vbgl** [comment] 2017-05-05 16:53
I think this is a duplicate of #24496.

See #24524 and #25122 for the fixes.

**Comment by Zimmi48** [comment] 2017-05-05 16:54
Right sorry for the noise. I don't know why I missed this.

**Comment by Zimmi48** [comment] 2017-05-05 17:01
@vbgl Actually, it seems that these fixes are in nixpkgs-unstable but not in nixos-17.03. Could you cherry-pick them?

**Comment by Zimmi48** [comment] 2017-05-10 13:06
Opening again as the fix to utop has only been committed in master, which means that `ocamlPackages_latest.utop` is still broken in NixOS 17.03.

**Closed** 2017-06-22 11:37 UTC
