### ISSUE TITLE
nixpkgs-built packages having issues running on fontconfig 2.13 distros

### ISSUE THREAD

**Issue by clojurians-org** [NixOS/nixpkgs#82983] opened 2020-03-20 07:38 UTC
## Issue description

chromium can't input chinese

### Steps to reproduce
```
[larluo@larluo ~]$ nix-env -f '<nixpkgs>' -iA chromium
installing 'chromium-80.0.3987.132'

[larluo@larluo ~]$ chromium
Gtk-Message: 15:33:46.428: Failed to load module "pk-gtk-module"
Gtk-Message: 15:33:46.428: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:33:46.429: Failed to load module "pk-gtk-module"
Gtk-Message: 15:33:46.429: Failed to load module "canberra-gtk-module"
[11330:11330:0320/153346.481271:ERROR:gl_surface_glx.cc(89)] glXGetFBConfigs failed.
[11330:11330:0320/153346.481313:ERROR:gl_surface_glx.cc(129)] Failed to get GLXConfig
[11330:11330:0320/153346.481322:ERROR:gl_surface_glx.cc(478)] CreateDummyWindow(gfx::GetXDisplay()) failed
[11330:11330:0320/153346.481328:ERROR:gl_initializer_x11.cc(148)] GLSurfaceGLX::InitializeOneOff failed.
[11330:11330:0320/153346.482794:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[11355:11355:0320/153346.528639:ERROR:gpu_channel_manager.cc(459)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
Fontconfig warning: "/etc/fonts/fonts.conf", line 5: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/fonts.conf", line 6: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/fonts.conf", line 9: unknown element "description"
Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf

```

## Technical details
```
[larluo@larluo ~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.0-147.el8.x86_64, CentOS Linux, 8 (Core)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(larluo): `"home-manager, nixpkgs-20.03beta591.99a3d7a86fc"`
 - nixpkgs: `/home/larluo/.nix-defexpr/channels/nixpkgs`
```

**Comment by mawis** [comment] 2020-03-20 09:09
What IME are you using?

Basically its not the browser/application that handles the input of Chinese characters but the IME (input method editor) you are using.

The IME is configured with `i18n.inputMethod` in `/etc/nixos/configuration.nix`. How is I18N configured in your `configuration.nix`?

**Comment by mawis** [comment] 2020-03-20 09:12
BTW: What's the connection to “centos8”?

**Comment by mawis** [comment] 2020-03-20 09:22
I did check  chromium on channel `nixos-20.03beta687.16dd1df0817` and Chinese input worked for me with these I18N settings:

```
  i18n = {                                                                       
    defaultLocale = "zh_TW.UTF-8";                                               
    inputMethod = {                                                              
      enabled = "fcitx";                                                         
      fcitx.engines = with pkgs.fcitx-engines; [ libpinyin rime ];               
    };                                                                           
  };
```

Note: `fcitx-configtool` or some other tool to configure fcitx has to be run by the user to set up fcitx after installing it with the configuration above.

**Comment by clojurians-org** [comment] 2020-03-20 10:27
thanks, i use the ibus input method on centos linux (not nixos).
i want to run package manage on all linux platform by nixpkgs. 
the yum installed chrome can type chinese normally.

thanks for your information you offer, i'll dig it more.

**Comment by mawis** [comment] 2020-03-23 09:54
Oh sorry, I completely forgot, that the packages can be used outside of NixOS as well.
In that case I have no experience with this setup.

**Comment by ShamrockLee** [comment] 2020-06-18 09:33
The same error comes to `pkgs.eclipses.eclipse-java` on Debian Testing (Bullseye).
Unable to use input method Dvorak and Chewing in `fcitx` installed on Debian.
#### Terminal output when running:
```bash
shamrock@debian64-201909:~$ . ~/.nix-profile/etc/profile.d/nix.sh 
shamrock@debian64-201909:~$ eclipse

(process:5145): Gtk-WARNING **: 03:02:56.130: Locale not supported by C library.
	Using the fallback 'C' locale.

(process:5163): Gtk-WARNING **: 03:02:56.618: Locale not supported by C library.
	Using the fallback 'C' locale.
Fontconfig warning: "/etc/fonts/fonts.conf", line 5: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/fonts.conf", line 6: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/fonts.conf", line 9: unknown element "description"
Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
org.eclipse.m2e.logback.configuration: Logback config file: /media/shamrock/Thirdspace/shamrock-shared/targets/Projects/ShamrockLee/eclipse-workspace/.metadata/.plugins/org.eclipse.m2e.logback.configuration/logback.1.15.0.20191217-1149.xml
org.eclipse.m2e.logback.configuration: Initializing logback

(Eclipse:5163): Gtk-CRITICAL **: 03:05:41.183: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(Eclipse:5163): Gtk-CRITICAL **: 03:05:43.405: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
```
`eclipse-java` works well (without these problems) on NixOS.

**Comment by flokli** [comment] 2020-07-11 10:58
We'd need to bump the nixpkgs fontconfig to 2.13 to fix these problems.

**Comment by flokli** [comment] 2020-07-11 14:20
There's a PR to bump fontconfig at https://github.com/NixOS/nixpkgs/pull/73795.

**Comment by StephenWithPH** [comment] 2020-07-17 19:11
#73795 was merged to `staging`, but it hasn't yet made it into `staging-next`.

https://discourse.nixos.org/t/release-process-staging-branches/2799/2 says:

>Every once in a while, the current staging gets forked off into staging-next. The purpose of staging-next is to let the current rebuild finish, detect regressions, stabilize. staging-next is then merged into master.

https://github.com/NixOS/rfcs/blob/531f9807053a0fb5248e5d926be620bf1680f1b3/rfcs/0026-staging-workflow.md doesn't give further details regarding the _frequency_ of this event.

https://hydra.nixos.org/jobset/nixpkgs/staging#tabs-evaluations seems like nothing has happened since June on `staging`. :man_shrugging:

**Comment by jtojnar** [comment] 2020-07-17 19:16
Last iteration of was just merged [yesterday](https://github.com/NixOS/nixpkgs/pull/91090#issuecomment-659298175), so next one will be opened soon. The `staging` branch is only used for accumulation so hydra should not build it, the checks run on https://hydra.nixos.org/jobset/nixpkgs/staging-next.

**Comment by vcunat** [comment] 2020-07-19 10:49
Frequency is like... whenever someone does it (fixes big regression etc.) and the build farm gets enough binaries :shrug:  (Doesn't seem worth documenting.)

**Comment by jtojnar** [comment] 2020-11-10 10:47
We now use fontconfig 2.14 (pre-release), and hopefully soon we will switch to master.

**Closed by jtojnar** 2020-11-10 10:47 UTC
Labels: 6.topic: non-nixos
