### ISSUE TITLE
error: builder for '/nix/store/8r6hvk43z84ccdf3ir01pvc2xqjcwj6a-vesktop-0.4.4.drv' failed with exit code 1;

### ISSUE THREAD

**Issue by CDTay** [NixOS/nixpkgs#294683] opened 2024-03-10 09:31 UTC
--loader flag in Vesktop package installation out of date

### Steps to reproduce:
1. Attempting `home-manager switch` with `pkgs.vesktop`

### Expected behavior
home-manager updates packages and switches

### Terminal Output
```
> VencordDesktop@0.4.4 build /build/source
> tsx scripts/build/build.mts


node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
Error: tsx must be loaded with --import instead of --loader
The --loader flag was deprecated in Node v20.6.0
    at Q (file:///build/source/node_modules/tsx/dist/esm/index.mjs:1:1793)
    at Hooks.addCustomLoader (node:internal/modules/esm/hooks:202:24)
    at Hooks.register (node:internal/modules/esm/hooks:168:16)
    at async initializeHooks (node:internal/modules/esm/utils:167:5)
    at async customizedModuleWorker (node:internal/modules/esm/worker:104:24)

Node.js v18.19.1
 ELIFECYCLE  Command failed with exit code 1.
/nix/store/10i1kjjq5szjn1gp6418x8bc1hswqc90-stdenv-linux/setup: line 131: pop_var_context: head of shell_variables not a function context
error: builder for '/nix/store/8r6hvk43z84ccdf3ir01pvc2xqjcwj6a-vesktop-0.4.4.drv' failed with exit code 1;
       last 10 log lines:
       > The --loader flag was deprecated in Node v20.6.0
       >     at Q (file:///build/source/node_modules/tsx/dist/esm/index.mjs:1:1793)
       >     at Hooks.addCustomLoader (node:internal/modules/esm/hooks:202:24)
       >     at Hooks.register (node:internal/modules/esm/hooks:168:16)
       >     at async initializeHooks (node:internal/modules/esm/utils:167:5)
       >     at async customizedModuleWorker (node:internal/modules/esm/worker:104:24)
       >
       > Node.js v18.19.1
       >  ELIFECYCLE  Command failed with exit code 1.
       > /nix/store/10i1kjjq5szjn1gp6418x8bc1hswqc90-stdenv-linux/setup: line 131: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/8r6hvk43z84ccdf3ir01pvc2xqjcwj6a-vesktop-0.4.4.drv'.
error: 1 dependencies of derivation '/nix/store/np94cf4waid8mk9vv3gjyf7xyr371sgc-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xb5glrn7kfiijpzff8zicdf0ni4y40ii-home-manager-generation.drv' failed to build
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.81, NixOS, 23.11 (Tapir), 23.11.5195.2be119add7b3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager-23.11.tar.gz, nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-03-10 16:04
duplicate of #293083

**Closed by eclairevoyant** 2024-03-10 16:04 UTC
Labels: 0.kind: bug
