### ISSUE TITLE
curl on macOS does not resolve IPv6 addresses

### ISSUE THREAD

**Issue by mknudsen** [NixOS/nixpkgs#283518] opened 2024-01-24 14:52 UTC
### Describe the bug

I installed curl through nix and tried to request a website through IPv6:

### Steps To Reproduce

```
nix-shell -p curl
this path will be fetched (0.05 MiB download, 0.25 MiB unpacked):
  /nix/store/frzkl4i1iyhy07949nrgqi2a6p9h0nmn-curl-8.4.0-dev
copying path '/nix/store/frzkl4i1iyhy07949nrgqi2a6p9h0nmn-curl-8.4.0-dev' from 'https://cache.nixos.org'...

[nix-shell:~]$ curl -6 www.heise.de
curl: (6) Could not resolve host: www.heise.de
```

### Expected behavior

A working HTTP request, like the mac os provided curl delivers:

```
➜  ~ /usr/bin/curl --version
curl 8.4.0 (x86_64-apple-darwin23.0) libcurl/8.4.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.55.1
Release-Date: 2023-10-11
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL threadsafe UnixSockets
➜  ~ /usr/bin/curl -6 www.heise.de
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

### Additional context

Running on macOS 14.2.1 (23C71).

### Notify maintainers

@lovek323

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
➜  ~ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.2.0, macOS 14.2.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by a-n-n-a-l-e-e** [comment] 2024-01-25 00:44
duplicate of https://github.com/NixOS/nixpkgs/issues/276961 and fix by https://github.com/NixOS/nixpkgs/pull/277471

**Closed by a-n-n-a-l-e-e** 2024-01-25 00:44 UTC
Labels: 0.kind: bug
