### ISSUE TITLE
[Darcs] Problems with encoding

### ISSUE THREAD

**Issue by a12l** [NixOS/nixpkgs#98190] opened 2020-09-18 00:16 UTC
**Describe the bug**

All recordings of changes in a Darcs repository using Darcs from Nixpkgs have the author information as

> Albin Otterh??ll <dev@inquisitive.se>

instead of

> Albin Otterhäll <dev@inquisitive.se>

No problems when using Darcs from Fedora 32's repository, when recording changesets.

**To Reproduce**

```
$ mkdir foo

$ cd foo/

$ darcs init
Finished initializing repository.

$ touch README.md

$ kak README.md

$ darcs add README.md
Adding './README.md'
Finished adding:
./README.md

$ darcs record
addfile ./README.md
Shall I record this change? (1/2)  [ynW...], or ? for more options: y
hunk ./README.md 1
+# Hello, World!
Shall I record this change? (2/2)  [ynW...], or ? for more options: y
Do you want to Record these changes? [Yglqk...], or ? for more options: Y
Finished recording patch 'Lorem ipsum'

$ darcs log -v
patch 509ac268e37fd48a6c3583f22b5a0926a49dba19
Author: Albin Otterh??ll <dev@inquisitive.se>
Date:   Thu Sep 17 23:36:13 CEST 2020
  * Lorem ipsum
    addfile ./README.md
    hunk ./README.md 1
    +# Hello, World!
```

```
$ /usr/bin/darcs init foo
Repository initialized.

$ cd foo/

$ kak README.md

$ /usr/bin/darcs status
a ./README.md

$ /usr/bin/darcs add README.md
Adding 'README.md'

$ /usr/bin/darcs record
addfile ./README.md
Shall I record this change? (1/2)  [ynW...], or ? for more options: y
hunk ./README.md 1
+# Hello, World!
Shall I record this change? (2/2)  [ynW...], or ? for more options: y
Do you want to Record these changes? [Yglqk...], or ? for more options: y
Finished recording patch 'Lorem ipsum'

$ /usr/bin/darcs log
patch b5fc1bdc7b153eeb7ed8243de78468c7660a2fad
Author: Albin Otterhäll <dev@inquisitive.se>
Date:   Fri Sep 18 00:49:40 CEST 2020
  * Lorem ipsum

$ kak README.md

$ darcs status
M ./README.md +2

$ darcs record -m "lol"
hunk ./README.md 2
+
+print("Python")
Shall I record this change? (1/1)  [ynW...], or ? for more options: y
Do you want to Record these changes? [Yglqk...], or ? for more options: y
Finished recording patch 'lol'

$ darcs log
patch 0e24e340c84adb8a6129ed8029c9c7c87fd3b510
Author: Albin Otterh??ll <dev@inquisitive.se>
Date:   Fri Sep 18 00:52:41 CEST 2020
  * lol
patch b5fc1bdc7b153eeb7ed8243de78468c7660a2fad
Author: Albin Otterhäll <dev@inquisitive.se>
Date:   Fri Sep 18 00:49:40 CEST 2020
  * Lorem ipsum
```

**Expected behavior**

```
[---]

$ darcs record
addfile ./README.md
Shall I record this change? (1/2)  [ynW...], or ? for more options: y
hunk ./README.md 1
+# Hello, World!
Shall I record this change? (2/2)  [ynW...], or ? for more options: y
Do you want to Record these changes? [Yglqk...], or ? for more options: Y
Finished recording patch 'Lorem ipsum'

$ darcs log -v
patch 509ac268e37fd48a6c3583f22b5a0926a49dba19
Author: Albin Otterhäll <dev@inquisitive.se>
Date:   Thu Sep 17 23:36:13 CEST 2020
  * Lorem ipsum
    addfile ./README.md
    hunk ./README.md 1
    +# Hello, World!
```

**Additional context**

```
$ cat ~/.darcs/author
# Each patch is attributed to its author, usually by email address (for
# example, `Fred Bloggs <fred@example.net>`).  Darcs looks in several
# places for this author string: the `--author` option, the files
# `_darcs/prefs/author` (in the repository) and `~/.darcs/author` (in your
# home directory), and the environment variables `$DARCS_EMAIL` and
# `$EMAIL`.  If none of those exist, Darcs will prompt you for an author
# string and write it to `~/.darcs/author`.  Note that if you have more
# than one email address, you can put them all in `~/.darcs/author`,
# one author per line.  Darcs will still prompt you for an author, but it
# allows you to select from the list, or to type in an alternative.

Albin Otterhäll <dev@inquisitive.se>
```

```
$ darcs --version
2.16.2 (release)
```

```
$ /usr/bin/darcs --version
2.14.2 (release)
```

**Notify maintainers**

_Not specified_

**Metadata**

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.9-200.fc32.x86_64, Fedora, 32 (Thirty Two)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(alo): `"home-manager, nixpkgs-21.03pre243353.6d4b93323e7"`
 - nixpkgs: `/home/alo/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by softinio** [comment] 2024-01-21 23:47
I am using:

```
❯ darcs --version
2.16.5 (release)
```

via nix on nixos and Darwin and cannot reproduce this issue. 

Shall we close this issue? 

cc @NixOS/haskell

**Comment by maralorn** [comment] 2024-01-22 00:10
Thanks for checking.

**Closed by maralorn** 2024-01-22 00:10 UTC
Labels: 0.kind: bug
