### ISSUE TITLE
`python39Packages.apsw` fails to build

### ISSUE THREAD

**Issue by elizagamedev** [NixOS/nixpkgs#167626] opened 2022-04-07 02:52 UTC
### Describe the bug
When building apsw as a dependency of `calibre` (which overrides some attrs, context below), build tests fail.

### Steps To Reproduce
1. nix-shell -p calibre

### Expected behavior
Successful build

### Screenshots
N/A

### Additional context
This is how Calibre overrides apsw, not sure if relevant.
```nix
# /pkgs/applications/misc/calibre/default.nix:87
      (apsw.overrideAttrs (oldAttrs: rec {
        setupPyBuildFlags = [ "--enable=load_extension" ];
      }))
```

### Notify maintainers

Wasn't sure who to @ here, picked some recentish names from git blame.
@fabaff 
@jonringer 

### Metadata
Using nix flakes, if that's relevant.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.29, NixOS, 22.05 (Quokka), 22.05.20220406.b6966d9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixos"`
 - channels(eliza): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by andresilva** [comment] 2022-04-07 14:52
Yes it's related to the use of the `load_extension` but I really don't understand why the tests started failing given that nothing seems to have changed. It's related to this code being executed: https://github.com/rogerbinns/apsw/blob/3.37.0-r1/tests.py#L8908-L8915

**Comment by cmm** [comment] 2022-04-10 08:04
broken somehow by this: https://github.com/NixOS/nixpkgs/commit/ac90f4238934a643f1858855223a59c525c97828

**Comment by yuuyins** [comment] 2022-04-13 23:08
maybe will fix https://github.com/NixOS/nixpkgs/pull/168071

**Comment by yuuyins** [comment] 2022-04-14 17:52
as a workaround for calibre this overlay by dee (thanks!!)

```nix
nixpkgs.overlays = [
  (overlayFinal: overlayPrev:
    let
      packageOverrides = (pythonFinal: pythonPrev: {
        apsw = pythonPrev.apsw.overridePythonAttrs (oldAttrs: {
          version = "3.38.1-r1";
          src = overlayPrev.fetchFromGitHub {
            owner = "rogerbinns";
            repo = "apsw";
            rev = "3.38.1-r1";
            sha256 = "sha256-pbb6wCu1T1mPlgoydB1Y1AKv+kToGkdVUjiom2vTqf4=";
          };
          checkInputs = [];
          # Project uses custom test setup to exclude some tests by default, so using pytest
          # requires more maintenance
          # https://github.com/rogerbinns/apsw/issues/335
          checkPhase = ''
          python tests.py
        '';
          pytestFlagsArray = [];
          disabledTests = [];
        });
      });
      python' = overlayPrev.python3.override { inherit packageOverrides; };
    in {
      calibre = overlayPrev.calibre.override { python3Packages = python'.pkgs; };
    }
  )
];
```

**Comment by rrix** [comment] 2022-04-15 20:33
> broken somehow by this: [ac90f42](https://github.com/NixOS/nixpkgs/commit/ac90f4238934a643f1858855223a59c525c97828)

that includes a pytest 6->7 bump, I can't say I'm surprised. I spent a week tracking down an incompatibility in a transitive dependency last week due to pulling in pytest 7 somewhere in a personal project.

**Comment by andresilva** [comment] 2022-04-19 10:04
Should be fixed now with https://github.com/NixOS/nixpkgs/pull/168797.

**Closed by andresilva** 2022-04-19 10:04 UTC
Labels: 0.kind: bug, 6.topic: python

**Comment by jerith666** [comment] 2022-04-21 01:52
Confirmed that 0323c98ce767eb7f7b33a60bd53b606333ab0a1d fixes the build of `calibre`.
