### ISSUE TITLE
wsl1 Failed to execute process '/nix/store/lan2w3ab1mvpxj3ppiw2sizh8i7rpz7s-busybox'. Reason:

### ISSUE THREAD

**Issue by jcleng** [NixOS/nixpkgs#114332] opened 2021-02-25 09:04 UTC
**Describe the bug**
```
/nix/store/lan2w3ab1mvpxj3ppiw2sizh8i7rpz7s-busybox
Failed to execute process '/nix/store/lan2w3ab1mvpxj3ppiw2sizh8i7rpz7s-busybox'. Reason:
exec: unknown error (errno was 8)
The file '/nix/store/lan2w3ab1mvpxj3ppiw2sizh8i7rpz7s-busybox' is marked as an executable but could not be run by the operating system.
```

```
uname -a
Linux DESKTOP-LQ95A7F 4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020 x86_64 GNU/Linux
```

**Comment by Artturin** [comment] 2023-08-27 23:03
That busybox is the one in https://github.com/NixOS/nixpkgs/blob/18f081cbbfeec96ef834afb8d865cc5ac46c59ef/pkgs/stdenv/linux/bootstrap-files/i686.nix#L2-L5

`/nix/store/lan2w3ab1mvpxj3ppiw2sizh8i7rpz7s-busybox: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, stripped`

it's used for x86_64 too https://github.com/NixOS/nixpkgs/blob/18f081cbbfeec96ef834afb8d865cc5ac46c59ef/pkgs/stdenv/linux/bootstrap-files/x86_64.nix#L1-L2

can 32bit not be executed on wsl (I think that's wsl)

**Comment by Artturin** [comment] 2023-08-27 23:09
Dupe of https://github.com/NixOS/nixpkgs/issues/24954

**Closed by Artturin** 2023-08-27 23:09 UTC
Labels: 0.kind: bug, 6.topic: windows
