### ISSUE TITLE
python35Packages.scipy fails to build

### ISSUE THREAD

**Issue by chrissound** [NixOS/nixpkgs#76499] opened 2019-12-25 14:25 UTC
With the following shell.nix:
```
let
  pkgs = import <nixpkgs> {};
in
  pkgs.mkShell {
    name = "simpleEnv";
    buildInputs = with pkgs; [
      python35Packages.virtualenv
      python35Packages.virtualenvwrapper
      python35Packages.pip
      python35Packages.setuptools
      python35Packages.numpy
      python35Packages.scikitlearn
      python35Packages.scipy
      python35Packages.matplotlib
      python35Packages.pytorch
      python35Packages.pillow
    ];
   shellHook = ''
      '';
  }
```

```
nixos-version
19.09.1549.45ea6092203 (Loris)
```

```
plementation 'sqlite(3.28.0)+pysqlite'
FAILED test/orm/test_unitofwork.py::EnsurePKSortableTest::test_exception_persistent_flush_py3k
=========== 1 failed, 8478 passed, 960 skipped in 569.16s (0:09:29) ============
f951: Warning: command line option ‘-Wformat=1’ is valid for C/C++/ObjC/ObjC++ but not for Fortran
f951: Warning: command line option ‘-Wformat-security’ is valid for C/C++/ObjC/ObjC++ but not for Fortran
creating build/lib.linux-x86_64-3.5/scipy/sparse/linalg/eigen
creating build/lib.linux-x86_64-3.5/scipy/sparse/linalg/eigen/arpack
/nix/store/2pvyavbxsdbyaxra5zzc8r6rxbpr8zc4-gfortran-wrapper-7.4.0/bin/gfortran -Wall -g -Wall -g -shared build/temp.linux-x86_64-3.5/build/src.linux-x86_64-3.5/build/src.linux-x86_64-3.5/scipy/sparse/linalg/eigen/arpack/_arpackmodule.o build/temp.linux-x86_64-3.5/build/src.linux-x86_64-3.5/build/src.linux-x86_64-3.5/build/src.linux-x86_64-3.5/scipy/sparse/linalg/eigen/arpack/fortranobject.o build/temp.linux-x86_64-3.5/build/src.linux-x86_64-3.5/build/src.linux-x86_64-3.5/scipy/sparse/linalg/eigen/arpack/_arpack-f2pywrappers.o -L/nix/store/mh4hwd7j35l9gich02nswlnayfrs1yji-openblas-0.3.7/lib -L/nix/store/hv79vzgcdl26rjvcr4y9lnaq9dkcc5kf-gfortran-7.4.0-lib/lib -L/nix/store/hv79vzgcdl26rjvcr4y9lnaq9dkcc5kf-gfortran-7.4.0-lib/lib -L/nix/store/xvd3qpm9shw0vpw70wrjjzqnfl81slr7-python3-3.5.9/lib -Lbuild/temp.linux-x86_64-3.5 -larpack_scipy -lopenblas -lopenblas -lpython3.5m -lgfortran -o build/lib.linux-x86_64-3.5/scipy/sparse/linalg/eigen/arpack/_arpack.cpython-35m-x86_64-linux-gnu.so -Wl,--version-script=build/temp.linux-x86_64-3.5/link-version-scipy.sparse.linalg.eigen.arpack._arpack.map
........................................................................ [ 53%]
........................................................................ [ 53%]
building 'scipy.sparse.csgraph._shortest_path' extension
compiling C sources
C compiler: gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

creating build/temp.linux-x86_64-3.5/scipy/sparse/csgraph
compile options: '-I/nix/store/na4q3dhghdl4956d3r2gkjyd1vxn6b6q-python3.5-numpy-1.17.2/lib/python3.5/site-packages/numpy/core/include -I/nix/store/na4q3dhghdl4956d3r2gkjyd1vxn6b6q-python3.5-numpy-1.17.2/lib/python3.5/site-packages/numpy/core/include -I/nix/store/xvd3qpm9shw0vpw70wrjjzqnfl81slr7-python3-3.5.9/include/python3.5m -c'
gcc: scipy/sparse/csgraph/_shortest_path.c
........................................................................ [ 53%]
In file included from /nix/store/na4q3dhghdl4956d3r2gkjyd1vxn6b6q-python3.5-numpy-1.17.2/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1830:0,
                 from /nix/store/na4q3dhghdl4956d3r2gkjyd1vxn6b6q-python3.5-numpy-1.17.2/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /nix/store/na4q3dhghdl4956d3r2gkjyd1vxn6b6q-python3.5-numpy-1.17.2/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from scipy/sparse/csgraph/_shortest_path.c:598:
/nix/store/na4q3dhghdl4956d3r2gkjyd1vxn6b6q-python3.5-numpy-1.17.2/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
scipy/sparse/csgraph/_shortest_path.c: In function ‘__pyx_f_5scipy_6sparse_7csgraph_14_shortest_path__floyd_warshall’:
scipy/sparse/csgraph/_shortest_path.c:4875:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (__pyx_t_7 = 0; __pyx_t_7 < __pyx_t_6; __pyx_t_7+=1) {
                                   ^
scipy/sparse/csgraph/_shortest_path.c:4887:53: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (__pyx_t_10 = (__pyx_v_i + 1); __pyx_t_10 < __pyx_t_9; __pyx_t_10+=1) {
                                                     ^
scipy/sparse/csgraph/_shortest_path.c:5157:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (__pyx_t_7 = 0; __pyx_t_7 < __pyx_t_6; __pyx_t_7+=1) {
                                   ^
scipy/sparse/csgraph/_shortest_path.c:5169:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (__pyx_t_10 = 0; __pyx_t_10 < __pyx_t_9; __pyx_t_10+=1) {
                                       ^
scipy/sparse/csgraph/_shortest_path.c:5211:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (__pyx_t_29 = 0; __pyx_t_29 < __pyx_t_28; __pyx_t_29+=1) {
                                         ^
scipy/sparse/csgraph/_shortest_path.c:5296:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (__pyx_t_7 = 0; __pyx_t_7 < __pyx_t_6; __pyx_t_7+=1) {
                                   ^
scipy/sparse/csgraph/_shortest_path.c:5308:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (__pyx_t_10 = 0; __pyx_t_10 < __pyx_t_9; __pyx_t_10+=1) {
                                       ^
scipy/sparse/csgraph/_shortest_path.c:5350:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (__pyx_t_29 = 0; __pyx_t_29 < __pyx_t_28; __pyx_t_29+=1) {
                                         ^
........................................................................ [ 53%]
scipy/sparse/csgraph/_shortest_path.c: In function ‘__pyx_f_5scipy_6sparse_7csgraph_14_shortest_path__bellman_ford_directed’:
scipy/sparse/csgraph/_shortest_path.c:10537:146: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (__pyx_t_19 = (*((int const  *) ( /* dim=0 */ (__pyx_v_csr_indptr.data + __pyx_t_17 * __pyx_v_csr_indptr.strides[0]) ))); __pyx_t_19 < __pyx_t_18; __pyx_t_19+=1) {
                                                                                                                                                  ^
scipy/sparse/csgraph/_shortest_path.c:10737:144: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (__pyx_t_13 = (*((int const  *) ( /* dim=0 */ (__pyx_v_csr_indptr.data + __pyx_t_35 * __pyx_v_csr_indptr.strides[0]) ))); __pyx_t_13 < __pyx_t_18; __pyx_t_13+=1) {
                                                                                                                                                ^
scipy/sparse/csgraph/_shortest_path.c: In function ‘__pyx_f_5scipy_6sparse_7csgraph_14_shortest_path__bellman_ford_undirected’:
scipy/sparse/csgraph/_shortest_path.c:11044:146: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (__pyx_t_19 = (*((int const  *) ( /* dim=0 */ (__pyx_v_csr_indptr.data + __pyx_t_17 * __pyx_v_csr_indptr.strides[0]) ))); __pyx_t_19 < __pyx_t_18; __pyx_t_19+=1) {
                                                                                                                                                  ^
scipy/sparse/csgraph/_shortest_path.c:11308:144: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (__pyx_t_13 = (*((int const  *) ( /* dim=0 */ (__pyx_v_csr_indptr.data + __pyx_t_38 * __pyx_v_csr_indptr.strides[0]) ))); __pyx_t_13 < __pyx_t_18; __pyx_t_13+=1) {
                                                                                                                                                ^
scipy/sparse/csgraph/_shortest_path.c: In function ‘__pyx_f_5scipy_6sparse_7csgraph_14_shortest_path__johnson_add_weights’:
scipy/sparse/csgraph/_shortest_path.c:13217:132: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (__pyx_t_8 = (*((int *) ( /* dim=0 */ (__pyx_v_csr_indptr.data + __pyx_t_6 * __pyx_v_csr_indptr.strides[0]) ))); __pyx_t_8 < __pyx_t_7; __pyx_t_8+=1) {
                                                                                                                                    ^
scipy/sparse/csgraph/_shortest_path.c: In function ‘__pyx_f_5scipy_6sparse_7csgraph_14_shortest_path__johnson_directed’:
scipy/sparse/csgraph/_shortest_path.c:13471:144: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (__pyx_t_15 = (*((int const  *) ( /* dim=0 */ (__pyx_v_csr_indptr.data + __pyx_t_13 * __pyx_v_csr_indptr.strides[0]) ))); __pyx_t_15 < __pyx_t_14; __pyx_t_15+=1) {
                                                                                                                                                ^
scipy/sparse/csgraph/_shortest_path.c:13618:140: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (__pyx_t_4 = (*((int const  *) ( /* dim=0 */ (__pyx_v_csr_indptr.data + __pyx_t_24 * __pyx_v_csr_indptr.strides[0]) ))); __pyx_t_4 < __pyx_t_14; __pyx_t_4+=1) {
                                                                                                                                            ^
scipy/sparse/csgraph/_shortest_path.c: In function ‘__pyx_f_5scipy_6sparse_7csgraph_14_shortest_path__johnson_undirected’:
scipy/sparse/csgraph/_shortest_path.c:13900:144: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (__pyx_t_15 = (*((int const  *) ( /* dim=0 */ (__pyx_v_csr_indptr.data + __pyx_t_13 * __pyx_v_csr_indptr.strides[0]) ))); __pyx_t_15 < __pyx_t_14; __pyx_t_15+=1) {
                                                                                                                                                ^
scipy/sparse/csgraph/_shortest_path.c:14080:140: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (__pyx_t_4 = (*((int const  *) ( /* dim=0 */ (__pyx_v_csr_indptr.data + __pyx_t_25 * __pyx_v_csr_indptr.strides[0]) ))); __pyx_t_4 < __pyx_t_14; __pyx_t_4+=1) {
                                                                                                                                            ^
........................................................................ [ 54%]
[ 56%] Building CXX object caffe2/CMakeFiles/caffe2.dir/operators/fully_connected_op.cc.o
........................................................................ [ 54%]
[ 56%] Building CXX object caffe2/CMakeFiles/caffe2.dir/operators/fused_rowwise_8bit_conversion_ops.cc.o
........................................................................ [ 54%]
........................................................................ [ 54%]
........................................................................ [ 54%]
[ 56%] Building CXX object caffe2/CMakeFiles/caffe2.dir/operators/fused_rowwise_random_quantization_ops.cc.o
........................................................................ [ 54%]
........................................................................ [ 54%]
........................................................................ [ 54%]
........................................................................ [ 54%]
[ 57%] Building CXX object caffe2/CMakeFiles/caffe2.dir/operators/gather_fused_8bit_rowwise_op.cc.o
[ 57%] Building CXX object caffe2/CMakeFiles/caffe2.dir/operators/gather_op.cc.o
[ 57%] Building CXX object caffe2/CMakeFiles/caffe2.dir/operators/gather_ranges_to_dense_op.cc.o
........................................................................ [ 54%]
[ 57%] Building CXX object caffe2/CMakeFiles/caffe2.dir/operators/generate_proposals_op.cc.o
[ 57%] Building CXX object caffe2/CMakeFiles/caffe2.dir/operators/given_tensor_byte_string_to_uint8_fill_op.cc.o
........................................................................ [ 54%]
[ 57%] Building CXX object caffe2/CMakeFiles/caffe2.dir/operators/given_tensor_fill_op.cc.o
........................................................................ [ 54%]
[ 57%] Building CXX object caffe2/CMakeFiles/caffe2.dir/operators/glu_op.cc.o
........................................................................ [ 54%]
[ 57%] Building CXX object caffe2/CMakeFiles/caffe2.dir/operators/group_norm_op.cc.o
........................................................................ [ 54%]
........................................................................ [ 54%]
builder for '/nix/store/psna8y6fqripggpy9bmnxi6sfgv02nm9-python3.5-SQLAlchemy-1.3.6.drv' failed with exit code 1
cannot build derivation '/nix/store/8j5gdcnw6ql0q55icdkaqv2j4n948yzm-python3.5-sphinx-1.8.3.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/p8axhzdj1bw32ps8nlcbkivf0ldz5ira-python3.5-joblib-0.13.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/kzcrcg2mp8rwj7lg7kn4c6m55b6g6xn9-python3.5-matplotlib-3.1.1.drv': 1 dependencies couldn't be built
error: build of '/nix/store/48drbcc60lqvgb03g6mjdiwj01g2csfs-python3.5-scipy-1.3.1.drv', '/nix/store/64f3iyy8wwxzr84scxv76l1in1w41b3w-python3.5-pytorch-1.0.0.drv', '/nix/store/kzcrcg2mp8rwj7lg7kn4c6m55b6g6xn9-python3.5-matplotlib-3.1.1.drv', '/nix/store/q291qhnspsz41cqi43yi380w3dsnwlic-python3.5-scikit-learn-0.21.2.drv' failed
```

**Comment by flokli** [comment] 2020-01-02 01:09
This seems to have been a build failure caused by sphinx not building. I can't reproduce on nixpkgs `master` or `release-19.09` branches anymore.

**Comment by chrissound** [comment] 2020-01-02 08:31
Still running into this issue, (and ran a nixos-channel update yesterday + I'm on 19.09):
https://gist.github.com/chrissound/6a4a399fdb8d662f3b9c87aa06d01c14
:
```
...
........................................................................ [ 63%]
........................................................................ [ 63%]
........................................................................ [ 63%]
........................................................................ [ 63%]
........................................................................ [ 63%]
........................................................................ [ 63%]
........................................................................ [ 63%]
builder for '/nix/store/q8i28gzh0yjsbiv7hkr0kxkl1pmbgx11-python3.5-SQLAlchemy-1.3.6.drv' failed with exit code 1
cannot build derivation '/nix/store/3yb2hbsrpjm7zrdlz4r0806l184xiy6g-python3.5-sphinx-1.8.3.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ii6s7blsc6qchv18gil9zlw9w0ivy7dd-python3.5-joblib-0.13.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/09kk6lzfn3akbwyb5p5blfyv4hl5g5kp-python3.5-scikit-learn-0.21.2.drv': 1 dependencies couldn't be built
error: build of '/nix/store/09kk6lzfn3akbwyb5p5blfyv4hl5g5kp-python3.5-scikit-learn-0.21.2.drv', '/nix/store/pw951khna7hwav8rs1wcchwrnccx6pfz-python3.5-scipy-1.3.1.drv' failed
```

I've also narrowed it somewhat down to:
```
let
  pkgs = import <nixpkgs> {};
in
  pkgs.mkShell {
    name = "simpleEnv";
    buildInputs = with pkgs; [
      python35Packages.scikitlearn
      python35Packages.scipy
    ];
   shellHook = ''
      '';
  }
```

```
nixos-version
19.09.1693.eab4ee0c27c (Loris)
```

**Comment by doronbehar** [comment] 2020-04-19 15:11
`python2Packages.scipy` doesn't build on latest master:

```
customize UnixCCompiler
  libraries mkl_rt not found in ['/nix/store/8f6kdvqkdb2g7pr8x68lm9hjbw29gf7k-python-2.7.17/lib']
  NOT AVAILABLE

openblas_lapack_info:
customize UnixCCompiler
customize UnixCCompiler
  libraries openblas not found in ['/nix/store/3gia15f4i46fvxxr6n4n3jlp8di2rxyw-blas-3/lib', '/nix/store/qrfg733cck2znlfp7bagrlqsrjxja9bm-lapack-3/lib']
  NOT AVAILABLE

openblas_clapack_info:
customize UnixCCompiler
customize UnixCCompiler
  libraries openblas,lapack not found in ['/nix/store/3gia15f4i46fvxxr6n4n3jlp8di2rxyw-blas-3/lib', '/nix/store/qrfg733cck2znlfp7bagrlqsrjxja9bm-lapack-3/lib']
  NOT AVAILABLE

atlas_3_10_threads_info:
Setting PTATLAS=ATLAS
customize UnixCCompiler
  libraries lapack_atlas not found in /nix/store/8f6kdvqkdb2g7pr8x68lm9hjbw29gf7k-python-2.7.17/lib
customize UnixCCompiler
  libraries tatlas,tatlas not found in /nix/store/8f6kdvqkdb2g7pr8x68lm9hjbw29gf7k-python-2.7.17/lib
<class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
  NOT AVAILABLE

atlas_3_10_info:
customize UnixCCompiler
  libraries lapack_atlas not found in /nix/store/8f6kdvqkdb2g7pr8x68lm9hjbw29gf7k-python-2.7.17/lib
customize UnixCCompiler
  libraries satlas,satlas not found in /nix/store/8f6kdvqkdb2g7pr8x68lm9hjbw29gf7k-python-2.7.17/lib
<class 'numpy.distutils.system_info.atlas_3_10_info'>
  NOT AVAILABLE

atlas_threads_info:
Setting PTATLAS=ATLAS
customize UnixCCompiler
  libraries lapack_atlas not found in /nix/store/8f6kdvqkdb2g7pr8x68lm9hjbw29gf7k-python-2.7.17/lib
customize UnixCCompiler
  libraries ptf77blas,ptcblas,atlas not found in /nix/store/8f6kdvqkdb2g7pr8x68lm9hjbw29gf7k-python-2.7.17/lib
<class 'numpy.distutils.system_info.atlas_threads_info'>
  NOT AVAILABLE

atlas_info:
customize UnixCCompiler
  libraries lapack_atlas not found in /nix/store/8f6kdvqkdb2g7pr8x68lm9hjbw29gf7k-python-2.7.17/lib
customize UnixCCompiler
  libraries f77blas,cblas,atlas not found in /nix/store/8f6kdvqkdb2g7pr8x68lm9hjbw29gf7k-python-2.7.17/lib
<class 'numpy.distutils.system_info.atlas_info'>
  NOT AVAILABLE

accelerate_info:
  NOT AVAILABLE

/nix/store/1z0m3xcdyvl7q2rfmmh8imfllqpsw2yj-python2.7-numpy-1.16.5/lib/python2.7/site-packages/numpy/distutils/system_info.py:639: UserWarning:
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  self.calc_info()
lapack_info:
customize UnixCCompiler
  libraries lapack not found in ['/nix/store/8f6kdvqkdb2g7pr8x68lm9hjbw29gf7k-python-2.7.17/lib']
  NOT AVAILABLE

/nix/store/1z0m3xcdyvl7q2rfmmh8imfllqpsw2yj-python2.7-numpy-1.16.5/lib/python2.7/site-packages/numpy/distutils/system_info.py:639: UserWarning:
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  self.calc_info()
lapack_src_info:
  NOT AVAILABLE

/nix/store/1z0m3xcdyvl7q2rfmmh8imfllqpsw2yj-python2.7-numpy-1.16.5/lib/python2.7/site-packages/numpy/distutils/system_info.py:639: UserWarning:
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  self.calc_info()
  NOT AVAILABLE

Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 492, in <module>
    setup_package()
  File "setup.py", line 488, in setup_package
    setup(**metadata)
  File "/nix/store/1z0m3xcdyvl7q2rfmmh8imfllqpsw2yj-python2.7-numpy-1.16.5/lib/python2.7/site-packages/numpy/distutils/core.py", line 137, in setup
    config = configuration()
  File "setup.py", line 395, in configuration
    raise NotFoundError(msg)
numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
builder for '/nix/store/61kq516hvbfzl8mdhs7wdf64wp5cqihp-python2.7-scipy-1.2.2.drv' failed with exit code 1
error: build of '/nix/store/61kq516hvbfzl8mdhs7wdf64wp5cqihp-python2.7-scipy-1.2.2.drv' failed
```

Relevant for example: Gnuradio, gqrx (just putting these as examples for anyone else to find this issue).

**Comment by symphorien** [comment] 2020-04-20 18:48
Same applies for python3Packages.scipy with a very similar error message.

**Comment by symphorien** [comment] 2020-04-20 19:49
I bisected with the very awesome nix-bisect of timokau, and the regression was introduced by 1c8aba83340be3713f68410d1d273a8b15e7e007 that is https://github.com/NixOS/nixpkgs/pull/83888

**Comment by teto** [comment] 2020-04-23 12:44
this looks fixed on master (checked with `hydra-check python3Packages.scipy --channel master`)

**Comment by fionera** [comment] 2020-04-24 18:10
Because of this binwalk doesnt build on nixpkgs-unstable

**Comment by flokli** [comment] 2020-04-24 20:33
I can confirm this is fixed on master.

I could compile `/nix/store/2ri3s6lnfchy0xijpd30jdkcmmqwqs0g-python3.5-scipy-1.4.1` successfully.

It'll end up in `nixpkgs-unstable` eventually too - I recommend montioring https://status.nixos.org/ when the channel advances, or using a custom nixpgks checkout for the time being.

**Closed by flokli** 2020-04-24 20:33 UTC
Labels: 0.kind: bug, 6.topic: python, 9.needs: reporter feedback
