### ISSUE TITLE
Installing virt-manager failed due to spice-gtk dependency (python pyparsing failed to find during building)

### ISSUE THREAD

**Issue by selfuryon** [NixOS/nixpkgs#161074] opened 2022-02-20 14:54 UTC
### Describe the bug
Can't install virt-manager due to failed spice-gtk dependency

### Steps To Reproduce
```
λ nix shell nixpkgs#virt-manager
error: builder for '/nix/store/mgs5j3b4baqjw322k7gfhx8if3wgssq3-spice-gtk-0.37.drv' failed with exit code 1;
       last 10 log lines:
       > spice-common| Run-time dependency openssl found: YES 1.1.1m
       > spice-common| Dependency celt051 skipped: feature celt051 disabled
       > spice-common| Run-time dependency opus found: YES 1.3.1
       > spice-common| Program python3 found: YES (/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/bin/python3.9)
       > spice-common| Message: Checking for python module six
       > spice-common| Message: Checking for python module pyparsing
       >
       > subprojects/spice-common/meson.build:140:6: ERROR: Problem encountered: Python module pyparsing not found
       >
       > A full log can be found at /build/spice-gtk-0.37/build/meson-logs/meson-log.txt
       For full logs, run 'nix log /nix/store/mgs5j3b4baqjw322k7gfhx8if3wgssq3-spice-gtk-0.37.drv'.
error: 1 dependencies of derivation '/nix/store/gxk3rzv7vwsxajg0d0xd1yfdpwsmjpj1-virt-manager-3.2.0.drv' failed to build
```

### Expected behavior
It should be installed successfully. In previous commit in unstable branch it works. 

### Additional context
Full log:
```
λ nix log /nix/store/mgs5j3b4baqjw322k7gfhx8if3wgssq3-spice-gtk-0.37.drv
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/1085xrxs0sl84r12641shac53af5cr18-spice-gtk-0.37.tar.bz2
source root is spice-gtk-0.37
setting SOURCE_DATE_EPOCH to timestamp 1558007590 of file spice-gtk-0.37/doc/reference/html/spice-gtk-spice-version.html
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
meson flags: --buildtype=plain         --libdir=/nix/store/54ix55g2q6jrkvgda5290azz0rbj7jix-spice-gtk-0.37/lib --libexecdir=/nix/store/54ix55g2q6jrkvgda5290azz0rbj7jix-spice-gtk-0.37/libexec         --bindir=/nix/store/54ix55g2q6jrkvgda5290azz0rbj7jix-spice-gtk-0.37/bin --sbindir=/nix/store/54ix55g2q6jrkvgda5290azz0rbj7jix-spice-gtk-0.37/sbin         --includedir=/nix/store/10>
The Meson build system
Version: 0.60.3
Source dir: /build/spice-gtk-0.37
Build dir: /build/spice-gtk-0.37/build
Build type: native build
Project name: spice-gtk
Project version: 0.37
C compiler for the host machine: gcc (gcc 10.3.0 "gcc (GCC) 10.3.0")
C linker for the host machine: gcc ld.bfd 2.35.2
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program sh found: YES (/nix/store/4nmqxajzaf60yjribkgvj5j54x9yvr1r-bash-5.1-p12/bin/sh)

Executing subproject spice-common

spice-common| Project name: spice-common
spice-common| Project version: undefined
spice-common| C compiler for the host machine: gcc (gcc 10.3.0 "gcc (GCC) 10.3.0")
spice-common| C linker for the host machine: gcc ld.bfd 2.35.2
spice-common| Has header "alloca.h" : YES
spice-common| Has header "arpa/inet.h" : YES
spice-common| Has header "dlfcn.h" : YES
spice-common| Has header "inttypes.h" : YES
spice-common| Has header "malloc.h" : YES
spice-common| Has header "memory.h" : YES
spice-common| Has header "netinet/in.h" : YES
spice-common| Has header "stddef.h" : YES
spice-common| Has header "stdint.h" : YES
spice-common| Has header "stdlib.h" : YES
spice-common| Has header "strings.h" : YES
spice-common| Has header "string.h" : YES
spice-common| Has header "sys/socket.h" : YES
spice-common| Has header "sys/stat.h" : YES
spice-common| Has header "sys/types.h" : YES
spice-common| Has header "unistd.h" : YES
spice-common| Has header "regex.h" : YES
spice-common| Has header "sys/mman.h" : YES
spice-common| Checking for function "alloca" : YES
spice-common| Checking for function "sigaction" : YES[user@system:~]$ nix-shell -p remarshal -I nixpkgs=https://github.com/NixOS/nixpkgs/ar0.2
spice-common| Run-time dependency gio-2.0 found: YES 2.70.2
spice-common| Run-time dependency gthread-2.0 found: YES 2.70.2
spice-common| Run-time dependency pixman-1 found: YES 0.38.4
spice-common| Run-time dependency openssl found: YES 1.1.1m
spice-common| Dependency celt051 skipped: feature celt051 disabled
spice-common| Run-time dependency opus found: YES 1.3.1
spice-common| Program python3 found: YES (/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/bin/python3.9)
spice-common| Message: Checking for python module six
spice-common| Message: Checking for python module pyparsing

subprojects/spice-common/meson.build:140:6: ERROR: Problem encountered: Python module pyparsing not found

A full log can be found at /build/spice-gtk-0.37/build/meson-logs/meson-log.txt
```

### Notify maintainers
@xeji as maintainer of spice-gtk
@qknight @fpletz @globin as maintainers of virt-manager

### Metadata
I use flake-based system, it looks like:
```
λ cat flake.lock -p
{
...
    "nixpkgs": {
      "locked": {
        "lastModified": 1644613700,
        "narHash": "sha256-wLRPJclMH8vsHuFtyI78aF09lw5mbi3lMB6uiK5S2wE=",
        "owner": "nixos",
        "repo": "nixpkgs",
        "rev": "23d785aa6f853e6cf3430119811c334025bbef55",
        "type": "github"
      },
      "original": {
        "owner": "nixos",
        "ref": "nixos-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
...
```

**Comment by lourkeur** [comment] 2022-02-20 18:28
duplicate of #159270. The issue is resolved on `master`, but `nixos-unstable` has been stuck for a bit because of an unrelated issue. In the meantime, please consider switching to `nixos-unstable-small`, or applying the patch yourself.

**Closed by lourkeur** 2022-02-20 18:28 UTC
Labels: 0.kind: bug
