### ISSUE TITLE
ffmpeg > 3.1 is broken on darwin

### ISSUE THREAD

**Issue by l2dy** [NixOS/nixpkgs#18137] opened 2016-08-31 00:53 UTC
## Issue description

From <https://hydra.nixos.org/job/nixpkgs/trunk/ffmpeg_3_1.x86_64-darwin>:
Build 39208806 and 39410737 are both for ffmpeg-3.1.2 and the later failed with `libavcodec/audiotoolboxdec.c:71:16: error: use of undeclared identifier 'kAudioFormatEnhancedAC3'; did you mean 'kAudioFormat60958AC3'?`.

## Technical details

* System: Mac OS X

**Comment by grahamc** [comment] 2016-08-31 01:00
Can you try this again in a bit? We upgraded ffmpeg again to 3.2.3.

**Comment by l2dy** [comment] 2016-08-31 01:02
3.1.3 is also broken. See <https://hydra.nixos.org/build/39510734>.

**Comment by grahamc** [comment] 2016-08-31 01:04
sure enough...

**Comment by grahamc** [comment] 2016-08-31 01:15
I heard from @copumpkin that the issue is likely due to using macOS headers from 10.10, and that his upgrade of stdenv (later this week) should make this fixable.

**Comment by copumpkin** [comment] 2016-08-31 11:30
10.9, but yeah, I'd expect that would cause an error like this: https://developer.apple.com/reference/coreaudio/kaudioformatenhancedac3

I guess the weird thing is that I wouldn't expect ffmpeg to just break on Mac OS < 10.11. Perhaps something else we're doing makes it believe we're on 10.11 (it might reach out to impure paths to determine that) and then when it tries to use the SDK it fails?

**Comment by acowley** [comment] 2016-08-31 23:21
I add a [temporary fix](https://github.com/NixOS/nixpkgs/pull/18174/commits/7b8668892316f1b5fb25d4526330f8e908c27c28) for this to `ffmpeg-full` while updating it.

**Comment by matthewbauer** [comment] 2016-09-19 00:21
This seems to be fixed. Can we close it?

**Closed** 2016-09-20 01:29 UTC
Labels: 6.topic: darwin
