### ISSUE TITLE
Radeon no longer works

### ISSUE THREAD

**Issue by simendsjo** [NixOS/nixpkgs#31154] opened 2017-11-02 20:25 UTC
## Issue description

I just updated from 17.09.1927.6a0a00d91e to 17.09.1965.c567ec632e, and now radeon (or X?) is broken.

```
Nov 02 20:55:36 simendsjo-macbook kernel: radeon 0000:01:00.0: ring 0 stalled for more than 10061msec
Nov 02 20:55:36 simendsjo-macbook kernel: radeon 0000:01:00.0: GPU lockup (current fence id 0x0000000000000006 last fence id 0x0000000000000008 on ring 0)
Nov 02 20:55:36 simendsjo-macbook kernel: radeon 0000:01:00.0: Saved 79 dwords of commands on ring 0.
Nov 02 20:55:36 simendsjo-macbook kernel: radeon 0000:01:00.0: GPU softreset: 0x00000049
Nov 02 20:55:36 simendsjo-macbook kernel: radeon 0000:01:00.0:   GRBM_STATUS               = 0xB2523028
Nov 02 20:55:36 simendsjo-macbook kernel: radeon 0000:01:00.0:   GRBM_STATUS_SE0           = 0x0D800006
Nov 02 20:55:36 simendsjo-macbook kernel: radeon 0000:01:00.0:   GRBM_STATUS_SE1           = 0x00000006
Nov 02 20:55:36 simendsjo-macbook kernel: radeon 0000:01:00.0:   SRBM_STATUS               = 0x200000C0
Nov 02 20:55:36 simendsjo-macbook kernel: radeon 0000:01:00.0:   SRBM_STATUS2              = 0x00000000
Nov 02 20:55:36 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_008674_CP_STALLED_STAT1 = 0x00000000
Nov 02 20:55:36 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_008678_CP_STALLED_STAT2 = 0x40000000
Nov 02 20:55:36 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_00867C_CP_BUSY_STAT     = 0x00408006
Nov 02 20:55:36 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_008680_CP_STAT          = 0x84228647
Nov 02 20:55:36 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_00D034_DMA_STATUS_REG   = 0x44C83D57
Nov 02 20:55:36 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_00D834_DMA_STATUS_REG   = 0x44C83D57
Nov 02 20:55:36 simendsjo-macbook kernel: radeon 0000:01:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x00000000
Nov 02 20:55:36 simendsjo-macbook kernel: radeon 0000:01:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x00000000
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0: GRBM_SOFT_RESET=0x0000DDFF
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0: SRBM_SOFT_RESET=0x00000100
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0:   GRBM_STATUS               = 0x00003028
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0:   GRBM_STATUS_SE0           = 0x00000006
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0:   GRBM_STATUS_SE1           = 0x00000006
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0:   SRBM_STATUS               = 0x200000C0
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0:   SRBM_STATUS2              = 0x00000000
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_008674_CP_STALLED_STAT1 = 0x00000000
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_008678_CP_STALLED_STAT2 = 0x00000000
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_00867C_CP_BUSY_STAT     = 0x00000000
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_008680_CP_STAT          = 0x00000000
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_00D034_DMA_STATUS_REG   = 0x44C83D57
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_00D834_DMA_STATUS_REG   = 0x44C83D57
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0: GPU reset succeeded, trying to resume
Nov 02 20:55:37 simendsjo-macbook kernel: [drm] probing gen 2 caps for device 8086:d01 = 261ac83/e
Nov 02 20:55:37 simendsjo-macbook kernel: [drm] PCIE gen 3 link speeds already enabled
Nov 02 20:55:37 simendsjo-macbook kernel: [drm] PCIE GART of 2048M enabled (table at 0x00000000001D6000).
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0: WB enabled
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0: fence driver on ring 0 use gpu addr 0x0000000080000c00 and cpu addr 0xffff9a6922c43c00
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0: fence driver on ring 1 use gpu addr 0x0000000080000c04 and cpu addr 0xffff9a6922c43c04
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0: fence driver on ring 2 use gpu addr 0x0000000080000c08 and cpu addr 0xffff9a6922c43c08
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0: fence driver on ring 3 use gpu addr 0x0000000080000c0c and cpu addr 0xffff9a6922c43c0c
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0: fence driver on ring 4 use gpu addr 0x0000000080000c10 and cpu addr 0xffff9a6922c43c10
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0: fence driver on ring 5 use gpu addr 0x0000000000075a18 and cpu addr 0xffffae0b84235a18
Nov 02 20:55:37 simendsjo-macbook kernel: radeon 0000:01:00.0: failed VCE resume (-22).
Nov 02 20:55:37 simendsjo-macbook kernel: [drm] ring test on 0 succeeded in 2 usecs
Nov 02 20:55:37 simendsjo-macbook kernel: [drm] ring test on 1 succeeded in 1 usecs
Nov 02 20:55:37 simendsjo-macbook kernel: [drm] ring test on 2 succeeded in 1 usecs
Nov 02 20:55:37 simendsjo-macbook kernel: [drm] ring test on 3 succeeded in 8 usecs
Nov 02 20:55:37 simendsjo-macbook kernel: [drm] ring test on 4 succeeded in 3 usecs
Nov 02 20:55:37 simendsjo-macbook kernel: [drm] ring test on 5 succeeded in 2 usecs
Nov 02 20:55:37 simendsjo-macbook kernel: [drm] UVD initialized successfully.
Nov 02 20:55:38 simendsjo-macbook systemd-journald[534]: Suppressed 55 messages from /system.slice/display-manager.service
Nov 02 20:55:38 simendsjo-macbook X[941]: (II) device control: off
Nov 02 20:55:38 simendsjo-macbook X[941]: (II) AIGLX: Suspending AIGLX clients for VT switch
Nov 02 20:55:39 simendsjo-macbook systemd[1]: Started Getty on tty2.
Nov 02 20:55:39 simendsjo-macbook kernel: [drm:radeon_dp_link_train [radeon]] *ERROR* displayport link status failed
Nov 02 20:55:39 simendsjo-macbook kernel: [drm:radeon_dp_link_train [radeon]] *ERROR* clock recovery failed
Nov 02 20:55:40 simendsjo-macbook kernel: [drm:r600_ib_test [radeon]] *ERROR* radeon: fence wait timed out.
Nov 02 20:55:40 simendsjo-macbook kernel: [drm:radeon_ib_ring_tests [radeon]] *ERROR* radeon: failed testing IB on GFX ring (-110).
Nov 02 20:55:40 simendsjo-macbook kernel: radeon 0000:01:00.0: GPU softreset: 0x00000049
Nov 02 20:55:40 simendsjo-macbook kernel: radeon 0000:01:00.0:   GRBM_STATUS               = 0xE7DE0028
Nov 02 20:55:40 simendsjo-macbook kernel: radeon 0000:01:00.0:   GRBM_STATUS_SE0           = 0xEDC00000
Nov 02 20:55:40 simendsjo-macbook kernel: radeon 0000:01:00.0:   GRBM_STATUS_SE1           = 0x00000006
Nov 02 20:55:40 simendsjo-macbook kernel: radeon 0000:01:00.0:   SRBM_STATUS               = 0x20000AC0
Nov 02 20:55:40 simendsjo-macbook kernel: radeon 0000:01:00.0:   SRBM_STATUS2              = 0x00000000
Nov 02 20:55:40 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_008674_CP_STALLED_STAT1 = 0x00000000
Nov 02 20:55:40 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_008678_CP_STALLED_STAT2 = 0x00010800
Nov 02 20:55:40 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_00867C_CP_BUSY_STAT     = 0x00008000
Nov 02 20:55:40 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_008680_CP_STAT          = 0x80038647
Nov 02 20:55:40 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_00D034_DMA_STATUS_REG   = 0x44C83D57
Nov 02 20:55:40 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_00D834_DMA_STATUS_REG   = 0x44C83D57
Nov 02 20:55:40 simendsjo-macbook kernel: radeon 0000:01:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x00000000
Nov 02 20:55:40 simendsjo-macbook kernel: radeon 0000:01:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x00000000
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0: GRBM_SOFT_RESET=0x0000DDFF
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0: SRBM_SOFT_RESET=0x00000100
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0:   GRBM_STATUS               = 0x00003028
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0:   GRBM_STATUS_SE0           = 0x00000006
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0:   GRBM_STATUS_SE1           = 0x00000006
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0:   SRBM_STATUS               = 0x200000C0
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0:   SRBM_STATUS2              = 0x00000000
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_008674_CP_STALLED_STAT1 = 0x00000000
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_008678_CP_STALLED_STAT2 = 0x00000000
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_00867C_CP_BUSY_STAT     = 0x00000000
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_008680_CP_STAT          = 0x00000000
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_00D034_DMA_STATUS_REG   = 0x44C83D57
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0:   R_00D834_DMA_STATUS_REG   = 0x44C83D57
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0: GPU reset succeeded, trying to resume
Nov 02 20:55:41 simendsjo-macbook kernel: [drm] probing gen 2 caps for device 8086:d01 = 261ac83/e
Nov 02 20:55:41 simendsjo-macbook kernel: [drm] PCIE gen 3 link speeds already enabled
Nov 02 20:55:41 simendsjo-macbook kernel: [drm] PCIE GART of 2048M enabled (table at 0x00000000001D6000).
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0: WB enabled
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0: fence driver on ring 0 use gpu addr 0x0000000080000c00 and cpu addr 0xffff9a6922c43c00
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0: fence driver on ring 1 use gpu addr 0x0000000080000c04 and cpu addr 0xffff9a6922c43c04
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0: fence driver on ring 2 use gpu addr 0x0000000080000c08 and cpu addr 0xffff9a6922c43c08
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0: fence driver on ring 3 use gpu addr 0x0000000080000c0c and cpu addr 0xffff9a6922c43c0c
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0: fence driver on ring 4 use gpu addr 0x0000000080000c10 and cpu addr 0xffff9a6922c43c10
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0: fence driver on ring 5 use gpu addr 0x0000000000075a18 and cpu addr 0xffffae0b84235a18
Nov 02 20:55:41 simendsjo-macbook kernel: radeon 0000:01:00.0: failed VCE resume (-22).
Nov 02 20:55:41 simendsjo-macbook kernel: [drm] ring test on 0 succeeded in 2 usecs
Nov 02 20:55:41 simendsjo-macbook kernel: [drm] ring test on 1 succeeded in 1 usecs
Nov 02 20:55:41 simendsjo-macbook kernel: [drm] ring test on 2 succeeded in 1 usecs
Nov 02 20:55:41 simendsjo-macbook kernel: [drm] ring test on 3 succeeded in 9 usecs
Nov 02 20:55:41 simendsjo-macbook kernel: [drm] ring test on 4 succeeded in 3 usecs
Nov 02 20:55:41 simendsjo-macbook kernel: [drm] ring test on 5 succeeded in 2 usecs
Nov 02 20:55:41 simendsjo-macbook kernel: [drm] UVD initialized successfully.
Nov 02 20:55:42 simendsjo-macbook kernel: [drm:radeon_dp_link_train [radeon]] *ERROR* displayport link status failed
Nov 02 20:55:42 simendsjo-macbook kernel: [drm:radeon_dp_link_train [radeon]] *ERROR* clock recovery failed
Nov 02 20:55:42 simendsjo-macbook kernel: [drm] ib test on ring 0 succeeded in 0 usecs
Nov 02 20:55:42 simendsjo-macbook kernel: [drm] ib test on ring 1 succeeded in 0 usecs
Nov 02 20:55:42 simendsjo-macbook kernel: [drm] ib test on ring 2 succeeded in 0 usecs
Nov 02 20:55:42 simendsjo-macbook kernel: [drm] ib test on ring 3 succeeded in 0 usecs
Nov 02 20:55:42 simendsjo-macbook kernel: [drm] ib test on ring 4 succeeded in 0 usecs
Nov 02 20:55:43 simendsjo-macbook kernel: [drm:uvd_v1_0_ib_test [radeon]] *ERROR* radeon: fence wait timed out.
Nov 02 20:55:43 simendsjo-macbook kernel: [drm:radeon_ib_ring_tests [radeon]] *ERROR* radeon: failed testing IB on ring 5 (-110).
Nov 02 20:55:43 simendsjo-macbook kernel: radeon 0000:01:00.0: scheduling IB failed (-12).
Nov 02 20:55:43 simendsjo-macbook kernel: [drm:radeon_vce_get_create_msg [radeon]] *ERROR* radeon: failed to schedule ib (-12).
Nov 02 20:55:43 simendsjo-macbook kernel: [drm:radeon_vce_ib_test [radeon]] *ERROR* radeon: failed to get create msg (-12).
Nov 02 20:55:43 simendsjo-macbook kernel: [drm:radeon_ib_ring_tests [radeon]] *ERROR* radeon: failed testing IB on ring 6 (-12).
Nov 02 20:55:43 simendsjo-macbook kernel: radeon 0000:01:00.0: scheduling IB failed (-12).
Nov 02 20:55:43 simendsjo-macbook kernel: [drm:radeon_vce_get_create_msg [radeon]] *ERROR* radeon: failed to schedule ib (-12).
Nov 02 20:55:43 simendsjo-macbook kernel: [drm:radeon_vce_ib_test [radeon]] *ERROR* radeon: failed to get create msg (-12).
Nov 02 20:55:43 simendsjo-macbook kernel: [drm:radeon_ib_ring_tests [radeon]] *ERROR* radeon: failed testing IB on ring 7 (-12).
Nov 02 20:55:43 simendsjo-macbook X[941]: (EE) modeset(0): failed to set mode: Permission denied
```

## Technical details

* System: 17.09.1927.6a0a00d91e (Hummingbird)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: 17.09.1965.c567ec632e
* Sandboxing enabled: true

**Comment by gebner** [comment] 2017-11-02 21:19
This is probably related to @vcunat's mesa upgrade to 17.1.10 in a7dbf725257b82e65a5b54bbd902a184e80e2ade, and I guess it's the same bug as #30188, which was fixed by upgrading to 17.2.2 in #30196.

I think we need to backport the 17.2.2 upgrade as well then..

**Comment by vcunat** [comment] 2017-11-02 21:58
I'm sorry, that was careless of me.  I'm not yet certain whether to revert to 17.1.8 or go forward to some 17.2.x version.  Looking at usage in distributions, I can't see 17.1 branch &ndash; they use either 17.2 or 17.0 or some older one.

**Comment by vcunat** [comment] 2017-11-03 08:13
17.2.2 is on master since Oct 15, so major issues probably would have been noticed by now and it should be OK, but on the other hand it would be a non-minor bump without any clear advantage I know of (wrt. 17.1.8).  /cc 17.09 managers for another opinion @globin, @fpletz.

**Comment by hlandau** [comment] 2017-11-04 06:58
Since this is an actual breaking change, fixing it is rather urgently desirable. Might be better just to rollback without waiting for feedback, and decide whether to upgrade later.

**Comment by vcunat** [comment] 2017-11-04 08:53
@hlandau: yes, I would have pushed one of the two options immediately if Hydra wasn't busy recompiling _security_ updates (or if the whole revert didn't involve a nontrivial rebuild).

**Comment by vcunat** [comment] 2017-11-05 07:52
Revert now contained in the latest nixos-17.09 channel.

**Comment by vcunat** [comment] 2017-11-05 07:53
Thanks for reporting this!

**Closed by vcunat** 2017-11-05 07:52 UTC
Labels: 0.kind: regression

**Comment by simendsjo** [comment] 2017-11-07 15:23
Seems like it's related to the login manager. Switching to slim worked.

**Comment by vcunat** [comment] 2017-11-07 15:55
@simendsjo: yes, as I wrote, I reverted it ;-)

**Comment by elaOnMars** [comment] 2018-04-26 20:33
I can confirm this issue. I have
radeon 0000:01:00.0: ring 0 stalled for more than 6354732 msec 
running in the background tty.
It is a fresh NixOS 18.03.132083.06c576b0525 (Impala) installation on an AMD system.
What can I do?
