### ISSUE TITLE
Atom can not delete files

### ISSUE THREAD

**Issue by Gerschtli** [NixOS/nixpkgs#97233] opened 2020-09-05 14:32 UTC
**Describe the bug**
It is not possible to delete files in atom.

**To Reproduce**
1. Open `atom`
2. Try to delete a file

**Expected behavior**
This action should not result in an error.

**Notify maintainers**
@offlinehacker @nequissimus @ysndr

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.61, NixOS, 20.03.2862.925ae0dee63 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200721_ff314f1`
 - channels(root): `"home-manager-20.03, nixos-20.03.2862.925ae0dee63, nur-gerschtli, unstable-20.09pre239318.c59ea8b8a0e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- atom
- atom-beta
# a list of nixos modules affected by the problem
module:
```

**Comment by jtojnar** [comment] 2020-09-05 15:10
gvfs-trash has been removed for a few years after several years of deprecation period.

For the atom issue, this is likely a duplicate of https://github.com/NixOS/nixpkgs/issues/60000

**Comment by Gerschtli** [comment] 2020-09-15 20:17
Ah thank you for this, I will update the title and description accordingly

**Comment by jtojnar** [comment] 2020-09-15 20:24
You can try installing `glib` globally. That contains `gio trash` command which some programs support.

**Closed** 2021-01-23 21:58 UTC
Labels: 0.kind: bug
