### ISSUE TITLE
Build failure: sapling

### ISSUE THREAD

**Issue by develop7** [NixOS/nixpkgs#326861] opened 2024-07-13 16:50 UTC
### Steps To Reproduce

1. `nix -v profile upgrade sapling`

### Expected

`sapling` is downloaded from binary cache, as it always was before.

### What happens instead

Build dependencies are downloaded and `sapling` is building locally

### Build log

https://gist.github.com/develop7/81a63f79c655d4141f7b3cfe2316b056

### Additional context

Fails in hydra as well: https://hydra.nixos.org/build/266337169/nixlog/2

### Notify maintainers

@pbar @thoughtpolice 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯  nix-shell -p nix-info --run "nix-info -m"                                                                                                                                                                                        2024-07-13 14:53
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/5nlrrxmz0qj3a685j2p4hlmqp907x9rs-nix-info
copying path '/nix/store/5nlrrxmz0qj3a685j2p4hlmqp907x9rs-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.7-1-default, openSUSE Tumbleweed, noversion, nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.21.2`
 - channels(root): `""`
 - nixpkgs: `/nix/store/038zs5b21569pjv6v0dwhi6fd95jbzvx-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-07-14 02:43
dupe of #326455

**Closed by eclairevoyant** 2024-07-14 02:43 UTC
Labels: 0.kind: build failure
