### ISSUE TITLE
Package request: Nexus Mods App

### ISSUE THREAD

**Issue by ardishco-the-great** [NixOS/nixpkgs#285121] opened 2024-01-30 23:47 UTC
**Project description**
A mod installer, creator and manager for all your popular games

**Metadata**

* homepage URL: https://github.com/Nexus-Mods/NexusMods.App
* source URL: https://github.com/Nexus-Mods/NexusMods.App
* license: gpl3+
* platforms: linux

**Comment by jopejoe1** [comment] 2024-01-31 00:04
Duplicate of #270358

**Closed by jopejoe1** 2024-01-31 00:04 UTC
Labels: 0.kind: packaging request
