### ISSUE TITLE
lumina is broken since 18.09

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#61481] opened 2019-05-14 03:54 UTC
## Issue description

```Lumina``` exits in a few seconds after start, just after showing MOTD, probably crashes.
The last ```NixOS``` it worked was ```18.03```

### Steps to reproduce

```js
services.xserver = {
  enable = true;
  resolutions = [ { x = 1024; y = 768; } ];
  displayManager.auto.enable = true;
  desktopManager.lumina.enable = true;
};
```

## Technical details

reproducible with
https://github.com/NixOS/nixpkgs/archive/release-18.09.tar.gz
https://github.com/NixOS/nixpkgs/archive/release-19.03.tar.gz
https://github.com/NixOS/nixpkgs/archive/master.tar.gz

**Comment by romildo** [comment] 2020-05-23 11:39
@volth Can you check if https://github.com/NixOS/nixpkgs/pull/88675 fixes this issue?

**Comment by petabyteboy** [comment] 2020-05-23 11:59
I can confirm the issue is fixed by using libsForQt mkDerivation.

**Closed by petabyteboy** 2020-05-23 11:59 UTC
