### ISSUE TITLE
pytest (pytest_30 and pytest_32) fail to build on Python 3.5

### ISSUE THREAD

**Issue by vanschelven** [NixOS/nixpkgs#29301] opened 2017-09-13 07:53 UTC
On the current master, trying to build the python package `pytest` fails because of failing tests:

Python 3.5 & pytest_32 (the current default) and pytest_30 fail to build, all other available versions of pytest build fine (it seems that the tests aren't being run at all for those) on Python 3.5.

On Python 3.6 I am able to build all available versions of pytest without any problems.

I have not (extensively) tried to reproduce this for older versions of Python.

* System: NixOS
* Master, on cd286d4d28883ee676815d6f5465432009f66dd4

**Comment by vanschelven** [comment] 2017-09-13 07:55
Pinging the maintainers of pytest, @domenkozar @lovek323 @madjar @lsix

**Comment by FRidh** [comment] 2017-09-13 08:32
> it seems that the tests aren't being run at all for those

Due to a circular test dependency.

I am unable to reproduce your issue. `pytest_30` and `pytest_32` seem to build fine here with Python 3.5 on NixOS at cd286d4.

**Comment by vanschelven** [comment] 2017-09-13 09:28
[This is what it looks like for me](https://github.com/NixOS/nixpkgs/files/1298905/trace.txt) with Python 3.5 and pytest_32.

**Comment by FRidh** [comment] 2017-09-13 09:34
Can you run
```
$ nix-build https://github.com/NixOS/nixpkgs/archive/cd286d4d28883ee676815d6f5465432009f66dd4.tar.gz -A python35.pkgs.pytest_32
unpacking ‘https://github.com/NixOS/nixpkgs/archive/cd286d4d28883ee676815d6f5465432009f66dd4.tar.gz’...
/nix/store/kkq8ycn3s46ns6r7npd3yxl43kcdh2i2-python3.5-pytest-3.2.1
```
and confirm whether the output matches.

**Comment by vanschelven** [comment] 2017-09-13 09:42
The output matches - same problem.

**Comment by FRidh** [comment] 2017-09-13 09:46
What do you mean with that? If you indeed get `/nix/store/kkq8ycn3s46ns6r7npd3yxl43kcdh2i2-python3.5-pytest-3.2.1`, then there is no issue here in Nixpkgs, but then you were having a modified Nixpkgs yourself, possibly using overlays or other overrides.

Because I cannot reproduce your issue I am closing this.

**Closed by FRidh** 2017-09-13 09:46 UTC
Labels: 6.topic: python

**Comment by vanschelven** [comment] 2017-09-13 10:08
Clarification: the output (roughly) matches _with my earlier output_ (but not with yours), starting like so:

```
nix-build https://github.com/NixOS/nixpkgs/archive/cd286d4d28883ee676815d6f5465432009f66dd4.tar.gz -A python35.pkgs.pytest_32
downloading ‘https://github.com/NixOS/nixpkgs/archive/cd286d4d28883ee676815d6f5465432009f66dd4.tar.gz’... [11388/12232 KiB, 746.0 KiB/s]
unpacking ‘https://github.com/NixOS/nixpkgs/archive/cd286d4d28883ee676815d6f5465432009f66dd4.tar.gz’...
these derivations will be built:
  /nix/store/7pf98yliywv7fzldcbmljrs8yq0fsfls-python3.5-pytest-3.2.1.drv
```

I have just reproduced this with a fresh checkout of the nixpkgs source from git; i.e. doing a fresh clone from github followed by

```
nix-shell -K -I nixpkgs=. --show-trace --pure
```

My "base system" is NixOS 17.03; but it is my understanding that Nix/NixOS is designed precisely such that this doesn't/shoudn't matter.

I am not aware of any overlays or other overrides (the term was new to me, so I doubt I would have configured such things myself).

Is there a way to ensure all such mechanisms are turned off and cannot affect the build?

I have removed all channels from my system; whenever I build I build with a specific path to a checkout of `nixpkgs`.

**Comment by FRidh** [comment] 2017-09-13 10:15
There are two differences still that I could think of:
1. Sandbox. I build with the sandbox on, while I think the sandbox is turned off by default. However, regardless, the `.drv` file should be the same.
2. Nix version. I use 1.12pre and you're likely on the default 1.11. I am not sure whether this impacts `.drv`, but I don't think so otherwise most of our users wouldn't be able to use the binary cache (Hydra runs unstable Nix as well).

**Comment by vanschelven** [comment] 2017-09-13 10:39
Switching to sandboxed building fixes the problem - thanks!

I suppose that still leaves open the question on _why_, but that question doesn't quite interest me enough to keep researching.
