### ISSUE TITLE
Build failure: super-slicer-beta

### ISSUE THREAD

**Issue by Saturn745** [NixOS/nixpkgs#295754] opened 2024-03-14 01:04 UTC
### Steps To Reproduce

1. build *super-slicer-beta*

### Build log
https://gist.github.com/Saturn745/8f116859812c5382f53cfb5d660c9c88
```console
       > [ 30%] Built target semver
       > [ 30%] Linking CXX static library libavrdude.a
       > [ 30%] Built target avrdude
       > [ 30%] Building CXX object src/avrdude/CMakeFiles/avrdude-slic3r.dir/main-standalone.cpp.o
       > [ 31%] Linking CXX executable avrdude-slic3r
       > [ 31%] Built target avrdude-slic3r
       > make[2]: *** [src/libslic3r/CMakeFiles/libslic3r_cgal.dir/build.make:76: src/libslic3r/CMakeFiles/libslic3r_cgal.dir/MeshBoolean.cpp.o] Error 1
       > make[2]: *** Waiting for unfinished jobs....
       > make[1]: *** [CMakeFiles/Makefile2:1116: src/libslic3r/CMakeFiles/libslic3r_cgal.dir/all] Error 2
       > make: *** [Makefile:156: all] Error 2
       For full logs, run 'nix log /nix/store/gcaq32vwh3l4w42fqwsf187xhfmhzzvb-super-slicer-2.5.59.6.drv'.
```

### Notify maintainers
@cab404 @Moredread @hesiod

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.79, NixOS, 24.05 (Uakari), 24.05.20240224.73de017`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(galaxy): `"home-manager-23.05.tar.gz"`
 - nixpkgs: `/nix/store/gzv0nsm8d5js3wzq2mr1sv9lfp1iyail-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-03-14 01:21
duplicate of https://github.com/NixOS/nixpkgs/issues/294114

**Closed by eclairevoyant** 2024-03-14 01:21 UTC
Labels: 0.kind: build failure
