### ISSUE TITLE
Desktop launchers not accessible via GNOME until new login

### ISSUE THREAD

**Issue by segfault3** [NixOS/nixpkgs#86647] opened 2020-05-03 13:18 UTC
**Describe the bug**
When installing an application, I can't access its desktop launcher via GNOME (for example by searching for it via GNOME Shell's search) until I log out of GNOME and log in again.

**To Reproduce**
1. Install a new application. For example, I installed Thunderbird by adding it to `environment.systemPackages` in `/etc/nixos/configuration.nix` and running `sudo nixos-rebuild switch`.
2. Try to start Thunderbird via GNOME Shell by opening the GNOME Shell activities overview and typing "Thunderbird" into the search entry. Thunderbird is not found.
3. Log out of GNOME and back in again.
4. Repeat step 2, this time Thunderbird is found.

**Expected behavior**
Thunderbird should be found via the GNOME Shell search without having to log out and back in again.

**Comment by emilazy** [comment] 2020-05-03 13:20
cc @NixOS/gnome

**Comment by jtojnar** [comment] 2020-05-03 14:36
This is a duplicate of this long standing issue: https://github.com/NixOS/nixpkgs/issues/12757

IIRC, the gist is that when we have `/run/current-system/sw/share` in `XDG_DATA_DIRS` and do a configuration switch, the `sw` changes what it links to, but GNOME Shell keeps monitoring the place where `/run/current-system/sw/share/applications` pointed to before.

**Closed by jtojnar** 2020-05-03 14:36 UTC
Labels: 0.kind: bug
