### ISSUE TITLE
Package request: spotube

### ISSUE THREAD

**Issue by ilovethensa** [NixOS/nixpkgs#278668] opened 2024-01-04 10:06 UTC
**Project description**

An open source, cross-platform Spotify client compatible across multiple platforms
utilizing Spotify's data API and YouTube (or Piped.video or JioSaavn) as an audio source

**Metadata**

* homepage URL: https://spotube.krtirtho.dev/
* source URL: https://github.com/KRTirtho/spotube
* license: BSD-4-Clause
* platforms: linux, darwin, windows

**Comment by TomaSajt** [comment] 2024-01-06 10:27
Duplicate of https://github.com/NixOS/nixpkgs/issues/200120

**Closed** 2024-01-06 17:19 UTC
Labels: 2.status: duplicate, 0.kind: packaging request
