### ISSUE TITLE
Update Zotero 5 standalone client

### ISSUE THREAD

**Issue by nico202** [NixOS/nixpkgs#31479] opened 2017-11-10 11:15 UTC
@ttuegel hi, I'm tagging you since no mantainer is explicitly set, and I saw you did some PR on this.
Do you think upgrading to zotero 5 is doable?
Thanks, Nicolò

**Comment by nico202** [comment] 2017-11-10 11:17
on arch linux [1], they simply download the binary. Maybe is possible to manually build it, however
 [1] https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=zotero

**Comment by ttuegel** [comment] 2017-11-10 16:58
> I'm tagging you since no mantainer is explicitly set, and I saw you did some PR on this.

I used to be the maintainer for this package, but I haven't used Zotero in several years. 

As far as updating, it would be advisable to repackage the standalone client using `buildFHSUserEnv`.

**Comment by nico202** [comment] 2017-11-16 17:07
Fixed in the commit by @timor.
Thanks!

**Comment by nico202** [comment] 2017-11-21 09:01
I'm reopening this since opening external programs fails with 

> relocation error: /usr/lib/libc.so.6: symbol __tunable_get_val, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference

as in: 

```
/nix/store/mrw4x303zmfxcngggr1vnx38dn20b0i4-bash-4.4-p12/bin/bash: relocation error: /usr/lib/libc.so.6: symbol __tunable_get_val, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
/nix/store/07q5ay5psyi96lidy3i58lprc0s3mi6p-firefox-unwrapped-51.0.1/lib/firefox-51.0.1/firefox: relocation error: /usr/lib/libc.so.6: symbol __tunable_get_val, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
/nix/store/07q5ay5psyi96lidy3i58lprc0s3mi6p-firefox-unwrapped-51.0.1/lib/firefox-51.0.1/firefox: relocation error: /usr/lib/libc.so.6: symbol __tunable_get_val, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference

```

**Comment by jluttine** [comment] 2017-11-21 12:01
Do you know if this supports Zotero extensions/plugins like Zotfile? I suppose they'd need to be packaged for nix and then somehow made available for Zotero. Would be nice to have Zotfile.

**Comment by nico202** [comment] 2017-11-21 12:02
I installed betterbibtex and zotfile and they do work indeed

**Comment by timor** [comment] 2017-11-21 12:03
@nico202 Can you provide instructions to reproduce the error?

**Comment by nico202** [comment] 2017-11-21 13:22
@timor I just opened it (it used my zotero 4-firefox plugin directory automatically), double click on a pdf file, open with: /home/USERNAME/.nix-profile/bin/okular
or right click: open folder -> with /home/USERNAME/.nix-profile/bin/pcmanfm

**Comment by timor** [comment] 2017-11-23 08:24
@nico202 Hmm, sorry. I use a similar setup, with evince instead of okular, and opening files works for me.  I would try to change it to okular for testing, but I don't know how to make it ask again for the path...

**Comment by nico202** [comment] 2017-11-23 09:05
@timor the same happens for me when zotero tries to open firefox when opening links from zotero, too. Firefox and zotero are added to the profile with nix-env -f ./nixpkgs/ -i {zotero,firefox} using the master checkout.

zotero --help does not show the help, and zotero -P does not open the profile manager, so I don't know how to try a clean profile.

Also, I don't know how to set the plugin directory. I think it's using the firefox one (my library was inside zotero-firefox before having to move to standalone).

**Comment by timor** [comment] 2017-11-23 09:24
@nico202 Maybe this has to do with your library location then?  I have had my library separate, and my standalone installation does not seem to have picked up my plugins.

I think that standalone zotero should actually be working without knowing anything about your day-to-day firefox.  As far as I understand, they basically ship their own version of the firefox internals with zotero.  Maybe it is some kind of conflict between these two?

**Comment by nico202** [comment] 2017-11-23 09:44
I think so. But I don't know how to let it forget about my old profile.

The bin is the right one: ls -lah $(which zotero) -> /nix/store/sp6ixxhsly25jaycwcx5rxfy4af5ykbh-zotero-5.0.25/bin/zotero

Renamed the the library dir (inside firefox) and rename ~/.zotero.

> /nix/store/07q5ay5psyi96lidy3i58lprc0s3mi6p-firefox-unwrapped-51.0.1/lib/firefox-51.0.1/firefox: relocation error: /usr/lib/libc.so.6: symbol __tunable_get_val, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference

I don't even know why it is calling firefox 51.

However, extensions get installed correctly (tried with https://github.com/retorquere/zotero-better-bibtex)

**Comment by timor** [comment] 2017-11-23 10:25
@nico202 Can you try the following:
1. run `less $(which zotero) and note the location of the `zotero-fhs-env` script location
2. run that script without any arguments to enter the chroot
3. start firefox from there manually (e.g. /run/current-system/bin/firefox or the path to your custom profile)

**Comment by nico202** [comment] 2017-11-23 10:29
@timor zotero-fhs-env-chrootenv:IITaudio@lenovo:~$firefox -> works

**Comment by timor** [comment] 2017-11-23 10:33
@nico202 Ok, no idea then.  Could you create a new user and see if it works then?  I think we don't know yet whether this is related to your profile or the zotero installation.

**Comment by jluttine** [comment] 2018-02-21 18:41
I'm unable to open PDFs with Okular from Zotero. I get the following error:
```
This application failed to start because it could not find or load the Qt platform plugin "xcb" in "".
```

When opening the PDF and choosing an app for opening the file, I choose `/run/current-system/sw/bin/okular` (because `which okular` points there). Any ideas? I guess it could be fixed by installing Okular to my home directory with nix-env but I wouldn't want to do that.

**Comment by timor** [comment] 2018-02-26 14:07
@jluttine 
This may be related to #30977. For me, the only way to get okular working correctly (independently from zotero) right now is having it installed via nix-env into my personal profile, btw.

**Comment by jluttine** [comment] 2018-02-26 14:08
Ok. Okular works for me outside of zotero, but I have it installed in system packages.

**Comment by plumps** [comment] 2018-05-18 10:27
There seems to be an issue with the zotero and a missing **libX11-xcb.so.1** atm:

```
/nix/store/7jwflsnyg92p8x31h9dxpyl4xx70vhak-zotero-fhs-env/bin/zotero-fhs-env /nix/store/pn5gywigh5fcm4pjlmzc19ky5qfxfdw0-zotero-5.0.35.1-pkg/bin/zotero
XPCOMGlueLoad error for file /nix/store/pn5gywigh5fcm4pjlmzc19ky5qfxfdw0-zotero-5.0.35.1-pkg/data/libxul.so:
libX11-xcb.so.1: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```

**Comment by schmittlauch** [comment] 2018-11-13 07:06
#48814 seems to be the specific issue about not being able to open content in Zotero using external programs.
So I suggest closing this issue in favor of the more specific one.

**Comment by schmittlauch** [comment] 2020-02-04 10:31
@ttuegel This can be closed

**Closed** 2020-06-11 04:51 UTC
Labels: 9.needs: package (update)
