### ISSUE TITLE
Emacs: providing ImageMagick support

### ISSUE THREAD

**Issue by Anton-Latukha** [NixOS/nixpkgs#70631] opened 2019-10-07 14:27 UTC
### Describe the bug

For support of `imagemagick`, which is allows a lot of picture and even gif abilities, picture previews, in Emacs - pretty handy stuff - it is needed to overload Emacs closure and as so - compile it only for enabling that.

### To Reproduce

Install Emacs.

Run any `imagemagic` related feature.

Observe that there is no support of it.

### Observed behavior

```
helm-M-x: Emacs with ‘imagemagick’ support is required. (libmagickcore, libmagickwand, --with-imagemagick)
```

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.75, NixOS, 20.03pre194293.2436c27541b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos, unstable-20.03pre194293.2436c27541b"`
 - channels(pyro): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Anton-Latukha** [comment] 2019-10-07 14:32
I just wanted to analyze myself and hear the thoughts on that.

Probably I would just transform this issue into Emacs linkage issue.

**Comment by Anton-Latukha** [comment] 2019-10-07 15:31
@matthewbauer Please say a word.

Should I include `--with-imagemagic` and extend Emacs with real Imagemagic support.
Since it would grow the closure, but really enable ImageMagic and extend image and preview support in Emacs.

I made a diff between nix-store closures. List what is new to Emacs from ImageMagic:
```
bzip2
coreutils
djvulibre
fftw
gcc
ilmbase
imagemagick
lcms2
libde265
libwebp
libXt
openexr
openjpeg
xz
```

It seems not that big a grow.

What you would say, powerful by default (include in `withX`), or customizable (`withImageMagic`).

**Comment by Anton-Latukha** [comment] 2019-10-07 16:01
With GCC in ImageMagic created a report: https://github.com/NixOS/nixpkgs/issues/70647, it would be solved in time.

**Comment by Anton-Latukha** [comment] 2019-10-08 18:30
@jwiegley Good day, John.
Sorry to bother you, you are the maintainer that was last active regarding Emacs.

What do you think about the two messages above: https://github.com/NixOS/nixpkgs/issues/70631#issuecomment-539070404

**Comment by jwiegley** [comment] 2019-10-08 18:42
I would like to see ImageMagick support included.

**Comment by matthewbauer** [comment] 2019-10-08 20:58
So I suspect the issue is that "shrink-rpath" is removing imagemagick from the RPATH. A quick fix is to add "dontPatchELF" to the Emacs derivation. PatchELF should skip anything that has the DT_NEEDED flag set. Something must be off with ImageMagick that it doesn't get that flag.

One trick you can do to add imagemagick without recompiling is by setting ```LD_LIBRARY_PATH``` to the imagemagick directory. Something like ```LD_LIBRARY_PATH=$(nix-build '<nixpkgs>' -A imagemagick)/lib```. I've wondered if setting ```LD_LIBRARY_PATH=/run/current-system/sw/lib``` globally would be a good idea? It would probably be controversial and result in bad contamination though.

**Comment by Anton-Latukha** [comment] 2019-10-08 23:45
Ok. I decided that raising `lib` question is a very dead horse topic. I also contradicted myself there, I've seen `imagemagick` already a build-dep in code, and wrote description thinking its support is already enabled, but there is no `--with-imagemagick` set in code, so I do not know why it is done so.

**Comment by Anton-Latukha** [comment] 2019-10-08 23:48
@jwiegley @matthewbauer 
I rewrote & downscaled the issue to Emacs stuff.

I'm doing `imagemagick` because there is a Telegram client in Emacs: https://github.com/zevlg/telega.el, which is, funny enough, objectively superior to all other Telegram desktop clients includding official, superior by implemented Telegram features.

Mainly I just want to be able to message people without waking them up. But that it is in Emacs is a bonus.

**Comment by cab404** [comment] 2020-01-01 21:35
It looks like this can be closed safely, there's 
```nix
pkgs.emacs.override { imagemagick = pkgs.imagemagickBig; }
```

which adds imagemagick support (at least it works for telega). @Anton-Latukha, can you try it?

**Comment by costrouc** [comment] 2020-01-02 15:57
@cab404 this works for me. I was using home manager and set `program.emacs.package = pkgs.emacs.override { imagemagick = pkgs.imagemagickBig; }`.

To easily check if this worked the following elisp should return `t`

```elisp
(image-type-available-p 'imagemagick)
```

**Comment by Anton-Latukha** [comment] 2020-04-19 09:36
@cab404

You mentioned, "at least it works for telega".

'cuz I tried some time ago, `telega` server failed to build on NixOS. As an example, `telega` upstream doc mentions:

> It will install headers to /usr/local/include and library itself into /usr/local/lib. These paths are hardcoded in telega.el.

Is it working for you on NixOS and how you achieved it?

**Comment by cab404** [comment] 2020-04-19 11:49
@Anton-Latukha

> Is it working for you on NixOS and how you achieved it?

https://gitlab.com/cab404/nixos-config/-/blob/a7eaa0990fa9f1cda1e383ef2d01403a2b2aaf26/home.nix

13, 61, 260
It's pretty much the same in system config

**Comment by Anton-Latukha** [comment] 2020-04-19 21:30
@cab404

Aha.

Thanks.

**Comment by cab404** [comment] 2020-04-20 13:22
> @cab404
> 
> Aha.
> 
> Thanks.

So, that worked?

**Comment by Anton-Latukha** [comment] 2020-04-20 18:11
@cab404

Kind of...

Telega starts to intialize. But fails with error code:

```
error in process filter: telega--authorization-ready: TDLib version=1.5.0 < 1.6.0 (min required), please upgrade TDLib and recompile ‘telega-server’
error in process filter: TDLib version=1.5.0 < 1.6.0 (min required), please upgrade TDLib and recompile ‘telega-server’
```

I'm sitting on the current `nixos-unstable` and current TDLib is 1.6.0.

So it seems state in the link you provided needs additionally an old TDLib.

I would try up-to-date `emacsPackages.telega`, as you did now. I was puzzled before, and now I  now know that Emacs uses both own package repo as also Emacs packages installed through NixOS. I've seen today that NixOS Emacs in `package-directory-list` from the get-go already provides a proper NixOS path to find provided Emacs NixPkgs.

**Comment by tazjin** [comment] 2020-08-04 12:25
@moritzschaefer Does that actually solve the problem for you?

I use EXWM (but [not through the module](https://cs.tvl.fyi/depot@94387dbc25e350b56f3ba1c63145ff2ed4c3f43b/-/blob/users/tazjin/nixos/frog/default.nix#L178-189)) and haven't been able to get [my Emacs](https://cs.tvl.fyi/depot/-/blob/users/tazjin/emacs/default.nix) to reliably build with ImageMagick support at all.

**Comment by moritzschaefer** [comment] 2020-08-04 13:47
@tazjin The code from the PR above #94648 does work for me!

**Comment by adisbladis** [comment] 2021-02-25 12:05
> This issue is also affecting emacs when using EXWM.

How is this affecting exwm in any way?

**Comment by moritzschaefer** [comment] 2021-02-25 12:32
@adisbladis When working with image-buffer (e.g. zooming).

**Comment by adisbladis** [comment] 2021-02-27 11:45
Since it's disabled by default upstream and `emacs.override { withImageMagick = true; }` now works ( fixed in https://github.com/NixOS/nixpkgs/pull/114348 ) I'm going to close this.

**Closed by adisbladis** 2021-02-27 11:45 UTC
Labels: 0.kind: bug
