### ISSUE TITLE
Awesomewm: LD_LIBRARY_PATH handed down to Subprocesses

### ISSUE THREAD

**Issue by makefu** [NixOS/nixpkgs#14164] opened 2016-03-23 15:01 UTC
## Basic info
- Kernel: Linux vbob 4.4.2 #1-NixOS SMP Wed Feb 17 20:31:25 UTC 2016 x86_64 GNU/Linux
- System: 16.03.git.40c586b (Emu)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 16.09.git.40c586b
## Describe your issue here

When subprocesses are being started by awesome-wm they will inherit the complete wrapped environment of the window manager. 

```
$ cat /run/current-system/sw/bin/awesome
export LUA_CPATH="/nix/store/pc0lrj04hp54syzqgfiba8gk7lm7byk2-lgi-0.7.2/lib/lua/5.2/?.so"${LUA_CPATH:+;}$LUA_CPATH
export LUA_PATH="/nix/store/pc0lrj04hp54syzqgfiba8gk7lm7byk2-lgi-0.7.2/share/lua/5.2/?.lua;/nix/store/pc0lrj04hp54syzqgfiba8gk7lm7byk2-lgi-0.7.2/share/lua/5.2/lgi/?.lua"${LUA_PATH:+;}$LUA_PATH
export GI_TYPELIB_PATH=/nix/store/n131myci13cns1q7x9a74awxqfpgqw3p-pango-1.38.1/lib/girepository-1.0:/nix/store/rbqrkq5g4yd6s6s67plqlg8yi65cy63i-gdk-pixbuf-2.32.3/lib/girepository-1.0:/nix/store/n2m8mk36686iilfq96r0hqpcjyhfdi78-gobject-introspection-1.46.0/lib/girepository-1.0:/nix/store/n131myci13cns1q7x9a74awxqfpgqw3p-pango-1.38.1/lib/girepository-1.0${GI_TYPELIB_PATH:+:}$GI_TYPELIB_PATH
export LD_LIBRARY_PATH=/nix/store/m0cp2r2n81k8277nf4v34iyp767fizwm-cairo-1.14.4/lib:/nix/store/n131myci13cns1q7x9a74awxqfpgqw3p-pango-1.38.1/lib:/nix/store/n2m8mk36686iilfq96r0hqpcjyhfdi78-gobject-introspection-1.46.0/lib${LD_LIBRARY_PATH:+:}$LD_LIBRARY_PATH
export PATH=/nix/store/xsi1z8b9yzg5znhqb7d2azywc1g5dh16-compton-0.1_beta2/bin:/nix/store/k6i5lmhz6y0gbz7bs7xrbr1wrp7cqf7p-unclutter-8/bin:/nix/store/3scdfmawm938iss0cxkqh1hw9vq1qr2s-procps-3.3.11/bin:/nix/store/f2z68wfywh4h31g9jpz4qizh9yr9kzr3-iproute2-4.3.0/sbin:/nix/store/78rzgch6q4x60frjh88095spyqpb8n12-coreutils-8.24/bin:/nix/store/1m46ywl6ca7h8a2j8rzcfnpw63694661-curl-7.47.1/bin:/nix/store/fpbcbaz0d1ksr8jvsvjga2ahdnbnks1p-alsa-utils-1.1.0/bin:/nix/store/xgnmdv1mq5l0pwr1jsp7dcwk4imzg341-findutils-4.4.2/bin:/nix/store/r7p17q7sq46p75lrahx23kvxqxrc3p3z-xterm-320/bin${PATH:+:}$PATH
exec -a "$0" /nix/store/794qxrmq3jfhhafnls5wlqqsj78lsv2p-awesome-3.5.8/bin/.awesome-wrapped "${extraFlagsArray[@]}" "$@"
```
### Expected result

When processes are started under awesome, the `basic` environment should be used. LD_LIBRARY_PATH should not contain explicit paths to /nix/store. My specific problem was  that i was unable to start pidgin after installing it via `nix-env` because of the error message `pidgin: symbol lookup error: /nix/store/n131myci13cns1q7x9a74awxqfpgqw3p-pango-1.38.1/lib/libpangoft2-1.0.so.0: undefined symbol: hb_buffer_set_cluster_level`
### Actual result

When a new terminal (urxvt+zsh in my case) is started the new shell will contains this environment, LD_LIBRARY_PATH being the most critical here because when new tools are installed via `nix-env` the LD_LIBRARY_PATH may not necessarily match.
### Steps to reproduce
1. Enable xserver with awesome enable:

```
  services.xserver = {
    enable = true;

    windowManager = {
      awesome.enable = true;
      awesome.luaModules = [ pkgs.luaPackages.vicious ];
      default = "awesome";
    };

    desktopManager.xterm.enable = false;
  };
   environment.systemPackages = [ pkgs.rxvt_unicode-with-plugins ];
```
1. start GUI, and open a new shell `WIN+r urxvt`

```
$ echo $LD_LIBRARY_PATH
/nix/store/m0cp2r2n81k8277nf4v34iyp767fizwm-cairo-1.14.4/lib:/nix/store/n131myci13cns1q7x9a74awxqfpgqw3p-pango-1.38.1/lib:/nix/store/n2m8mk36686iilfq96r0hqpcjyhfdi78-gobject-introspection-1.46.0/lib:/run/opengl-driver/lib:/run/opengl-driver-32/lib
# this actually may only contain /run/opengl-driver/lib:/run/opengl-driver-32/lib 
```

**Comment by vcunat** [comment] 2016-05-23 11:20
/cc maintainer @lovek323.

I expect the worst can be avoided easily by using patchelf+`RPATH` instead of `$LD_LIBRARY_PATH`.

**Comment by makefu** [comment] 2016-07-25 08:47
@vcunat , sorry for the late reply.
i tried to use `RPATH` instead of `LD_LIBRARY_PATH` but then awesome does not boot up anymore. Any other idea how to solve this?

**Comment by makefu** [comment] 2017-12-19 10:43
Update: the problem persists unfortunately and it breaks software from old nixpkgs when you try to run it because awesomewm spills cairo,gobject,pango and sane, as well as `/run/opengl-driver/lib` into the library path

**Comment by psychon** [comment] 2017-12-19 11:13
> i tried to use RPATH instead of LD_LIBRARY_PATH but then awesome does not boot up anymore. Any other idea how to solve this?

Well, why not? Which library is not found? Why doesn't `dlopen` look in `RPATH` as it should?

For the list of environment variables given in the first comment (assuming the goal is to get rid of as many of them as possible):
```
export LUA_CPATH="/nix/store/pc0lrj04hp54syzqgfiba8gk7lm7byk2-lgi-0.7.2/lib/lua/5.2/?.so"${LUA_CPATH:+;}$LUA_CPATH
export LUA_PATH="/nix/store/pc0lrj04hp54syzqgfiba8gk7lm7byk2-lgi-0.7.2/share/lua/5.2/?.lua;/nix/store/pc0lrj04hp54syzqgfiba8gk7lm7byk2-lgi-0.7.2/share/lua/5.2/lgi/?.lua"${LUA_PATH:+;}$LUA_PATH
```
The above can be replaced with passing `--search /nix/store/pc0lrj04hp54syzqgfiba8gk7lm7byk2-lgi-0.7.2/lib/lua/5.2/ --search /nix/store/pc0lrj04hp54syzqgfiba8gk7lm7byk2-lgi-0.7.2/share/lua/5.2/lgi/` to awesome (needs at least v4.1, I think).
```
export GI_TYPELIB_PATH=/nix/store/n131myci13cns1q7x9a74awxqfpgqw3p-pango-1.38.1/lib/girepository-1.0:/nix/store/rbqrkq5g4yd6s6s67plqlg8yi65cy63i-gdk-pixbuf-2.32.3/lib/girepository-1.0:/nix/store/n2m8mk36686iilfq96r0hqpcjyhfdi78-gobject-introspection-1.46.0/lib/girepository-1.0:/nix/store/n131myci13cns1q7x9a74awxqfpgqw3p-pango-1.38.1/lib/girepository-1.0${GI_TYPELIB_PATH:+:}$GI_TYPELIB_PATH
```
Sorry, I don't know much about gobject-introspection myself, but I guess this env var cannot be easily avoided.

For LD_LIBRARY_PATH:
- cairo is loaded through `dlopen()` (through gobject-introspection) and `man dlopen` says that it should respect `DT_RPATH` tags.
- Same for pango
- Awesome itself does not use gobject-introspection. Assuming that lgi is properly built (=finds gobject-introspection on its own), I don't see why this entry is necessary at all.

That leaves `$PATH` for which I also don't think it is necessary, but I guess this was done for convenience so that "this random set of tools" is found via `$PATH` from the user's config.

**Comment by makefu** [comment] 2017-12-19 11:28
@psychon thanks! i will test `DT_RPATH` and `--search` for awesomewm this evening

**Comment by vcunat** [comment] 2017-12-19 11:44
Yes, extending RPATH through patchelf does (generally) work for `dlopen`.

**Comment by psychon** [comment] 2017-12-19 15:10
Okay, I took a closer look and installed NixOS in qemu. As a first try, without modifying anything, the following command worked to start awesome (yes, I'm running this as root; line breaks added for readability):
```
env -i \
GI_TYPELIB_PATH=$GI_TYPELIB_PATH \
LD_LIBRARY_PATH=/nix/store/5mx1*cairo-1.14.10/lib \
HOME=/root \
DISPLAY=:1 \
/nix/store/2gi6wif*awesome-4.2/bin/.awesome-wrapped \
--search /nix/store/72v*lgi-0.9.1/lib/lua/5.2/ \
--search /nix/store/72v*lgi-0.9.1/share/lua/5.2/
```
So getting rid of `LUA_PATH` and `LUA_CPATH` seems to work.
(And yes, most stuff is already in RPATH, apparently.)

I then used `patchelf` to add that `LD_LIBRARY_PATH` to awesome's rpath and... that did not work...
According to `strace`, only `/nix/store/*glib-2.52.3/lib/libcairo-gobject.so.2`, `/nix/store/*pcre-8.41/lib/libcairo-gobject.so.2`, and `/nix/store/g1g31ah*-glibc-2.25-49/lib/libcairo-gobject.so.2` are checked, no other paths are searched?! Who pulled in pcre and why is the RPATH ignored?!? This is a completely different search path that is being applied.
Looking at `gobject-introspection` and `glib`, the code here does some weird dances, but in the end just calls `dlopen("libcairo-gobject.so.2")` which then fails, for whatever reason.

Out of a hunch, I checked `DT_RPATH` for `/nix/store/1nv*gobject-introspection-1.52.1/lib/libgirepository-1.0.so` and this at least contains a subset of the search path that is being used. No idea how `DT_RPATH` on binary and on shared library are combined, but apparently one overwrites the other?
@vcunat Thoughts?

**Comment by vcunat** [comment] 2017-12-19 16:21
Does `patchelf --print-rpath` show what you would expect?  There's an automatic patchelf run in fixup phase, so it's typically best to add `postFixup` where you `--print-rpath` and extend it by some more paths.

**Comment by psychon** [comment] 2017-12-20 09:07
@vcunat I have not much clue about NixOS, so I did not built my own awesome package. Instead I literally did what I said above: I copied the binary built by NixOS to `/root/awesome` and used `patchelf` on that. Hence, I'm quite certain that the automatic patchelf run in fixup phase did not affect this at all.
Instead, it seems like `dlopen()` is sensitive to its caller: When called from the main binary, the RPATH (actually, RUNPATH) of the binary is used, while when called from a shared object, only that object's settings are used?! Google doesn't really find any documentation on this...

I just copied `libgmodule-2.0.so.0` to `/root/`, too, and used `patchelf` to append the directory containing `libcairo-gobject.so.2` to its RPATH (well, RUNPATH). Then I replaced the `LD_LIBRARY_PATH` from my previous comment with `LD_LIBRARY_PATH=.` (= make awesome use the patched `libgmodule-2.0.so.0`). With this I was able to run awesome without any "real" `$LD_LIBRARY_PATH`.

I don't know how to incorporate this into NixOS. I guess you do not want to make glib (which is where `libgmodule-2.0.so.0` comes from) depend on cairo, so...
You could patch awesome to `dlopen("libcairo-gobject.so.2")` at the beginning of `main()`. This is ugly, but could work.

The above raises a question for me: Does `libgmodule` work on NixOS? From the above analysis, it should pretty much always fail to find libraries, unless they appear in `$LD_LIBRARY_PATH`?!

**Comment by vcunat** [comment] 2017-12-20 15:59
I'm not sure, but it seems very likely that for `dlopen` only R(UN)PATH of the _original_ executable is considered.  (The `dlopen` call will hardly be trying to find which part of code called it.)

**Comment by psychon** [comment] 2017-12-20 16:20
@vcunat Here's the line in `dlopen` that gets the instruction pointer in the caller:
https://sources.debian.org/src/glibc/2.23-1/dlfcn/dlopen.c/#L84
And here is the line of code that seems to translate that into a loaded library:
https://sources.debian.org/src/glibc/2.24-12/elf/dl-open.c/?hl=598#L222
The resulting handle is then passed to `_dl_map_object`:
https://sources.debian.org/src/glibc/2.24-12/elf/dl-open.c/?hl=598#L237
...which accesses things like `->l_info[DT_RUNPATH]`:
https://sources.debian.org/src/glibc/2.24-12/elf/dl-load.c/?hl=867#L2271

So yes, I have not actually tried this in a self-contained example, but to me it looks like `dlopen` only checks the `DT_RUNPATH` of the object that called it. So, for loading `libcairo-gobject.so.2`, the RUNPATH in the `awesome` binary is ignored, because `dlopen` is called from `libgmodule`.
This also fits with my other experiment above: When adding the path to `libcairo-gobject.so.2` to the binaries's `DT_RUNPATH`, the library is still not found. When adding the path to `libgmodule-2.0.so.0`'s `DT_RUNPATH`, everything starts working.

**Comment by psychon** [comment] 2018-01-19 11:01
> (The dlopen call will hardly be trying to find which part of code called it.)

@vcunat Here is a blog post that says that the above is exactly what happens (section "Why does this happen?", the part with "Unless loading object has RUNPATH").
And [here](https://gist.github.com/psychon/c7625ea030e3d78f09b1a709fd2d0bc7) is a self-contained Makefile which (at least here on Fedora) reproduces the problem: With `-Wl,--disable-new-dtags` or no such option at all, my `ld` generates a `DT_RPATH` and everything works. With `-Wl,--enable-new-dtags`, the call to `dlopen` fails, with "No such file or directory", because the `DT_RUNPATH` of the executable is not used.

What else do you need to be convinced?
Could someone now please acknowledge that all `dlopen`-wrappers are (semi-)broken on NixOS?

The only fix for this bug that I see is to use RPATH instead of RUNPATH everywhere (or at least for awesome and the glib `dlopen`-wrapper).

**Closed** 2018-02-03 10:03 UTC

**Comment by makefu** [comment] 2018-02-03 11:29
i am really glad that this issue got solved! thanks to everyone involved

**Comment by vcunat** [comment] 2018-02-04 09:37
Thanks for digging into these mechanisms.
