### ISSUE TITLE
akonadi doesn't start

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#8900] opened 2015-07-20 08:59 UTC
Hi there

I'm trying to run KMail/Kontact on KDE4 but Akonadi just seems to refuse to run. I have - among others -those packages installed:

        kde4.akonadi
        kde4.applications
        kde4.kdeadmin
        kde4.kdeaccessibility
        kde4.kdebase_workspace
        kde4.kdebindings
        kde4.kdegames
        kde4.kdegraphics
        kde4.kdelibs
        kde4.kdenetwork
        kde4.kdepim
        kde4.kdepim_runtime
        kde4.kdepimlibs
        kde4.kdesdk
        kde4.kdevelop
        kde4.kdevplatform
        kde4.kdewebdev
        kde4.kde_baseapps
        kde4.kde_base_artwork
        kde4.kde_wallpapers
        kde4.konversation
        kde4.kdemultimedia
        kde4.kdeplasma_addons
        kde4.networkmanagement
        kde4.oxygen_icons
        kde4.kdeutils

When I just run akonadictl start from the cli I get this output: https://paste.debian.net/284072/

From what I see on lines 51-57 there's seems to be an issue with MariaDB.

As regard to MySQL/MariaDB I have in my configuration.nix:

    # Enable mysql
    services.mysql = {
        enable = true;
        dataDir = "/var/mysql";
        user = "mysql";
        package = pkgs.mysql;
    };

**Comment by wkennington** [comment] 2015-07-20 09:45
Yeah, you need my changes in #8494

**Comment by domenkozar** [comment] 2015-10-02 23:49
duplicate of https://github.com/NixOS/nixpkgs/issues/1053

**Closed by domenkozar** 2015-10-02 23:49 UTC
