### ISSUE TITLE
"kvm version too old" when building disk image for aarch64

### ISSUE THREAD

**Issue by randomnetcat** [NixOS/nixpkgs#151157] opened 2021-12-18 04:24 UTC
### Describe the bug
When using `nixos/lib/make-disk-image.nix` for a nixpkgs with `system = "aarch64-linux"`, the build fails with the following last lines:
```
[    1.719357] NET: Registered protocol family 10
[    1.728039] Segment Routing with IPv6
[    1.728493] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    1.738766] Btrfs loaded, crc32c=crc32c-generic
[    1.741102] Warning: unable to open an initial console.
[    1.742254] This architecture does not have kernel memory protection.
[    1.742308] Run /init as init process
[    1.799241] EXT4-fs (vda1): mounted filesystem with ordered data mode. Opts: 
[    2.136294] random: fast init done
[    9.636343] random: crng init done
[   81.723629] reboot: Restarting system
WARNING: Image format was not specified for 'nixos.raw' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
kvm version too old
.qemu-system-aarch64-wrapped: failed to initialize kvm: Function not implemented
error: builder for '/nix/store/mpwc4pjm0wjf5vqkqmlyh347f5jk32bf-nixos-disk-image.drv' failed with exit code 1;
```

### Steps To Reproduce

With `<nixpkgs>` referring to nixpkgs commit `a2e281f5770247855b85d70c43454ba5bff34613` (HEAD on `nixos-unstable` at the time of writing), the following reproduces the issue:
```
{ pkgs ? import <nixpkgs> { system = "aarch64-linux"; } }:

import (pkgs.path + "/nixos/lib/make-disk-image.nix") {
  inherit pkgs;
  inherit (pkgs) lib;

  config = (import (pkgs.path + "/nixos/lib/eval-config.nix") {
    system = "aarch64-linux";
    modules = [
      ({ pkgs, lib, ... }: {
        config = {
          boot.loader.grub.device = "/dev/sda";

          fileSystems = {
            "/" = {
              device = "/dev/vda1";
              fsType = "ext4";
            };
          };
        };
      })
    ];
  }).config;
}
```

### Expected behavior
The build succeeds, producing a disk image with a nixos installation.

### Screenshots
N/A

### Additional context
N/A

### Notify maintainers

@talyz appears to be the last person to touch this (I'm very sorry if you're the wrong person to notify)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.84, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `""`
 - channels(randomcat): `""`
 - nixpkgs: `/run/active-nixpkgs-source`
```

(`/run/active-nixpkgs-source` is a symlink to `/nix/store/ydkfjk5v61jw0xvlzxcsfw7x59shzp4y-source`)

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- "virtualisation/google-compute-image.nix"
- "virtualisation/hyperv-image.nix"
- "virtualisation/digital-ocean-image.nix"
- "virtualisation/azure-image.nix"
- "virtualisation/vmware-image.nix"
- "virtualisation/proxmox-image.nix
- "virtualisation/virtualbox-image.nix"
```

(I have not double checked that all of those modules are affected, but they are the ones that use `make-disk-image.nix`.

**Comment by talyz** [comment] 2021-12-18 13:35
Sure, I can take a stab at this. I don't think there's really any one maintainer of this file anyway :)

I'm able to build this fine on a remote `aarch64` builder. I had to modify the configuration slightly, but I never saw the issue you're describing.

Here is the one I used:
```nix
{ pkgs ? import <nixpkgs> { system = "aarch64-linux"; } }:

import (pkgs.path + "/nixos/lib/make-disk-image.nix") {
  inherit pkgs;
  inherit (pkgs) lib;

  partitionTableType = "efi";

  config = (import (pkgs.path + "/nixos/lib/eval-config.nix") {
    system = "aarch64-linux";
    modules = [
      ({ pkgs, lib, ... }: {
        config = {
          boot.loader.systemd-boot.enable = true;

          fileSystems = {
            "/" = {
              device = "/dev/vda1";
              fsType = "ext4";
            };
          };
        };
      })
    ];
  }).config;
}
```

What system are you building this on? Your listed system is `x86_64-linux`, so you're using a remote builder for this, I assume? Does it have a working kvm setup?

**Comment by talyz** [comment] 2021-12-19 12:19
Aha, I see. I hadn't tried out `binfmt` myself, but did now and it's very cool indeed. I'm also able to reproduce your issue, so it's definitely because of it the build fails. However, I get the same error when building anything that relies on kvm virtualization, such as the NixOS tests. Did that use to work previously?

My guess is that it has to do with nested kvm virtualization not working / being supported. I don't know if it ever did or if it's supposed to, though. I think we can at least conclude that the error is not with `make-disk-image.nix`.

**Comment by randomnetcat** [comment] 2021-12-19 17:47
> However, I get the same error when building anything that relies on kvm virtualization, such as the NixOS tests. Did that use to work previously?

I had forgotten that those used KVM, so I didn't think to try them, and I've never run them before so I have no idea if they used to work.

> I think we can at least conclude that the error is not with make-disk-image.nix.
Thanks for all your help! And sorry for roping you into this when that wasn't the root cause.

**Comment by talyz** [comment] 2021-12-19 19:18
No problem! I'll close this, then. Feel free to open a new issue for the root cause, if you think it's something that should work.

**Closed by talyz** 2021-12-19 19:18 UTC
Labels: 0.kind: bug

**Comment by RaitoBezarius** [comment] 2022-12-25 22:13
Just hit this on my laptop using binfmt.
