### ISSUE TITLE
Package request: pantsbuild/pants

### ISSUE THREAD

**Issue by Moortiii** [NixOS/nixpkgs#278722] opened 2024-01-04 15:46 UTC
**Project description**

Pants is a tool for working effectively with monorepos, focusing primarily on Python. They also ship with support for Go, Java and Scala. It is designed for fast, consistent, ergonomic builds using aggressive caching and fine-grained invalidation. One of the lead developers describes Pants as "Cargo for Python".

**Metadata**

* homepage URL: https://www.pantsbuild.org/
* source URL: https://github.com/pantsbuild/pants
* license: Apache 2.0
* platforms: linux x86_64, linux_arm64, macos_x86_64, macos_arm64
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by tomodachi94** [comment] 2024-11-10 02:12
Closing as a duplicate of #294330, since the other issue has more discussion.

**Closed by tomodachi94** 2024-11-10 02:12 UTC
Labels: 0.kind: packaging request
