### ISSUE TITLE
Discourse-assets Blocks a System Update / Unstable Channel

### ISSUE THREAD

**Issue by Obikawa** [NixOS/nixpkgs#130140] opened 2021-07-13 23:17 UTC
**Describe the bug**
```
builder for '/nix/store/d643awr7ibza1ag0sr3bm8cmic0cakyg-discourse-assets-2.7.4.drv' failed with exit code 1; last 10 log lines:
        9: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/setup.rb:20:in `block in <top (required)>'
      8: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler.rb:149:in `setup'
       7: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/runtime.rb:20:in `setup'
        6: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/runtime.rb:91:in `block in definition_method'
           5: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/definition.rb:240:in `requested_specs'
          4: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/definition.rb:258:in `specs_for'
        3: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/definition.rb:189:in `specs'
    2: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/spec_set.rb:90:in `materialize'
         1: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/spec_set.rb:90:in `map!'
  /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/spec_set.rb:95:in `block in materialize': Could not find libv8-node-15.14.0.1-x86_64-linux in any of the sources (Bundler::GemNotFound)
```

**To Reproduce**
I am not sure - this is an attempt to update after a couple of weeks.

**Expected behavior**
Update as usual.

**Screenshots**

**Additional context**
I have not updated the system for a few feeks.

**Notify maintainers**
@talyz 

**Metadata**
$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.45, NixOS, 21.11pre299942.09c38c29f2c (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.11pre301576.d8f8f31af9d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by talyz** [comment] 2021-07-22 06:00
This was caused by the latest bundler upgrade and fixed in #129464.

**Closed by talyz** 2021-07-22 06:00 UTC
Labels: 0.kind: bug
