### ISSUE TITLE
Cross-compiling nixos for armv6l failing to build File-ShareDir

### ISSUE THREAD

**Issue by ilyakooo0** [NixOS/nixpkgs#112173] opened 2021-02-06 17:26 UTC
**Describe the bug**

I am trying to cross-compile nixos for the raspberry pi. Trying to do so leads to an error while trying to build `/nix/store/7x07kg9jvw7y1zxl2crk7lv4d73hmv0a-perl5.32.0-File-ShareDir-1.116-armv6l-unknown-linux-gnueabihf.drv`.

The error is this:

```
Can't load module IO, dynamic loading not available in this perl.
  (You may need to build a new perl executable which either supports
  dynamic loading or has the IO module statically linked into it.)
 at /nix/store/gjikgqfwbfgdavg5cm2nl2isgqj9xzwf-perl-5.32.0-armv6l-unknown-linux-gnueabihf/lib/perl5/5.32.0/armv6l-linux/IO/Handle.pm line 268.
Compilation failed in require at /nix/store/gjikgqfwbfgdavg5cm2nl2isgqj9xzwf-perl-5.32.0-armv6l-unknown-linux-gnueabihf/lib/perl5/5.32.0/armv6l-linux/IO/Handle.pm line 268.
BEGIN failed--compilation aborted at /nix/store/gjikgqfwbfgdavg5cm2nl2isgqj9xzwf-perl-5.32.0-armv6l-unknown-linux-gnueabihf/lib/perl5/5.32.0/armv6l-linux/IO/Handle.pm line 268.
Compilation failed in require at /nix/store/gjikgqfwbfgdavg5cm2nl2isgqj9xzwf-perl-5.32.0-armv6l-unknown-linux-gnueabihf/lib/perl5/5.32.0/armv6l-linux/IO/Seekable.pm line 100.
BEGIN failed--compilation aborted at /nix/store/gjikgqfwbfgdavg5cm2nl2isgqj9xzwf-perl-5.32.0-armv6l-unknown-linux-gnueabihf/lib/perl5/5.32.0/armv6l-linux/IO/Seekable.pm line 100.
Compilation failed in require at /nix/store/gjikgqfwbfgdavg5cm2nl2isgqj9xzwf-perl-5.32.0-armv6l-unknown-linux-gnueabihf/lib/perl5/5.32.0/armv6l-linux/IO/File.pm line 132.
BEGIN failed--compilation aborted at /nix/store/gjikgqfwbfgdavg5cm2nl2isgqj9xzwf-perl-5.32.0-armv6l-unknown-linux-gnueabihf/lib/perl5/5.32.0/armv6l-linux/IO/File.pm line 132.
Compilation failed in require at inc/latest/private.pm line 10.
BEGIN failed--compilation aborted at inc/latest/private.pm line 10.
Compilation failed in require at inc/latest.pm line 5.
Compilation failed in require at Makefile.PL line 18.
BEGIN failed--compilation aborted at Makefile.PL line 18.
```

I am using the nix expression from this repository: https://github.com/ilyakooo0/rasnixos.

**To Reproduce**
1. `git clone https://github.com/ilyakooo0/rasnixos.git`
2. `cd rasnixos`
3. `nix-build -j auto --argstr system x86_64-linux`

**Expected behavior**
Everything builds without error.

**Comment by MetaDark** [comment] 2021-02-07 15:47
This is the same problem reported in https://github.com/NixOS/mobile-nixos/issues/284, but a fix still hasn't been found.

**Comment by MetaDark** [comment] 2021-02-07 17:46
I narrowed down the regression to a0d34c753b85e8207510f0e4d9001906250973e4. It looks like the new `buildInputs` are the cause of the failure. Before that `File-ShareDir` wasn't a dependency.

**Comment by stigtsp** [comment] 2021-02-07 20:56
Hi!

a0d34c7 was reverted by 33fd4153ccaf390df83a0400b7fd71833d6ba903 (in #110908) it's currently in staging-next. I hope this fixes the issue.

**Comment by MetaDark** [comment] 2021-02-07 21:02
Thanks for the heads up @stigtsp! I was able cross compile with a0d34c7 reverted, so it should be fixed once it's merged to master.

**Comment by flokli** [comment] 2021-02-08 12:23
This also affects aarch64 cross compilation:

```
builder for '/nix/store/g3bacm74bdrk1pga8smxja10rh1g508b-perl5.32.0-File-ShareDir-1.118-aarch64-unknown-linux-gnu.drv' failed with exit code 255
# running Build.PL --prefix /nix/store/fnn2l9mp4b4jl1ainvk9ah50dlwmdqin-perl5.32.0-Module-Build-0.4231-aarch64-unknown-linux-gnu --installdirs site --config perl=/nix/store/6i92b6cwh4hqhykjc723wpvav8xqkhin-perl-5.32.0-aarch64-unknown-linux-gnu-mini/bin/perl --fullperl "/nix/store/n76dvh71a0kmbh1nxgf0x3n82cmiqvvk-perl-5.32.0/bin/perl"
Checking prerequisites...
  test_requires:
    !  Couldn't find a $VERSION in prerequisite File::Temp

Checking optional features...
inc_bundling_support....disabled
  requires:
    ! inc::latest is not installed

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
of the modules indicated above before proceeding with this installation

Attempt to reload Scalar/Util.pm aborted.
Compilation failed in require at /nix/store/2bm3hqd4cvrjks5vlmps7d4mz2awgw8j-perl-5.32.0-aarch64-unknown-linux-gnu/lib/perl5/5.32.0/aarch64-linux/Data/Dumper.pm line 304.
Couldn't run Build.PL: No such file or directory at lib/Module/Build/Compat.pm line 341.
builder for '/nix/store/4ga0br1ylnflgn08f64xc2kyvlz6hd7k-perl5.32.0-Module-Build-0.4231-aarch64-unknown-linux-gnu.drv' failed with exit code 2
```

**Closed** 2021-02-18 07:50 UTC
Labels: 0.kind: bug, 6.topic: cross-compilation

**Comment by korfuri** [comment] 2022-07-22 20:17
It seems that 3edf750956f235aee8c4a1f06fbb80bb096d92c9 reintroduced the breakage. That commit was immediately followed by 6308561c52d606e6a8a78f5c1106b679767a899b which is a security update, so I'm assuming it's not a good idea to revert. I'm poking at this now but I'm very unfamiliar with Perl, so I opened #182502 to follow up.
