### ISSUE TITLE
Unable to build `llvmPackages_10` on Darwin Catalina

### ISSUE THREAD

**Issue by afontaine** [NixOS/nixpkgs#89313] opened 2020-06-01 15:40 UTC
**Describe the bug**

Trying to use `llvmPackages_10` on MacOS 10.15 triggers compilation of the tools, which fail.

**To Reproduce**
1. `nix-shell -p llvmPackages_10`
2. Patience
3. 💥 

**Expected behavior**

A nix-shell with `llvmPackages_10` to be available.

**Stacktrace**

```
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
these derivations will be built:
  /nix/store/jdydng668hfb1wxrjyvnh83nnrpkvbq2-compiler-rt-10.0.0.drv
  /nix/store/py4n741v4mqz08n0l264ij2d5w76lqgd-clang-wrapper-10.0.0.drv
  /nix/store/m8yvik7h94fv9fqlmrh7a2874drg6saf-stdenv-darwin.drv
building '/nix/store/jdydng668hfb1wxrjyvnh83nnrpkvbq2-compiler-rt-10.0.0.drv'...
unpacking sources
unpacking source archive /nix/store/w51mccg34ly4sdj0zhjnq9c0fh6ghaka-compiler-rt-10.0.0.src.tar.xz
source root is compiler-rt-10.0.0.src
setting SOURCE_DATE_EPOCH to timestamp 1584975662 of file compiler-rt-10.0.0.src/www/menu.html.incl
patching sources
applying patch /nix/store/3mzkrxhsy3fp1w87x23q2v00x8mgcq8x-compiler-rt-codesign.patch
patching file cmake/Modules/AddCompilerRT.cmake
Hunk #1 succeeded at 321 with fuzz 2 (offset 111 lines).
applying patch /nix/store/m73sg79cxv8gwarncm1lq2jkkl0zb8n0-find-darwin-sdk-version.patch
patching file cmake/Modules/CompilerRTDarwinUtils.cmake
configuring
fixing cmake files...
cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_BUILD_RPATH=ON -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/store/ax0pvnybjqscmgn13mrbrb775qg25x2r-compiler-rt-10.0.0/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/ax0pvnybjqscmgn13mrbrb775qg25x2r-compiler-rt-10.0.0/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/ax0pvnybjqscmgn13mrbrb775qg25x2r-compiler-rt-10.0.0/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/ax0pvnybjqscmgn13mrbrb775qg25x2r-compiler-rt-10.0.0/share/doc/ -DCMAKE_INSTALL_INFODIR=/nix/store/ax0pvnybjqscmgn13mrbrb775qg25x2r-compiler-rt-10.0.0/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/ax0pvnybjqscmgn13mrbrb775qg25x2r-compiler-rt-10.0.0/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/bpcmx75i6xwy6w2y6wrj18qw25w3rj0g-compiler-rt-10.0.0-dev/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/bpcmx75i6xwy6w2y6wrj18qw25w3rj0g-compiler-rt-10.0.0-dev/include -DCMAKE_INSTALL_SBINDIR=/nix/store/ax0pvnybjqscmgn13mrbrb775qg25x2r-compiler-rt-10.0.0/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/ax0pvnybjqscmgn13mrbrb775qg25x2r-compiler-rt-10.0.0/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/ax0pvnybjqscmgn13mrbrb775qg25x2r-compiler-rt-10.0.0/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_SYSROOT= -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_FIND_FRAMEWORK=last -DCMAKE_STRIP=/nix/store/6vlz4ls90ag1m6dqm91mwnx0v78sbcb7-cctools-binutils-darwin-927.0.2/bin/strip -DCMAKE_RANLIB=/nix/store/6vlz4ls90ag1m6dqm91mwnx0v78sbcb7-cctools-binutils-darwin-927.0.2/bin/ranlib -DCMAKE_AR=/nix/store/6vlz4ls90ag1m6dqm91mwnx0v78sbcb7-cctools-binutils-darwin-927.0.2/bin/ar -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=/nix/store/ax0pvnybjqscmgn13mrbrb775qg25x2r-compiler-rt-10.0.0 -DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON -DCMAKE_C_COMPILER_TARGET=x86_64-apple-darwin -DCMAKE_ASM_COMPILER_TARGET=x86_64-apple-darwin 
-- The C compiler identification is Clang 7.1.0
-- The CXX compiler identification is Clang 7.1.0
-- The ASM compiler identification is Clang
-- Found assembler: /nix/store/l2vllq68666k0h4ydc7y12qqvs26ysay-clang-wrapper-7.1.0/bin/clang
-- Check for working C compiler: /nix/store/l2vllq68666k0h4ydc7y12qqvs26ysay-clang-wrapper-7.1.0/bin/clang
-- Check for working C compiler: /nix/store/l2vllq68666k0h4ydc7y12qqvs26ysay-clang-wrapper-7.1.0/bin/clang - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /nix/store/l2vllq68666k0h4ydc7y12qqvs26ysay-clang-wrapper-7.1.0/bin/clang++
-- Check for working CXX compiler: /nix/store/l2vllq68666k0h4ydc7y12qqvs26ysay-clang-wrapper-7.1.0/bin/clang++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for unwind.h
-- Looking for unwind.h - found
-- Looking for rpc/xdr.h
-- Looking for rpc/xdr.h - not found
CMake Warning at cmake/base-config-ix.cmake:113 (message):
  Detected OSX_SYSROOT does not exist
Call Stack (most recent call first):
  CMakeLists.txt:31 (include)


-- Found PythonInterp: /nix/store/mifia80k0frxaq68c7g1m3apmdz47f9j-python3-3.7.7/bin/python (found version "3.7.7") 
-- Looking for fopen in c
-- Looking for fopen in c - found
-- Looking for __gcc_personality_v0 in gcc_s
-- Looking for __gcc_personality_v0 in gcc_s - not found
-- Performing Test COMPILER_RT_HAS_NODEFAULTLIBS_FLAG
-- Performing Test COMPILER_RT_HAS_NODEFAULTLIBS_FLAG - Success
-- Performing Test COMPILER_RT_HAS_FFREESTANDING_FLAG
-- Performing Test COMPILER_RT_HAS_FFREESTANDING_FLAG - Success
-- Performing Test COMPILER_RT_HAS_STD_C11_FLAG
-- Performing Test COMPILER_RT_HAS_STD_C11_FLAG - Success
-- Performing Test COMPILER_RT_HAS_FPIC_FLAG
-- Performing Test COMPILER_RT_HAS_FPIC_FLAG - Success
-- Performing Test COMPILER_RT_HAS_FPIE_FLAG
-- Performing Test COMPILER_RT_HAS_FPIE_FLAG - Success
-- Performing Test COMPILER_RT_HAS_FNO_BUILTIN_FLAG
-- Performing Test COMPILER_RT_HAS_FNO_BUILTIN_FLAG - Success
-- Performing Test COMPILER_RT_HAS_FNO_EXCEPTIONS_FLAG
-- Performing Test COMPILER_RT_HAS_FNO_EXCEPTIONS_FLAG - Success
-- Performing Test COMPILER_RT_HAS_FOMIT_FRAME_POINTER_FLAG
-- Performing Test COMPILER_RT_HAS_FOMIT_FRAME_POINTER_FLAG - Success
-- Performing Test COMPILER_RT_HAS_FUNWIND_TABLES_FLAG
-- Performing Test COMPILER_RT_HAS_FUNWIND_TABLES_FLAG - Success
-- Performing Test COMPILER_RT_HAS_FNO_STACK_PROTECTOR_FLAG
-- Performing Test COMPILER_RT_HAS_FNO_STACK_PROTECTOR_FLAG - Success
-- Performing Test COMPILER_RT_HAS_FNO_SANITIZE_SAFE_STACK_FLAG
-- Performing Test COMPILER_RT_HAS_FNO_SANITIZE_SAFE_STACK_FLAG - Success
-- Performing Test COMPILER_RT_HAS_FVISIBILITY_HIDDEN_FLAG
-- Performing Test COMPILER_RT_HAS_FVISIBILITY_HIDDEN_FLAG - Success
-- Performing Test COMPILER_RT_HAS_FRTTI_FLAG
-- Performing Test COMPILER_RT_HAS_FRTTI_FLAG - Success
-- Performing Test COMPILER_RT_HAS_FNO_RTTI_FLAG
-- Performing Test COMPILER_RT_HAS_FNO_RTTI_FLAG - Success
-- Performing Test COMPILER_RT_HAS_FNO_FUNCTION_SECTIONS_FLAG
-- Performing Test COMPILER_RT_HAS_FNO_FUNCTION_SECTIONS_FLAG - Success
-- Performing Test COMPILER_RT_HAS_STD_CXX14_FLAG
-- Performing Test COMPILER_RT_HAS_STD_CXX14_FLAG - Success
-- Performing Test COMPILER_RT_HAS_FTLS_MODEL_INITIAL_EXEC
-- Performing Test COMPILER_RT_HAS_FTLS_MODEL_INITIAL_EXEC - Success
-- Performing Test COMPILER_RT_HAS_FNO_LTO_FLAG
-- Performing Test COMPILER_RT_HAS_FNO_LTO_FLAG - Success
-- Performing Test COMPILER_RT_HAS_MSSE3_FLAG
-- Performing Test COMPILER_RT_HAS_MSSE3_FLAG - Success
-- Performing Test COMPILER_RT_HAS_MSSE4_2_FLAG
-- Performing Test COMPILER_RT_HAS_MSSE4_2_FLAG - Success
-- Performing Test COMPILER_RT_HAS_SYSROOT_FLAG
-- Performing Test COMPILER_RT_HAS_SYSROOT_FLAG - Success
-- Performing Test COMPILER_RT_HAS_MCRC_FLAG
-- Performing Test COMPILER_RT_HAS_MCRC_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FNO_PARTIAL_INLINING_FLAG
-- Performing Test COMPILER_RT_HAS_FNO_PARTIAL_INLINING_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FVISIBILITY_INLINES_HIDDEN_FLAG
-- Performing Test COMPILER_RT_HAS_FVISIBILITY_INLINES_HIDDEN_FLAG - Success
-- Performing Test COMPILER_RT_HAS_GR_FLAG
-- Performing Test COMPILER_RT_HAS_GR_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_GS_FLAG
-- Performing Test COMPILER_RT_HAS_GS_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_MT_FLAG
-- Performing Test COMPILER_RT_HAS_MT_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_Oy_FLAG
-- Performing Test COMPILER_RT_HAS_Oy_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_GLINE_TABLES_ONLY_FLAG
-- Performing Test COMPILER_RT_HAS_GLINE_TABLES_ONLY_FLAG - Success
-- Performing Test COMPILER_RT_HAS_G_FLAG
-- Performing Test COMPILER_RT_HAS_G_FLAG - Success
-- Performing Test COMPILER_RT_HAS_Zi_FLAG
-- Performing Test COMPILER_RT_HAS_Zi_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WALL_FLAG
-- Performing Test COMPILER_RT_HAS_WALL_FLAG - Success
-- Performing Test COMPILER_RT_HAS_WERROR_FLAG
-- Performing Test COMPILER_RT_HAS_WERROR_FLAG - Success
-- Performing Test COMPILER_RT_HAS_WFRAME_LARGER_THAN_FLAG
-- Performing Test COMPILER_RT_HAS_WFRAME_LARGER_THAN_FLAG - Success
-- Performing Test COMPILER_RT_HAS_WGLOBAL_CONSTRUCTORS_FLAG
-- Performing Test COMPILER_RT_HAS_WGLOBAL_CONSTRUCTORS_FLAG - Success
-- Performing Test COMPILER_RT_HAS_WC99_EXTENSIONS_FLAG
-- Performing Test COMPILER_RT_HAS_WC99_EXTENSIONS_FLAG - Success
-- Performing Test COMPILER_RT_HAS_WGNU_FLAG
-- Performing Test COMPILER_RT_HAS_WGNU_FLAG - Success
-- Performing Test COMPILER_RT_HAS_WNON_VIRTUAL_DTOR_FLAG
-- Performing Test COMPILER_RT_HAS_WNON_VIRTUAL_DTOR_FLAG - Success
-- Performing Test COMPILER_RT_HAS_WVARIADIC_MACROS_FLAG
-- Performing Test COMPILER_RT_HAS_WVARIADIC_MACROS_FLAG - Success
-- Performing Test COMPILER_RT_HAS_WUNUSED_PARAMETER_FLAG
-- Performing Test COMPILER_RT_HAS_WUNUSED_PARAMETER_FLAG - Success
-- Performing Test COMPILER_RT_HAS_WCOVERED_SWITCH_DEFAULT_FLAG
-- Performing Test COMPILER_RT_HAS_WCOVERED_SWITCH_DEFAULT_FLAG - Success
-- Performing Test COMPILER_RT_HAS_WNO_PEDANTIC
-- Performing Test COMPILER_RT_HAS_WNO_PEDANTIC - Success
-- Performing Test COMPILER_RT_HAS_W4_FLAG
-- Performing Test COMPILER_RT_HAS_W4_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WX_FLAG
-- Performing Test COMPILER_RT_HAS_WX_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WD4146_FLAG
-- Performing Test COMPILER_RT_HAS_WD4146_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WD4291_FLAG
-- Performing Test COMPILER_RT_HAS_WD4291_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WD4221_FLAG
-- Performing Test COMPILER_RT_HAS_WD4221_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WD4391_FLAG
-- Performing Test COMPILER_RT_HAS_WD4391_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WD4722_FLAG
-- Performing Test COMPILER_RT_HAS_WD4722_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WD4800_FLAG
-- Performing Test COMPILER_RT_HAS_WD4800_FLAG - Failed
-- Looking for __func__
-- Looking for __func__ - found
-- Looking for dlopen in dl
-- Looking for dlopen in dl - found
-- Looking for shm_open in rt
-- Looking for shm_open in rt - not found
-- Looking for pow in m
-- Looking for pow in m - found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Looking for backtrace in execinfo
-- Looking for backtrace in execinfo - not found
-- Looking for setupterm in terminfo
-- Looking for setupterm in terminfo - not found
-- Looking for setupterm in tinfo
-- Looking for setupterm in tinfo - found
-- Looking for __cxa_throw in c++
-- Looking for __cxa_throw in c++ - found
-- Looking for __cxa_throw in stdc++
-- Looking for __cxa_throw in stdc++ - not found
-- Performing Test COMPILER_RT_HAS_Z_TEXT
-- Performing Test COMPILER_RT_HAS_Z_TEXT - Failed
-- Performing Test COMPILER_RT_HAS_FUSE_LD_LLD_FLAG
-- Performing Test COMPILER_RT_HAS_FUSE_LD_LLD_FLAG - Failed
-- Checking DARWIN_macosx_SYSROOT - ''
-- Checking DARWIN_iphonesimulator_SYSROOT - ''
-- Checking DARWIN_iphoneos_SYSROOT - ''
-- Checking DARWIN_watchsimulator_SYSROOT - ''
-- Checking DARWIN_watchos_SYSROOT - ''
-- Checking DARWIN_appletvsimulator_SYSROOT - ''
-- Checking DARWIN_appletvos_SYSROOT - ''
CMake Warning at cmake/config-ix.cmake:319 (message):
  Could not determine OS X sysroot, trying /var/empty/include
Call Stack (most recent call first):
  CMakeLists.txt:236 (include)


ERRORCould not detect OS X Sysroot. Either install Xcode or the Apple Command Line Tools
-- Performing Test COMPILER_RT_HAS_APP_EXTENSION
-- Performing Test COMPILER_RT_HAS_APP_EXTENSION - Success
-- Got ld supported ARCHES: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em (tvOS)
-- Toolchain supported arches: armv6;armv7;armv7s;arm64;arm64e;arm64_32;i386;x86_64;x86_64h;armv6m;armv7k;armv7m;armv7em;(tvOS)
-- Finding valid architectures for osx...
-- OSX supported arches: x86_64;x86_64h
-- Compiler-RT supported architectures: x86_64;x86_64h
-- Performing Test COMPILER_RT_HAS_VISIBILITY_HIDDEN_FLAG
-- Performing Test COMPILER_RT_HAS_VISIBILITY_HIDDEN_FLAG - Success
-- Performing Test COMPILER_RT_HAS_OMIT_FRAME_POINTER_FLAG
-- Performing Test COMPILER_RT_HAS_OMIT_FRAME_POINTER_FLAG - Success
-- Performing Test COMPILER_RT_HAS_FREESTANDING_FLAG
-- Performing Test COMPILER_RT_HAS_FREESTANDING_FLAG - Success
-- Performing Test COMPILER_RT_HAS_XRAY_COMPILER_FLAG
-- Performing Test COMPILER_RT_HAS_XRAY_COMPILER_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_ATOMIC_KEYWORD
-- Performing Test COMPILER_RT_HAS_ATOMIC_KEYWORD - Success
-- Checking DARWIN_macosx_SYSROOT - ''
-- Checking DARWIN_iphonesimulator_SYSROOT - ''
-- Checking DARWIN_iphoneos_SYSROOT - ''
-- Checking DARWIN_watchsimulator_SYSROOT - ''
-- Checking DARWIN_watchos_SYSROOT - ''
-- Checking DARWIN_appletvsimulator_SYSROOT - ''
-- Checking DARWIN_appletvos_SYSROOT - ''
-- OSX supported builtin arches: i386;i486;i586;i686;x86_64;x86_64h
-- Builtin supported architectures: i386;i486;i586;i686;x86_64;x86_64h
-- Performing Test COMPILER_RT_TARGET_HAS_ATOMICS
-- Performing Test COMPILER_RT_TARGET_HAS_ATOMICS - Success
-- Performing Test COMPILER_RT_TARGET_HAS_FCNTL_LCK
-- Performing Test COMPILER_RT_TARGET_HAS_FCNTL_LCK - Success
-- Performing Test COMPILER_RT_TARGET_HAS_UNAME
-- Performing Test COMPILER_RT_TARGET_HAS_UNAME - Success
-- Performing Test HAS_THREAD_LOCAL
-- Performing Test HAS_THREAD_LOCAL - Success
-- Configuring done
CMake Error at cmake/Modules/CompilerRTDarwinUtils.cmake:205 (add_library):
  No SOURCES given to target: clang_rt.builtins_i586_osx
Call Stack (most recent call first):
  cmake/Modules/CompilerRTDarwinUtils.cmake:303 (darwin_add_builtin_library)
  lib/builtins/CMakeLists.txt:570 (darwin_add_builtin_libraries)


CMake Error at cmake/Modules/CompilerRTDarwinUtils.cmake:205 (add_library):
  No SOURCES given to target: clang_rt.builtins_i486_osx
Call Stack (most recent call first):
  cmake/Modules/CompilerRTDarwinUtils.cmake:303 (darwin_add_builtin_library)
  lib/builtins/CMakeLists.txt:570 (darwin_add_builtin_libraries)


CMake Generate step failed.  Build files cannot be regenerated correctly.
builder for '/nix/store/jdydng668hfb1wxrjyvnh83nnrpkvbq2-compiler-rt-10.0.0.drv' failed with exit code 1
cannot build derivation '/nix/store/py4n741v4mqz08n0l264ij2d5w76lqgd-clang-wrapper-10.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/m8yvik7h94fv9fqlmrh7a2874drg6saf-stdenv-darwin.drv': 1 dependencies couldn't be built
error: build of '/nix/store/m8yvik7h94fv9fqlmrh7a2874drg6saf-stdenv-darwin.drv' failed
```

**Additional context**

This is all in an effort to [build `runit` on MacOS](https://discourse.nixos.org/t/unable-to-package-runit-on-macos/7419).

**Notify maintainers**

🤷 @LnL7 @ggreif 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.4.0, macOS 10.15.4`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.4`
 - channels(andrew): `"darwin, home-manager, nixpkgs-20.09pre226586.571212eb839"`
 - nixpkgs: `/Users/andrew/.nix-defexpr/channels/nixpkgs`
```

**Comment by ggreif** [comment] 2020-06-01 15:44
This looks like a duplicate of https://github.com/NixOS/nixpkgs/pull/87528. Any chance you can try the attached patch?

**Comment by afontaine** [comment] 2020-06-01 19:47
hey thanks for the fast response @ggreif! It does look that way, as compilation was successful.

I am not super familiar with the nixpkgs release process. How long does it take for recent patches to hit the `unstable` channel?

**Closed** 2020-06-01 19:56 UTC
Labels: 0.kind: bug, 6.topic: darwin

**Comment by LnL7** [comment] 2020-06-01 20:02
Large rebuilds like go through staging first, which is merged back in batches. This can take a while since that usually takes some work to stabilise regressions. But the last merge happened recently so it will be included in the next batch.
