### ISSUE TITLE
Perl scripts are run as shell after kernel upgrade

### ISSUE THREAD

**Issue by petrkr** [NixOS/nixpkgs#55705] opened 2019-02-13 13:47 UTC
After update kernel from 4.14.98 to 99 and also from 4.19.20 to 21 some perl scripts started write " line xxx: use: command not found"

git checkout release18.09 to commit after kernel update
nixos-rebuild -I nixpkgs=/path/to/git/version switch
reboot into it
open konsole and type any unknown command (easiest)
or
try nixos-rebuild, it will fails too

Problem occur on this commit a260b5dbd5cf4bc4060778e09392b01af63c7699 or a0ba6c2182677529f7002ddb9be3134dd6a0215c

also it fails in hydra's build log at bottom:
https://hydra.nixos.org/build/88723261/nixlog/1

regads Petr

**Comment by matthewbauer** [comment] 2019-02-13 18:34
Duplicate of https://github.com/NixOS/nixpkgs/issues/53672

**Closed by matthewbauer** 2019-02-13 18:34 UTC
Labels: 0.kind: bug, 6.topic: nixos
