### ISSUE TITLE
Document how to customize modules available to virtualenv

### ISSUE THREAD

**Issue by chaoflow** [NixOS/nixpkgs#66] opened 2012-07-20 17:53 UTC
see also #64

**Comment by geerds** [comment] 2015-03-26 10:10
There is a little difficulty combining `nix-shell` with `virtualenv`. I'm currently working on project which uses a specific version of the tornado web framework. Sadly not everyone use `nix` so we have a classic `requirements.txt` file with all the pinned dependencies. 

default.nix:
```
with import <nixpkgs> {}; {
  projectEnv = stdenv.mkDerivation {
    name = "project-env";
    buildInputs = [ stdenv python34 python34Packages.ipython python34Packages.virtualenv ];
    shellHook = ''
      [ -d venv ] && rm -r venv
      virtualenv --python=python3.4 venv
      . venv/bin/activate
      # "activate" doesn't work if it's the last command in the shellHook, so
      # we have to execute one more:
      true
    '';
  };
}
```

requirements.txt
```
# necessary modules during runtime
tornado==4.0.2
```

calling `nix-shell .` followed by a `pip freeze` shows that  `tornado==3.2` has been installed. This is due to `python34Packages.ipython` which depends on (an older) tornado version.

Is there a *workaround* for this? something like a lower priority for PYTHONPATH?

cc: @domenkozar

**Comment by domenkozar** [comment] 2015-03-26 11:27
That's a strange way of using virtualenv, if you can post a gist/git so that I can quickly reproduce the problem I can take a look.

**Comment by garbas** [comment] 2016-05-26 10:29
;) this is the oldest (still open) nixpkgs issue

**Comment by Azulinho** [comment] 2017-01-12 15:32
@jgeerds I also got a lot of trouble when I had to work on a python profile and attempted to get a virtualenv working inside a nix-shell, this particular default.nix worked for me:

``
with import <nixpkgs> {};
with pkgs.python27Packages;

buildPythonPackage { 
  name = "impurePythonEnv";
  buildInputs = [
    taglib
    openssl
    git
    libxml2
    libxslt
    libzip
    python27Full
    python27Packages.virtualenv
    python27Packages.pip
    stdenv
    zlib ];
  src = null;
  # When used as `nix-shell --pure`
  shellHook = ''
  unset http_proxy
  export GIT_SSL_CAINFO=/etc/ssl/certs/ca-bundle.crt
  virtualenv --no-wheel --no-setuptools venv 
  wget -c https://bootstrap.pypa.io/get-pip.py
  venv/bin/python get-pip.py
  venv/bin/pip install -r requirements.txt --no-use-wheel
  export PATH=$PWD/venv/bin:$PATH
  '';
  # used when building environments
  extraCmds = ''
  unset http_proxy # otherwise downloads will fail ("nodtd.invalid")
  export GIT_SSL_CAINFO=/etc/ssl/certs/ca-bundle.clr_white
  virtualenv venv
  venv/bin/pip install -r requirements.txt --no-use-wheel
  export PATH=$PWD/venv/bin:$PATH
  '';
}
``

**Comment by Azulinho** [comment] 2017-01-19 21:34
would the merge above ^  -> https://github.com/NixOS/nixpkgs/issues/21837 be enough to close this issue?

**Comment by LnL7** [comment] 2017-10-28 21:03
Fixed by https://github.com/NixOS/nixpkgs/pull/21837

**Closed by LnL7** 2017-10-28 21:03 UTC
Labels: 6.topic: python, old-label: documentation

**Comment by Azulinho** [comment] 2017-10-28 21:49
this was the oldest nixpkgs issue still open, next in line in https://github.com/NixOS/nixpkgs/issues/183
