### ISSUE TITLE
Package build fails: too many directories 

### ISSUE THREAD

**Issue by itkovian** [NixOS/nixpkgs#9707] opened 2015-09-07 21:53 UTC
I cannot install/build anything at this moment.

A dir that is created, for example:
~~~~
error (ignored): getting status of ‘/private/var/folders/dr/3fvg7z716x3118j15w2vyxw00000gn/T/nix-build-gnutar-1.28.drv-1/tar-1.28/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---’: File name too long
~~~~

Here's an example of a full dir structure

~~~~
/private/var/folders/dr/3fvg7z716x3118j15w2vyxw00000gn/T/nix-build-gnutar-1.28.drv-0/tar-1.28/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---
~~~~

I am on nix 1.10, nixpkgs commit-id 8f33b8cc93, on the staging branch, as per the fix that was introduced for the permissions flags in #9666. I am running OSX 10.11 public beta 6 (15A278b)

**Comment by dhess** [comment] 2015-09-11 23:16
I'm running OSX 10.11 GM, using master with 8f33b8c cherry-picked from staging, and I'm having the same problem with findutils.

This is really bad. I can't even delete the affected build directory because the path is too long.

**Comment by dhess** [comment] 2015-09-11 23:47
This does not appear to be related to 8f33b8c. I just reproduced it running OS X 10.11 GM on  master with 862900e reverted, and I'm running into the same problem, now with coreutils instead of findutils.

It's possible this is a 10.11 bug.

**Comment by dhess** [comment] 2015-09-12 00:32
Yep, same problem building findutils-4.4.2 from the tarball with Xcode tools. Many of the GNU utilities have an M4 macro that checks for getcwd problems during the configure process, and that's breaking. Anyway, this appears to be an upstream/vendor issue and not related to Nix.

**Comment by dhess** [comment] 2015-09-12 00:57
I've filed a Radar with Apple. Here's the Open Radar.

https://openradar.appspot.com/radar?id=6160634819379200

**Comment by dhess** [comment] 2015-09-12 02:03
As a workaround, you can skip the configure test that triggers the bug:

export gl_cv_func_getcwd_abort_bug="no"

I've hacked this into preHook in pkgs/stdenv/darwin/default.nix in my local tree.

**Comment by itkovian** [comment] 2015-09-13 14:06
Thanks a lot. I'll try this straight away.

**Comment by fundon** [comment] 2015-09-30 16:41
How to remove `confdir-14B`?

**Comment by dhess** [comment] 2015-09-30 19:39
@fundon I've tried all the command-line tricks I know and I still haven't been able to delete it. No word from Apple on my Radar submission, either, unfortunately.

**Comment by yegle** [comment] 2015-10-07 04:08
Holy...I got the same deep directory when trying to bootstrap a Gentoo Prefix...

**Comment by yegle** [comment] 2015-10-07 04:45
Finally find the solution:

```bash
while true
do
    mv confdir-14B---/confdir-14B--- a
    if [[ $? -ne 0 ]]
    then
        break
    fi
    rm -rf confdir-14B---
    mv a confdir-14B---
done
```

**Comment by grahamc** [comment] 2016-04-16 18:14
Can anyone confirm this issue still exists?

**Comment by dhess** [comment] 2016-04-21 20:05
I believe it was fixed in one of the El Cap updates. I haven't experienced it building Nix on Darwin recently.

**Closed** 2016-04-22 20:11 UTC
Labels: 6.topic: darwin
