### ISSUE TITLE
haskel: error build package insert-ordered-containers and uri-bytestring

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#53067] opened 2018-12-30 08:48 UTC
## Issue description
Error build package insert-ordered-containers

### Steps to reproduce
nixpkgs rev 6b1a429df33
nix build -f  ~/nixpkgs haskellPackages.insert-ordered-containers
```
builder for '/nix/store/c2vl0b6r6icrv2cnhzhsa9pzp2s1m7ry-insert-ordered-containers-0.2.1.0.drv' failed with exit code 1; last 10 log lines:
    die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:950:20 in Cabal-2.4.0.1:Distribution.Simple.Configure
    configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:460:12 in Cabal-2.4.0.1:Distribution.Simple.Configure
    configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:596:20 in Cabal-2.4.0.1:Distribution.Simple
    confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:67:5 in Cabal-2.4.0.1:Distribution.Simple.UserHooks
    configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:178:19 in Cabal-2.4.0.1:Distribution.Simple
    defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:115:27 in Cabal-2.4.0.1:Distribution.Simple
    defaultMain, called at Setup.hs:2:8 in main:Main
  Setup: Encountered missing dependencies:
  tasty >=0.10.1.2 && <1.2
```
nix build -f  ~/nixpkgs haskellPackages.uri-bytestring
```
builder for '/nix/store/7awm3all33j3gxn3xhlm13ykb90l1nkf-uri-bytestring-0.3.2.1.drv' failed with exit code 1; last 10 log lines:
          at test/URI/ByteString/Arbitrary.hs:(39,1)-(41,27)
      • In the second argument of ‘($)’, namely ‘SOP.hcpure p arbitrary’
        In the second argument of ‘($)’, namely
          ‘SOP.apInjs_POP $ SOP.hcpure p arbitrary’
        In the first argument of ‘oneof’, namely
          ‘(map SOP.hsequence $ SOP.apInjs_POP $ SOP.hcpure p arbitrary)’
     |
  42 | sopArbitrary' = oneof (map SOP.hsequence $ SOP.apInjs_POP $ SOP.hcpure p arbitrary)
     |                                                             ^^^^^^^^^^^^^^^^^^^^^^
  [2 of 4] Compiling URI.ByteStringQQTests ( test/URI/ByteStringQQTests.hs, dist/build/test/test-tmp/URI/ByteStringQQTests.o )
[0 built (1 failed)]
error: build of '/nix/store/7awm3all33j3gxn3xhlm13ykb90l1nkf-uri-bytestring-0.3.2.1.drv' failed

```
## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.12, NixOS, 19.03pre164359.60739e534d9 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2pre6526_9f99d624`
 - channels(root): `"nixos-19.03pre164359.60739e534d9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Izorkin** [comment] 2018-12-31 14:04
In nixpkg rev de0de8 normal build, in rev cb5bc3 - error.

**Comment by bb010g** [comment] 2019-01-06 08:36
insert-ordered-containers is fixed in https://github.com/phadej/insert-ordered-containers/commit/73fdf9c7a41ea7a02ee336cb01cb54f0ebc248f8 , but the new metadata revision hasn't been made on Hackage yet.

**Comment by swamp-agr** [comment] 2019-01-21 15:38
Same issue with `insert-ordered-containers` confirmed on Darwin: `tasty >=0.10.1.2 && <1.2`. During installation following line appeared:

```
Replace Cabal file with edited version from http://hackage.haskell.org/package/insert-ordered-containers-0.2.1.0/revision/9.cabal.
```

According to https://github.com/phadej/insert-ordered-containers/issues/27#issuecomment-450973496 version bump declined as an option. Is it possible to disable tests during package installation?

**Comment by wkral** [comment] 2019-02-05 17:09
Just noticed that #55108 was merged with a similar problem, it even seems to be from the same author with the policy of not pushing fixed test dependencies constraints. So it would seem that this library should be jailbroken until a new version is published.

I'll try to put a PR together for this fix in the next couple days but if someone wants to do it sooner, by all means. I'm not yet well versed in testing custom changes like that, been reading up though.

**Closed** 2019-02-09 10:17 UTC

**Comment by swamp-agr** [comment] 2019-02-09 20:10
Cool, thanks! Now it works!
