### ISSUE TITLE
nvidia driver broken in linuxPackages_latest

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#130620] opened 2021-07-19 08:57 UTC
I cannot update my `nixos-unstable` system any longer because `nvidia-x11-460.73.01-5.13.2` is broken. My machine uses the latest Linux kernel version and runs into these build errors:

~~~
  CC [M]  /build/kernel/nvidia-drm/nvidia-drm-gem-user-memory.o
/build/kernel/nvidia-drm/nvidia-drm-crtc.c:311:23: error: initialization of 'int (*)(struct drm_plane *, struct drm_atomic_state *)' from incompatible pointer type 'int (*)(struct drm_plane *, struct drm_plane_state *)' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wincompatible-pointer-types-Werror=incompatible-pointer-types8;;]
  311 |     .atomic_check   = nv_drm_plane_atomic_check,
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~
/build/kernel/nvidia-drm/nvidia-drm-crtc.c:311:23: note: (near initialization for 'nv_plane_helper_funcs.atomic_check')
/build/kernel/nvidia-drm/nvidia-drm-crtc.c:312:23: error: initialization of 'void (*)(struct drm_plane *, struct drm_atomic_state *)' from incompatible pointer type 'void (*)(struct drm_plane *, struct drm_plane_state *)' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wincompatible-pointer-types-Werror=incompatible-pointer-types8;;]
  312 |     .atomic_update  = nv_drm_plane_atomic_update,
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
/build/kernel/nvidia-drm/nvidia-drm-crtc.c:312:23: note: (near initialization for 'nv_plane_helper_funcs.atomic_update')
/build/kernel/nvidia-drm/nvidia-drm-crtc.c:313:23: error: initialization of 'void (*)(struct drm_plane *, struct drm_atomic_state *)' from incompatible pointer type 'void (*)(struct drm_plane *, struct drm_plane_state *)' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wincompatible-pointer-types-Werror=incompatible-pointer-types8;;]
  313 |     .atomic_disable = nv_drm_plane_atomic_disable,
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/kernel/nvidia-drm/nvidia-drm-crtc.c:313:23: note: (near initialization for 'nv_plane_helper_funcs.atomic_disable')
  CC [M]  /build/kernel/nvidia-drm/nvidia-drm-gem-dma-buf.o
cc1: some warnings being treated as errors
make[3]: *** [/nix/store/raiis134czq0ikrj7l7cl767pz0hnv3k-linux-5.13.2-dev/lib/modules/5.13.2/source/scripts/Makefile.build:273: /build/kernel/nvidia-drm/nvidia-drm-crtc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/build/kernel/nvidia-drm/nvidia-drm-modeset.c: In function '__will_generate_flip_event':
/build/kernel/nvidia-drm/nvidia-drm-modeset.c:96:23: warning: unused variable 'primary_plane' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wunused-variable-Wunused-variable8;;]
   96 |     struct drm_plane *primary_plane = crtc->primary;
      |                       ^~~~~~~~~~~~~
make[2]: *** [/nix/store/raiis134czq0ikrj7l7cl767pz0hnv3k-linux-5.13.2-dev/lib/modules/5.13.2/source/Makefile:1847: /build/kernel] Error 2
make[2]: Leaving directory '/nix/store/raiis134czq0ikrj7l7cl767pz0hnv3k-linux-5.13.2-dev/lib/modules/5.13.2/build'
make[1]: *** [Makefile:215: __sub-make] Error 2
make[1]: Leaving directory '/nix/store/raiis134czq0ikrj7l7cl767pz0hnv3k-linux-5.13.2-dev/lib/modules/5.13.2/source'
make: *** [Makefile:80: modules] Error 2
builder for '/nix/store/7warns3r69mfj3xy8xiwkcz9096sgmc6-nvidia-x11-460.73.01-5.13.2.drv' failed with exit code 2
~~~

**Comment by bkchr** [comment] 2021-07-19 09:03
Duplicate of https://github.com/NixOS/nixpkgs/issues/129233

**Closed** 2021-07-19 09:05 UTC
Labels: 0.kind: bug, 1.severity: blocker, 6.topic: nixos
