### ISSUE TITLE
raft-canonical is broken

### ISSUE THREAD

**Issue by wegank** [NixOS/nixpkgs#183759] opened 2022-07-29 18:11 UTC
... on both [nixos-unstable](https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.raft-canonical.x86_64-linux) and [nixpkgs-unstable](https://hydra.nixos.org/job/nixpkgs/trunk/raft-canonical.aarch64-linux). Looks like a test failed.

This at least prevents `lxd`(and therefore `waydroid`) from being built on Linux.

### Build log

```
make  check-TESTS
...
tcp_connect/closeDuringHandshake                            [ ERROR ]
Error: test/integration/test_uv_tcp_connect.c:46: assertion failed: status == result->status (0 == 13)
Error: child killed by signal 6 (Aborted)
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by vcunat** [comment] 2022-07-29 18:31
IIRC this is since PR #181620  merged in 29316ab.

**Comment by vcunat** [comment] 2022-07-29 18:32
Not like I want to work on this, but I see
```
$ errno 13
EACCES 13 Permission denied
```

**Comment by wentasah** [comment] 2022-07-29 21:41
Nope, 13 is not errno, but a file descriptor. See strace output of the failing test:
```
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 13
connect(13, {sa_family=AF_INET, sin_port=htons(41893), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
epoll_ctl(5, EPOLL_CTL_ADD, 8, {events=EPOLLIN, data={u32=8, u64=8}}) = 0
epoll_ctl(5, EPOLL_CTL_ADD, 10, {events=EPOLLIN, data={u32=10, u64=10}}) = 0
epoll_ctl(5, EPOLL_CTL_ADD, 13, {events=EPOLLOUT, data={u32=13, u64=13}}) = 0
epoll_wait(5, [{events=EPOLLOUT, data={u32=13, u64=13}}], 1024, -1) = 1
getsockopt(13, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
write(13, "\1\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\20\0\0\0\0\0\0\000127.0.0."..., 40) = 40
write(2, "Error", 5)                    = 5
write(2, ": ", 2)                       = 2
write(2, "test/integration/test_uv_tcp_con"..., 43) = 43
write(2, "assertion failed: status == resu"..., 52) = 52
``` 
This is likely caused by #181318. Reverting libuv to 1.44.1 results in a successful build. Looking at libuv changes, I guess that https://github.com/libuv/libuv/pull/3598 might be the reason. I'll file a bug upstream.

**Comment by vcunat** [comment] 2022-07-29 22:16
Oh, `status` and `result->status` sounded very much like error codes.

**Closed** 2022-08-02 21:19 UTC
Labels: 0.kind: build failure
