### ISSUE TITLE
logseq added support for the logseq protocol (`logseq://`), we don't have a handler for it

### ISSUE THREAD

**Issue by steveeJ** [NixOS/nixpkgs#179359] opened 2022-06-27 17:49 UTC
Around this version logseq added support for the [logseq protocol](https://docs.logseq.com/#/page/Logseq%20Protocol) (`logseq://`), shouldn't we have a handler for it?
Something like:
`xdg.mime.defaultApplications."x-scheme-handler/logseq" = "logseq.desktop"`

_Originally posted by @necauqua in https://github.com/NixOS/nixpkgs/issues/179013#issuecomment-1167341924_

**Comment by necauqua** [comment] 2022-07-09 10:39
My comment was probably wrong: it seems that it's enough to have a `MimeType=x-scheme-handler/logseq` line in the desktop file for xdg-open to pick it up, and upstream desktop file does not have that.
Same thing works fine for discord, for example, without explicitly touching things like `xdg.mime.defaultApplications`

**Comment by necauqua** [comment] 2022-07-17 14:14
Closing as an upstream issue (see the link above)

**Comment by raindev** [comment] 2022-11-22 20:40
@necauqua in which version was it fixed? I still have the same issue in 0.8.9

**Comment by klutchell** [comment] 2022-11-22 20:42
> @necauqua in which version was it fixed? I still have the same issue in 0.8.9

The [fix](https://github.com/logseq/logseq/pull/7219) is in 0.8.11 which is currently in `nixos-unstable`

**Comment by necauqua** [comment] 2022-11-22 20:44
I said it _will_ be fixed, someday, because that's an upstream issue with their appimage packer, not a nix-specific one

However I see this was merged https://github.com/logseq/logseq/pull/7219 recently, so the next release probably will actually be fixed

**Comment by necauqua** [comment] 2022-11-22 20:46
> The fix is in 0.8.11 which is currently in nixos-unstable and fixed the issue for me.

oh, this, great

**Comment by raindev** [comment] 2022-11-22 21:07
Thank you both for quick replies. The issue is indeed fixed in unstable already, have just confirmed after an upgrade, this issue could be closed. And sorry for reading inattentively :)

**Closed** 2022-11-23 18:26 UTC
