### ISSUE TITLE
`bruno` does not start correctly on nixos-23.11

### ISSUE THREAD

**Issue by p32blo** [NixOS/nixpkgs#300885] opened 2024-04-02 07:21 UTC
### Describe the bug
When Launching the application the window remains blank. 

### Steps To Reproduce
1. `nix shell nixpkgs/nixos-23.11#bruno`
2. `bruno`

### Expected behavior
The Application should start normally

### Screenshots
![bruno](https://github.com/NixOS/nixpkgs/assets/6619062/dbc62233-84ac-44d9-8524-6be05f129f25)

### Additional context

The console outputs the following erros:
```console
[10208:0402/081537.738868:ERROR:angle_platform_impl.cc(43)] Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Could not dlopen libGL.so.1: libGL.so.1: cannot open shared object file: No such file or directory
ERR: Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Could not dlopen libGL.so.1: libGL.so.1: cannot open shared object file: No such file or directory
[10208:0402/081537.739126:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not dlopen libGL.so.1: libGL.so.1: cannot open shared object file: No such file or directory
[10208:0402/081537.739244:ERROR:gl_display.cc(920)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
```
On `nixpkgs-unstable` it seems to be working.

### Notify maintainers
@water-sucks @lucasew @kashw2 @mattpolzin

### Metadata

I've tested both on Ubuntu and NixOS

**Ubuntu**

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-101-generic, Ubuntu, 20.04.6 LTS (Focal Fossa), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.21.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
output here
```
**NixOS**

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.82, NixOS, 23.11 (Tapir), 23.11.20240328.219951b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lucasew** [comment] 2024-04-02 13:56
Does it replicate on unstable?
```
nix shell nixpkgs/nixos-unstable#bruno
```

My hypothesis is that's a issue with Electron

**Comment by p32blo** [comment] 2024-04-02 15:05
No, it's working on unstable

**Comment by mattpolzin** [comment] 2024-10-26 03:12
I think we can close this unless it can be reproduced by someone on release 24.05 now that we are about to release 24.11. I'll wait a bit to see if someone says they can still reproduce this issue.

**Comment by lucasew** [comment] 2024-10-26 08:40
23.11 is basically EOL, no one is maintaining it anymore.

It was deprecated since 24.05 came out. 

I think it's out of scope of this issue to bring 24.05 to the subject. If the problem happens on 24.05 another issue can be created.

**Closed by lucasew** 2024-10-26 08:40 UTC
Labels: 0.kind: bug
