### ISSUE TITLE
21.05 unstable iso not booting on Lenovo thinkpad P14s  

### ISSUE THREAD

**Issue by drishal** [NixOS/nixpkgs#123376] opened 2021-05-17 15:22 UTC
![nixbug](https://user-images.githubusercontent.com/32875739/118515470-0d67b100-b753-11eb-9323-233a23bb7c41.jpg)
**Describe the bug**
On using the newer 21.05pre isos on my thinkpad P14s, it lands on the GRUB rescue  prompt. However the 20.09 iso boots perfectly fine (but can't use the GUI as kernel and mesa are a bit too old for the  hardware).  however the same USB drive with 21.05 works completely fine on the other Dell Vostro I have
Seems something wrong with the way Grub is implemented in the newer versions?  
Edit: Add an image, slightly blurry, my apologies

**Comment by putchar** [comment] 2021-05-17 15:34
Hello

I had the same issue with my lenovo t460 on uefi boot 
I had to use a 20.09iso , install nix. 
then switch to unstable channel

**Comment by justinas** [comment] 2021-05-17 15:43
If you just care about booting, I recently successfully installed my AMD P14s using a custom 20.09 ISO with `boot.kernelPackages = pkgs.linuxPackages_5_10;`.

**Comment by drishal** [comment] 2021-05-17 15:52
> If you just care about booting, I recently successfully installed my AMD P14s using a custom 20.09 ISO with `boot.kernelPackages = pkgs.linuxPackages_5_10;`.

but the thing is, I don't want the issue to get into stable, like say some time from now I want to change the SSD or something and need the 21.05 iso to do the reinstall

**Comment by justinas** [comment] 2021-05-17 20:10
I got the same result on an AMD ThinkPad P14s, using [this image](https://hydra.nixos.org/build/143009866). Boots right into the GRUB rescue menu.

**Comment by vcunat** [comment] 2021-05-18 08:05
21.05 is already using 5.10 kernel by default, so I expect the problem is somewhere else.  (boo!)

**Comment by drishal** [comment] 2021-05-20 11:02
hmm I can boot using this method: https://szymonkrajewski.pl/how-to-boot-system-from-usb-using-grub/
seems something changed between the way grub is handled  between 20.09 and 21.05 which affects lenovo bios?

**Comment by ncfavier** [comment] 2021-05-20 15:52
I also have this problem on my ThinkPad T420. The bug seems to come from GRUB 2.06-rc1, as replacing it with 2.04 on the same ISO fixes the problem. I investigated a bit a while ago and [filed a bug](https://savannah.gnu.org/bugs/index.php?60565), but it doesn't seem to have gotten any attention yet.

**Comment by hyperfekt** [comment] 2021-05-20 22:12
Bisected to commit 20def1a3c3952982395cd7c3ea7e78638527962b.

**Comment by hyperfekt** [comment] 2021-05-20 23:02
I have confirmed that reverting the patch in question solves the issue. If there isn't a fix we can apply from the grub project by the time we want to release 21.05 we can do that.

**Comment by drishal** [comment] 2021-05-21 04:05
> I also have this problem on my Lenovo ThinkPad T420. The bug seems to come from GRUB 2.06-rc1, as replacing it with 2.04 on the same ISO fixes the problem. I investigated a bit a while ago and [filed a bug](https://savannah.gnu.org/bugs/index.php?60565), but it doesn't seem to have gotten any attention yet.
> 
> EDIT: @drishal, how did you manage to boot exactly?

for booting:
1. I booted using the nixos unstable iso
2. it boots right to the grub prompt
3. found that my usb was `hd0`
Entered the following commands
`set root=(hd0)`
 `chainloader  /EFI/boot/bootx64.efi`
`boot`

**Comment by ncfavier** [comment] 2021-05-21 10:41
So... I was able to get GRUB to show me the graphical menu (`set root=hd0`, `set prefix=(hd0)/EFI/boot`, `normal`), but then I run into *another* bug where the screen freezes when I select an entry to boot. From the tests I did a while ago, it seemed to be caused by the font used in the graphical theme (`dejavu.pf2`) being too large for the text to fit on my screen.

Can anyone reproduce this?

**Comment by jonringer** [comment] 2021-05-22 17:33
> I have confirmed that reverting the patch in question solves the issue. If there isn't a fix we can apply from the grub project by the time we want to release 21.05 we can do that.

Branch off is supposed to happen soon, can we get a PR going?

**Comment by ncfavier** [comment] 2021-05-22 17:50
After a bit (a lot) of investigating, I seem to be running into *three* separate bugs with the latest unstable ISO:

1. The bug that sparked this issue: some files with a timestamp of 1970-01-01 (the UNIX epoch) are [copied into](https://github.com/NixOS/nixpkgs/blob/fc9a86afb02c76e432743e145021ddd188345286/nixos/modules/installer/cd-dvd/iso-image.nix#L418) the ISO's ESP, but because it's a FAT filesystem and the DOS epoch is 1980-01-01, those timestamps get interpreted as 2098-01-01, which then breaks GRUB because of the commit @hyperfekt pointed out (specifically, the bug seems to occur if the `\EFI` folder has a timestamp [above 2^31](https://en.wikipedia.org/wiki/Year_2038_problem)). An immediate solution would be to either patch GRUB as suggested, or to make sure those timestamps are set correctly.
2. A bug introduced by 20d0824b150492d4b484954c64aad9f24656c130, where `$root` gets set to the wrong device in some circumstances. AFAIK @samueldr is looking into fixing this.
3. The font bug I mentioned is caused by [this GRUB commit](https://git.savannah.gnu.org/cgit/grub.git/commit/?id=829329bddb2c3e623270cc634cc9ab32e6455fe7): the font used in the default theme is [too large](https://github.com/NixOS/nixos-artwork/blob/488c22aad523c709c44169d3e88d34b4691c20dc/bootloader/grub2-installer/fonts.sh#L18), which causes the check in that commit to fail for me because the default EFI video mode is 640x480. Possible fixes include reverting that commit, downsizing the font (the largest size that works for me is 15), setting `gfxmode` to include a better video mode (something like `1024x768,auto` works for me), or disabling the theme by default.

**Comment by samueldr** [comment] 2021-05-22 20:13
I wonder if there's also a combination knock-on effects of failure states not being handled the same way.

I don't have any *failure-inducing* hardware to test with, but my gut feeling tells me that on GRUB 2.04 failures would be much softer and things *tried* to continue, while on 2.06 it looks like (hard to tell!) that it might not really try.

**Comment by samueldr** [comment] 2021-05-22 20:19
GRUB@[20def1a3c3952982395cd7c3ea7e78638527962b](https://git.savannah.gnu.org/cgit/grub.git/commit/?h=20def1a3c3952982395cd7c3ea7e78638527962b)

**Comment by samueldr** [comment] 2021-05-22 22:27
Can you try with #124076

```
env -i nix-build nixos/release.nix -A iso_minimal_new_kernel.x86_64-linux
```

I'm trying with `($root)` instead of nothing. Hopefully that helps in the other situation. But my understanding is that `($root)` should be equivalent to not qualifying it.

**Comment by samueldr** [comment] 2021-05-22 22:39
Now files in the FAT32 FS should be backdated to 2000.

**Comment by samueldr** [comment] 2021-05-23 05:19
I'm closing as I assume this should fix the problem given the testing by other parties.

@drishal if there's still an issue after this fix, re-open the issue and/or tell us what is happening, and we'll try to see what is happening.

**Closed by samueldr** 2021-05-23 05:19 UTC
Labels: 0.kind: bug, 6.topic: nixos

**Comment by drishal** [comment] 2021-05-23 16:48
is it available on the latest unstable iso to test?

**Comment by hyperfekt** [comment] 2021-05-23 17:58
Check https://nixpk.gs/pr-tracker.html?pr=124076 for when the PR has made it to nixos-unstable and you can download the ISO. Until then you'll have to check out the repository and run `nix-build ./nixos -A config.system.build.isoImage -I nixos-config=nixos/modules/installer/cd-dvd/installation-cd-`{`minimal`,`graphical-plasma5`,`graphical-gnome`}`.nix` to build your own.

**Comment by etrigan63** [comment] 2021-06-03 14:10
Still a problem with 21.05 iso.

**Comment by jonringer** [comment] 2021-06-03 15:21
https://github.com/NixOS/nixpkgs/pull/124076 has been backported in https://github.com/NixOS/nixpkgs/pull/125508

**Comment by jonringer** [comment] 2021-06-03 15:21
I also forced an evaluation of release-21.05

**Comment by jonringer** [comment] 2021-06-03 15:24
https://nixpk.gs/pr-tracker.html?pr=125508 for people wondering about status

**Comment by jonringer** [comment] 2021-06-04 17:06
Direct link for people that are having caching issues to `nixos.org`

https://hydra.nixos.org/build/144749418/download/1/nixos-gnome-21.05.720.4c2e84394c0-x86_64-linux.iso

**Comment by zbskii** [comment] 2021-11-11 01:24
Note this issue is still reproducible for me in today's nightly nixos-minimal-21.05.4048.430e190b64d-x86_64-linux.iso on a framework laptop.

**Comment by samueldr** [comment] 2021-11-11 02:21
@zbskii can you open a new issue, with all diagnostic information you can figure out you have tested, and things you have, tested, verified works and not works?

The issue you're ultimately facing is unlikely to be the same as this one.

**Comment by runeksvendsen** [comment] 2022-09-17 13:11
FYI, is just ran into this issue and discovered my mistake: I copied the image to /dev/sda1. When I instead copied to /dev/sda it worked fine.
