### ISSUE TITLE
`arrow-cpp` build failure on x86_64-linux as of `b2b2c220`

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#287649] opened 2024-02-10 04:58 UTC
## Issue description
Build of `arrow-cpp` failed on x86_64-linux as of b2b2c220167c6073c9f4aec32d74044dd384762d. This is currently breaking `python3Packages.wandb`.

```
error: builder for '/nix/store/n5cccssrb53dz4759l4v0x4khjzbw4kl-arrow-cpp-15.0.0.drv' failed with exit code 8;
       last 10 log lines:
       > arrow_substrait     =   0.82 sec*proc (1 test)
       > filesystem          =   2.73 sec*proc (3 tests)
       > parquet-tests       =  19.47 sec*proc (9 tests)
       > unittest            = 212.83 sec*proc (90 tests)
       >
       > Total Test time (real) =  56.21 sec
       >
       > The following tests FAILED:
       >        73 - arrow-flight-test (Failed)
       > Errors while running CTest
       For full logs, run 'nix log /nix/store/n5cccssrb53dz4759l4v0x4khjzbw4kl-arrow-cpp-15.0.0.drv'.
error: 1 dependencies of derivation '/nix/store/rvbyv7b2dly1pd4q23jq7mq0p0m05xks-python3.11-pyarrow-15.0.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/35gnbz8qp9niamzalnly3wj79da6prmz-python3.11-dask-2024.1.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hljcngsyng7qvqm79n4yhzxl5faz7fxl-python3.11-mlflow-2.8.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/5yn0ppxy3sa2psfxkx55qkllsy7akxzp-python3.11-wandb-0.16.0.drv' failed to build
```

[full build log](https://github.com/samuela/nixpkgs-upkeep/actions/runs/7851044524)

python3Packages.wandb maintainers cc: @samuela
arrow-cpp maintainers cc: @tobim @veprbl @cpcloud
Other cc: n/a

### Steps to reproduce
1. Checkout nixpkgs at commit b2b2c220167c6073c9f4aec32d74044dd384762d
2. Run `nix-build -A arrow-cpp`

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.0-1019-azure, Ubuntu, 22.04.3 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.16.1`
 - nixpkgs: `/nix/store/5anayrh1fxrrjivmb3bhqcfdh7pwr8iy-source`
```

Contents of `~/.config/nixpkgs/config.nix`:
```
{ allowUnfree = true; cudaSupport = true; cudaCapabilities = ["8.0"]; }
```

## Misc.
This issue was automatically generated by [nixpkgs-upkeep](https://github.com/samuela/nixpkgs-upkeep).
- [CI workflow](https://github.com/samuela/nixpkgs-upkeep/actions/runs/7851044524) that created this issue.
- Internal tags: -2767112431859991377 -5425423171551306363

**Comment by dotlambda** [comment] 2024-02-11 00:19
duplicate of https://github.com/NixOS/nixpkgs/issues/284878

**Closed by dotlambda** 2024-02-11 00:19 UTC
