### ISSUE TITLE
GHC: build with hadrian

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#137127] opened 2021-09-08 20:04 UTC
I've given this a go, but it doesn't seem hadrian is packaged with Nix yet.

In theory, it should speed up the builds, but that's yet to be benchmarked.

**Comment by sternenseemann** [comment] 2022-05-11 14:16
Upstream aims to get rid of make for 9.6 and 9.4 with make will not get CI. Make can already not bootstrap any GHC with 9.2.2. So for 9.4 we have two options:

* Package 9.0 bindists and continue using make, hope for the best
* Switch to hadrian

I think I'll see how much time I have on my hands when the first release candidate appears and go for one of those. At least switching to hadrian will present the opportunity to make a `common-hadrian.nix` to ease the maintenance of future GHC releases.

Another problem is that starting with 9.4 all bindists will be hadrian which is a problem, since we haven't figured out how to make these find gmp yet (see https://github.com/NixOS/nixpkgs/pull/168003; **TODO** link GHC ticket).

cc fyi @NixOS/haskell @guibou

**Comment by maralorn** [comment] 2022-05-11 22:14
Didn’t @Ericson2314 have opinions about this?

**Comment by sternenseemann** [comment] 2022-05-11 23:20
Yes and I generally have the same opinion, but we are not there (there being, separately buildable GHC, RTS, libs) and upstream seems set on killing our beloved make build system. Thus, we seem to have not much choice in the matter.

**Comment by bgamari** [comment] 2022-07-16 12:37
Indeed GHC's `make` build system will be gone in GHC 9.6.

Note that my [`ghcs.nix`](https://gitlab.haskell.org/bgamari/ghcs-nix) derivation may serve as a good model. Specifically, there are two parts:

* https://gitlab.haskell.org/bgamari/ghcs-nix/-/blob/master/hadrian-bootstrap.nix builds Hadrian itself using the bootstrapping sources shipped with GHC
* https://gitlab.haskell.org/bgamari/ghcs-nix/-/blob/master/hadrian.nix builds GHC using the Hadrian we previously built

**Comment by sternenseemann** [comment] 2022-07-16 16:39
@bgamari I had a look and started on it in #179184, building hadrian is already possible.

However, the problem is that ghcs-nix doesn't support any of the interesting things we do in nixpkgs for hadrian (cross compilation, specific settings, ...). I had a look and fear that we actually need to compile a custom hadrian for every GHC derivation since not everything we do can be mapped to the default flavours and transformers.

Thus my initial effort has stalled a bit, since it'll take some time to figure out how to translate underdocumented make build system settings into underdocumented hadrian build settings.

**Comment by Ericson2314** [comment] 2022-07-16 16:57
@bgamari If we could accelerate the RTS configure stuff just a little bit, we could use neither Hadrian nor Make and keep all the easy functionality @sternenseemann is mentioning.

**Comment by bgamari** [comment] 2022-07-16 18:45
@sternenseemann, while it is true that `ghcs-nix` does not currently support cross-compilation, I would be surprised if there is actually a non-cross configuration that the `nixpkgs` derivation supports but `ghcs-nix` can not.

>  I had a look and fear that we actually need to compile a custom hadrian for every GHC derivation since not everything we do can be mapped to the default flavours and transformers.

Note that flavours and flavour transformers are not the only means of configuring a hadrian build. The [key-value configuration mechanism](https://gitlab.haskell.org/ghc/ghc/-/blob/097759f9f85ded496b21cf28e83cbdad1bf9a65b/hadrian/doc/user-settings.md#key-value-and-key-value-style-settings) is nearly as expressive as the `make` build system. I am happy to advise if you run into something that you can't work out.

**Comment by bgamari** [comment] 2022-07-16 19:01
> @bgamari If we could accelerate the RTS configure stuff just a little bit, we could use neither Hadrian nor Make and keep all the easy functionality @sternenseemann is mentioning.

I'll admit, this idea still seems quite speculative to me. It's possible that some day this could be feasible but I think it would be unwise to predicate nixpkgs's support on it. I am quite skeptical that doing this in a way that is maintainable could be done before even 9.8, although I am happy to be surprised.

**Comment by Ericson2314** [comment] 2022-07-16 20:07
Hadrian is nicer to modify than Make, but from the Nixpkgs standpoint we're not reading/writing Haskell just running a black box, and the fact that Hadrian does much more singing and dancing than Make is very noticeable downside.

I am happy to write whatever I need to write to convince the Haskell community that building GHC without Make or Hadrian is less costly --- easier and more maintainable --- than people imagine. Indeed we've discussed that many times. I comment here as this thread points out the benefits might be greater than people think too. Some combination of the costs being less and the benefits being greater will be needed to get this over the finish line, and this thread is a key resource for the latter.

**Comment by sternenseemann** [comment] 2022-07-18 18:06
> Note that flavours and flavour transformers are not the only means of configuring a hadrian build. The [key-value configuration mechanism](https://gitlab.haskell.org/ghc/ghc/-/blob/097759f9f85ded496b21cf28e83cbdad1bf9a65b/hadrian/doc/user-settings.md#key-value-and-key-value-style-settings) is nearly as expressive as the `make` build system. I am happy to advise if you run into something that you can't work out.

The key-value settings can only set flags for different tools during the build process which is only one of the things we seem to be using, so I think especially since arbitrary combinations of those settings are possible we may need to inject a custom `UserSettings.hs` always if we want to support everything we had before.

This is the current list of `build.mk` settings we set for `build.mk` and my current knowledge of how to translate them to hadrian:

| `build.mk` | hadrian |
| --- | --- |
| `BuildFlavour` | `--flavour` |
| `BUILD_SPHINX_HTML` | `--docs` (all combinations possible?) or in custom flavour |
 | `BUILD_SPHINX_PDF` | `--docs` (all combinations possible?) or in custom flavour |
 | `HADDOCK_DOCS` | `--docs`, but does `--docs=none` disable building `haddock` altogether like it used to? Is haddock still broken when building a cross compiler? |
| `EXTRA_HADDOCK_OPTS ` | ? |
| `DYNAMIC_GHC_PROGRAMS` | part of flavour |
| `BIGNUM_BACKEND` | part of flavour or `--bignum` |
| ` Stage1Only` | [supposedly](https://gitlab.haskell.org/ghc/ghc/-/blob/master/hadrian/doc/cross-compile.md) this is no longer necessary, will hadrian build stage2 as well, though? `--freeze1`? |
| `CrossCompilePrefix` | `./configure --target=` is sufficient now? |
| `GhcLibWays` | part of flavour |
| `GhcLibHcOpts` | `*.ghc.ghc.*.opts` (?) |
| `GhcRtsHcOpts` | `*.rts.ghc.*.opts` (?) |
| `EXTRA_CC_OPTS` | `*.*.cc.*.opts` |

**Comment by cdepillabout** [comment] 2022-08-02 05:50
I imagine it may not be very helpful, but here's a PR for haskell.nix where they are trying to support building with hadrian: https://github.com/input-output-hk/haskell.nix/pull/1475

**Comment by sternenseemann** [comment] 2022-09-22 14:23
`ghcHEAD` will now be built with hadrian, but there are a few regressions:

* Building a cross-compiler doesn't work due to [ghc#22090](https://gitlab.haskell.org/ghc/ghc/-/issues/22090)
* Static seems to be broken in an even worse way, but I've deferred looking at that until cross works again, since it is a prerequisite for the former.
* Probably more, unknown stuff.

I will _not_ port any GHC versions `< 9.5` to hadrian, as it is lacking features we are using (especially on those versions). There is no significant advantage in migrating for us anyways.

**Comment by sternenseemann** [comment] 2023-01-03 23:54
Cross is fixed in #208421 and we even can make the js backend work.

I'll look into `pkgsStatic` and see if that regression remains.

**Closed by sternenseemann** 2023-01-03 23:54 UTC
Labels: 6.topic: haskell
