### ISSUE TITLE
pcloud broken

### ISSUE THREAD

**Issue by leon-thomm** [NixOS/nixpkgs#325629] opened 2024-07-08 19:33 UTC
### Describe the bug

The `pcloud` package runs into a segmentation fault.

### Steps To Reproduce

```bash
$ NIXPKGS_ALLOW_UNFREE=1 nix-shell -p pcloud -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/e89cf1c932006531f454de7d652163a9a5c86668.tar.gz
[nix-shell:~]$ pcloud
Segmentation fault (core dumped)
```

### Expected behavior

application launches

### Additional context

I experience this issue since version 1.12.0. Version 1.11.0 seems to work fine.

### Notify maintainers

@Patryk27 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.11 (Vicuna), 24.11pre647193.9f4128e00b0a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos, nixpkgs-24.05"`
 - nixpkgs: `/home/leon/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Patryk27** [comment] 2024-07-08 19:36
Yes, it's a known issue: https://github.com/NixOS/nixpkgs/issues/226339.

Unfortunately, the underlying bug is not related to pcloud itself, but to patchelf (an application used internally by Nix) whose maintainers don't have enough time to review my patches at the moment.

Fortunately, you can just apply the appropriate patch locally:

https://discourse.nixos.org/t/pcloud-gives-segmentation-fault/31330/5?u=patryk27    
(https://gist.github.com/zarelit/c71518fe1272703788d3b5f570ef12e9)

Since the issue is already tracked in https://github.com/NixOS/nixpkgs/issues/226339, I'll close this issue.

**Closed by Patryk27** 2024-07-08 19:36 UTC
Labels: 0.kind: bug

**Comment by leon-thomm** [comment] 2024-07-08 19:48
whoopsie, thanks a lot! :pray:
