### ISSUE TITLE
Sane support for M2070

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#33579] opened 2018-01-07 19:35 UTC
## Issue description
I can print but not scan using my Samsung M2070
```
sudo sane-find-scanner 

  # sane-find-scanner will now attempt to detect your scanner. If the
  # result is different from what you expected, first make sure your
  # scanner is powered up and properly connected to your computer.

  # No SCSI scanners found. If you expected something different, make sure that
  # you have loaded a kernel SCSI driver for your SCSI adapter.
  # Also you need support for SCSI Generic (sg) in your operating system.
  # If using Linux, try "modprobe sg".

found USB scanner (vendor=0x04e8, product=0x3469 [M2070 Series]) at libusb:001:002
  # Your USB scanner was (probably) detected. It may or may not be supported by
  # SANE. Try scanimage -L and read the backend's manpage.

  # Not checking for parallel port scanners.

  # Most Scanners connected to the parallel port or other proprietary ports
  # can't be detected by this program.
```
however `scanimage -L` do not fing any scanner
also the content of the sane backends directory do not contains any `smfp.conf` file
```
ls /nix/store/s1vl6r0kw5nglk9iqr4x9yaja8m48qip-sane-backends-1.0.27/etc/sane.d
abaton.conf          canon630u.conf  dc210.conf    epson2.conf   hp4200.conf    kvs1025.conf     microtek.conf    pieusb.conf      s9036.conf     st400.conf     u12.conf
agfafocus.conf       canon.conf      dc240.conf    epson.conf    hp5400.conf    leo.conf         mustek.conf      pixma.conf       saned.conf     stv680.conf    umax1220u.conf
apple.conf           canon_dr.conf   dc25.conf     epsonds.conf  hp.conf        lexmark.conf     mustek_usb.conf  plustek.conf     sceptre.conf   tamarack.conf  umax.conf
artec.conf           cardscan.conf   dll.conf      fujitsu.conf  hs2p.conf      ma1509.conf      nec.conf         plustek_pp.conf  sharp.conf     teco1.conf     umax_pp.conf
artec_eplus48u.conf  coolscan2.conf  dll.d         genesys.conf  ibm.conf       magicolor.conf   net.conf         qcam.conf        sm3840.conf    teco2.conf     v4l.conf
avision.conf         coolscan3.conf  dmc.conf      gt68xx.conf   kodakaio.conf  matsushita.conf  p5.conf          ricoh.conf       snapscan.conf  teco3.conf     xerox_mfp.conf
bh.conf              coolscan.conf   epjitsu.conf  hp3900.conf   kodak.conf     microtek2.conf   pie.conf         rts8891.conf     sp15c.conf     test.conf
```

### Steps to reproduce
- connect a Samsung M2070
- add the following to `/etc/nixos/configuration.nix`
```
let
  p=pkgs.samsung-unified-linux-driver_1_00_37;
in
{
  hardware.sane={
    extraBackends=[p];
    enable=true;
  };
  nix.readOnlyStore=false;
  services.printing={
    enable=true;
    drivers=[p];
  };
}
```
- run  `sudo nixos-rebuild switch`

## Technical details
- system: `"x86_64-linux"`
 - host os: `Linux 4.9.73, NixOS, 18.03pre124015.f59a0f7f1a6 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.12pre5810_5d5b931f`
 - channels(root): `"nixos-18.03pre124015.f59a0f7f1a6"`
 - channels(pasquale): `"nixos-18.03pre124015.f59a0f7f1a6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by tohl** [comment] 2018-04-15 21:33
@tohl reminder to myself, I have a partial fix for this

**Comment by tohl** [comment] 2018-04-15 21:43
actually this is a duplicate of https://github.com/NixOS/nixpkgs/issues/27995

**Comment by pasqui23** [comment] 2018-04-15 22:35
Keep in mind that,as far as I know,the m2070 is a different model from the m2070w

**Closed** 2018-06-02 19:46 UTC

**Comment by tohl** [comment] 2019-03-11 21:06
pasqui23 <notifications@github.com> writes:
> Keep in mind that,as far as I know,the m2070 is a different model from
> the m2070w

m2070 and m2070w are different models but they share the same driver

<https://github.com/NixOS/nixpkgs/pull/57449> fixes this issue and also
the other issue <https://github.com/NixOS/nixpkgs/issues/27995>
