### ISSUE TITLE
Clang fails to build a shared library with atomics on linux

### ISSUE THREAD

**Issue by tobim** [NixOS/nixpkgs#91285] opened 2020-06-22 13:36 UTC
**Describe the bug**
Clang or `cc-wrapper` adds a directory with static (non-relocatable) gcc libs to the linker path (`${gcc-unwrapped}/lib64`). When trying to build a shared object, the linker errors with:
```
/nix/store/ivmds12g88jbjf8famgwkj36a4rrfcy6-binutils-2.31.1/bin/ld: /nix/store/7rnys4pl8v7sb72ljbhzr3wjfly339rg-gcc-9.3.0/lib64/gcc/x86_64-unknown-linux-gnu/9.3.0/../../../../lib64/libatomic.a(glfree.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
```

The same code builds correctly if the linker is called though gcc, because that uses the `lib` output of `gcc-unwrapped`. Looking at the `cc-ldflags` file of the wrapped, it adds `${gcc-unwrapped.lib}/x86_64-unknown-linux-gnu/lib`, which does not exist on my system. Maybe it should for consistency with cross-compiling toolchains?

I actually expected clang to link to `compiler-rt` for atomic support, but I discovered that these functions are disabled by default in LLVM's CMake scaffold.

**To Reproduce**
1. `shell.nix`:
``` nix
{ pkgs ? import <nixpkgs> { }, useClang ? false }:
let
  inherit (pkgs) lib;
  llvmPkgs = pkgs.llvmPackages_10;
  stdenv = if useClang then llvmPkgs.stdenv else pkgs.stdenv;
  mkShell = pkgs.mkShell.override { inherit stdenv; };
in
mkShell {
  name = "stdenv-" + (if useClang then "clang" else "gcc");
  hardeningDisable = [ "fortify" ];
}
```
`src.cxx`:
``` cpp
#include <atomic>
#include <cstdint>

int main()
{
  auto x = std::atomic<int>{};
  return !std::atomic_is_lock_free(&x);
}
```
2.  Build it with gcc:
```
nix-shell --arg useClang false --run "c++ -std=c++17 -shared -o lib.so src.cxx -fpic -latomic -v"
```
3. Build it with clang:
```
nix-shell --arg useClang true --run "c++ -std=c++17 -shared -o lib.so src.cxx -fpic -latomic -v"
```

**Expected behavior**
It links to `libatomic.so` like gcc does.

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.46, NixOS, 20.09.git.9c77f653c45 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.09pre229574.0a146054bdf"`
 - channels(tobim): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by matthewbauer** [comment] 2020-06-22 15:14
libatomic shouldn't be needed if your hardware has native. But when you do (on armv6l), I'm not sure if you can just use GCC's libatomic, since the compiler is different. It looks like compiler-rt does provide the same thing as libatomic, but we need to enable it with some flags for armv6l.

**Comment by tobim** [comment] 2020-06-22 15:40
> libatomic shouldn't be needed if your hardware has native.

As far as I know, that changed with GCC7, which came with an announcement that libatomic would be used in all cases. My own testing with GCC9 revealed that this seems not to be the case any more though, the code above does not use a call to the library, but replacing `int` with `__int128_t` makes it do so.

For clang, it  always calls into libatomic. Just build the objects instead of the `.so` and look at the output of `nm`.

> But when you do (on armv6l), 

I have amd64, so both 8 byte and 16 byte operations should be supported by the hardware.

> I'm not sure if you can just use GCC's libatomic, since the compiler is different.

The interface and abi are compatible. The code can be made to work by adding `-L/nix/store/aghiaaz22a0h4b91vx8d1z1xhz9paikf-gcc-9.3.0-lib/lib`

**Comment by tobim** [comment] 2020-06-26 08:56
I have to correct myself: Adding `-mcx16` to the compile flags makes both emit the call to the right instructions directly.

The problem still persists if `std::atomic` is used with a larger type, which might happen in generic code.

**Comment by harry75369** [comment] 2023-09-15 10:03
After some digging, I found that the incorrect path was fixed in https://github.com/NixOS/nixpkgs/blame/1976d434c41be158c0d820e7f83c3ce6af72ddb4/pkgs/build-support/cc-wrapper/default.nix#L379 last year, against the stable 23.05 version https://github.com/NixOS/nixpkgs/blame/4ecab3273592f27479a583fb6d975d4aba3486fe/pkgs/build-support/cc-wrapper/default.nix#L343

Maybe using the latest nixpkgs commit will fix the problem.

**Comment by harry75369** [comment] 2023-09-17 10:38
After more digging, the whole facts summarized here:

1. This issue was found in Jun 22, 2020.
2. This issue could be fixed with https://github.com/NixOS/nixpkgs/pull/133512 in Aug 11, 2021, but this PR is ignored for over one year.
3. Another PR https://github.com/NixOS/nixpkgs/pull/192459 was made in Sep 22, 2022 to accelerate the fixing, and was soon approved one day later.
4. As of today, Sep 17, 2023, this fix is still not merged into any stable branches of nixpkgs, and is only available in the following branches:
    - haskell-updates
    - master
    - nixos-unstable
    - nixos-unstable-small
    - nixpkgs-unstable
    - phpbench/init-at-1-2-14
    - phpdocumentor/init-at-3.4.1
    - python-updates
    - revert-255173-patch-1
    - robo/init-at-4-0-4
    - staging
    - staging-next
 
which is in 12 branches out of total 584 branches. So it is really hard for a new comer like me to figure out which nixpkgs version I should use. And this is really a very bad impression of the whole nix community.

This 2020-year issue wasted me more than three days to figure out in 2023. Very disappointed, indeed.

**Comment by Artturin** [comment] 2023-11-15 20:18
Made a test which demonstrates that the issue is fixed https://github.com/NixOS/nixpkgs/pull/267717

**Closed by Artturin** 2023-11-15 20:18 UTC
Labels: 0.kind: bug
