### ISSUE TITLE
Package request: doomrunner

### ISSUE THREAD

**Issue by keenanweaver** [NixOS/nixpkgs#231123] opened 2023-05-10 18:01 UTC
**Project description**

Modern preset-oriented graphical launcher of ZDoom and derivatives (an alternative to ZDL)

**Metadata**

* homepage URL:
* source URL: https://github.com/Youda008/DoomRunner/
* license: gpl3
* platforms: linux

**Comment by pinn3** [comment] 2023-05-10 18:27
Duplicate of https://github.com/NixOS/nixpkgs/issues/210339

**Closed** 2023-07-03 22:58 UTC
Labels: 0.kind: packaging request
