### ISSUE TITLE
Password hashes from mkpasswd result in unusable passwords

### ISSUE THREAD

**Issue by antifuchs** [NixOS/nixpkgs#136104] opened 2021-08-29 15:32 UTC
### Describe the bug

The [nixos manual suggests](https://nixos.org/manual/nixos/stable/#sec-user-management):

> Passwords may still be assigned by setting the user's hashedPassword option. A hashed password can be generated using `mkpasswd -m sha-512`.

Unfortunately, this outputs password hashes that do not let the user in when using the password being set. Another method of getting a salted password hash [from stackoverflow](https://unix.stackexchange.com/a/76337) results in a password hash that does work.

### Steps To Reproduce
1. Run `mkpasswd -m sha-512` and enter a randomly-generated password (I set a 27-character password consisting of lowercase letters and digits).
2. Set `users.users.root.hashedPassword = "<the emitted hash>";` in system config
3. `nixos-rebuild switch`
4. `su` and enter the randomly-generated password above
5. `su: Authentication failure`
6. Use `nix-shell -p python3 --run "python -c 'import crypt,getpass; print(crypt.crypt(getpass.getpass(), crypt.mksalt(crypt.METHOD_SHA512)))'"` to get a password hash; set that and rebuild
7. `su` and enter the randomly-generated password
8. root login shell opens.

### Expected behavior
`su` should accept the password in step 5.

### Additional context

I have many suspicions on why mkpasswd-emitted hashes don't work, but haven't yet evaluated any of them:
* input too long
* broken hash algorithm
* broken salt?

### Notify maintainers

@fpletz 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.57, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - nixpkgs: `/nix/store/npgpi8bip0qsh860rr3z6qrq5iwr04sd-source`
```
  
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [mkpasswd]
# a list of nixos modules affected by the problem
module: []
```

**Comment by Artturin** [comment] 2021-08-29 17:49
works for me
`nixos-21.11pre311431.88226ea038e`

**Comment by rnhmjoj** [comment] 2021-08-29 18:16
I've always used this method and never had any trouble. Can you post a specific hash that breaks the login?

**Comment by antifuchs** [comment] 2021-08-30 04:31
Hah. Took me a little while to reset the password I had tried to set so that I can publish it here. I used `teeny3vassar2stipple2bereft`. The salt that mkpasswd generated was `WWnJtJKELmoUU`, resulting in the following hash:

``` sh
$ :;    mkpasswd -m sha-512
Password:
$6$WWnJtJKELmoUU$DWBEmWnGIeAYCUFFhqrCT1DIkBI1NxRSuO2./FfMrmSRjEwJSFLp44J.RqSYHDn2qf13YLEJbe1RO7OxdfGYk1
```

You can repro that on other systems with `mkpasswd -S WWnJtJKELmoUU -m sha-512`

Generating the same password hash with the python command line above (using the pre-set salt) results in a different hash though:

```sh
:;    nix-shell -p python3 --run "python -c 'import crypt,getpass; print(crypt.crypt(getpass.getpass(), \"\$6\$WWnJtJKELmoUU\"))'"
Password:
$6$WWnJtJKELmoUU$tnVT0Vl.oMEN.dhp/vlmy5clJOwj3k0G36Qu0OcYO0OpB00SiZRjBoJH7/DSYy.E0klnn.maSm7eUjeA/brB7/
```

And given that the python script can generate a password that I can use to log in... I think something is wonky with mkpasswd.

**Comment by antifuchs** [comment] 2021-08-30 04:35
Trying some other randomly-generated strings, I notice that I must have gotten pretty (un)lucky: mkpasswd and crypt.crypt generate the same hash given the same salt, on many passwords. Just the first one I tried causes things to go off the rails (typical!) (:

**Comment by AkechiShiro** [comment] 2022-09-12 15:03
Is this issue still relevant, I've tried generating a password using `mkpasswd` with a random salt from `/dev/urandom` but saw very weird non-printable characters, I inputted a random salt but with only printable characters, and took the result (I was in the installation minimal ISO NixOS 22.10) and set it up for the `nixos` user, using `pkgs.lib.mkForce <value>` and then a `nixos-rebuild switch` and it worked alright to log in and lock the installation medium using `vlock`.

**Comment by fadenb** [comment] 2022-09-12 15:38
We experienced the issue described here just two weeks ago and are still in the process of rolling out fixed hashes to avoid lock-outs :see_no_evil: 
@otti0815: Which versions of NixOS were in use where we encountered the issue?

**Comment by fpletz** [comment] 2022-09-12 15:55
@fadenb can you confirm you you indeed used `sha-512` and the prefix is `$6$`? I think this issue is invalid because people forgot to add the hashing method to the `mkpasswd` call. Yescrypt is the new default in mkpasswd which is not supported in nixpkgs yet: #147312

There is a draft PR #181764 and I also tried fixing this in the past but it's complicated and requires lots of rebuilds. :slightly_frowning_face:

**Comment by AkechiShiro** [comment] 2022-09-12 16:27
I can confirm @fpletz that I've used `SHA-512` for mine, I believe you are correct, hence why I commented that I did not run into the issue.

**Comment by raboof** [comment] 2023-05-13 10:33
> @fadenb can you confirm you you indeed used `sha-512` and the prefix is `$6$`? I think this issue is invalid because people forgot to add the hashing method to the `mkpasswd` call. Yescrypt is the new default in `mkpasswd` which is not supported in nixpkgs yet: #147312
> 
> There is a draft PR #181764 and I also tried fixing this in the past but it's complicated and requires lots of rebuilds. slightly_frowning_face

This PR is now merged, and the manual no longer suggests `-m sha-512`. Does that mean this issue can now be closed, or is there more left to do?

**Comment by fpletz** [comment] 2023-05-22 09:22
> This PR is now merged, and the manual no longer suggests `-m sha-512`. Does that mean this issue can now be closed, or is there more left to do?

We indeed now support all hashes that libxcrypt supports with 23.05 and thus this issue can be closed. Thanks.

**Closed by fpletz** 2023-05-22 09:22 UTC
Labels: 0.kind: bug
