### ISSUE TITLE
fwupd fails to update BIOS

### ISSUE THREAD

**Issue by uzytkownik** [NixOS/nixpkgs#148542] opened 2021-12-04 01:40 UTC
### Describe the bug
fwupd fails to update BIOS with error:
```
/nix/store/kjlgvswvr2p21xwp9aa47wiba2n78aid-fwupd-1.7.1/libexec/fwupd/efi/fwupdx64.efi cannot be found
```

### Steps To Reproduce
1. Have BIOS update
2. Run `fwupd update`

### Expected behavior
Update happens

### Additional context
Missing configuration and/or documentation. Using uefi package doesn't seems to work:
```
error: attribute 'filesInstalledToEtc' missing

       at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/hardware/fwupd.nix:29:35:

           28|       mkEtcFile = n: nameValuePair n { source = "${cfg.package}/etc/${n}"; };
           29|     in listToAttrs (map mkEtcFile cfg.package.filesInstalledToEtc);
             |                                   ^
           30|   extraTrustedKeys =
(use '--show-trace' to show detailed location information)
```

### Notify maintainers
@jtojnar

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-22.05pre335103.6daa4a5c045"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
attribute:
module: fwupd
```

**Comment by jtojnar** [comment] 2021-12-04 02:51
Duplicate of https://github.com/NixOS/nixpkgs/issues/147040

`fwupd-efi` is a dependency of `fwupd` containing EFI stuff, not fwupd built with EFI support so it is expected that it cannot be used as a fwupd replacement.

**Closed** 2021-12-09 09:33 UTC
Labels: 0.kind: bug
