### ISSUE TITLE
ncdu: Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by GaetanLepage** [NixOS/nixpkgs#185644] opened 2022-08-08 08:55 UTC
### Describe the bug
The new version of ncdu crashes at runtime.
However, when run in a nix-shell, the 1.16 version is grabbed so it works:
```console
[gaetan@server:~]$ ncdu --version
ncdu 2.1.2

[gaetan@server:~]$ ncdu
Illegal instruction (core dumped)

[gaetan@server:~]$ nix-shell -p ncdu --command "ncdu --version"
ncdu 1.16

[gaetan@server:~]$ nix-shell -p ncdu --command ncdu       # It works
```

### Steps To Reproduce
1. Add `ncdu` to the system packages
2. run ncdu

### Expected behavior
The program works as expected.

### Additional context
I am using the `nixos-unstable` channel.
Bug report on ArchLinux: https://bugs.archlinux.org/task/74046

### Notify maintainers
@pSub @SuperSandro2000 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[gaetan@server:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.59, NixOS, 22.11 (Raccoon), 22.11.20220808.0e27b0d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by trofi** [comment] 2022-08-11 10:21
Probably a case of https://github.com/NixOS/nixpkgs/issues/185665 where `zig` uses `-march=native` and hydra builds binaries with too high CPU requirement.

**Comment by GaetanLepage** [comment] 2022-08-18 06:40
Is there something we can do to fix this ?

**Comment by Artturin** [comment] 2022-08-18 12:47
arch has https://github.com/archlinux/svntogit-community/blob/9268385f4036c3db5f221f9d16d95f93d1cc3b9d/trunk/PKGBUILD#L31

**Comment by ajs124** [comment] 2022-08-18 23:51
looks like a duplicate of #169461

**Comment by ncfavier** [comment] 2022-10-21 09:31
Proposed a fix in https://github.com/NixOS/nixpkgs/pull/197046

**Closed** 2022-10-26 08:37 UTC
Labels: 0.kind: bug
