### ISSUE TITLE
Expand support for and document systemd-cryptenroll

### ISSUE THREAD

**Issue by j0hax** [NixOS/nixpkgs#139433] opened 2021-09-25 12:52 UTC
### Describe the issue

The upgrade from systemd 247 to 249 recently landed in nixpkgs-unstable. Version 248 brought support for `systemd-cryptenroll`, which allows for automatica unlocking of LUKS2 volumes with diverse security hardware.

In my specific case, I would like to use a FIDO2 security key as described in Lennart Poettering's [blog post](http://0pointer.net/blog/unlocking-luks2-volumes-with-tpm2-fido2-pkcs11-security-hardware-on-systemd-248.html), which requires an entry in `/etc/crypttab`.

Running `systemd-cryptenroll` correctly configures LUKS slots and tokens, and setting

```nix
environment.etc.crypttab = {
    enable = true;
    text = ''
      cryptroot /dev/sda2 - fido2-device=auto
    '';
  };
```

in my system configuration provides the correct file and appears to integrate with systemd when rebuilding. However I am still asked to provide a password for `/dev/sda2` when rebooting with zero interaction from my security key.

### Expected behavior

Unlocking LUKS at boot by confirming user presence. Ideally this could be managed by a NixOS Module such as [luksroot](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/luksroot.nix).

### Additional Context

- I am using a SoloKeys Somu, which supports U2F and FIDO2

- I believe this could be related to https://github.com/NixOS/nixpkgs/issues/31258.

### Notify maintainers

@andir @eelco @flokli @kloenk

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```yaml
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.68, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210908_3c56f62`
 - channels(root): `"nixos-21.11pre313466.bc06c93905f"`
 - channels(johannes): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: cryptsetup
# a list of nixos modules affected by the problem
module: systemd
```

**Comment by flokli** [comment] 2021-10-07 10:56
@j0hax you might want to take a look at https://github.com/NixOS/nixpkgs/pull/139864, which should provide some guidelines, and verify this actually works with non-root partitions and `/etc/crypttab`.

**Comment by flokli** [comment] 2021-10-07 17:49
https://github.com/NixOS/nixpkgs/pull/139864 has been merged, the `staging` branch of nixpkgs should contain this.

Can you take a look at this and report back?

**Comment by NickCao** [comment] 2021-12-04 12:36
Tested with tpm2 and fido2, all working as intended.

**Closed by NickCao** 2021-12-04 12:36 UTC
Labels: 0.kind: enhancement, 0.kind: question, 6.topic: nixos, 9.needs: reporter feedback, 6.topic: systemd

**Comment by ivankovnatsky** [comment] 2021-12-05 08:15
(sorry for commenting on a closed issue)

I'm still being asked for the password, though the configuration went fine, Can you please share your configuration? maybe I'm just missing something?

running `nixos-unstable`

I have this in my config:

```nix
  environment.etc.crypttab = {
    enable = true;
    text = ''
      crypted /dev/nvme0n1p2 - tpm2-device=auto
    '';
  };
```

**Comment by NickCao** [comment] 2021-12-05 08:22
I'm using nearly identical configuration, you may test the correctness of your setup with:
`sudo /run/current-system/systemd/lib/systemd/systemd-cryptsetup attach crypted /dev/nvme0n1p2 - tpm2-device=auto`

**Comment by ivankovnatsky** [comment] 2021-12-05 08:26
yes, as expected: 

```
sudo /run/current-system/systemd/lib/systemd/systemd-cryptsetup attach crypted /dev/nvme0n1p2 - tpm2-device=auto
Volume crypted already active.
```

did you tweak something under this config: https://github.com/ivankovnatsky/nixos-config/blob/main/hosts/thinkpad/boot.nix#L13 ?

**Comment by NickCao** [comment] 2021-12-05 08:27
systemd-cryptsetup won't work in initrd yet

**Comment by ivankovnatsky** [comment] 2021-12-05 08:32
ah, got it.

**Comment by flokli** [comment] 2021-12-08 22:39
systemd in initrd is discussed at https://github.com/NixOS/nixpkgs/pull/120015 (and other issues/PRs linked to/from there)
