### ISSUE TITLE
Package request: OpenProject

### ISSUE THREAD

**Issue by jplhome** [NixOS/nixpkgs#252956] opened 2023-09-02 14:54 UTC
**Project description**

self-managed, free and open source software for secure project management 
**OpenProject Community edition*

* homepage URL: https://www.openproject.org/community-edition/
* source URL: https://github.com/opf/openproject
* license: gpl 3.0
* platforms: linux

**Comment by raspher** [comment] 2024-02-11 21:57
closing as it's duplicate of https://github.com/NixOS/nixpkgs/issues/191159

**Closed by raspher** 2024-02-11 21:57 UTC
Labels: 0.kind: packaging request
