### ISSUE TITLE
Polish keyboard layout is not working under Gnome out of the blue

### ISSUE THREAD

**Issue by dpc** [NixOS/nixpkgs#42987] opened 2018-07-04 05:18 UTC
## Issue description

Upgraded my NixOS, polish keyboard layout stoppd working. In the gnome settings, I still see "Polish" as selected, but I can't use right alt to input diacritics as I used to just a couple of days ago.

### Steps to reproduce

I'm not sure.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.52, NixOS, 18.09pre144959.be1461fc0ab (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09pre144959.be1461fc0ab"`
 - channels(dpc): `"nixpkgs-18.09pre137243.31effc1d7d5"`
 - nixpkgs: `/home/dpc/.nix-defexpr/channels/nixpkgs`
```

**Comment by jtojnar** [comment] 2018-07-05 13:37
Opened an upstream issue about the layout viewer crash: https://gitlab.gnome.org/GNOME/libgnomekbd/issues/1

Regarding the issue, it seems to be caused by a line of dashes on the line 500 in `${xkeyboard_config}/share/X11/xkb/symbols/pl` introduced in https://github.com/NixOS/nixpkgs/commit/13fb4458c2e322d1efb39848285afc095e03bd01

**Comment by jtojnar** [comment] 2018-07-05 13:41
Apparently, it was fixed in xkeyboard-config 2.24 ([commit](https://cgit.freedesktop.org/xkeyboard-config/commit/symbols/pl?id=9a5cecf64ffc427a6a5a7c9a061992c32e5b8a4f)), we just need to update it.

**Closed** 2018-07-11 22:15 UTC
Labels: 0.kind: bug, 6.topic: freedesktop

**Comment by dpc** [comment] 2018-07-11 22:17
Thank you! Poland Stronk again. ;)

**Comment by dpc** [comment] 2018-07-24 02:51
```
Jul 23 19:48:38 spinlock.dpc.pw org.gnome.Shell.desktop[2163]: #7 0x7ffe98473b90 I   resource:///org/gnome/gjs/modules/signals.js:128 (0x7f9d502d0f78 @ 386)
Jul 23 19:48:38 spinlock.dpc.pw org.gnome.Shell.desktop[2163]: #8 0x7ffe98473c40 b   resource:///org/gnome/shell/ui/tweener.js:207 (0x7f9d502d05e8 @ 159)
Jul 23 19:48:38 spinlock.dpc.pw org.gnome.Shell.desktop[2163]: #9 0x7ffe98473cb0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f9d502b5de0 @ 71)
Jul 23 19:48:38 spinlock.dpc.pw org.gnome.Shell.desktop[2163]: #10 0x7ffe98473cb0 I   resource:///org/gnome/shell/ui/tweener.js:182 (0x7f9d502d0560 @ 15)
Jul 23 19:48:45 spinlock.dpc.pw /nix/store/adbikl92im12ypjbqb3axx2sbx5z6bjn-gdm-3.28.2/libexec/gdm-x-session[2046]: syntax error: line 500 of pl
Jul 23 19:48:45 spinlock.dpc.pw /nix/store/adbikl92im12ypjbqb3axx2sbx5z6bjn-gdm-3.28.2/libexec/gdm-x-session[2046]: The XKEYBOARD keymap compiler (xkbcomp) reports:
Jul 23 19:48:45 spinlock.dpc.pw /nix/store/adbikl92im12ypjbqb3axx2sbx5z6bjn-gdm-3.28.2/libexec/gdm-x-session[2046]: > Error:            Error interpreting include file "pl"
Jul 23 19:48:45 spinlock.dpc.pw /nix/store/adbikl92im12ypjbqb3axx2sbx5z6bjn-gdm-3.28.2/libexec/gdm-x-session[2046]: >                   Exiting
Jul 23 19:48:45 spinlock.dpc.pw /nix/store/adbikl92im12ypjbqb3axx2sbx5z6bjn-gdm-3.28.2/libexec/gdm-x-session[2046]: >                   Abandoning symbols file "default"
Jul 23 19:48:45 spinlock.dpc.pw /nix/store/adbikl92im12ypjbqb3axx2sbx5z6bjn-gdm-3.28.2/libexec/gdm-x-session[2046]: Errors from xkbcomp are not fatal to the X server
Jul 23 19:48:45 spinlock.dpc.pw /nix/store/adbikl92im12ypjbqb3axx2sbx5z6bjn-gdm-3.28.2/libexec/gdm-x-session[2046]: (EE) Error loading keymap /tmp/server-0.xkm
```

Doesn't work again.
