### ISSUE TITLE
Kernel panic during boot in 19.09

### ISSUE THREAD

**Issue by yrashk** [NixOS/nixpkgs#73355] opened 2019-11-13 17:01 UTC
**Describe the bug**

When upgrading from 19.03 to 19.09 I can't boot anymore as the kernel crashes (see screenshot). I tried kernels from 4.19.80 to 4.19.84, same problem. My current generation of 19.03 runs on 4.19.80 without manifesting this problem.

**To Reproduce**
1. Upgrade to 19.09
2. Crash
3. ?

**Expected behavior**

I expect kernel not to crash.

**Screenshots**

![photo_2019-11-13_17-55-26](https://user-images.githubusercontent.com/452/68785777-f6687000-063e-11ea-89f4-18fc524f6e78.jpg)

**Additional context**

I am running this on Dell Precision 7520.

[lshw output](https://github.com/NixOS/nixpkgs/files/3842469/lshw.txt)

**Metadata**

From 19.03 that does boot:

```
$ nix run nixpkgs.nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.80, NixOS, 19.03.173632.658eed76bbf (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09.1223.cb2cdab7136"`
 - channels(yrashk): `"nixos-unstable-20.03pre200231.7827d3f4497"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by d-goldin** [comment] 2019-11-19 22:04
Possible regression aside (one could possibly suspect the nonfree firmware), which is hard to troubleshoot remotely - Have you tried some `linux_latest` with it just to see if it works?

**Comment by yrashk** [comment] 2019-11-25 09:18
Tried booting from a stock USB installer -- same problem.

**Comment by yrashk** [comment] 2019-11-25 09:22
@d-goldin `linux_latest` works!

**Comment by Emantor** [comment] 2020-04-28 12:25
Closing because this was solved by switching to latest kernel, presumably stable was also fixed in the meantime.

**Closed by Emantor** 2020-04-28 12:25 UTC
Labels: 0.kind: bug, 6.topic: kernel
