### ISSUE TITLE
tor-browser crashes for every page

### ISSUE THREAD

**Issue by mkocha2** [NixOS/nixpkgs#29747] opened 2017-09-24 18:43 UTC
## Issue description
tor-browser crashes for every page (use yahoo.com as an example). See screenshot.
![screenshot_20170924_203616](https://user-images.githubusercontent.com/30756411/30785552-7c4265c0-a168-11e7-9e59-68b5f600e5c5.png)

The following suspicious output is present:
```
###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0086,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

[Parent 7194] WARNING: waitpid failed pid:7261 errno:10: file /home/debian/build/tor-browser/ipc/chromium/src/base/process_util_posix.cc, line 268
```

### Steps to reproduce
Install tor-browser and visit yahoo.com

## Technical details

* System: 17.03.1853.b7e4857dd9 (Gorilla)

**Comment by joachifm** [comment] 2017-09-24 19:50
Duplicate of https://github.com/NixOS/nixpkgs/issues/27759.  A work-around was added in https://github.com/NixOS/nixpkgs/commit/69e3817eb64c0621703be05cb1bcfcc76d97dd77.

**Closed** 2017-09-25 10:17 UTC
