### ISSUE TITLE
Build failure: diffoscope broken by coreboot-utils 4.21 upgrade

### ISSUE THREAD

**Issue by aij** [NixOS/nixpkgs#256896] opened 2023-09-23 13:18 UTC
### Steps To Reproduce

1. build diffoscope
  * Eg: `nix-build -A diffoscope`

### Build log

https://gist.github.com/aij/ffc8e357eed2c6f4411910972ce0b920

### Additional context

Broken since https://github.com/NixOS/nixpkgs/pull/251110 merged per [`git bisect`](https://github.com/NixOS/nixpkgs/issues/252045#issuecomment-1713881494)

I looked into this a bit and I'm not sure if it's a diffoscope bug or a coreboot bug.

The failing tests generate test files with `cbfstool` (from coreboot) and the files generated by `cbfstool` 4.21 are using 4 bytes less space for the "header" (trailer) at the end of the file:

```diff
$ diffoscope coreboot1.rom.4.20 coreboot1.rom.4.21 
--- coreboot1.rom.4.20
+++ coreboot1.rom.4.21
@@ -2039,10 +2039,10 @@
 00007f60: ffff ffff ffff ffff ffff ffff ffff ffff  ................
 00007f70: ffff ffff ffff ffff ffff ffff ffff ffff  ................
 00007f80: ffff ffff ffff ffff ffff ffff ffff ffff  ................
 00007f90: ffff ffff ffff ffff ffff ffff ffff ffff  ................
 00007fa0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
 00007fb0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
 00007fc0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
-00007fd0: ffff ffff ffff ffff ffff ffff 4f52 4243  ............ORBC
-00007fe0: 3131 3132 0000 8000 0000 0000 0000 0040  1112...........@
-00007ff0: 0000 0000 0000 0001 ffff ffff dcff ffff  ................
+00007fd0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
+00007fe0: 4f52 4243 3131 3132 0000 8000 0000 0000  ORBC1112........
+00007ff0: 0000 0040 0000 0000 0000 0001 e0ff ffff  ...@............
```

As a result, [CbfsFile.recognizes](https://salsa.debian.org/reproducible-builds/diffoscope/-/blob/ac79ac5c3dfa8a2d1ec0e897e0940c3b997b284d/diffoscope/comparators/cbfs.py#L142) does not match.

My first thought was to change the matcher

```diff
@@ -139,7 +138,7 @@ class CbfsFile(File):
             rel_offset = struct.unpack("<i", f.read(4))[0]
             if (
                 rel_offset < 0
-                and -rel_offset > CBFS_HEADER_SIZE
+                and -rel_offset >= CBFS_HEADER_SIZE
                 and -rel_offset < size
             ):
                 f.seek(rel_offset, io.SEEK_END)
```

but then the `rom2` tests still fail...

Looking into [the relevant change on  the coreboot side](https://github.com/coreboot/coreboot/commit/242bac0e162ca9a9258f61b0674b0dced5bcc01a) it looks like the change to the `cbfs_header` size may have been accidental. (C99 flexible arrays are nice for `filename` and `data` but not for fixed size padding...)

Anyway, even if this is a  coreboot bug, it may still be useful to update diffutils to be able to recognize files produced by coreboot 4.21.

### Notify maintainers

Diffoscope: @dezgeg @danielfullmer @raitobezarius

coreboot-utils: @felixsinger @yuka

Other: @ElyesH @jmbaur @felixsinger @lamby

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
ivan@tobati:~/nixops/aij/unstable$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.50, NixOS, 23.11 (Tapir), 23.11.git.bfb7dfec93f3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos-21.11pre329341.9e70e9f732f"`
 - nixpkgs: `/etc/nixos/aij/unstable`
```

**Comment by delroth** [comment] 2023-09-23 21:42
Unless someone is confident that this is a coreboot-utils bug (either by diagnosing it themselves or by getting upstream to acknowledge it as a bug), I'd suggest 1. skipping the test in nixpkgs diffoscope to unbreak the build; 2. filing a bug with upstream diffoscope to let them know of that breakage with the new coreboot-utils version.

Any other thoughts?

**Comment by RaitoBezarius** [comment] 2023-09-26 10:57
I won't be able to react in time for this problem for diffoscope, apologies. I would appreciate it if any of the other comaintainer could take care of this.
I think we have pending diffoscope upgrades which could mitigate the problem in the meantime.

**Comment by mschwaig** [comment] 2023-09-27 11:02
Diffoscope has opened https://salsa.debian.org/reproducible-builds/diffoscope/-/issues/352 for this which links here.

I have opened https://github.com/NixOS/nixpkgs/pull/257635 which disables the tests as suggested by @delroth and I agree that this is a good way forward for now.
If my PR gets merged I'd still suggest leaving this issue open until it's fixed and the cbfs tests run again, but closing it would also be fine with me.

**Comment by ElyesH** [comment] 2023-10-02 15:32
Hi Ivan,

Please send an email to ***@***.***

Thx
 

De : "Ivan Jager"
A : "NixOS/nixpkgs" ,"Elyes HAOUAS" ,"Mention"
Envoyé: samedi 23 Septembre 2023 15:19
Objet : [NixOS/nixpkgs] Build failure: diffoscobe broken by coreboot-utils 4.21 upgrade (Issue #256896)
 

 

Steps To Reproduce

Steps to reproduce the behavior:


	build diffoscope



	Eg: nix-build -A diffoscope


Build log

https://gist.github.com/aij/ffc8e357eed2c6f4411910972ce0b920

Additional context

Broken since #251110 merged per git bisect

I looked into this a bit and I'm not sure if it's a diffoscope bug or a coreboot bug.

The failing tests generate test files with cbfstool (from coreboot) and the files generated by cbfstool 4.21 are using 4 bytes less space for the "header" (trailer) at the end of the file:


$ diffoscope coreboot1.rom.4.20 coreboot1.rom.4.21 
--- coreboot1.rom.4.20
+++ coreboot1.rom.4.21
@@ -2039,10 +2039,10 @@
 00007f60: ffff ffff ffff ffff ffff ffff ffff ffff  ................
 00007f70: ffff ffff ffff ffff ffff ffff ffff ffff  ................
 00007f80: ffff ffff ffff ffff ffff ffff ffff ffff  ................
 00007f90: ffff ffff ffff ffff ffff ffff ffff ffff  ................
 00007fa0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
 00007fb0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
 00007fc0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
-00007fd0: ffff ffff ffff ffff ffff ffff 4f52 4243  ............ORBC
-00007fe0: 3131 3132 0000 8000 0000 0000 0000 0040  1112...........@
-00007ff0: 0000 0000 0000 0001 ffff ffff dcff ffff  ................
+00007fd0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
+00007fe0: 4f52 4243 3131 3132 0000 8000 0000 0000  ORBC1112........
+00007ff0: 0000 0040 0000 0000 0000 0001 e0ff ffff  ...@............


As a result, CbfsFile.recognizes does not match.

My first thought was to change the matcher


@@ -139,7 +138,7 @@ class CbfsFile(File):
             rel_offset = struct.unpack("<i", f.read(4))[0]
             if (
                 rel_offset < 0
-                and -rel_offset > CBFS_HEADER_SIZE
+                and -rel_offset >= CBFS_HEADER_SIZE
                 and -rel_offset < size
             ):
                 f.seek(rel_offset, io.SEEK_END)


but then the rom2 tests still fail...

Looking into the relevant change on the coreboot side it looks like the change to the cbfs_header size may have been accidental. (C99 flexible arrays are nice for filename and data but not for fixed size padding...)

Anyway, even if this is a coreboot bug, it may still be useful to update diffutils to be able to recognize files produced by coreboot 4.21.

Notify maintainers

Diffoscope: @dezgeg @danielfullmer @RaitoBezarius

coreboot-utils: @felixsinger @yuka

Other: @ElyesH @jmbaur @felixsinger @lamby

Metadata

Please run nix-shell -p nix-info --run "nix-info -m" and paste the result.


***@***.***:~/nixops/aij/unstable$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.50, NixOS, 23.11 (Tapir), 23.11.git.bfb7dfec93f3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos-21.11pre329341.9e70e9f732f"`
 - nixpkgs: `/etc/nixos/aij/unstable`

**Comment by ElyesH** [comment] 2023-10-06 05:53
Hi

Thanks, Ivan, for bisecting and also submitting the fix for this:

https://review.coreboot.org/c/coreboot/+/78239

Kyösti

**Comment by lamby** [comment] 2023-10-11 12:00
As I understand this issue (I am, alas, not a NixOS user or developer), the root cause of this issue is in `coreboot` rather than `diffoscope`. If this is incorrect, please let me know — otherwise, I will assume that no action is needed on `diffoscope`'s part. :+1:

**Closed** 2024-05-01 20:04 UTC
Labels: 0.kind: build failure
