### ISSUE TITLE
docker tools layering with pullImage is broken

### ISSUE THREAD

**Issue by purefn** [NixOS/nixpkgs#27294] opened 2017-07-10 22:25 UTC
Prior to commit 8d3cb0af9e24b867df45fc7f35eddbf3e4449404, you could layer images using `pullImage` by doing this

```
with import ((import <nixpkgs> { }).fetchFromGitHub {
 owner = "NixOS";
 repo = "nixpkgs";
 rev = "4cccbc256c3225c1cbfc58faff7149cc59b98be4";
 sha256 = "0gk8zw5rd5198w8rrskzw7vj9yz3555gs9d6wpfklh2lz0sh5m6z";
 }) { };

with pkgs.dockerTools;

rec {
  redis = buildImage {
    name = "redis";
    tag = "latest";

    # for example's sake, we can layer redis on top of bash or debian
    fromImage = pullImage {
      imageName = "alpine";
      imageTag = "3.3";
      # imageId = "f58d61a874bedb7cdcb5a409ebb0c53b0656b880695c14e78a69902873358d5f";
      sha256 = "10wbq7633vg8j5jp692a7kpqg0pki06g656i26n5cyk1ygv9wqfm";
    };

    contents = pkgs.redis;
    runAsRoot = ''
      mkdir -p /data
    '';

    config = {
      Cmd = [ "/bin/redis-server" ];
      WorkingDir = "/data";
      Volumes = {
        "/data" = {};
      };
    };
  };
}
```

Build with `nix-build -A redis redis.nix`.

After that commit, layering with `pullImage` no longer works. Instead, when you do `docker load < result`, the image that gets loaded is the alpine image.

Looking at the created file, you can see that both layers are present

```
$ tar tf result
./
./54c0c062f9ef94fc586886c822ddb34c79aca49b04ce57b40347391945f3a2bb/
./54c0c062f9ef94fc586886c822ddb34c79aca49b04ce57b40347391945f3a2bb/layer.tar
./54c0c062f9ef94fc586886c822ddb34c79aca49b04ce57b40347391945f3a2bb/json
./54c0c062f9ef94fc586886c822ddb34c79aca49b04ce57b40347391945f3a2bb/VERSION
./606fed0878ec0dd7496630a8e2685b4aa8421bfdb210a000a6ca177831357fef.json
./16428f4439fde02399c3c772d694299fdf02cf01ddb2bd70569f1c611cb1b06d/
./16428f4439fde02399c3c772d694299fdf02cf01ddb2bd70569f1c611cb1b06d/layer.tar
./16428f4439fde02399c3c772d694299fdf02cf01ddb2bd70569f1c611cb1b06d/json
./16428f4439fde02399c3c772d694299fdf02cf01ddb2bd70569f1c611cb1b06d/VERSION
./manifest.json
./repositories
```

Expanding further, you can which layer has redis

```
$ tar tf tmp/16428f4439fde02399c3c772d694299fdf02cf01ddb2bd70569f1c611cb1b06d/layer.tar 
./
./bin/
./bin/redis-sentinel
./bin/redis-benchmark
./bin/redis-check-aof
./bin/redis-check-rdb
./bin/redis-cli
./bin/redis-server
./data/
./.wh.proc
./.wh.sys
nix/
nix/store/
nix/store/vzhrb2vwp5z5ijzaigrah9pifp3nn41p-glibc-2.25/
nix/store/vzhrb2vwp5z5ijzaigrah9pifp3nn41p-glibc-2.25/etc/
<snip>
```

and which layer has alpine

```
$ tar tf tmp/54c0c062f9ef94fc586886c822ddb34c79aca49b04ce57b40347391945f3a2bb/layer.tar 
bin/
bin/ash
bin/base64
bin/bbconfig
bin/busybox
bin/cat
bin/catv
bin/chgrp
bin/chmod
bin/chown
bin/conspy
<snip>
```

The problem is that the `manifest.json` only includes the alpine layer and the alpine repo tags

```
$ cat manifest.json 
[{"Config":"606fed0878ec0dd7496630a8e2685b4aa8421bfdb210a000a6ca177831357fef.json","RepoTags":["alpine:3.3"],"Layers":["54c0c062f9ef94fc586886c822ddb34c79aca49b04ce57b40347391945f3a2bb/layer.tar"]}]
```

**Comment by purefn** [comment] 2017-07-10 22:26
@puffnfresh @lethalman @matejc

**Comment by matejc** [comment] 2017-07-14 12:38
It is not the problem in pullImage, because it uses docker command to pull image and will always be compatible with current docker, the problem is in the logic of buildImage, it does include logic of extracting tars and other low level stuff, maybe it was some day compatible with docker logic but I am sure it is not anymore because docker is in active development, it is bound to change even more in the near future.

Possible solution (it is not ideal, as pullImage is not) is that we use docker directly like in pullImage and use Dockerfile to generate combined image:

1. load base image to docker
2. Dockerfile .. something in the lines of this
```
FROM ${baseImage.name}
ADD  ${contents[0]}  /
ADD  ${contents[1]}  /
.
.
.
```
3. run it and export the image to nix store

it is far from ideal, but I think this is the only way unless we have someone that wants to actively develop dockerTools

**Comment by puffnfresh** [comment] 2017-07-26 21:24
Duplicated by #27632

**Comment by globin** [comment] 2017-08-03 09:52
This is fixed on master

**Closed by globin** 2017-08-03 09:52 UTC
