### ISSUE TITLE
Calibre doesn't run

### ISSUE THREAD

**Issue by kephas** [NixOS/nixpkgs#132045] opened 2021-07-30 09:08 UTC
### Describe the bug
Just after install, running calibre ends with `SIGABRT`.

### Steps To Reproduce
1. nix-env -i calibre
2. calibre

### Expected behavior
Calibre should run.

### Screenshots
```console
[pierre@viper:~]$ nix-shell -p calibre --run calibre
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Could not initialize GLX
/tmp/nix-shell-2060922-0/rc: line 1: 2060941 Aborted                 calibre
```

### Notify maintainers
@pSub @AndersonTorres 

### Metadata
```console
[pierre@viper:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.0-7-amd64, Debian GNU/Linux, 11 (bullseye)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.12`
 - channels(pierre): `"nixpkgs-21.11pre293448.2a1c29ef4ba"`
 - nixpkgs: `/home/pierre/.nix-defexpr/channels/nixpkgs`
```

**Comment by veprbl** [comment] 2021-07-31 00:14
This is a duplicate of  #9415
A common workaround is to use https://github.com/guibou/nixGL

**Comment by kephas** [comment] 2021-07-31 06:37
Isn't a bug that this package's default state is to not run? Why not make GL-depending packages use nixGL by default?

**Comment by veprbl** [comment] 2021-07-31 23:08
> Isn't a bug that this package's default state is to not run? Why not make GL-depending packages use nixGL by default?

Yes, it's a bug. My guess is that the problems would be that nixGL is inherently impure, or that adding it to every OpenGL package might require adding every possible driver into the closure.

**Comment by kephas** [comment] 2021-08-17 20:13
Would it be a problem to include all drivers in the closure, and leave the choice at run time?

**Comment by kephas** [comment] 2022-10-15 22:50
@AndersonTorres why close the bug? It's stale but the problem persists. `calibre` will run fine with the help of `nixGL` but not without, and there's no warning, documentation or helper script for that.

**Comment by AndersonTorres** [comment] 2022-10-16 04:42
I believed it was already closed.

**Closed** 2024-03-26 13:46 UTC
Labels: 0.kind: bug, 6.topic: non-nixos

**Comment by kephas** [comment] 2024-04-02 10:30
@patka-123 sorry for the late reply, but it's still true for me with `/nix/store/glic4pdqdl2rs4xirc1j406hyd16mcfz-calibre-7.1.0`:

```
$ nix-shell -p calibre --run calibre
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
Could not initialize GLX
/tmp/nix-shell-3617183-0/rc : ligne 3 : 3621404 Aborted                 (core dumped)calibre
```

(but it works great with `nixGL`)
