### ISSUE TITLE
"dig" not in PATH after nix-shell -p bind

### ISSUE THREAD

**Issue by Thomas131** [NixOS/nixpkgs#187805] opened 2022-08-21 23:32 UTC
Hi,
I am new to NixOS. Sorry if I report something wrong or stupid, but this seems like a bug:

### Describe the bug
When switching to `nix-shell -p bind` (as recommended by nix when I try to execute the dig command), dig is still not found in the PATH.

### Steps To Reproduce
```sh
[root@server123:/]# nix-shell -p bind

[nix-shell:/]# dig example.com
The program 'dig' is not in your PATH. You can make it available in an
ephemeral shell by typing:
  nix-shell -p bind

[nix-shell:/]# echo $PATH
/nix/store/s0366zs7fkc3gffmc1fqnam896fvzi0y-bash-interactive-5.1-p16/bin:/nix/store/nln9q1q55z0cd8aw57vi0l10j1prgqsk-patchelf-0.14.5/bin:/nix/store/lsm1agffk0qv9yym55b3zdzx76gjkxcq-gcc-wrapper-9.5.0/bin:/nix/store/zva0i57cbablmnvrfx8zcr9jmpjqpgnd-gcc-9.5.0/bin:/nix/store/xrcvvcp3vwbr0gif0g024wmb938xzqhq-glibc-2.35-163-bin/bin:/nix/store/7mjrrj68fz00x7im4nkjv6sc298fqq95-coreutils-9.1/bin:/nix/store/1vn18k40gdamllkkw9wqsp1m0imaf396-binutils-wrapper-2.38/bin:/nix/store/4m0ql1nd3kahkcj9ah1s78pc689mfmhf-binutils-2.38/bin:/nix/store/hl8nri87pl7fkcdfy49aavaml83yykpa-bind-9.18.4/bin:/nix/store/7mjrrj68fz00x7im4nkjv6sc298fqq95-coreutils-9.1/bin:/nix/store/s9x16skrq8f9ykzrxysa98c06q3q9z1k-findutils-4.9.0/bin:/nix/store/3a7sdmh9hwzkwww346dfwxcw2q793ram-diffutils-3.8/bin:/nix/store/vfndbx1ylzlr660bgm48222bsplyp0hs-gnused-4.8/bin:/nix/store/450zz8z1vhb0mhmjvqg0ngvk7p2njzpx-gnugrep-3.7/bin:/nix/store/jj9ypmp0hpx2jy67niq6n4a7mi16mzd3-gawk-5.1.1/bin:/nix/store/48xvsfhmfixskfpazgvwn4xjgbayi1z4-gnutar-1.34/bin:/nix/store/avnsbf9d3m8dqynvlzhda5p7rl3fbnhi-gzip-1.12/bin:/nix/store/l4fqm8z2yqp96r2zbc5bn5g1qa66b6qq-bzip2-1.0.8-bin/bin:/nix/store/yaikhg6vn6hikb9fg01dfy082z52im7h-gnumake-4.3/bin:/nix/store/0rvrid3zvjcdn33685f4d3qncwiajnrh-bash-5.1-p16/bin:/nix/store/gmnikjmndd25ida53l51gqhw4kwadcdx-patch-2.7.6/bin:/nix/store/dcs3ab4xc0g015p0gwmgx9f6g0899scz-xz-5.2.5-bin/bin:/nix/store/c61z5409smzwagkhiv1d3fb6hxkr62g3-file-5.42/bin:/run/wrappers/bin:/root/.nix-profile/bin:/etc/profiles/per-user/root/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin

[nix-shell:/]# ls -l /nix/store/hl8nri87pl7fkcdfy49aavaml83yykpa-bind-9.18.4/bin
total 1372
-r-xr-xr-x 1 root root  13168 Jan  1  1970 arpaname
-r-xr-xr-x 1 root root  23536 Jan  1  1970 ddns-confgen
-r-xr-xr-x 1 root root  53712 Jan  1  1970 dnssec-cds
-r-xr-xr-x 1 root root  39104 Jan  1  1970 dnssec-dsfromkey
-r-xr-xr-x 1 root root  39160 Jan  1  1970 dnssec-importkey
-r-xr-xr-x 1 root root  42032 Jan  1  1970 dnssec-keyfromlabel
-r-xr-xr-x 1 root root  51528 Jan  1  1970 dnssec-keygen
-r-xr-xr-x 1 root root  33576 Jan  1  1970 dnssec-revoke
-r-xr-xr-x 1 root root  42264 Jan  1  1970 dnssec-settime
-r-xr-xr-x 1 root root 105648 Jan  1  1970 dnssec-signzone
-r-xr-xr-x 1 root root  34048 Jan  1  1970 dnssec-verify
-r-xr-xr-x 1 root root  53016 Jan  1  1970 mdig
-r-xr-xr-x 1 root root 573568 Jan  1  1970 named
-r-xr-xr-x 1 root root  38816 Jan  1  1970 named-checkconf
-r-xr-xr-x 1 root root  38072 Jan  1  1970 named-checkzone
-r-xr-xr-x 1 root root  38072 Jan  1  1970 named-compilezone
-r-xr-xr-x 1 root root  13912 Jan  1  1970 named-journalprint
-r-xr-xr-x 1 root root  19000 Jan  1  1970 named-rrchecker
-r-xr-xr-x 1 root root  14040 Jan  1  1970 nsec3hash
-r-xr-xr-x 1 root root  43424 Jan  1  1970 rndc
-r-xr-xr-x 1 root root  23632 Jan  1  1970 rndc-confgen
-r-xr-xr-x 1 root root  23536 Jan  1  1970 tsig-keygen

[nix-shell:/]# 
```

### Expected behavior
Either the nix-shell-hint should reflect the correct command or dig should be in the PATH of `nix-shell -p bind`. 

### Additional context
I haven't used bind on this machine.

### Notify maintainers
@globin 

### Metadata
 - system: `"aarch64-linux"`
 - host os: `Linux 5.15.55, NixOS, 22.11 (Raccoon), 22.11pre398667.39d7f929fbc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by vcunat** [comment] 2022-08-22 06:08
You do get it by `nix-shell -p bind.dnsutils` or `nix-shell -p dnsutils`.  (Yes, this case is confusing.)

**Comment by Thomas131** [comment] 2022-08-22 08:55
Hi&Thanks @vcunat !! Is there a easy way to change the hint to one of those commands? (If not feel free to close the issue since it is not that important to me)

**Comment by marmolak** [comment] 2022-08-31 17:50
Hi. Same here. It's little bit confusing.  Issues here helped.

**Comment by Yorwba** [comment] 2022-09-06 18:18
This issue seems like a duplicate of #140897 , which points to https://github.com/NixOS/nixos-channel-scripts/issues/26 as the reason for the incorrect hint.

**Comment by vcunat** [comment] 2022-09-06 18:21
OK, let's close this one as duplicate to concentrate the discussion better.

**Closed by vcunat** 2022-09-06 18:21 UTC
Labels: 0.kind: bug

**Comment by sanderhollaar** [comment] 2022-10-15 12:20
`systemd[1]: Started DNSSEC key rollover.
nsd-dnssec-start[492709]: /nix/store/57fladh8c6dnzcva1fy7qq9wik5vw0bq-unit-script-nsd-dnssec-start/bin/nsd-dnssec-start: line 7: /nix/store/3h8ayi2ksj6kmfxb1qj8f2wj06a1jiay-bind-9.18.7/bin/dnssec-keymgr: No such file or directory
systemd[1]: nsd-dnssec.service: Main process exited, code=exited, status=127/n/a`

I would be happy to test.
