### ISSUE TITLE
Package request: lmstudio-cuda / lmstudio-rocm

### ISSUE THREAD

**Issue by jee-mj** [NixOS/nixpkgs#340346] opened 2024-09-07 18:08 UTC
Package `lmstudio` already exists as is.

**LM Studio is an easy to use desktop app for experimenting with local and open-source Large Language Models (LLMs)**

* homepage URL: https://lmstudio.ai/
* source URL: https://github.com/NixOS/nixpkgs/blob/6f6c45b5134a8ee2e465164811e451dcb5ad86e3/pkgs/by-name/lm/lmstudio/package.nix
* license: unfree
* platforms:
    * [aarch64-darwin](https://hydra.nixos.org/job/nixos/release-24.05/nixpkgs.lmstudio.aarch64-darwin)
    * [aarch64-linux](https://hydra.nixos.org/job/nixos/release-24.05/nixpkgs.lmstudio.aarch64-linux)
    * [i686-linux](https://hydra.nixos.org/job/nixos/release-24.05/nixpkgs.lmstudio.i686-linux)
    * [x86_64-linux](https://hydra.nixos.org/job/nixos/release-24.05/nixpkgs.lmstudio.x86_64-linux)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

---

@cig0 @eeedean regarding `pkgs.lmstudio`

This package does not install correctly. LMStudio supports GPU rendering which does not work with this package.

Instead of submitting this as a bug report, I thought that it might be wiser to submit it as a package request because someone might want to use their threadripper without a gpu to run models for whatever reason.

I am not touching LMStudio anymore because in their discord a reputable super mod has mentioned that they will never open source the project, and I am going to GPT4ALL, but since you guys maintain the standard `lmstudio` package I'm raising this ticket for anyone who doesn't mind/prefers LMStudio.

Regards,

jee-mj

**Comment by eeedean** [comment] 2024-09-07 20:34
Thanks for your report! 

@cig0 , @crertel , unfortunately, I'm aarch64-darwin and headless x86_64-linux, only. Are you guys maybe running an x86_64-linux with GPU and can verify, test, maybe even fix our package? 

@jee-mj , if you had any further pointer for us, maybe that's helpful, too. 

Anyway: I unfortunately cannot really do a lot about it at this point in time due to lack of a suitable computer to reproduce and debug the issue.

**Comment by jee-mj** [comment] 2024-09-07 20:39
> Thanks for your report!
> 
> @cig0 , @crertel , unfortunately, I'm aarch64-darwin and headless x86_64-linux, only. Are you guys maybe running an x86_64-linux with GPU and can verify, test, maybe even fix our package?
> 
> @jee-mj , if you had any further pointer for us, maybe that's helpful, too.
> 
> Anyway: I unfortunately cannot really do a lot about it at this point in time due to lack of a suitable computer to reproduce and debug the issue.

Hi @eeedean, thank you for the quick response. Yes, I can test this for you. You can refer to GPT4ALL in nixpkgs for reference and you can also have a look at [this link to nixos search](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=cudaPackages) for the relevant packages since I will not be assisting in development for this black-box product.

**Comment by crertel** [comment] 2024-09-08 21:41
I'll test this tonight, but as far as I'm aware this does in fact properly use the Nvidia GPU which I have.

The blackbox situation is less than ideal (and Lord knows that the constantly changing paths for the binaries on their website were irksome) but I'd rather have this than not--the alternative was downloading it and using `appimage-run`.

**Comment by crertel** [comment] 2024-09-17 18:59
Using the current `lmstudio` @ 0.3.2 in unstable I see that this does in fact use my nvidia card. So, I _think_ we're good, unless I'm missing something.

**Comment by crertel** [comment] 2024-09-17 19:02
I'll close this in the next day or two if nobody objects. Thanks for checking in @eeedean and @jee-mj !

**Comment by ob7** [comment] 2024-10-23 21:56
It does detect nvidia cards, but it does not detect AMD.  Tested using Nvidia 3070 to confirm it detects Nvidia GPU.  Tested with AMD Vega Frontier to confirm it does not detect AMD gpu.

**Comment by crertel** [comment] 2024-10-31 05:09
@ob7 I'll go ahead and close this then. Thanks for the repro!

**Closed by crertel** 2024-10-31 05:09 UTC
Labels: 0.kind: packaging request

**Comment by ob7** [comment] 2025-01-20 19:36
how do you get Vulcan driver's working?  I was running rocm.  Had to go back to 24.05 I think for it to compile, but switching to unstable afterward somehow worked

**Comment by HuzaifaTP** [comment] 2025-01-21 06:18
@ob7 nothing at all really for getting vulkan, lmstudio automatically on startup detected vulkan runtime and I was able to select and load it, with 7900XT graphics its a little strange as ROCM is stated as being incompatible but yet upon selecting it and using its run time to load and query a model it is functioning fine by which I deduce that rocm works on lmstudio but that is specifically for 7900XT, tried the same on 5700XT but it ROCM runtime failed. Vulkan worked for both cards

      hardware.amdgpu.amdvlk.enable = true;

**Comment by KingKrouch** [comment] 2025-03-06 17:33
Quick question: ROCM usually works with open source drivers for me without installing amdvlk (Which has historically gave me performance issues and graphical bugs in other things, like games). Is there a way that I can set up ROCM in LM Studio using the open source drivers? I've followed ob7's instructions without much luck.

**Comment by jee-mj** [comment] 2025-03-23 01:42
@KingKrouch downgrade / use older version.

https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/351

**Comment by HuzaifaTP** [comment] 2025-03-23 04:22
> @ob7 nothing at all really for getting vulkan, lmstudio automatically on startup detected vulkan runtime and I was able to select and load it, with 7900XT graphics its a little strange as ROCM is stated as being incompatible but yet upon selecting it and using its run time to load and query a model it is functioning fine by which I deduce that rocm works on lmstudio but that is specifically for 7900XT, tried the same on 5700XT but it ROCM runtime failed. Vulkan worked for both cards
> 
>       hardware.amdgpu.amdvlk.enable = true;
> 

An update on this rocm was not being detected as I had not set the right environment variable for my GPU version (11.0.0), after which rocm runtime was able to use GPU for compute

**Comment by HuzaifaTP** [comment] 2025-04-21 14:16
> > > [@ob7](https://github.com/ob7) nothing at all really for getting vulkan, lmstudio automatically on startup detected vulkan runtime and I was able to select and load it, with 7900XT graphics its a little strange as ROCM is stated as being incompatible but yet upon selecting it and using its run time to load and query a model it is functioning fine by which I deduce that rocm works on lmstudio but that is specifically for 7900XT, tried the same on 5700XT but it ROCM runtime failed. Vulkan worked for both cards
> > > ```
> > >   hardware.amdgpu.amdvlk.enable = true;
> > > ```
> > 
> > 
> > An update on this rocm was able to use GPU as I had not set the right environment variable for my GPU version (11.0.0) which determines the underlying binaries that the runtime will execute for the compatible version, after which rocm runtime was able to use GPU for compute
> 
> Got an idea on how to do that?

@KingKrouch via the following variables, let me know if it works :
```
    environment.variables = {
      HSA_OVERRIDE_GFX_VERSION = "11.0.0";
    };
```
