### ISSUE TITLE
Package request: OpenComic

### ISSUE THREAD

**Issue by WenasPRG** [NixOS/nixpkgs#323213] opened 2024-06-28 18:10 UTC
**OpenComic request**

**Metadata**

* homepage URL: https://github.com/ollm/OpenComic
* source URL: https://github.com/ollm/OpenComic.git
* license: gpl3
* platforms: linux, linux arm, windows, macos, macos arm

**Comment by eclairevoyant** [comment] 2024-06-28 18:17
duplicate of #280883

**Closed by eclairevoyant** 2024-06-28 18:17 UTC
Labels: 2.status: duplicate, 0.kind: packaging request
