### ISSUE TITLE
Package request: vivarium

### ISSUE THREAD

**Issue by sogreatandpowerfull** [NixOS/nixpkgs#213611] opened 2023-01-30 17:19 UTC
**Project description**
A dynamic tiling Wayland compositor using wlroots 

**Metadata**

* homepage URL: https://github.com/inclement/vivarium
* source URL: https://github.com/inclement/vivarium
* license: gpl3
* platforms: linux

**Comment by pinn3** [comment] 2023-01-30 20:34
Duplicate of https://github.com/NixOS/nixpkgs/issues/172052

**Closed** 2023-01-30 23:16 UTC
Labels: 0.kind: packaging request
