### ISSUE TITLE
Secure Boot support

### ISSUE THREAD

**Issue by dominiktr** [NixOS/nixpkgs#255643] opened 2023-09-17 10:47 UTC
I'm unable to run an installer due to the lack of Secure Boot support. I'm aware of post-installation workarounds; however, I use Windows 11 with BitLocker enabled. Therefore, I would prefer not to turn off Secure Boot at all.

Are there plans to officially implement Secure Boot in the installer? If so, when can I expect it?

**Comment by Tungsten842** [comment] 2023-09-17 14:22
https://github.com/nix-community/lanzaboote

**Comment by Gerg-L** [comment] 2023-09-17 22:12
from lanzaboote:
> ## State of Upstreaming to Nixpkgs
>  SecureBoot is available by adding this project to your configuration.
> It relies on bootspec which is enabled by default since NixOS 23.05.
> An optimistic plan is to have a "in-tree" feature preview of Lanzaboote as part of NixOS 23.11.

**Comment by Artturin** [comment] 2023-10-07 17:17
Dupe of https://github.com/NixOS/nixpkgs/issues/42127

**Closed by Artturin** 2023-10-07 17:17 UTC
Labels: 2.status: duplicate, 0.kind: enhancement

**Comment by JohnRTitor** [comment] 2024-12-06 17:49
Duplicate of https://github.com/NixOS/nixpkgs/issues/42127
