### ISSUE TITLE
Package request: kanboard

### ISSUE THREAD

**Issue by jtara1** [NixOS/nixpkgs#339086] opened 2024-09-02 19:36 UTC
**Project description**
self-hosted kanban board using sqlite

**Metadata**

* homepage URL: https://kanboard.org/
* source URL: https://github.com/kanboard/kanboard
* license: mit
* platforms: N/A (web app)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-09-02 20:47
duplicate of #288788

**Closed** 2024-09-02 20:47 UTC
Labels: 0.kind: packaging request
