### ISSUE TITLE
17.09.2253.559ebb7ed02 image, both minimal and graphical, fail installation with: `changing mode of '/nix/store/[...]-update-users-groups.pl' to 100444: Read-only file system`

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixpkgs#32242] opened 2017-12-01 21:02 UTC
## Issue description

The current iso cannot complete a `nixos-install`.

The issue has been reported by a [couple users on IRC](https://botbot.me/freenode/nixos/msg/94159173/), and I was able to reproduce easily.

Known problematic isos:

 * https://d3g5gsiof5omrk.cloudfront.net/nixos/17.09/nixos-17.09.2253.559ebb7ed02/nixos-graphical-17.09.2253.559ebb7ed02-x86_64-linux.iso
 * https://d3g5gsiof5omrk.cloudfront.net/nixos/17.09/nixos-17.09.2253.559ebb7ed02/nixos-minimal-17.09.2253.559ebb7ed02-x86_64-linux.iso

```
nixos-install
[installation noise]
error: changing mode of '/nix/store/[...]-update-users-groups.pl' to 100444: Read-only file system
# echo $?
1
```

### Steps to reproduce

 * Boot the image (VirtualBox is fine).
 * Create a partition (I did dos/mbr, full disk one parttion)
 * `mkfs.ext4 -L nixos /dev/sda1` as in the manual
 * Mount it at /mnt as in the manual
 * nixos-generate-config --root /mnt as in the manual
 * *edited the config for grub mbr boot, but this might not be necessary*
 * `nixos-install`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

> *This was manually transcribed, sorry if there are typos*

```
 - system: x86_64-linux
 - host os: Linux 4.9.65, NixOS, 17.09.2253.559ebb7ed02 (Hummingbird)
 - multi-user?: no
 - sandbox: yes
 - version: nix-env (Nix) 1.11.15
 - channels(root): nixos-17.09.2253.559ebb7ed02
 - nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs
```

## Workaround

Use these (known working isos):

 * https://d3g5gsiof5omrk.cloudfront.net/nixos/17.09/nixos-17.09.2075.ac35504065/nixos-minimal-17.09.2075.ac35504065-x86_64-linux.iso
 * https://d3g5gsiof5omrk.cloudfront.net/nixos/17.09/nixos-17.09.2075.ac35504065/nixos-graphical-17.09.2075.ac35504065-x86_64-linux.iso

**Comment by samueldr** [comment] 2017-12-01 23:27
Using `nixos-17.09.git.6b8833d-x86_64-linux.iso`, built from the previously release channel worked. The issue should be from a change between 6b8833d and 559ebb7ed02

**Comment by samueldr** [comment] 2017-12-01 23:59
```
~/.../nixpkgs/nixos $ git rev-parse HEAD
559ebb7ed02f88ce8ed5ab38e849ad01cdbebcc8
```

Using this command:

```
nix-build -A config.system.build.isoImage -I nixos-config=modules/installer/cd-dvd/installation-cd-minimal.nix default.nix
```

The installation can complete.

Here are the nix-info for the system from which the working image was built. Don't know what factors could make it a different image, other than plain old corruption.

```
~/.../nixpkgs/nixos $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.61, NixOS, 17.09.git.78eed74 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(samuel): `"unstable-18.03pre120398.aeff3080d0"`
 - nixpkgs: `/etc/nixos/nixpkgs`
```

**Comment by alexanderkjeldaas** [comment] 2017-12-02 11:14
I got this today when installing a clean system using the official image.

**Comment by alexanderkjeldaas** [comment] 2017-12-02 11:16
I feel like this issue should be merged or kept open until a test is available.

**Comment by samueldr** [comment] 2017-12-02 13:39
[Another report on IRC, for unstable though, with unknown specific image](https://botbot.me/freenode/nixos/msg/94181815/).

**Comment by yellowgh0st** [comment] 2017-12-02 15:06
Hydra-built 18.03pre121253 2f1a818d00 affected too.

https://d3g5gsiof5omrk.cloudfront.net/nixos/unstable/nixos-18.03pre121253.2f1a818d00/nixos-graphical-18.03pre121253.2f1a818d00-x86_64-linux.iso

I reproduced it the same way.

http://i.imgur.com/ylRIf2g.png

**Comment by orivej** [comment] 2017-12-02 17:40
It's a wonder that `nixos.tests.installer.simple` [passes](https://hydra.nixos.org/build/65203535) when on my hydra (with `update-users-groups.pl` being writable among others) it fails just like the installer on the cdrom. Are the published images built on different hosts from those that run the tests?

**Comment by orivej** [comment] 2017-12-02 18:40
I tried to compare machines that build [nixos.iso_minimal](https://hydra.nixos.org/job/nixos/unstable-small/) and machines that run [nixos.tests.installer.simple](https://hydra.nixos.org/job/nixos/unstable-small/nixos.tests.installer.simple.x86_64-linux). These sets are almost disjoint (with `wendy` and `52.91.90.209` building and `lucifer` and `packet-t2-4` testing), however occasionally the testing machines do build an iso, and the installer on the iso works, e.g. https://hydra.nixos.org/build/65178276 from two days ago.

**Comment by davidak** [comment] 2017-12-02 20:01
On my system (Macbook 2,1 with coreboot) `nixos-17.09.2253.559ebb7ed02` even don't boot.

![img_20171202_192030](https://user-images.githubusercontent.com/91113/33519258-cc4bd9b8-d7a3-11e7-9218-101a5f300427.jpg)

`17.09.2075.ac35504065` works.

**Comment by orivej** [comment] 2017-12-02 20:21
This is a different issue, and looks like the problem with the media (incompletely written image, or bad USB connection).

According to the hypothesis that the only issue is `rw` files on some build machines, one of the latest good `release-17.09` images is [nixos-minimal-17.09.2241.f9390d652f9-x86_64-linux.iso](https://hydra.nixos.org/build/65100017/download/1/nixos-minimal-17.09.2241.f9390d652f9-x86_64-linux.iso) made by `lucifer` in https://hydra.nixos.org/build/65100017, and indeed it works.

**Comment by dezgeg** [comment] 2017-12-03 01:10
I suppose 52.91.90.209 is an EC2 machine built from the images before the commit https://github.com/NixOS/nixpkgs/commit/f5b3f2c5a7f2b51e80ac32fb47fd1d7d3e475ad1.

**Comment by dezgeg** [comment] 2017-12-03 01:52
I pushed a hack (574526d510bbfabd66fc251ef6054604c8221ca3) that should prevent building ISOs with such bad paths.

**Comment by orivej** [comment] 2017-12-03 05:24
Good idea to break invalid builders! It works. I have also confirmed that my hydra cluster that exhibits the same issue was deployed from the image with wrong permissions and times in /nix/store, and all the wrong paths existed from the moment of deployment.

**Comment by vcunat** [comment] 2017-12-03 18:59
I think we should fix the underlying problem on 17.09 as well.  Do you think it's better to have b8cc69b3 or f5b3f2c or something else?

**Comment by dezgeg** [comment] 2017-12-03 19:14
I think they are already all cherry-picked, but the EC2 base images are still very old or something.

**Comment by vcunat** [comment] 2017-12-03 19:41
Right, the first way is picked.  I don't know why I didn't check that before posting :-/

**Comment by vcunat** [comment] 2017-12-03 19:43
@edolstra: apparently we would better regenerate EC2 images of Hydra build machines. (Or something like that; I doubt our permissions can do it.)

**Comment by vcunat** [comment] 2017-12-03 19:44
In any case, with the hack in nixpkgs now, the issue shouldn't be experienced in newly published images.

**Comment by dezgeg** [comment] 2017-12-03 20:45
Well we still don't have an actual channel with working ISOs since the build job very frequently ends up on the EC2 nodes. So reopening until the problem is really gone.

**Comment by vcunat** [comment] 2017-12-04 14:10
So, after dozens of job-restart commands over several hours, I think all the four primary channels are now after your hack-fix commit. :tada:

**Comment by dezgeg** [comment] 2018-01-24 18:16
I believe this has been fixed for a while.

**Closed by dezgeg** 2018-01-24 18:16 UTC
Labels: 0.kind: bug
