### ISSUE TITLE
services.mysql.package needs to be set, but does not appear in man configuration.nix

### ISSUE THREAD

**Issue by ocharles** [NixOS/nixpkgs#10917] opened 2015-11-09 11:03 UTC
If you add

``` nix
services.mysql.enable = true;
```

then `nixos-rebuild switch` fails because `services.mysql.package` isn't defined. However, if you search `configuration.nix`, this option isn't even mentioned, which leaves users in the dark as to what they are meant to set this to.

**Comment by mucaho** [comment] 2015-11-16 18:03
Yes, I have the same problem with `15.09`. So what do you have to set `services.mysql.package` to?

**Comment by ocharles** [comment] 2015-11-18 16:35
@mucaho:

```nix
{ config, pkgs, ... }:
{
  services.mysql = { 
    enable = true; 
    extraOptions = ''
      max_allowed_packet = 64M
    '';
    package = pkgs.mysql;
  };
}
```

is working for me.

**Comment by ocharles** [comment] 2015-12-20 18:12
Looks like this is a case of adding this:

```nix
  config = mkIf config.services.mysql.enable {

    services.mysql.package =
      mkDefault pkgs.mysql;
```

Do people think that would do the job?

**Comment by layus** [comment] 2016-02-29 21:49
@ocharles It seems to me that the option does exist in nixos options, and does indeed not exist in configuration.nix. This is one of the rare cases where you must provide an option.
See the commit message of 1ce6fff4 for the reason behind the scene.
This is also well explained for postgres (https://nixos.org/nixos/manual/index.html#module-postgresql).

Note that there is information about this in https://nixos.org/nixos/options.html.
So this is not a bug, but you are most welcome to update the documentation of this option or the error message.
You could even add an assert with a more verbose failure in the module.
A pull request with better documentation would be merged very fast!

PS @mucaho: using pkgs.mysql works but may not be reliable.
/cc @shelvy, want to comment on this issue and/or close it ?

**Comment by joachifm** [comment] 2016-12-17 03:45
I believe this was resolved by 4358d3d43938666834d3e1fd5a8ea69b49c08112

**Comment by ocharles** [comment] 2016-12-17 09:04
Hm, is that a good idea though? Above has a fairly convincing argument as
to why you wouldn't want such a default.

**Comment by joachifm** [comment] 2016-12-17 10:37
@ocharles I did not know about that. I had thought that those who cared *would* pin it regardless, but that is perhaps too naive. I shall revert to the old behavior.

**Comment by Profpatsch** [comment] 2018-06-24 19:58
(triage) status?

**Comment by layus** [comment] 2018-06-24 20:34
@Profpatsch The original issue is fixed. I can find services.mysql.package in configuration.nix. The description could be improved tough.

**Comment by Profpatsch** [comment] 2018-06-25 05:44
@layus would you be willing to prepare a patch?

**Comment by Profpatsch** [comment] 2018-06-25 08:37
Ah, I see. It is possible to mark options as default, in this case this seems to have been a bug where `package` had no default. Having a `package` option for services is customary; as a first step I suggest adding a section documenting such patterns to the wiki, somewhere around https://nixos.wiki/wiki/NixOS_Modules

**Closed by Profpatsch** 2018-06-25 08:37 UTC
Labels: 0.kind: enhancement, 3.skill: good-first-bug, 3.skill: sprintable, 3.skill: trivial, 6.topic: nixos, 9.needs: documentation
