### ISSUE TITLE
Steam: Cannot install due to HTTP 404 errors

### ISSUE THREAD

**Issue by setzer22** [NixOS/nixpkgs#86588] opened 2020-05-02 13:49 UTC
**Describe the bug**
I've tried to install steam, both from the 20.03 and unstable channels. In both cases I get errors when the builder tries to download files from URLs starting with `https://public.abbradar.moe/steamrt/...`

```
trying https://public.abbradar.moe/steamrt/pool/main/s/steam-runtime-tools/libsteam-runtime-tools-0-helpers_0.20200109.0-0+steamrt1.1+srt1_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
error: cannot download libsteam-runtime-tools-0-helpers.deb from any mirror

trying https://public.abbradar.moe/steamrt/pool/main/s/steam-runtime-tools/libsteam-runtime-tools-0-helpers_0.20200109.0-0+steamrt1.1+srt1_i386.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

trying https://public.abbradar.moe/steamrt/pool/main/s/steam-runtime-tools/libsteam-runtime-tools-0-relocatable-libs_0.20200109.0-0+steamrt1.1+srt1_amd64.deb
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

trying https://public.abbradar.moe/steamrt/pool/main/s/steam-runtime-tools/libsteam-runtime-tools-0-relocatable-libs_0.20200109.0-0+steamrt1.1+srt1_i386.deb
```

**To Reproduce**
1. Add `steam` to environment.systemPackages
2. Run `nixos-rebuild switch`

**Expected behavior**
Steam should be installed

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.35, NixOS, 20.03.1619.ab3adfe1c76 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1619.ab3adfe1c76"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**NOTE:** I'm using the stable channel. The unstable channel is obtained using fetchTarball at https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz as described in: https://stackoverflow.com/questions/48831392/how-to-add-nixos-unstable-channel-declaratively-in-configuration-nix  and the tarball was downloaded right now at the time of submitting the issue.

**Comment by pbogdan** [comment] 2020-05-02 14:03
FWIW I believe this should have been fixed in https://github.com/NixOS/nixpkgs/pull/86358 although the update may not yet have trickled into the `nixos-unstable` channel. Also haven't checked if the change was backported to 20.03.

**Comment by Enteee** [comment] 2020-05-02 17:17
#86358 was merged and is in unstable. As far as I can see, the artifacts were deleted already.

**Comment by Enteee** [comment] 2020-05-02 17:35
Yeah I think this is a duplicate of  #86358. Unstable was last updated 3 days ago.

**Comment by Enteee** [comment] 2020-05-02 17:56
You are right @pbogdan, #86358 fixed this. But unstable is 3 days old.
@setzer22: Either wait for unstable to update or install steam from master:
```
NIXPKGS_ALLOW_UNFREE=1 nix-env -f https://github.com/NixOS/nixpkgs/archive/master.tar.gz -iA steam
```

**Comment by prusnak** [comment] 2020-05-02 23:12
Unstable fixed in https://github.com/NixOS/nixpkgs/pull/86358
Backport to 20.03 in https://github.com/NixOS/nixpkgs/pull/86619

**Comment by flokli** [comment] 2020-05-02 23:35
Both PRs merged, it'll land in the channels soon. Closing here :-)

**Closed by flokli** 2020-05-02 23:35 UTC
Labels: 0.kind: bug, 6.topic: reproducible builds, 6.topic: steam

**Comment by setzer22** [comment] 2020-05-03 06:39
Many thanks!!

@Enteee: Thank you! I was just wondering exactly how would I go about into installing from master :)
