### ISSUE TITLE
gcc build references non-existing file

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#14827] opened 2016-04-19 16:17 UTC
```
nix-env -i gcc-wrapper-5.3.0
```

returns

```
replacing old ‘gcc-wrapper-4.9.3’
installing ‘gcc-wrapper-5.3.0’
these derivations will be built:
  /nix/store/ghgvdwccpbqd3p384fhfvij0cd6mpx4k-gcc-5.3.0.drv
  /nix/store/bvrpsxvk1n33jzbsdaha3pdm296l5qqc-gcc-wrapper-5.3.0.drv
building path(s) ‘/nix/store/6cz4kpllk5r51jckq4fida4a4irk3l53-gcc-5.3.0’, ‘/nix/store/ciz4kxnl2ry3mrm3amvn6hh8ra2kyriq-gcc-5.3.0-man’, ‘/nix/store/dwq06w8y30jyyfpcs655353rwqwd69hm-gcc-5.3.0-lib’, ‘/nix/store/kxw1hqwbsadrhibc8bsqf2223xjbq46i-gcc-5.3.0-info’
$CPATH is `/nix/store/k0vlb3rd8v00gp2sr38lfzvfvqfjvbqd-zlib-1.2.8-dev/include'
$LIBRARY_PATH is `/nix/store/k0vlb3rd8v00gp2sr38lfzvfvqfjvbqd-zlib-1.2.8-dev/lib'
cat: /nix/store/82brnl5h9690b06s9sq5h2mx0m293lch-clang-wrapper-3.7.1/nix-support/libc-ldflags-before: No such file or directory
```

**Comment by vcunat** [comment] 2016-04-19 16:41
This is on `x86_64-darwin`, right? (Otherwise I can't see why gcc would refer to clang.)

**Comment by 0xABAB** [comment] 2016-04-20 09:03
@vcunat Yes. (I should have specified that.)

**Comment by retrry** [comment] 2016-04-21 15:24
Duplicate of https://github.com/NixOS/nixpkgs/issues/14812 or https://github.com/NixOS/nixpkgs/issues/6148 ?

**Comment by matthewbauer** [comment] 2017-05-20 05:36
@vcunat Can you close this issue? It's been fixed... I would close it but I don't have the rights.

**Closed** 2017-05-20 06:44 UTC
Labels: 0.kind: bug, 6.topic: darwin
