### ISSUE TITLE
Infinite recursion when enabling enlightenment as DE

### ISSUE THREAD

**Issue by numinit** [NixOS/nixpkgs#100693] opened 2020-10-16 07:51 UTC
**Describe the bug**

I get infinite recursion when enabling enlightenment as my DE with the latest 20.03 nixpkgs:

```
error: while evaluating the attribute 'activationScript' of the derivation 'nixos-system-cyrus-20.03.3122.ff6fda61600' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/top-level.nix:103:5:
while evaluating the attribute 'system.activationScripts.script' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/activation-script.nix:68:9:
while evaluating 'textClosureMap' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/strings-with-deps.nix:70:35, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/activation-script.nix:89:18:
while evaluating 'id' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/trivial.nix:14:5, called from undefined position:
while evaluating the attribute 'text' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/activation-script.nix:9:5:
while evaluating the attribute 'text' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/strings-with-deps.nix:77:38:
while evaluating the attribute 'sources' of the derivation 'etc' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/etc/etc.nix:12:5:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/etc/etc.nix:20:20, called from undefined position:
while evaluating the attribute 'source' at undefined position:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:84:45, called from undefined position:
while evaluating the attribute 'value' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:379:9:
while evaluating the option `environment.etc.dbus-1.source':
while evaluating the attribute 'mergedValue' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:411:5:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:413:22, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:413:9:
while evaluating 'check' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/types.nix:251:15, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:414:14:
while evaluating the attribute 'serviceDirectories' of the derivation 'dbus-1' at /nix/store/bhbwzy0p7jhpnxy0ivax9ck9sx3kk1lh-nixos-20.03.3122.ff6fda61600/nixos/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/types.nix:263:14, called from undefined position:
while evaluating the attribute 'value' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:425:27:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:413:22, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:413:9:
while evaluating 'check' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/types.nix:251:15, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:414:14:
while evaluating the attribute 'passAsFile' of the derivation 'system-path' at /nix/store/bhbwzy0p7jhpnxy0ivax9ck9sx3kk1lh-nixos-20.03.3122.ff6fda61600/nixos/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating the attribute 'buildCommand' of the derivation 'desktops' at /nix/store/bhbwzy0p7jhpnxy0ivax9ck9sx3kk1lh-nixos-20.03.3122.ff6fda61600/nixos/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating 'concatMapStrings' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/strings.nix:31:25, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/x11/display-managers/default.nix:124:9:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/x11/display-managers/default.nix:124:27, called from undefined position:
while evaluating the attribute 'text' of the derivation 'Enlightenment-xsession' at /nix/store/bhbwzy0p7jhpnxy0ivax9ck9sx3kk1lh-nixos-20.03.3122.ff6fda61600/nixos/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating the attribute 'text' of the derivation 'xsession' at /nix/store/bhbwzy0p7jhpnxy0ivax9ck9sx3kk1lh-nixos-20.03.3122.ff6fda61600/nixos/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating the attribute 'start' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/x11/desktop-managers/default.nix:73:11:
while evaluating the attribute 'start' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/x11/desktop-managers/enlightenment.nix:55:7:
infinite recursion encountered, at undefined position
```

**To Reproduce**

`services.xserver.desktopManager.enlightenment.enable = true;`

**Expected behavior**
Enlightenment works

**Additional context**
Used to work in a previous 20.03 nixpkgs...

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.56-ck1, NixOS, 20.03.2913.4bd1938e03e (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.3122.ff6fda61600, unstable-21.03pre246543.24c9b05ac53"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: enlightenment
# a list of nixos modules affected by the problem
module: services.xserver.desktopManager
```

**Comment by numinit** [comment] 2020-10-16 07:54
related to #87678 maybe?

**Comment by numinit** [comment] 2020-10-16 07:56
@romildo have you seen this?

**Comment by veprbl** [comment] 2020-10-16 13:13
Duplicate of #100464

**Comment by romildo** [comment] 2020-10-16 14:02
> @romildo have you seen this?

See https://github.com/NixOS/nixpkgs/commit/8fa9a8aa02298d738d552cc36af2e816cf03badb

**Closed** 2020-10-16 14:02 UTC
Labels: 0.kind: bug, 6.topic: nixos
