### ISSUE TITLE
Screen tearing with DRI3 enabled on Intel

### ISSUE THREAD

**Issue by aske** [NixOS/nixpkgs#19231] opened 2016-10-04 18:32 UTC
## Issue description

There's screen tearing on Macbook Air 6,2 after PR (https://github.com/NixOS/nixpkgs/pull/18717) which enables DRI3 by default.

Problem seems to go away after explicitly enabling DRI2 in `services.xserver.deviceSection`:

```
      videoDrivers = [ "intel" ];
      deviceSection = ''
        Option "DRI" "2"
      '';
      useGlamor = true;
```

Is there a widespread improvement with tearing problems after enabling DRI3 by default?
Would it be better to default DRI2 or add a note somewhere instead (or ask upstream guys)?

If anyone feels like it -- please test if you see how things change if you use DRI2 and DRI3 and comment here.
### Steps to reproduce
1. Update to the current nixos-unstable on MBA mid 2013.
2. Open  https://en.wikipedia.org/wiki/October_4 in firefox or qutebrowser and try scrolling.
3. Observe gruesome tearing.
## Technical details
- System: 17.03.git.adfcc2d (Gorilla)
- Nix version: 1.11.4
- Nixpkgs version: 17.03.git.adfcc2d

**Comment by Mic92** [comment] 2016-10-05 18:24
do you also have the problem using modsettings?

```
xserver = {
  videoDrivers = ["modsetting"];
}
```

**Comment by aske** [comment] 2016-10-05 20:46
@Mic92 I've tried different combinations (on/off; dri2/3, etc) of:
```
      videoDrivers = [ "modesetting" ];
      deviceSection = ''
        Option "DRI" "2"
        Option "TearFree" "true"
      '';
      useGlamor = true;
```
and tearing is present with all of them.

**Comment by Mic92** [comment] 2016-10-06 07:51
Thanks. This behavior is consistent, with what I heard of from T440s user.

**Comment by Mic92** [comment] 2016-10-06 07:55
I think there not much we could do hear then reconsidering DRI3. 
This is clearly an upstream issue: https://wiki.archlinux.org/index.php/intel_graphics#DRI3_issues

**Comment by rnhmjoj** [comment] 2016-10-07 11:58
I have never been able get rid of the tearing with DRI3. An option, which is what I'm currently using, is to run compton with the vsync option.

**Comment by Ralith** [comment] 2016-10-22 17:52
Agreed that this is an upstream issue, and should probably be raised there. Odd that you're experiencing it with both intel and modesetting. Is there good reason to believe that DRI2 is more stable in general? DRI3 certainly works fine for some users, is required for some features, is the default in other distros, and is easy enough to turn off, so considering the general shabby state of the intel driver the current state might be the best we can do.

**Comment by erlandsona** [comment] 2016-12-15 01:40
@Mic92's fix worked on my machine! Yay! Thanks @Mic92!

**Comment by primeos** [comment] 2017-02-18 16:47
(triage) Any updates?

It seems like there are already some related upstream issues ([Upstream bug HowTo](https://01.org/linuxgraphics/documentation/how-report-bugs)):
- https://bugs.freedesktop.org/show_bug.cgi?id=97957 (+ [duplicate](https://bugs.freedesktop.org/show_bug.cgi?id=97173))

Would be great if someone could help out over there :smile:

I personally wouldn't switch back to DRI2 but it would probably be worth adding a short comment to the NixOS documentation (like in the [Arch Wiki](https://wiki.archlinux.org/index.php/intel_graphics#DRI3_issues)).

**Comment by taktoa** [comment] 2017-02-18 19:33
If any xmonad users are experiencing these issues, know that compton is not mutually exclusive with xmonad, and that, at least in my case, adding `services.compton.enable = true;` to my `configuration.nix` completely solved this issue.

**Comment by IvanMalison** [comment] 2018-07-15 02:34
> If any xmonad users are experiencing these issues, know that compton is not mutually exclusive with xmonad, and that, at least in my case, adding services.compton.enable = true; to my configuration.nix completely solved this issue.

Weird. I'm running on xmonad, and have compton enabled, and I'm still getting screen tearing. Did you enable compton's vsync?

**Comment by taktoa** [comment] 2018-07-15 08:46
@IvanMalison I'm also having screen tearing lately. Not sure why; I'll try enabling compton vsync though.

**Comment by jvican** [comment] 2018-10-01 15:48
The following worked for me too (thanks to https://wiki.archlinux.org/index.php/intel_graphics#DRI3_issues and @Mic92's suggestion):
```
  videoDrivers = [ "intel" ];                                                                                                                                                                        
  deviceSection = ''                                                                            
    Option "DRI" "2"                                                                            
    Option "TearFree" "true"                                                                    
  '';
```

**Comment by rnhmjoj** [comment] 2020-06-04 07:01
Are you still having tearing issues? I haven't used the intel igpu in a long while.

If tearing is still an issue we could mention enabling tearfree and ~compton~ picom in the NixOS manual, but forcing DRI2 in 2020 doesn't look like a good idea.

**Comment by arximboldi** [comment] 2020-06-13 03:19
@rnhmjoj tearing was driving me mad when using XMonad. Picom did not solve the issue. I just applied all the workarounds suggested here, only enabling `DRI 2` + `TearFree` worked (regardless of Picom being enabled). Interestingly, there seems to be no tearing on Wayland though. Sadly I'm too attached to my XMonad to give up XOrg just yet...

**Comment by arximboldi** [comment] 2020-06-13 03:26
Oh... I was wrong, tearing was also fixed with:
```
  deviceSection = ''                                                                            
    Option "DRI" "3"                                                                            
    Option "TearFree" "true"                                                                    
  '';
```
It does not work if I remove the `DRI` explicit line... weird?

**Comment by arximboldi** [comment] 2020-06-13 03:29
Oops... no. I was wrong, tearing is back, had to revert to DRI 2.

**Comment by rnhmjoj** [comment] 2020-06-14 21:01
Does DRI2 alone (without tearfree) have tearing?

**Comment by arximboldi** [comment] 2020-06-16 09:29
Just removed `TearFree` and tearing seems gone still, only with DRI2.

**Comment by rnhmjoj** [comment] 2020-06-17 07:37
Last thing before updating the manual, can you check this settings?
```
  deviceSection = ''                                                                            
    Option "DRI" "3"
    Option "AccelMethod" "sna"                                                   
  '';
```

**Comment by arximboldi** [comment] 2020-06-17 08:53
No tearing when using `smplayer`, but there is tearing and stutter when using Youtube on Firefox.

**Comment by bb2020** [comment] 2020-06-19 19:59
I also have extreme tearing with iGPU and `none+xmonad` setup. It happens with two different laptops. Tearing does not occur with the old `xf86-video-intel` driver, but it somehow breaks everything multi-monitor related.

**Comment by rnhmjoj** [comment] 2020-06-21 21:58
@arximboldi, I realized you may have been trying to use `AccelMethod` and `TearFree` with modesetting, while this option are specific to xf86-video-intel. Can you check if you have `videoDrivers = [ "intel" ]`?

**Comment by arximboldi** [comment] 2020-06-22 09:15
@rnhmjoj I have not explicitly put in the snippets, but I had `videoDrivers = [ "intel" ]` on all time through my experiments :)

**Comment by arximboldi** [comment] 2020-06-22 09:16
I was just reding your snippet, maybe I should try to use modesetting driver instead which is more modern?

**Comment by bb2020** [comment] 2020-06-22 09:21
`xf86-video-intel` is considered legacy. It is still updated, but it does not have proper versioning. We only have bleeding edge git snapshots.

**Comment by arximboldi** [comment] 2020-06-22 09:25
I actually just tried the modesetting driver and I get tearing with it, so I'll stick to intel + DRI 2 for now :)

**Comment by arximboldi** [comment] 2020-06-22 09:26
Thanks @rnhmjoj for helping me investicate and documenting the results!

**Comment by rnhmjoj** [comment] 2020-06-22 10:03
@arximboldi No problem, thank you for the collaboration.
It's quite sad that modesetting does still have tearing issues but at least we have found a working solution.

**Closed** 2020-06-23 09:30 UTC
Labels: 0.kind: bug, 9.needs: community feedback

**Comment by arximboldi** [comment] 2020-12-18 22:12
@rnhmjoj sadly since 20.09, using the `intel` driver causes OpenGL applications to crash. I am using the `modesetting` driver now as a workaround, but it causes screen tearing when watching videos in full screen :(

**Comment by bb2020** [comment] 2020-12-18 22:41
It looks like screen tearing is not solvable with `modesetting` driver. Tearing intensifies when X11 `transform` operations are applied (`--scale`, `--scale-from` etc).

**Comment by arximboldi** [comment] 2020-12-18 23:29
That is sad. I was hoping this would be solvable in `modesetting`, overall it seems to perform better than `intel`, I've tried various options like `PageFlip`. However tearing just makes watching movies too annoying, so I'd like to go back to `intel`.

Are other people experiencing issues with `intel` on 20.09? Any clue on how to solve them?

**Comment by rnhmjoj** [comment] 2020-12-19 09:45
> sadly since 20.09, using the intel driver causes OpenGL applications to crash

Uhm, the `xf86-video-intel` package hasn't been updated since 20.03. The problem has probably been introduced by mesa xorg-server. Since I don't see any report of crashes in their issue tracker, it could very well be Nixpkgs has an outdated revision: you could try to override the package to use a more recent commit and see it that solves the crashes.

I can give you directions, if yu want to try.

**Comment by primeos** [comment] 2020-12-19 10:38
Regarding TearFree for the newer `modesetting` driver:
- Upstream issue: https://gitlab.freedesktop.org/xorg/xserver/-/issues/244
- Upstream MR: https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/24
  - Rebased patches for xorg-server-1.20.9: https://gitlab.freedesktop.org/vliaskov/xserver/-/commit/18be004ad18b8a33e5854c08ab2ea023f34890b6

So there is some progress being made but I doubt the patches will be merged anytime soon. Though overriding xorg-server to apply the patches could be a viable solution for the meantime.

@rnhmjoj's idea also sounds good. The last xf86-video-intel release is currently 5 years old ([list](https://gitlab.freedesktop.org/xorg/driver/xf86-video-intel/-/tags)) but apparently there is still quite some activity in the [master](https://gitlab.freedesktop.org/xorg/driver/xf86-video-intel/-/commits/master) branch.

Other solutions could be using a compositor for X11 or switching to Wayland(+XWayland).

**Comment by arximboldi** [comment] 2020-12-19 14:33
Thanks @primeos and @rnhmjoj!

@rnhmjoj I am trying overriding the `xf86videointel` package:
```nix
  nixpkgs.config.packageOverrides = pkgs: {
    xorg.xf86videointel = pkgs.xorg.xf86videointel.override {
      src = fetchGit {
        url = "https://gitlab.freedesktop.org/xorg/driver/xf86-video-intel.git";
        rev = "a511f22cdec56504913b457a2e60dafee8e2b570";
      };
    };
  };
```
But it is failing with:
```
error: attribute 'overrideScope'' missing, at /nix/store/csgakpb8wgymlj3a4374347hkg23qa01-nixos-20.09.2161.214e71a78a9/nixos/pkgs/top-level/static.nix:286:10
(use '--show-trace' to show detailed location information)
building Nix...
error: attribute 'overrideScope'' missing, at /nix/store/csgakpb8wgymlj3a4374347hkg23qa01-nixos-20.09.2161.214e71a78a9/nixos/pkgs/top-level/static.nix:286:10
(use '--show-trace' to show detailed location information)
building the system configuration...
error: anonymous function at /nix/store/csgakpb8wgymlj3a4374347hkg23qa01-nixos-20.09.2161.214e71a78a9/nixos/pkgs/os-specific/linux/amdgpu-pro/default.nix:1:1 called without required argument 'libxcb', at /nix/store/csgakpb8wgymlj3a4374347hkg23qa01-nixos-20.09.2161.214e71a78a9/nixos/lib/customisation.nix:69:16
(use '--show-trace' to show detailed location information)
```

**Comment by rnhmjoj** [comment] 2020-12-19 15:14
@arximboldi `override` is for arguments of the package (ie options and dependencies), to change an attribute like `src` you have to use `overrideAttrs`, works similarly.

**Comment by arximboldi** [comment] 2020-12-19 18:53
Sadly still not working @rnhmjoj, I get this error:
```
error: attribute 'overrideScope'' missing, at /nix/store/csgakpb8wgymlj3a4374347hkg23qa01-nixos-20.09.2161.214e71a78a9/nixos/pkgs/top-level/static.nix:286:10
(use '--show-trace' to show detailed location information)
building Nix...
error: attribute 'overrideScope'' missing, at /nix/store/csgakpb8wgymlj3a4374347hkg23qa01-nixos-20.09.2161.214e71a78a9/nixos/pkgs/top-level/static.nix:286:10
(use '--show-trace' to show detailed location information)
building the system configuration...
error: anonymous function at /nix/store/csgakpb8wgymlj3a4374347hkg23qa01-nixos-20.09.2161.214e71a78a9/nixos/pkgs/os-specific/linux/amdgpu-pro/default.nix:1:1 called without required argument 'libxcb', at /nix/store/csgakpb8wgymlj3a4374347hkg23qa01-nixos-20.09.2161.214e71a78a9/nixos/lib/customisation.nix:69:16
(use '--show-trace' to show detailed location information)
```

**Comment by rnhmjoj** [comment] 2020-12-21 07:46
Oh, right: it's because the override is replacing the whole `xorg` set with `{ xf86videointel = ...; }`.
Try this:
```nix
{
  nixpkgs.overlays = lib.singleton (self: super:
  { xorg = super.xorg // {
      xf86videointel = super.xorg.xf86videointel.overrideAttrs (old: {
        src = fetchGit {
          url = "https://gitlab.freedesktop.org/xorg/driver/xf86-video-intel.git";
          rev = "a511f22cdec56504913b457a2e60dafee8e2b570";
        };
      });
    };
  });

}
```

**Comment by arximboldi** [comment] 2020-12-21 20:13
Thank you so much for your help @rnhmjoj! :heart: 

That has worked. I can now use the Intel driver again without OpenGL crashes nor tearing issues.

Looking forward to trying the modesetting driver again in the next release, hopefully the `TearFree` patch is in by then!

**Comment by rmanne** [comment] 2021-03-14 19:42
While just enabling picom (even with `vSync=true`) didn't work on its own for me, for some reason, some combination of these settings DID stop screen tearing for me:
```
  services.picom = {
    enable = true;
    vSync = true;
    backend = "xr_glx_hybrid";
    settings = {
      glx-no-stencil = true;
      glx-no-rebind-pixmap = true;
      unredir-if-possible = true;
      xrender-sync-fence = true;
    };
  };
```

I think the key here was `backend = "xr_glx_hybrid"`. No other backend got rid of the screen tearing for me. I'm not sure if the extra options under settings matter. I don't know why this made the difference.

**Comment by bb2020** [comment] 2021-03-14 19:53
For ones using Xrandr `transform` operations like `--rotate` or `--scale-from`, I doubt utilization of a compositor will solve the tearing issue completely. I've seen a branch of `modesetting` driver that includes `TearFree` work that has been going on X11 repo. This is the commit URL: https://gitlab.freedesktop.org/vliaskov/xserver/-/commit/18be004ad18b8a33e5854c08ab2ea023f34890b6.

I don't have time to test it, yet alone break my `xserver`, meanwhile an override to X11 package with this branch may solve the issue.

**Comment by fuzzypixelz** [comment] 2021-03-24 22:54
@rmanne
Thank you! I can confirm this is working on Intel HD Graphics 520 with xmonad™ and modesetting/DRI3.
