### ISSUE TITLE
nsncd service fails to start on unstable

### ISSUE THREAD

**Issue by tschan** [NixOS/nixpkgs#344901] opened 2024-09-27 14:45 UTC
### Describe the bug
nsncd service fails to start on boot on unstable which results in a boot failure for me. This behavior started for me after upgrading from 9357f4f23713673f310988025d9dc261c20e70c6 to 30439d93eb8b19861ccbe3e581abf97bdc91b093.

### Steps To Reproduce
1. Upgrade to 30439d93eb8b19861ccbe3e581abf97bdc91b093
2. Profit!

### Expected behavior
nsncd service should correctly start.

### Additional context
Output of `journalctl -u nscd -b -1`:
```
Sep 27 07:57:38 desktop-nixos systemd[1]: Starting Name Service Cache Daemon (nsncd)...
Sep 27 07:57:39 desktop-nixos nsncd[2794]: Sep 27 05:57:38.922 INFO started, config: Config { ignored_request_types: {}, worker_count: 8, handoff_timeout: 3s }, path: "/var/run/nscd/socket"
Sep 27 07:57:39 desktop-nixos nsncd[2794]: Error: Read-only file system (os error 30)
Sep 27 07:57:38 desktop-nixos systemd[1]: nscd.service: Main process exited, code=exited, status=1/FAILURE
Sep 27 07:57:38 desktop-nixos systemd[1]: nscd.service: Failed with result 'exit-code'.
Sep 27 07:57:38 desktop-nixos systemd[1]: Failed to start Name Service Cache Daemon (nsncd).
Sep 27 07:57:39 desktop-nixos systemd[1]: Stopped Name Service Cache Daemon (nsncd).
Sep 27 07:57:39 desktop-nixos systemd[1]: Starting Name Service Cache Daemon (nsncd)...
Sep 27 07:57:39 desktop-nixos nsncd[3194]: Sep 27 05:57:39.031 INFO started, config: Config { ignored_request_types: {}, worker_count: 8, handoff_timeout: 3s }, path: "/var/run/nscd/socket"
Sep 27 07:57:39 desktop-nixos nsncd[3194]: Error: Read-only file system (os error 30)
Sep 27 07:57:39 desktop-nixos systemd[1]: nscd.service: Main process exited, code=exited, status=1/FAILURE
Sep 27 07:57:39 desktop-nixos systemd[1]: nscd.service: Failed with result 'exit-code'.
Sep 27 07:57:39 desktop-nixos systemd[1]: Failed to start Name Service Cache Daemon (nsncd).
Sep 27 07:57:39 desktop-nixos systemd[1]: nscd.service: Scheduled restart job, restart counter is at 1.
Sep 27 07:57:39 desktop-nixos systemd[1]: Starting Name Service Cache Daemon (nsncd)...
Sep 27 07:57:39 desktop-nixos nsncd[3329]: Sep 27 05:57:39.209 INFO started, config: Config { ignored_request_types: {}, worker_count: 8, handoff_timeout: 3s }, path: "/var/run/nscd/socket"
Sep 27 07:57:39 desktop-nixos nsncd[3329]: Error: Read-only file system (os error 30)
Sep 27 07:57:39 desktop-nixos systemd[1]: nscd.service: Main process exited, code=exited, status=1/FAILURE
Sep 27 07:57:39 desktop-nixos systemd[1]: nscd.service: Failed with result 'exit-code'.
Sep 27 07:57:39 desktop-nixos systemd[1]: Failed to start Name Service Cache Daemon (nsncd).
Sep 27 07:57:39 desktop-nixos systemd[1]: nscd.service: Scheduled restart job, restart counter is at 2.
Sep 27 07:57:39 desktop-nixos systemd[1]: nscd.service: Start request repeated too quickly.
Sep 27 07:57:39 desktop-nixos systemd[1]: nscd.service: Failed with result 'exit-code'.
Sep 27 07:57:39 desktop-nixos systemd[1]: Failed to start Name Service Cache Daemon (nsncd).
```

### Notify maintainers
@flokli @picnoir

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.0, NixOS, 24.11 (Vicuna), 24.11.20240921.9357f4f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.7`
 - nixpkgs: `/etc/nix/path/nixpkgs
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by picnoir** [comment] 2024-09-27 15:37
I'm running the exact same Nixpkgs pin on my systems without any issue, I can't reproduce this.

This log output  is… …pretty terse. I'm not 100% sure on what it's failing on. There's sadly no trivial way to raise the min log level without patching the cargo.toml file and recompiling the project. See https://docs.rs/slog/latest/slog/#notable-details

Alternatively, you could try to strace the process to figure out what it's trying to do before throwing this error.

Did you try to set

```nix
services.nscd.enableNsncd = false;
```

in your NixOS config to see if the boot can go further?

**Comment by tschan** [comment] 2024-09-27 17:02
> This log output is… …pretty terse. I'm not 100% sure on what it's failing on. There's sadly no trivial way to raise the min log level and get the debug logs without patching the cargo.toml file and recompiling the project. See https://docs.rs/slog/latest/slog/#notable-details

This did not change the log output at all unfortunately.

> Did you try to set
> 
> ```nix
> services.nscd.enableNsncd = false;
> ```

This also did not work on boot and produced the following log output:
```
Sep 27 18:50:58 desktop-nixos systemd[1]: Starting Name Service Cache Daemon...
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 /var/run/nscd/nscd.pid: No such file or directory
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring file `/etc/passwd` (1)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring file `/etc/group` (3)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring file `/etc/hosts` (4)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring file `/etc/resolv.conf` (5)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring file `/etc/services` (6)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring file `/etc/netgroup` (7)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 cannot create /var/db/nscd/passwd; no sharing possible
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 cannot create /var/db/nscd/group; no sharing possible
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 cannot create /var/db/nscd/hosts; no sharing possible
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 cannot create /var/db/nscd/services; no sharing possible
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 cannot create /var/db/nscd/netgroup; no sharing possible
Sep 27 18:50:58 desktop-nixos nscd[3279]: 3279 /var/run/nscd/socket: No such file or directory
Sep 27 18:50:58 desktop-nixos nscd[3259]: child exited with status 1
Sep 27 18:50:58 desktop-nixos systemd[1]: nscd.service: Control process exited, code=exited, status=1/FAILURE
Sep 27 18:50:58 desktop-nixos systemd[1]: nscd.service: Failed with result 'exit-code'.
Sep 27 18:50:58 desktop-nixos systemd[1]: Failed to start Name Service Cache Daemon.
Sep 27 18:50:58 desktop-nixos systemd[1]: nscd.service: Scheduled restart job, restart counter is at 1.
Sep 27 18:50:58 desktop-nixos systemd[1]: Starting Name Service Cache Daemon...
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 /var/run/nscd/nscd.pid: No such file or directory
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring file `/etc/passwd` (1)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring file `/etc/group` (3)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring file `/etc/hosts` (4)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring file `/etc/resolv.conf` (5)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring file `/etc/services` (6)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring file `/etc/netgroup` (7)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 monitoring directory `/etc` (2)
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 cannot create /var/db/nscd/passwd; no sharing possible
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 cannot create /var/db/nscd/group; no sharing possible
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 cannot create /var/db/nscd/hosts; no sharing possible
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 cannot create /var/db/nscd/services; no sharing possible
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 cannot create /var/db/nscd/netgroup; no sharing possible
Sep 27 18:50:58 desktop-nixos nscd[3394]: 3394 /var/run/nscd/socket: No such file or directory
Sep 27 18:50:58 desktop-nixos nscd[3366]: child exited with status 1
Sep 27 18:50:58 desktop-nixos systemd[1]: nscd.service: Control process exited, code=exited, status=1/FAILURE
Sep 27 18:50:58 desktop-nixos systemd[1]: nscd.service: Failed with result 'exit-code'.
Sep 27 18:50:58 desktop-nixos systemd[1]: Failed to start Name Service Cache Daemon.
Sep 27 18:50:58 desktop-nixos systemd[1]: nscd.service: Scheduled restart job, restart counter is at 2.
Sep 27 18:50:59 desktop-nixos systemd[1]: Starting Name Service Cache Daemon...
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 /var/run/nscd/nscd.pid: No such file or directory
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring file `/etc/passwd` (1)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring directory `/etc` (2)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring file `/etc/group` (3)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring directory `/etc` (2)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring file `/etc/hosts` (4)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring directory `/etc` (2)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring file `/etc/resolv.conf` (5)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring directory `/etc` (2)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring file `/etc/services` (6)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring directory `/etc` (2)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring file `/etc/netgroup` (7)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring directory `/etc` (2)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring directory `/etc` (2)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring directory `/etc` (2)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring directory `/etc` (2)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring directory `/etc` (2)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 monitoring directory `/etc` (2)
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 cannot create /var/db/nscd/passwd; no sharing possible
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 cannot create /var/db/nscd/group; no sharing possible
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 cannot create /var/db/nscd/hosts; no sharing possible
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 cannot create /var/db/nscd/services; no sharing possible
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 cannot create /var/db/nscd/netgroup; no sharing possible
Sep 27 18:50:59 desktop-nixos nscd[3576]: 3576 /var/run/nscd/socket: No such file or directory
Sep 27 18:50:59 desktop-nixos nscd[3573]: child exited with status 1
Sep 27 18:50:59 desktop-nixos systemd[1]: nscd.service: Control process exited, code=exited, status=1/FAILURE
Sep 27 18:50:59 desktop-nixos systemd[1]: nscd.service: Failed with result 'exit-code'.
Sep 27 18:50:59 desktop-nixos systemd[1]: Failed to start Name Service Cache Daemon.
Sep 27 18:50:59 desktop-nixos systemd[1]: nscd.service: Start request repeated too quickly.
Sep 27 18:50:59 desktop-nixos systemd[1]: nscd.service: Failed with result 'exit-code'.
Sep 27 18:50:59 desktop-nixos systemd[1]: Failed to start Name Service Cache Daemon.
```

I also tried the same option with the old working revision. That booted successfully and produced this output:
```
Sep 27 18:57:28 desktop-nixos systemd[1]: Starting Name Service Cache Daemon...
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 monitoring file `/etc/passwd` (1)
Sep 27 18:57:28 desktop-nixos systemd[1]: Started Name Service Cache Daemon.
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 monitoring directory `/etc` (2)
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 monitoring file `/etc/group` (3)
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 monitoring directory `/etc` (2)
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 monitoring file `/etc/hosts` (4)
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 monitoring directory `/etc` (2)
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 disabled inotify-based monitoring for file `/etc/resolv.conf': No such file or directory
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 stat failed for file `/etc/resolv.conf'; will try again later: No such file or directory
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 monitoring file `/etc/services` (5)
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 monitoring directory `/etc` (2)
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 monitoring file `/etc/netgroup` (6)
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 monitoring directory `/etc` (2)
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 monitoring file `/etc/nsswitch.conf` (7)
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 monitoring directory `/etc` (2)
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 monitoring file `/etc/nsswitch.conf` (7)
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 monitoring directory `/etc` (2)
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 monitoring file `/etc/nsswitch.conf` (7)
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 monitoring directory `/etc` (2)
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 monitoring file `/etc/nsswitch.conf` (7)
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 monitoring directory `/etc` (2)
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 monitoring file `/etc/nsswitch.conf` (7)
Sep 27 18:57:28 desktop-nixos nscd[3191]: 3191 monitoring directory `/etc` (2)
Sep 27 18:57:28 desktop-nixos systemd[1]: Stopping Name Service Cache Daemon...
Sep 27 18:57:28 desktop-nixos systemd[1]: nscd.service: Deactivated successfully.
Sep 27 18:57:28 desktop-nixos systemd[1]: Stopped Name Service Cache Daemon.
Sep 27 18:57:28 desktop-nixos systemd[1]: Starting Name Service Cache Daemon...
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring file `/etc/passwd` (1)
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring directory `/etc` (2)
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring file `/etc/group` (3)
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring directory `/etc` (2)
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring file `/etc/hosts` (4)
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring directory `/etc` (2)
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring file `/etc/resolv.conf` (5)
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring directory `/etc` (2)
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring file `/etc/services` (6)
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring directory `/etc` (2)
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring file `/etc/netgroup` (7)
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring directory `/etc` (2)
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring directory `/etc` (2)
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring directory `/etc` (2)
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring directory `/etc` (2)
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring directory `/etc` (2)
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:57:28 desktop-nixos nscd[3289]: 3289 monitoring directory `/etc` (2)
Sep 27 18:57:28 desktop-nixos systemd[1]: Started Name Service Cache Daemon.
Sep 27 18:57:32 desktop-nixos nscd[3289]: 3289 monitored file `/etc/resolv.conf` was written to
Sep 27 18:57:32 desktop-nixos systemd[1]: Stopping Name Service Cache Daemon...
Sep 27 18:57:32 desktop-nixos systemd[1]: nscd.service: Deactivated successfully.
Sep 27 18:57:32 desktop-nixos systemd[1]: Stopped Name Service Cache Daemon.
Sep 27 18:57:32 desktop-nixos systemd[1]: Starting Name Service Cache Daemon...
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring file `/etc/passwd` (1)
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring directory `/etc` (2)
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring file `/etc/group` (3)
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring directory `/etc` (2)
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring file `/etc/hosts` (4)
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring directory `/etc` (2)
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring file `/etc/resolv.conf` (5)
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring directory `/etc` (2)
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring file `/etc/services` (6)
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring directory `/etc` (2)
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring file `/etc/netgroup` (7)
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring directory `/etc` (2)
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring directory `/etc` (2)
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring directory `/etc` (2)
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring directory `/etc` (2)
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring directory `/etc` (2)
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:57:32 desktop-nixos nscd[4345]: 4345 monitoring directory `/etc` (2)
Sep 27 18:57:32 desktop-nixos systemd[1]: Started Name Service Cache Daemon.
Sep 27 18:57:33 desktop-nixos nscd[4345]: 4345 monitored file `/etc/resolv.conf` was written to
Sep 27 18:57:33 desktop-nixos systemd[1]: Stopping Name Service Cache Daemon...
Sep 27 18:57:33 desktop-nixos systemd[1]: nscd.service: Deactivated successfully.
Sep 27 18:57:33 desktop-nixos systemd[1]: Stopped Name Service Cache Daemon.
Sep 27 18:57:33 desktop-nixos systemd[1]: Starting Name Service Cache Daemon...
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring file `/etc/passwd` (1)
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring directory `/etc` (2)
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring file `/etc/group` (3)
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring directory `/etc` (2)
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring file `/etc/hosts` (4)
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring directory `/etc` (2)
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring file `/etc/resolv.conf` (5)
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring directory `/etc` (2)
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring file `/etc/services` (6)
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring directory `/etc` (2)
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring file `/etc/netgroup` (7)
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring directory `/etc` (2)
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring directory `/etc` (2)
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring directory `/etc` (2)
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring directory `/etc` (2)
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring directory `/etc` (2)
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring file `/etc/nsswitch.conf` (8)
Sep 27 18:57:33 desktop-nixos nscd[4637]: 4637 monitoring directory `/etc` (2)
Sep 27 18:57:33 desktop-nixos systemd[1]: Started Name Service Cache Daemon.
```

So it seems pretty obvious that nsncd is not the culprit here. Although I'm a bit stumped on what to do next.

**Comment by picnoir** [comment] 2024-09-27 17:07
Yeah, it's pretty confusing, it seems like you're missing either `/run` or `/etc. I'd try to run `ls -l /; ls -l /etc; ls -l /` in nscd's `preStart` script to make sure the filesystems are here.

**Comment by tschan** [comment] 2024-09-27 17:45
Looks like the cause is nothing in nixpkgs but a change in Impermanence. Reverting the following update makes the system bootable again:

```
• Updated input 'impermanence':
    'github:nix-community/impermanence/63f4d0443e32b0dd7189001ee1894066765d18a5' (2024-09-07)
  → 'github:nix-community/impermanence/8514fff0f048557723021ffeb31ca55f69b67de3' (2024-09-24)
```

I guess I'll check the Impermanence repo and raise an issue there.

**Comment by picnoir** [comment] 2024-09-27 17:51
Closing the issue in the meantime.

**Closed by picnoir** 2024-09-27 17:51 UTC
Labels: 0.kind: bug

**Comment by Luminger** [comment] 2024-11-20 10:52
For me the observed behavior was caused by an accidental creation of `/var/run` symlink before the boot process had a chance to create the symlink in the first place.

I'm not sure where this symlink is created during boot, but it would be great if a failing `ln` would result in a warning at boot. It's rather subtle that `/var/run` is a directory when it actually should be a symlink.

@picnoir Do you happen to know where the symlink is created? I'm happy to send a PR for the proposed warning :)

**Comment by picnoir** [comment] 2024-11-20 11:35
TBH, I don't know. Had a quick grep around without success.

**Comment by picnoir** [comment] 2024-11-20 12:16
Ok, nerdsniped :D

The symlinked is created by the `/etc/tmpfiles.d/var.conf` systemd tmpfile:

```
~ » cat /etc/tmpfiles.d/var.conf
(...)
L /var/run - - - - ../run
(...)
```

And we pull this file directly from systemd there:

https://github.com/NixOS/nixpkgs/blob/7bd7450b8240d5dd07892dbb841639e15ca27b6e/nixos/modules/system/boot/systemd/tmpfiles.nix#L265
