### ISSUE TITLE
haskellPackages.mattermost-api fails to build

### ISSUE THREAD

**Issue by alexvorobiev** [NixOS/nixpkgs#42392] opened 2018-06-22 20:16 UTC
## Issue description
haskellPackages.mattermost-api fails to build trying to build/run tests:
```
Preprocessing test suite 'test-mm-api' for mattermost-api-40900.1.0..
Building test suite 'test-mm-api' for mattermost-api-40900.1.0..
[1 of 3] Compiling Tests.Types      ( test/Tests/Types.hs, dist/build/test-mm-api/test-mm-api-tmp/Tests/Types.o )
[2 of 3] Compiling Tests.Util       ( test/Tests/Util.hs, dist/build/test-mm-api/test-mm-api-tmp/Tests/Util.o )

test/Tests/Util.hs:268:12: error:
    \u2022 Couldn't match type \u2018T.Text\u2019 with \u2018UserText\u2019
      Expected type: Maybe UserText
        Actual type: Maybe T.Text
    \u2022 In the second argument of \u2018wsHas\u2019, namely \u2018(Just msg)\u2019
      In the second argument of \u2018(&&&)\u2019, namely
        \u2018wsHas (\ e -> postMessage <$> (wepPost $ weData e)) (Just msg)\u2019
      In the first argument of \u2018(&&&)\u2019, namely
        \u2018hasWSEventType WMPosted
           &&& wsHas (\ e -> postMessage <$> (wepPost $ weData e)) (Just msg)\u2019
    |
268 |           (Just msg) &&&
    |            ^^^^^^^^

test/Tests/Util.hs:320:39: error:
    \u2022 Couldn't match expected type \u2018T.Text\u2019 with actual type \u2018UserText\u2019
    \u2022 In the expression: channelName c
      In the second argument of \u2018elem\u2019, namely
        \u2018[channelName c, channelDisplayName c]\u2019
      In the expression:
        name `elem` [channelName c, channelDisplayName c]
    |
320 |         nameMatches c = name `elem` [ channelName c
    |                                       ^^^^^^^^^^^^^

test/Tests/Util.hs:321:39: error:
    \u2022 Couldn't match expected type \u2018T.Text\u2019 with actual type \u2018UserText\u2019
    \u2022 In the expression: channelDisplayName c
      In the second argument of \u2018elem\u2019, namely
        \u2018[channelName c, channelDisplayName c]\u2019
      In the expression:
        name `elem` [channelName c, channelDisplayName c]
    |
321 |                                     , channelDisplayName c
    |                                       ^^^^^^^^^^^^^^^^^^^^
builder for '/nix/store/f9xwny38l90sd58lsjw6x6h10zarqk7v-mattermost-api-40900.1.0.drv' failed with exit code 1
error: build of '/nix/store/f9xwny38l90sd58lsjw6x6h10zarqk7v-mattermost-api-40900.1.0.drv' failed
```

### Steps to reproduce
```
nix-env -iA nixpkgs.haskellPackages.mattermost-api
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 3.10.0-514.26.2.el7.x86_64, Red Hat Enterprise Linux Server, 7.3 (Maipo)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixpkgs-18.09pre142966.91ca88b3e6b"`

I also tried with the latest master.

**Comment by wizzup** [comment] 2019-10-12 03:53
The issue is now resolved, please close this.

To verify

```
$ nix-build '<nixpkgs>' -A haskellPackages.mattermost-api -I nixpkgs=https://github.com/NixOS/nixpkgs/tarball/master
/nix/store/ara9ks42p1krb9c9dhgpd60270m3byh1-mattermost-api-50200.2.0
```

**Closed** 2019-10-12 04:44 UTC
Labels: 6.topic: haskell
