### ISSUE TITLE
Build failure: mission-center

### ISSUE THREAD

**Issue by Micheal129** [NixOS/nixpkgs#358757] opened 2024-11-24 16:27 UTC
## Steps To Reproduce

1. build mission center

## Build log

`nix-shell -p mission-center
this derivation will be built:
  /nix/store/jhr74v8dyzm38la54p98p521ap30ifhq-mission-center-0.6.2.drv
building '/nix/store/jhr74v8dyzm38la54p98p521ap30ifhq-mission-center-0.6.2.drv'...
Using versionCheckHook
Running phase: unpackPhase
unpacking source archive /nix/store/pdzy121sbx8zgpqjfbgjd12sx02yxb08-source
source root is source
Executing cargoSetupPostUnpackHook
Finished cargoSetupPostUnpackHook
Running phase: patchPhase
substituteInPlace called without any files to operate on (files must come before options!)
error: builder for '/nix/store/jhr74v8dyzm38la54p98p521ap30ifhq-mission-center-0.6.2.drv' failed with exit code 1;
       last 8 log lines:
       > Using versionCheckHook
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/pdzy121sbx8zgpqjfbgjd12sx02yxb08-source
       > source root is source
       > Executing cargoSetupPostUnpackHook
       > Finished cargoSetupPostUnpackHook
       > Running phase: patchPhase
       > substituteInPlace called without any files to operate on (files must come before options!)`

<details>

<summary>Build Log</summary>

```
error: builder for '/nix/store/jhr74v8dyzm38la54p98p521ap30ifhq-mission-center-0.6.2.drv' failed with exit code 1;
       last 8 log lines:
       > Using versionCheckHook
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/pdzy121sbx8zgpqjfbgjd12sx02yxb08-source
       > source root is source
       > Executing cargoSetupPostUnpackHook
       > Finished cargoSetupPostUnpackHook
       > Running phase: patchPhase
       > substituteInPlace called without any files to operate on (files must come before options!)
```

</details>

## Additional context

I am on unstable branch

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.0, NixOS, 25.05 (Warbler), 25.05beta710087.23e89b7da85c`

## Notify maintainers

  @GaetanLepage
  @getchoo

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by GaetanLepage** [comment] 2024-11-24 23:25
This is fixed on `master`. The issue is that the `nixos-unstable` channel is lagging a bit further than usual.
Let's just wait for the fix to land there.

https://nixpkgs-tracker.ocfox.me/?pr=357219

**Closed** 2024-12-02 18:39 UTC
Labels: 0.kind: build failure
