### ISSUE TITLE
NixOS: default to Gnome

### ISSUE THREAD

**Issue by tycho01** [NixOS/nixpkgs#41797] opened 2018-06-10 13:45 UTC
Looking at an old [Tweet](https://twitter.com/chris__martin/status/797213525097713665), it seems there was some consensus that it would be nice to have the NixOS iso default to using Gnome, yet for legacy reasons still used KDE.

Now, in 18.03, I came in as a new user to find this is still the case.

I'm not sure if new users are expected to somehow install in a different manner, but to make the experience more appealing, I hope it would be possible to default to Gnome instead.

**Comment by davidak** [comment] 2018-06-10 14:34
I use GNOME on NixOS now for some weeks and it seams pretty stable and usable. I had issues with Xfce after updating to 18.03 (that i reported, but not fixed as of now).

Since Ubuntu uses GNOME by default now, it might be a good time for us to do the same.

It's important to **use GDM** as of now, since locking the screen don't work with lightdm (also [known](https://github.com/NixOS/nixpkgs/issues/38492#issuecomment-393778977)).

We might want to default to a very lightweight desktop, so it works also on older machines, but it should be stable and usable. Xfce is not. MATE is not modern and i don't think it represents NixOS good.

**Comment by FRidh** [comment] 2018-06-10 18:28
> Looking at an old Tweet, it seems there was some consensus that it would be nice to have the NixOS iso default to using Gnome, yet for legacy reasons still used KDE.

I don't see any such consensus on the tweet you're referring to. Are you sure it's the right one? In any case, I suggest discussing such changes on the mailing list instead.

**Comment by Anton-Latukha** [comment] 2018-06-10 23:19
1. KDE is feature superior platform to GNOME applications. GNOME apps are mostly too simplified.
2. KDE is aimed at power users.
3. KDE is more lightweight. Recently tested on 15-17-year old PC. GNOME could not even normally run on NVidia NV20 card from 2001. In KDE my aunt on that card watches movies in 720p. 
4. QT5 is superior framework. Can you share GTK apps doing this: https://www.youtube.com/watch?v=nTp2P4pDt-A. Is GTK used in automotive industry, or can it run on microcontroller: https://www.youtube.com/watch?v=1ySTyBz2F0k.
5. C++ way better fits to develop Desktop Environment and GUI applications. That is why smalled KDE community keeps up with GTK large numbers.
6. KWin is just superior to Mutter. GNOME graphics is heavily single threaded.
7. GNOME even by design drops frames on network statechanges, desktop notifications, and more https://www.phoronix.com/scan.php?page=news_item&px=GNOME-3-Hungry-For-Pi

**Comment by Anton-Latukha** [comment] 2018-06-10 23:34
10. GNOME in no way superior, it wins because most people and companies uses GTK, GNOME. And still today unpaid KDE contributors outpaces GNOME development. https://pointieststick.wordpress.com/

I am for NixOS supporting KDE.
Everyone is GTK/GNOME.
NixOS is distinctive. It is line with few other distinctive distros that use KDE as a main DE (KDE Neon, BSD systems, Kubuntu).

NixOS has a great chance attracting KDE developers and collaborating with KDE Neon team.

**Comment by aexoxea** [comment] 2018-06-11 09:06
I'm a very new NixOS user who has yet to contribute here, so please weight the below accordingly.

Coming from an Arch background, it was nice to have access to a graphical environment (and particularly a graphical browser and partitioner) to do the installation. Being a KDE user, it was also nice to see my favourite DE.

However, I could have done just as well with any DE, since:

- The decision to install NixOS went beyond what DE was used on the install ISO.
- There's only a few applications involved, and the graphical environment is only in use for a comparitively short time (because it's only being used for the installation).
- I have a choice of what DE to install on the target system (and indeed, no DE is installed 'by default' based on what is in the generated `configuration.nix`).
- Some of KDE's tools refuse to run as root anyway (e.g. Dolphin).

I agree that the DE should be both aesthetic and well-functioning. That said, as Plasma 5 is already integrated (and pretty up-to-date) on the current install ISO, wouldn't it be easier to start with improving that with theming/configuration if there are specific concerns?

Also, if there are challenges with integrating updated components to the install ISO, that might be a reason to stick with Plasma 5, since it now offers LTS releases. I couldn't tell after a cursory search whether GNOME has similar; does it?

**Comment by Anton-Latukha** [comment] 2018-06-11 09:06
Major part of NixOS community is monolithic - Haskell developers.
If raise that question. To satisfy users we should switch to xmonad.

**Comment by davidak** [comment] 2018-06-11 09:27
@Anton-Latukha like @aexoxea correctly said, no DE get installed by default. So you have to choose which one you want. The DE of the installer live CD is just for testing and installation. So we should use a DE that many linux users are familiar with (like GNOME, Xfce or KDE, no window manager :D).

**Comment by globin** [comment] 2018-06-11 14:56
Since choosing a DE explicitly is necessary when installing I don't see anything we can do here except for changing the default in the graphical ISO. I would argue doing that would only make sense if we have larger problems with KDE and we don't have that, but rather a history of GNOME being broken in a few cases. Wrt to the above I'm closing this; if I have missed anything or there are specific thing you see that we should change or do feel free to reopen or create new issues!

**Closed by globin** 2018-06-11 14:56 UTC

**Comment by Mouvedia** [comment] 2018-06-20 14:28
Could someone pick up #12150?
