### ISSUE TITLE
Stack usage

### ISSUE THREAD

**Issue by Pitometsu** [NixOS/nixpkgs#10295] opened 2015-10-09 19:08 UTC
What is the proper way to use the `stack` on **NixOS**?
I eventually [got](https://github.com/commercialhaskell/stack/issues/1118) some errors with `libgmp.so.10` after one of regular system upgrade.

**Comment by peti** [comment] 2015-10-09 19:27
Please post a complete log that shows the error messages you're getting. Also, make sure to read http://nixos.org/nixpkgs/manual/#using-stack-together-with-nix.

**Comment by Pitometsu** [comment] 2015-10-09 23:43
With `stack --extra-lib-dirs=/nix/store/2w6z5pijhqj6v40mwc31wqclji666n8g-gmp-5.1.3/lib build` all right. But cat I do it without this hardcode?
*UPD:* fixed by
```shell
$ cd ; nix-channel --update ; ln -s /nix/var/nix/profiles/per-user/netsu .nix-profile
```
May I broke it by deleting .nix* in `~`?

**Comment by peti** [comment] 2015-10-10 17:11
I suppose that the problem is now fixed. If there is still something that doesn't work, then please submit a complete log that shows the command you're running plus the whole output that command produces.

**Closed by peti** 2015-10-10 17:11 UTC
Labels: haskell, question
