### ISSUE TITLE
Package request: XAMPP

### ISSUE THREAD

**Issue by ardishco-the-great** [NixOS/nixpkgs#285123] opened 2024-01-30 23:50 UTC
**Project description**

XAMPP is a very easy to install Apache Distribution for Linux, Solaris, Windows, and Mac OS X. The package includes the Apache web server, MySQL, PHP, Perl, a FTP server and phpMyAdmin.

**Metadata**

* homepage URL: https://www.apachefriends.org/
* source URL: https://sourceforge.net/projects/xampp/files/
* license: gpl2+
* platforms: linux

**Comment by jopejoe1** [comment] 2024-01-31 00:07
Duplicate of  #189105

**Closed by jopejoe1** 2024-01-31 00:07 UTC
Labels: 0.kind: packaging request
