### ISSUE TITLE
Collision in python packages due to test caches

### ISSUE THREAD

**Issue by azazel75** [NixOS/nixpkgs#44479] opened 2018-08-05 00:28 UTC
## Issue description
Installing a derivation that has some python3.6 packages as buildInputs, it fails with the following error:

```
building '/nix/store/30akhvz6d921h8kj30d2m1qqvm86bls0-python3-3.6.6-env.drv'...
collision between `/nix/store/j9zhsaci7jw4z0ki1nwchvh7pra7dars-python3.6-cairocffi-0.8.1/lib/python3.6/site-packages/.pytest_cache/v/cache/nodeids' and `/nix/store/hnwfl6f04nvhgg733iyjaqs5sf6q9n5c-python3.6-tinycss-0.3/lib/python3.6/site-packages/.pytest_cache/v/cache/nodeids'
builder for '/nix/store/30akhvz6d921h8kj30d2m1qqvm86bls0-python3-3.6.6-env.drv' failed with exit code 25
error: build of '/nix/store/30akhvz6d921h8kj30d2m1qqvm86bls0-python3-3.6.6-env.drv' failed
```

It seems that some unneeded paths have find their way into the packages  (the .pytest_cache/... entry). Those are just subproducts of the testing machinery.

I wasn't unable to find if these packages are obsolete as i'm using unstable 
### Steps to reproduce
I'm trying to reduce my code to something short that shows the error, but I failed until now, sorry... newbie here... I'll update this issue asap

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.5, NixOS, 18.09pre145679.dae9cf6106d (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09pre147850.2428f5dda13"`
 - channels(azazel): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FRidh** [comment] 2018-08-05 07:29
Duplicate of #40273. This should be fixed on master and on the latest channel.

**Comment by FRidh** [comment] 2018-08-05 09:25
Seems like it is still happening. Reopening https://github.com/NixOS/nixpkgs/issues/40273 instead.

**Closed by FRidh** 2018-08-05 09:25 UTC
Labels: 6.topic: python
