### ISSUE TITLE
NixOS installer (14.12): reconfiguration requires network due to (sic!) manual rebuild

### ISSUE THREAD

**Issue by deepfire** [NixOS/nixpkgs#10036] opened 2015-09-24 09:52 UTC
Non-package changes to the live installer's `configuration.nix` and consequent rebuild-switch cause network access to download manual-related things.

This causes problems when the network is unavailable -- and indeed, in the cases when this editing of configuration is for network's sake.

**Comment by vcunat** [comment] 2015-09-24 10:20
Yes, that can happen when we use generator tools (even elsewhere): the stuff is only truly needed during (re-)build time. It isn't clear to me whether we should force such stuff into the closure of systems.

Maybe make it an option and hand-pick some packages into it (for the manual at least)?

`man nix.conf` indicates some general ability to make GC keep build-time dependencies, but not a full one IMO, and typically people do not to keep all build-time dependencies anyway.

**Comment by edolstra** [comment] 2015-09-24 10:48
I think this is generally caused by option descriptions depending on option values, which is generally a bad idea.

Note that it *is* possible to disable the manual entirely.

**Comment by domenkozar** [comment] 2015-09-24 11:29
@deepfire it would help to specify what exactly you changed in `configuration.nix`

**Comment by deepfire** [comment] 2015-09-24 11:36
@domenkozar, the precise information is lost, but it was limited to provision of a static IP network configuration.

**Comment by domenkozar** [comment] 2015-09-24 12:10
This should be fixed with 5b8dae8ef3870aca16632ff29bf26391898d08f5, reopen if the issue presists

**Closed by domenkozar** 2015-09-24 12:10 UTC
Labels: enhancement, nixos

**Comment by deepfire** [comment] 2015-09-24 12:29
@nkaretnikov, /add

**Comment by nkaretnikov** [comment] 2015-09-24 21:03
One thing that nix was trying to download was dhcpcd. But there were other packages. Anyway, I don't understand why dhcpcd was needed since the system was sending DHCP requests before that.

BTW, why does --keep-going fail in the end if something fails to build?  I'd rather make it switch no matter what.

Note that I haven't tested the fix in 5d8dae8.

**Comment by nkaretnikov** [comment] 2015-09-24 21:04
Oh, I forgot to mention that @aszlig suggested to override dhcpcd with null, but that didn't work for me. Maybe we should come up with a working example and add it to some visible place, just in case. WDYT?

**Comment by vcunat** [comment] 2015-09-24 21:45
> BTW, why does --keep-going fail in the end if something fails to build? I'd rather make it switch no matter what.

There's nothing to switch to. BTW, that fix can only help with the manual.

**Comment by aszlig** [comment] 2015-09-25 14:17
@nkaretnikov: You asked about how to blacklist a package but not specifically `dhcpcd`.

If you want to disable DHCP (and thus `dhcpcd`) it's better to use `networking.useDHCP = false` or even `systemd.services.dhcpcd.enable = false` instead of replacing the package by `null` (which is going to end up with a failure to start the `dhcpcd.service`).
