### ISSUE TITLE
Package request: SQLite Studio

### ISSUE THREAD

**Issue by arcbra** [NixOS/nixpkgs#246083] opened 2023-07-29 18:16 UTC
**Project description**

A free, open source, multi-platform SQLite database manager written in C++, with use of Qt framework.

**Metadata**

* homepage URL: https://sqlitestudio.pl/
* source URL: https://github.com/pawelsalawa/sqlitestudio/tree/master
* license: SQLiteStudio is licensed under the GNU General Public License version 3 with the addition of the a special exception
* platforms: Linux

**Comment by felipelalli** [comment] 2023-07-30 15:34
Duplicated with #126536 - please close it.

**Comment by winterqt** [comment] 2023-07-30 15:42
Duplicate of #126536. Please be more careful when opening issues in the future, a simple search would have avoided this.

**Closed by winterqt** 2023-07-30 15:42 UTC
Labels: 0.kind: packaging request
