### ISSUE TITLE
bash_5 fails to build on master

### ISSUE THREAD

**Issue by austinbutler** [NixOS/nixpkgs#111805] opened 2021-02-03 20:22 UTC
**Describe the bug**

Building `bash_5` on master fails.

```
configure: WARNING: unrecognized options: --disable-static
building
build flags: -j16 -l16 SHELL=/nix/store/cwnwyy82wrq53820z6yg7869z8dl5s7g-bash-4.4-p23/bin/bash
cd . && autoconf
/nix/store/cwnwyy82wrq53820z6yg7869z8dl5s7g-bash-4.4-p23/bin/bash: autoconf: command not found
make: *** [Makefile:785: configure] Error 127
builder for '/nix/store/p18w1g4qspagb22qn7i4lijjgkhrgk2m-bash-5.1-p4.drv' failed with exit code 2
error: build of '/nix/store/p18w1g4qspagb22qn7i4lijjgkhrgk2m-bash-5.1-p4.drv' failed
```

I checked the [commit history](https://github.com/NixOS/nixpkgs/commits/nixpkgs-unstable/pkgs/shells/bash/5.1.nix), and going back to 7bc70734309575715c5b3b8c6018a73027e90d5a works.

**To Reproduce**

1. Check out nixpkgs at `77da66eb12c3ff302dd99de2d66fc09e3e902435` (master as of writing)
2. `nix-build -A bash_5`

**Expected behavior**

`bash_5` should build successfully.

**Notify maintainers**

@peti @dtzWill

**Metadata**

```yaml
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.10-arch1-1, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(austin): `"home-manager, nixpkgs-21.03pre267793.5c7a370a208"`
 - nixpkgs: `/home/austin/.nix-defexpr/channels/nixpkgs`
 ```

Maintainer information:

```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - bash_5
# a list of nixos modules affected by the problem
module:
```

**Comment by lourkeur** [comment] 2021-02-03 21:07
Confirmed on NixOS x86_64 (`nix build nixpkgs#bash_5`)

```
@nix { "action": "setPhase", "phase": "buildPhase" }
building
build flags: -j8 -l8 SHELL=/nix/store/cwnwyy82wrq53820z6yg7869z8dl5s7g-bash-4.4-p23/bin/bash
cd . && autoconf
/nix/store/cwnwyy82wrq53820z6yg7869z8dl5s7g-bash-4.4-p23/bin/bash: autoconf: command not found
make: *** [Makefile:785: configure] Error 127
```

Hydra too https://hydra.nixos.org/build/135957178/1/tail

**Comment by andersk** [comment] 2021-03-20 20:14
I’m closing this as a duplicate of #115177, even though this was filed first, because that one has what I think is the root cause.

**Closed by andersk** 2021-03-20 20:14 UTC
Labels: 0.kind: bug
