### ISSUE TITLE
Gitea module creates system user and group without reproducible UID/GID

### ISSUE THREAD

**Issue by Gerschtli** [NixOS/nixpkgs#145014] opened 2021-11-07 21:21 UTC
### Describe the bug
Gitea module creates system user and group without reproducible UID/GID.

### Expected behavior
Every user and group should be created with a statically defined UID/GID.

### Additional context
Unfortunately, defining a value now would result in a breaking change. What would be the best way to handle this?

### Notify maintainers

@srhb @ma27 @disassembler @bjornfor 

### Metadata

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - services.gitea
```

**Comment by Ma27** [comment] 2021-11-07 22:51
We only declare UIDs/GIDs statically if we have a reason to. Please elaborate why this is the case here.

**Comment by Gerschtli** [comment] 2021-11-07 23:46
I would have assumed that every user/group that is created by an official module that resides in nixpkgs has a reproducible UID/GID configured. That would help in several occasions like data synchronization via a shard NFS for example. Using fixed UIDs/GIDs whereever possible would help in getting a really consistent system across different reinstalls.

**Comment by Ma27** [comment] 2021-11-08 00:01
See https://github.com/NixOS/rfcs/blob/master/rfcs/0052-dynamic-ids.md for further context.

UIDs/GIDs aren't unreproducible per-se, as soon as a UID is allocated for a user X (and saved in `/var/lib/nixos`), `users-groups.pl` will ensure that only X will ever get this UID (i.e. no other user can get the UID in question if X was removed). By backing up `/var/lib/nixos`, the re-install issue shouldn't be a problem anymore. Also, NFS supports different kinds of permission-mappings IIRC.

All in all, we're trying to avoid static UIDs/GIDs whenever possible, so I don't see such a change happening for `gitea` soon, hence I'm closing. If you'd like to discuss this more thoroughly, I'd suggest to do it in a separate issue instead since this is not a gitea problem.

**Closed by Ma27** 2021-11-08 00:01 UTC
Labels: 0.kind: bug
