### ISSUE TITLE
can't install or build winetricks

### ISSUE THREAD

**Issue by nergdron** [NixOS/nixpkgs#65103] opened 2019-07-19 19:35 UTC
## Issue description
running `nix-env -i winetricks` fails with build errors, which I guess indicates there isn't a cached binary build to use either.

### Steps to reproduce
`nix-env -i winetricks`
... wait for it to fail.

## Technical details
```bash
$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/rcg8zi8qhprn9qy8rjpprll2a4rfd2yd-bash-interactive-4.4-p23-dev
copying path '/nix/store/rcg8zi8qhprn9qy8rjpprll2a4rfd2yd-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.58, NixOS, 19.09pre185259.362be9608c3 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre185259.362be9608c3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

and the broken build output:

```
g++ -Wl,--no-undefined -Wl,--version-script,QtGui.version -Wl,-O1 -fuse-ld=gold -Wl,--enable-new-dtags -Wl,-z,origin -Wl,-rpath,\$ORIGIN -shared -Wl,-Bsymbolic-functions -Wl,--dynamic-list,/build/qtbase-everywhere-src-5.12.0/src/gui/QtGui.dynlist -Wl,-soname,libQt5Gui.so.5 -o libQt5Gui.so.5.12.0 .obj/qimage_compat.o .obj/qaccessible.o .obj/qaccessiblecache.o .obj/qaccessibleobject.o .obj/qaccessibleplugin.o .obj/qplatformaccessibility.o .obj/qaccessiblebridge.o .obj/qgenericpluginfactory.o .obj/qgenericplugin.o .obj/qwindowsysteminterface.o .obj/qplatforminputcontextfactory.o .obj/qplatforminputcontextplugin.o .obj/qplatforminputcontext.o .obj/qplatformintegration.o .obj/qplatformscreen.o .obj/qplatformintegrationfactory.o .obj/qplatformintegrationplugin.o .obj/qplatformtheme.o .obj/qplatformthemefactory.o .obj/qplatformthemeplugin.o .obj/qplatformwindow.o .obj/qplatformoffscreensurface.o .obj/qplatformcursor.o .obj/qplatformclipboard.o .obj/qplatformnativeinterface.o .obj/qsessionmanager.o .obj/qsurfaceformat.o .obj/qguiapplication.o .obj/qwindow.o .obj/qoffscreensurface.o .obj/qplatformsurface.o .obj/qsurface.o .obj/qclipboard.o .obj/qcursor.o .obj/qevent.o .obj/qinputmethod.o .obj/qinternalmimedata.o .obj/qkeysequence.o .obj/qkeymapper.o .obj/qpalette.o .obj/qguivariant.o .obj/qscreen.o .obj/qshortcutmap.o .obj/qstylehints.o .obj/qtouchdevice.o .obj/qplatformsharedgraphicscache.o .obj/qplatformdialoghelper.o .obj/qplatformservices.o .obj/qplatformsystemtrayicon.o .obj/qplatformsessionmanager.o .obj/qplatformmenu.o .obj/qpixelformat.o .obj/qpaintdevicewindow.o .obj/qrasterwindow.o .obj/qplatformgraphicsbuffer.o .obj/qplatformgraphicsbufferhelper.o .obj/qinputdevicemanager.o .obj/qhighdpiscaling.o .obj/qtestsupport_gui.o .obj/qdnd.o .obj/qdrag.o .obj/qplatformdrag.o .obj/qshapedpixmapdndwindow.o .obj/qsimpledrag.o .obj/qplatformopenglcontext.o .obj/qopenglcontext.o .obj/qopenglwindow.o .obj/qbitmap.o .obj/qimage.o .obj/qimage_conversions.o .obj/qimageiohandler.o .obj/qimagereader.o .obj/qimagereaderwriterhelpers.o .obj/qimagewriter.o .obj/qpaintengine_pic.o .obj/qpicture.o .obj/qpictureformatplugin.o .obj/qpixmap.o .obj/qpixmapcache.o .obj/qplatformpixmap.o .obj/qpixmap_raster.o .obj/qpixmap_blitter.o .obj/qimagepixmapcleanuphooks.o .obj/qicon.o .obj/qiconloader.o .obj/qiconengine.o .obj/qiconengineplugin.o .obj/qmovie.o .obj/qbmphandler.o .obj/qppmhandler.o .obj/qxbmhandler.o .obj/qxpmhandler.o .obj/qpnghandler.o .obj/qfont.o .obj/qfontengine.o .obj/qfontengineglyphcache.o .obj/qfontsubset.o .obj/qfontmetrics.o .obj/qfontdatabase.o .obj/qtextengine.o .obj/qtextlayout.o .obj/qtextformat.o .obj/qtextobject.o .obj/qtextoption.o .obj/qfragmentmap.o .obj/qtextdocument.o .obj/qtextdocument_p.o .obj/qtexthtmlparser.o .obj/qabstracttextdocumentlayout.o .obj/qtextdocumentlayout.o .obj/qtextcursor.o .obj/qtextdocumentfragment.o .obj/qtextimagehandler.o .obj/qtexttable.o .obj/qtextlist.o .obj/qtextdocumentwriter.o .obj/qsyntaxhighlighter.o .obj/qstatictext.o .obj/qrawfont.o .obj/qglyphrun.o .obj/qdistancefield.o .obj/qinputcontrol.o .obj/qfontengine_qpf2.o .obj/qplatformfontdatabase.o .obj/qharfbuzzng.o .obj/qtextodfwriter.o .obj/qzip.o .obj/qcssparser.o .obj/qbackingstore.o .obj/qbezier.o .obj/qblendfunctions.o .obj/qblittable.o .obj/qbrush.o .obj/qcolor.o .obj/qcolorprofile.o .obj/qcompositionfunctions.o .obj/qcosmeticstroker.o .obj/qdrawhelper.o .obj/qemulationpaintengine.o .obj/qgrayraster.o .obj/qimagescale.o .obj/qmatrix.o .obj/qmemrotate.o .obj/qoutlinemapper.o .obj/qpagedpaintdevice.o .obj/qpagelayout.o .obj/qpagesize.o .obj/qpaintdevice.o .obj/qpaintengine.o .obj/qpaintengineex.o .obj/qpaintengine_blitter.o .obj/qpaintengine_raster.o .obj/qpainter.o .obj/qpainterpath.o .obj/qpathclipper.o .obj/qpdf.o .obj/qpdfwriter.o .obj/qpen.o .obj/qpolygon.o .obj/qrasterizer.o .obj/qregion.o .obj/qstroker.o .obj/qtextureglyphcache.o .obj/qtransform.o .obj/qtriangulatingstroker.o .obj/qtriangulator.o .obj/qplatformbackingstore.o .obj/qpathsimplifier.o .obj/qcssutil.o .obj/qdesktopservices.o .obj/qvalidator.o .obj/qgridlayoutengine.o .obj/qabstractlayoutstyleinfo.o .obj/qlayoutpolicy.o .obj/qshaderformat.o .obj/qshadergenerator.o .obj/qshadergraph.o .obj/qshadergraphloader.o .obj/qshaderlanguage.o .obj/qshadernode.o .obj/qshadernodeport.o .obj/qshadernodesloader.o .obj/qtexturefiledata.o .obj/qtexturefilereader.o .obj/qpkmhandler.o .obj/qktxhandler.o .obj/qgenericmatrix.o .obj/qmatrix4x4.o .obj/qquaternion.o .obj/qvector2d.o .obj/qvector3d.o .obj/qvector4d.o .obj/qopengl.o .obj/qopenglfunctions.o .obj/qopenglframebufferobject.o .obj/qopenglpaintdevice.o .obj/qopenglbuffer.o .obj/qopenglshaderprogram.o .obj/qopenglgradientcache.o .obj/qopengltexturecache.o .obj/qopenglengineshadermanager.o .obj/qopengl2pexvertexarray.o .obj/qopenglpaintengine.o .obj/qopenglcustomshaderstage.o .obj/qopengltextureglyphcache.o .obj/qopenglversionfunctions.o .obj/qopenglversionfunctionsfactory.o .obj/qopenglvertexarrayobject.o .obj/qopengldebug.o .obj/qopengltextureblitter.o .obj/qopengltexture.o .obj/qopengltexturehelper.o .obj/qopengltextureuploader.o .obj/qopenglpixeltransferoptions.o .obj/qopenglprogrambinarycache.o .obj/qopenglfunctions_1_0.o .obj/qopenglfunctions_1_1.o .obj/qopenglfunctions_1_2.o .obj/qopenglfunctions_1_3.o .obj/qopenglfunctions_1_4.o .obj/qopenglfunctions_1_5.o .obj/qopenglfunctions_2_0.o .obj/qopenglfunctions_2_1.o .obj/qopenglfunctions_3_0.o .obj/qopenglfunctions_3_1.o .obj/qopenglfunctions_3_2_core.o .obj/qopenglfunctions_3_3_core.o .obj/qopenglfunctions_4_0_core.o .obj/qopenglfunctions_4_1_core.o .obj/qopenglfunctions_4_2_core.o .obj/qopenglfunctions_4_3_core.o .obj/qopenglfunctions_4_4_core.o .obj/qopenglfunctions_4_5_core.o .obj/qopenglfunctions_3_2_compatibility.o .obj/qopenglfunctions_3_3_compatibility.o .obj/qopenglfunctions_4_0_compatibility.o .obj/qopenglfunctions_4_1_compatibility.o .obj/qopenglfunctions_4_2_compatibility.o .obj/qopenglfunctions_4_3_compatibility.o .obj/qopenglfunctions_4_4_compatibility.o .obj/qopenglfunctions_4_5_compatibility.o .obj/qopengltimerquery.o .obj/qguivariantanimation.o .obj/qstandarditemmodel.o .obj/qrc_qpdf.o .obj/qrc_qmake_webgradients.o .obj/moc_qaccessible.o .obj/moc_qaccessiblecache_p.o .obj/moc_qaccessibleplugin.o .obj/moc_qaccessiblebridge.o .obj/moc_qgenericplugin.o .obj/moc_qplatforminputcontext.o .obj/moc_qplatforminputcontextplugin_p.o .obj/moc_qplatformintegrationplugin.o .obj/moc_qplatformthemeplugin.o .obj/moc_qplatformnativeinterface.o .obj/moc_qplatformmenu.o .obj/moc_qsurfaceformat.o .obj/moc_qoffscreensurface.o .obj/moc_qsurface.o .obj/moc_qclipboard.o .obj/moc_qevent.o .obj/moc_qinternalmimedata_p.o .obj/moc_qkeysequence.o .obj/moc_qkeymapper_p.o .obj/moc_qpalette.o .obj/moc_qsessionmanager.o .obj/moc_qscreen.o .obj/moc_qstylehints.o .obj/moc_qtouchdevice.o .obj/moc_qplatformsharedgraphicscache.o .obj/moc_qplatformdialoghelper.o .obj/moc_qpaintdevicewindow.o .obj/moc_qrasterwindow.o .obj/moc_qplatformgraphicsbuffer.o .obj/moc_qinputdevicemanager_p.o .obj/moc_qdnd_p.o .obj/moc_qdrag.o .obj/moc_qshapedpixmapdndwindow_p.o .obj/moc_qopenglwindow.o .obj/moc_qimage.o .obj/moc_qimageiohandler.o .obj/moc_qpictureformatplugin.o .obj/moc_qiconengineplugin.o .obj/moc_qfont.o .obj/moc_qfontdatabase.o .obj/moc_qtextformat.o .obj/moc_qtextobject.o .obj/moc_qtextdocument.o .obj/moc_qtextimagehandler_p.o .obj/moc_qtexttable.o .obj/moc_qtextlist.o .obj/moc_qinputcontrol_p.o .obj/moc_qbrush.o .obj/moc_qpainter.o .obj/moc_qpdfwriter.o .obj/moc_qplatformbackingstore.o .obj/moc_qvalidator.o .obj/moc_qshaderlanguage_p.o .obj/moc_qopenglshaderprogram.o .obj/moc_qopenglengineshadermanager_p.o .obj/moc_qopengltexture.o .obj/moc_qopengltimerquery.o  -L/nix/store/rlvbxm3cmxxpb3a2cx4zvmfa2szdhw9n-libGL-1.0.0/lib -L/build/qtbase-everywhere-src-5.12.0/lib -lQt5Core -lpthread -L/nix/store/q856jpgr6ib5zgi43gi4nybw7k9av62f-libglvnd-1.0.0/lib -lGL -L/nix/store/7ynf9bc7d2ldk54yzcxrd0wzb4jbcjgc-zlib-1.2.11/lib -L/nix/store/pjayirrj98lsw9yy40fzqxdsfbs3ni5p-libpng-apng-1.6.37/lib -lpng16 -lharfbuzz -lz
.obj/qpathsimplifier.o:qpathsimplifier.cpp:function (anonymous namespace)::PathSimplifier::intersectNodes(QDataBuffer<(anonymous namespace)::PathSimplifier::Element*>&, (anonymous namespace)::PathSimplifier::BoundingVolumeHierarchy::Node*, (anonymous namespace)::PathSimplifier::BoundingVolumeHierarchy::Node*): error: undefined reference to '__divmoddi4'
.obj/qpathsimplifier.o:qpathsimplifier.cpp:function (anonymous namespace)::PathSimplifier::intersectNodes(QDataBuffer<(anonymous namespace)::PathSimplifier::Element*>&, (anonymous namespace)::PathSimplifier::BoundingVolumeHierarchy::Node*, (anonymous namespace)::PathSimplifier::BoundingVolumeHierarchy::Node*): error: undefined reference to '__divmoddi4'
.obj/qpathsimplifier.o:qpathsimplifier.cpp:function (anonymous namespace)::PathSimplifier::intersectNodes(QDataBuffer<(anonymous namespace)::PathSimplifier::Element*>&, (anonymous namespace)::PathSimplifier::BoundingVolumeHierarchy::Node*, (anonymous namespace)::PathSimplifier::BoundingVolumeHierarchy::Node*): error: undefined reference to '__divmoddi4'
.obj/qpathsimplifier.o:qpathsimplifier.cpp:function (anonymous namespace)::PathSimplifier::intersectNodes(QDataBuffer<(anonymous namespace)::PathSimplifier::Element*>&, (anonymous namespace)::PathSimplifier::BoundingVolumeHierarchy::Node*, (anonymous namespace)::PathSimplifier::BoundingVolumeHierarchy::Node*): error: undefined reference to '__divmoddi4'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1312: ../../lib/libQt5Gui.so.5.12.0] Error 1
make[2]: Leaving directory '/build/qtbase-everywhere-src-5.12.0/src/gui'
make[1]: *** [Makefile:448: sub-gui-make_first] Error 2
make[1]: Leaving directory '/build/qtbase-everywhere-src-5.12.0/src'
make: *** [Makefile:49: sub-src-make_first] Error 2
builder for '/nix/store/j36h7b7003w6xlf5fksp6bj9s6qmb074-qtbase-5.12.0.drv' failed with exit code 2
cannot build derivation '/nix/store/qzd1k2f43zxhd38q5q4g0jpq6q1s4089-python3.7-PyQt-5.11.3.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/m4n5m1mjznvn712hnjmyv2c1l1fcqlg6-zbar-0.23.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/c3iq7vz93zr3kbzf2vskb1w0g6q960w8-ffado-2.4.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/f65qql57q7rrfhsgi53xqb125vpvknck-gst-plugins-bad-1.16.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/dqkm5k6y6adscqib8i0029w1mif9rj2c-wine-4.0.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/chz5cv7qmyyk9l7p8dqdfw50xzyjva8j-winetricks-20190310.drv': 1 dependencies couldn't be built
error: build of '/nix/store/chz5cv7qmyyk9l7p8dqdfw50xzyjva8j-winetricks-20190310.drv' failed
```

this is especially weird that it's trying to rebuilt all of wine, since winetricks itself is just a shell script:

https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks

**Comment by matthewbauer** [comment] 2019-07-19 20:44
Duplicate of #63829

**Closed** 2019-07-20 10:24 UTC
