### ISSUE TITLE
Steam : can't download dependancies

### ISSUE THREAD

**Issue by katyucha** [NixOS/nixpkgs#49584] opened 2018-11-01 12:16 UTC
## Issue description
Can't install steam anymore

Here the pastebin : https://paste.katyucha.ovh/?f2003835a45b73bc#ar0bphpmuokcp0mRcQ0CQtGasUNNBlEPXWRZcoX8XWw=

### Steps to reproduce
nix-env -iA nixos.steam

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.09.1023.06fb0253afa (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09.1023.06fb0253afa"`
 - channels(katyucha): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FRidh** [comment] 2018-11-01 12:45
Duplicate of https://github.com/NixOS/nixpkgs/issues/49048

**Closed by FRidh** 2018-11-01 12:45 UTC
