### ISSUE TITLE
wrapQtAppsHook broken on macOS

### ISSUE THREAD

**Issue by hannesweisbach** [NixOS/nixpkgs#102044] opened 2020-10-29 13:15 UTC
**Describe the bug**

The convenience function `wrapQtAppsHook` does not work on macOS. The calls `patchelf` like so:
```
            patchelf --print-interpreter "$file" >/dev/null 2>&1 || continue
```
If the calls succeeds `wrapQtApp` is called with`$file` as argument. Since `patchelf` is not installed, this always fails, skip all files, and binaries are not properly wrapped – and hence fail to execute.

As a work-around I had to call `wrapQtApp` manually in the `preFixup` phase. It did it's thing, wrapped the binary properly and I could run the binary without issues.

**To Reproduce**
1. Build an arbitrary Qt app on macOS (for example gpxlab or glogg, but really any Qt app works …)
2. Compile and install under Linux, to see wrapping working
3. Disable manual call to `wrapQtApp`
4. Compile and install under macOS to see wrapping via the hook doing nothing
5. Verify that the app under macOS is indeed not wrapped and fails to execute

**Expected behavior**

Properly wrapped application. Wrapping itself works, as evidenced by a manual call to `wrapQtApp`, but have the hook not depend on `patchelf` on macOS or at least ** give a warning **  and give a warning in the manual.

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.01 MiB download, 0.03 MiB unpacked):
  /nix/store/12pkkc7l378r75xz1kvh39wlk1p4gw7w-DarwinTools-1
  /nix/store/zvir75d0b5swjva0xkyxcidpagf7jpdv-nix-info
copying path '/nix/store/12pkkc7l378r75xz1kvh39wlk1p4gw7w-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/zvir75d0b5swjva0xkyxcidpagf7jpdv-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(hannesweisbach): `""`
 - channels(root): `"nixpkgs-20.09pre242465.bd649f4f55c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment] 2020-11-01 13:34
This must have been broken for over a year then, when c6d516dfc49c1d84ef03605e0d2b8aa3ea8ae431 as part of https://github.com/NixOS/nixpkgs/pull/68513 was merged.

**Comment by FRidh** [comment] 2020-11-01 13:40
Is `patchelf` part of the `stdenv` for Darwin? Could you run
```
$ nix-shell --pure -p --run patchelf
```

**Comment by hannesweisbach** [comment] 2020-11-02 08:24
> Is `patchelf` not part of the `stdenv` for Darwin? Could you run
> 
> ```
> $ nix-shell --pure -p --run patchelf
> ```

Yes, sure:

```
% nix-shell --pure -p --run patchelf
/private/var/folders/gy/ngbl8v6s24gb86kc6lbjg9rr0000gn/T/nix-shell-30699-0/rc: line 1: patchelf: command not found
```

> This must have been broken for over a year then, when [c6d516d](https://github.com/NixOS/nixpkgs/commit/c6d516dfc49c1d84ef03605e0d2b8aa3ea8ae431) as part of #68513 was merged.

Hm, did I f*** something up?

**Comment by FRidh** [comment] 2020-11-02 08:33
Okay, so either the commit i pointed to is responsible for this, or
sometime since then patcheld got removed from darwin stdenv or at least the
builder.

**Comment by hannesweisbach** [comment] 2020-11-02 08:39
Thanks for looking into this.

Does this help:

```
pwd
/Users/hannesweisbach/.nix-defexpr/channels/nixpkgs
hannesweisbach@MBP nixpkgs % ack -i patchelf ./pkgs/stdenv/darwin
```

**Comment by OPNA2608** [comment] 2021-03-18 07:58
Would patchelf availability even fix anything in that check? Darwin binaries aren't ELF files, they're Mach-Os.

![grafik](https://user-images.githubusercontent.com/23431373/111591420-b764a480-87c7-11eb-8adf-67c65493c5dd.png)

**Comment by OPNA2608** [comment] 2021-04-14 08:42
Different question, is the patchelf check even needed? `wrapGAppsHook` just finds all executable files in a list of paths and wraps them.

https://github.com/NixOS/nixpkgs/blob/d600f006643e074c2ef1d72e462e218b647a096c/pkgs/build-support/setup-hooks/wrap-gapps-hook/wrap-gapps-hook.sh#L65-L69

**Comment by hannesweisbach** [comment] 2021-04-28 06:57
I don't know. patchelf itself probably isn't needed itself, only the fixup/wrap in paths. However, I'm not really qualified to give an answer.

I also don't have/use nix anymore. While its proposition was good, it was just too time consuming to get stuff working on macOS (compile time-wise, bug finding-wise and getting feedback on patches on issues).

**Comment by graham33** [comment] 2021-07-20 22:31
Just to confirm I'm also running into this (in my case it's causing pkgs.octaveFull binaries not to be wrapped for Qt).  I don't use darwin often, but I can confirm this issue wasn't present in a previous build I did from nixpkgs master from 25 Aug 2020 which already contains the `patchelf --print-interpreter` change, so I think it's more likely patchelf was removed later somehow on darwin.

**Comment by graham33** [comment] 2021-07-20 23:06
@OPNA2608 I agree, in my testing patchelf will fail on the executable I care about wrapping (octave) anyway.  I think we need to do something different on Darwin (either wrap everything executable, or use something else like `file` to detect Mach-O executables - I'd probably lean towards just wrapping all executables for simplicity).  Does anyone know a good way to detect Darwin inside the hook?

**Comment by smancill** [comment] 2021-08-13 20:40
The above PR would not close this, I wrote "should help fix <this issue>" and GitHub took the "fix" string as closing this. I've updated the PR comment with better wording.

**Closed** 2021-11-17 10:35 UTC
Labels: 0.kind: bug, 6.topic: darwin, 6.topic: qt/kde
