### ISSUE TITLE
fastfetch package

### ISSUE THREAD

**Issue by dnkmmr69420** [NixOS/nixpkgs#222739] opened 2023-03-23 14:47 UTC
**Project description**
Fastfetch is just like neofetch except it is written in C and is still being updated

"Fastfetch is a [neofetch](https://github.com/dylanaraps/neofetch)-like tool for fetching system information and displaying them in a pretty way. It is written mainly in C, with performance and customizability in mind. Currently, Linux, Android, FreeBSD, MacOS and Windows 7+ are supported." (description from main github readme)

**Metadata**

* both homepage URL and source: https://github.com/LinusDierheimer/fastfetch
* license: MIT
* platforms: FreeBSD, Linux, Darwin, Windows
* architectures: x86_64 aarch64

**Comment by figsoda** [comment] 2023-03-23 16:20
duplicate of #176799

there is an open PR: #176819

**Closed** 2023-03-30 06:52 UTC
Labels: 2.status: duplicate, 0.kind: packaging request
