### ISSUE TITLE
patchShebangs does not take into account NixOS specific setup

### ISSUE THREAD

**Issue by wwat** [NixOS/nixpkgs#5692] opened 2015-01-10 15:49 UTC
patchShebangs happily rewrites /usr/bin/pkexec to some /nix/store/ path. I think this is very undesired behaviour and the right behaviour would be to take into consideration that store paths like /nix/store/.../pkexec are never valid interpreters (and thus the rewrite should not happen or it should be rewritten to the system version (/var/...)).

**Comment by vcunat** [comment] 2015-01-11 14:35
I'm not sure that's a problem of ``patchShebangs`` itself: it just takes whatever is first on the current ``$PATH`` (when running ``patchShebangs``; it uses ``command -v foo``). I think that's *mostly* the right thing to do.&trade;

Note that e.g. in the case when we patch scripts to be runnable *during* the build (only), we don't even have access to ``/var`` or ``/run``, so we don't want to use such paths (in that case). I see no simple drop-in improvement of the semantics ATM. Perhaps the packages containing pkexec and similar should contain hooks to override those particular cases.

**Comment by bjornfor** [comment] 2015-01-11 14:44
@wwat: I don't know the reason for zoneminder to use pkexec shebang; I patched it so that it only uses pkexec on the command that really needs privileges (the shellout to systemd), instead of running that whole perl script via pkexec. We should just push that patch upstream and the issue is gone.

I agree with @vcunat, there is not an obvious way to improve the situation in the generic builder.

**Comment by wwat** [comment] 2015-01-11 19:30
@bjornfor Oh, good find. I thought there where calls coming from a lot of places. 

@vcunat I saw an IRC message saying something along the lines that patchShebangs is not well documented, either. (I also had to read the code at some point (but that's not how it's supposed to work)). 

There are also various places where assignments of the following form are being done:
```
a="$1"
```

The quotes are not needed in that case. 

It should be very easy to find all the places where this happens via a simple grep.

**Comment by bjornfor** [comment] 2015-01-11 19:38
@wwat: I might be wrong, but so far I haven't had any more pkexec issues after that patch. Quoting shell variables is just good style. (What would happen if someone _did_ pass something with whitespace?)

**Comment by wwat** [comment] 2015-01-11 19:42
@bjornfor It is *not* needed. It only tells me that whoever has written the NixOS build scripts wasn't very good at it. Read the POSIX standard on `sh` and you will see that I am right. 

Or just run this in your shell:
```
a='1 b c '  
b=$a                                                                                                                                     
echo "$b"
```

**Comment by bjornfor** [comment] 2015-01-11 22:10
@wwat: Oh, I didn't know about that. It's probably me that added quotes to variables in patchShebangs (I touched it once).

I've seen many broken shell scripts caused by to little quoting, so I'm a bit reluctant to dropping the quotes, even in places where it's safe to do so. (My personal rule is to quote everything that's not explicitly meant for word splitting.)

**Comment by vcunat** [comment] 2015-01-11 22:14
I think these extra quotes are a completely unimportant issue (and off-topic anyway).

**Comment by bjornfor** [comment] 2015-07-12 10:19
patchShebangs writes the path to the command that is first found in $PATH. I think it should be the responsibility of the user (aka. developer writing nix package expression) to ensure that $PATH is setup correctly.

Even if patchShebangs were to hardcode some paths in /var/setuid-wrappers/ (where that makes sense), there will probably be cases where that behaviour is wrong. The current behaviour is just a healthy separation of mechanism and policy, IMHO.

Closing.

**Closed by bjornfor** 2015-07-12 10:19 UTC
