### ISSUE TITLE
nixos-option does not work with flakes

### ISSUE THREAD

**Issue by TheOPtimal** [NixOS/nixpkgs#154900] opened 2022-01-13 15:27 UTC
### Describe the bug
The `nixos-option` program does not work with flake-based configurations.

### Steps To Reproduce
1. Switch the system to a flake-based configuration that differs in some way to the configuration located in /etc/nixos
2. Run `nixos-option` on the changed option
3. You will see the option as it is in `/etc/nixos` instead of the flake

### Expected behavior
`nixos-option` should display the option as evaluated in the flake-based configuration

### Screenshots
![Option `boot.plymouth.enable` set to true in flake configuration](https://user-images.githubusercontent.com/41379516/149357448-c445f1e0-e339-42d3-b6f9-86f3d558d0e4.png)
![`nixos-option` displaying the option as `false` as it was in the `/etc/nixos` configuration](https://user-images.githubusercontent.com/41379516/149357617-1253cf0e-3b33-4607-9086-8a2ecd95a621.png)

### Additional context
This issue could be resolved by moving the configuration flake to `/etc/nixos`, however this is more of a hack rather than a solution because system configuration flakes are independent of a static location.

### Notify maintainers

@chkno

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.12, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by edrex** [comment] 2022-01-21 23:15
#97855

**Comment by fabianhauser** [comment] 2022-03-20 17:26
Duplicate of https://github.com/NixOS/nixpkgs/issues/97855

**Closed by fabianhauser** 2022-03-20 17:26 UTC
Labels: 0.kind: bug
