### ISSUE TITLE
ESPhome: ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by techyporcupine** [NixOS/nixpkgs#266883] opened 2023-11-11 17:03 UTC
### Describe the bug
Hello, I have been messing around with ESPhome more on NixOS and recently tried using the `esp-idf` framework for a device. When I run the yaml file, I get the following error: `ModuleNotFoundError: No module named 'pkg_resources':` followed by a bunch of text. (If it's needed, I can send it as well.)

### Steps To Reproduce
1. Create a ESPhome file for an ESP32 and use the `esp-idf` framework
2. Try to build/run the file
3. Observe the error

### Expected behavior
I expected for it to compile, then get uploaded to my device.

### Additional context
I have attempted adding `setuptools` as a build input for it in a fork of nixpkgs and then using the package from there, but it didn't seem to work, unless I did something wrong...

### Notify maintainers
@mweinelt 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.0, NixOS, 23.11 (Tapir), 23.11.20231104.85f1ba3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(redacted): `""`
 - nixpkgs: `/nix/store/kcmipm57ph9bpzz8bs80iiijiwbyzwy3-source`

```

**Comment by mweinelt** [comment] 2023-11-11 19:01
Duplicate of https://github.com/NixOS/nixpkgs/issues/227230. Issue lies in platformio, not esphome.

**Closed by mweinelt** 2023-11-11 19:01 UTC
Labels: 0.kind: bug
