### ISSUE TITLE
python36Packages.pylint build failure (test phase)

### ISSUE THREAD

**Issue by seqizz** [NixOS/nixpkgs#59356] opened 2019-04-12 14:30 UTC
## Issue description

Switching to 19.03 broke pylint's tests (again? #51394)

### Steps to reproduce

`nix-shell -p python36Packages.pylint`

```
=================================== FAILURES ===================================
________________ TestNameChecker.test_assign_to_new_keyword_py3 ________________
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.34, NixOS, 19.03.172138.5c52b25283a (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03.172138.5c52b25283a"`
 - channels(myuser): `"home-manager-19.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FRidh** [comment] 2019-04-12 15:39
We don't do any regression testing for Python 3.6 packages on 19.03 (only 2.7 and 3.7) so these bugs may indeed slip in. If you like to have this fixed, please open a PR. I will be closing this issue because I don't see much point in having issues for packages for which we don't actually test.

**Closed by FRidh** 2019-04-12 15:39 UTC

**Comment by seqizz** [comment] 2019-04-12 15:49
I thought having it available qualifies it for "supported".
Thanks anyway, time to upgrade to 3.7 :)
