### ISSUE TITLE
tor-browser-bundle-bin segmentation fault

### ISSUE THREAD

**Issue by helma** [NixOS/nixpkgs#146401] opened 2021-11-17 15:25 UTC
### Describe the bug
tor-browser crashes with a segmentation fault immediately after startup

### Steps To Reproduce
1. Add nixpkgs-unstable to avoid 404 download errors: `nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs-unstable`
2. Update channels: `nix-channel --update` 
3. Add nixpkgs-unstable to configuration.nix
```
 nixpkgs = {
      config = {
        packageOverrides = pkgs: {
          unstable = import <nixpkgs-unstable> {
            config = config.nixpkgs.config;
          };
      };
   };
```
4. Install tor-browser-bundle-bin with home-manager:
```
home-manager = {
    users.ch = { pkgs, ... }: {
      home = {
        packages = with pkgs; [
          unstable.tor-browser-bundle-bin
        ]
      };
   };
};
```
5. `nixos-rebuild switch --upgrade`
6. Start tor-browser
```
> tor-browser
fatal allocator error: invalid uninitialized allocator usage
Redirecting call to abort() to mozalloc_abort

fish: Job 1, 'tor-browser' terminated by signal SIGSEGV (Address boundary error)
```

### Expected behavior
tor-browser should start without crashing

### Additional context
I am using Wayland/Sway with pipewire audio. I have tried without any effect to
- set MOZ_ENABLE_WAYLAND to 1
- switch between wayland and x11 for GDK_BACKEND
- disable pipewire and enable pulseaudio

in fish and bash .

### Notify maintainers
@offline @matejc @thoughtpolice @joachifm @hax404 @KarlJoad

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.79, NixOS, 21.05.4116.46251a79f75 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"home-manager-21.05, nixos-21.05.4116.46251a79f75, nixos-hardware, nixpkgs-unstable-21.11pre330734.5cb226a06c4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by helma** [comment] 2021-11-17 17:23
Thanks, tor-browser starts with `useHardenedMalloc = false`! My graphics card is a
`00:02.0 VGA compatible controller: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01)`, it might be related  to the "crashing tabs" problem mentioned in https://github.com/NixOS/nixpkgs/commit/5499f32f080874af2b88e691c349aad913e8267e

**Comment by tnias** [comment] 2021-11-26 00:54
Thanks for the workaround. My graphics card is `00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)` and I had the same problem.

**Comment by schmittlauch** [comment] 2021-12-02 14:16
Another data point:
With my graphics chip `VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b)` (also known as *Intel® HD-Grafik 4400*), tor-browser crashes with `useHardenedMalloc = true;` but works fine with `useHardenedMalloc = false;`.

**Comment by zseri** [comment] 2021-12-04 14:58
Another data point: also seems to happen with my graphics chip `VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Trinity [Radeon HD 7660D]`, tor-browser crashes, currently rebuilding my system to check if `useHardenedMalloc = true;` helps.

**Comment by yayayayaka** [comment] 2022-03-01 18:58
Just bumped into this. Defining

```
environment.systemPackages = with pkgs; [
  (tor-browser-bundle-bin.override {
    useHardenedMalloc = false;
   })
];
```
from the above discourse thread resolved the issue.

**Comment by dmadisetti** [comment] 2022-03-17 02:13
Just a note, if `firefox` has had a run previously then `tor-browser` also seems to work.

Steps: 
 1. `nix-shell -p firefox --command firefox`
 2. close Firefox
 3. `tor-browser`
 4. rejoice 🎉

This is obviously less than ideal, but it might mean we just have to bootstrap the Firefox profile. Haven't done much investigation

**Comment by dmadisetti** [comment] 2022-05-12 01:32
I no longer have this issue with a clean environment on Wayland

**Comment by mightyiam** [comment] 2022-05-12 16:37
> I no longer have this issue with a clean environment on Wayland

Ditto

**Comment by helma** [comment] 2022-05-20 16:05
Hardened malloc tor-browser still segfaults on my system.

**Comment by helma** [comment] 2022-07-20 21:23
unstable.tor-browser-bundle-bin works now on my system (NixOS 22.05)

**Comment by hxr404** [comment] 2023-02-18 19:30
Can reproduce this on NixOS 22.11.20230216.2fb7d74 using KDE Plasma (Xorg).
The workaround by @dmadisetti (launching firefox before tb) works for me, but I think this issue should be re-opened nonetheless as the bug isn't really fixed.

At least the latest stable release (22.11) doesn't work so even if this was fixed in unstable (like @helma commented), the fix should be backported, thus another reason to re-open.
Due to the bug being extremly inconsistent (haven't been able to figure out the circumstances under which it gets triggered, it seems almost random) I can't confirm that this hasn't been fixed in unstable, though. However, I will update this as soon as I know more.

**Comment by Lillecarl** [comment] 2023-05-23 23:38
I've still got this issue. AMD 5850U, KDE, Wayland

**Comment by CobaltCause** [comment] 2023-07-11 04:08
FWIW, someone on Matrix just ran into this and https://github.com/NixOS/nixpkgs/issues/146401#issuecomment-1055755932 solved it for them.

**Comment by Lillecarl** [comment] 2023-08-08 21:24
@felschr @panicgh @joachifm @hax404 You're listed as maintainers, should this stay broken or could hardenedmalloc we opt-in rather than "opt-out"? It'd be a non-breaking change for everyone consuming the package with inputs as-is today if switched.

**Comment by felschr** [comment] 2023-08-08 23:00
@Lillecarl Thank you for the ping. I don't get this issue myself but looks like quite a few people are affected.

I've actually looked a bit into the malloc stuff in Firefox a while ago and it seems that providing a different allocator via `LD_PRELOAD` doesn't even (fully) work because Firefox statically links jemalloc (see [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1668674)). The only way around this is building Firefox with `--disable-jemalloc` and Tor Browser's official builds don't do this.

I think it would actually be best just to remove the option altogether.

**Closed** 2023-08-25 18:12 UTC
Labels: 0.kind: bug

**Comment by Lillecarl** [comment] 2023-08-25 21:42
@fpletz thanks for your engagement!
