### ISSUE TITLE
iosevka-comfy does not build

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#185597] opened 2022-08-07 20:57 UTC
### Describe the bug

Building iosevka-comfy.comfy fails with the messages:

```console
$ nix-build --option sandbox true -K -A iosevka-comfy.comfy
this derivation will be built:
  /nix/store/sj22flg94xpjcvg5rgc7pf794wgq4z9a-iosevka-comfy-0.3.1.drv
building '/nix/store/sj22flg94xpjcvg5rgc7pf794wgq4z9a-iosevka-comfy-0.3.1.drv'...
unpacking sources
unpacking source archive /nix/store/8k7893693wqpnfi8s0c9bv8mh2kjicxz-iosevka-15.5.2.tar.gz
source root is Iosevka-15.5.2
setting SOURCE_DATE_EPOCH to timestamp 1656159437 of file Iosevka-15.5.2/verdafile.js
patching sources
configuring
building

Error: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/build/Iosevka-15.5.2/font-src/index' imported from /nix/store/b90gfjqlcsrm566fj601im22gbd8685j-iosevka-15.5.2/lib/node_modules/iosevka/node_modules/verda/lib/actions/nodejs/nodejs-call-process.js
Did you mean to import /build/Iosevka-15.5.2/font-src/index.js?
    at new NodeError (internal/errors.js:322:7)
    at finalizeResolution (internal/modules/esm/resolve.js:318:11)
    at moduleResolve (internal/modules/esm/resolve.js:776:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at Loader.import (internal/modules/esm/loader.js:177:28)
    at importModuleDynamically (internal/modules/cjs/loader.js:1028:27)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at process.<anonymous> (/nix/store/b90gfjqlcsrm566fj601im22gbd8685j-iosevka-15.5.2/lib/node_modules/iosevka/node_modules/verda/lib/actions/nodejs/nodejs-call-process.js:17:52) {
  code: 'ERR_MODULE_NOT_FOUND'
}
    at ChildProcess.<anonymous> (/nix/store/b90gfjqlcsrm566fj601im22gbd8685j-iosevka-15.5.2/lib/node_modules/iosevka/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (events.js:400:28)
    at emit (internal/child_process.js:935:14)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

### Notify maintainers

@DamienCassou 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.0, NixOS, 22.11 (Raccoon), 22.11.git.b73c161c630`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by toastal** [comment] 2022-08-08 05:47
This affects all Iosevka custom overrides

**Comment by t184256** [comment] 2022-08-08 06:25
It's probably https://github.com/be5invis/Iosevka/issues/1383, but 15.6.* versions hang and time out for me.

**Comment by nagy** [comment] 2022-08-08 09:50
Duplicate of https://github.com/NixOS/nixpkgs/issues/185633

**Comment by DamienCassou** [comment] 2022-08-09 08:46
I'm closing this issue as the duplicate https://github.com/NixOS/nixpkgs/issues/185633 has slightly more information.

**Closed by DamienCassou** 2022-08-09 08:46 UTC
Labels: 0.kind: bug
