### ISSUE TITLE
VirtualBox nixos guest missing 3D acceleration

### ISSUE THREAD

**Issue by viric** [NixOS/nixpkgs#18457] opened 2016-09-09 07:35 UTC
In NixOS 16.03 I enable VirtualBox guest additions (virtualization.virtualbox.guest.enable = true) and I properly get Direct Rendering in X.org but it still uses the swrast GL code. In VirtualBox I do enable "3D acceleration" but I guess there should be some userlib in the guest that makes GL go through the vm for the acceleration.

Does anybody know how to get this 3d acceleration?

Thank you.

**Comment by domenkozar** [comment] 2016-09-12 11:57
Did you check if guest additions are correctly installed and enabled?

**Comment by viric** [comment] 2016-10-11 07:56
Sure, they are installed. I also made the guest nixos module put virtualbox_dri.so to /run/opengl-driver/lib/dri, but that did not help.

My X log only says:
```
vboxvideo: kernel driver found, not loading.
modeset(0): using drv /dev/dri/card0
...
AIGLX: Screen 0 is not DRI2 compatible
AIGLX: reverting to software rendering
```

I tried with 'modeset' in cmdline too, no difference.

**Comment by viric** [comment] 2016-10-11 08:39
Ok, I have a dirty patch that makes it work. Basically, libGL.so.1 should point to VBoxOGL.so, instead of the mesa one. Then, acceleration works.

But in my machine, Optimus (Intel+NVidia), I fail to make the acceleration go through NVidia and I only get the Intel acceleration. Like this poor guy: http://superuser.com/questions/779070/use-nvidia-gpu-from-virtualbox  (but it is another topic).

We should think how to add a nixos option that makes the libGL.so.1 override in opengl-drivers/lib

**Comment by viric** [comment] 2016-10-11 09:02
btw, here is the source from where I got the idea of the symlink: https://bugs.archlinux.org/task/49752

**Comment by husnoo** [comment] 2016-12-22 08:54
I was able to get it to work using the link you provided:

`LD_PRELOAD=/nix/store/jbyg9nzcg405qw8byjg5p35fnhkknivz-system-path/lib/VBoxOGL.so glxinfo | grep -i render`

Any ideas how to make this the default using my configuration.nix?

thanks!

**Comment by rehno-lindeque** [comment] 2016-12-23 20:41
I think that #9415 may be somewhat related.

**Comment by rehno-lindeque** [comment] 2016-12-23 22:25
Also #1608 and #5051

**Comment by lovek323** [comment] 2017-03-17 01:44
I'm having the same issue. I can get good output from `glxinfo` in a similar way to @husnoo, but I am not sure where to go from here.

**Comment by rehno-lindeque** [comment] 2017-03-17 21:18
I'd been meaning to submit a PR for this, but unfortunately I'm no longer on VirtualBox.

Last time I tried it this expression in my config worked more or less:

```nix
{ pkgs
, config
, ...
}:

let
  makePackage = p: p.buildEnv {
    name = "mesa+vbox+txc-${p.mesa_drivers.version}";
    paths =
      let version = "5.1.12";
          virtualboxGuestAdditions = p.linuxPackages.virtualboxGuestAdditions.overrideDerivation (oldAttrs: {
              /* src = p.fetchurl { */
              /*   url = "http://download.virtualbox.org/virtualbox/${version}/VBoxGuestAdditions_${version}.iso"; */
              /*   sha256 = "08a3vycj7yw6ihb3myi9yhag1ivpwdl9m5c33viw66lpmdf2d80k"; */
              /* }; */
              buildCommand = lib.traceShowVal oldAttrs.buildCommand +
                ''
                  ln -s $out/lib/VBoxOGL.so $out/lib/libGL.so
                  ln -s $out/lib/VBoxOGL.so $out/lib/libGL.so.1
                  ln -s $out/lib/VBoxOGL.so $out/lib/libGL.so.1.2.0
                  # TODO: in the next version add EGL? 
                  # patchelf --set-rpath ${lib.makeLibraryPath (with p; with p.xorg; [ "$out" dbus libXcomposite libXdamage libXext libXfixes ])} lib/VBoxEGL.so
                  # cp -v lib/VBoxEGL.so $out/lib
                  # ln -s $out/lib/VBoxEGL.so $out/lib/libEGL.so
                  # ln -s $out/lib/VBoxEGL.so $out/lib/libEGL.so.1
                  # ln -s $out/lib/VBoxEGL.so $out/lib/libEGL.so.1.2.0
                '';
            });
      in
        [ virtualboxGuestAdditions # for the DRI driver
          # p.mesa_drivers
          # p.mesa_drivers.out # mainly for libGL # (TODO: replace?)
          (if config.hardware.opengl.s3tcSupport then p.libtxc_dxtn else p.libtxc_dxtn_s2tc)
        ];
  };
in
{
  hardware = {
    opengl = {
      /* FIXME: See https://github.com/NixOS/nixpkgs/issues/5051#issuecomment-64393958 */
      package = makePackage pkgs;
      /* extraPackages = [pkgs.linuxPackages.virtualboxGuestAdditions]; */
    };
  };
}
```

I hope it'll be helpful for someone that wants to submit a proper PR.

**Comment by cgo** [comment] 2017-03-26 22:08
@rehno-lindeque, I am relatively new to nixos, just trying to get it to do what I want for the second time (tried a while ago). When I simply paste your configuration snippet from above in my configuration.nix,
and call nixos-rebuild, it complains that the variable lib is undefined.
Any hint what I am doing wrong? Thanks!

**Comment by vcunat** [comment] 2017-03-27 09:36
@cgo: typically one adds `lib` to the parameter list at the start, but it's also accessible e.g. as `pkgs.stdenv.lib`.

**Comment by vcunat** [comment] 2017-03-27 09:42
BTW, setting `videoDrivers = [ "virtualbox" ];` on the guest nixos config is supposed to do all this automatically.  Now I see this setting is even done by `virtualisation.virtualbox.guest.x11 = true;`   If this doesn't work, it's a bug somewhere in the implementation.  (I've never tested this myself.)

**Comment by rehno-lindeque** [comment] 2017-03-28 03:24
> BTW, setting `videoDrivers = [ "virtualbox" ];` on the guest nixos config is supposed to do all this automatically.

@vcunat @cgo To clarify, the above is a makes use of virtualbox's `VBoxOGL.so` for hardware acceleration. Without this you get software-only rendering for 3D graphics. Never-the-less I wouldn't recommend this ugly hack unless you specifically need it or want to submit a PR.

**Comment by nek0** [comment] 2018-08-25 10:40
any movement on this?

**Comment by flokli** [comment] 2019-05-20 16:11
This should get fixed by https://github.com/NixOS/nixpkgs/pull/60985.

**Comment by ambrop72** [comment] 2019-05-20 17:49
> This should get fixed by #60985.

I don't think so. The problem is that the 3D support in VirtualBox additions relies on programs loading `VBoxOGL.so` in place of `libGL.so`, it (presumably) doesn't play with `libglvnd`. The current additions package doesn't provide the symlinks from `libGL.so` to `VBoxOGL.so` which supposedly fix this issue. Actually, #60985 will make it a bit harder to get this working once `LD_LIBRARY_PATH` no longer contains `/run/opengl-driver/lib` (one could still set it manually though).

But since the Linux 3D support on VirtualBox has a questionable support status and is known to have issues, I would be reluctant to make it enabled automatically even if we support it.

**Comment by flokli** [comment] 2019-05-20 22:32
If virtualbox would support libglvnd, this would have fixed it in a nice way.

But unfortunately you're right. Seems adding libglvnd and/or fixing some of the unstable 3d guest support is very much down on Oracles priority list: https://www.virtualbox.org/pipermail/vbox-dev/2017-June/014561.html

We should probably add some documentation on how to load `VBoxOGL.so` manually, but seems using 3d acceleration from a Linux guest currently isn't really advisable…

**Closed** 2019-05-22 21:36 UTC

**Comment by zarelit** [comment] 2019-05-23 11:18
@flokli @ambrop72  In the last two comments it looked like the #60985 would NOT solve the issue, does this mean that it has been fixed or that this has been closed accidentally?

**Comment by flokli** [comment] 2019-05-23 12:30
@zarelit as explained in the mail linked in my comment, 3d guest support is pretty much broken in virtualbox upstream too, and fixing that is far down on Oracle's priority list:
> In fact, as soon as I get round to it I will disable 3D support for
Fedora guests altogether, as it is not reliable.

On top of that, it's probably not really possible to run it in NixOS either, due to it not supporting libglvnd.

I guess this would need to be fixed upstream first.

I opened https://github.com/NixOS/nixpkgs/pull/61944 which changes virtualboxGuestAdditions to not install VBoxOGL.so, with a comment on why.

**Comment by zarelit** [comment] 2019-05-23 14:38
@flokli  thank you for the clarification on for your work on this!

**Comment by husnoo** [comment] 2019-05-23 14:54
just to clarify, there's a working solution for this, but we're not going to make it easy for ideological reasons? did I understand this right?

**Comment by flokli** [comment] 2019-05-23 15:23
@husnoo The reasons are mostly technical, given even upstream considers their driver to be unstable and are thinking loudly about disabling it entirely.

This *could* be made "easy" by passing in the VBoxOGL driver (together with the required `libGL.so` symlinks) through `hardware.opengl.extraPackages`, behind a `virtualisation.virtualbox.guest.enableHardwareAcceleration` option. I'd be reluctant to unconditionally enable it on `virtualisation.virtualbox.guest.enable` together with the other additions, given its unstable nature (we could flip the default if/when things improve).

I was just assuming there wasn't too much need in supporting that, given nobody stepped up with a PR after [a possible solution was sketched in March 2017](https://github.com/NixOS/nixpkgs/issues/18457#issuecomment-287473821).

I'd be happy to review a PR adding this option, though ;-)
