### ISSUE TITLE
nix-index - not work

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#44996] opened 2018-08-13 20:54 UTC
## Issue description
Error running nix-index
```
nix-index --show-trace
+ querying available packages
error: querying available packages failed
caused by: nix-env failed with error: nix-env failed with exit code 1:
error: while querying the derivation named 'gnome-keyring-0.3.1':
while evaluating the attribute 'buildInputs' of the derivation 'gnome-keyring-0.3.1' at /nix/store/haik8pamsqnpxzkphxqf98njm2jwx625-nixos-18.09pre149049.9968d0f053c/nixos/pkgs/stdenv/generic/make-derivation.nix:175:11:
while evaluating 'getOutput' at /nix/store/haik8pamsqnpxzkphxqf98njm2jwx625-nixos-18.09pre149049.9968d0f053c/nixos/lib/attrsets.nix:451:23, called from undefined position:
while evaluating anonymous function at /nix/store/haik8pamsqnpxzkphxqf98njm2jwx625-nixos-18.09pre149049.9968d0f053c/nixos/pkgs/stdenv/generic/make-derivation.nix:113:17, called from undefined position:
attribute 'gnome-keyring' missing, at /nix/store/haik8pamsqnpxzkphxqf98njm2jwx625-nixos-18.09pre149049.9968d0f053c/nixos/pkgs/development/haskell-modules/hackage-packages.nix:85145:10
```
## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.62, NixOS, 18.09pre149049.9968d0f053c (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1pre6338_45bcf541`
 - channels(root): `"nixos-18.09pre149049.9968d0f053c"`
 - channels(user): `"nixos-18.09pre149002.cfa49751c7f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by xeji** [comment] 2018-08-14 07:38
Looks like this is not an issue with `nix-index`. It seems to be caused by a reference to non-existing `gnome2.gnome-keyring` from `haskellPackages.gnome-keyring` in `pkgs/development/haskell-modules/hackage-packages.nix`.  
@peti @basvandijk

**Comment by peti** [comment] 2018-08-19 07:39
The broken reference is fixed in the `haskell-updates` branch, so this issue will be resolved once we merge that update. Meanwhile, I've committed a quick fix to `master`.

**Closed** 2018-08-19 07:44 UTC
Labels: 6.topic: haskell
