### ISSUE TITLE
Package request: Qt 6

### ISSUE THREAD

**Issue by erikarvstedt** [NixOS/nixpkgs#108008] opened 2020-12-31 01:16 UTC
**Project description**
A cross-platform application framework for C++

**Metadata**
* homepage URL: http://www.qt.io/
* source URL: https://download.qt.io/official_releases/qt/6.0/6.0.0/
* license: GPL, LGPL
* platforms: unix

**Rationale**
Qt 6 is the latest stable release of the popular Qt framework.
Building Qt 6 on nix is surprisingly challenging. Even a WIP PR that fleshes out some basic features (like only qtbase on Linux) would be highly useful for the nix community.

Relevant [discourse thread](https://discourse.nixos.org/t/attempting-to-build-qt6/10551).

cc @ttuegel @qknight @periklis @bkchr

**Comment by berryoda** [comment] 2021-01-22 12:55
I'm would be happy to offer a reward of 300 USD for packaging the following `Qt 6` modules on nixpkgs unstable:
```
Core
GUI
Network
QML
Quick
Quick Controls
Quick Layouts
```
The bounty will be paid in a cryptocurrency of your choice.
If you are a member of [nixpkgs committers](https://github.com/orgs/NixOS/teams/nixpkgs-committers) you will be **paid in advance**. Just reply to this thread with:
- An estimated timeframe
- The address for receiving the payment

**Comment by berryoda** [comment] 2021-01-22 13:19
I would be happy to offer a reward of 300 USD for packaging the following `Qt 6` modules on nixpkgs unstable:
```
Core
GUI
Network
QML
Quick
Quick Controls
Quick Layouts
```
The bounty will be paid in a cryptocurrency of your choice.
If you are a member of [nixpkgs committers](https://github.com/orgs/NixOS/teams/nixpkgs-committers) (or you seem trustworthy in general) you will be **paid in advance**. Just reply to this thread with:
- An estimated timeframe
- The address for receiving the payment
 
cc @ttuegel @qknight @periklis @bkchr @nyanloutre @seqizz

**Comment by berryoda** [comment] 2021-02-02 09:06
I'm raising the `Qt 6` packaging reward to 450 USD, paid in advance.
cc @ttuegel @qknight @periklis @bkchr @nyanloutre @seqizz

**Comment by asdf8dfafjk** [comment] 2021-02-25 17:32
@berryoda Hello, is the bounty still open? How do I contact you?

**Comment by berryoda** [comment] 2021-02-25 18:06
@asdf8dfafjk, yes, it's still open! You can reach me via alue2uoypv@protonmail.com.

**Comment by petabyteboy** [comment] 2021-06-14 05:32
@asdf8dfafjk did you start working on this? Otherwise I would give it a try.

**Comment by berryoda** [comment] 2021-06-14 08:38
@petabyteboy, asdf8dfafjk had a try at it but then got stuck and withdrew.

**Comment by heijligen** [comment] 2021-06-14 09:22
I had packaged something but run out of time. I've published it at https://github.com/heijligen/nixpkgs/commit/c08538de87347c903f6505dbf0b448915c75398a. The nix-support things need a rewrite and a wrapper is also missing. I could run all examples when setting environment variables. I can help but haven't enough nix packaging knowledge to do it alone

**Comment by NickCao** [comment] 2021-07-16 04:17
I was also trying packaging Qt 6, during the process, I found these lines: https://github.com/qt/qtbase/blob/442d367c4084b581fabb9cd2a48ee514a64527f2/cmake/QtBuild.cmake#L19-L38  
Which might hinder it being a multi output derivation.

**Comment by abelianring** [comment] 2021-08-17 01:59
@berryoda I sent you an email!

**Comment by rprospero** [comment] 2021-09-13 11:43
So I was in a situation where I needed to urgently work on a Qt6 project, so I threw together [something](https://gist.github.com/rprospero/dd8e16bad9f842409c85e63ade31c355) that allowed me to at least compile and run Qt6 code.  It's **terrible** (it downloads the pre-built Qt6 binaries and patches them, instead of actually building Qt6), but, if you're in the same situation, it might help you out until some competent comes along and does this properly.

**Comment by sikmir** [comment] 2021-10-02 16:51
Qt 6.2 LTS is out...

**Comment by rnhmjoj** [comment] 2021-10-02 21:35
> Qt 6.2 LTS is out...

The problem here is that there are not enough maintainers: there's not much to do about it.
Qt was updated to 5.15 more than 6 months after the release and was done mostly by a single person.
Updating Qt usually takes a lot of work, a major release will probably require to duplicate all the packages for the 34 modules, updating them and making sure all KDE and general Qt applications continue to work under the new version.

**Comment by Artturin** [comment] 2021-10-03 04:54
place a bounty with gitpay on this issue, that may motivate someone.

**Comment by milahu** [comment] 2021-11-09 17:33
@berryoda ping

**Comment by VergeDX** [comment] 2021-11-20 06:26
Ping @berryoda

**Comment by asdf8dfafjk** [comment] 2021-11-23 04:20
@rprospero I notice your gist as aqtinstall in there but doesn't look like you're using it? I ask because I went down that path as well and used patchelf to rewrite paths but couldn't quite get things to work

**Comment by rprospero** [comment] 2021-11-23 12:54
@asdfasdf You're right that including aqtinstall is a vestigal remains
of an old attempt.  Thank goodness nix is lazy and doesn't compile what
we don't use :-)

What I wound up doing is running aqtinstall on my local machine, seeing
what files it downloaded, and hard coded those URLS into lines 40 and
45.  I probably could have used a variable to hold the specific qt
version so that it would be easier to update, but I was lazy and figured
that I'd have to manually update the hashes anyway.

**Comment by arximboldi** [comment] 2022-01-19 13:01
I am working with a company that would potentially be happy to pay for the work. I think the problem is maybe finding someone with the required expertise. Happy to hear references here?

**Comment by milahu** [comment] 2022-01-19 13:18
@arximboldi see #141883 - some modules are working already

i have (mostly) abandoned the PR, since personally, i dont need qt6

current bottleneck:
nix-build is not incremental, ccache/sccache needs extra work, see https://github.com/mozilla/sccache/issues/1091
... so building `qtwebengine` can be frustrating

**Comment by arximboldi** [comment] 2022-01-25 10:11
Thank you @milahu !

**Comment by milahu** [comment] 2022-01-25 13:28
sure. i can not guarantee a merge into nixpkgs, since my coding style is rather messy ... but it should work

**Comment by Artturin** [comment] 2022-01-25 17:40
Make sure to format the nix files with https://github.com/nix-community/nixpkgs-fmt

**Comment by mvnetbiz** [comment] 2022-05-24 01:10
https://github.com/NixOS/nixpkgs/pull/169296 was merged

**Closed** 2022-05-24 09:05 UTC
Labels: 6.topic: qt/kde, 0.kind: packaging request

**Comment by MasterMind2k** [comment] 2022-11-08 08:23
I'm not sure where to put it, but if anyone needs to use Qt's provided installer, you can use this FHS setup:
```
{ pkgs ? import <nixpkgs> {}, command }:

(pkgs.buildFHSUserEnv {
  name = "Qt6-env";
  targetPkgs = pkgs: (with pkgs;
    [
      cacert
      alsa-lib
      libdrm
      libpulseaudio
      udev
      which
      libglvnd.dev
      libxkbcommon.dev
      nss
      libevdev
      nspr
      expat
      fontconfig
      bzip2
      dbus
      zlib
      glib
      lzma
      freetype
      libkrb5
      gdb
      pkg-config
      gcc
      bintools
      git
      ccache
      clang-tools_14
      # Any additional deps
    ]) ++ (with pkgs.xorg;
    [
      setxkbmap
      libX11.dev
      libXcursor
      libXrandr
      libXext
      libxcb.dev
      xcbutilimage
      xcbutilkeysyms
      xcbutilrenderutil
      xcbutilwm
      libXcomposite
      libXdamage
      libXtst
      libXi
      libXfixes
      libXrender
      libxshmfence
      libxkbfile
      xf86inputevdev
    ]);
  profile = ''
    unset QT_PLUGIN_PATH
    unset QTWEBKIT_PLUGIN_PATH
    unset QML2_IMPORT_PATH
    export QML_DISABLE_DISK_CACHE=1
    export PATH="$HOME/Qt/Tools/QtCreator/bin:$HOME/Qt:$PATH"
  '';
  runScript = command;
}).env
```

Usage:
```
nix-shell <path to nix file above> --argstr command <bash|zsh|qtcreator|MaintainanceTool>
```

Hope it helps anyone.

**Comment by milahu** [comment] 2022-11-08 09:40
> I'm not sure where to put it

you could package this as `qt6-bin` in http://nur.nix-community.org/

**Comment by ben-cottrell-nz** [comment] 2023-07-05 22:52
> 

I'm getting missing modules when I try to build a project with qmake in Qt Creator:
:-1: error: Project ERROR: Unknown module(s) in QT: core gui widgets

**Comment by re1san** [comment] 2024-03-06 15:50
@MasterMind2k I was able to launch Qt online installer and install Qt creator using your FHS (had to add `zstd` in targetPkgs) but after I run the command `nix-shell shell.nix --argstr command qtcreator` I am getting this error :(

```
Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.
```

**Comment by re1san** [comment] 2024-03-06 16:15
@ilya-fedin I get this output 
```
qt.core.plugin.loader: In /home/re1san/Qt/5.15.2/gcc_64/plugins/platforms/libqwayland-xcomposite-glx.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.factoryloader: "The plugin '/home/re1san/Qt/5.15.2/gcc_64/plugins/platforms/libqwayland-xcomposite-glx.so' uses incompatible Qt library. (5.15.0) [release]"
         not a plugin
qt.core.library: "/home/re1san/Qt/Tools/QtCreator/lib/Qt/plugins/platforms/libqxcb.so" cannot load: Cannot load library /home/re1san/Qt/Tools/QtCreator/lib/Qt/plugins/platforms/libqxcb.so: (libxcb-cursor.so.0: cannot open shared object file: No such file or directory)
qt.core.plugin.loader: QLibraryPrivate::loadPlugin failed on "/home/re1san/Qt/Tools/QtCreator/lib/Qt/plugins/platforms/libqxcb.so" : "Cannot load library /home/re1san/Qt/Tools/QtCreator/lib/Qt/plugins/platforms/libqxcb.so: (libxcb-cursor.so.0: cannot open shared object file: No such file or directory)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/re1san/Qt/5.15.2/gcc_64/plugins/platforms" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

**Comment by ilya-fedin** [comment] 2024-03-06 16:19
> libxcb-cursor.so.0: cannot open shared object file: No such file or directory

find this library

**Comment by re1san** [comment] 2024-03-06 16:23
@ilya-fedin Found it! its `xcb-util-cursor`now its working thanks!
