### ISSUE TITLE
macOS: ranlib timestamp resolution bugs break parallel builds?

### ISSUE THREAD

**Issue by endgame** [NixOS/nixpkgs#51221] opened 2018-11-29 10:53 UTC
Continues #51093 .

Background: on macOS, parallel builds of postgres would try to build `libpgtypes.a` multiple times, trip over each other and error out.

On the postgres mailing list, [Tom Lane figured out that](https://www.postgresql.org/message-id/28417.1543458718%40sss.pgh.pa.us):

* APFS has sub-second timestamp resolution
* GNU Make can use sub-second timestamps if the filesystem supports them
* `ranlib` truncates timestamps to the nearest second
  - Thomas Munro [identifies a possible cause](https://www.postgresql.org/message-id/CAEepm%3D3wHjf9ZfekMq5x0qs_r1XBd0YXTrhoZMbmDx-xE8NXwA%40mail.gmail.com)
* Therefore, the `.a` file appears to be built before the `.o` files that comprise it
* Therefore, multiple builds of `libpgtypes.a` are kicked off, trip over each other and error out.

GNU Make has a special target, [`.LOW_RESOLUTION_TIME`](https://www.gnu.org/software/make/manual/html_node/Special-Targets.html), that can be used in this situation.

I won't have time to dig much further on this, but thought I'd log the issue for completeness. Ping @delroth , who wasn't thrilled at the blunt hammer of disabling parallel builds.

**Comment by delroth** [comment] 2018-11-29 10:59
I wonder if we should just patch this in cctools' ranlib (using futimens/utimensat instead of utime when available). This is very broken and I'm guessing could lead to bad parallel builds across all packages.

**Comment by delroth** [comment] 2018-11-29 11:03
Confirmed with a simple repro:

```python
>>> import os
>>> os.utime('test.a', None)
>>> def test():
...   os.utime('test.a', None)
...   t1 = os.stat('test.a').st_mtime
...   os.system('ranlib test.a')
...   t2 = os.stat('test.a').st_mtime
...   return t2 - t1
... 
>>> [test() for i in range(10)]
[-0.8948380947113037, -0.9246668815612793, -0.9467489719390869, -0.959259033203125, -0.9685111045837402, -0.9778580665588379, -0.9862489700317383, 0.0052928924560546875, -0.003030061721801758, -0.011502981185913086]
```

This is pretty ridiculous...

**Comment by endgame** [comment] 2018-11-29 11:15
Yikes. Why doesn't it break more parallel builds? I posted this speculation (about the postgresql bug) to their mailing list:

> This bug seems to be tickled because two different Makefiles use attempt to build the same target at the same time, using a tool (macOS `libtool`/`ranlib`, albeit through a recursive `$(MAKE)` invocation) that doesn't support subsecond timestamps, on a filesystem that does (APFS). That's a bit of a corner case. I speculate that building a static library with a nonrecursive `Makefile` would only kick off one build of the `.a` file, because make will only invoke the command once as it walks the DAG of dependencies.

**Comment by delroth** [comment] 2018-11-29 14:35
Another option: any reason to not use ar/ranlib from binutils instead of using Apple's? I'm not fully aware of the particularities of Darwin so maybe there's an obvious reason why this is impossible. Might be worth giving it a shot.

If it's not possible, patching cctools' ranlib should be pretty easy anyway.

**Comment by matthewbauer** [comment] 2018-11-29 21:38
We don’t use cctools directly from apple but via a fork:

https://github.com/tpoechtrager/cctools-port

If this is causing the issue, i would open a pr there as it will probably effect many more tools!

**Comment by delroth** [comment] 2018-11-29 21:39
The issue is in Apple's upstream code: https://github.com/opensource-apple/cctools/blob/master/misc/libtool.c#L2779

**Comment by matthewbauer** [comment] 2018-11-29 21:42
Yes but i think @tpoechtrager would gladly accept a patch to fix this (at least quicker than apple)

**Comment by delroth** [comment] 2018-11-30 04:03
I've started working on this but right now our build environment targets builds at macOS 10.10, which means utimensat is not available at build time :( Not completely sure how that can be fixed unfortunately, I know close to nothing about macOS.

**Comment by delroth** [comment] 2018-11-30 04:16
Actually thinking more about it we can probably just build cctools-port to target 10.13 (through $MACOSX_DEPLOYMENT_TARGET) -- since the one feature requiring 10.13 (utimensat) in that package is runtime-optional through weak linking, I think the builds will still work on older versions on MacOS. Will need to give it a shot.

**Comment by matthewbauer** [comment] 2018-11-30 04:58
That might be a good reason to up the minimum version. Right now we set 10.11 as the minimum but I am planning to up it to 10.12 with #47678. Maybe bumping all the way to 10.13 wouldn't be that bad of an idea? 10.13 was released just a little over a year ago so it's somewhat of a quick turnaround for us. I would prefer to support up to 2 years back.

You can try it out by adding the symbol to this list:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/darwin/apple-source-releases/Libsystem/system_kernel_symbols

As an alternative, I'm thinking maybe we should just disable nanosecond precision in make? I think you can override it with ```make_cv_file_timestamp_hi_res=no```.

**Comment by alyssais** [comment] 2018-12-14 13:56
https://github.com/tpoechtrager/cctools-port/pull/62 has been merged.

**Comment by endgame** [comment] 2018-12-14 21:33
Thanks for the update @alyssais, and @delroth for making the change. What else need to happen here before this gets closed?

**Comment by matthewbauer** [comment] 2018-12-15 01:33
Let's wait for #51408 to hit master.

**Closed** 2018-12-19 08:12 UTC
Labels: 6.topic: darwin, 9.needs: port to stable
