### ISSUE TITLE
Cannot build LLVM-6 for Android

### ISSUE THREAD

**Issue by nomeata** [NixOS/nixpkgs#56156] opened 2019-02-21 15:48 UTC
## Issue description

With 9b94554008b25d1568b461c717adf44b9fed1d01
```
nix-build -A pkgsCross.aarch64-android-prebuilt.llvm_6
```
yields
```
[100%] Running all regression tests
/nix/store/954lfsfiv9vhrfgq9r7i52aijnzrhidv-python-2.7.15/bin/python2.7 /tmp/nix-build-llvm-6.0.1.drv-0/llvm/build/./bin/llvm-lit -sv /tmp/nix-build-llvm-6.0.1.drv-0/llvm/build/utils/lit /tmp/nix-build-llvm-6.0.1.drv-0/llvm/build/test
llvm-lit: /tmp/nix-build-llvm-6.0.1.drv-0/llvm/build/utils/lit/tests/lit.cfg:61: warning: Could not import psutil. Some tests will be skipped and the --timeout command line argument will not work.
-- Testing: 23291 tests, 8 threads --
Testing: 0 .. 10..
FAIL: LLVM :: CodeGen/AMDGPU/llvm.amdgcn.mbcnt.ll (5120 of 23291)
******************** TEST 'LLVM :: CodeGen/AMDGPU/llvm.amdgcn.mbcnt.ll' FAILED ********************
Script:
--
/tmp/nix-build-llvm-6.0.1.drv-0/llvm/build/bin/llc -march=amdgcn -mcpu=verde -verify-machineinstrs < /tmp/nix-build-llvm-6.0.1.drv-0/llvm/test/CodeGen/AMDGPU/llvm.amdgcn.mbcnt.ll | /tmp/nix-build-llvm-6.0.1.drv-0/llvm/build/bin/FileCheck -check-prefix=GCN -check-prefix=SI /tmp/nix-build-llvm-6.0.1.drv-0/llvm/test/CodeGen/AMDGPU/llvm.amdgcn.mbcnt.ll
/tmp/nix-build-llvm-6.0.1.drv-0/llvm/build/bin/llc -march=amdgcn -mcpu=tonga -verify-machineinstrs < /tmp/nix-build-llvm-6.0.1.drv-0/llvm/test/CodeGen/AMDGPU/llvm.amdgcn.mbcnt.ll | /tmp/nix-build-llvm-6.0.1.drv-0/llvm/build/bin/FileCheck -check-prefix=GCN -check-prefix=VI /tmp/nix-build-llvm-6.0.1.drv-0/llvm/test/CodeGen/AMDGPU/llvm.amdgcn.mbcnt.ll
--
Exit Code: 1

Command Output (stderr):
--
<stdin>:107:40: error: GCN-NOT: string occurred!
 .amd_amdgpu_isa "amdgcn-unknown-linux-android-gfx601"
                                       ^
/tmp/nix-build-llvm-6.0.1.drv-0/llvm/test/CodeGen/AMDGPU/llvm.amdgcn.mbcnt.ll:28:12: note: GCN-NOT: pattern specified here
; GCN-NOT: and
           ^

--

********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90..

1 warning(s) in tests.
Testing Time: 35688.81s
********************
Failing Tests (1):
    LLVM :: CodeGen/AMDGPU/llvm.amdgcn.mbcnt.ll

  Expected Passes    : 22189
  Expected Failures  : 138
  Unsupported Tests  : 963
  Unexpected Failures: 1
make[3]: *** [CMakeFiles/check-all.dir/build.make:58: CMakeFiles/check-all] Error 1
make[3]: Leaving directory '/tmp/nix-build-llvm-6.0.1.drv-0/llvm/build'
make[2]: *** [CMakeFiles/Makefile2:361: CMakeFiles/check-all.dir/all] Error 2
make[2]: Leaving directory '/tmp/nix-build-llvm-6.0.1.drv-0/llvm/build'
make[1]: *** [CMakeFiles/Makefile2:368: CMakeFiles/check-all.dir/rule] Error 2
make[1]: Leaving directory '/tmp/nix-build-llvm-6.0.1.drv-0/llvm/build'
make: *** [Makefile:251: check-all] Error 2
builder for '/nix/store/yf7ybjasq2bp7bf1f717a12zarlvvd34-llvm-6.0.1.drv' failed with exit code 2

```
## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
- system: `"x86_64-linux"`
 - host os: `Linux 4.19.0-2-amd64, Debian GNU/Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
find: '/nix/var/nix/profiles/per-user': No such file or directory
```

This blocks #56121.

**Comment by dtzWill** [comment] 2019-02-23 06:54
LLVM test failures-- the simple fix is to disable tests for at least llvm6 on Android or aarch64 or cross or whichever best captures the set of failing platforms.

More thorough fix:

* Do the LLVM6 tests pass for this platform in any other environment? (Or are they broken/invalid?)
* Why do tests fail, can these failures be ignored or are they indicative of a problem to be investigated?

I'm guessing the problem is just as you reported and not a new regression, LMK if that's incorrect since that of course changes things a bit :).

**Comment by nomeata** [comment] 2019-02-23 11:49
Sorry, I am just getting started with this, so I dunno if this is a regression or if it never worked.

**Comment by dtzWill** [comment] 2019-02-23 17:08
On Sat, 23 Feb 2019 03:49:55 -0800, Joachim Breitner <notifications@github.com> wrote:
> Sorry, I am just getting started with this, so I dunno if this is a regression or if it never worked.

No worries, just trying to make sure we're on the same page :).

And thanks for reporting, this should be fixed one way or another.

I don't have much experience with building things with Android
toolchain, but I wouldn't be surprised if some tests failed for benign
reasons...

Anyone know more about this?

**Comment by nomeata** [comment] 2019-02-24 00:12
Ok, I dug a bit into this, and here is my theory: The test case contains this code:
```
; GCN-LABEL: {{^}}mbcnt_lo_known_bits:
; GCN: v_mbcnt_lo_u32_b32
; GCN-NOT: and
define i32 @mbcnt_lo_known_bits(i32 %x, i32 %y) #0 {
  %lo = call i32 @llvm.amdgcn.mbcnt.lo(i32 %x, i32 %y)
  %mask = and i32 %lo, 63
  ret i32 %mask
}
```
and it checks how this code is compiled, using `GCN`-assertions. In particular, the resulting assembly must not contain the string `and`.

But on android, it contains the string ` .amd_amdgpu_isa "amdgcn-unknown-linux-android-gfx601"` which happens to contain the substring `and`.

So it is an upstream bug with the test suite that gives false negatives when compiling for android. Judging from `big blame`, it was introduced by https://github.com/llvm-mirror/llvm/commit/12d09b0dedd50fdbdc1c5316373a014519420d10.

**Comment by nomeata** [comment] 2019-02-24 00:35
This might be a work-around:
```diff
diff --git a/pkgs/development/compilers/llvm/6/llvm.nix b/pkgs/development/compilers/llvm/6/llvm.nix
index f16f3f72137..bfeeb098afe 100644
--- a/pkgs/development/compilers/llvm/6/llvm.nix
+++ b/pkgs/development/compilers/llvm/6/llvm.nix
@@ -79,6 +79,10 @@ in stdenv.mkDerivation (rec {
     substituteInPlace unittests/Support/CMakeLists.txt \
       --replace "add_subdirectory(DynamicLibrary)" ""
     rm unittests/Support/DynamicLibrary/DynamicLibraryTest.cpp
+  #'' + optionalString (stdenv.hostPlatform.isAarch32 || stdenv.hostPlatform.isAarch64) ''
+  '' + ''
+    echo "Deleting test case that fails when host platform contains \"and\""
+    rm ./test/CodeGen/AMDGPU/llvm.amdgcn.mbcnt.ll
   '';
 
   # hacky fix: created binaries need to be run before installation
```
(The commented out line would be nicer, but somehow did not trigger here, but I am am sure someone more experienced with nix knows what to put there.)

**Closed** 2019-03-02 19:48 UTC
Labels: 0.kind: bug, 6.topic: cross-compilation
