### ISSUE TITLE
gtk+ fails to build on darwin

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nixpkgs#7078] opened 2015-03-30 04:20 UTC
```
configure: error: *** XInput2 extension not found. Check 'config.log' for more details.
```

This is a very new breakage.

**Comment by codyopel** [comment] 2015-03-31 17:39
This is not enough information, What major version of gtk+ are you referring to, 2 or 3 (this probably affects both though).

I believe it is missing libXi, which is the cause for this error (part of xinput), it is only propagated on Linux.  For reference here are the gentoo ebuilds:
http://data.gpo.zugaina.org/gentoo/x11-libs/gtk+/gtk+-3.14.10.ebuild
http://data.gpo.zugaina.org/gentoo/x11-libs/gtk+/gtk+-2.24.27-r1.ebuild

https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/libraries/gtk+/

The ```x11``` build input is an alias for ```xlibsWrapper``` which only pulls in some of the Xorg libraries, it appears to be missing several though including libXi.
https://github.com/NixOS/nixpkgs/blob/146eb665d0fd660260992b7730ddab9af5801239/pkgs/top-level/all-packages.nix#L7745L7751

It may also/alternatively need ```inputproto``` which contains the Xorg-Xinput header files:
http://cgit.freedesktop.org/xorg/proto/inputproto/tree/

@vcunat

**Comment by spwhitt** [comment] 2015-03-31 17:49
@codyopel 

libXi seems to include `X11/extensions/Xfixes.h`, which is missing. Do you happen to know which Xorg library has this header? `inputproto` doesn't seem to help.

Thanks!

**Comment by spwhitt** [comment] 2015-03-31 17:52
Doh! `libXfixes`, obviously.

**Comment by spwhitt** [comment] 2015-04-02 13:53
@jwiegley both gtk and gtk3 now build for me on master, but since Darwin is impure I figure I should ask to you verify the problem is fixed on your end :).

**Comment by henrytill** [comment] 2015-10-30 09:24
What's the latest with this one, @jwiegley?  Could we close?

**Closed** 2015-10-30 18:35 UTC
Labels: bug, darwin

**Comment by Hax4us** [comment] 2017-12-12 11:54
I have same problem what i do ? And i have xinput2.h in x11/extensions
