### ISSUE TITLE
Ungoogled Chromium does not run under Wayland

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#145032] opened 2021-11-08 05:52 UTC
```
% chromium-browser --enable-features=UseOzonePlatform --ozone-platform=wayland
Окно или вкладка откроются в текущем сеансе браузера.
suhr@nixos:~/ > [12272:12272:0100/000000.513475:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is egl, ANGLE is 
[12272:12272:0100/000000.522948:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.77, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - channels(root): `"nixos-21.11pre328987.c935f5e0add"`
 - channels(suhr): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

@squalus

**Comment by emilylange** [comment] 2024-05-01 22:38
Unable to reproduce this under M124.

It's been almost 3 years since this issue has been opened.

Closing, assuming it has been fixed a long time ago.

**Closed by emilylange** 2024-05-01 22:38 UTC
Labels: 0.kind: bug
