### ISSUE TITLE
Clang 4.0.1 cannot compile a C++ file

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#28542] opened 2017-08-24 17:10 UTC
## Issue description

See the title:
```
 nixpkgs git:(master) ✗ result/bin/clang++ test.cpp
test.cpp:1:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
1 error generated.
```

### Steps to reproduce

1. Create a file `test.cpp`:
```
#include <iostream>

int main()
{
  std::cout << "Hello, world!\n";
  return 0;
}
```
2. `clang++ test.cpp`
3. Observe an error.

## Technical details

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) 6e200f264444a7d9c23ce06d8ce2eb4043ba9c68
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`) yes

Notice that `clang_34` works.

**Comment by gebner** [comment] 2017-08-24 17:46
This is a duplicate of #28223.

**Closed by gebner** 2017-08-24 17:46 UTC
Labels: 0.kind: bug
