### ISSUE TITLE
Python: collisions with backports namespace package

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#22319] opened 2017-01-31 15:51 UTC
## Issue description

```
collision between `/nix/store/qr9rrhalxbi1x914xj0hh9y73sfn1p3l-python2.7-backports.ssl_match_hostname-3.5.0.1/lib/python2.7/site-packages/backports/__init__.py' and `/nix/store/lazj5zfz9ysbadlrjwnzj4aa1znff7ff-python2.7-backports.shutil_get_terminal_size-1.0.0/lib/python2.7/site-packages/backports/__init__.py'
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by lheckemann** [comment] 2017-02-01 08:39
What caused this to happen? Can you provide steps to reproduce the issue, and version details, as in the issue template?

**Comment by FRidh** [comment] 2017-02-01 13:59
Looks to be a similar issue as https://github.com/NixOS/nixpkgs/issues/22311 so I am closing this. As @lheckemann said you need to give more details.

**Comment by RonnyPfannschmidt** [comment] 2017-02-01 14:02
@FRidh the issue is different - the problem is setuptools namespace packages generating namespace declaring __init__.py files - now if you merge the file tree of 2 of those, both will have a __init__.py with the same content

**Comment by RonnyPfannschmidt** [comment] 2017-02-01 14:07
```
$ nix-build -E '((import <nixpkgs> {}).python.withPackages (ps: [ps.backports_ssl_match_hostname ps.backports_shutil_get_terminal_size]))'
these derivations will be built:
  /nix/store/cp5p81j8mk94jhjy55q6aip67vld3qxi-python-2.7.13-env.drv
building path(s) ‘/nix/store/wdh53zgsjfcw9zscy6mw9iq01cgwcgsb-python-2.7.13-env’
collision between `/nix/store/qr9rrhalxbi1x914xj0hh9y73sfn1p3l-python2.7-backports.ssl_match_hostname-3.5.0.1/lib/python2.7/site-packages/backports/__init__.py' and `/nix/store/lazj5zfz9ysbadlrjwnzj4aa1znff7ff-python2.7-backports.shutil_get_terminal_size-1.0.0/lib/python2.7/site-packages/backports/__init__.py'
builder for ‘/nix/store/cp5p81j8mk94jhjy55q6aip67vld3qxi-python-2.7.13-env.drv’ failed with exit code 25
error: build of ‘/nix/store/cp5p81j8mk94jhjy55q6aip67vld3qxi-python-2.7.13-env.drv’ failed
```

**Comment by FRidh** [comment] 2017-02-01 16:32
According to [PEP 420](https://www.python.org/dev/peps/pep-0420/#specification) namespace packages shouldn't have an `__init__.py`

**Comment by FRidh** [comment] 2017-02-01 16:35
The `__init__.py` refers to [PEP 382](https://www.python.org/dev/peps/pep-0382/) which was rejected and was eventually replaced by PEP 420. Therefore, this is an upstream issue.

Even so, we can have a look at how to fix it for now.

**Comment by FRidh** [comment] 2017-02-01 16:43
I've reported the issue on the tracker of both packages:
- https://bitbucket.org/brandon/backports.ssl_match_hostname/issues/10/conform-to-pep-420
- https://github.com/chrippa/backports.shutil_get_terminal_size/issues/13

**Comment by RonnyPfannschmidt** [comment] 2017-02-01 18:13
@FRidh pep420 doesn't apply to python2.7 - this is setuptools namespaces that need the file

**Comment by FRidh** [comment] 2017-02-02 09:54
Indeed, you're right. 

I don't see any other solution than using `python.buildEnv.override` and passing `ignoreCollisions = true;`.

**Comment by FRidh** [comment] 2017-02-10 16:44
Closing because there isn't much else we can do here.

**Closed by FRidh** 2017-02-10 16:44 UTC
Labels: 2.status: wontfix, 6.topic: python
