### ISSUE TITLE
It is too easy to feed wrong hash into `fetchpatch`

### ISSUE THREAD

**Issue by Niki4tap** [NixOS/nixpkgs#249641] opened 2023-08-16 22:46 UTC
### Describe the bug
`fetchpatch` is weird. I have produced at least 3 different hashes out of it from the same url, and I'm fairly sure the remote file did not change.

### Steps To Reproduce
In general, just try to use the same patch in a variety of different contexts (I have no idea how this works), and it will produce different hashes.

1. Pray to nix gods

2. Try to reproduce the commands in the screenshot, or

```nix
# In nix repl, try:

:l <nixpkgs>

:b pkgs.fetchpatch {url = "https://dwm.suckless.org/patches/steam/dwm-steam-6.2.diff"; sha256 = "1ld1z3fh6p5f8gr62zknx3axsinraayzxw3rz1qwg73mx2zk5y1f";}

# Should succeed, although the hash for it is from unprocessed patch (nix-prefetch-url)

# Then try:

:b pkgs.dwm.overrideAttrs(oldAttrs: rec {patches = [(pkgs.fetchpatch {url ="https://dwm.suckless.org/patches/steam/dwm-steam-6.2.diff"; sha256 = "1ld1z3fh6p5f8gr62zknx3axsinraayzxw3rz1qwg73mx2zk5y1f";})];})

# Should fail, with mismatched hash on the patch

# Replace the hash and try again:

:b pkgs.dwm.overrideAttrs(oldAttrs: rec {patches = [(pkgs.fetchpatch {url ="https://dwm.suckless.org/patches/steam/dwm-steam-6.2.diff"; sha256 = "sha256-f3lffBjz7+0Khyn9c9orzReoLTqBb/9gVGshYARGdVc=";})];})

# Should succeed, and produce a processed patch

# Try the first step again:

:b pkgs.fetchpatch {url = "https://dwm.suckless.org/patches/steam/dwm-steam-6.2.diff"; sha256 = "1ld1z3fh6p5f8gr62zknx3axsinraayzxw3rz1qwg73mx2zk5y1f";}

# This should fail now, with hash mismatch like the previous
# I have no idea why
```

### Expected behavior
Calls to `fetchpatch` with different `sha256` attribute values and the same `url` should not succeed.

### Screenshots

![image](https://github.com/NixOS/nixpkgs/assets/66798058/8fbb4237-2bed-4500-a4cb-2afd9a616406)

diff from two resulted outputs:
![image](https://github.com/NixOS/nixpkgs/assets/66798058/ad11dd7c-e8ae-475b-ae5a-6d503d217b48)

### Additional context
Sometimes the processing does not get applied, sometimes only some part of processing completes, sometimes it goes through like it should. Absolutely no idea what is happening.

### Notify maintainers

Not sure who really maintains it

@vcunat
@ncfavier
@Artturin

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.24, NixOS, 23.05 (Stoat), 23.05.20230419.645bc49`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(niki4tap): `"nixos-unstable, nixpkgs-unstable"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment] 2023-08-16 23:38
Can't reproduce but 
`:b pkgs.fetchpatch {url = "https://dwm.suckless.org/patches/steam/dwm-steam-6.2.diff"; sha256 = "1ld1z3fh6p5f8gr62zknx3axsinraayzxw3rz1qwg73mx2zk5y1f";}`
works because nix looks at the hash and sees that there's already a file with the same hash and so won't refetch the file and thus there's no hash mismatch.

You have to use fetchpatch to get the correct `fetchpatch` hash for the file.

So there's probably no bug here.

**Comment by Niki4tap** [comment] 2023-08-17 10:05
Thanks for your quick reply, I think I understand what happened now, though if that's the intended behavior, can I somehow force `nix repl` to always evaluate it even if it is already there? As far as I understand this confusion should never happen in real derivations since nix does force evaluate it if it is wrapped in another derivation (like with dwm in reproducer).

And another question is, this might be a bit of a reach though, can other fetchers that wrap `fetchurl` use name prefixes/suffixes so this issue does not happen at all? Again, as far as I understand, changing the name of the output file, changes the path, and so if `fetchpatch` output would contain a suffix like `fetchpatch-...`, nix wouldn't look at the `fetchurl` or `nix-prefetch-url` outputs anymore and would always output the correct information.

Lastly, I'm not sure about this since I didn't look that thoroughly, but is there any documentation about this behavior?

**Comment by Niki4tap** [comment] 2023-08-17 10:10
Also, seems like I'm not the first victim of this confusion, nixpkgs example of dwm patches uses `fetchpatch` with a hash from unprocessed patch, maybe it even works, cannot try right now, but looks like a problem worth solving.

![image](https://github.com/NixOS/nixpkgs/assets/66798058/e874881f-20ec-4c31-adf3-d316ea30b661)

**Comment by ncfavier** [comment] 2023-08-17 10:13
> to always evaluate it even if it is already there

Note that evaluating is not enough, since fixed-output derivations have their hash derived from the *contents* of the built derivation. You'd have to fetch the thing again to know what hash it actually has.

I'm not aware of a Nix option to rebuild every FOD, but you probably don't want that either. [`invalidateFetcherByDrvHash`](https://nixos.org/manual/nixpkgs/unstable/#tester-invalidateFetcherByDrvHash) might be useful.

Some documentation: https://nixos.org/manual/nix/unstable/language/advanced-attributes#adv-attr-outputHash

> nixpkgs example of dwm patches uses `fetchpatch` with a hash from unprocessed patch

How can you tell?

**Comment by Niki4tap** [comment] 2023-08-17 10:54
> Note that evaluating is not enough, since fixed-output derivations have their hash derived from the contents of the built derivation. You'd have to fetch the thing again to know what hash it actually has.

Sorry, that's what I meant

> I'm not aware of a Nix option to rebuild every FOD, but you probably don't want that either.

Maybe not every, but at least one-offs just to test things like this in `nix repl`

> Some documentation: https://nixos.org/manual/nix/unstable/language/advanced-attributes#adv-attr-outputHash

I guess, though I kinda expected something in big red text, mentioning `fetchpatch` and the words "...never ever ever..."

**Comment by vcunat** [comment] 2023-08-17 11:54
I believe these misunderstandings are relatively common.

`nix-build --check` and `nix build --rebuild` are one way of forcing a rebuild of the explicitly specified derivation (but not its dependencies).

**Comment by Niki4tap** [comment] 2023-08-17 12:01
> maybe it even works, cannot try right now

Following derivation builds (`nix-build ./file.nix`), if `nix-prefetch-url --type sha256 https://dwm.suckless.org/patches/steam/dwm-steam-6.2.diff` was executed before running it, otherwise it will fail with hash mismatch.

```nix
{pkgs? import <nixpkgs> {}}:
pkgs.dwm.overrideAttrs (oldAttrs: rec {
  patches = [
    (super.fetchpatch {
      url = "https://dwm.suckless.org/patches/steam/dwm-steam-6.2.diff";
      sha256 = "1ld1z3fh6p5f8gr62zknx3axsinraayzxw3rz1qwg73mx2zk5y1f";
    })
  ];
})
```

**Comment by Niki4tap** [comment] 2023-08-17 12:02
> I believe these misunderstandings are relatively common.

Surely there can be something done to mitigate them? What about my idea with prefixes/suffixes?

**Comment by Niki4tap** [comment] 2023-08-17 13:04
I've changed the title, feel free to remove the bug label and put it as a question instead. I still think that this pitfall is **too** easy to fall into. And I also don't think there are ways to test if the hashes you input into the fetchers are correct or not, unless you go over all FODs manually and rebuild them.

Also the dwm patch example should be fixed, but that's for a different issue I guess.

**Comment by Artturin** [comment] 2023-08-17 19:04
Dupe of https://github.com/NixOS/nixpkgs/issues/48567

**Closed by Artturin** 2023-08-17 19:04 UTC
