### ISSUE TITLE
nixosTests.acme build broken

### ISSUE THREAD

**Issue by ajs124** [NixOS/nixpkgs#197513] opened 2022-10-24 08:43 UTC
### Steps To Reproduce
try to build `nixosTests.acme`

### Build log
https://hydra.nixos.org/log/hv4qwbrhmnxf6h0fq70m8lxy5an0xf89-vm-test-run-acme.drv

### Additional context
does not seem to block the channel, maybe it should

### Notify maintainers
@NixOS/acme

**Comment by m1cr0man** [comment] 2022-10-24 09:22
Weird, seems to be caused by some syscall blocking, likely from [this change](https://github.com/NixOS/nixpkgs/pull/191861/files#diff-f72bfee4e4288266759893ea9ae9b14380c9169157e61dae1a35132757b387e0R328). I had no problem with the test suite at the time however. Both lego and minica are having issues. Will investigate further.

**Comment by arianvp** [comment] 2022-10-24 11:27
> does not seem to block the channel, maybe it should

Agreed to add this test suite to the list of channel blockers.

**Comment by mweinelt** [comment] 2022-10-24 12:46
Duplicate of https://github.com/NixOS/nixpkgs/issues/197443

**Comment by zowoq** [comment] 2022-10-24 21:14
Odd that the test is failing on master with x86_64 and passes with aarch64.

**Closed** 2022-10-24 21:22 UTC
Labels: 0.kind: build failure
