### ISSUE TITLE
keyd (a key remapping daemon for linux)

### ISSUE THREAD

**Issue by augustebaum** [NixOS/nixpkgs#144812] opened 2021-11-05 23:09 UTC
**Project description**
`keyd` provides a flexible system wide daemon which remaps keys using kernel level input primitives (`evdev`, `uinput`).

**Metadata**
* source URL: https://github.com/rvaiya/keyd
* license: MIT
* platforms: Linux

**Comment by figsoda** [comment] 2021-11-05 23:24
duplicate of #132474

**Closed by figsoda** 2021-11-05 23:24 UTC
Labels: 0.kind: packaging request
