### ISSUE TITLE
Night color is broken after updated to plasma 5.21

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#117036] opened 2021-03-20 15:10 UTC
**Describe the bug**
Night color cannot be enabled and it shows an error message "Failed to connect to the Window Manager" on the settings panel.

**To Reproduce**
1. enable plasma and use kwin as the window manager (default)
2. open settings -> Display and Monitor -> Night Color

**Expected behavior**
Night color should work

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.7, NixOS, 21.05.20210319.f5e8bdd (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210317_8a5203d`
 - channels(root): `""`
 - nixpkgs: `/nix/store/mz372xs1z8r6b3337zs0qxkg0ffrbnn3-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by andrevmatos** [comment] 2021-05-18 21:49
This is caused by the lack of `lcms2` on kwin's `buildInputs` in order for cmake to build the `nightcolor` plugin. The dependencies for the krunner plugin is also missing. I have this overlay on my system which solves both bugs:
```nix
final: prev: {
  plasma5Packages = prev.plasma5Packages // {
    plasma5 = prev.plasma5Packages.plasma5 // {
      kwin = prev.plasma5Packages.plasma5.kwin.overrideAttrs (
        old: {
          buildInputs = (old.buildInputs or [ ]) ++ [ prev.lcms2 prev.plasma5Packages.krunner ];
        }
      );
    };
  };
}
```

**Comment by tim-hilt** [comment] 2021-05-19 08:37
Can confirm; the overlay works for me 👍

**Comment by mdevlamynck** [comment] 2021-05-19 08:45
PR? :pray:

**Comment by tim-hilt** [comment] 2021-05-19 09:31
In the process, but I don't know, how I could specify `plasma5Packages.krunner` as a dependency (First PR and Nix Newbie 😄 )

**Comment by mdevlamynck** [comment] 2021-05-19 10:51
In most case you want to target master and maybe backport the change to the current release after (you can find some informations about that in https://github.com/NixOS/nixpkgs#contributing and https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

After a quick search some other package use `krunner` directly (like `kdeplasma-addons` and `kdevelop`) so something like that should work (at least it builds on my machine, I haven't been able to test it yet): 
```diff --git a/pkgs/desktops/plasma-5/kwin/default.nix b/pkgs/desktops/plasma-5/kwin/default.nix
index 2008529a38b..ad5d4e3cfbf 100644
--- a/pkgs/desktops/plasma-5/kwin/default.nix
+++ b/pkgs/desktops/plasma-5/kwin/default.nix
@@ -12,7 +12,7 @@
   kcoreaddons, kcrash, kdeclarative, kdecoration, kglobalaccel, ki18n,
   kiconthemes, kidletime, kinit, kio, knewstuff, knotifications, kpackage,
   kscreenlocker, kservice, kwayland, kwayland-server, kwidgetsaddons, kwindowsystem, kxmlgui,
-  plasma-framework, libcap, libdrm, mesa, pipewire
+  plasma-framework, libcap, libdrm, mesa, pipewire, lcms2, krunner
 }:
 
 # TODO (ttuegel): investigate qmlplugindump failure
@@ -31,7 +31,7 @@ mkDerivation {
     kcoreaddons kcrash kdeclarative kdecoration kglobalaccel ki18n kiconthemes
     kidletime kinit kio knewstuff knotifications kpackage kscreenlocker kservice
     kwayland kwayland-server kwidgetsaddons kwindowsystem kxmlgui plasma-framework
-    libcap libdrm mesa pipewire
+    libcap libdrm mesa pipewire lcms2 krunner
   ];
   outputs = [ "dev" "out" ];
   patches = [
```

@andrevmatos What does the kwin plugin for krunner do? I can't find any information about it.

**Comment by tim-hilt** [comment] 2021-05-19 11:17
I'm currently not able to test the changes on my nixpkgs-fork. Would a PR still be a valid option or should I first test extensively?

**Comment by mdevlamynck** [comment] 2021-05-19 11:22
Well making sure the PR actually fixes the issue is kind of needed. I'll make the PR if I can test it. Feel free to do it if you can test it first :)

**Comment by tim-hilt** [comment] 2021-05-19 11:52
Thanks for all the information you've given! I think I'll contribute a bit later, when I have more time to get into all this stuff.

**Comment by mdevlamynck** [comment] 2021-05-20 07:38
Seems to be already fixed on `staging`.

**Comment by mdevlamynck** [comment] 2021-05-21 06:11
I think it's part of https://github.com/NixOS/nixpkgs/pull/123279.

**Comment by andrevmatos** [comment] 2021-05-21 09:54
`krunner` plugin for `kwin` is what allows krunner to search for open windows and select them. If kwin isn't compiled with krunner, this funcitonality doesn't work.

**Comment by solson** [comment] 2021-05-25 19:44
This is fixed for me in the latest `nixos-unstable.`

**Comment by andrevmatos** [comment] 2021-05-25 22:45
I can confirm it's fixed on current unstable. This issue can be closed.

**Closed** 2021-05-26 04:38 UTC
Labels: 0.kind: bug, 6.topic: qt/kde
