### ISSUE TITLE
Build failure: mindustry

### ISSUE THREAD

**Issue by zeuner** [NixOS/nixpkgs#304185] opened 2024-04-15 05:39 UTC
### Steps To Reproduce

1. build `mindustry`

### Build log

```
<-------------> 0% CONFIGURING [17s]> root project > Resolve dependencies of :classpath > guava-29.0-jre.pom > 1.3 > root project > Resolve dependencies of :classpath > kotlin-compiler-embeddabl> root project > Resolve dependencies of :classpath > kotlin-util-klib-1.6.0.po> root project > Resolve dependencies of :classpath > semver4j-0.16.4.pom> root project > Resolve dependencies of :classpath > kotlin-compiler-runner-1.> root project > Resolve dependencies of :classpath > guava-parent-29.0-jre.pom> IDLE> IDLE> IDLE> root project > Resolve dependencies of :classpath> root project > Resolve dependencies of :classpath > gson-parent-2.8.6.pom > 4> root project > Resolve dependencies of :classpath> root project > Resolve dependencies of :classpath > error_prone_annotations-2> root project > Resolve dependencies of :classpath > jsr305-3.0.2.pom> root project > Resolve dependencies of :classpath > checker-qual-2.11.1.pom> root project > Resolve dependencies of :classpath > j2objc-annotations-1.3.po> IDLE> IDLE> IDLE> root project > Resolve dependencies of :classpath> root project > Resolve dependencies of :classpath > oss-parent-9.pom<-------------> 0% CONFIGURING [18s]> root project > Resolve dependencies of :classpath > kotlin-daemon-embeddable-> root project > Resolve dependencies of :classpath > trove4j-1.0.20181211.pom> root project > Resolve dependencies of :classpath > jna-5.6.0.pom> root project > Resolve dependencies of :classpath > kotlin-build-common-1.6.0> root project > Resolve dependencies of :classpath > kotlinx-coroutines-core-j> root project > Resolve dependencies of :classpath > kotlin-daemon-client-1.6.> IDLE> IDLE> root project > Resolve dependencies of :classpath<-------------> 3% CONFIGURING [18s]> IDLE
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Mindustry'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.github.Anuken.Arc:packer:152e49944a.
     Searched in the following locations:
       - file:/var/empty/.m2/repository/com/github/Anuken/Arc/packer/152e49944a/packer-152e49944a.pom
       - https://repo.maven.apache.org/maven2/com/github/Anuken/Arc/packer/152e49944a/packer-152e49944a.pom
       - https://dl.google.com/dl/android/maven2/com/github/Anuken/Arc/packer/152e49944a/packer-152e49944a.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/github/Anuken/Arc/packer/152e49944a/packer-152e49944a.pom
       - https://jitpack.io/com/github/Anuken/Arc/packer/152e49944a/packer-152e49944a.pom
       - https://plugins.gradle.org/m2/com/github/Anuken/Arc/packer/152e49944a/packer-152e49944a.pom
     Required by:
         project :
   > Could not find com.github.Anuken.Arc:arc-core:152e49944a.
     Searched in the following locations:
       - file:/var/empty/.m2/repository/com/github/Anuken/Arc/arc-core/152e49944a/arc-core-152e49944a.pom
       - https://repo.maven.apache.org/maven2/com/github/Anuken/Arc/arc-core/152e49944a/arc-core-152e49944a.pom
       - https://dl.google.com/dl/android/maven2/com/github/Anuken/Arc/arc-core/152e49944a/arc-core-152e49944a.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/github/Anuken/Arc/arc-core/152e49944a/arc-core-152e49944a.pom
       - https://jitpack.io/com/github/Anuken/Arc/arc-core/152e49944a/arc-core-152e49944a.pom
       - https://plugins.gradle.org/m2/com/github/Anuken/Arc/arc-core/152e49944a/arc-core-152e49944a.pom
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 28s
```

### Additional context

Similar errors encountered on different hosts.

### Notify maintainers

Will do.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-101-generic, Ubuntu, 22.04.3 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MIvanchev** [comment] 2024-04-15 15:22
I get this for the Void Linux package as well, see https://github.com/Anuken/Mindustry/issues/7764#issuecomment-1762633812, I think it's relevant.

**Comment by SuperSandro2000** [comment] 2024-06-29 14:13
Probably a dupe of #278518

**Closed by SuperSandro2000** 2024-06-29 14:13 UTC
Labels: 0.kind: build failure

**Comment by zeuner** [comment] 2024-06-30 22:40
> Probably a dupe of #278518

Did you verify that https://github.com/NixOS/nixpkgs/issues/278518 fixes it? The issue does seem to include some instructions for Gradle-based projects, but these seem to be only targeted at projects written in Groovy or Kotlin.

It can be worked around by updating the `archash=` line in `gradle.properties`.

**Comment by ARC4991** [comment] 2024-08-12 16:11
You can try to access [this](https://maven.xpdustry.com/) website and downloading these jar files(freetype-v146.jar,flabel-v146.jar,arc-core-v146.jar,packer-v146.jar,arcnet-v146.jar,fx-v146.jar,g3d-v146.jar)

Finally, you need to modify file build.gradle
<img width="483" alt="截屏2024-08-13 00 10 34" src="https://github.com/user-attachments/assets/b5c1a9e3-1e3d-4041-b2dc-a7003af7f9fb">
<img width="428" alt="截屏2024-08-13 00 09 26" src="https://github.com/user-attachments/assets/134f976f-2cfc-4770-9eb2-219d6bb36ec6">
<img width="453" alt="截屏2024-08-13 00 09 02" src="https://github.com/user-attachments/assets/d154f609-7a0a-4333-904e-7431b0986387">
