### ISSUE TITLE
Package webapp-manager

### ISSUE THREAD

**Issue by StephanJ91** [NixOS/nixpkgs#239218] opened 2023-06-22 15:29 UTC
Run websites as if they were apps.

Utility to run websites as apps.

**Metadata**

* homepage URL: https://github.com/linuxmint/webapp-manager
* source URL: https://github.com/linuxmint/webapp-manager
* license: gplv3
* platforms: linux

**Comment by pinn3** [comment] 2023-06-22 16:29
Duplicate of https://github.com/NixOS/nixpkgs/issues/212089 and https://github.com/NixOS/nixpkgs/issues/217927

**Comment by das-g** [comment] 2023-10-24 12:25
Closing as duplicate of #212089.

**Closed by das-g** 2023-10-24 12:25 UTC
Labels: 0.kind: packaging request
