### ISSUE TITLE
Rstudio fail to start (correctly)

### ISSUE THREAD

**Issue by adfaure** [NixOS/nixpkgs#30118] opened 2017-10-05 08:52 UTC
## Issue description
Hi, I try to use Rstudio from nix.
The installation does not crash. Howerver, rstudio cannot be launch correctly.
```
[nix-shell:~/Projects/environments/nix]$ rstudio
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
"TypeError: undefined is not an object (evaluating 'window.desktopHooks.notifyRCrashed')"
```

### Steps to reproduce

I used nix-shell with the following default:
 
```nix
{
  pkgs ? import <nixpkgs> {},
}:
let
  callPackage = pkgs.lib.callPackageWith (pkgs // pkgs.xlibs // self);
  self = rec {
   jupyter_env=pkgs.stdenv.mkDerivation {
        name = "expe";
        propagatedBuildInputs =
        [
          pkgs.python36
          pkgs.python36Packages.jupyter
          pkgs.python36Packages.pyqt5
          pkgs.python36Packages.pandas
          pkgs.python36Packages.docopt
          pkgs.python36Packages.matplotlib
          pkgs.python36Packages.pip
          pkgs.rstudio # Rstudio is here
        ];
      };
  };

in
  self
```
## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
```
[adfaure@adchire ~]$ lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```

* Nix version: (run `nix-env --version`)
```
[adfaure@adchire ~]$ nix-env --version
nix-env (Nix) 1.11.13
```

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion)
```
[adfaure@adchire ~]$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.09.1502.19879836d1"
```
However I had the same issue with unstable.

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
```
[adfaure@adchire ~]$ grep build-use-sandbox /etc/nix/nix.conf
grep: /etc/nix/nix.conf: No such file or directory
```

**Comment by FRidh** [comment] 2017-10-06 19:36
Duplicate of https://github.com/NixOS/nixpkgs/issues/9415.

**Closed by FRidh** 2017-10-06 19:36 UTC
