### ISSUE TITLE
How to make services wait on network to be up? (and other sequencing problems)

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#13944] opened 2016-03-15 20:51 UTC
I'm trying to create a nixops example that demonstrates deploying Kubernetes to a cloud provider. (namely to Azure via the new backend being added).

I have it nearly working now (nearly, due to what looks like a docker 1.10 bug), but I've had to do a lot of hacking. I've created this snippet: `routewait = ''while true; do i=\"$(${pkgs.iproute}/sbin/ip route show default)\" ; if [[ ! -z \"$i\" ]]; then break; ${pkgs.coreutils}/bin/sleep 1; fi; done;'';` and I inject it as an `ExecStartPre` for the systemd units for `docker`, `kube-apiserver`, `flannel`, and others. This because the existing targets/services related to the network don't seem to work in NixOS.

Not only that, but I simply can't seem to get `docker` to actually wait for `flannel` to come up, so I've had to do even more weird things so that `docker` doesn't fail after too many restarts, while `flannel` waits for the network to be up. (I've had to do similar things with `flannel` and `etcd`). This is despite having flannel configured with `wantedBy = [ "multi-user.target" "docker.target" ]` and `requiredBy = [ "docker.target" ]` which in my mind should cause `docker` to wait on `flannel`.

(For context, I also disabled socket activation for docker. That's a cheat and I need docker up asap)
1. Is there a way to make `network.target` or better, `network-interfaces.target`/`network-setup.service` to work properly? IE: wait for the network to be fully setup?
2. Am I using systemd wrong, or why does my `flannel` service not cause the `docker` service to wait.

**Comment by copumpkin** [comment] 2016-03-15 21:08
It's not clear to me from what you write above what the issue is with just having your service depend on `network.target`. I assume that since you mention it, something went wrong when you tried it, but I don't know what.

**Comment by colemickens** [comment] 2016-03-15 21:16
It just flat out doesn't wait for anything. Using the snippet above, with a modification, you can clearly see services starting up before the default route is set, regardless of what `network*{target,service}` you attempt to wait on.

I was told that this is a known issue in NixOS by `kmicu` on `#nixos`.

**Comment by colemickens** [comment] 2016-03-15 21:17
You can see my latest attempt here: https://github.com/colemickens/nixpkgs/blob/cmpkgs-azure/nixos/modules/services/networking/flannel.nix#L57

Despite what's listed, the only thing that prevents flannel from starting too early is the `routewait` trick I have in place.

**Comment by joelmo** [comment] 2016-03-17 12:57
This article describes network-online.target and explains how to run a service that requires connection to Internet: https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/. I recommend looking at what NetworkManager-wait-online.service does.

**Comment by colemickens** [comment] 2016-03-17 17:48
As you can see, I've tried adding those targets and they don't do the right thing. The implication of that article is that you must use `network.target` with a `wait-online.service`, but it also implies that just `network-online.target` should be sufficient.... and it's not.

**Comment by joelmo** [comment] 2016-03-17 18:27
> network-online.target is a target that actively waits until the nework is "up", where the definition of "up" is defined by the network management software. 

I suppose network-online at minimum is that one interface have been configured for Ethernet access.

The definition of these network targets seems to be very loose so I don't know where it implied having network-online.target would be sufficient.

I think the ExecStartPre script you wrote should work, but I would try to move this into a separate service so that should be similar to how NetworkManager-wait-online works.

**Comment by grahamc** [comment] 2016-03-25 01:10
For reference, when kmico says it is incorrectly implemented: https://botbot.me/freenode/nixos/2016-03-15/?msg=62198142&page=3

**Comment by grahamc** [comment] 2016-03-25 01:32
Have you tried looking at how other distros do it in their systemd units? Theirs seem quite a bit simpler compared to yours.

CoreOS seems to just have dependent containers depend on flannel: https://coreos.com/flannel/docs/latest/flannel-config.html

DigitalOcean seems to add a bit more: https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-kubernetes-on-top-of-a-coreos-cluster with 
```
Requires=etcd.service
After=etcd.service
```

and 

```
[Install]
WantedBy=multi-user.target
```


CentOS seems to take advantage of notification:

```
[Unit]
Description=Flanneld overlay address etcd agent
After=network.target
After=network-online.target
Wants=network-online.target
After=etcd.service
Before=docker.service

[Service]
Type=notify
EnvironmentFile=/etc/sysconfig/flanneld
EnvironmentFile=-/etc/sysconfig/docker-network
ExecStart=/usr/bin/flanneld -etcd-endpoints=${FLANNEL_ETCD} -etcd-prefix=${FLANNEL_ETCD_KEY} $FLANNEL_OPTIONS
ExecStartPost=/usr/libexec/flannel/mk-docker-opts.sh -k DOCKER_NETWORK_OPTIONS -d /run/flannel/docker
Restart=on-failure

[Install]
WantedBy=multi-user.target
RequiredBy=docker.service
```

and have a patch to notify systemd:

```patch
From c623d5666ef076de1b79c7b86d72a9d68847f672 Mon Sep 17 00:00:00 2001
From: Jan Chaloupka <jchaloup@redhat.com>
Date: Wed, 23 Sep 2015 09:40:46 +0200
Subject: [PATCH] Notify systemd service when server is ready to listen

---
 remote/server.go | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/remote/server.go b/remote/server.go
index a39f80c..6d6fb05 100644
--- a/remote/server.go
+++ b/remote/server.go
@@ -26,6 +26,7 @@ import (
 
 	"github.com/coreos/flannel/Godeps/_workspace/src/github.com/coreos/etcd/pkg/transport"
 	"github.com/coreos/flannel/Godeps/_workspace/src/github.com/coreos/go-systemd/activation"
+	"github.com/coreos/flannel/Godeps/_workspace/src/github.com/coreos/go-systemd/daemon"
 	log "github.com/coreos/flannel/Godeps/_workspace/src/github.com/golang/glog"
 	"github.com/coreos/flannel/Godeps/_workspace/src/github.com/gorilla/mux"
 	"github.com/coreos/flannel/Godeps/_workspace/src/golang.org/x/net/context"
@@ -276,6 +277,8 @@ func RunServer(ctx context.Context, sm subnet.Manager, listenAddr, cafile, certf
 		c <- http.Serve(l, httpLogger(r))
 	}()
 
+	daemon.SdNotify("READY=1")
+
 	select {
 	case <-ctx.Done():
 		l.Close()
-- 
1.9.3
```

Note you can explore these files by downloading https://rpmfind.net/linux/RPM/centos/extras/7.2.1511/x86_64/Packages/flannel-0.5.3-9.el7.x86_64.html and use `nix-shell -p rpmextract`.

**Comment by fpletz** [comment] 2017-02-23 15:10
Networkd activates `network-online.target` correctly. With 66f553974b74378c524f08b3c7d745907927e6c4 on master it also works with dhcpcd.

As `network-online.target` now works as expected for all use cases we can close this.

**Closed by fpletz** 2017-02-23 15:10 UTC
