### ISSUE TITLE
[Steam] Dota fails to launch after Jan 31 update

### ISSUE THREAD

**Issue by tgharib** [NixOS/nixpkgs#157614] opened 2022-02-01 00:19 UTC
### Describe the bug
When launching dota from steam, it errors out with an error about `libpangoft`.

Dota was working yesterday. It broke today (Jan 31) after an update. I believe the update switched the game to use the soldier runtime (which runs the game inside a container). Before, I believe dota was running uncontainerized.

I filed a bug report on the dota tracker: https://github.com/ValveSoftware/Dota-2/issues/2018

### Steps To Reproduce
1. Launch steam
2. Launch dota

### Expected behavior
The game to launch.

### Screenshots
![screenshot](https://user-images.githubusercontent.com/6457015/151892698-35fa063c-9922-416d-9b90-2732e3d8099c.png)

### Additional context
Steam installed through `programs.steam.enable = true;`.

### Notify maintainers
@jagajaga @jonringer

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix > nix-info -m
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «string»:1:9:

            1| (import <nixpkgs> {}).stdenv.hostPlatform.system
             |         ^
 - system: `0`
 - host os: `Linux 5.10.93, NixOS, 21.11 (Porcupine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.0pre20211206_d1aaa7e`
 - channels(root): `""`
 - channels(owner): `""`
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «string»:1:1:

            1| <nixpkgs>
             | ^
 - nixpkgs: `0`
```

**Comment by jonringer** [comment] 2022-02-01 00:49
needs `gnome2.pango`

**Comment by tgharib** [comment] 2022-02-01 01:01
@jonringer Adding `gnome2.pango` might fix the symptom but since the game is running in a steam runtime container, it shouldn't need any additional dependencies on top of steam. It appears the container is leaking? According to this [person running non-nixos distro](https://github.com/ValveSoftware/Dota-2/issues/2018#issuecomment-1026358565), they only get the `libpangoft` error when running `dota.sh` outside of steam.

**Comment by jonringer** [comment] 2022-02-01 01:05
right now, we use `LD_LIBRARY_PATH` to make steam happy. However, it's a big hammer.

**Comment by jonringer** [comment] 2022-02-01 01:07
I tried removing `LD_LIBRARY_PATH` in https://github.com/NixOS/nixpkgs/pull/157621

**Comment by tgharib** [comment] 2022-02-01 01:12
In the meantime, I can confirm dota works in the flatpak version of steam.

**Comment by jonringer** [comment] 2022-02-01 01:15
> In the meantime, I can confirm dota works in the flatpak version of steam.

since nix also has to do a chroot-like operation, the performance implications are probably similar

**Comment by tgharib** [comment] 2022-02-01 01:32
It is even worth the time to bother with steam in nixpkgs? Steam appears to be an endless time-sink, especially when the flatpak works. Is there any advantage to nixpkgs steam over the flatpak?

**Comment by jonringer** [comment] 2022-02-01 01:45
> It is even worth the time to bother with steam in nixpkgs? Steam appears to be an endless time-sink, especially when the flatpak works. Is there any advantage to nixpkgs steam over the flatpak?

We would need data. But my guess is that the difference would be minimal. I would almost be in favor of just wrapping `steam` into a script which launches flatpak

**Comment by L-as** [comment] 2022-02-01 14:15
The flatpak one has limitations because you can't use bwrap inside flatpak IIRC. Not sure though.

**Comment by tgharib** [comment] 2022-02-01 14:30
> The flatpak one has limitations because you can't use bwrap inside flatpak IIRC. Not sure though.

That should no longer be an issue. See https://github.com/flatpak/flatpak/issues/3797

**Comment by Masda-X** [comment] 2022-02-01 19:26
Same issue on Linux Lite and Linux Mint. After the latest update can not run Dota 2. Tried with flatpak on both did not work as well.

**Comment by tgharib** [comment] 2022-02-01 19:34
> Same issue on Linux Lite and Linux Mint. After the latest update can not run Dota 2. Tried with flatpak on both did not work as well.

This github thread is for nixos only. I recommend pointing this out at https://github.com/ValveSoftware/Dota-2/issues/2018 since Valve only reads that thread.

**Comment by tgharib** [comment] 2022-02-01 23:46
@jonringer This comment from [TTimo was enlightening](https://github.com/ValveSoftware/Dota-2/issues/2018#issuecomment-1027329596). It appears the error message that dota throws completely buries the lede. The bug is actually Valve's bug. Dota is configured to use Steam Play but it is a native game and thus throws the error. After disabling Steam Play in Steam settings, dota works fine on nixos's steam.

So why didn't I get this bug when I ran Steam in Flatpak? Because I didn't have `~/.var/app/com.valvesoftware.Steam`, Steam created new dot files. With fresh dot files, Steam prompts you to enable or disable Steam play on first launch, which I instinctively disabled since I know dota is a native game and I only wanted to test dota. Since my nixos Steam uses old dot files with games that require Steam Play, I did not get this prompt since it was not fresh launch. It didn't occur to me to disable Steam play and I apologize for wasting people's time beacuse of that. Perhaps it might be wise to add a requirement to delete `~/.local/share/Steam` for future bug reports.

**Comment by tgharib** [comment] 2022-02-02 14:57
[For context, please read this first.](https://github.com/ValveSoftware/Dota-2/issues/2018#issuecomment-1027926586) I did some testing (I double checked once) and I arrived at the following results:

|                        | With Steam Linux Runtime | Without Steam Linux Runtime |
|------------------------|--------------------------|-----------------------------|
| NixOS Floating Point   | Works                    | Works                       |
| NixOS Dota 2           | libpangoft error         | Works                       |
| Flatpak Floating Point | Works                    | Works                       |
| Flatpak Dota 2         | Works                    | Works                       |

**Comment by sorpaas** [comment] 2022-03-21 16:39
> We would need data. But my guess is that the difference would be minimal. I would almost be in favor of just wrapping steam into a script which launches flatpak

I really hope we don't end up removing FHS Steam.

There are still a lot of edge cases where FHS Steam works much better than Flatpak Steam, simply because the former can be declarative customized via `extraPkgs`. For example, at this moment, Rimworld cannot display Chinese fonts on Flatpak Steam, even using ugly fixes mentioned in Arch wiki or https://github.com/NixOS/nixpkgs/issues/119433. Problems like this do not exist on FHS Steam.

**Comment by Atemu** [comment] 2022-11-13 06:35
There are not plans to remove our Steam derivation.

Are you still able to reproduce this issue on 22.05 and/or 22.11?

**Comment by SuperSamus** [comment] 2022-11-13 10:21
I have no problems launching Dota on 22.11.

**Comment by Atemu** [comment] 2022-11-13 12:33
Guess it's been fixed in the mean time then.

**Closed by Atemu** 2022-11-13 12:33 UTC
Labels: 0.kind: bug, 6.topic: steam
