### ISSUE TITLE
Package request: 2ship2harkinian

### ISSUE THREAD

**Issue by shuniki** [NixOS/nixpkgs#316474] opened 2024-06-01 17:45 UTC
**Project description**
 Ship of harkinian (known as shipwright on github) and its sequel, 2ship2harkinian, are two apps that can perfectly recreate Ocarina of Time and Majora's Mask respectively. Both run natively in Linux and installing them on NixOS works out of the box. 2ship2harkinian is also on it's second stable version, 1.0.1, and the project gets tons of issues on git that are quickly patched. Overall, it needs to be added to the nix repo out of quality of life and easy access reasons.

**Metadata**

* homepage URL: https://www.shipofharkinian.com/
* source URL: https://github.com/HarbourMasters/2ship2harkinian/releases
* license: Ship of Harkinian team, otherwise license isn't fully known personally
* platforms: unix, linux, windows, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment] 2024-06-01 18:17
Duplicate of https://github.com/NixOS/nixpkgs/issues/316326

**Comment by chewblacka** [comment] 2024-06-01 18:38
Closing as duplicate

**Closed by chewblacka** 2024-06-01 18:38 UTC
Labels: 0.kind: packaging request
