### ISSUE TITLE
OpenCV contrib python build fails

### ISSUE THREAD

**Issue by alexozer** [NixOS/nixpkgs#26304] opened 2017-06-01 18:58 UTC
## Issue description
The OpenCV Python 3 package fails to build with `enableContrib = true` enabled right at 100% completion.

```
[100%] Building CXX object modules/stitching/CMakeFiles/opencv_perf_stitching.dir/perf/perf_matchers.cpp.o
[100%] Linking CXX executable ../../bin/opencv_test_structured_light
[100%] Built target opencv_test_structured_light
[100%] Building CXX object modules/stitching/CMakeFiles/opencv_perf_stitching.dir/perf/perf_stich.cpp.o
Traceback (most recent call last):
  File "/tmp/nix-build-opencv-3.2.0.drv-0/opencv-3.2.0-src/modules/python/python3/..//src2/gen2.py", line 959, in <module>
    generator.gen(srcfiles, dstdir)
  File "/tmp/nix-build-opencv-3.2.0.drv-0/opencv-3.2.0-src/modules/python/python3/..//src2/gen2.py", line 871, in gen
    self.code_include.write( '#include "{0}"\n'.format(hdr[hdr.rindex('opencv2/'):]) )
ValueError: substring not found
make[2]: *** [modules/python3/CMakeFiles/opencv_python3.dir/build.make:312: modules/python3/pyopencv_generated_include.h] Error 1
make[1]: *** [CMakeFiles/Makefile2:13931: modules/python3/CMakeFiles/opencv_python3.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable ../../bin/opencv_perf_stitching
[100%] Built target opencv_perf_stitching
make: *** [Makefile:161: all] Error 2
builder for ‘/nix/store/cab110mn70l7aca7b7i33jbwl7bl1hjd-opencv-3.2.0.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/cbb980gscpxzwnyv1s9v7rlfaa9y1fq0-python3-3.5.3-env.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/cbb980gscpxzwnyv1s9v7rlfaa9y1fq0-python3-3.5.3-env.drv’ failed
/run/current-system/sw/bin/nix-shell: failed to build all dependencies
```

### Steps to reproduce

Instantiate: `pkgs.python35Packages.opencv3.override { enableContrib = true; }`

## Technical details

* System: 17.03.1247.05126bc850 (Gorilla)
* Nix version: 1.11.8
* Nixpkgs version: "17.03.1247.05126bc850"
* Sandboxing enabled: false

**Comment by FRidh** [comment] 2017-06-02 07:15
@alexozer you may want to cc the maintainer of the expression, if there is one that is.

**Comment by alexozer** [comment] 2017-06-02 13:36
@viric

**Comment by FRidh** [comment] 2017-06-05 10:14
Is it even supported on Python 3?
https://github.com/opencv/opencv/issues/4508

**Comment by alexozer** [comment] 2017-06-05 14:09
@FRidh in that issue it seems like they conclude it's possible to build OpenCV with Python 3 (which it is even in Nix without contrib), and I can also build OpenCV with contrib and python3 outside NixOS with cmake, so I do think OpenCV + OpenCV contrib supports Python 3.

**Comment by alexozer** [comment] 2017-06-07 16:37
Other maintainer: @mdaiter

**Comment by mdaiter** [comment] 2017-06-07 17:33
@alexozer , I'd say this seems like a NixOS specific problem. The package is trying to iterate over a set of files that doesn't exist under the current directory. I'd use `sed` to change this line:
https://github.com/opencv/opencv/blob/master/modules/python/src2/gen2.py#L953
like so:

```
sed -e 's|/Users/vp/tmp|/tmp|g' -i ${pkgs.opencv_contrib}/modules/python/src2/gen2.py
```

and this line:
https://github.com/opencv/opencv/blob/master/modules/python/src2/hdr_parser.py#L8-L20
to

```
sed -e '(do something here -- on vacation)' -i ${pkgs.opencv_contrib}/modules/python/src2/gen2.py
```

**Comment by FRidh** [comment] 2017-07-26 17:00
So those links should I think be

- https://github.com/opencv/opencv/blob/3.2.0/modules/python/src2/gen2.py#L917
- https://github.com/opencv/opencv/blob/3.2.0/modules/python/src2/gen2.py#L871

because we have 3.2.0.

**Comment by Hodapp87** [comment] 2017-07-26 17:01
This isn't just a Python 3 issue; I just reproduced this on Python 2.7.

**Comment by alexozer** [comment] 2017-07-26 22:36
Any way to cache the results of the compilation so we don't have to wait an hour each time to test?

**Comment by Hodapp87** [comment] 2017-07-26 23:37
What I'm running into at the debugger is that for the line:

```python
self.code_include.write( '#include "{0}"\n'.format(hdr[hdr.rindex('opencv2/'):]) )
```

it has a bunch of values of `hdr` which don't contain `opencv2/` anywhere:

```
/run/user/1000/opencv_contrib/dnn/misc/tensorflow/attr_value.pb.cc
/run/user/1000/opencv_contrib/dnn/misc/tensorflow/function.pb.cc
/run/user/1000/opencv_contrib/dnn/misc/tensorflow/graph.pb.cc
/run/user/1000/opencv_contrib/dnn/misc/tensorflow/op_def.pb.cc
/run/user/1000/opencv_contrib/dnn/misc/tensorflow/tensor.pb.cc
/run/user/1000/opencv_contrib/dnn/misc/tensorflow/tensor_shape.pb.cc
/run/user/1000/opencv_contrib/dnn/misc/tensorflow/types.pb.cc
/run/user/1000/opencv_contrib/dnn/misc/tensorflow/versions.pb.cc
/run/user/1000/opencv_contrib/dnn/misc/caffe/caffe.pb.cc
/run/user/1000/opencv_contrib/dnn/misc/tensorflow/attr_value.pb.h
/run/user/1000/opencv_contrib/dnn/misc/tensorflow/function.pb.h
/run/user/1000/opencv_contrib/dnn/misc/tensorflow/graph.pb.h
/run/user/1000/opencv_contrib/dnn/misc/tensorflow/op_def.pb.h
/run/user/1000/opencv_contrib/dnn/misc/tensorflow/tensor.pb.h
/run/user/1000/opencv_contrib/dnn/misc/tensorflow/tensor_shape.pb.h
/run/user/1000/opencv_contrib/dnn/misc/tensorflow/types.pb.h
/run/user/1000/opencv_contrib/dnn/misc/tensorflow/versions.pb.h
/run/user/1000/opencv_contrib/dnn/misc/caffe/caffe.pb.h
```
Almost every other path does, but this makes me wonder how this build ever works on any other system. Does it coincidentally find some `opencv2/` in the path there or something?

**Comment by basvandijk** [comment] 2018-11-26 16:11
This has been fixed in https://github.com/NixOS/nixpkgs/pull/27674.

**Closed by basvandijk** 2018-11-26 16:11 UTC
Labels: 6.topic: python
