### ISSUE TITLE
rustPlatform.buildRustPackage: Allow fetching `Cargo.lock` from a different URL

### ISSUE THREAD

**Issue by primeos** [NixOS/nixpkgs#95331] opened 2020-08-13 12:10 UTC
Note: My current knowledge might unfortunately be a bit outdated as I didn't open this issue right away. But `doc/languages-frameworks/rust.section.md` currently only mentions `cargoPatches` which IMO isn't suitable to add a large `Cargo.lock` file (at least without a function that can transform a file from `fetchurl` to a patch that adds the file).

With the current implementation it IIRC isn't possible to provide `Cargo.lock` during the patch phase as it is already used before to fetch the dependencies. To work around this a more verbose and inefficient workaround is required, e.g.:

```nix
  src = stdenv.mkDerivation rec {
    name = "${pname}-source-${version}";

    src = fetchFromGitHub {
      owner = "lu-zero";
      repo = pname;
      rev = "v${version}";
      sha256 = "0n52xh4qg12bvvp2dgx5wfj5f31qijdqahasa3qfa3c3aqq7cvvg";
    };
    cargoLock = fetchurl {
      url = "https://github.com/lu-zero/${pname}/releases/download/v${version}/Cargo.lock";
      sha256 = "0296187hsaxxmqhsrrva4qf313jwh3z08j1vxcbislxdq8xg32qb";
    };

    installPhase = ''
      mkdir -p $out
      cp -R ./* $out/
      cp ${cargoLock} $out/Cargo.lock
    '';
  };
```

(See #91050 for the complete example.)

It would be nice if one could instead do something like passing `cargoLock` to `buildRustPackage` (with `cargoLock` e.g. defaulting to `null` -> use `./Cargo.lock` / don't override it):

```nix
    src = fetchFromGitHub {
      owner = "lu-zero";
      repo = pname;
      rev = "v${version}";
      sha256 = "0n52xh4qg12bvvp2dgx5wfj5f31qijdqahasa3qfa3c3aqq7cvvg";
    };
    cargoLock = fetchurl {
      url = "https://github.com/lu-zero/${pname}/releases/download/v${version}/Cargo.lock";
      sha256 = "0296187hsaxxmqhsrrva4qf313jwh3z08j1vxcbislxdq8xg32qb";
    };
```

Or providing `Cargo.lock` during the unpack or patch phases (`postUnpack`, `prePatch`, `postPatch`), e.g. (using `let cargoLock = ...; in ...`):

```nix
  postUnpack = ''
    cp ${cargoLock} .
  '';
```

What do you think? Am I missing something?

cc @Mic92 @wizeman @bhipple @Ma27

**Comment by Ma27** [comment] 2020-08-13 12:13
Could you somehow use `cargoPatches` for instance?

**Comment by primeos** [comment] 2020-08-13 12:35
@Ma27 I didn't try but I wouldn't expect this to work:
```nix
cargoPatches = [
  (fetchurl {
    url = "https://github.com/lu-zero/${pname}/releases/download/v${version}/Cargo.lock";
    sha256 = "0296187hsaxxmqhsrrva4qf313jwh3z08j1vxcbislxdq8xg32qb";
  })
];
```

It would require some abstraction like `fetchUrlAsPatch` or `fileToPatch` (to convert the file into a patch that adds the entire file).

**Comment by Ma27** [comment] 2020-08-13 13:07
Fair enough, this is obviously only suitable if you have a patch somewhere (which is the case when a project doesn't have a Cargo.lock and you create a local commit with a locally generated lockfile).

Another approach that may be more suitable for you is the one in e.g. `cargo-make`:

https://github.com/NixOS/nixpkgs/blob/db0540d1787fd8470f8b491b9474a3d10bcce700/pkgs/development/tools/rust/cargo-make/default.nix#L9-L22

**Comment by primeos** [comment] 2020-08-13 17:12
> Another approach that may be more suitable for you is the one in e.g. `cargo-make`:

That's more or less just another (better) variant of my first sample (replacing `mkDerivation` with `runCommand`). It e.g. still produces tree store paths (the 3rd one combining the files from the other two - though with `nix.autoOptimiseStore` this will at least get deduplicated).

I also just realized that my title for this issue might be a bit misleading. It's mainly about adding an abstraction to make this easier as well as more efficient. See e.g. https://github.com/NixOS/nixpkgs/pull/91050#discussion_r442371134. And IMO we should certainly try to avoid adding entire `Cargo.lock` files to Nixpkgs as that creates huge diffs (and limits scalability of our monorepo - IIRC this is(/was?) also the biggest blocker for building npm/yarn packages from source in Nixpkgs).

**Comment by Mic92** [comment] 2020-08-15 07:46
I am just worried a bit that we clutter `buildRustPackage` with too many different options to do the same thing.
Right now we have `cargoUpdateHook`, `cargoDepsHook`, `unpackPhase` and `cargoPatches`. 
I think the issue is that `cargoDepsHook` and `cargoUpdateHook` only executed in either the fixed-input-derivation or the actual package build. If they would be merged into one hook than you could just do:

```
cargoDepsHook = ''
  cp ${fetchurl { ... }} Cargo.toml
'';
```

or any other modification instead of sed. How does that sound?

**Comment by Mic92** [comment] 2020-08-15 07:48
Also instead of `cargoPatches` we should have inherited `patches` for both derivations. There is no reason it should be only applied to one of the derivations.

**Comment by bhipple** [comment] 2020-08-15 16:59
IIRC `cargoPatches` is run twice: once on your `src`, and once on your cargo vendor dir -- so the only thing it can meaningfully patch are your `Cargo.lock` or cargo vendor deps.

>  am just worried a bit that we clutter buildRustPackage with too many different options to do the same thing.

Agreed; the solution in `cargo-make` is a little clunky, but probably adequate given that there aren't too many Rust apps missing cargo.lock in the first place?

**Comment by primeos** [comment] 2020-08-15 20:29
> I am just worried a bit that we clutter `buildRustPackage` with too many different options to do the same thing.

Agreed, though I don't think this is the case here as `cargoPatches` only accepts patches. Though I'm wondering if a `fileToPatch` library function might make sense (shouldn't be difficult to implement, basically something like `diff -u /dev/null ${file}` + correct file name and deterministic date)?

> If they would be merged into one hook [cargoDepsHook] than you could just do: [...] How does that sound?

LGTM, that would avoid having to combine two sources.

> Agreed; the solution in cargo-make is a little clunky, but probably adequate given that there aren't too many Rust apps missing cargo.lock in the first place?

If there aren't many packages that need to fetch a `Cargo.lock` file (I'm only aware of three so far but there should be at least a few more) then we can always just close this issue. Feel free to close it if you assume that this is the case ;)

**Comment by bhipple** [comment] 2020-08-26 19:13
> If there aren't many packages that need to fetch a Cargo.lock file (I'm only aware of three so far but there should be at least a few more) then we can always just close this issue. Feel free to close it if you assume that this is the case ;)

IIRC it's ~10-20 Rust packages out of 220+ packages, and decreasing over time since upstream cargo manual recommends including a working cargo.lock in git as best practice, so maintainers slowly seem to be adding them.  Not opposed to this idea in principle, but inclined to take a "wait and see" approach, since the status quo run cmd method works decently well-ish and is reasonably simple to understand.

**Closed by bhipple** 2020-08-26 19:13 UTC
Labels: 0.kind: enhancement, 6.topic: rust
