### ISSUE TITLE
`tensorflow-2.18.0-cp312-cp312` build failure on x86_64-linux as of `9a415c28`

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#351314] opened 2024-10-26 00:28 UTC
## Issue description
Build of `tensorflow-2.18.0-cp312-cp312` failed on x86_64-linux as of 9a415c28ae33047988090cf0af2dac3311f3e2a2. This is currently breaking `python3Packages.tensorflow-bin`.

```
error: builder for '/nix/store/4gcpji9zfqjcjkikhmrsypdya85g0s0q-tensorflow-2.18.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.drv' failed with exit code 1;
       last 9 log lines:
       > error checking the existence of https://tarballs.nixos.org/sha256/11k2gj0ibz9m35l673r12zk7w991ssfm53fp7ll68h06gvm6bpdz:
       > curl: (77) error setting certificate file: /nix/store/h8qhspg7pml84z8s4ghrhmx6m77rs161-nss-cacert-3.104/etc/ssl/certs/ca-bundle.crt
       >
       > trying https://storage.googleapis.com/tensorflow/versions/2.18.0/tensorflow-2.18.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > curl: (77) error setting certificate file: /nix/store/h8qhspg7pml84z8s4ghrhmx6m77rs161-nss-cacert-3.104/etc/ssl/certs/ca-bundle.crt
       > error: cannot download tensorflow-2.18.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl from any mirror
       For full logs, run 'nix log /nix/store/4gcpji9zfqjcjkikhmrsypdya85g0s0q-tensorflow-2.18.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.drv'.
error: 1 dependencies of derivation '/nix/store/rbm45ga45zgk1pl1s120w6qmcqri3685-python3.12-tensorflow-gpu-2.18.0.drv' failed to build
```

[full build log](https://github.com/samuela/nixpkgs-upkeep/actions/runs/11527128732)

python3Packages.tensorflow-bin maintainers cc: @jyp @abbradar
tensorflow-2.18.0-cp312-cp312 maintainers cc: 
Other cc: n/a

### Steps to reproduce
1. Checkout nixpkgs at commit 9a415c28ae33047988090cf0af2dac3311f3e2a2
2. Run `nix-build -A tensorflow-2.18.0-cp312-cp312`

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.0-1025-azure, Ubuntu, 22.04.5 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.16.1`
 - nixpkgs: `/nix/store/5wirvfs78yiczdjk0ilwzrqd3vdqj215-source`
```

Contents of `~/.config/nixpkgs/config.nix`:
```
{ allowUnfree = true; cudaSupport = true; cudaCapabilities = ["8.0"]; }
```

## Misc.
This issue was automatically generated by [nixpkgs-upkeep](https://github.com/samuela/nixpkgs-upkeep).
- [CI workflow](https://github.com/samuela/nixpkgs-upkeep/actions/runs/11527128732) that created this issue.
- Internal tags: -5597717282518604170 -1982047357228635782

**Comment by SuperSandro2000** [comment] 2024-10-26 11:51
dupe of #351312

**Closed by SuperSandro2000** 2024-10-26 11:51 UTC
Labels: 0.kind: build failure
