### ISSUE TITLE
Package request: Astronvim

### ISSUE THREAD

**Issue by Marin-Kitagawa** [NixOS/nixpkgs#326319] opened 2024-07-11 13:52 UTC
**Project description**

Astronvim is a Neovim framework just like Lunarvim. Lunarvim has a package in NixOS but not Astronvim. Astronvim feels friendlier to use than Lunarvim. It'd be better to have Astronvim as a package just like Lunarvim

**Metadata**

* homepage URL: https://astronvim.com
* source URL: https://github.com/AstroNvim/AstroNvim
* license: GNU General Public License v3.0
* platforms: *nix, Windows

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Tungsten842** [comment] 2024-07-11 14:27
duplicate of: https://github.com/NixOS/nixpkgs/issues/311887

**Comment by jopejoe1** [comment] 2024-07-12 05:15
Duplicate of #311887

**Closed by jopejoe1** 2024-07-12 05:15 UTC
Labels: 0.kind: packaging request
