### ISSUE TITLE
Alias @astrojs/language-server is still in node-packages.nix

### ISSUE THREAD

**Issue by hannesg** [NixOS/nixpkgs#333677] opened 2024-08-10 12:42 UTC
### Describe the bug
The nodejs package "@astrojs/language-server" fails after merging #309100 with:

```
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'shell'
         whose name attribute is located at /nix/store/vkyrj85l215ycifp3rx7hq2rirxw0rrc-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:334:7

       … while evaluating attribute 'buildInputs' of derivation 'shell'

         at /nix/store/vkyrj85l215ycifp3rx7hq2rirxw0rrc-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:381:7:

          380|       depsHostHost                = elemAt (elemAt dependencies 1) 0;
          381|       buildInputs                 = elemAt (elemAt dependencies 1) 1;
             |       ^
          382|       depsTargetTarget            = elemAt (elemAt dependencies 2) 0;

       error: Alias @astrojs/language-server is still in node-packages.nix
```

### Steps To Reproduce
1. Use nixpkgs unstable channel on a commit after `d128948f8c90`
2. Run `nix-shell -p "nodePackages.\"@astrojs/language-server\""`

### Expected behavior
The package should still work as it did in the commit before. If the package is up for removal there should be a clean migration path.

### Additional context
This package is used in nixvim ( https://github.com/nix-community/nixvim/blob/4852f94f8ccae551514df0092a077014bafb95ca/plugins/lsp/language-servers/default.nix#L31 ) and the change broke automatic update.

### Notify maintainers

@pyrox0

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.0-39-generic, Ubuntu, 24.04 LTS (Noble Numbat), nobuild`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.4`
 - channels(hag): `"home-manager, nixpkgs"`
 - nixpkgs: `/home/hag/.nix-defexpr/channels/nixpkgs
```

**Comment by MattSturgeon** [comment] 2024-08-10 13:05
Just to note, this issue has affected a number of package renames, being moved from `nodePackages` to the top-level.

I'm not sure what the intended deprecation warning and/or transition period is before an outright removal?

**Comment by mustafasegf** [comment] 2024-08-10 13:55
you can install `astro-language-server` instead https://github.com/NixOS/nixpkgs/blob/a3a5fb4bbc6833c197ddf9d66dbf610041013f04/pkgs/by-name/as/astro-language-server/package.nix

**Comment by MattSturgeon** [comment] 2024-08-10 14:52
> you can install `astro-language-server` instead

I don't think that's the issue; the issue is that `nodePackages.*` packages seem to getting renamed/moved/whatever without going through the normal alias -> deprecated -> assertion process.

**Comment by eclairevoyant** [comment] 2024-08-10 15:55
> The nodejs package "@astrojs/language-server" fails after merging #309100 with:

That's not possible since that PR wasn't merged.

**Comment by MattSturgeon** [comment] 2024-08-10 16:06
> > The nodejs package "@astrojs/language-server" fails after merging #309100 with:
> 
> That's not possible since that PR wasn't merged.

I believe they meant d128948f8c908057d56078380c797df14b6c4237

**Comment by donovanglover** [comment] 2024-08-10 19:36
Fixed in https://github.com/NixOS/nixpkgs/pull/333736

**Closed by donovanglover** 2024-08-10 19:36 UTC
Labels: 0.kind: bug, 6.topic: nodejs
