### ISSUE TITLE
Boost 1.70 cmake config broken

### ISSUE THREAD

**Issue by ktf** [NixOS/nixpkgs#63104] opened 2019-06-13 22:45 UTC
## Issue description

Looks like the CMake config files produced by boost 1.70 do not work correctly because they assume the headers and the library to be in the same top-level folder (they are not, due to the fact there is "out" and "dev").

### Steps to reproduce

Have a Cmakefile which does `find_package(Boost REQUIRED COMPONENTS unit_test_framework)` and try to build it.

## Technical details

```
→ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.5.0, macOS 10.14.4`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.1`
 - channels(ktf): `"nixpkgs-18.09pre154109.571b40d3f50, nixpkgs-19.03-19.03pre172363.b12b1e2f428, nixpkgs-unstable-19.09pre177248.ed1b59a98e7"`
 - nixpkgs: `/Users/ktf/src/nix/nixpkgs`
```

**Comment by veprbl** [comment] 2019-06-14 20:24
It appears the paths in those config files are quite aware of difference between the includedir and libdir as seen in "result-dev/lib/cmake/boost_atomic-1.70.0/boost_atomic-config.cmake":
```
get_filename_component(_BOOST_CMAKEDIR "${CMAKE_CURRENT_LIST_DIR}/../" ABSOLUTE)
get_filename_component(_BOOST_INCLUDEDIR "${_BOOST_CMAKEDIR}/../../../qk9apiwla9pzawjmnc4s5qsndyhkbqdg-boost-1.70.0-dev/include/" ABSOLUTE)
get_filename_component(_BOOST_LIBDIR "${_BOOST_CMAKEDIR}/../" ABSOLUTE)
```
The issue seems to be caused by the fact that these relative paths assume that the cmake configs will be installed in libdir which points to $out/lib, but in our case they end up in "$dev/lib".

**Comment by ktf** [comment] 2019-06-20 13:42
I've seen other packages with a similar issue (e.g. `fmt`). Any suggestion on how to work this around?

**Comment by veprbl** [comment] 2019-06-20 14:05
Well, it makes perfect sense to leave cmake files in the dev output.

One workaround that doesn't require any understanding of how boost builds itself is to just patch this with brute force. Something like:
```
postInstall = stdenv.lib.optionalString (lib.versionAtLeast "1.70" version) ''
  for file in "$dev/lib/cmake/"*/*.cmake; do
    substituteInPlace $file \
      --replace 'get_filename_component(_BOOST_CMAKEDIR " "get_filename_component(_BOOST_CMAKEDIR "'$dev/lib/cmake/'" ABSOLUTE)' \
      --replace 'get_filename_component(_BOOST_INCLUDEDIR " "get_filename_component(_BOOST_INCLUDEDIR "'$dev/include/'" ABSOLUTE)' \
      --replace 'get_filename_component(_BOOST_LIBDIR " "get_filename_component(_BOOST_LIBDIR "'$out/lib/'" ABSOLUTE)'
  done
'';
```
This is just a sketch of a possible workaround, I didn't test it in any way.

**Comment by ktf** [comment] 2019-06-24 22:47
Thanks, this allowed to get me a step further:

```
    myBoost = pkgs.boost170.overrideAttrs (attrs: {
      postFixup = ''
        # Make boost header paths relative so that they are not runtime dependencies
        cd ''${!outputDev} && find include \( -name '*.hpp' -or -name '*.h' -or -name '*.ipp' \) \
        -exec sed '1s/^\xef\xbb\xbf//;1i#line 1 "{}"' -i '{}' \;
        '';
      postInstall = ''
        echo "''${!outputDev}/lib/cmake/"*/*.cmake > $out/foo
        echo "''${!outputLib}/lib/cmake/"*/*.cmake >> $out/foo
        for file in "''${!outputLib}/lib/cmake/"*/*.cmake; do
          substituteInPlace $file \
            --replace "get_filename_component(_BOOST_CMAKEDIR" "get_filename_component(_BOOST_CMAKEDIR "''${!outputDev}/lib/cmake/" ABSOLUTE)#"   \
            --replace "get_filename_component(_BOOST_INCLUDEDIR" "get_filename_component(_BOOST_INCLUDEDIR "''${!outputDev}/include/" ABSOLUTE)#" \
            --replace "get_filename_component(_BOOST_LIBDIR" "get_filename_component(_BOOST_LIBDIR "''${!outputLib}/lib/" ABSOLUTE)#"
        done
        '';
    });
    myFmt = pkgs.fmt.overrideAttrs (attrs: {
      outputs = [ "out" ];
      cmakeFlags = [
        "-DFMT_TEST=FALSE"
        "-DBUILD_SHARED_LIBS=TRUE"
      ];
    });
```

Looks like in `postInstall` the files are still in `$out`.

Am I right that `${!outputDev}` should be preferred over `$dev` so that people can merge `out` and `dev` if needed by doing:

```
outputDev = "out";
```

?

I still have a problem with `unit_test_framework`, but I suspect that's because I need also the static version of it...

**Comment by veprbl** [comment] 2019-06-24 23:10
@ktf Great! Do you mind opening a PR?

Regarding `$outputFoo`, I believe it's meant to provide a framework for generic builders. There is documentation in manual https://nixos.org/nixpkgs/manual/#multiple-output-file-type-groups . Most expressions in nixpkgs use `$out`, `$dev` and such, your use case is currently not supported.

**Comment by arximboldi** [comment] 2019-09-25 12:05
Is there a workaround that does not involve rebuilding boost? Maybe something on the client side?

**Comment by veprbl** [comment] 2020-06-01 19:58
This may be resolved by #85254

**Comment by FlorianFranzen** [comment] 2020-06-02 10:38
If you run into this issue and need a quick fix, you can always symlink join `boost` with `boost.dev` to get a derivation with working CMake package config:
```nix
symlinkJoin {
  name = boost.name + "+cmake";
  paths = [ boost boost.dev ];
}
```

**Comment by mikepurvis** [comment] 2021-06-26 01:46
@veprbl I don't believe this is fixed yet— I'm still seeing the issue on the boost171 in the 21.05 release.

**Comment by knedlsepp** [comment] 2021-09-08 06:22
> FWIW, it looks like this _is_ actually fine in boost173-175, so maybe it is fine to close the ticket after all, since boost171 is now removed per #134930, and presumably the next NixOS release will be boost>=1.75:
> 
> ```
> $ grep filename /nix/store/2qn4pzrqpw0nlrq92v4c15nvg85jc0v3-boost-1.75.0-dev/lib/cmake/boost_system-1.75.0/boost_system-config.cmake
> get_filename_component(_BOOST_REAL_CMAKEDIR "${CMAKE_CURRENT_LIST_DIR}/../" REALPATH)
>   get_filename_component(_BOOST_CMAKEDIR_ORIGINAL "/nix/store/njh175giavpvnqpm1yzk6zn6d5pb81x5-boost-1.75.0/lib/cmake" REALPATH)
> get_filename_component(_BOOST_CMAKEDIR "/nix/store/njh175giavpvnqpm1yzk6zn6d5pb81x5-boost-1.75.0/lib/cmake" REALPATH)
> get_filename_component(_BOOST_INCLUDEDIR "${_BOOST_CMAKEDIR}/../../../2qn4pzrqpw0nlrq92v4c15nvg85jc0v3-boost-1.75.0-dev/include/" ABSOLUTE)
> get_filename_component(_BOOST_LIBDIR "${_BOOST_CMAKEDIR}/../" ABSOLUTE)
>   get_filename_component(_BOOST_CMAKEDIR "${CMAKE_CURRENT_LIST_DIR}/../" ABSOLUTE)
> ```

Nice. Then let's do that!

**Closed by knedlsepp** 2021-09-08 06:22 UTC
Labels: 0.kind: bug
