### ISSUE TITLE
openrussian-cli package cannot find necessary Lua modules

### ISSUE THREAD

**Issue by ehmry** [NixOS/nixpkgs#164118] opened 2022-03-14 14:04 UTC
### Describe the bug
The `openrussian-cli` package cannot find necessary Lua modules.

```
/nix/store/5gm4rzsdd40i9ph97bxs5bwrfanmg11v-lua-5.3.6/bin/lua: openrussian.lua:3: module 'luasql.sqlite3' not found:
	no field package.preload['luasql.sqlite3']
	no file './share/lua/5.3/luasql/sqlite3.lua'
	no file './luasql/sqlite3.lua'
	no file './luasql/sqlite3/init.lua'
	no file './lib/lua/5.3/luasql/sqlite3.so'
	no file './luasql/sqlite3.so'
	no file './lib/lua/5.3/loadall.so'
	no file './lib/lua/5.3/luasql.so'
	no file './luasql.so'
	no file './lib/lua/5.3/loadall.so'
stack traceback:
	[C]: in function 'require'
	openrussian.lua:3: in main chunk
	[C]: in ?
```

### Steps To Reproduce
1. `nix shell nixpksg#openrussian-cli`
2. `openrussian` 

### Notify maintainers
@vs49688 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.26, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220313_7abce04`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by vs49688** [comment] 2022-03-14 15:02
This is caused by https://github.com/NixOS/nixpkgs/issues/161375 and a fix is currently in staging-next. See https://github.com/NixOS/nixpkgs/pull/161396.

**Comment by ehmry** [comment] 2022-03-14 20:15
Nice. For now I was able to get a working version from the 21.11 release.

**Comment by vs49688** [comment] 2022-03-15 21:54
Closing, staging-next has been merged and the fix will show up in the channels when Hydra finishes.

**Closed by vs49688** 2022-03-15 21:54 UTC
Labels: 0.kind: bug, 6.topic: lua
