### ISSUE TITLE
Unable to set the user's language in GNOME Control Center

### ISSUE THREAD

**Issue by SamLukeYes** [NixOS/nixpkgs#204943] opened 2022-12-07 06:11 UTC
### Describe the bug
The per-user language setting in GNOME Control Center doesn't apply. After a re-login, GNOME still uses the system-wide language setting, while the setting in GNOME Control Center does remain as the language selected by user.

### Steps To Reproduce
1. Add an alternative language to `i18n.supportedLocales`, e.g. `zh_CN.UTF-8/UTF-8`
2. `sudo useradd -m test`
3. `sudo passwd test`
4. Switch user and login as user `test`
5. Change the language of Your Account in Region & Language setting
6. Logout and login `test` again

### Expected behavior
GNOME should use the language selected by user after re-login.

### Screenshots
![Screenshot from 2022-12-07 13-28-36](https://user-images.githubusercontent.com/12882091/206096335-ec113204-af5c-4439-a3f3-15fa77db9339.png)

### Additional context
- It seems that the `set-environment` script directly set `LANG` according to the system configuration without respecting per-user configurations. For some reason users might want to set locales at user level, according to [Arch Wiki](https://wiki.archlinux.org/title/Locale#Overriding_system_locale_per_user_session). I think this is how Arch handles per-user locale settings: https://github.com/archlinux/svntogit-packages/blob/packages/filesystem/trunk/locale.sh
- This issue can't be reproduced when using xonsh as login shell, even with https://github.com/NixOS/nixpkgs/pull/204252 (though the language used by interactive shell is changed to the system-wide setting after applying this PR). Actually, I first found this issue when I tried switching my login shell to bash after encountering https://github.com/NixOS/nixpkgs/issues/188404. Haven't tried other login shells yet.

### Notify maintainers
- @NixOS/gnome 
- Probably also related to i18n module: @edolstra @jfrankenau @minijackson 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.81, NixOS, 23.05 (Stoat), 23.05.20221204.14ddeae`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/store/lv4sashw7c0z9x06nh48rs4vg08dwdqq-source`

**Comment by jtojnar** [comment] 2022-12-07 13:43
Duplicate of https://github.com/NixOS/nixpkgs/issues/166913

**Closed** 2022-12-13 11:45 UTC
Labels: 0.kind: bug
