### ISSUE TITLE
bind-9.10.4-P4: bin/host collision

### ISSUE THREAD

**Issue by polyrod** [NixOS/nixpkgs#21677] opened 2017-01-05 13:42 UTC
## Issue description
When installing bind following packages collide binaries:
bind-9.10.4-P4-host/bin/host
bind-9.10.4-P4-dnsutils/bin/host

nix-env --setflag priority wont work because one cannot install one package standalone.
if you try to either , 
       nix-env -iA nixos.bind
       nix-env -iA nixos.dnsutils
       nix-env -iA nixos.host

, all three packeges are installed producing the collision.

### Steps to reproduce

nixenv -iA nixos.bind

## Technical details

* System: (NixOS: 17.03pre98008.59dbcef)
* Nix version: (nix-env (Nix) 1.11.4)
* Nixpkgs version: (17.03pre98008.59dbcef)

**Comment by vcunat** [comment] 2017-01-05 18:44
Duplicate of https://github.com/NixOS/nixpkgs/issues/19761

**Closed by vcunat** 2017-01-05 18:44 UTC
Labels: 0.kind: regression
