### ISSUE TITLE
python3Packages.qiskit-{aer,aqua} tests take way too long

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#102724] opened 2020-11-04 07:23 UTC
The unit tests for python packages should be ~5 mins or less on a reasonable desktop. I think they've been going for >=1hr between `qiskit-aer` and `qiskit-aqua` on my review server.

Unit tests are highly encouraged to ensure packages are still coherent as we are often "more flexible" about version bounds than most upstream packages. We don't need to be as thorough as upstream is about regressions, we just need to ensure compatibility.

cc @drewrisinger

**Comment by drewrisinger** [comment] 2020-11-04 13:38
@jonringer they run relatively quickly locally for me, about 5 mins each.

The issue is probably that they run relatively heavy computations/quantum simulations as part of the unit tests. I've generally disabled all tests that take longer than 10 seconds on my 2011-era desktop (i5-2500), so I don't understand how it's taking > 1 hr other than maybe some issue with multi-thread race conditions in highly parallel systems. 

I'm rebuilding them locally, and will get back.

**Comment by drewrisinger** [comment] 2020-11-04 16:21
Qiskit-aer build log: 
```
========== 1070 passed, 940 skipped, 98 warnings in 161.72s (0:02:41) ==========
/build/source
Finished executing pytestCheckPhase
pytestcachePhase
/nix/store/7d3pbjzxl13nprxkfpswfiipsbh4nywg-python3.8-qiskit-aer-0.6.1

Total time (nothing else running): 4m 20s
```

Qiskit-aqua build log:
```
== 1228 passed, 177 skipped, 153 deselected, 25 warnings in 188.13s (0:03:08) ==
Finished executing pytestCheckPhase
pytestcachePhase
/nix/store/yf4rpfcs5s2kjgqq6fp08kw2fy61f1aj-python3.8-qiskit-aqua-0.7.5

Total time (nothing else running): 3m 32s
```

**Comment by jonringer** [comment] 2020-11-04 16:49
Interesting, because I'm giving them 32 cores. However, I was maxing out the server reviewing other PRs. maybe a situation where the tests think they have more cores available than they really do?

Even in the previous issue https://github.com/Qiskit/qiskit-aer/issues/892#issuecomment-695847299 , it took me 20 minutes with 32 cores (I guess NIX_BUILD_CORES isn't respected by nix-build, but --cores is).

**Comment by drewrisinger** [comment] 2020-11-04 23:03
@jonringer I pushed #100007 to fail tests that last longer than 30 seconds. If you try to review that sometime, let me know which tests fail and I'll disable them to hopefully resolve this issue.

**Comment by drewrisinger** [comment] 2020-12-01 13:47
Closing Post #100007, which times out the tests automatically to fix this issue.

**Closed by drewrisinger** 2020-12-01 13:47 UTC
Labels: 0.kind: enhancement, 6.topic: python
