### ISSUE TITLE
Build failure: floorp

### ISSUE THREAD

**Issue by neg-serg** [NixOS/nixpkgs#326275] opened 2024-07-11 10:09 UTC
### Steps To Reproduce

1. build floorp / floorp-unwrapped

### Build log

```
spidermonkey> Traceback (most recent call last):
spidermonkey>   File "/build/firefox-102.15.1/obj/../js/src/../../configure.py", line 25, in <module>
spidermonkey>     from mach.site import (
spidermonkey>   File "/build/firefox-102.15.1/python/mach/mach/site.py", line 26, in <module>
spidermonkey>     from mach.requirements import (
spidermonkey>   File "/build/firefox-102.15.1/python/mach/mach/requirements.py", line 7, in <module>
spidermonkey>     from packaging.requirements import Requirement
spidermonkey>   File "/build/firefox-102.15.1/third_party/python/packaging/packaging/requirements.py", line 24, in <module>
spidermonkey>     from .markers import MARKER_EXPR, Marker
spidermonkey>   File "/build/firefox-102.15.1/third_party/python/packaging/packaging/markers.py", line 25, in <module>
spidermonkey>     from .specifiers import InvalidSpecifier, Specifier
spidermonkey>   File "/build/firefox-102.15.1/third_party/python/packaging/packaging/specifiers.py", line 14, in <module>
spidermonkey>     from .utils import canonicalize_version
spidermonkey>   File "/build/firefox-102.15.1/third_party/python/packaging/packaging/utils.py", line 9, in <module>
spidermonkey>     from .tags import Tag, parse_tag
spidermonkey>   File "/build/firefox-102.15.1/third_party/python/packaging/packaging/tags.py", line 7, in <module>
spidermonkey>     import distutils.util
spidermonkey> ModuleNotFoundError: No module named 'distutils'
error: builder for '/nix/store/d1sj7j5a78m6lwws3ygvywg0zk0cmxzv-spidermonkey-102.15.1.drv' failed with exit code 1;
```

### Additional context

reproducible on nixos-unstable, nixos-master 

### Notify maintainers

@christoph-heiss 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.37, NixOS, 24.11 (Vicuna), 24.11.20240710.aa94615`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/3x6hmlqc6682q9z6n11ynvmq19hfrgn0-source`
```

**Comment by eclairevoyant** [comment] 2024-07-11 11:35
duplicate of #325785

**Closed by eclairevoyant** 2024-07-11 11:35 UTC
Labels: 2.status: duplicate, 0.kind: build failure
