### ISSUE TITLE
Package request: auto-editor

### ISSUE THREAD

**Issue by utopiatopia** [NixOS/nixpkgs#351848] opened 2024-10-28 09:50 UTC
**Project description**

Edits video/audio automatically, typically via audio loudness.

**Metadata**

* homepage URL: https://auto-editor.com/
* source URL: https://github.com/WyattBlue/auto-editor
* license: unlicense
* platforms: unix

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TomaSajt** [comment] 2024-10-28 18:22
Duplicate of https://github.com/NixOS/nixpkgs/issues/317015

**Comment by TomaSajt** [comment] 2024-10-28 18:22
Also, solved by https://github.com/NixOS/nixpkgs/pull/317557

**Closed by TomaSajt** 2024-10-28 18:22 UTC
Labels: 0.kind: packaging request
