### ISSUE TITLE
Build failure: nextcloud-client

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#326707] opened 2024-07-13 04:59 UTC
### Steps To Reproduce

```console
$  nix build 'github:nixos/nixpkgs/nixos-unstable#pkgs.nextcloud-client'
error: hash mismatch in fixed-output derivation '/nix/store/zg2zsi4nkgnhn92nj3qqmyd12kvban13-source.drv':
         specified: sha256-z4yxWClbs05ZCT8CPJpPY2BWMSXxfJ09Lq3Oottx7dQ=
            got:    sha256-hZjmAdh9QQ2bAIYL3K7scl59kz9Wxnv9f6rKMeuKb7U=
error: 1 dependencies of derivation '/nix/store/x0fg4xc7zr3gbsbaypqaq4xdc9gwyj33-nextcloud-client-3.13.2.drv' failed to build
```

### Additional context

https://matrix.to/#/!RRerllqmbATpmbJgCn:nixos.org/$KnejFx08TwswgPt8wXaVMFzNVFHa_WscQjYtr-IDzjU?via=nixos.org&via=matrix.org&via=tchncs.de

Credit: Soliprem for reporting this, thanks! <3

### Notify maintainers

CC @Kranzes @SuperSandro2000
 
### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.31-hardened1, NixOS, 24.05 (Uakari), 24.05.20240609.2819fff`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/giq1qbcwfx5gq0g9jf6id0b3m55a860j-source`
```

NiXium Config Reference: https://github.com/NiXium-org/NiXium/tree/db7f7af8a4c278f1e9f7d77c56c66e6b18419e6e/src/nixos/machines/sinnenfreude

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-07-13 05:01
duplicate of #326258
fixed in #326093

**Closed by eclairevoyant** 2024-07-13 05:01 UTC
Labels: 0.kind: build failure

**Comment by Kreyren** [comment] 2024-07-13 05:04
nix build 'github:nixos/nixpkgs/feb2849fdeb70028c70d73b848214b00d324a497#nextcloud-client'
error: hash mismatch in fixed-output derivation '/nix/store/zg2zsi4nkgnhn92nj3qqmyd12kvban13-source.drv':
         specified: sha256-z4yxWClbs05ZCT8CPJpPY2BWMSXxfJ09Lq3Oottx7dQ=
            got:    sha256-hZjmAdh9QQ2bAIYL3K7scl59kz9Wxnv9f6rKMeuKb7U=
error: 1 dependencies of derivation '/nix/store/x0fg4xc7zr3gbsbaypqaq4xdc9gwyj33-nextcloud-client-3.13.2.drv' failed to build

Still in unstable: https://github.com/NixOS/nixpkgs/commit/feb2849fdeb70028c70d73b848214b00d324a497

**Comment by eclairevoyant** [comment] 2024-07-13 05:08
Yes, you will need to wait for the PR to land (can take a couple days depending on how slow hydra is)
