### ISSUE TITLE
"nix-env -i emacs" installs "emacs-2048-game-20151026.1433"

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#12353] opened 2016-01-13 09:02 UTC
The name of the MELPA package `2048-game` looks like Emacs version `2048-game-20151026.1433` to Nix once the `emacs-` prefix is added. This has undesirable side-effects for our users, because running `nix-env -u` on a profile that has Emacs installed will give you a profile that, well, has no Emacs installed.

Cc: @ttuegel

**Comment by peti** [comment] 2016-01-13 09:06
Duh, after that package has been removed, the next choice is `emacs-4clojure-20131014.1707`.

**Comment by vcunat** [comment] 2016-01-13 09:16
:-) To mitigate such cases in general, what about modifying `nix-env` to check if `foo.pname` and `foo.version` are available and use those instead of parsing `foo.name`? That won't help with running `nix-env` on paths directly, but it should still cover most real-life cases, IMHO. (We'll just have to make the attributes available in the problematic packages.)

**Comment by peti** [comment] 2016-01-13 09:25
@vcunat, personally, I'd even go as far as turning our notion of `name` into a triple: name, version, and revision. Name and version are determined by upstream, and the revision is something we can use to denote Nix-specific information about the package, like build variants "with-crazy-XYZ-patch applied", etc. Furthermore, derivations should be allowed to specify a function attribute `__compare_version` that defines a total order on the (version,revision) tuple, i.e. packages can implement version comparison schemes that differ from the one Nix uses by default.

**Comment by oxij** [comment] 2016-01-13 10:18
And/or we can add an attribute that describes the suffix (or prefix of a
suffix) of the resulting path in /nix/store. E.g.
`/nix/store/hash-customprefix-name-version`. Call it `packageGroup` or
whatever, display to the user in nix-env listings and allow to specify
those `nix-env -g emacs -i whatever`.

This way `ghc` packages could have `haskell-` prefix in store paths back
too. I miss those prefixes.

**Comment by vcunat** [comment] 2016-01-13 11:23
This is also related to the talked-about *name -> attribute name* transition. Apart from that, name is IMO only useful for nix-env to decide whether to upgrade or install the package.

**Comment by vcunat** [comment] 2016-01-13 14:01
Even if we add `__compare_version`, I still see we would have some problems in the way `nix-env -u` determines how to upgrade when there are multiple variants of a package, e.g. firefox and firefox-esr.

With this naming we correctly upgrade within the same variant (unless some rename has happened), but we can't express that if one installs either of these two, one wants (typically) to replace the other variant. (Otherwise there tend to be collisions, and the result typically won't be useful even after resolving them.)

Also, we can't express: firefox-wrapper is deprecated and should be upgraded to firefox. I think major packaging systems even can express this kind of things nowadays; we tend to focus on declarative specifications instead, but maybe we might improve those issues.

@peti, all of these issues seem easier to handle in the case that `nix-env` would store the **attribute path** that you specified during `nix-env -i` (instead of plain name). There would be at most one possibility to upgrade to or even downgrade (!) if the channel decided so, missing paths could be reported easily, and we already do provide aliases for deprecated attributes.

**Comment by ttuegel** [comment] 2016-01-13 16:49
I can't update the Emacs packages without obliterating @peti's patches (because he edited a generated file). So, until there is a more permanent solution to this issue, how can I rename these packages to satisfy everyone?

**Comment by peti** [comment] 2016-01-13 16:53
You could ...

1. remove `recurseIntoAttrs` from the Emacs package set to avoid these kind of conflicts altogether or
2. prepend an underscore `_` to every package name that begins with a digit.

Option (1) is what I chose for the Haskell package set.

**Closed** 2016-01-13 18:58 UTC
Labels: 0.kind: bug

**Comment by edolstra** [comment] 2016-01-13 20:07
The downside of (1) is that it makes packages undiscoverable. Regardless of whether to do (1), (2) is still a good idea, since we really shouldn't have name conflicts or package names that start with digits.

**Comment by ttuegel** [comment] 2016-01-13 20:11
I'm fine with that downside in the interim because there are too many Emacs packages to be readily discoverable anyway. This is just a stop-gap measure until someone devises a sane interface to our package database instead of what currently exists in nix-env.

**Comment by puffnfresh** [comment] 2016-02-18 00:08
I upgraded my user env and was left with emacs-2048-game but no Emacs :crying_cat_face:

**Comment by vcunat** [comment] 2016-02-18 00:15
I suppose the worst part is that one can't even play the game without Emacs?

**Comment by ttuegel** [comment] 2016-02-18 01:31
@puffnfresh Are you using the latest unstable channel? The problem should be fixed there.

**Comment by puffnfresh** [comment] 2016-02-18 04:05
@ttuegel nope, my work computer is on 15.09 where I had the problem. I didn't notice that this issue was closed. Thanks for the fix!

**Comment by vcunat** [comment] 2016-02-18 08:58
I can't reproduce it on 15.09, even a few weeks old one 9fe0c23. I assume you have something even older among the channels?

**Comment by puffnfresh** [comment] 2016-02-18 10:18
@vcunat that is totally bizarre. I'm on a 7 day old commit:

```
$ cat $(nix-instantiate --find-file 'nixpkgs/.git-revision')
9a7b24ad04171f97521b422aef6668539341ecd0
$ nix-env -e emacs
uninstalling ‘emacs-24.5’
building path(s) ‘/nix/store/a98ricnkxfy3dps8mc7k4vgm7gbbx4kh-user-environment’
created 2691 symlinks in user environment
$ nix-env -i -f '<nixpkgs>' -A emacs
installing ‘emacs-24.5’
$ nix-env -u emacs
upgrading ‘emacs-24.5’ to ‘emacs-2048-game-20151026.1433’
building path(s) ‘/nix/store/b5l07m6hd1p3wv5msafafy81zazxwxn2-user-environment’
created 2694 symlinks in user environment
```

**Comment by ttuegel** [comment] 2016-02-18 12:15
> I can't reproduce it on 15.09, even a few weeks old one 9fe0c23. I assume you have something even older among the channels?

This issue won't affect 15.09 at all because I never backported the new Emacs packages.

**Comment by vcunat** [comment] 2016-02-18 15:24
When you don't specify `-f`, it should take ` ~/.nix-defexpr` and you can have multiple old channels in there. (It considers a union of them and such a high version should always win.)

You can still `nix-env -f '<nixpkgs>' -u ...`

**Comment by puffnfresh** [comment] 2016-02-18 20:26
@vcunat whoops, I also had an old channel in there. Thank you!

**Comment by vcunat** [comment] 2016-02-19 06:56
:-)
