### ISSUE TITLE
Xournalpp is missing icons

### ISSUE THREAD

**Issue by QuantMint** [NixOS/nixpkgs#210182] opened 2023-01-11 10:54 UTC
### Describe the bug
Some icons from the sidebar are missing.

In the terminal:
```
(xournalpp:14560): Gtk-WARNING **: 11:48:58.377: Error loading theme icon 'window-close' for stock: Icon 'window-close' not present in theme Adwaita

(xournalpp:14560): Gtk-WARNING **: 11:48:58.377: Error loading theme icon 'go-up' for stock: Icon 'go-up' not present in theme Adwaita

(xournalpp:14560): Gtk-WARNING **: 11:48:58.377: Error loading theme icon 'go-down' for stock: Icon 'go-down' not present in theme Adwaita

(xournalpp:14560): Gtk-WARNING **: 11:48:58.377: Error loading theme icon 'edit-copy' for stock: Icon 'edit-copy' not present in theme Adwaita

(xournalpp:14560): Gtk-WARNING **: 11:48:58.377: Error loading theme icon 'edit-delete' for stock: Icon 'edit-delete' not present in theme Adwaita
```

### Screenshots
![image](https://user-images.githubusercontent.com/24614168/211787150-b64f511e-0a3d-4aab-abe9-5eeb738a305f.png)
![image](https://user-images.githubusercontent.com/24614168/211787243-793defb9-f9ba-4c3d-bdb9-e48bc2511bd5.png)

### Notify maintainers
 @andrew-d @sikmir @alyaeanyx 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.0-xanmod1, NixOS, 23.05 (Stoat), 23.05.20230105.a518c77`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `""`
 - channels(quantmint): `""`
 - nixpkgs: `/run/current-system/nixpkgs`
```

**Comment by alyaeanyx** [comment] 2023-01-11 11:39
What are your toolbar settings? (View -> Toolbars)

**Comment by QuantMint** [comment] 2023-01-11 11:51
> What are your toolbar settings? (View -> Toolbars)
Xournal++

**Comment by alyaeanyx** [comment] 2023-01-11 22:49
Thanks, I was able to reproduce this now. I'll take a look at it.

**Comment by alyaeanyx** [comment] 2023-01-11 23:04
Seems like it's an upstream issue that's already known: https://github.com/xournalpp/xournalpp/issues/3945
Apparently there was a PR about it that was merged 2 weeks ago in https://github.com/xournalpp/xournalpp/pull/4544, and I've confirmed that the issue is fixed on master, so we'll get the fix with the next release of Xournal++ :)

Screenshot of Xournalpp built from master:
![xournalpp_fix](https://user-images.githubusercontent.com/74795488/211936914-ab141819-e4e0-4fc1-830a-b9f8d8a24d92.png)

**Closed** 2023-01-11 23:04 UTC
Labels: 0.kind: bug
