### ISSUE TITLE
firewalld module(original PR has been closed)

### ISSUE THREAD

**Issue by deviantsemicolon** [NixOS/nixpkgs#326250] opened 2024-07-11 06:19 UTC
## Issue description

The PR for implementing a firewalld module has been closed. firewalld is something i'd like to be able to use without jumping through hoops to get it working because i have a laptop that i take with me places, and the zoning capabilities of firewalld would be appreciated.

### Steps to reproduce

1. Look at nixos options search
2. search for firewalld
3. cry

**Comment by eclairevoyant** [comment] 2024-07-11 06:33
duplicate of #165882

**Closed by eclairevoyant** 2024-07-11 06:33 UTC
