### ISSUE TITLE
Build failure: dkjson

### ISSUE THREAD

**Issue by s1n7ax** [NixOS/nixpkgs#334775] opened 2024-08-15 05:04 UTC
### Steps To Reproduce

1. build *luajitPackages.luacheck*

### Build log

```
❯ home-manager --impure switch --refresh --flake ./#desktop
warning: Git tree '/home/s1n7ax/Workspace/home-manager' is dirty
error: hash mismatch in fixed-output derivation '/nix/store/jl63hzr355zarhjlr50v887giyq8062n-dkjson-2.8.tar.gz.drv':
         specified: sha256-CfpgoEECteMiqwa51Zt6oPKcChnHVCFfikHzoWT5SUs=
            got:    sha256-JOjNO+uRwchh63uz+8m9QYu/+a1KpdBHGBYlgjajFTI=
error: 1 dependencies of derivation '/nix/store/vcbp9hj73w2jfc3kv785k0p9mvlqz17f-luajit2.1-dkjson-2.8-1.drv' failed t
o build
error: 1 dependencies of derivation '/nix/store/in0zqlfw4zdxr1mwz1fr8hp064ghd2mc-luajit2.1-busted-2.2.0-1.drv' failed
 to build
error: 1 dependencies of derivation '/nix/store/cbad31ygxcg5pkbr4kzshpcir335a7pj-luajit2.1-argparse-0.7.1-1.drv' fail
ed to build
error: 1 dependencies of derivation '/nix/store/79crlbgkkxj06paz6154qi2jj9slgf33-luajit2.1-luacheck-1.2.0-1.drv' fail
ed to build
error: 1 dependencies of derivation '/nix/store/4r89a5lqr1jc10zk6mfsbb821r3218bk-home-manager-path.drv' failed to bui
ld
error: 1 dependencies of derivation '/nix/store/j09m9vyacfx1r744bzpg6fjnipcpyfdy-home-manager-generation.drv' failed 
to build
```

### Notify maintainers

@teto

### Metadata

I'm using flake to manage home-manager so the following channel versions are not correct?

https://github.com/s1n7ax/home-manager/blob/6adaeece0c4984305e02918ce9a722b6a1808634/flake.nix?plain=1#L5-L13

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.44, NixOS, 24.05 (Uakari), 24.05.20240810.a781ff3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(s1n7ax): `"home-manager, nixos-23.11"`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/store/61502m9h1jl40j7sxbcyjdm6qi1k7x97-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lucc** [comment] 2024-08-15 06:30
Duplicate of #334395

**Closed** 2024-08-15 07:23 UTC
Labels: 0.kind: build failure
