### ISSUE TITLE
Can not Uninstall Gnome-Tour

### ISSUE THREAD

**Issue by pxp9** [NixOS/nixpkgs#180503] opened 2022-07-07 11:38 UTC
### Steps To Reproduce
1. Just install Nixos enabling Gnome 
```nix
services.xserver.desktopManager.gnome.enable = true;
```

### Expected behavior
An option to Exclude Gnome-Tour package or to exclude some Gnome-shell packages

### Additional context
I would like to exclude some useless Gnome-shell packages that if i exclude them will not break my whole system.
You can not exclude packages from Gnome-shell with this option [environment.gnome.excludePackages](https://search.nixos.org/options?channel=22.05&from=0&size=50&sort=relevance&type=packages&query=excludePackages)
and this 
```nix 
services.gnome.core-shell.enable = false ;
```
not work because is required by this
```nix 
services.xserver.desktopManager.gnome.enable = true;
```
### Notify maintainers
@bobby285271

**Comment by bobby285271** [comment] 2022-07-07 14:17
This should be resolved in #151005, but it is not part of 22.05, feel free to do a backport if you wish to.

**Comment by zendo** [comment] 2022-07-08 02:18
It works.

`  environment.gnome.excludePackages = with pkgs; [
    gnome-tour
    gnome.yelp
  ];`

**Comment by pxp9** [comment] 2022-07-08 10:53
> It works.
> 
> ` environment.gnome.excludePackages = with pkgs; [ gnome-tour gnome.yelp ];`

After doing this commands 
```bash
sudo nvim /etc/nixos/configuration.nix # editing that line that works for you 
sudo nix-channel --update
sudo nixos-rebuild switch
```
gnome tour still in my system.
Do i need to do something more ? @zendo

**Comment by zendo** [comment] 2022-07-08 11:06
It works in unstable channel, you need waitting **Backport 22.05** merge.

**Comment by pxp9** [comment] 2022-07-08 11:17
> It works in unstable channel, you need waitting for **Backport 22.05** merge.

Thank you @zendo

**Comment by bobby285271** [comment] 2022-07-10 15:51
I merged https://github.com/NixOS/nixpkgs/pull/180553, not sure why the issue is not auto-closed.

https://nixpk.gs/pr-tracker.html?pr=180553
You should get the fix when the backport reaches the channel you uses, feel free to re-open this if the issue persists.

**Closed by bobby285271** 2022-07-10 15:51 UTC
Labels: 0.kind: bug, 6.topic: nixos, 6.topic: GNOME

**Comment by pxp9** [comment] 2022-07-12 10:33
After waiting for being in Nixos 22.05,
Writing this in configuration.nix
```nix
environment.gnome.excludePackages = with pkgs; [
gnome-tour
];
```
And executing.
```bash
sudo nixos-rebuild switch --upgrade
```
That deleted Gnome-tour from my system.
Thank you for your support.

@bobby285271 
@zendo
