### ISSUE TITLE
vim_configurable packpath order

### ISSUE THREAD

**Issue by xunam** [NixOS/nixpkgs#85250] opened 2020-04-14 20:44 UTC
When using `vim_configurable` with custom packages (using Vim 8 native packages), the `packpath` setting lists the generated package folder *after* standard vim files. As a consequence, for instance, filetype plugins defined in packages cannot override default filetype plugins.

I spotted this issue when switching from a configuration with packages in `~/.vim/pack` to a new configuration with a custom vim built by nix using my set of packages. I use `vimtex` for LaTeX and it suddenly stopped loading automatically, reverting to the standard `tex` plugin, but still saying `:call vimtex#init()` did activate it.

The point of using packages is to extend the behaviour of default Vim, so it is only natural to load packages before default files.

**To Reproduce**
Steps to reproduce the behavior (I take the `vimtex` package as an example for illustration):
1. Define a customized vim package with the `vimtex` plugin, e.g. put this in your `config.nix` file:

    ```
    with import <nixpkgs> {}; {
      packageOverrides = pkgs: with pkgs; {
        myVim = vim_configurable.customize {
          name = "vim";
          vimrcConfig.packages.foo.start = [ pkgs.vimPlugins.vimtex ];
        };
      };
    }
    ```

2. Install it, e.g. `nix-env -iA nixos.myVim`
3. Edit a latex file: `vim a.tex`
4. Call a command specific command: `:VimtexInfo`

Then the command does not exist, which shows that the ftplugin was not activated.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.30, NixOS, 20.03beta1155.29eddfc36d7 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03beta1155.29eddfc36d7"`
 - channels(manu): `"nixos-19.09-19.09.2405.f6c1d3b113c, nixos-20.03-20.03beta1301.708cb6b307b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by doronbehar** [comment] 2020-08-04 21:15
I can't reproduce on current latest channels.

**Comment by NickHu** [comment] 2020-08-13 00:28
I believe that this was fixed in https://github.com/NixOS/nixpkgs/pull/78385 but your metadata hints that you might not have had this change merged in your channels. The solution would be for you to update. Please reopen if I'm mistaken.

**Closed by NickHu** 2020-08-13 00:28 UTC
Labels: 0.kind: bug, 6.topic: vim
