### ISSUE TITLE
Kontact not starting (Akonadi cannot be started)

### ISSUE THREAD

**Issue by ShalokShalom** [NixOS/nixpkgs#299153] opened 2024-03-26 11:02 UTC
### Describe the bug

I started with installing just Kontact. This lead me to discover, that Akonadi is not a dependency. Upon installing Akonadi, I ran into this issue: 

```
 kontact
Trying to create ksycoca...
kf.service.sycoca: The menu spec file ( "" ) contains a Layout or DefaultLayout tag without the mandatory Merge tag inside. Please fix it.
kf.service.sycoca: The menu spec file ( "" ) contains a Layout or DefaultLayout tag without the mandatory Merge tag inside. Please fix it.
qt.dbus.integration: Could not connect "org.freedesktop.NetworkManager" to "stateChanged" : Type not registered with QtDBus in parameter list: QNetworkManagerInterface::NMState
qt.dbus.integration: Could not connect "org.freedesktop.NetworkManager" to "connectivityChanged" : Type not registered with QtDBus in parameter list: QNetworkManagerInterface::NMConnectivityState
qt.dbus.integration: Could not connect "org.freedesktop.NetworkManager" to "deviceTypeChanged" : Type not registered with QtDBus in parameter list: QNetworkManagerInterface::NMDeviceType
qt.dbus.integration: Could not connect "org.freedesktop.NetworkManager" to "meteredChanged" : Type not registered with QtDBus in parameter list: QNetworkManagerInterface::NMMetered
org.kde.pim.akonadicore: "Unable to obtain agent type ''."
org.kde.pim.akonadicore: Failed SpecialCollectionsRequestJob::slotResult "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
org.kde.pim.mailcommon: "The Email program encountered a fatal error and will terminate now.\nThe error was:\nUnable to obtain agent type ''."
org.kde.pim.akonadicore: "Unable to obtain agent type ''."
org.kde.pim.akonadicore: Failed SpecialCollectionsRequestJob::slotResult "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
org.kde.pim.mailcommon: "The Email program encountered a fatal error and will terminate now.\nThe error was:\nUnable to obtain agent type ''."
org.kde.pim.akonadicore: Failed to request resource "" : "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
org.kde.pim.akonadicore: "Unable to obtain agent type ''."
org.kde.pim.akonadicore: Failed SpecialCollectionsRequestJob::slotResult "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
org.kde.pim.mailcommon: "The Email program encountered a fatal error and will terminate now.\nThe error was:\nUnable to obtain agent type ''."
org.kde.pim.akonadicore: Failed to request resource "" : "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
org.kde.pim.akonadicore: "Unable to obtain agent type ''."
org.kde.pim.akonadicore: Failed SpecialCollectionsRequestJob::slotResult "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
org.kde.pim.mailcommon: "The Email program encountered a fatal error and will terminate now.\nThe error was:\nUnable to obtain agent type ''."
org.kde.pim.akonadicore: Failed to request resource "" : "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
org.kde.pim.akonadicore: "Unable to obtain agent type ''."
org.kde.pim.akonadicore: Failed SpecialCollectionsRequestJob::slotResult "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
org.kde.pim.mailcommon: "The Email program encountered a fatal error and will terminate now.\nThe error was:\nUnable to obtain agent type ''."
org.kde.pim.akonadicore: Failed to request resource "" : "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
org.kde.pim.akonadicore: "Unable to obtain agent type ''."
org.kde.pim.akonadicore: Failed SpecialCollectionsRequestJob::slotResult "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
org.kde.pim.mailcommon: "The Email program encountered a fatal error and will terminate now.\nThe error was:\nUnable to obtain agent type ''."
org.kde.pim.akonadicore: Failed to request resource "" : "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
```

### Steps To Reproduce

https://paste.ee/p/F8zL3

### Expected behavior

Kontact starts

### Screenshots

![Screenshot_20240326_115835](https://github.com/NixOS/nixpkgs/assets/6344099/e2b480fe-927c-4173-93da-01892aebe294)

### Additional context

I added all the PIM related libraries I could find. The amount and lack of documentation makes it hard to determine, which ones are important. 

### Notify maintainers

@ilya-fedin 
@K900 
@LunNova 
@mjm 
@NickCao 
@SuperSandro2000 
@ttuegel 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.22, NixOS, 24.05 (Uakari), 24.05pre601756.44d0940ea560`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment] 2024-03-26 12:28
Are you using the full plasma 6 desktop?

**Comment by SuperSandro2000** [comment] 2024-03-26 13:20
```
# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # Bootloader.
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/sda";
  boot.loader.grub.useOSProber = true;

  networking.hostName = "nixos"; # Define your hostname.
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Enable networking
  networking.networkmanager.enable = true;

  # Set your time zone.
  time.timeZone = "Europe/Vienna";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "de_AT.UTF-8";
    LC_IDENTIFICATION = "de_AT.UTF-8";
    LC_MEASUREMENT = "de_AT.UTF-8";
    LC_MONETARY = "de_AT.UTF-8";
    LC_NAME = "de_AT.UTF-8";
    LC_NUMERIC = "de_AT.UTF-8";
    LC_PAPER = "de_AT.UTF-8";
    LC_TELEPHONE = "de_AT.UTF-8";
    LC_TIME = "de_AT.UTF-8";
  };

  # Enable the X11 windowing system.
  services.xserver.enable = true;

  # Enable the KDE Plasma Desktop Environment.
  services.xserver.displayManager.sddm.wayland.enable = true;
  services.xserver.displayManager.sddm.enable = true;
  services.desktopManager.plasma6.enable = true;

  # Configure keymap in X11
  services.xserver = {
    xkb.layout = "at";
    xkb.variant = "nodeadkeys";
  };

  # Enable CUPS to print documents.
  services.printing.enable = true;

  # Enable sound with pipewire.
  sound.enable = true;
  hardware.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    # If you want to use JACK applications, uncomment this
    #jack.enable = true;

    # use the example session manager (no others are packaged yet so this is enabled by default,
    # no need to redefine it in your config for now)
    #media-session.enable = true;
  };

  # Enable touchpad support (enabled default in most desktopManager).
  # services.xserver.libinput.enable = true;

  # Define a user account. Don&#039;t forget to set a password with ‘passwd’.
  users.users.cristof = {
    isNormalUser = true;
    description = "Cristof";
    extraGroups = [ "networkmanager" "wheel" ];
    packages = with pkgs; [
      audacity
      brave
      firefox
      gimp
      git
      hblock
      jamesdsp
      joplin
      kdePackages.akonadi
      kdePackages.akonadi-import-wizard
      kdePackages.dragon
      kdePackages.kcalc
      kdePackages.kdepim-addons
      kdePackages.kdenlive
      kdePackages.kontact
      kdePackages.libkdepim
      kdePackages.pimcommon
      kdePackages.pim-data-exporter
      kdePackages.yakuake
      libreoffice
      qbittorrent
      telegram-desktop
      thunderbird
      signal-desktop
    ];
  };

    programs.firefox = {
    enable = true;
    preferences = {
      "widget.use-xdg-desktop-portal.file-picker" = 1;
    };
  };

  # Enable automatic login for the user.
  services.xserver.displayManager.autoLogin.enable = true;
  services.xserver.displayManager.autoLogin.user = "cristof";

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
  ];

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  # programs.mtr.enable = true;
  # programs.gnupg.agent = {
  #   enable = true;
  #   enableSSHSupport = true;
  # };

  # List services that you want to enable:

  # Enable the OpenSSH daemon.
  # services.openssh.enable = true;

  # Open ports in the firewall.
  # networking.firewall.allowedTCPPorts = [ ... ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  # Or disable the firewall altogether.
  # networking.firewall.enable = false;

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "24.05"; # Did you read the comment?

}
```

**Comment by ShalokShalom** [comment] 2024-03-26 13:23
So what does this say about this issue? 🙂

**Comment by SuperSandro2000** [comment] 2024-03-27 09:58
That Is this related to https://github.com/NixOS/nixpkgs/issues/38887#issuecomment-1450355870?

**Comment by SuperSandro2000** [comment] 2024-03-27 10:06
Duplicate of #266565 which suggests to install ``kdepim-runtime``

**Closed by SuperSandro2000** 2024-03-27 10:06 UTC
Labels: 0.kind: bug
