### ISSUE TITLE
GNOME Shell forgets about running Chromium (spawns new instances)

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#12433] opened 2016-01-16 23:24 UTC
Somewhere between NixOS 15.09 and unstable, GNOME Shell became unaware whether or not it already has a running Chromium instance. This means it will spawn a _new_ Chromium instance each time I try to go jump back to my existing instance (with Super + "chro[...]").

Other programs are handled just fine (like "Terminal"), so I suspect this issue is due to a change in the chromium package and not gnome.

(Does anyone know how GNOME Shell finds out whether a program is currently running?)

**Comment by lethalman** [comment] 2016-01-16 23:36
Application instances are handled by the program itself. Maybe you have a different chromium in your user/system profile?

**Comment by bjornfor** [comment] 2016-01-16 23:47
I only have chromium in systemPackages.

Initially I had a chromium installed in my user profile too, but I removed it before I went on to boot into 15.09 and unstable. (I.e. before I wrote this issue.)

@lethalman: Does this mean you don't have this issue on your system?

**Comment by bjornfor** [comment] 2016-01-17 08:34
Oh, now release-15.09 is affected too (yesterday I updated to b4c64b9f375c5810f3d84ed5130fd5917dff0dbf).

**Comment by lethalman** [comment] 2016-01-17 12:06
@bjornfor activities -> chromium -> does not open a new instance.

**Comment by jgillich** [comment] 2016-01-17 12:11
I also cannot reproduce using Chrome (doubt Chromium would make a difference).

**Comment by lethalman** [comment] 2016-01-17 12:12
Right click on chromium in activities... it should show the existing window.

**Comment by lethalman** [comment] 2016-01-17 12:13
Also chromium should be in the left bar in activities, too.

**Comment by bjornfor** [comment] 2016-01-17 15:30
git bisect on release-15.09 points to commit e905ad130541b4e8b17c649a1c40c8591619ecf6 ("chromium: Updates, fixes #11492"). From that commit and onwards, only new chromium instances will be created in GNOME Shell.

The commit updates Chromium from 45.0.2454.101 to 47.0.2526.73. Nothing in that commit looks suspicious, so I guess Chromium itself broke this :-(

**Comment by jgillich** [comment] 2016-01-17 16:06
Actually I was wrong, I can reproduce it. Doesn't matter whether I install it in the user or system profile.

**Comment by Profpatsch** [comment] 2016-02-27 21:04
(triage) Does this still happen?

**Comment by bjornfor** [comment] 2016-02-29 18:34
Still happens on unstable branch as of today (commit 40c586b). I tried latest master but there are (unrelated) build errors preventing me from testing it.

**Comment by lethalman** [comment] 2016-02-29 19:25
I can confirm this too now.

**Comment by lethalman** [comment] 2016-02-29 19:31
Maybe relevant: https://bugs.chromium.org/p/chromium/issues/detail?id=174794

**Comment by lethalman** [comment] 2016-02-29 19:43
Seems to be fixed in 5f8311775c8832b1c5a88576cf58be05fd5c9070

**Closed** 2016-02-29 19:43 UTC
Labels: 0.kind: bug, 6.topic: nixos

**Comment by bjornfor** [comment] 2016-02-29 19:46
@lethalman: Excellent! Thank you.
