### ISSUE TITLE
gnucash missing on-line help documentation

### ISSUE THREAD

**Issue by winny-** [NixOS/nixpkgs#260564] opened 2023-10-12 00:49 UTC
### Describe the bug
Cannot load gnucash documentation (Help->Contents, Help->Tutorials & Concepts Guide) because it does not appear to be installed in the derivation.

Compare with the debian gnucash package for documentation: https://packages.debian.org/bookworm/all/gnucash-docs/filelist

Compare to what is shipped with the built derivation (notice the missing tutorials, guides, online help files): https://gist.github.com/winny-/0c6ab89f39a5e177194700788eb35bd5

### Steps To Reproduce
1. Set up gnucash, make sure to enable dconf too!
2. Try to access local on-line documentation via the Help menu.

### Expected behavior
Documentation appears in the user's preferred documentation viewer.  (On KDE it appears to be "Help Center").

### Screenshots

![Screenshot_20231011_194113](https://github.com/NixOS/nixpkgs/assets/3893828/ba47a385-eae4-4c9f-924c-7fe585659ca6)

![image](https://github.com/NixOS/nixpkgs/assets/3893828/6b4e5313-1135-49ec-a7e1-2379fcd7849d)

### Notify maintainers
 @domenkozar @AndersonTorres @rski @nevivurn

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
winston@icarus ~ $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.05 (Stoat), 23.05.20230927.e3f57c8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - nixpkgs: `/nix/store/x87x8b1dfvmzwgapjqphkgw27am77b37-source`
```

**Comment by nevivurn** [comment] 2023-10-13 08:22
Seems like a duplicate of #60361
I think I've got something working, so I'll probably send a PR soon.

**Closed by nevivurn** 2023-10-13 08:22 UTC
Labels: 0.kind: bug, 2.status: duplicate
