### ISSUE TITLE
Patch upstream to correctly handle install_data/data_files in Python

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#4968] opened 2014-11-12 20:59 UTC
See https://bitbucket.org/pypa/setuptools/issue/130/install_data-doesnt-respect-prefix

This is currently needed for some packages like `xpra`.
- [ ] update Python docs
- [ ] fix packages using the current workaround
- [ ] open PR upstream

Current workaround for `xpra`: https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/X11/xpra/default.nix#L45

**Comment by Profpatsch** [comment] 2016-08-16 19:41
(triage) status?

**Comment by domenkozar** [comment] 2016-08-16 19:44
Still needs to be fixed upstream: https://github.com/pypa/setuptools/issues/130

**Comment by Profpatsch** [comment] 2018-06-24 00:17
Still needs to be fixed upstream …
@domenkozar what do you think, if it’s just one line, why don’t we patch it?

**Comment by FRidh** [comment] 2019-08-31 13:19
Since this issue was opened we've changed how we install packages (we use wheels since 2015). Even so, the issue is still valid. See e.g. https://github.com/NixOS/nixpkgs/issues/23438. Closing this one in favor of that issue.

**Closed by FRidh** 2019-08-31 13:19 UTC
Labels: 0.kind: enhancement, 6.topic: python
