### ISSUE TITLE
server/trafficserver: 9.0.0

### ISSUE THREAD

**Issue by heroku-miraheze** [NixOS/nixpkgs#113016] opened 2021-02-13 16:53 UTC
**Project description**
Apache Traffic Server

**Metadata**

* homepage URL: https://trafficserver.apache.org
* source URL: https://downloads.apache.org/trafficserver/trafficserver-9.0.0.tar.bz2
* license: gpl2+
* platforms: unix

**Comment by dotlambda** [comment] 2021-02-23 11:53
duplicate of https://github.com/NixOS/nixpkgs/issues/111750

**Closed by dotlambda** 2021-02-23 11:53 UTC
Labels: 0.kind: packaging request
