### ISSUE TITLE
Package request: raze

### ISSUE THREAD

**Issue by keenanweaver** [NixOS/nixpkgs#231130] opened 2023-05-10 18:21 UTC
**Project description**

Raze is a fork of Build engine games backed by GZDoom tech

**Metadata**

* homepage URL:
* source URL: https://github.com/ZDoom/Raze
* license: gpl2
* platforms: linux

**Comment by pinn3** [comment] 2023-05-10 18:25
Duplicate of https://github.com/NixOS/nixpkgs/issues/189163

**Closed** 2023-05-24 19:41 UTC
Labels: 0.kind: packaging request
