### ISSUE TITLE
Building GHC 8.8.4 on AArch64 fails with a segfault

### ISSUE THREAD

**Issue by golddranks** [NixOS/nixpkgs#97421] opened 2020-09-08 05:05 UTC
**Describe the bug**
GHC 8.8.4 is the default Haskell compiler at the moment. When building it, apparently for bootstrapping, it first builds `/nix/store/wm7l4xaq4jk8w5r9kscb4h6cibjqccjz-ghc-8.6.5-binary.drv`, which fails with the following message: 
```
running install tests
/nix/store/khaz6yssv0bf5xidnp64dd5gra88ldba-stdenv-linux/setup: line 1310:  3361 Segmentation fault      (core dumped) $out/bin/ghc --make main.hs
builder for '/nix/store/wm7l4xaq4jk8w5r9kscb4h6cibjqccjz-ghc-8.6.5-binary.drv' failed with exit code 1
cannot build derivation '/nix/store/gjvc4nqn2846sfh43apvw9j77ljkk5bc-ghc-8.8.4.drv': 1 dependencies couldn't be built
error: build of '/nix/store/gjvc4nqn2846sfh43apvw9j77ljkk5bc-ghc-8.8.4.drv' failed
```

**To Reproduce**
1. Be on AArch64 machine.
2. Type
```
# nix-env -iA nixos.ghc
```
3. It starts building and eventually fails:
```
installing 'ghc-8.8.4'
these derivations will be built:
  /nix/store/wm7l4xaq4jk8w5r9kscb4h6cibjqccjz-ghc-8.6.5-binary.drv
  /nix/store/isi8yakzzzxgw3zdz7vz4c505l8dblhk-happy-1.19.12.drv
  /nix/store/77h3d2j7hhhipdh5nn3prwlxdpfsbxas-alex-3.2.5.drv
  /nix/store/w4cs5p873i01aw54vxf6bdmbijzz3y8a-hscolour-1.24.4.drv
  /nix/store/zmjw3s0qdizjxs6kkgmwxz9yd0yg9vb5-hscolour-1.24.4.drv
  /nix/store/gjvc4nqn2846sfh43apvw9j77ljkk5bc-ghc-8.8.4.drv
building '/nix/store/wm7l4xaq4jk8w5r9kscb4h6cibjqccjz-ghc-8.6.5-binary.drv'...
```

**Expected behavior**
I expect the build to succeed.

**Additional context**
Reproduced both on Raspberrpy Pi 4 and AWS Graviton 2.

**Notify maintainers**
@MarcWeber 
@peti 

**Metadata**
```
# nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 5.4.48, NixOS, 20.03.2351.f8248ab6d9e (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.09pre242714.a31736120c5, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by zowoq** [comment] 2020-09-08 07:27
Looks like this is a duplicate of #97407?

**Closed** 2020-09-08 10:38 UTC
Labels: 0.kind: bug
