### ISSUE TITLE
Package request: waveterm

### ISSUE THREAD

**Issue by RashiqAzhan** [NixOS/nixpkgs#297292] opened 2024-03-19 23:27 UTC
**Project description**

Add support for waveterm.

**Metadata**

* homepage URL: https://www.waveterm.dev/
* source URL: https://github.com/wavetermdev/waveterm
* license:  Apache License Version 2.0
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-03-19 23:32
duplicate of #280566

**Closed by eclairevoyant** 2024-03-19 23:32 UTC
Labels: 0.kind: packaging request
