### ISSUE TITLE
ZERO Hydra Failures 22.05

### ISSUE THREAD

**Issue by dasJ** [NixOS/nixpkgs#172160] opened 2022-05-09 10:03 UTC
## Mission
Every time we branch off a release we stabilize the release branch.
Our goal here is to get as little as possible jobs failing on the trunk/master jobsets.
We call this effort "Zero Hydra Failure".
I'd like to heighten, while it's great to focus on zero as our goal, it's essentially to 
have all deliverables that worked in the previous release work here also.

Please note the changes included in [RFC 85](https://github.com/NixOS/rfcs/blob/master/rfcs/0085-nixos-release-stablization.md).

Most significantly, branch off will occur on 2022 May 22; prior to that date, ZHF will be conducted
on master; after that date, ZHF will be conducted on the release channel using a backport
workflow similar to previous ZHFs.

## Jobsets

[trunk Jobset](https://hydra.nixos.org/jobset/nixpkgs/trunk) (includes linux, darwin, and aarch64-linux builds)
[nixos/combined Jobset](https://hydra.nixos.org/jobset/nixos/trunk-combined) (includes many nixos tests)

## How to help (textual)
1. Select an evaluation of the [trunk jobset](https://hydra.nixos.org/jobset/nixpkgs/trunk)
![Screenshot](https://user-images.githubusercontent.com/7673602/117478795-701baa00-af14-11eb-8a82-8a846b464cce.png)

2.  Find a failed job ❌️ , you can use the filter field to scope packages to your platform, or search for packages that are relevant to you.
![Screenshot from 2020-02-08 15 26 47](https://user-images.githubusercontent.com/28888242/74192277-3978b600-4c23-11ea-9f35-19a3988dd502.png)
Note: you can filter for architecture by filtering for it, eg: https://hydra.nixos.org/eval/1719540?filter=x86_64-linux&compare=1719463&full=#tabs-still-fail

3. Search to see if a PR is not already open for the package. It there is one, please help review it.

4. If there is no open PR, troubleshoot why it's failing and fix it.

5. Create a Pull Request with the fix targeting master, wait for it to be merged. 
If your PR causes around 500+ rebuilds, it's preferred to target `staging` to avoid compute and storage churn. If your PR is fixing Haskell packages, target the `haskell-updates` branch instead.

6. (after 2022 May 22) Please follow [backporting steps](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#backporting-changes) and target the `release-22.05` branch if the original PR landed in `master` or `staging-22.05` if the PR landed in `staging`. Be sure to do `git cherry-pick -x <rev>` on the commits that landed in unstable. @jonringer created [a video covering the backport process](https://www.youtube.com/watch?v=4Zb3GpIc6vk&t=520s).

Always reference this issue in the body of your PR:
```
ZHF: #172160
```

Please ping @NixOS/nixos-release-managers on the PR and add the `0.kind: build failure` label to the pull request.
If you're unable to because you're not a member of the NixOS org please ping @dasJ, @tomberek, @jonringer, @Mic92

## How can I easily check packages that I maintain?

I have created an experimental website that automatically crawls Hydra and lists packages by maintainer and lists the most important dependencies (failing packages with the most dependants).
You can reach it here: https://zh.fail

If you prefer the command-line way, you can also check failing packages that you maintain by running:
```
# from root of nixpkgs
nix-build maintainers/scripts/build.nix --argstr maintainer <name>
```

## New to nixpkgs?
- [Packaging a basic C application](https://www.youtube.com/watch?v=LiEqN8r-BRw)
- [Python nix packaging](https://www.youtube.com/watch?v=jXd-hkP4xnU)
- [Adding a package to nixpkgs](https://www.youtube.com/watch?v=fvj8H5yUKu8)
- other resources at: https://github.com/nix-community/awesome-nix
- https://nix.dev/tutorials/

## Packages that don't get fixed
The remaining packages will be marked as broken before the release (on the failing platforms).
You can do this like:
```nix
meta = {
  # ref to issue/explanation
  # `true` is for everything
  broken = stdenv.isDarwin; 
};
```

## Closing
This is a great way to help NixOS, and it is a great time for new contributors to start their nixpkgs adventure.  :partying_face: 

As with the [feature freeze issue](https://github.com/NixOS/nixpkgs/issues/167025), please keep discussion here to a minimal so you don't ping all maintainers (although relevant comments can of course be added here if they are directly ZHF-related) and ping me or the release managers team in the respective issues.

cc @NixOS/nixpkgs-committers @NixOS/nixpkgs-maintainers @NixOS/release-engineers

## Related Issues
- Timeline: #165792
- Feature Freeze Items: #167025

**Comment by raboof** [comment] 2022-05-09 10:18
Perhaps we should tag PR's that fix hydra failures with `0.kind: build failure` to encourage reviewing? https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%220.kind%3A+build+failure%22

**Comment by GuillaumeDesforges** [comment] 2022-05-09 12:12
The [packages I maintain](https://zh.fail/failed/by-maintainer/GuillaumeDesforges.html) have on Hydra the errors

> OSError: Too many open files

But they build ok on nixpkgs master locally.

Example: [https://hydra.nixos.org/build/175654425/nixlog/1/tail](https://hydra.nixos.org/build/175654425/nixlog/1/tail)

Not sure of what I can do on my end.

**Comment by vcunat** [comment] 2022-05-09 12:19
I restarted some, but [that scipy build](https://hydra.nixos.org/build/174843070) failed many times in a row so there it doesn't seem to make sense.  I'd suggest to try skipping tests that do similar problems.

**Comment by sternenseemann** [comment] 2022-05-09 12:21
For Haskell, please remember to target any PRs to the `haskell-updates` branch!

Since we've already marked (most) failures as broken, you need to check manually if your favorite package still works, instead of looking at failed builds on Hydra.

Additionally here is a list of more prominent problems (of Hakell packages exposed via top level `pkgs`) to look into, note that some of these are unmaintained and probably not worth fixing / should be removed in the long run.

* [ ] `hyper-haskell` (a problem here is also the electron version used)
* [ ] `jl`
* [ ] (`hasura-graphql-engine`, mostly blocked on upstream)
* [ ] `krank`
* [ ] `cedille`
* [ ] `diagrams-builder`
* [ ] `glirc`
* [ ] `hedgewars` (exception: fix can go to master)
* [ ] `icepeak`
* [ ] `madlang`
* [ ] `nix-delegate`
* [ ] `nix-deploy`
* [ ] `stack2nix`
* [ ] `stutter`
* [ ] `tweet-hs`

**Comment by KarlJoad** [comment] 2022-05-11 22:42
Most Octave packages are broken because of a change in the way Octave handles it packages. #168943 has further discussion of this issue.

**Comment by risicle** [comment] 2022-05-15 19:15
https://zh.fail/ is cool but I think we may be needing a logarithmic y-axis before long...

**Comment by neilmayhew** [comment] 2022-05-15 19:53
I've created an upstream [PR](https://github.com/chrisdone/jl/pull/23) for `jl`.

**Comment by Mathnerd314** [comment] 2022-05-15 20:04
> a logarithmic y-axis

That won't work, when we get to 0 the graph will be at negative infinity. We would need a [symmetric log plot](https://en.wikipedia.org/wiki/Logarithmic_scale#Extensions).

**Comment by risicle** [comment] 2022-05-15 20:22
If/when we get to 0 I'm perfectly happy for the graph to explode, in fact it would be a fitting celebration.

**Comment by vcunat** [comment] 2022-05-17 10:51
[staging-next](https://github.com/NixOS/nixpkgs/pull/172729) merged now.

- [ ] One notable regression is that [gnat bootstrap broke down](https://hydra.nixos.org/build/176567567), probably after pulling maintenance patches into glibc.  I tried some simple stuff like tweaking hardening flags and autoreconf, but it didn't help.  Perhaps some of you will have an idea, ideally in the form of a PR.

**Comment by 06kellyjac** [comment] 2022-05-17 12:33
looks like the pandas fix (#173177) missed that staging-next merge? does that mean it wont make release?

**Comment by ncfavier** [comment] 2022-05-17 12:43
If I'm reading the release schedule correctly, there's still a staging-next iteration left before branch-off.

**Comment by Madouura** [comment] 2022-05-18 20:57
tinygo should be fixed with #172160

**Comment by Ma27** [comment] 2022-05-20 12:04
#166817 fixes privacyidea and is nwo ready to review :)

**Comment by trofi** [comment] 2022-05-20 15:01
Filed upstream bug as https://sourceware.org/PR29162 for `gnat` / `glibc` incompatibility.

**Comment by schuelermine** [comment] 2022-05-20 18:23
I don’t see a filter option on the hydra page. How can I filter for failed jobs on my system?

![Screenshot from 2022-05-20 20-23-20](https://user-images.githubusercontent.com/48802534/169589767-6a36cdf4-d5e4-4cd0-b966-f1532af790a2.png)

**Comment by vcunat** [comment] 2022-05-20 18:51
@schuelermine: that's the "search jobs by name" field.  (you could directly edit the URL, too)

**Comment by schuelermine** [comment] 2022-05-20 20:03
What’s the syntax for filters?

**Comment by vcunat** [comment] 2022-05-20 20:25
None.  Contiguous substring, or how would I call the matching.

**Comment by schuelermine** [comment] 2022-05-20 20:28
Oh, that’s unintuitive. I would expect “search jobs by name” to search by name *only*

**Comment by dasJ** [comment] 2022-05-23 20:34
`release-22.05` has been branched off so remember to also add the `backport release-22.05` to your Pull Requests :tada:

**Comment by cab404** [comment] 2022-05-28 01:12
I've kinda put down a list of packages broken with stdenv update
https://gist.github.com/cab404/96259f25450d778e744108c0ea9bfaa8
it’s parsed from hydra outputs with smth like that
```
document.querySelector("#tabs-now-fail > table:nth-child(1) > tbody:nth-child(2)").filter((e) => e.getElementsByClassName("build-status")[0].attributes["alt"].value === "Failed" ).filter((e) => e.children[5].textContent === "x86_64-linux").map((r) => r.children[2].textContent)
```

**Closed** 2022-05-30 19:12 UTC
Labels: 6.topic: release process

**Comment by mweinelt** [comment] 2022-11-21 20:31
The `branch-off` just happened. Remember to add the backport labels for either `release-22.11` or ` staging-22.11` for changes that should be included in the release.
