### ISSUE TITLE
systemd unit doesn't report IP traffic

### ISSUE THREAD

**Issue by andir** [NixOS/nixpkgs#104070] opened 2020-11-17 17:39 UTC
**Describe the bug**
Systemd is supposed to account IP traffic for all units that are being ran. Currently when I run `systemctl status someunit.service` it returns `[…]IP: 0B in, 0B out[…]` regardless of the amount of traffic the unit has already made.

**To Reproduce**
1. `systemctl status systemd-timesyncd.service | grep IP:`

**Expected behavior**
I would expect to see any number of bytes being displayed but not zero.

**Additional context**
This is happening on 20.09 as well as on unstable.

**Notify maintainers**
@NixOS/systemd 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.2, NixOS, 21.03pre251971.a371c107116 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(root): `"nixos-21.03pre251971.a371c107116"`
 - channels(andi): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Also happening on this 20.09 revision: f41c0fc7d8e49d94220f74495d4d702922df2a67

**Comment by arianvp** [comment] 2020-11-17 17:44
Just for completeness sake. I assume you did set `IPAccounting=yes` on the respective unit or set `DefaultIPAccounting=yes` in `systemd.conf`?

**Comment by arianvp** [comment] 2020-11-17 17:45
I at least can not reproduce on unstable, the accounting works fine here.

```
 systemd-timesyncd.service - Network Time Synchronization
     Loaded: loaded (/nix/store/8zd3z4az6y3caga8aw3ip2cp2iv82vjq-systemd-246.6/example/systemd/system/systemd-timesyncd.service; enabled; vendor preset: enab>
    Drop-In: /nix/store/pznszdh9b17h3ji6kj65zcx7a4a65kp1-system-units/systemd-timesyncd.service.d
             └─overrides.conf
     Active: active (running) since Tue 2020-11-17 14:44:15 CET; 4h 0min ago
       Docs: man:systemd-timesyncd.service(8)
   Main PID: 1039 (systemd-timesyn)
     Status: "Initial synchronization to time server [2a02:c207:3005:4701::1]:123 (2.nixos.pool.ntp.org)."
         IP: 1.5K in, 1.3K out
         IO: 96.0K read, 0B written
      Tasks: 2 (limit: 4915)
     Memory: 2.3M
        CPU: 38ms
     CGroup: /system.slice/systemd-timesyncd.service
             └─1039 /nix/store/8zd3z4az6y3caga8aw3ip2cp2iv82vjq-systemd-246.6/lib/systemd/systemd-timesyncd


```

**Comment by NinjaTrappeur** [comment] 2020-11-17 20:32
Same, I can't reproduce on unstable nor 20.09:

```
~ » systemctl status systemd-timesyncd.service| grep IP
         IP: 1014B in, 3.8K out
```

**Comment by andir** [comment] 2020-11-19 09:57
> Just for completeness sake. I assume you did set `IPAccounting=yes` on the respective unit or set `DefaultIPAccounting=yes` in `systemd.conf`?

No I did not but @flokli assured me it should be the default on our systems.

**Comment by flokli** [comment] 2020-11-19 10:52
See f34f38ef1c0d2e9e5d985d266cfff84e17312fd1.

**Comment by flokli** [comment] 2020-11-19 10:55
Can you try the updated VM test from https://github.com/NixOS/nixpkgs/pull/104094, but with non-unified cgroup hierarchy (so without the systemd changes introduced there)?

With cgroupsv2, IPAccounting should certainly work on a per-unit basis, and that test proves this.

**Comment by flokli** [comment] 2020-11-24 16:47
There's a staging-next PR open with the unified cgroup changes in https://github.com/NixOS/nixpkgs/pull/104781. This can issue here can probably be closed once it's merged.

**Comment by flokli** [comment] 2020-12-22 14:29
The fix has been merged into `master`, and the test succeeds. Let's close this one.

**Closed by flokli** 2020-12-22 14:29 UTC
Labels: 0.kind: bug
