### ISSUE TITLE
Packaging request: Meshroom

### ISSUE THREAD

**Issue by pbsds** [NixOS/nixpkgs#171324] opened 2022-05-02 23:07 UTC
**Project description**
Meshroom is a free, open-source 3D Reconstruction and Photogrammetry Software based on the AliceVision framework.
It features both a graphical interface as well as a command-line interface.

Youtube:
[![Youtube thumbnail](https://img.youtube.com/vi/v_O6tYKQEBA/0.jpg)](https://www.youtube.com/watch?v=v_O6tYKQEBA)

**Metadata**

* homepage URL: https://alicevision.org/#meshroom
* source URL: https://github.com/alicevision/meshroom
* license: mpl2
* platforms: unix

**Additional notes**
AUR packages:

* https://aur.archlinux.org/packages/meshroom
* https://aur.archlinux.org/packages/meshroom-git
* https://aur.archlinux.org/packages/meshroom-bin

Related tool already in nixpkgs: [colmap](https://demuc.de/colmap/)

**Comment by Majiir** [comment] 2022-08-15 16:59
This is a duplicate of https://github.com/NixOS/nixpkgs/issues/94127 which links to some prior work. It would be great to get Meshroom running on NixOS.

**Closed** 2023-02-14 21:17 UTC
Labels: 0.kind: packaging request
