### ISSUE TITLE
Package request: thorium

### ISSUE THREAD

**Issue by steledama** [NixOS/nixpkgs#265756] opened 2023-11-06 00:19 UTC
**The fastest browser on Earth**

**browser**

* homepage URL: https://thorium.rocks/
* source URL: https://github.com/Alex313031/Alex313031.github.io
* license: mit, bsd, gpl2+ , ...
* platforms: linux, arm, raspeberry,

**Comment by eclairevoyant** [comment] 2023-11-06 02:28
dupe of #184823

**Closed by eclairevoyant** 2023-11-06 02:28 UTC
Labels: 0.kind: packaging request
