### ISSUE TITLE
LIBCLANG_PATH environment variable from inside .nix expression

### ISSUE THREAD

**Issue by nixbitcoin** [NixOS/nixpkgs#52447] opened 2018-12-17 18:07 UTC
## Issue description
I'm running into this issue building a nix expression I wrote with nix-build.
```
error: failed to run custom build command for `librocksdb-sys v5.14.2`
process didn't exit successfully: `/tmp/nix-build-electrs-0.4.2.drv-0/source/target/release/build/librocksdb-sys-b927be1902a306da/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any of [\'libclang.so\', \'libclang.so.*\', \'libclang-*.so\'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (skipped: [])"', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

builder for '/nix/store/8gwgvvbzpzsspl739r055fb7gm1fk2m2-electrs-0.4.2.drv' failed with exit code 101
error: build of '/nix/store/8gwgvvbzpzsspl739r055fb7gm1fk2m2-electrs-0.4.2.drv' failed
```
If I were installing this manually I would just set the environment variable with `export LIBCLANG_PATH = /nix/store/$path-to-libclang.so`. How can I do this from inside the nix expression across different versions of libclang?

### Steps to reproduce

Run nix-build on:
```
with import <nixpkgs> {};

rustPlatform.buildRustPackage rec {
  name = "electrs-${version}";
  version = "0.4.2";

  src = fetchFromGitHub {
    owner = "romanz";
    repo = "electrs";
    rev = "5f2d4289dcb98ef283725b3d12f8733a7b9e832b";
    sha256 = "1lqhrcyd8hdaja5k01a2banvjcbxxcwvb2p7zh05984fpzzs02gr";
  };

  cargoSha256 = "0v0cc62mx728cqfyz3x1bfh2436yiw2hkv58672j2f45cafcgp2h";

  nativeBuildInputs = [clang];

  meta = with stdenv.lib; {
    description = "An efficient re-implementation of Electrum Server in Rust ";
    homepage = https://github.com/romanz/electrs;
    maintainers = [ maintainers.tailhook ];
    platforms = platforms.all;
  };
}
```

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.74-1.pvops.qubes.x86_64, Debian GNU/Linux, 9 (stretch)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(user): `"nixpkgs-19.03pre161900.61c3169a0e1"`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`
```

**Comment by thoughtpolice** [comment] 2018-12-17 22:16
Import some variant of `llvmPackages` (such as the default `llvmPackages`, or `llvmPackages_7`, `llvmPackages_6`, `llvmPackages_5`, etc), then, inside your expression:

```nix
buildRustPackage rec {
  name = "foobar-${version}";
  version = "0.1.0";
  src = lib.cleanSource ./.;

  # Needed so bindgen can find libclang.so
  LIBCLANG_PATH="${llvmPackages.libclang}/lib";

  buildInputs = [ stdenv.cc.libc systemd libftdi1 ];
  cargoSha256 = "12mv4hl35grp6xawr3i29w7p1k8v0gaai5slakxvr4g4npci52hg";
```

If you make your expression take an `llvmPackages` parameter explicitly, then you can override the parameter with `callPackage` at some other call site, e.g.

```nix
   my_project = pkgs.callPackage ./default.nix { llvmPackages = llvmPackages_5; }
```

This is from a private project of mine that uses `bindgen` for `libftdi1` -- it's necessary for `bindgen` to find `libclang.so`, but it should work. Note that if you are using `bindgen` you will also absolutely have to pass `NIX_CFLAGS_COMPILE` from the build environment to the build script, otherwise, bindgen will be unable to find the location of header files to import (they must be passed into the environment after the necessary `/nix/store` paths have been resolved by the evaluator). For example, my `build.rs` looks something like

```rust
extern crate bindgen;

use std::env;
use std::path::PathBuf;

fn main() {
    println!("cargo:rustc-link-lib=ftdi1");

    // TODO FIXME: make optional
    let nix_cflags = env::var("NIX_CFLAGS_COMPILE").unwrap();
    let bindings = bindgen::Builder::default()
        .header("libftdi1/ftdi.h")
        .clang_args(nix_cflags.split(" "))
        .generate()
        .expect("Unable to generate bindings");

    // Write the bindings to the $OUT_DIR/bindings.rs file.
    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
    bindings
        .write_to_file(out_path.join("ftdi_bindings.rs"))
        .expect("Couldn't write bindings!");
}
```

**Comment by nixbitcoin** [comment] 2018-12-18 18:50
Adding LIBCLANG_PATH="${llvmPackages.libclang}/lib"; to my electrs.nix like so
```
with import <nixpkgs> {};

rustPlatform.buildRustPackage rec {
  name = "electrs-${version}";
  version = "0.4.2";

  src = fetchFromGitHub {
    owner = "romanz";
    repo = "electrs";
    rev = "5f2d4289dcb98ef283725b3d12f8733a7b9e832b";
    sha256 = "1lqhrcyd8hdaja5k01a2banvjcbxxcwvb2p7zh05984fpzzs02gr";
  };

  cargoSha256 = "0v0cc62mx728cqfyz3x1bfh2436yiw2hkv58672j2f45cafcgp2h";

  LIBCLANG_PATH="${llvmPackages.libclang}/lib";
  buildInputs = [ clang ];

  meta = with stdenv.lib; {
    description = "An efficient re-implementation of Electrum Server in Rust ";
    homepage = https://github.com/romanz/electrs;
    maintainers = [ maintainers.tailhook ];
    platforms = platforms.all;
  };
}
```
solved the issue.

Now I'm getting an issue resulting from not having a rust nightly version.
```
warning: redundant linker flag specified for library `stdc++`

   Compiling rocksdb v0.10.1
   Compiling electrs v0.4.2 (/tmp/nix-build-electrs-0.4.2.drv-0/source)
error: Edition 2018 is unstable and only available for nightly builds of rustc.

error: Could not compile `electrs`.

To learn more, run the command again with --verbose.
builder for '/nix/store/xkzy7izkx2w86jqvpjndz992f8m05h8v-electrs-0.4.2.drv' failed with exit code 101
```
What is the easiest way to integrate rust nightly into a nix expression?

**Closed** 2018-12-25 12:39 UTC

**Comment by jkryl** [comment] 2021-06-01 12:20
Just an update: with recent version of nixpkgs libclang has multiple outputs and lib output has to be used explicitly:
```diff
-    LIBCLANG_PATH = "${llvmPackages.libclang}/lib";
+    LIBCLANG_PATH = "${llvmPackages.libclang.lib}/lib";
```

**Comment by cassandracomar** [comment] 2021-06-02 22:41
that fix alone doesn't appear to fix this:

```
cpp -v /dev/null -o /dev/null                                                                ~/src/github.com/getditto/ditto/hydra
clang version 10.0.1 
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /nix/store/4x92wsm6f18mxrrqb5pxl81swlm9mbpf-clang-10.0.1/bin
 (in-process)
 "/nix/store/4x92wsm6f18mxrrqb5pxl81swlm9mbpf-clang-10.0.1/bin/clang-10" -cc1 -triple x86_64-unknown-linux-gnu -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name null -mrelocation-model static -mthread-model posix -mframe-pointer=all -fmath-errno -fno-rounding-math -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu x86-64 -dwarf-column-info -fno-split-dwarf-inlining -debugger-tuning=gdb -v -nostdsysteminc -resource-dir /nix/store/4x92wsm6f18mxrrqb5pxl81swlm9mbpf-clang-10.0.1/lib/clang/10.0.1 -internal-isystem /nix/store/4x92wsm6f18mxrrqb5pxl81swlm9mbpf-clang-10.0.1/lib/clang/10.0.1/include -fdebug-compilation-dir /home/cassandra/src/github.com/getditto/ditto/hydra -ferror-limit 19 -fmessage-length 0 -fgnuc-version=4.2.1 -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -faddrsig -o /dev/null -x c /dev/null
clang -cc1 version 10.0.1 based upon LLVM 10.0.1 default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/nix/store/4x92wsm6f18mxrrqb5pxl81swlm9mbpf-clang-10.0.1/lib/clang/10.0.1/include"
#include "..." search starts here:
End of search list.
```

the nonexistent directory referenced here is the old "${llvmPackages.libclang}/lib" so a bunch of header files appear to be missing, especially when compiling librocksdb-sys as in the OP:

```
   Compiling librocksdb-sys v6.17.3
error: failed to run custom build command for `librocksdb-sys v6.17.3`

Caused by:
  process didn't exit successfully: `./target/debug/build/librocksdb-sys-6c487f410fda9372/build-script-build` (exit code: 101)
  --- stderr
  rocksdb/include/rocksdb/c.h:65:10: fatal error: 'stdarg.h' file not found
  rocksdb/include/rocksdb/c.h:65:10: fatal error: 'stdarg.h' file not found, err: true
  thread 'main' panicked at 'unable to generate rocksdb bindings: ()', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/librocksdb-sys-6.17.3/build.rs:44:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I managed to fix this locally by setting `BINDGEN_EXTRA_CLANG_ARGS` per the advice in this blog https://hoverbear.org/blog/rust-bindgen-in-nix/:

```
  BINDGEN_EXTRA_CLANG_ARGS = "-isystem ${llvmPackages.libclang.lib}/lib/clang/${lib.getVersion clang}/include";
```

I tried to look into where the missed update to clang package definitions so I could send a PR but it's a little too large for me to figure out where the problem is occurring.

**Comment by Aleksanaa** [comment] 2024-01-29 16:21
There's `rustPlatform.bindgenHook` now.

**Comment by mooori** [comment] 2024-06-21 16:48
I was also hitting the issue of missing `stdarg.h` and it seems like things are packaged differently now. On channel `24.05` I could resolve the issue by changing `llvmPackages.libclang` to `libclang.lib` in [the snippet posted above](https://github.com/NixOS/nixpkgs/issues/52447#issuecomment-853429315).

```nix
{ ... }:
mkShell {
  nativeBuildInputs = [
      libclang.lib
      llvmPackages.libcxxClang
      clang
  ];
  LIBCLANG_PATH = "${libclang.lib}/lib";
  BINDGEN_EXTRA_CLANG_ARGS = "-isystem ${llvmPackages.libcxxClang.lib}/lib/clang/${lib.getVersion clang}/include";
}
```

**Comment by musjj** [comment] 2025-03-10 22:49
This is what worked for me:

```nix
nativeBuildInputs = with pkgs; [
  llvmPackages.libclang
  llvmPackages.libcxxClang
  clang
];

LIBCLANG_PATH = with pkgs; "${llvmPackages.libclang.lib}/lib";
BINDGEN_EXTRA_CLANG_ARGS =
  with pkgs;
  "-isystem ${llvmPackages.libclang.lib}/lib/clang/${lib.versions.major (lib.getVersion clang)}/include";
```
