### ISSUE TITLE
gnome-tweak-tool does not work in XFCE

### ISSUE THREAD

**Issue by wizeman** [NixOS/nixpkgs#5298] opened 2014-12-11 15:42 UTC
It doesn't start up. Instead, it returns the following error:

``` python
$ gnome-tweak-tool 

** (.gnome-tweak-tool-wrapped:8504): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
WARNING : Shell not installed or running
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
WARNING : Error loading desktopfile: /home/wizeman/.config/autostart/gnome-keyring-gpg.desktop
INFO    : GSetting missing org.gnome.mutter
Traceback (most recent call last):
  File "/nix/store/7cm1j9wznpzxvd7i89whkaz8xkhimav5-gnome-tweak-tool-3.12.0/lib/python2.7/site-packages/gtweak/app.py", line 39, in do_activate
    self.win = Window(self, model)
  File "/nix/store/7cm1j9wznpzxvd7i89whkaz8xkhimav5-gnome-tweak-tool-3.12.0/lib/python2.7/site-packages/gtweak/tweakview.py", line 54, in __init__
    self._model.load_tweaks(self)
  File "/nix/store/7cm1j9wznpzxvd7i89whkaz8xkhimav5-gnome-tweak-tool-3.12.0/lib/python2.7/site-packages/gtweak/tweakmodel.py", line 125, in load_tweaks
    mods = __import__("gtweak.tweaks", globals(), locals(), tweak_files, 0)
  File "/nix/store/7cm1j9wznpzxvd7i89whkaz8xkhimav5-gnome-tweak-tool-3.12.0/lib/python2.7/site-packages/gtweak/tweaks/tweak_group_shell.py", line 65, in <module>
    sw = StaticWorkspaceTweak(size_group=sg, loaded=_shell_loaded)
  File "/nix/store/7cm1j9wznpzxvd7i89whkaz8xkhimav5-gnome-tweak-tool-3.12.0/lib/python2.7/site-packages/gtweak/tweaks/tweak_group_shell.py", line 49, in __init__
    default = self.STATUS.keys()[self.STATUS.values().index(self.settings[self.key_name])]
ValueError: None is not in list
```

**Comment by Profpatsch** [comment] 2016-03-06 00:13
(triage) @wizeman can you still reproduce that?

**Comment by wizeman** [comment] 2016-03-07 10:01
@Profpatsch Yes, I can still reproduce it...

**Comment by despairblue** [comment] 2016-10-13 11:44
Happens to me as well, was going to change gtk3 theme. Seems like a legit use case outside of gnome.

**Comment by Mic92** [comment] 2016-10-22 21:34
@despairblue I use `lxappearence` for that.

**Comment by despairblue** [comment] 2016-10-22 23:10
@Mic92 that does neither show gtk3 themes nor any installed gtk2 theme except for Raleigh. :cry:

**Comment by yegortimoshenko** [comment] 2017-12-19 10:06
I have the same error. GNOME tweak tool would never work outside of GNOME, this is an upstream issue which we don't have control over.

Also, "middle click to lower window" is seemingly disabled by default in the latest Chromium (on Xfce), I can't reproduce the problem in Chromium ticket 132061 linked above, it's also marked as fixed.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.5, NixOS, 18.03.git.ab1d2a5 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"overlay, nixos-18.03pre122666.afe9649210c"`
 - channels(chronos): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by yegortimoshenko** [comment] 2017-12-19 10:15
```
$ nix-build -E "with import <nixpkgs> {}; gnome3.gnome-tweak-tool.overrideAttrs (super: { buildInputs = super.buildInputs ++ [ gnome3.mutter ]; })"
```

At least opens.

**Comment by yegortimoshenko** [comment] 2017-12-19 10:20
Oh, great! This was fixed by @jtojnar in master 2 days ago: 98adff8b1a4b99a5ed4b37f64d09c0f3c6e020d9

**Closed by yegortimoshenko** 2017-12-19 10:20 UTC
Labels: 6.topic: xfce

**Comment by jtojnar** [comment] 2017-12-19 12:38
Weird, there should not have been any functional changes other than the update.

**Comment by yegortimoshenko** [comment] 2017-12-19 12:50
@jtojnar You have added `gnome3.mutter` to `buildInputs`, which solved the issue. I still don't think it would necessarily work other than just open, because some of the settings are specific to GNOME.

**Comment by jtojnar** [comment] 2017-12-19 14:21
Oh, right, I forgot about that.
