### ISSUE TITLE
Packages are not installed via `nixos-install`.

### ISSUE THREAD

**Issue by k4leg** [NixOS/nixpkgs#127839] opened 2021-06-22 22:09 UTC
**Describe the bug**
Packages are not installed via `nixos-install`.

**To Reproduce**
1. Boot in LiveCD NixOS KDE Plasma 21.05.1105.6613a30c5e3.
2. Try to install a system with default config, `environment.systemPackages = with pkgs; [ anki (texlive.combine { inherit (texlive) metafont collection-latexrecommended collection-fontsrecommended collection-langcyrillic; }) ];` and `fonts.fonts = [ pkgs.jetbrains-mono ];`.

**Expected behavior**
Installation without errors.

**Additional context**
[Log #1](https://pastebin.com/CYqfcp3A), [log #2](https://pastebin.com/02GGvc4s), [log #3](https://pastebin.com/250sTMdC).

**Notify maintainers**

@oxij @Profpatsch @marsam @veprbl @lovek323 @raskin @jwiegley

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.44, NixOS, 21.05.1105.6613a30c5e3 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pkgs.anki, pkgs.jetbrains-mono, pkgs.texlive.combine
```

**Comment by Artturin** [comment] 2021-06-23 04:54
Dupe of #126141
you can find a workaround as a comment

**Closed by Artturin** 2021-06-23 04:54 UTC
Labels: 0.kind: bug
