### ISSUE TITLE
[Package Request] guacamole-server

### ISSUE THREAD

**Issue by ilovefornite797** [NixOS/nixpkgs#154217] opened 2022-01-10 02:09 UTC
**Apache guacamole-server**
_Remote desktop access via web browser_

**Metadata**

* homepage URL: [https://guacamole.apache.org/](https://guacamole.apache.org/)
* source URL: [https://dlcdn.apache.org/guacamole/1.4.0/source/guacamole-server-1.4.0.tar.gz](https://dlcdn.apache.org/guacamole/1.4.0/source/guacamole-server-1.4.0.tar.gz)
* license: apache 2.0
* platforms: unix, linux, darwin

**Comment by mausch** [comment] 2022-05-28 13:46
Duplicate of https://github.com/NixOS/nixpkgs/issues/17879

**Closed** 2022-07-31 15:28 UTC
Labels: 0.kind: packaging request
