### ISSUE TITLE
Packaging request: Psst

### ISSUE THREAD

**Issue by nerosnm** [NixOS/nixpkgs#134446] opened 2021-08-17 14:01 UTC
**Project description**
Psst is a Spotify client with a native GUI, without Electron, built in Rust.

**Metadata**

* homepage URL: https://github.com/jpochyla/psst
* source URL: https://github.com/jpochyla/psst
* license: mit
* platforms: linux, darwin

It's still early in development but looks promising, and does implement a base feature set already.

**Comment by figsoda** [comment] 2021-08-17 14:04
duplicate of https://github.com/NixOS/nixpkgs/issues/115155

**Closed by figsoda** 2021-08-17 14:04 UTC
Labels: 0.kind: packaging request
