### ISSUE TITLE
Build failure: minecraft

### ISSUE THREAD

**Issue by SullivanNagler** [NixOS/nixpkgs#344888] opened 2024-09-27 14:09 UTC
### Steps To Reproduce

1. build *pkgs.minecraft*

### Build log
pkgs.minecraft
```
       … while calling the 'head' builtin

         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'

         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: Package ‘minecraft-launcher-2.2.1441’ in /nix/store/66wih7h86q9x7aj88isn92gdssfg3d5d-nixos-24.05/nixos/pkgs/games/minecraft/default.nix:148 is marked as broken, refusing to evaluate.



```

### Additional context

I use nixos-24.05
### Notify maintainers
@ryantm 
[Carles Pagès](https://github.com/cpages) <[page@ruiec.cat](mailto:page@ruiec.cat)>
[Ryan Mulligan](https://github.com/ryantm) <[ryan@ryantm.com](mailto:ryan@ryantm.com)>

### Metadata
I’m new to nixos, i havn’t succed to show the metadata, if you need more info, i’m ready to help.
By the way the compiler is ok if i use ’nixpkgs.config.allowBroken = true;’ but in 1.21.3 the game dosn’t work and the code of exit is : 0
Thanks in advance

**Comment by SullivanNagler** [comment] 2024-09-27 14:29
I’ve found in the code marked "broken" this indication :  # "minecraft-launcher will fail on NixOS for minecraft versions >1.19
    # try prismlauncher or atlauncher instead"

**Comment by SigmaSquadron** [comment] 2024-09-27 14:30
The evaluation error is telling you Minecraft is marked as broken. You've verified that by disabling the broken check and running the game anyway, only to have the game stop working, because it is broken. This is intended behaviour in Nixpkgs: we mark packages that don't work as broken to prevent users from using broken software.

The comment you found shows it's probably Microsoft breaking things, in which case, there's nothing we can do to patch the game/launcher.

https://github.com/NixOS/nixpkgs/blob/4c030cf309bffa9cd87336705e96ce941ce977d9/pkgs/games/minecraft/default.nix#L154-L156

**Closed by SigmaSquadron** 2024-09-27 14:30 UTC
Labels: 0.kind: build failure

**Comment by SullivanNagler** [comment] 2024-09-27 14:57
Thx for the information and the context.
I've a better understarding now !

> The evaluation error is telling you Minecraft is marked as broken. You've verified that by disabling the broken check and running the game anyway, only to have the game stop working, because it is broken. This is intended behaviour in Nixpkgs: we mark packages that don't work as broken to prevent users from using broken software.
> 
> The comment you found shows it's probably Microsoft breaking things, in which case, there's nothing we can do to patch the game/launcher.
> 
> https://github.com/NixOS/nixpkgs/blob/4c030cf309bffa9cd87336705e96ce941ce977d9/pkgs/games/minecraft/default.nix#L154-L156
