### ISSUE TITLE
gdm doesn't care about local fr from configuration.nix file

### ISSUE THREAD

**Issue by jerome-diver** [NixOS/nixpkgs#20391] opened 2016-11-13 18:38 UTC
## Issue description
when indicate an other local than en_US, it works on tty, and on xserver, but never in gdm. in other distros, users need to create a xorg config file for keyboard device and pass this information for gdm be able to read and consider it...
So from your manual, no indication around how to do that with nixos.
I'm searching for a solution, no one find on IRC nixos channel to...

### Steps to reproduce
install gdm display manager with nixos and try to use an azerty keyboard for login desktop (good luck)

## Technical details

* System: nixos-16.09
* Nix version: 1.11.4 (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by onmh** [comment] 2017-05-09 15:05
exactly the same problem with nixos 17.03

**Comment by adamscott** [comment] 2017-06-18 00:39
It seems to be the same issue as the one mentioned here: #14318

**Comment by jerome-diver** [comment] 2017-06-18 23:31
yes, it seems to be the same, but it was on unstable version 1.11.2... on version 16.09 noone resolved the problem. And @lethalman answered that he thinks that maybe, probably, it should be a config to change in gnome (so after login... how is it possible ?). So i think, sure, it will not be resolved in that way...
so, good luck.

**Comment by adamscott** [comment] 2017-06-19 00:30
I did [find a sort of solution](https://github.com/NixOS/nixpkgs/issues/14318#issuecomment-309250231) in the issue I referred. If this module is imported and enabled, this fixes gdm and Gnome 3.

_En espérant que ça puisse aider!_ ☺️

**Comment by jtojnar** [comment] 2017-09-30 23:12
This should be closed as a duplicate of #14318

**Closed** 2017-09-30 23:20 UTC
Labels: 0.kind: bug, 6.topic: user experience, 9.needs: community feedback
