### ISSUE TITLE
device files for Brother DS-620 scanner owned by group "disk" despite udev rules

### ISSUE THREAD

**Issue by pmahoney** [NixOS/nixpkgs#99221] opened 2020-10-01 03:48 UTC
**Describe the bug**

My normal use could not access the scanner until I added that user to the "disk" group.

The included udev rules installed by [dsseries](https://github.com/NixOS/nixpkgs/blob/84cf00f98031e93f389f1eb93c4a7374a33cc0a9/pkgs/applications/graphics/sane/backends/dsseries/default.nix) imply they should be under group "scanner".

**To Reproduce**

1. in configuration.nix: hardware.sane.dsseries.enable = true
2. plug in a Brother DS-620
3. run `simple-scan` as normal user not in "disk" group; it cannot find scanner
4. run `simple-scan` as root; it can find scanner

**Expected behavior**

The scanner should be usable by a user in the "scanner" group.

**Additional context**

Watching the output of `sudo udevadm monitor -e` while plugging in the scanner, I can see several usb devices (I'm not very familiar with how these things are setup. Seems like the single scanner presents itself as several devices in a tree).

```
$ sudo udevadm monitor -e | grep DEVTYPE | sort | uniq
DEVTYPE=disk
DEVTYPE=scsi_device
DEVTYPE=scsi_host
DEVTYPE=scsi_target
DEVTYPE=usb_device
DEVTYPE=usb_interface
```

I noticed the device file on the last device (with DEVTYPE=disk) looked like this:
```
$ ls -lL /dev/disk/by-id/usb-Brother_DS-620_U63543M8U245853-0\:0 
brw-rw---- 1 root disk 8, 16 Sep 30 22:22 /dev/disk/by-id/usb-Brother_DS-620_U63543M8U245853-0:0
```
Then after adding my user to "disk" group, I was able to access the scanner as non-root.

The udev rules in `/etc/udev/rules.d/50-Brother_DSScanner.rules`:
```
KERNEL=="sg[0-9]*", ATTRS{type}=="0", ATTRS{vendor}=="Brother", ATTRS{model}=="DS-620", MODE="0666", GROUP="scanner", ENV{libsane_matched}="yes"
KERNEL=="sg[0-9]*", ATTRS{type}=="0", ATTRS{vendor}=="Brother", ATTRS{model}=="DS-720D", MODE="0666", GROUP="scanner", ENV{libsane_matched}="yes"
KERNEL=="sg[0-9]*", ATTRS{type}=="0", ATTRS{vendor}=="Brother", ATTRS{model}=="DS-820W", MODE="0666", GROUP="scanner", ENV{libsane_matched}="yes"
KERNEL=="sg[0-9]*", ATTRS{type}=="0", ATTRS{vendor}=="Brother", ATTRS{model}=="DS-920DW", MODE="0666", GROUP="scanner", ENV{libsane_matched}="yes"
```

**Notify maintainers**

@callahad

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.66, NixOS, 21.03pre244045.1179840f9a8 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre244045.1179840f9a8"`
 - channels(pat): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixpkgs.dsseries
# a list of nixos modules affected by the problem
module: <nixpkgs/nixos/modules/services/hardware/sane_extra_backends/dsseries.nix>
```

**Comment by callahad** [comment] 2020-10-01 12:21
Hm, I seem to be able to reproduce this, but something is even stranger on my end: if I launch `simple-scan` via a keyboard shortcut (or from a terminal which itself was launched from a keyboard shortcut), it works just fine. But if I launch `simple-scan` through the normal `gnome-shell` application launcher (or a terminal started from the same), it fails.

@pmahoney Just to make sure I'm not imagining things... does Simple Scan work for you if launched from a keyboard shortcut like this:

![2020-10-01_13-19](https://user-images.githubusercontent.com/24193/94808365-f608cd00-03e8-11eb-95d5-f8bce974bb6b.png)

**Comment by callahad** [comment] 2020-10-01 12:35
Nothing useful in `simple-scan --debug`

My scanner device appears as:

    $ ls -l /dev/sg0                                                                                             
    crw-rw-rw-+ 1 root disk 21, 0 Oct  1 13:08 /dev/sg0

I am not a member of the `disk` group:

    $ id                                                                                                                 
    uid=1000(dan) gid=100(users) groups=100(users),1(wheel),17(audio),26(video),57(networkmanager),59(scanner),62(systemd-journal),131(docker)

Diffing the `env` for each terminal finds that when launched from a keyboard shortcut, the working environments have:

    LD_LIBRARY_PATH=/nix/store/...-sane-config/lib/sane

And indeed, injecting that into a broken terminal and launching simple-scan from in there works correctly.

So now I guess the question is where that `LD_LIBRARY_PATH` value is coming from, and why it's not present in applications launched normally from gnome-shell.

**Comment by callahad** [comment] 2020-10-01 13:02
That envvar *is* present and everything works as expected on the GNOME Xorg session, just not on Wayland... Digging further.

**Comment by callahad** [comment] 2020-10-01 13:22
Looks like the `sane` module defines `LD_LIBRARY_PATH` here:

https://github.com/NixOS/nixpkgs/blob/076860e0340a5e4a909b9a710e186508b14d1c90/nixos/modules/services/hardware/sane.nix#L29-L32

And then sets it as `config.environment.sessionVariables` here:

https://github.com/NixOS/nixpkgs/blob/076860e0340a5e4a909b9a710e186508b14d1c90/nixos/modules/services/hardware/sane.nix#L124

...so why aren't those present in my Gnome session? (Help appreciated!)

**Comment by callahad** [comment] 2020-10-01 21:28
If I compare a working versus failing process hierarchy, I get:

    systemd(1)───systemd(8343)─┬─.simple-scan-wrapped(20023)
                               └─.gnome-shell-wrapped(8540)───.simple-scan-wrapped(20462)
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
                                 LD_LIBRARY_PATH isn't set

So the only difference is that launching from the Gnome shell places `gnome-shell` in the hierarchy, while launching from a shortcut does not... and the `gnome-shell` process doesn't have `LD_LIBRARY_PATH` in its environment, which prevents it from being inherited by the latter `simple-scan` process

**Comment by callahad** [comment] 2020-10-02 12:28
Closing this; root cause is much broader. Will file a new bug to track.

**Closed by callahad** 2020-10-02 12:28 UTC
Labels: 0.kind: bug, 6.topic: hardware, 6.topic: nixos

**Comment by callahad** [comment] 2020-10-02 12:50
Looks like #86730 is the same root cause, and has further debugging.

**Comment by pmahoney** [comment] 2020-10-03 02:23
Thanks for digging into this.

For the record, I created a keyboard shortcut to launch simple-scan, and it _was_ able to see the scanner.
