### ISSUE TITLE
NixOS: nixos-rebuild fails with memory allocation for gzip -d

### ISSUE THREAD

**Issue by cidkidnix** [NixOS/nixpkgs#124215] opened 2021-05-24 00:44 UTC
**Describe the bug**
nixos-rebuild fails with `install-info: Cannot allocate memory for gzip -d`
This should not be an actual OOM error since my system has 32GB of ram and was using around 4GB at the time of trying to switch

**To Reproduce**
1. Update to the latest nixos-unstable from the nixpkgs github (if you're on flakes)
2. Change configuration and attempt to rebuild

**Expected behavior**
For the system to rebuild and properly switch

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.16-zen1, NixOS, 21.05+patch-01ba471 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

**Comment by okanua** [comment] 2021-05-24 01:01
I have also have what appears to be the same problem . I updated my flake today (also on unstable), and since doing so I am unable to rebuild and switch. I get the following error:

```
error: builder for '/nix/store/b2h9l993pxf6r2rib50v72ryy8kkz6dl-user-environment.drv' failed with exit code 1;
       last 2 log lines:
> created 332 symlinks in user environment
> install-info: Cannot allocate memory for gzip -d
       For full logs, run 'nix log /nix/store/b2h9l993pxf6r2rib50v72ryy8kkz6dl-user-environment.drv'.
error: 1 dependencies of derivation '/nix/store/9af961nx18fbljiaqi8y0gdv0ixpyff1-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6yv7lrlzgbxyq8w9d18r8w4zwciq60pn-nixos-system-noddo-21.05.20210523.900115a.drv' failed to build
error: getting status of '/tmp/nixos-rebuild.6bYmNV/result': No such file or directory
```

Likewise, I do not believe this to be an actual OOM. Using a VM with 4GB RAM. Fresh startup with RAM usage sitting at ~500MB. Memory usage on htop doesn't go above 1.35GB. The same config, previously working before updating flake, was fine on a VM with only 3GB...

**Comment by codygman** [comment] 2021-05-24 04:11
I'm having this issue after updating my flake inputs recently. The computer I'm having this issue on also uses 32GB of RAM.

I have another computer using the same flake that builds it fine and has 16GB of RAM.

**Comment by sumnerevans** [comment] 2021-05-24 04:48
I am having this issue in a non-flakes environment. There's been some fun discussion over on the #nix:nixos.org Matrix room. This is not an OOM, there's some other issue. I'm going to try and bisect.

**Comment by codygman** [comment] 2021-05-24 05:12
@sumnerevans I got the error as far back as a73020b2a150322c9832b50baeb0296ba3b13dd7 which is 1 month ago. That makes me think that my nix store or something has been put in a bad state by the recent nixpkgs update?

**Comment by sumnerevans** [comment] 2021-05-24 05:18
@codygman I think you are right. I'm seeing the same thing. Let me try and figure out how to fix the store...

**Comment by cidkidnix** [comment] 2021-05-24 05:32
Right running `sudo nix store repair --all` fails with ```error: cannot repair path '/nix/store/*-source.drv'```

**Comment by sumnerevans** [comment] 2021-05-24 05:34
@cidkidnix I get the same error, but with:
```
error: cannot repair path '/nix/store/000sn4jyizvclw51bdkn4vj05b4pzy5m-texlive-pgf-3.1.8b.drv'
```

**Comment by cidkidnix** [comment] 2021-05-24 05:34
Assuming that it is an issue with the nix store being corrupted or borked, we probably should use this as a tracking issue as this is probably caused by something else.

**Comment by cidkidnix** [comment] 2021-05-24 05:40
Right I'm running a `doas nix-store --verify --check-contents` right now to see if any paths are messed up, repairing the store path that fails for me with `doas nix store repair /nix/store/path` doesn't actually do anything

**Comment by cidkidnix** [comment] 2021-05-24 05:42
`doas nix-store --verify --check-contents` doesn't output anything of any worry

**Comment by sumnerevans** [comment] 2021-05-24 05:48
I used `sudo nix-channel --rollback` multiple times to get to older versions of nixpkgs that were known to work for my config in the past, but I'm getting errors. It seems like any time I have to rebuild any of the system, it fails.

**Comment by cidkidnix** [comment] 2021-05-24 05:50
`documentation.info.enable = false;` Fixes it but that means that GNU Texlive is broken in nixpkgs at the moment and probably needs to be fixed and pushed ASAP

**Comment by lovesegfault** [comment] 2021-05-24 06:21
I'm affected by this issue as well. Currently cannot deploy to any of my systems due to it. 

I attempted  `documentation.info.enable = false`, but it had no effect on the issue for me on my AArch64 systems. It does, however, work around the problem on my x86 systems.

**Comment by mdevlamynck** [comment] 2021-05-24 06:22
Not sure if its related but as mentioned [here](https://github.com/NixOS/nixpkgs/issues/107216#issuecomment-754860025) when I encounter this issue the result of `nix show-config | grep sandbox-paths` is `sandbox-paths =` (empty value). If I rollback to a previous generation it fixes the issue and indeed `nix show-config | grep sandbox-paths` yields `sandbox-paths = /bin/sh=/nix/store/br5d32rv4y1qpm3bibwwn7birmpjf0hk-busybox-static-x86_64-unknown-linux-musl-1.32.1/bin/busybox`.

**Comment by Riey** [comment] 2021-05-24 06:23
I also have this issue seems related with #107216

however, I tried to change turn off sandbox option rebuild success then I can build with sandbox :confused:

**Comment by Ma27** [comment] 2021-05-24 11:53
I can confirm that the solution from worldofpeace  (`nix.sandboxPaths = [ "/bin/sh" ];`) has fixed the problem for me - so far at least (thanks for the hint @mdevlamynck)

**Comment by Ma27** [comment] 2021-05-24 11:54
also cc @NixOS/release-engineers 
@sumnerevans does "non-flake" environment mean that you're on Nix 2.3? If yes, then this is a blocker.

**Comment by gebner** [comment] 2021-05-24 13:10
This is already fixed on master: #124237 

If you are unable to `nixos-rebuild switch`, then you need to manually remove the `sandbox-paths =` option from `/etc/nix/nix.conf` first.

**Closed** 2021-05-24 13:11 UTC
Labels: 0.kind: bug

**Comment by wearemnr** [comment] 2021-05-24 13:36
> I can confirm that the solution from worldofpeace (`nix.sandboxPaths = [ "/bin/sh=${pkgs.bash}/bin/sh" ];`) has fixed the problem for me - so far at least (thanks for the hint @mdevlamynck)

Also I can confirm (`nix.sandboxPaths = [ "/bin/sh=${pkgs.bash}/bin/sh" ];`) solved almost same issue for me...

I had something like...
`
building the system configuration...
system-path> created 8688 symlinks in user environment
system-path> install-info: Cannot allocate memory for gzip -d
error: builder for '/nix/store/ixc1zymaf5pgvd56gv3hm128pdx4m50c-system-path.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/y4kljqbyb3g0vdywlhaf3rq8q6gs6zr9-nixos-system-nixos-21.05.20210523.900115a.drv' failed to build
error: getting status of '/tmp/nixos-rebuild.bF5ER4/result': No such file or directory
`

**Comment by codygman** [comment] 2021-05-24 13:39
It didn't work for me [in devos](https://github.com/divnix/devos/issues/296#issuecomment-847013609), but I think that's an issue with my lack of knowledge :sweat_smile:

**Comment by sumnerevans** [comment] 2021-05-24 14:01
> @sumnerevans does "non-flake" environment mean that you're on Nix 2.3? If yes, then this is a blocker.

I am on Nix 2.4pre20210503_6d2553a, but I am not using flakes for my config.

**Comment by nrdxp** [comment] 2021-05-25 14:44
> It didn't work for me [in devos](https://github.com/divnix/devos/issues/296#issuecomment-847013609), but I think that's an issue with my lack of knowledge

so first go ahead and update the nixos input @codygman, but since this issue is messing up your existing nix.conf, you'll also need to call `nixos-rebuild` with an extra option: `--option extra-sandbox-paths "/bin/sh=/nix/store/<bash-derivation>/bin/sh"`, this should update your system to a revision that includes the fix

**Comment by zyansheep** [comment] 2021-05-25 15:16
I'm getting a `./configure: /bin/sh: bad interpreter: No such file or directory` even when running with `--option extra-sandbox-paths ...` for different derivations (currently lucidatypewriter)

**Comment by nrdxp** [comment] 2021-05-25 16:21
> An even easier workaround is to just roll back your NixOS version to one without broken nix-daemon.

Only reason I didn't do that is because I deleted my previous generations yesterday :sweat_smile: 

> I'm getting a ./configure: /bin/sh: bad interpreter: No such file or directory even when running with --option extra-sandbox-paths ... for different derivations (currently lucidatypewriter)

hmm, so that's the exact error that I got _before_ I used the `extra-sandbox-paths` option. Does your `<bash-derivaton>` contain a full path to `sh` living in the nix/store? For example, mine was:
`"/bin/sh=/nix/store/fgbzvd4c6nly9m4dpczrxybdpkm8mnk3-bash-interactive-4.4-p23/bin/sh"`

**Comment by jonringer** [comment] 2021-05-25 18:21
> I'm getting a `./configure: /bin/sh: bad interpreter: No such file or directory` even when running with `--option extra-sandbox-paths ...` for different derivations (currently lucidatypewriter)

This has never worked, you need to do `patchShebangs configure`, or if the command is embedded, you would need to do a `substituteInPlace`

**Comment by superherointj** [comment] 2021-05-25 22:16
> install-info: Cannot allocate memory for gzip -d

To workaround this problem:
1) Set your system to master.
2) Activate it using it:
  `nixos-rebuild switch --option extra-sandbox-paths "/bin/sh=$(readlink -f $(which bash))"`

It works.

**Comment by codygman** [comment] 2021-05-26 01:35
> An even easier workaround is to just roll back your NixOS version to one without broken nix-daemon.
> 
> Even temporarily is enough: `sudo /nix/var/nix/profiles/system-version-before-update/bin/switch-to-configuration test`

I had already deleted mine since on my other machine there where no problems 😆

**Comment by xaverdh** [comment] 2021-05-26 14:26
Can we pin this issue for a few days or something? Its rather important for all ppl that follow master closely.

**Comment by Kreyren** [comment] 2024-05-19 14:17
Encountered on standalone nixos using Armbian 24.2.1 for OLIMEX Teres-I while trying to install NixOS 

```console
[nix-shell:/mnt/etc/nixos]# nixos-install --root /mnt --keep-going
/nix/store/0c337gsdfjf3162avbkchh0yh4qbs2s3-bash-5.2-p15/bin/bash: warning: setlocale: LC_ALL: cannot change locale (cs_CZ.UTF-8)
building the configuration in /mnt/etc/nixos/configuration.nix...
these 17 derivations will be built:
  /nix/store/1znl8y6c2bxl56jvfig0zjpa0l4q22y6-xsession-wrapper.drv
  /nix/store/hghxhjjmwc4mrp6szrfhv2x7l2i8gnvv-system-path.drv
  /nix/store/4s73mynh921qlzd48jdi2kl1bva4cp1j-etc-pam-environment.drv
  /nix/store/jk140xzg32svpv8j0wfa7vbm2m3s8w7b-set-environment.drv
  /nix/store/5qdvhi9l1b8m20j71nnd9i04jkv4pfm3-etc-profile.drv
  /nix/store/75lk75zxihb0ipryqh7i5pldkah9s14v-unit-accounts-daemon.service.drv
  /nix/store/z24d1h5m7p757a45mnq7gvc62gv7p8r3-X-Restart-Triggers-polkit.drv
  /nix/store/85bmcdl7m20p5v8hmgi53w5283mf39zb-unit-polkit.service.drv
  /nix/store/8dq9f84pj7kr01d0qg39zvdp1ms8ayx9-dbus-1.drv
  /nix/store/jbji9x6mb6rjfkpi7nn7xfizsxgzq3pr-X-Restart-Triggers-dbus.drv
  /nix/store/hn4qckrngcr7krbjy3l4sb47wcfzrazz-unit-dbus.service.drv
  /nix/store/66593hd41ga21c1arj5ch7izakv9ls9q-system-units.drv
  /nix/store/7s7zlyn2wklcjmp7sx97bdnzvl3583r0-xscreensaver.pam.drv
  /nix/store/6ys8isl32s5yxxpj5z2sff5vv3r7ad34-unit-dbus.service.drv
  /nix/store/pc69zlqpnzqxwnhb4qi38wax9whjc491-user-units.drv
  /nix/store/gqvlfbqn77bx2brgacpxc1kh8lw52vk5-etc.drv
  /nix/store/0drd1k1g1v2r380a2ib74vi8fcsbkmxk-nixos-system-tsvetan-23.11.7181.bacb8503d3a5.drv
building '/nix/store/hghxhjjmwc4mrp6szrfhv2x7l2i8gnvv-system-path.drv'...
created 15422 symlinks in user environment
install-info: No such file or directory for gzip -d
error: builder for '/nix/store/hghxhjjmwc4mrp6szrfhv2x7l2i8gnvv-system-path.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/z24d1h5m7p757a45mnq7gvc62gv7p8r3-X-Restart-Triggers-polkit.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8dq9f84pj7kr01d0qg39zvdp1ms8ayx9-dbus-1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/4s73mynh921qlzd48jdi2kl1bva4cp1j-etc-pam-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jk140xzg32svpv8j0wfa7vbm2m3s8w7b-set-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/75lk75zxihb0ipryqh7i5pldkah9s14v-unit-accounts-daemon.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jbji9x6mb6rjfkpi7nn7xfizsxgzq3pr-X-Restart-Triggers-dbus.drv' failed to build
error: 1 dependencies of derivation '/nix/store/5qdvhi9l1b8m20j71nnd9i04jkv4pfm3-etc-profile.drv' failed to build
error: 1 dependencies of derivation '/nix/store/85bmcdl7m20p5v8hmgi53w5283mf39zb-unit-polkit.service.drv' failed to build
building '/nix/store/7s7zlyn2wklcjmp7sx97bdnzvl3583r0-xscreensaver.pam.drv'...
error: 1 dependencies of derivation '/nix/store/6ys8isl32s5yxxpj5z2sff5vv3r7ad34-unit-dbus.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hn4qckrngcr7krbjy3l4sb47wcfzrazz-unit-dbus.service.drv' failed to build
error: 3 dependencies of derivation '/nix/store/66593hd41ga21c1arj5ch7izakv9ls9q-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/pc69zlqpnzqxwnhb4qi38wax9whjc491-user-units.drv' failed to build
building '/nix/store/1znl8y6c2bxl56jvfig0zjpa0l4q22y6-xsession-wrapper.drv'...
error: 7 dependencies of derivation '/nix/store/gqvlfbqn77bx2brgacpxc1kh8lw52vk5-etc.drv' failed to build
error: 2 dependencies of derivation '/nix/store/0drd1k1g1v2r380a2ib74vi8fcsbkmxk-nixos-system-tsvetan-23.11.7181.bacb8503d3a5.drv' failed to build

[nix-shell:/mnt/etc/nixos]# nix log /nix/store/hghxhjjmwc4mrp6szrfhv2x7l2i8gnvv-system-path.drv
error: path '/nix/store/hghxhjjmwc4mrp6szrfhv2x7l2i8gnvv-system-path.drv' is not a valid store path

[nix-shell:/mnt/etc/nixos]# nix store repair --all
error: cannot repair path '/nix/store/1xghqp6fb131ybs5akb78p6kw4rqrl5l-bootstrap-stage0-stdenv-linux.drv'

[nix-shell:/mnt/etc/nixos]# doas nix-store --verify --check-contents
bash: doas: command not found

[nix-shell:/mnt/etc/nixos]# nix-store --verify --check-contents
reading the Nix store...
checking path existence...
checking link hashes...
checking store hashes...

[nix-shell:/mnt/etc/nixos]# vim /mnt/etc/^C

[nix-shell:/mnt/etc/nixos]# vim configuration.nix

[nix-shell:/mnt/etc/nixos]# nixos-install --root /mnt --option extra-sandbox-paths "/bin/sh=$(readlink -f $(which bash))"
/nix/store/0c337gsdfjf3162avbkchh0yh4qbs2s3-bash-5.2-p15/bin/bash: warning: setlocale: LC_ALL: cannot change locale (cs_CZ.UTF-8)
building the configuration in /mnt/etc/nixos/configuration.nix...
these 15 derivations will be built:
  /nix/store/hghxhjjmwc4mrp6szrfhv2x7l2i8gnvv-system-path.drv
  /nix/store/4s73mynh921qlzd48jdi2kl1bva4cp1j-etc-pam-environment.drv
  /nix/store/jk140xzg32svpv8j0wfa7vbm2m3s8w7b-set-environment.drv
  /nix/store/5qdvhi9l1b8m20j71nnd9i04jkv4pfm3-etc-profile.drv
  /nix/store/75lk75zxihb0ipryqh7i5pldkah9s14v-unit-accounts-daemon.service.drv
  /nix/store/z24d1h5m7p757a45mnq7gvc62gv7p8r3-X-Restart-Triggers-polkit.drv
  /nix/store/85bmcdl7m20p5v8hmgi53w5283mf39zb-unit-polkit.service.drv
  /nix/store/8dq9f84pj7kr01d0qg39zvdp1ms8ayx9-dbus-1.drv
  /nix/store/jbji9x6mb6rjfkpi7nn7xfizsxgzq3pr-X-Restart-Triggers-dbus.drv
  /nix/store/hn4qckrngcr7krbjy3l4sb47wcfzrazz-unit-dbus.service.drv
  /nix/store/66593hd41ga21c1arj5ch7izakv9ls9q-system-units.drv
  /nix/store/6ys8isl32s5yxxpj5z2sff5vv3r7ad34-unit-dbus.service.drv
  /nix/store/pc69zlqpnzqxwnhb4qi38wax9whjc491-user-units.drv
  /nix/store/gqvlfbqn77bx2brgacpxc1kh8lw52vk5-etc.drv
  /nix/store/0drd1k1g1v2r380a2ib74vi8fcsbkmxk-nixos-system-tsvetan-23.11.7181.bacb8503d3a5.drv
building '/nix/store/hghxhjjmwc4mrp6szrfhv2x7l2i8gnvv-system-path.drv'...
created 15422 symlinks in user environment
gtk-update-icon-cache: Cache file created successfully.
building '/nix/store/z24d1h5m7p757a45mnq7gvc62gv7p8r3-X-Restart-Triggers-polkit.drv'...
building '/nix/store/8dq9f84pj7kr01d0qg39zvdp1ms8ayx9-dbus-1.drv'...
building '/nix/store/4s73mynh921qlzd48jdi2kl1bva4cp1j-etc-pam-environment.drv'...
building '/nix/store/jbji9x6mb6rjfkpi7nn7xfizsxgzq3pr-X-Restart-Triggers-dbus.drv'...
building '/nix/store/jk140xzg32svpv8j0wfa7vbm2m3s8w7b-set-environment.drv'...
building '/nix/store/75lk75zxihb0ipryqh7i5pldkah9s14v-unit-accounts-daemon.service.drv'...
building '/nix/store/5qdvhi9l1b8m20j71nnd9i04jkv4pfm3-etc-profile.drv'...
building '/nix/store/6ys8isl32s5yxxpj5z2sff5vv3r7ad34-unit-dbus.service.drv'...
building '/nix/store/hn4qckrngcr7krbjy3l4sb47wcfzrazz-unit-dbus.service.drv'...
building '/nix/store/85bmcdl7m20p5v8hmgi53w5283mf39zb-unit-polkit.service.drv'...
building '/nix/store/pc69zlqpnzqxwnhb4qi38wax9whjc491-user-units.drv'...
building '/nix/store/66593hd41ga21c1arj5ch7izakv9ls9q-system-units.drv'...
building '/nix/store/gqvlfbqn77bx2brgacpxc1kh8lw52vk5-etc.drv'...
building '/nix/store/0drd1k1g1v2r380a2ib74vi8fcsbkmxk-nixos-system-tsvetan-23.11.7181.bacb8503d3a5.drv'...
/nix/store/dinb0xw1izk7wyh7ign2ds2ki2zi5ii7-nixos-system-tsvetan-23.11.7181.bacb8503d3a5
installing the boot loader...
/nix/store/0c337gsdfjf3162avbkchh0yh4qbs2s3-bash-5.2-p15/bin/bash: warning: setlocale: LC_ALL: cannot change locale (cs_CZ.UTF-8)
/nix/store/0c337gsdfjf3162avbkchh0yh4qbs2s3-bash-5.2-p15/bin/bash: warning: setlocale: LC_ALL: cannot change locale (cs_CZ.UTF-8)
/nix/store/0c337gsdfjf3162avbkchh0yh4qbs2s3-bash-5.2-p15/bin/bash: warning: setlocale: LC_ALL: cannot change locale (cs_CZ.UTF-8)
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = "cs_CZ.UTF-8",
	LC_MESSAGES = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
setting up /etc...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = "cs_CZ.UTF-8",
	LC_MESSAGES = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
/nix/var/nix/profiles/system/sw/bin/bash: warning: setlocale: LC_ALL: cannot change locale (cs_CZ.UTF-8)
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = "cs_CZ.UTF-8",
	LC_MESSAGES = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
/nix/store/0c337gsdfjf3162avbkchh0yh4qbs2s3-bash-5.2-p15/bin/bash: warning: setlocale: LC_ALL: cannot change locale (cs_CZ.UTF-8)
Initializing machine ID from random generator.
File system "/dev/mmcblk2p2" has wrong type for an EFI System Partition (ESP).
Traceback (most recent call last):
  File "/nix/store/wxz9ap7mlklyfnhphb1q8s8i5131b5sg-systemd-boot/bin/systemd-boot-builder", line 343, in <module>
    main()
  File "/nix/store/wxz9ap7mlklyfnhphb1q8s8i5131b5sg-systemd-boot/bin/systemd-boot-builder", line 331, in main
    install_bootloader(args)
  File "/nix/store/wxz9ap7mlklyfnhphb1q8s8i5131b5sg-systemd-boot/bin/systemd-boot-builder", line 256, in install_bootloader
    subprocess.check_call(["/nix/store/l533347li9f4zikb3lw9hpdcvxf2i811-systemd-254.10/bin/bootctl", "--esp-path=/boot"] + bootctl_flags + ["install"])
  File "/nix/store/ag5i94r7jjlyws36jmyl4kw0ps4lfgaw-python3-3.11.8/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/l533347li9f4zikb3lw9hpdcvxf2i811-systemd-254.10/bin/bootctl', '--esp-path=/boot', '--no-variables', 'install']' returned non-zero exit status 1.
/nix/store/0c337gsdfjf3162avbkchh0yh4qbs2s3-bash-5.2-p15/bin/bash: warning: setlocale: LC_ALL: cannot change locale (cs_CZ.UTF-8)
/nix/store/0c337gsdfjf3162avbkchh0yh4qbs2s3-bash-5.2-p15/bin/bash: warning: setlocale: LC_ALL: cannot change locale (cs_CZ.UTF-8)
/nix/store/0c337gsdfjf3162avbkchh0yh4qbs2s3-bash-5.2-p15/bin/bash: warning: setlocale: LC_ALL: cannot change locale (cs_CZ.UTF-8)
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = "cs_CZ.UTF-8",
	LC_MESSAGES = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
setting up /etc...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = "cs_CZ.UTF-8",
	LC_MESSAGES = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
/nix/var/nix/profiles/system/sw/bin/bash: warning: setlocale: LC_ALL: cannot change locale (cs_CZ.UTF-8)
/nix/store/0c337gsdfjf3162avbkchh0yh4qbs2s3-bash-5.2-p15/bin/bash: warning: setlocale: LC_ALL: cannot change locale (cs_CZ.UTF-8)
/nix/store/0c337gsdfjf3162avbkchh0yh4qbs2s3-bash-5.2-p15/bin/bash: warning: setlocale: LC_ALL: cannot change locale (cs_CZ.UTF-8)
/nix/store/0c337gsdfjf3162avbkchh0yh4qbs2s3-bash-5.2-p15/bin/bash: warning: setlocale: LC_ALL: cannot change locale (cs_CZ.UTF-8)
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = "cs_CZ.UTF-8",
	LC_MESSAGES = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
setting up /etc...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = "cs_CZ.UTF-8",
	LC_MESSAGES = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
/nix/var/nix/profiles/system/sw/bin/bash: warning: setlocale: LC_ALL: cannot change locale (cs_CZ.UTF-8)
setting root password...
New password:
Retype new password:
passwd: password updated successfully
installation finished!

[nix-shell:/mnt/etc/nixos]# cat /etc/os-release
PRETTY_NAME="Armbian 24.2.1 bookworm"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.armbian.com"
SUPPORT_URL="https://forum.armbian.com"
BUG_REPORT_URL="https://www.armbian.com/bugs"
ARMBIAN_PRETTY_NAME="Armbian 24.2.1 bookworm"

[nix-shell:/mnt/etc/nixos]# nix-shell -p nix-info --run "nix-info -m"
bash: warning: setlocale: LC_ALL: cannot change locale (cs_CZ.UTF-8)
/nix/store/0c337gsdfjf3162avbkchh0yh4qbs2s3-bash-5.2-p15/bin/bash: warning: setlocale: LC_ALL: cannot change locale (cs_CZ.UTF-8)
 - system: `"aarch64-linux"`
 - host os: `Linux 6.6.16-current-sunxi64, Debian GNU/Linux, 12 (bookworm), nobuild`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.8.0`
 - channels(root): `"nixpkgs-23.11"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`
```
