### ISSUE TITLE
attribute ‘bin’ missing when upgrading to latest unstable

### ISSUE THREAD

**Issue by simonvandel** [NixOS/nixpkgs#15036] opened 2016-04-27 17:04 UTC
## Issue description

When upgrading to the latest nixos version from the unstable channel, it fails with:

```
error: while evaluating the attribute ‘buildCommand’ of the derivation ‘nixos-system-vandel-beast-16.09pre82105.7465bcd’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/nixos/modules/system/activation/top-level.nix:102:7:
while evaluating the attribute ‘sources’ of the derivation ‘etc’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/nixos/modules/system/etc/etc.nix:12:5:
while evaluating anonymous function at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/nixos/modules/system/etc/etc.nix:20:20, called from undefined position:
while evaluating the attribute ‘source’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/attrsets.nix:199:44:
while evaluating anonymous function at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:74:45, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/attrsets.nix:199:52:
while evaluating the attribute ‘value’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:287:9:
while evaluating the option `environment.etc.systemd/system.source':
while evaluating the attribute ‘mergedValue’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:314:5:
while evaluating anonymous function at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:314:32, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:314:19:
while evaluating ‘check’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/types.nix:106:15, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:315:10:
while evaluating the attribute ‘buildCommand’ of the derivation ‘system-units’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/pkgs/build-support/trivial-builders.nix:10:14:
while evaluating the attribute ‘text’ of the derivation ‘unit-dbus.service’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/pkgs/build-support/trivial-builders.nix:10:14:
while evaluating the attribute ‘text’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/attrsets.nix:199:44:
while evaluating anonymous function at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:74:45, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/attrsets.nix:199:52:
while evaluating the attribute ‘value’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:287:9:
while evaluating the option `systemd.units.dbus.service.text':
while evaluating the attribute ‘isDefined’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:319:5:
while evaluating ‘filterOverrides’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:391:21, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:303:18:
while evaluating ‘concatMap’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/lists.nix:90:18, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:397:8:
while evaluating ‘concatMap’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/lists.nix:90:18, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:298:17:
while evaluating anonymous function at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:298:28, called from undefined position:
while evaluating ‘dischargeProperties’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:361:25, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:299:62:
while evaluating the attribute ‘value’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:199:48:
while evaluating the attribute ‘config.text’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/nixos/modules/system/boot/systemd.nix:310:7:
while evaluating ‘commonUnitText’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/nixos/modules/system/boot/systemd.nix:294:20, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/nixos/modules/system/boot/systemd.nix:310:14:
while evaluating ‘attrsToSection’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/nixos/modules/system/boot/systemd-lib.nix:90:20, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/nixos/modules/system/boot/systemd.nix:296:9:
while evaluating ‘mapAttrsToList’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/attrsets.nix:223:23, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/nixos/modules/system/boot/systemd-lib.nix:91:33:
while evaluating the attribute ‘unitConfig’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/attrsets.nix:199:44:
while evaluating anonymous function at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:74:45, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/attrsets.nix:199:52:
while evaluating the attribute ‘value’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:287:9:
while evaluating the option `systemd.services.dbus.unitConfig':
while evaluating the attribute ‘mergedValue’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:314:5:
while evaluating anonymous function at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:314:32, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:314:19:
while evaluating ‘merge’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/types.nix:132:20, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:317:8:
while evaluating ‘mapAttrs’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/attrsets.nix:198:17, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/types.nix:133:9:
while evaluating ‘filterAttrs’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/attrsets.nix:115:23, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/types.nix:133:35:
while evaluating ‘concatMap’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/lists.nix:90:18, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/attrsets.nix:116:18:
while evaluating anonymous function at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/attrsets.nix:116:29, called from undefined position:
while evaluating anonymous function at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/types.nix:133:51, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/attrsets.nix:116:62:
while evaluating the attribute ‘X-Restart-Triggers’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/attrsets.nix:329:7:
while evaluating anonymous function at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/types.nix:133:86, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/attrsets.nix:329:15:
while evaluating the attribute ‘optionalValue’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:321:5:
while evaluating ‘filterOverrides’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:391:21, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:303:18:
while evaluating ‘concatMap’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/lists.nix:90:18, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:397:8:
while evaluating ‘concatMap’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/lists.nix:90:18, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:298:17:
while evaluating anonymous function at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:298:28, called from undefined position:
while evaluating ‘dischargeProperties’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:361:25, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:299:62:
while evaluating the attribute ‘value’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/types.nix:138:55:
while evaluating the attribute ‘X-Restart-Triggers’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/nixos/modules/system/boot/systemd.nix:213:13:
while evaluating the attribute ‘buildCommand’ of the derivation ‘dbus-conf’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/nixos/modules/services/system/dbus.nix:14:5:
while evaluating ‘concatMapStrings’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/strings.nix:31:25, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/nixos/modules/services/system/dbus.nix:47:23:
while evaluating anonymous function at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/nixos/modules/services/system/dbus.nix:48:6, called from undefined position:
while evaluating anonymous function at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/types.nix:117:14, called from undefined position:
while evaluating the attribute ‘value’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:322:27:
while evaluating anonymous function at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:314:32, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:314:19:
while evaluating ‘check’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/types.nix:106:15, called from /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/lib/modules.nix:315:10:
while evaluating the attribute ‘pkgs’ of the derivation ‘system-path’ at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/pkgs/build-support/trivial-builders.nix:10:14:
while evaluating anonymous function at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/pkgs/build-support/buildenv/default.nix:57:21, called from undefined position:
attribute ‘bin’ missing, at /nix/store/m1nblhmhn4zgl4ydv1dxc4xfgnpq4s52-nixos-16.09pre82105.7465bcd/nixos/pkgs/build-support/buildenv/default.nix:57:30
```
### Steps to reproduce
1. Run `sudo nixos-rebuild switch --upgrade --show-trace`
2. See that it fails with the aforementioned error
## Technical details
- System: (NixOS: 16.09pre79453.32b7b00 (Flounder))
- Nix version: (nix-env (Nix) 1.11.2)
- Nixpkgs version: (16.09pre82105.7465bcd)

**Comment by simonvandel** [comment] 2016-04-27 17:06
I'm sorry, it was an issue on my part.

**Comment by simonvandel** [comment] 2016-04-27 17:11
I thought it was my own fault in my configuration, but now I'm not sure anymore. Does this sound like a legitimate issue?

**Comment by vcunat** [comment] 2016-04-27 17:25
Please, use `--show-trace` for this. Otherwise it's hard to track down exactly.

**Comment by simonvandel** [comment] 2016-04-27 17:28
Sorry, updated the issue with --show-trace enabled.

**Comment by simonvandel** [comment] 2016-04-27 20:14
Okay, so i nailed it down to this line in my config `(hunspellWithDicts (with hunspellDicts; [en-us en-gb-ise]))`, so the error is probably in pkgs/development/libraries/hunspell/wrapper.nix. I will look into it, when I find the time.

**Comment by laMudri** [comment] 2016-09-18 20:03
It seems that this problem is still around, and it is to do with `hunspellWithDicts`. The error message is shorter now:
```
$ nix-env -iA g.everything --show-trace
replacing old ‘everything’
installing ‘everything’
error: while evaluating the attribute ‘pkgs’ of the derivation ‘everything’ at /home/james/nixpkgs/pkgs/build-support/trivial-builders.nix:10:14:
while evaluating anonymous function at /home/james/nixpkgs/pkgs/build-support/buildenv/default.nix:57:21, called from undefined position:
attribute ‘bin’ missing, at /home/james/nixpkgs/pkgs/build-support/buildenv/default.nix:57:30
```
cc @Fuuzetsu as Hunspell maintainer.

**Comment by vcunat** [comment] 2016-09-18 20:16
This should have been fixed by 66de416b. The error messages don't seem to indicate anything hunspell-related.

**Comment by dezgeg** [comment] 2016-09-18 20:18
Hmm. Is it perhaps caused by `inherit (hunspell) meta;` bringing `outputsToInstall = [ "bin" ];` to the wrapper as well?

**Comment by vcunat** [comment] 2016-09-18 20:39
I see, I think. But still, my error is different:
```
installing ‘hunspell-with-dicts-1.3.3’
error: this derivation has bad ‘meta.outputsToInstall’
```

**Comment by vcunat** [comment] 2016-09-18 20:41
Well, now I'm getting no error in master.

**Comment by dezgeg** [comment] 2016-09-18 20:42
The original reporter's problem comes from the nixpkgs buildenv (which gets used when placed in systemPackages) I presume.

**Comment by dezgeg** [comment] 2017-08-16 23:17
AFAICT the problem was solved.

**Closed by dezgeg** 2017-08-16 23:17 UTC
Labels: 0.kind: bug, 6.topic: closure-size
