### ISSUE TITLE
Package request: CODELITE

### ISSUE THREAD

**Issue by EilTalrent** [NixOS/nixpkgs#250616] opened 2023-08-21 20:46 UTC
**Project description**

CodeLite is an open source, free, cross platform IDE, specialized in C, C++, Rust, Python, PHP and JavaScript (mainly for backend developers using Node.js) programming languages which runs best on all major Platforms ( OSX, Windows and Linux )

**Metadata**

* homepage URL: https://codelite.org/
* source URL: https://github.com/eranif/codelite
* license: gpl2+
* platforms: OSX, Windows, Linux

**Comment by romildo** [comment] 2023-08-22 19:11
Duplicate of https://github.com/NixOS/nixpkgs/issues/238337

**Closed by romildo** 2023-08-22 19:11 UTC
Labels: 0.kind: packaging request
