### ISSUE TITLE
wiki: Printers

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13300] opened 2016-02-21 19:05 UTC
https://nixos.org/wiki/Printers

**Comment by FRidh** [comment] 2016-02-21 19:20
Three months ago I used this to configure printing. This is a good article and should go into the manual

**Comment by abbradar** [comment] 2016-02-22 17:58
Notice that with recent updates it's enough just to have `services.printing.gutenprint = true` (and remove it from `drivers` if it's there) -- this will list all the supported printers in CUPS and also update PPDs on Gutenprint updates.

**Comment by aragnon** [comment] 2016-03-16 22:59
Having to specify a PPD file via some manual interface is *not* how users of NixOS expect to see things. In particular, it's not reproducible.

**Comment by abbradar** [comment] 2016-03-16 23:07
This is fixed now -- you can choose printer from the list, as you'd do in an ordinary Linux distribution. Use `services.printing.gutenprint` instead of `drivers = [ gutenprint ]` to get proper PPDs auto-updating.

**Comment by abbradar** [comment] 2016-03-16 23:08
(Notice that this doesn't fix the reproduciblity point -- that would be harder and would require generating PPDs from some Nix description)

**Comment by aragnon** [comment] 2016-03-16 23:11
I mean that I would like to configure a location where the PPD file can be found (e.g. on a server or file or .. ) and that would then automatically set it all up. Any amount of manual work should be seen as a non-solution.

**Comment by abbradar** [comment] 2016-03-16 23:19
Actually we can do that! This would just require copying those configured PPDs to their directory. I'll look at this later.

**Comment by ericsagnes** [comment] 2016-09-30 02:57
Note: This should be moved to [printing module](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/printing/cupsd.nix) `meta.doc`.

**Comment by garbas** [comment] 2016-10-03 23:20
@abbradar @FRidh what is the status of printing on nixos? which way is now correct?

**Comment by abbradar** [comment] 2016-10-04 08:52
I can write a small article on this in documentation later, but in a few words things work nicely now. You can turn on `services.printing.enable`, add drivers to `services.printing.drivers` (if I remember the option correctly). CUPS will discover drivers correctly and list them. For Gutenprint there's additional support to be enabled (`services.printing.gutenprint`) so that Gutenprint automatically updates already installed printers to use new version of itself.

**Comment by garbas** [comment] 2016-10-04 10:58
@abbradar :+1: awesome, tnx!

**Comment by olejorgenb** [comment] 2017-08-19 22:18
I've recently set up a network printer and created a [wiki page](https://github.com/nixos-users/wiki/wiki/Printing) in the new wiki in the process. (seems something should be mentioned about the gutenprint thing.

I can make an attempt at converting to doc book and a style more similar to the nixos manual. But I think I'll need some assistance getting the details correct and I'm away from any printer at least for a few months. (note to self: [meta.doc](https://nixos.org/nixos/manual/index.html#sec-meta-attributes))

[The old wiki page](https://web.archive.org/web/20160829175522/https://nixos.org/wiki/Printers)

**Comment by Ekleog** [comment] 2018-03-13 10:13
@olejorgenb I think if you could open a PR to the docs with at least the “Basic configuration” part of https://nixos.wiki/wiki/Printing (and the rest if you can confirm it's still up-to-date) it would be great!

About the gutenprint thing, I don't think it's required any longer, given “If this list contains Gutenprint (i.e. a derivation with meta.isGutenprint = true) the PPD files in /var/lib/cups/ppd will be updated automatically to avoid errors due to incompatible versions.” in the documentation for `services.printing.drivers`.

**Closed** 2018-06-23 19:03 UTC
