### ISSUE TITLE
localtime: Failed to start GeoClue2 Client

### ISSUE THREAD

**Issue by asbachb** [NixOS/nixpkgs#130555] opened 2021-07-18 14:37 UTC
**Describe the bug**
localtime service is not starting.

**To Reproduce**
1. `services.localtime.enable = true;`

**Expected behavior**
`localtime` should be able to start service

**Additional context**
```
Started Timezone Updater Daemon.
Jul 18 09:23:44 nixo-t14s localtimed[7770]: Failed to start GeoClue2 Client: 'localtimed' disallowed, no agent for UID 1001
Jul 18 09:23:44 nixo-t14s systemd[1]: localtime.service: Main process exited, code=exited, status=1/FAILURE
Jul 18 09:23:44 nixo-t14s systemd[1]: localtime.service: Failed with result 'exit-code'.
```

**Notify maintainers**
@deviant @Mic92 @michaelpj 

**Metadata**
```
asbachb@nixo-t14s  ~  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.2, NixOS, 21.11pre302265.c6c4a3d45ab (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(asbachb): `"nixos-21.05pre286647.4518794ee53, nixos-20.09-20.09.4025.dc326c78a93"`
 - channels(root): `"nixos-21.11pre302265.c6c4a3d45ab, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
* localtime
* geoclue
# a list of nixos modules affected by the problem
module:
* localtime
```

**Comment by deviant** [comment] 2021-07-19 13:09
I've known of this for a few months now, and believe it was caused by https://github.com/NixOS/nixpkgs/pull/117439. I didn't have time to figure out what was going on exactly at that point, but a similar solution to https://github.com/NixOS/nixpkgs/pull/129630 might be possible?

**Comment by dschrempf** [comment] 2022-04-16 05:14
I just tested the localtime daemon on `nixpkgs-unstable` and it works. I think we can close this issue!

**Closed** 2022-05-16 12:37 UTC
Labels: 0.kind: bug, 6.topic: nixos

**Comment by asbachb** [comment] 2022-05-21 20:44
@dschrempf @chreekat  Can you describe a little bit more why you think it's working?

localtime server seems to be started:
```
 ✘ asbachb@nixos-t14s  ~  systemctl status localtime.service
● localtime.service - Timezone Updater Daemon
     Loaded: loaded (/etc/systemd/system/localtime.service; enabled; vendor preset: enabled)
    Drop-In: /nix/store/l651pj6pd12n5p794f1g25g1h5d3cahl-system-units/localtime.service.d
             └─overrides.conf
     Active: active (running) since Sat 2022-05-21 22:37:00 CEST; 6min ago
   Main PID: 24237 (localtimed)
         IP: 0B in, 0B out
         IO: 96.0K read, 0B written
      Tasks: 9 (limit: 37555)
     Memory: 2.7M
        CPU: 44ms
     CGroup: /system.slice/localtime.service
             ├─24237 /nix/store/jixxg7b8pblyh60g7h9p4r3xvg440msz-localtime-unstable-2021-11-23/bin/localtimed
             └─24265 /nix/store/dy4xyn694jlvxw70ifpz9acp35nqkp1i-geoclue-2.5.7/libexec/geoclue-2.0/demos/agent

May 21 22:37:00 nixos-t14s systemd[1]: Started Timezone Updater Daemon.
``` 

But it seems to do nothing as geoclue seems to be broken:
```
 ✘ asbachb@nixos-t14s  ~  journalctl -u geoclue
May 21 22:37:00 nixos-t14s systemd[1]: Starting Location Lookup Service...
May 21 22:37:01 nixos-t14s .geoclue-wrappe[24245]: Failed to connect to avahi service: Daemon not running
May 21 22:37:01 nixos-t14s systemd[1]: Started Location Lookup Service.
May 21 22:38:11 nixos-t14s .geoclue-wrappe[24245]: g_object_unref: assertion 'old_ref > 0' failed
May 21 22:38:11 nixos-t14s .geoclue-wrappe[24245]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
May 21 22:38:33 nixos-t14s systemd[1]: geoclue.service: Main process exited, code=dumped, status=11/SEGV
May 21 22:38:33 nixos-t14s systemd[1]: geoclue.service: Failed with result 'core-dump'.
```

nixos-unstable

**Comment by dschrempf** [comment] 2022-05-21 22:40
Hm, everything is working here. I am also on `nixos-unstable`. I do use avahi though, that's a difference. Also, there should never be  a segmentation fault...

**Comment by chreekat** [comment] 2022-05-25 07:49
I think there may still be something wrong with localtime. For me at least, my machine doesn't actually update to the correct timezone.

However, this specific issue seems resolved ("localtime failed to start"), so maybe we need to open a different, more-specific ticket about the current problems.

**Comment by asbachb** [comment] 2022-05-25 08:34
I guess there are still multiple problems:

1) geoclue fails if you are on a non gnome environment
2) even if you disable the feature which is causes the avahi update the timezone is not adjusted

I guess you are right when we track these separately.

Note: I'm recently switched to tzupdate and configured it to run on every network connection which works quite well.

**Comment by chreekat** [comment] 2022-05-25 08:40
I know we're going really off-topic here, but when I try to run tzupdate, it tells my my timezone Europe/Helsinki "is not available on your operating system" :D Now I wonder where timezone information is supposed to come from....
