### ISSUE TITLE
Package request: Rill

### ISSUE THREAD

**Issue by rupurt** [NixOS/nixpkgs#365269] opened 2024-12-15 00:20 UTC
## Project description

Rill is a tool for effortlessly transforming data sets into powerful, opinionated dashboards using SQL. BI-as-code.

## Metadata

* homepage URL: https://www.rilldata.com/
* source URL: https://github.com/rilldata/rill
* license: apache-2.0
* platforms: unix, linux, darwin

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pluiedev** [comment] 2024-12-17 13:55
Duplicate of #322741 — let's try to keep it in one issue

**Closed by pluiedev** 2024-12-17 13:55 UTC
Labels: 6.topic: golang, 6.topic: nodejs, 0.kind: packaging request

**Comment by rupurt** [comment] 2024-12-17 15:37
My bad @pluiedev. Didn't check before :cry:
