### ISSUE TITLE
immersed-vr from unstable fails to run

### ISSUE THREAD

**Issue by djmaze** [NixOS/nixpkgs#267408] opened 2023-11-14 09:17 UTC
### Describe the bug
When running immersed-vr from unstable I get the following error output:

```
ps: error while loading shared libraries: libgpg-error.so.0: cannot open shared object file: No such file or directory
```

### Steps To Reproduce
1. `nix-shell -I nixpkgs=channel:nixpkgs-unstable -p immersed-vr --run immersed-vr`

### Expected behavior
Expecting the app to start and open its GUI.

### Notify maintainers

@haruki7049

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.44, NixOS, 23.05 (Stoat), 23.05.4720.78f3a4ae19f0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(martin): `"home-manager-23.05.tar.gz, nixos-23.05, nixpkgs-unstable"`
 - channels(root): `"nixos-23.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by djmaze** [comment] 2023-12-02 16:17
Still the same error for me. I will upgrade to NixOS 32.11 soon, but I guess that should not make a difference either.

**Comment by Xyz00777** [comment] 2023-12-07 23:10
i have an other problem but would also like to acompany you.
i used `nix-shell -p immersed-vr libva-utils linuxPackages.v4l2loopback` to run it temporar. But i still get the following two errors:
![Screenshot_20231208_000826](https://github.com/NixOS/nixpkgs/assets/52142054/f511a675-7d33-4ada-b40f-75263d2bd953)
if i click OK i get the following error:
![Screenshot_20231208_000915](https://github.com/NixOS/nixpkgs/assets/52142054/133bcb3d-8c01-453d-87a5-6090a725abd8)

My environment is:
`nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.63, NixOS, 24.05 (Uakari), 24.05pre552293.5a09cb4b393d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(xyz00777): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos``

**Comment by haruki7049** [comment] 2023-12-08 21:53
I have confirmed that error on my machine. However, I don't think that error is directly related to NixOS. One of those errors can be resolved by writing the following to `configuration.nix` and running `nixos-rebuild switch`
```
  boot = {
    extraModulePackages = with config.boot.kernelPackages; [
      v4l2loopback.out
    ];
    kernelModules = [
      "v4l2loopback"
    ];
    extraModprobeConfig = ''
      options v4l2loopback exclisive_caps=1 card_label="Virtual Camera"
    '';
```
So I assume that one of the errors, `Virtual camera device is not found at /dev/video0`, is something that cannot be resolved by the `nix-shell` command.

But I don't know how to resolve the other error... It seems to be solved by editing the `configuration.nix` as well...

My environment is here by running `nix-shell -p nix-info --run  "nix-info -m"`
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.64, NixOS, 23.11 (Tapir), 23.11.1209.933d7dc15509`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Xyz00777** [comment] 2023-12-10 21:34
these and a few additional configurations where neede on my system to make it work :)
`
  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
    extraPackages = with pkgs; [
      libva
      vaapiVdpau
      libvdpau-va-gl
    ];
  };
  networking.firewall.allowedTCPPorts = [
    21000
    21013
    ];
`
after that it worked :)

**Comment by haruki7049** [comment] 2023-12-10 22:13
I'm glad to help you :)

**Comment by iggyZiggy** [comment] 2024-03-08 11:20
i've fixed it by adding: libgpg-error to hardware.opengl.extraPackages along with other stuff from this thread :)

**Comment by Pandapip1** [comment] 2024-03-28 15:23
https://github.com/NixOS/nixpkgs/issues/299591 was a duplicate of this issue. Moving discussion here.

**Comment by haruki7049** [comment] 2024-04-09 12:13
The error is:
```ps: error while loading shared libraries: libgpg-error.so.0: cannot open shared object file: No such file or directory```

**Comment by haruki7049** [comment] 2024-10-19 04:05
The result of looking for `libgpg-error` in the root directory on a newly installed Ubuntu24.04.1 LTS for testing

```txt
/usr/share/locale-langpack/en_AU/LC_MESSAGES/libgpg-error.mo
/usr/share/locale-langpack/en_GB/LC_MESSAGES/libgpg-error.mo
/usr/share/doc/libgpg-error0
/usr/share/doc/libgpg-error0/copyright
/usr/share/doc/libgpg-error0/README.gz
/usr/share/doc/libgpg-error0/changelog.Debian.gz
/usr/share/doc/libgpg-error-l10n
/usr/share/doc/libgpg-error-l10n/copyright
/usr/share/doc/libgpg-error-l10n/README.gz
/usr/share/doc/libgpg-error-l10n/changelog.Debian.gz
/usr/lib/x86_64-linux-gnu/libgpg-error.so.0
/usr/lib/x86_64-linux-gnu/libgpg-error.so.0.34.0
/var/lib/dpkg/info/libgpg-error0:amd64.md5sums
/var/lib/dpkg/info/libgpg-error0:amd64.symbols
/var/lib/dpkg/info/libgpg-error0:amd64.shlibs
/var/lib/dpkg/info/libgpg-error0:amd64.list
/var/lib/dpkg/info/libgpg-error-l10n.list
/var/lib/dpkg/info/libgpg-error0:amd64.triggers
/var/lib/dpkg/info/libgpg-error-l10n.md5sums
/snap/gnome-42-2204/176/lib/x86_64-linux-gnu/libgpg-error.so.0
/snap/gnome-42-2204/176/usr/lib/x86_64-linux-gnu/libgpg-error.so
/snap/core22/1564/usr/lib/x86_64-linux-gnu/libgpg-error.so.0
/snap/core22/1564/usr/lib/x86_64-linux-gnu/libgpg-error.so.0.32.1
/snap/core22/1564/usr/share/doc/libgpg-error0
/snap/core22/1564/usr/share/doc/libgpg-error0/changelog.Debian.gz
/snap/core22/1564/usr/share/doc/libgpg-error0/copyright
```

**Closed** 2024-10-27 04:29 UTC
Labels: 0.kind: bug
