### ISSUE TITLE
Update request: cinny 3.2.0 → 4.0.3

### ISSUE THREAD

**Issue by ofalvai** [NixOS/nixpkgs#329859] opened 2024-07-25 09:24 UTC
- Package name: cinny
- Latest released version: 4.0.3

- Current version on the unstable channel: 3.2.0
- Current version on the stable/release channel: 3.2.0

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@Qyriad 

-----

Note for maintainers: Please tag this issue in your PR.

---

I tried a naive version bump in both the `cinny` and `cinny-desktop` packages, and even though the build was successful, I get the following error on darwin-aarch64, which is way beyond my understanding of Nix and the Cinny source:

![image](https://github.com/user-attachments/assets/ad8a2720-8f23-4872-9105-d1633991acc8)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by KaiserCalm** [comment] 2024-07-28 11:52
The update is out, but I am having the same issue with it as with your manual update.

**Comment by ryand56** [comment] 2024-07-29 03:25
Can't reproduce this. Maybe this is just a darwin issue?

**Comment by ryand56** [comment] 2024-08-04 21:30
FYI, Cinny v4.1.0 is out

**Comment by austinbutler** [comment] 2024-09-07 05:19
Since https://github.com/NixOS/nixpkgs/pull/334805 is merged, seems this can be closed.

**Closed by austinbutler** 2024-09-07 05:19 UTC
Labels: 9.needs: package (update)
