### ISSUE TITLE
builder for fontconfig-conf fails on unstable

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#95685] opened 2020-08-17 11:50 UTC
**Describe the bug**

When rebuilding my NixOS unstable system I am getting the following failure:

```
[...]
rm: cannot remove '/nix/store/pqxvjd0gmx9y8q91r4vr72m03l4gwx19-fontconfig-conf/etc/fonts/2.11/conf.d/50-user.conf': No such file or directory
builder for '/nix/store/ph3kzyfmyg7jzqfjxfqkblwqmy8dgvj5-fontconfig-conf.drv' failed with exit code 1
cannot build derivation '/nix/store/x8hqsd8hssd2nsbwywgv7pnbsc94832y-fontconfig-etc.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/s82vqjm59l8vwflly5i4isj7xd00y654-etc.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/zfxa5z84pyglzfkzq0g0i04z0n84gsww-nixos-system-romildo-20.09pre238896.16fc531784a.drv': 1 dependencies couldn't be built
error: build of '/nix/store/zfxa5z84pyglzfkzq0g0i04z0n84gsww-nixos-system-romildo-20.09pre238896.16fc531784a.drv' failed
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.14, NixOS, 20.09.git.6ecf3768a5e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre238896.16fc531784a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by flokli** [comment] 2020-08-17 19:14
Even with nixpkgs pointed precisely at `16fc531784a` (what this nixpkgs checkout seems to be at), I can't reproduce.

**Comment by flokli** [comment] 2020-08-17 19:16
I also tried building `nixos/tests/gnome3.nix`, which surely should pull in fontconfig.

**Comment by pbogdan** [comment] 2020-08-17 19:48
Same failure as romildo if I set `fonts.fontconfig.includeUserConf` to `false`. If I set it to true... https://github.com/NixOS/nixpkgs/issues/95712

**Comment by DIzFer** [comment] 2020-08-17 20:34
On 17/08/2020 21:48, pbogdan wrote:
> Same failure as romildo if I set `fonts.fontconfig.includeUserConf` to `false`. If I set it to true... https://github.com/NixOS/nixpkgs/issues/95712
> 

Yes, I forgot to add that the line in question seems to imply that
option triggers the `rm` command that fails.

More specifically, in nixos/modules/config/fonts/fontconfig.nix, I can
build my system if I comment out lines 207 to 209.

**Comment by romildo** [comment] 2020-08-17 20:43
> Same failure as romildo if I set `fonts.fontconfig.includeUserConf` to `false`. If I set it to `true`... #95712

I have this set to `false` on my system.

**Comment by flokli** [comment] 2020-08-17 21:13
It seems I missed parts of edf2541f02c6b24ea791710d5cadeae36f9b1a3a while rebasing https://github.com/NixOS/nixpkgs/pull/93562. Fix incoming.

**Comment by flokli** [comment] 2020-08-17 21:15
Should be fixed by https://github.com/NixOS/nixpkgs/pull/95716.

**Closed** 2020-08-17 21:24 UTC
Labels: 0.kind: bug
