### ISSUE TITLE
Package request: xdg-desktop-portal-termfilechooser

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#286177] opened 2024-02-03 23:31 UTC
**Project description**

 xdg-desktop-portal backend for choosing files with your favorite file chooser

**Metadata**

* homepage URL: https://github.com/GermainZ/xdg-desktop-portal-termfilechooser
* source URL: https://github.com/GermainZ/xdg-desktop-portal-termfilechooser
* license: mit
* platforms: linux, ...

([repology shows](https://repology.org/project/xdg-desktop-portal-termfilechooser/versions) this has previously been packaged in AUR)

**Comment by Tungsten842** [comment] 2024-02-04 13:19
duplicate of https://github.com/NixOS/nixpkgs/issues/213438

**Closed by Tungsten842** 2024-02-04 13:19 UTC
Labels: 0.kind: packaging request
