### ISSUE TITLE
Package request: Nekoray

### ISSUE THREAD

**Issue by BehradJi** [NixOS/nixpkgs#264943] opened 2023-11-02 06:12 UTC
**Project description**

This is a QT GUI for using V2ray or Sing-box backend proxies, and it is very useful for circumventing internet censorship.

**Metadata**

* homepage URL: https://github.com/MatsuriDayo/nekoray
* source URL: https://github.com/MatsuriDayo/nekoray
* license: GPL-3.0 
* platforms: Linux

**Comment by eclairevoyant** [comment] 2023-11-02 06:23
dupe of #244451

**Closed by eclairevoyant** 2023-11-02 06:23 UTC
Labels: 0.kind: packaging request
