### ISSUE TITLE
Support Bazel on macOS

### ISSUE THREAD

**Issue by TravisWhitaker** [NixOS/nixpkgs#32080] opened 2017-11-26 17:58 UTC
In principle it should be possible to build Bazel from source on macOS. Bazel itself is quite a mess to patch, since `xcrun` is sometimes invoked from the PATH, sometimes absolutely from `/usr/bin`, and sometimes via an `xcrunwrapper.sh` script.

What has me stumped is that Bazel grabs a bunch of dependencies whose build systems also rely on `xcrun`, particularly protobuf and grpc. Many of the calls don't straightforwardly do something like `/usr/bin/xcrun clang ...`, but instead query various SDK locations and feed them into further wrapper scripts. Unfortunately the only success I've had has been allowing these build systems access to `/usr/bin/xcrun`. For my use case an impure-but-working Bazel derivation on Darwin is better than no working Bazel derivation on Darwin, especially considering that the impurity is confined to Xcode's CLT and libraries. From what I understand there are two reasonable paths forward.

- Accept this impurity on Darwin, but do so in a principled way. Surely there's some existing idiomatic way of doing this. I've seen mention of a "pure Darwin stdenv" and an "impure Darwin stdenv" in discussions elsewhere, but I can't seem to find any documentation on these.

- Build some heavyweight hacks into the Bazel build system. This might be something like inserting extra machinery to patch the external dependencies that Bazel grabs, or perhaps writing a fake `xcrun` command. I think this would involve a lot of work for questionable benefit; because of Xcode it seems that larger degree of impurity tends to be acceptable when it comes to Darwin in Nixpkgs at large.

@copumpkin and @abbradar, I'm curious about your thoughts.

**Comment by williammpratt** [comment] 2017-11-27 21:06
I am not happy with heavy divergence of NixOS configurations. If upstream cannot make a system that works based on standards, then I am not interested in using it, let alone increasing the size of the NixOS repository with workarounds. 

Why do you want to use it? Is Bazel so unique that you cannot do without?

There is an issue over 1.5 years old to remove /bin/bash references. It appears that portability has no priority for them. They do seem to accept shell script improvements, so there is hope.

**Comment by TravisWhitaker** [comment] 2017-11-27 21:23
Regrettably, I'm tied to Bazel because of TensorFlow. Furthermore, I'm calling TF from C++ (already a use case poorly supported upstream), for which none of upstream's binary distributions are suitable given my hardware, so I must build TF from source. It's only due to Nix that deploying this monstrosity works at all. A while ago there were a few community supported alternative build systems for TF, but they've all diverged too much for my use case. A working Bazel derivation on macOS would allow my colleagues to build our application and run tests locally without a virtual machine.

It is indeed a shame that the "state of the art" in machine learning is in such a pitiful state.

**Comment by williammpratt** [comment] 2017-11-27 22:11
OK, those are reasonable reasons. 

It turns out you don't actually need to know anything about computing to make a machine learning library. If you already made a cost calculation compared to the alternatives, I'd suggest you become good buddies with the Bazel maintainers and patch it to the point that it somewhat acceptable. Their third_party directory being present is also not what you typically want to see. 

One way to achieve this is to send in a few PRs to them and then send a message to their mailing list to get someone on board for getting your patches in with priority over others. 

Have you seen https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake?

**Comment by grahamc** [comment] 2017-12-07 01:04
For what it is worth, williammpratt's attitude here is not representative of the NixOS community's attitude toward other software. The user has since been blocked from the NixOS organization.

**Comment by jyp** [comment] 2018-01-03 13:52
Probably a duplicate of #30590

**Comment by pSub** [comment] 2018-03-24 19:11
Closing this issue in favor of #30590.

**Closed by pSub** 2018-03-24 19:11 UTC
