### ISSUE TITLE
Build failure: transmission

### ISSUE THREAD

**Issue by ProxyVT** [NixOS/nixpkgs#326140] opened 2024-07-10 15:51 UTC
### Steps To Reproduce

1. `services.transmission.enable = true`
    or
2. `nix run nixpkgs#transmission`

### Build log

```
error: builder for '/nix/store/aly8w8ip0vfi7sc854wypdmbdkm5wynv-transmission-3.00.drv' failed with exit code 2;
       last 10 log lines:
       >   197 |         if (UPNP_GetValidIGD(devlist, &handle->urls, &handle->data, handle->lanaddr,
       >       |             ^~~~~~~~~~~~~~~~
       > In file included from /build/source/libtransmission/upnp.c:12:
       > /nix/store/vmzxminj8mwfw81whay2524c4b6w321q-miniupnpc-2.2.8/include/miniupnpc/miniupnpc.h:122:1: note: declared here
       >   122 | UPNP_GetValidIGD(struct UPNPDev * devlist,
       >       | ^~~~~~~~~~~~~~~~
       > make[2]: *** [libtransmission/CMakeFiles/transmission.dir/build.make:804: libtransmission/CMakeFiles/transmission.dir/upnp.c.o] Error 1
       > make[2]: *** Waiting for unfinished jobs....
       > make[1]: *** [CMakeFiles/Makefile2:206: libtransmission/CMakeFiles/transmission.dir/all] Error 2
       > make: *** [Makefile:166: all] Error 2
       For full logs, run 'nix log /nix/store/aly8w8ip0vfi7sc854wypdmbdkm5wynv-transmission-3.00.drv'.
```

### Additional context

This affects both `transmission_3` and `transmission_4` packages.

### Notify maintainers

@astsmtl

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.8, NixOS, 24.11 (Vicuna), 24.11.20240709.feb2849`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/xr9wjzx0cdnwkmhzz74h8lphgn5jmyv3-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-07-10 16:15
Can't repro on `master` (0bd7ea1ab5f3bf35acf37f4c82d812aed86746d5) or `nixos-unstable` (655a58a72a6601292512670343087c2d75d859c1)

**Comment by eclairevoyant** [comment] 2024-07-10 16:28
Root cause: https://github.com/transmission/transmission/pull/6907#issuecomment-2158664001
Fixed in https://github.com/NixOS/nixpkgs/pull/326057

**Closed by eclairevoyant** 2024-07-10 16:28 UTC
Labels: 9.needs: reporter feedback, 0.kind: build failure
