### ISSUE TITLE
Build failure: jetbrains.jdk

### ISSUE THREAD

**Issue by andreaugustoaragao** [NixOS/nixpkgs#231341] opened 2023-05-11 20:00 UTC
### Steps To Reproduce

1. build jetbrains.jdk

### Build log

```
[6/257] Building CXX object libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.o
FAILED: libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.o
/nix/store/fsn9mccnjinl212ypa3rx8b8647s9klh-gcc-wrapper-12.2.0/bin/g++ -DCEF_USE_SANDBOX -DNDEBUG -DWRAPPING_CEF_SHARED -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -I/build/source/third_party/cef/cef_binary_104.4.26+g4180781+chromium-104.0.5112.102_linux64_minimal -O3 -DNDEBUG -fno-strict-aliasing -fPIC -fstack-protector -funwind-tables -fvisibility=hidden --param=ssp-buffer-size=4 -pipe -pthread -Wall -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-error=comment -Wno-comment -Wno-deprecated-declarations -m64 -march=x86-64 -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -std=c++14 -Wsign-compare -Wno-undefined-var-template -Wno-literal-suffix -Wno-narrowing -Wno-attributes -O2 -fdata-sections -ffunction-sections -fno-ident -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -MD -MT libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.o -MF libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.o.d -o libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.o -c /build/source/third_party/cef/cef_binary_104.4.26+g4180781+chromium-104.0.5112.102_linux64_minimal/libcef_dll/base/cef_lock.cc
g++: error: unrecognized command-line option '-m64'
ninja: build stopped: subcommand failed.
error: builder for '/nix/store/a7r53z6050vvhlmwnxac6c6kp41gcz2g-jcef-jetbrains-654.drv' failed with exit code 1;
       last 10 log lines:
       > g++: error: unrecognized command-line option '-m64'
       > [5/257] Building CXX object libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_callback_internal.cc.o
       > FAILED: libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_callback_internal.cc.o
       > /nix/store/fsn9mccnjinl212ypa3rx8b8647s9klh-gcc-wrapper-12.2.0/bin/g++ -DCEF_USE_SANDBOX -DNDEBUG -DWRAPPING_CEF_SHARED -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -I/build/source/third_party/cef/cef_binary_104.4.26+g4180781+chromium-104.0.5112.102_linux64_minimal -O3 -DNDEBUG -fno-strict-aliasing -fPIC -fstack-protector -funwind-tables -fvisibility=hidden --param=ssp-buffer-size=4 -pipe -pthread -Wall -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-error=comment -Wno-comment -Wno-deprecated-declarations -m64 -march=x86-64 -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -std=c++14 -Wsign-compare -Wno-undefined-var-template -Wno-literal-suffix -Wno-narrowing -Wno-attributes -O2 -fdata-sections -ffunction-sections -fno-ident -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -MD -MT libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_callback_internal.cc.o -MF libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_callback_internal.cc.o.d -o libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_callback_internal.cc.o -c /build/source/third_party/cef/cef_binary_104.4.26+g4180781+chromium-104.0.5112.102_linux64_minimal/libcef_dll/base/cef_callback_internal.cc
       > g++: error: unrecognized command-line option '-m64'
       > [6/257] Building CXX object libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.o
       > FAILED: libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.o
       > /nix/store/fsn9mccnjinl212ypa3rx8b8647s9klh-gcc-wrapper-12.2.0/bin/g++ -DCEF_USE_SANDBOX -DNDEBUG -DWRAPPING_CEF_SHARED -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -I/build/source/third_party/cef/cef_binary_104.4.26+g4180781+chromium-104.0.5112.102_linux64_minimal -O3 -DNDEBUG -fno-strict-aliasing -fPIC -fstack-protector -funwind-tables -fvisibility=hidden --param=ssp-buffer-size=4 -pipe -pthread -Wall -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-error=comment -Wno-comment -Wno-deprecated-declarations -m64 -march=x86-64 -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -std=c++14 -Wsign-compare -Wno-undefined-var-template -Wno-literal-suffix -Wno-narrowing -Wno-attributes -O2 -fdata-sections -ffunction-sections -fno-ident -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -MD -MT libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.o -MF libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.o.d -o libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.o -c /build/source/third_party/cef/cef_binary_104.4.26+g4180781+chromium-104.0.5112.102_linux64_minimal/libcef_dll/base/cef_lock.cc
       > g++: error: unrecognized command-line option '-m64'
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/a7r53z6050vvhlmwnxac6c6kp41gcz2g-jcef-jetbrains-654.drv'.
error: 1 dependencies of derivation '/nix/store/9mds0h6675lnh8hgam63xycvv8lrb01v-jetbrains-jdk-jcef-17.0.6-b829.5.drv' failed to build
```

### Additional context

This seems to happen during cef compilation. I can see these added to the g++ like "-m64 -march=x86-64". I'm using aarch64-linux - it should not be use x86-64.

### Notify maintainers
@edwtjo 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/mp8kz9wc1jnx1hxgvq0rxz2nyzjxmxq2-nix-info
copying path '/nix/store/mp8kz9wc1jnx1hxgvq0rxz2nyzjxmxq2-nix-info' from 'https://cache.nixos.org'...
 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.27, NixOS, 23.05 (Stoat), 23.05pre482756.12ba1a5f90b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(aragao): `""`
 - channels(root): `"nixos, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by MaxHearnden** [comment] 2023-05-12 12:47
This is caused by x86 specific code in https://github.com/NixOS/nixpkgs/pull/196738

**Comment by JohnRTitor** [comment] 2024-09-15 17:59
Closing, please reopen if it's still an issue.

**Closed** 2024-09-17 03:23 UTC
Labels: 0.kind: build failure
