### ISSUE TITLE
Jitsi fails to show anything

### ISSUE THREAD

**Issue by aragnon** [NixOS/nixpkgs#3482] opened 2014-08-07 07:47 UTC
Using jitsi-2.4.4997 on Ubuntu Precise I get the following:

`$ jitsi`

`14:43:06.925 SEVERE: [13] org.jitsi.impl.neomedia.device.DeviceConfiguration.error() Failed to register custom Renderer org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRe
nderer with JMF.
java.lang.IllegalStateException: audioSystem
        at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer.<init>(PulseAudioRenderer.java:105)
        at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer.<init>(PulseAudioRenderer.java:85)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:374)
        at org.jitsi.impl.neomedia.device.DeviceConfiguration.registerCustomRenderers(DeviceConfiguration.java:1028)
        at org.jitsi.impl.neomedia.device.DeviceConfiguration.<init>(DeviceConfiguration.java:355)
        at org.jitsi.impl.neomedia.MediaServiceImpl.<init>(MediaServiceImpl.java:141)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:374)
        at org.jitsi.impl.libjitsi.LibJitsiImpl.getService(LibJitsiImpl.java:133)
        at org.jitsi.impl.libjitsi.LibJitsiOSGiImpl.getService(LibJitsiOSGiImpl.java:86)
        at org.jitsi.service.libjitsi.LibJitsi.invokeGetServiceOnImpl(LibJitsi.java:163)
        at org.jitsi.service.libjitsi.LibJitsi.getMediaService(LibJitsi.java:115)
        at net.java.sip.communicator.impl.neomedia.NeomediaActivator.start(NeomediaActivator.java:380)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:629)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:1904)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:1822)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1192)
        at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:266)
        at java.lang.Thread.run(Thread.java:745)
14:43:06.929 SEVERE: [13] org.jitsi.impl.neomedia.device.DeviceConfiguration.error() Failed to register custom Renderer org.jitsi.impl.neomedia.jmfext.media.renderer.video.JAWTRenderer
 with JMF.
java.lang.UnsatisfiedLinkError: /nix/store/4lmjhyh1rbn90w1klmmms66f5jf857d5-jitsi-2.4.4997/lib/native/linux-64/libjnawtrenderer.so: libjawt.so: cannot open shared object file: No such
file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1880)
        at java.lang.Runtime.loadLibrary0(Runtime.java:849)
        at java.lang.System.loadLibrary(System.java:1088)
        at org.jitsi.impl.neomedia.jmfext.media.renderer.video.JAWTRenderer.<clinit>(JAWTRenderer.java:90)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:190)
        at org.jitsi.impl.neomedia.device.DeviceConfiguration.registerCustomRenderers(DeviceConfiguration.java:1028)
        at org.jitsi.impl.neomedia.device.DeviceConfiguration.<init>(DeviceConfiguration.java:355)
        at org.jitsi.impl.neomedia.MediaServiceImpl.<init>(MediaServiceImpl.java:141)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:374)
        at org.jitsi.impl.libjitsi.LibJitsiImpl.getService(LibJitsiImpl.java:133)
        at org.jitsi.impl.libjitsi.LibJitsiOSGiImpl.getService(LibJitsiOSGiImpl.java:86)
        at org.jitsi.service.libjitsi.LibJitsi.invokeGetServiceOnImpl(LibJitsi.java:163)
        at org.jitsi.service.libjitsi.LibJitsi.getMediaService(LibJitsi.java:115)
        at net.java.sip.communicator.impl.neomedia.NeomediaActivator.start(NeomediaActivator.java:380)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:629)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:1904)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:1822)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1192)
        at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:266)
        at java.lang.Thread.run(Thread.java:745)
Fontconfig warning: line 26: empty font directory name ignored
14:43:07.192 SEVERE: [13] impl.osdependent.SystemTray.getDefaultDesktop().62 Failed to initialize the java.awt.SystemTray implementation.
java.lang.UnsupportedOperationException: java.lang.reflect.InvocationTargetException
        at net.java.sip.communicator.impl.osdependent.Desktop$AWTDesktopPeer.<init>(Desktop.java:180)
        at net.java.sip.communicator.impl.osdependent.Desktop.getDefaultDesktop(Desktop.java:58)
        at net.java.sip.communicator.impl.osdependent.DesktopServiceImpl.<init>(DesktopServiceImpl.java:30)
        at net.java.sip.communicator.impl.osdependent.OsDependentActivator.start(OsDependentActivator.java:87)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:629)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:1904)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:1822)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1192)
        at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:266)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at net.java.sip.communicator.impl.osdependent.Desktop$AWTDesktopPeer.<init>(Desktop.java:172)
        ... 9 more
Caused by: java.lang.UnsupportedOperationException: Desktop API is not supported on the current platform
        at java.awt.Desktop.getDesktop(Desktop.java:144)
        ... 14 more
14:43:07.193 SEVERE: [13] impl.osdependent.SystemTray.getDefaultDesktop().70 Failed to initialize the desktop.tray implementation.
java.lang.UnsupportedOperationException: Failed to initialize the desktop.tray implementation.
        at net.java.sip.communicator.impl.osdependent.Desktop.getDefaultDesktop(Desktop.java:72)
        at net.java.sip.communicator.impl.osdependent.DesktopServiceImpl.<init>(DesktopServiceImpl.java:30)
        at net.java.sip.communicator.impl.osdependent.OsDependentActivator.start(OsDependentActivator.java:87)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:629)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:1904)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:1822)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1192)
        at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:266)
        at java.lang.Thread.run(Thread.java:745)
14:43:07.560 SEVERE: [38] util.UtilActivator.uncaughtException().108 An uncaught exception occurred in thread=Thread[AWT-EventQueue-0,6,main] and message was: null
java.lang.NullPointerException
        at sun.awt.X11FontManager.getDefaultPlatformFont(X11FontManager.java:779)
        at sun.font.SunFontManager$2.run(SunFontManager.java:433)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.font.SunFontManager.<init>(SunFontManager.java:376)
        at sun.awt.X11FontManager.<init>(X11FontManager.java:32)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:374)
        at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
        at sun.font.SunFontManager.getInstance(SunFontManager.java:250)
        at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:264)
        at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1027)
        at javax.swing.JComponent.getFontMetrics(JComponent.java:1624)
        at net.java.sip.communicator.plugin.desktoputil.ComponentUtils.getStringWidth(ComponentUtils.java:33)
        at net.java.sip.communicator.impl.gui.main.presence.GlobalStatusSelectorBox.fitSizeToText(GlobalStatusSelectorBox.java:501)
        at net.java.sip.communicator.impl.gui.main.presence.GlobalStatusSelectorBox.<init>(GlobalStatusSelectorBox.java:131)
        at net.java.sip.communicator.impl.gui.main.presence.AccountStatusPanel.<init>(AccountStatusPanel.java:146)
        at net.java.sip.communicator.impl.gui.main.MainFrame.<init>(MainFrame.java:188)
        at net.java.sip.communicator.impl.gui.UIServiceImpl.loadApplicationGui(UIServiceImpl.java:147)
        at net.java.sip.communicator.impl.gui.GuiActivator$1.run(GuiActivator.java:165)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
        at java.awt.EventQueue.access$200(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:694)
        at java.awt.EventQueue$3.run(EventQueue.java:692)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
^Cjava.lang.IllegalArgumentException: Listener is null
        at org.apache.felix.framework.util.EventDispatcher.removeListener(EventDispatcher.java:298)
        at org.apache.felix.framework.Felix.removeServiceListener(Felix.java:2875)
        at org.apache.felix.framework.BundleContextImpl.removeServiceListener(BundleContextImpl.java:258)
        at net.java.sip.communicator.impl.argdelegation.ArgDelegationActivator.stop(ArgDelegationActivator.java:125)
        at org.apache.felix.framework.util.SecureAction.stopActivator(SecureAction.java:651)
        at org.apache.felix.framework.Felix.stopBundle(Felix.java:2278)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1215)
        at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:266)
        at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Listener is null
        at org.apache.felix.framework.util.EventDispatcher.removeListener(EventDispatcher.java:298)
        at org.apache.felix.framework.Felix.removeServiceListener(Felix.java:2875)
        at org.apache.felix.framework.BundleContextImpl.removeServiceListener(BundleContextImpl.java:258)
        at net.java.sip.communicator.impl.argdelegation.ArgDelegationActivator.stop(ArgDelegationActivator.java:125)
        at org.apache.felix.framework.util.SecureAction.stopActivator(SecureAction.java:651)
        at org.apache.felix.framework.Felix.stopBundle(Felix.java:2278)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1215)
        at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:266)
        at java.lang.Thread.run(Thread.java:745)`

**Comment by khumba** [comment] 2015-09-09 16:51
On NixOS 15.09 I get similar error messages.  Jitsi's GUI does appear (after applying #9754), and my webcam is recognized, but no audio system is detected, despite having Pulseaudio enabled.  The audio options are `audiosilence` or `None`.  @aragnon, what's the status of this for you?

    09:35:50.654 SEVERE: [15] org.jitsi.impl.neomedia.device.DeviceConfiguration.error() Failed to register custom Renderer org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer with JMF.
    java.lang.IllegalStateException: audioSystem
        at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer.<init>(PulseAudioRenderer.java:112)
        at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer.<init>(PulseAudioRenderer.java:92)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at org.jitsi.impl.neomedia.device.DeviceConfiguration.registerCustomRenderers(DeviceConfiguration.java:1036)
        at org.jitsi.impl.neomedia.device.DeviceConfiguration.<init>(DeviceConfiguration.java:355)
        at org.jitsi.impl.neomedia.MediaServiceImpl.<init>(MediaServiceImpl.java:150)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at org.jitsi.impl.libjitsi.LibJitsiImpl.getService(LibJitsiImpl.java:142)
        at org.jitsi.impl.libjitsi.LibJitsiOSGiImpl.getService(LibJitsiOSGiImpl.java:86)
        at org.jitsi.service.libjitsi.LibJitsi.invokeGetServiceOnImpl(LibJitsi.java:163)
        at org.jitsi.service.libjitsi.LibJitsi.getMediaService(LibJitsi.java:115)
        at net.java.sip.communicator.impl.neomedia.NeomediaActivator.start(NeomediaActivator.java:380)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2152)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2070)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1297)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
        at java.lang.Thread.run(Thread.java:745)
    09:35:50.658 SEVERE: [15] org.jitsi.impl.neomedia.device.DeviceConfiguration.error() Failed to register custom Renderer org.jitsi.impl.neomedia.jmfext.media.renderer.video.JAWTRenderer with JMF.
    java.lang.UnsatisfiedLinkError: /nix/store/cg9c1az93gc94i89g9ir256538ij1j9c-jitsi-2.8.5426/lib/native/linux-64/libjnawtrenderer.so: libjawt.so: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1854)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.jitsi.impl.neomedia.jmfext.media.renderer.video.JAWTRenderer.<clinit>(JAWTRenderer.java:90)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.jitsi.impl.neomedia.device.DeviceConfiguration.registerCustomRenderers(DeviceConfiguration.java:1036)
        at org.jitsi.impl.neomedia.device.DeviceConfiguration.<init>(DeviceConfiguration.java:355)
        at org.jitsi.impl.neomedia.MediaServiceImpl.<init>(MediaServiceImpl.java:150)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at org.jitsi.impl.libjitsi.LibJitsiImpl.getService(LibJitsiImpl.java:142)
        at org.jitsi.impl.libjitsi.LibJitsiOSGiImpl.getService(LibJitsiOSGiImpl.java:86)
        at org.jitsi.service.libjitsi.LibJitsi.invokeGetServiceOnImpl(LibJitsi.java:163)
        at org.jitsi.service.libjitsi.LibJitsi.getMediaService(LibJitsi.java:115)
        at net.java.sip.communicator.impl.neomedia.NeomediaActivator.start(NeomediaActivator.java:380)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2152)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2070)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1297)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
        at java.lang.Thread.run(Thread.java:745)
    09:35:50.793 SEVERE: [30] util.UtilActivator.uncaughtException().108 An uncaught exception occurred in thread=Thread[Thread-12,5,main] and message was: null
    java.lang.NullPointerException
        at org.jitsi.impl.neomedia.transform.zrtp.ZrtpFortunaEntropyGatherer$GatherAudio.run(ZrtpFortunaEntropyGatherer.java:267)
    09:35:51.747 SEVERE: [15] impl.osdependent.SystemTray.getDefaultDesktop().62 Failed to initialize the java.awt.SystemTray implementation.
    java.lang.UnsupportedOperationException: java.lang.reflect.InvocationTargetException
        at net.java.sip.communicator.impl.osdependent.Desktop$AWTDesktopPeer.<init>(Desktop.java:180)
        at net.java.sip.communicator.impl.osdependent.Desktop.getDefaultDesktop(Desktop.java:58)
        at net.java.sip.communicator.impl.osdependent.DesktopServiceImpl.<init>(DesktopServiceImpl.java:30)
        at net.java.sip.communicator.impl.osdependent.OsDependentActivator.start(OsDependentActivator.java:170)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2152)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2070)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1297)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
        at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at net.java.sip.communicator.impl.osdependent.Desktop$AWTDesktopPeer.<init>(Desktop.java:172)
        ... 9 more
    Caused by: java.lang.UnsupportedOperationException: Desktop API is not supported on the current platform
        at java.awt.Desktop.getDesktop(Desktop.java:144)
        ... 14 more
    09:35:51.747 SEVERE: [15] impl.osdependent.SystemTray.getDefaultDesktop().70 Failed to initialize the desktop.tray implementation.
    java.lang.UnsupportedOperationException: Failed to initialize the desktop.tray implementation.
        at net.java.sip.communicator.impl.osdependent.Desktop.getDefaultDesktop(Desktop.java:72)
        at net.java.sip.communicator.impl.osdependent.DesktopServiceImpl.<init>(DesktopServiceImpl.java:30)
        at net.java.sip.communicator.impl.osdependent.OsDependentActivator.start(OsDependentActivator.java:170)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2152)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2070)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1297)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
        at java.lang.Thread.run(Thread.java:745)
    java.lang.UnsatisfiedLinkError: /nix/store/cg9c1az93gc94i89g9ir256538ij1j9c-jitsi-2.8.5426/lib/native/linux-64/libglobalshortcut.so: libstdc++.so.6: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1854)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at net.java.sip.communicator.impl.globalshortcut.NativeKeyboardHook.<clinit>(NativeKeyboardHook.java:254)
        at net.java.sip.communicator.impl.globalshortcut.GlobalShortcutServiceImpl.<init>(GlobalShortcutServiceImpl.java:56)
        at net.java.sip.communicator.impl.globalshortcut.GlobalShortcutActivator.start(GlobalShortcutActivator.java:101)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2152)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2070)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1297)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
        at java.lang.Thread.run(Thread.java:745)
    java.lang.UnsatisfiedLinkError: /nix/store/cg9c1az93gc94i89g9ir256538ij1j9c-jitsi-2.8.5426/lib/native/linux-64/libjdic_misc.so: libstdc++.so.6: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1854)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.jdesktop.jdic.misc.impl.LinuxAlerter.<init>(LinuxAlerter.java:48)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at org.jdesktop.jdic.misc.Alerter.loadLinux(Unknown Source)
        at org.jdesktop.jdic.misc.Alerter.newInstance(Unknown Source)
        at net.java.sip.communicator.plugin.chatalerter.ChatAlerterActivator.start(ChatAlerterActivator.java:88)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2152)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2070)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1297)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
        at java.lang.Thread.run(Thread.java:745)

**Comment by vcunat** [comment] 2015-09-17 18:24
Was this fixed by #9785?

**Comment by khumba** [comment] 2015-09-17 19:07
@aragnon had two errors that I didn't:

    Fontconfig warning: line 26: empty font directory name
    ...
    14:43:07.560 SEVERE: [38] util.UtilActivator.uncaughtException().108 An uncaught exception occurred in thread=Thread[AWT-EventQueue-0,6,main] and message was: null
    java.lang.NullPointerException
        at sun.awt.X11FontManager.getDefaultPlatformFont(X11FontManager.java:779)
        at sun.font.SunFontManager$2.run(SunFontManager.java:433)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.font.SunFontManager.<init>(SunFontManager.java:376)
        at sun.awt.X11FontManager.<init>(X11FontManager.java:32)
        ...

I haven't run Nix outside of NixOS yet, so I can't say whether it's fixed right now, but if it's still present then it's a problem interacting with that environment, and fonts not loading seems like a good reason for a GUI not to appear.  (#9785 fixed the errors I saw except for the system tray ones.)

**Comment by vcunat** [comment] 2015-09-17 19:15
That fontconfig warning is harmless IIRC.

**Comment by khumba** [comment] 2015-09-18 02:58
I think this issue is independent of my fix after all.  I installed
Nix and Jitsi in a fresh 12.04 VM and Jitsi opened up fine on
nixpkgs-stable (nixpkgs-16.03pre68896.135fc6a), which is before that
got merged.

Then again, Jitsi did start for me, so maybe something else was fixed
in the meantime.

**Comment by Profpatsch** [comment] 2016-07-23 15:19
(triage) do these problems still appear?

**Comment by khumba** [comment] 2016-07-28 04:48
Last time I tried ^, I got some of the same warnings, but I was never able to reproduce.  I think this is obsolete now.

**Comment by fpletz** [comment] 2016-07-28 09:47
Works for me, too.

**Closed by fpletz** 2016-07-28 09:47 UTC
Labels: 0.kind: bug
