### ISSUE TITLE
urxvt segfaults on i686

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#20185] opened 2016-11-05 12:48 UTC
## Issue description

When I run ``urxvt &`` on i686, it runs until I open the second one.
The second and all following shortly flash on screen, kill any running one, and give ``segmentation fault  urxvt``.

Similarly ``urxvtd`` runs normally, and if no ``urxvt(c)`` windows have been opened, ``urxvtc`` runs fine, but the following ones give ``segmentation fault  urxvtd``.

## Technical details

* System: 16.09.git.8b0e91d (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "16.09.741.354fd37"

**Comment by pSub** [comment] 2018-03-26 16:02
Does this still happen? I cannot test it since I don't have access to an i686 machine.

**Comment by magnetophon** [comment] 2018-03-26 18:25
I don't know, I'm not using urxvt nor a i686 anymore.
Shall I close the issue?

**Comment by pSub** [comment] 2018-07-15 19:46
Closing. If someone is able to reproduce it, please reopen or comment.

**Closed by pSub** 2018-07-15 19:46 UTC
Labels: 0.kind: bug

**Comment by igoodkit** [comment] 2020-09-09 17:33
hello!
seems like I have the same error on my pc
kernel: urxvt[83465]: segfault at 170 ip 00007efee91574ed sp 00007ffcd77d4140 error 4 in libc-2.32.so[7efee913e000+14d000]
░░ This usually indicates a programming error in the crashing program and
