### ISSUE TITLE
Package request: libadwaita-without-adwaita

### ISSUE THREAD

**Issue by PeraltaBoi** [NixOS/nixpkgs#314976] opened 2024-05-27 01:54 UTC
**Project description**

libadwaita; Includes a patch to not overwrite the system theme

**Metadata**

* homepage URL: doesn't apply
* source URL: https://aur.archlinux.org/libadwaita-without-adwaita-git.git
* license: LGPL-2.1-or-later 
* platforms: Linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-05-27 14:27
duplicate of #270458

**Closed** 2024-05-28 18:55 UTC
Labels: 0.kind: packaging request
