### ISSUE TITLE
find -perm /mode doesn't work on Darwin

### ISSUE THREAD

**Issue by tohl** [NixOS/nixpkgs#9044] opened 2015-07-29 16:12 UTC
nix works on cygwin but nixpkgs use a deprecated syntax which does not work with the latest cygwin anymore.

-perm +0100 should be -perm /0100

EDIT: after doing that change, Darwin has problems, likely due to using some ancient version of findutils.

**Comment by vcunat** [comment] 2015-07-30 08:35
Man pages confirm it being deprecated on all platforms, thanks! Staged.

@domenkozar: there was a stdenv rebuild scheduled in staging and now there's another one &ndash; would you make Hydra not rebuild all twice?

**Comment by domenkozar** [comment] 2015-07-30 08:36
sure

**Comment by vcunat** [comment] 2015-07-30 08:39
Hmm, maybe most of the former rebuild has happened already. I can't really tell with the new queuing semantics. https://github.com/NixOS/hydra/issues/190#issuecomment-122644897 Anyway, it will be good to have this fixed in the upcoming release, 15.08 I'd call it ;-)

**Comment by dhess** [comment] 2015-08-28 22:22
This change breaks OS X:

patching script interpreter paths in /nix/store/ry1xfxg5rm02caqzszjidqrgvzhp75hg-zlib-1.2.8
find: -perm: /0100: illegal mode string

**Comment by vcunat** [comment] 2015-08-29 06:05
Yeah, apparently. There was a discussion recently on the commit. It looks like we traded darwin for cygwin, but I believe darwin's find is what should get fixed (updated).

**Comment by tohl** [comment] 2015-08-29 07:34
Because it is using wrong find, not from findutils but whatever find
happens to be installed on the native OS, which is wrong.  It should be
using find from findutils as we should not assume anything about
programs which are not under nix control.

Reverting this commit would be a fix in the wrong direction.

Does anybody have an idea, how to fix it properly?

**Comment by tohl** [comment] 2015-08-29 07:40
Maybe it works on cygwin by chance too, simply because cygwin is using
the same find from findutils.

It is probably using whatever find happens to be in the path.

It might be enough to ensure, that find from findutils (the right find)
is in the path.

**Comment by zimbatm** [comment] 2015-08-30 21:44
findutils is supposed to be part of the stdenv but for some reason it's not picked-up on OSX

**Comment by vcunat** [comment] 2015-08-30 22:05
I don't know how darwin stdenv is built... it could be that during bootstrapping some different/older version of findutils is used.

**Comment by zimbatm** [comment] 2015-08-30 22:19
Yes the issue is that patch-shebangs.sh depends on the new findutils which isn't available during stage2. I also don't see the findutils being installed during the various stages of the darwin stdenv. It's a bit of a chicken and egg problem since the installation of findutils probably depends on the patch-shebang script.

```
# just bumped the version of gnused
$ nix-env -i gnused
...
<snip>
post-installation fixup
gzipping man pages in /nix/store/x8pgpksr958s0f38rvisd4a5rhlmgr4q-gnused-4.2.3
stripping (with flags -S) in /nix/store/x8pgpksr958s0f38rvisd4a5rhlmgr4q-gnused-4.2.3/bin
patching script interpreter paths in /nix/store/x8pgpksr958s0f38rvisd4a5rhlmgr4q-gnused-4.2.3
find: -perm: /0100: illegal mode string
builder for ‘/nix/store/1lvg7wh5sn49mlvhybnf2w6dahs585l2-gnused-4.2.3.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/x5wldl9cyikkfam14n90j3mz1zvbipp1-stdenv-darwin-boot-2.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/ci70ld20jmixqirnagk34pxdf7nr6qwy-bash-4.3-p39.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/730ksrpcl6qw39p9jgw8dw4iivg5vm10-bzip2-1.0.6.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/ijxjyayxnbxbxnsjj5va2q0qb3m3q80w-clang-wrapper-3.6.2.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/kcs02csvc5vmsg3idfrrinxqz1lym695-coreutils-8.24.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/k07d1zlwa0y728hxyslma2zr1bl45hs9-diffutils-3.3.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/wsx86lh8aarsval7dldv28rzfq6qyrl2-findutils-4.4.2.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/b72cpkf9i7rk2zpp2hwib5g0qxprn4dq-gawk-4.1.3.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/d9vcszrpxvhq04147kvv5m87bgvdbw20-gnugrep-2.21.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/c70m5dxlp2f22lxr6ps7rcr4blb3pi60-gnumake-4.1.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/j6x3rkd32cjd112d5ik3ia2jpqw7vsyj-gnused-4.2.3.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/3ir5936xlrnmiymbx6181c199k4hkj41-gnutar-1.28.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/7yq5hz3jwm7ppnrd8v14m85hj95x5h6k-gzip-1.6.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/1gmnhy003k5cxqh5xnd7k4ggs1rzg5zq-patch-2.7.5.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/71a3zh5iiyg4qm37ab52jkbxln751rb1-xz-5.2.1.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/hyw5h86xcf586jaj2vx9xs190zrgyhdv-gnused-4.2.3.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/hyw5h86xcf586jaj2vx9xs190zrgyhdv-gnused-4.2.3.drv’ failed
```

**Comment by zimbatm** [comment] 2015-08-30 22:32
Most of our invocations are to find executable scripts which is probably better expressed as `find -type f -executable`. BSD find (OSX) doesn't support that flag unfortunately.

According to the findutils-4.4.2 man pages the `-perm +` option is deprecated because of unexpected behaviour when using symbolic values but we always use numeric values. Also the + option is part of the POSIX standard so it's probably here to stay for a long time. Maybe it would be easier to revert until the darwin-pure environment is finished ?

**Comment by vcunat** [comment] 2015-08-31 07:05
Complete reverting would (reportedly) break cygwin, which has less users, probably, but it's still not too good. Perhaps revert only on darwin (to minimize rebuilding ATM and preserve cygwin) and only the needed files (to minimize pairs of almost-same scripts)?

**Comment by edolstra** [comment] 2015-08-31 09:36
Breaking Darwin would be a major regression, so it might be best to revert this, unless somebody has a quick fix.

**Comment by zimbatm** [comment] 2015-08-31 10:18
What version of findutils is cygwin using ? Nix is packaging the latest GNU
release which still supports the deprecated format.

**Comment by dredozubov** [comment] 2015-08-31 13:49
+1 on reverting it, this is a major pain on darwin and it's supposedly got a larger userbase

**Comment by domenkozar** [comment] 2015-08-31 18:38
+1 for reverting only for darwin and a bug to fix darwin stdenv

**Comment by tohl** [comment] 2015-09-01 21:36
> Yes the issue is that patch-shebangs.sh depends on the new
> findutils which isn't available during stage2. I also don't see
> the findutils being installed during the various stages of the
> darwin stdenv. It's a bit of a chicken and egg problem since the
> installation of findutils probably depends on the patch-shebang
> script.

Shouldn't the find (or whole findutils) be somehow part of the
bootstrapping tools instead of depending on host OS programs?
E.g. busybox has a find applet.  Or is that one not suitable?  Or we
don't use busybox for bootstrapping?

**Comment by zimbatm** [comment] 2015-09-01 22:23
It might be in the darwin-pure environment but it's not there yet.

Also:
```
$ busybox find -perm /0100
find: invalid mode '/0100'
```

**Comment by zimbatm** [comment] 2015-09-02 10:51
@dredozubov did you submit a PR for the revert ?

**Comment by dredozubov** [comment] 2015-09-02 11:37
No, i wasn't sure it was agreed upon. Can do this anytime if it's okay.

**Comment by vcunat** [comment] 2015-09-03 07:00
Are you sure `-executable` wouldn't work for **our** darwin bootstrap? A downside to that would be breaking (other) BSDs most likely, but reports of using those with nix are very scarce.

**Comment by zimbatm** [comment] 2015-09-03 09:31
`-exectuable` is not supported by BSD find (and thus OSX)

**Comment by vcunat** [comment] 2015-09-03 09:36
I had read that from you before, but I thought we use something else than darwin's native find during bootstrapping (maybe busybox).

**Comment by zimbatm** [comment] 2015-09-03 12:58
Darwin bootstrap uses the system find. `busybox find` doesn't support `-executable` either.

**Comment by tohl** [comment] 2015-09-04 06:46
> Darwin bootstrap uses the system find.

Isn't this the core of the problem?  Shouldn't be this functionality
implemented directly in nix?

**Comment by vcunat** [comment] 2015-09-04 07:03
I suppose you mean nixpkgs. Anyway, bootstrapping is a tricky thing. We *do* already have a decent proposal of a cross-platform solution/workaround in the discussion at #9603.

**Comment by chamini2** [comment] 2015-09-04 15:20
Is there a workaround for this?

**Comment by vcunat** [comment] 2015-09-04 15:32
@chamini2: yes, e.g. revert that patch, as #9603 suggests.

**Comment by taku0** [comment] 2015-09-06 02:18
How about using `-0100` instead of `/0100` or `+0100`?
`-` finds files with "All of the permission bits mode are set for the file" while `/` finds "Any of the permission bits mode are set for the file". Since we specify only one bit, it makes no difference.

**Comment by vcunat** [comment] 2015-09-06 09:30
You win! I staged 8f33b8cc, so Darwin users can follow staging for now.

Thanks to all who helped resolving this painful issue.

**Comment by vcunat** [comment] 2015-09-06 09:32
I think we don't need to patch this on 15.09, as the releases weren't meant (and built) for darwin so far, and the bash patches (and perhaps other changes) will make master stdenv diverge from 15.09 anyway...

**Closed** 2015-09-15 19:18 UTC
Labels: bug, darwin, mass-darwin-rebuild

**Comment by domenkozar** [comment] 2015-09-15 19:20
@vcunat we've decided to also patch 15.09 as LogicBlox and others are using stable channel for also darwin builds.
