### ISSUE TITLE
Package request: tabby

### ISSUE THREAD

**Issue by Kamchatskiy** [NixOS/nixpkgs#310937] opened 2024-05-11 21:49 UTC
**Project description**

 A terminal for a more modern age 

**Metadata**

* homepage URL: https://github.com/Eugeny/tabby
* source URL: https://github.com/Eugeny/tabby
* license: mit
* platforms: unix, linux, windows

**Comment by qwqawawow** [comment] 2024-05-12 12:02
See also https://github.com/NixOS/nixpkgs/pull/303924

**Comment by gepbird** [comment] 2024-10-05 17:55
Duplicate of https://github.com/NixOS/nixpkgs/issues/233509

**Closed by gepbird** 2024-10-05 17:55 UTC
Labels: 0.kind: packaging request
