### ISSUE TITLE
Build failure: swift

### ISSUE THREAD

**Issue by victorhooi** [NixOS/nixpkgs#326204] opened 2024-07-10 22:10 UTC
### Steps To Reproduce

1. Run `nix flake update`, then `nix run ./#build-switch` (part of [this Nix template](https://github.com/dustinlyons/nixos-config))
2. Wait for the `swift` build to fail.

### Build log

This is the console output:
```
❯ nix run ./#build-switch
warning: Git tree '/Users/foobar/nixos-config' is dirty
Running build-switch for aarch64-darwin
Starting build...
warning: Git tree '/Users/foobar/nixos-config' is dirty
error: builder for '/nix/store/64g6qq719bwlrjyqv1rgzf1h9hqyk32x-swift-5.8.drv' failed with exit code 1;
       last 10 log lines:
       > FAILED: stdlib/toolchain/Compatibility50/CMakeFiles/swiftCompatibility50-macosx-arm64.dir/Overrides.cpp.o
       > /tmp/nix-build-swift-5.8.drv-5/build/llvm/./bin/clang++ -DCMARK_STATIC_DEFINE -DGTEST_HAS_RTTI=0 -DLLVM_DISABLE_ABI_BREAKING_CHECKS_ENFORCING=1 -DSWIFT_INLINE_NAMESPACE=__runtime -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/nix-build-swift-5.8.drv-5/build/swift/stdlib/toolchain/Compatibility50 -I/tmp/nix-build-swift-5.8.drv-5/src/swift/stdlib/toolchain/Compatibility50 -I/private/tmp/nix-build-swift-5.8.drv-5/src/swift/stdlib/include -I/private/tmp/nix-build-swift-5.8.drv-5/src/swift/stdlib/public/SwiftShims -I/tmp/nix-build-swift-5.8.drv-5/build/swift/include -I/private/tmp/nix-build-swift-5.8.drv-5/src/swift/include -I/tmp/nix-build-swift-5.8.drv-5/build/llvm/include -I/tmp/nix-build-swift-5.8.drv-5/src/llvm-project/clang/include -I/tmp/nix-build-swift-5.8.drv-5/build/llvm/tools/clang/include -I/tmp/nix-build-swift-5.8.drv-5/src/swift-cmark/src/include -I/tmp/nix-build-swift-5.8.drv-5/build/swift-cmark/src -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -fdiagnostics-color -Werror=switch -Wdocumentation -Wimplicit-fallthrough -Wunreachable-code -Woverloaded-virtual -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -O3 -DNDEBUG -std=c++14 -arch arm64 -isysroot /nix/store/5pdnz640hmvkdd98psa7n0m7zsdh0msc-SDKs/MacOSX10.15.sdk -fvisibility=hidden -fvisibility-inlines-hidden  -fno-exceptions -fno-rtti -Werror=gnu -Werror=c++98-compat-extra-semi -fno-sanitize=all -Wall -Wglobal-constructors -Wexit-time-destructors -DSWIFT_COMPATIBILITY_LIBRARY=1 -DSWIFT_THREADING_IS_COMPATIBILITY_LIBRARY -DSWIFT_TARGET_LIBRARY_NAME=swiftCompatibility50 -DSWIFT_RUNTIME -target arm64-apple-macosx10.9 -isysroot /nix/store/5pdnz640hmvkdd98psa7n0m7zsdh0msc-SDKs/MacOSX10.15.sdk -F/nix/store/5pdnz640hmvkdd98psa7n0m7zsdh0msc-SDKs/MacOSX10.15.sdk/../../../Developer/Library/Frameworks -O2 -g0 -DNDEBUG -DSWIFT_LIBRARY_EVOLUTION=1 -DSWIFT_STDLIB_SUPPORT_BACK_DEPLOYMENT -DSWIFT_ENABLE_REFLECTION -DSWIFT_STDLIB_HAS_DLADDR -DSWIFT_STDLIB_HAS_DARWIN_LIBMALLOC=1 -DSWIFT_STDLIB_HAS_ASL -DSWIFT_STDLIB_HAS_STDIN -DSWIFT_STDLIB_HAS_ENVIRON -DSWIFT_STDLIB_HAS_LOCALE -DSWIFT_THREADING_DARWIN -DSWIFT_RUNTIME_OS_VERSIONING -DSWIFT_STDLIB_SHORT_MANGLING_LOOKUPS -DSWIFT_STDLIB_ENABLE_VECTOR_TYPES -DSWIFT_STDLIB_HAS_TYPE_PRINTING -DSWIFT_STDLIB_SUPPORTS_BACKTRACE_REPORTING -D SWIFT_STDLIB_ENABLE_UNICODE_DATA -DSWIFT_STDLIB_CONCURRENCY_TRACING -MD -MT stdlib/toolchain/Compatibility50/CMakeFiles/swiftCompatibility50-macosx-arm64.dir/Overrides.cpp.o -MF stdlib/toolchain/Compatibility50/CMakeFiles/swiftCompatibility50-macosx-arm64.dir/Overrides.cpp.o.d -o stdlib/toolchain/Compatibility50/CMakeFiles/swiftCompatibility50-macosx-arm64.dir/Overrides.cpp.o -c /tmp/nix-build-swift-5.8.drv-5/src/swift/stdlib/toolchain/Compatibility50/Overrides.cpp
       > clang-15-unwrapped: warning: overriding '-mmacos-version-min=10.15' option with '-target arm64-apple-macosx10.9' [-Woverriding-t-option]
       > clang-15-unwrapped: error: unsupported option '-fzero-call-used-regs=used-gpr' for target 'arm64-apple-macosx10.9.0'
       > [34/1354] Building CXX object stdlib/toolchain/Compatibility56/CMakeFiles/swiftCompatibility56-macosx-arm64.dir/Concurrency/Error.cpp.o
       > FAILED: stdlib/toolchain/Compatibility56/CMakeFiles/swiftCompatibility56-macosx-arm64.dir/Concurrency/Error.cpp.o
       > /tmp/nix-build-swift-5.8.drv-5/build/llvm/./bin/clang++ -DCMARK_STATIC_DEFINE -DGTEST_HAS_RTTI=0 -DLLVM_DISABLE_ABI_BREAKING_CHECKS_ENFORCING=1 -DSWIFT_COMPATIBILITY56 -DSWIFT_INLINE_NAMESPACE=__runtime -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/nix-build-swift-5.8.drv-5/build/swift/stdlib/toolchain/Compatibility56 -I/tmp/nix-build-swift-5.8.drv-5/src/swift/stdlib/toolchain/Compatibility56 -I/private/tmp/nix-build-swift-5.8.drv-5/src/swift/stdlib/include -I/private/tmp/nix-build-swift-5.8.drv-5/src/swift/stdlib/public/SwiftShims -I/tmp/nix-build-swift-5.8.drv-5/build/swift/include -I/private/tmp/nix-build-swift-5.8.drv-5/src/swift/include -I/tmp/nix-build-swift-5.8.drv-5/build/llvm/include -I/tmp/nix-build-swift-5.8.drv-5/src/llvm-project/clang/include -I/tmp/nix-build-swift-5.8.drv-5/build/llvm/tools/clang/include -I/tmp/nix-build-swift-5.8.drv-5/src/swift-cmark/src/include -I/tmp/nix-build-swift-5.8.drv-5/build/swift-cmark/src -I/tmp/nix-build-swift-5.8.drv-5/src/swift/stdlib/toolchain/Compatibility56/include -I/tmp/nix-build-swift-5.8.drv-5/src/swift/stdlib -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -fdiagnostics-color -Werror=switch -Wdocumentation -Wimplicit-fallthrough -Wunreachable-code -Woverloaded-virtual -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -O3 -DNDEBUG -std=c++14 -arch arm64 -isysroot /nix/store/5pdnz640hmvkdd98psa7n0m7zsdh0msc-SDKs/MacOSX10.15.sdk -fvisibility=hidden -fvisibility-inlines-hidden  -fno-exceptions -fno-rtti -Werror=gnu -Werror=c++98-compat-extra-semi -fno-sanitize=all -Wall -Wglobal-constructors -Wexit-time-destructors -DSWIFT_COMPATIBILITY_LIBRARY=1 -D__STDC_WANT_LIB_EXT1__=1 -DSWIFT_THREADING_IS_COMPATIBILITY_LIBRARY -DSWIFT_TARGET_LIBRARY_NAME=swiftCompatibility56 -DSWIFT_RUNTIME -target arm64-apple-macosx10.9 -isysroot /nix/store/5pdnz640hmvkdd98psa7n0m7zsdh0msc-SDKs/MacOSX10.15.sdk -F/nix/store/5pdnz640hmvkdd98psa7n0m7zsdh0msc-SDKs/MacOSX10.15.sdk/../../../Developer/Library/Frameworks -O2 -g0 -DNDEBUG -DSWIFT_LIBRARY_EVOLUTION=1 -DSWIFT_STDLIB_SUPPORT_BACK_DEPLOYMENT -DSWIFT_ENABLE_REFLECTION -DSWIFT_STDLIB_HAS_DLADDR -DSWIFT_STDLIB_HAS_DARWIN_LIBMALLOC=1 -DSWIFT_STDLIB_HAS_ASL -DSWIFT_STDLIB_HAS_STDIN -DSWIFT_STDLIB_HAS_ENVIRON -DSWIFT_STDLIB_HAS_LOCALE -DSWIFT_THREADING_DARWIN -DSWIFT_RUNTIME_OS_VERSIONING -DSWIFT_STDLIB_SHORT_MANGLING_LOOKUPS -DSWIFT_STDLIB_ENABLE_VECTOR_TYPES -DSWIFT_STDLIB_HAS_TYPE_PRINTING -DSWIFT_STDLIB_SUPPORTS_BACKTRACE_REPORTING -D SWIFT_STDLIB_ENABLE_UNICODE_DATA -DSWIFT_STDLIB_CONCURRENCY_TRACING -MD -MT stdlib/toolchain/Compatibility56/CMakeFiles/swiftCompatibility56-macosx-arm64.dir/Concurrency/Error.cpp.o -MF stdlib/toolchain/Compatibility56/CMakeFiles/swiftCompatibility56-macosx-arm64.dir/Concurrency/Error.cpp.o.d -o stdlib/toolchain/Compatibility56/CMakeFiles/swiftCompatibility56-macosx-arm64.dir/Concurrency/Error.cpp.o -c /tmp/nix-build-swift-5.8.drv-5/src/swift/stdlib/toolchain/Compatibility56/Concurrency/Error.cpp
       > clang-15-unwrapped: warning: overriding '-mmacos-version-min=10.15' option with '-target arm64-apple-macosx10.9' [-Woverriding-t-option]
       > clang-15-unwrapped: error: unsupported option '-fzero-call-used-regs=used-gpr' for target 'arm64-apple-macosx10.9.0'
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/64g6qq719bwlrjyqv1rgzf1h9hqyk32x-swift-5.8.drv'.
error: 1 dependencies of derivation '/nix/store/4dlmh6viviksr2dr46b95mxr11mrjc3k-fix-stdlib-path.patch.drv' failed to build
error: 1 dependencies of derivation '/nix/store/czvn66v1kb07yq87964k33vkxfvh1m3b-swift-wrapper-5.8.drv' failed to build
error: 1 dependencies of derivation '/nix/store/r75gcy2hykwv79nwz5hh6hpkhl7bxvhx-swift-wrapper-5.8.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7yip9avpwivhp4qf4zyy3gqyy2gisi11-dockutil-3.1.3.drv' failed to build
error: 1 dependencies of derivation '/nix/store/v8ksxfyg8kpsmrx877mbljzr2zfxi61i-darwin-system-24.11.20240708.655a58a+darwin4.cf297a8.drv' failed to build
```

Here is a link to `nix log /nix/store/64g6qq719bwlrjyqv1rgzf1h9hqyk32x-swift-5.8.drv`:

https://gist.github.com/victorhooi/dbddbfd3a1d3dcdba1574a0add3f9cef

### Notify maintainers

@trofi @stephank @domenkozar @symphorien @dduan @trepetti @Trundle @dtzWill 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
error:
       … while calling the 'import' builtin
         at «string»:1:18:
            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (nix-info) ]; } ""
             |                  ^

       … while realising the context of a path

       … while calling the 'findFile' builtin
         at «string»:1:25:
            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (nix-info) ]; } ""
             |                         ^

       error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

nixos-config on  main [!] 
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by khaneliman** [comment] 2024-07-10 22:17
Duplicate of https://github.com/NixOS/nixpkgs/issues/320900

**Closed by khaneliman** 2024-07-10 22:17 UTC
Labels: 0.kind: build failure
