### ISSUE TITLE
Tracking issue: Electron: Ozone/Wayland broken with wlroots 0.15

### ISSUE THREAD

**Issue by Synthetica9** [NixOS/nixpkgs#156352] opened 2022-01-23 19:43 UTC
### Description

wlroots 0.15 introduced version 4 of the wl_output protocol, which older electron versions don't support in combination with `--enable-features=UseOzonePlatform --ozone-platform=wayland`. This results in a crash on startup.

Related issues:

- #151902
- #147557 

### Packages affected

- [x] chromium
- [x] google-chrome
- [ ] vscodium
- [ ] vscode
- [ ] discord
- [ ] element-desktop
- [ ] schildi-chat
- [ ] signal-desktop
- [ ] slack
- [ ] plexamp
- [ ] brave

(maintainers: feel free to add any missing ones)

**Comment by primeos** [comment] 2022-01-23 20:56
Thanks @Synthetica9 for tracking this via an issue.

Electron 17 should be fine (at least once it's released at the beginning of next month) and we've requested a backport of the fixes to Electron version 16 here: https://github.com/electron/electron/issues/32487
I've helped cherry-picking the patches but I cannot test the result: https://github.com/electron/electron/issues/32487#issuecomment-1018848455
If someone has time and motivation that should be the best place to address this (since we cannot easily patch Electron in Nixpkgs, AFAIK - if we even have an Electron package built from source).

Also: There's also another Electron regression to look out for: https://github.com/NixOS/nixpkgs/pull/154003/commits/e06082eda06ee586de17e0a060e8cd0eddd20c69 (hopefully it won't affect Electron 17 as well... :o - this time it's really a regression in Electron but it only seems to affect packages of Linux distribution so it might/should be fixable on our side)

**Comment by theanonymousexyz** [comment] 2022-01-27 16:47
@primeos although not on NixOS, I've confirmed this to affect Signal Desktop, VSCodium and Brave as well.

**Comment by Synthetica9** [comment] 2022-01-27 17:08
> @primeos although not on NixOS, I've confirmed this to affect Signal Desktop, VSCodium and Brave as well.

Yep, can confirm. Added brave to the list.

**Comment by primeos** [comment] 2022-02-04 22:59
https://github.com/electron/electron/releases/tag/v17.0.0 contains the necessary fixes for this issue.

However, Ozone/Wayland is still broken, unfortunately (should also affect wlroots 0.14, etc. but I didn't test that).

> Also: There's also another Electron regression to look out for: https://github.com/NixOS/nixpkgs/commit/e06082eda06ee586de17e0a060e8cd0eddd20c69 (hopefully it won't affect Electron 17 as well... :o - this time it's really a regression in Electron but it only seems to affect packages of Linux distribution so it might/should be fixable on our side)

@Synthetica9 if you can confirm that issue with wlroots 0.14 we could also close this issue in favor of https://github.com/NixOS/nixpkgs/issues/158175 as that seems to be the bigger issue (should affect any Wayland compositor).

**Comment by maxhille** [comment] 2022-02-15 09:52
`google-chrome-stable` runs fine for me when run with `google-chrome-stable --features=UseOzonePlatform -ozone-platform=wayland`

```
~ $ google-chrome-stable --version
Google Chrome 98.0.4758.80
~ $ sway --version
sway version 1.7
```

**Comment by primeos** [comment] 2022-02-15 21:34
@maxhille oh, the title should've mentioned Electron - Google Chrome is indeed fine (or was - I had issues with hardware accelerated rendering but it could depend on the GPU drivers).
Anyway, I'll close this in favor of https://github.com/NixOS/nixpkgs/issues/158175 then (as mentioned earlier).

**Closed by primeos** 2022-02-15 21:34 UTC
Labels: 0.kind: bug, 0.kind: regression
