### ISSUE TITLE
nixos-install fails with getting attributes of path /nix/store/...: No such file or directory

### ISSUE THREAD

**Issue by Artturin** [NixOS/nixpkgs#126141] opened 2021-06-08 01:51 UTC
**Describe the bug**
during nixos-install a error appears ```getting attributes of path /nix/store/...: No such file or directory```
the person who told me about this is @epsyle 
i was using his dotfiles to test https://github.com/epsyle/snowflake/tree/c13f37ac19942bdcc3ddced28015b47b10e1f6b2

i did this in a vm and he did it on hw

**To Reproduce**
1. boot `nixos-minimal-21.05.804.5de44c15758-x86_64-linux.iso`
2. create a root partition
3. add fira-code in to your systemPackages
4. nixos-install

**Expected behavior**
install should work

**Screenshots**
![Screenshot_nixos-unstable_2021-06-08_02:34:54](https://user-images.githubusercontent.com/56650223/121108127-dba5af80-c811-11eb-8d62-2a41e516ec42.png)

**Additional context**
after `nix-build '<nixpkgs>' -A fira-code` or `nix-shell -p fira-code` the install will continue until there's a another error of the same type which can be fixed by doing the same thing
![Screenshot_nixos-unstable_2021-06-08_04:29:14](https://user-images.githubusercontent.com/56650223/121108255-1ad40080-c812-11eb-882f-ad9b46eb3514.png)
`nix-store --repair-path /nix/store/41qphrp1ksc1fqm01i7khs30n1zjl56r-fira-code-5.2` would fix it too

I hope this issue will help new people who are searching for a fix

Maybe related https://github.com/NixOS/nix/issues/1281

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.40, NixOS, 21.05.804.5de44c15758 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.804.5de44c15758"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Artturin** [comment] 2021-06-08 01:56
closing since this is a nix issue and there's a issue in the nix repo already
i made this because people will probably search for a fix to this in nixpkgs instead of nix

**Comment by Artturin** [comment] 2021-06-09 19:29
seen 3 people with the same issue in the last 2 days

**Comment by Artturin** [comment] 2021-06-15 18:05
a workaround by @jonringer 
first 
```
nix-build '<nixpkgs/nixos>' -A config.system.build.toplevel -I nixos-config=/mnt/etc/nixos/configuration.nix
```
let it complete
and then run `sudo nixos-install`

**Comment by jonringer** [comment] 2021-06-15 18:11
does `nix-build '<nixpkgs/nixos>' -A config.system.build.toplevel -I nixos-config=/mnt/etc/nixos/configuration.nix` then re-running `nixos-install` fix the issue?

Curious if flakification efforts of `nixos-install` caused some regressions.

**Comment by jonringer** [comment] 2021-06-15 18:12
oops, just noticed you posted it as well :)

**Comment by jonringer** [comment] 2021-06-15 18:18
Going to pin this issue until there's a better resolution of this, but many people have been having this issue.

**Comment by jonringer** [comment] 2021-06-15 19:06
cc @edolstra @jtojnar

**Comment by liamwhite** [comment] 2021-06-16 01:34
> Curious if flakification efforts of `nixos-install` caused some regressions.

Maybe, but it can be reproduced without using nixos-install at all. See nix bug: https://github.com/NixOS/nix/issues/4912

**Comment by jonringer** [comment] 2021-06-16 02:58
It's quite possible. The `nixos-install` script hasn't seen much iteration over the past few months. Much more likely there's a regression in the `nix-cli`

**Comment by ryantm** [comment] 2021-06-16 15:43
Related: https://discourse.nixos.org/t/21-05-not-installing/13547/9

**Comment by rnhmjoj** [comment] 2021-06-20 09:21
Did anyone figure this out? I've only be able to complete the installation by commeting out sections of the confiuration; once booted into the new system it worked. The problem must be with `nixos-install` and not nix in general.

**Comment by jspaalan** [comment] 2021-06-20 09:36
@rnhmjoj I'm also currently using a similar workaround. By using a minimal configuration the only derivation that is currently causing the issue in my install-phase config is mailcap-2.1.52. I noticed that by finding the derivations in /nix/store which have .lock files in place point out at least some of such problematic derivations and they can be fixed by nix-store --repair-path.

I needed to automate that temporary workaround and therefore I'm currently using the following as part of an install.sh script I'm running when installing NixOS VMware images from the 21.05 minimal ISO:
 
```
while true
do
  sudo nixos-install --show-trace --no-root-passwd
  EXITCODE=$?
  if [ $EXITCODE == 0 ]
  then
    break
  else
    sudo find /mnt/nix/store -iname *.lock | sudo nix-store --repair-path "/nix/store/$(xargs -I{} basename {} .lock)"
  fi
done
```

**Comment by rnhmjoj** [comment] 2021-06-20 09:51
Interesting, it was mailcap for me too, that can't be a coincidence. There must be something in common with these derivations that's making Nix fail, but only when invoked from nixos-install.

**Comment by liamwhite** [comment] 2021-06-20 23:44
The bug comes from nixos-install invoking nix-store with a --store path that is not /. I strongly believe that this is a nix bug and not a nixos-install bug.

**Comment by figsoda** [comment] 2021-06-23 17:14
might be related to https://github.com/NixOS/nix/issues/4081

**Comment by austinbutler** [comment] 2021-06-28 05:27
This happened to me with at least `beets` (but only when overridden with `enableExtraFiles`) and `google-fonts`. Using `nix-shell` indeed worked around it each time. This was with an install script that I used a few months back without issue.

**Comment by jonringer** [comment] 2021-06-29 23:31
> Did anyone figure this out? I've only be able to complete the installation by commeting out sections of the confiuration; once booted into the new system it worked. The problem must be with `nixos-install` and not nix in general.

don't remember where I read the issue, but there's to be a regression with `nix-build --store` or lesser so `nix-store --extra-substituters`, as those are likely to be the only difference between what I said above, and what nixos-install is calling:
```
        nix-build --out-link "$outLink" --store "$mountPoint" "${extraBuildFlags[@]}" \
            --extra-substituters "$sub" \
            '<nixpkgs/nixos>' -A system -I "nixos-config=$NIXOS_CONFIG" "${verbosity[@]}"
```

A temporary fix could be just building it twice, once without `--store` and `--extra-substitutes`, then again with them supplied. This would essentially be applying the "work-around" listed here.

The drawbacks being:
- configuration has to be evaluated twice, and it seems like repeated work to users (technically is).
- Fills up local /nix/store, which for the installation devices is tmpfs + overlay:
```
    fileSystems."/nix/.rw-store" =
      { fsType = "tmpfs";
        options = [ "mode=0755" ];
        neededForBoot = true;
      };

    fileSystems."/nix/store" =
      { fsType = "overlay";
        device = "overlay";
        options = [
          "lowerdir=/nix/.ro-store"
          "upperdir=/nix/.rw-store/store"
          "workdir=/nix/.rw-store/work"
        ];
```

**Comment by edolstra** [comment] 2021-06-30 11:16
> The bug comes from nixos-install invoking nix-store with a --store path that is not /. I strongly believe that this is a nix bug and not a nixos-install bug.

Yes, definitely a Nix bug. Note that the screenshots show that it's trying to substitute from `cache.nixos.org` (not `local`!) and then gets ENOENT on a path that isn't supposed to exist.

**Comment by jcleng** [comment] 2021-07-12 00:04
> a workaround by @jonringer
> first
> 
> ```
> nix-build '<nixpkgs/nixos>' -A config.system.build.toplevel -I nixos-config=/mnt/etc/nixos/configuration.nix
> ```
> 
> let it complete
> and then run `sudo nixos-install`

nice work，when  i install `nixos-plasma5-21.05.1408.9376bf7b342-x86_64-linux` error msg “not found xxx-glbc-2.2.1”.

```
sudo nix-build '<nixpkgs/nixos>' -A config.system.build.toplevel -I nixos-config=/mnt/etc/nixos/configuration.nix

sudo nixos-install

```
is working and instead.👍🏻

**Comment by domenkozar** [comment] 2021-07-12 10:26
It would really help if someone posts a log using `nixos-instal -vvv`

**Comment by jspaalan** [comment] 2021-07-14 07:33
> It would really help if someone posts a log using `nixos-instal -vvv`

@domenkozar I did a re-install on a new VMware machine using the latest minimal ISO nixos-minimal-21.05.1471.a7512bb64b1-x86_64-linux and reproduced the issue with nixos-install -vvv flag on.

Please find the install log files in this attached zip file. There are two files:
1. nixos-install-phase1-fails-to-mailcap-2.1.52.log is the first run of nixos-install -vvv which fails with "getting attributes of path '/nix/store/rya2s79k5ncqbas09rwhq43lrbr4s3m0-mailcap-2.1.52': No such file or directory". After this failure, I manually removed the .lock file of the mailcap-2.1.52 in /nix/store and re-ran nixos-install -vvv
2. nixos-install-phase2-finishes-ok.log is the log output of the second run, during which the installation finished OK

[2021-07-14-nixos-install-log-with-mailcap-2.1.52-no-such-file-error.zip](https://github.com/NixOS/nixpkgs/files/6814287/2021-07-14-nixos-install-log-with-mailcap-2.1.52-no-such-file-error.zip)

**Comment by jonringer** [comment] 2021-07-17 19:55
Until this issue has a proper fix, and all channels have the fix, please don't unpin this issue.

**Comment by YellowOnion** [comment] 2021-07-21 04:10
Work around is no good, I ran out of 'disk' space :-(

**Comment by Artturin** [comment] 2021-07-21 04:11
> Work around is no good, I ran out of 'disk' space :-(

How much ram

**Comment by YellowOnion** [comment] 2021-07-21 04:16
> > Work around is no good, I ran out of 'disk' space :-(
> 
> How much ram

```
# df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        390M     0  390M   0% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           2.0G  6.3M  1.9G   1% /run
tmpfs           3.9G  456K  3.8G   1% /run/wrappers
tmpfs           3.9G   85M  3.8G   3% /
/dev/root       2.4G  2.4G     0 100% /iso
/dev/loop0      2.3G  2.3G     0 100% /nix/.ro-store
tmpfs           3.9G  3.8G   43M  99% /nix/.rw-store
overlay         3.9G  3.8G   43M  99% /nix/store
tmpfs           779M  108K  779M   1% /run/user/1001
/dev/sdb2        32M   21M   12M  63% /run/media/nixos/VTOYEFI
/dev/sda1       403G  3.0G  393G   1% /mnt
/dev/sda3       510M  4.0K  510M   1% /mnt/boot
tmpfs           779M   20K  779M   1% /run/user/0
```

**Comment by Artturin** [comment] 2021-07-21 04:20
As a workaround workaround install with a minimal config and then use nixos-enter to choose and edit your config and rebuild

**Comment by YellowOnion** [comment] 2021-07-21 04:25
Going to try and copy the store to /mnt and then use `NIX_STORE_DIR` for the build command.

**Comment by ElvishJerricco** [comment] 2021-07-25 08:15
> Yes, definitely a Nix bug.

Is there an issue in the Nix repo for this? Definitely seems like a bug in the chroot store type implementation.

**Comment by ElvishJerricco** [comment] 2021-07-25 09:11
Well I did some rudimentary testing and while it definitely seems like a bug in chroot stores, it appears to be intermittent? I ran this command:

```
nix-build . -A fira-code --store $(pwd)/foo
```

And got the exact same error message. But then at some point after playing with other things that were shockingly working (specifically, using http://localhost as the only substituter after copying the derivation from local to a file://... store), I deleted the chroot store and did a sanity check and ran that command again, and it worked perfectly with https://cache.nixos.org. I'm not sure the exact time that it started working, but it seemed suspiciously close to 5:00am EDT exactly, though that's probably a red herring if I had to guess.

**Comment by samueldr** [comment] 2021-07-25 19:08
Was this bisected to a known regression? Just hit that the other day and... I'm surprised we're not all hands on deck finding the cause of the regression.

This is a terrible first impression, and this got me concerned even for knowledgeable users. Why? Because I assumed first that my hardware was somehow broken and spent a good hour formatting, re-formatting, verifying the disk for defects, reading dmesg output. On a wild goose chase!

Relatedly, for bisecting, we should probably *first* figure out a valid test protocol as a NixOS test so we don't get a similar regression in the future.

**Comment by ElvishJerricco** [comment] 2021-07-26 02:27
I figured out a script to test the issue with chroot stores pretty quickly, and managed to bisect it down to a few commits that wouldn't build nix to test with.

```
#!/usr/bin/env bash

set -euo pipefail

chmod -R +w foo || true
rm -r foo || true

rev=$(git rev-parse --short HEAD)

if [ -e ./release.nix ]; then
    nix=$(nix-build ./release.nix -A build.x86_64-linux -o nix-$rev || exit 125)
elif [ -e ./default.nix ]; then
    nix=$(nix-build ./default.nix -o nix-$rev || exit 125)
else
    echo "Don't know how to build this"
    exit 125
fi

exec "$nix"/bin/nix-build "<nixpkgs>" -A fira-code --store $(pwd)/foo -o fira-code-$rev
```

But I was having trouble finding a known-bad commit on master. So I decided to start from the 2.3 maintenance branch, as that's the one I've actually reproduced the issue with. So with good: https://github.com/NixOS/Nix/commit/b774845af7a645b44bff69cf9f655c47fe4b9fb2 and bad: https://github.com/NixOS/Nix/commit/59acbc52208429c5e46c090acc6616f987a212c3, `git bisect run ./script.sh` narrowed down to these commits that all just failed to build the nix package to test with for whatever reason and so were skipped:

```
5713ff48c3bff410666b20ac6645b7d0b4d6b142
702d707fb12cd77dce2b553d36010c0995b7fb8e
3dbd83b9a196b8c58eda9b6033442bf2020a9f60
5e5013e2f6f29ea9e5f4db41a2450a3861105449
59acbc52208429c5e46c090acc6616f987a212c3
```

Of those, only https://github.com/NixOS/Nix/commit/3dbd83b9a196b8c58eda9b6033442bf2020a9f60 actually modifies Nix. And given the commit message, it seems like a likely culprit, though I haven't dug into it yet.

```
    Check the CA hash when importing stuff in the local store
    
    When adding a path to the local store (via `LocalStore::addToStore`),
    ensure that the `ca` field of the provided `ValidPathInfo` does indeed
    correspond to the content of the path.
    Otherwise any untrusted user (or any binary cache) can add arbitrary
    content-addressed paths to the store (as content-addressed paths don’t
    need a signature).
```

Reverting this commit on the version of Nix I was originally testing with (2.3.12) has resolved the issue. And considering I couldn't find a bad commit on master, this looks to me like it's a failed backport to 2.3 or something along those lines.

**Comment by samueldr** [comment] 2021-07-26 02:33
(We were discussing it a bit in direct messages.)

In turn, Nix (2.3) was bumped only a few days before this issue was opened.

 - #125259
 - #125447

I can't believe reverting those and going back to 2.3.11 is going to cause more issues than breaking the installer.

My recommendation would be to revert this bump, and wait until 2.3.13 drops with a fix.

**Comment by samueldr** [comment] 2021-07-26 03:13
And to be complete, here's the repro I was working on, sorry it's not user friendly and a mess:

 - https://github.com/samueldr-wip/ugly-126141-repro

This verified that reverting to 2.3.11 (https://github.com/NixOS/nixpkgs/commit/f28671fa56f7bfaef616c4a66f5377ebfb162069) indeed directly returns to a working installer image.

It should also be usable to validate a future fix fixes the issue. Since reverting is not the actual final fix.

**Comment by regnat** [comment] 2021-07-26 09:37
@samueldr I couldn’t replicate the exact issue, but I’m fairly confident that it would be fixed by https://github.com/NixOS/nix/commit/89fba5c8473b8f8b2133698f1e1b9b14535c0bc0 . Do you mind giving it a try?

**Comment by samueldr** [comment] 2021-07-26 19:40
:heavy_check_mark: @regnat verified only against 21.05, but it does fix the issue; Nix finishes the system build.

 - Tested with: 09ffd851c3671fec991e0ff6c761da5d8ccf6e04 (and Nix back at 2.3.14)

(I do not know if the issue exists on unstable.)

**Comment by ElvishJerricco** [comment] 2021-07-26 19:57
Can also confirm that https://github.com/NixOS/nix/commit/89fba5c8473b8f8b2133698f1e1b9b14535c0bc0 fixed the issue in my `nix-build --store /path` test. Though what I don't understand is why I can't reproduce this issue on the master branch of Nix...

**Comment by regnat** [comment] 2021-07-27 08:19
> heavy_check_mark @regnat verified only against 21.05, but it does fix the issue; Nix finishes the system build.

Yay! I’ve opened https://github.com/NixOS/nix/pull/5053 so that we can have a proper release with the fix

> Though what I don't understand is why I can't reproduce this issue on the master branch of Nix... 

https://github.com/NixOS/nix/commit/3dbd83b9a196b8c58eda9b6033442bf2020a9f60 (the faulty commit) is a backport of https://github.com/NixOS/nix/commit/5985b8b5275605ddd5e92e2f0a7a9f494ac6e35d (which is on master), but I had to rework it a little bit as the code had changed in the meantime. And that’s when I introduced the bug.

**Comment by samueldr** [comment] 2021-07-27 18:29
@edolstra will a Nix 2.3.15 release be made soon enough? (before the end of the week)

Or should the patch be applied on 2.3.14 until then?

Given that this is a major blocker and tarnishes experience for new users, I think we should land a fix for this before the end of the week.

**Comment by tobiasBora** [comment] 2021-07-29 14:30
As far as I understand/experiment, the proposed temporal fixe download everything into the live `/nix` folder instead of the `/mnt/nix/` folder:
```
nix-build '<nixpkgs/nixos>' -A config.system.build.toplevel -I nixos-config=/mnt/etc/nixos/configuration.nix
sudo nixos-install
```

The problem is that the livecd does not have a huge space, and it tends to run out of space. Is there a way to download packages in the `/mnt/nix` store to benefit from a larger space?

**Comment by vcunat** [comment] 2021-07-30 09:19
So... we update nix then?  https://github.com/NixOS/nixpkgs/pull/132046

**Closed** 2021-07-30 13:12 UTC
Labels: 0.kind: bug, 6.topic: nixos, 6.topic: user experience

**Comment by mixmixmix** [comment] 2021-07-30 23:22
I understand that it is happily fixed @SuperSandro2000 but what do I need to do to install a fresh nixos now? Can we have some explanation for less technical folks?

**Comment by Artturin** [comment] 2021-07-31 08:55
> I understand that it is happily fixed but what do I need to do to install a fresh nixos now? Can we have some explanation for less technical folks?

You don't have to reinstall

**Comment by mixmixmix** [comment] 2021-07-31 09:38
I got a fresh install image and updated channels but still run into this problem, that's why I asked what to do :). Ultimately I see that I just needed to run what you suggested in initial post: 
`nix-store --repair-path /nix/store/rya2s79k5ncqbas09rwhq43lrbr4s3m0-mailcap-2.1.52`

**Comment by Artturin** [comment] 2021-07-31 09:58
no isos have been built with the pr yet 
https://nixpk.gs/pr-tracker.html?pr=132046
backport pr https://nixpk.gs/pr-tracker.html?pr=132073

**Comment by vcunat** [comment] 2021-07-31 16:11
Latest 21.05 ISOs should have all the fixes in them _now_.

**Comment by jonringer** [comment] 2021-08-02 18:11
Just waiting on https://nixpk.gs/pr-tracker.html?pr=132046 to finish, then I'll unpin

**Comment by domenkozar** [comment] 2021-08-03 10:17
I've used 21.05 and haven't spotted this bug.

**Comment by vcunat** [comment] 2021-08-03 10:52
All channels and ISOs should be fixed now.  (or at least contain those nix updates)

**Comment by jonringer** [comment] 2021-08-04 15:27
> I've used 21.05 and haven't spotted this bug.

It only occurs if you add new packages to your nixos configuration that don't exist in the image. If your initial install is a subset of the image, you're fine.

**Comment by ElvishJerricco** [comment] 2021-08-06 08:15
Yep, the issue only happens if you attempt to copy a fixed output derivation from a substituter into a chroot store. It's kind of rare but very unpleasant for people who try to do this thing that *should* work during installation.
