### ISSUE TITLE
Weird DNS resolutions with NixOS + NetworkManager

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#50290] opened 2018-11-13 00:11 UTC
## Issue description
Hi. This isn't my best bug report, but I'm at my wit's end and am hoping for some debugging suggestions.

I regularly find myself in situations where DNS resolution is not working in my browser despite it working just fine with `dig` in my terminal.

The screenshot here shows this: 
![whatthefuck](https://user-images.githubusercontent.com/327028/48382271-2a5c2e80-e695-11e8-8151-84a9d944808b.png)

This will persist for some number of minutes and then all of the sudden it will start working.

I don't think it's browsers caching negative hits either, because I waited until the network was up and DNS was working before I opened Chrome and tried there.

### Steps to reproduce

Use `NetworkManager` with NixOS, Leaving other networking options alone. Leave the DNS servers in NM to be the default pushed over DHCP.

Nothing special going on locally as far as DNS resolution is concerned.

I've never experienced this issue on a non-NixOS distribution before when using NM, etc.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.1, NixOS, 19.03.git.79ac9c3f8da (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `""`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by domenkozar** [comment] 2018-11-13 09:14
I've seen similar results, but switched. Terminal commands suddenly losing dns resolution while browser works. Switched to hardcoded 1.1.1.1 and haven't had the issue since.

**Comment by orivej** [comment] 2018-11-13 09:33
You can set `services.nscd.enable = false;` to make the browser behavior less surprising: browsers go through nscd which caches negative hits for a few minutes, while dig talks directly to DNS. (Related: #50042.) However, the root cause likely is a broken upstream DNS server that can respond with no-such-domain for real domains, and, as @domenkozar says, this can be fixed by overriding the DNS server in the NetworkManager settings.

**Comment by arianvp** [comment] 2018-11-13 16:16
https://github.com/NixOS/nixpkgs/pull/50316 probably fixes this :)

**Comment by volth** [comment] 2018-11-20 10:05
> Switched to hardcoded 1.1.1.1 and haven't had the issue since.

It is not al option at all.
Even besides the big-data paranoia and ```1.1.1.1```'s inability to resolve some domains, including domain of some banks (https://community.cloudflare.com/c/reliability/1111), those centralized DNS-servers unable to resolve ISP's technical domains, such as "retracker.local"

**Comment by adamtulinius** [comment] 2018-12-06 22:41
I experienced the same for some time, but it disappeared maybe 1-2 weeks ago, possible due to bumping my laptop to latest 18.09. We've had edns-related issues before with our DNS-servers at work, so thanks for that hint.

**Comment by vcunat** [comment] 2018-12-07 09:50
Related: the DNS community is now pushing harder for EDNS compliance: https://dnsflagday.net/  (it was standardized some 19 years ago)  though that's more relevant to authoritative servers whereas OSs/browsers are directly interacting with resolvers.

**Closed** 2018-12-12 23:21 UTC

**Comment by mjlbach** [comment] 2020-05-06 04:32
I'm having this issue again in 20.03

**Comment by Mic92** [comment] 2020-05-06 05:53
You can disable it by `networking.resolvconf.dnsExtensionMechanism = false;`.
