### ISSUE TITLE
Emacs 24.5 fails to build on OS X El Capitan

### ISSUE THREAD

**Issue by xuzhao9** [NixOS/nixpkgs#10247] opened 2015-10-05 21:49 UTC
nix-env -i emacs
gives following error:

    ld: library not found for -lSystem
    clang-3.6: error: linker command failed with exit code 1 (use -v to see invocation)

This happens when nix is trying to build CoreFoundation.framework.

**Comment by usharf** [comment] 2015-10-06 07:35
see some details here #9329

**Comment by henrytill** [comment] 2015-10-29 02:42
Could you check this again with a current clone of nixpkgs?  Everything should be fine there.  

Instructions here: https://nixos.org/wiki/Nix_on_OS_X

**Comment by usharf** [comment] 2015-10-29 11:34
Had to remove nix form that machine.
10x

**Comment by retrry** [comment] 2016-04-21 15:34
Duplicate of https://github.com/NixOS/nixpkgs/issues/9329 ?

**Comment by pipping** [comment] 2016-06-06 15:49
Works for me.

```
% uname -v
Darwin Kernel Version 15.6.0: Tue May 17 20:05:28 PDT 2016; root:xnu-3248.60.3~4/RELEASE_X86_64
% which emacs
.../.nix-profile/bin/emacs
% emacs --version
GNU Emacs 24.5.2
Copyright (C) 2015 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
% 
```

**Closed** 2016-06-06 20:22 UTC
Labels: 6.topic: darwin
