### ISSUE TITLE
Qt applications use Windows style regardless of style selected in KDE settings

### ISSUE THREAD

**Issue by alapshin** [NixOS/nixpkgs#98268] opened 2020-09-19 09:50 UTC
**Describe the bug**
Various Qt applications (smplayer, qjackctl etc) use Windows style regardless of what style is selected in KDE System Settings.
When I try to pass style via command line it doesn't work either.
```
qjackctl -style Breeze
QApplication: invalid style override 'Breeze' passed, ignoring it.
        Available styles: Breeze, Windows, Fusion
```

**To Reproduce**
1. Select any style (Breeze, Fusion) in KDE System Settings
2. Launch Qt application (smplayer for example)
3. Application uses Windows style

**Expected behavior**
Qt applications should use style selected in KDE System Settings

**Screenshots**
![Screenshot_20200919_124746](https://user-images.githubusercontent.com/321946/93664316-8e609280-fa76-11ea-8197-646acdb48b3d.png)

**Metadata**
```
- system: `"x86_64-linux"`
 - host os: `Linux 5.7.19, NixOS, 21.03pre243690.441a7da8080 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre243690.441a7da8080"`
 - channels(alapshin): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by poscat0x04** [comment] 2020-09-27 08:23
can confirm

**Comment by solson** [comment] 2020-10-12 04:01
I have the same problem with KeePassXC:

```console
$ keepassxc -style=Breeze
QApplication: invalid style override 'Breeze' passed, ignoring it.
        Available styles: Breeze, Windows, Fusion
```

But setting `-style=Fusion` or `-style=Windows` explicitly actually works, so the problem is Breeze-specific, at least on my machine. I confirmed the same thing with `qjackctl` just now.

**Comment by solson** [comment] 2020-10-12 04:29
I ran with `QT_DEBUG_PLUGINS=1` and found this:

```
Cannot load library /nix/store/0mpi3gn7v5hah1h2lc5my3a0n7rfzngh-breeze-qt5-5.18.5-bin/lib/qt-5.14.2/plugins/styles/breeze.so: (/nix/store/g6r4b8vmj30v5a6cjwxz936h90xcxj7m-qtdeclarative-5.14.2/lib/libQt5Quick.so.5: undefined symbol: _ZN4QRhi10newSamplerEN11QRhiSampler6FilterES1_S1_NS0_11AddressModeES2_, version Qt_5_PRIVATE_API)
QLibraryPrivate::loadPlugin failed on "/nix/store/0mpi3gn7v5hah1h2lc5my3a0n7rfzngh-breeze-qt5-5.18.5-bin/lib/qt-5.14.2/plugins/styles/breeze.so" : "Cannot load library /nix/store/0mpi3gn7v5hah1h2lc5my3a0n7rfzngh-breeze-qt5-5.18.5-bin/lib/qt-5.14.2/plugins/styles/breeze.so: (/nix/store/g6r4b8vmj30v5a6cjwxz936h90xcxj7m-qtdeclarative-5.14.2/lib/libQt5Quick.so.5: undefined symbol: _ZN4QRhi10newSamplerEN11QRhiSampler6FilterES1_S1_NS0_11AddressModeES2_, version Qt_5_PRIVATE_API)"
```

Those are some annoyingly long lines, but the relevant bit is the loading of `breeze.so` complaining about an undefined symbol with this name:

```console
> c++filt _ZN4QRhi10newSamplerEN11QRhiSampler6FilterES1_S1_NS0_11AddressModeES2_
QRhi::newSampler(QRhiSampler::Filter, QRhiSampler::Filter, QRhiSampler::Filter, QRhiSampler::AddressMode, QRhiSampler::AddressMode)
```

**Comment by solson** [comment] 2020-10-12 04:42
It may be relevant that, for some reason, my KDE programs like `plasmashell` or `kate` are linking against Qt 5.14.2 libraries, while `keepassxc` and `qjackctl` are linking against Qt 5.15.0 libraries. The `breeze-qt5` package is built under the plasma set of packages and also links against Qt 5.14.2 libraries.

**Comment by doronbehar** [comment] 2020-10-23 15:42
I'm rather sure this should be fixed by https://github.com/NixOS/nixpkgs/pull/101369. Please help me test packages there.

**Closed** 2020-11-01 10:05 UTC
Labels: 0.kind: bug, 6.topic: qt/kde
