### ISSUE TITLE
Restarting containers is broken

### ISSUE THREAD

**Issue by erikarvstedt** [NixOS/nixpkgs#43652] opened 2018-07-17 08:24 UTC
Restarting containers sometimes fails with this error in the service start script:
`Failed to register machine: Machine 'MACHINE' already exists`

#### Reproduce
```bash
# (as root)
nixos-container create tmp
while systemctl restart container@tmp; do :; done
# Job for container@tmp.service failed because the control process exited with error code.
journalctl -u container@tmp -n 50 | grep -5 'already exists'
```

#### Explanation
Restarting a container (`systemctl restart container@*`) leads to the following sequence of commands and events:
(1) kill container PID (in [ExecStop](https://github.com/NixOS/nixpkgs/blob/095fe5b43def40279a243e663c662b02caac5318/nixos/modules/virtualisation/containers.nix#L649))
(2) the container process exits
(3) the container service gets started again
(4) machinectl terminate container (in [ExecStartPre](https://github.com/NixOS/nixpkgs/blob/095fe5b43def40279a243e663c662b02caac5318/nixos/modules/virtualisation/containers.nix#L153))
(5) systemd-nspawn (in [ExecStart](https://github.com/NixOS/nixpkgs/blob/095fe5b43def40279a243e663c662b02caac5318/nixos/modules/virtualisation/containers.nix#L123))

Depending on the system load or performance, there's a time period of a few milliseconds after (2) where
(4) fails with error `Could not terminate machine: Resource deadlock avoided`
and (5) fails with error `Failed to register machine: Machine 'MACHINE' already exists`.

The error in (4) is ignored by the ExecStartPre script but (5) eventually causes the start process to fail.

Seperating the 'restart' command into 'stop and start' as newly implemented in [nixos-container](https://github.com/peterhoeg/nixpkgs/blob/b95a24fdf1f751c44282f6c38b84b763a85eee19/pkgs/tools/virtualization/nixos-container/nixos-container.pl#L255) (https://github.com/NixOS/nixpkgs/pull/39717) and [discussed here](https://github.com/NixOS/nixpkgs/issues/16753#issuecomment-244911041) makes the error less frequent but doesn't eliminate it.

Unfortunately, we can't just wait-loop in ExecStartPre or ExecStart until systemd has fully processed the termination of the machine, as this causes a deadlock: As long as systemctl is running, machined makes no progress and keeps the old machine around.

A possible workaround is to wait inside the `nixos-container` script, like so (bash):
```bash
systemctl stop container@mycontainer.service

# Retry terminating the container machine until the command succeeds
# or the machine has disappeared. Use `machinectl terminate` like
# in ExecStartPre.
for ((i = 1;; i++)); do
    failed=''
    output=$(machinectl terminate mycontainer 2>&1) || failed=1
    if [[ ! $failed || $output == *no*machine*known ]]; then
        break
    fi
    if ((i == 20)); then
        echo "Failed to stop container."
        exit 1
    fi
    sleep 0.001
done

systemctl start container@mycontainer.service
```

This is no satisfying solution as `systemctl restart` and `stop && start` is still broken for containers.
Is there a better way to fix this?
Should we file a systemd bug?

To aid debugging and experimenting, [here's a script](https://gist.github.com/erikarvstedt/3017979f8eba758967fe7d57a996b4be) that creates a mutable container which allows editing its service definition and start/stop scripts.

**Comment by peterhoeg** [comment] 2018-07-17 14:29
Does ```machinectl stop container_name``` wait properly?

**Comment by erikarvstedt** [comment] 2018-07-19 12:35
No, replacing the `kill` command in `ExecStop` with `machinectl poweroff` (for which `stop` is an alias) changes nothing.

Here's some more empirical data:
The error in `machinectl terminate` seems to happen only when the command is run inside of service script.

This loop consistently fails on my system after a few iterations:
```
while true; do
    echo run
    systemctl stop container@dev
    systemctl start container@dev || break
done
```
When called this way, `machinectl` never fails with a deadlock error. Also, the container start is always successful.
```
while true; do
    echo run
    systemctl stop container@dev
    machinectl terminate dev
    systemctl start container@dev || break
done
```
As described above, sleeping fixes starting, too:
```
while true; do
    echo run
    systemctl stop container@dev
    sleep 0.003
    systemctl start container@dev || break
done
```

**Comment by pjones** [comment] 2019-01-24 18:01
I'm experiencing this with NixOps created containers.  `journalctl` reports:

```
-- Unit container@eic.service has begun starting up.
Jan 24 10:58:36 elphaba systemd[1]: Requested transaction contradicts existing jobs: Transaction is destructive.
Jan 24 10:58:36 elphaba systemd-machined[1089]: Failed to stop machine scope: Transaction is destructive.
Jan 24 10:58:36 elphaba container eic[27807]: Spawning container eic on /var/lib/containers/eic.
Jan 24 10:58:36 elphaba container eic[27807]: Press ^] three times within 1s to kill container.
Jan 24 10:58:36 elphaba container eic[27807]: /etc/localtime does not point into /usr/share/zoneinfo/, not updating co>
Jan 24 10:58:36 elphaba container eic[27807]: Failed to register machine: Machine 'eic' already exists
Jan 24 10:58:36 elphaba systemd[1]: container@eic.service: Main process exited, code=exited, status=1/FAILURE
Jan 24 10:58:36 elphaba systemd[1]: container@eic.service: Failed with result 'exit-code'.
Jan 24 10:58:36 elphaba systemd[1]: Failed to start Container 'eic'.
-- Subject: Unit container@eic.service has failed
```

I'm running the latest build of NixOS 18.09.

**Comment by bqv** [comment] 2020-04-25 01:46
I've been wondering what the problem is here too. I work around it by manually restarting the containers that fail, which is very inconvenient.

**Comment by maralorn** [comment] 2020-05-08 07:59
I am really glad, that there is work being done on this. This is by far the biggest contributor to my server down times and monitoring alerts for years!
This single issue (nearly) alone has led me to migrate as much containers as possible away from nixos-containers. Just because they didn‘t feel stable enough.

**Comment by maralorn** [comment] 2021-03-31 09:35
No! Go away stale bot! This issue affects me on a daily basis and is a real problem that I have to work around.

**Comment by dpausp** [comment] 2021-06-27 14:52
I had problems with (re-)starting containers on 20.09 but it seems to work properly on 21.05. I also tried the test loop from the first post here, doesn't produce errors.

Anyone still experiencing this? 

@maralorn

**Comment by dpausp** [comment] 2021-06-27 14:52
I had problems with (re-)starting containers on 20.09 but it seems to work properly on 21.05. I also tried the test loop from the first post here, doesn't produce errors.

Anyone still experiencing this? 

@maralorn

**Comment by dpausp** [comment] 2021-06-27 14:52
I had problems with (re-)starting containers on 20.09 but it seems to work properly on 21.05. I also tried the test loop from the first post here, doesn't produce errors.

Anyone still experiencing this? 

@maralorn

**Comment by dpausp** [comment] 2021-06-27 14:52
I had problems with (re-)starting containers on 20.09 but it seems to work properly on 21.05. I also tried the test loop from the first post here, doesn't produce errors.

Anyone still experiencing this? 

@maralorn

**Comment by dpausp** [comment] 2021-06-27 14:52
I had problems with (re-)starting containers on 20.09 but it seems to work properly on 21.05. I also tried the test loop from the first post here, doesn't produce errors.

Anyone still experiencing this? 

@maralorn

**Comment by maralorn** [comment] 2021-06-27 14:57
In the meanwhile I mostly migrated away from using nixos containers and for my last container my workarounds are working, so I can‘t really tell.

But I will dig into it.

**Comment by maralorn** [comment] 2021-06-27 15:10
Yeah, nope. I can‘t seem to reproduce it. Nice!

We can close this from my point of view. I can still reopen when the issue resurges.

**Closed** 2021-06-27 15:18 UTC
Labels: 6.topic: nixos

**Comment by maralorn** [comment] 2021-06-27 15:59
There are a lot more people involved in this issue. If any of you still encounter this problem, don‘t hesitate to re-open?

(Also if anyone knows, what fixed this, that would be enlightening.)
