### ISSUE TITLE
qemu.conf doesn't point to UEFI 

### ISSUE THREAD

**Issue by clefru** [NixOS/nixpkgs#25209] opened 2017-04-25 14:03 UTC
## Issue description
New VMs created libvirtd/virt-manager can't switch to the UEFI boot chain.

### Steps to reproduce
virt-manger > File > New Virtual Machine > Select Network Boot > Forward > Forward > Forward > Deselect "Enable storage" > Forward > Click "Customize configuration before install" > Finish

Observe in the "Overview" Tab, that Firmware is "BIOS" and you can't move the selection to "UEFI". 
(Click "Cancel Installation")

## Technical details
qemu.conf needs to contain an "nvram" variable, see https://github.com/libvirt/libvirt/blob/master/src/qemu/qemu.conf#L663
Adding
```
nvram = [ "${nixos.OVMF}/FV/OVMF_CODE.fd:${nixos.OVMF}/FV/OVMF_VARS.fd" ]
```
should work. I'll prepare a PR.

* System: 17.09pre106117.c90998d5cf (Hummingbird)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: 17.09pre106117.c90998d5cf

**Comment by fpletz** [comment] 2017-04-27 15:38
Please ping me on your PR, I'm interested in testing this.

**Comment by clefru** [comment] 2017-05-01 16:38
@fpletz: https://github.com/NixOS/nixpkgs/pull/25397. Thanks for testing :)

**Comment by hyphon81** [comment] 2017-07-22 12:45
Hello.
The new option, virtualisation.libvirtd.qemuOvmf is very good!
However, at least in my environment, VMs with OVMF by this option were not working. It seems to use too old OVMF in nixpkgs. I attempted to use edk2 at github newest rev 1683ecec41a7c944783c51efa75375f1e0a71d08 now and VMs are running fine now.
So, for qemu with OVMF, it should be update the OVMF's version in nixpkgs.

**Comment by bjornfor** [comment] 2017-07-22 12:49
UEFI booting libvirt machines in NixOS 17.03 works for me.

**Comment by hyphon81** [comment] 2017-07-22 13:09
In not modified pkgs, I was failed to boot from iso files(ubuntu 16.04 and CentOS 7) on NixOS.
I'm using this NixOS version.
```
$ nixos-version
17.03.1556.4d1e1d07f9 (Gorilla)
```
Previously, the QEMU virtual machine's video console were black out and nothing to do when I used QEMU with OVMF.
And I switched edk2 version to newest, then virtual machines are running fine.
So, it caused by edk2(OVMF)'s version change to run VMs with OVMF. At least, I think this is not wrong...

**Comment by bjornfor** [comment] 2017-07-22 15:31
@hyphon81: Weird. I'm on NixOS 17.03.git.7b390ba. That's just a few commits later and I don't see anything relevant to that issue in this commit range.

I did this:

virt-manger > File > New Virtual Machine > Select "Local install media (ISO image or CDROM)" > Forward > Select ISO image (Ubuntu 16.04)  > Forward > Forward > Forward > Click "Customize configuration before install"

(The difference between the above steps and OP is that I use "Local install media" instead of "Network boot" and don't deselect "Enable storage". I don't think that should affect the outcome.)

In the "Customize configuration before install" step I'm able to switch between BIOS and UEFI.

**Comment by hyphon81** [comment] 2017-07-22 15:58
I found it is caused by using chipset Q35.
I'm always using this setting in virt-manager and OpenStack.
(In virt-install, adding option "--machine pc-q35-2.8" or "--machine pc-q35-2.9". The 2.x is QEMU's version)

**Comment by hyphon81** [comment] 2017-07-22 16:05
@bjornfor Yes, in virt-manager, after "Click "Customize configuration before install"", switching the Firmware BIOS to UEFI. **And, switching the Chipset i440FX to Q35**, then it will be reproduce.

**Comment by bjornfor** [comment] 2017-07-22 16:14
Good. Then we can close this.

**Closed by bjornfor** 2017-07-22 16:14 UTC
Labels: 0.kind: enhancement

**Comment by hyphon81** [comment] 2017-07-22 16:19
Should I create a new issue for updating OVMF package?

**Comment by bjornfor** [comment] 2017-07-22 17:04
Yes. Or a PR if you can :)
