### ISSUE TITLE
Eclipse with Marketplace does not work (glib gschemas error)

### ISSUE THREAD

**Issue by spinus** [NixOS/nixpkgs#16521] opened 2016-06-26 15:33 UTC
## Issue description

Marketplace plugin does not work with eclipse.
### Steps to reproduce
1. Install eclipse (nix-env -iA nixos.eclipses.eclipse-platform)
2. Run eclipse, install Marketplace addon
3. Try to open Marketplace (Help -> Eclipse Marketplace) -> crash

Error:

```
(Eclipse:14788): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
```

There is no more errors/debug messages.

I tried to install (nix-env -iA nixos.gnome3.gsettings_desktop_schemas) but it didn't help.
## Technical details
- System: NixOS: 16.09pre84674.fbde3a7 (Flounder)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 16.09pre85363.886c03a

**Comment by layus** [comment] 2016-08-22 22:32
I get the same error with eclipse-sdk-46. Eclipse crashes as soon as it opens an auto-complete popup, and displays the above error message.

I have installed plugins, but no idea if it is related.

It looks like eclipse searches for gschemas.compiled but does not find it.
```
$ strace -ff -e trace=file $(nix-build "<nixpkgs>" -A eclipses.eclipse-sdk-46)/bin/eclipse |& grep -i schemas 
[pid 20157] open("/run/current-system/sw/share/glib-2.0/schemas/gschemas.compiled", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 20157] open("/nix/var/nix/profiles/default/share/glib-2.0/schemas/gschemas.compiled", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 20157] open("/home/layus/.nix-profile/share/glib-2.0/schemas/gschemas.compiled", O_RDONLY) = -1 ENOENT (No such file or directory)
```

/cc @rycee, as you made significant changes to eclipse and may know more than we do.
/cc @lethalman, @domenkozar, @vcunat, maybe related to #1455 and gschemas insanity

**Comment by vcunat** [comment] 2016-08-23 21:08
Yes, that's a standard issue. Many apps need a wrapper to `--prefix XDG_DATA_DIRS : "$GSETTINGS_SCHEMAS_PATH:"` or the automatic `wrapGAppsHook` which does that and more.

**Comment by rycee** [comment] 2016-08-24 18:52
I've been unable to reproduce this but I agree with @vcunat that it might very well be solved by tweaking the `XDG_DATA_DIRS` environment variable. To test this hypothesis you can add `--prefix XDG_DATA_DIRS : "$GSETTINGS_SCHEMAS_PATH:"` to the `makeWrapper` call in [build-eclipse.nix](https://github.com/NixOS/nixpkgs/blob/672447f1ada85a38f1b1f7d909d72977658abcb4/pkgs/applications/editors/eclipse/build-eclipse.nix#L37-L40).

**Comment by vcunat** [comment] 2016-08-24 19:36
IIRC the schemas for file-dialog crashes are provided by gtk3.

**Comment by rycee** [comment] 2016-08-24 19:45
Eclipse uses gtk2, though…

**Comment by vcunat** [comment] 2016-08-24 19:56
From the messages here it's not clear what schemas it's missing. It might be failing to find its own schemas.

**Comment by globin** [comment] 2016-08-25 22:50
May be a case for `wrapGAppsHook`

**Comment by vcunat** [comment] 2016-08-27 15:42
I thought so, but this case seems strange/different. I can't pinpoint what's missing or reproduce it (but I only tried for several minutes.)

**Comment by Taeradan** [comment] 2017-03-14 09:58
I have a similar error with Eclipse, it keeps crashing with the error :
`(Eclipse:5820): GLib-GIO-ERROR **: Settings schema 'org.gnome.system.proxy' is not installed`

Eclipse is unusable as it crashes every few minutes.
As I just installed NixOS for my team at work, and we need Eclipse, this is very embarrassing.

**Comment by Taeradan** [comment] 2017-03-14 10:51
I have tried to remove the Marketplace, but still got the issue

**Comment by rycee** [comment] 2017-03-14 10:59
Please give https://github.com/rycee/nixpkgs/commit/59be9fe47d54fd199686bef0c181e7c255157eba a try. It may fix the issue. The patch should apply cleanly to master and 17.03.

**Comment by Taeradan** [comment] 2017-03-14 11:00
If it can help, this is the result of strace on eclipse :
[trace_eclipse.txt](https://github.com/NixOS/nixpkgs/files/841037/trace_eclipse.txt)

**Comment by Taeradan** [comment] 2017-03-14 11:25
I will try to test this today. Do you plan to make a PR soon ?

**Comment by rycee** [comment] 2017-03-14 11:27
If you can confirm it fixes the issue then I can make a PR or move directly to master (and I guess 17.03?).

**Comment by Taeradan** [comment] 2017-03-14 14:10
The problem seems solved, my 2 co-workers have your commit applied and no eclipse crashed yet :)

**Comment by rycee** [comment] 2017-03-14 14:13
Great, thanks for the confirmation. I'll get it merged into master and 17.03 later today.

Is there anybody that insists on having the fix in 16.09 as well?

**Comment by bjornfor** [comment] 2017-03-14 14:14
If it applies cleanly on release-16.09 as well, and is a known good fix, why not? :-)

**Comment by rycee** [comment] 2017-03-14 14:24
Yeah, I'll do 16.09 as well. I don't think the patch will apply cleanly there but it should only require small adjustments.

**Comment by rycee** [comment] 2017-03-14 20:40
Applied to master, 17.03, and 16.09. From cursory testing it works well on all three platforms so I'll close this issue. Please reopen if you find that the issue wasn't actually fixed.

**Closed by rycee** 2017-03-14 20:40 UTC
