### ISSUE TITLE
Package request: linuxKernels.packages.linux_cachyos[_<variant>]

### ISSUE THREAD

**Issue by Pandapip1** [NixOS/nixpkgs#330115] opened 2024-07-26 08:13 UTC
**Project description**

See https://wiki.cachyos.org/kernel/kernel/ for information about all the different cachyos kernels.

**Metadata**

* homepage URL: https://cachyos.org/
* source URL: https://github.com/CachyOS/linux-cachyos
* license: gpl2+
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by drakon64** [comment] 2024-07-29 19:10
I'm working on the 'generic' CachyOS variant https://github.com/NixOS/nixpkgs/pull/330917

**Comment by jopejoe1** [comment] 2024-07-29 21:14
Duplicate of #214819

**Closed by jopejoe1** 2024-07-29 21:14 UTC
Labels: 6.topic: kernel, 0.kind: packaging request
