### ISSUE TITLE
Pantheon: no wallpapers

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#100293] opened 2020-10-12 05:31 UTC
**Describe the bug**

![Screenshot from 2020-10-07 15-38-20](https://user-images.githubusercontent.com/91113/95708488-b77ed800-0c5c-11eb-929b-7cdd625a6c41.png)

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**
have wallpapers like before. this is a regression

**Additional context**

**Notify maintainers**
@worldofpeace 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.13, NixOS, 20.09beta992.7badbf18c45 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"home-manager-20.09, nixos-20.09beta992.7badbf18c45, nixos-hardware, nixos-unstable-21.03pre246062.420f89ceb26"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by worldofpeace** [comment] 2020-10-12 22:14
I can reproduce. This is a bug in application, probably. I changed how this plugin collects wallpapers a while ago, and that was for it to pickup a background directory from `XDG_DATA_DIRS`. There was one regression that got a committed fix as well. Last time I checked it seemed to work, maybe it was because it copied system backgrounds locally and making thumbnails for those was the only thing that worked on our setup. Anyways we should forward it upstream.

**Comment by worldofpeace** [comment] 2020-10-12 22:23
Actually, if I revert https://github.com/NixOS/nixpkgs/commit/5100e4f250833d42dffd9c55e3fda82303b606fd it works. This is a regression within the plugin for something that *was* fixed but seems to have broken again. The situation is that, before that commit `/run/current-system/sw/share/backgrounds` is just a single folder with images. After it has a `nixos` folder in it. https://github.com/elementary/switchboard-plug-pantheon-shell/issues/157

**Comment by worldofpeace** [comment] 2020-10-12 22:32
reported https://github.com/elementary/switchboard-plug-pantheon-shell/issues/246. Maybe my change caused this, will bisect.

**Closed** 2020-10-26 17:47 UTC
Labels: 0.kind: bug, 6.topic: pantheon

**Comment by worldofpeace** [comment] 2020-10-26 17:48
It was fairly involved but I figured out what a workaround for now would be https://github.com/elementary/switchboard-plug-pantheon-shell/issues/246#issuecomment-716713218
