### ISSUE TITLE
Pidgin: Voice and video not working

### ISSUE THREAD

**Issue by fuzzy-id** [NixOS/nixpkgs#10556] opened 2015-10-23 09:56 UTC
After installing `pidgin-with-plugins` I cannot get voice and video working. I additionally installed `gstreamer` and `gst_plugins_{base,good,bad}`, but no luck either.

**Comment by fuzzy-id** [comment] 2015-10-23 12:39
See #10559 on how to resolve this issue by setting `GST_PLUGIN_PATH`. I'd recommend to document this in the wiki as a first fix.

**Comment by hrdinka** [comment] 2016-03-06 23:15
Please check if https://github.com/NixOS/nixpkgs/pull/13722 fixes your issue.

**Comment by rasendubi** [comment] 2016-07-03 00:29
I believe the issue is fixed by #13722 and should be closed.

**Comment by rasendubi** [comment] 2016-09-09 05:32
I'm closing this as it should be fixed by #13722. Feel free to reopen if the issue persists.

**Closed by rasendubi** 2016-09-09 05:32 UTC
