### ISSUE TITLE
emacs25pre test suite failures

### ISSUE THREAD

**Issue by mjhoy** [NixOS/nixpkgs#13573] opened 2016-02-29 14:52 UTC
## Basic info

> Kernel: Linux nixos 4.4.2 #1-NixOS SMP Wed Feb 17 20:31:25 UTC 2016 x86_64 GNU/Linux

> System: 16.03pre77568.40c586b (Emu)

> Nix version: nix-env (Nix) 1.11.2

> Nixpkgs version: "16.03pre77568.40c586b"

## Describe your issue here

When adding `emacs25pre` to `environment.systemPackages` and running `nixos-rebuild switch`, emacs 25 builds and fails with 4 unexpected TRAMP mode test errors:

```
4 unexpected results:
   FAILED  tramp-test32-utf8
   FAILED  tramp-test32-utf8-with-ls
   FAILED  tramp-test32-utf8-with-perl
   FAILED  tramp-test32-utf8-with-stat
```

The full output contains null bytes and weird control characters that don't let me paste this into a gist easily. Is that part of the test or indicative of the problem?

cc @jwiegley

**Comment by mjhoy** [comment] 2016-02-29 15:11
ok... i think this will contain the build output? again if i open it in emacs there are lots of control characters. had to zip so github wouldn't complain.

[tramp-test-fail.zip](https://github.com/NixOS/nixpkgs/files/151149/tramp-test-fail.zip)

**Comment by bendlas** [comment] 2016-03-04 15:04
I disabled `doCheck` for emacs25pre, for now, on my system. I hope this will be resolved upstream before next release ...

**Comment by peti** [comment] 2016-04-04 09:49
It's quite possible that tramp-related tests fail because there is no proper networking support in the build chroot, i.e. it's not possible to resolve host names or service names. Another source of trouble could be the lack of an UTF-8 capable locale in our default build environment.

Anyhow, it would be really good to report those errors upstream to make sure that the next Emacs release has them fixed in one way or another.

**Comment by jwiegley** [comment] 2016-04-04 18:27
I've been working with the Tramp author for the past several days about these failures, and we've identified that the problem is somewhere in the environment that the tests are presented with, but we don't yet know what exactly.  I'm still digging into it.

**Closed** 2016-08-07 09:11 UTC
