### ISSUE TITLE
element-desktop: cannot search for my encrypted messages because it was built without Seshat and Keytar

### ISSUE THREAD

**Issue by jgarte** [NixOS/nixpkgs#112946] opened 2021-02-12 22:57 UTC
**Describe the bug**
Hi, I'm running into a bug in `element-desktop` where I get the following message in various rooms: __Use the Desktop app to search encrypted messages__. 

My element-desktop debug log says:

`2021-02-12T20:17:53.520Z I EventIndex: Event indexing isn't installed for the platform, not initializing.`

**Expected behavior**
I expect to be able to search my encrypted messages.

**Additional context**

From my discussion with upstream devs on #element:matrix.org:
 
> I suggest contacting the maintainer of that as they built it without Seshat hence it cannot act as a search index for your encrypted messages

# missing dependencies

[node-keytar](https://github.com/atom/node-keytar)
[seshat](https://github.com/matrix-org/seshat)

https://github.com/vector-im/element-desktop#building

**Notify maintainers**
@Ma27 @claudiiii  @r-ryantm 

**Metadata**
```nix
$ nix-shell -p nix-info --run "nix-info -m
> "
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.95, NixOS, 20.09.2996.002c001ab6f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(jgart): `"small-21.03pre268368.a007152316a, u-21.03pre268255.e5b478271ea, uu-21.03pre268206.536fe36e23a"`
 - channels(root): `"nixos-20.09.2996.002c001ab6f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ajs124** [comment] 2021-02-12 23:38
duplicate of #87752?

**Closed** 2021-02-13 05:11 UTC
Labels: 0.kind: bug
