### ISSUE TITLE
Screen doesn't wake up from sleep on Plasma Wayland with Nvidia dGPU

### ISSUE THREAD

**Issue by sid3425** [NixOS/nixpkgs#256071] opened 2023-09-19 10:03 UTC
### Describe the bug
I have an Nvidia dedicated GPU in my laptop, and while I have setup hybrid graphics properly, my laptop does not wake from sleep if I am using the Wayland session of KDE Plasma. The backlight powers on, but nothing shows on the display, eventually requiring a force reboot. However with X11 sleep/wake functionality works just fine.

### Steps To Reproduce
Putting laptop with dedicated Nvidia GPU to sleep in Plasma Wayland and waking it up does not display anything on the screen.

### Expected behavior
The laptop should resume from sleep and display should load.

### Additional context
I created a separate nix configuration linked to my main configuration.nix file to handle hybrid graphics. The code of the graphics related nix file is as follows:

``` 
{ config, lib, pkgs, ... }:

let
  nvidia-offload = pkgs.writeShellScriptBin "nvidia-offload" ''
    export __NV_PRIME_RENDER_OFFLOAD=1
    export __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
    export __GLX_VENDOR_LIBRARY_NAME=nvidia
    export __VK_LAYER_NV_optimus=NVIDIA_only
    exec "$@"
  '';

in {
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware = {
    opengl = {
      enable = true;
      driSupport = true;
      driSupport32Bit = true;
    };
    nvidia = {
      modesetting.enable = true;
      powerManagement.enable = true;
      open = false;
      nvidiaSettings = true;
      package = config.boot.kernelPackages.nvidiaPackages.stable;
      prime = {
        offload = {
          enable = true;
          enableOffloadCmd = true;
        };
        amdgpuBusId = "PCI:5:0:0";
        nvidiaBusId = "PCI:1:0:0";
      };
    };
  };
}
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.53, NixOS, 23.05 (Stoat), 23.05.3580.5d017a8822e0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(sid): `""`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by expipiplus1** [comment] 2023-09-22 02:02
Looks like a duplicate of https://github.com/NixOS/nixpkgs/issues/254614

**Closed by expipiplus1** 2023-09-22 02:02 UTC
Labels: 0.kind: bug
