### ISSUE TITLE
arm64: no go (golang is not supported)

### ISSUE THREAD

**Issue by vielmetti** [NixOS/nixpkgs#24878] opened 2017-04-13 15:59 UTC
## Issue description

go (golang) not supported on aarch64

### Steps to reproduce

```
[root@ed-nixos-nrt-2:/etc/nixos]# nix-env --install go --show-trace
installing 'go-1.8'
error: while evaluating the attribute 'disallowedReferences' of the derivation 'go-1.8' at /nix/store/cbwpjf6fw9d7w1zb0rxdm8mhaxzr3y31-nixos-17.09.git.01a8de9/nixos/pkgs/development/compilers/go/1.8.nix:26:3:
while evaluating the attribute 'GOARCH' of the derivation 'go-1.4-bootstrap-20161024' at /nix/store/cbwpjf6fw9d7w1zb0rxdm8mhaxzr3y31-nixos-17.09.git.01a8de9/nixos/pkgs/development/compilers/go/1.4.nix:11:3:
Unsupported system
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
[root@ed-nixos-nrt-2:/etc/nixos]# nixos-version && nix-env --version && nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
17.09.git.01a8de9 (Hummingbird)
nix-env (Nix) 1.11.8
"17.09.git.01a8de9"
```

**Comment by vielmetti** [comment] 2017-04-13 16:18
Here's some bootstrap for Go https://github.com/DieterReuter/go-bootstrap

**Comment by vielmetti** [comment] 2017-08-31 02:31
This should be an attainable task to pick up on again, since Go has now shipped a 1.9 binary for arm64 which can be consumed directly.

**Comment by fdietze** [comment] 2017-09-25 15:33
How difficult is this? It is a blocker for Syncthing on my RPi3 right now. I could help.

**Comment by vielmetti** [comment] 2017-09-25 16:22
@fdietze this should be a lot easier than it used to be, as Go 1.9 now ships with an arm64 binary release at https://storage.googleapis.com/golang/go1.9.linux-arm64.tar.gz via https://golang.org/dl/

**Comment by vielmetti** [comment] 2017-09-25 16:29
Probably best to sync this with #29173 which is the 1.8 -> 1.9 transition.

**Comment by orivej** [comment] 2017-09-25 16:40
I think that adding Go bootstrap for arm64 is unrelated to switching the default Go to 1.9.

**Comment by orivej** [comment] 2017-09-25 19:15
Wasn't this fixed by https://github.com/NixOS/nixpkgs/commit/723bd8b9c541acf546c825beffa1b241098f74d3 ?

**Comment by fdietze** [comment] 2017-09-26 14:09
I cannot install syncthing on my Aarch64 Raspberry Pi 3 because of this. How can I control the go version to use?
https://github.com/NixOS/nixpkgs/blob/3d04a557b72aa0987d9bf079e1445280b6bfd907/pkgs/applications/networking/syncthing/default.nix#L14

**Comment by fdietze** [comment] 2017-09-28 12:31
Here is the error:
```
$ sudo nixos-rebuild switch --show-trace
...
while evaluating the attribute ‘value’ at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/types.nix:209:55:
while evaluating the attribute ‘ExecStart’ at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/services/networking/syncthing.nix:137:11:
while evaluating the attribute ‘buildInputs’ of the derivation ‘syncthing-0.14.38’ at /nix/store/xzikn5p1lf765y9qqkmv3bkcdi8rfbsk-nixos-18.03pre116572.9824ca6975/nixos/pkgs/stdenv/generic/make-derivation.nix:98:11:
while evaluating the attribute ‘GOARCH’ of the derivation ‘go-1.9’ at /nix/store/xzikn5p1lf765y9qqkmv3bkcdi8rfbsk-nixos-18.03pre116572.9824ca6975/nixos/pkgs/stdenv/generic/make-derivation.nix:98:11:
Unsupported system

$ uname -m
aarch64
```

Is it possible to use syncthing with Go 1.8 until the 1.9 migration is done?

**Comment by fdietze** [comment] 2017-09-29 17:45
I tried, but it failed.

Here is the output: https://gist.github.com/fdietze/57b863876816b647756f50929395b6f7

I don't know exactly why it fails. Maybe a timeout, because the RPi3 is too slow?

**Comment by orivej** [comment] 2017-09-29 17:54
The root cause seems to be that you ran out of memory, see `cannot allocate memory` in the log. You won't have to build `go` once it is in binary caches (`if stdenv.isAarch64 then "arm64"` is already in `master`). Alternatively you can skip tests by replacing `./all.bash` with `./make.bash` in that `1.9.nix`.

**Comment by fdietze** [comment] 2017-10-01 18:38
It is working now, thank you!

**Closed** 2017-10-01 18:41 UTC

**Comment by fdietze** [comment] 2017-10-01 21:11
```
if stdenv.isAarch64 then "arm64"
```

I don't see this on master. Am I missing a PR?

**Comment by orivej** [comment] 2017-10-01 21:34
Thank you, it must have slipped off the pull request. https://github.com/NixOS/nixpkgs/commit/8d4b0eefce8801f0a7b63442e63f1fbdc6504796
