### ISSUE TITLE
Gnome 3 doesn't remember favorites

### ISSUE THREAD

**Issue by liamwigney** [NixOS/nixpkgs#25906] opened 2017-05-19 01:39 UTC
## Issue description
In Gnome 3 you can select applications as "favorites" to remain pinned to the sidebar. Under NixOS every time I reboot I lose my favorites.

### Steps to reproduce

Install NixOS with Gnome.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
17.09pre106916.c5badb123a (Hummingbird)
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.9
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"17.09pre107265.0afb6d789c"
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
No

**Comment by bjornfor** [comment] 2017-05-20 13:26
Seems to be a regression. It works for me on NixOS 17.03, but not master.

**Comment by midchildan** [comment] 2017-05-22 01:31
I can confirm this on nixos-unstable. It seems that none of my Gnome Shell-related settings settings are actually being applied. Possibly related to #4415 ?

## Logs
```
May 22 09:09:28 misaki org.gnome.Shell.desktop[1552]: GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
May 22 09:12:14 misaki .seahorse-wrapp[2895]: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
May 22 09:12:14 misaki .gnome-contacts[2885]: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
May 22 09:14:18 misaki .seahorse-wrapp[3185]: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
May 22 09:14:18 misaki .gnome-contacts[3166]: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
May 22 09:14:33 misaki .gnome-control-[3223]: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
```

## Examples
### Favorites
configuration
![screenshot from 2017-05-22 09-13-26](https://cloud.githubusercontent.com/assets/7343721/26289189/b0a9c9f4-3ed8-11e7-951f-9d1edab7425b.png)
result
![screenshot from 2017-05-22 09-14-10](https://cloud.githubusercontent.com/assets/7343721/26289194/d04ee47e-3ed8-11e7-8b88-4e096346e5b3.png)
### Time Format
configuration
![screenshot from 2017-05-22 09-15-45](https://cloud.githubusercontent.com/assets/7343721/26289230/22231a22-3ed9-11e7-9585-11d15d6e6469.png)
result
![screenshot from 2017-05-22 09-14-39](https://cloud.githubusercontent.com/assets/7343721/26289236/2ce75c20-3ed9-11e7-9f2f-ef0e1df52c1c.png)

**Comment by ixxie** [comment] 2017-08-04 08:26
I just switched from 17.03 to unstable and encountered a related issue with gnome-tweak-tool not propagating settings (see #27926).

**Comment by jtojnar** [comment] 2017-08-04 08:33
@ixxie That is indeed the same bug, it is fixed by #26113.

**Comment by ixxie** [comment] 2017-08-04 08:40
@jtojnar - cool, so looks like this will be fixed any say now :)

**Comment by jtojnar** [comment] 2017-08-04 09:30
@ixxie Unfortunately, Nixpkgs seem to be short on GNOME maintainers at the moment.

**Closed** 2017-08-05 10:21 UTC
Labels: 0.kind: bug, 0.kind: regression, 1.severity: blocker, 6.topic: gnome3, 6.topic: nixos

**Comment by ixxie** [comment] 2017-08-05 13:43
@jtojnar I would love to help, but I am not sure how to start (also my skills are lacking still so it will go slowly).

**Comment by jtojnar** [comment] 2017-08-05 15:42
@ixxie Now the focus should be on migrating to GNOME 3.24, see #26879. You can rebase and check if everything works correctly. Then you can report it in the PR thread or even fix it yourself. Feel free to ping me on IRC if you run into any problems, or just ask anyone there, I am still a beginner too.

**Comment by ixxie** [comment] 2017-08-06 17:18
@jtojnar - I don't think its clear how much of a beginner I am; I never contributed to any project at all, let alone Nix. I have *some* familiarity with Nix and the workflow in open-source, but not enough to piece together a complete workflow (for example, I don't know how to isolate tests on my system without rebuilding the whole of it). Is there some kind of guide?

**Comment by bjornfor** [comment] 2017-08-06 19:39
@ixxie: Running the "gnome3" NixOS test:

```
$ cd my-nixpkgs-working-tree-cloned-from-github
nix-build nixos/tests/gnome3.nix
```

Then open ./result/log.html in your browser to view the result.

**Comment by ixxie** [comment] 2017-08-07 06:23
@bjornfor - easy enough! And how do I then go about testing the functionality itself without rebuilding my main system? Just run it?

**Comment by bjornfor** [comment] 2017-08-07 06:32
Yes. The nixos tests do not depend on your /etc/NixOS/configuration.nix file.

**Comment by ixxie** [comment] 2017-08-07 06:33
Thanks @bjornfor - I will give it a try!
