### ISSUE TITLE
Kontact does find Kontact/Plugin service type -> empty window

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#41426] opened 2018-06-03 19:54 UTC
## Issue description

Kontact does not find the Kontact/Plugin service type resulting empty window:

![screenshot_20180603_205250](https://user-images.githubusercontent.com/96200/40890581-2b816414-6770-11e8-8fab-5c1b99cd2eee.png)

I was also able to reproduce the error with this little c++ snippet:

```
# main.pro
SOURCES = main.cpp
QT += KService KCoreAddons
```

```
// main.cpp
#include <KServiceType>
#include <KServiceTypeTrader>

int main(int argc, char** argv) {
  QCoreApplication a(argc, argv);
  auto res = KServiceTypeTrader::self()->query(QStringLiteral("Kontact/Plugin"));
}
```

```
qmake main.pro
make
./main
kf5.kservice.services: KServiceTypeTrader: serviceType "Kontact/Plugin" not found

```

### Steps to reproduce

```
$ kontact
grantlee.template: "Plugin library 'kde_grantlee_plugin' not found."
grantlee.template: "Plugin library 'kde_grantlee_plugin' not found."
kf5.kservice.services: KServiceTypeTrader: serviceType "Kontact/Plugin" not found
grantlee.template: "Plugin library 'kde_grantlee_plugin' not found."
grantlee.template: "Plugin library 'kde_grantlee_plugin' not found."
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.42, NixOS, 18.09.git.3c5bdec (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `""`
 - channels(joerg): `"nixpkgs, unstable-small-18.09pre137207.92f0d31b949"`
 - nixpkgs: `/home/joerg/git/nixpkgs`

**Comment by Mic92** [comment] 2018-06-03 19:56
I don't understand how services are defined. What files do I need to look for to see what services are available on my system?

**Comment by Mic92** [comment] 2018-06-03 20:03
According to strace it also finds all kontact plugins in the service directory:

```
statx(AT_FDCWD, "/home/joerg/.nix-profile/share/kservices5/kontactconfig.desktop", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_BASIC_STATS, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=5847, ...}) = 0
statx(AT_FDCWD, "/home/joerg/.nix-profile/share/kservices5/kontact", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_BASIC_STATS, stx_attributes=0, stx_mode=S_IFDIR|0555, stx_size=9, ...}) = 0
openat(AT_FDCWD, "/home/joerg/.nix-profile/share/kservices5/kontact", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 7
statx(AT_FDCWD, "/home/joerg/.nix-profile/share/kservices5/kontact/todoplugin.desktop", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_BASIC_STATS, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=6754, ...}) = 0
statx(AT_FDCWD, "/home/joerg/.nix-profile/share/kservices5/kontact/summaryplugin.desktop", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_BASIC_STATS, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=5390, ...}) = 0
statx(AT_FDCWD, "/home/joerg/.nix-profile/share/kservices5/kontact/kmailplugin.desktop", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_BASIC_STATS, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=5172, ...}) = 0
statx(AT_FDCWD, "/home/joerg/.nix-profile/share/kservices5/kontact/specialdatesplugin.desktop", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_BASIC_STATS, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=5416, ...}) = 0
statx(AT_FDCWD, "/home/joerg/.nix-profile/share/kservices5/kontact/journalplugin.desktop", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_BASIC_STATS, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=5548, ...}) = 0
statx(AT_FDCWD, "/home/joerg/.nix-profile/share/kservices5/kontact/korganizerplugin.desktop", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_BASIC_STATS, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=5625, ...}) = 0
statx(AT_FDCWD, "/home/joerg/.nix-profile/share/kservices5/kontact/kaddressbookplugin.desktop", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_BASIC_STATS, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=5788, ...}) = 0
statx(AT_FDCWD, "/run/current-system/sw/share/kservices5/kontact", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_BASIC_STATS, stx_attributes=0, stx_mode=S_IFDIR|0555, stx_size=8, ...}) = 0
openat(AT_FDCWD, "/run/current-system/sw/share/kservices5/kontact", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 7
statx(AT_FDCWD, "/run/current-system/sw/share/kservices5/kontact/kmailplugin.desktop", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_BASIC_STATS, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=5172, ...}) = 0
statx(AT_FDCWD, "/run/current-system/sw/share/kservices5/kontact/specialdatesplugin.desktop", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_BASIC_STATS, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=5416, ...}) = 0
statx(AT_FDCWD, "/run/current-system/sw/share/kservices5/kontact/korganizerplugin.desktop", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_BASIC_STATS, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=5625, ...}) = 0
statx(AT_FDCWD, "/run/current-system/sw/share/kservices5/kontact/todoplugin.desktop", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_BASIC_STATS, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=6754, ...}) = 0
statx(AT_FDCWD, "/run/current-system/sw/share/kservices5/kontact/summaryplugin.desktop", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_BASIC_STATS, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=5390, ...}) = 0
statx(AT_FDCWD, "/run/current-system/sw/share/kservices5/kontact/journalplugin.desktop", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_BASIC_STATS, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=5548, ...}) = 0
```

**Comment by nydn** [comment] 2019-01-06 14:20
Were you able to solve this? I'm having the same issue right now and don't know what package or anything I am missing.

**Comment by johnalotoski** [comment] 2019-01-06 19:16
Hi nydn, I'm not sure if this will completely address your issue, but see the following references for packages.  I used to run into the same problem, but no longer do with this configuration.  See the Kontact/KDE related system packages installed at this [link](https://github.com/johnalotoski/nixos-etc/blob/6fa7d2a8ff270b3eb8d6266548219f8c5fa2e370/configuration.nix#L321) and then also the user Kontact/KDE installed packages found at this [link](https://github.com/johnalotoski/nixos-user/blob/58126afc94ea8057a01cb58abb5cda73515307da/config.nix#L29).

**Comment by Mic92** [comment] 2019-01-09 11:00
@nydn no

**Comment by Mic92** [comment] 2019-01-09 11:01
I suspect there might be some files in the wronge build output that prevent them from being linked into the profile.

**Comment by schmittlauch** [comment] 2019-01-17 22:47
@nydn Sadly setting up several mail accounts and calendars didn't fix the issue for me.

What packages have you got installed? Just Kontact or did you also explicitly install some parts of it (e.g. KMail, korganizer)? If yes, in which profile?

**Comment by nydn** [comment] 2019-01-21 12:08
Yes, I explicitly stated all the packages, in my system configuration because I wasn't sure. Half of them probably doesn't need to be in there, but I haven't got the time to check all the dependencies and clean it up.
```
{ 
    ...
    systemPackages = with pkgs; with plasma5; with kdeApplications;
    [
     ...
      # KDE Apps
      akonadi
      akonadi-calendar
      akonadi-contacts
      akonadi-import-wizard
      akonadi-mime
      akonadi-notes
      akonadi-search
      akonadiconsole
      akregator
      ark
      gwenview
      kaddressbook
      kalarm
      kalarmcal
      kate
      kcalcore
      kcalutils
      kcontacts
      kdav
      kdepim-addons
      kdepim-apps-libs
      kdepim-runtime
      kdialog
      kidentitymanagement
      kldap
      kmail
      kmailtransport
      kmbox
      kmime
      kmix
      kontact
      kontactinterface
      korganizer
      konversation
      kpimtextedit
      libkdepim
      libksieve
      mailcommon
      messagelib
      pimcommon
      pim-sieve-editor
      okular
      oxygen
      oxygen-icons5
      oxygenfonts
      redshift-plasma-applet
      spectacle
      # End of KDE Apps
    ];
  };
  ...
}
```

Strangely, I have encountered this same issue on a brand new Arch install last week and adding a New Account solved it there too.

**Comment by schmittlauch** [comment] 2019-01-21 15:25
Adding the packages mentioned by @nydn to my system packages helped, now Kontact is working as intended.

Over the next days I'm going to remove those packages from my environment again one by one, to find the problematic ones.

**Comment by Mic92** [comment] 2019-01-21 15:32
bisect search might be faster :)

**Comment by schmittlauch** [comment] 2019-01-21 15:34
@Mic92 yeah, already had that idea. But enough procrastination for me today…

**Comment by schmittlauch** [comment] 2019-01-29 09:38
I was able to narrow it down to `nixpkgs.kdeApplications.kontactinterface` for Kontact (and additionally     `kdeApplications.akonadi-mime` for KOrganizer to work, see #38887) to be present in environment.systemPackages.
That is a workaround, but a proper fix for the Kontact derivation itself would be welcome.

**Comment by Mic92** [comment] 2020-06-03 08:16
I am not sure if there is a way to provide this through a wrapper. Maybe we can at least document it somewhere?

**Comment by Mic92** [comment] 2020-11-30 12:21
I don't think this has been solved.

**Comment by vs49688** [comment] 2021-12-28 10:10
Not stale. There's something bigger going on here, specifically relating to the `grantlee.template: "Plugin library 'kde_grantlee_plugin' not found."` error.

When I run kontact, kmail, kaddress, or korganizer via terminal, they all work perfectly. When run via KRunner (which uses systemd), I see odd behaviour similar to this, suggesting an environment issue.

Dumping the environment variables for each shows significant differences - I've attached the dumps for reference.
[kontact-logs.zip](https://github.com/NixOS/nixpkgs/files/7784104/kontact-logs.zip)

**Comment by liketechnik** [comment] 2021-12-31 11:10
Interestingly, I do not have a fully blank window, but 'only':
- the problem described in #96255 (e. g. akregator not being able to show the content of emails)
- and kmail not showing any mail bodies (e. g. sender, receiver, attachments, etc. are displayed correctly, but the body itself stays empty)

Additionally, I experienced it in the same way as @vs49688, after switching from X to wayland (things work fine on X but are broken on wayland).

-------

Today I was able to narrow it down to one specific env variable:

- inside my terminal, the env variable `NIX_PROFILES` is set:
```terminal
$ echo $NIX_PROFILES
/run/current-system/sw /nix/var/nix/profiles/default /etc/profiles/per-user/florian /home/florian/.nix-profile /var/lib/flatpak/exports /home/florian/.local/share/flatpak/exports
```
- starting via krunner (or the application menu or autostart), does not have that variable set. I tested that via `notify-desktop` (enter the following command into krunner or the start menu): `notify-desktop "nix profiles variable" "$(echo $NIX_PROFILES)"`

I suspect the root cause my be the same as in https://github.com/NixOS/nixpkgs/issues/129442#issuecomment-876212507 (e. g. wayland not picking up certain files defining env variables), therefore the workaround mentioned in the comment should work for this problem too (I'll try to find the time for testing it and put my result here).

**Comment by liketechnik** [comment] 2021-12-31 11:45
Adding 

```nix
  environment.sessionVariables = {
    NIX_PROFILES = "${lib.concatStringsSep " " (lib.reverseList config.environment.profiles)}";
  };
```

indeed fixes the issue for me.

Because the problem is not unique to kontact and the variable also isn't specific to kontact, I don't think the variable should be defined/changed just for kontact, though I'm not nearly experienced enough with nix to have any idea where to put it. Therefore I unfortunately don't see myself in the position to open a PR for (I'm happy to tackle this with some guidance though ;)

**Comment by vs49688** [comment] 2022-01-01 07:19
> Interestingly, I do not have a fully blank window, but 'only':
> 
>     * the problem described in [Akregator bug: Plugin library 'kde_grantlee_plugin' not found. #96255](https://github.com/NixOS/nixpkgs/issues/96255) (e. g. akregator not being able to show the content of emails)
> 
>     * and kmail not showing any mail bodies (e. g. sender, receiver, attachments, etc. are displayed correctly, but the body itself stays empty)
> 

That is exactly the behaviour I'm seeing, and the above fixes it for me.

Should this be closed as a dup of https://github.com/NixOS/nixpkgs/issues/129442?

**Closed** 2022-01-01 17:40 UTC
