### ISSUE TITLE
Wayland by default now on KDE (??) + clock broken 

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#143272] opened 2021-10-28 01:59 UTC
### Describe the bug
I updated today my distribution on latest unstable (I was already on unstable before). And it turned out that many things suddently broke (the clock is broken, my `services.xserver.xkbOptions` does not work anymore (of course), Carla's software does not have anymore a "Canvas" menu, NSM can't run Carla or it gets an error, Giada also fails to connect to Jack...). I quickly realized that I was running Wayland instead of X11, while I was always running X11 before on KDE Plasma.

Moreover, the KDE clock and calendar is now broken (negative numbers+hour does not appear at all+what is this `0%2?`):

![image](https://user-images.githubusercontent.com/2164118/139172375-62d27bd5-c922-43b4-b34b-7ec5d7c59049.png)

So here are my questions:
1. is it normal that Wayland is the default now? I can't find any documentation on Wayland vs X11, and it seems a bit risky to use Wayland by default given all the bugs I encountered...
2. If yes, how can I configure X11 to be the default? (I mean in the configuration file, not by just changing at connection time)
3. How can I get the clock and calendar back?
4. Any idea why Carla, Giada and NSM are also not working properly with Wayland? (I'm using pipewire)

### Steps To Reproduce
1. Enable `  services.xserver.displayManager.sddm.enable = true; services.xserver.desktopManager.plasma5.enable = true;`
2. Upgrade the system and reboot

### Notify maintainers

@peterhoeg 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.75, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - channels(me): `"nixos-unstable-21.11pre325514.a4bf4434570, home-manager, local-nixos-unstable-21.11pre304626.8ecc61c91a5, local-nixpkgs-unstable-21.11pre304920.dd98b100651, nixos-20-03-20.03.3328.6d1a044fc9f, test"`
 - channels(root): `"nixos-21.11pre325514.a4bf4434570"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by oxalica** [comment] 2021-10-29 19:44
I notice that the env var `TZDIR` is somehow missing for `plasmashell`. I run `plasmashell --replace` with `TZDIR` correctly set, and the clock widget just works. Running it with empty `TZDIR` reproduces the same broken clock.

I checked that `startplasma-wayland`, `kwin_wayland_wrapper` have `TZDIR`, but `startplasma-waylandsession` and `plasmashell` don't. Since `startplasma-wayland` is the session entrance started by `sddm` (so it's not `sddm`'s fault), we can know the envvar somehow gets dropped during the plasma starting chain.

**Comment by oxalica** [comment] 2021-10-29 22:50
By comparing `/proc/<pid>/environ` between `kwin_wayland{,_wrapper}`, exactly `TZDIR` is dropped when the wrapper running `kwin_wayland`, no other environment variable are added, removed or modified.

`kwin_wayland` is wrapped to gain CAP_SYS_NICE,
https://github.com/NixOS/nixpkgs/blob/b0d580340086409e6181643a37d82d834a164bf2/nixos/modules/services/x11/desktop-managers/plasma5.nix#L219-L225

I'm not sure how the `security.wrappers` work, but simply removing this wrapper just fix the clock widget issue. But it's definitely not a good idea since `kwin_wayland` is expecting to be real time scheduled.

cc @rnhmjoj

**Comment by rnhmjoj** [comment] 2021-10-30 09:37
> I'm not sure how the security.wrappers work, but simply removing this wrapper just fix the clock widget issue. But it's definitely not a good idea since kwin_wayland is expecting to be real time scheduled.

I have nothing to do with KDE, but I made a few changes to `security.wrappers` in [fedd7cd6](https://github.com/NixOS/nixpkgs/commit/fedd7cd6901646cb7e2a94a148d300f7b632d7e0#diff-03fbf9f534327a96ff2a6a1b6b3aa40a397d3dd9cac950f5af0ed500316b7512). I don't see how this could possibly have affected the clock, but you could try reverting my commits if you think this is related.

**Comment by oxalica** [comment] 2021-10-30 11:12
> but I made a few changes to security.wrappers in fedd7cd6.

That may be unrelated.

I found the related upstream issue https://bugs.kde.org/show_bug.cgi?id=400451
The cause here is that `ld.so` rejects `TMPDIR`, `TZDIR` and some other env vars in secure-excution mode, including programs with `setuid` or capabilities. See [ld.so(8)](https://man7.org/linux/man-pages/man8/ld.so.8.html#ENVIRONMENT) In our case, `kwin_wayland` has capabilities set. 

But I'm still not sure how we could workaround this. Currently my thought is to patch `kwin_wayland_wrapper` and `kwin_wayland` to let the wrapper pass these envvars in other ways, like renaming envvar name or passing through arguments.
If there's a better way to workaround, please point it out.

**Comment by haizaar** [comment] 2021-11-02 10:14
The "Wayland by default" thing was introduced here: https://github.com/NixOS/nixpkgs/pull/117102 as part of KDE Wayland support in NixOS in general. Mb shouldn't be default yet or at least not to override previous preference of X11 during upgrade.

**Comment by oxalica** [comment] 2021-11-02 10:45
Current status:

- The clock issue can be workaround by setting `services.xserver.desktopManager.plasma5.runUsingSystemd = true` since #144098 which is already in `master`.
  It will be fixed (without `runUsingSystemd`) in #143842
- The default session will be set back to X11 on SDDM in #143673 
  Currently, you can manually switch to X11 and login once, and SDDM will remember your last choice (hopefully, it may be reset if you change available desktop sessions. It's an issue of SDDM and I'll look into it later).

**Comment by haizaar** [comment] 2021-11-02 10:59
> * The clock issue can be workaround by setting `services.xserver.desktopManager.plasma5.runUsingSystemd = true` since [plasma-workspace: fix systemd unit detection and `plasma5.runUsingSystemd` #144098](https://github.com/NixOS/nixpkgs/pull/144098) which is already in `master`.

This fix didn't work for me. The clock is still broken in exactly the same way as reported in this bug.
Even after logging into fresh user.

**Comment by oxalica** [comment] 2021-11-02 22:03
@haizaar

> > * The clock issue can be workaround by setting `services.xserver.desktopManager.plasma5.runUsingSystemd = true` since [plasma-workspace: fix systemd unit detection and `plasma5.runUsingSystemd` #144098](https://github.com/NixOS/nixpkgs/pull/144098) which is already in `master`.
> 
> This fix didn't work for me. The clock is still broken in exactly the same way as reported in this bug. Even after logging into fresh user. (Again, I'm on Wayland)

Are you sure on nixpkgs `master` and that option is enabled? Please check if the plasma systemd service is started by `systemctl status --user plasma-plasmashell.service`.
- If it's not running, please open another issue for `services.xserver.desktopManager.plasma5.runUsingSystemd` not working. 
- If it's running, then there may be some issue of `systemd`. Since `systemd --user` will load PAM environment, which must contain `TZDIR`, and it will be propagated to other units. In this case please open an issue about "systemd user units not picking PAM environment".

**Comment by haizaar** [comment] 2021-11-02 23:11
Thanks for your advice! Yes indeed I'm on master (last synced yesterday) and have this option enabled:
```
  # Enable the X11 windowing system.
  services.xserver.enable = true;

  # Enable the Plasma 5 Desktop Environment.
  services.xserver.displayManager.sddm.enable = true;
  services.xserver.desktopManager.plasma5.enable = true;
  # Wayland will NOT be default in the meanwhile
  # https://github.com/NixOS/nixpkgs/issues/143272#issuecomment-957323052
  services.xserver.desktopManager.plasma5.runUsingSystemd = true;
```
```
$ systemctl status --user plasma-plasmashell.service
○ plasma-plasmashell.service - KDE Plasma Workspace
     Loaded: loaded (/run/current-system/sw/share/systemd/user/plasma-plasmashell.service; linked-runtime; vendor preset: enabled)
     Active: inactive (dead)
```
Though it says "dead" for some reason (and I'm writing this from an active KDE session), `plasmashell` process is a child of systemd according to pstree
```
-+= 00001 root systemd 
...
 |-+- 01374 haizaar /nix/store/fxlbyg5bwiddyjysj9vlhhb08dizs38l-plasma-workspace-5.23.1/bin/plasmashell 
```
TZDIR is defined as well:
```
[nix-shell:~/Desktop]$ env |grep TZ
TZDIR=/etc/zoneinfo

[nix-shell:~/Desktop]$ ls -lah /etc/zoneinfo
lrwxrwxrwx 1 root root 20 Nov  3 00:29 /etc/zoneinfo -> /etc/static/zoneinfo

[nix-shell:~/Desktop]$ ls -lah /etc/static/zoneinfo
lrwxrwxrwx 1 root root 71 Jan  1  1970 /etc/static/zoneinfo -> /nix/store/x629s2442r2qfa3834rl4iqrai24fym6-tzdata-2021a/share/zoneinfo
```

Do you have any other ideas?

**Comment by haizaar** [comment] 2021-11-02 23:18
Looking at `plasmashell`'s process env, indeed `TZDIR` env is not defined there. Is that the issue you are trying to point out?
```
cat /proc/1374/environ  |tr '\0' '\n' |grep TZDIR
```
(The above returns nothing)

**Comment by oxalica** [comment] 2021-11-03 07:42
@haizaar Please open an issue about `runUsingSystemd` not working, and provide `~/.local/share/sddm/wayland-session.log` there.

**Comment by haizaar** [comment] 2021-11-03 13:35
Did another update from unstable (it updated LOTs of packages) and after reboot, the clock is working again! (and TZDIR env is indeed known to plasma).

@oxalica thanks again for jumping on this!

**Closed** 2021-11-07 12:29 UTC
Labels: 0.kind: bug, 6.topic: qt/kde

**Comment by jansol** [comment] 2021-11-09 17:44
Could this be the same root cause for issues with IMEs, screen capturing and Flameshot simply not working at all?
IME (fcitx) does not activate, screen capturing in browsers and OBS does not show a source selection dialog, Flameshot does not react to its DBus invocation (Spectacle works although it is dog slow -- not sure what their internal differences are)
See #91218 and https://github.com/NixOS/nixpkgs/pull/117102#issuecomment-920753126

I don't know much about DBus but the bit about it not finding services dirs sounds like it could be caused by something like this. I also remember seeing some logs from Flameshot where it thinks it has been started already but actually invoking its screenshot function does not do anything -- wrong DBus instance?

... Or am I the only one with these problems on plasma/wayland? :D

**Comment by oxalica** [comment] 2021-11-13 17:55
For the `flameshot` issue, see #145777
