### ISSUE TITLE
ZFS umount errors during shutdown

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#34616] opened 2018-02-05 09:53 UTC
Hi.

I'm trying to use separate mountpoints for MySQL in nixos, like this:

```
/ = ztank/nixos/root1
/nix = ztank/nixos/nix
/tmp = ztank/nixos/tmp
/var/tmp = ztank/nixos/tmp_var
/home/user = ztank/home/user
/var/lib/mysql = ztank/data/mysql
/var/lib/mysql/ibdata = ztank/data/mysql/ibdata
/var/lib/mysql/iblogs = ztank/data/mysql/iblogs
```

As result, I observe the following errors during system shutdown:
```
Feb 05 12:09:39 nixos-vmware systemd[1]: ^[[0;1;39mvar-lib-mysql-iblogs.mount: Mount process exited, code=exited status=32
Feb 05 12:09:39 nixos-vmware systemd[1]: Failed unmounting /var/lib/mysql/iblogs.
Feb 05 12:09:39 nixos-vmware systemd[1]: ^[[0;1;39mrun-user-1000.mount: Mount process exited, code=exited status=32
Feb 05 12:09:39 nixos-vmware systemd[1]: Failed unmounting /run/user/1000.
Feb 05 12:09:40 nixos-vmware systemd[1]: ^[[0;1;39mvar-lib-mysql.mount: Mount process exited, code=exited status=32
Feb 05 12:09:40 nixos-vmware systemd[1]: Failed unmounting /var/lib/mysql.
```
Filesystem mount options in hardware-configuration.nix:
```
  fileSystems."/" = {
    device = "ztank/nixos/root1";
    fsType = "zfs";
    options = [ "relatime" "xattr" "posixacl" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4046e960-93b6-4f13-a5d5-70ae52932573";
    fsType = "ext3";
    options = [ "relatime" ];
  };

  fileSystems."/nix" = {
    device = "ztank/nixos/nix";
    fsType = "zfs";
    options = [ "relatime" "xattr" "posixacl" ];
  };

  fileSystems."/etc/nixos" = {
    device = "ztank/nixos/cfg";
    fsType = "zfs";
    options = [ "relatime" "xattr" "posixacl" ];
  };

  fileSystems."/tmp" = {
    device = "ztank/nixos/tmp";
    fsType = "zfs";
    options = [ "nosuid" "nodev" "noatime" ];
  };

  fileSystems."/var/tmp" = {
    device = "ztank/nixos/tmp_var";
    fsType = "zfs";
    options = [ "nosuid" "nodev" "noatime" "noexec" ];
  };

  fileSystems."/home/user" = {
    device = "ztank/home/user";
    fsType = "zfs";
    options = [ "relatime" "xattr" "posixacl" ];
  };

  fileSystems."/root" = {
    device = "ztank/home/root";
    fsType = "zfs";
    options = [ "relatime" "xattr" "posixacl" ];
  };

  fileSystems."/var/lib/mysql" = {
    device = "ztank/data/mysql";
    fsType = "zfs";
    options = [ "relatime" "xattr" "posixacl" ];
  };

  fileSystems."/var/lib/mysql/ibdata" = {
    device = "ztank/data/mysql/ibdata";
    fsType = "zfs";
    options = [ "relatime" "xattr" "posixacl" ];
  };

  fileSystems."/var/lib/mysql/iblogs" = {
    device = "ztank/data/mysql/iblogs";
    fsType = "zfs";
    options = [ "relatime" "xattr" "posixacl" ];
  };
```
I also tried the following:
```
zfs set mountpoint=/var/lib/mysql /var/lib/mysql
zfs set mountpoint=/var/lib/mysql/ibdata ztank/data/mysql/ibdata
zfs set mountpoint=/var/lib/mysql/iblogs ztank/data/mysql/iblogs
```

But it did not help. Unmounting is done by systemd, and the same errors occur.

Method, recommended in the following comment, does not help either:  https://github.com/NixOS/nixpkgs/issues/21928#issuecomment-274155848

How can I ensure that unmounting of filesystems is done correctly? Where/how can I configure systemd to wait for full stop of MySQL before unmounting ZFS file systems?

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0, NixOS, 18.03pre126729.2e4aded3669 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre126729.2e4aded3669"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Mic92** [comment] 2018-02-05 10:53
Please use `legacy` mountpoints as described in the wiki: https://nixos.wiki/wiki/NixOS_on_ZFS#How_to_use_it
Otherwise mountpoints cannot be correctly ordered on startup and shutdown. 
This might change in future, when we have a fstab generator for zfs: https://github.com/zfsonlinux/zfs/pull/4943

**Comment by Mic92** [comment] 2018-02-05 10:56
Usually systemd makes sure, that all processes are killed before it unmounts local filesystems.

**Comment by Mic92** [comment] 2018-02-05 10:58
The errno is quite strange. EBUSY should be returned if mysql is still accessing the device.

**Comment by Izorkin** [comment] 2018-02-05 12:06
Yes, me used legacy mountpoints
```
zfs list | grep mysql
ztank/data/mysql          582K  8,31G    25K  legacy
ztank/data/mysql/ibdata   527K  8,31G   527K  legacy
ztank/data/mysql/iblogs  29,5K  8,31G  29,5K  legacy
```

**Comment by Izorkin** [comment] 2018-02-05 16:57
Is it possible to configure systemd to skip mounting/unmounting of file systems altogether?

**Comment by Mic92** [comment] 2018-02-26 22:52
Mounting can be disabled using: `fileSystems."/mnt/backup".options = ["noauto"];`

**Comment by Mic92** [comment] 2018-02-26 22:53
I also use `nofail` sometimes to mark a mountpoint as non-critical.

**Comment by phryneas** [comment] 2018-08-16 16:46
Has one of your filesystems (most likely tmp) `sync=disabled`?
That could be caused by this bug: https://github.com/zfsonlinux/zfs/issues/7753#issuecomment-413598935

**Comment by Izorkin** [comment] 2018-08-17 04:54
Yes

**Comment by phryneas** [comment] 2018-08-17 06:07
Nice! I know, this issue is half a year old - but a bug report is on the way :)

**Comment by waphire** [comment] 2019-02-10 19:27
So, one possible workaround for using zfs native mounts is adding only the root filesystem mountpoint to `/etc/nixos/hardware-configuration.nix` (just so it doesn't throw an error) and rebuilding your system with zfs datasets (including the root dataset) set to native mounts.

**Comment by Mic92** [comment] 2019-02-10 21:47
We have now 0.8.0-rc3 merged into nixos, that should have this bugfix.
Can we close this issue? https://github.com/zfsonlinux/zfs/issues/7753#issuecomment-413598935

**Comment by Izorkin** [comment] 2019-02-11 04:59
I have another configuration now. 
There is only such an error

```
фев 09 22:10:09 elven.pw umount[2381]: umount: /var: target is busy.
фев 09 22:10:09 elven.pw systemd[1]: ^[[0;1;39m^[[0;1;39mvar.mount: Mount process exited, code=exited status=32
фев 09 22:10:09 elven.pw systemd[1]: ^[[0;1;39mFailed unmounting /var.
```

**Comment by Izorkin** [comment] 2019-02-11 07:36
Checked on a virtual machine
```
фев 11 10:31:13 nixos-local systemd[1]: Unmounting /var/lib/mysql/ibdata...
фев 11 10:31:13 nixos-local systemd[1]: Unmounting /var/lib/mysql/iblogs...
...
фев 11 10:31:13 nixos-local systemd[1]: Unmounted /var/lib/mysql/ibdata.
фев 11 10:31:13 nixos-local systemd[1]: Unmounted /var/lib/mysql/iblogs.
...
фев 11 10:31:13 nixos-local systemd[1]: Unmounting /var/lib/mysql...
...
фев 11 10:31:13 nixos-local systemd[1]: Unmounted /var/lib/mysql.
фев 11 10:31:13 nixos-local systemd[1]: Unmounting /var...
фев 11 10:31:13 nixos-local umount[25261]: umount: /var: target is busy.
фев 11 10:31:13 nixos-local systemd[1]: var.mount: Mount process exited, code=exited status=32
фев 11 10:31:13 nixos-local systemd[1]: Failed unmounting /var.
фев 11 10:31:13 nixos-local systemd[1]: Reached target Unmount All Filesystems.
```
/var/lib/mysql normally unmount

**Comment by phryneas** [comment] 2019-02-11 11:25
which version of zfs & spl are you running?
`modinfo zfs | grep version` and `modinfo spl | grep version`

**Comment by Izorkin** [comment] 2019-02-11 12:22
zfs
```
version:        0.8.0-rc3
srcversion:     E8ED8A9D1524780F1F823C9
```
spl
```
version:        0.8.0-rc3
srcversion:     52EA3DB565B585F98955FAE
```

Unmount error "/ var" probably does not apply to zfs.

**Comment by Mic92** [comment] 2020-06-03 10:26
Is this still an issue?

**Closed** 2020-06-04 18:32 UTC
