### ISSUE TITLE
onlyoffice-bin - not launching due to missing GLIBCXX_3.4.30 dependency

### ISSUE THREAD

**Issue by rkunschke** [NixOS/nixpkgs#218601] opened 2023-02-27 11:20 UTC
### Describe the bug
When I try to launch onlyoffice-bin this message appears in the terminal:
`/nix/store/fgsp7brxrj78r0sc714cg1rrajwdggz4-onlyoffice-desktopeditors-7.2.0/share/desktopeditors/DesktopEditors: /nix/store/fgsp7brxrj78r0sc714cg1rrajwdggz4-onlyoffice-desktopeditors-7.2.0/share/desktopeditors/converter/.system/libstdc++.so.6: version "GLIBCXX_3.4.30" not found (required by /nix/store/jlx2nfpi73sjb0f3096cly5ik8arw9k9-icu4c-72.1/lib/libicuuc.so.72)
`

### Steps To Reproduce
1. install onlyoffice-bin
2. open onlyoffice inside the terminal
3. this message appears and onlyoffice does not launch

### Additional context
I am using the unstable channel.

### Notify maintainers
@nh2 @GTrunSec Can you have a look at this issue please?

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.13-xanmod1, NixOS, 23.05 (Stoat), 23.05pre457956.9952d6bc395`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixos"`
 - channels(reini): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by anund** [comment] 2023-02-27 14:01
Duplicate of https://github.com/NixOS/nixpkgs/issues/218238 ?

**Closed** 2023-02-27 19:16 UTC
Labels: 0.kind: bug
