### ISSUE TITLE
allowUnfree is broken

### ISSUE THREAD

**Issue by cmm** [NixOS/nixpkgs#171810] opened 2022-05-06 11:39 UTC
### Describe the bug
After https://github.com/NixOS/nixpkgs/commit/1c49b81263858c69b932da05ae63a7767b308e74 setting `nixpkgs.config.allowUnfree = true` has no effect.

(Probably same for `allowBroken` and `allowUnsupportedSystem`, didn't check)

(I guess it still works when set as explicit nixpkgs import attribute?  Didn't check either)

### Steps To Reproduce
1. Have a system/home config that sets `nixpkgs.config.allowUnfree` in a module (not as nixpkgs import attribute)
2. Move to nixpkgs past https://github.com/NixOS/nixpkgs/commit/1c49b81263858c69b932da05ae63a7767b308e74
3. Watch you config break

### Additional context
My config is a flake, could that be somehow relevant?

### Notify maintainers
@Artturin 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.5, NixOS, 22.05 (Quokka), 22.05.20220506.e23ece8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - channels(root): `""`
 - channels(cmm): `""`
 - nixpkgs: `/home/cmm/.config/home/input/nixpkgs`
```

**Comment by cmm** [comment] 2022-05-06 11:42
Thanks for missing `allowUnfreePredicate`, so that one still works :)

**Comment by cmm** [comment] 2022-05-06 12:49
Yeah, it's actually specific to my home-config (system config's fine), so probably this: https://github.com/nix-community/home-manager/issues/2942

Sorry for the noise!

**Comment by Pablo1107** [comment] 2022-05-06 15:49
> Thanks for missing `allowUnfreePredicate`, so that one still works :)

For someone encountering this same issue, a workaround is to add this your nixpkgs config:
`nixpkgs.config.allowUnfreePredicate = (pkg: true);`

This will allow any unfree package to be installed.

**Comment by gebner** [comment] 2022-05-14 09:58
It looks like the change also caused issues with `flake-utils-plus`, this fails now:
```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/1c49b81263858c69b932da05ae63a7767b308e74";
    utils.url = "github:gytis-ivaskevicius/flake-utils-plus/v1.3.1";
  };

  outputs = inputs@{ self, utils, ... }: utils.lib.mkFlake {
    inherit self inputs;

    hosts.default.modules = [
      ({ pkgs, ... }: {
        environment.systemPackages = [ pkgs.discord ];
        nixpkgs.config.allowUnfree = true;
      })
    ];
  };
}
```

**Comment by nyanloutre** [comment] 2022-05-18 17:51
This issue is still relevant for me

**Comment by Artturin** [comment] 2022-05-18 17:58
nixos or home-manager? please provide a reproducer

**Comment by eclairevoyant** [comment] 2024-02-22 15:55
This should be working as designed on the NixOS/nixpkgs side, and even the HM bug was fixed in a prior release.

If there's still an issue with the behaviour, please provide an example to reproduce and file a new issue (if an issue does not already exist for the topic).

**Closed** 2024-02-22 15:55 UTC
Labels: 0.kind: bug
