### ISSUE TITLE
Collision between pandoc-crossref and haskell-language-server (libHShaddock)

### ISSUE THREAD

**Issue by DavSanchez** [NixOS/nixpkgs#197389] opened 2022-10-23 16:04 UTC
### Describe the bug
Ttrying to switch to a setup using both `haskellPackages.haskell-language-server` and `haskellPackages.pandoc-crossref` causes this error:

```console
 > error: collision between `/nix/store/kb1m1wp35d90cfwds6insy79rx26npjn-pandoc-crossref-0.3.13.0/lib/links/libHShaddock-library-1.10.0-JE5iPDDobj72f6xOR2JdOh-ghc9.0.2.dylib' and `/nix/store/viz4yf7y0pibv5cd0sqxmx45cyjvy3dz-haskell-language-server-1.8.0.0/lib/links/libHShaddock-library-1.10.0-JE5iPDDobj72f6xOR2JdOh-ghc9.0.2.dylib'
```

### Steps To Reproduce
1. Add `haskellPackages.haskell-language-server` to your packages
2. Add `haskellPackages.pandoc-crossref` to your packages
3. Try to switch.

### Expected behavior
These 2 packages should be able to be installed together.

### Additional context
I'm also using nix-darwin and home-manager, but I think this is a nixpkgs issue.

### Notify maintainers
@maralorn (for HLS, not sure who to tag for pandoc-crossref).

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.6.0, macOS 12.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.0`
 - channels(david): `"darwin"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Thank you very much!

**Comment by maralorn** [comment] 2022-10-23 16:17
Phew, that’s a weird one. I am quite uncertain about the problem, but my best guess is that we have a reproducibility issue here. Maybe two darwin builders somehow have two subtly different versions of the same haddock library? Which causes a clash because normally this should be the same file and merging it shouldn’t be an issue. If that’s the right guess, then this would be very annoying, but at least transient.
I don‘t believe this is very package specific, but maybe someone else knows more about this.

**Comment by maralorn** [comment] 2022-10-23 16:17
(Sorry, didn’t mean to close.)

**Comment by Et7f3** [comment] 2022-10-23 19:20
Could it be 2 package depending on the same ghc version but with different parameters? and propagateBuildInputs thus clashing each other ? I would investigate that root by seeing what is in dependencies of each packages.

**Comment by DavSanchez** [comment] 2022-10-24 22:21
Hi,

Thanks for the feedback, @maralorn well if it's transient then I guess waiting for new nixpkgs versions from unstable could fix this on its own?

I'll try to investigate this as you suggest @Et7f3, though I'm not sure how to check the roots you mention yet. Any advice?

**Comment by maralorn** [comment] 2022-10-24 22:29
If Et7f3 is right, then there should be different haddock derivations in the closures of haskellPackages.haskell-language-server and haskellPackages.crossref-pandoc. I think that’s theoretically possible, but quite unlikely because haddock is a boot package delivered with ghc and I have never heard of a situation, where we build different packages in the same package set with different ghcs.

**Comment by maralorn** [comment] 2022-10-24 22:42
I stand corrected. There are actually to different haddock-libraries in play here, and they both have different derivation hashes.
hls builds its own here: https://hydra.nixos.org/build/195595296#tabs-buildsteps, drv: `/nix/store/wh316k3ncyb3qh60cimz7ni7rvkp1x1l-haddock-library-1.10.0.drv` 
While the normal haddock is here: https://hydra.nixos.org/build/195622441, drv: `/nix/store/wh316k3ncyb3qh60cimz7ni7rvkp1x1l-haddock-library-1.10.0.drv`
Next step is to find out if this is a darwin-aarch64 issue only, and then were in nixpkgs the offending override resides.

**Comment by maralorn** [comment] 2022-10-24 22:58
More of my findings: I got confused between `haddock` which is a ghc core package and `haddock-library` which isn’t, and the later one is the culprit here. x86_64-linux is also affected.

**Comment by maralorn** [comment] 2022-10-24 23:25
Huh, I found the culprit:
```
❯ nix-diff /nix/store/ia75a2kciqf0sr0zhf5zkx89g7jdxbpq-haddock-library-1.10.0 /nix/store/2czj08dmx4ln828jm886vqi196a3ifll-haddock-library-1.10.0
- /nix/store/ia75a2kciqf0sr0zhf5zkx89g7jdxbpq-haddock-library-1.10.0:{out}
+ /nix/store/2czj08dmx4ln828jm886vqi196a3ifll-haddock-library-1.10.0:{out}
• The input derivation named `tree-diff-0.2.2` differs
  - /nix/store/n5r68qm0a6ax15g98phz06ny43vyrpd5-tree-diff-0.2.2.drv:{out}
  + /nix/store/gkb6n0p8jz0200s1vqdjb96843rr9z0l-tree-diff-0.2.2.drv:{out}
  • The input derivation named `trifecta-2.1.2` differs
    - /nix/store/al4529l0fnlcl372pypyrdqp4z4wyjrl-trifecta-2.1.2.drv:{out}
    + /nix/store/90rzbba7as9sngcpfch71lvxd6x2lavj-trifecta-2.1.2.drv:{out}
    • The input derivation named `prettyprinter-ansi-terminal-1.1.3` differs
      - /nix/store/2825xljc4m29i77iyky7g4kzbp0dfm9k-prettyprinter-ansi-terminal-1.1.3.drv:{out}
      + /nix/store/k8apsjs29n52wscfmzin6fdpnqfb9540-prettyprinter-ansi-terminal-1.1.3.drv:{out}
      • The input derivation named `doctest-0.18.2` differs
        - /nix/store/5vdlrh6kr6g9wbkdsk05lpjapnnsqzxz-doctest-0.18.2.drv:{out}
        + /nix/store/md8cljrqnz0vx5hz7n7if221fdaki20j-doctest-0.18.2.drv:{out}
        • The input derivation named `ghc-paths-0.1.0.12` differs
          - /nix/store/3k9k5mbjw2kay0cyiyi9b555dqrnrq0a-ghc-paths-0.1.0.12.drv:{out}
          + /nix/store/spkba0r69r9cgldzz9fyzpyv7ar02w4s-ghc-paths-0.1.0.12.drv:{out}
          • The set of input derivation names do not match:
              - Cabal-3.6.3.0
          • The environments do not match:
              nativeBuildInputs=''
              /nix/store/dkx556v7h19hnhdj55vj6d449jra3nrw-ghc-9.0.2 /nix/store/gffw4l741fqp6shayrw4966lic13p1bz-remove-references-to  /nix/store/awnb28mygayyzcmb3v6z0zdjfy0gljyq-Cabal-3.6.3.0    
          ''
        • Skipping environment comparison
      • Skipping environment comparison
    • Skipping environment comparison
  • Skipping environment comparison
• Skipping environment comparison
```
This is caused by this override:

https://github.com/NixOS/nixpkgs/blob/743264a9cd2818b33a82e1d41b606dc753f34222/pkgs/development/haskell-modules/configuration-ghc-9.0.x.nix#L105

I knew that `overrideScope` can be a dangerous tool, I didn’t know how dangerous. I need to think about how to fix this without causing other issues.

**Comment by Et7f3** [comment] 2022-10-25 01:32
Can it be changed to `Cabal = self.Cabal_3_8_1_0;` that's way the collision still exists but it won't pull two derivation and won't cause conflict.

**Comment by maralorn** [comment] 2022-10-27 20:24
I am not sure. The default Cabal with ghc 9.0.2 is 3.4.1 so using 3.6.3 is already a real override, and I am uncertain as to why haddock-library gets twice the same abi-hash when built with different Cabal versions.

**Comment by maralorn** [comment] 2022-10-27 20:36
Well, the reason is: haddock-library does not actually depend on Cabal, Cabal is just in the closure because of this remove reference-to and that leads to the same build happening twice. But because ghc compilation is not reproducible that can lead to conflicts.

**Comment by maralorn** [comment] 2022-10-27 20:41
Maybe the Cabal version used to build the Setup.hs script does not influence the result hash. ghc-paths does somehow declare a Cabal dependency but only uses Cabal in the Setup.hs script and does not actually link against it.

**Comment by maralorn** [comment] 2022-10-27 22:05
I hope this is fixed by fc886ef1fc62693029222d610388c6dfee5845c7, we will see how it goes.

**Comment by maralorn** [comment] 2022-10-27 22:26
Yeah, I am reasonably confident, that this specific issue is fixed on the haskell-updates branch now. Watch https://github.com/NixOS/nixpkgs/pull/198127 for when this fix hits master.

**Comment by DavSanchez** [comment] 2022-11-02 23:05
Hi @maralorn, @Et7f3 !

I can now build the two packages correctly without collisions. Thank you very much!

Unless we are waiting for the changes to move from unstable to stable, I guess we can close this.

**Closed** 2022-11-03 10:38 UTC
Labels: 0.kind: bug, 6.topic: haskell
