### ISSUE TITLE
Package request: spotify-player

### ISSUE THREAD

**Issue by Xyven1** [NixOS/nixpkgs#218195] opened 2023-02-25 09:30 UTC
**Project description**

A Spotify TUI with support for streaming direct from the terminal, or using Spotify Connect to control other players. Implements vim like bindings with for navigation, with helpful navigation hints when applicable, as well as some other quality of life features.

**Metadata**

* homepage URL: [https://github.com/aome510/spotify-player/](https://github.com/aome510/spotify-player/)
* source URL: [https://github.com/aome510/spotify-player/](https://github.com/aome510/spotify-player/)
* license: mit
* platforms: linux

**Comment by pinn3** [comment] 2023-02-25 14:46
Duplicate of https://github.com/NixOS/nixpkgs/issues/213176
It has already been packaged in https://github.com/NixOS/nixpkgs/pull/213596 and is available on the unstable channel

**Comment by Xyven1** [comment] 2023-02-26 06:52
Closed due to duplicate

**Closed** 2023-02-26 06:52 UTC
Labels: 0.kind: packaging request
