### ISSUE TITLE
certbot: ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#253852] opened 2023-09-07 12:43 UTC
### Describe the bug

When I try to request new certificates I get a `ModuleNotFoundError`:

### Steps To Reproduce

```
$ certbot certonly --manual -d "*.eicas.nl" -d eicas.nl --agree-tos --manual-public-ip-logging-ok --preferred-challenges dns-01 --server https://acme-v02.api.letsencrypt.org/directory --register-unsafely-without-email --rsa-key-size 4096 --config-dir config/ --work-dir work/ --logs-dir logs/
Traceback (most recent call last):
  File "/nix/store/s7apnbzmxsikd8bv3icfj6pkxw58dd4s-python3.11-certbot-2.4.0/bin/.certbot-wrapped", line 6, in <module>
    from certbot.main import main
  File "/nix/store/s7apnbzmxsikd8bv3icfj6pkxw58dd4s-python3.11-certbot-2.4.0/lib/python3.11/site-packages/certbot/main.py", line 6, in <module>
    from certbot._internal import main as internal_main
  File "/nix/store/s7apnbzmxsikd8bv3icfj6pkxw58dd4s-python3.11-certbot-2.4.0/lib/python3.11/site-packages/certbot/_internal/main.py", line 28, in <module>
    from certbot import configuration
  File "/nix/store/s7apnbzmxsikd8bv3icfj6pkxw58dd4s-python3.11-certbot-2.4.0/lib/python3.11/site-packages/certbot/configuration.py", line 11, in <module>
    from certbot import util
  File "/nix/store/s7apnbzmxsikd8bv3icfj6pkxw58dd4s-python3.11-certbot-2.4.0/lib/python3.11/site-packages/certbot/util.py", line 26, in <module>
    from certbot._internal import constants
  File "/nix/store/s7apnbzmxsikd8bv3icfj6pkxw58dd4s-python3.11-certbot-2.4.0/lib/python3.11/site-packages/certbot/_internal/constants.py", line 6, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

### Expected behavior

New certificates

### Notify maintainers

@domenkozar 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.1, NixOS, 23.11 (Tapir), 23.11.git.e841d8c7d41a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos-20.03pre194293.2436c27541b"`
 - nixpkgs: `/home/aengelen/nixpkgs`
```

on nixos-unstable 3c15feef7770eb5500a4b8792623e2d6f598c9c1

**Comment by con-f-use** [comment] 2023-09-08 19:00
duplicate of https://github.com/NixOS/nixpkgs/issues/253850 (by 2 minutes :grin:)

**Closed** 2023-09-09 11:46 UTC
Labels: 0.kind: bug
