### ISSUE TITLE
QuteBrowser - Core Dumped 

### ISSUE THREAD

**Issue by QJoly** [NixOS/nixpkgs#239895] opened 2023-06-26 09:18 UTC
### Describe the bug

```bash
[nix-shell:/tmp]$ qutebrowser
Gtk-Message: 11:12:57.199: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:12:57.200: Failed to load module "canberra-gtk-module"
11:12:57 WARNING: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
11:12:57 WARNING: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
11:12:57 CRITICAL: Could not initialize GLX
Fatal Python error: Aborted

Current thread 0x00007f5271a10740 (most recent call first):
  File "/nix/store/ai0m2b701gyk03k1fw037agbp7a1zmqd-qutebrowser-2.5.4/lib/python3.10/site-packages/qutebrowser/app.py", line 558 in __init__
  File "/nix/store/ai0m2b701gyk03k1fw037agbp7a1zmqd-qutebrowser-2.5.4/lib/python3.10/site-packages/qutebrowser/app.py", line 95 in run
  File "/nix/store/ai0m2b701gyk03k1fw037agbp7a1zmqd-qutebrowser-2.5.4/lib/python3.10/site-packages/qutebrowser/qutebrowser.py", line 245 in main
  File "/nix/store/ai0m2b701gyk03k1fw037agbp7a1zmqd-qutebrowser-2.5.4/bin/.qutebrowser-wrapped", line 34 in <module>

Extension modules: PyQt5.QtCore, PyQt5.QtGui, PyQt5.QtWidgets, markupsafe._speedups, yaml._yaml, PyQt5.QtNetwork, PyQt5.QtQml, PyQt5.QtSql, PyQt5.QtOpenGL, PyQt5.QtDBus, PyQt5.QtPrintSupport, PyQt5.QtWebEngineCore, PyQt5.QtWebChannel, PyQt5.QtWebEngineWidgets, PyQt5.QtWebEngine (total: 15)
Aborted (core dumped)
```

### Steps To Reproduce
1. Install or init a nix-shell with `qutebrowser` (`nix-shell -p qutebrowser`)
2. Run qutebrowser

### Expected behavior
The browser should open

### Notify maintainers

@jagajaga @rnhmjoj @ebzzry @dotlambda @nrdxp  

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.12-76060006-generic, Pop!_OS, 22.04 LTS, nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.0`
 - nixpkgs: `/home/kiko/.nix-defexpr/channels/nixpkgs`
```

**Comment by Artturin** [comment] 2023-06-28 23:01
Looks like a dupe of https://github.com/NixOS/nixpkgs/issues/9415

**Closed by Artturin** 2023-06-28 23:01 UTC
Labels: 0.kind: bug
