### ISSUE TITLE
nixos/etc: system.etc.overlay.enable make system unable to login after reboot

### ISSUE THREAD

**Issue by avnik** [NixOS/nixpkgs#337226] opened 2024-08-25 11:09 UTC
### Describe the bug

system.etc.overlay.enable make system unable to login after reboot

### Steps To Reproduce
1. Turn on overlays
```
system.etc.overlay = {
   enable = true;
   mutable = true;
};
```
2. switch, reboot
3. try to login

### Expected behavior
I expect, that I able to log in

### Additional context
I have `users.mutableUsers = true` if this matters.

### Notify maintainers
@nikstur 

### Metadata
My build based on top of 771c5644e82f5cfba6673771f7dab77c5c46995f from master branch

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nikstur** [comment] 2024-08-26 08:12
This is expected and somewhat intended. There is no mechanism to transfer state from the old /etc mechansim to the overlay. You can somewhat cricumvent this by setting your user password via `initialHashedPassword` or `hashedPassword` but this still won't necessarily transfer all possible state you have on /etc.

I currently do not plan to build such a mechanism either.

**Comment by avnik** [comment] 2024-08-26 13:21
@nikstur thanks for explanation. May be you denote it in docs/comments, that state not fully transferred?

Also -- would it enough to move passwd+shadow from current /etc to /.rw-etc/upper?

**Comment by nikstur** [comment] 2024-08-26 15:40
> would it enough to move passwd+shadow from current /etc to /.rw-etc/upper?

You can try that but it's hard to predict (even for me when I moved to the overlay etc) what state you have lying around that you need to transfer.

It's generally not a bad idea though to set you users passwords via `hashedPassword`.

**Comment by avnik** [comment] 2024-08-26 17:02
@nikstur Anyway, worth to mention this in docs

**Comment by nyabinary** [comment] 2024-09-02 19:00
Duplicate of #319524 ?

**Comment by nikstur** [comment] 2024-09-30 15:39
Closed as duplicate of https://github.com/NixOS/nixpkgs/issues/319524

**Closed by nikstur** 2024-09-30 15:39 UTC
Labels: 0.kind: bug
