### ISSUE TITLE
Cannot build gcc on OSX El Capitan

### ISSUE THREAD

**Issue by codygman** [NixOS/nixpkgs#14812] opened 2016-04-19 01:04 UTC
## Issue description

Using nix version 1.11.2 OSX 10.11.4 El Capitan with Apple LLVM version 7.0.2 (clang-700.1.81). I have this in my `/etc/nix/nix.conf`:

```
~ λ cat /etc/nix/nix.conf 
# chroot didn't work with 1.10, haven't tried with 1.12 yet
build-use-chroot = false
# Anytime a build tries to access a file it’s not allowed to, the file path and culprit will be logged to the system log, which you can view with Console.app. The filter Sandbox: will show you sandbox violations. 
darwin-log-sandbox-violations = true
```

Here is a full output log of me trying to install gcc5:

```shell
acbc32a98e5f:tmp cody$ nix-env -iA nixpkgs.gcc5
installing ‘gcc-wrapper-5.3.0’
these derivations will be built:
  /nix/store/w7dshcjfpmpa5cga6cchj4pf320plli2-gcc-5.3.0.drv
  /nix/store/2fg64qvxdw7cf21kkjcjyhnc41fxrg3r-gcc-wrapper-5.3.0.drv
building path(s) ‘/nix/store/7cd2j3h1i47fnxlycm0gkdla8ijz0ds2-gcc-5.3.0-info’, ‘/nix/store/fs1pa2bip048i353bc01k2xqvj9xdjr0-gcc-5.3.0’
$CPATH is `/nix/store/5fvfxwd069sgkr0rrqj032wqs0kms7i5-zlib-1.2.8/include'
$LIBRARY_PATH is `/nix/store/5fvfxwd069sgkr0rrqj032wqs0kms7i5-zlib-1.2.8/lib'
unpacking sources
unpacking source archive /nix/store/5g86gghmv2jzwp5rxqpizwhhnf0y0b5y-gcc-5.3.0.tar.bz2
source root is gcc-5.3.0
setting SOURCE_DATE_EPOCH to timestamp 1449235351 of file gcc-5.3.0/MD5SUMS
patching sources
applying patch /nix/store/k4xxs05a0y02m36sv2hdl0vrmzpk77y8-use-source-date-epoch.patch
patching file libcpp/macro.c
applying patch /nix/store/pz03lhak99nzyyni72m14zsjzfjvqvr8-no-sys-dirs.patch
patching file gcc/cppdefault.c
patching file gcc/gcc.c
Hunk #1 succeeded at 1261 (offset 99 lines).
fixing the `GLIBC_DYNAMIC_LINKER' and `UCLIBC_DYNAMIC_LINKER' macros...
... SNIP ...
clang-3.7: warning: argument unused during compilation: '-isystem /nix/store/nh9magpclysn06wnqik8amp40qy4mx6f-gettext-0.19.7/include'
clang-3.7: warning: argument unused during compilation: '-isystem /nix/store/zvyqwaqqd7mmpnpqbjxh42xpqb3gi9i0-gmp-5.1.3/include'
clang-3.7: warning: argument unused during compilation: '-isystem /nix/store/295xa0d6shds4x9dk09b4dhqhxj2b9d3-mpfr-3.1.3/include'
clang-3.7: warning: argument unused during compilation: '-isystem /nix/store/qd5hsfrhp39slj6524di1zvqcbv5w4i7-libmpc-1.0.3/include'
clang-3.7: warning: argument unused during compilation: '-isystem /nix/store/lrsk4iy91f9ff9ray6yb4d2n4sc2p62s-libelf-0.8.13/include'
clang-3.7: warning: argument unused during compilation: '-isystem /nix/store/zz8y762f28f23gsza4rk8sdmnj2vipqs-isl-0.14.1/include'
clang-3.7: warning: argument unused during compilation: '-isystem /nix/store/5fvfxwd069sgkr0rrqj032wqs0kms7i5-zlib-1.2.8/include'
clang-3.7: warning: argument unused during compilation: '-isystem /nix/store/93y7bp6x3fa691a96nyvb4kp0fdaa3rl-cctools-binutils-darwin/include'
clang-3.7: warning: argument unused during compilation: '-F/nix/store/y18ng60rsc8zvvdpk8k8z3i8c9nzhbcm-CF-osx-10.9.5/Library/Frameworks'
clang-3.7: warning: argument unused during compilation: '-isystem /nix/store/cbdrpqbhzs9lah33251r7600gzwdz00j-libc++-3.7.1/include'
# Early copyback; see "all" above for the rationale.  The
# early copy is necessary so that the gcc -B options find
rm -f libgcc.a
# the right startup files when linking shared libgcc.
/nix/store/m9m9ql2pbdhmbls584k1z571vr1ynfqi-bash-4.3-p42/bin/bash ../../../gcc-5.3.0/libgcc/../mkinstalldirs ../.././gcc
objects="_muldi3.o _negdi2.o _lshrdi3.o _ashldi3.o _ashrdi3.o _cmpdi2.o _ucmpdi2.o _clear_cache.o _trampoline.o __main.o _absvsi2.o _absvdi2.o _addvsi3.o _addvdi3.o _subvsi3.o _subvdi3.o _mulvsi3.o _mulvdi3.o _negvsi2.o _negvdi2.o _ctors.o _ffssi2.o _ffsdi2.o _clz.o _clzsi2.o _clzdi2.o _ctzsi2.o _ctzdi2.o _popcount_tab.o _popcountsi2.o _popcountdi2.o _paritysi2.o _paritydi2.o _powisf2.o _powidf2.o _powixf2.o _powitf2.o _mulsc3.o _muldc3.o _mulxc3.o _multc3.o _divsc3.o _divdc3.o _divxc3.o _divtc3.o _bswapsi2.o _bswapdi2.o _clrsbsi2.o _clrsbdi2.o _eprintf.o __gcc_bcmp.o _fixunssfsi.o _fixunsdfsi.o _fixunsxfsi.o _fixsfdi.o _fixdfdi.o _fixxfdi.o _fixunssfdi.o _fixunsdfdi.o _fixunsxfdi.o _floatdisf.o _floatdidf.o _floatdixf.o _floatundisf.o _floatundidf.o _floatundixf.o _fixsfti.o _fixdfti.o _fixxfti.o _fixtfti.o _fixunssfti.o _fixunsdfti.o _fixunsxfti.o _fixunstfti.o _floattisf.o _floattidf.o _floattixf.o _floattitf.o _floatuntisf.o _floatuntidf.o _floatuntixf.o _floatuntitf.o _divdi3.o _moddi3.o _udivdi3.o _umoddi3.o _udiv_w_sdiv.o _udivmoddi4.o darwin-64.o cpuinfo.o sfp-exceptions.o addtf3.o divtf3.o eqtf2.o getf2.o letf2.o multf3.o negtf2.o subtf3.o unordtf2.o fixtfsi.o fixunstfsi.o floatsitf.o floatunsitf.o fixtfdi.o fixunstfdi.o floatditf.o floatunditf.o fixtfti.o fixunstfti.o floattitf.o floatuntitf.o extendsftf2.o extenddftf2.o extendxftf2.o trunctfsf2.o trunctfdf2.o trunctfxf2.o enable-execute-stack.o";					\
if test -z "$objects"; then				\
  echo 'int __libgcc_eh_dummy;' > eh_dummy.c;		\
  /private/var/folders/d7/3941r8qj64b5y2h2yw3xnwrxmwd4h7/T/nix-build-gcc-5.3.0.drv-0/build/./gcc/xgcc -B/private/var/folders/d7/3941r8qj64b5y2h2yw3xnwrxmwd4h7/T/nix-build-gcc-5.3.0.drv-0/build/./gcc/ -F/System/Library/Frameworks    -F/System/Library/Frameworks -O2  -F/System/Library/Frameworks -DIN_GCC    -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-format -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -pipe -fno-common -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector   -pipe -fno-common -I. -I. -I../.././gcc -I../../../gcc-5.3.0/libgcc -I../../../gcc-5.3.0/libgcc/. -I../../../gcc-5.3.0/libgcc/../gcc -I../../../gcc-5.3.0/libgcc/../include  -DHAVE_CC_TLS -DUSE_EMUTLS -fvisibility=hidden -DHIDE_EXPORTS -c eh_dummy.c		\
     -o eh_dummy.o;				\
  objects=eh_dummy.o;				\
fi;							\
ar  rc libgcc.a $objects
parts="crt3.o crttms.o crttme.o crtprec32.o crtprec64.o crtprec80.o crtfastmath.o";					\
for file in $parts; do					\
  rm -f ../.././gcc/$file;		\
  /nix/store/k8k36jwwjaqnsikc8li4f3ys5n75x83r-coreutils-8.25/bin/install -c -m 644 $file ../.././gcc/;	\
  case $file in 					\
    *.a)						\
      ranlib ../.././gcc/$file ;;	\
  esac;							\
done
/nix/store/lq36kfy1njwdr52db69aa742isgw7lr7-cctools-port-877.5/bin/ranlib: file: libgcc.a(_trampoline.o) has no symbols
/nix/store/lq36kfy1njwdr52db69aa742isgw7lr7-cctools-port-877.5/bin/ranlib: file: libgcc.a(_ctors.o) has no symbols
/nix/store/lq36kfy1njwdr52db69aa742isgw7lr7-cctools-port-877.5/bin/ranlib: file: libgcc.a(_floatuntisf.o) has no symbols
/nix/store/lq36kfy1njwdr52db69aa742isgw7lr7-cctools-port-877.5/bin/ranlib: file: libgcc.a(_floatuntidf.o) has no symbols
/nix/store/lq36kfy1njwdr52db69aa742isgw7lr7-cctools-port-877.5/bin/ranlib: file: libgcc.a(_floatuntixf.o) has no symbols
/nix/store/lq36kfy1njwdr52db69aa742isgw7lr7-cctools-port-877.5/bin/ranlib: file: libgcc.a(_floatuntitf.o) has no symbols
ranlib libgcc.a
ranlib: file: libgcc.a(_trampoline.o) has no symbols
ranlib: file: libgcc.a(_ctors.o) has no symbols
ranlib: file: libgcc.a(_floatuntisf.o) has no symbols
ranlib: file: libgcc.a(_floatuntidf.o) has no symbols
ranlib: file: libgcc.a(_floatuntixf.o) has no symbols
ranlib: file: libgcc.a(_floatuntitf.o) has no symbols
# @multilib_flags@ is still needed because this may use
# /private/var/folders/d7/3941r8qj64b5y2h2yw3xnwrxmwd4h7/T/nix-build-gcc-5.3.0.drv-0/build/./gcc/xgcc -B/private/var/folders/d7/3941r8qj64b5y2h2yw3xnwrxmwd4h7/T/nix-build-gcc-5.3.0.drv-0/build/./gcc/ -F/System/Library/Frameworks    and -O2  -F/System/Library/Frameworks -DIN_GCC    -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-format -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -pipe -fno-common -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector  directly.
# @multilib_dir@ is not really necessary, but sometimes it has
# more uses than just a directory name.
/nix/store/m9m9ql2pbdhmbls584k1z571vr1ynfqi-bash-4.3-p42/bin/bash ../../../gcc-5.3.0/libgcc/../mkinstalldirs .
/private/var/folders/d7/3941r8qj64b5y2h2yw3xnwrxmwd4h7/T/nix-build-gcc-5.3.0.drv-0/build/./gcc/xgcc -B/private/var/folders/d7/3941r8qj64b5y2h2yw3xnwrxmwd4h7/T/nix-build-gcc-5.3.0.drv-0/build/./gcc/ -F/System/Library/Frameworks    -O2  -F/System/Library/Frameworks -DIN_GCC    -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-format -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -pipe -fno-common -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector  -dynamiclib -nodefaultlibs -install_name /nix/store/fs1pa2bip048i353bc01k2xqvj9xdjr0-gcc-5.3.0/lib/libgcc_s.1.dylib -single_module -o ./libgcc_s.dylib -Wl,-exported_symbols_list,libgcc.map -compatibility_version 1 -current_version 1.0 -F/System/Library/Frameworks -B./ _muldi3_s.o _negdi2_s.o _lshrdi3_s.o _ashldi3_s.o _ashrdi3_s.o _cmpdi2_s.o _ucmpdi2_s.o _clear_cache_s.o _trampoline_s.o __main_s.o _absvsi2_s.o _absvdi2_s.o _addvsi3_s.o _addvdi3_s.o _subvsi3_s.o _subvdi3_s.o _mulvsi3_s.o _mulvdi3_s.o _negvsi2_s.o _negvdi2_s.o _ctors_s.o _ffssi2_s.o _ffsdi2_s.o _clz_s.o _clzsi2_s.o _clzdi2_s.o _ctzsi2_s.o _ctzdi2_s.o _popcount_tab_s.o _popcountsi2_s.o _popcountdi2_s.o _paritysi2_s.o _paritydi2_s.o _powisf2_s.o _powidf2_s.o _powixf2_s.o _powitf2_s.o _mulsc3_s.o _muldc3_s.o _mulxc3_s.o _multc3_s.o _divsc3_s.o _divdc3_s.o _divxc3_s.o _divtc3_s.o _bswapsi2_s.o _bswapdi2_s.o _clrsbsi2_s.o _clrsbdi2_s.o _fixunssfsi_s.o _fixunsdfsi_s.o _fixunsxfsi_s.o _fixsfdi_s.o _fixdfdi_s.o _fixxfdi_s.o _fixunssfdi_s.o _fixunsdfdi_s.o _fixunsxfdi_s.o _floatdisf_s.o _floatdidf_s.o _floatdixf_s.o _floatundisf_s.o _floatundidf_s.o _floatundixf_s.o _fixsfti_s.o _fixdfti_s.o _fixxfti_s.o _fixtfti_s.o _fixunssfti_s.o _fixunsdfti_s.o _fixunsxfti_s.o _fixunstfti_s.o _floattisf_s.o _floattidf_s.o _floattixf_s.o _floattitf_s.o _floatuntisf_s.o _floatuntidf_s.o _floatuntixf_s.o _floatuntitf_s.o _divdi3_s.o _moddi3_s.o _udivdi3_s.o _umoddi3_s.o _udiv_w_sdiv_s.o _udivmoddi4_s.o darwin-64_s.o cpuinfo_s.o sfp-exceptions_s.o addtf3_s.o divtf3_s.o eqtf2_s.o getf2_s.o letf2_s.o multf3_s.o negtf2_s.o subtf3_s.o unordtf2_s.o fixtfsi_s.o fixunstfsi_s.o floatsitf_s.o floatunsitf_s.o fixtfdi_s.o fixunstfdi_s.o floatditf_s.o floatunditf_s.o fixtfti_s.o fixunstfti_s.o floattitf_s.o floatuntitf_s.o extendsftf2_s.o extenddftf2_s.o extendxftf2_s.o trunctfsf2_s.o trunctfdf2_s.o trunctfxf2_s.o enable-execute-stack_s.o unwind-dw2_s.o unwind-dw2-fde-darwin_s.o unwind-sjlj_s.o unwind-c_s.o emutls_s.o libgcc.a -lc
ld: library not found for -lc
collect2: error: ld returned 1 exit status
Makefile:947: recipe for target 'libgcc_s.dylib' failed
make[3]: *** [libgcc_s.dylib] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/private/var/folders/d7/3941r8qj64b5y2h2yw3xnwrxmwd4h7/T/nix-build-gcc-5.3.0.drv-0/build/x86_64-apple-darwin15.4.0/libgcc'
Makefile:14829: recipe for target 'all-stage1-target-libgcc' failed
make[2]: *** [all-stage1-target-libgcc] Error 2
make[2]: Leaving directory '/private/var/folders/d7/3941r8qj64b5y2h2yw3xnwrxmwd4h7/T/nix-build-gcc-5.3.0.drv-0/build'
Makefile:19039: recipe for target 'stage1-bubble' failed
make[1]: *** [stage1-bubble] Error 2
make[1]: Leaving directory '/private/var/folders/d7/3941r8qj64b5y2h2yw3xnwrxmwd4h7/T/nix-build-gcc-5.3.0.drv-0/build'
Makefile:19343: recipe for target 'bootstrap' failed
make: *** [bootstrap] Error 2
builder for ‘/nix/store/w7dshcjfpmpa5cga6cchj4pf320plli2-gcc-5.3.0.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/2fg64qvxdw7cf21kkjcjyhnc41fxrg3r-gcc-wrapper-5.3.0.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/2fg64qvxdw7cf21kkjcjyhnc41fxrg3r-gcc-wrapper-5.3.0.drv’ failed
```

### Steps to reproduce

```
nix-env -iA nixpkgs.gcc5
```

## Technical details

* System: OSX 10.11.4 El Capitan
* Nix version: 1.11.2
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by copumpkin** [comment] 2016-04-19 10:54
This is on my list of things to fix, but I'd love for someone else to get to it before I do. Keep in mind (for your own reference) that the Apple LLVM version is mostly irrelevant for Nix builds because we use our own compiler .

**Comment by retrry** [comment] 2016-04-21 15:23
Duplicate of https://github.com/NixOS/nixpkgs/issues/6148 ?

**Comment by squiddle** [comment] 2016-04-23 22:27
i have the same error on mavericks (10.9.5) using nix 1.11.2 and nixpkgs 16.09pre81657.9445bb2

```lang=text
ranlib: file: libgcc.a(_trampoline.o) has no symbols
ranlib: file: libgcc.a(_ctors.o) has no symbols
ranlib: file: libgcc.a(_floatuntisf.o) has no symbols
ranlib: file: libgcc.a(_floatuntidf.o) has no symbols
ranlib: file: libgcc.a(_floatuntixf.o) has no symbols
ranlib: file: libgcc.a(_floatuntitf.o) has no symbols
# @multilib_flags@ is still needed because this may use
# /private/var/folders/7c/h3n12hhx6sn6xd344nbx9rwm0000gn/T/nix-build-gcc-5.3.0.drv-2/build/./gcc/xgcc -B/private/var/folders/7c/h3n12hhx6sn6xd344nbx9rwm0000gn/T/nix-build-gcc-5.3.0.drv-2/build/./gcc/ -F/Applications/Xcode.app/Contents/
Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks    and -O2  -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks -DIN_GCC    -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-format -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -pipe -fno-common -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector  d
irectly.
# @multilib_dir@ is not really necessary, but sometimes it has
# more uses than just a directory name.
/nix/store/n3y3b7qm1bjb622wbn9sgmjghbl2lwsm-bash-4.3-p42/bin/bash ../../../gcc-5.3.0/libgcc/../mkinstalldirs .
/private/var/folders/7c/h3n12hhx6sn6xd344nbx9rwm0000gn/T/nix-build-gcc-5.3.0.drv-2/build/./gcc/xgcc -B/private/var/folders/7c/h3n12hhx6sn6xd344nbx9rwm0000gn/T/nix-build-gcc-5.3.0.drv-2/build/./gcc/ -F/Applications/Xcode.app/Contents/De
veloper/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks    -O2  -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks -DIN_GCC
    -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-format -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -pipe -fno-common -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector  -dynami
clib -nodefaultlibs -install_name /nix/store/jgsrjxfbri5fljwhp9isi8fvy5dhchy0-gcc-5.3.0/lib/libgcc_s.1.dylib -single_module -o ./libgcc_s.dylib -Wl,-exported_symbols_list,libgcc.map -compatibility_version 1 -current_version 1.0 -F/Appl
ications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks -B./ _muldi3_s.o _negdi2_s.o _lshrdi3_s.o _ashldi3_s.o _ashrdi3_s.o _cmpdi2_s.o _ucmpdi2_s.o _clear_cache_s.o _tra
mpoline_s.o __main_s.o _absvsi2_s.o _absvdi2_s.o _addvsi3_s.o _addvdi3_s.o _subvsi3_s.o _subvdi3_s.o _mulvsi3_s.o _mulvdi3_s.o _negvsi2_s.o _negvdi2_s.o _ctors_s.o _ffssi2_s.o _ffsdi2_s.o _clz_s.o _clzsi2_s.o _clzdi2_s.o _ctzsi2_s.o _c
tzdi2_s.o _popcount_tab_s.o _popcountsi2_s.o _popcountdi2_s.o _paritysi2_s.o _paritydi2_s.o _powisf2_s.o _powidf2_s.o _powixf2_s.o _powitf2_s.o _mulsc3_s.o _muldc3_s.o _mulxc3_s.o _multc3_s.o _divsc3_s.o _divdc3_s.o _divxc3_s.o _divtc3
_s.o _bswapsi2_s.o _bswapdi2_s.o _clrsbsi2_s.o _clrsbdi2_s.o _fixunssfsi_s.o _fixunsdfsi_s.o _fixunsxfsi_s.o _fixsfdi_s.o _fixdfdi_s.o _fixxfdi_s.o _fixunssfdi_s.o _fixunsdfdi_s.o _fixunsxfdi_s.o _floatdisf_s.o _floatdidf_s.o _floatdix
f_s.o _floatundisf_s.o _floatundidf_s.o _floatundixf_s.o _fixsfti_s.o _fixdfti_s.o _fixxfti_s.o _fixtfti_s.o _fixunssfti_s.o _fixunsdfti_s.o _fixunsxfti_s.o _fixunstfti_s.o _floattisf_s.o _floattidf_s.o _floattixf_s.o _floattitf_s.o _f
loatuntisf_s.o _floatuntidf_s.o _floatuntixf_s.o _floatuntitf_s.o _divdi3_s.o _moddi3_s.o _udivdi3_s.o _umoddi3_s.o _udiv_w_sdiv_s.o _udivmoddi4_s.o darwin-64_s.o cpuinfo_s.o sfp-exceptions_s.o addtf3_s.o divtf3_s.o eqtf2_s.o getf2_s.o
 letf2_s.o multf3_s.o negtf2_s.o subtf3_s.o unordtf2_s.o fixtfsi_s.o fixunstfsi_s.o floatsitf_s.o floatunsitf_s.o fixtfdi_s.o fixunstfdi_s.o floatditf_s.o floatunditf_s.o fixtfti_s.o fixunstfti_s.o floattitf_s.o floatuntitf_s.o extends
ftf2_s.o extenddftf2_s.o extendxftf2_s.o trunctfsf2_s.o trunctfdf2_s.o trunctfxf2_s.o enable-execute-stack_s.o unwind-dw2_s.o unwind-dw2-fde-darwin_s.o unwind-sjlj_s.o unwind-c_s.o emutls_s.o libgcc.a -lc
ld: library not found for -lc
collect2: error: ld returned 1 exit status
Makefile:947: recipe for target 'libgcc_s.dylib' failed
make[3]: *** [libgcc_s.dylib] Error 1
make[3]: Leaving directory '/private/var/folders/7c/h3n12hhx6sn6xd344nbx9rwm0000gn/T/nix-build-gcc-5.3.0.drv-2/build/x86_64-apple-darwin13.4.0/libgcc'
Makefile:14829: recipe for target 'all-stage1-target-libgcc' failed
make[2]: *** [all-stage1-target-libgcc] Error 2
```

**Comment by cablehead** [comment] 2016-05-13 18:54
I'm pretty sure I'm also seeing this.

I'm trying to install ragel on osx 10.9. It fails trying to build gcc-5.3.0

```
ld: library not found for -lc
collect2: error: ld returned 1 exit status
Makefile:947: recipe for target 'libgcc_s.dylib' failed
make[3]: *** [libgcc_s.dylib] Error 1
make[3]: Leaving directory '/private/var/folders/20/7hdvppyj0g73z01r5fqmvw7c0000gn/T/nix-build-gcc-5.3.0.drv-0/build/x86_64-apple-darwin13.4.0/libgcc'
Makefile:14829: recipe for target 'all-stage1-target-libgcc' failed
make[2]: *** [all-stage1-target-libgcc] Error 2
make[2]: Leaving directory '/private/var/folders/20/7hdvppyj0g73z01r5fqmvw7c0000gn/T/nix-build-gcc-5.3.0.drv-0/build'
Makefile:19039: recipe for target 'stage1-bubble' failed
make[1]: *** [stage1-bubble] Error 2
make[1]: Leaving directory '/private/var/folders/20/7hdvppyj0g73z01r5fqmvw7c0000gn/T/nix-build-gcc-5.3.0.drv-0/build'
Makefile:19343: recipe for target 'bootstrap' failed
make: *** [bootstrap] Error 2
builder for ‘/nix/store/4b1m5271ks3hzw9c7db2f195r93zsz6g-gcc-5.3.0.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/im9lrvna49ryyvcv6kd9m1pja825qp10-gcc-wrapper-5.3.0.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/365ndx3r37h03rivn1lilzfkb255wxnj-ragel-7.0.0.6.tar.gz’
cannot build derivation ‘/nix/store/575qh9752959j0sr06kcydriimxzxxrp-colm-0.13.0.3.drv’: 1 dependencies couldn't be built
killing process 50954
cannot build derivation ‘/nix/store/jcnnp4zmfsg9rpja33121df0sv4v2njy-ragel-7.0.0.6.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/jcnnp4zmfsg9rpja33121df0sv4v2njy-ragel-7.0.0.6.drv’ failed
```

@copumpkin where would you start to investigate this?

**Comment by copumpkin** [comment] 2016-05-13 20:20
Are you sure that colm actually needs gcc? Does it integrate into the compiler somehow?

**Comment by cablehead** [comment] 2016-05-13 20:54
Interesting. A quick bit of experimentation suggests it's not needed. Actually, ragel might not even require colm ...

**Comment by cablehead** [comment] 2016-05-13 21:24
Ok, it does look colm is needed, but if I remove gcc as a dependency for colm, ragel does build. When I then run this ragel under dtruss I don't see it `open` any files outside of `/nix/store`. But it does `stat64` a lot of system files. Does that sound normal? I'm really new to nix, obviously :)

I appreciate that this is now off topic for this issue.

**Comment by dredozubov** [comment] 2016-06-08 16:13
I had the same problem with this on OS X Yosemite https://github.com/NixOS/nixpkgs/issues/16047

**Comment by mitchty** [comment] 2016-06-09 02:34
@dredozubov Same here, not sure where or how to start debugging this bug.

**Closed** 2016-06-29 06:06 UTC
Labels: 6.topic: darwin
