### ISSUE TITLE
Fail to update `vim-plugins` using the `update.py` script

### ISSUE THREAD

**Issue by gvolpe** [NixOS/nixpkgs#92450] opened 2020-07-06 11:25 UTC
**Describe the bug**

It seems the [update.py](https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vim-plugins/update.py) does no longer work due to the Github API being rate-limited.

This is a truncated output I got when trying to run the script:

```
HTTP Error 429: too many requests, Retrying in 12 seconds...
HTTP Error 429: too many requests, Retrying in 12 seconds...
HTTP Error 429: too many requests, Retrying in 12 seconds...
HTTP Error 429: too many requests, Retrying in 12 seconds...
HTTP Error 429: too many requests, Retrying in 12 seconds...
HTTP Error 429: too many requests, Retrying in 12 seconds...
HTTP Error 429: too many requests, Retrying in 12 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
prefetch neoclide/coc-emmet
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
warning: unable to download 'https://github.com/neoclide/coc-emmet/archive/6e00ae0643b199ce0d037eae16affb36152ed9bd.tar.gz': Couldn't connect to server (7); retrying in 271 ms
downloading 'https://github.com/neoclide/coc-emmet/archive/6e00ae0643b199ce0d037eae16affb36152ed9bd.tar.gz'<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
warning: unable to download 'https://github.com/neoclide/coc-emmet/archive/6e00ae0643b199ce0d037eae16affb36152ed9bd.tar.gz': Couldn't connect to server (7); retrying in 579 ms
downloading 'https://github.com/neoclide/coc-emmet/archive/6e00ae0643b199ce0d037eae16affb36152ed9bd.tar.gz'<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
[0.0 MiB DL] downloading 'https://github.com/neoclide/coc-emmet/archive/6e00ae0643b199ce0d037eae16affb36152ed9bd.tar.gz'<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
unpacking...
[0.1 MiB DL]<urlopen error [Errno 113] No route to host>, Retrying in 6 seconds...
[0.1 MiB DL]
path is '/nix/store/kvwx584xd42jc75ly3bn1ljgcvp1268k-6e00ae0643b199ce0d037eae16affb36152ed9bd.tar.gz'
<urlopen error [Errno 113] No route to host>, Retrying in 6 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
<urlopen error [Errno 113] No route to host>, Retrying in 3 seconds...
````

Note: my Internet connection is fine and I can access Github without any issues.

**To Reproduce**

1. `cd pkgs/misc/vim-plugins/`
2. `./update.py`

**Expected behavior**

It updates the `generated.nix` file.

**Notify maintainers**

**Metadata**

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
- system: `"x86_64-linux"`
- host os: `Linux 5.4.46, NixOS, 20.09pre230335.9480bae3370 (Nightingale)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.3.6`
- channels(gvolpe): `"home-manager"`
- channels(root): `"nixos-20.09pre230335.9480bae3370"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by teto** [comment] 2020-07-06 12:16
duplicate of https://github.com/NixOS/nixpkgs/issues/91339

**Closed by teto** 2020-07-06 12:16 UTC
Labels: 0.kind: bug
