### ISSUE TITLE
Akonadi should include MySQL as BuildInput

### ISSUE THREAD

**Issue by silverhook** [NixOS/nixpkgs#1053] opened 2013-10-08 10:03 UTC
Akonadi service won't start even manually. It whines that it cannot connect to MySQL.

**Comment by matthiasbeyer** [comment] 2015-01-07 19:54
Hi guys. I have the described issues. (server->settings is a blank window, akonadi crashes my kde plasma desktop at login, etc). Shall I open another issue for this?

**Comment by vcunat** [comment] 2015-01-07 19:57
If it looks MySQL-related, then let's continue this issue.

**Comment by matthiasbeyer** [comment] 2015-01-07 20:02
I don't know whether it looks/is mysql-related, ... 

The KDE crash handler cannot tell me anything (no crash output). It appears right after login, plasma is already dead then.

**Comment by matthiasbeyer** [comment] 2015-01-08 15:15
Short update: I did some further investigation: Installing all KDE packages and then starting akonadi succeeds. I can use kmail, kontact and so on ... everything seems to work!

After I did the `nixos-rebuild switch`, everything works. But after a reboot, the Plasma Desktop crashes after login. So it _seems_ (to me) that the akonadi server wants to start which crashes the KDE Plasma desktop. I don't know why, though.

**Comment by silverhook** [comment] 2015-01-08 21:35
@matthiasbeyer, do you use the Eventlist plasmoid?

If so, that was a bug that I encountered in older versions of Eventlist.

**Comment by matthiasbeyer** [comment] 2015-01-09 14:09
@silverhook I don't even know what this is :smile:

**Comment by matthiasbeyer** [comment] 2015-01-09 15:58
The issue vanished after I added the unstable channel. Maybe this was actually the fix for this, maybe not. If you want, I can invastigate further...

**Comment by thorhop** [comment] 2015-02-04 07:47
So this issue keeps popping up on IRC. I didn't get this issue when installing kde4, but now that I'm running with **desktopManager.kde5.enable = true;** and  _mysql_ is not pulled as a dependency within that package set. This means any application trying to use _akonadi_ will fail outright. Shouldn't _akonadi_ be directly dependent upon _mysql_? This is assuming ofc that **pkgs/desktops/plasma-5.1** pulls _akonadi_ from **pkgs.desktops.kde-4.14.support.akonadi** as a dependency since the plasma repo for neither 5.1 or 5.2 contain an _akonadi_ package (and I couldn't find out what **KF5akonadi** was).

@ttuegel Thoughts?

**Comment by ttuegel** [comment] 2015-02-04 13:12
@thorhop KF5Akonadi refers to the KF5 port of Akonadi, which I have not yet put in Nixpkgs because it is neither stable nor required. Please try adding `pkgs.kde4.akonadi`, `pkgs.mysql`, and `pkgs.kdeApps.kdepim-runtime` to `environment.systemPackages` and report whether the issue persists or not. If the issue does persist, please specify exactly which command triggers the issue, so that I can reproduce.

**Comment by flat235** [comment] 2015-07-17 23:36
The issue is still there for me. unstable channel, kde4, all the kde stuff (except games and toys I think). The error is that the db isn't booting because default_home is set to /not/a/real/dir (says akonadi error log). To be honest I am not sure if it uses mysql or mariadb since I don't know how to find out / force one of them. Maybe the issue vanishes for people who setup a global database, thereby setting the default_home var for all dbs?

**Comment by wkennington** [comment] 2015-07-17 23:45
This is supposed to be addressed by #8494, but unfortunately this can't be merged until we have new nix features to support reference checking on multiple outputs.

**Comment by pwetzel** [comment] 2016-06-12 02:28
If this problem is just what @flat235 described (it was my problem), then this issue can be closed. It's fixed in master by #15421.

**Closed** 2016-06-13 18:59 UTC
Labels: 0.kind: bug, 6.topic: kde
