### ISSUE TITLE
ghcjs broken

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#17176] opened 2016-07-22 16:04 UTC
ghcjs has been broken from commit `bce5a51a9f33a16bf91e7d72a927c3382f333442` on x64 linux, with the following error:

```
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __1.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __2.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __3.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __4.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __5.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __6.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __7.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __8.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __9.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __10.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __11.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __12.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __13.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __14.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __15.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __16.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __17.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __18.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __19.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __20.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __21.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __22.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __23.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __24.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __25.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __26.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __27.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __28.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __29.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __30.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __31.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __32.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __33.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __34.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __35.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __36.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __37.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __38.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __39.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __40.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __41.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __42.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __43.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __44.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __45.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __46.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __47.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __48.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __49.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __50.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __51.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __52.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __53.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __54.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __55.o
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find /tmp/nix-build-generic-deriving-1.10.6.drv-0/generic-deriving-1.10.6/dist/build/Generics/Deriving/TH/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find _o_split/Pre4
/nix/store/84x0vldsif3v7i7c6i2ckfzp4jyg9bq9-binutils-2.26/bin/ld: cannot find __56.o
collect2: error: ld returned 1 exit status
'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9'9
builder for ‘/nix/store/n4kraf8ynkw7xkxxm1ygjvy25wmsiy0b-generic-deriving-1.10.6.drv’ failed with exit code 1
```

something concerning nodejs has been merged in the commit before.
cc @jwiegley @cstrahan

**Comment by rasendubi** [comment] 2016-07-22 18:31
Possible duplicate of https://github.com/NixOS/nixpkgs/issues/15916

**Comment by Ptival** [comment] 2016-07-22 18:58
My impression is that the package fails to build because the author of generic-deriving started naming one file `Pre4'9.hs` and the quote is possibly tripping up some tools down the line...

**Comment by Ptival** [comment] 2016-07-22 19:00
Is it possible to rename an issue? This issue is not ghcjs-specific, really it's about `haskell.packages.ghc7103.generic-deriving`.

**Comment by peti** [comment] 2016-07-22 19:35
Duplicate of https://github.com/NixOS/nixpkgs/issues/15916.

**Closed by peti** 2016-07-22 19:35 UTC
