### ISSUE TITLE
nix-shell: what is needed to get -p to work? Are there extra implicit packages?

### ISSUE THREAD

**Issue by fxfactorial** [NixOS/nixpkgs#12880] opened 2016-02-08 20:22 UTC
I am trying to built some C++ code that needs a C++ library, specifically Facebook's folly library. 
I'm still iterating so I don't need to add this in nixpkgs yet, so I am looking at the folly library and trying to use with with nix-shell like so:

```
nix-shell -p boost libevent stdenv folly google-gflags clang glog double_conversion gnumake41 libcxx libiberty clangStdenv
```

1) I had to provide many other packages other than folly, why doesn't nix-shell -p folly just full in all its dependencies? 
2) This craps out with 

```
/nix/store/ka8wj4qfsb6mkk6b58pgfvdyyfnry4wa-folly-0.57.0/include/folly/Portability.h:230:10: fatal error: 
      'bits/functexcept.h' file not found
#include <bits/functexcept.h>
         ^
1 error generated.
Makefile:13: recipe for target 'all' failed
make: *** [all] Error 1
``` 

Which makes no sense since its in the folly directory and I have used all the packages that the nix expression for folly said it wanted.

**Comment by domenkozar** [comment] 2016-02-09 04:36
Not sure about 2), but to get into the shell with builder parameters do `nix-shell -A folly`

**Comment by zimbatm** [comment] 2016-02-16 11:52
Closing for now. `nix-shell -A folly` works fine on master

**Comment by fxfactorial** [comment] 2016-02-16 16:11
@zimbatm this was not fine, I showed the exact problem and how it wasn't finding proper headers.

**Comment by zimbatm** [comment] 2016-02-16 17:36
@fxfactorial did you try with `nix-shell -A folly` ?

**Comment by grahamc** [comment] 2016-03-31 15:42
@fxfactorial Did you manage to solve your problem?

**Comment by fxfactorial** [comment] 2016-03-31 15:43
@grahamc sorry for delay, will report back about it end of day.

**Comment by rasendubi** [comment] 2016-09-15 00:58
Closing us there is still no response. @fxfactorial, please reopen if the issue is still present.

**Closed by rasendubi** 2016-09-15 00:58 UTC
