### ISSUE TITLE
freerdpUnstable build error

### ISSUE THREAD

**Issue by devhell** [NixOS/nixpkgs#7841] opened 2015-05-14 09:20 UTC
Currently this is happening when trying to build `freerdpUnstable`, I'm not sure what the reason is that it can't find `gstreamer` so I'm going to report it as an issue. There has been a beta9 update since then by the way. Thanks!

```
-- checking for module 'gstreamer-1.0'
--   package 'gstreamer-1.0' not found
-- checking for module 'gstreamer-base-1.0'
--   package 'gstreamer-base-1.0' not found
-- checking for module 'gstreamer-app-1.0'
--   package 'gstreamer-app-1.0' not found
-- checking for module 'gstreamer-audio-1.0'
--   package 'gstreamer-audio-1.0' not found
-- checking for module 'gstreamer-fft-1.0'
--   package 'gstreamer-fft-1.0' not found
-- checking for module 'gstreamer-pbutils-1.0'
--   package 'gstreamer-pbutils-1.0' not found
-- checking for module 'gstreamer-video-1.0'
--   package 'gstreamer-video-1.0' not found
-- Could NOT find GSTREAMER_1_0 (missing:  GSTREAMER_1_0_LIBRARIES GSTREAMER_1_0_INCLUDE_DIRS) 
CMake Warning at cmake/FindFeature.cmake:46 (message):
      feature GStreamer_1_0 was requested but could not be found! ON / FALSE
Call Stack (most recent call first):
  CMakeLists.txt:504 (find_feature)


-- Skipping optional feature JPEG for codec (use JPEG library)
--     Enable feature JPEG using "-DWITH_JPEG=ON"
-- Skipping optional feature GSM for codec (GSM audio codec library)
--     Enable feature GSM using "-DWITH_GSM=ON"
-- Skipping optional feature IPP for performance (Intel Integrated Performance Primitives library)
--     Enable feature IPP using "-DWITH_IPP=ON"
-- FreeRDP GIT
CMake Warning at winpr/CMakeLists.txt:82 (export):
  Cannot create package registry file:

    /homeless-shelter/.cmake/packages/winpr/a995248e89e614f61fc6d45f7162a6c5

  No such file or directory
```

**Comment by pSub** [comment] 2015-05-15 10:52
This build problem persists with version 1.2.0-beta1+android9. Not sure whats the cause. @wkennington do you have any ideas?

**Comment by vcunat** [comment] 2015-05-15 19:27
No gstreamer is passed to the package, and it never mattered in succeeding builds http://hydra.nixos.org/build/22026054/log/raw.

**Comment by vcunat** [comment] 2015-05-15 19:36
I think this is what stops it: ```CMake Error at channels/client/CMakeLists.txt:27 (list):
  list sub-command REMOVE_DUPLICATES requires list to be present.```

I skimmed what's changed between last success and first failure on Hydra, but I saw nothing related. https://github.com/NixOS/nixpkgs/compare/7021988dd1d7b5b4e2abf852fee872085ab892da...aef701babc933a2d8a4059029f81743ab4a555b5

**Comment by vcunat** [comment] 2015-05-15 20:15
Hmm, maybe the range returned by Hydra was wrong. I suspect cmake update is the cause, merged into master on 07338d13c97df.

**Comment by devhell** [comment] 2015-05-15 20:25
@vcunat Thanks for looking in to this by the way. :beers:

**Comment by vcunat** [comment] 2015-05-15 20:53
Confirmed that the mentioned merge commit contains the culprit.

**Closed** 2015-05-15 21:11 UTC
