### ISSUE TITLE
several packages are brokten due to Qt

### ISSUE THREAD

**Issue by rkoe** [NixOS/nixpkgs#78527] opened 2020-01-26 11:06 UTC
**Describe the bug**
There are currently many broken packages, due to the Qt-plugin/wrapper-problem:

```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
```

This affects
- aqemu
- boomerang
- (snowman; fixed by #78382)
- ... and probably *every Qt-using package* which was not adapted to the last Qt-wrapper-change

Can't this be fixed for *all* packages? It does not make much sense to open an issue for every affected package...
(And can such changes in the future please NOT break lots of packages?)

**Metadata**
- system: `"x86_64-linux"`
- host os: `Linux 4.19.93, NixOS, 19.09....
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.3`
- channels(root): `"nixos-19.09.1907.63a3564987d"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment] 2020-01-26 22:56
This is a duplicate of https://github.com/NixOS/nixpkgs/issues/65399.

> Can't this be fixed for all packages? It does not make much sense to open an issue for every affected package...
> (And can such changes in the future please NOT break lots of packages?)

The change wasn't actually meant to break a lot of package. It was actually because there was an overwhelming amount of packages in nixpkgs not being packaged properly per the Qt documentation.
It was discussed in the aforementioned thread how it could be fixed all at once, but I think people's time was just limited.

**Closed by worldofpeace** 2020-01-26 22:56 UTC
Labels: 0.kind: bug, 6.topic: qt/kde
