### ISSUE TITLE
nixos: "infinite recursion encountered" if config.checkMetaRecursively

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#193296] opened 2022-09-28 08:40 UTC
### Describe the bug

Since 6762de9a28e248f46bd0810e03c9666289de8e1d from #191171, evaluating my configuration of nixos-unstable is giving:

```
error: infinite recursion encountered

       at /home/aengelen/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:470:19:

          469|       inherit (validity) unfree broken unsupported insecure;
          470|       available = validity.valid != "no"
             |                   ^
          471|                && (if config.checkMetaRecursively or false
(use '--show-trace' to show detailed location information)
```

I'm still encountering it at the latest nixos-unstable, 7e52b35fe98481a279d89f9c145f8076d049d2b9

### Steps To Reproduce

I have not further narrowed down whether it is something specific to my configuration that triggers the issue, but here is the snippet from my configuration.nix that might be most relevant:

```
  nixpkgs.config.allowUnfree = false;
  nixpkgs.config.checkMetaRecursively = true;
  nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.g
etName pkg) [
    "zoom"
    # needed by zoom
    "faac"
    # printing
    "hplip"
    "canon-cups-ufr2"
  ];
```

Disabling `nixpkgs.config.checkMetaRecursively` makes the problem go away, but I kinda don't want to ;).

### Notify maintainers

@piegamesde @fricklerhandwerk 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.9, NixOS, 22.11 (Raccoon), 22.11.git.254a6aada9a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos-20.03pre194293.2436c27541b"`
 - nixpkgs: `/home/aengelen/nixpkgs`
```

**Comment by piegamesde** [comment] 2022-09-28 09:10
That's a weird one. Because I did not know about `config.checkMetaRecursively` until now, it is undocumented and used exactly once in the entire nixpkgs. The pull request I did enabled `config.checkMeta` by default, so it might be the cause nevertheless. Could you please confirm that the commit before works fine?

**Comment by raboof** [comment] 2022-09-28 09:16
> Have you explicitly set that option to true in your configuration?

Yes I did - TBH I don't remember what exactly prompted it, but it *sounds* like a good idea at least ;)

> Could you please confirm that the commit before works fine?

Confirmed

> Also, can you please try to minimize the package set which causes this? I think this is an issue with the check-meta evaluation, and it only surfaces through transitive dependencies.

Will-do (hopefully tonight)

**Comment by fricklerhandwerk** [comment] 2022-09-28 13:04
I'm not maintaining this, just making sure documentation is readable and self-consistent. I do not vouch for its correctness (this should be maintainers' responsibility).

**Comment by piegamesde** [comment] 2022-09-29 20:38
I notice that the failure is only reproducible when both `checkMeta` and `checkMetaRecursively` are enabled. I guess this is because the dependency tree has some cyclic dependency somehow, but due to laziness it is only exposed through the combination of both options. Since the only relevant #191171 changed the default of `checkMeta`, I have the strong supposition that both options never truly worked together.

@raboof how did you find that `checkMetaRecursively` option, and what exactly do you need it for? As far as I can see, it is used nowhere in nixpkgs and also undocumented. I am therefore inclined to remove it.

**Comment by arcnmx** [comment] 2022-09-30 19:12
#191171 indeed [broke my whole CI system implementation](https://github.com/arcnmx/nixexprs/actions) with "infinite recursion" errors yeah :disappointed: 

> As far as I can see, it is used nowhere in nixpkgs and also undocumented. I am therefore inclined to remove it.

Please don't without at least offering a way to get equivalent functionality. You can find some discussion on [an old related issue](https://github.com/NixOS/nixpkgs/pull/33057#issuecomment-357531426) if you want some context. It's my opinion that `checkMetaRecursively` should be the default behaviour, and I believe it only isn't due to performance reasons. I do also consider it a bit of a longstanding nixpkgs bug that this isn't the default behaviour, because if a package transiently depends on something unfree or `meta.broken`, evaluating it will `throw` an error even though `package.meta.available == true`. If this is removed, `builtins.tryEval` may be the only remaining option and I consider that to be a poor hacky solution.

**Comment by piegamesde** [comment] 2022-09-30 20:46
Thanks @arcnmx for the input. I think I'm slowly starting to better understand the situation.

- `checkMeta` defaulted to false, which I considered a long-standing issue and thus changed it.
- `checkMetaRecursively` defaults to false, and we probably want to have that changed too
- Due to the default values, both have almost never been tested together, and thus never worked. When enabling both, it produces some infinitive recursion error on some packages. I tried debugging it but then ran [into segfaults](https://github.com/NixOS/nix/issues/6772) 😒
- My tolerance of undocumented options is limited. If we want to keep it in, it must be properly documented.

**Comment by piegamesde** [comment] 2022-09-30 22:48
Okay, I finally understand the interaction between both options:

- `available` forces the evaluation of `checkMeta`, and if `checkMetaRecursively` then recursively for all dependencies
- `checkMeta` forces the evaluation of `available` in order to check its type
- There are packages like `libsysprof-capture` which have the following line `meta = sysprof.meta // {`. With the usual laziness this is not a problem, but the recursive forcing of attributes results in an infinite recursion:
  - libsysprof-capture.meta requires libsysprof.meta
  - libsysprof.meta.available (forced through `checkMeta`) goes through all dependences (because of `checkMetaRecursive`), including `libsysprof-capture`
  - Infinite recursion on `libsysprof-capture.meta`
- There is no good way to forbid such recursive trickeries in nixpkgs, therefore `checkMeta` and `checkMetaRecursively` are mutually incompatible.

However, it is possible to build a custom check that does the same recursive decent externally:

```nix
with (import <nixpkgs> { config = { checkMetaRecursively = false; checkMeta = true; }; });
let
  mapFun = attrs: {
    key = builtins.toString (
      if attrs == null then
        "<null>"
      else if builtins.isPath attrs then
        attrs
      else
        attrs.drvPath);
    drv = attrs;
    available = if attrs == null || builtins.isPath attrs then true else attrs.meta.available;
  };
  result = builtins.genericClosure {
    startSet = [
      # Put your inputs here
      # having multiple inputs is more efficient than calling `genericClosure` multiple times with a single argument. You can also call with a single derivation that has all your inputs as dependencies
      (mapFun sysprof)
      (mapFun chromium)
      (mapFun texlive.combined.scheme-full)
    ];
    operator = { key, drv, available }: let
      references = drv.nativeBuildInputs or [] ++ drv.buildInputs or [] ++ drv.propagatedNativeBuildInputs or [] ++ drv.propagatedBuildInputs or [];
    in
      builtins.map mapFun references;
  };
in
  lib.pipe result [
    (builtins.map ({available, ...}: available))
    (builtins.foldl' (a: b: a && b) true)
  ]
```

Please let me know if this suits your use case.

**Comment by arcnmx** [comment] 2022-10-08 19:17
> Due to the default values, both have almost never been tested together, and thus never worked. When enabling both, it produces some infinitive recursion error on some packages.

For now, the quickest fix might be to make the two options mutually exclusive; it could disable `checkMeta` if recursive is on, or assert/throw if they're both on?

> My tolerance of undocumented options is limited. If we want to keep it in, it must be properly documented.

I'd be happy to see it documented, regardless of whether it becomes enabled by default or not!

> There is no good way to forbid such recursive trickeries in nixpkgs, therefore checkMeta and checkMetaRecursively are mutually incompatible.

This sounds wrong, I don't see why this can't be fixed. There can't be a true recursive dependency here between the two derivations. A simple fix to this seems like it would just be to ignore `attrs.meta.available`, so it can't be set via `mkDerivation { meta.available = x; }` (it already can't be; if that's **really** what you wanted, you need to use `addPassthru` or something) - it doesn't even really need to be type-checked if it's only set by `mkDerivation`.

> There are packages like libsysprof-capture which have the following line `meta = sysprof.meta // {`.

You could even consider this to be poor form, and encourage the following instead:

```nix
mkDerivation {
  meta = {
    inherit (sysprof.meta) license platforms etc;
  };
```

> However, it is possible to build a custom check that does the same recursive decent externally:

While it can be done, it feels like a bit of a hack? Efficiency also seems a bit complicated compared to the free thunks you get from having `meta.available`

also the concerns stated in #194058 seem relevant to mention here.

**Comment by piegamesde** [comment] 2022-10-08 19:37
I think that creating a custom helper function that recursively checks all `available` attributes of a derivation would be the cleanest solution. `builtins.genericClosure` is pretty efficient because the code walking the tree and checking for cycles is written in C++ (people have already build the same thing in Nix, and it was both ugly and slow). As a bonus, that solution would make the `checkMetaRecursively` option obsolete (I generally consider less options and thus less complexity as a win).

I am not convinced of your approach of simply removing the attribute from the type check, because it might clash with future attempts to tighten the type checking of `meta` (e.g. using a module system).

**Comment by arcnmx** [comment] 2022-10-08 19:48
> I am not convinced of your approach of simply removing the attribute from the type check, because it might clash with future attempts to tighten the type checking of meta (e.g. using a module system).

While I agree that this feature could use more discussion about a future design, I see nothing wrong with fixing an obvious bug in the existing logic. I still do think that recursive checking should be default behaviour, and probably tied to `checkMeta` rather than being a separate option to begin with?

The thing to realise here is that setting `meta.available = anything;` is nonsensical; it gets `//` overwritten by `mkDerivation`, so the value is effectively ignored. So...
1. Type-checking a value that never sees the light of day outside of the internal check is silly.
2. If anything, there should be a warning that `meta.available` was set to anything, since doing so is ineffectual and probably a mistake.
3. This just ties back into the idea that the `meta = x.meta // { ... }` pattern is lazy and assigns values that one doesn't even intend to set - we're just lucky that they usually get ignored/overwritten

**Comment by piegamesde** [comment] 2022-10-08 20:02
Regarding the part about documenting the option: what would be any use cases where one would want this default to false? I'd really like to see that option gone.

Also, how about having `available` and `availableRecurseDependencies` (name suggestions welcome)?

**Comment by arcnmx** [comment] 2022-10-08 20:23
> Regarding the part about documenting the option: what would be any use cases where one would want this default to false? I'd really like to see that option gone.

This somewhat comes down to [this sentiment](https://github.com/NixOS/nixpkgs/pull/194058#issuecomment-1264634611) in that if the performance impact is determined to be an unreasonable burden, you keep the option off by default but have a `do-extra-checks` option that is typically only enabled at CI / PR review time. I however don't feel that we need both `checkMeta` and `checkMetaRecursive` in this scenario, they could just be merged into one option - even if meta type-checking is switched on by default again, the option can remain to toggle the extra CI checks (recursive behaviour) without being explicitly named `Recursive`.

But if there's no meaningful impact, there's no reason to expose an option to switch it off!

> Also, how about having `available` and `availableRecurseDependencies` (name suggestions welcome)?

Maybe? I might suggest `valid` (non-recursive) and `available`, which are already used in `checkMeta`.

But the more I think about it, what purpose does non-recursive availability even provide? For example, some JDK stuff uses `enableJavaFX ? openjfx.meta.available` to determine whether it can use JFX, and IIRC this check only worked properly when `checkMetaRecursive` is enabled - it produced a broken JDK on some platforms when it was off (which it is by default). The obvious use of `available` is to check whether a derivation can be evaluated and is expected to build properly - why would you ever want to subject yourself to the false positives that crop up from the check not being recursive?

Yes, non-recursive `available` is obviously more efficient, but if you actually use it for anything, you're making assumptions that you really shouldn't be making. We should probably just scrutinize how and when availability is used rather than worrying about whether it's maximally efficient.
From this perspective, `checkMetaRecursive = false;` is an optimization that makes `meta.available` unreliable and useless (and therefore shouldn't be optional), while `checkMeta = true;` is a superficial/sanity type check that is optional to enable when you know that all of its inputs are well-formed.

**Comment by piegamesde** [comment] 2022-10-09 10:59
I did a few greps in order to get a feeling for how this attribute is used, and was greeted with the usual chaotic inconsistency:

- `withValgrind ? lib.meta.availableOn stdenv.hostPlatform valgrind`
- `withValgrind ? lib.meta.availableOn stdenv.hostPlatform valgrind-light && !valgrind-light.meta.broken`
- `valgrindSupport ? !stdenv.isDarwin && lib.meta.availableOn stdenv.hostPlatform valgrind`
- `withValgrind ? valgrind-light.meta.available`

Then I looked at the `lib.meta.availableOn` implementation and it should be equivalent to the output of `checkMeta` but (a) only checking for platforms and not for other evaluation issues and (b) without the possibility to opt-in via configuration. It kind of feels like `lib.meta.availableOn` should replaced in favor of `meta.available`, but I'm not ready to jump into that rabbit hole yet …

But given what I've seen so far, I am in favor of always doing the recursive check in `meta.available` and removing the configuration option. I am not worried about big performance hits, but a quick benchmark should be performed nevertheless for good measure and to appease potential critics.

The `valid` attribute from `checkMeta` is currently not exposed, this could be added however. Note that `checkMeta` currently produces a Yes/No/Warn tri-state, we only want to expose a boolean though (Warn => true).

Regarding the recursion check, instead of removing the attribute from the set I suggest removing the type check: `available = bool // { check = _: true; };`. This should have the same effect as your solution right now (the available attribute not being evaluated prematurely), but should be more compatible with potential future type checking improvements.

**Closed** 2022-10-16 13:33 UTC
Labels: 0.kind: bug, 6.topic: nixos
