### ISSUE TITLE
Package request: ultralytics

### ISSUE THREAD

**Issue by GardenerGeralt** [NixOS/nixpkgs#342313] opened 2024-09-16 13:43 UTC
**Project description**

A python package that provides cutting-edge machine learning algorithms for computer vision.

**Metadata**

* homepage URL: https://www.ultralytics.com/ & https://pypi.org/project/ultralytics/
* source URL: https://github.com/ultralytics/ultralytics
* license: AGPL-3.0
* platforms: any platform with python/pip

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Aleksanaa** [comment] 2024-12-06 12:33
Duplicate of https://github.com/NixOS/nixpkgs/issues/308154

**Closed by Aleksanaa** 2024-12-06 12:33 UTC
Labels: 6.topic: python, 0.kind: packaging request
