### ISSUE TITLE
`python312Packages.triton` build failure on x86_64-linux as of `13bb3040`

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#350117] opened 2024-10-21 00:28 UTC
## Issue description
Build of `python312Packages.triton` failed on x86_64-linux as of 13bb3040aebb54bb116f2450eba78afa6ecaaffb. This is currently breaking `python3Packages.torch-bin`.

```
error: builder for '/nix/store/p49mxpdb58j2vzjr9f4kk1jhjv8h7yxm-python3.12-triton-3.1.0.drv' failed with exit code 1;
       last 10 log lines:
       > checking for references to /build/ in /nix/store/3pgvjqnl5c5wxzxppy8p3xpcp2kb3j79-python3.12-triton-3.1.0...
       > patching script interpreter paths in /nix/store/3pgvjqnl5c5wxzxppy8p3xpcp2kb3j79-python3.12-triton-3.1.0
       > shrinking RPATHs of ELF executables and libraries in /nix/store/5pi24hh71yafcxdvfzggviw018j2yshl-python3.12-triton-3.1.0-dist
       > checking for references to /build/ in /nix/store/5pi24hh71yafcxdvfzggviw018j2yshl-python3.12-triton-3.1.0-dist...
       > patching script interpreter paths in /nix/store/5pi24hh71yafcxdvfzggviw018j2yshl-python3.12-triton-3.1.0-dist
       > Rewriting #!/nix/store/wfbjq35kxs6x83c3ncpfxdyl5gbhdx4h-python3-3.12.6/bin/python3.12 to #!/nix/store/wfbjq35kxs6x83c3ncpfxdyl5gbhdx4h-python3-3.12.6
       > wrapping `/nix/store/3pgvjqnl5c5wxzxppy8p3xpcp2kb3j79-python3.12-triton-3.1.0/bin/proton'...
       > Rewriting #!/nix/store/wfbjq35kxs6x83c3ncpfxdyl5gbhdx4h-python3-3.12.6/bin/python3.12 to #!/nix/store/wfbjq35kxs6x83c3ncpfxdyl5gbhdx4h-python3-3.12.6
       > wrapping `/nix/store/3pgvjqnl5c5wxzxppy8p3xpcp2kb3j79-python3.12-triton-3.1.0/bin/proton-viewer'...
       > chmod: cannot access '/nix/store/3pgvjqnl5c5wxzxppy8p3xpcp2kb3j79-python3.12-triton-3.1.0/lib/python3.12/site-packages/triton/third_party/cuda/bin/ptxas': No such file or directory
       For full logs, run 'nix log /nix/store/p49mxpdb58j2vzjr9f4kk1jhjv8h7yxm-python3.12-triton-3.1.0.drv'.
error: 1 dependencies of derivation '/nix/store/d61p8x24ddvj42bac0sqcxxqylpvrcsc-python3.12-torch-2.4.1.drv' failed to build
```

[full build log](https://github.com/samuela/nixpkgs-upkeep/actions/runs/11430817371)

python3Packages.torch-bin maintainers cc: @junjihashimoto
python312Packages.triton maintainers cc: @SomeoneSerge @Madouura @derdennisop
Other cc: n/a

### Steps to reproduce
1. Checkout nixpkgs at commit 13bb3040aebb54bb116f2450eba78afa6ecaaffb
2. Run `nix-build -A python312Packages.triton`

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.0-1025-azure, Ubuntu, 22.04.5 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.16.1`
 - nixpkgs: `/nix/store/h5x7dvrz3gg20m1bh4dx333g1vvqsagp-source`
```

Contents of `~/.config/nixpkgs/config.nix`:
```
{ allowUnfree = true; cudaSupport = true; cudaCapabilities = ["8.0"]; }
```

## Misc.
This issue was automatically generated by [nixpkgs-upkeep](https://github.com/samuela/nixpkgs-upkeep).
- [CI workflow](https://github.com/samuela/nixpkgs-upkeep/actions/runs/11430817371) that created this issue.
- Internal tags: 6836712381962779645 -3613853086660875134

**Comment by SomeoneSerge** [comment] 2024-10-21 01:09
```
❯ nom build -f "<nixpkgs>" -I "nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz" --arg config "{ config.cudaSupport = true; config.allowUnfree = true; }" --print-out-paths python3Packages.triton
/nix/store/m68xm8gyf282m79hf1phl6z4n6bz4xgd-python3.12-triton-3.1.0
```

**Comment by samuela** [comment] 2024-10-21 01:26
Huh, this doesn't look like a timeout or OOM error -- I wonder what's wrong. I can close if it's not a concern for others.

**Comment by DerDennisOP** [comment] 2024-10-21 08:03
`stderr: chmod: cannot access '/nix/store/3pgvjqnl5c5wxzxppy8p3xpcp2kb3j79-python3.12-triton-3.1.0/lib/python3.12/site-packages/triton/third_party/cuda/bin/ptxas': No such file or directory`

yeah this error is the cause of it. @SomeoneSerge do you know how we can fix it?

**Comment by GnRlLeclerc** [comment] 2024-10-26 09:57
I have the same issue with nixpkgs at revision 2768c7d042a37de65bb1b5b3268fc987e534c49d.

I tried inspecting the `torch-bin` derivation works, but I do not understand how `triton` is resolved in it:
Building python triton succeeds (version 3.1.0):
```
nix build nixpkgs#python312Packages.triton
# Produces /nix/store/m68xm8gyf282m79hf1phl6z4n6bz4xgd-python3.12-triton-3.1.0
```

However building `torch-bin` fails with the same error as above:
```
NIXPKGS_ALLOW_UNFREE=1 nix build nixpkgs#python312Packages.torch-bin --impure
# The error comes from derivation /nix/store/p49mxpdb58j2vzjr9f4kk1jhjv8h7yxm-python3.12-triton-3.1.0.drv
```

I am a nixpkgs beginner, I don't really know how `torch-bin` alters the `triton` build config, here are pastebins of `nix derivation show` for these 2 derivations which seem to show some differences when diffing the 2:
Working [`/nix/store/m68xm8gyf282m79hf1phl6z4n6bz4xgd-python3.12-triton-3.1.0`](https://pastebin.com/2cWVvEJP)
Broken [`/nix/store/p49mxpdb58j2vzjr9f4kk1jhjv8h7yxm-python3.12-triton-3.1.0`](https://pastebin.com/b5Nr40GB)

**Comment by graham33** [comment] 2024-10-27 11:24
I took a quick look at this. `torch-bin` by default is using `python312Packages.triton-bin` for its `triton` dependency, rather than the from-source `python312Packages.triton` (see here: https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/python-packages.nix#L15803). If you build `python312Packages.triton-bin` you'll see the same error.

I pushed a potential fix here: https://github.com/NixOS/nixpkgs/pull/351627 but I expect it's not correct as-is (see PR comments).

**Comment by SomeoneSerge** [comment] 2024-10-27 11:37
Thanks for picking up the triton-bin issue.
The original issue (about the source build of triton) doesn't seem to be reproducible or maybe was specific to that concrete revision, I don't think it's worth the time to find out which

```
❯ git pull 
...
Updating 6422c786dd51..23664a7358c5                                                                                                                            
Fast-forward 
...
❯ nom build .#python3Packages.triton --print-out-paths 
Finished at 11:30:20 after 0s
/nix/store/m68xm8gyf282m79hf1phl6z4n6bz4xgd-python3.12-triton-3.1.0
❯ nom build -f "<nixpkgs>" --arg config "{ cudaSupport = true; allowUnfree = true; }" python3Packages.triton --print-out-paths 
Finished at 11:31:22 after 0s
/nix/store/0acx76pmmk9zlrp9dfcsrir7q0gv6i6b-python3.12-triton-2.1.0
❯ git show HEAD
commit 23664a7358c599dd4f975f16cea0865bf423e83d (HEAD -> master, nixos/master, nixos/HEAD)
Merge: 3de6ab6d99de 2f5d739cfeb6
Author: Stig <stig@stig.io>
Date:   Sun Oct 27 10:41:34 2024 +0000

    perlPackages.AppSqitch: 1.4.0 -> 1.4.1 (#351171)
```

**Closed by SomeoneSerge** 2024-10-27 11:37 UTC
Labels: 6.topic: python, 0.kind: build failure
