### ISSUE TITLE
"nixos-rebuild boot" is broken in master: cryptsetup: error while loading shared libraries: libssl.so.1.0.0:

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#42301] opened 2018-06-20 14:19 UTC
In current versions of `master` @ d91c70171fb96ee42f10b2d447430b8a9cc576a8, attempts to build a system fail:

~~~
$ nix-build --no-out-link nixos -A system 
[...]
testing patched programs...
hello world
238
mdadm - v4.0 - 2017-01-09
/nix/store/lg53x3h518y1mn1k1l73agnkq77vc7pi-extra-utils/bin/cryptsetup: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
builder for '/nix/store/2bsasb69iigc1pqii597x4vx73b5qh67-extra-utils.drv' failed with exit code 127
cannot build derivation '/nix/store/gv7wldlvj7d485422j473avqiqpan1lv-stage-1-init.sh.drv': 1 dependencies couldn't be built
~~~

**Comment by dezgeg** [comment] 2018-06-20 14:47
This is a duplicate of #42276 (for which I have a fix soon).

**Closed by dezgeg** 2018-06-20 14:47 UTC
Labels: 0.kind: regression, 1.severity: blocker, 6.topic: nixos
