### ISSUE TITLE
Unable to install KDE global themes 

### ISSUE THREAD

**Issue by water-sucks** [NixOS/nixpkgs#106602] opened 2020-12-10 21:30 UTC
**Describe the bug**

Installing any KDE global theme results in an error with lots of random unintelligible characters, but usually starts with: `Installation of /tmp/uazsso-Lavender-Global.zip failed: Could not install dependency: 'kns://colorschemes.knsrc/api.kde-look.org/1457362`. Installing anything else, like for example, Plasma Themes or Icons, installs perfectly fine.

**To Reproduce**
1. ... Open KDE System Settings.
2. ... Click on Global Theme -> Get New Global Themes
3. ... Attempt to install any global theme presented.

**Expected behavior**

I expect a theme to be installed and shown in the Global Themes selection for me to apply.

**Screenshots**

![FailedThemeInstallation-1](https://user-images.githubusercontent.com/68445574/101832023-9ff08e00-3aeb-11eb-87c4-d8cd3293ae74.png)
![FailedThemeInstallation-2](https://user-images.githubusercontent.com/68445574/101832026-a0892480-3aeb-11eb-90fb-c6b6c40f453d.png)

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.81, NixOS, 20.09.2190.78dc359abf8 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"unstable-21.03pre257780.e9158eca70a, nixos-20.09.2190.78dc359abf8"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by dalvescb** [comment] 2020-12-18 00:20
Also experiencing this 
 - system `x86_64-linux`
 - host-os `NixOS 20.09.2238.b94726217f7 (Nightingale)`
 - multi-user?: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `nixos https://nixos.org/channels/nixos-20.09`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
 
In case anyone's wondering, a workaround is just downloading the .tar.gz for the theme directly from the KDE store and extracting it to ~/.local/share/plasma/look-and-feel/ (and I'm guessing I should write a nix derivation for this once I stop being a nix noob)

**Comment by peterhoeg** [comment] 2021-10-21 07:48
The issue is that KDE tries to install to the nix store, which obviously fails. 

Same as https://github.com/NixOS/nixpkgs/issues/98997 and https://github.com/NixOS/nixpkgs/issues/99071

**Comment by pjones** [comment] 2022-05-16 23:24
@peterhoeg Why does KDE try to write into the Nix store?

On other distros the user won't have write access to the global themes directory and KDE should fallback to `~/.local`.  But it's not doing that on NixOS.  Does it have something to do with the way we package it?

**Comment by milahu** [comment] 2022-06-12 21:30
duplicate of #76615

**Closed** 2022-10-27 21:06 UTC
Labels: 0.kind: bug, 6.topic: qt/kde
