### ISSUE TITLE
emacsWithPackages broken in master

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#27873] opened 2017-08-02 14:59 UTC
The `emacsWithPackages` function stopped working in recent versions of `master`. To reproduce, run `emacs` inside of

    nix-shell -p 'emacsWithPackages (p: with p.melpaPackages; [bbdb use-package])'

and try to load `use-package`. The result on my system at be0071c2d7053 is

    Symbol's function definition is void: use-package

..., but in earlier versions of Nixpkgs this used to work fine.

Ping: @mdorman

**Comment by peti** [comment] 2017-08-02 17:23
`emacsWithPackages` works fine in Nixpkgs 0854c856783b1f7a84f9307ef0c812d27f43b518.

**Comment by mdorman** [comment] 2017-08-02 20:58
@peti so you mean it fixed itself (since 0854c85 is a child of be0071c)?

**Comment by mdorman** [comment] 2017-08-02 21:12
So I reverted the most recent set of package updates, and it's still broken.  So someone broke something along the way.  I'll attempt a little bisecting to fix stuff.

**Comment by mdorman** [comment] 2017-08-02 21:26
Somewhat unsurprisingly (to me, at least), it appears the breakage is somewhere in the giant wad of changes that was recently merged as 740d76371e; 2a48a62b9c, which immediately precedes it, works fine.

@FRidh, you did that merge, do you have any thoughts?

**Comment by matthewbauer** [comment] 2017-08-02 21:52
I bet it has to do with the findInputs probably ea7d13cf1acc60999a442b46b279460928165140

**Comment by mdorman** [comment] 2017-08-02 22:00
@matthewbauer thanks for the suggestion---I'll factor that into my bisecting.

**Comment by bendlas** [comment] 2017-08-03 12:56
@mdorman anything new? Would it make sense for me to dig into this as well?

**Comment by mdorman** [comment] 2017-08-03 13:11
@bendlas the bisecting script that I started last night---after trying a straight revert of ea7d13c didn't apply cleanly, I figured I'd just let git do the work---was faulty; I've fixed it, but there's a lot of rebuilding going on, so it's slow; so if you have specific ideas for how to attack the problem, please go ahead, otherwise hopefully the bisect will have finished by this evening.

**Comment by Ericson2314** [comment] 2017-08-03 16:10
That specific commit should only improve things.

**Comment by mdorman** [comment] 2017-08-03 19:04
ea9af6e3bd appears to be the merge that causes the problem.

**Comment by mdorman** [comment] 2017-08-03 19:05
Something fell over in my bisect, so I had to restart it to try and narrow down among the commits in the merge.  May take a while longer.

**Comment by mdorman** [comment] 2017-08-03 20:07
bisect identifies 8d76effc178747f0c8f456fe619c1b014736a6af as the first bad commit. @Ericson2314, do you have any thoughts?

**Comment by mdorman** [comment] 2017-08-03 20:08
For the record:
```
git bisect start

git bisect bad 740d76371e6c1c76bae4801fc5b736a796c1ebbe
740d76371e bad Merge commit 'ba68231273bea4cba01413fd2a0e56d68db9234c' into HEAD

git bisect good 2a48a62b9cfe99140bfa9d45fca960be848f87fe
2a48a62b9c good sensu: 0.29.0 -> 1.0.2

git bisect bad 4b14212914faac8a4d0dd3a6e0ff66cf4a1e1484
4b14212914 bad nixos/tests/keymap: use SLIM theme from nixos/tests/slim

git bisect bad ae26f291bcb6da0910fd3de47ff970e696f2c155
ae26f291bc bad systemd: 233 -> 234

git bisect bad 674c82739c1287da6f2446095f221d8da394788d
674c82739c bad Merge #26613: init and use dns-root-data

git bisect bad ea9af6e3bd6aaaf27524ccbe195980887532d67e
ea9af6e3bd bad Merge pull request #27336 from obsidiansystems/stdenv-setup-cleanup

git bisect bad ea9af6e3bd6aaaf27524ccbe195980887532d67e
ea9af6e3bd bad Merge pull request #27336 from obsidiansystems/stdenv-setup-cleanup

git bisect good a889454869e4f7d5ba6067ebcc0ba7fcd26e4417
a889454869 good Merge pull request #27284 from obsidiansystems/prop-lines

git bisect good a889454869e4f7d5ba6067ebcc0ba7fcd26e4417
a889454869 good Merge pull request #27284 from obsidiansystems/prop-lines

git bisect bad 273a4c1c78d9e0b3aa852f197ce9ecc0e63ce42b
273a4c1c78 bad stdenv-setup: Combine [[ .. ]] && [[ .. ]] into one [[ .. && .. ]]

git bisect bad 5d4efb2c816d2143f29cad8153faad1686557b2a
5d4efb2c81 bad stdenv-setup: Misc improvements as directed by ShellCheck

git bisect bad 8d76effc178747f0c8f456fe619c1b014736a6af
8d76effc17 bad stdenv-setup: Make the package accumulators associative arrays instead of strings
```

**Comment by Ericson2314** [comment] 2017-08-03 20:19
Ah https://github.com/NixOS/nixpkgs/commit/8d76effc178747f0c8f456fe619c1b014736a6af#diff-a070e31e9cecdb4638e536bb958ca1dfR89 was in error; It  should be `-z`. But this was also fixed on master.

**Comment by mdorman** [comment] 2017-08-03 20:42
@Ericson2314 Well apparently there is _something_ else, because this is the change that appears to have broken things.

**Comment by Ericson2314** [comment] 2017-08-03 20:57
@mdorman Err sadly when something is broken and then fixed, bisecting is hard because correctness is not monotonic. Can you try doing a build at that commit with the `-n` changed to `-z`? That will rule that out.

**Comment by mdorman** [comment] 2017-08-03 21:24
@Ericson2314 So I'm assuming you're talking about the specific `-n` that you pointed to above---the one `pkgs/development/interpreters/python/wrap.sh`, in which case that fails to build gmp.

**Comment by mdorman** [comment] 2017-08-03 21:53
@Ericson2314 OK, the problem is that the observable behavior of `findInputs` was changed.

I applied the following instrumentation to the emacs wrapper generator:

```
diff --git a/pkgs/build-support/emacs/wrapper.nix b/pkgs/build-support/emacs/wrapper.nix
index e41b1fd6a2..8f6fa5afad 100644
--- a/pkgs/build-support/emacs/wrapper.nix
+++ b/pkgs/build-support/emacs/wrapper.nix
@@ -60,7 +60,9 @@ stdenv.mkDerivation {
 
      local requires
      for pkg in $explicitRequires; do
+       echo "Finding inputs for [$pkg]"
        findInputs $pkg requires propagated-user-env-packages
+       echo "- Required packages [$requires]"
      done
      # requires now holds all requested packages and their transitive dependencies
 
@@ -80,7 +82,10 @@ stdenv.mkDerivation {
        linkPath "$1" "share/emacs/site-lisp" "share/emacs/site-lisp"
      }
 
+     echo "Required packages [$requires]"
+
      for pkg in $requires; do
+       echo "Linking package [$pkg]"
        linkEmacsPackage $pkg
      done
 ```

I then used `nix-shell` to invoke the same expression on the last working commit 2a48a62b9c, and `HEAD`.  The working version outputs:

```
bash-4.4$ nix-shell --packages 'emacsWithPackages (p: with p.melpaStablePackages; [bind-key use-package])'
these derivations will be built:
  /nix/store/n09d070d5d5shw9jn7jrnynpprhx9ijq-emacs-packages-deps.drv
  /nix/store/lsmr9dfr80s49c1c7qwhwqnhc5x82sd6-emacs-with-packages-25.2.drv
building path(s) ‘/nix/store/yffan83hgpv3m464zalaqrk47aqgffrr-emacs-packages-deps’
Finding inputs for [/nix/store/xxd31fwgzhflwdwnjwa0sfpfd56hqa6i-emacs-bind-key-2.3]
- Required packages [ /nix/store/xxd31fwgzhflwdwnjwa0sfpfd56hqa6i-emacs-bind-key-2.3 ]
Finding inputs for [/nix/store/hswyv4hiyx19dzj9mj23qbyny3q9hrvp-emacs-use-package-2.3]
- Required packages [ /nix/store/xxd31fwgzhflwdwnjwa0sfpfd56hqa6i-emacs-bind-key-2.3  /nix/store/hswyv4hiyx19dzj9mj23qbyny3q9hrvp-emacs-use-package-2.3  /nix/store/a7di8ys1wwz2v1fj5l6j1lsmyhczvrnb-emacs-diminish-0.45 ]
Required packages [ /nix/store/xxd31fwgzhflwdwnjwa0sfpfd56hqa6i-emacs-bind-key-2.3  /nix/store/hswyv4hiyx19dzj9mj23qbyny3q9hrvp-emacs-use-package-2.3  /nix/store/a7di8ys1wwz2v1fj5l6j1lsmyhczvrnb-emacs-diminish-0.45 ]
Linking package [/nix/store/xxd31fwgzhflwdwnjwa0sfpfd56hqa6i-emacs-bind-key-2.3]
Linking package [/nix/store/hswyv4hiyx19dzj9mj23qbyny3q9hrvp-emacs-use-package-2.3]
Linking package [/nix/store/a7di8ys1wwz2v1fj5l6j1lsmyhczvrnb-emacs-diminish-0.45]
building path(s) ‘/nix/store/n11g1indmbfd1w4b8s66bh8qxpq2yrqn-emacs-with-packages-25.2’
installing
```

In a version with your changes, we instead get the output:

```
bash-4.4$ nix-shell --packages 'emacsWithPackages (p: with p.melpaStablePackages; [bind-key use-package])'
these derivations will be built:
  /nix/store/36av16yvi71vd6a0v5bxa845rwa9v4im-emacs-packages-deps.drv
  /nix/store/as3bswfxqvhx9fkgyamgizkcpx5wl9fw-emacs-with-packages-25.2.drv
building path(s) ‘/nix/store/i63ki8a3hw0p0a4r2crj53kal1qf2lgj-emacs-packages-deps’
Finding inputs for [/nix/store/2wnx9x9h29kwzgiwqh8bycwz3b6lavps-emacs-bind-key-2.3]
- Required packages [/nix/store/2wnx9x9h29kwzgiwqh8bycwz3b6lavps-emacs-bind-key-2.3]
Finding inputs for [/nix/store/fpwrs2dnc594hzgs3fksv75x5kj6fha0-emacs-use-package-2.3]
- Required packages [/nix/store/2wnx9x9h29kwzgiwqh8bycwz3b6lavps-emacs-bind-key-2.3]
Required packages [/nix/store/2wnx9x9h29kwzgiwqh8bycwz3b6lavps-emacs-bind-key-2.3]
Linking package [/nix/store/2wnx9x9h29kwzgiwqh8bycwz3b6lavps-emacs-bind-key-2.3]
building path(s) ‘/nix/store/r7laf4b5dri357a8qswwl4pxj52jhll0-emacs-with-packages-25.2’
installing
```

Clearly the list of required packages isn't getting modified.
```
```

**Comment by Ericson2314** [comment] 2017-08-03 22:57
Eesh!

**Comment by Ericson2314** [comment] 2017-08-03 22:57
I think I need like a meta-issue of fallout from the changes that anyone can edit

**Comment by matthewbauer** [comment] 2017-08-03 22:59
Nice work @mdorman! Luckily findInputs isn't used too much in nixpkgs:

https://github.com/NixOS/nixpkgs/search?q=findinputs

**Comment by Ericson2314** [comment] 2017-08-03 23:02
Ah. It is using propagated user env packages. I'll think about it / `set -x` should reveal the full story.

**Closed** 2017-08-04 14:07 UTC
Labels: 0.kind: bug
