### ISSUE TITLE
Package request: ALVR

### ISSUE THREAD

**Issue by whitfieldts** [NixOS/nixpkgs#278019] opened 2024-01-01 06:55 UTC
**Project description**

Allows for running wireless PC VR from a linux computer to a Meta Quest headset.

**Metadata**

* homepage URL: https://github.com/alvr-org/ALVR/wiki/Installation-guide
* source URL: https://github.com/alvr-org/ALVR
* license: MIT
* platforms: Linux, Windows, MacOS

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by justinas** [comment] 2024-01-01 16:29
Duplicate of https://github.com/NixOS/nixpkgs/issues/238102. There's also some recent progress in https://github.com/NixOS/nixpkgs/pull/275926.

**Closed by justinas** 2024-01-01 16:29 UTC
Labels: 0.kind: packaging request
