### ISSUE TITLE
Build failure: citrix_workspace

### ISSUE THREAD

**Issue by GsakuL** [NixOS/nixpkgs#348868] opened 2024-10-15 19:49 UTC
### Steps To Reproduce

1. use `citrix_workspace` (i.e. the "main"/"latest" one)
2. update channel `nixos-unstable` to rev `a3c0b3b21515f74fd2665903d4ce6bc4dc81c77c`
3. `sudo nixos-rebuild build --flake ~/mynix`

### Build log
`nix log  /nix/store/8h191qnqkib7zdmp26q5lhyghf2lxq3x-citrix-workspace-24.5.0.76.drv`
https://gist.github.com/GsakuL/4d67b55bc23428899aa9f08ec5575c64

error at the bottom:
```txt
...

auto-patchelf: 1 dependencies could not be satisfied
error: auto-patchelf could not satisfy dependency libogg.so.0 wanted by /nix/store/ms9j3ik2yfvdbxw1hqzii9a7azvnlg6d-citrix-workspace-24.5.0.76/opt/citrix-icaclient/VORBIS.DLL
auto-patchelf failed to find all the required dependencies.
Add the missing dependencies to --libs or use `--ignore-missing="foo.so.1 bar.so etc.so"`.
```

### Additional context

maybe see also #348866

also, is it normal, that the Citrix version reports itself as `24.5.0.76` even tho in nixpkgs it is `24.2.0.65`?
### Notify maintainers

@michaeladler

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.54, NixOS, 24.11 (Vicuna), 24.11.20241006.c31898a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/rs4fjbnw4qx7ns2hzzrz2iz52va7vs5z-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by l0b0** [comment] 2024-10-17 01:19
FYI, `pkgs.citrix_workspace_23_11_0` on current unstable is also broken.

**Comment by michaeladler** [comment] 2024-10-17 08:51
Yeah, I think commit 04bf3a5a24294b530a985b95ec8aa984c7d339ae by @doronbehar broke it (switching to cmake-based build).

**Comment by westernmagic** [comment] 2024-10-18 09:32
Adding `-DBUILD_SHARED_LIBS=ON` to `libogg`'s `cmakeFlags` fixes things (by making the `.so` libs build again.

This should probably be fixed in `libogg` - do you agree @ehmry? 

Here is an overlay that makes things compile again:
```
final: prev: {
  # https://github.com/NixOS/nixpkgs/issues/348868
  citrix_workspace = prev.citrix_workspace.override {
    libvorbis = final.libvorbis.override {
      libogg = final.libogg.overrideAttrs (prevAttrs: {
        cmakeFlags = (if prevAttrs ? cmakeFlags then prevAttrs.cmakeFlags else []) ++ [
          (final.lib.cmakeBool "BUILD_SHARED_LIBS" true)
        ];
      });
    };
  };
}
```

**Comment by 0-a-9-5-6** [comment] 2024-10-18 10:09
> if prevAttrs ? cmakeFlags then prevAttrs.cmakeFlags else []

By the way, you can write this more simply as `prevAttrs.cmakeFlags or []`
https://nix.dev/manual/nix/2.18/language/operators#attribute-selection

But yeah I agree that fixing `libogg` itself is the way to move forward

**Comment by doronbehar** [comment] 2024-10-18 10:17
> Adding `-DBUILD_SHARED_LIBS=ON` to `libogg`'s `cmakeFlags` fixes things (by making the `.so` libs build again.
> 
> This should probably be fixed in `libogg` - do you agree @ehmry?

Yes I agree. Sorry about this regression.

**Comment by doronbehar** [comment] 2024-10-18 10:17
Will create a PR targetting staging shortly.

**Comment by doronbehar** [comment] 2024-10-18 10:22
https://github.com/NixOS/nixpkgs/pull/349503

**Comment by l0b0** [comment] 2024-10-21 00:15
> Here is an overlay that makes things compile again:
> 
> ```
> final: prev: {
>   […]
> }
> ```

I got an infinite recursion error when using that (`libvorbis = final.libvorbis` seems to be the issue), but [this](https://gitlab.com/engmark/root/-/merge_requests/672/diffs) worked:

```
{
  nixpkgs.overlays = [
    (final: prev: {
      libvorbis = prev.libvorbis.override {
        libogg = final.libogg.overrideAttrs (prevAttrs: {
          cmakeFlags = (prevAttrs.cmakeFlags or [ ]) ++ [ (final.lib.cmakeBool "BUILD_SHARED_LIBS" true) ];
        });
      };
    })
  ];
}
```

(Well, it's still building, but it hasn't failed yet :grin:.)

**Comment by 0-a-9-5-6** [comment] 2024-10-22 13:21
@l0b0 Of course as written that would cause infrec, writing something like `a = final.a.override...` would inherently be infrec. The infrec was because of not including the previous line:

```
citrix_workspace = prev.citrix_workspace.override {
```

**Comment by duckunix** [comment] 2024-10-28 19:35
@0-a-9-5-6 Being a relatively new NixOS user, how would I use your code above?  In the same module where I include the citrix_workspace, just add it?

Thanks!

**Comment by 0-a-9-5-6** [comment] 2024-11-04 03:25
_Replace_ `pkgs.citrix_workspace` with `(pkgs.citrix_workspace.override ...)`. (I'll not rewrite it out the `...` again.)

**Comment by duckunix** [comment] 2024-11-04 04:46
Thank you for taking time out to help me.  I was able to copy your code, and it is working for me now.  Thanks, again!

**Comment by doronbehar** [comment] 2024-11-22 08:36
The PR that fixed this has reached `nixos-unstable`:

https://nixpk.gs/pr-tracker.html?pr=349503

**Closed by doronbehar** 2024-11-22 08:36 UTC
Labels: 0.kind: build failure

**Comment by andrew-isakov** [comment] 2025-11-20 07:49
https://github.com/NixOS/nixpkgs/issues/348868#issuecomment-2429273888
same error...

<img width="571" height="187" alt="Image" src="https://github.com/user-attachments/assets/27274822-7912-4872-97f0-f6a421c5dbb4" />

https://github.com/NixOS/nixpkgs/issues/348868#issuecomment-2493184870
504
