### ISSUE TITLE
Java: multiple variations to install zulu on darwin and linux

### ISSUE THREAD

**Issue by freezeboy** [NixOS/nixpkgs#56549] opened 2019-02-28 23:14 UTC
## Issue description

There are different ways to install java (zulu edition) on darwin. one is common with linux (but doesn't compile currently due to a link to `alsaLib`): `pkgs/development/compilers/zulu` and another one that is specific to `darwin`: `pkgs/development/compilers/openjdk/darwin`.

I see that the recipes are quite different, but I don't get the point :

- Different versions are available (8 and 11 or 8 and 10 !?)
- As they are different, it is hard to switch between the variants (#23557)

Could we (I volunteer to help on that) try to merge or refactor the packages to avoid duplication, and maybe have an upgrade process that deals with the different variants?

Thanks

CC maintainers / authors: @nequissimus @fpletz @edwtjo @jerith666 @matthewbauer 

### Steps to reproduce

nix run nixpkgs.zulu8
nix run nixpkgs.zulu
nix run nixpkgs.openjdk (on darwin)

**Comment by matthewbauer** [comment] 2019-03-01 02:08
Yeah - zulu should be the prebuilt version of openjdk. We should probably get rid of the openjdk/darwin/ as that is confusing to have.

**Comment by jerith666** [comment] 2019-03-02 15:25
It'd be great to get openjdk to build or darwin.

I'm also interested in looking into sharing / reusing the https://adoptopenjdk.net/ binaries.

**Comment by austinbutler** [comment] 2020-09-15 22:56
Currently on unstable, `zulu8` refused to install, while `jdk` seems to work fine.

```
❯ nix-shell -p zulu8
error: Package ‘libpciaccess-0.16’ in /nix/store/5ihk0s5j4jlixwn282lpv9561q8xhcs4-nixpkgs-21.03pre243353.6d4b93323e7/nixpkgs/pkgs/servers/x11/xorg/default.nix:1135 is not supported on ‘x86_64-darwin’, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

Yet `jdk` seem to in fact _be_ Zulu...

```
[nix-shell:~]$ java -version
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (Zulu 8.36.0.1-CA-macosx) (build 1.8.0_202-b05)
OpenJDK 64-Bit Server VM (Zulu 8.36.0.1-CA-macosx) (build 25.202-b05, mixed mode)
```

**Comment by freezeboy** [comment] 2021-03-18 14:35
I don't have a mac anymore so I could not work on it since then

**Comment by ggPeti** [comment] 2021-08-15 03:38
https://gitlab.com/ggpeti/buildEnv-sscce is a minimal reproduction of this issue. Seems like buildEnv fails when one of the paths to link is a symlink to begin with. Run `nix build gitlab:ggpeti/buildenv-sscce` to see the output of the example.

The reason it surfaces with the jdk package is probably that its source contains a similarly symlinked directory - man.

**Comment by tomodachi94** [comment] 2024-11-13 19:08
It looks like this was solved by https://github.com/NixOS/nixpkgs/pull/259825. Closing, feel free to reopen this if I am wrong.

**Closed by tomodachi94** 2024-11-13 19:08 UTC
Labels: 6.topic: darwin, 6.topic: java
