### ISSUE TITLE
unable to update xfce due to gst-plugins-good not building

### ISSUE THREAD

**Issue by andrewrk** [NixOS/nixpkgs#18304] opened 2016-09-04 21:29 UTC
## Issue description

When doing `nixos-rebuild switch --upgrade`:

```
substitute(): file '/nix/store/96ixnlzkjdn6ncgjkh8d9mkv0ijs57jx-gst-plugins-good-0.10.31/lib/gstreamer-0.10/libgstaasink.la' does not exist
builder for ‘/nix/store/63mvcwjphm4h3jbbzsafprwplza9ggq0-gst-plugins-good-0.10.31.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/gsi6ngr0c6fjqc81a51rsa75yp3gnr4v-xfce4-mixer-4.10.0.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/0kyg5n4rsdkmd5brd2lq7nsl661j0v6d-xfce4-panel-4.12.0.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/pyic7sg0q81gww167v4q4r6rd6x971xa-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/nmy0i9jbyhl5j8m4fwv2wfdifr45hanz-xfce4-session-4.12.1.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/kbj5wwq2aq1zs689s1isidpddzlks98v-nixos-system-xps-16.09pre90254.6b20d5b.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/kbj5wwq2aq1zs689s1isidpddzlks98v-nixos-system-xps-16.09pre90254.6b20d5b.drv’ failed
```

### Steps to reproduce

Relevant config:

```
services.xserver.desktopManager.xfce.enable = true;
```

## Technical details

* System: NixOS: `16.09pre87524.2ef1c6b (Flounder)`
* Nix version: nix-env (Nix) 1.11.2

**Comment by abbradar** [comment] 2016-09-05 00:48
Do you have `nixpkgs.config.pulseaudio` enabled? This should then be fixed by c9bcec2e880897505dae6972bc32f8f3cfe2d3d7.

**Comment by andrewrk** [comment] 2016-09-05 04:42
> Do you have nixpkgs.config.pulseaudio enabled?

Yes.

I wanted to wait until I could test if this worked before posting a comment, but somehow this time chromium-browser had to be built locally instead of using the cached one from hydra, and it's been going for 6 hours now. Looks like I got past the gst-plugins package though; thank you for your suggestion.

**Closed** 2016-09-05 14:51 UTC

**Comment by cleverca22** [comment] 2016-09-07 04:29
related, a packageOverride on xfce.xfce4mixer doesnt have any impact on xfce panel, i need to override each thing that depends on mixer

**Comment by vcunat** [comment] 2016-09-11 12:44
@cleverca22: I suspect that's caused by https://github.com/NixOS/nixpkgs/issues/18316.
