### ISSUE TITLE
Can't install zlib

### ISSUE THREAD

**Issue by chamini2** [NixOS/nixpkgs#9654] opened 2015-09-04 06:19 UTC
I just did a clean install of Nix and when trying to install packages, it always fails trying to install `zlib`:

For python:

> unpacking source archive /nix/store/a048k7r603jq7sphp907zja27gpyzbx1-zlib-1.2.8.tar.gz
> source root is zlib-1.2.8
> patching sources
> configuring
> configure flags: --prefix=/nix/store/ry1xfxg5rm02caqzszjidqrgvzhp75hg-zlib-1.2.8 --shared
> Checking for shared library support...
> Building shared library libz.1.2.8.dylib with gcc.
> Checking for off64_t... No.
> Checking for fseeko... Yes.
> Checking for strerror... Yes.
> Checking for unistd.h... Yes.
> Checking for stdarg.h... Yes.
> Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
> Checking for vsnprintf() in stdio.h... Yes.
> Checking for return value of vsnprintf()... Yes.
> Checking for attribute(visibility) support... Yes.
> building
> make flags: SHELL=/bin/bash
> gcc -O3  -DHAVE_HIDDEN -I. -c -o example.o test/example.c
> gcc -O3  -DHAVE_HIDDEN   -c -o adler32.o adler32.c
> gcc -O3  -DHAVE_HIDDEN   -c -o crc32.o crc32.c
> gcc -O3  -DHAVE_HIDDEN   -c -o deflate.o deflate.c
> gcc -O3  -DHAVE_HIDDEN   -c -o infback.o infback.c
> gcc -O3  -DHAVE_HIDDEN   -c -o inffast.o inffast.c
> gcc -O3  -DHAVE_HIDDEN   -c -o inflate.o inflate.c
> gcc -O3  -DHAVE_HIDDEN   -c -o inftrees.o inftrees.c
> gcc -O3  -DHAVE_HIDDEN   -c -o trees.o trees.c
> gcc -O3  -DHAVE_HIDDEN   -c -o zutil.o zutil.c
> gcc -O3  -DHAVE_HIDDEN   -c -o compress.o compress.c
> gcc -O3  -DHAVE_HIDDEN   -c -o uncompr.o uncompr.c
> gcc -O3  -DHAVE_HIDDEN   -c -o gzclose.o gzclose.c
> gcc -O3  -DHAVE_HIDDEN   -c -o gzlib.o gzlib.c
> gcc -O3  -DHAVE_HIDDEN   -c -o gzread.o gzread.c
> gcc -O3  -DHAVE_HIDDEN   -c -o gzwrite.o gzwrite.c
> ar -r libz.a adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o zutil.o compress.o uncompr.o gzclose.o gzlib.o gzread.o gzwrite.o
> ar: creating archive libz.a
> gcc -O3  -DHAVE_HIDDEN -o example example.o -L. libz.a
> gcc -O3  -DHAVE_HIDDEN -I. -c -o minigzip.o test/minigzip.c
> gcc -O3  -DHAVE_HIDDEN -o minigzip minigzip.o -L. libz.a
> gcc -O3  -fPIC -DHAVE_HIDDEN -DPIC -c -o objs/adler32.o adler32.c
> gcc -O3  -fPIC -DHAVE_HIDDEN -DPIC -c -o objs/crc32.o crc32.c
> gcc -O3  -fPIC -DHAVE_HIDDEN -DPIC -c -o objs/deflate.o deflate.c
> gcc -O3  -fPIC -DHAVE_HIDDEN -DPIC -c -o objs/infback.o infback.c
> gcc -O3  -fPIC -DHAVE_HIDDEN -DPIC -c -o objs/inffast.o inffast.c
> gcc -O3  -fPIC -DHAVE_HIDDEN -DPIC -c -o objs/inflate.o inflate.c
> gcc -O3  -fPIC -DHAVE_HIDDEN -DPIC -c -o objs/inftrees.o inftrees.c
> gcc -O3  -fPIC -DHAVE_HIDDEN -DPIC -c -o objs/trees.o trees.c
> gcc -O3  -fPIC -DHAVE_HIDDEN -DPIC -c -o objs/zutil.o zutil.c
> gcc -O3  -fPIC -DHAVE_HIDDEN -DPIC -c -o objs/compress.o compress.c
> gcc -O3  -fPIC -DHAVE_HIDDEN -DPIC -c -o objs/uncompr.o uncompr.c
> gcc -O3  -fPIC -DHAVE_HIDDEN -DPIC -c -o objs/gzclose.o gzclose.c
> gcc -O3  -fPIC -DHAVE_HIDDEN -DPIC -c -o objs/gzlib.o gzlib.c
> gcc -O3  -fPIC -DHAVE_HIDDEN -DPIC -c -o objs/gzread.o gzread.c
> gcc -O3  -fPIC -DHAVE_HIDDEN -DPIC -c -o objs/gzwrite.o gzwrite.c
> gcc -dynamiclib -install_name /nix/store/ry1xfxg5rm02caqzszjidqrgvzhp75hg-zlib-1.2.8/lib/libz.1.dylib -compatibility_version 1 -current_version 1.2.8 -O3  -fPIC -DHAVE_HIDDEN -o libz.1.2.8.dylib adler32.lo crc32.lo deflate.lo infback.lo inffast.lo inflate.lo inftrees.lo trees.lo zutil.lo compress.lo uncompr.lo gzclose.lo gzlib.lo gzread.lo gzwrite.lo  -lc
> rm -f libz.dylib libz.1.dylib
> ln -s libz.1.2.8.dylib libz.dylib
> ln -s libz.1.2.8.dylib libz.1.dylib
> gcc -O3  -DHAVE_HIDDEN -o examplesh example.o -L. libz.1.2.8.dylib
> gcc -O3  -DHAVE_HIDDEN -o minigzipsh minigzip.o -L. libz.1.2.8.dylib
> installing
> install flags: install SHELL=/bin/bash
> cp libz.a /nix/store/ry1xfxg5rm02caqzszjidqrgvzhp75hg-zlib-1.2.8/lib
> chmod 644 /nix/store/ry1xfxg5rm02caqzszjidqrgvzhp75hg-zlib-1.2.8/lib/libz.a
> cp libz.1.2.8.dylib /nix/store/ry1xfxg5rm02caqzszjidqrgvzhp75hg-zlib-1.2.8/lib
> chmod 755 /nix/store/ry1xfxg5rm02caqzszjidqrgvzhp75hg-zlib-1.2.8/lib/libz.1.2.8.dylib
> cp zlib.3 /nix/store/ry1xfxg5rm02caqzszjidqrgvzhp75hg-zlib-1.2.8/share/man/man3
> chmod 644 /nix/store/ry1xfxg5rm02caqzszjidqrgvzhp75hg-zlib-1.2.8/share/man/man3/zlib.3
> cp zlib.pc /nix/store/ry1xfxg5rm02caqzszjidqrgvzhp75hg-zlib-1.2.8/lib/pkgconfig
> chmod 644 /nix/store/ry1xfxg5rm02caqzszjidqrgvzhp75hg-zlib-1.2.8/lib/pkgconfig/zlib.pc
> cp zlib.h zconf.h /nix/store/ry1xfxg5rm02caqzszjidqrgvzhp75hg-zlib-1.2.8/include
> chmod 644 /nix/store/ry1xfxg5rm02caqzszjidqrgvzhp75hg-zlib-1.2.8/include/zlib.h /nix/store/ry1xfxg5rm02caqzszjidqrgvzhp75hg-zlib-1.2.8/include/zconf.h
> post-installation fixup
> gzipping man pages in /nix/store/ry1xfxg5rm02caqzszjidqrgvzhp75hg-zlib-1.2.8
> stripping (with flags -S) in /nix/store/ry1xfxg5rm02caqzszjidqrgvzhp75hg-zlib-1.2.8/lib
> strip: can't process non-object and non-archive file: /nix/store/ry1xfxg5rm02caqzszjidqrgvzhp75hg-zlib-1.2.8/lib/pkgconfig/zlib.pc
> patching script interpreter paths in /nix/store/ry1xfxg5rm02caqzszjidqrgvzhp75hg-zlib-1.2.8
> find: -perm: /0100: illegal mode string
> builder for ‘/nix/store/ydby11y8c66mip7c0hrwba1piipl2r91-zlib-1.2.8.drv’ failed with exit code 1
> cannot build derivation ‘/nix/store/h0prdxs8k2irmjbf0cxg4bv1sgcp65x7-curl-7.43.0.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/59sdl75fbpa0lr14k9zkyd810rgc6viv-sed-4.2.2.tar.bz2.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/y4753yvsd0ya2b6wy0g5k3wn4lwfs533-xz-5.2.1.tar.bz2.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/plsbi4kds37f6gn48gvnx5p6ick8izik-gnused-4.2.2.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/4riavg2sz9yvvbvwm80bjfd5kaqaznmh-xz-5.2.1.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/46lrmvbirqjl5gb869sphvj6whmylfn6-stdenv-darwin-boot-2.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/vnpirirkrc4958nhz1bsrwa5zzq536l4-bash-4.3-p39.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/lrf5xz97lqi4cm5384i7jy2p2gz9w99k-clang-wrapper-3.6.2.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/r7pqc5a7shzl8cpy9vcnl01dwzy889n8-gnutar-1.28.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/pida8z8l506rjyfnimyj5f4b98gpjy5y-python-2.7.10.drv’: 1 dependencies couldn't be built
> error: build of ‘/nix/store/pida8z8l506rjyfnimyj5f4b98gpjy5y-python-2.7.10.drv’ failed

And for `cabal-install`, and `hub` is the same.

Any suggestions?

**Comment by vcunat** [comment] 2015-09-04 06:27
Duplicate of #9044.

**Closed by vcunat** 2015-09-04 06:27 UTC
Labels: darwin, duplicate
