### ISSUE TITLE
Gnome forces keyring ssh info into SSH_AUTH_SOCK

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#8356] opened 2015-06-16 12:41 UTC
I deactivated gnome's keyring ssh and gnupg support by adding `--disable-gpg-agent` and `--disable-ssh-agent` to the keyrings configure flags. I also set `services.xserver.startGnuPGAgent=true` and `programs.ssh.startAgent=false` in my `configuration.nix`. I also put the following in my `~/.profile`:

```
# GnuPG agent is used as an SSH agent
export SSH_AUTH_SOCK=~/.gnupg/S.gpg-agent.ssh
```

Still, in Gnome, I have this in a terminal:

```
$ echo $SSH_AUTH_SOCK 
/run/user/1000/keyring/ssh
```

**Comment by DamienCassou** [comment] 2015-06-16 12:42
@lethalman

**Comment by lethalman** [comment] 2015-06-16 14:14
Cannot reproduce, you are probably overriding it wrong. I have no `SSH_AUTH_SOCK` in the env. Closing.

**Closed by lethalman** 2015-06-16 14:14 UTC

**Comment by philandstuff** [comment] 2016-06-18 09:59
I am seeing this too. I want to use gpg-agent for ssh, but gnome-keyring overrides my settings.  I am tying to do what @peti suggested in c4018c0e65f825584f6154fd91b85d7ad6fe9896, and put the following lines somewhere on session startup:

    gpg-connect-agent /bye
    GPG_TTY=$(tty)
    export GPG_TTY

    unset SSH_AGENT_PID
    export SSH_AUTH_SOCK="${HOME}/.gnupg/S.gpg-agent.ssh"

In particular, I'm trying to put them into `services.xserver.displayManager.sessionCommands`.  However, once I've logged in, I find that SSH_AUTH_SOCK points to `/run/user/1000/keyring/ssh` instead.

[It's possible to disable SSH support from gnome-keyring](https://wiki.gnome.org/Projects/GnomeKeyring/Ssh), which would be my preferred option. I'm going to see if I can expose this as a NixOS option.

**Comment by DamienCassou** [comment] 2016-06-18 13:16
Thanks for having a look. This might also be relevant: http://www.fsij.org/doc-gnuk/gnome3-gpg-settings.html

**Comment by philandstuff** [comment] 2016-06-18 13:23
Yes. I think disabling ssh support by editing `/etc/xdg/autostart/gnome-keyring-ssh.desktop` in the system profile is my preferred way of doing this, if it's possible. I've [asked a question on nix-dev](http://lists.science.uu.nl/pipermail/nix-dev/2016-June/020790.html) about it.

**Comment by peti** [comment] 2016-06-18 13:48
Maybe it helps to move the commands 

~~~
GPG_TTY=$(tty)
export GPG_TTY
unset SSH_AGENT_PID
export SSH_AUTH_SOCK="${HOME}/.gnupg/S.gpg-agent.ssh"
~~~

into `~/.bashrc` instead?

**Comment by philandstuff** [comment] 2016-06-18 13:51
Putting the lines into `.bashrc` feels a sticking plaster which will only affect `bash` environments rather than the whole session.  In particular, I won't be able to access the gpg-agent for ssh from within emacs, because it'll see the wrong environment variables.

**Comment by cstrahan** [comment] 2016-07-18 19:26
Note that gpg 2.1.13 changed the directory for IPC sockets, so you'd need something like this instead:

    export SSH_AUTH_SOCK="/run/user/$UID/gnupg/S.gpg-agent.ssh"

https://lists.gnupg.org/pipermail/gnupg-announce/2016q2/000390.html

**Comment by makefu** [comment] 2016-07-20 23:47
when i put       `GPG_TTY=$(tty)` into ` services.xserver.displayManager.sessionCommands` the variable contains "not a tty". how can i work around this?
i am using slim + awesomewm
