### ISSUE TITLE
peazip,please

### ISSUE THREAD

**Issue by prehonor** [NixOS/nixpkgs#208954] opened 2023-01-03 23:46 UTC
**Project description**
PeaZip is a free file archiver utility and rar extractor for Linux, macOS, and Windows, which works with 200+ archive types and variants (7z, ace, arc, bz2, cab, gz, iso, paq, pea, rar, tar, wim, zip, zipx...), handles spanned archives (001, r01, z01...), supports multiple archive encryption standards, file hashing, exports tasks as console scripts

**Metadata**

* homepage URL:https://peazip.github.io/peazip-linux.html
* source URL:https://sourceforge.net/projects/peazip/
* license:  LGPL-3.0 license 
* platforms: unix, linux, darwin

**Comment by wegank** [comment] 2023-01-04 00:21
#169447

**Comment by totoroot** [comment] 2023-01-04 19:01
Duplicate of https://github.com/NixOS/nixpkgs/issues/167707

**Closed by totoroot** 2023-01-04 19:01 UTC
Labels: 0.kind: packaging request
