### ISSUE TITLE
nix-perl and nix-serve fails to build

### ISSUE THREAD

**Issue by pinpox** [NixOS/nixpkgs#158579] opened 2022-02-08 09:43 UTC
### Describe the bug
Since recenctly, enabling nix-serve breaks rebuilding the system as it's dependency nix-perl fails to build. 
This is the log of the build:
https://gist.github.com/pinpox/b5d5f4b8d20bcbe53a485f5a5752f2b4

### Steps To Reproduce
1. Enable nix-serve
2. rebuild system

### Expected behavior
System rebuilds fine

### Notify maintainers
@edolstra @InternetUnexplorer @Artturin @Mic92 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - host os: `Linux 5.10.93, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(root): `"nixos-22.05pre350399.a529f0c125a"`
 - nixpkgs: `/nix/store/626qldjl59n3cx00l2sd86734vdj99pk-source`

```

**Comment by edolstra** [comment] 2022-02-08 10:15
Looks like a mismatch between nix and nix-perl. It's building nix-perl 2.3 against nix 2.6, which doesn't work.

**Comment by pinpox** [comment] 2022-02-08 10:25
> Looks like a mismatch between nix and nix-perl. It's building nix-perl 2.3 against nix 2.6, which doesn't work.

I've used the workaround mentionend here:  https://github.com/edolstra/nix-serve/issues/28 is fixed
```
 
    nixpkgs.overlays = [
      (self: super: {
        nix-serve = super.nix-serve.override { nix = pkgs.nix_2_3; };
      })
    ];
```
To be able to build on unstable. Is that not required anymore or is there a different way to get it to work on unstable now?

**Comment by edolstra** [comment] 2022-02-08 13:15
BTW, I can't reproduce this. `nix-build -A nix-serve` on nixpkgs master succeeds for me.

**Comment by misuzu** [comment] 2022-07-25 16:06
nix-perl and nix-serve are still [broken](https://hydra.nixos.org/build/184492237) on aarch64-darwin

**Comment by misuzu** [comment] 2022-07-30 08:22
Should be fixed now.

**Closed by misuzu** 2022-07-30 08:22 UTC
Labels: 0.kind: bug
