### ISSUE TITLE
IBus Doesn't Work with Gnome

### ISSUE THREAD

**Issue by sorpaas** [NixOS/nixpkgs#17277] opened 2016-07-26 17:02 UTC
## Issue description

IBus does not work together with gnome.
### Steps to reproduce

Enable ibus and gnome in the config file:

```
  services.xserver.desktopManager.gnome3.enable = true;
  services.xserver.displayManager.gdm.enable = true;
  i18n.inputMethod.enabled = "ibus";
  i18n.inputMethod.ibus.engines = with pkgs.ibus-engines; [ anthy hangul libpinyin m17n mozc table table-others ];
```

Rebuild, and run `ibus-setup` results in this error:

```
Traceback (most recent call last):
  File "/nix/store/jp7n999igwwx0593z4i4jk07fjj41x0q-ibus-1.5.13/share/ibus/setup/main.py", line 556, in <module>
    setup = Setup()
  File "/nix/store/jp7n999igwwx0593z4i4jk07fjj41x0q-ibus-1.5.13/share/ibus/setup/main.py", line 110, in __init__
    self.__init_ui()
  File "/nix/store/jp7n999igwwx0593z4i4jk07fjj41x0q-ibus-1.5.13/share/ibus/setup/main.py", line 269, in __init_ui
    self.__checkbutton_auto_start.set_active(self.__is_auto_start())
  File "/nix/store/jp7n999igwwx0593z4i4jk07fjj41x0q-ibus-1.5.13/share/ibus/setup/main.py", line 512, in __is_auto_start
    "share/applications/ibus.desktop")
  File "/nix/store/g12rmkz0a8j6sd3h0sw3zm4a57f29vmi-python3-3.5.2/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/nix/store/g12rmkz0a8j6sd3h0sw3zm4a57f29vmi-python3-3.5.2/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```
## Technical details
- System: 16.09.git.5e5a413 (Flounder) (Merged from nixos-unstable channel 3badad811c600db9867f15a326efa69898299099)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 16.09.git.5e5a413

**Comment by Kintaro** [comment] 2016-08-05 05:16
Running into the exact same problem.

**Comment by gebner** [comment] 2016-08-05 07:17
cc @ericsagnes

**Comment by ericsagnes** [comment] 2016-08-05 08:10
Thanks for pinging, I totally missed this issue.

cc ibus maintainer @ttuegel

**Comment by ericsagnes** [comment] 2016-08-05 08:44
As a quickfix renaming/deleting `~/.config/ibus/` seems to fix the problem.

**Comment by Kintaro** [comment] 2016-08-05 11:41
Already tried deleting that directory.
I tried it from withing gnome, xmonad and my own WM. Issue seems to persist.

**Comment by ericsagnes** [comment] 2016-08-05 11:53
@Kintaro I added a PR (#17532) that should fix the issue.

The reason is that gnome3 module install `pkgs.ibus` in path and this conflicts with the `ibus-with-plugins` package installed by the ibus module.

Until the PR is merged a workaround is to run `ibus-setup` from `ibus-with-plugins` package.
It is possible with some shell-fu:

```
$ $(nixos-option i18n.inputMethod.package | sed -n 2p | sed 's/"//g')/bin/ibus-setup
```

**Comment by DamienCassou** [comment] 2016-08-06 05:31
@sorpaas @Kintaro Can you please test the patch and report to us?

**Comment by Kintaro** [comment] 2016-08-14 10:11
Sorry for the late reply With that shell-fu, it does start, but cannot find Anthy, even if I include it in the packages

**Comment by ericsagnes** [comment] 2016-08-14 12:37
> Sorry for the late reply With that shell-fu, it does start, but cannot find Anthy, even if I include it in the packages

I tried, and got the same result.
Ibus doesn't even show in the systray.

Fcitx is working fine in gnome, so maybe until a solution is found for ibus you can use it instead?
It has anthy and mozc and work in a similar manner to ibus.

I will look a little more into this and try to find the cause.
Having regular ibus path in `XDG_DATA_DIRS` and `GI_TYPELIB_PATH` is strange.

**Comment by eqyiel** [comment] 2018-01-11 08:48
@Kintaro if you are still interested in this, would you mind checking out https://github.com/NixOS/nixpkgs/pull/33731?

**Comment by jtojnar** [comment] 2018-03-04 17:56
Works for me with the latest PR and mozc. There were also some more significant changes in ibus packaging in the meanwhile. Please re-open if you can still reproduce this.

**Closed by jtojnar** 2018-03-04 17:57 UTC
Labels: 0.kind: bug
