### ISSUE TITLE
Chromium coredump on wayland screenshare

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#167526] opened 2022-04-06 12:37 UTC
### Describe the bug
Chromium coredumps on wayland/sway when trying to share a screen.

### Steps To Reproduce
1. Use sway/wayland
2. start `chromium --enable-features=UseOzonePlatform --ozone-platform=wayland`
3. visit "https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing/"
4. Click on "share screen"
5. Click anywhere
6. Core-Dump

### Expected behavior
A selector for the screen to share should appear

### Additional context
According chromium setting:
```
chrome://flags/#enable-webrtc-pipewire-capturer = enabled
```

According nixos configuration:

```
  xdg.portal = { 
    enable = true;
    wlr = { 
      enable = true;
      settings = { 
        screencast = { 
          max_fps = 30; 
          chooser_type = "simple";
          chooser_cmd = "${pkgs.slurp}/bin/slurp -f %o -or";
        };
      };  
    };  
    gtkUsePortal = true; # does not seem to affect the issue. Same with this setting disabled.
  };  


```

Console output when the error occurs:
```
[191680:191711:0406/150359.461672:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[191680:191711:0406/150359.461712:ERROR:select_file_dialog_linux_portal.cc(242)] Failed to read portal version property
[191720:191720:0406/150359.472635:ERROR:gl_surface_egl.cc(1405)] EGL display query failed with error EGL_BAD_PARAMETER
[191720:191720:0406/150359.472775:ERROR:gl_surface_egl.cc(1430)] eglInitialize Default failed with error EGL_BAD_DISPLAY
[191720:191720:0406/150359.472840:ERROR:gl_ozone_egl.cc(20)] GLSurfaceEGL::InitializeOneOff failed.
[191720:191720:0406/150359.474047:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[191680:191680:0406/150359.496758:ERROR:cursor_loader.cc(116)] Failed to load a platform cursor of type kNull
[191776:191776:0406/150359.543208:ERROR:gl_surface_egl.cc(1405)] EGL display query failed with error EGL_BAD_PARAMETER
[191776:191776:0406/150359.543331:ERROR:gl_surface_egl.cc(1430)] eglInitialize Default failed with error EGL_BAD_DISPLAY
[191776:191776:0406/150359.543393:ERROR:gl_ozone_egl.cc(20)] GLSurfaceEGL::InitializeOneOff failed.
[191776:191776:0406/150359.546580:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[191680:191796:0406/150359.554448:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[191680:191796:0406/150359.555528:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[191680:191796:0406/150359.556719:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[191680:191680:0406/150359.560628:ERROR:system_web_app_manager.cc(320)] Exceeded SWA install retry attempts.  Skipping installation, will retry on next OS update or when locale changes.
[191816:191816:0406/150359.571755:ERROR:gl_surface_egl.cc(1405)] EGL display query failed with error EGL_BAD_PARAMETER
[191816:191816:0406/150359.571857:ERROR:gl_surface_egl.cc(1430)] eglInitialize Default failed with error EGL_BAD_DISPLAY
[191816:191816:0406/150359.571934:ERROR:gl_ozone_egl.cc(20)] GLSurfaceEGL::InitializeOneOff failed.
[191816:191816:0406/150359.573569:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[191828:191828:0406/150359.601234:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[191680:191680:0406/150405.624912:ERROR:cursor_loader.cc(116)] Failed to load a platform cursor of type kHand
[191680:191680:0406/150409.571176:ERROR:egl_dmabuf.cc(296)] Unable to load EGL entry functions.
[0406/150409.602465:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0406/150409.607672:ERROR:process_memory_range.cc(75)] read out of range
/home/dse/bin/chromium-wayland: line 6: 191680 Segmentation fault      (core dumped) chromium --enable-features=UseOzonePlatform --ozone-platform=wayland

```

Also this works fine with firefox-wayland and used to work with chromium.

### Notify maintainers

@primeos
@danielfullmer
@Frostman

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.0-zen1, NixOS, 22.05 (Quokka), 22.05pre366144.bc4b9eef3ce`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(dse): `""`
 - channels(root): `"nixos, nixos-stable-21.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by d4g** [comment] 2022-04-06 13:09
Could be related to https://github.com/NixOS/nixpkgs/issues/156950

**Comment by primeos** [comment] 2022-04-06 20:30
Did screen sharing work before / is that crash (segmentation fault) new? And do you know since which version it stopped working?

So far screen sharing did never work reliably and there have been frequent regressions: https://github.com/NixOS/nixpkgs/issues/91218 (I've fixed it twice on my test setup but I've given up since then).

We might want to close this issue in favor of https://github.com/NixOS/nixpkgs/issues/91218 to keep the discussion in one place.

**Comment by mdarocha** [comment] 2022-04-06 22:07
For me, screenshare works on Chromium v99, and stopped working after uodate to v100

**Comment by d4g** [comment] 2022-04-07 07:30
For me it also worked in the past without issues.
This is new and this is chrome core-dumping. This is a different issue. If screen sharing did not work in the past, it just did not work. It did not cause an out of bounds read or crash of the browser.

Please don't close this issue.

**Comment by primeos** [comment] 2022-04-07 19:46
> Please don't close this issue.

Sure, we can leave it open. We should mention it in the other issue though (I just did that) for better visibility.
Now we need someone with time and motivation to handle this issue (analyzing the issue, searching for upstream issues, etc. and eventually someone needs to submit a fix).

**Comment by nh2** [comment] 2022-04-07 20:14
@d4g Since this is NixOS and we have the boon of input-reproducibility and a binary cache, could you post:

* the nixpkgs commit you are on
* the nix store path of your chromium binary

This will make it even easier for others to reproduce.

You may also be able to get the stack trace with GDB using `gdb --args chromium`, use `run`, make the segfault happen, and use `backtrace` in GDB.

**Comment by chaoflow** [comment] 2022-04-08 00:15
- nixpkgs: ccb90fb9e11459aeaf83cc28d5f8910816d90dd0
- /nix/store/07346c7jv5wnwg30r5dvmlgqbk52hinz-chromium-100.0.4896.60/bin/chromium

**Comment by chaoflow** [comment] 2022-04-08 00:19
Regarding gdb: ``"/run/current-system/sw/bin/chromium": not in executable format: file format not recognized``

How do I get gdb on the actual executable but keep the env vars of the shell script wrapper?

**Comment by nh2** [comment] 2022-04-08 00:43
@chaoflow

> How do I get gdb on the actual executable but keep the env vars of the shell script wrapper?

```sh
cp $(which chromium) ~/chromium-gdb
chmod u+w ~/chromium-gdb
```

Now edit `~/chromium-gdb`, replacing like this:

```diff
-exec "/nix/store...
+gdb --args "/nix/store...
```

Then terminate all chromium instances (to avoid joining existing instances), and run `~/chromium-gdb`.

**Comment by edrex** [comment] 2022-04-08 19:03
https://bugs.chromium.org/p/chromium/issues/detail?id=1311437&q=webrtc%3A%3ASharedScreenCastStreamPrivate%3A%3AProcessBuffer&can=1

Looks like it should be fixed in m101

**Comment by d4g** [comment] 2022-04-11 09:46
I tried to build chromiumDev(102) or chrimiumBeta (101) - but both failed with errors related to:

```
 unsupported instrumentation profile format version

```

**Comment by anthr76** [comment] 2022-04-19 11:50
This patch may be useful:

https://webrtc-review.googlesource.com/c/src/+/255601

**Comment by edrex** [comment] 2022-04-19 18:46
@d4g @anthr76 building chrome s you can install the chrome dev or beta channel package. On my up-to-date, flakes-enabled nixos-unstable:

```
$ NIXPKGS_ALLOW_UNFREE=1 nix run --impure nixpkgs#google-chrome-dev
(fetches google-chrome-unstable_102.0.4997.0-1_amd64.deb)
```

The issue seems fixed there. I guess there are no dev builds of chromium upstream, that's a shame.

**Comment by primeos** [comment] 2022-04-19 22:01
I've opened https://github.com/NixOS/nixpkgs/pull/169365 for a quick and dirty fix - the code isn't pretty but should do the job (I wish `fetchpatch` would support Base64 patches or even better: Gerrit and gitiles would support fetching patches using a sane format like basically any other web VCS frontend does...). Anyway, I'll check if the VM test passes (although that patch is so trivial that it should be unnecessary) and can merge the fix tomorrow.

**Comment by d4g** [comment] 2022-04-19 23:44
I love the name `webrtc-wayland-screenshare-coredump-fix.patch `

**Closed** 2022-04-20 19:24 UTC
Labels: 0.kind: bug, 0.kind: regression
