### ISSUE TITLE
Matplotlib with enableQt = false will attempt to use Qt and if Qt is imported by another package

### ISSUE THREAD

**Issue by shuhaowu** [NixOS/nixpkgs#85046] opened 2020-04-12 02:18 UTC
**Describe the bug**
If you construct a nix-shell with matplotlib in its default setting (`enableTk = true; enableQt = false;`) with another app that depends on Qt, matplotlib will try to use the Qt backend unless `matplotlib.use("TkAgg")` is called at the beginning of the Python code that you write.

**To Reproduce**
1. Create a nix shell with a PySide2 app with matplotlib
2. `import matplotlib.pyplot as plt; plt.figure()`
3. Observe crash: 
```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem
```

**Expected behavior**
Matplotlib should use the TK backend.

**Workaround**
Add 
```
import matplotlib
matplotlib.use("TkAgg")
```
to the top of the python script using matplotlib.

**Metadata**
```
these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/8pkkw458w4q00gp9yrcg95mxc72nzd85-nix-info
copying path '/nix/store/8pkkw458w4q00gp9yrcg95mxc72nzd85-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-91-generic, Ubuntu, 16.04.6 LTS (Xenial Xerus)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixpkgs-20.09pre217526.9b3515eb95d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`


```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by teto** [comment] 2020-04-12 12:15
isn't that a matplotlib issue ? they shouldn't rely on an absent backend

**Comment by shuhaowu** [comment] 2020-04-12 13:35
I suspect matplotlib is detecting if it can import pyside, which is possible as pyside exist in this nix shell environment. However, if enableqt is explicitly false, the nix build of matplotlob shouldn't try to use it IMO.

**Comment by doronbehar** [comment] 2020-04-13 21:18
Sounds like a matplot issue to me as well. You see, according to matplotlib's `default.nix`, pretty much the only difference between building it with qt or without it, is the existence of `pyqt5` in it's `propagatedBuildInputs`:

https://github.com/NixOS/nixpkgs/blob/d1295c460fd1c3ccac6221bd3170574137d606ab/pkgs/development/python-modules/matplotlib/default.nix#L43-L49

I also tested the resulting outputs of matplotlib with and without qt using [dirdiff](https://github.com/will133/vim-dirdiff) and the only main difference is `$out/nix-support/propagated-build-inputs`.

When `nix-shell` creates the environment, it puts in `PYTHONPATH` all `propagatedBuildInputs` of all packages you add to the environment that `python` eventually sees. At this point, I wonder how it detects qt5 in it's environment as [`pyside2`](https://github.com/NixOS/nixpkgs/blob/d1295c460fd1c3ccac6221bd3170574137d606ab/pkgs/development/python-modules/pyside2/default.nix#L26-L30) doesn't require `pyqt5` but only `qt5`.

This also conflicts with their docs: https://matplotlib.org/3.2.1/users/installing.html#install-requirements . Please report this upstream @shuhaowu .

As for this error:

```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem
```

This is a known issue with pretty much every python library that requires certain environment to perform GUI stuff. See https://github.com/NixOS/nixpkgs/issues/25351 . See a possible fix in https://github.com/NixOS/nixpkgs/pull/83321 and discussions / broader ideas:

- https://discourse.nixos.org/t/declarative-wrappers/1775
- https://discourse.nixos.org/t/declarative-wrappers-another-idea/6661
- https://github.com/NixOS/nixpkgs/pull/85103

**Comment by dschrempf** [comment] 2021-05-12 14:09
This is still an issue, I just bumped into it.

**Comment by dschrempf** [comment] 2021-11-13 16:26
I just tried plotting a figure with matplotlib default setting (no config files, no additional settings in Nix config), and it worked. I think it uses the tk backend.

**Comment by doronbehar** [comment] 2021-11-13 19:24
I too can confirm the issue is fixed. As mentioned earlier, this was an upstream issue IMO and it is fixed now so it seems.

**Closed by doronbehar** 2021-11-13 19:24 UTC
Labels: 0.kind: bug, 6.topic: python

**Comment by ShamrockLee** [comment] 2024-03-27 01:40
Has anyone reported it upstream?

**Comment by dschrempf** [comment] 2024-03-27 08:15
Is this an upstream issue? Is so, I do not think so.

**Comment by doronbehar** [comment] 2024-03-27 10:55
You can open a new issue if you still experience this issue, when we closed this, we weren't sure what exactly upstream did that fixed this, we just observed this is no longer an issue.
