### ISSUE TITLE
Build failure: system76-power

### ISSUE THREAD

**Issue by PersonForSure** [NixOS/nixpkgs#350143] opened 2024-10-21 05:07 UTC
### Steps To Reproduce

1. Add the following to the configuration.nix
      
      boot.kernelModules = [ "system76_acpi" "system76_io" "k10temp" ];
      hardware.enableAllFirmware = true;
      services.power-profiles-daemon.enable = false;
      hardware.system76.enableAll = true;

2. Rebuild

### Build log

```
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/6ang6g3hkygpymgz6kggl3bvamxvyh17-system76-power-1.1.23.drv^*'
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/n9sfla7fskrba6gg4dma3lm44n9j7ylm-source
source root is source
Executing cargoSetupPostUnpackHook
unpacking source archive /nix/store/h3z8z705cn9ly3cysjll22yr0xq8gz2a-system76-power-1.1.23-vendor.tar.gz
Finished cargoSetupPostUnpackHook
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Executing cargoSetupPostPatchHook
Validating consistency between /build/source/Cargo.lock and /build/system76-power-1.1.23-vendor.tar.gz/Cargo.lock
Finished cargoSetupPostPatchHook
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
Executing cargoBuildHook
cargoBuildHook flags: -j 12 --target x86_64-unknown-linux-gnu --offline --profile release
error: failed to get `sysfs-class` as a dependency of package `system76-power v1.1.23 (/build/source)`

Caused by:
  failed to load source for dependency `sysfs-class`

Caused by:
  Unable to update https://github.com/pop-os/sysfs-class#ab63e7f6

Caused by:
  can't checkout from 'https://github.com/pop-os/sysfs-class': you are in the offline mode (--offline)

```

### Additional context

This is on the unstable channel and the package has no maintainers

### Metadata

```❯nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.54, NixOS, 24.11 (Vicuna), 24.11.20241009.5633bcf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"home-manager, hyprland, nixos"`
 - nixpkgs: `/nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FliegendeWurst** [comment] 2024-10-21 13:10
Duplicate of #349872

**Closed by FliegendeWurst** 2024-10-21 13:10 UTC
Labels: 0.kind: build failure
