### ISSUE TITLE
Chromium seems blurry since 81 -> 83 update

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#89512] opened 2020-06-04 22:50 UTC
## Describe the bug
Recently, the version of Chromium in nixpkgs was updated from version 81.0.4044.138 to 83.0.4103.61, seemingly in commit <https://github.com/NixOS/nixpkgs/commit/cdd95a9625a16827717d8a762eb080334b5ce78a>. For me, this update seems to have caused Chromium to render everything blurrily.

I took some screen-captures of pages viewed in the old and new versions of Chromium to compare (running the old Chromium as `/nix/var/nix/profiles/system-<N>-link/sw/bin/chromium` and otherwise using the current system generation for both, in case that matters), and it looks as though the new Chromium is up-scaling everything slightly — e.g., GitHub issues lists are very slightly wider.

The blurring effect is very noticeable on PDF files and on some images but is much more subtle on text. Images displayed with the HTML `img` element seem to be blurred more than images displayed with the CSS `background-image` property, which are blurred only slightly.

## Screenshots
All these screen-captures were taken with the browser zoom at 100% and show the same webpage (or PDF file) rendered in Chromium 81 (top or left) and Chromium 83 (bottom or right). (The blue and red lines were added by me for clarity.)

### Normal text on the Web (from [(1)](https://github.com/NixOS/nixpkgs/issues?page=501&q=is%3Aissue+is%3Aclosed)):
<details>

<summary>Click to expand</summary>

![GitHub issues](https://user-images.githubusercontent.com/3662816/83813965-f51b9500-a6ad-11ea-9bc7-5e083b36d07b.png)
#### Full size (one can view these in new tabs, zoom in, and switch between them to see the "up-scaling")
![GitHub issues (Chromium 81)](https://user-images.githubusercontent.com/3662816/83817092-7295d400-a6b3-11ea-906f-b653aeef7688.png)
![GitHub issues (Chromium 83)](https://user-images.githubusercontent.com/3662816/83817088-6f9ae380-a6b3-11ea-9a0a-1fc5eb0acb03.png)

</details>

### Text in a PDF file on disk (from [(2)](https://www.jstor.org/stable/j.ctt7sd01)):
<details>

<summary>Click to expand</summary>

![Chromium PDF rendering](https://user-images.githubusercontent.com/3662816/83814858-a3273f00-a6ae-11ea-8d68-fbb23911225b.png)

</details>

### An image displayed as an HTML `img` (from [(3)](https://wiki.debian.org)):
<details>

<summary>Click to expand</summary>

Note that the image is rendered as one pixel wider on each side by Chromium 83 than by Chromium 81.

![The banner on the front page of the Debian wiki](https://user-images.githubusercontent.com/3662816/83816339-b5ef4300-a6b1-11ea-8b77-cbb16a9c7713.png)

</details>

### Another image displayed as an HTML `img` (from [(4)](https://www.gunnerkrigg.com/?p=708)):
<details>

<summary>Click to expand</summary>

![A panel from a webcomic](https://user-images.githubusercontent.com/3662816/83816482-023a8300-a6b2-11ea-954e-59850ccf84db.png)

</details>

### An image displayed as a CSS `background-image` (from [(5)](https://play.google.com/books/reader?id=hEF-BAAAQBAJ&pg=GBS.PA874)):
<details>

<summary>Click to expand</summary>

![Google Play Books](https://user-images.githubusercontent.com/3662816/83816577-3ca42000-a6b2-11ea-900a-815a96efcd32.png)

</details>

## Notify maintainers
 @primeos @thefloweringash @bendlas

## Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.43-hardened, NixOS, 20.09pre228204.467ce5a9f45 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"nixos-20.09pre228204.467ce5a9f45"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [chromium]
# a list of nixos modules affected by the problem
module: []
```

**Comment by matthew-piziak** [comment] 2020-06-05 03:29
Interestingly enough, Chrome 83 adds **Vision Deficiency Emulation**: https://developers.google.com/web/updates/2020/03/devtools

I thought it'd be funny if that were left in this case, but the blurred-vision effect is significantly more pronounced than what you're experiencing.

**Comment by primeos** [comment] 2020-06-05 13:20
@8573 I guess this could be an upstream issue/regression, might be worth trying to reproduce this with Google Chrome or on other Linux distributions. But of course it could also be due to incorrect packaging in Nixpkgs or "incompatible" dependencies.

**Comment by 8573** [comment] 2020-06-06 07:00
Note to self: <https://bugs.chromium.org/p/chromium/issues/detail?id=1087109> might be relevant; try the workaround from that ticket when I have time.

**Comment by 8573** [comment] 2020-06-06 22:53
Indeed, in Chromium 83 I have

```javascript
› window.devicePixelRatio
‹ 1.0026346445083618
```

whereas in Chromium 81 this is simply 1, and, indeed, running Chromium 83 with the command-line option `--force-device-scale-factor=1` changes `window.devicePixelRatio` to 1 and successfully suppresses the blurriness.  I'll add that option to my Chromium wrapper script for now.

Does it count as a NixOS bug that Chromium gets such an irregular `devicePixelRatio`?  In that Chromium ticket, a Chromium developer asks ["Did you ever change your font scale settings?"](https://bugs.chromium.org/p/chromium/issues/detail?id=1087109#c13), but I don't think I did or otherwise have anything suspect in [my font settings](https://github.com/8573/nixos-config/blob/a3ea0f7fa4d64354f2b9615714e547d709e07185/sections/fonts/default.nix).

**Comment by primeos** [comment] 2020-06-07 09:58
@8573 Interesting, with Chromium `83.0.4103.97` I have a `window.devicePixelRatio` of `1`. So this seems to depend on some other configuration as well. I use Wayland (Sway) with XWayland for Chromium. I do explicitly set the DPI to 96 which should be the default. Can you check that value on your setup (e.g. as described in the [Arch wiki](https://wiki.archlinux.org/index.php/Xorg#Display_size_and_DPI))? Maybe this is used to compute the value of `window.devicePixelRatio`.

**Comment by 8573** [comment] 2020-06-11 02:24
@primeos:
> Can you check that value on your setup (e.g. as described in the [Arch wiki](https://wiki.archlinux.org/index.php/Xorg#Display_size_and_DPI))?

```
$ nix-env -iA nixos.xorg.xdpyinfo
...
$ xdpyinfo | grep -B2 resolution
screen #0:
  dimensions:    1920x1080 pixels (508x285 millimeters)
  resolution:    96x96 dots per inch
```
"1920x1080 pixels" looks correct, but I don't know the dimensions of the display in millimeters. (I imagine I can find them if they're important.)

I'm using the i3 window manager without Wayland.  I don't believe I set DPI anywhere — a case-insensitive search for "dpi" in my NixOS configuration returns nothing, and I don't have a `~/.Xresources` file.

**Comment by primeos** [comment] 2020-06-11 09:40
@8573 then I'm unfortunately out of ideas on what causes `window.devicePixelRatio != 1`. I guess as an alternative you could use your workaround with something like `chromium.override { commandLineArgs = --force-device-scale-factor=1 }` or put that setting in your Chromium configuration.

To resolve this properly you'd most likely have to take a look at the Chromium documentation (if this is documented there) or even the source code to find out how `window.devicePixelRatio` is set. But unfortunately that could take quite some time so I'm not sure if it's worth it for you.

> Does it count as a NixOS bug that Chromium gets such an irregular `devicePixelRatio`?

If it's caused by a mistake in the default NixOS configuration, our Nix expression for Chromium, or something like wrong/missing referenced due to not using the FHS I'd consider that a bug that we should fix.

**Comment by DerGuteMoritz** [comment] 2020-06-15 08:23
FWIW, I have the same issue since upgrading to Chromium 83.0.4103.97. My `window.devicePixelRatio` value is exactly `1.0026346445083618`, as well. I'm using Xorg with GDM as display manager and StumpWM as window manager. For comparison, here's my equivalent `xdpyinfo` output:

```
$ nix-shell -p xorg.xdpyinfo --command xdpyinfo | grep -B2 resolution
screen #0:
  dimensions:    4480x1440 pixels (1182x380 millimeters)
  resolution:    96x96 dots per inch
```

**Comment by 8573** [comment] 2020-06-15 17:40
@DerGuteMoritz, thanks for the data point. Does the work-around `--force-device-scale-factor=1` work for you?

I haven't gotten around to investigating from where Chromium gets this value yet.

**Comment by DerGuteMoritz** [comment] 2020-06-15 17:52
Yep, that work-around works (around :smile:). Hat tip, @primeos!

**Comment by primeos** [comment] 2020-07-25 21:37
Is this maybe fixed with M84 now?

Credit for the `--force-device-scale-factor=1` workaround goes to @8573 btw, but thanks anyway :)

**Comment by 8573** [comment] 2020-07-26 04:20
Unfortunately in Chromium 84.0.4147.89, without `--force-device-scale-factor=1`, I still get blurriness and the same `devicePixelRatio`:

```
› window.devicePixelRatio
‹ 1.0026346445083618
```

I never got around to investigating from where this number comes.

As for `--force-device-scale-factor=1`, ultimately it was a Chromium developer by the username of "futhark" who [suggested that](https://bugs.chromium.org/p/chromium/issues/detail?id=1087109#c10).

**Comment by samuelgrf** [comment] 2021-05-03 18:15
This is still an issue.

**Comment by samuelgrf** [comment] 2021-05-03 19:00
Ok, I just wrote that to remove the stale label. I just checked if this still happens on Chromium stable, and it seems to have been fixed since version 90, the issue reappears after downrading to 89.
Can anyone confirm so this can be closed?

**Comment by zeorin** [comment] 2021-08-30 09:58
I have a similar issue, except in my case all text in chrome is _too small_:
```
window.devicePixelRatio
0.828125
```
```
❯ nix-shell -p xorg.xdpyinfo --command xdpyinfo | grep -B2 resolution
screen #0:
  dimensions:    3840x1080 pixels (1204x343 millimeters)
  resolution:    81x80 dots per inch
```
using i3wm, not setting the dpi manually anywhere. I am using 2× 27" 1080p screens, so that probably is _technically correct_, but not what I want. I'll set the DPI manually, then.

**Comment by wmertens** [comment] 2022-02-22 18:36
If you run wayland and set NIXOS_OZONE=1, the latest builds are nice and sharp. Eventually, Ozone will be the default Chromium renderer. So I propose this issue be closed.

**Comment by primeos** [comment] 2022-02-22 20:10
Let's close it then. Not sure if this is even still an issue (the old X11 code was replaced with Ozone/X11 so many things might have changed). Feel free to re-open if if it's still an issue but I don't think we can really do much about it in Nixpkgs anyway (probably an upstream bug/issue).

**Closed by primeos** 2022-02-22 20:10 UTC
Labels: 0.kind: bug
