### ISSUE TITLE
Package request: ActivityWatch 

### ISSUE THREAD

**Issue by stnert** [NixOS/nixpkgs#226209] opened 2023-04-14 22:56 UTC
The best free and open-source automated time tracker. Cross-platform, extensible, privacy-focused.

homepage URL: https://activitywatch.net/
source URL: https://github.com/ActivityWatch/activitywatch
license:  MPL-2.0 license
platforms: Linux

**Comment by pinn3** [comment] 2023-04-15 09:17
Duplicate of https://github.com/NixOS/nixpkgs/issues/97379

**Closed** 2023-04-15 15:13 UTC
Labels: 0.kind: packaging request
