### ISSUE TITLE
cutegram cannot find Qt plugin "xcb"

### ISSUE THREAD

**Issue by kisik21** [NixOS/nixpkgs#39658] opened 2018-04-28 18:28 UTC
## Issue description
Cutegram dumps this to console and bails out:
```
 ~ $ cutegram
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
Aborted (core dumped)
```

### Steps to reproduce
```
~ $ nix-env -iA nixos.cutegram
~ $ cutegram
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.35, NixOS, 18.03.132083.06c576b0525 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03.132083.06c576b0525"`
 - channels(kisik21): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment] 2018-04-28 19:33
Duplicate of https://github.com/NixOS/nixpkgs/search?q=qt+aborted&type=Issues

**Comment by jtojnar** [comment] 2018-04-28 19:36
[This one](https://github.com/NixOS/nixpkgs/issues/37864) is a recent one explaining a solution.

**Closed** 2018-06-27 09:39 UTC

**Comment by balsoft** [comment] 2019-02-22 17:18
This is still somehow a problem, even though it's supposed to be fixed. It fails for me on unstable.
