### ISSUE TITLE
fetchdarcs fetches into a fixed build directory

### ISSUE THREAD

**Issue by pijul** [NixOS/nixpkgs#18528] opened 2016-09-12 08:13 UTC
## Issue description

Fetchdarcs calls `darcs get` into `$out`, which is wrong, as `$out` is the directory where the `fetchdarcs` derivation lives. It works fine if only one version of one derivation on the system is fetched via darcs, but fails in other cases.

### Steps to reproduce

- Install an existing package that uses fetchdarcs.
- Write a package using `fetchdarcs`, and try to build it.

## Technical details

* System:  16.09pre89269.8512747 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre89269.8512747"

**Comment by rasendubi** [comment] 2016-09-12 22:23
`fetchdarcs` is not a derivation, but a function that returns a derivation. Thus, `builder.sh` is called with `$out` set to output directory of the final package (where the final package is fetched darcs repository).

For example, the same approach is used in `fetchurl` and many other fetchers.

Though, I've followed your steps to reproduce and built both `pijul.src` and `emacsPackages.darcsum.src` (which are both `fetchdarcs`) and that worked fine.

I'm closing the issue as I believe there is no bug. Feel free to reopen if you still think otherwise (the best way is to post better SToR)

**Closed by rasendubi** 2016-09-12 22:23 UTC

**Comment by pijul** [comment] 2016-09-13 07:26
I reported this because… it actually hit me!
I tried the pijul derivation some time ago, and then started writing a package for another project. `fetchdarcs` kept fetching the sources for pijul. I should add that that other project is not packaged in Nix, it's just installed locally with nix-env.
`fetchgit` uses a hack to turn a URL into a `$out`.

**Comment by rasendubi** [comment] 2016-09-13 08:46
Have you copied `sha256` from the other `fetchdarcs` package?

I see the issue can happen if two `fetchdarcs` derivations have the same hash. In that case, they both end up with the same output directory (because they all have the same name).

**Comment by pijul** [comment] 2016-09-13 08:47
Good point. I copied it in order for `nix-build` to tell me what hash it expected!
Thanks.

**Comment by pijul** [comment] 2016-09-22 11:50
Wait, tried again with a different hash, same error. I'm reopening.
