### ISSUE TITLE
Update request: gtk3 3.24.37 → 3.24.38

### ISSUE THREAD

**Issue by simplejack-src** [NixOS/nixpkgs#237452] opened 2023-06-13 00:27 UTC
- Package name: [gtk3](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/gtk/3.x.nix)
- Latest released version: 3.24.38
- Current version on the unstable channel: 3.24.37
- Current version on the stable/release channel: 3.24.37
- Release [Notes](https://gitlab.gnome.org/GNOME/gtk/-/blob/3e6fd55ee00d4209ce2f2af292829e4d6f674adc/NEWS)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

(teams.gnome.members):
@bobby285271
@hedning
@jtojnar
@dasj19
@maxeaubrey

-----

Note for maintainers: Please tag this issue in your PR.

Reason for request: gtk3.24.37 modified freedesktop startup notifications (fixing it in some people's setups, breaking it in others). 3.24.38 includes a fix for the breaking people (specific to Wayland users using a compositor that doesn't support startup notifications). Ideally would like a [backport] to 23.05 (so people on the upgrade path don't find this broken as I did).

**Comment by simplejack-src** [comment] 2023-06-14 23:13
@bobby285271 I don't see this version-bump in staging or master (nor a PR for it), is that label correct?

**Comment by bobby285271** [comment] 2023-06-15 00:37
https://github.com/NixOS/nixpkgs/commit/eb9d4dbe5c35febbe1e2c1118acfb7c279d58900 ([PR tracker](https://nixpk.gs/pr-tracker.html?pr=236817)), I have the (bad) habit of batching updates for the same desktop in one PR since I do the testing in batches, so I would expect it hard to find the corresponding PR... When I don't mention package name or attr path in title [I usually use](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+updates+in%3Atitle+author%3Abobby285271) `xxx updates` or `xxx updates YYYY-MM-DD` (if I am doing it frequent)

**Comment by simplejack-src** [comment] 2023-06-15 01:54
Ah there it is (sorry for the noise). I'll leave this issue open to keep track until its merged into the 23.05 branch.

**Comment by bobby285271** [comment] 2023-06-22 10:42
Sorry it took too long for me to revisit this, hopefully we don't miss the next staging-next-23.05

> gtk3.24.37 modified freedesktop startup notifications (fixing it in some people's setups, ...)

Hmmm, I guess this is probably https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/5443? :thought_balloon: 

> (..., breaking it in others). 3.24.38 includes a fix for the breaking people (specific to Wayland users using a compositor that doesn't support startup notifications).

And, I guess this is probably https://gitlab.gnome.org/GNOME/gtk/-/issues/5701 (and the fix https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/5743)? Have you tried the MR via e.g. `system.replaceRuntimeDependencies`? :thinking: 

> Ideally would like a [backport] to 23.05.

I revisited most distro packaging and https://github.com/GNOME/gtk/compare/3.24.38...gtk-3-24, this should be fine to me, note that 3.24.38 is said to "[cause regression](https://gitlab.gnome.org/GNOME/gtk/-/issues/5853) on darwin". Have no darwin access and don't know what the actual status is :woman_shrugging:

**Comment by simplejack-src** [comment] 2023-06-22 20:32
@bobby285271 I can't comment on the Darwin situation either (similarly no HW). As for the other specific patch, that was the commit I had originally pegged as the fix that I wanted (to fix my GTK3 apps from crashing on startup with the Wayfire compositor). So yes, I would find that patch alone (for me) to be an acceptable fix* [when backported to 23.05].

*Cherrypicking this fix out (vs the 3.24.48 bump) actually works better for me as I run [gtk3-classic](https://github.com/lah7/gtk3-classic) grafted (`system.replaceRuntimeDependencies`) onto the relevant gtk3 apps and the bump to 3.24.38 also included a glib schema change (which meant I had to hack that in to keep grafting instead rebuilding).

**Comment by paperdigits** [comment] 2023-06-22 21:03
darktable has opened a bug upstream: https://gitlab.gnome.org/GNOME/gtk/-/issues/5853

**Comment by bobby285271** [comment] 2023-06-23 02:16
Okay I updated #239169 to address that (on 23.05).

**Comment by bobby285271** [comment] 2023-06-24 04:38
I merged the PR, since there is no more things to do here I am closing this.

It might take another 2-3 weeks for the change to hit nixos-23.05 channel though since this is a staging change, you can visit https://nixpk.gs/pr-tracker.html?pr=239169 for updates.

**Closed by bobby285271** 2023-06-24 04:38 UTC
Labels: 9.needs: port to stable
