### ISSUE TITLE
bottles 2022.8.28-brescia-2

### ISSUE THREAD

**Issue by X9VoiD** [NixOS/nixpkgs#192292] opened 2022-09-21 19:46 UTC
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: bottles

current version: 2022.5.28-trento-3
desired version: 2022.8.28-brescia-2

###### Notify maintainers

@psydvl @SCOTT-HAMILTON

###### Note for maintainers

`bottles` is using gtk4 for brescia.

**Comment by SuperSamus** [comment] 2022-09-21 20:23
Kinda duplicate of #181501.

**Closed** 2022-11-21 20:11 UTC
Labels: 9.needs: package (update)
