### ISSUE TITLE
Termius ssh client

### ISSUE THREAD

**Issue by Th0rgal** [NixOS/nixpkgs#76816] opened 2020-01-02 12:22 UTC
**Project description**
I'm using Termius everyday because it is quite simple to easy and it allows me to share my ssh keys between my different computers and even my phone. I really like this app and it's possible to get the premium features for free with github student. Currently I have to restart to windows in order to use it and I would really like to be able to use it on nixos too :)

**Metadata**

* homepage URL: https://termius.com/
* source URL: this is closed source
* license: I'm not sure but I can ask them
* platforms: this is an electron app so there is a version for basically every systems

**Comment by filalex77** [comment] 2020-01-03 11:13
Duplicate of #74777.

**Closed** 2020-02-21 14:22 UTC
Labels: 0.kind: packaging request
