### ISSUE TITLE
bumblebee starts xorg with log file in nix store

### ISSUE THREAD

**Issue by Szczyp** [NixOS/nixpkgs#11530] opened 2015-12-07 16:24 UTC
```
kernel: bbswitch: enabling discrete graphics
kernel: vgaarb: device changed decodes: PCI:0000:01:00.0,olddecodes=io+mem,decodes=none:owns=none
kernel: [drm] Initialized nvidia-drm 0.0.0 20150116 for 0000:01:00.0 on minor 1
kernel: NVRM: loading NVIDIA UNIX x86_64 Kernel Module  352.63  Sat Nov  7 21:25:42 PST 2015
display-manager-start[812]: xf86: found device 1
bumblebeed[755]: [XORG] (EE)
bumblebeed[755]: [XORG] (EE) Cannot open log file "/nix/store/1fxyhm8262vvsqyh4mhi8gcj84skj983-xorg-server-1.17.2/var/log/Xorg.8.log"
bumblebeed[755]: [XORG] (EE)
bumblebeed[755]: [XORG] (EE)
bumblebeed[755]: [XORG] (EE)
bumblebeed[755]: X did not start properly
```

I'm using ```  hardware.bumblebee.enable = true;``` in my configuration.nix and ```primusrun```. Seems like the case of relative path instead of absolute as ```/var/log/Xorg.8.log``` would probably work.

**Comment by abbradar** [comment] 2015-12-08 15:27
Hm, strange, this shouldn't be the case because we patch `-logfile /var/log/X.bumblebee.log` in. You use the latest `master`, correct? I've made numerous changes to `bumblebee` a while ago.

**Comment by Szczyp** [comment] 2015-12-08 21:08
I'm using unstable which is currently at ```b1dca6```. I can see a few bumblebee related commits prior to this and none after so I assume theses changes you are talking about are included.

**Comment by abbradar** [comment] 2015-12-08 22:07
Very strange, let's try to debug this. Please apply http://lpaste.net/146755 (you can do this via `overrideDerivation`), run `bumblebeed -vvv` from `root` manually (don't forget to run `systemctl stop bumblebeed` before this!), run `optirun` and show us the `bumblebeed` output.

**Comment by Szczyp** [comment] 2015-12-09 04:42
This is what i get after building from master (which is basically the same):
```
[20006.484902] [DEBUG]Found card: 01:00.0 (discrete)
[20006.484928] [DEBUG]Found card: 00:02.0 (integrated)
[20006.484936] [DEBUG]Reading file: /nix/store/9c8s0lkjh4yfhbl0qi84z5wkx8855rbv-bumblebee-3.2.1/etc/bumblebee/bumblebee.conf
[20006.485330] [DEBUG]Process modprobe started, PID 22525.
[20006.485365] [DEBUG]Hiding stderr for execution of modprobe
[20006.589432] [DEBUG]SIGCHILD received, but wait failed with No child processes
[20006.589564] [DEBUG]Process modprobe started, PID 22526.
[20006.589605] [DEBUG]Hiding stderr for execution of modprobe
[20006.644769] [DEBUG]SIGCHILD received, but wait failed with No child processes
[20006.644810] [DEBUG]Detected nouveau driver
[20006.644874] [DEBUG]bbswitch has been detected.
[20006.644887] [INFO]Switching method 'bbswitch' is available and will be used.
[20006.644900] [DEBUG]Active configuration:
[20006.644912] [DEBUG] bumblebeed config file: /nix/store/9c8s0lkjh4yfhbl0qi84z5wkx8855rbv-bumblebee-3.2.1/etc/bumblebee/bumblebee.conf
[20006.644923] [DEBUG] X display: :8
[20006.644934] [DEBUG] LD_LIBRARY_PATH:
[20006.644945] [DEBUG] Socket path: /var/run/bumblebee.socket
[20006.644955] [DEBUG] pidfile: /var/run/bumblebeed.pid
[20006.644966] [DEBUG] xorg.conf file: /nix/store/9c8s0lkjh4yfhbl0qi84z5wkx8855rbv-bumblebee-3.2.1/etc/bumblebee/xorg.conf.nouveau
[20006.644977] [DEBUG] xorg.conf.d dir: /nix/store/9c8s0lkjh4yfhbl0qi84z5wkx8855rbv-bumblebee-3.2.1/etc/bumblebee/xorg.conf.d
[20006.644989] [DEBUG] ModulePath:
[20006.644999] [DEBUG] GID name: wheel
[20006.645019] [DEBUG] Power method: auto
[20006.645030] [DEBUG] Stop X on exit: 1
[20006.645040] [DEBUG] Driver: nouveau
[20006.645051] [DEBUG] Driver module: nouveau
[20006.645061] [DEBUG] Card shutdown state: 1
[20006.645155] [DEBUG]Process modprobe started, PID 22527.
[20006.645204] [DEBUG]Hiding stderr for execution of modprobe
[20006.646217] [DEBUG]SIGCHILD received, but wait failed with No child processes
[20006.646244] [DEBUG]Configuration test passed.
[20006.646436] [INFO]/home/user1/.nix-profile/bin/bumblebeed 3.2.1 started
[20006.646593] [INFO]Switching dedicated card OFF [bbswitch]
[20006.657838] [INFO]Initialization completed - now handling client requests
[20020.154310] [DEBUG]Accepted new connection
[20020.154518] [INFO]Switching dedicated card ON [bbswitch]
[20020.566545] [INFO]Loading driver nouveau (module nouveau)
[20020.566648] [DEBUG]Process modprobe started, PID 22590.
[20021.170827] [DEBUG]Process with PID 22590 returned code 0
[20021.170912] [INFO]Starting X server on display :8.
[20021.170980] [DEBUG]Process Xorg started, PID 22606.
[20021.228051] [DEBUG]Process with PID 22606 returned code 1
[20021.228082] [ERROR][XORG] (EE)
[20021.228098] [DEBUG][XORG] Fatal server error:
[20021.228102] [ERROR][XORG] (EE) Cannot open log file "/nix/store/qx3axwkxlfqcmnykbniqdp1krr5w5xiz-xorg-server-1.17.4/var/log/Xorg.8.log"
[20021.228105] [ERROR][XORG] (EE)
[20021.228107] [ERROR][XORG] (EE)
[20021.228108] [DEBUG][XORG] Please consult the The X.Org Foundation support
[20021.228110] [DEBUG][XORG]     at http://wiki.x.org
[20021.228112] [DEBUG][XORG]  for help.
[20021.228114] [ERROR][XORG] (EE)
[20021.228116] [ERROR]X did not start properly
[20021.228177] [DEBUG]Socket closed.
```

**Comment by abbradar** [comment] 2015-12-09 09:00
Very strange but that's not quite what I wanted -- the patch above does not present in `master` and adds argument logging to the X server invocation. That way we'll see all the X server flags.

**Comment by abbradar** [comment] 2015-12-09 17:00
Have you managed to solve this?

**Comment by Szczyp** [comment] 2015-12-09 17:03
I thought the patch got applied because i put it into ```patches = [ ... ]``` in ```bumblebee/default.nix```. So now I'm trying to debug the patch application issue with nix-shell. When I manually ```patchPhase``` I get prompt to point to a file to patch because it can't find a patch target file.

sorry i accidentaly closed this issue

**Comment by Szczyp** [comment] 2015-12-09 17:04
I get this prompt even with nixos.patch.

**Comment by abbradar** [comment] 2015-12-09 17:06
Hm, it should have been applied if you put it in `patches`.

A wild guess -- do you have `nix.chroot` enabled? Maybe something interferes with the build and the patch is not applied correctly...

Also, you run `patchPhase` while being in the source root, correct?

**Comment by Szczyp** [comment] 2015-12-09 17:21
Ok when I'm in the source root patches got applied. Now I'm on the install phase. I can't ```sudo installPhase```. I tried to sudo initial ```nix-shell``` but then I'll need ```allowUnfree = true;``` in root? Is there some better way to do this?

**Comment by abbradar** [comment] 2015-12-09 17:23
You wouldn't be able to install things from `nix-shell`, even with `sudo`. If the patches got applied they should have been applied with `nix-build` too. I think I need to add more debugging information in the patch -- stay tuned.

**Comment by abbradar** [comment] 2015-12-09 17:34
http://lpaste.net/146803 try this one.

**Comment by Szczyp** [comment] 2015-12-09 17:49
This is what i got with ```buildPhase```.
```
src/bbrun.c: In function ‘bb_run_fork’:
src/bbrun.c:162:81: error: ‘ret’ undeclared (first use in this function)
     bb_log(LOG_DEBUG, "Process %s started via bb_run_fork, PID %i.\n", argv[0], ret);
                                                                                 ^
src/bbrun.c:162:81: note: each undeclared identifier is reported only once for each function it appears in
Makefile:577: recipe for target 'src/bbrun.o' failed
make: *** [src/bbrun.o] Error 1
```
When I use ```nix-env -f . -iA pkgs.bumblebee``` from nixpkgs source dir it builds and the error is the same as before.

**Comment by abbradar** [comment] 2015-12-09 17:51
Things are more and more cryptic -- I have clearly made a mistake in the patch, so the question is: why has `nix-env` suceeded?

I'll post the fix shortly. Meanwhile, please try to find the cause of `nix-env` succeeding.

**Comment by abbradar** [comment] 2015-12-09 17:52
(To clarify -- you have put my patch into `patches` in the `pkgs/tools/X11/bumblebee/default.nix`, correct?)

**Comment by Szczyp** [comment] 2015-12-09 17:56
yeah i put it there

I don't really know how to debug this ```nix-env``` issue. Can i just run the build output after ```buildPhase``` without installing?

**Comment by abbradar** [comment] 2015-12-09 17:57
We also need some `installPhase` hooks to work correctly, unfortunately.

What about `nix-build -A bumblebee`?

**Comment by Szczyp** [comment] 2015-12-09 18:00
Now it just returns the one in nix-store (```/nix/store/zanilc405wlbm365j03fvbmcmffynj4h-bumblebee-3.2.1```). How can i remove it from nix-store?

**Comment by abbradar** [comment] 2015-12-09 18:00
Aha! I've found the root of the problem!

**Comment by abbradar** [comment] 2015-12-09 18:00
(You can run `nix-collect-garbage` or `nix-store --delete`)

**Comment by abbradar** [comment] 2015-12-09 18:05
Closed by https://github.com/NixOS/nixpkgs/commit/67c109efe57012d41ad673e48f040be6a8e9977f

It was caused by a PR which have been merged without testing w.r.t. my recent changes. Please test, just in case.

**Closed by abbradar** 2015-12-09 18:05 UTC

**Comment by Szczyp** [comment] 2015-12-09 18:14
Tested. It solves the log issue.

**Comment by abbradar** [comment] 2015-12-09 18:15
Nice, thank you very much for helping!

**Comment by carldong** [comment] 2015-12-12 03:52
Do you know how long it usually takes to push into unstable?
