### ISSUE TITLE
Build failure: openmm

### ISSUE THREAD

**Issue by ryanswrt** [NixOS/nixpkgs#216577] opened 2023-02-16 03:03 UTC
### Steps To Reproduce

1. `nix build github:nixos/nixpkgs#openmm`
or 
1. `nix build github:nixos/nixpkgs/nixos-unstable#openmm`

### Build log

https://gist.github.com/ryanswrt/757f4b9e6fab558793c86da372437b1a

### Additional context

Still works around  fab09085df1b60d6a0870c8a89ce26d5a4a708c2 - but has been broken for at least 3 days in nixos-unstable

### Notify maintainers

@sheepforce 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[nix-shell -p nix-info --run "nix-info -m"                                                               feat/qscore-workflow * ] 10:59 AM
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.9-zen1, SnowflakeOS, 23.05 (Stoat), 23.05.20230204.0591d6b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(ryanswart): `"nixos, nixpkgs"`
 - nixpkgs: `/home/ryanswart/.nix-defexpr/channels/nixpkgs`
```

**Comment by sheepforce** [comment] 2023-02-20 14:16
OK, it is specifically cb572732360 that breaks it. Not too surprising, its the update from GCC 11 -> GCC 12. The best fix for the moment seems to be to use the GCC 11 until OpenCL and vectorisation problems are resolved. Very much to my surprise
```nix
openmm = callPackage ../development/libraries/science/chemistry/openmm {
    stdenv = gcc11Stdenv;
  };
```
(and all lower gccXStdenv versions) still give me the GCC 12. @markuskowa do you know why this does not work?

**Comment by markuskowa** [comment] 2023-02-20 16:00
It seems to be connected to the Fortran compiler. This works:
```
openmm = callPackage ../development/libraries/science/chemistry/openmm {
  gfortran = gfortran11;
 };
```

**Comment by ryanswrt** [comment] 2023-02-21 01:40
Good catch -  does it make sense to do a PR to fix it or investigate the failure upstream?

**Comment by sheepforce** [comment] 2023-02-21 09:53
> It seems to be connected to the Fortran compiler. This works:
> 
> ```
> openmm = callPackage ../development/libraries/science/chemistry/openmm {
>   gfortran = gfortran11;
>  };
> ```

Nice that this works. Still I am surprised, as using `clangStdenv` without replacing the gfortran was enough. However, gfortran also seems to include gcc and g++ in PATH. 

> Good catch - does it make sense to do a PR to fix it or investigate the failure upstream?

For now I will make a nixpkgs PR with the gfortran11 and gcc11Stdenv to get it working here again. I will try to reproduce this on Debian with the GCC12 to see if this is purely a Nix problem or not.

**Comment by markuskowa** [comment] 2023-02-21 10:14
>  However, gfortran also seems to include gcc and g++ in PATH.

This is probably a bug in the gfortran compiler wrappers? Pulling in gfortran should not override the c compiler from stdenv.

**Comment by sheepforce** [comment] 2023-02-21 10:16
Hm, I am pretty the gfortran wrapper does. Simply doing `nix shell nixpkgs#gfortran` gives me g++ and gcc. But I am afraid to touch anything involving the compiler wrappers in nixpkgs :sweat_smile:

**Comment by sheepforce** [comment] 2023-02-21 13:20
This even happens on Debian Sid with the GCC12 and OpenCL from the Debian repos. Thus, I would agree, this is probably an upstream bug. I am not sure whether this is a GCC bug or a OpenMM bug ... At least it also still happens on OpenMM's master branch.

**Comment by markuskowa** [comment] 2023-02-21 13:26
The build failure with GCC 12 is certainly an `openmm` upstream bug which, I assume, will be fixed sooner or later. 
However, the bug that gfortran overrides c compilers is most likely a problem on our end (probably in the compiler wrapper).

**Comment by sheepforce** [comment] 2023-02-21 13:29
> The build failure with GCC 12 is certainly an `openmm` upstream bug which

I am not sure about this one. clang and g++ < 12 works flawless and a vectorisation pass of g++ calls this an compiler bug itself.

**Closed** 2023-02-21 15:45 UTC
Labels: 0.kind: build failure
