### ISSUE TITLE
IBus input methods having no effect in GTK2

### ISSUE THREAD

**Issue by laMudri** [NixOS/nixpkgs#11558] opened 2015-12-08 17:42 UTC
I have IBus set up on NixOS 16.03.git.97ccbb9M as follows:

```
programs.ibus = {
  enable = true;
  plugins = [
    pkgs.ibus-anthy
  ];
};
```

It has worked with this configuration a few months ago, but stopped working. The daemon still runs, showing the tray icon and allowing me to select new input methods to use (including Anthy, and I also tested Modern Greek), and those settings affect the tray menu. However, there is no change to the input behaviour. I have tested in Firefox, Terminator, and LibreOffice, so it may not affect Qt.

My `/etc/nixos/configuration.nix` is [here](http://nixpaste.lbr.uno/AThzFDHA). The `programs.ibus.table` stuff is from my changes to include ibus-table (not working yet), but shouldn't affect other plugins. IBus was not working before I started this. I've tried commenting out the `xkbcomp` line, rebuilding, then restarting, but that didn't help.

There are no maintainers for the ibus package, but @gebner and @ericsagnes may be interested.

**Comment by ericsagnes** [comment] 2015-12-09 09:05
Ibus + anthy is working fine on my machine with unstable `16.03pre71289.7ae05ed (Emu)`.
I would like to test with the same version as yours, how can I get `16.03.git.97ccbb9M`?

**Comment by laMudri** [comment] 2015-12-10 00:41
Mine is a fairly recent clone of this repository. The issue has persisted over a few pulls, so getting something recent will probably be near enough.

**Comment by laMudri** [comment] 2015-12-17 12:51
@ericsagnes, Any more thoughts? Could you share your config?

**Comment by ericsagnes** [comment] 2015-12-18 00:58
I am on current unstable `16.03pre73316.93d8671 (Emu)` and the relevant `configuration.nix` part is:

```
  programs = {
    ibus.enable  = true;
    ibus.plugins = with pkgs; [ ibus-anthy ];
  };
```

I also have a few packageOverrides that are unrelated to ibus but needed to use the current unstable on my machine:

```
    packageOverrides = pkgs: rec {
      flashplayer = pkgs.stdenv.lib.overrideDerivation pkgs.flashplayer (oldAttrs: {
        name = "flashplayer-11.2.202.554";
        src  = pkgs.fetchurl {
          url    = "http://fpdownload.adobe.com/get/flashplayer/pdc/11.2.202.554/install_flash_player_11_linux.x86_64.tar.gz";
          sha256 = "15zziclffvsa0wpygkwzbh3v367n73pmzwsnkanhg75rv28dgl3x";
        };
      });
      signing-party = pkgs.stdenv.lib.overrideDerivation pkgs.signing-party (oldAttrs: {
        name = "signing-party-2.1";
        src  = pkgs.fetchurl {
          url    = "mirror://debian/pool/main/s/signing-party/signing-party_2.1.orig.tar.gz";
          sha256 = "0pcni3mf92503bqknwlsvv1f5gz23dmzwas2j8g2fk7afjd891ya";
        };
      });
    };
```

ibus requires `dconf` at runtime to save settings, so in case you don't have it, installing it could help.

You also can check that the environment variables are correctly set:

```
printenv | grep ibus
XMODIFIERS=@im=ibus
QT_IM_MODULE=ibus
GTK_IM_MODULE=ibus
IBUS_COMPONENT_PATH=/nix/store/1lr02jj1lgikdk4p46iq8ax6nfm2nq1q-ibus-env/share/ibus/component
```

Restarting the X11 session can sometimes help fix things.

**Comment by linquize** [comment] 2015-12-18 01:12
Any ibus based input method work?

**Comment by ericsagnes** [comment] 2015-12-18 01:29
@linquize `ibus-anthy` and `ibus-mozc` are working fine as far as I can tell.

Side-note: I currently work on improving the current state of input method by adding new engines to ibus and fcitx and making the module integration better in #11254.
Ibus based engines are a little tricky, and my current experience is that fcitx works better most of the time.

**Comment by laMudri** [comment] 2015-12-18 20:44
I have `dconf` installed for both root and user, but still nothing happens (even after rebooting). The `ibus` package does do proper [wrapping](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/inputmethods/ibus/default.nix#L33) these days, so that shouldn't be an issue.

I'll ask around the IBus people to see whether I can do any more troubleshooting.

**Comment by laMudri** [comment] 2015-12-19 11:41
Thanks to mfabian of ibus, I narrowed it down to being a GTK2 problem. IBus does work for me in xterm and gedit, but still not Firefox and Terminator. Starting Terminator _from a terminal emulator_ gives a relevant error message, then crashes:
```
$ terminator

** (process:27918): WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

** (process:27918): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

** (process:27918): WARNING **: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
/nix/store/xwxjqxrli9g0qk95rxiy1abn302b55w0-terminator-0.97/lib/python2.7/site-packages/terminatorlib/window.py:63: Warning: The property GtkWindow:allow-shrink is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.set_property('allow-shrink', True)

** (.terminator-wrapped:27918): WARNING **: Binding '<Shift><Control><Alt>a' failed!
Unable to bind hide_window key, another instance/window has it.
/nix/store/xwxjqxrli9g0qk95rxiy1abn302b55w0-terminator-0.97/lib/python2.7/site-packages/terminatorlib/window.py:384: GtkWarning: GModule (/nix/store/sz7dbblgaq7svw1qzs3z89bybbizrclb-gtk-exe-env/lib/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)
  self.present()
/nix/store/xwxjqxrli9g0qk95rxiy1abn302b55w0-terminator-0.97/lib/python2.7/site-packages/terminatorlib/window.py:384: GtkWarning: Loading IM context type 'ibus' failed
  self.present()
/nix/store/xwxjqxrli9g0qk95rxiy1abn302b55w0-terminator-0.97/bin/.terminator-wrapped:118: GtkWarning: GModule (/nix/store/sz7dbblgaq7svw1qzs3z89bybbizrclb-gtk-exe-env/lib/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)
  gtk.main()
/nix/store/xwxjqxrli9g0qk95rxiy1abn302b55w0-terminator-0.97/bin/.terminator-wrapped:118: GtkWarning: Loading IM context type 'ibus' failed
  gtk.main()
```

**Comment by ericsagnes** [comment] 2015-12-19 22:19
It seems that the `im-ibus.so` is using a too old version of `glib`.

Does `ldd /run/current-system/sw/lib/gtk-2.0/2.10.0/immodules/im-ibus.so | grep glib` gives any interesting information?

For reference, here is the result on a machine where `ibus` works well in terminator and firefox:

```
ldd /run/current-system/sw/lib/gtk-2.0/2.10.0/immodules/im-ibus.so | grep glib
        librt.so.1 => /nix/store/483br9kb3f5igsgmb6aqsjhl2ipj2bxr-glibc-2.21/lib/librt.so.1 (0x00007f3833bdb000)
        libgthread-2.0.so.0 => /nix/store/030k372iyg241a706dprvkibc9q8brzn-glib-2.46.2/lib/libgthread-2.0.so.0 (0x00007f3832ed4000)
        libm.so.6 => /nix/store/483br9kb3f5igsgmb6aqsjhl2ipj2bxr-glibc-2.21/lib/libm.so.6 (0x00007f3832023000)
        libgio-2.0.so.0 => /nix/store/030k372iyg241a706dprvkibc9q8brzn-glib-2.46.2/lib/libgio-2.0.so.0 (0x00007f38317f2000)
        libgmodule-2.0.so.0 => /nix/store/030k372iyg241a706dprvkibc9q8brzn-glib-2.46.2/lib/libgmodule-2.0.so.0 (0x00007f38315ee000)
        libdl.so.2 => /nix/store/483br9kb3f5igsgmb6aqsjhl2ipj2bxr-glibc-2.21/lib/libdl.so.2 (0x00007f38313ea000)
        libresolv.so.2 => /nix/store/483br9kb3f5igsgmb6aqsjhl2ipj2bxr-glibc-2.21/lib/libresolv.so.2 (0x00007f3830fba000)
        libgobject-2.0.so.0 => /nix/store/030k372iyg241a706dprvkibc9q8brzn-glib-2.46.2/lib/libgobject-2.0.so.0 (0x00007f3830d69000)
        libglib-2.0.so.0 => /nix/store/030k372iyg241a706dprvkibc9q8brzn-glib-2.46.2/lib/libglib-2.0.so.0 (0x00007f3830828000)
        libpthread.so.0 => /nix/store/483br9kb3f5igsgmb6aqsjhl2ipj2bxr-glibc-2.21/lib/libpthread.so.0 (0x00007f383060b000)
        libc.so.6 => /nix/store/483br9kb3f5igsgmb6aqsjhl2ipj2bxr-glibc-2.21/lib/libc.so.6 (0x00007f383026b000)
        /nix/store/483br9kb3f5igsgmb6aqsjhl2ipj2bxr-glibc-2.21/lib64/ld-linux-x86-64.so.2 (0x000055e08937b000)
```

**Comment by laMudri** [comment] 2015-12-19 22:30
I get the following output:
```
	librt.so.1 => /nix/store/483br9kb3f5igsgmb6aqsjhl2ipj2bxr-glibc-2.21/lib/librt.so.1 (0x00007f0a7dbe7000)
	libgthread-2.0.so.0 => /nix/store/030k372iyg241a706dprvkibc9q8brzn-glib-2.46.2/lib/libgthread-2.0.so.0 (0x00007f0a7cee0000)
	libm.so.6 => /nix/store/483br9kb3f5igsgmb6aqsjhl2ipj2bxr-glibc-2.21/lib/libm.so.6 (0x00007f0a7c02f000)
	libgio-2.0.so.0 => /nix/store/030k372iyg241a706dprvkibc9q8brzn-glib-2.46.2/lib/libgio-2.0.so.0 (0x00007f0a7b7fe000)
	libgmodule-2.0.so.0 => /nix/store/030k372iyg241a706dprvkibc9q8brzn-glib-2.46.2/lib/libgmodule-2.0.so.0 (0x00007f0a7b5fa000)
	libdl.so.2 => /nix/store/483br9kb3f5igsgmb6aqsjhl2ipj2bxr-glibc-2.21/lib/libdl.so.2 (0x00007f0a7b3f6000)
	libresolv.so.2 => /nix/store/483br9kb3f5igsgmb6aqsjhl2ipj2bxr-glibc-2.21/lib/libresolv.so.2 (0x00007f0a7afc6000)
	libgobject-2.0.so.0 => /nix/store/030k372iyg241a706dprvkibc9q8brzn-glib-2.46.2/lib/libgobject-2.0.so.0 (0x00007f0a7ad75000)
	libglib-2.0.so.0 => /nix/store/030k372iyg241a706dprvkibc9q8brzn-glib-2.46.2/lib/libglib-2.0.so.0 (0x00007f0a7a834000)
	libpthread.so.0 => /nix/store/483br9kb3f5igsgmb6aqsjhl2ipj2bxr-glibc-2.21/lib/libpthread.so.0 (0x00007f0a7a617000)
	libc.so.6 => /nix/store/483br9kb3f5igsgmb6aqsjhl2ipj2bxr-glibc-2.21/lib/libc.so.6 (0x00007f0a7a277000)
	/nix/store/qlxp7vb63fp8kx5vk9a0y3rj8svbvl27-glibc-2.21/lib64/ld-linux-x86-64.so.2 (0x00005579ed57f000)
```
It's completely identical, except for the last line.

**Comment by laMudri** [comment] 2016-01-11 21:54
IBus has miraculously started working in Firefox and nothing else using GTK2. I took a look at things, and it could well be a `glib` mismatch causing problems. Using `nix-store -q --requisites`, I found the following:

```
executable                | glib package
--------------------------|-------------
ibus                      | 6qbv9vdygxwzwhcbw1kimd76vhl6hiv6-glib-2.46.2
firefox (working)         | 6qbv9vdygxwzwhcbw1kimd76vhl6hiv6-glib-2.46.2
thunderbird (not working) | zy7xi64lsmnx0i0d0h8qgqigs4m85crc-glib-2.44.1
terminator (not working)  | k70hhnsrz47la5201gwfnqn9g357avza-glib-2.44.0
```

After doing that table, I reïnstalled thunderbird. That made it use the `6qbv...-glib-2.46.2` package, and IBus indeed started working in it.

I think I understand why this happens, and keeping up with unstable releases probably exacerbates the issue. Ideally, it shouldn't happen, but I don't think Nix has any way to fix it (almost by design). It may have to be part of the `ibus` installation instructions to reïnstall any applications in which it doesn't work.

**Comment by khumba** [comment] 2016-08-06 20:27
I have the same IBus configuration in my system config.  I have the following in my .xinitrc before starting Openbox:

    export XMODIFIERS="@im=ibus"
    export GTK_IM_MODULE="ibus"
    export QT_IM_MODULE="ibus"

Emacs (GTK2), urxvt (no toolkit), Tagainijisho (Qt) all recognize the current input method; Firefox (GTK2), Chromium (GTK2), Terminator (GTK2), gedit (GTK3) don't.  But I get:

    $ nix-store -qR $(readlink -f $(type -p $PKG)) | grep -e -glib-
    /nix/store/r22zqk5frxb7ysp163gvh90vl9mp5s2f-glib-2.46.2

for all of the above packages, and I don't see the "GLib too old" messages.  On NixOS, release-16.03.

**Comment by laMudri** [comment] 2016-08-06 21:04
There is another IBus issue open at the moment (#17277), though my copy of IBus is currently working fine (I don't use Gnome either). At first glance, your problem seems to be the same as neither of these, which is a little unsettling. Have you had IBus working before?

**Comment by khumba** [comment] 2016-08-06 21:10
I saw that one too, but chose to comment here because yes, not using Gnome, and also `nixos-option i18n.inputMethod.package` comes back empty for me.  The IBus binaries in my path are from `ibus-with-plugins` (though I don't know if that's a sufficient condition).

This same configuration works fully for me on Gentoo, but I haven't had it working fully on NixOS.

**Comment by laMudri** [comment] 2016-08-06 21:17
Could you post your `/etc/nixos/configuration.nix`? Also, I don't remember whether the big changes to input method configuration happened before or after 16.03, so I'll look that up.

**Comment by ericsagnes** [comment] 2016-08-06 23:23
@khumba I think you are facing #14019.

To summarize the problem, gtk has a cache for input mrthods set by a env var `GTK_IM_MODULE_FILE`, that can work only with one GTK version at a time, so we have a patched version of GTK2 and GTK3 to look in `NIX_PROFILE` for a special cache file (`/etc/gtk-{2,3}.0/immodules.cache`).

The fix for this, #14568, is in unstable but not in 16.03. (ibus module is present in 16.03).
Using the ibus module from unstable should fix the problem.

**Comment by khumba** [comment] 2016-08-07 18:37
Yeah, that makes sense, thanks.  When I switch to staging, IBus starts, but when I try to activate Anthy via the tray applet, it fails with the warning below, and EN stays active.  I couldn't see where this was actually being written to; there were no relevant IBus or Anthy messages in `journalctl`, `journalctl --user`, `.xsession-errors`.  I'm starting IBus with `ibus-daemon -d -x`.  My NixOS configuration is [here](http://khumba.net/tmp2/nixos.tar.bz2).

    $ strace -p $(pidof ibus-ui-gtk3) -s 1000
    ...lots of garbage...
    futex(0x2655030, FUTEX_WAKE_PRIVATE, 1) = 1
    futex(0x265d1a0, FUTEX_WAKE_PRIVATE, 1) = 1
    futex(0x261b278, FUTEX_WAKE_PRIVATE, 1) = 1
    poll([{fd=12, events=POLLIN}], 1, 16000) = 1 ([{fd=12, revents=POLLIN}])
    poll([{fd=12, events=POLLIN}], 1, 16000) = 1 ([{fd=12, revents=POLLIN}])
    read(12, "\1\0\0\0\0\0\0\0", 16)        = 8
    poll([{fd=12, events=POLLIN}], 1, 16000
    
    * LONG PAUSE HERE *
    
    ) = 1 ([{fd=12, revents=POLLIN}])
    read(12, "\1\0\0\0\0\0\0\0", 16)        = 8
    write(12, "\1\0\0\0\0\0\0\0", 8)        = 8
    futex(0x27ef420, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    close(12)                               = 0
    write(2, "\n(ibus-ui-gtk3:1676): IBUS-WARNING **: ibus_bus_call_sync: org.freedesktop.IBus.SetGlobalEngine: GDBus.Error:org.freedesktop.DBus.Error.Failed: Set global engine failed: Timeout was reached\n", 190) = 190
    write(2, "\n(ibus-ui-gtk3:1676): IBUS-WARNING **: panel.vala:812: Switch engine to anthy failed.\n", 86) = 86
    recvmsg(3, 0x7ffd19ee3200, 0)           = -1 EAGAIN (Resource temporarily unavailable)

**Comment by ericsagnes** [comment] 2016-08-07 23:37
Does starting ibus with `ibus-daemon -d -x --cache=refresh` changes something?

**Comment by Profpatsch** [comment] 2018-06-23 23:54
(triage) what’s the current status?

**Comment by laMudri** [comment] 2018-06-24 14:56
I think the conclusion is https://github.com/NixOS/nixpkgs/issues/11558#issuecomment-170702789. The solution is probably to explain it somewhere in the (NixOS?) manual.

**Comment by Profpatsch** [comment] 2018-06-24 17:01
@laMudri are you interested in preparing a tab?

**Comment by laMudri** [comment] 2018-06-24 20:14
Could do. I've never worked on the manual before, but I'll have a look.

**Comment by evanjs** [comment] 2020-01-08 01:32
Outside of needing `ibus-setup` and all the other non-declarative stuff right now...
This seems to work fine for me.

Language tested: Japanese (Hiragana)
Apps tested:
LibreOffice, Chromium, GitKraken, GtkPerf (gtk2), Firefox, Kitty (https://github.com/kovidgoyal/kitty/issues/469#issuecomment-419406438).

[This](https://github.com/evanjs/nixos_cfg/blob/3beba9b17031f0da7b55c603d1de903d3e34b2c3/modules/i18n/ibus.nix) is all I have in terms of ibus configuration at the moment.

Happy to test any other applications or languages, or have any of this confirmed by other ibus users.

```
- system: `"x86_64-linux"`
 - host os: `Linux 5.4.8, NixOS, 19.09.1778.db3e8325a9b (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-19.09.1778.db3e8325a9b"`
 - channels(evanjs): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Closed** 2020-01-10 12:23 UTC
