### ISSUE TITLE
Zoom Workspace no longer works after 24.05 upgrade

### ISSUE THREAD

**Issue by godexsoft** [NixOS/nixpkgs#329389] opened 2024-07-23 12:01 UTC
### Describe the bug
Zoom does no longer start after upgrading to 24.05.

### Steps To Reproduce
Simply including the `zoom-us` pkg from either stable or unstable does no longer work on my machine.

### Expected behavior
Tha application should work on any machine.

### Additional context
While Zoom does not produce any output to stdout, it does create a log file. Here are the relevant lines: 
```
   1   │ ZoomLauncher started.
   2   │ Zoom path is: /nix/store/gfch2yy2j0fazxkdnsgcd77byl1bsx3b-zoom-6.1.1.443/opt/zoom
   3   │ cmd line:
   4   │ Start subprocess: /nix/store/gfch2yy2j0fazxkdnsgcd77byl1bsx3b-zoom-6.1.1.443/opt/zoom/zoom sucessfully,  process pid:
       │  29495
   5   │ No PulseAudio daemon running, or not running as session daemon.
   6   │                              Class      App      Lib Possible Culprit Flags
   7   │                 resip::Connection      656      656
   8   │                       resip::Data       36       36
   9   │                  resip::DnsResult     1080     1080
  10   │                    resip::Headers        1        1
  11   │           resip::MsgHeaderScanner       40       40
  12   │                 resip::SipMessage     5224     5224
  13   │          resip::TransportSelector      896      896
  14   │                      resip::Tuple      128      128
  15   │               resip::UdpTransport     1144     1144
  16   │           resip::GenericIPAddress       28       28
  17   │
  18   │ zoom started.
  19   │ Client: Breakpad is using Single Client Mode! client fd = -1
  20   │ qt.qpa.xcb: could not connect to display :0
  21   │ qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
  22   │ This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may
       │  fix this problem.
  23   │
  24   │ Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xc
       │ omposite-egl, wayland-xcomposite-glx, xcb.
  25   │
  26   │ zoom was exited due to a handled signal: 11
  27   │ ZoomLauncher exit.
```

I'm on Hyprland so i'm not sure why it does not use the `wayland` plugin already but i can't seem to select the plugin with any `QT_*` env variables that i was able to google.

I also tried from both stable and unstable and the result is the same. I'd imagine it's a misconfiguration on my system (and it still may be) but the same config was working great for 23.11 and stopped working after upgrading to 24.05 hence the bug report. Any help is welcome though! :bow: 

### Notify maintainers

@danbst @tadfisher 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.40, NixOS, 24.05 (Uakari), 24.05.20240717.c716603`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/sj9yrq21wbbfr5715hys3laa2qd6x471-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-07-23 12:13
duplicate of #322970

**Comment by eclairevoyant** [comment] 2024-07-23 12:14
whoops that was about screeesharing, guess this is distinct

**Closed by eclairevoyant** 2024-07-23 12:13 UTC
Labels: 0.kind: bug
