### ISSUE TITLE
nixos-unstable channel hasn't updated in over a month

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#7083] opened 2015-03-30 11:24 UTC
The `nixos-unstable` channel is at a869c8351cfcd6ec42147e7f1c8f4f14ac20e587, a commit from Feb 23th. The `nixos-unstable-small` channel is at a00e19ceb96ed8ae2910b009c1ed79dff7167517, which was committed on March 6th.

**Comment by edwtjo** [comment] 2015-03-30 11:36
What would be the best way to help the nixos channel move forward?

**Comment by domenkozar** [comment] 2015-03-30 16:42
I've canceled staging jobs for now. Once 4600 jobs are built and nixos tests pass again, hopefully we'll have a channel update.

**Comment by domenkozar** [comment] 2015-03-31 08:24
Last bit missing is the cups test: http://hydra.nixos.org/build/20935181/log/raw

Cups systemd service was recently renamed, so maybe that's the reason for failure

**Comment by vcunat** [comment] 2015-03-31 08:49
No, the logs show the service starts fine and lots of tests succeed, but then there's an unreadable error (to me)
```
error: Died at (eval 13) line 21, <__ANONIO__> line 254.
```
.

**Comment by domenkozar** [comment] 2015-03-31 08:50
@lethalman is testing the revert of https://github.com/NixOS/nixpkgs/commit/032859faba7174ef69f96b53bc07d544fba5e871

**Comment by geerds** [comment] 2015-03-31 09:10
@lethalman I've already fixed the cups rename issue: 164dbfff80e7d314a68b845ca4183dd485a26685

**Comment by domenkozar** [comment] 2015-03-31 09:27
So the last bit missing is reverting https://github.com/NixOS/nixpkgs/commit/032859faba7174ef69f96b53bc07d544fba5e871

**Comment by domenkozar** [comment] 2015-04-05 10:06
Current tests failures show two problems:

- simple installer test is failing, but I'm unable to reproduce locally
- all installer tests are failing on 32bit linux and I'm able to reproduce.

Running `nix-build nixos/tests/installer.nix -A swraid --option extra-binary-caches http://hydra.nixos.org --argstr system i686-linux` should give you:

```machine# error checking the existence of http://tarballs.nixos.org/sha256/13029baw9kkyjgr7q3jccw2mz38amq7mmpr5p3bh775qawd1bisz:
machine# curl: (6) Couldn't resolve host 'tarballs.nixos.org'
machine# 
machine# trying http://xmlsoft.org/sources/libxslt-1.1.28.tar.gz
machine# Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.
machine# Warning: Transient problem: timeout Will retry in 2 seconds. 2 retries left.
machine# Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.
machine# curl: (6) Couldn't resolve host 'xmlsoft.org'
machine# error: cannot download libxslt-1.1.28.tar.gz from any mirror
```

**Comment by domenkozar** [comment] 2015-04-05 10:15
Simple test failures also appear on `release-14.12`, here is the diff between changes: https://github.com/NixOS/nixpkgs/compare/99bfc89a97c86db6180d9fc927eeef3d84f30a41...8515a124d1a42090fa41f4b5bfb0d59b8bc2e914

@edolstra thoughts?

**Comment by wkennington** [comment] 2015-04-05 21:49
Could it somehow be related to a problem like this?

https://github.com/NixOS/nix/commit/afa433e58c3fe6029660a43fdc2073c9d15b4210

**Comment by domenkozar** [comment] 2015-04-06 16:05
@wkennington yeah `simple` test failure is most probably related to Nix bump.

The rest of the installer tests (32 bit ones) are broken by https://github.com/NixOS/nixpkgs/commit/72c6afe9ec7584ca5eaa56450c492efa8ce5576a (according to git bisect)

**Comment by domenkozar** [comment] 2015-04-08 18:16
See https://github.com/NixOS/nixpkgs/issues/7252

**Comment by domenkozar** [comment] 2015-04-09 12:13
Last two evals passed `tested` job, closing.

http://hydra.nixos.org/job/nixos/trunk-combined/tested

**Comment by peti** [comment] 2015-04-10 08:59
http://hydra.nixos.org/job/nixos/trunk-combined/tested is broken again -- and still no `nixos-unstable` channel update in sight: https://github.com/NixOS/nixpkgs-channels/tree/nixos-unstable is still at February 12th.

**Comment by vcunat** [comment] 2015-04-10 09:28
I guess the channel didn't update because those evaluations with succeeding "tested" job have a pair of user-cancelled jobs (32-bit libreoffice).

**Comment by edolstra** [comment] 2015-04-10 10:16
There was a problem (since yesterday) with copying the release to nixos.org because its host key had changed. It's fixed now.

**Closed by edolstra** 2015-04-10 10:16 UTC
Labels: blocker, bug, nixos

**Comment by vcunat** [comment] 2015-04-10 10:41
Yes! :-) Thank you all!

**Comment by domenkozar** [comment] 2015-04-10 11:25
:cake:

**Comment by peti** [comment] 2015-04-10 11:57
Wow, a channel update! Very nice. :smile:
