### ISSUE TITLE
Build failure: sweethome3d.application

### ISSUE THREAD

**Issue by LamprosPitsillos** [NixOS/nixpkgs#296381] opened 2024-03-16 10:13 UTC
### Steps To Reproduce

1. build  `sweethome3d.application`

### Build log

```
Running phase: buildPhase
Buildfile: /build/SweetHome3D-7.2-src/build.xml

furniture:
    [mkdir] Created dir: /build/SweetHome3D-7.2-src/build
      [zip] Building zip: /build/SweetHome3D-7.2-src/build/Furniture.jar

textures:
      [zip] Building zip: /build/SweetHome3D-7.2-src/build/Textures.jar

help:
      [zip] Building zip: /build/SweetHome3D-7.2-src/build/Help.jar

BUILD SUCCESSFUL
Total time: 1 second
Buildfile: /build/SweetHome3D-7.2-src/build.xml

build:
     [echo] compiling Sweet Home 3D for Java 1.7 minimum version
    [mkdir] Created dir: /build/SweetHome3D-7.2-src/build/classes
    [javac] /build/SweetHome3D-7.2-src/build.xml:68: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 2 source files to /build/SweetHome3D-7.2-src/build/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 7
    [javac] error: Source option 7 is no longer supported. Use 8 or later.
    [javac] error: Target option 7 is no longer supported. Use 8 or later.

BUILD FAILED
/build/SweetHome3D-7.2-src/build.xml:68: Compile failed; see the compiler error output for details.

Total time: 0 seconds
```

### Notify maintainers

@edwtjo 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.21, NixOS, 24.05 (Uakari), 24.05.20240312.0ad13a6`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `not found`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TomaSajt** [comment] 2024-03-16 10:47
Java also fails to build `sweethome3d.textures-editor` and `sweethome3d.furniture-editor`

It seems like `jdk21`, the latest Java version does not support generating Java 7 compatible jars. This can be fixed by either locking the jdk version to something earlier, like `jdk17` (which is the previous LTS version) or by patching the ant buildfile to not target the older source versions.

**Comment by eclairevoyant** [comment] 2024-03-16 11:15
duplicate of #295277

**Closed** 2024-03-20 23:06 UTC
Labels: 0.kind: build failure
