### ISSUE TITLE
Gnuradio 3.8 installation not detecting other installed gr-packages

### ISSUE THREAD

**Issue by dbusan** [NixOS/nixpkgs#139334] opened 2021-09-24 16:01 UTC
### Describe the bug
I am having trouble running gnuradio3_8 with support for available extra packages. Not sure if I am doing something wrong. I tried on Ubuntu 20.04 under WSL2. I also tried on a fresh Ubuntu 20.04 VM running inside Vmware player with the same results.

```nix-env -iA nixpkgs.gnuradio3_8 nixpkgs.gnuradio3_8.pkgs.limesdr``` installs successfully and I can successfully run gnuradio, however I cannot see the limesdr sink/source blocks. It seems that the GRC_BLOCKS_PATH is missing the other store paths where the plugins are installed because it only looks for blocks in one location:

```gnuradio-companion
<<< Welcome to GNU Radio Companion 3.8.3.1 >>>
Block paths:
/nix/store/r5imq1hzdcvw19i31234xv01ncsa94nf-gnuradio-3.8.3.1/share/gnuradio/grc/blocks
```

### Steps To Reproduce
1. install gnuradio3.8 and limesdr with ```nix-env -iA nixpkgs.gnuradio3_8 nixpkgs.gnuradio3_8.pkgs.limesdr```
2. run gnuradio-companion
3. limesdr sink/sources are missing

### Expected behavior
Expected to see additional installed packages.

### Additional context
I also tried installing all packages with ```nix-env -iA nixpkgs.gnuradio3_8.pkgs``` but that doesn't run at all. Attempting to run gnuradio-companion fails with the error message ```Cannot import gnuradio```.

### Notify maintainers
@doronbehar @bjornfor @fpletz 

#### Ubuntu 20.04 WSL2 metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
- host os: `Linux 5.10.16.3-microsoft-standard-WSL2, Ubuntu, 20.04.3 LTS (Focal Fossa)`
- multi-user?: `no`
- sandbox: `yes`
- version: `nix-env (Nix) 2.3.15`
- channels(user): `"nixpkgs-21.11pre317666.1a56d76d718"`
- nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`  
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: gnuradio3_8
# a list of nixos modules affected by the problem
module:
```

**Comment by bjornfor** [comment] 2021-09-24 18:14
Hi. I think this is by design and that the way to install gnuradio with extra blocks is to use something like this:

```
  environment.systemPackages = with pkgs; [
    (gnuradio.override {
      extraPackages = with gnuradio.pkgs; [
        # ais is broken for GR3.9
        #ais
      ];
    })
  ];
```

(From my /etc/nixos/configuration.nix.)

That being said, I also have this snippet in my config:

```
  # Uncomment to compose environments imperatively with nix-env
  #environment.profileRelativeEnvVars = {
  #  GRC_BLOCKS_PATH = [ "/share/gnuradio/grc/blocks" ];
  #};
```

It's been years since I used gnuradio, other people might have better/more input.

**Comment by doronbehar** [comment] 2021-09-24 22:35
I'm not sure how it'll be most comfortable for you on Ubuntu WSL to do this, but you will need an expression like in @bjornfor's comment. Note the difference - what you did was installing two packages but you did not make `gnuradio` aware of the other package[1], with `gnuradio.override { extraPackages = [];}` you create a derivation of gnuradio that has `GRC_BLOCKS_PATH` set properly.

[1]: It's an unintuitive behavior people new to the Nix world are surprised to confront.

`nix-env` is deprecated in favor of declarative ways to install packages for your system, such as [home-manager](https://nix-community.github.io/home-manager) which will allow you to write such an expression and install and update it with a command like `home-manager switch`.

I'd also consider using the new Nix command line interface of what we call `nixUnstable`. You can install it with:

https://github.com/numtide/nix-unstable-installer

And then install `gnuradio3_8` with the following command:

```
nix profile install --impure --expr 'with (import <nixpkgs>{}); gnuradio3_8.override { extraPackages = [ gnuradio3_8.pkgs.limesdr ]; }'
```

I think with `nix-env` you can also install that wrapped gnuradio3_8 derivation with (untested):

```
nix-env -f<nixpkgs> -E 'gnuradio3_8.override { extraPackages = [ gnuradio3_8.pkgs.limesdr ]; }'
```

**Comment by dbusan** [comment] 2021-09-25 01:35
@bjornfor thank you for your help. If I was using nix only (not nixOS), where would my configuration.nix file be located? I tried finding an answer on google, but I could not get a straight answer.

@doronbehar That is very helpful and insightful! You are correct, this is my first go at using nix at all.

I was able to successfully get gnuradio with limesdr installed after removing my old /nix installation and installing the **nix-unstable-installer**. I did have to create a ```~/.config/nix/nix.conf``` file and add ```experimental-features = nix-command ca-references``` inside it to get the above command to work within WSL2. 
For reference, I am using WSL2 with GWSL to run Gnuradio under windows, and whilst I cannot use the LimeSDR sink/source directly under there, I can use this technique to install other pkgs to work with Gnuradio. It is fairly straightforward to replace the LimeSDR source with a UDP source or something else and keep most of my flowgraphs the same.

Regarding the final mention:

> I think with `nix-env` you can also install that wrapped gnuradio3_8 derivation with (untested):
> 
> ```
> nix-env -f<nixpkgs> -E 'gnuradio3_8.override { extraPackages = [ gnuradio3_8.pkgs.limesdr ]; }'
> ```

This is probably something of my doing, but this command fails with with the following error.

```@console
dbusan@ubuntu:~$ nix-env -f<nixpkgs> -E 'gnuradio3_8.override { extraPackages = [ gnuradio3_8.pkgs.limesdr ]; }'
bash: nixpkgs: No such file or directory
```

Finally, I will investigate home-manager as well; but from my perspective, using the **nix-unstable-installer** along with the proposed install command solved my issue.

Thank you for your help.

**Comment by Artturin** [comment] 2021-09-25 06:01
This may help https://nixos.org/manual/nixpkgs/stable/#sec-declarative-package-management

**Comment by doronbehar** [comment] 2021-09-25 06:14
>     bash: nixpkgs: No such file or directory

That might be due to `NIX_PATH` not set properly. For your setup I'd use:

```
export NIX_PATH="nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz"
```

Note that `nix-env` without `-f<nixpkgs>` uses `~/.nix-defexpr` regardless of `$NIX_PATH`.



> I cannot use the LimeSDR sink/source directly under there

If you install `gnuradio` with the `--expr` command, what does the `Block paths:` message says when you launch it?

**Comment by dbusan** [comment] 2021-09-26 00:03
@Artturin Thanks for that. 

@doronbehar in my WSL2 Ubuntu 20.04 installation, after installing the **nix-unstable-installer** and using 
```
nix profile install --impure --expr 'with (import <nixpkgs>{}); gnuradio3_8.override { extraPackages = [ gnuradio3_8.pkgs.limesdr ]; }'
```
to install gnuradio3_8 with limesdr, this is Block paths output when running gnuradio:
 
```@console
Block paths:
        /nix/store/bp671ncfjpkclrcqchkhfy6s9hdb73f3-gr-limesdr-3.0.1/share/gnuradio/grc/blocks
        /nix/store/r5imq1hzdcvw19i31234xv01ncsa94nf-gnuradio-3.8.3.1/share/gnuradio/grc/blocks
```
So this is working as expected, as far as I understand.

Trying ```nix-env -f<nixpkgs> -E 'gnuradio3_8.override { extraPackages = [ gnuradio3_8.pkgs.limesdr ]; }'``` command on my Ubuntu 20.04 VM (which does not have the nix-unstable-installer), with NIX_PATH export outputs the same error.

```@console
dbusan@ubuntu:~$ env | grep NIX_PATH
NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz
dbusan@ubuntu:~$ nix-env --version
nix-env (Nix) 2.3.15
dbusan@ubuntu:~$ nix-env -f<nixpkgs> -E 'gnuradio3_8.override { extraPackages = [ gnuradio3_8.pkgs.limesdr ]; }'
bash: nixpkgs: No such file or directory```

**Comment by Artturin** [comment] 2021-09-26 00:05
its actually `-f 'nixpkgs>'`

**Comment by dbusan** [comment] 2021-09-26 00:22
Thanks @Artturin 

Attempting to run 
```
nix-env -f'<nixpkgs>' -E 'gnuradio3_8.override { extraPackages = [ gnuradio3_8.pkgs.limesdr ]; }'
``` 
on its own results in a ```no operation specified``` error. 
```@console
dbusan@ubuntu:~$ nix-env -f'<nixpkgs>' -E 'gnuradio3_8.override { extraPackages = [ gnuradio3_8.pkgs.limesdr ]; }'
error: no operation specified
```

Running:
```
nix-env -f'<nixpkgs>' -E 'gnuradio3_8.override { extraPackages = [ gnuradio3_8.pkgs.limesdr ]; }' -iA nixpkgs.gnuradio3_8 nixpkgs.gnuradio3_8.pkgs.limesdr
```
Results in a error about the override attribute. 
```@console
dbusan@ubuntu:~$ nix-env -f'<nixpkgs>' -E 'gnuradio3_8.override { extraPackages = [ gnuradio3_8.pkgs.limesdr ]; }' -iA nixpkgs.gnuradio3_8 nixpkgs.gnuradio3_8.pkgs.limesdr
error: attribute 'override { extraPackages = [ gnuradio3_8' in selection path 'gnuradio3_8.override { extraPackages = [ gnuradio3_8.pkgs.limesdr ]; }' not found
Try 'nix-env --help' for more information.
```

**Comment by doronbehar** [comment] 2021-09-26 12:38
> Running:
> 
> ```
> nix-env -f'<nixpkgs>' -E 'gnuradio3_8.override { extraPackages = [ gnuradio3_8.pkgs.limesdr ]; }' -iA nixpkgs.gnuradio3_8 nixpkgs.gnuradio3_8.pkgs.limesdr
> ```
> 
> Results in a error about the override attribute.

I'm not sure how to further help with `nix-env`. I don't use it at all and [it can't be tested](https://nixos.wiki/wiki/Nix_command/profile#Switching_between_nix-env_and_nix_profile) when unstable nix' profiles are enabled..

Anyway, it seems to me that the wrapper works as expected, so I'll close this issue with your permission @dbusan . Feel free to ask for more help here or in the forums.

**Closed by doronbehar** 2021-09-26 12:38 UTC
Labels: 0.kind: bug, 0.kind: question
