### ISSUE TITLE
ckb: currently broken due to recent Qt5 changes

### ISSUE THREAD

**Issue by kierdavis** [NixOS/nixpkgs#30519] opened 2017-10-17 18:18 UTC
## Issue description

`ckb` currently fails on startup with the following message:

    This application failed to start because it could not find or load the Qt platform plugin "xcb" in "".

    Reinstalling the application may fix this problem.

I believe it's looking for `libqxcb.so`, which is currently located at `/nix/store/kgvmhibzszc84p2ddzbhhsw54pdb8awh-qtbase-5.9.2-bin/lib/qt-5.9/plugins/platforms/libqxcb.so`.

`git bisect` revealed that this problem has been present since commit 6fa41788be7e020b5e551f7b89601cad2c277b12.

I've not been keeping up with the recent changes to Qt5 - **what's the most canonical way to fix this and allow `ckb` to find the `xcb` plugin again?**

### Steps to reproduce

    cd <nixpkgs>
    nix-build -A ckb
    result/bin/ckb

## Technical details

* System: 17.03.1862.ea06690f1f (Gorilla)
* Nix version: 1.11.14
* Nixpkgs version: master as of the time of writing (b304695c7fe616fa29f845af7597d4b419330b64)
* Sandboxing enabled: no

**Comment by NickHu** [comment] 2017-10-23 13:52
This seems to be the same issue as #30713

**Comment by kierdavis** [comment] 2017-10-28 12:37
cc Qt5.9 maintainers: @qknight @ttuegel @periklis

**Comment by yegortimoshenko** [comment] 2017-10-31 19:47
Can't reproduce:

* System: 18.03pre118631.66b63d2f5a (Impala)
* Nix version: 1.11.15
* Nixpkgs version: e2edccae47dc4972ec16bdeb6eb5374f7631fea8
* Sandboxing enabled: yes

**Comment by GallagherCommaJack** [comment] 2017-11-16 12:08
Reproduced with slightly different error:
`This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: minimal, offscreen, vnc, xcb, wayland-org.kde.kwin.qpa.

Reinstalling the application may fix this problem.`

- System: 17.09.2075.ac35504065 (Hummingbird)
- Nix version: 1.11.15
- Sandboxing enabled: no
(I would include nixpkgs version, but I don't actually know how to find that out)

**Comment by yegortimoshenko** [comment] 2017-11-16 13:11
@GallagherCommaJack Nixpkgs version is important in this case. Could you please run `nix-shell -p nix-info --run 'nix-info -m'`?

**Comment by GallagherCommaJack** [comment] 2017-11-16 21:24
Uh, this is the output from that command, both with and without `sudo`:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.61, NixOS, 17.09.2075.ac35504065 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(jack): `"unstable-18.03pre120398.aeff3080d0"`
 - channels(root): `"nixos-17.09.2075.ac35504065"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by GallagherCommaJack** [comment] 2017-11-16 21:46
Distressingly enough, this wasn't fixed by rolling back to a previous configuration built when I wasn't having this problem.

**Comment by kierdavis** [comment] 2017-11-17 00:39
After finally getting round to upgrading to 17.09, I can't reproduce anymore.

NixOS version: 17.09.2075.ac35504065 (Hummingbird)
Nix version: 1.11.15
nixpkgs version: ac35504065

Output of `nix-info -m`:

    - system: `"x86_64-linux"`
    - host os: `Linux 4.9.61, NixOS, 17.09.2075.ac35504065 (Hummingbird)`
    - multi-user?: `yes`
    - sandbox: `no`
    - version: `nix-env (Nix) 1.11.15`
    - channels(root): `"nixos-17.09.2075.ac35504065"`
    - channels(kier): `""`
    - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by kierdavis** [comment] 2017-11-17 00:52
I think I may have a lead.

I currently have (at least) two instances of ckb in my store: one built from nixpkgs ac35504065 as part of my NixOS build, and one built from nixpkgs master (963204e) just now. The former works fine, while the latter exhibits this issue. Comparing the contents of the store paths shows that the working one contains a file named `/nix/store/.../nix-support/propagated-native-build-inputs`, which contains a reference to `/nix/store/i1mgik5x2f8akjwhjcd0r62259s89592-qtbase-5.9.1-bin`. This is the package that contains `libqxcb.so`. The version of ckb that exhibits the missing plugin problem lacks this file, so I think it's very likely that this issue is caused by `qtbase-bin` not being recorded in the `nix-support/propagated-native-build-inputs` file.

The contents of `<nixpkgs>/pkgs/tools/misc/ckb/default.nix` are unchanged between these two versions of nixpkgs, so it seems this issue is due to a change elsewhere in nixpkgs. Now running a git bisect...

**Comment by orivej** [comment] 2017-11-17 01:28
> ```
> nix-build -A ckb
> result/bin/ckb
> ```
This may work, but currently it is not supported for Qt applications. Also the unfortunate best practice on NixOS is not to install Qt into the user profile either, so do not try `nix-env -iA ckb`, or use this workaround: https://github.com/NixOS/nixpkgs/issues/30551#issuecomment-343707838

**Comment by GallagherCommaJack** [comment] 2017-11-17 03:39
Weirdly enough, I've got it working if I try to launch it from `sudo su`.
If I run `sudo su`, then `nvim-qt` (another command having the same issue), it opens.
If I run the same binary from my user account, it can't find `xcb`.

**Comment by orivej** [comment] 2017-11-17 04:13
Likely there is a way to make `~/.nix-profile/lib/qt-5.9` disappear even when Qt is installed into the user env, but this may and likely will break Qt applications installed into the user env (unless system and user versions of Qt are exactly the same). Let's continue in #30551.

**Closed by orivej** 2017-11-17 04:13 UTC
