### ISSUE TITLE
Package request: GitButler

### ISSUE THREAD

**Issue by 4r7if3x** [NixOS/nixpkgs#348014] opened 2024-10-11 23:12 UTC
**Project description**

A Git client for simultaneous branches on top of your existing workflow.

**Metadata**

* homepage URL: https://gitbutler.com
* source URL: https://github.com/gitbutlerapp/gitbutler
* license: FSL-1.1-MIT
* platforms: linux, darwin, windows

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jfvillablanca** [comment] 2024-10-12 00:21
`gitbutler` is already available in `nixos-unstable`

**Comment by tomodachi94** [comment] 2024-10-12 04:06
Duplicate of #288567, and resolved already by #318101.

**Closed by tomodachi94** 2024-10-12 04:06 UTC
Labels: 0.kind: packaging request
