### ISSUE TITLE
Blender having GLX / OpenGL issue, won't launch.

### ISSUE THREAD

**Issue by thedaemon** [NixOS/nixpkgs#202907] opened 2022-11-25 20:34 UTC
### Describe the bug
Blender crashes after a clean install, says cannot find GLX extension. Blender (3d) doesn't run.

### Steps To Reproduce
1. Here is my history exactly.
2. 54  sh <(curl -L https://nixos.org/nix/install) --daemon
   55  nix-env -qaP blender
   56  nix-env -qaP blender
   57  nix-env -iA nixpkgs.blender
   58  cd /nix/store/70yxqrmbf3bxjnfn0pbpbfyh9r5y1vkw-blender-3.3.1/bin/
   60  ./blender
3. Error message:
clay@claydoh:/nix/store/70yxqrmbf3bxjnfn0pbpbfyh9r5y1vkw-blender-3.3.1/bin$ ./blender
Warning: Falling back to the standard locale ("C")
Read prefs: /home/clay/.config/blender/3.3/config/userpref.blend
intern/ghost/intern/GHOST_WindowX11.cpp:191: X11 glXChooseVisual() failed, verify working openGL system!
initial window could not find the GLX extension
Writing: /tmp/blender.crash.txt
Segmentation fault (core dumped)

### Expected behavior
Blender to run. I did this today.

**Comment by vcunat** [comment] 2022-11-25 20:49
OpenGL stuff in nixpkgs running on non-NixOS are... complicated.  I'm not really knowledgeable about that combination, but I've heard some people liking https://github.com/guibou/nixGL

**Comment by Artturin** [comment] 2022-11-28 11:58
Closing as a dupe of other non-nixos opengl issues

**Closed by Artturin** 2022-11-28 11:58 UTC
Labels: 0.kind: bug
