### ISSUE TITLE
asciidoctor-pdf not accessible

### ISSUE THREAD

**Issue by PierreR** [NixOS/nixpkgs#24293] opened 2017-03-24 15:26 UTC
## Issue description
After installing `asciidoctor` in `17.03`, the executable `asciidoctor-pdf` is not accessible anymore. Trying to use `asciidoctor -b pdf won't work either

### Steps to reproduce
`nix-env -i asciidoctor` 
-> asciidoctor-pdf -> not available

```
→ asciidoctor -b pdf README.adoc 
asciidoctor: FAILED: missing converter for backend 'pdf'. Processing aborted. (RuntimeError)
```

## Technical details

* System: 17.03beta582.1e8c017 (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: 17.03beta675.3a368d7

**Comment by globin** [comment] 2017-03-24 16:13
cc @gpyh

**Comment by globin** [comment] 2017-03-24 17:39
And ping @zimbatm who was working on ruby infrastructure last IIRC.

**Comment by 8573** [comment] 2017-03-25 06:25
`asciidoctor -r asciidoctor-pdf -b pdf <AsciiDoc file>` works for me
in `nix-shell -p asciidoctor`, though I don't know whether it's
supposed not to need the `-r asciidoctor-pdf`.

**Comment by gpyh** [comment] 2017-03-25 15:35
I have no idea why it does this. I'm going to investigate when I find some time.

**Comment by zimbatm** [comment] 2017-03-25 16:19
It's probably a change in behavior of asciidoctor, which has been upgraded, where the extension has to be loaded explicitly now. Either use `asciidoctor -r asciidoctor-pdf -b pdf` or `asciidoctor-pdf` instead.

**Comment by globin** [comment] 2017-03-25 16:21
@zimbatm but `asciidoctor-pdf` does not make it into `$out` only in `${ruby.gemPath}/bin` so it is not really accessible.

**Comment by fidergo-stephane-gourichon** [comment] 2018-02-05 15:19
# Context

Hello. I'm here considering a migration from python asciidoc that already has custom PDF style, vector-rendered graphviz diagrams in HTML and PDF.

Installed through ruby gems like this:

    gem install --user-install asciidoctor
    gem install --user-install asciidoctor-diagram
    gem install --user-install asciidoctor-pdf --pre

# Same quirks here

After trying a "hello world" document with default backend, since `asciidoctor --help` mentions `-b`, it's natural to do:

    asciidoctor -b pdf asciidoctor_diagram.asciidoc.txt

Alas this fails.
Finding this very issue on github allows to find these working alternatives:

    asciidoctor-pdf asciidoctor_diagram.asciidoc.txt
    asciidoctor -r asciidoctor-pdf -b pdf asciidoctor_diagram.asciidoc.txt

# What's the actual bug?

Is the first failure intended behavior?

If yes, the doc should be fixed.  I can provide patch and pull request.
If no, then the program should be fixed.

Fixing such gotchas should help other people following a similar path.

# Additional information

`asciidoctor --help` says "additional backends are supported via extensions (e.g., pdf, latex)".  Is this actually meant to be a hint to use `-r`?  Perhaps it could be made more explicit, like "add `-r asciidoctor-pdf` to command line" or similar. If that's the way to go, I can provide patch and pull request.

Thank you for your attention.

**Comment by zimbatm** [comment] 2018-02-09 14:44
wonderful report @fidergo-stephane-gourichon. inspired by your effort I created a fix at #34763

**Closed** 2018-02-09 15:59 UTC
