### ISSUE TITLE
Package request: Cerebro

### ISSUE THREAD

**Issue by mwalid207** [NixOS/nixpkgs#323299] opened 2024-06-29 03:22 UTC
**Project description**

Cerebro is an open-source launcher to improve your productivity and efficiency.

**Metadata**

* homepage URL: [www.cerebroapp.com/](https://www.cerebroapp.com/)
* source URL: https://github.com/cerebroapp/cerebro
* license: **MIT**
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment] 2024-06-29 03:44
duplicate of #214977

**Closed by eclairevoyant** 2024-06-29 03:44 UTC
Labels: 0.kind: packaging request
