### ISSUE TITLE
add Celeste 

### ISSUE THREAD

**Issue by gonzoknows** [NixOS/nixpkgs#215538] opened 2023-02-09 17:02 UTC
**Project description**

Celeste is a GUI file synchronization client that can connect to virtually any cloud provider.

-     Backed by [rclone](https://rclone.org/), giving you a reliable and battle-tested way to sync your files anywhere
-     Written with GTK4 and Libadwaita, giving Celeste a native look and feel on your desktop
-     Written in Rust, making Celeste blazingly fast to use

**Metadata**

* homepage URL: https://github.com/hwittenborn/celeste 
* source URL: https://github.com/hwittenborn/celeste
* license: gpl3.0
* platforms: unix, linux

**Comment by dit7ya** [comment] 2023-02-09 17:34
Closing as duplicate of https://github.com/NixOS/nixpkgs/issues/215322.

**Closed by dit7ya** 2023-02-09 17:34 UTC
Labels: 0.kind: packaging request
