### ISSUE TITLE
magick unable to access configure file

### ISSUE THREAD

**Issue by akgrant43** [NixOS/nixpkgs#353169] opened 2024-11-02 16:50 UTC
### Describe the bug

Executing:

```
magick -list configure
```

causes the error:

```
magick: unable to access configure file `configure.xml' @ warning/configure.c/GetConfigureOptions/722.
```

### Steps To Reproduce

Execute:

```
magick -list configure
```

### Expected behavior

`magick`  successfully writes values from `configure.xml`, e.g.:

```

Path: /nix/store/fazsxpmly5c9j7ijxn8pj43zr0nnhwls-imagemagick-7.1.1-39/share/ImageMagick-7/configure.xml

Name                  Value
-------------------------------------------------------------------------------
CC                    gcc
CFLAGS                -I/usr/include/libxml2    -I/usr/include/libraw  -I/usr/include/libpng16   -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libdrm -I/usr/include/harfbuzz  -I/usr/include/OpenEXR -pthread -I/usr/include/libdrm   -I/usr/include/openjpeg-2.2    -I/usr/include/freetype2 -I/usr/include/libpng16  -I/usr/include/freetype2 -I/usr/include/libpng16  -pthread     -fopenmp -g -O2 -Wall -mtune=sandybridge -fexceptions -pthread -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16
CODER_PATH            /usr/local/lib/ImageMagick-7.0.7/modules-Q16HDRI/coders
...
```

### Screenshots
N/A.

### Additional context

The following patch to the derivation fixes the problem, but I'm not sure this is the best fix:

```
$  git diff pkgs/applications/graphics/ImageMagick/default.nix
diff --git a/pkgs/applications/graphics/ImageMagick/default.nix b/pkgs/applications/graphics/ImageMagick/default.nix
index fd45ff16d257..4fdf8e005c1f 100644
--- a/pkgs/applications/graphics/ImageMagick/default.nix
+++ b/pkgs/applications/graphics/ImageMagick/default.nix
@@ -122,6 +122,7 @@ stdenv.mkDerivation (finalAttrs: {
     (cd "$dev/include" && ln -s ImageMagick* ImageMagick)
     moveToOutput "bin/*-config" "$dev"
     moveToOutput "lib/ImageMagick-*/config-Q16HDRI" "$dev" # includes configure params
+    cp $src/www/source/configure.xml $out/share/ImageMagick-*/
     for file in "$dev"/bin/*-config; do
       substituteInPlace "$file" --replace pkg-config \
         "PKG_CONFIG_PATH='$dev/lib/pkgconfig' '$(command -v $PKG_CONFIG)'"
```

I'm happy to provide a PR if this is correct.

### Notify maintainers

@dotlambda @rhendric @bloxx12

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.58, NixOS, 24.05 (Uakari), 24.05.20241030.080166c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/ylrrz211xgjzkcpyiafpq9y2yws7fyah-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bloxx12** [comment] 2024-11-02 18:20
Can reproduce on master, your patch works too.
This seems to be the same problem as in #82749.
A PR would be great! :)

**Comment by akgrant43** [comment] 2024-11-02 18:31
Huh, I did a search for similar issues and didn't see that, I probably didn't search far enough back.
Pr on the way...

**Comment by akgrant43** [comment] 2024-11-02 19:09
https://github.com/NixOS/nixpkgs/pull/353197

I tried to run the package tests as described at [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests), the first run produced a summary of 214 run, 20 skipped and 7 failed.  I then attempted to run the tests on the master branch to see if the number had increased, however it just printed the paths that were built.  What am I missing?

**Comment by dotlambda** [comment] 2024-11-02 21:05
duplicate of https://github.com/NixOS/nixpkgs/issues/82749

**Closed** 2024-11-02 21:05 UTC
Labels: 0.kind: bug
