### ISSUE TITLE
Package request: fastfetch

### ISSUE THREAD

**Issue by hervyqa** [NixOS/nixpkgs#221150] opened 2023-03-14 10:12 UTC
**Project description**

Fastfetch is a [neofetch](https://github.com/dylanaraps/neofetch)-like tool for fetching system information and displaying them in a pretty way. It is written mainly in C, with performance and customizability in mind. Currently, Linux, Android, FreeBSD, MacOS and Windows 7+ are supported.

**Metadata**

* homepage URL: https://github.com/LinusDierheimer/fastfetch
* source URL: https://github.com/LinusDierheimer/fastfetch/releases
* license: MIT license
* platforms: unix, linux, darwin.

**Comment by pinn3** [comment] 2023-03-14 11:48
Duplicate of https://github.com/NixOS/nixpkgs/issues/176799

**Comment by sogreatandpowerfull** [comment] 2023-03-14 14:25
@hervyqa FYI, It's available NUR: `nur.repos.vanilla.fastfetch`

**Closed** 2023-03-20 22:06 UTC
Labels: 0.kind: packaging request
