### ISSUE TITLE
lldb_16 errors with ModuleNotFoundError: No module named 'lldb'

### ISSUE THREAD

**Issue by mohnishkodnani** [NixOS/nixpkgs#232689] opened 2023-05-18 19:18 UTC
### Describe the bug
I am using a nix flake to install some build tools and lldb_16 is one of them. When I try to run the installed program I get the error. 
```
ModuleNotFoundError: No module named 'lldb'
```
Full output
```
❯ lldb -version
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lldb'
lldb version 16.0.1
```

### Steps To Reproduce
1. ❯ nix-shell -p lldb_16 --run "lldb -version"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lldb'
lldb version 16.0.1

### Expected behavior
No error for ModuleNotFoundError and just print the version info.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
these 2 paths will be fetched (0.01 MiB download, 0.11 MiB unpacked):
  /nix/store/l35qi8ycgi26b62wzxzpfgm1i7a6za0s-nix-info
  /nix/store/xrphcgmpj5kvh8gp2ni6vqlq07fpvl8j-DarwinTools-1
copying path '/nix/store/xrphcgmpj5kvh8gp2ni6vqlq07fpvl8j-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/l35qi8ycgi26b62wzxzpfgm1i7a6za0s-nix-info' from 'https://cache.nixos.org'...
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.4.0, macOS 13.3.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `""`
 - nixpkgs: `/nix/store/5v36rw1pmah970dyb7xgh7xd9pvxln05-source`
```

**Comment by wegank** [comment] 2023-05-20 00:20
Duplicate of #166604.

**Closed** 2024-01-04 10:00 UTC
Labels: 0.kind: bug
