### ISSUE TITLE
Heroic (legendary GUI frontend)

### ISSUE THREAD

**Issue by yangm97** [NixOS/nixpkgs#139561] opened 2021-09-26 19:25 UTC
**Project description**

Heroic is an Open Source Game Launcher for Linux, Windows and MacOS (Limited to Windows games using Wine/Crossover - tested only on Intel and on 10.14).
Right now it supports launching games from the Epic Games Store using [Legendary](https://github.com/derrod/legendary), a CLI alternative to the Epic Games Launcher.
Heroic is built with Web Technologies like: TypeScript, React, NodeJS and Electron.

**Metadata**

* homepage URL:
* source URL: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher
* license: gpl3
* platforms: linux

**Comment by OPNA2608** [comment] 2021-09-26 19:42
Duplicate of #109733

**Closed** 2021-09-26 22:16 UTC
Labels: 0.kind: packaging request
