### ISSUE TITLE
Rust Application Migration to fetchCargoTarball Implementation

### ISSUE THREAD

**Issue by bhipple** [NixOS/nixpkgs#79975] opened 2020-02-13 03:27 UTC
## What
We are making general infrastructure improvements to the cargo fetcher used to
produce the vendor package in Rust applications. This should not materially
change behavior, but will change the `cargoSha256`, so this is being rolled out
carefully to avoid disruption and merge conflicts.

## Motivation
Currently `fetchcargo` will pull all of the cargo vendor deps into a
`attr.cargoDeps` package with a recursive sha256 hash. We are migrating to a new
implementation that will compress the cargoDeps into a tar.gz archive that gets
unpacked at the start of the build. This has been implemented and merged in
#78501

The new implementation has several advantages:

1. It takes up significantly less space on disk in-between builds in the nix store.

2. It plays nicely with hashed mirrors like tarballs.nixos.org, which only
   substitute --flat hashes on single files (not recursive directory hashes).
   This is important for internal reproducibility and air-gapped builders.

3. It's significantly faster with distributed builders, because in that scenario
   the actual full src package is copied back and forth (unlike with a binary cache,
   where it's compressed). This can be very slow.

4. It's consistent with how simple fetchurl src derivations work.

5. It provides a stronger abstraction between input src-package and output
   package, e.g., it's harder to accidentally depend on the src derivation at
   runtime by referencing something like ${src}/etc/index.html. Moreover, in the
   store it's harder to get confused with something that is just there as a
   build-time dependency directory vs. an actual runtime package directory,
   since the build-time src dependencies are flat tarballs.

6. It ensures that if a `patchPhase` makes modifications to the `src`, the
   build/install must reference the patched sources in the build directory,
   rather than the original input src package. This prevents issues like #79575

## Additional Improvements
Changes to the `fetchcargo.nix` behavior that cause changes to the `cargoSha256`
are somewhat disruptive, so historically we've added conditionals to provide
backwards compatibility. We've now accumulated enough of these that it makes
sense to do a clean sweep updating hashes, and delete the conditionals in the
fetcher to simplify maintenance and implementation complexity. These
conditionals are:

1. When cargo vendors dependencies, it generates a config. Previously, we were
   hard-coding our own config, but this fails if there are git dependencies. We
   have conditional logic to sometimes copy the vendored cargo config in, and
   sometimes not.

2. When users update the src package, they may forget to update the
   `cargoSha256`. We have an opt-in conditional flag to add the `Cargo.lock`
   into the vendor dir for inspection and compare at build-time, which catches
   this mistake; but it defaults to false.

We will bring both of these features in as defaults in the new
`fetchCargoTarball` implementation.

## Migration Plan and Current Status

1. (DONE in #78501) Implement `fetchCargoTarball` as a separate, clean fetcher
   implementation along-side `fetchcargo`. Rename `verifyCargoDeps` (default
   false) to `legacyCargoFetcher` (default true), which switches the fetcher
   implementation used. Replace `verifyCargoDeps = true;` with
   `legacyCargoFetcher = false;` in Rust applications.

2. (DONE in #79978) Send a treewide Rust PR that sets `legacyCargoFetcher = true;` in all Rust
   applications not using this (which is ~200 of them), with a note to
   maintainers to delete if updating the package. Change the default in
   `buildRustPackage` to false.

3. (ABANDONED) Backport both (1) and (2) to 20.03 so that other Rust backports can be done without issue.  Note: per discussion below, we're not going to do this, and instead will just have maintainers re-compute the cargoSha256 when backporting Rust applications to 20.03. This will give it time to incubate and then sweep for 20.09.

4. (DONE) Go through all Rust src packages deleting the `legacyCargoFetcher = false;`
   line and re-computing the `cargoSha256`, merging as we go.

5. (PR #82901) Delete the `fetchcargo.nix` implementation entirely and all conditionals around it. Update the manual accordingly.

**Comment by bhipple** [comment] 2020-02-15 00:56
This introduced a bug in the legacy fetcher, as found by @Ma27 : previously, it had a step where it would explicitly run `chmod -R +w` on the vendor directory. I spot-checked ~20 out of the ~220 Rust applications and couldn't find one where this line did anything, and it's done by default in the newer fetcher's `unpackFile` hook, so I removed the line as a cleanup of "dead" code.  

Unfortunately, some Rust applications will run a custom build hook in cargo that writes to the vendor directory; these packages will fail without one of the following two fixes:

1. Upgrade to the new fetcher, which is now the default behavior unless the package opts-out.  This is preferred since we want to do this anyways for all packages.

2. Leave it broken on master and wait for the next staging -> master cycle that includes a systemic fix for the legacy cargo fetcher, at which point it will evaluate again.  (See #80153)

**Comment by bhipple** [comment] 2020-02-15 21:07
For anyone who's looking at bumping a package, no need to recompute the `cargoSha256` by hand; just use this script:

```bash
#!/usr/bin/env zsh
set -euo pipefail

# Helper script for migrating a NixPkgs Rust pkg to the new cargoSha256
# verification. Run from the root of a NixPkgs git checkout.
if [ -z "$1" ]; then
    echo "USAGE: $0 <attribute>"
    echo "EXAMPLE: $0 ripgrep"
    exit 1
fi

ATTR=$1
FNAME=$(EDITOR=ls nix edit -f . $ATTR)

section() {
    echo "********************************************************************************"
    echo "$ATTR: $1"
    echo "********************************************************************************"
}

main() {
    sed -i '/.*Delete this on next update.*/,/^$/d' $FNAME

    section "Nuking cargoSha256 reference for $FNAME, then rebuilding"
    sed -i 's|cargoSha256.*|cargoSha256 = "0000000000000000000000000000000000000000000000000000";|' $FNAME;
    nix-build -A $ATTR 2>&1 | tee /tmp/nix-rust-logfile-$ATTR || true
    actual=$(grep 'got:.*sha256:.*' /tmp/nix-rust-logfile-$ATTR | cut -d':' -f3-)
    echo "Build of $ATTR determined that cargoSha256 should be $actual"
    sed -i "s|cargoSha256.*|cargoSha256 = \"$actual\";|" $FNAME

    section "Rebuilding with updated hash, expecting a pass:"
    nix-build -A $ATTR || exit 1

    section "Finished successfully!"
}

main
```

**Comment by eraserhd** [comment] 2020-02-25 04:56
Removing `legacyCargoFetcher` and updating the `cargoSha256` for `pkgs/development/tools/parinfer-rust/default.nix` behaved weirdly.  On NixOS, it built successfully, but the same commit on MacOS  complained that the same hash is incorrect and tells me to enter all 1s to recompute it.  

When I do so, it suggests the hash I tried in the first place.  When I added the hash back, it built.  After it successfully built, I seem to be able to use it from the nix store without issues?

Is it possible there's something nondeterministic here?

See #81005

**Comment by jonringer** [comment] 2020-02-25 16:11
IIRC, mac can handle encoding differently. It's popped up a few times

**Comment by Ma27** [comment] 2020-02-25 19:11
I experienced the same issue when I was trying to update `pkgs.cargo-make` to [`0.28.0`](https://github.com/sagiegurari/cargo-make/releases/tag/0.28.0) on NixOS. @bhipple do you have an idea how this might be fixed (or have some pointers for me how to debug this)? Unfortunately I didn't have the time yet to take a closer look.

I'd like to mention though that I'm now pretty much against #79981 (backport of the fetchCargo-changes to 20.03) as we keep finding issues and I really think that we should leave this on nixos-unstable until 20.09 for further testing (please don't take this personally, I'm still in favor of the actual idea, I just think we should give it more time to stabilize on nixos-unstable).

**Comment by B4dM4n** [comment] 2020-02-25 21:08
The issue arises because in `pkgs/build-support/rust/default.nix` `validateCargoDeps` is checked during `postUnpack`, before the `cargoPatches` are applied.

This would have also happened with `fetchcargo`  and `verifyCargoDeps = true`.

Doing the `validateCargoDeps` check after `postPatch` fixes the issue:
```patch
diff --git a/pkgs/build-support/rust/default.nix b/pkgs/build-support/rust/default.nix
index 3fdfc0636f9..e13662eaefc 100644
--- a/pkgs/build-support/rust/default.nix
+++ b/pkgs/build-support/rust/default.nix
@@ -114,7 +114,9 @@ stdenv.mkDerivation (filteredArgs // {
     EOF

     export RUST_LOG=${logLevel}
-  '' + stdenv.lib.optionalString validateCargoDeps ''
+  ''+ (args.postUnpack or "");
+
+  postPatch = (args.postPatch or "") + stdenv.lib.optionalString validateCargoDeps ''
     if ! diff source/Cargo.lock $cargoDepsCopy/Cargo.lock ; then
       echo
       echo "ERROR: cargoSha256 is out of date"
@@ -131,7 +133,7 @@ stdenv.mkDerivation (filteredArgs // {
     fi
   '' + ''
     unset cargoDepsCopy
-  '' + (args.postUnpack or "");
+  '';

   configurePhase = args.configurePhase or ''
     runHook preConfigure
```

Tested with the `rink` crate after removing `legacyCargoFetcher`, but not further.

**Comment by bhipple** [comment] 2020-02-25 23:52
@B4dM4n / @Ma27 `cargo-make` and `rink` are both fixed by https://github.com/NixOS/nixpkgs/pull/80262, along with anything else that has custom patches or fetcher mutations for the Cargo.lock files.  It's been open for a week and a half, waiting for a merge.  I think it's good to go though as I've addressed all the PR feedback.

No offense taken; this doesn't need to get backported to 20.03, though that would mean that you'd have to set the fetcher to false and re-compute the cargoSha256 when cherry-picking any Rust application back to 20.03 from master.

**Comment by bhipple** [comment] 2020-02-26 00:03
@eraserhd does the package have unicode filenames?  You may be hitting https://github.com/NixOS/nix/issues/847, though that would impact you equally on either fetcher.  

I've seen this in the wild recently with https://github.com/NixOS/nixpkgs/pull/80583/files.  In that particular case, the non-ASCII filename that causes hash invalidations on MacOS happens to be in a test case, so we can just patch it away by deleting the test case filename without materially impacting the build.  If you find a non-ASCII filename that can't just be nuked like that, then unfortunately you'll have to do something like:

```nix
cargoSha256 = if stdenv.isDarin then "XXX" else "YYY";
```
(Again on either fetcher implementation, since it's an AFS issue for fixed-output derivations on Mac in general, unfortunately.)

**Comment by eraserhd** [comment] 2020-02-26 02:42
@bhipple There's no non-ASCII characters in filenames in the repo.  There's none in the Cargo.toml, either, although there could be transitive dependencies.  It seems like if there were non-ASCII characters, it wouldn't have worked the second time I tried (?).

**Comment by jonringer** [comment] 2020-02-26 03:01
> @B4dM4n / @Ma27 `cargo-make` and `rink` are both fixed by #80262, along with anything else that has custom patches or fetcher mutations for the Cargo.lock files. It's been open for a week and a half, waiting for a merge. I think it's good to go though as I've addressed all the PR feedback.

mass rustc rebuilds are tough to review. Rustc seems to mistake my RAM for an all-you-can-eat buffet, and proceeds to consume all of my 32GBs. Linux in a memory-starved environment doesn't handle it very well. Xserver essentially grinds to a halt, and certain processes begin to perform seppuku.

**Comment by bhipple** [comment] 2020-02-26 03:32
> It seems like if there were non-ASCII characters, it wouldn't have worked the second time I tried (?).

Indeed that's true, I was mainly just bringing this up because it's the one known deficiency of fixed-output derivations that has no clean solution on Mac.  

Did you see anything interesting in the build output, like Cargo failing or choking out on network access but somehow not killing the build?  What happens if you run `nix-store --delete` on the package and `cargoDeps` attribute and rebuild from scratch?  I've built these a few hundred times with Cargo on Linux and haven't noticed an issue yet, and we have some test cases and stripping logic to make Cargo deterministic, but if you have a way to reproduce this (your package worked first try on my machine) I'd be happy to dig into it.

**Comment by bhipple** [comment] 2020-02-28 02:35
@eraserhd I gave this a try and was successful:

```bash
for in in {1..5}; do nix-build -A parinfer-rust.cargoDeps --check || exit 1; done 
```
If you are able to reproduce the issue you saw, please do let me know, as mentioned above.  In the meantime, I'm sweeping forward the remaining PRs that can be done without https://github.com/NixOS/nixpkgs/pull/80262

**Comment by Profpatsch** [comment] 2020-02-28 17:49
It would be great if you could add a similar poison mechanism to what we are doing in https://github.com/NixOS/nixpkgs/pull/80953, so that cargo updates force the `cargoSha256` hashes to be changed.

**Comment by eraserhd** [comment] 2020-02-28 21:48
@bhipple I ran 10 times on Mac and 10 times on NixOS (parinfer-rust) with no problems.

**Comment by bhipple** [comment] 2020-02-29 01:42
> It would be great if you could add a similar poison mechanism to what we are doing in #80953, so that cargo updates force the `cargoSha256` hashes to be changed.

Interesting, we do in fact have some poisoning here: the `cargoSha256` will validate that its lockfile is in sync with `src`, and error out the build immediately if not.  This means there's no risk that you use the "wrong" fetcher with the "wrong" `cargoSha256`, because an attempt to do so will immediately result it an error like this that the `Cargo.lock` file is out of sync or cannot be found.  On this particular change, there's a second level of erroring, which is that the `cargoDeps` derivation is no longer a recursive hash and has a different `name`, just like in the Bazel poisoning.

One cautionary tale is that the reason a couple packages can't be updated yet (https://github.com/NixOS/nixpkgs/pull/80262) is that the poisoning mechanism itself has a bug for certain packages :)

I haven't been around in the Rust ecosystem long enough to have an idea if Cargo materially changes the vendor directory layout on updates, but if it does I'll look into adding a version poison on this.  That'd be really unfortunate, though, because having to change 200+ fixed output derivations is an expensive amount of churn :/

**Comment by jonringer** [comment] 2020-02-29 02:25
especially since rust builds are not light. If this were python packages, it would be significantly easier

**Comment by bluescreen303** [comment] 2020-02-29 14:18
my simple hello world example breaks because of this change and I'm forced to add `legacyCargoFetcher = true` for it to build. I did set `cargoSha256` to all `1`'s, wait for fail and copy the expected sha.

but then I get:
```
these derivations will be built:
  /nix/store/0xji5n7mdsjxw1n533hfrc3prlfs8mh6-hello-hello-0.1.0.drv
building '/nix/store/0xji5n7mdsjxw1n533hfrc3prlfs8mh6-hello-hello-0.1.0.drv'...
unpacking sources
unpacking source archive /nix/store/lrbh9rxl7bls08nkj2j8jgqvjc1yllja-foobar1
source root is foobar1
unpacking source archive /nix/store/09svapal9yq5mjnpi7r1dkxs2av5dxac-hello-hello-0.1.0-vendor.tar.gz
diff: source/Cargo.lock: No such file or directory

ERROR: cargoSha256 is out of date

Cargo.lock is not the same in hello-hello-0.1.0-vendor.tar.gz

To fix the issue:
1. Use "1111111111111111111111111111111111111111111111111111" as the cargoSha256 value
2. Build the derivation and wait it to fail with a hash mismatch
3. Copy the 'got: sha256:' value back into the cargoSha256 field

builder for '/nix/store/0xji5n7mdsjxw1n533hfrc3prlfs8mh6-hello-hello-0.1.0.drv' failed with exit code 1
error: build of '/nix/store/0xji5n7mdsjxw1n533hfrc3prlfs8mh6-hello-hello-0.1.0.drv' failed
```

here's my Cargo.toml:
```
[package]
name = "hello-hello"
version = "0.1.0"
edition = "2018"

[dependencies]

[[bin]]
path = "src/hello.rs"
name = "hello"

[[bin]]
path = "src/main.rs"
name = "inout"
```

and here's my Cargo.lock:
```
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
[[package]]
name = "hello-hello"
version = "0.1.0"
```

and finally default.nix:
```
{ pkgs ? import <nixpkgs> {}}:
pkgs.rustPlatform.buildRustPackage rec {
  name = "hello-hello-${version}";
  version = "0.1.0";

  src = ./.;

  cargoSha256 = "1nwid5bm5a2fx8jwf5yzslqa72kdbrxxqg7j7rv2q8dpn7qa05d3";
  # legacyCargoFetcher = true;
}
```

As stated, switching to the legacy fetcher and changing the sha works

**Comment by bhipple** [comment] 2020-02-29 15:06
That's the aforementioned poison pill bug, which is now fixed on the staging branch (https://github.com/NixOS/nixpkgs/pull/80262).  Until staging is merged to master, continuing to use the fetcher without the cargoSha256 validation is fine, but if you rebase onto staging it should work.  

The context here is that you have a fixed-output derivation for the `src`, and a fixed-output derivation for all the cargo vendor dependencies; when bumping to a new version, you could easily build the new src with the old dependencies.  So the new fetcher has validation that the two Cargo.lock files are in-sync and correspond to the same update.  

This worked on ~200/220 of the Rust packages, but the remainder had either patches to the lockfiles, no lockfiles at all, or different src directory layouts than the standards you'd get from pulling off github and crates.io, in which case the poison pill would incorrectly poison the build.  The version on staging is capable of handling all known scenarios, so if you give it a try and it doesn't work please do let me know.

**Comment by FlorianFranzen** [comment] 2020-03-06 16:19
It would probably also make sense to remove the comment in ```pkgs/build-support/rust/default.nix``` about this issue, as it is not only incorrect now but also refers to none existing documents.

**Comment by bhipple** [comment] 2020-03-10 22:46
We're now done with all of the update PRs!  Every package has either been upgraded on `master`, or has an open PR fixing/upgrading/removing it.

As of this writing, there are 12 open PRs left. The last couple Rust upgrades got really grindy as I encountered a handful of broken packages that have been abandoned upstream without commits for years; in these cases I sent PRs deleting the packages entirely.  In most other cases, we can fix the broken builds on master by just upgrading (as in, they had been broken for a long time, not related to this issue).

I think it probably makes sense to backport the new cargo fetcher implementation to 20.03 now. The main motivation in doing so would be to make it easier to backport Rust updates to 20.03, since right now a maintainer has to re-run the build to re-compute the `cargoSha256` after cherry-picking the commit from master to 20.03.  What do you think @ma27 @marsam @NixOS/backports ?

Note that this isn't a forced option; we can keep the old fetcher on 20.03 if we want to, it's just inconvenient for maintainers cherry-picking backport commits if we do so.

**Comment by 7c6f434c** [comment] 2020-03-11 05:56
>Note that this isn't a forced option; we can keep the old fetcher on 20.03 if we want to, it's just inconvenient for maintainers cherry-picking backport commits if we do so.

How inconvenient is mix-and-match, i.e. backporting the existence of the new fetcher and allowing maintainers to decide whether to migrate the backported packages for simpler backporting?

**Comment by Ma27** [comment] 2020-03-11 10:20
> We're now done with all of the update PRs! Every package has either been upgraded on master, or has an open PR fixing/upgrading/removing it.

First of all, thanks a lot for the effort!

> I think it probably makes sense to backport the new cargo fetcher implementation to 20.03 now. The main motivation in doing so would be to make it easier to backport Rust updates to 20.03, since right now a maintainer has to re-run the build to re-compute the cargoSha256 after cherry-picking the commit from master to 20.03.

As I stated previously, I'm a bit skeptical about backporting this already. The implementation is rather new and I'm afraid that we'll encounter further regressions that have to be fixed on stable branches as well. For now I think it's better to leave this on master to stabilize.

> Note that this isn't a forced option; we can keep the old fetcher on 20.03 if we want to, it's just inconvenient for maintainers cherry-picking backport commits if we do so.

I personally disagree here: this is not the first time where those fixed-output hashes need to be recomputed when backporting and IMHO every maintainer who backports patches should ensure that the hashes are correct.

Also, what if one of the next cargo versions we'll have on unstable changes some behavior that doesn't break anything, but will result in different hashes? (we had this issue about a year ago after a `cargo-vendor` update for instance).

**Comment by bhipple** [comment] 2020-03-11 21:41
> this is not the first time where those fixed-output hashes need to be recomputed when backporting and IMHO every maintainer who backports patches should ensure that the hashes are correct.

Ah ok, as long as maintainers are aware that they can't just cherry-pick-and-push.  If they go through a pull request and CI though it should fail safely, or if they try to build it.  This just takes ~5 minutes, which is a lot more than the ~30 seconds a cherry-pick may take, but in the grand scheme of things not a big deal. Let's leave it until 20.09 then; LMK if there's somewhere we should communicate this to maintainers for 20.03 backports, though it sounds like they're in the habit of checking this anyways.

> Also, what if one of the next cargo versions we'll have on unstable changes some behavior that doesn't break anything, but will result in different hashes? (we had this issue about a year ago after a cargo-vendor update for instance).

This is a big fear of mine, and would really suck. However, a lot of what this ticket is doing is making it easier to mirror / download / transfer the `cargoDeps` package *without* having to build it with Cargo itself.  Since it's no longer a recursive fixed-output derivation, it shows up in the content-addressed source tarball mirror https://tarballs.nixos.org, so even users who aren't using the binary cache can pick it up, and even users who aren't using the hashed mirror can just download the tar.gz file and put it into the store or on an FTP server.  

All of the above just reduces the blast radius and mitigates damage if Cargo screws us, though; it doesn't solve the root problem.  I'm hoping that Cargo is well-behaved enough that this never happens, or only happens once every couple years and is manageable ... is there a ticket about the cargo vendor update issues that I can check out to see how we've dealt with this in the past?

**Comment by Ma27** [comment] 2020-03-11 22:25
> This is a big fear of mine, and would really suck. However, a lot of what this ticket is doing is making it easier to mirror / download / transfer the cargoDeps package without having to build it with Cargo itself. Since it's no longer a recursive fixed-output derivation, it shows up in the content-addressed source tarball mirror https://tarballs.nixos.org, so even users who aren't using the binary cache can pick it up, and even users who aren't using the hashed mirror can just download the tar.gz file and put it into the store or on an FTP server.

That's true, I wanted to state something different: if cargo alters its behavior and we get different hashes, we'll have to regenerate our hashes again when backporting patches to release-20.03 even if your changes get backported now.

I mentioned this to demonstrate that we can't promise deterministic cargo-hashes between unstable and release which is why I don't consider it a benefit that with your stuff backported you wouldn't need to regenerate cargo-hashes at the moment.

> is there a ticket about the cargo vendor update issues that I can check out to see how we've dealt with this in the past?

For instance #60668. The "fix" was to update all hashes. This isn't a totally bad thing, but also shows that we can't guarantee that you don't have to recompute hashes when backporting.

**Comment by bhipple** [comment] 2020-03-17 20:42
There are just three uses of the legacy fetcher left:

- https://github.com/NixOS/nixpkgs/pull/80243
- https://github.com/NixOS/nixpkgs/pull/81994
- https://github.com/NixOS/nixpkgs/pull/82213

If someone could help with reviewing/merging, that'd be great.  Once those three are gone, we can proceed with the deletion of the legacy infra and complete this ticket!

**Closed** 2020-03-19 03:12 UTC
Labels: 6.topic: fetch, 6.topic: rust
