### ISSUE TITLE
python3Packages.beautifulsoup4 fails to build on Darwin

### ISSUE THREAD

**Issue by austinbutler** [NixOS/nixpkgs#137678] opened 2021-09-13 18:08 UTC
### Describe the bug

`python3Packages.beautifulsoup4` fails to build on Darwin.

### Steps To Reproduce

1. `nix-build -A python39Packages.beautifulsoup4`

### Expected behavior

Package builds.

### Additional context

<details>
<summary>Test failures</summary>

```
=================================== FAILURES ===================================
______________ LXMLTreeBuilderSmokeTest.test_real_hebrew_document ______________

self = <bs4.tests.test_lxml.LXMLTreeBuilderSmokeTest testMethod=test_real_hebrew_document>

    def test_real_hebrew_document(self):
        # A real-world test to make sure we can convert ISO-8859-9 (a
        # Hebrew encoding) to UTF-8.
        hebrew_document = b'<html><head><title>Hebrew (ISO 8859-8) in Visual Directionality</title></head><body><h1>Hebrew (ISO 8859-8) in Visual Directionality</h1>\xed\xe5\xec\xf9</body></html>'
>       soup = self.soup(
            hebrew_document, from_encoding="iso8859-8")

bs4/testing.py:813:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
bs4/testing.py:75: in soup
    return BeautifulSoup(markup, builder=builder, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self =
markup = b'<html><head><title>Hebrew (ISO 8859-8) in Visual Directionality</title></head><body><h1>Hebrew (ISO 8859-8) in Visual Directionality</h1>\xed\xe5\xec\xf9</body></html>'
features = None
builder = <bs4.builder._lxml.LXMLTreeBuilder object at 0x10c86d520>
parse_only = None, from_encoding = 'iso8859-8', exclude_encodings = None
element_classes = None, kwargs = {}
deprecated_argument = <function BeautifulSoup.__init__.<locals>.deprecated_argument at 0x10d734310>
original_builder = <class 'bs4.builder._lxml.LXMLTreeBuilder'>
original_features = None
builder_class = <class 'bs4.builder._lxml.LXMLTreeBuilder'>

    def __init__(self, markup="", features=None, builder=None,
                 parse_only=None, from_encoding=None, exclude_encodings=None,
                 element_classes=None, **kwargs):
        """Constructor.

        :param markup: A string or a file-like object representing
         markup to be parsed.

        :param features: Desirable features of the parser to be
         used. This may be the name of a specific parser ("lxml",
         "lxml-xml", "html.parser", or "html5lib") or it may be the
         type of markup to be used ("html", "html5", "xml"). It's
         recommended that you name a specific parser, so that
         Beautiful Soup gives you the same results across platforms
         and virtual environments.

        :param builder: A TreeBuilder subclass to instantiate (or
         instance to use) instead of looking one up based on
         `features`. You only need to use this if you've implemented a
         custom TreeBuilder.

        :param parse_only: A SoupStrainer. Only parts of the document
         matching the SoupStrainer will be considered. This is useful
         when parsing part of a document that would otherwise be too
         large to fit into memory.

        :param from_encoding: A string indicating the encoding of the
         document to be parsed. Pass this in if Beautiful Soup is
         guessing wrongly about the document's encoding.

        :param exclude_encodings: A list of strings indicating
         encodings known to be wrong. Pass this in if you don't know
         the document's encoding but you know Beautiful Soup's guess is
         wrong.

        :param element_classes: A dictionary mapping BeautifulSoup
         classes like Tag and NavigableString, to other classes you'd
         like to be instantiated instead as the parse tree is
         built. This is useful for subclassing Tag or NavigableString
         to modify default behavior.

        :param kwargs: For backwards compatibility purposes, the
         constructor accepts certain keyword arguments used in
         Beautiful Soup 3. None of these arguments do anything in
         Beautiful Soup 4; they will result in a warning and then be
         ignored.

         Apart from this, any keyword arguments passed into the
         BeautifulSoup constructor are propagated to the TreeBuilder
         constructor. This makes it possible to configure a
         TreeBuilder by passing in arguments, not just by saying which
         one to use.
        """
        if 'convertEntities' in kwargs:
            del kwargs['convertEntities']
            warnings.warn(
                "BS4 does not respect the convertEntities argument to the "
                "BeautifulSoup constructor. Entities are always converted "
                "to Unicode characters.")

        if 'markupMassage' in kwargs:
            del kwargs['markupMassage']
            warnings.warn(
                "BS4 does not respect the markupMassage argument to the "
                "BeautifulSoup constructor. The tree builder is responsible "
                "for any necessary markup massage.")

        if 'smartQuotesTo' in kwargs:
            del kwargs['smartQuotesTo']
            warnings.warn(
                "BS4 does not respect the smartQuotesTo argument to the "
                "BeautifulSoup constructor. Smart quotes are always converted "
                "to Unicode characters.")

        if 'selfClosingTags' in kwargs:
            del kwargs['selfClosingTags']
            warnings.warn(
                "BS4 does not respect the selfClosingTags argument to the "
                "BeautifulSoup constructor. The tree builder is responsible "
                "for understanding self-closing tags.")

        if 'isHTML' in kwargs:
            del kwargs['isHTML']
            warnings.warn(
                "BS4 does not respect the isHTML argument to the "
                "BeautifulSoup constructor. Suggest you use "
                "features='lxml' for HTML and features='lxml-xml' for "
                "XML.")

        def deprecated_argument(old_name, new_name):
            if old_name in kwargs:
                warnings.warn(
                    'The "%s" argument to the BeautifulSoup constructor '
                    'has been renamed to "%s."' % (old_name, new_name))
                value = kwargs[old_name]
                del kwargs[old_name]
                return value
            return None

        parse_only = parse_only or deprecated_argument(
            "parseOnlyThese", "parse_only")

        from_encoding = from_encoding or deprecated_argument(
            "fromEncoding", "from_encoding")

        if from_encoding and isinstance(markup, str):
            warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")
            from_encoding = None

        self.element_classes = element_classes or dict()

        # We need this information to track whether or not the builder
        # was specified well enough that we can omit the 'you need to
        # specify a parser' warning.
        original_builder = builder
        original_features = features

        if isinstance(builder, type):
            # A builder class was passed in; it needs to be instantiated.
            builder_class = builder
            builder = None
        elif builder is None:
            if isinstance(features, str):
                features = [features]
            if features is None or len(features) == 0:
                features = self.DEFAULT_BUILDER_FEATURES
            builder_class = builder_registry.lookup(*features)
            if builder_class is None:
                raise FeatureNotFound(
                    "Couldn't find a tree builder with the features you "
                    "requested: %s. Do you need to install a parser library?"
                    % ",".join(features))

        # At this point either we have a TreeBuilder instance in
        # builder, or we have a builder_class that we can instantiate
        # with the remaining **kwargs.
        if builder is None:
            builder = builder_class(**kwargs)
            if not original_builder and not (
                    original_features == builder.NAME or
                    original_features in builder.ALTERNATE_NAMES
            ) and markup:
                # The user did not tell us which TreeBuilder to use,
                # and we had to guess. Issue a warning.
                if builder.is_xml:
                    markup_type = "XML"
                else:
                    markup_type = "HTML"

                # This code adapted from warnings.py so that we get the same line
                # of code as our warnings.warn() call gets, even if the answer is wrong
                # (as it may be in a multithreading situation).
                caller = None
                try:
                    caller = sys._getframe(1)
                except ValueError:
                    pass
                if caller:
                    globals = caller.f_globals
                    line_number = caller.f_lineno
                else:
                    globals = sys.__dict__
                    line_number= 1
                filename = globals.get('__file__')
                if filename:
                    fnl = filename.lower()
                    if fnl.endswith((".pyc", ".pyo")):
                        filename = filename[:-1]
                if filename:
                    # If there is no filename at all, the user is most likely in a REPL,
                    # and the warning is not necessary.
                    values = dict(
                        filename=filename,
                        line_number=line_number,
                        parser=builder.NAME,
                        markup_type=markup_type
                    )
                    warnings.warn(
                        self.NO_PARSER_SPECIFIED_WARNING % values,
                        GuessedAtParserWarning, stacklevel=2
                    )
        else:
            if kwargs:
                warnings.warn("Keyword arguments to the BeautifulSoup constructor will be ignored. These would normally be passed into the TreeBuilder constructor, but a TreeBuilder instance was passed in as `builder`.")

        self.builder = builder
        self.is_xml = builder.is_xml
        self.known_xml = self.is_xml
        self._namespaces = dict()
        self.parse_only = parse_only

        self.builder.initialize_soup(self)

        if hasattr(markup, 'read'):        # It's a file-type object.
            markup = markup.read()
        elif len(markup) <= 256 and (
                (isinstance(markup, bytes) and not b'<' in markup)
                or (isinstance(markup, str) and not '<' in markup)
        ):
            # Print out warnings for a couple beginner problems
            # involving passing non-markup to Beautiful Soup.
            # Beautiful Soup will still parse the input as markup,
            # just in case that's what the user really wants.
            if (isinstance(markup, str)
                and not os.path.supports_unicode_filenames):
                possible_filename = markup.encode("utf8")
            else:
                possible_filename = markup
            is_file = False
            is_directory = False
            try:
                is_file = os.path.exists(possible_filename)
                if is_file:
                    is_directory = os.path.isdir(possible_filename)
            except Exception as e:
                # This is almost certainly a problem involving
                # characters not valid in filenames on this
                # system. Just let it go.
                pass
            if is_directory:
                warnings.warn(
                    '"%s" looks like a directory name, not markup. You may'
                    ' want to open a file found in this directory and pass'
                    ' the filehandle into Beautiful Soup.' % (
                        self._decode_markup(markup)
                    ),
                    MarkupResemblesLocatorWarning
                )
            elif is_file:
                warnings.warn(
                    '"%s" looks like a filename, not markup. You should'
                    ' probably open this file and pass the filehandle into'
                    ' Beautiful Soup.' % self._decode_markup(markup),
                    MarkupResemblesLocatorWarning
                )
            self._check_markup_is_url(markup)

        rejections = []
        success = False
        for (self.markup, self.original_encoding, self.declared_html_encoding,
         self.contains_replacement_characters) in (
             self.builder.prepare_markup(
                 markup, from_encoding, exclude_encodings=exclude_encodings)):
            self.reset()
            try:
                self._feed()
                success = True
                break
            except ParserRejectedMarkup as e:
                rejections.append(e)
                pass

        if not success:
            other_exceptions = [str(e) for e in rejections]
>           raise ParserRejectedMarkup(
                "The markup you provided was rejected by the parser. Trying a different parser or a different encoding may help.\n\nOriginal exception(s) from parser:\n " + "\n ".join(other_exceptions)
            )
E           bs4.builder.ParserRejectedMarkup: The markup you provided was rejected by the parser. Trying a different parser or a different encoding may help.
E
E           Original exception(s) from parser:
E            LookupError: unknown encoding: 'b'iso8859-8''
E            UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 0: invalid continuation byte
E            LookupError: unknown encoding: 'b'windows-1252''

bs4/__init__.py:371: ParserRejectedMarkup
______ LXMLTreeBuilderSmokeTest.test_smart_quotes_converted_on_the_way_in ______

self = <bs4.tests.test_lxml.LXMLTreeBuilderSmokeTest testMethod=test_smart_quotes_converted_on_the_way_in>

    def test_smart_quotes_converted_on_the_way_in(self):
        # Microsoft smart quotes are converted to Unicode characters during
        # parsing.
        quote = b"<p>\x91Foo\x92</p>"
>       soup = self.soup(quote)

bs4/testing.py:750:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
bs4/testing.py:75: in soup
    return BeautifulSoup(markup, builder=builder, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = , markup = b'<p>\x91Foo\x92</p>', features = None
builder = <bs4.builder._lxml.LXMLTreeBuilder object at 0x10d7077c0>
parse_only = None, from_encoding = None, exclude_encodings = None
element_classes = None, kwargs = {}
deprecated_argument = <function BeautifulSoup.__init__.<locals>.deprecated_argument at 0x10d6f2d30>
original_builder = <class 'bs4.builder._lxml.LXMLTreeBuilder'>
original_features = None
builder_class = <class 'bs4.builder._lxml.LXMLTreeBuilder'>

    def __init__(self, markup="", features=None, builder=None,
                 parse_only=None, from_encoding=None, exclude_encodings=None,
                 element_classes=None, **kwargs):
        """Constructor.

        :param markup: A string or a file-like object representing
         markup to be parsed.

        :param features: Desirable features of the parser to be
         used. This may be the name of a specific parser ("lxml",
         "lxml-xml", "html.parser", or "html5lib") or it may be the
         type of markup to be used ("html", "html5", "xml"). It's
         recommended that you name a specific parser, so that
         Beautiful Soup gives you the same results across platforms
         and virtual environments.

        :param builder: A TreeBuilder subclass to instantiate (or
         instance to use) instead of looking one up based on
         `features`. You only need to use this if you've implemented a
         custom TreeBuilder.

        :param parse_only: A SoupStrainer. Only parts of the document
         matching the SoupStrainer will be considered. This is useful
         when parsing part of a document that would otherwise be too
         large to fit into memory.

        :param from_encoding: A string indicating the encoding of the
         document to be parsed. Pass this in if Beautiful Soup is
         guessing wrongly about the document's encoding.

        :param exclude_encodings: A list of strings indicating
         encodings known to be wrong. Pass this in if you don't know
         the document's encoding but you know Beautiful Soup's guess is
         wrong.

        :param element_classes: A dictionary mapping BeautifulSoup
         classes like Tag and NavigableString, to other classes you'd
         like to be instantiated instead as the parse tree is
         built. This is useful for subclassing Tag or NavigableString
         to modify default behavior.

        :param kwargs: For backwards compatibility purposes, the
         constructor accepts certain keyword arguments used in
         Beautiful Soup 3. None of these arguments do anything in
         Beautiful Soup 4; they will result in a warning and then be
         ignored.

         Apart from this, any keyword arguments passed into the
         BeautifulSoup constructor are propagated to the TreeBuilder
         constructor. This makes it possible to configure a
         TreeBuilder by passing in arguments, not just by saying which
         one to use.
        """
        if 'convertEntities' in kwargs:
            del kwargs['convertEntities']
            warnings.warn(
                "BS4 does not respect the convertEntities argument to the "
                "BeautifulSoup constructor. Entities are always converted "
                "to Unicode characters.")

        if 'markupMassage' in kwargs:
            del kwargs['markupMassage']
            warnings.warn(
                "BS4 does not respect the markupMassage argument to the "
                "BeautifulSoup constructor. The tree builder is responsible "
                "for any necessary markup massage.")

        if 'smartQuotesTo' in kwargs:
            del kwargs['smartQuotesTo']
            warnings.warn(
                "BS4 does not respect the smartQuotesTo argument to the "
                "BeautifulSoup constructor. Smart quotes are always converted "
                "to Unicode characters.")

        if 'selfClosingTags' in kwargs:
            del kwargs['selfClosingTags']
            warnings.warn(
                "BS4 does not respect the selfClosingTags argument to the "
                "BeautifulSoup constructor. The tree builder is responsible "
                "for understanding self-closing tags.")

        if 'isHTML' in kwargs:
            del kwargs['isHTML']
            warnings.warn(
                "BS4 does not respect the isHTML argument to the "
                "BeautifulSoup constructor. Suggest you use "
                "features='lxml' for HTML and features='lxml-xml' for "
                "XML.")

        def deprecated_argument(old_name, new_name):
            if old_name in kwargs:
                warnings.warn(
                    'The "%s" argument to the BeautifulSoup constructor '
                    'has been renamed to "%s."' % (old_name, new_name))
                value = kwargs[old_name]
                del kwargs[old_name]
                return value
            return None

        parse_only = parse_only or deprecated_argument(
            "parseOnlyThese", "parse_only")

        from_encoding = from_encoding or deprecated_argument(
            "fromEncoding", "from_encoding")

        if from_encoding and isinstance(markup, str):
            warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")
            from_encoding = None

        self.element_classes = element_classes or dict()

        # We need this information to track whether or not the builder
        # was specified well enough that we can omit the 'you need to
        # specify a parser' warning.
        original_builder = builder
        original_features = features

        if isinstance(builder, type):
            # A builder class was passed in; it needs to be instantiated.
            builder_class = builder
            builder = None
        elif builder is None:
            if isinstance(features, str):
                features = [features]
            if features is None or len(features) == 0:
                features = self.DEFAULT_BUILDER_FEATURES
            builder_class = builder_registry.lookup(*features)
            if builder_class is None:
                raise FeatureNotFound(
                    "Couldn't find a tree builder with the features you "
                    "requested: %s. Do you need to install a parser library?"
                    % ",".join(features))

        # At this point either we have a TreeBuilder instance in
        # builder, or we have a builder_class that we can instantiate
        # with the remaining **kwargs.
        if builder is None:
            builder = builder_class(**kwargs)
            if not original_builder and not (
                    original_features == builder.NAME or
                    original_features in builder.ALTERNATE_NAMES
            ) and markup:
                # The user did not tell us which TreeBuilder to use,
                # and we had to guess. Issue a warning.
                if builder.is_xml:
                    markup_type = "XML"
                else:
                    markup_type = "HTML"

                # This code adapted from warnings.py so that we get the same line
                # of code as our warnings.warn() call gets, even if the answer is wrong
                # (as it may be in a multithreading situation).
                caller = None
                try:
                    caller = sys._getframe(1)
                except ValueError:
                    pass
                if caller:
                    globals = caller.f_globals
                    line_number = caller.f_lineno
                else:
                    globals = sys.__dict__
                    line_number= 1
                filename = globals.get('__file__')
                if filename:
                    fnl = filename.lower()
                    if fnl.endswith((".pyc", ".pyo")):
                        filename = filename[:-1]
                if filename:
                    # If there is no filename at all, the user is most likely in a REPL,
                    # and the warning is not necessary.
                    values = dict(
                        filename=filename,
                        line_number=line_number,
                        parser=builder.NAME,
                        markup_type=markup_type
                    )
                    warnings.warn(
                        self.NO_PARSER_SPECIFIED_WARNING % values,
                        GuessedAtParserWarning, stacklevel=2
                    )
        else:
            if kwargs:
                warnings.warn("Keyword arguments to the BeautifulSoup constructor will be ignored. These would normally be passed into the TreeBuilder constructor, but a TreeBuilder instance was passed in as `builder`.")

        self.builder = builder
        self.is_xml = builder.is_xml
        self.known_xml = self.is_xml
        self._namespaces = dict()
        self.parse_only = parse_only

        self.builder.initialize_soup(self)

        if hasattr(markup, 'read'):        # It's a file-type object.
            markup = markup.read()
        elif len(markup) <= 256 and (
                (isinstance(markup, bytes) and not b'<' in markup)
                or (isinstance(markup, str) and not '<' in markup)
        ):
            # Print out warnings for a couple beginner problems
            # involving passing non-markup to Beautiful Soup.
            # Beautiful Soup will still parse the input as markup,
            # just in case that's what the user really wants.
            if (isinstance(markup, str)
                and not os.path.supports_unicode_filenames):
                possible_filename = markup.encode("utf8")
            else:
                possible_filename = markup
            is_file = False
            is_directory = False
            try:
                is_file = os.path.exists(possible_filename)
                if is_file:
                    is_directory = os.path.isdir(possible_filename)
            except Exception as e:
                # This is almost certainly a problem involving
                # characters not valid in filenames on this
                # system. Just let it go.
                pass
            if is_directory:
                warnings.warn(
                    '"%s" looks like a directory name, not markup. You may'
                    ' want to open a file found in this directory and pass'
                    ' the filehandle into Beautiful Soup.' % (
                        self._decode_markup(markup)
                    ),
                    MarkupResemblesLocatorWarning
                )
            elif is_file:
                warnings.warn(
                    '"%s" looks like a filename, not markup. You should'
                    ' probably open this file and pass the filehandle into'
                    ' Beautiful Soup.' % self._decode_markup(markup),
                    MarkupResemblesLocatorWarning
                )
            self._check_markup_is_url(markup)

        rejections = []
        success = False
        for (self.markup, self.original_encoding, self.declared_html_encoding,
         self.contains_replacement_characters) in (
             self.builder.prepare_markup(
                 markup, from_encoding, exclude_encodings=exclude_encodings)):
            self.reset()
            try:
                self._feed()
                success = True
                break
            except ParserRejectedMarkup as e:
                rejections.append(e)
                pass

        if not success:
            other_exceptions = [str(e) for e in rejections]
>           raise ParserRejectedMarkup(
                "The markup you provided was rejected by the parser. Trying a different parser or a different encoding may help.\n\nOriginal exception(s) from parser:\n " + "\n ".join(other_exceptions)
            )
E           bs4.builder.ParserRejectedMarkup: The markup you provided was rejected by the parser. Trying a different parser or a different encoding may help.
E
E           Original exception(s) from parser:
E            UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 0: invalid start byte
E            LookupError: unknown encoding: 'b'windows-1252''

bs4/__init__.py:371: ParserRejectedMarkup
_________ LXMLXMLTreeBuilderSmokeTest.test_can_parse_unicode_document __________

self = <bs4.tests.test_lxml.LXMLXMLTreeBuilderSmokeTest testMethod=test_can_parse_unicode_document>

    def test_can_parse_unicode_document(self):
        markup = '<?xml version="1.0" encoding="euc-jp"><root>Sacr\N{LATIN SMALL LETTER E WITH ACUTE} bleu!</root>'
        soup = self.soup(markup)
>       self.assertEqual('Sacr\xe9 bleu!', soup.root.string)
E       AttributeError: 'NoneType' object has no attribute 'string'

bs4/testing.py:1002: AttributeError
=========================== short test summary info ============================
FAILED bs4/tests/test_lxml.py::LXMLTreeBuilderSmokeTest::test_real_hebrew_document
FAILED bs4/tests/test_lxml.py::LXMLTreeBuilderSmokeTest::test_smart_quotes_converted_on_the_way_in
FAILED bs4/tests/test_lxml.py::LXMLXMLTreeBuilderSmokeTest::test_can_parse_unicode_document
======================== 3 failed, 514 passed in 2.21s =========================
builder for '/nix/store/k0gkn6wnyxgb4z48jnxjcslvm57vmxmh-python3.9-beautifulsoup4-4.10.0.drv' failed with exit code 1
error: build of '/nix/store/k0gkn6wnyxgb4z48jnxjcslvm57vmxmh-python3.9-beautifulsoup4-4.10.0.drv' failed
```

</details>

### Notify maintainers

@domenkozar @fabaff 

### Metadata

```yaml
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.6.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.6`
 - channels(abutler): `"home-manager, nixpkgs-21.11pre314682.65b70fbe4c3"`
 - nixpkgs: `/Users/abutler/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - python38Packages.beautifulsoup4
  - python39Packages.beautifulsoup4
# a list of nixos modules affected by the problem
module:
```

**Comment by creedasaurus** [comment] 2021-09-13 18:12
Also seeing this after running `nix flake update` and trying to rebuild with home-manager.

**Comment by thefloweringash** [comment] 2021-09-14 05:55
One of the errors from the log:
```
E           bs4.builder.ParserRejectedMarkup: The markup you provided was rejected by the parser. Trying a different parser or a different encoding may help.
E
E           Original exception(s) from parser:
E            LookupError: unknown encoding: 'b'iso8859-8''
E            UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 0: invalid continuation byte
E            LookupError: unknown encoding: 'b'windows-1252''```
```

Some of which, at least, appear to come from [`python3Packages.lxml`](https://github.com/lxml/lxml/blob/5c8edfa39b0e31490a581740aaff44656ec72348/src/lxml/parser.pxi#L835-L837).

```
$ nix-shell -p 'python3.withPackages (ps: [ps.lxml])' \
  --run "python3 -c 'import lxml.etree; lxml.etree.HTMLParser(encoding=\"windows-1252\")'"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "src/lxml/parser.pxi", line 1709, in lxml.etree.HTMLParser.__init__
  File "src/lxml/parser.pxi", line 837, in lxml.etree._BaseParser.__init__
LookupError: unknown encoding: 'b'windows-1252''
```

**Comment by YorikSar** [comment] 2021-09-15 20:58
I've bisected it to the commit

```
commit 03f2cae1bb2741ee54b7d1bd85d26e03dd45ed01 (HEAD, refs/bisect/bad)
Merge: 5fae387b594 231dd103c7a
Author: Sandro <sandro.jaeckel@gmail.com>
Date:   Sun Sep 12 21:34:28 2021 +0200

    Merge pull request #137273 from fabaff/bump-beautifulsoup4
    
    python3Packages.beautifulsoup4: 4.9.3 -> 4.10.0
```
that merged #137273.

It seems `beautifulsoup4` just didn't depend on `lxml` before that update. The issue with `lxml` and `windows-1252` encoding can be reproduced before that commit as well. It also seems like removing `lxml` from `propagatedBuildInputs` fixes the issue.

**Comment by YorikSar** [comment] 2021-09-15 21:18
Oh, I also found #137870 that might fix the issue in lxml.

**Comment by jupblb** [comment] 2021-09-17 16:33
Is there a simple way of locally overcoming this issue with an overlay or something?

**Comment by austinharris** [comment] 2021-09-17 18:14
> Is there a simple way of locally overcoming this issue with an overlay or something?

You could do something like this to just rollback to the previous beautifulsoup version.

```
  pythonPackages = super.pythonPackages.override {
    packageOverrides = self: super: {
      beautifulsoup4 = super.beautifulsoup4.overridePythonAttrs {
        version = "4.9.3";
        src = super.fetcyPypi {
          version = "4.9.3";
          pname = "beautifulsoup4";
          sha256 = "84729e322ad1d5b4d25f805bfa05b902dd96450f43842c4e99067d5e1369eb25";
        };
      };
    };
  };
```

**Comment by YorikSar** [comment] 2021-09-17 18:46
@jupblb You can try removing `lxml` from the `beautifulsoup4` dependencies. It's not ideal, and maintainers [don't like](https://github.com/NixOS/nixpkgs/pull/138059#issuecomment-921247123) this workaround, but it works and doesn't trigger many rebuilds. Drop this content in your `~/.config/nixpkgs/overlays/bs4.nix`:
```
self: super:
let
  lib = super.lib;
in
rec {
  python39 = super.python39.override {
    packageOverrides = self: super: {
      beautifulsoup4 = super.beautifulsoup4.overrideAttrs (old: {
        propagatedBuildInputs = lib.remove super.lxml old.propagatedBuildInputs;
      });
    };
  };
  python39Packages = python39.pkgs;
}
```
and it should work. Replace `python39` if you want to use different base python version.

**Comment by jupblb** [comment] 2021-09-17 20:26
@YorikSar that helped a lot. Thank you! :) In my previous attempts I missed the fact that aside from `python3Packages` there is also `python3.pkgs` (which is the root definition).

**Comment by emilazy** [comment] 2021-09-25 16:01
This would be fixed by #137870 (awaiting feedback so I can fix the regressions on x86_64-darwin; I'm not sure if `propagatedBuildInputs` is the right thing to use there or not) and #138059 (an alternative approach that sacrifices functionality but is less invasive and would cause fewer rebuilds).

**Comment by m4dc4p** [comment] 2021-10-05 22:54
@jupblb I've been trying to incorporate this into a `nix-shell` `!#` invocation and I just can't get it (I've got a python script I like to run standalone that's broken due to this). How can I translate your overlay into an expression that will execute? I've gotten to the following, but the `beautifulsoup` tests still fail:

```bash
#! /usr/bin/env nix-shell
#! nix-shell -i python -p "let x = { python38 = python38.override { packageOverrides = self: super: { beautifulsoup4 = super.beautifulsoup4.overrideAttrs (old: { propagatedBuildInputs = lib.remove super.lxml old.propagatedBuildInputs; }); }; }; python38Packages = python38.pkgs; }; in with x;[python38 python38Packages.beautifulsoup4]"
```

Pretty printed, the expression is:

```nix
let x = { 
  python38 = python38.override { 
    packageOverrides = self: super: { 
      beautifulsoup4 = super.beautifulsoup4.overrideAttrs (old: { 
        propagatedBuildInputs = lib.remove super.lxml old.propagatedBuildInputs; 
      }); 
    }; 
  }; 
  python38Packages = python38.pkgs; 
}; 
in with x; [python38 python38Packages.beautifulsoup4]
```

Thanks for any help!

**Comment by jupblb** [comment] 2021-10-06 19:13
Thanks a milion, but I think the credit should go @YorikSar. 😅 And @emilazy (for https://github.com/NixOS/nixpkgs/pull/137870).

**Closed** 2021-11-02 06:40 UTC
Labels: 0.kind: bug, 6.topic: darwin
