### ISSUE TITLE
texlive: "mktextfm: Cannot find mktex.opt; check your installation"

### ISSUE THREAD

**Issue by stebulus** [NixOS/nixpkgs#16724] opened 2016-07-05 10:43 UTC
## Issue description

Running `mktextfm` from texlive yields the error message `mktextfm: Cannot find mktex.opt; check your installation`.
### Steps to reproduce

```
$ cat >default.nix <<EOF
with import <nixpkgs> {};
stdenv.mkDerivation {
  name = "nixpkgs-mktexpk-problem-0.1.0";
  buildInputs = [
    (texlive.combine { inherit (texlive) scheme-basic metafont; })
  ];
}
EOF
$ nix-shell
[nix-shell]$ mktextfm cmr10
```
## Technical details
- System: Ubuntu 14.04.4 LTS
- Nix version: 1.11.2
- Nixpkgs version: 16.09pre83147.df89584
## Uninformed investigation

I think the patching of scripts in texlive.combine doesn't achieve the desired effect with `mktextfm`, `mktexpk`, and `mktexmf`.  In `/nix/store/69aarjbh...-texlive-combined-2015/bin/mktextfm`, the final command is

```
exec /nix/store/d20f169r...-bash-4.3-p42/bin/sh  /nix/store/dmfikj6q...-texlive-bin-2015/bin/mktextfm "${extraFlagsArray[@]}" "$@"
```

which causes `$0` to be `/nix/store/dmfikj6q...-texlive-bin-2015/bin/mktextfm`.  Since the script `mktextfm` prepends its own directory (as determined by inspecting `$0`) to PATH, it runs `kpsewhich` from texlive-bin-2015 rather than from texlive-combined-2015, so it doesn't find the combined `texmf.cnf`.

If I replace the final line of `mktextfm` with

```
exec /nix/store/d20f169r...-bash-4.3-p42/bin/bash  -c ". /nix/store/dmfikj6q...-texlive-bin-2015/bin/mktextfm" /nix/store/69aarjbh...-texlive-combined-2015/bin/mktextfm "${extraFlagsArray[@]}" "$@"
```

(so that $0 will refer to texlive-combined-2015 even though the script itself is not there), then the command `mktextfm cmr10` seems to run metafont normally, and reports generating files in `~/.texlive2014/texmf-var` as expected.

**Comment by Profpatsch** [comment] 2018-06-23 22:57
triage: can you still reproduce this?

**Comment by veprbl** [comment] 2020-03-31 00:01
I can't reproduce on current master. Closing for now.

**Closed by veprbl** 2020-03-31 00:01 UTC
Labels: 6.topic: TeX
