### ISSUE TITLE
flakes: cannot reference a github branch with a '/' in the name

### ISSUE THREAD

**Issue by danderson** [NixOS/nixpkgs#104649] opened 2020-11-23 03:55 UTC
**Describe the bug**

I want to add `github.com/danderson/nixpkgs` as a flake input, using the branch `danderson/influxdb2-svc`. Nix refuses to, presumably because there are too many slashes in the URL portion:

```
error: --- BadURL -------------------------------------------------- nix
URL 'github:danderson/nixpkgs/danderson/influxdb2-svc' is invalid
```

**To Reproduce**

Add to a flake.nix:

```
inputs.borked.url = github:danderson/nixpkgs/danderson/influxdb2-svc
```

Run `nix flake update`, observe it rejects the new input URL.

**Expected behavior**

Git branch names with slashes are legal, I would expect to be able to point nix at one.

**Notify maintainers**

@edolstra is the only person I know related to flakes.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.16, NixOS, 20.09.20201116.f41c0fc (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201102_550e11f`
 - channels(root): `""`
 - channels(dave): `"nixos-unstable-21.03pre250878.a52e974cff8, nixpkgs-20.09.1693.d12178b1c4a"`
 - nixpkgs: `/home/dave/.nix-defexpr/channels/nixpkgs`

**Comment by FRidh** [comment] 2020-11-23 07:20
This is a Nix issue, not Nixpkgs.

Duplicate of https://github.com/NixOS/nix/issues/4061.

**Closed by FRidh** 2020-11-23 07:20 UTC
Labels: 0.kind: bug
