### ISSUE TITLE
Nautilus returns Operation not supported when connecting (s)ftp with gvfs.enable = true

### ISSUE THREAD

**Issue by diamondburned** [NixOS/nixpkgs#60449] opened 2019-04-30 03:08 UTC
## Issue description

Nautilus would return an `Operation not supported`, even with `services.gnome3.gvfs.enable = true;` in the config.

Edit: unsure if related or not, but MTP does not work either.

![](https://cdn.discordapp.com/attachments/361916911682060289/572618660586192896/unknown.png)

### Steps to reproduce

1. Add `gnome3.nautilus` to environment.systemPackages`
2. Add `services.gnome3.gvfs.enable = true;`
3. Run `nautilus`
4. If one tries to connect to a `(s)ftp` bookmarks, the above image is returned
4.5. If one tries to connect via the `Connect to server` field in `Other Locations`, the Connect button is greyed

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.34, NixOS, 19.03.172361.cf3e277dd0b (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(diamond): `"nixpkgs-19.09pre177248.ed1b59a98e7"`
 - channels(root): `"nixos-19.03.172361.cf3e277dd0b, nixpkgs-19.09pre177248.ed1b59a98e7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

A copy of my `configuration.nix` can be found here: https://gitlab.com/diamondburned/dotfiles/blob/master/Scripts/nix/configuration.nix

**Comment by jtojnar** [comment] 2019-04-30 10:26
Can this be duplicate of https://github.com/NixOS/nixpkgs/issues/50254

Does the fix in the collapsed section of https://github.com/NixOS/nixpkgs/issues/50254#issuecomment-472432604 work for you?

Perhaps https://github.com/NixOS/nixpkgs/pull/57603 needs to be backported.

**Comment by diamondburned** [comment] 2019-05-01 04:18
Fixx at https://github.com/NixOS/nixpkgs/issues/50254#issuecomment-472432604 sadly didn't fix it for me. 

![](https://media.discordapp.net/attachments/361910177961738244/572995192299192330/unknown.png)

(same error)

I've also tried running `systemctl --user stop gvfs-daemon` and `systemctl --user start gvfs-daemon`, though that didn't work either (worth noting that I have not rebooted yet)

**Comment by worldofpeace** [comment] 2019-08-01 18:26
I believe the fix was ported to stable. Is this still an issue?

**Comment by jtojnar** [comment] 2019-09-03 18:45
Closing with no feedback.

**Closed by jtojnar** 2019-09-03 18:45 UTC
Labels: 0.kind: bug, 6.topic: gnome3, 9.needs: port to stable
