### ISSUE TITLE
Infinite recursion evaluating mate module 

### ISSUE THREAD

**Issue by s9gf4ult** [NixOS/nixpkgs#100742] opened 2020-10-16 17:53 UTC
**Describe the bug**

Infinite recursion while evaluation the 

```
nixpkgs/nixos/modules/services/x11/desktop-managers/mate.nix:50:7
```

**To Reproduce**

1. Check out nixpkgs to d74573d8ae6f02ef0ac1299c862d1b762ba0aad1
2. Use Mate as desktop manager together with lightdm

```
  # Enable the X11 windowing system.
  services.xserver = {
    enable = true;
    layout = "us,ru";
    xkbOptions = "grp:shift_toggle";
    xkbVariant = "workman";
    # Enable touchpad support.
    libinput.enable = true;

    # Enable the KDE Desktop Environment.
    displayManager = {
      lightdm.enable = true;
      defaultSession = "mate" ;
    };
    desktopManager = {
      mate.enable = true;
    };
  };
```

3. Building results to infinite recursion 

```
NIXOS_CONFIG="/home/razor/work/nixos-config/desktop.nix" NIX_PATH="nixpkgs=/home/razor/work/nixos-config/nixpkgs:nixos-config=/home/razor/work/nixos-config/desktop.nix" nixos-rebuild build --show-trace
building Nix...
building the system configuration...
error: while evaluating the attribute 'activationScript' of the derivation 'nixos-system-gazoline-20.03post-git' at /home/razor/work/nixos-config/nixpkgs/nixos/modules/system/activation/top-level.nix:103:5:
while evaluating the attribute 'system.activationScripts.script' at /home/razor/work/nixos-config/nixpkgs/nixos/modules/system/activation/activation-script.nix:68:9:
while evaluating 'textClosureMap' at /home/razor/work/nixos-config/nixpkgs/lib/strings-with-deps.nix:70:35, called from /home/razor/work/nixos-config/nixpkgs/nixos/modules/system/activation/activation-script.nix:89:18:
while evaluating 'id' at /home/razor/work/nixos-config/nixpkgs/lib/trivial.nix:14:5, called from undefined position:
while evaluating the attribute 'text' at /home/razor/work/nixos-config/nixpkgs/nixos/modules/system/activation/activation-script.nix:9:5:
while evaluating the attribute 'text' at /home/razor/work/nixos-config/nixpkgs/lib/strings-with-deps.nix:77:38:
while evaluating the attribute 'sources' of the derivation 'etc' at /home/razor/work/nixos-config/nixpkgs/nixos/modules/system/etc/etc.nix:12:5:
while evaluating anonymous function at /home/razor/work/nixos-config/nixpkgs/nixos/modules/system/etc/etc.nix:20:20, called from undefined position:
while evaluating the attribute 'source' at undefined position:
while evaluating anonymous function at /home/razor/work/nixos-config/nixpkgs/lib/modules.nix:84:45, called from undefined position:
while evaluating the attribute 'value' at /home/razor/work/nixos-config/nixpkgs/lib/modules.nix:379:9:
while evaluating the option `environment.etc.dbus-1.source':
while evaluating the attribute 'mergedValue' at /home/razor/work/nixos-config/nixpkgs/lib/modules.nix:411:5:
while evaluating anonymous function at /home/razor/work/nixos-config/nixpkgs/lib/modules.nix:413:22, called from /home/razor/work/nixos-config/nixpkgs/lib/modules.nix:413:9:
while evaluating 'check' at /home/razor/work/nixos-config/nixpkgs/lib/types.nix:251:15, called from /home/razor/work/nixos-config/nixpkgs/lib/modules.nix:414:14:
while evaluating the attribute 'serviceDirectories' of the derivation 'dbus-1' at /home/razor/work/nixos-config/nixpkgs/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating anonymous function at /home/razor/work/nixos-config/nixpkgs/lib/types.nix:263:14, called from undefined position:
while evaluating the attribute 'value' at /home/razor/work/nixos-config/nixpkgs/lib/modules.nix:425:27:
while evaluating anonymous function at /home/razor/work/nixos-config/nixpkgs/lib/modules.nix:413:22, called from /home/razor/work/nixos-config/nixpkgs/lib/modules.nix:413:9:
while evaluating 'check' at /home/razor/work/nixos-config/nixpkgs/lib/types.nix:251:15, called from /home/razor/work/nixos-config/nixpkgs/lib/modules.nix:414:14:
while evaluating the attribute 'passAsFile' of the derivation 'system-path' at /home/razor/work/nixos-config/nixpkgs/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating the attribute 'buildCommand' of the derivation 'desktops' at /home/razor/work/nixos-config/nixpkgs/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating 'concatMapStrings' at /home/razor/work/nixos-config/nixpkgs/lib/strings.nix:31:25, called from /home/razor/work/nixos-config/nixpkgs/nixos/modules/services/x11/display-managers/default.nix:124:9:
while evaluating anonymous function at /home/razor/work/nixos-config/nixpkgs/nixos/modules/services/x11/display-managers/default.nix:124:27, called from undefined position:
while evaluating the attribute 'text' of the derivation 'mate-xsession' at /home/razor/work/nixos-config/nixpkgs/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating the attribute 'text' of the derivation 'xsession' at /home/razor/work/nixos-config/nixpkgs/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating the attribute 'start' at /home/razor/work/nixos-config/nixpkgs/nixos/modules/services/x11/desktop-managers/default.nix:73:11:
while evaluating the attribute 'start' at /home/razor/work/nixos-config/nixpkgs/nixos/modules/services/x11/desktop-managers/mate.nix:50:7:
infinite recursion encountered, at undefined position
```

**Expected behavior**
System build

**Additional context**

1. When switching to `plasma5` everything builds

```
  # Enable the X11 windowing system.
  services.xserver = {
    enable = true;
    layout = "us,ru";
    xkbOptions = "grp:shift_toggle";
    xkbVariant = "workman";
    # Enable touchpad support.
    libinput.enable = true;

    # Enable the KDE Desktop Environment.
    displayManager = {
      lightdm.enable = true;
      defaultSession = "plasma5" ;
    };
    desktopManager = {
      plasma5.enable = true;
    };
  };
```

2. When checkout to previous commit  08d429920bcb2dba1d47c93e5ed30d0f92838c89 then everything builds 

The d74573d8ae6f02ef0ac1299c862d1b762ba0aad1 is the first bad commit found by bisection. The bug is reproduceable at ff6fda61600cc60404bab5cb6b18b8636785b7bc (current nixos-20.03)

**Notify maintainers**

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.70, NixOS, 20.03.git.0d474ee1aede (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - nixpkgs: `/etc/nixos/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - services/x11/desktop-managers/mate
```

**Comment by veprbl** [comment] 2020-10-16 21:28
Duplicate of #100464

**Closed** 2020-10-18 13:17 UTC
Labels: 0.kind: bug, 6.topic: nixos
