### ISSUE TITLE
Packaging request: Quarto

### ISSUE THREAD

**Issue by leonvonrabenmond** [NixOS/nixpkgs#186437] opened 2022-08-13 12:29 UTC
**Project description**
Quarto® is an open-source scientific and technical publishing system built on [Pandoc](https://pandoc.org/)

**Metadata**

* homepage URL: https://quarto.org/
* source URL: https://github.com/quarto-dev/quarto-cli
* license: gpl2+
* platforms: unix, linux, darwin

**Comment by das-g** [comment] 2022-08-22 14:28
Duplicate of #160911

**Closed by das-g** 2022-08-22 14:28 UTC
Labels: 2.status: duplicate, 0.kind: packaging request
