### ISSUE TITLE
Build failure: thefuck-3.32

### ISSUE THREAD

**Issue by mayersj1** [NixOS/nixpkgs#298154] opened 2024-03-22 20:02 UTC
### Steps To Reproduce

1. performed a 'nix flake update' in my standalone ~/.config/home-manager directory
2. I'm tracking nixpkgs-unstable
3. Then did a 'home-manager flake .#smayer@heresy switch -v'
4. Build of 'thefuck' fails with four test failures as noted in the build log

Verified this on both aarch64-darwin and x86_64-linux systems. Same error

### Build log

```
https://gist.github.com/mayersj1/5a9d8c28f0bec5d45d754098c29144ec
```

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 nix-shell -p nix-info --run "nix-info -m"
these 2 paths will be fetched (0.01 MiB download, 0.11 MiB unpacked):
  /nix/store/n4adgfc87gr37lmisvlxi4d0sxlr6kg7-DarwinTools-1
  /nix/store/pahmj55ad28yv2mw82881hqi32zfhckr-nix-info
copying path '/nix/store/n4adgfc87gr37lmisvlxi4d0sxlr6kg7-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/pahmj55ad28yv2mw82881hqi32zfhckr-nix-info' from 'https://cache.nixos.org'...
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.4.0, macOS 14.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.20.5`
 - channels(root): `""`
 - nixpkgs: `/nix/store/bv68i4l7g6s5sixxm0c9lcjdxhlkg0n5-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lolbinarycat** [comment] 2024-03-23 01:43
Unable to replicate.

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.4, NixOS, 23.11 (Tapir), 23.11.4315.c68a9fc85c2c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(binarycat): `"stable-23.05, unstable"`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/home/binarycat/.nix-defexpr/channels/nixpkgs`
```

**Comment by anriha** [comment] 2024-03-23 01:48
I had the same issue, but seems that https://github.com/NixOS/nixpkgs/pull/297868 fixed it.

**Comment by kashw2** [comment] 2024-04-28 07:29
closing as unable to reproduce when running `nix build nixpkgs#thefuck` and this seems to have been fixed by https://github.com/NixOS/nixpkgs/pull/297868

**Closed by kashw2** 2024-04-28 07:29 UTC
Labels: 0.kind: build failure
