### ISSUE TITLE
Build failure: gimp-with-plugins

### ISSUE THREAD

**Issue by nipsy** [NixOS/nixpkgs#295161] opened 2024-03-11 23:45 UTC
### Steps To Reproduce

1. build gimp-with-plugins

### Build log

```
building the system configuration...
error: builder for '/nix/store/3rzl6mwdk8w06pivfabzk8hkv4l666lq-gimp-plugin-gap-2.6.0.drv' failed with exit code 2;
       last 10 log lines:
       > ./libavcodec/bitstream.h:65: Error: operand type mismatch for `shr'
       > ./libavcodec/bitstream.h:65: Error: operand type mismatch for `shr'
       > ./libavcodec/bitstream.h:65: Error: operand type mismatch for `shr'
       > make[3]: *** [common.mak:25: libavformat/adtsenc.o] Error 1
       > make[3]: Leaving directory '/build/gimp-gap-2.6.0/extern_libs/ffmpeg'
       > make[2]: *** [Makefile:440: /build/gimp-gap-2.6.0/extern_libs/ffmpeg/libavformat/libavformat.a] Error 2
       > make[2]: Leaving directory '/build/gimp-gap-2.6.0/extern_libs'
       > make[1]: *** [Makefile:331: all-recursive] Error 1
       > make[1]: Leaving directory '/build/gimp-gap-2.6.0'
       > make: *** [Makefile:270: all] Error 2
       For full logs, run 'nix log /nix/store/3rzl6mwdk8w06pivfabzk8hkv4l666lq-gimp-plugin-gap-2.6.0.drv'.
error: 1 dependencies of derivation '/nix/store/3hzlr2rk68ljsdb9whbhl0m09fc62dgy-gimp-with-plugins-2.10.36.drv' failed to build
```

### Additional context

Looks like there was a patch already for this mentioned [here](https://bbs.archlinux.org/viewtopic.php?id=289424) on the Arch forums available at https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/effadce6c756247ea8bae32dc13bb3e6f464f0eb.

### Notify maintainers

@jtojnar

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
# nix-shell -p nix-info --run "nix-info -m"
these 5 paths will be fetched (0.68 MiB download, 9.97 MiB unpacked):
  /nix/store/8ja6nib32kv3h9z6jwlh95b5ayma7wfx-file-5.45
  /nix/store/zwkzkw313x6vmd9683h11rqaawyysz1s-gnu-config-2023-09-19
  /nix/store/w0q0c4jham4h0cbvi3ygydl6hrcmzn6x-gnumake-4.4.1
  /nix/store/3qnm3nwjajgqa771dmi2dnwxrw0kzq5m-stdenv-linux
  /nix/store/hcrhrs1mmm2q5a3rzd6xwypqgkpm13vx-update-autotools-gnu-config-scripts-hook
copying path '/nix/store/zwkzkw313x6vmd9683h11rqaawyysz1s-gnu-config-2023-09-19' from 'https://cache.nixos.org'...
copying path '/nix/store/8ja6nib32kv3h9z6jwlh95b5ayma7wfx-file-5.45' from 'https://cache.nixos.org'...
copying path '/nix/store/w0q0c4jham4h0cbvi3ygydl6hrcmzn6x-gnumake-4.4.1' from 'https://cache.nixos.org'...
copying path '/nix/store/hcrhrs1mmm2q5a3rzd6xwypqgkpm13vx-update-autotools-gnu-config-scripts-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/3qnm3nwjajgqa771dmi2dnwxrw0kzq5m-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.7, NixOS, 24.05 (Uakari), 24.05.20240306.9df3e30`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/gig8j85kj7ybjy3ksn6k3aich8j2k59y-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment] 2024-03-12 13:11
Yuck, we should not allow vendoring ffmpeg. We should probably `--disable-libavformat` like Fedora [was doing](https://src.fedoraproject.org/rpms/gimp-gap/blob/b870d959417a8d2a9d5770a818317e620a09b416/f/gimp-gap.spec#_60).

Or maybe just remove gap since it is [dead upstream](https://gitlab.gnome.org/Archive/gimp-gap) and will likely break with upcoming GIMP 3.

**Comment by freelock** [comment] 2024-03-12 16:22
Looks like #294707 might be related...

**Comment by jtojnar** [comment] 2024-03-12 18:46
Duplicate of #294707

**Closed by jtojnar** 2024-03-12 18:46 UTC
Labels: 0.kind: build failure
