### ISSUE TITLE
Discord requires upgrade to 0.0.12

### ISSUE THREAD

**Issue by Poetastrophe** [NixOS/nixpkgs#97828] opened 2020-09-12 07:46 UTC
The package needs to upgraded somehow, because right now it won't be launched. See picture: 
![image](https://user-images.githubusercontent.com/17691932/92990397-82a42780-f4dc-11ea-8cf1-0bc298a1cd95.png)
I use 20.03 channel.
# Notify maintainters
@ldesgoui @MP2E @tadeokondrak

**Comment by moyamo** [comment] 2020-09-12 08:49
It seems like it's in the pipeline already https://github.com/NixOS/nixpkgs/pull/97708. I think it will only be available in the channels once the Hydra tests pass.

To get Discord 0.12 right now you can run

``` bash
nix-env -f https://github.com/NixOS/nixpkgs/archive/release-20.03.tar.gz -iA discord
```

**Comment by YellowOnion** [comment] 2020-09-16 09:46
How long does a hydra test take? I still don't have it on unstable.

**Comment by zakkor** [comment] 2021-03-24 08:57
This is now an issue again with Discord requiring an upgrade to 0.0.14, while the NixOS repositories only have 0.0.13
What can we do while waiting for the new version to land?

**Comment by zakkor** [comment] 2021-03-24 09:10
I guess there is not much else that can be done other than doing:
```
nix-env -f https://github.com/NixOS/nixpkgs/archive/release-<LATEST_VERSION>.tar.gz -iA discord
```

**Comment by Poetastrophe** [comment] 2021-03-24 12:20
@zakkor Yea or if you manage discord with Home-manager you can do something like
```nix
let
  unstable = import  <nixos-unstable> {}; #Or however bleeding edge you wanna be.
in
{
#...
home.packages = with pkgs; [
unstable.discord
];
#...
}
```

**Comment by YellowOnion** [comment] 2021-03-25 00:44
The problem is discord is pinned to a specific version in nix, and version needs to be manually bumped by humans, and so it will forever be an issue until there's someway to "unpin" a package from a hash value, and let upstream control version releases.

Maybe a discussion should be opened around adding mechanisms for this.

**Comment by NomisIV** [comment] 2021-03-25 20:03
Since NixOS is built to be reproducible, I don't think it would be possible to introduce something like that. I don't think a package is rebuilt unless the derivation has changed, and since a hypothetical `discord-latest` derivation would never change, neither would the package. 

However there are bots for this, like r-ryantm. I don't know how it works, or why it doesn't seem to update discord automatically, but I think that bot is the way to go, I'll create a PR for this for now.

**Comment by tadeokondrak** [comment] 2021-03-25 20:08
> I think that bot is the way to go, I'll create a PR for this for now.

r-ryantm already updates Discord automatically using its `updateScript`, but normally someone gets to it first with the stable version. https://github.com/NixOS/nixpkgs/search?q=discord+author%3Ar-ryantm&type=issues

**Comment by NomisIV** [comment] 2021-03-25 20:14
Is this because the `updateScript` isn't run often enough, or is it because some other reason? It seems to pick up the canary releases quicker than the stable, or is this just bad luck? The update script is great and all, but it's not really that useful if it isn't run often enough.

**Comment by ldesgoui** [comment] 2021-03-25 20:21
I don't think there is a good resolution for this problem within the constraints of `nixpkgs` and its infrastructure limitations at the moment, we have discussed this at length at this point, there is no real point to keep this issue open.
The "easy" solution at the moment is installing from `archive/master.tar.gz` whenever the update PR is merged.
A potential solution is writing a script that manages a pin locally.

**Comment by ldesgoui** [comment] 2021-04-05 14:55
It feels like something like this would potentially work well, it manages a new nix profile where `Discord` is installed from `master` while running `update-discord`. `profilePath` needs to be created manually, `update-discord` may need to be run as `sudo` if the user is missing write permissions to `profilePath`, all of that can be addressed with better scripts. It does not currently create the desktop icon thing, it's probably easy to fix up.

```nix
{ stdenv
, writeShellScriptBin
, profilePath ? "/nix/var/nix/profiles/discord-in-a-profile/profile"
}:
stdenv.mkDerivation {
  pname = "discord-in-a-profile";
  version = "0.1.0";

  updater = writeShellScriptBin "update-discord" ''
    echo 'Installing or updating Discord'

    NIXPKGS_ALLOW_UNFREE=1 nix-env \
      --profile ${profilePath} \
      --install \
      --file https://github.com/NixOS/nixpkgs/archive/master.tar.gz \
      --attr discord
  '';

  runner = writeShellScriptBin "Discord" ''
    exec ${profilePath}/bin/Discord $@
  '';

  dontUnpack = true;

  installPhase = ''
    mkdir -p $out/{bin,share}

    cp $updater/bin/update-discord $out/bin/
    cp $runner/bin/Discord $out/bin/
  '';
}
```

**Comment by ldesgoui** [comment] 2021-04-15 23:42
Closing as there are no other steps forward.

**Closed by ldesgoui** 2021-04-15 23:42 UTC
