### ISSUE TITLE
flutter for darwin (aarch64)

### ISSUE THREAD

**Issue by kirinnee** [NixOS/nixpkgs#187947] opened 2022-08-23 03:18 UTC
**Flutter**
Flutter is Google’s UI toolkit for building beautiful, natively compiled applications for mobile, web, and desktop from a single codebase.

**Metadata**

* homepage URL: https://flutter.dev/
* source URL: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/compilers/flutter/flutter.nix#L170
* license: [BSD 3-clause "New" or "Revised" License](https://spdx.org/licenses/BSD-3-Clause.html)
* platforms: darwin-aarch64

**Comment by wegank** [comment] 2022-10-27 21:05
#196133

**Comment by wegank** [comment] 2023-01-22 02:39
Duplicate of #145701.

**Closed by wegank** 2023-01-22 02:39 UTC
Labels: 6.topic: darwin, 0.kind: packaging request
