### ISSUE TITLE
Strange behaviour with GTK_USE_PORTAL=1, affects firefox, evince and gnome-desktop

### ISSUE THREAD

**Issue by astrojhgu** [NixOS/nixpkgs#156950] opened 2022-01-27 04:58 UTC
### Describe the bug
When `xdg.portal.gtkUsePortal=true` is set, following abnormal behaviors happen:
1. gnome desktop login time period becomes much longer (~30s on my x1 yoga)
2. In gnome environment, Firefox failed to launch a file chooser when I press ctrl+O and complains
```
no such interface “org.freedesktop.portal.filechooser” on object at path /org/freedesktop/portal/desktop
```
3. Similar behavior happens in `evince` (still in gnome environment).

As to the `plasma` desktop, all are OK.
For gnome (wayland), it still takes a long period of time (~30s) between I enter the password and the gnome desktop is fully ready, but the filechooser can launch normally after that.

If I remove the `gtkUsePortal` setting, everything becomes OK.

### Steps To Reproduce
1. in `configuration.nix`, add `xdg.portal.gtkUsePortal=true;`
2. `sudo nixos-rebuild boot`
3. reboot
4. login to gnome-xorg.

### Expected behavior
1. gnome desktop should be launch in a short period time (say 5~10 s)
2. the file chooser should be launched normally.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.93, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(root): `"nixos-22.05pre348581.c07b471b52b"`
 - channels(astrojhgu): `"android, nixos-21.11pre329341.9e70e9f732f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jansol** [comment] 2022-01-28 09:45
This sounds like #156830 all over again

**Comment by Algram** [comment] 2022-01-29 23:07
Also affects `gnome.gnome-boxes`

**Comment by avitex** [comment] 2022-03-30 08:32
Duplicate of #135898?

**Comment by itslychee** [comment] 2022-07-02 17:54
I'm getting this with sway too

**Closed** 2022-07-08 14:59 UTC
Labels: 0.kind: bug
