### ISSUE TITLE
OBS Studio - "Show Recordings" fails to open file browser (`GLIBC_2.33` not found)

### ISSUE THREAD

**Issue by x3rAx** [NixOS/nixpkgs#143911] opened 2021-10-30 22:49 UTC
### Describe the bug

OBS in the `unstable` channel fails to open the file browser when selecting `File > Show Recordings`.

### Steps To Reproduce

1. Install OBS from `unstable` channel: `nix-env -iA nixos-unstable.obs-studio`
2. Run `obs` from the terminal
3. Click on `File > Show Recordings`

### Expected behavior

The default file browser should open in the configured recordings directory (configurable in `File > Settings > Output (left menu) > Recording (section) > Recording Path`)

### Screenshots
![](https://i.imgur.com/Xm5UmRo.png)

### Additional context

The following error is logged to STDOUT:

```txt
/run/current-system/sw/bin/kde-open5: /nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/3drz007zp3w7bksw73rnv1xry1pa1js1-libX11-1.7.2/lib/libX11.so.6)
```

### Notify maintainers

@jb55 @MP2E @V

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.75, NixOS, 21.05.3926.5ebb1dca9bb (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.05.3964.6c0c3014634, nixos-unstable-21.11pre325810.2deb07f3ac4"`
 - channels(x3ro): `"nu-21.11pre325810.2deb07f3ac4, n-21.05.3957.66d6ec6ed2d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:

```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by jb55** [comment] 2021-10-31 17:40
>/run/current-system/sw/bin/kde-open5: /nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/3drz007zp3w7bksw73rnv1xry1pa1js1-libX11-1.7.2/lib/libX11.so.6)

I can't reproduce this. On my end it uses xdg-open with the directory as an argument.

**Comment by Artturin** [comment] 2021-10-31 17:43
probably a dupe of https://github.com/NixOS/nixpkgs/issues/84043

**Closed by Artturin** 2021-10-31 17:43 UTC
Labels: 0.kind: bug
