### ISSUE TITLE
GTK theme not used when application is run from GNOME shell activites

### ISSUE THREAD

**Issue by simonvandel** [NixOS/nixpkgs#10577] opened 2015-10-24 16:12 UTC
System info:
Gnome3
nixos-version: 16.03.git.e57024fM (Emu)

Steps to reproduce:
1. Install a GTK theme not included with gnome by default. For example "theme-vertex"
2. Choose the theme in gnome-tweak-tool.
2a. I had to reboot for the theme change to be visible. I also think this is a bug.
3. Open gedit from activities->all applications. Observe that vertex theme is **not** used.
4. Open gedit from terminal. Observe that vertex theme is used

**Comment by jgeerds** [comment] 2016-01-11 20:15
Try adding `theme-vertex` to `services.xserver.desktopManager.gnome3.sessionPath`. Does it resolve the third issue?

**Comment by jgeerds** [comment] 2016-01-11 20:15
@simonvandel

**Comment by jgillich** [comment] 2016-01-11 21:31
Ahh, so that's why my nautilus uses adwaita. Maybe we can create a module to set themes that will then be picked up by the desktop environments? @lethalman

**Comment by lethalman** [comment] 2016-01-11 21:33
@jgillich it should suffice to just put the theme in `systemPackages`

**Comment by jgillich** [comment] 2016-01-12 00:39
I do have my theme in `systemPackages`, but I didn't yet try adding it to `sessionPath`.

**Comment by simonvandel** [comment] 2016-01-14 13:50
Note that i am now using the arc-gtk-theme, but the issue reported originally still applies.

Adding arc-gtk-theme to ```services.xserver.desktopManager.gnome3.sessionPath``` does not solve the issue. Any other ideas?

**Comment by cruegge** [comment] 2016-04-13 22:37
If think the cause of the problem might be that Gnome Shell uses DBus activation if specified in the `desktop` files. So the processes get launched by the DBus daemon and inherit its environment, which unfortunately does not contain some required variables, since it is launched pretty early in the `xsession` script. I think the proper way to change the DBus environment is to use the `UpdateActivationEnvironment` method, like

    gdbus call --session --dest org.freedesktop.DBus --object-path /org/freedesktop/DBus --method org.freedesktop.DBus.UpdateActivationEnvironment "{'FOO': '1', 'BAR': '2'}"

I tried injecting some variables this way and managed to get Nautilus to use my theme. The question is, which variables are necessary to get the proper behaviour? The simplest solution would be to dump the whole `env` to DBus right before launching `gnome-session`. This way, even user-defined variables from `.xprofile` would be made available, but I'm not sure if other side effects might occur.

**Comment by simonvandel** [comment] 2016-04-16 09:52
@cruegge Applying #14741 locally fixes this issue, thanks!

**Comment by nioncode** [comment] 2018-03-12 11:45
Since the commit is already merged to master, this issue can be closed, right?

**Closed** 2018-03-22 17:09 UTC
Labels: 0.kind: bug, 6.topic: gnome3
