### ISSUE TITLE
Package request: Thorium

### ISSUE THREAD

**Issue by RiseWith** [NixOS/nixpkgs#262248] opened 2023-10-20 09:35 UTC
Thorium -
The fastest browser on Earth.

website: https://thorium.rocks/
repo: https://github.com/Alex313031/Thorium

Chromium fork for Linux, Windows, MacOS, Android, and Raspberry Pi named after radioactive element Thorium No. 90.

Highlights:

Compiler optimizations include SSE4.2, AVX, AES, and modifications to CFLAGS, LDFLAGS, thinLTO flags, import_instr_limit flags, and PGO, as well as other compiler flags.
LLVM LOOP optimizations as -mllvm flags
Learn more about these compiler optimizations and how they work: [https://thorium.rocks/optimizations](https://thorium.rocks/optimizations)
UI Changes and Patches for Linux and Windows that fix bugs, enhance useability, and strengthen privacy/security.

  Thorium nets a improvement over vanilla Chromium, depending on the benchmark and OS. See [PATCHES.md](https://github.com/Alex313031/Thorium/blob/main/infra/PATCHES.md) for a detailed overview of all modifications compared to vanilla Chromium regarding performance, security and useability.

**Comment by eclairevoyant** [comment] 2023-10-20 11:36
duplicate of #184823

**Closed by eclairevoyant** 2023-10-20 11:36 UTC
Labels: 0.kind: packaging request
