### ISSUE TITLE
Build failure: ollama-rocm

### ISSUE THREAD

**Issue by PHSix** [NixOS/nixpkgs#344850] opened 2024-09-27 09:31 UTC
### Steps To Reproduce

1. run `nix build nixpkgs#ollama-rocm`

### Build log

```
ollama> [ 76%] Linking HIP shared library libggml.so
ollama> [ 76%] Built target ggml
ollama> [ 76%] Building CXX object src/CMakeFiles/llama.dir/llama.cpp.o
ollama> [ 79%] Building CXX object src/CMakeFiles/llama.dir/llama-vocab.cpp.o
ollama> [ 79%] Building CXX object src/CMakeFiles/llama.dir/llama-grammar.cpp.o
ollama> [ 82%] Building CXX object src/CMakeFiles/llama.dir/llama-sampling.cpp.o
ollama> [ 82%] Building CXX object src/CMakeFiles/llama.dir/unicode.cpp.o
ollama> [ 84%] Building CXX object src/CMakeFiles/llama.dir/unicode-data.cpp.o
ollama> [ 84%] Linking CXX shared library libllama.so
ollama> [ 84%] Built target llama
ollama> [ 84%] Building CXX object examples/llava/CMakeFiles/llava.dir/llava.cpp.o
ollama> [ 87%] Building CXX object common/CMakeFiles/common.dir/common.cpp.o
ollama> [ 87%] Building CXX object common/CMakeFiles/common.dir/grammar-parser.cpp.o
ollama> [ 89%] Building CXX object common/CMakeFiles/common.dir/console.cpp.o
ollama> [ 92%] Building CXX object examples/llava/CMakeFiles/llava.dir/clip.cpp.o
ollama> [ 92%] Building CXX object common/CMakeFiles/common.dir/sampling.cpp.o
ollama> [ 92%] Building CXX object common/CMakeFiles/common.dir/json-schema-to-grammar.cpp.o
ollama> [ 94%] Building CXX object common/CMakeFiles/common.dir/train.cpp.o
ollama> [ 94%] Building CXX object common/CMakeFiles/common.dir/ngram-cache.cpp.o
ollama> [ 94%] Built target llava
ollama> [ 97%] Linking CXX static library libcommon.a
ollama> [ 97%] Built target common
ollama> [100%] Building CXX object ext_server/CMakeFiles/ollama_llama_server.dir/server.cpp.o
ollama> [100%] Linking CXX executable ../bin/ollama_llama_server
ollama> [100%] Built target ollama_llama_server
ollama> + rm -f ../build/linux/amd64/rocm/bin/ggml-common.h ../build/linux/amd64/rocm/bin/ggml-metal.metal
ollama> + mkdir -p ../../dist/linux-amd64//../linux-amd64-rocm/lib/ollama
ollama> ++ ldd ../build/linux/amd64/rocm/bin/ollama_llama_server
ollama> ++ grep '=>'
ollama> ++ cut -f2 -d=
ollama> ++ cut -f2 '-d '
ollama> ++ grep -v amd64/rocm
ollama> ++ grep -e rocm -e amdgpu -e libtinfo -e libnuma -e libelf
ollama> + for dep in $(ldd "${BUILD_DIR}/bin/ollama_llama_server" | grep "=>" | cut -f2 -d= | cut -f2 -d' ' | grep -v "${GOARCH}/rocm${ROCM_VARIANT}" | grep -e rocm -e amdgpu -e libtinfo -e libnuma -e libelf)
ollama> + cp -a /nix/store/d7wl4hnydqbqc2j1qg29sybpc614wkz8-rocm-path/lib/libhipblas.so.2 /nix/store/d7wl4hnydqbqc2j1qg29sybpc614wkz8-rocm-path/lib/libhipblas.so.2.0 ../../dist/linux-amd64//../linux-amd64-rocm/lib/ollama
ollama> ++ readlink -f /nix/store/d7wl4hnydqbqc2j1qg29sybpc614wkz8-rocm-path/lib/libhipblas.so.2
ollama> + '[' /nix/store/2c04lrnax0x0jcdrdins3wykm1lb1360-hipblas-6.0.2/lib/libhipblas.so.2.0 '!=' /nix/store/d7wl4hnydqbqc2j1qg29sybpc614wkz8-rocm-path/lib/libhipblas.so.2 ']'
ollama> ++ readlink -f /nix/store/d7wl4hnydqbqc2j1qg29sybpc614wkz8-rocm-path/lib/libhipblas.so.2
ollama> + cp /nix/store/2c04lrnax0x0jcdrdins3wykm1lb1360-hipblas-6.0.2/lib/libhipblas.so.2.0 ../../dist/linux-amd64//../linux-amd64-rocm/lib/ollama
ollama> cp: '/nix/store/2c04lrnax0x0jcdrdins3wykm1lb1360-hipblas-6.0.2/lib/libhipblas.so.2.0' and '../../dist/linux-amd64//../linux-amd64-rocm/lib/ollama/libhipblas.so.2.0' are the same file
ollama> llm/generate/generate_linux.go:3: running "bash": exit status 1
error: builder for '/nix/store/61lr3bfvwm5nc3gk2adxsglkcwcxb23s-ollama-0.3.11.drv' failed with exit code 1;
       last 10 log lines:
       > ++ grep -v amd64/rocm
       > ++ grep -e rocm -e amdgpu -e libtinfo -e libnuma -e libelf
       > + for dep in $(ldd "${BUILD_DIR}/bin/ollama_llama_server" | grep "=>" | cut -f2 -d= | cut -f2 -d' ' | grep -v "${GOARCH}/rocm${ROCM_VARIANT}" | grep -e rocm -e amdgpu -e libtinfo -e libnuma -e libelf)
       > + cp -a /nix/store/d7wl4hnydqbqc2j1qg29sybpc614wkz8-rocm-path/lib/libhipblas.so.2 /nix/store/d7wl4hnydqbqc2j1qg29sybpc614wkz8-rocm-path/lib/libhipblas.so.2.0 ../../dist/linux-amd64//../linux-amd64-rocm/lib/ollama
       > ++ readlink -f /nix/store/d7wl4hnydqbqc2j1qg29sybpc614wkz8-rocm-path/lib/libhipblas.so.2
       > + '[' /nix/store/2c04lrnax0x0jcdrdins3wykm1lb1360-hipblas-6.0.2/lib/libhipblas.so.2.0 '!=' /nix/store/d7wl4hnydqbqc2j1qg29sybpc614wkz8-rocm-path/lib/libhipblas.so.2 ']'
       > ++ readlink -f /nix/store/d7wl4hnydqbqc2j1qg29sybpc614wkz8-rocm-path/lib/libhipblas.so.2
       > + cp /nix/store/2c04lrnax0x0jcdrdins3wykm1lb1360-hipblas-6.0.2/lib/libhipblas.so.2.0 ../../dist/linux-amd64//../linux-amd64-rocm/lib/ollama
       > cp: '/nix/store/2c04lrnax0x0jcdrdins3wykm1lb1360-hipblas-6.0.2/lib/libhipblas.so.2.0' and '../../dist/linux-amd64//../linux-amd64-rocm/lib/ollama/libhipblas.so.2.0' are the same file
       > llm/generate/generate_linux.go:3: running "bash": exit status 1
       For full logs, run 'nix log /nix/store/61lr3bfvwm5nc3gk2adxsglkcwcxb23s-ollama-0.3.11.drv'.
```

### Notify maintainers

@abysssol 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.52, NixOS, 24.11 (Vicuna), 24.11.20240923.30439d9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.7`
 - nixpkgs: `/nix/store/p2hby44a0qzrnd1vxcpcgfav6160rmcv-source````

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SigmaSquadron** [comment] 2024-09-27 14:32
Duplicate of #344182 which was fixed in #344236 and has already reached `nixos-unstable`.

**Closed by SigmaSquadron** 2024-09-27 14:32 UTC
Labels: 0.kind: build failure
