### ISSUE TITLE
helmfile does not recognize helm plugins

### ISSUE THREAD

**Issue by sleiner** [NixOS/nixpkgs#217768] opened 2023-02-22 23:15 UTC
### Describe the bug
When trying to use [helmfile](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/networking/cluster/helmfile/default.nix#L32) from `nixos-unstable` (d0d55259081f0b97c828f38559cad899d351cad1 to be exact) with [environment secrets](https://helmfile.readthedocs.io/en/latest/#environment-secrets), helmfile will complain about a missing secrets plugin, even though it was installed with nix.

### Steps To Reproduce
1. Create three files:
    - **shell.nix**:
      ```nix
      { pkgs ? import <nixpkgs> {} }:
      pkgs.mkShell {
        buildInputs = [
          (pkgs.wrapHelm pkgs.kubernetes-helm {
            plugins = [
              pkgs.kubernetes-helmPlugins.helm-diff
              pkgs.kubernetes-helmPlugins.helm-secrets
            ];
          })
          pkgs.helmfile
        ];
      ```
    - **helmfile.yaml**
      ```yaml
      # This file is incomplete and foo.yaml will not contain valid secrets.
      # It works to reproduce this bug though :-)
      environments:
        default:
          secrets:
            - foo.yaml
      ```
    - **foo.yaml**: empty

2. Enter the developer shell: `$ nix-shell`
3. Ensure the plugins are installed `$ helm plugin list`
4. `$ helmfile apply`

### Expected behavior
In the case above, helmfile executes `helm secrets dec foo.yaml` (which would still fail).
However, actually we get as output:
```
Decrypting secret /some/path/helmfile/foo.yaml
plugin secrets not installed
plugin secrets not installed
in ./helmfile.yaml: failed to read helmfile.yaml: failed loading environment secrets with 1 errors
```

### Additional context
In version 0.146.0, [helmfile has introduced a check for plugin versions](https://github.com/helmfile/helmfile/pull/360/files#diff-cc23d827ce15a3ce002578cc0b18d846fd3614d59ac080c703bdd17881466795R89) which uses helm's Go API directly (instead of calling the `helm` binary). I suspect that the `helmfile` binary does not know about the helm plugins directory set up by nix (as opposed to the `helm` binary, which is [wrapped by nix](https://github.com/NixOS/nixpkgs/blob/988cc958c57ce4350ec248d2d53087777f9e1949/pkgs/applications/networking/cluster/helm/wrapper.nix)).

### Notify maintainers
@kliu128 
@yurrriq

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 22.3.0, macOS `
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by 06kellyjac** [comment] 2023-02-23 15:05
Maybe if the wrapper exposed `passtrhu.plugginsDir` you could just set the env var `HELM_PLUGINS` for the whole shell

Or this should work?

```nix
{ pkgs ? import <nixpkgs> {} }:
let
  helm-plugins-dir = pkgs.symlinkJoin {
    name = "helm-plugins";
    paths = with pkgs.kubernetes-helmPlugins; [
      helm-diff
      helm-secrets
    ];
  };
in
pkgs.mkShell {
  shellHook = ''
    export HELM_PLUGINS="${helm-plugins-dir}"
  '';
  buildInputs = [
    pkgs.kubernetes-helm
    pkgs.helmfile
  ];
```

**Comment by sleiner** [comment] 2023-02-23 18:54
Having `HELM_PLUGINS` set to the path set up by nix when `helmfile` is called fixes the issue, yes 👍🏻
And the snippet that you posted works and does that automatically - which is great, thanks @06kellyjac! :-)

Still, this does not seem like a proper fix to me... My expectation as a user of what _should_ be happening is: nix's helmfile should "just work" with nix's helm plugins, just as helm itself does. As a user, I do not have to take extra steps to get this to work.

A possible approach I can think of (without having any nix developer experience and only using it for a few hours):
- Wrap the `helmfile` command, just as the `helm` command is wrapped.
- In the wrapper, set `HELM_PLUGINS`.
- In order to not make this a weird one-off coupling between helmfile and helm and require the helm package to expose the plugins directory somehow, the wrapper could use the output of `helm env` to have both the `helmfile` and `helm` share the same environment information, regardless of whether it is the plugins directory or anything else that the helm wrapper might add.

What do you think, @06kellyjac? What do the maintainers think?

**Comment by 06kellyjac** [comment] 2023-02-23 19:31
If wrap helm could also take a list of things to wrap that might be good enough.

I worry that forcing helmfile to run helm env every time might be a bit too much

**Comment by sleiner** [comment] 2023-02-23 19:54
Good point, sounds sensible to me :-)

**Comment by yurrriq** [comment] 2023-05-01 15:06
Hmm.. I'm not able to reproduce the issue on ccde02e9ff2. Are you?

**flake.nix**:
```nix
{
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/ccde02e9ff2";

  outputs = { self, nixpkgs }:
    let
      pkgs = nixpkgs.legacyPackages.x86_64-linux;
    in
    {
      devShells.x86_64-linux.default = pkgs.mkShell {
        buildInputs = with pkgs; [
          helmfile
          (
            wrapHelm kubernetes-helm {
              plugins = with kubernetes-helmPlugins; [
                helm-diff
                helm-secrets
              ];
            }
          )
        ];
      };
    };
}
```

**helmfile.yaml**:
```yaml
environments:
  default:
    secrets:
      - foo.yaml
```

**foo.yaml**:
```yaml
# This file intentionally left blank.
```


```bash
$ nix develop --command helmfile template
...
  Error: plugin "secrets" exited with error
in ./helmfile.yaml: failed to read helmfile.yaml: failed loading environment secrets with 1 errors
```

**Comment by yurrriq** [comment] 2023-05-09 16:28
I do see this now using the same flake in a Docker container...
```
Pulling docker image nixpkgs/cachix-flakes ...
Using docker image sha256:4aa2cb389b920b79c02bfccc80e4f5860f146ef0d2974fa9ad123ddc5807873e for nixpkgs/cachix-flakes with digest nixpkgs/cachix-flakes@sha256:d0785ee0c4e5fb34000cb17fcd207f2ba3963d84e9de837ac5da2b9b20039163 ...
```

**Comment by yurrriq** [comment] 2023-05-09 17:13
Aha, so the trick is I had helm-secrets installed globally too in `~/.local/share/helm/plugins/helm-secrets`. I can now reproduce this locally. PR incoming :smile:

**Comment by yurrriq** [comment] 2023-07-26 22:00
Closing this as I've merged #231312. Please reopen or open an new issue as needed.

**Closed by yurrriq** 2023-07-26 22:00 UTC
Labels: 0.kind: bug

**Comment by icodeforyou-dot-net** [comment] 2023-08-07 20:13
@yurrriq just read through this, what exactly is the actual solution to this issue? Just get the new `helmfile-wrapped` derivation instead of `helmfile`? Or do I have to wrap my own `helmfile` like suggested in https://github.com/NixOS/nixpkgs/pull/231312#issuecomment-1557592291 ?

**Comment by yurrriq** [comment] 2023-08-09 21:03
@icodeforyou-dot-net that error looks like you don't have a recent enough nixpkgs. Could you share what you tried?

By default `kubernetes-helm-wrapped` does not include any plugins and `helmfile-wrapped` reads `kubernetes-helm-wrapped.passthru.pluginsDir`. Here's a minimal working example which should hopefully point you in the right direction. 

**flake.nix:**
```nix
{
  description = "A very basic flake";

  inputs.nixpkgs.url = "github:nixos/nixpkgs/697d5360";

  outputs = { self, nixpkgs }:
    let
      pkgs = import nixpkgs {
        overlays = [
          self.overlays.default
        ];
        system = "x86_64-linux";
      };
    in
    {
      overlays.default = final: prev: {
        kubernetes-helm-wrapped = prev.wrapHelm prev.kubernetes-helm {
          plugins = with prev.kubernetes-helmPlugins; [
            helm-diff
            helm-unittest
          ];
        };
      };

      devShells.x86_64-linux.default = pkgs.mkShell {
        nativeBuildInputs = with pkgs; [
          helmfile-wrapped
          kubernetes-helm-wrapped
        ];
      };
    };
}

```

**helmfile.yaml:**

```yaml
releases:
  - name: example
    version: 15.1.2
    chart: oci://registry-1.docker.io/bitnamicharts/nginx
```

Wrapped Helm knows about its plugins. This is nothing new.

```
λ nix develop -c helm plugin list --debug
plugin_list.go:35: [debug] pluginDirs: /nix/store/5sqj0gspblsli631fhdq3dzplcl8393j-helm-plugins
NAME    	VERSION	DESCRIPTION                                                                         
diff    	3.8.1  	Preview helm upgrade changes as a diff                                              
unittest	0.3.3  	Unit test for helm chart in YAML with ease to keep your chart functional and robust.
```

With access to a Kubernetes cluster and `~/.kube/config` set up correctly, `helmfile diff` works too, since I've added it to `kubernetes-helm-wrapped` whose `passthru.pluginsDir` is passed to `helmfile-wrapped` by default.

```
λ helmfile diff
Pulling registry-1.docker.io/bitnamicharts/nginx:15.1.2
Comparing release=example, chart=/tmp/nix-shell.xOTfsn/helmfile96282263/example/nginx/15.1.2/nginx
********************

	Release was not present in Helm.  Diff will show entire contents as new.

********************
...
```

**Comment by yurrriq** [comment] 2023-08-09 21:22
Another approach might be something like this.

```nix
{ helmfile-wrapped, kubernetes-helm, kubernetes-helmPlugins, mkShell, wrapHelm }:

let
  myHelm = wrapHelm kubernetes-helm {
    plugins = with kubernetes-helmPlugins; [
      helm-diff
    ];
  };

  myHelmfile = helmfile-wrapped.override {
    inherit (myHelm.passthru) pluginsDir;
  };
in
mkShell {
  nativeBuildInputs = [
    myHelm
    myHelmfile
  ];
}
```

**Comment by icodeforyou-dot-net** [comment] 2023-08-10 10:28
@yurrriq Thank you for the fast reply! You were indeed correct, even though I had updated my flake, my nixpkgs in the unstable channel were not up-to-date enough it seems. They now are.

Both your solutions work fine now. Running `helmfile init` picks up the plugins now, just complaining about `helm-git` being too outdated. But that is for another issue.

I have a feeling though I should translate my gratitude into creating a piece of documentation on nixos wiki for this. Afaik there is no documentation as of now on how to get up and running with `helm` and `helmfile` quickly. I will write that up in the coming days I think.

**Comment by yurrriq** [comment] 2023-08-13 08:46
I'm glad you got it working. Adding documentation would be awesome! I'll gladly review, if you @ me. Re: helm-git. Are you interested and willing to contribute a PR for that too? I'd be happy to review/test that as well.

**Comment by icodeforyou-dot-net** [comment] 2023-08-13 10:08
@yurrriq I will let you know once its up on NixOS wiki. Other might chime in as well commenting what I write up!

Since I haven't contributed to `nixpkgs` yet, I am interested, yes. Sounds like a nice first PR. But it might be a week or so before I get to it. So I hope it is not too urgent for anyone using `helm-git`.

**Comment by icodeforyou-dot-net** [comment] 2023-08-21 09:53
@yurrriq I made a wiki entry today. https://nixos.wiki/wiki/Helm_and_Helmfile ... I'd be happy to have some feedback once you have a free minute or two. I hope I'll be able to get the helm-git PR going soonish once i got the time myself.

**Comment by yurrriq** [comment] 2023-08-21 16:07
Thanks, it looks pretty good! I have some minor nitpicks that probably aren't worth discussing. But what's the strategy behind splitting `nativeBuildInputs` and `buildInputs` in the devShell examples? Doesn't it make better sense to have them all as `nativeBuildInputs` since we're building a dev environment?

**Comment by icodeforyou-dot-net** [comment] 2023-08-21 16:55
Thanks for the quick feedback! I think there is not much of a strategy there to be honest. I even believe that for making shells like this there is no technical difference between the two. In the back of my mind however I had saved somewhere that `buildInputs` is stuff you want available run-time, but `nativeBuildInputs` compile-time stuff. So I kinda separated the helm stuff out that I actually wanna work with inside the shell.

And the only reason why I put `bashInteractive` in there at all is that I use it in all shells where I might want to open `vscode` inside. Not sure if this is actually needed any longer.

**Comment by lucasfcnunes** [comment] 2026-04-16 22:40
What's the best way to make `my-helm` (with plugins) and `my-helmfile` available on `pkgs.my-*` via my top `flake.nix` for multiple machines?
