### ISSUE TITLE
pyspark - SyntaxError: invalid syntax - export PATH

### ISSUE THREAD

**Issue by InLaw** [NixOS/nixpkgs#96387] opened 2020-08-26 16:37 UTC
**Describe the bug**

**To Reproduce**
`nix-shell -p python37Packages.pyspark --run "pyspark "`
```
  File "/nix/store/40cvlpp1hv721gzj0q8fp7hi0fcsv5md-python3.7-pyspark-2.4.4/bin/find_spark_home.py", line 2
    export PATH='/nix/store/r94aa2gj4drkhfvkm2p4ab6cblb6kxlq-python3-3.7.6/bin:/nix/store/40cvlpp1hv721gzj0q8fp7hi0fcsv5md-python3.7-pyspark-2.4.4/bin'${PATH:+':'}$PATH
              ^
SyntaxError: invalid syntax
/nix/store/40cvlpp1hv721gzj0q8fp7hi0fcsv5md-python3.7-pyspark-2.4.4/bin/pyspark: line 24: /bin/load-spark-env.sh: No such file or directory
/nix/store/40cvlpp1hv721gzj0q8fp7hi0fcsv5md-python3.7-pyspark-2.4.4/bin/pyspark: line 77: /bin/spark-submit: No such file or directory
```

**Expected behavior**

**Notify maintainers**
@thoughtpolice 
@offline 
@kamilchm

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.10, NixOS, 20.03.2652.076c67fdea6 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200622_334e26b`
 - channels(ae): `"home-manager-20.03, home-manager-unstable, nixos-20.03.2652.076c67fdea6, nixpkgs-20.03.2652.076c67fdea6, unstableNix-20.09pre235652.7d557a5d1b3, unstableOS-20.09pre235279.5717d9d2f7c"`
 - nixpkgs: `/home/ae/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by edibopp** [comment] 2020-12-03 13:32
This is a duplicate of #64358, is it not? So I would suggest closing it in favor of the existing issue.

**Closed** 2020-12-05 07:42 UTC
Labels: 0.kind: bug, 6.topic: python
