### ISSUE TITLE
Build failure: python3.12Packages.python-on-whales fails pydantic dependency check

### ISSUE THREAD

**Issue by sarahec** [NixOS/nixpkgs#353040] opened 2024-11-02 02:15 UTC
### Steps To Reproduce

Steps to reproduce the behavior
1. Run any nixpkgs-review that triggers rebuilding python-on-whales (for example, python3Packages.aiohttp)
2. Observe:
```sh
       > adding 'python_on_whales-0.73.0.dist-info/LICENSE'
       > adding 'python_on_whales-0.73.0.dist-info/METADATA'
       > adding 'python_on_whales-0.73.0.dist-info/WHEEL'
       > adding 'python_on_whales-0.73.0.dist-info/entry_points.txt'
       > adding 'python_on_whales-0.73.0.dist-info/top_level.txt'
       > adding 'python_on_whales-0.73.0.dist-info/RECORD'
       > removing build/bdist.linux-x86_64/wheel
       > Successfully built python_on_whales-0.73.0-py3-none-any.whl
       > Finished creating a wheel...
       > Finished executing pypaBuildPhase
       > Running phase: pythonRuntimeDepsCheckHook
       > Executing pythonRuntimeDepsCheck
       > Checking runtime dependencies for python_on_whales-0.73.0-py3-none-any.whl
       >   - pydantic!=2.0.*,<3,>=2 not satisfied by version 1.10.16
```

It appears to be picking up the wrong pydantic.

### Notify maintainers

@bcdarwin
@natsukium has worked on differentiating pydantic 1 from 2

### Metadata

```sh
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.58, NixOS, 24.11 (Vicuna), 24.11.20241029.807e915`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixos-23.05"`
 - channels(sec): `""`
 - nixpkgs: `/nix/store/m68ikm8045fj7ys7qvgr608z9l70hh1k-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by sarahec** [comment] 2024-11-02 02:17
Seen as part of #351868 and #353002

**Comment by natsukium** [comment] 2024-11-02 04:30
I can't reproduce this build failure on master branch.
```
nix build github:nixos/nixpkgs/9b1431570776cf269afb38abf03ef7e9345cfa23#python312Packages.python-on-whales --rebuild
```

**Comment by dotlambda** [comment] 2024-11-02 05:39
Are you trying to build dbx? A fix similar to https://github.com/NixOS/nixpkgs/commit/1d1b7c6f37317 needs to be applied to that package.

**Comment by sarahec** [comment] 2024-11-02 18:19
> I can't reproduce this build failure on master branch.
> 
> ```
> nix build github:nixos/nixpkgs/9b1431570776cf269afb38abf03ef7e9345cfa23#python312Packages.python-on-whales --rebuild
> ```

This fails during `nixpkgs-review`, but not during `nix-build`.

**Comment by dotlambda** [comment] 2024-11-02 19:42
Closing because of a lack of details.

**Closed by dotlambda** 2024-11-02 19:42 UTC
Labels: 6.topic: python, 0.kind: build failure
