### ISSUE TITLE
currently c2hs can't cope with glibc-2.26

### ISSUE THREAD

**Issue by ikervagyok** [NixOS/nixpkgs#31433] opened 2017-11-09 11:04 UTC
it's an error in macro expansion for some glibc-code, discussed here: https://github.com/haskell/c2hs/issues/192

should be fixed upstream, this is just a reminder, to pull the update as soon as it's available

error log looks like this:
```
sudo nixos-rebuild boot -I nixpkgs=/home/bali/nixpkgs/stable.git -j 1 --show-trace                                                                                                                                                                                                      141 ↵
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/3mhs0ijv5ffsjyldi5v5yv6q7ksj5rgq-unit-script.drv
  /nix/store/05rk6zvmzk77xwc9q856l6b8yisz1cig-unit-network-setup.service.drv
  /nix/store/0b62awgk5a54rhlzxdg8dmzs0wr0cqix-useradd.drv
  /nix/store/0cfkmz65y155bx7lzgail1irdf7lcfcg-unit-systemd-journal-flush.service.drv
  /nix/store/0nxhlrni6m0iaczwha58mr365022kwl2-unit-udisks2.service.drv
  /nix/store/144jdimwfpvdamkwlhy54c67wis8fhm6-unit-fs.target.drv
  /nix/store/r9zknc1140v3adn8hwk82fjidw13ay7d-unit-script.drv
  /nix/store/15na11shhlkgcnb6skzyj7sary67cjvm-unit-update-locatedb.service.drv
  /nix/store/3m45h19j0wgf0d3n3rhzr5j7c5s3yn37-unit-script.drv
  /nix/store/162vpjln3vy0523qc7mwyc5vvdmbmqmj-unit-nixos-upgrade.service.drv
  /nix/store/1cpd5rkzv0fn2av1b1ir03rcavrdnrms-unit-script.drv
  /nix/store/f0vhmcx479h1pl6gzff746rl54c6frfp-unit-script.drv
  /nix/store/jd1dj06qzchn0vfa47xqiaqc28lz1h93-unit-script.drv
  /nix/store/mk7jy7bv38jpl6c9bqvfajw70i7w26lz-unit-script.drv
  /nix/store/1swpl51s2r1m9m9kw3hfq539k5gglzcv-unit-container-.service.drv
  /nix/store/1z7hy6hmjrc1rnbj1r2ca7nwdnq8m5sr-unit-serial-getty-.service.drv
  /nix/store/wb2xplfpldxchz3yp4dam5fqfr9n942k-unit-script.drv
  /nix/store/21c3n8cgf0kdaw0n6cq131gfi33xavpq-unit-prepare-kexec.service.drv
  /nix/store/q9iwvmy0hj292c5iw4yzyynb6pjg6psi-unit-script.drv
  /nix/store/s7fzfff81lmwrkn7p3vdssjksm2r9d64-unit-script.drv
  /nix/store/2av0v923vy2i1mdahrf4d4l32pdw8mfd-unit-display-manager.service.drv
  /nix/store/2bwjkf792mxssl5hwffpw24zfry4gds2-unit-rngd.service.drv
  /nix/store/2y7dqa115lz1msfwxxpd3vnxfrxg41ak-unit-systemd-journal-gatewayd.socket.drv
  /nix/store/2zgixi9cv344nq8xjhpvhb9rsgnb3y4l-unit-systemd-backlight-.service.drv
  /nix/store/3p7fhxb02fd2hk496pbjh2babfxjna8q-unit-script.drv
  /nix/store/40j2zxs1ngvr96292hpxb1lxdbaaazsv-userdel.pam.drv
  /nix/store/4f573xp5b2ybi7a1216i94d7dacx8s75-unit-alsa-store.service.drv
  /nix/store/4gcw00qya34wxkviay2fnkxli062qydx-unit-script.drv
  /nix/store/4xiddg3vp27fqhnffliq7g316bsy6yvy-unit-systemd-random-seed.service.drv
  /nix/store/k1c7hc6cl6xfzi08d89ycbxh3hcrsahd-texlive-xdvi.bin-2016.drv
  /nix/store/517j0k1yxbfkaia210ld8ggwxy3fbbvi-texlive-combined-2016.drv
  /nix/store/830qv2ccbz2npisccgvy2z0rjzlq7arl-sencha-bare-6.5.2.drv
  /nix/store/kd9ffkvq126slw70j7kw9fb6h3aq2774-sencha-6.5.2.drv
  /nix/store/wadlhbrkpccz2j1sln5wvgy78w113qgx-rambox-bare-0.5.13.drv
  /nix/store/59276krms8x0flw8grsv68bcyg0avz2l-rambox-0.5.13.drv
  /nix/store/5qk40dv53s93ry7q945w28r8f40rm892-unit-console-getty.service-disabled.drv
  /nix/store/7af10lkz8xn04gr805g8dhc6incjb1za-teamviewer-12.0.76279.drv
  /nix/store/9yjnrz8z0y1hfjczxp39bv2lyvwnsd4v-zathura-with-plugins-0.3.7.drv
  /nix/store/b2f11hi40wl5za7l653q7dgpvclllsfa-alsa-mixer-0.2.0.3.drv
  /nix/store/cb3s4mcbnjqfhxadg04ldi9w6ndr9bb3-xmonad-extras-0.13.1.drv
  /nix/store/y6rkpd9r62z4yk52iibhbkndynfhvk9s-ghc-8.0.2-with-packages.drv
  /nix/store/bvmay0xqwhnl01xrs2v9zaawcfwq4bk2-xmonad-with-packages.drv
  /nix/store/imizk7qv2z7cvycxw56d1f02qm62hxy7-nixos-version.drv
  /nix/store/jbzxd794pkxma8mqgkcq08y7ciwhacpd-xmobar-0.24.5.drv
  /nix/store/nmhksjp8pkk9971daq5yrxsz9f96naws-ghc-8.0.2-with-packages.drv
  /nix/store/9m5igkxlsaqg7sj2fzd5z1r5asv3yc83-system-path.drv
  /nix/store/5xaar63nvlfwgi6yq351814x8d3j8vpn-dbus-1.drv
  /nix/store/60gjybxsqb9zmkqcwsq7h7wbd6xl1izb-unit-mdmon-.service.drv
  /nix/store/zx1jdr5qk2vp7n0kmc251jz4xsfrmyyy-firmware.drv
  /nix/store/8qgiia0l7fm8jjirrpx7ckn7ndvy1xyr-etc-nixos.conf.drv
  /nix/store/afgnr3cpkv7g342q4sph9fkvv3q8ca6i-usermod.pam.drv
  /nix/store/b5axldck7aa231gm3m4v6c9fl0yy28x9-xsession.drv
  /nix/store/7v6vv7cjcc1gqah9kqmg5jhil1nscy25-desktops.drv
  /nix/store/95ys1msvd47mqzi36mp3zzxf6mmwxwrq-xserver.conf.drv
  /nix/store/vijfg4h09s9jvs2wwapadfw42rsiwinq-xserver-wrapper.drv
  /nix/store/brbdr52jhrd5fgqk6chw6vx1qnywnh91-lightdm.conf.drv
  /nix/store/ccimb75s5513g4djdw33mbjyab70x28x-users.conf.drv
  /nix/store/fxwckkckx8g1y96zc0pp9mjihg3ljh38-xscreensaver.pam.drv
  /nix/store/jq1xcxq1w1amnx8ipsh4hck785yiarjz-udev-rules.drv
  /nix/store/lm62rkm21gvgfd4cs008a16axhzb6j34-vlock.pam.drv
  /nix/store/mcjgph5kircimnngfcjmm1a7flpvbkhn-issue.drv
  /nix/store/mllvagsc76dsz7q6xibcb4xlgxkhq7h4-vconsole.conf.drv
  /nix/store/6k9xkv73l3bdpkmhjzxric60pkhxvxvj-unit-dbus.service.drv
  /nix/store/b3bj1123ymgiid5bqml6c14dmf71gzdi-unit-graphical-session.target.drv
  /nix/store/bsix5px687qxaj80a8xnii3nnj9n1b6z-unit-obex.service.drv
  /nix/store/hd3jfj0406i5syrlhfpk2rjakmy5iph8-unit-pulseaudio.socket.drv
  /nix/store/izll2vk8xnb80bvd35z4qx9f72y4nwf1-unit-pulseaudio.service.drv
  /nix/store/kaaq9q3hf3msgx5ychs3krj4ls1dpwvc-unit-dbus.socket.drv
  /nix/store/v5snhjy5r4xm7g756qf5asrbwkrh1a8d-user-units.drv
  /nix/store/wg6wgrn17frrw8fyf5kzr37sbjf9rmd1-useradd.pam.drv
  /nix/store/60yiikyq1rjm5bsahj1rqz5rg825ilig-unit-bluetooth.service.drv
  /nix/store/71q0shyp4fxnvb6gvj6y6p6jpdyb4yj5-unit-docker.socket.drv
  /nix/store/7693wfs83fhnr9afb1pw1rlcd0sz58lk-unit-network-interfaces.target.drv
  /nix/store/7k4fz6955ygfdmjglry8wqj5q90h8385-unit-systemd-timedated.service.drv
  /nix/store/7ynmpiq6b60br18zw3aiqmwqpcj6cq07-unit-systemd-timesyncd.service.drv
  /nix/store/iy3idq8a5hvsv2bn5wqwz3lzniffxq10-unit-script.drv
  /nix/store/8izdb0sqngxlmy6pdzypzdr9ai35d0xc-unit-sshd.service.drv
  /nix/store/91lh6rxbjs35kiqg800f7p4clw4x3chx-unit-mdadm-grow-continue-.service.drv
  /nix/store/h9cfbgz2bdjyb8n4hbxxv8skvlk9wljy-unit-script.drv
  /nix/store/9yzqgpliqis4s30g77m7pqc1nghdaais-unit-post-resume.service.drv
  /nix/store/a6f12k06h3wjadgxxd17i3gwcvdk1hi6-unit-save-hwclock.service.drv
  /nix/store/bxlvyhrsk8i44xlhrh6hf7vgwk3mmksf-unit-systemd-fsck-.service.drv
  /nix/store/bym9zw20sxas0bymx9hz594qgz9z7v8g-unit-update-locatedb.timer.drv
  /nix/store/cf2cq3iah9gnynp03q5j8lx6jyfxza41-unit-audit.service.drv
  /nix/store/cs5cqr5ac23dn5qcmcdbv5flfaanx4zv-unit-systemd-binfmt.service.drv
  /nix/store/cwl1m18zhkhdhczsy8qym1x3x35w6yy0-unit-post-resume.target.drv
  /nix/store/f0jk0l4h8yxhb8lc2s8f8j3mkk6k3cw2-unit-docker.service.drv
  /nix/store/gklnxfxh03jbz2wxf6bf9im20aavxbfg-unit-nix-optimise.service.drv
  /nix/store/b9pzak1rkiw1hrdsryr76599psbv43l7-unit-script.drv
  /nix/store/gkqclcxg8h9pwib8mdkbmbcf0w7b5l0g-unit-teamviewerd.service.drv
  /nix/store/aw6fj4n72ggdccbhwy7kpdgpf2r4d0vi-unit-script.drv
  /nix/store/h862h37kvnz7lbr21yxfq0ipgpw5i33x-unit-pre-sleep.service.drv
  /nix/store/85ikyry8pr5w5kd90yikrw72gx0vig41-unit-script.drv
  /nix/store/hbiglw8xh6vzxd0320pdwyggy73730fi-unit-docker-prune.service.drv
  /nix/store/dz0zprhqqlml3b53kf9dlk4d1ix9w75z-unit-script.drv
  /nix/store/hi64k6n0yv1cylsxsk5nsy4s12pzqmpa-unit-network-manager.service.drv
  /nix/store/i09fyd4lfmmqrrc6y56y58a3dqv8wlcn-unit-systemd-user-sessions.service.drv
  /nix/store/jcmlgzj4swxkcndk10dhdsgs7kwwf66g-unit-accounts-daemon.service.drv
  /nix/store/k0wnwhgvqmhx7va7xzg1crq7qkgnbqjg-unit-mdadm-shutdown.service.drv
  /nix/store/kh9apw456xbhr81gymxx9z2gf3q248p4-unit-container-getty-.service.drv
  /nix/store/kwjhjppaq6vlsngmmzjpiahi8ivgr00z-unit-user-.service.drv
  /nix/store/lyw7y8gy4wml2w72cspnfzgi9maj0shm-unit-systemd-update-utmp.service.drv
  /nix/store/m1bply2g9nzx5znw7jcickw0bnbwggvk-unit-systemd-journald.service.drv
  /nix/store/mmbf6ip2mz28p5pyn5lgygrxid64cca4-unit-network-online.target.drv
  /nix/store/nn158k8lrbhs4d8c70m37xhlv0pfy00j-unit-remote-fs.target.drv
  /nix/store/iyndcw2n9r7rm4sda130hnf9v8ygmhb0-unit-script.drv
  /nix/store/p38rbxs0f4fi0718w3y8dvbrb5aqskw9-unit-nscd.service.drv
  /nix/store/pc733k7plnxf7sha933am0mhwcg38vh2-unit-keys.target.drv
  /nix/store/pnmmnlg1y3jj32a3a7hc46bkm80yyzvj-unit-nix-daemon.socket.drv
  /nix/store/q7k752icvp4pspy0cknwjly7gr6nyr6q-unit-nix-daemon.service.drv
  /nix/store/qipfpm7aay5mlgdzh9kwln755a8zymyb-unit-systemd-vconsole-setup.service.drv
  /nix/store/qll73qjmjld4dg5y0n4qbyighr58xr19-unit-cups.service.drv
  /nix/store/rm3917fqishk8ka669cri1z6sih64hsg-unit-systemd-remount-fs.service.drv
  /nix/store/lv3j2bsyfsjvl6yn173hhfsi1jm0870b-unit-script.drv
  /nix/store/rnhfmvjq3xkg1j9m8rghhcj7f5dvxi3h-unit-network-local-commands.service.drv
  /nix/store/rva78vn5z7rwsx77gk6xjgp1xbhzppvz-unit-systemd-modules-load.service.drv
  /nix/store/v7m69gl5yah4b6ax1h6lgnvdnpwjgv58-unit-systemd-udevd.service.drv
  /nix/store/vdfflvb5b1dyr6fnbcnv1dv9491x2vjw-unit-polkit.service.drv
  /nix/store/w2a6l52b0p865cdk3m9xfjrzr75dn53s-unit-local-fs.target.drv
  /nix/store/wbk0xccap2bwdnhnfcca80igc7f7ana4-unit-systemd-sysctl.service.drv
  /nix/store/wrvdzkhg0ry3pgl1ffvc4zmv3q3rr8i9-unit-systemd-logind.service.drv
  /nix/store/yhd0f30qpwwws69x4g92xifvc3ris8qa-unit-nixos-upgrade.timer.drv
  /nix/store/yzxblli757l5a4afc9q96majyczwig12-unit-cpufreq.service.drv
  /nix/store/zcj2j71hkb10fypadncbwdxdya989gdh-unit-getty-.service.drv
  /nix/store/wclfdza65m4i339dmhv640d3jxvi1ixd-unit-script.drv
  /nix/store/zrinsl1c2rdyr33w9zh8phhpfxwq5mz1-unit-nix-gc.service.drv
  /nix/store/xp88d9b89ln8kw4rapcil6g008djn09n-system-units.drv
  /nix/store/ybw6r3iqj78dxaky8gmkrsp8w681f31s-xlock.pam.drv
  /nix/store/60y2rxbmw7jwx4c6k6q71rh4cyd04wg8-etc.drv
  /nix/store/7ap23702h5mg768p390shqpnq1s1bgyc-udev-rules.drv
  /nix/store/jadpzpz42dvdr2c7v0s0yw78s309x0m2-kernel-modules-shrunk.drv
  /nix/store/87qpi2gfi4nr2nazr33kf3agf75c6pyp-stage-1-init.sh.drv
  /nix/store/6h48k5ssv9psjj270qr60zi3j77d6ik2-initrd.drv
  /nix/store/8hlxylmvmdkwxdifpw9z6rmmn9kijksd-libtxc_dxtn-1.0.1.drv
  /nix/store/6in5mcklnjcymfwbn06sfd5w44y1qfmx-mesa-drivers+txc-17.2.4.drv
  /nix/store/a4an9dhzy8j7w839xz87kd0r656fdi9m-opengl-drivers-32bit.drv
  /nix/store/xqxahvwgdaga93ydbiblih7vz1r31qcq-xkb-validated.drv
  /nix/store/dgac3ghgwd75snaw4jc809y5imkfmssg-nixos-system-lb.matrix-18.03.git.5ba3ad5.drv
building path(s) ‘/nix/store/q3q6354gb87ma14qy8q00g6g9j3422pb-issue’
building path(s) ‘/nix/store/4g9r3p47g71ykpzdfg5cgary341cfd3s-alsa-mixer-0.2.0.3-doc’, ‘/nix/store/90461gry15k9swd9pbn0hn0y9yvar0fa-alsa-mixer-0.2.0.3’
setupCompilerEnvironmentPhase
Build with /nix/store/d7pa43zz28cxmmbnk8aw1fsdlwhizcmm-ghc-8.0.2.
unpacking sources
unpacking source archive /nix/store/kl0r7i7fxaygbjxm5r2mpmdk27m7s0gv-alsa-mixer-0.2.0.3.tar.gz
source root is alsa-mixer-0.2.0.3
setting SOURCE_DATE_EPOCH to timestamp 1452094992 of file alsa-mixer-0.2.0.3/Sound/ALSA/Mixer/Internal.chs
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-alsa-mixer-0.2.0.3.drv-0/package.conf.d -j3 -threaded
[1 of 1] Compiling Main             ( Setup.hs, /tmp/nix-build-alsa-mixer-0.2.0.3.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/90461gry15k9swd9pbn0hn0y9yvar0fa-alsa-mixer-0.2.0.3 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --docdir=/nix/store/4g9r3p47g71ykpzdfg5cgary341cfd3s-alsa-mixer-0.2.0.3-doc/share/doc --with-gcc=gcc --package-db=/tmp/nix-build-alsa-mixer-0.2.0.3.drv-0/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/90461gry15k9swd9pbn0hn0y9yvar0fa-alsa-mixer-0.2.0.3/lib/ghc-8.0.2/alsa-mixer-0.2.0.3 --ghc-option=-j3 --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-library-vanilla --enable-executable-dynamic --enable-tests --ghc-option=-split-sections --extra-include-dirs=/nix/store/vrw0852pd7nh9iabsa9c5i7vfl4jfwzc-alsa-lib-1.1.4.1-dev/include --extra-lib-dirs=/nix/store/vrw0852pd7nh9iabsa9c5i7vfl4jfwzc-alsa-lib-1.1.4.1-dev/lib --extra-lib-dirs=/nix/store/8afcvwgrgki3x20wrlnpa3lv52bzzz1k-alsa-lib-1.1.4.1/lib
Configuring alsa-mixer-0.2.0.3...
Dependency alsa-core ==0.5.*: using alsa-core-0.5.0.1
Dependency base ==4.*: using base-4.9.1.0
Dependency unix >=2.6 && <3: using unix-2.7.2.1
Using Cabal-1.24.2.0 compiled by ghc-8.0
Using compiler: ghc-8.0.2
Using install prefix:
/nix/store/90461gry15k9swd9pbn0hn0y9yvar0fa-alsa-mixer-0.2.0.3
Binaries installed in:
/nix/store/90461gry15k9swd9pbn0hn0y9yvar0fa-alsa-mixer-0.2.0.3/bin
Libraries installed in:
/nix/store/90461gry15k9swd9pbn0hn0y9yvar0fa-alsa-mixer-0.2.0.3/lib/ghc-8.0.2/alsa-mixer-0.2.0.3
Dynamic libraries installed in:
/nix/store/90461gry15k9swd9pbn0hn0y9yvar0fa-alsa-mixer-0.2.0.3/lib/ghc-8.0.2/x86_64-linux-ghc-8.0.2
Private binaries installed in:
/nix/store/90461gry15k9swd9pbn0hn0y9yvar0fa-alsa-mixer-0.2.0.3/libexec
Data files installed in:
/nix/store/90461gry15k9swd9pbn0hn0y9yvar0fa-alsa-mixer-0.2.0.3/share/x86_64-linux-ghc-8.0.2/alsa-mixer-0.2.0.3
Documentation installed in:
/nix/store/4g9r3p47g71ykpzdfg5cgary341cfd3s-alsa-mixer-0.2.0.3-doc/share/doc
Configuration files installed in:
/nix/store/90461gry15k9swd9pbn0hn0y9yvar0fa-alsa-mixer-0.2.0.3/etc
No alex found
Using ar found on system at:
/nix/store/yha4q7zgm6y0ci0b57a8hbmzwyvv1w44-binutils-2.28.1/bin/ar
Using c2hs version 0.28.2 found on system at:
/nix/store/q9s9v9nmr5k9ilwdmljh9pajpw4vwlrg-c2hs-0.28.2/bin/c2hs
No cpphs found
Using gcc version 6.4.0 given by user at:
/nix/store/yjh21h38fmw3i4h2b5r557p4ggbvrd0v-gcc-wrapper-6.4.0/bin/gcc
Using ghc version 8.0.2 found on system at:
/nix/store/d7pa43zz28cxmmbnk8aw1fsdlwhizcmm-ghc-8.0.2/bin/ghc
Using ghc-pkg version 8.0.2 found on system at:
/nix/store/d7pa43zz28cxmmbnk8aw1fsdlwhizcmm-ghc-8.0.2/bin/ghc-pkg
No ghcjs found
No ghcjs-pkg found
No greencard found
Using haddock version 2.17.3 found on system at:
/nix/store/d7pa43zz28cxmmbnk8aw1fsdlwhizcmm-ghc-8.0.2/bin/haddock
No happy found
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.67 found on system at:
/nix/store/d7pa43zz28cxmmbnk8aw1fsdlwhizcmm-ghc-8.0.2/bin/hpc
Using hsc2hs version 0.68.1 found on system at:
/nix/store/d7pa43zz28cxmmbnk8aw1fsdlwhizcmm-ghc-8.0.2/bin/hsc2hs
Using hscolour version 1.24 found on system at:
/nix/store/bx21s5qjz1l75kb40pjg8kkppj7gk3g1-hscolour-1.24.1/bin/HsColour
No jhc found
Using ld found on system at:
/nix/store/yjh21h38fmw3i4h2b5r557p4ggbvrd0v-gcc-wrapper-6.4.0/bin/ld
No lhc found
No lhc-pkg found
No pkg-config found
Using strip version 2.28 found on system at:
/nix/store/yha4q7zgm6y0ci0b57a8hbmzwyvv1w44-binutils-2.28.1/bin/strip
Using tar found on system at:
/nix/store/7lx6bha6l22vi5h9c31nri1p7rqs7v1d-gnutar-1.29/bin/tar
No uhc found
building
Building alsa-mixer-0.2.0.3...
Preprocessing library alsa-mixer-0.2.0.3...
c2hs: C header contains errors:

/nix/store/xd2mlzvlgmskbyyb33lz2vdq15k74xpr-glibc-2.26-75-dev/include/bits/floatn.h:73: (column 20) [ERROR]  >>> Syntax error !
  The symbol `_Float128' does not fit here.

builder for ‘/nix/store/b2f11hi40wl5za7l653q7dgpvclllsfa-alsa-mixer-0.2.0.3.drv’ failed with exit code 1
building path(s) ‘/nix/store/3zbg1f1gr9p739x7ajg4dl187mqq6c8c-firmware’
cannot build derivation ‘/nix/store/y6rkpd9r62z4yk52iibhbkndynfhvk9s-ghc-8.0.2-with-packages.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/jbzxd794pkxma8mqgkcq08y7ciwhacpd-xmobar-0.24.5.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/nmhksjp8pkk9971daq5yrxsz9f96naws-ghc-8.0.2-with-packages.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/bvmay0xqwhnl01xrs2v9zaawcfwq4bk2-xmonad-with-packages.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/9m5igkxlsaqg7sj2fzd5z1r5asv3yc83-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/b5axldck7aa231gm3m4v6c9fl0yy28x9-xsession.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/dgac3ghgwd75snaw4jc809y5imkfmssg-nixos-system-lb.matrix-18.03.git.5ba3ad5.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/dgac3ghgwd75snaw4jc809y5imkfmssg-nixos-system-lb.matrix-18.03.git.5ba3ad5.drv’ failed
```
### Steps to reproduce
rebuild with latest git checkout 5ba3ad5096a3f8f22999035016c211aaa2cf25c6 and probably any package using c2hs. this config fails for sure:

```
let
  haskell = pkgs.haskellPackages.ghcWithPackages (pkgs: with pkgs; [
    taffybar
    ghc-core
    attoparsec
    matrix
    numeric-quest
    vector-space
    hmatrix
    numeric-prelude
    criterion
#   easyplot
    ghc-mod
#   hakyll
    hoogle
#   loop-while
    mtl
    clock
    SHA
    network-simple
    dates
#   simplessh
#   libssh2
    xmobar
    parsec-numbers
    pandoc
#   idris_1_1_1
    idris
  ]);
in
  environment.systemPackages = [
    haskell ];
  services.xserver.windowManager.default = "xmonad";
  services.xserver.windowManager.xmonad.enable = true;
  services.xserver.windowManager.xmonad.enableContribAndExtras = true;
```

**Comment by NickHu** [comment] 2017-11-09 12:12
dupe of https://github.com/NixOS/nixpkgs/issues/31411

**Closed** 2017-11-09 13:00 UTC
