### ISSUE TITLE
Build failure: python311Packages.jaxlib hash mismatch

### ISSUE THREAD

**Issue by nixupp** [NixOS/nixpkgs#347928] opened 2024-10-11 13:35 UTC
### Steps To Reproduce

1. Set `cudaSupport = true`
2. Add `python311Packages.jaxlib` to system environment packages
3. `nixos-rebuild test`
4. Get the mismatch

### Build log

```log
error: hash mismatch in fixed-output derivation '/nix/store/wf16dhdpavb09vqssd0lvx622wy7n616-bazel-build-jaxlib-0.4.28-deps.tar.gz.drv':
         specified: sha256-VGNMf5/DgXbgsu1w5J1Pmrukw+7UO31BNU+crKVsX5k=
            got:    sha256-IjsUIfCLcZiAdwNAmM1ul0dxT6XAHpQCDNFnjIPp1gc=
```

### Additional context

This causes `python311Packages.faster-whisper` to fail to build and with it many neural network packages do not work (like open-webui)

There's a bug open for this (#346686). I have filed a new issue to have the label better reflect the issue.
### Notify maintainers

@ndl 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.56, NixOS, 24.05 (Uakari), 24.05.5627.1dfc201544fe`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos-24.05-small"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by tomodachi94** [comment] 2024-10-28 06:41
Duplicate of https://github.com/NixOS/nixpkgs/issues/321920

**Closed by tomodachi94** 2024-10-28 06:41 UTC
Labels: 6.topic: python, 0.kind: build failure, 6.topic: cuda
